### ISSUE TITLE
az network dns comands failure after upgrade to 2.50

### ISSUE THREAD

**Issue by mbv** [Azure/azure-cli#26814]
### Describe the bug

After upgrade on azure cli 2.50.0 stop working commands related to `az network dns`, Microsoft.Network is registered

```az provider list --output table
Namespace                                                RegistrationPolicy    RegistrationState    ProviderAuthorizationConsentState
-------------------------------------------------------  --------------------  -------------------  -----------------------------------
Microsoft.DomainRegistration                             RegistrationRequired  Registered
Microsoft.Network                                        RegistrationRequired  Registered
```

### Related command

az network dns record-set a show

### Errors

(NoRegisteredProviderFound) No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/A'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/A'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.

### Issue script & Debug output

cli.knack.cli: Command arguments: ['network', 'dns', 'record-set', 'a', 'show', '--resource-group', '{hidden}', '--zone-name', '{hidden}', '--name', '{hidden}', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x105b4de10>, <function OutputProducer.on_global_arguments at 0x105bdadd0>, <function CLIQuery.on_global_arguments at 0x105c44280>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'network': ['azure.cli.command_modules.network', 'azure.cli.command_modules.privatedns']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: network                   0.296       115       355
cli.azure.cli.core: privatedns                0.002        14        66
cli.azure.cli.core: Total (2)                 0.298       129       421
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 128 groups, 421 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : network dns record-set a show
cli.azure.cli.core: Command table: network dns record-set a show
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x1066ee8c0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/{hidden}/.azure/commands/2023-07-04.11-53-37.network_dns_record-set_a_show.66317.log'.
az_command_data_logger: command args: network dns record-set a show --resource-group {} --zone-name {} --name {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x106703250>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x1067e8f70>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x1067e9090>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x105bdae60>, <function CLIQuery.handle_query_parameter at 0x105c44310>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x1067e9000>]
cli.azure.cli.core.auth.persistence: build_persistence: location='/Users/{hidden}/.azure/msal_token_cache.json', encrypt=False
cli.azure.cli.core.auth.binary_cache: load: /Users/{hidden}/.azure/msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/{hidden}/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/{hidden}/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/{hidden}/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/{hidden}/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/{hidden}/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/{hidden}/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/{hidden}/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 8e5059c9-d3d9-49a8-8a7f-7087b90c8bbf
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/{hidden}/resourceGroups/{hidden}/providers/Microsoft.Network/dnsZones/{hidden}/A/{hidden}?api-version=2023-07-01-preview'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'a5c9117a-1a50-11ee-b595-9e15d7563ae2'
cli.azure.cli.core.sdk.policies:     'CommandName': 'network dns record-set a show'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --zone-name --name --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.50.0 (HOMEBREW) (AAZ) azsdk-python-core/1.26.0 Python/3.10.12 (macOS-13.4.1-arm64-arm-64bit)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/{hidden}/resourceGroups/{hidden}/providers/Microsoft.Network/dnsZones/{hidden}/A/{hidden}?api-version=2023-07-01-preview HTTP/1.1" 400 359
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'gateway'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'a36d0a08-fe1f-4235-8859-0d06dcfe7368'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'a36d0a08-fe1f-4235-8859-0d06dcfe7368'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SWEDENCENTRAL:20230704T095338Z:a36d0a08-fe1f-4235-8859-0d06dcfe7368'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 04 Jul 2023 09:53:38 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '359'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/A'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'."}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.50.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.50.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.50.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.50.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.50.0/libexec/lib/python3.10/site-packages/azure/cli/core/aaz/_command.py", line 149, in __call__
    return self._handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.50.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_show.py", line 27, in _handler
    self._execute_operations()
  File "/opt/homebrew/Cellar/azure-cli/2.50.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_show.py", line 67, in _execute_operations
    self.RecordSetsGet(ctx=self.ctx)()
  File "/opt/homebrew/Cellar/azure-cli/2.50.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/network/aaz/latest/network/dns/record_set/_show.py", line 91, in __call__
    return self.on_error(session.http_response)
  File "/opt/homebrew/Cellar/azure-cli/2.50.0/libexec/lib/python3.10/site-packages/azure/cli/core/aaz/_operation.py", line 332, in on_error
    raise HttpResponseError(response=response, error_format=error_format)
azure.core.exceptions.HttpResponseError: (NoRegisteredProviderFound) No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/A'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/A'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.

cli.azure.cli.core.azclierror: (NoRegisteredProviderFound) No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/A'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/A'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.
az_command_data_logger: (NoRegisteredProviderFound) No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/A'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/A'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x1066eeb00>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.877 seconds (init: 0.086, invoke: 0.791)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 4231 in cache
telemetry.check: Returns Positive.
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/opt/homebrew/Cellar/azure-cli/2.50.0/libexec/bin/python /opt/homebrew/Cellar/azure-cli/2.50.0/libexec/lib/python3.10/site-packages/azure/cli/telemetry/__init__.py /Users/{hidden}/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

output dns records info

### Environment Summary

azure-cli                         2.50.0

core                              2.50.0
telemetry                          1.0.8

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2

Python (Darwin) 3.10.12 (main, Jun 20 2023, 19:43:52) [Clang 14.0.3 (clang-1403.0.22.14.1)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by shajeena** [comment]
Even am facing this issue - Is there any ETA for the fix ?
he resource type 'dnszones' could not be found in the namespace 'Microsoft.Network' for api version '2023-07-01-preview'. The supported api-versions are '2015-05-04-preview,2016-04-01,2017-09-01,2017-09-15-preview,2017-10-01,2018-03-01-preview,2018-05-01'.

**Comment by jfortier** [comment]
I also ran into this issue today. I was required to remove latest azure-cli from homebrew and install via pip, since homebrew does not allow you to select a lower version! 

I ended up going a couple of releases back, and that was good enough for my purposes. Version 2.49.0 is also available.

```
brew remove azure-cli
pip3 install azure-cli==2.48.1
```

**Comment by shajeena** [comment]
I did:  dnf install azure-cli-2.49.0-1.el9 -y as a workaround instead of dnf install azure-cli -y it worked for me

**Comment by RajendraJadi** [comment]
Facing the same issue 

`ERROR: (NoRegisteredProviderFound) No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/CNAME'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.
Code: NoRegisteredProviderFound`

**Comment by adamcarter81** [comment]
We are also facing the same issue, it broke the deployment pipelines. Will specify a previous version in the build agents until this is resolved. Is there any ETA?

**Comment by MmAtBosch** [comment]
same issue here.
one more time... 
why is it always the DNS subcommand which is messed up?

**Comment by alexftr** [comment]
That version 2.50.0 has been rolled out to Microsoft hosted agents on Azure DevOps and now many of our pipelines fails.
With message:
ERROR: (NoRegisteredProviderFound) No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/CNAME'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'. Code: NoRegisteredProviderFound Message: No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/CNAME'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'. 

Downgrade is not an option because I need to do it in dozens of pipelines and it add 2.5 minutes extra time to run to each pipeline.

When do you plan to fix this issue.
Thanks.

**Comment by jorisscheppers** [comment]
Not sure if a human will get a ping if the bot is mentioned, but it's worth a shot:

@azure-client-tools-bot-prd you were quick to 'resolve' similar issues by linking to [#23985](https://github.com/Azure/azure-cli/issues/23985#issue-1383263012) but that issue applies to problems happening **inside** a sovereign cloud. This issue is happening on the global AzureCloud as well! I can't believe there are so few people complaining about this situation.

**Comment by mischavandenburg** [comment]
We are running into the same problems with many of our deployments in a large enterprise organisation due to this issue. 

`Message: No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.
`

Is there an ETA for the fix for this issue?

**Comment by markheath** [comment]
have just hit the same issue using the AzureCLI@2 task in Azure DevOps pipelines, which I don't think can easily be downgraded to a previous version of the CLI.

**Comment by marlowp** [comment]
We've encountered this issue kind of issue many times for various different CLI commands during the past 12 months (which is very disappointing). The following command also works for downgrading the Azure CLI on ubuntu-20.04 Azure DevOps hosted agents:

```yaml
- task: PowerShell@2
  displayName: 'Revert to az cli version 2.49.0'
  inputs:
    targetType: 'inline'
    pwsh: true
    script: |
      pip install -Iv azure-cli==2.49.0 --extra-index-url https://azurecliprod.blob.core.windows.net/edge
```

**Comment by lbruun** [comment]
What would a workaround for GitHub Workflow be?

**Comment by frederikreher** [comment]
> What would a workaround for GitHub Workflow be?

@lbruun  Adding this step to our workflow resolved our issue: 

```yml
- name: Downgrade azure-cli
  run: python3 -m pip install --upgrade --force azure-cli==2.49.0
```
