### ISSUE TITLE
"--public-network-access" option does not exist

### ISSUE THREAD

**Issue by nakamacchi** [Azure/azure-cli#26812]
### Describe the bug

"--public-network-access" option does not exist.

### Related command

az cosmosdb create

### Errors

unrecognized arguments: --public-network-access DISABLED

### Issue script & Debug output

az cosmosdb create --name ${TEMP_COSMOSDB_NAME}  --resource-group ${TEMP_RG_NAME} --public-network-access DISABLED --network-acl-bypass AzureServices --default-consistency-level Session --enable-free-tier false --locations regionName="${TEMP_LOCATION_NAME}" failoverPriority=0 isZoneRedundant=False

### Expected behavior

It seems that the right option is "--enable-public-network true/false"

### Environment Summary

azure-cli                         2.45.0 *

core                              2.45.0 *
telemetry                          1.0.8

Extensions:
monitor-control-service               0.3.0
connectedmachine                   0.5.1
containerapp                      0.3.22
scheduled-query                    0.5.1
application-insights              0.1.18
alertsmanagement                   0.2.3
guestconfig                        0.1.1
azure-firewall                    0.14.4
automanage                         0.1.2
virtual-wan                       0.2.15
account                            0.2.5
bastion                            0.2.3

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location '/opt/az/bin/python3'
Extensions directory '/home/nakama/.azure/cliextensions'

Python (Linux) 3.10.8 (main, Feb  3 2023, 09:43:57) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by nakamacchi** [comment]
https://learn.microsoft.com/ja-jp/cli/azure/cosmosdb?view=azure-cli-latest#az-cosmosdb-create
