### ISSUE TITLE
Support new value for PPG type parameter

### ISSUE THREAD

**Issue by ShivapriyaGujjarlapudi** [Azure/azure-cli#26829]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

[az ppg create](https://learn.microsoft.com/en-us/cli/azure/ppg?view=azure-cli-latest#az-ppg-create);
[az ppg update](https://learn.microsoft.com/en-us/cli/azure/ppg?view=azure-cli-latest#az-ppg-update)

### Resource Provider

Compute Resource Provider

### Description of Feature or Work Requested

Command: [az ppg create](https://learn.microsoft.com/en-us/cli/azure/ppg?view=azure-cli-latest#az-ppg-create); [az ppg update](https://learn.microsoft.com/en-us/cli/azure/ppg?view=azure-cli-latest#az-ppg-update)
Parameter: --type -t

Values Supported: "Standard"
New value requested to be supported: "Ultra"

Outcome: PPG create/update commands should now support both values "Standard" and "Ultra"

### Minimum API Version Required

NA

### Swagger PR link / SDK link

NA

### Target Date

2023-08-20

### PM Contact

sgujjarlapud

### Engineer Contact

rosingla

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
> Target Date
2023-08-20

@ShivapriyaGujjarlapudi The closest release date to `08-20` is `09-05`, so we plan to release it on `09-05`. Do you think this date meets your expectations?

**Comment by ShivapriyaGujjarlapudi** [comment]
Hi @***@***.***>,

Thanks for the heads-up. This sounds good to me, considering we are planning for private preview mid-EO September. Please let us know if by any chance this is re-prioritized to deliver sooner so that we can leave enough buffer for testing internally 😊

Regards,
Shivapriya

**Comment by ShivapriyaGujjarlapudi** [comment]
Hi @Shivapriya ***@***.***>,

Actually, we can keep the release time on 09-05, and before that, we can provide you with a private package through edge build<https://github.com/Azure/azure-cli/blob/dev/doc/try_new_features_before_release.md> for testing before release, what do you think of it?

Thanks,
Xing

From: Shivapriya ***@***.***>
Sent: 10 July 2023 12:11
To: ***@***.******@***.***>; ***@***.***>; Xing ***@***.***>
Cc: ***@***.***>; ***@***.***>
Subject: RE: [Azure/azure-cli] Support new value for PPG type parameter (Issue #26829)

Hi @***@***.***>,

Thanks for the heads-up. This sounds good to me, considering we are planning for private preview mid-EO September. Please let us know if by any chance this is re-prioritized to deliver sooner so that we can leave enough buffer for testing internally 😊

Regards,
Shivapriya
