### ISSUE TITLE
CLI Commands provide no feedback while executing

### ISSUE THREAD

**Issue by spboyer** [Azure/azure-cli#2682]
Need to implement some visual feedback while executing commands. Similar to other CLIs

Azure node version:

![npm-azure-cli](https://cloud.githubusercontent.com/assets/7681382/24523339/bd96e1b6-1560-11e7-848e-d22760ae4348.gif)

Docker Example:

![docker-cli](https://cloud.githubusercontent.com/assets/7681382/24523778/398b0c2e-1562-11e7-98e6-32aa2e541a7f.gif)

**Comment by tjprescott** [comment]
This was a deliberate design decision in the CLI. If you want more information, you can use --verbose. 

If that doesn't give you the right kinds of information you would expect, then please let us know.

**Comment by spboyer** [comment]
Should be `--versbose` default and should have  a `--quiet` option

**Comment by derekbekoe** [comment]
Related to https://github.com/Azure/azure-cli/issues/987.
As @tjprescott said, this was a deliberate design decision.

**Comment by spboyer** [comment]
Closing for duplicate of #987
