### ISSUE TITLE
Azure CLI 2.50.0 - az aks get-versions returns incomplete JSON

### ISSUE THREAD

**Issue by spr0ches** [Azure/azure-cli#26832]
### Describe the bug

Running az aks get-versions --location norwayeast on version 2.50.0 of the Azure CLI returns an incomplete JSON with missing information. 

Same error with --location westeurope

JSON returned:
{
  "values": [
    {
      "capabilities": {
        "supportPlan": [
          "KubernetesOfficial"
        ]
      },
      "isPreview": null,
      "patchVersions": {
        "1.24.10": {
          "upgrades": [
            "1.25.5",
            "1.25.6"
          ]
        },
        "1.24.9": {
          "upgrades": [
            "1.24.10",
            "1.25.5",
            "1.25.6"
          ]
        }
      },
      "version": "1.24"
    },
    {
      "capabilities": {
        "supportPlan": [
          "KubernetesOfficial"
        ]
      },
      "isPreview": null,
      "patchVersions": {
        "1.25.5": {
          "upgrades": [
            "1.25.6",
            "1.26.0",
            "1.26.3"
          ]
        },
        "1.25.6": {
          "upgrades": [
            "1.26.0",
            "1.26.3"
          ]
        }
      },
      "version": "1.25"
    },
    {
      "capabilities": {
        "supportPlan": [
          "KubernetesOfficial"
        ]
      },
      "isPreview": null,
      "patchVersions": {
        "1.26.0": {
          "upgrades": [
            "1.26.3",
            "1.27.1"
          ]
        },
        "1.26.3": {
          "upgrades": [
            "1.27.1"
          ]
        }
      },
      "version": "1.26"
    },
    {
      "capabilities": {
        "supportPlan": [
          "KubernetesOfficial",
          "AKSLongTermSupport"
        ]
      },
      "isPreview": null,
      "patchVersions": {
        "1.27.1": {
          "upgrades": []
        }
      },
      "version": "1.27"
    }
  ]
}

### Related command

az aks get-versions --location norwayeast

### Errors

No error messages received

### Issue script & Debug output

cli.knack.cli: Command arguments: ['aks', 'get-versions', '--location', 'norwayeast', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f22a12192d0>, <function OutputProducer.on_global_arguments at 0x7f22a11701f0>, <function CLIQuery.on_global_arguments at 0x7f22a0f8d3f0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'aks': ['azure.cli.command_modules.acs']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: acs                       0.019         6        48
cli.azure.cli.core: Total (1)                 0.019         6        48
cli.azure.cli.core: Loaded 6 groups, 48 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : aks get-versions
cli.azure.cli.core: Command table: aks get-versions
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f229ff66cb0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/retracted/.azure/commands/2023-07-06.15-49-07.aks_get-versions.6016.log'.
az_command_data_logger: command args: aks get-versions --location {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f229ff837f0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f229ffc9750>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f229ffc9870>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f22a1170280>, <function CLIQuery.handle_query_parameter at 0x7f22a0f8d480>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f229ffc97e0>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ContainerServiceClient
cli.azure.cli.core.auth.persistence: build_persistence: location='/home/retracted/.azure/msal_token_cache.json', encrypt=False
cli.azure.cli.core.auth.binary_cache: load: /home/retracted/.azure/msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/retracted/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/retracted/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/retracted/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/retracted/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/retracted/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/retracted/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/retracted/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 8a55dca4-2a73-490c-9686-ded8e83e8fdb
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/retracted/providers/Microsoft.ContainerService/locations/norwayeast/kubernetesVersions?api-version=2023-05-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'e0e74679-1c03-11ee-8cc9-6b109ea93bd3'
cli.azure.cli.core.sdk.policies:     'CommandName': 'aks get-versions'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--location --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.50.0 (DEB) azsdk-python-azure-mgmt-containerservice/24.0.0 Python/3.10.10 (Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/retracted/providers/Microsoft.ContainerService/locations/norwayeast/kubernetesVersions?api-version=2023-05-01 HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'bb2a28c1-b497-4b8a-a609-4e2fd193971c'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'f0b35d49-7b54-4af9-83ad-366a9e5c0dad'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Server': 'nginx'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'NORWAYEAST:20230706T134906Z:bb2a28c1-b497-4b8a-a609-4e2fd193971c'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 06 Jul 2023 13:49:05 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "values": [
   {
    "version": "1.25",
    "capabilities": {
     "supportPlan": [
      "KubernetesOfficial"
     ]
    },
    "patchVersions": {
     "1.25.5": {
      "upgrades": [
       "1.25.6",
       "1.26.0",
       "1.26.3"
      ]
     },
     "1.25.6": {
      "upgrades": [
       "1.26.0",
       "1.26.3"
      ]
     }
    }
   },
   {
    "version": "1.26",
    "capabilities": {
     "supportPlan": [
      "KubernetesOfficial"
     ]
    },
    "patchVersions": {
     "1.26.0": {
      "upgrades": [
       "1.26.3",
       "1.27.1"
      ]
     },
     "1.26.3": {
      "upgrades": [
       "1.27.1"
      ]
     }
    }
   },
   {
    "version": "1.27",
    "capabilities": {
     "supportPlan": [
      "KubernetesOfficial",
      "AKSLongTermSupport"
     ]
    },
    "patchVersions": {
     "1.27.1": {
      "upgrades": []
     }
    }
   },
   {
    "version": "1.24",
    "capabilities": {
     "supportPlan": [
      "KubernetesOfficial"
     ]
    },
    "patchVersions": {
     "1.24.10": {
      "upgrades": [
       "1.25.6",
       "1.25.5"
      ]
     },
     "1.24.9": {
      "upgrades": [
       "1.25.6",
       "1.24.10",
       "1.25.5"
      ]
     }
    }
   }
  ]
 }
cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x7f229ffaecb0>, <function _x509_from_base64_to_hex_transform at 0x7f229ffaed40>]
cli.knack.cli: Event: CommandInvoker.OnFilterResult []
{
  "values": [
    {
      "capabilities": {
        "supportPlan": [
          "KubernetesOfficial"
        ]
      },
      "isPreview": null,
      "patchVersions": {
        "1.25.5": {
          "upgrades": [
            "1.25.6",
            "1.26.0",
            "1.26.3"
          ]
        },
        "1.25.6": {
          "upgrades": [
            "1.26.0",
            "1.26.3"
          ]
        }
      },
      "version": "1.25"
    },
    {
      "capabilities": {
        "supportPlan": [
          "KubernetesOfficial"
        ]
      },
      "isPreview": null,
      "patchVersions": {
        "1.26.0": {
          "upgrades": [
            "1.26.3",
            "1.27.1"
          ]
        },
        "1.26.3": {
          "upgrades": [
            "1.27.1"
          ]
        }
      },
      "version": "1.26"
    },
    {
      "capabilities": {
        "supportPlan": [
          "KubernetesOfficial",
          "AKSLongTermSupport"
        ]
      },
      "isPreview": null,
      "patchVersions": {
        "1.27.1": {
          "upgrades": []
        }
      },
      "version": "1.27"
    },
    {
      "capabilities": {
        "supportPlan": [
          "KubernetesOfficial"
        ]
      },
      "isPreview": null,
      "patchVersions": {
        "1.24.10": {
          "upgrades": [
            "1.25.6",
            "1.25.5"
          ]
        },
        "1.24.9": {
          "upgrades": [
            "1.25.6",
            "1.24.10",
            "1.25.5"
          ]
        }
      },
      "version": "1.24"
    }
  ]
}
cli.knack.cli: Event: Cli.SuccessfulExecute []
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f229ff66ef0>]
az_command_data_logger: exit code: 0
cli.__main__: Command ran in 0.473 seconds (init: 0.078, invoke: 0.395)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3417 in cache
telemetry.check: Returns Positive.
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/bin/../../opt/az/bin/python3 /opt/az/lib/python3.10/site-packages/azure/cli/telemetry/__init__.py /home/retracted/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

Expecting the same JSON as with Azure CLI version 2.49.0

2.49.0 JSON:

{
  "id": "/subscriptions/retracted/providers/Microsoft.ContainerService/locations/norwayeast/orchestrators",
  "name": "default",
  "orchestrators": [
    {
      "default": null,
      "isPreview": null,
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.24.9",
      "upgrades": [
        {
          "isPreview": null,
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.24.10"
        },
        {
          "isPreview": null,
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.25.5"
        },
        {
          "isPreview": null,
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.25.6"
        }
      ]
    },
    {
      "default": null,
      "isPreview": null,
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.24.10",
      "upgrades": [
        {
          "isPreview": null,
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.25.5"
        },
        {
          "isPreview": null,
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.25.6"
        }
      ]
    },
    {
      "default": null,
      "isPreview": null,
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.25.5",
      "upgrades": [
        {
          "isPreview": null,
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.25.6"
        },
        {
          "isPreview": null,
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.26.0"
        },
        {
          "isPreview": null,
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.26.3"
        }
      ]
    },
    {
      "default": true,
      "isPreview": null,
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.25.6",
      "upgrades": [
        {
          "isPreview": null,
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.26.0"
        },
        {
          "isPreview": null,
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.26.3"
        }
      ]
    },
    {
      "default": null,
      "isPreview": null,
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.26.0",
      "upgrades": [
        {
          "isPreview": null,
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.26.3"
        },
        {
          "isPreview": true,
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.27.1"
        }
      ]
    },
    {
      "default": null,
      "isPreview": null,
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.26.3",
      "upgrades": [
        {
          "isPreview": true,
          "orchestratorType": "Kubernetes",
          "orchestratorVersion": "1.27.1"
        }
      ]
    },
    {
      "default": null,
      "isPreview": true,
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.27.1",
      "upgrades": null
    }
  ],
  "type": "Microsoft.ContainerService/locations/orchestrators"
}

### Environment Summary

azure-cli                         2.50.0

core                              2.50.0
telemetry                          1.0.8

Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/home/christian/.azure/cliextensions'

Python (Linux) 3.10.10 (main, Jun 29 2023, 11:09:14) [GCC 11.3.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@spr0ches Thanks for reaching out to us and reporting this issue. Could you please confirm if you have the `aks-preview` extension installed. If you don't please install this extension and then run the command again.

> **az extension add -n aks-preview**

After installing the aks-preview run the cli command `az aks get-versions --location norwayeast` and check if that helps.

**Comment by spr0ches** [comment]
@navba-MSFT Thanks for getting back to me.
The issue persists even after installing the aks-preview extension, the JSON looks the same with missing fields.

**Comment by FumingZhang** [comment]
Hey @spr0ches, the backend API used by this command is changed since `2.50.0` so the json response is not the same as it used to be.

We've noticed that the new API is missing field `default`, which is used to identify the current default k8s version. Besides this field, by `incomplete JSON`, is there any other information you think is missing?

**Comment by spr0ches** [comment]
Hi @FumingZhang 

I would expect the new backend API to return the same JSON as versions < 2.50.0.
You will find both the new and old JSON listed in the issue, but of the top of my head, isPreview, orchestratorType & orchestratorVersion are missing.

**Comment by irishtechie** [comment]
Seeing this issue as well. Following.

**Comment by drazkiewicz** [comment]
Problem indeed! Workaround for those who are looking for latest K8S version (not in preview) that can be deployed:
`az aks get-versions -l northeurope --query "values[?isPreview==null].patchVersions.keys(@) |[]| sort(@) | [-1]"`

**Comment by navba-MSFT** [comment]
@spr0ches As mentioned above the backend API used by this command is changed since 2.50.0 so the json response is not the same as it used to be. We've noticed that the new API is missing field default, which is used to identify the current default k8s version. We have identified the cause and planning to fix this issue. We might have this ship with next api-version.
