### ISSUE TITLE
Discrepancy in Documentation

### ISSUE THREAD

**Issue by gamullen** [Azure/azure-cli#26847]
### Describe the bug

The definition of "az afd origin create" shows the use of a parameter called "[--private-link-sub-resource-type]," but the following example shows:

"az afd origin create -g group --host-name example.contoso.com --profile-name profile --origin-group-name originGroup --origin-name origin1 --origin-host-header example.contoso.com --priority 1 --weight 500 --enabled-state Enabled --http-port 80 --https-port 443 --private-link-resource /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group/providers/Microsoft.Storage/storageAccounts/plstest --private-link-location EastUS --private-link-request-message 'Please approve this request' **--private-link-sub-resource table**"

### Related command

az afd origin create

### Errors

NA

### Issue script & Debug output

NA

### Expected behavior

Fix docs.

### Environment Summary

Latest

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by SaurabhSharma-MSFT** [comment]
@gamullen The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
