### ISSUE TITLE
az rest --method patch for https://graph.microsoft.com/v1.0/applications/ does not parse json body correctly

### ISSUE THREAD

**Issue by notaturkey** [Azure/azure-cli#26848]
### Describe the bug

currently trying to add redirect urls to single page applications from azure cli using bash.

e.g:
```
map["https://localhost123"]=""

echo "The following SPA redirect URLs will be in place:"
echo "${!map[@]}"
urls=$(printf '%s\n' "${!map[@]}" | jq -R . | jq -s .)
echo $urls
body=$(cat <<EOF
{
"spa": {
    "redirectUris": $urls
    }
}
EOF
)

echo "$body" | jq -c .

az rest --method patch --uri "https://graph.microsoft.com/v1.0/applications/$id" \
  --headers "Content-Type: application/json" \
  --body "$(echo "$body" | jq -c .)"
```

it for sure is passing a valid json string to he body, ive tried without qoutes as well.  it gives me this error: `File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/util.py", line 885, in send_raw_request
    key, value = s.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)` 

strangely enough i got this working on my mac using powershell core 7:
```
$map["https://localhost123"] = ""
echo "The following spa redirect urls will be in place:"
echo $map.Keys
$urls = $map.Keys


$body=@{
  spa=@{
    redirectUris=$urls
  }
}

echo $body
echo $body | ConvertTo-Json -Depth 3

az rest --method patch --uri "https://graph.microsoft.com/v1.0/applications/$id" `
    --headers Content-Type="application/json" `
    --body "$($body | ConvertTo-Json -Depth 3)"
```

but i cant for the life of me get it working as a powershell or powershell core script in azure devops. Very frustrating!

### Related command

az rest --method patch 

### Errors

File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/util.py", line 885, in send_raw_request key, value = s.split('=', 1) ValueError: not enough values to unpack (expected 2, got 1

### Issue script & Debug output

['rest', '--method', 'patch', '--uri', 'https://graph.microsoft.com/v1.0/applications/e1bf7f37-2a9f-4d73-8613-587f9d020165', '--headers', 'Content-Type: application/json', '--debug', '--body', '{"spa":{"redirectUris":["https://localhost:7039/signout-oidc"]}}']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x108c4a440>, <function OutputProducer.on_global_arguments at 0x108cff520>, <function CLIQuery.on_global_arguments at 0x108d349d0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'rest': ['azure.cli.command_modules.util']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: util                      0.006         3         7
cli.azure.cli.core: Total (1)                 0.006         3         7
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0  
cli.azure.cli.core: Loaded 3 groups, 7 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : rest
cli.azure.cli.core: Command table: rest
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x10975b880>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/notaturkey/.azure/commands/2023-07-07.15-55-10.rest.4606.log'.
az_command_data_logger: command args: rest --method {} --uri {} --headers {} --debug --body {}
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x1097783a0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x10979a0e0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x10979a200>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x108cff5b0>, <function CLIQuery.handle_query_parameter at 0x108d34a60>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x10979a170>]
cli.azure.cli.core.util: invalid syntax (<unknown>, line 1)
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/util.py", line 574, in shell_safe_json_parse
    return json.loads(json_or_dict_string, strict=strict)
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/util.py", line 882, in send_raw_request
    temp = shell_safe_json_parse(s)
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/util.py", line 600, in shell_safe_json_parse
    raise InvalidArgumentValueError(msg, recommendation=recommendation) from json_ex
azure.cli.core.azclierror.InvalidArgumentValueError: Failed to parse string as JSON:
Content-Type: application/json
Error detail: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/util/custom.py", line 24, in rest_call
    r = send_raw_request(cmd.cli_ctx, method, url, headers, uri_parameters, body,
  File "/usr/local/Cellar/azure-cli/2.49.0/libexec/lib/python3.10/site-packages/azure/cli/core/util.py", line 885, in send_raw_request
    key, value = s.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)

### Expected behavior

itd add a single page application url to my app registration

### Environment Summary

azure-cli                         2.49.0 *

core                              2.49.0 *
telemetry                          1.0.8

Extensions:
azure-devops                      0.26.0
containerapp                      0.3.28
log-analytics                      0.2.2

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
It looks like the error is caused by `--headers "Content-Type: application/json"`. It should be `--headers "Content-Type=application/json"`. Please see https://github.com/Azure/azure-cli/issues/21758#issuecomment-1075996521.

Also, could you share how `map` is constructed in Bash? `map["https://localhost123"]=""` can't be executed directly:

```
$ map["https://localhost123"]=""
-bash: https://localhost123: syntax error in expression (error token is "://localhost123")
```

**Comment by notaturkey** [comment]
That worked for bash thanks!

for powershell im still confused whats going on though, thats what i was originally trying to implement it with. headers are formatted that way in the snippet i provided, i wrapped them in quotes ( `--headers "Content-Type=application/json"` ) to be sure but it still doesnt work running for both powershell and powershell core on a azure devops agent. At this point im confused why it works running on my mac with PowerShell 7.3.4

for powershell the map would be declared like so:
```
$id = ""
$map = @{}
$map["https://localhost123"] = ""
echo "The following spa redirect urls will be in place:"
echo $map.Keys
$urls = $map.Keys


$body=@{
  spa=@{
    redirectUris=$urls
  }
}

echo $body
echo $body | ConvertTo-Json -Depth 3

az rest --method patch --uri "https://graph.microsoft.com/v1.0/applications/$id" `
    --headers "Content-Type=application/json" `
    --body "$($body | ConvertTo-Json -Depth 3)"
    ```

bash:
```
declare -A map
map["https://localhost123"]=""

echo "The following SPA redirect URLs will be in place:"
echo "${!map[@]}"
urls=$(printf '%s\n' "${!map[@]}" | jq -R . | jq -s .)
echo $urls
body=$(cat <<EOF
{
"spa": {
    "redirectUris": $urls
    }
}
EOF
)

echo "$body" | jq -c .

az rest --method patch --uri "https://graph.microsoft.com/v1.0/applications/$id" \
  --headers "Content-Type=application/json" \
  --body "$(echo "$body" | jq -c .)"
```

**Comment by jiasli** [comment]
@notaturkey I am glad it is now working for you.

Actually, you don't need to specify header `Content-Type` at all if the body is a valid JSON.

If you add `--debug` flag to the command, you will see you are hitting [PowerShell quoting issue](https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md) as `--body` is not passed correctly. 

```
> az --debug rest --method patch --uri "https://graph.microsoft.com/v1.0/applications/$id" `
>>     --headers "Content-Type=application/json" `
>>     --body "$($body | ConvertTo-Json -Depth 3)"
cli.knack.cli: Command arguments: ['--debug', 'rest', '--method', 'patch', '--uri', 'https://graph.microsoft.com/v1.0/applications/', '--headers', 'Content-Type=application/json', '--body', '{']
```

I would really recommend using the `@<file>` convention to either read from `stdin` or a local temporary file. See https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md#best-practice-use-file-input-for-json

```
> echo $body | ConvertTo-Json -Depth 3 | az rest --method patch --uri "https://graph.microsoft.com/v1.0/applications/$id" --body "@-" --debug
...
cli.azure.cli.core.util: Request URL: 'https://graph.microsoft.com/v1.0/applications/'
cli.azure.cli.core.util: Request method: 'PATCH'
cli.azure.cli.core.util: Request headers:
cli.azure.cli.core.util:     'User-Agent': 'python/3.10.10 (Windows-10-10.0.22621-SP0) AZURECLI/2.50.0 (MSI)'
cli.azure.cli.core.util:     'Accept-Encoding': 'gzip, deflate'
cli.azure.cli.core.util:     'Accept': '*/*'
cli.azure.cli.core.util:     'Connection': 'keep-alive'
cli.azure.cli.core.util:     'x-ms-client-request-id': '47a0241e-2b3e-4e92-8a2a-86c21060d43a'
cli.azure.cli.core.util:     'Content-Type': 'application/json'
cli.azure.cli.core.util:     'CommandName': 'rest'
cli.azure.cli.core.util:     'ParameterSetName': '--method --uri --body --debug'
cli.azure.cli.core.util:     'Authorization': 'Bearer eyJ0eXAiOiJKV...'
cli.azure.cli.core.util:     'Content-Length': '51'
cli.azure.cli.core.util: Request body:
cli.azure.cli.core.util: {"spa": {"redirectUris": ["https://localhost123"]}}
```

**Comment by notaturkey** [comment]
awesome thanks for the help!
