### ISSUE TITLE
[Document Modification Request] az iot hub routing-endpoint create

### ISSUE THREAD

**Issue by tkudo-ms** [Azure/azure-cli#26841]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az iot hub routing-endpoint create

### Resource Provider

N/A

### Description of Feature or Work Requested

MY customer has requested a document correction.

- Target Documents
https://learn.microsoft.com/en-us/cli/azure/iot/hub/routing-endpoint?view=azure-cli-latest#az-iot-hub-routing-endpoint-create

- Corrections
```
  - name: Add a new endpoint "S1" of type AzureStorageContainer to "MyIotHub" IoT Hub. And "S1" of Resource Group is "RGS1".
    text: |
        az iot hub routing-endpoint create --resource-group MyResourceGroup --hub-name MyIotHub \\
        --endpoint-name S1 --endpoint-type azurestoragecontainer --endpoint-resource-group RGS1 \\
        --endpoint-subscription-id {SubscriptionId} --connection-string {ConnectionString} \\
        --container-name {ContainerName} --batch-frequency 100 --chunk-size 100 \\
        --ff {iothub}-{partition}-{YYYY}-{MM}-{DD}-{HH}-{mm}
```

### Minimum API Version Required

N/A

### Swagger PR link / SDK link

N/A

### Request Example

N/A

### Target Date

N/A

### PM Contact

N/A

### Engineer Contact

tkudo

### Additional context

N/A

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@tkudo-ms Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by vilit1** [comment]
Copying Paymaun's response in the above pr: 
> Just FYI, the `az iot hub routing-endpoint` command group is deprecated. The user should be pointed to the `az iot hub message-endpoint` and `az iot hub message-route` command groups in the [`azure-iot` extension](https://learn.microsoft.com/en-us/cli/azure/iot/hub/message-endpoint?view=azure-cli-latest).
> 
> Here is an MS learning doc link https://learn.microsoft.com/en-us/azure/iot-hub/how-to-routing-azure-cli?tabs=azurestorage

**Comment by navba-MSFT** [comment]
@tkudo-ms I am following up to check if you had a chance to look at the above comment and share this suggestion with the customer.
