### ISSUE TITLE
Error installing azure cli on ubuntu using install-azure-cli-linux script

### ISSUE THREAD

**Issue by zackyaz** [Azure/azure-cli#26884]
### Describe the bug

failed to install azure cli on Ubuntu 20.04.6 using the script described in option 1 of the azure cli documentation. https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-1-install-with-one-command

### Related command

curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

### Errors

Err:2 https://packages.microsoft.com/repos/azure-cli focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF

### Issue script & Debug output

installation error

### Expected behavior

install azure-cli

### Environment Summary

latest version 2.50.0

### Additional context

try also with Step-by-step installation instructions
failed on the same error in the 

4) Update repository information and install the azure-cli package:
sudo apt-get update

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
I can't repro.
No idea why microsoft key is missing.
You may follow the steps in https://github.com/dotnet/core/issues/7017 to fix it.

**Comment by zackyaz** [comment]
Hi

thanks, I follow the https://github.com/dotnet/core/issues/7017 and it works for me.

however, I look again in my code and found the following
I run the the command
curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
it works ok but the access to the file /etc/apt/trusted.gpg.d/microsoft.gpg was 600 then change it to 644 it was worked

Regards Zacky

**Comment by wannadream** [comment]
@bebound 
I ran into the same problem here. Here is my environment.
![image](https://github.com/Azure/azure-cli/assets/6989212/7a8b0c05-2a15-435e-b739-d9d6ded199e2)
![image](https://github.com/Azure/azure-cli/assets/6989212/b2ed1d5d-b18a-4b2b-9695-766a279e633d)
![image](https://github.com/Azure/azure-cli/assets/6989212/1aa4766d-b47a-453f-9f8e-8ffe983d50b6)
![image](https://github.com/Azure/azure-cli/assets/6989212/a0a37c6f-ae02-47f4-aa98-1a0f07a73750)

**Comment by wannadream** [comment]
@yonzhan @bebound 
Could you help taking another look at this?

**Comment by bebound** [comment]
If the previous comments does not work, try https://askubuntu.com/questions/1433368/how-to-solve-gpg-error-with-packages-microsoft-com-pubkey

**Comment by wannadream** [comment]
> If the previous comments does not work, kindly try https://askubuntu.com/questions/1433368/how-to-solve-gpg-error-with-packages-microsoft-com-pubkey

No luck. :(
![image](https://github.com/Azure/azure-cli/assets/6989212/93de831f-da6b-4f46-890f-ea205098ab76)
![image](https://github.com/Azure/azure-cli/assets/6989212/a2140cc8-e374-467a-9538-cea7b1c6d375)

**Comment by bebound** [comment]
What's the output of `ls -la /etc/apt/keyrings/microsoft.gpg`?

**Comment by wannadream** [comment]
> What's the output of `ls -la /etc/apt/keyrings/microsoft.gpg`?

![image](https://github.com/Azure/azure-cli/assets/6989212/10d70996-581d-4a29-998a-7b1b444d612d)

**Comment by bebound** [comment]
How about `apt-key list | grep 9CF`?
It should print `BC52 8686 B50D 79E3 39D3  721C EB3E 94AD BE12 29CF`

**Comment by wannadream** [comment]
> How about `apt-key list | grep 9CF`? It should print `BC52 8686 B50D 79E3 39D3 721C EB3E 94AD BE12 29CF`, [dotnet/core#7017](https://github.com/dotnet/core/issues/7017) should add it successfully.

![image](https://github.com/Azure/azure-cli/assets/6989212/cbdeeecf-284b-45c9-9bce-590cfd201f3c)

**Comment by bebound** [comment]
What's the output of `apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EB3E94ADBE1229CF`?

**Comment by bebound** [comment]
I have no solution to this, as it's out of CLI's scope.
You may ask Ubuntu community about this.

**Comment by wannadream** [comment]
> I have no solution to this, as it's out of CLI's scope. You may ask Ubuntu community about this.

For some reasons, below script worked:
`curl -sL https://packages.microsoft.com/keys/microsoft.asc |
gpg --dearmor |
sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null`
Official installation script grabs the key to /etc/apt/keyrings/ folder. It may be a corner case in Ubuntu 20.04?
