### ISSUE TITLE
az network application-gateway waf-policy does not support Bot 1.0 ruleset

### ISSUE THREAD

**Issue by kosti365GM** [Azure/azure-cli#26888]
**Related command**
`az network application-gateway waf-policy managed-rule rule-set update --policy-name <> --resource-group <> --type 'Microsoft_BotManagerRuleSet' --version '1.0'`

`az network application-gateway waf-policy managed-rule rule-set add --policy-name <> --resource-group <> --type 'Microsoft_BotManagerRuleSet' --version '1.0'`

Ref: https://azure.microsoft.com/en-us/updates/general-availability-bot-manager-rule-set-10-on-regional-azure-web-application-firewall/

**Error**
_az network application-gateway waf-policy managed-rule rule-set add: '1.0' is not a valid value for '--version'. Allowed values: 0.1, 2.2.9, 3.0, 3.1, 3.2._

**Is your feature request related to a problem? Please describe.**
Attempting to script out the update of App Gateway WAF policies from the 0.1 managed ruleset for bot protection --> 1.0. Does not seem to be an allowed input.

**Describe the solution you'd like**
Add 1.0 as an allowed input

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
> Hi @yonzhan, I see the issue added to a backlog - is that for triaging or was the issue already reproduced?

Correct, it's triaged and in the process of planning.
