### ISSUE TITLE
Wrong documentation for conditions

### ISSUE THREAD

**Issue by JoakimNylundOP** [Azure/azure-cli#26881]
### Describe the bug

    --condition "avg Percentage CPU > 90" --window-size 5m --evaluation-frequency 1m \ is wrong. The actual syntax is: 
   --condition "avg CpuPercentage > 90" --window-size 5m --evaluation-frequency 1m \. I have seen this syntax error in multiple documentation pages about az monitor metrics alert. 

### Related command

az monitor metrics alert

### Errors

If typed into the CLI: 
(BadRequest) Couldn't find a metric named Percentage CPU. Make sure the name is correct.
Code: BadRequest

### Issue script & Debug output

(BadRequest) Couldn't find a metric named Percentage CPU. Make sure the name is correct.
Code: BadRequest

### Expected behavior

Adjusted documentation.

### Environment Summary

azure-cli                         2.50.0

core                              2.50.0
telemetry                          1.0.8

Extensions:
ai-examples                        0.2.5
ml                                2.18.0
ssh                                1.1.6

Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by JoakimNylundOP** [comment]
> Hi @JoakimNylundOP,
> 
> This is not the official Azure CLI published by Microsoft.
> 
> How to tell if the installed Azure CLI is unofficial:
> 
>     * [Unofficial Azure CLI deb packages are distributed by Linux repositories #19640 (comment)](https://github.com/Azure/azure-cli/issues/19640#issuecomment-1133875268)
> 
>     * [Unofficial Azure CLI deb packages are distributed by Linux repositories #19640 (comment)](https://github.com/Azure/azure-cli/issues/19640#issuecomment-1148202854)
> 
> 
> Please follow https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux to install Microsoft official Azure CLI.
> 
> If you feel that further discussion is needed, please add a comment with the text `/clibot unresolve` to reopen the issue.

/clibot unresolve
