### ISSUE TITLE
learn the ETA of the latest Version CLI

### ISSUE THREAD

**Issue by Bonn-ws** [Azure/azure-cli#26894]
Hi Team,

Hope things are going well. 

I would like to learn the ETA of the latest Version CLI.

Recently, Some customers meet similar issue in using Windows CLI to  export/import DNS zone

az network dns zone import -g eitb_dns -n eitb.eus --file eitb.eus.txt 
az network private-dns zone export -g myresourcegroup -n contoso.com -f contoso.com.txt

They get same error message:

(NoRegisteredProviderFound) No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/recordsets'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'global' and API version '2023-07-01-preview' for type 'dnszones/recordsets'. The supported api-versions are '2015-05-04-preview, 2016-04-01, 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.

I have found the possible workaround in this link and help customer resolve it by installing previous version windows CLI 2.24.0 and 2.49.0.
[Listing DNS entries fails, expecting 2023-07-01-preview API version to be present. · Issue #26813 · Azure/azure-cli · GitHub](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-cli%2Fissues%2F26813&data=05%7C01%7Cv-bowenli%40microsoft.com%7Ca27ae39a377e42f4f4cf08db83f39168%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638248854409784160%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1yCUSgLtfO5wA4fhkvHzvNJLcS61uDwlh12x9eScz7E%3D&reserved=0)

But they want to know the ETA of the latest version windows CLI to support '2023-07-01-preview' API, could you help in it?

Thank you very much for your reply!

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by Bonn-ws** [comment]
I would like to learn the ETA of the latest Version CLI.

**Comment by Bonn-ws** [comment]
@yonzhan Hi Team, hope things are going well. Do you have any suggestion in it?

**Comment by Bonn-ws** [comment]
/clibot unresolve
Hi team, hope things are going well. Do you have the ETA of the latest version?

**Comment by Bonn-ws** [comment]
Hi team, hope things are going well. Do you have the ETA of the latest version? Thanks for your reply

**Comment by necusjz** [comment]
@Bonn-ws After DNS team fix it, the next release date could be found in https://github.com/Azure/azure-cli/milestone/132.

**Comment by RobinZergiebel** [comment]
We are also experiencing this issue right now - what is the progress on this? Can we at least roll back the azure cli version on the hosted agents to version 2.49.0 until this issue is resolved?

**Comment by necusjz** [comment]
> We are also experiencing this issue right now - what is the progress on this? Can we at least roll back the azure cli version on the hosted agents to version 2.49.0 until this issue is resolved?

Will be resolved around 08/01 by 2.51.0.
