### ISSUE TITLE
az network dns record-set txt add-record doesn;t support

### ISSUE THREAD

**Issue by Greedygre** [Azure/azure-cli#26893]
### Describe the bug

I test my extension integration test with azure-cli dev branch, found the command `az network dns record-set txt add-record `was working before with `api-version=2018-05-01` but not now with `api-version=2023-07-01-preview`.

self.cmd('network dns record-set txt add-record -g {} -z {} -n {} -v {}'.format(resource_group, zone_name, txt_name_1, verification_id)).get_output_in_json()

### Related command

az network dns record-set txt add-record -g clitest.rgknofmyvztmwm37vdxoxguz5tfxlbp66v6jm4ho6l3lo7jfyuqtmykwuowx6lrhdgm -z {} -n {} -v {}

### Errors

(NoRegisteredProviderFound) No registered resource provider found for location 'global' and API ver... 2017-09-01, 2017-09-15-preview, 2017-10-01, 2018-03-01-preview, 2018-05-01'. The supported locations are ', global'.

### Issue script & Debug output

self.cmd('network dns record-set txt add-record -g {} -z {} -n {} -v {}'.format(resource_group, zone_name, txt_name_1, verification_id)).get_output_in_json()
azext_containerapp\tests\latest\test_containerapp_commands.py:272:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  
..\..\..\azure-cli\src\azure-cli-testsdk\azure\cli\testsdk\base.py:175: in cmd
    return execute(self.cli_ctx, command, expect_failure=expect_failure).assert_with_checks(checks)
..\..\..\azure-cli\src\azure-cli-testsdk\azure\cli\testsdk\base.py:250: in __init__
    self._in_process_execute(cli_ctx, command, expect_failure=expect_failure)
..\..\..\azure-cli\src\azure-cli-testsdk\azure\cli\testsdk\base.py:313: in _in_process_execute
    raise ex.exception
..\..\env\lib\site-packages\knack\cli.py:233: in invoke
    cmd_result = self.invocation.execute(args)
..\..\..\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py:663: in execute
    raise ex
..\..\..\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py:726: in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
..\..\..\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py:697: in _run_job
    result = cmd_copy(params)
..\..\..\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py:333: in __call__
    return self.handler(*args, **kwargs)
..\..\..\azure-cli\src\azure-cli-core\azure\cli\core\commands\command_operation.py:121: in handler
    return op(**command_args)
..\..\..\azure-cli\src\azure-cli\azure\cli\command_modules\network\custom.py:2910: in add_dns_txt_record
    return _add_save_record(cmd, record, record_type, record_set_name, resource_group_name, zone_name,
..\..\..\azure-cli\src\azure-cli\azure\cli\command_modules\network\custom.py:3140: in _add_save_record
    return _record_create(cli_ctx=cmd.cli_ctx)(command_args={
..\..\..\azure-cli\src\azure-cli-core\azure\cli\core\aaz\_command.py:149: in __call__
    return self._handler(*args, **kwargs)
..\..\..\azure-cli\src\azure-cli\azure\cli\command_modules\network\aaz\latest\network\dns\record_set\_create.py:27: in _handler
    self._execute_operations()
..\..\..\azure-cli\src\azure-cli\azure\cli\command_modules\network\aaz\latest\network\dns\record_set\_create.py:376: in _execute_operations
    self.RecordSetsCreateOrUpdate(ctx=self.ctx)()
..\..\..\azure-cli\src\azure-cli\azure\cli\command_modules\network\aaz\latest\network\dns\record_set\_create.py:400: in __call__

### Expected behavior

should return statusCode 201, not 400

### Environment Summary

{
  "azure-cli": "2.50.0",
  "azure-cli-core": "2.50.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "application-insights": "0.1.18",
    "appservice-kube": "0.1.7",
    "azure-devops": "0.26.0",
    "connectedk8s": "1.3.20",
    "containerapp": "0.3.35",
    "customlocation": "0.1.3",
    "dev-spaces": "1.0.6",
    "k8s-extension": "1.4.2",
    "virtual-network-tap": "0.1.0"
  }
}

Python/3.10.11 (Windows-10-10.0.22621-SP0)

### Additional context

I saw this PR update with has something to do with the command I'm getting an error on.
[Run command ](https://github.com/Azure/azure-cli/pull/26727/files#diff-3d52a6b2a9ccfbf45bf6164b819e4d92dfb023fb7a91573bb8e1f3f9b77bd5f3)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
