### ISSUE TITLE
Support for Azure AD administrative units is missing

### ISSUE THREAD

**Issue by fabiendelpierre** [Azure/azure-cli#26890]
**Related command**
`az ad`

**Is your feature request related to a problem? Please describe.**
I was shocked to find out that the Azure CLI doesn't appear to have support for [Azure AD administrative units](https://learn.microsoft.com/en-us/azure/active-directory/roles/administrative-units). Am I missing something? If not, please add support for administrative units.

Additional details if it matters: I want to use GitHub Actions to interact with an administrative unit in my Azure AD tenant. I already wrote a Python script that does it via the Graph API using an app registration with a client secret. My problem is that I don't want to use a client secret, instead I want to use federated credentials so that my GitHub Actions workflow can obtain an access token via OIDC without having to store static credentials anywhere. I need the access token for my Python script to interact with the Graph API, but I can't figure out how to obtain that access token via OIDC. I use the [Azure/login](https://github.com/Azure/login) action to authenticate to Azure with OIDC, but it doesn't return a token that I've been able to use with my Python script.

However, if the Azure CLI had support for administrative units, I could use the [Azure/cli](https://github.com/Azure/cli) action to interact with my administrative unit instead of Python.

**Describe the solution you'd like**
The Azure CLI should provide a way to interact with Azure AD administrative units (create/delete AUs, add objects to/remove objects from an AU, list objects in an AU, etc.)

**Describe alternatives you've considered**
I'm aware I can use the Graph API directly but that's a lot less user-friendly.

**Additional context**
N/A

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
As described in https://github.com/Azure/azure-cli/issues/7579#issuecomment-460895548,

> Azure CLI's graph commands have never meant to be used for general graph object management; rather they are just enough for RBAC.

According to [Create administrativeUnit](https://learn.microsoft.com/en-us/graph/api/directory-post-administrativeunits?view=graph-rest-1.0&branch=main&tabs=http) REST API doc, this API requires **AdministrativeUnit.ReadWrite.All** permission, but Azure CLI's app registration doesn't have this permisison.

In [Azure/cli](https://github.com/Azure/cli) action, even though you can use `az account get-access-token` to get the access token or use `az rest` to call Microsoft Graph API, Azure CLI's app registration won't allow it to call this specific [Create administrativeUnit](https://learn.microsoft.com/en-us/graph/api/directory-post-administrativeunits?view=graph-rest-1.0&branch=main&tabs=http) REST API.

You may refer to https://learn.microsoft.com/en-us/azure/active-directory/roles/admin-units-manage to see solutions that use Microsoft Graph PowerShell or Azure AD PowerShell.
