### ISSUE TITLE
Deploy com serverless

### ISSUE THREAD

**Issue by reinaldoper** [Azure/azure-cli#26905]
### Describe the bug

Não estou conseguindo fazer deploy usando o serverless Azure, aparece este erro: Error:
Error: Authentication returned an empty list of subscriptions. Try another form of authentication. See the serverless-azure-functions README for more help.

Please help me .

### Related command

sls deploy

### Errors

Error: Authentication returned an empty list of subscriptions. Try another form of authentication. See the serverless-azure-functions README for more help.

### Issue script & Debug output

provider:
  name: azure
  region: West US 2
  runtime: nodejs14

### Expected behavior

Fazer deploy.

### Environment Summary

azure-cli                         2.50.0

core                              2.50.0
telemetry                          1.0.8

### Additional context

Please help me,.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by reinaldoper** [comment]
Thanks.
Very good.

**Comment by jsntcy** [comment]
@reinaldoper, `sls deploy` is not a command in azure cli and it seems it belongs to https://github.com/serverless/serverless-azure-functions/tree/master.

**Comment by navba-MSFT** [comment]
@reinaldoper The similar issue has been discussed [here ](https://forum.serverless.com/t/unable-to-deploy-to-azure/9358#:~:text=I%20was%20having%20a%20similar%20problem%20and%20was%20only%20able%20to%20find%20success%20following%20the%20instructions%20below.%20Hope%20these%20can%20help.)and [here](https://dzeyelid.medium.com/check-in-serverless-framework-for-azure-when-got-an-authentication-error-2a798066d602#:~:text=Authentication%20returned%20an%20empty%20list%20of%20subscriptions.%20Try%20another%20form%20of%20authentication.%20See%20the%20serverless%2Dazure%2Dfunctions%20README%20for%20more%20help).

 If the suggestions provided there doesn't help, I would suggest you to please raise this issue [here](https://github.com/serverless/serverless-azure-functions/issues) ? Hope this helps.
