### ISSUE TITLE
Rhel 8.8 ValueError: 'network_interfaces' is not available in API version 2021-03-01. Pass service API version 2015-06-15 or newer to your client.

### ISSUE THREAD

**Issue by troush2022** [Azure/azure-cli#26912]
### Describe the bug

Rhel 8.8 ValueError: 'network_interfaces' is not available in API version 2021-03-01. Pass service API version 2015-06-15 or newer to your client.

Python3 packages
azure-cli                               2.50.0
azure-cli-core                          2.50.0
azure-cli-telemetry                     1.0.8

Yum package
azure-cli-2.50.0-1.el8.x86_64
rhui-azure-rhel8-ansible-2.2-306.noarch
rhui-azure-rhel8-2.2-602.noarch

ansible [core 2.15.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/US/usconrad01app/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/US/usconrad01app/.local/lib/python3.11/site-packages/ansible
  ansible collection location = /home/US/usconrad01app/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/US/usconrad01app/.local/bin/ansible
  python version = 3.11.2 (main, Jun  6 2023, 07:39:01) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True

### Related command

?

### Errors

ValueError: 'network_interfaces' is not available in API version 2021-03-01. Pass service API version 2015-06-15 or newer to your client.\n",

### Issue script & Debug output

ValueError: 'network_interfaces' is not available in API version 2021-03-01. Pass service API version 2015-06-15 or newer to your client.\n",

The full traceback is:
Traceback (most recent call last):
  File "/home/US/usconrad01app/.ansible/tmp/ansible-tmp-1689598956.5495083-6203-209741900227192/AnsiballZ_azure_rm_networkinterface.py", line 107, in <module>
    _ansiballz_main()
  File "/home/US/usconrad01app/.ansible/tmp/ansible-tmp-1689598956.5495083-6203-209741900227192/AnsiballZ_azure_rm_networkinterface.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/US/usconrad01app/.ansible/tmp/ansible-tmp-1689598956.5495083-6203-209741900227192/AnsiballZ_azure_rm_networkinterface.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_networkinterface', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_networkinterface', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_azure_rm_networkinterface_payload_2djbopz5/ansible_azure_rm_networkinterface_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_networkinterface.py", line 946, in <module>
  File "/tmp/ansible_azure_rm_networkinterface_payload_2djbopz5/ansible_azure_rm_networkinterface_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_networkinterface.py", line 942, in main
  File "/tmp/ansible_azure_rm_networkinterface_payload_2djbopz5/ansible_azure_rm_networkinterface_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_networkinterface.py", line 631, in __init__
  File "/tmp/ansible_azure_rm_networkinterface_payload_2djbopz5/ansible_azure_rm_networkinterface_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 478, in __init__
  File "/tmp/ansible_azure_rm_networkinterface_payload_2djbopz5/ansible_azure_rm_networkinterface_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_networkinterface.py", line 693, in exec_module
  File "/home/US/usconrad01app/.local/lib/python3.11/site-packages/azure/mgmt/network/_validation.py", line 32, in wrapper
    raise ValueError(
ValueError: 'network_interfaces' is not available in API version 2021-03-01. Pass service API version 2015-06-15 or newer to your client.
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/US/usconrad01app/.ansible/tmp/ansible-tmp-1689598956.5495083-6203-209741900227192/AnsiballZ_azure_rm_networkinterface.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/US/usconrad01app/.ansible/tmp/ansible-tmp-1689598956.5495083-6203-209741900227192/AnsiballZ_azure_rm_networkinterface.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/US/usconrad01app/.ansible/tmp/ansible-tmp-1689598956.5495083-6203-209741900227192/AnsiballZ_azure_rm_networkinterface.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_networkinterface', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_networkinterface', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_azure_rm_networkinterface_payload_2djbopz5/ansible_azure_rm_networkinterface_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_networkinterface.py\", line 946, in <module>\n  File \"/tmp/ansible_azure_rm_networkinterface_payload_2djbopz5/ansible_azure_rm_networkinterface_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_networkinterface.py\", line 942, in main\n  File \"/tmp/ansible_azure_rm_networkinterface_payload_2djbopz5/ansible_azure_rm_networkinterface_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_networkinterface.py\", line 631, in __init__\n  File \"/tmp/ansible_azure_rm_networkinterface_payload_2djbopz5/ansible_azure_rm_networkinterface_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 478, in __init__\n  File \"/tmp/ansible_azure_rm_networkinterface_payload_2djbopz5/ansible_azure_rm_networkinterface_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_networkinterface.py\", line 693, in exec_module\n  File \"/home/US/usconrad01app/.local/lib/python3.11/site-packages/azure/mgmt/network/_validation.py\", line 32, in wrapper\n    raise ValueError(\nValueError: 'network_interfaces' is not available in API version 2021-03-01. Pass service API version 2015-06-15 or newer to your client.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP *************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0   

### Expected behavior

Ansible error due to azure package issue

### Environment Summary

azure-cli                         2.50.0

core                              2.50.0
telemetry                          1.0.8

Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.11'
Extensions directory '/home/US/usconrad01app/.azure/cliextensions'

Python (Linux) 3.11.2 (main, Jun  6 2023, 07:39:01) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

there is some conflict with what packages are compatible together.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yonzhan** [comment]
Please provide detailed CLI command.

**Comment by navba-MSFT** [comment]
@troush2022 Thanks for reaching out to us and reporting this issue. Please provide the details about your use case and your AzCLI command. Awaiting your reply.

**Comment by troush2022** [comment]
All,

I figure out the issue. For azure you still need python 2.7 installed and once I did that I was able to run with no issues. We can close this ticket.

**Comment by navba-MSFT** [comment]
@troush2022 Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
