### ISSUE TITLE
Trusted Launch as Default - Warning message request - Enable backup for VM

### ISSUE THREAD

**Issue by AjKundnani** [Azure/azure-cli#26914]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

`az backup protection enable-for-vm`

### Resource Provider

Microsoft.RecoveryServices/vaults

### Description of Feature or Work Requested

# Implement TL-as-Default breaking change warning

Upcoming default for VM to become **Trusted Launch** as per change #23450 (planned for Ignite - November 2023) can cause impact to CLI users if they do not change the command [az backup protection enable-for-vm](https://learn.microsoft.com/en-us/azure/backup/quick-backup-vm-cli#enable-backup-for-an-azure-vm) from Standard Policy -> Enhanced Policy because Trusted Launch VMs support backup using **Enhanced Policy**. 

Request to add below warning message for end users when they execute the command `az backup protection enable-for-vm`:

`Ignite (November) 2023 onwards Virtual Machine deployments will default to Trusted Launch configuration. You need to ensure Policy Name used with Backup enablement <command> is of type Enhanced Policy for Trusted Launch VMs. Non-Trusted Launch Virtual Machines will not be impacted by this change. To know more about default change and Trusted Launch, please visit https://aka.ms/TLaD.`

Goal is to reduce impact for users enabling backup using CLI due to Trusted Launch as default change implementation for VMs.

### Minimum API Version Required

NA

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2023-04-01/bms.json

### Request Example

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2023-04-01/examples/AzureIaasVm/ProtectionIntent_CreateOrUpdate.json

### Target Date

2023-08-30

### PM Contact

ajkundna;nikhilsarode

### Engineer Contact

psurad

### Additional context

Present Error message - Enable backup for Trusted Launch using Standard Policy.

![image](https://github.com/Azure/azure-cli/assets/18166395/47e5b3f9-8f49-4796-98bd-4aab3c2b0c3b)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
Since the `backup` module is owned by service team, + @zubairabid @akshayneema to help take a look at this feature request

**Comment by zubairabid** [comment]
The code change has been pushed as part of PR https://github.com/Azure/azure-cli/pull/27130

**Comment by AjKundnani** [comment]
> As I understand, the only ask here is to add a warning message when `az backup protection enable-for-vm` is run.
> 
> I've implemented it as follows, @AjKundnani could you please verify if this is what you are looking for: ![image](https://user-images.githubusercontent.com/26400677/260973210-e0ba7e96-9532-43ab-a9dc-d8393dcca632.png)

Minor update to message, updates highlighted in **bold**, need not be bold in implementation.

“Ignite (November) 2023 onwards Virtual Machine deployments **using PS and CLI** will default to **security type** Trusted Launch. Please ensure Policy Name used with Backup enablement using PS and CLI <command> is of type Enhanced Policy for Trusted Launch VMs. Non-Trusted Launch Virtual Machines will not be impacted by this change. To know more about default change and Trusted Launch, please visit https://aka.ms/TLaD”

Also, if we can ensure https://aka.ms/TLaD is clickable? Sample from az vm create command below.

![image](https://github.com/Azure/azure-cli/assets/18166395/25bc60f5-343a-48ff-a4be-d55616283a40)

**Comment by zubairabid** [comment]
Thanks for the confirmation, @AjKundnani . I've updated the error message, will push it soon.

The link is clickable, the user sees the message when hovering over it with their cursor.
![image](https://github.com/Azure/azure-cli/assets/26400677/339aaf48-af7a-4d3e-91a6-eb1e923a17b9)

**Comment by AjKundnani** [comment]
> Thanks for the confirmation, @AjKundnani . I've updated the error message, will push it soon.
> 
> The link is clickable, the user sees the message when hovering over it with their cursor. ![image](https://user-images.githubusercontent.com/26400677/260980251-339aaf48-af7a-4d3e-91a6-eb1e923a17b9.png)

Last edit, `will default to security type Trusted Launch` **configuration**. Please remove keyword configuration from this statement.

**Comment by zubairabid** [comment]
Updated it: https://github.com/Azure/azure-cli/pull/27130/files#diff-533e682d590ff485eb9714bc014cf702fe19e9cf2389cf1225bb8abf1db8078e

https://github.com/Azure/azure-cli/blob/4a0b1bf0977b72434a8202d2f9c4d035b4de7046/src/azure-cli/azure/cli/command_modules/backup/custom.py#L660
