### ISSUE TITLE
how to login cli 2.0 using service-principal and certificate

### ISSUE THREAD

**Issue by dhermans** [Azure/azure-cli#2692]
Hi,
cli1.0 had an option to use just this:
azure login --service-principal --tenant ZZZZZZZZZZZZ -u RRRRRRRR --certificate-file MYCERT.pem --thumbprint ZZZZZZZZZZZZZZZZZ

there doesn't seem to be a CLI2.0 equivalent of this useful feature!!

Thanks!

**Comment by tjprescott** [comment]
`az login -h` has an entry for this scenario:

```
Log in with a service principal using client certificate.
        az login --service-principal -u http://azure-cli-2016-08-05-14-31-15 -p ~/mycertfile.pem
        --tenant contoso.onmicrosoft.com
```

If that doesn't work, please re-open.

**Comment by yugangw-msft** [comment]
JFYI, the `az ad sp create-for-rabc` supports to create a service principal with certificate through the flag of ` --create-cert`

**Comment by dhermans** [comment]
yes I saw that in the documentation but it doesn't work - the same service principal and cert that I can use for Azure 1.0 CLI doesn't work for Azure 2.0 CLI:

/usr/local/bin/azure-cli/az login -u https://MYURL --tenant XXXXXXXXX -p ./MYCERT.pem --service-principal
Get Token request returned http error: 401 and server response: {"error":"invalid_client","error_description":"AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided.\r\nTrace ID: XXXXXXXXXXXXXX\r\nCorrelation ID: CCCCCCCCCCC\r\nTimestamp: 2017-04-03 00:15:01Z","error_codes":[70002,50012],"timestamp":"2017-04-03 00:15:01Z","trace_id":"TTTTTTT","correlation_id":"CCCCCCCCC"}

**Comment by yugangw-msft** [comment]
Please make sure `./MYCERT.pem` is the right file path to the pem file

**Comment by dhermans** [comment]
its the same cert i used for CLI 1.0 - which works perfectly:

azure login --service-principal --tenant TTTTTTTTT -u UUUUUUUUUUUUU --certificate-file MYCERT.pem --thumbprint TTTTTTTTTTTTTTTTTTTTTTTT
info:    Executing command login
info:    login command OK
azure vm list etc.. works

so to restate, on the same machine, using same certificate and  tenantID I can login with Cert on CLI 1.0 just fine.

**Comment by dhermans** [comment]
running with debug it seems  the CLI is parsing the password as a text field and not a file:
func=<function _execute_command at 0x41f7b90>, password='./MYCERT.pem', service_principal=Tru 

I 'straced' the function calls and I don't see any open attempt on the certificate file.

seems i am missing commit #2327  which was merged 18 days ago

sigh................

**Comment by dhermans** [comment]
i meant #2457

**Comment by yugangw-msft** [comment]
The support is not released yet and we will have on this week. For now you can either use the docker image or the nightly drop

**Comment by yugangw-msft** [comment]
@dhermans, we have published a release with the support. Thanks.

**Comment by dhermans** [comment]
@yugangw-msft Thanks very much! working!!
