### ISSUE TITLE
list all enabled addons

### ISSUE THREAD

**Issue by ozbillwang** [Azure/azure-cli#26937]
with current features, there only two commands to enable and delete addons

```
az aks enable-addons
az aks disable-addons
```

would be nice to have a new sub-command `list-addons` to list all enabled add-ons on aks if they are enabled.

```
az aks list-addons
```
The similar requirement has been raised before with https://github.com/Azure/azure-cli/issues/10000, but seems it was closed without any actions.

For example, I used below command to enable the addon `azure-keyvault-secrets-provider` 

```
az aks enable-addons --addons azure-keyvault-secrets-provider --name myAKSCluster --resource-group myResourceGroup
```

currently I need run this command to confirm

```
kubectl get pods -n kube-system -l 'app in (secrets-store-csi-driver,secrets-store-provider-azure)'
```

So I need check if the addon has been enabled or not , with `list-addons` if possible.

ref: https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-driver

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by SaurabhSharma-MSFT** [comment]
@ozbillwang You can use `az aks addon list --resource-group  --name --output table` to get list of addons with enabled as True to identify addons enabled on your AKS. Please check the screenshot below -
![image](https://github.com/Azure/azure-cli/assets/38112130/b74704b3-6ad6-4fe8-a829-5dade47f62c2)

**Comment by ozbillwang** [comment]
Thanks, @SaurabhSharma-MSFT , the feature is exist already, I can see the list now.

Then the problme is about the sub-commands naming. 

should we do

```
az aks addon enable
az aks addon disable
az aks addon list
```
or
```
az aks enable-addons
az aks disable-addons
az aks list-addons
```
currently they are mixed.
