### ISSUE TITLE
Add hibernate optional parameter for az vmss deallocate

### ISSUE THREAD

**Issue by vatsan28** [Azure/azure-cli#26938]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az vmss deallocate --instance-ids 1 --name MyScaleSet --resource-group MyResourceGroup --hibernate

### Resource Provider

Microsoft.Compute/VirtualMachineScaleSets

### Description of Feature or Work Requested

We would like support for hibernating a VM while deallocating. The support is already added in the SDK and api. We want to extend this support for CLI by adding this optional parameter - `hiberante` in the az vmss deallocate.

### Minimum API Version Required

2021-03-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/23409

### Target Date

2023-08-01

### PM Contact

jainan

### Engineer Contact

srivmura

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
> 2023-08-01

@vatsan28 Please note that due to the fact that our work is already fully scheduled for this sprint and the submission time of this request is relatively late, so we plan to develop and release it in the next sprint. Do you think this release time meets your expectations?

**Comment by ReaNAiveD** [comment]
Hi @vatsan28 , 
Could you help me with the following error prompt that I encountered when running the command in development.
![image](https://github.com/Azure/azure-cli/assets/32201005/d1561784-3365-4a40-8910-3a153e23d431)
I have run `az vmss create -g qinkai-test -n vmss-test --image Canonical:UbuntuServer:18.04-LTS:latest --orchestration-mode Flexible --admin-username vmtest` before the execution.

Or could you please provide an end-to-end user case in the form of Azure CLI command sequence so we can test the effect of the new parameter?

**Comment by vatsan28** [comment]
@ReaNAiveD The VMSS needs to be created with the hibernationEnabled. Following is the example:
```az vmss create -g qinkai-test -n vmss-test --image Canonical:UbuntuServer:18.04-LTS:latest --orchestration-mode Flexible --admin-username vmtest --enable-hibernation true```

**Comment by ReaNAiveD** [comment]
> @ReaNAiveD The VMSS needs to be created with the hibernationEnabled. Following is the example: `az vmss create -g qinkai-test -n vmss-test --image Canonical:UbuntuServer:18.04-LTS:latest --orchestration-mode Flexible --admin-username vmtest --enable-hibernation true`

Hi @vatsan28 , at present, there is no argument named `--enable-hibernation` in command `az vmss create`. You can create a feature request issue for the argument and then we can move forward.

**Comment by vatsan28** [comment]
Created issue: https://github.com/Azure/azure-cli/issues/27070

**Comment by vatsan28** [comment]
Can you please confirm if both of these can be done before 09-05 release?
