### ISSUE TITLE
[ACS] ACS create --tags parameter doesn't work

### ISSUE THREAD

**Issue by IainColledge** [Azure/azure-cli#2693]
Am trying to pass single a single or multiple tags when creating a cluster i.e. az acs create -n foo -g bar --tag key1=value2

The response is:

Deployment template validation failed: 'The provided value for the template parameter 'tags' at line '69' and column '14' is not valid.'.

The documentation states Tag Object but even trying quotes and JSON doesn't seem to result in a valid set of tags. Searches seem to bring up nothing either. The above pattern of key1=value1 is a common pattern with other acs commands, hence why tried.

**Comment by tjprescott** [comment]
If the standard tags notation used throughout the CLI is not accepted here, that would be a bug.

**Comment by IainColledge** [comment]
Thanks.
