### ISSUE TITLE
Doc update needed for CLI command "az mysql flexible-server replica create"

### ISSUE THREAD

**Issue by VandhanaMehta** [Azure/azure-cli#26944]
Documentation update needed, for optional parameters section to help customer using this "az mysql flexible-server replica create" cli command to have better clarity for in-region and cross region read replica. 

pls see updated doc guidance pasted below and changes highlighted in bold:

--private-dns-zone

 

**This parameter only applies if you are creating cross region replica server with private access. For in-region read replica with private access, source server settings are carried over and this parameter is ignored**. The name or id of new or existing private dns zone. You can use the private dns zone from same resource group, different resource group, or different subscription. If you want to use a zone from different resource group or subscription, please provide resource Id. CLI creates a new private dns zone within the same resource group as virtual network if not provided by users.

--public-access

 

Determines the public access.

accepted values: Disabled, Enabled

--subnet

 

Name or resource ID of a new or existing subnet. **This parameter only applies if you are creating cross region replica server with private access. For in-region read replica with private access, source server settings are carried over and this parameter is ignored**. If you want to use a subnet from different resource group or subscription, please provide resource ID instead of name. Please note that the subnet will be delegated to flexibleServers. After delegation, this subnet cannot be used for any other type of Azure resources.

--tags

 

Space-separated tags: key[=value] [key[=value] ...]. Use "" to clear existing tags.

--vnet

 

Name or ID of a new or existing virtual network. **This parameter only applies if you are creating cross region replica server with private access. For in-region read replica with private access, source server settings are carried over and this parameter is ignored**. If you want to use a vnet from different resource group or subscription, please provide a resource ID. The name must be between 2 to 64 characters. The name must begin with a letter or number, end with a letter, number or underscore, and may contain only letters, numbers, underscores, periods, or hyphens.

--zone -z

 

Availability zone into which to provision the resource.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by SaurabhSharma-MSFT** [comment]
@VandhanaMehta The PR for the fix has been created and it will be merged upon approval. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
