### ISSUE TITLE
Got InvalidApiVersionParameter when use az keyvault network-rule add --name "keyvaultname" --subnet "subnetresourceid"

### ISSUE THREAD

**Issue by rachelxj-ms** [Azure/azure-cli#26950]
There are over 100 KeyVaults in customer's subscription. When customer called the command:
az keyvault network-rule add --name "keyvaultname" --subnet "subnetresourceid", they got below error message:

(InvalidApiVersionParameter) The api-version '2023-02-01' is invalid. The supported versions are '2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.

The nextlink has the right api-version 2015-11-01, but the next call changes the api-version to 2023-02-01, which is incorrect. 
![image](https://github.com/Azure/azure-cli/assets/66855967/ea7cb6ce-2675-425f-9e10-734ccccbdd77)

This is impacting customer's production, please help fix it ASAP. thanks. 

### Related command

az keyvault network-rule add --name "keyvaultname" --subnet "subnetresourceid"

### Errors

(InvalidApiVersionParameter) The api-version '2023-02-01' is invalid. The supported versions are '2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.

### Issue script & Debug output

az keyvault network-rule add --name "keyvaultname" --subnet "subnetresourceid" --debug >> ErrorOutput.txt
![image](https://github.com/Azure/azure-cli/assets/66855967/c547ea10-db67-4c05-82f6-1559ec029ed6)
Please ping me on teams if you need full logs. 

### Expected behavior

It should work when there are more than 100 key vaults in the subscription. 

### Environment Summary

{
  "azure-cli": "2.50.0",
  "azure-cli-core": "2.50.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "ai-examples": "0.2.5",
    "ml": "2.18.0",
    "ssh": "1.1.6"
  }
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by rachelxj-ms** [comment]
Hi, @yonzhan you can use this API to get specific key vault instead of listing all keyvautls in the subscription. 
https://learn.microsoft.com/en-us/rest/api/keyvault/keyvault/vaults/get?tabs=HTTP

**Comment by evelyn-ys** [comment]
@rachelxj-ms will ping you on teams

**Comment by evelyn-ys** [comment]
@rachelxj-ms It's recommended to specify `--resource-group` name if there're lots of keyvaults in the sub or else CLI would list all keyvaults to find the matched one.

Though adding `--resource-group` parameter can unblock customer. But the bug does exist. And it's from `azure-mgmt-keyvault` SDK side. @msyyc for confirmation.

`vaults_operation.list()` manually specify `2015-11-01`(Line 1529) for first fetch(Line ) then doesn't honor the API version returned in `nextlink`, it uses `2023-02-01` instead. Please help explain or fix. @msyyc 

[Code ref](https://github.com/Azure/azure-sdk-for-python/blob/4f883d31b966e944b78f201a6d3ab550688fcdee/sdk/keyvault/azure-mgmt-keyvault/azure/mgmt/keyvault/v2023_02_01/operations/_vaults_operations.py#L1529-L1571):
![image](https://github.com/Azure/azure-cli/assets/10227683/ebf5ab6b-128e-42ea-88be-0868af02db64)

**Comment by rachelxj-ms** [comment]
@evelyn-ys Thanks. --resource-group works for the customer.

**Comment by kabhMSFT** [comment]
@evelyn-ys / @msyyc please help me understand who will be fixing this on the SDK side? Is there a work item for this?

**Comment by evelyn-ys** [comment]
Should be a work item from SDK side. But I don't know whether @msyyc or Kyle Kim(Keyvault service engineer) should be the owner

**Comment by evelyn-ys** [comment]
CLI also improves our implementation in https://github.com/Azure/azure-cli/pull/26990
