### ISSUE TITLE
Add default oubound subnet feature for subnets

### ISSUE THREAD

**Issue by brianlehr** [Azure/azure-cli#26956]
**Description of Feature or Work Requested**

When a virtual machine is deployed (when not associated to a Load Balancer, NAT Gateway resource or Public IP), it gets an unknown dynamic IP address owned by Microsoft. This IP is called a “pseudovip” and provides what is called default outbound connectivity. Apart from being insecure (as it opens resources up to the internet), it is also a cause of support cases since customers cannot see this IP, the address is unknown and they cannot depend on it.  This goes against our “secure by default” model and should not be the default in the future.
We have documented a [multi-phased approach](https://microsoft.sharepoint.com/:w:/t/Aznet/EcK_b7PWhEtDjQ52eW2NYnQBivF9xpSgWTFTER7W-qi5Mg?e=BdXzb4) for moving away from default outbound access.  A major part of this is the introduction and use of the defaultOutboundAccess parameter for a subnet – making the subnet considered a “private subnet”.

Note this parameter already [exists ](https://msazure.visualstudio.com/One/_git/Networking-nrp?path=/src/sources/Frontend/FrontendContract/Csm.Public/Subnet.cs&_a=contents&version=GBmaster)and can be invoked through ARM; we would like to ensure it is also available in CLI.

Spec is [here](https://microsoft.sharepoint.com/:w:/t/Aznet/EaF7dVMyNwVIjxEP3uTA-EABRCbEmaSozPlbGXsAhJW5MQ?e=X9xxCU)

**Resource Provider**
Network Resource Provider

**Describe the solution you'd like**

New parameter for default outbound access to be enabled or disabled when creating netnew subnets.

az network vnet subnet create
--name <subnetName>
--resource-group <resourceGroupName>
--vnet-name <virtualNetworkName>
**--defaultoutboundaccess <true|false>**

Parameter is a string that takes true or false as valid inputs.  Default value of subnet would be "true" if it is not specified.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by ZengTaoxu** [comment]
Hello, could you please attach the corresponding api version and link?

**Comment by brianlehr** [comment]
Sure -- it is here: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2023-05-01/virtualNetwork.json

**Comment by brianlehr** [comment]
Do we have a date when this will be merged?

**Comment by necusjz** [comment]
> Do we have a date when this will be merged?

https://github.com/Azure/azure-cli/milestone/134

**Comment by brianlehr** [comment]
Hello @ZengTaoxu @yonzhan - I'm not seeing this as implemented when using cloudshell, is there something I'm doing wrong?

**Comment by ZengTaoxu** [comment]
Is Azure CLI updated to the latest version？
If you haven't already attempted to do so, please upgrade to the latest Azure CLI version by following
https://learn.microsoft.com/en-us/cli/azure/update-azure-cli

**Comment by brianlehr** [comment]
Yes @ZengTaoxu I have the latest version.  Tried in both cloud shell and terminal.  It says defaultoutboundaccess is an unrecognized argument.

**Comment by brianlehr** [comment]
@ZengTaoxu I figured out why it wasn't working, you ended up using a different verbiage than I asked for above.  That is, I asked for --defaultoutboundaccess and you guys used --default-outbound.  Not a huge deal but that was the issue :-)

**Comment by ZengTaoxu** [comment]
Hi brianlehr, because parameters have a length limit, parameters that exceed the length should be given a shorter name. Both --default-outbound and --default-outbound-access are available. If --defaultoutboundaccess is used, it does not comply with the cli naming convention. Therefore, it is not used.
