### ISSUE TITLE
[ResourceManager] Unable to delete a resource with `az resource delete`

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#2695]
As reported in #2694, I was unable to delete a lock using the `az lock delete` command. However, since this is an Azure resource, I should be able to delete it using the `az resource delete` command as a workaround. However, when I tried, I got the following result:

```
az resource delete --id /subscriptions/xxx-xxx/resourceGroups/tjp-lock/providers/Microsoft.Network/virtualNetworks/vnet1/providers/Microsoft.Authorization/locks/VnetLock

No registered resource provider found for location 'westus' and API version '2017-03-01' for type 'locks'. The supported api-versions are '2015-01-01, 2015-05-01-preview, 2015-06-01, 2016-09-01, 2017-04-01'. The supported locations are ''.
```

**Comment by perseusCode** [comment]
Should you be using the API version specified in the error message. The resource 'locks' actually belongs to the Microsoft.Authorization provider. Hence you should use the api-version belonging to the provider as the error message suggests.

**Comment by tjprescott** [comment]
The API version is resolved automatically within the CLI, so it looks like that logic has some flaw in it.

**Comment by brendandburns** [comment]
Yeah, I'll dig into that code and see what's up.

**Comment by brendandburns** [comment]
Fix is here:

https://github.com/Azure/azure-cli/pull/2781
