### ISSUE TITLE
config-zip deployment fails with "The write operation timed out"

### ISSUE THREAD

**Issue by reedperkins** [Azure/azure-cli#26955]
### Describe the bug

When I invoke the command:

`az functionapp deployment source config-zip --src my.zip -g my-rg -n my-app`

I get the following exception: 

`TimeoutError('The write operation timed out)`

Azure cli version: 2.50.0

Output of `hostnamectl`:

Operating System: Fedora Linux 38 (Workstation Edition)
Kernel: Linux 6.3.12-200.fc38.x86_64
Architecture: x86-64

### Related command

`az functionapp deployment source config-zip --src my.zip -g my-rg -n my-app --timeout 360`

### Errors

`TimeoutError('The write operation timed out)`

### Issue script & Debug output

Too much information unfortunately

### Expected behavior

Function app should be deployed successfully

### Environment Summary

azure-cli                         2.50.0

core                              2.50.0
telemetry                          1.0.8

Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2

### Additional context

Navigating to https://my-app.scm.azurewebsites.net/api/deployments/latest I see webpage with simply: `Deployment 'latest' not found.`

Size of .zip file: 45.5 MB (too big?)

First deployment done with Jet Brains Rider Publish to Azure. Subsequent attempts through the same method unsuccessful. 

Tried adding `--timeout 360`. Timeout parameter does not seem to be respected -- 360 seconds is 5 minutes, but the command times out at about 2 mins regardless of the timeout value

Function app is on Linux consumption plan. Total number of functions in app: 11 including durable functions w/ activity triggers

Under the subscription I have the role of "Owner". However, when I try to review the raw release files in the storage account in the azure portal (Data Storage > Containers > function_releases) I get a permissions error: `You do not have permissions to list the data using your user account with Azure AD.`

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by kamperiadis** [comment]
Hi @reedperkins Just wanted to check in and see if you are still experiencing this issue? Thank you.
