### ISSUE TITLE
Add documentation for commands to work with WorkItemQueryFolders

### ISSUE THREAD

**Issue by jeffrey-chongsathien-oxinst** [Azure/azure-cli#26964]
**Describe the solution you'd like**

Add documentation for commands to work with WorkItemQueryFolders

**Additional context**

I suspect this is missing because that functionality doesn't exist.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jsntcy** [comment]
@jeffrey-chongsathien-oxinst, please provide more details.

**Comment by jeffrey-chongsathien-oxinst** [comment]
These notifications were stuck in our organization's email filter.

"please provide more details."

That's not an adequate request. My response is "Like what?"

**Comment by jeffrey-chongsathien-oxinst** [comment]
If you're struggling with the vagueness of a report, a vague question isn't going to progress the issue. The title is really self-explanatory, assuming the issue includes the documentation page I was referencing.
