### ISSUE TITLE
antlr4-python3-runtime is being installed using the legacy 'setup.py install'

### ISSUE THREAD

**Issue by den-is** [Azure/azure-cli#26969]
### Describe the bug

Installing azure-cli using pip outputs Warning about using outdated installation method for one of the components - `antlr4-python3-runtime`.
And it is going to completely fail with the future pip versions.

```
Python 3.10.12
# default pip version installed in the virtualenv (pyenv+direnv)
pip 23.0.1
```

> pip install -U azure-cli
> ...
> DEPRECATION: antlr4-python3-runtime is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for antlr4-python3-runtime ... done
> ...
> [notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip

### Related command

pip install -U azure-cli==2.50.0

### Errors

DEPRECATION: antlr4-python3-runtime is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

### Issue script & Debug output

N/A

### Expected behavior

Clean installation without using deprecated ancient methods and techniques.

### Environment Summary

azure-cli                         2.50.0

core                              2.50.0
telemetry                          1.0.8

Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2

Python location '/Users/den/projects/azure/.direnv/python-3.10/bin/python'
Extensions directory '/Users/den/.azure/cliextensions'

Python (Darwin) 3.10.12 (main, Jul 22 2023, 21:22:22) [Clang 14.0.0 (clang-1400.0.29.202)]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
I believe bump antlr4 is the right way to solve it.

----------

Currently, it does not affect CLI.
When pip is 23.2.1, here is the installation log:
```
pip install antlr4-python3-runtime==4.9.3 --no-cache-dir
Collecting antlr4-python3-runtime==4.9.3
  Downloading antlr4-python3-runtime-4.9.3.tar.gz (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.0/117.0 kB 1.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: antlr4-python3-runtime
  Building wheel for antlr4-python3-runtime (pyproject.toml) ... done
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.9.3-py3-none-any.whl size=144552 sha256=026a0c30aaef6e3957942e670b1bc201a92fe96fcb89d22216bccd190c0ec732
  Stored in directory: /tmp/pip-ephem-wheel-cache-24cvxjof/wheels/12/93/dd/1f6a127edc45659556564c5730f6d4e300888f4bca2d4c5a88
Successfully built antlr4-python3-runtime
Installing collected packages: antlr4-python3-runtime
Successfully installed antlr4-python3-runtime-4.9.3
```
```
pip list
Package                Version
---------------------- -------
antlr4-python3-runtime 4.9.3
pip                    23.2.1
setuptools             59.6.0
```
