### ISSUE TITLE
Unable to utilize the az storage blob directory list command

### ISSUE THREAD

**Issue by TopperKain** [Azure/azure-cli#26968]
### Describe the bug

Running the command 
```
az storage blob directory list --account-name "xxxx" -c "xx" -d "xxx/xxx/xxx" --auth-mode login --verbose
```

Results in the following error:

```
This command is implicitly deprecated because command group 'storage blob directory' is deprecated and will be removed in a future release. Use 'az storage fs directory' instead.

You do not have the required permissions needed to perform this operation.
Depending on your operation, you may need to be assigned one of the following roles:
    "Storage Blob Data Contributor (Preview)"
    "Storage Blob Data Reader (Preview)"
    "Storage Queue Data Contributor (Preview)"
    "Storage Queue Data Reader (Preview)"

If you want to use the old authentication method and allow querying for the right account key, please use the "--auth-mode" parameter and "key" value.
```

However, running the newer command

```
az storage fs file list --account-name "xxx" --file-system "xxx" --path "xxx/xxx/xxx" --auth-mode login
```

Resulted in success.

The az storage blob directory list  command appears to be broken. The target storage account has the following properties:
<img width="326" alt="image" src="https://github.com/Azure/azure-cli/assets/5587143/7fbaa9db-c855-433c-a05e-5da82f8dbf5a">

<img width="714" alt="image" src="https://github.com/Azure/azure-cli/assets/5587143/dc70e643-84a7-45b4-9119-c7e0fb8e3139">

The user is confirmed to have appropriate permissions on the file system

### Related command

az storage blob directory list --account-name "xxxx" -c "xx" -d "xxx/xxx/xxx" --auth-mode login --verbose

### Errors

This command is implicitly deprecated because command group 'storage blob directory' is deprecated and will be removed in a future release. Use 'az storage fs directory' instead.

You do not have the required permissions needed to perform this operation.
Depending on your operation, you may need to be assigned one of the following roles:
    "Storage Blob Data Contributor (Preview)"
    "Storage Blob Data Reader (Preview)"
    "Storage Queue Data Contributor (Preview)"
    "Storage Queue Data Reader (Preview)"

### Issue script & Debug output

az storage blob directory list --account-name "xxxx" -c "xx" -d "xxx/xxx/xxx" --auth-mode login --verbose

This command is implicitly deprecated because command group 'storage blob directory' is deprecated and will be removed in a future release. Use 'az storage fs directory' instead.

### Expected behavior

User should have lsit of files in the directory returned.

### Environment Summary

I wasn't sure where to get this

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by calvinhzy** [comment]
`az storage fs file list` is indeed the correct command to use, https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/docs/ADLS%20Gen2.md#Manage-Directories-in-Azure-Data-Lake-Storage-Gen2-file-system. `az storage blob directory` has been deprecated as shown
