### ISSUE TITLE
Enable Trusted Launch on existing VMSS | az vmss update

### ISSUE THREAD

**Issue by AjKundnani** [Azure/azure-cli#26972]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

`az vmss update`

### Resource Provider

Microsoft.Compute/virtualMachineScaleSets

### --security-type (az vmss update)

Customers can use **az vmss update** with new parameter **--security-type** to enable `TrustedLaunch` on existing VMSS. The new parameter will be aligned with az vmss create --security-type command.

**Example:** az vmss update --security-type TrustedLaunch

When above command is executed:

- CLI will validate if VMSS is already Gen2 HyperVGeneration=V2 using OS Disk attributes. End user should pass Gen2 OS image in same command if VMSS is running Gen1 HyperVGeneration=v1 else backend will return error. To mitigate above scenario, informational message can be displayed to end user.
- CLI will validate securityType is currently set to `null` or `TrustedLaunch` using VMSS attributes.
- CLI will set `--enable-secure-boot:false` and `--enable-vtpm:true` if not specified by end user.
- Post execution, the securityType of VMSS will be updated to TrustedLaunch

--security-Type Value | Description
-|-
TrustedLaunch | Changes existing Gen1/Gen2 VMSS from Standard (or null) Security type to Trusted Launch enabled.

### Scenario 1 - Gen1 VMSS - Change OS Image to Gen2

VMSS is currently deployed using Hyper-V Gen1 (v1) OS image.

1. Customer runs following command to change OS image to Gen2 and enable Trusted Launch

```
az vmss update -g <resourceGroupName -n $<vmssName> `
 --set virtualMachineProfile.storageProfile.imageReference.sku='2022-datacenter-azure-edition'
 --security-type TrustedLaunch --enable-secure-boot true --enable-vtpm true
```

2. CLI will display following informational message to end user.

`Trusted Launch security type is supported on Hyper-V Generation 2 OS Images. To know more please visit https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch`

3. Set `--enable-secure-boot:false` and `--enable-vtpm:true` if not specified by end user.

### Scenario 2 - Gen1 VMSS - No OS Image change

VMSS is currently deployed using Hyper-V Gen1 (v1) OS image.

1. Customer runs following command to enable Trusted Launch

`az vmss update -g <resourceGroupName -n $<vmssName> --security-type TrustedLaunch`

2. CLI will display following informational message to end user.

`Trusted Launch security type is supported on Hyper-V Generation 2 OS Images. To know more please visit https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch`

3. Set `--enable-secure-boot:false` and `--enable-vtpm:true` if not specified by end user.

4. Backend will return error as Trusted Launch is not supported on Gen1 OS Images.

### Scenario 3 - Gen2 VMSS - No OS Image change

VMSS is currently deployed using Hyper-V Gen1 (v1) OS image.

1. Customer runs following command to enable Trusted Launch

`az vmss update -g <resourceGroupName -n $<vmssName> --security-type TrustedLaunch`

2. CLI will display following informational message to end user.

`Trusted Launch security type is supported on Hyper-V Generation 2 OS Images. To know more please visit https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch`

3. Set `--enable-secure-boot:false` and `--enable-vtpm:true` if not specified by end user.

### Minimum API Version Required

2020-06-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2022-11-01/virtualMachineScaleSet.json

### Request Example

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2022-11-01/examples/virtualMachineScaleSetExamples/VirtualMachineScaleSet_Create_WithUefiSettings.json

### Target Date

2023-09-30

### PM Contact

ajkundna

### Engineer Contact

shankarma

### Additional context

- **VMSS Gen1/Gen2 -> Trusted Launch Upgrade** is currently in Private preview and enabled in specific regions. Refer to [Enable Trusted Launch on existing VMSS](https://eng.ms/docs/cloud-ai-platform/azure-core/core-compute-and-host/compute-platform-arunki/vmss-team-docs/documents/gen1totlmigrationonboardingdoc) for more details.
- Public Preview ETA: August 2023 (available in all regions but behind AFEC).
- General Availability ETA: October 2023.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by AjKundnani** [comment]
> Hi @AjKundnani Find similar issue #21180.
> 
> Issue title	Trusted Launch Az CLI VMSS Support
> Create time	2022-02-02
> Comment number	8
> Possible solution: To enable Trusted Launch on an existing VMSS using az vmss update, you can use the following command:
> 
> ```
> az vmss update -g <resourceGroupName> -n <vmssName> --security-type TrustedLaunch --enable-secure-boot true --enable-vtpm true
> ```
> 
> This command will validate if the VMSS is already Gen2 HyperVGeneration=V2 using OS Disk attributes. If the VMSS is running Gen1 HyperVGeneration=v1, the backend will return an error. To mitigate this scenario, an informational message can be displayed to the end user.
> 
> The command will also validate if the securityType is currently set to `null` or TrustedLaunch using VMSS attributes. If the securityType is not set, the command will set `--enable-secure-boot:false` and `--enable-vtpm:true` if not specified by the end user.
> 
> After execution, the securityType of the VMSS will be updated to TrustedLaunch.
> 
> Please note that Trusted Launch security type is supported on Hyper-V Generation 2 OS Images. If you are using a Gen1 OS image, the backend will return an error.
> 
> Please confirm if this resolves your issue.

No this does not resolves issue as `az vmss update` command does not support `--security-type` parameter in version **2.50.0** (latest)

**Comment by zhoxing-ms** [comment]
> Target Date
2023-09-30

@AjKundnani Since the release time for next sprint is `09-05`, dose this release time do you think is suitable?

**Comment by ReaNAiveD** [comment]
> 3\. Set `--enable-secure-boot:false` and `--enable-vtpm:true` if not specified by end user.

Hi @AjKundnani . Should I set `--enable-secure-boot` to `false` if end user specifies it as `true`? What if end user sets one of the two parameters? For example, the user specifies `--enable-vtpm` as `false` while not specifying `--enable-secure-boot`.

**Comment by AjKundnani** [comment]
> > 3. Set `--enable-secure-boot:false` and `--enable-vtpm:true` if not specified by end user.
> 
> Hi @AjKundnani . Should I set `--enable-secure-boot` to `false` if end user specifies it as `true`? What if end user sets one of the two parameters? For example, the user specifies `--enable-vtpm` as `false` while not specifying `--enable-secure-boot`.

End user parameter value takes preference always. Default value is applicable only if end user does not provides inputs.
- if end user sets --enable-secure-boot `true` then it's `true`, default value does not applies.
- if end user specifies --enable-vtpm `false` then --enable-vtpm is `false` and --enable-secure-boot uses default value of `false`

**Comment by ReaNAiveD** [comment]
> * CLI will validate securityType is currently set to `null` or `TrustedLaunch` using VMSS attributes.

Hi @AjKundnani , What should we do if current value of `securityType` is `TrustedLaunch`? Should we set the default value of `--enable-secure-boot` and `--enable-vtpm` if the user does not specify them in such condition?

**Comment by AjKundnani** [comment]
> > * CLI will validate securityType is currently set to `null` or `TrustedLaunch` using VMSS attributes.
> 
> Hi @AjKundnani , What should we do if current value of `securityType` is `TrustedLaunch`? Should we set the default value of `--enable-secure-boot` and `--enable-vtpm` if the user does not specify them in such condition?

If VMSS is already using `TrustedLaunch`, I do not anticipate end users specifying parameter `--security-type` with az vmss update command.
The defaults will apply only when end user is running `az vmss update --security-type` command to enable TrustedLaunch.

Corner case end user does it erroneously then ideally we should skip changing any of values related to securityType, secureBoot & vTPM.

**Comment by ReaNAiveD** [comment]
> * **VMSS Gen1/Gen2 -> Trusted Launch Upgrade** is currently in Private preview and enabled in specific regions. Refer to [Enable Trusted Launch on existing VMSS](https://eng.ms/docs/cloud-ai-platform/azure-core/core-compute-and-host/compute-platform-arunki/vmss-team-docs/documents/gen1totlmigrationonboardingdoc) for more details.

Hi @AjKundnani , according to the document, I attempted to register the feature flag `Microsoft.Compute/ImageSkuGenUpdateWithVMSS`, but I got an `FeatureRegistrationUnsupported` error as shown below.
![image](https://github.com/Azure/azure-cli/assets/32201005/f8b62b94-1766-43c8-b96a-3116c6c62e00)
Can you help me with the problem?
