### ISSUE TITLE
"az acs kubernetes install-cli" should indicate where kubectl was placed

### ISSUE THREAD

**Issue by mjrousos** [Azure/azure-cli#2700]
Currently, "az acs kubernetes install-cli" doesn't give any console output if it succeeds. It also doesn't add the kubectl install location to the path.

As someone new to K8s, I understood from docs that 'az acs kubernetes install-cli' would install kubectl for me, but when it finished I was left to search for kubectl on my computer since there was no indication of where it was or how to call it.

A simple message saying "Kubectl.exe successfully installed at C:\Program Files (x86)\kubectl.exe" would have been a better experience.

**Comment by brendandburns** [comment]
@mjrousos See https://github.com/Azure/azure-cli/pull/2701 for a fix.
