### ISSUE TITLE
"az sig update" ability to update gallery that has SoftDeletePolicy set to False

### ISSUE THREAD

**Issue by user127057** [Azure/azure-cli#27017]
**Related command**
az sig update

**Is your feature request related to a problem? Please describe.**
For Azure Shared Image Galleries (SIG) with property “softDeletePolicy”  set to False, instead of Null, "az sig update" is failing with error: "Subscription is not registered with the feature Microsoft.Compute/SigSoftDelete. Please register the subscription before retrying the call"
![image](https://github.com/Azure/azure-cli/assets/140574211/bab60e1c-cb56-4fbe-9c4e-83835a31b9d1)

**Describe the solution you'd like**
Be able to use "az sig update" to update Azure Shared Image Galleries (SIG) whose property “softDeletePolicy” was set to False.

**Describe alternatives you've considered**
Right now, newly created Azure Shared Image Galleries (SIG) property “softDeletePolicy” is set to Null by default.

**Additional context**
+Cx  had three galleries which were created in April 2022, all having this the issue. The same happens when calling powershell command "Update-AzGallery"

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
> "Subscription is not registered with the feature Microsoft.Compute/SigSoftDelete. Please register the subscription before retrying the call"

I guess this is because this feature is still in the private preview stage and requires customers to register it first. @kangsun-ctrl Could you please take a look at this issue?

**Comment by user127057** [comment]
Thanks for the reply, but
+Cx had never set this “softDeletePolicy" when creating the gallery. According to MS Product team, this feature is not currently supposed to be used/registered. 

+Not sure why Cx gallery, which was created back in April 2022, had this property set to False instead of Null at the beginning.

+Now, since “softDeletePolicy" is False, is there a work around to update/change this property, so that Cx can keep using "az sig update" to update his gallery.

**Comment by kangsun-ctrl** [comment]
@zhoxing-ms  hey Xing, looks like this issue is a regression on https://github.com/Azure/azure-cli/issues/20658, the mentioned issue should prevent this problem.

@user127057 Hey for your mitigation, the easiest one is to use ARM template to deploy the change, and when you input gallery, do not include softDeletePolicy in the payload, then you should be fine I think.

**Comment by TravisCragg-MSFT** [comment]
@sandeepraichura FYI

**Comment by user127057** [comment]
> @zhoxing-ms hey Xing, looks like this issue is a regression on #20658, the mentioned issue should prevent this problem.
> 
> @user127057 Hey for your mitigation, the easiest one is to use ARM template to deploy the change, and when you input gallery, do not include softDeletePolicy in the payload, then you should be fine I think.

Thanks @kangsun-ctrl message. We actually tried to deploy using ARM template, but after deployment, this softDeletePolicy showed up again and set to False for some reason.

**Comment by kangsun-ctrl** [comment]
> > @zhoxing-ms hey Xing, looks like this issue is a regression on #20658, the mentioned issue should prevent this problem.
> > @user127057 Hey for your mitigation, the easiest one is to use ARM template to deploy the change, and when you input gallery, do not include softDeletePolicy in the payload, then you should be fine I think.
> 
> Thanks @kangsun-ctrl message. We actually tried to deploy using ARM template, but after deployment, this softDeletePolicy showed up again and set to False for some reason.

@user127057  in my opinion, it is fine that it is false since it is actually false, but i can modify it to null for you in the backend if you want. The problem happens due to a past regression in SIG side and unfortunately your gallery was created during that time so it has 'false' as the softDeletePolicy, we fix the issue and after that, it is always null if you do not input it.

**Comment by user127057** [comment]
@user127057 in my opinion, it is fine that it is false since it is actually false, but i can modify it to null for you in the backend if you want. The problem happens due to a past regression in SIG side and unfortunately your gallery was created during that time so it has 'false' as the softDeletePolicy, we fix the issue and after that, it is always null if you do not input it.

+Thanks for the information. These galleries belong to one customer, let me check with customer and maybe you can help reset it on one gallery for test. What information do you need? Subscription ID and gallery resource URI?
+Customer just hopes to be able to use "az sig update" and "Update-AzGallery" command to update these galleries property, such as tags. Right now, with softDeletePolicy =False, it seems these commands keep failing.

**Comment by kangsun-ctrl** [comment]
@user127057 if the AzCLi fix got in, then cx should be able to do so, for my backend, i only need ARM id for this resource.

**Comment by user127057** [comment]
> @user127057 if the AzCLi fix got in, then cx should be able to do so, for my backend, i only need ARM id for this resource.

As you can see in the screenshot below, customer was using latest AzCLi in cloud shell, the fix should be in I assume, but still, seeing errors when attempting to update any property using "az sig update"
![image](https://github.com/Azure/azure-cli/assets/140574211/81663a36-b34b-4d50-b635-21c5e0f60b55)

What is ARM id, where can we find it? Thanks!

**Comment by kangsun-ctrl** [comment]
@user127057  what i mean is that CLI has a bug now, that's why this problem is surfacing while it was fine in the past.

The arm id is like /subscription/xxx/resourcegroup/xxx/Microsoft.Compute/Galleries/xxx

**Comment by user127057** [comment]
> CLI has a bug now, that's why this problem is surfacing while it was fine in the past.

Thanks Kangsun. We've got customer approval, how should I deliver the resource ID to you? is there an email address?

**Comment by user127057** [comment]
> @user127057 what i mean is that CLI has a bug now, that's why this problem is surfacing while it was fine in the past.
> 
> The arm id is like /subscription/xxx/resourcegroup/xxx/Microsoft.Compute/Galleries/xxx

HI @kangsun-ctrl    How can sent the ARM ID to you? I don't think we can put down here

**Comment by mikazka** [comment]
Hi @kangsun-ctrl I have loaded a ticket with MS but apparently they don't have access to change it. Are you able to set mine to null as well? I can ping you the arm ID directly

**Comment by kangsun-ctrl** [comment]
> Hi @kangsun-ctrl I have loaded a ticket with MS but apparently they don't have access to change it. Are you able to set mine to null as well? I can ping you the arm ID directly

Hey @mikazka  and @user127057 , you can send me the ARM id by email, thanks!

**Comment by sandeepraichura** [comment]
Hello @user127057 - Is this still an issue ? SoftDelete feature is not yet available and shouldn't be enabled.

**Comment by sandeepraichura** [comment]
needs-author-feedback
