### ISSUE TITLE
 No registered resource provider found for location 'eastus2' and API version '2023-04-01T00:00:00Z' for type 'privateEndpoints'

### ISSUE THREAD

**Issue by mananchoksi007** [Azure/azure-cli#27010]
### Describe the bug

We are using policy to add the dns entries in to DNS zones and we are getting error all the time with all dns zones. 

No registered resource provider found for location 'eastus2' and API version '2023-04-01T00:00:00Z' for type 'privateEndpoints'. The supported api-versions are '2019-02-01, 2019-04-01, 2019-06-01, 2019-07-01, 2019-08-01, 2019-09-01, 2019-11-01, 2019-12-01, 2020-01-01, 2020-03-01, 2020-04-01, 2020-05-01, 2020-06-01, 2020-07-01, 2020-08-01, 2020-11-01, 2021-01-01, 2021-02-01, 2021-03-01, 2021-04-01, 2021-05-01, 2021-06-01, 2021-08-01, 2021-12-01, 2022-01-01, 2022-05-01, 2022-07-01, 2022-09-01, 2022-11-01, 2023-02-01, 2023-04-01'. The supported locations are 'westus, eastus, northeurope, westeurope, eastasia, southeastasia, northcentralus, southcentralus, centralus, eastus2, japaneast, japanwest, brazilsouth, australiaeast, australiasoutheast, centralindia, southindia, westindia, canadacentral, canadaeast, westcentralus, westus2, ukwest, uksouth, koreacentral, koreasouth, francecentral, australiacentral, southafricanorth, uaenorth, switzerlandnorth, germanywestcentral, norwayeast, westus3, jioindiawest, swedencentral, qatarcentral, polandcentral'.

![image](https://github.com/Azure/azure-cli/assets/29955719/33f9aa8b-e4ee-4ec3-a425-4ccc44652717)

![image](https://github.com/Azure/azure-cli/assets/29955719/80252af6-ea86-4dc3-8a98-e40eab3c89fe)

### Related command

Azure

### Errors

No registered resource provider found for location 'eastus2' and API version '2023-04-01T00:00:00Z' for type 'privateEndpoints'. The supported api-versions are '2019-02-01, 2019-04-01, 2019-06-01, 2019-07-01, 2019-08-01, 2019-09-01, 2019-11-01, 2019-12-01, 2020-01-01, 2020-03-01, 2020-04-01, 2020-05-01, 2020-06-01, 2020-07-01, 2020-08-01, 2020-11-01, 2021-01-01, 2021-02-01, 2021-03-01, 2021-04-01, 2021-05-01, 2021-06-01, 2021-08-01, 2021-12-01, 2022-01-01, 2022-05-01, 2022-07-01, 2022-09-01, 2022-11-01, 2023-02-01, 2023-04-01'. The supported locations are 'westus, eastus, northeurope, westeurope, eastasia, southeastasia, northcentralus, southcentralus, centralus, eastus2, japaneast, japanwest, brazilsouth, australiaeast, australiasoutheast, centralindia, southindia, westindia, canadacentral, canadaeast, westcentralus, westus2, ukwest, uksouth, koreacentral, koreasouth, francecentral, australiacentral, southafricanorth, uaenorth, switzerlandnorth, germanywestcentral, norwayeast, westus3, jioindiawest, swedencentral, qatarcentral, polandcentral'.

### Issue script & Debug output

Azure

### Expected behavior

Azure

### Environment Summary

Azure Policy deployment

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
