### ISSUE TITLE
Update Azure LB inbound NAT rules create/update to block NAT64/46 

### ISSUE THREAD

**Issue by mahipdeora** [Azure/azure-cli#27013]
### Describe the bug

Currently, a user can create a Inbound NAT rule with a v6 frontend and a v4 backend. This is incorrect as traffic will not flow. Azure load balancer only supports NAT44 and NAT66. 

We would like the experience to be similar to how azure load balancing rule create/update handles this scenario. 

### Related command

az network lb inbound-nat-rule create
az network lb inbound-nat-rule Update

### Errors

None

### Issue script & Debug output

none 

### Expected behavior

An error needs to be thrown if the frontend IP type doesn't match the backend IP type. 

### Environment Summary

{
  "azure-cli": "2.50.0",
  "azure-cli-core": "2.50.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "account": "0.2.5",
    "ai-examples": "0.2.5",
    "ml": "2.18.0",
    "ssh": "1.1.6"
  }
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by mahipdeora** [comment]
Seems that the NRP team is missing the validation. Let us wait until we get that done before adding checks to CLI.
