### ISSUE TITLE
Upgrade subscription operation api version to 2022-12-01

### ISSUE THREAD

**Issue by gauravkumar1491** [Azure/azure-cli#27033]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az account list-locations

### Resource Provider

N/A

### Description of Feature or Work Requested

feature request to add a new parameters in the response list-locations API as part of new version 2022-12-01.

The new parameters are as follows : 

- availabilityZoneMappings
- geography (part of metadata)

The rest-api [Subscriptions - List Locations](https://learn.microsoft.com/en-us/rest/api/resources/subscriptions/list-locations?tabs=HTTP#code-try-0) response would look like : 

{
  "value": [
    {
      "id": "/subscriptions/a1ffc958-d2c7-493e-9f1e-125a0477f536/locations/eastus",
      "name": "eastus",
      "type": "Region",
      "displayName": "East US",
      "regionalDisplayName": "(US) East US",
      "metadata": {
        "regionType": "Physical",
        "regionCategory": "Recommended",
        "geography": "United States",
        "geographyGroup": "US",
        "longitude": "-79.8164",
        "latitude": "37.3719",
        "physicalLocation": "Virginia",
        "pairedRegion": [
          {
            "name": "westus",
            "id": "/subscriptions/a1ffc958-d2c7-493e-9f1e-125a0477f536/locations/westus"
          }
        ]
      },
      "availabilityZoneMappings": [
        {
          "logicalZone": "1",
          "physicalZone": "eastus-az1"
        },
        {
          "logicalZone": "2",
          "physicalZone": "eastus-az3"
        },
        {
          "logicalZone": "3",
          "physicalZone": "eastus-az2"
        }
      ]
    },

### Minimum API Version Required

2022-12-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/23292

### Request Example

Request : 
GET https://management.azure.com/subscriptions/{subscriptionId}/locations?api-version=2022-12-01

Response :  

{
  "value": [
    {
      "id": "/subscriptions/a1ffc958-d2c7-493e-9f1e-125a0477f536/locations/eastus",
      "name": "eastus",
      "type": "Region",
      "displayName": "East US",
      "regionalDisplayName": "(US) East US",
      "metadata": {
        "regionType": "Physical",
        "regionCategory": "Recommended",
        "geography": "United States",
        "geographyGroup": "US",
        "longitude": "-79.8164",
        "latitude": "37.3719",
        "physicalLocation": "Virginia",
        "pairedRegion": [
          {
            "name": "westus",
            "id": "/subscriptions/a1ffc958-d2c7-493e-9f1e-125a0477f536/locations/westus"
          }
        ]
      },
      "availabilityZoneMappings": [
        {
          "logicalZone": "1",
          "physicalZone": "eastus-az1"
        },
        {
          "logicalZone": "2",
          "physicalZone": "eastus-az3"
        },
        {
          "logicalZone": "3",
          "physicalZone": "eastus-az2"
        }
      ]
    },

### Target Date

2023-08-01

### PM Contact

ifeoluwa.okunoren@microsoft.com

### Engineer Contact

gakumar@microsoft.com

### Additional context

As per release 231.0b1, it should contain additional parameters that I added :

 
![image](https://github.com/Azure/azure-cli/assets/32332608/5f07808c-f528-4479-9d21-f97b7908a16f)

However, when I run the API via az cli on [az account | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fcli%2Fazure%2Faccount%3Fview%3Dazure-cli-latest%23code-try-7&data=05%7C01%7Cgakumar%40microsoft.com%7C98fafa55c38d4e8673a608db8f39cf5b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638261250724022732%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DkqDIPACWaOG%2BryE57uOAn5V6G7s0zz9B2MgGRgq1X8%3D&reserved=0), the response doesn’t contain the parameters, likely its using the older version of Python SDK  : 

![image](https://github.com/Azure/azure-cli/assets/32332608/ffab89d9-bec3-4074-947c-16f060be5d0f)

The reason for that is :  

In fact, this is because Azure CLI did not upgrade the api-version for subscriptions operation, as CLI only upgraded the SDK version without upgrading the api-version of subscription operation (the api-version and SDK version are not in a binding upgrade relationship in Azure CLI)
At present, the api-version set for subscription operation is still [2019-11-01](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-cli%2Fblob%2Fdev%2Fsrc%2Fazure-cli-core%2Fazure%2Fcli%2Fcore%2Fprofiles%2F_shared.py%23L183&data=05%7C01%7Cgakumar%40microsoft.com%7C98fafa55c38d4e8673a608db8f39cf5b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638261250723866515%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YhKtk0k4CEUUcm3QRdLOKwNjpMQ5Cjy%2FJ98fJJDLm4I%3D&reserved=0), so it may not return the contents included in the later api-version from REST.

![image](https://github.com/Azure/azure-cli/assets/32332608/d8427a52-4199-41d7-9f1b-e8a5597fe7e9)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
@gauravkumar1491 As our work for this sprint is already scheduled, we plan to develop and release it in the next sprint. Could you accept us releasing it in early October?

**Comment by gauravkumar1491** [comment]
@zhoxing-ms 09-26 would be too late. Can we do it by 08-15 ?

**Comment by zhoxing-ms** [comment]
@gauravkumar1491 Sorry, we usually do not release the out of boundary release for normal features but only for bug fix. 
Moreover, due to the late submission of this feature, our work schedule was already very full. 
Could you accept us providing you with a private package from Edge build in early September for release on **09-26**?

**Comment by gauravkumar1491** [comment]
@zhoxing-ms Yes, please proceed and update as soon as possible

**Comment by zhoxing-ms** [comment]
Hi @gauravkumar1491 We found that there are some issues that need to be discussed for directly adding the new parameter `--include-extended-locations` to command `az account list-locations`, as the previous design of command `az account list-locations` was not very reasonable and easy to confuse, especially in the `account` extension, there is a `az account subscription list-location` command with similar functionality and naming.
For the more detailed discussions, please refer to https://github.com/Azure/azure-cli/pull/27400#discussion_r1327276057
Therefore, we would like to postpone the release of this feature to the next sprint **(11-15)**, so that we can design a better solution for customers. Do you think this is acceptable?

**Comment by zhoxing-ms** [comment]
@Jing-song Could you please take a look at the above question?

**Comment by Jing-song** [comment]
> @zhoxing-ms I saw the discussion where you're planning to deprecate az account list-locations and change it to az subscription list-locations . But before you do that can you first implement this feature in this sprint to use the latest Python SDK which adds availabilityZoneMappings and geography as part of response.
> 
> adding the new parameter --include-extended-locations doesn't describe this feature request, I am not sure where this came from.
> 
> But can you please make the availabilityZoneMappings and geography change for az account list-locations in this sprint and then move this to az subscription list-locations .

The link([Subscriptions - List Locations](https://learn.microsoft.com/en-us/rest/api/resources/subscriptions/list-locations?tabs=HTTP#code-try-0)) in the description contains this parameter(`--include-extended-locations`)

`availabilityZoneMappings` and `geography` are included in the new [response](https://github.com/Azure/azure-cli/pull/27400/files#diff-ef876d58099baf761fb6f20c0aa11991830c232a37b137875c103839524b684cR5638-R5646)
