### ISSUE TITLE
support for Cosmos DB for PostgreSQL

### ISSUE THREAD

**Issue by MarioGruda** [Azure/azure-cli#27030]
It seems there is no way to manage a Cosmos DB for PostgreSQL resources on Azure with the Azure CLI (Perhaps I have been looking in the wrong place? I'm still a bit surprised and looking for my mistake).  Previously, the resource was 
known as PostgreSQL Citus Hyperscale.

There is documentation on the REST API https://learn.microsoft.com/en-us/rest/api/postgresqlhsc

The type is `Microsoft.DBforPostgreSQL/serverGroupsv2`

**Related command**
* `az cosmosdb`

**Is your feature request related to a problem? Please describe.**
We would like to automate the setup of our Azure infrastructure with Terraform (APP service, CosPos, ...). However, we do not seem to have the possibility to automatically retrieve the connection string with Terraform at the moment. Until then, we wanted to automate the retrieval of the connection string via the azure cli, but there seems to be no support for the resource.

**Describe the solution you'd like**
azure cli support for Cosmos DB for PostgreSQL

**Describe alternatives you've considered**
Using the REST-API directly

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by MarioGruda** [comment]
The support was implemented with the following commit: https://github.com/Azure/azure-cli/commit/c9039dd747db13a2046c9146f591f73c81950e13

Sorry, I should have searched better
