### ISSUE TITLE
User is not able to access the Azure using Azure CLI

### ISSUE THREAD

**Issue by AKTTMR** [Azure/azure-cli#27031]
### Describe the bug

User is not able to access the Azure using Azure CLI even after fulfilling the Conditions configured in the Conditional Access Policy while using VPN.

### Related command

az login

### Errors

You cannot access this right now.

Your Sign-in was successful but does not meet the criteria to access this resource. For example, you might be signing in from a browser, app, or location that is restricted by your admin.

### Issue script & Debug output

NA

### Expected behavior

User should be able to login to Azure CLI

### Environment Summary

NA

### Additional context

We have raised a case with Microsoft regarding the same. Case ID---2307260050002272

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
This issue is not caused by Azure CLI and should be investigated by AAD team.
