### ISSUE TITLE
Azure CLI 2.51.0 cannot be released to Homebrew

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#27047]
Latest `pip` fails to install `azure-mgmt-consumption` 2.0.0 from source code https://pypi.org/project/azure-mgmt-consumption/2.0.0/#files

This make homebrew fail to install Azure CLI (https://github.com/Homebrew/homebrew-core/pull/138158):

https://github.com/Homebrew/homebrew-core/actions/runs/5722058178/job/15504679804?pr=138158

```
2023-08-01T03:12:33.5413100Z   creating '/private/tmp/pip-modern-metadata-vjgv3zcx/azure_mgmt_consumption-2.0.0.dist-info'
2023-08-01T03:12:33.5413250Z   error: error in setup.cfg: command 'bdist_wheel' has no such option 'azure_namespace_package'
2023-08-01T03:12:33.5413340Z   error: subprocess-exited-with-error
```

To repro locally:

```
> pip uninstall -y wheel
> pip install https://files.pythonhosted.org/packages/8c/f0/e2d94b246e2dce71eff8d362836a1979f02b4185f5403a13e4fb26c07ccb/azure-mgmt-consumption-2.0.0.zip
Collecting https://files.pythonhosted.org/packages/8c/f0/e2d94b246e2dce71eff8d362836a1979f02b4185f5403a13e4fb26c07ccb/azure-mgmt-consumption-2.0.0.zip
  Using cached azure-mgmt-consumption-2.0.0.zip (56 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Wheel is not available, disabling bdist_wheel hook
      running dist_info
      creating C:\Users\xxx\AppData\Local\Temp\pip-modern-metadata-v6_4olsi\azure_mgmt_consumption.egg-info
      writing C:\Users\xxx\AppData\Local\Temp\pip-modern-metadata-v6_4olsi\azure_mgmt_consumption.egg-info\PKG-INFO
      writing dependency_links to C:\Users\xxx\AppData\Local\Temp\pip-modern-metadata-v6_4olsi\azure_mgmt_consumption.egg-info\dependency_links.txt
      writing requirements to C:\Users\xxx\AppData\Local\Temp\pip-modern-metadata-v6_4olsi\azure_mgmt_consumption.egg-info\requires.txt
      writing top-level names to C:\Users\xxx\AppData\Local\Temp\pip-modern-metadata-v6_4olsi\azure_mgmt_consumption.egg-info\top_level.txt
      writing manifest file 'C:\Users\xxx\AppData\Local\Temp\pip-modern-metadata-v6_4olsi\azure_mgmt_consumption.egg-info\SOURCES.txt'
      reading manifest file 'C:\Users\xxx\AppData\Local\Temp\pip-modern-metadata-v6_4olsi\azure_mgmt_consumption.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      writing manifest file 'C:\Users\xxx\AppData\Local\Temp\pip-modern-metadata-v6_4olsi\azure_mgmt_consumption.egg-info\SOURCES.txt'
      creating 'C:\Users\xxx\AppData\Local\Temp\pip-modern-metadata-v6_4olsi\azure_mgmt_consumption-2.0.0.dist-info'
      error: error in setup.cfg: command 'bdist_wheel' has no such option 'azure_namespace_package'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
@jsntcy, It seems `azure-mgmt-consumption` 2.0.0 is still Track 1. Can we migrate it to Track 2?

**Comment by bebound** [comment]
This only occurs in pip>=23.1, see discussion in https://github.com/pypa/pip/issues/8559

**Comment by bebound** [comment]
I guess this related changes in pip 23.1:
> When the wheel package is not installed, pip now uses the default build backend instead of setup.py install and setup.py develop for project without pyproject.toml. ([#8559](https://github.com/pypa/pip/issues/8559)) -- https://pip.pypa.io/en/stable/news/#v23-1

**Comment by jiasli** [comment]
https://github.com/Azure/azure-cli/blob/dev/doc/track_2_migration_roadmap.md keeps track of the Track 2 SDK migration progress. To verify the current status, I wrote the below script to print all Track 1 SDKs Azure CLI is still using:

```py
import os
from importlib import import_module

import azure.mgmt

azure_mgmt_dir = azure.mgmt.__path__[0]

print("""| sdk | version | pypi |
| - | - | - |""")

track_1_sdks = {}
for sdk in os.listdir(azure_mgmt_dir):
    sdk_path = os.path.join(azure_mgmt_dir, sdk)
    # Track 1 SDK contains version.py; Track 2 SDK contains _version.py
    if os.path.isdir(sdk_path) and 'version.py' in os.listdir(sdk_path):
        sdk_module_name = f'azure.mgmt.{sdk}'
        sdk_module = import_module(sdk_module_name)
        version = sdk_module.version.VERSION
        package_name = f'azure-mgmt-{sdk}'
        pypi_link = f'https://pypi.org/project/{package_name}/{version}/#files'
        print(f'| {sdk_module_name} | {version} | {pypi_link} |')
```

Result:

| sdk | version | pypi |
| - | - | - |
| azure.mgmt.consumption | 2.0.0 | https://pypi.org/project/azure-mgmt-consumption/2.0.0/#files |
| azure.mgmt.devtestlabs | 4.0.0 | https://pypi.org/project/azure-mgmt-devtestlabs/4.0.0/#files |
| azure.mgmt.kusto | 0.3.0 | https://pypi.org/project/azure-mgmt-kusto/0.3.0/#files |
| azure.mgmt.managedservices | 1.0.0 | https://pypi.org/project/azure-mgmt-managedservices/1.0.0/#files |
| azure.mgmt.relay | 0.1.0 | https://pypi.org/project/azure-mgmt-relay/0.1.0/#files |

Amongst them, only `azure-mgmt-consumption` and `azure-mgmt-relay` contain `azure_bdist_wheel.py`.

**Additional information**

Using `version.py` and `_version.py` to detect Track 1 or Track 2 SDK is inspired by https://github.com/Azure/azure-cli/blob/b6ebd6fac6342c1112c2bb03927509d39263cdee/src/azure-cli-core/azure/cli/core/util.py#L457-L467

The detection method Azure CLI core uses is too complex in this case: https://github.com/Azure/azure-cli/blob/b6ebd6fac6342c1112c2bb03927509d39263cdee/src/azure-cli-core/azure/cli/core/util.py#L668-L674

**Comment by jiasli** [comment]
https://github.com/Azure/azure-cli/pull/25452 contains detailed explanation for breaking changes discovered during one of the most complex Track 2 SDK migrations - `azure-mgmt-authorization`. If none or only a few of these breaking changes are hit by `consumption` and `relay` command modules, the effort for migrating to Track 2 SDK is rather small, as we only need to bump the SDK and re-record all tests.

We also need to evaluate other options such as using code-gen to regenerate these modules.

**Comment by chenrui333** [comment]
I closed [the bot PR](https://github.com/Homebrew/homebrew-core/pull/138158), once the issue got sorted out, feel free to open a new one.

**Comment by bebound** [comment]
`azure-mgmt-datalake-analytics 0.2.1` also fails with same error.

**Comment by bebound** [comment]
@chenrui333   If I install this formula, `setuptools` and `pip` are not installed automatically, do you have any idea?
[azure-cli.txt](https://github.com/Azure/azure-cli/files/12332206/azure-cli.txt)

**Comment by bebound** [comment]
I see, it's caused by https://github.com/Homebrew/brew/pull/15792.
We need to add `without_pip: false` in formula. I'll fix it.

**Comment by branchvincent** [comment]
Yea `without_pip: false` is a good short-term workaround. Long term, I'd recommend either

1. Explicitly depending on `setupools` (needed anyway for python 3.12+ https://github.com/python/cpython/issues/95299)
2. If you just need to declare a namespace package, use an [implicit namespace](https://peps.python.org/pep-0420/)

**Comment by bebound** [comment]
@branchvincent  Thanks for your helpful reminder.
Both `setuptools` and `pip` is needed in azure-cli.

**Comment by chenrui333** [comment]
@bebound looks like `azure-mgmt-consumption 3.0.0` has already removed `azure_bdist_wheel`, why not bump to that dependency? (I have done the pip install for that sdist, which works fine in my local)

**Comment by bebound** [comment]
`azure-mgmt-relay` is not removed yet.
- https://github.com/Azure/azure-cli/pull/27207
- https://github.com/Azure/azure-cli/pull/27152

**Comment by scanyard** [comment]
This issue hasn't been updated in a bit - the build of `azure-cli` available in homebrew is now 2 months old. Is this close to being fixed?

**Comment by chenrui333** [comment]
@bebound this can also be removed from the pinned issue list?

**Comment by bebound** [comment]
`azure-mgmt-datalake-store==0.5.0` makes formula fails to build again.
```
Last 15 lines from /Users/runner/Library/Logs/Homebrew/azure-cli/41.python3.11:
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/local/Cellar/azure-cli/2.61.0/libexec/bin/python /usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /private/tmp/tmp8t6xbm2g
  cwd: /private/tmp/azure-cli--azure-mgmt-datalake-store-20240626-12379-yfbs8f/azure-mgmt-datalake-store-0.5.0
  Preparing metadata (pyproject.toml): finished with status 'error'
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: python -m pip install --upgrade pip

Do not report this issue to Homebrew/brew or Homebrew/homebrew-core!

```

Log: https://dev.azure.com/azclitools/public/_build/results?buildId=167640&view=logs&jobId=ebe8970d-a8af-5d7e-4086-8f4ce0be006b&j=ebe8970d-a8af-5d7e-4086-8f4ce0be006b&t=3f22f999-770c-5d06-3bb8-1a936f5d8384

It uses `azure_bdist_wheel`, but is compatible with latest wheel. (In 2.51.0, those pacakges are not compatible with latest wheel and fails to install.)

I can repro the same error in `python:3.11-slim` image:
```
pip uninstall -y wheel
pip install  https://files.pythonhosted.org/packages/00/13/037f0128bdfcd47253f69a3b4ca6a7ff7b673b35832bc48f7c74df24a9be/azure-mgmt-datalake-store-0.5.0.zip --no-deps
```

I have no idea why it worked before and fails now.
Maybe there are some changes in brew or setuptools?

AFAIK, latest `setuptools` now has a vendored wheel 0.4.3.

**Comment by bebound** [comment]
@chenrui333 Is any change in brew about my [previous comment](https://github.com/Azure/azure-cli/issues/27047#issuecomment-2191203916)?

**Comment by bebound** [comment]
I find the cause: the change in `setuptools` 70.1: https://github.com/pypa/setuptools/commit/b3d3e93a834426f1bef8712e1405495084eb3b7f#diff-0480ca57cef22161092786457725dbe93e08344a9d8fb3bb0c1b68d19d5ea395R325

When building wheel from source code, `setuptools` craetes an isolated build environment. Previously, it installs `wheel` because it's required in `python setup.py bdist_wheel` command.
In 70.1, `setuptools` has a vendor wheel, and it removes `wheel` from requirement.
However, `azure-mgmt-datalake-store==0.5.0` still requires `wheel` in https://github.com/Azure/azure-sdk-for-python/blob/azure-mgmt-datalake-analytics_0.5.0/azure-mgmt-datalake-store/azure_bdist_wheel.py#L10. So it fails to build. 


This change in setuptools also make us to pin 70.0 in azure-cli-extension to keep using `wheel 0.3.0`: https://github.com/Azure/azure-cli-extensions/pull/7739

---------------

Here are some old technologies we're using:
**Track 1 SDK**
```
azure-mgmt-kusto==0.3.0
azure-mgmt-devtestlabs==4.0.0
azure-graphrbac==0.60.0

azure-mgmt-managedservices~=1.0 in setup.py
```
**wheel 0.3.0**
Used in azure-cli-extension: https://github.com/Azure/azure-cli-extensions/pull/6842

**Legacy PEP420**
It uses `setuptools` instead of `find_namespace_pacakge`: https://github.com/Azure/azure-cli/blob/05c898c24cb7c6be5a3ffe27407b04423ba6ef5b/src/azure-cli/azure/__init__.py#L5

We need to apply this in 3.12: https://github.com/Azure/azure-cli/pull/27196

**No `pyproject.toml`**
https://setuptools.pypa.io/en/latest/build_meta.html#
