### ISSUE TITLE
unattended install for cli2.0

### ISSUE THREAD

**Issue by dhermans** [Azure/azure-cli#2704]
hi,
is there a way to perform an unattended install of cli2.0?

for comparison aws cli is a simple 'pip install awscli' 

this is convenient to preload the cli into packer images etc..

**Comment by IainColledge** [comment]
This is what i do for Docker, hope it helps

```
RUN pip install --user azure-cli
ENV PATH "$PATH:/<user path>/.local/bin/"
# Add any components etc
RUN az component update --add acr
```

**Comment by tjprescott** [comment]
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli

Pip install is the way to go. If you are installing on Linux, be sure to check out the prerequisites section in the install guid.

**Comment by dhermans** [comment]
@IainColledge @tjprescott  Thanks!
