### ISSUE TITLE
Add --enable-hibernation support for azure vmss create

### ISSUE THREAD

**Issue by vatsan28** [Azure/azure-cli#27070]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az vmss `--enable-hibernation`

### Resource Provider

Microsoft.Compute/VirtualMachineScaleSets

### Description of Feature or Work Requested

This request is for adding VM hibernate support in VMSS create/update. The support for VM was added in: https://github.com/Azure/azure-cli/issues/19611. We would like to enable this feature to support `hibernate` query parameter in the deallocate VMSS VM operation(https://github.com/Azure/azure-cli/issues/26938).

### Minimum API Version Required

2021-03-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/15067

### Target Date

2023-09-05

### PM Contact

jainan

### Engineer Contact

srivmura

### Additional context

This work was identified in the process of trying to add optional parameter - hibernate to the deallocate VMSS VM api for flex. Link: https://github.com/Azure/azure-cli/issues/26938

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
