### ISSUE TITLE
az vm run-command invoke, this command takes a long time to finish on the Activity Log

### ISSUE THREAD

**Issue by tranvanthuc365** [Azure/azure-cli#27085]
### Describe the bug

<img width="526" alt="image" src="https://github.com/Azure/azure-cli/assets/79855897/34be69d2-1707-4ff6-bb84-5a4dc409f1eb">

<img width="305" alt="image" src="https://github.com/Azure/azure-cli/assets/79855897/6df0ff40-3d21-4548-8220-33dce8a27fb1">

az vm run-command invoke  --command-id RunPowerShellScript --name dev-vm -g dev-rg --scripts "C:\projects\download_code\deploy.ps1"

I checked inside the VM and this deploy.ps1 is finished, but on the ActivityLog it's not finished. 
I can use --no-wait to finish the pipeline, but in the background (Activity Log) is still running, and take a long time to finish, also I can't run new command to deploy new code in that time.

### Related command

`az vm run-command invoke  --command-id RunPowerShellScript --name dev-vm -g dev-rg --scripts "C:\projects\download_code\deploy.ps1"`

### Errors

My Pipeline is timeout,  I can't re-run the pipeline to trigger the command inside the VM, (it has status is pending)

### Issue script & Debug output

`az vm run-command invoke  --command-id RunPowerShellScript --name dev-vm -g dev-rg --scripts "C:\projects\download_code\deploy.ps1"`

`
npm i

npm run build

pm2 start dist\main.js --name "App"

`

### Expected behavior

1 - Why does it take a long time, and may I optimize the time?
2 - Is there a solution trigger to run a script inside the Azure VM Windows?
(I create a pipeline to build/re-deploy the app on Azure VM Windows)

### Environment Summary

azure-cli                         2.50.0 *

core                              2.50.0 *
telemetry                          1.0.8 *

Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\synergenx-team2\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

### Additional context

When I run it on my local laptop, it still takes a long time, it is the same as when the pipeline is triggered.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by vivlingaiah** [comment]
@tranvanthuc365 tranvanthuc365 ,
   Are you still facing issues like these ? We can investigate if needed.

Also, at this time we recommend using Managed Run Command. You'd be able to use multiple run commands even if one of the Run Commands gets stuck. 
https://aka.ms/ManagedRunCommandWindows

Also, you'd be able to debug by getting the errors with the execution of Run Command:
https://learn.microsoft.com/en-us/azure/virtual-machines/windows/run-command-managed#get-a-run-command-instance-view-for-a-vm-after-creating-or-updating-run-command

**Comment by GabstaMSFT** [comment]
@tranvanthuc365 checking to see if you are still having this issue?

**Comment by GabstaMSFT** [comment]
@tranvanthuc365, we haven’t been able to reach you in our last few attempts. Perhaps this is a bad time for you right now due to other obligations or you no longer need assistance. To avoid further ‘spam’ from me trying to contact you I will be closing your issue for now.

Your issue is important to us, and we want to ensure you do get the help you need so if at any time you want to continue working on this issue, please reopen the issue and we would be happy to continue to assist you.
