### ISSUE TITLE
az login using python stack fails

### ISSUE THREAD

**Issue by oscarenzo** [Azure/azure-cli#27084]
### Describe the bug

Hello,

I've a little program that list the deployments from **iothub**, the code that run is like this:

`iot edge deployment list --subscription {subscription_name} -n {iothub_name} --output none""".split()
`
I'm using the python library 'azure.cli.core' like this in my script:

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from azure.cli.core import get_default_cli
```

For after can run the before command using this (replacing the command variable by the before string):

```
cli = get_default_cli()
cli.invoke(command)
```

I'm running this script from Azure pipeline and cloud agents, my problem is that after run this command (located in my python script as **_rings function_**) like this:

```
def rings(params):
  .....
   iot edge deployment list --subscription {subscription_name} -n {iothub_name} --output none""".split()
```

As login method, in the same script I'm using the follow method (Invoking using azure.cli.core):

`login --service-principal --username {azure_service_principal_url} --password {azure_service_principal_password} --tenant {azure_service_principal_tenant}
`
But, there a weird case, the first time that my pipeline work in a fresh agent, it fail with this error:

```
Traceback (most recent call last):
  File "/mnt/bin/script-manage.py", line 64, in <module>
    base_ring_list = rings(genParams=deployParams)
  File "/mnt/bin/azhelper.py", line 378, in rings
TypeError: 'NoneType' object is not iterable
```

But if I relaunch the same pipeline and the job is managed by the same agent, the script it works, somebody has facing by similar issue?

Thank you, best regards.

### Related command

az login
az iot edge deployment list

### Errors

Traceback (most recent call last):
  File "/mnt/bin/script-manage.py", line 64, in <module>
    base_ring_list = rings(genParams=deployParams)
  File "/mnt/bin/azhelper.py", line 378, in rings
TypeError: 'NoneType' object is not iterable

### Issue script & Debug output

```
Starting: Job name
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.212.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /agent/_work/_temp/¿?.sh
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "¿?¿?¿¿¿¿?¿?",
    "id": "¿?¿?¿?¿?¿?¿?¿",
    "isDefault": true,
    "managedByTenants": [],
    "name": "¿?¿?-Dev",
    "state": "Enabled",
    "tenantId": "¿?¿?¿¿¿¿?¿?",
    "user": {
      "name": "http://¿?",
      "type": "servicePrincipal"
    }
  },
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "¿?¿?¿¿¿¿?¿?",
    "id": "¿?¿?¿",
    "isDefault": false,
    "managedByTenants": [],
    "name": "¿?¿?-Prd",
    "state": "Enabled",
    "tenantId": "¿?¿?¿¿¿¿?¿?",
    "user": {
      "name": "http://¿?",
      "type": "servicePrincipal"
    }
  }
]
Traceback (most recent call last):
  File "/mnt/bin/script-manage.py", line 64, in <module>
    base_ring_list = rings(genParams=deployParams)
  File "/mnt/bin/azhelper.py", line 378, in rings
TypeError: 'NoneType' object is not iterable

```

### Expected behavior

Should be list the deployments in the iothub and subscription desired.

### Environment Summary

azure_cli-2.51.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by DevonK3** [comment]
I am facing similar issues. `az upgrade` will not even work.

 ~  az upgrade --verbose
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Your current Azure CLI version is 2.50.0. Latest version available is 2.51.0.
Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
Do you want to continue? (Y/n): y
Already up-to-date.
Warning: azure-cli 2.50.0_1 already installed
CLI upgrade failed or aborted.
Command ran in 11.050 seconds (init: 0.211, invoke: 10.840)

PS /Users/devonkelly> az --version
azure-cli                         2.50.0 *

core                              2.50.0 *
telemetry                          1.0.8 *

Extensions:
account                            0.2.3
aks-preview                       0.5.98
azure-devops                      0.25.0
k8s-configuration                  1.7.0
resource-graph                     2.1.0

Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2

Python location '/usr/local/Cellar/azure-cli/2.50.0_1/libexec/bin/python'
Extensions directory '/Users/devonkelly/.azure/cliextensions'

Python (Darwin) 3.10.12 (main, Jun 20 2023, 17:00:24) [Clang 14.0.3 (clang-1403.0.22.14.1)]

Legal docs and information: aka.ms/AzureCliLegal


You have 3 update(s) available. Consider updating your CLI installation with 'az upgrade'

**Comment by DevonK3** [comment]
For some user accounts `az login` works. For others, I get this error:

The command failed with an unexpected error. Here is the traceback:
WsTrust server returned error in RSTR: {'reason': 'ID3242: The security token could not be authenticated or authorized.', 'code': 'a:FailedAuthentication'}
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.50.0_1/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.50.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.50.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.50.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.50.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.50.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.50.0_1/libexec/lib/python3.10/site-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/usr/local/Cellar/azure-cli/2.50.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 157, in login
    user_identity = identity.login_with_username_password(username, password, scopes=scopes, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.50.0_1/libexec/lib/python3.10/site-packages/azure/cli/core/auth/identity.py", line 172, in login_with_username_password
    result = self._msal_app.acquire_token_by_username_password(username, password, scopes, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.50.0_1/libexec/lib/python3.10/site-packages/msal/application.py", line 1610, in acquire_token_by_username_password
    response = _clean_up(self._acquire_token_by_username_password_federated(
  File "/usr/local/Cellar/azure-cli/2.50.0_1/libexec/lib/python3.10/site-packages/msal/application.py", line 1637, in _acquire_token_by_username_password_federated
    wstrust_result = wst_send_request(
  File "/usr/local/Cellar/azure-cli/2.50.0_1/libexec/lib/python3.10/site-packages/msal/wstrust_request.py", line 69, in send_request
    return parse_response(resp.text)
  File "/usr/local/Cellar/azure-cli/2.50.0_1/libexec/lib/python3.10/site-packages/msal/wstrust_response.py", line 49, in parse_response
    raise RuntimeError("WsTrust server returned error in RSTR: %s" % (error or body))
RuntimeError: WsTrust server returned error in RSTR: {'reason': 'ID3242: The security token could not be authenticated or authorized.', 'code': 'a:FailedAuthentication'}

**Comment by oscarenzo** [comment]
Hello all,

Thank you by the comments, I'm still facing this problems, somebody get to fix this situation?, maybe some CLI version, some authentication method or some like this that be compatible with the Azure pipelines?

Thank you, best regards.

**Comment by jiasli** [comment]
@oscarenzo, running Azure CLI command by programmatically creating Azure CLI instance with `get_default_cli` like below is NOT support.

```py
from azure.cli.core import get_default_cli
cli = get_default_cli()
cli.invoke(command)
```
I guess you find this approach from internet posts such as https://stackoverflow.com/questions/51546073/how-to-run-azure-cli-commands-using-python, but none of these are published by Microsoft.

Azure CLI can only be invoked via `az` command. You may use [`subprocess`](https://docs.python.org/3/library/subprocess.html) to call `az` for example.

--- 

As for

```
Traceback (most recent call last):
File "/mnt/bin/script-manage.py", line 64, in
base_ring_list = rings(genParams=deployParams)
File "/mnt/bin/azhelper.py", line 378, in rings
TypeError: 'NoneType' object is not iterable
```

This error is not related to Azure CLI, as no Azure CLI code path appears in the call stack. You will need to look at the source code of `/mnt/bin/azhelper.py:378` and see why it fails with `TypeError: 'NoneType' object is not iterable`.

**Comment by jiasli** [comment]
@DevonK3, your error `WsTrust server returned error in RSTR: {'reason': 'ID3242: The security token could not be authenticated or authorized.', 'code': 'a:FailedAuthentication'}` is a different topic. Please refer to https://github.com/Azure/azure-cli/issues/21050.

**Comment by oscarenzo** [comment]
> @oscarenzo, running Azure CLI command by programmatically creating Azure CLI instance with `get_default_cli` like below is NOT support.
> 
> ```python
> from azure.cli.core import get_default_cli
> cli = get_default_cli()
> cli.invoke(command)
> ```
> 
> I guess you find this approach from internet posts such as https://stackoverflow.com/questions/51546073/how-to-run-azure-cli-commands-using-python, but none of these are published by Microsoft.
> 
> Azure CLI can only be invoked via `az` command. You may use [`subprocess`](https://docs.python.org/3/library/subprocess.html) to call `az` for example.
> 
> As for
> 
> ```
> Traceback (most recent call last):
> File "/mnt/bin/script-manage.py", line 64, in
> base_ring_list = rings(genParams=deployParams)
> File "/mnt/bin/azhelper.py", line 378, in rings
> TypeError: 'NoneType' object is not iterable
> ```
> 
> This error is not related to Azure CLI, as no Azure CLI code path appears in the call stack. You will need to look at the source code of `/mnt/bin/azhelper.py:378` and see why it fails with `TypeError: 'NoneType' object is not iterable`.

Yes, I found this link and used as reference, As you said I start to use **subprocess** and not get any problems, thank you by the support.
