### ISSUE TITLE
Select Powershell 7 for execution of scripts via Set-AZVmRun command

### ISSUE THREAD

**Issue by Satyadm123** [Azure/azure-cli#27097]
I  am trying to  execute Powershell scripts using run commands on Windows VM. I have powershell 7 installed on the server. But Powershell 7 is not selected and it defaults to Powershell 5 while executing Run commands. Is it possible to select Powershell 7 for execution via run co mmands (Invoke Az VM run command/Set AzVM Run command)?
I have tried creating a profile and mentioning pwsh.exe but I get error when I execute a Powershell via SetAzVMRun Command

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yonzhan** [comment]
Please open this issue in Azure-powershell repo.
