### ISSUE TITLE
Add syncMode property for Azure Load Balancer backend pools

### ISSUE THREAD

**Issue by thisisanniefang** [Azure/azure-cli#27090]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az network lb address-pool create
az network lb address-pool update
az network lb address-pool show

### Resource Provider

Microsoft.Network/loadbalancers

### Description of Feature or Work Requested

We are looking to add the property "syncMode" as parameter --sync-mode to the above commands, as part of our upcoming public preview release for what we call "managed IP-based".

Managed IP-based is an umbrella term used to describe a new and improved model for deploying backend pools for load balancer.

With the release of managed IP-based, we will introduce a new property to backend pools, known as “syncMode”. There are 3 possible valid values for the property syncMode: “Automatic”, “Manual”, or unspecified.

syncMode: “Automatic”
-	This is the new and improved version of what is known as NIC-based backend pools today
-	This is the primary reason why we are releasing managed IP-based, as it allows for more performant backend pool updates, among other platform/infrastructure-related improvements.

syncMode: “Manual”
-	This is an improved version of what is known as IP-based backend pools today (you may also hear this referred to as “pure” IP-based)
-	This is almost identical to pure IP-based, but it most notably resolves the longstanding known issue where IP-based backend pools are not secure by default and do not disable default outbound access of instances when added to the backend pool.
-	We also intend to bridge some gaps + continue to improve this version of IP-based backend pools, which we will call “syncMode manual” pools

E2E customer experience:
To use "managed IP-based". customers will need to specify the --sync-mode property as either automatic/manual, the default should be unspecified. When this parameter is specified for creation of the pool, the customer will also need to specify the --vnet property (this is required when sync mode is explicitly specified as Automatic or Manual).

### Minimum API Version Required

2023-04-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/24685

### Target Date

2023-09-30

### PM Contact

anniefang

### Engineer Contact

irrogozh, anjbal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
@mahipdeora Current implementation doesn't rely on SDK and the API version is 2023-04-01.
