### ISSUE TITLE
[DevTestLabs] Add scenario tests for commands

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-cli#2709]
Potential Scenario Tests:

**Lab**
- [x] Delete a lab

**VM in the Lab**
- [x] Creating VM in lab from gallery image
- [ ] Creating VM in lab from custom image
- [ ] Creating VM in lab from formula

**Environment in the lab**
- [x] Create an environment from ARM template in the lab
- [x] Delete an environment from the lab

...

**Comment by tjprescott** [comment]
...?

**Comment by vishrutshah** [comment]
@tjprescott I'll extending list as i discover the scenarios needs to be covered :)

**Comment by vishrutshah** [comment]
More tests :

- [ ] Claim a specific vm in the lab
- [ ] Claim any vm from the lab
- [ ] List my vms in the lab

**Comment by vishrutshah** [comment]
Closing this as most of the listed tests are checked-in. We can open and manager new test as part of future command implementations. Thanks!
