### ISSUE TITLE
az upgrade not upgrading from version 2.50 to version 2.51

### ISSUE THREAD

**Issue by rick-wubs** [Azure/azure-cli#27091]
### Describe the bug

The `az upgrade` command says it will upgrade to the latest version. I have currently version 2.50 installed, and it says version 2.51 is available. However, when I run az upgrade it says '`already up to date`'.

### Related command

az upgrade

### Errors

Already up-to-date.
Warning: azure-cli 2.50.0_1 already installed
WARNING: New Azure CLI version available. Running 'az upgrade' to update automatically.
WARNING: This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Your current Azure CLI version is 2.50.0. Latest version available is 2.51.0.
WARNING: Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli

### Issue script & Debug output

 ~  az upgrade --debug
cli.knack.cli: Command arguments: ['upgrade', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x1031bdb40>, <function OutputProducer.on_global_arguments at 0x10324a710>, <function CLIQuery.on_global_arguments at 0x1032afb50>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'upgrade': ['azure.cli.command_modules.util']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: util                      0.001         3         7
cli.azure.cli.core: Total (1)                 0.001         3         7
cli.azure.cli.core: Loaded 3 groups, 7 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : upgrade
cli.azure.cli.core: Command table: upgrade
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x103d61870>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/<user>/.azure/commands/2023-08-04.07-08-06.upgrade.18451.log'.
az_command_data_logger: command args: upgrade --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x103e1a200>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x103e37d00>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x103e37e20>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x10324a7a0>, <function CLIQuery.handle_query_parameter at 0x1032afbe0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x103e37d90>]
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
urllib3.connectionpool: Starting new HTTPS connection (1): raw.githubusercontent.com:443
urllib3.connectionpool: https://raw.githubusercontent.com:443 "GET /Azure/azure-cli/main/src/azure-cli/setup.py HTTP/1.1" 200 2428
cli.azure.cli.command_modules.util.custom: Your current Azure CLI version is 2.50.0. Latest version available is 2.51.0.
cli.azure.cli.command_modules.util.custom: Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
Do you want to continue? (Y/n): Y
cli.azure.cli.command_modules.util.custom: Update homebrew formulae
Already up-to-date.
cli.azure.cli.command_modules.util.custom: Update azure cli with 'brew upgrade azure-cli'
Warning: azure-cli 2.50.0_1 already installed
WARNING: New Azure CLI version available. Running 'az upgrade' to update automatically.
WARNING: This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Your current Azure CLI version is 2.50.0. Latest version available is 2.51.0.
WARNING: Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli

Warning: azure-cli 2.50.0_1 already installed
WARNING: New Azure CLI version available. Running 'az upgrade' to update automatically.
WARNING: This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Your current Azure CLI version is 2.50.0. Latest version available is 2.51.0.
WARNING: Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli

### Expected behavior

when I have version 2.50 and version 2.51 is available, I expect `az upgrade` to upgrade version 2.50 to version 2.51

### Environment Summary

 ~  az --version
azure-cli                         2.50.0 *

core                              2.50.0 *
telemetry                          1.0.8 *

Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2

Python location '/opt/homebrew/Cellar/azure-cli/2.50.0_1/libexec/bin/python'
Extensions directory '/Users/<user>/.azure/cliextensions'

Python (Darwin) 3.10.12 (main, Jul 28 2023, 18:34:01) [Clang 14.0.3 (clang-1403.0.22.14.1)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
2.51 is not released to Homebrew yet, see https://github.com/Azure/azure-cli/issues/27047

**Comment by WaitingForGuacamole** [comment]
Is there a timeline for getting this into Homebrew?

**Comment by bebound** [comment]
We plan to remove two dependencies, which takes extra effort.
We’ll release 2.52 to Homebrew on Sep 5

**Comment by noumanmanan-msft** [comment]
It looks like there is no way to run 'az' on macos anymore. Everytime az command is run, for any service, it tries to upgrade, shows the following warning  and keeps doing this in a loop.

Warning: azure-cli 2.50.0_1 already installed
WARNING: New Azure CLI version available. Running 'az upgrade' to update automatically.
WARNING: This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Your current Azure CLI version is 2.50.0. Latest version available is 2.51.0.
WARNING: Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli

Is there anyway we can fix this before Sep. 5th?

Thank you

**Comment by krknopp** [comment]
Hopefully this workaround won't delay a real fix, but this got me working while I wait.

`az config set auto-upgrade.enable=no`

**Comment by noumanmanan-msft** [comment]
> 

Thank you @krknopp

**Comment by bebound** [comment]
Close as 2.52.0 is available in Homebrew.
