### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED error on "az bicep install" Resurfaced Again . Reference  #20842

### ISSUE THREAD

**Issue by aslan-im** [Azure/azure-cli#27096]
### Describe the bug

I do not use the proxy, but have the same issue when trying to run:
az bicep install

OS: MacOS Ventura 13.5
azure-cli 2.51.0
core 2.51.0
telemetry 1.1.0
Extensions:
azure-devops 0.26.0
Dependencies:
msal 1.24.0b1
azure-mgmt-resource 23.1.0b2
Bicep CLI version 0.19.5 (87ca110fc0)

### Related command

az bicep *

### Errors

Error while attempting to download Bicep CLI: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)>

### Issue script & Debug output

DEBUG: cli.knack.cli: Command arguments: ['bicep', 'install', '--debug']
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x10124f700>, <function OutputProducer.on_global_arguments at 0x10149dc10>, <function CLIQuery.on_global_arguments at 0x101513160>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Modules found from index for 'bicep': ['azure.cli.command_modules.resource']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: resource                  0.006        51       224
DEBUG: cli.azure.cli.core: Total (1)                 0.006        51       224
DEBUG: cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
DEBUG: cli.azure.cli.core: Loading extensions:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
DEBUG: cli.azure.cli.core: Total (0)                 0.000         0         0  
DEBUG: cli.azure.cli.core: Loaded 51 groups, 224 commands.
DEBUG: cli.azure.cli.core: Found a match in the command table.
DEBUG: cli.azure.cli.core: Raw command  : bicep install
DEBUG: cli.azure.cli.core: Command table: bicep install
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x102615af0>]
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/n0mad/.azure/commands/2023-08-04.19-40-43.bicep_install.42062.log'.
INFO: az_command_data_logger: command args: bicep install --debug
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x10263d9d0>]
DEBUG: cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/Users/n0mad/Library/Python/3.9/lib/python/site-packages/azure/cli/core/profiles/_shared.py", line 659, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azure.mgmt.resource.resources.v2022_09_01.models' has no attribute 'ExemptionCategory'

DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x1026cdca0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x1026eac10>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x10149dca0>, <function CLIQuery.handle_query_parameter at 0x1015131f0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x1026eab80>]
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): aka.ms:443
DEBUG: urllib3.connectionpool: https://aka.ms:443 "GET /BicepLatestRelease HTTP/1.1" 301 0
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): downloads.bicep.azure.com:443
DEBUG: urllib3.connectionpool: https://downloads.bicep.azure.com:443 "GET /releases/latest HTTP/1.1" 200 36737
DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/n0mad/Library/Python/3.9/lib/python/site-packages/azure/cli/command_modules/resource/_bicep.py", line 135, in ensure_bicep_installation
    request = urlopen(_get_bicep_download_url(system, release_tag, target_platform=target_platform))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/n0mad/Library/Python/3.9/lib/python/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/n0mad/Library/Python/3.9/lib/python/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/Users/n0mad/Library/Python/3.9/lib/python/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/Users/n0mad/Library/Python/3.9/lib/python/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/Users/n0mad/Library/Python/3.9/lib/python/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/n0mad/Library/Python/3.9/lib/python/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/n0mad/Library/Python/3.9/lib/python/site-packages/azure/cli/command_modules/resource/custom.py", line 4259, in install_bicep_cli
    ensure_bicep_installation(cmd.cli_ctx, release_tag=version, target_platform=target_platform)
  File "/Users/n0mad/Library/Python/3.9/lib/python/site-packages/azure/cli/command_modules/resource/_bicep.py", line 154, in ensure_bicep_installation
    raise ClientRequestError(f"Error while attempting to download Bicep CLI: {err}")
azure.cli.core.azclierror.ClientRequestError: Error while attempting to download Bicep CLI: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)>

ERROR: cli.azure.cli.core.azclierror: Error while attempting to download Bicep CLI: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)>
ERROR: az_command_data_logger: Error while attempting to download Bicep CLI: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)>
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x102615d30>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 1.776 seconds (init: 0.152, invoke: 1.624)
INFO: telemetry.main: Begin splitting cli events and extra events, total events: 1
INFO: telemetry.client: Accumulated 0 events. Flush the clients.
INFO: telemetry.main: Finish splitting cli events and extra events, cli events: 1
INFO: telemetry.save: Save telemetry record of length 3643 in cache
INFO: telemetry.main: Begin creating telemetry upload process.
INFO: telemetry.process: Creating upload process: "/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 /Users/n0mad/Library/Python/3.9/lib/python/site-packages/azure/cli/telemetry/__init__.py /Users/n0mad/.azure"
INFO: telemetry.process: Return from creating process
INFO: telemetry.main: Finish creating telemetry upload process.
Installing Bicep CLI v0.20.4...

### Expected behavior

az bicep installed

### Environment Summary

azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9'
Extensions directory '/Users/n0mad/.azure/cliextensions'

Python (Darwin) 3.9.13 (v3.9.13:6de2ca5339, May 17 2022, 11:37:23)
[Clang 13.0.0 (clang-1300.0.29.30)]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@aslan-im Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you please follow the steps mentioned in the below article depending on your environment to install the bicep CLI ? Hope this helps.

[Linux](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/install#linux)
[macOS](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/install#macos)
[Windows](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/install#windows)


Awaiting your reply.

**Comment by aslan-im** [comment]
@navba-MSFT Yes, it can be installed that way, but I see the same error when run something like
az deployment group

**Comment by navba-MSFT** [comment]
@aslan-im Thanks for getting back.

- Could you please try the same operation from a different reliable network and check if that helps ?

- Run this command and check the result:
> python.exe" -c "import urllib.request; print(urllib.request.getproxies())"

- I understand it is your personal laptop, but looking at the error it seems like there is a proxy that is interfering. You need to add HTTP_PROXY and HTTPS_PROXY environment variables to the system

- Then you need to find certifi path for your AzCLI installation. Default path should be: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\certifi".

- Download your corporate proxy's root certificate and append it to "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\certifi\cacert.pem"

- You could try setting the env variable (set AZURE_CLI_DISABLE_CONNECTION_VERIFICATION=1). Not a recommended approach though.

- Try disabling SSL certificate verification temporarily by setting the REQUESTS_CA_BUNDLE environment variable to None and check if that helps to run the CLI command. `export REQUESTS_CA_BUNDLE=None`

Awaiting your reply.

**Comment by aslan-im** [comment]
@navba-MSFT 
Could you please try the same operation from a different reliable network and check if that helps ?
- Checked with another network (mobile internet) and result is the same.

Run this command and check the result:
python.exe" -c "import urllib.request; print(urllib.request.getproxies())"
- result: {} (it is macOS)

I understand it is your personal laptop, but looking at the error it seems like there is a proxy that is interfering. You need to add HTTP_PROXY and HTTPS_PROXY environment variables to the system
Then you need to find certifi path for your AzCLI installation. Default path should be: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\certifi".

Download your corporate proxy's root certificate and append it to "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\certifi\cacert.pem"
You could try setting the env variable (set AZURE_CLI_DISABLE_CONNECTION_VERIFICATION=1). Not a recommended approach though.
- Please update the instructions according to the MacOS

Try disabling SSL certificate verification temporarily by setting the REQUESTS_CA_BUNDLE environment variable to None and check if that helps to run the CLI command. export REQUESTS_CA_BUNDLE=None

**Comment by navba-MSFT** [comment]
@aslan-im Thanks for getting back.

1. Check if the OpenSSL version is up to date by running the following command in the terminal:

>openssl version

If the version is not up to date, you can update it using Homebrew by running the following command:

> brew upgrade openssl

I understand you don't have a proxy, it might still be worth double-checking the system's proxy settings. You can run the following command to print the proxy settings:

```
echo $http_proxy
echo $https_proxy
```

2. Try running the below:

> **export AZURE_CLI_DISABLE_CONNECTION_VERIFICATION=1**

Though it isn't recommended, its worth trying to isolate this issue.

3. Set the REQUESTS_CA_BUNDLE environment variable to the path of the Base64-encoded SSL certificate file. You can download the certificate from your corporate proxy and save it to a file on your local machine. Then, set the environment variable to the path of the file by running the following command.

> **export REQUESTS_CA_BUNDLE=/path/to/certificate.pem**

4. If the above steps do not work, you can try disabling SSL certificate verification temporarily by setting the REQUESTS_CA_BUNDLE environment variable to None. Run the following command in the terminal:

> export REQUESTS_CA_BUNDLE=None

Note that this is not a recommended, its worth trying to isolate this issue.

**Comment by aslan-im** [comment]
- Check if the OpenSSL version is up to date by running the following command in the terminal:
openssl version
 Output: 
` OpenSSL 3.1.1 30 May 2023 (Library: OpenSSL 3.1.1 30 May 2023)`

I understand you don't have a proxy, it might still be worth double-checking the system's proxy settings. You can run the following command to print the proxy settings:

echo $http_proxy
echo $https_proxy
output:
`
❯ echo $http_proxy

❯ echo $https_proxy

`
- output is empty


Try running the below:
export AZURE_CLI_DISABLE_CONNECTION_VERIFICATION=1

Though it isn't recommended, its worth trying to isolate this issue.

Set the REQUESTS_CA_BUNDLE environment variable to the path of the Base64-encoded SSL certificate file. You can download the certificate from your corporate proxy and save it to a file on your local machine. Then, set the environment variable to the path of the file by running the following command.
export REQUESTS_CA_BUNDLE=/path/to/certificate.pem // I have no proxy

If the above steps do not work, you can try disabling SSL certificate verification temporarily by setting the REQUESTS_CA_BUNDLE environment variable to None. Run the following command in the terminal:
export REQUESTS_CA_BUNDLE=None

Note that this is not a recommended, its worth trying to isolate this issue.

**Comment by navba-MSFT** [comment]
@aslan-im Thanks for getting back. Could you please collect [network traces ](https://www.wireshark.org/docs/wsug_html_chunked/ChBuildInstallOSXInstall.html)and share this trace over email navba [@] microsoft . (dot) com ? Awaiting your reply.

**Comment by aslan-im** [comment]
@navba-MSFT  email with network traces has been sent to your email address.

**Comment by navba-MSFT** [comment]
@aslan-im I had a look at the traces and this might require a deeper troubleshooting. May I know if it is feasible for you to open a support ticket with Microsoft ? so that our support professionals and get on a troubleshooting session with you to look into this. Awaiting your reply.

**Comment by aslan-im** [comment]
@navba-MSFT Please clarify through what I should rise a ticket? Is it possible to raise it in a way not related to particular Az tenant?

**Comment by navba-MSFT** [comment]
@aslan-im Thanks for getting back. You can type **support** in azure portal and select for `Help + Support` and create a ticket:

<img width="569" alt="image" src="https://github.com/Azure/azure-cli/assets/57353862/a772bb11-52b4-4e3b-beb4-ffca3142c10f">

More Info [here](https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request#go-to-help--support-from-the-global-header).


Alternatively, you can create support ticket from [here](https://azure.microsoft.com/en-in/support/create-ticket).  Hope this helps.

**Comment by navba-MSFT** [comment]
@aslan-im I hope you had a chance to follow the above suggestion and opened a support ticket to work on this issue.

**Comment by pecord-at-MSFT** [comment]
@aslan-im - I was running into the same issue, on macos, no proxy, latest openssl, etc, I was able to get past this error using the following commands. Guessing something from my dev env added a self signed cert to the CA bundle or something - 

```
CERT_PATH=$(python -m certifi)
export SSL_CERT_FILE=${CERT_PATH}
export REQUESTS_CA_BUNDLE=${CERT_PATH}
```

ref - https://stackoverflow.com/a/57795811
