### ISSUE TITLE
Create a containerapp env using existing log-analytics

### ISSUE THREAD

**Issue by arambazamba** [Azure/azure-cli#27098]
### Describe the bug

When trying to execute 

az containerapp env create -n $acea -g $grp -l $loc --logs-destination log-analytics --logs-workspace-id $wsId --logs-workspace-key $wsKey

I get the message: LogAnalyticsConfiguration.CustomerId is invalid.  CustomerId must be a GUID without additional whiteSpace

Can you please clarify on the CustomerId which is not documented

### Related command

env=dev
loc=westeurope
grp=foodapp-$env
ws=foodlogs-$env
acr=foodcontainers$env
ace=foodace-$env
ai=foodai-$env
acaenv=food-$env

az group create -n $grp -l $loc

az acr create -g $grp -n $acr --sku Basic
az acr login --name $acr
az acr update -n $acr --admin-enabled true

wsId=$(az monitor log-analytics workspace create -g $grp --workspace-name $ws --query  id -o tsv)
wsKey=$(az monitor log-analytics workspace get-shared-keys -g $grp --workspace-name $ws --query primarySharedKey -o tsv)

az monitor app-insights component create --app $ai --location $loc --kind web -g $grp --application-type web --workspace $wsId

aiKey=$(az monitor app-insights component show --app $ai -g $grp --query instrumentationKey -o tsv)                                    
aiConString=$(az monitor app-insights component show --app $ai -g $grp --query connectionString -o tsv) 

echo "AppInsights Key: $aiKey"
echo "AppInsights Connection String: $aiConString"

az containerapp env create -n $ace -g $grp -l $loc --logs-destination log-analytics --logs-workspace-id $wsId --logs-workspace-key $wsKey

### Errors

LogAnalyticsConfiguration.CustomerId is invalid.  CustomerId must be a GUID without additional whiteSpace

### Issue script & Debug output

DEBUG: cli.knack.cli: Command arguments: ['containerapp', 'env', 'create', '-n', 'testtesttse', '-g', 'foodapp-dev', '-l', 'westeurope', '--logs-destination', 'log-analytics', '--logs-workspace-id', '/subscriptions/78033352-805c-4acd-af80-f8f95083268d/resourceGroups/foodapp-dev/providers/Microsoft.OperationalInsights/workspaces/foodlogs-dev', '--logs-workspace-key', 'MwtLqj5N0y+2EQitRIbRBNnTchsSgVjdX+KGOU3zhsz18Fv3P9zHuqCrfEXoOEolFLyset8vFrHoQq4m2qJydw==', '--debug', '-']
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f57be425510>, <function OutputProducer.on_global_arguments at 0x7f57be37c430>, <function CLIQuery.on_global_arguments at 0x7f57be199630>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Modules found from index for 'containerapp': ['azure.cli.command_modules.serviceconnector', 'azext_containerapp']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: serviceconnector          0.629        16       235
DEBUG: cli.azure.cli.core: Total (1)                 0.629        16       235
DEBUG: cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
DEBUG: cli.azure.cli.core: Loading extensions:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
DEBUG: cli.azure.cli.core: containerapp              0.391        41       127  /home/alex/.azure/cliextensions/containerapp
DEBUG: cli.azure.cli.core: Total (1)                 0.391        41       127  
DEBUG: cli.azure.cli.core: Loaded 56 groups, 362 commands.
DEBUG: cli.azure.cli.core: Found a match in the command table.
DEBUG: cli.azure.cli.core: Raw command  : containerapp env create
DEBUG: cli.azure.cli.core: Command table: containerapp env create
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f57bd562e60>]
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/alex/.azure/commands/2023-08-05.14-16-22.containerapp_env_create.1947.log'.
INFO: az_command_data_logger: command args: containerapp env create -n {} -g {} -l {} --logs-destination {} --logs-workspace-id {} --logs-workspace-key {} --debug {}
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f57bd57f9a0>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f57bd5c97e0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f57bd5c9900>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): app.aladdin.microsoft.com:443
DEBUG: urllib3.connectionpool: https://app.aladdin.microsoft.com:443 "GET /api/v1.0/suggestions?query=%7B%22command%22%3A+%22containerapp+env+create%22%2C+%22parameters%22%3A+%22%22%7D&clientType=AzureCli&context=%7B%22versionNumber%22%3A+%222.51.0%22%2C+%22errorType%22%3A+%22UnrecognizedArguments%22%2C+%22correlationId%22%3A+%2255df6c46-6bc2-412c-be55-65d6552afb54%22%2C+%22subscriptionId%22%3A+%2278033352-805c-4acd-af80-f8f95083268d%22%2C+%22eventId%22%3A+%220964d7a9-1376-4b2d-a99f-7b3c6b0e495d%22%7D HTTP/1.1" 200 None
DEBUG: cli.azure.cli.core.azclierror: NoneType: None

ERROR: cli.azure.cli.core.azclierror: unrecognized arguments: -
ERROR: az_command_data_logger: unrecognized arguments: -

Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f57bd5630a0>]
INFO: az_command_data_logger: exit code: 2
INFO: cli.__main__: Command ran in 1.477 seconds (init: 0.090, invoke: 1.387)
INFO: telemetry.main: Begin splitting cli events and extra events, total events: 1
INFO: telemetry.client: Accumulated 0 events. Flush the clients.
INFO: telemetry.main: Finish splitting cli events and extra events, cli events: 1
INFO: telemetry.save: Save telemetry record of length 3561 in cache
INFO: telemetry.main: Begin creating telemetry upload process.
INFO: telemetry.process: Creating upload process: "/usr/bin/../../opt/az/bin/python3 /opt/az/lib/python3.10/site-packages/azure/cli/telemetry/__init__.py /home/alex/.azure"
INFO: telemetry.process: Return from creating process
INFO: telemetry.main: Finish creating telemetry upload process.

### Expected behavior

The container app env would be created using the provided log workspace

### Environment Summary

azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Extensions:
application-insights              0.1.19
containerapp                      0.3.36

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/home/alex/.azure/cliextensions'

Python (Linux) 3.10.10 (main, Jul 27 2023, 07:11:10) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by Wwwsylvia** [comment]
@yonzhan It looks like this issue is for `az containerapp`, not ACR.

**Comment by arambazamba** [comment]
@Wwwsylvia: I also think it is an issue with azure cli ... works fine when doing it using bicep

resource acaEnvironment 'Microsoft.App/managedEnvironments@2023-05-01' = {
  name: acaEnv
  location: rgLocation
  properties: {
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: logAnalytics.properties.customerId
        sharedKey: logAnalytics.listKeys().primarySharedKey
      }
    }
  }
}

**Comment by SaurabhSharma-MSFT** [comment]
@arambazamba I suspect, this is because of how you are getting the workspace id 
Instead of using `--query Id`, can you please try `--query customerId`
`wsId=$(az monitor log-analytics workspace create -g $grp --workspace-name $ws --query customerId-o tsv)`
Thanks.

**Comment by emilast** [comment]
> @arambazamba I suspect, this is because of how you are getting the workspace id Instead of using `--query Id`, can you please try `--query customerId` `wsId=$(az monitor log-analytics workspace create -g $grp --workspace-name $ws --query customerId-o tsv)` Thanks.

I've had the exact same issue and can confirm that using `customerId` instead of `id` from the Log Analytics Workspace works. The problem is that the parameter name `--logs-workspace-id` is very misleading and the documentation [here](https://learn.microsoft.com/en-us/cli/azure/containerapp/env?view=azure-cli-latest#az-containerapp-env-create) does not say anything about any `customerId` either, so one just assumes it's the id that should be used. I think you need to at least update the docs.

**Comment by arambazamba** [comment]
@emilast thank you for your comment! I did not habe time to answer. I see it like you: the name of the param is causing confusion. The docs specify the following explanation:

--logs-workspace-id
Workspace ID of the Log Analytics workspace to send diagnostics logs to. Only works with logs destination "log-analytics". You can use "az monitor log-analytics workspace create" to create one. Extra billing may apply.

**Comment by kraduk** [comment]
this most definitely still is an issue 
```
$ az containerapp env create \
        --name XXX-aca-env \
        --resource-group XXX-rg \
        --infrastructure-subnet-resource-id /subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.Network/virtualNetworks/XXX/subnets/XXX \
        --zone-redundant \
        --internal-only true \
        --logs-workspace-id /subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.OperationalInsights/workspaces/XXX \
        --logs-workspace-key xxxxxxxxxxxxxxxxxxxxxxxxxxx+xxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx+x+xxxx.== \
        --logs-destination log-analytics \
        --enable-workload-profiles true
(InvalidRequestParameterWithDetails) LogAnalyticsConfiguration.CustomerId is invalid.  CustomerId must be a GUID without additional whiteSpace.
$ az --version
azure-cli                         2.55.0

core                              2.55.0
telemetry                          1.1.0

Extensions:
azure-devops                      0.25.0
containerapp                      0.3.41
ssh                                1.1.6

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/home/XXX/.azure/cliextensions'

Python (Linux) 3.11.5 (main, Nov 29 2023, 03:40:58) [GCC 11.4.0]

Legal docs and information: aka.ms/AzureCliLegal


```

**Comment by arambazamba** [comment]
@kraduk from my perspektive there is no reason to re-open … @emilast answered the question above

**Comment by mgd722** [comment]
@alexander-kastil, sure he answered the question, but the parameter name still makes no sense and the docs are still incorrect.

> `--logs-workspace-id`
Workspace ID of the Log Analytics workspace to send diagnostics logs to. Only works with logs destination "log-analytics". You can use "az monitor log-analytics workspace create" to create one. Extra billing may apply.

Yet, if you send the workspace ID as the docs (and the parameter name!) indicate, it still fails.
