### ISSUE TITLE
Change in the minimum capacities allowed for Log Analytics cluster - CREATE/UPDATE

### ISSUE THREAD

**Issue by roizhv22** [Azure/azure-cli#27119]
### Preconditions

- [ ] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az monitor log-analytics cluster create
az monitor log-analytics cluster update

### Resource Provider

Microsoft.OperaitonalInsights

### Description of Feature or Work Requested

[CLI_Change_Cluster_size.docx](https://github.com/Azure/azure-cli/files/12292617/CLI_Change_Cluster_size.docx)

Change in allowed cluster size, https://learn.microsoft.com/en-us/cli/azure/monitor/log-analytics/cluster?view=azure-cli-latest#az-monitor-log-analytics-cluster-create required change in docs as well.

### Minimum API Version Required

2020-08-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/tree/main/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/stable/***/Clusters.json

where *** are the different api version where Clusters are enabled in (all versions from 2019-08-01-preview and above) 

### Request Example

PUT  https://management.azure.com/subscriptions/*/resourcegroups/*/providers/Microsoft.OperationalInsights/clusters/weLoveClusters?api-version=2021-06-01
body
{
  "sku": {
    "name": "CapacityReservation",
    "capacity": 100
  },
  "location": "wcus",
  "tags": {
    "tag1": "val1"
  }
}

-> returns 201

PUT  https://management.azure.com/subscriptions/*/resourcegroups/*/providers/Microsoft.OperationalInsights/clusters/weLoveClusters?api-version=2021-06-01
body
{
  "sku": {
    "name": "CapacityReservation",
    "capacity": 99
  },
  "location": "wcus",
  "tags": {
    "tag1": "val1"
  }
}

-> returns 400
    "error": {
        "code": "InvalidInput",
        "message": "CapacityReservationLevel must be an allowed value: [100,200,300,400,500,1000,2000,5000]. Operation Id: '4b0969a19bfb86fe7d475e78960da344'",
        "target": "sku.capacity",
...}

### Target Date

N/A

### PM Contact

N/A

### Engineer Contact

t-roizehavi

### Additional context

feature already deployed and enforced via REST requests.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by AllyW** [comment]
@roizhv22 hi, please update corresponding swagger parameter enum [here.](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/stable/2021-06-01/Clusters.json#L532-L536)
