### ISSUE TITLE
Change default SKU for "az network public-ip create"

### ISSUE THREAD

**Issue by cburuzie** [Azure/azure-cli#27121]
**Related command**
"az network public-ip create"

**Is your feature request related to a problem? Please describe.**
Last year, we announced the retirement of Basic IPs and created a warning message to cx who were using this command of the upcoming changes of this command's default SKU. Now we would like to change the default SKU to Standard as part of the retirement.

**Describe the solution you'd like**
We want to change the default SKU from Basic to Standard IP. 

**Describe alternatives you've considered**
N/A

**Additional context**
Previous ask where we added the warning message last year - #22074

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
