### ISSUE TITLE
Change default SKU for "az network lb create" & "az network lb frontend-ip create"

### ISSUE THREAD

**Issue by cburuzie** [Azure/azure-cli#27123]
**Related command**
"az network lb create" & "az network lb frontend-ip create"

**Is your feature request related to a problem? Please describe.**
Last year, we announced the retirement of Basic LBs and created a warning message to cx who were using this command of the upcoming changes to this command's default SKU. Now we would like to change the default SKU to Standard as part of the retirement.

**Describe the solution you'd like**
We want to change the default SKU from Basic to Standard LB. 

**Describe alternatives you've considered**
N/A

**Additional context**
Previous ask where we added the warning message last year - #21831

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
