### ISSUE TITLE
[Gitlab]Unable to deploy function app from azure cli

### ISSUE THREAD

**Issue by Babug01** [Azure/azure-cli#27122]
### Describe the bug

I'm using below terraform configuration for creating Azure Function App,
`# Configure the Azure provider
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.68.0"
    }
  }
  required_version = ">= 0.14.9"
}
provider "azurerm" {
  features {}
}

data "azurerm_resource_group" "resource_group" {
  name = "xxxxxx"
}

resource "azurerm_storage_account" "app" {
  /*
   * var.function_name: shared-test
   * name: funcsharedtest
   * The below constructs the name, strips invalid characters then truncates the name to be only 24 characters long
   */
  name                = substr(replace(format("func%s", "webapp"), "/[ -_]*/", ""), 0, 24)
  location            = data.azurerm_resource_group.resource_group.location
  resource_group_name = data.azurerm_resource_group.resource_group.name

  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_application_insights" "app" {
  name                = "webapp-appin"
  location            = data.azurerm_resource_group.resource_group.location
  resource_group_name = data.azurerm_resource_group.resource_group.name
  application_type    = "Node.JS"
}

resource "azurerm_service_plan" "appserviceplan" {
  name                = "webapp-asp"
  location            = data.azurerm_resource_group.resource_group.location
  resource_group_name = data.azurerm_resource_group.resource_group.name
  os_type             = "Linux"
  sku_name            = "Y1"
}

resource "azurerm_linux_function_app" "webapp" {
  name                       = "webapp"
  location                   = data.azurerm_resource_group.resource_group.location
  resource_group_name        = data.azurerm_resource_group.resource_group.name
  service_plan_id            = azurerm_service_plan.appserviceplan.id
  storage_account_name       = azurerm_storage_account.app.name
  storage_account_access_key = azurerm_storage_account.app.primary_access_key
  https_only                 = true
  builtin_logging_enabled    = false
  app_settings = {
    FUNCTIONS_WORKER_RUNTIME = "node"
  }
  site_config {
    minimum_tls_version                    = "1.2"
    http2_enabled                          = false
    application_insights_key               = azurerm_application_insights.app.instrumentation_key
    application_insights_connection_string = azurerm_application_insights.app.connection_string
    application_stack {
      node_version = "18"
    }
  }
  identity {
    type = "SystemAssigned"
  }
}
`
And using below CICD pipeline to deploy nodejs app through gitlab

`stages:
  - build
  - deploy

variables:
  AZURE_FUNCAPP_NAME: "webapp"
  AZURE_RESOURCE_GROUP: "XXXX"

build:
  stage: build
  image: node:latest
  script:
    - npm install
  artifacts:
    paths:
      - dist/myartifact.zip
    name: webapp_node_artifact

deploy:
  stage: deploy
  image: mcr.microsoft.com/azure-cli
  script:
    - az --version
    # Login to Azure
    - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
    - az account set --subscription $AZURE_SUBSCRIPTION_ID
    # Deploy the code to Azure
    - az functionapp deployment source config-zip --name $AZURE_FUNCAPP_NAME  --resource-group $AZURE_RESOURCE_GROUP --src dist/myartifact.zip --debug
  dependencies:
    - build
`
and I'm getting bellow error from deploy stage
 az functionapp deployment source config-zip --name $AZURE_FUNCAPP_NAME  --resource-group $AZURE_RESOURCE_GROUP --src dist/myartifact.zip
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: float division by zero

### Related command

az functionapp deployment source config-zip --name $AZURE_FUNCAPP_NAME  --resource-group $AZURE_RESOURCE_GROUP --src dist/myartifact.zip --debug

### Errors

 az functionapp deployment source config-zip --name $AZURE_FUNCAPP_NAME  --resource-group $AZURE_RESOURCE_GROUP --src dist/myartifact.zip
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: float division by zero
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 574, in enable_zip_deploy_functionapp
    return upload_zip_to_storage(cmd, resource_group_name, name, src, slot)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 763, in upload_zip_to_storage
    block_blob_service.create_blob_from_path(container_name, blob_name, src, validate_content=True,
  File "/usr/local/lib/python3.10/site-packages/azure/multiapi/storage/v2018_11_09/blob/blockblobservice.py", line 455, in create_blob_from_path
    return self.create_blob_from_stream(
  File "/usr/local/lib/python3.10/site-packages/azure/multiapi/storage/v2018_11_09/blob/blockblobservice.py", line 574, in create_blob_from_stream
    progress_callback(0, count)
  File "/usr/local/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 757, in progress_callback
    filled_length = int(round(total_length * current) / float(total))
ZeroDivisionError: float division by zero
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

### Issue script & Debug output

[webapp_debug_logs.txt](https://github.com/Azure/azure-cli/files/12295346/webapp_debug_logs.txt)

### Expected behavior

I'm expecting to deploy function app correctly

### Environment Summary

[32;1m$ az --version[0;m
azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location '/usr/local/bin/python'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.10.12 (main, Jun 15 2023, 03:17:49) [GCC 12.2.1 20220924]

using docker image: mcr.microsoft.com/azure-cli

### Additional context

Attached logs

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by kamperiadis** [comment]
Hello @Babug01 Are you able to successfully deploy that same zip package using other client tools? The reason why this is happening is because we use [this function](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blockblobservice.blockblobservice?view=azure-python-previous#azure-storage-blob-blockblobservice-blockblobservice-create-blob-from-path) and `progress_callback` must be setting the total size of the blob to be 0. On our end we should add validation that the total size identified is not zero or None (if the total size is unknown).

**Comment by babuga365** [comment]
Yes and Im closing this case
