### ISSUE TITLE
`az eventhubs eventhub` command group downgraded from GA to preview

### ISSUE THREAD

**Issue by dhavemeyer-symplr** [Azure/azure-cli#27136]
### Describe the bug

After upgrading from az cli 2.43 to 2.51 when running `az eventhubs eventhub create` I started getting a warning that the command group is in preview. It is unclear to me why this command group would be in preview since this functionality has been out of preview for some time. Is this command group truly supposed to be back in preview, if so why? Sorry if this isn't really a bug, but I'm just trying to get a better understanding of the command group lifecycle and I'm confused by the current state.

PS: I did see that the command group was pretty heavily refactored in #26168, so maybe maybe that's part of why it was marked as preview again? But there wasn't anything in the release notes stating that `az eventhubs eventhub` would go back into preview as a result of the change.

### Related command

`az eventhubs eventhub`

### Errors

Command group 'eventhubs eventhub' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus

### Issue script & Debug output

> az eventhubs eventhub create --resource-group <resource-group> --namespace-name <eventhub-namespace> --name <name> --retention-time-in-hours 168 --partition-count 1 --cleanup-policy delete
Command group 'eventhubs eventhub' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus

### Expected behavior

I expect that a command ground that has been in GA would have a clear statement about why it was put back in preview.

### Environment Summary

az --version
azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Extensions:
account                            0.2.1
azure-devops                      0.25.0
datafactory                        0.6.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by Saglodha** [comment]
Thanks for reaching out to us @dhavemeyer-symplr , we have opened up an investigation task for the issue. 

I would keep you posted with updates.

**Comment by WakaToa** [comment]
We have the same problem with `az eventhubs namespace` command in 2.52.0

**Comment by Saglodha** [comment]
@dhavemeyer-symplr / @WakaToa - Apologies for inconvenience you may have experienced. Upon conducting a thorough internal investigation, we identified that the unexpected appearance of the preview banner was due to an erroneously set flag. We want to assure you that this issue has been addressed and the rectified behavior will be incorporated in our November release.

**Comment by WakaToa** [comment]
Hi @Saglodha, do you have any update for us? I was not able find a PR in https://github.com/Azure/azure-cli/milestone/136

**Comment by Saglodha** [comment]
@WakaToa - Fix for above issue is merged in our breaking change release. Could you kindly confirm if you still observe the issue?

**Comment by WakaToa** [comment]
> @WakaToa - Fix for above issue is merged in our breaking change release. Could you kindly confirm if you still observe the issue?

Thank you for the ping. I will check it early january :)
