### ISSUE TITLE
Unable to pass argument list where value has leading hyphen

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-cli#27140]
### Describe the bug

For a command like `az containerapp create`, it has a parameter `--command` that takes a space separated list of values. This is an example of how it's used (in bash on macOS or Linux):

```bash
az containerapp create -n foo -g foo --environment foo --image ubuntu --command "/bin/sh" "-c" "sleep 10"
```

The above command fails because the CLI parses `"-c"` as a flag instead of an item in the list of values provided to `--command`.

There's a workaround provided here: https://github.com/Azure/azure-cli/issues/7054#issuecomment-414102787 and here: https://github.com/Azure/azure-cli/issues/8396#issuecomment-459440724

But because this parameter takes multiple space-separated values as arguments, I don't think it's possible to use the `--name=value` syntax.

In this case, is there a workaround?

### Related command

Demonstrated in `az containerapp create`, but this appears to be an issue with how the CLI parses arguments, not with the command itself.

### Errors

unrecognized arguments: -c sleep 10

### Issue script & Debug output

N/A

### Expected behavior

The command should work, with the values properly passed to `--command` as arguments.

### Environment Summary

azure-cli                         2.48.1 *

core                              2.48.1 *
telemetry                          1.0.8 *

Extensions:
application-insights              0.1.19
containerapp                      0.3.36
containerapp-compose               0.2.0
deploy-to-azure                    0.2.0
log-analytics                      0.2.2
spring                            1.11.2

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location '/usr/local/Cellar/azure-cli/2.48.1/libexec/bin/python'
Extensions directory '/Users/antchu/.azure/cliextensions'

Python (Darwin) 3.10.11 (main, Apr  7 2023, 07:31:31) [Clang 14.0.0 (clang-1400.0.29.202)]

Legal docs and information: aka.ms/AzureCliLegal

You have 3 update(s) available. Consider updating your CLI installation with 'az upgrade'

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
Non customer-reported issue. Adding Service team to look into this.

**Comment by anthonychu** [comment]
Closing as duplicate of #27011
