### ISSUE TITLE
Enable Trusted Launch on existing VMSS | az vmss update | Additional Scenarios

### ISSUE THREAD

**Issue by AjKundnani** [Azure/azure-cli#27143]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

`az vmss update`

### Resource Provider

Microsoft.Compute/virtualMachineScaleSets

## Overview
This request is append to existing request #26972 for supporting additional scenarios.

### Scenario 3 - Gen2 VMSS - OS Image Change or No OS Image change - SecurityType null

VMSS is currently deployed using Hyper-V Gen2 (v2) OS image.

1. Customer runs following command to enable Trusted Launch
`az vmss update -g <resourceGroupName -n $<vmssName> --security-type TrustedLaunch`

2. CLI will display following informational message to end user.
Trusted Launch security type is supported on Hyper-V Generation 2 OS Images. To know more please visit https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch

3. Set --enable-secure-boot:false and --enable-vtpm:true if not specified by end user.

### Scenario 4 - Gen2 VMSS - OS Image Change or No OS Image change - TrustedLaunch enabled

VMSS is currently deployed using Hyper-V Gen2 (v2) OS image and security type `TrustedLaunch`

1. Customer runs following command to enable Trusted Launch
`az vmss update -g <resourceGroupName -n $<vmssName> --security-type TrustedLaunch --enable-secure-boot true`

2. VM validation will return **securityProfile** is not null and security type `securityProfile.securityType` is set to **TrustedLaunch**

3. Update request per user inputs will be sent to backend. Backend will skip securityType update and only enable SecureBoot per end user inputs.

### Scenario 5 - Gen2 VMSS - OS Image Change or No OS Image change - ConfidentialVM enabled

VMSS is currently deployed using Hyper-V Gen2 (v2) OS image and security type `ConfidentialVM`

1. Customer runs following command to enable Trusted Launch
`az vmss update -g <resourceGroupName -n $<vmssName> --security-type TrustedLaunch --enable-secure-boot true`

2. VM validation will return **securityProfile** is not null and security type `securityProfile.securityType` is set to **ConfidentialVM**

3. For Confidential VMs, CLI generates below error message for end user and terminates:
`<resource name> is already configured with <securityProfile.securityType>. Security Configuration cannot be updated from ConfidentialVM to TrustedLaunch.`

### Minimum API Version Required

2020-06-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2022-11-01/virtualMachineScaleSet.json

### Request Example

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2022-11-01/examples/virtualMachineScaleSetExamples/VirtualMachineScaleSet_Create_WithUefiSettings.json

### Target Date

2023-09-30

### PM Contact

ajkundna

### Engineer Contact

shankarma

### Additional context

This is append to existing request #26972 with additional scenarios for VMSS already enabled with TL or CVM.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
