### ISSUE TITLE
az-cli 2.51.0 gives an error for keyvault commands that api version 2023-02-01 is invalid

### ISSUE THREAD

**Issue by marijadjukic** [Azure/azure-cli#27147]
### Describe the bug

When using azure cli 2.51.0 for keyvault commands I'm getting error:  _(InvalidApiVersionParameter) The api-version '2023-02-01' is invalid._
![image](https://github.com/Azure/azure-cli/assets/37125049/d0e3edc6-0773-4822-8b35-2e341f9884c0)

### Related command

az keyvault set-policy --name <key-vault-name> --object-id <identity-principal> --secret-permissions get list -o none

### Errors

The command failed with error InvalidApiVersionParameter
The api-version '2023-02-01' is invalid.
![image](https://github.com/Azure/azure-cli/assets/37125049/f79fa1b8-3ef1-4ece-a0c4-8f35b6472390)

### Issue script & Debug output

_(InvalidApiVersionParameter) The api-version '2023-02-01' is invalid._

### Expected behavior

Expected behaviour key vault policy is set successfully with az-cli.

### Environment Summary

azure-cli 2.51.0
azure core 2.51.0
telemetry 1.1.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by evelyn-ys** [comment]
duplicate with #27109 

Please see details and workaround in previous issue comments

**Comment by marijadjukic** [comment]
Followed one of the suggestions from linked issue, adding `--resource-group` option does temporary solve the problem
