### ISSUE TITLE
InvalidApiVersionParameter: Azure CLI 2.51.0 fails to execute Key Vault calls 

### ISSUE THREAD

**Issue by cc-at-cg** [Azure/azure-cli#27159]
### Describe the bug

We are running a script with two CLI Key Vault calls. These worked until yesterday, and then started to fail. There have been no recent changes to this script or the parameters being passed in. The calls in question are `az keyvault show` and  'az keyvault set-policy'.

Running `az version` tells us we are using CLI version 2.51.0. Downgrading to Az CLI version 2.44.1 before running the calls solves the issue.

### Related command

$query =  "properties.accessPolicies[?objectId == '$objectId']"
$policy = az keyvault show --name $vaultName --query $query | ConvertFrom-Json

az keyvault set-policy --name $vaultName --object-id $objectId --secret-permissions get list --only-show-errors

### Errors

ERROR: cli.azure.cli.core.azclierror: (InvalidApiVersionParameter) The api-version '2023-02-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
Code: InvalidApiVersionParameter

### Issue script & Debug output

[azCLIVersionKVErrors.txt](https://github.com/Azure/azure-cli/files/12325424/azCLIVersionKVErrors.txt)

### Expected behavior

The two Key Vault calls succeed, as in the older versions.

### Environment Summary

{
  "azure-cli": "2.51.0",
  "azure-cli-core": "2.51.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "azure-devops": "0.26.0"
  }
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yonzhan** [comment]
Did you specify '--resource-group' parameter to avoid listing all vaults?

**Comment by cc-at-cg** [comment]
Including the –resource-group param fixed the issue. That wasn’t needed before, but we are unblocked at this point.
