### ISSUE TITLE
Unable to log into azure using elevated powershell

### ISSUE THREAD

**Issue by sachikethareddy** [Azure/azure-cli#27158]
### Describe the bug

Seeing an  error while running az login.

Error: `Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError`

### Related command

Az login

### Errors

Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError

### Issue script & Debug output

cli.azure.cli.core.azclierror: Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError
az_command_data_logger: Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError

### Expected behavior

Need to see all the available subscriptions.

### Environment Summary

azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by sachikethareddy** [comment]
Deleted the .azure folder and re-installed the Azure cli but still seeing the same error.

**Comment by jiasli** [comment]
The information provided by at https://github.com/Azure/azure-cli/issues/27158#issuecomment-1675275349 is inaccurate yet.

Please try not to run Azure CLI as admin. If the issue persists, you may try to disable token cache. See https://github.com/Azure/azure-cli/issues/20231#issuecomment-1007176901
