### ISSUE TITLE
Missing instruction on how to create cli command for GroupByVariable or GroupByUserSession

### ISSUE THREAD

**Issue by Shawnli222** [Azure/azure-cli#27160]
### Describe the bug

https://learn.microsoft.com/en-us/cli/azure/network/application-gateway/waf-policy/custom-rule?view=azure-cli-latest
In this document, I do not see the instruction to create GroupByVariable or GroupByUserSessionin az network application-gateway waf-policy custom-rule create and az network application-gateway waf-policy custom-rule update. We need GroupByVariable to create a GroupByUserSession. Please update the doc with instructions or tell me how we do it in cli command. Thanks

### Related command

az network application-gateway waf-policy custom-rule create 
az network application-gateway waf-policy custom-rule update

### Errors

Missing command

### Issue script & Debug output

Missing command

### Expected behavior

Missing command

### Environment Summary

all versions

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by tejasshah7** [comment]
Tried all these but keep getting an error:

PS C:\Users\tesha>  az network application-gateway waf-policy custom-rule create --action Block --name "TestRule1" --policy-name "TejasTestRLCLIPlcy" --priority 5 --resource-group "TejasTestRLCLIRG" --rule-type RateLimitRule --group-by-user-session GeoLocation --rate-limit-duration OneMin --rate-limit-threshold 100
Failed to parse '--group-by-user-session' argument: list type value expected, got 'GeoLocation'(<class 'str'>)

PS C:\Users\tesha>  az network application-gateway waf-policy custom-rule create --action Block --name "TestRule1" --policy-name "TejasTestRLCLIPlcy" --priority 5 --resource-group "TejasTestRLCLIRG" --rule-type RateLimitRule --group-by-user-session "GeoLocation" --rate-limit-duration OneMin --rate-limit-threshold 100
Failed to parse '--group-by-user-session' argument: list type value expected, got 'GeoLocation'(<class 'str'>)

PS C:\Users\tesha>  az network application-gateway waf-policy custom-rule create --action Block --name "TestRule1" --policy-name "TejasTestRLCLIPlcy" --priority 5 --resource-group "TejasTestRLCLIRG" --rule-type RateLimitRule --group-by-user-session none --rate-limit-duration OneMin --rate-limit-threshold 100
Failed to parse '--group-by-user-session' argument: list type value expected, got 'none'(<class 'str'>)

**Comment by tejasshah7** [comment]
This is blocking our release so an update on this asap will be appreciated.

**Comment by necusjz** [comment]
@tejasshah7 

I'll update the example in the next release. E.g., `--group-by-user-session "[{group-by-variables:[{variable-name:GeoLocation}]}]"` could be a valid case
