### ISSUE TITLE
Terraform Development for Azure Elastic SAN

### ISSUE THREAD

**Issue by adarshv98** [Azure/azure-cli#27182]
**Related command**

**Is your feature request related to a problem? Please describe.**
The Azure Elastic SAN team would like to involve the Terraform team in the development of the Terraform cmdlets for our GA.

**Describe the solution you'd like**
Terraform generated for the given GA swagger.

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yonzhan** [comment]
Please open this feature request in Terraform repo.

**Comment by dalemcinnis** [comment]
I am mounting the elastic SAN on several Linux VMs.  However on 1 particular VM for 1 specific volume it always uses 32 threads, on all other VMs and other volumes it uses 1 thread which is what I want.  Why?
