### ISSUE TITLE
Typo in az network vnet peering create command

### ISSUE THREAD

**Issue by ChaitanyaNaykodi-MSFT** [Azure/azure-cli#27193]
### Describe the bug

The --remote-vnet property is a required property and not optional.
Documentation link : https://learn.microsoft.com/en-US/cli/azure/network/vnet/peering?view=azure-cli-latest#az-network-vnet-peering-create

![image](https://github.com/Azure/azure-cli/assets/67453298/63f06a22-dc54-4a25-8816-0e844b30b1b5)

### Related command

---

### Errors

--

### Issue script & Debug output

----

### Expected behavior

--------

### Environment Summary

----------

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
