### ISSUE TITLE
Add hostNames field for Application gateway listeners cmdlets

### ISSUE THREAD

**Issue by gdhillon24** [Azure/azure-cli#27197]
**Related command**

az network application-gateway listener

**Is your feature request related to a problem? Please describe.**

New feature request, hostNames field is added for application gateway l4 listeners, this change would enable Customers to cofigure HostNames for TLS multisite listeners.

Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/25982

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
