### ISSUE TITLE
Fail to create vhub connection | Code: LinkedAuthorizationFailed

### ISSUE THREAD

**Issue by aldairzamoramsft** [Azure/azure-cli#27201]
### Describe the bug

Unable to create a vwan vhub connection to a remote vnet in a cross tenant subscription.

Connection works if powershell is used.

### Related command

az network vhub connection create --resource-group "rg-test" --name "cross-vnet-connection-01" --vhub-name "virtualhub-scus-test" --remote-vnet "/subscriptions/fd9333ae-4947-4e99-801b-e02754f5b62e/resourceGroups/rg-vwan-lab/providers/Microsoft.Network/virtualNetworks/vnet-test"

### Errors

(LinkedAuthorizationFailed) The client has permission to perform action 'Microsoft.Network/virtualNetworks/peer/action' on scope '/subscriptions/9bf48539-d253-4f7d-9370-a5e17815325e/resourceGroups/rg-test/providers/Microsoft.Network/virtualHubs/virtualhub-scus-test/hubVirtualNetworkConnections/cross-vnet-connection-01', however the current tenant '72f988bf-86f1-41af-91ab-2d7cd011db47' is not authorized to access linked subscription 'fd9333ae-4947-4e99-801b-e02754f5b62e'.
Code: LinkedAuthorizationFailed
Message: The client has permission to perform action 'Microsoft.Network/virtualNetworks/peer/action' on scope '/subscriptions/9bf48539-d253-4f7d-9370-a5e17815325e/resourceGroups/rg-test/providers/Microsoft.Network/virtualHubs/virtualhub-scus-test/hubVirtualNetworkConnections/cross-vnet-connection-01', however the current tenant '72f988bf-86f1-41af-91ab-2d7cd011db47' is not authorized to access linked subscription 'fd9333ae-4947-4e99-801b-e02754f5b62e'.

### Issue script & Debug output

cli.knack.cli: Command arguments: ['network', 'vhub', 'connection', 'create', '--resource-group', 'rg-test', '--name', 'cross-vnet-connection-01', '--vhub-name', 'virtualhub-scus-test', '--remote-vnet', '/subscriptions/fd9333ae-4947-4e99-801b-e02754f5b62e/resourceGroups/rg-vwan-lab/providers/Microsoft.Network/virtualNetworks/vnet-test', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x01FEA538>, <function OutputProducer.on_global_arguments at 0x021EC778>, <function CLIQuery.on_global_arguments at 0x022083D0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'network': ['azure.cli.command_modules.network', 'azure.cli.command_modules.privatedns', 'azext_vwan']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: network                   0.944       115       453
cli.azure.cli.core: privatedns                0.029        14        63
cli.azure.cli.core: Total (2)                 0.974       129       516
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: virtual-wan               0.079        22        83  C:\Users\aldairzamora\.azure\cliextensions\virtual-wan
cli.azure.cli.core: Total (1)                 0.079        22        83
cli.azure.cli.core: Loaded 149 groups, 599 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : network vhub connection create
cli.azure.cli.core: Command table: network vhub connection create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x043AB6A0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\aldairzamora\.azure\commands\2023-08-18.14-08-51.network_vhub_connection_create.4692.log'.
az_command_data_logger: command args: network vhub connection create --resource-group {} --name {} --vhub-name {} --remote-vnet {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x045DF4A8>]
D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\OpenSSL/_util.py:6: UserWarning: You are using cryptography on a 32-bit Python on a 64-bit Windows Operating System. Cryptography will be significantly faster if you switch to using a 64-bit Python.
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x045DFA00>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x045DF928>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x021EC7C0>, <function CLIQuery.handle_query_parameter at 0x02208418>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x045DF8E0>]
az_command_data_logger: extension name: virtual-wan
az_command_data_logger: extension version: 0.2.17
azext_vwan.vendored_sdks.v2022_07_01._serialization: allow_remote_vnet_to_use_hub_vnet_gateway is not a known attribute of class <class 'azext_vwan.vendored_sdks.v2022_07_01.v2022_07_01.models._models_py3.HubVirtualNetworkConnection'> and will be ignored
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=NetworkManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\aldairzamora\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\aldairzamora\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/kerberos', 'tenant_region_scope': 'WW', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: a6fa488e-5395-41dc-84f2-c907966cd372
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/9bf48539-d253-4f7d-9370-a5e17815325e/resourceGroups/rg-test/providers/Microsoft.Network/virtualHubs/virtualhub-scus-test/hubVirtualNetworkConnections/cross-vnet-connection-01?api-version=2022-07-01'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '307'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '0c568530-3e03-11ee-8c0e-010101010000'
cli.azure.cli.core.sdk.policies:     'CommandName': 'network vhub connection create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --name --vhub-name --remote-vnet --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.51.0 (MSI) azsdk-python-azure-mgmt-network/22.2.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"name": "cross-vnet-connection-01", "properties": {"remoteVirtualNetwork": {"id": "/subscriptions/fd9333ae-4947-4e99-801b-e02754f5b62e/resourceGroups/rg-vwan-lab/providers/Microsoft.Network/virtualNetworks/vnet-test"}, "enableInternetSecurity": true, "routingConfiguration": {"propagatedRouteTables": {}}}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/9bf48539-d253-4f7d-9370-a5e17815325e/resourceGroups/rg-test/providers/Microsoft.Network/virtualHubs/virtualhub-scus-test/hubVirtualNetworkConnections/cross-vnet-connection-01?api-version=2022-07-01 HTTP/1.1" 403 506
cli.azure.cli.core.sdk.policies: Response status: 403
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'gateway'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'e20160cb-a62e-4fee-974c-ec04c2222643'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'e20160cb-a62e-4fee-974c-ec04c2222643'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'CENTRALUS:20230818T200852Z:e20160cb-a62e-4fee-974c-ec04c2222643'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Fri, 18 Aug 2023 20:08:51 GMT'
cli.azure.cli.core.sdk.policies:     'Connection': 'close'
cli.azure.cli.core.sdk.policies:     'Content-Length': '506'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"LinkedAuthorizationFailed","message":"The client has permission to perform action 'Microsoft.Network/virtualNetworks/peer/action' on scope '/subscriptions/9bf48539-d253-4f7d-9370-a5e17815325e/resourceGroups/rg-test/providers/Microsoft.Network/virtualHubs/virtualhub-scus-test/hubVirtualNetworkConnections/cross-vnet-connection-01', however the current tenant '72f988bf-86f1-41af-91ab-2d7cd011db47' is not authorized to access linked subscription 'fd9333ae-4947-4e99-801b-e02754f5b62e'."}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\aldairzamora\.azure\cliextensions\virtual-wan\azext_vwan\custom.py", line 235, in create_hub_vnet_connection
    return sdk_no_wait(no_wait, client.begin_create_or_update, resource_group_name,
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 716, in sdk_no_wait
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
  File "C:\Users\aldairzamora\.azure\cliextensions\virtual-wan\azext_vwan\vendored_sdks\v2022_07_01\v2022_07_01\operations\_operations.py", line 86752, in begin_create_or_update
    raw_result = self._create_or_update_initial(
  File "C:\Users\aldairzamora\.azure\cliextensions\virtual-wan\azext_vwan\vendored_sdks\v2022_07_01\v2022_07_01\operations\_operations.py", line 86603, in _create_or_update_initial
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (LinkedAuthorizationFailed) The client has permission to perform action 'Microsoft.Network/virtualNetworks/peer/action' on scope '/subscriptions/9bf48539-d253-4f7d-9370-a5e17815325e/resourceGroups/rg-test/providers/Microsoft.Network/virtualHubs/virtualhub-scus-test/hubVirtualNetworkConnections/cross-vnet-connection-01', however the current tenant '72f988bf-86f1-41af-91ab-2d7cd011db47' is not authorized to access linked subscription 'fd9333ae-4947-4e99-801b-e02754f5b62e'.
Code: LinkedAuthorizationFailed
Message: The client has permission to perform action 'Microsoft.Network/virtualNetworks/peer/action' on scope '/subscriptions/9bf48539-d253-4f7d-9370-a5e17815325e/resourceGroups/rg-test/providers/Microsoft.Network/virtualHubs/virtualhub-scus-test/hubVirtualNetworkConnections/cross-vnet-connection-01', however the current tenant '72f988bf-86f1-41af-91ab-2d7cd011db47' is not authorized to access linked subscription 'fd9333ae-4947-4e99-801b-e02754f5b62e'.

cli.azure.cli.core.azclierror: (LinkedAuthorizationFailed) The client has permission to perform action 'Microsoft.Network/virtualNetworks/peer/action' on scope '/subscriptions/9bf48539-d253-4f7d-9370-a5e17815325e/resourceGroups/rg-test/providers/Microsoft.Network/virtualHubs/virtualhub-scus-test/hubVirtualNetworkConnections/cross-vnet-connection-01', however the current tenant '72f988bf-86f1-41af-91ab-2d7cd011db47' is not authorized to access linked subscription 'fd9333ae-4947-4e99-801b-e02754f5b62e'.
Code: LinkedAuthorizationFailed
Message: The client has permission to perform action 'Microsoft.Network/virtualNetworks/peer/action' on scope '/subscriptions/9bf48539-d253-4f7d-9370-a5e17815325e/resourceGroups/rg-test/providers/Microsoft.Network/virtualHubs/virtualhub-scus-test/hubVirtualNetworkConnections/cross-vnet-connection-01', however the current tenant '72f988bf-86f1-41af-91ab-2d7cd011db47' is not authorized to access linked subscription 'fd9333ae-4947-4e99-801b-e02754f5b62e'.
az_command_data_logger: (LinkedAuthorizationFailed) The client has permission to perform action 'Microsoft.Network/virtualNetworks/peer/action' on scope '/subscriptions/9bf48539-d253-4f7d-9370-a5e17815325e/resourceGroups/rg-test/providers/Microsoft.Network/virtualHubs/virtualhub-scus-test/hubVirtualNetworkConnections/cross-vnet-connection-01', however the current tenant '72f988bf-86f1-41af-91ab-2d7cd011db47' is not authorized to access linked subscription 'fd9333ae-4947-4e99-801b-e02754f5b62e'.
Code: LinkedAuthorizationFailed
Message: The client has permission to perform action 'Microsoft.Network/virtualNetworks/peer/action' on scope '/subscriptions/9bf48539-d253-4f7d-9370-a5e17815325e/resourceGroups/rg-test/providers/Microsoft.Network/virtualHubs/virtualhub-scus-test/hubVirtualNetworkConnections/cross-vnet-connection-01', however the current tenant '72f988bf-86f1-41af-91ab-2d7cd011db47' is not authorized to access linked subscription 'fd9333ae-4947-4e99-801b-e02754f5b62e'.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x043AB7C0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 4.166 seconds (init: 1.928, invoke: 2.238)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 4479 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\aldairzamora\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process

### Expected behavior

successfully create the vhub connection

### Environment Summary

azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Extensions:
virtual-wan                       0.2.17

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\aldairzamora\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
virtual-wan 0.3.0 fixed it, please feel free to upgrade.
