### ISSUE TITLE
Bug : Provide Own name for the AKS node resource group

### ISSUE THREAD

**Issue by ksingh-scogo** [Azure/azure-cli#27215]
### Describe the bug

Using Azure Portal Cloud Shell , we are trying to create AKS cluster via CLI. We need to supply Node Resource Group Name using `--node-resource-group` parameter as defined in the [documentation](https://learn.microsoft.com/en-us/azure/aks/faq#can-i-provide-my-own-name-for-the-aks-node-resource-group)

While doing this we are getting error `Node resource group 'XXXX_Staging_RG' is the same as ResourceGroup 'XXXX_Staging_RG', which is not allowed`

### Related command

```
az aks create --resource-group XXXXX_Staging_RG --node-resource-group XXXXX_Staging_RG --name XXXXX-Staging-AKS-1 --node-count 3 --enable-addons monitoring --generate-ssh-keys --enable-keda --nodepool-name ondemand --node-vm-size Standard_D4as_v5 --node-osdisk-size 30  --tier free --tags "created_by=admin" "environment=staging" --nodepool-labels nodepool-type=ondemand --nodepool-tags "created_by=admin" "environment=staging" --attach-acr XXXXX --verbose
```

### Errors

```
(NodeResourceGroupSameAsResourceGroup) Node resource group 'XXXX_Staging_RG' is the same as ResourceGroup 'XXXX_Staging_RG', which is not allowed, please provide a different node resource group.
Code: NodeResourceGroupSameAsResourceGroup
Message: Node resource group 'XXXX_Staging_RG' is the same as ResourceGroup 'XXXX_Staging_RG', which is not allowed, please provide a different node resource group.
```

### Issue script & Debug output

```
(NodeResourceGroupSameAsResourceGroup) Node resource group 'XXXX_Staging_RG' is the same as ResourceGroup 'XXXX_Staging_RG', which is not allowed, please provide a different node resource group.
Code: NodeResourceGroupSameAsResourceGroup
Message: Node resource group 'XXXX_Staging_RG' is the same as ResourceGroup 'XXXX_Staging_RG', which is not allowed, please provide a different node resource group.
```

### Expected behavior

As [documentation](https://learn.microsoft.com/en-us/azure/aks/faq#can-i-provide-my-own-name-for-the-aks-node-resource-group) clearly mentions user provided node resource group names could be provided by using `--node-resource-group` parameter of `az aks create` command with the help of [aks-preview](https://learn.microsoft.com/en-us/cli/azure/aks) Azure CLI extension version 0.3.2 or later

### Environment Summary

```
{
  "azure-cli": "2.51.0",
  "azure-cli-core": "2.51.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "ai-examples": "0.2.5",
    "aks-preview": "0.5.152",
    "ml": "2.19.1",
    "ssh": "2.0.1"
  }
}
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by ksingh-scogo** [comment]
For the record we are using Azure Cloud Shell from the Azure Portal

**Comment by navba-MSFT** [comment]
@ksingh-scogo Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by FumingZhang** [comment]
Hey @ksingh-scogo, the error message is returned from server side and it means you should choose different resource groups for the cluster and other managed resources like `az aks create --resource-group <rg1> --node-resource-group <rg2> --name <cluster-name>`.

While the docs don't explicitly state this, I don't think it's possible to put the cluster and other managed resources in the same resource group. Maybe we should update the doc @Azure/aks-pm

**Comment by ksingh-scogo** [comment]
@FumingZhang  thanks for looking into this issue, i am looking for a way through AZ CLI by which i can put the AKS cluster and other managed groups into the same Resource Group.

**Comment by FumingZhang** [comment]
@ksingh-scogo I suppose this is not possible at the moment, and I would like to know how you made it

**Comment by ksingh-scogo** [comment]
@FumingZhang  what would your say this this ?

<img width="892" alt="image" src="https://github.com/Azure/azure-cli/assets/76433381/821370b2-13ee-41e6-a2ae-46ef31926331">

- [source](https://learn.microsoft.com/en-us/azure/aks/faq#can-i-provide-my-own-name-for-the-aks-node-resource-group)

**Comment by FumingZhang** [comment]
@ksingh-scogo, the doc says you could put the managed resource to a resource group with custom name, BUT I don't think it's possible to put them to the same resource group where the AKS resource (i.e., managed cluster) locates, and this is what the error message telling you.

To give a more concrete example, if you create a cluster named `dev100` in resource group `azcli-aks-dev` in location `eastus`, the default node resource group name is `MC_azcli-aks-dev_dev101_eastus` and you can customize the name of this node resource group to something like `AKS_Managed_Resource_Group_For_dev101` **but not** `azcli-aks-dev` (where AKS cluster locates).

**Comment by ksingh-scogo** [comment]
@FumingZhang  So you mean the Azure Official Docs does not have correct information ? Pls confirm so that i can take necessary steps ?

**Comment by FumingZhang** [comment]
I don't see what _incorrect_ information the doc provides. It says 

> As you work with the node resource group, keep in mind that you can't:
>     Specify an **existing** resource group for the node resource group.

The rg where the AKS cluster locates needs to be created in advance by the user, and the node rg is created by AKS, which prevents user from using the same rg.

**Comment by FumingZhang** [comment]
![image](https://github.com/Azure/azure-cli/assets/81607949/aa3b24a5-440c-4a61-bbd4-edb2d60abadc)

you **cann't** "Specify an existing resource group for the node resource group"

**Comment by navba-MSFT** [comment]
@ksingh-scogo I hope you had a chance to look at the above comment. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by ksingh-scogo** [comment]
@FumingZhang  @navba-MSFT  what is the process to submit this issue as a feature request ? Can you help linking this to the right place / right project ?
