### ISSUE TITLE
Incorrect examples for `az acr network-rule add`

### ISSUE THREAD

**Issue by hugo-paredes** [Azure/azure-cli#27224]
### Describe the bug

When running the command `az acr network-rule add --name <acr_name> --subnet <subnet_id>`, it tells me that the `subnet` property is deprecated and it will be removed.

The documentation page, doesn't show these properties in the command description, but it uses them in the examples. It isn't very clear.

Another thing is the description of certain properties, they aren't very descriptive. In the same page, there's reference to the resource group, but it doesn't specify which resource group. Is it for the vnets? Is it for the container registry?

### Related command

`az acr network-rule add --name <acr_name> --subnet <subnet_id>`

### Errors

Argument 'subnet' has been deprecated and will be removed in a future release.

### Issue script & Debug output

N/A

### Expected behavior

N/A

### Environment Summary

azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/home/vmadmin/.azure/cliextensions'

Python (Linux) 3.10.10 (main, Jul 27 2023, 07:10:25) [GCC 11.3.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by SaurabhSharma-MSFT** [comment]
@hugo-paredes The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
