### ISSUE TITLE
AZ CLI  does not consider cross-resourcegroup network rules on: az keyvault network-rule add

### ISSUE THREAD

**Issue by FabianGonzalez-MSFT** [Azure/azure-cli#27238]
### Describe the bug

If you execute the following cmdlet:

az keyvault network-rule add --name ContosoKV --vnet-name ContosoVnet --subnet default

And the Vnet/Subnet are in a different Resource Group (RG) within the same subscription. It will fail with the following error:

`DEBUG: cli.azure.cli.core.sdk.policies: {"error":{"code":"VirtualNetworkNotValid","message":"Operation on Virtual Network could not be performed. StatusCode: 404 (NotFound). Error Code: ParentResourceNotFound. Error Message: Failed to perform 'action' on resource(s) of type 'virtualNetworks/taggedTrafficConsumers', because the parent resource '/subscriptions/*****/resourceGroups/*******/providers/microsoft.network/virtualNetworks/VnetName' could not be found.."}}`

Adding a network rule with a Vnet/Subnet in different RG than the KV's one is possible and supported. Through the GUI it gives no error.

Through further investigation, I found out that if you run the command including '--vnet-name' + 'subnet', CLI makes an assumption that the Vnet is part of the same KV's RG and looks for that Vnet in that RG, and as the Vnet/Subnet exist in different RG, it returns the above error.

A workaround was to use the subnet ID instead by running the cmdlet like this which ran successfully and somehow "demonstrates" it's a valid operation at service-level:

az keyvault network-rule add --name ContosoKV --subnet "/subscriptions/xxxxxxxxxxx/resourceGroups/**non-AKV-RG**/providers/Microsoft.Network/virtualNetworks/**non-AKV-RG-Vnet**/subnets/**non-AKV-RG-subnet**"

### Related command

az keyvault network-rule add 

### Errors

DEBUG: cli.azure.cli.core.sdk.policies: {"error":{"code":"VirtualNetworkNotValid","message":"Operation on Virtual Network could not be performed. StatusCode: 404 (NotFound). Error Code: ParentResourceNotFound. Error Message: Failed to perform 'action' on resource(s) of type 'virtualNetworks/taggedTrafficConsumers', because the parent resource '/subscriptions/*****/resourceGroups/*******/providers/microsoft.network/virtualNetworks/VnetName' could not be found.."}}

### Issue script & Debug output

DEBUG: cli.azure.cli.core.sdk.policies: {"error":{"code":"VirtualNetworkNotValid","message":"Operation on Virtual Network could not be performed. StatusCode: 404 (NotFound). Error Code: ParentResourceNotFound. Error Message: Failed to perform 'action' on resource(s) of type 'virtualNetworks/taggedTrafficConsumers', because the parent resource '/subscriptions/*****/resourceGroups/*******/providers/microsoft.network/virtualNetworks/VnetName' could not be found.."}}

### Expected behavior

CLI should not assume KV and Vnet RG is the same and allow the operation with no error.

### Environment Summary

azure-cli                         2.32.0 *  (**But also reproducible on latest version 2.51.0**)

core                              2.32.0 *
telemetry                          1.0.6 *

Dependencies:
msal                              1.16.0
azure-mgmt-resource               20.0.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\fagonza\.azure\cliextensions'

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by evelyn-ys** [comment]
By design. Using `--subnet $subnetID` is the right way to add subnet in different resource group.
