### ISSUE TITLE
'az keyvault set-policy' fails with "The api-version '2023-02-01' is invalid."

### ISSUE THREAD

**Issue by vhhughes** [Azure/azure-cli#27239]
### Describe the bug

When using the Azure CLI version 2.51.0 (which is current), attempting to use "az keyvault set-policy" results in an error.

### Related command

az keyvault set-policy

### Errors

Operation returned an invalid status 'Bad Request'
Content: "{\"error\":{\"code\":\"InvalidApiVersionParameter\",\"message\":\"The api-version '2023-02-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.\"}}"

### Issue script & Debug output

cli.knack.cli: Command arguments: ['keyvault', 'set-policy', '--name', 'kv-foo', '--secret-permissions', 'get', '--object-id', 'd2f3b918-63b3-44fb-9608-a77ccec8661b', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x040FA4F0>, <function OutputProducer.on_global_arguments at 0x042FB730>, <function CLIQuery.on_global_arguments at 0x04318388>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'keyvault': ['azure.cli.command_modules.keyvault']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: keyvault                  0.017        22       133
cli.azure.cli.core: Total (1)                 0.017        22       133
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 22 groups, 133 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : keyvault set-policy
cli.azure.cli.core: Command table: keyvault set-policy
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x04EAB580>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\chughev\.azure\commands\2023-08-22.22-38-40.keyvault_set-policy.7984.log'.
az_command_data_logger: command args: keyvault set-policy --name {} --secret-permissions {} --object-id {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x04ED3658>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x04EE3580>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x04EE3778>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x042FB778>, <function CLIQuery.handle_query_parameter at 0x043183D0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x04EE3730>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=KeyVaultManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\chughev\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\chughev\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/a1f1e214-7ded-45b6-81a1-9e8ae3459641/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/a1f1e214-7ded-45b6-81a1-9e8ae3459641/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/a1f1e214-7ded-45b6-81a1-9e8ae3459641/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/a1f1e214-7ded-45b6-81a1-9e8ae3459641/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/a1f1e214-7ded-45b6-81a1-9e8ae3459641/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/a1f1e214-7ded-45b6-81a1-9e8ae3459641/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/a1f1e214-7ded-45b6-81a1-9e8ae3459641/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? True
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 1f7a350d-f558-4e83-86db-dd69bfba4168
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/64a50daa-16fd-48c0-95cd-5317e14fe14d/resources?$filter=resourceType%20eq%20%27Microsoft.KeyVault%2Fvaults%27%20and%20name%20eq%20%27kv-foo%27&api-version=2015-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '505914d9-4177-11ee-ade3-3814280333d7'
cli.azure.cli.core.sdk.policies:     'CommandName': 'keyvault set-policy'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --secret-permissions --object-id --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.51.0 (MSI) azsdk-python-azure-mgmt-keyvault/10.2.2 Python/3.10.10 (Windows-10-10.0.19045-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/64a50daa-16fd-48c0-95cd-5317e14fe14d/resources?$filter=resourceType%20eq%20%27Microsoft.KeyVault%2Fvaults%27%20and%20name%20eq%20%27kv-foo%27&api-version=2015-11-01 HTTP/1.1" 200 621
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '621'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'c410b344-33bf-4f6c-9ea5-d2c1c864963a'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'c410b344-33bf-4f6c-9ea5-d2c1c864963a'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHCENTRALUS:20230823T053841Z:c410b344-33bf-4f6c-9ea5-d2c1c864963a'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: 145A0F227C7846A2BF07278BC7FF2698 Ref B: CO6AA3150218045 Ref C: 2023-08-23T05:38:41Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 23 Aug 2023 05:38:41 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"value":[],"nextLink":"https://management.azure.com/subscriptions/64a50daa-16fd-48c0-95cd-5317e14fe14d/resources?%24filter=resourceType+eq+%27Microsoft.KeyVault%2fvaults%27+and+name+eq+%27kv-foo%27&api-version=2015-11-01&%24skiptoken=eyJuZXh0UGFydGl0aW9uS2V5IjoiMSE4IU9UQkJOelktIiwibmV4dFJvd0tleSI6IjEhMjIwIU5qUkJOVEJFUVVFeE5rWkVORGhETURrMVEwUTFNekUzUlRFMFJrVXhORVJmUjFKTUxVRmFWVkpGUWtGRFMxVlFVa2M2TlVaRlFWTlVWVk15T2pWR01pMU5TVU5TVDFOUFJsUTZNa1ZEVDAxUVZWUkZPakpHVWtWVFZFOVNSVkJQU1U1VVEwOU1URVZEVkVsUFRsTTZNa1pCV2xWU1JVSkJRMHRWVURvMVJrb3dNekJUTkRjd09qVkdOVFF4TXpjek1UTTNNekUzT1RnMU56Y3lNaTFGUVZOVVZWTXkifQ%3d%3d"}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/64a50daa-16fd-48c0-95cd-5317e14fe14d/resources?$filter=resourceType%20eq%20%27Microsoft.KeyVault/vaults%27%20and%20name%20eq%20%27kv-foo%27&api-version=2023-02-01&$skiptoken=eyJuZXh0UGFydGl0aW9uS2V5IjoiMSE4IU9UQkJOelktIiwibmV4dFJvd0tleSI6IjEhMjIwIU5qUkJOVEJFUVVFeE5rWkVORGhETURrMVEwUTFNekUzUlRFMFJrVXhORVJmUjFKTUxVRmFWVkpGUWtGRFMxVlFVa2M2TlVaRlFWTlVWVk15T2pWR01pMU5TVU5TVDFOUFJsUTZNa1ZEVDAxUVZWUkZPakpHVWtWVFZFOVNSVkJQU1U1VVEwOU1URVZEVkVsUFRsTTZNa1pCV2xWU1JVSkJRMHRWVURvMVJrb3dNekJUTkRjd09qVkdOVFF4TXpjek1UTTNNekUzT1RnMU56Y3lNaTFGUVZOVVZWTXkifQ%3D%3D'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '505914d9-4177-11ee-ade3-3814280333d7'
cli.azure.cli.core.sdk.policies:     'CommandName': 'keyvault set-policy'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--name --secret-permissions --object-id --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.51.0 (MSI) azsdk-python-azure-mgmt-keyvault/10.2.2 Python/3.10.10 (Windows-10-10.0.19045-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/64a50daa-16fd-48c0-95cd-5317e14fe14d/resources?$filter=resourceType%20eq%20%27Microsoft.KeyVault/vaults%27%20and%20name%20eq%20%27kv-foo%27&api-version=2023-02-01&$skiptoken=eyJuZXh0UGFydGl0aW9uS2V5IjoiMSE4IU9UQkJOelktIiwibmV4dFJvd0tleSI6IjEhMjIwIU5qUkJOVEJFUVVFeE5rWkVORGhETURrMVEwUTFNekUzUlRFMFJrVXhORVJmUjFKTUxVRmFWVkpGUWtGRFMxVlFVa2M2TlVaRlFWTlVWVk15T2pWR01pMU5TVU5TVDFOUFJsUTZNa1ZEVDAxUVZWUkZPakpHVWtWVFZFOVNSVkJQU1U1VVEwOU1URVZEVkVsUFRsTTZNa1pCV2xWU1JVSkJRMHRWVURvMVJrb3dNekJUTkRjd09qVkdOVFF4TXpjek1UTTNNekUzT1RnMU56Y3lNaTFGUVZOVVZWTXkifQ%3D%3D HTTP/1.1" 400 773
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '773'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'd69b70fb-cb2f-4e93-a406-05122d002301'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'd69b70fb-cb2f-4e93-a406-05122d002301'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTUS:20230823T053842Z:d69b70fb-cb2f-4e93-a406-05122d002301'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: 642A82CA010344C7B6EBBEF2DF8D4ECF Ref B: CO6AA3150218045 Ref C: 2023-08-23T05:38:41Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 23 Aug 2023 05:38:41 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: "{\"error\":{\"code\":\"InvalidApiVersionParameter\",\"message\":\"The api-version '2023-02-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.\"}}"
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/invocation.py", line 113, in _validation
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 859, in _validate_arg_level
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/_validators.py", line 387, in validate_resource_group_name
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/keyvault/_validators.py", line 110, in _get_resource_group_from_resource_name
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 128, in __next__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/paging.py", line 76, in __next__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/keyvault/v2023_02_01/operations/_vaults_operations.py", line 1591, in get_next
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'
Content: "{\"error\":{\"code\":\"InvalidApiVersionParameter\",\"message\":\"The api-version '2023-02-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.\"}}"

cli.azure.cli.core.azclierror: Operation returned an invalid status 'Bad Request'
Content: "{\"error\":{\"code\":\"InvalidApiVersionParameter\",\"message\":\"The api-version '2023-02-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.\"}}"
az_command_data_logger: Operation returned an invalid status 'Bad Request'
Content: "{\"error\":{\"code\":\"InvalidApiVersionParameter\",\"message\":\"The api-version '2023-02-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.\"}}"
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x04EAB6A0>]
az_command_data_logger: exit code: 2
cli.__main__: Command ran in 2.388 seconds (init: 0.578, invoke: 1.810)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 4261 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\chughev\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

The command should execute successfully.

### Environment Summary

azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Extensions:
application-insights              0.1.18
arcdata                            1.5.4
cosmosdb-preview                  0.22.0
datafactory                        0.7.0
front-door                        1.0.17
storage-preview                    0.8.4

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\chughev\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

### Additional context

None

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by luis261** [comment]
Can we please get an update on this? As described [here](https://github.com/MicrosoftDocs/azure-docs/commit/48a0cf5dd923f2739860fc2a4fc0c1c3f4d178ed#commitcomment-125663586), it seems like there might be plans to deprecate access policies for Key Vaults entirely? It would really help if I'd know whether this is just a temporary bug or if MSFT is moving away from access policies entirely and we shouldn't expect this to ever be functional again

**Comment by evelyn-ys** [comment]
This will be fixed in CLI next release(CLI 2.52.0 on 2023-09-05). For tmp workaround, pls specify `--resource-group` manually

**Comment by luis261** [comment]
> This will be fixed in CLI next release(CLI 2.52.0 on 2023-09-05). For tmp workaround, pls specify `--resource-group` manually

Thank you for replying this quickly! I could verify that specifying `--resource-group` manually is indeed a valid workaround
