### ISSUE TITLE
Enable Autoupgrade by default for CodeIntegrityAgent extension

### ISSUE THREAD

**Issue by MS030611** [Azure/azure-cli#27244]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az vm extension set --force-update --subscription __subscription_guid__ --resource-group __resource-group-name__ --vm-name __vm-name__ --name CodeIntegrityAgent --publisher Microsoft.Azure.Security.WindowsCodeIntegrity --enable-auto-upgrade true

az vmss extension set --force-update --subscription __subscription_guid__ --resource-group __resource-group-name__ --vmss-name __vmss-name__ --name CodeIntegrityAgent --publisher Microsoft.Azure.Security.WindowsCodeIntegrity --enable-auto-upgrade true

### Resource Provider

Microsoft.Compute/virtualMachines/extensions

### Description of Feature or Work Requested

CodeIntegrityAgent Extension on install should have autoupgrade flag enabled by default as this is an extension which is crucial in emergency scenarios to switch Code Integrity state and autoupdate is needed to pick the latest set of changes.

--enable-auto-upgrade true should be applied by default.

### Minimum API Version Required

2018-10-01

### Swagger PR link / SDK link

N/A

### Request Example

N/A

### Target Date

2023-09-15

### PM Contact

isamure

### Engineer Contact

smudduluru

### Additional context

CodeIntegrityAgent extension deploys a client process that runs as a system service and checks/updates Code Integrity state of the machine timely. It won't break any existing processes on client machine.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by MS030611** [comment]
++Arihant FYI

**Comment by yanzhudd** [comment]
Hi @MS030611, since we recently have no more time to develop this feature, may I ask if the ETA 2023-09-26 is acceptable?

**Comment by MS030611** [comment]
Hi Yan,

Yes, on or before 2023-09-26 is acceptable.

Thanks & Regards,
Sahithya M.

**Comment by yanzhudd** [comment]
Hi @MS030611,
let me check if the parameter `--enable-auto-upgrade` should be set `true` by default ignoring values of other parameters? in other words, what scenarios is the `--enable-auto-upgrade true` applied?

**Comment by MS030611** [comment]
CodeIntegrityAgent extension deploys a client process that runs as a system service and checks/updates Code Integrity state of the machine timely. It won't break any existing processes on client machine unless their scripts have a hard dependency on Code Integrity state.

**Comment by yanzhudd** [comment]
Hi @MS030611, 
we noticed that `--enable-auto-upgrade true` is applied by default for `GuestAttestation` extension in `az vm extension` command:
https://github.com/Azure/azure-cli/blob/55813ed2dbd481717150f54c1e9e186a57db183b/src/azure-cli/azure/cli/command_modules/vm/custom.py#L2168-L2169

let me check with you if setting `--enable-auto-upgrade true` by default is also applied to **`GuestAttestation`** extension in **`az vmss extension set`** command?

**Comment by MS030611** [comment]
Yes, we want something similar to what's been done for GuestAttestation extension for our extension i.e. CodeIntegrityAgent.

**Comment by yanzhudd** [comment]
Hi @MS030611, 
I mean currently `--enable-auto-upgrade true` seems to only be applied to `GuestAttestation` extension in `az vm extension` command not including `az vmss extension` command. Let me check with you if it should be also applied to `az vmss extension` command?

**Comment by MS030611** [comment]
Sorry, can't comment for GuestAttestation extension.
But for CodeIntegrityAgent extension, we want --enable-auto-upgrade to be set to true for both az vm extension and az vmss extension.
