### ISSUE TITLE
[Compute] Change default Public IP SKU for "az vm create" 

### ISSUE THREAD

**Issue by cburuzie** [Azure/azure-cli#27254]
**Related command**
"az vm create"
When customers associate a public IP (using "--public-ip-address")
to the VM as part of creation without defining a SKU type. 

**Is your feature request related to a problem? Please describe.**
Last year, we announced the retirement of Basic IPs and created a warning message to cx who were using this command of the upcoming changes of this command's default SKU for Public IPs. Now we would like to change the default SKU to Standard as part of the retirement.

**Describe the solution you'd like**
We want to change the default SKU for Public IP from Basic to Standard IP.

**Describe alternatives you've considered**
N/A

**Additional context**
Previous ask where we added the warning message last year - #18662

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
@cburuzie Do we need to remove the Basic option of `--public-ip-sku`? Currently, it has 2 options: Basic and Standard.

![image](https://github.com/Azure/azure-cli/assets/12371639/0fca1f6c-0156-495c-9f9f-872f10124ec8)
