### ISSUE TITLE
Improvements on az snapshot create and az disk create CLI commands

### ISSUE THREAD

**Issue by AdamZLi** [Azure/azure-cli#27266]
**Related command**
1. az snapshot create
2. az disk create

**Is your feature request related to a problem? Please describe.**
Currently, when running over an OS disk, both commands assume by default Gen1 snapshot/disks, even if the original disk/snapshot is Gen2. The customer has to specify the parameter “--hyper-v-generation V2” for any disk or snapshot created from a Gen2 source, otherwise it will create a V1 (Gen1) disk/snapshot.

This will have the consequence of generating Gen1 disks/snapshots that are not bootable when used to create a VM, because internally a Gen2 disk is GPT/UEFI formatted; it will also prevent a Gen2 VM from being attached or created from that disk/snapshot, as it is marked as V1(Gen1).

**Describe the solution you'd like**
Let the “az snapshot create” and “az disk create” determine the correct disk/snapshot Hyper-V generation from the original disk/snapshot, instead of always defaulting to V1.

**Describe alternatives you've considered**
N/A

**Additional context**
hyperVGeneration V1 is being passed as a value by CLI to diskRP. CLI needs to pass the corret value (V1 or V2)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yanzhudd** [comment]
Hi @AdamZLi,
the info in description is not sufficient for our developing. Could you please reopen a feature request with filling the template ([New Issue · Azure/azure-cli (github.com)](https://github.com/Azure/azure-cli/issues/new?assignees=&labels=feature-request&projects=&template=Service_team_request.yml))?

**Comment by sarahrahman34** [comment]
@yanzhudd Our ask is to not pass V1 as a default value for the hyper-v-generation parameter for this CLI command. No default value should be used.

**Comment by yanzhudd** [comment]
@sarahrahman34, please provide more details, i.e., `Minimum API Version Required`, `Swagger PR link / SDK link`, `Target Date`, etc.

![image](https://github.com/Azure/azure-cli/assets/105691024/662ca2cc-3cd1-49ea-91e0-f4d2814cacb9)

Besides, please specify how to distinguish the disk/snapshot is Gen1/Gen2 (in which scenarios is the value of `--hyper-v-generation` set to `V2`?)

**Comment by zhoxing-ms** [comment]
@AdamZLi @sarahrahman34 Please take a look at the above comment~ Otherwise, this feature request will not be able to join our work plan in a timely manner

**Comment by AdamZLi** [comment]
A new item is treated to triage this with necessary details: https://github.com/Azure/azure-cli/issues/27323

Let us know if any other information is needed.

**Comment by yanzhudd** [comment]
We will use #27323 to follow up this feature request. Let's close this page.

**Comment by yanzhudd** [comment]
We will use https://github.com/Azure/azure-cli/issues/27323 to follow up this feature request. Let's close this page.
