### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by Jordanwaslistening** [Azure/azure-cli#27264]
**Related command**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yonzhan** [comment]
Please provide detailed info.

**Comment by SaurabhSharma-MSFT** [comment]
@Jordanwaslistening Can you please provide details of your issue.
