### ISSUE TITLE
Obviously they changed their API again.

### ISSUE THREAD

**Issue by Talhasaleem110** [Azure/azure-cli#27274]
Obviously they changed their API again.
I recently changed my code because suddenly addresses weren't shown correctly anymore.
It seems they reverted the change - so here is a version where I also reverted my change.

Uninstall
Remove .zip and install

[app-release.apk.zip](https://github.com/woheller69/lavatories/files/12448597/app-release.apk.zip)

_Originally posted by @woheller69 in https://github.com/woheller69/lavatories/issues/14#issuecomment-1694734000_

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
