### ISSUE TITLE
AZ CLI command 'az eventgrid domain topic event-subscription update' occurs error

### ISSUE THREAD

**Issue by scrgee** [Azure/azure-cli#27277]
### Describe the bug

An error occurs when executing the az command:
```shell
az eventgrid domain topic event-subscription update --name subscriptionName -g resourceGroupName 
--domain-name domainName --domain-topic-name topicName --delivery-attribute-mapping headerName1 static value1 true
``` 
Error message: `usage error: --delivery-attribute-mapping NAME TYPE [SOURCEFIELD] [VALUE] [ISSECRET]`

GitHub docs: https://github.com/Azure/azure-cli/blob/azure-cli-2.51.0/src/azure-cli/azure/cli/command_modules/eventgrid/_help.py#L315

The --help option shows the usage:

`--delivery-attribute-mapping -d        : Add delivery attribute mapping to send
                                                            additional information via HTTP headers
                                                            when delivering events. This attribute
                                                            is valid for all destination types
                                                            except StorageQueue. Multiple attributes
                                                            can be specified by using more than one
                                                            `--delivery-attribute-mapping` argument.

        **Usage**:                        --delivery-attribute-mapping attribute-name attribute-type
        attribute-value [attribute-is-secret]
        Static Attribute Mapping:     --delivery-attribute-mapping somename static somevalue
        Static Attribute Mapping:     --delivery-attribute-mapping somename static somevalue false
        Static Attribute Mapping:     --delivery-attribute-mapping somename static somevalue true
        Dynamic Attribute Mapping:    --delivery-attribute-mapping somename dynamic somevalue
        Both Static and Dynamic:      --delivery-attribute-mapping somename dynamic somevalue
                                                      --delivery-attribute-mapping somename2 static somevalue.`

The questions is:
What is the parameter [SOURCEFIELD]  and what value should be there?

### Related command

az eventgrid domain topic event-subscription update --name subscriptionName -g resourceGroupName 
--domain-name domainName --domain-topic-name topicName --delivery-attribute-mapping headerName1 static value1 true

### Errors

usage error: --delivery-attribute-mapping NAME TYPE [SOURCEFIELD] [VALUE] [ISSECRET]

### Issue script & Debug output

cli.knack.cli: Command arguments: ['eventgrid', 'domain', 'topic', 'event-subscription', 'update', '--name', 'test-partner-webhook', '-g', 'RG_DEV', '--domain-name', 'dela-egd-icdp-dev', '--domain-topic-name', 'test-partner', '--delivery-attribute-mapping', 'headerName1', 'static', 'sourceField', 'key1', 'true', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f7ecf39d360>, <function OutputProducer.on_global_arguments at 0x7f7ecf2f8280>, <function CLIQuery.on_global_arguments at 0x7f7ecf115480>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'eventgrid': ['azure.cli.command_modules.eventgrid']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: eventgrid                 0.032        25        96
cli.azure.cli.core: Total (1)                 0.032        25        96
cli.azure.cli.core: Loaded 25 groups, 96 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : eventgrid domain topic event-subscription update
cli.azure.cli.core: Command table: eventgrid domain topic event-subscription update
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f7ece4decb0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/baurzhan/.azure/commands/2023-08-29.12-32-30.eventgrid_domain_topic_event-subscription_update.2503.log'.
az_command_data_logger: command args: eventgrid domain topic event-subscription update --name {} -g {} --domain-name {} -d{} {} --delivery-attribute-mapping {} {} {} {} {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f7ece527910>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f7ece541630>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f7ece541750>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 588, in execute
    parsed_args = self.parser.parse_args(args)
  File "/opt/az/lib/python3.10/site-packages/knack/parser.py", line 261, in parse_args
    return super().parse_args(args)
  File "/opt/az/lib/python3.10/argparse.py", line 1826, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/parser.py", line 281, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/opt/az/lib/python3.10/argparse.py", line 1859, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.10/argparse.py", line 2054, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/opt/az/lib/python3.10/argparse.py", line 2031, in consume_positionals
    take_action(action, args)
  File "/opt/az/lib/python3.10/argparse.py", line 1936, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.10/argparse.py", line 1214, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/parser.py", line 281, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/opt/az/lib/python3.10/argparse.py", line 1859, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.10/argparse.py", line 2054, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/opt/az/lib/python3.10/argparse.py", line 2031, in consume_positionals
    take_action(action, args)
  File "/opt/az/lib/python3.10/argparse.py", line 1936, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.10/argparse.py", line 1214, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/parser.py", line 281, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/opt/az/lib/python3.10/argparse.py", line 1859, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.10/argparse.py", line 2054, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/opt/az/lib/python3.10/argparse.py", line 2031, in consume_positionals
    take_action(action, args)
  File "/opt/az/lib/python3.10/argparse.py", line 1936, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.10/argparse.py", line 1214, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/parser.py", line 281, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/opt/az/lib/python3.10/argparse.py", line 1859, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.10/argparse.py", line 2054, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/opt/az/lib/python3.10/argparse.py", line 2031, in consume_positionals
    take_action(action, args)
  File "/opt/az/lib/python3.10/argparse.py", line 1936, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.10/argparse.py", line 1214, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/parser.py", line 281, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/opt/az/lib/python3.10/argparse.py", line 1859, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.10/argparse.py", line 2054, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/opt/az/lib/python3.10/argparse.py", line 2031, in consume_positionals
    take_action(action, args)
  File "/opt/az/lib/python3.10/argparse.py", line 1936, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.10/argparse.py", line 1214, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/parser.py", line 281, in parse_known_args
    self._namespace, self._raw_arguments = super().parse_known_args(args=args, namespace=namespace)
  File "/opt/az/lib/python3.10/argparse.py", line 1859, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/az/lib/python3.10/argparse.py", line 2072, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/opt/az/lib/python3.10/argparse.py", line 2012, in consume_optional
    take_action(action, args, option_string)
  File "/opt/az/lib/python3.10/argparse.py", line 1936, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/eventgrid/delivery_attribute_mapping.py", line 23, in __call__
    raise CLIError('usage error: --delivery-attribute-mapping NAME TYPE [SOURCEFIELD] [VALUE] [ISSECRET]')
knack.util.CLIError: usage error: --delivery-attribute-mapping NAME TYPE [SOURCEFIELD] [VALUE] [ISSECRET]

cli.azure.cli.core.azclierror: usage error: --delivery-attribute-mapping NAME TYPE [SOURCEFIELD] [VALUE] [ISSECRET]
az_command_data_logger: usage error: --delivery-attribute-mapping NAME TYPE [SOURCEFIELD] [VALUE] [ISSECRET]
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f7ece4deef0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.672 seconds (init: 0.795, invoke: 0.877)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3584 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/bin/../../opt/az/bin/python3 /opt/az/lib/python3.10/site-packages/azure/cli/telemetry/__init__.py /home/baurzhan/.azure"       
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

I'm expected that new delivery properties will  be added to existing domain topic event-subscription

### Environment Summary

azure cli - 2.51.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by scrgee** [comment]
I just found that I missed the dash in the parameter name.

**Comment by sudharsan2020** [comment]
@scrgee `delivery-attribute-mapping` isn't working for me. 
```
az eventgrid system-topic event-subscription create \
    --name $eventGridSubscriptionName \
    --resource-group $resourceGroupName \
    --system-topic-name $eventGridTopicName \
    --endpoint $serviceBusTopicEndpoint \
    --subject-begins-with $eventGridSubjectStart \
    --subject-ends-with $eventGridSubjectEnd \
    --endpoint-type servicebustopic \
    --included-event-types Microsoft.Storage.BlobCreated \
    --delivery-attribute-mapping Label static demo_subscription false
```
Can you please help on this?
