### ISSUE TITLE
Function App: Can't list publishing profiles via ID

### ISSUE THREAD

**Issue by dawidjedrzejczak-intive** [Azure/azure-cli#27273]
### Describe the bug

I can't retrieve publish profile for Function App slot via CLI with ID parameter. 

instead of slot publish profile I am receiving production slot publish profile 
`az functionapp deployment list-publishing-profiles --ids "/subscriptions/***/resourceGroups/func-sb-plecomm-slots-deploy/providers/Microsoft.Web/sites/func-sb-plecomm-slots-deploy/slots/pr-2772" --xml`

### Related command

az functionapp deployment list-publishing-profiles --ids

### Errors

Receiving production publish profile instead of slot.

### Issue script & Debug output

Issue described above.

### Expected behavior

Command `az functionapp deployment list-publishing-profiles --ids` will return correct publish profile

### Environment Summary

azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Extensions:
account                            0.2.5
resource-graph                     2.1.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\dawid.jedrzejczak\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by SaurabhSharma-MSFT** [comment]
@dawidjedrzejczak-intive
You need to use the `--slot` parameter along with `--ids` to get function app slot publishing profile.
Example - 
`az functionapp deployment list-publishing-profiles --ids /subscriptions/{subscriptionid}/resourceGroups/{resourcegroup}/providers/Microsoft.Web/sites/{websitename} --slot {slotname}`.
Thanks
Saurabh
