### ISSUE TITLE
Implement slot parameter for az functionapp function show

### ISSUE THREAD

**Issue by luis261** [Azure/azure-cli#27297]
**Related command**

`az functionapp function show`

**Is your feature request related to a problem? Please describe.**

I can't find a way to run `az functionapp function show` and target a deployment slot (besides the default/production one).
It apparently does not offer a `--slot` parameter: https://learn.microsoft.com/en-us/cli/azure/functionapp/function?view=azure-cli-latest#az-functionapp-function-show

![unrecognized_arg](https://github.com/Azure/azure-cli/assets/72552948/c0e211da-7aa7-4c63-97ea-42b513ae3fb4)

**Describe the solution you'd like**

Please consider adding a `--slot` parameter to `az functionapp function show`

**Describe alternatives you've considered**

I tried a workaround via modifying `--name` to match the test slots name, but that does not seem to work

![target_function](https://github.com/Azure/azure-cli/assets/72552948/6a1531f6-031c-45a9-81c0-667aece1acea)

![not_found](https://github.com/Azure/azure-cli/assets/72552948/5593791d-fd35-4ac4-9f2e-73abd6108c19)

**Additional context**

This is the context in which I would use the new parameter: https://github.com/luis261/aztraphile/blob/reintroduce-slot-bound-http-invocations/utils/aztra-utils.ps1#L334

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by kamperiadis** [comment]
Hello @luis261 Thank you for your feedback. This is a feature request I just added to our backlog. In the meantime, you would just have to make direct API calls to `https://management.azure.com/subscriptions/<subscriptionId>/resourceGroups/<resourceGroup>/providers/Microsoft.Web/sites/<functionAppName>/slots/<slotName>/functions/<functionName>?api-version=2022-03-01`.

**Comment by luis261** [comment]
Hi @kamperiadis - glad to know it made the backlog! Thanks for keeping me in the loop. Also good to know the alternative via the direct API call (:
