### ISSUE TITLE
az sf cluster list issues

### ISSUE THREAD

**Issue by RicardoCostaPS** [Azure/azure-cli#27304]
### Describe the bug

[az sf cluster list](https://learn.microsoft.com/en-us/cli/azure/sf/cluster?view=azure-cli-latest#az-sf-cluster-list) fails to list azure hosted service fabric clusters ( azure service fabric clusters with version 9.0.1114.1 ) ( using --subscription ). The issue started happening very recently and it creates issues for API's that rely on this cli command. 

### Related command

az sf cluster list --subscription {subscriptionID}

### Errors

Service Fabric clusters deployed and ready aren't being listed ( not all service fabric clusters weirdly, some aren't listed in output )

### Issue script & Debug output

Regular ouput with some service fabric clusters not listed

### Expected behavior

All service fabric clusters deployed and ready listed

### Environment Summary

Ubuntu 18.04

{
  "azure-cli": "2.36.0",
  "azure-cli-core": "2.36.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "account": "0.2.1"
  }
}

### Additional context

Command has worked fine for a very long time, recently it's missing clusters that are live and ready for listing.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@RicardoCostaPS Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you please upgrade your AzCLI to the [most recent version](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#update-azure-cli) and test again ?

**Comment by RicardoCostaPS** [comment]
az upgrade
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
You already have the latest azure-cli version: 2.52.0
Upgrade finished.You can enable auto-upgrade with 'az config set auto-upgrade.enable=yes'. More details in https://docs.microsoft.com/cli/azure/update-azure-cli#automatic-update

What's the max number of results being displayed by this command ? Looks like only 1 cluster is outputted by this command.

**Comment by RicardoCostaPS** [comment]
The rest api works ( I still need the cli to work though, doesn't mean issue is fixed ), if you keep requesting the next link variable ( can't remember if this new or old stuff )  from -> https://learn.microsoft.com/en-us/rest/api/servicefabric/sfrp-model-clusterlistresult

**Comment by navba-MSFT** [comment]
@RicardoCostaPS Thanks for the update. Please run the below command:

Set the concerned subscription context:
> az account set --subscription "XXXX-XXXX-XXXX-XXXXX"

Then run the below CLI command to list the SF clusters:
> az resource list --resource-type Microsoft.ServiceFabric/clusters

**Comment by RicardoCostaPS** [comment]
> @RicardoCostaPS Thanks for the update. Please run the below command:
> 
> Set the concerned subscription context:
> 
> > az account set --subscription "XXXX-XXXX-XXXX-XXXXX"
> 
> Then run the below CLI command to list the SF clusters:
> 
> > az resource list --resource-type Microsoft.ServiceFabric/clusters

Thank you @navba-MSFT, that works 👍
