### ISSUE TITLE
{afd} --custom-domain-name value in autogen content uses dots (incorrect) vs dash (correct)

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#27309]
### Describe the bug

This issue is being moved from https://github.com/MicrosoftDocs/azure-docs-cli/issues/3838.

### Azure CLI version being used

2.51.1

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/afd/custom-domain?view=azure-cli-latest#az-afd-custom-domain-create

### Description of the documentation error

Hello. I used the following command to create a custom domain in Azure Front Door:
```
az afd custom-domain create --certificate-type CustomerCertificate
                            --custom-domain-name dev.project.org.example.com
                            --host-name dev.project.org.example.com
                            --minimum-tls-version TLS12
                            --profile-name example-profile-name
                            --resource-group example-resource-group
                            --secret example-secret-name
```

but got an error:
```
Command group `afd` is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
(BadRequest) Property 'AfdDomainEntry.AfdDomainName' cannot be set to 'dev.project.org.example.com'.
Code: BadRequest
Message: Property 'AfdDomainEntry.AfdDomainName' cannot be set to 'dev.project.org.example.com'.
```

I obtained a REST API request from Azure Portal and according to it, the custom domain name should use `-` as delimiter, but there is no mention of this in the documentations.
<details>
<summary>REST API</summary>

```
curl 'https://management.azure.com/subscriptions/<subscription-id>/resourceGroups/<resource-group>/providers/Microsoft.Cdn/profiles/<profile>/customdomains/dev-project-org-example-com?api-version=2023-05-01' \
    -X PUT \
    --data-raw '{
                    "id": "/subscriptions/<subscription-id>/resourceGroups/<resource-group>/providers/Microsoft.Cdn/profiles/<profile>/customdomains/dev-project-org-example-com",
                    "name": "dev-project-org-example-com",
                    "properties": {
                        "hostName": "dev.project.org.example.com",
                        "tlsSettings": {
                            "certificateType": "CustomerCertificate",
                            "minimumTlsVersion": "TLS12",
                            "secret": { 
                                "id":"/subscriptions/<subscription-id>/resourceGroups/<resource-group>/providers/Microsoft.Cdn/profiles/<profile>/secrets/<secret-name>"
                            }
                        }
                    }
                }'
```

</details>

```
--custom-domain-name
Name of the custom domain.
```

After changing the delimiter for `--custom-domain-name`, I successfully created the domain.
```
az afd custom-domain create --certificate-type CustomerCertificate
                            --custom-domain-name dev-project-org-example-com
                            --host-name dev.project.org.example.com
                            --minimum-tls-version TLS12
                            --profile-name example-profile-name
                            --resource-group example-resource-group
                            --secret example-secret-name
```

<details>
<summary>az-afd response</summary>

```json
{
  "azureDnsZone": null,
  "deploymentStatus": "Succeeded",
  "domainValidationState": "Approved",
  "hostName": "dev.project.org.example.com",
  "name": "dev-project-org-example-com",
  "preValidatedCustomDomainResourceId": null,
  "profileName": null,
  "provisioningState": "Succeeded",
  "resourceGroup": "example-resource-group",
  "systemData": null,
  "tlsSettings": {
    "certificateType": "CustomerCertificate",
    "minimumTlsCertificate": "TLS12",
    "secret": {
      "id": "/subscriptions/<subscription-id>/resourceGroups/<resource-group>/providers/Microsoft.Cdn/profiles/<profile>/secrets/<secret-name>",
      "resourceGroup": "example-resource-group"
    }
  },
  "type": "Microsoft.Cdn/profiles/customdomains",
  "validationProperties": {
    "expirationDate": "0001-01-01T00:00:00.0000000",
    "validationToken": null
  }
}
```

</details>

### Related command

az afd custom-domain create

### Errors

Command group `afd` is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
(BadRequest) Property 'AfdDomainEntry.AfdDomainName' cannot be set to 'dev.project.org.example.com'.
Code: BadRequest
Message: Property 'AfdDomainEntry.AfdDomainName' cannot be set to 'dev.project.org.example.com'.

### Issue script & Debug output

After changing the delimiter for `--custom-domain-name`, I successfully created the domain.

az afd custom-domain create --certificate-type CustomerCertificate
                            --custom-domain-name `dev-project-org-example-com` not `dev.project.org.example.com`
                            --host-name dev.project.org.example.com
                            --minimum-tls-version TLS12
                            --profile-name example-profile-name
                            --resource-group example-resource-group
                            --secret example-secret-name

### Expected behavior

The custom domain name should use `-` as a delimiter, but there is no mention of this in the documentation.

### Environment Summary

2.51.1

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
Adding service team, since this is non-customer reported issue

**Comment by dbradish-microsoft** [comment]
@yonzhan , how can I tell if the service team is responding to this issue?

**Comment by yonzhan** [comment]
You can find service owner from above Bot "We are routing this to the appropriate team for follow-up. cc @cdnfdsuppgithub."

**Comment by progxaker** [comment]
Hello. Could someone please tell if there are any updates?

**Comment by dbradish-microsoft** [comment]
@cdnfdsuppgithub, Can you kindly provide an update on this GitHub issue?  Thank you.

**Comment by progxaker** [comment]
Any updates?

**Comment by progxaker** [comment]
Hello. Are there any updates?

**Comment by t-bzhan** [comment]
Hi @progxaker, @dbradish-microsoft. The custom domain name differs from the host name. The host name is a fully qualified domain name (FQDN), while the custom domain name serves as the resource name. It plays a crucial role in constructing the resource ID, such as: 

> /subscriptions/27cafca8-b9a4-4264-b399-45d0c9cca1ab/resourcegroups/bo-private/providers/Microsoft.Cdn/profiles/bzhan-test111/customdomains/bundletest-localdev-cdn-azure-cn

. This resource ID is used to locate resources in contexts where a resource reference is needed.

Importantly, there is no strict relationship between the custom domain name and the host name. You have the flexibility to use other unique identifiers. Replacing dots with hyphens in the host name is just one approach used by the portal (although it may cause conflict if the domain already contains hyphens).

Additionally, all resource names for Azure Front Door Premium/Standard (such as OriginGroup, Origin, Security Policy, Custom Domain, Rule/RuleSet, Secret, etc.) must adhere to the following restrictions:

- They can only contain hyphens, letters (a-z), and digits (0-9).
- The name must start with a letter or a digit.
- The length should be less than or equal to 260.

We’ll enhance the Swagger documentation to highlight this aspect.

**Comment by progxaker** [comment]
Hi @t-bzhan. Thanks for your response. The difference between custom domain and host names confused me, so it would be helpful to add more detail in the argument description.

> although it may cause conflict if the domain already contains hyphens
You're right, I hadn't thought of that.

> We’ll enhance the Swagger documentation to highlight this aspect.
If I understand correctly, this will also entail updating the Learn documentation, correct?

**Comment by progxaker** [comment]
Hello. Are there any updates?
