### ISSUE TITLE
cluster_subnet_type warning when creating SQL VM group via CLI

### ISSUE THREAD

**Issue by calvinhzy** [Azure/azure-cli#27300]
### Describe the bug

Trying to create SQL VM group with cluster_subnet_type parameter generates warnings:
![image](https://github.com/Azure/azure-cli/assets/17182306/14f0f074-3b22-428e-8f5f-81ab83a36e61)
Link to documentation: https://learn.microsoft.com/en-us/cli/azure/release-notes-azure-cli#december-06-2022
help commmand: az sql vm group create -h
![image](https://github.com/Azure/azure-cli/assets/17182306/4755c4d1-d6c5-4a62-a67d-33df68d8b7a2)
Why do we get this warning though cluster-subnet-type is supported parameter?

Raised by v-veppala@microsoft.com

### Related command

`az sql vm group create` `--cluster-subnet-type` 

### Issue script & Debug output

N/A

### Expected behavior

Should raise no warning

### Environment Summary

2.51.0 in cloudshell

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
