### ISSUE TITLE
az grafana api-key create does not work

### ISSUE THREAD

**Issue by thesse1** [Azure/azure-cli#27302]
### Describe the bug

az grafana api-key create does not work

### Related command

az grafana api-key create --key mykey --name azure-demo-01-grafana --resource-group azure-demo-01-monitoring-rg --role editor

### Errors

b'{"message": "If you enabled api key recently, please wait a few moments and refresh the page"}'
403 Client Error: Forbidden for url: https://azure-demo-01-grafana-hjg3gdauedd5g6fz.weu.grafana.azure.com/api/auth/keys

### Issue script & Debug output

az grafana api-key create --key mykey --name azure-demo-01-grafana --resource-group azure-demo-01-monitoring-rg --role editor --debug

cli.knack.cli: Command arguments: ['grafana', 'api-key', 'create', '--key', 'mykey', '--name', 'azure-demo-01-grafana', '--resource-group', 'azure-demo-01-monitoring-rg', '--role', 'editor', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0162D538>, <function OutputProducer.on_global_arguments at 0x0182B778>, <function CLIQuery.on_global_arguments at 0x018483D0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'grafana': ['azext_amg']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: amg                       0.159         9        45  C:\Users\THES\.azure\cliextensions\amg
cli.azure.cli.core: Total (1)                 0.159         9        45  
cli.azure.cli.core: Loaded 9 groups, 45 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : grafana api-key create
cli.azure.cli.core: Command table: grafana api-key create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03A0C5C8>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\THES\.azure\commands\2023-09-01.09-38-36.grafana_api-key_create.31724.log'.
az_command_data_logger: command args: grafana api-key create --key {} --name {} --resource-group {} --role {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03A355C8>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03A446A0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03A44730>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x0182B7C0>, <function CLIQuery.handle_query_parameter at 0x01848418>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03A446E8>]
az_command_data_logger: extension name: amg
az_command_data_logger: extension version: 1.2.7
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=DashboardManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\THES\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\THES\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/d9662eb9-ad98-4e74-a8a2-04ed5d544db6/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/d9662eb9-ad98-4e74-a8a2-04ed5d544db6/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/d9662eb9-ad98-4e74-a8a2-04ed5d544db6/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/d9662eb9-ad98-4e74-a8a2-04ed5d544db6/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/d9662eb9-ad98-4e74-a8a2-04ed5d544db6/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/d9662eb9-ad98-4e74-a8a2-04ed5d544db6/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/d9662eb9-ad98-4e74-a8a2-04ed5d544db6/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 4cfe45fd-58ca-4657-a704-9ef3188d2fef
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/309065ca-a060-4592-8096-b74694126b61/resourceGroups/azure-demo-01-monitoring-rg/providers/Microsoft.Dashboard/grafana/azure-demo-01-grafana?api-version=2022-10-01-preview'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '8f30c0a5-489a-11ee-a4f4-ac74b1298ffa'
cli.azure.cli.core.sdk.policies:     'CommandName': 'grafana api-key create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--key --name --resource-group --role --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.51.0 (MSI) azsdk-python-mgmt-dashboard/1.0.0b1 Python/3.10.10 (Windows-10-10.0.19045-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/309065ca-a060-4592-8096-b74694126b61/resourceGroups/azure-demo-01-monitoring-rg/providers/Microsoft.Dashboard/grafana/azure-demo-01-grafana?api-version=2022-10-01-preview HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'ETag': '"2301c10b-0000-0d00-0000-64f16a970000"'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-providerhub-traffic': 'True'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'aaaf6241-4281-4817-a574-1d02e6e33233'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'd310def8-e156-489a-9798-1b9963c07849'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'GERMANYWESTCENTRAL:20230901T073835Z:d310def8-e156-489a-9798-1b9963c07849'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Fri, 01 Sep 2023 07:38:34 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"id":"/subscriptions/309065ca-a060-4592-8096-b74694126b61/resourceGroups/azure-demo-01-monitoring-rg/providers/Microsoft.Dashboard/grafana/azure-demo-01-grafana","name":"azure-demo-01-grafana","type":"microsoft.dashboard/grafana","sku":{"name":"Standard"},"location":"westeurope","tags":{"environment":"azure-demo-01-monitoring","project":"azure-demo-01"},"systemData":{"createdBy":"3f802b61-e674-4b13-85ab-67db63c32d5a","createdByType":"Application","createdAt":"2023-09-01T04:35:03.0174314Z","lastModifiedBy":"3f802b61-e674-4b13-85ab-67db63c32d5a","lastModifiedByType":"Application","lastModifiedAt":"2023-09-01T04:35:03.0174314Z"},"identity":{"principalId":"3f8a30e8-b00c-4712-b40d-5a90b318aca1","tenantId":"d9662eb9-ad98-4e74-a8a2-04ed5d544db6","type":"SystemAssigned"},"properties":{"provisioningState":"Succeeded","grafanaVersion":"9.5.6","endpoint":"https://azure-demo-01-grafana-hjg3gdauedd5g6fz.weu.grafana.azure.com","zoneRedundancy":"Disabled","publicNetworkAccess":"Enabled","autoGeneratedDomainNameLabelScope":"TenantReuse","apiKey":"Disabled","deterministicOutboundIP":"Disabled","grafanaIntegrations":{"azureMonitorWorkspaceIntegrations":[{"azureMonitorWorkspaceResourceId":"/subscriptions/309065ca-a060-4592-8096-b74694126b61/resourcegroups/azure-demo-01-monitoring-rg/providers/microsoft.monitor/accounts/azure-demo-01-monitor-workspace"}]},"grafanaConfigurations":{"smtp":{"enabled":false}}}}
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/d9662eb9-ad98-4e74-a8a2-04ed5d544db6/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/d9662eb9-ad98-4e74-a8a2-04ed5d544db6/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/d9662eb9-ad98-4e74-a8a2-04ed5d544db6/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/d9662eb9-ad98-4e74-a8a2-04ed5d544db6/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/d9662eb9-ad98-4e74-a8a2-04ed5d544db6/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/d9662eb9-ad98-4e74-a8a2-04ed5d544db6/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/d9662eb9-ad98-4e74-a8a2-04ed5d544db6/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('ce34e7e5-485f-4d76-964f-b3d2b16d1e4f/.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 62a32a93-84cb-4cf5-bff0-bce3d8e7b70c
urllib3.connectionpool: Starting new HTTPS connection (1): azure-demo-01-grafana-hjg3gdauedd5g6fz.weu.grafana.azure.com:443
urllib3.connectionpool: https://azure-demo-01-grafana-hjg3gdauedd5g6fz.weu.grafana.azure.com:443 "POST /api/auth/keys HTTP/1.1" 403 None
cli.azext_amg.custom: b'{"message": "If you enabled api key recently, please wait a few moments and refresh the page"}'
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\THES\.azure\cliextensions\amg\azext_amg\custom.py", line 696, in create_api_key
    response = _send_request(cmd, resource_group_name, grafana_name, "post", "/api/auth/keys", data)
  File "C:\Users\THES\.azure\cliextensions\amg\azext_amg\custom.py", line 987, in _send_request
    response.raise_for_status()
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\requests/models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://azure-demo-01-grafana-hjg3gdauedd5g6fz.weu.grafana.azure.com/api/auth/keys

cli.azure.cli.core.azclierror: 403 Client Error: Forbidden for url: https://azure-demo-01-grafana-hjg3gdauedd5g6fz.weu.grafana.azure.com/api/auth/keys
az_command_data_logger: 403 Client Error: Forbidden for url: https://azure-demo-01-grafana-hjg3gdauedd5g6fz.weu.grafana.azure.com/api/auth/keys
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03A0C6E8>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.149 seconds (init: 0.332, invoke: 0.817)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3595 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\THES\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

It should create an API key

### Environment Summary

az --version

azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Extensions:
aks-preview                      0.5.154
amg                                1.2.7
azure-devops                      0.26.0
elastic                          1.0.0b1

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\THES\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by thesse1** [comment]
Hi @yonzhan Thanks for picking this up. Any news on the progress?

Thanks!

Best regards,
Thomas

**Comment by neopsyon** [comment]
Hello @thesse1 , did you enable API Keys in the Grafana resource configuration?

![Screenshot 2023-09-26 at 11 33 50](https://github.com/Azure/azure-cli/assets/47423607/1d18724c-b069-4ed5-9bfe-930b717de1bf)

**Comment by thesse1** [comment]
Hi @neopsyon,

Thanks a lot for the hint. Now it is working fine!

Best regards,
Thomas
