### ISSUE TITLE
az webapp vnet-integration add FAILS due to 'InvalidApiVersionParameter'

### ISSUE THREAD

**Issue by Matt-C22** [Azure/azure-cli#27305]
### Describe the bug

When trying to add the VNET integration to a webapp via the portal it fails with "An error has occurred". 

When trying to apply the same feature via CLI we get the actual error message. 

**INFO:** The WebApp and VNET are in different resource groups and different subscriptions.  Both subscriptions and RGs are in SwitzerlandNorth.

The command used is `az webapp vnet-integration add --resource-group $rg --name $app --vnet $vnet --subnet $sub `
where the `$vnet` and `$sub` are the resourceIDs of the VNET and subscription. The AzContext is set to the subscription where the webApp resides.

### Related command

az webapp vnet-integration add

### Errors

(InvalidApiVersionParameter) The api-version '2022-03-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
Code: InvalidApiVersionParameter
Message: The api-version '2022-03-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.

### Issue script & Debug output

--

### Expected behavior

Add vnet integration

### Environment Summary

azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
ml                                2.19.1
ssh                                2.0.1

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.9'
Extensions directory '/home/azureuser/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.14 (main, Feb  8 2023, 03:39:52)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by madsd** [comment]
Just for reference, it is documented here at the end of the section: https://learn.microsoft.com/en-us/azure/app-service/overview-vnet-integration#permissions
