### ISSUE TITLE
Issues with az artifacts universal download

### ISSUE THREAD

**Issue by amelendez100** [Azure/azure-cli#27307]
### Describe the bug

az artifacts universal download commands return FileNotFoundError

### Related command

The following commands return "FileNotFoundError": 

`az artifacts universal download --organization https://msazure.visualstudio.com/ --project="Antares" --scope project --feed antares-websites --name antares.appservicesecretsmanager --version * --path c:\tools\AppServiceSecretsManager`

`az artifacts universal download --organization https://msazure.visualstudio.com/ --project="Antares" --scope project --feed antares-websites --name antares.updatesiteextension --version * --path .\out\updatesiteextension`

### Errors

The command failed with an unexpected error. 
FileNotFoundError: [WinError 2] The system cannot find the file specified

### Issue script & Debug output

C:\Windows\System32>az artifacts universal download --organization https://msazure.visualstudio.com/ --project="Antares" --scope project --feed antares-websites --name antares.updatesiteextension --version * --path .\out\updatesiteextension --debug
cli.knack.cli: Command arguments: ['artifacts', 'universal', 'download', '--organization', 'https://msazure.visualstudio.com/', '--project=Antares', '--scope', 'project', '--feed', 'antares-websites', '--name', 'antares.updatesiteextension', '--version', '*', '--path', '.\\out\\updatesiteextension', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Enable VT mode.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x01A2A538>, <function OutputProducer.on_global_arguments at 0x01B2B778>, <function CLIQuery.on_global_arguments at 0x01C483D0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'artifacts': ['azext_devops']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: azure-devops              0.093        60       191  C:\Users\adrianm\.azure\cliextensions\azure-devops
cli.azure.cli.core: Total (1)                 0.093        60       191
cli.azure.cli.core: Loaded 60 groups, 191 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : artifacts universal download
cli.azure.cli.core: Command table: artifacts universal download
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03DDB5C8>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\adrianm\.azure\commands\2023-09-01.12-36-46.artifacts_universal_download.30388.log'.
az_command_data_logger: command args: artifacts universal download --organization {} --project={} --scope {} --feed {} --name {} --version {} --path {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03E03A90>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03E399B8>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03E39BB0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x01B2B7C0>, <function CLIQuery.handle_query_parameter at 0x01C48418>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03E39B68>, <function DevCommandsLoader.post_parse_args at 0x03EA2970>]
az_command_data_logger: extension name: azure-devops
az_command_data_logger: extension version: 0.25.0
cli.azext_devops.dev.common.artifacttool_updater: Checking for a new ArtifactTool
cli.azext_devops.dev.common.artifacttool_updater: Checking for ArtifactTool updates
cli.azext_devops.dev.common._credentials: Getting credential: azdevops-cli:https://msazure.visualstudio.com
cli.azext_devops.dev.common._credentials: Getting credential: azdevops-cli: default
cli.azure.cli.core: Current cloud config:
AzureCloud
cli.azext_devops.dev.common.services: trying to get token (temp) for tenant 72f988bf-86f1-41af-91ab-2d7cd011db47 and user adrianm@microsoft.com
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\adrianm\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\adrianm\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/kerberos', 'tenant_region_scope': 'WW', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('499b84ac-1321-427f-aa17-267ca6975798/.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 804497a5-c96d-44fd-9ecb-e98df60c2ae6
msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
cli.azext_devops.dev.common.telemetry: Azure devops telemetry enabled.
cli.azext_devops.dev.common.telemetry: Logging telemetry to azure devops server.
msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
azext_devops.devops_sdk._file_cache: Loading cache file: C:\Users\adrianm\.azure-devops\python-sdk\cache\options.json
azext_devops.devops_sdk._file_cache: attempting to read file C:\Users\adrianm\.azure-devops\python-sdk\cache\options.json as utf-8-sig
msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
azext_devops.devops_sdk.client: File cache hit for options on: https://msazure.visualstudio.com
azext_devops.devops_sdk._file_cache: Loading cache file: C:\Users\adrianm\.azure-devops\python-sdk\cache\resources.json
azext_devops.devops_sdk.client: Route template: _apis/{area}/{resource}
azext_devops.devops_sdk._file_cache: attempting to read file C:\Users\adrianm\.azure-devops\python-sdk\cache\resources.json as utf-8-sig
azext_devops.devops_sdk.client: Api version '5.0-preview.1'
azext_devops.devops_sdk.connection: File cache hit for resources on: https://msazure.visualstudio.com
azext_devops.devops_sdk.client: POST https://msazure.visualstudio.com/_apis/CustomerIntelligence/Events
msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
cli.azext_devops.dev.common.artifacttool_updater: Looking up current version of ArtifactTool...
azext_devops.devops_sdk.client: Request content: [{'area': 'AzureDevopsCli', 'feature': 'artifacts', 'properties': {'Command': 'universal download', 'Args': 'feed name version path scope organization project', 'ShellType': 'cmd', 'IsInteractive': 'True', 'OutputType': 'json', 'OrgPresentInCommand': True, 'ProjectPresentInCommand': True, 'RepoPresentInCommand': False}}]
msrest.universal_http: Configuring redirects: allow=True, max=30
msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
azext_devops.devops_sdk.client: File cache hit for options on: https://msazure.vsblob.visualstudio.com
msrest.universal_http: Configuring proxies: ''
azext_devops.devops_sdk.client: Route template: _apis/{area}/{toolName}/{resource}
msrest.universal_http: Evaluate proxies against ENV settings: True
azext_devops.devops_sdk.client: Api version '5.0-preview'
azext_devops.devops_sdk.client: GET https://msazure.vsblob.visualstudio.com/_apis/clienttools/ArtifactTool/release?osName=Windows&arch=AMD64
urllib3.connectionpool: Starting new HTTPS connection (1): msazure.visualstudio.com:443
azext_devops.devops_sdk.client: Request content: None
msrest.universal_http: Configuring redirects: allow=True, max=30
msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http: Configuring proxies: ''
msrest.universal_http: Evaluate proxies against ENV settings: True
urllib3.connectionpool: Starting new HTTPS connection (1): msazure.vsblob.visualstudio.com:443
urllib3.connectionpool: https://msazure.visualstudio.com:443 "POST /_apis/CustomerIntelligence/Events HTTP/1.1" 204 0
urllib3.connectionpool: https://msazure.vsblob.visualstudio.com:443 "GET /_apis/clienttools/ArtifactTool/release?osName=Windows&arch=AMD64 HTTP/1.1" 200 444
azext_devops.devops_sdk.client: Response content: b'{"name":"ArtifactTool","rid":"win10-x64","version":"0.2.290","uri":"https://vsblobprodeussu2shard1.vsblob.vsassets.io/artifacttool/artifacttool-win10-x64-Release_0.2.290.zip?sv=2019-07-07&sr=b&sig=UvLcSITnbB707oVGkNyc4xK1suVsF3JFmLcbgyqUMMM%3D&spr=https&se=2023-09-01T20%3A36%3A47Z&sp=r&P1=1693600307&P2=11&P3=2&P4=rTE9B1qO%2fLfzu3mDWAonXvKi0qoFD4%2bxrWnotSc%2bfHY%3d"}'
cli.azext_devops.dev.common.artifacttool_updater: Checking if we already have ArtifactTool release 'ArtifactTool_win10-x64_0.2.290'
cli.azext_devops.dev.common.artifacttool_updater: Not updating ArtifactTool because the current release already exists at 'C:\Users\adrianm\.azure\azuredevops\cli\tools\artifacttool\ArtifactTool_win10-x64_0.2.290'
cli.azext_devops.dev.common._credentials: Getting credential: azdevops-cli:https://msazure.visualstudio.com
cli.azext_devops.dev.common._credentials: Getting credential: azdevops-cli: default
cli.azure.cli.core: Current cloud config:
AzureCloud
cli.azext_devops.dev.common.services: trying to get token (temp) for tenant 72f988bf-86f1-41af-91ab-2d7cd011db47 and user adrianm@microsoft.com
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/kerberos', 'tenant_region_scope': 'WW', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('499b84ac-1321-427f-aa17-267ca6975798/.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 906b1137-fbdb-41ec-9c8a-53a8251b926b
cli.azext_devops.dev.common.external_tool: Running external command: C:\Users\adrianm\.azure\azuredevops\cli\tools\artifacttool\ArtifactTool_win10-x64_0.2.290\artifacttool universal download --service https://msazure.visualstudio.com/ --patvar AZURE_DEVOPS_EXT_ARTIFACTTOOL_PATVAR --feed antares-websites --package-name antares.updatesiteextension --package-version * --path .\out\updatesiteextension --project Antares
cli.azext_devops.dev.common.exception_handler: handling generic error
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "C:\Users\adrianm\.azure\cliextensions\azure-devops\azext_devops\dev\common\exception_handler.py", line 31, in azure_devops_exception_handler
    reraise(*sys.exc_info())
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\six.py", line 719, in reraise
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\adrianm\.azure\cliextensions\azure-devops\azext_devops\dev\artifacts\universal.py", line 98, in download_package
    return artifact_tool.download_universal(organization, project, feed, name, version, path, file_filter)
  File "C:\Users\adrianm\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool.py", line 42, in download_universal
    return self.run_artifacttool(organization, args, "Downloading")
  File "C:\Users\adrianm\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool.py", line 67, in run_artifacttool
    proc = self._tool_invoker.run(command_args, new_env, initial_progress_message, _process_stderr)
  File "C:\Users\adrianm\.azure\cliextensions\azure-devops\azext_devops\dev\common\external_tool.py", line 74, in run
    self.start(command_args, env)
  File "C:\Users\adrianm\.azure\cliextensions\azure-devops\azext_devops\dev\common\external_tool.py", line 33, in start
    self._proc = subprocess.Popen(
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1440, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "C:\Users\adrianm\.azure\cliextensions\azure-devops\azext_devops\dev\common\exception_handler.py", line 31, in azure_devops_exception_handler
    reraise(*sys.exc_info())
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\six.py", line 719, in reraise
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\adrianm\.azure\cliextensions\azure-devops\azext_devops\dev\artifacts\universal.py", line 98, in download_package
    return artifact_tool.download_universal(organization, project, feed, name, version, path, file_filter)
  File "C:\Users\adrianm\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool.py", line 42, in download_universal
    return self.run_artifacttool(organization, args, "Downloading")
  File "C:\Users\adrianm\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool.py", line 67, in run_artifacttool
    proc = self._tool_invoker.run(command_args, new_env, initial_progress_message, _process_stderr)
  File "C:\Users\adrianm\.azure\cliextensions\azure-devops\azext_devops\dev\common\external_tool.py", line 74, in run
    self.start(command_args, env)
  File "C:\Users\adrianm\.azure\cliextensions\azure-devops\azext_devops\dev\common\external_tool.py", line 33, in start
    self._proc = subprocess.Popen(
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1440, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
az_command_data_logger: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "C:\Users\adrianm\.azure\cliextensions\azure-devops\azext_devops\dev\common\exception_handler.py", line 31, in azure_devops_exception_handler
    reraise(*sys.exc_info())
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\six.py", line 719, in reraise
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\adrianm\.azure\cliextensions\azure-devops\azext_devops\dev\artifacts\universal.py", line 98, in download_package
    return artifact_tool.download_universal(organization, project, feed, name, version, path, file_filter)
  File "C:\Users\adrianm\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool.py", line 42, in download_universal
    return self.run_artifacttool(organization, args, "Downloading")
  File "C:\Users\adrianm\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool.py", line 67, in run_artifacttool
    proc = self._tool_invoker.run(command_args, new_env, initial_progress_message, _process_stderr)
  File "C:\Users\adrianm\.azure\cliextensions\azure-devops\azext_devops\dev\common\external_tool.py", line 74, in run
    self.start(command_args, env)
  File "C:\Users\adrianm\.azure\cliextensions\azure-devops\azext_devops\dev\common\external_tool.py", line 33, in start
    self._proc = subprocess.Popen(
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1440, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03DDB6E8>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.499 seconds (init: 0.411, invoke: 1.088)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 7296 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\adrianm\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

Download of requested artifcats, plus the following output

C:\Windows\System32>az artifacts universal download --organization https://msazure.visualstudio.com/ --project="Antares" --scope project --feed antares-websites --name antares.updatesiteextension --version * --path .\out\updatesiteextension
{
  "Description": "Antares UpdateSiteExtension",
  "ManifestId": "2D0839FFA2871599C10A11BA19E8DE5EC3A99C74E55DD0553ADD3C4BD9BD10D601",
  "PackageSize": 60703830,
  "SuperRootId": "6226CEB54FFF108D79F491F690636E2F0F127B42B477316316F1A2DA081CC0E502",
  "Version": "102.0.171"
}

### Environment Summary

azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Extensions:
azure-devops                      0.25.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\adrianm\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by amelendez100** [comment]
This is not the same issue

**Comment by navba-MSFT** [comment]
@amelendez100 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you please update your `devops `extension and then test again ?

> **az extension update -n azure-devops**

Awaiting your reply.

**Comment by navba-MSFT** [comment]
@amelendez100 The action is pending on you to try the above plan. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by borjamunozf** [comment]
I have the same issue. The command I was using stopped working without any change.

Please, any help?
