### ISSUE TITLE
Decryption failed error during execution of any program 

### ISSUE THREAD

**Issue by glxymesh** [Azure/azure-cli#27317]
### Describe the bug

This bug is occurred during the login and running of az command through cli during the first time installation and login everything has worked perfectly but now i the below error kept occurring during the execution of the command i tried which is below.

### Related command

```az login```

```az vm start --name myvm --resource-group group-name```

### Errors

Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError

### Issue script & Debug output

cli.knack.cli: Command arguments: ['login', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Enable VT mode.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x000001B1E8481240>, <function OutputProducer.on_global_arguments at 0x000001B1E85CFEB0>, <function CLIQuery.on_global_arguments at 0x000001B1E8821240>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'login': ['azure.cli.command_modules.profile']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: profile                   0.004         2         9
cli.azure.cli.core: Total (1)                 0.004         2         9
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 2 groups, 9 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : login
cli.azure.cli.core: Command table: login
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x000001B1EAEE4310>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\username\.azure\commands\2023-09-05.02-11-26.login.3052.log'.
az_command_data_logger: command args: login --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x000001B1EAEE6F80>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x000001B1EAF2CF70>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x000001B1EAF2D090>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x000001B1E85CFF40>, <function CLIQuery.handle_query_parameter at 0x000001B1E88212D0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x000001B1EAF2D000>]
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\username\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\username\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/organizations/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/{tenantid}/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/organizations/kerberos', 'tenant_region_scope': None, 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? True
msal.application: Falls back to broker._signin_interactively()
cli.azure.cli.core.auth.identity: Please select the account you want to log in with.
msal.broker: [MSAL:0001]        INFO    SetCorrelationId:220    Set correlation ID: d1192201-e1df-4f62-a7cc-6d612683d7a1
msal.broker: [MSAL:0001]        INFO    ExecuteInteractiveRequest:738   The original authority is 'https://login.microsoftonline.com/organizations'
msal.broker: [MSAL:0001]        WARNING TryNormalizeRealm:2219  No HomeAccountId provided to normalize the realm
msal.broker: [MSAL:0001]        INFO    ExecuteInteractiveRequest:749   The normalized realm is ''
msal.broker: [MSAL:0001]        INFO    ModifyAndValidateAuthParameters:182     Additional query parameter added successfully. Key: '(pii)' Value: '(pii)'
msal.broker: [MSAL:0001]        INFO    ModifyAndValidateAuthParameters:182     Additional query parameter added successfully. Key: '(pii)' Value: '(pii)'
msal.broker: [MSAL:0001]        INFO    ModifyAndValidateAuthParameters:199     Authority Realm: organizations
msal.broker: [MSAL:0002]        WARNING TryReadUniversalStorage:638     Attempted to read cache with a non-normalized realm, access token and ID token reads will fail
msal.broker: [MSAL:0002]        WARNING ReadAccountById:225     Account id is empty - account not found
msal.broker: [MSAL:0003]        INFO    SetCorrelationId:220    Set correlation ID: d1192201-e1df-4f62-a7cc-6d612683d7a1
msal.broker: [MSAL:0002]        INFO    SetCanonicalRealm:1039  Normalize realm to: 'f8cdef31-a31e-4b4a-93e4-5f571e91255a'
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:332    Printing Telemetry for Correlation ID: d1192201-e1df-4f62-a7cc-6d612683d7a1
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: start_time, Value: 2023-09-05T02:11:26.000Z
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: api_name, Value: SignInInteractively
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: was_request_throttled, Value: false
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: authority_type, Value: MSA
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: access_token_expiry_time, Value: 2023-09-05T03:35:47.000Z
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: msal_version, Value: 1.1.0+local
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: client_id, Value: 04b07795-8ddb-461a-bbee-02f9e1bf7b46
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: wam_cached_time_diff, Value: 300
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: correlation_id, Value: d1192201-e1df-4f62-a7cc-6d612683d7a1
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: stop_time, Value: 2023-09-05T02:11:31.000Z
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: msalruntime_version, Value: 0.13.9
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: original_authority, Value: https://login.microsoftonline.com/organizations
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: request_eligible_for_broker, Value: true
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: broker_app_used, Value: true
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: additional_query_parameters_count, Value: 2
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: read_token_last_error, Value: missing required parameter
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: ui_event_count, Value: 1
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: wam_telemetry, Value: {"x_ms_clitelem":"1,0,0,,","ui_visible":false,"tenant_id":"f8cdef31-a31e-4b4a-93e4-5f571e91255a","scope":"https://management.core.windows.net//.default offline_access openid profile","redirect_uri":"ms-appx-web://Microsoft.AAD.BrokerPlugin/04b07795-8ddb-461a-bbee-02f9e1bf7b46","provider_id":"https://login.windows.net","idp":"live.com","http_status":200,"http_event_count":1,"device_join":"not_joined","correlation_id":"{d1192201-e1df-4f62-a7cc-6d612683d7a1}","client_id":"04b07795-8ddb-461a-bbee-02f9e1bf7b46","cache_event_count":0,"broker_version":"10.0.20348.1850","authority":"https://login.microsoftonline.com/organizations","api_error_code":0,"account_join_on_start":"not_joined","account_join_on_end":"not_joined","silent_code":0,"silent_bi_sub_code":0,"silent_message":"","silent_mats":{"x_ms_clitelem":"1,0,0,,","ui_visible":false,"tenant_id":"f8cdef31-a31e-4b4a-93e4-5f571e91255a","scope":"https://management.core.windows.net//.default offline_access openid profile","redirect_uri":"ms-appx-web://Microsoft.AAD.BrokerPlugin/04b07795-8ddb-461a-bbee-02f9e1bf7b46","provider_id":"https://login.windows.net","idp":"live.com","http_status":200,"http_event_count":1,"device_join":"not_joined","correlation_id":"{d1192201-e1df-4f62-a7cc-6d612683d7a1}","client_id":"04b07795-8ddb-461a-bbee-02f9e1bf7b46","cache_event_count":0,"broker_version":"10.0.20348.1850","authority":"https://login.microsoftonline.com/organizations","api_error_code":0,"account_join_on_start":"not_joined","account_join_on_end":"not_joined"},"silent_status":0,"is_cached":0}
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: transfer_token_request, Value: succeeded
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: transfer_token_added, Value: true
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: tenant_id, Value: f8cdef31-a31e-4b4a-93e4-5f571e91255a
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: normalized_realm, Value: f8cdef31-a31e-4b4a-93e4-5f571e91255a
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: write_token, Value: AT|ID
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: is_successful, Value: true
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: authorization_type, Value: CompleteBrokerResult
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:340    Key: request_duration, Value: 4910
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:345    Printing Execution Flow:
msal.broker: [MSAL:0002]        INFO    LogTelemetryData:353    {"t":"646u1","tid":1,"ts":0,"l":2},{"t":"8dqim","tid":2,"ts":7,"l":2},{"t":"8dqkl","tid":1,"ts":9,"l":2,"a":9,"ie":0},{"t":"54uxd","tid":1,"ts":13,"l":2},{"t":"4wqnh","tid":3,"ts":3444,"l":2},{"t":"8dqmh","tid":3,"ts":3464,"l":2},{"t":"8dqme","tid":3,"ts":3464,"l":2},{"t":"4wqm9","tid":3,"ts":3464,"l":2},{"t":"8dql1","tid":3,"ts":4118,"l":2},{"t":"6myt3","tid":3,"ts":4118,"l":2},{"t":"6m026","tid":3,"ts":4118,"l":2},{"t":"6m028","tid":3,"ts":4118,"l":2},{"t":"8dqmj","tid":3,"ts":4118,"l":2},{"t":"4wqm9","tid":3,"ts":4119,"l":2},{"t":"8dql1","tid":3,"ts":4895,"l":2},{"t":"8dqkn","tid":3,"ts":4896,"l":2,"a":5,"ie":1},{"t":"8dqko","tid":3,"ts":4896,"l":2,"a":9,"ie":1},{"t":"8dqkr","tid":3,"ts":4896,"l":2},{"t":"8b2yn","tid":2,"ts":4896,"l":2},{"t":"8dqlh","tid":2,"ts":4896,"l":2},{"t":"8dqli","tid":2,"ts":4896,"l":2},{"t":"8dqln","tid":2,"ts":4896,"l":2},{"t":"8dqih","tid":2,"ts":4896,"l":2},{"t":"5i16b","tid":2,"ts":4896,"l":2},{"t":"7e61d","tid":2,"ts":4896,"l":2,"a":2,"ie":0},{"t":"7e61e","tid":2,"ts":4899,"l":2,"a":2,"ie":1},{"t":"7e60p","tid":2,"ts":4899,"l":2,"a":3,"ie":0},{"t":"7e60q","tid":2,"ts":4902,"l":2,"a":3,"ie":1},{"t":"7e60v","tid":2,"ts":4902,"l":2,"a":2,"ie":0},{"t":"7e60w","tid":2,"ts":4903,"l":2,"a":2,"ie":1},{"t":"7e60r","tid":2,"ts":4903,"l":2,"a":3,"ie":0},{"t":"6ou2y","tid":2,"ts":4906,"l":2,"a":3,"ie":1},{"t":"8dqi6","tid":2,"ts":4906,"l":2},{"t":"7e60t","tid":2,"ts":4906,"l":2,"a":3,"ie":0},{"t":"7e60u","tid":2,"ts":4907,"l":2,"a":3,"ie":1},{"t":"6xuag","tid":2,"ts":4907,"l":2},{"t":"4waym","tid":2,"ts":4907,"l":2}
msal.broker: [MSAL:0002]        INFO    operator ():221 Attempting to hydrate properties in the home account after a guest SignIn
msal.broker: [MSAL:0002]        INFO    SetCorrelationId:220    Set correlation ID: d1192201-e1df-4f62-a7cc-6d612683d7a1
msal.token_cache: event={
    "_account_id": "00000000-0000-0000-8a26-664afcf91464.9188040d-6c67-4c5b-b112-36a304b66dad.f8cdef31-a31e-4b4a-93e4-5f571e91255a",
    "client_id": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
    "data": {},
    "response": {
        "_account_id": "00000000-0000-0000-8a26-664afcf91464.9188040d-6c67-4c5b-b112-36a304b66dad.f8cdef31-a31e-4b4a-93e4-5f571e91255a",
        "_msalruntime_telemetry": {
            "access_token_expiry_time": "2023-09-05T03:35:47.000Z",
            "additional_query_parameters_count": "2",
            "api_name": "SignInInteractively",
            "authority_type": "MSA",
            "authorization_type": "CompleteBrokerResult",
            "broker_app_used": "true",
            "client_id": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
            "correlation_id": "d1192201-e1df-4f62-a7cc-6d612683d7a1",
            "is_successful": "true",
            "msal_version": "1.1.0+local",
            "msalruntime_version": "0.13.9",
            "normalized_realm": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
            "original_authority": "https://login.microsoftonline.com/organizations",
            "read_token_last_error": "missing required parameter",
            "request_duration": "4910",
            "request_eligible_for_broker": "true",
            "start_time": "2023-09-05T02:11:26.000Z",
            "stop_time": "2023-09-05T02:11:31.000Z",
            "tenant_id": "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
            "transfer_token_added": "true",
            "transfer_token_request": "succeeded",
            "ui_event_count": "1",
            "wam_cached_time_diff": "300",
            "was_request_throttled": "false",
            "write_token": "AT|ID"
        },
        "access_token": "********",
        "client_info": "eyJ1aWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtOGEyNi02NjRhZmNmOTE0NjQiLCJ1dGlkIjoiOTE4ODA0MGQtNmM2Ny00YzViLWIxMTItMzZhMzA0YjY2ZGFkIn0",
        "expires_in": 5056,
        "id_token": "********",
        "id_token_claims": "********",
        "scope": "https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default",
        "token_type": "Bearer"
    },
    "scope": [
        "https://management.core.windows.net//user_impersonation",
        "https://management.core.windows.net//.default"
    ],
    "token_endpoint": "https://login.microsoftonline.com/organizations/oauth2/v2.0/token"
}
msal.broker: [MSAL:0002]        INFO    EnqueueBackgroundRequest:677    The original authority is 'https://login.microsoftonline.com/common'
msal.broker: [MSAL:0002]        INFO    ModifyAndValidateAuthParameters:182     Additional query parameter added successfully. Key: '(pii)' Value: '(pii)'
msal.broker: [MSAL:0002]        INFO    ModifyAndValidateAuthParameters:182     Additional query parameter added successfully. Key: '(pii)' Value: '(pii)'
msal.broker: [MSAL:0002]        INFO    ModifyAndValidateAuthParameters:199     Authority Realm: common
msal.broker: [MSAL:0004]        INFO    SetCanonicalRealm:1039  Normalize realm to: '9188040d-6c67-4c5b-b112-36a304b66dad'
msal.broker: [MSAL:0004]        WARNING StorageTokenResponse:14 No credentials found in the cache
msal.broker: [MSAL:0004]        WARNING TryReadUniversalStorage:747     No id token found in the cache
msal.broker: [MSAL:0004]        WARNING TryReadUniversalStorage:766     No access token found in the cache
msal.broker: [MSAL:0004]        ERROR   ErrorInternalImpl:134   Created an error: 9u8f4, StatusInternal::InteractionRequired, InternalEvent::None, Error Code 0, Context 'No refresh tokens available in the cache, but an account was found on disk. RT likely deleted.'
msal.broker: [MSAL:0004]        WARNING GetPlatformPropertiesFromStorage:1913   No account found in cache.
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/persistence.py", line 236, in load
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/windows.py", line 123, in unprotect
OSError: [WinError -2146893813] Key not valid for use in specified state.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 139, in login
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 154, in login
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 153, in login_with_auth_code
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1846, in acquire_token_interactive
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1968, in _acquire_token_interactive_via_broker
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1434, in _process_broker_response
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 317, in add
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 128, in add
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/token_cache.py", line 192, in __add
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/token_cache.py", line 64, in modify
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/token_cache.py", line 55, in _reload_if_necessary
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal_extensions/persistence.py", line 238, in load
msal_extensions.persistence.PersistenceDecryptionError: [Errno -2146893813] Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError: 'C:\\Users\\username\\.azure\\msal_token_cache.bin'

cli.azure.cli.core.azclierror: Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError
az_command_data_logger: Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError
Please report to us via Github: https://github.com/Azure/azure-cli/issues/20231
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x000001B1EAEE4550>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 5.700 seconds (init: 0.395, invoke: 5.304)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3426 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\username\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

I should have been logged in on to the cli and command should have start the vm on cloud.

### Environment Summary

azure-cli                         2.51.0

core                              2.51.0
telemetry                          1.1.0

Extensions:
interactive                        0.5.3

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\abhishek\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
