### ISSUE TITLE
az snapshot create and az disk create CLI commands to not pass V1 as default value

### ISSUE THREAD

**Issue by AdamZLi** [Azure/azure-cli#27323]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az snapshot create
az disk create

### Resource Provider

CLI

### Description of Feature or Work Requested

**Describe the problem**
Currently, when running over an OS disk, both commands assume by default Gen1 snapshot/disks, even if the original disk/snapshot is Gen2. The customer has to specify the parameter “--hyper-v-generation V2” for any disk or snapshot created from a Gen2 source, otherwise it will create a V1 (Gen1) disk/snapshot. 

This will have the consequence of generating Gen1 disks/snapshots that are not bootable when used to create a VM, because internally a Gen2 disk is GPT/UEFI formatted; it will also prevent a Gen2 VM from being attached or created from that disk/snapshot, as it is marked as V1(Gen1).

The azure CLI spec specifies Gen 1 as a default value, which is leading to this incorrect behavior: [az snapshot | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fcli%2Fazure%2Fsnapshot%3Fview%3Dazure-cli-latest&data=05%7C01%7Csarahrahman%40microsoft.com%7C209e1aabb398444dbde908dba7815a31%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638287946240679766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4emvW2aPU4%2BtqU2%2BCt9x%2BF%2B7rJAYEIxNeDnigaS4r4I%3D&reserved=0).

**Describe the solution**
Let the “az snapshot create” and “az disk create” determine the correct disk/snapshot Hyper-V generation from the original disk/snapshot, instead of always defaulting to V1. The ask is to not pass V1 as a default value for the hyper-v-generation parameter for this CLI command. No default value should be used. 

When no default value is passed, diskRP will correctly usethe hyperVGeneration property of the source resource. An example of correct behavior would be creating a snapshot from a Gen 1 disk and no hyperVGen parameter will lead to the snapshot having the Gen1 hyperVGen property. (I.E. az snapshot create -g TESTRG -n TestSnapshot --source Win2019DCG2_OsDisk_WithGen1  will create a snapshot with Gen1.)

### Minimum API Version Required

N/A

### Swagger PR link / SDK link

[Commit 4d66a8f2: Merged PR 1126070: DiskRP Gen2 VM Support... - Repos (azure.com)](https://dev.azure.com/msazure/One/_git/Compute-CPlat-Disks/commit/4d66a8f2fb56803e80260f612d4d79c912ada14a?refName=refs/heads/develop&path=/src/Disk/Dev/DiskManager/GoalSeeking/AvailabilitySetPipelineInMemoryState.cs&_a=compare)

### Target Date

2023-12-31

### PM Contact

adli@microsoft.com

### Engineer Contact

sarahrahman@microsoft.com

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yanzhudd** [comment]
Hi @AdamZLi, since currently `--hyper-v-generation` setting to `V1` is be default in CLI, is it possible to bring breaking change to users if we make this change?

**Comment by sarahrahman34** [comment]
@yanzhudd This will not cause breaking changes for the following reasons:

**1) Create Snapshot does not require hyperVGen to be specified.** I.E. take a look at this request to create a snapshot. No hyperVGen is passed in the properties body for Invoking action Snapshots.ResourceOperation.PUT()

DiskManagerContextActivityEvent
| where activityId == "be062fb5-47b7-444c-bbc8-49f97087efd2"
| where PreciseTimeStamp between (datetime(2023-06-21 01:15:30.580)..20hr)

Invoking action Snapshots.ResourceOperation.PUT(subscriptionId=f0c630e0-2995-4853-b056-0b3c09cb673f, resourceGroupName=rgEAcan-otds-rraj, resourceName=snapshot-23480857-20d5-4eef-adbf-301ab855fbd7, snapshotDescription={
  "location": "eastasia",
  "tags": {},
  "properties": {
    "creationData": {
      "createOption": "Copy",
      "sourceResourceId": "/subscriptions/f0c630e0-2995-4853-b056-0b3c09cb673f/resourceGroups/mc_rgeacan-rraj_k8seacan-rraj_eastasia/providers/Microsoft.Compute/disks/pvc-c88ae48d-f40c-4d67-822d-d6d9e53af297"
    },
    "incremental": true
  }
})

**2) In both portal and Powershell, there is no default value being passed to diskRP either.** Here is an example log of creating snapshot "testHyperVGen" via portal. There is no hyperVGen in the body as well:


DiskManagerContextActivityEvent
| where activityId == "608d66e0-840e-4a50-8b0b-d9c275433019"
| where PreciseTimeStamp between (datetime(2023-09-06 19:01:10.792) .. 10min)

Invoking action Snapshots.ResourceOperation.PUT(subscriptionId=7f2086a0-45d9-4086-8df0-1467dd245ef0, resourceGroupName=diskrptestappbi, resourceName=testHyperVGen, snapshotDescription={
  "location": "southcentralusstg",
  "tags": {},
  "sku": {
    "name": "Standard_LRS"
  },
  "properties": {
    "creationData": {
      "createOption": "Copy",
      "sourceResourceId": "/subscriptions/7f2086a0-45d9-4086-8df0-1467dd245ef0/resourceGroups/DISKRPTESTAPPBI/providers/Microsoft.Compute/disks/vmarm1eoiglcak8_osDisk"
    },
    "incremental": false,
    "networkAccessPolicy": "AllowAll",
    "publicNetworkAccess": "Enabled",
    "dataAccessAuthMode": "None"
  }
})

**Comment by sarahrahman34** [comment]
HI @zhoxing-ms and @yanzhudd, any update on this?

**Comment by yanzhudd** [comment]
If it goes well, we will release the feature in this sprint (2023-11-15).

**Comment by Jing-song** [comment]
Hi @AdamZLi, do we need to use the `--source` name to decide whether to use V1 or V2?

**Comment by sarahrahman34** [comment]
Hi @Jing-song

Yes source will be used to decide V1 or V2 for hyperVGen.

We should follow the following suggestion:

For best user experience I think:
1.	Both commands should default to the source Gen, not Gen1;
2.	If the above is not possible, a warning should be issued to the user if a source Gen/destination Gen mismatch is detected or if it is not possible to determine the source Gen;
3.	If the users forces the Gen using the parameter “--hyper-v-generation V1|V2”, a warning should be sent to the user **if the source Gen does not match the destination Gen,** or if it is not possible to determine the source Gen.
