### ISSUE TITLE
azureOrigin diplayed as NULL for the command az afd origin show

### ISSUE THREAD

**Issue by GonzaloMurilloTello** [Azure/azure-cli#27320]
### Describe the bug

A command like

az afd origin show --origin-group-name myorigingroup --origin-name xxxx-profile-name yyy --resource-group zzz --subscription kkk

Returns

azureOrigin:null

Even when the origin is not null
 

### Related command

az afd origin show 

### Errors

none, just lack of information

### Issue script & Debug output

az afd origin show --origin-group-name xxx --origin-name yyy -profile-name supercdn ZZZ --resource-group kkk --subscription xxxx

### Expected behavior

The expectation is that the command az afd origin show displays in the field azureOrigin, the origin, rather than null

### Environment Summary

azure-cli                         2.49.0 *

 

core                              2.49.0 *

telemetry                          1.0.8 *

 

Extensions:

aks-preview                      0.5.144

 

Dependencies:

msal                              1.20.0

azure-mgmt-resource               22.0.0

 

Python location '/opt/az/bin/python3'

Extensions directory '/home/cspx_a_tkratzt/.azure/cliextensions'

 

Python (Linux) 3.10.10 (main, May 19 2023, 08:20:31) [GCC 11.3.0]

### Additional context

Is the return of the parameter azureOrigin, in the command 

az afd origin show 

Still not implemented?

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@GonzaloMurilloTello Thanks for reaching out to us and reporting this issue. Please share an update after testing with recent AzCLI version.

**Comment by GonzaloMurilloTello** [comment]
Hello, this is the output
az –version
{
  "azure-cli": "2.52.0",
  "azure-cli-core": "2.52.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "aks-preview": "0.5.156"
  }
}

Command group 'afd' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus

{

  **"azureOrigin": null,**
  "deploymentStatus": "NotStarted",
  "enabledState": "Enabled",
  "enforceCertificateNameCheck": true,
  "hostName": "",
  "httpPort": 80,
  "httpsPort": 443,
  "id": "",
  "name": "REMOVED-DUE-TO-PRIVACY",

  "originGroupName": "REMOVED-DUE-TO-PRIVACY",

  "originHostHeader": "",

  "priority": 2,

  "provisioningState": "Succeeded",

  "resourceGroup": "REMOVED-DUE-TO-PRIVACY",

  "sharedPrivateLinkResource": {

    "groupId": "web",

   "privateLink": {

      "id": "",

      "resourceGroup": "REMOVED-DUE-TO-PRIVACY"

    },

    "privateLinkLocation": "westeurope",

    "requestMessage": "message",

    "status": null

  },

  "systemData": null,

  "type": "Microsoft.Cdn/profiles/origingroups/origins",

  "weight": 1000

}


As you can see AzureOrigin = NULL

Can you confirm if the AzureOrigin property is returned in this command that it is in preview?

Thanks

**Comment by navba-MSFT** [comment]
@GonzaloMurilloTello Thanks for your reply. Could you please click on the [**TryIt option**](https://learn.microsoft.com/en-us/rest/api/frontdoor/azurefrontdoorstandardpremium/afd-origin-groups/list-by-profile#afdorigingrouplistresult) and try to invoke the REST API directly and check if that lists. If it doesn't then the CLI also will not show it.

**Comment by GonzaloMurilloTello** [comment]
The only thing that we get is this:

{

  "id": "/subscriptions/XXXX/resourcegroups/XXXX/providers/Microsoft.Cdn/profiles/XXXX/origingroups/XXXX/origins/XXXX",

 "type": "Microsoft.Cdn/profiles/origingroups/origins",

  "name": "XXXX",

  "properties": {

    "originGroupName": "XXXX",

    "hostName": "XXXX",

    "httpPort": 80,

    "httpsPort": 443,

    "originHostHeader": "XXXX ",

    "priority": 2,

    "weight": 1000,

    "enabledState": "Enabled",

    "sharedPrivateLinkResource": {

      "privateLink": {

        "id": "/subscriptions/XXXX/resourceGroups/XXXX/providers/Microsoft.Storage/storageAccounts/XXXX"

      },

      "groupId": "web",

      "privateLinkLocation": "westeurope",

      "status": null,

     "requestMessage": "message"

    },

    "enforceCertificateNameCheck": true,

    "provisioningState": "Succeeded",

    "deploymentStatus": "NotStarted"

  }

}

As you can see we do not see the field "azureOrigin": null

Does this mean that is not supported at the API level?

Any way to know when it would be available?

Thanks

**Comment by navba-MSFT** [comment]
@GonzaloMurilloTello Apologies for the late reply. Thanks for getting back and sharing an update.

Instead of fetching the properties details at the origin group, try getting it directly from the origin using AFD Origins - Get REST API. This API resoponse includes the `properties.azureOrigin ` this has the Resource reference to the Azure origin resource..

Please click on the [**Try It option**](https://learn.microsoft.com/en-us/rest/api/frontdoor/azurefrontdoorstandardpremium/afd-origins/get#code-try-0) and check if that helps.

**Comment by navba-MSFT** [comment]
@GonzaloMurilloTello I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@GonzaloMurilloTello The action is currently pending on you to follow [the above suggestion. ](https://github.com/Azure/azure-cli/issues/27320#issuecomment-1732923822)If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
