### ISSUE TITLE
Add newer process architecture support for Bicep installation

### ISSUE THREAD

**Issue by anthony-c-martin** [Azure/azure-cli#27333]
**Related command**
```sh
az bicep install
```

**Is your feature request related to a problem? Please describe.**
AzCLI's built-in Bicep support is limited to the following architectures:
- bicep-win-x64
- bicep-linux-x64
- bicep-linux-musl-x64
- bicep-osx-x64

However we also publish the following binaries:
- bicep-win-arm64
- bicep-linux-arm64
- bicep-osx-arm64

See here for the code which is figuring out the correct binary to install: https://github.com/Azure/azure-cli/blob/090024ddd24311b8daafe5d831cf5fe11cf7743c/src/azure-cli/azure/cli/command_modules/resource/_bicep.py#L271-L287

I suspect this is the cause behind https://github.com/Azure/bicep/issues/11734.

**Describe the solution you'd like**
AzCLI should be able to detect arm64 processors and install arm64 Bicep binaries

**Possible solution**
AzCLI has similar logic for helm - we could probably reuse some of this logic for architecture detection: https://github.com/Azure/azure-cli/blob/090024ddd24311b8daafe5d831cf5fe11cf7743c/src/azure-cli/azure/cli/command_modules/acr/helm.py#L338-L362

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
Non customer reported. Adding Service team to look into this.

**Comment by jennyhunter-msft** [comment]
+ @alex-frankel 
This was filed by Anthony.
