### ISSUE TITLE
WebApp:CLI: Documentation for "--slot-setting" in "storage-account" for webapp remains unclear

### ISSUE THREAD

**Issue by haslo** [Azure/azure-cli#27343]
**Related command**

```sh
az webapp config storage-account [...]
```

* Content: [az webapp config storage-account](https://docs.microsoft.com/en-us/cli/azure/webapp/config/storage-account?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config/storage-account.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/latest/docs-ref-autogen/webapp/config/storage-account.yml)

**Is your feature request related to a problem? Please describe.**

Documentation is unclear: This is essentially my report for #16854 again.

The documentation that I made this ticket for still has this to say about `--slot-setting`:

```
--slot-setting
Slot setting.

default value: False
```

**Describe the solution you'd like**

I think it should say something like:

```
--slot-setting
With slot setting you can decide to make BYOS configuration sticky to a slot, meaning that when that slot is swapped, the storage account stays with that slot.

default value: False
```

Based on the discussion in that other ticket, this is what I believe that this setting will do, but of course it's very possible that I'm wrong (and obviously it's too informal like that).

**Describe alternatives you've considered**

n/a

**Additional context**

What definitely doesn't explain what `--slot-setting` does is the text "Slot setting." So while it looks like some other bug was closed, the original issue that I made a ticket for in 2021 remains open. The documentation has not been updated despite this comment: https://github.com/Azure/azure-cli/issues/16854#issuecomment-776747739

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@haslo Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by haslo** [comment]
Thanks. I am no longer personally impacted by this, but I figured that others might be in the future.
