### ISSUE TITLE
az backup protection check-vm not working as described

### ISSUE THREAD

**Issue by Klaas-** [Azure/azure-cli#27359]
### Describe the bug

az backup protection check-vm does not actually do what it claims to do in help. If I have a system where the state is "ProtectionFailed" it will still return the recovery services vault ID, it should return empty. 

```
$ az backup protection check-vm --help

Command
    az backup protection check-vm : Find out whether the virtual machine is protected or not. If
    protected, it returns the recovery services vault ID, otherwise it returns empty.
```

Example where it shows the wrong output:
```
$ az backup protection check-vm --subscription subscription-id --resource-group resoruce_group --vm hostname
"/subscriptions/subscription-id/resourceGroups/resource_group/providers/Microsoft.RecoveryServices/vaults/recovery_vault"
```

Output of the restapi seems to be correct:
```
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"protectionStatus":"ProtectionFailed","vaultId":"/subscriptions/subscription-id/resourceGroups/resource_group/providers/Microsoft.RecoveryServices/vaults/recovery_vault","fabricName":"Azure","containerName":"iaasvmcontainer;iaasvmcontainerv2;resoruce_group;hostname","protectedItemName":"vm;iaasvmcontainerv2;resoruce_group;hostname","errorCode":"UserErrorGuestAgentStatusUnavailable","errorMessage":"VM agent is unable to communicate with the Azure Backup Service.. Ensure that VM agent is latest and running. Allow access to IP 168.63.129.16 (refer https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/features-windows#network-access ). For more information, please refer to https://aka.ms/guestagent-status-unavailable ","policyName":"policy_name","protectedItemsCount":0}
```

### Related command

`az backup protection check-vm`

### Errors

No error message, logic error I'd guess -- or you need to change the description of what the command does

### Issue script & Debug output

See description, I'd say the necessary part is in the rest api response

### Expected behavior

It should show [] because the VM is not protected

### Environment Summary

```
az version
{
  "azure-cli": "2.52.0",
  "azure-cli-core": "2.52.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "resource-graph": "2.1.0"
  }
}
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by Klaas-** [comment]
Also when running with --debug I see that it does the same request twice:
```
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/subscription-id/resourceGroups/resource_group/providers/Microsoft.Compute/virtualMachines/hostname?api-version=2022-11-01'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '2f5f79d5-a138-455b-85c4-991971d6f6d1'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'ea6837fc-c28e-459b-b0cd-b8cf58637a34'
```


```
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/subscription-id/resourceGroups/resource_group/providers/Microsoft.Compute/virtualMachines/hostname?api-version=2022-11-01'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '23a91976-bc91-4f61-833e-9754630acf89'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'c2371baf-2ccf-4777-95cc-6c8c860669c9'
```

and then it finally creates the real request, but it does not use any additional information it gained from the first two requests, all information in the body was already available before getting the details of the VM

```
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/Subscriptions/subscription-id/providers/Microsoft.RecoveryServices/locations/germanywestcentral/backupStatus?api-version=2023-02-01'
cli.azure.cli.core.sdk.policies: Request method: 'POST'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '637dd066-50a2-11ee-ad8a-0022485b3991'
cli.azure.cli.core.sdk.policies:     'CommandName': 'backup protection check-vm'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--subscription --resource-group --vm --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.52.0 (RPM) azsdk-python-mgmt-recoveryservicesbackup/6.0.0 Python/3.9.16 (Linux-4.18.0-477.21.1.el8_8.x86_64-x86_64-with-glibc2.28)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"resourceType": "VM", "resourceId": "/subscriptions/subscription-id/resourceGroups/resource_group/providers/Microsoft.Compute/virtualMachines/hostname"}
```

and there is no --ids parameter that all(most?) other commands have

**Comment by adityabalaji-msft** [comment]
Adding @Daya-Patil , @zubairabid to look into the above

**Comment by Daya-Patil** [comment]
Thanks for reaching out. When the user triggers configure protection on a VM, there are series of steps performed on the VM. like validation, installing agent, talking snapshot, etc. During this process, machine also get associated to vault. When the status of configuring protection is "protection failed", service captures the error code and message to help user understand why the process failed. This error code and message can be seen in vault by navigating to jobs. Thats why vault details are displayed, so that user can go to said vault, see the error and perform the recommended steps to fix it. 

This is the default behavior.

**Comment by Klaas-** [comment]
> Thanks for reaching out. When the user triggers configure protection on a VM, there are series of steps performed on the VM. like validation, installing agent, talking snapshot, etc. During this process, machine also get associated to vault. When the status of configuring protection is "protection failed", service captures the error code and message to help user understand why the process failed. This error code and message can be seen in vault by navigating to jobs. Thats why vault details are displayed, so that user can go to said vault, see the error and perform the recommended steps to fix it.
> 
> This is the default behavior.

Hi @Daya-Patil,
I am not sure if I was able to properly get my complaint across, so l will try to say it differently.
The command does not do what the help says it does:

> Find out whether the virtual machine is protected or not. If protected, it returns the recovery services vault ID, otherwise it returns empty.

What it actually does:

Show the associated vault if one is associated, regardless of it's protection status

So if you say this is behavior you want, you have to correct the docs.

Greetings
Klaas

**Comment by Klaas-** [comment]
Also I'd guess it's not well named then because it does not "check" the VM :)

**Comment by Daya-Patil** [comment]
Sure, will update the documentation. Thanks

**Comment by zubairabid** [comment]
The documentation has been updated: https://github.com/Azure/azure-cli/pull/27569

**Comment by zubairabid** [comment]
Given the updated documentation, can we close this issue? @Klaas- @yonzhan

**Comment by Klaas-** [comment]
yeah you can close it from my point of view. I'd still argue it doesn't actually check a vm so it's a misnamed command. But with the updated help at least I now understand what it does :)
