### ISSUE TITLE
az vm show no longer works

### ISSUE THREAD

**Issue by nelson-manohar** [Azure/azure-cli#27365]
### Describe the bug

az vm show does not return anything -- even though vm is running.

az vm show --resource-group <resource-group-name> --name <vm-name> --query 'powerState' -o tsv

### Related command

az vm create

### Errors

Silent.

### Issue script & Debug output

![image](https://github.com/Azure/azure-cli/assets/86931296/b28cb87b-8523-4fd0-9970-0ad32193b359)

### Expected behavior

output: VM running.

### Environment Summary

$  az --version
azure-cli                         2.26.1 *

core                              2.26.1 *
telemetry                          1.0.6

Extensions:
azure-devops                      0.20.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\nelsonma\.azure\cliextensions'

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

You have 2 updates available. Consider updating your CLI installation with 'az upgrade'

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yanzhudd** [comment]
May I ask if the command worked in the previous versions of CLI?
