### ISSUE TITLE
[Service Connector] `az spring connection` remove the default value of `--deployment`

### ISSUE THREAD

**Issue by ChenTanyi** [Azure/azure-cli#27371]
**Description**
Service Connector is planning to support create connection with Spring App Resource beside Spring App Deployment Resource. Therefore, we need to remove the default value of `--deployment` to determine these different resource type while currently the default value of `--deployment` is `default`. It would be a breaking change in the current command.

**Related command**
`az spring connection`

**Expected behavior**
`--deployment` would not be required and no default value

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by ChenTanyi** [comment]
Close as breaking change PR merged.
