### ISSUE TITLE
function app vnet-integration add fails for France Central region with latest versions of Az cli

### ISSUE THREAD

**Issue by AnantRajSinghPAN** [Azure/azure-cli#27389]
### Describe the bug

Issue is seen on France Central Region only so far.

`az functionapp vnet-integration add` fails with following errors, for az cli versions 2.52.0, 2.51.0. Though works with 2.40.0
`There was a conflict. VnetRouteAllEnabled has different values as site property and site config`

the command works with version 2.40.0 for France Central Region.

### Related command

$ az version
{
  "azure-cli": "2.52.0",
  "azure-cli-core": "2.52.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {}
}
$ az functionapp vnet-integration add  --resource-group 'rg-xxxxx-03' --name 'func-xxxx' --subnet 'xxxx-subnet' --vnet '/subscriptions/d7xxxxxxxxxxxxxxxxxxxxxx9/resourceGroups/rg-xxxxxxxxxxx-03/providers/Microsoft.Network/virtualNetworks/vnetxxxxxxfrancecentral' 
`There was a conflict. VnetRouteAllEnabled has different values as site property and site config`

$ az version
{
  "azure-cli": "2.40.0",
  "azure-cli-core": "2.40.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}
$ az functionapp vnet-integration add  --resource-group 'rg-xxxxxxxxxxxxxxxx-03' --name 'func-xxxxxx' --subnet 'xxxxx-subnet' --vnet '/subscriptions/d76xxxxxxxxxxxx9/resourceGroups/rg-xxxxxxxxxxxxxh-03/providers/Microsoft.Network/virtualNetworks/vnetxxxxx-francecentral'
`{
  "id": "/subscriptions/d76xxxxxxxxxxxxxxxx9/resourceGroups/rg-xxxxxxxxxxxxxx-03/providers/Microsoft.Network/virtualNetworks/vnetxxxxxfrancecentral",
  "location": "France Central",
  "name": "vnetxxxxxxfrancecentral",
  "resourceGroup": "rg-xxxxxxxxxxxxxx-03",
  "subnetResourceId": "/subscriptions/d76xxxxxxxxxxxxxxxx9/resourceGroups/rg-xxxxxxxxxxxxxxxxxxx-03/providers/Microsoft.Network/virtualNetworks/vnetxxxxxxxfrancecentral/subnets/xxxxx-subnet"
}`

### Errors

There was a conflict. VnetRouteAllEnabled has different values as site property and site config

### Issue script & Debug output

NA

### Expected behavior

Add vnet to function app

### Environment Summary

{
  "azure-cli": "2.52.0",
  "azure-cli-core": "2.52.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {}
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by AnantRajSinghPAN** [comment]
Hi, any update on the issue. Thanks

**Comment by Sagarthore11** [comment]
Hello,

Even I noticed the same that only for central France we are getting the false, false value. I created the web app as well and noticed the same issue. 

Problem is reproducible using the portal/ARM template --> create function app

Thanks

**Comment by Sagarthore11** [comment]
Hello Team,

Thank you for helping on it.

Any update on it please?

**Comment by lankaapura** [comment]
> Thank you for opening this issue, we will look into it.

Hi @yonzhan - any update on this regard. This is causing failures in our devops pipelines for the France Central region. but the pipelines are working fine for other regions.

Appreciate if you could provide a workaround if it is long time to fix this.

**Comment by kamperiadis** [comment]
Hello @AnantRajSinghPAN @Sagarthore11 @lankaapura! If this is an issue reproducible using the portal and ARM template as @Sagarthore11 mentioned, then this is not an Azure CLI issue but rather a control plane issue.
