### ISSUE TITLE
bad pattern: [{name:Myipconfig1,group-id:sqlServer

### ISSUE THREAD

**Issue by KirillKotovsky** [Azure/azure-cli#27388]
### Describe the bug

az network private-endpoint create -n MyPE -g MyResourceGroup --vnet-name MyVnetName --subnet MySubnet --connection-name MyConnectionName --group-id MyGroupId --private-connection-resource-id MyResourceId --ip-configs [{name:Myipconfig1,group-id:MyGroupId ,member-name:MyMemberName,private-ip-address:10.0.0.4},{name:Myipconfig2,private-ip-address:10.0.0.6}]

bad pattern: [{name:Myipconfig1,group-id:sqlServer

### Related command

az network private-endpoint create -n MyPE -g MyResourceGroup --vnet-name MyVnetName --subnet MySubnet --connection-name MyConnectionName --group-id MyGroupId --private-connection-resource-id MyResourceId --ip-configs [{name:Myipconfig1,group-id:MyGroupId ,member-name:MyMemberName,private-ip-address:10.0.0.4},{name:Myipconfig2,private-ip-address:10.0.0.6}]

### Errors

bad pattern: [{name:Myipconfig1,group-id:sqlServer

### Issue script & Debug output

bad pattern: [{name:Myipconfig1,group-id:sqlServer

### Expected behavior

 private-endpoint create

### Environment Summary

{
  "azure-cli": "2.45.0",
  "azure-cli-core": "2.45.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "account": "0.2.5",
    "front-door": "1.0.17"
  }
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
> [{name:Myipconfig1,group-id:MyGroupId ,

Extra space before comma?
