### ISSUE TITLE
keyvault check-name always returns true

### ISSUE THREAD

**Issue by algonzalez-wf** [Azure/azure-cli#27390]
### Describe the bug

Calling `az keyvault check-name --name {name of an existing vault} --subscription {subscription name}` 
always returns `{ "message": null, "nameAvailable": true, "reason": null }`

### Related command

`az keyvault check-name`

### Errors

No errors, just an invalid response.

### Issue script & Debug output

No error, so nothing to debug

### Expected behavior

Similar response to when I call `az storage account check-name --name {existing account}`:
`{ "message": "The storage account named {existing account} is already taken.",  "nameAvailable": false, "reason": "AlreadyExists" }` 
but with the message referring to a key vault name.

### Environment Summary

azure-cli                         2.52.0

core                              2.52.0
telemetry                          1.1.0

Extensions:
azure-devops                      0.21.0
redisenterprise                    0.1.2

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\Alberto.Gonzalez\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by evelyn-ys** [comment]
@algonzalez-wf Currently `az keyvault check-name` only checks name availability of mhsm, vault is not covered:
![image](https://github.com/Azure/azure-cli/assets/10227683/bcd0c292-bb58-48d4-83e1-2c4a479c2bbd)

**Comment by algonzalez-wf** [comment]
Got it. Thanks. I'll use `$result = az keyvault list --resource-group $rgName --resource-type vault --query "contains([].name, '$kvName')"` instead
