### ISSUE TITLE
A story from Bhavish Ramaswamy on Medium

### ISSUE THREAD

**Issue by Jordanwaslistening** [Azure/azure-cli#27398]
Read this story from Bhavish Ramaswamy on Medium: https://bhavishramaswamy.medium.com/erc-721-erc-1155-c9b18eb19a5d![shared_image.jpg](https://github.com/Azure/azure-cli/assets/126301589/fb40288e-52dc-4c04-8e45-6eb2d75427de)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yonzhan** [comment]
Please provide detailed CLI command if any.

**Comment by bebound** [comment]
Off-topic / Spam
