### ISSUE TITLE
Palo-ALto cloudngfw's Rulestack commit cmdlet giving error

### ISSUE THREAD

**Issue by rheajain** [Azure/azure-cli#27401]
### Describe the bug

When you make a change to a rulestack, like add a new FQDN list, there are uncommitted changes added to the Rulestack that can then be committed using the commit command. This command is giving an error.

### Related command

az palo-alto cloudngfw local-rulestack commit

### Errors

TypeError: 'NoneType' object is not callable

### Issue script & Debug output

>az palo-alto cloudngfw local-rulestack commit --local-rulestack-name azTest -g rheaTerraformTest --debug
cli.knack.cli: Command arguments: ['palo-alto', 'cloudngfw', 'local-rulestack', 'commit', '--local-rulestack-name', 'azTest', '-g', 'rheaTerraformTest', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Enable VT mode.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x01A1B460>, <function OutputProducer.on_global_arguments at 0x01C1D6A0>, <function CLIQuery.on_global_arguments at 0x01C382F8>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'palo-alto': ['azext_palo_alto_networks']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: palo-alto-networks        0.247         8        21  C:\Users\rhjai\.azure\cliextensions\palo-alto-networks
cli.azure.cli.core: Total (1)                 0.247         8        21
cli.azure.cli.core: Loaded 8 groups, 21 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : palo-alto cloudngfw local-rulestack commit
cli.azure.cli.core: Command table: palo-alto cloudngfw local-rulestack commit
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03DBB4F0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\rhjai\.azure\commands\2023-09-14.11-47-55.palo-alto_cloudngfw_local-rulestack_commit.20860.log'.
az_command_data_logger: command args: palo-alto cloudngfw local-rulestack commit --local-rulestack-name {} -g {} --debugcli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03DE3928>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03E15A00>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03E15A90>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x01C1D6E8>, <function CLIQuery.handle_query_parameter at 0x01C38340>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03E15A48>]
az_command_data_logger: extension name: palo-alto-networks
az_command_data_logger: extension version: 1.0.0b1
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\rhjai\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\rhjai\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/888d76fa-54b2-4ced-8ee5-aac1585adee7/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/888d76fa-54b2-4ced-8ee5-aac1585adee7/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/888d76fa-54b2-4ced-8ee5-aac1585adee7/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/888d76fa-54b2-4ced-8ee5-aac1585adee7/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/888d76fa-54b2-4ced-8ee5-aac1585adee7/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/888d76fa-54b2-4ced-8ee5-aac1585adee7/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/888d76fa-54b2-4ced-8ee5-aac1585adee7/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: dec5317c-e55b-4db5-a486-7c1d0eabbda8
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/2bf4a339-294d-4c25-b0b2-ef649e9f5c27/resourceGroups/rheaTerraformTest/providers/PaloAltoNetworks.Cloudngfw/localRulestacks/azTest/commit?api-version=2022-08-29'
cli.azure.cli.core.sdk.policies: Request method: 'POST'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '7133cf5e-52c6-11ee-b1a5-d08e790a92ca'
cli.azure.cli.core.sdk.policies:     'CommandName': 'palo-alto cloudngfw local-rulestack commit'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--local-rulestack-name -g --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.51.0 (MSI) (AAZ) azsdk-python-core/1.26.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "POST /subscriptions/2bf4a339-294d-4c25-b0b2-ef649e9f5c27/resourceGroups/rheaTerraformTest/providers/PaloAltoNetworks.Cloudngfw/localRulestacks/azTest/commit?api-version=2022-08-29 HTTP/1.1" 202 2
cli.azure.cli.core.sdk.policies: Response status: 202
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '2'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Location': 'https://management.azure.com/providers/PaloAltoNetworks.Cloudngfw/locations/NORTHCENTRALUS/operationStatuses/9e4f3df5-faa5-4e68-afcc-055ea81b1ac7*B41AA7AB1B9DC0FF752579267D034858284431F7CA350635BB96609C2B18AD69?api-version=2022-08-29'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-providerhub-traffic': 'True'
cli.azure.cli.core.sdk.policies:     'Request-Context': 'appId=cid-v1:4aa06bd6-38f4-4944-9612-cd84d39b5e90'
cli.azure.cli.core.sdk.policies:     'mise-correlation-id': '59ced0b3-53af-456e-b4db-b8ae22e0a21a'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Azure-AsyncOperation': 'https://management.azure.com/providers/PaloAltoNetworks.Cloudngfw/locations/NORTHCENTRALUS/operationStatuses/9e4f3df5-faa5-4e68-afcc-055ea81b1ac7*B41AA7AB1B9DC0FF752579267D034858284431F7CA350635BB96609C2B18AD69?api-version=2022-08-29'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '9e4f3df5-faa5-4e68-afcc-055ea81b1ac7'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '6f245ce1-340b-4c95-bd9f-d47bf5a8d741'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'JIOINDIACENTRAL:20230914T061757Z:6f245ce1-340b-4c95-bd9f-d47bf5a8d741'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 14 Sep 2023 06:17:57 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/providers/PaloAltoNetworks.Cloudngfw/locations/NORTHCENTRALUS/operationStatuses/9e4f3df5-faa5-4e68-afcc-055ea81b1ac7*B41AA7AB1B9DC0FF752579267D034858284431F7CA350635BB96609C2B18AD69?api-version=2022-08-29'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '7133cf5e-52c6-11ee-b1a5-d08e790a92ca'
cli.azure.cli.core.sdk.policies:     'CommandName': 'palo-alto cloudngfw local-rulestack commit'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--local-rulestack-name -g --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.51.0 (MSI) (AAZ) azsdk-python-core/1.26.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: https://management.azure.com:443 "GET /providers/PaloAltoNetworks.Cloudngfw/locations/NORTHCENTRALUS/operationStatuses/9e4f3df5-faa5-4e68-afcc-055ea81b1ac7*B41AA7AB1B9DC0FF752579267D034858284431F7CA350635BB96609C2B18AD69?api-version=2022-08-29 HTTP/1.1" 202 525
cli.azure.cli.core.sdk.policies: Response status: 202
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '525'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'ETag': '"4702386d-0000-0100-0000-6502a5950000"'
cli.azure.cli.core.sdk.policies:     'Location': 'https://management.azure.com/providers/PaloAltoNetworks.Cloudngfw/locations/northcentralus/operationStatuses/9e4f3df5-faa5-4e68-afcc-055ea81b1ac7*B41AA7AB1B9DC0FF752579267D034858284431F7CA350635BB96609C2B18AD69?api-version=2022-08-29'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-tenant-reads': '11999'
cli.azure.cli.core.sdk.policies:     'Azure-AsyncOperation': 'https://management.azure.com/providers/PaloAltoNetworks.Cloudngfw/locations/northcentralus/operationStatuses/9e4f3df5-faa5-4e68-afcc-055ea81b1ac7*B41AA7AB1B9DC0FF752579267D034858284431F7CA350635BB96609C2B18AD69?api-version=2022-08-29'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'af51771a-5e78-4699-b3aa-a98f5c949d69'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'acc83b1f-f2aa-4c47-aa7a-43aa5685c333'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'JIOINDIACENTRAL:20230914T061758Z:acc83b1f-f2aa-4c47-aa7a-43aa5685c333'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 14 Sep 2023 06:17:57 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"id":"/providers/PaloAltoNetworks.Cloudngfw/locations/NORTHCENTRALUS/operationStatuses/9e4f3df5-faa5-4e68-afcc-055ea81b1ac7*B41AA7AB1B9DC0FF752579267D034858284431F7CA350635BB96609C2B18AD69","name":"9e4f3df5-faa5-4e68-afcc-055ea81b1ac7*B41AA7AB1B9DC0FF752579267D034858284431F7CA350635BB96609C2B18AD69","resourceId":"/subscriptions/2bf4a339-294d-4c25-b0b2-ef649e9f5c27/resourceGroups/rheaTerraformTest/providers/PaloAltoNetworks.Cloudngfw/localRulestacks/azTest","status":"Accepted","startTime":"2023-09-14T06:17:57.4304065Z"}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/providers/PaloAltoNetworks.Cloudngfw/locations/NORTHCENTRALUS/operationStatuses/9e4f3df5-faa5-4e68-afcc-055ea81b1ac7*B41AA7AB1B9DC0FF752579267D034858284431F7CA350635BB96609C2B18AD69?api-version=2022-08-29'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '7133cf5e-52c6-11ee-b1a5-d08e790a92ca'
cli.azure.cli.core.sdk.policies:     'CommandName': 'palo-alto cloudngfw local-rulestack commit'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--local-rulestack-name -g --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.51.0 (MSI) (AAZ) azsdk-python-core/1.26.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: https://management.azure.com:443 "GET /providers/PaloAltoNetworks.Cloudngfw/locations/NORTHCENTRALUS/operationStatuses/9e4f3df5-faa5-4e68-afcc-055ea81b1ac7*B41AA7AB1B9DC0FF752579267D034858284431F7CA350635BB96609C2B18AD69?api-version=2022-08-29 HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'ETag': '"47023c6d-0000-0100-0000-6502a5ad0000"'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-tenant-reads': '11998'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '039e1a7c-7707-4092-832c-4529314ed9b2'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '0b03e1a6-b562-42c6-97aa-3d069ee10cf2'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'JIOINDIACENTRAL:20230914T061828Z:0b03e1a6-b562-42c6-97aa-3d069ee10cf2'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 14 Sep 2023 06:18:28 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"id":"/providers/PaloAltoNetworks.Cloudngfw/locations/NORTHCENTRALUS/operationStatuses/9e4f3df5-faa5-4e68-afcc-055ea81b1ac7*B41AA7AB1B9DC0FF752579267D034858284431F7CA350635BB96609C2B18AD69","name":"9e4f3df5-faa5-4e68-afcc-055ea81b1ac7*B41AA7AB1B9DC0FF752579267D034858284431F7CA350635BB96609C2B18AD69","resourceId":"/subscriptions/2bf4a339-294d-4c25-b0b2-ef649e9f5c27/resourceGroups/rheaTerraformTest/providers/PaloAltoNetworks.Cloudngfw/localRulestacks/azTest","status":"Succeeded","startTime":"2023-09-14T06:17:57.4304065Z","endTime":"2023-09-14T06:18:21.8098853Z","error":{},"properties":null}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/providers/PaloAltoNetworks.Cloudngfw/locations/NORTHCENTRALUS/operationStatuses/9e4f3df5-faa5-4e68-afcc-055ea81b1ac7*B41AA7AB1B9DC0FF752579267D034858284431F7CA350635BB96609C2B18AD69?api-version=2022-08-29'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '7133cf5e-52c6-11ee-b1a5-d08e790a92ca'
cli.azure.cli.core.sdk.policies:     'CommandName': 'palo-alto cloudngfw local-rulestack commit'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--local-rulestack-name -g --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.51.0 (MSI) (AAZ) azsdk-python-core/1.26.0 Python/3.10.10 (Windows-10-10.0.22621-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: https://management.azure.com:443 "GET /providers/PaloAltoNetworks.Cloudngfw/locations/NORTHCENTRALUS/operationStatuses/9e4f3df5-faa5-4e68-afcc-055ea81b1ac7*B41AA7AB1B9DC0FF752579267D034858284431F7CA350635BB96609C2B18AD69?api-version=2022-08-29 HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'ETag': '"47023c6d-0000-0100-0000-6502a5ad0000"'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-tenant-reads': '11997'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '2f104a73-a0d7-477e-94ff-a76f209361e3'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'ff6c9ffe-ff0d-4111-9920-5aaf92b8b911'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'JIOINDIACENTRAL:20230914T061828Z:ff6c9ffe-ff0d-4111-9920-5aaf92b8b911'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 14 Sep 2023 06:18:28 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"id":"/providers/PaloAltoNetworks.Cloudngfw/locations/NORTHCENTRALUS/operationStatuses/9e4f3df5-faa5-4e68-afcc-055ea81b1ac7*B41AA7AB1B9DC0FF752579267D034858284431F7CA350635BB96609C2B18AD69","name":"9e4f3df5-faa5-4e68-afcc-055ea81b1ac7*B41AA7AB1B9DC0FF752579267D034858284431F7CA350635BB96609C2B18AD69","resourceId":"/subscriptions/2bf4a339-294d-4c25-b0b2-ef649e9f5c27/resourceGroups/rheaTerraformTest/providers/PaloAltoNetworks.Cloudngfw/localRulestacks/azTest","status":"Succeeded","startTime":"2023-09-14T06:17:57.4304065Z","endTime":"2023-09-14T06:18:21.8098853Z","error":{},"properties":null}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 708, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1000, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 109, in result
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 453, in resource
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 571, in _parse_resource
TypeError: 'NoneType' object is not callable

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 708, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1000, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 109, in result
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 453, in resource
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 571, in _parse_resource
TypeError: 'NoneType' object is not callable
az_command_data_logger: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 708, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1000, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 109, in result
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 453, in resource
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 571, in _parse_resource
TypeError: 'NoneType' object is not callable
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03DBB610>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 34.361 seconds (init: 0.640, invoke: 33.721)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 7331 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\rhjai\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

Commit is an async operation. So polling the API should give correct response.

### Environment Summary

azure-cli                         2.51.0 *

core                              2.51.0 *
telemetry                          1.1.0

Extensions:
palo-alto-networks               1.0.0b1

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\rhjai\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by rheajain** [comment]
I upgraded to version 2.52.0 and still getting the same error. Can you please check again.

**Comment by ZengTaoxu** [comment]
Has the version palo-alto-networks been updated to the latest version? The latest version is 1.1.1b1.
