### ISSUE TITLE
Microsoft.Web provider stuck with Registering status

### ISSUE THREAD

**Issue by ayelencasamassa** [Azure/azure-cli#27405]
### Describe the bug

Microsoft.Web provider stuck with Registering status

### Related command

-

### Errors

Microsoft.Web provider stuck with Registering status

### Issue script & Debug output

Microsoft.Web provider stuck with Registering status

### Expected behavior

Register the provider

### Environment Summary

-

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by YSDimov** [comment]
I experience the same issue for two different subscriptions, same tenant.

**Comment by darinhoward** [comment]
Same issue as well across 2 subscriptions.

**Comment by seligj95** [comment]
Thank you for reaching out. This is not related to CLI. If this is still an issue, please open a support case.
