### ISSUE TITLE
az iot hub device-identity import -n {iothub_name} --ibcu {input_sas_uri} --obcu {output_sas_uri} is invaild

### ISSUE THREAD

**Issue by zh0903** [Azure/azure-cli#27411]
### Describe the bug

Customer reported :
"az iot hub device-identity import -n {iothub_name} --ibcu {input_sas_uri} --obcu {output_sas_uri}" is invalid now.
I can reproduce his error with all fine configuration and resource.
But 
az iot hub device-identity import -n {iothub_name} --ibc {input_blob_container_name} --isa {input_storage_account_name} --obc {output_blob_container_name} --osa {output_storage_account_name}
works well.

### Related command

Customer reported :
"az iot hub device-identity import -n {iothub_name} --ibcu {input_sas_uri} --obcu {output_sas_uri}" is invalid now.
I can reproduce his error with all fine configuration and resource.
But 
az iot hub device-identity import -n {iothub_name} --ibc {input_blob_container_name} --isa {input_storage_account_name} --obc {output_blob_container_name} --osa {output_storage_account_name}
works well.

### Errors

Customer reported :
"az iot hub device-identity import -n {iothub_name} --ibcu {input_sas_uri} --obcu {output_sas_uri}" is invalid now.
I can reproduce his error with all fine configuration and resource.
But 
az iot hub device-identity import -n {iothub_name} --ibc {input_blob_container_name} --isa {input_storage_account_name} --obc {output_blob_container_name} --osa {output_storage_account_name}
works well.

### Issue script & Debug output

Customer reported :
"az iot hub device-identity import -n {iothub_name} --ibcu {input_sas_uri} --obcu {output_sas_uri}" is invalid now.
I can reproduce his error with all fine configuration and resource.
But 
az iot hub device-identity import -n {iothub_name} --ibc {input_blob_container_name} --isa {input_storage_account_name} --obc {output_blob_container_name} --osa {output_storage_account_name}
works well.

### Expected behavior

Customer reported :
"az iot hub device-identity import -n {iothub_name} --ibcu {input_sas_uri} --obcu {output_sas_uri}" is invalid now.
I can reproduce his error with all fine configuration and resource.
But 
az iot hub device-identity import -n {iothub_name} --ibc {input_blob_container_name} --isa {input_storage_account_name} --obc {output_blob_container_name} --osa {output_storage_account_name}
works well.

### Environment Summary

Customer reported :
"az iot hub device-identity import -n {iothub_name} --ibcu {input_sas_uri} --obcu {output_sas_uri}" is invalid now.
I can reproduce his error with all fine configuration and resource.
But 
az iot hub device-identity import -n {iothub_name} --ibc {input_blob_container_name} --isa {input_storage_account_name} --obc {output_blob_container_name} --osa {output_storage_account_name}
works well.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by vilit1** [comment]
Hi

For the `az iot hub device-identity import -n {iothub_name} --ibcu {input_sas_uri} --obcu {output_sas_uri}` - do you include the SAS token key as part of the URI's? 
This is noted in the help:
![image](https://github.com/Azure/azure-cli/assets/73560279/edb65f3e-d3e6-4d35-846c-788bc94e33e0)

If you use the alternate `az iot hub device-identity import -n {iothub_name} --ibc {input_blob_container_name} --isa {input_storage_account_name} --obc {output_blob_container_name} --osa {output_storage_account_name}`, the cli will retrieve the necessary SAS token for you.

If you add the SAS token to the ibcu/obcu version and still have issues, please post the error message so I can debug your issue.

**Comment by zh0903** [comment]
> Hi
> 
> For the `az iot hub device-identity import -n {iothub_name} --ibcu {input_sas_uri} --obcu {output_sas_uri}` - do you include the SAS token key as part of the URI's? This is noted in the help: ![image](https://user-images.githubusercontent.com/73560279/272063591-edb65f3e-d3e6-4d35-846c-788bc94e33e0.png)
> 
> If you use the alternate `az iot hub device-identity import -n {iothub_name} --ibc {input_blob_container_name} --isa {input_storage_account_name} --obc {output_blob_container_name} --osa {output_storage_account_name}`, the cli will retrieve the necessary SAS token for you.
> 
> If you add the SAS token to the ibcu/obcu version and still have issues, please post the error message so I can debug your issue.

Yes, we included them. You may test if "az iot hub device-identity import -n {iothub_name} --ibcu {input_sas_uri} --obcu {output_sas_uri}" works

**Comment by vilit1** [comment]
Can you post the error message? I cannot debug without it.
