### ISSUE TITLE
There is an issue with the markdown on this page

### ISSUE THREAD

**Issue by mrblurgle** [Azure/azure-cli#27419]
### Describe the bug

Documentation rendering raw markdown.

### Related command

See https://learn.microsoft.com/en-us/cli/azure/billing/enrollment-account?view=azure-cli-latest#az-billing-enrollment-account-list() in Chrome.

### Errors

There appears to be a markdown issue on the page:
https://learn.microsoft.com/en-us/cli/azure/billing/enrollment-account?view=azure-cli-latest#az-billing-enrollment-account-list()

### Issue script & Debug output

The page is rendering some raw Markdown code by the look of it. I see this.

```
:keyword callable cls: A custom type or function that will be passed the direct response :return: An iterator like instance of either EnrollmentAccountListResult or the result of cls(response) :rtype: ~azure.core.paging.ItemPaged[~azure.mgmt.billing.models.EnrollmentAccountListResult] :raises: ~azure.core.exceptions.HttpResponseError
```

### Expected behavior

I'd expect to see the rendered markup, not the raw markdown.

### Environment Summary

Chrome Version 116.0.5845.179 (Official Build) (64-bit) running on NixOs.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jsntcy** [comment]
@mrblurgle, please report issue related to document in https://github.com/MicrosoftDocs/azure-docs-cli/issues

**Comment by mrblurgle** [comment]
> @mrblurgle, please report issue related to document in https://github.com/MicrosoftDocs/azure-docs-cli/issues

I have now reported this as https://github.com/MicrosoftDocs/azure-docs-cli/issues/3870. I will close this issue.
