### ISSUE TITLE
The "--ip-address" can't afford a list of IPs

### ISSUE THREAD

**Issue by jeremiedeveloper** [Azure/azure-cli#27425]
### Describe the bug

When we want to add several IPs using "az storage account network-rule add" the parameter --ip-address" can't support more than one IPs.

### Related command

az storage account network-rule add --ip-address ip1 ip2 ip3

### Errors

unrecognized arguments: <valueofIP2>

### Issue script & Debug output

cli.knack.cli: Command arguments: ['storage', 'account', 'network-rule', 'add', '--account-name', 'xxxxx', '--resource-group', 'xxxxx', '--ip-address', 'xxxxx', 'xxxxxx', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7efd371bd1f0>, <function OutputProducer.on_global_arguments at 0x7efd370d7d30>, <function CLIQuery.on_global_arguments at 0x7efd37070310>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'storage': ['azure.cli.command_modules.storage', 'azext_storage_preview']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: storage                   0.050        58       272
cli.azure.cli.core: Total (1)                 0.050        58       272
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: ai-examples               0.113         1         1  /usr/lib/python3.9/site-packages/azure-cli-extensions/ai-examples
cli.knack.cli: Event: CommandLoader.OnLoadCommandTable []
cli.azure.cli.core: storage-preview           0.010        14        36  /home/jeremie_rouelle/.azure/cliextensions/storage-preview
cli.azure.cli.core: Total (2)                 0.123        15        37  
cli.azure.cli.core: Loaded 65 groups, 295 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : storage account network-rule add
cli.azure.cli.core: Command table: storage account network-rule add
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7efd36514430>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/jeremie_rouelle/.azure/commands/2023-09-19.12-53-34.storage_account_network-rule_add.1204.log'.
az_command_data_logger: command args: storage account network-rule add --account-name {} --resource-group {} --ip-address {} {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7efd364bf040>]
cli.knack.cli: Event: CommandLoader.OnLoadArguments []
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7efd364f50d0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7efd3647fee0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
urllib3.connectionpool: Starting new HTTPS connection (1): app.aladdin.microsoft.com:443
urllib3.connectionpool: https://app.aladdin.microsoft.com:443 "GET /api/v1.0/suggestions?query=%7B%22command%22%3A+%22storage+account+network-rule+add%22%2C+%22parameters%22%3A+%22%22%7D&clientType=AzureCli&context=%7B%22versionNumber%22%3A+%222.52.0%22%2C+%22errorType%22%3A+%22UnrecognizedArguments%22%2C+%22correlationId%22%3A+%224a523397-7292-47c1-b200-0186e2ebdacd%22%2C+%22subscriptionId%22%3A+%228e152e9e-e3b9-4b44-a286-3893ae868626%22%2C+%22eventId%22%3A+%2224dfc215-693f-4a77-8b1d-056732e6e10d%22%7D HTTP/1.1" 200 None
cli.azure.cli.core.azclierror: NoneType: None

cli.azure.cli.core.azclierror: unrecognized arguments: <valueofIP2>
az_command_data_logger: unrecognized arguments: <valueofIP2>

Examples from AI knowledge base:
az storage account network-rule add --resource-group myRg --account-name mystorageaccount --subnet $subnetId
Create a rule to allow access for a subnet in another resource group.

az storage account network-rule add --resource-group myRg --account-name mystorageaccount --vnet-name myvnet --subnet mysubnet
Create a rule to allow access for a subnet.

https://docs.microsoft.com/en-US/cli/azure/storage/account/network-rule#az_storage_account_network_rule_add
Read more about the command in reference docs
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7efd36514670>]
az_command_data_logger: exit code: 2
cli.__main__: Command ran in 0.434 seconds (init: 0.123, invoke: 0.310)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3816 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/bin/python3.9 /usr/lib/az/lib/python3.9/site-packages/azure/cli/telemetry/__init__.py /home/jeremie_rouelle/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

I would like to add more than 1 IP by command executed

### Environment Summary

{
  "azure-cli": "2.52.0",
  "azure-cli-core": "2.52.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "ai-examples": "0.2.5",
    "databricks": "0.10.2",
    "k8s-extension": "1.4.2",
    "logic": "0.1.4",
    "ml": "2.19.1",
    "resource-graph": "2.1.0",
    "ssh": "2.0.1",
    "storage-preview": "0.7.0"
  }
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by calvinhzy** [comment]
What format of ip are you trying to add? Multiple ips should be accepted. 
![image](https://github.com/Azure/azure-cli/assets/17182306/2f33f6bc-a4b6-47d1-983d-fb26ca7b0b16)
Another thing that might affect this is the extension version, old extension version for storage-preview could be affecting this command. I see you have 0.7.0 installed, the latest should be 1.0.0b1, can you run `az extension add -n storage-preview --upgrade` to try it with the latest version. 
![image](https://github.com/Azure/azure-cli/assets/17182306/a244580d-9025-4721-884f-4d749263e895)

**Comment by jeremiedeveloper** [comment]
Hi @calvinhzy 
Thanks for your answer, indeed, upgrading storage-preview extension fixed it !
(I use IPV4 adresses as well)

Thank you!
