### ISSUE TITLE
az storage account check-name -n stgteststorageaccountthat fails with SubscriptionNotFound when the subscription exists

### ISSUE THREAD

**Issue by svenna** [Azure/azure-cli#27436]
### Describe the bug

trying to run the command 
❯ az storage account check-name -n stgteststorageaccountthat
responds with the following error
(SubscriptionNotFound) Subscription <sub1id> was not found.
Code: SubscriptionNotFound
Message: Subscription <sub1id> was not found.

the above command works as expected when run in another subscription
the subscription is a subscription managed by another tenant 

![image](https://github.com/Azure/azure-cli/assets/94612/e9f0a81e-c339-4bc0-ad3f-5faeac80d57f)

### Related command

 az storage account check-name -n stgteststorageaccountthat

### Errors

![image](https://github.com/Azure/azure-cli/assets/94612/69d55833-64ba-497c-aa3a-dc3a3aeaa176)

### Issue script & Debug output

❯ az storage account check-name -n stgteststorageaccountt --debug
cli.knack.cli: Command arguments: ['storage', 'account', 'check-name', '-n', 'stgteststorageaccountt', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fb65982f010>, <function OutputProducer.on_global_arguments at 0x7fb6597824d0>, <function CLIQuery.on_global_arguments at 0x7fb6595a79a0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'storage': ['azure.cli.command_modules.storage']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: storage                   0.038        58       272
cli.azure.cli.core: Total (1)                 0.038        58       272
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 58 groups, 272 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : storage account check-name
cli.azure.cli.core: Command table: storage account check-name
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fb6582be7a0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/fredrik/.azure/commands/2023-09-20.11-59-35.storage_account_check-name.6568.log'.
az_command_data_logger: command args: storage account check-name -n {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fb6580aae60>]
cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/home/fredrik/.pyenv/versions/3.10.11/envs/btpy/lib/python3.10/site-packages/azure/cli/core/profiles/_shared.py", line 655, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azure.mgmt.storage.v2022_09_01.models' has no attribute 'ActiveDirectoryPropertiesAccountType'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/home/fredrik/.pyenv/versions/3.10.11/envs/btpy/lib/python3.10/site-packages/azure/cli/core/profiles/_shared.py", line 655, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azure.mgmt.storage.v2022_09_01.models' has no attribute 'ListKeyExpand'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/home/fredrik/.pyenv/versions/3.10.11/envs/btpy/lib/python3.10/site-packages/azure/cli/core/profiles/_shared.py", line 655, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azure.mgmt.storage.v2022_09_01.models' has no attribute 'CorsRuleAllowedMethodsItem'

cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7fb6580d4ca0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7fb6580d4dc0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fb659782560>, <function CLIQuery.handle_query_parameter at 0x7fb6595a7a30>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7fb6580d4d30>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=StorageManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='/home/fredrik/.azure/msal_token_cache.json', encrypt=False
cli.azure.cli.core.auth.binary_cache: load: /home/fredrik/.azure/msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/hidden1/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/hidden/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/hidden/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/hidden/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/hidden/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/hidden/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/hidden/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 78902d53-b909-4840-975b-9833673bfd0f
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/hidden/providers/Microsoft.Storage/checkNameAvailability?api-version=2022-09-01'
cli.azure.cli.core.sdk.policies: Request method: 'POST'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '79'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '67165ef4-579c-11ee-ac4b-00155dbaef7f'
cli.azure.cli.core.sdk.policies:     'CommandName': 'storage account check-name'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-n --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.52.0 (PIP) azsdk-python-azure-mgmt-storage/21.0.0 Python/3.10.11 (Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"name": "stgteststorageaccountt", "type": "Microsoft.Storage/storageAccounts"}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "POST /subscriptions/hidden/providers/Microsoft.Storage/checkNameAvailability?api-version=2022-09-01 HTTP/1.1" 404 118
cli.azure.cli.core.sdk.policies: Response status: 404
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '118'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '9edada86-a1dc-4a59-b596-403ac16931ad'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11995'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '8d6a2218-b029-460f-a211-b0f081f47ad6'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SWEDENSOUTH:20230920T095935Z:8d6a2218-b029-460f-a211-b0f081f47ad6'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 20 Sep 2023 09:59:35 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"SubscriptionNotFound","message":"Subscription hidden was not found."}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/home/fredrik/.pyenv/versions/3.10.11/envs/btpy/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/fredrik/.pyenv/versions/3.10.11/envs/btpy/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/home/fredrik/.pyenv/versions/3.10.11/envs/btpy/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/home/fredrik/.pyenv/versions/3.10.11/envs/btpy/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/home/fredrik/.pyenv/versions/3.10.11/envs/btpy/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/home/fredrik/.pyenv/versions/3.10.11/envs/btpy/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/fredrik/.pyenv/versions/3.10.11/envs/btpy/lib/python3.10/site-packages/azure/cli/command_modules/storage/operations/account.py", line 22, in check_name_availability
    return client.check_name_availability(account_name)
  File "/home/fredrik/.pyenv/versions/3.10.11/envs/btpy/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/fredrik/.pyenv/versions/3.10.11/envs/btpy/lib/python3.10/site-packages/azure/mgmt/storage/v2022_09_01/operations/_storage_accounts_operations.py", line 704, in check_name_availability
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/fredrik/.pyenv/versions/3.10.11/envs/btpy/lib/python3.10/site-packages/azure/core/exceptions.py", line 109, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: (SubscriptionNotFound) Subscription hidden was not found.
Code: SubscriptionNotFound
Message: Subscription hidden was not found.

cli.azure.cli.core.azclierror: (SubscriptionNotFound) Subscription hidden was not found.
Code: SubscriptionNotFound
Message: Subscription hidden was not found.
az_command_data_logger: (SubscriptionNotFound) Subscription hidden was not found.
Code: SubscriptionNotFound
Message: Subscription hidden was not found.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fb6582be9e0>]
az_command_data_logger: exit code: 3
cli.__main__: Command ran in 0.965 seconds (init: 0.169, invoke: 0.796)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3683 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/home/fredrik/.pyenv/versions/3.10.11/envs/btpy/bin/python3.10 /home/fredrik/.pyenv/versions/3.10.11/envs/btpy/lib/python3.10/site-packages/azure/cli/telemetry/__init__.py /home/fredrik/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

❯ az storage account check-name -n stgteststorageaccountt
{
  "message": null,
  "nameAvailable": true,
  "reason": null
}

### Environment Summary

❯ az --version
azure-cli                         2.52.0

core                              2.52.0
telemetry                          1.1.0

Extensions:
account                            0.2.5

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location '/home/fredrik/.pyenv/versions/3.10.11/envs/btpy/bin/python3.10'
Extensions directory '/home/fredrik/.azure/cliextensions'

Python (Linux) 3.10.11 (main, May  2 2023, 16:44:34) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by calvinhzy** [comment]
Hi @svenna, since the subscription is in another tenant, it is probably why it is raising this error. Can you use `az login --tenant "tenantid"` to login to the other tenant? Thanks.
