### ISSUE TITLE
"Could not find control plane"

### ISSUE THREAD

**Issue by roy-work** [Azure/azure-cli#27440]
### Describe the bug

The `az aks show` is to demonstrate that this cluster does, in fact, exist:
```
» az aks show -g akscorp -n akscorp >/dev/null && printf '(success.)\n'
(success.)
» az aks get-credentials --admin -g akscorp -n akscorp
(ControlPlaneNotFound) Could not find control plane with ID 5cfeec3b8842470001f05b2f.
Code: ControlPlaneNotFound
Message: Could not find control plane with ID 5cfeec3b8842470001f05b2f.
Exception Details:	(Unspecified) rpc error: code = NotFound desc = Control Plane not found
	Code: Unspecified
	Message: rpc error: code = NotFound desc = Control Plane not found
```

… I cannot reach the control plane via `kubectl`, either. Near as I can tell, Azure AKS is in an outage.

### Related command

`az aks get-credentials`

### Errors

```
(ControlPlaneNotFound) Could not find control plane with ID 5cfeec3b8842470001f05b2f.
Code: ControlPlaneNotFound
Message: Could not find control plane with ID 5cfeec3b8842470001f05b2f.
Exception Details:	(Unspecified) rpc error: code = NotFound desc = Control Plane not found
	Code: Unspecified
	Message: rpc error: code = NotFound desc = Control Plane not found
```

### Issue script & Debug output

(Snipped. I don't have time to dig through & sanitize that much logging. Suffice to say the response from the API appears insane.)
```
cli.azure.cli.core.sdk.policies: Response status: 404
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '285'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'd8e24758-95bf-4cb1-834f-8d47b70c8edc'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '1c31460f-5b1c-4fd2-92d1-e6bfd3e0289e'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'EASTUS2:20230920T203608Z:d8e24758-95bf-4cb1-834f-8d47b70c8edc'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: AA8BE0ED400E4CBBACB0680C04CBB25A Ref B: MNZ221060608051 Ref C: 2023-09-20T20:36:08Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 20 Sep 2023 20:36:08 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "code": "ControlPlaneNotFound",
  "details": [
   {
    "code": "Unspecified",
    "message": "rpc error: code = NotFound desc = Control Plane not found"
   }
  ],
  "message": "Could not find control plane with ID 5cfeec3b8842470001f05b2f.",
  "subcode": "ControlPlaneNotFound"
 }
 ```

### Expected behavior

… this command should succeed. The cluster exists, & I have access to it.

(And if either of those assumptions turn out to be wrong, then it should emit a usable diagnostic.)

Additionally, Azure's status page should reflect the actual status of services.

### Environment Summary

```
» az --version
azure-cli                         2.50.0 *

core                              2.50.0 *
telemetry                          1.0.8 *

Extensions:
automation                         0.1.1
databricks                         0.8.0
ssh                                2.0.1
storage-preview                    0.8.3

Dependencies:
msal                              1.22.0
azure-mgmt-resource             23.1.0b2
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by roy-work** [comment]
(Additionally, this is support ticket ID 2309200040013939 .)

**Comment by navba-MSFT** [comment]
@roy-work Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by FumingZhang** [comment]
Hey @roy-work, sorry for the inconvenience, this is not a client side issue. AKS team has helped restore your cluster from server side. Please check whether its current status meets your expectations.

**Comment by roy-work** [comment]
@FumingZhang Apologies, I did not see your reply in time. Support refused to support us, as we're on 1.24¹. So, I attempted to upgrade the cluster.

Prior to the upgrade, I attempted to reach the cluster, and wasn't able to. I don't think I attempted to refresh the credentials until after the upgrade had started. However, after the upgrade started, I was able to reach the API server, but the cert was expired, or something; I refreshed the credentials and all was good. The API server's URL appears to have changed, which I did not expect, and I wonder if that was related.

¹I am so over this excuse. People cannot get to a supported version, because stuff is constantly not working, and support's eternal answer is "we don't support that version". Make it easier for me to upgrade, and I will keep up to date, but right now it's a massive pain in my side, and I'm starting to seriously wonder what benefit AKS has over a kubeadm cluster on some VMs.

**Comment by navba-MSFT** [comment]
@roy-work Thanks for getting back. Apologies for the inconvenience caused on this from the support standpoint. As mentioned by @FumingZhang in the above comment AKS team has helped restore your cluster from server side. Could you please check again and reconfirm if you are still facing the same issue ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@roy-work I hope you had a chance to look at the [above comment. ](https://github.com/Azure/azure-cli/issues/27440#issuecomment-1732934392) If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
