### ISSUE TITLE
az vm encryption enable - Results in Error - 'CertificateClient' object has no attribute 'get_key'

### ISSUE THREAD

**Issue by mackswift** [Azure/azure-cli#27446]
### Describe the bug

Attempting to encrypt a vm with Azure Cloud Shell with the command - az vm encryption enable --resource-group ****** --name ******* --disk-encryption-keyvault ******** --key-encryption-key *********

This results in an an Azure Cloud Shell error regardless of the type of VM created (Ubuntu Linux, Windows 2019 or 2022).

### Related command

az vm encryption enable

### Errors

The command failed with an unexpected error. Here is the traceback:
'CertificateClient' object has no attribute 'get_key'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/vm/disk_encryption.py", line 118, in encrypt_vm
    key_encryption_key = _get_keyvault_key_url(
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/vm/disk_encryption.py", line 367, in _get_keyvault_key_url
    result = client.get_key(key_name)
AttributeError: 'CertificateClient' object has no attribute 'get_key'

### Issue script & Debug output

cli.knack.cli: Command arguments: ['vm', 'encryption', 'enable', '--resource-group', 'azuremolchapter14', '--name', 'molvmwin', '--disk-encryption-keyvault', 'azuremolch14keyvault', '--key-encryption-key', 'azuremolencryptionkey', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f5be02ef1f0>, <function OutputProducer.on_global_arguments at 0x7f5be020ad30>, <function CLIQuery.on_global_arguments at 0x7f5be01a1310>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'vm': ['azure.cli.command_modules.vm']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: vm                        0.179        57       244
cli.azure.cli.core: Total (1)                 0.179        57       244
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: ai-examples               0.075         1         1  /usr/lib/python3.9/site-packages/azure-cli-extensions/ai-examples
cli.azure.cli.core: Total (1)                 0.075         1         1  
cli.azure.cli.core: Loaded 58 groups, 245 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : vm encryption enable
cli.azure.cli.core: Command table: vm encryption enable
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f5bdf644430>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/mack/.azure/commands/2023-09-21.18-06-52.vm_encryption_enable.621.log'.
az_command_data_logger: command args: vm encryption enable --resource-group {} --name {} --disk-encryption-keyvault {} --key-encryption-key {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f5bdf5f0040>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f5bdf61f0d0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f5bdf626ee0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f5be020adc0>, <function CLIQuery.handle_query_parameter at 0x7f5be01a13a0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f5bdf626e50>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ComputeManagementClient
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2172
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: MSIAuthenticationWrapper.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2172
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: Normalize expires_on: '1695321582' -> 1695321582
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/1bc09500-bd2d-4aeb-ac76-2b4c2a50b819/resourceGroups/azuremolchapter14/providers/Microsoft.Compute/virtualMachines/molvmwin?api-version=2022-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'a4454002-58a9-11ee-a8ec-8203de4bc7be'
cli.azure.cli.core.sdk.policies:     'CommandName': 'vm encryption enable'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --name --disk-encryption-keyvault --key-encryption-key --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.52.0 (RPM) azsdk-python-azure-mgmt-compute/30.0.0 Python/3.9.14 (Linux-5.4.0-1109-azure-x86_64-with-glibc2.35) cloud-shell/1.0'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/1bc09500-bd2d-4aeb-ac76-2b4c2a50b819/resourceGroups/azuremolchapter14/providers/Microsoft.Compute/virtualMachines/molvmwin?api-version=2022-11-01 HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-resource': 'Microsoft.Compute/LowCostGet3Min;3995,Microsoft.Compute/LowCostGet30Min;31982'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '92303b98-09c0-4114-aa89-076656accc34'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11994'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'e37fb725-58d0-4640-8157-780697ec5233'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'EASTUS:20230921T180653Z:e37fb725-58d0-4640-8157-780697ec5233'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 21 Sep 2023 18:06:52 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "name": "molvmwin",
  "id": "/subscriptions/1bc09500-bd2d-4aeb-ac76-2b4c2a50b819/resourceGroups/azuremolchapter14/providers/Microsoft.Compute/virtualMachines/molvmwin",
  "type": "Microsoft.Compute/virtualMachines",
  "location": "eastus",
  "tags": {},
  "properties": {
    "hardwareProfile": {
      "vmSize": "Standard_D2s_v3"
    },
    "provisioningState": "Succeeded",
    "vmId": "b26a48b6-dea2-4706-87de-b098a8de6bbb",
    "storageProfile": {
      "imageReference": {
        "publisher": "MicrosoftWindowsServer",
        "offer": "WindowsServer",
        "sku": "2022-Datacenter",
        "version": "latest",
        "exactVersion": "20348.1970.230905"
      },
      "osDisk": {
        "osType": "Windows",
        "name": "molvmwin_disk1_dd35b33856a94fd2802b4bade9006f13",
        "createOption": "FromImage",
        "caching": "ReadWrite",
        "managedDisk": {
          "id": "/subscriptions/1bc09500-bd2d-4aeb-ac76-2b4c2a50b819/resourceGroups/azuremolchapter14/providers/Microsoft.Compute/disks/molvmwin_disk1_dd35b33856a94fd2802b4bade9006f13"
        },
        "deleteOption": "Detach"
      },
      "dataDisks": []
    },
    "osProfile": {
      "computerName": "molvmwin",
      "adminUsername": "mackswift",
      "windowsConfiguration": {
        "provisionVMAgent": true,
        "enableAutomaticUpdates": true,
        "patchSettings": {
          "patchMode": "AutomaticByOS",
          "assessmentMode": "ImageDefault"
        },
        "enableVMAgentPlatformUpdates": false
      },
      "secrets": [],
      "allowExtensionOperations": true,
      "requireGuestProvisionSignal": true
    },
    "networkProfile": {"networkInterfaces":[{"id":"/subscriptions/1bc09500-bd2d-4aeb-ac76-2b4c2a50b819/resourceGroups/azuremolchapter14/providers/Microsoft.Network/networkInterfaces/molvmwinVMNic"}]},
    "timeCreated": "2023-09-21T17:40:08.5196467+00:00"
  }
}
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=KeyVaultManagementClient
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2172
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: MSIAuthenticationWrapper.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2172
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: Normalize expires_on: '1695321582' -> 1695321582
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/1bc09500-bd2d-4aeb-ac76-2b4c2a50b819/resourceGroups/azuremolchapter14/providers/Microsoft.KeyVault/vaults/azuremolch14keyvault?api-version=2023-02-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'a4454002-58a9-11ee-a8ec-8203de4bc7be'
cli.azure.cli.core.sdk.policies:     'CommandName': 'vm encryption enable'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --name --disk-encryption-keyvault --key-encryption-key --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.52.0 (RPM) azsdk-python-azure-mgmt-keyvault/10.2.3 Python/3.9.14 (Linux-5.4.0-1109-azure-x86_64-with-glibc2.35) cloud-shell/1.0'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/1bc09500-bd2d-4aeb-ac76-2b4c2a50b819/resourceGroups/azuremolchapter14/providers/Microsoft.KeyVault/vaults/azuremolch14keyvault?api-version=2023-02-01 HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'a4454002-58a9-11ee-a8ec-8203de4bc7be'
cli.azure.cli.core.sdk.policies:     'x-ms-keyvault-service-version': '1.5.914.0'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'd61277ff-8a86-4c3e-a697-bde38e235efe'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-IIS/10.0'
cli.azure.cli.core.sdk.policies:     'X-AspNet-Version': '4.0.30319'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11994'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '186d0001-f760-4826-b6c2-3c245ba32048'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'EASTUS:20230921T180653Z:186d0001-f760-4826-b6c2-3c245ba32048'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 21 Sep 2023 18:06:53 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"id":"/subscriptions/1bc09500-bd2d-4aeb-ac76-2b4c2a50b819/resourceGroups/azuremolchapter14/providers/Microsoft.KeyVault/vaults/azuremolch14keyvault","name":"azuremolch14keyvault","type":"Microsoft.KeyVault/vaults","location":"eastus","tags":{},"systemData":{"createdBy":"mackswift@hotmail.com","createdByType":"User","createdAt":"2023-09-21T16:16:13.912Z","lastModifiedBy":"mackswift@hotmail.com","lastModifiedByType":"User","lastModifiedAt":"2023-09-21T16:16:13.912Z"},"properties":{"sku":{"family":"A","name":"standard"},"tenantId":"56e7a889-f84c-4b0b-8b98-3d8280c0ce4c","accessPolicies":[{"tenantId":"56e7a889-f84c-4b0b-8b98-3d8280c0ce4c","objectId":"10f297ef-fadd-4ec2-96fc-eda471377545","permissions":{"keys":["all"],"secrets":["all"],"certificates":["all"],"storage":["all"]}}],"enabledForDeployment":false,"enabledForDiskEncryption":true,"enableSoftDelete":true,"softDeleteRetentionInDays":90,"vaultUri":"https://azuremolch14keyvault.vault.azure.net/","provisioningState":"Succeeded","publicNetworkAccess":"Enabled"}}
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2172
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/vm/disk_encryption.py", line 118, in encrypt_vm
    key_encryption_key = _get_keyvault_key_url(
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/vm/disk_encryption.py", line 367, in _get_keyvault_key_url
    result = client.get_key(key_name)
AttributeError: 'CertificateClient' object has no attribute 'get_key'

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: 'CertificateClient' object has no attribute 'get_key'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/vm/disk_encryption.py", line 118, in encrypt_vm
    key_encryption_key = _get_keyvault_key_url(
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/vm/disk_encryption.py", line 367, in _get_keyvault_key_url
    result = client.get_key(key_name)
AttributeError: 'CertificateClient' object has no attribute 'get_key'
az_command_data_logger: 'CertificateClient' object has no attribute 'get_key'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/vm/disk_encryption.py", line 118, in encrypt_vm
    key_encryption_key = _get_keyvault_key_url(
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/vm/disk_encryption.py", line 367, in _get_keyvault_key_url
    result = client.get_key(key_name)
AttributeError: 'CertificateClient' object has no attribute 'get_key'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f5bdf644670>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.970 seconds (init: 0.125, invoke: 0.845)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 7322 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/bin/python3.9 /usr/lib/az/lib/python3.9/site-packages/azure/cli/telemetry/__init__.py /home/mack/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

The command was supposed to result in the encryption of my VMs using a newly created key stored in the Azure Key Vault.

### Environment Summary

azure-cli                         2.52.0

core                              2.52.0
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
ml                                2.20.0
ssh                                2.0.1

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.9'
Extensions directory '/home/mack/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.14 (main, Feb  8 2023, 03:39:52) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

I've also attempted to re-register EncryptionAtHost with the following command in Powershell - Register-AzProviderFeature -FeatureName "EncryptionAtHost" -ProviderNamespace "Microsoft.Compute".

No luck as the issue remains the same as it was.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by mackswift** [comment]
> Thank you for opening this issue, we will look into it.

Thank you!

**Comment by Gr00tB3ar** [comment]
Hi Team, I did some testing, and this failure is only received if the --key-encryption-key parameter is specified in the command. Otherwise az vm encryption enable command works just fine.

I tested this with 4 different VMs in the same resource group and using same key vault. the only one that failed had that parameter specified.

**Comment by spalnatik** [comment]
Hi Team,

The issue is the latest azure-cli version when I ran the same command (using key) with older azure-cli version it is perfectly working fine.

![MicrosoftTeams-image (4)](https://github.com/Azure/azure-cli/assets/139609488/53f5d8de-0091-4daf-bcbd-9fed2ba159d4)
![MicrosoftTeams-image (3)](https://github.com/Azure/azure-cli/assets/139609488/98d02ae1-5d19-4ea9-a065-88703c7d97fb)
![MicrosoftTeams-image (2)](https://github.com/Azure/azure-cli/assets/139609488/1e898aeb-e3f2-422e-99bd-1c98109311d7)

**Comment by spalnatik** [comment]
Hello Team,

I can still see the same error while kek .

**Comment by yanzhudd** [comment]
> Hello Team,
> 
> I can still see the same error while running az command with kek .

Hi @spalnatik, this fix will be released in the coming new version of CLI around 11-15.
