### ISSUE TITLE
Enable CLI support for ed25519 SSH format on Linux VMs

### ISSUE THREAD

**Issue by srijang** [Azure/azure-cli#27449]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Resource Provider

CRP

### Description of Feature or Work Requested

Our team is currently working to enable support for ed25519 SSH format on Linux VMs. This format will be available on all Linux Images that support OpenSSH format. Once we are live, customers will be able to choose RSA or ed25519 SSH format for Linux VMs. Portals will enable support for ed25519. We are targeting for Public Preview in early to mid December.

### Minimum API Version Required

N/A, We can discuss this once you start working on this request.

### Swagger PR link / SDK link

N/A

We can discuss this once you start working on this request.

### Target Date

12/15/2023

### PM Contact

srijangupta@microsoft.com

### Engineer Contact

Vasanth.Ramani@microsoft.com

### Additional context

We can discuss this once you start working on this request.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yanzhudd** [comment]
is the same as #27708
