### ISSUE TITLE
--node-osdisk-size in CLI is configured to use GB whereas the VMsizes are using GiB which is creating confusion. 

### ISSUE THREAD

**Issue by anilkumar1619** [Azure/azure-cli#27461]
[###]([url](u Describe the bug

Hello Team, 

This is regarding "--node-osdisk-size" parameter in the az aks nodepool add command, which is configured to use the disk measurements in GB whereas the VM SKUs are configured to use GiB which is creating confusion. 

Default disk size measurements for the VM SKUs are mentioned in GiB but "--node-osdisk-size" is creating disk with GB which is creating a confusion because customer is looking to create nodepool with 128Gib disk size but it is creating with less size as the parameters are defined to use GB. Nodepool or VMSS disk size measurement is defined in GiB but this parameters are using GB which is confusing customers. Please do the needful. Please confirm if this is expected. 

### Related command

az aks nodepool add -h

### Errors

No error. 

### Issue script & Debug output

NA

### Expected behavior

NA

### Environment Summary

NA
![vmsizescreenshot](https://github.com/Azure/azure-cli/assets/84578520/b480851b-c214-47c2-8b62-8905b8c7ed78)

### Additional context
![azcliazaksnodepoolhoutput](https://github.com/Azure/azure-cli/assets/84578520/de7a614f-3890-4252-a6db-1b5fcf685b5b)
![disksizescreenshot](https://github.com/Azure/azure-cli/assets/84578520/7459a64e-5ff4-4a2a-b941-663c09309c92)

NA

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by anilkumar1619** [comment]
Hello Team, @dyu1208 @FumingZhang @andyliuliming. Kindly assist.

**Comment by anilkumar1619** [comment]
@FumingZhang Thank you for the response. Any ETA on the fix.

**Comment by FumingZhang** [comment]
The upcoming azure-cli release is on [11/15](https://github.com/Azure/azure-cli/milestone/135)
