### ISSUE TITLE
Add ouput to examples

### ISSUE THREAD

**Issue by asaltv** [Azure/azure-cli#27463]
**Related command**

all of the above

**Is your feature request related to a problem? Please describe.**

I have to test with actual data to see what is output.

**Describe the solution you'd like**

Similar below to all commands.
IE:
az postgres flexible-server firewall-rule list -g testgroup -n testsvr

add ouput:
[
  {
    "endIpAddress": "XXX.XXX.XXX.XXX",
    "id": "/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/testgroup/providers/Microsoft.DBforPostgreSQL/flexibleServers/testsvr/firewallRules/ruleName",
    "name": "ruleName",
    "resourceGroup": "testgroup",
    "startIpAddress": "XXX.XXX.XXX.XXX",
    "systemData": null,
    "type": "Microsoft.DBforPostgreSQL/flexibleServers/firewallRules"
  },
  {
    "endIpAddress": "XXX.XXX.XXX.XXX",
    "id": "/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/testgroup/providers/Microsoft.DBforPostgreSQL/flexibleServers/testsvr/firewallRules/ruleName2",
    "name": "ruleName2",
    "resourceGroup": "testgroup",
    "startIpAddress": "XXX.XXX.XXX.XXX",
    "systemData": null,
    "type": "Microsoft.DBforPostgreSQL/flexibleServers/firewallRules"
  },
]
**Describe alternatives you've considered**

N/A
**Additional context**

N/A

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@asaltv Thanks for reaching out to us and reporting this issue. Example and sample output cannot be added for all the CLI commands. Instead you can leverage the sample response documented in the REST API documentation as shown below:

https://learn.microsoft.com/en-us/rest/api/postgresql/flexibleserver/firewall-rules/list-by-server?tabs=HTTP#firewallrulelist

Hope this helps.

**Comment by asaltv** [comment]
/unresolve

Can you confirm that the rest API is **always** returning the same as the CLI commands do?
When developing solutions it is very tedious to have to spin-up environments just to confirm the command behavior.

**Comment by navba-MSFT** [comment]
@asaltv Thanks for getting back. The Azure CLI underneath calls the same above rest api. To confirm, you can run the same az cli command with` --debug` switch.

**Comment by asaltv** [comment]
Then you should add that to the documentation :)

**Comment by nachoalonsoportillo** [comment]
@yonzhan Please close this one. Request is addressed with #4374.
