### ISSUE TITLE
Creating service connector local connection to postgres failed

### ISSUE THREAD

**Issue by hui1110** [Azure/azure-cli#27469]
### Describe the bug

Call the [Azure CLI command line](https://learn.microsoft.com/en-us/cli/azure/connection/create?view=azure-cli-latest#az-connection-create-postgres(serviceconnector-passwordless)) in the documentation to create a Service Connector local connection to Postgres.

I get the following error:

```text
Command execution failed, command is: az postgres server db show --ids /subscriptions/799c12ba-353c-44a1-883d-84808ebb2216/resourceGroups/postgres-bug-rg/providers/Microsoft.DBforPostgreSQL/servers/postgresqlsingletest0/databases/demo, error message is:
 ERROR: 'db' is misspelled or not recognized by the system.

Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs
```

### Related command

```azure CLI
az connection create postgres --resource-group <resource_group> --connection postgres_conn --target-resource-group <resource_group> --server <server_name> --database <db_name> --user-account
```

### Errors

```
The behavior of this command has been altered by the following extension: serviceconnector-passwordless
Client type is not specified, use default one: --client-type none
Command execution failed, command is: az postgres server db show --ids /subscriptions/799c12ba-353c-44a1-883d-84808ebb2216/resourceGroups/postgres-bug-rg/providers/Microsoft.DBforPostgreSQL/servers/postgresqlsingletest0/databases/demo, error message is:
 ERROR: 'db' is misspelled or not recognized by the system.

Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs
```

### Issue script & Debug output

If I run the following code:

```
az postgres db show --name <db_name> --ids <ids>
```
I can see the database and server are there and valid:

```
{
  "charset": "UTF8",
  "collation": "English_United States.1252",
  "id": "/subscriptions/799c12ba-353c-44a1-883d-84808ebb2216/resourceGroups/postgres-bug-rg/providers/Microsoft.DBforPostgreSQL/servers/postgresqlsingletest0/databases/demo",
  "name": "demo",
  "resourceGroup": "postgres-rg",
  "type": "Microsoft.DBforPostgreSQL/servers/databases"
}
```

### Expected behavior

Service connector local connection to Postgres can be created successfully.

### Environment Summary

- azure-cli:  2.53.0
- Extension 'serviceconnector-passwordless':  0.3.9

### Additional context

In documents [az postgres db](https://learn.microsoft.com/en-us/cli/azure/postgres/db?view=azure-cli-latest#az-postgres-db-show()) and [az postgres server](https://learn.microsoft.com/en-us/cli/azure/postgres/server?view=azure-cli-latest), I did not find the relevant command of `az postgres server db show`. Did I miss anything?

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by xfz11** [comment]
@hui1110 Thanks for your feedback. The issue is fixed. Feel free to try again.
