### ISSUE TITLE
DOCKER_PULL_ERROR when acr check-health for macOS

### ISSUE THREAD

**Issue by ealtuna** [Azure/azure-cli#27487]
### Describe the bug

I am the owner of a Azure Container Registry, I am logged in in the AZ CLI using the organization SSO. I can list the registries with **_az acr list_** and see the one I am interested in. However, when I try to login with **_az acr login --name NAME_**, I get the error:

```
Could not connect to the registry login server 'NAME.azurecr.io'. Please verify that the registry exists and the URL 'https://NAME.azurecr.io/v2/' is reachable from your environment.
Try running 'az acr check-health -n NAME --yes' to diagnose this issue.
```

I can paste the URL in the browser and I get access.

When I run **_az acr check-health -n NAME --yes_** I get the error:

```
Docker daemon status: available
Docker version: 'Docker version 24.0.6, build 1a79695, platform linux/arm64'
2023-09-27 20:58:15.600238 An error occurred: DOCKER_PULL_ERROR
An error occurred while pulling a sample image. Please validate your network connection and verify if Docker daemon is running properly.
Failed to run command 'docker pull mcr.microsoft.com/mcr/hello-world:latest'. 
What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview mcr.microsoft.com/mcr/hello-world:latest

Please refer to https://aka.ms/acr/errors#docker_pull_error for more information.
```

But the thing is I can successfully run the docker command standlone:

`docker pull mcr.microsoft.com/mcr/hello-world:latest`

```
latest: Pulling from mcr/hello-world
1b930d010525: Pull complete 
Digest: sha256:92c7f9c92844bbbb5d0a101b22f7c2a7949e40f8ea90c8b3bc396879d95e899a
Status: Downloaded newer image for mcr.microsoft.com/mcr/hello-world:latest
mcr.microsoft.com/mcr/hello-world:latest
```

### Related command

az acr login --name NAME
az acr check-health -n NAME --yes

### Errors

Docker daemon status: available
Docker version: 'Docker version 24.0.6, build 1a79695, platform linux/arm64'
2023-09-27 20:58:15.600238 An error occurred: DOCKER_PULL_ERROR
An error occurred while pulling a sample image. Please validate your network connection and verify if Docker daemon is running properly.
Failed to run command 'docker pull mcr.microsoft.com/mcr/hello-world:latest'. 
What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview mcr.microsoft.com/mcr/hello-world:latest

Please refer to https://aka.ms/acr/errors#docker_pull_error for more information.

### Issue script & Debug output

az acr check-health -n NAME --yes --debug
cli.knack.cli: Command arguments: ['acr', 'check-health', '-n', 'NAME', '--yes', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x105cae4d0>, <function OutputProducer.on_global_arguments at 0x105d43490>, <function CLIQuery.on_global_arguments at 0x105dac940>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'acr': ['azure.cli.command_modules.acr']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: acr                       0.071        34       144
cli.azure.cli.core: Total (1)                 0.071        34       144
cli.azure.cli.core: Loaded 34 groups, 144 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : acr check-health
cli.azure.cli.core: Command table: acr check-health
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x10685add0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/USER_HOME/.azure/commands/2023-09-27.17-03-17.acr_check-health.54192.log'.
az_command_data_logger: command args: acr check-health -n {} --yes --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x106951360>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x1069513f0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x106951510>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x105d43520>, <function CLIQuery.handle_query_parameter at 0x105dac9d0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x106951480>]
cli.azure.cli.command_modules.acr.check_health: Docker daemon status: available
cli.azure.cli.command_modules.acr.check_health: Docker version: 'Docker version 24.0.6, build 1a79695, platform linux/arm64'
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.53.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.53.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.53.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.53.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.53.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.53.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.53.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acr/check_health.py", line 431, in acr_check_health
    _get_docker_status_and_version(ignore_errors, yes)
  File "/opt/homebrew/Cellar/azure-cli/2.53.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acr/check_health.py", line 114, in _get_docker_status_and_version
    _handle_error(DOCKER_PULL_ERROR.append_error_message(stderr), ignore_errors)
  File "/opt/homebrew/Cellar/azure-cli/2.53.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/acr/check_health.py", line 41, in _handle_error
    raise CLIError(error.get_error_message(error_msg))
knack.util.CLIError: 2023-09-27 21:03:22.063096 An error occurred: DOCKER_PULL_ERROR
An error occurred while pulling a sample image. Please validate your network connection and verify if Docker daemon is running properly.
Failed to run command 'docker pull mcr.microsoft.com/mcr/hello-world:latest'. 
What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview mcr.microsoft.com/mcr/hello-world:latest

Please refer to https://aka.ms/acr/errors#docker_pull_error for more information.

cli.azure.cli.core.azclierror: 2023-09-27 21:03:22.063096 An error occurred: DOCKER_PULL_ERROR
An error occurred while pulling a sample image. Please validate your network connection and verify if Docker daemon is running properly.
Failed to run command 'docker pull mcr.microsoft.com/mcr/hello-world:latest'. 
What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview mcr.microsoft.com/mcr/hello-world:latest

Please refer to https://aka.ms/acr/errors#docker_pull_error for more information.
az_command_data_logger: 2023-09-27 21:03:22.063096 An error occurred: DOCKER_PULL_ERROR
An error occurred while pulling a sample image. Please validate your network connection and verify if Docker daemon is running properly.
Failed to run command 'docker pull mcr.microsoft.com/mcr/hello-world:latest'. 
What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview mcr.microsoft.com/mcr/hello-world:latest

Please refer to https://aka.ms/acr/errors#docker_pull_error for more information.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x10685b010>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 5.138 seconds (init: 0.091, invoke: 5.047)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 4023 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/opt/homebrew/Cellar/azure-cli/2.53.0/libexec/bin/python /opt/homebrew/Cellar/azure-cli/2.53.0/libexec/lib/python3.10/site-packages/azure/cli/telemetry/__init__.py /Users/USER_HOMR/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

I should be able to authenticate with ACR.

### Environment Summary

azure-cli                         2.53.0

core                              2.53.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/opt/homebrew/Cellar/azure-cli/2.53.0/libexec/bin/python'
Extensions directory '/Users/USER_HOME/.azure/cliextensions'

Python (Darwin) 3.10.13 (main, Aug 24 2023, 22:36:46) [Clang 14.0.3 (clang-1403.0.22.14.1)]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by ealtuna** [comment]
From the error messages I don't see any relation between my issue and the one related with notary.

**Comment by rukmal** [comment]
+1, we @renxyzinc are also impacted by this issue.

**Comment by AntonioVT** [comment]
Hi @ealtuna, 

Could you confirm if this issue happens using CLI only.
You could try listing repositories using the Azure Portal (this will perform acr login as well)

**Comment by ealtuna** [comment]
Hi @AntonioVT, if you are asking if I can go in the Azure Portal UI and list the ACRs, the answer is yes. I can also list the repositories inside the registry.

**Comment by mabenedi** [comment]
Please update your docker client to the latest version and see if you’re still experiencing the error.

**Comment by ealtuna** [comment]
Upgrading to 4.25.0,126437 and experiencing the same error.

**Comment by Wwwsylvia** [comment]
We are able to reproduce this issue on Mac and will work on a fix.
