### ISSUE TITLE
`ModuleNotFoundError: No module named 'uamqp.message'` when running `az iot hub monitor-events` in Azure portal CLI

### ISSUE THREAD

**Issue by tobias-talaj** [Azure/azure-cli#27499]
### Describe the bug

I'm experiencing a problem when running the `az iot hub monitor-events` command in the Azure portal CLI. The error message is `ModuleNotFoundError: No module named 'uamqp.message'`.

### Related command

az iot hub monitor-events -n MyIotHub

### Errors

The command failed with an unexpected error. Here is the traceback:
No module named 'uamqp.message'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/tobiasz/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 2548, in iot_hub_monitor_events
    _iot_hub_monitor_events(
  File "/home/tobiasz/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 2661, in _iot_hub_monitor_events
    from azext_iot.monitor.handlers import CommonHandler
  File "/home/tobiasz/.azure/cliextensions/azure-iot/azext_iot/monitor/handlers/__init__.py", line 7, in <module>
    from azext_iot.monitor.handlers.common_handler import CommonHandler
  File "/home/tobiasz/.azure/cliextensions/azure-iot/azext_iot/monitor/handlers/common_handler.py", line 12, in <module>
    from azext_iot.monitor.parsers.common_parser import CommonParser
  File "/home/tobiasz/.azure/cliextensions/azure-iot/azext_iot/monitor/parsers/common_parser.py", line 12, in <module>
    from uamqp.message import Message
ModuleNotFoundError: No module named 'uamqp.message'

### Issue script & Debug output

cli.knack.cli: Command arguments: ['iot', 'hub', 'monitor-events', '-n', 'MyIotHub', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f30ca6bf1f0>, <function OutputProducer.on_global_arguments at 0x7f30ca5d9d30>, <function CLIQuery.on_global_arguments at 0x7f30ca571310>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'iot': ['azure.cli.command_modules.iot', 'azext_iot']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: iot                       0.177        19        82
cli.azure.cli.core: Total (1)                 0.177        19        82
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: ai-examples               0.068         1         1  /usr/lib/python3.9/site-packages/azure-cli-extensions/ai-examples
cli.azure.cli.core: azure-iot                 0.018       103       337  /home/tobiasz/.azure/cliextensions/azure-iot
cli.azure.cli.core: Total (2)                 0.086       104       338  
cli.azure.cli.core: Loaded 118 groups, 420 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : iot hub monitor-events
cli.azure.cli.core: Command table: iot hub monitor-events
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f30c9a14430>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/tobiasz/.azure/commands/2023-09-29.10-23-17.iot_hub_monitor-events.345.log'.
az_command_data_logger: command args: iot hub monitor-events -n {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f30c99bf040>]
cli.azure.cli.core: Current cloud config:
AzureCloud
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f30c99ef0d0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f30c99f7ee0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f30ca5d9dc0>, <function CLIQuery.handle_query_parameter at 0x7f30ca5713a0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f30c99f7e50>, <function handler at 0x7f30c999d9d0>]
az_command_data_logger: extension name: azure-iot
az_command_data_logger: extension version: 0.21.5
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=IotHubClient
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2105
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: MSIAuthenticationWrapper.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2105
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: Normalize expires_on: '1695987099' -> 1695987099
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/a963b753-c0a6-4cfc-a8f2-1a79e2fbad41/providers/Microsoft.Devices/IotHubs?api-version=2022-04-30-preview'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '343399b2-5eb2-11ee-bb9c-caa0ffeaa33c'
cli.azure.cli.core.sdk.policies:     'CommandName': 'iot hub monitor-events'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-n --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.53.0 (RPM) azsdk-python-azure-mgmt-iothub/2.3.0 Python/3.9.14 (Linux-5.4.0-1109-azure-x86_64-with-glibc2.35) cloud-shell/1.0'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/a963b753-c0a6-4cfc-a8f2-1a79e2fbad41/providers/Microsoft.Devices/IotHubs?api-version=2022-04-30-preview HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11996'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '262f0760-4870-4be2-a06b-d5f6de0094ed'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '262f0760-4870-4be2-a06b-d5f6de0094ed'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'NORTHEUROPE:20230929T102317Z:262f0760-4870-4be2-a06b-d5f6de0094ed'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Fri, 29 Sep 2023 10:23:17 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"value":[{"id":"/subscriptions/a963b753-c0a6-4cfc-a8f2-1a79e2fbad41/resourceGroups/TestingGroup/providers/Microsoft.Devices/IotHubs/MyIotHub","name":"MyIotHub","type":"Microsoft.Devices/IotHubs","location":"westeurope","tags":{},"subscriptionid":"a963b753-c0a6-4cfc-a8f2-1a79e2fbad41","resourcegroup":"TestingGroup","etag":"AAAADH9LVqM=","properties":{"locations":[{"location":"West Europe","role":"primary"},{"location":"North Europe","role":"secondary"}],"state":"Active","provisioningState":"Succeeded","ipFilterRules":[],"hostName":"MyIotHub.azure-devices.net","eventHubEndpoints":{"events":{"retentionTimeInDays":1,"partitionCount":4,"partitionIds":["0","1","2","3"],"path":"myiothub","endpoint":"sb://iothub-ns-testingenb-25253250-d6af042441.servicebus.windows.net/"}},"routing":{"endpoints":{"serviceBusQueues":[],"serviceBusTopics":[],"eventHubs":[],"storageContainers":[],"cosmosDBSqlCollections":[]},"routes":[],"fallbackRoute":{"name":"$fallback","source":"DeviceMessages","condition":"true","endpointNames":["events"],"isEnabled":true}},"storageEndpoints":{"$default":{"sasTtlAsIso8601":"PT1H","connectionString":"","containerName":""}},"messagingEndpoints":{"fileNotifications":{"lockDurationAsIso8601":"PT5S","ttlAsIso8601":"PT1H","maxDeliveryCount":10}},"enableFileUploadNotifications":false,"cloudToDevice":{"maxDeliveryCount":10,"defaultTtlAsIso8601":"PT1H","feedback":{"lockDurationAsIso8601":"PT5S","ttlAsIso8601":"PT1H","maxDeliveryCount":10}},"features":"None","allowedFqdnList":[]},"sku":{"name":"S1","tier":"Standard","capacity":1},"identity":{"type":"None"},"systemData":{"createdAt":"2023-09-19T09:51:03.79Z"}}]}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/a963b753-c0a6-4cfc-a8f2-1a79e2fbad41/resourceGroups/TestingGroup/providers/Microsoft.Devices/IotHubs/MyIotHub/listkeys?api-version=2022-04-30-preview'
cli.azure.cli.core.sdk.policies: Request method: 'POST'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '343399b2-5eb2-11ee-bb9c-caa0ffeaa33c'
cli.azure.cli.core.sdk.policies:     'CommandName': 'iot hub monitor-events'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-n --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.53.0 (RPM) azsdk-python-azure-mgmt-iothub/2.3.0 Python/3.9.14 (Linux-5.4.0-1109-azure-x86_64-with-glibc2.35) cloud-shell/1.0'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: https://management.azure.com:443 "POST /subscriptions/a963b753-c0a6-4cfc-a8f2-1a79e2fbad41/resourceGroups/TestingGroup/providers/Microsoft.Devices/IotHubs/MyIotHub/listkeys?api-version=2022-04-30-preview HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1198'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'a6380c5a-f0e2-4efc-9c5e-46035504d5af'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'a6380c5a-f0e2-4efc-9c5e-46035504d5af'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'NORTHEUROPE:20230929T102317Z:a6380c5a-f0e2-4efc-9c5e-46035504d5af'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Fri, 29 Sep 2023 10:23:17 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"value":[{"keyName":"iothubowner","primaryKey":"+eLrPlnHFYKSqYGqyP3T8UdFQnUib1VM2AIoTKmK1Ts=","secondaryKey":"Tz3oqKcCF4gjGZeqgJqkawyJTOdV8j87jAIoTHS5t38=","rights":"RegistryWrite, ServiceConnect, DeviceConnect"},{"keyName":"service","primaryKey":"xR90GUB19xHCOcJBIXwr8SUGF2xswPZS0AIoTC5m3Rw=","secondaryKey":"tHICvzBqN7CbdMkDTfFPtT1FOyeto0h8iAIoTJK5lwM=","rights":"ServiceConnect"},{"keyName":"device","primaryKey":"dufJAAE1yEsPuBYZkRKhE45vR0yaLvbbpAIoTJjMiKY=","secondaryKey":"wjd17+PmSgQlmwOIfXF5TVHhBoyrhndvKAIoTNuqt20=","rights":"DeviceConnect"},{"keyName":"registryRead","primaryKey":"dOKY4ZX3kgsrSs6oz9p/FEywTswtkSMCPAIoTPfjgYo=","secondaryKey":"Tt1QbW38G39BuxNBaw3XhhT/hJ6P4v5yJAIoTCw8VjM=","rights":"RegistryRead"},{"keyName":"registryReadWrite","primaryKey":"qSBlaL9g0oNUuCoIClq7/BNZgvFOHuE2jAIoTH33k30=","secondaryKey":"+hX3H9PIEIPvRPhc0XHtXFUWna8piOg28AIoTIRSPXQ=","rights":"RegistryWrite"}]}
cli.azext_iot.common.base_discovery: Using policy 'iothubowner' for IoT Hub interaction.
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/tobiasz/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 2548, in iot_hub_monitor_events
    _iot_hub_monitor_events(
  File "/home/tobiasz/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 2661, in _iot_hub_monitor_events
    from azext_iot.monitor.handlers import CommonHandler
  File "/home/tobiasz/.azure/cliextensions/azure-iot/azext_iot/monitor/handlers/__init__.py", line 7, in <module>
    from azext_iot.monitor.handlers.common_handler import CommonHandler
  File "/home/tobiasz/.azure/cliextensions/azure-iot/azext_iot/monitor/handlers/common_handler.py", line 12, in <module>
    from azext_iot.monitor.parsers.common_parser import CommonParser
  File "/home/tobiasz/.azure/cliextensions/azure-iot/azext_iot/monitor/parsers/common_parser.py", line 12, in <module>
    from uamqp.message import Message
ModuleNotFoundError: No module named 'uamqp.message'

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: No module named 'uamqp.message'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/tobiasz/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 2548, in iot_hub_monitor_events
    _iot_hub_monitor_events(
  File "/home/tobiasz/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 2661, in _iot_hub_monitor_events
    from azext_iot.monitor.handlers import CommonHandler
  File "/home/tobiasz/.azure/cliextensions/azure-iot/azext_iot/monitor/handlers/__init__.py", line 7, in <module>
    from azext_iot.monitor.handlers.common_handler import CommonHandler
  File "/home/tobiasz/.azure/cliextensions/azure-iot/azext_iot/monitor/handlers/common_handler.py", line 12, in <module>
    from azext_iot.monitor.parsers.common_parser import CommonParser
  File "/home/tobiasz/.azure/cliextensions/azure-iot/azext_iot/monitor/parsers/common_parser.py", line 12, in <module>
    from uamqp.message import Message
ModuleNotFoundError: No module named 'uamqp.message'
az_command_data_logger: No module named 'uamqp.message'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/tobiasz/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 2548, in iot_hub_monitor_events
    _iot_hub_monitor_events(
  File "/home/tobiasz/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 2661, in _iot_hub_monitor_events
    from azext_iot.monitor.handlers import CommonHandler
  File "/home/tobiasz/.azure/cliextensions/azure-iot/azext_iot/monitor/handlers/__init__.py", line 7, in <module>
    from azext_iot.monitor.handlers.common_handler import CommonHandler
  File "/home/tobiasz/.azure/cliextensions/azure-iot/azext_iot/monitor/handlers/common_handler.py", line 12, in <module>
    from azext_iot.monitor.parsers.common_parser import CommonParser
  File "/home/tobiasz/.azure/cliextensions/azure-iot/azext_iot/monitor/parsers/common_parser.py", line 12, in <module>
    from uamqp.message import Message
ModuleNotFoundError: No module named 'uamqp.message'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f30c9a14670>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.326 seconds (init: 0.114, invoke: 1.212)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 7307 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/bin/python3.9 /usr/lib/az/lib/python3.9/site-packages/azure/cli/telemetry/__init__.py /home/tobiasz/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

The command should run without errors, and I would be able to monitor IoT hub events.

### Environment Summary

- Azure CLI version: 2.53.0
- Python version: 3.9.14
- OS: Linux (Azure portal)
- Extensions: 
  - ai-examples: 0.2.5
  - azure-iot: 0.21.5
  - ml: 2.20.0
  - ssh: 2.0.1

### Additional context

I ran pip install uamqp, still the same result
The same command worked without issues about three days ago
I also reset the cli

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by tobias-talaj** [comment]
Reinstallation of azure-iot did the trick. After I reinstalled it I got dependency update (uamqp 1.2) and now it works as expected.
