### ISSUE TITLE
Failed to install az cli with apt-get

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Azure/azure-cli#2749]
As of last night, the az cli is failing to install for me through apt-get. I'm follow the instructions [here](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli):

```
echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/azure-cli/ wheezy main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
sudo apt-get install apt-transport-https
sudo apt-get update && sudo apt-get install azure-cli
```

It's failing at the last step:
```
<removing most of the log>
Hit http://security.ubuntu.com trusty-security/main amd64 Packages
Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
Err https://apt-mo.trafficmanager.net wheezy/main amd64 Packages
  gnutls_handshake() failed: Handshake failed
Ign https://apt-mo.trafficmanager.net wheezy/main Translation-en_US
Hit http://security.ubuntu.com trusty-security/main Translation-en
Ign https://apt-mo.trafficmanager.net wheezy/main Translation-en
Hit http://security.ubuntu.com trusty-security/universe Translation-en
W: Failed to fetch https://apt-mo.trafficmanager.net/repos/azure-cli/dists/wheezy/main/binary-amd64/Packages  gnutls_handshake() failed: Handshake failed

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

I reproduced this on a clean Ubuntu 14.04 VM

NOTE: It succeeds if I do `curl -L https://aka.ms/InstallAzureCli | bash`, but we using the cli in some automation scenarios and I believe that script requires interaction, correct? Can I pass it parameters so that it doesn't prompt me?

**Comment by derekbekoe** [comment]
@EricJizbaMSFT I'm taking a look.
As a work around, you can download the .deb file straight from blob storage.
https://azurecliprod.blob.core.windows.net/repos/azure-cli_0.2.4-1_all.deb
Install with:
`sudo dpkg -i azure-cli_0.2.4-1_all.deb`

**Comment by derekbekoe** [comment]
This has been fixed. An update was pushed server-side. Thanks for the bug report.

**Comment by EricJizbaMSFT** [comment]
Thanks for the fix! I verified it's working for me now
