### ISSUE TITLE
run az webapp deployment source config-zip is failed

### ISSUE THREAD

**Issue by FisherMS** [Azure/azure-cli#27504]
### Describe the bug

```powershell

az login --username $Username --password $Password

Write-Host "Login ok"

$webappRGNam = "dev-sampleweb"
$webappName = "webapp"
$firstFile = "F:\WebApp\webapp-6.3.2-dev.230930.8.zip"

Write-Host "Begin deploy..." ($webappRGNam , $webappName, $firstFile)
az webapp deployment source config-zip --resource-group $webappRGName --name $webappName --src $firstFile

```

### Related command

`az webapp deployment source config-zip --resource-group $webappRGName --name $webappName --src $firstFile`

### Errors

![image](https://github.com/Azure/azure-cli/assets/12068896/d182c539-e7f8-4cc6-83cd-4bc4860d94ae)

### Issue script & Debug output

![image](https://github.com/Azure/azure-cli/assets/12068896/d182c539-e7f8-4cc6-83cd-4bc4860d94ae)

### Expected behavior

deploy success.

### Environment Summary

azure-cli                         2.44.1 *

core                              2.44.1 *
telemetry                          1.0.8 *

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\Yu\.azure\cliextensions'

Python (Windows) 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:37:59) [MSC v.1933 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by FisherMS** [comment]
I update az cli to 2.53.0 and this issue is happen again.
```powershell
argument --resource-group/-g: expected one argument

Examples from AI knowledge base:
az webapp deployment source config-zip --resource-group {myRG} --name {myAppName} --src {zipFilePathLocation}
Perform deployment by using zip file content.

az webapp deployment source config-zip --name MyWebapp --resource-group MyResourceGroup --slot staging --src {zipFilePathLocation}
Perform deployment using the kudu zip push deployment for a web app. (autogenerated)

https://docs.microsoft.com/en-US/cli/azure/webapp/deployment/source#az_webapp_deployment_source_config_zip
Read more about the command in reference docs
PS F:\AzDeployment> az -v
azure-cli                         2.53.0

core                              2.53.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\Yu\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal
```

**Comment by btardif** [comment]
@jvano / @tulikac can you guys take a look not sure if this is on the zip deploy or CLI side

**Comment by dannysongg** [comment]
Hi @FisherMS 
It looks like you have a typo in your script. You are defining $webappRGNam but passing $webappRGName as the parameter.

**Comment by btardif** [comment]
closing this issue based on @dannysongg comment
