### ISSUE TITLE
az ml job list not show all jobs with --parent-job-name

### ISSUE THREAD

**Issue by yufang67** [Azure/azure-cli#27502]
### Describe the bug

I would like to show all jobs running in a pipelines (around 100 children jobs). 
when i use 
az ml job list --query "[].{Name:name,Jobstatus:status}" --output table -g <rg> -w <ws> --subscription <sub> --parent-job-name <jobname> -r 100 | wc -l
it did not show all jobs.

However, if i dont use --parent-job-name <jobname>, it works normally. But in my case, if i dont use --parent-job-name, but query the experiment name, it didn't show all children jobs.

how should it work ?

### Related command

az ml job list --query "[].{Name:name,Jobstatus:status}" --output table -g <rg> -w <ws> --subscription <sub> --parent-job-name <jobname> -r 100 | wc -l

### Errors

No, error message. 

But it gives me only 52 jobs not all jobs (72 jobs).

### Issue script & Debug output
i cant put all logs, because there are too many identity informations. i put the beginning of the log.

DEBUG: cli.knack.cli: Command arguments: ['ml', 'job', 'list', '--query', '[].{Name:name,Jobstatus:status}', '--output', 'json', '-g', 'xx', '-w', 'xx', '--subscription', 'xx', '--parent-job-name', 'xx', '--debug']
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fb8b8926f80>, <function OutputProducer.on_global_arguments at 0x7fb8b8863370>, <funct
ion CLIQuery.on_global_arguments at 0x7fb8b86a8670>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Modules found from index for 'ml': ['azext_mlv2']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: Total (0)                 0.000         0         0
DEBUG: cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
DEBUG: cli.azure.cli.core: Loading extensions:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
DEBUG: azext_mlv2.manual.vendored_curated_sdk.azure.ai.ml._azure_environments: Using the default cloud configuration: 'AzureCloud'.
DEBUG: azext_mlv2.manual.vendored_curated_sdk.azure.ai.ml._azure_environments: Using the default cloud configuration: 'AzureCloud'.
DEBUG: azext_mlv2.manual.vendored_curated_sdk.azure.ai.ml._azure_environments: Using the default cloud configuration: 'AzureCloud'.
DEBUG: cli.azure.cli.core: ml                        3.011        20       138  /home/xx
DEBUG: cli.azure.cli.core: Total (1)                 3.011        20       138  
DEBUG: cli.azure.cli.core: Loaded 20 groups, 138 commands.
DEBUG: cli.azure.cli.core: Found a match in the command table.
DEBUG: cli.azure.cli.core: Raw command  : ml job list
DEBUG: cli.azure.cli.core: Command table: ml job list
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fb8b7b43490>]
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/xx.log'.
INFO: az_command_data_logger: command args: ml job list --query {} --output {} -g {} -w {} --subscription {} --parent-job-name {} --debug
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fb8b7b74040>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7fb8b7bb6680>, <function register_cache_arguments.<locals>.add_cac
he_arguments at 0x7fb8b7bb67a0>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fb8b8863400>, <function CLIQuery.handle_query_parameter at 0x7fb8b86a8700>, <function
register_ids_argument.<locals>.parse_ids_arguments at 0x7fb8b7bb6710>]
INFO: az_command_data_logger: extension name: ml
INFO: az_command_data_logger: extension version: 2.17.2
DEBUG: cli.azure.cli.core.commands.client_factory: Getting management service client client_type=AzureMachineLearningWorkspaces
DEBUG: cli.azure.cli.core.auth.persistence: build_persistence: location='/home/xx.json', encrypt=False
DEBUG: cli.azure.cli.core.auth.binary_cache: load: /home/xx.bin
DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)

### Expected behavior

show all jobs

### Environment Summary

"azure-cli": "2.51.0",
  "azure-cli-core": "2.51.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "azure-devops": "0.26.0",
    "ml": "2.17.2"

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yufang67** [comment]
any update ? Thanks

**Comment by nemanjarajic** [comment]
Fix to issue has been included for the upcoming February release since January release has been cancelled and December release has been postponed.
