### ISSUE TITLE
azure-cli does not permit new enough azure-cosmos

### ISSUE THREAD

**Issue by hauntsaninja** [Azure/azure-cli#27513]
### Describe the bug

azure-cli does not permit new azure-cosmos versions:  https://github.com/Azure/azure-cli/blob/2e81a4abe15bbe4f5e5058f54ef857910734a706/src/azure-cli/setup.py#L56

It should be possible to install alongside azure-cosmos>=4

### Related command

pip install azure-cli

### Environment Summary

azure-cli 2.53.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
This is by design.

The code is only tested with `azure-cosmos==3.2.0`, we don't know if it is compatible with 4.0.

**Comment by LeszekKalibrate** [comment]
Azure cli using:
 python 3.10 and cosmos 4.6 works
 python 3.11 and cosmos 4.6 blow up... error
