### ISSUE TITLE
Add parameters to az restore-point create to support Encryption Input

### ISSUE THREAD

**Issue by linugeorgeofficial** [Azure/azure-cli#27520]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az restore-point create

### Resource Provider

Microsoft.Compute

### Description of Feature or Work Requested

- When a restore point is created using 'az restore-point create' be it a local restore point or a remote restore point, customer should be able to specify Encryption details for the new disk restore point. For each source disk / disk restore point that user wants to change encryption for, they should be able to pass encryption type and/or disk encryption set id.

- These are optional parameters, if they are not specified by the customer, the default encryption is used for the new restore point.

### Minimum API Version Required

2023-03-01

### Swagger PR link / SDK link

1. Restore Points in the REST API specs repo: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-07-01/restorePoint.json
3. Corresponding PR: https://github.com/Azure/azure-rest-api-specs/pull/23303 (included in https://github.com/Azure/azure-rest-api-specs/pull/22885)
5. SDK Docs: https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.restorepoint?view=azure-dotnet-legacy&viewFallbackFrom=azure-dotnet

### Request Example

There are 2 scenarios

**a) Local Restore Point**

- `--source-restore-point` is not passed
- In this case, the source-data-disk-resource should have zero or more Disk ARM ID's.
- For each Disk ARM ID, its corresponding EncryptionSetId or/and EncryptionType must be passed.
- For Example, if the cli request contains the following values for the new parameters
```powershell
az restore-point create --resource-group "linurg" --collection-name "rpc-1" --name "rp-1" --source-os-resource "/subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/disks/vm1_osDisk" --os-restore-point-encryption-set "/subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/diskEncryptionSets/des1" --source-data-disk-resource "/subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/disks/vm1_DataDisk_0 /subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/disks/vm1_DataDisk_2" --data-disk-restore-point-encryption-set "/subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/diskEncryptionSets/des1 /subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/diskEncryptionSets/des2"
```
The Restore Point API request body should look like the following:
```json
{
  "name": "rp-1",
  "properties": {
    "sourceMetadata": {
      "storageProfile": {
        "osDisk": {
          "managedDisk": {
            "id": "/subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/disks/vm1_osDisk"
          },
          "diskRestorePoint": {
            "encryption": {
              "diskEncryptionSet": {
                "id": "/subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/diskEncryptionSets/des1"
              }
            }
          }
        },
        "dataDisks": [
          {
            "managedDisk": {
              "id": "/subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/disks/vm1_DataDisk_0"
            },
            "diskRestorePoint": {
              "encryption": {
                "diskEncryptionSet": {
                  "id": "/subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/diskEncryptionSets/des1"
                }
              }
            }
          },
          {
            "managedDisk": {
              "id": "/subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/disks/vm1_DataDisk_1"
            },
            "diskRestorePoint": {
              "encryption": {
                "diskEncryptionSet": {
                  "id": "/subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/diskEncryptionSets/des2"
                }
              }
            }
          }
        ]
      }
    }
  }
}
````

**b) Remote Restore Point**

- `--source-restore-point` **is** passed
- In this case, the source-data-disk-resource should have zero or more Disk  Restore Point ARM ID's.
- For each Disk  Restore Point ARM ID, its corresponding EncryptionSetId or/and EncryptionType must be passed.
- For Example, if the cli request contains the following values for the new parameters

```powershell
az restore-point create --resource-group "linurg" --collection-name "rpc-1" --name "rp-1" --source-restore-point "/subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/restorePointCollections/rpc-1/restorePoints/rp-1" --source-os-resource "/subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/restorePointCollections/rpc-1/restorePoints/rp-1/diskrestorepoints/vm1_osDisk_9e82d2fe-7001-40dc-8bfb-57fc191f182f" --os-restore-point-encryption-set "/subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/diskEncryptionSets/des1" --os-restore-point-encryption-type EncryptionAtRestWithCustomerKey --source-data-disk-resource "/subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/restorePointCollections/rpc-1/restorePoints/rp-1/diskrestorepoints/vm1_DataDisk_0_9e82d2fe-7001-40dc-8bfb-57fc191f182f /subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/restorePointCollections/rpc-1/restorePoints/rp-1/diskrestorepoints/vm1_DataDisk_1_9e82d2fe-7001-40dc-8bfb-57fc191f182f" --data-disk-restore-point-encryption-set "/subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/diskEncryptionSets/des1 /subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/diskEncryptionSets/des2" --data-disk-restore-point-encryption-type  "EncryptionAtRestWithCustomerKey EncryptionAtRestWithCustomerKey"
```

The Restore Point API request body should look like the following:

```json
{
  "name": "rp-1",
  "properties": {
    "sourceRestorePoint": {
      "id": "/subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/restorePointCollections/rpc-1/restorePoints/rp-1"
    },
    "sourceMetadata": {
      "storageProfile": {
        "osDisk": {
          "diskRestorePoint": {
            "sourceDiskRestorePoint": {
              "id": "/subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/restorePointCollections/rpc-1/restorePoints/rp-1/diskrestorepoints/vm1_osDisk_9e82d2fe-7001-40dc-8bfb-57fc191f182f"
            },
            "encryption": {
              "type": "EncryptionAtRestWithCustomerKey",
              "diskEncryptionSet": {
                "id": "/subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/diskEncryptionSets/des1"
              }
            }
          }
        },
        "dataDisks": [
          {
            "diskRestorePoint": {
              "sourceDiskRestorePoint": {
                "id": "/subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/restorePointCollections/rpc-1/restorePoints/rp-1/diskrestorepoints/vm1_DataDisk_0_9e82d2fe-7001-40dc-8bfb-57fc191f182f"
              },
              "encryption": {
                "type": "EncryptionAtRestWithCustomerKey",
                "diskEncryptionSet": {
                  "id": "/subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/diskEncryptionSets/des1"
                }
              }
            }
          },
          {
            "diskRestorePoint": {
              "sourceDiskRestorePoint": {
                "id": "/subscriptions/{sub}/resourceGroups/linurg/providers/Microsoft.Compute/restorePointCollections/rpc-1/restorePoints/rp-1/diskrestorepoints/vm1_DataDisk_1_9e82d2fe-7001-40dc-8bfb-57fc191f182f"
              },
              "encryption": {
                "type": "EncryptionAtRestWithCustomerKey",
                "diskEncryptionSet": {
                  "id": "/subscriptions/{sub}}/resourceGroups/linurg/providers/Microsoft.Compute/diskEncryptionSets/des2"
                }
              }
            }
          }
        ]
      }
    }
  }
}
```

### Target Date

2023-10-31

### PM Contact

aarthiv

### Engineer Contact

linugeorge

### Additional context

Github Issue for Powershell which has more details: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1379

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
The release time of this sprint is **11-15**. Does this release time meet your expectations?

**Comment by linugeorgeofficial** [comment]
@zhoxing-ms Yes, that works for us.

**Comment by Jing-song** [comment]
Hi @linugeorgeofficial, These two descriptions are almost the same. Are there any errors that need to be corrected?

**a) Local Restore Point**

- `--source-restore-point` is not passed
- In this case, the source-data-disk-resource should have one or more Disk ARM ID's.
- For each Disk ARM ID, its corresponding EncryptionSetId or/and EncryptionType must be passed.

**b) Remote Restore Point**

- `--source-restore-point` **is** passed
- In this case, the source-data-disk-resource should have one or more Disk ARM ID's.
- For each Disk ARM ID, its corresponding EncryptionSetId or/and EncryptionType must be passed.

**Comment by linugeorgeofficial** [comment]
@Jing-song 
I've corrected the description for Remote Restore Point to the following.


**b) Remote Restore Point**

- `--source-restore-point` **is** passed
- In this case, the source-data-disk-resource should have one or more Disk  Restore Point ARM ID's.
- For each Disk Restore Point ARM ID, its corresponding EncryptionSetId or/and EncryptionType must be passed.
- For Example, if the cli request contains the following values for the new parameters


The difference is that disk restore point ARM ID's are being passed instead of Disk ID's.
