### ISSUE TITLE
Support Public IP Prefix Tier Option

### ISSUE THREAD

**Issue by mahipdeora** [Azure/azure-cli#27537]
### Describe the bug

Public IP Prefix's CLI doesn't let you set the tier of the IP (**regional or global**), we need to add support for tiers

### Related command

az network public-ip prefix create --name
                                   --resource-group
                                   [--custom-ip-prefix-name]
                                   [--edge-zone]
                                   [--ip-tags]
                                   [--length]
                                   [--location]
                                   [--no-wait {0, 1, f, false, n, no, t, true, y, yes}]
                                   [--tags]
                                   [--version {IPv4, IPv6}]
                                   [--zone]

### Errors

NA

### Issue script & Debug output

NA

### Expected behavior

Customers can create Tier similar to public IP addresses today 

### Environment Summary

azure-cli                         2.53.0

core                              2.53.0
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
ml                                2.20.0
ssh                                2.0.2

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.9'
Extensions directory '/home/mahip/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.14 (main, Sep 24 2023, 01:49:33) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

az network public-ip create --name
                            --resource-group
                            [--allocation-method {Dynamic, Static}]
                            [--ddos-protection-mode {Disabled, Enabled, VirtualNetworkInherited}]
                            [--ddos-protection-plan]
                            [--dns-name]
                            [--dns-name-scope {NoReuse, ResourceGroupReuse, SubscriptionReuse, TenantReuse}]
                            [--edge-zone]
                            [--idle-timeout]
                            [--ip-address]
                            [--ip-tags]
                            [--location]
                            [--public-ip-prefix]
                            [--reverse-fqdn]
                            [--sku {Basic, Standard}]
                            [--tags]
                            [--tier {Global, Regional}]
                            [--version {IPv4, IPv6}]
                            [--zone {1, 2, 3}]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
