### ISSUE TITLE
Add option to get ClearDB account username and password

### ISSUE THREAD

**Issue by okelet** [Azure/azure-cli#2753]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: apt-get

**CLI Version:** What version of the CLI and modules are installed? (Available with `az --version`)  
Answer here: 2.0.2

**OS Version:** What OS and version are you using?  
Answer here: Linux, Ubuntu 16.04 x64

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, PowerShell)  
Answer here: Bash

### Description

Currently, the resource can be show using `az resource show`, but connection parameters such as username and password, that exist in the Azure portal, can not be got using the CLI.

**Comment by JasonRShaver** [comment]
Sorry for the delayed response, but ClearDB is a marketplace extension and we don't currently support marketplace extensions.  Let us know if this is still a concern.
