### ISSUE TITLE
az storage blob upload-batch: incorrect usage: source must be an existing directory

### ISSUE THREAD

**Issue by RitaAguiar** [Azure/azure-cli#27530]
### Describe the bug

I want to copy all files and sub-folder files in the Build Artifacts Folder to the Azure Storage Container.
I have attempted to copy one single file from the Build Artifacts Folder to the Azure Storage Container with success, using the command:
`az storage blob upload --account-name $(accountName) --container-name $(storageContainer) --name dummyfile --file "$(Build.ArtifactStagingDirectory)/Folder/dummy.txt" --overwrite`
However, when I attempt to copy all files using the `az storage blob upload-batch` command, I get the following error:
`ERROR: incorrect usage: source must be an existing directory`
The command I am using:
`az storage blob upload-batch -s $(Build.ArtifactStagingDirectory)/Folder/ -d $(storageContainer)`
I have also tried with:
`az storage blob upload-batch -s $(Build.ArtifactStagingDirectory)/Folder/ --account-name $(accountName) -d $(storageContainer)`
I am sure that the artifact's contents of the Folder are correct as I have outputed/listed them and confirmed.

### Related command

az storage blob upload-batch

### Errors

ERROR: incorrect usage: source must be an existing directory

### Issue script & Debug output

```
ERROR: incorrect usage: source must be an existing directory
##[debug]Exit code 2 received from tool 'C:\Program Files\Git\bin\bash.exe'
##[debug]STDIO streams have closed for tool 'C:\Program Files\Git\bin\bash.exe'
##[debug]task result: Failed
##[error]Script failed with exit code: 2
##[debug]Processed: ##vso[task.issue type=error;]Script failed with exit code: 2
##[debug]Processed: ##vso[task.complete result=Failed;]Script failed with exit code: 2
##[debug]which 'az'
##[debug]found: 'C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd'
##[debug]C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd arg:  account clear
##[debug]C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd arg:  account clear
##[debug]exec tool: C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd
##[debug]exec tool: C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd
##[debug]arguments:
##[debug]arguments:
##[debug]   account
##[debug]   account
##[debug]   clear
##[debug]   clear
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account clear"
Finishing: Deploy to Azure Blob Storage
```

### Expected behavior

Copying all files and sub-folder files in the Build Artifacts Folder to the Azure Storage Container.

### Environment Summary

azure-cli                         2.53.0

core                              2.53.0
telemetry                          1.1.0

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Program Files\Common Files\AzureCliExtensionDirectory'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]

### Additional context

Could be useful to provide the listing of files I'm trying to copy:

```
Your CLI is up-to-date.
Artifact Staging Directory: D:\a\1\a
D:\a\1\a:
Folder

D:\a\1\a/Folder:
Auth0.Core.dll
Auth0.OidcClient.Core.dll
Auth0.OidcClient.dll
IdentityModel.OidcClient.dll
IdentityModel.dll
IdentityModel.pdb
LanguageSupport
LiveCharts.Wpf.dll
LiveCharts.Wpf.pdb
LiveCharts.dll
LiveCharts.pdb
Microsoft.Bcl.AsyncInterfaces.dll
Microsoft.Extensions.DependencyInjection.Abstractions.dll
Microsoft.Extensions.DependencyInjection.dll
Microsoft.Extensions.Logging.Abstractions.dll
Microsoft.Extensions.Logging.dll
Microsoft.Extensions.Options.dll
Microsoft.Extensions.Primitives.dll
Microsoft.IdentityModel.JsonWebTokens.dll
Microsoft.IdentityModel.Logging.dll
Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
Microsoft.IdentityModel.Protocols.dll
Microsoft.IdentityModel.Tokens.dll
Microsoft.Toolkit.Wpf.UI.Controls.WebView.dll
Microsoft.Toolkit.Wpf.UI.Controls.WebView.pdb
Newtonsoft.Json.dll
Prism.dll
Prism.pdb
Revit.Async.dll
RevitAPI.dll
RevitAPIUI.dll
RevitTemplate.dll
RevitTemplate.dll.config
RevitTemplate.pdb
System.Buffers.dll
System.Diagnostics.DiagnosticSource.dll
System.IdentityModel.Tokens.Jwt.dll
System.Memory.dll
System.Numerics.Vectors.dll
System.Runtime.CompilerServices.Unsafe.dll
System.Text.Encodings.Web.dll
System.Text.Json.dll
System.Threading.Tasks.Extensions.dll
System.ValueTuple.dll
SomeFile.addin
en
no

D:\a\1\a/Folder/LanguageSupport:
Resources.en.resx
Resources.no.resx
Resources.resx

D:\a\1\a/Folder/en:
SomeFile.resources.dll

D:\a\1\a/Folder/no:
SomeFile.resources.dll
ERROR: incorrect usage: source must be an existing directory

```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by RitaAguiar** [comment]
I'm very embarrassed to say that the error I was experienced was because I had to input solution with double quotes. Oh syntax 😅
