### ISSUE TITLE
Add options to create databases and collections for DocumentDB/MongoDB

### ISSUE THREAD

**Issue by okelet** [Azure/azure-cli#2756]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: apt-get

**CLI Version:** What version of the CLI and modules are installed? (Available with `az --version`)  
Answer here: 2.0.2

**OS Version:** What OS and version are you using?  
Answer here: Linux, Ubuntu 16.04 x64

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, PowerShell)  
Answer here: Bash

### Description

There are no options to create database or collections inside a DocumentDB/MongoDB account. After creating the account from the CLI, we must go to the portal to create the database and collections and set the options for the collection (size, throughput, partition key); we should be able to do this from the CLI.

**Comment by tjprescott** [comment]
These have been in the CLI a while.  Confirmed in version 2.0.26.
