### ISSUE TITLE
Remove unversioned image aliases from CLI

### ISSUE THREAD

**Issue by Sandido** [Azure/azure-cli#27564]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

Any use of the -image parameter that takes in an unversioned linux image alias. 

### Resource Provider

Microsoft.Compute

### Description of Feature or Work Requested

This PR will remove the unversioned image aliases: https://github.com/Azure/azure-rest-api-specs/pull/26086
The CLI code needs to be updated to remove these aliases along with any related tests. 
This has been planned since this past March. 

Additionally, the messaging warning users of this breaking change should be removed from the vm and vmss creation cmdlets and any others that had this warning added. 

### Minimum API Version Required

2023-07-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/26086

### Request Example

N/A

### Target Date

2023-10-25

### PM Contact

saakpan@microsoft.com

### Engineer Contact

adsandor@microsoft.com

### Additional context

The proper communications for this breaking change were sent out repeatedly and many months ago.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
