### ISSUE TITLE
Adding support for getting Application Gateway WAF Dynamic Manifest

### ISSUE THREAD

**Issue by alonzop** [Azure/azure-cli#27580]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az network application-gateway waf-config list-rule-sets

however for this cli we don't pass any parameters

### Resource Provider

Microsoft.Network (nrp)

### Description of Feature or Work Requested

Need to add support to get the waf dynamic manifest, the result will be in the form of a json

example of the api is - https://management.azure.com/subscriptions/0327f602-dc7b-48da-8267-a2ad819f128f/providers/Microsoft.Network/locations/japaneast/applicationGatewayWafDynamicManifests?api-version=2022-05-01

its already rolled out to PS

### Minimum API Version Required

2022-05-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/20047

### Request Example

https://management.azure.com/subscriptions/0327f602-dc7b-48da-8267-a2ad819f128f/providers/Microsoft.Network/locations/japaneast/applicationGatewayWafDynamicManifests?api-version=2022-05-01

### Target Date

2023-11-01

### PM Contact

gunjan.jain@microsoft.com

### Engineer Contact

alpelled@microsoft.com

### Additional context

this step was missed and we are trying to catch up

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
@alonzop `az network application-gateway waf-config list-rule-sets` you mentioned is based on a different API, something like `/subscriptions/{}/providers/microsoft.network/applicationgatewayavailablewafrulesets`.

Could you please describe what you'd like the CLI command to look like for getting the waf dynamic manifest? Is `az network application-gateway waf-config show-dynamic-manifest` OK for you?

**Comment by alonzop** [comment]
> @alonzop `az network application-gateway waf-config list-rule-sets` you mentioned is based on a different API, something like `/subscriptions/{}/providers/microsoft.network/applicationgatewayavailablewafrulesets`.
> 
> Could you please describe what you'd like the CLI command to look like for getting the waf dynamic manifest? Is `az network application-gateway waf-config show-dynamic-manifest` OK for you?

we would like the cli to be similar to the old one and as such we prefer az network application-gateway waf-config list-dynamic-rule-sets

will that work?

**Comment by necusjz** [comment]
> > @alonzop `az network application-gateway waf-config list-rule-sets` you mentioned is based on a different API, something like `/subscriptions/{}/providers/microsoft.network/applicationgatewayavailablewafrulesets`.
> > Could you please describe what you'd like the CLI command to look like for getting the waf dynamic manifest? Is `az network application-gateway waf-config show-dynamic-manifest` OK for you?
> 
> we would like the cli to be similar to the old one and as such we prefer az network application-gateway waf-config list-dynamic-rule-sets
> 
> will that work?

`az network application-gateway waf-config list-dynamic-rule-sets` is a good one.

**Comment by alonzop** [comment]
> > > @alonzop `az network application-gateway waf-config list-rule-sets` you mentioned is based on a different API, something like `/subscriptions/{}/providers/microsoft.network/applicationgatewayavailablewafrulesets`.
> > > Could you please describe what you'd like the CLI command to look like for getting the waf dynamic manifest? Is `az network application-gateway waf-config show-dynamic-manifest` OK for you?
> > 
> > 
> > we would like the cli to be similar to the old one and as such we prefer az network application-gateway waf-config list-dynamic-rule-sets
> > will that work?
> 
> `az network application-gateway waf-config list-dynamic-rule-sets` is a good one.

sounds good

**Comment by necusjz** [comment]
@alonzop I just curious about `/subscriptions/{subscriptionId}/providers/Microsoft.Network/locations/{location}/applicationGatewayWafDynamicManifests/dafault` and `/subscriptions/{subscriptionId}/providers/Microsoft.Network/locations/{location}/applicationGatewayWafDynamicManifests`.

I knew the 2nd one can support pagination, but do we need to implement both of them?

**Comment by alonzop** [comment]
only one should be enough, they return the same info
