### ISSUE TITLE
Support Explicit Proxy feature for Azure Firewall Policy

### ISSUE THREAD

**Issue by girishmotwani** [Azure/azure-cli#27581]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az network firewall policy 

### Resource Provider

Microsoft.Network/firewallPolicies

### Description of Feature or Work Requested

We have added support to allow the Azure Firewall to be configured as an explicit proxy. Prior to this, Azure firewall could only be configured as a transparent proxy - and would require customers to setup a UDR to direct their application traffic to be inspected by the Azure Firewall.

With Explicit proxy set on the outbound path, you can configure a proxy setting on the sending application (such as a web browser) with Azure Firewall configured as the proxy. As a result, traffic from the sending application goes to the firewall's private IP address and therefore egresses directly from the firewall without the using a UDR.

With the Explicit proxy mode (supported for HTTP/S), you can define proxy settings in the browser to point to the firewall private IP address. You can manually configure the IP address on the browser or application, or you can configure a proxy auto config (PAC) file. The firewall can host the PAC file to serve the proxy requests after you upload it to the firewall. 

### Minimum API Version Required

N/A

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/15017

Additional PR to add one more field - https://github.com/Azure/azure-rest-api-specs/pull/19011

### Request Example

(https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2023-05-01/examples/FirewallPolicyPut.json)
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2023-05-01/examples/FirewallPolicyGet.json

### Target Date

2023-11-01

### PM Contact

mgakman@microsoft.com

### Engineer Contact

uditmisra@microsoft.com

### Additional context

https://github.com/Azure/azure-rest-api-specs/pull/15017/files

powershell PR - https://github.com/Azure/azure-powershell/pull/18642

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
