### ISSUE TITLE
The resource type could not be found in the namespace 'Microsoft.Compute' for api version '2016-04-30-preview'

### ISSUE THREAD

**Issue by bleissem** [Azure/azure-cli#2759]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
followed instrucstions on 
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli

**CLI Version:** What version of the CLI and modules are installed? (Available with `az --version`)  
Answer here:
azure-cli (2.0.2)

acr (2.0.0)
acs (2.0.2)
appservice (0.1.2)
batch (2.0.0)
cloud (2.0.0)
component (2.0.0)
configure (2.0.2)
container (0.1.2)
core (2.0.2)
documentdb (0.1.2)
feedback (2.0.0)
find (0.0.1b1)
iot (0.1.2)
keyvault (2.0.0)
lab (0.0.1)
monitor (0.0.1)
network (2.0.2)
nspkg (2.0.0)
profile (2.0.2)
redis (0.1.1b3)
resource (2.0.2)
role (2.0.1)
sql (2.0.0)
storage (2.0.2)
vm (2.0.2)

Python (Linux) 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]

**OS Version:** What OS and version are you using?  
Answer here:
ubuntu linux 16.04

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, PowerShell)  
Answer here:
bash
### Description
Hi,
when I execute: 
az disk create ..
( based on the description 
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/upload-vhd )
I get an error:
"
The resource type could not be found in the namespace 'Microsoft.Compute' for api version '2016-04-30-preview'.
"
I am currently running this command in: AzureGermanCloud
( that is the output of: az cloud show )

Please fix this issue. Thanks in advance.

**Comment by yugangw-msft** [comment]
Let us use #2190 to trace sovereign clouds. 
@bleissem, you need to wait, and hope it won't be long
