### ISSUE TITLE
Tests fail when run on Windows

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#2760]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: `dev_setup.py`

**CLI Version:** What version of the CLI and modules are installed? (Available with `az --version`)  
Answer here: `latest`

**OS Version:** What OS and version are you using?  
Answer here: `Windows 10`

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, PowerShell)  
Answer here: `cmd.exe`

### Description

The following tests routinely fail on my machine when I run `run_tests` (they pass on CI however). 

- test_get_expanded_subscription_info_for_logged_in_service_principal
- test_batch_cancel_operation
- test_batch_copy_blob_with_pattern
- test_batch_copy_blob_with_sas
- test_batch_copy_blob_without_sas
- test_batch_copy_files_without_sas
- test_help_extra_missing_params
- test_help_full_documentations
- test_help_group_help
- test_set_config_value_file_permissions
- test_storage_blob_upload_128mb_file
- test_storage_blob_upload_64mb_file
- test_storage_blob_upload_midsize_file
- test_storage_blob_upload_small_file

**Comment by derekbekoe** [comment]
Just ran into `test_get_expanded_subscription_info_for_logged_in_service_principal` failing.

Looks like on a clean machine, it succeeds the first time. Second time it fails. That would explain why it works on CI.

**Comment by troydai** [comment]
@derekbekoe what platform? Windows?

**Comment by troydai** [comment]
One reason I can see for there tests to fail on Windows is the file path issue. For example, the storage tests depend on temp file, in which the separator must be `\` instead of `/` on Windows.

**Comment by troydai** [comment]
Fixed recently
