### ISSUE TITLE
Not available from Debian 12 "bookworm" repo

### ISSUE THREAD

**Issue by yrro** [Azure/azure-cli#27600]
### Describe the bug

`azure-cli` depends on `libffi7` and `libssl1.1` which are [not](https://packages.debian.org/search?keywords=libffi7) [present](https://packages.debian.org/search?keywords=libssl1.1) in Debian 12 ("bookworm").

You should be relying on `dpkg-shlibdeps` to do the work of collecting up all your shared library dependencies and generating the `shlibs:Depends` substvar which you should reference in the `Depends` field in `debian/control`.

See [dpkg-shlibdeps(1)](https://manpages.debian.org/bookworm/dpkg-dev/dpkg-shlibdeps.1.en.html), [deb-substvars(5)](https://manpages.debian.org/bookworm/dpkg-dev/deb-substvars.5.en.html), [Debian Policy Manual section 8.6.1 Shared libraries: Generating dependencies on shared libraries](https://www.debian.org/doc/debian-policy/ch-sharedlibs.html)

### Related command

`apt install azure-cli`

### Errors

```
The following packages have unmet dependencies:
 azure-cli : Depends: libffi7 (>= 3.3~20180313) but it is not installable
             Depends: libssl1.1 (>= 1.1.1) but it is not installable
```

### Issue script & Debug output

N/A

### Expected behavior

Package should be installable on Debian 12 "bookworm"

### Environment Summary

N/A

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yrro** [comment]
Based on #25750 I assumed the package was now built for Debian 12 "bookworm" and present in `deb https://packages.microsoft.com/debian/12/prod bookworm main`.

However I now see that I can only see `2.53.0-1~bullseye` from the Debian 11 "bullseye" repo, and there is no `azure-cli` package in the bookworm repo.

**Comment by yrro** [comment]
Scrolling up in that issue a bit I see this comment https://github.com/Azure/azure-cli/issues/25750#issuecomment-1605940173

I suggest leaving this issue open until the package is uploaded to the bookworm repository--that will avoid future confusion/duplicate issues being filed which has already happened a few times. :)

**Comment by bebound** [comment]
We've released the CLI for Debian 12.
Apparently, this is a config error, please check your repo settings and remove the bullseye repo.

**Comment by yrro** [comment]
Thank you. I forgot `azure-cli` is in its own `repos/azure-cli` repo and I hadn't changed that over to use the `bookworm1 suite. :facepalm:
