### ISSUE TITLE
Update API version to the latest stable when accessing "microsoft.insights/activityLogAlerts" resource type

### ISSUE THREAD

**Issue by grchris-microsoft** [Azure/azure-cli#27602]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

Commands start with "az monitor activity-log alert ..", for example:
**az monitor activity-log alert** action-group add --name MyName --resource-group MyRg --action /subscriptions/abcd

### Resource Provider

microsoft.insights/activityLogAlerts

### Description of Feature or Work Requested

Currently az works with older version of the service. Some customers face issues with this, and obviously it has to be updated to the latest stable version. The tool uses "2017-04-01", and it has to use the latest stable version, which is "2020-10-01".

### Minimum API Version Required

2020-10-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/monitor/resource-manager/Microsoft.Insights/stable/2020-10-01/activityLogAlerts_API.json

### Request Example

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/monitor/resource-manager/Microsoft.Insights/stable/2020-10-01/examples/ActivityLogAlertRule_CreateOrUpdate.json

### Target Date

2020-10-01

### PM Contact

@yagil

### Engineer Contact

@grchris

### Additional context

There's a related CRI, where the customer complains that he cannot update his rule using the CLI tool. After our investigation it turns out that the API version is not up to date.

[Incident 425584794](https://portal.microsofticm.com/imp/v3/incidents/incident/425584794/summary) : [Pending PG] || # [AzMonCRI] - Couldn't add action group to service health alert via Azure CLI

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by asafst** [comment]
Hi @yonzhan , we tried to follow the [aaz dev tools doc](https://azure.github.io/aaz-dev-tools/) to try to update the CLIs using the self-service tools, and sent the following PRs:
aaz repo - https://github.com/Azure/aaz/pull/323
azure cli repo - https://github.com/Azure/azure-cli/pull/27612

From the azure cli PR validation failures, looks like we missed something in the process.
I would appreciate understanding if it was expected that our team would use these tools to update the CLI version, and if we could get some help with it.
Thanks!

**Comment by AllyW** [comment]
Hi @asafst , we are evaluating upgrading the "microsoft.insights/activityLogAlerts" api-version to the latest stable one this week and may reply to this issue later. 

Regarding the pr you pulled, there are some missing parts.
1) if api version is changed, related service live tests should be run and recorded locally and submitted to repo to ensure current functionality still works well
2) pull request has its own formatting and can be referred [here]( https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests)
3) because previous execution has some customization, it should be inherited into new versions. Otherwise, "BREAKING CHANGE" label needs to be added into this pr release notes.

**Comment by AllyW** [comment]
@asafst  related version upgrading pr is linked

**Comment by asafst** [comment]
Thanks @AllyW! The PR looks great. I closed my PR on the cli repo. should I also close the PR in the [aaz repo](https://github.com/Azure/aaz/pull/323)?

**Comment by AllyW** [comment]
@asafst, yes, we'll pull a new request in the aaz repo later after the code submit for azure cli main repo is ready

**Comment by asafst** [comment]
Thanks @AllyW, I closed the PR I opened in the aaz repo.
