### ISSUE TITLE
az functionapp create does not use newly created application insight's connection string

### ISSUE THREAD

**Issue by georgeOsdDev** [Azure/azure-cli#27607]
### Describe the bug

`az functionapp create` use `APPINSIGHTS_INSTRUMENTATIONKEY` instead of `APPLICATIONINSIGHTS_CONNECTION_STRING `.

<App settings reference for Azure Functions | Microsoft Learn>
https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings#appinsights_instrumentationkey
> While the use of APPLICATIONINSIGHTS_CONNECTION_STRING is recommended in all cases

> 

### Related command

```
az functionapp create \
          --resource-group ${RESOURCE_GROUP_NAME} \
          --storage-account ${STORAGE_NAME}\
          --plan ${ASP_NAME} \
          --name  ${FUINCTIONAPP_NAME}  \
          --functions-version 4 \
          --os-type Linux \
          --runtime custom \
           --verbose --debug
```

### Errors

The command will not fail.

### Issue script & Debug output

While processing command newly Application Insights component will be created. I expect Function App to have app settings with `APPLICATIONINSIGHTS_CONNECTION_STRING`  with the value of ConnectionString from Application insights, but app settings has  `APPINSIGHTS_INSTRUMENTATIONKEY`.

### Expected behavior

Newly created FunctionApp should have app settings with `APPLICATIONINSIGHTS_CONNECTION_STRING`.

### Environment Summary

azure-cli                         2.53.0

core                              2.53.0
telemetry                          1.1.0

Extensions:
application-insights               1.0.0
communication                    1.7.2b1
log-analytics                      0.2.2

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/home/toshida/.azure/cliextensions'

Python (Linux) 3.10.10 (main, Sep 20 2023, 06:07:38) [GCC 11.4.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

I think below block is related.
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L4059-L4064

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by AnatoliB** [comment]
cc @RohitRanjanMS
