### ISSUE TITLE
DiskRP 2023-04-02 Changes

### ISSUE THREAD

**Issue by carlos6125** [Azure/azure-cli#27613]
### Related commands

az disk show [--disk-name]
             [--ids]
             [--resource-group]
             [--subscription]

az disk create --name
               --resource-group
               [--accelerated-network {false, true}]
               [--architecture {Arm64, x64}]
               [--data-access-auth-mode {AzureActiveDirectory, None}]
               [--disk-access]
               [--disk-encryption-set]
               [--disk-iops-read-only]
               [--disk-iops-read-write]
               [--disk-mbps-read-only]
               [--disk-mbps-read-write]
               [--edge-zone]
               [--enable-bursting {false, true}]
               [--encryption-type {EncryptionAtRestWithCustomerKey, EncryptionAtRestWithPlatformAndCustomerKeys, EncryptionAtRestWithPlatformKey}]
               [--gallery-image-reference]
               [--gallery-image-reference-lun]
               [--hyper-v-generation {V1, V2}]
               [--image-reference]
               [--image-reference-lun]
               [--location]
               [--logical-sector-size]
               [--max-shares]
               [--network-access-policy {AllowAll, AllowPrivate, DenyAll}]
               [--no-wait]
               [--os-type {Linux, Windows}]
               [--performance-plus {false, true}]
               [--public-network-access {Disabled, Enabled}]
               [--secure-vm-disk-encryption-set]
               [--security-data-uri]
               [--security-type {ConfidentialVM_DiskEncryptedWithCustomerKey, ConfidentialVM_DiskEncryptedWithPlatformKey, ConfidentialVM_VMGuestStateOnlyEncryptedWithPlatformKey, Standard, TrustedLaunch}]
               [--size-gb]
               [--sku {PremiumV2_LRS, Premium_LRS, Premium_ZRS, StandardSSD_LRS, StandardSSD_ZRS, Standard_LRS, UltraSSD_LRS}]
               [--source]
               [--source-storage-account-id]
               [--support-hibernation {false, true}]
               [--tags]
               [--tier]
               [--upload-size-bytes]
               [--upload-type {Upload, UploadWithSecurityData}]
               [--zone {1, 2, 3}]
               **[--elasticSanResourceId]
	       [--OptimizedForFrequentAttach]**

az snapshot create --name
                   --resource-group
                   [--accelerated-network {false, true}]
                   [--architecture {Arm64, x64}]
                   [--copy-start {false, true}]
                   [--disk-access]
                   [--disk-encryption-set]
                   [--edge-zone]
                   **[--elasticSanResourceId]**
                   [--encryption-type {EncryptionAtRestWithCustomerKey, EncryptionAtRestWithPlatformAndCustomerKeys, EncryptionAtRestWithPlatformKey}]
                   [--for-upload {false, true}]
                   [--hyper-v-generation {V1, V2}]
                   [--incremental {false, true}]
                   [--location]
                   [--network-access-policy {AllowAll, AllowPrivate, DenyAll}]
                   [--no-wait]
                   [--public-network-access {Disabled, Enabled}]
                   [--size-gb]
                   [--sku {Premium_LRS, Standard_LRS, Standard_ZRS}]
                   [--source]
                   [--source-storage-account-id]
                   [--tags]

### Describe the solution you'd like

"az disk show" should output LastOwnershipUpdateTime - a newly added property to a managed disk. This property shows the last time a disk transitioned in between the diskStates Attached/Detached/Reserved. Field is null on disk creation.

Below are the new parameters that need to be added for disk and snapshot creation commands: 
az disk create --name 
--resource-group `
**[--elasticSanResourceId] 
[--OptimizedForFrequentAttach]** 

az snapshot create --name 
--resource-group 
**[--elasticSanResourceId]** 

### Additional context

Customer can use ElasticSanResourceID to export Elastic San volume snapshot to managed disk resources
OptimizedForFrequentAttach property is used to skip fault domain alignment for the disk with the vm. This allows users to move the disk between vms in an availability set with no data move.

Once Customer provides ElasticSanResourceId parameter,
**diskrpResource.properties.creationData.elasticSanResourceId** needs to be set.

Similarly, if customer provides OptimizedForFrequentAttach parameter,
**diskrpResource.properties.optimizedForFrequentAttach** needs to be populated.

Link to the OpenAPI (swagger) spec:
https://github.com/Azure/azure-rest-api-specs/blob/82e7e30a6d46c095e0c3211f3ff7bafe82a362f1/specification/compute/resource-manager/Microsoft.Compute/DiskRP/stable/2023-04-02/diskRPCommon.json#L373

Link to our Powershell Github work version to this request:
https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1377

Feature flags or restrictions on the changes provided in this design specification:
ElasticSanResourceId can only be used when a customer's subscription is whitelisted with Microsoft.Compute/ElasticSanImportExport” AFEC

**Examples:**
```
- az disk create -n diskName
-r resourceGroup 
**-ElasticSanResourceId ""subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.ElasticSan/elasticSans/myElasticSan/volumegroups/myElasticSanVolumeGroup/snapshots/myElasticSanVolumeSnapshot"
```

```
- az snapshot create -n snapshotName
-r resourceGroup 
**-ElasticSanResourceId ""subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.ElasticSan/elasticSans/myElasticSan/volumegroups/myElasticSanVolumeGroup/snapshots/myElasticSanVolumeSnapshot"
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by carlos6125** [comment]
Added more info under Additional Context section.

**Comment by zhoxing-ms** [comment]
@carlos6125 Could you please use this template [[Microsoft Internal / Service Team] Feature Request](https://github.com/Azure/azure-cli/issues/new?assignees=&labels=feature-request&projects=&template=Service_team_request.yml) to create this feature request? It contains more necessary information for us to develop, such as whether the SDK is ready

**Comment by zhoxing-ms** [comment]
> [--elasticSanResourceId]
   [--OptimizedForFrequentAttach]

Please note that the parameter naming convention for CLI usually does not use camel case, but rather snake case, such as:
`--elastic-san-resource-id` and `--optimized-for-frequent-attach`

**Comment by zhoxing-ms** [comment]
@carlos6125 Additionally, as our Ignite Sprint is already super fully scheduled (with a total of around 15 features and some top priority projects)
I'm concerned that we don't have enough time and energy to support this feature in this sprint. Is it acceptable if we plan the development and release of this feature for the next sprint (release date is **12-05**)?

**Comment by carlos6125** [comment]
Created a new request using the template recommended. Closing this one.
