### ISSUE TITLE
Cannot upgrade postgres flexible-server to 15.

### ISSUE THREAD

**Issue by mtlljm** [Azure/azure-cli#27638]
### Describe the bug

The CLI is still limited to upgrade postgres flexible-server due to the version flag only accepting Allowed values: 12, 13, 14.

### Related command

az postgres flexible-server upgrade --name myServerName --resource-group myResouceGroup --version 15

### Errors

az_command_data_logger: az postgres flexible-server upgrade: '15' is not a valid value for '--version'. Allowed values: 12, 13, 14.

### Issue script & Debug output

az_command_data_logger: command args: postgres flexible-server upgrade --name {} --resource-group {} --version {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f81a50eeef0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f81a4e9cd30>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f81a4e9ce50>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
urllib3.connectionpool: Starting new HTTPS connection (1): app.aladdin.microsoft.com:443
urllib3.connectionpool: https://app.aladdin.microsoft.com:443 "GET /api/v1.0/suggestions?query=%7B%22command%22%3A+%22postgres+flexible-server+upgrade%22%2C+%22parameters%22%3A+%22--resource-group%2C--version%2C--name%22%7D&clientType=AzureCli&context=%7B%22versionNumber%22%3A+%222.53.0%22%2C+%22errorType%22%3A+%22InvalidParameterValue%22%2C+%22correlationId%22%3A+%22d3d15fc2-76f2-469d-8700-7fe39a5a7da8%22%2C+%22subscriptionId%22%3A+%22b3452914-00cd-466c-b921-92a36c0485a5%22%2C+%22eventId%22%3A+%223733a628-6934-423f-99d5-6512efa1b9a4%22%7D HTTP/1.1" 200 None
cli.azure.cli.core.azclierror: NoneType: None

cli.azure.cli.core.azclierror: az postgres flexible-server upgrade: '15' is not a valid value for '--version'. Allowed values: 12, 13, 14.
az_command_data_logger: az postgres flexible-server upgrade: '15' is not a valid value for '--version'. Allowed values: 12, 13, 14.

### Expected behavior

The postgres flexible-server should be upgraded to 15, this is possible via the https://portal.azure.com, but for some reason not possible via the CLI.

Unsure whether there is a technical reason why, of the list of acceptable arguments to the --version flag still need to be updated.

### Environment Summary

azure-cli                         2.53.0

core                              2.53.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/usr/local/bin/python'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.10.11 (main, Apr  5 2023, 23:58:40) [GCC 12.2.1 20220924]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by nachoalonsoportillo** [comment]
#27773 resolved this issue seven months ago.

@yonzhan, please resolve. Thanks!
