### ISSUE TITLE
az cli fails on CentOS 7

### ISSUE THREAD

**Issue by mattboston** [Azure/azure-cli#27652]
### Describe the bug

We have the latest version of azcli (v2.38.1) installed for CentOS7, which is also the last version according to this page (https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=dnf).  When we try to run any command it tells us we need to upgrade to v2.53.0, which isn't available for CentOS/RHEL7.  Unfortunately we still have some CentOS 7 servers that will be around for another year.  Until then we need to be able to use azcli.

### Related command

`az version`

### Errors

# az version
{
  "azure-cli": "2.38.1",
  "azure-cli-core": "2.38.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
New Azure CLI version available. Running 'az upgrade' to update automatically.
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Your current Azure CLI version is 2.38.1. Latest version available is 2.53.0.
Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
Do you want to continue? (Y/n): y
Loaded plugins: fastestmirror, versionlock
Loading mirror speeds from cached hostfile
No packages marked for update
WARNING: New Azure CLI version available. Running 'az upgrade' to update automatically.
WARNING: This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Your current Azure CLI version is 2.38.1. Latest version available is 2.53.0.
WARNING: Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli

### Issue script & Debug output

# az version --debug
cli.knack.cli: Command arguments: ['version', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x2b09e257dae8>, <function OutputProducer.on_global_arguments at 0x2b09e2a52c80>, <function CLIQuery.on_global_arguments at 0x2b09e2c8e158>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'version': ['azure.cli.command_modules.util']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: util                      0.003         3         6
cli.azure.cli.core: Total (1)                 0.003         3         6
cli.azure.cli.core: Loaded 3 groups, 6 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : version
cli.azure.cli.core: Command table: version
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x2b09e3d11400>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/root/.azure/commands/2023-10-20.15-49-54.version.22439.log'.
az_command_data_logger: command args: version --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x2b09e416f400>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x2b09e424ab70>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x2b09e424ac80>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x2b09e2a52d08>, <function CLIQuery.handle_query_parameter at 0x2b09e2c8e1e0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x2b09e424abf8>]
cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x2b09e41b50d0>, <function _x509_from_base64_to_hex_transform at 0x2b09e41b5158>]
cli.knack.cli: Event: CommandInvoker.OnFilterResult []
{
  "azure-cli": "2.38.1",
  "azure-cli-core": "2.38.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
cli.knack.cli: Event: Cli.SuccessfulExecute []
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x2b09e3d11620>]
az_command_data_logger: exit code: 0
cli.__main__: Command ran in 0.534 seconds (init: 0.454, invoke: 0.080)
cli.__main__: New Azure CLI version available. Running 'az upgrade' to update automatically.
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Your current Azure CLI version is 2.38.1. Latest version available is 2.53.0.
Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
Do you want to continue? (Y/n): 
Loaded plugins: fastestmirror, versionlock
Loading mirror speeds from cached hostfile
No packages marked for update
WARNING: New Azure CLI version available. Running 'az upgrade' to update automatically.
WARNING: This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
WARNING: Your current Azure CLI version is 2.38.1. Latest version available is 2.53.0.
WARNING: Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli

### Expected behavior

If CentOS/RHEL 7 will not be updated, can it still be used?  And can something be added to bypass the forced upgrade.

### Environment Summary

# az --version
azure-cli                         2.38.1 *

core                              2.38.1 *
telemetry                          1.0.6 *

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location '/bin/python3.6'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.8 (default, Jun 20 2023, 11:53:23) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

Legal docs and information: aka.ms/AzureCliLegal

You have 3 updates available. Consider updating your CLI installation with 'az upgrade'

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
New Azure CLI version available. Running 'az upgrade' to update automatically.
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Your current Azure CLI version is 2.38.1. Latest version available is 2.53.0.
Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
This is a known issue, the CLI upgrade does not check whether the latest version is available in current distro.

`New Azure CLI version available. Running 'az upgrade' to update automatically.` is printed by https://learn.microsoft.com/en-us/cli/azure/update-azure-cli#automatic-update, which can be disabled by `az config set auto-upgrade.enable=no`
