### ISSUE TITLE
DiskRP 2023-04-02 Changes

### ISSUE THREAD

**Issue by carlos6125** [Azure/azure-cli#27697]
### Preconditions

- [x] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az disk show [--disk-name]
[--ids]
[--resource-group]
[--subscription]

az disk create --name
--resource-group
[--accelerated-network {false, true}]
[--architecture {Arm64, x64}]
[--data-access-auth-mode {AzureActiveDirectory, None}]
[--disk-access]
[--disk-encryption-set]
[--disk-iops-read-only]
[--disk-iops-read-write]
[--disk-mbps-read-only]
[--disk-mbps-read-write]
[--edge-zone]
[--enable-bursting {false, true}]
[--encryption-type {EncryptionAtRestWithCustomerKey, EncryptionAtRestWithPlatformAndCustomerKeys, EncryptionAtRestWithPlatformKey}]
[--gallery-image-reference]
[--gallery-image-reference-lun]
[--hyper-v-generation {V1, V2}]
[--image-reference]
[--image-reference-lun]
[--location]
[--logical-sector-size]
[--max-shares]
[--network-access-policy {AllowAll, AllowPrivate, DenyAll}]
[--no-wait]
[--os-type {Linux, Windows}]
[--performance-plus {false, true}]
[--public-network-access {Disabled, Enabled}]
[--secure-vm-disk-encryption-set]
[--security-data-uri]
[--security-type {ConfidentialVM_DiskEncryptedWithCustomerKey, ConfidentialVM_DiskEncryptedWithPlatformKey, ConfidentialVM_VMGuestStateOnlyEncryptedWithPlatformKey, Standard, TrustedLaunch}]
[--size-gb]
[--sku {PremiumV2_LRS, Premium_LRS, Premium_ZRS, StandardSSD_LRS, StandardSSD_ZRS, Standard_LRS, UltraSSD_LRS}]
[--source]
[--source-storage-account-id]
[--support-hibernation {false, true}]
[--tags]
[--tier]
[--upload-size-bytes]
[--upload-type {Upload, UploadWithSecurityData}]
[--zone {1, 2, 3}]
**[--elastic-san-resource-id]
[--optimized-for-frequent-attach]**

az snapshot create --name
--resource-group
[--accelerated-network {false, true}]
[--architecture {Arm64, x64}]
[--copy-start {false, true}]
[--disk-access]
[--disk-encryption-set]
[--edge-zone]
**[--elastic-san-resource-id]**
[--encryption-type {EncryptionAtRestWithCustomerKey, EncryptionAtRestWithPlatformAndCustomerKeys, EncryptionAtRestWithPlatformKey}]
[--for-upload {false, true}]
[--hyper-v-generation {V1, V2}]
[--incremental {false, true}]
[--location]
[--network-access-policy {AllowAll, AllowPrivate, DenyAll}]
[--no-wait]
[--public-network-access {Disabled, Enabled}]
[--size-gb]
[--sku {Premium_LRS, Standard_LRS, Standard_ZRS}]
[--source]
[--source-storage-account-id]
[--tags]

### Resource Provider

DiskRP

### Description of Feature or Work Requested

"az disk show" should output LastOwnershipUpdateTime - a newly added property to a managed disk. This property shows the last time a disk transitioned in between the diskStates Attached/Detached/Reserved. Field is null on disk creation.

Below are the new parameters that need to be added for disk and snapshot creation commands:
az disk create --name
--resource-group `
**[--elastic-san-resource-id]
[--optimized-for-frequent-attach]**

az snapshot create --name
--resource-group
**[--elastic-san-resource-id]**

### Minimum API Version Required

2023-04-02

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/blob/82e7e30a6d46c095e0c3211f3ff7bafe82a362f1/specification/compute/resource-manager/Microsoft.Compute/DiskRP/stable/2023-04-02/diskRPCommon.json#L373

https://github.com/Azure/azure-rest-api-specs/blob/82e7e30a6d46c095e0c3211f3ff7bafe82a362f1/specification/compute/resource-manager/Microsoft.Compute/DiskRP/stable/2023-04-02/disk.json#L773

### Request Example

```
- az disk create -n diskName
-r resourceGroup 
**-elastic-san-resource-id ""subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.ElasticSan/elasticSans/myElasticSan/volumegroups/myElasticSanVolumeGroup/snapshots/myElasticSanVolumeSnapshot"
```

```
- az snapshot create -n snapshotName
-r resourceGroup 
**-elastic-san-resource-id ""subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.ElasticSan/elasticSans/myElasticSan/volumegroups/myElasticSanVolumeGroup/snapshots/myElasticSanVolumeSnapshot"
```

### Target Date

2023-11-06

### PM Contact

adarshv@microsoft.com, uarshadkhan@microsoft.com, yuemlu@microsoft.com

### Engineer Contact

carloshehe@microsoft.com, pramb@microsoft.com, chetan.maddula@microsoft.com

### Additional context

Customer can use ElasticSanResourceID to export Elastic San volume snapshot to managed disk resources
OptimizedForFrequentAttach property is used to skip fault domain alignment for the disk with the vm. This allows users to move the disk between vms in an availability set with no data move.

Once Customer provides ElasticSanResourceId parameter,
**diskrpResource.properties.creationData.elasticSanResourceId** needs to be set.

Similarly, if customer provides OptimizedForFrequentAttach parameter,
**diskrpResource.properties.optimizedForFrequentAttach** needs to be populated.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
