### ISSUE TITLE
Microsoft.CloudShell Namespace Registration issue in Azure Cloud Shell - Started This Afternoon for No Reason.

### ISSUE THREAD

**Issue by mackswift** [Azure/azure-cli#27699]
### Describe the bug

Azure Cloud Shell shows this message on every login:

Storage fileshare subscription subscription ID is not registered to Microsoft.CloudShell Namespace. Please follow these instructions "https://aka.ms/RegisterCloudShell" to register. In future, unregistered subscriptions will have restricted access to CloudShell service.

The instructions on this page do not resolve the issue. The message continues to show up every single time the cloud shell is started. Prior to today, this message did not appear. Also, Microsoft.Cloudshell is registered.

### Related command

There is no related command. This began displaying today upon starting up the Azure Cloud Shell.

### Errors

Storage fileshare subscription is not registered to Microsoft.CloudShell Namespace. Please follow these instructions "https://aka.ms/RegisterCloudShell" to register. In future, unregistered subscriptions will have restricted access to CloudShell service.

![image](https://github.com/Azure/azure-cli/assets/54779661/e7adf1db-2bfb-486d-a203-3eefbca901cf)

### Issue script & Debug output

Not applicable

### Expected behavior

The Cloud Shell should not be displaying a 'not registered' message while the Microsoft.CloudShell Namespace is clearly registered.

### Environment Summary

azure-cli                         2.53.0 *

core                              2.53.0 *
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
azure-iot                         0.22.0
ml                                2.21.1
ssh                                2.0.2

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.9'
Extensions directory '/home/mack/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.14 (main, Oct 12 2023, 19:48:32) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

You have 2 update(s) available. They will be updated with the next build of Cloud Shell.
New Azure CLI version available. Running 'az upgrade' to update automatically.
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Your current Azure CLI version is 2.53.0. Latest version available is 2.53.1.
Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
Do you want to continue? (Y/n): n

### Additional context

I also can't seem to upgrade Azure CLI to version 2.53.1. The prompt just hangs and hangs until I Ctrl-C back to the prompt.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by hima-gadupudi** [comment]
There was a bug in the image code and it is fixed on 10/31/2023. If your subscription is registered and you still see this message after restarting cloudshell, please comment here. Thank you.

**Comment by javacavaj** [comment]
I'm still seeing this issue after completing the instructions on the page. What additional steps should I take to resolve this?

**Comment by DaleyKD** [comment]
@hima-gadupudi : After I registered the provider with my subscription, I needed to restart my Cloud Shell. THANK YOU!

**Comment by mackswift** [comment]
Everything seems fine now. Thank you!

**Comment by brthurr** [comment]
I am still seeing this as of today, 12/14
![Untitled](https://github.com/Azure/azure-cli/assets/11654145/abd3d701-1a3f-4b5d-9892-2d4d847a86d9)

**Comment by clr2of8** [comment]
I have the same issue as brthurr Storage Fileshare not registered

**Comment by Amrish-Sharma** [comment]
Do we have to do anything about this on our subscription level as I am also getting this warning on my cloudshell

**Comment by weeyin83** [comment]
I am also seeing the error in my subscription.

**Comment by moshfiqrony** [comment]
I am also getting the same warning

**Comment by smereczynski** [comment]
+1

**Comment by ScottWatsonWork** [comment]
> Still a problem here too.

So it turns out my storage account was not in the same subscription ( found using the env | grep ACC_STORAGE_PROFILE ) I was using it was using some other subscription and that one indeed didn't have cloudshell registered.  I ended up deleting the storage account and moving to a new one in my most used subscription.  ( needed to use clouddrive unmount and clouddrrive mount commands )

**Comment by benprebble-maker** [comment]
Attempted de-registering and re-registering. I only have one subscription. Issue persists.
![Screenshot 2024-03-07 at 11 14 20 AM](https://github.com/Azure/azure-cli/assets/67561895/3db22a8c-c632-4a9e-9aae-cd3b3208226c)

**Comment by mczteinaz** [comment]
I am getting this same error. I have 2 subscriptions, and I have Microsoft.Storage and Microsoft.CloudShell registered under resource providers on both. The subscription number in the error is my student account and as you can see in the screenshot, these are registered. How do I resolve the error?

![image](https://github.com/Azure/azure-cli/assets/158778605/7e8321ed-2686-4382-88ea-b406080e5bd1)

**Comment by Olypensun** [comment]
> I am getting this same error. I have 2 subscriptions, and I have Microsoft.Storage and Microsoft.CloudShell registered under resource providers on both. The subscription number in the error is my student account and as you can see in the screenshot, these are registered. How do I resolve the error?
> 
> **UPDATE I fixed this by clicking the settings gear on the shell window --> reset user settings --> reset**
> 
> ![image](https://private-user-images.githubusercontent.com/158778605/316384034-7e8321ed-2686-4382-88ea-b406080e5bd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzODc4OTksIm5iZiI6MTcxMzM4NzU5OSwicGF0aCI6Ii8xNTg3Nzg2MDUvMzE2Mzg0MDM0LTdlODMyMWVkLTI2ODYtNDM4Mi04OGVhLWI0MDYwODBlNWJkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QyMDU5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWQ1MjU0OGZlY2E4MWExZjQ5YWFhNTBhNzYzMjBlZmI5YzlkMjdmOTg0N2ZhOWQ4NTliYzBhZTg3ZDAyNTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xC0gdHBuSc9sfxOwjc3v6PgC_C4IfMWxXt4P4kXqHNw)

Thank you!!!! This is exactly what fixed mine today

**Comment by raghumuttana** [comment]
> > I am getting this same error. I have 2 subscriptions, and I have Microsoft.Storage and Microsoft.CloudShell registered under resource providers on both. The subscription number in the error is my student account and as you can see in the screenshot, these are registered. How do I resolve the error?
> > **UPDATE I fixed this by clicking the settings gear on the shell window --> reset user settings --> reset**
> > ![image](https://private-user-images.githubusercontent.com/158778605/316384034-7e8321ed-2686-4382-88ea-b406080e5bd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzODc4OTksIm5iZiI6MTcxMzM4NzU5OSwicGF0aCI6Ii8xNTg3Nzg2MDUvMzE2Mzg0MDM0LTdlODMyMWVkLTI2ODYtNDM4Mi04OGVhLWI0MDYwODBlNWJkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QyMDU5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWQ1MjU0OGZlY2E4MWExZjQ5YWFhNTBhNzYzMjBlZmI5YzlkMjdmOTg0N2ZhOWQ4NTliYzBhZTg3ZDAyNTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xC0gdHBuSc9sfxOwjc3v6PgC_C4IfMWxXt4P4kXqHNw)
> 
> Thank you!!!! This is exactly what fixed mine today

>This worked for me too.
