### ISSUE TITLE
[ResourceManager] Improve lock level validation

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#2771]
PR #2768 added validation to the lock commands to resolve the command target to either the subscription/resource group/resource level. This validation can be improved using a strategy like that use for VM create to resolve storage profile.

**Comment by brendandburns** [comment]
@tjprescott can you give a pointer to that validation?

**Comment by tjprescott** [comment]
@brendandburns an example starts here for the type of network balancer to use on a VMSS:
https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py#L782

Essentially you resolve the "type" using some coarse logic and then you specify the required and forbidden parameters for each case and, based on the type, validate those. The benefit is that you'll get a list of ALL your errors rather than only getting one of potentially many errors with each run.

**Comment by brendandburns** [comment]
Closing this since #3106 is merged.
