### ISSUE TITLE
VM/VMSS to support Azure Metadata Security Protocol

### ISSUE THREAD

**Issue by hmyan90** [Azure/azure-cli#27729]
### Preconditions

- Need to release Python SDK support 2023-09-01

### Related command

az vm create [--enable-proxy-agent {false, true}]  [--proxy-agent-mode {Audit, Enforce}]
az vm update
az vmss create [--enable-proxy-agent {false, true}]  [--proxy-agent-mode {Audit, Enforce}]
az vmss update

### Resource Provider

Microsoft.Compute

### Description of Feature or Work Requested

PM doc: https://microsoft.sharepoint.com/:w:/r/teams/CPlat-PM/_layouts/15/Doc.aspx?sourcedoc=%7BDD02825F-7D23-4C67-B21C-6352733A8858%7D&file=Wire-Server%20Endpoint%20Security%20PM%20Spec.docx&action=default&mobileredirect=true&share=IQFfggLdI31nTLIcY1JzOohYAV82cMdRnCluKCTcaCyt91E

User can opt-in the Azure metadata security protocol for their VM by specifying the newly introduced VM or VMSS property, thus their VM can be protected from SSRF and Scorpin heart attack to IMDS and WireServer endpoints.

Need to support for vm create, vm update, vmss create, vmss update.

### Minimum API Version Required

2023-09-01

### Swagger PR link / SDK link

[[ProxyAgentSettings swagger by hmyan90 · Pull Request #26145 · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/pull/26145/)](https://github.com/Azure/azure-rest-api-specs/pull/26145/)

### Request Example

VM: https://github.com/Azure/azure-rest-api-specs/blob/c9d9a0180149e72541752672790ed642a439adfa/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-09-01/examples/virtualMachineExamples/VirtualMachine_Create_WithProxyAgentSettings.json

VMSS: https://github.com/Azure/azure-rest-api-specs/blob/c9d9a0180149e72541752672790ed642a439adfa/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-09-01/examples/virtualMachineScaleSetExamples/VirtualMachineScaleSet_Create_WithProxyAgentSettings.json

### Target Date

2023-12-30

### PM Contact

minnielahoti@microsoft.com

### Engineer Contact

huiya@microsoft.com

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
> Target Date
2023-12-30

May I ask if this ETA refers to before or around December 30th? We have two close release dates around this time, one is **2023-12-05** and the other is early January 2024, which do you prefer?

**Comment by hmyan90** [comment]
This feature is planning to be GA at the end of December, so would need to go to 2023-12-05 release if possible. thanks!

**Comment by hmyan90** [comment]
> > Target Date
> > 2023-12-30
> 
> May I ask if this ETA refers to before or around December 30th? We have two close release dates around this time, one is **2023-12-05** and the other is early January 2024, which do you prefer?

This feature is planning to be GA at the end of December, so would need to go to 2023-12-05 release if possible. thanks!

**Comment by Jing-song** [comment]
![image](https://github.com/Azure/azure-cli/assets/37168047/0f9fbba8-feec-4318-b2b8-6d20f578283b)
Hi @hmyan90  This new feature appears in the `2023-09-01` version, but the current Comte python SDK does not yet have this version. Could you please release a new version SDK to support it as soon？

**Comment by hmyan90** [comment]
> ![image](https://user-images.githubusercontent.com/37168047/282396153-0f9fbba8-feec-4318-b2b8-6d20f578283b.png) Hi @hmyan90 This new feature appears in the `2023-09-01` version, but the current Comte python SDK does not have this version. Could you please fix the swagger PR([Azure/azure-rest-api-specs/pull/26145](https://github.com/Azure/azure-rest-api-specs/pull/26145)]) to generate python SDK and release new SDK as soon?

@grizzlytheodore can we check when Python SDK will be released?

**Comment by hmyan90** [comment]
> ![image](https://user-images.githubusercontent.com/37168047/282396153-0f9fbba8-feec-4318-b2b8-6d20f578283b.png) Hi @hmyan90 This new feature appears in the `2023-09-01` version, but the current Comte python SDK does not have this version. Could you please fix the swagger PR([Azure/azure-rest-api-specs/pull/26145](https://github.com/Azure/azure-rest-api-specs/pull/26145)]) to generate python SDK and release new SDK as soon?

Hi, jingsong, checked with SDK team, the python SDK to support 2023-09-01 will be released in third week of December. So, we need to adjust the ETA to be early Jan 2024 - I'll double check with the feature's PM, most likely we are fine. thanks!
