### ISSUE TITLE
az functionapp deployment source config-zip does not return provisioningState property

### ISSUE THREAD

**Issue by evavsun** [Azure/azure-cli#27728]
### Describe the bug

Hello! I'm struggling to deploy my python code to the Azure Function using the 'az functionapp deployment source config-zip' command. Everything is successful and my function works properly, but I cannot check the provisioningState property, the return object does not contain it:
![image](https://github.com/Azure/azure-cli/assets/26879801/fbee4a5f-abb8-4a80-a220-54ba065757af)

But for the dotnet app - it does:
![image](https://github.com/Azure/azure-cli/assets/26879801/b53a7511-7525-4bee-8ce9-2874667c036c)

I use this property to determine the status of the deployment.
Could someone support me with that, maybe when we deploy to the Linux machine we are not able to get this property? How I can check the deploying status in this case or maybe I missed some configurations on Azure?

### Related command

az functionapp deployment source config-zip

### Errors

No errors

### Issue script & Debug output
I just attached a screenshot with a debug log where we can see that provisioningState is successful. Will provide more logs if needed.
![image](https://github.com/Azure/azure-cli/assets/26879801/ebe89cd9-4110-407c-826a-c6bdf506535c)
### Expected behavior

the provisioningState should be returned

### Environment Summary

azure-cli: 
![image](https://github.com/Azure/azure-cli/assets/26879801/c5ce4502-01c8-4a78-9618-983264288140)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by kamperiadis** [comment]
Hello @evavsun We only provide `provisioningState` for Windows, not for Linux. But in both scenarios, as long as you get that response with `status` set to 4, it means that the deployment has succeeded. If the deployment were still in progress, you would not return from the command. And if the operation timed out or failed, you would see an exception.

**Comment by kamperiadis** [comment]
Please let us know if this answered your question and if so, we will close this issue. Thank you.

**Comment by evavsun** [comment]
> Hello @evavsun We only provide `provisioningState` for Windows, not for Linux. But in both scenarios, as long as you get that response with `status` set to 4, it means that the deployment has succeeded. If the deployment were still in progress, you would not return from the command. And if the operation timed out or failed, you would see an exception.

Thank you. I got it. I'm struggling to find some official documentation where I can see that the status 4 - Succeeded. I would appreciate it if you provide me a link, if this document exists, of course.

**Comment by kamperiadis** [comment]
Closing as we have not heard back from the customer.
