### ISSUE TITLE
Unable to download Azure cli with Ubuntu 22.04

### ISSUE THREAD

**Issue by schlinke13** [Azure/azure-cli#27733]
### Describe the bug

We are currently unable to download the azurecli package on ubuntu 22.04.

This issue first appeared yesterday october 31st morning at 7:00 am CET. Since then no machine was able to download the package anymore. It all worked fine the day before.

### Related command

lsbRelease=$(lsb_release -cs)
sudo mkdir -p /etc/apt/keyrings
curl -sLS https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/keyrings/microsoft.gpg > /dev/null
sudo chmod go+r /etc/apt/keyrings/microsoft.gpg
echo "deb [arch=`dpkg --print-architecture` signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ '$lsbRelease' main" | sudo tee /etc/apt/sources.list.d/azure-cli.list

sudo apt-get install azure-cli

### Errors

Enable failed: failed to execute command: command terminated with exit status=32 [stdout] deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ 'jammy' main [stderr] E: The repository 'https://packages.microsoft.com/repos/azure-cli 'jammy' Release' does not have a Release file.

### Issue script & Debug output

Enable failed: failed to execute command: command terminated with exit status=32 [stdout] deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ 'jammy' main [stderr] E: The repository 'https://packages.microsoft.com/repos/azure-cli 'jammy' Release' does not have a Release file.

### Expected behavior

The installation finishes without any errors.

### Environment Summary

Ubuntu 22.04 LTS

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by schlinke13** [comment]
I found the solution. This issue appeared due to a config change, which added single quotes '$lsbRelease'
