### ISSUE TITLE
Canr disable Enable Health Probes using AZ CLI

### ISSUE THREAD

**Issue by gsuttie** [Azure/azure-cli#27744]
### Describe the bug

When running the following command it doesn't seem like there is a way to disable the health probe

az afd origin-group create `
    --resource-group $resourceGroupName `
    --origin-group-name $originGroupName `
    --profile-name $frontDoorName `
    --probe-request-type GET `
    --probe-protocol Http `
    --probe-interval-in-seconds 60 `
    --probe-path / `
    --sample-size 4 `
    --successful-samples-required 3 `
    --additional-latency-in-milliseconds 50 `
    --output none

### Related command

az afd origin-group create 

### Errors

No errors but I don't see how to disable the 'Enable Health probes tickbox'

### Issue script & Debug output

az afd origin-group create `
    --resource-group $resourceGroupName `
    --origin-group-name $originGroupName `
    --profile-name $frontDoorName `
    --probe-request-type GET `
    --probe-protocol Http `
    --probe-interval-in-seconds 60 `
    --probe-path / `
    --sample-size 4 `
    --successful-samples-required 3 `
    --additional-latency-in-milliseconds 50 `
    --output none

### Expected behavior

origin group doesnt have 'Enable Heath probes ticket'

### Environment Summary

azure-cli                         2.53.1

core                              2.53.1
telemetry                          1.1.0

Extensions:
account                            0.2.5
aks-preview                      0.5.149
application-insights              0.1.19
azure-devops                      0.26.0
azure-firewall                    0.14.8
desktopvirtualization               0.2.0
front-door                        1.0.17

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by surlypants** [comment]
january 2024 and still impossible? neither az cli nor pwsh

**Comment by t-bzhan** [comment]
Hi @gsuttie/ @surlypants , that is a bug. We will try to fix it in next release. As a workaround, you could try to use below command as a workaround:

```
az afd origin-group update --remove "healthProbeSettings" --resource-group bo-private --origin-group-name og111 --profile-name bzhan-test111 --debug
```
