### ISSUE TITLE
Subcommand for returning a valid accessToken

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#2774]
`gcloud config config-helper` returns a JSON blob with a number of things about the current configuration of the CLI, along with an properly-refreshed, active token for applications to use. This is a feature request for a similar functionality in the `az` CLI.

Scenario: In Kubernetes, we are trying to emulate the Google Auth plugin which uses `gcloud config config-helper` to get a refreshed accessToken and then uses it for authentication in it's own ways. Currently, the Azure implementation reaches into `~/.azure/` directly to read the access token. It would be much better if this was done via os.Exec'ing `az config config-helper` or something similar, so that the CLI can refresh the token if needed and then return it.

Can we create a command like `config config-helper` in `az`?

cc: @brendandburns

**Comment by colemickens** [comment]
cc: @anhowe as FYI

**Comment by yugangw-msft** [comment]
@colemickens, i should get it done early next week. Let me know if there are any plan change at your end.
