### ISSUE TITLE
Updation of CLI for AzureStackHCI

### ISSUE THREAD

**Issue by NikitaSingh-ms** [Azure/azure-cli#27741]
Resource Provider

AzureStackHCI
Description of Feature or Work Requested

With api version refresh, we want the CLI to be refreshed as well.

Extension: https://github.com/Azure/azure-cli-extensions/tree/main/src/stack-hci

Minimum API Version Required

2023-08-01-preview 
Swagger Link

https://github.com/Azure/azure-rest-api-specs-pr/tree/RPSaaSMaster/specification/azurestackhci/resource-manager/Microsoft.AzureStackHCI/preview/2023-08-01-preview

Target Date

November, 2023

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jsntcy** [comment]
Will plan it in next sprint

**Comment by priyjain358** [comment]
@Jing-song it would be helpful if you could share out a list of the new APIs, we will confirm what all we want to add in this release

**Comment by Jing-song** [comment]
Hi @priyjain358 , Additional APIs than the existing version(2023-03-01) include: 3 APIs in [edgedevice.json](https://github.com/Azure/azure-rest-api-specs-pr/blob/8dcf9ff319353a914627a75c7e7eb2e6afcdaf56/specification/azurestackhci/resource-manager/Microsoft.AzureStackHCI/preview/2023-08-01-preview/edgeDevices.json#L41-L328), and 2 APIs in [deploymentsetting.json](https://github.com/Azure/azure-rest-api-specs-pr/blob/8dcf9ff319353a914627a75c7e7eb2e6afcdaf56/specification/azurestackhci/resource-manager/Microsoft.AzureStackHCI/preview/2023-08-01-preview/deploymentSettings.json#L42-L277)

`/{resourceUri}/providers/Microsoft.AzureStackHCI/edgeDevices`
`/{resourceUri}/providers/Microsoft.AzureStackHCI/edgeDevices/{edgeDeviceName}`
`/{resourceUri}/providers/Microsoft.AzureStackHCI/edgeDevices/{edgeDeviceName}/validate`
`/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AzureStackHCI/clusters/{clusterName}/deploymentSettings`
`/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AzureStackHCI/clusters/{clusterName}/deploymentSettings/{deploymentSettingsName}`

Please help confirm whether to add new commands for them and add preview tags for new commands, thanks!

**Comment by Jing-song** [comment]
**Update:**
![image](https://github.com/Azure/azure-cli/assets/37168047/a8acbb12-803f-4d79-95dd-398075c50b1b)
Finally decided to use the 2023-08-01 version
