### ISSUE TITLE
az servicebus namespace authorization-rule keys list gives redacted value as ***

### ISSUE THREAD

**Issue by sahuabhi** [Azure/azure-cli#27751]
### Describe the bug

when using az servicebus namespace authorization-rule keys list gives redacted value as *** in the output.
also on az servicebus queue authorization-rule keys list gives redacted value as ***.

![image](https://github.com/Azure/azure-cli/assets/45171937/86496c1e-2fa1-4437-8263-1531bb081ef4)

### Related command

az servicebus namespace authorization-rule keys list 
az servicebus queue authorization-rule keys list 

### Errors

The command succeeds but the output is redacted which makes the command useless

### Issue script & Debug output

az servicebus namespace authorization-rule keys list 
az servicebus queue authorization-rule keys list 

### Expected behavior

This should give the keys and connection string in output.

### Environment Summary

azure-cli                         2.53.1

core                              2.53.1
telemetry                          1.1.0

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Program Files\Common Files\AzureCliExtensionDirectory'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]

### Additional context

this also obeserved when getting connection string for Redis using command -->az redis list-keys

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by schaudhari6254888** [comment]
![imags](https://github.com/Azure/azure-cli/assets/111409694/2930e5e5-1973-485c-a7f6-6c94e7e50da4)

Hey @sahuabhi , I cannot reproduce your issue from portal or local CLI env. this command is working fine at our end.
Can you pls tell me, how I can reproduce this or some more information about the bug.
