### ISSUE TITLE
Update to application gateway address pool reverts unrelated previous app gateway address pool update

### ISSUE THREAD

**Issue by agra6475** [Azure/azure-cli#27771]
### Describe the bug

Using azure devops to update multiple backend pools of a single application gateway. 
Updates to the application gateway are done concurrently.

#### Job 1
One job executed this command to update a backend pool.

```powershell
az network application-gateway address-pool update `
    --gateway-name someName `
    --name oneBackend `
    --resource-group someResourceGroup `
    --servers someNewPrivateIP
```
The command completes at 7:59:40
![image](https://github.com/Azure/azure-cli/assets/149966774/07f22d7d-58f4-4c7d-bf65-83e40b6555a1)
And the provisioning state of the application gateway changes as expected
![image](https://github.com/Azure/azure-cli/assets/149966774/f59c064c-96fe-4351-ad25-c012f1e81a64)

At  7:59:45 the provisioning state changes again as the app gateway has completed the update
![image](https://github.com/Azure/azure-cli/assets/149966774/42b92deb-7595-4463-a1b4-8dd2097ef7d6)

#### Job 2
At 7:59:51 the following command completes
```powershell
az network application-gateway address-pool update `
  --gateway-name someName  `
  --name aDifferentbackend `
  --resource-group someResourceGroup `
  --servers someNewPrivateIP
```
As expected it updates `aDifferentbackend`
![image](https://github.com/Azure/azure-cli/assets/149966774/abb9a11e-dae2-4cfb-8339-95f230d16b8d)

What is not expected is that it reverts the change to `oneBackend`
![image](https://github.com/Azure/azure-cli/assets/149966774/568390a8-c1a0-434d-a3a1-770d5074e6e8)

### Related command

Job 1 command
```powershell
az network application-gateway address-pool update `
    --gateway-name someName `
    --name oneBackend `
    --resource-group someResourceGroup `
    --servers someNewPrivateIP
```

Job 2 command
```powershell
az network application-gateway address-pool update `
  --gateway-name someName  `
  --name aDifferentbackend `
  --resource-group someResourceGroup `
  --servers someNewPrivateIP
```

### Errors

No error happened during these commands.

### Issue script & Debug output

Not able to reproduce it.
Only has the output from the first command.

```json
{
  "backendAddresses": [
    {
      "ipAddress": "10.0.0.7"
    }
  ],
  "etag": "W/\"3fe05e13-ff6d-4907-89a9-f2a3651b05b0\"",
  "id": "/subscriptions/___/resourceGroups/___/providers/Microsoft.Network/applicationGateways/___/backendAddressPools/oneBackend",
  "name": "oneBackend",
  "provisioningState": "Succeeded",
  "resourceGroup": "___",
  "type": "Microsoft.Network/applicationGateways/backendAddressPools"
}
```

### Expected behavior

Expected `az network application-gateway address-pool update` to only update the backend address pool matching the name of the address pool provided in the command.

Did not expect `az network application-gateway address-pool update` to revert updates to other, recently updated, address pools.

### Environment Summary

Since two different azure devops pipeline jobs executed the commands i will provide the version output from each job when they executed the step that included the commands.

#### Job 1
azure-cli                         2.53.1

core                              2.53.1
telemetry                          1.1.0

Extensions:
application-insights               1.0.0
azure-devops                      0.26.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/opt/az/azcliextensions'

Python (Linux) 3.10.10 (main, Oct 24 2023, 06:10:14) [GCC 11.4.0]

#### Job 2
azure-cli                         2.53.1

core                              2.53.1
telemetry                          1.1.0

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/opt/az/azcliextensions'

Python (Linux) 3.10.10 (main, Oct 24 2023, 06:10:14) [GCC 11.4.0]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by agra6475** [comment]
Why was the bug label removed from this issue? Is this not considered a bug or am i misunderstanding how these labels work?
