### ISSUE TITLE
`az identity list-operations` is Confusing and Misleading

### ISSUE THREAD

**Issue by sfc-gh-aivanou** [Azure/azure-cli#27814]
### Describe the bug

I want to know what roles and permissions a particular managed identity has, so I thought that `az identity list-operations`
would provide me this information, based on its name.
But it does not even accept name of managed identity o resource group, which makes this operation very confusing and useless. 

### Related command

az identity list-operations

### Errors

Misleading operation

### Issue script & Debug output

---

### Expected behavior

I would expect that this command `az identity list-operations` would output roles and permissions associated with the particular identity, but it outputs completely different thing. 

### Environment Summary

azure-cli                         2.53.1

core                              2.53.1
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/opt/homebrew/Cellar/azure-cli/2.53.1/libexec/bin/python'
Extensions directory '/Users/aivanou/.azure/cliextensions'

Python (Darwin) 3.10.13 (main, Aug 24 2023, 12:59:26) [Clang 15.0.0 (clang-1500.0.40.1)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
