### ISSUE TITLE
`az functionapp create` can't choose container app's rg

### ISSUE THREAD

**Issue by iotalambda** [Azure/azure-cli#27829]
**Related command**
```
az functionapp create
	--name {NAME}
	--storage-account {STORAGE}
	--environment {MENV}
	--resource-group {RG}
	--functions-version 4
	--runtime dotnet-isolated
	--image {IMAGE}
	--registry-server {REGISTRY_SERVER}
	--registry-username {REGISTRY_USERNAME}
	--registry-password {REGISTRY_PASSWORD}
	--disable-app-insights true
```

**Is your feature request related to a problem? Please describe.**
The command CREATES A NEW RESOURCE GROUP called `{MENV}_FunctionApp_{RANDOM_IDENTIFIER}` with the container app inside it.

**Describe the solution you'd like**
I'd like to be able to choose the target resource group. Or at least the container app should be created to the same rg I provided to the command.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by iotalambda** [comment]
Closed as double https://github.com/Azure/azure-functions-on-container-apps/issues/36
