### ISSUE TITLE
Curl is missing from latest tag image

### ISSUE THREAD

**Issue by usnea-longissima** [Azure/azure-cli#27844]
### Describe the bug

curl is missing from image tagged "latest"

### Related command

curl

### Errors

bash: curl: command not found

### Issue script & Debug output

bash: curl: command not found

### Expected behavior

curl should be available

### Environment Summary

65d1dae9f6b4:/# az --version
azure-cli                         2.54.0

core                              2.54.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/usr/local/bin/python'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.11.6 (main, Oct 19 2023, 05:43:48) [GCC 12.2.1 20220924]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by juanhz0101** [comment]
> ### Describe the bug
> curl is missing from image tagged "latest"
> 
> ### Related command
> curl
> 
> ### Errors
> bash: curl: command not found
> 
> ### Issue script & Debug output
> bash: curl: command not found
> 
> ### Expected behavior
> curl should be available
> 
> ### Environment Summary
> 65d1dae9f6b4:/# az --version azure-cli 2.54.0
> 
> core 2.54.0 telemetry 1.1.0
> 
> Dependencies: msal 1.24.0b2 azure-mgmt-resource 23.1.0b2
> 
> Python location '/usr/local/bin/python' Extensions directory '/root/.azure/cliextensions'
> 
> Python (Linux) 3.11.6 (main, Oct 19 2023, 05:43:48) [GCC 12.2.1 20220924]
> 
> Legal docs and information: aka.ms/AzureCliLegal
> 
> Your CLI is up-to-date.
> 
> ### Additional context
> _No response_

We have the same problem today, a quick fix this you can use the version 2.9.1 of image:

`mcr.microsoft.com/azure-cli:2.9.1`

but actually this change was added on this pull request: https://github.com/Azure/azure-cli/pull/27567

**Comment by juanhz0101** [comment]
@usnea-longissima We have the same problem today, a quick fix this you can use the version 2.9.1 of image:

`mcr.microsoft.com/azure-cli:2.9.1`

but actually this change was added on this pull request: https://github.com/Azure/azure-cli/pull/27567

**Comment by usnea-longissima** [comment]
Ah, thanks for the PR reference.  I wonder why the new image wasn't pushed to the latest tag when that pull request was merged 3 weeks ago.
