### ISSUE TITLE
az bicep can produce bad output when using --stdout option

### ISSUE THREAD

**Issue by mvromer-ge** [Azure/azure-cli#27855]
### Describe the bug

If the Bicep CLI hasn't been installed or it otherwise not available, then calling an `az bicep` command will trigger an install of Bicep. If the `az bicep` command being called supports the `--stdout` parameter and is called with it, then the standard output stream actually gets polluted with status messages from the Bicep installation. This can result in badly formatted output that can't be used in downstream processes.

### Related command

`az bicep generate-params`

Probably any other `az bicep` command that supports the `--stdout` option.

### Errors

The actual error depends on the downstream command consuming the standard output of the `az bicep` command being called. In my case I was piping the output to PowerShell's `ConvertFrom-Json` cmdlet and received the following error:

```
ConvertFrom-Json: Conversion from JSON failed with error: Error parsing Infinity value. Path '', line 1, position 2.
```

### Issue script & Debug output

Consider the following `main.bicep` file:

```bicep
param name string
output message string = 'Hello, ${name}'
```

Running the following PowerShell script fails:

```powershell
# NOTE: Purposely uninstall Bicep CLI to simulate scenario where az bicep called
# when Bicep CLI is not already present.
az bicep uninstall

# This is the actual line I would want to execute but will fail.
az bicep generate-params --file ./main.bicep --stdout | ConvertFrom-Json
```

The pipeline above results in the following error output:

```
ConvertFrom-Json: Conversion from JSON failed with error: Error parsing Infinity value. Path '', line 1, position 2.
```

If I do the above again but instead 1) capture the output of `az bicep generate-params` to a variable and 2) output that variable, the reason for the JSON conversion becomes apparent:

```powershell
az bicep uninstall

$paramContent = az bicep generate-params --file ./main.bicep --stdout
Write-Host $paramContent
```

The `Write-Host` cmdlet above produces the following output:

```
Installing Bicep CLI v0.23.1... Successfully installed Bicep CLI to "/Users/212341174/.azure/bin/bicep". {   "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",   "contentVersion": "1.0.0.0",   "parameters": {     "name": {       "value": ""     }   } }
```

As you can see, the standard output actually contained more than just the expected JSON. It contained all the status output from the implicit Bicep installation.

### Expected behavior

If `--stdout` is passed, then standard output should NOT contain status messages from ancillary tasks the CLI might perform. To contrast, if I perform the following after ensuring Bicep is installed, then the standard output is not corrupted:

```powershell
az bicep install
$paramContent = az bicep generate-params --file ./main.bicep --stdout
Write-Host $paramContent
```

The output in this case is only the expected JSON:

```
{   "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",   "contentVersion": "1.0.0.0",   "parameters": {     "name": {       "value": ""     }   } }
```

### Environment Summary

azure-cli                         2.53.0 *

core                              2.53.0 *
telemetry                          1.1.0

Extensions:
account                            0.2.5
containerapp                      0.3.41
front-door                        1.0.17

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/opt/homebrew/Cellar/azure-cli/2.53.0/libexec/bin/python'
Extensions directory '/Users/212341174/.azure/cliextensions'

Python (Darwin) 3.10.13 (main, Aug 24 2023, 22:36:46) [Clang 14.0.3 (clang-1403.0.22.14.1)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
