### ISSUE TITLE
Customer control knobs to block traffic types on ExpressRoute.

### ISSUE THREAD

**Issue by jjcv-msft** [Azure/azure-cli#27854]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Resource Provider

Microsoft.Network/virtualnetworkgateways and Microsoft.Network/expressRouteGateways

### Description of Feature or Work Requested

We have added two new bool properties to our virtual network gateway resource and one to our ExpressRoute gateway resource. These properties can be used by the customer to allow/block certain traffic patterns on the gateway.

The original Swagger change was merged in 2022 but we are only getting ready to release the actual feature now, hence I would like to understand better how you plan to use the API version entry in the form below.

### Minimum API Version Required

N/A - could you reach out to me to understand more about this

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/20831

The original Swagger change was merged in 2022 but we are only getting ready to release the actual feature now, hence I would like to understand better how you plan to use the API version entry in the form above

### Target Date

2023-12-06

### PM Contact

mialdrid

### Engineer Contact

javico

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
@jjcv-msft Just clarify--`Minimum API Version Required` means from which API version, one feature starts to be supported.

It's quite important to us, since we need to decide whether to bump version according to it.
