### ISSUE TITLE
Error when trying to create storage account "--kind BlobStorage"

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#2785]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: dev_setup.py

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: latest master

**OS Version:** What OS and version are you using?  
Answer here: Windows 10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

---

### Description

If I run:
`az storage account create -g {rg} -n {name} -l westus --kind BlobStorage --sku Standard_LRS`

I get an error: 
"The storage account property 'accessTier' is invalid or cannot be set at this time."

In reality, --access-tier is required when --kind is BlobStorage. We should update the validation to reflect this, or apply a default when creating a BlobStorage account (the portal default is Hot).

**Comment by mxplusb** [comment]
I get the same error with this in Python:
```
storage_async_operation = storage_client.storage_accounts.create(
        group_name, storage_account_name,
        StorageAccountCreateParameters(
            sku=Sku(SkuName.standard_ragrs),
            kind=Kind.blob_storage,
            location=k
        )
    )
```

**Comment by williexu** [comment]
Closing this as service now returns a proper message when access-tier is missing:
-"Account property accessTier is required for the request."
