### ISSUE TITLE
Trusted launch default | az disk create with managed image

### ISSUE THREAD

**Issue by AjKundnani** [Azure/azure-cli#27872]
### Describe the bug

Creating disk from [Managed image](https://learn.microsoft.com/en-us/azure/virtual-machines/capture-image-resource) is failing with below error after implementation of Trusted launch default in 2.54.0 release.

The command failed with an unexpected error. Here is the traceback:
'child_name_1'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/vm/custom.py", line 410, in create_managed_disk
KeyError: 'child_name_1'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

### Related command

`az disk create`

### Errors

The command failed with an unexpected error. Here is the traceback:
'child_name_1'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/vm/custom.py", line 410, in create_managed_disk
KeyError: 'child_name_1'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

### Issue script & Debug output

**az disk create -n climig1disk -g $rgName --image-reference "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/DEMOACGRG/providers/Microsoft.Compute/images/ws2022-azureedition-managedimage" --debug**

az disk create -n climig1disk -g $rgName --image-reference "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/DEMOACGRG/providers/Microsoft.Compute/images/ws2022-azureedition-managedimage" --debug
cli.knack.cli: Command arguments: ['disk', 'create', '-n', 'climig1disk', '-g', 'ps1711rg', '--image-reference', '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/DEMOACGRG/providers/Microsoft.Compute/images/ws2022-azureedition-managedimage', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x000001B359C6F560>, <function OutputProducer.on_global_arguments at 0x000001B359DF5C60>, <function CLIQuery.on_global_arguments at 0x000001B359E237E0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'disk': ['azure.cli.command_modules.vm']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: vm                        0.227        57       265
cli.azure.cli.core: Total (1)                 0.227        57       265
cli.azure.cli.core: Loaded 57 groups, 265 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : disk create
cli.azure.cli.core: Command table: disk create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x000001B35CCB94E0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\testuser\.azure\commands\2023-11-17.20-45-50.disk_create.21924.log'.
az_command_data_logger: command args: disk create -n {} -g {} --image-reference {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x000001B35CCF79C0>]
cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2022_11_01.models' has no attribute 'RestorePointEncryptionType'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/profiles/_shared.py", line 655, in _get_attr
AttributeError: module 'azure.mgmt.compute.v2022_11_01.models' has no attribute 'RestorePointEncryptionType'

cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x000001B35CCF7A60>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x000001B35CCF7BA0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x000001B359DF5D00>, <function CLIQuery.handle_query_parameter at 0x000001B359E23880>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x000001B35CCF7B00>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ResourceManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\testuser\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\testuser\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/kerberos', 'tenant_region_scope': 'WW', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? True
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 1d0d9908-d6e4-42a9-8afd-dafcb212e88d
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/ps1711rg?api-version=2022-09-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '316c0373-855c-11ee-8656-8038fba89e1c'
cli.azure.cli.core.sdk.policies:     'CommandName': 'disk create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-n -g --image-reference --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.54.0 (MSI) azsdk-python-azure-mgmt-resource/23.1.0b2 Python/3.11.5 (Windows-10-10.0.22621-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/ps1711rg?api-version=2022-09-01 HTTP/1.1" 200 278
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '00c614cc-8419-4698-874a-2ba8db9d8ff8'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '00c614cc-8419-4698-874a-2ba8db9d8ff8'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'JIOINDIAWEST:20231117T151551Z:00c614cc-8419-4698-874a-2ba8db9d8ff8'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Fri, 17 Nov 2023 15:15:51 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '278'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"id":"/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/ps1711rg","name":"ps1711rg","type":"Microsoft.Resources/resourceGroups","location":"westus3","properties":{"provisioningState":"Succeeded"}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/vm/custom.py", line 410, in create_managed_disk
KeyError: 'child_name_1'

cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: 'child_name_1'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/vm/custom.py", line 410, in create_managed_disk
KeyError: 'child_name_1'
az_command_data_logger: 'child_name_1'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/vm/custom.py", line 410, in create_managed_disk
KeyError: 'child_name_1'
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x000001B35CCB9760>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 2.226 seconds (init: 0.471, invoke: 1.755)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 6959 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\testuser\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

Disk created as Gen1 or Gen2 dependent on HyperV generation of managed image.
Recommendation printed to end user for considering upgrade to Trusted launch.

### Environment Summary

azure-cli                         2.54.0

core                              2.54.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\ajkundna\.azure\cliextensions'

Python (Windows) 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

Unable to check if your CLI is up-to-date. Check your internet connection.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by AjKundnani** [comment]
> Hi @AjKundnani Find similar issue #24908.
> 
> Issue title	Meet problems when changing the data disk size and sku when creating from an image
> Create time	2022-12-15
> Comment number	1
> Possible solution: The error message in the new issue is the same as the one in the old issue, which is caused by a KeyError: 'child_name_1'. The old issue suggests that the problem might be related to the format of the `--image-reference` parameter. The format should be like this: `/Subscriptions/{subscriptionId}/Providers/Microsoft.Compute/Locations/westus/Publishers/{publisher}/ArtifactTypes/VMImage/Offers/{offer}/Skus/{sku}/Versions/1.0.0`.
> 
> In the new issue, the user is creating a disk from a managed image, so they might want to try using `--gallery-image-reference` and `--gallery-image-reference-lun` instead of `--image-reference`. If the problem persists, they should follow the recommendations in the old issue and check the format of the `--image-reference` parameter.
> 
> Please confirm if this resolves your issue.

No this is different issue.

**Comment by yanzhudd** [comment]
> az disk create -n climig1disk -g $rgName --image-reference "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/DEMOACGRG/providers/Microsoft.Compute/images/ws2022-azureedition-managedimage" --debug

Hi @AjKundnani,
In fact, the `--image-reference` is: ID or URN (publisher:offer:sku:version) of the image from which to create a disk, and the format shoule be like: "MicrosoftWindowsServer:WindowsServer:2022-datacenter-smalldisk-g2:latest" or "/Subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/Providers/Microsoft.Compute/Locations/westus/Publishers/Canonical/ArtifactTypes/VMImage/Offers/0001-com-ubuntu-server-jammy/Skus/22_04-lts-gen2/Versions/22.04.202311010".

If you want to create disk based on a gallery image, please use `--gallery-image-reference` instead.

**Comment by yanzhudd** [comment]
Hi @AjKundnani,
I see... This issue is caused by the feature #23614: 

> ## Scenario 1 - User creates OS disk from PIR image using `az disk create --image-reference`
> 
> Present Behavior | Updated Behavior post change
> -|-
> New disk with create option FromImage:<ol><li>User runs command `az disk create -n diskname -g diskrgname --image-reference 'urnofPIRimage'`<li>OS Disk with image reference and Premium_LRS SKU is created.</li></ol> | Updated default parameters and sequence:<ol><li>User runs command `az disk create -n diskname -g diskrgname --image-reference 'urnofPIRimage'`<li>CLI queries image capabilities using API [Virtual Machines Images GET API](https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-images/get?tabs=HTTP)<ul><li>For Gen2, use property **hyperVGeneration** with value of **V2**</li></ul><li>Conditions:<ul><li>If PIR image supports **hyperVGeneration = v2**, enable following parameters by default:<ul><li>--hyper-v-generation with value **V2**<li>--security-type with value **TrustedLaunch**</li></ul><li>Else, Disk will get deployed per user inputs. If securityType is not set to _TrustedLaunch_, Notification message should be printed for user. **Notification Message**:  `Consider upgrading security for your workloads using Azure Trusted Launch VMs. To know more about Trusted Launch, please visit https://aka.ms/TrustedLaunch`</li></ul></ol>

This scenario would query image capabilities using API [Virtual Machines Images GET API](https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-images/get?tabs=HTTP), whose request body contains info of publisher_name, offer, skus and version. Therefore, we would parse the input of `--image-reference` into these parts.

However, your input "az disk create -n climig1disk -g $rgName --image-reference "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/DEMOACGRG/providers/Microsoft.Compute/images/ws2022-azureedition-managedimage" --debug" cannot be parsed into these required parts, then the error reported.

So, let me check with you if we would change the logic to: if the parsing failed, we would not query image capabilities and thus the warning log would not be shown.

**Comment by AjKundnani** [comment]
> So, let me check with you if we would change the logic to: if the parsing failed, we would not query image capabilities and thus the warning log would not be shown.

@yanzhudd - Is it feasible to implement following (considering performance impact if any into consideration):
1. Check for platform image, if parsing fails go to 2,
2. Check for managed image API, if error go to 3.
3. Cannot validate source image, deploy as per end user inputs with recommendation to upgrade to Trusted launch if `securityType` is not `TrustedLaunch`.

**Comment by yanzhudd** [comment]
Hi @AjKundnani,
when I fix this issue, as I input a managed image id as the value of `--image-reference`, an error reported from service side:
![image](https://github.com/Azure/azure-cli/assets/105691024/6cd1ded1-7273-4ff1-a990-bc286a98cde2)
My request body:
![image](https://github.com/Azure/azure-cli/assets/105691024/4d46a1aa-cc0a-4755-9ea5-31739eed56b9)

Let me check with you whether the managed image can be the value of imageReference or not? If you need a private package to repro this error, please let me know.

**Comment by AjKundnani** [comment]
> Let me check with you whether the managed image can be the value of imageReference or not? If you need a private package to repro this error, please let me know.

@yanzhudd - Disk team confirmed that OS disk create using managed image is not supported by backend API. We should be good to close this issue.
