### ISSUE TITLE
az sql server show not returning the administrator login password

### ISSUE THREAD

**Issue by peterj** [Azure/azure-cli#2789]
I am trying to get the admin password for the SQL server instance. If I run ```az sql server show```, the ```administratorLoginPassword``` is always null. 

Is there a way I can get the password or full connection string?

**Comment by peterj** [comment]
Any updates on this issue?

**Comment by tjprescott** [comment]
It is common that the services will not return passwords, treating them as write-only. However, @jaredmoo for the question related to connection strings. I don't see a command currently that does that.

**Comment by peterj** [comment]
If that's the case for passwords, am right to assume that the same would be true for connection strings, since those usually contain a password as well? 

Also, another thing that I noticed is that the connection string is visible in the portal, but doesn't contain the password either...

**Comment by tjprescott** [comment]
Possibly. The CS may contain some kind of secure hash or encoding that will allow it to authenticate without exposing the actual password--or it may have a blank where you'd be expected to fill in the password.  @jaredmoo can you clarify?

**Comment by jaredmoo** [comment]
No, there is no way to get the password after the server is created. This is by design. If we showed the password then readonly privilege in ARM on a SQL DB server would instantly escalate to full admin privilege in the data plane. Not good. 

A command to show sql connection strings would be nice to have. Great idea.

**Comment by alexvicegrab** [comment]
Would be great to get a connection string template with placeholders for the username/password. I can see these on the portal, but can't see an option to get them via the CLI.

**Comment by jaredmoo** [comment]
This is done and can be closed. Thanks!
