### ISSUE TITLE
Spelling error on "az security assessment"

### ISSUE THREAD

**Issue by lewism77** [Azure/azure-cli#27909]
### Describe the bug

Two misspellings present of "programmatic" as "progremmatic" on https://learn.microsoft.com/en-us/cli/azure/security/assessment?view=azure-cli-latest#az-security-assessment-create-optional-parameters

### Related command

az security assessment create

### Errors

n/a

### Issue script & Debug output

n/a

### Expected behavior

Spelling of programmatic is corrected.

### Environment Summary

n/a

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
The code is here:

https://github.com/Azure/azure-cli/blob/a55dcd9bd7fc4b1b82deda8e5334377ce89bf9a0/src/azure-cli/azure/cli/command_modules/security/_params.py#L78-L79

@lewism77, do you mind submitting a PR so that you can get the credit for fixing it? Thanks!

**Comment by lewism77** [comment]
Thanks, I have created a PR
