### ISSUE TITLE
Azure CLI Msi borked install leads to memory hog and spawns 50+ python processes

### ISSUE THREAD

**Issue by wUEZRs** [Azure/azure-cli#27908]
### Describe the bug

I played around with Azure CLI many months ago to use Bastion RDP. 

Then a few weeks ago while doing some other MSI work I noticed an install error because "Azure CLI" msi was in progress of "doing something"

That's weird, as I haven't dealt with Azure CLI in months. Then lately my PC grinded to a halt over a few days. Task Manager showed continously spawning Python.exe processes. I found the path in Azure CLI folder. Had to reinstall the machine

So somewhere Azure CLI completely messed up the computer. Uninstalling the CLI lead to "Installer is no longer responding"

### Related command

x

### Errors

x

### Issue script & Debug output

x

### Expected behavior

x

### Environment Summary

x

### Additional context

x

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by wUEZRs** [comment]
Thanks, this is the same problem and I will comment in the other issue.

tor. 23. nov. 2023 kl. 13:15 skrev Yong Zhang ***@***.***>:

**Comment by bebound** [comment]
As stated in the https://github.com/Azure/azure-cli/issues/26934, we can't repro it and it doesn't appear to be a problem with the CLI.

Duplicated of https://github.com/Azure/azure-cli/issues/26934
