### ISSUE TITLE
"az storage account key list" throws 32-bit Python warning

### ISSUE THREAD

**Issue by mortenjoenby** [Azure/azure-cli#27917]
### Describe the bug

I am running Windows 11 with latest version of azure-cli (2.54.0).
A UserWarning is thrown:
D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\cryptography/hazmat/backends/openssl/backend.py:27: UserWarning: You are using cryptography on a 32-bit Python on a 64-bit Windows Operating System. Cryptography will be significantly faster if you switch to using a 64-bit Python.

### Related command

az storage account keys list --account-name somename --subscription somesub --query "[?keyName=='key1'].{Value:value}" -o tsv

### Errors

D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\cryptography/hazmat/backends/openssl/backend.py:27: UserWarning: You are using cryptography on a 32-bit Python on a 64-bit Windows Operating System. Cryptography will be significantly faster if you switch to using a 64-bit Python.

### Issue script & Debug output

az storage account keys list --account-name somename --subscription somesub --query "[?keyName=='key1'].{Value:value}" -o tsv
D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\cryptography/hazmat/backends/openssl/backend.py:27: UserWarning: You are using cryptography on a 32-bit Python on a 64-bit Windows Operating System. Cryptography will be significantly faster if you switch to using a 64-bit Python.

### Expected behavior

I would expect azure-cli 64-bit to actually use Python 64-bit instead of 32-bit.
Since I am looping over a bunch of Storage Accounts I get this warning every time.

### Environment Summary

```
azure-cli                         2.54.0

core                              2.54.0
telemetry                          1.1.0

Extensions:
account                            0.2.5
aks-preview                      0.5.140
costmanagement                     0.2.1
reservation                        0.3.0
storage-blob-preview               0.7.2
storage-preview                    0.8.4
vm-repair                          0.5.3

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Users\mojo\scoop\apps\azure-cli\current\python.exe'
Extensions directory 'C:\Users\mojo\.azure\cliextensions'

Python (Windows) 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:21:31) [MSC v.1936 32 bit (Intel)]
```

### Additional context

I have checked for other Github issues like https://github.com/Azure/azure-cli/issues/27115, but it seems that does not solve the problem when running on my own client.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
The

**Comment by jiasli** [comment]
The Python you are using is `C:\Users\mojo\scoop\apps\azure-cli\current\python.exe` and it is 32-bit:

```
Python (Windows) 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:21:31) [MSC v.1936 32 bit (Intel)]
```

This is not the official Azure CLI package. Could you let us know how you installed Azure CLI?

Please follow https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-windows to install the official x64 MSI package and you will see

```
> az --version
azure-cli                         2.54.0

core                              2.54.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\xxx\.azure\cliextensions'

Python (Windows) 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
```

**Comment by mortenjoenby** [comment]
Hi Jiashuo.
I’m using the Scoop package manager and running:
scoop install main/azure-cli

Not sure why that doesn’t use 64-bit Python.
I guess I will have to uninstall that one and use the msi installer.

Best regards / med venlig hilsen,

Morten
________________________________
Fra: Jiashuo Li ***@***.***>
Sendt: Friday, November 24, 2023 3:27:16 PM
Til: Azure/azure-cli ***@***.***>
Cc: Morten Jønby ***@***.***>; Manual ***@***.***>
Emne: Re: [Azure/azure-cli] "az storage account key list" throws 32-bit Python warning (Issue #27917)


External e-mail.


The Python you are using is C:\Users\mojo\scoop\apps\azure-cli\current\python.exe and it is 32-bit:

Python (Windows) 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:21:31) [MSC v.1936 32 bit (Intel)]


This is not the official Azure CLI package. Could you let us know how you installed Azure CLI?

Please follow https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-windows to install the official x64 MSI package and you will see

> az --version
azure-cli                         2.54.0

core                              2.54.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\xxx\.azure\cliextensions'

Python (Windows) 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]

**Comment by bebound** [comment]
The scoop only contains 32bit CLI https://github.com/ScoopInstaller/Main/blob/dca79710e7691a03ffe97e45fe67f17e18e6a345/bucket/azure-cli.json
Please follow the official installation document.

**Comment by mortenjoenby** [comment]
Thanks @bebound .
I did that and it works. Don't know why the Scoop installer used 32-bit. I find that strange, but that's how it is.
