### ISSUE TITLE
Deployment failure inner error not shown in many instances

### ISSUE THREAD

**Issue by BorisB2015** [Azure/azure-cli#2792]
Az CLI 2.0.2.

Run the following command:

```
az vm create -g JMP-AZ10-RHT --name bb-custom-vm100 --image rhel-custom-71 --admin-username azureuser --no-wait
```
Got this error:

>The template deployment 'vm_deploy_QcfOZ81VGBVOYQxXRfI9GjQJxtSBW8WY' is not valid according to the validation procedure. The tracking id is 'c82d598c-50c2-442b-8d0b-43c11da1479e'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.

This error is non-actionable. The inner error, however, clearly indicates what failed in the validation:

```json
"statusMessage": "{\"error\":{\"code\":\"InvalidTemplateDeployment\",\"message\":\"The template deployment 'vm_deploy_QcfOZ81VGBVOYQxXRfI9GjQJxtSBW8WY' is not valid according to the validation procedure. The tracking id is 'c82d598c-50c2-442b-8d0b-43c11da1479e'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.\",\"details\":[{\"code\":\"QuotaExceeded\",\"message\":\"Operation results in exceeding quota limits of Core. Maximum allowed: 100, Current in use: 100, Additional requested: 1.\"}]}}"
    },
```

Copy-pasting tail end of the above message: 

**Operation results in exceeding quota limits of Core. Maximum allowed: 100, Current in use: 100, Additional requested: 1.**

My request here is to pull this inner information and provide it in the CLI error message as it saves me loading the portal, going to activity log and finding it there. 

If there is already a way to get this in some detailed log of the az CLI execution, the error message should be expanded to provide the info on how to find it (e.g. azure CLI 1.0 was referring to azure.error.detailed file or something like that).

**Comment by sauryadas** [comment]
@yugangw-msft are you just outputting the error message that the vm create api is returning ?

**Comment by yugangw-msft** [comment]
Nope, `VM create` is done through arm deployment like portal. Most deployment errors are pretty explicitly displayed by CLI. @BorisB2015, want to confirm, the inner error was not displayed by CLI, right? If true, we need to get a better understanding of the deployment error format and extract out more pertinent information.

**Comment by BorisB2015** [comment]
Correct, the inner error was not displayed in the output of the CLI. I can share the JSON of the deployment write operation in activity log - this is where I got the inner error from.

**Comment by tjprescott** [comment]
If you run the command with `--validate` do you get the better error?

**Comment by tjprescott** [comment]
When I tried this, I got the following:
```
The template deployment 'vmss_deploy_XngScIlKnDHeVGq1gqtN44fKUALRY9DL' is not valid according to the validation procedure. The tracking id is '0f0ab6c2-1331-4686-8a0a-824ce7c3c5ab'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details. Operation results in exceeding quota limits of Core. Maximum allowed: 100, Current in use: 43, Additional requested: 1000.
```
Note that the end of the error contains the details.

Additionally, I ran this with --validate:
```
{
  "error": {
    "code": "InvalidTemplateDeployment",
    "details": [
      {
        "code": "QuotaExceeded",
        "details": null,
        "message": "Operation results in exceeding quota limits of Core. Maximum allowed: 100, Current in use: 43, Additional requested: 1000.",
        "target": null
      }
    ],
    "message": "The template deployment 'vmss_deploy_THFHPhJktLrajlWFRtJ01jmWJwyCfY05' is not valid according to the validation procedure. The tracking id is '131f1ae4-a9db-46e7-9afd-3c27b3f18072'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.",
    "target": null
  },
  "properties": null
}
```
Here it is a little easier to spot. In either case, the error is shown. `vm create` supports `--validate` as well.

**Comment by BorisB2015** [comment]
@tjprescott, Could you please run the above command with "--no-wait"  and tell me what you see - it seems it is when I do not get the second half of the message. I do get the full message when I wait for the command to complete.

**Comment by BorisB2015** [comment]
Another item: my default output is set to table (az configure). If I run `--validate`  I get no output - I expected to get something indicating an error. I do get expected output with `--output=json`

**Comment by tjprescott** [comment]
@BorisB2015 thanks for that feedback!  We'll take a look at improving this experience.

**Comment by tjprescott** [comment]
To recap, the issues are:

- [ ] Deployment inner error not show when using `--no-wait`
- [ ] `--validate` does not work with `--output table`

**Comment by BorisB2015** [comment]
@tjprescott - thank you for the summary!

**Comment by stewartadam** [comment]
I ran into this as well. Two NSG rules with same priority conflicted, 'az group deployment create' failed and said to refer to inner error which was not printed. Found the inner error by attempting deployment in the portal.

**Comment by dctucker** [comment]
I propose re-opening this issue, as the error messaging is still pretty vague, even without specifying `--no-wait`.

```
az vm create --output json --size "$AZURE_INSTANCE" \
    --authentication-type ssh --ssh-key-value ~/.ssh/id_rsa_azure.pub \
    --location "$AZURE_LOCATION" --resource-group "$AZURE_RESOURCE_GROUP" \
    --name "$VMNAME" --nsg "$NSG_NAME" --image "$IMAGENAME" --admin-username adminblahblah
```

```
Creating VM 'ci-ghe-test-REDACTED' size Standard_DS3_v2 at West US
ERROR: The template deployment 'vm_deploy_1Pxz7pK4sUHfnSKEqHjg8Ndg3djLKVyT' is not valid according to the validation procedure. The tracking id is '55de1ffb-5661-4e55-b58f-aff68469750d'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.
{
  "additionalProperties": {},
  "endTime": "2018-07-19T18:24:26.002087+00:00",
  "error": null,
  "name": "REDACTED,
  "startTime": "2018-07-19T18:24:20.908537+00:00",
  "status": "Succeeded"
}
```

**Comment by tjprescott** [comment]
@dctucker you are using a version of the CLI that is over 6 months old. I'd recommend you try it on a newer version and if the errors are still too vague, open a new issue.
