### ISSUE TITLE
az login fails: OSError: [WinError -2146893813] #20231

### ISSUE THREAD

**Issue by Krishnapapineni** [Azure/azure-cli#27922]
### Describe the bug

unable to az login to fail the issues

### Related command

to create logic app and functional app in azure

### Errors

PS C:\Users\krishna143\OneDrive\Documents\Azure function app> .\terraform plan

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Warning: Deprecated Resource
│
│   with azurerm_app_service_plan.WorkflowStandard,
│   on Azurefunctionapp.tf line 18, in resource "azurerm_app_service_plan" "WorkflowStandard":
│   18: resource "azurerm_app_service_plan" "WorkflowStandard" {
│
│ The `azurerm_app_service_plan` resource has been superseded by the `azurerm_service_plan` resource. Whilst this      
│ resource will continue to be available in the 2.x and 3.x releases it is feature-frozen for compatibility purposes,  
│ will no longer receive any updates and will be removed in a future major release of the Azure Provider.
│
│ (and one more similar warning elsewhere)
╵
╷
│ Error: building account: could not acquire access token to parse claims: running Azure CLI: exit status 1: ERROR: Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError
│ Please report to us via Github: https://github.com/Azure/azure-cli/issues/20231
│
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on Azurefunctionapp.tf line 1, in provider "azurerm":
│    1: provider "azurerm" {
│

### Issue script & Debug output

│ Error: building account: could not acquire access token to parse claims: running Azure CLI: exit status 1: ERROR: Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError

### Expected behavior

i need a soluation for error because im unble to access azure login credencials 

### Environment Summary

azure-cli                         2.53.0

core                              2.53.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\krishna143\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

### Additional context

│ Error: building account: could not acquire access token to parse claims: running Azure CLI: exit status 1: ERROR: Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
