### ISSUE TITLE
NtStatus 0xc000000d (STATUS_INVALID_PARAMETER)

### ISSUE THREAD

**Issue by gn4711** [Azure/azure-cli#27939]
### Describe the bug

I got error / unhandled exception
**Failed to get last change of target at \\?\T:: NtStatus 0xc000000d (STATUS_INVALID_PARAMETER)
when executing command on USB Drive (T:)**
when running same script with same content from a disk, this error does not appear. 

### Related command

az storage blob sync -s ./  -c cccc--account-name nnnn--account-key kkkk

### Errors

INFO: Failed to get last change of target at \\?\T:: NtStatus 0xc000000d (STATUS_INVALID_PARAMETER)
0 Files Scanned at Source, 0 Files Scanned at Destinationpanic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x1052800]

goroutine 1 [running]:
github.com/Azure/azure-storage-azcopy/v10/cmd.(*localTraverser).Traverse.func1(0xc00032e5d0, 0x6, 0x0, 0x0, 0x0, 0x0, 0xc00032e620, 0xc00032e680)
        /home/vsts/work/1/s/cmd/zc_traverser_local.go:355 +0x680
github.com/Azure/azure-storage-azcopy/v10/cmd.WalkWithSymlinks.func1(0xc00032e620, 0x7, 0x1407358, 0xc00017a2a0, 0x0, 0x0, 0x0, 0x0)
        /home/vsts/work/1/s/cmd/zc_traverser_local.go:278 +0x1104
github.com/Azure/azure-storage-azcopy/v10/common/parallel.Walk(0xc00032e620, 0x7, 0x10, 0x0, 0xc00073ec00)
        /home/vsts/work/1/s/common/parallel/FileSystemCrawler.go:89 +0x136
github.com/Azure/azure-storage-azcopy/v10/cmd.WalkWithSymlinks(0xc00032e5d0, 0x7, 0xc00073eeb8, 0x0, 0x0, 0x0)
        /home/vsts/work/1/s/cmd/zc_traverser_local.go:186 +0x217
github.com/Azure/azure-storage-azcopy/v10/cmd.(*localTraverser).Traverse(0xc0004fc6e0, 0x0, 0xc00039ce70, 0x1a2dfa0, 0x0, 0x0, 0x13eece0, 0xc000430010)
        /home/vsts/work/1/s/cmd/zc_traverser_local.go:382 +0x925
github.com/Azure/azure-storage-azcopy/v10/cmd.(*syncEnumerator).enumerate(0xc0000121e0, 0x1401b00, 0xc000088360)
        /home/vsts/work/1/s/cmd/zc_enumerator.go:622 +0x9e
github.com/Azure/azure-storage-azcopy/v10/cmd.(*cookedSyncCmdArgs).process(0xc000236a80, 0xa1, 0x0)
        /home/vsts/work/1/s/cmd/sync.go:683 +0x425
github.com/Azure/azure-storage-azcopy/v10/cmd.init.19.func2(0xc000489900, 0xc00047ed20, 0x2, 0x3)
        /home/vsts/work/1/s/cmd/sync.go:718 +0x17a
github.com/spf13/cobra.(*Command).execute(0xc000489900, 0xc00047ecc0, 0x3, 0x3, 0xc000489900, 0xc00047ecc0)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x19d9e20, 0x9a8fba701d2bec4d, 0x30, 0x11a75e0)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/Azure/azure-storage-azcopy/v10/cmd.Execute(0xc00002ee58, 0x16, 0xc00002ee58, 0x16, 0xc000033260, 0x1c, 0x7fffffff)
        /home/vsts/work/1/s/cmd/root.go:165 +0xfa
main.main()
        /home/vsts/work/1/s/main.go:82 +0x397
Failed to perform sync operation.

### Issue script & Debug output

see command

### Expected behavior

no unhandled execption

### Environment Summary

azure-cli                         2.51.0 *

core                              2.51.0 *
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\xxx\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by gn4711** [comment]
Validated with newest az. Same error:

azure-cli                         2.51.0 *

core                              2.51.0 *
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\xxx\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by gn4711** [comment]
same with newest az: 

_azure-cli                         2.54.0

core                              2.54.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\xxx\.azure\cliextensions'

Python (Windows) 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:21:31) [MSC v.1936 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date._
