### ISSUE TITLE
azure cli support swapinpreview

### ISSUE THREAD

**Issue by leitu** [Azure/azure-cli#2793]
Hi 

According to https://blogs.msdn.microsoft.com/waws/2016/12/12/slot-swap-with-preview/
powershell supports the swap slot in swapwithpreview mode, is there any plan to have the same feature in az cli 2.0?

 az appservice web deployment slot -h

Group
    az appservice web deployment slot: Manage deployment slots.

Commands:
    auto-swap: Configure slot auto swap.
    create   : Create a slot.
    delete   : Delete a slot.
    list     : List all slots.
    swap     : Swap slots.

**Comment by yugangw-msft** [comment]
Suggest this to be done by //build
