### ISSUE TITLE
Azure Image Builder New API Version Request - 2023-07-01

### ISSUE THREAD

**Issue by zdelacerda-microsoft** [Azure/azure-cli#27946]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az image builder error-handler add
az image builder error-hander remove
az image builder error-handler show

### Resource Provider

Microsoft.VirtualMachineImages (Azure VM Image Builder)

### Description of Feature or Work Requested

Add new top level errorHandling property group.

az image builder error-handler add [--on-customizer-error {cleanup, abort}, --on-vaidation-error]

Customers may specify the error handling behavior for an error that occurs during customize: either clean up or abort. 
-Clean up is the existing and default behavior which cleans up the customizing VM. 
-Abort will preserve the customizing VM to allow the customer to investigate the error that occurred during customizing. The customer is responsible for manually cleaning up the VM and related resources when abort is specified.

az image builder error-handler remove (no input)
az image builder error-handler show (output: --on-customizer-error and --on-validation-error)

### Minimum API Version Required

2023-07-01

### Swagger PR link / SDK link

[[Hub Generated] Review request for Microsoft.VirtualMachineImages to add version stable/2022-02-14 and stable/2023-07-01 by zdelacerda-microsoft · Pull Request #26309 · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/pull/26309)

[[API 2023-07-01 Update] Fixing distribute in ImageTemplateUpdateParameters by zdelacerda-microsoft · Pull Request #26487 · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/pull/26487)

### Request Example

[onCustomizerError set to cleanup](https://dev.azure.com/msazure/One/_git/Compute-AzLinux-ImageBuilderRp?path=/scripts/test/errorhandling/mariner_2.0_cleanup_template.json&version=GCf00c0ec97703e6fcfd7aee3330347da1a03b47dd&line=43&lineEnd=45&lineStartColumn=5&lineEndColumn=6&lineStyle=plain&_a=contents)

[onCustomizerError set to abort and onValidationError set to cleanup](https://dev.azure.com/msazure/One/_git/Compute-AzLinux-ImageBuilderRp?path=/scripts/test/errorhandling/mariner_2.0_validatecleanup_template.json&version=GCf00c0ec97703e6fcfd7aee3330347da1a03b47dd&line=49&lineEnd=52&lineStartColumn=5&lineEndColumn=6&lineStyle=plain&_a=contents)

### Target Date

2023-12-31

### PM Contact

kofiforson

### Engineer Contact

zdelacerda

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yanzhudd** [comment]
> Target Date
> 2023-12-31

Hi @zdelacerda-microsoft,
please note that CLI the next release date is 2024-01-02. Is it acceptable for you?

**Comment by zdelacerda-microsoft** [comment]
> > Target Date
> > 2023-12-31
> 
> Hi @zdelacerda-microsoft, please note that CLI the next release date is 2024-01-02. Is it acceptable for you?

That's acceptable. Thank you

**Comment by yanzhudd** [comment]
Hi @zdelacerda-microsoft,
it seems that this new added property is not in the current SDK package. Please note that CLI uses Azure Python SDK to interact with backend side, so only when the SDK is ready can we develop this feature. 
Please contact SDK team to release a new version firstly. Since SDK team follow [monthly release cycle](https://eng.ms/docs/products/azure-developer-experience/develop/sdk-release), please follow https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/release-request/rules-for-release-request.md to raise release request issue to catch up release train of this month. Thanks!

**Comment by uiri** [comment]
The [latest public Azure Python SDK release](https://pypi.org/project/azure-mgmt-imagebuilder/) appears to be more than 6 months old. It doesn't make any sense to me that there has not been any Azure Python SDK release since April.

**Comment by yanzhudd** [comment]
> Hi @zdelacerda-microsoft, it seems that this new added property is not in the current SDK package. Please note that CLI uses Azure Python SDK to interact with backend side, so only when the SDK is ready can we develop this feature. Please contact SDK team to release a new version firstly. Since SDK team follow [monthly release cycle](https://eng.ms/docs/products/azure-developer-experience/develop/sdk-release), please follow https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/release-request/rules-for-release-request.md to raise release request issue to catch up release train of this month. Thanks!

please release the Azure Python SDK before 12-18 so that we have time to develop and test, otherwise this feature has to be postponed to next sprint (release date is 2024-02-06).

**Comment by zdelacerda-microsoft** [comment]
Hi @yanzhudd, python SDK is now updated. Is this still on track for 2024-02-06?

**Comment by yanzhudd** [comment]
> Hi @yanzhudd, python SDK is now updated. Is this still on track for 2024-02-06?

Yeah, it is still on track for 02-06.
