### ISSUE TITLE
`azure-loganalytics` used in this package but it's deprecated

### ISSUE THREAD

**Issue by TylerLeonhardt** [Azure/azure-cli#27952]
### Describe the bug

The Azure CLI brings in this deprecated package:
https://pypi.org/project/azure-loganalytics/

this is causing our component governance to complain. There's a migration guide here:
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/monitor/azure-monitor-query/migration_guide.md

azure-cli should migrate.

Links where it's used:
* https://github.com/Azure/azure-cli/blob/ef8ec47b16297a31c47fdc2b396e15474236bb14/src/azure-cli/setup.py#L65
* https://github.com/Azure/azure-cli/blob/ef8ec47b16297a31c47fdc2b396e15474236bb14/src/azure-cli/requirements.py3.windows.txt#L20
* https://github.com/Azure/azure-cli/blob/ef8ec47b16297a31c47fdc2b396e15474236bb14/src/azure-cli/requirements.py3.Linux.txt#L20
* https://github.com/Azure/azure-cli/blob/ef8ec47b16297a31c47fdc2b396e15474236bb14/src/azure-cli/requirements.py3.Darwin.txt#L20

### Related command

base package

### Errors

This package has been deprecated in favor of the Azure Monitor Query SDK. Support for this library officially ends on 3/31/2023. Upgrade to [azure-monitor-query](https://pypi.org/project/azure-monitor-query/) and refer to the [Python migration guide](https://aka.ms/azsdk/python/migrate/la-to-monitor-query) for additional information. [Read more about the SDK](https://devblogs.microsoft.com/azure-sdk/announcing-the-new-azure-monitor-query-client-libraries/).

### Issue script & Debug output

n/a

### Expected behavior

this shouldn't show

### Environment Summary

azure-cli 2.54.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
