### ISSUE TITLE
az login stopped working after updating to latest az cli

### ISSUE THREAD

**Issue by shobhit-kumar-code** [Azure/azure-cli#27955]
### Describe the bug

After updating to the latest az cli, I get an error message when i run az login. I can proceed with device code but it doesn't support a usecase.
Here is the output:
<img width="960" alt="image" src="https://github.com/Azure/azure-cli/assets/22573271/67021c85-bf73-4d73-a168-6f63e46567ce">

and here is the output of az version
![image](https://github.com/Azure/azure-cli/assets/22573271/8c6b2663-2da0-431a-b7a4-892985b5b379)

Happy to share further info

### Related command

az login

### Errors

<img width="960" alt="image" src="https://github.com/Azure/azure-cli/assets/22573271/0d64b92f-151c-43d4-8d8b-06c7de80dcb9">

### Issue script & Debug output

msal.telemetry: Generate or reuse correlation_id: XXXXXXXXXXXXXXXXXXXXXX
msal.oauth2cli.oauth2: Using http://localhost:45495 as redirect_uri
msal.oauth2cli.authcode: Abort by visit http://localhost:45495?error=abort

### Expected behavior

I expect a browser to pop up where i enter the login details

### Environment Summary

azure-cli                         2.54.0

core                              2.54.0
telemetry                          1.1.0

Extensions:
bastion                            0.2.5
connectedk8s                       1.4.2
customlocation                     0.1.3
k8s-extension                      1.5.2
mobile-network                     0.2.1
ssh                                2.0.1

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/home/shobhit/.azure/cliextensions'

Python (Linux) 3.11.5 (main, Nov  8 2023, 05:20:54) [GCC 11.4.0]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
