### ISSUE TITLE
Assignment the impossible 

### ISSUE THREAD

**Issue by Jordanwaslistening** [Azure/azure-cli#27966]
Assignment 

_Originally posted by @Jordanwaslistening in https://github.com/Marithon-Production-of-Choice/desktop-37734696/pull/1#issuecomment-1792368163_

**Comment by Jordanwaslistening** [comment]
> Assignment 
> 
> _Originally posted by @Jordanwaslistening in https://github.com/Marithon-Production-of-Choice/desktop-37734696/pull/1#issuecomment-1792368163_

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
