### ISSUE TITLE
ssh-key-value and agent-vm-size get ignored while creating cluster using az acs create

### ISSUE THREAD

**Issue by sudharsanmit** [Azure/azure-cli#2797]
## Environment summary

Install Method: How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)
**pip**

CLI Version: What version of the CLI and modules are installed? (Available with az --version)
**azure-cli (2.0.2)**

OS Version: What OS and version are you using?
**Windows 7 32-bit**

Shell Type: What shell are you using? (e.g. bash, cmd.exe, PowerShell)
**Bash**

## Description

I used the below script to create the cluster on Azure. The cluster gets created but it has the following problems:

1. **The SSH Key is not transmitted to the server even though specified.** (I tried both ways - file and value) So, when trying to login to the master with PuTTY, I get error. The workaround is to create the cluster with the below script, login to the Azure Portal and reset the password for the master by manually uploading the RSA Public key. Once, the password is reset by this method, it will allow access through Putty.

2. **The Agent VM size is ignored even though specified**. In the below script, I specified the Agent VM to be a Standard_DS1_v2. But the argument gets ignored and the Agent VM gets created with Standard_DS2_v2.
```
#!/bin/ksh

RESOURCE_GROUP=newexample
LOCATION=westus
DNS_PREFIX=newexample
CLUSTER_NAME=newexample

MASTER_COUNT=1
AGENT_COUNT=1
SSH_KEY_VALUE="$(cat $HOME/.ssh/id_rsa.pub)"

# Check this link for windows sizing https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-general
AGENT_VM_SIZE=Standard_DS1_v2

#Delete before start
az acs delete --resource-group=$RESOURCE_GROUP --name=$CLUSTER_NAME
az group delete --name=$RESOURCE_GROUP --yes

# Create group and cluster
az group create --name=$RESOURCE_GROUP --location=$LOCATION
az acs create --orchestrator-type=kubernetes --ssh-key-value "$SSH_KEY_VALUE" --resource-group $RESOURCE_GROUP --name=$CLUSTER_NAME --dns-prefix=$DNS_PREFIX --master-count $MASTER_COUNT --agent-count $AGENT_COUNT --agent-vm-size $AGENT_VM_SIZE

```

**Comment by brendandburns** [comment]
Acknowledged. Will try to reproduce this.

**Comment by brendandburns** [comment]
I can't reproduce this. I downloaded your script and ran it on my machine and the cluster was created with the right key and the right agent size.

Please try upgrading the cli and re-open and run with the `--debug` flag if it re-occurs.
