### ISSUE TITLE
Unable to update existing Managed App Definition

### ISSUE THREAD

**Issue by TravarA** [Azure/azure-cli#27976]
### Describe the bug

I've created a managed application definition via Azure portal. 
Now I'm trying to update the definition using Azure CLI (```az managedapp definition update```), but I'm unable to because I get the following error:
```bash
(ApplicationDefinitionApplicationManagementPolicyLockConflict) Modifying application management policy on existing application definition is not allowed, current application management mode is 'Managed' while request contains different mode '<null>'.
Code: ApplicationDefinitionApplicationManagementPolicyLockConflict
Message: Modifying application management policy on existing application definition is not allowed, current application management mode is 'Managed' while request contains different mode '<null>'.
```

I see no way to set the mode via CLI, while setting it via REST API is possible by setting the request body property ```properties.managementPolicy.mode```  (https://learn.microsoft.com/en-us/rest/api/managedapplications/application-definitions/create-or-update?view=rest-managedapplications-2019-07-01&tabs=HTTP#applicationmanagementpolicy)

### Related command

az managedapp definition update

### Errors

(ApplicationDefinitionApplicationManagementPolicyLockConflict) Modifying application management policy on existing application definition is not allowed, current application management mode is 'Managed' while request contains different mode '<null>'.
Code: ApplicationDefinitionApplicationManagementPolicyLockConflict
Message: Modifying application management policy on existing application definition is not allowed, current application management mode is 'Managed' while request contains different mode '<null>'.

### Issue script & Debug output

Output is too long, so here's pastebin link:
https://pastebin.com/q9eCacZ5

### Expected behavior

I expect for the command to update the resource without errors.

### Environment Summary

azure-cli                         2.54.0 *

core                              2.54.0 *
telemetry                          1.1.0

Extensions:
partnercenter                      0.2.4

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/home/adnan/.azure/cliextensions'

Python (Linux) 3.11.5 (main, Nov  8 2023, 05:20:54) [GCC 11.4.0]

Legal docs and information: aka.ms/AzureCliLegal

### Additional context

I have tried the latest az cli version 2.55.0, and same thing happens

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by TravarA** [comment]
I went back and re-read the documentation, and apparently adding the '@' character before file names,  is **required** when/if setting ```--create-ui-definition``` and  ```--main-template``` arguments.

```bash
az managedapp definition create \ 
-g MyResourceGroup \
-n MyManagedAppDef \
-l eastus \
--display-name "MyManagedAppDef" \
--description "My Managed App Def description" \
-a "myPrincipalId:myRoleId" \
--lock-level \
None \
--create-ui-definition @myCreateUiDef.json --main-template @myMainTemplate.json
```

This resolves the issue when creating new and updating existing app definitions.
