### ISSUE TITLE
az deployment <scope> create gives nonsensical error message on missing parameters file

### ISSUE THREAD

**Issue by jannef** [Azure/azure-cli#27989]
### Describe the bug

When deploying to any scope using bicepparam file, nonsensical error is given when user makes a typing error on the bicepparam file name **in certain way**

```
az deployment mg create --management-group-id mymanagementgroup --location westeurope --parameters parameters/notfound.bicepparam
```

Typing wrong filename, (notfound.bicepparam) the error is as expected:
```
An error occurred reading file. Could not find a part of the path '/Users/janne/zbj/infra/parameters/notfound.bicepparam'
```

Typing wrong **fileextension** (found.bicepparam**s**), the error is nonsensical:
```
'NoneType' object has no attribute 'lower'
```

### Related command

az deployment mg create

### Errors

'NoneType' object has no attribute 'lower'

### Issue script & Debug output

az deployment mg create --management-group-id zorgbijjou --location westeurope --parameters parameters/sandbox.bicepparams --debug
cli.knack.cli: Command arguments: ['deployment', 'mg', 'create', '--management-group-id', 'zorgbijjou', '--location', 'westeurope', '--parameters', '@parameters/sandbox.bicepparams', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x101c24040>, <function OutputProducer.on_global_arguments at 0x101c9f1a0>, <function CLIQuery.on_global_arguments at 0x101cf0cc0>]
cli.azure.cli.core.commands: Failed to load '@parameters/sandbox.bicepparams', assume not a file
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'deployment': ['azure.cli.command_modules.resource']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: resource                  0.104        51       228
cli.azure.cli.core: Total (1)                 0.104        51       228
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 51 groups, 228 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : deployment mg create
cli.azure.cli.core: Command table: deployment mg create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x102a14180>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/Users/janne/.azure/commands/2023-12-08.13-10-03.deployment_mg_create.53867.log'.
az_command_data_logger: command args: deployment mg create --management-group-id {} --location {} --parameters {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x102a599e0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x102a5aac0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x102a31e40>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.parser: Attempting to read file parameters/sandbox.bicepparams
cli.knack.parser: File Error: Failed to open parameters/sandbox.bicepparams, assume not a file
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x101c9f240>, <function CLIQuery.handle_query_parameter at 0x101cf0d60>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x102a5ab60>]
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.55.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.55.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.55.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.55.0/libexec/lib/python3.11/site-packages/azure/cli/command_modules/resource/custom.py", line 751, in deploy_arm_template_at_management_group
    return _deploy_arm_template_at_management_group(cmd=cmd,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.55.0/libexec/lib/python3.11/site-packages/azure/cli/command_modules/resource/custom.py", line 782, in _deploy_arm_template_at_management_group
    deployment_properties = _prepare_deployment_properties_unmodified(cmd, 'managementGroup', template_file=template_file,
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.55.0/libexec/lib/python3.11/site-packages/azure/cli/command_modules/resource/custom.py", line 1189, in _prepare_deployment_properties_unmodified
    if is_bicep_file(template_file)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.55.0/libexec/lib/python3.11/site-packages/azure/cli/command_modules/resource/_bicep.py", line 173, in is_bicep_file
    return file_path.lower().endswith(".bicep")
           ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.55.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/arm.py", line 109, in handle_template_based_exception
    raise CLIError(ex.inner_exception.error.message)
                   ^^^^^^^^^^^^^^^^^^
AttributeError: 'AttributeError' object has no attribute 'inner_exception'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.55.0/libexec/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.55.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.55.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.55.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/azure-cli/2.55.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/arm.py", line 114, in handle_template_based_exception
    raise CLIError(ex)
knack.util.CLIError: 'NoneType' object has no attribute 'lower'

cli.azure.cli.core.azclierror: 'NoneType' object has no attribute 'lower'
az_command_data_logger: 'NoneType' object has no attribute 'lower'
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x102a14400>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.400 seconds (init: 0.127, invoke: 0.274)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3600 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/opt/homebrew/Cellar/azure-cli/2.55.0/libexec/bin/python /opt/homebrew/Cellar/azure-cli/2.55.0/libexec/lib/python3.11/site-packages/azure/cli/telemetry/__init__.py /Users/janne/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

File not found error

An error occurred reading file. Could not find a part of the path '/Users/janne/zbj/infra/@parameters/sandbox.bicepparams'

### Environment Summary

az --version
azure-cli                         2.55.0

core                              2.55.0
telemetry                          1.1.0

Extensions:
account                            0.2.5

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/opt/homebrew/Cellar/azure-cli/2.55.0/libexec/bin/python'
Extensions directory '/Users/janne/.azure/cliextensions'

Python (Darwin) 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

Same behaviour (nonsensical error) happens with some other typing errors (prefixingthe path with @, for example)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
