### ISSUE TITLE
Azure CLI connect fail

### ISSUE THREAD

**Issue by Clairelala** [Azure/azure-cli#27985]
### Describe the bug

I'm encountering a connectivity issue when trying to run the following Azure CLI command

az storage blob list --container-name mycontainer --account-name mycvstorage --sas-token 'mytoken'

### Related command

az storage blob list

### Errors

<urllib3.connection.HTTPSConnection object at 0x000001EA965D9ED0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

### Issue script & Debug output

<urllib3.connection.HTTPSConnection object at 0x000001F0ECC07090>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

### Expected behavior

list the container

### Environment Summary

azure-cli                         2.55.0

core                              2.55.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\liangcl01\.azure\cliextensions'

Python (Windows) 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by calvinhzy** [comment]
Hi @Clairelala do the other commands work like `az storage account create` and `az storage container create`?
Did you get the sas token through this command?
`az storage container generate-sas --permissions rl --account-name satestbloblist --name container1 --start "2023-12-07T00:00:00Z" --expiry "2024-01-01T00:00:00Z" -o tsv`
Another thing to try is run `az login` again.
![image](https://github.com/Azure/azure-cli/assets/17182306/0bb8168f-91d7-42df-b103-71b32bb77978)
