### ISSUE TITLE
Az sig update SoftDeletePolicy keep to be null if user does not specify

### ISSUE THREAD

**Issue by kangsun-ctrl** [Azure/azure-cli#27992]
**Related command**
az sig update

**Is your feature request related to a problem? Please describe.**
Yes.

Current scenario: user does 'az sig update' without '--soft-delete-policy', CLI will still pass in SoftDeletePolicy to the backend if the Get result has SoftDeletePolicy.

Ask: When user does 'az sig update' without '--soft-delete-policy', CLI do not pass in SoftDeletePolicy to the backend(set it as null). If user specify '--soft-delete-policy' in CLI, then CLI pass in whatever user passed to backend.

Otherwise we would get icm like https://portal.microsofticm.com/imp/v3/incidents/details/446631906/home

**Describe the solution you'd like**
Described above.

**Describe alternatives you've considered**
An alternative is that we remove all DM of softDeletePolicy, but that could be a huge effort.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
