### ISSUE TITLE
[Network] Issues with VPN connection shared keys

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#2799]
When I create a VPN connection that is VNet-to-VNet or Site-to-Site, the CLI requires I specify `--shared-key`. This value is sent to the server every time, but about 50% of the time, after the create call returns, the sharedKey value is different from what I specified. 

- If I use the `vpn-connection shared-key update` command, it always correctly sets my sharedKey.
- If I remove the CLI enforcement on shared key and supply nothing, the service generates a shared key.

So my questions are:
1. Why not remove `--shared-key` from the `vpn-connection create` command and let the service set the shared key?
2. What use case is there for manually setting the shared key, since that encourages insecure keys.
3. Why could we not just remove the `shared-key update` and `shared-key show` commands and simply have `vpn-connection regenerate-shared-key` similar to storage?

cc/ @aanandr

**Comment by yonzhan** [comment]
@MyronFanQiu  add to S162.

**Comment by MyronFanQiu** [comment]
@tjprescott Hello. I have tested this issue and running create commands about 25 times. I don't meet this issue again. Besides, I checked the telemetry, looks like we cannot deprecate this one since lot's of customers are using it.

**Comment by MyronFanQiu** [comment]
I closed this issue. If we meet this one later, we can open a new one. Thanks~
