### ISSUE TITLE
Trusted Launch as Default - VM/VMSS Deployment with Image URN/ID

### ISSUE THREAD

**Issue by AjKundnani** [Azure/azure-cli#28005]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

- [az vm create --name 'vmname' --resource-group 'vm-rgname' --image 'imagealias'](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create)
- [az vmss create --name 'vmssname' --resource-group 'rgname' --image 'imagealias'](https://docs.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#az-vmss-create)
- [az vm image list](https://docs.microsoft.com/en-us/cli/azure/vm/image?view=azure-cli-latest#az-vm-image-list)

### Resource Provider

Microsoft.Compute/virtualMachines

### Description of Feature or Work Requested

# Trusted Launch as Default

This request is in continuation of #23450 - Scenario 4 & Scenario 5. Post implementation decision was taken by Service LT team to support intelligence for further minimizing end user impact.

As part of making compute layer secure for customers to deploy workloads, request is to make [Trusted Launch](https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch) (GA Date: November 2021) as default deployment option in CLI. Following changes will need to be made for same:

## Scenario 4 - User creates VM with command `az vm create` and image URN

Present Behavior | Updated Behavior post change
-|-
New VM with image parameter: <ol><li>User runs command `az vm create --name vmname --resource-group rgname --image imageURN --size vmsize`.<li>If `--size` parameter is not specified, CLI creates VM with **Standard_DS1_v2** VM SIze.<li>**Check**: CLI will check if input URN is Gen2 OS image using [Virtual Machine Images - GET API](https://learn.microsoft.com/rest/api/compute/virtual-machine-images/get).<li>Conditions:<ul><li>If hyperVGeneration for OS image is **v2** then following parameters are set by default:<ul><li>`--enable-secure-boot` with value **true**<li>`--enable-vtpm` with value **true**<li>`--security-type` with value **TrustedLaunch**</li></ul><li>If hyperVGeneration for OS image is **v1** securityType is set to **Standard** with the following message displayed and Trusted Launch default is not applied. `Consider upgrading security for your workloads using Azure Trusted Launch VMs. To know more about Trusted Launch, please visit https://aka.ms/TrustedLaunch`</li></ul></li></ol> | Updated default parameters: <ol><li>User runs command `az vm create --name vmname --resource-group rgname --image imageURN --size vmsize`<li>CLI will set default VM Size **Standard_DS1_v2** if  no size specified,<li>**Check**: CLI will check if input URN is Gen2 OS image **AND** `securityType` under `features` contains **TrustedLaunch** (it can be `TrustedLaunchSupported` OR `TrustedLaunchAndConfidentialVmSupported`) using [Virtual Machine Images - GET API](https://learn.microsoft.com/rest/api/compute/virtual-machine-images/get).<li>Conditions:<ul><li>If hyperVGeneration for OS image is **v2** **AND** under `features` contains **TrustedLaunch** then following parameters are set by default:<ul><li>`--enable-secure-boot` with value **true**<li>`--enable-vtpm` with value **true**<li>`--security-type` with value **TrustedLaunch**</li></ul><li>If hyperVGeneration for OS image is **v2** **AND** under `features` does not contains **TrustedLaunch** then following parameters are set by default:<ul><li>`--security-type` with value **Standard**<li>with the following message displayed and Trusted Launch default is not applied. `Consider upgrading security for your workloads using Azure Trusted Launch VMs. To know more about Trusted Launch, please visit https://aka.ms/TrustedLaunch`</li></ul><li>If hyperVGeneration for OS image is **v1** securityType is set to **Standard** with the following message displayed and Trusted Launch default is not applied. `Consider upgrading security for your workloads using Azure Trusted Launch VMs. To know more about Trusted Launch, please visit https://aka.ms/TrustedLaunch`</li></ul><li>API will return error in following scenarios:<ul><li>Image URN provided is Gen2 but not TrustedLaunchSupported.<li>VM Size does not supports Gen2 or Trusted Launch.</li></ul></ol>

## Scenario 5 - User creates VMSS with command `az vmss create` and image URN

Present Behavior | Updated Behavior post change
-|-
New VMSS with image parameter: <ol><li>User runs command `az vmss create --name vmssname --resource-group rgname --image imageURN --size vmsssize`.<li>If `--size` parameter is not specified, CLI creates VM with **Standard_DS1_v2** VM SIze.<li>**Check**: CLI will check if input URN is Gen2 OS image using [Virtual Machine Images - GET API](https://learn.microsoft.com/rest/api/compute/virtual-machine-images/get).<li>Conditions:<ul><li>If hyperVGeneration for OS image is **v2** then following parameters are set by default:<ul><li>`--enable-secure-boot` with value **true**<li>`--enable-vtpm` with value **true**<li>`--security-type` with value **TrustedLaunch**</li></ul><li>If hyperVGeneration for OS image is **v1** securityType is set to **Standard** with the following message displayed and Trusted Launch default is not applied. `Consider upgrading security for your workloads using Azure Trusted Launch VMs. To know more about Trusted Launch, please visit https://aka.ms/TrustedLaunch`</li></ul></li></ol> | Updated default parameters: <ol><li>User runs command `az vm create --name vmname --resource-group rgname --image imageURN --size vmsize`<li>CLI will set default VM Size **Standard_DS1_v2** if  no size specified,<li>**Check**: CLI will check if input URN is Gen2 OS image **AND** `securityType` under `features` contains **TrustedLaunch** (it can be `TrustedLaunchSupported` OR `TrustedLaunchAndConfidentialVmSupported`) using [Virtual Machine Images - GET API](https://learn.microsoft.com/rest/api/compute/virtual-machine-images/get).<li>Conditions:<ul><li>If hyperVGeneration for OS image is **v2** **AND** under `features` contains **TrustedLaunch** then following parameters are set by default:<ul><li>`--enable-secure-boot` with value **true**<li>`--enable-vtpm` with value **true**<li>`--security-type` with value **TrustedLaunch**</li></ul><li>If hyperVGeneration for OS image is **v2** **AND** under `features` does not contains **TrustedLaunch** then following parameters are set by default:<ul><li>`--security-type` with value **Standard**<li>with the following message displayed and Trusted Launch default is not applied. `Consider upgrading security for your workloads using Azure Trusted Launch VMs. To know more about Trusted Launch, please visit https://aka.ms/TrustedLaunch`</li></ul><li>If hyperVGeneration for OS image is **v1** securityType is set to **Standard** with the following message displayed and Trusted Launch default is not applied. `Consider upgrading security for your workloads using Azure Trusted Launch VMs. To know more about Trusted Launch, please visit https://aka.ms/TrustedLaunch`</li></ul><li>API will return error in following scenarios:<ul><li>Image URN provided is Gen2 but not TrustedLaunchSupported.<li>VM Size does not supports Gen2 or Trusted Launch.</li></ul></ol>

## Sample Gen2 OS Image with TrustedLaunch support

```
az vm image show --publisher MicrosoftWindowsServer --offer WindowsServer --sku 2019-datacenter-gensecond --version 17763.5122.231109
{
  "architecture": "x64",
  "automaticOsUpgradeProperties": {
    "automaticOsUpgradeSupported": false
  },
  "dataDiskImages": [],
  "disallowed": {
    "vmDiskType": "Unmanaged"
  },
  "extendedLocation": null,
  "features": [
    {
      "name": "SecurityType",
      "value": "TrustedLaunchAndConfidentialVmSupported"
    },
    {
      "name": "IsAcceleratedNetworkSupported",
      "value": "True"
    },
    {
      "name": "DiskControllerTypes",
      "value": "SCSI, NVMe"
    },
    {
      "name": "IsHibernateSupported",
      "value": "True"
    }
  ],
  "hyperVGeneration": "V2",
  "id": "/Subscriptions/52942f45-54fd-4fd9-b730-03d518fedf35/Providers/Microsoft.Compute/Locations/westus/Publishers/MicrosoftWindowsServer/ArtifactTypes/VMImage/Offers/WindowsServer/Skus/2019-datacenter-gensecond/Versions/17763.5122.231109",
  "imageDeprecationStatus": {
    "alternativeOption": null,
    "imageState": "Active",
    "scheduledDeprecationTime": null
  },
  "location": "westus",
  "name": "17763.5122.231109",
  "osDiskImage": {
    "operatingSystem": "Windows",
    "sizeInGb": 127
  },
  "plan": null,
  "tags": null
}
```

### Minimum API Version Required

2021-11-01

### Swagger PR link / SDK link

[Compute Swagger 2021-11-01](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2021-11-01/compute.json)

### Request Example

- [Create VM with UEFI Settings JSON](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2021-11-01/examples/compute/CreateAVmWithUefiSettings.json)
- [Create VMSS with UEFI Settings JSON](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2021-11-01/examples/compute/CreateAScaleSetWithUefiSettings.json)

### Target Date

2024-01-10

### PM Contact

ajkundna

### Engineer Contact

abver

### Additional context

- **Change in request since November 2023 (breaking change implementation)**:
   - OS image check extended from hyperVGeneration = v2 to hyperVGeneration = v2 AND securityType contains TrustedLaunch

- Error message from API: 

Id | PS/CLI Scenario | Existing API Error Message | Updated API Error Message (November 2023)
-|-|-|-
1 | Input VM Size is Gen1-Only and PS/CLI enables TL. | Not Available | The VM size '<VM Size Name> is not supported for creation of VMs and Virtual Machine Scale Set with 'TrustedLaunch' security type. For more information, see https://aka.ms/TrustedLaunch-FAQ
2 | Input VM Size is Non-TL supported. PS/CLI TLaD enables TL for deployment | The VM size 'Standard_A4_v2' is not supported for creation of VMs and Virtual Machine Scale Set with 'TrustedLaunch' security type. | The VM size '<VM Size Name> is not supported for creation of VMs and Virtual Machine Scale Set with 'TrustedLaunch' security type. For more information, see https://aka.ms/TrustedLaunch-FAQ
3 | Input PIR Gen2 OS Image is not TL supported. PS/CLI enables TL for deployment. | Use of TrustedLaunch setting is not supported for the provided image. | Use of TrustedLaunch setting is not supported for the provided image “<image name>”. Please select Trusted Launch Supported Gen2 OS Image. For more information, see https://aka.ms/TrustedLaunch-FAQ

**Comment by zhoxing-ms** [comment]
@AjKundnani I see some changes of default behavior in this feature request. May I ask will these default changes cause breaking changes to the customers' automation scripts or processes?

**Comment by AjKundnani** [comment]
@zhoxing-ms - This change will reduce the scope of previous TL-as-default breaking change and ensure deployments succeed by failing back to Gen2 if OS Image is not TLSupported.

In summary it'll not cause breaking change to customer's existing automation script.

**Comment by zhoxing-ms** [comment]
@AjKundnani Okay, thank you for your confirmation

**Comment by yanzhudd** [comment]
> If hyperVGeneration for OS image is v2 AND under features does not contains TrustedLaunch then following parameters are set by default:
--security-type with value Standard
with the following message displayed and Trusted Launch default is not applied. Consider upgrading security for your workloads using Azure Trusted Launch VMs. To know more about Trusted Launch, please visit https://aka.ms/TrustedLaunch

Hi @AjKundnani,
could you share a image URN/ID whose hyperVGeneration is v2 and under features does not contains TrustedLaunch, so that we can add a test for this case to CLI?

**Comment by AjKundnani** [comment]
> Hi @AjKundnani, could you share a image URN/ID whose hyperVGeneration is v2 and under features does not contains TrustedLaunch, so that we can add a test for this case to CLI?

@yanzhudd - Please try with following image:
- Publisher: OpenLogic
- Offer: CentOS
- SKYU: 7_6-gen2
