### ISSUE TITLE
Support cross-subscription resource ID

### ISSUE THREAD

**Issue by mahipdeora** [Azure/azure-cli#28003]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

**az network lb create**
az network lb frontend-ip create
az network lb frontend-ip update
az network lb address-pool create 
az network lb address-pool update
az network lb address-pool address add
az network lb address-pool address update

### Resource Provider

Microsoft.Network/loadBalancers

### Description of Feature or Work Requested

The SLB team is launching a cross-subscription feature for Azure Load Balancer. Currently, the CLI parameters (vnet, subnet, public IP addresses) accept resource IDs, but the IDs are limited to same subscription as the LB. 

CLI should now support accepting resource IDs without this restriction and accepts Ids across subscriptions. 

In addition, the command "az network lb create" vnet parameter should be able to take in an ID value (currently only accepts a name). 

### Minimum API Version Required

2023-04-01

### Swagger PR link / SDK link

 N/A

### Target Date

2024-02-02

### PM Contact

mahipdeora, anniefang

### Engineer Contact

irrogozh

### Additional context

Please reach out on teams for additional questions

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
@mahipdeora If my understanding correctly, except `az network lb create`, other commands already supported cross-subscription. Could you please confirm it for me? Thanks.

**Comment by mahipdeora** [comment]
The CLI exits out with the following: 

**Command:** az network lb frontend-ip create -g MahipCrossSUBCarnary -n MyFrontendIp --lb-name MyLb --public-ip-address '/subscriptions/56a332c0-57e2-46a2-a204-2d85d11e0e71/resourceGroups/crosssubTest/providers/Microsoft.Network/publicIPAddresses/Test'


**Exit Code:**
(LoadBalancerMustReferenceResourcesFromSameSubscription) LoadBalancer /subscriptions/6bb4a28a-db84-4e8a-b1dc-fabf7bd9f0b2/resourceGroups/MahipCrossSUBCarnary/providers/Microsoft.Network/loadBalancers/MyLb must use network resources from the same subscription and should not reference resources from different subscriptions.
Code: LoadBalancerMustReferenceResourcesFromSameSubscription
Message: LoadBalancer /subscriptions/6bb4a28a-db84-4e8a-b1dc-fabf7bd9f0b2/resourceGroups/MahipCrossSUBCarnary/providers/Microsoft.Network/loadBalancers/MyLb must use network resources from the same subscription and should not reference resources from different subscriptions.


The same command done through rest API/ARM works.

**Comment by mahipdeora** [comment]
Yes you are correct for frontend. There is a bug with the backend CLI command (taken offline), so I can only test that once the bug is resolved. 

Could we build support out for LB create?

**Comment by ReaNAiveD** [comment]
Hi @mahipdeora . 

According to the help message, the argument `--subnet` in `az network lb create` can accept an existing subnet from another subscription. Is this working for you?
![image](https://github.com/Azure/azure-cli/assets/32201005/3559b08b-0fb1-47eb-8c5e-07ecc1027f16)

I think modifying the `--vnet-name` argument is unnecessary if the `--subnet` argument already supports cross-subscription. 
The `--vnet-name` argument is meant to be used with the `--subnet` argument, and changing it to accept vnet-id or adding a new argument `--vnet-id` would only confuse the users.

**Comment by necusjz** [comment]
@mahipdeora It means `--subnet` and `--vnet-name` under _az network lb create_, does the creation support cross subscription when input `--subnet` in ID format as the help message says?
> Name or ID of a subnet. Uses existing resource or creates new
                                     if specified, or none if omitted. If name specified, also
                                     specify --vnet-name. If you want to use an existing subnet in
                                     other resource group or subscription, please provide the ID
                                     instead of the name of the subnet.

**Comment by mahipdeora** [comment]
Right but when a customer sets the subnet property/vnet name, do we add that vnet to the backend pool of the LB? For example, in LB create if I specify a BE pool, vnet, and subnet, does the BE pool get assigned the vnet?

**Comment by necusjz** [comment]
@mahipdeora Thanks for your clarification. IMO, the subnet/vnet settings are related to `frontendIPConfigurations` (i.e., subnet_id), `backendAddressPools` is independent from it. https://github.com/Azure/azure-cli/blob/759bb130cc6736c80aab945a0902d13a75ce7b8f/src/azure-cli/azure/cli/command_modules/network/_template_builder.py#L356-L370

**Comment by mahipdeora** [comment]
Ah in that case, the subnet should be fine and we won't need the vnet ID.

**Comment by necusjz** [comment]
@mahipdeora Yes..., but our concern is currently `--subnet` in ID format is cross-subscription or not, could you please confirm it for us?

**Comment by mahipdeora** [comment]
I just attempted this, and it fails with the following 

az network lb create -g MahipCrossSUBCarnary -n MyLb2 --sku Standard --subnet '/subscriptions/56a332c0-57e2-46a2-a204-2d85d11e0e71/resourceGroups/crosssubTest/providers/Microsoft.Network/virtualNetworks/vnet/subnets/default'
subnet 

/subscriptions/56a332c0-57e2-46a2-a204-2d85d11e0e71/resourceGroups/crosssubTest/providers/Microsoft.Network/virtualNetworks/vnet/subnets/default does not exist. Specify ( --subnet NAME [--vnet-name NAME] ) to create a new resource.

**Comment by mahipdeora** [comment]
Just attempted and it fails with 

az network lb create -g MahipCrossSUBCarnary -n LBNAME2 --sku Standard --subnet '/subscriptions/56a332c0-57e2-46a2-a204-2d85d11e0e71/resourceGroups/crosssubTest/providers/Microsoft.Network/virtualNetworks/vnet/subnets/default' --location eastus2euap

subnet /subscriptions/56a332c0-57e2-46a2-a204-2d85d11e0e71/resourceGroups/crosssubTest/providers/Microsoft.Network/virtualNetworks/vnet/subnets/default does not exist. Specify ( --subnet NAME [--vnet-name NAME] ) to create a new resource.

**Comment by mahipdeora** [comment]
Same deployment goes through via ARM template.

**Comment by ReaNAiveD** [comment]
Hi @mahipdeora .Thanks for your confirmation. 

I'm working on supporting cross-subscription resource ID for `--subnet` and `--public-ip-address`. 
However, I ran into a `SubscriptionNotRegisteredForFeature` when I tried to test this functionality. The error message says '`Subscription 0b1f6471-1bf0-4dda-aec3-cb9272f09590 is not registered for feature AllowCrossSubscriptionReferences required to carry out the requested operation.`'

Unfortunately, I cannot register this feature myself due to a `FeatureRegistrationUnsupported` error. Could you please help me register this feature for the test subscription `0b1f6471-1bf0-4dda-aec3-cb9272f09590`?
