### ISSUE TITLE
`az graph query` keys are inconsistent

### ISSUE THREAD

**Issue by gsmith077** [Azure/azure-cli#28012]
### Describe the bug

We have various processes where we audit resources via graph. Our method that has worked for the better part of 2 years involves a call of 
```
$Results = az graph query `
    --subscriptions $Customer_Subscription_Id `
    --first 1000 `
    -q ${Query} `
    -o json --debug `
  | ConvertFrom-Json
  ```
  
  This is performed in a `.psm1` file, where we build repeatable execution contexts.
  
  Recently (exact date unknown) we started getting error when deserializing into a powershell object from json. Included is some of the error handling text from our automation:

```
Running Azure Graph Query...
Error encountered while executing for $Subscription
The Actual error is:
Cannot convert the JSON string because it contains keys with different casing. Please use the -AsHashTable switch instead. The key that was attempted to be added to the existing key 'CostCenter' was 'costcenter'.
```
  
 This also appears when we target different resource types. SQL databases gives an `'Environment' was 'environment'` variant of the above error.
 
 Is there a reason for this sudden inconsistency in the keys being returned by graph query?

### Related command

az graph query

### Errors

On consumption via powershell `ConvertFrom-Json`:

```
Cannot convert the JSON string because it contains keys with different casing. Please use the -AsHashTable switch instead. The key that was attempted to be added to the existing key 'CostCenter' was 'costcenter'
```

### Issue script & Debug output

None relevant: The command executes and gives data back, the data is just inconsistent.

### Expected behavior

A call to query should have the same output format. Casing should not change between items in a query.

### Environment Summary

azure-cli                         2.55.0

core                              2.55.0
telemetry                          1.1.0

Extensions:
resource-graph                     2.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/home/azureuser/.azure/cliextensions'

Python (Linux) 3.11.5 (main, Nov 29 2023, 03:42:00) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by gsmith077** [comment]
It looks like this was an issue with the tags being unstandardized in the resources.

I am curious if it makes sense to present the json of resource tags as an object `"tags": {"a":"1","b":"2"}` instead of a list of objects: `"tags":[{"a":"1"},{"b":"2"}]`.

Either way, It looks like we just encountered a situation that hadn't been encountered before and assumed it was an issue with `az graph query` calls.

**Comment by nbarnwell** [comment]
Just another one for this. `az storage account list` returns a lot of information, and if I just want a list of the names I'd like to do `az storage account list | ConvertFrom-Json | Select-Object 'name'` but I get the error "Cannot convert the JSON string because it contains keys with different casing". Makes it totally useless, unfortunately.

**Comment by gsmith077** [comment]
@nbarnwell In the year since I encountered this issue, I've learned not to trust Azure and its CLI for sane practices. You will have to rely on the external functionality from `jmespath` to get a list of names.

Try adding `--query "[].name"` argument to your usage on the `az storage account list`. This will have it return only the name property of the listed storage accounts. This will reduce the response list of objects to a list of strings that should be able to be serialized.

Since you're reducing it to just a list of names, the rest of the properties (like mismatching tags) won't be a problem for your `ConvertFrom-Json`.

If you need the rest of the data, your best bet is to drop the tags from everything or run them through a `"STRING".ToLower()` type operation to compensate.

---

I'm going to mark this as closed. Azure semi-randomly decides to down-cast capital characters on some resources (I had to compensate for this on vnet managers for example). It will also full-caps some resource groups and their properties seemingly randomly. You have inconsistencies in whether resources support tags on creation, or at all, and the behaviors of tags can be random.

You have to take full ownership of the data, piecemeal it, and compensate for glaring weaknesses in the platform that don't make sense. That's just the cost of using Azure.
