### ISSUE TITLE
Support NetworkSecurityGroupEnabled and RouteTableEnabled values for PrivateEndpointNetworkPolicies

### ISSUE THREAD

**Issue by ajinkyapotdar** [Azure/azure-cli#28016]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az network vnet subnet update  --disable-private-endpoint-network-policies false    --name default --resource-group myResourceGroup   --vnet-name myVNet

### Resource Provider

Microsoft.Network

### Description of Feature or Work Requested

Presently PrivateEndpointNetworkPolicies enum in virtualNetwork.json that's part of networking swagger supports Enabled and Disabled values. We have added couple more enum values NetworkSecurityGroupEnabled and RouteTableEnabled in the swagger spec recently and need CLI support for the same.

### Minimum API Version Required

2023-09-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/26972

### Request Example

https://github.com/chrisbrugal/azure-rest-api-specs/blob/29a51b9a858f398d21c5eeb95c19f0845d18f435/specification/network/resource-manager/Microsoft.Network/stable/2023-09-01/virtualNetwork.json

### Target Date

2023-12-22

### PM Contact

ivapplyr@microsoft.com

### Engineer Contact

cbrugal@microsoft.com

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
@ajinkyapotdar and @ivapplyr, as the specs changes haven't merged into main branch, may I know is service ready for API version `2023-09-01` now?

**Comment by ivapplyr** [comment]
Yes the API changes are already in effect. This is to ensure Swagger catches up

From: necusjz ***@***.***>
Date: Wednesday, December 13, 2023 at 2:58 AM
To: Azure/azure-cli ***@***.***>
Cc: Ivens Applyrs ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/azure-cli] Support NetworkSecurityGroupEnabled and RouteTableEnabled values for PrivateEndpointNetworkPolicies (Issue #28016)

@ajinkyapotdar<https://github.com/ajinkyapotdar> and @ivapplyr<https://github.com/ivapplyr>, as the specs changes haven't merged into main branch, may I know is service ready for API version 2023-09-01 now?

**Comment by necusjz** [comment]
@ajinkyapotdar and @ivapplyr, is there any breaking changes on `2023-09-01`? I got `PrivateLinkConfigurationsSubnetShouldHavePrivateLinkServiceNetworkPoliciesDisabled` error after bump version.

**Comment by ivapplyr** [comment]
That is a different property so not sure. @Ajinkya ***@***.***> can you comment?

-Ivens Applyrs
Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by necusjz** [comment]
Add more context for @ajinkyapotdar, `privateEndpointNetworkPolicies` is Disabled by default and `privateLinkServiceNetworkPolicies` is Enabled by default but asking for Disabled.

**Comment by ajinkyapotdar** [comment]
This is a different property (not related to the changes you are making).  Disabling privateLinkServiceNetworkPolicies is day 0 requirement. Nothing changed there.

**Comment by necusjz** [comment]
@ajinkyapotdar I see. And I wanna confirm one thing, is `2023-09-01` stable enough? As subnet create/update is a very basic command, plenty of operations depend on it...

**Comment by necusjz** [comment]
@ivapplyr As the code freeze date is coming, we do need the above confirmation, thanks.

**Comment by ivapplyr** [comment]
Yes this is stable. We are several APIs ahead with no issues. This update is for swagger to capture change

-Ivens Applyrs
Outlook for iOS<https://aka.ms/o0ukef>
________________________________
