### ISSUE TITLE
That code didn't work. Check the code and try again.

### ISSUE THREAD

**Issue by rwb196884** [Azure/azure-cli#28029]
### Describe the bug

```
# az login --use-device-code
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code LLD35HQDH to authenticate.
```
![image](https://github.com/Azure/azure-cli/assets/12090617/f6d090ad-36d5-40d7-b4c3-0b770b39b079)

### Related command

az login --use-device-code

### Errors

That code didn't work. Check the code and try again.

### Issue script & Debug output

?

### Expected behavior

It works.

### Environment Summary

# az --version
azure-cli                         2.45.0 *

core                              2.45.0 *
telemetry                          1.0.8 *

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                              1.21.0
azure-mgmt-resource               22.0.0

Python location '/usr/bin/python3'
Extensions directory '/root/.azure/cliextensions'
Extensions system directory '/usr/lib/python3/dist-packages/azure-cli-extensions'

Python (Linux) 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]

Legal docs and information: aka.ms/AzureCliLegal

You have 3 update(s) available. Consider updating your CLI installation with 'az upgrade'

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
