### ISSUE TITLE
az storage blob show command doesn't list blob url in verbose mode

### ISSUE THREAD

**Issue by mw007** [Azure/azure-cli#2802]
**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
docker

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
~~~
# az --version
azure-cli (2.0.2+dev)

acr (2.0.0+dev)
acs (2.0.2+dev)
appservice (0.1.2+dev)
batch (2.0.0+dev)
cloud (2.0.0+dev)
component (2.0.0+dev)
configure (2.0.2+dev)
container (0.1.2+dev)
core (2.0.2+dev)
dla (0.0.1+dev)
dls (0.0.1+dev)
documentdb (0.1.2+dev)
feedback (2.0.0+dev)
find (0.0.1b1+dev)
iot (0.1.2+dev)
keyvault (2.0.0+dev)
lab (0.0.1+dev)
monitor (0.0.1+dev)
network (2.0.2+dev)
nspkg (2.0.0+dev)
profile (2.0.2+dev)
redis (0.1.1b3+dev)
resource (2.0.2+dev)
role (2.0.1+dev)
sql (2.0.0+dev)
storage (2.0.2+dev)
taskhelp (0.1.1b4+dev)
vm (2.0.2+dev)

Python (Linux) 3.5.2 (default, Dec 27 2016, 21:33:11) 
[GCC 5.3.0]
~~~

**OS Version:** What OS and version are you using?  
Red Hat Enterprise Linux Server 7.2

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
bash

---

### Description

In Azure CLI 1.0, the blob url is shown in the verbose output of the `azure storage blob show` command; see below.

~~~
# azure storage blob show -v -a mystorageacct -k mystoragekey --container mycontainer myblob
...
{ url: 'https://mystorageacct.blob.core.windows.net:443/mycontainer/myblob',
...
~~~

The Azure CLI 2.0 does not do this. Can this functionality be added?

**Comment by tjprescott** [comment]
Hi @mw007, you can use the `az storage blob url` command to get this. It takes the same parameters as blob show.

**Comment by mw007** [comment]
Thanks @tjprescott I'm not sure how I missed that command.
