### ISSUE TITLE
az storage share list command is failing on the storage account not having file share

### ISSUE THREAD

**Issue by MageshSrinivasulu** [Azure/azure-cli#28026]
### Describe the bug

`az storage share list` must return an empty list if the storage account does not have a file share. 

Instead, the command is stuck for some time and getting timed out

Error:

<urllib3.connection.HTTPSConnection object at 0x05ABBD10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

### Related command

az storage share list --account-name <storage-account-name>

### Errors

<urllib3.connection.HTTPSConnection object at 0x05ABBD10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

### Issue script & Debug output

Not applicable

### Expected behavior

Show return empty array

### Environment Summary

azure-cli                         2.55.0

core                              2.55.0
telemetry                          1.1.0

Extensions:
aks-preview                      0.5.166
ssh                                2.0.1

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by calvinhzy** [comment]
Hi @MageshSrinivasulu it seems to be working fine in westus. Which region did you try it in? Can you try logging in again with `az login`? 
![image](https://github.com/Azure/azure-cli/assets/17182306/e216f827-dfb1-45c1-8274-6fc7a7fdd15d)
