### ISSUE TITLE
Any extensions are available to join the VM to domain after deployment?

### ISSUE THREAD

**Issue by gangadhar01a** [Azure/azure-cli#2803]
### Environment summary

Please list out the extension/s which I can use through Powershell to join the deployed VM to the domain.

Thanks
**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:2.0.1

**OS Version:** What OS and version are you using?  
Answer here:

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:Windows

---

**Comment by tjprescott** [comment]
Powershell is not a supported shell for AzureCLI 2.0.  If you are using Powershell, please refer to https://github.com/Azure/azure-powershell

**Comment by tjprescott** [comment]
Closing as this question was in regards to Powershell.
