### ISSUE TITLE
Installing kubectl via Azure CLI cause PATH variable to be set as REG_SZ in Windows Registry

### ISSUE THREAD

**Issue by beaulieukevin** [Azure/azure-cli#28049]
**Related command**

az aks install-cli

**Is your feature request related to a problem? Please describe.**

The installation of kubectl via the Azure CLI cause the type of PATH on Windows to be set as REG_SZ instead of REG_EXPAND_SZ.
This can lead to unexpected non expanded URI from other applications.

**Describe the solution you'd like**

In the file `src/azure-cli/azure/cli/command_modules/acs/custom.py` line 1652 within the function `append_install_dir_to_windows_user_path`, you are using the `setx` process which is leading to this behavior.
Probably better to check the PATH value type using the Windows Registry API and to setup the correct type accordingly.

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by FumingZhang** [comment]
@devwith-kev thanks for pointing this out, however, after my testing, for the user Path, which is originally REG_EXPAND_SZ, its type does not change after the command is executed. Besides, I don't see that setx has an option for specifying the type of the variable being set, do you have any suggestions?

**Comment by FumingZhang** [comment]
no response
