### ISSUE TITLE
Error in description of  "az storage account file-service-properties update" SMB properties

### ISSUE THREAD

**Issue by hcrutz** [Azure/azure-cli#28069]
### Describe the bug

The documentation contains the following section:
"Set secured SMB setting for file service.
        az storage account file-service-properties update --versions SMB2.1;SMB3.0;SMB3.1.1 --auth-
        methods NTLMv2;Kerberos --kerb-ticket-encryption RC4-HMAC;AES-256 --channel-encryption AES-
        CCM-128;AES-GCM-128;AES-GCM-256 -n mystorageaccount -g MyResourceGroup"
But the listed values for --channel-encryption are wrong and cause an error if you use them as listed       

### Related command

az storage account file-service-properties update --versions SMB3.1.1 --auth-methods Kerberos --kerb-ticket-encryption AES-256 
--channel-encryption AES-GCM-256 -n mystorageaccount -g MyResourceGroup

### Errors

(InvalidXmlDocument) XML specified is not syntactically valid.
RequestId:40331b1e-901a-0000-7d54-33bb39000000
Time:2023-12-20T14:57:16.6027100Z
Code: InvalidXmlDocument
Message: XML specified is not syntactically valid.
RequestId:40331b1e-901a-0000-7d54-33bb39000000
Time:2023-12-20T14:57:16.6027100Z

### Issue script & Debug output

not needed here

### Expected behavior

The values you have to enter here for --channel-encryption are:
AES-128-CCM;AES-128-GCM;AES-256-GCM

### Environment Summary

azure-cli                         2.55.0

core                              2.55.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
