### ISSUE TITLE
allow-blob-public-access and allow-cross-tenant-replication option's default value in "az storage account create" command

### ISSUE THREAD

**Issue by Yongchool** [Azure/azure-cli#28068]
**Related command**

az storage account create

**Is your feature request related to a problem? Please describe.**

In the public documentation, it explain allow-blob-public-access and allow-cross-tenant-replication option's default value in "az storage account create" command is true.

![image](https://github.com/Azure/azure-cli/assets/67408348/da0714ef-1f1d-4fa7-8f04-081de00e9d76)

**Describe the solution you'd like**

New Azure Storage accounts created from August 2023 is created with default value is false about allow-blob-public-access and allow-cross-tenant-replication option.
Please changed the explain in the documentation to that "If not specified, the default value is currently false for new accounts to follow best security practices."

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by calvinhzy** [comment]
Hi @Yongchool, there have been ongoing service changes so the default behavior was not reliable. Starting in January the documentation will specify the default value for both param to be false. Thanks.
