### ISSUE TITLE
az functionapp config appsettings set --settings parameter not processing multiple space-separated settings

### ISSUE THREAD

**Issue by felix-the** [Azure/azure-cli#28071]
### Describe the bug

Does not actually process space-separated key-value pairs as expected

### Related command

az functionapp config appsettings set

### Errors

No error, just the input isn't processed as expected

### Issue script & Debug output

az functionapp config appsettings set -n [function-name] -g [rg-name] --settings **"key1=value1 key2=value2"**

Excerpt of the output of the list command
az functionapp config appsettings list -n [function-name] -g [rg-name]

  {
    "name": "key1",
    "slotSetting": false,
    "value": "value1 **key2=value2**"
  }

i.e. **[space]key2=value2** is being treated as part of key1's value

### Expected behavior

Expecting the two space-separated key-value pairs will be converted to two separate items in settings, like below

  {
    "name": "key1",
    "slotSetting": false,
    "value": "value1"
  },
  {
    "name": "key2",
    "slotSetting": false,
    "value": "key2=value2"
  }

### Environment Summary

Executed from Azure cloud shell.

azure-cli                         2.55.0

core                              2.55.0
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
ml                                2.22.0
ssh                                2.0.2

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.9'
Extensions directory '/home/felix/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.14 (main, Oct 12 2023, 19:48:32) 
[GCC 11.2.0]

### Additional context

Expecting one of the two:
1. AZ CLI fix to actually take multiple space-separated settings with a single **--settings** parameter as described in docs
2. Fixing docs to mention multiple **--settings** parameters are needed

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by kamperiadis** [comment]
Hello @felix-the I was able to reproduce the issue when running the command with that format:
`az functionapp config appsettings set -n [function-name] -g [rg-name] --settings "key1=value1 key2=value2"`
However, I get the expected behavior when I run the command without the quotation marks:
`az functionapp config appsettings set -n [function-name] -g [rg-name] --settings key1=value1 key2=value2`

Can you please run the command again without the quotation marks?

**Comment by felix-the** [comment]
OK thanks @kamperiadis. Your suggestion actually works. I'd recommend updating the example in the docs listed below and have the double-quotes removed.

`az functionapp config appsettings set --name MyFunctionApp --resource-group MyResourceGroup --settings "AzureWebJobsStorage=$storageConnectionString"
`

I saw the above example, and then the following:

> --settings
> Space-separated appsettings in KEY=VALUE format. Use @{file} to load from a file.

And did what I did, which is throwing multiple KEY=VALUE pairs inside the pair of double-quotes.

**Comment by kamperiadis** [comment]
Thank you for the feedback @felix-the I just created a PR to update documentation. Since there are no other action items to take for this issue, I will mark it as resolved. Please open a new GitHub issue if you have any questions/issues in the future. Thank you.
