### ISSUE TITLE
Making 2023-09-01 api-version as default for VMSS operations 

### ISSUE THREAD

**Issue by mannanbansal** [Azure/azure-cli#28080]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az vmss create
az vmss update

### Resource Provider

Microsoft.Compute

### Description of Feature or Work Requested

Some of the new feature offerings for VMSS flex has been rolled out under 2023-09-01 api-version. Although customer is able to use those features through SDK, PS etc. but we need to update CLI also for these features. One of those features is instanceProtection which is already there for VMSS Uniform and works fine with CLI, and I see there are no client-side validation for this feature while executing command for VMSS flex. And there are some key customers who use CLI for these operations. We just need to update api-version for VMSS in CLI, as there are no client side validations while running the command.
Command:
For Eg: az vmss update -n {vmssName} -g {rgName} --instance-id {vmssVmName} --protectFromScaleIn

### Minimum API Version Required

2023-09-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/26270/

### Request Example

NA

### Target Date

2024-01-10

### PM Contact

@bhawanaraj

### Engineer Contact

@mannanbansal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yanzhudd** [comment]
> Target Date
> 2024-01-10

Hi @mannanbansal,
please note that we would have a code freeze on 12-26 for the release of this sprint, and we don't have extra time to develop this feature. May I ask if the next release train (02-06) is acceptable to you?

**Comment by mannanbansal** [comment]
Thanks Yan for reverting, yeah we are fine with next release train on 02/06.

**Comment by yanzhudd** [comment]
PR: #28078
