### ISSUE TITLE
'az rest' can't handle the long uri returned by azure-asyncoperation response header

### ISSUE THREAD

**Issue by devlie** [Azure/azure-cli#28086]
### Describe the bug

When using `az rest` to call an ARM LRO, the response would include `azure-asyncoperation` response header that points to `OperationStatus` resource that we can use for LRO polling. Passing that url to `az rest` would yield this error:

```
└$ az rest --uri $uri
Unauthorized({"error":{"code":"AuthorizationFailed","message":"Unable to verify that the user that sent this request is the original caller of the asynchronous operation being polled."}})
't' is not recognized as an internal or external command,
operable program or batch file.
'c' is not recognized as an internal or external command,
operable program or batch file.
's' is not recognized as an internal or external command,
operable program or batch file.
'h' is not recognized as an internal or external command,
operable program or batch file.
```

I had ARM service dev took a look and they claimed that the request they received did not contain all the params, so it appears that `az rest` is clipping the uri.

I then tried manually calling the REST API and was able to:

```powershell
└$ invoke-restmethod $uri -Headers @{ Authorization = "Bearer $($token.accessToken)" } | convertto-json -depth 10
{
  "id": "/providers/Microsoft.DeviceUpdate/locations/WESTUS3/operationStatuses/013069f9-7bbf-4249-9c10-c3bd1874ab03*650317BAB2A67D42109EB673BACAFC6323FC5870F8A8BD332357906D4B1A0E7C",
  "name": "013069f9-7bbf-4249-9c10-c3bd1874ab03*650317BAB2A67D42109EB673BACAFC6323FC5870F8A8BD332357906D4B1A0E7C",
  ....
}
```

### Related command

az rest

### Errors

```
└$ az rest --uri $uri
Unauthorized({"error":{"code":"AuthorizationFailed","message":"Unable to verify that the user that sent this request is the original caller of the asynchronous operation being polled."}})
't' is not recognized as an internal or external command,
operable program or batch file.
'c' is not recognized as an internal or external command,
operable program or batch file.
's' is not recognized as an internal or external command,
operable program or batch file.
'h' is not recognized as an internal or external command,
operable program or batch file.
```

### Issue script & Debug output

--verbose and --debug doesn't work in this case. It just returns the mentioned error.

### Expected behavior

Able to get `OperationStatus` resource.

### Environment Summary

└$ az --version
azure-cli                         2.52.0 *

core                              2.52.0 *
telemetry                          1.1.0

Extensions:
azure-devops                      0.26.0
azure-iot                    255.255.1.9

Dependencies:
msal                            1.24.0b1
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\leolie\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
I guess you are using PowerShell and hitting https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md.

```
't' is not recognized as an internal or external command,
operable program or batch file.
'c' is not recognized as an internal or external command,
operable program or batch file.
's' is not recognized as an internal or external command,
operable program or batch file.
'h' is not recognized as an internal or external command,
operable program or batch file.
```

These errors indicate the URL Azure CLI receives is corrupted by the shell. Most likely, `&` is recognized by CMD as a command separator. 

I can repro the error with 

```
> $url='https://management.azure.com/a&b'
> az rest -u $url
Bad Request({"error":{"code":"MissingApiVersionParameter","message":"The api-version query parameter (?api-version=) is required for all requests."}})
'b' is not recognized as an internal or external command,
operable program or batch file.
```

> --verbose and --debug doesn't work in this case. It just returns the mentioned error.

`--debug` does provide more information on the arguments Azure CLI actually receives after shell's parsing, but in this case, you need to add `--debug` directly after `az` to prevent the shell from interpreting it as part of a separate command:

```
> az --debug rest -u $url
cli.knack.cli: Command arguments: ['--debug', 'rest', '-u', 'https://management.azure.com/a']
```

To make `$url` work, you need to quote `$url` with literal double quotes `"` to prevent CMD from interpreting the ampersand `&` in it.

```
> az --debug rest -u `"$url`"
cli.knack.cli: Command arguments: ['--debug', 'rest', '-u', 'https://management.azure.com/a&b']

> az --debug rest -u "`"$url`""
cli.knack.cli: Command arguments: ['--debug', 'rest', '-u', 'https://management.azure.com/a&b']
```
