### ISSUE TITLE
packages.microsoft.com is very slow

### ISSUE THREAD

**Issue by yasharya2901** [Azure/azure-cli#28099]
### Describe the bug

I am trying to update microsoft-edge, however, the speed is super slow and all the other packages have already been downloaded. Also, here's the preview of the `ping -c10 packages.microsoft.com`:
```
PING csd-apt-weu-d-4.westeurope.cloudapp.azure.com (13.81.215.193) 56(84) bytes of data.

--- csd-apt-weu-d-4.westeurope.cloudapp.azure.com ping statistics ---
10 packets transmitted, 0 received, 100% packet loss, time 9192ms

```

### Related command

`ping -c10 packages.microsoft.com`

### Errors

Slow speed

### Issue script & Debug output

`ping -c10 packages.microsoft.com`

```
PING csd-apt-weu-d-4.westeurope.cloudapp.azure.com (13.81.215.193) 56(84) bytes of data.

--- csd-apt-weu-d-4.westeurope.cloudapp.azure.com ping statistics ---
10 packets transmitted, 0 received, 100% packet loss, time 9192ms
```

### Expected behavior

Should be super fast

### Environment Summary

```
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### Additional context

I didn't know where to post about this issue. If it is not relevant to this project, please pass it to the concerned team.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
You can report it to https://github.com/microsoft/linux-package-repositories/issues

**Comment by bebound** [comment]
I can't repo, the pi
