### ISSUE TITLE
Using the Microsoft Documentation unable to create subnet

### ISSUE THREAD

**Issue by Ratnavo** [Azure/azure-cli#28097]
### Describe the bug

we are unable to create a new subnet for an existing VNet after using all the right values. A VNet is already created with the right address-prefix of /16 enough to create multiple subnets. Output of Az Vnet show command, the below subnet-A was already created during the time of creation of VNet.
=================
 az network vnet show -g app-grp -n app-network
{
  "addressSpace": {
    "addressPrefixes": [
      "10.0.0.0/16"
    ]
  },
  "dhcpOptions": {
    "dnsServers": []
  },
  "enableDdosProtection": false,
  "etag": "W/\"6e6aa3cc-a73f-4f62-a7c9-f43e41dbde6d\"",
  "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/app-grp/providers/Microsoft.Network/virtualNetworks/app-network",
  "location": "northeurope",
  "name": "app-network",
  "provisioningState": "Succeeded",
  "resourceGroup": "app-grp",
  "resourceGuid": "f88e30fa-c0c7-41e5-bb6e-43c348e52d8a",
  "subnets": [
    {
      "addressPrefix": "10.0.0.0/24",
      "delegations": [],
      "etag": "W/\"6e6aa3cc-a73f-4f62-a7c9-f43e41dbde6d\"",
      "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/app-grp/providers/Microsoft.Network/virtualNetworks/app-network/subnets/SubnetA",
      "name": "SubnetA",
      "networkSecurityGroup": {
        "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/app-grp/providers/Microsoft.Network/networkSecurityGroups/app-network-SubnetA-nsg-northeurope",
        "resourceGroup": "app-grp"
      },
      "privateEndpointNetworkPolicies": "Disabled",
      "privateLinkServiceNetworkPolicies": "Enabled",
      "provisioningState": "Succeeded",
      "resourceGroup": "app-grp",
      "serviceEndpoints": [],
      "type": "Microsoft.Network/virtualNetworks/subnets"
    }
  ],
  "type": "Microsoft.Network/virtualNetworks",
  "virtualNetworkPeerings": []
}

### Related command

az network vnet subnet create  -n "testing" -g "app-grp" --vnet-name "app-network" -n "testing" --address-prefixes "10.1.0.0/24"
#or
az network vnet subnet create -g app-grp --vnet-name app-network -n MySubnet --address-prefixes 10.1.0.0/24
#or
$subnetname = "test"
$SubnetAddress= "10.1.0.0/24"
az network vnet subnet create --resource-group app-grp --vnet-name app-network --name $subnetname --address-prefixes $SubnetAddress

### Errors

(NetcfgInvalidSubnet) Subnet 'test' is not valid in virtual network 'app-network'.
Code: NetcfgInvalidSubnet
Message: Subnet 'test' is not valid in virtual network 'app-network'.

### Issue script & Debug output

PS C:\C.O.D.E\CLI\Azure-CLI-Code> az network vnet subnet create  -n "testing" -g "app-grp" --vnet-name "app-network" -n "testing" --address-prefixes "10.1.0.0/24" --debug
cli.knack.cli: Command arguments: ['network', 'vnet', 'subnet', 'create', '-n', 'testing', '-g', 'app-grp', '--vnet-name', 'app-network', '-n', 'testing', '--address-prefixes', '10.1.0.0/24', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x016DE7A8>, <function OutputProducer.on_global_arguments at 0x01A07898>, <function CLIQuery.on_global_arguments at 0x01A28668>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'network': ['azure.cli.command_modules.network', 'azure.cli.command_modules.privatedns', 'azext_vwan']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: network                   0.630       115       463
cli.azure.cli.core: privatedns                0.038        14        60
cli.azure.cli.core: Total (2)                 0.668       129       523
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: virtual-wan               0.015        20        84  C:\Users\user\.azure\cliextensions\virtual-wan
cli.azure.cli.core: Total (1)                 0.015        20        84  
cli.azure.cli.core: Loaded 147 groups, 607 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : network vnet subnet create
cli.azure.cli.core: Command table: network vnet subnet create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03B1AE88>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\user\.azure\commands\2023-12-26.20-05-45.network_vnet_subnet_create.33512.log'.
az_command_data_logger: command args: network vnet subnet create -n {} -g {} --vnet-name {} -n {} --address-prefixes {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03B476B8>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03B762A8>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03B762F8>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x01A078E8>, <function CLIQuery.handle_query_parameter at 0x01A286B8>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03B76258>]
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\user\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\user\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/maskedvalue/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/maskedvalue/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/maskedvalue/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/maskedvalue/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/maskedvalue/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/maskedvalue/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/maskedvalue/kerberos', 'tenant_region_scope': 'WW', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: a6aeb9ef-a4dd-4b9e-9904-420ca825c7f1
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/app-grp/providers/Microsoft.Network/virtualNetworks/app-network/subnets/testing?api-version=2023-05-01'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '67'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '0d916398-a3fc-11ee-a27d-dc7196eb3b5a'
cli.azure.cli.core.sdk.policies:     'CommandName': 'network vnet subnet create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-n -g --vnet-name -n --address-prefixes --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.55.0 (MSI) (AAZ) azsdk-python-core/1.26.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"name": "testing", "properties": {"addressPrefix": "10.1.0.0/24"}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/app-grp/providers/Microsoft.Network/virtualNetworks/app-network/subnets/testing?api-version=2023-05-01 HTTP/1.1" 400 129
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '129'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'b003c361-09be-4723-8b45-7a85572649d6'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '6618841c-6915-4e67-b92d-1b3d328fa411'
cli.azure.cli.core.sdk.policies:     'x-ms-arm-service-request-id': 'ffe5675d-a788-408f-b17e-bbc99ecef38d'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1198'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHINDIA:20231226T143547Z:6618841c-6915-4e67-b92d-1b3d328fa411'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 26 Dec 2023 14:35:46 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"NetcfgInvalidSubnet","message":"Subnet 'testing' is not valid in virtual network 'app-network'.","details":[]}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 708, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1013, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1000, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 108, in result
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 130, in wait
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_poller.py", line 83, in _start
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\command_modules\network\aaz_compact\latest\network\vnet\subnet\__cmds.py", line 304, in _execute_operations
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure\cli\command_modules\network\aaz_compact\latest\network\vnet\subnet\__cmds.py", line 344, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_operation.py", line 332, in on_error
azure.core.exceptions.HttpResponseError: (NetcfgInvalidSubnet) Subnet 'testing' is not valid in virtual network 'app-network'.
Code: NetcfgInvalidSubnet
Message: Subnet 'testing' is not valid in virtual network 'app-network'.

cli.azure.cli.core.azclierror: (NetcfgInvalidSubnet) Subnet 'testing' is not valid in virtual network 'app-network'.
Code: NetcfgInvalidSubnet
Message: Subnet 'testing' is not valid in virtual network 'app-network'.
az_command_data_logger: (NetcfgInvalidSubnet) Subnet 'testing' is not valid in virtual network 'app-network'.
Code: NetcfgInvalidSubnet
Message: Subnet 'testing' is not valid in virtual network 'app-network'.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03B1E028>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 3.457 seconds (init: 0.592, invoke: 2.864)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3675 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\user\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

Should be able to accept the script and deploy a new subnet.

### Environment Summary

az --version
azure-cli                         2.55.0

core                              2.55.0
telemetry                          1.1.0

Extensions:
account                            0.2.3
azure-devops                      0.25.0
interactive                        0.4.5
virtual-wan                       0.2.12

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\user\.azure\cliextensions'

Python (Windows) 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:21:31) [MSC v.1936 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
@Ratnavo It seems subnet `10.1.0.0/24` isn't belong to address space of vnet, i.e., `10.0.0.0/16`. `10.0.1.0/24` is valid.

**Comment by Ratnavo** [comment]
Yes, you are right. It was a mistake on my end. Somehow i overlook that part. Please close the item on your end.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
