### ISSUE TITLE
Question: Whats the difference between this repo and azure-xplat-cli?

### ISSUE THREAD

**Issue by billpratt** [Azure/azure-cli#2809]
What's the different between this repo and the [Azure/azure-xplat-cli](https://github.com/Azure/azure-xplat-cli) besides one uses the command ```az``` and the other uses ```azure```? Both appear to be cross platform.

**Comment by allclark** [comment]
They're both cross-platform. The older repo (azure-xplat-cli) is an earlier cli built on node.js and this is a newer one built with python and designed to work well with Bash.

**Comment by billpratt** [comment]
Nice. Thanks!
