### ISSUE TITLE
az network public-ip list --query "[].ipAddress" -o tsv returns empty array when there are public ips

### ISSUE THREAD

**Issue by toutas** [Azure/azure-cli#28100]
### Describe the bug

When I run the command `az network public-ip list --query "[].ipAddress" -o tsv` it sometimes (not always, but often) returns an empty array even when there are VMs provisioned with public ips. 

### Related command

az network public-ip list --query "[].ipAddress" -o tsv 

### Errors

It fails without errors.

### Issue script & Debug output

az network public-ip list --query "[].ipAddress" -o tsv --debug

cli.knack.cli: Command arguments: ['network', 'public-ip', 'list', '--query', '[].ipAddress', '-o', 'tsv', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f4980ec53a0>, <function OutputProducer.on_global_arguments at 0x7f4980e69da0>, <function CLIQuery.on_global_arguments at 0x7f4980c7b880>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'network': ['azure.cli.command_modules.network', 'azure.cli.command_modules.privatedns']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: network                   0.327       115       354
cli.azure.cli.core: privatedns                0.008        14        60
cli.azure.cli.core: Total (2)                 0.335       129       414
cli.azure.cli.core: Loaded 128 groups, 414 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : network public-ip list
cli.azure.cli.core: Command table: network public-ip list
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f497ff10c20>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/ubuntu/.azure/commands/2023-12-27.09-48-45.network_public-ip_list.1097082.log'.
az_command_data_logger: command args: network public-ip list --query {} -o {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f497ff27100>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f497ff80ea0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f497ff80fe0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f4980e69e40>, <function CLIQuery.handle_query_parameter at 0x7f4980c7b920>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f497ff80f40>]
cli.azure.cli.core.auth.persistence: build_persistence: location='/home/ubuntu/.azure/msal_token_cache.json', encrypt=False
cli.azure.cli.core.auth.binary_cache: load: /home/ubuntu/.azure/msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/<sensitive?>/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/<sensitive?>/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/<sensitive?>/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/<sensitive?>/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/<sensitive?>/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/<sensitive?>/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/<sensitive?>/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: f386a291-42f7-4419-b14b-c96a14179bdb
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<sensitive?>/providers/Microsoft.Network/publicIPAddresses?api-version=2022-11-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'be6674ce-a494-11ee-bd80-a8a159c10f57'
cli.azure.cli.core.sdk.policies:     'CommandName': 'network public-ip list'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--query -o --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.55.0 (DEB) (AAZ) azsdk-python-core/1.26.0 Python/3.11.5 (Linux-5.4.0-163-generic-x86_64-with-glibc2.31)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/<sensitive?>/providers/Microsoft.Network/publicIPAddresses?api-version=2022-11-01 HTTP/1.1" 200 133
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11998'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '28adda90-decb-40f0-bf12-c3e8ce85efeb'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '28adda90-decb-40f0-bf12-c3e8ce85efeb'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SWEDENCENTRAL:20231227T084845Z:28adda90-decb-40f0-bf12-c3e8ce85efeb'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Wed, 27 Dec 2023 08:48:45 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '133'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"value":[]}
cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x7f497ff56020>, <function _x509_from_base64_to_hex_transform at 0x7f497ff560c0>]
cli.knack.cli: Event: CommandInvoker.OnFilterResult [<function CLIQuery.handle_query_parameter.<locals>.filter_output at 0x7f497dbc3560>]
cli.knack.cli: Event: Cli.SuccessfulExecute []
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f497ff10ea0>]
az_command_data_logger: exit code: 0
cli.__main__: Command ran in 0.794 seconds (init: 0.113, invoke: 0.682)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3418 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/opt/az/bin/python3 /opt/az/lib/python3.11/site-packages/azure/cli/telemetry/__init__.py /home/ubuntu/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

The output should have been two different ips at the time the command was run, instead of no ips:

52.143.58.121
51.136.4.25

I verified these ips were present through the azure portal, and after a while it started returning these ips instead of no ips again. 

### Environment Summary

azure-cli                         2.55.0

core                              2.55.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/home/ubuntu/.azure/cliextensions'

Python (Linux) 3.11.5 (main, Nov 29 2023, 03:42:00) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

The ansible modules that can retrieve the IP addresses are also affected, e.g `azure.azcollection.azure_rm_publicipaddress_info`. The behaviour is exactly the same as with az cli, returning an empty array when there should be elements in it.

The thing is that provisioning VMs with `azure.azcollection.azure_rm_virtualmachine `works without issues all the time, but too often when running another playbook with `azure.azcollection.azure_rm_publicipaddress_info` (or the `az network public-ip list --query "[].ipAddress" -o tsv` command) afterwards it "fails" intermittently. Retry logic is not viable since it does not actually fail, but just returns an empty array when there should be elements in the array.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jsntcy** [comment]
@necusjz, please help take a look.

**Comment by toutas** [comment]
anything happening on this? this issue is pretty horrific since it breaks ansible awx azure rm inventory integration, so hosts cannot be populated in awx properly. we're moving most if not all of our compute resources away from azure soon, and I can't argue for going back to using azure later with especially this issue present.
