### ISSUE TITLE
 Prompted with error "unrecognized arguments: --node-os-upgrade-channel NodeImage " when executing az aks update command

### ISSUE THREAD

**Issue by SwathiDhanwada-MSFT** [Azure/azure-cli#28118]
### Describe the bug

Getting error even after registering NodeOsUpgradeChannelPreview via below command-

`az feature register --namespace "Microsoft.ContainerService" --name "NodeOsUpgradeChannelPreview"`

Also ran below command after that-

`az provider register --namespace Microsoft.ContainerService`

But was seeing the error as shown in the image.

![image](https://github.com/Azure/azure-cli/assets/48976275/6fca4630-19dd-4a47-8f9a-82d3d31faaf3)

### Related command

`az aks update -g rg -n MyManagedCluster --node-os-upgrade-channel NodeImage`

### Errors

unrecognized arguments: --node-os-upgrade-channel NodeImage

### Issue script & Debug output

PS /home/swathi> az aks update -g rg -n MyManagedCluster --node-os-upgrade-channel NodeImage --debug
cli.knack.cli: Command arguments: ['aks', 'update', '-g', 'rg', '-n', 'MyManagedCluster', '--node-os-upgrade-channel', 'NodeImage', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fb48444a1f0>, <function OutputProducer.on_global_arguments at 0x7fb484365d30>, <function CLIQuery.on_global_arguments at 0x7fb4842fd310>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'aks': ['azext_aks_preview', 'azure.cli.command_modules.acs']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: acs                       0.067         7        54
cli.azure.cli.core: Total (1)                 0.067         7        54
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: ai-examples               0.194         1         1  /usr/lib/python3.9/site-packages/azure-cli-extensions/ai-examples
cli.knack.cli: Event: CommandLoader.OnLoadCommandTable []
cli.azure.cli.core: aks-preview               0.013        13        68  /home/swathi/.azure/cliextensions/aks-preview
cli.azure.cli.core: Total (2)                 0.207        14        69  
cli.azure.cli.core: Loaded 16 groups, 83 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : aks update
cli.azure.cli.core: Command table: aks update
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fb4837a23a0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/swathi/.azure/commands/2024-01-02.15-48-13.aks_update.2648.log'.
az_command_data_logger: command args: aks update -g {} -n {} --node-os-upgrade-channel {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fb48376bdc0>]
cli.knack.cli: Event: CommandLoader.OnLoadArguments []
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7fb4836c70d0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7fb4836ceee0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.azure.cli.core.command_recommender: "--node-os-upgrade-channel" is an invalid parameter for command "aks update".
urllib3.connectionpool: Starting new HTTPS connection (1): app.aladdin.microsoft.com:443
urllib3.connectionpool: https://app.aladdin.microsoft.com:443 "GET /api/v1.0/suggestions?query=%7B%22command%22%3A+%22aks+update%22%2C+%22parameters%22%3A+%22%22%7D&clientType=AzureCli&context=%7B%22versionNumber%22%3A+%222.55.0%22%2C+%22errorType%22%3A+%22UnrecognizedArguments%22%2C+%22correlationId%22%3A+%22e92bb6d3-ed16-4190-877d-99c6be83e33a%22%2C+%22subscriptionId%22%3A+%22b83c1ed3-c5b6-44fb-b5ba-2b83a074c23f%22%2C+%22eventId%22%3A+%223073b235-dfb5-4f78-b26a-dd21d9a2ebb6%22%7D HTTP/1.1" 200 None
cli.azure.cli.core.command_recommender: "--node-os-upgrade-channel" is an invalid parameter for command "aks update".
cli.azure.cli.core.azclierror: NoneType: None

cli.azure.cli.core.azclierror: unrecognized arguments: --node-os-upgrade-channel NodeImage
az_command_data_logger: unrecognized arguments: --node-os-upgrade-channel NodeImage

Examples from AI knowledge base:
az aks update --resource-group MyResourceGroup --name MyManagedCluster --load-balancer-managed-outbound-ip-count 2
Update a kubernetes cluster with standard SKU load balancer to use two AKS created IPs for the load balancer outbound connection usage.

az aks update --resource-group MyResourceGroup --name MyManagedCluster --api-server-authorized-ip-ranges 0.0.0.0/32
Restrict apiserver traffic in a kubernetes cluster to agentpool nodes.

az version
Show the versions of Azure CLI modules and extensions in JSON format by default or format configured by --output (autogenerated)

https://docs.microsoft.com/en-US/cli/azure/aks#az_aks_update
Read more about the command in reference docs
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fb4837a25e0>]
az_command_data_logger: exit code: 2
cli.__main__: Command ran in 1.193 seconds (init: 0.213, invoke: 0.980)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3817 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/bin/python3.9 /usr/lib/az/lib/python3.9/site-packages/azure/cli/telemetry/__init__.py /home/swathi/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

Set the auto upgrade channel using az cli command

### Environment Summary

<img width="366" alt="image" src="https://github.com/Azure/azure-cli/assets/48976275/c600b4d9-4577-4d86-8f22-8841b8987c8b">

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
