### ISSUE TITLE
Basic az aks create command fails with stacktrace in place of a meaningful error message

### ISSUE THREAD

**Issue by mrdeveloperdude** [Azure/azure-cli#28110]
### Describe the bug

When I try to provision a kubernetes cluster with azure cli command it fails with a stacktrace and no meaningful explanation (from a user's perspective).

### Related command

`az aks create -g merchbot-k8s-cluster -n merchbotmanual`

### Errors

CLIInternalError: The command failed with an unexpected error. Here is the traceback:
'ManagedClustersOperations' object has no attribute 'create_or_update'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 659, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 715, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 693, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 330, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 786, in default_command_handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/acs/custom.py", line 2204, in aks_create
    client.create_or_update,
AttributeError: 'ManagedClustersOperations' object has no attribute 'create_or_update'
To open an issue, please run: 'az feedback'

### Issue script & Debug output

az aks create -g merchbot-k8s-cluster -n merchbotmanual --debug
cli.knack.cli: Command arguments: ['aks', 'create', '-g', 'merchbot-k8s-cluster', '-n', 'merchbotmanual', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fe3a4158820>, <function OutputProducer.on_global_arguments at 0x7fe3a4065b80>, <function CLIQuery.on_global_arguments at 0x7fe3a40020d0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'aks': ['azure.cli.command_modules.acs']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: acs                       0.125         7        49
cli.azure.cli.core: Total (1)                 0.125         7        49
cli.azure.cli.core: Loaded 7 groups, 49 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : aks create
cli.azure.cli.core: Command table: aks create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fe3a38d9790>]
az_command_data_logger: command args: aks create -g {} -n {} --debug
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/leo/.azure/commands'.
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fe3a3887ee0>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x7fe3a37e4160>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7fe3a37e41f0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7fe3a37e4310>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fe3a4065c10>, <function CLIQuery.handle_query_parameter at 0x7fe3a4002160>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x7fe3a3858820>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7fe3a37e4280>]
cli.azure.cli.command_modules.acs._validators: Use existing SSH public key file: /home/leo/.ssh/id_rsa.pub
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ContainerServiceClient
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ResourceManagementClient
cli.azure.cli.core.adal_authentication: AdalAuthentication.get_token invoked by Track 2 SDK with scopes=('https://management.core.windows.net//.default',)
cli.azure.cli.core._profile: Retrieving token from ADAL for resource 'https://management.core.windows.net/'
cli.azure.cli.core.util: attempting to read file /home/leo/.azure/accessTokens.json as utf-8-sig
adal-python: 5e91d81f-ee42-49f3-b277-6146753c80c8 - Authority:Performing instance discovery: ...
adal-python: 5e91d81f-ee42-49f3-b277-6146753c80c8 - Authority:Performing static instance discovery
adal-python: 5e91d81f-ee42-49f3-b277-6146753c80c8 - Authority:Authority validated via static instance discovery
adal-python: 5e91d81f-ee42-49f3-b277-6146753c80c8 - TokenRequest:Getting token from cache with refresh if necessary.
adal-python: 5e91d81f-ee42-49f3-b277-6146753c80c8 - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python: 5e91d81f-ee42-49f3-b277-6146753c80c8 - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python: 5e91d81f-ee42-49f3-b277-6146753c80c8 - CacheDriver:Found 1 potential entries.
adal-python: 5e91d81f-ee42-49f3-b277-6146753c80c8 - CacheDriver:Resource specific token found.
adal-python: 5e91d81f-ee42-49f3-b277-6146753c80c8 - CacheDriver:Returning token from cache lookup, AccessTokenId: REDACTED +zND0=', RefreshTokenId: b'REDACTED+hWRw='
azure.core.pipeline.policies._universal: Request URL: 'https://management.azure.com/subscriptions/eaaa3175-65a7-44e2-b998-ffcc28a78cf1/resourcegroups/merchbot-k8s-cluster?api-version=2020-10-01'
azure.core.pipeline.policies._universal: Request method: 'GET'
azure.core.pipeline.policies._universal: Request headers:
azure.core.pipeline.policies._universal:     'Accept': 'application/json'
azure.core.pipeline.policies._universal:     'x-ms-client-request-id': '58f37a05-a734-11ee-b32c-274a246918b0'
azure.core.pipeline.policies._universal:     'CommandName': 'aks create'
azure.core.pipeline.policies._universal:     'ParameterSetName': '-g -n --debug'
azure.core.pipeline.policies._universal:     'User-Agent': 'AZURECLI/2.18.0 (DEB) azsdk-python-azure-mgmt-resource/16.0.0 Python/3.9.2 (Linux-5.10.0-26-amd64-x86_64-with-glibc2.31)'
azure.core.pipeline.policies._universal:     'Authorization': '*****'
azure.core.pipeline.policies._universal: Request body:
azure.core.pipeline.policies._universal: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/eaaa3175-65a7-44e2-b998-ffcc28a78cf1/resourcegroups/merchbot-k8s-cluster?api-version=2020-10-01 HTTP/1.1" 200 292
azure.core.pipeline.policies._universal: Response status: 200
azure.core.pipeline.policies._universal: Response headers:
azure.core.pipeline.policies._universal:     'Cache-Control': 'no-cache'
azure.core.pipeline.policies._universal:     'Pragma': 'no-cache'
azure.core.pipeline.policies._universal:     'Content-Type': 'application/json; charset=utf-8'
azure.core.pipeline.policies._universal:     'Content-Encoding': 'gzip'
azure.core.pipeline.policies._universal:     'Expires': '-1'
azure.core.pipeline.policies._universal:     'Vary': 'Accept-Encoding'
azure.core.pipeline.policies._universal:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
azure.core.pipeline.policies._universal:     'x-ms-request-id': '77d63cff-25e2-4541-a47c-aff1f144efd9'
azure.core.pipeline.policies._universal:     'x-ms-correlation-request-id': '77d63cff-25e2-4541-a47c-aff1f144efd9'
azure.core.pipeline.policies._universal:     'x-ms-routing-request-id': 'NORWAYEAST:20231230T165617Z:77d63cff-25e2-4541-a47c-aff1f144efd9'
azure.core.pipeline.policies._universal:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
azure.core.pipeline.policies._universal:     'X-Content-Type-Options': 'nosniff'
azure.core.pipeline.policies._universal:     'Date': 'Sat, 30 Dec 2023 16:56:16 GMT'
azure.core.pipeline.policies._universal:     'Content-Length': '292'
azure.core.pipeline.policies._universal: Response content:
azure.core.pipeline.policies._universal: {"id":"/subscriptions/eaaa3175-65a7-44e2-b998-ffcc28a78cf1/resourceGroups/merchbot-k8s-cluster","name":"merchbot-k8s-cluster","type":"Microsoft.Resources/resourceGroups","location":"swedencentral","properties":{"provisioningState":"Succeeded"}}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 659, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 715, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 693, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 330, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 786, in default_command_handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/acs/custom.py", line 2204, in aks_create
    client.create_or_update,
AttributeError: 'ManagedClustersOperations' object has no attribute 'create_or_update'

cli.azure.cli.core.azclierror: CLIInternalError: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: CLIInternalError: The command failed with an unexpected error. Here is the traceback:
cli.azure.cli.core.azclierror: 'ManagedClustersOperations' object has no attribute 'create_or_update'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 659, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 715, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 693, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 330, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 786, in default_command_handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/acs/custom.py", line 2204, in aks_create
    client.create_or_update,
AttributeError: 'ManagedClustersOperations' object has no attribute 'create_or_update'
cli.azure.cli.core.azclierror: 'ManagedClustersOperations' object has no attribute 'create_or_update'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 659, in execute
    raise ex
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 715, in _run_job
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 693, in _run_job
    result = cmd_copy(params)
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 330, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/azure/cli/core/__init__.py", line 786, in default_command_handler
    return op(**command_args)
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/acs/custom.py", line 2204, in aks_create
    client.create_or_update,
AttributeError: 'ManagedClustersOperations' object has no attribute 'create_or_update'
To open an issue, please run: 'az feedback'
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fe3a38d99d0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.981 seconds (init: 0.126, invoke: 0.854)
telemetry.save: Save telemetry record of length 6363 in cache
telemetry.check: Negative: The /home/leo/.azure/telemetry.txt was modified at 2023-12-30 17:49:53.291520, which in less than 600.000000 s

### Expected behavior

I would expect a cluster to be provisioned.

### Environment Summary

az --version
azure-cli                         2.18.0 *

core                              2.18.0 *
telemetry                          1.0.6

Python location '/usr/bin/python3'
Extensions directory '/home/leo/.azure/cliextensions'

Python (Linux) 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]

Legal docs and information: aka.ms/AzureCliLegal

You have 2 updates available. Consider updating your CLI installation with 'az upgrade'

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by mrdeveloperdude** [comment]
This is strange, I installed Azure CLI following this article: https://learn.microsoft.com/en-us/linux/packages#debian-based-linux-distributions

My install procedure is as follows:
```
	# Download the repo config package: 
	@echo "Distribution: $(shell lsb_release -is | tr '[:upper:]' '[:lower:]')"
	@echo "Version: $(shell lsb_release -rs | cut -d. -f1)"
	curl -fsSL -O "https://packages.microsoft.com/config/$(shell lsb_release -is | tr '[:upper:]' '[:lower:]')/$(shell lsb_release -rs | cut -d. -f1)/packages-microsoft-prod.deb"
	# Install the repo config package:
	sudo dpkg -i packages-microsoft-prod.deb
	# Delete the repo config package after installing:
	rm packages-microsoft-prod.deb
	# Update package index files:
	sudo apt-get update
	# To install the Microsoft product package you're after using this Linux repository (packages.microsoft.com): 
	sudo apt-get install -qy azure-cli

```

As you can clearly see I am using Microsoft sanctioned installation version. How is it possible that it is flagged as "not an official version?"

**Comment by FumingZhang** [comment]
Juding from the error message
> AttributeError: 'ManagedClustersOperations' object has no attribute 'create_or_update'

The azure-cli you are actually using is a very old version (likely 2.18.0 * from the output of az version). The latest version of azure-cli is 2.55.0. Maybe you have multiple versions of azure-cli installed. Please remove the old version (if any) and use the latest one.
