### ISSUE TITLE
cannot use az upgrade from 2.38

### ISSUE THREAD

**Issue by TheThrownGormal** [Azure/azure-cli#28134]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az upgrade

### Resource Provider

N/A

### Description of Feature or Work Requested

upgrade az cli to latest

### Minimum API Version Required

N/A

### Swagger PR link / SDK link

N/A

### Target Date

2024-01-04

### PM Contact

odysnatsio@gmail.com

### Engineer Contact

N/A

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
If you're referring to centos7, then it's by design.
> Azure CLI [2.38.1](https://review.learn.microsoft.com/en-us/cli/azure/release-notes-azure-cli#september-01-2023) (released on September 01, 2023) is the lastest version supported on RHEL 7 and Centos 7 and will continue to receive security fixes until the end of life of the operating systems. Microsoft isn't providing other updates or bug fixes for these distributions. 
    -----https://review.learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?branch=live&pivots=dnf

**Comment by TheThrownGormal** [comment]
So I can't have azure cli later than 2.38 on centos 7

**Comment by bebound** [comment]
Exactly
