### ISSUE TITLE
nodepool update not allowing empty string ("") to remove all taints

### ISSUE THREAD

**Issue by michaelbanzato** [Azure/azure-cli#28132]
### Describe the bug

While using local binary, we can set nodepool taints to "None" by running:
`az aks nodepool update --cluster-name MyCluster --resource-group MyRg --nodepool-name MyNodepool --node-taints ""`

But the azure-cli is not allowing it.
```
File "/home/banzato/.local/lib/python3.8/site-packages/azure/cli/command_modules/acs/_validators.py", line 307, in validate_taint
    raise ArgumentUsageError('Invalid node taint: %s' % taint)
azure.cli.core.azclierror.ArgumentUsageError: Invalid node taint: ""
```

If we define a `var = ""` it didn't go to the aks command and return an error:
argument --node-taints: expected one argument

But looks like the code here is prepared to it, but has some bug that 
```
    if taint == "":
        return
```
Like the function is not receiving the correct input.

I've test this kind of code locally and it works. Therefore I didn't identified the problem.
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/_validators.py#L303

### Related command

```
aks nodepool update --cluster-name {cluster_name} --resource-group rg-{cluster_name} --subscription {SUBSCRIPTION} --nodepool-name nodepool --node-taints ""
```

### Errors

```
File "/home/banzato/.local/lib/python3.8/site-packages/azure/cli/command_modules/acs/_validators.py", line 307, in validate_taint
    raise ArgumentUsageError('Invalid node taint: %s' % taint)
azure.cli.core.azclierror.ArgumentUsageError: Invalid node taint: ""
```

### Issue script & Debug output

```
import base64
from azure.cli.core import get_default_cli
import os, json
from subprocess import run, PIPE

def az_cli (args_str):
    args = args_str.split()
    cli = get_default_cli()
    cli.invoke(args)
    if cli.result.result:
        return cli.result.result
    elif cli.result.error:
        raise cli.result.error
    return True

ACTION="untaint"
empty = ""
#empty = '""'
#empty = " "
#empty='\"\"'
if ACTION == "untaint":
   taint_response = az_cli(f"aks nodepool update --cluster-name {cluster_name} --resource-group rg-{cluster_name} --subscription {SUBSCRIPTION} --nodepool-name nodepool --node-taints {empty}")
```
---
```
Invalid node taint: ""
Traceback (most recent call last):
  File ".terraform/test.py", line 93, in <module>
    rescale_aks()
  File ".terraform/test.py", line 80, in rescale_aks
    taint_response = az_cli(f"aks nodepool update --cluster-name {cluster_name} --resource-group rg-{cluster_name} --subscription {SUBSCRIPTION} --nodepool-name nodepool --node-taints {empty} --debug")
  File ".terraform/test.py", line 13, in az_cli
    raise cli.result.error
  File "/home/banzato/.local/lib/python3.8/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/banzato/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 651, in execute
    self._validation(expanded_arg)
  File "/home/banzato/.local/lib/python3.8/site-packages/knack/invocation.py", line 113, in _validation
    self._validate_arg_level(parsed_ns)
  File "/home/banzato/.local/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 859, in _validate_arg_level
    validator(**self._build_kwargs(validator, ns))
  File "/home/banzato/.local/lib/python3.8/site-packages/azure/cli/command_modules/acs/_validators.py", line 295, in validate_nodepool_taints
    validate_taint(taint)
  File "/home/banzato/.local/lib/python3.8/site-packages/azure/cli/command_modules/acs/_validators.py", line 307, in validate_taint
    raise ArgumentUsageError('Invalid node taint: %s' % taint)
azure.cli.core.azclierror.ArgumentUsageError: Invalid node taint: ""
```

### Expected behavior

nodepool taint == None

### Environment Summary

**azure-cli -- version**
```
azure-cli                         2.55.0

core                              2.55.0
telemetry                          1.1.0

Dependencies:
msal                              1.26.0
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3'
Extensions directory '/home/banzato/.azure/cliextensions'

Python (Linux) 3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
True
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by FumingZhang** [comment]
![image](https://github.com/Azure/azure-cli/assets/81607949/a8b03669-d3d3-42f6-902a-f6a4e567e74f)
somehow the shell you are using automatically escaped the input from `""` to `\"\"`

**Comment by michaelbanzato** [comment]
> ![image](https://private-user-images.githubusercontent.com/81607949/294879360-a8b03669-d3d3-42f6-902a-f6a4e567e74f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjA2ODIsIm5iZiI6MTcwNDcyMDM4MiwicGF0aCI6Ii84MTYwNzk0OS8yOTQ4NzkzNjAtYThiMDM2NjktZDNkMy00MmY2LTkwMmEtZjZhNGU1NjdlNzRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDEzMjYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiODI5NjBjYTA5YjJjMWUzMmQ2YTRhYzZjMWQzNWQxZTkzZmNmYjhkYzk1YWVlMDJjZjdkNzRkZjdiMDI3ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZqBFCUgW4GHHnXye7dJYjhJwnH3xfXBsyC7XX14RLss) somehow the shell you are using automatically escaped the input from `""` to `\"\"`

I don't think so, I've tried inside GCP Functions with python 3.8 as well. Same problem.
But maybe that is the split before calling the fuction.
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/_validators.py#L294

**Comment by mschumacher-syntellis** [comment]
I was seeing same behavior, windows 11, vscode 1.90.0

PS C:\Users\mschumacher> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Users\mschumacher> az version 
{
  "azure-cli": "2.61.0",
  "azure-cli-core": "2.61.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "azure-firewall": "0.14.5",
    "k8s-extension": "1.6.0",
    "vm-repair": "1.0.0b1"
  }
}




PS C:\Users\mschumacher> az aks nodepool update --resource-group test-rg --cluster-name test-cl --name wsch02 --node-taints ""
argument --node-taints: expected one argument

Examples from AI knowledge base:
az aks nodepool update --enable-cluster-autoscaler --min-count 1 --max-count 5 --resource-group MyResourceGroup --name nodepool1 --cluster-name MyManagedCluster
Enable cluster-autoscaler within node count range [1,5]

az aks nodepool update --update-cluster-autoscaler --min-count 1 --max-count 10 --resource-group MyResourceGroup --name nodepool1 --cluster-name MyManagedCluster
Update min-count or max-count for cluster autoscaler.

https://docs.microsoft.com/en-US/cli/azure/aks/nodepool#az_aks_nodepool_update
Read more about the command in reference docs


PS C:\Users\mschumacher> az aks nodepool update --resource-group test-rg --cluster-name test-cl --name wsch02 --node-taints \"\"
Invalid node taint: \\



But able to get it to work using 

**PS C:\Users\mschumacher>az aks nodepool update --resource-group tests-rg --cluster-name test-cl --name wsch02 --node-taints """"**

**Comment by johnknutsonhc** [comment]
I understand that this is a shell issue, not a CLI issue, but I think it would be appropriate to add some sort of note to the Azure CLI documentation: [Use node taints in an Azure Kubernetes Service (AKS) cluster](https://learn.microsoft.com/en-us/azure/aks/use-node-taints#remove-all-node-taints)
