### ISSUE TITLE
Failed to run az eventhubs xxx commands.

### ISSUE THREAD

**Issue by zhangyunbo1994** [Azure/azure-cli#28144]
### Describe the bug

Failed to run az eventhubs xxx commands. 

![image](https://github.com/Azure/azure-cli/assets/44389598/43ab7ef1-0214-46ed-a772-aa3a806f047e)

### Related command

az eventhubs namespace list
az eventhubs namespace network-rule-set list -g xxxx --namespace-name xxxx

### Errors

(NoRegisteredProviderFound) No registered resource provider found for location 'chinanorth3' and API version '2023-01-01-preview' for type 'namespaces/networkrulesets'. The supported api-versions are '2017-04-01, 2018-01-01-preview, 2021-01-01-preview, 2021-06-01-preview, 2021-11-01, 2022-01-01-preview, 2022-10-01-preview'. The supported locations are 'chinaeast, chinaeast2, chinanorth, chinanorth2, chinanorth3, '.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'chinanorth3' and API version '2023-01-01-preview' for type 'namespaces/networkrulesets'. The supported api-versions are '2017-04-01, 2018-01-01-preview, 2021-01-01-preview, 2021-06-01-preview, 2021-11-01, 2022-01-01-preview, 2022-10-01-preview'. The supported locations are 'chinaeast, chinaeast2, chinanorth, chinanorth2, chinanorth3, '.

### Issue script & Debug output

cli.knack.cli: Command arguments: ['eventhubs', 'namespace', 'network-rule-set', 'list', '-g', 'zyb-event-hub-case-2210180040001205', '--namespace-name', 'zyb-test-will-delete', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x01EC0668>, <function OutputProducer.on_global_arguments at 0x021E8758>, <function CLIQuery.on_global_arguments at 0x0220B528>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'eventhubs': ['azure.cli.command_modules.eventhubs']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: eventhubs                 0.313        16        34
cli.azure.cli.core: Total (1)                 0.313        16        34
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 16 groups, 34 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : eventhubs namespace network-rule-set list
cli.azure.cli.core: Command table: eventhubs namespace network-rule-set list
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x042DBD48>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\yunbozhang\.azure\commands\2024-01-08.13-58-49.eventhubs_namespace_network-rule-set_list.13892.log'.
az_command_data_logger: command args: eventhubs namespace network-rule-set list -g {} --namespace-name {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x042EF988>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x04307E38>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x04333118>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x021E87A8>, <function CLIQuery.handle_query_parameter at 0x0220B578>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x043330C8>]
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\yunbozhang\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\yunbozhang\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.chinacloudapi.cn/954ddad8-66d7-47a8-8f9f-1316152d9587/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.chinacloudapi.cn/954ddad8-66d7-47a8-8f9f-1316152d9587/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.partner.microsoftonline.cn/954ddad8-66d7-47a8-8f9f-1316152d9587/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://microsoftgraph.chinacloudapi.cn/oidc/userinfo', 'authorization_endpoint': 'https://login.chinacloudapi.cn/954ddad8-66d7-47a8-8f9f-1316152d9587/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.chinacloudapi.cn/954ddad8-66d7-47a8-8f9f-1316152d9587/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.chinacloudapi.cn/954ddad8-66d7-47a8-8f9f-1316152d9587/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.chinacloudapi.cn/954ddad8-66d7-47a8-8f9f-1316152d9587/kerberos', 'tenant_region_scope': 'AS', 'cloud_instance_name': 'partner.microsoftonline.cn', 'cloud_graph_host_name': 'graph.chinacloudapi.cn', 'msgraph_host': 'microsoftgraph.chinacloudapi.cn', 'rbac_url': 'https://pas.chinacloudapi.cn'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.chinacloudapi.cn//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.chinacloudapi.cn//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: c1c3f707-a847-44ec-bae1-b52473064e39
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.chinacloudapi.cn/subscriptions/d453271c-5cbc-40be-aeab-ab19f5cc0b6c/resourceGroups/zyb-event-hub-case-2210180040001205/providers/Microsoft.EventHub/namespaces/zyb-test-will-delete/networkRuleSets?api-version=2023-01-01-preview'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'fe0efb39-adea-11ee-92f3-701ab806c132'
cli.azure.cli.core.sdk.policies:     'CommandName': 'eventhubs namespace network-rule-set list'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g --namespace-name --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.55.0 (MSI) (AAZ) azsdk-python-core/1.26.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.chinacloudapi.cn:443
urllib3.connectionpool: https://management.chinacloudapi.cn:443 "GET /subscriptions/d453271c-5cbc-40be-aeab-ab19f5cc0b6c/resourceGroups/zyb-event-hub-case-2210180040001205/providers/Microsoft.EventHub/namespaces/zyb-test-will-delete/networkRuleSets?api-version=2023-01-01-preview HTTP/1.1" 400 449
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'gateway'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'a1661b37-b7a7-4cfc-a2b6-08a8064c0b08'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'a1661b37-b7a7-4cfc-a2b6-08a8064c0b08'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'CHINAEAST2:20240108T055849Z:a1661b37-b7a7-4cfc-a2b6-08a8064c0b08'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 08 Jan 2024 05:58:48 GMT'
cli.azure.cli.core.sdk.policies:     'Content-Length': '449'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'chinanorth3' and API version '2023-01-01-preview' for type 'namespaces/networkrulesets'. The supported api-versions are '2017-04-01, 2018-01-01-preview, 2021-01-01-preview, 2021-06-01-preview, 2021-11-01, 2022-01-01-preview, 2022-10-01-preview'. The supported locations are 'chinaeast, chinaeast2, chinanorth, chinanorth2, chinanorth3, '."}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 710, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_paging.py", line 87, in __next__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_paging.py", line 43, in __next__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_command.py", line 250, in executor_wrapper
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/eventhubs/aaz/latest/eventhubs/namespace/network_rule_set/_list.py", line 61, in _execute_operations
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/eventhubs/aaz/latest/eventhubs/namespace/network_rule_set/_list.py", line 86, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/aaz/_operation.py", line 332, in on_error
azure.core.exceptions.HttpResponseError: (NoRegisteredProviderFound) No registered resource provider found for location 'chinanorth3' and API version '2023-01-01-preview' for type 'namespaces/networkrulesets'. The supported api-versions are '2017-04-01, 2018-01-01-preview, 2021-01-01-preview, 2021-06-01-preview, 2021-11-01, 2022-01-01-preview, 2022-10-01-preview'. The supported locations are 'chinaeast, chinaeast2, chinanorth, chinanorth2, chinanorth3, '.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'chinanorth3' and API version '2023-01-01-preview' for type 'namespaces/networkrulesets'. The supported api-versions are '2017-04-01, 2018-01-01-preview, 2021-01-01-preview, 2021-06-01-preview, 2021-11-01, 2022-01-01-preview, 2022-10-01-preview'. The supported locations are 'chinaeast, chinaeast2, chinanorth, chinanorth2, chinanorth3, '.

cli.azure.cli.core.azclierror: (NoRegisteredProviderFound) No registered resource provider found for location 'chinanorth3' and API version '2023-01-01-preview' for type 'namespaces/networkrulesets'. The supported api-versions are '2017-04-01, 2018-01-01-preview, 2021-01-01-preview, 2021-06-01-preview, 2021-11-01, 2022-01-01-preview, 2022-10-01-preview'. The supported locations are 'chinaeast, chinaeast2, chinanorth, chinanorth2, chinanorth3, '.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'chinanorth3' and API version '2023-01-01-preview' for type 'namespaces/networkrulesets'. The supported api-versions are '2017-04-01, 2018-01-01-preview, 2021-01-01-preview, 2021-06-01-preview, 2021-11-01, 2022-01-01-preview, 2022-10-01-preview'. The supported locations are 'chinaeast, chinaeast2, chinanorth, chinanorth2, chinanorth3, '.
az_command_data_logger: (NoRegisteredProviderFound) No registered resource provider found for location 'chinanorth3' and API version '2023-01-01-preview' for type 'namespaces/networkrulesets'. The supported api-versions are '2017-04-01, 2018-01-01-preview, 2021-01-01-preview, 2021-06-01-preview, 2021-11-01, 2022-01-01-preview, 2022-10-01-preview'. The supported locations are 'chinaeast, chinaeast2, chinanorth, chinanorth2, chinanorth3, '.
Code: NoRegisteredProviderFound
Message: No registered resource provider found for location 'chinanorth3' and API version '2023-01-01-preview' for type 'namespaces/networkrulesets'. The supported api-versions are '2017-04-01, 2018-01-01-preview, 2021-01-01-preview, 2021-06-01-preview, 2021-11-01, 2022-01-01-preview, 2022-10-01-preview'. The supported locations are 'chinaeast, chinaeast2, chinanorth, chinanorth2, chinanorth3, '.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x042DBE88>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 2.349 seconds (init: 0.637, invoke: 1.712)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 4309 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\yunbozhang\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

No error outpot

### Environment Summary

PS C:\Users\yunbozhang> az --version
azure-cli                         2.55.0

core                              2.55.0
telemetry                          1.1.0

Extensions:
stream-analytics                   0.1.2

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\yunbozhang\.azure\cliextensions'

Python (Windows) 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:21:31) [MSC v.1936 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
