### ISSUE TITLE
Service Connectors creation using CLI for Function Apps

### ISSUE THREAD

**Issue by shreyabatra4** [Azure/azure-cli#28140]
For Queue, ([az functionapp connection create | Microsoft Learn](https://learn.microsoft.com/en-us/cli/azure/functionapp/connection/create?view=azure-cli-latest#az-functionapp-connection-create-storage-queue) we can specify optional parameters such as Service Principal, System Identity, and User Identity.
 
A request came in to do the same for the Table storage service, ([az functionapp connection create | Microsoft Learn](https://learn.microsoft.com/en-us/cli/azure/functionapp/connection/create?view=azure-cli-latest#az-functionapp-connection-create-storage-table) according to this documentation these parameters are not present yet.

**Comment by houk-ms** [comment]
@shreyabatra4 thank you for the feedback!

I will mark this as a feature request to support Microsoft Entra ID as auth types for table storage. You may expect this can be supported on next CLI release and we will give updates here when there are any progresses. 

As a work around, you may explore our experience on Portal ([quickstart](https://learn.microsoft.com/en-us/azure/service-connector/quickstart-portal-functions-connection?tabs=SMI)), where table storage with Microsoft Entra ID as auth types are supported.

**Comment by houk-ms** [comment]
PR created.
https://github.com/Azure/azure-cli/pull/28162
