### ISSUE TITLE
Dedicated Host Redeploy

### ISSUE THREAD

**Issue by thomascoats** [Azure/azure-cli#28161]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az vm host redeploy

### Resource Provider

Microsoft.Compute

### Description of Feature or Work Requested

We are looking to add CLI support for the new dedicated host redeploy operation in preparation for public preview.

### Minimum API Version Required

2023-09-01

### Swagger PR link / SDK link

Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/26427
SDK Release: https://github.com/Azure/azure-sdk-for-python/releases/tag/azure-mgmt-compute_30.4.0

### Request Example

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-09-01/examples/dedicatedHostExamples/DedicatedHost_Redeploy.json

### Target Date

2023-02-05

### PM Contact

vakavuru

### Engineer Contact

thomascoats

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
@thomascoats Thank you for submitting this feature request. We will plan to develop and release it in the next sprint. The release date is **03-05**, do you think it is acceptable?

**Comment by thomascoats** [comment]
@zhoxing-ms We're targeting a February release, is there any way we could get it released in February?

**Comment by zhoxing-ms** [comment]
@thomascoats We can provide you with a private package from edge build at the end of February and officially release it in **03-05**. Do you think it's acceptable?

**Comment by yanzhudd** [comment]
Hi @thomascoats,
when we develop this feature, an error is reported. It seems the feature need to be registered manually. Could you please help to register our subId for this feature (subId: 0b1f6471-1bf0-4dda-aec3-cb9272f09590)? Thanks!
![image](https://github.com/Azure/azure-cli/assets/105691024/870d4d4c-c0fd-4b29-9ac4-f9958c26a3ef)

**Comment by yanzhudd** [comment]
Hi @thomascoats,
Could you please help look into this error? I thought maybe I lost some necessary steps before running "az vm host redeploy":
![image](https://github.com/Azure/azure-cli/assets/105691024/2c2bc9cf-e42c-4160-9750-33a206016131)
My reproduce steps are:
1. az vm host group create
2. az vm host create
3. az vm host redeploy

Thanks in advance.

**Comment by thomascoats** [comment]
Hi Yan,

Could you provide me with the subscription ID, resource group name, and host name you used?

Thanks,
Jacob

**Comment by yanzhudd** [comment]
Hi @thomascoats,
The resources are:
- Subsription ID: 0b1f6471-1bf0-4dda-aec3-cb9272f09590
- Resource Group: zytest
- Host Group Name: zy-host-group
- Host Name: zy-host

Thanks!

**Comment by thomascoats** [comment]
Hi Yan,

The issue is that ADH redeploy isn't enabled in WestUS. Redeploy is currently enabled in EastUS, NorthEurope, and KoreaCentral.

Thanks,
Jacob

**Comment by yanzhudd** [comment]
Hi @thomascoats 
It seems that our subID is not registered for this feature
![image](https://github.com/Azure/azure-cli/assets/105691024/8e29cc60-6da2-464d-8ba6-22754c68f89f)

Could you please help to register our subID? Thanks!
0b1f6471-1bf0-4dda-aec3-cb9272f09590

**Comment by thomascoats** [comment]
Hi, sorry I missed this. I'll have your sub whitelisted by tomorrow.

**Comment by thomascoats** [comment]
Hi @yanzhudd your subscription is whitelisted
