### ISSUE TITLE
Found multiple accounts with the same username

### ISSUE THREAD

**Issue by NAJ8ry** [Azure/azure-cli#28166]
### Describe the bug

When I log in I have been asked through the web site has the business created the user or is it private. Over the years I have had both. Now when I try to log in with az login 
I get the following error: 
Found multiple accounts with the same username 'nicholas@remeody.com': [{'home_account_id': '00000000-0000-0000-xxxx-xxxxxxxxxxxx.xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', 'environment': 'login.microsoftonline.com', 'username': 'nicholas@remeody.com', 'authority_type': 'MSSTS', 'local_account_id': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'realm': 'organizations'}, {'home_account_id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx.xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', 'environment': 'login.microsoftonline.com', 'username': 'nicholas@remeody.com', 'authority_type': 'MSSTS', 'local_account_id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', 'realm': 'organizations'}]

### Related command

az login --scope https://management.core.windows.net//.default

### Errors

Found multiple accounts with the same username 'nicholas@remeody.com': [{'home_account_id': '00000000-0000-0000-xxxx-xxxxxxxxxxxx.xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', 'environment': 'login.microsoftonline.com', 'username': 'nicholas@remeody.com', 'authority_type': 'MSSTS', 'local_account_id': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'realm': 'organizations'}, {'home_account_id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx.xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', 'environment': 'login.microsoftonline.com', 'username': 'nicholas@remeody.com', 'authority_type': 'MSSTS', 'local_account_id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', 'realm': 'organizations'}]

### Issue script & Debug output

No script just command prompt

### Expected behavior

Should be able to simply login.

### Environment Summary

azure-cli                         2.44.1 *

core                              2.44.1 *
telemetry                          1.0.8 *

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location '/opt/az/bin/python3'
Extensions directory '/home/nicholas/.azure/cliextensions'

Python (Linux) 3.10.8 (main, Jan 10 2023, 15:48:33) [GCC 9.4.0]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by NAJ8ry** [comment]
I've updated the version of az to no effect.

**Comment by NAJ8ry** [comment]
> Hi @NAJ8ry,
> 
> 2.44.1 is not the latest Azure CLI(2.56.0).
> 
> If you haven't already attempted to do so, please upgrade to the latest Azure CLI version by following https://learn.microsoft.com/en-us/cli/azure/update-azure-cli.

I am now running the following:
azure-cli                         2.56.0

core                              2.56.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/home/nicholas/.azure/cliextensions'

Python (Linux) 3.11.5 (main, Jan  8 2024, 09:08:13) [GCC 11.4.0]

**Comment by NAJ8ry** [comment]
The id's are different for both:
[
    {
        "home_account_id": "00000000-0000-0000-f569-",
        "environment": "login.microsoftonline.com",
        "username": "nicholas@remeody.com",
        "authority_type": "MSSTS",
        "local_account_id": "6Io6J8DoQ3-",
        "realm": "organizations"
    },
    {
        "home_account_id": "cd8ab407-dc19-4bb0-af8c-",
        "environment": "login.microsoftonline.com",
        "username": "nicholas@remeody.com",
        "authority_type": "MSSTS",
        "local_account_id": "cd8ab407-",
        "realm": "organizations"
    }
]

**Comment by NAJ8ry** [comment]
I don't know if you have changed anything but this morning I logged into the personal account and setup a new alias (I was trying to change the personal one to use a separate email address but it was not obvious - if its possible - and all I could do was setup an alias.) I then "Switched Directory" to the private one. 
I'm writing this simply for thoroughness in case it helps someone. 
I then signed out. Then logged into the business account, switched directory to the business one I needed the az login for.
At which point from the CLI I used az account clear followed by the az login and it worked!

**Comment by jiasli** [comment]
We use https://github.com/Azure/azure-cli/issues/20168 to track this issue. 

> At which point from the CLI I used az account clear followed by the az login and it worked!

This is the same solution given by https://github.com/Azure/azure-cli/issues/20168#issuecomment-963747032.
