### ISSUE TITLE
Use ANSI color codes for intercept survey style

### ISSUE THREAD

**Issue by hyoshis** [Azure/azure-cli#28179]
![image](https://github.com/Azure/azure-cli/assets/13126058/f9d64aa5-77ce-43a6-ab8b-bebceb8c2c07)

The intercept survey message uses hardcoded blue color. Originally the intention was to use the same blue color as Azure brand, however, since the hardcoded colors don't get adjusted according to user's color customization, it should be changed to use ANSI color variables.

Can you change it to use ANSI color variables for the **white** foreground and **blue** background?

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by hyoshis** [comment]
@dcaro FYI

**Comment by hyoshis** [comment]
Actually, I checked how the blue and white combination shows up in Azure CLI on both CloudShell and iTerm 2. It doesn't provide enough contrast as you can see:
![image](https://github.com/Azure/azure-cli/assets/13126058/d7779cf0-5c00-47e5-ac0b-885fa1980b02)
![image](https://github.com/Azure/azure-cli/assets/13126058/5492335a-5288-49a4-8e9e-80410f963773)

@dcaro 
Should we consider using black foreground + blue background color?

**Comment by evelyn-ys** [comment]
FYI, CLI intercept survey does use ANSI color:
https://github.com/Azure/azure-cli/blob/6729cef5014d71057abad932774ad1c13f683ea8/src/azure-cli-core/azure/cli/core/intercept_survey.py#L25

**Comment by hyoshis** [comment]
Ok. Let's keep the current implementation for the intercept survey.
