### ISSUE TITLE
unable to create ARO cluster due to ValidationError "permission is disabled" despite user is assigned Owner role on ARO Vnet

### ISSUE THREAD

**Issue by boliu83** [Azure/azure-cli#28197]
### Describe the bug

Unable to create ARO cluster using Az cli version 2.56. Failed with ValidationError "`Microsoft.Network/virtualNetworks/write permission is disabled`" on the ARO Vnet, despite account used is assigned to **Owner** role on the Vnet resource. 

Besides Owner role, user account is also assigned to a custom role on the Vnet resource. This custom role has "Microsoft.Network/virtualNetworks/write" permission on its NotActions list. 

### Related command

az aro create 

### Errors

![image](https://github.com/Azure/azure-cli/assets/7767774/64b32b83-005b-44d5-a327-9637af535f6c)

### Issue script & Debug output

n/a

### Expected behavior

validation should pass if user account is assigned to Owner role on the resource

### Environment Summary

{
  "azure-cli": "2.56.0",
  "azure-cli-core": "2.56.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "aks-preview": "0.5.171",
    "azure-firewall": "1.0.0",
    "connectedk8s": "1.4.0",
    "costmanagement": "0.2.1",
    "k8s-configuration": "1.7.0",
    "k8s-extension": "1.4.2",
    "maintenance": "1.4.0"
  }
}

### Additional context

the error message is actually from my client's environment. I am unable to test it in my lab environment due to subscription restriction.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by boliu83** [comment]
I found the issue is caused by a validation logic added since 2.52 which flags a permission is disabled if the permission is found on any role assigned to the user on the resource. For example, if my account is assigned to Owner role and a custom role that has "Microsoft.Network/virtualNetwork/write" permission on its NotActions list on the ARO Vnet, it will fail the validation when trying to create an ARO cluster.  

https://github.com/Azure/azure-cli/blob/azure-cli-2.52.0/src/azure-cli/azure/cli/command_modules/aro/_dynamic_validators.py#L31
```python
def can_do_action(perms, action):
    for perm in perms:
        for not_action in perm.not_actions:
            match = re.escape(not_action)
            match = re.match("(?i)^" + match.replace(r"\*", ".*") + "$", action)
            if match:
                return f"{action} permission is disabled"
        for perm_action in perm.actions:
            match = re.escape(perm_action)
            match = re.match("(?i)^" + match.replace(r"\*", ".*") + "$", action)
            if match:
                return None

    return f"{action} permission is missing"
```

In reality user can be assigned to multiple roles on a resource. the user permission should be **union** of permissions of all assigned roles.

**Comment by boliu83** [comment]
@Devaraj004   Azure cli takes the account info of current Azure CLI login session for pre-flight validation.   The service principal you used in the "az aro create" command is for the ARO control plane to interaction with Azure ARM API.  

so basically there are two identities involved in ARO 
1. Account used by Azure cli (aka your user account) is used to create ARO cluster.  this account is only used during cluster creation.  
2. after the cluster is created,  the service principal you provided is used by the ARO control-plane for the on-going interaction with Azure (create Azure fileshare, disk for PV, update Azure load balancer  etc)

**Comment by tsatam** [comment]
We're taking a look at this issue and are working on a fix.
