### ISSUE TITLE
Please port to Python3.12

### ISSUE THREAD

**Issue by tillea** [Azure/azure-cli#28194]
### Describe the bug

The test suite does not pass when using Python3.12 as it is reported in a [Debian bug report](https://bugs.debian.org/1057393).  It results in

    E       AttributeError: 'TestApplication' object has no attribute 'assertNotEquals'. Did you mean: 'assertNotEqual'?
    tests_core/test_application.py:56: AttributeError
    E       AttributeError: 'TestApplication' object has no attribute 'assertNotEquals'. Did you mean: 'assertNotEqual'?
    tests_core/test_application.py:35: AttributeError
    E           AttributeError: 'TestCommandRegistration' object has no attribute 'assertDictContainsSubset'
    tests_core/test_command_registration.py:96: AttributeError
    E           AttributeError: 'TestCommandRegistration' object has no attribute 'assertDictContainsSubset'
    tests_core/test_command_registration.py:564: AttributeError

While fixing the `assertNotEquals` can be easily fixed with this [patch](https://salsa.debian.org/python-team/packages/azure-cli/-/blob/debian/sid/debian/patches/python3.12.patch?ref_type=heads) `assertDictContainsSubset` is not supported any more as you can read in the [Python3.12 documentation](https://docs.python.org/3/whatsnew/3.12.html#unittest).
(BTW, the patch is against the Debian packaged version 2.50.0 so not the latest release but it should be pretty easy to adapt sind the replacement is simple.)

### Related command

Simply run the test suite under Python3.12.

### Errors

    E       AttributeError: 'TestApplication' object has no attribute 'assertNotEquals'. Did you mean: 'assertNotEqual'?
    tests_core/test_application.py:56: AttributeError
    E       AttributeError: 'TestApplication' object has no attribute 'assertNotEquals'. Did you mean: 'assertNotEqual'?
    tests_core/test_application.py:35: AttributeError
    E           AttributeError: 'TestCommandRegistration' object has no attribute 'assertDictContainsSubset'
    tests_core/test_command_registration.py:96: AttributeError
    E           AttributeError: 'TestCommandRegistration' object has no attribute 'assertDictContainsSubset'
    tests_core/test_command_registration.py:564: AttributeError

### Issue script & Debug output

See above

### Expected behavior

The unittest should be passed when using Python3.12.

### Environment Summary

azure-cli 2.50.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by tillea** [comment]
> Hi @tillea,
> 
> 2.50.0 is not the latest Azure CLI(2.56.0).
> 
> If you haven't already attempted to do so, please upgrade to the latest Azure CLI version by following https://learn.microsoft.com/en-us/cli/azure/update-azure-cli.

I'm perfectly aware that this is not the latest version.  However, I've seeked for the string `assertNotEquals` inside the Github web interface and found the according hits so I expect the problem to persists even in the latest release.

Kind regards, Andreas.

**Comment by bebound** [comment]
3.12 is not supported yet.
I've added this item in https://github.com/Azure/azure-cli/issues/27673
