### ISSUE TITLE
How to disable Older Versions of Secrets

### ISSUE THREAD

**Issue by clumsyhands** [Azure/azure-cli#28196]
### Describe the bug

I know this can be achieved on the Azure Portal and the Powershell Az module, but I can not find a way to achieve this using the Az CLI?

I can run "list-versions" but on the return, there is nothing to differentiate what is "current" and what is "older". 

### Related command

az keyvault secret list-versions

### Errors

n/a

### Issue script & Debug output

n/a

### Expected behavior

On running "az keyvault secret list-versions" it should return what is "Current" and what is "Older"

### Environment Summary

PS /home/aal> az --version                                                                                                              
azure-cli                         2.55.0 *

core                              2.55.0 *
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
ml                                2.22.0
ssh                                2.0.2

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.9'
Extensions directory '/home/aal/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.14 (main, Oct 12 2023, 19:48:32) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

You have 2 update(s) available. They will be updated with the next build of Cloud Shell.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by evelyn-ys** [comment]
Hi @clumsyhands, you can find the creation time and update time for each version and figure out the latest version accordingly

**Comment by clumsyhands** [comment]
Thanks @evelyn-ys
