### ISSUE TITLE
curl missing in docker images after mcr.microsoft.com/azure-cli:2.53.x

### ISSUE THREAD

**Issue by mknj** [Azure/azure-cli#28193]
### Describe the bug

We use curl to trigger pipelines and this is not working anymore since mcr.microsoft.com/azure-cli:2.54.0.

Please provide a docker image including curl

### Related command

curl

### Errors

bda26e5ed2e1:/# curl
bash: curl: command not found

### Issue script & Debug output

curl

### Expected behavior

3b70cdb23479:/# curl
curl: try 'curl --help' or 'curl --manual' for more information

### Environment Summary

1f0e01096282:/# az --version
azure-cli                         2.56.0

core                              2.56.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/usr/local/bin/python'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.11.7 (main, Dec  9 2023, 01:24:05) [GCC 13.2.1 20231014]

Legal docs and information: aka.ms/AzureCliLegal

Unable to check if your CLI is up-to-date. Check your internet connection.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by mknj** [comment]
same as #27844, but that one is closed although the problem is still present.

**Comment by bebound** [comment]
This was introduced in https://github.com/Azure/azure-cli/pull/27567. No plan to revert it.
