### ISSUE TITLE
Cannot create Azure Container Apps for which the cpu and memory allocation is a multiple of 0.1

### ISSUE THREAD

**Issue by pengxo** [Azure/azure-cli#28204]
### Describe the bug

The azure container apps is described with Bicep template and deployed through Azure CLI. The aca environment is created with dedicated workload profiles. When the resource allocation for cpu and memory is multiple of 0.1 such as 0.1, the deployment will fail. The cpu needs to be a multiple of 0.25 to make the deployment successful.

### Related command

`az deployment group create -g my-rg -n my-aca-app --template-file my-aca-app.bicep --parameters cpu=0.1 --parameters memory=0.7`

### Errors

`azure.cli.core.azclierror.DeploymentError: {"code": "InvalidTemplate", "message": "Deployment template validation failed: 'The provided value for the template parameter 'cpu' is not valid. The value '0.1' is not part of the allowed value(s): '0.25,0.5,0.75,1.0,1.25,1.5,1.75,2.0'.'.", "additionalInfo": [{"type": "TemplateViolation", "info": {"lineNumber": 77, "linePosition": 24, "path": "properties.template.parameters.cpu.allowedValues"}}]}`

### Issue script & Debug output

`azure.cli.core.azclierror.DeploymentError: {"code": "InvalidTemplate", "message": "Deployment template validation failed: 'The provided value for the template parameter 'cpu' is not valid. The value '0.1' is not part of the allowed value(s): '0.25,0.5,0.75,1.0,1.25,1.5,1.75,2.0'.'.", "additionalInfo": [{"type": "TemplateViolation", "info": {"lineNumber": 77, "linePosition": 24, "path": "properties.template.parameters.cpu.allowedValues"}}]}`

### Expected behavior

The deployment should be successful with the resource allocation for 0.1 of cpu and 0.7 of memory for dedicated workload profiles environment. I confirmed this by creating the container apps/revisions through Azure Portal with the same resource allocation and the deployment was successful.   So I assume it should also work through Azure CLI.  The limitation of 0.25 should only apply to the consumption plan.

### Environment Summary

Azure CLI: 2.54.0;
Bicep: 0.24.24;

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by pengxo** [comment]
This is related to the constraint enforced on the cpu and memory in bicep template. Therefore this issue can be closed.
