### ISSUE TITLE
Registering or Unregistering provider Microsoft.OperationalInsights very long

### ISSUE THREAD

**Issue by mapperCoderZ** [Azure/azure-cli#28203]
### Describe the bug

Trying to register "Microsoft.OperationalInsights" for my subscription via the portal but it gets stuck in registering and eventually gives this kind of message "Unregister' operation check timed out on Resource Provider 'microsoft.operationalinsights', please refresh resource providers list to check for registration status".

### Related command

Portal and `az provider register --namespace  Microsoft.OperationalInsights --verbose --wait`

### Errors

no error, but very slow (hours? days?)

### Issue script & Debug output

az provider list --query "[?registrationState=='Registering']" -o table
Namespace                      RegistrationState    RegistrationPolicy
-----------------------------  -------------------  --------------------
Microsoft.OperationalInsights  Registering          RegistrationRequired

### Expected behavior

Provider should be registered in the subscription

### Environment Summary

azure-cli                         2.55.0 *

core                              2.55.0 *
telemetry                          1.1.0

Extensions:
containerapp                      0.3.46

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

### Additional context

Related to 26801 ?

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by sassai** [comment]
Same issue here. Status is in state 'registering' for some hours now.

**Comment by mapperCoderZ** [comment]
Thank you for keeping an eye on it.

I've updated az. The problem is the same in the portal.

This is the result after az update:

```
az --version
azure-cli                         2.56.0

core                              2.56.0
telemetry                          1.1.0

Extensions:
containerapp                      0.3.46

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2
```
```
az provider register --namespace  Microsoft.OperationalInsights --verbose --wait
#never finish
```

**Comment by gadeweever** [comment]
Same issue here. Tried re-registering in the portal and it has been stuck.

**Comment by Passie1982** [comment]
Contacted Microsoft support on this issue. They were aware that there was an issue with registering the Microsoft.OperationalInsights resource provider. I tested it wit a existing subscription and a new subscription. Both subscriptions have now the resource provider Microsoft.OperationalInsights registered.

**Comment by mapperCoderZ** [comment]
thank you problem disappeared.
