### ISSUE TITLE
Changing the Default Rule Set to DRS2.1 in Firewall Policy

### ISSUE THREAD

**Issue by Shawnli222** [Azure/azure-cli#28210]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

No new command, just changing a field in CLI

### Resource Provider

Network (NRP)

### Description of Feature or Work Requested

In az network application-gateway waf-policy create
For optional field below, change the default value to the following:
type: Microsoft_DefaultRuleSet
version: 2.1

Changing the Default Rule Set to DRS2.1 from CRS3.0 in PSApplicationGatewayFirewallPolicyManagedRuleSet, there are 2 places needs change, example in below
example in Powershell: https://github.com/Azure/azure-powershell/pull/23760

### Minimum API Version Required

2022-11-01

### Swagger PR link / SDK link

no swagger needed

### Request Example

NA

### Target Date

2024-02-01

### PM Contact

luke.nowak

### Engineer Contact

lishawn

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
@Shawnli222 at least you should share which command and which parameter in Azure CLI will be affected

**Comment by Shawnli222** [comment]
@necusjz updated the info, pls let me know it is good enough
