### ISSUE TITLE
az containerapp job update overwrites all scale rules instead of updating one

### ISSUE THREAD

**Issue by acidbubbles** [Azure/azure-cli#28226]
### Describe the bug

Run a command like this one:

```bash
az containerapp job update --name $NAME --resource-group $RG --scale-rule-name $SR_NAME --scale-rule-type "azure-queue" --scale-rule-metadata "accountName=$ACCOUNT_NAME" "queueName=$QUEUE_NAME" "queueLength=1" --scale-rule-auth "connection=connection-string-secret"
```

It will effectively create the desired scale rule. However, it will also delete _all other existing scale rules_.

I want to keep two scale rules.

### Related command

`az containerapp job update --name $NAME --resource-group $RG --scale-rule-name $SR_NAME --scale-rule-type "azure-queue" --scale-rule-metadata "accountName=$ACCOUNT_NAME" "queueName=$QUEUE_NAME" "queueLength=1" --scale-rule-auth "connection=connection-string-secret"`

### Errors

Other scale rules deleted

### Issue script & Debug output

N/A

### Expected behavior

The scale rule name I set is overwritten, other scale rules are not touched.

### Environment Summary

azure-cli                         2.56.0

core                              2.56.0
telemetry                          1.1.0

Extensions:
containerapp                      0.3.46

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\USERNAME\.azure\cliextensions'

Python (Windows) 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:21:31) [MSC v.1936 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

### Additional context

My objective is two spawn my job if any of the queues have messages to process.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by Greedygre** [comment]
Hi @anandanthony 

Can you please have a look for this issue? Thanks.

**Comment by Greedygre** [comment]
Hi @acidbubbles 

Yes, currently with `az containerapp job update --name $NAME --resource-group $RG --scale-rule-name $SR_NAME --scale-rule-type "azure-queue" --scale-rule-metadata ` it will delete other scale rules.

There is a workaround:
use `az containerapp job update --yaml` to input all existing scale rules and new added scale rules.
You can use command
`az containerapp show --name $NAME --resource-group $RG -o yaml` to get the existing setting.

**Comment by acidbubbles** [comment]
Thank you, that sounds like a reasonable workaround, I appreciate the info! Since there is no UI in the Azure Portal for the azure queue rules metadata yet, this behavior can be quite confusing and hard to spot.
