### ISSUE TITLE
when installing on windows

### ISSUE THREAD

**Issue by Vanitharani** [Azure/azure-cli#2823]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

**OS Version:** What OS and version are you using?  
Answer here:

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

---

### Description

when I am trying to install az iot -h
C:\Users\hp>az iot -h
Error loading command module 'redis'
Error loading command module 'acs'
Error loading command module 'appservice'
Error loading command module 'batch'
Error loading command module 'iot'
Error loading command module 'keyvault'
Error loading command module 'network'
Error loading command module 'resource'
Error loading command module 'role'
Error loading command module 'sql'
Error loading command module 'storage'
Error loading command module 'vm'
Install the 'iot' module with 'az component update --add iot'
az: error: argument _command_package: invalid choice: 'iot' (choose from 'feedback', 'monitor', 'account', 'acr', 'documentdb', 'lab', 'cloud', 'find', 'component', 'logout', 'container', 'login', 'configure')
usage: az [-h] [--output {json,tsv,table,jsonc}] [--verbose] [--debug]
          [--query JMESPATH]
          {feedback,monitor,account,acr,documentdb,lab,cloud,find,component,logout,container,login,configure}
I am facing this issues can u please help me

**Comment by derekbekoe** [comment]
What versions do you have (`az --version`)? You may have outdated modules

What's the output of `az iot -h --debug`? It should contain stacktraces.

**Comment by tjprescott** [comment]
Please answer the questions specified in the Environment Summary and reopen.
