### ISSUE TITLE
the latest docker image doesn't have git installed

### ISSUE THREAD

**Issue by ChaseDaii** [Azure/azure-cli#28248]
### Describe the bug

i was pulling the latest docker image, and found that git command was not found in the image.
![image](https://github.com/Azure/azure-cli/assets/114065856/48bb559a-581c-4ddf-b025-23fe9503e279)

### Related command

docker run-it mcr.microsoft.com/azure-cli:latest
git 

### Errors

git: command not found
![image](https://github.com/Azure/azure-cli/assets/114065856/82172911-15d9-4d54-aa5e-5d038ddf1c27)

### Issue script & Debug output

![image](https://github.com/Azure/azure-cli/assets/114065856/56083cbc-c6b4-480f-a41a-e9fc898915cd)

### Expected behavior

if i try to run an older version, it works
![image](https://github.com/Azure/azure-cli/assets/114065856/580c03c4-bdaa-4744-accc-0e3f1d463f26)

### Environment Summary

not relevant to az version

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
This is by design, see https://github.com/Azure/azure-cli/pull/27567
