### ISSUE TITLE
Unable to load extension 'containerapp' 

### ISSUE THREAD

**Issue by larrywa** [Azure/azure-cli#28244]
### Describe the bug

I am using Az CLI version 2.56.
 
I am seeing an error:
 
WARNING: Unable to load extension 'containerapp: cannot import name 'network_client_factory' from 'azure.cli.command_modules.network._client_factory' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\command_modules\network\_client_factory.pyc)'. Use --debug for more information.
 
Expanded error after debug:
 
DEBUG: cli.knack.cli: Event: MainLoader.OnFailedExtensionLoad []
WARNING: cli.azure.cli.core: Unable to load extension 'containerapp: cannot import name 'network_client_factory' from 'azure.cli.command_modules.network._client_factory' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\command_modules\network\_client_factory.pyc)'. Use --debug for more information.
DEBUG: cli.azure.cli.core: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 351, in _update_command_table_from_extensions
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1081, in _load_extension_command_loader
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1067, in _load_command_loader
  File "C:\Users\larrywa\.azure\cliextensions\containerapp\azext_containerapp\__init__.py", line 23, in load_command_table
    from azext_containerapp.commands import load_command_table
  File "C:\Users\larrywa\.azure\cliextensions\containerapp\azext_containerapp\commands.py", line 10, in <module>
    from ._validators import validate_ssh
  File "C:\Users\larrywa\.azure\cliextensions\containerapp\azext_containerapp\_validators.py", line 14, in <module>
    from ._ssh_utils import ping_container_app
  File "C:\Users\larrywa\.azure\cliextensions\containerapp\azext_containerapp\_ssh_utils.py", line 20, in <module>
    from ._utils import safe_get, is_platform_windows
  File "C:\Users\larrywa\.azure\cliextensions\containerapp\azext_containerapp\_utils.py", line 18, in <module>
    from azure.cli.command_modules.network._client_factory import network_client_factory
ImportError: cannot import name 'network_client_factory' from 'azure.cli.command_modules.network._client_factory' (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\command_modules\network\_client_factory.pyc)
 
 
When I check for the containerapp extension, it is installed.
 
I have also uninstalled and reinstalled the CLI.
 
Any idea what this error means?

### Related command

The issue happens during one of these commands:
$eventHubPrimaryKey = az deployment group show -g $resourceGroupName -n event-hub-deployment --query properties.outputs.eventHubPrimaryKey.value --debug
$appInsightsKey = az deployment group show -g $resourceGroupName -n app-insights-deployment --query properties.outputs.instrumentationKey.value --debug
$appInsightsConnectionString = az monitor app-insights component show --app  appInsights${suffix} -g $resourceGroupName --query connectionString --debug

### Errors

Shown above

### Issue script & Debug output

This information is shown above

### Expected behavior

The expected behavior is to receive the values in my PS script

### Environment Summary

azure-cli                         2.56.0

core                              2.56.0
telemetry                          1.1.0

Extensions:
aks-preview                      0.5.132
application-insights               1.2.0
containerapp                      0.3.23

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\larrywa\.azure\cliextensions'

Python (Windows) 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:21:31) [MSC v.1936 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by AllyW** [comment]
Hi @larrywa , cause some migration happened to network sdk in azure cli 2.47.0， therefore, containerapp is influenced and needs to be upgraded to 0.32.4 or later (run `az upgrade` or `az extension update --name containerapp`). 

Updates about network sdk migration, please refer to this post: https://github.com/Azure/azure-cli/issues/25941

**Comment by FBoucher** [comment]
it fixed the issue for me, I no longer see that message.
