### ISSUE TITLE
Feature to map AAD groups to AWS IAM roles in Azure Enterprise apps

### ISSUE THREAD

**Issue by johnakash** [Azure/azure-cli#28263]
**Related command**
NA

**Is your feature request related to a problem? Please describe.**
Background: I am using Azure AD and Azure Enterprise Apps to enable AWS SSO. And we have around 150 AWS accounts. I am looking for a solution by using which I can map the AAD group into an IAM role, which is listing enterprise apps.

Ref: https://learn.microsoft.com/en-us/entra/identity/saas-apps/amazon-web-service-tutorial 
**Describe the solution you'd like**
Azure CLI or any API which I can used to perform this activity using an automation. 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
Azure CLI only natively supports a subset of Microsoft Graph APIs, covered by `az ad`: https://learn.microsoft.com/en-us/cli/azure/ad. For unsupported APIs, you may use `az rest`: https://github.com/Azure/azure-cli/issues/22580#issuecomment-1150686865

However, as for Microsoft Graph API usages, please contact AAD customer support.
