### ISSUE TITLE
Missing features in "az iot hub create"

### ISSUE THREAD

**Issue by dluc** [Azure/azure-cli#2826]
Please implement the features of `azure` in `az` too:

### az iot hub create -h

```
--name -n
--resource-group -g
--location -l
--sku
--unit
```

### azure iothub create -h

```
-n --name <name>
-g --resource-group <resourceGroup>
-l --location <location>
-k --sku-name <skuName>
-u --units <units>
-e --enable-dm [enableDm]
-p --d2c-partitions [d2cPartitions]
-r --d2c-retention-time-in-days [d2cRetentionTimeInDays]
-d --c2d-max-delivery-count [c2dMaxDeliveryCount]
-c --c2d-ttl [c2dTtl]
-f --feedback-lock-duration [feedbackLockDuration]
-F --feedback-ttl [feedbackTtl]
-m --feedback-max-delivery-count [feedbackMaxDeliveryCount]
-x --enable-fileupload-notifications [enableFileuploadNotifications]
-S --fileupload-storage-connectionstring [fileuploadStorageConnectionstring]
-C --fileupload-container-name [fileuploadContainerName]
-T --fileupload-sas-uri-ttl [fileuploadSasUriTtl]
-N --fileupload-notification-ttl [fileuploadNotificationTtl]
-D --fileupload-notification-max-delivery-count [fileuploadNotificationMaxDeliveryCount]
```

**Comment by dluc** [comment]
@tjprescott I thought it might make more sense to have one ticket with all the missing features, as opposed to one issue per feature (closed #2791)

**Comment by tjprescott** [comment]
@dluc I agree--thanks for closing the duplicate issue!

**Comment by dluc** [comment]
`azure` provides also a device import/export command. Would that be part of this issue too?

azure iothub device -h

```
Commands to manage the devices of an IoT hub

Export the devices of an IoT hub
  iothub device export <resourceGroup> <name> [options]

Import the devices of an IoT hub
  iothub device import <resourceGroup> <name> [options]

Options:
  -h, --help  output usage information
```

**Comment by xscript** [comment]
@dluc have you checked out `az iot device export` and `az iot device import`?

**Comment by dluc** [comment]
@xscript with regard to import/export yes, I noticed right after posting my last comment, which I deleted.

With regard to the creation option, it would really be a better user experience to do all at once, like `azure iothub create` does. Is there any reason to split the operation in 2 steps?

**Comment by dluc** [comment]
By the way I don't think the workaround works for the number of partitions, that setting can be set only during the creation.

Looking at the syntax of `az iot hub update` I'm not sure that actually does what I am looking for:

```
Command
    az iot hub update: Update non-security metadata of an IoT Hub.

    --ids              : One or more resource IDs (space delimited). If provided, no other 'Resource
                         Id' arguments should be specified.
    --name -n          : IoT Hub name.
    --resource-group -g: Name of resource group. You can configure the default group using 'az
                         configure --defaults group=<name>'.

    --add              : Add an object to a list of objects by specifying a path and key value
                         pairs.  Example: --add property.listProperty <key=value, string or JSON
                         string>.
    --remove           : Remove a property or an element from a list.  Example: --remove
                         property.list <indexToRemove> OR --remove propertyToRemove.
    --set              : Update an object by specifying a property path and value to set.  Example:
                         --set property1.property2=<value>.
```

How would you use it to set TTLs, delivery count thresholds, etc. ?

**Comment by tjprescott** [comment]
@dluc for those properties you can update, you can use the generic set syntax to set them, based on the structure of the JSON output for `iot hub show`.  There's an open issue #2531 to add convenience flags to the update command, but anything you could accomplish with them you can accomplish with generic set (though the syntax may be really ugly).

**Comment by dluc** [comment]
@tjprescott any update on this front?  Some properties can be set only before the deployment, e.g. the number of partitions, so there should be a dedicated flag for `az iot hub create`

**Comment by chrissie926** [comment]
@dluc Thank you for the followup. We are working on the CLI 2.0 planning right now. The goal is to have azure commands and az commands in parity. I will update you the ETA by end of this week.

**Comment by jlian** [comment]
We should have parity. Feature request.

**Comment by jlian** [comment]
Created item to target Nov this year https://msazure.visualstudio.com/One/_workitems/edit/4979160
