### ISSUE TITLE
az network front-door routing-rule not updating Premium afds

### ISSUE THREAD

**Issue by Jaxelr** [Azure/azure-cli#28268]
**Related command**

The team is trying to use the `az network front-door routing-rule update -g {resourcegroup} -f {frontdoor} -n {routing} --backend-pool {backendpool}` to reroute traffic via the az-cli.

**Is your feature request related to a problem? Please describe.**

Our team has an Azure Front Door Classic that we recently migrated to the Premium version, we had the ability to reroute traffic by swapping backend-pools on the Classic AFD, using the az cli command provided above. After the migration, we are not allowed to upgrade the frontdoor with a message of `(BadRequest) No updates can be made on the frontdoor in Migrated State. Code: BadRequest
Message: No updates can be made on the frontdoor in Migrated State.`, which is understandable and completely expected. 

![image](https://github.com/Azure/azure-cli/assets/5913008/9353e17f-b301-43b8-bdd5-129c64f295be)

But, if we run the command `az network front-door routing-rule list -g {resourcegroup} -f {newPremiumFrontDoor}` we cannot find the migrated resources via the cli, we receive an ResourceNotFound failure. I've confirmed that both resources are on the same resource group / subscription. 

<img width="808" alt="image" src="https://github.com/Azure/azure-cli/assets/5913008/cf825964-fd06-4075-b5b4-b58334064610">

**Describe the solution you'd like**

We would like to be able to see the migrated premium frontdoor with another name (the one shown on the portal) and to have the ability to reroute traffic using the original command above or any similar command.

**Describe alternatives you've considered**

We can currently do the traffic rerouting via the azure portal, but because of the Sev 0 from the ARM outage which recently happened, we were unable to move traffic and it caused us our team to have a Sev 2 as well.

**Additional context**

**Comment by benj-ch** [comment]
Hi,

To use Az CLI with Azure Front Door Standard/Premium, you have to use the new CLI command `az afd`
https://learn.microsoft.com/fr-fr/cli/azure/afd?view=azure-cli-latest

**Comment by Jaxelr** [comment]
This Issue can be closed then, thanks for the clarification.
