### ISSUE TITLE
Cross region copy of incremental snapshot with enhanced speed 

### ISSUE THREAD

**Issue by AdamZLi** [Azure/azure-cli#28276]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az snapshot create

### Resource Provider

Disk Restore Provider

### Description of Feature or Work Requested

We're introducing a new "enhanced speed" tier for copying incremental snapshots of managed disks from one region to the other with higher bandwidth. This is a paid tier offering for the service aiming to provide 2X bandwidth. 

Today, when customer copy an incremental snapshot to a different region in CLI, they use az snapshot create (https://learn.microsoft.com/en-us/azure/virtual-machines/disks-copy-incremental-snapshot-across-regions?tabs=azure-cli#managed-copy).

We need to add another option for az snapshot create for "TierOption" as an parameter, and customer can make it EnhancedSpeed.

### Minimum API Version Required

2023-10-02

### Swagger PR link / SDK link

[Compute] New API version 2023-10-02 by haagha · Pull Request #27120 · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/pull/27120)

[[Compute] SDK version from 2023-10-02 by haagha · Pull Request #41456 · Azure/azure-sdk-for-net (github.com)](https://github.com/Azure/azure-sdk-for-net/pull/41456)

### Target Date

2024-2-28

### PM Contact

adli@microsoft.com

### Engineer Contact

stevenlara@microsoft.com

### Additional context

N/A

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yanzhudd** [comment]
Hi @AdamZLi 
since we have planed a lot of works to do and have no more time to develop this feature in this sprint. May I ask if the ETA 04-02 acceptable to you?

**Comment by AdamZLi** [comment]
Hi @yanzhudd ,

Sorry for the late response as I was OOF last few weeks. ETA 04-02 is the ETA for rolling out the CLI changes? If so, that should be acceptable timeline. Please advise how we should track this effort (in this thread, or on team). Thank you!

**Comment by yanzhudd** [comment]
> Hi @yanzhudd ,
> 
> Sorry for the late response as I was OOF last few weeks. ETA 04-02 is the ETA for rolling out the CLI changes? If so, that should be acceptable timeline. Please advise how we should track this effort (in this thread, or on team). Thank you!

That's correct. ETA 04-02 will be the date for rolling out this CLI change.
We usually track features in GitHub, so this thread will be fine.

**Comment by AdamZLi** [comment]
Thanks!!
