### ISSUE TITLE
Microsoft.OperationalInsights 2022-10-01 Update, 2023-09-01 Create

### ISSUE THREAD

**Issue by dulikvor** [Azure/azure-cli#28287]
**Resource Provider**
Microsoft.OperaitonalInsights

**Description of Feature or Work Requested**
Addition of new stable version (2023-09-01), Updates to existing stable version (2022-10-01).
Details in the doc listed below:
[CLI_OperationInsights_2023-09-01.docx](https://github.com/Azure/azure-cli/files/14122705/CLI_OperationInsights_2023-09-01.docx)

Changes are scoped to 3 resources:
2023-09-01 -> workspaces
2022-10-01 -> clusters, workspaces/tables

**Swagger PR link**
[[Hub Generated] Review request for Microsoft.OperationalInsights to a… · Azure/azure-rest-api-specs-pr@4e11f91 (github.com)](https://github.com/Azure/azure-rest-api-specs-pr/commit/4e11f9198d3500bb47fffe805ffa7c25a1a4bc46)

[[Hub Generated] Review request for Microsoft.OperationalInsights to a… · Azure/azure-rest-api-specs-pr@e7fa448 (github.com)](https://github.com/Azure/azure-rest-api-specs-pr/commit/e7fa448fbdf57e3a235b1c11a8441795fdd1127b)

**Target Date**
2024-03-01

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
