### ISSUE TITLE
Azure blob storage filter by lease status

### ISSUE THREAD

**Issue by ViswanathVeerappan** [Azure/azure-cli#28280]
Hello Team,

I was wondering if there was an option to filter the blobs available in a container by its lease status using the listBlobs operation.

Thanks,

Viswanath V

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by calvinhzy** [comment]
Hi @ViswanathVeerappan, you can try with the `--query` param with something like this. `az storage blob list --account-name satestquery -c container1 --query "[?properties.lease.status=='unlocked']"`
here is the link to how to format the query for the specific status needed https://learn.microsoft.com/en-us/cli/azure/query-azure-cli?tabs=concepts%2Cbash#filter-arrays-with-boolean-expressions

**Comment by ViswanathVeerappan** [comment]
Hi @calvinhzy, I'm using the Java client library and within the library, I've a couple of options to find the blobs associated with a container.

1. listBlobs() => does not have a way to send query to filter the blobs by properties or lease state in particular
2. findBlobsByTags => would take a query, but it would only search by tags added by a user.

Please help me find the appropriate api which would help me fetch blobs by lease state or in general the properties of a blob.

FYI, The following are the library details used in my application,

<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-storage-blob</artifactId>
  <version>12.16.1</version>
</dependency>
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-core</artifactId>
  <version>1.28.0</version>
</dependency>

**Comment by calvinhzy** [comment]
Hi @ViswanathVeerappan as far as I can see, the Python SDK does not have a way to filter on the service side. The filtering would need to be done through custom client code. Feel free to open an issue with the sdk team https://github.com/Azure/azure-sdk-for-java/issues/new?assignees=&labels=&projects=&template=feature_request.md&title=%5BFEATURE+REQ%5D and they might have some more insight as to when this filter option would be added.

**Comment by ViswanathVeerappan** [comment]
Hi @calvinhzy, Thanks for your response. I have created a feature request for this [here](https://github.com/Azure/azure-sdk-for-java/issues/38579).

Thanks,

Viswanath V

**Comment by calvinhzy** [comment]
Glad I could help! Thanks.
