### ISSUE TITLE
"az snapshot grant-access" fails with "Accessing disk or snapshot with a logical sector size of 4096 requires specifying the file format. Set the fileFormat property to VHDX."

### ISSUE THREAD

**Issue by riccom76** [Azure/azure-cli#28320]
### Describe the bug

CLI cmdlet "az snapshot grant-access", using APIs equal or later than 2023-01-02, fails with "Accessing disk or snapshot with a logical sector size of 4096 requires specifying the file format. Set the fileFormat property to VHDX".

<table><td>
[ ~ ]$ az snapshot grant-access --duration-in-seconds 3600 --resource-group martinme_repro --name premV2Snap

(BadRequest) Accessing disk or snapshot with a logical sector size of 4096 requires specifying the file format. Set the fileFormat property to VHDX.
Code: BadRequest
Message: Accessing disk or snapshot with a logical sector size of 4096 requires specifying the file format. Set the fileFormat property to VHDX.
<td></table>

When trying to pass the "fileFormat" as parameter for CMDLets, an error is returned saying the 'fileFormat' isn't valid.
<table><td>
[ ~ ]$ az snapshot grant-access --duration-in-seconds 3600 --resource-group martinme_repro --name premV2Snap --fileFormat VHDX
unrecognized arguments: --fileFormat VHDX
<td></table>

Tested with RESTAPI --> [Snapshots - Grant Access - REST API (Azure Compute) | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/compute/snapshots/grant-access?view=rest-compute-2023-10-02&tabs=HTTP)
The supported api-versions are '2016-04-30-preview, 2017-03-30, 2018-04-01, 2018-06-01, 2018-09-30, 2019-03-01, 2019-07-01, 2019-11-01, 2020-05-01, 2020-06-30, 2020-09-30, 2020-12-01, 2021-04-01, 2021-08-01, 2021-12-01, 2022-03-02, 2022-07-02, 2023-01-02, 2023-04-02, 2023-10-02'

<html>
<body>
<ul style="box-sizing: border-box; color: rgb(0, 0, 0); font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 14.6667px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 11pt; color: rgb(0, 0, 0);"><span style="box-sizing: border-box; background-color: rgb(0, 255, 0);">SUCCESS:</span><span> </span>I've tried it again with the RestAPI by specifying with the fileFormat set to VHDX in the body and it works with the latest API version<span> </span><span style="box-sizing: border-box; background-color: rgb(255, 255, 0); display: inline !important;">2023-10-02 </span>as well: <a href="https://learn.microsoft.com/en-us/rest/api/compute/snapshots/grant-access?view=rest-compute-2023-10-02&amp;tabs=HTTP" target="_blank" style="box-sizing: border-box; color: var(--icm-primary-color, #0078d4); text-decoration: none; cursor: pointer;">Snapshots - Grant Access - REST API (Azure Compute) | Microsoft Learn</a></li><li style="box-sizing: border-box; font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 11pt; color: rgb(0, 0, 0);">
{access: "Read",durationInSeconds: "3600",fileFormat: "VHDX"}
--
</li></ul>

"az snapshot grant-access", using APIs equal or later than 2023-01-02, do not offer any parameter to define the "fileFormat".

RestAPI [Snapshots - Grant Access - REST API (Azure Compute) | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/compute/snapshots/grant-access?view=rest-compute-2023-10-02&tabs=HTTP) accepts the "fileFormat" as parameter. CLI cmdlet should do the same.

### Related command

az snapshot grant-access --duration-in-seconds 3600 --resource-group martinme_repro --name premV2Snap

### Errors

[ ~ ]$ az snapshot grant-access --duration-in-seconds 3600 --resource-group martinme_repro --name premV2Snap --fileFormat VHDX
unrecognized arguments: --fileFormat VHDX

### Issue script & Debug output

-

### Expected behavior

"az snapshot grant-access", using APIs equal or later than 2023-01-02, do not offer any parameter to define the "fileFormat".

RestAPI [Snapshots - Grant Access - REST API (Azure Compute) | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/compute/snapshots/grant-access?view=rest-compute-2023-10-02&tabs=HTTP) accepts the "fileFormat" as parameter. CLI cmdlet should do the same.

### Environment Summary

Azure Portal CloudShell

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yanzhudd** [comment]
Hi @riccom76,
currently CLI has no parameter to set the field "fileFormat". If you want CLI to support this feature, please provide the necessary info by raising a feature request using this [feature request template](https://github.com/Azure/azure-cli/issues/new?assignees=&labels=feature-request&projects=&template=Service_team_request.yml).

**Comment by riccom76** [comment]
hi @yanzhudd , this is not a feature request but more a fix to a misalignment between the CLI cmdlet parameters and what the RestAPI version used is expecting as parameters when invoked.

RestAPI [Snapshots - Grant Access - REST API (Azure Compute) | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/compute/snapshots/grant-access?view=rest-compute-2023-10-02&tabs=HTTP) vesion equal or later than 2023-01-02, expects the "fileFormat" to be there. This CLI cmdlet has to be updated to accommodate what the RestAPI expects as passed parameters.

**Comment by yanzhudd** [comment]
Hi @riccom76 
I have raised a PR to fix this issue, could you please help to verify if this private package meets your expectation?
https://dev.azure.com/azclitools/public/_build/results?buildId=140563&view=artifacts&pathAsName=false&type=publishedArtifacts

Thanks in advance!
