### ISSUE TITLE
Azure Front Door WAF Configuration using az 

### ISSUE THREAD

**Issue by hugopinetree** [Azure/azure-cli#28340]
**Related command**

I am giving a proposal to the azure front door team to consider an addition to the `az afd` command SDK in the Azure Front Door Premium SDK that would allow us to automate the WAF policy creation. I would also appreciate some guidance on the best way to do this right now.
**Is your feature request related to a problem? Please describe.**

none
**Describe the solution you'd like**

I would like to see a command to create and configure the WAF Policy using AZ so that my team could automate the policy creation process.
**Describe alternatives you've considered**

I have considered `az resource create` but found it a little cumbersome. 
**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by t-bzhan** [comment]
Hi @hugopinetree , can you check whether https://learn.microsoft.com/en-us/cli/azure/network/front-door/waf-policy?view=azure-cli-latest helps?
