### ISSUE TITLE
'az monitor app-insights component' is only using deprecated IKey.

### ISSUE THREAD

**Issue by tomo-msft** [Azure/azure-cli#28348]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

- az monitor app-insights component connect-webapp
- az monitor app-insights component connect-function

### Resource Provider

microsoft.insights/components

### Description of Feature or Work Requested

The current ‘az monitor app-insights component’ is only using IKey. However, since this will be deprecated soon, it is necessary to change to use a connection string.
For example, the following changes are necessary.
https://github.com/Azure/azure-cli-extensions/compare/main...tomo-msft:azure-cli-extensions:main

### Minimum API Version Required

N/A

### Swagger PR link / SDK link

N/A

### Request Example

N/A

### Target Date

2025-03-31

### PM Contact

tmasushio@microsoft.com

### Engineer Contact

N/A

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
