### ISSUE TITLE
"az vmss nic" CLI Documentation Issue

### ISSUE THREAD

**Issue by hilaryw29** [Azure/azure-cli#28342]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

- az vmss nic list
- az vmss nic show
- az vmss nic list-vm-nics

### Resource Provider

Microsoft.Compute

### Description of Feature or Work Requested

The above commands are Uniform-specific and will not work for Flexible VMSS (returns NotFound). Can we please update the CLI documentation on these commands to highlight that they are Uniform-only and Flexible VMSS should use [az network nic](https://learn.microsoft.com/en-us/cli/azure/network/nic?view=azure-cli-latest) commands instead?  

Affected documentation/cmdlets:
- [az vmss nic](https://learn.microsoft.com/en-us/cli/azure/vmss/nic?view=azure-cli-latest)

This was identified from the following github issue: https://github.com/Azure/azure-cli/issues/28258

### Minimum API Version Required

N/A

### Swagger PR link / SDK link

N/A - this is a documentation request

### Request Example

N/A - this is a documentation request

### Target Date

N/A

### PM Contact

hilarywang

### Engineer Contact

N/A

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
@yanzhudd  Could you help update the relevant information in the help message of these commands?

**Comment by yanzhudd** [comment]
Hi @hilaryw29 
we have updated the help messages of these commands. Could you please help to review this [PR](https://github.com/Azure/azure-cli/pull/28390)? Thanks!
