### ISSUE TITLE
Resource tag and Managing Disks Using the Azure CLI 

### ISSUE THREAD

**Issue by metazog** [Azure/azure-cli#2835]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.2)

**OS Version:** What OS and version are you using?  
Answer here: Windows

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

---

### Description
With the CLI 2.0, I can apply a Resource Tag to a Managed Disk and Managed Snapshot, but not a Managed Image.

C:\Users\riwasa>az resource tag --tags cli20=set -g rgname -n web2vm-image --resource-type "Microsoft.Compute/images"
Changing property 'osDisk.caching' is not allowed.

With PowerShell, I can apply a Resource Tag to Managed Disks, Images, and Snapshots.

**Comment by neilpeterson** [comment]
+1 on this using two methods for applying the tag.

```
neillocal@MININT-4A5OFPD:~$ az resource tag --tags created=$date --id /subscriptions/11111111-2222-2222-2222-333333333333/resourceGroups/myResourceGroup/providers/Microsoft.Compute/images/myImage
Changing property 'osDisk.caching' is not allowed.
```

and then similar to @metazog 

```
neillocal@MININT-4A5OFPD:~$ az resource tag --tags created=test -g myResourceGroup -n myImage --resource-type "Microsoft.Compute/images"
Changing property 'osDisk.caching' is not allowed.
```

**Comment by yugangw-msft** [comment]
It is confirmed the CRP service has a bug. The fix will roll out sometime in June. This is not a CLI bug

**Comment by yugangw-msft** [comment]
For now, the workaround is to tag using the `create` command

**Comment by yugangw-msft** [comment]
Verified it has been fixed
