### ISSUE TITLE
az functionapp deployment source config-zip --build-remote false is been treated as "--build-remote true"

### ISSUE THREAD

**Issue by VixiXia** [Azure/azure-cli#28369]
### Describe the bug

When running [az functionapp deployment source config-zip --build-remote **false**](https://learn.microsoft.com/en-us/cli/azure/functionapp/deployment/source?view=azure-cli-latest#az-functionapp-deployment-source-config-zip) to do deployment to Linux function app, it is been treated as setting "--build-remote **true**" which enabled remote build and also set SCM_DO_BUILD_DURING_DEPLOYMENT to true for the function app based on code logic [add_remote_build_app_settings](https://github.com/Azure/azure-cli/blob/release/src/azure-cli/azure/cli/command_modules/appservice/custom.py) during the deployment. 

If we do not specify the parameter --build-remote, it will use the default value false which is working fine, but if we specify --build-remote false, it treats it as --build-remote true. Based on code logic here [azure-cli/src/azure-cli/azure/cli/command_modules/appservice/custom.py at release · Azure/azure-cli (github.com)](https://github.com/Azure/azure-cli/blob/release/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L608), it will check build-remote value, if build-remote is false, it should go to remove_remote_build_app_settings instead of  add_remote_build_app_settings, however it goes to add_remote_build_app_settings logic here, not sure if the parameter value passed is changed or any code logic issue here: 

![image](https://github.com/Azure/azure-cli/assets/24731902/dc8b89e8-c71d-4910-8db1-d503252d1f04)
![image](https://github.com/Azure/azure-cli/assets/24731902/224cee6c-2347-40d7-ad45-8b10d455756d)

### Related command

az functionapp deployment source config-zip --build-remote false

### Errors

No error, it is just the behavior is not correct as expected. 

### Issue script & Debug output

cli.azure.cli.command_modules.appservice.custom: Setting SCM_DO_BUILD_DURING_DEPLOYMENT to true

### Expected behavior

It should not enable remote build and also do not set SCM_DO_BUILD_DURING_DEPLOYMENT to true.

### Environment Summary

azure-cli                         2.57.0
core                              2.57.0
telemetry                          1.1.0
Dependencies:
msal                              1.26.0
azure-mgmt-resource             23.1.0b2

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by VixiXia** [comment]
@yonzhan Good day. May I know if we have any update on this issue?

**Comment by VixiXia** [comment]
@shreyas-gopalakrishna Good day. Would you please help check this issue? If we do not specify the parameter --build-remote, it will use the default value false which is working fine, but if we specify --build-remote false, it treats it as --build-remote true.  Based on code logic here [azure-cli/src/azure-cli/azure/cli/command_modules/appservice/custom.py at release · Azure/azure-cli (github.com)](https://github.com/Azure/azure-cli/blob/release/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L608), it will check build-remote value, seems logic is correct. Not sure which part caused the issue here.

**Comment by VixiXia** [comment]
@shreyas-gopalakrishna @amamounelsayed @kaibocai @kamperiadis Wish everything is fine there. Would you please help check this issue?

**Comment by VixiXia** [comment]
I checked the source code, it seems like it is due to code logic below, if return_label set to true, it always return the label which is a string not a boolean value
![image](https://github.com/Azure/azure-cli/assets/24731902/3120dddb-4cc5-4cef-83c7-49e06c68d408)
![image](https://github.com/Azure/azure-cli/assets/24731902/14f53de3-ade5-4565-93f7-2cae1461e61f)
![image](https://github.com/Azure/azure-cli/assets/24731902/3da31804-ca8b-43e7-8686-55f0c4804758)

so the condition below always be true no matter we pass --build-remote true or --build-remote false
seems like we just need to change the code to not pass return_label and the default value is False for this to return boolean value for the parameter

with self.argument_context(scope + ' deployment source config-zip') as c:
            c.argument('src', help='a zip file path for deployment')
            c.argument('build_remote', help='enable remote build during deployment',
                       arg_type=**get_three_state_flag()**)

[azure-cli/src/azure-cli/azure/cli/command_modules/appservice/_params.py at release · Azure/azure-cli (github.com)](https://github.com/Azure/azure-cli/blob/release/src/azure-cli/azure/cli/command_modules/appservice/_params.py#L309)
[azure-cli/src/azure-cli-core/azure/cli/core/commands/parameters.py at release · Azure/azure-cli (github.com)](https://github.com/Azure/azure-cli/blob/release/src/azure-cli-core/azure/cli/core/commands/parameters.py#L161)
[azure-cli/src/azure-cli/azure/cli/command_modules/appservice/custom.py at release · Azure/azure-cli (github.com)](https://github.com/Azure/azure-cli/blob/release/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L621)

**Comment by kamperiadis** [comment]
Hi @VixiXia! This should be fixed with the latest Azure CLI version. Can you please try to see if you are still experiencing this issue? Thank you!
