### ISSUE TITLE
az afd route update "The command line is too long."

### ISSUE THREAD

**Issue by benj-ch** [Azure/azure-cli#28379]
### Describe the bug

I have an Azure Front Door Premium, 1 route with some urls associated.
I want to remove 1 url from the route.

I got the following error "az: The command line is too long.": 
![image](https://github.com/Azure/azure-cli/assets/61045959/fe41347f-eddf-4fe6-8fe3-648b3f42d983)

The command has 8346 characters and PowerShell accepts only 8191.

I have other routes with more URLs.

How manage Azure Front Door with a command line?
There is no PowerShell commands to do this.

### Related command

az afd route update --resource-group RSGXXXXXXYYY001-TEMPOR --profile-name LBAXXXXXXYYY001 --endpoint-name LBAXXXXXXYYY001 --route-name "abcdefghijklmno-test-route" --custom-domains /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999985-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999950-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999949-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999916-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999973-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999974-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999991-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999997-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999924-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999969-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999994-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999987-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999906-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999940-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/url01-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999992-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999956-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999918-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999983-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999945-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999946-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999963-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999907-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999917-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999993-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999931-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999926-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999921-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999927-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999920-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999988-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999962-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999914-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999968-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999925-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999958-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999913-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999901-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999941-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999903-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999954-customdomaincustomer-contoso-com /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999955-customdomaincustomer-contoso-com

### Errors

az : The command line is too long.
At line:1 char:1
+ az afd route update --resource-group RSGXXXXXXYYY001-TEMPOR --profile ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The command line is too long.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

### Issue script & Debug output

az : The command line is too long.
At line:1 char:1
+ az afd route update --resource-group RSGXXXXXXYYY001-TEMPOR --profile ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The command line is too long.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

### Expected behavior

I want to manage my URLs associated with the route, regardless of the number of URLs.

A command line like:
`az afd route update add-customdomain --resource-group RSGXXXXXXYYY001-TEMPOR --profile-name LBAXXXXXXYYY001 --endpoint-name LBAXXXXXXYYY001 --route-name "abcdefghijklmno-test-route" --custom-domain /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999955-customdomaincustomer-contoso-com`

`az afd route update remove-customdomain --resource-group RSGXXXXXXYYY001-TEMPOR --profile-name LBAXXXXXXYYY001 --endpoint-name LBAXXXXXXYYY001 --route-name "abcdefghijklmno-test-route" --custom-domain /subscriptions/b3012d5c-1b0e-4ccb-b19b-96273f4eb345/resourcegroups/RSGXXXXXXYYY001-TEMPOR/providers/Microsoft.Cdn/profiles/LBAXXXXXXYYY001/customdomains/99999955-customdomaincustomer-contoso-com`

Or just use the name of the URL and not the resourceId.

### Environment Summary

azure-cli                         2.57.0

core                              2.57.0
telemetry                          1.1.0

Extensions:
azure-iot                         0.21.2
front-door                        1.0.16
resource-graph                     2.1.0

Dependencies:
msal                              1.26.0
azure-mgmt-resource             23.1.0b2

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by benj-ch** [comment]
I just updated the az cli version and updated the issue.
azure-cli                         2.57.0

**Comment by t-bzhan** [comment]
Hi @benj-ch, you don’t need to specify the complete resource ID. Instead, you can use the custom domain name to shorten the length of the command line, like this::
`az afd route update --resource-group bo-private --profile-name bzhan-test111 --endpoint-name dnltest --route-name route11 --custom-domains bundletest-localdev-cdn-azure-cn`

The CLI itself will automatically add the required resource groups and profiles to obtain the underlying resource ID. For more details, refer to https://github.com/Azure/azure-cli/blob/b07a0c75978ef72bf0a2e1f074f157ce4e3f1210/src/azure-cli/azure/cli/command_modules/cdn/custom/custom_afdx.py#L371C1-L378C48
![image](https://github.com/Azure/azure-cli/assets/61817681/bc517615-e476-4385-854f-d7a17f8fdf0a)

**Comment by benj-ch** [comment]
Thank you @t-bzhan!
