### ISSUE TITLE
Unable to create a VM with --security-type Standard

### ISSUE THREAD

**Issue by jackmtpt** [Azure/azure-cli#28397]
### Describe the bug

It looks like on azcli 2.57.0 it's not possible to explicitly create a VM with `--security-type Standard`. Looking at the ARM template that's sent for deployment, if --security-type isn't specified at all then it sends the following:

```
"securityProfile": {
                    "securityType": "TrustedLaunch",
                    "uefiSettings": {
                        "secureBootEnabled": true,
                        "vTpmEnabled": true
                    }
                }
```

but if it's set to Standard then you get this - notice how securityType is not actually sent as part of the template at all:

```
"securityProfile": {
                    "uefiSettings": {
                        "secureBootEnabled": true,
                        "vTpmEnabled": true
                    }
                }
```

and then you get the below error that says `Use of UEFI settings is not supported when security type is not set.`

If you then include `--enable-secure-boot false --enable-vtpm false` as well as `--security-type Standard` those two `uifiSettings` attributes are set to `false` but this is still rejected by ARM; it seems to require that the `uefiSettings` property isn't present at all if `securityType` is not set.

I think the best fix here is for the CLI to always set `securityType`, and not omit it just because it's Standard.

### Related command

az vm create --resource-group your-rg --name linux-test-cli --image Canonical:0001-com-ubuntu-server-jammy:22_04-lts-gen2:latest --subscription your-sub --subnet /subscriptions/a/subnet --public-ip-address "" --nsg "" --nic-delete-option delete --admin-username azureuser --admin-password password  --storage-sku Premium_LRS --size Standard_D4ads_v5 --security-type Standard

### Errors

ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/blah/providers/Microsoft.Resources/deployments/vm_deploy_7oPl207xwHytCotfrwlloxp9FihjYAoW","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"BadRequest","message":"Use of UEFI settings is not supported when security type is not set."}]}}

### Issue script & Debug output

attached

### Expected behavior

The VM should be created with security type Standard, as it used to be on old CLI versions.

### Environment Summary

azure-cli                         2.57.0

core                              2.57.0
telemetry                          1.1.0

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                              1.26.0
azure-mgmt-resource             23.1.0b2

**Comment by jackmtpt** [comment]
[debug.log](https://github.com/Azure/azure-cli/files/14333361/debug.log)

**Comment by jackmtpt** [comment]
Possibly due to https://github.com/Azure/azure-cli/blob/48d06b2a293e22f4c87236d618324ed93a9b5dcb/src/azure-cli/azure/cli/command_modules/vm/_template_builder.py#L646

**Comment by jaypipes** [comment]
Possible duplicate of #28396

**Comment by jackmtpt** [comment]
Hah, looks like it is. Looks like that got created while I was writing mine.

**Comment by zhoxing-ms** [comment]
@yanzhudd @AjKundnani Please take a look at this issue~

**Comment by CyanDevs** [comment]
Thanks for the fix. It seems to be slated for an April release -- are there any workarounds we can use in the meantime?

**Comment by yanzhudd** [comment]
> Thanks for the fix. It seems to be slated for an April release -- are there any workarounds we can use in the meantime?

Hi @CyanDevs,
this fix will be released on 03-05.

**Comment by picklesrein** [comment]
Am I missing something or does this mean I can't use cli to deploy until then?

On Feb 26, 2024 21:15, Yan Zhu ***@***.***> wrote:

Thanks for the fix. It seems to be slated for an April release -- are there any workarounds we can use in the meantime?

Hi @CyanDevs<https://github.com/CyanDevs>,
this fix will be released on 03-05.

**Comment by picklesrein** [comment]
This worked for me on EL8:
~~~
dnf list --showduplicates azure-cli
dnf install azure-cli-2.56.0-1.el8
~~~
https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=dnf#install-specific-version
