### ISSUE TITLE
CLI Command does works fully  

### ISSUE THREAD

**Issue by joaoleandr** [Azure/azure-cli#28395]
### Describe the bug

command - az functionapp list - partial list of Function Apps 

### Related command

az functionapp list 

### Errors

Which our of 25 only 24 function apps appear.

### Issue script & Debug output

[debugOutput (1).txt](https://github.com/Azure/azure-cli/files/14331489/debugOutput.1.txt)

### Expected behavior

all 25 functions should appear 

### Environment Summary

azure cli 2.57.0.

**Comment by KonradKws** [comment]
Hello, facing same problem here with the latest version of CLI 2.61. We are missing about 20 FA form 283 total on subscription.
Issue is not happening on version 2.55 and when listing functions inside resource group. Could not find any connection between missing Function Aps besides there are all running on consumption plan.
