### ISSUE TITLE
traffic-manager command failed to update endpoint

### ISSUE THREAD

**Issue by iljoong** [Azure/azure-cli#2839]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
apt-get

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
azure-cli (2.0.0)
network (2.0.0)

**OS Version:** What OS and version are you using?  
Windows 10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Bash on Windows

---

### Description
Cannot update endpoint settings. '--type' parameter seems to be used setting resource rul as below
```
$ az network traffic-manager endpoint update -g DEMO-FTAPP --profile-name ilkimftapptm --name endpoint1 --priority 3 --type "Microsoft.Network/trafficManagerProfiles/azureEndpoints"
Operation failed with status: 'Bad Request'. Details: 400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/<subs>/resourceGroups/DEMO-FTAPP/providers/Microsoft.Network/trafficmanagerprofiles/ilkimftapptm/Microsoft.Network%2FtrafficManagerProfiles%2FazureEndpoints/endpoint1?api-version=2015-11-01
```

url should be:

```
https://management.azure.com/subscriptions/<subs>/resourceGroups/DEMO-FTAPP/providers/Microsoft.Network/trafficmanagerprofiles/ilkimftapptm/azureEndpoints/endpoint1?api-version=2015-11-01
```

I tried below command and it didn't work too!

```
$ az network traffic-manager endpoint update -g DEMO-FTAPP --profile-name ilkimftapptm --name endpoint1 --priority 3 --type "azureEndpoints"
The value 'azureEndpoints' provided for field 'type' is invalid. Expected value is 'Microsoft.Network/trafficManagerProfiles/azureendpoints'.
```

**Comment by iljoong** [comment]
workaround is using `az resource update` command
```
az resource update -g DEMO-FTAPP --namespace "Microsoft.Network/trafficManagerProfiles" \
	--resource-type "azureEndpoints" --api-version 2015-04-28-preview \
	--parent "ilkimftapptm" -n endpoint1 \
	--set properties.priority=1 --verbose
```
notice that `azureEndpoints` is used for `-resource-type` value, not `Microsoft.Network/trafficManagerProfiles/azureEndpoints`

**Comment by tjprescott** [comment]
Hi @iljoong, what kind of endpoint are you originally creating that you are attempting to update to type azureEndpoints?
