### ISSUE TITLE
Standby Pools on VMSS Flex

### ISSUE THREAD

**Issue by mimckitt** [Azure/azure-cli#28416]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Resource Provider

Microsoft.StandbyPools

### Description of Feature or Work Requested

Standby Pools enables customers to create a pool of preprovisioned VMs that their scale set (Flexible orchestration mode only) can use when scaling out. See attached docs for more information. 

[Standby Pools - Update or Delete.pdf](https://github.com/Azure/azure-cli/files/14352406/Standby.Pools.-.Update.or.Delete.pdf)
[Standby Pools - Create.pdf](https://github.com/Azure/azure-cli/files/14352407/Standby.Pools.-.Create.pdf)
[Standby Pools - Overview.pdf](https://github.com/Azure/azure-cli/files/14352408/Standby.Pools.-.Overview.pdf)
[Standby Pools - FAQ.pdf](https://github.com/Azure/azure-cli/files/14352409/Standby.Pools.-.FAQ.pdf)

### Minimum API Version Required

2023-12-01-preview

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/tree/main/specification/standbypool

### Request Example

https://github.com/Azure/azure-rest-api-specs/tree/main/specification/standbypool/resource-manager/Microsoft.StandbyPool/preview/2023-12-01-preview/examples

### Target Date

2024-03-31

### PM Contact

mimckitt

### Engineer Contact

box

### Additional context

The Swagger was just merged today (2/20/2024). So the Python SDK has yet been generated. I selected the no update needed box but unsure if that's accurate.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by mimckitt** [comment]
@bxubxu FYI

**Comment by zhoxing-ms** [comment]
> Target Date
2024-03-31

@mimckitt As our work for this sprint is already fully scheduled, we plan to develop it in the next sprint. Our expected release time is `04-02`, do you think it meets your expectations?

**Comment by jsntcy** [comment]
@mimckitt, could you please fill the [form](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRzREmk_IqvpAtIsQYYeErr9URU9ITVQ5Sk5aTUwyNVIxTVJGR0swQVZRSi4u) first?
Add the PM of Azure CLI @Jacekey23 to help on the onboarding process.

**Comment by mimckitt** [comment]
@jsntcy I just completed the form.

**Comment by zhoxing-ms** [comment]
Completed by PR https://github.com/Azure/azure-cli-extensions/pull/7430 of PLR
