### ISSUE TITLE
Add `--redirect-port` to `az login` command

### ISSUE THREAD

**Issue by cecheta** [Azure/azure-cli#28425]
**Related command**

`az login`

**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Similar to the `azd auth login` command, it would be good to have the ability to specify the redirect port used in the browser login for `az login`. At the moment, it uses a random ephemeral port.

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
Duplicate of #24626
