### ISSUE TITLE
When you use az aks update to set the LTS mode on an existing AKS cluster, auto upgrade is defaulting to patch

### ISSUE THREAD

**Issue by israelvaldez** [Azure/azure-cli#28436]
### Describe the bug

When you use az aks update to set the LTS mode on an existing AKS cluster, auto upgrade is defaulting to patch

### Related command

az aks update

### Errors

The auto upgrade channel is defaulted to patch, causing unplanned upgrades on AKS clusters in the middle of the day, causing downtime

### Issue script & Debug output

az aks update --resource-group myResourceGroup --name myAKSCluster --tier premium --k8s-support-plan AKSLongTermSupport

### Expected behavior

The previously defined setting on the AKS cluster was to set the auto upgrade to disabled, however after running the command listed, the auto upgrade channel is set to patch, unadventedly causing that our clusters go down for upgrades.

### Environment Summary

C:\Users\ivaldez>az --version
azure-cli                         2.53.0

core                              2.53.0
telemetry                          1.1.0

Extensions:
aks-preview                      0.5.174
bastion                            0.2.7

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\ivaldez\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Unable to check if your CLI is up-to-date. Check your internet connection.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by FumingZhang** [comment]
@israelvaldez setting the auto upgrade channel to patch is not a client-side behavior. I'll check with the feature team to see if this is expected behavior on the server side.

**Comment by FumingZhang** [comment]
comments from feature owner

> this is expected, we were trying to bind LTS with patch version upgrade, reason is LTS without latest patch seems dumb. 
>  
> but after discussion we remove that bind, but we still carry the default.
>  
> customer can fix the issue by set to different upgrade channel, we won't block it.
