### ISSUE TITLE
Set Upgrade policy to Rolling and configure the rolling upgrade policy during VMSS creation

### ISSUE THREAD

**Issue by mimckitt** [Azure/azure-cli#28439]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az vmss create --upgrade-policy-mode Rolling --rolling-upgrade-policy

### Resource Provider

Microsoft.Compute

### Description of Feature or Work Requested

I am the PM for Upgrade Policies on Virtual Machine Scale Sets. We are working towards Public Preview of Upgrade Policies on VMSS Flex and I am finding a lot of inconsistencies between Portal, REST, PowerShell and CLI. Mostly, the CLI seems to be limited to being able to adjust the upgrade policy settings for VMSS deployments. 

I would like to start the work to get better consistency between these 4 CLI tools. 

This ask is specifically to allow setting the Upgrade Policy for Virtual Machine Scale Sets during VMSS creation using `az vmss create --upgarde-policy-mode Rolling --rolling-upgrade-policy XYZ`

Scenario | Portal | CLI | PowerShell | REST
-- | -- | -- | -- | --
Set   Upgrade policy to Rolling and configure the rolling upgrade policy during   VMSS creation | Yes | No <br><br>     Rolling Upgrade Policy   requires App health extension and extensions cannot be set during VM creation using CLI | Yes | Yes
Set   upgrade policy to Manual during VMSS creation | Yes | Yes | Yes | Yes
Set   upgrade policy to Automatic during VMSS creation | Yes | Yes | Yes | Yes
Update   the upgrade policy to Rolling post VMSS creation | Yes | No      <br><br> The az   vmss update command does not have any parameters to change upgrade policy.   Using –set upgradepolicy=Rolling does not work | Yes     <br><br>  Cannot   enable MaxSurge using update-azVMSS command. Need to use   Set-AzVmssRollingUpgradePolicy first then apply update-azvmss | Yes
Update   the rolling upgrade policy settings | Yes | Yes       <br><br> You can use az vmss update –set upgradePolicy.RollingUpgradePolicySettings.SETTING       <br><br>This   is only allows you to change the upgrade policy settings, not the upgrade   policy itself. | Yes       <br><br>Cannot enable MaxSurge using update-azVMSS command. Need to use   Set-AzVmssRollingUpgradePolicy first then apply update-azvmss | Yes
Update   the Upgrade policy to Manual post VMSS creation | Yes | No     <br><br>  The az   vmss update command does not have any parameters to change upgrade policy.   Using –set upgradepolicy=manual does not work | Yes | Yes
Update   the upgrade policy to Automatic post VMSS creation | Yes | No     <br><br>  The az   vmss update command does not have any parameters to change upgrade policy.   Using –set upgradepolicy=automatic does not work | Yes | Yes
Trigger   a rolling upgrade       (no   way to directly start a rolling upgrade. Need to trigger a generic model   update) | No | No | No | No
Stop   a Rolling Upgrade | Yes | Yes | Yes | Yes
Get   rolling upgrade status | Yes | Yes | Yes | Yes

### Minimum API Version Required

Latest

### Swagger PR link / SDK link

https://learn.microsoft.com/en-us/rest/api/compute/virtual-machine-scale-sets/create-or-update?view=rest-compute-2023-10-02&tabs=HTTP

### Request Example

I don't see any specific rest examples for setting upgrade policy in REST. Here are all the samples available: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-09-01/examples/virtualMachineScaleSetExamples

Here is the link to the Upgrade Policy mode parameters: https://learn.microsoft.com/en-us/rest/api/compute/virtual-machine-scale-sets/create-or-update?view=rest-compute-2023-10-02&tabs=HTTP#upgradepolicy

### Target Date

4/1/2024

### PM Contact

mimckitt

### Engineer Contact

jwa

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yanzhudd** [comment]
Hi @mimckitt,
since there are lots of works need to be done in the next sprint and we have no more effort to develop this feature, is the ETA 04-02 acceptable to you?

**Comment by mimckitt** [comment]
@yanzhudd yes, that would be fine. Thank you! Let me know how I can help. I am more than happy to help provide design docs and input.
