### ISSUE TITLE
Impossible to set --total-retention-time larger than 2556 (7 years), while the portal allows up to 12 years

### ISSUE THREAD

**Issue by shnanostics** [Azure/azure-cli#28437]
### Describe the bug

So, the issue is that the following CLI command

az monitor log-analytics workspace table update 

does not allow more than 7 years of  --total-retention-time,
giving following error:

InvalidArgumentValue: --total-retention-time: Invalid format: '3650' is greater than 2556

The version of the azure cli is:

{
  "azure-cli": "2.57.0",
  "azure-cli-core": "2.57.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {}
}

### Related command

az monitor log-analytics workspace table update 

### Errors

InvalidArgumentValue: --total-retention-time: Invalid format: '3650' is greater than 2556

### Issue script & Debug output

[Thu Feb 22 10:12:10] step@metal ~ $ sudo az monitor log-analytics workspace table update --debug --subscription $subscription --resource-group $rg --workspace-name $log_analytics_workspace_name --name "StorageBlobLogs" --retention-time 730 --total-retention-time 4380
[sudo] password for step:          
cli.knack.cli: Command arguments: ['monitor', 'log-analytics', 'workspace', 'table', 'update', '--debug', '--subscription', 'f0ca78e2-cd9b-4382-aa3b-b9f1b0f0fb15', '--resource-group', 'Vldtn1nnstcs_ClarityDX_Prostate_RG', '--workspace-name', 'vldtn1nnstcs-log-analytics-workspace', '--name', 'StorageBlobLogs', '--retention-time', '730', '--total-retention-time', '4380']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f3be13780e0>, <function OutputProducer.on_global_arguments at 0x7f3be131e200>, <function CLIQuery.on_global_arguments at 0x7f3be1353ce0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'monitor': ['azure.cli.command_modules.monitor', 'azext_amcs']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: monitor                   0.488        26        87
cli.azure.cli.core: Total (1)                 0.488        26        87
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: monitor-control-service      0.003        10        37  /root/.azure/cliextensions/monitor-control-service
cli.azure.cli.core: Total (1)                 0.003        10        37  
cli.azure.cli.core: Loaded 35 groups, 124 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : monitor log-analytics workspace table update
cli.azure.cli.core: Command table: monitor log-analytics workspace table update
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f3be0245940>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/root/.azure/commands/2024-02-22.10-12-55.monitor_log-analytics_workspace_table_update.373953.log'.
az_command_data_logger: command args: monitor log-analytics workspace table update --debug --subscription {} --resource-group {} --workspace-name {} --name {} --retention-time {} --total-retention-time {}
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f3be0288040>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f3be02bdda0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f3be02bdee0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f3be131e2a0>, <function CLIQuery.handle_query_parameter at 0x7f3be1353d80>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f3be02bde40>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=LogAnalyticsManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='/root/.azure/msal_token_cache.json', encrypt=False
cli.azure.cli.core.auth.binary_cache: load: /root/.azure/msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/eebac8a0-1aa8-4127-840e-ac2f3233ac23/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/eebac8a0-1aa8-4127-840e-ac2f3233ac23/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/eebac8a0-1aa8-4127-840e-ac2f3233ac23/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/eebac8a0-1aa8-4127-840e-ac2f3233ac23/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/eebac8a0-1aa8-4127-840e-ac2f3233ac23/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/eebac8a0-1aa8-4127-840e-ac2f3233ac23/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/eebac8a0-1aa8-4127-840e-ac2f3233ac23/kerberos', 'tenant_region_scope': 'NA', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/aaz/_command_ctx.py", line 53, in format_args
    self.args._schema._fmt(ctx=self, value=self.args)
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/aaz/_arg_fmt.py", line 402, in __call__
    raise err from err
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/aaz/_arg_fmt.py", line 399, in __call__
    value[field_name] = field_schema._fmt(ctx, value[field_name])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/aaz/_arg_fmt.py", line 297, in __call__
    raise AAZInvalidArgValueError(
azure.cli.core.aaz.exceptions.AAZInvalidArgValueError: InvalidArgumentValue: --total-retention-time: Invalid format: '4380' is greater than 2556

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 729, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_job
    return cmd_copy.exception_handler(ex)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/command_modules/monitor/_exception_handler.py", line 23, in exception_handler
    raise ex
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 698, in _run_job
    result = cmd_copy(params)
             ^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 334, in __call__
    return self.handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/command_modules/monitor/operations/log_analytics_workspace.py", line 352, in update_log_analytics_workspace_table
    return WorkspaceTableUpdate(cli_ctx=cmd.cli_ctx)(command_args=command_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/aaz/_command.py", line 155, in __call__
    return self._handler(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/command_modules/monitor/aaz/latest/monitor/log_analytics/workspace/table/_update.py", line 31, in _handler
    super()._handler(command_args)
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/aaz/_command.py", line 165, in _handler
    self.ctx.format_args()
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/aaz/_command_ctx.py", line 55, in format_args
    raise InvalidArgumentValueError(str(err))
azure.cli.core.azclierror.InvalidArgumentValueError: InvalidArgumentValue: --total-retention-time: Invalid format: '4380' is greater than 2556

cli.azure.cli.core.azclierror: InvalidArgumentValue: --total-retention-time: Invalid format: '4380' is greater than 2556
az_command_data_logger: InvalidArgumentValue: --total-retention-time: Invalid format: '4380' is greater than 2556
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f3be0245bc0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.791 seconds (init: 0.158, invoke: 0.632)
cli.azure.cli.core.decorators: Suppress exception:
Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/azure/cli/__main__.py", line 62, in <module>
    raise ex
  File "/opt/az/lib/python3.11/site-packages/azure/cli/__main__.py", line 55, in <module>
    sys.exit(exit_code)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/decorators.py", line 79, in _wrapped_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/azure/cli/core/telemetry.py", line 532, in _get_secrets_warning_config
    show_secrets_warning = _get_config().getboolean('clients', 'show_secrets_warning', fallback=None)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/az/lib/python3.11/site-packages/knack/config.py", line 147, in getboolean
    raise ValueError('Not a boolean: {}'.format(val))
ValueError: Not a boolean: None

telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3707 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/opt/az/bin/python3 /opt/az/lib/python3.11/site-packages/azure/cli/telemetry/__init__.py /root/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

The command should be able to set up --total-retention-time up to 4380, similarly as 9in azure portal.

### Environment Summary

azure-cli                         2.57.0

core                              2.57.0
telemetry                          1.1.0

Dependencies:
msal                              1.26.0
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/home/step/.azure/cliextensions'

Python (Linux) 3.11.7 (main, Jan 31 2024, 05:29:49) [GCC 11.4.0]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by AllyW** [comment]
@shnanostics yes, we cli team are already upgrading our log-analytics workspace code recently to the latest api-version of it, which will allow a larger total-retention-time and retention-time. please refer to the linked pr for future releases.

**Comment by shnanostics** [comment]
Ok. Thanks

**Comment by shnanostics** [comment]
Ok. Thanks
