### ISSUE TITLE
az login issue

### ISSUE THREAD

**Issue by cltj** [Azure/azure-cli#28452]
### Describe the bug

After upgrading to wsl2 it seems i cannot use az login command. Could it be a network issue? 

### Related command

az login

### Errors

ERROR: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /organizations/v2.0/.well-known/openid-configuration (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe860094ee0>: Failed to resolve 'login.microsoftonline.com' ([Errno -3] Temporary failure in name resolution)"))

### Issue script & Debug output

Not a script

### Expected behavior

I expect to get a login link

### Environment Summary

❯ az --version
azure-cli                         2.53.1

core                              2.53.1
telemetry                          1.1.0

Dependencies:
msal                              1.26.0
azure-mgmt-resource             23.1.0b2

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jmohanvenkatesh** [comment]
az login issue #28452

**Comment by yonzhan** [comment]
similar issue https://github.com/Azure/azure-cli/issues/21514.
