### ISSUE TITLE
running terraform plan in windows 10 pro but shows unsupported platform error User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy. Supported device platforms are: iOS, Android, Mac, and Windows flavors.

### ISSUE THREAD

**Issue by XiaoYue2-22** [Azure/azure-cli#28455]
### Describe the bug

running terraform plan in windows 10 pro but shows unsupported platform error
C:\test>terraform plan

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: building account: could not acquire access token to parse claims: running Azure CLI: exit status 1: ERROR: AADSTS50005: User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy. Supported device platforms are: iOS, Android, Mac, and Windows flavors. Trace ID: 37aa6e06-04c6-4059-bc87-8e9f87137300 Correlation ID: 1779b0de-6ac2-44d5-b97a-64f69d477f3d Timestamp: 2024-02-26 09:09:47Z
│ Interactive authentication is needed. Please run:
│ az login --scope https://graph.microsoft.com/.default
│
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on providers.tf line 12, in provider "azurerm":
│   12: provider "azurerm" {
│

### Related command

terraform plan

### Errors

╷
│ Error: building account: could not acquire access token to parse claims: running Azure CLI: exit status 1: ERROR: AADSTS50005: User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy. Supported device platforms are: iOS, Android, Mac, and Windows flavors. Trace ID: 37aa6e06-04c6-4059-bc87-8e9f87137300 Correlation ID: 1779b0de-6ac2-44d5-b97a-64f69d477f3d Timestamp: 2024-02-26 09:09:47Z
│ Interactive authentication is needed. Please run:
│ az login --scope https://graph.microsoft.com/.default
│
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on providers.tf line 12, in provider "azurerm":
│   12: provider "azurerm" {

### Issue script & Debug output

see errors

### Expected behavior

should be run successfully

### Environment Summary

azure-cli                         2.57.0

core                              2.57.0
telemetry                          1.1.0

Dependencies:
msal                              1.26.0
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\usernametest\.azure\cliextensions'

Python (Windows) 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

n/a

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yonzhan** [comment]
Please open this issue in terraform repo

**Comment by XiaoYue2-22** [comment]
sure, thanks
