### ISSUE TITLE
[Network] BGP Peering Address should not be settable on any gateway commands

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#2846]
A comment carried over from PR #2751. `az network vnet/local-gateway create/update` commands expose the `bgp_peering_address` property, which is set automatically by the service and not intended to be configurable. 

In this case, this property should be set as ReadOnly in the swagger spec (https://github.com/Azure/azure-rest-api-specs/issues/1115)

**Comment by tjprescott** [comment]
Closing this.

After further discussion, BGP peering address is actually required for local gateways. It remains an optional parameter for vnet-gateway pending resolution of Azure/azure-rest-api-specs#1115 by the service team.

**Comment by Nilambari** [comment]
BgpSettings object is part of both objects:- VirtualNetworkGateway & LocalNetworkGateway, whereas BgpSettings.bgpPeeringAddress is a required fields for creating/updating LocalNetworkGateway and not needed/optional for creating/updating VirtualNetworkGateway.
		As the same object is used two places, we could not make it reaqdonly. Even though customer passes Address for VirtualNetworkGateway, we take care of not passing it to service and read it from service set address after VirtualNetworkGateway is created. Please close this and get back if you have further questions.
