### ISSUE TITLE
Trying to create a AKS cluster - ingress controller for nginx and it says LB IP address is not found...tried in different regions etc.

### ISSUE THREAD

**Issue by pandurp59** [Azure/azure-cli#28460]
### Describe the bug

Tutorial followed: https://learn.microsoft.com/en-us/azure/linux-workloads/createwordpressdeployment/readme

Azure Subscription: 7485a9b6-0996-4265-aa23-5df43acac280

Command tried:  helm upgrade --debug --install --cleanup-on-fail --atomic ingress-nginx ingress-nginx/ingress-nginx \
    --namespace ingress-nginx \
    --create-namespace \
    --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-dns-label-name"=$MY_DNS_LABEL \
    --set controller.service.loadBalancerIP=$MY_STATIC_IP \
    --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"=/healthz \
    --wait --timeout 10m0s

Error: 
ready.go:274: [debug] Service does not have load balancer ingress IP address: ingress-nginx/ingress-nginx-controller
ready.go:274: [debug] Service does not have load balancer ingress IP address: ingress-nginx/ingress-nginx-controller

### Related command

helm upgrade --debug --install --cleanup-on-fail --atomic ingress-nginx ingress-nginx/ingress-nginx \
    --namespace ingress-nginx \
    --create-namespace \
    --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-dns-label-name"=$MY_DNS_LABEL \
    --set controller.service.loadBalancerIP=$MY_STATIC_IP \
    --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"=/healthz \
    --wait --timeout 10m0s

### Errors

helm upgrade --debug --install --cleanup-on-fail --atomic ingress-nginx ingress-nginx/ingress-nginx     --namespace ingress-nginx     --create-namespace     --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-dns-label-name"=$MY_DNS_LABEL     --set controller.service.loadBalancerIP=$MY_STATIC_IP     --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"=/healthz     --wait --timeout 10m0s
history.go:56: [debug] getting history for release ingress-nginx
Release "ingress-nginx" does not exist. Installing it now.
install.go:214: [debug] Original chart version: ""
install.go:231: [debug] CHART PATH: /home/pandu/.cache/helm/repository/ingress-nginx-4.9.1.tgz

client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "ingress-nginx-admission" ServiceAccount
client.go:490: [debug] Ignoring delete failure for "ingress-nginx-admission" /v1, Kind=ServiceAccount: serviceaccounts "ingress-nginx-admission" not found
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 10m0s
client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "ingress-nginx-admission" ClusterRole
client.go:490: [debug] Ignoring delete failure for "ingress-nginx-admission" rbac.authorization.k8s.io/v1, Kind=ClusterRole: clusterroles.rbac.authorization.k8s.io "ingress-nginx-admission" not found
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 10m0s
client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "ingress-nginx-admission" ClusterRoleBinding
client.go:490: [debug] Ignoring delete failure for "ingress-nginx-admission" rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding: clusterrolebindings.rbac.authorization.k8s.io "ingress-nginx-admission" not found
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 10m0s
client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "ingress-nginx-admission" Role
client.go:490: [debug] Ignoring delete failure for "ingress-nginx-admission" rbac.authorization.k8s.io/v1, Kind=Role: roles.rbac.authorization.k8s.io "ingress-nginx-admission" not found
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 10m0s
client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "ingress-nginx-admission" RoleBinding
client.go:490: [debug] Ignoring delete failure for "ingress-nginx-admission" rbac.authorization.k8s.io/v1, Kind=RoleBinding: rolebindings.rbac.authorization.k8s.io "ingress-nginx-admission" not found
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 10m0s
client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "ingress-nginx-admission-create" Job
client.go:490: [debug] Ignoring delete failure for "ingress-nginx-admission-create" batch/v1, Kind=Job: jobs.batch "ingress-nginx-admission-create" not found
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 10m0s
client.go:142: [debug] creating 1 resource(s)
client.go:712: [debug] Watching for changes to Job ingress-nginx-admission-create with timeout of 10m0s
client.go:740: [debug] Add/Modify event for ingress-nginx-admission-create: ADDED
client.go:779: [debug] ingress-nginx-admission-create: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for ingress-nginx-admission-create: MODIFIED
client.go:779: [debug] ingress-nginx-admission-create: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for ingress-nginx-admission-create: MODIFIED
client.go:779: [debug] ingress-nginx-admission-create: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for ingress-nginx-admission-create: MODIFIED
client.go:486: [debug] Starting delete for "ingress-nginx-admission" ServiceAccount
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 10m0s
client.go:486: [debug] Starting delete for "ingress-nginx-admission" ClusterRole
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 10m0s
client.go:486: [debug] Starting delete for "ingress-nginx-admission" ClusterRoleBinding
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 10m0s
client.go:486: [debug] Starting delete for "ingress-nginx-admission" Role
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 10m0s
client.go:486: [debug] Starting delete for "ingress-nginx-admission" RoleBinding
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 10m0s
client.go:486: [debug] Starting delete for "ingress-nginx-admission-create" Job
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 10m0s
client.go:142: [debug] creating 11 resource(s)
wait.go:48: [debug] beginning wait for 11 resources with timeout of 10m0s
ready.go:274: [debug] Service does not have load balancer ingress IP address: ingress-nginx/ingress-nginx-controller
ready.go:274: [debug] Service does not have load balancer ingress IP address: ingress-nginx/ingress-nginx-controller

### Issue script & Debug output

wait.go:48: [debug] beginning wait for 11 resources with timeout of 10m0s
ready.go:274: [debug] Service does not have load balancer ingress IP address: ingress-nginx/ingress-nginx-controller
ready.go:274: [debug] Service does not have load balancer ingress IP address: ingress-nginx/ingress-nginx-controller

### Expected behavior

nginx ingress controller should be created

### Environment Summary

pandu [ ~ ]$ az --version
azure-cli                         2.57.0

core                              2.57.0
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
ml                                2.22.0
ssh                                2.0.2

Dependencies:
msal                              1.26.0
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.9'
Extensions directory '/home/pandu/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.14 (main, Oct 12 2023, 19:48:32) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by FumingZhang** [comment]
The error is not related to the aks command group in azure-cli. Please seek help from https://github.com/Azure/AKS.

**Comment by pandurp59** [comment]
Hello Team,

Thanks for looking into this issue. Ideally would have liked the issued to be routed to another group rather than marking it as completed.


Thanks and Regards,
Pandu
________________________________
