### ISSUE TITLE
az cli with netappfiles forces to use netappfiles-preview and fails as "netappfiles misspelled"

### ISSUE THREAD

**Issue by abhinovntap** [Azure/azure-cli#28474]
### Describe the bug

While creating python(pytest) scripts to run AZ CLI commands to create volumes in ANF; I see the failures like below:
`error_msg  = "'netappfiles' is misspelled or not recognized by the system."

The command works fine if run on the shell, but fails only when run inside a pytest testcase and halts mid-way asking to install netappfiles-preview extension.

### Related command

`az netappfiles volume create -g "my-rg" --account-name "my-na" --pool-name "myeastus-ultra" --name "vol125" -l "eastus" --service-level "Ultra" --usage-threshold 125 --file-path "vol125" --vnet "my-vnet" --subnet "my-subnet" --protocol-types "NFSv3"`

### Errors

`ERROR    cli.azure.cli.core.azclierror:azlogging.py:212 'netappfiles' is misspelled or not recognized by the system.
ERROR    az_command_data_logger:azlogging.py:213 'netappfiles' is misspelled or not recognized by the system.`

### Issue script & Debug output

`cmd = ["netappfiles", "volume", "create", "-g", resource_group, "--account-name", netapp_account, "--pool-name", capacity_pool, "--name", volume_name, "-l", location, "--service-level", service_level, "--usage-threshold", size, "--file-path", volume_name, "--vnet", vnet, "--subnet", subnet, "--protocol-types","NFSv3" ]
self.az_cli.invoke(cmd)
response = self.az_cli.result.result`

### Expected behavior

The volume create should run as is given any python venv or just over CLI. Also it should not force users to install preview extensions.

### Environment Summary

{
  "azure-cli": "2.57.0",
  "azure-cli-core": "2.57.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {}
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by audunn** [comment]
@abhinov-netapp Not sure what is going on here,  NetAppFiles CLI module is part of the Azure CLI and as such should be availble as part of intallation of Azure CLI.  Can you share more on how the Azure CLI is soured and referenced in your script and a bit more on the output and erros you are seeing that might give context.

**Comment by audunn** [comment]
Stale issue
