### ISSUE TITLE
sig image-version create managed-image parameter should map to new VM backend field

### ISSUE THREAD

**Issue by tiregan** [Azure/azure-cli#28488]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az sig image-version create

### Resource Provider

Microsoft.Compute

### Description of Feature or Work Requested

Currently, the --managed-image parameter of the az sig image-version create command maps to the properties.storageprofile.source.id field.  We need it to map to the properties.storageprofile.source.virtualMachineId field ONLY when the source provided is a VM id.

### Minimum API Version Required

2023_07_03

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/27518

### Request Example

Example of how it would be mapped today:
{
  "name": "1.0.0",
  "location": "South Central US STG",
  "properties": {
    "storageProfile": {
      "source": {
        "id": "{virtual machine id}"
      }
    }
  }
}

The new mapping:
{
  "name": "1.0.0",
  "location": "South Central US STG",
  "properties": {
    "storageProfile": {
      "source": {
        "virtualMachineId": "{virtual machine id}"
      }
    }
  }
}

Not we should only use the virtualMachineId if the id is a virtual machine.  If the id is a managed image then we should continue to use the old field.

### Target Date

As soon as possible

### PM Contact

sandeep.raichura@microsoft.com

### Engineer Contact

tiregan, jerch, kagarwal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
