### ISSUE TITLE
Enable Auto Image Upgrade while Creating new VMSS - CLI Change Request

### ISSUE THREAD

**Issue by maulikshah23** [Azure/azure-cli#28493]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az vmss create --name myScaleSet --resource-group myResourceGroup --set UpgradePolicy.AutomaticOSUpgradePolicy.EnableAutomaticOSUpgrade=true

### Resource Provider

Compute Resource Provider

### Description of Feature or Work Requested

Allow customers to enable Auto OS Image Upgrades on their VM Scale Sets for 1P Gallery using CLI. This capability is already available on Powershell and API. The 1P Gallery is created as part of Project Standard to ensure 1P assets have an improved security posture. In order for customers to migrate to the gallery they need to enable Auto OS Image Upgrades (https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-automatic-upgrade?toc=%2fazure%2fvirtual-machines%2ftoc.json).

### Minimum API Version Required

Use Compute API version 2018-10-01 or higher

### Swagger PR link / SDK link

https://learn.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#az-vmss-create

### Target Date

2024-04-30

### PM Contact

Maulik Shah

### Engineer Contact

Deepali Gupta

### Additional context

This feature is required for the 1P Image Gallery as well as for other customers that use the Auto OS Image Upgrade capability to remain secured.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
