### ISSUE TITLE
Running a function app via dotnet test with 64 bit version of az cli errors with: "Access token could not be acquired 'az' is not recognized as an internal or external command"

### ISSUE THREAD

**Issue by spiraljacobs** [Azure/azure-cli#28498]
### Describe the bug

The application is a dotnet core 3.1 function application.

The execution of the specflow functional tests via 'dotnet test' works perfectly when the 32 bit version of the Azure CLI is installed, but failed with: "Access token could not be acquired 'az' is not recognized as an internal or external command" when the 64 bit is installed and the 32 bit is removed.  

'az' is recognized if I type it in the command line, 'az --version' works.

The 64 bit version of the Azure CLI was installed via Powershell:
`$ProgressPreference = 'SilentlyContinue'; Invoke-WebRequest -Uri https://aka.ms/installazurecliwindowsx64 -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; Remove-Item .\AzureCLI.msi `

The code in question is using the AzureServiceTokenProvider.  I've forced it to only use the AzureCli, as that's the intended execution in the pipeline.  If I run locally without the connection string indicating runas=Developer and DeveloperTool = AzureCli, it will work, but it will be using my Visual Studio connection to azure, _not_ the CLI.

               
```
               var azureServiceTokenProvider = new AzureServiceTokenProvider("runAs = Developer; DeveloperTool = AzureCli;");
                var keyVaultClient = new KeyVaultClient(
                                                        new KeyVaultClient.AuthenticationCallback(
                                                                                                  azureServiceTokenProvider.KeyVaultTokenCallback));

                configurationBuilder.AddAzureKeyVault(configuration["KeyVaultUrl"],
                                                      keyVaultClient,
                                                      new DefaultKeyVaultSecretManager());
```

It appears as though the AzureServiceTokenProvider is attempting to _only_ use the location of the 32 bit CLI.  If I create a symlink from the 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2' to 'C:\Program Files\Microsoft SDKs\Azure\CLI2' like so:

mklink /J "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\" "C:\Program Files\Microsoft SDKs\Azure\CLI2\"

 the error does not occur and the application is able to find and use the AZ CLI properly.

I would like to not have to make a symlink and have this just work correctly with the 64 bit version of the CLI.

The path to the 64 bit version of the CLI is also on my system PATH.

### Related command

      
```
               var azureServiceTokenProvider = new AzureServiceTokenProvider("runAs = Developer; DeveloperTool = AzureCli;");
                var keyVaultClient = new KeyVaultClient(
                                                        new KeyVaultClient.AuthenticationCallback(
                                                                                                  azureServiceTokenProvider.KeyVaultTokenCallback));

                configurationBuilder.AddAzureKeyVault(configuration["KeyVaultUrl"],
                                                      keyVaultClient,
                                                      new DefaultKeyVaultSecretManager());
```

### Errors

 Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. 'az' is not recognized as an internal or external command,

### Issue script & Debug output

see above for code snippet:

### Expected behavior

The tests run and the error " Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. 'az' is not recognized as an internal or external command," does not show, just as it does in the 32 bit version of the CLI.

### Environment Summary

azure-cli                         2.57.0

core                              2.57.0
telemetry                          1.1.0

Dependencies:
msal                              1.26.0
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\me\ .azure\cliextensions'

Python (Windows) 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by spiraljacobs** [comment]
Closing, as upgrading the transitive package Microsoft.Azure.Services.AppAuthentication to latest fixed the issue and everything working correctly now.
