### ISSUE TITLE
Add --quiet option for LRO to prevent output to stderr  

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#285]
az resource group delete -n demo700 2>/dev/null &
should become
az resource group delete -n demo700 --quiet &

**Comment by tjprescott** [comment]
@derekbekoe @JasonRShaver since we now no longer output anything for LRO, can this be closed?

**Comment by derekbekoe** [comment]
We still output the 'starting ...' message to stderr.
But yes I think this can be closed.
