### ISSUE TITLE
`test_batch_general_arm_cmd` randomly fails

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#28500]
https://dev.azure.com/azclitools/public/_build/results?buildId=135710&view=logs&j=e3d58f38-f120-52d4-9d7a-9847591da328&t=95a8677a-ae64-591e-54ce-dbe38e361b97

```
        self.cmd('batch account login -g {rg} -n {acc}').assert_with_checks(self.is_empty())
        self.assertEqual(self.cli_ctx.config.get('batch', 'auth_mode'), 'aad')
        self.assertEqual(self.cli_ctx.config.get('batch', 'account'), self.kwargs['acc'])
    
        self.cmd('batch account login -g {rg} -n {acc} --shared-key-auth').assert_with_checks(self.is_empty())
        self.assertEqual(self.cli_ctx.config.get('batch', 'auth_mode'), 'shared_key')
>       self.assertEqual(self.cli_ctx.config.get('batch', 'account'), self.kwargs['acc'])
E       AssertionError: 'clibatchtestacct000002' != 'clibatchtestacct000003'
E       - clibatchtestacct000002
E       ?                      ^
E       + clibatchtestacct000003
E       ?                      ^

/opt/az/lib/python3.11/site-packages/azure/cli/command_modules/batch/tests/latest/test_batch_mgmt_commands.py:90: AssertionError
------------- generated xml file: /azure_cli_test_result/batch.xml -------------
=========================== short test summary info ============================
FAILED tests/latest/test_batch_mgmt_commands.py::BatchMgmtScenarioTests::test_batch_general_arm_cmd
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
I think this test: `test_batch_general_arm_cmd` is interfering with `test_batch_byos_account_cmd` in multiprocessing.

`clibatchtestacct000002` is in https://github.com/Azure/azure-cli/blob/807e336e94f22ccf534cba872456a34d20867169/src/azure-cli/azure/cli/command_modules/batch/tests/latest/recordings/test_batch_byos_account_cmd.yaml

They use `login` or `account set` to switch account and cause conflict.

**Comment by jiasli** [comment]
> They use `login` or `account set` to switch account and cause conflict.

Where is the source code?

**Comment by jiasli** [comment]
Another error happened today:

https://dev.azure.com/azclitools/public/_build/results?buildId=136380&view=logs&j=2e7bfaf9-dede-58e4-b583-d6c0427bb4f3&t=9f12ab83-9a55-5b5a-cb22-48963a35b709

```
        self.cmd('batch account login -g {rg} -n {acc}').assert_with_checks(self.is_empty())
        self.assertEqual(self.cli_ctx.config.get('batch', 'auth_mode'), 'aad')
        self.assertEqual(self.cli_ctx.config.get('batch', 'account'), self.kwargs['acc'])
    
        self.cmd('batch account login -g {rg} -n {acc} --shared-key-auth').assert_with_checks(self.is_empty())
>       self.assertEqual(self.cli_ctx.config.get('batch', 'auth_mode'), 'shared_key')
E       AssertionError: 'aad' != 'shared_key'
E       - aad
E       + shared_key

/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/batch/tests/latest/test_batch_mgmt_commands.py:89: AssertionError
------------- generated xml file: /azure_cli_test_result/batch.xml -------------
=========================== short test summary info ============================
FAILED tests/latest/test_batch_mgmt_commands.py::BatchMgmtScenarioTests::test_batch_general_arm_cmd
```

**Comment by bebound** [comment]
> > They use `login` or `account set` to switch account and cause conflict.
> 
> Where is the source code?

https://github.com/Azure/azure-cli/blob/c2484454166a0f237be48b8e259533207eac1854/src/azure-cli/azure/cli/command_modules/batch/tests/latest/test_batch_mgmt_commands.py#L61

https://github.com/Azure/azure-cli/blob/c2484454166a0f237be48b8e259533207eac1854/src/azure-cli/azure/cli/command_modules/batch/tests/latest/test_batch_mgmt_commands.py#L88

https://github.com/Azure/azure-cli/blob/807e336e94f22ccf534cba872456a34d20867169/src/azure-cli/azure/cli/command_modules/batch/tests/latest/test_batch_mgmt_commands.py#L384-L386

**Comment by jiasli** [comment]
So they are `az batch account login` and `az batch account set`, not `az login` and `az account set`. I confused them.
