### ISSUE TITLE
Azure Virtual Network Manager - User Defined Routing (Public Preview)

### ISSUE THREAD

**Issue by jbgorthy** [Azure/azure-cli#28505]
### Preconditions
(We have not needed python sdk in the past, please let jaredgorthy@microsoft.com know if this has changed for virtual-network-manager extension).
- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

All CRUD commands for: _az network manager routing-config_
All CRUD commands for: _az network manager routing-config rule-collection_
All CRUD commands for: _az network manager routing-config rule-collection rule_
Ability to commit a routing config type via: _az network manager post-commit --commit-type "Routing"_
Ability to create/update a routing config type via: _az network manager create --scope-accesses "Routing"_

### Resource Provider

Microsoft.Network/networkManagers

### Description of Feature or Work Requested

Azure virtual network manager is a resource which applies configurations to virtual networks at-scale. We already have CLI support for our Connectivity and SecurityAdmin configurations. We now have a new configuration for Routing, which follows the same structure as SecurityAdmin (Configuration->RuleCollection->Rule), so I'm hoping some code can be reused in the CLI extension. 

The three new nested resource types can be found within https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/preview/2023-03-01-preview/networkManagerRoutingConfiguration.json. The network manager should also be able to select this 'Routing' type when creating/updating the network manager via 'networkManagerScopeAccesses' and during commit via 'commitType'.

This feature is in public preview, so we would want it released behind some preview virtual-network-manager extension version.

### Minimum API Version Required

2023-03-01-preview is the only API version that should be used for this feature.

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/tree/main/specification/network/resource-manager/Microsoft.Network/preview/2023-03-01-preview

### Request Example

https://github.com/Azure/azure-rest-api-specs/tree/main/specification/network/resource-manager/Microsoft.Network/preview/2023-03-01-preview/examples

### Target Date

2023/04/01

### PM Contact

jayli@microsoft.com

### Engineer Contact

jaredgorthy@microsoft.com, ankursood@microsoft.com

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
