### ISSUE TITLE
az graph query -q "project id" -> unrecognized arguments: id

### ISSUE THREAD

**Issue by ikiris04** [Azure/azure-cli#28517]
### Describe the bug

On my RHEL 8.9 VM, I have az cli and the resource-graph extension installed.
az graph query -q "project id" is resulting in unrecognized arguments: id

It's not honoring single quotes, double quotes or variables and parsing all words as an 

### Related command

az graph query -q "project id"

### Errors

unrecognized arguments: id

### Issue script & Debug output

az graph query -q "project id"

 az graph query -q "project id" --debug
cli.knack.cli: Command arguments: ['graph', 'query', '-q', 'project', 'id', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fa783945430>, <function OutputProducer.on_global_arguments at 0x7fa783660040>, <function CLIQuery.on_global_arguments at 0x7fa7833f75e0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'graph': ['azext_resourcegraph']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: resource-graph            0.003         2         5  /users-xxxx/.azure/cliextensions/resource-graph
cli.azure.cli.core: Total (1)                 0.003         2         5  
cli.azure.cli.core: Loaded 2 groups, 5 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : graph query
cli.azure.cli.core: Command table: graph query
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fa77fb54dc0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/users-xxxx/.azure/commands/2024-03-07.00-11-57.graph_query.2182129.log'.
az_command_data_logger: command args: graph query -q {} {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fa77fafe9d0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7fa77fb269d0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7fa77fac8820>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
urllib3.connectionpool: Starting new HTTPS connection (1): app.aladdin.microsoft.com:443
urllib3.connectionpool: https://app.aladdin.microsoft.com:443 "GET /api/v1.0/suggestions?query=%7B%22command%22%3A+%22graph+query%22%2C+%22parameters%22%3A+%22%22%7D&clientType=AzureCli&context=%7B%22versionNumber%22%3A+%222.58.0%22%2C+%22errorType%22%3A+%22UnrecognizedArguments%22%2C+%22correlationId%22%3A+%227ec7949b-c17b-40e1-937a-c50d9cc1d2d3%22%2C+%22eventId%22%3A+%22cdc34c96-1a05-4a48-9d09-d83bb1be5199%22%7D HTTP/1.1" 200 None
cli.azure.cli.core.azclierror: NoneType: None

cli.azure.cli.core.azclierror: unrecognized arguments: id
az_command_data_logger: unrecognized arguments: id

Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fa77fb55040>]
az_command_data_logger: exit code: 2
cli.__main__: Command ran in 0.462 seconds (init: 0.181, invoke: 0.281)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3566 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/local/bin/python3.9 /usr/lib64/az/lib/python3.9/site-packages/azure/cli/telemetry/__init__.py /users-xxxx/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

query results are shown

### Environment Summary

 az --version
azure-cli                         2.58.0

core                              2.58.0
telemetry                          1.1.0

Extensions:
resource-graph                     2.1.0

Dependencies:
msal                              1.26.0
azure-mgmt-resource             23.1.0b2

Python location '/usr/local/bin/python3.9'
Extensions directory '/users-XXX/.azure/cliextensions'

Python (Linux) 3.9.8 (main, Jul  5 2023, 22:37:22) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-18)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by ikiris04** [comment]
> Thank you for opening this issue, we will look into it.

Thanks, just added the debug output

**Comment by ikiris04** [comment]
Closing, I found that we had an az wrapper that was used to workaorund some python issues. using the command directly worked as expected.
