### ISSUE TITLE
Progress report of `az storage blob upload`

### ISSUE THREAD

**Issue by elibarzilay** [Azure/azure-cli#2852]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  

`apt-get`

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  

    $ az --version
    azure-cli (2.0.1)
    
    acs (2.0.1)
    appservice (0.1.1b6)
    batch (0.1.1b5)
    cloud (2.0.0)
    component (2.0.0)
    configure (2.0.1)
    container (0.1.1b4)
    core (2.0.1)
    documentdb (0.1.1b2)
    feedback (2.0.0)
    find (0.0.1b1)
    iot (0.1.1b3)
    keyvault (0.1.1b6)
    network (2.0.1)
    nspkg (2.0.0)
    profile (2.0.1)
    redis (0.1.1b3)
    resource (2.0.1)
    role (2.0.0)
    sql (0.1.1b6)
    storage (2.0.0)
    vm (2.0.1)
    
    Python (Linux) 2.7.12 (default, Nov 19 2016, 06:48:10) 
    [GCC 5.4.0 20160609]

**OS Version:** What OS and version are you using?  

Linux: `Ubuntu 16.04.2 LTS`

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  

`bash`

---

### Description

Running `az storage blob upload` shows a `Percent complete` progress report, and it gets printed to stderr.  This is fine for interactive use, but from a script I want to hide that output (since including it in build logfiles will make the logs messy).  I don't want to hide/divert stderr because if there were errors, then they *should* be included in the log, and there is no command-line argument that I see that can supress that error.

It would be much better to show the progress output on stdout instead, and even better to also include a flag to supress that output, similar to other network tools like `curl`, `wget`, `rsync`, etc.

**Comment by derekbekoe** [comment]
Related to https://github.com/Azure/azure-cli/issues/987

**Comment by troydai** [comment]
Thanks for the feedback @elibarzilay. We will consider different options to improve the progress indicator.

**Comment by elibarzilay** [comment]
Note that one improvement that is unrelated to new options is to display the progress output on stdout.

**Comment by tjprescott** [comment]
I would think we could also simply check for interactive use and if not, don't print the progress.

**Comment by elibarzilay** [comment]
@tjprescott, +1 --- it's common to print such output only if stdout is a tty.

**Comment by williexu** [comment]
@elibarzilay this has been addressed with https://github.com/Azure/azure-cli/commit/71f0c703ddea462f96891ba8f402f964cfdba5d7
Simply use the `--no-progress` flag to suppress the progress output.
