### ISSUE TITLE
cannot pip install azure-cli [portalocker conflicting dependencies]

### ISSUE THREAD

**Issue by ryancrawcour** [Azure/azure-cli#28536]
### Describe the bug

I cannot pip-install azure-cli on my Windows 11 development machine

### Related command

pip-install azure-cli 

### Errors

ERROR: Cannot install azure-cli-telemetry because these package versions have conflicting dependencies.

### Issue script & Debug output

C:\Users\ryanc> pip install azure-cli --upgrade
Collecting azure-cli
  Using cached azure_cli-2.58.0-py3-none-any.whl.metadata (8.4 kB)
Collecting antlr4-python3-runtime~=4.13.1 (from azure-cli)
  Using cached antlr4_python3_runtime-4.13.1-py3-none-any.whl.metadata (304 bytes)
Collecting azure-appconfiguration~=1.1.1 (from azure-cli)
  Using cached azure_appconfiguration-1.1.1-py2.py3-none-any.whl.metadata (15 kB)
Collecting azure-batch~=14.1.0 (from azure-cli)
  Using cached azure_batch-14.1.0-py3-none-any.whl.metadata (21 kB)
Collecting azure-cli-core==2.58.0 (from azure-cli)
  Using cached azure_cli_core-2.58.0-py3-none-any.whl.metadata (1.7 kB)
Collecting azure-cosmos>=3.0.2,~=3.0 (from azure-cli)
  Using cached azure_cosmos-3.2.0-py2.py3-none-any.whl.metadata (22 kB)
Collecting azure-data-tables==12.4.0 (from azure-cli)
  Using cached azure_data_tables-12.4.0-py3-none-any.whl.metadata (31 kB)
Collecting azure-datalake-store~=0.0.49 (from azure-cli)
  Using cached azure_datalake_store-0.0.53-py2.py3-none-any.whl.metadata (19 kB)
Collecting azure-graphrbac~=0.60.0 (from azure-cli)
  Using cached azure_graphrbac-0.60.0-py2.py3-none-any.whl.metadata (10 kB)
Collecting azure-keyvault-administration==4.4.0b2 (from azure-cli)
  Using cached azure_keyvault_administration-4.4.0b2-py3-none-any.whl.metadata (30 kB)
Collecting azure-keyvault-certificates==4.7.0 (from azure-cli)
  Using cached azure_keyvault_certificates-4.7.0-py3-none-any.whl.metadata (34 kB)
Collecting azure-keyvault-keys==4.9.0b3 (from azure-cli)
  Using cached azure_keyvault_keys-4.9.0b3-py3-none-any.whl.metadata (46 kB)
Collecting azure-keyvault-secrets==4.7.0 (from azure-cli)
  Using cached azure_keyvault_secrets-4.7.0-py3-none-any.whl.metadata (28 kB)
Collecting azure-mgmt-advisor==9.0.0 (from azure-cli)
  Using cached azure_mgmt_advisor-9.0.0-py2.py3-none-any.whl.metadata (8.6 kB)
Collecting azure-mgmt-apimanagement==4.0.0 (from azure-cli)
  Using cached azure_mgmt_apimanagement-4.0.0-py3-none-any.whl.metadata (24 kB)
Collecting azure-mgmt-appconfiguration==3.0.0 (from azure-cli)
  Using cached azure_mgmt_appconfiguration-3.0.0-py3-none-any.whl.metadata (9.3 kB)
Collecting azure-mgmt-appcontainers==2.0.0 (from azure-cli)
  Using cached azure_mgmt_appcontainers-2.0.0-py3-none-any.whl.metadata (19 kB)
Collecting azure-mgmt-applicationinsights~=1.0.0 (from azure-cli)
  Using cached azure_mgmt_applicationinsights-1.0.0-py2.py3-none-any.whl.metadata (11 kB)
Collecting azure-mgmt-authorization~=4.0.0 (from azure-cli)
  Using cached azure_mgmt_authorization-4.0.0-py3-none-any.whl.metadata (18 kB)
Collecting azure-mgmt-batchai==7.0.0b1 (from azure-cli)
  Using cached azure_mgmt_batchai-7.0.0b1-py2.py3-none-any.whl.metadata (8.9 kB)
Collecting azure-mgmt-batch~=17.2.0 (from azure-cli)
  Using cached azure_mgmt_batch-17.2.0-py3-none-any.whl.metadata (19 kB)
Collecting azure-mgmt-billing==6.0.0 (from azure-cli)
  Using cached azure_mgmt_billing-6.0.0-py2.py3-none-any.whl.metadata (7.5 kB)
Collecting azure-mgmt-botservice~=2.0.0b3 (from azure-cli)
  Using cached azure_mgmt_botservice-2.0.0-py3-none-any.whl.metadata (18 kB)
Collecting azure-mgmt-cdn==12.0.0 (from azure-cli)
  Using cached azure_mgmt_cdn-12.0.0-py3-none-any.whl.metadata (25 kB)
Collecting azure-mgmt-cognitiveservices~=13.5.0 (from azure-cli)
  Using cached azure_mgmt_cognitiveservices-13.5.0-py3-none-any.whl.metadata (18 kB)
Collecting azure-mgmt-compute~=30.4.0 (from azure-cli)
  Using cached azure_mgmt_compute-30.4.0-py3-none-any.whl.metadata (66 kB)
Collecting azure-mgmt-containerinstance==10.1.0 (from azure-cli)
  Using cached azure_mgmt_containerinstance-10.1.0-py3-none-any.whl.metadata (13 kB)
Collecting azure-mgmt-containerregistry==10.3.0 (from azure-cli)
  Using cached azure_mgmt_containerregistry-10.3.0-py3-none-any.whl.metadata (23 kB)
Collecting azure-mgmt-containerservice~=29.1.0 (from azure-cli)
  Using cached azure_mgmt_containerservice-29.1.0-py3-none-any.whl.metadata (49 kB)
Collecting azure-mgmt-cosmosdb==9.4.0 (from azure-cli)
  Using cached azure_mgmt_cosmosdb-9.4.0-py3-none-any.whl.metadata (100 kB)
Collecting azure-mgmt-databoxedge~=1.0.0 (from azure-cli)
  Using cached azure_mgmt_databoxedge-1.0.0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting azure-mgmt-datalake-store~=0.5.0 (from azure-cli)
  Using cached azure_mgmt_datalake_store-0.5.0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting azure-mgmt-datamigration~=10.0.0 (from azure-cli)
  Using cached azure_mgmt_datamigration-10.0.0-py2.py3-none-any.whl.metadata (13 kB)
Collecting azure-mgmt-devtestlabs~=4.0 (from azure-cli)
  Using cached azure_mgmt_devtestlabs-4.0.0-py2.py3-none-any.whl.metadata (10 kB)
Collecting azure-mgmt-dns~=8.0.0 (from azure-cli)
  Using cached azure_mgmt_dns-8.0.0-py2.py3-none-any.whl.metadata (8.9 kB)
Collecting azure-mgmt-eventgrid==10.2.0b2 (from azure-cli)
  Using cached azure_mgmt_eventgrid-10.2.0b2-py3-none-any.whl.metadata (23 kB)
Collecting azure-mgmt-eventhub~=10.1.0 (from azure-cli)
  Using cached azure_mgmt_eventhub-10.1.0-py3-none-any.whl.metadata (15 kB)
Collecting azure-mgmt-extendedlocation==1.0.0b2 (from azure-cli)
  Using cached azure_mgmt_extendedlocation-1.0.0b2-py2.py3-none-any.whl.metadata (2.4 kB)
Collecting azure-mgmt-hdinsight~=9.0.0 (from azure-cli)
  Using cached azure_mgmt_hdinsight-9.0.0-py2.py3-none-any.whl.metadata (12 kB)
Collecting azure-mgmt-imagebuilder~=1.3.0 (from azure-cli)
  Using cached azure_mgmt_imagebuilder-1.3.0-py3-none-any.whl.metadata (9.4 kB)
Collecting azure-mgmt-iotcentral~=10.0.0b1 (from azure-cli)
  Using cached azure_mgmt_iotcentral-10.0.0b2-py3-none-any.whl.metadata (8.3 kB)
Collecting azure-mgmt-iothub==3.0.0 (from azure-cli)
  Using cached azure_mgmt_iothub-3.0.0-py3-none-any.whl.metadata (16 kB)
Collecting azure-mgmt-iothubprovisioningservices==1.1.0 (from azure-cli)
  Using cached azure_mgmt_iothubprovisioningservices-1.1.0-py3-none-any.whl.metadata (7.3 kB)
Collecting azure-mgmt-keyvault==10.3.0 (from azure-cli)
  Using cached azure_mgmt_keyvault-10.3.0-py3-none-any.whl.metadata (15 kB)
Collecting azure-mgmt-kusto~=0.3.0 (from azure-cli)
  Using cached azure_mgmt_kusto-0.3.0-py2.py3-none-any.whl.metadata (4.7 kB)
Collecting azure-mgmt-loganalytics==13.0.0b4 (from azure-cli)
  Using cached azure_mgmt_loganalytics-13.0.0b4-py3-none-any.whl.metadata (17 kB)
Collecting azure-mgmt-managedservices~=1.0 (from azure-cli)
  Using cached azure_mgmt_managedservices-1.0.0-py2.py3-none-any.whl.metadata (2.2 kB)
Collecting azure-mgmt-managementgroups~=1.0.0 (from azure-cli)
  Using cached azure_mgmt_managementgroups-1.0.0-py2.py3-none-any.whl.metadata (5.6 kB)
Collecting azure-mgmt-maps~=2.0.0 (from azure-cli)
  Using cached azure_mgmt_maps-2.0.0-py2.py3-none-any.whl.metadata (5.6 kB)
Collecting azure-mgmt-marketplaceordering==1.1.0 (from azure-cli)
  Using cached azure_mgmt_marketplaceordering-1.1.0-py2.py3-none-any.whl.metadata (7.5 kB)
Collecting azure-mgmt-media~=9.0 (from azure-cli)
  Using cached azure_mgmt_media-9.0.0-py3-none-any.whl.metadata (14 kB)
Collecting azure-mgmt-monitor~=5.0.0 (from azure-cli)
  Using cached azure_mgmt_monitor-5.0.1-py3-none-any.whl.metadata (24 kB)
Collecting azure-mgmt-msi~=7.0.0 (from azure-cli)
  Using cached azure_mgmt_msi-7.0.0-py3-none-any.whl.metadata (8.9 kB)
Collecting azure-mgmt-netapp~=10.1.0 (from azure-cli)
  Using cached azure_mgmt_netapp-10.1.0-py3-none-any.whl.metadata (21 kB)
Collecting azure-mgmt-policyinsights==1.1.0b4 (from azure-cli)
  Using cached azure_mgmt_policyinsights-1.1.0b4-py3-none-any.whl.metadata (11 kB)
Collecting azure-mgmt-privatedns~=1.0.0 (from azure-cli)
  Using cached azure_mgmt_privatedns-1.0.0-py2.py3-none-any.whl.metadata (4.9 kB)
Collecting azure-mgmt-rdbms~=10.2.0b12 (from azure-cli)
  Using cached azure_mgmt_rdbms-10.2.0b15-py3-none-any.whl.metadata (30 kB)
Collecting azure-mgmt-recoveryservicesbackup~=8.0.0 (from azure-cli)
  Using cached azure_mgmt_recoveryservicesbackup-8.0.0-py3-none-any.whl.metadata (33 kB)
Collecting azure-mgmt-recoveryservices~=2.5.0 (from azure-cli)
  Using cached azure_mgmt_recoveryservices-2.5.0-py3-none-any.whl.metadata (13 kB)
Collecting azure-mgmt-redis~=14.3.0 (from azure-cli)
  Using cached azure_mgmt_redis-14.3.0-py3-none-any.whl.metadata (16 kB)
Collecting azure-mgmt-redhatopenshift~=1.4.0 (from azure-cli)
  Using cached azure_mgmt_redhatopenshift-1.4.0-py3-none-any.whl.metadata (6.9 kB)
Collecting azure-mgmt-resource==23.1.0b2 (from azure-cli)
  Using cached azure_mgmt_resource-23.1.0b2-py3-none-any.whl.metadata (36 kB)
Collecting azure-mgmt-search~=9.0 (from azure-cli)
  Using cached azure_mgmt_search-9.1.0-py3-none-any.whl.metadata (10 kB)
Collecting azure-mgmt-security==5.0.0 (from azure-cli)
  Using cached azure_mgmt_security-5.0.0-py3-none-any.whl.metadata (31 kB)
Collecting azure-mgmt-servicebus~=8.2.0 (from azure-cli)
  Using cached azure_mgmt_servicebus-8.2.0-py3-none-any.whl.metadata (15 kB)
Collecting azure-mgmt-servicefabricmanagedclusters~=1.0.0 (from azure-cli)
  Using cached azure_mgmt_servicefabricmanagedclusters-1.0.0-py2.py3-none-any.whl.metadata (3.4 kB)
Collecting azure-mgmt-servicelinker==1.2.0b1 (from azure-cli)
  Using cached azure_mgmt_servicelinker-1.2.0b1-py3-none-any.whl.metadata (5.4 kB)
Collecting azure-mgmt-servicefabric~=1.0.0 (from azure-cli)
  Using cached azure_mgmt_servicefabric-1.0.0-py2.py3-none-any.whl.metadata (10 kB)
Collecting azure-mgmt-signalr==2.0.0b1 (from azure-cli)
  Using cached azure_mgmt_signalr-2.0.0b1-py3-none-any.whl.metadata (9.9 kB)
Collecting azure-mgmt-sqlvirtualmachine==1.0.0b5 (from azure-cli)
  Using cached azure_mgmt_sqlvirtualmachine-1.0.0b5-py3-none-any.whl.metadata (8.8 kB)
Collecting azure-mgmt-sql==4.0.0b15 (from azure-cli)
  Using cached azure_mgmt_sql-4.0.0b15-py3-none-any.whl.metadata (62 kB)
Collecting azure-mgmt-storage==21.1.0 (from azure-cli)
  Using cached azure_mgmt_storage-21.1.0-py3-none-any.whl.metadata (29 kB)
Collecting azure-mgmt-synapse==2.1.0b5 (from azure-cli)
  Using cached azure_mgmt_synapse-2.1.0b5-py3-none-any.whl.metadata (15 kB)
Collecting azure-mgmt-trafficmanager~=1.0.0 (from azure-cli)
  Using cached azure_mgmt_trafficmanager-1.0.0-py3-none-any.whl.metadata (7.8 kB)
Collecting azure-mgmt-web==7.2.0 (from azure-cli)
  Using cached azure_mgmt_web-7.2.0-py3-none-any.whl.metadata (87 kB)
Collecting azure-monitor-query==1.2.0 (from azure-cli)
  Using cached azure_monitor_query-1.2.0-py3-none-any.whl.metadata (32 kB)
Collecting azure-multiapi-storage~=1.2.0 (from azure-cli)
  Using cached azure_multiapi_storage-1.2.0-py2.py3-none-any.whl.metadata (6.4 kB)
Collecting azure-storage-common~=1.4 (from azure-cli)
  Using cached azure_storage_common-1.4.2-py2.py3-none-any.whl.metadata (8.1 kB)
Collecting azure-synapse-accesscontrol~=0.5.0 (from azure-cli)
  Using cached azure_synapse_accesscontrol-0.5.0-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting azure-synapse-artifacts~=0.18.0 (from azure-cli)
  Using cached azure_synapse_artifacts-0.18.0-py3-none-any.whl.metadata (14 kB)
Collecting azure-synapse-managedprivateendpoints~=0.4.0 (from azure-cli)
  Using cached azure_synapse_managedprivateendpoints-0.4.0-py2.py3-none-any.whl.metadata (2.3 kB)
Collecting azure-synapse-spark~=0.2.0 (from azure-cli)
  Using cached azure_synapse_spark-0.2.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting chardet~=5.2.0 (from azure-cli)
  Using cached chardet-5.2.0-py3-none-any.whl.metadata (3.4 kB)
Collecting colorama~=0.4.4 (from azure-cli)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting fabric~=3.2.2 (from azure-cli)
  Using cached fabric-3.2.2-py3-none-any.whl.metadata (3.5 kB)
Collecting javaproperties~=0.5.1 (from azure-cli)
  Using cached javaproperties-0.5.2-py2.py3-none-any.whl.metadata (5.8 kB)
Collecting jsondiff~=2.0.0 (from azure-cli)
  Using cached jsondiff-2.0.0-py3-none-any.whl.metadata (562 bytes)
Collecting packaging>=20.9 (from azure-cli)
  Using cached packaging-24.0-py3-none-any.whl.metadata (3.2 kB)
Collecting pycomposefile>=0.0.29 (from azure-cli)
  Using cached pycomposefile-0.0.30-py3-none-any.whl.metadata (356 bytes)
Collecting PyGithub~=1.38 (from azure-cli)
  Using cached PyGithub-1.59.1-py3-none-any.whl.metadata (2.0 kB)
Collecting PyNaCl~=1.5.0 (from azure-cli)
  Using cached PyNaCl-1.5.0-cp36-abi3-win_amd64.whl.metadata (8.7 kB)
Collecting scp~=0.13.2 (from azure-cli)
  Using cached scp-0.13.6-py2.py3-none-any.whl.metadata (4.5 kB)
Collecting semver==2.13.0 (from azure-cli)
  Using cached semver-2.13.0-py2.py3-none-any.whl.metadata (5.0 kB)
Collecting six>=1.10.0 (from azure-cli)
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting sshtunnel~=0.1.4 (from azure-cli)
  Using cached sshtunnel-0.1.5-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: urllib3 in c:\users\ryanc\appdata\local\programs\python\python313\lib\site-packages (from azure-cli) (2.2.1)
Collecting websocket-client~=1.3.1 (from azure-cli)
  Using cached websocket_client-1.3.3-py3-none-any.whl.metadata (6.9 kB)
Collecting xmltodict~=0.12 (from azure-cli)
  Using cached xmltodict-0.13.0-py2.py3-none-any.whl.metadata (7.7 kB)
Collecting argcomplete~=3.1.1 (from azure-cli-core==2.58.0->azure-cli)
  Using cached argcomplete-3.1.6-py3-none-any.whl.metadata (16 kB)
Collecting azure-cli-telemetry==1.1.0.* (from azure-cli-core==2.58.0->azure-cli)
  Using cached azure_cli_telemetry-1.1.0-py3-none-any.whl.metadata (1.8 kB)
Collecting azure-mgmt-core<2,>=1.2.0 (from azure-cli-core==2.58.0->azure-cli)
  Using cached azure_mgmt_core-1.4.0-py3-none-any.whl.metadata (4.1 kB)
Collecting cryptography (from azure-cli-core==2.58.0->azure-cli)
  Using cached cryptography-42.0.5-cp39-abi3-win_amd64.whl.metadata (5.4 kB)
Collecting humanfriendly~=10.0 (from azure-cli-core==2.58.0->azure-cli)
  Using cached humanfriendly-10.0-py2.py3-none-any.whl.metadata (9.2 kB)
Collecting jmespath (from azure-cli-core==2.58.0->azure-cli)
  Using cached jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)
Collecting knack~=0.11.0 (from azure-cli-core==2.58.0->azure-cli)
  Using cached knack-0.11.0-py3-none-any.whl.metadata (5.2 kB)
Collecting msal-extensions~=1.0.0 (from azure-cli-core==2.58.0->azure-cli)
  Using cached msal_extensions-1.0.0-py2.py3-none-any.whl.metadata (7.3 kB)
Collecting msal==1.26.0 (from msal[broker]==1.26.0->azure-cli-core==2.58.0->azure-cli)
  Using cached msal-1.26.0-py2.py3-none-any.whl.metadata (11 kB)
Collecting msrestazure~=0.6.4 (from azure-cli-core==2.58.0->azure-cli)
  Using cached msrestazure-0.6.4-py2.py3-none-any.whl.metadata (15 kB)
Collecting paramiko<4.0.0,>=2.0.8 (from azure-cli-core==2.58.0->azure-cli)
  Using cached paramiko-3.4.0-py3-none-any.whl.metadata (4.4 kB)
Collecting pkginfo>=1.5.0.1 (from azure-cli-core==2.58.0->azure-cli)
  Using cached pkginfo-1.10.0-py3-none-any.whl.metadata (11 kB)
Collecting PyJWT>=2.1.0 (from azure-cli-core==2.58.0->azure-cli)
  Using cached PyJWT-2.8.0-py3-none-any.whl.metadata (4.2 kB)
Collecting pyopenssl>=17.1.0 (from azure-cli-core==2.58.0->azure-cli)
  Using cached pyOpenSSL-24.1.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: requests[socks] in c:\users\ryanc\appdata\local\programs\python\python313\lib\site-packages (from azure-cli-core==2.58.0->azure-cli) (2.31.0)
Collecting psutil~=5.9 (from azure-cli-core==2.58.0->azure-cli)
  Using cached psutil-5.9.8-cp37-abi3-win_amd64.whl.metadata (22 kB)
Collecting azure-core<2.0.0,>=1.15.0 (from azure-data-tables==12.4.0->azure-cli)
  Using cached azure_core-1.30.1-py3-none-any.whl.metadata (37 kB)
Collecting msrest>=0.6.21 (from azure-data-tables==12.4.0->azure-cli)
  Using cached msrest-0.7.1-py3-none-any.whl.metadata (21 kB)
Collecting azure-common~=1.1 (from azure-keyvault-administration==4.4.0b2->azure-cli)
  Using cached azure_common-1.1.28-py2.py3-none-any.whl.metadata (5.0 kB)
Collecting isodate>=0.6.1 (from azure-keyvault-administration==4.4.0b2->azure-cli)
  Using cached isodate-0.6.1-py2.py3-none-any.whl.metadata (9.6 kB)
Collecting typing-extensions>=4.0.1 (from azure-keyvault-administration==4.4.0b2->azure-cli)
  Using cached typing_extensions-4.10.0-py3-none-any.whl.metadata (3.0 kB)
Collecting applicationinsights<0.12,>=0.11.1 (from azure-cli-telemetry==1.1.0.*->azure-cli-core==2.58.0->azure-cli)
  Using cached applicationinsights-0.11.10-py2.py3-none-any.whl.metadata (982 bytes)
Collecting portalocker<3,>=1.6 (from azure-cli-telemetry==1.1.0.*->azure-cli-core==2.58.0->azure-cli)
  Using cached portalocker-2.8.2-py3-none-any.whl.metadata (8.5 kB)
Collecting pymsalruntime<0.14,>=0.13.2 (from msal[broker]==1.26.0->azure-cli-core==2.58.0->azure-cli)
  Using cached pymsalruntime-0.13.12.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cffi (from azure-datalake-store~=0.0.49->azure-cli)
  Using cached cffi-1.16.0.tar.gz (512 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting azure-mgmt-datalake-nspkg>=2.0.0 (from azure-mgmt-datalake-store~=0.5.0->azure-cli)
  Using cached azure_mgmt_datalake_nspkg-3.0.1-py3-none-any.whl.metadata (1.5 kB)
Collecting python-dateutil (from azure-multiapi-storage~=1.2.0->azure-cli)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting invoke>=2.0 (from fabric~=3.2.2->azure-cli)
  Using cached invoke-2.2.0-py3-none-any.whl.metadata (3.3 kB)
Collecting decorator>=5 (from fabric~=3.2.2->azure-cli)
  Using cached decorator-5.1.1-py3-none-any.whl.metadata (4.0 kB)
Collecting deprecated>=1.2 (from fabric~=3.2.2->azure-cli)
  Using cached Deprecated-1.2.14-py2.py3-none-any.whl.metadata (5.4 kB)
Collecting pyyaml (from pycomposefile>=0.0.29->azure-cli)
  Using cached PyYAML-6.0.1.tar.gz (125 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting azure-mgmt-nspkg>=3.0.0 (from azure-mgmt-datalake-nspkg>=2.0.0->azure-mgmt-datalake-store~=0.5.0->azure-cli)
  Using cached azure_mgmt_nspkg-3.0.2-py3-none-any.whl.metadata (1.5 kB)
Collecting pycparser (from cffi->azure-datalake-store~=0.0.49->azure-cli)
  Using cached pycparser-2.21-py2.py3-none-any.whl.metadata (1.1 kB)
Collecting wrapt<2,>=1.10 (from deprecated>=1.2->fabric~=3.2.2->azure-cli)
  Using cached wrapt-1.16.0-py3-none-any.whl.metadata (6.6 kB)
Collecting pyreadline3 (from humanfriendly~=10.0->azure-cli-core==2.58.0->azure-cli)
  Using cached pyreadline3-3.4.1-py3-none-any.whl.metadata (2.0 kB)
Collecting pygments (from knack~=0.11.0->azure-cli-core==2.58.0->azure-cli)
  Using cached pygments-2.17.2-py3-none-any.whl.metadata (2.6 kB)
Collecting tabulate (from knack~=0.11.0->azure-cli-core==2.58.0->azure-cli)
  Using cached tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ryanc\appdata\local\programs\python\python313\lib\site-packages (from msrest>=0.6.21->azure-data-tables==12.4.0->azure-cli) (2024.2.2)
Collecting requests-oauthlib>=0.5.0 (from msrest>=0.6.21->azure-data-tables==12.4.0->azure-cli)
  Downloading requests_oauthlib-1.4.0-py2.py3-none-any.whl.metadata (11 kB)
Collecting adal<2.0.0,>=0.6.0 (from msrestazure~=0.6.4->azure-cli-core==2.58.0->azure-cli)
  Using cached adal-1.2.7-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting bcrypt>=3.2 (from paramiko<4.0.0,>=2.0.8->azure-cli-core==2.58.0->azure-cli)
  Using cached bcrypt-4.1.2-cp39-abi3-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\ryanc\appdata\local\programs\python\python313\lib\site-packages (from requests[socks]->azure-cli-core==2.58.0->azure-cli) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ryanc\appdata\local\programs\python\python313\lib\site-packages (from requests[socks]->azure-cli-core==2.58.0->azure-cli) (3.6)
Collecting PySocks!=1.5.7,>=1.5.6 (from requests[socks]->azure-cli-core==2.58.0->azure-cli)
  Using cached PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Collecting azure-nspkg>=3.0.0 (from azure-mgmt-nspkg>=3.0.0->azure-mgmt-datalake-nspkg>=2.0.0->azure-mgmt-datalake-store~=0.5.0->azure-cli)
  Using cached azure_nspkg-3.0.2-py3-none-any.whl.metadata (1.5 kB)
INFO: pip is looking at multiple versions of portalocker to determine which version is compatible with other requirements. This could take a while.
Collecting portalocker<3,>=1.6 (from azure-cli-telemetry==1.1.0.*->azure-cli-core==2.58.0->azure-cli)
  Using cached portalocker-2.8.1-py3-none-any.whl.metadata (8.5 kB)
  Using cached portalocker-2.7.0-py2.py3-none-any.whl.metadata (6.8 kB)
  Using cached portalocker-2.6.0-py2.py3-none-any.whl.metadata (6.8 kB)
  Using cached portalocker-2.5.1-py2.py3-none-any.whl.metadata (6.8 kB)
  Using cached portalocker-2.5.0-py2.py3-none-any.whl.metadata (6.8 kB)
  Using cached portalocker-2.4.0-py2.py3-none-any.whl.metadata (6.8 kB)
  Using cached portalocker-2.3.2-py2.py3-none-any.whl.metadata (7.6 kB)
INFO: pip is still looking at multiple versions of portalocker to determine which version is compatible with other requirements. This could take a while.
  Using cached portalocker-2.3.1-py2.py3-none-any.whl.metadata (7.5 kB)
  Using cached portalocker-2.3.0-py2.py3-none-any.whl.metadata (7.4 kB)
  Using cached portalocker-2.2.1-py2.py3-none-any.whl.metadata (7.4 kB)
  Using cached portalocker-2.2.0-py2.py3-none-any.whl.metadata (7.4 kB)
  Using cached portalocker-2.1.0-py2.py3-none-any.whl.metadata (7.4 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached portalocker-2.0.0-py2.py3-none-any.whl.metadata (5.2 kB)
  Using cached portalocker-1.7.1-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached portalocker-1.7.0-py2.py3-none-any.whl.metadata (4.6 kB)
  Using cached portalocker-1.6.0-py2.py3-none-any.whl.metadata (4.6 kB)
ERROR: Cannot install azure-cli-telemetry because these package versions have conflicting dependencies.

The conflict is caused by:
    portalocker 2.8.2 depends on pywin32>=226; platform_system == "Windows"
    portalocker 2.8.1 depends on pywin32>=226; platform_system == "Windows"
    portalocker 2.7.0 depends on pywin32>=226; platform_system == "Windows"
    portalocker 2.6.0 depends on pywin32>=226; platform_system == "Windows"
    portalocker 2.5.1 depends on pywin32>=226; platform_system == "Windows"
    portalocker 2.5.0 depends on pywin32>=226; platform_system == "Windows"
    portalocker 2.4.0 depends on pywin32>=226; platform_system == "Windows"
    portalocker 2.3.2 depends on pywin32>=226; platform_system == "Windows"
    portalocker 2.3.1 depends on pywin32!=226; platform_system == "Windows"
    portalocker 2.3.0 depends on pywin32!=226; platform_system == "Windows"
    portalocker 2.2.1 depends on pywin32!=226; platform_system == "Windows"
    portalocker 2.2.0 depends on pywin32!=226; platform_system == "Windows"
    portalocker 2.1.0 depends on pywin32!=226; platform_system == "Windows"
    portalocker 2.0.0 depends on pywin32!=226; platform_system == "Windows"
    portalocker 1.7.1 depends on pywin32!=226; platform_system == "Windows"
    portalocker 1.7.0 depends on pywin32!=226; platform_system == "Windows"
    portalocker 1.6.0 depends on pywin32!=226; platform_system == "Windows"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

### Expected behavior

pip install azure-cli installs the python azure cli

### Environment Summary

  "azure-cli": "2.53.1",
  "azure-cli-core": "2.53.1",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {}
  
  

### Additional context

  "azure-cli": "2.53.1",
  "azure-cli-core": "2.53.1",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {}

Python 3.13.0a2 (tags/v3.13.0a2:9c4347e, Nov 22 2023, 18:30:15) [MSC v.1937 64 bit (AMD64)] on win32

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
I can't repro in Python3.11.
CLI does not support python3.13.

**Comment by ryancrawcour** [comment]
does the CLI support python 3.12? Or only 3.11?

**Comment by bebound** [comment]
3.8 to 3.11
