### ISSUE TITLE
az snapshot create --elastic-san-id not working in cloud shell BASH

### ISSUE THREAD

**Issue by adarshv98** [Azure/azure-cli#28537]
### Describe the bug

<img width="604" alt="image" src="https://github.com/Azure/azure-cli/assets/101731207/59461a86-60d3-4d51-86d3-5ffbf1a93d5e">
The snapshot create cmdlet is not working in cloud shell when given elastic-san source id

### Related command

az snapshot create -g joycehe-rg --name exportedslice --elastic-san-id /subscriptions/dd80b94e-0463-4a65-8d04-c94f403879dc/resourceGroups/joycehe-rg/providers/Microsoft.ElasticSan/elasticSans/joyce-bugbash-san/volumegroups/desserts/snapshots/slice1

### Errors

(ElasticSanGetResourceFailed/ElasticSANNotFound) Elastic San Volume(/subscriptions/dd80b94e-0463-4a65-8d04-c94f403879dc/resourceGroups/joycehe-rg/providers/Microsoft.ElasticSan/elasticSans/joyce-bugbash-san/volumegroups/desserts/snapshots/slice1) or one of its parent resources are not found
Code: ElasticSanGetResourceFailed/ElasticSANNotFound
Message: Elastic San Volume(/subscriptions/dd80b94e-0463-4a65-8d04-c94f403879dc/resourceGroups/joycehe-rg/providers/Microsoft.ElasticSan/elasticSans/joyce-bugbash-san/volumegroups/desserts/snapshots/slice1) or one of its parent resources are not found

### Issue script & Debug output

cli.knack.cli: Command arguments: ['snapshot', 'create', '-g', 'joycehe-rg', '--name', 'exportedslice', '--elastic-san-id', '/subscriptions/dd80b94e-0463-4a65-8d04-c94f403879dc/resourceGroups/joycehe-rg/providers/Microsoft.ElasticSan/elasticSans/joyce-bugbash-san/volumegroups/desserts/snapshots/slice1', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fa27cdb61f0>, <function OutputProducer.on_global_arguments at 0x7fa27ccd0d30>, <function CLIQuery.on_global_arguments at 0x7fa27cc68310>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'snapshot': ['azure.cli.command_modules.vm']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: vm                        0.860        58       237
cli.azure.cli.core: Total (1)                 0.860        58       237
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: ai-examples               0.247         1         1  /usr/lib/python3.9/site-packages/azure-cli-extensions/ai-examples
cli.azure.cli.core: Total (1)                 0.247         1         1  
cli.azure.cli.core: Loaded 59 groups, 238 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : snapshot create
cli.azure.cli.core: Command table: snapshot create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fa27c10dc10>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/adarsh/.azure/commands/2024-03-11.03-21-22.snapshot_create.1957.log'.
az_command_data_logger: command args: snapshot create -g {} --name {} --elastic-san-id {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fa27c0de670>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7fa27c0de8b0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7fa27c03c790>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fa27ccd0dc0>, <function CLIQuery.handle_query_parameter at 0x7fa27cc683a0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7fa27c03c700>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ResourceManagementClient
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2542
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: MSIAuthenticationWrapper.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2542
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: Normalize expires_on: '1710132087' -> 1710132087
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/dd80b94e-0463-4a65-8d04-c94f403879dc/resourcegroups/joycehe-rg?api-version=2022-09-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '6ee63b08-df56-11ee-a6b5-00155d19e23e'
cli.azure.cli.core.sdk.policies:     'CommandName': 'snapshot create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g --name --elastic-san-id --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.58.0 (RPM) azsdk-python-core/1.28.0 Python/3.9.14 (Linux-5.10.102.2-microsoft-standard-x86_64-with-glibc2.35) cloud-shell/1.0'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/dd80b94e-0463-4a65-8d04-c94f403879dc/resourcegroups/joycehe-rg?api-version=2022-09-01 HTTP/1.1" 200 218
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '218'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'f315f462-e78f-482f-b316-b9a363a79f82'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'f315f462-e78f-482f-b316-b9a363a79f82'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHCENTRALUS:20240311T032124Z:f315f462-e78f-482f-b316-b9a363a79f82'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: 5D907E28E64D4FEE90F689447DAB2811 Ref B: SN4AA2022304031 Ref C: 2024-03-11T03:21:24Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 11 Mar 2024 03:21:23 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"id":"/subscriptions/dd80b94e-0463-4a65-8d04-c94f403879dc/resourceGroups/joycehe-rg","name":"joycehe-rg","type":"Microsoft.Resources/resourceGroups","location":"westus2","properties":{"provisioningState":"Succeeded"}}
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=ComputeManagementClient
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2542
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: MSIAuthenticationWrapper.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2542
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: Normalize expires_on: '1710132087' -> 1710132087
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/dd80b94e-0463-4a65-8d04-c94f403879dc/resourceGroups/joycehe-rg/providers/Microsoft.Compute/snapshots/exportedslice?api-version=2023-04-02'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '346'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '6ee63b08-df56-11ee-a6b5-00155d19e23e'
cli.azure.cli.core.sdk.policies:     'CommandName': 'snapshot create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g --name --elastic-san-id --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.58.0 (RPM) azsdk-python-core/1.28.0 Python/3.9.14 (Linux-5.10.102.2-microsoft-standard-x86_64-with-glibc2.35) cloud-shell/1.0'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"location": "westus2", "tags": {}, "sku": {"name": "Standard_LRS"}, "properties": {"creationData": {"createOption": "CopyFromSanSnapshot", "elasticSanResourceId": "/subscriptions/dd80b94e-0463-4a65-8d04-c94f403879dc/resourceGroups/joycehe-rg/providers/Microsoft.ElasticSan/elasticSans/joyce-bugbash-san/volumegroups/desserts/snapshots/slice1"}}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/dd80b94e-0463-4a65-8d04-c94f403879dc/resourceGroups/joycehe-rg/providers/Microsoft.Compute/snapshots/exportedslice?api-version=2023-04-02 HTTP/1.1" 400 347
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '347'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-resource': 'Microsoft.Compute/HighCostSnapshotCreateHydrate3Min;999,Microsoft.Compute/HighCostSnapshotCreateHydrate30Min;7998'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-served-by': 'e308c1eb-57c4-4df2-9661-af489e620e75_133543028426224101'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '27a30f19-2dc7-4896-9126-babf49d0480b'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '7319aaaa-54d4-431d-b15f-e34d750e3cde'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHCENTRALUS:20240311T032125Z:7319aaaa-54d4-431d-b15f-e34d750e3cde'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: 831C216F94074775BF62906789AC443A Ref B: SN4AA2022305031 Ref C: 2024-03-11T03:21:24Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 11 Mar 2024 03:21:24 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "error": {
    "code": "ElasticSanGetResourceFailed/ElasticSANNotFound",
    "message": "Elastic San Volume(/subscriptions/dd80b94e-0463-4a65-8d04-c94f403879dc/resourceGroups/joycehe-rg/providers/Microsoft.ElasticSan/elasticSans/joyce-bugbash-san/volumegroups/desserts/snapshots/slice1) or one of its parent resources are not found"
  }
}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 701, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 334, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/vm/custom.py", line 746, in create_snapshot
    return sdk_no_wait(no_wait, client.snapshots.begin_create_or_update, resource_group_name, snapshot_name, snapshot)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/util.py", line 710, in sdk_no_wait
    return func(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/mgmt/compute/v2023_04_02/operations/_operations.py", line 5483, in begin_create_or_update
    raw_result = self._create_or_update_initial(
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/mgmt/compute/v2023_04_02/operations/_operations.py", line 5354, in _create_or_update_initial
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (ElasticSanGetResourceFailed/ElasticSANNotFound) Elastic San Volume(/subscriptions/dd80b94e-0463-4a65-8d04-c94f403879dc/resourceGroups/joycehe-rg/providers/Microsoft.ElasticSan/elasticSans/joyce-bugbash-san/volumegroups/desserts/snapshots/slice1) or one of its parent resources are not found
Code: ElasticSanGetResourceFailed/ElasticSANNotFound
Message: Elastic San Volume(/subscriptions/dd80b94e-0463-4a65-8d04-c94f403879dc/resourceGroups/joycehe-rg/providers/Microsoft.ElasticSan/elasticSans/joyce-bugbash-san/volumegroups/desserts/snapshots/slice1) or one of its parent resources are not found

cli.azure.cli.core.azclierror: (ElasticSanGetResourceFailed/ElasticSANNotFound) Elastic San Volume(/subscriptions/dd80b94e-0463-4a65-8d04-c94f403879dc/resourceGroups/joycehe-rg/providers/Microsoft.ElasticSan/elasticSans/joyce-bugbash-san/volumegroups/desserts/snapshots/slice1) or one of its parent resources are not found
Code: ElasticSanGetResourceFailed/ElasticSANNotFound
Message: Elastic San Volume(/subscriptions/dd80b94e-0463-4a65-8d04-c94f403879dc/resourceGroups/joycehe-rg/providers/Microsoft.ElasticSan/elasticSans/joyce-bugbash-san/volumegroups/desserts/snapshots/slice1) or one of its parent resources are not found
az_command_data_logger: (ElasticSanGetResourceFailed/ElasticSANNotFound) Elastic San Volume(/subscriptions/dd80b94e-0463-4a65-8d04-c94f403879dc/resourceGroups/joycehe-rg/providers/Microsoft.ElasticSan/elasticSans/joyce-bugbash-san/volumegroups/desserts/snapshots/slice1) or one of its parent resources are not found
Code: ElasticSanGetResourceFailed/ElasticSANNotFound
Message: Elastic San Volume(/subscriptions/dd80b94e-0463-4a65-8d04-c94f403879dc/resourceGroups/joycehe-rg/providers/Microsoft.ElasticSan/elasticSans/joyce-bugbash-san/volumegroups/desserts/snapshots/slice1) or one of its parent resources are not found
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fa27c10de50>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 4.345 seconds (init: 0.362, invoke: 3.983)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 4447 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/bin/python3.9 /usr/lib/az/lib/python3.9/site-packages/azure/cli/telemetry/__init__.py /home/adarsh/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

The cmdlet should work and output the creation status of the new managed disk snapshot

### Environment Summary

azure-cli                         2.58.0

core                              2.58.0
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
elastic-san                        1.0.0
ml                                2.23.0
ssh                                2.0.2

Dependencies:
msal                              1.26.0
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.9'
Extensions directory '/home/adarsh/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.14 (main, Oct 12 2023, 19:48:32) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yanzhudd** [comment]
Hi @adarshv98,
does this issue only occur in the 2.58.0 version of Azure CLI or also in the previous versions?

**Comment by adarshv98** [comment]
Hi @yanzhudd,

The issue was due to location being a required parameter - the operation needs to happen in the same region as the source. You can close this issue whenever convenient!

Regards,
Adarsh
