### ISSUE TITLE
az afd origin-group delete = ERROR: cli.azure.cli.core.azclierror: Operation cancelled

### ISSUE THREAD

**Issue by bigteejay** [Azure/azure-cli#28538]
### Describe the bug

I get an error, with little additional detail via `--debug`, when trying to [delete an origin group](https://learn.microsoft.com/en-us/cli/azure/afd/origin-group?view=azure-cli-latest#az-afd-origin-group-delete).  Origin group (and therefor resource group) can be listed.  Delete returns, "ERROR: cli.azure.cli.core.azclierror: Operation cancelled"

`az afd origin-group show --origin-group-name $main_webapp_origin_group --profile-name $front_door --query provisioningState --output tsv --only-show-errors`

> Succeeded

`az afd origin-group delete --origin-group-name $main_webapp_origin_group --profile-name $front_door  --debug`

> ERROR: Operation cancelled.
> NativeCommandExitException: 

### Related command

az afd origin-group delete 

### Errors

ERROR: Operation cancelled.
NativeCommandExitException: 
Line |
  15 |  az afd origin-group delete --origin-group-name $main_webapp_origin_gr …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Program "az.cmd" ended with non-zero exit code: 1.

### Issue script & Debug output

DEBUG: cli.knack.cli: Command arguments: ['afd', 'origin-group', 'delete', '--origin-group-name', 'MyProductMainWebAppOriginGroup', '--profile-name', 'MyProductFrontDoor', '--debug']
DEBUG: cli.knack.cli: __init__ debug log:
Color is disabled by config.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x00000156C687B880>, <function OutputProducer.on_global_arguments at 0x00000156C6A06020>, <function CLIQuery.on_global_arguments at 0x00000156C6A33BA0>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Modules found from index for 'afd': ['azure.cli.command_modules.cdn']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: cdn                       2.056        35       100
DEBUG: cli.azure.cli.core: Total (1)                 2.056        35       100
DEBUG: cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
DEBUG: cli.azure.cli.core: Loading extensions:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
DEBUG: cli.azure.cli.core: Total (0)                 0.000         0         0  
DEBUG: cli.azure.cli.core: Loaded 35 groups, 100 commands.
DEBUG: cli.azure.cli.core: Found a match in the command table.
DEBUG: cli.azure.cli.core: Raw command  : afd origin-group delete
DEBUG: cli.azure.cli.core: Command table: afd origin-group delete
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x00000156C98BAD40>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x00000156C98C74C0>]
INFO: cli.knack.commands: Configured default 'MyCompanyMyProductTesting' for arg resource_group
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x00000156C99153A0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x00000156C99154E0>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x00000156C6A060C0>, <function CLIQuery.handle_query_parameter at 0x00000156C6A33C40>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x00000156C9915440>]
WARNING: Command group 'afd' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
DEBUG: cli.knack.prompting: No tty available.
WARNING: cli.knack.commands: Unable to prompt for confirmation as no tty available. Use --yes.
DEBUG: cli.knack.cli: Event: Command.OnOperationCancelled []
DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 640, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 858, in resolve_confirmation
knack.util.CLIError: Operation cancelled.

ERROR: cli.azure.cli.core.azclierror: Operation cancelled.
ERROR: az_command_data_logger: Operation cancelled.
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x00000156C98BAFC0>]
INFO: cli.__main__: Command ran in 4.209 seconds (init: 1.877, invoke: 2.332)
NativeCommandExitException: 
Line |
  15 |  az afd origin-group delete --origin-group-name $main_webapp_origin_gr …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Program "az.cmd" ended with non-zero exit code: 1.

### Expected behavior

origin group deleted

### Environment Summary

azure-cli                         2.58.0

core                              2.58.0
telemetry                          1.1.0

Extensions:
bastion                            0.3.0
containerapp                      0.3.46
front-door                        1.0.17
scenario-guide                     0.1.1
serviceconnector-passwordless              0.3.13
storage-preview                  1.0.0b1

Dependencies:
msal                              1.26.0
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\User\.azure\cliextensions'

Python (Windows) 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bigteejay** [comment]
Perhaps the script was waiting on user confirmation?  Adding `--yes` (["optional" parameter](https://learn.microsoft.com/en-us/cli/azure/afd/origin?view=azure-cli-latest#az-afd-origin-delete-optional-parameters)) and the statement executes without error.

**Comment by bigteejay** [comment]
Perhaps add note to docs that for delete, `--yes` (override prompt), is **not** optional when scripting?  Seems sensible now, but was non obvious based on error message returned.
