### ISSUE TITLE
Disabling acticity log alert rules does not work

### ISSUE THREAD

**Issue by ywy-pexip** [Azure/azure-cli#28545]
### Describe the bug

When running the command to disable an activity log alert rule via azure cli (as per example in documentation), it gives an error message.

Example command:
`az monitor activity-log alert update -n AlertName -g ResourceGroup --enable false`

Expected behaviour:
Specified alert rule gets disabled

Actual behaviour:
Error message stating that the condition field is null
```
(ConditionFieldIsNull) The condition field is null. Activity ID: da9ecec3-f435-41f7-92a5-ce1cbbfd7fd3.
Code: ConditionFieldIsNull
Message: The condition field is null. Activity ID: da9ecec3-f435-41f7-92a5-ce1cbbfd7fd3.
```

Possible explanation:
It is not properly identified that the alert rule should only be disabled, not the condition updated.
Condition parameter is required, even though documentation gives example to disable alert rules without including the existing condition.

### Related command

`az monitor activity-log alert update -n AlertName -g ResourceGroup --enable false`

### Errors

```
(ConditionFieldIsNull) The condition field is null. Activity ID: da9ecec3-f435-41f7-92a5-ce1cbbfd7fd3.
Code: ConditionFieldIsNull
Message: The condition field is null. Activity ID: da9ecec3-f435-41f7-92a5-ce1cbbfd7fd3.
```

### Issue script & Debug output

cli.knack.cli: Command arguments: ['monitor', 'activity-log', 'alert', 'update', '--ids', '/subscriptions/SUB_ID/resourceGroups/RESOURCE_GROUP/providers/Microsoft.Insights/activityLogAlerts/Azure VMSS issue - DEPLOYMENT', '--enable', 'false', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fa1ce2bd480>, <function OutputProducer.on_global_arguments at 0x7fa1ce2183a0>, <function CLIQuery.on_global_arguments at 0x7fa1ce0355a0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'monitor': ['azure.cli.command_modules.monitor']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: monitor                   0.342        25        70
cli.azure.cli.core: Total (1)                 0.342        25        70
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0  
cli.azure.cli.core: Loaded 25 groups, 70 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : monitor activity-log alert update
cli.azure.cli.core: Command table: monitor activity-log alert update
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fa1cd28eef0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/yannick/.azure/commands/2024-03-12.14-33-41.monitor_activity-log_alert_update.20911.log'.
az_command_data_logger: command args: monitor activity-log alert update --ids {} --enable {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fa1cd2aba30>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7fa1cd2ed870>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7fa1cd2ed990>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fa1ce218430>, <function CLIQuery.handle_query_parameter at 0x7fa1ce035630>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7fa1cd2ed900>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=MonitorManagementClient
cli.azure.cli.core.auth.persistence: build_persistence: location='/home/yannick/.azure/msal_token_cache.json', encrypt=False
cli.azure.cli.core.auth.binary_cache: load: /home/yannick/.azure/msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/983be362-1f4b-4a72-b5c5-ad805e211fa0/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/983be362-1f4b-4a72-b5c5-ad805e211fa0/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/983be362-1f4b-4a72-b5c5-ad805e211fa0/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/983be362-1f4b-4a72-b5c5-ad805e211fa0/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/983be362-1f4b-4a72-b5c5-ad805e211fa0/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/983be362-1f4b-4a72-b5c5-ad805e211fa0/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/983be362-1f4b-4a72-b5c5-ad805e211fa0/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 34f871db-8369-417e-a917-35057410bb89
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/SUB_ID/resourceGroups/RESOURCE_GROUP/providers/microsoft.insights/activityLogAlerts/Azure%20VMSS%20issue%20-%20DEPLOYMENT?api-version=2017-04-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '7743a5c6-e03a-11ee-b10c-00155d5731cf'
cli.azure.cli.core.sdk.policies:     'CommandName': 'monitor activity-log alert update'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--ids --enable --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.53.1 (DEB) azsdk-python-azure-mgmt-monitor/5.0.0 Python/3.10.10 (Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/SUB_ID/resourceGroups/RESOURCE_GROUP/providers/microsoft.insights/activityLogAlerts/Azure%20VMSS%20issue%20-%20DEPLOYMENT?api-version=2017-04-01 HTTP/1.1" 200 3791
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '3791'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'd6c04402-3175-44df-93d2-4d22ce3cbce5, d6c04402-3175-44df-93d2-4d22ce3cbce5'
cli.azure.cli.core.sdk.policies:     'api-supported-versions': '2017-03-01-preview, 2017-04-01, 2020-10-01, 2023-01-01-preview'
cli.azure.cli.core.sdk.policies:     'Arr-Disable-Session-Affinity': 'true'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-AspNet-Version': '4.0.30319'
cli.azure.cli.core.sdk.policies:     'X-Powered-By': 'ASP.NET'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11999'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'd6c04402-3175-44df-93d2-4d22ce3cbce5'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHEASTASIA:20240312T063342Z:d6c04402-3175-44df-93d2-4d22ce3cbce5'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: A76C463E5F784B678E442551E3B6D2F1 Ref B: MAA201060514037 Ref C: 2024-03-12T06:33:41Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 12 Mar 2024 06:33:41 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "id": "/subscriptions/SUB_ID/resourceGroups/RESOURCE_GROUP/providers/Microsoft.Insights/activityLogAlerts/Azure VMSS issue - DEPLOYMENT",
  "name": "Azure VMSS issue - DEPLOYMENT",
  "type": "Microsoft.Insights/ActivityLogAlerts",
  "location": "Global",
  "properties": {
    "scopes": [
      "/subscriptions/SUB_ID"
    ],
    "condition": {
      "allOf": [
        {
          "field": "category",
          "equals": "ResourceHealth"
        },
        {
          "anyOf": [
            {
              "field": "properties.cause",
              "equals": "PlatformInitiated"
            },
            {
              "field": "properties.cause",
              "equals": "Unknown"
            }
          ]
        },
        {
          "anyOf": [
            {
              "field": "properties.currentHealthStatus",
              "equals": "Unavailable"
            }
          ]
        },
        {
          "anyOf": [
            {
              "field": "properties.previousHealthStatus",
              "equals": "Available"
            }
          ]
        },
        {
          "anyOf": [
            {
              "field": "resourceGroup",
              "equals": "networkwatcherrg"
            },
            {
              "field": "resourceGroup",
              "equals": "prod-health-alerts"
            },
            {
              "field": "resourceGroup",
              "equals": "prod-DEPLOYMENT-traffic-manager"
            },
            {
              "field": "resourceGroup",
              "equals": "RESOURCE_GROUP"
            },
            {
              "field": "resourceGroup",
              "equals": "tcDEPLOYMENT-FOO-rg"
            },
            {
              "field": "resourceGroup",
              "equals": "tcDEPLOYMENT-FOO-static-rg"
            },
            {
              "field": "resourceGroup",
              "equals": "tcDEPLOYMENT-FOO-rg"
            },
            {
              "field": "resourceGroup",
              "equals": "tcDEPLOYMENT-FOO-static-rg"
            },
            {
              "field": "resourceGroup",
              "equals": "tcDEPLOYMENT-FOO-rg"
            },
            {
              "field": "resourceGroup",
              "equals": "tcDEPLOYMENT-FOO-static-rg"
            },
            {
              "field": "resourceGroup",
              "equals": "tcDEPLOYMENT-FOO-rg"
            },
            {
              "field": "resourceGroup",
              "equals": "tcDEPLOYMENT-FOO-static-rg"
            },
            {
              "field": "resourceGroup",
              "equals": "tcDEPLOYMENT-FOO-rg"
            },
            {
              "field": "resourceGroup",
              "equals": "tcDEPLOYMENT-FOO-static-rg"
            },
            {
              "field": "resourceGroup",
              "equals": "tcDEPLOYMENT-FOO-rg"
            },
            {
              "field": "resourceGroup",
              "equals": "tcDEPLOYMENT-FOO-static-rg"
            }
          ]
        },
        {
          "anyOf": [
            {
              "field": "resourceType",
              "equals": "microsoft.compute/virtualmachinescalesets"
            }
          ]
        }
      ]
    },
    "actions": {
      "actionGroups": [
        {
          "actionGroupId": "/subscriptions/SUB_ID/resourceGroups/prod-health-alerts/providers/microsoft.insights/actionGroups/AG"
        }
      ]
    },
    "enabled": true,
    "description": "VMSS resource status changed to Unavailable, Degraded or Unknown."
  }
}
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=MonitorManagementClient
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/983be362-1f4b-4a72-b5c5-ad805e211fa0/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/983be362-1f4b-4a72-b5c5-ad805e211fa0/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/983be362-1f4b-4a72-b5c5-ad805e211fa0/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/983be362-1f4b-4a72-b5c5-ad805e211fa0/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/983be362-1f4b-4a72-b5c5-ad805e211fa0/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/983be362-1f4b-4a72-b5c5-ad805e211fa0/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/983be362-1f4b-4a72-b5c5-ad805e211fa0/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=MonitorManagementClient
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/983be362-1f4b-4a72-b5c5-ad805e211fa0/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/983be362-1f4b-4a72-b5c5-ad805e211fa0/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/983be362-1f4b-4a72-b5c5-ad805e211fa0/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/983be362-1f4b-4a72-b5c5-ad805e211fa0/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/983be362-1f4b-4a72-b5c5-ad805e211fa0/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/983be362-1f4b-4a72-b5c5-ad805e211fa0/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/983be362-1f4b-4a72-b5c5-ad805e211fa0/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? False
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 2cf5749f-63cc-4c28-a344-2b71b1a2ea68
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/SUB_ID/resourceGroups/RESOURCE_GROUP/providers/microsoft.insights/activityLogAlerts/Azure%20VMSS%20issue%20-%20DEPLOYMENT?api-version=2017-04-01'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '491'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '7743a5c6-e03a-11ee-b10c-00155d5731cf'
cli.azure.cli.core.sdk.policies:     'CommandName': 'monitor activity-log alert update'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--ids --enable --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.53.1 (DEB) azsdk-python-azure-mgmt-monitor/5.0.0 Python/3.10.10 (Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"location": "Global", "properties": {"scopes": ["/subscriptions/SUB_ID"], "enabled": false, "condition": {"allOf": [{"field": "category", "equals": "ResourceHealth"}, {}, {}, {}, {}, {}]}, "actions": {"actionGroups": [{"actionGroupId": "/subscriptions/SUB_ID/resourceGroups/prod-health-alerts/providers/microsoft.insights/actionGroups/AG"}]}, "description": "VMSS resource status changed to Unavailable, Degraded or Unknown."}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/SUB_ID/resourceGroups/RESOURCE_GROUP/providers/microsoft.insights/activityLogAlerts/Azure%20VMSS%20issue%20-%20DEPLOYMENT?api-version=2017-04-01 HTTP/1.1" 400 123
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '123'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'ad93b04f-abbb-4042-b8dc-5f0957354394'
cli.azure.cli.core.sdk.policies:     'api-supported-versions': '2017-03-01-preview, 2017-04-01, 2020-10-01, 2023-01-01-preview'
cli.azure.cli.core.sdk.policies:     'Arr-Disable-Session-Affinity': 'true'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-AspNet-Version': '4.0.30319'
cli.azure.cli.core.sdk.policies:     'X-Powered-By': 'ASP.NET'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'ad93b04f-abbb-4042-b8dc-5f0957354394'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHEASTASIA:20240312T063344Z:ad93b04f-abbb-4042-b8dc-5f0957354394'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: 712045EB5EF54260B8BB2755FA660BEB Ref B: MAA201060515009 Ref C: 2024-03-12T06:33:42Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 12 Mar 2024 06:33:43 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"code":"ConditionFieldIsNull","message":"The condition field is null. Activity ID: ad93b04f-abbb-4042-b8dc-5f0957354394."}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/monitor/_exception_handler.py", line 23, in exception_handler
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 242, in handler
    result = cached_put(self.cmd, setter, setterargs[self.setter_arg_name],
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 452, in cached_put
    return _put_operation()
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 446, in _put_operation
    result = operation(**kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/mgmt/monitor/v2017_04_01/operations/_activity_log_alerts_operations.py", line 380, in create_or_update
    raise HttpResponseError(response=response, model=error, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (ConditionFieldIsNull) The condition field is null. Activity ID: ad93b04f-abbb-4042-b8dc-5f0957354394.
Code: ConditionFieldIsNull
Message: The condition field is null. Activity ID: ad93b04f-abbb-4042-b8dc-5f0957354394.

cli.azure.cli.core.azclierror: (ConditionFieldIsNull) The condition field is null. Activity ID: ad93b04f-abbb-4042-b8dc-5f0957354394.
Code: ConditionFieldIsNull
Message: The condition field is null. Activity ID: ad93b04f-abbb-4042-b8dc-5f0957354394.
az_command_data_logger: (ConditionFieldIsNull) The condition field is null. Activity ID: ad93b04f-abbb-4042-b8dc-5f0957354394.
Code: ConditionFieldIsNull
Message: The condition field is null. Activity ID: ad93b04f-abbb-4042-b8dc-5f0957354394.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fa1cd28f130>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 3.450 seconds (init: 0.159, invoke: 3.291)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3734 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/bin/../../opt/az/bin/python3 /opt/az/lib/python3.10/site-packages/azure/cli/telemetry/__init__.py /home/yannick/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

Specified alert rule gets disabled

### Environment Summary

azure-cli                         2.53.1 *

core                              2.53.1 *
telemetry                          1.1.0

Extensions:
account                            0.2.5

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/home/user/.azure/cliextensions'

Python (Linux) 3.10.10 (main, Oct 24 2023, 06:10:14) [GCC 11.4.0]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by ywy-pexip** [comment]
I'm sorry, the issue was solved by updating azure cli to the latest version.
Thanks for wanting to help anyway :)

**Comment by ywy-pexip** [comment]
Just tried running the command on the latest version. Didn't get an error message and alert rule gets disabled/enabled as expected
