### ISSUE TITLE
`az storage blob upload-batch`: unclear documentation

### ISSUE THREAD

**Issue by elibarzilay** [Azure/azure-cli#2854]
### Environment summary

(Same as in my last issue.)

---

### Description

The documentation of `az storage blob upload-batch` is really unclear.

1. It seems to me that the description of the destination argument has a few occurrences of "source" that should really be "target".

2. The doc for the source argument is ungrammatical in a confusing way too.

3. It fails to specify what happens when the source directory has nested directories: is the structure copied? flattened? or maybe subdirs are ignored?

5. It is really unclear what "shape" should a URL destination have.  An example would help a lot.  (I had to read the source, and the only thing I could figure is that it can be the container name, which I used.)

6. It also fails to mention that the destination can be "<container-name>/<subdir>".

7. Slightly unrelated: it'd be nice if the syntax of this would be similar to the syntax of the `upload` subcommand.  Even better, if there was only `upload`, and it had a flag specifying that the source is a glob pattern for several files to upload.

**Comment by elibarzilay** [comment]
I forgot to add: when I tried to see if I can guess the syntax of a destination url, I kept getting the same unhelpful error message:

    incorrect usage: destination cannot be a blob url

**Comment by balazsnemeth** [comment]
@elibarzilay : Do you know the answer for the 3) point? What happend if a source directory has nested directories? My upload failing without any error message, so maybe this cause an issue

**Comment by troydai** [comment]
@balazsnemeth it should copy file recursively base on the pattern you gave.
https://github.com/Azure/azure-cli/blob/4fdaec707616bb45fcba43fef82ba8e4c4658448/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/util.py#L73

**Comment by williexu** [comment]
@balazsnemeth, @troydai  by default, the command will copy files recursively through any nested directories. The pattern will limit the files being uploaded.

**Comment by williexu** [comment]
Closing this as most of these issues have been addressed;
-docs should be more clear (please raise issues for any further problems)
-urls are taken from portal; cli users can just specify the container name for their destination
