### ISSUE TITLE
`az` help text

### ISSUE THREAD

**Issue by elibarzilay** [Azure/azure-cli#2855]
When there are mistakes in uses of the `az` cli, the output often comes out in a way that is not too helpful.  As a random example, see the below.  It looks like the output is made by printing the basic command+subs and then the list of arguments with some automatic line wrapping.  The thing is that the commands tend to be very nested and therefore very long, so there's little room for the argument list.  In particular, note that in my example the destination and source mandatory arguments are wrapped in a very confusing way.

It would be much better if the arguments were
* specified at a fixed indentation from the left side (or maybe following some "arguments:" header
* listed with only one argument per line
* listed in a better & consistent order, eg, mandatory arguments first, optional ones next, and finally generic ones (`-h` / `--output` / etc)

(As a side note, this style of command-line is very fitting for someone who is coming from a powershell background, but the overall design is weird in a linux world: like the lack of non-flagged ("positional") arguments, and the flags that have multiple values as in the `--metadata` below.)

    $ az storage blob upload-batch --destination "https://...windows.net/.../foo/" --source "..."
    usage: az storage blob upload-batch [-h] [--output {json,tsv,table,jsonc}]
                                        [--verbose] [--debug] [--query JMESPATH]
                                        [--lease-id LEASE_ID]
                                        [--account-key ACCOUNT_KEY]
                                        [--content-language CONTENT_LANGUAGE]
                                        [--connection-string CONNECTION_STRING]
                                        [--account-name ACCOUNT_NAME]
                                        [--max-connections MAX_CONNECTIONS]
                                        [--if-modified-since IF_MODIFIED_SINCE]
                                        [--pattern PATTERN] --destination
                                        DESTINATION [--type BLOB_TYPE] --source
                                        SOURCE [--validate-content]
                                        [--content-encoding CONTENT_ENCODING]
                                        [--content-md5 CONTENT_MD5]
                                        [--if-match IF_MATCH]
                                        [--content-disposition CONTENT_DISPOSITION]
                                        [--metadata METADATA [METADATA ...]]
                                        [--dryrun] [--if-none-match IF_NONE_MATCH]
                                        [--maxsize-condition MAXSIZE_CONDITION]
                                        [--sas-token SAS_TOKEN]
                                        [--content-type CONTENT_TYPE]
                                        [--content-cache-control CONTENT_CACHE_CONTROL]
                                        [--timeout TIMEOUT]
                                        [--if-unmodified-since IF_UNMODIFIED_SINCE]
    az storage blob upload-batch: error: incorrect usage: destination cannot be a blob url

**Comment by tjprescott** [comment]
cc/ @johanste

**Comment by yugangw-msft** [comment]
//CC @chewong, a bit different from #3994 though

**Comment by yonzhan** [comment]
add to S165.

**Comment by jiasli** [comment]
As discussed in https://github.com/Azure/azure-cli/issues/10676#issuecomment-536253290, Azure CLI uses Python's [argparse](https://docs.python.org/3/library/argparse.html) for the help text, so we have little control over the format if we don't override that. You may always use `-h` to view better-printed help text. 

As for **positional** arguments, they are not supported by Azure CLI. All argument needs to be keyword arguments. The only exception is `az find`:

https://github.com/Azure/azure-cli/blob/5edbd822ee860d7ba5d5182811b68233e0846ba8/src/azure-cli/azure/cli/command_modules/find/_params.py#L9
