### ISSUE TITLE
Azure CLI on Portal have pg_dump version: 14.10

### ISSUE THREAD

**Issue by HitenBhavsarMSFT** [Azure/azure-cli#28558]
### Describe the bug

On the azure portal CLI hold the over the version on the utility then the current postgreSQL version

### Related command

az upgrade 
should update the cli and other utility pg_dump version: 14.10 to current version. 

### Errors

Password:
pg_dump: error: server version: 15.4; pg_dump version: 14.10
pg_dump: error: aborting because of server version mismatch
chocilowski@Azure:~/clouddrive$

### Issue script & Debug output

pg_dump: error: server version: 15.4; pg_dump version: 14.10

![image](https://github.com/Azure/azure-cli/assets/72768193/b455ed40-931e-4b1f-9645-de876746f24e)

### Expected behavior

pg_dump version: 15 or 16, per our product group team 

### Environment Summary

cx on 2.58 version, which is current

 
![image](https://github.com/Azure/azure-cli/assets/72768193/afc9e08f-66ab-4247-8753-4ffc7e270872)

### Additional context

![image](https://github.com/Azure/azure-cli/assets/72768193/88b3e870-d512-4d0a-a27d-f326d953c1ae)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
`az upgrade`'s error message is clear: `Cannot update system extension ai-examples, please wait until Cloud Shell updates it in the next release.`

`pg_dump` is not related to azure-cli.
You should report to https://github.com/Azure/CloudShell

**Comment by HitenBhavsarMSFT** [comment]
https://github.com/Azure/CloudShell/issues/383
