### ISSUE TITLE
az postgres up | In in-line help, provide list of azCLI reference commands being executed

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#28565]
### Describe the bug

Customers are asking what Azure CLI reference commands are being executed by our `az ... up` commands.  Doc writers are also requesting this information when they must replicate Azure CLI docs with Azure PowerShell commands. Although the reference list might change based on the parameters being passed, we need clarity in our in-line help and resulting autogenerated reference content. 

**Reference command link:** https://learn.microsoft.com/en-us/cli/azure/postgres#az-postgres-up

**Current description:** `Set up an Azure Database for PostgreSQL server and configurations.`

**REQUEST:** Please modify this description to list each Azure CLI reference command that "up" can/is executing.

**Possible impacted source code files** (where this description is found):
https://github.com/azure/azure-cli-extensions/blob/main/src/db-up/azext_db_up/_help.py

### Related command

az postgres up

### Errors

n/a

### Issue script & Debug output

n/a

### Expected behavior

n/a

### Environment Summary

Azure CLI 2.58.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by nachoalonsoportillo** [comment]
@dbradish-microsoft Everything that this command does is send to the output in forms of warnings:

```
Creating Resource Group 'group7499853968'...
Creating PostgreSQL Server 'server665783898' in group 'group7499853968'...
Creating PostgreSQL database 'sampledb'...
Checking your ip address...
Configuring server firewall rule, 'devbox', to allow for your ip address: 20.13.76.206
If PostgreSQL server declines your IP address, please create a new firewall rule using:
    `az postgres server firewall-rule create -g group7499853968 -s server665783898 -n {rule_name} --start-ip-address {ip_address} --end-ip-address {ip_address}`
Configuring server firewall rule, 'azure-access', to accept connections from all Azure resources...
Successfully Connected to PostgreSQL.
Ran Database Query: `CREATE USER root WITH ENCRYPTED PASSWORD 'Sampledb1'`
Ran Database Query: `GRANT ALL PRIVILEGES ON DATABASE sampledb TO root`
```

The logic varies, depending on whether you have configured some of the parameters as defaults, via `az configure --defaults` or depending on whether you've run the command before and those arguments have been cached in ~/.azext_db_up/config, or if the user is overriding them via the parameter accepted by the `az postgres up` command itself.

I don't think it is feasible to try to describe all that logic in the in-line help.

Besides, Azure Database for PostgreSQL Flexible Server is retiring on March 2025, hence don't think we should spend cycles on this at this point.

**Comment by dbradish-microsoft** [comment]
@nachoalonsoportillo, does --debug expose all the different API calls? If so, that would be a simple solution.

**Comment by nachoalonsoportillo** [comment]
> @nachoalonsoportillo, does --debug expose all the different API calls? If so, that would be a simple solution.

Yes, it does.
