### ISSUE TITLE
az webapp up | In in-line help, provide list of azCLI reference commands being executed

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#28567]
### Describe the bug

Customers are asking what Azure CLI reference commands are being executed by our `az ... up` commands.  Doc writers are also requesting this information when they must replicate Azure CLI docs with Azure PowerShell commands. Although the reference list might change based on the parameters being passed, we need clarity in our in-line help and resulting autogenerated reference content. 

**Reference command link:** https://learn.microsoft.com/en-us/cli/azure/webappt#az-webapp-up

**Current description:** 
----------------------------------------------
![image](https://github.com/Azure/azure-cli/assets/58762114/908eea93-1fde-439f-9aea-92ea199cb2ec)

**REQUEST:** Please modify this description to list each Azure CLI reference command that "up" can/is executing. You can move the current description to the `long-summary` property in _help.py whereby giving you a paragraph break. For an example, see the [Azure CLI reference guidelines for long-summary](https://github.com/Azure/azure-cli/blob/dev/doc/reference_doc_guidelines.md#long-summary).

**Possible impacted source code files** (where this description is found):
https://github.com/azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/_help.py

### Related command

az webapp up

### Errors

n/a

### Issue script & Debug output

n/a

### Expected behavior

n/a

### Environment Summary

Azure CLI 2.58.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by dbradish-microsoft** [comment]
@AzureAppServiceCLI, @antcp.

Can we resolve this issue by putting a sentence in the short or long summary that states something like "Run this command with the --debug parameter to see the API calls and parameters values being used."?

This avoids a lengthy long-summary property, but tells the customer how to find the answer for themselves.
