### ISSUE TITLE
ACS: Allow reuse of existing VNETS and SUBNETS

### ISSUE THREAD

**Issue by andrewstevenson** [Azure/azure-cli#2856]
I really like the cli and `acs` functionality but would like to deploy into existing vnets and subnets?

**Comment by brendandburns** [comment]
This is coming.  Currently if you use [acs-engine](https://github.com/Azure/acs-engine/tree/master/examples/vnet) you can do this.

It will come to ACS eventually.

Closing for now, since this is more of an ACS API issue than a CLI issue.
