### ISSUE TITLE
Is there any way to perform NSG operations in bulk? (Inquiry/FR?)

### ISSUE THREAD

**Issue by nneul** [Azure/azure-cli#2858]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 0.1.0b8

**OS Version:** What OS and version are you using?  
Answer here: ubuntu 16.04

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

### Description

Would like to know if there is any way to do NSG operations in bulk. Right now, I've got automation for the entire process creating numerous rules with az network nsg create (and similar with xplat cli), but it's very slow - and parallelizing (at least with xplat) doesn't work right - the updates seem to stomp on each other.

I'm wondering if there is support for anything equivalent to the opposite of 'az network nsg rule list'? (I'm fine with it being a little raw, but would rather not have to do the underlying API support directly in my scripts at this time.) 

If there isn't, consider this a feature request. I'd love to see something like:

'az network nsg rule import [--replace] [--update]  --json file.json' with the nsg name, resource group name, etc. options on command line acting as defaults if they were not included in the content. Input format of the json would be identical to the output format of nsg rule list. --replace would request a wholesale replacement of the ruleset (delete all not present), --update would load, and replace any that had the same index and/or id.

**Comment by tjprescott** [comment]
Hi @nneul, the best way I can think to accomplish your scenario would be to use generic update combined with the @file syntax to define your rules in a JSON snippet and then load them.  The command would look something like:

`az network nsg update -g yourRG -n yourNSG --set securityRules=@rules.json`

Then your JSON would have to be the JSON array definition of the rules you want to create. In this way, you can add all your rules with a single PUT call. Does that work for your scenario?

**Comment by nneul** [comment]
I don't know, but it sure looks like it would. I will give it a try. 

That sounds like a complete set - equivalent to what I described above as '...import --replace...' ? If so, yes, I think that will work quite nicely.

**Comment by tjprescott** [comment]
Yes, it is a complete replacement.  You could also add multiple rules using:
`az network nsg update -g yourRG -n yourNSG --add securityRules {ugly JSON string} --add securityRules {ugly JSON string}`

But I think you'd be better off capturing the rules you have, adding the ones you want, and setting the whole object.  Template deployment would be another option of course.

**Comment by nneul** [comment]
Very cool. I was unaware of this functionality, and can think of a LOT of places in my automation where it might be useful. I'll close this for now, thank you for the assist.
