### ISSUE TITLE
Curl appears to be missing from mcr.microsoft.com/azure-cli:latest

### ISSUE THREAD

**Issue by lcividinwork** [Azure/azure-cli#28581]
### Describe the bug

Curl appears to be missing in mcr.microsoft.com/azure-cli:latest  alpine  I can see it's still in the dockerfile here https://github.com/Azure/azure-cli/blob/dev/alpine.dockerfile#L38  
I can install it with apk add 

docker run -it mcr.microsoft.com/azure-cli sh
/ # curl
sh: curl: not found

### Related command

docker run -it mcr.microsoft.com/azure-cli sh
/ # curl
sh: curl: not found

/ # ls -lah /usr/bin | grep curl    #nothing found 
/ # ls -lah /usr/local/bin | grep curl #nothing found 

curl --version 
sh: curl: not found

apk add curl 
/ # apk add curl
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
(1/7) Installing brotli-libs (1.1.0-r1)
(2/7) Installing c-ares (1.24.0-r1)
(3/7) Installing libunistring (1.1-r2)
(4/7) Installing libidn2 (2.3.4-r4)
(5/7) Installing nghttp2-libs (1.58.0-r0)
(6/7) Installing libcurl (8.5.0-r0)
(7/7) Installing curl (8.5.0-r0)
Executing busybox-1.36.1-r15.trigger
OK: 35 MiB in 57 packages
/ # which curl
/usr/bin/curl
/ #

/ # curl --version
curl 8.5.0 (x86_64-alpine-linux-musl) libcurl/8.5.0 OpenSSL/3.1.4 zlib/1.3.1 brotli/1.1.0 c-ares/1.24.0 libidn2/2.3.4 nghttp2/1.58.0
Release-Date: 2023-12-06
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM SSL threadsafe TLS-SRP UnixSockets
/ #

### Errors

Curl is missing from the image. I can see it's meant to be added in the dockerfile in this repo though 

sh: curl: not found 

### Issue script & Debug output

no debug required package is missing possible image build issue d

### Expected behavior

Curl should be present in the latest image 

### Environment Summary

/ # az --version
azure-cli                         2.58.0

core                              2.58.0
telemetry                          1.1.0

Dependencies:
msal                              1.26.0
azure-mgmt-resource             23.1.0b2

Python location '/usr/local/bin/python'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.11.8 (main, Feb  7 2024, 23:20:20) [GCC 13.2.1 20231014]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

is docker image related not azcli command related.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by lcividinwork** [comment]
no that is not a solution but a work around, which has been implemented to work around it but I believe it still should be in the image build.  https://github.com/Azure/azure-cli/blob/dev/alpine.dockerfile#L38

**Comment by bebound** [comment]
We remove it intentionally. See https://[github.com/Azure/azure-cli/pull/27567](https://github.com/Azure/azure-cli/pull/27567)

**Comment by lcividinwork** [comment]
Ok thanks for the explanation, we've been using the latest tag azurecli image for a long time, our deployment plans only now have started failing with the missing curl package this week. 
If it's been removed from since 2023, I wonder why our plans have only started failing now? 
I added a step to install the package, just don't get why the image only started failing this week.

**Comment by pinkfloydx33** [comment]
You realize that by removing you have broken Azure ARM `deploymentScripts` which uses the azure-cli image and from within launches curl to download supporting scripts. This no longer works. I just tried updating to the latest version "supported" by Azure but apparently that's wrong and I need to downgrade a few versions.
