### ISSUE TITLE
Wrong structure for azure-cli-nspkg

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-cli#2859]
azure-cli-nspkg has some issues:

- Since it's a sub-package of "azure-nspkg", it should have it in dependency
- the file "azure/__init__.py" must be absent (will be provided by the "azure-nspkg" dependency)

See azure-mgmt-nspkg for instance

This is not an issue about the content of "azure/cli/__init__.py", that should be without declare_namespace or not. So you can release a first version with this fixed, and then a second version without declare_namespace, if you think you're not ready to do both at the same time.

@derekbekoe @johanste

**Comment by johanste** [comment]
Thanks, @lmazuel. Yes, we also observed this as part of the declare_namespace changes.

**Comment by derekbekoe** [comment]
@johanste is there any action required here?

**Comment by johanste** [comment]
This has been addressed.
