### ISSUE TITLE
[k8s-configuration] BREAKING CHANGE: `az k8s-configuration create`: Removal of create cmd for flux v1 

### ISSUE THREAD

**Issue by bavneetsingh16** [Azure/azure-cli#28608]
### Describe the bug

The command `az k8s-configuration create` has been obsolete for two years. As a replacement, we introduced `az k8s-configuration flux create`. The former command utilizes Flux v1, while the latter employs Flux v2. We have already informed our customers that from December 2023 onwards, they will only have the ability to list, display, or remove Flux v1 configurations. All production workloads have been transitioned to Flux v2.

PR for the breaking change: [https://github.com/Azure/azure-cli-extensions/pull/7406](https://github.com/Azure/azure-cli-extensions/pull/7406)

### Related command

az k8s-configuration create

### Errors

`create` cmd can no longer be used. The cmd has been deprecated for 2 years now.

### Issue script & Debug output

N/A

### Expected behavior

`az k8s-configuration create` cmd should no longer work.

### Environment Summary

azure-cli: 2.52.0
k8s-configuration: 1.7.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
