### ISSUE TITLE
Cannot install ml extension

### ISSUE THREAD

**Issue by AndriyDmytrenko** [Azure/azure-cli#28600]
### Describe the bug

Cannot install ml extension, possibly due to python dependency issue.
The platform is MacOS arm64.

### Related command

az extension add -n ml

### Errors

An error occurred. Pip failed with status code 1. Use --debug for more information.

### Issue script & Debug output

[az-ml-debug.txt](https://github.com/Azure/azure-cli/files/14691275/az-ml-debug.txt)

### Expected behavior

ml extension installed

### Environment Summary

azure-cli                         2.58.0

core                              2.58.0
telemetry                          1.1.0

Extensions:
aks-preview                      2.0.0b6
alb                                1.0.0
application-insights               1.2.0
appservice-kube                   0.1.10
azure-devops                       1.0.0
bastion                            0.3.0
connectedk8s                       1.6.7
customlocation                     0.1.3
front-door                        1.0.17
k8s-extension                      1.6.1
ssh                                2.0.3
storage-preview                  1.0.0b1

Dependencies:
msal                              1.26.0
azure-mgmt-resource             23.1.0b2

Python location '/opt/homebrew/Cellar/azure-cli/2.58.0/libexec/bin/python'
Extensions directory '/Users/Andriy_Dmytrenko/.azure/cliextensions'

Python (Darwin) 3.11.8 (main, Feb  6 2024, 21:21:21) [Clang 15.0.0 (clang-1500.1.0.2.5)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by NMontanaBrown** [comment]
Hi, I am having the same issue - unfortunately the proposed fix does not resolve the installation problem.

**Comment by AndriyDmytrenko** [comment]
> Hi, I am having the same issue - unfortunately the proposed fix does not resolve the installation problem.
> 
> EDIT: Flagging the typo from the bot , which I presume meant `openssl@1.1` vs `openssl.1`:
> 
> ```
> brew install openssl@1.1
> export LDFLAGS="-L/opt/homebrew/opt/openssl@1.1/lib"
> export CPPFLAGS="-I/opt/homebrew/opt/openssl@1.1/include"
> az extension add -n ml -y
> ```

The same, it doesn't fix the issue for me either.

**Comment by bebound** [comment]
According to the log:
```
Given no hashes to check 0 links for project 'azureml-dataprep-rslex': discarding no candidates
INFO: pip is looking at multiple versions of ml to determine which version is compatible with other requirements. This could take a while.
Will try a different candidate, due to conflict:
    ml 2.24.0 depends on azureml-dataprep-rslex>=2.22.0
ERROR: Could not find a version that satisfies the requirement azureml-dataprep-rslex>=2.22.0 (from ml) (from versions: none)
ERROR: No matching distribution found for azureml-dataprep-rslex>=2.22.0
```
This package does not provide wheel for MacOS arm64.
I think you need to report to [azure-sdk-for-python](https://github.com/Azure/azure-sdk-for-python)

**Comment by jake-ise** [comment]
A work around that may help is to try an older version for now.

You can list older versions with:
`az extension list-versions -n ml --output table`

And then select one with:
`az extension add --name ml --version 2.23.0`

For me, `2.23.0` was the newest version that I could install without similar errors.

**Comment by AndriyDmytrenko** [comment]
Installed successfully version 2.25.1.
Thanks a lot!
