### ISSUE TITLE
Add support to list dangling resources in a resource group or subscription

### ISSUE THREAD

**Issue by afengli** [Azure/azure-cli#2862]
az resource list lists all resources, but provides no indication if a resource in unallocated or attached/in use.

We create multiple different resources and remove resources, but there are still occasionally some dangling resources left that there is no easy way to track.

For e.g. when a VM is terminated, we have to individually find any unattached disks or blobs and delete them and so on. Sometimes, we still miss some resources. 

Can we add support to identify any dangling resources and delete them?

**Comment by tjprescott** [comment]
The nature of what is dangling is highly subjective. A storage account can function independent of a VM, so how would we be able to ascertain it is orphaned?  The best way to accomplish this would be to create your related resources inside a resource group. The group can be deleted, cleaning up all the resources within that group. Based on the amount of engineering effort needed and the lack of demand for this feature, I will close this issue.
