### ISSUE TITLE
az maintenance assignment create-or-update-subscription giving generic Server side error 

### ISSUE THREAD

**Issue by freekbrouwer** [Azure/azure-cli#28630]
### Describe the bug

I run the below as a task to add the resources under a subscription to a dynamic scope.
When running the below command 

        az maintenance assignment create-or-update-subscription `
            --subscription $subscriptionId `
            --config-id $mcResourceID `
            --name $filterTag `
            --filter-os-types windows linux `
            --filter-tags "{PatchCycle:[$filterTag]}" `
            --filter-tags-operator All `
            --filter-locations 'westeurope' `
            --location westeurope `
            --debug

I get the error 
{"Message":"An error has occurred."}

The above is part of a FOR loop.
I have checked al the parameter if they are correct, which they all are.

This worked about 3 to 2 week ago, 

### Related command

az maintenance assignment create-or-update-subscription

### Errors

cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '5ebd7c78-16a6-4af9-9eb7-460a4390f619'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTEUROPE:20240325T152706Z:5ebd7c78-16a6-4af9-9eb7-460a4390f619'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'

### Issue script & Debug output

cli.azure.cli.core.azclierror: (None) An error has occurred.
Code: None
Message: An error has occurred.
az_command_data_logger: (None) An error has occurred.
Code: None
Message: An error has occurred.

### Expected behavior

I expect it to go through all the values i have setup and add the subscription/resources to the dynamic scope of the maintenance config.

### Environment Summary

az_command_data_logger: exit code: 1
cli.__main__: Command ran in 9.316 seconds (init: 0.224, invoke: 9.092)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3643 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc REDACTED"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

azure-cli                         2.58.0
core                              2.58.0
telemetry                          1.1.0
Extensions:
maintenance                        1.5.0
resource-graph                     2.1.0

Dependencies:
msal                              1.26.0
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\Redacted\.azure\cliextensions'

Python (Windows) 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]

### Additional context

Did not want to misuse other open standing issues

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by freekbrouwer** [comment]
Was fixed by using the --location global flag.

**Comment by freekbrouwer** [comment]
Can be closed!
