### ISSUE TITLE
Fotoğrafçılıkta yüz tanıma. 

### ISSUE THREAD

**Issue by ossanica** [Azure/azure-cli#28650]
IstanBul Bağcılar'da Profesyonel Fotoğrafçıyım  200.000 kışı  cıvarında  bu bölgeden ınsanların  bıyometrık ve portre çekmlernden oluşan bır arşıvım var.   Studio  fotoğrafçılığında yüz tanıma özelliğini kuulanmak  ve yararlanmak ıstıyorum.  Studyoya gren herkesın kamerayla görüntüsünü tespt edıp, arşivimde  kişiye ait tüm fotoğraf ve videoları tespit edip br sayfa veya sunum  ile rapor edeblmeli. Ayrıca günün renk calıbrasyon ayarlarına göre fotoğrafların renk ve yüz düzenleme gıbı basıtçe bır ışlem dahılınde bunu yapabılmelı.  Yüz tanıma özellği ayrıca  muşterı bılgılerını (''alındı - bakye'' gıbı  ve-veya müşterının takib edileblen bilgılerını  de özet geceblmel.  
Profesyonel anlamda FOTOĞRAFÇILIK  özveri ve bolca sabır ısteyen bır meslek olabılır.  Ben Teknik anlamda, üretkenlk ve yaratıcılığın zırvesındeyım.  Uzay teleskopları le yapılan ''objektf'' çekımlerın teknk ve optık bilımi açısından değerlendrp eleştırı ve önerlerm de derlyorum. Önümüzdekı yıllarda  gelecek olan o muazzam ütopya'nın  tasarımcıları arasındayım..   (Ayrıca Fotoğrafçı  model olabılecek (hem normal, hem denz altı hem uzay alanlarında fotoğraf çekeblecek )  yapay zeka  model eğıtımInde nasıl katkı sağlayabılırım. ? )

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
