### ISSUE TITLE
When `AZURE_CONFIG_DIR` is set, login context gets cleared by setting `random_config_dir=True`

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#28668]
ADO's Azure CLI task contains this step:

```
Setting AZURE_CONFIG_DIR env variable to: /mnt/vss/_work/_temp/.azclitask
```

In Knack, the config dir specified by env var takes higher precedence:

https://github.com/microsoft/knack/blob/e0c14114aea5e4416c70a77623e403773aba73a8/knack/config.py#L44

```py
        self.config_dir = os.environ.get('{}CONFIG_DIR'.format(env_var_prefix), default_config_dir)
```

So when `AZURE_CONFIG_DIR` is set, setting `config_dir` becomes a no-op for `AzCli`:

https://github.com/Azure/azure-cli/blob/c087891017008dd22c49d14742dc7d6480212cfd/src/azure-cli-core/azure/cli/core/mock.py#L44-L46

`self.config.config_dir` in this case is the value of `AZURE_CONFIG_DIR` (`/mnt/vss/_work/_temp/.azclitask`).

During `tearDown`, directory specified by `AZURE_CONFIG_DIR` gets deleted:

https://github.com/Azure/azure-cli/blob/b223dd9d4379d5c633a9f4dba4941ae791531126/src/azure-cli-testsdk/azure/cli/testsdk/base.py#L139-L144

This causes failure in the following `azdev test --live` command:

```
self = <azure.cli.core._profile.Profile object at 0x7f3d731794b0>
subscription = None

    def get_subscription(self, subscription=None):  # take id or name
        subscriptions = self.load_cached_subscriptions()
        if not subscriptions:
>           raise CLIError(_AZ_LOGIN_MESSAGE)
E           knack.util.CLIError: Please run 'az login' to setup account.

src/azure-cli-core/azure/cli/core/_profile.py:546: CLIError
```

Introduced by #25689

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
Local repro:

```sh
export AZURE_CONFIG_DIR='/home/user2/.azclitask'

az login --service-principal --username xxx --password xxx --tenant xxx
cat /home/user2/.azclitask/azureProfile.json

azdev test config
cat /home/user2/.azclitask/azureProfile.json
# cat: /home/user2/.azclitask/azureProfile.json: No such file or directory
```

**Comment by jiasli** [comment]
One possible solution is to temporarily alter `AZURE_CONFIG_DIR` while calling `super(DummyCli, self).__init__`:

https://github.com/Azure/azure-cli/blob/c087891017008dd22c49d14742dc7d6480212cfd/src/azure-cli-core/azure/cli/core/mock.py#L44-L53

`unittest.mock` provides a very handy [`patch.dict`](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.patch.dict) which can be used to patch `os.environ`.
