### ISSUE TITLE
In-place migration of VMSS from non-ephemeral to ephemeral OS disk and vice-versa

### ISSUE THREAD

**Issue by viveksingla08** [Azure/azure-cli#28669]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

**non-eph to eph** 
az vmss update --name "testvmss" --resource-group "EphemeralMigrationForCLI" --ephemeral-os-disk true --ephemeral-os-disk-placement ResourceDisk --os-disk-caching ReadOnly

**eph to non-eph** <TBD>
az vmss update --name "testvmss" --resource-group "EphemeralMigrationForCLI" --ephemeral-os-disk false 

### Resource Provider

Microsoft.Compute/VMSS

### Description of Feature or Work Requested

**Description of the feature**
Need support for upgrading non-ephemeral scale sets of SQL/Cosmos DB to ephemeral scale sets. Expectation is that SQL/Cosmos DB don’t have to rebuild their VMSS. While VMSS team is already working on the functionality, current AzCLI doesn't support enabling diff disk setting for an existing non-ephemeral VMSS. As SQL/Cosmos DB are looking to use AzCLi & SDK for some of the scenarios, same support needs to be added in all client tools.

**What is the ask?**
We need to support the migration of existing VMSS from non-eph to eph & vice-versa in az cli. We have already merged the PR in swagger release API version 2024-03-01. Currently, both of these operations are not supported. Along with the implementation, We need your help in deciding the right input format for converting ephemeral VMSS to non-ephemeral.

### Minimum API Version Required

2024-03-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/28049

### Target Date

2024-05-30

### PM Contact

viveksingla

### Engineer Contact

sumitsahu, aygaur

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
