### ISSUE TITLE
CLI support for Shared VNet 

### ISSUE THREAD

**Issue by ramandhillon84** [Azure/azure-cli#28662]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az network vnet subnet create -g $gName --vnet-name $vnetName -n $podSubnetName --default-outbound false **--sharing-scope Tenant**

### Resource Provider

Microsoft.network/virtualnetworks

### Description of Feature or Work Requested

Shared Vnet enables customers to deploy compute resources across subscriptions, to a Virtual Network owned by a different subscription that their own (but a part of the same AAD Tenant).

This is enabled by a new parameter in the Subnet configuration - **SharingScope,** which is set to **Tenant** for enabling sharing

### Minimum API Version Required

2023-11-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/27530

### Request Example

/subscriptions/subscriptionId/resourceGroups/sharedvnet-network-rg/providers/Microsoft.Network/virtualNetworks/SharedVnet1

```json
{
    "name": "SharedVnet1",
    "id": "/subscriptions/subscriptionId/resourceGroups/sharedvnet-network-rg/providers/Microsoft.Network/virtualNetworks/SharedVnet1",
    "type": "Microsoft.Network/virtualNetworks",
    "location": "westcentralus",
    "properties": {
        "provisioningState": "Succeeded",
        "addressSpace": {
            "addressPrefixes": [
                "10.0.0.0/16",
                "2404:f800:8000:120::/62"
            ]
        },
        "subnets": [
            {
                "name": "SharedVnet1-Subnet1",
                "id": "/subscriptions/subscriptionId/resourceGroups/sharedvnet-network-rg/providers/Microsoft.Network/virtualNetworks/SharedVnet1/subnets/SharedVnet1-Subnet1",
                "properties": {
                    "provisioningState": "Succeeded",
                    "addressPrefixes": [
                        "10.0.10.0/24",
                        "2404:f800:8000:121::/64"
                    ],
                    **"sharingScope": "Tenant",**
                    "networkSecurityGroup": {
                        "id": "/subscriptions/subscriptionId/resourceGroups/sharedvnet-network-rg/providers/Microsoft.Network/networkSecurityGroups/myVnetNsg"
                    },
                    "natGateway": {
                        "id": "/subscriptions/subscriptionId/resourceGroups/-sharedvnet-network-rg/providers/Microsoft.Network/natGateways/myNatGW"
                    },
                    "delegations": [],
                    "privateEndpointNetworkPolicies": "Disabled",
                    "privateLinkServiceNetworkPolicies": "Enabled",
                    "defaultOutboundAccess": false
                },
                "type": "Microsoft.Network/virtualNetworks/subnets"
            }
        ],
        "virtualNetworkPeerings": [],
        "enableDdosProtection": false
    }
}
```

### Target Date

2024-06-01

### PM Contact

rdhillon

### Engineer Contact

vlad.serov@microsoft.com

### Additional context

This is already available in Private Preview via JSON in West Central US region.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by ramandhillon84** [comment]
[like]  Ramandeep Singh Dhillon reacted to your message:
________________________________

**Comment by necusjz** [comment]
@ramandhillon84 we're working on https://github.com/Azure/azure-cli/issues/28506, they are quite similar, could you please explain their differences a little bit?
