### ISSUE TITLE
Provide --master-vm-size in Azure Container Service

### ISSUE THREAD

**Issue by jaydp17** [Azure/azure-cli#2867]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: interactive script

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
```sh
azure-cli (2.0.2)

acr (2.0.0)
acs (2.0.2)
appservice (0.1.2)
batch (2.0.0)
cloud (2.0.0)
component (2.0.0)
configure (2.0.2)
container (0.1.2)
core (2.0.2)
documentdb (0.1.2)
feedback (2.0.0)
find (0.0.1b1)
iot (0.1.2)
keyvault (2.0.0)
lab (0.0.1)
monitor (0.0.1)
network (2.0.2)
nspkg (2.0.0)
profile (2.0.2)
redis (0.1.1b3)
resource (2.0.2)
role (2.0.1)
sql (2.0.0)
storage (2.0.2)
vm (2.0.2)

Python (Darwin) 2.7.10 (default, Feb  6 2017, 23:53:20)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```
**OS Version:** What OS and version are you using?  
Answer here: macOS Sierra 10.12.4

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

---

### Description

When creating a cluster in Azure Container Service, it doesn't provide an option to specify the master VM size.

Right now the default master vm-size is `Standard_D2_v2`. 

The cli provides an option to specify the VM size of agents (`--agent-vm-size`), it would be nice if master vm-size (`--master-vm-size`) was also available.

**Comment by brendandburns** [comment]
There isn't an option for this in the ACS API currently.

I filed a feature request for this on the ACS repo:

https://github.com/Azure/ACS/issues/20

I'm closing this, since we'll support it when it is in the API.
