### ISSUE TITLE
Reimage of Ephemeral OS disk VMs to support updating the base OS disk

### ISSUE THREAD

**Issue by viveksingla08** [Azure/azure-cli#28670]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az vmss reimage --ids <vmss resource id> --forceUpdateOSDiskForEphemeral 

### Resource Provider

Microsoft.Compute/VMSS

### Description of Feature or Work Requested

Currently, reimage of ephemeral VMSS resets the VM to the original state. It does not bring the ephemeral OS disk to the latest version. We are introducing a new flag, forceUpdateOSDiskForEphemeral, which will bring the ephemeral OS disk to the latest version in VMSS.

### Minimum API Version Required

2024-03-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/28074

### Target Date

2024-08-30

### PM Contact

viveksingla

### Engineer Contact

sumitsahu, aygaur

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
> Target Date
2024-06-30

@viveksingla08 Due to the super busy schedule of this sprint, we didn't have the effort to develop this feature in this sprint. If this feature only adds a new parameter --zones without any breaking changes, could we schedule it for the next sprint (released at 07-02)?

**Comment by viveksingla08** [comment]
Its fine with us. I have updated the target release date. our release has got delayed due to some bugs being found.
