### ISSUE TITLE
Broken repo index

### ISSUE THREAD

**Issue by morkalfon** [Azure/azure-cli#28676]
### Describe the bug

While trying to pull azure-cli tools from https://packages.microsoft.com/repos/azure-cli/ I'm getting:
E: Failed to fetch https://packages.microsoft.com/repos/azure-cli/dists/focal/main/binary-amd64/Packages.gz  File has unexpected size (1456 != 1399). Mirror sync in progress? [IP: 13.107.213.41 443]
   Hashes of expected file:
    - Filesize:1399 [weak]

### Related command

apt-get install azure-cli

### Errors

File has unexpected size

### Issue script & Debug output

See command

### Expected behavior

Should fetch the repo

### Environment Summary

azure-cli latest

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zajca** [comment]
We are seeing a similar issue, but our error is related to a mismatch with hashes. It still seems related.

```
E: Failed to fetch https://packages.microsoft.com/repos/azure-cli/dists/focal/main/binary-all/Packages.gz  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:4113 [weak]
    - SHA512:f9aee0312e43c8dffa7ef34031c3cbaaddef8051c6cffd64deabf935b3e78ee1c2baefb51d9ffed76c308aa11f0acbb0a97acc8972e9698c98f0422d21a24770
    - SHA256:98703f91d266d8a2bfa9b77a6255c726d2640d35c6283deadb4aadebb2a32d2a
   Hashes of received file:
    - SHA512:fe923cd1cce43bd3faae75df06ce7d2d3106f70f1dde7998b119e5698b4893a9b782e85b236c488cdff8a44ef373d07fdc1226253f2aeeb6ab384531c2745404
    - SHA256:1275ec4a6c689b023c32227ff827fb6ad91af0af77da6dfe07f3d472ab74d98b
    - Filesize:4113 [weak]
   Last modification reported: Tue, 02 Apr 2024 07:13:37 +0000
   Release file created at: Tue, 05 Mar 2024 03:15:50 +0000
E: Failed to fetch https://packages.microsoft.com/repos/azure-cli/dists/focal/main/binary-amd64/Packages.gz  
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by dornfeder** [comment]
> We are seeing a similar issue, but our error is related to a mismatch with hashes. It still seems related.
> 
> ```
> E: Failed to fetch https://packages.microsoft.com/repos/azure-cli/dists/focal/main/binary-all/Packages.gz  Hash Sum mismatch
>    Hashes of expected file:
>     - Filesize:4113 [weak]
>     - SHA512:f9aee0312e43c8dffa7ef34031c3cbaaddef8051c6cffd64deabf935b3e78ee1c2baefb51d9ffed76c308aa11f0acbb0a97acc8972e9698c98f0422d21a24770
>     - SHA256:98703f91d266d8a2bfa9b77a6255c726d2640d35c6283deadb4aadebb2a32d2a
>    Hashes of received file:
>     - SHA512:fe923cd1cce43bd3faae75df06ce7d2d3106f70f1dde7998b119e5698b4893a9b782e85b236c488cdff8a44ef373d07fdc1226253f2aeeb6ab384531c2745404
>     - SHA256:1275ec4a6c689b023c32227ff827fb6ad91af0af77da6dfe07f3d472ab74d98b
>     - Filesize:4113 [weak]
>    Last modification reported: Tue, 02 Apr 2024 07:13:37 +0000
>    Release file created at: Tue, 05 Mar 2024 03:15:50 +0000
> E: Failed to fetch https://packages.microsoft.com/repos/azure-cli/dists/focal/main/binary-amd64/Packages.gz  
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> ```

same here.

**Comment by DianaSierb** [comment]
Same issue using  `curl -sL https://aka.ms/InstallAzureCLIDeb`
```
E: Failed to fetch https://packages.microsoft.com/repos/azure-cli/dists/focal/main/binary-all/Packages.gz  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:41[13](https://github.dev.global.tesco.org/Online-Technology/checkout/actions/runs/734035/job/2332902#step:4:14) [weak]
    - SHA512:f9aee0312e43c8dffa7ef34031c3cbaaddef8051c6cffd64deabf935b3e78ee1c2baefb51d9ffed76c308aa11f0acbb0a97acc8972e9698c98f0422d21a24770
    - SHA256:98703f91d266d8a2bfa9b77a6255c726d2640d35c6283deadb4aadebb2a32d2a
   Hashes of received file:
    - SHA512:fe923cd1cce43bd3faae75df06ce7d2d3106f70f1dde7998b119e5698b4893a9b782e85b236c488cdff8a44ef373d07fdc1226253f2aeeb6ab384531c2745404
    - SHA256:1275ec4a6c689b023c32227ff827fb6ad91af0af77da6dfe07f3d472ab74d98b
    - Filesize:4113 [weak]
   Last modification reported: Tue, 02 Apr 2024 07:13:37 +0000
   Release file created at: Tue, 05 Mar 2024 03:[15](https://github.dev.global.tesco.org/Online-Technology/checkout/actions/runs/734035/job/2332902#step:4:16):50 +0000
E: Failed to fetch https://packages.microsoft.com/repos/azure-cli/dists/focal/main/binary-amd64/Packages.gz  
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by sowa705** [comment]
Same here, we cannot install azure-cli on ubuntu 20.04 with the `curl -sL https://aka.ms/InstallAzureCLIDeb` command

**Comment by bebound** [comment]
Sorry for the inconvenience.
I've reported this to PMC (packages.microsoft.com) team.

**Comment by pfrydids** [comment]
It seems to have resolved itself for our CI environment.

**Comment by AndersRunningen** [comment]
we are still failing in our CI environments, do the PMC team confirm that this is fixed?

**Comment by daviddavis** [comment]
I cleared the cache at 11:56 UTC and it takes about 10 minutes. But I already see the new file:

```
$ curl https://packages.microsoft.com/repos/azure-cli/dists/focal/InRelease | grep Date
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3596  100  3596    0     0  32396      0 --:--:-- --:--:-- --:--:-- 32396
Date: Tue, 02 Apr 2024 07:13:34 +0000
```

**Comment by AndersRunningen** [comment]
seems to be working better now! Thank you for the explenation ;)

**Comment by DianaSierb** [comment]
Working now. Thank you!
