### ISSUE TITLE
Cannot install AzureCLI 

### ISSUE THREAD

**Issue by shaulimaya** [Azure/azure-cli#28675]
### Describe the bug

I am using devcontainer , and from today the installation of azure-cli stopped working.

It seems that the version was updated several hours ago
https://packages.microsoft.com/repos/azure-cli/dists/bookworm/

Any ideas ?

### Related command

rebuild devcontainer

### Errors

0.418 Err:3 https://packages.microsoft.com/repos/azure-cli bookworm/main amd64 Packages
0.418   File has unexpected size (1161 != 1100). Mirror sync in progress? [IP: 13.107.213.62 443]
0.418   Hashes of expected file:
0.418    - Filesize:1100 [weak]
0.418    - SHA512:dfe4412ef50567887ae10f815b017c95f98eef516bab53e1fd392e9012f891857da597253466e33fc1786a0f707ba75612c5530936e6bf30fd4ded9a8b567551
0.418    - SHA256:dbdc0cb77a09e8835195f500ef6c61545209c6ec68cdb8333a3b2a4f7c5f6699
0.418   Release file created at: Tue, 05 Mar 2024 03:15:40 +0000

### Issue script & Debug output

0.418 Err:3 https://packages.microsoft.com/repos/azure-cli bookworm/main amd64 Packages
0.418   File has unexpected size (1161 != 1100). Mirror sync in progress? [IP: 13.107.213.62 443]
0.418   Hashes of expected file:
0.418    - Filesize:1100 [weak]
0.418    - SHA512:dfe4412ef50567887ae10f815b017c95f98eef516bab53e1fd392e9012f891857da597253466e33fc1786a0f707ba75612c5530936e6bf30fd4ded9a8b567551
0.418    - SHA256:dbdc0cb77a09e8835195f500ef6c61545209c6ec68cdb8333a3b2a4f7c5f6699
0.418   Release file created at: Tue, 05 Mar 2024 03:15:40 +0000

### Expected behavior

installation of azure-cli

### Environment Summary

mcr.microsoft.com/devcontainers/python:3.10-bookworm

using feature:
ghcr.io/devcontainers/features/azure-cli:1

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by CalWyresHG** [comment]
Hey, 

@yonzhan is there any update on this?

**Comment by bebound** [comment]
Track in https://github.com/Azure/azure-cli/issues/28676
