### ISSUE TITLE
New CLI cmdlets Options for application gateway for Header Value Matcher Property Introduced in Header Rewrites Config

### ISSUE THREAD

**Issue by Sukhdev841** [Azure/azure-cli#28684]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Resource Provider

Microsoft.Network/ApplicationGateway

### Description of Feature or Work Requested

Azure Application Gateway has an existing feature called Header Rewrites, wherein users can do CRUD (Create, Read, Update and Delete) operations on the HTTP Headers. The Header Rewrite has a sub-field named ActionSet, and as feature enhancement a new field 'HeaderValueMatcher' is introduced in this field. The new cmdlets option should be able to set this optional field.

### Minimum API Version Required

2023-11

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/27477

### Target Date

2024-05-16

### PM Contact

jaysoni

### Engineer Contact

singhsukhdev

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jsntcy** [comment]
@Sukhdev841, is this feature targeted for Build event?

**Comment by jaesoni** [comment]
@necusjz @jsntcy any ETA that you can share? Thanks

**Comment by necusjz** [comment]
https://github.com/Azure/azure-cli/milestone/142
