### ISSUE TITLE
[CLI] Implicit Disk Creation from Snapshot and Disk Restore Points - Single VMs, VMs in an AvSet, VMs in VMSS

### ISSUE THREAD

**Issue by vishalprayag24** [Azure/azure-cli#28686]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az vm create -n vm1 -g linurg --image Ubuntu2204 --attach-data-disks /subscriptions/3f93e959-674b-4d15-a196-0b64f0ea1fba/resourceGroups/linurg/providers/Microsoft.Compute/disks/datadisk_1 --data-disk-sizes-gb 20 --generate-ssh-keys --source-snapshots-or-disks [SnapshotDisk-ARMID1] --snapshot-or-disk-source-disk-sizes-in-gb [2]  --source-disk-restore-point [DiskRestorepoint-ARMID2] --disk-restore-point-source-disk-sizes-in-gb [3] --storage-sku 1=UltraSSD_LRS 2=PremiumV2_LRS 3=PremiumV2_LRS

Note: [] --> these brackets in the command is to signify space separated list

### Resource Provider

Microsoft.Compute/VirtualMachines

### Description of Feature or Work Requested

This is to cover the implicit disk creation from snapshot scenario. It is an important so that disk restored from snapshot and the VM are aligned/co-locate with each other. 

Currently we don't support disk move for disks in import. We have to wait for background copy to finish. Instead customers should be able to create an implicit disk from a snapshot, so that there isn't a disk move as disk is placed rightly and customer don't have to wait for background to complete

Implicit disk creation avoids disk movement for new disks required for fault domain alignment or collocation as DiskRP already knows where to create the disks as the parent VMs’ location is known. Disk movement impacts the latency due to multiple hops in fetching the data and reliability due to increase in surface area as disks are spread across multiple clusters. We are trying to reduce disk movement as much as possible.

### Minimum API Version Required

2024-03-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/tree/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2024-03-01

https://github.com/Azure/azure-rest-api-specs/pull/27480/commits

### Target Date

Mid May 2024

### PM Contact

vishalprayag

### Engineer Contact

linugeorge

### Additional context

SDK support is in progress and expected to be ready by 04/12/2024

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
@vishalprayag24 Due to the fact that the workload of this sprint is already fully scheduled, we plan to develop this feature request on the next sprint, and the release time is **05-21**. Does this release time meet your expectations?

**Comment by vishalprayag24** [comment]
Hi @zhoxing-ms, just wanted to confirm the timeline from customer perspective. Are you saying by 21st May 2024, customers will be able to use the feature? If that's not the case, at what date the feature is accessible to the customers?

**Comment by zhoxing-ms** [comment]
> just wanted to confirm the timeline from customer perspective. Are you saying by 21st May 2024, customers will be able to use the feature?

@vishalprayag24 Yes, exactly
