### ISSUE TITLE
Prefer the local image name of the same subscription to global image alias such a "RHEL" to avoid unintended  charge.

### ISSUE THREAD

**Issue by tanaka-takayoshi** [Azure/azure-cli#2868]
When creating a VM from an image, we can use aliases defined here.
https://github.com/Azure/azure-cli/blob/4c98204f3baf42a021c02f691e310e651e5ce546/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_actions.py#L70-L93
(test code) https://github.com/Azure/azure-cli/blob/011e1eaa0902ac7da47d473b989417f00730cf47/src/command_modules/azure-cli-vm/tests/aliases.json

However, we also create an image with the same name of these aliases. So I can create my customer image with name "rhel".Then I intend to create a new VM from this customer image with the command.
```
$ az vm create -n testvm  -g rhel-base -l japanwest --image rhel --storage-sku Standard_LRS --size Standard_A1 --authentication-type password --admin-password clouduser
```

Though I intended to create VM from my custom image, but the VM is created with RHEL VM on the marketplace. It means it costs extra unintended marketplace charge.

I know I can specify the resource id of an image to create new VM with my custom image. But, users may think they can specify the image name if the location and Resource group of the VM is same as those of the custom image.

I have some ideas to improve this situation. Could you tell me your thought?

- Azure CLI 2.0 always prefer the image name when the local image name has the same name of aliases
- Azure CLI 2.0 outputs the warning message, when the user create a VM with one of aliases and the user, has the image whose name is same of the alises.
- Azure CLI 2.0 does nothing about this issue as it's not CLI specific issue. But the document should be improved. (in this case I'll create a documentation fix PR to azure docs repo)

**Comment by tjprescott** [comment]
Hi @tanaka-takayoshi, I think your suggestions make a lot of sense.  The order

**Comment by yugangw-msft** [comment]
Most `VM/VMSS create` use images defined in the alias doc. The number I was told is 80%+. Hence, I am not convinced we have to search managed images first, which incurs one extra rest call (mostly not useful and hurts the command perf). Also, it is possible other people prefer aliased common images, so this change will break them. Last, using a managed image is till very minority scenario, so I am not convinced we have to pull the trigger right now.
If using a resource id is inconvenient, I suggest use a new image name when you create it, be more specific is always good. Please let me know if picking a new image name is not applicable as well. 
Agreed, we should update doc to make the logic clear.

**Comment by tjprescott** [comment]
I have already added debug statements in the VM/VMSS create command (visible with --debug) which show how the storage profile is resolved (i.e. managed image vs. marketplace URN).

**Comment by adewaleo** [comment]
Given the discussion above and that the "storage profile" of the image is emitted in debug output, I will be closing this issue. 

I would also like to add that If you really need to disambiguate between custom images and managed images, you can use a different name from the alias. Moreover, you can ask your customers to confirm that the result of `az vm show -n exampleVM` has the correct storage profile. If the vm was created from an image, the imageReference under storageProfile would show details for a managed image. Users can run: 
```az vm show -n exampleVM-g ova-test-1 --query "storageProfile.imageReference"```

If the current documentation for `--image` can be improved, feel free to let me know how it could be improved or to make a change to it yourself.
