### ISSUE TITLE
az login fails if password contains ")"

### ISSUE THREAD

**Issue by TheOnlyWei** [Azure/azure-cli#28692]
### Test 1
If you run `az login` with a password that contains closing parenthesis `)`, it will throw the following error.
```
az login --service-principal -u "<app id>" -p ")" --tenant "<tenant id>"
```
**Error**
```
--tenant was unexpected at this time.
```

### Test 2
If you run with a password containing a closing parenthesis that is padded with other characters, you get an error that whatever is after the closing parenthesis is "unexpected at this time":
```
az login --service-principal -u "<app id>" -p  "1ab)2ab" --tenant "<tenant id>"
```
**Error**
```
2ab was unexpected at this time.
```

### Test 3
Same issue with username and password login.
```
az login -u "<username>" -p ")" -t "<tenant id>"
```

**Error**
```
-t was unexpected at this time.
```

### Related command

```
az login --service-principal -u "<app id>" -p ")" --tenant "<tenant id>"
```

### Errors

```
az : --tenant was unexpected at this time.
```

### Issue script & Debug output

No useful debug output.

### Expected behavior

Should not throw an error if `)` character is in the password.

### Environment Summary

```
 
azure-cli                         2.58.0 *

core                              2.58.0 *
telemetry                          1.1.0

Extensions:
azure-devops                       1.0.0

Dependencies:
msal                              1.26.0
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Program Files\Common Files\AzureCliExtensionDirectory'

Python (Windows) 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by TheOnlyWei** [comment]
Same issue as https://github.com/Azure/azure-cli/issues/25173. Seems like a PowerShell issue.

**Comment by jiasli** [comment]
See https://github.com/Azure/azure-cli/issues/15529
