### ISSUE TITLE
monitor log-analytics cluster is Missing Available SKUs for Capacity Reservations

### ISSUE THREAD

**Issue by millerjryan** [Azure/azure-cli#28696]
### Describe the bug

az monitor log-analytics cluster errors out when attempting to put in any sku other than 500, 1000, 2000, 5000 even though LA supports 100, 200, 300, 400, 500, 1000, 2000, 5000, 10000, 25000, 50000. 

### Related command

az monitor log-analytics cluster

### Errors

100 is not supported.  Did you mean 1000?

### Issue script & Debug output

NA - We don't have any debug since this is strictly just a limitation of what is supported by the parameter

### Expected behavior

Parameter should accept 100, 200, 300, 400, 500, 1000, 2000, 5000, 10000, 25000, 50000 as SKUs

### Environment Summary

azure-cli                         2.59.0

core                              2.59.0
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
log-analytics                      0.2.2
ml                                2.25.0
scheduled-query                    0.2.2
ssh                                2.0.3

Dependencies:
msal                              1.27.0
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.9'
Extensions directory '/home/joshua/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.19 (main, Mar 28 2024, 18:56:59)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by AllyW** [comment]
@millerjryan we are upgrading our cluster api-version to latest version and please track the linked pr for release.
