### ISSUE TITLE
added the new query param to retrieve the capacity reservation group resource ids that are owned and shared by a subscription in the List Capacity reservation Group API 

### ISSUE THREAD

**Issue by hari-bodicherla** [Azure/azure-cli#28690]
**Related command**
az capacity reservation group list

**Resource Provider**
Microsoft.Compute

**Is your feature request related to a problem? Please describe.**
Today CapacityReservationGroup allows creating capacity reservations that can be used only in the subscription where the reservation is created. we have now allowed Capacity Reservation Group to be shared across subscriptions.For customers to be able to identify capacity reservation groups which are shared with subscription there is no list api to get the list of shared Capacity reservation groups for a given Subscription as well as mininal metadata like resource ids of crgs owned by a subscription or shared.

**Describe the solution you'd like**
For customers to be able to identify capacity reservation groups which are shared with subscription, owned by subscription we have introduced a query param called ResourceIdsOnly with allowed enums of "CreatedInSubscription", "SharedWithSubscription" and "All"

**Note**: This property is an optional parameter. by default if the property is not passed then the behaviour will be same as existing behavior where we return all the Capacity reservation group entities owned by the subscription with full details like capacity reservation group model data . If the parameter is passed with allowed enums, then we should be returning the resource ids only for the relevant enum value passed in the List request.

**Note** : This property is only applicable in the Subscription scope for the az capacity reservation group list , so we should not allow the ResourceGroup set when we use this new param in the cmdlet.

**Describe alternatives you've considered**
The alternatives would be customers getting the capacity reservations which are present in the other subscriptions and get the subscriptions from the data model metadata of CRG and then aggregate manually to get this reverse mapping of subscription to shared Capacity reservation groups

**Additional context**
The Cmd should be looking like

az capacity reservation group list --resource-group
                                   [--vm-instance]
                                   [--vmss-instance] 
                                   [--resource-ids-only] 

The new param called "resource-ids-only" has the 3 allowed enum string values which are "CreatedInSubscription", "SharedWithSubscription" and "All" 

As mentioned in the above note, this is not applicable when the "resource-group" param is set as this is allowed only at the subscription scope (which is default scope) and "resource-group" param is optional.

Swagger changes PR: https://github.com/Azure/azure-rest-api-specs/pull/27510 

Please let us know if you need more details.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
Could you use the [Microsoft internal feature template](https://github.com/Azure/azure-cli/issues/new?assignees=&labels=feature-request&projects=&template=Service_team_request.yml) to create this requirement? 
It requires you to supplement some necessary information for CLI team planning and development it, such as `Target Date`, `Minimum API Version Required`
