### ISSUE TITLE
Authentication token not being generated for GWLB cross-tenant scenarios

### ISSUE THREAD

**Issue by thisisanniefang** [Azure/azure-cli#28705]
### Describe the bug

Even with the proper RBAC permissions, any updates to a Standard Public LB that is chained to a GWLB will fail - I believe this may be due to the fact that the authentication token is only being generated/passed during the chaining operation, and not all operations to the LB which trigger the same access check. 

Steps to repro the issue:

1. Create a Standard Public LB in Sub 1
2. Create a GWLB in Sub 2 (different tenant)
3. Ensure the user has the "Permission for the resource provider operation Microsoft.Network/loadBalancers/frontendIPConfigurations/join/action"
4. Chain the Standard Public LB to the GWLB
5. Attempt to update any component of the Standard Public LB via CLI (this will fail with the following error message)

![image](https://github.com/Azure/azure-cli/assets/32456734/abfeae2e-615e-4fe7-bfce-685f016e5d57)

### Related command

az network lb (all commands likely)

### Errors

(LinkedAuthorizationFailed) The client has permission to perform action 'Microsoft.Network/loadBalancers/frontendIPConfigurations/join/action' on scope '/subscriptions/6bb4a28a-db84-4e8a-b1dc-fabf7bd9f0b2/resourceGroups/annie-consumerlb/providers/Microsoft.Network/loadBalancers/aclb-lb', however the current tenant '72f988bf-86f1-41af-91ab-2d7cd011db47' is not authorized to access linked subscription 'ba7e135e-8399-483d-9875-ad6faf28ff3b'.
Code: LinkedAuthorizationFailed
Message: The client has permission to perform action 'Microsoft.Network/loadBalancers/frontendIPConfigurations/join/action' on scope '/subscriptions/6bb4a28a-db84-4e8a-b1dc-fabf7bd9f0b2/resourceGroups/annie-consumerlb/providers/Microsoft.Network/loadBalancers/aclb-lb', however the current tenant '72f988bf-86f1-41af-91ab-2d7cd011db47' is not authorized to access linked subscription 'ba7e135e-8399-483d-9875-ad6faf28ff3b'.

### Issue script & Debug output

N/A

### Expected behavior

Expected behavior is any update to the load balancer should succeed as long as the user has the appropriate join/action and other RBAC permissions necessary.

### Environment Summary

azure-cli                         2.31.0 *

core                              2.31.0 *
telemetry                          1.0.6 *

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\anniefang\.azure\cliextensions'

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

You have 3 updates available. Consider updating your CLI installation with 'az upgrade'

**Comment by necusjz** [comment]
it is supposed to work in the latest version of azure cli

**Comment by thisisanniefang** [comment]
Hi @necusjz I upgraded and tested again, it is still failing - I don't think it works even with the latest version:

![image](https://github.com/Azure/azure-cli/assets/32456734/6e157a6b-2e52-41a3-a43f-1e000e2e2dca)

As mentioned in the issue, the chaining command works fine (updating the LB frontend w/ the GWLB reference), however, any following changes to the consumer LB fail

**Comment by necusjz** [comment]
could you please explain more about the 4th step "Chain the Standard Public LB to the GWLB"?

**Comment by thisisanniefang** [comment]
@necusjz chaining just means updated the Standard/consumer LB's gatewayLoadBalancer property to reference the GWLB's frontend IP configuration, feel free to ping me directly on Teams if it's easier to discuss and troubleshoot together
