### ISSUE TITLE
[Network] Support API version 2017-03-01

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#2870]
**Application Gateways**
- [x] Add `application-gateway waf-config list-rule-sets` command
- [x] Update `application-gateway waf-config set` to support `rule-set-type, rule-set-version, disabled-rule-groups`

**VPN Connection**
- [x] Support `policy-based-traffic-selectors` flag in `vpn-connection` commands
- [x] Support `IPsec-policies` collection in `vpn-connection` commands

**Traffic Manager**
- [x] Add support for geo mapping to `traffic-manager endpoint create`
- [x] Add support for geographic hierarchies

**Comment by tjprescott** [comment]
cc/ @aanandr for VPN connection scnearios

**Comment by nneul** [comment]
Will this also add ability to see/update (even if it's via raw/json 'set' or 'update' type requests) the enabled rulesets (2.x,3.x) and rules (i.e. 920421) for the application-gateway waf mode? It appears that currently it won't even return the data in the show command.

**Comment by tjprescott** [comment]
See, probably. Update...maybe?  The Swagger for the API version only lists one new operation, which is list. It is possible you'd be able to alter those with the generic set commands.

**Comment by nneul** [comment]
Actually, I think that's separate (the get list of rules) - there is a separate section in the rest output described here:

https://docs.microsoft.com/en-us/rest/api/applicationgateway/get-application-gateway

```
  "requestRoutingRules": [
    {
 ...   }
  ],
  "webApplicationFirewallConfiguration": {
    "enabled": true | false,
    "firewallMode": "Prevention | Detection",
    "ruleSetType": "OWASP",
    "ruleSetVersion": "2.2.9 | 3.0",
    "disabledRuleGroups": [
      {
        "ruleGroupName":"{rulegroupName}", 
        "rules":[
          "{ruleId}"
        ]
      }
    ]
  }
}
```

Note the additional fields in the json that are returned? Those aren't visible in current client. enabled and firewallmode are shown in current code.

**Comment by tjprescott** [comment]
That's probably because the current API version for networking is 2016-09-01 and those parameters are not supported by it (at least according to the swagger). So when the service returns the object, it returns it without those fields (or the SDK might strip them away). When the CLI moves up to support these API versions, these should appear, and then whether they can be modified using the generic update command depends entirely on the service implementation.

**Comment by nneul** [comment]
Interesting. It appears that I am able to see those additional properties via 'az resource show' - so maybe I can leverage that path to update them as well. Will try it out.

**Comment by nneul** [comment]
Sweet. It appears to have worked. Probably off-topic now, but including here in case anyone searches and finds above discussion - $id is the resource id of the app gateway. 

```az resource update --verbose \
    --id $id \
    --set properties.webApplicationFirewallConfiguration.enabled=true \
    --set properties.webApplicationFirewallConfiguration.firewallMode=Prevention \
    --set properties.webApplicationFirewallConfiguration.ruleSetType=OWASP \
    --set properties.webApplicationFirewallConfiguration.ruleSetVersion=3.0 \
    --set properties.webApplicationFirewallConfiguration.disabledRuleGroups=@waf-disabled-rules.json
```
