### ISSUE TITLE
Update ADF secret not working 

### ISSUE THREAD

**Issue by vandanchev** [Azure/azure-cli#28717]
### Describe the bug

Trying to update an already existing secret in an FD profile as per the documentation and example but I keep getting denied as the operation seems not allowed.

Docu:
https://learn.microsoft.com/en-us/cli/azure/afd/secret?view=azure-cli-latest#az-afd-secret-update

### Related command

az afd secret update -g group --profile-name profile --secret-name secret1 --use-latest-version

### Errors

Command fails with:

ERROR: (OperationNotAllowed) Update is not allowed for secrets.
Code: OperationNotAllowed
Message: Update is not allowed for secrets.The command

### Issue script & Debug output

az : DEBUG: cli.knack.cli: Command arguments: ['afd', 'secret', 'update', '-g', '****', '--profile-name', '****', '--secret-name', '*****', '--use-latest-version', '--debug']
At line:1 char:1
+ az afd secret update -g **** --profile-name *** - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (DEBUG: cli.knac...on', '--debug']:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x017DA4A8>, <function OutputProducer.on_global_arguments at 0x019DD6E8>, <function CLIQuery.on_global_arguments at 0x019F8340>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Modules found from index for 'afd': ['azure.cli.command_modules.cdn']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: cdn                       0.016        39       133
DEBUG: cli.azure.cli.core: Total (1)                 0.016        39       133
DEBUG: cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
DEBUG: cli.azure.cli.core: Loading extensions:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
DEBUG: cli.azure.cli.core: Total (0)                 0.000         0         0  
DEBUG: cli.azure.cli.core: Loaded 39 groups, 133 commands.
DEBUG: cli.azure.cli.core: Found a match in the command table.
DEBUG: cli.azure.cli.core: Raw command  : afd secret update
DEBUG: cli.azure.cli.core: Command table: afd secret update
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03BDC538>]
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\Ivan.A.Danchev\.azure\commands\2024-04-09.12-41-33.afd_secret_update.44076.log'.
INFO: az_command_data_logger: command args: afd secret update -g {} --profile-name {} --secret-name {} --use-latest-version --debug
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03C03808>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03C17730>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03C17928>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x019DD730>, <function CLIQuery.handle_query_parameter at 0x019F8388>, <function register_ids_argument.<locals>.parse_ids_arguments at 
0x03C178E0>]
WARNING: Command group 'afd' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
DEBUG: cli.azure.cli.core.commands.client_factory: Getting management service client client_type=CdnManagementClient
DEBUG: cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\Ivan.A.Danchev\\.azure\\msal_token_cache.bin', encrypt=True
DEBUG: cli.azure.cli.core.auth.binary_cache: load: C:\Users\Ivan.A.Danchev\.azure\msal_http_cache.bin
DEBUG: urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
DEBUG: msal.authority: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/82913d90-8716-4025-a8e8-4f8dfa42b719/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 
'jwks_uri': 'https://login.microsoftonline.com/82913d90-8716-4025-a8e8-4f8dfa42b719/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': 
['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/82913d90-8716-4025-a8e8-4f8dfa42b719/v2.0', 
'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/82913d90-8716-4025-a8e8-4f8dfa42b719/oauth2/v2.0/authorize', 
'device_authorization_endpoint': 'https://login.microsoftonline.com/82913d90-8716-4025-a8e8-4f8dfa42b719/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 
'https://login.microsoftonline.com/82913d90-8716-4025-a8e8-4f8dfa42b719/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 
'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/82913d90-8716-4025-a8e8-4f8dfa42b719/kerberos', 'tenant_region_scope': 'EU', 'cloud_instance_name': 
'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
DEBUG: msal.application: Broker enabled? False
DEBUG: cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
DEBUG: cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
DEBUG: msal.application: Cache hit an AT
DEBUG: msal.telemetry: Generate or reuse correlation_id: 74204bf2-af18-485f-820b-b2bd0efb67e9
DEBUG: cli.azure.cli.core.sdk.policies: Request URL: 
'https://management.azure.com/subscriptions/****/resourceGroups/****/providers/Microsoft.Cdn/profiles/****t/secrets/****?api-version=2021-06-01'
DEBUG: cli.azure.cli.core.sdk.policies: Request method: 'GET'
DEBUG: cli.azure.cli.core.sdk.policies: Request headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '5a089543-f655-11ee-bfd1-5c80b646adec'
DEBUG: cli.azure.cli.core.sdk.policies:     'CommandName': 'afd secret update'
DEBUG: cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g --profile-name --secret-name --use-latest-version --debug'
DEBUG: cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.53.0 (MSI) azsdk-python-mgmt-cdn/12.0.0 Python/3.10.10 (Windows-10-10.0.22631-SP0)'
DEBUG: cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
DEBUG: cli.azure.cli.core.sdk.policies: Request body:
DEBUG: cli.azure.cli.core.sdk.policies: This request has no body
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
DEBUG: urllib3.connectionpool: https://management.azure.com:443 "GET 
/subscriptions/****/resourceGroups/***/providers/Microsoft.Cdn/profiles/***/secrets/****?api-version=2021-06-01 HTTP/1.1" 404 79
DEBUG: cli.azure.cli.core.sdk.policies: Response status: 404
DEBUG: cli.azure.cli.core.sdk.policies: Response headers:
DEBUG: cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Length': '79'
DEBUG: cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
DEBUG: cli.azure.cli.core.sdk.policies:     'Expires': '-1'
DEBUG: cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '48c58027-e240-4ca7-aecf-58b9e9589b7b'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '5a089543-f655-11ee-bfd1-5c80b646adec'
DEBUG: cli.azure.cli.core.sdk.policies:     'Server': 'Kestrel'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11989'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'd60607ce-e778-4434-9c57-52b2fdcddd23'
DEBUG: cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'POLANDCENTRAL:20240409T094134Z:d60607ce-e778-4434-9c57-52b2fdcddd23'
DEBUG: cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
DEBUG: cli.azure.cli.core.sdk.policies:     'Date': 'Tue, 09 Apr 2024 09:41:34 GMT'
DEBUG: cli.azure.cli.core.sdk.policies: Response content:
DEBUG: cli.azure.cli.core.sdk.policies: {"error":{"code":"NotFound","message":"The requested resource was not found."}}
DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/cdn/custom/custom_afdx.py", line 810, in update_afd_secret
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/cdn/operations/_secrets_operations.py", line 326, in get
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/exceptions.py", line 107, in map_error
azure.core.exceptions.ResourceNotFoundError: (NotFound) The requested resource was not found.
Code: NotFound
Message: The requested resource was not found.
ERROR: cli.azure.cli.core.azclierror: (NotFound) The requested resource was not found.
Code: NotFound
Message: The requested resource was not found.
ERROR: az_command_data_logger: (NotFound) The requested resource was not found.
Code: NotFound
Message: The requested resource was not found.
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03BDC658>]
INFO: az_command_data_logger: exit code: 3
INFO: cli.__main__: Command ran in 1.556 seconds (init: 0.481, invoke: 1.075)
INFO: telemetry.main: Begin splitting cli events and extra events, total events: 1
INFO: telemetry.client: Accumulated 0 events. Flush the clients.
INFO: telemetry.main: Finish splitting cli events and extra events, cli events: 1
INFO: telemetry.save: Save telemetry record of length 3546 in cache
INFO: telemetry.main: Begin creating telemetry upload process.
INFO: telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\Ivan.A.Danchev\.azure"
INFO: telemetry.process: Return from creating process
INFO: telemetry.main: Finish creating telemetry upload process.

### Expected behavior

As per the documentation and example, we should be able to update the secret to use the latest version.

### Environment Summary

azure-cli                         2.53.0 *

core                              2.53.0 *
telemetry                          1.1.0

Extensions:
acrtransfer                        1.1.0
application-insights               1.0.0
azure-devops                      0.26.0
containerapp                      0.3.41
front-door                        1.0.17
log-analytics                      0.2.2
support                            1.0.3

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\Ivan.A.Danchev\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by vandanchev** [comment]
> Hi @vandanchev,
> 
> 2.53.0 is not the latest Azure CLI(2.59.0).
> 
> If you haven't already attempted to do so, please upgrade to the latest Azure CLI version by following https://learn.microsoft.com/en-us/cli/azure/update-azure-cli.

Already tried with the latest CLI(2.59.0) but I got the same error.

**Comment by caiovbraga** [comment]
Any updates? This was working before
