### ISSUE TITLE
Getting copy status via "az storage blob show" now returns error

### ISSUE THREAD

**Issue by jpalermo** [Azure/azure-cli#28727]
### Describe the bug

Following instructions found in #1787 we've been using `az storage blob show` to determine when a copy operation has completed. Sometime in the last month this has changed from returning the JSON noting that the copy operation has not finished to the following error instead
```
There is currently a pending copy operation.
RequestId:30b04d02-001c-0044-628b-8b27fb000000
Time:2024-04-10T21:07:29.2468935Z
ErrorCode:PendingCopyOperation
Error:None
```
I see reports of this over in a [closed issue](https://github.com/Azure/azure-cli/issues/10160#issuecomment-2020517478), but wanted to make a new issue to track this problem.

### Related command

`az storage blob show` on the destination blob of a new `az storage blob copy start` command.

### Errors

There is currently a pending copy operation.
RequestId:30b04d02-001c-0044-628b-8b27fb000000
Time:2024-04-10T21:07:29.2468935Z
ErrorCode:PendingCopyOperation
Error:None

### Issue script & Debug output

Skipping as we saw this issue suddenly appear without updating the CLI, so it seems like an error being generated from the Azure side of things.

### Expected behavior

The blob show json is returned with the current status of the copy operation

### Environment Summary

Also saw the same behavior on an older version and in another installation that didn't have `storage-blob-preview` installed
```
azure-cli                         2.59.0

core                              2.59.0
telemetry                          1.1.0

Extensions:
storage-blob-preview               0.5.0

Dependencies:
msal                              1.27.0
azure-mgmt-resource             23.1.0b2

Python location '/opt/homebrew/Cellar/azure-cli/2.59.0/libexec/bin/python'
Extensions directory '/Users/jpalermo/.azure/cliextensions'

Python (Darwin) 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by calvinhzy** [comment]
Hi @jpalermo , recently there have been a service side change DC "XStoreConfigSettings.NativeXfe.Common.BackgroundSettings.EnableCopyBlobNotInProgressFix" that changed the current CLI behavior. Will have a fix for this by 4/30 which is our next release. Thanks.

**Comment by chloeyin** [comment]
Same here
