### ISSUE TITLE
az afd origin-group create missing sessionAffinityState arg

### ISSUE THREAD

**Issue by ReStoreSupport** [Azure/azure-cli#28721]
**Related command**
az afd origin-group create

**Is your feature request related to a problem? Please describe.**
if you create a frontdoor origin group from azure portal you can check the checkbox Enable session affinity but on az cli this settings is missing

**Describe the solution you'd like**
a new arg on the command called session_affinity_state where you can specify Enabled/Disabled

**Describe alternatives you've considered**
i've try the arg --set properties.session_affinity_state=Disabled without success

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by stefank94** [comment]
The same argument when using `az afd origin-group update` would be very useful as well.
