### ISSUE TITLE
enable-purge-protection for Keyvault not allowed to be set to false through az cli

### ISSUE THREAD

**Issue by roelof-adam** [Azure/azure-cli#28732]
### Describe the bug

enable-purge-protection for Keyvault not allowed to be set to false when using az cli

"azure-cli": "2.59.0"

### Related command

```
az keyvault create --name $kv --resource-group $rg --location "westeurope" --enable-purge-protection false
```

### Errors

```
We will enable rbac authorization by default in the near future, please manually specify --enable-rbac-authorization if you want to overwrite the default value.
(BadRequest) The property "enablePurgeProtection" cannot be set to false. Enabling the purge protection for a vault is an irreversible action.
Code: BadRequest
Message: The property "enablePurgeProtection" cannot be set to false. Enabling the purge protection for a vault is an irreversible action.
```

### Issue script & Debug output

-

### Expected behavior

allowed to be set false

### Environment Summary

{
  "azure-cli": "2.59.0",
  "azure-cli-core": "2.59.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "account": "0.2.5",
    "aks-preview": "2.0.0b8"
  }
}

### Additional context

there seems to be an existing issue:
https://github.com/Azure/azure-rest-api-specs/issues/18106

The question in this bug is also to update the docs page to reflect the bug: documentation is incorrect atm

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by evelyn-ys** [comment]
@roelof-adam Yes as you can see from the err msg, keyvault server side has restrict enabling purge protection, what you can change is the retention days

**Comment by roelof-adam** [comment]
This means I can never create a KV through az cli without purge protection?

**Comment by roelof-adam** [comment]
any update?

**Comment by evelyn-ys** [comment]
> Hi @evelyn-ys, thank you for the reply, does this mean I can never create a KV through az cli without purge protection?

seems so. I'd defer this question to keyvault service PM @jlichwa

**Comment by jlichwa** [comment]
The entire flag should be skipped instead to have purge protection not enabled.

**Comment by roelof-adam** [comment]
@yonzhan The issue the bot mentions is indeed similar, and has been open since April 2021, it should be an easy fix, any further actions should take place on that issue, closing this
