### ISSUE TITLE
'az deployment group' got AttributeError 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by mynadx** [Azure/azure-cli#28730]
### Describe the bug

Hi team,
az command got 'str ' object has no attribute 'get'. I had try to download the template file and parameter file . Then I imported template through console. It worked well and created resources successfully. But command is not working.

### Related command

az deployment group create 
--name ${RESOURCE_NAME}
--resource-group ${RESOURCE_GROUP}
--template-file $templatefile 
--parameters $parameters 
--debug

### Errors

![adf-1](https://github.com/Azure/azure-cli/assets/49837189/02eb95a3-1eba-4f84-9fa6-1f7454952f99)
![adf-2](https://github.com/Azure/azure-cli/assets/49837189/9841c392-ca95-44e9-a9d3-1c2ab7144a5c)

### Issue script & Debug output

Attached are part of template and parameter file.
As company security policy, I can not stick any text and code.

### Expected behavior

expect use as deployment group create command to create adf resources.

### Environment Summary

azure-cli 2.59.0
core 2.59.0
telemetry 1.1.0
dependencies:
msal 1.27.0
azure-mgmt-resource 23.1.0b2

python version: 3.11

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by mynadx** [comment]
![param](https://github.com/Azure/azure-cli/assets/49837189/39e52fe2-c17d-452f-9874-8689f366cc76)
![template](https://github.com/Azure/azure-cli/assets/49837189/58b44447-9697-485c-994e-4d3c18d96bc9)
template and param attached.
