### ISSUE TITLE
az aks mesh upgrade command with prompt for yes/no should accept --yes/-y argument

### ISSUE THREAD

**Issue by savaradh** [Azure/azure-cli#28739]
### Describe the bug

az aks mesh upgrade complete command prompts a yes/no confirmation to successfully remove the old mesh configuration. However, this command does not accept --yes or -y passed as an argument.

Nor does it accept piping commands like "yes | az aks mesh upgrade complete ....". The piping command throws NoTTYException

### Related command

az aks mesh upgrade complete --resource-group "myAKSRG" --name myAKSCluster

### Errors

When providing --yes argument

unrecognized arguments: --yes

When piping yes

WARNING: The behavior of this command has been altered by the following extension: aks-preview
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 701, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 334, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/saravanan/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2625, in aks_mesh_upgrade_complete
    return _aks_mesh_update(
  File "/home/saravanan/.azure/cliextensions/aks-preview/azext_aks_preview/custom.py", line 2682, in _aks_mesh_update
    mc = aks_update_decorator.update_azure_service_mesh_profile(mc)
  File "/home/saravanan/.azure/cliextensions/aks-preview/azext_aks_preview/managed_cluster_decorator.py", line 4016, in update_azure_service_mesh_profile
    mc.service_mesh_profile = self.context.update_azure_service_mesh_profile()
  File "/home/saravanan/.azure/cliextensions/aks-preview/azext_aks_preview/managed_cluster_decorator.py", line 2254, in update_azure_service_mesh_profile
    if prompt_y_n(msg, default="y"):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/prompting.py", line 71, in prompt_y_n
    return _prompt_bool(msg, 'y', 'n', default=default, help_string=help_string)
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/prompting.py", line 79, in _prompt_bool
    verify_is_a_tty()
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/prompting.py", line 28, in verify_is_a_tty
    raise NoTTYException()
knack.prompting.NoTTYException

### Issue script & Debug output

cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f556e4d9160>, <function OutputProducer.on_global_arguments at 0x7f556e3f3ca0>, <function CLIQuery.on_global_arguments at 0x7f556e38b280>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'aks': ['azext_aks_preview', 'azure.cli.command_modules.acs']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: acs                       0.082        14        76
cli.azure.cli.core: Total (1)                 0.082        14        76
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: ai-examples               0.196         1         1  /usr/lib/python3.9/site-packages/azure-cli-extensions/ai-examples
cli.knack.cli: Event: CommandLoader.OnLoadCommandTable []
cli.azure.cli.core: aks-preview               0.024        18        91  /home/saravanan/.azure/cliextensions/aks-preview
cli.azure.cli.core: Total (2)                 0.220        19        92  
cli.azure.cli.core: Loaded 21 groups, 103 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : aks mesh upgrade complete
cli.azure.cli.core: Command table: aks mesh upgrade complete
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f556d8395e0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/saravanan/.azure/commands/2024-04-12.21-37-06.aks_mesh_upgrade_complete.1953.log'.
az_command_data_logger: command args: aks mesh upgrade complete --yes --resource-group {} --name {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f556d7e11f0>]
cli.knack.cli: Event: CommandLoader.OnLoadArguments []
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f556d71b1f0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f556d73e0d0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
urllib3.connectionpool: Starting new HTTPS connection (1): app.aladdin.microsoft.com:443
urllib3.connectionpool: [https://app.aladdin.microsoft.com:443](https://app.aladdin.microsoft.com/) "GET /api/v1.0/suggestions?query=%7B%22command%22%3A+%22aks+mesh+upgrade+complete%22%2C+%22parameters%22%3A+%22--yes%22%7D&clientType=AzureCli&context=%7B%22versionNumber%22%3A+%222.59.0%22%2C+%22errorType%22%3A+%22UnrecognizedArguments%22%2C+%22correlationId%22%3A+%2286b2949a-4c4e-4104-a098-1cb57c59c128%22%2C+%22subscriptionId%22%3A+%2284c559c6-30a0-417c-ba06-8a2253b388c3%22%2C+%22eventId%22%3A+%22aeb4c8a3-4eae-4bfd-91ec-aff8905adf9b%22%7D HTTP/1.1" 200 None
cli.azure.cli.core.azclierror: NoneType: None
 
cli.azure.cli.core.azclierror: unrecognized arguments: --yes
az_command_data_logger: unrecognized arguments: --yes
 
Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f556d839820>]
az_command_data_logger: exit code: 2
cli.__main__: Command ran in 0.940 seconds (init: 0.170, invoke: 0.770)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3871 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/bin/python3.9 /usr/lib/az/lib/python3.9/site-packages/azure/cli/telemetry/__init__.py /home/saravanan/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

--yes should be accepted for prompt commands

### Environment Summary

azure-cli                         2.59.0
 
core                              2.59.0
telemetry                          1.1.0
 
Extensions:
ai-examples                        0.2.5
aks-preview                      0.5.173
ml                                2.25.0
ssh                                2.0.3
 
Dependencies:
msal                              1.27.0
azure-mgmt-resource             23.1.0b2
 
Python location '/usr/bin/python3.9'
Extensions directory '/home/saravanan/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'
 
Python (Linux) 3.9.19 (main, Mar 28 2024, 18:56:59) 
[GCC 11.2.0]
 
Legal docs and information: aka.ms/AzureCliLegal
 
 
Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by deveshdama** [comment]
@yonzhan can you please assign this incident to me. We are currently testing the fix and should be able to release the fix by tomorrow.

**Comment by deveshdama** [comment]
@yonzhan 
Fix has been deployed, this issue can be cloed.
