### ISSUE TITLE
az storage fs directory upload - Not accepting --auth-mode

### ISSUE THREAD

**Issue by kalirajann** [Azure/azure-cli#28749]
### Describe the bug

We are attempting to upload the file using --auth-mode login, but the upload process is not accepting the --auth-mode arguments, which forces us to bypass Entra validation. The organization also prohibits using the storage key/SAS approach. Here is the command we're trying to use:

az storage fs directory upload

https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/docs/ADLS%20Gen2.md - Document refers to use the --auth-mode as well

### Related command

az storage fs directory upload

### Errors

Auth mode not supported

### Issue script & Debug output

Auth mode not supported

### Expected behavior

Auth mode not supported

### Environment Summary

az-cli - 2.50

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
