### ISSUE TITLE
az keyvault secret set <urllib3.connection.HTTPSConnection object at 0x0000027907C21590>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by davesbrown** [Azure/azure-cli#28772]
### Describe the bug

Fail to set a secret using az keyvault secret set.  
Error is:
<urllib3.connection.HTTPSConnection object at 0x0000027907C21590>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

### Related command

az keyvault secret set --name "TestAzCliSetSecret" --vault-name "myvault" --value "SuperSecret"

### Errors

<urllib3.connection.HTTPSConnection object at 0x0000027907C21590>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

### Issue script & Debug output

CMD-LOG-LINE-BEGIN 7004 | 2024-04-17 21:29:44,691 | INFO | az_command_data_logger | command args: keyvault secret set --name {} --vault-name {} --value {} --debug
CMD-LOG-LINE-BEGIN 7004 | 2024-04-17 21:29:50,552 | ERROR | az_command_data_logger | <urllib3.connection.HTTPSConnection object at 0x000001D34B4314D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
CMD-LOG-LINE-BEGIN 7004 | 2024-04-17 21:29:50,552 | INFO | az_command_data_logger | exit code: 1

### Expected behavior

Be able to set a secret to a keyvault.

### Environment Summary

>az --version
azure-cli                         2.59.0

core                              2.59.0
telemetry                          1.1.0

Dependencies:
msal                              1.27.0
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\dbrown\.azure\cliextensions'

Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by evelyn-ys** [comment]
Please check if your value `myvault` and your secret `TestAzCliSetSecret` exist

**Comment by davesbrown** [comment]
@evelyn-ys The `myvault` does exist, but I was under impression from the reference docs:

"Create a secret (**if one doesn't exist**) or update a secret in a KeyVault."

https://learn.microsoft.com/en-us/cli/azure/keyvault/secret?view=azure-cli-latest#az-keyvault-secret-set

**Comment by evelyn-ys** [comment]
Yes this command will create a secret if it doesn't exist, but the vault is required to exist
