### ISSUE TITLE
Storage CLI causing a bad security issue.

### ISSUE THREAD

**Issue by KeevF** [Azure/azure-cli#28771]
### Describe the bug

Azue CLI for Storage is allowing me to add a service endpoint external subnet on firewal configuration, without having access to the subscription or tenant from where it's located, I only need to know subnet URI and tenantID to perform this command on my personal account:

az storage account network-rule add -n <personal-storage-name> --subnet "<remote-subnet-URI>" --tenant-id "<remote-tenant-id>"

Above command is causing a security issue, because doesent matter if I dont have any permissions over remote subscription or tenant, it only validates if exist and create the configuration on my personal storage. 

This is bypassing my firewall and allows me to write data outside a corporate tenant to my personal environment.

### Related command

az storage account network-rule add -n <personal-storage-name> --subnet "<remote-subnet-URI>" --tenant-id "<remote-tenant-id>"

### Errors

No errors, this is bypassing my firewall and allows me to write data outside a corporate tenant to my personal environment.

### Expected behavior

Validate credentials/permissions on remote resource (subnet) and tenant for user that is running command.

### Environment Summary

azure-cli                         2.42.0 *

core                              2.42.0 *
telemetry                          1.0.8 *

Extensions:
account                            0.2.5
ssh                                1.1.3

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\keevynyaelf\.azure\cliextensions'

Python (Windows) 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:37:59) [MSC v.1933 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

### Additional context

This is causing a bad security issue.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by calvinhzy** [comment]
Please see this guide for managing access to the storage account. https://learn.microsoft.com/en-us/azure/storage/common/storage-network-security?tabs=azure-portal
I am wondering what settings you are using for your firewall and what specific commands and params are you using when writing to the storage account.
Since network access and authentication are two separate issues, do you perhaps have anonymous access enabled. 
![image](https://github.com/Azure/azure-cli/assets/17182306/75facf2a-2a1e-433e-8426-9caead18ef3a)

**Comment by KeevF** [comment]
Hi Zhiyi,

Issue is not with storage security, it's data exfiltration security risk bypassing firewall.

Ex. 

There is a Databricks workspace on a corporate "secure" environment using a firewall to block attempts of connection to non-authorized external resources like external storage accounts. 

Then there is an user working in that company that has access to a corporate tenant and subscription resources, this user can easily on a personal subscription having a storage account, login to personal account using Azure CLI from their personal device or any computer and running command:

az storage account network-rule add -n personal-storage-name --subnet "remote-corporate-Databricks-public-subnet-URI" --tenant-id "remote-corporate-tenant-id"

This will be adding a SERVICE ENPOINT on personal Storage account linked to a remote corporate Databricks public subnet. Giving this user the ability of bypassing the firewall, because a service endpoint was established between corporate Databricks subnet and personal storage account, now communications for that storage account are not going through the firewall. Now user can export corporate data to their personal storage account without any restrictions. 

Doesn't matter that the user on personal account doesn't have any permissions on corporate remote account, command is running without validating credentials. Command only validate if remote subnet and tenant exist and creates the link.

Expected behavior is that command validate if remote subnet and tenant exist, then validate if the user that is trying to use them has required permissions over them, if user has permissions over remote resources then proceed with action, if not reject action.

**Comment by KeevF** [comment]
For recreating this issue is required that Service endpoint is already enabled on Databricks subnet. Command will fail if the service endpoint is not already enabled on Databricks subnet.

**Comment by KeevF** [comment]
I have detected another security issue:

I discovered that anyone with a personal subscription can enable service endpoints for any subscription like corporate, doesn't matter if you don't have permissions, if using your personal subscription, you execute the following command it will be enabling service endpoint on remote subnet (Of Course for this, user need to know remote values: subscription ID resource groupName, vnet name, subnet name):

az network vnet subnet update -g **resource-groupName** -n **subnet-name** --vnet-name **vnet-name** --service-endpoints Microsoft.Storage --subscription **subscriptionID**

**Comment by calvinhzy** [comment]
Hi @KeevF thanks for the more detailed explanation. We will look into this. Have you tried other ways of updating the network-rule like PowerShell or Portal. Do they have similar behavior as well?

**Comment by KeevF** [comment]
Hi @calvinhzy,

Using Azure UI (portal) is not posible as it will be only showing subscription resources to which user have access and permissions (as expected). I haven't tried using PowerShell.

Is there any update on this? Or an ETA to be fixed?

**Comment by KeevF** [comment]
I just tested on PowerShell, and we can see same issue there:

Add-AzStorageAccountNetworkRule -ResourceGroupName "personal-stroage-rg-name" -Name "personal-storage-name" -VirtualNetworkResourceId "remote-databricks-subnet-id" 

So, issue is reproducible in Azure CLI and PowerShell.
