### ISSUE TITLE
Install script (Any) should be deprecated

### ISSUE THREAD

**Issue by bebound** [Azure/azure-cli#28791]
The script provided in the [Install script (any)](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=script#install-or-update-azure-cli) `curl -L https://aka.ms/InstallAzureCli | bash` is not working since python 3.11. The pip install doc could be an alternative: https://github.com/Azure/azure-cli/issues/20476.

Since it's not marked as deprecated, numerous users continue to attempt using it, leading to a lot of issues.

- https://github.com/Azure/azure-cli/issues/28872
- https://github.com/Azure/azure-cli/issues/27775
- https://github.com/Azure/azure-cli/issues/27529
- https://github.com/Azure/azure-cli/issues/27218
- https://github.com/Azure/azure-cli/issues/26590
- https://github.com/Azure/azure-cli/issues/25378
- https://github.com/Azure/azure-cli/issues/23522
- https://github.com/Azure/azure-cli/issues/23215
- https://github.com/Azure/azure-cli/issues/20206
- https://github.com/Azure/azure-cli/issues/20713
- https://github.com/Azure/azure-cli/issues/20047

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
Close as warning info is added in https://github.com/MicrosoftDocs/azure-docs-cli/pull/4355

> The install script only works on Python 3.8.x, 3.9.x, or 3.10.x. This install script does not work on Python 3.11.x or later versions.
