### ISSUE TITLE
[Feature request] az login with cookie or bearer token

### ISSUE THREAD

**Issue by recolic** [Azure/azure-cli#28815]
**Related command**

We need them:

```
az login --cookies "xxx=xxx; xxx=xxx; xxx=xxx;"
az login --auth-header "bearer xxxxxxxxxxxxxxxxxxxxxxxx"
```

**Is your feature request related to a problem? Please describe.**

Currently our organization requires `az login` multiple times EVERY DAY, and we must use `az login --use-device-code` and copy-paste code into customized browser for auth. 

I have been doing authentication again and again, day and day, month after month, I'm so tired.

WHY NOT SIMPLY ACCEPT auth-header or cookie, so we have freedom to extract things from browser directly?

**Describe the solution you'd like**

```
az login --cookies "xxx=xxx; xxx=xxx; xxx=xxx;"
az login --auth-header "bearer xxxxxxxxxxxxxxxxxxxxxxxx"
```

**Describe alternatives you've considered**

Do `az login --use-device-code` again and again, day and day, month after month, I'm so tired.

I have a dirty tampermonkey script to make it easier, but still pissed off after doing such boring work for years.

**Additional context**

I'M SO TIRED.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
Azure REST API uses OAuth2 for authentication, so cookies are not supported.

As for accepting bearer tokens, this is tracked by https://github.com/Azure/azure-cli/issues/16459. The bearer token usually expires after 1 hour. You have to log in again after it expires.

**Comment by recolic** [comment]
Got it.. Thanks for your information.

**Comment by jiasli** [comment]
If you want to get rid of logging in again and again, it is best to leverage a service principal: https://learn.microsoft.com/en-us/cli/azure/authenticate-azure-cli-service-principal
