### ISSUE TITLE
[Monitor Control Service CLI Extension] Support a full JSON payload argument

### ISSUE THREAD

**Issue by AfstoneBharfon** [Azure/azure-cli#28827]
**Related command**

`az monitor data-collection-rule create`

This command is used a Data Collection Rule (DCR) resource. Link to the resource [swagger definition](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/monitor/resource-manager/Microsoft.Insights/stable/2023-03-11)

This resource is quite complex and it is nearly impossible to define it via the usual CLI command line arguments.

That's why we want to push for a `-- payload` argument at the azure-cli core level.  
This argument should be the path to a JSON file that contains the PUT/POST request payload for a specific resource.

The `monitor-control-service` CLI extension already has a  `-- -rule-file argument which serves the same purpose. 
However, the current process requires the CLI team to manually maintain our resource model definition whenever we introduce a new API version. Unfortunately, they haven't been able to, which has hindered the use of our CLI by our customers as properties introduced in our latest API versions are not being serialized.  

The goal is to introduce this pattern at the Azure CLI core level so that other teams can also benefit from it.

**Is your feature request related to a problem? Please describe.**
A Data Collection Rule (DCR) resource definition is impossible to achieve via the CLI command line arguments.
It has so many properties with 

**Describe the solution you'd like**
Introduce a command line argument (ex; `-- payload`) where customers can specify the full payload of a complex resource 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by AllyW** [comment]
@AfstoneBharfon  for applying whole payload from a json file, az cli has a command that can help: `az rest`. Details can be found as below:

![image](https://github.com/Azure/azure-cli/assets/8137253/a62982f4-060b-45f4-8626-b8e869e6e2d4)

And I tested that we can create a data-collection rule directly from a json file, like `az rest --method put --url https://management.azure.com/subscriptions/{your-sub-id}/resourceGroups/{your-resource-group}/providers/Microsoft.Insights/dataCollectionRules/{your-rule-name}?api-version=2022-06-01 --body "@your_rule_file.json"`

So in general, cli have the ability for making service requests based on user's payload file.
