### ISSUE TITLE
Leak of az secrets in file system system calls

### ISSUE THREAD

**Issue by freedge** [Azure/azure-cli#28839]
this is a spin off of https://github.com/Azure/login/issues/27

when running 
```
az login --service-principal -u $U --tenant $T -p $P
```
the secret is leaked on the command line as known, it is also leaked through a newfstatat system call.

This is undocumented but it's possible to use instead a "@" so that the password is read from a file, eg in this fashion
```
az login --service-principal -u $U --tenant $T -p @<(echo "$P")
```
which prevents the password leak on the command line (in some cases somewhat addressing https://github.com/Azure/azure-cli/issues/10241 and https://github.com/Azure/azure-cli/pull/27938), however it is still leaked in the newfstatat system call:

```
15547 newfstatat(AT_FDCWD, "W3x..., 0x7fffe0296410, 0) = -1 ENOENT (No such file or directory)
```
performed from https://github.com/Azure/azure-cli/blob/246725e59015f4b267f5a5ea4fb8d832e153f58d/src/azure-cli-core/azure/cli/core/auth/identity.py#L285-L286

this means the secret is leaked to the file system (if a network file system like NFS it is sent over the network) and relevant auditing tools (auditd, selinux, fapolicyd, etc.)

In addition w.r.t to the previous opened ticket, any documentation that mentions
```az login --service-principal``` with a password provided on the command line is wrong and should be updated.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
> This is undocumented but it's possible to use instead a "@" so that the password is read from a file, eg in this fashion

We do have document for the `@<file>` convention: https://learn.microsoft.com/en-us/cli/azure/use-azure-cli-successfully#use-quotation-marks-in-parameters. Its implementation is at 

https://github.com/Azure/azure-cli/blob/c4407842f98b5961fe25affefce13a0989238848/src/azure-cli-core/azure/cli/core/commands/__init__.py#L85-L101

Not https://github.com/Azure/azure-cli/blob/246725e59015f4b267f5a5ea4fb8d832e153f58d/src/azure-cli-core/azure/cli/core/auth/identity.py#L285-L286

The logic here is for specifying a certificate file path, without `@` prefix, such as

```
az login --service-principal -u $U --tenant $T -p /home/user1/mycert.pem
```
> however it is still leaked in the newfstatat system call:

I am wondering why `<(echo "$P")` is logged in `newfstatat` - is it writing to or reading from the df that results in the `newfstatat` system call? I think it is more about how Linux works internally, instead of Azure CLI's implementation. Can we repro this without Azrue CLI, such as

```
$ echo <(echo "aaa")
/dev/fd/63
$ cat <(echo "aaa")
aaa
$ python3 -c "import sys; print(sys.argv)" <(echo "aaa")
['-c', '/dev/fd/63']
$ python3 -c "import sys; print(open(sys.argv[1]).read(), end='')" <(echo "aaa")
aaa
```

@freedge, could you please share more details on how you captured this line?

```
15547 newfstatat(AT_FDCWD, "W3x..., 0x7fffe0296410, 0) = -1 ENOENT (No such file or directory)
```

**Comment by freedge** [comment]
> We do have document for the `@<file>` convention: 

ah indeed. it's not documented anywhere as a way to prevent leaking secrets though

> https://github.com/Azure/azure-cli/blob/c4407842f98b5961fe25affefce13a0989238848/src/azure-cli-core/azure/cli/core/commands/__init__.py#L85-L101
> 
> Not
> 
> https://github.com/Azure/azure-cli/blob/246725e59015f4b267f5a5ea4fb8d832e153f58d/src/azure-cli-core/azure/cli/core/auth/identity.py#L285-L286
> 

right. but the identity.py is still called with the actual password, and the stat call made with it.


> 
> I am wondering why `<(echo "$P")` is logged in `newfstatat` 

it's not


> how you captured this line?

strace az login etc.

**Comment by daviewales** [comment]
So far as I can tell, the `<(echo "$P")` construct doesn't leak information except to the current user and root. So it's a similar level of security to using environment variables. Is that correct?

**Comment by daviewales** [comment]
Note also that the security improvement can also be implemented without bash-specific process substitution using `/dev/stdin`:

```
printf '%s' "$P" | az login --service-principal -u $U --tenant $T -p @/dev/stdin
```

**Comment by freedge** [comment]
Right. Note that even specifying "@/dev/stdin" will still perform a system call to check whether there is a file named $P under the current directory, so the leak reported in this ticket persists.

**Comment by daviewales** [comment]
Does the system call check leak $P to all users? Or is it only visible to current user and root?

**Comment by jiasli** [comment]
> So far as I can tell, the `<(echo "$P")` construct doesn't leak information except to the current user and root.

I agree with @daviewales. Password being shown in `newfstatat` doesn't cause any leak. If you can run `strace az login` to intercept the password, you may also edit `azure-cli/src/azure-cli-core/azure/cli/core/auth/identity.py` to show the password in the terminal by adding

```py
print(user_expanded)
```

`strace` is only for debugging, it should never be run as a normal/common routine.

**Comment by jiasli** [comment]
On a second thought, I think I understand what @freedge is trying to say. 

**Even though the `newfstatat` log is not a problem on local machine, it is indeed a problem on a NFS (Network File System) where each `newfstatat` can be inspected and logged.**

A possible solution I can think of is to 

1. use `--password` only for passing secret and remove its functionality for passing a certificate
2. introduce a dedicated argument `--certificate` for passing service principal certificate

This can eliminate the `os.path.isfile(user_expanded)` system call.

BTW, my result of running `strace` looks like:

```
$ strace --follow-forks az login --service-principal --tenant 72f988bf-86f1-41af-91ab-2d7cd011db47 -u xxx -p mysecret 2>&1 | grep
 mysecret
...
[pid 10126] newfstatat(AT_FDCWD, "mysecret", 0x7ffc98ac7a30, 0) = -1 ENOENT (No such file or directory)
```

while your log is

```
15547 newfstatat(AT_FDCWD, "W3x..., 0x7fffe0296410, 0) = -1 ENOENT (No such file or directory)
```

@freedge, could you share detailed information or the full command you used to capture this line?

**Comment by freedge** [comment]
I think you got the right strace output. I am running:

    strace -f -e newfstatat -o out az login --service-principal -u $CID -p $CS --tenant $TID;

**Comment by jiasli** [comment]
@freedge, thanks for the information.

It's interesting that `strace`'s output with `-o out` is different from what's shown in `stderr`:

```sh
# output file
$ strace -f -e newfstatat -o out az login --service-principal --tenant 72f988bf-86f1-41af-91ab-2d7cd011db47 -u xxx -p mysecret
$ cat out | grep mysecret
35220 newfstatat(AT_FDCWD, "mysecret", 0x7ffe58b7f530, 0) = -1 ENOENT (No such file or directory)

# stderr
$ strace -f -e newfstatat az login --service-principal --tenant 72f988bf-86f1-41af-91ab-2d7cd011db47 -u xxx -p mysecret 2>&1 | grep mysecret
[pid 35438] newfstatat(AT_FDCWD, "mysecret", 0x7ffe6d4e8ab0, 0) = -1 ENOENT (No such file or directory)
```

**Comment by freedge** [comment]
ah indeed curious. in more recent versions of strace containing https://github.com/strace/strace/commit/9da5884135b587c57d6ee367a98586f24f769781#diff-96254e7c668273f0fa2069e9493e1ccc5613d7cb93a31eefb3c3d3e5639eda53R3186
we can use ```--always-show-pid``` to get the same output

**Comment by jiasli** [comment]
@freedge, Azure CLI 2.66.0 introduced a new `--certificate` argument for `az login`. You can use it to eliminate `newfstatat` calls.

Azure CLI 2.67.0 will disallow passing certificate with `--password`.
