### ISSUE TITLE
--public-network-access flag is missing for "az postgres flexible-server update"

### ISSUE THREAD

**Issue by kishendas** [Azure/azure-cli#28838]
### Describe the bug

We are able to change the public access flag from the UI for the Azure PostgreSQL Flexible server. 
However that option seems to be missing from in the Azure CLI. 
For example: We cannot do `az postgres flexible-server update --public-network-access all `

Below option is available for the regular postgres server. 

You can see this option in the help. 
az postgres server update --help
```
    --public --public-network-access : Enable or disable public network access to server. When
                                       disabled, only connections made through Private Links can
                                       reach this server. Allowed values are : Enabled, Disabled,
                                       all, 0.0.0.0, <SingleIP>, <StartIP-DestinationIP>. Default is
                                       Enabled.
```

### Related command

az postgres flexible-server update --public-network-access all

### Errors

unrecognized arguments: --public-network-access all 

### Issue script & Debug output

Unable to update public access flag for Azure PostgreSQL Flexible server through the Azure CLI

### Expected behavior

Should be able to update public access flag for Azure PostgreSQL Flexible server through the Azure CLI

### Environment Summary

azure-cli 2.59.0

### Additional context

Below screenshot is to show where we can change the same in the UI, after the server is created. 

<img width="1633" alt="public_access_flag_azure_cli" src="https://github.com/Azure/azure-cli/assets/528086/b4c81617-04a5-434d-8922-130420933a2f">

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by kishendas** [comment]
@sunilagarwal @niklarin Any update on this issue ? Cc : @yonzhan

**Comment by jackmtpt** [comment]
This is also something that I would like to see added. As a workaround I tried the following command `az postgres flexible-server update --name server0name --resource-group my-resource-group --set network.publicNetworkAccess=Disabled` which does seem to disable public network access but annoyingly the command overall returns an error:

`('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

**Comment by nachoalonsoportillo** [comment]
Thanks @kishendas for reporting this.

We're working on it so that we provide for `postgres flexible-server` the exact same experience that we're providing for `mysql flexible-server`. That is, for the `create` command, we accept the following input for `--public-access`:

```
    --public-access         : Determines the public access. Enter single or range of IP addresses to
                              be included in the allowed list of IPs. IP address ranges must be
                              dash-separated and not contain any spaces. Specifying 0.0.0.0 allows
                              public access from any resources deployed within Azure to access your
                              server. Setting it to "None" sets the server in public access mode but
                              does not create a firewall rule.
```

And for the `update` command we will accept these:

```
    --public-access           : Enable or disable the public access on a server.  Allowed values:
                                Disabled, Enabled.
```

For creating, updating, showing or listing firewall-rules on already existing instances, you should be using the following command group:

```
Group
    az postgres flexible-server firewall-rule : Manage firewall rules for a server.

Commands:
    create : Create a new firewall rule for a flexible server.
    delete : Delete a firewall rule.
    list   : List all firewall rules for a flexible server.
    show   : Get the details of a firewall rule.
    update : Update a firewall rule.

To search AI knowledge base for examples, use: az find "az postgres flexible-server firewall-rule"
```

While we bake that functionality, you could use the approach suggested by @jackmtpt in the [comment above](https://github.com/Azure/azure-cli/issues/28838#issuecomment-2090491094).
