### ISSUE TITLE
Unable to Access Azure from terminal 

### ISSUE THREAD

**Issue by joelsybrid** [Azure/azure-cli#28844]
**Related command**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by joelsybrid** [comment]
Facing error in accessing Azure from terminal

**Comment by joelsybrid** [comment]
Hello,
I am facing the same problem.
