### ISSUE TITLE
Add ZIP release to GitHub releases too

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/azure-cli#28856]
**Related command**

**Is your feature request related to a problem? Please describe.**

The MSI installer is (way too) slow, upgrade from v2.59 to v2.60 took 15-20 minutes.

ZIP releases already exists after #27911, but are not added to GitHub releases. Instead can be downloaded from:

* <https://azcliprod.blob.core.windows.net/zip/azure-cli-2.60.0-x64.zip>

**Describe the solution you'd like**

Add ZIP release to GitHub releases too.

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by o-l-a-v** [comment]
One more reason to add the ZIP to GitHub releases: Download speed from your Azure Storage Account is much slower than from GitHub.

Example for latest MSI x64:

* Azure Storage Account: <https://azcliprod.blob.core.windows.net/msi/azure-cli-2.60.0-x64.msi>
* GitHub: <https://github.com/Azure/azure-cli/releases/download/azure-cli-2.60.0/azure-cli-2.60.0.msi>

Downloading from GitHub takes 1-3 seconds on 1/1gbps fiber, while downloading from Storage Account takes ~60 seconds. Geolocation might affect this. `azcliprod.blob.core.windows.net` sems to reside in some US Azure data center.

**Comment by jiasli** [comment]
> Download speed from your Azure Storage Account is much slower than from GitHub.

This is because the storage account https://azcliprod.blob.core.windows.net/ is not cached by a CDN. This feature request is tracked by https://github.com/Azure/azure-cli/issues/19447.

**Comment by o-l-a-v** [comment]
Why not piggyback some existing MS system to speed up downloads, rather than creating and maintaining Azure infrastructure just for Azure CLI? Why not use GitHub?

**Comment by bebound** [comment]
zip has been available since 2.63.0.
https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.63.0
