### ISSUE TITLE
Az login workload identity suddenly not working

### ISSUE THREAD

**Issue by Merlijnv** [Azure/azure-cli#28863]
### Describe the bug

Our azure devops pipeline is suddenly broken on logging in with workload identity.

### Related command

az login --service-principal -u *** --tenant *** --allow-no-subscriptions --federated-token ***

### Errors

ERROR: AADSTS50166: Request to External OIDC endpoint failed. Trace ID: fec4b5cc-da51-4cbb-89e0-5df845893e00 Correlation ID: f320ae69-3529-4ea6-a450-bc10985251bc Timestamp: 2024-05-01 05:51:15Z

### Issue script & Debug output

can't add --debug on login because this is done by AzureCLI@2 task

### Expected behavior

Logged in with workload identity on azure devops pipeline and able to do az acr login afterwards.

### Environment Summary

azure-cli                         2.59.0 *

core                              2.59.0 *
WARNING: You have 2 update(s) available. Consider updating your CLI installation with 'az upgrade'
telemetry                          1.1.0

Extensions:
azure-devops                       1.0.0

Dependencies:
msal                              1.27.0
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/opt/az/azcliextensions'

Python (Linux) 3.11.8 (main, Mar 27 2024, 04:03:04) [GCC 11.4.0]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by askebm** [comment]
It seems we are having the same issue, though with error AADSTS90061 instead

```
Task         : Azure CLI
Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
Version      : 2.238.5
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
==============================================================================
/usr/bin/az --version
azure-cli                         2.60.0

core                              2.60.0
telemetry                          1.1.0

Extensions:
azure-devops                       1.0.0

Dependencies:
msal                              1.28.0
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.9'
Extensions directory '/home/vsts_azpcontainer/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.18 (main, Jan  4 2024, 00:00:00) 
[GCC 11.4.1 20230605 (Red Hat 11.4.1-2)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
Setting AZURE_CONFIG_DIR env variable to: /__w/_temp/.azclitask
Setting active cloud to: AzureCloud
/usr/bin/az cloud set -n AzureCloud
/usr/bin/az login --service-principal -u *** --tenant 0ddb5c93-50d2-477c-a373-273efb95ba07 --allow-no-subscriptions --federated-token ***
ERROR: AADSTS90061: Request to External OIDC endpoint failed. Trace ID: 58ef1dad-76dd-43de-ade0-4db693097800 Correlation ID: bad8661d-8a44-40e0-9079-7aa0b05c115f Timestamp: 2024-04-30 21:48:01Z
Interactive authentication is needed. Please run:
az login
##[error]Error Code: [1]
##[error]Error: Azure login failed
##[error]Script failed with error: ERROR: AADSTS90061: Request to External OIDC endpoint failed. Trace ID: 58ef1dad-76dd-43de-ade0-4db693097800 Correlation ID: bad8661d-8a44-40e0-9079-7aa0b05c115f Timestamp: 2024-04-30 21:48:01Z
Interactive authentication is needed. Please run:
az login
```

**Comment by MarcDenman** [comment]
We are running into the same issue as well. We have been able replicate it using both Microsoft hosted agents and self hosted agents.

```
Setting AZURE_CONFIG_DIR env variable to: D:\a\_temp\.azclitask
Setting active cloud to: AzureCloud
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" cloud set -n AzureCloud"
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" login --service-principal -u *** --tenant *** --allow-no-subscriptions --federated-token ***"
ERROR: AADSTS90061: Request to External OIDC endpoint failed. Trace ID: 86f1f15b-89cd-49a9-afc9-c0f214382d01 Correlation ID: 106c5070-d068-4f46-942b-14d5fa0db5ab Timestamp: 2024-05-01 07:53:01Z
##[error]Error Code: [1]
Interactive authentication is needed. Please run:
##[error]Error: Azure login failed
az login
##[error]Script failed with error: ERROR: AADSTS90061: Request to External OIDC endpoint failed. Trace ID: 86f1f15b-89cd-49a9-afc9-c0f214382d01 Correlation ID: 106c5070-d068-4f46-942b-14d5fa0db5ab Timestamp: 2024-05-01 07:53:01Z
Interactive authentication is needed. Please run:
az login
```

**Comment by virtualdian** [comment]
We are seeing the same issue since this morning. Switching back to service principals works well. 

Microsoft Entra rejected the token issued by Azure DevOps with error code AADSTS50166: Request to External OIDC endpoint failed.

**Comment by jackmtpt** [comment]
We are also blocked by this. Switching back to service principal auth is not an option.

**Comment by birdnathan** [comment]
Same here. PoSh or CLI.

**Comment by MarcDenman** [comment]
Looks like it has been acknowledged as a problem with Azure DevOps - https://status.dev.azure.com/_event/499193080

**Comment by Dhargor55** [comment]
Same issue here, looking forward to hearing from MSFT.

**Comment by neilmcalister** [comment]
Enforced Workflow Identity federation is the future, thanks to the "secret" way being deliberately suffocated by the powers that be.

https://developercommunity.visualstudio.com/t/Azure-DevOps-Service-Connection-for-Azur/10637633

**Comment by PJBCoetzer** [comment]
We are experiencing the same AADSTS50166 error when deploying resources to EU-WEST. Unfortunately our process is automated and we cannot revert to the old mechanism, so hoping for some light at the end of the tunnel soon. :-)

**Comment by RebekkaBekk** [comment]
Same issue here (AADSTS90061).

**Comment by PJBCoetzer** [comment]
For those who want to follow the MS Event Log for this issue:  https://status.dev.azure.com/_event/499193080

**Comment by jackmtpt** [comment]
As the incident page says it's working again now (confirmed in my org as well), so this can be closed.
