### ISSUE TITLE
az billing subscription update throwing error due to incorrect API version called in the backend

### ISSUE THREAD

**Issue by darushah** [Azure/azure-cli#28877]
### Describe the bug

When calling this cli cmdlet:

az billing subscription update --account-name "xxxxxxxx" --cost-center "ABC1234" --subscription xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx--debug 

we are getting the below error:

cli.azure.cli.core.azclierror: (NotFound) The resource or one of its dependencies could not be found.
Code: NotFound
Message: The resource or one of its dependencies could not be found.
az_command_data_logger: (NotFound) The resource or one of its dependencies could not be found.
Code: NotFound
Message: The resource or one of its dependencies could not be found.

Upon checking the debug logs, we found it is calling this REST API:

cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/providers/Microsoft.Billing/billingAccounts/xxxxxxxx/billingSubscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx?api-version=2020-05-01'
cli.azure.cli.core.sdk.policies: Request method: 'PATCH'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '41'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '2be481c6-0890-11ef-b576-00155dbfeda6'

Making the direct call in Postman with the API version  2020-05-01 gives the same error.

However, if we update the API version to 2022-10-01-privatepreview then it is working fine and receiving 200 OK response.

Hence, request you to kindly update the API version of the cli cmdlet az billing subscription update to 2022-10-01-privatepreview.

### Related command

az billing subscription update

### Errors

cli.azure.cli.core.azclierror: (NotFound) The resource or one of its dependencies could not be found.
Code: NotFound
Message: The resource or one of its dependencies could not be found.
az_command_data_logger: (NotFound) The resource or one of its dependencies could not be found.
Code: NotFound
Message: The resource or one of its dependencies could not be found.

### Issue script & Debug output

PS /home/darshit> az billing subscription update --account-name "xxxxxxxx" --cost-center "ABC1234" --subscription xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx --debug                        
cli.knack.cli: Command arguments: ['billing', 'subscription', 'update', '--account-name', 'xxxxxxxx', '--cost-center', 'ABC1234', '--subscription', 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f1d4575e160>, <function OutputProducer.on_global_arguments at 0x7f1d45678ca0>, <function CLIQuery.on_global_arguments at 0x7f1d45610280>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'billing': ['azure.cli.command_modules.billing']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: billing                   0.137        22        57
cli.azure.cli.core: Total (1)                 0.137        22        57
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: ai-examples               0.077         1         1  /usr/lib/python3.9/site-packages/azure-cli-extensions/ai-examples
cli.azure.cli.core: Total (1)                 0.077         1         1  
cli.azure.cli.core: Loaded 23 groups, 58 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : billing subscription update
cli.azure.cli.core: Command table: billing subscription update
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f1d44abd700>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/darshit/.azure/commands/2024-05-02.14-27-57.billing_subscription_update.2466.log'.
az_command_data_logger: command args: billing subscription update --account-name {} --cost-center {} --subscription {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f1d44a66310>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f1d44a8e310>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f1d44a451f0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f1d45678d30>, <function CLIQuery.handle_query_parameter at 0x7f1d45610310>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f1d44a45160>]
Command group 'billing subscription' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=BillingManagementClient
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2049
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: MSIAuthenticationWrapper.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
urllib3.connectionpool: Starting new HTTP connection (1): localhost:50342
urllib3.connectionpool: http://localhost:50342 "POST /oauth2/token HTTP/1.1" 200 2049
msrestazure.azure_active_directory: MSI: Retrieving a token from http://localhost:50342/oauth2/token, with payload {'resource': 'https://management.core.windows.net/'}
cli.azure.cli.core.auth.adal_authentication: Normalize expires_on: '1714664301' -> 1714664301
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/providers/Microsoft.Billing/billingAccounts/xxxxxxx/billingSubscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx?api-version=2020-05-01'
cli.azure.cli.core.sdk.policies: Request method: 'PATCH'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '41'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '2be481c6-0890-11ef-b576-00155dbfeda6'
cli.azure.cli.core.sdk.policies:     'CommandName': 'billing subscription update'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--account-name --cost-center --subscription --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.60.0 (RPM) azsdk-python-core/1.28.0 Python/3.9.19 (Linux-5.10.102.2-microsoft-standard-x86_64-with-glibc2.35) cloud-shell/1.0'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"properties": {"costCenter": "ABC1234"}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PATCH /providers/Microsoft.Billing/billingAccounts/xxxxxxx/billingSubscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx?api-version=2020-05-01 HTTP/1.1" 404 91
cli.azure.cli.core.sdk.policies: Response status: 404
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '91'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-service-version': '10.6.2669.547'
cli.azure.cli.core.sdk.policies:     'api-supported-versions': '2018-11-01-preview, 2019-10-01-preview, 2020-05-01, 2020-12-15-privatepreview, 2021-10-01, 2022-10-01-privatepreview, 2024-04-01'
cli.azure.cli.core.sdk.policies:     'X-Frame-Options': 'DENY'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-tenant-writes': '1199'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'd3575a8c-9756-4f7e-a6bb-8e69ae04dcf2'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'd3575a8c-9756-4f7e-a6bb-8e69ae04dcf2'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTINDIA:20240502T142758Z:d3575a8c-9756-4f7e-a6bb-8e69ae04dcf2'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: 8C119F7515F14B5A8089F3C4E5C431E9 Ref B: MAA201060513033 Ref C: 2024-05-02T14:27:58Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 02 May 2024 14:27:57 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"code":"NotFound","message":"The resource or one of its dependencies could not be found."}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 664, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 701, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 334, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/billing/generated/custom.py", line 284, in billing_subscription_update
    return client.update(billing_account_name=account_name,
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/mgmt/billing/operations/_billing_subscriptions_operations.py", line 467, in update
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/core/exceptions.py", line 112, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: (NotFound) The resource or one of its dependencies could not be found.
Code: NotFound
Message: The resource or one of its dependencies could not be found.

cli.azure.cli.core.azclierror: (NotFound) The resource or one of its dependencies could not be found.
Code: NotFound
Message: The resource or one of its dependencies could not be found.
az_command_data_logger: (NotFound) The resource or one of its dependencies could not be found.
Code: NotFound
Message: The resource or one of its dependencies could not be found.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f1d44abd940>]
az_command_data_logger: exit code: 3
cli.__main__: Command ran in 0.766 seconds (init: 0.142, invoke: 0.624)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 4095 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/bin/python3.9 /usr/lib/az/lib/python3.9/site-packages/azure/cli/telemetry/__init__.py /home/darshit/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

The cmd should go through without any error.

### Environment Summary

azure-cli                         2.60.0

core                              2.60.0
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
ml                                2.25.1
ssh                                2.0.3

Dependencies:
msal                              1.28.0
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.9'
Extensions directory '/home/darshit/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.19 (main, Mar 28 2024, 18:56:59) 
[GCC 11.2.0]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by himanshuPandey25** [comment]
The current GA version of API doesn't support for EA therefore this api can't be used.

**Comment by Sapna-Keshari** [comment]
Closing the issue as GA version supporting EA is needed to update CLI
