### ISSUE TITLE
az afd origin create "--enabled-state" documentation

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#28893]
### Describe the bug

I am moving this customer feedback from MicrosoftDocs/azure-docs [issue 122125](https://github.com/MicrosoftDocs/azure-docs/issues/122125).  

**Request:** Please provide more clarity for [az afd origin create](https://learn.microsoft.com/en-us/cli/azure/afd/origin?view=azure-cli-latest#az-afd-origin-create) `--enabled-state` parameter. Possibly replace the first sentence in the description with something along the lines of "When set to 'disabled' [this will happen]. When set to 'enabled', [this will happen]."  

**Customer feedback:**
**********
"
The documentation says against parameter "--enabled-state" as below

"Whether to enable health probes to be made against backends defined under backendPools. Health probes can only be disabled if there is a single enabled backend in single enabled backend pool."

This seems odd as this parameter value is meant to 'actually disable further requests to that origin itself', like AFD will stop forwarding requests if that origin is marked disabled.

Doc Link: https://learn.microsoft.com/en-us/cli/azure/afd/origin?view=azure-cli-latest#az-afd-origin-create
"
*********

CCing CDN contacts from Azure CLI Service Contact List: @cdnfdsuppgithub, @t-bzhan, @gxue, @TracyYaoYao

### Related command

az afd origin create

### Errors

n/a

### Issue script & Debug output

n/a

### Expected behavior

n/a

### Environment Summary

Version 2.60.0

### Additional context

n/a

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
