### ISSUE TITLE
Use SyncMode property by default when a cross-sub frontends for LB Create

### ISSUE THREAD

**Issue by mahipdeora** [Azure/azure-cli#28898]
### Describe the bug

Right now during the LB create if a user tries to create a new load balancer with the az network LB create command, then the operation will fail since the backend pool created doesn't have syncMode enabled. There is no way to add syncMode during the LB create command. 

On the LB create command we need to expose both the syncMode command. SyncMode also requires a virtual network, so we need to ensure the vnet parameter on the LB create command is passed into the backend pool. 

### Related command

az network LB Create 

https://learn.microsoft.com/en-us/cli/azure/network/lb?view=azure-cli-latest#az-network-lb-create

### Errors

na

### Issue script & Debug output

na

### Expected behavior

When passing a cross-sub frontend or backend, customers need to enable the syncMode property which isn't available on the LB create command 

### Environment Summary

azure-cli                         2.60.0

core                              2.60.0
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
ml                                2.25.1
ssh                                2.0.3

Dependencies:
msal                              1.28.0
azure-mgmt-resource             23.1.0b2

Python location '/usr/bin/python3.9'
Extensions directory '/home/mahip/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.19 (main, Mar 28 2024, 18:56:59) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context
https://github.com/Azure/azure-cli/issues/27090

The SyncMode work was done for the the backend address pool add command, we can re-use that logic for LB create command.

API version needs to be above 2023-05-01. This is an active blocker for our release, any help in getting this prioritzed would be appreciated.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by mahipdeora** [comment]
Also right now --vnet-name can only take in a name; we need it also accept the ID of a vnet. Otherwise, cross-sub vnet use case will still be broken.

**Comment by necusjz** [comment]
does combining `az network lb create xx` and `az network lb address-pool create xx` work here? e.g., https://github.com/necusjz/azure-cli/blob/8c40496059e8609f0b9ba5d2bde89e4899cbbd5b/src/azure-cli/azure/cli/command_modules/network/tests/latest/test_network_commands.py#L3981-L3984

**Comment by mahipdeora** [comment]
Not today, since LB create commands creates a default backend pool. So using 2 commands will create 2 backend pools.

**Comment by mahipdeora** [comment]
Actually I tested this further, in combo with az network LB create + az network lb address-pool update, the issue is resolved.
