### ISSUE TITLE
VMSS Zonal Expansion

### ISSUE THREAD

**Issue by fitzgeraldsteele** [Azure/azure-cli#28900]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az vmss update

### Resource Provider

Microsoft.compute/virtualmachinescalesets

### Description of Feature or Work Requested

We've recently enabled ability to update the zones paramter on an existing scale set. Today, this can be set with the az vmss update --set or --update commands, like:

az vmss update --set zones=["1","2","3"] -n regionaltozonaluniform2 -g zoneexpansion 

We'd like to simplify the ability to make this change on CLI with something like:

az vmss update --zones 1 2

### Minimum API Version Required

2023-03-01

### Swagger PR link / SDK link

current compute swagger is fine

### Request Example

PATCH /subscriptions/576f5e67-b043-4ec9-81e9-47c7e8692cc4/resourceGroups/zoneexpansion/providers/Microsoft.Compute/virtualMachineScaleSets/regionaltozonaluniform2?api-version=2023-03-01 

{ 

  "zones": [ 

    "1",  

    "2" 

  ] 

} 

### Target Date

6/1/2024

### PM Contact

fisteele

### Engineer Contact

frankpang

### Additional context

https://aka.ms/vmss-zonal-expansion-preview/docs

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
> 6/1/2024

@fitzgeraldsteele Due to the super busy schedule of this sprint, we didn't have the effort to develop this feature in this sprint. If this feature only adds a new parameter `--zones` without any breaking changes, could we schedule it for the next sprint (released at the end of June)?

**Comment by fitzgeraldsteele** [comment]
July Sounds great. Thank you!
