### ISSUE TITLE
Support to create Container App Environment in VNET (az containerapp compose create)

### ISSUE THREAD

**Issue by vienleidl** [Azure/azure-cli#28902]
**Related command**
az containerapp compose create -g resource_group_name --environment environment_name--location region --compose-file-path "./docker-compose.yml" --registry-server registry_name.azurecr.io --registry-username registry_username --registry-password registry_password

**Is your feature request related to a problem? Please describe.**
The created Container App Environment and its Container Apps are not able to communicate with an App Service with enabled Regional VNET Integration on the different subnet.

**Describe the solution you'd like**
It would be great if there is a way to deploy Container Apps to the same regional virtual network with an App Service. So, they can communicate to each others within the same vnet.

**Describe alternatives you've considered**
Using the external ingress (Accepting traffic from anywhere) temporarily.

**Additional context**
![image](https://github.com/Azure/azure-cli/assets/97711647/fd8dc7a9-5790-4f3f-90af-cfc8d7f07831)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by Greedygre** [comment]
Hi @vienleidl 

With `az containerapp compose create` the auto created environment(if specified environment does not exit) is not support vnet option, recommend using `az containerapp env create`, for example:
`az containerapp env create -g {resource_group} -n {env_name} --infrastructure-subnet-resource-id {subnetId}`

**Comment by vienleidl** [comment]
> Hi @vienleidl
> 
> With `az containerapp compose create` the auto created environment(if specified environment does not exit) is not support vnet option, recommend using `az containerapp env create`, for example: `az containerapp env create -g {resource_group} -n {env_name} --infrastructure-subnet-resource-id {subnetId}`

Thanks for your info! I managed to make it worked by creating the environment before starting the az containerapp compose create command.
