### ISSUE TITLE
Support Admin State on Azure Global Load Balancer

### ISSUE THREAD

**Issue by mahipdeora** [Azure/azure-cli#28917]
**Related command**

az network cross-region-lb address-pool create
az network cross-region-lb address-pool address add
az network cross-region-lb address-pool update 
az network cross-region-lb address-pool address update

**Is your feature request related to a problem? Please describe.**

Right now customers can set admin state on their regional load balancer through CLI but there is no support for global LB. We need to support admin state for global LB.

**Describe the solution you'd like**

Support setting admin state on global LB, similar to regional load balancer. 

**Describe alternatives you've considered**

**Additional context**

**Comment by cburuzie** [comment]
Hello @yonzhan, are we able to take this as part of the current milestone?
