### ISSUE TITLE
az upgrade failed because trivy-repo is changed

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-cli#28929]
### Describe the bug

 az version
{
  "azure-cli": "2.53.1",
  "azure-cli-core": "2.53.1",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "aks-preview": "2.0.0b7"
  }
}
az upgrade
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Your current Azure CLI version is 2.53.1. Latest version available is 2.60.0.
Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
Do you want to continue? (Y/n): Y
Hit:1 http://azure.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://azure.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease
Get:5 https://packages.microsoft.com/repos/azure-cli focal InRelease [3596 B]
Get:6 https://packages.microsoft.com/repos/microsoft-ubuntu-focal-prod focal InRelease [3632 B]
Hit:7 https://storage.googleapis.com/bazel-apt stable InRelease
Hit:8 https://download.docker.com/linux/ubuntu focal InRelease
Get:9 https://aquasecurity.github.io/trivy-repo/deb focal InRelease [3061 B]
Reading package lists... Done
E: Repository 'https://aquasecurity.github.io/trivy-repo/deb focal InRelease' changed its 'Origin' value from 'knqyf263.github.io/trivy-repo/deb' to 'aquasecurity.github.io/trivy-repo/deb'
E: Repository 'https://aquasecurity.github.io/trivy-repo/deb focal InRelease' changed its 'Label' value from 'github.io/knqyf263' to 'github.io/aquasecurity'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
CLI upgrade failed.

### Related command

az upgrade

### Errors

E: Repository 'https://aquasecurity.github.io/trivy-repo/deb focal InRelease' changed its 'Origin' value from 'knqyf263.github.io/trivy-repo/deb' to 'aquasecurity.github.io/trivy-repo/deb'
E: Repository 'https://aquasecurity.github.io/trivy-repo/deb focal InRelease' changed its 'Label' value from 'github.io/knqyf263' to 'github.io/aquasecurity'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
CLI upgrade failed.

### Issue script & Debug output

cli.knack.cli: Command arguments: ['upgrade', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f048b599360>, <function OutputProducer.on_global_arguments at 0x7f048b4f0280>, <function CLIQuery.on_global_arguments at 0x7f048b30d480>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'upgrade': ['azure.cli.command_modules.util']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: util                      0.001         3         7
cli.azure.cli.core: Total (1)                 0.001         3         7
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 3 groups, 7 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : upgrade
cli.azure.cli.core: Command table: upgrade
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f048a6d6dd0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/abelch/.azure/commands/2024-05-10.02-08-12.upgrade.358560.log'.
az_command_data_logger: command args: upgrade --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f048a71b880>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f048a5a57e0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f048a5a5900>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f048b4f0310>, <function CLIQuery.handle_query_parameter at 0x7f048b30d510>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f048a5a5870>]
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
urllib3.connectionpool: Starting new HTTPS connection (1): raw.githubusercontent.com:443
urllib3.connectionpool: https://raw.githubusercontent.com:443 "GET /Azure/azure-cli/main/src/azure-cli/setup.py HTTP/1.1" 200 2442
cli.azure.cli.command_modules.util.custom: Your current Azure CLI version is 2.53.1. Latest version available is 2.60.0.
cli.azure.cli.command_modules.util.custom: Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
Do you want to continue? (Y/n): y
Hit:1 http://azure.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://azure.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu focal-backports InRelease
Get:4 https://aquasecurity.github.io/trivy-repo/deb focal InRelease [3061 B]
Hit:5 https://packages.microsoft.com/repos/azure-cli focal InRelease
Hit:6 http://security.ubuntu.com/ubuntu focal-security InRelease
Get:7 https://packages.microsoft.com/repos/microsoft-ubuntu-focal-prod focal InRelease [3632 B]
Hit:8 https://storage.googleapis.com/bazel-apt stable InRelease
Hit:9 https://download.docker.com/linux/ubuntu focal InRelease
Reading package lists... Done
E: Repository 'https://aquasecurity.github.io/trivy-repo/deb focal InRelease' changed its 'Origin' value from 'knqyf263.github.io/trivy-repo/deb' to 'aquasecurity.github.io/trivy-repo/deb'
E: Repository 'https://aquasecurity.github.io/trivy-repo/deb focal InRelease' changed its 'Label' value from 'github.io/knqyf263' to 'github.io/aquasecurity'                                                                                               N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
cli.azure.cli.command_modules.util.custom: CLI upgrade failed.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f048a6d7010>]
az_command_data_logger: exit code: 100
cli.__main__: Command ran in 8.018 seconds (init: 0.165, invoke: 7.853)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3453 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/bin/../../opt/az/bin/python3 /opt/az/lib/python3.10/site-packages/azure/cli/telemetry/__init__.py /home/abelch/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

az upgrade succeeds

### Environment Summary

{
  "azure-cli": "2.53.1",
  "azure-cli-core": "2.53.1",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "aks-preview": "2.0.0b7"
  }
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by AbelHu** [comment]
Update: `sudo apt upgrade` can upgrade az-cli to `2.60.0`

**Comment by bebound** [comment]
It seems that `apt update` fails.
Close as it's not related to azure-cli.

**Comment by AbelHu** [comment]
@bebound Although I happened to find the mitigation, it should still be an issue of `az upgrade`.
