### ISSUE TITLE
Reg Adding new force Deletion Types for: az group delete command

### ISSUE THREAD

**Issue by mvvsubbu** [Azure/azure-cli#28923]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az group delete --name "RG-veena-test" --force-deletion-types Microsoft.Databricks/workspaces

### Resource Provider

Microsoft.Databricks

### Description of Feature or Work Requested

We have enabled [Resource Deletion Policy](https://armmanifest.visualstudio.com/One/_git/Manifest?path=/MICROSOFT.DATABRICKS/PROD/MANIFEST.JSON&version=GBmaster&line=27&lineEnd=27&lineStartColumn=6&lineEndColumn=41&lineStyle=plain&_a=contents) for Microsoft.Databricks/workspaces as "Force" and we were being told by ARM team saying after defining this policy delete resource group command should support passing "Microsoft.Databricks/workspaces" as allowed option. But it looks like the delete resource group command has some validation about allowed resource types.  The same operation is working via ARM REST API calls as specified [here](https://learn.microsoft.com/en-us/rest/api/resources/resource-groups/delete?view=rest-resources-2021-04-01&tabs=HTTP). We need your team's help to update allowed resource types to include "Microsoft.Databricks/workspaces" as well 
 
az group delete failed : 'Microsoft.Databricks/workspaces' is not a valid value for '--force-deletion-types'. Allowed values: Microsoft.Compute/virtualMachines, Microsoft.Compute/virtualMachineScaleSets.

### Minimum API Version Required

N/A

### Swagger PR link / SDK link

There is no change required for this in ARM, however there was a change required in DELETE API of Databricks Swagger for this, sharing the latest swagger for Databricks here. As long as the additional resource type is added to allowed types in az group delete command and command sent to ARM, ARM will make sure to pass the forceDeletion parameter with correct values to Databricks RP using correct API version of Databricks RP. 

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/databricks/resource-manager/Microsoft.Databricks/stable/2024-05-01/databricks.json

### Request Example

DELETE https://management.azure.com/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}?forceDeletionTypes=Microsoft.Databricks/workspaces&api-version=2021-04-01

### Target Date

2024-05-15

### PM Contact

shahjoy@microsoft.com

### Engineer Contact

subraman@microsoft.com

### Additional context

The only change that is required is to update the additional type "Microsoft.Databricks/workspaces" to be included in the results of the following query in repo

https://github.com/search?q=repo%3AAzure%2Fazure-cli%20--force-deletion-types%20&type=code

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
@mvvsubbu Due to the super busy schedule of this sprint, we didn't have the effort to develop this feature in this sprint. Could we schedule it for the next sprint (released at **07-02**)?

**Comment by mvvsubbu** [comment]
Would be possible to consider this for release in June? I have already shared code changes as well, where we need to update. Let me know your thoughts on how can we speed up the process
