### ISSUE TITLE
Azure CLI Support for Scheduled Event Profile

### ISSUE THREAD

**Issue by adwilso** [Azure/azure-cli#28937]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az vmss update --enable-terminate-notification {false, true}

### Resource Provider

microsoft.maintenance/scheduledevents

### Description of Feature or Work Requested

Currently we are adding a new profile setting to the VM and VMSS profile. We'd like to make sure that customers can make this change from the CLI as well.

https://learn.microsoft.com/en-us/rest/api/compute/virtual-machine-scale-sets/create-or-update?view=rest-compute-2024-03-01&viewFallbackFrom=rest-compute-2024-03-01-preview&tabs=HTTP#scheduledeventspolicy

Note: you have to sign into see the preview docs above. Pasted a screenshot for simplicity: 
![image](https://github.com/Azure/azure-cli/assets/1334452/1f1b2eea-a7ef-4bae-8691-f2bde418a082)

### Minimum API Version Required

2024-03-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/commit/5312cc6da7d6c051e0e96902f3718a9fb3e9e021 --ScheduledEventsAdditionalPublishingTargets

### Target Date

2024-06-15

### PM Contact

wilsonadam

### Engineer Contact

arpit.nand; 

### Additional context

The scheduledEventsPolicy had 3 different settings added that we'd like to have 
included in the CLI. They are ScheduledEventsAdditionalPublishingTargets, userInitiatedRedeploy, userInitiatedReboot.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
> Target Date
2024-06-15

@adwilso Due to the super busy schedule of this sprint, we didn't have the bandwidth to develop this feature in this sprint. Could we schedule it for the next sprint (released at **07-02**)?

**Comment by adwilso** [comment]
Thanks - understand that this is a last-minute request. Just to understand your release cycle if it is released on 7/02 does that mean that customers will start consuming it on that day or is there a preview process it must move through first?

**Comment by zhoxing-ms** [comment]
> it is released on 7/02 does that mean that customers will start consuming it

@adwilso This one, customers can use it after new CLI version releasing on 7/02

**Comment by adwilso** [comment]
That's perfect then. Thanks so much for your help
