### ISSUE TITLE
The --bandwidth-copy-speed is not working in Mooncake

### ISSUE THREAD

**Issue by JohnTangZX** [Azure/azure-cli#28979]
### Describe the bug

The az snapshot create command with --bandwidth-copy-speed is not working in Mooncake. The error is as below:

PS C:\Program Files\PowerShell\7> az snapshot create -g rg --name i1 --location chinanorth3 --source "/subscriptions/xxx/resourceGroups/tzx-linux/providers/Microsoft.Compute/snapshots/i1" --incremental true --output tsv --bandwidth-copy-speed Enhanced
(BadRequest) This subscription is not registered to use Microsoft.Compute/EnhancedProvisionedBandwidthCopy feature.
Code: BadRequest
Message: This subscription is not registered to use Microsoft.Compute/EnhancedProvisionedBandwidthCopy feature.

Can not register the feature either:

PS C:\Program Files\PowerShell\7> az feature register --namespace "Microsoft.Computer" --name EnhancedProvisionedBandwidthCopy
Once the feature 'EnhancedProvisionedBandwidthCopy' is registered, invoking 'az provider register -n Microsoft.Computer' is required to get the change propagated
(FeatureNotFound) The feature 'EnhancedProvisionedBandwidthCopy' could not be found.
Code: FeatureNotFound
Message: The feature 'EnhancedProvisionedBandwidthCopy' could not be found.

### Related command

az snapshot create -g rg --name i1 --location chinanorth3 --source "/subscriptions/xxx/resourceGroups/tzx-linux/providers/Microsoft.Compute/snapshots/i1" --incremental true --output tsv --bandwidth-copy-speed Enhanced

az feature register --namespace "Microsoft.Computer" --name EnhancedProvisionedBandwidthCopy

### Errors

(BadRequest) This subscription is not registered to use Microsoft.Compute/EnhancedProvisionedBandwidthCopy feature.
Code: BadRequest
Message: This subscription is not registered to use Microsoft.Compute/EnhancedProvisionedBandwidthCopy feature.

(FeatureNotFound) The feature 'EnhancedProvisionedBandwidthCopy' could not be found.
Code: FeatureNotFound
Message: The feature 'EnhancedProvisionedBandwidthCopy' could not be found.

### Issue script & Debug output

 az feature register --namespace Microsoft.Storage --name EnhancedProvisionedBandwidthCopy --debug
cli.knack.cli: Command arguments: ['feature', 'register', '--namespace', 'Microsoft.Storage', '--name', 'EnhancedProvisionedBandwidthCopy', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
Enable VT mode.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x00000175D4F63880>, <function OutputProducer.on_global_arguments at 0x00000175D50EA020>, <function CLIQuery.on_global_arguments at 0x00000175D5113BA0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'feature': ['azure.cli.command_modules.resource']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: resource                  0.205        51       228
cli.azure.cli.core: Total (1)                 0.205        51       228
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 51 groups, 228 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : feature register
cli.azure.cli.core: Command table: feature register
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x00000175D803EE80>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\xxx\.azure\commands\2024-05-16.14-59-17.feature_register.39412.log'.
az_command_data_logger: command args: feature register --namespace {} --name {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x00000175D80772E0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x00000175D808D3A0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x00000175D808D4E0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x00000175D50EA0C0>, <function CLIQuery.handle_query_parameter at 0x00000175D5113C40>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x00000175D808D440>]
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=FeatureClient
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\xxx\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\xxx\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: openid_config = {'token_endpoint': 'https://login.chinacloudapi.cn/xxx/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.chinacloudapi.cn/xxx/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.partner.microsoftonline.cn/xxx/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://microsoftgraph.chinacloudapi.cn/oidc/userinfo', 'authorization_endpoint': 'https://login.chinacloudapi.cn/xxx/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.chinacloudapi.cn/xxx/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.chinacloudapi.cn/xxx/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.chinacloudapi.cn/xxx/kerberos', 'tenant_region_scope': 'AS', 'cloud_instance_name': 'partner.microsoftonline.cn', 'cloud_graph_host_name': 'graph.chinacloudapi.cn', 'msgraph_host': 'microsoftgraph.chinacloudapi.cn', 'rbac_url': 'https://pas.chinacloudapi.cn'}
msal.application: Broker enabled? None
cli.azure.cli.command_modules.resource.custom: Once the feature 'EnhancedProvisionedBandwidthCopy' is registered, invoking 'az provider register -n Microsoft.Storage' is required to get the change propagated
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.chinacloudapi.cn//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.chinacloudapi.cn//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: fc098983-fa95-4eb3-9f10-1412ee26d1e7
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.chinacloudapi.cn/subscriptions/xxx/providers/Microsoft.Features/providers/Microsoft.Storage/features/EnhancedProvisionedBandwidthCopy/register?api-version=2021-07-01'
cli.azure.cli.core.sdk.policies: Request method: 'POST'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json, text/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'd02ebbd9-1351-11ef-bd54-c8cb9e2e58b9'
cli.azure.cli.core.sdk.policies:     'CommandName': 'feature register'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--namespace --name --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.59.0 (MSI) azsdk-python-core/1.28.0 Python/3.11.8 (Windows-10-10.0.22631-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: Starting new HTTPS connection (1): management.chinacloudapi.cn:443
urllib3.connectionpool: https://management.chinacloudapi.cn:443 "POST /subscriptions/xxx/providers/Microsoft.Features/providers/Microsoft.Storage/features/EnhancedProvisionedBandwidthCopy/register?api-version=2021-07-01 HTTP/1.1" 404 115
cli.azure.cli.core.sdk.policies: Response status: 404
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '115'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'chinaeast:f67b4ba8-672f-46b5-9760-56601b08c20a'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1198'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'a5bc870b-8d13-450e-84e6-3aafbdc622b7'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'CHINAEAST:20240516T065919Z:a5bc870b-8d13-450e-84e6-3aafbdc622b7'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 16 May 2024 06:59:18 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"FeatureNotFound","message":"The feature 'EnhancedProvisionedBandwidthCopy' could not be found."}}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 664, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 701, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 334, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 2941, in register_feature
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/resource/features/v2021_07_01/operations/_operations.py", line 740, in register
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/exceptions.py", line 112, in map_error
azure.core.exceptions.ResourceNotFoundError: (FeatureNotFound) The feature 'EnhancedProvisionedBandwidthCopy' could not be found.
Code: FeatureNotFound
Message: The feature 'EnhancedProvisionedBandwidthCopy' could not be found.

cli.azure.cli.core.azclierror: (FeatureNotFound) The feature 'EnhancedProvisionedBandwidthCopy' could not be found.
Code: FeatureNotFound
Message: The feature 'EnhancedProvisionedBandwidthCopy' could not be found.
az_command_data_logger: (FeatureNotFound) The feature 'EnhancedProvisionedBandwidthCopy' could not be found.
Code: FeatureNotFound
Message: The feature 'EnhancedProvisionedBandwidthCopy' could not be found.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x00000175D803F100>]
az_command_data_logger: exit code: 3
cli.__main__: Command ran in 2.368 seconds (init: 0.562, invoke: 1.806)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3874 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\v-zhenxtang\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

The command should work.

### Environment Summary

PS C:\Program Files\PowerShell\7> az version
{
  "azure-cli": "2.59.0",
  "azure-cli-core": "2.59.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "k8s-extension": "1.6.1",
    "ssh": "2.0.3",
    "storage-preview": "1.0.0b1"
  }
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by AdamZLi** [comment]
Hi @JohnTangZX, the feature is currently in internal private preview. You can reach out to adli@microsoft.com if you want to test out the feature.

**Comment by ushnaarshadkhan** [comment]
Issue will be closed as 'EnhancedProvisionedBandwidthCopy; feature is only in internal private preview'.
