### ISSUE TITLE
Example missing an argument - az postgres flexible-server firewall-rule create

### ISSUE THREAD

**Issue by perrutbruno** [Azure/azure-cli#28972]
### Describe the bug

The examples for az postgres flexible-server firewall-rule create section, allowing public access for Azure services does not include the --rule-name argument which is required for this to work. I found [this Issue](https://github.com/Azure/azure-cli/issues/24757) from two years ago that pointed the same problem, and hence, I got how to make the command work.

Without the argument, the command fails with this error: _expected string or bytes-like object_

### Related command

az postgres flexible-server firewall-rule create

### Errors

expected string or bytes-like object

### Issue script & Debug output

cli.knack.cli: Command arguments: ['postgres', 'flexible-server', 'firewall-rule', 'create', '--resource-group', 'proreforma-prog-sg', '--name', 'proreforma-teste-db', '--start-ip-address', '217.123.78.38', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fa852f7d360>, <function OutputProducer.on_global_arguments at 0x7fa852e73f40>, <function CLIQuery.on_global_arguments at 0x7fa852ec11b0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'postgres': ['azure.cli.command_modules.rdbms']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: rdbms                     0.200        55       230
cli.azure.cli.core: Total (1)                 0.200        55       230
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 55 groups, 230 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : postgres flexible-server firewall-rule create
cli.azure.cli.core: Command table: postgres flexible-server firewall-rule create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fa851ec6b90>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/gitlab-runner/.azure/commands/2024-05-15.18-57-21.postgres_flexible-server_firewall-rule_create.854699.log'.
az_command_data_logger: command args: postgres flexible-server firewall-rule create --resource-group {} --name {} --start-ip-address {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fa851ee36d0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7fa851f29630>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7fa851f29750>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fa852e90040>, <function CLIQuery.handle_query_parameter at 0x7fa852ec1240>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7fa851f296c0>]
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/invocation.py", line 113, in _validation
    self._validate_arg_level(parsed_ns)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 859, in _validate_arg_level
    validator(**self._build_kwargs(validator, ns))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/command_modules/rdbms/validators.py", line 499, in firewall_rule_name_validator
    if not re.search(r'^[a-zA-Z0-9][-_a-zA-Z0-9]{1,126}[_a-zA-Z0-9]$', ns.firewall_rule_name):
  File "/opt/az/lib/python3.10/re.py", line 200, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

cli.azure.cli.core.azclierror: expected string or bytes-like object
az_command_data_logger: expected string or bytes-like object
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7fa851ec6dd0>]
az_command_data_logger: exit code: 2
cli.__main__: Command ran in 0.370 seconds (init: 0.153, invoke: 0.217)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3600 in cache
telemetry.check: Returns Positive.
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/bin/../../opt/az/bin/python3 /opt/az/lib/python3.10/site-packages/azure/cli/telemetry/__init__.py /home/gitlab-runner/.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

The documentation should clarify the mandatory argument or the cli should recognize that this mandatory argument is missing

### Environment Summary

az --version
azure-cli                         2.60.0

core                              2.60.0
telemetry                          1.1.0

Extensions:
azure-devops                      0.26.0

Dependencies:
msal                              1.28.0
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/home/gitlab-runner/.azure/cliextensions'

Python (Linux) 3.11.8 (main, Apr 24 2024, 04:15:18) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

reopening an Issue of a problem that is still around.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by nachoalonsoportillo** [comment]
Thanks for reporting this @perrutbruno!

My understanding is that you're not reporting the lack of the `--rule-name` parameter in any of the examples, but the fact that the validations made by our module don't require the presence of that parameter for the `flexible-server firewall-rule create` command, right?

I'm asking because it is true that in the past one of the examples was missing the parameter, but it was fixed back on November 2022 via #24770.

If I use the version of az cli you're reporting this issue against (`2.61.0`) to run the following statement:

```
az postgres flexible-server firewall-rule create --help
```

This is the output that I get, in which all examples have the `--rule-name` parameter present (highlighting their presence by preceding with `>>>` and suceeding with `<<<`):

```
Command
    az postgres flexible-server firewall-rule create : Create a new firewall rule for a flexible
    server.

Arguments
    --name -n           [Required] : Name of the server. The name can contain only lowercase
                                     letters, numbers, and the hyphen (-) character. Minimum 3
                                     characters and maximum 63 characters.
    --resource-group -g [Required] : Name of resource group. You can configure the default group
                                     using `az configure --defaults group=<name>`.
    --end-ip-address               : The end IP address of the firewall rule. Must be IPv4 format.
                                     Use value '0.0.0.0' to represent all Azure-internal IP
                                     addresses.
    --rule-name -r                 : The name of the firewall rule. If name is omitted, default name
                                     will be chosen for firewall name. The firewall rule name can
                                     only contain 0-9, a-z, A-Z, '-' and '_'. Additionally, the name
                                     of the firewall rule must be at least 3 characters and no more
                                     than 128 characters in length.
    --start-ip-address             : The start IP address of the firewall rule. Must be IPv4 format.
                                     Use value '0.0.0.0' to represent all Azure-internal IP
                                     addresses.

Global Arguments
    --debug                        : Increase logging verbosity to show all debug logs.
    --help -h                      : Show this help message and exit.
    --only-show-errors             : Only show errors, suppressing warnings.
    --output -o                    : Output format.  Allowed values: json, jsonc, none, table, tsv,
                                     yaml, yamlc.  Default: json.
    --query                        : JMESPath query string. See http://jmespath.org/ for more
                                     information and examples.
    --subscription                 : Name or ID of subscription. You can configure the default
                                     subscription using `az account set -s NAME_OR_ID`.
    --verbose                      : Increase logging verbosity. Use --debug for full debug logs.

Examples
    Create a firewall rule allowing connections from a specific IP address.

        az postgres flexible-server firewall-rule create --resource-group testGroup --name
        testserver >>>--rule-name allowip<<< --start-ip-address 107.46.14.221


    Create a firewall rule allowing connections from an IP address range.

        az postgres flexible-server firewall-rule create --resource-group testGroup --name
        testserver >>>--rule-name allowiprange<<< --start-ip-address 107.46.14.0 --end-ip-address
        107.46.14.221


    Create a firewall rule allowing connections to all Azure services

        az postgres flexible-server firewall-rule create --resource-group testGroup --name
        testserver >>>--rule-name allowazureservices<<< --start-ip-address 0.0.0.0


To search AI knowledge base for examples, use: az find "az postgres flexible-server firewall-rule
create"
```

**Comment by gbowerman** [comment]
@yonzhan do you know how we can get the owner of all Postgres CLI issues changed from sunilagrawal to gbowerman?

**Comment by nasc17** [comment]
@perrutbruno  Thanks for reporting this issue. PR with the fix has been merged now. It will be surfaced in upcoming version of Azure CLI.

@yonzhan  Please, close this one as resolved. Thank you.
