### ISSUE TITLE
Update az-vm-install-patches to include maxpatchpublishdate as a command

### ISSUE THREAD

**Issue by maulikshah23** [Azure/azure-cli#28973]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az vm install-patches

### Resource Provider

Compute Resource Provider

### Description of Feature or Work Requested

The install patches command does not allow users to specify a max patch publish date. This is currently available through different mechanisms, but not CLI. Adding this capability will bring further parity between API and CLI. 

### Minimum API Version Required

Use Compute API version 2018-10-01 or higher

### Swagger PR link / SDK link

https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/install-patches?view=rest-compute-2024-03-01&tabs=HTTP#windowsparameters](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Frest%2Fapi%2Fcompute%2Fvirtual-machines%2Finstall-patches%3Fview%3Drest-compute-2024-03-01%26tabs%3DHTTP%23windowsparameters&data=05%7C02%7Cmaulikshah%40microsoft.com%7Ca04b390ba5c04167481608dc710de211%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638509551685157344%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=WPvq0unFOnLw0qzGuHpi4bu8auM7tUIcLRPdHQYvcII%3D&reserved=0

### Request Example

az vm install-patches --maxpatchpublishdate mmddyyyy

### Target Date

2024-06-30

### PM Contact

Maulik Shah

### Engineer Contact

Mike Richmond

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
@maulikshah23 Sorry, due to our recent work being fully scheduled, we plan to put it on the next sprint with the release date in early August. Do you think it meets your expectations?

**Comment by maulikshah23** [comment]
Hi,

Sure that's fine. If you have any bandwidth sooner then please pick up this item.

Maulik

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zhoxing-ms** [comment]
> Sure that's fine. If you have any bandwidth sooner then please pick up this item.

OK, thanks for your understanding~

**Comment by zhoxing-ms** [comment]
@maulikshah23 We have completed this PR in this sprint and it will be released in **07-02**

**Comment by maulikshah23** [comment]
Adding @Mike ***@***.***> for visibility.

Thank you @Xing ***@***.***>. Looking forward for the availability of this update on 7/2.

Maulik
________________________________

**Comment by maulikshah23** [comment]
Hi @Xing ***@***.***>,

Will the documentation be updated as well by 7/2?

Maulik
________________________________

**Comment by zhoxing-ms** [comment]
@maulikshah23 Yes
