### ISSUE TITLE
Install script breaks Github action in 2.61

### ISSUE THREAD

**Issue by jimmystridh** [Azure/azure-cli#28984]
### Describe the bug

We are running the install script at `https://aka.ms/InstallAzureCLIDeb` in a github action pipeline like this:
```
      - name: Install Azure CLI
        run: |
          sudo apt update && sudo apt-get install curl -y
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
```

this morning this was broken, and it seems like the reason is because the gpg installation breaks the script with
```
gpg: cannot open '/dev/tty': No such device or address
curl: (23) Failed writing body
Error: Process completed with exit code 2.
```

I did some digging by enabling a tty and it seems the gpg installation wants to ask for an okay to overwrite the file:
`File '/etc/apt/keyrings/microsoft.gpg' exists. Overwrite? (y/N)`

which I assume is due to the path changes in:
`https://github.com/Azure/azure-cli/commit/655b05b15204ef8a5c76b7a5cd78cb489058530a`

### Related command

https://aka.ms/InstallAzureCLIDeb

### Errors

gpg: cannot open '/dev/tty': No such device or address
curl: (23) Failed writing body
Error: Process completed with exit code 2.

### Issue script & Debug output

not possible

### Expected behavior

the install script installs az cli without error

### Environment Summary

github action standard runner, before installation

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jimmystridh** [comment]
I was able to work around the issue by completely removing the addition of the key:
```
- name: Install Azure CLI
        run: |
          sudo apt update && sudo apt-get install curl -y
          curl -sL https://aka.ms/InstallAzureCLIDeb -o installAzureCli.sh
          sed -i '/curl -sLS https:\/\/packages.microsoft.com\/keys\/microsoft.asc |/d' installAzureCli.sh
          sed -i '/gpg --dearmor -o \/etc\/apt\/keyrings\/microsoft.gpg/d' installAzureCli.sh
          sed -i '/chmod go+r \/etc\/apt\/keyrings\/microsoft.gpg/d' installAzureCli.sh
          sudo bash installAzureCli.sh
```

**Comment by boobboo** [comment]
> I was able to work around the issue by completely removing the addition of the key:
> 
> ```
> - name: Install Azure CLI
>         run: |
>           sudo apt update && sudo apt-get install curl -y
>           curl -sL https://aka.ms/InstallAzureCLIDeb -o installAzureCli.sh
>           sed -i '/curl -sLS https:\/\/packages.microsoft.com\/keys\/microsoft.asc |/d' installAzureCli.sh
>           sed -i '/gpg --dearmor -o \/etc\/apt\/keyrings\/microsoft.gpg/d' installAzureCli.sh
>           sed -i '/chmod go+r \/etc\/apt\/keyrings\/microsoft.gpg/d' installAzureCli.sh
>           sudo bash installAzureCli.sh
> ```

Thanks for the workaround, I also have had the same issue
Chris

**Comment by ajadams-T4** [comment]
This has also broken for me but i'm using VMSS in azure devops pipelines. Appreciate the workaround.

**Comment by taco-coder** [comment]
I'm also running into this same issue using "ubuntu-latest" on Azure DevOps Pipelines. Really appreciate the work around.

**Comment by bebound** [comment]
We've updated the script at `https://aka.ms/InstallAzureCLIDeb` to fix this issue.
