### ISSUE TITLE
Az account should use subscriptionid and principalid/tenantid combination as primary key

### ISSUE THREAD

**Issue by cveld** [Azure/azure-cli#28985]
**Related command**

Az login / az account set

**Is your feature request related to a problem? Please describe.**

Currently whenever you do az login with a particular subscriptionid with a set of principalids, the latest operation always overwrites the previous ones. Only the subscriptionid is currently used as the primary key for an account context.

**Describe the solution you'd like**

Like the Azure PowerShell modules (Az.Account) I would like to add the full set of principals for a particular subscription (or even subscription less for that matter) to the az cli context.

**Describe alternatives you've considered**

Currently I use the environment variable setting to specify a different folder for every principal.

**Additional context**

I believe this was discussed already early on in the lifetime of the az cli but can't find back the related issue.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
