### ISSUE TITLE
Unable to log in interactivelly on 2.61.0: User cancelled the Accounts Control Operation

### ISSUE THREAD

**Issue by jomacedo** [Azure/azure-cli#28997]
### Describe the bug

When I try to az login I get the following behavior:
![image](https://github.com/Azure/azure-cli/assets/42640349/f9788d7b-63d7-4759-b76e-5f4c832ad673)

It looks like it gets a UserCanceled before the Sign in window ever pops up.
If I click Continue in the Sign in window it crashes the Terminal.

### Related command

az login

### Errors

User cancelled the Accounts Control Operation.. Status: Response_Status.Status_UserCanceled, Error code: 0, Tag: 528315210
Please explicitly log in with:
az login

### Issue script & Debug output

cli.knack.cli: Command arguments: ['login', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x000002080C55B920>, <function OutputProducer.on_global_arguments at 0x000002080C6E6160>, <function CLIQuery.on_global_arguments at 0x000002080C713CE0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'login': ['azure.cli.command_modules.profile']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: profile                   0.002         2         8
cli.azure.cli.core: Total (1)                 0.002         2         8
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: Loaded 2 groups, 8 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : login
cli.azure.cli.core: Command table: login
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x000002080F66E3E0>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\jomacedo\.azure\commands\2024-05-21.11-50-14.login.26344.log'.
az_command_data_logger: command args: login --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x000002080F6D4900>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x000002080F6D49A0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x000002080F6D4AE0>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x000002080C6E6200>, <function CLIQuery.handle_query_parameter at 0x000002080C713D80>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x000002080F6D4A40>]
cli.azure.cli.core.auth.persistence: build_persistence: location='C:\\Users\\jomacedo\\.azure\\msal_token_cache.bin', encrypt=True
cli.azure.cli.core.auth.binary_cache: load: C:\Users\jomacedo\.azure\msal_http_cache.bin
urllib3.util.retry: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
msal.authority: Initializing with Entra authority: https://login.microsoftonline.com/organizations
msal.authority: openid_config("https://login.microsoftonline.com/organizations/v2.0/.well-known/openid-configuration") = {'token_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/organizations/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/{tenantid}/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/organizations/kerberos', 'tenant_region_scope': None, 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'}
msal.application: Broker enabled? True
msal.application: Falls back to broker._signin_interactively()
cli.azure.cli.core.auth.identity: Please select the account you want to log in with.
msal.broker: [MSAL:0001]        WARNING SetAuthorityString:98   Initializing authority from string 'https://login.microsoftonline.com/organizations' without authority type, defaulting to MsSts
msal.broker: [MSAL:0002]        INFO    SetCorrelationId:273    Set correlation ID: 0c8c6c51-eb49-4fd8-a7c2-e0fb9720def6
msal.broker: [MSAL:0002]        INFO    ExecuteInteractiveRequest:1103  The original authority is 'https://login.microsoftonline.com/organizations'
msal.broker: [MSAL:0002]        WARNING TryNormalizeRealm:2295  No HomeAccountId provided to normalize the realm
msal.broker: [MSAL:0002]        INFO    ExecuteInteractiveRequest:1114  The normalized realm is ''
msal.broker: [MSAL:0002]        INFO    ModifyAndValidateAuthParameters:191     Additional query parameter added successfully. Key: '(pii)' Value: '(pii)'
msal.broker: [MSAL:0002]        INFO    ModifyAndValidateAuthParameters:191     Additional query parameter added successfully. Key: '(pii)' Value: '(pii)'
msal.broker: [MSAL:0002]        INFO    ModifyAndValidateAuthParameters:215     Authority Realm: organizations
msal.broker: [MSAL:0003]        WARNING ReturnResponseDueToMissingParameter:643 Attempted to read cache with a non-normalized realm, access token and ID token reads will fail
msal.broker: [MSAL:0003]        WARNING ReadAccountById:227     Account id is empty - account not found
msal.broker: [MSAL:0004]        INFO    ErrorInternalImpl:116   Created an error: 55xnk, StatusInternal::UserCanceled, InternalEvent::None, Context 'User cancelled the Accounts Control Operation.'
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:383    Printing Telemetry for Correlation ID: 0c8c6c51-eb49-4fd8-a7c2-e0fb9720def6
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:391    Key: start_time, Value: 2024-05-21T10:50:14.000Z
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:391    Key: api_name, Value: SignInInteractively
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:391    Key: was_request_throttled, Value: false
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:391    Key: authority_type, Value: Unknown
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:391    Key: msal_version, Value: 1.1.0+local
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:391    Key: api_status_code, Value: StatusInternal::UserCanceled
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:391    Key: client_id, Value: 04b07795-8ddb-461a-bbee-02f9e1bf7b46
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:391    Key: correlation_id, Value: 0c8c6c51-eb49-4fd8-a7c2-e0fb9720def6
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:391    Key: broker_app_used, Value: true
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:391    Key: stop_time, Value: 2024-05-21T10:50:14.000Z
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:391    Key: all_error_tags, Value: 55xnk
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:391    Key: msalruntime_version, Value: 0.14.2-alpha1
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:391    Key: original_authority, Value: https://login.microsoftonline.com/organizations
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:391    Key: additional_query_parameters_count, Value: 2
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:391    Key: read_token_last_error, Value: missing required parameter
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:391    Key: request_eligible_for_broker, Value: true
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:391    Key: auth_flow, Value: Broker
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:391    Key: ui_event_count, Value: 1
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:391    Key: authorization_type, Value: Interactive
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:391    Key: api_error_code, Value: 0
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:391    Key: api_error_tag, Value: 55xnk
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:391    Key: api_error_context, Value: User cancelled the Accounts Control Operation.
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:391    Key: is_successful, Value: false
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:391    Key: request_duration, Value: 20
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:396    Printing Execution Flow:
msal.broker: [MSAL:0004]        INFO    LogTelemetryData:404    {"t":"646u1","tid":2,"ts":0,"l":2},{"t":"4s7ub","tid":2,"ts":0,"l":2},{"t":"4sufd","tid":2,"ts":0,"s":2,"l":2},{"t":"4swgg","tid":2,"ts":0,"s":1,"l":2},{"t":"4swgf","tid":2,"ts":0,"s":1,"l":2},{"t":"4swgi","tid":3,"ts":0,"s":1,"l":2},{"t":"8dqim","tid":3,"ts":0,"l":2},{"t":"8dqkl","tid":3,"ts":0,"l":2,"a":9,"ie":0},{"t":"54uxd","tid":2,"ts":0,"l":2},{"t":"8dqkn","tid":4,"ts":19,"l":2,"a":5,"ie":1},{"t":"8dqko","tid":4,"ts":19,"l":2,"a":9,"ie":1},{"t":"646u1","tid":4,"ts":19,"l":2}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 664, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 701, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 334, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 158, in login
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 172, in login
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 166, in login_with_auth_code
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/util.py", line 139, in check_result
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/util.py", line 43, in aad_error_handler
azure.cli.core.azclierror.AuthenticationError: User cancelled the Accounts Control Operation.. Status: Response_Status.Status_UserCanceled, Error code: 0, Tag: 528315210

cli.azure.cli.core.azclierror: User cancelled the Accounts Control Operation.. Status: Response_Status.Status_UserCanceled, Error code: 0, Tag: 528315210
az_command_data_logger: User cancelled the Accounts Control Operation.. Status: Response_Status.Status_UserCanceled, Error code: 0, Tag: 528315210
Please explicitly log in with:
az login
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x000002080F66E660>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.475 seconds (init: 0.280, invoke: 0.196)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 4837 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\jomacedo\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

The command waits for me to choose my account and then successfully logs in.

### Environment Summary

az --version
azure-cli                         2.61.0

core                              2.61.0
telemetry                          1.1.0

Extensions:
azure-iot                         0.23.1
azure-iot-ops                    0.5.0b1
bastion                            0.3.0
connectedk8s                       1.7.3
customlocation                     0.1.3
k8s-extension                      1.6.1
ssh                                2.0.3

Dependencies:
msal                              1.28.0
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\jomacedo\.azure\cliextensions'

Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

Started happening once I upgraded from 2.60.0 to 2.61.0.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jomacedo** [comment]
@pgr-lopes is seeing the same.

**Comment by pgr-lopes** [comment]
+1 on Windows 11 and AzCli 2.61, it didn't happen in 2.60

**Comment by odaiwa** [comment]
same, Windows 10 azure-cli version `2.58.0`

**Comment by jomacedo** [comment]
Update: although this fails in Windows Terminal + PowerShell 7.4.2, it works with VS Code + PowerShell 7.4.2 🤔

**Comment by msftnadavbh** [comment]
Fails on WSL as well [Ubuntu and others tested] - 

nadav@NADAVBH-YOGA:~$ az login
A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
gio: https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize?client_id=04b07795-8ddb-461a-bbee-02f9e1bf7b46&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A43603&scope=https%3A%2F%2Fmanagement.core.windows.net%2F%2F.default+offline_access+openid+profile&state=OsUThVrwEiympJZj&code_challenge=X1yss09JxHVPoCfrc1jAs-PRk40m9ongIuSrgpG49F0&code_challenge_method=S256&nonce=9b473f4bf81379ba8aea3b853bd319c230dd71a0c9d7bf9bfedb3f03f988bb95&client_info=1&claims=%7B%22access_token%22%3A+%7B%22xms_cc%22%3A+%7B%22values%22%3A+%5B%22CP1%22%5D%7D%7D%7D&prompt=select_account: Operation not supported

**Comment by jiasli** [comment]
@msftnadavbh, your issue `gio: https://...: Operation not supported` is different from this one. Please see https://github.com/Azure/azure-cli/issues/27879.

**Comment by jiasli** [comment]
https://github.com/Azure/azure-cli/pull/28841 made WAM the default authentication method. While we are investigating this issue, you may temporarily revert back to browser flow following the instruction at https://github.com/Azure/azure-cli/pull/28841#issue-2265611727:

```
az account clear
az config set core.enable_broker_on_windows=false
az login
```

BTW, it seems everyone seeing this issue is a Microsoft employee. Not sure if it happens to external users.

**Comment by bengimblett** [comment]
after upgrading it works for me without the config switch on terminal (PS1) and cmd
(I'm msft)

**Comment by simonkurtz-MSFT** [comment]
**Thumbs up if you see this issue as a Microsoft employee**

**Thumbs down otherwise**

**Comment by vancleimatheus** [comment]
having the same issue, following the thread

**Comment by simonkurtz-MSFT** [comment]
For the time being, I ended up wiping my AZ CLI configuration, including the auto-upgrade of CLI versions, then I uninstalled 2.61.0, then installed 2.60.0. With Build this week, it's not the right time for me to troubleshoot. That was a radical way to do it, but it's an option.

**Comment by jiasli** [comment]
> Looks like the login process changed, because when I logged in, a menu with the subscriptions that I have available is listed, there's an announcement with a link that redirects to https://learn.microsoft.com/en-us/cli/azure/authenticate-azure-cli-interactively

Indeed, we changed the login process, but WAM and subscription selector are two separate features and are not related.

**Comment by jiasli** [comment]
To everyone seeing this issue: When this issue happens, are you running Windows Terminal as administrator? Please click 👍 if so, 👎 if not.

**Comment by jiasli** [comment]
Upstream issue on MSAL: https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/707

**Comment by TheOnlyWei** [comment]
> To everyone seeing this issue: When this issue happens, are you running Windows Terminal as administrator? Please click 👍 if so, 👎 if not.

This happens for both administrator and non-administrator on PowerShell. So, I added both a thumbs down and thumbs up.

**Comment by SASELAMB** [comment]
It works on a system with with following config

PS C:\windows\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.3672
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.3672
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\windows\system32> az --version
azure-cli                         2.56.0 *

core                              2.56.0 *
telemetry                          1.1.0

Extensions:
azure-cli-ml                      1.41.0
connectedmachine                   0.7.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\xxx\.azure\cliextensions'

Python (Windows) 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal


You have 2 update(s) available. Consider updating your CLI installation with 'az upgrade'

**Comment by squirrelmaster666** [comment]
Not a microsoft employee . doing classes for the 104  the below  ( that was mentioned by jiasli ) worked perfectly. I have ben trying all kinds of things over the last week. 
Updated powershell, updated windows , installed all the az packages again , even -devicecode wasn't working , now they both are. thanks 
Win 11 23H2 
{
  "azure-cli": "2.61.0",
  "azure-cli-core": "2.61.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {}

> #28841 made WAM the default authentication method. While we are investigating this issue, you may temporarily revert back to browser flow following the instruction at [#28841 (comment)](https://github.com/Azure/azure-cli/pull/28841#issue-2265611727):
> 
> ```
> az account clear
> az config set core.enable_broker_on_windows=false
> az login
> ```
> 
> BTW, it seems everyone seeing this issue is a Microsoft employee. Not sure if it happens to external users.

**Comment by mcdonamw** [comment]
I just installed Az CLI for the first time and I ran into this issue as well.  I was running Powershell 7 via administrator.  If I run as non-admin, it works fine.

**Comment by jch254-lawvu** [comment]
I also just installed Azure CLI for the first time today via Chocolatey and I ran into this issue as well. I was running Powershell via administrator. The solution posted above did the trick:
```
az account clear
az config set core.enable_broker_on_windows=false
az login
```

**Comment by jiasli** [comment]
The Release Candidate of Azure 2.62.0 has been released which fixed this issue. You download from:

- MSI: https://azcliprod.blob.core.windows.net/msi/azure-cli-2.62.0-x64.msi
- ZIP: https://azcliprod.blob.core.windows.net/zip/azure-cli-2.62.0-x64.zip

**Comment by docouto** [comment]
Hi all, 
I was following the thread and I can confirm that running Az CLI **2.63.0** has _fixed_ the issue to me.

For context: 

- I am not a Microsoft employee
- Running on Windows Terminal as Admin 

Thanks for the work put into this!
