### ISSUE TITLE
Unable to retrieve CDN endpoint list for az cli versions 2.60 and 2.61 

### ISSUE THREAD

**Issue by theAmazingJia** [Azure/azure-cli#29005]
### Describe the bug

I'm using AzureChinaCloud region.
And I'm trying to retrieve cdn endpoint list from the following command:
az cdn endpoint list  -g cdn --profile-name jiacdnprofile

But I got this error:

(InvalidResourceType) The resource type 'profiles/endpoints' could not be found in the namespace 'Microsoft.Cdn' for api version '2024-02-01'. The supported api-versions are '2015-06-01,2016-04-02,2016-10-02,2017-04-02,2017-10-12,2018-04-02,2019-04-15,2019-06-15-preview,2019-12-31,2020-09-01,2021-06-01,2023-05-01'.
Code: InvalidResourceType
Message: The resource type 'profiles/endpoints' could not be found in the namespace 'Microsoft.Cdn' for api version '2024-02-01'. The supported api-versions are '2015-06-01,2016-04-02,2016-10-02,2017-04-02,2017-10-12,2018-04-02,2019-04-15,2019-06-15-preview,2019-12-31,2020-09-01,2021-06-01,2023-05-01'.

This issue can be produced in az versions 2.60 and 2.61. And for versions including and below 2.59, this issue does not exist.

### Related command

az cdn endpoint list 

### Errors

(InvalidResourceType) The resource type 'profiles/endpoints' could not be found in the namespace 'Microsoft.Cdn' for api version '2024-02-01'. The supported api-versions are '2015-06-01,2016-04-02,2016-10-02,2017-04-02,2017-10-12,2018-04-02,2019-04-15,2019-06-15-preview,2019-12-31,2020-09-01,2021-06-01,2023-05-01'.
Code: InvalidResourceType
Message: The resource type 'profiles/endpoints' could not be found in the namespace 'Microsoft.Cdn' for api version '2024-02-01'. The supported api-versions are '2015-06-01,2016-04-02,2016-10-02,2017-04-02,2017-10-12,2018-04-02,2019-04-15,2019-06-15-preview,2019-12-31,2020-09-01,2021-06-01,2023-05-01'.

### Issue script & Debug output

(InvalidResourceType) The resource type 'profiles/endpoints' could not be found in the namespace 'Microsoft.Cdn' for api version '2024-02-01'. The supported api-versions are '2015-06-01,2016-04-02,2016-10-02,2017-04-02,2017-10-12,2018-04-02,2019-04-15,2019-06-15-preview,2019-12-31,2020-09-01,2021-06-01,2023-05-01'.
Code: InvalidResourceType
Message: The resource type 'profiles/endpoints' could not be found in the namespace 'Microsoft.Cdn' for api version '2024-02-01'. The supported api-versions are '2015-06-01,2016-04-02,2016-10-02,2017-04-02,2017-10-12,2018-04-02,2019-04-15,2019-06-15-preview,2019-12-31,2020-09-01,2021-06-01,2023-05-01'.

### Expected behavior

Retrieve the cnd endpoints

### Environment Summary

2.60.0
2.61.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by t-bzhan** [comment]
Loop @Ptnan7 to take a look.

**Comment by t-bzhan** [comment]
Hi @theAmazingJia , We are working on upgrading the Miicrosoft.CDN manifest for AzureChinaCloud. Those versions should be available in a week or two.

**Comment by Ptnan7** [comment]
We updated the CDN manifest for China, please retry and if any failure, contact us.
