### ISSUE TITLE
netappfiles pool update expects TB, but documentation says bytes. 

### ISSUE THREAD

**Issue by matt-chan** [Azure/azure-cli#29015]
### Describe the bug

The `netappfiles pool update --size` parameter documentation says it should be in bytes, but the code expects TB. This is also the case for `netappfiles pool create --size`. 

The offending line is here: https://github.com/Azure/azure-cli/blob/a4723a12378a0395231b03bdc84fbd741916bd08/src/azure-cli/azure/cli/command_modules/netappfiles/custom.py#L213

The documentation is here: https://learn.microsoft.com/en-us/cli/azure/netappfiles/pool?view=azure-cli-latest#az-netappfiles-pool-update

### Related command

`netappfiles pool update --size`

### Errors

azcli reports the input is too large.

### Issue script & Debug output

N/A

### Expected behavior

The documentation should be updated, or the command should take bytes. 

### Environment Summary

azure-cli                         2.61.0

core                              2.61.0
telemetry                          1.1.0

Dependencies:
msal                              1.28.0
azure-mgmt-resource               23.1.1

Python location '/opt/az/bin/python3'
Extensions directory '/home/hpcadmin/.azure/cliextensions'

Python (Linux) 3.11.8 (main, May 16 2024, 03:47:41) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by audunn** [comment]
The documentation is fixed here https://github.com/Azure/azure-cli/pull/29624
