### ISSUE TITLE
CLI changes for VNet Carrying VIP for Storage regional traffic for 1PCustomers.

### ISSUE THREAD

**Issue by bhupeshbhatt1985** [Azure/azure-cli#29029]
**Related command**

No changes in command , additional new field "networkIdentifier" will be added in the existing command.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Enabling Service Endpoints on VNet subnet API, improvement to support referencing a public IP address resource: 

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
@bhupeshbhatt1985 seems a feature request, please leverage https://github.com/Azure/azure-cli/issues/new?assignees=&labels=&projects=&template=Feature_request.md&title=
