### ISSUE TITLE
[Redis] Issues with Redis commands 

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#2902]
Reviewing the updated Redis commands, I found the following issues:

- [ ] If I simply run `az redis update -g myRG -n myRedisCache` with no additional parameters (essentially PUTting the object back unchanged), I get the following error (created with Basic SKU):
```
The setting 'maxmemory-reserved' is not allowed on 'Basic' cache instances.
RequestID=f76b1c36-7b1b-4620-8afa-42549d39e3a4
```
- [ ] If I try to change the SKU from Basic (C2) to Premium, I get the following error:
```
Exception of type 'AzCacheRP.Exceptions.SkuFamilyNotSupportedException' was thrown.
RequestID=d7a662ad-5d0b-4222-b3c4-f9deb2a933e4
```
- [x] The help text for SKU on `redis create` shows the allowed values twice:
```
    --sku               [Required]: What type of redis cache to deploy. Valid values: (Basic,
                                    Standard, Premium).  Allowed values: Basic, Premium, Standard.
```

**Comment by MECHANDR** [comment]
You can't scale from a Basic cache directly to a Premium cache. First, scale from Basic to Standard in one scaling operation, and then from Standard to Premium in a subsequent scaling operation. Please refer to this documentation for supported ways to scale: <https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-how-to-scale#scale-a-cache>
