### ISSUE TITLE
GitHub.Network resource provider stuck registering status

### ISSUE THREAD

**Issue by yasirmohamed777** [Azure/azure-cli#29028]
### Describe the bug

Tried to register the GitHub.Network resource provider and it has been stuck on registering status for about 24 hours not

### Related command

`az provider register --namespace GitHub.Network`

### Errors

The resource provider stuck on the registering status

### Issue script & Debug output

The resource provider stuck on the registering status, there is no information of failure

### Expected behavior

The resource to have registered status at a reasonable amount of time

### Environment Summary

azure-cli                         2.61.0
core                              2.61.0
telemetry                          1.1.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by oscarhermoso** [comment]
Our company is running into the same issue right now, looks like this:

![image-20240527-080857](https://github.com/Azure/azure-cli/assets/23239955/7f1f9cc6-f5f9-4b95-b8b5-06ce9a6e9983)

**Comment by yasirmohamed777** [comment]
The issue seems to be resolved and the provider registered after 3 days
