### ISSUE TITLE
New endpoints in cloud config file not used in config for the cloud already exists

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-cli#2905]
Hi there,

We had a customer encounter an error where the recently added 'batch_resource_id' was not set in their cached clouds.config file, yet the Batch command module requested it. In other words - the cached config was out-of-date with the rest of the CLI installation, and didn't contain the latest fields as required by the modules. 
Is this expected behavior? Or should the CLI core update the cached config file between version updates?

The customer is running on Ubuntu 16.04 LTS, and their CLI install history is as follows:
- Initially installed the apt-get package from a few months ago, however this didn't work with [this tutorial](https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fvirtual-machines%2Fvirtual-machines-linux-capture-image%3Ftoc%3D%252fazure%252fvirtual-machines%252flinux%252ftoc.json&data=02%7C01%7CAnna.Tisch%40microsoft.com%7C62e25bbad1954ed12b6a08d4867c326f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636281315363138094&sdata=pZ%2F0SnHJzNpSrsq5jXcKmdBZ47JVKPEiP%2B4b8A%2BU4UE%3D&reserved=0)
- Installed the nightly build in order to image VMs.
- Upgraded to the latest apt-get package, with the following version info:
az --version
azure-cli (2.0.3)
acr (2.0.1)
acs (2.0.3)
appservice (0.1.3)
batch (2.0.1)
cloud (2.0.1)
component (2.0.1)
configure (2.0.3)
container (0.1.3)
core (2.0.3)
documentdb (0.1.3)
feedback (2.0.1)
find (0.0.2)
iot (0.1.3)
keyvault (2.0.1)
lab (0.0.2)
monitor (0.0.2)
network (2.0.3)
nspkg (2.0.0)
profile (2.0.3)
redis (0.2.0)
resource (2.0.3)
role (2.0.2)
sql (2.0.1)
storage (2.0.3)
vm (2.0.3)
Python (Linux) 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

Is the above install process likely to have led to the confused config file? If so - is there a guaranteed method to wipe an installation along with any cached configs and profile data to insure a clean update?

Thanks,
Anna

**Comment by kpu** [comment]
I'm the customer.

**Comment by derekbekoe** [comment]
As a workaround, you can delete the file `~/.azure/clouds.config`.
It will get recreated once you run `az` and then `batch_resource_id` will exist. (if you added your own custom cloud, remember to save that though)

The issue was that the new `batch_resource_id` was added but since `~/.azure/clouds.config` already existed, it wasn't updated.

Renaming the issue to reflect this.
