### ISSUE TITLE
Cannot add another IP to an existing VMSS

### ISSUE THREAD

**Issue by amitmavgupta** [Azure/azure-cli#29061]
### Describe the bug

- Cannot add another IP to an existing VMSS. 
- Have an AKS cluster with two nodegroups. Trying to add another IP to an existing VMSS and it's not working via Az CLI. Can the exact steps be shared, please?
- Do I need to use a different load balancer than the one existing for index[0]? I did create another load balancer but it seems I need to create index1 first which I am not able to figure out how to do that.
- Also, saw in another bug that the feature needs to be enabled but it has been in Pending state forever. 

```
az feature show --name 'AllowPublicIpsAndLoadBalancingOnSecondaryIpConfigsInVMScaleSet' --namespace 'Microsoft.Network'
{
  "id": "/subscriptions/8dbd2563-77eb-41a1-917b-5a1344da9767/providers/Microsoft.Features/providers/Microsoft.Network/features/AllowPublicIpsAndLoadBalancingOnSecondaryIpConfigsInVMScaleSet",
  "name": "Microsoft.Network/AllowPublicIpsAndLoadBalancingOnSecondaryIpConfigsInVMScaleSet",
  "properties": {
    "state": "Pending"
  },
  "type": "Microsoft.Features/providers/features"
}
```

### Related command

az vmss update --resource-group MC_byocni_byocni_canadacentral  --name aks-egressgw-27814974-vmss --add virtualMachineProfile.networkProfile.networkInterfaceConfigurations[1].ipConfigurations[1].loadBalancerBackendAddressPools '{"id": "/subscriptions/##########################/resourceGroups/MC_byocni_byocni_canadacentral/providers/Microsoft.Network/loadBalancers/testegress/backendAddressPools/testegress-backendpool01"}'
index 1 doesn't exist on [1]

### Errors

index 1 doesn't exist on [1]

### Issue script & Debug output

index 1 doesn't exist on [1]

### Expected behavior

Please inform the users how to add multiple NIC's in a VMSS.

### Environment Summary

{
  "azure-cli": "2.61.0",
  "azure-cli-core": "2.61.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "account": "0.2.5",
    "aks-preview": "4.0.0b4",
    "azure-firewall": "1.0.1",
    "connectedk8s": "1.7.3",
    "customlocation": "0.1.3",
    "k8s-extension": "1.6.1",
    "ml": "2.26.0",
    "quota": "1.0.0",
    "ssh": "2.0.3"
  }
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by amitmavgupta** [comment]
Hello, I was able to find a solution for this issue and hence closing this bug.
