### ISSUE TITLE
googlecloudcommunity.com/qsqph94282/rss/message?board.id=chronicle-announcements&message.id=134

### ISSUE THREAD

**Issue by devarmenchik1408** [Azure/azure-cli#29077]
https://www.googlecloudcommunity.com/qsqph94282/rss/message?board.id=chronicle-announcements&message.id=134

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by devarmenchik1408** [comment]
https://www.googlecloudcommunity.com/gc/News-Announcements/New-community-ranking-structure-and-badges-are-now-live/td-p/734116
