### ISSUE TITLE
No module named mgmt.sql.operations.servers_operations

### ISSUE THREAD

**Issue by iyerusad** [Azure/azure-cli#2907]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: 
```
sudo apt-get update && sudo apt-get install -y libssl-dev libffi-dev python-dev build-essential
curl -L https://aka.ms/InstallAzureCli | bash
```

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

> azure-cli (2.0.3)
> 
> acr (2.0.1)
> acs (2.0.3)
> appservice (0.1.3)
> batch (2.0.1)
> cloud (2.0.1)
> component (2.0.1)
> configure (2.0.3)
> container (0.1.3)
> core (2.0.3)
> documentdb (0.1.3)
> feedback (2.0.1)
> find (0.0.2)
> iot (0.1.3)
> keyvault (2.0.1)
> lab (0.0.2)
> monitor (0.0.2)
> network (2.0.3)
> nspkg (2.0.0)
> profile (2.0.3)
> redis (0.2.0)
> resource (2.0.3)
> role (2.0.2)
> sql (2.0.1)
> storage (2.0.3)
> vm (2.0.3)
> 
> Python (Linux) 2.7.12 (default, Nov 19 2016, 06:48:10)
> [GCC 5.4.0 20160609]

**OS Version:** What OS and version are you using?  
Answer here: `Ubuntu 16.04.2 LTS`

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: `bash`

---

### Description
Basic command (`az sql server create`) fails with error about missing module. Didn't manually update az-cli so curious how to resolve and how to possibly avoid. Not sure if similar to #2811 but the solution in #2811 suggestion Python 3.6, which is not currently available in stable Ubuntu 16.04 repos.

`sudo apt-get update && sudo apt-get upgrade`
`az sql server create`

> No module named mgmt.sql.operations.servers_operations
> Traceback (most recent call last):
>   File "/home/runner/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
>     cmd_result = APPLICATION.execute(args)
>   File "/home/runner/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 166, in execute
>     self.configuration.load_params(command)
>   File "/home/runner/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 49, in load_params
>     commands.load_params(command)
>   File "/home/runner/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 244, in load_params
>     command_table[command].load_arguments()
>   File "/home/runner/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 206, in load_arguments
>     self.arguments.update(self.arguments_loader())
>   File "/home/runner/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 442, in arguments_loader
>     return extract_args_from_signature(get_op_handler(operation), no_wait_param=no_wait_param)
>   File "/home/runner/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 340, in get_op_handler
>     op = import_module(mod_to_import)
>   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
> ImportError: No module named mgmt.sql.operations.servers_operations

**Comment by iyerusad** [comment]
Looks like not component specific? Another basic command fails:

`az account set --subscription ${AzureSubscriptionID}`

> ERROR: No module named mgmt.resource
> Traceback (most recent call last):
>   File "/home/runner/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
>     cmd_result = APPLICATION.execute(args)
>   File "/home/runner/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 201, in execute
>     result = expanded_arg.func(params)
>   File "/home/runner/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 403, in _execute_command
>     raise ex
> ImportError: No module named mgmt.resource

**Comment by derekbekoe** [comment]
@iyerusad Yes this isn't specific to SQL.
Since you're running the CLI that came through the interactive script, run `curl -L https://aka.ms/InstallAzureCli | bash` again. When prompted to remove this directory, choose yes.
This will give you a clean (latest) install.

fyi @johanste @lmazuel

**Comment by iyerusad** [comment]
@derekbekoe This (clean latest install) successfully resolved the issue for me:
```
curl -L https://aka.ms/InstallAzureCli | bash
#When prompted to remove this directory, choose yes.
```
Thank you.

Not sure if close or should be left in packaging bug queue.

**Comment by derekbekoe** [comment]
Will leave it open for now so it's more visible.

**Comment by derekbekoe** [comment]
Closing and marking as FAQ as I've seen a few others run into this.
