### ISSUE TITLE
Add support for querying ARM operations

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#2908]
In the CLI 2.0 today, we don't have a way of showing operations, and (per the ARM team) "operations is critical for RBAC (creating custom roles etc) and auditing (this is what gets written into Event service entries)."

**Comment by mayurid** [comment]
@yugangw-msft:  thoughts on the work here?

**Comment by yugangw-msft** [comment]
@mayurid, the work is fairly straightforward, please schedule for //build
