### ISSUE TITLE
Hakeo

### ISSUE THREAD

**Issue by Marlonhak** [Azure/azure-cli#29094]
**Related command**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

# A first-level heading
### A third-level heading

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by Marlonhak** [comment]
Quiero aprender

**Comment by Marlonhak** [comment]
# A first-level heading
## A second-level heading
### A third-level heading
