### ISSUE TITLE
Infinite Status Pulling During Deployment with az webapp deploy Command on Azure App Service (Linux)

### ISSUE THREAD

**Issue by EugeneDeveloper** [Azure/azure-cli#29090]
### Describe the bug

When deploying an application to an Azure App Service running on a Linux system using the az webapp deploy command, the command shows a successful status message. However, it continues to pull the result of the deployment indefinitely after the successful log line is displayed. This issue does not occur when deploying to an Azure App Service running on a Windows system.

### Related command

az webapp deploy --resource-group resource-group-name --name app-name-in-azure --src-path source.zip --type zip --slot slotName

### Errors

no error

### Issue script & Debug output

Initiating deployment
Deploying from local path: application_1.0.0.zip
Polling the status of sync deployment. Start Time: 2024-06-04 09:53:59.555758+00:00 UTC
Status: Build successful. Time: 0(s)
Status: Build successful. Time: 17(s)
Status: Build successful. Time: 32(s)
Status: Build successful. Time: 48(s)
Status: Build successful. Time: 67(s)
Status: Build successful. Time: 83(s)
Status: Build successful. Time: 99(s)
Status: Build successful. Time: 115(s)
Status: Build successful. Time: 131(s)
Status: Build successful. Time: 147(s)
Status: Build successful. Time: 163(s)
Status: Build successful. Time: 179(s)
Status: Build successful. Time: 195(s)
Status: Build successful. Time: 211(s)

### Expected behavior

Initiating deployment
Deploying from local path: application_1.0.0.zip
Polling the status of sync deployment. Start Time: 2024-06-04 10:41:20.833045+00:00 UTC
Deployment has completed successfully
You can visit your app at: http://example-url

### Environment Summary

azure-cli                         2.61.0

core                              2.61.0
telemetry                          1.1.0

Dependencies:
msal                              1.28.0
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'

Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by imfaber** [comment]
We are experiencing the same

**Comment by 2mas** [comment]
Same here, stopping our pipelines before triggering swap.

**Comment by EugeneDeveloper** [comment]
The "--track-status false" argument helped me.
