### ISSUE TITLE
Linking to this issue because it still exists, 3 years later: https://github.com/Azure/azure-cli/issues/19468

### ISSUE THREAD

**Issue by tyler-suard-parker** [Azure/azure-cli#29105]
### Describe the bug

Can't install azure-cli from requirements .txt due to jsmin being deprecated

### Related command

python -m pip install -r requirements.txt
(requirements.txt contains azure-cli)

### Errors

Using cached azure_cli_core-2.28.0-py3-none-any.whl.metadata (1.7 kB)
Collecting jsmin~=2.2.2 (from azure-cli->-r .\requirements.txt (line 12))
  Using cached jsmin-2.2.2.tar.gz (12 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in jsmin setup command: use_2to3 is invalid.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### Issue script & Debug output

azure-cli

### Expected behavior

This should install azure-cli, but it errors out instead.

### Environment Summary

Windows 11, Python 3.11.4

### Additional context

This is a 3 year old bug and it still has not been fixed.  WTF Microsoft?

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by tyler-suard-parker** [comment]
@azure-client-tools-bot-prd Here is the issue with that solution: if I downgrade my setuptools and my azure-cli version, then I will have to downgrade numerous other packages that the rest of my program depends on.  Most of my other packages are new, within the last year, and so downgrading azure-cli to a version from 3 years ago does not make sense for me.

**Comment by bebound** [comment]
The bot's second workaround also works.

**Comment by tyler-suard-parker** [comment]
@bebound I did not set the version, I just did pip install azure-cli.  I tried both workarounds and neither one works.  I am on Windows.

**Comment by bebound** [comment]
What's the content of `requirements.txt`?

**Comment by tyler-suard-parker** [comment]
@bebound here is my requirements.txt:

promptflow[azure]>=1.7.0
promptflow-tools
bs4
azure-cli
promptflow-tracing
promptflow-core

**Comment by tyler-suard-parker** [comment]
@bebound solution 2 worked but now I am getting version conflicts for cryptography: azure cli requires cryptography 3-4, while Promptflow requires cryptography 40.  How can I solve this?

**Comment by bebound** [comment]
Dependency conflict is a common issue in Python. This is out of CLI's scope.
