### ISSUE TITLE
Publish Azure CLI for Windows x86 as ZIP too

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/azure-cli#29104]
**Is your feature request related to a problem? Please describe.**

* Azure CLI for Windows x64 has been available as ZIP since #27911.
* Azure CLI for Windows x86 is as far as I can see only available through MSI.
* Somewhat related: #28856.

**Describe the solution you'd like**

Publish Azure CLI for Windows x86 as ZIP too, give x86 and x62 the same treatment.

**Describe alternatives you've considered**

None.

**Additional context**

ZIP is much faster to install/extract than MSI.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
We have no plan for this.
It's encouraged to gradually switch to the 64-bit version.
AFAIK, 32-bit version has this annoying issue for now: https://github.com/Azure/azure-cli/issues/27115
