### ISSUE TITLE
Preview warning still showing on az network lb address-pool address commands

### ISSUE THREAD

**Issue by thisisanniefang** [Azure/azure-cli#29103]
### Describe the bug

Preview message needs to be removed - IP-based backend pools have been GA for quite some time

### Related command

az network lb address-pool address
az network lb address-pool address add
az network lb address-pool address list
az network lb address-pool address remove
az network lb address-pool address show
az network lb address-pool address update
az network lb address-pool address wait

### Errors

![image](https://github.com/Azure/azure-cli/assets/32456734/8e616857-8950-4f01-bca0-db36312c3f21)

### Issue script & Debug output

N/A

### Expected behavior

No preview warning should show

### Environment Summary

azure-cli                         2.59.0 *

core                              2.59.0 *
telemetry                          1.1.0

Dependencies:
msal                              1.27.0
azure-mgmt-resource             23.1.0b2

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by thisisanniefang** [comment]
@yonzhan any status update on this issues?
