### ISSUE TITLE
az webapp deploy `complete` but no files uploaded 

### ISSUE THREAD

**Issue by emma12812** [Azure/azure-cli#29114]
### Describe the bug

I have the latest version of the CLI, my nodejs app is using node 20. Is zipped correctly (it has deployed before) and when I try and run this command 
`az webapp deploy --async true --name {}  --resource-group {}  --src-path ./build.zip  --type zip` I get a completed deployment 
<img width="362" alt="image" src="https://github.com/Azure/azure-cli/assets/43077292/273df66e-d2fa-4c2c-be16-f02b2815626b">
but no files are uploaded to my azure app service. 

I have the following env variables set in the app service  
SCM_DO_BUILD_DURING_DEPLOYMENT = false
SCM_ZIPDEPLOY_DONOT_PRESERVE_FILETIME = 1
WEBSITE_RUN_FROM_PACKAGE = 1

This app has deployed before but for the last 24 hours I cannot get anything to deploy 
The zip file includes my package.json all my build files and all my node modules. The zip runs locally

### Related command

az webapp deploy

### Errors

No files uploaded to auzre. 

### Issue script & Debug output

{
  "active": true,
  "author": "N/A",
  "author_email": "N/A",
  "build_summary": {
    "errors": [],
    "warnings": []
  },
  "complete": true,
  "deployer": "OneDeploy",
  "end_time": "2024-06-06T11:01:20.2013339Z",
  "id": "",
  "is_readonly": true,
  "is_temp": false,
  "last_success_end_time": "2024-06-06T11:01:20.2013339Z",
  "log_url": "",
  "message": "OneDeploy",
  "progress": "",
  "received_time": "2024-06-06T11:01:16.2191243Z",
  "site_name": "",
  "start_time": "2024-06-06T11:01:17.6685842Z",
  "status": 4,
  "status_text": "",
  "url": ""
}

### Expected behavior

Expect the files to upload and be able to view them in the advanced tools section of the app service 

### Environment Summary

azure cli 2.61.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
