### ISSUE TITLE
Principal not found in tenant error

### ISSUE THREAD

**Issue by AlbyST** [Azure/azure-cli#29113]
### Describe the bug

**Authentication failed**
invalid_resource: AADSTS500011: The resource principal named https://xxx.azure-devices-provisioning.net was not found in the tenant named yyy. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant. Trace ID: 7e4b5ba7-59cd-4d4f-82a5-a8370ce63400 Correlation ID: 89028c2e-ef28-4dac-b3e9-51cd8129d117 Timestamp: 2024-06-06 08:29:09Z. (https://login.microsoftonline.com/error?code=500011)

You can log an issue at [Azure CLI GitHub Repository](https://github.com/azure/azure-cli/issues) and we will assist you in resolving it.

### Related command

az login --scope https://xxx.azure-devices-provisioning.net/.default

### Errors

**Authentication failed**
invalid_resource: AADSTS500011: The resource principal named https://xxx.azure-devices-provisioning.net was not found in the tenant named yyy. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant. Trace ID: 7e4b5ba7-59cd-4d4f-82a5-a8370ce63400 Correlation ID: 89028c2e-ef28-4dac-b3e9-51cd8129d117 Timestamp: 2024-06-06 08:29:09Z. (https://login.microsoftonline.com/error?code=500011)

You can log an issue at [Azure CLI GitHub Repository](https://github.com/azure/azure-cli/issues) and we will assist you in resolving it.

### Issue script & Debug output

az login --scope https://xxx.azure-devices-provisioning.net/.default

### Expected behavior

I get authenticated and can access the requested resource.

### Environment Summary

azure-cli                         2.61.0

core                              2.61.0
telemetry                          1.1.0

Dependencies:
msal                              1.28.0
azure-mgmt-resource               23.1.1

Python location '/usr/local/Cellar/azure-cli/2.61.0/libexec/bin/python'
Extensions directory '/Users/zzz/.azure/cliextensions'

Python (Darwin) 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by jiasli** [comment]
The error `AADSTS500011` is returned by Microsoft Entra ID's token service and surfaced through Azure CLI.

Please check if `https://xxx.azure-devices-provisioning.net/` is correctly configured in the tenant `yyy` and allows Azure CLI's first party app ID `04b07795-8ddb-461a-bbee-02f9e1bf7b46`. Also, you may try adding `--tenant` and specifying the correct tenant ID.

If you still have any questions, please reach out to the customer support of the corresponding Resource Provider. Thanks for your understanding.
