### ISSUE TITLE
Confirmation message is useless in a loop

### ISSUE THREAD

**Issue by jaredmoo** [Azure/azure-cli#2912]
```
(env) C:\users\jaredmoo> az group list --query '[].name' --output tsv | findstr cmdlet-test | % { az group delete -n $_ --no-wait }
Are you sure you want to perform this operation? (y/n): y
Are you sure you want to perform this operation? (y/n): y
Are you sure you want to perform this operation? (y/n): y
```

Confirmation message doesn't help because I don't know what operation is being confirmed. I know that I'm deleting a group, but I don't know which one.

**Comment by tjprescott** [comment]
Good point. While it doesn't address the utility of the prompt, you can add -y to your delete command so that you won't have said prompt

**Comment by tjprescott** [comment]
What shell are you using?  I couldn't get this to work in CMD or bash.

**Comment by jaredmoo** [comment]
This is PowerShell.

**Comment by tjprescott** [comment]
Closing in favor of #4087.
