### ISSUE TITLE
"az containerapp hostname bind" does not create a managed certificate

### ISSUE THREAD

**Issue by MichaelCameronDHSC** [Azure/azure-cli#29128]
### Describe the bug

The command does not work as described.  Documentation states:
"Look for or create a managed certificate and bind with the hostname if no certificate or thumbprint is provided."
However, if not certificate or thumbprint is given the command fails.

### Related command

az containerapp hostname bind -n caefdtest001 -g rg-internalapp-dev-uks-001 --
hostname a02.azurefd.net

### Errors

Please specify at least one of parameters: --certificate and --thumbprint

### Issue script & Debug output

az containerapp hostname bind -n caefdtest001 -g rg-internalapp-dev-uks-001 --
hostname a02.azurefd.net

Please specify at least one of parameters: --certificate and --thumbprint

### Expected behavior

A managed certificate to be created and bound

### Environment Summary

{
  "azure-cli": "2.61.0",
  "azure-cli-core": "2.61.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "ai-examples": "0.2.5",
    "azure-devops": "1.0.0",
    "front-door": "1.1.0",
    "ml": "2.26.0",
    "ssh": "2.0.3"
  }
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by Greedygre** [comment]
Hi @MichaelCameronDHSC 

About "Look for or create a managed certificate and bind with the hostname if no certificate or thumbprint is provided."

You need to install `containerapp` extension with command: `az extension add -n containerapp`.

**Comment by MichaelCameronDHSC** [comment]
Sorry but this suggestion still fails, albeit with a different error message:

michael_cameron [ ~ ]$ az extension add -n containerapp
Default enabled including preview versions for extension installation now. Disabled in future release. Use '--allow-preview true' to enable it specifically if needed. Use '--allow-preview false' to install stable version only. 
The installed extension 'containerapp' is in preview.
michael_cameron [ ~ ]$ az containerapp hostname bind -n caefdtest001 -g rg-internalapp-dev-uks-001 --hostname a02.azurefd.net
The behavior of this command has been altered by the following extension: containerapp
Please specify at least one of parameters: --certificate and --environment

Specifying the environment leads to another different error:

michael_cameron [ ~ ]$ az containerapp hostname bind -n caefdtest001 -g rg-internalapp-dev-uks-001 --hostname a02.azurefd.net --environment cae-internal-dev-uks-001
The behavior of this command has been altered by the following extension: containerapp
Creating managed certificate 'mc-cae-internal-d-a02-azurefd-net-1605' for a02.azurefd.net.
It may take up to 20 minutes to create and issue a managed certificate.
Please specify the parameter: --validation-method

I cannot see anything in the updated documentation that describes what values the validation-method parameter accepts.

**Comment by Greedygre** [comment]
> --validation-method

The validation-method accpect `HTTP`, `CNAME` or `TXT`.

PS:
In azure-cli will be included from Azure CLI version: 2.62.0, Official Release: 07/02/2024 , PR: https://github.com/Azure/azure-cli/pull/29156 , no need to install extension. The doc in `az containerapp hostname bind -h` will also show the available vale for `-validation-method` from Azure CLI version: 2.62.0.

**Comment by MichaelCameronDHSC** [comment]
How do I force the use of private DNS?  There is CNAME record but not the public one

**Comment by Greedygre** [comment]
> How do I force the use of private DNS? There is CNAME record but not the public one

I don't know how to use private DNS, did you occur error with `--validation-method CNAME`?

**Comment by MichaelCameronDHSC** [comment]
Yes, the CNAME record that exists in private DNS cannot be found.  I'm following a guide to using internal container apps and exposing them via custom private links with front door so need to use private DNS but cannot bind the hostname either with cli or in the portal.

michael_cameron [ ~ ]$ az containerapp hostname bind -n caefdtest001 -g rg-internalapp-dev-uks-001 --hostname a02.azurefd.net --environment cae-internal-dev-uks-001  --validation-method CNAME 
The behavior of this command has been altered by the following extension: containerapp
Creating managed certificate 'mc-cae-internal-d-a02-azurefd-net-9665' for a02.azurefd.net.
It may take up to 20 minutes to create and issue a managed certificate.
(FailedCnameValidation) Not found CNAME of hostname 'a02.azurefd.net' directly pointing to a default hostname. Found CNAME record(s) of the hostname are .

**Comment by Greedygre** [comment]
Hi @MichaelCameronDHSC 
Can you use a Private key certificates?
 - use `az containerapp env certificate upload` to create a private key certificate in your environment
 - use `az containerapp hostname bind` to bind it to your containerapp

**Comment by MichaelCameronDHSC** [comment]
No

**Comment by tdaroly** [comment]
Hello @MichaelCameronDHSC ,

I see that this is a Consumption Environment with a VNet. Can you share your DNS settings of `a02.azurefd.net` as well ? 

I see from the custom-domain on the app `caefdtest001` that the custom domain you are trying to add is `a02.azurefd.net`. This looks like a Azure Front Door instance. Do you have a reference to your container app generated FQDN in the DNS settings ?
https://learn.microsoft.com/en-us/azure/container-apps/custom-domains-certificates
![image](https://github.com/Azure/azure-cli/assets/41846928/befebebd-a162-4dba-b683-a9170c4d8024)

Have you tried the following ?
https://learn.microsoft.com/en-us/azure/container-apps/networking?tabs=workload-profiles-env%2Cazure-cli#dns
![image](https://github.com/Azure/azure-cli/assets/41846928/07706490-0230-498c-970d-5e7808d5b835)

**Comment by MichaelCameronDHSC** [comment]
Hi, I was trying to follow this but find it confusing.

The heading states "If you plan to use VNET-scope ingress in an **internal** environment"
However the second sub-section says "If you plan to use custom-domains **and** are using an **external** Container Apps environment"

I'm not using an external CAE (nor would anyone if the first assertion is true so surely this never applies)

**Comment by MichaelCameronDHSC** [comment]
I'm trying to set up access via frontdoor and am also using MS authentication in my container app.  
The only need for a custom domain is to enable host name preservation to allow the app to operate as it should.  So, yes, I want to create a custom domain and have created a private DNS Zone to try and achieve that with an A record that points to the static IP.

I do not understand the assertion "If you are using an internal Container Apps Environment, there is no validation for the DNS binding, as the cluster can only be accesses from within the virtual network"
To create the binding appears to require validation.

What am I missing?

**Comment by Greedygre** [comment]
Hi @MichaelCameronDHSC 
Your environment is not internal. 
You can also check with command `az containerapp env show -n {name} -g {rg-name} --query "[].properties.vnetConfiguration.internal"`, the value is `false`.

**Comment by MichaelCameronDHSC** [comment]
The value is true (taking the extra []. out of the query):

michael_cameron [ ~ ]$ az containerapp env show -n cae-internal-dev-uks-001 -g rg-internalapp-dev-uks-001 --query "properties.vnetConfiguration.internal"
The behavior of this command has been altered by the following extension: containerapp
true

**Comment by tdaroly** [comment]
@MichaelCameronDHSC Can you add the app FQDN as a CNAME record in your DNS settings.

a02.azurefd.net **CNAME** caefdtest001.lemonground-3209f350.uksouth.azurecontainerapps.io

The error you are seeing `(FailedCnameValidation) Not found CNAME of hostname 'a02.azurefd.net' directly pointing to a default hostname. Found CNAME record(s) of the hostname are .` is due to DigiCert not able to find any CNAME's in your DNS settings. I did a quick DNS lookup on `a02.azurefd.net` and was not able to see any CNAME settings
<img width="867" alt="image" src="https://github.com/Azure/azure-cli/assets/41846928/5d744069-886c-4ced-a415-d90cf95dd696">

**Comment by tdaroly** [comment]
We also see that the env `cae-internal-dev-uks-001` is internal. One of the requirements for managed certs is having the container app accessible publicly.

https://learn.microsoft.com/en-us/azure/container-apps/custom-domains-managed-certificates?pivots=azure-portal
![image](https://github.com/Azure/azure-cli/assets/41846928/84789f93-9d5f-4dbf-8077-58a2c2f6bfa6)

**Comment by MichaelCameronDHSC** [comment]
Thanks for the comments.  I can add a CNAME to private DNS (which I have) but I don't have easy access to a signing authority in this environment so was intending to reply on a managed cert.  Obviously this presents a different problem.

Ultimately what I would like is an internal container app with VNET scope ingress which is exposed using a private link and Front door. I think that would be fine unless and until I enable authentication for the container app - dealing with host name preservation for the callback URLs then requires a custom domain aligned to frontdoor (unless you can suggest some other means to achieve this).

I still think there is an issue with the command output.
The warning implies that the cert is being created but can take some time, however. the subsequent error message doesn't say that the cert creation has failed, it just says a CNAME cannot be found.  To me that implies that the validation step has failed, I'm still expecting a cert is getting created (but could take 20 mins)

_It may take up to 20 minutes to create and issue a managed certificate.
(FailedCnameValidation) Not found CNAME of hostname 'a02.azurefd.net' directly pointing to a default hostname. Found CNAME record(s) of the hostname are ._
