### ISSUE TITLE
az monitor diagnostic-settings create will not accept same json as returned by show for 'logs'

### ISSUE THREAD

**Issue by nneul** [Azure/azure-cli#2913]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: script

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.3

**OS Version:** What OS and version are you using?  
Answer here: Ubuntu 16.04 x64

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

---

### Description

The input to logs option for monitor create won't accept the logs array as returned by 'az monitor diagnostics-settings show' - you have to strip out the 'retentionPolicy' elements. This seems incorrect. 

Example in my case:

```
  "logs": [
    {
      "category": "ApplicationGatewayAccessLog",
      "enabled": false,
      "retentionPolicy": {
        "days": 0,
        "enabled": false
      }
    },
    {
      "category": "ApplicationGatewayPerformanceLog",
      "enabled": false,
      "retentionPolicy": {
        "days": 0,
        "enabled": false
      }
    },
    {
      "category": "ApplicationGatewayFirewallLog",
      "enabled": true,
      "retentionPolicy": {
        "days": 0,
        "enabled": false
      }
    }
  ],
```

It fails with:

```
u'retentionPolicy'
Traceback (most recent call last):
  File "/users/nneul/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/users/nneul/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 201, in execute
    result = expanded_arg.func(params)
  File "/users/nneul/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 403, in _execute_command
    raise ex
KeyError: u'retentionPolicy'
```

**Comment by tjprescott** [comment]
@vishrutshah it looks like the UX here could use improvement.
1. Command insists on 'resource-id' when it should support names or IDs.
2. It really doesn't seem like "create" is the right verb here. If anything it seems more like a "configure" command.
3. The JSON dump doesn't seem necessary at all. It seems I should be able to simply specify the name, whether it is enabled or not, and a retention period (optional).

**Comment by nneul** [comment]
No disagreement with @tjprescott comments, my issue was more: If it's going to take json for the settings, it should at least accept the same json as input that is output by the same command.

**Comment by tjprescott** [comment]
@nneul agreed.

**Comment by vishrutshah** [comment]
@nneul Thanks for reporting this issue. Yes we agree that it should take the logs. 

I see that you mentioned that you have to stip out `retentionPolicy`. Could you please try keeping them but renaming it `retention_policy`. I believe that is the case for the issue. Let me know if that works or not.

Meanwhile, I am working on fixing the issues to take the same json as input. 👍 Thanks again for reporting the issue.

**Comment by nneul** [comment]
Yes, using retention_policy proceeds without error.

**Comment by vishrutshah** [comment]
@nneul Closing the bug as PR is merged in. Could please use the nightly tomorrow and let us know whether things are good on you end or not. Appreciate your help.

**Comment by nneul** [comment]
Confirmed that this is now working. Thank you!
