### ISSUE TITLE
azure cli via script failing on ubuntu

### ISSUE THREAD

**Issue by sunilemanjee** [Azure/azure-cli#29131]
### Describe the bug

using the instructions provided here https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=script and running `curl -sL https://aka.ms/InstallAzureCli | bash` 

get the following error
```
ubuntu@ip-xxxx:~$ curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
Hit:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu noble InRelease
Hit:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu noble-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu noble-security InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
apt-transport-https is already the newest version (2.7.14build2).
ca-certificates is already the newest version (20240203).
curl is already the newest version (8.5.0-2ubuntu10.1).
gnupg is already the newest version (2.4.4-2ubuntu17).
lsb-release is already the newest version (12.0-2).
0 upgraded, 0 newly installed, 0 to remove and 34 not upgraded.
curl: (28) Failed to connect to packages.microsoft.com port 443 after 134029 ms: Couldn't connect to server
gpg: no valid OpenPGP data found.
```
running on ubuntu: 24.10

### Related command

curl -sL https://aka.ms/InstallAzureCli | bash

### Errors

curl: (28) Failed to connect to packages.microsoft.com port 443 after 134029 ms: Couldn't connect to server
gpg: no valid OpenPGP data found.

### Issue script & Debug output

curl: (28) Failed to connect to packages.microsoft.com port 443 after 134029 ms: Couldn't connect to server
gpg: no valid OpenPGP data found.

### Expected behavior

Install of azure cli

### Environment Summary

not able to install azure cli

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by sunilemanjee** [comment]
Issue “magically resolved” after an hour or so of being down (end point).

Regards,

Sunile Manjee | Senior Principal Solutions Architect | 630-333-2433
*Azure Solutions Architect Expert Certified, Accreditation verified here
<https://tinyurl.com/3mtzu33t>*
*Azure Fundamentals Certified, Accreditation verified here
<https://tinyurl.com/bdte7p7v>*
Technical Enablement: ***@***.***
<https://tinyurl.com/ywxxt8te>

<https://www.elastic.co/>

**Comment by bebound** [comment]
There seems to be an issue in PMC at that time.
