### ISSUE TITLE
Add support for az network application-gateway waf-policy Bot 1.1 ruleset

### ISSUE THREAD

**Issue by Shawnli222** [Azure/azure-cli#29158]
### Describe the bug

Add support for az network application-gateway waf-policy Bot 1.1 ruleset

similar to this PR: https://github.com/Azure/azure-cli/issues/26888

### Related command

az network application-gateway waf-policy managed-rule rule-set update --policy-name <> --resource-group <> --type 'Microsoft_BotManagerRuleSet' --version '1.1'

az network application-gateway waf-policy managed-rule rule-set add --policy-name <> --resource-group <> --type 'Microsoft_BotManagerRuleSet' --version '1.1'

### Errors

Add 1.1 as an allowed input

### Issue script & Debug output

Add 1.1 as an allowed input

### Expected behavior

Add 1.1 as an allowed input

### Environment Summary

na

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by Shawnli222** [comment]
Hi@yonzhan , want to check on the progess of this, this is requirement for our GA

**Comment by Shawnli222** [comment]
Hi @yonzhan just checking on the progress here, we need to test it soon in cli

**Comment by cxznmhdcxz** [comment]
Hi @Shawnli222 , added 1.1 as allowed value but got this error when testing:
``` 
ApplicationGatewayFirewallUnknownRuleSetVersion
RuleSetVersion '1.1' is unsupported for specified RuleSetType 'Microsoft_BotManagerRuleSet' for Application Gateway Firewall
```
