### ISSUE TITLE
New az login support for --subscription

### ISSUE THREAD

**Issue by blueboxes** [Azure/azure-cli#29167]
**Related command**
az login --tenant XXXXX 

When using the [new login experience ](https://techcommunity.microsoft.com/t5/microsoft-developer-community/new-login-experience-for-azure-subscriptions-with-az-login/ba-p/4157184)

**Is your feature request related to a problem? Please describe.**
I can turn off the new login however I want to leave it on. In Powershell scripts, though I don't want the user to pick from a long list, I want to set it as part of the CLI.

**Describe the solution you'd like**
az login --tenant XXXXX --subscription XXXX

**Describe alternatives you've considered**
I tried setting the default sub first (which errors as not logged in) and also with  --allow-no-subscriptions but the list is still shown.

**Additional context**
None

**Comment by jiasli** [comment]
Supporting `--subscription` in `az login` is tracked by https://github.com/Azure/azure-cli/issues/14933.

`--allow-no-subscriptions` is a no-op when there are indeed accessible subscriptions. See more details at https://github.com/Azure/azure-cli/issues/13285.
