### ISSUE TITLE
Can't specify image tag in compose when using `az containerapp compose create`

### ISSUE THREAD

**Issue by amitkma** [Azure/azure-cli#29166]
### Describe the bug

We are using the docker-compose file for container app creation using the command: `az containerapp compose create`. We have specified a tag in `image` attribute of service, we get the error: ```(InvalidImageString) Image name 'dev:latest:20240614142829041798' is invalid.```

I believe it is happening because [here](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/containerapp/_up_utils.py#L598) a timestamp is added as image tag even if there is already a tag. 

### Related command

`az containerapp compose create -g dms-rg-development --environment pr-test-env --compose-file-path "compose.yml" ----transport-mapping "db=tcp" --transport-mapping "redis=tcp" --transport-mapping "azurite=http"`

### Errors

(InvalidInputValue) Some of the properties of 'runRequest' are invalid.. InnerErrors: DockerBuildRequest:Image name 'dev:latest:20240614142829041798' is invalid. 
The acceptable patterns are 'repository' or 'repository:tag'.The repository and tag names follow the standardized docker repository and tag naming conventions. Tag templates are supported within '{{' and '}}'. 
Please refer to docs for more information on using image name and tag:  https://aka.ms/az/acr/az-acr-build
Code: InvalidInputValue
Message: Some of the properties of 'runRequest' are invalid.. InnerErrors: DockerBuildRequest:Image name 'dev:latest:20240614142829041798' is invalid. 
The acceptable patterns are 'repository' or 'repository:tag'.The repository and tag names follow the standardized docker repository and tag naming conventions. Tag templates are supported within '{{' and '}}'. 
Please refer to docs for more information on using image name and tag:  https://aka.ms/az/acr/az-acr-build
Target: request
Exception Details:      (InvalidImageString) Image name 'dev:latest:20240614142829041798' is invalid. 
        The acceptable patterns are 'repository' or 'repository:tag'.The repository and tag names follow the standardized docker repository and tag naming conventions. Tag templates are supported within '{{' and '}}'. 
        Please refer to docs for more information on using image name and tag:  https://aka.ms/az/acr/az-acr-build
        Code: InvalidImageString
        Message: Image name 'dev:latest:20240614142829041798' is invalid. 
        The acceptable patterns are 'repository' or 'repository:tag'.The repository and tag names follow the standardized docker repository and tag naming conventions. Tag templates are supported within '{{' and '}}'. 
        Please refer to docs for more information on using image name and tag:  https://aka.ms/az/acr/az-acr-build
        Target: DockerBuildRequest

### Issue script & Debug output

(InvalidInputValue) Some of the properties of 'runRequest' are invalid.. InnerErrors: DockerBuildRequest:Image name 'dev:latest:20240614142829041798' is invalid. 
The acceptable patterns are 'repository' or 'repository:tag'.The repository and tag names follow the standardized docker repository and tag naming conventions. Tag templates are supported within '{{' and '}}'. 
Please refer to docs for more information on using image name and tag:  https://aka.ms/az/acr/az-acr-build
Code: InvalidInputValue
Message: Some of the properties of 'runRequest' are invalid.. InnerErrors: DockerBuildRequest:Image name 'dev:latest:20240614142829041798' is invalid. 
The acceptable patterns are 'repository' or 'repository:tag'.The repository and tag names follow the standardized docker repository and tag naming conventions. Tag templates are supported within '{{' and '}}'. 
Please refer to docs for more information on using image name and tag:  https://aka.ms/az/acr/az-acr-build
Target: request
Exception Details:      (InvalidImageString) Image name 'dev:latest:20240614142829041798' is invalid. 
        The acceptable patterns are 'repository' or 'repository:tag'.The repository and tag names follow the standardized docker repository and tag naming conventions. Tag templates are supported within '{{' and '}}'. 
        Please refer to docs for more information on using image name and tag:  https://aka.ms/az/acr/az-acr-build
        Code: InvalidImageString
        Message: Image name 'dev:latest:20240614142829041798' is invalid. 
        The acceptable patterns are 'repository' or 'repository:tag'.The repository and tag names follow the standardized docker repository and tag naming conventions. Tag templates are supported within '{{' and '}}'. 
        Please refer to docs for more information on using image name and tag:  https://aka.ms/az/acr/az-acr-build
        Target: DockerBuildRequest

### Expected behavior

When an image tag is specified, no timestamp tag should be appended.

### Environment Summary

azure-cli                         2.60.0 *

core                              2.60.0 *
telemetry                          1.1.0

Extensions:
account                            0.2.5
containerapp                      0.3.50
rdbms-connect                      1.0.5

Dependencies:
msal                              1.28.0
azure-mgmt-resource             23.1.0b2

Python location '/opt/homebrew/Cellar/azure-cli/2.60.0/libexec/bin/python'
Extensions directory '/Users/workspace/.azure/cliextensions'

Python (Darwin) 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by Greedygre** [comment]
Hi @amitkma 
The compose will build the image with a tag using current time. You can remove the `:latest` from the image name you specify.

> Creating a tag for the image using the current time to avoid overwriting customer's existing images

Thanks

**Comment by amitkma** [comment]
Hey @Greedygre, thanks for the response. But sometimes we want to tag the image with a version and that's not possible. Is there a way to create image tag like `dev-backend:v2.30.0`

**Comment by Greedygre** [comment]
> Hey @Greedygre, thanks for the response. But sometimes we want to tag the image with a version and that's not possible. Is there a way to create image tag like `dev-backend:v2.30.0`

Currently it doesn't support to create image with a specify tag.

**Comment by kamalsivalingam** [comment]
@Greedygre Is there any update on allowing to specifying a tag? We would like to use a version/tag other than latest

**Comment by Greedygre** [comment]
> @Greedygre Is there any update on allowing to specify a tag? We would like to use a version/tag other than latest

Hi @kamalsivalingam 

The PR for this issue has been merged, and it will be ready in  Azure CLI version: 2.65.0, Official Release: 10/08/2024

**Comment by kamalsivalingam** [comment]
@Greedygre Awesome, Thanks!

**Comment by amitkma** [comment]
> > @Greedygre Is there any update on allowing to specify a tag? We would like to use a version/tag other than latest
> 
> Hi @kamalsivalingam @amitkma
> 
> The PR for this issue has been merged, and it will be ready in Azure CLI version: 2.65.0, Official Release: 10/08/2024

Hey @Greedygre, Thank you very much.
