### ISSUE TITLE
BYOIP v4 Parent/Child for Custom IP Prefix

### ISSUE THREAD

**Issue by brianlehr** [Azure/azure-cli#29164]
In Azure today, Custom IPv6 Prefixes all use parent/child functionality.  We are now allowing Custom IPv4 Prefixes to use this same functionality, and we need the custom IP prefixes to be specified as "parent" or "child".

In PowerShell, the parameter used to denote the custom IP prefix as parent during creation is "-IsParent"

****************
$prefix =@{
    Name = 'myCustomGlobalPrefix'
    ResourceGroupName = 'myResourceGroup'
    Location = 'SomeRegion'
    CIDR = '1.2.3.0/24'
}
$myCustomIPGlobalPrefix = New-AzCustomIPPrefix @prefix **-IsParent**
****************

So for CLI, we would want something like:
az network custom-ip prefix create --name myCustomGlobalPrefix --resource-group myResourceGroup --location someregion --cidr '1.2.3.0/24' **--isparent**

There is also a command used to label a custom IP prefix is a "child" range during creation, but this should already exist in CLI (--cip-prefix-parent).

Swagger is here: [https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2023-11-01/customIpPrefix.json]( https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2023-11-01/customIpPrefix.json)

Please let me know if there are questions about this

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by brianlehr** [comment]
@yonzhan Please note this is linked to the Security Sprint as it is required for BYOIP to go GA in Airgapped Cloud, which is tied in with Wave 1 Security Sprint to ensure all 1P IPs are service tagged.  Please prioritize.

**Comment by brianlehr** [comment]
@yonzhan are there any additional questions about this work?  When can your team create this on priority since it is related to Security Sprint?

**Comment by yonzhan** [comment]
@necusjz FYI
