### ISSUE TITLE
[DNS] zone import should strip trailing .@ from relative record names

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#2917]
The following is a legitimate DNS record from a BIND zone file:

_sip._tls.@	3600 	IN	SRV	100	1	443	sipdir.online.lync.com

Note the '.@' in the record name, which currently causes import to fail (Bad Request).

Where a record name ends in .@, we should strip it off (and then apply the current value of $ORIGIN).

**Comment by yonzhan** [comment]
@MyronFanQiu  add to S162.

**Comment by haroldrandom** [comment]
Could you provide some related file contents? It would be helpful.
