### ISSUE TITLE
Add support for the new property on the service endpoint configuration

### ISSUE THREAD

**Issue by harics24** [Azure/azure-cli#29184]
**Related command**
az network vnet subnet update -n s1 --vnet-name vNet1 --service-endpoints Microsoft.Storage,Microsoft.Sql

**Is your feature request related to a problem? Please describe.**
Adding a new property to specify the networkIdentifier in the form of a public IP address.
https://microsoft.sharepoint.com/:w:/t/Aznet/EZyqWxvEt1JEoJlsxf6WjaUBHmjOr3mCdBcLrMpBjn8J7w?e=Evot8t

**Describe the solution you'd like**
az network vnet subnet update -n s1 --vnet-name vNet1 --service-endpoints { Microsoft.Storage, <PIP1ArmID> },{Microsoft.Sql, <Pip2ArmId>}

**Describe alternatives you've considered**

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
