### ISSUE TITLE
multiple account

### ISSUE THREAD

**Issue by Ranjith-Sigmoid** [Azure/azure-cli#29199]
### Describe the bug

Hi, when I login to azure cli is says Found multiple accounts with the same username 'ranjith@sigmoidanalytics.com'.

How to rectify this

### Related command

Found multiple accounts with the same username 'ranjith@sigmoidanalytics.com':

### Errors

Found multiple accounts with the same username 'ranjith@sigmoidanalytics.com':

### Issue script & Debug output

NA

### Expected behavior

Login to Azure cli 

### Environment Summary

Found multiple accounts with the same username 'ranjith@sigmoidanalytics.com':

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
Duplicate of #20168
