### ISSUE TITLE
Unable to set upgrade policy to automatic during VMSS creation

### ISSUE THREAD

**Issue by mimckitt** [Azure/azure-cli#29191]
### Describe the bug

creating a new scale set using the following command is accepted but the upgrade policy mode is not actually set to automatic. It remains set to manual. 

az vmss create \
  --resource-group myResourceGroup \
  --name myScaleSet \
  --image Ubuntu2204 \
  --orchestration-mode Flexible \
  --upgrade-policy-mode Automatic \
  --admin-username azureuser \
  --generate-ssh-keys

### Related command

az vmss create

### Errors

No errors, upgrade policy is set to manual instead of automatic as it should be. 

### Issue script & Debug output

Logs are very long. I can send offline if needed. 

### Expected behavior

The upgrade policy of the scale set should be set to Automatic. 

### Environment Summary

Using Azure Cloud Shell

### Additional context

Note, updating the upgrade policy to automatic works fine. 

az vmss update \
    --name myScaleSet \
    --resource-group myResourceGroup \
    --set upgradePolicy.mode=Automatic

Seeing similar issue with create VMSS for PowerShell: https://github.com/Azure/azure-powershell/issues/25301

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
