### ISSUE TITLE
Azure Dogfood Subscription Request

### ISSUE THREAD

**Issue by h-sadeghpour** [Azure/azure-cli#29217]
**Related command**
I was checking Azure Dogfood tenant and was trying to work with some of Preview features and Services and was wondering how it's possible to get a subscription in there?

**Describe the solution you'd like**
Want to work with Preview Features

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yonzhan** [comment]
Not related to Azure CLI commands
