### ISSUE TITLE
Add support for raw ARM API requests

### ISSUE THREAD

**Issue by snobu** [Azure/azure-cli#2921]
Any plans to add a raw request mode to **az**?

Something like:
```
$ az raw get https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/redis/providers/Microsoft.Cache/Redis/{RedisCacheName}?api-version=2016-04-01
```

Basically what [ARMClient ](https://github.com/projectkudu/armclient) is doing. There's an opportunity to merge functionality into a single CLI tool.

**Comment by yugangw-msft** [comment]
#2607 should cover this.
