### ISSUE TITLE
az login for service principal with certificate is failing

### ISSUE THREAD

**Issue by paresh-borkar** [Azure/azure-cli#29216]
### Describe the bug

Here are the steps to reproduce this issue:
1. Create new service principal. I used the command below:

paresh@localhost:~$ az ad sp create-for-rbac -n "http://pb-test-sp-cert.amolthreatwatch.onmicrosoft.com" --role contributor --create-cert
Creating a role assignment under the scope of "/subscriptions/418abed9-b812-40d4-9825-72ee6f3d846b"
  Retrying role assignment creation: 1/36
Please copy /home/paresh/tmpegdt55f6.pem to a safe place. When run 'az login' provide the file path to the --password argument
{
  "appId": "be56d598-552d-4152-9e7a-85657ad612aa",
  "displayName": "pb-test-sp-cert.amolthreatwatch.onmicrosoft.com",
  "fileWithCertAndPrivateKey": "/home/paresh/tmpegdt55f6.pem",
  "name": "http://pb-test-sp-cert.amolthreatwatch.onmicrosoft.com",
  "password": null,
  "tenant": "660199a4-dd4e-44ff-8978-68ce1f0a3494"
}

2. I confirmed that the generated private key file contained private key and certificate. Rename file to azure_sp_key_cert.pem

3. az login command fails as below:

paresh@localhost:~$ az login --service-principal -u be56d598-552d-4152-9e7a-85657ad612aa -p ./azure_sp_key_cert.pem -t 660199a4-dd4e-44ff-8978-68ce1f0a3494
Error:Invalid Certificate: Expected Start of Certificate to be '-----BEGIN RSA PRIVATE KEY-----'

### Related command

paresh@localhost:~$ az login --service-principal -u be56d598-552d-4152-9e7a-85657ad612aa -p ./azure_sp_key_cert.pem -t 660199a4-dd4e-44ff-8978-68ce1f0a3494
Error:Invalid Certificate: Expected Start of Certificate to be '-----BEGIN RSA PRIVATE KEY-----'

### Errors

Error:Invalid Certificate: Expected Start of Certificate to be '-----BEGIN RSA PRIVATE KEY-----'

### Issue script & Debug output

paresh@localhost:~$ az login --service-principal -u be56d598-552d-4152-9e7a-85657ad612aa -p ./azure_sp_key_cert.pem -t 660199a4-dd4e-44ff-8978-68ce1f0a3494 --debug
Command arguments: ['login', '--service-principal', '-u', 'be56d598-552d-4152-9e7a-85657ad612aa', '-p', './azure_sp_key_cert.pem', '-t', '660199a4-dd4e-44ff-8978-68ce1f0a3494', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f5a4b5f9820>, <function OutputProducer.on_global_arguments at 0x7f5a4b527550>, <function CLIQuery.on_global_arguments at 0x7f5a4b547310>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
Loaded module 'acr' in 0.006 seconds.
Loaded module 'acs' in 0.006 seconds.
Loaded module 'advisor' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.005 seconds.
Loaded module 'apim' in 0.002 seconds.
Loaded module 'appconfig' in 0.003 seconds.
Loaded module 'appservice' in 0.020 seconds.
Loaded module 'backup' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.007 seconds.
Loaded module 'batchai' in 0.004 seconds.
Loaded module 'billing' in 0.002 seconds.
Loaded module 'botservice' in 0.004 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.003 seconds.
Loaded module 'cloud' in 0.002 seconds.
Loaded module 'cognitiveservices' in 0.002 seconds.
Loaded module 'configure' in 0.001 seconds.
Loaded module 'consumption' in 0.002 seconds.
Loaded module 'container' in 0.002 seconds.
Loaded module 'cosmosdb' in 0.005 seconds.
Loaded module 'deploymentmanager' in 0.003 seconds.
Loaded module 'dla' in 0.005 seconds.
Loaded module 'dls' in 0.003 seconds.
Loaded module 'dms' in 0.002 seconds.
Loaded module 'eventgrid' in 0.003 seconds.
Loaded module 'eventhubs' in 0.003 seconds.
Loaded module 'extension' in 0.001 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.001 seconds.
Loaded module 'hdinsight' in 0.002 seconds.
Loaded module 'interactive' in 0.000 seconds.
Loaded module 'iot' in 0.004 seconds.
Loaded module 'iotcentral' in 0.001 seconds.
Loaded module 'keyvault' in 0.004 seconds.
Loaded module 'kusto' in 0.002 seconds.
Loaded module 'lab' in 0.003 seconds.
Loaded module 'managedservices' in 0.002 seconds.
Loaded module 'maps' in 0.001 seconds.
Loaded module 'monitor' in 0.006 seconds.
Loaded module 'natgateway' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'netappfiles' in 0.003 seconds.
Loaded module 'network' in 0.021 seconds.
Loaded module 'policyinsights' in 0.002 seconds.
Loaded module 'privatedns' in 0.004 seconds.
Loaded module 'profile' in 0.002 seconds.
Loaded module 'rdbms' in 0.006 seconds.
Loaded module 'redis' in 0.002 seconds.
Loaded module 'relay' in 0.003 seconds.
Loaded module 'reservations' in 0.002 seconds.
Loaded module 'resource' in 0.006 seconds.
Loaded module 'role' in 0.004 seconds.
Loaded module 'search' in 0.002 seconds.
Loaded module 'security' in 0.003 seconds.
Loaded module 'servicebus' in 0.005 seconds.
Loaded module 'servicefabric' in 0.003 seconds.
Loaded module 'signalr' in 0.002 seconds.
Loaded module 'sql' in 0.007 seconds.
Loaded module 'sqlvm' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.023 seconds.
Loaded module 'vm' in 0.013 seconds.
Loaded all modules in 0.245 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: '/home/paresh/.azure/cliextensions'
Found 1 extensions: ['azure-devops']
Extensions directory: '/home/paresh/.azure/cliextensions'
Extension compatibility result: is_compatible=True cli_core_version=2.0.81 min_required=2.0.69 max_required=None
Extensions directory: '/home/paresh/.azure/cliextensions'
Loaded extension 'azure-devops' in 0.021 seconds.
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f5a4afacdc0>]
az_command_data_logger : command args: login --service-principal -u {} -p {} -t {} --debug
metadata file logging enabled - writing logs to '/home/paresh/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f5a4afc7d30>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f5a4af7adc0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f5a4af7aee0>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7f5a492dfd30>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f5a4b5275e0>, <function CLIQuery.handle_query_parameter at 0x7f5a4b5473a0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f5a4af7ae50>, <function handler at 0x7f5a4919dc10>, <function DevCommandsLoader.post_parse_args at 0x7f5a4898e670>]
attempting to read file /home/paresh/.azure/accessTokens.json as utf-8-sig
adal-python : 29c29e9d-fa56-4c2c-8cad-4b7e231fee80 - Authority:Performing instance discovery: ...
adal-python : 29c29e9d-fa56-4c2c-8cad-4b7e231fee80 - Authority:Performing static instance discovery
adal-python : 29c29e9d-fa56-4c2c-8cad-4b7e231fee80 - Authority:Authority validated via static instance discovery
adal-python : 29c29e9d-fa56-4c2c-8cad-4b7e231fee80 - TokenRequest:Getting a token via certificate.
adal-python : 29c29e9d-fa56-4c2c-8cad-4b7e231fee80 - SelfSignedJwt:Creating self signed JWT header. x5t: KUZmYc3lOsYUAa1v3_h5Db0gerk=, x5c: None
adal-python : 29c29e9d-fa56-4c2c-8cad-4b7e231fee80 - SelfSignedJwt:Creating self signed JWT payload. Expires: 2024-06-20 10:19:54.332751 NotBefore: 2024-06-20 10:09:54.332751
cli.azure.cli.core.util : Error:Invalid Certificate: Expected Start of Certificate to be '-----BEGIN RSA PRIVATE KEY-----'
Error:Invalid Certificate: Expected Start of Certificate to be '-----BEGIN RSA PRIVATE KEY-----'
az_command_data_logger : exit code: 1
telemetry.save : Save telemetry record of length 2487 in cache
telemetry.check : Negative: The /home/paresh/.azure/telemetry.txt was modified at 2024-06-20 10:03:19.721483, which in less than 600.000000 s
command ran in 0.324 seconds.

### Expected behavior

az login for service principal should have worked

### Environment Summary

Linux-5.4.0-88-generic-x86_64-with-glibc2.29
Python 3.8.10
Shell: bash

azure-cli 2.0.81

Extensions:
azure-devops 0.17.0

paresh@localhost:~$ az --version
azure-cli                         2.0.81

core                              2.0.81
telemetry                          1.0.4

Extensions:
azure-devops                      0.17.0

Python location '/usr/bin/python3'
Extensions directory '/home/paresh/.azure/cliextensions'

Python (Linux) 3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
