### ISSUE TITLE
JSONC is not parsed successfully by json.loads in Python2.

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#2924]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: dev_setup.py

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.2

**OS Version:** What OS and version are you using?  
Answer here: macOS Sierra

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash, cmd.exe

**Python Version:** 2.7.11

---

### Description

Running the example in the example:
```
az keyvault certificate create --vault-name myvault -n cert1 -p "$(az keyvault certificate get-default-policy)"
```

results in the following error on bash (Python 2.7.11):
```
invalid syntax: "attributes": {
```

Alternate ways of accomplishing this (for example piping) generate the same error.

If I run this on Windows with cmd.exe it works in Python 3.  In Python 2 I get an error:
```
Property policy.x509_props has invalid value. Invalid X.500 distinguished name
Property policy.key_props has invalid value. Invalid Kty UlNB
Property policy.secret_props has invalid value. ContentType is invalid
```

**Comment by tjprescott** [comment]
@devigned I thought this may have been related to my PR #2705, but even when I roll back to just after you merged the original change, I get an even worse error.

**Comment by tjprescott** [comment]
Looks like there's something super wonky about the way Python 2 handles this (surprise, surprise, I know)

**Comment by derekbekoe** [comment]
What's your output type? Looks like it could be `jsonc`

**Comment by tjprescott** [comment]
Oh yes, my output type is always JSONC.  In that case, perhaps the "get-default-policy" command should ALWAYS output JSON (since no other format makes sense) regardless of the output format set by the user. 

This could easily be accomplished by a transform on the command that prints the result to STDOUT as JSON and then returns None (so that the nothing is passed to the generic CLI output handler).

**Comment by devigned** [comment]
@tjprescott and @derekbekoe I think this is not just a `get-default-policy` issue. It's a more generic issue with accepting JSONC input for **any command** accepting JSON.

It might be better to change the issue to reflect the deeper problem.

**Comment by derekbekoe** [comment]
@tjprescott I believe this is by-design? There are many tools that will not accept `jsonc` as valid JSON. 
Okay to close?

**Comment by tjprescott** [comment]
I think a better solution would be to force the command to output JSON.  Outputting JSONC seems reasonable except that it breaks on Python2 (for piping scenarios) and outputting table or TSV makes absolutely no sense.

**Comment by MikkelHegn** [comment]
I know this is an older issue, but I spent a few hours today on this, as it cascades to using e.g. jq top parse output from az commands.

Relevant versions:
![image](https://user-images.githubusercontent.com/12242001/57445326-6215ee80-7252-11e9-8a87-1625e10eee80.png)

**Comment by yonzhan** [comment]
add to S165.

**Comment by jiasli** [comment]
Corresponding changes is put into Knack https://github.com/microsoft/knack/pull/173
