### ISSUE TITLE
Azure CLI Feature: Show OS Version, along with az --version

### ISSUE THREAD

**Issue by johnpapa** [Azure/azure-cli#2925]
To make it easier to add issues here in github, add the OS and other important info to the displayed output when we run `az --version`

Here is my current output

```
$ az --version
azure-cli (2.0.3)

acr (2.0.1)
acs (2.0.3)
appservice (0.1.3)
batch (2.0.1)
cloud (2.0.1)
component (2.0.1)
configure (2.0.3)
container (0.1.3)
core (2.0.3)
documentdb (0.1.3)
feedback (2.0.1)
find (0.0.2)
iot (0.1.3)
keyvault (2.0.1)
lab (0.0.2)
monitor (0.0.2)
network (2.0.3)
nspkg (2.0.0)
profile (2.0.3)
redis (0.2.0)
resource (2.0.3)
role (2.0.2)
sql (2.0.1)
storage (2.0.3)
vm (2.0.3)

Python (Darwin) 2.7.13 (default, Apr  4 2017, 08:47:57) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

**Comment by spboyer** [comment]
The dotnet cli has an `--info` which provides the information which we could add similar output to this.

```console
dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```

**Comment by tjprescott** [comment]
Why Node version?  Azure CLI 2.0 doesn't require Node in any way.

**Comment by yonzhan** [comment]
add to S165.

**Comment by jiasli** [comment]
Please check https://github.com/Azure/azure-cli/issues/8102 which is similar and let us know if you are still facing this issue.

**Comment by jiasli** [comment]
Also, `az --version` involves a network connection to check pypi for the latest version: https://github.com/Azure/azure-cli/blob/4d684d2678a6c3a39e0ed9918cd210c6c161939a/src/azure-cli-core/azure/cli/core/util.py#L106

We have introduced a new command [`az version`](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-version) which only runs locally and returns the result in JSON by default.

**Comment by jiasli** [comment]
For Python applications, it is not a convention to display system information. 

```
>python --version
Python 3.8.1

>pip --version
pip 20.0.2 from d:\cli\env38\lib\site-packages\pip (python 3.8)

>pytest --version
This is pytest version 4.4.2, imported from d:\cli\env38\lib\site-packages\pytest.py
```

To open an issue, you may use `az feedback` which automatically generates the issue template with system information:

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.8.1
Shell: cmd.exe
