### ISSUE TITLE
Install script does not work on elementaryOS

### ISSUE THREAD

**Issue by spotlesscoder** [Azure/azure-cli#29264]
### Describe the bug

`curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash` does not work on elementaryOS

Probably the distro cannot be determined.
It should be resolved to Ubuntu 22.04 for elementaryOS 7.1:

`cat /etc/lsb-releae`
```
DISTRIB_ID=elementary
DISTRIB_RELEASE=7.1
DISTRIB_CODENAME=horus
DISTRIB_DESCRIPTION="elementary OS 7.1 Horus"
```

### Related command

See above

### Errors

```
Unable to find a package for your system. Please check if an existing package in https://packages.microsoft.com/repos/azure-cli/dists/ can be used in your system and install with the dist name: 'curl -sL https://aka.ms/InstallAzureCLIDeb | sudo DIST_CODE=<dist_code_name> bash'
```

### Issue script & Debug output

see above

### Expected behavior

Install works

### Environment Summary

Latest

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
elementaryOS has its own code name.

As shown in the error message, please try this:
`curl -sL https://aka.ms/InstallAzureCLIDeb | sudo DIST_CODE=jammy bash`

**Comment by spotlesscoder** [comment]
This is not a very user-friendly solution
It should work without extra effort
