### ISSUE TITLE
Azure CLI Feature: Make aliases for common commands like "create"

### ISSUE THREAD

**Issue by johnpapa** [Azure/azure-cli#2927]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.3)

**OS Version:** What OS and version are you using?  
Answer here: macOS 10.12.3

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash on macOS

---

### Description

We often need to `create` a resource using the CLI. Aliases are super common with many CLI's. Some of our Azure CLI flags have aliases, but our commands should benefit from this too. Consider how often we create something ... we currently type:

`az group create -n PapaResourceGroup -l "East US"`

but we could type

`az group c -n PapaResourceGroup -l "East US"`

Now consider 3 commands in a row ...

```
az group create -n PapaResourceGroup -l eastus

az storage account create -n papastorage -g PapaResourceGroup --sku Standard_LRS -l eastus

az functionapp create -n papafunction -g PapaResourceGroup -s papastorage -c eastus
```

now see this ...

```
az group c -n PapaResourceGroup -l eastus

az storage account c -n papastorage -g PapaResourceGroup --sku Standard_LRS -l eastus

az functionapp c -n papafunction -g PapaResourceGroup -s papastorage -c eastus
```

I also think it would be great to have aliases for other commands, but the quick win would be "create" since we use it in so many places.

cc // @SyntaxC4

**Comment by chewong** [comment]
Hey @johnpapa,

I am very excited to let you know that the alias extension is just released. You can check out https://github.com/chewong/azure-cli-alias-extension/blob/dev/doc/az-alias-blog-post.md for more detail.
