### ISSUE TITLE
Azure CLI Feature: Use default location and sku when specifying a resource group

### ISSUE THREAD

**Issue by johnpapa** [Azure/azure-cli#2928]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.3)

**OS Version:** What OS and version are you using?  
Answer here: macOS 10.12.3

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash on macOS

---

### Description

It would be great if when we create a storage account (or other resources) that if we specify a resource group, we can default to use its location. Otherwise we do this ...
```
az group create -n PapaResourceGroup -l eastus

az storage account create -n papastorage -g PapaResourceGroup --sku Standard_LRS -l eastus
```

Notice we type the location twice. If I omit the location in the second command, it fails. We also should be able to default the sku. A quicker way would look like this ...

```
az group create -n PapaResourceGroup -l eastus

az storage account create -n papastorage -g PapaResourceGroup 

```

cc // @SyntaxC4

**Comment by tjprescott** [comment]
In general, most commands do just this. There are some older ones that don't. However, you can also set a default location, in which case that will be used and you won't incur the REST overhead of looking up the location from the resource-group.

**Comment by johnpapa** [comment]
very true. good point.

**Comment by tjprescott** [comment]
That being said--I'm doing the work to add this defaulting logic to storage account create. If you see other instances where location isn't defaulted, please open new issues against them.
