### ISSUE TITLE
`docker pull` fails with `certificate signed by unknown authority`

### ISSUE THREAD

**Issue by omni-htg** [Azure/azure-cli#29298]
### Describe the bug

Hey there, Azure CLI team!

Recently while trying to pull an image from our Container Registry, I get the error:
```
error pulling image configuration: download failed after attempts=6: tls: failed to verify certificate: x509: certificate signed by unknown authority
```
After doing:
```
az login
az acr login -n <acr name>
```

Which is weird, as I have configured this same flow myself and know that it used to work not that long ago (can't remember detailed timelines).

Is there something I'm missing here, or that I could try?

Thanks a ton!

### Related command

az acr login
docker pull

### Errors

error pulling image configuration: download failed after attempts=6: tls: failed to verify certificate: x509: certificate signed by unknown authority

### Issue script & Debug output

Using default tag: latest
latest: Pulling from <image>
04e7578caeaa: Retrying in 1 second
f58cc51ecd71: Retrying in 1 second
3493f2c78126: Retrying in 1 second
587db8524f02: Waiting
dcbac13f0ca9: Waiting
6a511d56e0ad: Waiting
4f4fb700ef54: Waiting
8995cd2a782d: Waiting
0dafcc22f686: Waiting

### Expected behavior

Once logged in through the Azure CLI and then acr login, docker should be able to pull without issue.

### Environment Summary

azure-cli                         2.61.0

core                              2.61.0
telemetry                          1.1.0

Extensions:
cosmosdb-preview                   1.0.1
interactive                        0.5.3

Dependencies:
msal                              1.28.0
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\<USER>\.azure\cliextensions'

Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by omni-htg** [comment]
Hello team, it is the next day.
Tried the same flow from the top and now it succeeds!
Apologies if the issue was from something else.
