### ISSUE TITLE
`get-access-token` not always returning token for specified audience from within Cloud Shell 

### ISSUE THREAD

**Issue by Korving-F** [Azure/azure-cli#29313]
### Describe the bug

The `--resource`-flag behaves unexpectedly when generating tokens from within a Cloud Shell.

1. Try generating a token from a cloud-shell using `az account get-access-token --resource https://management.azure.com --tenant $TENANT_ID`
2. Receive an error that TENANT_ID shouldn't be specified from within Cloud Shells.
3. Generate the token from a cloud shell using `az account get-access-token --resource https://management.azure.com`
4. Analyze the generated token in https://jwt.ms to see that the scope was changed to 'https://management.core.windows.net/'

When issuing the command from step 1 (explicitly setting the tenant id) while in a normal terminal, no error is presented and the generated token is scoped correctly.

**NB!** This does not seem to affect all other specified resources. For example while using `https://graph.microsoft.com` the token is generated correctly.

### Related command

az account get-access-token

### Errors

> "Tenant shouldn't be specified for Cloud Shell account"

Link to place in code where the error seems to originate from: [L398](https://github.com/Azure/azure-cli/blob/add4b2cc69df23d4e664d79b6aec3e036b2d6e2c/src/azure-cli-core/azure/cli/core/_profile.py#L398)

### Issue script & Debug output
NULL

### Expected behavior

When explicitly specifying a resource while generating a token, I expect the token to be scoped accordingly.

### Environment Summary

azure-cli 2.61.0
core 2.61.0
telemetry 1.1.0

Extensions:
account 0.2.5

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
`https://management.core.windows.net/` and `https://management.azure.com` are the same resource app.

I guess Cloud Shell's token cache treats them as the same resource too and that's why `az account get-access-token --resource https://management.core.windows.net/` and `az account get-access-token --resource https://management.azure.com/` return the same access token.
