### ISSUE TITLE
MSI support for az storage fs directory

### ISSUE THREAD

**Issue by aj9411** [Azure/azure-cli#29322]
**Related command**
[az storage fs directory](https://learn.microsoft.com/en-us/cli/azure/storage/fs/directory?view=azure-cli-latest#az-storage-fs-directory-download)

**Is your feature request related to a problem? Please describe.**
Problem: security requirements are causing us to switch from using connection string to using user delegated sas token, which intermittently fails, retrying with a new user delegated sas token helps, sometimes.

**Describe the solution you'd like**
It would be good to have support for MSI with --auth-mode login, like other az storage commands, az storage fs directory lacks this support

**Describe alternatives you've considered**
Sadly the flaky user delegated sas token is the only way I have.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
