### ISSUE TITLE
Default behaviour of 'az role assignment delete' is to delete ALL role assignments on the subscription. This is wildly dangerous and breaks everything

### ISSUE THREAD

**Issue by dbsanfte** [Azure/azure-cli#2933]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
azure-cli (2.0.2)
acr (2.0.0)
acs (2.0.2)
appservice (0.1.2)
batch (2.0.0)
cloud (2.0.0)
component (2.0.0)
configure (2.0.2)
container (0.1.2)
core (2.0.2)
documentdb (0.1.2)
feedback (2.0.0)
find (0.0.1b1)
iot (0.1.2)
keyvault (2.0.0)
lab (0.0.1)
monitor (0.0.1)
network (2.0.2)
nspkg (2.0.0)
profile (2.0.2)
redis (0.1.1b3)
resource (2.0.2)
role (2.0.1)
sql (2.0.0)
storage (2.0.2)
vm (2.0.2)

**OS Version:** What OS and version are you using?  
Answer here: Windows 10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

---

### Description
The default behaviour of 'az role assignment delete' is to delete all role assignments on the subscription. No other command has such a wildly dangerous default parameterless behaviour. I typed this and have completely wiped out everyone's access to my subscription. :D Luckily it was in dev.

When 'az role assignment delete' is entered, it should prompt for a parameter. The current default behaviour is nuts.

**Comment by yugangw-msft** [comment]
Agreed, we should prompt

**Comment by tjprescott** [comment]
You could also make it opt-in to the dangerous case by making the parameter accept a sentinel value (for example --scope *)

**Comment by rzal** [comment]
This is very dangerous, but there's hope if you ever get in the same situation; please read this article: https://docs.microsoft.com/en-us/azure/role-based-access-control/elevate-access-global-admin

**Comment by cherwin** [comment]
@yugangw-msft How about we just show the usage? I've just got bitten by this issue as well.

**Comment by yugangw-msft** [comment]
@cherwin, I will address this soon, agreed we should do something here.
