### ISSUE TITLE
Authorization Failed

### ISSUE THREAD

**Issue by graccelle** [Azure/azure-cli#29334]
### Describe the bug

Trying to run my python script, trying to access the azure OpenAI service using my API credentials, but keep getting the "authorization failed" error message in the attached screenshot.
![Screenshot 2024-07-08 161944](https://github.com/Azure/azure-cli/assets/54447737/39f3dcc4-3298-4917-a0b1-ae2ff6be98a4)

### Related command

azure openai (reference attached screenshot)
![Screenshot 2024-07-08 161944](https://github.com/Azure/azure-cli/assets/54447737/77bc8439-cdf5-4f98-a299-80caa28b6d31)

### Errors

azure.core.exceptions.HttpResponseError: () Authorization failed.
Code:
Message: Authorization failed.

### Issue script & Debug output

![Screenshot 2024-07-08 161944](https://github.com/Azure/azure-cli/assets/54447737/5cffa509-28a2-4bbd-af79-e152a93c868a)

### Expected behavior

Given the successful access to the chatbot local host (http://localhost:7860/), once i send a prompt, I should get a response to my question (like you would in ChatGPT). See attached screenshot of the error message i get instead on the user interface.
![Screenshot 2024-07-08 162737](https://github.com/Azure/azure-cli/assets/54447737/dc25d71b-e0ad-4009-8127-8855ef12a4d5)

### Environment Summary

Name: azure-core
Version: 1.30.2
Summary: Microsoft Azure Core Library for Python
Home-page: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/core/azure-core
Author: Microsoft Corporation
Author-email: azpysdkhelp@microsoft.com
License: MIT License
Location: c:\users\t-grbabalola\appdata\local\anaconda3\envs\chatosp\lib\site-packages
Requires: requests, six, typing-extensions
Required-by: azure-identity, azure-search-documents, msrest

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yonzhan** [comment]
Please open this issue in Python SDK repo

**Comment by graccelle** [comment]
How am I supposed to open this issue in Python SDK repo @yonzhan?

**Comment by jiasli** [comment]
This is not related to Azure CLI. I guess the code you are running doesn't set up credential correctly for the underlying Azure Python SDK.

Is your `main.py` from https://github.com/Azure-Samples/openai? If so, I would recommend opening an issue there, or contacting Azure OpenAI customer support.
