### ISSUE TITLE
Tab completion not working 

### ISSUE THREAD

**Issue by spboyer** [Azure/azure-cli#2934]
`azure-cli (2.0.3+1.dev20170419)`

No tab completion in iTerm or default terminal on macOS Sierra 10.12.4

cc:/ @SyntaxC4

**Comment by derekbekoe** [comment]
@spboyer looks like this is the nightly build so it was installed with pip.
Have you run `source az.completion.sh`?

**Comment by marb21** [comment]
I got the same problem with 10.13.3. Did you find any solution?. Thanks!

**Comment by derekbekoe** [comment]
@marb21 It looks like you're using the previous Azure CLI at https://github.com/Azure/azure-xplat-cli

**Comment by marb21** [comment]
Thanks for your response.
No, I'm not. 

azure-cli (2.0.28)
