### ISSUE TITLE
Azure Database for PostgreSQL Flexible Server - Allow enabling PostgreSQL authentication for existing servers

### ISSUE THREAD

**Issue by danvalero** [Azure/azure-cli#29346]
**Related command**
```
az postgres flexible-server update
```

**Is your feature request related to a problem? Please describe.**
It is not possible to enable PostgreSQL Authentication using az postgres flexible-server update
PostgreSQL Authentication can only be enabled using CLI on creation time. 

If "az postgres flexible-server update  --password-auth Enabled" is used, no option to set the username and password, and get error:

>_(EngineCredentialsNotProvided) The admin credentials are required for creating admin role while enabling Password Authentication and must be provided.
Code: EngineCredentialsNotProvided
Message: The admin credentials are required for creating admin role while enabling Password Authentication and must be provided._

I need to use the portal to make then change (not programmatically) or "az rest" which adds complexity

**Describe the solution you'd like**

I want to be able to enable PostgreSQL authentication suing CLi in a simple way using "az postgres flexible-server update" by adding parameter [--admin-user] and use in conjunction with  [--admin-password]

**Describe alternatives you've considered**
N/A 

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by danvalero** [comment]
Hi @yonzhan 
FYI. I am a MSFT. Technical Advisor for the Microsoft CSS Azure Database for PostgreSQL support team. I am opening this request in behave of a customer that had issued to do it himself.

**Comment by nachoalonsoportillo** [comment]
@danvalero Thanks for creating this issue. I've triaged it already and created a backlog item to support that scenario in a future version of Azure CLI. While we fix this, users will have to continue using the `az rest` alternative as you suggested.

**Comment by nachoalonsoportillo** [comment]
Fixed by https://github.com/Azure/azure-cli/pull/30200.
