### ISSUE TITLE
Feature: List command or az defaults

### ISSUE THREAD

**Issue by spboyer** [Azure/azure-cli#2935]
Add a `list` command for `az configure` to list the defaults.

```bash
az configure list
```
or

```bash
az configure defaults list
```

This eliminates the need the prompts if we just want to see the list of defaults

**Comment by mboersma** [comment]
👍 to this idea. A user on the #sig-azure channel on the Kubernetes slack was asking for the same thing yesterday.

**Comment by EamonKeane** [comment]
Thanks @mboersma . The use case is to initialise a script similar to the below.

```bash
ACCOUNT=$(gcloud config get-value core/account)
PROJECT=$(gcloud config get-value core/project)
REGION=$(gcloud config get-value compute/region)
GCE_ZONE=$(gcloud config get-value compute/zone)
```

**Comment by yonzhan** [comment]
add to S165.

**Comment by jiasli** [comment]
Thanks for the feedback. This feature has been implemented in https://github.com/Azure/azure-cli/pull/9210: now available as `az configure --list-defaults`. Run `az configure -h` for more details.
