### ISSUE TITLE
Internal Feedback | az sig create | Soft-delete should not be appearing here

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#29358]
### Describe the bug

This GitHub issue is being moved from MicrosoftDocs/azure-docs-cli [#4447](https://github.com/MicrosoftDocs/azure-docs-cli/issues/4447) as it pertains to autogenerated reference content.

**********************************
**Type of issue**
Other (describe below)

**Feedback**
--soft-delete should not yet being appearing as customers need to register for the feature and it is not yet in preview.

**Page URL**
https://learn.microsoft.com/en-us/cli/azure/sig?view=azure-cli-latest#az-sig-create

**Content source URL**
https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/sig.yml
**********************************

### Related command

az sig create

### Errors

n/a

### Issue script & Debug output

n/a

### Expected behavior

n/a

### Environment Summary

n/a

### Additional context

n/a

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by clmendes-MSFT** [comment]
Thank you @yonzhan please feel free to reach out.
