### ISSUE TITLE
Impossible to update network application-gateway listener customErrorConfigurations

### ISSUE THREAD

**Issue by danyric** [Azure/azure-cli#29351]
### Describe the bug

Hello
While trying to set a customErrorConfigurations to network application-gateway listener.
First run the command:
`
az network application-gateway http-listener update   -g $gr_ppd   --gateway-name $appgw_ppd   --name appGatewayHttpListener  --set customErrorConfigurations=[]
`

> {
  "customErrorConfigurations": [],
   ................
  "type": "Microsoft.Network/applicationGateways/httpListeners"
}

An then try to run still have an error .

### Related command

 az network application-gateway http-listener update   -g $gr_ppd   --gateway-name $appgw_ppd   --name appGatewayHttpListener   --add customErrorConfigurations[0].customErrorPageUrl=https://xxxxxx.windows.net/error-502.html customErrorConfigurations[0].statusCode=HttpStatus502

### Errors

Couldn't find 'customErrorPageUrl=https://xxxxx' in 'customErrorConfigurations[0].customErrorPageUrl=https://xxxxx.windows.net/error-502'. Available options: ['custom_error_page_url', 'status_code']

### Issue script & Debug output

Couldn't find 'customErrorPageUrl=https://xxxxx' in 'customErrorConfigurations[0].customErrorPageUrl=https://xxxxx.windows.net/error-502'. Available options: ['custom_error_page_url', 'status_code']

### Expected behavior

customErrorConfigurations set and visible when issuing az cli show command and when using the az portal

### Environment Summary

azure-cli                         2.62.0

core                              2.62.0
telemetry                          1.1.0

Extensions:
bastion                            1.0.1

Dependencies:
msal                              1.28.1
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\edanede\.azure\cliextensions'

Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
network

**Comment by ReaNAiveD** [comment]
@danyric Based on the error message, could you please try changing `customErrorConfigurations[0].customErrorPageUrl` to `customErrorConfigurations[0].custom_error_page_url` and changing `customErrorConfigurations[0].statusCode` to `customErrorConfigurations[0].status_code`?

**Comment by ReaNAiveD** [comment]
We are closing this issue due to a lack of response. If you have any further questions or updates, please feel free to reopen the issue. Thank you!
