### ISSUE TITLE
az storage blob sync does not yet support --auth-mode login 

### ISSUE THREAD

**Issue by F-JJonas** [Azure/azure-cli#29365]
**Related command**
az storage blob sync

**Is your feature request related to a problem? Please describe.**
--auth-mode login is not supported but disabling local auth is required as part of SFI wave 1 requirements

**Describe the solution you'd like**
support for MSI authentication with --auth-mode login 

**Describe alternatives you've considered**
az storage azcopy blob sync
This solution does not support --exclude-pattern or --exclude-path options.

**Additional context**

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
