### ISSUE TITLE
azure/CLI@v2 with azcliversion: 2.62.0 get an error "ERROR: Invalid base64-encoded string: number of data characters (29) cannot be 1 more than a multiple of 4"

### ISSUE THREAD

**Issue by zaaraungkam** [Azure/azure-cli#29361]
### Describe the bug

Warning : Warning: Unable to fetch all az cli versions, please report it as an issue on https://github.com/Azure/CLI/issues. Output: ***

ERROR: Invalid base64-encoded string: number of data characters (29) cannot be 1 more than a multiple of 4

### Related command

            - name: Inline script upload blob
              uses: azure/CLI@v2
              with:
                  azcliversion: 2.62.0
                  inlineScript: |
                      az storage blob upload \
                      --container-name "xxx" \
                      --file "xxx" \
                      --name ${{ env.BlobName }} \
                      --account-name ${{env.storage_account_name}} \
                      --account-key ${{ secrets.mrmawebstatichostingdev_access_key }}

### Errors

ERROR: Invalid base64-encoded string: number of data characters (29) cannot be 1 more than a multiple of 4

### Issue script & Debug output

Starting script execution via docker image mcr.microsoft.com/azure-cli:2.62.0
ERROR: Invalid base64-encoded string: number of data characters (29) cannot be 1 more than a multiple of 4
Error: Error: az cli script failed.
cleaning up container...
MICROSOFT_AZURE_CLI_1720679723394_CONTAINER
Error: az cli script failed.

### Expected behavior

can upload a file to blob storage

### Environment Summary

azure cli 2.62.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zaaraungkam** [comment]
this one running on GitHub action

**Comment by zaaraungkam** [comment]
completed with argument --sas-token
