### ISSUE TITLE
Azure CLI Feature: az resource list should indicate that a functionapp is a Function App

### ISSUE THREAD

**Issue by johnpapa** [Azure/azure-cli#2938]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.3)

**OS Version:** What OS and version are you using?  
Answer here: macOS 10.12.3

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash on macOS

---

### Description

Function Apps should somehow indicate that they are a functionapp. The type is "Microsoft.Web/site", which is fine, but we should also show that it is a function app

```
$ az resource list
Name                    ResourceGroup             Location    Type                               Status
----------------------  ------------------------  ----------  ---------------------------------  --------
papafowlerfuncapp       PapaFowlerResourceGroup   eastus      Microsoft.Web/sites
```

**Comment by tjprescott** [comment]
`resource list` is generic and its table format needs to be compatible with all resource types. 

There is a property on a Microsoft.Web/sites that distinguishes between them--kind--which does show if you output JSON.

For these reasons we would not add kind to the table output for resource list.

**Comment by johnpapa** [comment]
Sorry, not understanding. Is there a way to show this?

**Comment by tjprescott** [comment]
Because 90% of resources don't have this property. The default table format for resource list was selected to the subset of properties that ALL resources share, because, if you just show the resources in a resource group (for example) you will see a mix of many different resource types.

You can specify a custom table format if you want to show this:
`resource list --resource-type Microsoft.Web/sites -otable --query "[].{Name:name,ResourceGroup:resourceGroup,Kind:kind}"`

**Comment by johnpapa** [comment]
Understood. Thanks for helping clarifying the reasoning.

The use case is trying to get a view of all resources, but identifying which type they all are. It seems there is no way to do that today without a lot of flags. I would hope that would be easier in the future to identify what is a function vs a regular app service.

I would request you keep this open for future consideration to help make this use case easier to use.
