### ISSUE TITLE
Release docker images for Azure Linux 3.0

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#29383]
Azure Linux 3.0 is now preview. Its docker image is available at `azurelinuxpreview.azurecr.io/public/azurelinux/base/core:3.0`.

Azure CLI should release docker images for Azure Linux 3.0 and publish them to Microsoft Artifact Registry (MAR) https://mcr.microsoft.com/ .

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
Official image is released: `mcr.microsoft.com/azurelinux/base/core:3.0`

**Comment by bebound** [comment]
We've release azure linux 3 image from 2.65.0 https://mcr.microsoft.com/en-us/artifact/mar/azure-cli/tags
