### ISSUE TITLE
Release RPM packages for Azure Linux 3.0

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#29382]
Azure Linux 3.0 is now preview. Its docker image is available at `azurelinuxpreview.azurecr.io/public/azurelinux/base/core:3.0`.

Azure CLI should release RPM packages for Azure Linux 3.0 and publish them to PMC https://packages.microsoft.com/.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
Azure Linux 3.0's default Python is 3.12

```
> docker run --rm -t azurelinuxpreview.azurecr.io/public/azurelinux/base/core:3.0

# tdnf install python

# python3 -V
Python 3.12.0
```

This increases the priority of https://github.com/Azure/azure-cli/issues/27673.
