### ISSUE TITLE
storage queue metadata does not return the message count header

### ISSUE THREAD

**Issue by seguler** [Azure/azure-cli#2940]
### Environment summary

**Install Method:** PIP

**CLI Version:** 2.0.2 

**OS Version:** Linux Microsoft Creators

**Shell Type:** Bash 

---

### Description
Get storage queue metadata does not show the message count header: https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/get-queue-metadata

x-ms-approximate-messages-count:int-value

@troydai

**Comment by seguler** [comment]
Works on PSH:
 Get-AzureStorageQueue -Name testqueue


CloudQueue              : Microsoft.WindowsAzure.Storage.Queue.CloudQueue
Uri                     : https://account.queue.core.windows.net/testqueue
ApproximateMessageCount : 2
EncodeMessage           : True
Context                 : Microsoft.WindowsAzure.Commands.Common.Storage.AzureStorageContext
Name                    : testqueue

**Comment by williexu** [comment]
The CLI command simply outputs the metadata to the user, as the command suggests. 
We have not received requests for the approximate message count, however this can be done through logging if needed to not break users.
Closing this issue for now, will add the additional info if requested by users.

**Comment by kevinblumenfeld** [comment]
**OS**: Windows 10
**Postman**: v7.1.1
**Powershell**: 5.1, 6.2.0
**doc.microsoft.com**: https://docs.microsoft.com/en-us/rest/api/storageservices/get-queue-metadata
**Expected response header**: `x-ms-approximate-messages-count:int-value` | The approximate number of messages in the queue. This number is not lower than the actual number of messages in the queue, but could be higher

@williexu I am noticing the same (similar) issue with the API when using REST calls via Postman and Invoke-WebRequest.  Nothing seems to be returned at all including, `x-ms-approximate-messages-count`.  I receive a 200 response with no data even though there are non-expired messages in multiple queues.

`https://<storageaccount>.queue.core.windows.net/<queue>?comp=metadata`

Any guidance would be greatly appreciated.
Thank you for your time.
@seguler @troydai @williexu

**Comment by cutty201** [comment]
YOu guys are awful --- return the Approximate Message count --- you are so full of yourselves --- it comes in when you make the call and you are so terrible even with "VERBOSE" on you will not show me those headers --- for what purpose? you guys are terribly shameful --- your Azure Cli has the data and you wont release it to me --- this is really awful --- if Computers had rights this would definitely be a violation ---

**Comment by guss77** [comment]
> The CLI command simply outputs the metadata to the user, as the command suggests.
> We have not received requests for the approximate message count, however this can be done through logging if needed to not break users.
> Closing this issue for now, will add the additional info if requested by users.

Please add the additional info - we, the users, request it.
