### ISSUE TITLE
az container create returns internal server error

### ISSUE THREAD

**Issue by YeabTilahun** [Azure/azure-cli#29438]
### Describe the bug

When I tried to create a container instance I got an internal error.
The command I used and the output is provided

### Related command

```az container create -g demovs -n demoaci --image mcr.microsoft.com/azuredocs/aci-helloworld --dns-name-label demoaci --ports 80```

### Errors

```(InternalServerError) Encountered an internal server error. The tracking activity id is 'e8b6f2d9-2eeb-4020-bec9-0dd00d319ca5', correlation id is 'bcc31d76-9341-44fc-a437-6fd5593d1cfc'.
Code: InternalServerError
Message: Encountered an internal server error. The tracking activity id is 'e8b6f2d9-2eeb-4020-bec9-0dd00d319ca5', correlation id is 'bcc31d76-9341-44fc-a437-6fd5593d1cfc'.```

### Issue script & Debug output

```

cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '466'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'c5dc7ad1-4825-11ef-bfcb-988d469bd539'
cli.azure.cli.core.sdk.policies:     'CommandName': 'container create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g -n --image --dns-name-label --ports --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.62.0 (MSI) azsdk-python-core/1.28.0 Python/3.11.8 (Windows-10-10.0.22631-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"properties": {"containers": [{"name": "demoaci", "properties": {"image": "mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine", "ports": [{"protocol": "TCP", "port": 80}], "resources": {"requests": {"memoryInGB": 1.5, "cpu": 1.0}}}}], "restartPolicy": "Always", "ipAddress": {"ports": [{"protocol": "TCP", "port": 80}], "type": "Public", "dnsNameLabel": "demoaci", "autoGeneratedDomainNameLabelScope": "Unsecure"}, "osType": "Linux"}, "location": "eastus", "tags": {}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/17334ce3-4359-45e5-9056-fa93b27cd019/resourceGroups/demovs/providers/Microsoft.ContainerInstance/containerGroups/demoaci?api-version=2023-05-01 HTTP/1.1" 500 216
cli.azure.cli.core.sdk.policies: Response status: 500
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '216'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-resource-requests-pt5m': '99'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-resource-requests-pt1h': '299'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'eastus:d72cc120-0e6d-4502-a040-6ae6cf5d1b6d'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '199'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-global-writes': '2999'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '8a2dde22-6357-4df3-922d-f0f87cdff1e6'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHAFRICANORTH:20240722T122742Z:8a2dde22-6357-4df3-922d-f0f87cdff1e6'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: 9C9289ACFB354366A8214B5861BF4CDC Ref B: MRS211050618045 Ref C: 2024-07-22T12:27:38Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 22 Jul 2024 12:27:42 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"InternalServerError","message":"Encountered an internal server error. The tracking activity id is 'd72cc120-0e6d-4502-a040-6ae6cf5d1b6d', correlation id is '8a2dde22-6357-4df3-922d-f0f87cdff1e6'."}}
cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.broker: [MSAL:0001]        INFO    LogTelemetryData:422    Printing Telemetry for Correlation ID: be8aa95c-62c6-41f9-96d0-9fd09904ebd5
msal.broker: [MSAL:0001]        INFO    LogTelemetryData:430    Key: start_time, Value: 2024-07-22T12:27:42.000Z
msal.broker: [MSAL:0001]        INFO    LogTelemetryData:430    Key: api_name, Value: ReadAccountById
msal.broker: [MSAL:0001]        INFO    LogTelemetryData:430    Key: was_request_throttled, Value: false
msal.broker: [MSAL:0001]        INFO    LogTelemetryData:430    Key: authority_type, Value: Unknown
msal.broker: [MSAL:0001]        INFO    LogTelemetryData:430    Key: msal_version, Value: 1.1.0+local
msal.broker: [MSAL:0001]        INFO    LogTelemetryData:430    Key: correlation_id, Value: be8aa95c-62c6-41f9-96d0-9fd09904ebd5
msal.broker: [MSAL:0001]        INFO    LogTelemetryData:430    Key: broker_app_used, Value: false
msal.broker: [MSAL:0001]        INFO    LogTelemetryData:430    Key: stop_time, Value: 2024-07-22T12:27:42.000Z
msal.broker: [MSAL:0001]        INFO    LogTelemetryData:430    Key: msalruntime_version, Value: 0.16.2
msal.broker: [MSAL:0001]        INFO    LogTelemetryData:430    Key: is_successful, Value: true
msal.broker: [MSAL:0001]        INFO    LogTelemetryData:430    Key: request_duration, Value: 0
msal.broker: [MSAL:0002]        WARNING SetAuthorityUri:78      Initializing authority from URI 'https://login.microsoftonline.com/2be31c19-a23c-472f-97da-1f5ae228d76b' without authority type, defaulting to MsSts
msal.broker: [MSAL:0002]        INFO    SetCorrelationId:258    Set correlation ID: be8aa95c-62c6-41f9-96d0-9fd09904ebd5
msal.broker: [MSAL:0002]        INFO    EnqueueBackgroundRequest:1000   The original authority is 'https://login.microsoftonline.com/2be31c19-a23c-472f-97da-1f5ae228d76b'
msal.broker: [MSAL:0002]        INFO    ModifyAndValidateAuthParameters:243     Authority Realm: 2be31c19-a23c-472f-97da-1f5ae228d76b
msal.broker: [MSAL:0002]        WARNING TryEnqueueMsaDeviceCredentialAcquisitionAndContinue:1052        MsaDeviceOperationProvider is not available. Not attempting to register the device.
msal.broker: [MSAL:0003]        INFO    StorageTokenResponse:84 StorageTokenResponse account constructor invoked. This is only expected in Runtime flows
msal.broker: [MSAL:0003]        INFO    IsAccessTokenValid:2658 The access token is expired
msal.broker: [MSAL:0003]        WARNING StorageTokenResponse:15 No credentials found in the cache
msal.broker: [MSAL:0003]        WARNING GetPlatformPropertiesFromStorage:2013   No account found in cache.
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:422    Printing Telemetry for Correlation ID: be8aa95c-62c6-41f9-96d0-9fd09904ebd5
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: start_time, Value: 2024-07-22T12:27:42.000Z
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: api_name, Value: AcquireTokenSilently
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: was_request_throttled, Value: false
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: authority_type, Value: MSA
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: access_token_expiry_time, Value: 2024-07-22T13:27:45.000Z
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: read_token, Value: ID|EAT
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: msal_version, Value: 1.1.0+local
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: client_id, Value: 04b07795-8ddb-461a-bbee-02f9e1bf7b46
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: correlation_id, Value: be8aa95c-62c6-41f9-96d0-9fd09904ebd5
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: storage_delete, Value: DAT
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: broker_app_used, Value: true
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: stop_time, Value: 2024-07-22T12:27:43.000Z
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: msalruntime_version, Value: 0.16.2
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: original_authority, Value: https://login.microsoftonline.com/2be31c19-a23c-472f-97da-1f5ae228d76b
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: request_eligible_for_broker, Value: true
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: additional_query_parameters_count, Value: 0
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: storage_read, Value: DAC|DAT|DID|DAMD|DAC
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: delete_token, Value: AT
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: is_successful, Value: true
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: wam_telemetry, Value: {"x_ms_clitelem":"1,0,0,4589794.0362,","ui_visible":false,"tenant_id":"2be31c19-a23c-472f-97da-1f5ae228d76b","scope":"https://management.core.windows.net//.default offline_access openid profile","redirect_uri":"ms-appx-web://Microsoft.AAD.BrokerPlugin/04b07795-8ddb-461a-bbee-02f9e1bf7b46","provider_id":"https://login.windows.net","idp":"live.com","http_status":200,"http_event_count":1,"http_content_type":"application/json; charset=utf-8","http_content_size":7311,"device_join":"not_joined","correlation_id":"{be8aa95c-62c6-41f9-96d0-9fd09904ebd5}","client_id":"04b07795-8ddb-461a-bbee-02f9e1bf7b46","cache_event_count":0,"broker_version":"10.0.22621.3672","authority":"https://login.microsoftonline.com/2be31c19-a23c-472f-97da-1f5ae228d76b","api_error_code":0,"account_join_on_start":"not_joined","account_join_on_end":"not_joined","account_id":"c8211da7-970f-4057-b371-e53b3d56c573","silent_code":0,"silent_bi_sub_code":0,"silent_message":"","silent_status":0,"is_cached":0}
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: auth_flow, Value: Broker
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: tenant_id, Value: 2be31c19-a23c-472f-97da-1f5ae228d76b
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: write_token, Value: AT|ID
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: storage_write, Value: DAT|DID|DAC
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: authorization_type, Value: WindowsIntegratedAuth
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:430    Key: request_duration, Value: 1400
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:435    Printing Execution Flow:
msal.broker: [MSAL:0003]        INFO    LogTelemetryData:443    {"t":"4s7uc","tid":2,"ts":0,"l":2},{"t":"4sufd","tid":2,"ts":1,"s":2,"l":2},{"t":"4swgg","tid":2,"ts":1,"s":1,"l":2},{"t":"4swgf","tid":2,"ts":1,"s":1,"l":2},{"t":"4swgi","tid":3,"ts":1,"s":1,"l":2},{"t":"8b2yn","tid":3,"ts":1,"l":2},{"t":"8dqkx","tid":3,"ts":1,"l":2},{"t":"8dqik","tid":3,"ts":1,"l":2},{"t":"4q2di","tid":3,"ts":1,"l":2},{"t":"4qnng","tid":3,"ts":1,"l":2,"a":2,"ie":0},{"t":"4qnnf","tid":3,"ts":2,"l":2,"a":2,"ie":1},{"t":"8dqit","tid":3,"ts":2,"l":2},{"t":"8b2ht","tid":3,"ts":3,"l":2},{"t":"4qnno","tid":3,"ts":3,"l":2,"a":2,"ie":0},{"t":"4qnnn","tid":3,"ts":23,"l":2,"a":2,"ie":1},{"t":"4qnnk","tid":3,"ts":24,"l":2,"a":3,"ie":0},{"t":"4qnnj","tid":3,"ts":26,"l":2,"a":4,"ie":1},{"t":"4qwi1","tid":3,"ts":27,"l":2},{"t":"4qnna","tid":3,"ts":27,"l":2,"a":2,"ie":0},{"t":"4qnm9","tid":3,"ts":27,"l":2,"a":2,"ie":1},{"t":"8dqip","tid":3,"ts":28,"l":2},{"t":"4qnno","tid":3,"ts":28,"l":2,"a":2,"ie":0},{"t":"4qnnn","tid":3,"ts":28,"l":2,"a":2,"ie":1},{"t":"8b2hu","tid":3,"ts":28,"l":2},{"t":"5b8fg","tid":3,"ts":31,"l":2},{"t":"8dqk0","tid":3,"ts":31,"l":2},{"t":"4qnng","tid":3,"ts":31,"l":2,"a":2,"ie":0},{"t":"4qnnf","tid":3,"ts":32,"l":2,"a":2,"ie":1},{"t":"8dqjd","tid":3,"ts":32,"l":2},{"t":"694nj","tid":3,"ts":32,"l":2,"a":10,"ie":0},{"t":"4vw1f","tid":3,"ts":32,"l":2},{"t":"4wqnh","tid":3,"ts":33,"l":2},{"t":"4vw1c","tid":3,"ts":42,"l":2},{"t":"4vw1b","tid":3,"ts":42,"l":2},{"t":"4wqnk","tid":3,"ts":42,"l":2},{"t":"6omfm","tid":3,"ts":48,"l":2},{"t":"4vw1a","tid":3,"ts":48,"l":2},{"t":"4wqnf","tid":3,"ts":48,"l":2},{"t":"4wqm5","tid":3,"ts":64,"l":2},{"t":"4wqm6","tid":3,"ts":64,"l":2},{"t":"4u9jc","tid":3,"ts":1378,"l":2},{"t":"8dql1","tid":3,"ts":1378,"l":2},{"t":"4qopb","tid":3,"ts":1378,"l":2},{"t":"58yep","tid":3,"ts":1379,"l":2},{"t":"694nk","tid":3,"ts":1379,"l":2,"a":10,"ie":1},{"t":"8dqk1","tid":3,"ts":1379,"l":2},{"t":"8dqlh","tid":3,"ts":1379,"l":2},{"t":"8dqli","tid":3,"ts":1379,"l":2},{"t":"8dqln","tid":3,"ts":1379,"l":2},{"t":"4qnnm","tid":3,"ts":1379,"l":2,"a":3,"ie":0},{"t":"4qnnl","tid":3,"ts":1389,"l":2,"a":3,"ie":1},{"t":"4zbmt","tid":3,"ts":1389,"l":2},{"t":"4zbmu","tid":3,"ts":1389,"l":2},{"t":"4qnng","tid":3,"ts":1389,"l":2,"a":2,"ie":0},{"t":"4qnnf","tid":3,"ts":1390,"l":2,"a":2,"ie":1},{"t":"4qnne","tid":3,"ts":1390,"l":2,"a":3,"ie":0},{"t":"4qnnd","tid":3,"ts":1391,"l":2,"a":3,"ie":1},{"t":"6xuag","tid":3,"ts":1398,"l":2}
msal.token_cache: event={
    "_account_id": "c8211da7-970f-4057-b371-e53b3d56c573",
    "client_id": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
    "data": {},
    "environment": "login.microsoftonline.com",
    "grant_type": "broker",
    "response": {
        "_account_id": "c8211da7-970f-4057-b371-e53b3d56c573",
        "_msalruntime_telemetry": {
            "DATA LIMITED": "Full MSALRuntime telemetry not yet implemented",
            "api_name": "AcquireTokenSilently",
            "broker_app_used": "true",
            "client_id": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
            "correlation_id": "be8aa95c-62c6-41f9-96d0-9fd09904ebd5",
            "is_successful": "true",
            "msal_version": "1.1.0+local",
            "msalruntime_version": "0.16.2"
        },
        "access_token": "********",
        "client_info": "eyJ1aWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtOWNlOS05MjExYzNhZmYzMjciLCJ1dGlkIjoiOTE4ODA0MGQtNmM2Ny00YzViLWIxMTItMzZhMzA0YjY2ZGFkIn0",
        "expires_in": 3602,
        "id_token": "********",
        "id_token_claims": "********",
        "scope": "https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default",
        "token_type": "bearer"
    },
    "scope": [
        "https://management.core.windows.net//user_impersonation",
        "https://management.core.windows.net//.default"
    ],
    "token_endpoint": "https://login.microsoftonline.com/2be31c19-a23c-472f-97da-1f5ae228d76b/oauth2/v2.0/token"
}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/17334ce3-4359-45e5-9056-fa93b27cd019/resourceGroups/demovs/providers/Microsoft.ContainerInstance/containerGroups/demoaci?api-version=2023-05-01'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '466'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': 'c5dc7ad1-4825-11ef-bfcb-988d469bd539'
cli.azure.cli.core.sdk.policies:     'CommandName': 'container create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '-g -n --image --dns-name-label --ports --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.62.0 (MSI) azsdk-python-core/1.28.0 Python/3.11.8 (Windows-10-10.0.22631-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"properties": {"containers": [{"name": "demoaci", "properties": {"image": "mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine", "ports": [{"protocol": "TCP", "port": 80}], "resources": {"requests": {"memoryInGB": 1.5, "cpu": 1.0}}}}], "restartPolicy": "Always", "ipAddress": {"ports": [{"protocol": "TCP", "port": 80}], "type": "Public", "dnsNameLabel": "demoaci", "autoGeneratedDomainNameLabelScope": "Unsecure"}, "osType": "Linux"}, "location": "eastus", "tags": {}}
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/17334ce3-4359-45e5-9056-fa93b27cd019/resourceGroups/demovs/providers/Microsoft.ContainerInstance/containerGroups/demoaci?api-version=2023-05-01 HTTP/1.1" 500 216
cli.azure.cli.core.sdk.policies: Response status: 500
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '216'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-resource-requests-pt5m': '99'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-resource-requests-pt1h': '298'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'eastus:9a161666-952b-4a78-9060-7cfb2b842c45'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '199'
cli.azure.cli.core.sdk.policies:     'x-ms-failure-cause': 'service'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-global-writes': '2999'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '63857adf-c13f-41b2-962c-863dd5d04b2d'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'SOUTHAFRICANORTH:20240722T122748Z:63857adf-c13f-41b2-962c-863dd5d04b2d'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: 1624180FEABB44A4B214417340B5668C Ref B: MRS211050618045 Ref C: 2024-07-22T12:27:44Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 22 Jul 2024 12:27:48 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"error":{"code":"InternalServerError","message":"Encountered an internal server error. The tracking activity id is '9a161666-952b-4a78-9060-7cfb2b842c45', correlation id is '63857adf-c13f-41b2-962c-863dd5d04b2d'."}}
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/17334ce3-4359-45e5-9056-fa93b27cd019/resourceGroups/demovs/providers/Microsoft.ContainerInstance/containerGroups/demoaci?api-version=2023-05-01'

cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 664, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 701, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 334, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/container/custom.py", line 269, in create_container
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 710, in sdk_no_wait
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/containerinstance/operations/_container_groups_operations.py", line 798, in begin_create_or_update
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/containerinstance/operations/_container_groups_operations.py", line 660, in _create_or_update_initial
azure.core.exceptions.HttpResponseError: (InternalServerError) Encountered an internal server error. The tracking activity id is 'faa8389b-fb0d-480b-b7d8-8b9b049b1b68', correlation id is '3b55160e-90b4-4fe0-8f95-018d7d8ac425'.
Code: InternalServerError
Message: Encountered an internal server error. The tracking activity id is 'faa8389b-fb0d-480b-b7d8-8b9b049b1b68', correlation id is '3b55160e-90b4-4fe0-8f95-018d7d8ac425'.

cli.azure.cli.core.azclierror: (InternalServerError) Encountered an internal server error. The tracking activity id is 'faa8389b-fb0d-480b-b7d8-8b9b049b1b68', correlation id is '3b55160e-90b4-4fe0-8f95-018d7d8ac425'.
Code: InternalServerError
Message: Encountered an internal server error. The tracking activity id is 'faa8389b-fb0d-480b-b7d8-8b9b049b1b68', correlation id is '3b55160e-90b4-4fe0-8f95-018d7d8ac425'.
az_command_data_logger: (InternalServerError) Encountered an internal server error. The tracking activity id is 'faa8389b-fb0d-480b-b7d8-8b9b049b1b68', correlation id is '3b55160e-90b4-4fe0-8f95-018d7d8ac425'.
Code: InternalServerError
Message: Encountered an internal server error. The tracking activity id is 'faa8389b-fb0d-480b-b7d8-8b9b049b1b68', correlation id is '3b55160e-90b4-4fe0-8f95-018d7d8ac425'.
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x000001FBC5C6C400>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 31.408 seconds (init: 0.369, invoke: 31.039)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 4592 in cache
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\yeabs\.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.
```

### Expected behavior

Container will be created

### Environment Summary

```azure-cli                         2.62.0

core                              2.62.0
telemetry                          1.1.0

Dependencies:
msal                              1.28.1
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\yeabs\.azure\cliextensions'

Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.```

### Additional context

_No response_

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by YeabTilahun** [comment]
Somehow it worked after I changed the container instance name from ```demoaci`` to ```demoaci2```
