### ISSUE TITLE
az storage blob upload-batch: Error: Unable to find image 'mcr.microsoft.com/azure-cli:latest' locally

### ISSUE THREAD

**Issue by zaaraungkam** [Azure/azure-cli#29444]
### Describe the bug

az storage blob upload-batch found an erorr 'Error: Unable to find image 'mcr.microsoft.com/azure-cli:latest' locally'

### Related command

az storage blob upload-batch

### Errors

Unable to find image 'mcr.microsoft.com/azure-cli:latest' locally'

### Issue script & Debug output

Error: Error: Unable to find image 'mcr.microsoft.com/azure-cli:latest' locally
latest: Pulling from azure-cli
ec99f8b99825: Already exists
d63e8a09145a: Pulling fs layer
041c9cdb8297: Pulling fs layer
d3f485a7c887: Pulling fs layer
6818d21c925c: Pulling fs layer
df3841669e52: Pulling fs layer
4f4fb700ef54: Pulling fs layer
df3841669e52: Waiting
4f4fb700ef54: Waiting
6818d21c925c: Waiting
d63e8a09145a: Verifying Checksum
d63e8a09145a: Download complete
d3f485a7c887: Download complete
041c9cdb8297: Verifying Checksum
041c9cdb8297: Download complete
6818d21c925c: Verifying Checksum
6818d21c925c: Download complete
4f4fb700ef54: Verifying Checksum
4f4fb700ef54: Download complete
d63e8a09145a: Pull complete
df3841669e52: Verifying Checksum
df3841669e52: Download complete
041c9cdb8297: Pull complete
d3f485a7c887: Pull complete
6818d21c925c: Pull complete
df3841669e52: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:bfd724c58bb9c784dc4c494e2eeb8ee2c1b07207747bebcdc41939d7b3e34e49
Status: Downloaded newer image for mcr.microsoft.com/azure-cli:latest
/home/runner/work/_temp/AZ_CLI_GITHUB_ACTION_[17](https://github.com/ExxonMobil/MRMA-Frontend/actions/runs/10051847970/job/27782269781#step:8:18)21703398657.sh: line 1: unexpected EOF while looking for matching ``'

cleaning up container...
MICROSOFT_AZURE_CLI_1721703398599_CONTAINER

Error: Unable to find image 'mcr.microsoft.com/azure-cli:latest' locally
latest: Pulling from azure-cli
ec99f8b99825: Already exists
d63e8a09145a: Pulling fs layer
041c9cdb8297: Pulling fs layer
d3f485a7c887: Pulling fs layer
68[18](https://github.com/ExxonMobil/MRMA-Frontend/actions/runs/10051847970/job/27782269781#step:8:19)d21c925c: Pulling fs layer
df3841669e52: Pulling fs layer
4f4fb700ef54: Pulling fs layer
df3841669e52: Waiting
4f4fb700ef54: Waiting
6818d21c925c: Waiting
d63e8a09145a: Verifying Checksum
d63e8a09145a: Download complete
d3f485a7c887: Download complete
041c9cdb8297: Verifying Checksum
041c9cdb8297: Download complete
6818d21c925c: Verifying Checksum
6818d21c925c: Download complete
4f4fb700ef54: Verifying Checksum
4f4fb700ef54: Download complete
d63e8a09145a: Pull complete
df3841669e52: Verifying Checksum
df3841669e52: Download complete
041c9cdb8297: Pull complete
d3f485a7c887: Pull complete
6818d21c925c: Pull complete
df3841669e52: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:bfd724c58bb9c784dc4c494e2eeb8ee2c1b07207747bebcdc4[19](https://github.com/ExxonMobil/MRMA-Frontend/actions/runs/10051847970/job/27782269781#step:8:20)39d7b3e34e49
Status: Downloaded newer image for mcr.microsoft.com/azure-cli:latest
/home/runner/work/_temp/AZ_CLI_GITHUB_ACTION_17[21](https://github.com/ExxonMobil/MRMA-Frontend/actions/runs/10051847970/job/27782269781#step:8:22)703398657.sh: line 1: unexpected EOF while looking for matching ``'

### Expected behavior

Command to finish successfully.

### Environment Summary

GitHub action command:
                  azcliversion: latest
                  inlineScript: |
                      az storage blob upload-batch --account-name ${{ env.storage_account_name }} --auth-mode key -d ${{ env.BlobName }} -s "./dist" --debug --overwrite

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by MoChilia** [comment]
Hi @zaaraungkam, could you check if there are any unexpected quotes passed in the az cli inlineScript, especially the environment variable?

**Comment by MoChilia** [comment]
@zaaraungkam, azure/cli action runs scripts in bash, you can either enclose the variable in single quotes or prepend with a backslash, like `\$web`.

**Comment by zaaraungkam** [comment]
this solution work fine, please close the issue.
very appreciated for your help.
