### ISSUE TITLE
Azure Key Vault access

### ISSUE THREAD

**Issue by abhi-markan** [Azure/azure-cli#29440]
### Describe the bug

When switching between permission model under `Access configuration` on Azure Portal the warning message seems to grow longer.

![image](https://github.com/user-attachments/assets/09dd6f07-6ccb-469b-a6f5-a091178b4fdc)

After switching between RBAC and VAP.

![image](https://github.com/user-attachments/assets/c03fbd0b-c076-4184-8478-9ae8109e09b5)

### Related command

Azure Portal

### Errors

![image](https://github.com/user-attachments/assets/09dd6f07-6ccb-469b-a6f5-a091178b4fdc)

After switching between RBAC and VAP.

![image](https://github.com/user-attachments/assets/c03fbd0b-c076-4184-8478-9ae8109e09b5)

### Issue script & Debug output

N/A

### Expected behavior

Do not repeat warning messages.

### Environment Summary

Azure Portal

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yonzhan** [comment]
Please report this issue to Azure Portal instead of Azure CLI.
