### ISSUE TITLE
Support for sensitivity for rules in Application Gateway WAF

### ISSUE THREAD

**Issue by MaNehaKa** [Azure/azure-cli#29451]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Resource Provider

Network (NRP)

### Description of Feature or Work Requested

Support for sensitivity in Application gateway WAF rules. We are adding sensitivity to rule and Rule override structures as per the below swagger PR.
https://github.com/Azure/azure-rest-api-specs/pull/29855/files 

Corresponding  NRP PR:
https://msazure.visualstudio.com/One/_git/Networking-nrp/pullrequest/8483554

### Minimum API Version Required

2024-03-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/29855

### Target Date

2024-08-30

### PM Contact

joeelerich@microsoft.com

### Engineer Contact

nehakaushil@microsoft.com

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by MaNehaKa** [comment]
Hello @Yonzhan, @necusjz. The Swagger and Powershell changes for this feature have been merged. We require Azure CLI support for public preview. Can you please take a look ?
