### ISSUE TITLE
Document ways to install a specific version of azure-cli on Mac

### ISSUE THREAD

**Issue by cYKatherine** [Azure/azure-cli#29463]
**Describe the solution you'd like**
Document ways to install a specific version of azure-cli on Mac

**Additional context**
Hello, due to https://github.com/Azure/azure-cli/issues/29395 this issue, I have to downgrade my azure-cli from 2.62.0 to 2.61.0, however, after researching on the doc, I don't see any ways for Mac user to switch/downgrade versions.

When I ran `brew search azure-cli` there was no options for different options. 

Just wondering if there is a way to switch versions in mac? If so can I kindly request a documentation upgrade on that please?

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
Downgrade is discouraged in Homebrew. There is no official way to do so.

Please see the discussion： https://github.com/orgs/Homebrew/discussions/155

**Comment by stevo-f3** [comment]
> Downgrade is discouraged in Homebrew. There is no official way to do so.

Please consider re-opening the ticket, since it doesn't actually solve the issue. From Azure customer perspective, Homebrew is not a must, implementation detail.
