### ISSUE TITLE
Customer feedback | az afd endpoint purge |  need information on purging multiple domains

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#29475]
### Describe the bug

 This GitHub issue is from a customer verbatim on 2024-07-14.

**Type of issue**
Missing examples

**Link to reference content:** https://learn.microsoft.com/en-us/cli/azure/afd/endpoint?view=azure-cli-latest#az-afd-endpoint-purge

**This is the current parameter description:** `List of domains. Support shorthand-syntax, json-file and yaml-file. Try "??" to show more.`

**Customer verbatim:**
"
Please add information on how to add multiple domains to the '--domains' parameter.
"

**Request to close this issue:** Please add an example codeblocks showing multiple domains in shorthand syntax, JSON and YAML. For JSON and YAML, consider using Azure CLI's [@fileName convention](https://learn.microsoft.com/en-us/cli/azure/use-azure-cli-successfully-quoting?tabs=bash1%2Cbash2%2Cbash3#json-strings) and bypass the shell's interpretation mechanisms.

### Related command

az afd endpoint purge

### Errors

n/a

### Issue script & Debug output

n/a

### Expected behavior

n/a

### Environment Summary

n/a

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
