### ISSUE TITLE
OpenSuse TW upgrade python311-psutil to version v6 issue

### ISSUE THREAD

**Issue by martinspudich** [Azure/azure-cli#29471]
### Describe the bug

When I'm trying to upgrade OpenSuse TW I'm getting error:
installed azure-cli-core-2.62.0-1.1.noarch requires 'python311-psutil < 6.0', but this request cannot be fulfilled

### Related command

zypper ref & zypper dup

### Errors

installed azure-cli-core-2.62.0-1.1.noarch requires 'python311-psutil < 6.0', but this request cannot be fulfilled

### Issue script & Debug output

...

### Expected behavior

Allow to use python311-psutil >= 6.0

### Environment Summary

azure-cli-2.62.0-1.1
azure-cli-core-2.62.0-1.1
azure-cli-telemetry-1.1.0-3.1
azure-cli-2.62.0-1.1

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
