### ISSUE TITLE
[App Service] Command to add a hostname mistakenly uses the default web app as the hostname

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#2947]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip nightly

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

azure-cli (2.0.3+1.dev20170419)

acr (2.0.1+1.dev20170419)
acs (2.0.3+1.dev20170419)
appservice (0.1.3+1.dev20170419)
batch (2.0.1+1.dev20170419)
cloud (2.0.1+1.dev20170419)
component (2.0.1+1.dev20170419)
configure (2.0.3+1.dev20170419)
container (0.1.3+1.dev20170419)
core (2.0.3+1.dev20170419)
documentdb (0.1.3+1.dev20170419)
feedback (2.0.1+1.dev20170419)
find (0.1.2rc1+1.dev20170312)
iot (0.1.3+1.dev20170419)
keyvault (2.0.1+1.dev20170419)
lab (0.0.2+1.dev20170419)
monitor (0.0.2+1.dev20170419)
network (2.0.3+1.dev20170419)
nspkg (2.0.0+1.dev20170419)
profile (2.0.3+1.dev20170419)
redis (0.2.0+1.dev20170419)
resource (2.0.3+1.dev20170419)
role (2.0.2+1.dev20170419)
sql (2.0.1+1.dev20170419)
storage (2.0.3+1.dev20170419)
vm (2.0.3+1.dev20170419)

Python (Darwin) 2.7.13 (default, Apr  4 2017, 08:47:57) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]

**OS Version:** What OS and version are you using?  
Answer here: macOS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

---

### Description

The `az appservice web config hostname add` command uses the `--name` parameter to indicate the hostname, and not the web app name. This causes the hostname value to pick up the default web app name, if one is set. Could we just rename `--webapp-name` to `--name`, and add a new parameter called `--hostname` (or equivalent)? That way `--name` is used throughout the `appservice web` group and supports defaults holistically.

**Comment by yugangw-msft** [comment]
I thought about that too but backed out the change later, as it goes against a bit the guideline that the `name` should be reserved for the entity the sub-category was created for, which is the `host`
I think we can relax a bit for better usability.

**Comment by lostintangent** [comment]
@yugangw-msft Is this resolved by #2984?

**Comment by yugangw-msft** [comment]
yes.
