### ISSUE TITLE
[App Service] Adding a hostname returns a pretty unfriendly error while waiting for A record changes to apply

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#2948]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip nightly

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

azure-cli (2.0.3+1.dev20170419)

acr (2.0.1+1.dev20170419)
acs (2.0.3+1.dev20170419)
appservice (0.1.3+1.dev20170419)
batch (2.0.1+1.dev20170419)
cloud (2.0.1+1.dev20170419)
component (2.0.1+1.dev20170419)
configure (2.0.3+1.dev20170419)
container (0.1.3+1.dev20170419)
core (2.0.3+1.dev20170419)
documentdb (0.1.3+1.dev20170419)
feedback (2.0.1+1.dev20170419)
find (0.1.2rc1+1.dev20170312)
iot (0.1.3+1.dev20170419)
keyvault (2.0.1+1.dev20170419)
lab (0.0.2+1.dev20170419)
monitor (0.0.2+1.dev20170419)
network (2.0.3+1.dev20170419)
nspkg (2.0.0+1.dev20170419)
profile (2.0.3+1.dev20170419)
redis (0.2.0+1.dev20170419)
resource (2.0.3+1.dev20170419)
role (2.0.2+1.dev20170419)
sql (2.0.1+1.dev20170419)
storage (2.0.3+1.dev20170419)
vm (2.0.3+1.dev20170419)

Python (Darwin) 2.7.13 (default, Apr  4 2017, 08:47:57) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]

**OS Version:** What OS and version are you using?  
Answer here: macOS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

---

### Description

After running `az appservice web config hostname add`, I received the following error, which isn't particularly helpful:

```
Operation failed with status: 'Bad Request'. Details: 400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/227e5d5d-9ecf-4d90-a747-95f50501343e/resourceGroups/<GROUP>/providers/Microsoft.Web/sites/<APP>/hostNameBindings/<DOMAIN>?api-version=2016-08-01
```

When I try adding a hostname via the portal, it indicates that the `A` record changes don't appear to have propagated yet, which helps explain what the issue might be.

After waiting an hour or so, and re-running the command, it worked, which is awesome, but it would be ideal if the CLI provided a friendly indication of what it likely a pretty common error.

**Comment by yugangw-msft** [comment]
I will use this issue to apply the common error extraction logic on all LRO from webapp
