### ISSUE TITLE
Adding resiliency model property on VNG create and update commands

### ISSUE THREAD

**Issue by diagaval** [Azure/azure-cli#29489]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az network vnet-gateway create
az network vnet-gateway show

### Resource Provider

Microsoft.Network/virtualNetworkGateways

### Description of Feature or Work Requested

Feature request to add a property resiliencyModel on gateway creation or update.
[az network vnet-gateway create](https://learn.microsoft.com/en-us/cli/azure/network/vnet-gateway?view=azure-cli-latest#az-network-vnet-gateway-create )
[az network vnet-gateway update](https://learn.microsoft.com/en-us/cli/azure/network/vnet-gateway?view=azure-cli-latest#az-network-vnet-gateway-update)
[az network vnet-gateway show](https://learn.microsoft.com/en-us/cli/azure/network/vnet-gateway?view=azure-cli-latest#az-network-vnet-gateway-show)

**Feature Details**
To drive resiliency for Azure resources and enforce customers to have multi-site resilient setup, customers will have “resiliency model” as a parameter on the gateways at creation. Any virtual network gateway created with gateway_type as ExpressRoute that is marked as multihomed should be connected to at least two ExpressRoute circuits in distinct peering locations or should be connected to an ExpressRoute circuit in metro locations. The behavior for a gateway that is marked as singlehomed will remain the same as current experience.

--resiliency-model
The generation for the virtual network gateway. --resiliency-model should be provided if gateway_type is ExpressRoute.

Accepted values: SingleHomed, MultiHomed

**New Parameter**
--resiliency-model (az network vnet-gateway create and az network vnet-gateway update)
New string parameter for command az network vnet-gateway create:

Allows customer to choose SingleHomed or MultiHomed as the resiliencyModel for the gateways with gatewayType is ExpressRoute.
--resiliency-model (az network vnet-gateway create and az network vnet-gateway update)
Options for this new parameter:
Allows customer to choose SingleHomed or MultiHomed as the resiliency option for the gateways.

az network vnet-gateway show --ids

{
  "name": "resGw",
  "id": "/subscriptions/8c992d64-fce9-426d-b278-85642dfeab03/resourceGroups/diagavalRg/providers/Microsoft.Network/virtualNetworkGateways/resGw",
  "etag": "W/\"aee5a5f4-61a0-4695-b10f-5b46a3532da3\"",
  "type": "Microsoft.Network/virtualNetworkGateways",
  "location": "centraluseuap",
  "tags": {},
  "properties": {
    "provisioningState": "Succeeded",
    "resourceGuid": "65621a40-48a6-45e6-a523-de7fa8fa2a92",
    "packetCaptureDiagnosticState": "None",
    "enablePrivateIpAddress": false,
    "isMigrateToCSES": false,
    "virtualNetworkGatewayMigrationStatus": {
      "state": "None",
      "phase": "None",
      "errorMessage": ""
    },
    "ipConfigurations": [
      {
        "name": "default",
        "id": "/subscriptions/8c992d64-fce9-426d-b278-85642dfeab03/resourceGroups/resRg/providers/Microsoft.Network/virtualNetworkGateways/resGw/ipConfigurations/default",
        "etag": "W/\"aee5a5f4-61a0-4695-b10f-5b46a3532da3\"",
        "type": "Microsoft.Network/virtualNetworkGateways/ipConfigurations",
        "properties": {
          "provisioningState": "Succeeded",
          "privateIPAllocationMethod": "Dynamic",
          "publicIPAddress": {
            "id": "/subscriptions/8c992d64-fce9-426d-b278-85642dfeab03/resourceGroups/diagavalRg/providers/Microsoft.Network/publicIPAddresses/exrPublicIp"
          },
          "subnet": {
            "id": "/subscriptions/8c992d64-fce9-426d-b278-85642dfeab03/resourceGroups/diagavalRg/providers/Microsoft.Network/virtualNetworks/resVnet/subnets/GatewaySubnet"
          }
        }
      }
    ],
    "natRules": [],
    "virtualNetworkGatewayPolicyGroups": [],
    "enableBgpRouteTranslationForNat": false,
    "disableIPSecReplayProtection": false,
    "sku": {
      "name": "Standard",
      "tier": "Standard",
      "capacity": 2
    },
    "gatewayType": "ExpressRoute",
    "vpnType": "PolicyBased",
    "enableBgp": false,
    "activeActive": false,
    "vpnGatewayGeneration": "None",
    "allowRemoteVnetTraffic": false,
    "allowVirtualWanTraffic": false,
    "adminState": "Enabled",
    "resiliencyModel": "MultiHomed"
  }
}

### Minimum API Version Required

2024-03-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-rest-api-specs/pull/29854

### Target Date

2024-08-05

### PM Contact

mekaylamoore@microsoft.com

### Engineer Contact

diagaval@microsoft.com, niteeshkumar@microsoft.com

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by necusjz** [comment]
@diagaval as current is security semester, is your feature request related to any 'security' topic?

**Comment by diagaval** [comment]
No @necusjz. This does not anything related to security.

**Comment by diagaval** [comment]
What are the timelines we are looking for the backlog requests? We are aiming to get this in before the upcoming release. Based on the timelines provided, I can get it escalated if needed. Thanks

**Comment by necusjz** [comment]
@diagaval as https://github.com/Azure/azure-cli/issues/29489#issuecomment-2259349478 mentioned, we're working heavily on security-related features. i cannot give you a solid timeline at that moment

**Comment by diagaval** [comment]
@necusjz Does an escalation from PMs help here? We are targeting this feature as part of 183.

**Comment by necusjz** [comment]
> @necusjz Does an escalation from PMs help here? We are targeting this feature as part of 183.

you guys can contact with our pm (alias: mingxuli) about that

**Comment by diagaval** [comment]
@necusjz Is there a way we can get a review on this PR? We are targeting GA for this feature early next year.

**Comment by necusjz** [comment]
@diagaval got it
