### ISSUE TITLE
Customer feedback & build error | stack-hci-vm | broken links in azure-cli-extensions-list.md

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#29496]
### Feedback category
Broken links

### Document URL:
https://learn.microsoft.com/en-us/cli/azure/azure-cli-extensions-list

### Broken links
1. Extension link: `https://github.com/Azure/azure-cli-extensions/tree/master/src/stack-hci-vm`
2. Release notes link: `https://github.com/Azure/azure-cli-extensions/tree/master/src/stack-hci-vm`

### Reference command
stack-hci-vm extension

### Summary
From Learn Customer Feedback and azure-docs-cli build report, the `stack-hci-vm` links in the Extension list table return a 404. 

### Customer feedback
"
stack-hci-vm extension link is broken.
"

### Screen print on 2024-06-27
![image](https://github.com/user-attachments/assets/f74fbfa9-a190-4f14-a646-ac18e2ce7961)

### Related command
az stack-hci

### Reference page:
https://learn.microsoft.com/en-us/cli/azure/stack-hci

### Errors
404

### Issue script & Debug output

n/a

### Expected behavior

n/a

### Environment Summary

n/a

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by dbradish-microsoft** [comment]
Duplicate GitHub issue.  See #29501
