### ISSUE TITLE
Customer feedback | az network public-ip ddos-protection-statu show | "status" is spelled incorrectly in command name

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#29494]
### Feedback category
Incorrect spelling

### Reference command
az network public-ip ddos-protection-statu

### Problem summary
From Learn Customer Feedback, the word "status" is spelled incorrectly in command name `az network public-ip ddos-protection-statu show`.  The `S` in statu**S** is missing.

### Doc link
https://learn.microsoft.com/en-us/cli/azure/network/public-ip/ddos-protection-statu?view=azure-cli-latest

### Customer feedback
"
AZ Cli doesn't seem to know this commands.
Commands are ambiguous:
- ddos-protection-statu show
- show-ddos-protection-statu

Why the hell `statu` whithout `s` ?
"

### Screen print:
![image](https://github.com/user-attachments/assets/1486364b-cc5d-4d09-9108-afb5d0b4bf7a)

### Related command

az network public-ip ddos-protection-statu

### Errors

n/a

### Issue script & Debug output

n/a

### Expected behavior

n/a

### Environment Summary

Screen print taken from Azure CLI 2.62.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
