### ISSUE TITLE
Resource deletion: unable to pass --force when using query

### ISSUE THREAD

**Issue by Teodelas** [Azure/azure-cli#2953]
Hi,

I'm trying to delete VMs in bulk and need to pass the --force switch.  
 az vm delete --ids "$(az vm list -g IPv6 --query "[?contains(name,'XREVM')].id" -o tsv)" --force 
& 
 az vm delete --force --ids $(az vm list -g IPv6 --query "[?contains(name,'XREVM')].id" -o tsv)

- Both give the error: az: error: unrecognized arguments: --force

**Comment by derekbekoe** [comment]
The param is `--yes` (it was renamed).
Adding `--help` should indicate the available params.

**Comment by Teodelas** [comment]
Thanks.  Note that the help file still references –force (under examples):

Delete a VM without a prompt for confirmation.
        az vm delete -g MyResourceGroup -n MyVm --force

[cid:image002.jpg@01D2BAA2.0EE5B890]

**Comment by derekbekoe** [comment]
What version of the CLI do you have?

I see:
```
Examples
    Delete a VM without a prompt for confirmation.
        az vm delete -g MyResourceGroup -n MyVm --yes
```

**Comment by Teodelas** [comment]
azure-cli (2.0.1)

**Comment by derekbekoe** [comment]
The current latest is 2.0.3 so would suggest upgrading to that.
