### ISSUE TITLE
{relay} HTML tags are rendering as empty parameter values in reference docs

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#29539]
### Problem to solve:
HTML tags in source code are causing build warnings in MicrosoftDocs/azure-docs-cli. More importantly, customer-facing reference docs are not instantiating properly -- parameter values formatted with \`<>` are missing. Here's an example:
![image](https://github.com/user-attachments/assets/5552ae5e-dd43-4376-b8fc-3c6c750707e2)

### Requested solution:
These values should be escaped with a backtick. Here's an example from [az webpubsub](https://learn.microsoft.com/en-us/cli/azure/webpubsub?view=azure-cli-latest#az-webpubsub-create-required-parameters).
![image](https://github.com/user-attachments/assets/806899f7-9eca-483e-a175-c486f003b7f4)

### Related GitHub issues:
This is the same issue as [these GitHub issues](https://github.com/Azure/azure-cli/issues?q=is%3Aissue+author%3Adbradish-microsoft+HTML+in%3Atitle+).

### List of HTML tag instances that need update:
|File name | Build error |
|-|-|
| latest/docs-ref-autogen/relay/hyco.yml | HTML tag 'indexToRemove' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder. | 
| latest/docs-ref-autogen/relay/hyco.yml | HTML tag 'value' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder. | 
| latest/docs-ref-autogen/relay/hyco/authorization-rule.yml | HTML tag 'indexToRemove' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder. | 
| latest/docs-ref-autogen/relay/hyco/authorization-rule.yml | HTML tag 'value' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder. | 
| latest/docs-ref-autogen/relay/namespace.yml | HTML tag 'indexToRemove' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder. | 
| latest/docs-ref-autogen/relay/namespace.yml | HTML tag 'value' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder. | 
| latest/docs-ref-autogen/relay/namespace/authorization-rule.yml | HTML tag 'indexToRemove' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder. | 
| latest/docs-ref-autogen/relay/namespace/authorization-rule.yml | HTML tag 'value' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder. | 
| latest/docs-ref-autogen/relay/wcfrelay.yml | HTML tag 'indexToRemove' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder. | 
| latest/docs-ref-autogen/relay/wcfrelay.yml | HTML tag 'value' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder. | 
| latest/docs-ref-autogen/relay/wcfrelay/authorization-rule.yml | HTML tag 'indexToRemove' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder. | 
| latest/docs-ref-autogen/relay/wcfrelay/authorization-rule.yml | HTML tag 'value' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder. | 

### Related command

az relay

### Errors

n/a

### Issue script & Debug output

n/a

### Expected behavior

n/a

### Environment Summary

Azure CLI 2.62.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
