### ISSUE TITLE
az network nat gateway create NO --TAGS PARAMETER

### ISSUE THREAD

**Issue by sassdawe** [Azure/azure-cli#29565]
### Describe the bug

Trying to create a Nat Gateway with the CLI but I can't assign tags at creation, which is a problem because there is a policy in place expecting tags on the resources

### Related command

az network nat gateway create

### Errors

ERROR: unrecognized arguments: --tags 

### Issue script & Debug output

DEBUG: cli.azure.cli.core.command_recommender: "--tags" is an invalid parameter for command "network nat gateway create".

### Expected behavior

the `--tags` parameter should work

### Environment Summary

```
azure-cli                         2.62.0

core                              2.62.0
telemetry                          1.1.0

Dependencies:
msal                              1.28.1
azure-mgmt-resource               23.1.1
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
