### ISSUE TITLE
[Provider] Improve output of `provider show` command

### ISSUE THREAD

**Issue by jaredmoo** [Azure/azure-cli#2957]
Registering provider gives this helpful hint:
```
(env) D:\git\azure-cli [usages ≡]> az provider register -n Microsoft.Sql
Registering is still on-going. You can monitor using 'az provider show -n Microsoft.Sql'
```

However the output of `az provider show -n Microsoft.Sql` is huge and overwhelming. `az provider show -n Microsoft.Sql --query registrationState` would be better.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: nightly

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
```
azure-cli (2.0.3+dev)

acr (2.0.1+dev)
acs (2.0.3+dev)
appservice (0.1.3+dev)
batch (2.0.1+dev)
cloud (2.0.1+dev)
component (2.0.1+dev)
configure (2.0.3+dev)
container (0.1.3+dev)
core (2.0.3+dev)
dla (0.0.2+dev)
dls (0.0.2+dev)
documentdb (0.1.3+dev)
feedback (2.0.1+dev)
find (0.0.2+dev)
iot (0.1.3+dev)
keyvault (2.0.1+dev)
lab (0.0.2+dev)
monitor (0.0.2+dev)
network (2.0.3+dev)
nspkg (2.0.0+dev)
profile (2.0.3+dev)
redis (0.2.0+dev)
resource (2.0.3+dev)
role (2.0.2+dev)
sql (2.0.1+dev)
storage (2.0.3+dev)
taskhelp (0.1.1b4+dev)
testsdk (0.1.0+dev)
utility-automation (0.1.1)
vm (2.0.3+dev)

Python (Windows) 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
```

**OS Version:** What OS and version are you using?  
Answer here: Windows 10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: PowerShell

**Comment by jaredmoo** [comment]
Also if I have already registered then the help text is misleading. It should just succeed or maybe write text like "already registered".

**Comment by jaredmoo** [comment]
Docs at https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-common-deployment-errors#noregisteredproviderfound has the command `az provider show -n Microsoft.Web --query "resourceTypes[?resourceType=='sites'].locations"` which returns an empty list for `Microsoft.Sql`. So this doc page also needs to be clarified somehow.

**Comment by tjprescott** [comment]
@yugangw-msft isn't automatic registration now part of the CLI infrastructure?

**Comment by yugangw-msft** [comment]
> isn't automatic registration now part of the CLI infrastructure?

Yes, it is a part of the infrastructure to trigger when a CLI command fails for the error of `MissingSubscriptionRegistration`. So with recent versions of CLI, `az provider register` is less needed.
But, we still need to mention correct state in the status text, and also ensure the table output contains good information.

**Comment by lmazuel** [comment]
It's even part of msrestazure since 0.4.9, and less than less needed :)

**Comment by yugangw-msft** [comment]
> Docs at https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-common-deployment-errors#noregisteredproviderfound has the command az provider show -n Microsoft.Web --query "resourceTypes[?resourceType=='sites'].locations" which returns an empty list for Microsoft.Sql. So this doc page also needs to be clarified somehow.

Using `az provider show -n Microsoft.SQL --query "resourceTypes[?resourceType=='servers/databases'].locations` should work, the document uses appservice as the example, so you have to tweak across 

   > Also if I have already registered then the help text is misleading. It should just succeed or maybe write text like "already registered".

This was fixed last month :)
