### ISSUE TITLE
az k8s-configuration flux create executes kubectl commands on current kubernetes cluster context not specified cluster name

### ISSUE THREAD

**Issue by israelvaldez** [Azure/azure-cli#29601]
### Describe the bug

When you run the command az k8s-configuration flux create with the following parameters, the result is that if you have a different kubernetes cluster in your context that you'd get kubectl commands executed against the kuberentes cluster in your current context as opposed to the one that you specified.

### Related command

az k8s-configuration flux create

### Errors

Kubernetes cluster in current context gets disconnected

### Issue script & Debug output

```Powershell
$clusterName = "AKS cluster name"
$clusterResourceGroup="resource group of AKS cluster to connect"
$urlOfClusterGitOpsRepo="git url"
$clusterGitOpsBranch = "branch name"
$httpsUser="user"
$httpsKey=""
Write-Host "##[section]Running connectedk8s connect"
az connectedk8s connect --name $clusterName --resource-group $clusterResourceGroup
 
Write-Host "##[section]Verify cluster is connected to ARC"
az connectedk8s list --resource-group $clusterResourceGroup --output table
 
$clusterConfigName = "cluster-config"
 
Write-Host "##[section]Connect Cluster GitOps repo [$clusterConfigName]"
az k8s-configuration flux create `
    --name $clusterConfigName `
    --cluster-name $clusterName `
    --resource-group $clusterResourceGroup `
    --cluster-type connectedClusters `
    --scope cluster `
    --namespace $clusterConfigName `
    --kind git `
    --url $urlOfClusterGitOpsRepo `
    --branch $clusterGitOpsBranch `
    --https-user $httpsUser `
    --https-key $httpsKey `
    --sync-interval 5m `
    --timeout 5m `
    --kustomization name=$clusterConfigName sync_interval=5m timeout=5m prune=true
```

### Expected behavior

Kubernetes cluster specified in the parameters should be used to install azure arc on it

### Environment Summary

azure-cli                         2.53.0 *

core                              2.53.0 *
telemetry                          1.1.0

Extensions:
aks-preview                      0.5.174
azure-devops                       1.0.1
bastion                            0.2.7
connectedk8s                       1.6.5
k8s-configuration                  1.7.0
k8s-extension                      1.6.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\ivaldez\.azure\cliextensions'

Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

You have 2 update(s) available. Consider updating your CLI installation with 'az upgrade'

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bavneetsingh16** [comment]
@israelvaldez, the k8s-configuration CLI does not use the kube context and sends requests directly to the Azure service. The fluxconfig-agent on the cluster then queries the Azure service for any pending requests and applies the necessary configurations. For troubleshooting logs, please run the command with the --debug flag.

**Comment by israelvaldez** [comment]
Sure, I'm terrified of running this again. I'll try to find a way to run it in the context of development clusters so that I can run it in a safe place and get back to you.

**Comment by israelvaldez** [comment]
It appears that the problem happens even though you run the Azure CLI commands in the context of the correct Azure subscription using an Azure DevOps Azure CLI task and you've pulled down the correct Kubernetes context (which doesn't seem to matter).

What kind of log do you need in order to triage this problem?

**Comment by bavneetsingh16** [comment]
@israelvaldez, can you please share the cmd and the output when the cmd is run using '--debug' flag.

az k8s-configuration flux create `
    --name $clusterConfigName `
    --cluster-name $clusterName `
    --resource-group $clusterResourceGroup `
    --cluster-type connectedClusters `
    --scope cluster `
    --namespace $clusterConfigName `
    --kind git `
    --url $urlOfClusterGitOpsRepo `
    --branch $clusterGitOpsBranch `
    --https-user $httpsUser `
    --https-key $httpsKey `
    --sync-interval 5m `
    --timeout 5m `
    --kustomization name=$clusterConfigName sync_interval=5m timeout=5m prune=true
    --debug

**Comment by bavneetsingh16** [comment]
The kube-context set in the az connectedk8s cli extension was incorrect which caused the issue. Regarding 'connectedk8s' switching context during onboarding, the kube-config is simply loaded and used to run helm operations without any additional manipulation that would affect the current context in kube-config. The issue arose because the context in the kube-config was always pointing to the wrong cluster, specifically the eastus cluster. Consequently, during the pre-onboarding process, it cleaned up Azure Arc resources(extension CRD) from the cluster, leading to the deletion of the flux-configurations and extension.
