### ISSUE TITLE
Issue with Get-AzStorageAccount command

### ISSUE THREAD

**Issue by pkent81** [Azure/azure-cli#29629]
### Describe the bug

Using the above command to get the minimium TLS version of our storage accounts it retirns correct values when the storage account is ysing TLS1_0m TLS1_1 and TLS1_2 but if the minimium has been set as TLS1_3 then null gets returned in the MinimumTlsVersion property

### Related command

Get-AzStorageAccount -ResourceGroupName $targetResourceGroup -Name $storageAccountName

### Errors

output not as expected when TLS1.3 is set on sa

### Issue script & Debug output

StorageAccountName                : policytls13testsa
Kind                              : StorageV2
Encryption                        : Microsoft.Azure.Management.Storage.Models.Encryption
AccessTier                        : Hot
MinimumTlsVersion                 : 

StorageAccountName                : testtls11policysa       
Kind                              : StorageV2
Encryption                        : Microsoft.Azure.Management.Storage.Models.Encryption
AccessTier                        : Hot
MinimumTlsVersion                 : TLS1_1

StorageAccountName                : testtlspolicy12sa
Encryption                        : Microsoft.Azure.Management.Storage.Models.Encryption
AccessTier                        : Hot
MinimumTlsVersion                 : TLS1_2

StorageAccountName                : testtlspolicysa
Kind                              : StorageV2
AccessTier                        : Hot
MinimumTlsVersion                 : TLS1_0

### Expected behavior

For the sa using 1.3 i would expect t see:
MinimumTlsVersion                 : TLS1_3

### Environment Summary

azure-cli                         2.62.0

core                              2.62.0
telemetry                          1.1.0

Extensions:
azure-devops                       1.0.1

Dependencies:
msal                              1.28.1
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\KentP\.azure\cliextensions'

Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 21:52:07) [MSC v.1937 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yonzhan** [comment]
Please open this issue in Azure-PowerShell repo.
