### ISSUE TITLE
Feature request: Include port numbers in az vmss list-instances

### ISSUE THREAD

**Issue by kpu** [Azure/azure-cli#2962]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: apt-get

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
```
azure-cli (2.0.3)

acr (2.0.1)
acs (2.0.3)
appservice (0.1.3)
batch (2.0.1)
cloud (2.0.1)
component (2.0.1)
configure (2.0.3)
container (0.1.3)
core (2.0.3)
documentdb (0.1.3)
feedback (2.0.1)
find (0.0.2)
iot (0.1.3)
keyvault (2.0.1)
lab (0.0.2)
monitor (0.0.2)
network (2.0.3)
nspkg (2.0.0)
profile (2.0.3)
redis (0.2.0)
resource (2.0.3)
role (2.0.2)
sql (2.0.1)
storage (2.0.3)
vm (2.0.3)

Python (Linux) 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]
```

**OS Version:** What OS and version are you using?  
Answer here: Ubuntu 16.04.2 LTS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

---

### Description
Due to overprovisioning and deletion, SSH port numbers may not correspond to 50000 + InstanceId in VM scale sets.  A better option would be to fix that but, failing that, expose this in the command line tables.  

So far as I can tell the only way figure out the correspondence between port number and instance ID is logging into the machine and parsing the host name or parsing the JSON from
```bash
az network lb show -g group -n scaleLB -o json
```
Can you add this to the output of `az vmss list-instances` so I'd feel better about deleting the right instance?  That or let me delete by port number.

**Comment by yugangw-msft** [comment]
Will `az vmss list-instance-connection-info` help?

**Comment by kpu** [comment]
That tells me the IP and port numbers, but not how they correspond to InstanceId.

**Comment by yugangw-msft** [comment]
I can add the instance id, will that be sufficient?

**Comment by kpu** [comment]
Yes
