### ISSUE TITLE
Curl install improvements

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#2963]
- [x] Native dependency check should be Python version aware. eg. if user is using Python 3, suggest `python3-dev` instead of `python-dev`.

- [x] Check if `python` available. If not, show actionable user message.
(see https://github.com/Microsoft/BashOnWindows/issues/1980)
Possibly could do this in `install` file.
```
command -v python > /dev/null 2>&1 || {echo "Python not found. If python is available on the system, add it to PATH. For example `sudo ln -s /usr/bin/python3 /usr/bin/python`"; exit 1;}
```

Could potentially be more clever and run `command -v python3`. If that's there, modify the error message with the correct path to use.

cc/ @troydai

**Comment by troydai** [comment]
I'd like to hear more from users regarding the choice between python 2 and 3. If both pythons exist on the platform, what version of python do customers prefer to have our CLI relies on.
