### ISSUE TITLE
Add checksums (SHA256) to GitHub releases for all files

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/azure-cli#29656]
**Related command**

Add checksums (SHA256) to releases for all files, be it files hosted on GitHub (MSI, source code), and files from `azcliprod.blob.core.windows.net` (ZIP, MSI etc.).

**Is your feature request related to a problem? Please describe.**

* Integrity, know that what you downloaded hasn't been corrupted.
* Make it faster for package managers like Scoop to get checksums for new releases without having to download the artifact(s).
  * Which is an even bigger pain with Azure CLI because `azcliprod.blob.core.windows.net` is so slow.
    * 2021-09-03 #19447
    * 2024-04-30 #28856

**Describe the solution you'd like**

Add a list to GitHub releases with SHA256, like Beaver Notes does:

* <https://github.com/Beaver-Notes/Beaver-Notes/releases/tag/3.5.0>

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
Hi @o-l-a-v, I noticed https://github.com/Beaver-Notes/Beaver-Notes/releases/tag/3.5.0 puts SHA256s in the release description:

![image](https://github.com/user-attachments/assets/1acc1d90-858c-4a8e-91d0-ac3df72416ba)

https://github.com/PowerShell/PowerShell/releases/tag/v7.4.4 uses a different format:

![image](https://github.com/user-attachments/assets/1521c03c-c42e-4b2d-aa92-c26e5fc632e7)

How does Scoop extract this information from plaintext?

**Comment by o-l-a-v** [comment]
I have a PR on Beaver Notes for Scoop that shows the info Scoop needs to fetch the SHA256 checksums:

* <https://github.com/ScoopInstaller/Extras/pull/13661/files>

Here's the manifest for pwsh, looks like it fetches SHA256 info from release info too:

* <https://github.com/ScoopInstaller/Main/blob/master/bucket/pwsh.json>

Here's info on the Scoop app manifest:

* <https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests>

Here's Scoop main manifest repos, see if you can find more examples there:

* main (command line programs only): <https://github.com/ScoopInstaller/Main/tree/master/bucket>
* extras (can be GUI too): <https://github.com/ScoopInstaller/Extras/tree/master/bucket>

**Comment by jiasli** [comment]
Thanks @o-l-a-v, but I think you misunderstand my question. 

In other words, how is `6461dd3fda39fc65e30c7642f863b9e1dabe32885043094e1d8a79dffcef1dcb` extracted from https://github.com/PowerShell/PowerShell/releases/tag/v7.4.4 to https://github.com/ScoopInstaller/Main/blob/75c4fa28f734a4849633a8bd920013bf7d93911a/bucket/pwsh.json#L16 ? Is this a manual process? Or is there a standard format? I would like to know which format you want us to use to provide the SHA256s.

BTW, I noticed Scoop computes the SHA256 of https://azcliprod.blob.core.windows.net/zip/azure-cli-2.63.0-x64.zip by itself: https://github.com/ScoopInstaller/Main/blob/75c4fa28f734a4849633a8bd920013bf7d93911a/bucket/azure-cli.json#L13

**Comment by o-l-a-v** [comment]
As the feature request states: Scoop can calculate SHA256 by downloading the artifact. But if checksum is already made available and Scoop is told were to look, it does not have to 1) download the artifact and 2) calculate hash.

Scoop has logic to autoupdate manifests. If we add hash (`"autoupdate":{"hash": {}}`) property to the manifest JSON, scoop will try to find the checksums depending on the logic. So for Beaver-Notes <https://github.com/ScoopInstaller/Extras/pull/13661/files>:

```json
    ...
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/Beaver-Notes/Beaver-Notes/releases/download/$version/Beaver-notes.$version.portable.exe#/dl.7z"
            },
            "arm64": {
                "url": "https://github.com/Beaver-Notes/Beaver-Notes/releases/download/$version/Beaver-notes.$version.portable.arm64.exe#/dl.7z"
            }
        },
        "hash": {
            "url": "https://github.com/Beaver-Notes/Beaver-Notes/releases/tag/$version",
            "regex": "$sha256.*?$basename"
        }
    }
}
```

And for pwsh <https://github.com/ScoopInstaller/Main/blob/master/bucket/pwsh.json>:

```json
{
    ...
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/PowerShell/PowerShell/releases/download/v$version/PowerShell-$version-win-x64.zip"
            },
            "32bit": {
                "url": "https://github.com/PowerShell/PowerShell/releases/download/v$version/PowerShell-$version-win-x86.zip"
            },
            "arm64": {
                "url": "https://github.com/PowerShell/PowerShell/releases/download/v$version/PowerShell-$version-win-arm64.zip"
            }
        },
        "hash": {
            "url": "$baseurl/hashes.sha256"
        }
    }
}
```

**Comment by o-l-a-v** [comment]
There are som `find_hash_in_x` function sinside here:

* <https://github.com/ScoopInstaller/Scoop/blob/master/lib/autoupdate.ps1>

**Comment by jiasli** [comment]
Thank you for the detailed explanation. [`find_hash_in_textfile`](https://github.com/ScoopInstaller/Scoop/blob/859d1db51bcc840903d5280567846ae2f7207ca2/lib/autoupdate.ps1#L23) looks a little bit fragile. I think creating a `hashes.sha256` with `sha256sum --binary *` is a more formal and reliable implementation. We will consider this as a feature request.

**Comment by jiasli** [comment]
I noticed today that Python provides very convenient functions to compute file hashes:

https://docs.python.org/3/library/hashlib.html#file-hashing

```py
import io, hashlib, hmac
with open(hashlib.__file__, "rb") as f:
    digest = hashlib.file_digest(f, "sha256")

digest.hexdigest()  
```

**Comment by jiasli** [comment]
Our release pipeline is on Linux, so the below command will do the job:

```
sha256sum -b azure-cli* > hashes.sha256
```

**Comment by jiasli** [comment]
Our release pipeline is on Linux, so the below command will do the job:

```
sha256sum --binary azure-cli* > hashes.sha256
```

`hashes.sha256` will look like

```
723cf2ac1d252ee086841dece0fff10538e15926d2c7ed1085d02c0f82b7393e *azure-cli-2.67.0-x64.msi
b8b31530939d8016ff23da4d2196a4286e9db6477117733c770b805b6fa64162 *azure-cli-2.67.0-x64.zip
c4cdd13157968052bc2ffeecb4459d466de95d4b9ab8194963ab601d9f613c44 *azure-cli-2.67.0.msi
```

`*` indicates binary mode.

According to https://manpages.ubuntu.com/manpages/noble/man1/sha256sum.1.html

> Note: There is no difference between binary mode and text mode on GNU systems.

But it is still better to specify `--binary` to align with `hashes.sha256` from https://github.com/PowerShell/PowerShell/releases

**Comment by jiasli** [comment]
@o-l-a-v, we have updated the latest release (2.67.0) to include SHA256 hashes for the release artifacts in the release description: https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.67.0

This is only experimental, so please let us know if this suits your needs. If you want us to change its format, feel free to let us know. 😊

Also, do you want us to publish a `hashes.sha256` file? If so, any preference on the file name?

**Comment by o-l-a-v** [comment]
Nice! That should make it easy for Scoop to find the checksum.

I think I prefer one `<filename.ext>.sha256` file per artifact, but one file for all hashes like PowerShell do works too:

* <https://github.com/PowerShell/PowerShell/releases/tag/v7.4.6>

**Comment by jiasli** [comment]
I am glad it works for you. 😊

Actually, I noticed https://github.com/Beaver-Notes/Beaver-Notes/releases doesn't have a dedicated file for hashes.

![Image](https://github.com/user-attachments/assets/5d651c8c-923e-4ad5-a97b-cf25cdc2dad2)

Does putting hashes only in release description work for you? Or is it still necessary for us to release dedicated hash file(s)?

Also, there doesn't seem to be an industry standard on what should be inside that file.

**Comment by o-l-a-v** [comment]
Hashes in description only works.

If creating checksum file(s) it'd be great it they work with sha256sum:

* <https://www.man7.org/linux/man-pages/man1/sha256sum.1.html>

`sha256sum --check --ignore-missing checksums.sha256sum`

**Comment by jiasli** [comment]
@o-l-a-v, thanks for the additional information. As I mentioned in https://github.com/Azure/azure-cli/issues/29656#issuecomment-2562240157, our pipeline is on a Linux agent, so a single `sha256sum --binary azure-cli* > hashes.sha256` command will do the job.

There is even no convention on the hash file name: `hashes.sha256` vs `checksums.sha256`. Also, as PowerShell does, if we add `hashes.sha256`, the `hashes.sha256` needs its own hash (https://github.com/PowerShell/PowerShell/releases/tag/v7.4.6). I prefer not to complicate things too much.

As "Hashes in description only works", I will keep it this way. If a dedicated hash file is needed someday, please don't hesitate to create a new issue.

**Comment by o-l-a-v** [comment]
Perfect, thanks @jiasli. 😊
