### ISSUE TITLE
az functionapp missing

### ISSUE THREAD

**Issue by spboyer** [Azure/azure-cli#2967]
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: `pip install --upgrade --pre azure-cli --extra-index-url https://azureclinightly.blob.core.windows.net/packages`

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
```
azure-cli (2.0.3+1.dev20170421)

acr (2.0.1+1.dev20170421)
acs (2.0.3+1.dev20170421)
appservice (0.1.3+1.dev20170421)
batch (2.0.1+1.dev20170421)
cloud (2.0.1+1.dev20170421)
component (2.0.1+1.dev20170421)
configure (2.0.3+1.dev20170421)
container (0.1.3+1.dev20170421)
core (2.0.3+1.dev20170421)
documentdb (0.1.3+1.dev20170421)
feedback (2.0.1+1.dev20170421)
find (0.1.2rc1+1.dev20170312)
iot (0.1.3+1.dev20170421)
keyvault (2.0.1+1.dev20170421)
lab (0.0.2+1.dev20170421)
monitor (0.0.2+1.dev20170421)
network (2.0.3+1.dev20170421)
nspkg (2.0.0+1.dev20170421)
profile (2.0.3+1.dev20170421)
redis (0.2.0+1.dev20170421)
resource (2.0.3+1.dev20170421)
role (2.0.2+1.dev20170421)
sql (2.0.1+1.dev20170421)
storage (2.0.3+1.dev20170421)
vm (2.0.3+1.dev20170421)

Python (Darwin) 2.7.12 (default, Jun 29 2016, 14:05:02)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
```

**OS Version:** What OS and version are you using?  
Answer here: macOS Sierra 10.12.4

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: iTerm (bash)

---

### Description

`az functionapp` no longer available as command. Was perviously.

![image](https://cloud.githubusercontent.com/assets/7681382/25305454/4f9dc03a-2749-11e7-97b2-3b3da242fec8.png)

@SyntaxC4

**Comment by tjprescott** [comment]
Functionapp was never available on the master branch--upgrading from the nightly build like you did will align your installation with the master branch (correct me if I'm wrong here @derekbekoe).  You would need to clone the repo, switch to the functionapp branch and run dev_setup.py. Then to "update" you simply pull the latest from that branch and (possibly) re-run dev_setup.py

**Comment by spboyer** [comment]
@tjprescott - I was in nightly build, please see the version info pasted above. Please reopen issue. 

Thanks.

**Comment by derekbekoe** [comment]
@spboyer Doesn't look like it was ever in the nightly build as it's on the [functionapp branch](https://github.com/Azure/azure-cli/blob/functionapp/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py) and not [master branch](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py).

Nightly builds are built from master.
