### ISSUE TITLE
 az ams | missing examples in reference content

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#29676]
### Bug category:
**Missing information**

### Request:

The [Azure CLI reference guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/reference_doc_guidelines.md#examples) specifiy at least two examples for each command. Please review the Azure CLI reference guidelines for [examples](https://github.com/Azure/azure-cli/blob/dev/doc/reference_doc_guidelines.md#examples) and [parameters](https://github.com/Azure/azure-cli/blob/dev/doc/reference_doc_guidelines.md#parameters) and add missing content to your source code. 

If a parameter accepts JSON content, provide a JSON example in the parameter long or short summary, or in a separate code block.

### Issue summary:
Understanding that not all “create” commands directly generate Microsoft revenue, every “create” or “add” minimally make a revenue-producing Azure resource possible. Consequently, **create commands are the most important examples to add.** Of secondary importance are reference commands with complex parameters (JSON, YAML, URLs, complex Azure resource IDs, multi-valued lists, key:value pairs, conditional parameters, parameter pairs ...).

### Subgroups with no examples:

Note: The commands for these subgroups are in the second table (below).  Page views (PVs) for a subgroup are "the sum of all PVs for every autogenerated reference doc in that subgroup." When there is > 1 command in a single GitHub file, the same PV amount is counted for both commands. PVs are being provided as a general idea of customer interest.

| Subgroup name | Status | Command count| 6 month PVs |
|-|-|-|-|
| [az ams account](https://docs.microsoft.com/cli/azure/ams/account) | GA | 6 | 72 | 
| [az ams account mru](https://docs.microsoft.com/cli/azure/ams/account/mru) | GA | 2 |  | 
| [az ams account storage](https://docs.microsoft.com/cli/azure/ams/account/storage) | GA | 4 | 13 | 
| [az ams asset-track](https://docs.microsoft.com/cli/azure/ams/asset-track) | GA | 6 |  | 
| [az ams live-output](https://docs.microsoft.com/cli/azure/ams/live-output) | GA | 4 | 63 | 
| [az ams streaming-endpoint akamai](https://docs.microsoft.com/cli/azure/ams/streaming-endpoint/akamai) | GA | 2 | 13 | 
| [az ams streaming-locator](https://docs.microsoft.com/cli/azure/ams/streaming-locator) | GA | 6 | 117 | 
| [az ams streaming-policy](https://docs.microsoft.com/cli/azure/ams/streaming-policy) | GA | 4 | 22 | 

### Reference commands with no examples:

Note: Some of these command **subgroups** have at least one example. This table is a list of all `az ams` **commands** with no examples. PV values repeat when one GitHub file contains > 1 reference command. PVs are being provided as a general idea of customer interest.

| Reference name | Parameter count | is Create | 6 month PVs |
|-|-|-|-|
| [az ams account check-name](https://docs.microsoft.com/cli/azure/ams/account#az-ams-account-check-name) | 2 |  | 72 |
| [az ams account create](https://docs.microsoft.com/cli/azure/ams/account#az-ams-account-create) | 10 | **yes** | 72 |
| [az ams account delete](https://docs.microsoft.com/cli/azure/ams/account#az-ams-account-delete) | 4 |  | 72 |
| [az ams account list](https://docs.microsoft.com/cli/azure/ams/account#az-ams-account-list) | 1 |  | 72 |
| [az ams account mru set](https://docs.microsoft.com/cli/azure/ams/account/mru#az-ams-account-mru-set) | 6 |  |   |
| [az ams account mru show](https://docs.microsoft.com/cli/azure/ams/account/mru#az-ams-account-mru-show) | 4 |  |   |
| [az ams account show](https://docs.microsoft.com/cli/azure/ams/account#az-ams-account-show) | 4 |  | 72 |
| [az ams account sp reset-credentials](https://docs.microsoft.com/cli/azure/ams/account/sp#az-ams-account-sp-reset-credentials) | 9 |  | 10 |
| [az ams account storage add](https://docs.microsoft.com/cli/azure/ams/account/storage#az-ams-account-storage-add) | 7 | **yes** | 13 |
| [az ams account storage remove](https://docs.microsoft.com/cli/azure/ams/account/storage#az-ams-account-storage-remove) | 5 |  | 13 |
| [az ams account storage set-authentication](https://docs.microsoft.com/cli/azure/ams/account/storage#az-ams-account-storage-set-authentication) | 8 |  | 13 |
| [az ams account storage sync-storage-keys](https://docs.microsoft.com/cli/azure/ams/account/storage#az-ams-account-storage-sync-storage-keys) | 5 |  | 13 |
| [az ams account update](https://docs.microsoft.com/cli/azure/ams/account#az-ams-account-update) | 9 |  | 72 |
| [az ams account-filter delete](https://docs.microsoft.com/cli/azure/ams/account-filter#az-ams-account-filter-delete) | 5 |  | 20 |
| [az ams account-filter list](https://docs.microsoft.com/cli/azure/ams/account-filter#az-ams-account-filter-list) | 2 |  | 20 |
| [az ams account-filter show](https://docs.microsoft.com/cli/azure/ams/account-filter#az-ams-account-filter-show) | 5 |  | 20 |
| [az ams account-filter update](https://docs.microsoft.com/cli/azure/ams/account-filter#az-ams-account-filter-update) | 17 |  | 20 |
| [az ams asset create](https://docs.microsoft.com/cli/azure/ams/asset#az-ams-asset-create) | 7 | **yes** | 169 |
| [az ams asset delete](https://docs.microsoft.com/cli/azure/ams/asset#az-ams-asset-delete) | 5 |  | 169 |
| [az ams asset get-encryption-key](https://docs.microsoft.com/cli/azure/ams/asset#az-ams-asset-get-encryption-key) | 5 |  | 169 |
| [az ams asset get-sas-urls](https://docs.microsoft.com/cli/azure/ams/asset#az-ams-asset-get-sas-urls) | 7 |  | 169 |
| [az ams asset list-streaming-locators](https://docs.microsoft.com/cli/azure/ams/asset#az-ams-asset-list-streaming-locators) | 5 |  | 169 |
| [az ams asset show](https://docs.microsoft.com/cli/azure/ams/asset#az-ams-asset-show) | 5 |  | 169 |
| [az ams asset update](https://docs.microsoft.com/cli/azure/ams/asset#az-ams-asset-update) | 11 |  | 169 |
| [az ams asset-filter delete](https://docs.microsoft.com/cli/azure/ams/asset-filter#az-ams-asset-filter-delete) | 9 |  | 22 |
| [az ams asset-filter list](https://docs.microsoft.com/cli/azure/ams/asset-filter#az-ams-asset-filter-list) | 0 |  | 22 |
| [az ams asset-filter show](https://docs.microsoft.com/cli/azure/ams/asset-filter#az-ams-asset-filter-show) | 6 |  | 22 |
| [az ams asset-filter update](https://docs.microsoft.com/cli/azure/ams/asset-filter#az-ams-asset-filter-update) | 18 |  | 22 |
| [az ams asset-track create](https://docs.microsoft.com/cli/azure/ams/asset-track#az-ams-asset-track-create) | 10 | **yes** |   |
| [az ams asset-track delete](https://docs.microsoft.com/cli/azure/ams/asset-track#az-ams-asset-track-delete) | 6 |  |   |
| [az ams asset-track list](https://docs.microsoft.com/cli/azure/ams/asset-track#az-ams-asset-track-list) | 3 |  |   |
| [az ams asset-track show](https://docs.microsoft.com/cli/azure/ams/asset-track#az-ams-asset-track-show) | 6 |  |   |
| [az ams asset-track update](https://docs.microsoft.com/cli/azure/ams/asset-track#az-ams-asset-track-update) | 10 |  |   |
| [az ams asset-track update-data](https://docs.microsoft.com/cli/azure/ams/asset-track#az-ams-asset-track-update-data) | 7 |  |   |
| [az ams content-key-policy delete](https://docs.microsoft.com/cli/azure/ams/content-key-policy#az-ams-content-key-policy-delete) | 5 |  | 34 |
| [az ams content-key-policy option add](https://docs.microsoft.com/cli/azure/ams/content-key-policy/option#az-ams-content-key-policy-option-add) | 27 | **yes** | 6 |
| [az ams content-key-policy option remove](https://docs.microsoft.com/cli/azure/ams/content-key-policy/option#az-ams-content-key-policy-option-remove) | 6 |  | 6 |
| [az ams content-key-policy show](https://docs.microsoft.com/cli/azure/ams/content-key-policy#az-ams-content-key-policy-show) | 6 |  | 34 |
| [az ams job cancel](https://docs.microsoft.com/cli/azure/ams/job#az-ams-job-cancel) | 7 |  | 33 |
| [az ams job delete](https://docs.microsoft.com/cli/azure/ams/job#az-ams-job-delete) | 6 |  | 33 |
| [az ams job show](https://docs.microsoft.com/cli/azure/ams/job#az-ams-job-show) | 6 |  | 33 |
| [az ams job start](https://docs.microsoft.com/cli/azure/ams/job#az-ams-job-start) | 14 |  | 33 |
| [az ams job update](https://docs.microsoft.com/cli/azure/ams/job#az-ams-job-update) | 12 |  | 33 |
| [az ams live-event create](https://docs.microsoft.com/cli/azure/ams/live-event#az-ams-live-event-create) | 25 | **yes** | 11 |
| [az ams live-event delete](https://docs.microsoft.com/cli/azure/ams/live-event#az-ams-live-event-delete) | 5 |  | 11 |
| [az ams live-event reset](https://docs.microsoft.com/cli/azure/ams/live-event#az-ams-live-event-reset) | 6 |  | 11 |
| [az ams live-event show](https://docs.microsoft.com/cli/azure/ams/live-event#az-ams-live-event-show) | 5 |  | 11 |
| [az ams live-event standby](https://docs.microsoft.com/cli/azure/ams/live-event#az-ams-live-event-standby) | 6 |  | 11 |
| [az ams live-event start](https://docs.microsoft.com/cli/azure/ams/live-event#az-ams-live-event-start) | 6 |  | 11 |
| [az ams live-event stop](https://docs.microsoft.com/cli/azure/ams/live-event#az-ams-live-event-stop) | 7 |  | 11 |
| [az ams live-output create](https://docs.microsoft.com/cli/azure/ams/live-output#az-ams-live-output-create) | 10 | **yes** | 63 |
| [az ams live-output delete](https://docs.microsoft.com/cli/azure/ams/live-output#az-ams-live-output-delete) | 6 |  | 63 |
| [az ams live-output list](https://docs.microsoft.com/cli/azure/ams/live-output#az-ams-live-output-list) | 3 |  | 63 |
| [az ams live-output show](https://docs.microsoft.com/cli/azure/ams/live-output#az-ams-live-output-show) | 6 |  | 63 |
| [az ams streaming-endpoint akamai add](https://docs.microsoft.com/cli/azure/ams/streaming-endpoint/akamai#az-ams-streaming-endpoint-akamai-add) | 8 | **yes** | 13 |
| [az ams streaming-endpoint akamai remove](https://docs.microsoft.com/cli/azure/ams/streaming-endpoint/akamai#az-ams-streaming-endpoint-akamai-remove) | 6 |  | 13 |
| [az ams streaming-endpoint create](https://docs.microsoft.com/cli/azure/ams/streaming-endpoint#az-ams-streaming-endpoint-create) | 16 | **yes** | 50 |
| [az ams streaming-endpoint delete](https://docs.microsoft.com/cli/azure/ams/streaming-endpoint#az-ams-streaming-endpoint-delete) | 5 |  | 50 |
| [az ams streaming-endpoint get-skus](https://docs.microsoft.com/cli/azure/ams/streaming-endpoint#az-ams-streaming-endpoint-get-skus) | 5 |  | 50 |
| [az ams streaming-endpoint list](https://docs.microsoft.com/cli/azure/ams/streaming-endpoint#az-ams-streaming-endpoint-list) | 2 |  | 50 |
| [az ams streaming-endpoint scale](https://docs.microsoft.com/cli/azure/ams/streaming-endpoint#az-ams-streaming-endpoint-scale) | 6 |  | 50 |
| [az ams streaming-endpoint show](https://docs.microsoft.com/cli/azure/ams/streaming-endpoint#az-ams-streaming-endpoint-show) | 5 |  | 50 |
| [az ams streaming-endpoint start](https://docs.microsoft.com/cli/azure/ams/streaming-endpoint#az-ams-streaming-endpoint-start) | 6 |  | 50 |
| [az ams streaming-endpoint stop](https://docs.microsoft.com/cli/azure/ams/streaming-endpoint#az-ams-streaming-endpoint-stop) | 6 |  | 50 |
| [az ams streaming-endpoint update](https://docs.microsoft.com/cli/azure/ams/streaming-endpoint#az-ams-streaming-endpoint-update) | 20 |  | 50 |
| [az ams streaming-locator create](https://docs.microsoft.com/cli/azure/ams/streaming-locator#az-ams-streaming-locator-create) | 12 | **yes** | 117 |
| [az ams streaming-locator delete](https://docs.microsoft.com/cli/azure/ams/streaming-locator#az-ams-streaming-locator-delete) | 5 |  | 117 |
| [az ams streaming-locator get-paths](https://docs.microsoft.com/cli/azure/ams/streaming-locator#az-ams-streaming-locator-get-paths) | 5 |  | 117 |
| [az ams streaming-locator list](https://docs.microsoft.com/cli/azure/ams/streaming-locator#az-ams-streaming-locator-list) | 5 |  | 117 |
| [az ams streaming-locator list-content-keys](https://docs.microsoft.com/cli/azure/ams/streaming-locator#az-ams-streaming-locator-list-content-keys) | 5 |  | 117 |
| [az ams streaming-locator show](https://docs.microsoft.com/cli/azure/ams/streaming-locator#az-ams-streaming-locator-show) | 5 |  | 117 |
| [az ams streaming-policy create](https://docs.microsoft.com/cli/azure/ams/streaming-policy#az-ams-streaming-policy-create) | 28 | **yes** | 22 |
| [az ams streaming-policy delete](https://docs.microsoft.com/cli/azure/ams/streaming-policy#az-ams-streaming-policy-delete) | 5 |  | 22 |
| [az ams streaming-policy list](https://docs.microsoft.com/cli/azure/ams/streaming-policy#az-ams-streaming-policy-list) | 5 |  | 22 |
| [az ams streaming-policy show](https://docs.microsoft.com/cli/azure/ams/streaming-policy#az-ams-streaming-policy-show) | 5 |  | 22 |
| [az ams transform delete](https://docs.microsoft.com/cli/azure/ams/transform#az-ams-transform-delete) | 0 |  | 35 |
| [az ams transform list](https://docs.microsoft.com/cli/azure/ams/transform#az-ams-transform-list) | 4 |  | 35 |
| [az ams transform show](https://docs.microsoft.com/cli/azure/ams/transform#az-ams-transform-show) | 5 |  | 35 |

### Related command

az ams

### Errors

n/a

### Issue script & Debug output

n/a

### Expected behavior

n/a

### Environment Summary

Azure CLI 2.63.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by akucer** [comment]
Closing as won't fix as Azure Media Services was retired on 6/30/2024 (https://aka-ms/ams-retirement)

**Comment by akucer** [comment]
Closing

**Comment by akucer** [comment]
@dbradish-microsoft - The GA status is not correct. It should be marked as deprecated.
