### ISSUE TITLE
az vm list -g MyGroup -d gives error on 'chunked data'

### ISSUE THREAD

**Issue by Teodelas** [Azure/azure-cli#2968]
az 2.0.3

az vm list -g MyGroup -d gives error:
```
msrest.http_logger : Body contains chunked data.
sequence item 1: expected string or Unicode, NoneType found
Traceback (most recent call last):
  File "/home/teodelas/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/home/teodelas/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 201, in execute
```

**Comment by derekbekoe** [comment]
A few questions:
- What version of Python? (this well be in `az --version`)
- What OS and version?
- What shell are you using?

- Was the command run against an Azure Stack instance (as opposed to Public Azure)?

**Comment by Teodelas** [comment]
Python (Linux) 2.7.6 (default, Oct 26 2016, 20:30:19)

Windows 10 

Bash on Windows

Ran command against Public Azure

**Comment by Teodelas** [comment]
I installed AZ 2.0.3 and Python 3.5.2 on Windows and also get the same error.

**Comment by tjprescott** [comment]
Can you run regular VM list (without `-d`)?

**Comment by Teodelas** [comment]
Yes.

**Comment by yugangw-msft** [comment]
Please reactivate if you are still able to reproduce it. Do mention the version and how you installed the CLI.
