### ISSUE TITLE
azure-cli not working on macOS Sierra

### ISSUE THREAD

**Issue by lutzroeder** [Azure/azure-cli#2969]
### Environment summary

**Install Method:**
sudo pip install azure-cli

**CLI Version:**
az version doesn't run because of error below.
azure-cli 2.0.3

**OS Version:**
macOS Sierra 10.12.4 16E195

**Shell Type:**
Bash

---

### Description
After a blank install either "sudo pip install azure-cli" or using "curl -L https://aka.ms/InstallAzureCli | bash" running az shows the following error:
```
~/Desktop: az
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/azure/cli/__main__.py", line 9, in <module>
    import azure.cli.main
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/azure/cli/main.py", line 12, in <module>
    from azure.cli.core.util import (show_version_info_exit, handle_exception)
ImportError: No module named util
~/Desktop: 
```

**Comment by derekbekoe** [comment]
Since you installed with multiple methods, can you run `which az` to check which one is running?
Also, if you installed with curl, it should be available at `~/bin/az`. Does that work?

**Comment by lutzroeder** [comment]
both /usr/local/bin/az and ~/Library/azure-cli/bin/az (used a different directory as the default is polluting ~/ on macOS) show the same error.

~/Desktop: which az
/usr/local/bin/az

**Comment by derekbekoe** [comment]
Looking like you have version mismatches that's why you get a `ImportError: No module named util`.

What did you mean by "used a different directory as the default is polluting ~/ on macOS"? Did you change the default install location?

Also, how about the output of `cat $(which az)`?
Also, `pip freeze | grep azure-cli`?
Also, `~/lib/azure-cli/bin/pip freeze | grep azure-cli`?

**Comment by lutzroeder** [comment]
I used attached script to `pip uninstall` all packages starting with `azure-cli-*`. After that running `sudo -H pip install azure-cli` made things work again. Looks like a likely cause is that updating azure-cli via pip from a previous package leaves mismatching versions. Uninstalling the `azure-cli` package leaves the other packages around.

Regarding your other question: Not a big fan of running the curl bash installer and dropping the files into the ~/ folder so yes different directory means changing the default install location. However, apt-get, brew and pip support is preferable and back to using the pip version now. Also wondering why it has so many separate pip packages.

[uninstall-azure-cli.txt](https://github.com/Azure/azure-cli/files/952761/uninstall-azure-cli.txt)

**Comment by derekbekoe** [comment]
Yes you have to uninstall each package individually if you want to uninstall. The command below achieves this.
`pip uninstall -y $(pip freeze | grep azure-cli-) && pip uninstall -y azure-cli`

There are separate pip packages for the different components inside the CLI.

Can this issue be closed?

**Comment by lutzroeder** [comment]
My problem is resolved. However, the pip uninstall and update experience is not very intuitive and wonder if there should be a work item to improve this. The fact that simply running an update got me into this state make me wonder if there is some underlying build/update issue that needs to be addressed.

**Comment by derekbekoe** [comment]
Upgrade: `pip install --upgrade azure-cli`
This upgrade command does upgrade the main CLI package and all azure-cli-* as well.

Now running `pip install azure-cli==VERSION` would not work as expected as all the azure-cli-* packages would not be updated by pip in this scenario.

Currently, we treat the `pip` install scenarios as more advanced.

**Comment by sasukeh** [comment]
I really recommend to use python virtual environment. 

'''
pip install --user virtualenv
mkdir azure-cli
cd azure-cli
virtualenv .
source bin/activate
pip install --user azure-cli
'''

**Comment by derekbekoe** [comment]
Thanks for the comment @sasukeh.
Would recommend a virtual environment as suggested or installing with `--user`.

Closing issue.
