### ISSUE TITLE
Azure Database for PostgreSQL Flexible Server failed to deploy

### ISSUE THREAD

**Issue by abhinavthula** [Azure/azure-cli#29708]
### Describe the bug

We are deploying the Azure Database for PostgreSQL Flexible Server with CMK enabled in the Qatar Central Region but it is failing with the following error.

Status: "InternalServerError"
│ Code: ""
│ Message: "An unexpected error occured while processing the request. Tracking ID: '21f509fd-b7bf-4181-96f6-cfd4b821cc67'"
│ Activity Id: ""
│ 
│ ---
│ 
│ API Response:
│ 
│ ----[start]----
│ {"name":"1994465b-794a-4708-8519-3fb4fcf1c386","status":"Failed","startTime":"2024-08-11T16:24:11.783Z","error":{"code":"InternalServerError","message":"An unexpected error occured while processing the request. Tracking ID: '21f509fd-b7bf-4181-96f6-cfd4b821cc67'"}}
│ -----[end]-----
│ 

### Related command

I’m deploying it through Azure DevOps Pipeline using Terraform

### Errors

Status: "InternalServerError"
│ Code: ""
│ Message: "An unexpected error occured while processing the request. Tracking ID: '21f509fd-b7bf-4181-96f6-cfd4b821cc67'"
│ Activity Id: ""
│ 
│ ---
│ 
│ API Response:
│ 
│ ----[start]----
│ {"name":"1994465b-794a-4708-8519-3fb4fcf1c386","status":"Failed","startTime":"2024-08-11T16:24:11.783Z","error":{"code":"InternalServerError","message":"An unexpected error occured while processing the request. Tracking ID: '21f509fd-b7bf-4181-96f6-cfd4b821cc67'"}}
│ -----[end]-----
│ 

### Issue script & Debug output

Status: "InternalServerError"
│ Code: ""
│ Message: "An unexpected error occured while processing the request. Tracking ID: '21f509fd-b7bf-4181-96f6-cfd4b821cc67'"
│ Activity Id: ""
│ 
│ ---
│ 
│ API Response:
│ 
│ ----[start]----
│ {"name":"1994465b-794a-4708-8519-3fb4fcf1c386","status":"Failed","startTime":"2024-08-11T16:24:11.783Z","error":{"code":"InternalServerError","message":"An unexpected error occured while processing the request. Tracking ID: '21f509fd-b7bf-4181-96f6-cfd4b821cc67'"}}
│ -----[end]-----
│ 

### Expected behavior

It should be deployed without any issues

### Environment Summary

Everything with latest versions

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by gbowerman** [comment]
@abhinavthula 
- Does this problem repro in Azure CLI? 
- Does this problem repro in Terraform (outside of Azure DevOps pipeline)
- Can you share the exact steps to repro the problem?
- Have you logged a support call for this?

**Comment by abhinavthula** [comment]
Hi, 

After adding one rule in the route table, the deployment is ok however, I'm unable to add the microsoft entra admin group for my postgresql flexible server.

Yes, I raised the support request but there is no update

Getting the below error.

 Error: creating Administrator (Subscription: "97d138e4-98c0-4831-XXXXXXXXXXXXXX"
│ Resource Group Name: "rg-qc-jXXXXXXXXXXXXXXXXX"
│ Flexible Server Name: "psql-XXXXXXXXXX"
│ Object: "ffdb00a8-a69a-4fa6-9f17-e8a8e8a2875d"): polling after Create: polling failed: the Azure API returned the following error:
│ 
│ Status: "AadAuthPrincipalCreationFailed"
│ Code: ""
│ Message: "Failed to create Azure AD Principal. Reason - 0LP01: An unexpected error occurred while trying to validate user."
│ Activity Id: ""
│ 
│ ---
│ 
│ API Response:
│ 
│ ----[start]----
│ {"name":"a7c71edc-1407-449b-9806-6694c5476eea","status":"Failed","startTime":"2024-08-13T10:39:05.593Z","error":{"code":"AadAuthPrincipalCreationFailed","message":"Failed to create Azure AD Principal. Reason - 0LP01: An unexpected error occurred while trying to validate user."}}
│ -----[end]-----
│

**Comment by nachoalonsoportillo** [comment]
@abhinavthula Have you made sure your instance meets the requirements described here? https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-configure-sign-in-azure-ad-authentication#prerequisites

That error you're seeing typically happens when you have a firewall or Network Security Group configured in your VNET's subnet delegated to Microsoft.DBforPostgreSQL/flexibleServer and it is blocking outbound traffic to AzureActiveDirectory.

BTW, because this is not an Azure CLI module issue, I'll be closing this Azure CLI issue. If my suggestion above doesn't resolve the problem, please work with our support services to resolve it, as @gbowerman suggested. Thanks!

**Comment by abhinavthula** [comment]
Hi @nachoalonsoportillo ,

Yes, that is already in place.

![image](https://github.com/user-attachments/assets/8233969f-6c5a-4bc3-aa68-25ecdd3efde6).

**Comment by abhinavthula** [comment]
@gbowerman , I'm deploying the postgresql flexible server using terraform scripts via devops pipeline. Initially I have issues deploying the server but that is resolved and now, I'm not able to set the entra admin group for the sql server. (This is also from terraform)

Getting the below error.

Error: creating Administrator (Subscription: "97d138e4-98c0-4831-XXXXXXXXXXXXXX"
│ Resource Group Name: "rg-qc-jXXXXXXXXXXXXXXXXX"
│ Flexible Server Name: "psql-XXXXXXXXXX"
│ Object: "ffdb00a8-a69a-4fa6-9f17-e8a8e8a2875d"): polling after Create: polling failed: the Azure API returned the following error:
│
│ Status: "AadAuthPrincipalCreationFailed"
│ Code: ""
│ Message: "Failed to create Azure AD Principal. Reason - 0LP01: An unexpected error occurred while trying to validate user."
│ Activity Id: ""
│
│ ---
│
│ API Response:
│
│ ----[start]----
│ {"name":"a7c71edc-1407-449b-9806-6694c5476eea","status":"Failed","startTime":"2024-08-13T10:39:05.593Z","error":{"code":"AadAuthPrincipalCreationFailed","message":"Failed to create Azure AD Principal. Reason - 0LP01: An unexpected error occurred while trying to validate user."}}
│ -----[end]-----
│

**Comment by gbowerman** [comment]
@abhinavthula this doesn't appear to be related to Azure CLI.
