### ISSUE TITLE
Azure CLI "az containerapp logs show" - retruns malformed JSON

### ISSUE THREAD

**Issue by S7uX** [Azure/azure-cli#29711]
### Describe the bug

`"` is not escaped

example Output:
```
{"TimeStamp":"2024-08-13T11:17:18.5785844Z","Log":"DEBUG   [16:46:37] -  urllib3.connectionpool (connectionpool _make_request 546) -
https://kv-baz.azure.net:443 "GET /secrets/foobar/?api-version=7.5 HTTP/11" 401 97"}
```

### Related command

az containerapp logs show --type console --name foo --resource-group bar

### Errors

With `az containerapp logs show --type console --name foo --resource-group bar | ConvertFrom-Json | Select-Object -ExpandProperty Log`

I get:
`ConvertFrom-Json : Ein ungültiges Objekt wurde übergeben. Erwartet wurde ":" oder "}". (189): {<MALFORMED JSON>}`

### Issue script & Debug output

`cli.azure.cli.command_modules.containerapp.custom: received raw log line: b'{"TimeStamp":"2024-08-13T11:31:22.2964236Z","Log":"DEBUG   [16:46:38] -  urllib3.connectionpool (connectionpool _make_request 546) -  https://kv-foo.vault.azure.net:443 \\u0022GET /secrets/bar/?api-version=7.5 HTTP/11\\u0022 200 3351"}'`

### Expected behavior

escaped `"` --> well formed JSON

### Environment Summary

```
azure-cli                         2.63.0

core                              2.63.0
telemetry                          1.1.0

Dependencies:
msal                              1.30.0
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\foo\.azure\cliextensions'

Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by Greedygre** [comment]
Thanks for reporting this issue, I will take a look.

**Comment by Greedygre** [comment]
Hi @S7uX 
We are investigating this issue.
For workaround, you can use text format as following:
`az containerapp logs show --type console --name foo --resource-group bar --format text`
