### ISSUE TITLE
az storage account or-policy create --policy with json file exception

### ISSUE THREAD

**Issue by harrchen88** [Azure/azure-cli#29725]
### Describe the bug

According to documentation, https://learn.microsoft.com/en-us/cli/azure/storage/account/or-policy?view=azure-cli-latest#az-storage-account-or-policy-create, I should be able to create OR policy with json file.  However, that doesn't work for me.  It errors with exceptions of:
AttributeError: 'dict' object has no attribute 'source_account'.
and The value 'default' is not allowed for property policyId.

The command I used is: az storage account or-policy create -g rgadflab -n harrchenmsdnsasource1 --policy @objectreplicationpolicy.json --debug.

Attached is the objectreplicationpolicy.json and debug output.
[objectreplicationpolicy.json](https://github.com/user-attachments/files/16636721/objectreplicationpolicy.json)
[orpolicy debug.txt](https://github.com/user-attachments/files/16636723/orpolicy.debug.txt)

### Related command

az storage account or-policy create -g rgadflab -n harrchenmsdnsasource1 --policy @objectreplicationpolicy.json --debug

### Errors

AttributeError: 'dict' object has no attribute 'source_account'.
and The value 'default' is not allowed for property policyId.
Debug output: [orpolicy debug.txt](https://github.com/user-attachments/files/16636723/orpolicy.debug.txt)

### Issue script & Debug output

[orpolicy debug.txt](https://github.com/user-attachments/files/16636723/orpolicy.debug.txt)

### Expected behavior

Policy created as defined by the policy json file

### Environment Summary

azure-cli                         2.63.0

core                              2.63.0
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
datafactory                        1.0.2
ml                                2.28.0
ssh                                2.0.5

Dependencies:
msal                              1.30.0
azure-mgmt-resource               23.1.1

Python location '/usr/bin/python3.9'
Extensions directory '/home/harry/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.19 (main, Jul 31 2024, 03:47:41) 
[GCC 11.2.0]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by harrchen88** [comment]
Actually, this json file worked with this command:
az storage account or-policy create -g rgadflab -n harrchenmsdnsatarget1 --policy @or1.json

{
  "policyId": "default",
  "sourceAccount": "/subscriptions/b7c12d9f-e21b-4abe-9377-aafff5a79f00/resourceGroups/rgadflab/providers/Microsoft.Storage/storageAccounts/harrchenmsdnsasource1",
  "destinationAccount": "/subscriptions/b7c12d9f-e21b-4abe-9377-aafff5a79f00/resourceGroups/rgadflab/providers/Microsoft.Storage/storageAccounts/harrchenmsdnsatarget1",
  "rules": [
    {   
      "sourceContainer": "sourceor1",
      "destinationContainer": "targetor1",
      "filters": {
        "minCreationTime": "1601-01-01T00:00:00Z",
        "prefixMatch": null
      }
    },
    {
      "destinationContainer": "targetor2",
      "filters": null,
      "sourceContainer": "sourceor2"
    }
  ]
  }
