### ISSUE TITLE
Azure Language copy via az cli

### ISSUE THREAD

**Issue by mwarqee** [Azure/azure-cli#29720]
### Describe the bug

While executing in az cli VS Code

`curl.exe --request POST   --url 'https://aclu.cognitiveservices.azure.com//language/authoring/analyze-conversations/projects/TestCopy/:authorize-copy?api-version=2023-04-15-preview'   --header 'Content-Type: application/json'   --header 'Ocp-Apim-Subscription-Key: 230498wefuie81749378asdfoi23d69e9512'   --data '{"projectKind":"Conversation","allowOverwrite":false}'`

The following error is obtained

`{"error":{"code":"InvalidArgument","message":"Failed to parse the input.","details":[{"code":"InvalidArgument","message":"Unexpected character encountered while parsing value: C. Path 'projectKind', line 1, position 13.","target":"projectKind"},{"code":"InvalidArgument","message":"Unexpected character encountered while parsing value: C. Path 'projectKind', line 1, position 13.","target":"projectKind"}]}}`

However as described in https://learn.microsoft.com/en-us/azure/ai-services/language-service/conversational-language-understanding/concepts/best-practices#copy-projects-across-language-resources
I am using the correct project type for CLU - **analyze-conversations**

### Related command

curl.exe --request POST   --url 'https://aclu.cognitiveservices.azure.com//language/authoring/analyze-conversations/projects/TestCopy/:authorize-copy?api-version=2023-04-15-preview'   --header 'Content-Type: application/json'   --header 'Ocp-Apim-Subscription-Key: 230498wefuie81749378asdfoi23d69e9512'   --data '{"projectKind":"Conversation","allowOverwrite":false}'

### Errors

{"error":{"code":"InvalidArgument","message":"Failed to parse the input.","details":[{"code":"InvalidArgument","message":"Unexpected character encountered while parsing value: C. Path 'projectKind', line 1, position 13.","target":"projectKind"},{"code":"InvalidArgument","message":"Unexpected character encountered while parsing value: C. Path 'projectKind', line 1, position 13.","target":"projectKind"}]}}

### Issue script & Debug output

None available

### Expected behavior

I expected to actually work, or provide a more precise indication of the error itself.

### Environment Summary

azure-cli                         2.63.0

core                              2.63.0
telemetry                          1.1.0

Dependencies:
msal                              1.30.0
azure-mgmt-resource               23.1.1

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yonzhan** [comment]
Which CLI command is it related to?

**Comment by mwarqee** [comment]
I think this is more an azure language issue so will refer it to the proper team.
