### ISSUE TITLE
az functionapp config set --resource-group some-rg --name some-functionapp --vnet-route-all-enabled false

### ISSUE THREAD

**Issue by noelleheerinkwijnja** [Azure/azure-cli#29733]
### Describe the bug

executing below command:
az functionapp config set –vnet-route-all-enabled 

returns error: the data is not valid (ftpsState

### Related command

functionapp config set --resource-group 'some-rg' --name 'some-functionapp' --vnet-route-all-enabled false/true

### Errors

az functionapp config set --resource-group some-rg --name some-functionapp --vnet-route-all-enabled false

The data is not valid (ftpsState).

### Issue script & Debug output

cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/subscriptionId/resourceGroups/some-rg/providers/Microsoft.Web/sites/some-functionapp/config/web?api-version=2023-01-01'
cli.azure.cli.core.sdk.policies: Request method: 'PATCH'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '1470'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '4085b434-5e0d-11ef-91f7-7404f1452738'
cli.azure.cli.core.sdk.policies:     'CommandName': 'functionapp config set'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--resource-group --name --vnet-route-all-enabled --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.63.0 (MSI) azsdk-python-core/1.28.0 Python/3.11.8 (Windows-10-10.0.22631-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: {"properties": {"numberOfWorkers": 1, "defaultDocuments": ["Default.htm", "Default.html", "Default.asp", "index.htm", "index.html", "iisstart.htm", "default.aspx", "index.php"], "netFrameworkVersion": "v8.0", "phpVersion": "", "pythonVersion": "", "nodeVersion": "", "powerShellVersion": "", "linuxFxVersion": "", "requestTracingEnabled": false, "remoteDebuggingEnabled": false, "remoteDebuggingVersion": "VS2022", "httpLoggingEnabled": false, "acrUseManagedIdentityCreds": false, "logsDirectorySizeLimit": 35, "detailedErrorLoggingEnabled": false, "publishingUsername": "REDACTED", "scmType": "None", "use32BitWorkerProcess": false, "webSocketsEnabled": false, "alwaysOn": true, "appCommandLine": "", "managedPipelineMode": "Integrated", "virtualApplications": [{"virtualPath": "/", "physicalPath": "site\\wwwroot", "preloadEnabled": true}], "loadBalancing": "LeastRequests", "experiments": {"rampUpRules": []}, "autoHealEnabled": false, "vnetName": "", "vnetRouteAllEnabled": false, "vnetPrivatePortsCount": 0, "cors": {"allowedOrigins": ["https://portal.azure.com"], "supportCredentials": false}, "localMySqlEnabled": false, "scmIpSecurityRestrictionsUseMain": false, "http20Enabled": false, "minTlsVersion": "1.2", "scmMinTlsVersion": "1.2", "ftpsState": "false", "preWarmedInstanceCount": 0, "functionAppScaleLimit": 0, "functionsRuntimeScaleMonitoringEnabled": false, "minimumElasticInstanceCount": 0, "azureStorageAccounts": {}, "publicNetworkAccess": "Enabled"}}
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PATCH /subscriptions/subscriptionId/resourceGroups/some-rg/providers/Microsoft.Web/sites/some-functionapp/config/web?api-version=2023-01-01 HTTP/1.1" 400 367
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '367'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'ETag': '"1DAF216DAB9DB6B"'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'X-AspNet-Version': '4.0.30319'
cli.azure.cli.core.sdk.policies:     'X-Powered-By': 'ASP.NET'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '199'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-global-writes': '2999'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': 'fee3d60c-ee42-4421-bef1-3c30ea1c6b7a'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': 'fee3d60c-ee42-4421-bef1-3c30ea1c6b7a'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'WESTEUROPE:20240819T092730Z:fee3d60c-ee42-4421-bef1-3c30ea1c6b7a'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'X-Cache': 'CONFIG_NOCACHE'
cli.azure.cli.core.sdk.policies:     'X-MSEdge-Ref': 'Ref A: 622BCD2C6D65477193CE193D3CFD0539 Ref B: AMS231032607007 Ref C: 2024-08-19T09:27:28Z'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 19 Aug 2024 09:27:30 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"Code":"BadRequest","Message":"The data is not valid (ftpsState).","Target":null,"Details":[{"Message":"The data is not valid (ftpsState)."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"01019","MessageTemplate":"The data is not valid ({0}).","Parameters":["ftpsState"],"Code":"BadRequest","Message":"The data is not valid (ftpsState)."}}],"Innererror":null}
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 701, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 334, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 2303, in update_site_configs_functionapp
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 1909, in update_site_configs
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/_appservice_utils.py", line 21, in _generic_site_operation
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/mgmt/web/v2023_01_01/operations/_web_apps_operations.py", line 21870, in update_configuration
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'
Content: {"Code":"BadRequest","Message":"The data is not valid (ftpsState).","Target":null,"Details":[{"Message":"The data is not valid (ftpsState)."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"01019","MessageTemplate":"The data is not valid ({0}).","Parameters":["ftpsState"],"Code":"BadRequest","Message":"The data is not valid (ftpsState)."}}],"Innererror":null}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 664, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 723, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/commands.py", line 46, in _ex_handler
knack.util.CLIError: The data is not valid (ftpsState).

cli.azure.cli.core.azclierror: The data is not valid (ftpsState).
az_command_data_logger: The data is not valid (ftpsState).
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03C3A938>]

### Expected behavior

az functionapp config set --resource-group some-rg --name some-functionapp --vnet-route-all-enabled false
setting the vnet integration for route all accordingly

### Environment Summary

az --version

azure-cli                         2.63.0

core                              2.63.0
telemetry                          1.1.0

Extensions:
account                            0.2.5
aks-preview                      7.0.0b6
amg                                2.1.0
azure-firewall                     1.2.0
bastion                            1.1.0
containerapp                      0.3.54
interactive                        0.5.3
resource-graph                     2.1.0
ssh                                2.0.5

Dependencies:
msal                              1.30.0
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\<username>\.azure\cliextensions'
Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 21:52:07) [MSC v.1937 32 bit (Intel)]

### Additional context

.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
