### ISSUE TITLE
{afd} --enable-private-link default has been inverted when creating an origin

### ISSUE THREAD

**Issue by the-Jamz** [Azure/azure-cli#29753]
### Describe the bug

Running `az afd origin create` used to default the parameter `--enable-private-link`  to `false` but now it defaults to `true`, leading to the error:
 ```
 (BadRequest) Property 'AfdOrigin.SharedPrivateLinkResource.PrivateLink.Id' is required but it was not set;
Property 'AfdOrigin.SharedPrivateLinkResource.RequestMessage' is required but it was not set
Code: BadRequest
Message: Property 'AfdOrigin.SharedPrivateLinkResource.PrivateLink.Id' is required but it was not set;
Property 'AfdOrigin.SharedPrivateLinkResource.RequestMessage' is required but it was not set
```

This bug seems to have been introduced by #29427 and this issue has been mentioned in #29406

### Related command

 `az afd origin create`

### Errors

 ```
 (BadRequest) Property 'AfdOrigin.SharedPrivateLinkResource.PrivateLink.Id' is required but it was not set;
Property 'AfdOrigin.SharedPrivateLinkResource.RequestMessage' is required but it was not set
Code: BadRequest
Message: Property 'AfdOrigin.SharedPrivateLinkResource.PrivateLink.Id' is required but it was not set;
Property 'AfdOrigin.SharedPrivateLinkResource.RequestMessage' is required but it was not set
```

### Issue script & Debug output

```
az afd origin create --resource-group [rgp] --host-name [hostname] --profile-name [profilename] --origin-group-name [origingroupname] --origin-name [originname] --origin-host-header [originhostheader] --priority 1 --weight 1000 --enabled-state Enabled --http-port 80 --https-port 443
```

### Expected behavior

The origin should be created without needing the specify the `--enable-private-link` argument.

### Environment Summary

azure-cli                         2.63.0

core                              2.63.0
telemetry                          1.1.0

Extensions:
front-door                         1.2.0

Dependencies:
msal                              1.30.0
azure-mgmt-resource               23.1.1
Python (Linux) 3.11.8 (main, Jul 31 2024, 03:39:39) [GCC 11.4.0]

### Workaround

As a temporary workaround, `--enable-private-link false` can be manually specified when creating origins.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
