### ISSUE TITLE
[PREVIEW TAG] AZ Capacity reservation

### ISSUE THREAD

**Issue by geraldo29** [Azure/azure-cli#29757]
### Describe the bug

1) We have the preview tag attached to this cli command in learn / documentation
2) when using az capacity reservation group it says: Command group 'capacity reservation group' is in preview and under development. reference and support levels: https://aka.ms/cli_refstatus

Please remove any reference to Preview for capacity reservation as we have been in GA already for a long time.

<img width="422" alt="tag2" src="https://github.com/user-attachments/assets/5024bd99-f3ff-49a5-9895-025d7477d9d8">
<img width="565" alt="tag" src="https://github.com/user-attachments/assets/c141328d-2248-4481-b7d1-051b253c5fe5">

### Related command

az capacity reservation
az capacity reservation group 

### Errors

Command group 'capacity reservation group' is in preview and under development. reference and support levels: https://aka.ms/cli_refstatus

### Issue script & Debug output

Command group 'capacity reservation group' is in preview and under development. reference and support levels: https://aka.ms/cli_refstatus

### Expected behavior

No warning that says that we are still in preview and not Tag in documentation website specifying we are in preview.

### Environment Summary

azure-cli latest version

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
