### ISSUE TITLE
Customer feedback | az afd endpoint | need JSON example for `--domains` parameter

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#29801]
### Feedback category
Need more information

### Reference command
az afd endpoint purge --domains

### Summary
From Learn Customer Feedback, a customer is requesting more information on the `--domains` parameter. The sentence `Support shorthand-syntax, json-file and yaml-file. Try "??" to show more.` appears over 5,337 times in our autogenerated content.  The lack of a JSON or shorthand-syntax example generates recurring customer complaints.  See GitHub issue [29479](https://github.com/Azure/azure-cli/issues/29479).

### Request
* Add an example that includes multiple domain values for the `--domains` parameter

### Doc link
https://learn.microsoft.com/en-us/cli/azure/afd/endpoint

### Customer feedback
"
Please add information on how to add multiple domains to the '--domains' parameter.
"

### Related command

az afd endpoint purge

### Errors

n/a

### Issue script & Debug output

n/a

### Expected behavior

n/a

### Environment Summary

Azure CLI 2.63.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
