### ISSUE TITLE
Expose ImageDeprecationStatus Property in Virtual Machine Image list cmdlet

### ISSUE THREAD

**Issue by nidhjain-ms1** [Azure/azure-cli#29819]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

`az vm image list`

### Resource Provider

Microsoft.Compute/ComputeRP

### Description of Feature or Work Requested

We want to expose `imageDeprecationStatus` property also in the above cmdlet. Currently, this cmdlet is calling REST API with this request url having `expand` param equals to `properties`:
https://management.azure.com/subscriptions/823ca539-d44d-43ee-8dc8-023fd4f27396/providers/Microsoft.Compute/locations/eastus/publishers/center-for-internet-security-inc/artifacttypes/vmimage/offers/cis-rocky/skus/cis-rockylinux-9-l1-gen2-azure-observability/versions?$expand=properties&api-version=2023-09-01 

We want it to call with this request url having `expand` param equals to `properties/imageDeprecationStatus`: 
https://management.azure.com/subscriptions/823ca539-d44d-43ee-8dc8-023fd4f27396/providers/Microsoft.Compute/locations/eastus/publishers/center-for-internet-security-inc/artifacttypes/vmimage/offers/cis-rocky/skus/cis-rockylinux-9-l1-gen2-azure-observability/versions?$expand=properties/imageDeprecationStatus&api-version=2023-09-01

The new request url will expose the imageDeprecationStatus property as well with this cmdlet.

### Minimum API Version Required

2022-11-01

### Swagger PR link / SDK link

- Link to the OpenAPI (swagger) spec

  -  https://github.com/RajalakshmiSwaminathan/azure-rest-api-specs/blob/e5f4f0f98ed6417790f8ea0db56b20a3f71dbeff/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2022-11-01/virtualMachineImage.json

- Link to any other Github work related to this request

  - Swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/21615
  - SDK PR: https://github.com/Azure/azure-sdk-for-net/pull/32660

### Request Example

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2022-11-01/virtualMachineImage.json

### Target Date

2024-09-30

### PM Contact

edewebolton@microsoft.com

### Engineer Contact

nidhjain@microsoft.com

### Additional context

This request is to just include one more property in list cmd. This change is of 0 risk because we are not removing any existing property but want to show one more property i.e 'imageDeprecationStatus'

**Comment by zhoxing-ms** [comment]
@nidhjain-ms1 May I ask if this feature request is related to security? Please note that currently, due to the CLI team being busy with the security wave and prioritizing security in this semester, so all the feature requests unrelated to security will be postponed. cc PM @Jacekey23

**Comment by nidhjain-ms1** [comment]
Hi @zhoxing-ms , this is not directly related to any particular security wave, but yes, it is related to security in a way that deprecated images may be end of life and insecure so allowing customers to easily find and exclude images that are deprecated/scheduled for deprecation would prevent them from using such images.

**Comment by zhoxing-ms** [comment]
@nidhjain-ms1 Sorry, due to our recent busy schedule, I am concerned that we may not have enough effort to do work outside of safety waves. But I understand that this feature is indirectly related to security. May I ask if this feature is urgent? If you can provide some business evidence, we will discuss with the PM @Jacekey23 whether to prioritize it

**Comment by ebolton-cyber** [comment]
@zhoxing-ms @Jacekey23 I am the PM for this feature. The business justification is that we want to ensure customers move away from images that are deprecated/scheduled for deprecation as these images might be End of life, lack security patches and pose security risks to Azure customers. A lot of customers have requested for a way to list and exclude images that not scheduled for deprecation or already deprecated via the CLI. This is why need the Image deprecation status parameter added to the az vm list command. I hope this explains it clearly. Let me know if you have any further questions

**Comment by nidhjain-ms1** [comment]
Hi @zhoxing-ms , can you please provide any updates/timelines for this issue. Please let me know, if any other information is required.

**Comment by zhoxing-ms** [comment]
@nidhjain-ms1 OK, we will plan this feature in this sprint, it will be released on 10-08

**Comment by nidhjain-ms1** [comment]
Hi @zhoxing-ms , would it be released on 10-08? I see in the PR, milestone to be mentioned as 11-05..

**Comment by zhoxing-ms** [comment]
@nidhjain-ms1 It should be released today
