### ISSUE TITLE
Azure devops variables are not updating

### ISSUE THREAD

**Issue by shehanGuruge** [Azure/azure-cli#29820]
### Describe the bug

I am trying to update the devops pipeline library variables through azure devops task via yaml. This is the code I have

```
- script: |
      echo "Updating variable group..."
      echo $(System.AccessToken) | az devops login --organization https://dev.azure.com/<org_name>
      echo "Logged in..."
      az devops project list -o jsonc
      az devops configure --defaults organization=https://dev.azure.com/<org_name>
      echo "Configured..."
      az pipelines variable-group list --top 6 --query-order Asc --output table --project "Test"
      echo "Listing success..."
      az pipelines variable-group variable update -p "Test" --group-id 2 --name version --value Test --output table
      echo "Update success..."
```

However,this code stops executing after `az devops project list -o jsonc` and the other echo commands are not visible in the log and none of the variables are getting updated. And worth to mention no errors as well. But if I run the same commands from my laptop terminal it works as expected. I am not sure what's wrong with this command. Any assist will be greatly appreciated.

### Related command

 az devops configure --defaults organization=https://dev.azure.com/<org_name>
 az pipelines variable-group list --top 6 --query-order Asc --output table --project "Test"
 az pipelines variable-group variable update -p "Test" --group-id 2 --name version --value Test --output table

### Errors

There are no errors

### Issue script & Debug output

No trace of anything apart from this output

```
"Updating variable group..."
"Logged in..."
{
  "continuationToken": null,
  "value": [
    {
      "abbreviation": null,
      "defaultTeamImageUrl": null,
      "description": "All coding projects for the $$$ Android platform.",
      "id": "c02d75df-27d9-46c7-8090-185c510d0627",
      "lastUpdateTime": "2024-04-30T08:39:06.483000+00:00",
      "name": "$$$",
      "revision": 85,
      "state": "wellFormed",
      "url": "[https://dev.azure.com/$$/_apis/projects/$$$",]
      "visibility": "private"
    }
  ]
}
Finishing: Update Variable Group in Azure DevOps Library
```

### Expected behavior

Should be able to update variables. Or at least a traceable error should be thrown

### Environment Summary

azure-cli                         2.63.0

core                              2.63.0
telemetry                          1.1.0

Extensions:
azure-devops                       1.0.1

Dependencies:
msal                              1.30.0
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Program Files\Common Files\AzureCliExtensionDirectory'

Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by shehanGuruge** [comment]
To anyone who encounter the issue, this code will help you. Adding this will be enough 
```
 - bash: |
              az pipelines variable-group variable update \
                --group-id 2 \
                --name version \
                --value Test \
                --organization 'https://dev.azure.com/<org-name>/' \
                --project <project-name> \
                --output table
            displayName: 'Update variable'
            env:
              AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
```
