### ISSUE TITLE
Integrate new disk attach/detach API in AzCLI

### ISSUE THREAD

**Issue by viveksingla08** [Azure/azure-cli#29841]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az vm disk attach
az vm disk detach

### Resource Provider

Microsoft.Compute/virtualmachines

### Description of Feature or Work Requested

CRP team has created a new Disk attach/detach API that customers can use to attach/detach disks to the VM. API to be used is already in public preview - [Virtual Machines - Attach Detach Data Disks - REST API (Azure Compute) | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/attach-detach-data-disks?view=rest-compute-2024-03-01&tabs=HTTP)

Change required in Azcli commands:

1. az vm disk attach - Introduce a new field --disk-ids. Customers can mention multiple disk ids after this and the API will attach all of them. Sample usage :

 ```
 az vm disk attach --disk-ids <disk uri> 
  [--caching {None, ReadOnly, ReadWrite}]
  [--enable-write-accelerator]<- supported
  [--lun]<- supported
  [--resource-group]
  [--subscription
```

2. az vm disk detach - Introduce a new field --disk-ids. Customers can mention multiple disk ids after this and the API will attach all of them. Sample usage :

```
az vm disk detach [--name] 
                  --resource-group
                  --vm-name
                  [--force-detach] 
                  [--disk-ids] <- new param
```

### Minimum API Version Required

2024-03-01

### Swagger PR link / SDK link

https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/attach-detach-data-disks?view=rest-compute-2024-03-01&tabs=HTTP

### Target Date

2024-11-30

### PM Contact

viveksingla

### Engineer Contact

nij, abver

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by zhoxing-ms** [comment]
@viveksingla08 May I ask if this feature request is related to security? Please note that currently, due to the CLI team being busy with the security wave and prioritizing security in this semester, so all the feature requests unrelated to security will be postponed. cc PM @Jacekey23

**Comment by viveksingla08** [comment]
This is related to the quality. This API would reduce the throttling faced by customers when trying to attach/detach disks

**Comment by zhoxing-ms** [comment]
@viveksingla08 Since security is still the no.1 top things to catch up within Azure. but CLI will be in continous planning manner. If things can be justify as highly customer impact. please send the justification and we'll take it into consideration.
