### ISSUE TITLE
Add support for Azure Firewall Byopip feature

### ISSUE THREAD

**Issue by udit1402** [Azure/azure-cli#29854]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

The powershell of the feature has been done, and Az Cli is remaining and we need that to be done as part of our Public Preview of the feature 

### Resource Provider

Microsoft.Network/azureFirewall

### Description of Feature or Work Requested

We just need a support to provide a functionality for the feature that we added to Powershell. The powershell PRs are as follows:
https://github.com/Azure/azure-powershell/pull/25385
https://github.com/Azure/azure-powershell/pull/24501

### Minimum API Version Required

2020-05-01

### Swagger PR link / SDK link

https://github.com/Azure/azure-powershell/pull/25385
https://github.com/Azure/azure-powershell/pull/24501

### Target Date

2024-10-01

### PM Contact

GOPIKANN

### Engineer Contact

UDITMISRA

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
