### ISSUE TITLE
tar package not available in azure-cli latest image

### ISSUE THREAD

**Issue by rajharini** [Azure/azure-cli#29857]
### Describe the bug

I make use of mcr.microsoft.com/azure-cli:latest image for the jobs in my k8s cluster. Upto two days ago all of the jobs were running successfully. But from yesterday, it seems like tar package is missing
![image](https://github.com/user-attachments/assets/b9bec671-eaa8-47fc-88ed-d3882b662cff)

Is this an intentional change to the latest tag?

### Related command

.

### Errors

.

### Issue script & Debug output

.

### Expected behavior

.

### Environment Summary

azure-cli                         2.64.0

core                              2.64.0
telemetry                          1.1.0

Dependencies:
msal                              1.30.0
azure-mgmt-resource               23.1.1

Python location '/usr/bin/python3.9'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.9.19 (main, Aug 23 2024, 00:07:48)
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
We've changed to Azure Linux based docker image in 2.64.0.
Please use `tdnf install tar` to install it.

**Comment by rajharini** [comment]
okay, I'm able to proceed after installing tar. Thank you for the response!
