### ISSUE TITLE
Install jq in new Alpine-Linux based Azure/CLI image.

### ISSUE THREAD

**Issue by aderant-smcd** [Azure/azure-cli#29896]
**Related command**
azure/CLI@V2

**Is your feature request related to a problem? Please describe.**
The previous 2.63 container image based on Alpine had the jq package installed by default, 2.64 based on Azure Linux does not - needing to parse json during CI/CD tasks is fairly common and including this helps save some time/reduce script size. It would be helpful to my use cases if this could be included again.

**Describe the solution you'd like**
Install jq by default.

**Describe alternatives you've considered**
Can install myself, but as each azure/CLI@v2 task runs in a fresh container image it's not super ergonomic to have to chuck the apt-get install command everywhere - + it adds to runtime.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
Added in https://github.com/Azure/azure-cli/pull/29867
