### ISSUE TITLE
Inconsistent output of cores for constrained HB versus HBv2, HBv3, and HBv4

### ISSUE THREAD

**Issue by marconetto** [Azure/azure-cli#29903]
### Describe the bug

az vm list-sizes shows available cores for HB but for HBv[2--4] it shows the full number of cores of the SKU.

It seems it would make sense to have the same output for all HBs (either available cores or full number of cores)

-----------> here it shows the full number of cores (120 instead of 32)
az vm list-sizes --location westeurope --query "[?name=='Standard_HB120-32rs_v3']"
[
  {
    "maxDataDiskCount": 32,
    "memoryInMB": 466944,
    "name": "Standard_HB120-32rs_v3",
    "numberOfCores": 120,
    "osDiskSizeInMB": 1047552,
    "resourceDiskSizeInMB": 491520
  }
]

-----------> here it shows the available cores (30 instead of 60)
az vm list-sizes --location westeurope --query "[?name=='Standard_HB60-30rs']"
[
  {
    "maxDataDiskCount": 4,
    "memoryInMB": 233472,
    "name": "Standard_HB60-30rs",
    "numberOfCores": 30,
    "osDiskSizeInMB": 1047552,
    "resourceDiskSizeInMB": 716800
  }
]

### Related command

az vm list-sizes

### Errors

na

### Issue script & Debug output

na

### Expected behavior

Have the same output (either available cores or full number of cores) across all HB series.

### Environment Summary

azure-cli                         2.64.0

core                              2.64.0
telemetry                          1.1.0

Extensions:
account                            0.2.5
bastion                            1.1.0
quota                              1.0.0
ssh                                2.0.5

Dependencies:
msal                              1.30.0
azure-mgmt-resource               23.1.1

Python location '/usr/local/Cellar/azure-cli/2.64.0/libexec/bin/python'

Python (Darwin) 3.11.10 (main, Sep  7 2024, 01:03:31) [Clang 15.0.0 (clang-1500.3.9.4)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by TravisCragg-MSFT** [comment]
@marconetto Please use the VM SKU API for information on VM Sizes - [az vm list skus](https://learn.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-list-skus)
