### ISSUE TITLE
Customer feedback |  az compute-diagnostic | remove unused parameters

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#29931]
### Describe the bug

This GitHub issue is being moved from MicrosoftDocs/azue-docs-cli customer PR [4621](https://github.com/MicrosoftDocs/azure-docs-cli/pull/4621).  

### Request
* Please review and make source code adjustments if appropriate.
* If the `--ids` parameter should NOT be removed, please provide more information in the short-summary of why, or in what scenario, this parameter would be used.

***************************************************
### Customer feedback

Remove unused parameter `--ids`

### Screen print
![image](https://github.com/user-attachments/assets/b9cc6e17-fd6d-413f-8217-2afaa4776319)

### Related command

 az compute-diagnostic spot-placement-recommender generate

### Errors

n/a

### Issue script & Debug output

n/a

### Expected behavior

n/a

### Environment Summary

Azure CLI 2.64.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yanzhudd** [comment]
Hi @dbradish-microsoft 
The command "az compute-diagnostic" is not developed in this azure-cli repo but in the azure-cli-extension repo, so please raise issue here: https://github.com/Azure/azure-cli-extensions
Besides, please note the command is not owned by Azure CLI team, Hi @joal42 could you please help to look at this issue?
