### ISSUE TITLE
Overlay Default CNI for aks

### ISSUE THREAD

**Issue by chasewilson** [Azure/azure-cli#29946]
### Preconditions

- [X] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

`az aks create`

### Resource Provider

na

### Description of Feature or Work Requested

Update az aks create -n testcluster -g testgroup  to create a cluster using Azure CNI Overlay as the default when k8s version is 1.30+

### Minimum API Version Required

na

### Swagger PR link / SDK link

na

### Target Date

2024-11-18

### PM Contact

phwilson

### Engineer Contact

tylloyd

### Additional context

AKS is moving it's default to Azure CNI Overlay

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by chasewilson** [comment]
Closing this. Not needed due to previous change: https://github.com/Azure/azure-cli/pull/29388
