### ISSUE TITLE
Az login

### ISSUE THREAD

**Issue by PullaiahDegala** [Azure/azure-cli#29954]
### Describe the bug

azure CLI login problem it is not open it is showing error

### Related command

az login

### Errors

Decryption failed: [WinError 0] None. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError

### Issue script & Debug output

az login

### Expected behavior

azure CLI login successfully.

### Environment Summary

az login

### Additional context

az login problem

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
