### ISSUE TITLE
**az progres flexible-server list-skus** returns invalid SKus

### ISSUE THREAD

**Issue by zikalino** [Azure/azure-cli#29960]
### Describe the bug

SKUs returned are in lower case as visible here:

`
      {
        "reason": null,
        "serverCount": 0,
        "status": null,
        "supportedServerVersions": "12",
        "supportedSku": "standard_b1ms",
        "supportedStorageGb": 32,
        "supportedTier": "Burstable"
      }
`

When trying to execute command with returned lower case SKU:

`
az postgres flexible-server create ... --sku-name standard_b1ms  --tier Burstable
`

Azure CLI will fail with following error:

Incorrect value for --sku-name. The SKU name does not match Burstable tier. Specify --tier if you did not. Or CLI will set GeneralPurpose as the default tier. Allowed values : {'Standard_B20ms', 'Standard_B2ms', 'Standard_B1ms', 'Standard_B16ms', 'Standard_B2s', 'Standard_B4ms', 'Standard_B12ms', 'Standard_B8ms'}

after making SKU uppercase:

`
az postgres flexible-server create ... --sku-name Standard_B1ms  --tier Burstable
`

it works

### Related command

az progres flexible-server list-skus

### Errors

no error, just wrong SKU names returned

### Issue script & Debug output

no need, it's clear without script

### Expected behavior

command should return proper values

### Environment Summary

azure-cli                         2.61.0 *

core                              2.61.0 *
telemetry                          1.1.0

Extensions:
acrtransfer                        1.1.0
alertsmanagement                   0.2.3
attestation                        1.0.0
automanage                         0.1.2
automation                       1.0.0b1
azure-devops                       1.0.1
azurestackhci                      0.2.9
blueprint                          0.3.2
communication                      1.9.3
confluent                          0.6.0
costmanagement                     1.0.0
databox                            1.1.0
databricks                         1.0.0
datadog                            0.1.1
datafactory                        1.0.2
datamigration                    1.0.0b1
dataprotection                     1.5.3
datashare                          0.2.0
desktopvirtualization               1.0.0
devcenter                          6.0.1
dnc                                0.2.1
edgeorder                          0.1.0
elastic                          1.0.0b2
eventgrid                        1.0.0b1
front-door                         1.2.0
gallery-service-artifact             1.0.0b1
healthbot                          0.1.0
ip-group                           0.1.2
kusto                              0.5.0
logic                              1.1.0
logz                               0.1.0
maintenance                        1.6.0
managementpartner                  0.1.3
mobile-network                     1.0.0
networkcloud                     2.0.0b2
nginx                            2.0.0b5
notification-hub                 1.0.0a1
offazure                           0.1.0
orbital                            0.1.0
peering                            0.2.1
portal                             0.1.3
powerbidedicated                 1.0.0b1
providerhub                      1.0.0b1
purview                            0.1.0
quota                              1.0.0
redisenterprise                    1.0.0
reservation                        0.3.1
sap-hana                           0.6.5
scvmm                              1.1.1
storagesync                        1.0.0
support                            2.0.0
virtual-wan                        1.0.0

Dependencies:
msal                              1.28.0
azure-mgmt-resource               23.1.1

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by nachoalonsoportillo** [comment]
Thanks @zikalino for reporting this issue. It has been addressed in https://github.com/Azure/azure-cli/pull/29840 which will be part of version 2.65.0 scheduled to be released on 2024-10-08.

**Comment by zikalino** [comment]
Thank you @nachoalonsoportillo! I will definitely try :-)
