### ISSUE TITLE
Customer feedback |  afd rule create --cache-duration parameter | "--cache-duration" on "az afd rule create" not working as expected

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#29970]
### Describe the bug

This GitHub issue is being moved from MicrosoftDocs/azure-docs-cli [4635](https://github.com/MicrosoftDocs/azure-docs-cli/issues/4635).

*******************************

### Request to engineering
1. Kindly provide the customer with a working example of the `--cache-duration` parameter
2. Please review the [Azure CLI reference guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/reference_doc_guidelines.md#examples) and provide at least one example for each parameter. If you don't want to do this in code blocks, add this information to the `short-summary` description property.  The `--cache-duration` description might look something like this: `The duration for which the content needs to be cached. Allowed format is [d.]hh:mm:ss. Example: 90.24:59:59.`

### Type of issue

Code doesn't work

### Feedback

I tried executing this command:
`az afd rule create --resource-group xxxxxx --profile-name xxxxxxx --rule-set-name xxxxxxx --name xxxxxx --order 1 --match-processing-behavior Continue --match-variable RequestUri --operator BeginsWith --match-values 'xxxxxxxx' --negate-condition false --action-name RouteConfigurationOverride --cache-behavior OverrideAlways --cache-duration '365.23:59:59' --enable-compression true --query-string-caching-behavior IgnoreQueryString --origin-group '/subscriptions/xxxxxxx/resourcegroups/rg-ledger-germanywest-prod/providers/Microsoft.Cdn/profiles/frontdoor-xxxxxxx/origingroups/xxxxxxx' --forwarding-protocol MatchRequest`

According to the docs, --cache-duration is in the valid format ([d.]hh:mm:ss)
Still, the following error is printed:

`InvalidArgumentValue: --cache-duration: Unable to parse: '365.23:59:59'. Expected format: Format: time (hh:mm:ss.xxxxxx)`

### Page URL

https://learn.microsoft.com/en-us/cli/azure/afd/rule?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/afd/rule.yml

### Related command

az afd rule create

### Errors

`InvalidArgumentValue: --cache-duration: Unable to parse: '365.23:59:59'. Expected format: Format: time (hh:mm:ss.xxxxxx)`

### Issue script & Debug output

n/a

### Expected behavior

n/a

### Environment Summary

n/a

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
