### ISSUE TITLE
get an ERROR: listing locations: failed retrieving Azure location for account - when executing 'azd up' command

### ISSUE THREAD

**Issue by azaslawski** [Azure/azure-cli#29976]
### Describe the bug

Logged in with 'azd auth login' - with correct subscription id (work account)
Executed 'azd up' to deploy my Bicep script on Work Azure account.
Got Below Error (redacted PII)
```
ERROR: listing locations: failed retrieving Azure location for account <displaying_personal_acct_id_INCORRECT_should_be_work_ID>: failed to resolve user <displaying_work_user_acct_CORRECT> access to subscription with ID <displaying_personal_acct_id_INCORRECT_should_be_work_ID> If you recently gained access to this subscription, run `azd auth login` again to reload subscriptions.
Otherwise, visit this subscription in Azure Portal using the browser, then run `azd auth login` 
``` 

### Related command

`azd auth login `- no issues here, correct account is used (never used personal login from work VM)
`azd up` - to run bicep script, but getting an error

### Errors

command # 1:
`azd auth login`
- works w/o issues (used work credentials)

command # 2: 
`azd up`

ERROR: listing locations: failed retrieving Azure location for account <displaying_personal_acct_id_INCORRECT_should_be_work_ID>: failed to resolve user <displaying_work_user_acct_CORRECT> access to subscription with ID <displaying_personal_acct_id_INCORRECT_should_be_work_ID> If you recently gained access to this subscription, run `azd auth login` again to reload subscriptions.
Otherwise, visit this subscription in Azure Portal using the browser, then run `azd auth login` 

### Issue script & Debug output

executed with debugging on:
azd up --debug -> log_azd.txt
content:
Initialize bicep provider
Retrieving locations...

ERROR: listing locations: failed retrieving Azure location for account <displaying_personal_acct_id_INCORRECT_should_be_work_ID>: failed to resolve user <displaying_work_user_acct_CORRECT> access to subscription with ID <displaying_personal_acct_id_INCORRECT_should_be_work_ID> If you recently gained access to this subscription, run `azd auth login` again to reload subscriptions.
Otherwise, visit this subscription in Azure Portal using the browser, then run `azd auth login` 

### Expected behavior

after executing 'azd up' I expect a location prompt to come up so that I can select a location: i.e. eastus, instead the above error is displaying.

### Environment Summary

azure-cli                         2.64.0

core                              2.64.0
telemetry                          1.1.0

Dependencies:
msal                              1.30.0
azure-mgmt-resource               23.1.1

Python location '/opt/az/bin/python3'
Extensions directory '/home/<username>/.azure/cliextensions'

Python (Linux) 3.11.8 (main, Aug 28 2024, 05:45:18) [GCC 11.4.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

### Additional context

I have two VMs running Ubuntu operating systems 22.04.4 LTS.
I use both VMs for development, but each is using a different Azure account (personal, and work) nothing is shared between these VMs, other than they run on the same OS (Win11-23H2, 12th Gen i7-12700K 3.60 GHz, 128 GB Ram).
When executing 'azd up' on VM1 (personal Azure account), bicep script runs w/o issues and generates resources.
BUT
Wen executing 'azd up' on VM2 (work Azure account), bicep script does not work and I get an error (specified below) also even though the error message shows my correct (work) user id, it (somehow) is displaying my personal subscription id.
Also, when setting up 'azd init' it correctly shows my Work Azure Subscriptions at which point a correct subscription is selected.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by yonzhan** [comment]
Please open this question in azd repo.

**Comment by azaslawski** [comment]
Makes sense!
Done!
