### ISSUE TITLE
Use of allow no subscriptions

### ISSUE THREAD

**Issue by lazyspark** [Azure/azure-cli#2998]
The option for allow no subscription is provided in the documentation but not in the az login -h (as of version 2.0.3). On investigating further there seems to be code checked in for enabling this option just 5 days back. Will this option available in upcoming release?

**Environment summary**
CLI was installed using apt-get and an upgrade was tried using pip. 
2.0.3 CLI Version
Windows 10 bash

**Comment by yugangw-msft** [comment]
It will be available in the upcoming release
