### ISSUE TITLE
CLI prompted parameter input with ARM Template fails to deploy

### ISSUE THREAD

**Issue by raykao** [Azure/azure-cli#3001]
### Description
Parameters entered during the deployment with ARM template and azure-cli 2.0.3 fails to deploy.

Does CLI 2.0 require that the parameters be passed in via params file or params string only?  Are user inputed parameters in console a WIP?

Console error:
```
Deployment template validation failed: 'The value for the template parameter 'jumpboxServerName' at line '1' and column '89' is not provided. Please see https://aka.ms/arm-deploy/#param
eter-file for usage details.'.
```

ARM Template:
https://github.com/raykao/OSSonAzure/blob/master/arm_templates/jumpbox.arm.json
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
Installed on Mac and using a docker image (raykao/azure_lightsaber) runnin

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
2.0.3

**OS Version:** What OS and version are you using?  
Answer here:
MacOS Sierra
Docker image with Ubuntu 16.04.2 LTS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
Bash

**Comment by brendandburns** [comment]
Reproduced this error, debugging...

**Comment by brendandburns** [comment]
Please see: https://github.com/Azure/azure-cli/pull/3173 for the fix. Apologies.
