### ISSUE TITLE
Documentation confusion for Azure Spot Placement Recommender CLI

### ISSUE THREAD

**Issue by krtaiyang** [Azure/azure-cli#30038]
### Describe the bug

First of all, the codes of Commands and Examples are different.
'compute-diagnostic ' and 'compute diagnostic', I don't know which one is correct.

Refer:
[Azure CLI guide- compute-diagnostic ](https://learn.microsoft.com/en-us/cli/azure/compute-diagnostic/spot-placement-recommender?view=azure-cli-latest)

### Related command

az compute-diagnostic spot-placement-recommender generate
or
az compute diagnostic spot-placement-recommender generate

### Errors

**Commands: compute-diagnostic**
**Examples: compute diagnostic**
Both writing methods failed to call.

### Issue script & Debug output

**Commands: compute-diagnostic**
Error Code: 
`Message: The HTTP resource that matches the request URI 'https://eastus2.diagnostic.compute.azure.com/subscriptions/xxxx-8c09-45ac-88da-xxxx/providers/Microsoft.Compute/locations/eastus2/diagnostics/spotPlacementRecommender/generate' does not support the API version '2021-06-01-preview'.`

**Examples: compute diagnostic**
Error Code: 
`'compute' is misspelled or not recognized by the system.`

### Expected behavior

Correct call, and return the correct spot vm placement score info.

### Environment Summary

azure-cli                         2.64.0
core                              2.64.0
telemetry                          1.1.0
Extensions:
compute-diagnostic-rp             1.0.0b1
Dependencies:
msal                              1.30.0
azure-mgmt-resource               23.1.1
Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\MyPC\.azure\cliextensions'
Python (Windows) 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 21:52:07) [MSC v.1937 32 bit (Intel)]
Legal docs and information: aka.ms/AzureCliLegal
Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by joal42** [comment]
@krtaiyang Plz use `az compute-recommender`. The `az compute-diagnostic spot-placement-recommender generate` will be removed. 
https://learn.microsoft.com/en-us/cli/azure/compute-recommender?view=azure-cli-latest

**Comment by krtaiyang** [comment]
When I made the call, I initially received a normal response, but later it returned an error code as follows:

**Comment by joal42** [comment]
@krtaiyang "too many requests" error means u send to the request u send per region pre subscription reached our rate limit. U can wait and re-try or use other region/subscription.

**Comment by krtaiyang** [comment]
Issue Description: When I call the API using the Subscription ID created under my account, the following error is returned. Could you advise how to handle this situation?

`(SubscriptionMetadataNotFound) Unable to retrieve metadata for subscription: '86624446-566d-4805-bec1-XXXX'.
Code: SubscriptionMetadataNotFound`

**Comment by Elina-L** [comment]
Hi @krtaiyang, the Spot Placement API will only work if the subscription is registered to Microsoft.Compute resource provider as the API is under the Compute manifest. I see that the subscription is now registered and the Spot API requests are returning successfully, are you still seeing any errors?

**Comment by krtaiyang** [comment]
Thank you for your detailed explanation. Yes, I solved the issue by modifying the Register. I will close this issue.

Additionally, since I really couldn't find a place to ask this, how can I increase the number of Subscriptions that can be created? Currently, the limit is 6. Although this is unrelated to the CLI.
@Elina-L
