### ISSUE TITLE
Azure CLI installed but can't run AZ commands

### ISSUE THREAD

**Issue by demibalcu** [Azure/azure-cli#30049]
### Describe the bug

I have installed Azure CLI from extensions, also from microsoft by ps script  but I can't run AZ commands. Says that it's not recognized. Also there is no selection of Azure CLI from terminal drop down. VS was restarted. What am I doing wrong?

### Related command

az

### Errors

az' is not recognized as an internal or external command,
operable program or batch file.
az : The term 'az' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ az
+ ~~
    + CategoryInfo          : ObjectNotFound: (az:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

### Issue script & Debug output

no debug

### Expected behavior

i want to run azure cli from VS studio

### Environment Summary

not working

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
I don't understand the problem, please read this first: https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli
