### ISSUE TITLE
az network private-dns does not list the domain fully

### ISSUE THREAD

**Issue by arunprakashn** [Azure/azure-cli#30059]
### Describe the bug

Create a custom private dns zone for a database with name "stage.privatelink.database.windows.net".
Try to list or show using the below commands. 
#$privateDns = az network private-dns zone list --resource-group "rgp" | ConvertFrom-Json
#$privateDns = az network private-dns zone show --resource-group "rgp" --name "stage.privatelink.database.windows.net" | ConvertFrom-Json

The list displays "privatelink.database.windows.net" omitting the "stage." 
The show throws error that such a privatedns zone does not exist.

The azure portal correctly displays it as "stage.privatelink.database.windows.net"

### Related command

#$privateDns = az network private-dns zone list --resource-group "rgp" | ConvertFrom-Json
#$privateDns = az network private-dns zone show --resource-group "rgp" --name "stage.privatelink.database.windows.net" | ConvertFrom-Json

### Errors

No errors but the output is wrong

### Issue script & Debug output

#$privateDns = az network private-dns zone list --resource-group "rgp" | ConvertFrom-Json
#$privateDns = az network private-dns zone show --resource-group "rgp" --name "stage.privatelink.database.windows.net" | ConvertFrom-Json

### Expected behavior

Should fetch "stage.privatelink.database.windows.net" instead of just "privatelink.database.windows.net"

### Environment Summary

{
  "azure-cli": "2.64.0",
  "azure-cli-core": "2.64.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "application-insights": "0.1.15",
    "databricks": "0.10.2"
  }
}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by arunprakashn** [comment]
It was an oversight from my side. Closing this.
