### ISSUE TITLE
New option to allow non interactive "az login"

### ISSUE THREAD

**Issue by dluc** [Azure/azure-cli#30054]
I am running `az login` from a script to cache credentials for subsequent Azure CLI commands. In my use case, I do not need to select or set a subscription during the script execution. I would like the script to execute non-interactively without prompting the user.

When running `az login` with the following options:

* `--allow-no-subscriptions`
* `--only-show-errors`
* `--output none`

the command still prompts for subscription selection after authentication. This prompt blocks the script execution, waiting for user input, which is not suitable for automated scripts.

The only workaround I’ve found is to redirect /dev/null to the standard input:

    az login --allow-no-subscriptions --output none < /dev/null

This prevents the prompt and allows the script to continue, but it feels like a hack rather than a proper solution.

Could you add an option to `az login` (or `az` itself) to disable any interactive prompts, such as `--non-interactive` or `--accept-defaults`? This option would cause `az` to fail immediately if user input is absolutely required, rather than blocking execution waiting for input.

---

az --version: azure-cli 2.65.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
You may set the `core.login_experience_v2` configuration option to `off` to disable this feature.

```
az config set core.login_experience_v2=off
```

See https://learn.microsoft.com/en-us/cli/azure/authenticate-azure-cli-interactively#subscription-selector

**Comment by jiasli** [comment]
There is a feature request https://github.com/Azure/azure-cli/issues/14933 to support `--subscription` in `az login`. If it is implemented, it can be used to disable the interactive subscription selector as well.
