### ISSUE TITLE
Az Login Issue

### ISSUE THREAD

**Issue by srinivas699** [Azure/azure-cli#30073]
### Describe the bug

PS C:\Users\Admin\Desktop\Terraform> az login
Please select the account you want to log in with.
Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError
Please report to us via Github: https://github.com/Azure/azure-cli/issues/20231![Image](https://github.com/user-attachments/assets/c4b1dc8a-ee23-40f7-b075-e5fa8b6805e9)

### Related command

az login![Image](https://github.com/user-attachments/assets/e23ee9b8-b495-4b92-b10f-b103212aaefa)

### Errors

![Image](https://github.com/user-attachments/assets/5ac2c47b-d0a2-4f44-bc9c-ba986f5bad5e)

### Issue script & Debug output

PS C:\Users\Admin\Desktop\Terraform> az login
Please select the account you want to log in with.

### Expected behavior

PS C:\Users\Admin\Desktop\Terraform> az login
Please select the account you want to log in with.

### Environment Summary

![Image](https://github.com/user-attachments/assets/7a292858-138e-406d-a065-896d29a93b10)

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
