### ISSUE TITLE
Error for rdbms module on alpine docker container

### ISSUE THREAD

**Issue by hapeka72** [Azure/azure-cli#30102]
### Describe the bug

We are using the Azure CLI from inside a Docker container based on Alpine Linux.
Since a few days we are getting this error when running certain commands:

Error loading command module 'mysql': cannot import name 'mysql_flexibleservers' from 'azure.mgmt.rdbms' (/usr/local/lib/python3.11/site-packages/azure/mgmt/rdbms/__init__.py)
Error loading command module 'rdbms': No module named 'azure.mgmt.rdbms.mysql_flexibleservers'
'postgres' is misspelled or not recognized by the system.

I am able to reproduce the error using the following steps:
1. Install azure-cli in a docker container based on python:alpine as described on https://github.com/Azure/azure-cli/issues/19591
2. Execute this command in the container: az postgres server key list

The error started to appear on October 12, one day earlier it still worked.
I suspect that something is wrong with the azure-mgmt-rdbms library (it recevied an update on that day).

### Related command

az postgres server key list

### Errors

Error loading command module 'mysql': cannot import name 'mysql_flexibleservers' from 'azure.mgmt.rdbms' (/usr/local/lib/python3.11/site-packages/azure/mgmt/rdbms/__init__.py)
Error loading command module 'rdbms': No module named 'azure.mgmt.rdbms.mysql_flexibleservers'
'postgres' is misspelled or not recognized by the system.

### Issue script & Debug output

I am able to reproduce the error using the following steps:
1. Install azure-cli in a docker container based on python:alpine as described on https://github.com/Azure/azure-cli/issues/19591
2. Execute this command in the container: az postgres server key list

### Expected behavior

no error

### Environment Summary

azure-cli                         2.65.0

core                              2.65.0
telemetry                          1.1.0

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location '/usr/local/bin/python3.13'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.13.0 (main, Oct  8 2024, 00:10:24) [GCC 13.2.1 20240309]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by hapeka72** [comment]
I found out that I can work around the issue if I run
`pip install --force-reinstall -v "azure-mgmt-rdbms==10.2.0b17"`
after installing the azure-cli.

**Comment by randallt** [comment]
> pip install --force-reinstall -v "azure-mgmt-rdbms==10.2.0b17"

I verified that this indeed eliminates the ERRORs for me as well.

**Comment by aymptlt** [comment]
Isn't there a more elegant way to fix this error? I can't find where the initial problem comes from since all versions of this library seem to be locked in the project.

My installation of the Azure CLI is automated, and I don't really want to add a 'pip force reinstall' in my Dockerfile to work around an error that could be resolved :)

Thanks

**Comment by aymptlt** [comment]
hi, fyi the new 2.66.0 version works like a charm ! We don't have the error anymore. Thank you

**Comment by hapeka72** [comment]
for me it works
