### ISSUE TITLE
No me permite logear

### ISSUE THREAD

**Issue by pablomunozcanales** [Azure/azure-cli#30121]
### Describe the bug

Ingreso al cli, ejecuto el comando az login, luego voy a  https://microsoft.com/devicelogin a ingresar el codigo, me aparece el subscription doy enter y hace logout con el mensaje 

"If you encounter any problem, please open an issue at https://aka.ms/azclibug

[Warning] The login output has been updated. Please be aware that it no longer displays the full list of available subscriptions by default."

### Related command

az login

### Errors

If you encounter any problem, please open an issue at https://aka.ms/azclibug

[Warning] The login output has been updated. Please be aware that it no longer displays the full list of available subscriptions by default.

### Issue script & Debug output

cli.knack.cli: Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x7f16d92d8790>, <function _x509_from_base64_to_hex_transform at 0x7f16d92d8820>]
cli.knack.cli: Event: CommandInvoker.OnFilterResult []
cli.knack.cli: Event: Cli.SuccessfulExecute []
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f16d930e9d0>]
az_command_data_logger: exit code: 0
cli.__main__: Command ran in 28.537 seconds (init: 0.158, invoke: 28.380)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3887 in cache file under /home/pablo/.azure/telemetry/20241017181711129
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "/usr/bin/python3.9 /usr/lib/az/lib/python3.9/site-packages/azure/cli/telemetry/__init__.py /home/pablo/.azure /home/pablo/.azure/telemetry/20241017181711129"
telemetry.process: Return from creating process 3017
telemetry.main: Finish creating telemetry upload process.

### Expected behavior

que se logee y poder ejecutar comandos

### Environment Summary

azure-cli                         2.65.0                      

core                              2.65.0
telemetry                          1.1.0

Extensions:
ai-examples                        0.2.5
ml                                2.30.1
ssh                                2.0.5

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location '/usr/bin/python3.9'
Extensions directory '/home/pablo/.azure/cliextensions'
Extensions system directory '/usr/lib/python3.9/site-packages/azure-cli-extensions'

Python (Linux) 3.9.19 (main, Aug 23 2024, 00:07:48) 
[GCC 11.2.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by jiasli** [comment]
Please provide the error message you are seeing.
