### ISSUE TITLE
[Shell] Running 'az shell' results in an error

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#3014]
### Description
```
(env2) C:\Users\trpresco\Documents\github\azure-cli>az shell
The operation 'azure.cli.command_modules.network.custom#' is invalid.
```

I deleted my virtual environment and did a fresh install and got the same error.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: dev_setup.py

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.3+dev)

acr (2.0.1+dev)
acs (2.0.3+dev)
appservice (0.1.3+dev)
batch (2.0.1+dev)
cloud (2.0.1+dev)
component (2.0.1+dev)
configure (2.0.3+dev)
container (0.1.3+dev)
core (2.0.3+dev)
dla (0.0.2+dev)
dls (0.0.2+dev)
documentdb (0.1.3+dev)
feedback (2.0.1+dev)
find (0.2.0+dev)
iot (0.1.3+dev)
keyvault (2.0.1+dev)
lab (0.0.2+dev)
monitor (0.0.2+dev)
network (2.0.3+dev)
nspkg (3.0.0+dev)
profile (2.0.3+dev)
redis (0.2.0+dev)
resource (2.0.3+dev)
role (2.0.2+dev)
shell (0.2.3+dev)
sql (2.0.1+dev)
storage (2.0.3+dev)
taskhelp (0.1.1b4+dev)
testsdk (0.1.0+dev)
utility-automation (0.1.1)
vm (2.0.3+dev)

**OS Version:** What OS and version are you using?  
Answer here: Windows 10 Creators Update

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: CMD.exe

**Comment by derekbekoe** [comment]
@tjprescott how did you get this error? Doesn't look like the message is from the shell. What does `--debug` provide?

**Comment by tjprescott** [comment]
Hmmm... it seems this only happens on my profile supported Network branch.  I'll look into it. Closing for now.

**Comment by tjprescott** [comment]
It turns out a rebase ripped out all of my network watcher commands, so that was the source of the error. Yay cherry pick... 🍒
