### ISSUE TITLE
delete command doesn't show usage information on error

### ISSUE THREAD

**Issue by BrianPeek** [Azure/azure-cli#3015]
### Description
When using the "az functionapp" commands, the required parameters are displayed in the same color as the rest of the usage text, and at the end of that text.  Other commands that display this information as the first output text and in red, making it much easier to see what's rong.

![example](https://cloud.githubusercontent.com/assets/2321675/25458268/456eff28-2aa7-11e7-9e09-34b0dad64bb3.png)

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.3+1.dev20170420)

**OS Version:** What OS and version are you using?  
Answer here: Win10 Creator's Update

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

**Comment by yugangw-msft** [comment]
This is a more general issue, that any delete commands have such issues:
```bash
yugangw@yg-2:~$ az disk delete 
(--resource-group --name | --ids) are required
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 288, in execute
    self.cli_ctx.raise_event(EVENT_INVOKER_POST_PARSE_ARGS, command=parsed_args.command, args=parsed_args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 157, in raise_event
    func(self, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 246, in parse_ids_arguments
    raise ValueError('({} | {}) are required'.format(missing_required, '--ids'))
ValueError: (--resource-group --name | --ids) are required
```

**Comment by yugangw-msft** [comment]
This is fixed now. Please reactivate if you see otherwise.
