### ISSUE TITLE
Inclusion of date of the spend as part of costbyresource json / csv export

### ISSUE THREAD

**Issue by mlnraop** [Azure/azure-cli#30161]
Hi, Would like to capture the the date of the spend as part "azure-cost costByResource -s " csv export.
While this is possible with individual date export, not having the date is causing bit of an issue in analysis.

Appreciate if there is method added to include the date as one additional item against each line of spend.

Thanks

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
