### ISSUE TITLE
VNet create/update support for IPAM pool association (2024-05-01)

### ISSUE THREAD

**Issue by danlope** [Azure/azure-cli#30199]
### Preconditions

- [x] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

az network vnet create
az network vnet update

### Resource Provider

Microsoft.Network

### Description of Feature or Work Requested

Feature request for the `vnet create/update` commands to introduce a new parameter: `--ipam-pool-prefix-allocations`. This enhancement aims to facilitate the association/disassociation of a VNET with an IP Address Management (IPAM) pool, thereby streamlining the allocation of address prefixes.

This feature support is crucial for IPAM service going GA, which was targeted for mid-November.

- https://learn.microsoft.com/en-us/cli/azure/network/vnet?view=azure-cli-latest#az-network-vnet-create
- https://learn.microsoft.com/en-us/cli/azure/network/vnet?view=azure-cli-latest#az-network-vnet-update

### New Parameter details: 

- Optional Parameter
- Enables customers to specify an IPAM pool for allocating address prefixes to resources within the VNET, instead of defining an address prefix during VNET creation/update.
- If this parameter is utilized, the `addressPrefixes` array must explicitly be empty. Otherwise, a default address prefix will be used, causing an error.

Good example: 
![Image](https://github.com/user-attachments/assets/8495a9f1-5841-4c9d-b403-748e36b09f92)

Bad example: 
![Image](https://github.com/user-attachments/assets/d6ad5132-f8a3-46c2-a9fb-4f70a232168c)
- 

### Minimum API Version Required

2024-05-01

### Swagger PR link / SDK link

swagger:
https://github.com/Azure/azure-rest-api-specs/pull/30560/files#diff-3865305b0c4c82aae9addc443cc6c5001ea7a833c4332d15f6f7dfe646e300b0

example PR of changes needed in CLI repo (may not be everything was just testing locally): 
https://github.com/Azure/azure-cli/pull/30152

### Request Example

https://github.com/Azure/azure-rest-api-specs/blob/kamboj-prjwl/release-network-Microsoft.Network-2024-05-01/specification/network/resource-manager/Microsoft.Network/stable/2024-05-01/examples/VirtualNetworkCreateWithIpamPool.json

### Target Date

2024-11-15

### PM Contact

LIJAY

### Engineer Contact

DANLOPE

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
