### ISSUE TITLE
Support streaming file content to output

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#302]
What we have now is not right as it hard coded to stdout. This is causing issues on testing
This impacts both getting boot diagnostic and group template exporting.

**Comment by tjprescott** [comment]
@yugangw-msft is the issue that file content is sent to stdout instead of a file? Does "command > file.txt" not work? Or are you saying we should support outputting directly to a file?

**Comment by yugangw-msft** [comment]
"command > file.txt" is a workaround. The right thing is for command handlers to have a hand hold on the [file object](https://github.com/Azure/azure-cli/blob/master/src/azure/cli/main.py#L38), which would be the test log when run under testing. Please chat with @johanste  
This is not a very important issue we should work on right now. Fine to just close it.

**Comment by yugangw-msft** [comment]
@johanste, I think you are the better person to drive for the desired option. I don't really have strong opinions on this, and we don't have user voices on the end behaviors.
I am closing this as we have no near term plan and motivations to change this
