### ISSUE TITLE
Allow ? gesture to inject into the next command

### ISSUE THREAD

**Issue by oakeyc** [Azure/azure-cli#3020]
### Description
**Outline the issue here:**
Since the ? feature allows you retain the output of the last run command, it might be nice to use it to enable simplified scenarios like:

```
az>> vm list -g {myrg}
az>> vm stop --ids ?[].id
```

The equivalent bash command would be something like:
```
az>> vm stop --ids ${az vm list -g {myrg} --query "[].id"}
```
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

**OS Version:** What OS and version are you using?  
Answer here:

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

**Comment by tjprescott** [comment]
This will (most likely) not work:
`az>> vm stop --ids ${az vm list -g {myrg} --query "[].id"}`

You need to use TSV format:
`az>> vm stop --ids ${az vm list -g {myrg} --query "[].id" -o tsv}`
