### ISSUE TITLE
can't connect to azure vm at home, but can do at office

### ISSUE THREAD

**Issue by kailums** [Azure/azure-cli#30281]
### Describe the bug

Hi,
I recently work at home, but i can't connect to azure vm at home. when i'm at office, i can connect to it.

and i have connected to to MSFTVPN at home, but still cannot connect to it.

could you please help me?

### Related command

az ssh vm --ip 52.228.186.184

### Errors

OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2
ssh: connect to host 52.228.186.184 port 22: Connection timed out

### Issue script & Debug output

OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2
ssh: connect to host 52.228.186.184 port 22: Connection timed out

### Expected behavior

can connect to it.

### Environment Summary

azure-cli                         2.65.0

core                              2.65.0
telemetry                          1.1.0

Extensions:
ssh                                2.0.6

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location '/opt/az/bin/python3'
Extensions directory '/home/kailu/.azure/cliextensions'

Python (Linux) 3.11.8 (main, Sep 25 2024, 11:34:47) [GCC 13.2.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
