### ISSUE TITLE
ACS: add az acs stop command to stop and deallocate vm's in an acs cluster

### ISSUE THREAD

**Issue by sauryadas** [Azure/azure-cli#3030]
### Description - add a helper command to stop/deallocate the acs cluster
**Outline the issue here:**
The az vm stop is not the same as the stop button in the portal. The stop button in the portal also deallocates resources which means that you don't get charged for the resources after you stop a vm in the portal. In the CLI, you have to explicitly run the deallocate command after the stop command to prevent from getting charged for the resources.

Essentially the code will call the following commands
az vm list
az vm stop
az vm deallocate

Design of the command-

az acs command -n containerServiceName -g resourceGroupName - stops/deallocates all vm's in the cluster

az acs command -n containerServiceName -g resourceGroupName  -vm-names  {vm_name1, ...} to stop only a specific vm or multiple vm's

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:dev build

**OS Version:** What OS and version are you using?  
Answer here:mac os

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:terminal

**Comment by mboersma** [comment]
@sauryadas correct me if I'm wrong, but we're not planning to implement this for `az acs`. @tjprescott let's close this issue.
