### ISSUE TITLE
Decryption failed: [WinError -2146893813]

### ISSUE THREAD

**Issue by deepan1984** [Azure/azure-cli#30314]
### Describe the bug

# az login
Select the account you want to log in with. For more information on login with Azure CLI, see https://go.microsoft.com/fwlink/?linkid=2271136
Decryption failed: [WinError -2146893813] Key not valid for use in specified state. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError
Please report to us via Github: https://github.com/Azure/azure-cli/issues/20231

### Related command

 az login
Select the account you want to log in with. For more information on login with Azure CLI, see https://go.microsoft.com/fwlink/?linkid=2271136
Decryption failed: [WinError -2146893813] Key not valid for use in specified state. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError
Please report to us via Github: https://github.com/Azure/azure-cli/issues/20231

### Errors

Decryption failed: [WinError -2146893813] 

### Issue script & Debug output

Decryption failed: [WinError -2146893813] 

### Expected behavior

az login

### Environment Summary

azure cli

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
