### ISSUE TITLE
Keyvault commands registered twice in commands.py

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#3032]
### Description
**Outline the issue here:**

Some KeyVault commands are registered twice. e.g. `cli_keyvault_data_plane_command('keyvault key list', convenience_path.format('KeyVaultClient.get_keys'))`.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: n/a

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: latest master

**OS Version:** What OS and version are you using?  
Answer here: n/a

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: n/a

**Comment by tjprescott** [comment]
This has been fixed since the Knack conversion.
