### ISSUE TITLE
Output of the reset Gateway command is not useful

### ISSUE THREAD

**Issue by aanandr** [Azure/azure-cli#3036]
### Description
The output of az network vpnet-gateway reset doesnt provide any useful information. The recommendation is to just output whatever az network vnet-gateway show would display

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.3

**OS Version:** What OS and version are you using?  
Answer here: Windows 10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

Following is the output see today. Please instead output what ever the show command would output.
{
  "activeActive": null,
  "bgpSettings": null,
  "enableBgp": null,
  "etag": null,
  "gatewayDefaultSite": null,
  "gatewayType": null,
  "id": null,
  "ipConfigurations": null,
  "location": null,
  "name": null,
  "provisioningState": null,
  "resourceGuid": null,
  "sku": null,
  "tags": null,
  "type": null,
  "vpnClientConfiguration": null,
  "vpnType": null
}

**Comment by tjprescott** [comment]
The swagger specifies that this operation returns a VirtualNetworkGateway object.  It clearly does not, which is why you see the output you do.  Please open an issue against the Swagger specs.

**Comment by aanandr** [comment]
Travis – how does PS display the right output then?

**Comment by tjprescott** [comment]
@aanandr I can't speak for Powershell, but I would guess they make an extra get call when the command completes to smooth over the deficiency. Based on the service response, it seems like the output should be nothing, in which case the Swagger is incorrect because it says the gateway object is returned.  Alternatively, the service can be fixed to actually return the object that the swagger says it should.

**Comment by aanandr** [comment]
Ok I will look into this. Two things

1.       Who updates the Swagger specs? Is that a contact in the Engineering team (in this case GW)?

2.       Can CLI also make extra calls to get the Gateway object?

Aanand

**Comment by tjprescott** [comment]
1. Service teams own their swagger.
2. Yes, but if the service returns nothing then this (and thus PS) would be the incorrect behavior. The only reason for the output oddity is because the SDK is trying to deserialize null into a gateway object and so you get all null values for the properties..

**Comment by aanandr** [comment]
Travis – I checked and found that in the case of PS they actually make a call to get the GW object. So the fix, as you rightly pointed, is to either have the service return the object or update Swagger. That being said, when the service doesn’t return anything, why do you display what you display today? Why not just blank?

**Comment by tjprescott** [comment]
This is because the SDK is expecting a gateway object (because it is generated against the Swagger and that's what the Swagger says it returns).  So it is deserializing a Gateway object and since nothing is provided, all the fields of that object have null values, hence the output you see.

**Comment by aanandr** [comment]
Travis – when nothing proper is being returned why even display it. I think you should either do what PS is doing or don’t display anything. What is being displayed today doesn’t provide any value. Also, can you open the bug on Swagger? I will route it internally here.
