### ISSUE TITLE
[Shell] Default color for parameter value is very weak

### ISSUE THREAD

**Issue by yokawasa** [Azure/azure-cli#3037]
### Description
**Outline the issue here:**
Default color for parameter value is very weak. More distinct color is better especially for users who use terminal with black/grey colored background.  It's good to pick a color from standard 16 color pallet considering many terminal configurations.
![](https://lrsjapanwestv2.blob.core.windows.net/testfuse/shell-color.png)

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
pip install --user azure-cli-shell

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
azure-cli-shell (0.2.2)

**OS Version:** What OS and version are you using?  
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.10
Release:        16.10
Codename:       yakkety
```

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
I've tried the following patterns.
- bash or zsh + tmux 
- bash or zsh + w/o tmux

**Comment by oakeyc** [comment]
In the next shell release, there will be multiple color options.

**Comment by oakeyc** [comment]
PR #93 for azure-cli-shell added the colors

**Comment by StingyJack** [comment]
@oakeyc  - how are these color options supposed to work?

**Comment by tjprescott** [comment]
@StingyJack the colors referred to in this issue apply only to the `az interactive` command, not the CLI in general.

**Comment by StingyJack** [comment]
@tjprescott - OP made no mention of that command unless it was edited out in the past.

**Comment by tjprescott** [comment]
It is in the title `[Shell]` and also you can tell from the prompt in the screenshot `az>>` is the prompt within `az interactive`. But you are right--nothing in the original post makes that clear. I just happen to know the history of the issue :)
