### ISSUE TITLE
[Ask/Discussion]Capability of managed disk export

### ISSUE THREAD

**Issue by sasukeh** [Azure/azure-cli#3038]
### Description
**Customer want to use managed disk export via azure cli 2.0:**
It looks like there is no function of exporting managed disk via azure cli2.0.
This is a customer needs.
Is there potential to implement exporting disk feature azure cli 2.0 upon a load map?

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
pip install azure-cli

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
2.0.3

**OS Version:** What OS and version are you using?  
Answer here:
Ubuntu 16.04 

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
GNU/Linux bash

**Comment by tjprescott** [comment]
@yugangw-msft is this functionality supported by the REST API?

**Comment by yugangw-msft** [comment]
Apologize for the delay.
Depends on the end goal, if for backup you can create a managed disk/snapshot from another managed disk, if you want to read you can use "az disk grant-access" to get SAS URI.

**Comment by yugangw-msft** [comment]
like i commented
