### ISSUE TITLE
[Feature] Support managed identity on on-premis Arc-enabled Linux servers

### ISSUE THREAD

**Issue by sijjay** [Azure/azure-cli#30399]
**Related command**
Recently it was enabled for Windows (looks like) https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/release-notes-azure-cli.md#core
Would be great to have the same for Linux OS

**Describe the solution you'd like**
Probably the same as it is done for Windows, but for Linux and discussed here: https://github.com/Azure/azure-cli/issues/16573

**Describe alternatives you've considered**
Az Python library and custom scripts

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
Managed identity on Arc-enabled Linux servers will be supported in the next release. Please see my comment at https://github.com/Azure/azure-cli/issues/16573#issuecomment-2488123485. You may also follow https://github.com/Azure/azure-cli/issues/16573#issuecomment-2488223313 to test it right away.
