### ISSUE TITLE
Authentication Code Expired

### ISSUE THREAD

**Issue by t1agob** [Azure/azure-cli#3040]
### Description
Hello,
having an issue authenticating with Azure CLI 2.0 on linux machines. Works fine from Windows machine but not from Linux.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Used this article to install on both Windows and Linux https://docs.microsoft.com/en-us/cli/azure/install-azure-cli

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
azure-cli (2.0.3)

acr (2.0.1)
acs (2.0.3)
appservice (0.1.3)
batch (2.0.1)
cloud (2.0.1)
component (2.0.1)
configure (2.0.3)
container (0.1.3)
core (2.0.3)
documentdb (0.1.3)
feedback (2.0.1)
find (0.0.2)
iot (0.1.3)
keyvault (2.0.1)
lab (0.0.2)
monitor (0.0.2)
network (2.0.3)
nspkg (2.0.0)
profile (2.0.3)
redis (0.2.0)
resource (2.0.3)
role (2.0.2)
sql (2.0.1)
storage (2.0.3)
vm (2.0.3)

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

**OS Version:** What OS and version are you using?  
Windows 10 and Linux Ubuntu 14.04 LTS (on Azure)

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
cmd.exe for Windows machine and bash for Linux machine

**Comment by yugangw-msft** [comment]
Sorry for the delay on response. For a while, there was service side bugs on managing device code which was fixed. Please re-activate when you see it again
