### ISSUE TITLE
`az ad sp create-for-rbac` fails even after deleting the created sp

### ISSUE THREAD

**Issue by devigned** [Azure/azure-cli#3043]
### Description
It seems like `az ad sp create-for-rbac` is creating a service principal only, so after running `az ad sp delete`, deleting the sp leaves the application (which makes sense).

The problem is when deleting a sp created with create-for-rbac, then trying to run `az ad sp create-for-rbac`, the command fails unless you delete the app.

Seems this command should be `az ad app create-for-rbac` or take into account the app may still exist and simply add another sp to the existing app.

**Comment by yugangw-msft** [comment]
Actually deleting  the app is the right way. In the output of "-h", there is a section
```
Revoke the service principal when done with it.
        az ad app delete --id <name>
```
i have no push back that the experience is not optimal. 
 I don't think you can create more than 1 sp for an app, but we can at least output a clear actionable error to delete the app, or reuse it if we can  put in new creds.

**Comment by yugangw-msft** [comment]
I will expose a command of `az ad sp revoke-for-rbac` to clean up related artifacts across, including the role assignments

**Comment by tjprescott** [comment]
Why don't we just make the `sp delete` command default to deleting the app definition unless you specify a `--keep-app` flag or something like that?

**Comment by yugangw-msft** [comment]
sorry, i didn't update the comment in time. Yep, I chatted with @devigned yesterday, I will let both `ad sp/app delete` to clean up the assignment, and related sp object as well
