### ISSUE TITLE
Az container create returns "No registered resource provider found for location 'chinaeast2' and API version '2024-05-01-preview' for type 'containerGroups'."

### ISSUE THREAD

**Issue by Xiaojing123456** [Azure/azure-cli#30444]
### Describe the bug

Unable to create container instance using latest Azure CLI version (2.67.0) . When I  downgrade CLI version to 2.64.0, I can create container instance successfully. 

### Related command

az container create --resource-group myResourceGroup --name mycontainer --image mcr.microsoft.com/azuredocs/aci-helloworld --dns-name-label aci-demo --ports 80

### Errors

ERROR: (NoRegisteredProviderFound) No registered resource provider found for location 'chinaeast2' and API version '2024-05-01-preview' for type 'containerGroups'. The supported api-versions are '2017-08-01-preview, 2017-10-01-preview, 2017-12-01-preview, 2018-02-01-preview, 2018-04-01, 2018-06-01, 2018-07-01, 2018-09-01, 2018-10-01, 2019-12-01, 2020-11-01, 2021-03-01, 2021-07-01, 2021-09-01, 2021-10-01, 2022-04-01-preview, 2022-09-01, 2022-10-01-preview, 2023-02-01-preview, 2023-05-01, 2023-05-15-preview'. The supported locations are 'chinaeast2, chinanorth3'.

### Issue script & Debug output

none

### Expected behavior

Please help fix "unable to create container instance with latest cli version" issue

### Environment Summary

PS C:\Windows\system32> az --version
azure-cli                         2.67.0

core                              2.67.0
telemetry                          1.1.0

Extensions:
aks-preview                      0.5.168
ssh                                1.1.3

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\zuo.xiaojing\.azure\cliextensions'

Python (Windows) 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
