### ISSUE TITLE
Azure : cannot delete Azure Postgres server

### ISSUE THREAD

**Issue by fdonnet** [Azure/azure-cli#30459]
### Describe the bug

 az postgres flexible-server delete --my-rg --name mypostgresserver --yes

 Server 'mypostgresserver ' is busy with another operation. Please try again later.

Can start and stop the server.
Cannot see any databases in it.
Cannot delete the server....

Trying everthing.

Can someone help me ?

Not pending activity. Maybe a used a name for the server I used before for an already deleted resource. It's the only thing I can see.

### Related command

 az postgres flexible-server delete --my-rg --name mypostgresserver --yes

### Errors

 Server 'mypostgresserver ' is busy with another operation. Please try again later.

### Issue script & Debug output

 Server 'mypostgresserver ' is busy with another operation. Please try again later.

### Expected behavior

Delete the postgres server.

### Environment Summary

  "azure-cli": "2.66.0",
  "azure-cli-core": "2.66.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {}

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by nachoalonsoportillo** [comment]
> Do you need my RG and my postgres server name ?

Please, server name and, if possible, region.

**Comment by fdonnet** [comment]
rg : ubik-general-rg
server : ubik-general-postgres-db
region: eu west

You can delete the full rg (containing the vnet + postgres). I rebuild another one that is working.
But for this one, I cannot delete any resource in it. (it fail to remove posgres, it fail to remove the subnet and it fail to remove the full rg)

**Comment by nachoalonsoportillo** [comment]
> Do you need my RG and my postgres server name ?

In fact, this issue is not related Azure CLI module for Postgres at all. You're not able to delete the server using the CLI module, neither though the portal or using the [Server - Delete](https://learn.microsoft.com/en-us/rest/api/postgresql/flexibleserver/servers/delete?view=rest-postgresql-flexibleserver-2022-12-01&tabs=HTTP) REST API, are you?

Do you see the Flexible Server resource that you're trying to delete in the portal?

What's the output returned by `az postgres flexible-server show` command on that server?

**Comment by fdonnet** [comment]
No I cannot delete it with the cli or the portal.

The result of the command 
{
  "administratorLogin": "mydbuser",
  "administratorLoginPassword": null,
  "authConfig": {
    "activeDirectoryAuth": "Enabled",
    "passwordAuth": "Enabled",
    "tenantId": "18a60c86-dd4d-4891-9e5e-e0aa55794c5d"
  },
  "availabilityZone": "2",
  "backup": {
    "backupRetentionDays": 7,
    "earliestRestoreDate": "2024-12-03T10:18:11.534736+00:00",
    "geoRedundantBackup": "Disabled"
  },
  "cluster": null,
  "createMode": null,
  "dataEncryption": {
    "geoBackupEncryptionKeyStatus": null,
    "geoBackupKeyUri": null,
    "geoBackupUserAssignedIdentityId": null,
    "primaryEncryptionKeyStatus": null,
    "primaryKeyUri": null,
    "primaryUserAssignedIdentityId": null,
    "type": "SystemManaged"
  },
  "fullyQualifiedDomainName": "ubik-general-postgres-db.postgres.database.azure.com",
  "highAvailability": {
    "mode": "Disabled",
    "standbyAvailabilityZone": null,
    "state": ""
  },
  "id": "/subscriptions/8d22ba2a-159f-4d6b-bfa7-ca8edf122cbc/resourceGroups/ubik-general-rg/providers/Microsoft.DBforPostgreSQL/flexibleServers/ubik-general-postgres-db",
  "identity": null,
  "location": "West Europe",
  "maintenanceWindow": {
    "customWindow": "Disabled",
    "dayOfWeek": 0,
    "startHour": 0,
    "startMinute": 0
  },
  "minorVersion": "4",
  "name": "ubik-general-postgres-db",
  "network": {
    "delegatedSubnetResourceId": "/subscriptions/8d22ba2a-159f-4d6b-bfa7-ca8edf122cbc/resourceGroups/ubik-general-rg/providers/Microsoft.Network/virtualNetworks/ubik-general-rg-vnet/subnets/default",
    "privateDnsZoneArmResourceId": "/subscriptions/8d22ba2a-159f-4d6b-bfa7-ca8edf122cbc/resourceGroups/ubik-general-rg/providers/Microsoft.Network/privateDnsZones/ubik-general-postgres-db.private.postgres.database.azure.com",
    "publicNetworkAccess": "Disabled"
  },
  "pointInTimeUtc": null,
  "privateEndpointConnections": null,
  "replica": {
    "capacity": 5,
    "promoteMode": null,
    "promoteOption": null,
    "replicationState": null,
    "role": "Primary"
  },
  "replicaCapacity": 5,
  "replicationRole": "Primary",
  "resourceGroup": "ubik-general-rg",
  "sku": {
    "name": "Standard_B1ms",
    "tier": "Burstable"
  },
  "sourceServerResourceId": null,
  "state": "Stopped",
  "storage": {
    "autoGrow": "Disabled",
    "iops": 120,
    "storageSizeGb": 32,
    "throughput": null,
    "tier": "P4",
    "type": ""
  },
  "systemData": {
    "createdAt": "2024-12-03T10:11:17.429295+00:00",
    "createdBy": null,
    "createdByType": null,
    "lastModifiedAt": null,
    "lastModifiedBy": null,
    "lastModifiedByType": null
  },
  "tags": {},
  "type": "Microsoft.DBforPostgreSQL/flexibleServers",
  "version": "16"
}

**Comment by fdonnet** [comment]
I can stop it, or start it via cli or via the portal. But cannot kill it. That's very strange.

**Comment by nachoalonsoportillo** [comment]
Please, create a support ticket from the Azure Portal for our support staff to look into that particular server.

**Comment by nachoalonsoportillo** [comment]
@fdonnet I'll be closing this issue as this is not specific to CLI.
