### ISSUE TITLE
Awk command not working in latest Azure cli version

### ISSUE THREAD

**Issue by JoanaPedrosoDiconium** [Azure/azure-cli#30450]
### Describe the bug

Hello, 

We have a Github action in which we install the latest version of Azure CLI and try to run a inlineScript that includes the following command:

`OUTPUT=$(echo $MY_JSON_VARIABLE | jq -r .scopeMapId | awk -F'\/' '{ print $9 }')`

And we get this error: 

`Starting script execution via docker image mcr.microsoft.com/azure-cli:2.67.0
/opt/github/actions-runner/_work/_temp/AZ_CLI_GITHUB_ACTION_1732898353757.sh: line 2: awk: command not found`

I saw that there was an issue created for the -jq command and it was fixed, so wondering if this was already reported somewhere and fixed. If so I'd appreciate it if you linked the issue with the solution! 

Thank you!

### Related command

jq -r .scopeMapId | awk -F'\/' '{ print $9 }'

### Errors

`Starting script execution via docker image mcr.microsoft.com/azure-cli:2.67.0
/opt/github/actions-runner/_work/_temp/AZ_CLI_GITHUB_ACTION_1732898353757.sh: line 2: awk: command not found`

### Issue script & Debug output

.

### Expected behavior

awk command should work with latest version of Azure CLI

### Environment Summary

  Job step uses: azure/CLI@v2 image.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by bebound** [comment]
Azure CLI Docker image does not include all Linux tools.

Please add `tdnf install awk -y` at the beginning of the script.

**Comment by padupe** [comment]
@bebound  It worked perfectly for our scenario.

PSC @claudinei-ferreira @faelzsouza

**Comment by carmodyquinnms** [comment]
The tndf install command does not work and there are several unix tools missing (which, awk), is there a way to load a standard set on?
