### ISSUE TITLE
`shell` shows up as a command whilst inside the shell

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#3047]
### Description

![screen shot 2017-04-27 at 12 04 27 pm](https://cloud.githubusercontent.com/assets/16448634/25499863/c10483ca-2b41-11e7-93cb-fbe01eb26c66.png)
![screen shot 2017-04-27 at 12 06 07 pm](https://cloud.githubusercontent.com/assets/16448634/25499909/ea3923cc-2b41-11e7-8fc5-c5d475d6965e.png)

Repro steps:
Start shell `az shell`
Start typing `shell` and you'll see the completion available.
It will start an new shell inside the current shell. You can carry on doing this recursively...

Expected:
`shell` should not be a valid command whilst inside `shell`.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: `nightly`

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
```
# az --version
azure-cli (2.0.3+1.dev20170426)
...
shell (0.2.3+1.dev20170426)

Python (Linux) 3.5.2 (default, Jul 19 2016, 21:09:41) 
[GCC 4.9.2]

Python location '/usr/local/bin/python'
```

**OS Version:** What OS and version are you using?  
Answer here: `Ubuntu 14.04`

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: `bash`

**Comment by tjprescott** [comment]
I love it! (but it still probably still be fixed...)
