### ISSUE TITLE
AZ AD APP - Can't update SPA redirectUris

### ISSUE THREAD

**Issue by julesblancphin** [Azure/azure-cli#30504]
**Related command**
`az ad app`

**Is your feature request related to a problem? Please describe.**
The `az ad app` command let's you update redirect uris but only for webapps, not SPAs. It would be beneficial if the azure CLI fully supported updating an app registration's SPA redirect URIs.

I've got an IaC pipeline to provision envs for my SPA, I need to be able to automatically update an app registration in B2C.

I have seen similar requests going as far back as 2020 but all have been ignored.

Here is a link to the [https://learn.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest#az-ad-app-create](docs)

**Describe the solution you'd like**
There's an option called `--web-redirect-uris`, it would be nice to have one called `--spa-redirect-uris`

**Describe alternatives you've considered**
Using `az rest` does not work. There's a potential issue there I might raise.

Doing it through the UI is not a solution either, for security reasons and the fact that it would become a manual step. It also goes against the purpose of the Azure CLI.

**Additional context**
The Azure CLI can be used in IaC pipelines to provision resources. As part of this, it's important to be able to automatically update an app registration's redirect URIs. This currently only is doable for webapps but not SPAs.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
Tracked by https://github.com/Azure/azure-cli/issues/14880
