### ISSUE TITLE
unable to copy from blob container using a sas-token

### ISSUE THREAD

**Issue by mbhardwaj-msft** [Azure/azure-cli#30509]
### Describe the bug

Unable to copy the content from blob container using a sas_token in CLI. The Azure Load Testing service provides a SAS URL to its customers which can be used to download/view the load test logs and results. While this URL works with Azure Storage Explorer and AzCopy, it's not working with 'az storage copy'

### Related command

Doesn't work: `az storage copy --source 'https://****.*39.blob.storage.azure.net/*****?skoid=*****&sktid=*****&skt=*****&ske=*****&sks=*****&skv=*****&sv=*****&st=*****&se=*****&sr=****&sp=****&sig=****' --destination 'C:\Workspace\downloads' --recursive`

Works: `azcopy copy "https://****.*39.blob.storage.azure.net/*****?skoid=*****&sktid=*****&skt=*****&ske=*****&sks=*****&skv=*****&sv=*****&st=*****&se=*****&sr=****&sp=****&sig=****" "C:\Workspace\downloads" --overwrite=prompt --check-md5 FailIfDifferent --from-to=BlobLocal --recursive --log-level=INFO`

### Errors

failed to perform copy command due to error: Login Credentials missing. No SAS token or OAuth token is present and the resource is not public
Failed to perform copy operation.
'sktid' is not recognized as an internal or external command,
operable program or batch file.
'skt' is not recognized as an internal or external command,
operable program or batch file.
'ske' is not recognized as an internal or external command,
operable program or batch file.
'sks' is not recognized as an internal or external command,
operable program or batch file.
'skv' is not recognized as an internal or external command,
operable program or batch file.
'sv' is not recognized as an internal or external command,
operable program or batch file.
'st' is not recognized as an internal or external command,
operable program or batch file.
'se' is not recognized as an internal or external command,
operable program or batch file.
'sr' is not recognized as an internal or external command,
operable program or batch file.
'sp' is not recognized as an internal or external command,
operable program or batch file.
'sig' is not recognized as an internal or external command,
operable program or batch file.

### Issue script & Debug output

No additional debug output besides the error message

### Expected behavior

Expected to download the files to local destination

### Environment Summary

azure-cli                         2.67.0

core                              2.67.0
telemetry                          1.1.0

Extensions:
load                               1.4.0 (dev) C:\Workspace\Github\azure-cli-extensions\src\load

Dependencies:
msal                              1.31.0
azure-mgmt-resource               23.1.1

Python location 'C:\Program Files\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\mbhardwaj\.azure\cliextensions'
Development extension sources:
    C:\Workspace\Github\azure-cli-extensions

Python (Windows) 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by mbhardwaj-msft** [comment]
I am using PowerShell 7.4.6

**Comment by calvinhzy** [comment]
Hi @mbhardwaj-msft, seems to be caused by the difference when parsing quoted strings between python version 3.9 and newer versions (3.12 here). 
Please add another pair of double quotes within the single quotes like this:
`az storage copy --source '"https://****.*39.blob.storage.azure.net/*****?skoid=*****&sktid=*****&skt=*****&ske=*****&sks=*****&skv=*****&sv=*****&st=*****&se=*****&sr=****&sp=****&sig=****"' --destination 'C:\Workspace\downloads' --recursive`
