### ISSUE TITLE
vmss: improvement on create

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#3051]
1. Default to no balancer for large scaleset
2. Default subnet prefix for app-geteway

**Comment by yugangw-msft** [comment]
//cc:@gbowerman @gatneil

**Comment by gatneil** [comment]
awesome; thanks! :)

**Comment by tjprescott** [comment]
How is this a trivial fix?  It's a breaking change.

**Comment by yugangw-msft** [comment]
Based on the client usage data which I will share with you offline, it is not that big impact
But again, thanks for pointing out this is breaking change

**Comment by yugangw-msft** [comment]
We need to output a warning for at least one release before switch to no balancer

**Comment by yugangw-msft** [comment]
Done

**Comment by yugangw-msft** [comment]
Note, we don't do the `Default to no balancer for large scaleset` at the current point, as so far we have no set command to wire up balancer on existing VMSS.
