### ISSUE TITLE
test

### ISSUE THREAD

**Issue by jsntcy** [Azure/azure-cli#30515]
### Preconditions

- [x] No need to upgrade Python SDK or the Python SDK is ready.

### Related command

test

### Resource Provider

test

### Description of Feature or Work Requested

test

### Minimum API Version Required

test

### Swagger PR link / SDK link

test

### Target Date

test

### PM Contact

test

### Engineer Contact

test

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.
