### ISSUE TITLE
az monitor log-analytics workspace get-schema | broken link in command description

### ISSUE THREAD

**Issue by dbradish-microsoft** [Azure/azure-cli#30511]
### Request to engineering

Please replace the broken link `https://docs.microsoft.com/en-us/rest/api/loganalytics/workspace-schema/get` showing in the `short-summary` of [ az monitor log-analytics workspace get-schema](https://learn.microsoft.com/en-us/cli/azure/monitor/log-analytics/workspace?view=azure-cli-latest#az-monitor-log-analytics-workspace-get-schema).

![Image](https://github.com/user-attachments/assets/14edd8ce-8abb-4a24-a63a-db9cba295b2e)

This link throws a 404

![Image](https://github.com/user-attachments/assets/a83be39a-caef-4916-86c6-6c66ecc82491)

### Related command

 az monitor log-analytics workspace get-schema

### Errors

404

### Issue script & Debug output

.

### Expected behavior

.

### Environment Summary

Azure CLI 2.67.0

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by dbradish-microsoft** [comment]
Closing GitHub issue as it is a duplicate of https://github.com/Azure/azure-cli/issues/29527.
