### ISSUE TITLE
[Reference feedback] Required privileges are not mentioned in the doc

### ISSUE THREAD

**Issue by c3p0-maif** [Azure/azure-cli#30544]
### Type of issue

Missing information

### Reference command name

az ad group ....

### Feedback

When using the command `az ad group show -g groupName` we can have an exception :  
> Insufficient privileges to complete the operation.

In the doc, no sign of required privileges are mentioned.

### Page URL

https://learn.microsoft.com/fr-fr/cli/azure/ad/group?view=azure-cli-latest

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/ad/group.yml

### Author

@dbradish-microsoft

### Document Id

0c7138d1-9849-0b71-8e76-22d0116ff663

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
You may run Azure CLI commands with `--debug`. The log shows the underlying HTTP requests.

Specifically, `az ad group show` internally calls [Get group](https://learn.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&tabs=http) Microsoft Graph API.

As a REST API can change its design and behavior, it is difficult for CLI's document to keep synchronized with the REST API.

**Comment by jiasli** [comment]
Duplicate of https://github.com/Azure/azure-cli/issues/22362
