### ISSUE TITLE
december_2024

### ISSUE THREAD

**Issue by tchatua** [Azure/azure-cli#30556]
### Describe the bug

Unable to run terraform plan on azure

### Related command

az plan

### Errors

[Warning] The login output has been updated. Please be aware that it no longer displays the full list of available subscriptions by default.

### Issue script & Debug output

az login

### Expected behavior

login on az

### Environment Summary

azure cli

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by jiasli** [comment]
Duplicate of https://github.com/Azure/azure-cli/issues/30558
