### ISSUE TITLE
Enable silent install of the azure cli

### ISSUE THREAD

**Issue by piotrpMSFT** [Azure/azure-cli#3058]
### Description
**Outline the issue here:**
The current install.py does not support a silent installation mode. This makes usage of the CLI on build servers cumbersome as it requires updating the base image of the server. If required inputs could be specified when kicking off the script then installation could progress automatically without user interaction and the end-to-end automation scenario would be feasible.

**Comment by troydai** [comment]
@piotrpMSFT can the build servers access to `apt-get`? `az` can be installed from `apt-get`.

**Comment by derekbekoe** [comment]
@piotrpMSFT Like @troydai mentioned, there are other ways to install that are non-interactive.
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli
Do those not satisfy your scenario?

**Comment by piotrpMSFT** [comment]
@troydai @derekbekoe thanks for the quick reply

The available installation mechanisms seem to carry some undesirable characteristics for the build server scenario. Here are characteristics that are important to us:
- Per-User: we can't assume we have root access to our build servers
- Scriptable: we don't want to add  machine setup instructions for new developers/new machines
- Private: we don't want builds to leak changes from e.g. `az component update`
- Reproducable: I know this feature doesn't exist, but I'd love to be able to specify the version of the `azure cli` that I'm downloading so that What I See on my Dev Box is guaranteed to be What I Get on my build server [or my peer's dev box]

CLI install via script seems to give me 3 of the above 4, assuming that I'm able to use the install script within another srcipt.

**Comment by troydai** [comment]
@piotrpMSFT can you please elaborate the third point? What do you mean by "leak changes" from `az component update`?

**Comment by piotrpMSFT** [comment]
as I understand `az component update` it updates the implementation of a component with another implementation. So let's say I have a shared CLI installed, and I run two builds on one build agent:

- BuildA.1: `az appservice ....` <- success
- Build B.1: `az component update appservice` <- success
- Build A.2: `az appservice ....` <- failure because of some difference between the pre-and-post update versions

Does the implementation of `update` guard against this sort of scenario?

**Comment by troydai** [comment]
The chance in which the scenario you described happens is rare in my opinion.

In what case you will run `az component update` during a build? The caller to the CLI is in control of the build script so this is totally avoidable.

It is honestly an unavoidable scenario as long as a tool can be upgraded.

In case you really want to avoid it, the CLI installed through `apt-get` will not have the component update feature.

**Comment by troydai** [comment]
Get back to the original topic, @derekbekoe as far as you know is there a way to provide @piotrpMSFT a mean to install quietly with the script? What change shall we make?

**Comment by piotrpMSFT** [comment]
@troydai agreed regarding rarity, but this is exactly the sort of corner case that ends up causing long and complicated investigations. Nobody wants to deal with build system variability...

**Comment by troydai** [comment]
But you as the build system manager is responsible for how and when you call `az component update`. As long as you don't call it the component module won't be updated. Am I right? Otherwise, if there are scenarios in which CLI voluntarily update/change itself, which I'm not aware of, please let us know the repo steps, which we can address further.

In terms of the silent installation, `apt-get` is the recommended channel. There are CLI dependencies which require the natively installed package, such as `python-dev`, `build-essential` and so on, therefore `apt-get` call is unavoidable. As long as, you're going to install these packages anyway, what's the obstacle for you to install CLI through `apt-get`?

**Comment by derekbekoe** [comment]
@piotrpMSFT I have created https://github.com/Azure/azure-cli/issues/3376 which should address your requirements.
