### ISSUE TITLE
Rolling update vmss

### ISSUE THREAD

**Issue by RutgerP** [Azure/azure-cli#3063]
### Description
Hello,
Is it possible to do a rolling update on a vmss? The only thing I found is az vmss update and az vmss reimage. But the problem is it takes down all the instances and then updates them. Is there an option to say that there has to be atleast 1 instance running? So is there a command in cli or a json template I can use to do this?

My vmss is a simple load balancer, autoscaling website. I have 2 instances running(linux custom image) and would love to do a rolling update with packer and circleci.

**Comment by devigned** [comment]
Good discussion going on here too: https://www.reddit.com/r/AZURE/comments/67unod/rolling_update_vm_scale_set/

**Comment by yugangw-msft** [comment]
Done through #4596. 2 Notes
1. This is still in preview with the hard requirement that you need to have a health probe on the LB
2. Check out the test case in the PR for the end to end flow to provision such VMSS.
