### ISSUE TITLE
[Webapp] VSTS CI/CD config displays stack along with error message

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#3103]
### Description
**Outline the issue here:**

If you attempt to configure VSTS-based CI/CD on a web app, using a Git repo, but omitting the `--cd-account` flag, then you get the following error:

```shell
You must provide a value for cd-account since your repo-url is not a Team Services repository.
Traceback (most recent call last):
  File "/Users/joncart/Library/Python/2.7/lib/python/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/Users/joncart/Library/Python/2.7/lib/python/site-packages/azure/cli/core/application.py", line 201, in execute
    result = expanded_arg.func(params)
  File "/Users/joncart/Library/Python/2.7/lib/python/site-packages/azure/cli/core/commands/__init__.py", line 415, in _execute_command
    exception_handler(ex)
  File "/Users/joncart/Library/Python/2.7/lib/python/site-packages/azure/cli/command_modules/appservice/commands.py", line 52, in _polish_bad_errors
    raise ex
RuntimeError: You must provide a value for cd-account since your repo-url is not a Team Services repository.
```

The error message itself is actually really clear. However, it would be ideal if the stack wasn't also displayed.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip nightly

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

azure-cli (2.0.4+1.dev20170428)

acr (2.0.2+1.dev20170428)
acs (2.0.4+1.dev20170428)
appservice (0.1.4+1.dev20170428)
batch (2.0.2+1.dev20170428)
cloud (2.0.2+1.dev20170428)
command-modules-nspkg (2.0.0+1.dev20170428)
component (2.0.2+1.dev20170428)
configure (2.0.4+1.dev20170428)
container (0.1.4+1.dev20170428)
core (2.0.4+1.dev20170428)
documentdb (0.1.4+1.dev20170428)
feedback (2.0.2+1.dev20170428)
find (0.2.1+1.dev20170428)
iot (0.1.4+1.dev20170428)
keyvault (2.0.2+1.dev20170428)
lab (0.0.3+1.dev20170428)
monitor (0.0.3+1.dev20170428)
network (2.0.4+1.dev20170428)
nspkg (3.0.0+1.dev20170428)
profile (2.0.4+1.dev20170428)
redis (0.2.1+1.dev20170428)
resource (2.0.4+1.dev20170428)
role (2.0.3+1.dev20170428)
sql (2.0.2+1.dev20170428)
storage (2.0.4+1.dev20170428)
vm (2.0.4+1.dev20170428)

Python (Darwin) 2.7.13 (default, Apr  4 2017, 08:47:57) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]

Python location '/usr/local/opt/python/bin/python2.7'

**OS Version:** What OS and version are you using?  
Answer here: macOS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by yugangw-msft** [comment]
//cc: @jpricketMSFT

**Comment by jpricketMSFT** [comment]
@lostintangent - thanks for the feedback. Most error conditions with this feature just throw an error and so you will probably get a call stack. I will try to fix this soon.
