### ISSUE TITLE
[App Service] VSTS account creation doesn't appear to work when configuring CI/CD

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#3104]
### Description
**Outline the issue here:**

The new `--cd-account` flag (for the `az appservice web source-control config --cd-provider vsts` command), indicates that the account will be created if it doesn't already exist. However, when trying to run it, using unique account names, I get the following error:

```shell
POST https://<NAME>.portalext.visualstudio.com/_apis/continuousdelivery/provisioningconfigurations?api-version=3.2-preview.1
response: 404
The resource cannot be found.
Operation returned an invalid status code 'Not Found'
```

Aside from the fact that the command doesn't appear to function correctly, the above error message also isn't particularly user-friendly. It would be ideal if it simply displayed the exception message, as opposed to the details of the underlying HTTP response.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip nightly

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: Nightly 

**OS Version:** What OS and version are you using?  
Answer here: macOS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by lostintangent** [comment]
As an aside, I noticed that if you specify an existing account in the `--cd-account`, that you don't have access to, you get a similarly unfriendly error response. 

```
POST https://foo-bar.portalext.visualstudio.com/_apis/continuousdelivery/provisioningconfigurations?api-version=3.2-preview.1
response: 401
TF400813: The user '72f988bf-86f1-41af-91ab-2d7cd011db47\joncart@microsoft.com' is not authorized to access this resource.
Operation returned an invalid status code 'Unauthorized'
```

It would be ideal if this simply displayed something like `The user '72f988bf-86f1-41af-91ab-2d7cd011db47\joncart@microsoft.com' is not authorized to access this resource.`, as opposed to the HTTP response info.

**Comment by yugangw-msft** [comment]
//cc: @jpricketMSFT

**Comment by jpricketMSFT** [comment]
@lostintangent - you are correct this functionality is still in progress. It will work as expected soon. Right not you have to use an existing vsts account.
Thanks,
Jason

**Comment by jpricketMSFT** [comment]
This feature was completed last week. Let us know if there are any issues.
Thanks,
Jason

**Comment by jpricketMSFT** [comment]
@yugangw-msft - can you close this issue? I don't have access.
