### ISSUE TITLE
Enable creating an issue right from the cli

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-cli#3109]
may be like az bug or az issue
You can collect all the below environment details needed by yourself

### Description
**Outline the issue here:**

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

**OS Version:** What OS and version are you using?  
Answer here:

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

**Comment by tjprescott** [comment]
Or az feedback could be extended in some way. Either way, this would be nice as we could automatically collect certain info to include with the issue instead of hoping people supply it.

**Comment by troydai** [comment]
Maybe we can print an environment information digest in markdown format so the users can copy and past the diagnostics information directly in github issue page.

We can also print stack trace and other information in markdown when the command runs into an error and --debug is specified.

**Comment by JasonRShaver** [comment]
we're looking at improving the situations for providing case-level help on the command line (cli and/or azure), but closing this ticket while we open the issue in another feature
