### ISSUE TITLE
`clear` should clear the terminal in interactive

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#3116]
Currently clear seems to be a nop.

**Comment by tjprescott** [comment]
That's because you have to use # to specify a non-az command.

**Comment by derekbekoe** [comment]
`Ctrl+L` works as well. Standard to bash/unix.

**Comment by oakeyc** [comment]
PR #3118, I originally had 'clear' map to something that clears the history. I changed that to 'clear-history,' and I hooked up 'clear' to clear the screen
