### ISSUE TITLE
Choosing ACS orchestrator version (Kubernetes version)

### ISSUE THREAD

**Issue by DonMartin76** [Azure/azure-cli#3123]
Hey guys,

How do I specify which Kubernetes version I want `az acs create` to provision? I know `acs-engine` supports this.

Right now, I get a 1.5.3 Kubernetes cluster, which is currently fine; I would like to be able to use `az acs create` to create a 1.6.2 cluster for testing purposes as well.

Is this currently possible? Are there plans on getting this in to the `az` command line?

Best regards,
Martin

**Comment by derekbekoe** [comment]
@brendandburns or @colemickens may be able to help here.

**Comment by brendandburns** [comment]
Currently ACS only supports a single version (1.5.3, soon to be 1.6.x)

We are currently working on multi-version support and expect it to roll out in the coming months.

**Comment by brendandburns** [comment]
Closing for now, since this is planned for the future, and currently unactionable.

Please feel free to open an issue in https://github.com/Azure/ACS if you want a tracking issue.

Thanks!
