### ISSUE TITLE
You should be able to call out of a interactive mode scoping

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#3137]
I expect this command set to invoke three total commands without requiring me to leave the scoping.  

%%vm
list
az group list
list
^^vm

The trigger should be a command starting with 'az', it would ignore scoping for that command

**Comment by tjprescott** [comment]
I agreed--until I realize you can already do with with:
`#az group list`

**Comment by mayurid** [comment]
@JasonRShaver : I believe what we have right now is a great start. Lets see if we get more feedback here
