### ISSUE TITLE
az acs kubernetes get-credentials fails when specifying ssh-key-file

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Azure/azure-cli#3138]
As of v2.0.4, I get an error when I use `--ssh-key-file` along with `az acs kubernetes get-credentials` (the command works if my key is in the default location of `~/.ssh/id_rsa`).

I took a look at past commits and I believe https://github.com/Azure/azure-cli/commit/b26248718cc1a66e27836b0c5d238cdc2bfcc997 by @derekbekoe and @brendandburns might've introduced the bug. It looks like 'pkey' is set to 'None' inside 'SecureCopy', but never updated. I also couldn't figure out where the newly-added 'keys' array was used in that function

Here's my full error:
```
No authentication methods available
Traceback (most recent call last):
  File "/opt/az/local/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/opt/az/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 201, in execute
    result = expanded_arg.func(params)
  File "/opt/az/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 417, in _execute_command
    reraise(*sys.exc_info())
  File "/opt/az/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 399, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/opt/az/local/lib/python2.7/site-packages/azure/cli/command_modules/acs/custom.py", line 690, in k8s_get_credentials
    _k8s_get_credentials_internal(name, acs_info, path, ssh_key_file)
  File "/opt/az/local/lib/python2.7/site-packages/azure/cli/command_modules/acs/custom.py", line 711, in _k8s_get_credentials_internal
    '.kube/config', path_candidate, key_filename=ssh_key_file)
  File "/opt/az/local/lib/python2.7/site-packages/azure/cli/command_modules/acs/acs_client.py", line 48, in SecureCopy
    ssh.connect(host, username=user, pkey=pkey)
  File "/opt/az/local/lib/python2.7/site-packages/paramiko/client.py", line 381, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/opt/az/local/lib/python2.7/site-packages/paramiko/client.py", line 623, in _auth
    raise SSHException('No authentication methods available')
SSHException: No authentication methods available
```

**Comment by derekbekoe** [comment]
Is this what https://github.com/Azure/azure-cli/pull/3102 addresses?

**Comment by EricJizbaMSFT** [comment]
Looks like it to me. I still don't get what the point of the 'keys' array is, though.

**Comment by brendandburns** [comment]
@EricJizbaMSFT the keys are loaded from the ssh-agent program.

(although that fix fixes the bug temporarily, we still should consider all keys in that array when doing auth)

**Comment by EricJizbaMSFT** [comment]
I get that part - but where are the keys used? Nowhere at the moment, right? (Although I guess the fix in the PR would use the first key)

**Comment by brendandburns** [comment]
Right, the true fix is to loop through the keys and catch `AuthenticationException` and try the next...

Please file an issue on me and I will fix that.

**Comment by EricJizbaMSFT** [comment]
Seems like that's already covered by this issue: https://github.com/Azure/azure-cli/issues/2612

In any case, I was more concerned about the `--ssh-key-file` scenario. When should I expect the fix to be shipped?

**Comment by brendandburns** [comment]
I'll fix it this evening.


--brendan



________________________________

**Comment by brendandburns** [comment]
Actually, I just tested @ head. The fix from #3102 fixes this problem.

**Comment by EricJizbaMSFT** [comment]
Thanks for verifying the fix - what's the ETA for the new 'acs' package to be published?

**Comment by brendandburns** [comment]
not sure, up to the az CLI team (I'm on the ACS team...)

**Comment by EricJizbaMSFT** [comment]
Ah okay thanks

**Comment by derekbekoe** [comment]
It will be released later this week or next week.
Alternatively, we have nightly builds. Since it was merged today, it'll be available tomorrow.
https://github.com/Azure/azure-cli/#nightly-builds

**Comment by brendandburns** [comment]
(and fwiw, I'm going to improve testing too so that I don't break this again in the future)
