### ISSUE TITLE
'az component update' fails with ImportError: No module named...

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#3141]
### Description
**Outline the issue here:**

![image](https://cloud.githubusercontent.com/assets/16448634/25641188/a5887354-2f47-11e7-8245-e794d9ccdf2f.png)

![image](https://cloud.githubusercontent.com/assets/16448634/25641191/a94919ee-2f47-11e7-87cc-cd0d92d900dd.png)

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: `pip` or `interactive script`

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: any before 2.0.4

**OS Version:** What OS and version are you using?  
Answer here: `Linux` or `OS X`

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: `bash`, `cmd.exe`, Bash on Windows

**Comment by derekbekoe** [comment]
PR with the code fix https://github.com/Azure/azure-cli/pull/3144

PR with the release of the module to PyPI https://github.com/Azure/azure-cli/pull/3145

**Comment by mayurid** [comment]
adding Build milestone to make sure we verify and resolve this
