### ISSUE TITLE
Unable to install on windows using pip (error in azure-mgmt-resource setup command)

### ISSUE THREAD

**Issue by akempe** [Azure/azure-cli#3160]
### Description

When trying to install azure-cli using the Windows command line, I get this error:

`pip install --user azure-cli`

> Downloading/unpacking azure-mgmt-resource==1.0.0rc1 (from azure-cli-acr->azure-cli)
>   Downloading azure-mgmt-resource-1.0.0rc1.zip (219kB): 219kB downloaded
>   Running setup.py egg_info for package azure-mgmt-resource
>     Wheel is not available, disabling bdist_wheel hook
>     error in azure-mgmt-resource setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
>     Complete output from command python setup.py egg_info:
>     Wheel is not available, disabling bdist_wheel hook
> 
> error in azure-mgmt-resource setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

`pip install --user azure-cli`

Python 2.7.13

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

Not installed yet

**OS Version:** What OS and version are you using?  
Answer here:

Microsoft Windows [Version 10.0.15063]

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

cmd.exe

**Comment by derekbekoe** [comment]
@akempe what's the output of `pip --version` and `pip freeze`?
I suspect there's an old version of `pip` or `setuptools`.

**Comment by akempe** [comment]
Right so...

`pip --version`

> pip 1.4.1 from c:\python27 (python 2.7)

I then ran `pip install --upgrade pip` and `pip install --upgrade setuptools` and now get:

> pip 9.0.1 from c:\python27\lib\site-packages (python 2.7)

`pip show setuptools` now shows:

> Version: 35.0.2

This fixed the issue above, but now it's erroring with:

> Collecting azure-datalake-store==0.0.8 (from azure-cli-dls->azure-cli)
>   Using cached azure-datalake-store-0.0.8.tar.gz
>     Complete output from command python setup.py egg_info:
>     Wheel is not available, disabling bdist_wheel hook
>     error in azure-datalake-store setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
> 
> Command "python setup.py egg_info" failed with error code 1 in c:\users\xxx\appdata\local\temp\pip-build-xucp01\azure-datalake-store\

Prior to the pip upgrade, `pip freeze` gave me:

> Fabric==1.7.0
> astroid==1.4.9
> distribute==0.6.49
> isort==4.2.5
> lazy-object-proxy==1.2.2
> mccabe==0.6.1
> mixpanel==4.3.2
> paramiko==1.11.0
> pycrypto==2.6
> pylint==1.6.5
> six==1.10.0
> transifex-client==0.12.4
> urllib3==1.20
> virtualenv==15.0.2
> wrapt==1.10.8

After the update I get:

> appdirs==1.4.3
> astroid==1.4.9
> Fabric==1.7.0
> isort==4.2.5
> lazy-object-proxy==1.2.2
> mccabe==0.6.1
> mixpanel==4.3.2
> packaging==16.8
> paramiko==1.11.0
> pycrypto==2.6
> pylint==1.6.5
> pyparsing==2.2.0
> six==1.10.0
> transifex-client==0.12.4
> urllib3==1.20
> virtualenv==15.0.2
> wrapt==1.10.8

**Comment by derekbekoe** [comment]
@akempe I couldn't repro and we now have an MSI for Windows so closing issue.
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli#windows

**Comment by pipern** [comment]
FYI have the same same issue on Linux (Red Hat Enterprise Linux Server release 7.4 (Maipo)):

```
Downloading/unpacking azure-mgmt-resource==1.2.1 (from azure-cli-acr->azure-cli)
  Downloading azure-mgmt-resource-1.2.1.zip (340kB): 340kB downloaded
  Running setup.py egg_info for package azure-mgmt-resource
    Wheel is not available, disabling bdist_wheel hook
    error in azure-mgmt-resource setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    Wheel is not available, disabling bdist_wheel hook

error in azure-mgmt-resource setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
```

That's with pip 1.4.1 in a virtualenv.

I let pip upgrade itself to pip 10.0.1.

Now the install works.

**Comment by colemickens** [comment]
I'm still having issues with this, and unfortunately am not able to upgrade to pip 10 everywhere.

If anyone has advice on other workarounds, it'd be appreciated.

**Comment by troydai** [comment]
@colemickens what's the PIP version, OS, and Python version you encounter this issue?
