### ISSUE TITLE
Tags are shown as "null" when listing resources by tag name

### ISSUE THREAD

**Issue by agegould** [Azure/azure-cli#3180]
When using the command below, the Tags property is returned as null :-

** az resource list --tag NewTag **
[
  {
    "id": "/subscriptions/4ef077d8-550f-4367-861b-e73ce1114a98/resourceGroups/Development/providers/Microsoft.Storage/storageAccounts/influxury",
    "identity": null,
    "kind": "Storage",
    "location": "westeurope",
    "managedBy": null,
    "name": "influxury",
    "plan": null,
    "properties": null,
    "resourceGroup": "Development",
    "sku": {
      "capacity": null,
      "family": null,
      "model": null,
      "name": "Standard_RAGRS",
      "size": null,
      "tier": "Standard"
    },
    "tags": null,
    "type": "Microsoft.Storage/storageAccounts"
  }
]

However, when no tag name is specified, the Tags property is returned as expected:-

** az resource list **
[
  {
    "id": "/subscriptions/4ef077d8-550f-4367-861b-e73ce1114a98/resourceGroups/Development/providers/Microsoft.Storage/storageAccounts/influxury",
    "identity": null,
    "kind": "Storage",
    "location": "westeurope",
    "managedBy": null,
    "name": "influxury",
    "plan": null,
    "properties": null,
    "resourceGroup": "Development",
    "sku": {
      "capacity": null,
      "family": null,
      "model": null,
      "name": "Standard_RAGRS",
      "size": null,
      "tier": "Standard"
    },
    "tags": {
      "NewTag": "12345"
    },
    "type": "Microsoft.Storage/storageAccounts"
  }
]

### Environment summary

**CLI Version:
Answer here:** 2.0.4 **

**OS Version:** What OS and version are you using?  
Answer here: Windows 10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Windows cmd.exe

**Comment by brendandburns** [comment]
This is a storage bug, I believe, since ARM is just returning what the service returns here...

**Comment by brendandburns** [comment]
I take it back, this is definitely not a storage bug, I'll follow up with ARM team.

**Comment by yonzhan** [comment]
add to S165.

**Comment by yonzhan** [comment]
@armleads-azure any update for this issue?

**Comment by joshsten** [comment]
Also experiencing this.

**Comment by yonzhan** [comment]
@armleads-azure any update for this issue?

**Comment by leylakazemi** [comment]
This work is planned for the 2nd half of the year as part of the backend work that we are doing
