### ISSUE TITLE
Help file validation needs to be part of CI.

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#3188]
Follow up work for PR #3184.

While doing work for `az interactive` we should be able to validate the help files against the command table to find things like:
- [x] missing type (command or group)
- [x] command entries in help that aren't in the command table (for example, a command name changed)
- [x] extra parameters in help that aren't in the command (I think it used to do this, but it should be part of a script and not a runtime error).

**Comment by derekbekoe** [comment]
@williexu is this what your linter does?

**Comment by williexu** [comment]
YES! IT DOES :)
