### ISSUE TITLE
output: An extra line of "?25..." at the end of command output

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#3193]
I am on windows command. This needs to be fixed for //build

![output](https://cloud.githubusercontent.com/assets/6014209/25761641/5ebf4448-3190-11e7-900e-ec408dcfae6b.png)
/build

**Comment by derekbekoe** [comment]
@oakeyc is looking at this as part of https://github.com/Azure/azure-cli/pull/3192

**Comment by yugangw-msft** [comment]
@derekbekoe, thanks!

**Comment by derekbekoe** [comment]
The change was reverted so it's no longer in the product. Closing...
