### ISSUE TITLE
--license-type in az vm create?

### ISSUE THREAD

**Issue by thebitguru** [Azure/azure-cli#3195]
### Description
We would like to deploy Windows servers with the Hybrid Use Benefit.  To do this with 1.0 we could specify `--license-type Windows_Server`, but it seems that 2.0 does not support this flag.  Is this intentional or is there a way to achieve this using 2.0?

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: macOS CLI (tried docker as well)

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.4)

**OS Version:** What OS and version are you using?  
Answer here: mac 10.12.4

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: zsh

**Comment by yugangw-msft** [comment]
@thebitguru , are you willing to install from my fork? Otherwise, I will submit the change the first thing when the master branch is open

**Comment by thebitguru** [comment]
Sure, I can do that. I looked in the [commit history](https://github.com/yugangw-msft/azure-cli/commits/master), but didn't see any obvious commits for this change.  Is it already committed?

**Comment by yugangw-msft** [comment]
@thebitguru, you can either pick up the docker image, or try the nightly tomorrow

**Comment by thebitguru** [comment]
Great, thanks!
