### ISSUE TITLE
[ACS] Allow specifying custom vnet when creating a cluster

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#3196]
### Description
**Outline the issue here:**

It would be great if the `az acs create` command allowed specifying an existing vnet/subnet that the created VMs should be attached to, as opposed to creating a new one. ACS Engine appears to [support this](https://github.com/Azure/acs-engine/blob/master/examples/vnet/kubernetesvnet.json#L19), however, this option isn't expose via the CLI or set in the [underlying template](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py#L563).

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip nightly

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: Nightly

**OS Version:** What OS and version are you using?  
Answer here: macOS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by lostintangent** [comment]
@brendandburns Apologies, I just noticed that this is a dupe of #2856. However, I'm confused why the CLI couldn't simply set the `vnetSubnetId` property in the [template](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py#L563) it generates via the `az acs create` command.

**Comment by brendandburns** [comment]
That would be the vnet of the ACS resource, not the VMs...

**Comment by lostintangent** [comment]
@brendandburns Was this issue closed because the user scenario is solved (or won't fix), or because I misinterpreted the intent of #2856 and/or the `vnetSubnetId` property?

**Comment by brendandburns** [comment]
@lostintangent eventually this will be supported in ACS, but it's not currently, the `vnetSubnetId` property is currently only in ACS-Engine...

**Comment by AmudhaPalani** [comment]
Can you please let me know if there's any update to this? Does az acs create command allow property vnetSubnetId to be set?
