### ISSUE TITLE
vm: expose license type when create windows vm

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#3198]
Need to sort out how many types we have now, in addition to "Windows_Server" and "Windows_Client"

**Comment by derekbekoe** [comment]
Same as https://github.com/Azure/azure-cli/issues/3195?

**Comment by yugangw-msft** [comment]
yes, thanks!

**Comment by thebitguru** [comment]
@yugangw-msft, did you already take care of this? I am having to rewrite some provisioning code as PowerShell to work around this. Any chance you can share this as a patch?  It might be quicker for me to patch my local version than rewrite as PowerShell script.  Thanks!
