### ISSUE TITLE
Docstrings for CLI core methods

### ISSUE THREAD

**Issue by devigned** [Azure/azure-cli#3199]
### Description
`cli_command` and other often used core methods should provide doc string comments. This is particularly important for methods accepting `**kwargs`.

Having this documentation will help developers to understand all of the options available and likely help them to produce better commands. For example, a developer building a command would see they can provide a table transformation with `cli_command`, rather than having to read through the rest of the code to find examples or deep dive into the functionality of the method.

**Comment by tjprescott** [comment]
With the Knack conversion I believe this has been accomplished. If you see specific instances where you think there should be docstrings, please comment and re-open
