### ISSUE TITLE
'vm create' should default to use existing storage account

### ISSUE THREAD

**Issue by iainfoulds** [Azure/azure-cli#321]
When creating a new VM and specifying a storage account with --storage-account-name, the default action is to create new storage account.

While great for the first VM deployment, not so great when you already have a resource group and storage account. Unless you add -debug and see where it's failing, you then get no warning as why your VM failed to be created. It isn't intuitive that when you're specifying the storage account name, that's a name for the account you want to actually create. Adding "--storage-account-type existing" is a little cumbersome and detracts from clean and quick approach.

Suggestion would be to default to using an existing storage account. Bonus points for prompting to create a new one if it doesn't exist in case there was a typo.

**Comment by BurtBiel** [comment]
Fixed.
