### ISSUE TITLE
'public-ip create --allocation-method' is case-sensitive

### ISSUE THREAD

**Issue by iainfoulds** [Azure/azure-cli#322]
az network public-ip create --allocation-method Static

When creating a new public IP, --allocation-method is case-sensitive and will fail when using 'static' rather than 'Static', for example. You get a prompt telling you the available options, which are capitalized, but I can't find other instances that require capitalization.

**Comment by tjprescott** [comment]
Verified that this is fixed, and we have addressed this across modules. If there are isolated incidents of case insensitivity, feel free to open another issue.
