### ISSUE TITLE
az dcos browse returning NoneType found error

### ISSUE THREAD

**Issue by christianhxc** [Azure/azure-cli#3232]
### Description
When running the command to create the tunnel:

`az acs dcos browse -g containers -n containerservice-containers
`

I'm getting the following error:

> coercing to Unicode: need string or buffer, NoneType found
> Traceback (most recent call last):
>   File "C:\Python27\lib\site-packages\azure\cli\main.py", line 36, in main
>     cmd_result = APPLICATION.execute(args)
>   File "C:\Python27\lib\site-packages\azure\cli\core\application.py", line 203, in execute
>     result = expanded_arg.func(params)
>   File "C:\Python27\lib\site-packages\azure\cli\core\commands\__init__.py", line 278, in __call__
>     return self.handler(*args, **kwargs)
>   File "C:\Python27\lib\site-packages\azure\cli\core\commands\__init__.py", line 476, in _execute_command
>     reraise(*sys.exc_info())
>   File "C:\Python27\lib\site-packages\azure\cli\core\commands\__init__.py", line 450, in _execute_command
>     result = op(client, **kwargs) if client else op(**kwargs)
>   File "C:\Python27\lib\site-packages\azure\cli\command_modules\acs\custom.py", line 183, in dcos_browse
>     _dcos_browse_internal(acs_info, disable_browser, ssh_key_file)
>   File "C:\Python27\lib\site-packages\azure\cli\command_modules\acs\custom.py", line 187, in _dcos_browse_internal
>     if not os.path.isfile(ssh_key_file):
>   File "C:\Python27\lib\genericpath.py", line 37, in isfile
>     st = os.stat(path)
> TypeError: coercing to Unicode: need string or buffer, NoneType found

---

### Environment summary

**Install Method:** pip install

**CLI Version:** 2.0.5 (don't know why I can't choose an older version with pip)

**OS Version:** Windows 10 Pro

**Shell Type:** Powershell

**Comment by johnsta** [comment]
Christian, try providing the --ssh-key-file argument, which should include the full path to the SSH private key associated with your cluster.

**Comment by christianhxc** [comment]
I'll give it a try this weekend, I just needed to include the key with Pageant and it was working.

**Comment by christianhxc** [comment]
@johnsta I just tried putting the --ssh-key-file argument and now I get this error:

> Proxy running on 127.0.0.1:52071
> Press CTRL+C to close the tunnel...
> 2017-05-22 09:24:41,393| ERROR   | Could not open connection to gateway
> Could not establish session to SSH gateway
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\main.py", line 36, in main
>     cmd_result = APPLICATION.execute(args)
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\application.py", line 203, in execute
>     result = expanded_arg.func(params)
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 278, in __call__
>     return self.handler(*args, **kwargs)
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 473, in _execute_c
> ommand
>     reraise(*sys.exc_info())
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\six.py", line 686, in reraise
>     raise value
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 450, in _execute_c
> ommand
>     result = op(client, **kwargs) if client else op(**kwargs)
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acs\custom.py", line 183, in dcos_b
> rowse
>     _dcos_browse_internal(acs_info, disable_browser, ssh_key_file)
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acs\custom.py", line 219, in _dcos_
> browse_internal
>     local_port=local_port)
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acs\acs_client.py", line 189, in cr
> eate_tunnel
>     local_bind_address=('0.0.0.0', local_port)):
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\sshtunnel.py", line 1482, in __enter__
>     self.start()
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\sshtunnel.py", line 1224, in start
>     reason='Could not establish session to SSH gateway')
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\sshtunnel.py", line 1036, in _raise
>     raise exception(reason)
> sshtunnel.BaseSSHTunnelForwarderError: Could not establish session to SSH gateway

I even disabled the firewall but no success

**Comment by christianhxc** [comment]
Ok, it worked but I needed to add the key with Pageant. I ran the same command with --debug and saw that it said "Authentication (publickey) failed" so I thought it wasn't putting the correct username then I added the key with Pageant and it worked.

**Comment by mboersma** [comment]
@tjprescott this issue can be closed now.
