### ISSUE TITLE
[ACS] Default ACS value isn't respected by the delete, show or scale commands

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#3233]
### Description
The `acs delete`, `acs show` and `acs scale` commands don't seem to support their `--name` parameter being defaulted if you set it via `az configure -d acs=<foo>`. All other commands (e.g. `az acs browse`,`az acs install-cli`), support it, so it would be awesome if all of the commands within the `acs` group provided consistent behavior.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: nightly

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: nightly

**OS Version:** What OS and version are you using?  
Answer here: macOS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by yugangw-msft** [comment]
closing as `az acs` is deprecating
