### ISSUE TITLE
[RBAC] Role definition JSON mismatch

### ISSUE THREAD

**Issue by jboeshart** [Azure/azure-cli#3250]
### Description
When creating the role definition using a definition file, the nomenclature on the commands does not line up with the nomenclature in the definition file. Using the below definition file and `list` output, the following mismatches exist. See the following table for the corresponding elements. Each is mismatched, and the `--name` parameter actually corresponds to the `roleName` element output from the command. Seems like the output of the create and list operations could be aligned with the definition file and with the output from the `Get-AzureRmRoleDefinition` cmdlet.

| Definition File | Create/List Output |
|---|---|
| Name | roleName |
| Id | name |
| full resource id (not actually in file) | id |

Role definition file:
```
{
  "Name": "Role1",
  "Id": "eba5c82d-7a1c-4a3b-9a86-82a9abcfa83e",
  "IsCustom": true,
  "Description": "Test role",
  "Actions": [
    "Microsoft.Authorization/*",
    "Microsoft.Support/*"
  ],
  "NotActions": [
  ],
  "AssignableScopes": [
    "/subscriptions/a049a5ae-8a50-4a84-9a3c-abbfa1eac3a3"
  ]
}
```

Results of `list` operation for the specific role:
```
C:\WINDOWS\system32>az role definition list --name "Role1"
[
  {
    "id": "/subscriptions/a049a5ae-8a50-4a84-9a3c-abbfa1eac3a3/providers/Microsoft.Authorization/roleDefinitions/eba5c82d-7a1c-4a3b-9a86-82a9abcfa83e",
    "name": "eba5c82d-7a1c-4a3b-9a86-82a9abcfa83e",
    "properties": {
      "assignableScopes": [
        "/subscriptions/a049a5ae-8a50-4a84-9a3c-abbfa1eac3a3"
      ],
      "description": "Test role",
      "permissions": [
        {
          "actions": [
            "Microsoft.Authorization/*",
            "Microsoft.Support/*"
          ],
          "notActions": []
        }
      ],
      "roleName": "Role1",
      "type": "CustomRole"
    },
    "type": "Microsoft.Authorization/roleDefinitions"
  }
]
```

PowerShell output:
```
PS C:\> get-azurermroledefinition -name Role1


Name             : Role1
Id               : eba5c82d-7a1c-4a3b-9a86-82a9abcfa83e
IsCustom         : True
Description      : Test role
Actions          : {Microsoft.Authorization/*, Microsoft.Support/*}
NotActions       : {}
AssignableScopes : {/subscriptions/a049a5ae-8a50-4a84-9a3c-abbfa1eac3a3}
```
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli#windows via pip install method.

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
azure-cli (2.0.4)

acr (2.0.2)
acs (2.0.4)
appservice (0.1.4)
batch (2.0.2)
cloud (2.0.2)
command-modules-nspkg (2.0.0)
component (2.0.3)
configure (2.0.4)
container (0.1.4)
core (2.0.4)
documentdb (0.1.4)
feedback (2.0.2)
find (0.2.1)
iot (0.1.4)
keyvault (2.0.2)
lab (0.0.3)
monitor (0.0.3)
network (2.0.4)
nspkg (3.0.0)
profile (2.0.4)
redis (0.2.1)
resource (2.0.4)
role (2.0.3)
sql (2.0.2)
storage (2.0.4)
vm (2.0.4)

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

**OS Version:** What OS and version are you using?  
Answer here:
Windows 10 - creators update

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
cmd

**Comment by yugangw-msft** [comment]
This is mostly server behavior. And I agree we can use more client side transformation for more consistency
