### ISSUE TITLE
(recent version) pip install azure-cli (with or without --pre) fails: azure-nspkg not found

### ISSUE THREAD

**Issue by rubin55** [Azure/azure-cli#3264]
### Description
Installed Python 3.5.3, came with pip 9.0.1 (latest, pip install --upgrade pip tells me so)
    
    pip install azure-cli 

and  

    pip install --pre azure-cli

fail with:
``` 
Collecting azure-nspkg>=2.0.0 (from azure-cli-nspkg->azure-cli)
Could not find a version that satisfies the requirement azure-nspkg>=2.0.0 (from azure-cli-nspkg->azure-cli) (from versions: 1.0.0rc1, 1.0.0rc2, 1.0.0)
No matching distribution found for azure-nspkg>=2.0.0 (from azure-cli-nspkg->azure-cli)
```

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Installed python 3.5.3, came with pip 9.0.1, then: 'pip install azure-cli'

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
N/A.

**OS Version:** What OS and version are you using?  
Windows 10 Pro x64  [Version 10.0.15063]

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
cmd.exe

**Comment by rubin55** [comment]
Note: In my case, specifying --pre did not work globally because of this (bug?) in pip: https://github.com/pypa/pip/issues/4468 . I passed --install-option to control where the scripts are installed and this clobbers --pre specification, resulting in unresolvable packages.

So to clarify: 

BAD: Stable packages are pointing to pre-release package dependencies which are unresolvable. This should be fixed imho.

GOOD: As a workaround, specifying --pre without --install-option makes azure-cli install correctly (it does mean you have to install the pre release version - I tried mixing only pre-release packages for the requirements that demanded so, but that resulted in some commands, like az sql db list backtracing).

**Comment by derekbekoe** [comment]
Looks like this is working and azure-nspkg is available on PyPI at https://pypi.python.org/pypi/azure-nspkg.

I ran the commands below and it installed fine.

```
$ sudo docker run -it python:3.5 bash
$ python --version
Python 3.5.3
$ pip install azure-cli
$ az
```

**Comment by sai306** [comment]
Could not install Azure CLi 2.

I am trying these steps. I got an error in the second command. Please help..

pip install --pre --user azure-nspkg 
pip install --pre --user azure-multiapi-storage
pip install azure-cli

C:\Users\vSai>pip install --pre --user azure-multiapi-storage
Collecting azure-multiapi-storage
  Could not fetch URL https://pypi.python.org/simple/azure-multiapi-storage/: There was a problem confirming the ssl certificate: unknown error (_ssl.c:3566) - skipping
  Could not find a version that satisfies the requirement azure-multiapi-storage (from versions: )
No matching distribution found for azure-multiapi-storage

**Comment by derekbekoe** [comment]
The error has `There was a problem confirming the ssl certificate: unknown error (_ssl.c:3566) - skipping` which indicates an SSL issue on the machine.
Also, it looks like you're on Windows. We have a Windows MSI https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest
