### ISSUE TITLE
Limit of 100 alerts per Subscription

### ISSUE THREAD

**Issue by jefffall** [Azure/azure-cli#3276]
### Description
**Outline the issue here:**

We need more than 100 Alerts per subscription.

We have 250+ VM's in one Subscription.

We also need to know how Azure figures out
Warning, 
Critical and resolved alerts.

We see alerts self resolving.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

curl -L https://aka.ms/InstallAzureCli | bash

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

2.0.5

**OS Version:** What OS and version are you using?  
Answer here:

macOS Sierra

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

csh

**Comment by tjprescott** [comment]
Hi @jefffall, in order to increase your subscription limit, you'd need to open a support request from inside the portal. From any resource blade (a VM for instance) choose "New Support Request" at the bottom. 

Choose Issue Type "Quota" and Quota type "Questions or Other service and subscription limits".

**Comment by tjprescott** [comment]
> We also need to know how Azure figures out
> Warning,
> Critical and resolved alerts.
> We see alerts self resolving.

@johnkemnetz

**Comment by jefffall** [comment]
Thank you Travis.

As my previous boss many years used to say:

"You are an Ace".

"You are a Gem".

Coming from my old boss Larry - those were high complements.

**Comment by jefffall** [comment]
Hi Travis,

  is this limit cast in stone?


Can we go to 1000 or even higher?


Has it been done for certain customers?

My employer is a fortune 50 probably

Resource 	Limit
Autoscale Settings 	100 per region per subscription
Metric Alerts 	100 active alert rules per subscription

**Comment by tjprescott** [comment]
Hi @jefffall, I don't personally know the limits for the Azure Monitor service, but if you create a support ticket in the portal, they should be able to bump up your subscription's limit (assuming it is possible for this service).  

@johnkemnetz, @gucalder might be able to shed light on this question as well.

**Comment by snehithm** [comment]
Hi @jefffall, the [default quota limit for new metric alerts has been made 1000 per subscription.](https://docs.microsoft.com/azure/azure-subscription-service-limits#alerts) For classic alerts which are [getting retired soon](https://azure.microsoft.com/updates/azure-monitor-classic-alerts-retirement-date-extended-to-august-31st-2019/), the default limit is at 100.

@tjprescott can you please this issue?
