### ISSUE TITLE
azure login: for service principal, do not acquire token for every single request,rather look up the cache first

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#330]
for operations happening within our hour, this saves a around trip to azure AAD server for each request

**Comment by tjprescott** [comment]
@yugangw-msft is this still an issue?

**Comment by yugangw-msft** [comment]
@tjprescott  yes

**Comment by tjprescott** [comment]
@yugangw-msft now is this still an issue? :grin:

**Comment by grgarcia-ms** [comment]
when is this happening? would be very useful to aml workbench
