### ISSUE TITLE
Investigate az interactive start and exit performance

### ISSUE THREAD

**Issue by mayurid** [Azure/azure-cli#3306]
### Description
Start is fairly slow
Exit also has a perceivable delay and i see "Have a lovely day!!" and wait for prompt to show

---

### Environment summary

**OS Version:** What OS and version are you using?  
Answer here: Windows 10 (Creators update)

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd

**Comment by oakeyc** [comment]
related to #3019
