### ISSUE TITLE
[Monitor] Alert rule update fails due to service bug

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#3311]
Due to a service bug (https://github.com/Azure/azure-rest-api-specs/issues/1211) the alert-rule update command will fail unless you manually specify the condition operator, because this field is not returned from the service (but should be).  Issue for tracking purposes.

cc/ @johnkemnetz

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: dev_setup.py

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: latest master

**OS Version:** What OS and version are you using?  
Answer here: Win10CU

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

**Comment by snehithm** [comment]
@tjprescott, looks like the service bug is fixed. Does this need a fix for CLI?

If not, can you close this issue?

**Comment by tjprescott** [comment]
Thanks @snehithm. Closing.
