### ISSUE TITLE
[Key Vault] InsecureRequestWarning

### ISSUE THREAD

**Issue by devigned** [Azure/azure-cli#3314]
### Description
See: https://github.com/Azure/azure-sdk-for-python/issues/1162

Current master causes raises this warning.

```
$ az keyvault certificate list --vault-name vault_name
python3.5/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
[
  {
    ...
  }
]
```

---

### Environment summary

**Install Method: source**

**CLI Version: master 047d00e9**

**OS Version: OS X**

**Shell Type: bash**

**Comment by derekbekoe** [comment]
This was the commit where we changed the SDK version https://github.com/Azure/azure-cli/commit/1e4e0505248a37d8957db58ef66ba79d76e4c43e

**Comment by derekbekoe** [comment]
@tjprescott should we revert this change until SDK is fixed?

**Comment by tjprescott** [comment]
Yes.  We can just go back to using 0.3.0.

**Comment by tjprescott** [comment]
This should be fixed now.
