### ISSUE TITLE
[DevTestLabs] Enable more Lab vm commands

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-cli#3317]
**Scenario:**
I am a student and I use pre-created VMs in the classroom Lab to do my assignment.  I need to be able to:

- [x] List claimable VMs
- [x] Claim a VM
- [x] Claim any – The system picks one for me – I do not specify which one

**CC**
@ericame @gxy001

**Comment by vishrutshah** [comment]
- [ ] List claimable VMs

```
az lab vm list -g MyRG --lab-name MyLab --claimable -o table
```

- [ ] Claim a specific VM from the lab

```
az lab vm claim -g MyRG --lab-name MyLab --name MyVM
```
```
az lab vm claim --ids /subscriptions/{SubID}/resourcegroups/{MyRG}/providers/microsoft.devte
        stlab/labs/{MyLab}/virtualmachines/{MyVM1} /subscriptions/{SubID}/resourcegroups/{MyRG}/prov
        iders/microsoft.devtestlab/labs/{MyLab}/virtualmachines/{MyVM2}
```

- [ ] Claim any available VM from the lab

```
az lab vm claim -g MyRG --lab-name MyLab
```

**Comment by gxy001** [comment]
Is it possible to rename -g to --lab-resourcegroup (or --lab-rg) so as to reduce confusion which resource group (lab's or VM's) it is?

**Comment by vishrutshah** [comment]
@gxy001 Yes it is possible to do it in CLI. I'll open a separate bug for that as It has to be done for all the commands not just `az lab vm`.

**Comment by vishrutshah** [comment]
Closing this in favor of https://github.com/Azure/azure-cli/issues/3418
