### ISSUE TITLE
login: expose ADFS flow for azure stack env

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#3319]

**Comment by bganapa** [comment]
Three things to fix are
1.	Passing validate_authority as false in case of adfs
2.	Removing TenantId from the token request url incase of adfs
3.	Detect the environment as ADFS from the az cloud register command or from the authority url

**Comment by yugangw-msft** [comment]
@bganapa, those are the workaround we made to get you testing going. I will first cross check adal-python's implementation to ensure it does things right for adfs on-prem, particularly inline with adal-dotnet

**Comment by bganapa** [comment]
@yugangw-msft  Thank you.  You are the expert in auth:)
