### ISSUE TITLE
az vm open-port returns error but executes successfully

### ISSUE THREAD

**Issue by larryms** [Azure/azure-cli#3322]
### Description
az vm open-port returns an error but executes successfully

Example:
PS C:\Users\larry> az vm open-port -g JUMPBOXRG -n jumpbox --port 80  --priority 500
Operation failed with status: 'Not Found'. Details: 404 Client Error: Not Found for url: https://management.azure.com/subscriptions/5ba80c27-8c76-[***]/providers/Microsoft.Network/locations/eastus/operations/5c5fa1c7-3e4a-4dd3-[***]?api-version=2017-03-01

Error occurs on Windows & Linux
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Windows:  pip.  Linux: apt-get

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
2.0.6

**OS Version:** What OS and version are you using?  
Windows 10, Ubuntu 17.04

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Powershell, Bash

**Comment by tjprescott** [comment]
When you say it executes successfully, do you mean the port is open as expected or just that it returns the result in white text (instead of red error text)?

**Comment by tjprescott** [comment]
This is happening when the command tries to update the NIC. The reason the command still "succeeds" (from a functional perspective) is because the NIC doesn't need to be updated since it is already associated with the NSG.  I'll create a fix to avoid updating the NIC/subnet when the NSG already existed and investigate if this happens when the NSG does need to be created.

**Comment by tjprescott** [comment]
The root cause of this is issue #3330. I'll keep this open to track fixing the fact that we unnecessarily attempt to update the NIC/subnet in some cases.

**Comment by alexeyshishkin01** [comment]
when the fix is supposed to be available?
how to grab it?

**Comment by rbrisita** [comment]
@alexeyshishkin01 try:
`az component update`

**Comment by tjprescott** [comment]
@alexeyshishkin01 the fix is included in the most recent release.

**Comment by alexeyshishkin01** [comment]
hi there, I don't use 'az component', instead I've updated via apt-get and tested - it finally works! thanks!
