### ISSUE TITLE
Command paths should be case insensitive

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#3325]
Example. This works:
  az network dns record-set a show
This fails:
  az network dns record-set A show
That's strange, since DNS record types are normally capitalized!
The record type, in all DNS commands, should be case-insensitive.

**Comment by tjprescott** [comment]
This actually applies to the entire CLI.  If I type `az Network -h` I get an error that "Network" is an invalid choice!  We should force the "command part" of the input to lowercase before we try to match it to commands.

**Comment by derekbekoe** [comment]
I would say this is open to discussion if the issue is for the whole CLI in general...

**Comment by tjprescott** [comment]
It applies to the entire CLI.  Do you see any reason the command "path" should be case sensitive?

**Comment by jtuliani** [comment]
Thinking about other CLIs, folks are used to command *switches* being case sensitive. E.g. "git branch -d" is different from "git branch -D".

However, I see no reason for the command *path* to be case sensitive.

**Comment by tjprescott** [comment]
@jtuliani I agree.

**Comment by derekbekoe** [comment]
Makes sense. I was thinking of command path and command params as one.

**Comment by jtuliani** [comment]
Brilliant, thanks Travis
