### ISSUE TITLE
[DNS] 'show' on empty record set doesn't show empty record list

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#3326]
If I do 'az network dns record-set show', I get shown the record set details. That includes the list of records in the record set.

However, if the record set is empty (no records), then the empty record set list is NOT shown. That's bad. I'm left looking for it. It's quite a jump to realize the record set must have no records because the list isn't shown.

By contrast, if there is no metadata associated with the record set, we DO show an empty metadata list, to make that explicit.

Empty record sets (of all types) should show their empty record list explicitly. Note that the list property name varies with record type. This applies to the 'show' command and also any other command that displays record set data (e.g. list, or when creating an empty record set, etc)

**Comment by tjprescott** [comment]
Likely a side effect of #2095.
