### ISSUE TITLE
Azurestack: Infrastructure of tests needed against azure with older profiles 2017-03-09-profile

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-cli#3336]
### Description
Azure stack uses the profile 2017-03-09-profile . We need minimal tests with this profile to make sure that this profile is not broken.

---

**Comment by mayurid** [comment]
@troydai to pick up the PR https://github.com/Azure/azure-cli/pull/3056#issuecomment-298040722 and provide the infrastructure piece.

**Comment by troydai** [comment]
This is in now. I'm working on refining the documentation.
