### ISSUE TITLE
Azurestack: az vm images list  returns a cached response which is not applicable for azurestack

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-cli#3338]
### Description
az vm images list right now lists a cached response. The images listed in this are not likely available in azure stack instance.

In azure stack the admin uploads the images as part of the initial setup and he may upload only a specific set of images.

az vm images list --all actually makes the api call and gets the right set of images. May be the solution is to make --all as the default and use the cached data only for TabTab completion

**Comment by mayurid** [comment]
Not sure if --all is default behavior or having user pass profile or make a call in the context of profile they are in. @yugangw-msft and @derekbekoe to discuss as well

**Comment by yugangw-msft** [comment]
@derekbekoe, @tjprescott 
I suggest we detect under azure stack, and if yes, we do not expose `--all` and always makes api call. We should not use cached data under all circumstances

**Comment by bganapa** [comment]
agree with Yugang,  a complicated solution would be to maintain a per cloud on demand cache

we could do the following.
1.	Keep an empty cache of per cloud images, instead of prepopulating with a standard  set(cache may be persisted in file)
2.	If the cache is empty,  make the api call and populate the per cloud cache
3.	If the cache is not empty, show it from the just like we do now
With this only the first call is going to be costly. I am not sure how often these set of images are changed in azure and if so often we may need to force invalidate the cache. Or I am fine with making the –all default and incurring the cost every time instead of showing the wrong list of images for azurestack.
