### ISSUE TITLE
AzureStack: images aliases is not applicable for azurestack

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-cli#3340]
### Description
CLI has a set of aliases for the images referred from the following location
https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json

These aliases makes the assumption that these images are available in all the clouds and matches the 
definition like below
          "UbuntuLTS":{
            "publisher":"Canonical",
            "offer":"UbuntuServer",
            "sku":"16.04-LTS",
            "version":"latest"
          }

In azure stack , the alias does not make much sense as the admin may not have uploaded the same image
in azure stack the Ubuntu server sku could be 14.04.3 instead of 16.04-LTS

luckily , the image parameter can be specified with the whole urn like below and this is what being used in azurestack 
Canonical:UbuntuServer:14.04.3-LTS:1.0.0

All the public documentation is referring to the use of aliases and the aliases most likely wont work against azurestack unless the admin chooses to upload image matching the azure definitions

**Comment by mayurid** [comment]
@yugangw-msft and@derekbekoe to discuss for upcoming sprint.

**Comment by yugangw-msft** [comment]
@derekbekoe @tjprescott 
I suggest detect we are under stack, and update 2 trivial code lines
1. In the [help for vm/vmss create](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py#L10), remove the alias
2. skip the [alias check](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py#L141) in the command validator

**Comment by bganapa** [comment]
I am inclined to take the following approach for the use of image alias.
1.	Keep the alias and the –image parameter as such for all the profiles
2.	When the image parameter is specified for the vm create, Check explicitly with an api call whether the image exists in the current cloud
3.	If the image does not exist, provide a proper message encouraging the use of image urn 
like ‘The image urn Canonical:UbuntuServer:16.04-LTS:1.0.0 does not exist in the current cloud, please use the urn for the image parameter by executing  az vm image list and pick from the available images’
Right now we don’t check for the availability of the image beforehand and fire up the template deployment immediately and it takes minutes to return an error. I am ok to display the error message rather than complicating the solution and we can wait for customer feedback .
