### ISSUE TITLE
VMCreate: Update key gen message

### ISSUE THREAD

**Issue by jluk** [Azure/azure-cli#3342]
### Description
**Outline the issue here:**
Need to update keygen message to remove cloud shell reference. Opening issue here per thread with Mayuri/Yugang.

New string:
SSH key files ‘id_rsa.pub’ and ‘id_rsa’ have been generated under ~/.ssh to allow SSH access to the VM. If using machines without permanent storage, back up your keys to a safe location.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

**OS Version:** What OS and version are you using?  
Answer here:

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

**Comment by mayurid** [comment]
approved to @yugangw-msft for upcoming sprint.
