### ISSUE TITLE
[VMSS] `az vmss create` should build a NSG

### ISSUE THREAD

**Issue by devigned** [Azure/azure-cli#3347]
### Description

When creating a VMSS, I'd expect the instances to reside within a subnet protected by a network security group similar to `az vm create`.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: source

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: master

**OS Version:** What OS and version are you using?  
Answer here: OS X

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by yugangw-msft** [comment]
Supported now through `--nsg`
