### ISSUE TITLE
[Monitor] Autoscale-settings "autoscale-parameters-template.json" file not included with PIP install

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#3349]
After doing a PIP install, if I run `az monitor autoscale-settings get-parameters-template` I get the following error:
```
File C:\Users\trpresco\Documents\github\env3\lib\site-packages\azure\cli\command_modules\monitor\autoscale-parameters-template.json not found.
```

It seems like the JSON file that is embedded in the command module for a dev_setup does not get included in the final package. 

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.6)

acr (2.0.4)
acs (2.0.6)
appservice (0.1.6)
batch (2.0.4)
cdn (0.0.2)
cloud (2.0.2)
cognitiveservices (0.1.2)
command-modules-nspkg (2.0.0)
component (2.0.4)
configure (2.0.6)
core (2.0.6)
cosmosdb (0.1.6)
dla (0.0.6)
dls (0.0.6)
feedback (2.0.2)
find (0.2.2)
interactive (0.3.1)
iot (0.1.5)
keyvault (2.0.4)
lab (0.0.4)
monitor (0.0.4)
network (2.0.6)
nspkg (3.0.0)
profile (2.0.4)
rdbms (0.0.1)
redis (0.2.3)
resource (2.0.6)
role (2.0.4)
sf (1.0.1)
sql (2.0.3)
storage (2.0.6)
vm (2.0.6)

**OS Version:** What OS and version are you using?  
Answer here: Win10CU

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

**Comment by derekbekoe** [comment]
This is a bug in the setup.py of the module. The file should be included in the setup.py file of the module.
https://docs.python.org/2/distutils/setupscript.html#installing-package-data

**Comment by vishrutshah** [comment]
Thanks @tjprescott for finding this & @derekbekoe for point to the solution. Let me fix this soon
