### ISSUE TITLE
Public IP creation with --version parameter

### ISSUE THREAD

**Issue by kasunsjc** [Azure/azure-cli#3350]
### Description
When I run the following command it should create IPv4 IP address but as an output I get versions of each Azure CLI modules

**Command**
network  public-ip create --name linuxvm --resource-group clivm --allocation-method Dynamic --location southeastasia --version "IPv4" --verbose

**Output**
azure-cli (2.0.6)

acr (2.0.4)
acs (2.0.6)
appservice (0.1.6)
batch (2.0.4)
cdn (0.0.2)
cloud (2.0.2)
cognitiveservices (0.1.2)
command-modules-nspkg (2.0.0)
component (2.0.4)
configure (2.0.6)
core (2.0.6)
cosmosdb (0.1.6)
dla (0.0.6)
dls (0.0.6)
feedback (2.0.2)
find (0.2.2)
interactive (0.3.1)
iot (0.1.5)
keyvault (2.0.4)
lab (0.0.4)
monitor (0.0.4)
network (2.0.6)
nspkg (3.0.0)
profile (2.0.4)
rdbms (0.0.1)
redis (0.2.3)
resource (2.0.6)
role (2.0.4)
sf (1.0.1)
sql (2.0.3)
storage (2.0.6)
vm (2.0.6)

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'

What I did was I remove the version parameter and run the command and It works as I expected

**Command**
az network  public-ip create --name linuxvm-ip --resource-group clivm --location southeastasia --verbose

**Output**
```
{
  "publicIp": {
    "dnsSettings": null,
    "etag": "W/\"e102dba5-471b-49c9-a6c6-55db94c410a8\"",
    "id": "/subscriptions/<SubscriptionID>/resourceGroups/clivm/providers/Microsoft.Network/publicIPAddresses/linuxvm-ip",
    "idleTimeoutInMinutes": 4,
    "ipAddress": null,
    "ipConfiguration": null,
    "location": "southeastasia",
    "name": "linuxvm-ip",
    "provisioningState": "Succeeded",
    "publicIpAddressVersion": "IPv4",
    "publicIpAllocationMethod": "Dynamic",
    "resourceGroup": "clivm",
    "resourceGuid": "6c3bdf50-acbd-4395-8b81-20f73215f85c",
    "tags": null,
    "type": "Microsoft.Network/publicIPAddresses"
  }
}
```
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.6)

**OS Version:** What OS and version are you using?  
Answer here: Windows 10 Creates Update

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: CMD.exe

**Comment by mayurid** [comment]
@troydai to take a look

**Comment by troydai** [comment]
@kasunsjc, thanks for reporting the issue. However, I'm not able to repo this issue locally. I tried on both Windows and Linux.

```
C:\Users\troydai>az network public-ip create --name linuxvm --resource-group trdai-permanent --allocation-method Dynamic --location southeastasia --version "IPv4" --verbose -ojson
{
  "publicIp": {
    "dnsSettings": null,
    "etag": "W/\"9cd6a5b7-5ca8-4fdf-8d08-628bc9a3fe32\"",
    "id": "/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/resourceGroups/trdai-permanent/providers/Microsoft.Network/publicIPAddresses/linuxvm",
    "idleTimeoutInMinutes": 4,
    "ipAddress": null,
    "ipConfiguration": null,
    "location": "southeastasia",
    "name": "linuxvm",
    "provisioningState": "Succeeded",
    "publicIpAddressVersion": "IPv4",
    "publicIpAllocationMethod": "Dynamic",
    "resourceGroup": "trdai-permanent",
    "resourceGuid": "8c3acacc-a6a3-4aac-b013-469dd0fb8f3d",
    "tags": null,
    "type": "Microsoft.Network/publicIPAddresses"
  }
}
```

Would you please try upgrade your CLI to the `2.0.7`?

**Comment by derekbekoe** [comment]
I believe @tjprescott fixed this.

**Comment by tjprescott** [comment]
At least according to git blame, I didn't fix this, but I'd be happy to take credit.  I did however, just verify that this behavior occurs using `az interactive`. The reason is because it simply looking for "--version" in the text of the command, so it will do this for any commands that have --version parameters.  @oakeyc
