### ISSUE TITLE
After installed azure-cli, some users' pip is down

### ISSUE THREAD

**Issue by Sneezry** [Azure/azure-cli#3353]
### Description
**Outline the issue here:**
After installed azure-cli, some users' pip is down.

In the screenshot, you may see we are trying to install pip, however, you can see the error is thrown when we call `pip --version`, and pip has been already broken.

I'm not sure if it is related, but I find a similar issue in one of Google's projects https://github.com/GoogleCloudPlatform/google-cloud-python/issues/1570 

![](https://cloud.githubusercontent.com/assets/5545529/25689994/65656056-30bf-11e7-8922-d7605b0b1267.png)
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
`pip install -r https://github.com/Azure/azure-cli/blob/master/packaged_releases/pip_requirements/0.2.5_python27.txt`

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
azure-cli 2.0.3
As azure-cli is not installed correct, and pip is down, we cannot know modules' version on users' machine

**OS Version:** What OS and version are you using?  
Answer here:
Microsoft Windows [Version 10.0.15063]

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
cmd.exe

**Comment by derekbekoe** [comment]
@Sneezry this should be fixed in more recent versions of the CLI.
This error occurred during a transition in how we created the Python packages.
