### ISSUE TITLE
[CognitiveServices] Could the create command include param enums?

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#3358]
### Description

When looking at the help for the `az cognitiveservices account create` command, neither the `--kind` nor `--sku` params display an enumerated set of allowable values. From the example provided in the help text, you can see that `Face` is an acceptable input for `--kind`, but it would be awesome if you could easily see the complete list of kinds + have auto-completion (e.g. like you have with `az cosmosdb create --kind`).

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: nightly

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: nightly

**OS Version:** What OS and version are you using?  
Answer here: macOS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by mayurid** [comment]
@kostenray to comment.

**Comment by tjprescott** [comment]
@pchoudhari
