### ISSUE TITLE
[MySQL/Postgres] Can't list servers across a subscription

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#3359]
### Description

The `az mysql server list` (and `az postgres server list`) commands currently require specifying a resource group, which isn't consistent with most of the other `list` commands in the CLI. It would be great if these commands allowed omitting the group, and simply specifying it when you want to filter the list to a specific group.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: nightly

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: nightly

**OS Version:** What OS and version are you using?  
Answer here: macOS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by mayurid** [comment]
@Suna-MS for this issue.

**Comment by Suna-MS** [comment]
Will fix it.

**Comment by mayurid** [comment]
@Suna-MS : Added this to upcoming milestone.

**Comment by Suna-MS** [comment]
Fixed in https://github.com/Azure/azure-cli/pull/3417, and merged

**Comment by mayurid** [comment]
@lostintangent : Please feel free to reactivate if you still have concerns. You can try the latest docker image
