### ISSUE TITLE
Storage locking on VM Smart Create

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#336]
I created a new, empty subscription and tried to follow our demo steps and ran into a number of issues relating to using an ARM template for deployment.

_Example Error #1_
Long running operation failed with status 'Failed' {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see http://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "Conflict",
            "message": "{\r\n  \"error\": {\r\n    \"code\": \"StorageAccountAlreadyTaken\",\r\n    \"message\": \"The storage account named vhdstorageki7qdyzg6loo2 is already taken.\"\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}

_Example Error #2_
Long running operation failed with status 'Failed' {
  "error": {
    "code": "DeploymentActive",
    "message": "Unable to edit or replace deployment 'demo100vmNicIp': previous deployment from '5/27/2016 3:49:49 PM' is still active (expiration time is '6/3/2016 3:49:47 PM'). Please see http://aka.ms/arm-deploy for usage details."
  }
}

**Comment by yugangw-msft** [comment]
Nothing left to do
