### ISSUE TITLE
az storage cors throws python exception

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-cli#3362]
### Description
Run the command `az storage cors add --connection-string $connstr --methods GET --origins * --services blob`

Output:

```
'l'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/application.py", line 203, in execute
    result = expanded_arg.func(params)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 278, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 473, in _execute_command
    reraise(*sys.exc_info())
  File "/usr/local/lib/python3.5/site-packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 450, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/azure/cli/command_modules/storage/custom.py", line 438, in add_cors
    properties = SERVICES[character]
KeyError: 'l'
```
---

### Environment summary

**Install Method:** Docker

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.6+dev)

acr (2.0.4+dev)
acs (2.0.6+dev)
appservice (0.1.6+dev)
batch (2.0.4+dev)
cdn (0.0.2+dev)
cloud (2.0.2+dev)
cognitiveservices (0.1.2+dev)
command-modules-nspkg (2.0.0+dev)
component (2.0.4+dev)
configure (2.0.6+dev)
core (2.0.6+dev)
cosmosdb (0.1.6+dev)
dla (0.0.6+dev)
dls (0.0.6+dev)
feedback (2.0.2+dev)
find (0.2.2+dev)
interactive (0.3.1+dev)
iot (0.1.5+dev)
keyvault (2.0.4+dev)
lab (0.0.4+dev)
monitor (0.0.4+dev)
network (2.0.6+dev)
nspkg (3.0.0+dev)
profile (2.0.4+dev)
rdbms (0.0.1+dev)
redis (0.2.3+dev)
resource (2.0.6+dev)
role (2.0.4+dev)
sf (1.0.1+dev)
sql (2.0.3+dev)
storage (2.0.6+dev)
taskhelp (0.1.2+dev)
vm (2.0.6+dev)

Python (Linux) 3.5.2 (default, Dec 27 2016, 21:33:11)
[GCC 5.3.0]

Python location '/usr/local/bin/python'

**OS Version:** What OS and version are you using?  
Answer here: Windows 10 Creator Update

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Powershell, then docker run

**Comment by lindydonna** [comment]
Update: with the following command, I also get an error. This happens on the Cloud Shell in the portal as well as on my local machine:

Command:
```az storage cors add --connection-string $connstr --origins '*' --methods GET --allowed-headers 'x-ms-meta-abc,content-type,x-ms-blob-type,x-ms-meta-data*,x-ms-meta-target*' --exposed-headers 'x-ms-meta-*' --max-age 200 --services blob
```

Output:
> XML specified is not syntactically valid.

**Comment by mayurid** [comment]
@troydai to take a look
@lindydonna : can you also provide the complete output by running the command with --debug.

**Comment by troydai** [comment]
@lindydonna for the exception complaining `l`, that is because the `type` parameter only accepts `b` `f` `q` and `t`. We should probably improve the error message.

For the issue of `XML specified is not syntactically valid`, I looked into it last week. This is a service issue. The error can be repoed with SDK, and the issue can't be produced constantly. I'm in talk with the storage team.

Be more specific, this is what the underlying error:

```
Request:
 
host = {str} 'trdaibatch01storage.blob.core.windows.net'
host_locations = {dict} {'primary': 'trdaibatch01storage.blob.core.windows.net'}
method = {str} 'PUT'
path = {str} '/'
query = {dict} {'restype': 'service', 'comp': 'properties', 'timeout': None}
 
Headers:
{'Content-Length': '1219', 'x-ms-version': '2016-05-31', 'User-Agent': 'Azure-Storage/0.34.0 (Python CPython 3.6.1; Darwin 16.6.0) AZURECLI/2.0.6+dev', 'x-ms-client-request-id': '47adbe88-3b4a-11e7-8f82-4c32759c53db', 'x-ms-date': 'Wed, 17 May 2017 21:48:54 GMT', 'Authorization': 'SharedKey trdaibatch01storage:66FdOIdAGlh01VNZwxw1zmc7SK8nFqnnYrZX6BAOb28='}
 
Body:
b"<?xml version='1.0' encoding='utf-8'?>\n<StorageServiceProperties><Cors><CorsRule><AllowedOrigins>*</AllowedOrigins><AllowedMethods>GET</AllowedMethods><MaxAgeInSeconds>200</MaxAgeInSeconds><ExposedHeaders>x-ms-meta-*</ExposedHeaders><AllowedHeaders>x-ms-meta-abc,content-type,x-ms-blob-type,x-ms-meta-data*,x-ms-meta-target*</AllowedHeaders></CorsRule><CorsRule><AllowedOrigins>*</AllowedOrigins><AllowedMethods>GET</AllowedMethods><MaxAgeInSeconds>200</MaxAgeInSeconds><ExposedHeaders /><AllowedHeaders /></CorsRule><CorsRule><AllowedOrigins>'*'</AllowedOrigins><AllowedMethods>GET</AllowedMethods><MaxAgeInSeconds>200</MaxAgeInSeconds><ExposedHeaders /><AllowedHeaders /></CorsRule><CorsRule><AllowedOrigins>'*'</AllowedOrigins><AllowedMethods>GET</AllowedMethods><MaxAgeInSeconds>200</MaxAgeInSeconds><ExposedHeaders /><AllowedHeaders /></CorsRule><CorsRule><AllowedOrigins>'*'</AllowedOrigins><AllowedMethods>GET</AllowedMethods><MaxAgeInSeconds>200</MaxAgeInSeconds><ExposedHeaders /><AllowedHeaders /></CorsRule><CorsRule><AllowedOrigins>'*'</AllowedOrigins><AllowedMethods>GET</AllowedMethods><MaxAgeInSeconds>200</MaxAgeInSeconds><ExposedHeaders /><AllowedHeaders /></CorsRule></Cors></StorageServiceProperties>"
 
Response:
 
400
'content-length' (4483572336) = {str} '294'
'content-type' (4483574576) = {str} 'application/xml'
'date' (4471567280) = {str} 'Wed, 17 May 2017 21:49:06 GMT'
'server' (4483554528) = {str} 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
'x-ms-request-id' (4483574512) = {str} '0aeb76c7-0001-00ff-0757-cfbc27000000'
'x-ms-version' (4483572208) = {str} '2016-05-31'
 
b'\xef\xbb\xbf<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidXmlDocument</Code><Message>XML specified is not syntactically valid.\nRequestId:0aeb76c7-0001-00ff-0757-cfbc27000000\nTime:2017-05-17T21:49:06.3451506Z</Message><LineNumber>0</LineNumber><LinePosition>0</LinePosition><Reason /></Error>'
 

 ```

**Comment by troydai** [comment]
@lindydonna the 400 is caused by too many rules. An account can't hold more than 6 CORS rules.

**Comment by lindydonna** [comment]
@troydai Does your fix improve the error message so that customers know why the command failed?

**Comment by troydai** [comment]
I don't think CLI should unilaterally interpret all error messages in this action as an indication of  "too many rules". The best approach is still to fix this message in service. I'll talk to storage PM and push for the service to make the change.

**Comment by mayurid** [comment]
@troydai : any updates?

**Comment by troydai** [comment]
Storage team is tracking this issue. I believe @lindydonna is on the email thread. I don't think it is appropriate for CLI to address this issue. What we can do is cosmetically rephrase the error message. However, there is a risk the change will over-generalize the issue. So the best to wait for server returns a correct error message and CLI can report it correctly.
