### ISSUE TITLE
Question on vmss update-instances help message

### ISSUE THREAD

**Issue by karataliu** [Azure/azure-cli#3364]
### Description
```
$ az vmss update-instances -h

Command
    az vmss update-instances: Upgrade virtual machines in a virtual machine scale set.

Arguments
    --instance-ids      [Required]: Space separated list of IDs (ex: 1 2 3 ...) or * for all
                                    instances. If not provided, the action will be applied on the
                                    scaleset itself.
```
'--instance-ids' is a required parameter, then when does 'If not provided' apply? Something needs update?

```
$ az vmss update-instances -g $NAME -n $NAME                                                                                                    
az vmss update-instances: error: the following arguments are required: --instance-ids
```

---

### Environment summary
**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
azure-cli (2.0.5)

**Comment by tjprescott** [comment]
Thanks for the report @karataliu.  Taking a look at the command implementation and the SDK, this appears to be a documentation bug. This command only applies to the VMs within the scale set so the part about "the action will be applied on the scaleset itself" is not correct.
