### ISSUE TITLE
 api-ms-win-crt-runtime-l1-1-0.dll is missing error while running az commands

### ISSUE THREAD

**Issue by Parth6288** [Azure/azure-cli#3365]
### Description
Just installed azurecli.msi and getting the subjected error while running az commands (ran az --version) from command prompt.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: unable to run the command, the installer however used is azure-cli-0.2.8.msi

**OS Version:** What OS and version are you using?  
Answer here: Windows 7 Enterprise

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

**Comment by derekbekoe** [comment]
@Parth6288 do you have the Windows updates for Windows 7 (including service packs)?
If so and you still see this error, install [Visual C++ Redistributable for Visual Studio 2015
](https://www.microsoft.com/en-us/download/details.aspx?id=48145)

**Comment by Parth6288** [comment]
It is working now, Thanks.
