### ISSUE TITLE
issues with paste on bash on ubuntu on windows

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#3367]
### Description
**Outline the issue here:**
I've installed Bash on Ubuntu on Windows following the
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli#windows
I open 'Notepad' and type 'hello-привет'.
Then I copy typed text and try to paste it onto Ubuntu command line.
If my current keyboard language is English the result of paste command it 'hello-' (i.e. Russian letters are not pasted).
When I switch my keyboard language to Russian and paste it again the result of it is '-привет' (i.e. English symbols are not pasted).
You see '-' symbol is pasted in both tests.
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
According to https://docs.microsoft.com/en-us/cli/azure/install-azure-cli#windows for Bash on Ubuntu on Windows
**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
D:\>az --version
azure-cli (2.0.6)
D:\>bash
root@ALEXEY-HP:/mnt/d# az --version
azure-cli (2.0.6)
**OS Version:** What OS and version are you using?  
Answer here:
Windows 10 Pro 64-bit
**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
Bash on Windows

**Comment by alexeyshishkin01** [comment]
one more thing:
the issue doesn't exist when copying to 'cmd.exe' console, i.e. the pasted text is the same as copied - 'hello-привет' regardless of the current keyboard language

**Comment by mayurid** [comment]
@alexeyshishkin01 : This looks like an issue with bash on windows and not something to do with the CLI.
You can redirect it here https://github.com/Microsoft/BashOnWindows 
Please reopen if I have missed something and it relates to the CLI 2.0
