### ISSUE TITLE
issue with accessing created VM

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#3368]
### Description
**Outline the issue here:**
I'm using Azure CLI 2.0.
I've installed it under Bash on Ubuntu on Windows according to https://docs.microsoft.com/en-us/cli/azure/install-azure-cli#windows
I have a VHD-image in Azure and I try to create VM from it.
I have issue with accessing to created VM if I use the command:
az vm create ... --attach-os-disk ... --admin-password Azure1234567890+ --admin-username azureuser --authentication-type password --os-type linux
when I try to connect to VM using
ssh azureuser@VM-IP-address
I get an error message about authentication failure.
If I reset password of 'azureuser' with
az vm extension set --name VMAccessForLinux --publisher Microsoft.OSTCExtensions --protected-settings '{"username":"azureuser","password":"Azure1234567890+"}'
I can connect to the VM.

I don't have authentication failure issue, i.e. I can successfully connect to created VM if I use the following commands:
az vm create ... --attach-os-disk ... --os-type linux
az vm extension set --name VMAccessForLinux --publisher Microsoft.OSTCExtensions --protected-settings '{"username":"azureuser","password":"Azure1234567890+"}'
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
Bash on Ubuntu on Windows according to https://docs.microsoft.com/en-us/cli/azure/install-azure-cli#windows
**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
D:\>az --version
azure-cli (2.0.6)
D:\>bash
root@ALEXEY-HP:/mnt/d# az --version
azure-cli (2.0.6)
**OS Version:** What OS and version are you using?  
Answer here:
Windows 10 Pro 64-bit
**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
cmd.exe, Bash on Windows

**Comment by yugangw-msft** [comment]
The pertinent issue is when attach to an existing OS disk, the creds provided in the command line are not picked up by server, probably by design. We should either error out on unused args or make it work
```
az vm create ... --attach-os-disk ... --admin-password Azure1234567890+ --admin-username azureuser --authentication-type password --os-type linux
```

**Comment by tjprescott** [comment]
+1 for raising an error. If you are attaching an existing OS disk, you have to know that disk's credentials.

**Comment by alexeyshishkin01** [comment]
ok, I see.
Frankly I don't understand the difference for creating new VM's OS user:
- either during creating VM
- or after it
Compare it with VM creation using OS image:
az vm create ... --image CentOS ... --admin-password Azure1234567890+ --admin-username azureuser --authentication-type password --os-disk-name myosdisk
It works fine, no authentication failure at all.
Why?

Another point is about VM's OS user existing in VHD image - I cannot change its password via 'az' commands (see above).
I looked through waagent log files and found out an error message similar to 'cannot change password for system user'.
Is it by design as well? If so is it documented somewhere?
Many thanks!

**Comment by tjprescott** [comment]
If you were using a generalized image, you would be able to create a VM from that image and supply the credentials at create time. That is essentially what happens when you specify --image CentOS.

https://www.tech-coffee.net/deploy-azure-vm-from-a-generalized-image/

Using an existing (non-generalized) disk you can still log in to it (assuming you know the credentials) and then set up additional accounts.

**Comment by alexeyshishkin01** [comment]
that's the issue: in both cases I provide the same '--admin-password Azure1234567890+ --admin-username azureuser --authentication-type password' but in case of VHD-image I cannot login to VM after creation with these credentials.
Am I alone?

**Comment by tjprescott** [comment]
Was your VHD generalized beforehand?  If not, this is the expected behavior.

**Comment by alexeyshishkin01** [comment]
existing VHD image has credentials, but I try to create new user 'azureuser' which doesn't exist in VHD image.
at the same time I can add it in separate command after creating VM - that's odd a bit.

**Comment by tjprescott** [comment]
Yes, you cannot create a new user in that VHD during the VM create process.

**Comment by alexeyshishkin01** [comment]
ok, got it!
what I have is:

1) clear case
create new user credentials works fine
az vm create ... --image ... --admin-password Azure1234567890+ --admin-username azureuser --authentication-type password

2) needs to be fixed/documented case, but at least with known solution
create new user credentials doesn't work with
az vm create ... --attach-os-disk ... --admin-password Azure1234567890+ --admin-username azureuser --authentication-type password
new user credentials have to be created with additional command
az vm extension set ... --name VMAccessForLinux --publisher Microsoft.OSTCExtensions --protected-settings '{"username":"azureuser","password":"Azure1234567890+"}'

3) needs to be clarified case
reset password of the user existing in VHD image doesn't work either with
az vm create ... --attach-os-disk ... --admin-password <NEW_PASSWORD_FOR_EXISTING_USER> --admin-username <EXISTING_USER> --authentication-type password
or with
az vm extension set ... --name VMAccessForLinux --publisher Microsoft.OSTCExtensions --protected-settings '{"username":"<EXISTING_USER>","password":"<NEW_PASSWORD_FOR_EXISTING_USER>"}'

thanks in advance!
