### ISSUE TITLE
[Storage]Support max page blob up to 8191GB

### ISSUE THREAD

**Issue by yuemlu** [Azure/azure-cli#3388]
### Description
**Outline the issue here:**

az storage blob upload command need to increase the max page blob size from 1,023GB to 8,191GB. Currently the max page blob is 1,023GB.  

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

**OS Version:** What OS and version are you using?  
Answer here:

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

**Comment by troydai** [comment]
As far as I know we rely on the storage SDK for this. Does SDK currently current support 8T file size?

**Comment by yugangw-msft** [comment]
closing. It is an issue in SDK
