### ISSUE TITLE
tab completion: make it consistent and predictable

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#339]
1. 'location' completion should be available across all commands, so fat it is only available for 'vm create'
2. It is slow
3. Print out non related lists if there are no list. 

============original feedback==============
One of the _wow_ pieces of feedback we always get is the ability to use bash completion for common parameter values, such as VM sizes, locations, etc.  The problem is that this works beautifully in some commands and not in others, so can never really trust it and rely on it for productivity.  The problem is exacerbated by the fact that statement completion is currently pretty slow and prints out a weird list in cases where there is no value completion.  For example if you type az storage account create –location<tab><tab> we print a list of all of the parameters the create commands takes followed by all files in the current directory.  But if you type az storage account create –type<tab><tab> you get a list of storage account types.  I think it’s prudent to flush out the model and use it consistently, such that users can intuit the behavior.

**Comment by derekbekoe** [comment]
@yugangw-msft Can we close this now? Tab completion support has been beefed-up and perf. has also improved.
