### ISSUE TITLE
Telemetry: in order to improve command usage, we want to make sure that we are capturing which commands users invoke tab completion for

### ISSUE THREAD

**Issue by johanste** [Azure/azure-cli#3401]
We need to verify that, if the user has opted in to providing usage telemetry data, we capture which command we are providing tab completion for.

**Comment by troydai** [comment]
Investigated. The current structure doesn't support feed enough information to telemetry for tab completion. The scope of the changes requires for this feature may be beyond sprint 16.

**Comment by yugangw-msft** [comment]
We will revisit when we have actions to take based on the data. TAB completion are for Show/List, which we have way less design decisions pending on it.
