### ISSUE TITLE
Azure CLI does not report error code

### ISSUE THREAD

**Issue by adubnik** [Azure/azure-cli#3403]
### Description
**Outline the issue here:**

Group blabla does not exists and cli should return 1 if so as this is also what portal generated script expect. Unfortunately it returns 0 as successful completion.

az group show --name blabla
echo $?
0
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.6)

**OS Version:** What OS and version are you using?  
Answer here: MacOS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by derekbekoe** [comment]
This was as a result of https://github.com/Azure/azure-cli/issues/1952

**Comment by adubnik** [comment]
Thanks it make sense now. 

I suggest MS to change portal code generator as well. It still thinks show return status code. Also some CLI commands portal generator uses are out of date. 

Issue is easy to workaround just thought I post it here.
