### ISSUE TITLE
az ad sp create-for-rbac: unrecognized arguments --key-vault

### ISSUE THREAD

**Issue by valtynikov** [Azure/azure-cli#3404]
### Description
Getting the following error when trying to use the `--key-vault` argument with the `az ad sp create-for-rbac` command.

The argument should be supported by Azure 2.0 CLI according to the documentation: https://docs.microsoft.com/en-us/cli/azure/ad/sp#create-for-rbac.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Both **MSI for the Windows command-line** and **apt-get for Bash on Ubuntu on Windows** installation methods produce the same result.

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
```
azure-cli (2.0.6)

acr (2.0.4)
acs (2.0.6)
appservice (0.1.6)
batch (2.0.4)
cdn (0.0.2)
cloud (2.0.2)
cognitiveservices (0.1.2)
command-modules-nspkg (2.0.0)
component (2.0.4)
configure (2.0.6)
core (2.0.6)
cosmosdb (0.1.6)
dla (0.0.6)
dls (0.0.6)
feedback (2.0.2)
find (0.2.2)
interactive (0.3.2)
iot (0.1.5)
keyvault (2.0.4)
lab (0.0.4)
monitor (0.0.4)
network (2.0.6)
nspkg (3.0.0)
profile (2.0.4)
rdbms (0.0.1)
redis (0.2.3)
resource (2.0.6)
role (2.0.4)
sf (1.0.1)
sql (2.0.3)
storage (2.0.6)
vm (2.0.6)
```

**OS Version:** What OS and version are you using?  
Edition: Windows 10 Enterprise
Version: 1607
OS Build: 14393.970

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Both cmd.exe and Bash on Windows

**Comment by tjprescott** [comment]
Hi @valtynikov this is a documentation bug. The parameter should is `--keyvault` so that it matches the `az keyvault` commands.  We'll get the help text fixed.

**Comment by valtynikov** [comment]
@tjprescott I actually tried that too. Still get the same error: `az: error: unrecognized arguments: --keyvault`

**Comment by tjprescott** [comment]
When you run `az ad sp create-for-rbac -h` does it show as an argument?

**Comment by valtynikov** [comment]
No, it doesn't.
```
Command
    az ad sp create-for-rbac: Create a service principal and configure its access to Azure
    resources.

Arguments
    --cert           : PEM or DER formatted public certificate using string or `@<file path>` to
                       load from a file. Do not include private key info.
    --create-cert    : Create and upload self-signed certificate which you can use to login.
    --expanded-view  : Once created, display more information like subscription and cloud
                       environments.
    --name -n        : A display name or an app id uri. Command will generate one if missing.
    --password -p    : The password used to login. If missing, command will generate one.
    --role           : Role the service principal has on the resources.  Default: Contributor.
    --scopes         : Space separated scopes the service principal's role assignment applies to.
                       Defaults to the root of the current subscription.
    --skip-assignment: Do not create default assignment.
    --years          : Years the password will be valid. Default: 1 year.
```

**Comment by tjprescott** [comment]
Ah, yes, that is because this change has not yet been released!  It was merged in the last week or so, and thus it won't be available publicly until the next release.  You could get a nightly install or dev_setup to acquire it.

At the same time, @mayurid do we need to have a discussion with the docs team to publish docs based on the last public release rather than the latest master?

**Comment by valtynikov** [comment]
OK, that makes sense. I'll try to get a nightly build.

When is the next release date?

**Comment by tjprescott** [comment]
Should be at the end of the month.

**Comment by derekbekoe** [comment]
We are following milestones and are currently on Sprint 16 - https://github.com/Azure/azure-cli/milestones?direction=asc&sort=due_date&state=open
