### ISSUE TITLE
--debug on Interactive mode doesn't work

### ISSUE THREAD

**Issue by oakeyc** [Azure/azure-cli#3408]

**Comment by tjprescott** [comment]
As a thought, should these be configurable in interactive?  i.e. you want ALL commands to run with --debug or --verbose?  Since an interactive experience would be expected to be "chattier", having to add --verbose to each invocation seems very inconvenient.

**Comment by oakeyc** [comment]
Currently, since you have to run 'interactive' through az, if you add run the intial command with --debug or --verbose then all the commands will pick that up eg:
```bash
az interactive --debug
az>>vm list
```
will output vm list --debug

**Comment by derekbekoe** [comment]
@oakeyc the one action item I might add is to then remove the --debug and --verbose options from the completions provided by the shell.
