### ISSUE TITLE
[ACS] DCOS Browse should use a default value if ssh key path is not provided or throw error

### ISSUE THREAD

**Issue by sanar-microsoft** [Azure/azure-cli#3410]
### Description
**Outline the issue here:**
---
az acs dcos browse doesn't work without specifying the --ssh-key-file argument and this argument is not marked as a required parameter. The error thrown says 'TypeError: stat: can't specify None for path argument'. I think in case it is not provided, the command should default to a path like  "/Users/user/.ssh/id_rsa" or throw a well defined error specifying the missing argument. 

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: nightly

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: nightly

**OS Version:** What OS and version are you using?  
Answer here: macOS Sierra

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by mayurid** [comment]
@brendanburns to comment.

**Comment by neilpeterson** [comment]
I've also encountered this, which led me to this issue. I agree with the desired outcome as expressed by @sanar-microsoft .

**Comment by yugangw-msft** [comment]
closing as `az acs` is deprecating
