### ISSUE TITLE
Installation using homebrew

### ISSUE THREAD

**Issue by Ali92hm** [Azure/azure-cli#3413]
### Description
**Outline the issue here:**
---

Create a brew formula for Azure-Cli 2. I know azure-cli version one is on brew, are there any plans to make a brew formula for `az`?

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: 
`curl -L https://aka.ms/InstallAzureCli | bash`

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
```
azure-cli (2.0.6)

acr (2.0.4)
acs (2.0.6)
appservice (0.1.6)
batch (2.0.4)
cdn (0.0.2)
cloud (2.0.2)
cognitiveservices (0.1.2)
command-modules-nspkg (2.0.0)
component (2.0.4)
configure (2.0.6)
core (2.0.6)
cosmosdb (0.1.6)
dla (0.0.6)
dls (0.0.6)
feedback (2.0.2)
find (0.2.2)
interactive (0.3.2)
iot (0.1.5)
keyvault (2.0.4)
lab (0.0.4)
monitor (0.0.4)
network (2.0.6)
nspkg (3.0.0)
profile (2.0.4)
rdbms (0.0.1)
redis (0.2.3)
resource (2.0.6)
role (2.0.4)
sf (1.0.1)
sql (2.0.3)
storage (2.0.6)
vm (2.0.6)

Python (Darwin) 2.7.13 (default, Apr  4 2017, 08:47:57)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]

Python location '/usr/local/custom/azure-cli/bin/python'
```

**OS Version:** What OS and version are you using?  
Answer here:
 `macOS Sierra 10.12.5`

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: 
`bash`

**Comment by derekbekoe** [comment]
Please see https://github.com/Azure/azure-cli/issues/643

**Comment by derekbekoe** [comment]
@Ali92hm Please add any comments you have there. Thanks!

**Comment by Ali92hm** [comment]
Thanks, sorry I did a search on the issues and didn't find that initially. Thanks for the pointer!
