### ISSUE TITLE
Telemetry: in order to better understand what linux distros we should support, we should include the distro in the usage data

### ISSUE THREAD

**Issue by johanste** [Azure/azure-cli#3414]
It looks like we are sending platform.version() but not platform.linux_distribution(). It would be helpful to understand which distros are used. 

(I was trying to look up which distros are used when making requests in order to better understand what native installers we should look at)

**Comment by yugangw-msft** [comment]
Let us close it, we don't have actions to take right now based on this outcome. Once we need to do it, it will be either [user agent](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/commands/client_factory.py#L84), or client end [telemetry](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/telemetry.py#L121)
