### ISSUE TITLE
[DevTestLab] Rename --resource-group/-g to --lab-resource-group/-lg for all commands 

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-cli#3418]
### Description
Rename `--resource-group/-g` to `--lab-resource-group/-lg` for all commands 

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: Development version from master

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
```
azure-cli (2.0.6+dev)

acr (2.0.4+dev)
acs (2.0.6+dev)
appservice (0.1.6+dev)
batch (2.0.4+dev)
cdn (0.0.2+dev)
cloud (2.0.2+dev)
cognitiveservices (0.1.2+dev)
component (2.0.4+dev)
configure (2.0.6+dev)
container (0.1.3+dev)
core (2.0.6+dev)
cosmosdb (0.1.6+dev)
dla (0.0.6+dev)
dls (0.0.6+dev)
documentdb (0.1.5+dev)
feedback (2.0.2+dev)
find (0.2.2+dev)
interactive (0.3.1+dev)
iot (0.1.5+dev)
keyvault (2.0.4+dev)
lab (0.0.4+dev)
monitor (0.0.4+dev)
network (2.0.6+dev)
nspkg (3.0.0+dev)
profile (2.0.4+dev)
rdbms (0.0.1+dev)
redis (0.2.3+dev)
resource (2.0.6+dev)
role (2.0.4+dev)
sf (1.0.1+dev)
shell (0.2.3+dev)
sql (2.0.3+dev)
storage (2.0.6+dev)
taskhelp (0.1.2+dev)
testsdk (0.1.0+dev)
utility-automation (0.1.1)
vm (2.0.6+dev)

Python (Darwin) 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

Python location '/Users/vishrut/git-repos/azure-cli/env/bin/python'
```

**OS Version:** What OS and version are you using?  
Answer here: MacOS 10.12.4

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by tjprescott** [comment]
-lg is not a valid flag. It can only be a single letter.

**Comment by vishrutshah** [comment]
@tjprescott Aha I see. 

@gxy001 As Travis has pointed out the short flag must be a single letter, feel free to provide your suggestion on what letter makes more sense to represent `Lab's Resource Group`.
