### ISSUE TITLE
Best way to spin up mutliple Kubernetes clusters?

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#3422]
I was approached with the following scenario:

Customer wants to spin up a number of Kubernetes clusters and would like to use the same SSH key for each. He would like to spin these up in parallel for faster deployment.

Option 1
===

Use an ARM template deployment to deploy the clusters in parallel. However, this throws away any convenience introduced by the ACS create command, including the ability to generate SSH keys if not found.  Thus, either the customer would need to manually generate the keys and pass them into as template parameters, or the `group deployment` commands would need to replicate the convenience logic to auto-generate the SSH keys.

Option 2
===

You can start multiple create scenarios using the `--no-wait` flag and then use matching `wait` commands to wait until all of the creates are finished.  This lets you leverage all of the conveniences of the ACS create command, include `--generate-ssh-keys`.

Any insights into better ways to accomplish this scenario?

**Comment by brendandburns** [comment]
`--no-wait` flag is the way to go.  The service principal work alone in the `az` CLI makes it way easier to use than in a template...
