### ISSUE TITLE
Azure CLI 2.0 is missing a "strongly typed" command for enabling the chef extension on VMs

### ISSUE THREAD

**Issue by johanste** [Azure/azure-cli#3425]
### Description
The xplat CLI has a `azure vm extension set-chef` command that helps enabling the compute chef extension. The `az`, there is only the generic `az vm extension set` command. It would be nice to provide more named parameters that are specific to the chef extension.

**Comment by johanste** [comment]
In addition, we should update the documentation (i.e. https://github.com/chef-partners/azure-chef-extension/blob/master/examples/azure-xplat-cli-examples.md, https://github.com/chef-partners/azure-chef-extension/tree/master/examples) to show how to use Azure CLI 2.0 instead of xplat for ARM compute resources...

**Comment by tjprescott** [comment]
Would you advodate adding this as a convenience command or adding parameters to the VM extension set command?

**Comment by johanste** [comment]
Since I would envision the parameters for the command to be specific to the extension configuration schema for the chef extension, it would have to be a specific (convenience) command. 

It does raise the question what to do for extensions in general, since VM/compute extensions are also extensions for the platform (meaning that new ones can be registered/added both by Microsoft as well as by partners), and it may make sense to have the corresponding extensibility point in the CLI as well. At the moment, there is no supported way to extend/add named extension commands under the `az vm extension ...` path.

**Comment by tjprescott** [comment]
Also, since the Azure documentation on configuration management seems to promote both Puppet and Chef, we probably also should have convenience commands for Puppet configuration.

**Comment by yugangw-msft** [comment]
I will take this one

**Comment by yugangw-msft** [comment]
Talk to extension team which suggested to punt
