### ISSUE TITLE
[VM] [Feature request] Platform image support

### ISSUE THREAD

**Issue by paulmey** [Azure/azure-cli#3427]
### Description
With the advent of Managed Disks and Images as first class resources, Azure now has a new way to reference [Platform Images](https://docs.microsoft.com/en-us/rest/api/compute/platformimages).
The capability that I am interested in is to [create a Managed Disk from a Platform Image](https://docs.microsoft.com/en-us/rest/api/manageddisks/disks/disks-create-or-update), so that I can attach it as a data disk and patch it before I create a VM from it.

**Comment by yugangw-msft** [comment]
@paulmey apologize for the delay, but I just didn’t see it. Is this still an ask?
In cli, you can do “az image create --source <vm resource id>” to create an image, I assume you like to create a managed disk from the image?

**Comment by yugangw-msft** [comment]
We can consider to exposing commands for this if the e2e flow is clear and we do have API support on this. Please reactivate it with more details.
