### ISSUE TITLE
Commands run from az interactive are missing parameters

### ISSUE THREAD

**Issue by johanste** [Azure/azure-cli#3428]
### Description
If I run vm show from `az interactive`, the --ids parameter is not showing in the parameters list.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: interactive script

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

azure-cli (2.0.6)

acr (2.0.4)
acs (2.0.6)
appservice (0.1.6)
batch (2.0.4)
cdn (0.0.2)
cloud (2.0.2)
cognitiveservices (0.1.2)
command-modules-nspkg (2.0.0)
component (2.0.4)
configure (2.0.6)
core (2.0.6)
cosmosdb (0.1.6)
dla (0.0.6)
dls (0.0.6)
feedback (2.0.2)
find (0.2.2)
interactive (0.3.2)
iot (0.1.5)
keyvault (2.0.4)
lab (0.0.4)
monitor (0.0.4)
network (2.0.6)
nspkg (3.0.0)
profile (2.0.4)
rdbms (0.0.1)
redis (0.2.3)
resource (2.0.6)
role (2.0.4)
sf (1.0.1)
sql (2.0.3)
storage (2.0.6)
vm (2.0.6)

Python (Darwin) 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 12:54:16) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

**OS Version:** What OS and version are you using?  
Answer here:
macOs 10.12.4

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
bash

**Comment by tjprescott** [comment]
This may have to do with the fact that the "handle IDs parameter stuff" happens after the command table is loaded.

**Comment by oakeyc** [comment]
What does the handling for ID parameters?

**Comment by tjprescott** [comment]
It's in `arm.py`.  `command_loaded_handler`.

**Comment by oakeyc** [comment]
duplicate #3018

**Comment by tjprescott** [comment]
Since it's a duplicate, feel free to close one of them. :)
