### ISSUE TITLE
az group deployment show is missing tab completion for the name parameter 

### ISSUE THREAD

**Issue by johanste** [Azure/azure-cli#3439]
### Description
Run `az group deployment show -g <one of your resource groups> -n <tab>`

Results: no tab completion.

And, yes, tab completion is hooked up and works for other parameters 
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
script

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
resource (2.0.6)

**OS Version:** What OS and version are you using?  
Answer here:

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

**Comment by derekbekoe** [comment]
Is this different from https://github.com/Azure/azure-cli/issues/3412#issuecomment-303780989?

**Comment by tjprescott** [comment]
It is different because deployment_name just doesn't have a completer (as opposed to have a broken one!)

**Comment by tjprescott** [comment]
@kristapratico should be easy to confirm this and fix if it is still true.

**Comment by zhoxing-ms** [comment]
This issure can be worked in the latest version of azure-cli. Please update the version and try again. If you have any other questions, please let us know.

**Comment by zhoxing-ms** [comment]
@johanste This issure can be worked in the latest version of azure-cli. Please update the version and try again. If you have any other questions, please let us know.

**Comment by yonzhan** [comment]
add to S164.

**Comment by yonzhan** [comment]
@johanste any update?

**Comment by zhoxing-ms** [comment]
Because it hasn't been replied for a long time, I'll close the issue first. If you have any other questions, please feel free to reopen it or create a new one.
