### ISSUE TITLE
az webapp config ssl bind results in error when binding valid wildcard certificate.

### ISSUE THREAD

**Issue by PaulTrampert** [Azure/azure-cli#3443]
### Description
Attempting to bind a wildcard ssl certificate (valid for hostnames `*.example.com` and `example.com`) to a deployment slot with the hostname, `slot-master.example.com`, results in the following error:
`Certificate for thumbprint '<thumbprint>' not found.`

The command I used was `az webapp config ssl bind --certificate-thumbprint <thumbprint> -n <appname> -g <resourceGroup> --ssl-type SNI -s master`.

I have verified that the thumbprint exists, and was able to bind the certificate to the hostname via the Azure portal. Also verified that the certificate is listed via the command line using `az webapp config ssl list --resource-group <rg>`

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip, and using `az component update` to keep up to date.

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 
```
azure-cli (2.0.6)

acr (2.0.4)
acs (2.0.6)
appservice (0.1.6)
batch (2.0.4)
cdn (0.0.2)
cloud (2.0.2)
cognitiveservices (0.1.2)
command-modules-nspkg (2.0.0)
component (2.0.4)
configure (2.0.6)
core (2.0.6)
cosmosdb (0.1.6)
dla (0.0.6)
dls (0.0.6)
documentdb (0.1.5)
feedback (2.0.2)
find (0.2.2)
interactive (0.3.2)
iot (0.1.5)
keyvault (2.0.4)
lab (0.0.4)
monitor (0.0.4)
network (2.0.6)
nspkg (3.0.0)
profile (2.0.4)
rdbms (0.0.1)
redis (0.2.3)
resource (2.0.6)
role (2.0.4)
sf (1.0.1)
sql (2.0.3)
storage (2.0.6)
vm (2.0.6)

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]

Python location 'C:\Python36\python.exe'
```
**OS Version:** What OS and version are you using?  
Answer here: Windows 10 Pro Version 1607, Build 14393.1198

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Powershell

**Comment by yugangw-msft** [comment]
@PaulTrampert, could you please provide a few more information?
1. Is your cert and appservice plan are in the same resource group? I worry [this change](https://github.com/Azure/azure-cli/commit/4c7e7b7f964bc9adb66f9d1e67c1f45f3ac466e8) might cause the break.
2. Could you double check whether the thumbprint arg value completely matches the `list` output, even the character casing?

**Comment by PaulTrampert** [comment]
@yugangw-msft 
1. The cert and appservice plan are both in the same resource group.
1. The thumbprint arg does match exactly the list output, including casing.

**Comment by yugangw-msft** [comment]
@PaulTrampert , i can't reproduce it. Please check out my command and let me know what was missed.
```bash
(env) D:\temp\web>az webapp config ssl upload -g yugangw -n yugangw-web --certificate-file host_main.pfx --certificate-password test
{
  "cerBlob": null,
  "certificateName": null,
  "expirationDate": "2019-12-31T07:00:00+00:00",
  "friendlyName": "",
  "geoRegion": null,
  "hostNames": [
    "*.azurewebsites.net"
  ],
  "hostingEnvironmentProfile": null,
  "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272XXXXXX/resourceGroups/yugangw/providers/Microsoft.Web/certificates/949E18460B30704E25348A3972E1B329954BBFED__West US_yugangw",
  "issueDate": "2017-01-01T07:00:00+00:00",
  "issuer": "*.azurewebsites.net",
  "keyVaultId": null,
  "keyVaultSecretName": null,
  "keyVaultSecretStatus": "Initialized",
  "kind": null,
  "location": "West US",
  "name": "949E18460B30704E25348A3972E1B329954BBFED__West US_yugangw",
  "password": null,
  "pfxBlob": null,
  "publicKeyHash": null,
  "resourceGroup": "yugangw",
  "selfLink": null,
  "serverFarmId": null,
  "siteName": null,
  "subjectName": "*.azurewebsites.net",
  "tags": null,
  "thumbprint": "949E18460B30704E25348A3972E1B329954BBFED",
  "type": "Microsoft.Web/certificates",
  "valid": null
}

(env) D:\temp\web>az webapp config ssl bind -g yugangw -n yugangw-web --certificate-thumbprint 949E18460B30704E25348A3972E1B329954BBFED --ssl-type SNI -s master
{
  "appServicePlanId": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272XXXXXX/resourceGroups/yugangw/providers/Microsoft.Web/serverfarms/yugangw-plan",
  "availabilityState": "Normal",
  "clientAffinityEnabled": true,
  "clientCertEnabled": false,
  "cloningInfo": null,
  "containerSize": 0,
  "dailyMemoryTimeQuota": 0,
  "defaultHostName": "yugangw-web-master.azurewebsites.net",
  "enabled": true,
  "enabledHostNames": [
    "yugangw-web-master.azurewebsites.net",
    "yugangw-web-master.scm.azurewebsites.net"
  ],
  "ftpPublishingUrl": "ftp://waws-prod-bay-077.ftp.azurewebsites.windows.net/site/wwwroot",
  "gatewaySiteName": null,
  "hostNameSslStates": [
    {
      "hostType": "Standard",
      "name": "yugangw-web-master.azurewebsites.net",
      "sslState": "Disabled",
      "thumbprint": null,
      "toUpdate": null,
      "virtualIp": null
    },
    {
      "hostType": "Repository",
      "name": "yugangw-web-master.scm.azurewebsites.net",
      "sslState": "Disabled",
      "thumbprint": null,
      "toUpdate": null,
      "virtualIp": null
    }
  ],
  "hostNames": [
    "yugangw-web-master.azurewebsites.net"
  ],
  "hostNamesDisabled": false,
  "hostingEnvironmentProfile": null,
  "id": "/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272XXXXXX/resourceGroups/yugangw/providers/Microsoft.Web/sites/yugangw-web/slots/master",
  "isDefaultContainer": null,
  "kind": "app",
  "lastModifiedTimeUtc": "2017-05-31T19:27:43.123333",
  "location": "West US",
  "maxNumberOfWorkers": null,
  "microService": "WebSites",
  "name": "yugangw-web/master",
  "outboundIpAddresses": "138.91.247.220,138.91.246.230,138.91.246.197,138.91.241.182",
  "premiumAppDeployed": null,
  "repositorySiteName": "yugangw-web",
  "reserved": false,
  "resourceGroup": "yugangw",
  "scmSiteAlsoStopped": false,
  "siteConfig": null,
  "slotSwapStatus": null,
  "state": "Running",
  "suspendedTill": null,
  "tags": null,
  "targetSwapSlot": null,
  "trafficManagerHostNames": null,
  "type": "Microsoft.Web/sites/slots",
  "usageState": "Normal"
}
```

**Comment by PaulTrampert** [comment]
I do notice a couple things. First, unless you're anonymizing the address, the default azurewebsites.net address has a built in working cert...

That said, the other difference I see is that the cert I have has 2 hostNames: *.mydomain.com, and mydomain.com (and correspondingly, 2 subject names: *.mydomain.com,mydomain.com). Would that cause an issue?

**Comment by yugangw-msft** [comment]
I have used my own domain and bound with a wildcard cert using CLI. It went through w/o any problems.
This error was emitted by CLI when it could not find the cert in plan's resource group, which has nothing to do with the cert's details,
Please run following commands and send me the output to yugangw ar microsoft dot com
```bash
az webapp config ssl upload ... 
az webapp config ssl list ...
az webapp config ssl bind --debug
```

**Comment by yugangw-msft** [comment]
Need repro. Not actionable at the current moment.

**Comment by yugangw-msft** [comment]
@PaulTrampert, please re-activate when you have the data. Thanks for reporting this!

**Comment by stagrlee** [comment]
Is this issue related to #5533 ?

**Comment by aemil1** [comment]
I am having the same problem as PaulTrampert.
Version: azure-cli 2.0.64.

When executing the "az webapp config ssl bind" command in debug mode, the trace reveals an interesting fact: the certificate is being searched for not in the app's resource group, but in that of its service plan.

**Comment by tmakin** [comment]
I've just run into this. with cli 2.0.64. Details as follows:
- wildcard cert
- multiple domains
- app service plan in a different resource group to app service

**Comment by platform-co** [comment]
Having the same issue. 

1. Manually uploaded pfx cert to portal + added bindings
2. Deleted from portal due to: https://feedback.azure.com/forums/169385-web-apps/suggestions/35348716-make-certificate-deployment-idempotent
3: Uploaded with azure cli (idempotent upload works now without error)
4: Azure cli bind now returns: Certificate for thumbprint 'xyz' not found.

**Comment by owenmather** [comment]
Having the same issue. Steps that got me here:

1. Manually uploaded pfx cert to portal + added bindings
2. Deleted from portal due to: https://feedback.azure.com/forums/169385-web-apps/suggestions/35348716-make-certificate-deployment-idempotent
3. Uploaded with azure cli (idempotent upload works now without error)
4. Azure cli bind now returns: Certificate for thumbprint 'xyz' not found.

thumbprint is same as original uploaded through portal

**Comment by cima** [comment]
I have similar issue. Using --ids switch it return success but it takes no effect. I have to go to portal and bind it manually. We do use wildcard certificate.

**Comment by mstancombe** [comment]
@yugangw-msft I have the same issue where a wildcard cert issued by letsencrypt can be bound via cli when the app service is in the same resource group as the plan, but not when it's in a different resource group.  Given that this is a supported configuration through the azure portal ui, can this issue be re-opened?

**Comment by owenmather** [comment]
@mstancombe
Have issue open here:
https://github.com/Azure/azure-cli/issues/9972
