### ISSUE TITLE
Add legal note to --version

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#3449]
Let's put a legal note inside the --version:

```
$ az --version
[...]
storage (2.0.6)
vm (2.0.6)

Legal docs and information: aka.ms/AzureCliLegal
Python (Darwin) 2.7.10 (default, Feb  6 2017, 23:53:20) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
[...]
```

The link goes to our MSI license (in yucky RTF), but we should post a clean version to the repo if there is not already a copy and assign back to me to update the aka.

**Comment by derekbekoe** [comment]
@JasonRShaver This will be the new link for the license terms once the linked PR has been merged https://raw.githubusercontent.com/Azure/azure-cli/master/cli_license_terms.md
