### ISSUE TITLE
[DevTestLabs] How do you create a lab?

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#3450]
### Description

Most (all?) of the commands underneath the `az lab` group require a lab name to be specified (which makes sense), but I don't actually see a way from the CLI to create a lab. Is this functionality missing? Is it expected that the lab creation is done via the portal, and then everything else can be done via the CLI? 

Apologies if I'm missing something super obvious here. I noticed that you can delete a lab, so I was expecting to see an `az lab create` command, but I didn't notice it.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: nightly

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: nightly

**OS Version:** What OS and version are you using?  
Answer here: macOS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by tjprescott** [comment]
@vishrutshah can confirm, but I believe that yes, indeed, lab create isn't currently supported. You would create it using an ARM template or the portal right now.

**Comment by vishrutshah** [comment]
@lostintangent Yes, we have not exposed creation of the DevTest Labs via the CLI yet. As of today, you create a lab via portal or ARM template. Then perform some of the lab related operation via CLI.
