### ISSUE TITLE
cannot find out attached disk caching policy

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#3470]
### Description
**Outline the issue here:**
I cannot find out attached disk caching policy
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
According to https://docs.microsoft.com/en-us/cli/azure/install-azure-cli#windows (Bash on Ubuntu on Windows)
**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
azure-cli (2.0.6)
**OS Version:** What OS and version are you using?  
Answer here:
Windows 10 64-bit 10.0.15063
**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
Bash on Windows

**Comment by alexeyshishkin01** [comment]
Am I the first with my question?
Ok, what I was able to do so far is:

1) run:
az vm list \
--query [] \
--output jsonc

2) look at the long output and shorten it a bit:
az vm list \
--query "[].{vmname:name,datadisks:storageProfile.dataDisks[*]}" \
--output jsonc

3) or even shorter:
az vm list \
--query "[?starts_with(name,'myvm')].{vmname:name,datadisks:storageProfile.dataDisks[*]}" \
--output jsonc

So now I have another question: how to change caching mode for data disk?
I done several tests for None, Readonly and ReadWrite caching modes and found out ReadWrite performs much better.

I assume os disk cache mode is always ReadWrite, i.e. no need to change it, right?

**Comment by yugangw-msft** [comment]
For a disk, there are only 2 properties you can change, `size` and `account type, aka sku`. If you like to change caching model, please create a new disk. You can let the new one import from the existing one if you need to persist the data.

**Comment by yugangw-msft** [comment]
Related with #3471. I will update both when I have more information
