### ISSUE TITLE
az vm disk attach ignores caching argument

### ISSUE THREAD

**Issue by danielaene** [Azure/azure-cli#3471]
### Description
The argument "--caching" from "az vm disk attach" command is ignored. The disk is attached with host caching None

To reproduce the issue I ran the commands:
az group create  -l eastus -n topo-ene

az vm create -n topo-ene-vm-1 -g topo-ene \
--size "Standard_DS3_v2" \
--image RHEL \
--admin-username azureuser --ssh-key-value $ssh_key_path \
--storage-caching ReadOnly \
--storage-sku Premium_LRS \
--data-disk-sizes-gb 128

diskName=$(az vm show --name topo-ene-vm-1 -g topo-ene --query "storageProfile.dataDisks[0].name" )

az vm disk detach --name $diskName \
   -g topo-ene \
   --vm-name topo-ene-vm-1

az vm disk attach --disk $diskName \
   -g topo-ene \
   --vm-name topo-ene-vm-1 \
   --caching ReadOnly

I noticed that if I attach a new disk to the vm ( with --new argument), the caching is set correctly.

Shouldn't the caching argument be taken into consideration also for already created disks ?

Thanks a lot for your help!

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: interactive script using the instructions from https://docs.microsoft.com/en-us/cli/azure/install-azure-cli

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.6)

**OS Version:** What OS and version are you using?  
Answer here: OS X El Capitan 1.11.6 

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by yugangw-msft** [comment]
Changing the caching model of an existing disk is not allowed by service. We should error out if it is not used with `--new`

**Comment by danielaene** [comment]
Hello

If caching argument can work only with --new, how can you specify the caching when you create a disk from a snapshot and you attach it to a vm ?

The commands used in this usecase are: az disk create (which doesn't have caching argument) and az vm disk attach. I can not use only "az vm disk attach --new" because it doesn't have the possibility to create the disk from a source

Thanks a lot for your help!

**Comment by yugangw-msft** [comment]
@danielaene, I will investigate and get back to you

**Comment by alexeyshishkin01** [comment]
the same for me - I cannot detach disk and attach it with new Caching policy regardless of VM state (deallocated or not)

**Comment by yugangw-msft** [comment]
Fixed

**Comment by alexeyshishkin01** [comment]
what is exactly fixed?

**Comment by yugangw-msft** [comment]
as the title states `az vm disk attach ignores caching argument `

**Comment by alexeyshishkin01** [comment]
so now it doesn't ignore it?

**Comment by yugangw-msft** [comment]
yes

**Comment by alexeyshishkin01** [comment]
do I have to update CLI version in order to get the fix?

**Comment by yugangw-msft** [comment]
Not released yet, you can try either the docker image or nightly drop tomorrow morning
https://github.com/Azure/azure-cli#installation

**Comment by alexeyshishkin01** [comment]
when it's going to be available via apt-get for example? I don't use docker image so far.
the last time I tried to use nightly drop I had an issue with it and had to reinstall CLI from scratch

**Comment by yugangw-msft** [comment]
It will be available when the current milestone (sprint 17) ends. 
https://github.com/Azure/azure-cli/milestones
