### ISSUE TITLE
Cannot create VM with new unmanaged data disks

### ISSUE THREAD

**Issue by PascalRD** [Azure/azure-cli#3474]
### Description
To create VM I use command:

az vm create  \
    -g some-group \
    -n VM_NAME \
    --os-type linux \
    --attach-os-disk "https://path_to_vhd_in_storage" \
    --data-disk-sizes-gb 50 \
    --size Standard_F1S \
    --use-unmanaged-disk \
    --debug

and got error:

usage: az vm create
az vm create: error: 'data_disk_sizes_gb

Is this key is forbidden with "--use-unmanaged-disk"?
---

### Environment summary

**Install Method:** 
curl -L https://aka.ms/InstallAzureCli | bash

**CLI Version:** 
/home/void/stuff/azure-cli/bin/az --version
azure-cli (2.0.6)

acr (2.0.4)
acs (2.0.6)
appservice (0.1.6)
batch (2.0.4)
cdn (0.0.2)
cloud (2.0.2)
cognitiveservices (0.1.2)
command-modules-nspkg (2.0.0)
component (2.0.4)
configure (2.0.6)
core (2.0.6)
cosmosdb (0.1.6)
dla (0.0.6)
dls (0.0.6)
feedback (2.0.2)
find (0.2.2)
interactive (0.3.2)
iot (0.1.5)
keyvault (2.0.4)
lab (0.0.4)
monitor (0.0.4)
network (2.0.6)
nspkg (3.0.0)
profile (2.0.4)
rdbms (0.0.1)
redis (0.2.3)
resource (2.0.6)
role (2.0.4)
sf (1.0.1)
sql (2.0.3)
storage (2.0.6)
vm (2.0.6)

Python (Linux) 2.7.12 (default, Mar 17 2017, 11:06:25) 
[GCC 5.4.0]

Python location '/home/void/stuff/azure-cli/bin/python'

**OS Version:** 
uname -srm && cat /etc/os-release 
Linux 4.9.9-gentoo x86_64
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"

**Shell Type:**
bash

**Comment by PascalRD** [comment]
OK, I patched cli/command_modules/vm/_validators.py in order to avoid forbidden of this keyboard and got error from server: 

"code": "OperationNotAllowed",
    "target": "dataDisk",
    "message": "Addition of a managed disk to a VM with blob based disks is not supported."
But in web gui I can attach adidtional data disk to blob based disk, why I accon do it in VM creation stage?

**Comment by tjprescott** [comment]
We should definitely clean up that error message; however, the help text is clear:

``` 
--data-disk-sizes-gb               : Space separated empty managed data disk sizes in GB to
                                     create.
```
The CLI only supports creating new *managed* data disks at the time of VM creation. 

For your scenario, you would first create the VM, then use the following commands:
`az vm unmanaged-disk attach -g {rg} --vm-name {vm} ... --new`

@yugangw-msft may have more insight on this.

**Comment by PascalRD** [comment]
Thanks for reply. If there are any possibility to attach data disk before VM starts to execute?

**Comment by tjprescott** [comment]
Not that I'm aware of.  @yugangw-msft might know more. However, I did create the VM (it is created in the running state) and then attached the new data disks.  You can then restart the VM.

**Comment by PascalRD** [comment]
My use case assumes that VM first started before data disk is attached. For some reason I cannot restart VM after data drive is attached. If there are no possibility to do it please tell me.
