### ISSUE TITLE
az command fails when invoked inside xargs

### ISSUE THREAD

**Issue by pg1809** [Azure/azure-cli#3475]
### Description
I have a following bash command:
echo -n [some valid input] | xargs --max-args 3 -P 16 -d' ' bash -ec 'az storage blob download --container-name [valid container name] --name ${2} --file [valid file path]/${1}/${3} --output tsv --query [].name'

When invoked it returns strange errors:
ERROR: Error loading command module 'acr'
ERROR: Error loading command module 'acs'
ERROR: Error loading command module 'acr'
ERROR: Error loading command module 'lab'
ERROR: Error loading command module 'lab'
ERROR: Error loading command module 'keyvault'
ERROR: Error loading command module 'lab'
ERROR: Error loading command module 'lab'
ERROR: Error loading command module 'keyvault'
ERROR: Error loading command module 'keyvault'
ERROR: Error loading command module 'monitor'
ERROR: Error loading command module 'redis'
ERROR: Error loading command module 'lab'
ERROR: Error loading command module 'lab'
ERROR: Error loading command module 'monitor'
ERROR: Error loading command module 'network'
ERROR: Error loading command module 'resource'
ERROR: Error loading command module 'redis'
ERROR: Error loading command module 'storage'
ERROR: Error loading command module 'sql'

It works when using az installed from apt-get package version 0.2.6-1. Newer versions cause the mentioned error. 

### Environment summary

**Install Method:**  
apt-get

**CLI Version:**   
The same as in 0.2.7-1, 0.2.8-1, 0.2.9-1 apt packages

**OS Version:** 
Ubuntu 16.04-LTS

**Shell Type:**  
bash

**Comment by derekbekoe** [comment]
I suspect this is due to https://github.com/Azure/azure-cli/issues/3255 since you're running commands in parallel.
Running `--debug` would confirm this.

A fix for this will be released first part of next week.

**Comment by derekbekoe** [comment]
Closing https://github.com/Azure/azure-cli/pull/3446
