### ISSUE TITLE
[ARM] Resource commands should support --ids

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#3479]
Currently the generic resource commands only support --id.  We should enhance these commands to support --ids so that they are consistent with the rest of the CLI.  See issue #3457 for an example of why this lack of support is problematic.

The lock commands don't have support for even one ID.

We should ensure both sets of commands support the --ids semantic.

- [x] resource (PR #3791)
- [ ] lock
- [x] managedapp (PR #3791)

**Comment by tjprescott** [comment]
`--ids` support for lock commands is considerably complicated by the fact that the lock commands work at various levels, so I excluded it from PR #3791 and will revisit this in a future sprint.

**Comment by williexu** [comment]
`--ids` support for lock commands taken care of by https://github.com/Azure/azure-cli/pull/4412
