### ISSUE TITLE
Provide mechanism for paging

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#3481]
A paging mechanism is helpful when a command needs to process large operation results. It should reduce the memory pressure and improve UI responsiveness.

**Comment by troydai** [comment]
After investigation I found this feature requires SDK improvement: https://github.com/Azure/azure-sdk-for-python/issues/1296

**Comment by lmazuel** [comment]
@troydai or not :)
https://github.com/Azure/azure-cli/blob/56bfba8c830ae2d4a5438d0fca9d7c0a0bf0150a/src/azure-cli-core/azure/cli/core/commands/__init__.py#L539

I return an iterator, and you cast it as a list :)

**Comment by troydai** [comment]
Misread the code. You're right.

**Comment by lmazuel** [comment]
@troydai no problem! You'll get me next time for sure :p

**Comment by squillace** [comment]
@troydai, @lmazuel, where are we on this? I need this command to work, as documented.... it appears as if this was just taken on here: https://github.com/Azure/azure-cli/issues/3323. True?

**Comment by karungithub** [comment]
Add on to this - I could not find if Azure Storage or compute REST API for some of the listing commands (like VM list) supports paging. If anyone knows the options to use in a REST call to get a paged list of elements, that would be really helpful. Thanks.

**Comment by lmazuel** [comment]
@karungithub The paging mechanism of ARM is described here:
https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/resource-api-reference.md#get-resource

If you don't have "nextLink" in the documentation or in what you get from Azure. or the "top" parameter, this probably means that the service does not support paging for this operation.

**Comment by seanknox** [comment]
Hey folks, this continues to a major problem for customers/Microsoft employees needing to managing many app registrations. Without a viable CLI alternative, the portal experience exposes users to accidentally deleting the wrong app registrations.

**Comment by troydai** [comment]
@seanknox thanks for the feedback. The SDK's paging mechanism acts like a linked list, meaning you can only travel through the entities in one direction page by page. There is no random access. Does this mechanism help the customers?

**Comment by seanknox** [comment]
No, unfortunately. See the discussion here: https://github.com/Azure/azure-cli/issues/1150

**Comment by troydai** [comment]
Thank you for pointing to this. Depends on the type of resources, we may provide different solutions. However, the difficult part is to make the change intuitive and usable. We may need to work with service team on this.

**Comment by yugangw-msft** [comment]
> Hey folks, this continues to a major problem for customers/Microsoft employees needing to managing many app registrations

I will fix this through filters such `--mine` to avoid using unconditional `list`, which is more or less usage error. Even we have the paging, going through thousands of pages won't really help you find the one you are looking for. See details in #1150

I am closing this, as we will have a different way to fix this
