### ISSUE TITLE
[ARM] Issues deleting locks

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#3492]
I created a lock on a VM using the following
`az lock create -g {rg} -n {lock-name} --resource-type Microsoft.Compute/virtualMachines --resource-name {vm-name}`

When I went to delete the lock I tried:
`az lock delete -g {rg} -n {lock-name}`

This failed with:
`Unexpected --namespace for lock lockvm, expected Microsoft.Compute`

So first, I was surprised that it failed. Then I was surprised by the error. If it expects Microsoft.Compute, then why do I need to specify it?

Anyways, I then tried:
`az lock delete -g {rg} -n {lock-name} --resource-type Microsoft.Compute/virtualMachines --resource-name {vm-name}`

This also failed with:
`Unexpected --namespace for lock lockvm, expected Microsoft.Compute`

However, the delete command's help text says that it will accept resource-type in "namespace/type" format (which is how I created the lock).

Finally when I tried:
`az lock delete -g {rg} -n {lock-name} --namespace Microsoft.Compute --resource-type virtualMachines --resource-name {vm-name}`

The command succeeded.  So looking at the ID for the lock, I can see why I needed to specify the "other stuff" though I am confused how the command knew what to expect, and if it did, then apparently I didn't need to specify that stuff.  Second, it is not parsing the resource-type argument correctly since the "namespace/type" format didn't work as advertised.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: dev_setup.py

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.6+dev)

acr (2.0.4+dev)
acs (2.0.6+dev)
appservice (0.1.6+dev)
batch (3.0.0+dev)
cdn (0.0.2+dev)
cloud (2.0.2+dev)
cognitiveservices (0.1.2+dev)
component (2.0.4+dev)
configure (2.0.6+dev)
core (2.0.6+dev)
cosmosdb (0.1.6+dev)
dla (0.0.6+dev)
dls (0.0.6+dev)
feedback (2.0.2+dev)
find (0.2.2+dev)
interactive (0.3.2+dev)
iot (0.1.5+dev)
keyvault (2.0.4+dev)
lab (0.0.4+dev)
monitor (0.0.4+dev)
network (2.0.6+dev)
nspkg (3.0.0+dev)
profile (2.0.4+dev)
rdbms (0.0.1+dev)
redis (0.2.3+dev)
resource (2.0.6+dev)
role (2.0.4+dev)
sf (1.0.1+dev)
sql (2.0.3+dev)
storage (2.0.6+dev)
taskhelp (0.1.2+dev)
testsdk (0.1.0+dev)
utility-automation (0.1.1)
vm (2.0.6+dev)

Python (Windows) 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)]

**OS Version:** What OS and version are you using?  
Answer here: Win10CU

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

**Comment by brendandburns** [comment]
I sent a PR with a partial fix, but this is mostly expected.

My design choice was to require the user to be specific, otherwise we may accidentally delete a lock that the user doesn't expect us to delete.

e.g. suppose a user has a subscription level lock named 'foo' and a resource group level lock named 'foo'

If the user has already deleted the subscription level lock, and then accidentally re-runs the same command, I don't think we want to delete the resource group level lock.

I'm open to other suggestions you might have to improve the UX.

**Comment by tjprescott** [comment]
1. I wouldn't put the "Expected blah" message because if you aren't trying to guess the lock for the user (which makes sense) then this sounds like you are. In general, the CLI doesn't try and guess what the user meant to do.  In this case, I should simply get a 404.

2. The help text says that `--resource-type NAMESPACE/TYPE` is valid, but the command doesn't accept it. It should accept the alternate form to be consistent with the other generic ARM commands, so this is a bug.

3. One way to avoid the confusion with locks would be to have different lock commands:
- az lock : Current, all-in-one solution. Could be deprecated.
- az resource lock : Manage resource locks
- az group lock : Manage resource group locks
- az account lock : Manage subscription locks

In this way, the user would know exactly what type of lock he/she is working with. Just a suggestion--not really the point of this thread. :smile:
