### ISSUE TITLE
[VM/VMSS] Cannot create a new subnet on an existing Vnet 

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#3494]
Scenario:  I created an app-gateway, which creates a VNET and a subnet. I want to add a VM to the backend pool, which requires the VM exists in the same VNET; however, the app-gateway itself has to be in its own subnet.  SO, what I'd like to do is create the VM, specify the existing VNET but specify a new subnet for that VNET. This does not work. The VM attempts to create a new VNET with the same name, which fails because the app-gateway is using that VNET.

VM create supports:
1. Specify nothing and use an existing VNET/subnet
2. Specify an existing VNET and subnet
3. Specify parameter to create a new VNET *and* subnet.

We should support a fourth scenario:
4. Specify parameter to create a new subnet on an existing VNET. 

The workaround is simply to create the extra subnet and then create the VM using the now-existing subnet.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: dev_setup.py

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.6+dev)

acr (2.0.4+dev)
acs (2.0.6+dev)
appservice (0.1.6+dev)
batch (3.0.0+dev)
cdn (0.0.2+dev)
cloud (2.0.2+dev)
cognitiveservices (0.1.2+dev)
component (2.0.4+dev)
configure (2.0.6+dev)
core (2.0.6+dev)
cosmosdb (0.1.6+dev)
dla (0.0.6+dev)
dls (0.0.6+dev)
feedback (2.0.2+dev)
find (0.2.2+dev)
interactive (0.3.2+dev)
iot (0.1.5+dev)
keyvault (2.0.4+dev)
lab (0.0.4+dev)
monitor (0.0.4+dev)
network (2.0.6+dev)
nspkg (3.0.0+dev)
profile (2.0.4+dev)
rdbms (0.0.1+dev)
redis (0.2.3+dev)
resource (2.0.6+dev)
role (2.0.4+dev)
sf (1.0.1+dev)
sql (2.0.3+dev)
storage (2.0.6+dev)
taskhelp (0.1.2+dev)
testsdk (0.1.0+dev)
utility-automation (0.1.1)
vm (2.0.6+dev)

Python (Windows) 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)]

**OS Version:** What OS and version are you using?  
Answer here:  Win10 CU

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

**Comment by adewaleo** [comment]
Per our discussion, I will be closing this issue @tjprescott. There is a simple workaround and adding this feature might not be so straightforward, giving the current implementation of create_vm/vmss and the fact that subnets are subresources.
