### ISSUE TITLE
Can't obtain full blob list for a large blob container

### ISSUE THREAD

**Issue by cornelcreanga** [Azure/azure-cli#3496]
### Description
I'm running this command

creanga-macOS:tmp creanga$ time  az storage blob list --container-name REMOVED--output table --account-name REMOVED --account-key REMOVED> list.txt

The blob container has about 6.5 millions blobs.
Command result:

/Users/creanga/bin/az: line 2: 60560 Killed: 9               /Users/creanga/lib/azure-cli/bin/python -m azure.cli "$@"

real	329m28.797s
user	81m7.952s
sys	63m57.351s

Note: it works for a tiny container. 

In the end I've obtained the full list using the Azure Java SDK - however it would be nice to only use the cli tools. 

Environment summary

Install Method: How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)
Answer here:
curl -L https://aka.ms/InstallAzureCli | bash

CLI Version: What version of the CLI and modules are installed? (Use az --version)
Answer here:
azure-cli (2.0.6)

acr (2.0.4)
acs (2.0.6)
appservice (0.1.6)
batch (2.0.4)
cdn (0.0.2)
cloud (2.0.2)
cognitiveservices (0.1.2)
command-modules-nspkg (2.0.0)
component (2.0.4)
configure (2.0.6)
core (2.0.6)
cosmosdb (0.1.6)
dla (0.0.6)
dls (0.0.6)
feedback (2.0.2)
find (0.2.2)
interactive (0.3.2)
iot (0.1.5)
keyvault (2.0.4)
lab (0.0.4)
monitor (0.0.4)
network (2.0.6)
nspkg (3.0.0)
profile (2.0.4)
rdbms (0.0.1)
redis (0.2.3)
resource (2.0.6)
role (2.0.4)
sf (1.0.1)
sql (2.0.3)
storage (2.0.6)
vm (2.0.6)

Python (Linux) 2.7.5 (default, Aug 2 2016, 04:20:16)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

OS Version: What OS and version are you using?
Answer here: OSX Sierra

Shell Type: What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)
Answer here: bashre:

**Comment by williexu** [comment]
Closing in favor of: https://github.com/Azure/azure-cli/issues/3745
