### ISSUE TITLE
'az feedback' command errors out on MacOS command line

### ISSUE THREAD

**Issue by peter-gergely-horvath** [Azure/azure-cli#3503]
### Description
'az feedback' command errors out on MacOS command line with error message 'unknown locale: UTF-8'

The 'az feedback' utility should allow users to share quick feedback on the tooling. Unfortunately, it does NOT work on MacOS at all, it fails after 'If you would like to join our insiders program and receive tips, tricks, and early access to new features, let us know by leaving your email address (leave blank to skip)' step with 'unknown locale: UTF-8'

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
Official Microsoft interactive installer package for Mac OS  

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.2 

**OS Version:** What OS and version are you using?  
Answer here:
Mac OS 16.6.0 Darwin, x86_64

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Mac OS bash

See screen shot ![screen shot 2017-05-25 at 15 08 43](https://cloud.githubusercontent.com/assets/15800802/26545248/36bfdc2c-4465-11e7-99d4-cc344b3df0f5.png)

**Comment by tjprescott** [comment]
If you run this with --debug do you get any more information on the error?

**Comment by peter-gergely-horvath** [comment]
Not really -- here is the screenshot:

![screen shot 2017-05-31 at 22 05 49](https://cloud.githubusercontent.com/assets/15800802/26651667/bced0e98-464d-11e7-88ca-1135574b8480.png)

**Comment by derekbekoe** [comment]
This may have been an isolated case but it's working after I just verified on macOS.
