### ISSUE TITLE
Installing in Docker via script does not work

### ISSUE THREAD

**Issue by sjdweb** [Azure/azure-cli#3506]
### Description
If you'd like to install the Azure CLI on your own Docker image, the script fails as it requires access to `/dev/tty`.

After hours of trying various things, I luckily discovered you publish `apt` packages for `Bash on Windows` users. This will suffice for now on my `ubuntu:14.04`-based image.

***Error:***
```
sh: 32: cannot open /dev/tty: No such device or address
```

I'm aware you publish your own Docker image, but my use case is building an application via CI in a Docker container. This is using bitbucket pipelines specifically, which only allows a one-step build process at the moment, so I can not separate build and deploy and thus must use one image.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: Script

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: Latest

**OS Version:** What OS and version are you using?  
Answer here: Ubuntu 14.04 via Docker

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Docker/macOS

**Comment by derekbekoe** [comment]
That install script is designed to be interactive.
Try this installer which is non-interactive and reproducible:
https://github.com/derekbekoe/azure-cli/blob/bdd09472eb99a4baeda55ae124edfedc49eeb577/packaged_releases/bundled/README.md#using-the-bundled-installer

This should fit your scenario. You're welcome to re-open if it does not.
