### ISSUE TITLE
[CosmosDB] `az cosmosdb list-connection-strings` is not the same as the portal

### ISSUE THREAD

**Issue by devigned** [Azure/azure-cli#3507]
### Description

When running `az cosmosdb list-connection-strings`, the connection string is not the connection strings as seen in the portal.

For example:
- az: `mongodb://username:password@testdj2.documents.azure.com:10250/?ssl=true`
- portal: `mongodb://username:password@testdj2.documents.azure.com:10255/?ssl=true&replicaSet=globaldb`

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: Source

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: ref 8dd7cf7

**OS Version:** What OS and version are you using?  
Answer here: OS X

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by devigned** [comment]
Looks like this might be a service issue as this command is a proxy to the management plane.

**Comment by devigned** [comment]
@moderakh or @dmakwana any thoughts on this one?

**Comment by moderakh** [comment]
This is account management. Should be assigned to digvijay @dmakwana

**Comment by shurd** [comment]
These connection strings match now. They follow the format that ends with "&replicaSet=globaldb"

**Comment by tjprescott** [comment]
Thanks @shurd. I will close this.
