### ISSUE TITLE
[Question] How to define virtual applications and directories on az resource create --properties?

### ISSUE THREAD

**Issue by zignd** [Azure/azure-cli#3512]
### Description
I'm struggling to define virtual applications and directories through `az resource create --properties`. This option is available here on the Azure portal:

![Azure portal](http://i.imgur.com/BWSHEX0.png)

Here's what I've tried:

```
az resource create --name "contoso-az-1" --resource-group "contoso-web" --resource-type "Microsoft.Web/sites" --properties '{\"virtualApplications\":[{\"virtualPath\":\"/\",\"physicalPath\":\"site\\wwwroot\"},{\"virtualPath\":\"/api\",\"physicalPath\":\"site\\api\\wwwroot\"}],\"serverFarmId\":\"ServicePlanS3\"}'
```

It works, the app service is being created and the `serverFarmId` sets the service plan just as I needed, but the `virtualApplications` property is not being considered and when I check the app service on the Azure portal only the default settings for virtual applications and directories is set.

I got those properties by guess, looking at a generated automation script because I could not find a documentation on what is accepted by this `--properties` option.

There's any documentation about the JSON format accepted by this `--properties` option? How do I use it to define virtual applications and directories on a new app service?

Thanks in advance.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
```
azure-cli (2.0.6)

acr (2.0.4)
acs (2.0.6)
appservice (0.1.6)
batch (2.0.4)
cdn (0.0.2)
cloud (2.0.2)
cognitiveservices (0.1.2)
command-modules-nspkg (2.0.0)
component (2.0.4)
configure (2.0.6)
core (2.0.6)
cosmosdb (0.1.6)
dla (0.0.6)
dls (0.0.6)
feedback (2.0.2)
find (0.2.2)
interactive (0.3.2)
iot (0.1.5)
keyvault (2.0.4)
lab (0.0.4)
monitor (0.0.4)
network (2.0.6)
nspkg (3.0.0)
profile (2.0.4)
rdbms (0.0.1)
redis (0.2.3)
resource (2.0.6)
role (2.0.4)
sf (1.0.1)
sql (2.0.3)
storage (2.0.6)
vm (2.0.6)

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
```

**OS Version:** What OS and version are you using?  
Answer here:
```
Edition: Windows 10 Home Single Language
Version: 1703
OS Build: 15063.332
```
**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: PowerShell

**Comment by tjprescott** [comment]
In general, whatever the structure of a "show" command looks like it the format you would use when setting properties.  Is there a reason you are using the generic resource commands to accomplish this rather than the dedicated webapp/appservice commands?  Are they missing the functionality you are looking for?

**Comment by zignd** [comment]
Thanks! Your reply gave me some light! I decided to investigate the resource using the Azure Resource Explorer and I figured out that the property I was trying to set was located in different resource type, one named `Microsoft.Web/sites/config`. So I created the app service normally and then I proceeded to update this resource to set `virtualApplications` property like so:

    az resource update --name "contoso-az-1/config/web" --resource-group "contoso-web" --resource-type "Microsoft.Web/sites/config" --set 'properties.virtualApplications=[{"virtualPath":"/","physicalPath":"site\wwwroot"},{"virtualPath":"/api","physicalPath":"site\api\wwwroot"}]'

> Is there a reason you are using the generic resource commands to accomplish this rather than the dedicated webapp/appservice commands?

Well, I initially choose it because I wanted to be able to create an app service from scratch in one command and to be able to set the `virtualApplications` property. But it doesn't seem to be possible with the available options on both commands - `az webapp` and `az appservice`. Please correct me if I'm wrong.

> Are they missing the functionality you are looking for?

I'm not sure, but there might be a feature I wish I could find in them. I'd say that it's the option to set the virtual applications and directories, it seems to me that it should be on `az webapp config set`, correct me if I'm wrong. Because `az webapp config show` when given the name and resource group of a `Microsoft.Web/sites` resource type returns a JSON object containing a property named `virtualApplications`, and its value is what I managed to change using `az resource update`.

**Comment by tjprescott** [comment]
@yugangw-msft is most familiar with the webapp commands.

**Comment by yugangw-msft** [comment]
CLI doesn't expose the strong type flag for `virtual applications`, because you are the first one asking for it.
If you like to use `az resource set`, then yes, the resource type is `Microsoft.Web/sites/config`. And yes, related webapp command to update is `az webapp config set`, if CLI would expose this support.  
At the same time, for `create`, I would much recommend to use `group deployment create`. You can use `az group export` on an existing group with such webapp so to get the initial template to start with.

**Comment by yugangw-msft** [comment]
I will keep this issue open in case there are new incoming voices the bump up the priority

**Comment by zignd** [comment]
Oh, thanks for suggesting this alternative method through `az group deployment create`, but for now I keep the `az resource set` to avoid having to handle template files on my CI/CD process.

**Comment by iyerusad** [comment]
Seconding the desire for this. I will attempt to use `az resource update` as zignd mentions above but would like to see this in my strongly typed flag. Similar in spirit issue also at #3553.

**Comment by iyerusad** [comment]
Oddly enough I am not able to get any variation of this `az resource update` command to function properly:

```
myapp="app123"
rsgroup="blah"

az resource show --name $myapp --resource-group $rsgroup --resource-type "Microsoft.Web/sites/config" | jq .properties.virtualApplications
```
Lists the virtualApplications, as expected


However, this command
```
az resource update --name $myapp --resource-group $rsgroup --resource-type "Microsoft.Web/sites/config" --set 'properties.virtualApplications=[{\"virtualPath\":\"\/\",\"physicalPath\":\"site\\wwwroot\",\"virtualDirectories\":null},{\"virtualPath\":\"\/api\",\"physicalPath\":\"site\\wwwroot\\api\",\"virtualDirectories\":null}]'
```
does not error out but spits out unchanged value. I would expect an error but it silently "fails"?

**Comment by sdementen** [comment]
+1 for supporting web.config changes in the cli

**Comment by automagicallyio** [comment]
Any update on this? How do I configure additional virtual applications within the webapp?

**Comment by iyerusad** [comment]
@automagicallyio I was able to achieve this in a bit of janky manner but it works:

```
echo -n '[
        {
          "physicalPath"':' "site\\wwwroot",
          "preloadEnabled"':' false,
          "virtualDirectories"':' null,
          "virtualPath"':' "/"
        },
        {
          "physicalPath"':' "site\\wwwroot\\app2",
          "preloadEnabled"':' false,
          "virtualDirectories"':' null,
          "virtualPath"':' "/app2"
        }
      ]' > json.txt

json=$(cat json.txt)

az resource update --name "${webappname}/config/web" --resource-group "$rsgroupname" --resource-type "Microsoft.Web/sites/config" --set properties.virtualApplications="$json" | jq .properties.virtualApplications
```

Would still like to see this as a flag in az cli though.

**Comment by dnplkndll** [comment]
I am still getting unchanged values even with the second method of passing the json

**Comment by panchagnula** [comment]
Closing this - tracking this as a feature request here https://github.com/Azure/azure-cli/issues/6463

**Comment by Pr0t0star** [comment]
@dano-reisys your example is missing in your comment.

Im facing the exact same issue as @dnplkndll on both examples

if your referring to backslashes on the path, these have been added and are in the example above too.

**Comment by spatialman** [comment]
> @automagicallyio I was able to achieve this in a bit of janky manner but it works:
> 
> ```
> echo -n '[
>         {
>           "physicalPath"':' "site\\wwwroot",
>           "preloadEnabled"':' false,
>           "virtualDirectories"':' null,
>           "virtualPath"':' "/"
>         },
>         {
>           "physicalPath"':' "site\\wwwroot\\app2",
>           "preloadEnabled"':' false,
>           "virtualDirectories"':' null,
>           "virtualPath"':' "/app2"
>         }
>       ]' > json.txt
> 
> json=$(cat json.txt)
> 
> az resource update --name "${webappname}/config/web" --resource-group "$rsgroupname" --resource-type "Microsoft.Web/sites/config" --set properties.virtualApplications="$json" | jq .properties.virtualApplications
> ```
> 
> Would still like to see this as a flag in az cli though.

This worked like a charm to me...
