### ISSUE TITLE
XMLError when trying to exceed max number of ACL entries

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#355]
The current max number of ACL entries from the storage SDK is 5. If you attempt to add more, you will get an error stating that your XML is invalid.

An issue has been opened against the storage SDK to provide a more accurate error in this instance so that we don't need to hard code a limit that could change without our knowledge.

https://github.com/Azure/azure-storage-python/issues/181

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
