### ISSUE TITLE
Feature Request: azure cli to enable "App Service Authentication/Authorization"

### ISSUE THREAD

**Issue by iyerusad** [Azure/azure-cli#3553]
### Description
Capability to use azure cli to enable **[App Service Authentication/Authorization](https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-get-started-2#authenticate-your-users)**.

---

Currently this only appears to be supported via portal interface, (as described here https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-get-started-2#authenticate-your-users)

**Comment by bccore** [comment]
+1

Hi,

I was just searching for an answer to this as well. Are there any other methods of achieving this in an automated way? I guess I'll be looking at RM templates to configure some parts of my infrastructure to fill in the missing gaps.

Thanks!
Ben.

**Comment by iyerusad** [comment]
@bccore Are you willing to share the other methods you found to achieve this (something about RM templates)? I would prefer to see this implemented as standard az-cli fare but I would consider expanding my knowledge of an alternative in the meantime.

**Comment by bccore** [comment]
@iyerusad sorry, for not responding earlier. I haven't yet a working solution for this to automate this all. It will by a combination of the graph api for azure objects and resource manager templates for the rest. We're actually looking to avoid using azure cli now so we have everything in one place. It's very much a work in progress though as the documentation is not complete...

**Comment by iyerusad** [comment]
In the interim, Here is a stackoverflow question that goes into some detail on how to do this using a Azure Resource Manager (ARM) template: <https://stackoverflow.com/questions/35846300/is-it-possible-to-script-the-configuration-of-azure-app-service-authentication/41882512#41882512>
