### ISSUE TITLE
Curl install on RHEL 7.3 times out connecting to aka.ms

### ISSUE THREAD

**Issue by JanaJensen** [Azure/azure-cli#3554]
### Description
**Outline the issue here:**

The command to install azure-cli times out and never runs.

[~]$ sudo curl -L https://aka.ms/InstallAzureCli | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:07 --:--:--     0curl: (7) Failed connect to aka.ms:443; Connection timed out
[~]$ sudo curl https://azurecliprod.blob.core.windows.net/install | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:07 --:--:--     0curl: (7) Failed connect to azurecliprod.blob.core.windows.net:443; Connection timed out
[~]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.3 (Maipo)

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: curl -L https://aka.ms/InstallAzureCli | bash

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: n/a

**OS Version:** What OS and version are you using?  
Answer here: Red Hat Enterprise Linux Server release 7.3 (Maipo)

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by derekbekoe** [comment]
Is there a proxy/firewall blocking the download?
Does it work without sudo?

**Comment by JanaJensen** [comment]
I can access other urls. It doesn't work without sudo.

**Comment by derekbekoe** [comment]
What version of `curl` are you using?

**Comment by JanaJensen** [comment]
$ curl --version
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.21 Basic ECC zlib/1.2.7 libidn/1.28 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets

**Comment by derekbekoe** [comment]
Curl has a `--connect-timeout <seconds>` and `-m, --max-time <seconds>` parameters.
You can try setting them.

This doesn't look CLI related though as the download link is working.

**Comment by JanaJensen** [comment]
I'll check with our networking team. It's working fine on another server.

**Other machine:**
 curl https://azurecliprod.blob.core.windows.net/install | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1252  100  1252    0     0   2446      0 --:--:-- --:--:-- --:--:--  2450
Downloading Azure CLI install script from https://azurecliprod.blob.core.windows.net/install.py to /tmp/azure_cli_install_tmp_Mf1k.
######################################################################## 100.0%
5.85
/tmp/azure_cli_install_tmp_Mf1k: OK
Running install script.
bash: line 32: /tmp/azure_cli_install_tmp_Mf1k: Permission denied

**This machine:**
 curl -L https://aka.ms/InstallAzureCli --connect-timeout 500 | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:07 --:--:--     0curl: (7) Failed connect to aka.ms:443; Connection timed out
