### ISSUE TITLE
Progress reporting should be cleared before completing

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#3555]
### Description
When a LRO completes, the output is pasted over the existing progress text.  Can we clear that out before presenting the output?

```
$ az vm create -g MyRGTemp -n MyVMName2 --image UbuntuLTS --out json | jq
{\ Finished ..
  "fqdns": "",
  "id": "/subscriptions/db5eb[...]cce5/resourceGroups/MyRGTemp/providers/Microsoft.Compute/virtualMachines/MyVMName2",
  "location": "westus",
  "macAddress": "00-0D-3A-37-49-0B",
  "powerState": "VM running",
  "privateIpAddress": "10.0.0.5",
  "publicIpAddress": "01.01.254.74",
  "resourceGroup": "MyRGTemp"
}
```
---

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

**OS Version:** What OS and version are you using?  
Answer here:

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

**Comment by yugangw-msft** [comment]
Suggest we prioritize this and get it fixed in the next sprint or so. This glitch is widespread and makes CLI appear not well done

**Comment by chewong** [comment]
Can only reproduce this issue on a Windows machine, with cmd.exe. For long-running operations, we use a third-party library called humanfriendly to indicate the progress and animate the spinner. Once the LRO is finished, the third-party library writes an ANSI escape sequence (called `erase_line_code` in the third-party library) `'\r\x1b[K'` to the standard out stream to remove the spinner. Also noticed that [the erase_line_code was actually modified to an empty string](https://github.com/Azure/azure-cli/blame/dev/src/azure-cli-core/azure/cli/core/commands/progress.py#L13) for Windows machines. That means that we are writing an empty string to the standard out stream when the LRO is finished, causing the spinner not to disappear for Windows machines.
