### ISSUE TITLE
OS Disk name for vm create is not stable -> command is not idempotent

### ISSUE THREAD

**Issue by johanste** [Azure/azure-cli#3563]
From the vm_create function:

    ...
    os_disk_name = os_disk_name or 'osdisk_{}'.format(random_string(10))
    ....

This means that if I invoke the command twice with the same parameters (with os disk name omitted), I will (with a very high probability :)) end up with two disks, one of which is orphaned. This goes against the goal of having idempotent commands.

**Comment by tjprescott** [comment]
Actually it just errors out saying you can't change OSDisk name.
