### ISSUE TITLE
[ACS] Default image not found for Kubernetes / Windows

### ISSUE THREAD

**Issue by neilpeterson** [Azure/azure-cli#3564]
### Description
When creating a Kubernetes cluster for Windows based containers, the default image is not found. I have updated to the lastest CLI version `2.0.7`, tested on both Windows 10 (WSL) and macOS, in both the west and east us regions.

```
az acs create --resource-group test555 --orchestrator-type Kubernetes --name myK8SCluster --windows --generate-ssh-keys --admin-password Password12
```

Error:

```
The platform image 'MicrosoftWindowsServer:WindowsServer:2016-Datacenter-with-Containers:2016.0.20170127' is not available.
```

Output from `az vm image list --offer WindowsServer --all --output table`:

```
WindowsServer             MicrosoftWindowsServer               2016-Datacenter-with-Containers        MicrosoftWindowsServer:WindowsServer:2016-Datacenter-with-Containers:2016.127.20170406      2016.127.20170406
WindowsServer             MicrosoftWindowsServer               2016-Datacenter-with-Containers        MicrosoftWindowsServer:WindowsServer:2016-Datacenter-with-Containers:2016.127.20170411      2016.127.20170411
WindowsServer             MicrosoftWindowsServer               2016-Datacenter-with-Containers        MicrosoftWindowsServer:WindowsServer:2016-Datacenter-with-Containers:2016.127.20170510      2016.127.20170510
```

Perhaps updating the CLI default behavior to use the latest image would resolve.

```
MicrosoftWindowsServer:WindowsServer:2016-Datacenter-with-Containers:Latest
```

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  

```
azure-cli (2.0.7)

acr (2.0.5)
acs (2.0.7)
appservice (0.1.7)
batch (3.0.0)
billing (0.1.0)
cdn (0.0.3)
cloud (2.0.3)
cognitiveservices (0.1.3)
command-modules-nspkg (2.0.0)
component (2.0.5)
configure (2.0.7)
consumption (0.1.0)
core (2.0.7)
cosmosdb (0.1.7)
dla (0.0.7)
dls (0.0.7)
feedback (2.0.3)
find (0.2.3)
interactive (0.3.3)
iot (0.1.6)
keyvault (2.0.5)
lab (0.0.5)
monitor (0.0.5)
network (2.0.7)
nspkg (3.0.0)
profile (2.0.5)
rdbms (0.0.2)
redis (0.2.4)
resource (2.0.7)
role (2.0.5)
sf (1.0.2)
sql (2.0.4)
storage (2.0.7)
vm (2.0.7)

Python (Linux) 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609]

Python location '/home/neillocal/lib/azure-cli/bin/python'
```

**OS Version:** What OS and version are you using?  

I've verified on:

- Windows 10
- macOS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  

- Windows 10 WSL / Bash on Windows
- macOS default bash

**Comment by neilpeterson** [comment]
I've spoken with Anthony and Surya and understand that a fix is on its way.

**Comment by brendandburns** [comment]
Yes, this is a known issue with the service (sorry!) the fix is rolling out right now but may take a few days to get everywhere.

Closing this issue.
