### ISSUE TITLE
HDInsights Commands

### ISSUE THREAD

**Issue by ramayer** [Azure/azure-cli#3571]
### Description
**The old Azure CLI had features to manage HDInsight clusters as described here:**

https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-administer-use-command-line

Reading and searching the documentation of the new CLI ( https://docs.microsoft.com/en-us/cli/azure/overview ), it doesn't seem to reference HDInsight. 

Can such features be added to the new CLI?

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

 curl -L https://aka.ms/InstallAzureCli | bash

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

ron@i5:~/work/fli/azure/azure-automation/bin$ az --version
azure-cli (2.0.7)

acr (2.0.5)
acs (2.0.7)
appservice (0.1.7)
batch (3.0.0)
billing (0.1.0)
cdn (0.0.3)
cloud (2.0.3)
cognitiveservices (0.1.3)
command-modules-nspkg (2.0.0)
component (2.0.5)
configure (2.0.7)
consumption (0.1.0)
core (2.0.7)
cosmosdb (0.1.7)
dla (0.0.7)
dls (0.0.7)
feedback (2.0.3)
find (0.2.3)
interactive (0.3.3)
iot (0.1.6)
keyvault (2.0.5)
lab (0.0.5)
monitor (0.0.5)
network (2.0.7)
nspkg (3.0.0)
profile (2.0.5)
rdbms (0.0.2)
redis (0.2.4)
resource (2.0.7)
role (2.0.5)
sf (1.0.2)
sql (2.0.4)
storage (2.0.7)
vm (2.0.7)

Python (Linux) 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4]

Python location '/home/ron/lib/azure-cli/bin/python'

**OS Version:** What OS and version are you using?  
Answer here:

$ uname -a
Linux i5 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

bash

**Comment by tjprescott** [comment]
cc/ @mayurid

**Comment by syedhassaanahmed** [comment]
+1

**Comment by JaminShanti** [comment]
+1

**Comment by avnarun** [comment]
+1

**Comment by vishwanath79** [comment]
+ 1

**Comment by nalthoff** [comment]
+1

**Comment by gsacavdm** [comment]
+1

**Comment by RoelantStegmann** [comment]
+1

**Comment by shaynewang** [comment]
+1

**Comment by justinmjc** [comment]
+1

**Comment by tjprescott** [comment]
I've posted this request in the Azure feedback forms:

https://feedback.azure.com/forums/217335-hdinsight/suggestions/34482229-on-board-hdinsights-to-azure-cli-2-0

For those who have +1'ed this thread, please go to the link and cast your votes for this feature.

**Comment by prashanthmadi** [comment]
It would be great if we could also have a way to delete edge node using az cli which doesn't exist in azure cli v1.0

**Comment by yugangw-msft** [comment]
I am closing this as CLI has hdinsights support now though not very completed yet.
Please open individual issues for any feature missing.

**Comment by DenisBiondic** [comment]
@yugangw-msft what features are missing then?
