### ISSUE TITLE
az image create documentation insufficient/out of date

### ISSUE THREAD

**Issue by stewartadam** [Azure/azure-cli#3572]
### Description
1. Documentation for `az image create` (https://docs.microsoft.com/en-us/cli/azure/image) and its help strings do not provide sufficient context to enable users to decide when to use the parameters (e.g. how does `--source` and `--data-disk-sources` differ?
2. Examples reference non-existent parameter `--data-snapshot`
3. Only `-n` and `-g` are marked as required flags, some invocations fail with NoneType error e.g. `az image create -n foo -g bar --data-disk-sources mdname --os-type windows`:
```
usage: az image create [-h] [--output {json,tsv,table,jsonc}] [--verbose]
                       [--debug] [--query JMESPATH] --resource-group
                       RESOURCE_GROUP_NAME --name NAME
                       [--os-type {Windows,Linux}] [--location LOCATION]
                       [--source SOURCE]
                       [--data-disk-sources DATA_DISK_SOURCES [DATA_DISK_SOURCES ...]]
                       [--tags [TAGS [TAGS ...]]]
az image create: error: 'NoneType' object has no attribute 'lower'
```
Providing `--source` appears to suppress the error.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip3

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
```
azure-cli (2.0.7)

acr (2.0.5)
acs (2.0.7)
appservice (0.1.7)
batch (3.0.0)
billing (0.1.0)
cdn (0.0.3)
cloud (2.0.3)
cognitiveservices (0.1.3)
command-modules-nspkg (2.0.0)
component (2.0.5)
configure (2.0.7)
consumption (0.1.0)
core (2.0.7)
cosmosdb (0.1.7)
dla (0.0.7)
dls (0.0.7)
documentdb (0.1.5)
feedback (2.0.3)
find (0.2.3)
interactive (0.3.3)
iot (0.1.6)
keyvault (2.0.5)
lab (0.0.5)
monitor (0.0.5)
network (2.0.7)
nspkg (3.0.0)
profile (2.0.5)
rdbms (0.0.2)
redis (0.2.4)
resource (2.0.7)
role (2.0.5)
sf (1.0.2)
sql (2.0.4)
storage (2.0.7)
vm (2.0.7)

Python (Darwin) 3.6.1 (default, Apr  4 2017, 09:40:21) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]

Python location '/usr/local/opt/python3/bin/python3.6'
```

**OS Version:** What OS and version are you using?  
Answer here: MacOS 10.12.4

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Bash

**Comment by tjprescott** [comment]
From your output, there is a validation bug--not just a documentation problem.

**Comment by stewartadam** [comment]
Agreed, it looks like there's a traceback triggered on incomplete CLI parameters, and the docs don't sufficiently clarify what a complete CLI sequence would look like (imo).

**Comment by stewartadam** [comment]
Documentation on `az disk` faces similar issues, notably both `image` and `disk` state that `--source` can be a SAS URI, but when I supply the HTTPS SAS URI generated for a Managed Disk, it fails to parse.

**Comment by stewartadam** [comment]
Another issue, trying to migrate a snapshot from one RG to another in the same sub by creating a new snapshot pointing to the same disk:
```
az snapshot create -g stad-redblueDeploy1 -n $snapshotName --source $snapshotId
```
just returns "The entity was not found." despite $snapshotId being a snapshot ID (e.g. `/subscriptions/GUID/resourceGroups/RG_NAME/providers/Microsoft.Compute/snapshots/SNAPSHOT_NAME`) per current docs.

**Comment by stewartadam** [comment]
Running the same command line but with `az image`:
```
az image create -g rg_name -n $snapshotName --source $snapshotId --os-type windows
```
just yeilds
```
An internal execution error occurred.
```

**Comment by yugangw-msft** [comment]
> Documentation on az disk faces similar issues, notably both image and disk state that --source can be a SAS URI, but when I supply the HTTPS SAS URI generated for a Managed Disk, it fails to parse.

I will update the help to be `unmanaged blob uri`, `SAS` is not a right term

> Another issue, trying to migrate a snapshot from one RG to another in the same sub by creating a new snapshot pointing to the same disk:
 
You have to supply the argument value of:
    `--source-storage-account-id   : Used when source blob is in a different subscription.`

> An internal execution error occurred.
It is a known bad server error for unmatched regions.  Let me contact CRP team for the progress/plan to fix this
