### ISSUE TITLE
Template Creates Not Goal Seeking

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#3589]
If you run the following twice:
`az vm create -g {rg} -n {vm} --image UbuntuLTS --verbose`

You will note that in the second instance, the resulting template uses the pre-created VNET and does not include it as a resource in the generated template. Thus, if you were to use the various VM create arguments that affect the VNET or subnet, those parameters would either be ignored or the CLI would throw an error that you can't use those arguments with an existing VNET.

Should, instead, the command generate the template and make a best-faith effort to apply the arguments to the resources, even if they already exist?

**Comment by adewaleo** [comment]
@tjprescott  closing this as it was fixed in #3586

**Comment by tjprescott** [comment]
This issue was not fixed in that PR.

**Comment by tjprescott** [comment]
Essentially, while this issue is legitimate, no customers have complained about this behavior. Given the engineering cost involved, I am closing this issue.
