### ISSUE TITLE
dryrun error when running "az storage blob download-batch"

### ISSUE THREAD

**Issue by odlevakp** [Azure/azure-cli#3592]
### Description
Using `--dryrun` with `az storage blob download-batch` creates following error:
```
object of type 'generator' has no len()
Traceback (most recent call last):
[...]
  File "/root/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/command_modules/storage/blob.py", line 119, in storage_blob_download_batch
    logger.warning('      total %d', len(source_blobs))
TypeError: object of type 'generator' has no len()
```

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
interactive script / Docker

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
azure-cli (2.0.7)

**OS Version:** What OS and version are you using?  
Issue found with docker container, macOS and Ubuntu 14.04

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
bash

**Comment by troydai** [comment]
Thank you @odlevakp
