### ISSUE TITLE
Creation of Windows Kubernetes cluster fails

### ISSUE THREAD

**Issue by dswersky** [Azure/azure-cli#3594]
### Description
When trying to create a Windows-Container Kubernetes cluster using `azs create` the provision fails.  The same process fails with the same error through the RM Portal.

Command:
`***@DAVEPC:~$ az acs create -n RMA-KB-01 -d rmakb -g RG-KB-01 --generate-ssh-keys --orchestrator-type kubernetes --windows --admin-password=*****`

Error:
```
At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. {   "status": "Failed",   "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "ProvisioningFailed",
        "message": "Provisioning of resource(s) for container service 'RMA-KB-01' in resource group 'RG-KB-01' failed with errors: Resource type: Microsoft.Compute/virtualMachines, name: 1E4FCacs9001, id: /subscriptions/64b38e64-5dbd-438d-84d3-94e87b553a51/resourceGroups/RG-KB-01/providers/Microsoft.Compute/virtualMachines/1E4FCacs9001, StatusCode: NotFound, StatusMessage: \\n {\r\n  \"error\": {\r\n    \"code\": \"ImageNotFound\",\r\n    \"target\": \"imageReference\",\r\n    \"message\": \"The platform image 'MicrosoftWindowsServer:WindowsServer:2016-Datacenter-with-Containers:2016.0.20170127' is not available. Verify that all fields in the storage profile are correct.\"\r\n  }\r\n}\r\nResource type: Microsoft.Compute/virtualMachines, name: 1E4FCacs9000, id: /subscriptions/64b38e64-5dbd-438d-84d3-94e87b553a51/resourceGroups/RG-KB-01/providers/Microsoft.Compute/virtualMachines/1E4FCacs9000, StatusCode: NotFound, StatusMessage: \\n {\r\n  \"error\": {\r\n    \"code\": \"ImageNotFound\",\r\n    \"target\": \"imageReference\",\r\n    \"message\": \"The platform image 'MicrosoftWindowsServer:WindowsServer:2016-Datacenter-with-Containers:2016.0.20170127' is not available. Verify that all fields in the storage profile are correct.\"\r\n  }\r\n}\r\nResource type: Microsoft.Compute/virtualMachines, name: 1E4FCacs9002, id: /subscriptions/64b38e64-5dbd-438d-84d3-94e87b553a51/resourceGroups/RG-KB-01/providers/Microsoft.Compute/virtualMachines/1E4FCacs9002, StatusCode: NotFound, StatusMessage: \\n {\r\n  \"error\": {\r\n    \"code\": \"ImageNotFound\",\r\n    \"target\": \"imageReference\",\r\n    \"message\": \"The platform image 'MicrosoftWindowsServer:WindowsServer:2016-Datacenter-with-Containers:2016.0.20170127' is not available. Verify that all fields in the storage profile are correct.\"\r\n  }\r\n}\r\n"
      }
    ]   } }  Correlation ID: c69bc7a4-2d0a-431b-ac7e-f98894110eea
```

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
I installed the Azure CLI using the Ubuntu for Windows instructions here: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
azure-cli (2.0.7)

acr (2.0.5)
acs (2.0.7)
appservice (0.1.7)
batch (3.0.0)
billing (0.1.0)
cdn (0.0.3)
cloud (2.0.3)
cognitiveservices (0.1.3)
command-modules-nspkg (2.0.0)
component (2.0.5)
configure (2.0.7)
consumption (0.1.0)
core (2.0.7)
cosmosdb (0.1.7)
dla (0.0.7)
dls (0.0.7)
feedback (2.0.3)
find (0.2.3)
interactive (0.3.3)
iot (0.1.6)
keyvault (2.0.5)
lab (0.0.5)
monitor (0.0.5)
network (2.0.7)
nspkg (3.0.0)
profile (2.0.5)
rdbms (0.0.2)
redis (0.2.4)
resource (2.0.7)
role (2.0.5)
sf (1.0.2)
sql (2.0.4)
storage (2.0.7)
vm (2.0.7)

Python (Linux) 3.6.1 (default, May 30 2017, 16:59:26)
[GCC 4.8.4]

Python location '/opt/az/bin/python3'

**OS Version:** What OS and version are you using?  
Answer here:

Windows 10.0.14393.0

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
Ubuntu for Windows

**Comment by stimms** [comment]
I am also seeing this issue. I opened a parallel issue at https://github.com/Azure/acs-engine/issues/729. Not sure which is the right locaiton

**Comment by brendandburns** [comment]
This is tracked here https://github.com/Azure/ACS/issues/25

(and should be fixed in the next day or so)

Closing this as a duplicate.
