### ISSUE TITLE
Transactional behavior for template deployments

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#3595]
This issue has been brought up internally a few times and again in issue #3574.

If you have an ARM template deployment (such as VM create) and it fails midway through, several resources may have already been created for you. In many cases, this is what you want--you'd tweak your parameters, redeploy the template and achieve your desired end-state without needing to delete those resources or recreate them.

However, it is certainly reasonable that a user would want to have some kind of transactional behavior for a command where, if the command fails, the user can assume they were in the same state they were before the ran the command.

This would be easy for template-based creates. We know what resources we plan to create. We could include a `--transaction` flag (or something) to signify that if any of the resources fail to deploy, clean up anything that was created.

It might get a little trickier for the generic `group deployment create` command, but still, conceptually, a `--transaction` flag makes sense.

Thoughts?

**Comment by JasonRShaver** [comment]
This behavior is not supported by ARM and we cannot build this into CLI itself.
