### ISSUE TITLE
Azure WebApp config container set should not require creds for ACR repos

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#3597]
When configuring an Azure WebApp to run a container, the registry URI, password, and login/user are required. This pretty cumbersome when working with ACR, since you need to write several commands to fetch the credential values. Instead, the command should accept an image name and (optional) resource ID or name for an ACR repo.

**Comment by yugangw-msft** [comment]
@binderjoe , please clarify, the creds are optional arguments which you are ignore

**Comment by yugangw-msft** [comment]
Please re-activate with clarifications

**Comment by binderjoe** [comment]
To clarify,

1. Create an ACR registry
`az acr create --admin-enabled --name somename --sku Basic`
2. Push an image to the registry
3. Get the URL for the new registry:
```
export DOCKER_REGISTRY=$(az acr show --name somename \
					--query loginServer --output tsv)
```
4. Create a new webapp (linux)
```
az appservice plan create --name linuxappservice --is-linux --sku S1
az webapp create --name someapp --plan linuxappservice
```
4. Configure the webapp to use the container image from the new registry:
```
az webapp config container set --name someapp \
     --docker-custom-image-name \${DOCKER_REGISTRY}/image-name:latest \
     --docker-registry-server-url https://\${DOCKER_REGISTRY}
```
5. Open any needed port(s)
`az webapp config appsettings set --settings PORT=8080 --name someapp`
6. Restart the webapp
`az webapp restart --name someapp`

The app will never come up. Looking into the Kudu logs, the app doesn't start because the image can't be pulled; it needs authentication info to do the pull.

My point here is that it shouldn't be necessary to specify the username and password for the ACR registry when setting the webapp container if they are in the same subscription and I have RBAC to read the credentials.

**Comment by yugangw-msft** [comment]
After talked to @djyou, I am a bit clear now on ACR's creds management. 
Yep, we can improve this flow.

**Comment by peteribbett** [comment]
when using az webapp config container set, for ACR, do the credentials passed have to be the admin credentials? These are the only credentials I can get to work. I tried the login details for an azure user that has ownership role on the Access Policy for the ACR resource but this didn't work

    --docker-registry-server-user <registry_user> 
    --docker-registry-server-password <registry_password>

Do these credentials passed
