### ISSUE TITLE
vm command component: inconsistency caused by putting "vmss", "acs", and "available-set" under 'vm'

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#360]
'vm' is a resource type, not a resource provider (compute is)
As much as node cli has its own inconsistency, it puts "vmss", 'acs' at the same level with 'vm', which is correct because they are all resource types.
azure-cli's current bebavior is not right.

**Comment by JasonRShaver** [comment]
with moving vmss to be a top-level group, we should be ok here.
