### ISSUE TITLE
az webapp log tail accepts a "provider" but there is no way to get the list of valid providers

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#3600]
The log tail command accepts a provider, but as far as I can tell there is no way--through docs, help, or other CLI commands--to get the list of valid providers. It's not helpful to have parameters if there's no way to determine what values it accepts.

**Comment by yugangw-msft** [comment]
> there is no way--through docs, help, or other CLI commands--to get the list of valid providers

The help does call out
`Scope the live traces to certain providers/folders, for example:'application', 'http' for server log, 'kudu/trace'`

**Comment by johanste** [comment]
If the help stats "for example", it implies that the list is not complete. So we should update the help text to state that these are all the valid values (if that is the case) instead of telling the user that these are some examples of what may be used.

**Comment by yugangw-msft** [comment]
There is no fixed and complete list, it comes from
    https://github.com/projectkudu/kudu/wiki/Diagnostic-Log-Stream

**Comment by yugangw-msft** [comment]
Closing per my comment. By default all traces will be shown, hence the `--provider` is optional and won't get into the way. Once you see the traces, using the flag to scope down should be pretty clear.
FYI: for linux, the trace doesn't quite work, which is tracked by #1803

**Comment by binderjoe** [comment]
Thank you for the clarification. The documentation needs to be updated to reflect this behavior. It's very misleading currently.

**Comment by yugangw-msft** [comment]
@binderjoe, what part? About the `--provider` usages help text? Or the Linux web streaming not available?
My argument was the `--provider`'s help is just right.

**Comment by binderjoe** [comment]
The important detail I'd suggest adding is that all logs will be returned if no provider is specified. As an aside, I still don't think we should have commands that take parameters that take values that can't be known or discovered. As @johanste mentions, the help text provides some examples, but it isn't clear if the list is complete. For example, I am not sure how to get the Docker logs.

**Comment by yugangw-msft** [comment]
The help will be updated like the following.
I decided not to error out when invoke the command on a linux web, because webapp team is working on to get it work.
```
(env) D:\sdk\azure-cli>az webapp log tail -h

Command
    az webapp log tail: Start live tracing.
        Not working with Linux web.

Arguments
    --provider         : By default all live traces configured by 'az webapp log config' will be
                         shown, but you can scope to certain providers/folders, e.g. 'application',
                         'http', etc. For details, check out
                         https://github.com/projectkudu/kudu/wiki/Diagnostic-Log-Stream.
    --slot -s          : The name of the slot. Default to the productions slot if not specified.
```
