### ISSUE TITLE
UX for specifying template parameters is very poor.

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#3601]
### Description
When deploying arm templates with parameters, it's necessary to encode the parameter values as JSON documents, which is very cumbersome to do on the command-line, particularly if the parameter values must be retrieved dynamically (e.g., from other CLI commands).

As a thought exercise, consider the experience for deploying a QuickStart template that accepts Azure resource IDs as parameters. (https://raw.githubusercontent.com/Microsoft/openshift-origin/master/azuredeploy.json)

It should be possible to specify template parameters to the deployment create command itself, essentially promoting template parameters to CLI command parameters.

For example,
`az group deployment create --template-uri [some uri] --param1fromtemplate [value] --param2fromtemplate value`

**Comment by yugangw-msft** [comment]
Maybe, we should just expose an arg accepting key-value pairs list.

**Comment by tjprescott** [comment]
@yugangw-msft tag style syntax sounds good to me!  `--parameters param1=val1 param2=val2 ...`

**Comment by mayurid** [comment]
@yugangw-msft : lets do this. 
I am adding this to upcoming sprint for us to pick
