### ISSUE TITLE
[WebApps] Browse command displays a seemingly inert error message

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#3604]
### Description

When running the `az webapp browse` command, the following error message is printed in the terminal:

```
0:56: execution error: "http://<APP_NAME>.azurewebsites.net" doesn’t understand the “open location” message. (-1708)
```

However, the browser is launched and correctly navigated to the web app. Therefore, the error doesn't appear to impact the successful behavior of the command (at least at first glance). Additionally, if I add the `-l` flag, the log tail also seems to work, so the error message doesn't seem to impact that behavior either. 

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: nightly

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: nightly

**OS Version:** What OS and version are you using?  
Answer here: macOS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by yugangw-msft** [comment]
This is OSX sierra specific. Repro'd using `python -m webbrowser -t msn.com`. [Reported](https://eclecticlight.co/2017/05/17/known-bugs-in-macos-sierra-10-12-5-an-incomplete-summary/) as an OS level bug
I will fix this and #3608 by not going through python's webbrowser object
