### ISSUE TITLE
No way to determine if an AppService is actually running/responsive

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#3606]
### Description
There doesn't appear to be any mechanism for determining if a webapp is actually running and responsive to web requests. For example, if you restart the webapp it often takes 1-3 minutes to be responsive (tested with Linux container scenario), but there isn't a way to know for sure that the site is ready short of curl ing the endpoint.

I have tried 
`az webapp show --name somename --query availabilityState`

But it always returns "Normal", even if the site is down.

**Comment by yugangw-msft** [comment]
There is a `state` field you can check.

**Comment by binderjoe** [comment]
I am afraid that the state property does not reflect the functional state of the webapp. To repro, 

1.  start a containerized webapp. 
2.  Note that state==running
3.  In a new terminal, write an infinite loop that detects when the state property changes
```
while true; do
   az webapp show --name [appname] --query "state" | awk '!/Running/'
done
```
3.  Now call az webapp restart --name [appname] in the original terminal.

The state property never changes even though the site is unresponsive for ~1-2 minutes.

**Comment by yugangw-msft** [comment]
Let me contact webapp team for the right mechanism. Likely there is not, then I will consider letting CLI  `curl` till we have a response

**Comment by yugangw-msft** [comment]
Looks like we don't have that kind of support from the service end. For windows, once the Create command returns, the site is ready, so we are good. For linux, use "curl http://<defaultHostName>" is probably the only way to go
So @binderjoe, can you use `curl`? Acceptable?

**Comment by yugangw-msft** [comment]
Please activate if you have a different opinion
