### ISSUE TITLE
[WebApps] [Discussion] Could the runtime list be more "real-time"?

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#3607]
### Description

Node 8 support was [just deployed](https://github.com/Azure/app-service-announcements/issues/5) to Web Apps (on Windows), and I noticed that calling `az webapp list-runtimes` doesn't reflect that fact (`node|7.7` is the latest Node version displayed). Additionally, Node 6.10 has been available in Linux Web Apps for a while, but running `az webapp list-runtimes --linux` displays `node|6.9` as the latest.

It would be ideal if users could rely solely on this command to understand the set of available runtimes, as opposed to needing to keep up with blogs/[Twitter](https://twitter.com/davidebbo/status/870693592557273088)/GitHub/etc. in order to find out that something is available.

Additionally, in the case of Linux runtimes, it's kind of strange that it states that the list is an "offline" copy, and that you can visit `https://aka.ms/linux-stacks` for the full list. Not only does that seem fairly inconvenient, but the list of available runtimes isn't even up-to-date on that page either! So the user would navigate to the page, only to get the exact same list. I sent a [PR](https://github.com/Microsoft/azure-docs/pull/1898) to update that page 3 days ago, and haven't seen much traction, so while we could try to keep the docs up to date, it just feels like having a really realiable `az webapp list-runtimes` command would be a lot nicer.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: nightly

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: nightly

**OS Version:** What OS and version are you using?  
Answer here: macOS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by yugangw-msft** [comment]
For linux the runtime list is well known not accurate which can only be addressed when related API is exposed. @ahmedelnably, could you please accept the PR(https://github.com/Microsoft/azure-docs/pull/1898)?
For windows, let us give a couple of days. If still not showing up, i will contact webapp folks to investigate

**Comment by panchagnula** [comment]
@lostintangent  we updated our back end API. This should now be fixed
