### ISSUE TITLE
az webapp browser opens the wrong browser

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#3608]
### Description
`az webapp browse --name`
Appears to open Firefox and ignore the default system browser on OSX. It should use the default browser.

### `Environment` summary
OSX 10.12

**Comment by yugangw-msft** [comment]
To be clear, we didn't pick Firefox, but python's webbrowser component does that!

**Comment by yugangw-msft** [comment]
This is a python 2.x bug on osx. I can reproduce using `python -m webbrowser -t msn.com`.
