### ISSUE TITLE
az webapp browse error message is cryptic

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#3609]
### Description
`az webapp browse`

Reports the following error when run with a webapp that isn't running. The error should denote either the HTTP response or the website state if it isn't running

`0:51: execution error: "http://somesite.azurewebsites.net" doesn’t understand the “open location” message. (-1708)`
---

**Comment by lostintangent** [comment]
I hit this as well after updating my nightly bits, so I'm not sure if it was a recent regression. It's also tracked via #3604.

**Comment by yugangw-msft** [comment]
dupe
