### ISSUE TITLE
default to --output list, do not output json as default

### ISSUE THREAD

**Issue by gianugo** [Azure/azure-cli#362]
I'm expecting a command line to give me nicely formatted, user readable output. JSON is not such a thing. the command 'az login' provides a JSON dump as a result, it would be much better to have some text mentioning that login was successful and providing a short subscription list.

**Comment by JasonRShaver** [comment]
I believe this will be resolved once we implement an `az configure` command to set your default output format.  In addition, we are implementing a `table` output format to replace our `list` use-cases.

**Comment by tjprescott** [comment]
@JasonRShaver now that `az configure` is in, can this be closed?

**Comment by JasonRShaver** [comment]
List is gone, Table is the new hotness and our default
