### ISSUE TITLE
[Question]Is it able to convert an existed VIP on Cloud Service classic mode to Reserved IP ?

### ISSUE THREAD

**Issue by jackting73** [Azure/azure-cli#3628]
### Description
Is it able to convert an existed VIP on Cloud Service classic mode to Reserved IP ?

---

### Environment summary
1. I realize we can done this by powershell from the article here: https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-reserved-public-ip  
2. But seems no information to indicate if it is possible to achieve by CLI: https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-deploy-static-pip-arm-cli 

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
CLI 2.0

**OS Version:** What OS and version are you using?  
CentOS6.7 and by Azure Cloud Shell

**Comment by tjprescott** [comment]
CLI 2.0 only supports ARM. There is no support for the cloud service classic model. You could try releasing your classic model IP and then creating a static public IP address, which would create an ARM public IP resource with that address.

**Comment by jackting73** [comment]
Hi Travis,

Thanks for your response.
Is it possible to achieve this by CLI 1.0 or other version ? 

Regards,
-Jack

**Comment by JasonRShaver** [comment]
I've asked around and it seems like your best options are to use the Azure PowerShell.  I understand this is not ideal (especially for a Linux user).

```
New-AzureReservedIP –ReservedIPName MyReservedIP –Location "Central US" -ServiceName TestService
```

or use CURL to call the REST API, but I honestly don't know where to look up the REST API for the ASM (non-ARM) endpoints.

**Comment by JasonRShaver** [comment]
Closing this, but if you find yourself blocked, don't be afraid to reach out again!
