### ISSUE TITLE
Template "outputs" does not display output values

### ISSUE THREAD

**Issue by lastcoolnameleft** [Azure/azure-cli#3632]
### Description
**I'd expect foo:bar to be in the outputs**

➜  azure az --version
azure-cli (2.0.7)
➜  azure cat /tmp/output.json
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
  },
  "resources": [
  ],
  "outputs": {
      "foo": {
          "type": "string",
          "value": "bar"
      }
  }
}
➜  azure az group deployment validate --template-file output.json -g sandbox-rhel
{
  "error": null,
  "properties": {
    "correlationId": "6ea78c89-9234-4a89-9c5b-2a125f8f4214",
    "debugSetting": null,
    "dependencies": [],
    "mode": "Incremental",
    "outputs": null,
    "parameters": {},
    "parametersLink": null,
    "providers": [],
    "provisioningState": "Succeeded",
    "template": null,
    "templateLink": null,
    "timestamp": "2017-06-07T21:51:54.493935+00:00"
  }
}

If you run the same command via PS, you get:
PS Microsoft.PowerShell.Core\FileSystem::\\Mac\Home\tmp> New-AzureRmResourceGroupDeployment -Name ExampleDeployment -ResourceGroupName sandbox  -TemplateFile .\output.json

DeploymentName          : ExampleDeployment
ResourceGroupName       : sandbox
ProvisioningState       : Succeeded
Timestamp               : 6/7/17 10:02:54 PM
Mode                    : Incremental
TemplateLink            :
Parameters              :
Outputs                 :
                          Name             Type                       Value
                          ===============  =========================  ==========
                          foo              String                     bar

DeploymentDebugLogLevel :

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
curl -L https://aka.ms/InstallAzureCli | bash

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
➜  azure az --version
azure-cli (2.0.7)

acr (2.0.5)
acs (2.0.7)
appservice (0.1.7)
batch (3.0.0)
billing (0.1.0)
cdn (0.0.3)
cloud (2.0.3)
cognitiveservices (0.1.3)
command-modules-nspkg (2.0.0)
component (2.0.5)
configure (2.0.7)
consumption (0.1.0)
core (2.0.7)
cosmosdb (0.1.7)
dla (0.0.7)
dls (0.0.7)
feedback (2.0.3)
find (0.2.3)
interactive (0.3.3)
iot (0.1.6)
keyvault (2.0.5)
lab (0.0.5)
monitor (0.0.5)
network (2.0.7)
nspkg (3.0.0)
profile (2.0.5)
rdbms (0.0.2)
redis (0.2.4)
resource (2.0.7)
role (2.0.5)
sf (1.0.2)
sql (2.0.4)
storage (2.0.7)
vm (2.0.7)

Python (Darwin) 2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]

Python location '/Users/thfalgou/bin/azure-cli/bin/python'

**OS Version:** What OS and version are you using?  
OSX 10.12.5

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
zsh

**Comment by yugangw-msft** [comment]
Sorry for such a late response, but it is true `validate` doesn't produce the output. Likely the reason is it doesn't know 100% that the resource can always be created, but using `az group deployment create` will produce the output once it gets through, and that is what `New-AzureRmResourceGroupDeployment` does.
Based on that, I am closing this.
