### ISSUE TITLE
Resource Group 'xxxx' not found for `az storage account list -g xxxx`

### ISSUE THREAD

**Issue by puneetloya** [Azure/azure-cli#3651]
### Description
Am struggling to find the resource group when I need to list resource, storage accounts for a resource group. Able to get all the details for the default resource group set in the .azure/config file. But its not listing other resource groups

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

**CLI Version: '2.0.7'

**OS Version: 'MacOS Yosmemite'

**Comment by tjprescott** [comment]
Are you wanting to list all storage accounts in your subscription?  If so, it is just `az storage account list`.

**Comment by derekbekoe** [comment]
If a default resource group is set, that's the resource group that will be used for `az storage account list`. If you want to list all storage accounts again, remove the default (e.g. `az configure --defaults group=''`)

**Comment by puneetloya** [comment]
my mistake. Thanks for the prompt reply.

**Comment by milindchavan12** [comment]
In fact, this is not the issue with showing the list of the storage account, but with other az artifacts. I have come across the same for `az acr list -o table`, but then removing the default resource group by `az configure --defaults group=''` works absolutely fine.
