### ISSUE TITLE
Command 'az: not found' in Docker latest image 

### ISSUE THREAD

**Issue by maticko** [Azure/azure-cli#3657]
### Description
**Outline the issue here:**
Latest published docker image with az preinstalled is not working. Az is not in path.

[link to build](https://hub.docker.com/r/azuresdk/azure-cli-python/builds/bplsgrcvv8nfktfpuadh3xz/)
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: Docker

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: None (az command doesn't work)

**OS Version:** What OS and version are you using?  
Answer here: Docker

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Bash and Sh in Docker

**Comment by tirithen** [comment]
Same here, this docker image seem totally unusable? The point would have been to have the az application inside but there is no such thing. What is then the purpose of this Docker image?

+1

**Comment by vishalraina** [comment]
+1 not able to work with this docker image.

**Comment by derekbekoe** [comment]
Hmm thanks for the reports. Investigating...

**Comment by derekbekoe** [comment]
As a workaround, you can use `azuresdk/azure-cli-python:0.2.10`.

`latest` is an automated build from master branch so looks like a recent check in broke `latest`.

**Comment by derekbekoe** [comment]
Related to https://github.com/pyca/pynacl/issues/298

**Comment by derekbekoe** [comment]
@maticko, @tirithen, @vishalraina thanks for the reports. A PR is out. Once merged, `latest` should be back in working order.

**Comment by vishalraina** [comment]
👍

**Comment by derekbekoe** [comment]
Verified that it's working again.
