### ISSUE TITLE
webapp: 'DOCKER_REGISTRY_SERVER_PASSWORD' should be write only

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#3660]
For now, webapp service just treats it as a regular app-setting and exposes it on any read operation. This is not ideal due to security concerns. CLI makes workaround through #3656 to hide it. So opening this tracking issue so we will remove the workaround when the service side makes the improvement.

**Comment by yugangw-msft** [comment]
Move to the sprint 18, as likely the service side will have changes deployed this week to address this.

**Comment by yugangw-msft** [comment]
I will check this out again.

**Comment by yugangw-msft** [comment]
still there

**Comment by yugangw-msft** [comment]
still there

**Comment by panchagnula** [comment]
The API call here is a POST call & if a user doesn't have write RBAC access for the App  or Config level the API fails.  No GETs work on this API. In general we have an effort going on move to using KeyValut. Closing this.
