### ISSUE TITLE
servicefabric application upload partial file only

### ISSUE THREAD

**Issue by cy33hc** [Azure/azure-cli#3666]
### Description
I have a Java application deployed to servicefabric as guest executable. When we execute "az sf application upload --path <path_to_pkg>, only part of the file is uploaded, causing the JAR to be corrupted. As you can see from the screenshot, my JAR file is about 57MB. The az cli reports only 103855 bytes uploaded. And also on the windows Image service path it shows only 98KB.
![azure_1](https://user-images.githubusercontent.com/4947747/27060852-a7619742-4f94-11e7-92d5-eb4223109b8e.png)
![azure_2](https://user-images.githubusercontent.com/4947747/27060856-aa83ea24-4f94-11e7-82aa-6b976b8a9a33.png)
![azure_3](https://user-images.githubusercontent.com/4947747/27060859-ade26588-4f94-11e7-943f-d546be4c68e8.png)

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Installed with pip3 for python3

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
azure-cli (2.0.7)

acr (2.0.5)
acs (2.0.7)
appservice (0.1.7)
batch (3.0.0)
billing (0.1.0)
cdn (0.0.3)
cloud (2.0.3)
cognitiveservices (0.1.3)
command-modules-nspkg (2.0.0)
component (2.0.5)
configure (2.0.7)
consumption (0.1.0)
core (2.0.7)
cosmosdb (0.1.7)
dla (0.0.7)
dls (0.0.7)
feedback (2.0.3)
find (0.2.3)
interactive (0.3.3)
iot (0.1.6)
keyvault (2.0.5)
lab (0.0.5)
monitor (0.0.5)
network (2.0.7)
nspkg (3.0.0)
profile (2.0.5)
rdbms (0.0.2)
redis (0.2.4)
resource (2.0.7)
role (2.0.5)
sf (1.0.2)
sql (2.0.4)
storage (2.0.7)
vm (2.0.7)

Python (Linux) 3.4.5 (default, Nov  9 2016, 16:24:59) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

**OS Version:** What OS and version are you using?  
Centos 7.3

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
bash

**Comment by VipulM-MSFT** [comment]
What version of Service Fabric cluster are you using? Is this is a consistent repro?

**Comment by cy33hc** [comment]
5.6.210.9494

Yes. It is consistently reproducible with cli 2.0.

Using cli 1.0, the package copy succeeds.

**Comment by jeffreychenmsft** [comment]
We have confirmed the bug, and working on the bug fix now. Thanks.
