### ISSUE TITLE
Cant add a component

### ISSUE THREAD

**Issue by ascobie** [Azure/azure-cli#3667]
### Description
I had an old version of the CLI installed and i wanted to update the Batch component from: 0.1.1b5
I tried "az component update" which failed with: 

AttributeError: '_NamespacePath' object has no attribute 'sort' 
pip.basecommand : Command "python setup.py egg_info" failed with error code 1 in C:\Users\ascobie\AppData\Local\Temp\pip-build-eotc0v1z\azure-datalake-store\ 

Updated to urllib3-1.21.1 and tried again with the same error. 

Uninstalled and tried to re-install and got the same error.

Gave up and installed the MSI from: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli#windows

Now i can't add a component: "az component update --add batch-extensions --allow-third-party"

> az component and subcommands are not available with the current Azure CLI installation.
> If installed with apt-get, please use 'apt-get update' to update this installation.
> If installed with Docker, please use 'docker pull' to update this installation.
> If installed with Windows MSI, download the new MSI to update this installation.
> Components cannot be updated.

I need this extension as i purely want the CLI for No Code Jobs testing. 

The user experience for updating the CLI is shocking!

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip install

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.1

**OS Version:** What OS and version are you using?  
Answer here: Win 10, build 14393

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: CMD

**Comment by ascobie** [comment]
Trying to update the CLI completely destroyed my PIP install. 

1. Uninstalled Python and manually deleted the site-packages and old pip directories
2. Re-installed Python after a restart 
3. Ran: "pip install azure-cli"
4. Ran: "az component update --add batch-extensions --allow-third-party"

It now works again.

**Comment by troydai** [comment]
@ascobie thank you for providing the feedback. It will definitely help us to improve our acquisition scenarios. 

A few tips here: to isolate an application's dependencies, most of Python users use [virtualenv](http://docs.python-guide.org/en/latest/dev/virtualenvs/). Without the virtualenv, essentially the dependencies of all your Python programs are mixed globally. Therefore the recommended installation approaches on Windows are 1. MSI and 2. run `curl -L https://aka.ms/InstallAzureCli | bash` in 
Windows Linux subsystem. (See: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli).

**Comment by itowlson** [comment]
Some users found a workaround by running the MSI followed by `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe -m pip install azure-cli-batch-extensions`.  However another user reports that this broke his entire CLI with the following error:

'Profile' object has no attribute 'get_expanded_subscription_info'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\application.py", line 211, in execute
    result = expanded_arg.func(params)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 351, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 522, in _execute_command
    client = client_factory(kwargs) if client_factory else None
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\batch_extensions\_client_factory.py", line 13, in batch_extensions_client
    client = batch.BatchExtensionsClient(base_url=account_endpoint)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\batch_extensions\batch_extensions_client.py", line 60, in __init__
    credentials, mgmt_credentials, subscription_id)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\batch_extensions\batch_extensions_client.py", line 116, in _configure_credentials
    profile, subscription = self._get_cli_profile(profile, subscription_id)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\batch_extensions\batch_extensions_client.py", line 103, in _get_cli_profile
    subscription = profile.get_expanded_subscription_info(subscription_id=subscription_id)
AttributeError: 'Profile' object has no attribute 'get_expanded_subscription_info'

How do we progress this?  This is an important customer-facing Batch feature and it's a horrific experience for our customers and seems to be totally out of our hands.  Is there any update on #3619?

**Comment by derekbekoe** [comment]
@itowlson We're looking at what's available in the Python ecosystem to support this scenario (and if we need to roll our own).

The issue your customer ran into is exactly *one of the reasons* why we've disabled the 'az component' commands in the MSI. I suspect that `azure-cli-batch-extensions` had dependencies that didn't match with the version of the MSI the customer had installed.
