### ISSUE TITLE
Install documentation precludes adding extensions

### ISSUE THREAD

**Issue by itowlson** [Azure/azure-cli#3668]
The install methods listed on https://docs.microsoft.com/en-us/cli/azure/install-azure-cli say "az component isn't supported" and describe alternate methods of upgrading to the latest CLI.  That's great for the built-in modules but gives customers no way of installing extensions such as the Batch Extensions (https://github.com/Azure/azure-batch-cli-extensions).

Please could you provide documentation on how to install the CLI in such a way that users can run `az component update` to install extensions?  Thanks!

(I thought `pip install azure-cli` used to work but now it crashes with an obscure error message.)

**Comment by troydai** [comment]
@itowlson, for now, install the az using our bash script should provide an installation enable `component` command. Can you provide the obscure error you hit during your `pip install`?

**Comment by itowlson** [comment]
By the bash script do you mean `curl -L https://aka.ms/InstallAzureCli | bash`?  The docs page says "When you install with InstallAzureCli, `az component update` isn't supported."

Regarding the pip install errors, @ascobie has raised an issue with the details (https://github.com/Azure/azure-cli/issues/3667) as he had much better notes than I did; I'm seeking documentation for an install mechanism that allows customers to add extensions.  If that mechanism is `pip install` then can we add that to the docs page please?

**Comment by troydai** [comment]
@itowlson thank you for the feedback. We're currently working on improving the experience of acquisition and extension. Your feedback is valuable to us.
