### ISSUE TITLE
Failed to create large number of machines using azure-cli

### ISSUE THREAD

**Issue by liorbiu** [Azure/azure-cli#3669]
I'm trying to deploy large number of machines using the azure cli (100 machines). I'm using the following basic bash script in order to create the machines:
```
number_of_servers=100
for i in `seq 1 1 ${number_of_servers}`;
do
az vm create --resource-group Automationsystem --name VM${i} --image LibscapiBaseImage --admin-username azureuser --size Standard_F4S --ssh-key-value ~/.ssh/id_rsa_azure.pub &
done
```
When I'm running it I'm receiving the following error for some of the machines (part of them are created successfully):
`The template deployment 'vm_deploy_DE2BVJyVpgy1UXinnyNUAp3BEYSCf6b0' is not valid according to the validation procedure. The tracking id is '54fd9b3b-6300-47cd-82a3-65332f2f28bd'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details`.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: **interactive script**

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: **azure-cli (2.0.7)**

**OS Version:** What OS and version are you using?  
Answer here: **Ubuntu 16.04 LTS**

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: **bash**

**Comment by tjprescott** [comment]
If you look in the portal, you should be able to see the failed deployments, along with why they failed.  Does this reveal any additional information?

**Comment by tjprescott** [comment]
Is "LibscapiBaseImage" a managed image?

**Comment by yugangw-msft** [comment]
Maybe a quota exceeding error like #2792? He is creating 100 vms, by default a subscription allows 100.
Either way, I think we need to improve the create command so to pull our the inner error from the deployment

**Comment by liorbiu** [comment]
@tjprescott my images are linux machines. When I'm looking at the portal I'm not see the failed machines at all.
@yugangw-msft the error occured even when I'm creating 50 machines so I don't think it's quanta problem.

**Comment by tjprescott** [comment]
@yugangw-msft I believe you are correct. When I ran this, I got the same thing. After creating 20 VMs, I kept getting the error @liorbiu describes. Looking at the failed deployments in the portal, the error is:

```
Operation results in exceeding quota limits of Core. Maximum allowed: 100, Current in use: 97, Additional requested: 4. (Code: OperationNotAllowed)
```

You quota isn't 100 VMs--it is 100 total cores. Since you are using Standard_F4S, each VM requires 4 cores against your quota. Thus, your practical limit is 25 VMs.

However, you can open a support ticket within the portal and request your quota be increased.

Since the issue regarding the error message is already tracked by #2792, I'm going to go ahead and close this.

**Comment by liorbiu** [comment]
@tjprescott I increased mu cores quanta to 2000 using the portal.
I tried to create 12 machines and still not all the machines created.
I didn't get any output besides to visit this [address](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-deploy).
After I ran the script not all the machines created (image attached).
![azurescreenshot](https://user-images.githubusercontent.com/17683901/27176826-cc254ed6-51cc-11e7-8448-3a95e7e02243.png)

**Comment by tjprescott** [comment]
@liorbiu when PR #3726 is merged, you'll be able to see what the inner error is. However, you can see that now within the portal by navigating to your resource group blade and then selecting the "Deployments" section.  It will show your successful and failed deployments and allow you to get the error details.
