### ISSUE TITLE
Creating a KeyVault in Cloud Console fails with illegible error

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#3714]
### Description
**Outline the issue here:**
When creating a KeyVault inside the cloud console, the CLI command dies with the below error.

To repro:
```
az group create --name myResourceGroup --location eastus
az keyvault create --resource-group myResourceGroup --name myKeyVault --enabled-for-deployment
```

```
'isMRRT'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/lib/python3.5/dist-packages/azure/cli/core/application.py", line 210, in exe
cute
    result = expanded_arg.func(params)
  File "/usr/local/lib/python3.5/dist-packages/azure/cli/core/commands/__init__.py", line 289,
in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/azure/cli/core/commands/__init__.py", line 488,
in _execute_command
    reraise(*sys.exc_info())
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/azure/cli/core/commands/__init__.py", line 465,
....
    return token_func(self)
  File "/usr/local/lib/python3.5/dist-packages/adal/authentication_context.py", line 124, in to
ken_func
    return token_request.get_token_from_cache_with_refresh(user_id)
  File "/usr/local/lib/python3.5/dist-packages/adal/token_request.py", line 350, in get_token_f
rom_cache_with_refresh
    return self._find_token_from_cache()
  File "/usr/local/lib/python3.5/dist-packages/adal/token_request.py", line 128, in _find_token
_from_cache
    return self._cache_driver.find(cache_query)
  File "/usr/local/lib/python3.5/dist-packages/adal/cache_driver.py", line 179, in find
    entry, is_resource_tenant_specific = self._load_single_entry_from_cache(query)
  File "/usr/local/lib/python3.5/dist-packages/adal/cache_driver.py", line 112, in _load_single
_entry_from_cache
    token = next(mrrt_tokens, None)
  File "/usr/local/lib/python3.5/dist-packages/adal/cache_driver.py", line 111, in <genexpr>
    mrrt_tokens = (x for x in potential_entries if x[TokenResponseFields.IS_MRRT])
KeyError: 'isMRRT'
```
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
Cloud Shell

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
CLI Version 2.0.7
KeyVault Pkg: 2.0.5

**OS Version:** What OS and version are you using?  
Answer here:

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

**Comment by troydai** [comment]
@tjprescott

**Comment by tjprescott** [comment]
From the stack trace, this looks like an ADAL issue.

**Comment by derekbekoe** [comment]
The stack trace looks similar to https://github.com/Azure/azure-cli/issues/3641

**Comment by tjprescott** [comment]
@yugangw-msft what do you think?

**Comment by yugangw-msft** [comment]
@jluk, @yangl900, please take a look. It appears CLI was not yet given the keyvault token. How soon cloud console pass on the vault tokens to cli? 
This issue will not be addressed through #3641. W/o refresh token, we have to have the token with exactly the same relying party uri.
@binderjoe, for now, wait for a minute or so and retry.

**Comment by jluk** [comment]
@binderjoe or @yugangw-msft can you still repro this issue, if so can you provide time details of when it was reproduced? We have additional logs now that can help debug this, however we are unable to repro.

**Comment by mmacy** [comment]
@jluk I don't get the stack trace, but I do get this message when attempting to create a key vault in the Cloud Shell:

```
marsh@Azure:~$ az keyvault create -n $KEYVAULT_NAME --enabled-for-template-deployment -g myResourceGroup
Could not retrieve token from local cache, please run 'az login'.
```

Was running through [Mounting an Azure file share with Azure Container Instances](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-mounting-azure-files-volume#store-storage-account-access-details-with-azure-key-vault) when I hit this.

**Comment by jluk** [comment]
@mmacy approx how long was cloud shell running before this cmd was invoked? it's possible calls are made before cloud shell can auth for keyvault.

**Comment by mmacy** [comment]
@jluk Hmm... 5 minutes?

**Comment by jluk** [comment]
I've been hitting some odd auth errors as well for unrelated CLI tasks like #4332, lets pick this up with @yugangw-msft when he returns

**Comment by yugangw-msft** [comment]
This has been fixed for a while that cloud shell has made token available for KV, ARM, Graph, Batch and Storage at least.
