### ISSUE TITLE
How can the user tell which Azure Batch account they are logged into?

### ISSUE THREAD

**Issue by itowlson** [Azure/azure-cli#3715]
### Description

To use Azure Batch CLI commands, you need to log into a Batch account using `az batch account login`.  I can't find a way to determine if the user is currently logged into a Batch account, or if so which account they are logged into.  Is there a command that provides this information?

---

### Environment summary

**Install Method:** pip

**CLI Version:** CLI 2.07, Batch 3.0.0

**OS Version:** Windows 10

**Shell Type:** PowerShell

**Comment by troydai** [comment]
@annatisch @xingwu1

**Comment by tjprescott** [comment]
ping @annatisch @xingwu1
