### ISSUE TITLE
Automation: Improve the package release process

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#3727]
Here are the notes I took during the past package release practice.

1. The versions are hardcoded in the source code. Therefore, in order to rev the packages version code changes were deliberately made to `setup.py` and `__init__.py`. It worth consider taking the value out of the source code and leverage environment variable or other sources to define version.
2. It requires too many release comments and pull requests. Make the bot to release multiple packages in one commit.
3. Can we rely on tag instead of a symbolic commit?
4. The bot relies on pull request merge event for trigger mechanism. It is not ideal for automation. It should rely on git merge event.
5. The bot release failed when pull requests were merged "too fast".
6. Command modules' versions are not aligned.
7. There isn't strong verification mechanism after package or bundle is released.
8. Package scripts are python 2.7 only.
9. The apt build can only be done on Ubuntu 14.04

**Comment by troydai** [comment]
@derekbekoe

**Comment by derekbekoe** [comment]
This PR, https://github.com/Azure/azure-cli/pull/3915, improves on this but still not fully automated with 'one click' yet.

**Comment by derekbekoe** [comment]
This has been done.
