### ISSUE TITLE
Parameters file values not being read during deployment create

### ISSUE THREAD

**Issue by jayden-at-arista** [Azure/azure-cli#3729]
### Description
When using `az group deployment create` with the newest version of the Azure CLI it no longer respects the `--parameters @<file>` contents and prompts me to type out each value in the command line. 

Tested same template/parameters JSON files on another machine with an older version of Azure CLI without issue.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: Linux install using curl -L <url> | bash

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

azure-cli (2.0.8)

acr (2.0.6)
acs (2.0.8)
appservice (0.1.8)
batch (3.0.1)
billing (0.1.1)
cdn (0.0.4)
cloud (2.0.4)
cognitiveservices (0.1.4)
command-modules-nspkg (2.0.0)
component (2.0.5)
configure (2.0.8)
consumption (0.1.1)
core (2.0.9)
cosmosdb (0.1.8)
dla (0.0.8)
dls (0.0.8)
feedback (2.0.4)
find (0.2.4)
interactive (0.3.4)
iot (0.1.7)
keyvault (2.0.6)
lab (0.0.6)
monitor (0.0.6)
network (2.0.8)
nspkg (3.0.0)
profile (2.0.6)
rdbms (0.0.3)
redis (0.2.5)
resource (2.0.8)
role (2.0.6)
sf (1.0.3)
sql (2.0.5)
storage (2.0.8)
vm (2.0.8)

Python (Linux) 2.7.5 (default, Feb 10 2017, 17:36:50)
[GCC 4.9.2 20141101 (Red Hat 4.9.2-1)]

Python location '/home/jayden/lib/azure-cli/bin/python'

**OS Version:** What OS and version are you using?  
Answer here: Modified Fedora 18

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by tjprescott** [comment]
Is any kind of error displayed?  I've tested this on Windows and Linux and verified the behavior is working correctly.

**Comment by sagalovsky** [comment]
Our script stopped working after the latest "azure-cli" release as well. I suspect that v2.0.8 introduced a backward-incompatible change to the ```--parameters``` argument:
- using 2.0.7 we called ```az group deployment create ... --parameters @/tmp/myparamfile```
- after 2.0.8 we had to change it to ```az group deployment create ... --parameters /tmp/myparamfile``` (notice the lack of ```@``` symbol)

The CLI hint doesn't really explain the difference between a "parameters file" and "raw JSON ... loaded using ```@<file path>``` syntax" (I guess the former should conform to ```https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#``` and the latter is just a "flat" dict), so I'm not sure if it was a deliberate change to make the CLI more consistent.

**Comment by tjprescott** [comment]
Thanks for the clarification @sagalovsky. With the change to the parameters argument, we did want to be able to work with a properly formatted parameters file, but also wanted to preserve the previous behavior to prevent a breaking change. I'll take a look at this.

**Comment by jayden-at-arista** [comment]
@sagalovsky Yes, this is exactly it. I removed the `@` and it now works with the new version of CLI...but some of our development environment uses the old version of the CLI which I confirmed does not work with the `@` removed, so we have to have two versions of our script now.

v2.0.8 is a breaking change in terms of the API of the `--parameters` argument in the `az group deployment create` command, and is not fully backwards compatible.

**Comment by tjprescott** [comment]
@jayden-at-arista @sagalovsky 
Could you please run the command using the @ notation along with `--debug` and send the trace to me at "trpresco at Microsoft dot com", along with your OS type/version and your shell. I'm unable to reproduce this on the OS/shells I have tried so far.

**Comment by jayden-at-arista** [comment]
Email sent. Just to confirm you're trying my exact configuration:

- You have a properly formatted JSON parameters file (including "$schema", "contentVersion", and "parameters") 
- You're passing in that filename to `--parameters @file.json`, and it's properly taking the parameter values from that parameters json file (not prompting you to enter them on commandline when deploying, as is happening for me)
- You're using v2.0.8

**Comment by andrewstevenson** [comment]
Stopped working for me if a parameter had `=` in the string .i.e public key data. Worked previously.

**Comment by tjprescott** [comment]
Thank you @andrewstevenson! Now I can reproduce this and work on the fix.

**Comment by sagarkul** [comment]
read parameter values and store in variable
`parameters=$(curl --silent "$parametersUri?$token&$(date +%s)" | jq .parameters )
`
use variable at deployment time. don't forget use double quotes ("$parameters").

`az group deployment create --name $job --resource-group $resourceGroupName --template-uri $templateUri?$token --parameters "$parameters" --output tsv --rollback-on-error)`
