### ISSUE TITLE
Can I retrieve the OAUTH 2.0 Authorization endpoint from the Azure CLI ?

### ISSUE THREAD

**Issue by yagupta** [Azure/azure-cli#3733]
### Description
Not an Issue, but really a gap : I need to retrieve the OAUTH 2.0 authorization endpoint from the Azure CLI and could not find how to do this. 

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.7

**OS Version:** What OS and version are you using?  
Answer here: Windows 10, Ubuntu, MacOS (use this across platforms

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Mulitple

**Comment by yugangw-msft** [comment]
1. run `az account show --query "tenantId"` 
2. open the link in browse:  `https://login.windows.net/<tenant id you got>/.well-known/openid-configuration`
