### ISSUE TITLE
Property to set version no longer works without extra quotes

### ISSUE THREAD

**Issue by nneul** [Azure/azure-cli#3739]
### Description

Previously used this snippet:

```
entity=${entity_prefix}-cust-gw
id=$(az network application-gateway show --resource-group $res_group --name ${entity} | jq -r '.id')
az resource update --verbose \
    --id $id \
    --set properties.webApplicationFirewallConfiguration.enabled=true \
    --set properties.webApplicationFirewallConfiguration.firewallMode=$waf_mode_customer \
    --set properties.webApplicationFirewallConfiguration.ruleSetType=OWASP \
    --set properties.webApplicationFirewallConfiguration.ruleSetVersion=3.0 \
    --set properties.webApplicationFirewallConfiguration.disabledRuleGroups=@waf-rules-customer.json &

```

Sometime recently (past few weeks/month) this stopped working, and I now have to use:

`    --set properties.webApplicationFirewallConfiguration.ruleSetVersion="'3.0'" \
`
(note the hard embedded quotes) or else I get this error:

`RuleSetVersion '3' is unsupported for specified RuleSetType 'OWASP' for Application Gateway Firewall in context 'properties.webApplicationFirewallConfiguration'.
`

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: Nightly snapshot - updated to latest before reporting.

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
azure-cli (2.0.8+1.dev20170614)

**OS Version:** What OS and version are you using?  
Answer here: ub16.04lts x64

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
bash

**Comment by tjprescott** [comment]
This likely occurs because ruleSetVersion is a string and the way you were specifying it likely resulted in it being interpreted as an int.

However, is there a reason you aren't just using the `az network application-gateway waf-config set` command?

**Comment by nneul** [comment]
How do you set the ruleset version and/or enabled rules with waf-config set? If there is a better way to do the above, I'm open to it.

**Comment by tjprescott** [comment]
```
Command
    az network application-gateway waf-config set: Update the firewall configuration of a web
    application.

Arguments
    --enabled   [Required]: Specify whether the application firewall is enabled.  Allowed values:
                            false, true.
    --disabled-rule-groups: Space separated list of rule groups to disable. This disables the entire
                            group. To disable specifc rules, use '--disabled-rule-ids'.  Values
                            from: az application-gateway waf-config list-rule-sets.
    --disabled-rules      : Space separated list of rule IDs to disable.  Values from: az
                            application-gateway waf-config list-rule-sets.
    --firewall-mode       : Web application firewall mode.  Allowed values: Detection, Prevention.
                            Default: Detection.
    --no-wait             : Do not wait for the long running operation to finish.
    --rule-set-type       : Rule set type.  Default: OWASP.  Values from: az application-gateway
                            waf-config list-rule-sets.
    --rule-set-version    : Rule set version.  Values from: az application-gateway waf-config list-
                            rule-sets.
```
You would set the rule set type and version and then any disabled rules (or rule groups)

**Comment by nneul** [comment]
Ah, multiple terminals, and not all of them have the latest az version so didn't see the new options in the one I mistakenly checked with. You can close this if desired - above is clearly a better solution. :)
