### ISSUE TITLE
Creating a Native App from Azure CLI

### ISSUE THREAD

**Issue by yagupta** [Azure/azure-cli#3742]
### Description
How do I create a Native App from Azure CLI v2.0 ? If I try to follow instructions in 
````az ad app create -h````
I believe I can only create a WebApp. 

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
2.0.7

**OS Version:** What OS and version are you using?  
Answer here:
Windows 10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
cmd.exe

**Comment by tjprescott** [comment]
What do you mean by a native app?

**Comment by yagupta** [comment]
Native App is defined as a type of an App in Azure Portal, see more here : https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-integrating-applications

I can describe our use case, if that is helpful. I know I can create this from the UX, but doing things from the Azure CLI is much easier and preferable.

**Comment by tjprescott** [comment]
@yugangw-msft for comment

**Comment by yugangw-msft** [comment]
All commands under `az ad` are there to support RBAC system. Native app is not supported because it plays no roles in the RBAC which requires confidential clients with their own credentials. At current point, we have no intention to cover the whole AAD area.
I will close on this issue. For anyone who come across this issue, please vote up if you need such support as well

**Comment by ams0** [comment]
Please provide a way to use CLI to create Native and WebAPI application, as we need those for Kubernetes RBAC support: https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/aad.md . Now the process involves using the portal, we would like to have the process automated via CLI.

**Comment by yugangw-msft** [comment]
I will add the support
