### ISSUE TITLE
Add cloud-shell and interactive-mode to Feedback 

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#3752]
[ ] Move `az feedback` telemetry store to new AI account
[ ] Add custom dimension fields for "IsCloudShell", "IsInteractiveMode", "DefaultOutput", "HashedMacAddress" and "InstallationId"
[ ] Change `az feedback` to accept an "empty" NPS value, and if provided, error out with message "If you change your mind and want to provide us feedback, we'll still be here!"
[ ] When a customer provides feedback and gives an email address, can we save that in the profile and prepopulate it?  Or maybe default to their `az account show` login?

In addition, I think we should move to a three question model (ask pro and con) as it *seems* lots of folks are using 0 just to exit the command which adds lots of noise to our numbers.

```
We appreciate your feedback!  This survey is only three questions and should take less than a minute"
"How likely is it you would recommend our Azure CLI to a friend or colleague? [0 to 10]: 
"What can we improve on?"
"What do we do really well?"
"Do you want to provide an email we could follow up with?"
```

**Comment by yugangw-msft** [comment]
we can live w/o it
