### ISSUE TITLE
Max agent pool error provides wrong number for "az acs scale" 

### ISSUE THREAD

**Issue by seanknox** [Azure/azure-cli#3759]
### Description
**Outline the issue here:**
Try scaling an ACS cluster above 100 nodes:
```
$ az acs scale -n $RESOURCE_GROUP --new-agent-count 500 -g $RESOURCE_GROUP
Parameter 'ContainerServiceAgentPoolProfile.count' must be less than 100.
```

The error says the agent count must be less than 100, but it works:
```
$ az acs scale -n $RESOURCE_GROUP --new-agent-count 100 -g $RESOURCE_GROUP
 / Running ..
```
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: `$ curl -L https://aka.ms/InstallAzureCli | bash`

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: `azure-cli (2.0.8)`

**OS Version:** What OS and version are you using?  
Answer here: MacOS Sierra 10.12.4

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by brendandburns** [comment]
This is in the apiserver, not the client, closing here in favor of https://github.com/Azure/ACS/issues/33
