### ISSUE TITLE
Incorrect usage text after mis-typed command

### ISSUE THREAD

**Issue by mboersma** [Azure/azure-cli#3760]
### Description

I blundered into a command, hoping it would prompt me for the correct flags. But instead it suggested something illegal:
```shell
$ az group delete mbdev
az: error: unrecognized arguments: mbdev
usage: az [-h] [--output {json,tsv,table,jsonc}] [--verbose] [--debug]
          [--query JMESPATH]
          {group} ...
```
This disagrees with the correct command documentation:
```shell
$ az group delete
az group delete: error: argument --name/-n is required
usage: az group delete [-h] [--output {json,tsv,table,jsonc}] [--verbose]
                       [--debug] [--query JMESPATH] --name RESOURCE_GROUP_NAME
                       [--yes] [--no-wait]
```

Basically the `--name` parameter is required but the first usage message suggests it could be a positional argument, which is wrong.
```

**Outline the issue here:**
Usage text needs to be updated for this case. I'll try to PR that.

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
The curl | bash script, as recommended.

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
2.0.8

**OS Version:** What OS and version are you using?  
macOS sierra.

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
`bash` 3.2.57

**Comment by tjprescott** [comment]
This would involve some core changes to the CLI command parsing logic. The reason is because the CLI assumes everything you submitted is part of the command name since the CLI doesn't support positional parameters.  The current logic essentially splits the command line into the "command part" which is everything to the left of the first - character, and the "arguments part", which is everything to the right of and including the first - character.

**Comment by yugangw-msft** [comment]
//CC: @chewong, a bit different from #3994, though related as both in regarding to a better error.

**Comment by derekbekoe** [comment]
I believe this is now fixed. In version 2.0.32, I see the below. In 2.0.8 it was the error that was first reported.

<img width="802" alt="screen shot 2018-04-19 at 3 47 35 pm" src="https://user-images.githubusercontent.com/16448634/39022143-0221d608-43e9-11e8-87ff-a00225ea1bfb.png">
