### ISSUE TITLE
az interactive prompt for `storage XXX generate-sas` misses the option `--account-name` when `-n` parameter is used

### ISSUE THREAD

**Issue by nth-block** [Azure/azure-cli#3764]
### Description
While trying to create a SAS  using CLI 2.0  in the interactive mode, the intellisense prompts do not have the `--account-name` in the listing if the `-n` parameter is defined. However, if the parameter is not defined, then the intellisense has the `--account-name` parameter showing up. This happens in all the **storage XXX generate-sas** context. Screenshots below are for blobs, containers and tables. (see screenshots at end).

However, if the `--name` switch is used, the issue does not seem to occur. (Next screenshot for the `--name` switch only)
![image](https://user-images.githubusercontent.com/20584285/27276240-2f53842c-54f8-11e7-9f0b-1749d460e301.png)

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: Azure Cloud Shell

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
```
azure-cli (2.0.7)

acr (2.0.5)
acs (2.0.7)
appservice (0.1.7)
batch (3.0.0)
billing (0.1.0)
cdn (0.0.3)
cloud (2.0.3)
cognitiveservices (0.1.3)
command-modules-nspkg (2.0.0)
component (2.0.5)
configure (2.0.7)
consumption (0.1.0)
core (2.0.7)
cosmosdb (0.1.7)
dla (0.0.7)
dls (0.0.7)
feedback (2.0.3)
find (0.2.3)
interactive (0.3.3)
iot (0.1.6)
keyvault (2.0.5)
lab (0.0.5)
monitor (0.0.5)
network (2.0.7)
nspkg (3.0.0)
profile (2.0.5)
rdbms (0.0.2)
redis (0.2.4)
resource (2.0.7)
role (2.0.5)
sf (1.0.2)
sql (2.0.4)
storage (2.0.7)
vm (2.0.7)

Python (Linux) 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609]

Python location '/usr/bin/python'
```

**OS Version:** What OS and version are you using?  
Answer here: Azure Cloud Shell
```
**navneet@Azure:~$lsb_release -a**
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```
**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:  Bash

**Without the `-c` and `-n` options defined for a Blob SAS**
![image](https://user-images.githubusercontent.com/20584285/27275799-aea4fc44-54f6-11e7-9d7c-e7473f4091cc.png)

**With `-c` and `-n` options defined  for a Blob SAS**
![image](https://user-images.githubusercontent.com/20584285/27275738-6f62b152-54f6-11e7-8532-b87a00222f4f.png)

**Without the `-n` option defined for a Container SAS**
![image](https://user-images.githubusercontent.com/20584285/27276044-77644b58-54f7-11e7-9f8e-9ebbc299537c.png)

**With `-n` option defined  for a Container SAS**
![image](https://user-images.githubusercontent.com/20584285/27276056-821d4f7c-54f7-11e7-8dc6-28804cf75f42.png)

**Without the `-n` option defined for a Table SAS**
![image](https://user-images.githubusercontent.com/20584285/27276134-d1cafa88-54f7-11e7-9e21-33b8bd3f254d.png)

**With `-n` option defined  for a Table SAS**
![image](https://user-images.githubusercontent.com/20584285/27276154-ec4bc7a2-54f7-11e7-8f5b-a77eca0540bd.png)

**Comment by tjprescott** [comment]
cc/ @oakeyc @troydai. Could be an interactive bug manifesting in storage or a storage bug manifesting in interactive mode. ❓

**Comment by oakeyc** [comment]
@tjprescott, it's an interactive bug. The way it handles duplicate named parameters eg (-n, --name) isn't specific for commands. So there is some command where (-n, --account-name) is supposed to be the same, but that is not true for all --account-names.
