### ISSUE TITLE
how to assign particular new user ID via VMAccessForLinux?

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#3765]
### Description
**Outline the issue here:**
new user ID created by command below is '1000'

az vm extension set \
--resource-group myresourcegroup \
--vm-name myvm-xx \
--name VMAccessForLinux \
--publisher Microsoft.OSTCExtensions \
--protected-settings '{"username":"<USER>","password":"<PASSWORD>"}'

Is it possible to assign particular user ID?
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
According to https://docs.microsoft.com/en-us/cli/azure/install-azure-cli#windows

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
root@Alexey-HP:/root# az --version | head -1
azure-cli (2.0.8)

**OS Version:** What OS and version are you using?  
Answer here:
D:\>ver
Microsoft Windows [Version 10.0.15063]

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
Bash on Ubuntu on Windows

**Comment by tjprescott** [comment]
I would expect there is a setting you could set using the `--settings` argument. @yugangw-msft do you agree?

**Comment by tjprescott** [comment]
You might also ask your question here: https://github.com/Azure/azure-linux-extensions

They would know best if what you are trying to accomplish is supported. Briefly looking through their documentation, I didn't see where anyone chose the user ID manually.

**Comment by alexeyshishkin01** [comment]
do you mean using --settings <SCRIPT-CONFIG.JSON> instead of --protected-settings '{"username":"<USER>","password":"<PASSWORD>"}'?

**Comment by alexeyshishkin01** [comment]
so far new user is created with ID=1000 (CentOS) which set umask value to '0002' based on /etc/bashrc settings

**Comment by alexeyshishkin01** [comment]
any news?

**Comment by tjprescott** [comment]
@hosungsmsft can you comment?

**Comment by hosungsmsft** [comment]
I don't own the VMAccessForLinux extension, so I can't tell definitely, but I'm pretty sure that the extension doesn't offer such an option. If you'd like a more definite answer, this question should be asked at https://github.com/Azure/azure-linux-extensions. And this issue here should be closed. This is a question about the extension, not about the CLI.
