### ISSUE TITLE
VM extension set should support KEY=VALUE pairs like `group deployment create`

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#3767]
Currently `vm extension set` has `--settings` and `--protected-settings` which only accept JSON format. As these are simple key/value pairs, we should consider adding support similar to PR #3637.

**Comment by yugangw-msft** [comment]
@tjprescott, the extension `settings` can contain very arbitrary json with special characters that shell could interfere, hence it might not be very easy to use with key-value pairs.

**Comment by tjprescott** [comment]
I guess I'd argue it wouldn't be any harder than JSON but could be easier. However, since there are no customer asks here, we can close.
