### ISSUE TITLE
az group deployment create prompts for parameters even though they have a default value if the default value is null

### ISSUE THREAD

**Issue by johanste** [Azure/azure-cli#3771]
### Description
There is a) not a way that I've found to provide a null value (or empty string) as a template parameter value and b) if the parameter has a default value that is null, you still get prompted to provide a value

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
2.0.7

**OS Version:** What OS and version are you using?  
Answer here:
OSX

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
Bash

**Comment by tjprescott** [comment]
I plan to do this in concert with #3722 since it will involve similar logic (reading in the template first and then handling the parameters).
