### ISSUE TITLE
Misbehaved `az storage blob exists`

### ISSUE THREAD

**Issue by elibarzilay** [Azure/azure-cli#3772]
`az storage blob exists` would be much more useful if it would return a
non-zero exit code when the specified path doesn't exist.  It would make
it usable in a more idiomatic shell code,

    if az storage blob exists ...; then ...; fi

Currently, parsing the json output is much more tedious, using the `tsv`
output seems shaky (eg, it prints `False`, but maybe in the future it
will print `false`), etc.

Also, using `-o table` prints nothing at all if it doesn't exist, and a
useless output if it does.

**Comment by troydai** [comment]
Thanks for the suggestion. We did discuss this before. The challenge here is that there are other reasons may cause the command to fail:

1. Incorrect account key / name;
2. Failed network communication;
3. Incorrect command format / parameter / input.

Should 'non-exist' also represented by non-zero exit code, users will not able to deterministically call if the file/blob exists.

In terms of the `-otsv` output, the boolean value should be translated into `True` and `False` fairly stable.

**Comment by elibarzilay** [comment]
Re exit status: that's not a special issue...  Incorrect cases apply
even for a simple bash `-e` test.  The usual way of dealing with it is
to return a different error status when there's some other problem than
the one for nonexistent path.

And re the `tsv` output: I'm sorry but "fairly stable" is exactly what
I'm complaining about.  If it *is* stable, then that output should be
documented (and hopefully with tests in place to avoid a break in the
future).  If it's just a "fairly stable, for now", then it's useless for
use in scripts (that will probably linger around for a long time).

**Comment by JasonRShaver** [comment]
Our current policy is to treat exit codes as the success or failure of the command being executed.  This, as Troy mentioned, allows folks to have consistent expectations across all CLI commands.  

This also matches the industry pattern for POSIX where **any non-zero value** is consider an error.  And, of course, an `exists` function that did not find anything still worked as intended.  

I would recommend checking with BASH's conditional validation (better handling of param expansion, easier to debug with `set -ex`, and way safer than `test` / `[`):
```shell
if [[ -z $(az storage file exists -p ${path}) ]]; then
    echo "File exists"
else 
    echo "File does not exist"
fi
```

**Comment by elibarzilay** [comment]
@JasonRShaver: there are several problems with your reply:

1. The behavior that I *expected* is extremely idiomatic (in other
   words, a very common intustry pattern, if that's of any importance):

       bash$ [[ -e "missing file" ]]; echo $?
       1

   So in fact it's the `az` behavior which is not following this pattern.

2. I don't know whether it makes any difference here, but I talked about
   `az storage blob`, not `az storage file`.

3. I don't really know what you mean by the last sentence or your code
   example (which is broken in several ways)...  The exercise of
   correcting that example will demonstrate the inconvenience of the
   current behavior.
