### ISSUE TITLE
VM: boot diagnostics has a few glitches after enable it

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#3794]
(For tracking, as the issue is either on portal or CRP service.)
So, after `az vm boot-diagnostics enable`
  - Restarting the VM doesn’t work to emit out the boot log, rather you have to de-allocate the VM and start it, which is a bit crazy.
 - The portal doesn’t show the storage account associated in the setting tab for boot diagnostics, though the boot diagnostics appears works fine in the subsequent steps.

**Comment by LiliDeng** [comment]
+1, customer needs to see first boot up diagnostic info, azure cli 1.0 can enable boot diagnostics when create a vm

**Comment by yugangw-msft** [comment]
not repro'd any more

**Comment by yugangw-msft** [comment]
@LiliDeng, JFYI, though might be too late for you, but `enable on create` will be supported in the upcoming release.
