### ISSUE TITLE
[VMSS] Creating VMSS with new App Gateway uses expensive defaults

### ISSUE THREAD

**Issue by alexsab1** [Azure/azure-cli#3802]
### Description

Provisioning scale set with a new application gateway creates an application gateway of a Standard tier, of a Large SKU with 10 instances. That is about $3330.00 per month according to the pricing page: https://azure.microsoft.com/en-us/pricing/details/application-gateway/

`az vmss create --name "sitecore" --resource-group "<group name>" --image "Win2012R2DataCenter" --app-gateway "new" --instance-count=1 --upgrade-policy-mode=Manual --vm-sku=Standard_D2_v2`

Had I not noticed it I would have caused a huge expense for my company!

I suggest that new app gateway be provision with a Small SKU and one instance.

Below is the zip file with downloaded provision template:

[ExportedTemplate-vmss_deploy_GYwsNUbhJ4B0k2ZGNBNexwwXTPR363zp.zip](https://github.com/Azure/azure-cli/files/1092603/ExportedTemplate-vmss_deploy_GYwsNUbhJ4B0k2ZGNBNexwwXTPR363zp.zip)

Thank you

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:  MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 

azure-cli (2.0.8)

acr (2.0.6)
acs (2.0.8)
appservice (0.1.8)
batch (3.0.1)
billing (0.1.1)
cdn (0.0.4)
cloud (2.0.4)
cognitiveservices (0.1.4)
command-modules-nspkg (2.0.0)
component (2.0.5)
configure (2.0.8)
consumption (0.1.1)
core (2.0.8)
cosmosdb (0.1.8)
dla (0.0.8)
dls (0.0.8)
feedback (2.0.4)
find (0.2.4)
interactive (0.3.4)
iot (0.1.7)
keyvault (2.0.6)
lab (0.0.6)
monitor (0.0.6)
network (2.0.8)
nspkg (3.0.0)
profile (2.0.6)
rdbms (0.0.3)
redis (0.2.5)
resource (2.0.8)
role (2.0.6)
sf (1.0.3)
sql (2.0.5)
storage (2.0.8)
vm (2.0.8)

**OS Version:** What OS and version are you using?  
Answer here: Windows 10 Enterprise

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

**Comment by tjprescott** [comment]
@alexsab1 first, please delete the scaleset and gateway to prevent those charges from accruing.

The addition of application gateway to this command was intended to support scale sets with 100-1000 instances, which is why the defaults are the way they are. A small single unit gateway would simply not work for that scenario.

Your template shows you created a scaleset with a single instance with an application gateway. Were you just trying out the CLI or does this fit a scenario you are trying to achieve?

For more fine grained control, I'd recommend you create the application gateway using the `application-gateway create` command with whatever specific settings your scenario requires and then pass it into the VMSS create command.

cc/ @markjbrown

**Comment by alexsab1** [comment]
@tjprescott Thank you for the quick reply. I have deleted the resource group per your recommendation.

> Your template shows you created a scaleset with a single instance with an application gateway. Were you just trying out the CLI or does this fit a scenario you are trying to achieve?

Yes, I was trying out the example CLI for VMSS. 

> The addition of application gateway to this command was intended to support scale sets with 100-1000 instances, which is why the defaults are the way they are. A small single unit gateway would simply not work for that scenario.

I was following the documentation at https://docs.microsoft.com/en-us/cli/azure/vmss#create to create the new VMSS with a new gateway. Did you have other documentation in mind regarding the 100-1000 intended support?

> For more fine grained control, I'd recommend you create the application gateway using the application-gateway create command with whatever specific settings your scenario requires and then pass it into the VMSS create command.

I'm not sure I can do this yet, because the documentation at https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/address-pool#create states I need to provide servers. On the other hand the ARM template allows me to create a a backend pool without any associated servers

https://github.com/Azure/azure-quickstart-templates/blob/master/201-vmss-windows-app-gateway/azuredeploy.json

Also, the Portal will not allow me to create a backend pool without specifying server information.

So based on this I conclude that the only way I can associate new VMSS with an existing Application Gateway is through an ARM template. Is my understanding correct?

Thank you

**Comment by tjprescott** [comment]
Hi @alexsab1. We should definitely call out in the help and documentation exactly what kind of app gateway will be created when the user uses this functionality. We should also add an example for creating the very large VMSS.  By default, if you create a scale-set with fewer than 100 instances, you'll get a load balancer.

There is an open issue I am working on this sprint to improve the experience of creating these connections between load balancers, app gateways and VM/VMSS:  https://github.com/Azure/azure-cli/issues/3748.

Taking a look, I would agree that it doesn't seem possible to hook up an app gateway to a VMSS without using the create functionality--or at least it is very confusing. One way that I have tested would be to create the app-gateway using the `vmss create` command, and then follow up with this following:

`az network application-gateway update -g myRg -n myAppGateway --sku Standard_Small --capacity 1`

This would be a temporary workaround until this sprint's enhancements are in place.
