### ISSUE TITLE
According to telemetry, we have a problem with tab completion

### ISSUE THREAD

**Issue by johanste** [Azure/azure-cli#3807]
**Message:** <lambda>() got an unexpected keyword argument _prefix_
**Stack**: [_ File _usrlocallibpython3.5site-packagesazureclimain.py_, line 36, in main\n cmd_result = APPLICATION.execute(args)\n_, _ File _usrlocallibpython3.5site-packagesazureclicoreapplication.py_, line 179, in execute\n enable_autocomplete(self.parser)\n_, _ File _usrlocallibpython3.5site-packagesazureclicoreparser.py_, line 41, in enable_autocomplete\n default_completer=lambda _: ())\n_, _ File _usrlocallibpython3.5site-packagesargcomplete__init__.py_, line 214, in __call__\n completions = self._get_completions(comp_words, cword_prefix, cword_prequote, last_wordbreak_pos)\n_, _ File _usrlocallibpython3.5site-packagesargcomplete__init__.py_, line 244, in _get_completions\n completions = self.collect_completions(active_parsers, parsed_args, cword_prefix, debug)\n_, _ File _usrlocallibpython3.5site-packagesargcomplete__init__.py_, line 453, in collect_completions\n completions)\n_, _ File _usrlocallibpython3.5site-packagesargcomplete__init__.py_, line 407, in _complete_active_option\n prefix=cword_prefix, action=active_action, parser=parser, parsed_args=parsed_args)\n_]

I can provide additional callstacks if needed in order to investigate...

**Comment by tjprescott** [comment]
Please re-open if this is still an issue.
