### ISSUE TITLE
According to telemetry, polling while logging in sometimes fails

### ISSUE THREAD

**Issue by johanste** [Azure/azure-cli#3808]
**Message:** Unexpected polling state code_expired
**Stack:** [_site-packages\\azure\\cli\\main.py_, line 36, in main\n cmd_result = APPLICATION.execute(args)\n_, _site-packages\\azure\\cli\\core\\application.py_, line 210, in execute\n result = expanded_arg.func(params)\n_, _site-packages\\azure\\cli\\core\\commands\\__init__.py_, line 289, in __call__\n return self.handler(*args, **kwargs)\n_, _site-packages\\azure\\cli\\core\\commands\\__init__.py_, line 488, in _execute_command\n reraise(*sys.exc_info())\n_, _site-packages\\six.py_, line 686, in reraise\n raise value\n_, _site-packages\\azure\\cli\\core\\commands\\__init__.py_, line 465, in _execute_command\n result = op(client, **kwargs) if client else op(**kwargs)\n_, _site-packages\\azure\\cli\\command_modules\\profile\\custom.py_, line 91, in login\n raise CLIError(err)\n_]

**Comment by yugangw-msft** [comment]
`code_expired` means the device code.
2 possible causes:
1. The code is only valid for a limited period, so if you don't use the code to authenticate in the browser page, the code will expire, and adal-python's polling will fail.
2. For a period of about 7 days, particularly in Japan, the device code has server replicate issue, which caused authenticating through the browser could not succeed, again adal will fail for the same error

Please reactivate If you see new data leading to other causes
