### ISSUE TITLE
vm: creating managed image using sources from different region fails with a bad server error   

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#3809]
repro:
```bash
az group create -n rg -l westus
az snapshot -g rg -l eastus -n s1
az image create -g rg -n i1 --source s1 --os-type linux  
Deployment failed. An internal execution error occurred
```

**Comment by yugangw-msft** [comment]
For now, I will call out in related arguments' help doc

**Comment by kpu** [comment]
Please please fix this for real, by enabling copies of images with managed disks from one region to another.  This is a big pain point and should not require ten obtuse commands to figure out.

**Comment by derekbekoe** [comment]
@kpu 
This may be what you're after?
https://github.com/Azure/azure-cli-extensions/blob/master/src/image-copy/setup.py.

Let us know and we can describe how to install the extension.

cc: @tamirkamara

**Comment by mjconnection** [comment]
The Images need to be created from sources in the same Azure region.  Once created, images can be added to Azure shared image galleries for replication to other regions

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
