### ISSUE TITLE
ACS: Remove the duplicate az acs browse command

### ISSUE THREAD

**Issue by sauryadas** [Azure/azure-cli#3845]
### Description
There are 2 sets of commands
1) az acs browse 
2) az acs dcos browse and az acs kubernetes browse

Need to remove 1) because you cant browse for Docker Swarm and swarm mode because both orchestrators have no UI

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: Docker

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: Latest that comes with the docker image

**OS Version:** What OS and version are you using?  
Answer here: MAC osX

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by mboersma** [comment]
We don't plan to implement this `az acs` change. @tjprescott this issue can be closed.
