### ISSUE TITLE
[ARM] `group deployment` support KeyVault references

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#3852]
- [x] via parameters file
- [ ] via prompting
- [ ] via argument (similar to KEY=VALUE syntax)

**Comment by brendandburns** [comment]
@tjprescott Did you have any thoughts about what the syntax would be?

`!keyVault(vault, keyname)` ?

**Comment by tjprescott** [comment]
@brendandburns I haven't given it much thought. Since references are permitted via file it's pretty much back burner at the moment. My preference would be something like:

`--keyvault-parameter mySecret={secret URL}`

The annoying part is you need the secret NAME and the vault's ARM ID.  You only really get the secret name from the URL and then you'd have to do some kind of reverse lookup to try and get the vault's ARM ID from the base URL, but if that's possible, I'd rather do that than invent a tuple format. If you can have custom domains for the vault's base URL though this might not be possible.

**Comment by brendandburns** [comment]
That would be for a flag, but you also identify prompting. What did you have in mind for prompting?

**Comment by tjprescott** [comment]
I don't really have anything in mind--that's why it's on the back burner. :)  I would try to avoid a "function-like" syntax if possible.

The simplest thing I could think (from a user perspective) would be to put in a secret URL and automatically try and parse it as KeyVault.  If that doesn't work, then pass it as a string. From an implementation perspective though, there's a lot wonky about that approach.  @johanste, @schaabs, any thoughts?

**Comment by johanste** [comment]
Specifying the keyvault reference in a prompt is the least important scenario (in my mind). Being able to specify it through the parameters file was a must-have - and that should already work (else we have a clear bug to address :))

This leaves the parameter= command line flags.

**Comment by tjprescott** [comment]
I have verified that parameters file does work.

**Comment by yonzhan** [comment]
add to S165.

**Comment by zhoxing-ms** [comment]
For the moment, we think that most scenarios can be supported by the way of via parameters file. There is no need to support KeyVault references via prompt and argument.
I close this issue first, and maybe reopen it or open a new issue when users feedback similar needs.
