### ISSUE TITLE
Add supportsHttpsTrafficOnly flag option for "az storage account create" command

### ISSUE THREAD

**Issue by AlexeyAtIgloo** [Azure/azure-cli#3855]
### Description
**Outline the issue here:**

Unable to set supportsHttpsTrafficOnly flag when running `az storage account create`

As per API, this flag can be set: <https://docs.microsoft.com/en-us/rest/api/storagerp/storageaccounts#StorageAccounts_Create>

This option is missing from `az storage account create -h`

If this is possible to set after account creation, please let me know.
---

### Environment summary
**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip3

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
azure-cli (2.0.8)

acr (2.0.6)
acs (2.0.8)
appservice (0.1.8)
batch (3.0.1)
billing (0.1.1)
cdn (0.0.4)
cloud (2.0.4)
cognitiveservices (0.1.4)
command-modules-nspkg (2.0.0)
component (2.0.5)
configure (2.0.8)
consumption (0.1.1)
core (2.0.9)
cosmosdb (0.1.8)
dla (0.0.8)
dls (0.0.8)
feedback (2.0.4)
find (0.2.4)
interactive (0.3.4)
iot (0.1.7)
keyvault (2.0.6)
lab (0.0.6)
monitor (0.0.6)
network (2.0.8)
nspkg (3.0.0)
profile (2.0.6)
rdbms (0.0.3)
redis (0.2.5)
resource (2.0.8)
role (2.0.6)
sf (1.0.3)
sql (2.0.5)
storage (2.0.8)
vm (2.0.8)

**OS Version:** What OS and version are you using?  
Answer here: macOS Sierra 10.12.5

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: zsh

**Comment by tjprescott** [comment]
You should be able to set it using something like:

`storage account update ... --set supportsHttpsTrafficOnly=true`

**Comment by AlexeyAtIgloo** [comment]
Create account:
```sh
az group create --name someuniquename123 --location eastus
az storage account create --name someuniquename123 --resource-group someuniquename123 --sku Standard_GRS --kind BlobStorage --encryption blob --access-tier Cool --location eastus
```
Trying:
```sh
az storage account update --name someuniquename123 --resource-group someuniquename123 --set supportsHttpsTrafficOnly=true      
```
getting: `Property 'supports_https_traffic_only' not found on root. Update may be ignored.`

Trying:
```sh
az storage account update --name someuniquename123 --resource-group someuniquename123 --set properties.supportsHttpsTrafficOnly=true
```
Getting: `Couldn't find 'properties' in ''. Available options: ['accessTier', 'customDomain', 'encryption', 'sku', 'tags']`

Looks like its missing in update as well. I was not able to find it in the code, all tests have it hardcoded and set to 'false'

**Comment by troydai** [comment]
Thanks for reporting this issue.

**Comment by troydai** [comment]
Potential Sprint 18.

**Comment by angrox** [comment]
Obviously the official azure-cli documentation has this feature already documented (--https-only) https://docs.microsoft.com/en-us/cli/azure/storage/account#create

The code is still missing the feature, though.

**Comment by troydai** [comment]
The change was merged days ago https://github.com/Azure/azure-cli/pull/3997. The document site picks it up fast. The next release containing the change will be in a couple of weeks. I'll close this issue.

Thanks for reporting and commenting.
