### ISSUE TITLE
[Network] Support Application Gateway API 2017-06-01

### ISSUE THREAD

**Issue by akshaysngupta** [Azure/azure-cli#3856]
### Description
We are pushing to release few features for application gateway in the early July release for CLI.
* [Swagger changes](https://github.com/Azure/azure-rest-api-specs/pull/1285) are in for these features. 
* [Powershell Diff](https://github.com/Azure/azure-powershell/pull/4177/files)
**Note**: We are running late as NRP update is running late and hope that it gets over by 27 June.

### Summary of Changes
1)	ApplicationGateway Ssl Policy custom cipher suites support [new properties added to Sslpolicy Property of ApplciationGatewayPropertiesFormat]
2)	Get AvailableSslOptions api [new resource ApplicationGatewayAvailableSslOptions and child resource ApplicationGatewayPredefinedPolicy]
3)	Redirection support [new child resource ApplicationGatewayRedirectConfiguration for Application Gateway, new properties in UrlPathMap, PathRules and RequestRoutingRule]
4)	Azure Websites feature support [new properties in ApplicationGatewayBackendHttpSettingsPropertiesFormat, ApplicationGatewayProbePropertiesFormat, schema for property ApplicationGatewayProbeHealthResponseMatch]

**Comment by mayurid** [comment]
@JasonRShaver as FYI.
@akshaysngupta : Have put it in S18 for now. Do you have the Swagger updates ready? If not any ETA?

**Comment by akshaysngupta** [comment]
I have added the link to swagger in the description.

**Comment by tjprescott** [comment]
Based on the diff of the Swagger:
- New Commands: `ssl-policy show-options`, `ssl-policy list-predefined`, `ssl-policy show-predefined`
- New properties for `ssl-policy` objects: `type`, `name`, `cipher-suites`, `min-protocol`
- New properties for `http-settings` objects: `host-name`, `host-name-from-backend-address`, `affinity-cookie-name`, `enable-probe`, `path`
- New property for `url-path-map rule` object: `redirect-configuration`
- New properties for `probe` objects: `host-name-from-http-settings`, `min-servers`, `match-criteria`
- New object type: probe health response match with properties: `body`, `status-codes`
- New property for `rule` object: `redirect-configuration`
- New object type: redirect configuration with properties: `redirect-type`, `target-listener`, `target-url`, `include-path`, `include-query-string`, `request-routing-rules`, url-path-maps`, `path-rules`, `name`- 
- New properties on app-gateway object: `redirect-configurations`
- New properties on `url-path-map` objects: `default-redirect-configuration`

**Comment by lmazuel** [comment]
@tjprescott @akshaysngupta SDK released:
https://pypi.python.org/pypi/azure-mgmt-network/1.1.0

**Comment by tjprescott** [comment]
@akshaysngupta do these look correct to you?  Do you see anything I'm missing?

**Comment by tjprescott** [comment]
@akshaysngupta the Powershell PR mentions websites, but I didn't see anything related to that in the PR or in the swagger diff. Can you elaborate?

**Comment by akshaysngupta** [comment]
1) ssl-policy predefined show (by name) ?
2) ssl-policy: policytype ? , rename "name" to "policyname"
3) http-settings: host-name? (this must be by mistake)
4) For probe, How is match criteria specified ? This can a many more fields in the future.

Azure websites support has been added by picking up the host name from Backend pool and using it for probe and http settings

**Comment by tjprescott** [comment]
1. Yes, show is the GET operation by name
2. We are using `--name` because this is a CLI-wide convention.
3. `host_name` is a parameter that was previously required.  With this change it becomes optional.
4. `--match-body` and `--match-status-codes`.

**Comment by akshaysngupta** [comment]
--policyname will only be used when policytype (not mandatory) is specified and is set to predefined. 
minprotocolversion/ciphersuites are used when policy type is Custom. Additionally, None of the ssl-policy fields are mandatory. Its just that either use disabledSslProtocols or use the new fields

**Comment by tjprescott** [comment]
Yes. The CLI will automatically set policy-type based on whether a prefined policy name is supplied.  The server errors are good, so we don't have to duplicate a bunch of client side validation in the CLI (thank you!).

**Comment by akshaysngupta** [comment]
For ssl policy,
disabled ssl protocols field should not set the policy type (or should set to null).
minprotocolversion and cipehrsuites should set policy type to custom
policy name should set policy type to predefined

**Comment by akshaysngupta** [comment]
For testing the 3 new endpoints, try using `https://westcentralus.management.azure.com`
