### ISSUE TITLE
OS Version reported from client telemetry is inaccurate

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#3858]
### Description

Currently, `Context.Default.VS.Core.OS.Version` returns values such as `#100-ubuntu smp wed may 17 19:58:14 utc 2017`, which is difficult for the data teams to parse.  

Can we investigate how to get a better OS string?

**Comment by troydai** [comment]
The string is OS version string which is given by Ubuntu. We do not have the control over the format of the string.
``` Python
# Windows
platform.version()
'10.0.15063'

# MacOS
platform.version()
Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24-6/RELEASE_X86_X64

# Ubuntu
platform.version()
#100-ubuntu smp wed may 17 19:58:14 utc 2017
```

We return system type in OS.Type, which is 'Windows', 'Linux', and 'Darwin'. There isn't a good way to generalize the different distro among Linux without extensive string parsing.

**Comment by JasonRShaver** [comment]
It seems this is working as intended.
