### ISSUE TITLE
Idea: Single resource 'show' commands should auto-expand

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#386]
If we provide list vs single-item output (`list` vs. `show`), the single-item output should automatically --expand.  

I don't know of any cases that support nested expands (generally would require crossing RP boundaries), but we can cap this at the first level of nesting.   

This would align vm instance-view with vm show as a single command.  For perf-sensitive scenarios, we would direct users to `list`.  This would also grow the output size, but this is already an issue across the board and should be addressed by `--terse`

**Comment by johanste** [comment]
Networking has plenty of multi-level expands. If we were to do this, it would likely be on a case-by-case basis, and it would require multiple service calls. 

Also, compare with --depth for some of the VM calls in the xplat CLI.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
