### ISSUE TITLE
webapp:`az appservice list-locations` produces incomplete output

### ISSUE THREAD

**Issue by sptramer** [Azure/azure-cli#3869]
### Description

It looks like a filed (and fixed) bug with xplat is in CLI 2.0:

https://github.com/Azure/azure-xplat-cli/issues/2021
    
Check out the results from `az appservice list-locations -o tsv` to see what the current output is (it's the US-EN localized region names.) Doesn't look like there's another way to get a locations list.

---

### Environment summary

**Install Method:** Via `curl`

**CLI Version:** azure-cli (2.0.8), appservice (0.1.8)

**OS Version:** bash on Windows 10

**Shell Type:** Bash on Windows, using `zsh`

**Comment by yugangw-msft** [comment]
@sptramer, App service is a bit unique that it uses the geo-region which works for both `asm` and `arm`( the site created by CLI is actually visible under `asm` mode). The region name should work for you to create the plan, but let me know otherwise.

**Comment by sptramer** [comment]
The issue isn't creating the plan, but being able to get the internal identifiers for the regions _at all_. For example, if I wanted to find all locations in the US, I can guess that the naming scheme is of the form `*us`, but without a guarantee from an API point to get the identifiers, I don't know. There's also the possibility of `*us` slurping in domains/locations I may not want to batch-operate on, such as USG-compliant datacenters.

**Comment by yugangw-msft** [comment]
We should push the webapp team to fix it by providing "canonical name"

**Comment by ahmedelnably** [comment]
@LukaszStem can you please check this issue, and fix if needed

**Comment by ahmedelnably** [comment]
Currently we return the externally visible regions' names. doining * US and * US 2, should work to get all US regions. The USGov regions will not show up unless you connect your CLI to the USGov cloud, same applies for Chinese, German, and all other Azure sovereign clouds.

Closing this issue, please reopen if you still get an incomplete list
