### ISSUE TITLE
`az network vnet` create does not take address space of other vnets in the same subscription and/or resource group into account

### ISSUE THREAD

**Issue by johanste** [Azure/azure-cli#3870]
The portal will compute a non-overlapping address space for a newly created vnet (or warn you if you have overlapping address spaces). Ideally, we'd do something similar when we create default VNETs in create scenarios like `az vm create`.

**Comment by tjprescott** [comment]
Given that we've received no external customer requests for this enhancement, we are closing this issue. That being said, we would be open to reviewing any PR that incorporates such an ask.

**Comment by tjprescott** [comment]
Reopening this with the `help wanted` tag. If there's no further action on it for some time, we will close it.

**Comment by tjprescott** [comment]
No one has expressed interest in taking up this task in 6 months. Closing.
