### ISSUE TITLE
No value completion for many cosmosdb commands

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#3872]
### Description

I'm used to hitting [TAB][TAB] for value names but I don't get it for database names, or cosmos db account names.

For consistently with the rest of the CLI, would be good to see value completion enabled here also.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: `interactive script`

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
```
$ az --version
azure-cli (2.0.8)

acr (2.0.6)
acs (2.0.8)
appservice (0.1.8)
batch (3.0.1)
billing (0.1.1)
cdn (0.0.4)
cloud (2.0.4)
cognitiveservices (0.1.4)
command-modules-nspkg (2.0.0)
component (2.0.5)
configure (2.0.8)
consumption (0.1.1)
core (2.0.9)
cosmosdb (0.1.8)
dla (0.0.8)
dls (0.0.8)
feedback (2.0.4)
find (0.2.4)
interactive (0.3.4)
iot (0.1.7)
keyvault (2.0.6)
lab (0.0.6)
monitor (0.0.6)
network (2.0.8)
nspkg (3.0.0)
profile (2.0.6)
rdbms (0.0.3)
redis (0.2.5)
resource (2.0.8)
role (2.0.6)
sf (1.0.3)
sql (2.0.5)
storage (2.0.8)
vm (2.0.8)

Python (Darwin) 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]

Python location '/Users/debekoe/lib/azure-cli/bin/python'
```

**OS Version:** What OS and version are you using?  
`macOS Sierra`

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
`bash`

**Comment by shurd** [comment]
Thank you for the suggestion to help improve our command module. Currently, tab completion is available for database account names for most commands. I am tracking a change (work item 448972) that will enable auto completion for database account names when using the `update` command. The target date for this change is the middle of July. 

We are currently working on changing the way the CLI accesses databases and collections, so we are not going to make auto complete changes to those resources at this time. Unlike with database account names, they require very specific account information before any can be retrieved, so the auto complete would only be valid in a subset of cases.
