### ISSUE TITLE
Concurrency and multiple configuration support

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#3879]
### Description and goals
Add support for common concurrency operations, such as:
* Multiple VSTS Tasks running CLI jobs
* Concurrent usage of the CLI in multiple terminal sessions

Users can define the target config file for each command:

```shell
# uses ~/.azure/config
az vm list

# uses ~/.azure/prodconfig
az vm list --config prodconfig

# uses /usr/bin/config
az vm list --config /usr/bin/config
```

Users can create or edit config file with the configure command:

```shell
# edits default config
az configure

# creates prodconfig
az configure --config prodconfig

# edits prodconfig
az configure --config prodconfig
```

Users can change the default config with an env var

```shell
# uses default config
az vm list

# uses prodconfg
export AzConfig="prodconfg"
az vm list
```

Discussion:
1. Should we lock the config file for all commands?
2. Are we 'touching' the config file for read-only operations?

### Prior Art
http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html

https://cloud.google.com/sdk/gcloud/reference/config/

**Comment by yugangw-msft** [comment]
env var of `azure_configure_dir` should do it
