### ISSUE TITLE
[Test] create_random_name always generates None

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#3880]
When trying to use `create_random_name` from the test suite, it now always returns None.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: dev_setup.py

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:azure-cli (2.0.9+dev)

acr (2.0.7+dev)
acs (2.0.9+dev)
appservice (0.1.9+dev)
batch (3.0.2+dev)
billing (0.1.2+dev)
cdn (0.0.5+dev)
cloud (2.0.5+dev)
cognitiveservices (0.1.5+dev)
component (2.0.6+dev)
configure (2.0.9+dev)
consumption (0.1.2+dev)
core (2.0.10+dev)
cosmosdb (0.1.9+dev)
dla (0.0.9+dev)
dls (0.0.9+dev)
feedback (2.0.5+dev)
find (0.2.5+dev)
interactive (0.3.5+dev)
iot (0.1.8+dev)
keyvault (2.0.7+dev)
lab (0.0.7+dev)
monitor (0.0.7+dev)
network (2.0.9+dev)
nspkg (3.0.0+dev)
profile (2.0.7+dev)
rdbms (0.0.4+dev)
redis (0.2.6+dev)
resource (2.0.9+dev)
role (2.0.7+dev)
sf (1.0.4+dev)
sql (2.0.6+dev)
storage (2.0.9+dev)
taskhelp (0.1.4+dev)
testsdk (0.1.0+dev)
utility-automation (0.1.1)
vm (2.0.9+dev)

Python (Windows) 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)]

**OS Version:** What OS and version are you using?  
Answer here: Win10CU

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

**Comment by troydai** [comment]
This method can be removed. Thanks for spotting it.
