### ISSUE TITLE
[Test] run_tests should support --test

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#3885]
I should be able to run:

`run_tests --module {module] --test {one or more test names}`

in order to selectively run tests in the command line.  I can selectively run them in VS, but this is very slow and I avoid it unless I *need* to debug into the test.

Currently there is a syntax like so:
`nosetests azure.cli.command_modules.resource.tests.test_resource.DeploymentTest -c nose.cfg`

This only seems to work on Python 3 (See #3883) but more to the point, I should be able to leverage the script and not worry about the implementation or where the test folder is.

**Comment by troydai** [comment]
Fixed in https://github.com/Azure/azure-cli/pull/4062
