### ISSUE TITLE
az group export extracts arguably the wrong error message from result and excludes the whole template if anything fails to export

### ISSUE THREAD

**Issue by johanste** [Azure/azure-cli#3889]
### Description
There are plenty of resource types that currently fail on export (service issue). From the portal, you will get everything that was possible to export + list of error messages for things that couldn't be exported. From the CLI, you just get the first sub-error and nothing else if there is one or more errors.

For example, when running with verbose, you will see the following data in the log - but the error message is only "Could not get resources of the type 'Microsoft.Network/loadBalancers'. Resources of this type will not be exported" and the partial valid template is not output at all...

<partial valid template here>
,"error":{"code":"ExportTemplateCompletedWithErrors","message":"Export template operation completed with errors. Some resources were not exported. Please see details for more information.","details":[{"code":"ExportTemplateProviderError","target":"Microsoft.Network/loadBalancers","message":"Could not get resources of the type \'Microsoft.Network/loadBalancers\'. Resources of this type will not be exported."},{"code":"ExportTemplateProviderError","target":"Microsoft.Network/networkInterfaces","message":"Could not get resources of the type \'Microsoft.Network/networkInterfaces\'. Resources of this type will not be exported."},{"code":"ExportTemplateProviderError","target":"Microsoft.Network/networkSecurityGroups","message":"Could not get resources of the type \'Microsoft.Network/networkSecurityGroups\'. Resources of this type will not be exported."},{"code":"ExportTemplateProviderError","target":"Microsoft.Network/publicIPAddresses","message":"Could not get resources of the type \'Microsoft.Network/publicIPAddresses\'. Resources of this type will not be exported."},{"code":"ExportTemplateProviderError","target":"Microsoft.Network/virtualNetworks","message":"Could not get resources of the type \'Microsoft.Network/virtualNetworks\'. Resources of this type will not be exported."},{"code":"ExportTemplateProviderError","target":"Microsoft.Web/sites/premieraddons","message":"Could not get resources of the type \'Microsoft.Web/sites/premieraddons\'. Resources of this type will not be exported."},{"code":"ExportTemplateProviderError","target":"Microsoft.Web/sites/sourcecontrols","message":"Could not get resources of the type \'Microsoft.Web/sites/sourcecontrols\'. Resources of this type will not be exported."}]}}'

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Latest

**OS Version:** What OS and version are you using?  
Windows

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Bash

**Comment by markheath** [comment]
I'm running into this a lot - makes the `az group export` command almost unusable

**Comment by mikewiegand** [comment]
Hi,
is there any update on this? I'd love to see this work.
thanks

**Comment by sshorkey** [comment]
+1 to seeing a fix.. it should give least a partial template from what it can extract and spit out error messages for whatever it can't. Any workarounds possible in the meantime?

**Comment by jochenvanwylick** [comment]
+1

**Comment by tjprescott** [comment]
Does running the command with `--debug` give you any additional information?
