### ISSUE TITLE
'az account show' --expanded-view option is deprecating and will be removed

### ISSUE THREAD

**Issue by johanburati** [Azure/azure-cli#3894]
When using the  **az account show** command option **--expanded-view** , 
it says that the option will be removed in the future and to use **az cloud show** command instead,
however it is currently not possible to retrieve the password using the **az cloud show** command.

Could you you tell me what command to use to retrieve the password as below ?

```
az account show --expanded-view

'--expanded-view' is deprecating and will be removed in a future
release. You can get the same information using 'az cloud show'
{
  "client": "https://",
  "endpoints": {
    "activeDirectory": "https://",
    "activeDirectoryGraphResourceId": "https://",
    "activeDirectoryResourceId": "https://",
    "batchResourceId": "https://",
    "gallery": "https://",
    "management": "https://",
    "resourceManager": "https://",
    "sqlManagement": "https://",
    "vmImageAliasDoc": "https://"
  },
  "environmentName": "AzureCloud",
  "password": "*******************************************=",
  "subscriptionId": "******************************************",
  "subscriptionName": "******************************************",
  "tenantId": "******************************************"
}
```

**Comment by yugangw-msft** [comment]
@johanburati , this flag was originally introduced to expose a few information for sdk-for-java. We are renaming to like "--sdk-auth" through #3867, so it can be a bit more explicit to support all azure sdks
We don't expect CLI users will ever need to read the secret as CLI will maintain it and acquire access tokens for all CLI commands, so it should be transparent to users
