### ISSUE TITLE
[Test] CI Output cluttered with Coverage information

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#3895]
Recently I have noticed that when a CI build fails, the output is filled with pages and pages of code coverage statistics.  These are not in any way helpful as they are never the cause of the build failure. This was not the behavior until recently so we should revert whatever change introduced this along with #3878.

**Comment by troydai** [comment]
Add to sprint 18. Low priority.

**Comment by troydai** [comment]
Fixed in #3955
