### ISSUE TITLE
Can no longer create container registry due to unavailable apiVersion

### ISSUE THREAD

**Issue by EricABC** [Azure/azure-cli#3898]
### Description
**Outline the issue here:**

```az acr create -n ... -g ... --sku Managed_Standard``` fails since the new version (which adds delete capabilities) elevated the apiVersion for registries to 2017-06-01-preview.  ```az provider show -n Microsoft.ContainerRegistry``` shows only 2017-03-01.  My goal was to recreate with a managed storage SKU so I could use delete.  To the best of my knowledge it isn't related to my azure subscription so I filed here.  I already tried re-registering ContainerRegistry under subscriptions, in case that was necessary.  The error code is NoRegisteredProviderFound.  The update seems to be a week ago here https://github.com/Azure/azure-cli/commit/855f1233a4211c99cb7708833b5c85d5a47b36bf

---

### Environment summary

Newest CLI, includes acr 2.0.7

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: Both MSI and BashUW

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.9 (acr 2.0.7)

**OS Version:** What OS and version are you using?  
Answer here: win10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: PS/Bash

**Comment by djyou** [comment]
Hi EricABC, managed registries together with several other features will be publicly available by 7/5. Creating registries in Basic SKU can work as they were, but as you also said, delete repositories will only be supported in managed registries. /cc @SajayAntony

**Comment by EricABC** [comment]
Great, thanks!  I see I jumped the gun, so I'll close.
