### ISSUE TITLE
`az group deployment create` runs forever

### ISSUE THREAD

**Issue by scottkof** [Azure/azure-cli#3899]
### Description
`az group deployment create` runs forever. Top-level deployment never completes, but all sub-deployments are successfully created.
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
azure-cli (2.0.9)

acr (2.0.7)
acs (2.0.9)
appservice (0.1.9)
batch (3.0.2)
billing (0.1.2)
cdn (0.0.5)
cloud (2.0.5)
cognitiveservices (0.1.5)
command-modules-nspkg (2.0.0)
component (2.0.6)
configure (2.0.9)
consumption (0.1.2)
core (2.0.10)
cosmosdb (0.1.9)
dla (0.0.9)
dls (0.0.9)
feedback (2.0.5)
find (0.2.5)
interactive (0.3.5)
iot (0.1.8)
keyvault (2.0.7)
lab (0.0.7)
monitor (0.0.7)
network (2.0.9)
nspkg (3.0.0)
profile (2.0.7)
rdbms (0.0.4)
redis (0.2.6)
resource (2.0.9)
role (2.0.7)
sf (1.0.4)
sql (2.0.6)
storage (2.0.9)
vm (2.0.9)

Python (Darwin) 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]

Python location '/Users/xxxxx/dev/az-v/bin/python'

**OS Version:** What OS and version are you using?  
macOS 10.12.5

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
bash in macOS Terminal

**Comment by brendandburns** [comment]
Can you send your Subscription ID (and correlation-id if you have it) to bburns [at] microsoft.com

We'll dig into logs.

**Comment by scottkof** [comment]
I emailed you some data about an unending deployment.

**Comment by brendandburns** [comment]
Closing this as obsolete...

**Comment by brendandburns** [comment]
(or I don't have the power, but we should close this @tjprescott)

**Comment by tjprescott** [comment]
Please re-open if this is still an issue.

**Comment by andybrucenet** [comment]
This is occurring for me as well - latest of everything installed.

Install method: brew install azure-cli

Version:
$ az --version
azure-cli                         2.64.0

core                              2.64.0
telemetry                          1.1.0

Extensions:
log-analytics                      0.2.2

Dependencies:
msal                              1.30.0
azure-mgmt-resource               23.1.1

Python location '/usr/local/Cellar/azure-cli/2.64.0/libexec/bin/python'
Extensions directory '/Users/l.abruce/.azure/cliextensions'

Python (Darwin) 3.11.10 (main, Sep  7 2024, 01:03:31) [Clang 15.0.0 (clang-1500.3.9.4)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

Operation:
az deployment group create --resource-group fdiaz-m-tc3-dnsserver --mode Incremental --name fdiaz-m-tc3-dnsserver-deployment --parameters @work/arm/azuredeploy.parameters.json --template-file work/arm/azuredeploy.json --output json

See attached json files for specifics.

The command simply hangs. All the resources are created - VM, NIC, etc. I can login to the created VM using the public IP.
[azuredeploy.json](https://github.com/user-attachments/files/16967293/azuredeploy.json)
[azuredeploy.parameters.json](https://github.com/user-attachments/files/16967294/azuredeploy.parameters.json)
