### ISSUE TITLE
Support to delete multiple resources with dependent relationship

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#3902]
This is to support users can delete all resources created by `az vm/vmss create` so to avoid getting billed by leftovers such as the public IP. The flow by leveraging tags:
```bash
1.	az vm create -g myRG -n myVM --image centos --tag staging
2.	az resource delete –-id $(az resource list –tag staging –query “[].id” -otsv)
```

**Comment by riezebosch** [comment]
> This is to support users can delete all resources created by `az vm/vmss create` so to avoid getting billed by leftovers such as the public IP. The flow by leveraging tags:
> 
> ```shell
> 1.	az vm create -g myRG -n myVM --image centos --tag staging
> 2.	az resource delete –-id $(az resource list –tag staging –query “[].id” -otsv)
> ```

I suppose the `$()` notation is specific to bash and won't work on cmd for example?

**Comment by riezebosch** [comment]
Unfortunately, you don't have that luxury when using the [Azure CLI task](https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureCLIV1) in Azure Pipelines. It's very hard to write a cross-shell compatible script there, a problem that I partially solved with [this extension](https://marketplace.visualstudio.com/items?itemName=riezebosch.setvar).
