### ISSUE TITLE
Unable to debug C# Functions in VS2017 Preview after clean install

### ISSUE THREAD

**Issue by cmatskas** [Azure/azure-cli#3903]
### Description
After having to repave my machine, I tried to re-install my Azure Functions tooling. The order of the install was:

- VS2017 Preview (15.3)
- Node.js/NPM
- Azure Functions Extension for VS2017 Preview
- Azure Functions Core Tools (via NPM)

Tried to debug a C# Function but I got the following error:
![functionerror](https://user-images.githubusercontent.com/4126750/27604845-8a062548-5b72-11e7-86be-3a5aa9cee7f0.png)

I then installed the **Azure Function CLI (old version)** which failed to install due to bandwidth issues. To fix this I download it manually following the steps outlined here: [https://github.com/Azure/Azure-Functions/issues/110](https://github.com/Azure/Azure-Functions/issues/110). 

I unzipped the files in the following location:
`C:\Users\<userprofile>\AppData\Local\Azure.Functions.Cli\1.0.0-beta.9`

This made VS2017 to stop complaining, but the Function failed to run since there was a mismatch between the CLI tools and the latest Functions project format (WebJobs based). 

###Workaround
To make it work, I went in my NPM package folder and copied the executable and accompanying dlls to the directory that VS2017 expects to find them. To make it more explicit, I copied from here:

**C:\Users\<userprofile>\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin**
to
**C:\Users\<userprofile>\AppData\Local\Azure.Functions.Cli\1.0.0-beta.9**

With this workaround, I was able to run and debug the latest Functions code in VS2017
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
Azure Functions Core tools ->NPM 
Azure CLI -> manually

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
Azure Functions Core Tools (1.0.0-beta.99)
Function Runtime Version: 1.0.11002.0

**OS Version:** What OS and version are you using?  
Answer here: Windows 10 Creator's update

**Comment by tjprescott** [comment]
When you run `az --version` what output do you get?

**Comment by cmatskas** [comment]
Stupid me.. this is the wrong thread! Apologies for the confusion but this belongs to the Azure Functions CLI! arg, too many CLIs
