### ISSUE TITLE
Invalid cloud configurations leaves CLI in corrupted state.

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#3905]
### Description
If you use attempt to use an incorrectly configured cloud
```
az cloud register -n Dogfood --endpoint-resource-manager https://api-dogfood.resources.windows-int.net/ --endpoint-management https://management.core.windows.net/ --endpoint-active-directory https://login.windows-ppe.net --endpoint-active-directory-graph-resource-id https://graph.ppe.windows.net/ 
```

After login, the CLI won't load:
```
Error loading command module 'acr'
Error loading command module 'acs'
Error loading command module 'appservice'
Error loading command module 'cdn'
Error loading command module 'dla'
Error loading command module 'dls'
Error loading command module 'iot'
Error loading command module 'keyvault'
Error loading command module 'lab'
Error loading command module 'monitor'
Error loading command module 'network'
Error loading command module 'rdbms'
Error loading command module 'redis'
Error loading command module 'resource'
Error loading command module 'sf'
Error loading command module 'sql'
Error loading command module 'storage'
Error loading command module 'vm'
The endpoint 'active_directory_resource_id' for this cloud is not set but is used.
```

I deleted `~/.azure/clouds.config`, to attempt to recover, but now the CLI reports the cloud being invalid:
```
CloudNotRegisteredException: The cloud 'Dogfood' is not registered.
```

but I cannot list or change clouds.

**Comment by JasonRShaver** [comment]
Workaround is to delete the `config` file or change the cloud config to
```
[cloud]
name = AzureCloud
```

**Comment by derekbekoe** [comment]
@JasonRShaver How about this experience?
1. The error message says `clouds.config may be corrupt or invalid` and suggests deleting the file.
2. On `az` if the cloud is not registered, we default to Public Azure cloud.

```bash
$ az cloud register -n Dogfood --endpoint-resource-manager https://api-dogfood.resources.windows-int.net/ --endpoint-management https://management.core.windows.net/ --endpoint-active-directory https://login.windows-ppe.net --endpoint-active-directory-graph-resource-id https://graph.ppe.windows.net/
$ az
Error loading command module 'acr'
...
Error loading command module 'vm'

     /\
    /  \    _____   _ _ __ ___
   / /\ \  |_  / | | | \'__/ _ \
  / ____ \  / /| |_| | | |  __/
 /_/    \_\/___|\__,_|_|  \___|


Welcome to the cool new Azure CLI!

Here are the base commands:

The endpoint 'active_directory_resource_id' for this cloud is not set but is used.
/Users/debekoe/.azure/clouds.config may be corrupt or invalid.
You can delete this file and try again.
$ rm /Users/debekoe/.azure/clouds.config
$ az
The cloud 'Dogfood' is not registered.
Resetting active cloud to 'AzureCloud'.

     /\
    /  \    _____   _ _ __ ___
   / /\ \  |_  / | | | \'__/ _ \
  / ____ \  / /| |_| | | |  __/
 /_/    \_\/___|\__,_|_|  \___|


Welcome to the cool new Azure CLI!
```

**Comment by rbitia** [comment]
Rias-MacBook-Pro:aci-demos riabhatia$ az logout
Error loading command module 'acr'
Error loading command module 'acs'
Error loading command module 'appservice'
Error loading command module 'batch'
Error loading command module 'billing'
Error loading command module 'cdn'
Error loading command module 'cognitiveservices'
Error loading command module 'consumption'
Error loading command module 'container'
Error loading command module 'cosmosdb'
Error loading command module 'dla'
Error loading command module 'dls'
Error loading command module 'eventgrid'
Error loading command module 'iot'
Error loading command module 'keyvault'
Error loading command module 'lab'
Error loading command module 'monitor'
Error loading command module 'network'
Error loading command module 'rdbms'
Error loading command module 'redis'
Error loading command module 'resource'
Error loading command module 'role'
Error loading command module 'servicefabric'
Error loading command module 'sql'
Error loading command module 'storage'
Error loading command module 'vm'
The endpoint 'management' for this cloud is not set but is used.
/Users/riabhatia/.azure/clouds.config may be corrupt or invalid.
Resolve the error or delete this file and try again.
Rias-MacBook-Pro:aci-demos riabhatia$ 


Still in a bad state plz reopen the issue

**Comment by derekbekoe** [comment]
@rbitia which version of the CLI are you running?

**Comment by derekbekoe** [comment]
Opening the issue again to make this change:
Mark the endpoints that are likely to cause the CLI to fail as required on 'az cloud register'.

**Comment by derekbekoe** [comment]
Closed with https://github.com/Azure/azure-cli/pull/4830
