### ISSUE TITLE
Get window dimension in global scope will cause issues when az is not run in a terminal

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#3906]
`$TERM` is missing when the command is not run in a terminal. Therefore fetching dimension will fail no matter what. Running `get_window_dim` in global scope will cause an exception when simply `azure-cli-interactive` is just imported.

https://github.com/Azure/azure-cli/blob/4e25d149cf8b1ad2182e89a0c1c29e2638a5b6b8/src/command_modules/azure-cli-interactive/azclishell/gather_commands.py#L16

**Comment by oakeyc** [comment]
This was fixed in #3893
