### ISSUE TITLE
Integrate commandlint script into CI work flow

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#3912]
We have a commandlint script running in CI that shows commands/params without descriptions.
However, it doesn't exit with non-zero exit code if there's an error so the errors are ignored and CI still passes.

- [ ] Fail with exit code 1 if there are commands without descriptions.
- [ ] Modify our [PR template](https://github.com/Azure/azure-cli/blob/master/.github/PULL_REQUEST_TEMPLATE.md) to remove "Each command and parameter has a meaningful description." as CI will check this now.
- [ ] The error should be more descriptive (current error below) as currently, you don't even know what caused that error to appear. Consider adding a message like "The following commands/parameters don't have descriptions". If there are other things the script checks, add these to the message also.

```
==== FAILED COMMANDS ====
{
  "commands": [],
  "parameters": {
    "dla account compute-policy update": [
      "max_dop_per_job",
      "compute_policy_name",
      "min_priority_per_job"
    ],
    "dls account update": [
      "key_version"
    ],
    "dla account compute-policy create": [
      "max_dop_per_job",
      "object_type",
      "compute_policy_name",
      "object_id",
      "min_priority_per_job"
    ],
    "dla account blob-storage add": [
      "storage_account_name"
    ],
    "dla account blob-storage update": [
      "storage_account_name"
    ],
    "dla job submit": [
      "recurrence_id",
      "recurrence_name",
      "run_id",
      "pipeline_id",
      "pipeline_uri",
      "pipeline_name"
    ],
    "lock show": [
      "resource_name"
    ]
  },
  "subgroups": []
}
```

**Comment by derekbekoe** [comment]
cc: @oakeyc @troydai

**Comment by tjprescott** [comment]
I was looking at the allowed-error doc and there are some additional issues that need to be resolved before we should rely on this script:

- [ ] Counts a parameter as missing even if it is `ignore_type`.  We don't care about missing help for suppressed parameters :smile: (ex: `network application-gateway auth-cert update: cert-data`)
- [ ] Appears to count help as missing if it is supplied solely via the help file and not through the help kwarg for `register_cli_argument`.  (ex: `network application-gateway waf-config set: rule_set_version...`)

**Comment by derekbekoe** [comment]
@williexu Sounds like the linter to me. Close?

**Comment by williexu** [comment]
@derekbekoe Yep, we've actually removed the old commandlint script.
