### ISSUE TITLE
az vm create under PowerShell won't permit empty public-ip-address

### ISSUE THREAD

**Issue by TitaniumCoder477** [Azure/azure-cli#3917]
### Description
**Outline the issue here:**
I first noticed this issue with my full az vm create command, and I progressively simplified it until it was basically just `az vm create --resource-group TEST --name TEST-VNAS --public-ip-address ""` and it still threw the error: `az vm create: error: argument --public-ip-address: expected one argument`. That's when I finally thought maybe this is just an issue with az under PowerShell. So I tried my original full command under a simple Command Prompt window, and it worked fine.

![170629-screenshot](https://user-images.githubusercontent.com/26101661/27686322-484614f4-5ca0-11e7-9ed0-c274c161bfb5.PNG)

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: MSI on Windows 10 Pro

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.9  (same version under PowerShell and CMD)

**OS Version:** What OS and version are you using?  
Answer here: Windows 10 Pro

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: PowerShell (throws error) and CMD (no issues)

**Comment by tjprescott** [comment]
Powershell is not a supported shell for Azure CLI 2.0. You might try using double single quotes instead of double quotes.... OR (this is a hacky workaround) you could try something like "''" (two singles wrapped in double) or '""' (two doubles wrapped in singles).

**Comment by TitaniumCoder477** [comment]
I guess MS has reasons for not supporting the cli under their own shell,
but oh well. One more reason to use my Linux box! :)

**Comment by tjprescott** [comment]
The main reason is because it is assumed that people using Powershell would be using the Powershell cmdlets for working with Azure rather than Azure CLI 2.0.

**Comment by TitaniumCoder477** [comment]
Ah, now that makes sense! I've just started exploring command line
interaction with Azure and didn't realize there was PS  commands for it
too.

**Comment by tjprescott** [comment]
https://github.com/Azure/azure-powershell

Enjoy (or use our product on your Linux box :grin:)

**Comment by tjprescott** [comment]
The CLI was not designed for use in Powershell. It was designed for use in CMD.exe and bash. As a result, while it does work in Powershell, it means that some of the syntax is much more cumbersome in Powershell. Online docs are written for bash specifically.

**Comment by automagicallyio** [comment]
--public-ip-address '""' worked. thanks.
