### ISSUE TITLE
Add VMSS public IP per VM feature to VMSS create

### ISSUE THREAD

**Issue by gbowerman** [Azure/azure-cli#3923]
### Description
Please add support for the new public IP per VM feature for VMSS to the CLI VMSS create command:

### Creating a scale set with public IP per VM
To create a VM scale set that assigns a public IP address to each VM, make sure the API version of the Microsoft.Compute/virtualMAchineScaleSets resource is 2017-03-30, and add a publicipaddressconfiguration JSON packet to the scale set ipConfigurations section. Example:
```
    "publicipaddressconfiguration": {
        "name": "pub1",
        "properties": {
        "idleTimeoutInMinutes": 15
        }
    }
```

**Comment by gbowerman** [comment]
For more information on the new VMSS network features: [https://github.com/gbowerman/azure-myriad/tree/master/preview/network](https://github.com/gbowerman/azure-myriad/tree/master/preview/network)

**Comment by yugangw-msft** [comment]
We will try to get this into the current release if we can.
//cc:@mayurid

**Comment by yugangw-msft** [comment]
#3961
