### ISSUE TITLE
Add configurable DNS features to VMSS create

### ISSUE THREAD

**Issue by gbowerman** [Azure/azure-cli#3924]
### Description
Please add the new VMSS configurable DNS features to the VMSS create command..
## Configurable DNS Settings
For DNS, previously scale sets relied on the specific DNS settings of the VNET and subnet they were created in. With configurable DNS, you can now configure the DNS settings for a scale set directly. The DNS settings will then apply to all VMs in the scale set.

### Creating a scale set with configurable DNS servers
To create a VM scale set with a custom DNS configuration, add a dnsSettings JSON packet to the scale set networkInterfaceConfigurations section. Example:
```
    "dnsSettings":{
        "dnsServers":["10.0.0.6"], ["10.0.0.5"]
    }
```

### Creating a scale set with configurable domain name
To create a VM scale set with a custom DNS name, add a dnsSetting JSON packet to the scale set networkInterfaceConfigurations section. Example:

```
          "networkProfile": {
            "networkInterfaceConfigurations": [
              {
                "name": "nic1",
                "properties": {
                  "primary": "true",
                  "ipConfigurations": [
                    {
                      "name": "ip1",
                      "properties": {
                        "subnet": {
                            "id": "[concat('/subscriptions/', subscription().subscriptionId,'/resourceGroups/', resourceGroup().name, '/providers/Microsoft.Network/virtualNetworks/', variables('vnetName'), '/subnets/subnet1')]"
                        },
                        "publicIPAddressconfiguration": {
                          "name": "publicip",
                          "properties": {
                            "idleTimeoutInMinutes": 10,
                              "dnsSettings": {
                                "domainNameLabel": "[parameters('vmssDnsName')]"
                              }
                          }
                        }
```

The output, in terms of individual VM dns name would look like: 
```
<vmname><vmindex>.<specifiedVmssDomainNameLabel>
```

**Comment by yugangw-msft** [comment]
We will try to get this into the current release if we can.
//cc:@mayurid

**Comment by yugangw-msft** [comment]
#3961
