### ISSUE TITLE
Add multiple IP address per NIC support to VMSS create

### ISSUE THREAD

**Issue by gbowerman** [Azure/azure-cli#3925]
### Description
Please add support for multiple IP addresses per NIC to VMSS create command.

You can now define up to 50 IP addresses per NIC when creating a VM scale set. Syntax is the same as multiple IP addresses per NIC for regular VMs, i.e. add multiple entries to ipConfigurations[] in the networkInterfaceConfigurations list.

See [https://github.com/gbowerman/azure-myriad/tree/master/preview/network](https://github.com/gbowerman/azure-myriad/tree/master/preview/network) for more details.

**Comment by yugangw-msft** [comment]
Per discussion, move to a later milestone till we have more user asks on this

**Comment by yugangw-msft** [comment]
Will reactivate it till we have more user asks on this. It is hard to fit 2 dimensions of configuration in a single command line. Users might be better to use deployment templates

//CC: @gatneil,
