### ISSUE TITLE
Add HTTPs Only support in CLI for storage management

### ISSUE THREAD

**Issue by fhryo-msft** [Azure/azure-cli#3930]
### Description
We released a feature named "Secure Transfer Required" on storage account. Right now it's supported in both REST API and Python SDK:
REST API (Version: 2016-12-01): https://docs.microsoft.com/en-us/rest/api/storagerp/storageaccounts
Python SDK (1.1.0): https://pypi.python.org/pypi/azure-mgmt-storage/1.1.0

We expect CLI support the feature in two scenarios:
1. Enable/Disable the option when creating new storage accounts
2. Enable/Disable the option for existing storage accounts

The option is named "supportsHttpsTrafficOnly" in storage account.

We don't have strong timeline requirement so it's fine to release it in your next release train.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: As far as CLI supports today

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: As far as CLI supports today

**OS Version:** What OS and version are you using?  
Answer here: As far as CLI supports today

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: As far as CLI supports today

**Comment by troydai** [comment]
Please in sprint 18 for now.

**Comment by troydai** [comment]
Move to sprint 19. Upgrading to 1.1.0 sdk will pull in `azure-nskpg 2.0.0` and `azure-mgmt-nspkg 2.0.0`. It requires more testing time.
