### ISSUE TITLE
Creating a new policy in IOT Hub deletes all the existing policies

### ISSUE THREAD

**Issue by amaldevv** [Azure/azure-cli#3934]
### Description
When I am executing the `az iot hub policy create` command to create a new policy, all the existing shared access policies in the hub are getting deleted

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  

azure-cli (2.0.9)

acr (2.0.7)
acs (2.0.9)
appservice (0.1.9)
batch (3.0.2)
billing (0.1.2)
cdn (0.0.5)
cloud (2.0.5)
cognitiveservices (0.1.5)
command-modules-nspkg (2.0.0)
component (2.0.6)
configure (2.0.9)
consumption (0.1.2)
core (2.0.10)
cosmosdb (0.1.9)
dla (0.0.9)
dls (0.0.9)
feedback (2.0.5)
find (0.2.5)
interactive (0.3.5)
iot (0.1.8)
keyvault (2.0.7)
lab (0.0.7)
monitor (0.0.7)
network (2.0.9)
nspkg (3.0.0)
profile (2.0.7)
rdbms (0.0.4)
redis (0.2.6)
resource (2.0.9)
role (2.0.7)
sf (1.0.4)
sql (2.0.6)
storage (2.0.9)
vm (2.0.9)

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'

**OS Version:** What OS and version are you using?  
Windows 10 Pro 1703 (Build 15063.413)

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Powershell

**Comment by BretStateham** [comment]
I am having the same issues.  I have a video that shows the behavior as well as repro steps here: https://1drv.ms/f/s!Al5K6Hl-Z2ggpOAxFzzNxiPoqKscjA

Repro steps given here for convenience:

1. Login to the Azure Portal
2. Open the Bash Cloud Shell
3. Issue the following commands (replacing the bssgroupcli3 and bssiotcli3 names with your own).

```bash
az group create --name "bssgroupcli3" --location "westus"
az iot hub create --resource-group "bssgroupcli3" --name "bssiotcli3" --sku "s1" --unit 1 --location "westus"
az iot device create --resource-group "bssgroupcli3" --hub-name "bssiotcli3" --device-id "coffeepot"
az iot hub policy list --resource-group "bssgroupcli3" --hub-name "bssiotcli3"
az iot hub policy create --resource-group "bssgroupcli3" --hub-name "bssiotcli3" --name "coffeeclient" --permissions ServiceConnect
az iot hub policy list --resource-group "bssgroupcli3" --hub-name "bssiotcli3"
```

4. Note that the output of the first call to "az iot hub policy list" displays all of the default SAS Policies for a hub (iothubowner, service, device, etc.).
However if the bug occurred (which it doesn't always) the second call to "az iot hub policy list" after creating the "coffeeclient" policy shows ONLY the "coffeeclient" SAS policy.



Although the repro steps use the cloud shell I have seen the problem occur on both local powershell and bash shells as well.  Also multiple users on multiple computers in multiple regions have experienced the issue.

**Comment by BretStateham** [comment]
Actually, after a little more testing it appears that the problem occurs in azure-cli version 2.0.9, but it is not happening on the same machine, group, hub, etc. with version 2.0.1.  Tested this in both a Powershell and Bash shell on my machine.  2.0.1 works, 2.0.9 has the problem. 

Version information where it is working correctly (in PowerShell):

```bash
C:\WINDOWS\system32> az --version
azure-cli (2.0.1)

acr (0.1.1b2)
acs (2.0.1)
appservice (0.1.1b6)
batch (0.1.1b5)
cloud (2.0.0)
component (2.0.0)
configure (2.0.1)
container (0.1.1b4)
context (0.1.1b2)
core (2.0.1)
documentdb (0.1.1b2)
feedback (2.0.0)
find (0.0.1b1)
iot (0.1.1b3)
keyvault (0.1.1b6)
network (2.0.1)
nspkg (2.0.0)
profile (2.0.1)
redis (0.1.1b3)
resource (2.0.1)
role (2.0.0)
sql (0.1.1b6)
storage (2.0.1)
vm (2.0.1)
```

**Comment by tjprescott** [comment]
@xscript to take a look

**Comment by jsturtevant** [comment]
I had the same issue in `version 2.0.3`. I upgraded to `azure-cli (2.0.14)` with iot version `iot (0.1.10)` and it is now working as expected, leaving existing policies alone.
