### ISSUE TITLE
AZ cli python3 virtualenv picks wrong interpreter

### ISSUE THREAD

**Issue by vijayrajah** [Azure/azure-cli#3937]
### Description
I installed az-cli usig the follwing steps

```
mkdir az-cli-venv
python3 -m venv az-cli-venv
cd /az-cli-venv
source bin/activate
pip install azure-cli

```
the install is successful.  I'm able to use the if I activate it

but when I try to execute (without activating the venv)
`/az-cli/bin/az`
it fails with

> /usr/bin/python: No module named azure

This is because it picks improper python interpreter

---
**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
CLI Version: latest (2.0.9)

**OS Version:** What OS and version are you using?  
Docker image alpine (custom build)

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Bash

**Comment by derekbekoe** [comment]
The `az` in the environment can only be executed from the environment as it calls the current python interpreter with `python -m azure.cli`.

Running `az-cli-venv/bin/python -m azure.cli` works though.

You can also achieve what you were after with something like the following:
```
echo "az-cli-venv/bin/python -m azure.cli \"\$@\"" > az
chmod +x ./az
./az
```

**Comment by derekbekoe** [comment]
@clarkbreyman We do not use `entry_points['console_scripts']` because the executable it creates has an import to `pkg_resources` and importing that package takes several milliseconds.

```
time python -c 'import pkg_resources'

real	0m0.340s
user	0m0.226s
sys	0m0.088s
```

**Comment by clarkbreyman** [comment]
@derekbekoe  - looks like https://github.com/pypa/setuptools/issues/510
