### ISSUE TITLE
Do not advertise http urls to install software

### ISSUE THREAD

**Issue by migueldeicaza** [Azure/azure-cli#394]
They are vectors for hijacking.

On the main README.md page, we ask people to do this:

    curl http://azure-cli-nightly.westus.cloudapp.azure.com/install | bash

**Comment by JasonRShaver** [comment]
Great point!  We'll look to address this.

As an FYI, this is a point-in-time solution until we stand-up our idiomatic installs (brew, apt, yum, msi).

**Comment by JasonRShaver** [comment]
Opened issues for this work (#644, #645, #643)
