### ISSUE TITLE
Webapp deployment user set has cryptic errors

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#3940]
### Description
`az webapp deployment user set --user-name <username> --password <password>` 

the error messages when this command fails are not intuitive – Bad request means create a stronger password and Conflict. Details: 409 means your username is taken.  Can we get some some errors in here that don't require googling to figure out?

**Comment by yugangw-msft** [comment]
This is really the same thing like #1007. webapp's error model is not ARM conforming

**Comment by mayurid** [comment]
@jasonrshaver: please work on collecting these service attention issues and work with service team on them.
feel free to discuss with me a proposed plan.

**Comment by yugangw-msft** [comment]
@williexu, can you apply a workaround to extract out the real error. Multiple customers are complaining on this, so we should do something. We can still keep the issue open for service team to follow up

```json
b'{"Code":"BadRequest","Message":"The specified password does not meet the minimum requirements. The password should be at least eight characters long and must contain lowercase and uppercase letters and numbers.","Target":null,"Details":[{"Message":"The specified password does not meet the minimum requirements. The password should be at least eight characters long and must contain lowercase and uppercase letters and numbers."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"58010","MessageTemplate":"The specified password does not meet the minimum requirements. The password should be at least eight characters long and must contain lowercase and uppercase letters and numbers.","Parameters":[],"Code":"BadRequest","Message":"The specified password does not meet the minimum requirements. The password should be at least eight characters long and must contain lowercase and uppercase letters and numbers."}}],"Innererror":null}'
```
