### ISSUE TITLE
Migrate dependencies to external core package

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#3942]
Many parts of azure.cli.core have been moved to an external package.  Move dependencies over to that package and remove the duplicate code from the CLI.

**Command Modules to Convert**

- [x] redis
- [x] profile
- [x] cloud
- [x] feedback
- [x] configure
- [x] extension
- [x] resource
- [x] cdn
- [x] interactive
- [x] network
- [x] role
- [ ] vm
- [ ] rdbms

-------------
- [ ] acr
- [ ] acs
- [ ] appservice
- [ ] backup
- [ ] batch
- [ ] batchai
- [ ] billing
- [ ] cognitiveservices
- [ ] consumption
- [ ] container
- [ ] cosmosdb
- [ ] dla
- [ ] dls
- [ ] eventgrid
- [ ] find
- [ ] iot
- [ ] keyvault
- [ ] lab
- [ ] monitor
- [ ] servicefabric
- [ ] sql
- [ ] storage

**Comment by tjprescott** [comment]
cc/ @derekbekoe, @mayurid

**Comment by derekbekoe** [comment]
See also https://github.com/Azure/azure-cli/issues/838

**Comment by tjprescott** [comment]
Moving this forward to Sprint 21 since knack work will likely need to be done before I can return to this for the third phase of changes.

**Comment by tjprescott** [comment]
Continuing work into sprint 22 (and likely into 24 and beyond!)

**Comment by tjprescott** [comment]
Closing this as we now have a project with each of these tracked as individual issues.
