### ISSUE TITLE
VM creation failing?

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#3951]
### Description

`az vm create -g myrg -n ubuntu2 --image UbuntuLTS`

I run a simple VM create command but then the deployment fails.

```
Deployment failed. {
  "error": {
    "code": "BadRequest",
    "target": "vm.properties.storageProfile.osDisk.managedDisk",
    "message": "Could not find member 'managedDisk' on object of type 'OSDisk'. Path 'properties.storageProfile.osDisk.managedDisk', line 1, position 252."
  }
}
```

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
`interactive script`

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
```
azure-cli (2.0.9)

acr (2.0.7)
acs (2.0.9)
appservice (0.1.9)
batch (3.0.2)
billing (0.1.2)
cdn (0.0.5)
cloud (2.0.5)
cognitiveservices (0.1.5)
command-modules-nspkg (2.0.0)
component (2.0.6)
configure (2.0.9)
consumption (0.1.2)
core (2.0.10)
cosmosdb (0.1.9)
dla (0.0.9)
dls (0.0.9)
feedback (2.0.5)
find (0.2.5)
interactive (0.3.5)
iot (0.1.8)
keyvault (2.0.7)
lab (0.0.7)
monitor (0.0.7)
network (2.0.9)
nspkg (3.0.0)
profile (2.0.7)
rdbms (0.0.4)
redis (0.2.6)
resource (2.0.9)
role (2.0.7)
sf (1.0.4)
sql (2.0.6)
storage (2.0.9)
vm (2.0.9)

Python (Darwin) 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]

Python location '/Users/debekoe/lib/azure-cli/bin/python'
```

**OS Version:** What OS and version are you using?  
`macOS Sierra`

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
`bash`

**Comment by derekbekoe** [comment]
I also saw this error on the prev. version of the CLI before updating.
```
At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. {
  "error": {
    "code": "BadRequest",
    "target": "vm.properties.storageProfile.osDisk.managedDisk",
    "message": "Could not find member 'managedDisk' on object of type 'OSDisk'. Path 'properties.storageProfile.osDisk.managedDisk', line 1, position 252."
  }
}
```

**Comment by tjprescott** [comment]
Did you re-run dev_setup to get the latest compute SDK?

**Comment by derekbekoe** [comment]
@tjprescott I'm using the latest shipped code.

**Comment by tjprescott** [comment]
I think I got similar errors after pulling the latest code until I re-ran dev_setup--then they went away. 

Try running the command with --validate --verbose to get the ARM template. It should give a clue as to the problem.

**Comment by yugangw-msft** [comment]
Sync'd to the tip of master, ran dev_setup, tried the command and it worked

**Comment by derekbekoe** [comment]
Hmm it's working for me now.

**Comment by J1nFr34ks** [comment]
I'm new to Azure CLI and I have the same problem, how can I ran dev_setup ?
