### ISSUE TITLE
[WebApp] Delete command should be more transparent about deleting plans

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#3958]
### Description

If you call the `az webapp delete` command, and the specified webapp instance is the only one within the App Service plan, then it will delete the plan as well. Personally, I found this behavior pretty confusing (since you have no way of knowing it's happening), but more importantly, it wasn't what I wanted at all, so I had to re-create the plan again.

The portal makes this behavior pretty clear when you're attempting to delete a web app instance, and it also allows you to prevent deleting the plan. It would be great if the CLI allowed suppressing the plan deletion behavior (some new flag?) and/or maybe it would make sense to display a prompt that notifies the user that they're about to delete the only web app, and ask whether they'd like to also delete the plan. That way, the behavior is clear and predictable.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: nightly

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: nightly

**OS Version:** What OS and version are you using?  
Answer here: macOS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by yugangw-msft** [comment]
Yes, we can expose a flag for this.

**Comment by tjprescott** [comment]
This seems similar in concept to #3922. We should aim for a consistent solution.

**Comment by yugangw-msft** [comment]
It is a bit different, that the API supports this through a flag but CLI doesn't expose it
