### ISSUE TITLE
Need helpful errors for webapp deployment user set

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#3959]
### Description
`az webapp deployment user set --user-name <username> --password <password>` 

the error messages when this command fails are not intuitive – Bad request means create a stronger password and Conflict. Details: 409 means your username is taken.  Can we get some some errors in here that don't require googling to figure out?

**Comment by yugangw-msft** [comment]
You have already opened #3940

**Comment by yugangw-msft** [comment]
Also this is a service side issue. //cc: @johanste to surface this up to service team
