### ISSUE TITLE
[KeyVault] Newest CLI versions missing "all" option for az keyvault set-policy command

### ISSUE THREAD

**Issue by mabicca** [Azure/azure-cli#3970]
### Description
In the past we had instructions to use the parameter all when specifying permissions for key/secret:

Currently, that option is not available, so at the moment you need to type all options separated by space.

This is the output of the help on CLI 2.0.9+DEV

   --key-permissions        : Space separated list. Possible values: encrypt, decrypt, wrapKey,
                               unwrapKey, sign, verify, get, list, create, update, import, delete,
                               backup, restore, recover, purge.
    --secret-permissions     : Space separated list. Possible values: get, list, set, delete,
                               backup, restore, recover, purge.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: docker as well as the built-in CLI on Azure portal

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

azure-cli (2.0.9+dev)

acr (2.0.7+dev)
acs (2.0.9+dev)
appservice (0.1.9+dev)
batch (3.0.2+dev)
billing (0.1.2+dev)
cdn (0.0.5+dev)
cloud (2.0.5+dev)
cognitiveservices (0.1.5+dev)
command-modules-nspkg (2.0.0+dev)
component (2.0.6+dev)
configure (2.0.9+dev)
consumption (0.1.2+dev)
core (2.0.10+dev)
cosmosdb (0.1.9+dev)
dla (0.0.9+dev)
dls (0.0.9+dev)
feedback (2.0.5+dev)
find (0.2.5+dev)
interactive (0.3.5+dev)
iot (0.1.8+dev)
keyvault (2.0.7+dev)
lab (0.0.7+dev)
monitor (0.0.7+dev)
network (2.0.9+dev)
nspkg (3.0.0+dev)
profile (2.0.7+dev)
rdbms (0.0.4+dev)
redis (0.2.6+dev)
resource (2.0.9+dev)
role (2.0.7+dev)
sf (1.0.4+dev)
sql (2.0.6+dev)
storage (2.0.9+dev)
taskhelp (0.1.4+dev)
vm (2.0.9+dev)

Python (Linux) 3.5.2 (default, Dec 27 2016, 21:33:11)
[GCC 5.3.0]

Python location '/usr/local/bin/python'

**OS Version:** What OS and version are you using?  
Answer here: OSX 10.11.6 (El Capitan) and Docker 17.06.0-ce-mac18 (18433)

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash on OSX

**Comment by tjprescott** [comment]
Do you know which version had the "all" parameter?

**Comment by mabicca** [comment]
Hi @tjprescott , I noticed that version 2.0.6 had it. Not sure if we need to reintroduce that but we just have to be sure that is documented properly.

**Comment by tjprescott** [comment]
Hi @mabicca it looks like in the newest API version of the KeyVault management plane, they removed "all" as a valid option for these enums.  I've opened an issue against the REST API specs (https://github.com/Azure/azure-rest-api-specs/issues/1394) to get resolution on whether the new API version truly doesn't support "all" or whether it was accidentally removed.

**Comment by tjprescott** [comment]
cc/ @schaabs. If "all" is no longer supported by the service, it would likely make sense to support it with custom logic in the KeyVault convenience layer or, at a minimum, in the CLI.

**Comment by schaabs** [comment]
@tjprescott The "all" permission was intentionally removed in this API version when we added the purge permission. This was to avoid users unintentionally assigning the purge permission to users, and force them to be explicit.

**Comment by tjprescott** [comment]
Thanks @schaabs.  Based on this, I'm going to close this issue as I don't see any instances of "all" being used in the CLI help documentation.
