### ISSUE TITLE
Split Azure Interactive command module's core and UI logics.

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#3980]
This issue is inspired by PR https://github.com/Azure/azure-cli/pull/3360. After discussed with @chrmarti I realize that both az interactive shell and az cli vs code extension depends on a common set of core functionalities:
1. load command table;
2. arguments completer;
3. profile management.

If we split the UI logic from the core logic in az interactive shell, the core logic can be exposed as tooling API for 3rd party, such as Azure CLI VS Code extension to consume. 

This also helps to improve the az interactive shell's code quality and maintainability.

**Comment by tjprescott** [comment]
@troydai is this adequately addressed by the API file?  If not this should be reopened.
