### ISSUE TITLE
The pains in copying web contents

### ISSUE THREAD

**Issue by elibarzilay** [Azure/azure-cli#3983]
(This is basically an extended feature request list.  To skip to it, see
under the bar.)

I've been hacking on some script that copies a bunch of web pages
(generated api documentation pages) to blob storage, which is possible,
but painful.  What I wanted to do is:

1. Use proper content types
2. Serve a default html file when visiting `.../foo/` instead of forcing
   `.../foo/index.html`
3. Optionally have generated default index pages when such a file does
   not exist.
4. Make `.../foo` redirect the browser to `.../foo/` which would then be
   the above default page.

The way that I achieved all of this is with a pile of hacks:

1. Iterate over a manually-made list of glob patterns and matching
   content types, using `--pattern` to copy only the respective subset
   of files with a correct type.  (This needs to be done carefully,
   keeping account of paths in case new file types are added in the
   future.)
2. For each case where there's a directory with an `index.html` file,
   copy that file to a blob name that looks like `.../dirname/`.
3. A manual pre-scan of the whole directory generates a simple
   `index.html` in directories that don't have one.
4. Finally, for each directory `foo/bar` I upload an html file that is
   called `foo/bar` with a
       <meta http-equiv="refresh" content="0; url=bar/" />
   which works, except that it makes the browser show the stub html for
   a brief moment before jumping on (and it also doesn't work with
   things like `curl`).

Note that this means one `az` use for each type, and two more for each
directory, which means a significant overall time, almost completely
spent in the ~2 second overhead for each such use!

---

My feature requests are therefore:

* A way to specify "use the right content type based on file names"
* A way to serve some default sub-blob for requests for `foo/bar/` paths
  that end with a slash.
* I know that dealing with the redirections is too big for a quick
  feature request, but it would be much better if the [list of http properties](https://docs.microsoft.com/en-us/rest/api/storageservices/setting-and-retrieving-properties-and-metadata-for-blob-resources#a-namesubheading3a-standard-http-properties-for-containers-and-blobs)
  that can be set on blobs would include `Location`, and the existence
  of that header would also make the blob serve with a 307 status.  This
  will even make it a good substitute for creating "symlink"-like blobs.
  (It could also be used for serving a default file.)

  If this was implemented as part of the above "use the right type", it would
  be a significant step towards making it possible to host html content in
  blob storage.

**Comment by williexu** [comment]
@troydai can you look at this

**Comment by williexu** [comment]
@seguler is there any plan on the service-side to support any of these features?

**Comment by pemari-msft** [comment]
We have supported this:
``A way to serve some default sub-blob for requests for foo/bar/ paths
that end with a slash.``

and this:
`` dealing with the redirections`` is in our backlog. Sorry for the missed response.

**Comment by elibarzilay** [comment]
@pemari-msft, I see that the first bullet works with a random jpeg, and I'm happy that redirections are planned.

But I still don't see serving `some/path/index.html` when browsing `some/path/`.  If you're talking about the special `$web` blob, than that's different since it forces moving blobs...
