### ISSUE TITLE
Bad or no error handling during for "az sf cluster"

### ISSUE THREAD

**Issue by zopyx** [Azure/azure-cli#3984]
### Description

```
 az --verbose sf cluster select  --endpoint https://xxxx.westeurope.cloudapp.azure.com:19080 --no-verify --pem XXXX.pem
```

does not perform any error checking or does not give any feedback when you specify an improper non-existing argument for --pem

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

```
curl -L https://aka.ms/InstallAzureCli | bash
```

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
```
az --version
azure-cli (2.0.9)

acr (2.0.7)
acs (2.0.9)
appservice (0.1.9)
batch (3.0.2)
billing (0.1.2)
cdn (0.0.5)
cloud (2.0.5)
cognitiveservices (0.1.5)
command-modules-nspkg (2.0.0)
component (2.0.6)
configure (2.0.9)
consumption (0.1.2)
core (2.0.10)
cosmosdb (0.1.9)
dla (0.0.9)
dls (0.0.9)
feedback (2.0.5)
find (0.2.5)
interactive (0.3.5)
iot (0.1.8)
keyvault (2.0.7)
lab (0.0.7)
monitor (0.0.7)
network (2.0.9)
nspkg (3.0.0)
profile (2.0.7)
rdbms (0.0.4)
redis (0.2.6)
resource (2.0.9)
role (2.0.7)
sf (1.0.4)
sql (2.0.6)
storage (2.0.9)
vm (2.0.9)

Python (Linux) 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]

Python location '/home/ajung/lib/azure-cli/bin/python'
```

**OS Version:** What OS and version are you using?  

Ubuntu 16.04

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  

Bash

**Comment by samedder** [comment]
We've considered adding this enhancement and it is planned for the next release of the Service Fabric commands.
