### ISSUE TITLE
Easier login experience

### ISSUE THREAD

**Issue by jaraco** [Azure/azure-cli#3987]
### Description

Each time I enter `az login`, I then automatically take several actions:
- copy the code to the clipboard
- launch my default browser
- enter the URL into the browser

There's no reason the client couldn't do these three things for me, using [jaraco.clipboard](https://pypi.org/project/jaraco.clipboard/) or similar for clipboard functionality and other techniques for launching a browser. Or even better if the browser could be launched with the code in the URL, saving the paste action also.

I suspect such a feature should only be enabled opt-in (as parameters to `login` command).

Thoughts?

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.10 (though `az --version` fails due to another bug)

**OS Version:** What OS and version are you using?  
Answer here: macOS 10.12.5

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: zsh

**Comment by yugangw-msft** [comment]
Launching a browser is not hard. We are discussing with AAD team for auto-filling the code.

**Comment by yugangw-msft** [comment]
This has been addressed since June

**Comment by jaraco** [comment]
I noticed. Thank you!
