### ISSUE TITLE
Add key to App registration in Azure Active Directory

### ISSUE THREAD

**Issue by magol** [Azure/azure-cli#3996]
### Description
I try to script the process to create my environment in Azure, but I can not find how I do to add a key to a app in the Azure Active Directory. 

To add a key, I have to use the GUI like this:
 1. Go til Azure Active Directory
 2. Select App registration and select my app
 3. Select Keys
 4. Give a "Key description" and press Save
 5. Copy the generated value

Or is it any way to do this with Azure CLI?

---

### Environment summary

**Install Method:** 
Manualy with https://aka.ms/InstallAzureCliWindows 

**CLI Version:** 

> azure-cli (2.0.8)
> 
> acr (2.0.6)
> acs (2.0.8)
> appservice (0.1.8)
> batch (3.0.1)
> billing (0.1.1)
> cdn (0.0.4)
> cloud (2.0.4)
> cognitiveservices (0.1.4)
> command-modules-nspkg (2.0.0)
> component (2.0.5)
> configure (2.0.8)
> consumption (0.1.1)
> core (2.0.8)
> cosmosdb (0.1.8)
> dla (0.0.8)
> dls (0.0.8)
> feedback (2.0.4)
> find (0.2.4)
> interactive (0.3.4)
> iot (0.1.7)
> keyvault (2.0.6)
> lab (0.0.6)
> monitor (0.0.6)
> network (2.0.8)
> nspkg (3.0.0)
> profile (2.0.6)
> rdbms (0.0.3)
> redis (0.2.5)
> resource (2.0.8)
> role (2.0.6)
> sf (1.0.3)
> sql (2.0.5)
> storage (2.0.8)
> vm (2.0.8)
> 
> Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
> 
> Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'

**OS Version:** 
Windows 7

**Shell Type:** 
PowerShell

**Comment by tjprescott** [comment]
@yugangw-msft

**Comment by yugangw-msft** [comment]
Try `az ad sp reset-credentials`

**Comment by magol** [comment]
@yugangw-msft Thanks for you answer. Now I know how I generate a new password for a key. But how do I create a new key? I have test the parameters, but can not figure out how I should do

**Comment by yugangw-msft** [comment]
`key` is the `password`, same thing. Portal uses `key`, but the graph directory api underneath uses the term of `password credential`, and the `key credential` is meant for certificate based creds, a different thing. Yes, confusing.
The subtle part is do you want to add new `password` and keep the old ones? If yes, then `reset-credentials` might not do you like as it just overwrites old ones.

**Comment by yugangw-msft** [comment]
Please re-activate if you have more questions.

**Comment by datavirtue** [comment]
For anyone who happens upon this thread from a search as I did...

It seems there is no way to add a certificate key credential to an existing application registration in the graphical portal for Azure.  This required step is highlighted in the "automation authentication 8 steps blog post." 

https://blogs.technet.microsoft.com/keithmayer/2016/03/26/8-steps-for-using-azure-ad-service-principal-certificate-authentication-with-azure-automation-powershell-workflow-runbooks/

In that post they create a registered app in Azure AD and assign a key credential from a self-signed certificate via powershell.  Presumably, once you know the JSON format of the key credential you might be able to generate it and edit the manifest in the portal directly.  

![image](https://user-images.githubusercontent.com/1112636/32584811-4d80bc72-c4c8-11e7-999c-d4f7cd09cb7a.png)

**Comment by yugangw-msft** [comment]
I am updating CLI to support this through the new flag of `--append`, e.g.
```bash
az ad sp reset-credentials -n <myapp-id> -p mypassword --append
az ad sp reset-credentials -n <myapp-id> --cert @mycertfile --append 
```
