### ISSUE TITLE
Not able to list "Web App On Linux"

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#4000]
The websites created on Linux app service plan can't be listed using `webapp list` command.
```
21:22 $ az webapp list -ojson
[]
```

![screen shot 2017-07-10 at 9 23 51 pm](https://user-images.githubusercontent.com/1329240/28050998-1c360594-65b6-11e7-898e-76e92290cf41.png)

The app service plan can be listed correctly:
```
21:22 $ az appservice plan list 
Kind    Location      MaximumNumberOfWorkers  Name       NumberOfSites  ProvisioningState    Reserved    ResourceGroup        Status
------  ----------  ------------------------  -------  ---------------  -------------------  ----------  -------------------  --------
linux   West US                            3  plan-s1                1  Succeeded            True        trdai-exp-permanent  Ready
```

@yugangw-msft 

I'm on latest dev code / Mac OS.

**Comment by yugangw-msft** [comment]
This is a server breaking change, that the app type for linux webapp was changed over to `app,linux`, which breaks the client side filter.  Let me double check with them before fix this.
Note, linux webapp is not GA yet

**Comment by akanieski** [comment]
Has the fix for this been released in Azure SDK 2.x yet? If so which version?
