### ISSUE TITLE
Consider remove jsonc output formatter

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#4002]
There are existing tools to colorize the json output. For example, `az ad user list | jq` generated colorized results as well.
![screen shot 2017-07-11 at 12 17 13 pm](https://user-images.githubusercontent.com/1329240/28086152-e48f7300-6632-11e7-9c2a-58fa00d5478b.png)

This can reduce the number of dependencies and simplify the output logic. In addition, this reduce the chances that issues caused by color marks.

**Comment by derekbekoe** [comment]
At this point, it's unlikely we'll remove jsonc so closing but you're welcome to re-open...

**Comment by troydai** [comment]
Should we take a look at the telemetry to see if anyone is actually using jsonc?
