### ISSUE TITLE
Check my resources quanta limit

### ISSUE THREAD

**Issue by liorbiu** [Azure/azure-cli#4011]
### Description
I would like to know how can I get my resources quanta limit, i.e. check how many VMs (or cores) I can create?, check how many public IP addresses I can create?

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: apt-get

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.7)

**OS Version:** What OS and version are you using?  
Answer here: Ubuntu 16.04.2 LTS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by yugangw-msft** [comment]
Check out `az vm list-usage` and `az network list-usages`, which should address the scenarios you mentioned.
We don't have one command outputing everything

**Comment by liorbiu** [comment]
@yugangw-msft Thank you, this is exactly what i looked for!
