### ISSUE TITLE
`az storage blob list` should clarify the meaning of `--prefix`

### ISSUE THREAD

**Issue by elibarzilay** [Azure/azure-cli#4013]
The description of `--prefix` is pretty straightforward, but I think
that it would be better if there was an additional warning there saying
that it is just a plain *literal prefix*.  In other words, it should
clarify that a listing with `--prefix foo` would show all of `foo`,
`foo2`, and `foo/bar` (when they exist, of course).

This would be helpful in avoiding an illusion that this is a similar
operation to getting a list of files in a directory.  (Something that I
think is impossible with azure storage due to its flat namespace
design.)

**Comment by williexu** [comment]
Customers should be aware from the online docs that blob storage(as opposed to file storage) is inherently flat. 
The description for the parameter- "Filters the results to return only blobs whose names begin with the specified prefix." should suffice to let users understand the behavior.
Closing this for now.

**Comment by elibarzilay** [comment]
@williexu, the thing is that many people will use it without looking at the online docs, and therefore my suggestion was a minimal number of examples that would make it very clear.  I think that the cost of two more lines in the help description is worth in avoiding potential confusion.

**Comment by williexu** [comment]
@elibarzilay I see your point, I've raised an issue and will address it in our next sprint.

**Comment by elibarzilay** [comment]
Thanks!
