### ISSUE TITLE
Add generate container CI URL for Web App on Linux

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-cli#4023]
### Description
**Outline the issue here:**
No command to generate container CI URL for Web App on Linux
---

**Comment by yugangw-msft** [comment]
Could you please elaborate the detail logic here?

**Comment by ahmedelnably** [comment]
To setup CI/CD for custom containers for Web App on Linux you need to configure DockerHub or ACR with a webhook URL to send the change notifications to.
To generate that URL the customer need to download their publishing profile and format the URL carefully, this is explained here: https://docs.microsoft.com/en-us/azure/app-service-web/app-service-linux-ci-cd#step-3---prepare-webhook-url

using the new command this will be no longer the case, as the output of the command can be directly used to configure an ACR webhook
https://docs.microsoft.com/en-us/cli/azure/acr/webhook#create

**Comment by yugangw-msft** [comment]
Got it, should the command also expose the argument to enable `DOCKER_ENABLE_CI`?

**Comment by ahmedelnably** [comment]
We were thinking about having this is a get/show command. and have another command to enable the app setting.

General guidance in the command design will be really appreciated.

**Comment by yugangw-msft** [comment]
if 2 steps are usually done at the same time, then it is unnecessary to split into 2 separate commands. Users are mostly scenario(task) driven, so would appreciate simplicity. BTW the existing command doing this kind of thing is `az webapp deployment source config`.  Should we update it or are you considering new commands?

**Comment by ahmedelnably** [comment]
@aspaan has a PR out: https://github.com/Azure/azure-cli/pull/4044

The command we are proposing is: 'webapp deployment list-container-cd-url'

**Comment by yugangw-msft** [comment]
This command is fine. Still I would suggest we follow up on end to end configuration. For ACR, if not mistaken, CLI can handle it completely for users.

**Comment by aspaan** [comment]
Just had a chat with Ahmed. How about something like this _az webapp deployment container config --enable-cd true_

**Comment by yugangw-msft** [comment]
` az webapp deployment container` looks good, i assume the new command of getting the container cd url will also go there?

**Comment by ahmedelnably** [comment]
the original idea was to return the url when you enable the feature,
but on second thought, it would be a good idea to add another command just to return the url

`az webapp deployment container show-container-cd-url`

**Comment by yugangw-msft** [comment]
Agreed

**Comment by yugangw-msft** [comment]
fixed
