### ISSUE TITLE
False positive from devicelogin

### ISSUE THREAD

**Issue by dazdaz** [Azure/azure-cli#4028]
### Description
False authentication positive reported via devicelogin from az cli 2.10.
I run az login, copy the code into aka.ms/devicelogin, enter my account details and receive a successful authentication report, however I cannot execute any az commands, as i'm told to run 'az login' again. 

I installed Ubuntu 17.04 to see if a fresh OS and different distribution makes a difference, azure-cli 2, and also receive the same issue.

### Environment summary

**Install Method:** curl -L https://aka.ms/InstallAzureCli | bash

**CLI Version:** 2.10

**OS Version:** RHEL 7.3 & Ubuntu 17.04

**Shell Type:** BASH 4.2.46

**Comment by yugangw-msft** [comment]
Does your account have subscriptions? if yes, maybe you can share the verbose log (`--debug`) and let me take a look?

**Comment by dazwork** [comment]
Emailed you the debug log. Let me know if I can provide further info. Not being able to use Azure CLI is a major issue for me. Thx

**Comment by yugangw-msft** [comment]
Thanks. I have recommended you open an internal ticket to let AAD ESTS take a look.

**Comment by yugangw-msft** [comment]
I am closing this since you have an internal ticket opened
