### ISSUE TITLE
Unable to create VM using Azure CLI 2.0

### ISSUE THREAD

**Issue by itzrahulsoni** [Azure/azure-cli#4038]
### Description
I am unable to use the following command to create a VM using Azure CLI 2.0

az vm create -g $resource_group \
-n $dc_vm -l $location --admin-username $admin \
--admin-password $password --attach-os-disk $dc_disk \
--authentication-type password --availability-set $availability_set \
--image Win2012R2Datacenter --license-type Windows_Client \
--nics $dc_nic  --os-type Windows

I get an error message > incorrect usage: --image IMAGE | --attach-os-disk DISK

My resources are all set up individually, and I have created an empty managed disk. All I need is to use a product image (Windows Server 2012 R2 Datacenter) to create a VM. Seems like I am doing something wrong. Please suggest.

### Environment summary
**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.9)

**OS Version:** What OS and version are you using?  
Answer here: macOS Sierra 10.12.6 

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Bash

**Comment by tjprescott** [comment]
You cannot use `--attach-os-disk` and `--image` together.  You should remove `--image` if you are using an existing OS disk.

**Comment by yugangw-msft** [comment]
i think the current document is enough, so close it?
