### ISSUE TITLE
Travis CI needs to include tests for 2017-03-09-profile

### ISSUE THREAD

**Issue by viananth** [Azure/azure-cli#4039]
### Description
Travis CI runs tests only for profile "latest"
It should also support running tests for profile "2017-03-09-profile"
Its a test blocker for Azure Stack. Having Travis CI run tests for "2017-03-09-profile" helps us catch breaks in Stack immediately.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

**OS Version:** What OS and version are you using?  
Answer here:

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

**Comment by osule** [comment]
I think this was already resolved after looking in the `.travis.yml` 
and `test_automation.sh` and one of the builds in Travis CI.


https://github.com/Azure/azure-cli/blob/dev/.travis.yml#L52-L56

    - stage: verify
      env:
      - PURPOSE='Automation'
      - REDUCE_SDK='True'
      - AZURE_CLI_TEST_TARGET_PROFILE='2017-03-09'
      script: ./scripts/ci/test_automation.sh

**Comment by viananth** [comment]
Yes, this issue was resolved using https://github.com/Azure/azure-cli/pull/7122
