### ISSUE TITLE
Curl install on RHEL 7.3 encounters "command not found"

### ISSUE THREAD

**Issue by JanaJensen** [Azure/azure-cli#4040]
### Description
**Outline the issue here:**

sudo curl -L https://aka.ms/InstallAzureCli | bash
results in:
bash: line 33: /tmp/azure_cli_install_tmp_5U1E: Permission denied

So I tried this:
sudo bash /tmp/azure_cli_install_tmp_5U1E
resulted in a whole bunch of "command not found" on things like "from", "import", "try".

How should I be invoking this?

Attached is my terminal session with all of the output.
[Terminal Saved Output - AzureCLI install.txt](https://github.com/Azure/azure-cli/files/1157053/Terminal.Saved.Output.-.AzureCLI.install.txt)

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: Curl

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: Whatever is at https://aka.ms/InstallAzureCli today

**OS Version:** What OS and version are you using?  
Answer here: Red Hat Enterprise Linux Server release 7.3 (Maipo)

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by derekbekoe** [comment]
@JanaJensen It's a Python script so `sudo bash /tmp/azure_cli_install_tmp_5U1E` wouldn't work.
You can use `sudo /tmp/azure_cli_install_tmp_5U1E` and the script will find a version of python on the machine and use that.
Alternatively, `sudo python /tmp/azure_cli_install_tmp_5U1E` and you specify your own python executable by replacing `python` to another python.

**Comment by JanaJensen** [comment]
Thank you! That worked!
