### ISSUE TITLE
make --name and --file optional for az storage upload and download

### ISSUE THREAD

**Issue by jeongyoonlee** [Azure/azure-cli#4045]
### Description
**Outline the issue here:**
Azure CLI requires much longer commands than AWS CLI. Making `--name` in `az storage upload` and `--file` in `az storage download` optional will help.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: apt install

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.10

**OS Version:** What OS and version are you using?  
Answer here: Ubuntu 16.04

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by mayurid** [comment]
@troydai to comment.

**Comment by troydai** [comment]
@jeongyoonlee thanks for opening this issue. I assume you're talking about `az storage blob upload / download` command, because its has both `--name` and `--file` parameter. In both scenarios, without specifying the `file`, which represents the desination, or `name` which represents the source, the command can't guess what action to take.

Can you please elobrate your idea a bit further by show me an example? Thanks.

**Comment by jeongyoonlee** [comment]
@troydai Thanks for looking into it. 

For comparison, with AWS CLI, the destination file name is optional and a directory or a bucket name can be given instead :
```bash
$ aws s3 cp local-file.txt s3://bucket-name/
$ aws s3 cp s3://bucket-name/local-file.txt .
```
Meanwhile, with Azure CLI, both source and destination file names need to be given explicitly even if those are the same:
```bash
$ az storage blob upload --file local-file.txt --name local-file.txt --container-name container-name
$ az storage blob download --name local-file.txt --file local-file.txt --container-name container-name
```
Note that how much longer the commands with Azure CLI are than the same commands with AWS CLI.

Thanks!

**Comment by troydai** [comment]
@jeongyoonlee thanks for the examples. On paper, the simple example does stand. However, when the source or destination paths are more than a file name, the users' expectation may vary. For example, should the same folder hierarchy be created at the destination?

But this is a good suggesiton. I'll work with Azure Storage team to see what's the best approach to improve the commands. Thank you.

I'll leave this issue open and add to the backlog. And I will start a conversation with the stakeholders.

**Comment by williexu** [comment]
@jeongyoonlee you might be interested in one of our new extensions: az alias

Provided you have a minimum cli version of 2.0.28, you can install Alias with `az extension add --name alias` and start creating your own custom commands. Check out the [blog post](https://github.com/chewong/azure-cli-alias-extension/blob/dev/doc/az-alias-blog-post.md#working-with-the-alias-extension) for further details.

**Comment by williexu** [comment]
Closing this from lack of discussion and mitigation using the alias extension.
In addition, any major changes in our command formats will break users.
