### ISSUE TITLE
Warn users when CLI is out of date (esp for bug fixed commands)

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#4046]
### Description
**Outline the issue here:**

Saw a user mention on Twitter that they had struggled with a particular `az` command and it turned out it was due to an old version of CLI (presumably newer versions included a bugfix). It would be nice if the CLI warned users, either, when:

1. the CLI is out of date
2. there is a known bugfix for a particular command being executed in the CLI

The first one certainly seems easier, but might be considered a nuisance by people.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: n/a

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: n/a

**OS Version:** What OS and version are you using?  
Answer here: n/a

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: n/a

**Comment by troydai** [comment]
We can add a periodically check mechanism to CLI. But it won't fix the old CLI which we've already shipped since we can't patch old CLI when users don't know it is old.

**Comment by tjprescott** [comment]
This has been implemented as part of `az --version`.
