### ISSUE TITLE
[ACR] Creating managed registries doesn't appear to work

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#4050]
### Description

When I attempt to run the `az acr create` command,  and specify any of the `Managed_*` SKU options via the `--sku` flag, it spins for a few moments and then spits out the following error:

```
Deployment failed. {
  "error": {
    "code": "NoRegisteredProviderFound",
    "message": "No registered resource provider found for location 'westus' and API version '2017-06-01-preview' for type 'registries'. The supported api-versions are '2016-06-27-preview, 2017-03-01, 2017-06-01-preview'. The supported locations are 'westus, eastus, southcentralus, westeurope, northeurope, uksouth, ukwest, australiaeast, australiasoutheast, centralindia, eastasia, japaneast, japanwest, southeastasia, southindia, brazilsouth, canadaeast, canadacentral, centralus, eastus2, northcentralus, westcentralus, westus2'."
  }
}
```

If I set specify `--sku Basic`, then everything works great, but I'd really like to use a managed registry :) Am I doing something wrong? Any help would be greatly appreciated!

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: bash interactive script

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

azure-cli (2.0.10)

acr (2.0.8)
acs (2.0.10)
appservice (0.1.10)
batch (3.0.3)
billing (0.1.3)
cdn (0.0.6)
cloud (2.0.6)
cognitiveservices (0.1.6)
command-modules-nspkg (2.0.1)
component (2.0.6)
configure (2.0.10)
consumption (0.1.3)
core (2.0.11)
cosmosdb (0.1.10)
dla (0.0.10)
dls (0.0.10)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.6)
iot (0.1.9)
keyvault (2.0.8)
lab (0.0.8)
monitor (0.0.8)
network (2.0.10)
nspkg (3.0.1)
profile (2.0.8)
rdbms (0.0.5)
redis (0.2.7)
resource (2.0.10)
role (2.0.8)
sf (1.0.5)
sql (2.0.7)
storage (2.0.10)
vm (2.0.10)

Python (Darwin) 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]

Python location '/Users/joncart/lib/azure-cli/bin/python'

**OS Version:** What OS and version are you using?  
Answer here: macOS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by djyou** [comment]
@lostintangent Thank you for trying out managed registries.
Basic SKU is globally available but managed registries is a preview feature that is available in three regions `West Central US`, `East US`, and `West Eurpoe`.
ARM however returns a bad error message too in this case. @tjprescott What is a good way for this scenario besides hard code the three regions? /cc @SajayAntony

**Comment by lostintangent** [comment]
@djyou Ah OK, using `westcentralus` fixed it! Thanks for that clarification :)

**Comment by djyou** [comment]
@tjprescott Can you please close this issue as the service has been available in all regions? Thanks.
