### ISSUE TITLE
How to check the status of a Function?

### ISSUE THREAD

**Issue by blueelvis** [Azure/azure-cli#4066]
### Description
Is it possible to get the details of the Function when it runs? For example, when the Function runs, we get access to it's unique ID, so is there any way to find the status of the function using that ID as in did it complete successfully or did it just crash?

Was asked to file an issue over here - https://www.reddit.com/r/AZURE/comments/6og5am/how_can_i_check_the_status_of_an_azure_function/dkivz8x/
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
azure-cli (2.0.10)

acr (2.0.8)
acs (2.0.10)
appservice (0.1.10)
batch (3.0.3)
billing (0.1.3)
cdn (0.0.6)
cloud (2.0.6)
cognitiveservices (0.1.6)
command-modules-nspkg (2.0.1)
component (2.0.6)
configure (2.0.10)
consumption (0.1.3)
core (2.0.11)
cosmosdb (0.1.10)
dla (0.0.10)
dls (0.0.10)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.6)
iot (0.1.9)
keyvault (2.0.8)
lab (0.0.8)
monitor (0.0.8)
network (2.0.10)
nspkg (3.0.1)
profile (2.0.8)
rdbms (0.0.5)
redis (0.2.7)
resource (2.0.10)
role (2.0.8)
sf (1.0.5)
sql (2.0.7)
storage (2.0.10)
vm (2.0.10)
Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'

**OS Version:** What OS and version are you using?  
Answer here: Windows 10 Enterprise 1703

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

**Comment by yugangw-msft** [comment]
//cc: @lindydonna

**Comment by lindydonna** [comment]
@blueelvis This isn't possible right now, because we don't have an API to check the execution status from an invocation ID. However, this feature is in our backlog. We can close this issue in favor of that one. See [Provide a host\-level API to get logs for a given invocation ID \#1329](https://github.com/Azure/azure-webjobs-sdk-script/issues/1329)

**Comment by blueelvis** [comment]
@lindydonna - Thanks a lot for the response. I am eagerly waiting for that feature :)


-Pranav
