### ISSUE TITLE
Enable dls progress controller

### ISSUE THREAD

**Issue by clehene** [Azure/azure-cli#4072]
### Description
This should report progress on transferred chunks (similar to blob store transfer)

```
Alive[#########################                                       ]  40.0881%
Finished[#############################################################]  100.0000%
```
Progress callback was added in dls master (0.0.14) https://github.com/Azure/azure-data-lake-store-python/commit/11f23b9ce381ad6353ad7019e3313a2e97c34aa2

**Comment by clehene** [comment]
@tjprescott I implemented the required functionality in the DLS SDK and it was merged and I  made a PR for this as well https://github.com/Azure/azure-cli/pull/4073
This said, it would require updating the DLS module to 0.0.14 or 0.0.15 (not sure how they cut releases) in which it will be available.

**Comment by tjprescott** [comment]
Once the PR is merged, it will automatically go into the subsequent release.

**Comment by clehene** [comment]
@tjprescott should I then make a PR here in order to upgrade DLS to that version (once it's published) as a prerequisite to this enablement?

**Comment by tjprescott** [comment]
So you updated the SDK version?  In that case, you would want to create a PR that bumps the version in your setup.py file.

**Comment by hmilkovi** [comment]
Is this released?

**Comment by clehene** [comment]
I believe so. You should be able to check by uploading a larger file or by
setting a smaller chunk size

**Comment by tjprescott** [comment]
Closing as this should be fixed. Please reopen if it has not.
