### ISSUE TITLE
Bash process substitution not working for az group deployment create

### ISSUE THREAD

**Issue by snebel29** [Azure/azure-cli#4074]
### Description
Hi,
Looks like the azure cli does not allow to load files from `named pipes`, a good example would be using [process substitution](http://wiki.bash-hackers.org/syntax/expansion/proc_subst) technique to produce the file through a command, like rendering a template with some external tool to then feed az-cli with it...

A trivial example to show the issue
```
$ az group deployment create \
    --name="mydeployment" \
    --resource-group="myresourcegroup" \
    --template-file=<( cat template.json ) \
    --parameters=<( cat parameters.json )
```
Will cause something like
```
Unable to parse parameter: /dev/fd/62
```
I've tracked the issue in the code to [here](https://github.com/Azure/azure-cli/blob/azure-cli-vm-2.0.9/src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_validators.py#L44)

As you can see the tool is only looking for regular files, but in the example I've provided a named pipe is given instead... This would be really awesome to have the possibility of reading from FIFO files so process substitution can be used with it.

I'd be really happy to create the PR myself once agreed on the approach, I was thinking on simply checking if isfile() for any OS or if OS linux if isfile() or isFifo() using something like

```
 import stat, os
 stat.S_ISFIFO(os.stat(path).st_mode)
```
This is also true that this functionality might be implemented for any parameter that should be a filein the whole scope of az-cli tool so further digging would be necessary ...

Let me know what you think about
---
### Environment
azure-cli-vm-2.0.9
Ubuntu 16.04.2TLS
GNU bash, version 4.3.48(1)-release

Thanks!

**Comment by snebel29** [comment]
Hi,
I also realize that for the `--template-file` parameters the same check is NOT in place hence is working perfectly, see [here](https://github.com/Azure/azure-cli/blob/azure-cli-vm-2.0.9/src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py#L335)

Making behavior consistent feels to me the right thing.

So other option to make things simple might be to just remove the isFile() check from `_try_load_file_object` on the _validators.py linked above.

Thanks! :-)

**Comment by tjprescott** [comment]
Hi @snebel29 sorry this issue got lost in the mix. You bring up a good point. We'll triage and try and get it scheduled accordingly.

**Comment by snebel29** [comment]
No worries, thanks

**Comment by yugangw-msft** [comment]
We will reconsider if we have more user voices. Right now, this is not a blocking issue, rather a few more lines for not mainline scenarios
