### ISSUE TITLE
Creation of network inbound rule does not work

### ISSUE THREAD

**Issue by lonesomegeek** [Azure/azure-cli#4090]
### Description
**Outline the issue here:**
When creating a new rule from the az cli, it is not working as expected. Here is the command executed:
`az network lb inbound-nat-rule create --lb-name X -g Y --protocol tcp --backend-port 37777 --frontend-port 37777 -n Z`

This is the error thrown:
`Property '/subscriptions/A/resourceGroups/Y/providers/Microsoft.Network/loadBalancers/X/frontendIPConfigurations/**swarmm-master-lbFrontEnd-54568498**' does not exist`

I've checked and this lb is created and working actually with 2 active rules. If I run the listing of the inbound rules with that command, it is listing me the two rules: 
`az network lb inbound-nat-rule list --lb-name X -g Y`

What am I doing wrong?
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: Docker

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.12+dev

**OS Version:** What OS and version are you using?  
Answer here: Windows 10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by lonesomegeek** [comment]
It is working with this image BTW: azuresdk/azure-cli-python:2.0.9

**Comment by tjprescott** [comment]
Hi @lonesomegeek I've confirmed this is a bug. If you supply the `--frontend-ip LoadBalancerFrontEnd` argument it will work.  If you omit this parameter it attempts to retrieve the value for you, and a bug in this logic is why it isn't working.
