### ISSUE TITLE
waagent ovf-env.xml file missing after 'waagent -deprovision+user -force'

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#4097]
### Description
**Outline the issue here:**
I prepare VHD-image of my VM.
After running 'waagent -deprovision+user -force' the file /var/lib/waagent/ovf-env.xml is deleted and is not recreated.
When I try to create VM from VHD-image VMAccessForLinux fails in creating new user.
I was able to get the disk of this VM, mount it to running VM and look at /var/log/waagent.log file - it throws an error of missing '/var/lib/waagent/ovf-env.xml' file.
How to fix it?

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
CLI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
root@Alexey-HP:/root# az --version | head -1
azure-cli (2.0.10)

**OS Version:** What OS and version are you using?  
Answer here:
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
Bash on Windows

**Comment by yugangw-msft** [comment]
This is not a CLI issue really, but did you follow the steps mentioned in the [document](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/capture-image)

**Comment by alexeyshishkin01** [comment]
yes, of course I did - pls. see description of the issue

**Comment by troydai** [comment]
@alexeyshishkin01 We didn't own `waagent`. Here's the repository you can open issue for this tool: https://github.com/Azure/WALinuxAgent. Thanks.

**Comment by alexeyshishkin01** [comment]
ok
