### ISSUE TITLE
Delete all resources related to machine

### ISSUE THREAD

**Issue by liorbiu** [Azure/azure-cli#4101]
### Description
Is there a way to delete ALL the resources related to machine when a vm is deleted? Including public ip address, nsg, nic, etc.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.12

**OS Version:** What OS and version are you using?  
Answer here: Ubuntu 16.04

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Bash

**Comment by yugangw-msft** [comment]
Please check out the pattern mentioned in #3902 and let me know whether that will help you. Basically you specify a tag when create the VM and then use `az resource delete` to clean them up

**Comment by tjprescott** [comment]
Currently we don't have a first-class way of doing this, but we have an open issue to address this across the CLI:
https://github.com/Azure/azure-cli/issues/3922
