### ISSUE TITLE
Support --env for Azure Container Instances

### ISSUE THREAD

**Issue by brendandburns** [Azure/azure-cli#4107]
Many people use environment variables to configure containers. The feature is present in the API, but not the CLI. We should add a `--env` flag to the CLI.

**Comment by yolo3301** [comment]
We do have env variables supported:

    --environment-variables -e    : A list of environment variable for the container. Space
                                    separated values in 'key=value' format.

Example:

   Create a container group with envrionment variables.
        az contanier create -g MyResourceGroup --name MyAlpine --image alpine:latest -e key1=value1
        key2=value2

**Comment by brendandburns** [comment]
Ah, sorry for the noise. closing.
