### ISSUE TITLE
[Container] Table output doesn't appear supported by the create command

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#4110]
### Description

If your CLI is configured to use table-output by default, then running `az container create` results in the following error message: `Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.`.

Oddly enough, running `az container list` or `az container show` works just fine, so it's a little unusual to get this message as the result of creating a new ACI instance. It would be awesome if all of the `az container` commands supported table output out of the box.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: nightly

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: nightly

**OS Version:** What OS and version are you using?  
Answer here: macOS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by derekbekoe** [comment]
This is a strange experience for users who have table output set as default.
It makes it seem like the command failed and so it's hard to tell if it was actually created.
@yolo3301

**Comment by samkreter** [comment]
@tjprescott  This has been. We can close the issue.
