### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by peterennis** [Azure/azure-cli#4112]
### Description
**Outline the issue here:**

Install following instructions and it does not work.
Domain environment running local non-privileged account.
I can enter the password for a domain admin.

---

### Environment summary

Windows 10

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

Followed instruction here:
https://openedx.microsoft.com/courses/course-v1:Microsoft+AZURE214x+2017_T3/courseware/fea92457971d4b5199dfae7c0b6caf65/8175cdcbd9664497a64730c64219cab2/

az location not added to the path.

C:\Users\petere>az
'az' is not recognized as an internal or external command,
operable program or batch file.

What is the path for az x64? I can manuall add it and test.

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

**OS Version:** What OS and version are you using?  
Answer here:

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

**Comment by derekbekoe** [comment]
Can you provide more info? The link included is behind a login.
It looks like you're on Windows so the best way to install is with the MSI
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli#windows

**Comment by tjprescott** [comment]
If the MSI does not work for you, please reopen and provide the requested info.

**Comment by peterennis** [comment]
That link worked.
The command prompt must be run as admin.
