### ISSUE TITLE
Launching staged images in portal

### ISSUE THREAD

**Issue by jimyjohny** [Azure/azure-cli#4114]
### Description
Using GUI, we are able to list and launch staged images. However, the cli doesn't seems to have this option. Its not listing the staged images. Is there any solution available ?

---

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
azure-cli (2.0.9) 

**OS Version:** What OS and version are you using?  
centos 6

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
bash

**Comment by tjprescott** [comment]
@Yugangw-msft are you familiar with this?

**Comment by yugangw-msft** [comment]
This is not exposed from the VM Image API. Since we have not got other user voices, I am closing this as the ask might never get supported
