### ISSUE TITLE
[ACS] default DNS prefix will cause deployment failure, because it exceeds domain name

### ISSUE THREAD

**Issue by anhowe** [Azure/azure-cli#4116]
### Description
**Outline the issue here:**

Dns-prefix – should note in the help that if none is given will default to the clustername-resourcegroup and some other pattern that usually blows up if there are any _ characters and can be too long as well and deployment fails. Many of my customers use underscore in their RG naming schemes

Solution here is to choose a default name that matches the requirement of the DNS name.
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: 

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

**OS Version:** What OS and version are you using?  
Answer here:

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

**Comment by anhowe** [comment]
@rjtsdl please look

**Comment by rjtsdl** [comment]
@anhowe , please help to close this.

**Comment by derekbekoe** [comment]
@rjtsdl You can get GitHub to close PRs on a merge automatically by including "Closes <bugnumber>" in the PR description.
https://help.github.com/articles/closing-issues-using-keywords/
