### ISSUE TITLE
Allow users to force-stop a VM

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#4120]
User reporting an issue where it can take a long time for an unresponsive VM to stop, and would prefer a method to "kill a VM WITH EXTREME PRJUDICE."

An idea, add an param to force-stop after 30 seconds of stopping

```
$ az vm stop --force-after 30  
```

**Comment by JasonRShaver** [comment]
Current working theory is that the [Azure Linux agent](https://github.com/azure/WALinuxAgent/issues) is non-responsive (and not receiving the stop).  @brendandixon

**Comment by yugangw-msft** [comment]
I suggest let the user ssh into the vm and check out `/var/log/waagent.log`, and we can start from there based on the content
AFAIK, no such API exists for force-stop. The next candidate would be `az vm delete` which i guess a bit harsh

**Comment by angrox** [comment]
When a VM is non responsing you do not have the possibilty to log in via SSH. We need something like all VM providers have: Reset the VM and boot in again.
I just have the same issue - a "reset" would be appreciated. It is not acceptable waiting 15-20 minutes to restart a unresponsive VM.

**Comment by yugangw-msft** [comment]
@adewaleo, let us expose a `--force` and invoke the redeploy?

**Comment by singhkays** [comment]
@yugangw-msft btw, this is the PS equivalent https://docs.microsoft.com/en-us/azure/virtual-machines/troubleshooting/redeploy-to-new-node-windows

**Comment by adewaleo** [comment]
closed through #7885
