### ISSUE TITLE
test: support to record commands with large  response payload (128kb+)

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#4127]
So far tests invoking `az vm list-skus`  can't playback as large response doesn't get into the recording. Per discussion, please expose a property to let such tests override the default behavior .

**Comment by tjprescott** [comment]
Alternatively, this processor should not be present as the default recording_processors (which in the devtools code-base, it is). It really should only be selectively applied to certain kinds of tests (for example, the Storage commands that it was originally designed against).  It causes too many unintended consequences.

**Comment by yugangw-msft** [comment]
Linked bug at https://github.com/Azure/azure-python-devtools/issues/37

**Comment by tjprescott** [comment]
This has been fixed. @yugangw-msft please re-open if this is still an issue.
