### ISSUE TITLE
Allow VMs to be created in an 'off' state.

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#4128]
There are things you can only do to a machine when it is powered down, such as setting the console logging information, but you need to have the logging set on the very initial boot to be able to debug its initial power up...

Customer tried doing an asynchronous bring up  (--no-wait) and then setting console logging but never really got what they were looking for.  

If you could set it up, and set everything up and THEN fire it off you get the chance to have the initial power up "under you control" so to speak.

**Comment by johanste** [comment]
What options other than enabling of boot logs are we talking about? The `az vm create` command should probably add native support for doing exactly that. 

I'm not sure if there are other scenarios that you are hinting at as well - but generally, anything that is needed to be available on first boot (i.e. cloudinit etc.) should be made available in the create commands.

**Comment by yugangw-msft** [comment]
We have supports now to capture boot log on creating a vm. Hence we don't need this any more
