### ISSUE TITLE
Not possible to list connection strings of non-MongoDB CosmosDB accounts

### ISSUE THREAD

**Issue by vjrantal** [Azure/azure-cli#4131]
### Description
**Outline the issue here:**

Command `az cosmosdb list-connection-strings` (documented [here](https://docs.microsoft.com/en-us/cli/azure/cosmosdb#list-connection-strings)) does not list connection strings unless the account kind is `MongoDB`.

However, it would be useful to be able to query the connection strings also when the kind of the account is, for example, `GlobalDocumentDB`. In this case, the connection string can be only seen from the Azure portal, but I could not find a programmatic way to access it.

A workaround is to call `az cosmosdb list-keys` and construct the connection string manually.

This issue comes down to the fact that the REST API at management.azure.com does not list the connection string unless the account is `MongoDB`. If there is a better repository to report issues directly against the REST API, let me know and I'll create an issue there as well.

**Comment by moderakh** [comment]
I added data plane API. This is account management API. Should be assigned to digvijay @dmakwana who worked on account mgt API.

**Comment by syedhassaanahmed** [comment]
@moderakh @dmakwana I've also encountered the same problem. Any progress on this issue?

**Comment by shurd** [comment]
This command returns connection strings now for all API types

**Comment by tjprescott** [comment]
Thank you @shurd. I'll close this now.
