### ISSUE TITLE
[Network] AppGateway frontend-ip update --public-ip-address parameter useless

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#4133]
The following command will fail:

`az network application-gateway frontend-ip update -g {rg} --gateway-name {ag} -n {ip config} --public-ip-address {different public ip}`

It gives an error: 
```
ApplicationGatewayFrontendIpPublicIpAddressCannotBeChanged
Message: PublicIPAddress property of FrontendIpConfiguration /subscriptions/xxxx/resourceGroups/rg/providers/Microsoft.Network/applicationGateways/ag/frontendIPConfigurations/myfrontend cannot be changed.
```

In this scenario, the `--public-ip-address` parameter on this command is useless and can be removed.

**Comment by tjprescott** [comment]
Closing this since the service may change to permit this behavior.

**Comment by fiftin** [comment]
I have the same problem. How to fix it?
