### ISSUE TITLE
webapp: add key-vault secret support to 'deployment user set' 

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#4141]
The password argument can point to a key-vault secret to make it easier for people to manage credentials

**Comment by yaronyg** [comment]
@yugangw-msft It would also be very useful on 'az webapp config appsettings set ... --settings' so that we can set an environment variable's value based on a key-vault secret.

**Comment by panchagnula** [comment]
Closing this since this is not something the platform team has planned. We will activate this if this plan changes. Thank you.
