### ISSUE TITLE
Unable to delete container attached to a deleted resourcegroup

### ISSUE THREAD

**Issue by johnkors** [Azure/azure-cli#4144]
### Description

I was able to delete a resource group, and I'm no longer able to delete a container instance earlier applied to the deleted resource group.
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
```
λ az --version
azure-cli (2.0.12)

acr (2.0.9)
acs (2.0.11)
appservice (0.1.11)
batch (3.0.3)
billing (0.1.3)
cdn (0.0.6)
cloud (2.0.7)
cognitiveservices (0.1.6)
command-modules-nspkg (2.0.1)
component (2.0.6)
configure (2.0.10)
consumption (0.1.3)
container (0.1.7)
core (2.0.12)
cosmosdb (0.1.11)
dla (0.0.10)
dls (0.0.11)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.7)
iot (0.1.10)
keyvault (2.0.8)
lab (0.0.9)
monitor (0.0.8)
network (2.0.11)
nspkg (3.0.1)
profile (2.0.9)
rdbms (0.0.5)
redis (0.2.7)
resource (2.0.11)
role (2.0.9)
sf (1.0.5)
sql (2.0.8)
storage (2.0.11)
vm (2.0.11)

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
```

**OS Version:** What OS and version are you using?  
Answer here: Win10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
Cmder/ConEmu

**Comment by tjprescott** [comment]
What command did you use to create the container?

**Comment by johnkors** [comment]
```
az container create --name <name> --image <img> --resource-group <resourcegroupname> --ip-address public
```

**Comment by johnkors** [comment]
It seems it moved my container registered to a deleted resource group to another existing resource-group, so now I was able to delete it.

**Comment by johnkors** [comment]
Btw, here's a log of what commands I ran: 
 https://gist.github.com/johnkors/05eb0ea7dd90ce9919a672b1768eb090

**Comment by derekbekoe** [comment]
Deleting the resource group deletes the resources inside of it.
There doesn't appear to be an issue here.
