### ISSUE TITLE
mySQL password error does not provide solution for bad password

### ISSUE THREAD

**Issue by yaronyg** [Azure/azure-cli#4152]
### Description
When calling "az mysql server create" with --admin-password the password was rejected with:

Deployment failed. Password validation failed. The password does not meet policy requirements because it is not complex enough.

Which is fair enough but no solution is provided. What are the requirements for the password? It seems like that information should be returned in the error message.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.10

**OS Version:** What OS and version are you using?  
Answer here: Windows 10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Powershell

**Comment by yaronyg** [comment]
@SaloniSonpal - Since you have a bug on your end tracking this I'll close this bug.

**Comment by brunoborges** [comment]
Hi SaloniSonpal, @yaronyg, has this issue been solved on Azure CLI? I have the latest version and the error message is still the same.

```
▶ az --version
azure-cli (2.0.45)
[...]
▶ az mysql server create --name brborgesdb --admin-user brborges --admin-password <some-random-pass> --sku-name GP_Gen5_2 --ssl-enforcement Disabled --version 5.7
Deployment failed. Correlation ID: ece5e840-2d02-4a23-8514-c8884a7222ab. Password validation failed. The password does not meet policy requirements because it is not complex enough.
```

**Comment by TakhiAbed** [comment]
I do got the same error is there any solution to this?
