### ISSUE TITLE
WSL: _openssl.abi3.so: cannot enable executable stack as shared object requires: Invalid argument

### ISSUE THREAD

**Issue by benc-uk** [Azure/azure-cli#4154]
### Description
Many simple commands e.g. `az webapp list` or `az appservice plan list` fail with a Python openssl error 
```
/opt/az/lib/python3.6/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: cannot enable executable stack as shared object requires: Invalid argument
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/main.py", line 36, in main
```

I've just updated to the latest v2.0.12 CLI. The `create` options also fail

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
apt-get under WSL

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
azure-cli (2.0.12)

**OS Version:** What OS and version are you using?  
Windows 10 (Latest update v1703, build: 15063.482)

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Bash for Windows

**Comment by tjprescott** [comment]
I believe this may be related to #4106.

**Comment by benc-uk** [comment]
Hi, What's the timeline for a fix? I've updated to 2.0.14 and it is still broken

**Comment by marrobi** [comment]
Any news on this? Is blocking me as need the "az container" commands so need to be > 2.0.12

**Comment by benc-uk** [comment]
Hey hi Marcus!
For me `az container` commands seem ok, as do many others. Which is odd if the issue is with the version of Python being bundled, I'd imagine it would affect all HTTPS calls made by the the CLI

**Comment by marrobi** [comment]
Yeah, they work fine, but means I can't roll back to a version of the cli where the broken commands work. `az acs kubernetes get-credentials` also fails.

**Comment by benc-uk** [comment]
Yes of course! The last good version was 2.10 I think and that was before they added the ACI stuff.  
I can imagine this is affecting *LOTS* of people, surprised there are not more issues/comments

**Comment by derekbekoe** [comment]
@marrobi Are you using Windows Subsystem also?
I suspect this is due to a missing Linux subsystem call on WSL.

**Comment by marrobi** [comment]
Yes, WSL, however the commands have worked previously...

**Comment by derekbekoe** [comment]
Okay thanks.
Yes so it last worked on version 2.0.10 of the CLI which was released [Jul 7](https://github.com/Azure/azure-cli/blob/master/packaged_releases/HISTORY.md).
The newer versions also pulled in newer versions of [cryptography](https://github.com/pyca/cryptography/blob/master/CHANGELOG.rst) which I suspect now require some different Linux system calls.

**Comment by marrobi** [comment]
So is someone going to look into this? Or is this the end of Azure CLI on WSL for now? Thanks.

**Comment by derekbekoe** [comment]
I will investigate this further and post an update.

**Comment by derekbekoe** [comment]
There was a change introduced in 2.0.1 of the cryptography package that causes certain commands to fail on WSL. Bash on Windows does not support executable stacks yet - see https://github.com/Microsoft/BashOnWindows/issues/2431#issuecomment-323141901.

I have created a patched .deb that pins the cryptography version, @marrobi @benc-uk @jwendl can you verify this resolves the issue?

```
wget https://derekb.blob.core.windows.net/public/azure-cli_2.0.14-2_all.deb
sudo dpkg -i azure-cli_2.0.14-2_all.deb
az
```

If so, we can consider pushing an update so it's available through apt-get update.

Thanks!

**Comment by jwendl** [comment]
@derekbekoe - Just verified the changes with the .deb file above and all is working well. Thank you for looking into this.

**Comment by derekbekoe** [comment]
Thanks @jwendl. I verified it on WSL also.
So I have published a patch with version `2.0.14-2`.

`sudo apt-get update && sudo apt-get install azure-cli` to update.

Closing issue. Please comment if you still have issues.

**Comment by rbitia** [comment]
@derekbekoe Hey Derek! Is this going to be added into the cli in the next update - I also just got stuck on this. Thanks!

**Comment by derekbekoe** [comment]
I have pushed the update. See my above comment.
It's a patch so it's version `2.0.14-2`.

**Comment by rbitia** [comment]
Gotcha thank you so much!

**Comment by marrobi** [comment]
Great. Did an apt-get update and upgrade and all is good 👍

**Comment by benc-uk** [comment]
Updated to 2.0.14-2 and commands are working again, thanks for the quick fix
