### ISSUE TITLE
"az storage metrics update" will not accept "true" for --api, --hour and --minute 

### ISSUE THREAD

**Issue by thiruma0203** [Azure/azure-cli#4155]
### Description
Run below command to enable storage metrics.
`az storage metrics update --services b --account-name teststorage --account-key xxxxxxxxxx --api true --hour true --minute true --retention 128`

However, storage metrics stay disabled. Check with the Azure portal or this command;
 `az storage metrics show --services b --account-name teststorage`

> {
>   "blob": {
>     "hour": {
>       "enabled": false,
>       "includeApis": null,
>       "retentionPolicy": {
>         "days": 128,
>         "enabled": true
>       },
>       "version": "1.0"
>     },
>     "minute": {
>       "enabled": false,
>       "includeApis": null,
>       "retentionPolicy": {
>         "days": 128,
>         "enabled": true
>       },
>       "version": "1.0"
>     }
>   }
> }
> 

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
apt-get

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

azure-cli (2.0.10)

acr (2.0.8)
acs (2.0.10)
appservice (0.1.10)
batch (3.0.3)
billing (0.1.3)
cdn (0.0.6)
cloud (2.0.6)
cognitiveservices (0.1.6)
command-modules-nspkg (2.0.1)
component (2.0.6)
configure (2.0.10)
consumption (0.1.3)
core (2.0.11)
cosmosdb (0.1.10)
dla (0.0.10)
dls (0.0.10)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.6)
iot (0.1.9)
keyvault (2.0.8)
lab (0.0.8)
monitor (0.0.8)
network (2.0.10)
nspkg (3.0.1)
profile (2.0.8)
rdbms (0.0.5)
redis (0.2.7)
resource (2.0.10)
role (2.0.8)
sf (1.0.5)
sql (2.0.7)
storage (2.0.10)
vm (2.0.10)

Python (Linux) 3.6.1 (default, Jul  7 2017, 17:58:08)
[GCC 4.8.4]

**OS Version:** What OS and version are you using?  
Answer here:
Ubuntu 16.04.2 LTS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
bash

**Comment by williexu** [comment]
Fixed with this:
https://github.com/Azure/azure-cli/pull/4819

**Comment by neerajks77** [comment]
Please let me know if this is already resolved. I am currently running into the issue
