### ISSUE TITLE
Nightly builds not getting updated with latest changes 

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-cli#4162]
Sometimes nightly builds are not picking up the latest changes and manual trigger is needed. Azure stack CI is consuming nightly builds for validation/regression testing and sometimes running in to issues as some of our fixes are not getting picked up in the nightly builds

**Comment by bganapa** [comment]
cc:@derekbekoe

**Comment by derekbekoe** [comment]
The latest nightly builds have been working so closing issue.
