### ISSUE TITLE
CI: Dependency mismatch as idna package updated today

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#4163]
### Description
**Outline the issue here:**

`idna==2.6` was published today.
https://pypi.python.org/pypi/idna

This is causing the CI dependency verification to fail:
```
+python -m automation.tests.verify_dependencies
Dependency compatibility errors found!
requests 2.18.3 has requirement idna<2.6,>=2.5, but you have idna 2.6.
```

The `requests` package specifies the following dependencies:
```
requires = [
    'chardet>=3.0.2,<3.1.0',
    'idna>=2.5,<2.6',
    'urllib3>=1.21.1,<1.23',
    'certifi>=2017.4.17'
]
```

**Comment by tjprescott** [comment]
Is there a fix? Do we merge PRs if that's the reason for failure or do we hold off on PRs?
