### ISSUE TITLE
Questions (Bugs?) when using Azure CLI 2.0 to configure Application Gateway URL Routing

### ISSUE THREAD

**Issue by IamVincentLin** [Azure/azure-cli#4168]
### Description
**Outline the issue here:**

My customer is trying to use Azure CLI 2.0 to configure Application Gateway URL Routing. He found the below questions and I can also reproduce it in my lab.

1.	We will not able to see the PathBased rule in Azure Portal if we create the UrlPathMap via Azure CLI 2.0
In the below output, we can see there is a rule named imagespathmap but it cannot be shown at Azure Portal
az network application-gateway url-path-map list --gateway-name TestAppGW -g APPGWRG
[
  {
    "defaultBackendAddressPool": {
      "id": "/subscriptions/e199e5ca-17cd-40b9-a32f-a7a10d19376a/resourceGroups/AppGWRG/providers/Microsoft.Network/applicationGateways/TestAppGW/backendAddressPools/appGatewayBackendPool",
      "resourceGroup": "AppGWRG"
    },
    "defaultBackendHttpSettings": {
      "id": "/subscriptions/e199e5ca-17cd-40b9-a32f-a7a10d19376a/resourceGroups/AppGWRG/providers/Microsoft.Network/applicationGateways/TestAppGW/backendHttpSettingsCollection/appGatewayBackendHttpSettings",
      "resourceGroup": "AppGWRG"
    },
    "defaultRedirectConfiguration": null,
    "etag": "W/\"1e2217e6-f02d-4229-b2a9-993eb2e41bf8\"",
    "id": "/subscriptions/e199e5ca-17cd-40b9-a32f-a7a10d19376a/resourceGroups/AppGWRG/providers/Microsoft.Network/applicationGateways/TestAppGW/urlPathMaps/imagespathmap",
    "name": "imagespathmap",
    "pathRules": [
      {
        "backendAddressPool": {
          "id": "/subscriptions/e199e5ca-17cd-40b9-a32f-a7a10d19376a/resourceGroups/AppGWRG/providers/Microsoft.Network/applicationGateways/TestAppGW/backendAddressPools/imagesBackendPool",
          "resourceGroup": "AppGWRG"
        },
        "backendHttpSettings": {
          "id": "/subscriptions/e199e5ca-17cd-40b9-a32f-a7a10d19376a/resourceGroups/AppGWRG/providers/Microsoft.Network/applicationGateways/TestAppGW/backendHttpSettingsCollection/appGatewayBackendHttpSettings",
          "resourceGroup": "AppGWRG"
        },
        "etag": "W/\"1e2217e6-f02d-4229-b2a9-993eb2e41bf8\"",
        "id": "/subscriptions/e199e5ca-17cd-40b9-a32f-a7a10d19376a/resourceGroups/AppGWRG/providers/Microsoft.Network/applicationGateways/TestAppGW/urlPathMaps/imagespathmap/pathRules/images",
        "name": "images",
        "paths": [
          "/images/*"
        ],
        "provisioningState": "Succeeded",
        "redirectConfiguration": null,
        "resourceGroup": "AppGWRG",
        "type": null
      },

2.	After we create the UrlPathMap object, we will fail to add new rule in the object via below commands

az network application-gateway url-path-map rule create --gateway-name TestAppGW --name images --path-map-name TestPath --paths /images/* --resource-group AppGWRG --address-pool imagesBackendPool --http-settings appGatewayBackendHttpSettings 

Error Message : Cannot parse the request.

However the below one works.

az network application-gateway url-path-map rule create --gateway-name TestAppGW --name images --path-map-name TestPath --paths /images/* --resource-group AppGWRG --address-pool /subscriptions/e199e5ca-17cd-40b9-a32f-a7a10d19376a/resourceGroups/AppGWRG/providers/Microsoft.Network/applicationGateways/TestAppGW/backendAddressPools/imagesBackendPool --http-settings /subscriptions/e199e5ca-17cd-40b9-a32f-a7a10d19376a/resourceGroups/AppGWRG/providers/Microsoft.Network/applicationGateways/TestAppGW/backendHttpSettingsCollection/appGatewayBackendHttpSettings

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: Install Windows version .msi

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: Azure CLI 2.0

**OS Version:** What OS and version are you using?  
Answer here: Windows 10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

**Comment by tjprescott** [comment]
Hi @IamVincentLin, I've looked into your scenario.

You create a URL path map, with associated rules, but for this to appear in the portal, you must create an application gateway rule (a request routing rule) which actually wires up that path map to a listener. So you would have something like:
`az network application-gateway rule create -g {rg} --gateway-name {ag} -n {path-rule} --http-listener {listener} --url-path-map {path-map}`

Then it should appear (and more importantly, function!).  There are some service side quirks related to path maps and rules that the portal tries to streamline, whereas the CLI tends to expose the raw API. I'll split this into two separate issues (1 for improving this experience and 1 for fixing the name/ID bug).

If your path map rules don't appear after wiring them up with a request routing rule, please let me know.
