### ISSUE TITLE
Order of subcommands in 'Usage' not consistent

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#417]
In the screenshot below, you can see that the order changes each time.

I would expect the order to not change.

<img width="563" alt="screen shot 2016-06-14 at 4 34 01 pm" src="https://cloud.githubusercontent.com/assets/16448634/16063430/140033dc-324e-11e6-80fc-95ec8412f0f5.png">

**Comment by johanste** [comment]
Unless the list is sorted (and thus stable), I personally wouldn't care if it changed all the time.

**Comment by derekbekoe** [comment]
I'm fine with this.
