### ISSUE TITLE
Weird param handling for special chars in PowerShell shell

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#4179]
```
az --% keyvault secret set --name mySql --vault-name webAppSCUdkeyVault --value Z#LvdInS"$l_YPbzs#J0l#X8SMP-HEvN 
az keyvault secret set --name 'mySql' --vault-name 'webAppSCUdkeyVault' --value "Z#LvdInS""`$l_YPbzs#J0l#X8SMP-HEvN"

Original: Z#LvdInS"$l_YPbzs#J0l#X8SMP-HEvN
Recorded: Z#LvdInS$l_YPbzs#J0l#X8SMP-HEvN

# another example
Original:    m4KSA2Jqk^tuM71Z0AD4jXBWxwR%AVwd
Recorded: m4KSA2JqktuM71Z0AD4jXBWxwR%AVwd
```

**Comment by tjprescott** [comment]
If you run this with debug, you will see that the quote character is stripped out by PowerShell before it reaches the CLI:
`Command arguments: [... 'Z#LvdInS$l_YPbzs#J0l#X8SMP-HEvN']`

As such, there is nothing we can do about this and you will need to figure out how to properly escape the string.

**Comment by mmello-certica** [comment]
Actually it looks like this is a python problem. I tried this from a cmd session with the same result. A co-worker found this:
https://stackoverflow.com/questions/13168666/python-argparse-argument-with-quotes
Escaping the string with a backslash worked for me. Writing this in case anyone else finds this page searching for this same problem
