### ISSUE TITLE
Enable .zip file deployment for az functionapp

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-cli#4180]
### Description
Feature request in azfunctionapp: For cases where Git-based deployment is too heavyweight, it would be nice to have the option of deploying using a .zip file or some other compressed package.
`az functionapp deployment source config --name $functionapp --resource-group myResourceGroup --source-url --type zip`

Maybe this also applies to Web Apps? Note that I originally opened this in the wrong repo: https://github.com/Azure/azure-functions-cli/issues/203 

---

### Environment summary

**Install Method:** Cloud Shell
**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: n/a

**OS Version:** What OS and version are you using?  
Answer here: Cloud Shell

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Cloud Shell

**Comment by richardjortega** [comment]
If sending a local zip file, is the `--source-url` even required?

**Comment by yugangw-msft** [comment]
Closing per #4700. Thanks @panchagnula!
