### ISSUE TITLE
Sending a kill signal to the cli should reap the corresponding python procress

### ISSUE THREAD

**Issue by jchauncey** [Azure/azure-cli#4182]
### Description
**Outline the issue here:**
On a linux host if you start the az cli and then send a `kill -9` to that pid it will not reap the python process that was started. This means that process keeps going even if you dont want it to.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.10

**OS Version:** What OS and version are you using?  
Answer here: Ubuntu: 16.04

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by jchauncey** [comment]
```bash
root@7ff7ab739171:/go/src/github.com/Azure/acs-engine# ps aux | grep az
root     12306  0.0  0.1  18056  2756 ?        S+   21:54   0:00 /bin/bash /usr/local/bin/az group deployment create --name k8s-westus2-67940 --resource-group k8s-westus2-67940 --template-file /go/src/github.com/Azure/acs-engine/_output/k8s-westus2-67940/azuredeploy.json --parameters /go/src/github.com/Azure/acs-engine/_output/k8s-westus2-67940/azuredeploy.parameters.json
root     12312  4.0  2.4 182204 50868 ?        Sl+  21:54   0:00 python -m azure.cli group deployment create --name k8s-westus2-67940 --resource-group k8s-westus2-67940 --template-file /go/src/github.com/Azure/acs-engine/_output/k8s-westus2-67940/azuredeploy.json --parameters /go/src/github.com/Azure/acs-engine/_output/k8s-westus2-67940/azuredeploy.parameters.json
root     12327  0.0  0.0  11288   896 ?        S+   21:54   0:00 grep --color=auto az
root@7ff7ab739171:/go/src/github.com/Azure/acs-engine# kill -9 12306
root@7ff7ab739171:/go/src/github.com/Azure/acs-engine# ps aux | grep az
root     12312  2.7  2.5 183144 51924 ?        Sl+  21:54   0:00 python -m azure.cli group deployment create --name k8s-westus2-67940 --resource-group k8s-westus2-67940 --template-file /go/src/github.com/Azure/acs-engine/_output/k8s-westus2-67940/azuredeploy.json --parameters /go/src/github.com/Azure/acs-engine/_output/k8s-westus2-67940/azuredeploy.parameters.json
root     12329  0.0  0.0  11288   936 ?        S+   21:54   0:00 grep --color=auto az
```

**Comment by troydai** [comment]
@jchauncey, thank you for reporting. In your case, you killed the parent process while the child process lives on. If you want to kill parent process while clear all its child processes you can use this command:
`pkill -9 -P <PPID>`

**Comment by jchauncey** [comment]
So the way I found out about this problem is that our e2e tests exec out in golang to create a deployment. If the timeout for that deployment is exceeded (we dont wnat to wait the full azure timeout) golang attempts to send a `SIG_KILL` to the pid it started. It knew nothing of the spawned processes that the az cli created. Because the cli didnt honor the signal golang will not respond appropriately. 

I would think the best way to handle this is to capture the signals being sent and handle them. In this case if I send a `-9` to the root process you should be able to kill all spawned processes for me.

**Comment by yonzhan** [comment]
add to S165.

**Comment by jiasli** [comment]
I can repro with:

```sh
$ az login &
[1] 35063

$ ps aux | grep az
...   35063  0.0  0.0  13308  3100 pts/0    S    08:04   0:00 bash /usr/bin/az login
...   35064 11.7  0.3 151472 58464 pts/0    S    08:04   0:00 /opt/az/bin/python3 -Im azure.cli login

$ kill -9 35063

$ ps aux | grep az
...   35064  1.7  0.3 151608 58680 pts/0    S    08:04   0:00 /opt/az/bin/python3 -Im azure.cli login
```

`35064` keeps running, which is the designed behavior of Linux that it doesn't forward `SIGTERM` to child processes. 

As @troydai suggested, you may use `pkill -9 -P <PPID>` to kill the python process and the script will error out automatically:

http://manpages.ubuntu.com/manpages/bionic/man1/pgrep.1.html

>-P, --parent ppid,...
>Only match processes whose parent process ID is listed.

```sh
$ az login &
[1] 35267

$ ps aux | grep az
...   35267  0.0  0.0  13308  3184 pts/0    S    08:08   0:00 bash /usr/bin/az login
...   35268 11.4  0.3 151472 58336 pts/0    S    08:08   0:00 /opt/az/bin/python3 -Im azure.cli login

$ pkill -9 -P 35267
/usr/bin/az: line 2: 35268 Killed                  /opt/az/bin/python3 -Im azure.cli "$@"

$ ps aux | grep az
# no 35267 and 35268 anymore
```

Or you may change the `az` script directly so that it can forward `SIGTERM`: https://unix.stackexchange.com/a/146770/145565
