### ISSUE TITLE
az mysql server firewall-rule create gives bad error message

### ISSUE THREAD

**Issue by yaronyg** [Azure/azure-cli#4183]
### Description
The error message for a bad parameter doesn't specify which parameter is bad

For example:
```
az mysql server firewall-rule create --resource-group webAppSCUp --server webappscupmysql --name mySql13.65.92.72 --start-ip-address 13.65.92.72 --end-ip-address 13.65.92.72
```
Just returns: Deployment failed. Invalid value given for parameter 'firewallRule'. Specify a valid parameter value.

In this case the bad parameter was the name but there error didn't specify that.
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
2.0.10

**OS Version:** What OS and version are you using?  
Windows 10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Powershell

**Comment by SaloniSonpal** [comment]
@yaronyg - Thanks for your feedback. This does look like a bug where the exact parameter is not called out and hence not very actionable. We will work on addressing this issue and fixing it as a part of the next release.

**Comment by yaronyg** [comment]
@SaloniSonpal  - If this is tracked on your end can I safely close this bug?

**Comment by ajlam** [comment]
Will track this internally in VSO. 

@bsiegel - please help close this.
