### ISSUE TITLE
Add more compatibility with xplat cli when there is no conflict

### ISSUE THREAD

**Issue by nneul** [Azure/azure-cli#4186]
### Description

For `az vnet subnet` operations `-e` is not used for any other existing argument - would be good for xplat migrations to support -e which it uses.

`-e` => `--vnet-name`

Would have submitted a PR, but wasn't clear how to do the `register_alias` in network.py with where it have cli_generic_update_command and similar. If you can point out an example of how to do this, I'll send a PR.

**Comment by nneul** [comment]
`az network dns record-set` add:
 `-l` => `--ttl` 

For that command, these are not shown in the help information, but do work:
`-g` => `--resource-group`
`-n` => `--record-set-name`
`-z` => `--zone-name`

**Comment by nneul** [comment]
`az network nic create` add:
`-m` => `--vnet-name`
`-k` => `--subnet`

**Comment by tjprescott** [comment]
For the DNS record commands the short options are listed in the help:
```Command
    az network dns record-set a add-record

Arguments
    --ipv4-address -a    [Required]: IPV4 address in string notation.
    --record-set-name -n [Required]: The name of the record set relative to the zone. Creates a new
                                     record set if one does not exist.
    --resource-group -g  [Required]: Name of resource group. You can configure the default group
                                     using `az configure --defaults group=<name>`.
    --zone-name -z       [Required]: The name of the zone.
```

We made a conscious choice not to lift short arguments from Xplat. As you point out, for one command, `vnet-name` is `-e` and another it is `-m`.  Neither makes any sense. If we choose a short option, we do so when the argument is used often and when the user can have a reasonable expectation that it will be consistent throughout the CLI, ideally globally (-g and -l), but at least throughout a module (short options in storage for example).

There may be no conflict today, but as we are already finding when we wanted to introduce a new global alias, there is a conflict with one random command group that decided to use that short option for something that it really didn't need to.

**Comment by nneul** [comment]
Ok, I can live with that since it was a conscious decision.

Now I can't reproduce what triggered my comment about the short items not being listed... strange. Maybe was confusing output of one cmd with another.

**Comment by tjprescott** [comment]
It might be that the usage string doesn't display the short options: 
```
usage: az network dns record-set a add-record [-h]
                                              [--output {json,tsv,table,jsonc}]
                                              [--verbose] [--debug]
                                              [--query JMESPATH]
                                              --resource-group
                                              RESOURCE_GROUP_NAME --zone-name
                                              ZONE_NAME --ipv4-address
                                              IPV4_ADDRESS --record-set-name
                                              NAME
```
However the argparse error message does:
```
az network dns record-set a add-record: error: the following arguments are required: --resource-group/-g, --zone-name/-z, --ipv4-address/-a, --record-set-name/-n
```

**Comment by nneul** [comment]
Ah, yep. that was it! ty.
