### ISSUE TITLE
ExpressRoute: Add support for IPv6 in Microsoft peering

### ISSUE THREAD

**Issue by ganesr** [Azure/azure-cli#4189]
### Description
We have enabled support for IPv6 for Microsoft peering. We would love to have CLI support for it. 
Swagger spec. is at https://github.com/Azure/azure-rest-api-specs/blob/current/specification/network/resource-manager/Microsoft.Network/2017-06-01/expressRouteCircuit.json

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

**OS Version:** What OS and version are you using?  
Answer here:

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

**Comment by tjprescott** [comment]
Thanks @ganesr.

**Comment by tjprescott** [comment]
Currently this is blocked pending action from the service team.
