### ISSUE TITLE
[EventGrid] Required work prior to GA

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#4194]
- [ ] Add support for update commands (with generic update support) (https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#generic-update-commands)
- [ ] Add support for IDs in general (--ids parameters) (https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#supporting-the-ids-parameter)
- [ ] Add resource specific features (similar to `az resource` and `az lock`) (something to consider, low priority)
- [x] Finalize command tree structure.
- [ ] Tab completion for names
- [ ] Table formats
- [ ] `az eventgrid topic key regenerate` `--key-name` should have a choice list of the possible values.

**Comment by snobu** [comment]
Isn't EventGrid supposed to still be super secret confidential stuff?

**Comment by ahamad-MS** [comment]
@tjprescott  @jfggdl  This is an old issue and many of the requests are already taken care or not applicable any more and remaining ones are being addressed currently. Here is an update for these issues. I am planning to close this one and open a task on the last issue remaining (table format) if still applicable. thanks

1. Add support for update commands (with generic update support) (https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#generic-update-commands) 

===> This has been already addressed in previous PRs and part of both extension and Stable versions.

2.  Add support for IDs in general (--ids parameters) 

===> This has been already addressed in previous PRs and part of both extension and Stable versions.

3. Add resource specific features (similar to az resource and az lock) (something to consider, low priority)

===> Per discussion with Kalyan, this was already decided as Won't fix or not applicable any more.

4.  Finalize command tree structure.

===> This has been already addressed in previous PRs and part of both extension and Stable versions.

5.  Tab completion for names

===> This has been already addressed in previous PRs and part of both extension and Stable versions.

6.  Table formats

===> This is not clear. Is this in the context of output? Can you please provide some context/info on the ask?

7.  az eventgrid topic key regenerate --key-name should have a choice list of the possible values.

===> This is currently being addressed by this PR:  https://github.com/Azure/azure-cli/pull/9578

**Comment by jfggdl** [comment]
@tjprescott, would you please help us with questions 6 above?

**Comment by jfggdl** [comment]
@tjprescott, we are closing this issue, but feel free to reopen it if you still are interested in the features mentioned when you open the issue. Please also help us with question 6 above if you reopen the issue. We would be happy to continue working on your requests.
