### ISSUE TITLE
Latest version on documentation site is behind the releases here on GitHub

### ISSUE THREAD

**Issue by SteveALee** [Azure/azure-cli#4199]
* I Installed the msi linked to from the decumentation site and it is 2.012. as is here
~~* I ran `az --version` and get 2.0.1~~
* The [release notes on document site](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli) stop at 2.0.6, though here on git hub the latets release is 2.0.12

**Comment by SteveALee** [comment]
Oh, sorry I need to open a new console window for the update version to show. 

So just the release page is at issue

**Comment by SteveALee** [comment]
Actually if i run `az --version` from a `git4windows` bash shell it gives 2.0.1, even after a reboot.

This is annoying as I use this shell all the time.

**Comment by SteveALee** [comment]
It seems to be picking up an install; of python 3.5.2 under roaming which has an az.cmd file

In a cmd shell it use Pyhton 3.6.1 which I do not have globally installed

**Comment by tjprescott** [comment]
@derekbekoe is best to comment on the different installations, but I'll just add you are likely to run into issues using git bash as a shell.

**Comment by SteveALee** [comment]
@tjprescott Thanks - yes. I manually removed that old python installation and a CLI v1 installation as they should not have been arround. Now AZ does not work at all in git bash, even though is on the path. Seems to be assumptions made with .bat files.

But it's easy enough to run a cmd sub shell for the the odd `az` command and NPM currently always runs cmd. even when called from git bash.

I'll use WSL once links/JUNCTIONS work correctly on both sides of the shared files space.

In actually fact, I switched to `AzCopy` as it correcly sets MIME types when files uploaded to blob storage.

**Comment by derekbekoe** [comment]
Looks like there are two versions of the CLI installed if git bash picks up a different version to cmd.

**Comment by derekbekoe** [comment]
You can check your path for multiple `az`s and remove the one you don't want to use or uninstall the older one altogether.

**Comment by SteveALee** [comment]
@derekbekoe That was indeed the case (I used `which az`). I don't understand why as I had used the WIndows remove to kill all old versions. See more detaisl above. :)

**Comment by derekbekoe** [comment]
Ah. @SteveALee okay to close issue?

**Comment by SteveALee** [comment]
Well, the releases listed on the [documentation site](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli) are behind so I could rename issue to just cover that point if you like?

**Comment by derekbekoe** [comment]
The release notes page has been updated and we'll submit changes for future releases to the docs page.
