### ISSUE TITLE
az webapp list 404 Client Error

### ISSUE THREAD

**Issue by luna4d** [Azure/azure-cli#4200]
### Description
**az webapp list**
https://docs.microsoft.com/en-us/cli/azure/webapp#list
`PS C:\WINDOWS\system32> az webapp list
Operation failed with status: 'Not Found'. Details: 404 Client Error: Not Found for url: https://management.azure.com/su
bscriptions/01c16a40-ab7e-4703-8205-a6d402d14870/providers/Microsoft.Web/sites?api-version=2016-08-01`

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.12)

**OS Version:** What OS and version are you using?  
Answer here: Windows 10 1703

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: PowerShell

**Comment by yugangw-msft** [comment]
@luna4d , I can't reproduce it. Are you still seeing it?

**Comment by derekbekoe** [comment]
Also @luna4d please add the `--debug` argument and provide the output.

**Comment by yugangw-msft** [comment]
@luna4d, please activate with more details
