### ISSUE TITLE
Azure CLI Deployment doesnt understand parameter file with no parameters but valid schema

### ISSUE THREAD

**Issue by amalik99** [Azure/azure-cli#4201]
### Description
there are a bunch of templates with no parameters, azure-deploy and parameter file looking like below.

Sample Template file - https://raw.githubusercontent.com/SpektraSystems/azure-quickstart-templates/master/101-subnet-add-vnet-existing/prereqs/prereq.azuredeploy.json

Sample parameter file - https://raw.githubusercontent.com/SpektraSystems/azure-quickstart-templates/master/101-subnet-add-vnet-existing/prereqs/prereq.azuredeploy.parameters.json 

When we do the deployment with az group deployment create, gets error that parameter file is malformed, whereas schema is absolutely fine. It used to work well with Azure CLI 1.0

I understand that specifying --parameters is options, but this also should be working which is crucial for devops/automation scenarios or at-least give understandable error

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: - apt-get

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.12)
acr (2.0.9)
acs (2.0.11)
appservice (0.1.11)
batch (3.0.3)
billing (0.1.3)
cdn (0.0.6)
cloud (2.0.7)
cognitiveservices (0.1.6)
command-modules-nspkg (2.0.1)
component (2.0.6)
configure (2.0.10)
consumption (0.1.3)
container (0.1.7)
core (2.0.12)
cosmosdb (0.1.11)
dla (0.0.10)
dls (0.0.11)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.7)
iot (0.1.10)
keyvault (2.0.8)
lab (0.0.9)
monitor (0.0.8)
network (2.0.11)
nspkg (3.0.1)
profile (2.0.9)
rdbms (0.0.5)
redis (0.2.7)
resource (2.0.11)
role (2.0.9)
sf (1.0.5)
sql (2.0.8)
storage (2.0.11)
vm (2.0.11)

**OS Version:** What OS and version are you using?  
Answer here: Ubuntu 14

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by tjprescott** [comment]
Hi @amalik99 you raise an excellent point. We'll get it taken care of.
