### ISSUE TITLE
Add a VM to an AvailabilitySet after creation.

### ISSUE THREAD

**Issue by nneul** [Azure/azure-cli#4202]
### Description

Is there an azure-cli equivalent of this powershell cmdlet? Described here:

https://www.petri.com/understanding-azure-availability-sets

https://docs.microsoft.com/en-us/powershell/module/azure/set-azureavailabilityset?view=azuresmps-4.0.0`

The first link has an example like this:

`Get-AzureVM -ServiceName contosodc1 -Name contosodc1 | Set-AzureAvailabilitySet -AvailabilitySetName contosodcs | Update-AzureVM`

---

### Environment summary

**Install Method:** nightly

**CLI Version:** azure-cli (2.0.12+1.dev20170808)

**OS Version:** ubuntu 16.04 x64

**Shell Type:** bash

**Comment by tjprescott** [comment]
Hi @nneul there is no dedicated command for this. I tried to accomplish this via generic update and had no luck.  It seems you must specify the availability set when you create the VM (at least currently in 2.0)  We have an open project to improve the adding of VMs to load balancers and application gateway pools.

I'll investigate some potential solutions for this next sprint and see if we can get something into the next release. Ideas would be having an `availability-set add-vm` command, or adding availability set as strongly typed parameter on `vm update`.

**Comment by tjprescott** [comment]
Moving this into the same project as improving LB/AG experience.

**Comment by superminiek** [comment]
Anything new here?

**Comment by tjprescott** [comment]
The item is on our backlog but not planned for upcoming work.  @yugangw-msft does this fit into your upcoming sprint plans?

**Comment by yugangw-msft** [comment]
@tjprescott, I will take a look in the next sprint

**Comment by yugangw-msft** [comment]
I have confirmed with Compute team that adding an existing VM to an existing av-set only works with RDFE(cloud service). For Compute RP, the only time you can add to an av-set is during VM create.
