### ISSUE TITLE
az storage metrics update command overwrite the diag settings to be incorrect

### ISSUE THREAD

**Issue by shinjisgogo** [Azure/azure-cli#4203]
### Description
**Outline the issue here:**
I found the problematic behavior that looks like a bug when cx sets the diagnostics of storage. I also found the code which must be fixed. Could you look into this issue and fix this if it’s bug?

Problematic behavior
When “Blob aggregate metrics” and “Blob per API metrics” are “true” and overwrite both settings to be “true” again, both settings will be “false”.

1.	Check default settings of “Blob aggregate metrics” and “Blob per API metrics”.
```
$ az storage metrics show --services b --account-name invdiag412
{
  "blob": {
    "hour": {
      "enabled": true,
      "includeApis": true,
      "retentionPolicy": {
        "days": 10,
        "enabled": true
      },
      "version": "1.0"
    },
    "minute": {
      "enabled": true,
      "includeApis": true,
      "retentionPolicy": {
        "days": 10,
        "enabled": true
      },
      "version": "1.0"
    }
  }
}
```
2.	Then overwrite the both settings to be “true” again.
```
$ az storage metrics update --services b --account-name invdiag412 --api true --hour true --minute true --retention 10
```

3.	Check both settings again and found that the these are “false”
```
$ az storage metrics show --services b --account-name invdiag412
{
  "blob": {
    "hour": {
      "enabled": false,
      "includeApis": null,
      "retentionPolicy": {
        "days": 10,
        "enabled": true
      },
      "version": "1.0"
    },
    "minute": {
      "enabled": false,
      "includeApis": null,
      "retentionPolicy": {
        "days": 10,
        "enabled": true
      },
      "version": "1.0"
    }
  }
}
```

4.	Here is the code which must be fixed.
https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py

The code is evaluated with enable / disable, but this location should be evaluated as true / false.
~~~~~~~~~
    namespace.hour = namespace.hour == 'enable'
    namespace.minute = namespace.minute == 'enable'
    namespace.api = namespace.api == 'enable' if namespace.api else None
~~~~~~~~~

Could you please look into this behavior and fix it?

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
$az --version
azure-cli (2.0.8)

acr (2.0.6)
acs (2.0.8)
appservice (0.1.8)
batch (3.0.1)
billing (0.1.1)
cdn (0.0.4)
cloud (2.0.4)
cognitiveservices (0.1.4)
command-modules-nspkg (2.0.0)
component (2.0.5)
configure (2.0.8)
consumption (0.1.1)
core (2.0.8)
cosmosdb (0.1.8)
dla (0.0.8)
dls (0.0.8)
feedback (2.0.4)
find (0.2.4)
interactive (0.3.4)
iot (0.1.7)
keyvault (2.0.6)
lab (0.0.6)
monitor (0.0.6)
network (2.0.8)
nspkg (3.0.0)
profile (2.0.6)
rdbms (0.0.3)
redis (0.2.5)
resource (2.0.8)
role (2.0.6)
sf (1.0.3)
sql (2.0.5)
storage (2.0.8)
vm (2.0.8)

Python (Linux) 3.6.1 (default, Jun 14 2017, 11:33:22)
[GCC 4.8.4]

Python location '/opt/az/bin/python3'

**OS Version:** What OS and version are you using?  
Answer here:
Windows 10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
Bash on Windows

**Comment by AlexandreBouffard** [comment]
I can reproduce this issue on latest version (2.0.17).

The unit test does not raise the bug as it only tests for disabling metrics (https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/tests/test_storage_account_scenarios.py).
