### ISSUE TITLE
no-wait option on az vm availability-set create doesn't work

### ISSUE THREAD

**Issue by nneul** [Azure/azure-cli#4207]
### Description

`nneul@skyhawk:/local/deploy $ az vm availability-set create --resource-group ${res_group} --name ${aset}-availset --location $region --no-wait` 

results in 

`
Deployment failed. 'ClientRawResponse' object has no attribute 'done'
`

Works fine if I don't specify `--no-wait`

---

### Environment summary

**Install Method:** nightly
**CLI Version:** azure-cli (2.0.12+1.dev20170808)
**OS Version:** ubuntu 16.04
**Shell Type:** bash

**Comment by tjprescott** [comment]
Thanks for the report @nneul!
