### ISSUE TITLE
[ACS] deployment output has incorrect ssh output to master

### ISSUE THREAD

**Issue by weinong** [Azure/azure-cli#4210]
### Description
**Outline the issue here:**  
---
When a Kubernetes cluster is created, the cli returns the outputs like

> "sshMaster0": {
>  "type": "String",
>  "value": "ssh azureuser@foo.westcentralus.cloudapp.azure.com -A -p 2200
>}

But there is no 2200 port opened on master
this is the result of [this](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/custom.py#L685)
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: latest

**OS Version:** What OS and version are you using?  
Answer here: Ubuntu 16.04

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by rjtsdl** [comment]
I guess, it should just be 22 instead of 2200. I will send a PR for this fix.

**Comment by weinong** [comment]
it depends on the orchestrator. for DCOS and Swarm it's 2200-2202.

**Comment by tjprescott** [comment]
PR #4212 merged
