### ISSUE TITLE
Showing NSG is not showing error when given wrong options

### ISSUE THREAD

**Issue by eon01** [Azure/azure-cli#4211]
### Description

*update*

Typing a RG or a NSG that doesn't exist will not show any error. As a user I think this is confusing.

```
az network nsg show --resource-group myResourceGroupxxxxx --name myNetworkSecurityGroupxxxx
```

Probably adding an message would be more helpful.

---

### Environment summary

**Install Method:** CLI / Linux

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  :

```
azure-cli (2.0.13)

acr (2.0.10)
acs (2.0.12)
appservice (0.1.12)
batch (3.1.1)
billing (0.1.3)
cdn (0.0.6)
cloud (2.0.7)
cognitiveservices (0.1.6)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.10)
consumption (0.1.3)
container (0.1.8)
core (2.0.13)
cosmosdb (0.1.11)
dla (0.0.10)
dls (0.0.12)
eventgrid (0.1.1)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.7)
iot (0.1.10)
keyvault (2.0.8)
lab (0.0.9)
monitor (0.0.8)
network (2.0.12)
nspkg (3.0.1)
profile (2.0.10)
rdbms (0.0.5)
redis (0.2.7)
resource (2.0.12)
role (2.0.10)
sf (1.0.6)
sql (2.0.9)
storage (2.0.12)
vm (2.0.12)

Python (Linux) 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]
```

**OS Version:** What OS and version are you using?  
```
cat /etc/lsb-release 

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.1
DISTRIB_CODENAME=serena
DISTRIB_DESCRIPTION="Linux Mint 18.1 Serena"
```

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows) : 
```
echo $SHELL
/bin/bash
```

**Comment by tjprescott** [comment]
Hi @eon01 we appreciate the feedback. The main reason we don't error out when the resource doesn't exist is because it simplifies scripting scenarios. As the CLI tries to be quiet, when you run a show command, if nothing is printed then there was nothing there to print. Thus, by implication the resource did not exist. If that isn't clear then the interactive scenario isn't being given enough consideration and we can look at striking the right balance between scripting and interactivity.  @johanste can offer further comment on this.

**Comment by eon01** [comment]
Hi @tjprescott Thank you for your comment, I appreciate it. In this case it's not a bug but a way of designing the CLI.

For users in my case using ``` --debug ``` could be helpful:

```
az network nsg show --resource-group xxx --name xxx --debug
```

Another way of thinking instead of showing nothing when there is nothing to show is printing something like:

```
{
    "SecurityGroups": []
}
```

This is the case for other CLIs like AWS CLI:

```
aws ec2 describe-security-groups --filters Name=group-name,Values="*DoesntExist*" 

{
    "SecurityGroups": []
}
```
But as I said, ``` --debug ``` is what I should have used :+1: 

Cheers,
Aymen

**Comment by tjprescott** [comment]
This has been fixed. An error will be displayed and the command will return error code 3.
