### ISSUE TITLE
ADFS 'active_directory' endpoint can't be recognized if trailing slash is present

### ISSUE THREAD

**Issue by viananth** [Azure/azure-cli#4213]
### Description
**Outline the issue here:**
If the "endpoint-active-directory" parameter for ADFS env has a trailing slash in it, the tenant is not able to login.

**Error:**
```
ERROR : az.azure.cli.core.util : Instance Discovery request returned http error: 400 and server response: 
{
  "error":"invalid_instance",
  "error_description":"AADSTS50049: Unknown or invalid instance.\r\nTrace ID: e424a75e-3f92-41ac-b1f1-6fa393da0300\r\nCorrelation ID: b3d0a700-5c5b-4c3f-91b9-0e8001e3ec67\r\nTimestamp: 2017-08-12 08:15:45Z",
  "error_codes":[50049],
  "timestamp":"2017-08-12 08:15:45Z",
  "trace_id":"e424a75e-3f92-41ac-b1f1-6fa393da0300",
  "correlation_id":"b3d0a700-5c5b-4c3f-91b9-0e8001e3ec67"
}
```

But once the trailing slash was removed, tenant was able to login.

---

**Comment by tjprescott** [comment]
@viananth is this related to #4216?

**Comment by yugangw-msft** [comment]
Different thing from #4216 .
@viananth, like I communicated in the mail thread, let us settle on how ADFS endpoints in the Stack env would look like, document it, and I will align CLI's auth code for that
