### ISSUE TITLE
az storage account update encryption - syntax mismatch?

### ISSUE THREAD

**Issue by nneul** [Azure/azure-cli#4220]
### Description

`az storage account update \
	--name ${storageacct} --resource-group ${res_group} \
	--encryption queue table blob file`

based on this in usage:

`[--encryption {queue,table,blob,file} [{queue,table,blob,file} ...]]`

results in 

`az storage account update: error: __init__() got an unexpected keyword argument 'queue'`

issueing them one at a time appears to work.

---

### Environment summary

**Install Method:** nightly
**CLI Version:** azure-cli (2.0.12+1.dev20170808)
**OS Version:** Ubuntu 16.04 x64
**Shell Type:** bash

**Comment by tjprescott** [comment]
@troydai can you take a look?  This used to work fine so I wonder if storage released an SDK update with a breaking change.

**Comment by tjprescott** [comment]
As described in #4248, this also affect storage account create.

**Comment by troydai** [comment]
I'll introduce a breaking change to rename `--encryption` to `--encryption-services` and fix this issue in the process.

**Comment by sptramer** [comment]
@troydai @tjprescott @derekbekoe -- When making breaking changes to the CLI like this, can you please send an email or mention myself (owner of Azure DevEx for the CLI) so that I can make any required changes to conceptual documentation to go live with the release, or point you to any documentation to edit?

Thanks.

**Comment by troydai** [comment]
@sptramer sure. The pull request will have breaking change label and it will be also mentioned in the release note. Should we @ you in all the pull request involving breaking changes? If so, we need to write a bot to ensure nothing is missing. Or you can query pr with corresponding label.

**Comment by sptramer** [comment]
@troydai If all of the PRs which will make a breaking change are guaranteed to be tagged, I can just do a periodic search to make sure that I'm capturing everything before a release. Thanks!

**Comment by troydai** [comment]
@sptramer it's "Breaking Change".

**Comment by ArieShout** [comment]
I had this issue in Azure CLI 2.0.29

```sh
az storage account create --name $account --resource-group $group --encryption-services table queue
```

results in

```
usage: az storage account create [-h] [--verbose] [--debug]
                                 [--output {json,jsonc,table,tsv}]
                                 [--query JMESPATH] --resource-group
                                 RESOURCE_GROUP_NAME --name ACCOUNT_NAME
                                 [--sku {Standard_LRS,Standard_GRS,Standard_RAGRS,Standard_ZRS,Premium_LRS}]
                                 [--location LOCATION]
                                 [--kind {Storage,StorageV2,BlobStorage}]
                                 [--tags [TAGS [TAGS ...]]]
                                 [--custom-domain CUSTOM_DOMAIN]
                                 [--encryption-services {blob,file,table,queue} [{blob,file,table,queue} ...]]
                                 [--access-tier {Hot,Cool}]
                                 [--https-only [{true,false}]]
                                 [--bypass {None,Logging,Metrics,AzureServices} [{None,Logging,Metrics,AzureServices} ...]]
                                 [--default-action {Allow,Deny}]
                                 [--assign-identity]
az storage account create: error: __init__() got an unexpected keyword argument 'table'
```
