### ISSUE TITLE
[Test] Need mechanism to thoroughly test module imports

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#4224]
Recently we released a module whose `setup.py` file was missing some necessary entries in it's packages list, resulting in a non-functioning build. The CI did not catch this because it only ensures that the wheel file builds and that `az` runs. This approach is insufficient because it is not guaranteed to trigger the relevant imports.

When we run a module's tests, we run the `dev_setup.py` script which doesn't rely on the packages list. 

We need to ensure that our CI system will, as best as it can, detect packaging errors like this. Possible solutions:

- include additional metadata in `setup.py` that runs certain commands after wheel installation to ensure that no import errors are thrown. This should be fairly easy to implement but the downside is that not every command which could be chosen is guaranteed to trigger the imports.
- Run the tests using a wheel installation instead of a dev setup.  Since the tests aren't included in the packages, this could be tricky, but would be the most thorough option.

cc/ @mayurid

**Comment by tjprescott** [comment]
cc/ @troydai and @derekbekoe for thoughts on technical feasibility.

**Comment by troydai** [comment]
The live test today is doing this. And we can reorg our Travis CI automation logic to a formal: build -> install -> test flow.

**Comment by tjprescott** [comment]
It's good that the live tests will catch this, but then we need to have a policy to ensure that we examine a live test run after the last merge and prior to release to avoid this happening again in the future, which is pitfall rife for human error (mostly, forgetting).

If we could reconfigure the CI to do a "regular install" and then run the tests that would be ideal since the automation would catch this much faster.

**Comment by troydai** [comment]
@tjprescott we should do that. And it can probably save us more time by building package only once.
