### ISSUE TITLE
Resource show fails on resources with parentheses in the name

### ISSUE THREAD

**Issue by Krakenfall** [Azure/azure-cli#4225]
### Description
Command `az resource show` with a resource name that includes parentheses returns "--resource-type was unexpected at this time" in PowerShell 5.0 console.

### Repro Steps

* Open PowerShell console
* Run `az resource show -g "TestGroup" --name "ResourceName(NestedForSomeReason)" --resource-type "Microsoft.OperationsManagement/solutions"` (resource type is example)

Result:

```
--resource-type was unexpected at this time.
C:\WINDOWS\system32>  "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\\..\python.exe" -Im azure.cli resource show
 -g TestGroup --name ResourceName(NestedForSomeReason) --resource-type Microsoft.OperationsManagement/solutions
```

### Remarks

Parentheses are currently allowed (as far as I know) in resource names, so the CLI should be able to handle them. I know that the parentheses should probably be escaped somehow, but the CLI does not allow for parentheses to be escaped. Neither PowerShell escaping with ``--name "ResourceName`(NestedForSomeReason`)"`` nor python escaping with `--name "ResourceName\(NestedForSomeReason\)"` works.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.12

**OS Version:** What OS and version are you using?  
Answer here: Windows 10 Enterprise

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: PowerShell 5.1.14

**Comment by tjprescott** [comment]
The following syntaxes work:

**CMD.exe**
`az resource show -n name(stuff)`

**bash**
`az resource show -n 'name(stuff)'`

Powershell is not an actively supported shell for CLI 2.0. However, you could try:
`az resource show --% -n name(stuff)`

The `--%` is supposed to disable Powershell's inbuilt parsing for anything after the escape sequence.

**Comment by Krakenfall** [comment]
Thank you for the information. I appreciate knowing PowerShell is not currently supported. Unfortunately, using `--%` did not work, but I was able to work around the issue with 
```
cmd.exe /c "az resource show -g `"TestGroup`" --name `"ResourceName(NestedForSomeReason)`" --resource-type `"Microsoft.OperationsManagement/solutions`"" | Out-String
```

**Comment by sassdawe** [comment]
Hey @tjprescott, do you know if the supportability of PowerShell as the shell have changed in the past 5 years or so?

**Comment by tjprescott** [comment]
@sassdawe I'm no longer on the CLI team so I don't know that answer. @jiasli could you answer this?

**Comment by jiasli** [comment]
PowerShell is supported now.

You have to quote `ResourceName(NestedForSomeReason)` twice, one for PowerShell, one for CMD:

```
> az group --debug --name '"ResourceName(NestedForSomeReason)"'
cli.knack.cli: Command arguments: ['group', '--debug', '--name', 'ResourceName(NestedForSomeReason)']
```

See:

- https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md
- https://learn.microsoft.com/en-us/cli/azure/use-azure-cli-successfully#use-quotation-marks-in-parameters
