### ISSUE TITLE
Can't create vms in new regions

### ISSUE THREAD

**Issue by liorbiu** [Azure/azure-cli#4231]
### Description
I'm using azure cli to create vm in different regions. I 'm trying to create vm in germanycentral, southafricawest and centeralindia. According to this [link](https://azure.microsoft.com/en-us/regions/) this regions are available. When I'm trying to create vm in these regions I received the following error:

`ERROR: Deployment failed. The provided location 'centeralindia' is not available for resource type 'Microsoft.Network/virtualNetworks'. List of available regions for the resource type is 'westus,eastus,northeurope,westeurope,eastasia,southeastasia,northcentralus,southcentralus,centralus,eastus2,japaneast,japanwest,brazilsouth,australiaeast,australiasoutheast,centralindia,southindia,westindia,canadacentral,canadaeast,westcentralus,westus2,ukwest,uksouth,koreacentral,koreasouth'.`

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:2.0.12

**OS Version:** What OS and version are you using?  
Answer here: Ubuntu 16.04.2 LTS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by tjprescott** [comment]
Additionally, `centralindia` is also listed in the error message as being available for that resource type. @yugangw-msft do you think this is a service bug or are we compiling an erroneous help message?

**Comment by yugangw-msft** [comment]
> I 'm trying to create vm in germanycentral, southafricawest and centeralindia

The `centeralindia` has a typo, and the error message calls out the correct spelling of  `centralindia`
