### ISSUE TITLE
[VM] Certain VM scenarios require explicit specification of plan information

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#4233]
Initially reported by @huzferd in PR #4159.

Create Data Science VM using templates.
Create Image from DSVM.
Attempting to restore DSVM from Image yields the following error:
{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMMarketplaceInvalidInput",
        "message": "Creating a virtual machine from Marketplace image requires Plan information in the request. OS disk name is 'test1_disk1'."
      }
    ]
  }
}

**Comment by yugangw-msft** [comment]
I believe @huzferd  has already opened #4157 for this

**Comment by tjprescott** [comment]
I'll close that one as this outlines the issue rather than the proposed solution.
