### ISSUE TITLE
Adding confirmation to custom commands should not require adding a "yes" parameter to the command signature

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#4235]
I was working with a dev trying to create a custom command with confirmation.  He set "confirmation=True" in the command registration but then the command failed with "<operation> received unexpected keyword argument 'yes'."

The confirmation mechanism is built into the command execution template, so it should never be required (or desired) within a custom command.  Instead of being a `kwargs.get` operation, it should be a `kwargs.pop` operation. If the parameter should be accessible within the command, we should probably have less vague name than "yes".

**Comment by derekbekoe** [comment]
Closing in favor of https://github.com/Azure/azure-cli/issues/2520.
