### ISSUE TITLE
[ExpressRoute] express-route peering update operation does not recognize the –route-filter parameter

### ISSUE THREAD

**Issue by anzaman** [Azure/azure-cli#4241]
The update operation does not recognize the –route-filter parameter

Command
    az network express-route peering **update**: Update peering settings.

Arguments
    --peer-asn                  : Autonomous system number of the customer/connectivity provider.
    --primary-peer-subnet       : /30 subnet used to configure IP addresses for primary interface.
    --secondary-peer-subnet     : /30 subnet used to configure IP addresses for secondary interface.
    --shared-key                : Key for generating an MD5 for the BGP session.
    --vlan-id                   : Identifier used to identify the customer.

Resource Id Arguments
    --circuit-name              : ExpressRoute circuit name.
    --ids                       : One or more resource IDs (space delimited). If provided, no other
                                  'Resource Id' arguments should be specified.
    --name -n                   : The name of the peering.
    --resource-group -g         : Name of resource group. You can configure the default group using
                                  `az configure --defaults group=<name>`.

Microsoft Peering Arguments
    --advertised-public-prefixes: List of prefixes to be advertised through the BGP peering.
                                  Required to set up Microsoft Peering.
    --customer-asn              : Autonomous system number of the customer.
    --routing-registry-name     : Internet Routing Registry / Regional Internet Registry.  Allowed
                                  values: AFRINIC, ALTDB, APNIC, ARIN, LACNIC, LEVEL3, RADB,
                                  RIPENCC.

However it’s available in the “create” operation:

Command
    az network express-route peering create: Create peering settings.

Arguments
    --circuit-name          [Required]: ExpressRoute circuit name.
    --peer-asn              [Required]: Autonomous system number of the customer/connectivity
                                        provider.
    --peering-type          [Required]: BGP peering type for the circuit.  Allowed values:
                                        AzurePrivatePeering, AzurePublicPeering, MicrosoftPeering.
    --primary-peer-subnet   [Required]: /30 subnet used to configure IP addresses for primary
                                        interface.
    --resource-group -g     [Required]: Name of resource group. You can configure the default group
                                        using `az configure --defaults group=<name>`.
    --secondary-peer-subnet [Required]: /30 subnet used to configure IP addresses for secondary
                                        interface.
    --vlan-id               [Required]: Identifier used to identify the customer.
    --shared-key                      : Key for generating an MD5 for the BGP session.

Microsoft Peering Arguments
    --advertised-public-prefixes      : List of prefixes to be advertised through the BGP peering.
                                        Required to set up Microsoft Peering.
    --customer-asn                    : Autonomous system number of the customer.
    --route-filter                    : Name or ID of a route filter to apply to the peering
                                        settings.
    --routing-registry-name           : Internet Routing Registry / Regional Internet Registry.
                                        Allowed values: AFRINIC, ALTDB, APNIC, ARIN, LACNIC, LEVEL3,
                                        RADB, RIPENCC.

**Comment by tjprescott** [comment]
Currently this is blocked pending action from the service team

**Comment by tjprescott** [comment]
This should be fixed now.
