### ISSUE TITLE
[Network] VNET-Gateway/Connection New Features

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#4249]
**S2S Additions**
- [x] Support for new vnet gateway SKUs (VpnGw1, 2, 3). Update tests.
- [x] Scenario test for `vnet-gateway ipsec-policy` commands (https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-ipsecikepolicy-rm-powershell)
- [x] Add command `vnet-gateway list-bgp-peer-status`
- [x] Add command `vnet-gateway list-learned-routes`
- [x] Add command `vnet-gateway list-advertised-routes`

**P2S Addtions**
- [x] Add `--vpn-client-address-pool`  (all API versions)
- [x] Add `--radius-server`, `--radius-secret` and `--vpn-client-protocol` to `vnet-gateway create/update` (2017-06-01)
- [X] Add `vnet-gateway vpn-client generate` (2017-06-01)
- [ ]  <del>Add `vnet-gateway vpn-client show` (TBD)</del> Moved to #4390.

cc/ @aanandr

**Comment by lmazuel** [comment]
@tjprescott FYI https://github.com/Azure/azure-sdk-for-python/pull/1373
