### ISSUE TITLE
"az acs kubernetes get-credentials" ignores "--output" parameter

### ISSUE THREAD

**Issue by dmitsh** [Azure/azure-cli#4250]
### Description
**Outline the issue here:**

When running "az acs kubernetes get-credentials --help" command, it claims:

    --output -o                   : Output format.  Allowed values: json, jsonc, table, tsv.
                                    Default: json.

However, in reality the format of the output file is YAML, even though this format is not listed as supported, and the default format is JSON.
Setting "--output json" has no effect.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: interactive script

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.14

**OS Version:** What OS and version are you using?  
Answer here: Linux (Ubuntu 16.04)

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by tolu** [comment]
I've interpreted the global parameter `-o` (`--output`) as only affecting the output written to the console, and not (in this case) the format of the written file.

The interesting thing is how you say `az acs kubernetes get-credentials` always output `yaml` when (I'm having the same format issue but the other way around with) `az aks get-credentials` alyways seem to output **unquoted** `json` like so...

```
{apiVersion: v1, clusters: [{cluster: {certificate-authority-data: REDACTED,
        server: 'https://<REDACTED>.azmk8s.io:443'},
      name: k8s-ps-prod}], contexts: [{context: {cluster: k8s-ps-prod, user: REDACTED},
      name: k8s-ps-prod}], current-context: k8s-ps-prod, kind: Config, preferences: {},
  users: [{name: REDACTED, user: {client-certificate-data: REDACTED,
        client-key-data: REDACTED,
        token: REDACTED}}]}
```
