### ISSUE TITLE
Consistency between 'az vm unmanaged-disk' and 'az vm disk'

### ISSUE THREAD

**Issue by nneul** [Azure/azure-cli#4255]
### Description

Would be nice if the '-z' and '--disk' or '--name' options were consistent across the two commands. Right now, unmanaged doesn't have the -z option, and has --name instead of --disk. 

---

### Environment summary

**Install Method:** nightly
**CLI Version:** azure-cli (2.0.12+1.dev20170808)
**OS Version:** ubuntu 16.04 x64
**Shell Type:** bash

You should consider a 'az supportinfo' command to return the above in directly copy-pastable form.

**Comment by tjprescott** [comment]
If anything `-z` will go away on the managed disk command. It conflicts with a more "global" use of `-z` that is planned.

**Comment by tjprescott** [comment]
But definitely agree they should be consistent!
