### ISSUE TITLE
az network route-filter rule delete command does not delete the rule

### ISSUE THREAD

**Issue by anzaman** [Azure/azure-cli#4256]
I can’t delete a rule in a route filter, I run the following commands (in bold) but still see the rule (in italics)

**ali@Azure:~$ az network route-filter rule delete --filter-name MyRouteFilter -n CRM -g UOLDIVEO
ali@Azure:~$ az network route-filter list**
[
  {
    "etag": "W/\"d740dd4d-c66f-44d7-a231-e0ea6ceae982\"",
    "id": "/subscriptions/81ab786c-56eb-4a4d-bb5f-f60329772466/resourceGroups/Ascenty/providers/Microsoft.Network/routeFilters/MyRouteFilter",
    "location": "brazilsouth",
    "name": "MyRouteFilter",
    "peerings": null,
    "provisioningState": "Succeeded",
    "resourceGroup": "Ascenty",
    "rules": [
      _{
        "access": "Allow",
        "communities": [
          "12076:5040"
        ],
        "etag": "W/\"d740dd4d-c66f-44d7-a231-e0ea6ceae982\"",
        "id": "/subscriptions/81ab786c-56eb-4a4d-bb5f-f60329772466/resourceGroups/Ascenty/providers/Microsoft.Network/routeFilters/MyRouteFilter/routeFilterRules/CRM",
        "location": null,
        "name": "CRM",
        "provisioningState": "Succeeded",
        "resourceGroup": "Ascenty",
        "tags": null
      }_
    ],
    "tags": null,
    "type": "Microsoft.Network/routeFilters"
  },
  {
    "etag": "W/\"55530af5-d288-48b5-9e70-582461c8c0fe\"",
    "id": "/subscriptions/81ab786c-56eb-4a4d-bb5f-f60329772466/resourceGroups/UOLDIVEO/providers/Microsoft.Network/routeFilters/MyRouteFilter",
    "location": "brazilsouth",
    "name": "MyRouteFilter",
    "peerings": [
      {
        "azureAsn": null,
        "etag": null,
        "gatewayManagerEtag": null,
        "id": "/subscriptions/81ab786c-56eb-4a4d-bb5f-f60329772466/resourceGroups/UOLDIVEO/providers/Microsoft.Network/expressRouteCircuits/UOLDIVEOTest/peerings/MicrosoftPeering",
        "ipv6PeeringConfig": null,
        "lastModifiedBy": null,
        "microsoftPeeringConfig": null,
        "name": null,
        "peerAsn": null,
        "peeringType": null,
        "primaryAzurePort": null,
        "primaryPeerAddressPrefix": null,
        "provisioningState": null,
        "resourceGroup": "UOLDIVEO",
        "routeFilter": null,
        "secondaryAzurePort": null,
        "secondaryPeerAddressPrefix": null,
        "sharedKey": null,
        "state": null,
        "stats": null,
        "vlanId": null
      }
    ],
    "provisioningState": "Succeeded",
    "resourceGroup": "UOLDIVEO",
    "rules": [],
    "tags": null,
    "type": "Microsoft.Network/routeFilters"
  }
]

**Comment by tjprescott** [comment]
What version of the CLI are you running? I just tested this and it worked exactly as intended.

**Comment by anzaman** [comment]
I am using a CLI session from the Azure Portal

-Ali

**Comment by tjprescott** [comment]
I just tried it in a Cloud Shell session from the Portal and observed the same behavior. The delete was successful. Did you have any issues creating the rule?  When I do (in Cloud Shell or standalone) I get a weird deployment error but the rule is created (albeit in a Failed state).

**Comment by tjprescott** [comment]
I have tested this on the latest version in both stand-alone and Cloud Shell and it worked fine.
