### ISSUE TITLE
vm/vmss: expose an argument to configure data disks' storage skus

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#4263]
So far, in the `vm/vmss create` commands, the data disk defaults to the same sku of the os disk, which is not always what users want. There are scenarios a user can have 10+ data disks, and like to configure individuals. So the proposed change after discussed with @singhkays are:
1. Expose a `--data-disk-storage-skus` which accepts space separated sku list
2. Argument values can be just sku name which CLI will match with the lun in sequence; or users can pair with lun, e.g. `2=Premium_LRS`. For disks w/o sku specified, we go with the one used by os disk for backward compatibility. 

Examples:
1. `az vm create -g rg -n vm1 --image centos --data-disk-sizes-gb 10 20 --data-disk-storage-skus standard_lrs  standard_lrs`
2. `az vm create -g rg -n vm2 --image imageWith16DataDisks  --data-disk-storage-skus 2=standard_lrs 10=standard_lrs`

For mixing styles, CLI will throw for simplicity, but can change if there are asks
`az vm create -g rg -n vm2 --image imageWith16DataDisks  --data-disk-storage-skus standard_lrs 10=standard_lrs`

**Comment by singhkays** [comment]
@chagarw Please review

**Comment by yugangw-msft** [comment]
we have fixed this in sprint 50
```
    --storage-sku                  : The SKU of the storage account with which to persist VM. Use a
                                     singular sku that would be applied across all disks, or specify
                                     individual disks. Usage: [--storage-sku SKU | --storage-sku
                                     ID=SKU ID=SKU ID=SKU...], where each ID is "os" or a 0-indexed
                                     lun. Allowed values: Premium_LRS, StandardSSD_LRS,
                                     Standard_LRS, UltraSSD_LRS.
```
