### ISSUE TITLE
[ACS] location errors when creating k8 cluster

### ISSUE THREAD

**Issue by rbitia** [Azure/azure-cli#4271]
### Description
**Outline the issue here:**
eastus, eastus2, westus and more regions are not supported but the cli responds saying they are. 

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: apt-get 

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.14

**OS Version:** What OS and version are you using?  
Answer here: Windows 10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Bash on Windows 
![location issue cli 2](https://user-images.githubusercontent.com/7662363/29480766-ab96a3be-842f-11e7-86fe-59c775bf1925.PNG)
![location issue cli 1](https://user-images.githubusercontent.com/7662363/29480767-aba99d3e-842f-11e7-8797-e1eb0631381f.PNG)

**Comment by neilpeterson** [comment]
I believe this is related and that a fix has been merged into the CLI. All details are in the issue.

https://github.com/Azure/azure-cli/issues/4222

**Comment by rjtsdl** [comment]
@neilpeterson you are right. You can close this. The release should be cut shortly.
