### ISSUE TITLE
[ACS] improve cli documentation/example

### ISSUE THREAD

**Issue by weinong** [Azure/azure-cli#4273]
### Description
**Outline the issue here:**

---
1. the use of `--windows` flag is confusing. it will set the osType of all agent pools whose osType is nil?
2. `--agent-profiles` is very verbose because it's a json string. in fact, we can do `--agent-profiles @file.json`. please put this in the cli example

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

**OS Version:** What OS and version are you using?  
Answer here:

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

**Comment by rjtsdl** [comment]
@weinong, the introduction of multiple profiles, really makes some existing flags confusing. The existing flags are designed in the scope of only one agent pool exists. For example --windows, it just means the only agent pool is a windows agent pool. 

To make the existing flags still valid in the multiple profiles world, we underlying changed the definition a little bit. For example, --windows would imply the **default** osType of all the agent pools would be windows.  I guess, i need to change the documents iteratively to make things clearer.

I will send PR for sure.

**Comment by rjtsdl** [comment]
@tjprescott you can close it now.
