### ISSUE TITLE
Missing "set" or "update" option for dns records to allow updating ttl

### ISSUE THREAD

**Issue by nneul** [Azure/azure-cli#4276]
### Description

xplat cli allows for set to update TTL, there doesn't appear to be an equivalent in az other than create, and that does not feel right since the record already exists. (And scary when it says it will create an empty record in the case of cnames.)

I'd suggest a mostly copy-and-paste of create with the exception that it only does an update of the passed parameters. 

---

### Environment summary

**Install Method:** nightly
**CLI Version:** azure-cli (2.0.12+1.dev20170808)
**OS Version:** ubuntu 16.04 x64
**Shell Type:** bash

You should consider a 'az supportinfo' command to return the above in directly copy-pastable form.

**Comment by adewaleo** [comment]
@nneul, az does allow for updating the TTL for a dns record set (but not for an individual record).

`az network dns record-set a update --resource-group myresourcegroup --zone-name contoso.com --name www --set ttl=60`

Please see this [page](https://docs.microsoft.com/en-us/azure/dns/dns-operations-recordsets-cli#to-modify-the-ttl-of-an-existing-record-set) for more information.

**Comment by adewaleo** [comment]
I will go ahead and close this issue. I will also make sure to bring up the  `az supportinfo` command to the team.
