### ISSUE TITLE
Installing Azure CLI 2.0 on macOS with CLEAN setup failed

### ISSUE THREAD

**Issue by helenlivsc** [Azure/azure-cli#4277]
### Description
**Outline the issue here:**
Installing Azure CLI 2.0 on macOS with CLEAN setup failed. The error happens in building '_scandir' extension using cc command, with the error code about xcode-select: no developer tools were found at '/Applications/Xcode.app'.
We are preparing a bash script for end customers, and azure cli installation is a part of it. We wonder how to get azure cli smoothly installed on CLEAN macOS? For example is it possible to avoid such building work?
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: curl -L https://aka.ms/InstallAzureCli | bash (following webpage https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: That command should install latest version of CLI and the installation failed.

**OS Version:** What OS and version are you using?  
Answer here: macOS Sierra 10.12.6

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

![azureclionmac](https://user-images.githubusercontent.com/25995707/29510294-e382f038-868d-11e7-8b19-3214bfa51be3.jpg)

**Comment by tej001** [comment]
There is problem in installation scripts; 

You can apply patched manually and then install it should work. 

gcc 
libffi-devel
python-devel
openssl-devel

yum install gcc libffi-devel python-devel openssl-devel

Tej

**Comment by helenlivsc** [comment]
Yum is not built-in command in clean macOS. What is your recommended way to install yum?

**Comment by helenlivsc** [comment]
Yum is not built-in command in clean macOS. What is your recommended way to install yum?

**Comment by derekbekoe** [comment]
@helenlivsc see https://github.com/Azure/azure-cli/issues/1522#issuecomment-298716269

**Comment by derekbekoe** [comment]
Closing. Comment if you still have issues.

**Comment by helenlivsc** [comment]
I suppose the issue here is different from https://github.com/Azure/azure-cli/issues/1522#issuecomment-298716269. We are talking about clean MacOs.

Per tej001, it is a problem in installation scripts. When will you plan to fix it?

**Comment by derekbekoe** [comment]
On a fresh machine, if you only run `curl -L https://aka.ms/InstallAzureCli | bash`, the xcode prompt should also appear automatically then after installation of the xcode feature, you can run the install script again.

If the xcode prompt doesn't appear, this below will work:
```
xcode-select --install
curl -L https://aka.ms/InstallAzureCli | bash
```
