### ISSUE TITLE
Dedicated log config argument for Docker Container logging?

### ISSUE THREAD

**Issue by Benjiiim** [Azure/azure-cli#4279]
### Description

In order to activate the "Docker Container logging" setting of a Linux web app, we have to use the --web-server-logging argument of az webapp log config.

As Docker is definitly not the web server, shouldn't we have an other argument dedicated to the Linux-based Docker Container logging feature?

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: apt-get

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
azure-cli (2.0.14)

acr (2.0.10)
acs (2.0.13)
appservice (0.1.13)
batch (3.1.1)
billing (0.1.3)
cdn (0.0.6)
cloud (2.0.7)
cognitiveservices (0.1.6)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.10)
consumption (0.1.3)
container (0.1.8)
core (2.0.13)
cosmosdb (0.1.11)
dla (0.0.10)
dls (0.0.12)
eventgrid (0.1.2)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.7)
iot (0.1.10)
keyvault (2.0.8)
lab (0.0.9)
monitor (0.0.8)
network (2.0.12)
nspkg (3.0.1)
profile (2.0.10)
rdbms (0.0.5)
redis (0.2.7)
resource (2.0.12)
role (2.0.10)
sf (1.0.6)
sql (2.0.9)
storage (2.0.12)
vm (2.0.12)

Python (Linux) 3.6.1 (default, Aug 17 2017, 10:48:15)
[GCC 4.8.4]

Python location '/opt/az/bin/python3'

**OS Version:** What OS and version are you using?  
Answer here: W10 1607

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Bash on Windows

**Comment by yugangw-msft** [comment]
//cc: @ahmedelnably

**Comment by yugangw-msft** [comment]
We should consider this when we re-organize the command tree for better supports towards the linux webapp

**Comment by ahmedelnably** [comment]
@LukaszStem has this planned

**Comment by ahmedelnably** [comment]
PR: https://github.com/Azure/azure-cli/pull/4718
