### ISSUE TITLE
vm: support "Run Command"

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#4286]

**Comment by tjprescott** [comment]
What is this?

**Comment by yugangw-msft** [comment]
Detail will follow, but at a high level, it is about to run specified commands in a VM you are managing
API is [here](https://github.com/Azure/azure-rest-api-specs/blob/current/specification/compute/resource-manager/Microsoft.Compute/2017-03-30/runCommands.json)

**Comment by yugangw-msft** [comment]
#4444 fixed it

**Comment by gregjhogan** [comment]
@yugangw-msft I tried the API out in the beginning of September, and I found that once you used "run command" the custom script extension would fail to deploy (it would say it was already in use on the VM) and there seemed to be no way to fix that issue (no way to remove/cleanup and get back to a state where you could use the custom script extension again).  Is that still the case?

**Comment by yugangw-msft** [comment]
@gregjhogan , I tried out just now and it works for me. FYI, the commands I tried are
```
az vm run-command invoke -g yugangw -n yugangw-1 --command-id RunShellScript --script "sudo apt-get update && sudo apt-get install -y nginx"

az vm extension set -g yugangw --vm-name yugangw-1 -n customScript --publisher Microsoft.Azure.Extensions --settings "{\"commandToExecute\": \"ls\"}" --version 2.0
```

Run-command is built on top of custom script extension. Maybe you can cross check the version you  are trying to install, though regardless this should work even with older version

**Comment by gregjhogan** [comment]
Linux did always work fine, but Windows did not.  I tested windows again and there are some peculiarities, but I was able to deploy the custom script extension after using the runCommand action.  It seems like it is really geared toward only using one or the other (or it is just a little rough around the edges still and will improve over time).
