### ISSUE TITLE
Not seeing correlation IDs on deployment errors with `az group deployment create`

### ISSUE THREAD

**Issue by seanknox** [Azure/azure-cli#4288]
### Description
**Outline the issue here:**
This might be [pebkac](https://en.wikipedia.org/wiki/User_error), but we're stumped trying to figure out why correlation IDs are seemingly not being returned on failed deployments using ARM templates.

We're using the following command to create deployments with ARM templates:
```
	az group deployment create \
		--name "${DEPLOYMENT_NAME}" \
		--resource-group "${RESOURCE_GROUP}" \
		--template-file "${OUTPUT}/azuredeploy.json" \
		--parameters "@${OUTPUT}/azuredeploy.parameters.json"
```
On some subscriptions, we see the correlation ID returned on errors, e.g.
```
/usr/local/bin/az
ERROR: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "OSProvisioningTimedOut",
        "message": "OS Provisioning for VM 'k8s-master-26938380-0' did not finish in the allotted time. The VM may still finish provisioning successfully. Please check provisioning state later."
      }
    ]
  }
}  Correlation ID: cc3b6940-e73c-4853-8720-714960725a7e
```

On some newly created internal (Azure) subs, we're not seeing it:
```
/usr/local/bin/az
ERROR: Deployment failed. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "OSProvisioningTimedOut",
        "message": "OS Provisioning for VM 'k8s-agentpri-18601064-1' did not finish in the allotted time. The VM may still finish provisioning successfully. Please check provisioning state later."
      }
    ]
  }
}
```

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: `pip install --disable-pip-version-check --no-cache-dir azure-cli==2.0.10`

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: `2.0.10`

**OS Version:** What OS and version are you using?  
Answer here: Ubuntu

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by tjprescott** [comment]
If you run the command with --debug do you see the correlation anywhere inside the response object?

**Comment by seanknox** [comment]
I see `x-ms-correlation-request-id` in the debug output, is that it?

https://gist.github.com/seanknox/a60cedc9a39a0c51ae5677367d57b371#file-azure-cli-debug-txt-L663

**Comment by tjprescott** [comment]
That should be it. We'll take a look at why this isn't being extracted.

**Comment by seanknox** [comment]
Thanks. If helpful, can provide you a couple subs where this is happening (and subs where correlation is being output).
