### ISSUE TITLE
paramiko.transport : Exception: Error reading SSH protocol banner Windows 10 Pro

### ISSUE THREAD

**Issue by iniside** [Azure/azure-cli#4294]
### Description
**Outline the issue here:**

Error when I try to:
az acs kubernetes get-credentials --resource-group=myResource --name=myCluter --debug
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
MSI.
**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
azure-cli (2.0.14)

acr (2.0.10)
acs (2.0.13)
appservice (0.1.13)
batch (3.1.1)
billing (0.1.3)
cdn (0.0.6)
cloud (2.0.7)
cognitiveservices (0.1.6)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.10)
consumption (0.1.3)
container (0.1.8)
core (2.0.13)
cosmosdb (0.1.11)
dla (0.0.10)
dls (0.0.12)
eventgrid (0.1.2)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.7)
iot (0.1.10)
keyvault (2.0.8)
lab (0.0.9)
monitor (0.0.8)
network (2.0.12)
nspkg (3.0.1)
profile (2.0.10)
rdbms (0.0.5)
redis (0.2.7)
resource (2.0.12)
role (2.0.10)
sf (1.0.6)
sql (2.0.9)
storage (2.0.12)
vm (2.0.12)

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
**OS Version:** What OS and version are you using?  
Answer here:
Windows 10
**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
PowerShell

Debug info:

File logging enabled - Writing logs to 'C:\Users\Lukasz\.azure\logs'.
Command arguments ['acs', 'kubernetes', 'get-credentials', '--resource-group=unrealACSResource', '--name=unrealCluster']
Current cloud config:
{'endpoints': {'active_directory': 'https://login.microsoftonline.com',
               'active_directory_data_lake_resource_id': 'https://datalake.azure.net/',
               'active_directory_graph_resource_id': 'https://graph.windows.net/',
               'active_directory_resource_id': 'https://management.core.windows.net/',
               'batch_resource_id': 'https://batch.core.windows.net/',
               'gallery': 'https://gallery.azure.com/',
               'management': 'https://management.core.windows.net/',
               'resource_manager': 'https://management.azure.com/',
               'sql_management': 'https://management.core.windows.net:8443/',
               'vm_image_alias_doc': 'https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/qu
ickstart-templates/aliases.json'},
 'is_active': True,
 'name': 'AzureCloud',
 'profile': 'latest',
 'suffixes': {'azure_datalake_analytics_catalog_and_job_endpoint': 'azuredatalakeanalytics.net',
              'azure_datalake_store_file_system_endpoint': 'azuredatalakestore.net',
              'keyvault_dns': '.vault.azure.net',
              'sql_server_hostname': '.database.windows.net',
              'storage_endpoint': 'core.windows.net'}}
Registered application event handler 'CommandTableParams.Loaded' at <function add_id_parameters at 0x03A8F7C8>
Registered application event handler 'CommandTable.Loaded' at <function add_id_parameters at 0x03A8F7C8>
Successfully loaded command table from module 'acs'.
Application event 'CommandTable.Loaded' with event data {'command_table': {'acs kubernetes get-credentials': <azure.cli.
core.commands.CliCommand object at 0x03A9CA30>}}
Application event 'CommandParser.Loaded' with event data {'parser': AzCliCommandParser(prog='az', usage=None, descriptio
n=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)}
Registered application event handler 'CommandParser.Parsed' at <function _handle_container_ssh_file at 0x0457EDF8>
Application event 'CommandTableParams.Loaded' with event data {'command_table': {'acs kubernetes get-credentials': <azur
e.cli.core.commands.CliCommand object at 0x03A9CA30>}}
Application event 'CommandParser.Parsing' with event data {'argv': ['acs', 'kubernetes', 'get-credentials', '--resource-
group=unrealACSResource', '--name=unrealCluster']}
Application event 'CommandParser.Parsed' with event data {'command': 'acs kubernetes get-credentials', 'args': Namespace
(_command_package='acs', _jmespath_query=None, _log_verbosity_debug=False, _log_verbosity_verbose=False, _output_format=
'jsonc', _parser=AzCliCommandParser(prog='az acs kubernetes get-credentials', usage=None, description='Download and inst
all kubectl credentials from the cluster master', formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='er
ror', add_help=True), _validators=[], command='acs kubernetes get-crede [...]
Getting management service client client_type=ContainerServiceClient
attempting to read file C:\Users\Lukasz\.azure\accessTokens.json as utf-8-sig
adal-python : 462955bd-7638-42bc-84f1-c6280b741723 - Authority:Performing instance discovery: https://login.microsoftonl
ine.com/e741d6c9-de27-4487-8ae9-0c5df9ac759b
adal-python : 462955bd-7638-42bc-84f1-c6280b741723 - Authority:Performing static instance discovery
adal-python : 462955bd-7638-42bc-84f1-c6280b741723 - Authority:Authority validated via static instance discovery
adal-python : 462955bd-7638-42bc-84f1-c6280b741723 - TokenRequest:Getting token from cache with refresh if necessary.
adal-python : 462955bd-7638-42bc-84f1-c6280b741723 - OAuth2Client:finding with query: {"_clientId": "04b07795-8ddb-461a-
bbee-02f9e1bf7b46", "userId": "iniside@live.com"}
adal-python : 462955bd-7638-42bc-84f1-c6280b741723 - OAuth2Client:Looking for potential cache entries:
adal-python : 462955bd-7638-42bc-84f1-c6280b741723 - OAuth2Client:{"_clientId": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
"userId": "iniside@live.com"}
adal-python : 462955bd-7638-42bc-84f1-c6280b741723 - OAuth2Client:Found 3 potential entries.
adal-python : 462955bd-7638-42bc-84f1-c6280b741723 - OAuth2Client:Resource specific token found.
adal-python : 462955bd-7638-42bc-84f1-c6280b741723 - OAuth2Client:Returning token from cache lookup, AccessTokenId: b'XB
JdhD8ahPg2UuhgqfCrI+5fLX/lC+xkFQUc62fuzhM=', RefreshTokenId: b'n2ff1+BuOggHN2moewVtGXFVg6gplAU4RowYo0y86N8='
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring proxies: ''
msrest.pipeline : Evaluate proxies against ENV settings: True
msrest.pipeline : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com
urllib3.connectionpool : https://management.azure.com:443 "GET /subscriptions/b9a29aba-5bcd-45dd-99e5-8971de90d595/resou
rceGroups/unrealACSResource/providers/Microsoft.ContainerService/containerServices/unrealCluster?api-version=2017-01-31
HTTP/1.1" 200 None
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/b9a29aba-5bcd-45dd-99e5-8971de90d595/resou
rceGroups/unrealACSResource/providers/Microsoft.ContainerService/containerServices/unrealCluster?api-version=2017-01-31'
msrest.http_logger : Request method: 'GET'
msrest.http_logger : Request headers:
msrest.http_logger :     'User-Agent': 'python/3.6.1 (Windows-10-10.0.15063-SP0) requests/2.18.4 msrest/0.4.11 msrest_az
ure/0.4.11 containerserviceclient/1.0.0 Azure-SDK-For-Python AZURECLI/2.0.13'
msrest.http_logger :     'Accept-Encoding': 'gzip, deflate'
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'Connection': 'keep-alive'
msrest.http_logger :     'Authorization': '*****'
msrest.http_logger :     'x-ms-client-request-id': 'e06e5aa4-8768-11e7-84f2-bc5ff4f8b422'
msrest.http_logger :     'CommandName': 'acs kubernetes get-credentials'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger : Request body:
msrest.http_logger : None
msrest.http_logger : Response status: 200
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Transfer-Encoding': 'chunked'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Content-Encoding': 'gzip'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'Vary': 'Accept-Encoding'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'x-ms-served-by': '2aba321f-7e48-4758-a187-3d461a4519ef_131461035145247507'
msrest.http_logger :     'x-ms-request-id': '7d817d04-0ff5-4024-b7ee-e14529b8d714'
msrest.http_logger :     'Server': 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-reads': '14999'
msrest.http_logger :     'x-ms-correlation-request-id': '76a517dc-ca37-4494-89fa-dd5395aaa632'
msrest.http_logger :     'x-ms-routing-request-id': 'WESTEUROPE:20170822T183656Z:76a517dc-ca37-4494-89fa-dd5395aaa632'
msrest.http_logger :     'Date': 'Tue, 22 Aug 2017 18:36:55 GMT'
msrest.http_logger : Response content:
msrest.http_logger : Body contains chunked data.
paramiko.transport : starting thread (client mode): 0x38bc030
paramiko.transport : Local version/idstring: SSH-2.0-paramiko_2.2.1
paramiko.transport : Exception: Error reading SSH protocol banner
paramiko.transport : Traceback (most recent call last):
paramiko.transport :   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\paramiko\transport.py",
line 1952, in _check_banner
paramiko.transport :     buf = self.packetizer.readline(timeout)
paramiko.transport :   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\paramiko\packet.py", lin
e 353, in readline
paramiko.transport :     buf += self._read_timeout(timeout)
paramiko.transport :   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\paramiko\packet.py", lin
e 546, in _read_timeout
paramiko.transport :     raise socket.timeout()
paramiko.transport : socket.timeout
paramiko.transport :
paramiko.transport : During handling of the above exception, another exception occurred:
paramiko.transport :
paramiko.transport : Traceback (most recent call last):
paramiko.transport :   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\paramiko\transport.py",
line 1805, in run
paramiko.transport :     self._check_banner()
paramiko.transport :   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\paramiko\transport.py",
line 1957, in _check_banner
paramiko.transport :     'Error reading SSH protocol banner' + str(e)
paramiko.transport : paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
paramiko.transport :
Error reading SSH protocol banner
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\paramiko\transport.py", line 1952, in _check_
banner
    buf = self.packetizer.readline(timeout)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\paramiko\packet.py", line 353, in readline
    buf += self._read_timeout(timeout)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\paramiko\packet.py", line 546, in _read_timeo
ut
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\application.py", line 211, in
execute
    result = expanded_arg.func(params)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 35
1, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 55
5, in _execute_command
    reraise(*sys.exc_info())
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\six.py", line 686, in reraise
    raise value
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 53
2, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acs\custom.py", lin
e 785, in k8s_get_credentials
    _k8s_get_credentials_internal(name, acs_info, path, ssh_key_file)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acs\custom.py", lin
e 806, in _k8s_get_credentials_internal
    '.kube/config', path_candidate, key_filename=ssh_key_file)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\acs\acs_client.py",
 line 62, in secure_copy
    ssh.connect(host, username=user, pkey=pkey)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\paramiko\client.py", line 366, in connect
    t.start_client(timeout=timeout)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\paramiko\transport.py", line 510, in start_cl
ient
    raise e
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\paramiko\transport.py", line 1805, in run
    self._check_banner()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\paramiko\transport.py", line 1957, in _check_
banner
    'Error reading SSH protocol banner' + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

**Comment by rjtsdl** [comment]
Take a bit of research on this specific error. 
https://stackoverflow.com/questions/25609153/paramiko-error-reading-ssh-protocol-banner 

Looks this thread explained all. @iniside have you done retries?

**Comment by yugangw-msft** [comment]
closing as `az acs` is deprecating
