### ISSUE TITLE
az vmss get-instance-view --instance-id "*" returns wrong latestModelApplied  value 

### ISSUE THREAD

**Issue by iljoong** [Azure/azure-cli#4296]
### Description
When executing `az vmss get-instance-view --instance-id "*"` returns wrong  `latestModelApplied` value 

I used this command for checking `latestModelApplied` of all VM instances but it always returns 'false' 

```
    "latestModelApplied": false,
    "licenseType": null,
    "location": null,
    "name": null,
   ...
```

Where as with `az vmss show --instance-id #n`, I can get correct value

```
  "instanceId": "7",
  "instanceView": null,
  "latestModelApplied": true,
  "licenseType": null,
   ...
```
FYI, az vmss show does not support multi-instance for `--instance-id` option, that is `*`

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)
  
Azure cloud shell & apt-get

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  

azure-cli (2.0.14)

**OS Version:** What OS and version are you using?  

Windows 10 Ubuntu

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  

Bash on Windows

**Comment by tjprescott** [comment]
The reason is because "get-instance-view" only retrieves the instance view, and this property is not part of that. Thus the surrounding "non-instance view" properties are all `null` and unfortunately that Boolean gets deserialized to False (as opposed to null which would suggest Unknown).

You'll notice if you run the command with a number instead of a * that there's no mention of this property. I'll create a PR so the * case works the same as the individual case.

**Comment by iljoong** [comment]
I noticed the difference of output of  single instance and multi instances. Thank you for the explanation. 

I used this command to get status of ` latestModelApplied ` of all instances, like below command.
```
az vmss get-instance-view -n myvmss -g rgname --instance-id "*" --query "[].[instanceId, latestModelApplied]" -o tsv
```

I tried `az vmss show` command but it does not support `--instance-id *`. Any suggestion to achieve my goal?

**Comment by tjprescott** [comment]
`az vmss list-instances --query "[].[instanceId, latestModelApplied]" -o tsv -g {rg} -n {name}`

**Comment by iljoong** [comment]
Thanks!
