### ISSUE TITLE
Use newer azure-graphrbac Python SDK package

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#4300]
This is to get rid of the usage of "api-version=1.6-internal"

**Comment by lmazuel** [comment]
Avoid 0.30.0 that is broken, and directly move to 0.31.0

**Comment by derekbekoe** [comment]
@lmazuel and @yugangw-msft please take a look at my linked PR.

I am working on packaging for Homebrew and this is currently blocked because 
```
azure-graphrbac 0.30.0rc6 has requirement azure-common[autorest]==1.1.4, but you have azure-common 1.1.8.
```

The newer version of `azure-graphrbac` fixes this - https://github.com/Azure/azure-sdk-for-python/blob/master/azure-graphrbac/setup.py#L82.
