### ISSUE TITLE
--name (Disk Name) on az disk show should be an optional parameter

### ISSUE THREAD

**Issue by singhkays** [Azure/azure-cli#4301]
### Description
--name (Disk Name) on az disk show should be an optional parameter

```
➜  ~ az disk show -g kdockerrg
usage: az disk show [-h] [--output {json,tsv,table,jsonc}] [--verbose]
                    [--debug] [--query JMESPATH]
                    [--resource-group RESOURCE_GROUP_NAME] [--name NAME]
                    [--ids RESOURCE_ID [RESOURCE_ID ...]]
az disk show: error: (--name | --ids) are required
```

There is an API available to list all disks in an RG, so --name should be an optional parameter

`https://management.azure.com/subscriptions/<sub-id>/resourceGroups/<rg-name>/providers/Microsoft.Compute/disks?api-version=2017-03-30`

cc: @yugangw-msft @chagarw

**Comment by yugangw-msft** [comment]
`az disk list` expose this support

**Comment by singhkays** [comment]
@yugangw-msft Got it, thanks!
