### ISSUE TITLE
No error when creating NIC tied to VNet in different resource group

### ISSUE THREAD

**Issue by inhifistereo** [Azure/azure-cli#4309]
### Description
I'm attempting to create a NIC in the "VMs" resource group tied to vnet1 in the "VNets" resource group. I'm using the following CLI statement:

`az network nic create -g vms --vnet-name vnet1 --subnet default -n MyNic4`

I retrieve the following once the CLI runs:

`{}`

Further, no NIC is created in Azure.

When I create the NIC in the "VNets" resource group the NIC is successfully created. Is this desired behavior?

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: curl cmd

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 
azure-cli (2.0.1)

acs (2.0.1)
appservice (0.1.1b6)
batch (0.1.1b5)
cloud (2.0.0)
component (2.0.0)
configure (2.0.1)
container (0.1.1b4)
core (2.0.1)
documentdb (0.1.1b2)
feedback (2.0.0)
find (0.0.1b1)
iot (0.1.1b3)
keyvault (0.1.1b6)
network (2.0.1)
nspkg (2.0.0)
profile (2.0.1)
redis (0.1.1b3)
resource (2.0.1)
role (2.0.0)
sql (0.1.1b6)
storage (2.0.1)
vm (2.0.1)

**OS Version:** What OS and version are you using?  
Answer here: macOS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: macOS Terminals

**Comment by tjprescott** [comment]
I am surprised it doesn't give an error. I'll take a look.

However, to use a vnet that is in a different resource group, you need to supply the full Azure resource ID.

**Comment by tjprescott** [comment]
Your CLI version is out of date. I tried this on the latest version and it gives an error (as expected).

**Comment by inhifistereo** [comment]
Upgrading fixed my issue.

My reaction upon seeing my CLI version was out of date:

![ ](https://media.giphy.com/media/TwtXMS5EnKDBK/giphy.gif)
