### ISSUE TITLE
Creating a Linux VM in Azure Stack by using "az vm create" command is resulting in admin user name validation error

### ISSUE THREAD

**Issue by SnehaGunda** [Azure/azure-cli#4315]
### Description
**Outline the issue here:**

Creating a Linux VM in azure stack is failing with a admin name validation issue. The admin user name is always validated even if we don't pass the parameter. The following command works in Azure but not in Azure Stack environment.

Command: az vm create --resource-group LinuxVMRG123 --name demouser --image UbuntuLTS --generate-ssh-keys

![image](https://user-images.githubusercontent.com/14284405/29694713-15965d50-88f3-11e7-9313-6292e70045de.png)

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.10

**OS Version:** What OS and version are you using?  
Answer here: Windows Server 2016 

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Bash

**Comment by bganapa** [comment]
@derekbekoe @JasonRShaver any idea about this error?

**Comment by derekbekoe** [comment]
By default, it uses the current user:

e.g. on my machine
```
$ az vm create -h
Authentication Arguments
    --admin-password                   : Password for the VM if authentication type is 'Password'.
    --admin-username                   : Username for the VM.  Default: derekb.
```

**Comment by tjprescott** [comment]
If your username is "AzureStackAdmin" (which is what it looks like from your screenshot) then that is why it fails.  You can supply `--admin-username` and it should work fine. We also could arguably take the lowercase version of the current user, which would probably also be fine. It's not too adventurous but would save people some headache. @derekbekoe thoughts?

**Comment by yugangw-msft** [comment]
failed on public cloud as well. The error is good and comes back pretty quick, hence we don't need client end polishing
