### ISSUE TITLE
az storage account generate-sas --expiry precision

### ISSUE THREAD

**Issue by Zureka** [Azure/azure-cli#4316]
### Description

Attempting to generate a sas token with seconds precision fails:

`az storage account generate-sas: error: argument --expiry: invalid datetime_type value: '2017-08-25T12:27:03'`

In Powershell, the Get-Date cmdlet provides quick format options for SortableDateTimePattern and UniversalSortableDateTimePattern which both include seconds. Using these formats results in the error above.

Fails:            `2017-08-25T12:27:03`
Succeeds:   `2017-08-25T12:27Z`

[Similar to closed issue #1560](https://github.com/Azure/azure-cli/issues/1560)

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: interactive script

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.14

**OS Version:** What OS and version are you using?  
Answer here: Mac OSX Sierra 10.12.6

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Powershell on OSX

**Comment by tjprescott** [comment]
To clarify, are you saying that you can't use seconds to generate a SAS in PS either or simply that the format you got from a PS cmdlet fails in the CLI?

**Comment by Zureka** [comment]
The latter. For some context, I'm currently switching from using the ARM PS cmdlets to Azure CLI, and using the `New-AzureStorageContainerSASToken` cmdlet I am able to specify an `-ExpiryTime (Get-Date).AddHours(4)` without issues. 

The formats for dates in PS include seconds which isn't allowed in the format specified for the CLI: `(Y-m-d'T'H:M'Z')`. My expectation would be for the seconds precision to not make a difference in this case and should be allowed as part of the `-expiry` argument in the CLI.

**Comment by troydai** [comment]
Can you try adding a 'Z' at the end of your time string?

https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_validators.py#L821

**Comment by Zureka** [comment]
@troydai That does resolve the issue I had. I ended up using the SortableDateTimePattern and concatenating a 'Z' on the end. It's a bummer that there's not an option available in PS that fits this pattern but that's not a problem I expect you guys to solve. 

Thanks!

**Comment by troydai** [comment]
You're welcome, @Zureka .

**Comment by sumanthkannedari** [comment]
Can you please help me how to auto generate the SAS Token for every 3 or 5 seconds through powershell and how the resources can access the auto generated SAS Token

**Comment by rohancragg** [comment]
> I ended up using the SortableDateTimePattern and concatenating a 'Z' on the end.

For anyone reading this - the following also works:

`--expiry (Get-Date).AddMinutes(30).ToString("yyyy-MM-dTH:mZ")`

**Comment by kevinferretti** [comment]
> > I ended up using the SortableDateTimePattern and concatenating a 'Z' on the end.
> 
> For anyone reading this - the following (in PowerShell) also works:
> 
> `--expiry (Get-Date).AddMinutes(30).ToString("yyyy-MM-dTH:mZ")`

Just noting that I needed to add `.ToUniversalTime()` to this so it becomes:

`--expiry (Get-Date).ToUniversalTime().AddMinutes(30).ToString("yyyy-MM-dTH:mZ")`
