### ISSUE TITLE
CosmosDb - Parameter 'ConsistencyPolicy.max_interval_in_seconds' must be less than 100. Need to set to 300 for multi-region.

### ISSUE THREAD

**Issue by andscho-msft** [Azure/azure-cli#4317]
### Description
**Outline the issue here:**
To enable multi-region with bounded staleness, it is required to set the maximum lag time to 5 minutes (300 seconds). This is possible in the Azure portal.

The CLI has validation that rejects any number higher than 100. I don't think this validation is correct.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
pip
**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
azure-cli (2.0.12)

acr (2.0.4)
acs (2.0.6)
appservice (0.1.6)
batch (2.0.4)
billing (0.1.0)
cdn (0.0.2)
cloud (2.0.2)
cognitiveservices (0.1.2)
command-modules-nspkg (2.0.0)
component (2.0.4)
configure (2.0.6)
consumption (0.1.0)
container (0.1.1b4)
core (2.0.12)
cosmosdb (0.1.6)
dla (0.0.6)
dls (0.0.6)
documentdb (0.1.1b2)
feedback (2.0.2)
find (0.2.2)
interactive (0.3.1)
iot (0.1.5)
keyvault (2.0.8)
lab (0.0.4)
monitor (0.0.4)
network (2.0.6)
nspkg (3.0.0)
profile (2.0.4)
rdbms (0.0.1)
redis (0.2.3)
resource (2.0.6)
role (2.0.4)
sf (1.0.1)
sql (2.0.3)
storage (2.0.6)
vm (2.0.12)

Python (Windows) 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]

Python location 'C:\Python35\python.exe'
**OS Version:** What OS and version are you using?  
Answer here:
Windows 10
**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
powershell

**Comment by moderakh** [comment]
This is account management API not data plane api. Should be assigned to digvijay @dmakwana who owns account mgt API.

**Comment by andscho-msft** [comment]
Ping

**Comment by dmakwana** [comment]
@andscho-msft Thanks for creating this issue. I have filed a PR which will allow us to publish a new version of the Python SDK with this fix. CLI issue should be resolved shortly after.

**Comment by lmazuel** [comment]
Fixed in SDK Mgmt package 0.2.1
https://pypi.python.org/pypi/azure-mgmt-cosmosdb/0.2.1

**Comment by shurd** [comment]
The CLI now uses version 0.5.2 of the SDK management, which contains this fix.
