### ISSUE TITLE
az vm encryption enable- doesn't allow for different key vault resource group

### ISSUE THREAD

**Issue by nahalf** [Azure/azure-cli#4318]
### Description
**Outline the issue here:**
az vm encryption enable cmd does not allow specifying a different resource group for the key vault from the resource group the VM resides in. Az CLI 1.0 did allow for this. I can perform disk encryption via PowerShell though on the same VM and with the same Key Vault.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: used CloudShell

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: az --version 2.0

**OS Version:** What OS and version are you using?  
Answer here: Windows 10 15063.540

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Cloud Shell in Azure portal

**Comment by tjprescott** [comment]
Hi @nahalf, the keyvault parameters should accept the name or ID of the keyvault you want to use.  To use cross-RG resources, you must specify the ID.  This is standard across the CLI. 

If this doesn't work then there's a bug.  Regardless, the help text should make it clear that you should provide the name or ID of the KeyVault resource (especially since someone might expect to provide the keyvault URL).

**Comment by nahalf** [comment]
@tjprescott I provided the resourceID in this format: /subscriptions/3fd58db1-6100-4fa1-b575-5856e3364898/resourceGroups/s00140nrgpkvt00001/providers/Microsoft.KeyVault/vaults/s00140cnkvt00001

I provided a value of TestRG for  the VM resource group, and I received this error message:
key Vault https://s00140cnkvt00001.vault.azure.net/secrets/7CFFFBA6-5ACA-41E5-9FAE-72E9CD7629F6/876d366d2a8446e696c2b58847c26ce7 either has not been enabled for Volume Encryption or the vault id provided does not match /subscriptions/3fd58db1-6100-4fa1-b575-5856e3364898/resourceGroups/TestRG/providers/Microsoft.KeyVault/vaults/s00140cnkvt00001's true resource id.

So even though the resourceID indicates belonging to a different resource group, it is still attempting to find the key vault in the TestRG resource group, which makes it sound like there's a bug.

**Comment by tjprescott** [comment]
@yugangw-msft can you look into this?

**Comment by peterlil** [comment]
I'm experiencing the exact same problem.

**Comment by yugangw-msft** [comment]
@peterlil  @nahalf, what OS does your VM have? CLI does support using key-vault from other resource group. For example, the following command works for me
```bash
az vm encryption enable -g yugangw3 -n yugangw3-2 --aad-client-id e7c210e6-a714-4743-b81d-ad5b65xxxxxx --aad-client-secret 'xxxx' --disk-encryption-keyvault /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272xxxxxx/resourceGroups/yugangw/providers/Microsoft.KeyVault/vaults/yugangw-xxxxxxx --volume-type all
```
One cause of the error you mentioned is the keyvault has not been configured with the permission of `enabledForDiskEncryption`. Please double check

**Comment by peterlil** [comment]
I used the wrong OS. I tried with CentOS 7.3 when I got the error. Just now I ran the same scripts again (from scratch) but I used RHEL7.2, and it worked.

**Comment by yugangw-msft** [comment]
@peterlil, I will report this bad error to the ADE team. 
CentOS 7.3 is not in the supported OS distro list for encryption. If you created the VM from PIR images, CLI command should emit out a warning. For your reference, the list is [here](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/disk_encryption.py#L330-L362)

**Comment by tjprescott** [comment]
Since this issue was about not accepting cross RG keyvaults and you are able to do so, I will close this.

**Comment by lhardison** [comment]
I think I'm running into this issue currently on an Ubuntu 16 VM on a support VHost.

I got this error when trying to use the Azure CLI 2.0 commands to encrypt the host;

`Deployment failed. Tracking ID: <snip>. Key Vault https://<snip>.vault.azure.net/keys/<snip>Key01/<snip> either has not been enabled for Volume Encryption or the vault id provided does not match /subscriptions/<snip>/resourceGroups/<snip>/providers/Microsoft.KeyVault/vaults/<snip>'s true resource id.`

My VM's are in a dedicated Resource Group and the KeyVault is in it's own resource group.

I tried after the fact using @yugangw-msft suggestion of specifying the long form; however, it did not seem to make a difference.

That being said, we are going on 24+ hours of "EncryptionInProgress status from both the Azure CLI 1.0 and Azure CLI 2.0 tools. I'm going to check back on Monday and see if it's made any progress.

Should I see the VM host consuming CPU resources to reflect the encryption?

`dcesrvadmin@EUSDB01:~$ az vm encryption show --resource-group RG-East-VM-Data --name EUSDB01
{
  "dataDisk": "EncryptionInProgress",
  "osDisk": "EncryptionInProgress",
  "osDiskEncryptionSettings": {
    "diskEncryptionKey": {
      "secretUrl": "https://<snip>kv01.vault.azure.net/secrets/904c2ced-66fa-41e2-<snip>-<snip>/cb9e28567a594b669fb2<snip>",
      "sourceVault": {
        "id": "/subscriptions/47d96f0e-8472-40a5-<snip>-<snip>/resourceGroups/RG-East-VM-Data/providers/Microsoft.KeyVault/vaults/FLPPSEUSKV01"
      }
    },
    "enabled": true,
    "keyEncryptionKey": {
      "keyUrl": "https://flppseuskv01.vault.azure.net/keys/EUSDB01Key01/96caf1a7ac424ac08c36<snip>",
      "sourceVault": {
        "id": "/subscriptions/47d96f0e-8472-40a5-<snip>-<snip>/resourceGroups/RG-East-VM-Data/providers/Microsoft.KeyVault/vaults/<snip>KV01"
      }
    }
  },
  "osType": "Linux",
  "progressMessage": "https://<snip>kv01.vault.azure.net/secrets/904c2ced-66fa-41e2-<snip>-<snip>/cb9e28567a594b669fb2<snip>"
}`

**Comment by bgoykhman-nyt** [comment]
I believe this is still a bug.

I currently have the following setup:
1. A Keyvault in one Resource Group and VM in another. Keyvault is enabled for disk encryption.
2. A service principal is in the same group as the in the keyvault has 'wrapKey' permission and a set permission for secrets.
3. The message produce d

**Comment by drGarbinsky** [comment]
+1

**Comment by yugangw-msft** [comment]
@bgoykhman-nyt, @drGarbinsky, let me take a look at this again.

**Comment by yugangw-msft** [comment]
Tried out just now, still no repro. @bgoykhman-nyt, @drGarbinsky can one of you share the minimum repro? Please note, this error could also mean the vault has not been enabled for Volume Encryption, so please double check
@lhardison, i have to apologize for having been late on providing assistance, but please let me know if your issue still exists.
If needed, I can be reached at yugangw at microsoft dot com
For reference, the following are the whole flow I tried. I used `RedHat:RHEL:7.3:latest` for the mere reason that encryption takes the least time, based on suggestion from the team owning the disk encryption extension
```bash
az group create -n rg1 -l westus
az group create -n rg2 -l westus
az keyvault create -g rg1 -n rg1-kv --enabled-for-disk-encryption
az ad sp create-for-rbac -n my-enc-test -p verySecret --skip-assignment
az keyvault set-policy -n rg1-kv  --spn 91e08d37-a5a3-4932-80b4-e7547667XXXX --key-permissions backup create decrypt delete encrypt get import list purge recover restore sign unwrapKey update verify wrapKey  --secret-permissions backup delete get list purge recover restore set
az keyvault key create -n rg1-kv-key -p software --vault-name rg1-kv
az vm create -g rg2 -n rg2-vm2 --image rhel
az vm encryption enable -g rg2 -n rg2-vm2 --aad-client-id 91e08d37-a5a3-4932-80b4-e7547667XXX --aad-client-secret verySecret --disk-encryption-keyvault /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f0XXXX/resourceGroups/rg1/providers/Microsoft.KeyVault/vaults/rg1-kv --key-encryption-key rg1-kv-key --volume-type all
(The encryption request was accepted. Please use 'show' command to monitor the progress. If you see 'VMRestartPending', please restart the VM, and the encryption will finish shortly)
```

**Comment by lhardison** [comment]
I was able to get my VM’s encrypted; however, it was after a few hours of troubleshooting and eventually the tech assigned to my case had me scrap the entire VM. We then used some sort of portal template deployment to initiate the encryption process, which did have the VM in RG1 and Key in RG2.

I will try and find some time this week to try this out. Do I need to grab anything specific or will pulling down azure cli 2.0 to a fresh install cover the test case?

Thanks for your attention on this matter.

Regards,

Leif

Leif Hardison
IT Systems Architect & Security Manager
Finger Lakes Performing Provider System, Inc.(FLPPS)
2100 Brighton Henrietta Town Line Road, Suite 100
Rochester, NY 14623
O. 585.239.9348

Important Warning: This email (and any attachments) is only intended for use of the person or entity to which it is addressed, and may contain information that is privileged and confidential. You, the recipient, are obligated to maintain it in a safe, secure confidential manner. Unauthorized redisclosure or failure to maintain confidentiality may subject you to federal and state penalties. If you are not the recipient, please immediately notify us by return email, and delete this message from your computer.

**Comment by lhardison** [comment]
Hello,

I also asked the tech to report up a problem with the Azure Security Portal dashboard and how it report on a device being encrypted. My failed VM that never had either the OS or data disks encrypted and always reported “encryption in progress” type statuses showed as a green check in the dashboard for encrypted VM, which obviously it was not.

Regards,

Leif

Leif Hardison
IT Systems Architect & Security Manager
Finger Lakes Performing Provider System, Inc.(FLPPS)
2100 Brighton Henrietta Town Line Road, Suite 100
Rochester, NY 14623
O. 585.239.9348

Important Warning: This email (and any attachments) is only intended for use of the person or entity to which it is addressed, and may contain information that is privileged and confidential. You, the recipient, are obligated to maintain it in a safe, secure confidential manner. Unauthorized redisclosure or failure to maintain confidentiality may subject you to federal and state penalties. If you are not the recipient, please immediately notify us by return email, and delete this message from your computer.

**Comment by drGarbinsky** [comment]
@yugangw-msft I couldn't get this to repro. I'm guessing I had /overview on the end of the resource path as I copied that out of the URL in the portal. I have since been able to get this scenario to work.

**Comment by yugangw-msft** [comment]
Closing as there are no action we can take at CLI's side

**Comment by raghavanr** [comment]
I am having different issue, i have an encrypted VM (both Windows and Linux), now i want to add an data disk of 100 gb but i want my data disk to be encrypted as well. what is the easiest way to achieve it since the vm is already encrypted i just want my additional disk to be encrypted as well.
Hope you understand the issue.

**Comment by manjudemo** [comment]
Hi Team,
I am trying to enable using with new keyvault with new key after removing the encryption done by old keyvault. But I am getting below error.
Deployment failed. Correlation ID: xxxxxxxxxxxxxxxxxxxx. VM has reported a failure when processing extension 'AzureDiskEncryption'. Error message: "Failed to send DiskEncryptionData, Check KeyVault inputs, ResourceIds and retry encryption operation".

**Comment by david-stewart-cloudknowhow** [comment]
I don't see that a solution was provided here so I thought I'd post one:

In Azure CLI, when a Key Vault exists in a separate resource group, if you use the full Resource ID property of the Key Vault, instead of just the Key Vault name, it will work:

az vm encryption enable -g MyResourceGroupName --name MyVMName --disk-encryption-keyvault /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/MyResourceGroupName/providers/Microsoft.KeyVault/vaults/MyKeyVaultName
