### ISSUE TITLE
Azure China / The resource namespace 'Microsoft.DBforMySQL' is invalid.

### ISSUE THREAD

**Issue by narayaar** [Azure/azure-cli#4324]
### Description
**Cloud:**  AzureChinaCloud
**Locations:**  China North, China East
**Issue:**  When using the az cli to create the MySQL DAAS, the following error is seen;

_*# az mysql server list*
_The resource namespace 'Microsoft.DBforMySQL' is invalid.

*#  az provider list |grep -i DBforMySQL*
# <null>_

**Resolution**:  Please provide the api for Microsoft.DBforMySQL so that it can be imported/registered.

---
### Environment summary
**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:  

The az cli was installed using the method outlined in https://docs.microsoft.com/en-us/cli/azure/install-azure-cli

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

_*#  az --version*
azure-cli (2.0.14)

acr (2.0.10)
acs (2.0.13)
appservice (0.1.13)
batch (3.1.1)
billing (0.1.3)
cdn (0.0.6)
cloud (2.0.7)
cognitiveservices (0.1.6)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.10)
consumption (0.1.3)
container (0.1.8)
core (2.0.13)
cosmosdb (0.1.11)
dla (0.0.10)
dls (0.0.12)
eventgrid (0.1.2)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.7)
iot (0.1.10)
keyvault (2.0.8)
lab (0.0.9)
monitor (0.0.8)
network (2.0.12)
nspkg (3.0.1)
profile (2.0.10)
rdbms (0.0.5)
redis (0.2.7)
resource (2.0.12)
role (2.0.10)
sf (1.0.6)
sql (2.0.9)
storage (2.0.12)
vm (2.0.12)

Python (Linux) 2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

Python location '/usr/local/lib/azure-cli/bin/python'_

**OS Version:** What OS and version are you using?  
Answer here:

_*# lsb_release -a | grep -v Version*
Distributor ID: CentOS
Description:    CentOS Linux release 7.3.1611 (Core)
Release:        7.3.1611
Codename:       Core_

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

_*# echo $0*
-bash_
_*# bash --version | grep "GNU bash"*
GNU bash, version 4.2.46(1)-release (x86_64-redhat-linux-gnu)_

**Comment by SaloniSonpal** [comment]
The Azure Database for MySQL service is not available in the China cloud today, Hence the resource provider 'Microsoft.DBforMySQL' is invalid as expected. 

For latest updates and service announcements, follow us on Twitter @AzureDBPostgres or track the Azure blog at https://azure.microsoft.com/en-us/blog/topics/updates/.

**Comment by up9cloud** [comment]
@SaloniSonpal 

![screen shot 2017-11-10 at 10 49 37](https://user-images.githubusercontent.com/8325632/32640698-eb3ecd7c-c604-11e7-8e32-e0cdf6e1e486.png)

**Comment by ajlam** [comment]
The Azure Database for MySQL service is now available in Azure China. 

@tjprescott, @bsiegel - can you please help close?

**Comment by bsiegel** [comment]
Thanks Andrea, closing the issue!
