### ISSUE TITLE
[cloud shell][bug] az login returns `source code string cannot contain null bytes`

### ISSUE THREAD

**Issue by jluk** [Azure/azure-cli#4332]
### Description
**Outline the issue here:**
When attempting to use CLI in cloud shell, it prompts for an az login.

Upon invoking az login the error `source code string cannot contain null bytes` is returned.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: cloud shell

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.14

**OS Version:** What OS and version are you using?  
Answer here: Ubuntu 16.04 (cloud shell container)

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Bash

Verbose debug outputs below:

az account show --debug
`
justin@Azure:~$ az login
source code string cannot contain null bytes
justin@Azure:~$ az account show --debug
Command arguments ['account', 'show']
Loading all installed modules as module with name 'account' not found.
Installed command modules ['acr', 'acs', 'appservice', 'batch', 'billing', 'cdn', 'cloud', 'cognitiveservices', 'component', 'configure', 'consumption', 'container', 'cosmosdb', 'dla', 'dls', 'eventgrid', 'feedback', 'find', 'interactive', 'iot', 'keyvault', 'lab', 'monitor', 'network', 'profile', 'rdbms', 'redis', 'resource', 'role', 'sf', 'sql', 'storage', 'vm']
Current cloud config:
{'endpoints': {'active_directory': 'https://login.microsoftonline.com',
               'active_directory_data_lake_resource_id': 'https://datalake.azure.net/',
               'active_directory_graph_resource_id': 'https://graph.windows.net/',
               'active_directory_resource_id': 'https://management.core.windows.net/',
               'batch_resource_id': 'https://batch.core.windows.net/',
               'gallery': 'https://gallery.azure.com/',
               'management': 'https://management.core.windows.net/',
               'resource_manager': 'https://management.azure.com/',
               'sql_management': 'https://management.core.windows.net:8443/',
               'vm_image_alias_doc': 'https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json'},
'is_active': True,
'name': 'AzureCloud',
'profile': 'latest',
'suffixes': {'azure_datalake_analytics_catalog_and_job_endpoint': 'azuredatalakeanalytics.net',
              'azure_datalake_store_file_system_endpoint': 'azuredatalakestore.net',
              'keyvault_dns': '.vault.azure.net',
              'sql_server_hostname': '.database.windows.net',
              'storage_endpoint': 'core.windows.net'}}
Registered application event handler 'CommandTableParams.Loaded' at <function add_id_parameters at 0x7f3137112d08>
Registered application event handler 'CommandTable.Loaded' at <function add_id_parameters at 0x7f3137112d08>
Loaded module 'acr' in 0.017 seconds.
Loaded module 'acs' in 0.006 seconds.
Registered application event handler 'CommandParser.Parsing' at <function deprecate at 0x7f3137126950>
Loaded module 'appservice' in 0.004 seconds.
Did not load Batch Extensions module
No module named 'azure.cli.command_modules.batch_extensions'
Loaded module 'batch' in 0.022 seconds.
Loaded module 'billing' in 0.001 seconds.
Loaded module 'cdn' in 0.006 seconds.
Loaded module 'cloud' in 0.001 seconds.
Loaded module 'cognitiveservices' in 0.001 seconds.
Loaded module 'component' in 0.001 seconds.
Loaded module 'configure' in 0.001 seconds.
Loaded module 'consumption' in 0.001 seconds.
Loaded module 'container' in 0.001 seconds.
Registered application event handler 'CommandParser.Parsing' at <function deprecate at 0x7f313706e158>
Loaded module 'cosmosdb' in 0.003 seconds.
Loaded module 'dla' in 0.001 seconds.
Loaded module 'dls' in 0.001 seconds.
Loaded module 'eventgrid' in 0.005 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.001 seconds.
Loaded module 'interactive' in 0.003 seconds.
Loaded module 'iot' in 0.005 seconds.
Loaded module 'keyvault' in 0.002 seconds.
Loaded module 'lab' in 0.004 seconds.
Loaded module 'monitor' in 0.006 seconds.
Loaded module 'network' in 0.018 seconds.
Loaded module 'profile' in 0.001 seconds.
Loaded module 'rdbms' in 0.005 seconds.
Loaded module 'redis' in 0.001 seconds.
Loaded module 'resource' in 0.002 seconds.
Loaded module 'role' in 0.001 seconds.
Loaded module 'sf' in 0.408 seconds.
Loaded module 'sql' in 0.003 seconds.
Loaded module 'storage' in 0.023 seconds.
Loaded module 'vm' in 0.008 seconds.
Loaded all modules in 0.560 seconds. (note: there's always an overhead with the first module loaded)
Application event 'CommandTable.Loaded' with event data {'command_table': {'account show': <azure.cli.core.commands.CliCommand object at 0x7f3136ee0c50>}}
Application event 'CommandParser.Loaded' with event data {'parser': AzCliCommandParser(prog='az', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)}
Application event 'CommandTableParams.Loaded' with event data {'command_table': {'account show': <azure.cli.core.commands.CliCommand object at 0x7f3136ee0c50>}}
Application event 'CommandParser.Parsing' with event data {'argv': ['account', 'show']}
Application event 'CommandParser.Parsed' with event data {'command': 'account show', 'args': Namespace(_command_package='account', _jmespath_query=None, _log_verbosity_debug=False, _log_verbosity_verbose=False, _output_format='json', _parser=AzCliCommandParser(prog='az account show', usage=None, description='', formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True), _validators=[], command='account show', func=<azure.cli.core.commands.CliCommand object at 0x7f3136ee0c50>, show_auth_for_sdk=None, subcommand='sh [...]
Please run 'az login' to setup account.
`

az login --debug
`justin@Azure:~$ az login --debug
Command arguments ['login']
Loading all installed modules as module with name 'login' not found.
Installed command modules ['acr', 'acs', 'appservice', 'batch', 'billing', 'cdn', 'cloud', 'cognitiveservices', 'component', 'configure', 'consumption', 'container', 'cosmosdb', 'dla', 'dls', 'eventgrid', 'feedback', 'find', 'interactive', 'iot', 'keyvault', 'lab', 'monitor', 'network', 'profile', 'rdbms', 'redis', 'resource', 'role', 'sf', 'sql', 'storage', 'vm']
Current cloud config:
{'endpoints': {'active_directory': 'https://login.microsoftonline.com',
               'active_directory_data_lake_resource_id': 'https://datalake.azure.net/',
               'active_directory_graph_resource_id': 'https://graph.windows.net/',
               'active_directory_resource_id': 'https://management.core.windows.net/',
               'batch_resource_id': 'https://batch.core.windows.net/',
               'gallery': 'https://gallery.azure.com/',
               'management': 'https://management.core.windows.net/',
               'resource_manager': 'https://management.azure.com/',
               'sql_management': 'https://management.core.windows.net:8443/',
               'vm_image_alias_doc': 'https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json'},
'is_active': True,
'name': 'AzureCloud',
'profile': 'latest',
'suffixes': {'azure_datalake_analytics_catalog_and_job_endpoint': 'azuredatalakeanalytics.net',
              'azure_datalake_store_file_system_endpoint': 'azuredatalakestore.net',
              'keyvault_dns': '.vault.azure.net',
              'sql_server_hostname': '.database.windows.net',
              'storage_endpoint': 'core.windows.net'}}
Registered application event handler 'CommandTableParams.Loaded' at <function add_id_parameters at 0x7fd689b25d08>
Registered application event handler 'CommandTable.Loaded' at <function add_id_parameters at 0x7fd689b25d08>
Loaded module 'acr' in 0.013 seconds.
Loaded module 'acs' in 0.001 seconds.
Registered application event handler 'CommandParser.Parsing' at <function deprecate at 0x7fd689b39950>
Loaded module 'appservice' in 0.002 seconds.
Did not load Batch Extensions module
No module named 'azure.cli.command_modules.batch_extensions'
Loaded module 'batch' in 0.009 seconds.
Loaded module 'billing' in 0.001 seconds.
Loaded module 'cdn' in 0.002 seconds.
Loaded module 'cloud' in 0.001 seconds.
Loaded module 'cognitiveservices' in 0.001 seconds.
Loaded module 'component' in 0.001 seconds.
Loaded module 'configure' in 0.001 seconds.
Loaded module 'consumption' in 0.001 seconds.
Loaded module 'container' in 0.001 seconds.
Registered application event handler 'CommandParser.Parsing' at <function deprecate at 0x7fd689a81158>
Loaded module 'cosmosdb' in 0.003 seconds.
Loaded module 'dla' in 0.001 seconds.
Loaded module 'dls' in 0.001 seconds.
Loaded module 'eventgrid' in 0.001 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.001 seconds.
Loaded module 'interactive' in 0.001 seconds.
Loaded module 'iot' in 0.001 seconds.
Loaded module 'keyvault' in 0.002 seconds.
Loaded module 'lab' in 0.001 seconds.
Loaded module 'monitor' in 0.001 seconds.
Loaded module 'network' in 0.009 seconds.
Loaded module 'profile' in 0.001 seconds.
Loaded module 'rdbms' in 0.002 seconds.
Loaded module 'redis' in 0.001 seconds.
Loaded module 'resource' in 0.002 seconds.
Loaded module 'role' in 0.001 seconds.
Loaded module 'sf' in 0.178 seconds.
Loaded module 'sql' in 0.002 seconds.
Loaded module 'storage' in 0.010 seconds.
Loaded module 'vm' in 0.003 seconds.
Loaded all modules in 0.255 seconds. (note: there's always an overhead with the first module loaded)
Application event 'CommandTable.Loaded' with event data {'command_table': {'login': <azure.cli.core.commands.CliCommand object at 0x7fd6898f3908>}}
Application event 'CommandParser.Loaded' with event data {'parser': AzCliCommandParser(prog='az', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)}
Application event 'CommandTableParams.Loaded' with event data {'command_table': {'login': <azure.cli.core.commands.CliCommand object at 0x7fd6898f3908>}}
Application event 'CommandParser.Parsing' with event data {'argv': ['login']}
Application event 'CommandParser.Parsed' with event data {'args': Namespace(_command_package='login', _jmespath_query=None, _log_verbosity_debug=False, _log_verbosity_verbose=False, _output_format='json', _parser=AzCliCommandParser(prog='az login', usage=None, description='Log in to access Azure subscriptions', formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True), _validators=[], allow_no_subscriptions=False, command='login', func=<azure.cli.core.commands.CliCommand object at 0x7fd6898f3908>, password=None,  [...]
attempting to read file /home/justin/.azure/accessTokens.json as utf-8-sig
source code string cannot contain null bytes
`

**Comment by jluk** [comment]
Adding @yugangw-msft so he can see this when he gets back 😄

**Comment by yugangw-msft** [comment]
The `az login` should be blocked in the latest CLI.  But I will talk to you and Anders about how to diagnose such issues moving forward, as it is possible that Cloud-Shell has not invoked CLI to set up local accounts

**Comment by jluk** [comment]
Thanks @yugangw-msft I got around this by deleting the accessTokens file and restarting Cloud Shell to have it generate a new one. Any ideas on what the root cause was here to break az login on Cloud Shell start-up?

**Comment by yugangw-msft** [comment]
@jluk, like I communicated to you through a mail just now, any chance clould shell can record the traces for me to cross check? If you have a repro on a specific subscription, I can take a look too.
The bottom line is `az account show` should never ever return nothing.

**Comment by jluk** [comment]
Got it, unfortunately no repro available on specific sub right now. I'll follow up via your email about traces.

**Comment by yugangw-msft** [comment]
please reactivate when you have more recent data, particularly the hostname, so we can cross check the trace
