### ISSUE TITLE
New cloud shell had expired access token for CLI

### ISSUE THREAD

**Issue by gbowerman** [Azure/azure-cli#4333]
Launching a new cloud shell and running an az command resulted in:
"The access token expiry UTC time '8/28/2017 12:46:41 AM' is earlier than current UTC time '8/28/2017 11:14:23 PM'.
![cloud_shell](https://user-images.githubusercontent.com/4258913/29799873-9e91b52a-8c1b-11e7-91e8-ba065bdaaf0e.png)

**Comment by rswe** [comment]
![image](https://user-images.githubusercontent.com/31866877/30297625-443c81e2-9740-11e7-84ae-21718deafc53.png)

**Comment by yugangw-msft** [comment]
unfortunately, there is no way to diagnose the root cause till cloud shell picks up the newer CLI drop which prints out the host container name we can use to cross check the tracing to figure out the right party to investigate, say, either cloud shell has not passed on the up to date credentials to CLI or CLI just failed to refresh.

**Comment by alexbez** [comment]
Have the same issue today, after I left Azure portal open for the previous night. Now I get the same error message: 'The access token expiry UTC time '10/3/2017 2:50:31 PM' is earlier than current UTC time'. I restarted web CLI, logged off and back on Azure portal - but the problem persists.

I also tried to do 'azure login' in hope it will refresh the token. It asked me to enter a code on Azure login page. After I entered the code, verified that it comes from Azure CLI and hit 'Continue", the login page stays as it is and I have a rolling bar after '|info:    To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code XXXXXXX to authenticate.' message in CLI window. So the authentication process is stuck.

**Comment by Spreadcat** [comment]
I am experiencing the same here with the identical message and leaving the portal open as well. Re-opening didn't have any effect.  
[The Azure Status Page](https://azure.microsoft.com/en-us/status/) shows a warning for the cloud shell, but with a different error message.  I wonder if this might be related.

**Comment by yugangw-msft** [comment]
There is an infrastructure level defect being investigated in the cloud shell right now which very likely has caused CLI's credentials are not updated in time.  Will update the thread when it is addressed

**Comment by Spreadcat** [comment]
FYI: When the issue mentioned on the [status page](https://azure.microsoft.com/en-us/status/) was corrected, the CLI started working for meg again. I just tested it again (the morning after), and the scripts are still running fine.
For my part this issue is no longer present and has been resolved.

**Comment by yugangw-msft** [comment]
@Spreadcat, yep, the cloud shell team has mitigated the issue mentioned here last week.
For the original issue, anyone who still ran into it, please post newer error message here.
