### ISSUE TITLE
Unable to create storage account in certain regions

### ISSUE THREAD

**Issue by rauluka** [Azure/azure-cli#4335]
### Description
**Outline the issue here:**
I can't create storage account in some regions, e.g. westeurope.
Here is the command:
`az storage account create  --resource-group xxx --kind "Storage" --sku "Standard_GRS" --name xxx -l westeurope`
As a result I get:

> A feature was requested which is not yet available in this location.
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: apt-get

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.15)

acr (2.0.11)
acs (2.0.14)
appservice (0.1.14)
batch (3.1.2)
billing (0.1.4)
cdn (0.0.7)
cloud (2.0.7)
cognitiveservices (0.1.7)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.10)
consumption (0.1.4)
container (0.1.9)
core (2.0.14)
cosmosdb (0.1.12)
dla (0.0.11)
dls (0.0.13)
eventgrid (0.1.3)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.8)
iot (0.1.11)
keyvault (2.0.8)
lab (0.0.10)
monitor (0.0.9)
network (2.0.13)
nspkg (3.0.1)
profile (2.0.11)
rdbms (0.0.6)
redis (0.2.8)
resource (2.0.13)
role (2.0.11)
servicefabric (0.0.2)
sf (1.0.7)
sql (2.0.10)
storage (2.0.13)
vm (2.0.13)

Python (Linux) 3.6.1 (default, Aug 28 2017, 20:27:30) 
[GCC 4.8.4]

Python location '/opt/az/bin/python3'

Legal docs and information: aka.ms/AzureCliLegal

**OS Version:** What OS and version are you using?  
Answer here: Ubuntu 14.04

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by tjprescott** [comment]
Can you create the storage account in these regions using the portal?

**Comment by rauluka** [comment]
Yes, and I can create it also using cli version 2.0.14.Od: "Travis Prescott" &lt;notifications@github.com&gt;Do: "Azure/azure-cli" &lt;azure-cli@noreply.github.com&gt;; Wysłane: 16:52 Wtorek 2017-08-29Temat: Re: [Azure/azure-cli] [bug]Storage account creation fails (#4335)Can you create the storage account in these regions using the portal?

**Comment by tjprescott** [comment]
@troydai can you take a look?

**Comment by troydai** [comment]
@rauluka is this issue limited to westeurope region only?

**Comment by troydai** [comment]
I got this issue, too. However, I think this is a service limited. Can you accomplish this operation through the portal?

**Comment by tjprescott** [comment]
> Yes, and I can create it also using cli version 2.0.14.

**Comment by troydai** [comment]
Oh. I suspect it is MSI related.

**Comment by troydai** [comment]
In contact with storage service team.

**Comment by rauluka** [comment]
@troydai regarding other regions, I tried also northeurope (which fails with the same error), but e.g. westus works good. I agree with @tjprescott, it looks like regression. With earlier version of cli everything worked for mentioned regions.

**Comment by troydai** [comment]
@rauluka, thank you. I'm in contact with service team. The issue may cause by the upgrade of our SDK dependencies. I'm working with the service team to solve this issue.

**Comment by kydeeds** [comment]
@troydai I was also able to repro the issue when attempting to create storage accounts in US Gov Regions using version 2.0.15 . Not sure sovereign clouds need additonal work

**Comment by tjprescott** [comment]
This occurs because a feature included in the latest release was not deployed to all regions by the storage team. We will issue a fix in the upcoming release.
