### ISSUE TITLE
Improvements to --ids parameter

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#4340]
**1. Ingest Output Formats Easily**

Currently `--ids` requires a space-separate list of IDs.  To feed this to from another command, you could try:

```
az foo action --ids $(az foo list --query [].id --output tsv)
```
This doesn't actually work.  It would be much more convenient if --ids could sniff IDs from a variety of output formats, to enable the following:

```
az foo action --ids $(az foo list)
```

**2. Allow Looping on Name**

Currently you can supply a list of IDs... OR a single name. When I would like to delete multiple things in the same resource group, it would be convenient to allow the name component to accept a list of names.

```
az foo show -g {rg} -n name1 name2 name3
```
Should work just like:
```
az foo show --ids id1 id2 id3
```

**Comment by JasonRShaver** [comment]
closed pending future customer development on UX
