### ISSUE TITLE
ERROR: Deployment failed. VM has reported a failure when processing extension 'CustomScript'. Error message: "Enable failed: failed to execute command: command terminated with exit status=1".

### ISSUE THREAD

**Issue by agolomoodysaada** [Azure/azure-cli#4341]
### Description
Running the below commands on VMSS 
```sh
$ az vmss extension set --publisher Microsoft.Azure.Extensions \
  --version 2.0 \
  --name CustomScript \
  --resource-group <resource-group> \
  --vmss-name <vmss-name> \
  --settings @custom-script.json
```

```sh
$ az vmss update-instances --instance-ids '*' \
                         -n <vmss-name> \
                         -g <resource-group>
```
with a custom-script.json
```
{
  "fileUris": [
    <blob-to-script.sh>
  ],
  "commandToExecute": "sh script.sh"
}
```

both commands throw this error
```
ERROR: Deployment failed. VM has reported a failure when processing extension 'CustomScript'. Error message: "Enable failed: failed to execute command: command terminated with exit status=1".
```
If I delete the 1 VM in the VMSS and re-run commands against the VMSS they work fine for a few times and then start failing again. It's almost like the VM gets corrupted somehow?

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: I'm using the docker version as follows
```
docker run --rm -v ~/.azure:/root/.azure -v $(pwd):/tmp/mount -w /tmp/mount azuresdk/azure-cli-python az 
```

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
```
azure-cli (2.0.15+dev)

acr (2.0.11+dev)
acs (2.0.14+dev)
appservice (0.1.14+dev)
batch (3.1.2+dev)
billing (0.1.4+dev)
cdn (0.0.7+dev)
cloud (2.0.7+dev)
cognitiveservices (0.1.7+dev)
command-modules-nspkg (2.0.1+dev)
component (2.0.7+dev)
configure (2.0.10+dev)
consumption (0.1.4+dev)
container (0.1.9+dev)
core (2.0.14+dev)
cosmosdb (0.1.12+dev)
dla (0.0.11+dev)
dls (0.0.13+dev)
eventgrid (0.1.3+dev)
feedback (2.0.6+dev)
find (0.2.6+dev)
interactive (0.3.8+dev)
iot (0.1.11+dev)
keyvault (2.0.8+dev)
lab (0.0.10+dev)
monitor (0.0.9+dev)
network (2.0.13+dev)
nspkg (3.0.1+dev)
profile (2.0.11+dev)
rdbms (0.0.6+dev)
redis (0.2.8+dev)
resource (2.0.13+dev)
role (2.0.11+dev)
servicefabric (0.0.2+dev)
sf (1.0.7+dev)
sql (2.0.10+dev)
storage (2.0.13+dev)
taskhelp (0.1.6+dev)
vm (2.0.13+dev)

Python (Linux) 3.5.2 (default, Dec 27 2016, 21:33:11)
[GCC 5.3.0]

Python location '/usr/local/bin/python'

Legal docs and information: aka.ms/AzureCliLegal
```

**OS Version:** What OS and version are you using?  
Answer here: macOS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: zsh

**Comment by tjprescott** [comment]
This sounds like an issue with the extension rather than the CLI. If you try this with an ARM template or in Powershell do you observe the same behavior?

I'd recommend you post your issue here:
https://github.com/Azure/custom-script-extension-linux

They will have better insight into the extension's behavior and be better able to guide you.

**Comment by agolomoodysaada** [comment]
@tjprescott, thanks for your great suggestion. While attempting to create an issue in the other repository, their issue description mentioned

```
If you are encountering issues, please take a look at the following log files
on your virtual machine and provide their contents in the issue description:
  - /var/log/azure/custom-script/handler.log
  - /var/log/waagent.log
```
which effectively helped me debug my actual issue. I found a directory `/var/lib/waagent/custom-script/download/` that had all the downloaded files with `stdout` and `stderr` output that helped me figure out the problem with my script. I had to delete the old instances to re-attempt my cli command and bypass the above error.

While my issue is somewhat resolved... Wouldn't it be wonderful if stdout and stderr were sent back to the terminal cli? It would be even better if I didn't have to delete my instance to attempt uploading an updated script.

**Comment by yugangw-msft** [comment]
Let me contact CRP folks to see whether we can do something here. W/o stdout/stderr, diagnosis is getting rather inconvenient.
#2394 has the same ask. Note, `run-command` mentioned there will not work with scale-set.

**Comment by yugangw-msft** [comment]
Fix was committed for https://github.com/Azure/custom-script-extension-linux/issues/107

**Comment by huangpf** [comment]
mark

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
