### ISSUE TITLE
"az keyvault secret download" command threw an error.

### ISSUE THREAD

**Issue by fletchsod-developer** [Azure/azure-cli#4344]
### Description
**Outline the issue here:**

Command line as per documentation.

     az keyvault secret download --file secret.foo --name <<foo>> --vault-name <<foo>>

Error response

'NoneType' object has no attribute "get"
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/main.py", line 36, in main
cmd_result = APPLICATION.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/application.py", line 211, in execute
  result = expanded_arg.func(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 351, in __call__
  return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/keyvault/_command_type.py", line 69, in _execute_command
  result = op(client, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/keyvault/custom.py", line 534, in download_secret
  encoding = encoding or secret.tags.get('file-encoding', 'utf-8')
  AttributeError: 'NoneType' object has no attribute 'get'

`get` attribute is not supported in Azure-CLI for `az keyvault secret download` command.

This StackOverflow.com post https://serverfault.com/questions/848168/putting-rsa-keys-into-azure-key-vault showed `get` which seems to exists in the past.

So I typed this 

    az keyvault secret get

and got this output.

usage: az keyvault secret [-h]
                          {list,list-versions,list-deleted,set,set-attributes,show,show-deleted,delete,purge,recover,download,backup,resto...
    
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:  Microsoft Azure Online (MSI Installer)

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.14

**OS Version:** What OS and version are you using?  
Answer here: Windows 10, using Ubuntu & Bash

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Bash in Ubuntu

**Comment by tjprescott** [comment]
Hi @fletchsod-developer this is a bug that is occurring because the command is looking for a tag that specifies the encoding. If you have no tags, then this is the error you get.

We will issue a fix for the next release. In the meantime, if you specify the encoding parameter manually, it should download without issue.

**Comment by fletchsod-developer** [comment]
Thanks.
