### ISSUE TITLE
Too many management API calls

### ISSUE THREAD

**Issue by elibarzilay** [Azure/azure-cli#4347]
For a while now we've been having bad throttling issues, where things
kept crashing with errors.  After a long debugging session where I went
into the code to track where the bad calls are made, I saw that the
offending calls are ones that are made to the management API, eg:

    https://management.azure.com/subscriptions/[...]/providers/Microsoft.Storage/storageAccounts?api-version=2017-06-01

Later on, we found that it's no wonder that we've been throttled, since
apparently the limit for these calls is 100 per 5 minutes, which is easy
to reach when we have a bunch of blobs to delete, which we have to do
one by one (see Issue #3757).  To make things worse, it looks like this
limit is at the subscription level, and therefore it's even easier to
reach.

Digging more into the code, it looked like these calls are made to get
the storage access key, so we've tried providing that (via
`$AZURE_STORAGE_KEY`) and the throttling problems went away.  To
clarify, this became a bad blocking issue for us since we got to a point
where we couldn't create any new builds.

I also see that the help text claims that `--account-name` must be used
with `--account-key`, which we haven't followed.

So: I think that as a good short-term stopgap it would be best to clear
the help text and say that it will retrieve the key, but that makes for
another API call and therefore it slows things down and it might run
into the much-tighter throttling limits on the management service.

A better long-term solution would be to cache the access key itself,
possibly together with the cached login information.  For example, it
would retrieve and cache the key if it's not there, and if it uses a
cached key and that doesn't work, only then try to re-retrieve the key
in case it changed.  This would make it possible to lift the requirement
of using both the account name and the key, and still have a sane
interaction.

**Comment by tjprescott** [comment]
Yes, throttling issues are exactly why we don't recommend people rely on using --account-name to automatically retrieve the key.  Correct me if I'm wrong @troydai but we do reuse the key for batch upload operations.

The recommended way to work with storage is to retrieve the key and store it in the environment variable.

**Comment by tjprescott** [comment]
@troydai I recommend we add a warning to the logic that retrieves the key that points the user toward the recommended way of operating. It would also have saved @elibarzilay a lot of time spent troubleshooting because his screen would have been filled with warnings that retrieving the key for each call is inefficient and may cause throttling issues.

**Comment by elibarzilay** [comment]
@tjprescott, Yes -- I wasn't even aware of that text until I was deep
into debugging the problem, so an error, or at least a warning text
would have definitely helped.  I guess that this is basically saying
that "not recommended" is too weak: it could make me think that it's OK
to not add the key, and the errors that I got as a result of not doing
that are far enough that there's no way to guess why I got them.

But the caching thing seems to be getting the best of all: if the
subscription information is already cached, then there is no risk in
adding information that you can retrieve using it, so I don't see any
downside of caching the key once it's retrieved from the subscription
(and the name).

**Comment by troydai** [comment]
- [ ] Improve documentation and help to state that without specifying `--account-key` additional management call will be made to retrieve storage account key.
- [ ] Feature requested: cache the storage account key.

**Comment by elibarzilay** [comment]
@troydai: Yes, with a minor comment -- the documentation should refer to the page that lists these limits, since 100/5min is small enough to surprise people...

And yes, the second one is definitely a new feature request.

Thanks!

**Comment by troydai** [comment]
got it.

**Comment by troydai** [comment]
The key caching mechanism will be introduced together with the new OAuth based authentication scheme: https://github.com/Azure/azure-cli-extensions/commit/f5df07a01c97d853e28356a5a0082524555390c5

**Comment by elibarzilay** [comment]
@troydai That's great -- thanks!

**Comment by tjprescott** [comment]
The OAuth mechanism is available using the storage CLI extension. Please give it a try. cc/ @williexu

**Comment by elibarzilay** [comment]
@tjprescott Is there some page with a description of the new functionality?

**Comment by tjprescott** [comment]
This is the reference documentation for the preview extension:
https://docs.microsoft.com/en-us/cli/azure/ext/storage-preview/storage?view=azure-cli-latest

@williexu  is there a blog post that describes the newer auth behavior?

**Comment by williexu** [comment]
@elibarzilay no need to use the extension, the feature is already being shipped with our product.
Take a look at: https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-script#call-cli-commands-with-an-azure-ad-identity
