### ISSUE TITLE
az policy definition show does not work for built-in ploicies

### ISSUE THREAD

**Issue by andy26nash** [Azure/azure-cli#4374]
Saw this was previously an issue but closed.

Still don't seem to be able to 'show' a built-in policy
Was trying to assign one of the built-in polices “Allowed resource types” using the CLI in the Azure console.
I can list the available policies ‘az policy definition list’ which includes the policy I want to use.
When I try to show that specific policy I get nothing back, no error
az policy definition show --name a08ec900-254a-4555-9bf5-e42af04b5c5c (with or without single or double quotes)
or
az policy definition show --name "/providers/Microsoft.Authorization/policyDefinitions/a08ec900-254a-4555-9bf5-e42af04b5c5c" (again with or without all variant of quotes)
Same happens when I try to assign it: The policy definition 'a08ec900-254a-4555-9bf5-e42af04b5c5c' could not be found.

**Comment by tjprescott** [comment]
Which issue?

**Comment by tjprescott** [comment]
I found the issue. #692. I will close this and re-open that issue, as that is what the team requested. Thanks for bringing this to our attention!
