### ISSUE TITLE
VMSS create with existing network in another resource group

### ISSUE THREAD

**Issue by alexsab1** [Azure/azure-cli#4376]
### Description

I used "az vmss create --vnet-net <existing network> " where existing vnet exists in another resource group. My expectation was to reuse the existing network in another resource group.

Instead of using the existing vnet in another resource group, the command created new vnet in the same resource group.

Thank you

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.0.16

**OS Version:** What OS and version are you using?  
Answer here: Windows 10 Enterprise 

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

**Comment by tjprescott** [comment]
This is 100% by design. If you would like to use a VNET in another resource group, you must supply the fully-qualified resource ID to the VNet you want to use. This pattern is used throughout the CLI for cross-RG (and cross-subscription) resources.

**Comment by alexsab1** [comment]
Sorry and thank you for the explanation!

**Comment by tjprescott** [comment]
No problem. This question comes up every now and then :)

**Comment by alexsab1** [comment]
Where in documentation I can find the details about the pattern for full-qualified resource IDs?

**Comment by tjprescott** [comment]
@JasonRShaver do we have a blog post that addresses this?

**Comment by alexsab1** [comment]
From this issue I have found that I only need to specify fully-qualified ID for the subnet, without --vnet-name switch. That seems to work.

https://github.com/Azure/azure-cli/issues/2128

Thank you for your support.

**Comment by tjprescott** [comment]
If you do it incorrectly you should see something like:
`incorrect usage: --subnet ID | --subnet NAME --vnet-name NAME`
