### ISSUE TITLE
az storage blob upload-batch outputs misleading error if --account-key is not attached

### ISSUE THREAD

**Issue by roygara** [Azure/azure-cli#4382]
(I realize this may be obvious to most, especially as most other commands -h don't outline certain parameters as required even if they are but that doesn't make it a good practice and as a first time user of the CLI it can lead to some unnecessary trial and error, especially when the errors don't actually specify the correct error)

### Description
Basically, when running "az storage blob upload-batch -d https://[storageaccount].blob.core.windows.net/test-container -s C:\Users\<myuser>\storage-blob-integration-with-cdn-search-hdi\clinical-trials\clinical-
trials-small" 

it outputs "The specified resource does not exist."

This is misleading, as the resource does in-fact exist (I created it myself after-all) and it can see it and work with it. After some trial and error and reading through the -h I determined it's probably failing because the command is missing the account key, after adding --account-key and my information, the command is accepted and executes correctly, filling the container with the files. Which I've verified over in the UI just to be sure the command is actually executing.

So I'd suggest adding an additional error message which identifies that the --account-key parameter is missing in the event that it is.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: I downloaded and ran the windows MSI.

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
"azure-cli (2.0.15)

acr (2.0.11)
acs (2.0.14)
appservice (0.1.14)
batch (3.1.2)
billing (0.1.4)
cdn (0.0.7)
cloud (2.0.7)
cognitiveservices (0.1.7)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.10)
consumption (0.1.4)
container (0.1.9)
core (2.0.14)
cosmosdb (0.1.12)
dla (0.0.11)
dls (0.0.13)
eventgrid (0.1.3)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.8)
iot (0.1.11)
keyvault (2.0.8)
lab (0.0.10)
monitor (0.0.9)
network (2.0.13)
nspkg (3.0.1)
profile (2.0.11)
rdbms (0.0.6)
redis (0.2.8)
resource (2.0.13)
role (2.0.11)
servicefabric (0.0.2)
sf (1.0.7)
sql (2.0.10)
storage (2.0.13)
vm (2.0.13)

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'

Legal docs and information: aka.ms/AzureCliLegal"

**OS Version:** What OS and version are you using?  
Answer here: Windows 10 Enterprise

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: powershell

**Comment by troydai** [comment]
Supposedly the account key is not required if the full qualified share/container name is given. The command is supposed to fetch the account name from the URL and fetch the account key automatically if the CLI is logged in. (Is it logged in here?)

The error message indeed can be improved. Thanks for the advice.

**Comment by roygara** [comment]
For what it's worth I (thought?) I provided the URL (I omitted parts of it when I put it here, which is why it looks incomplete), I copied it from the primary service endpoint over in the portal. Is that the correct URL? (sorry, again, new user)
If so: it didn't seem like it was able to parse it correctly (and yes it was logged in, I wouldn't imagine the command would work if it wasn't but I haven't tried).

**Comment by troydai** [comment]
```
https://.blob.core.windows.net/test-container
```
This URL on paper doesn't look correct. The account name is missing here.

**Comment by roygara** [comment]
I'm aware, I omitted my account when I put it here, I wrote in tags but it looks like those were deleted when I posted somehow. On reflection there was no reason to omit it in the first place so I'll post it, I've since deleted that particular storage account but it was something like this:

https://examplestorageacct.blob.core.windows.net/

**Comment by troydai** [comment]
Thank you. The url looks correct. I will revisit this scenario in a bit. The bottom line is that we can improve the message, but I'm curious what stop the command from fetching the key.

**Comment by troydai** [comment]
Fixed in https://github.com/Azure/azure-cli/pull/4624.

The account key should be automatically fetched when it is missing in this situation.
