### ISSUE TITLE
[KeyVault] KeyVault permissions enums are case sensitive

### ISSUE THREAD

**Issue by tomasr** [Azure/azure-cli#4384]
### Description
I can't seem to get the right incantation to set the WrapKey or UnwrapKey permissions on keys in Azure Key Vault using the Azure CLI;

```
az keyvault set-policy --name $keyvault --object-id $id--key-permissions get list wrap_key unwrap_key
```

Fails with:

```
usage: az keyvault set-policy [-h] [--output {json,tsv,table,jsonc}]
                              [--verbose] [--debug] [--query JMESPATH]
                              [--resource-group RESOURCE_GROUP_NAME] --name
                              NAME [--object-id OBJECT_ID] [--spn SPN]
                              [--upn UPN]
                              [--key-permissions [PERM [PERM ...]]]
                              [--secret-permissions [PERM [PERM ...]]]
                              [--certificate-permissions [PERM [PERM ...]]]
az keyvault set-policy: error: unrecognized key permission 'wrap_key'
```

From reading the docs for the [management library](https://docs.microsoft.com/en-us/python/api/azure.mgmt.keyvault.models.keypermissions?view=azure-python), `wrap_key` and `unwrap_key` should be the right names, but no idea what is the right mechanism to do it.

Also, the error message here desperately needs to tell you what valid values for the enumeration are.
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: MSI

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.16

**OS Version:** What OS and version are you using?  
Answer here: Windows 10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

**Comment by tjprescott** [comment]
The values are shown in the help output (command -h).  They should be wrapKey and unwrapKey.

**Comment by tomasr** [comment]
Well.... I had no idea the output of -h and the generic syntax help that pops out on errors was different. Go figure.

Also, I *had* tried `wrapkey`, but no idea those things were case sensitive either (which seems kinda pointless, but oh well). Thanks for the help.

**Comment by tjprescott** [comment]
@tomasr indeed, the permissions should **not** be case sensitive but are, so I'll reopen this to track that fix.  For the value we use the rest API naming convention, which is `camelCased`.  If you look at the Python SDK documentation though, yes, everything will be `python_cased`. You should always be able to use -h to see the accepted values (which should be case insensitive).
