### ISSUE TITLE
az ad sp list Stalls

### ISSUE THREAD

**Issue by dazdaz** [Azure/azure-cli#4398]
### Description
After running "az login", the command "az ad sp list" stalls.  I assume that this is'nt expected behavior and would like to know what I can do, to debug this.

$ date ; az ad sp list ; date
Thu Sep  7 16:44:22 +08 2017
^CThu Sep  7 16:46:36 +08 2017

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Added repo, debian file update

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
2.0.13

**OS Version:** What OS and version are you using?  
Ubuntu 17.04

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
bash

**Comment by yugangw-msft** [comment]
Same with #559. #3481 will resolve it
