### ISSUE TITLE
Command acr login fails in docker container

### ISSUE THREAD

**Issue by tripdubroot** [Azure/azure-cli#4407]
### Description
While using the azure-cli-python container and working with ACR, running the az acr login requires docker which is not in the container.

```
bash-4.3# az acr login --name iptmpacr
Please verify whether docker is installed and running properly
```

---

### Environment summary
I'm running the docker container: 
`docker run -v ${HOME}:/user -it azuresdk/azure-cli-python:2.0.16`

**CLI Version:** 
azure-cli (2.0.16+dev)

**OS Version:** 
Fedora: 4.12.9-300.fc26.x86_64

Docker:
 Version:      17.09.0-ce-rc1
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   ae21824
 Built:        Wed Sep  6 22:33:07 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Shell Type:** 
GNU bash, version 4.3.42(1)-release (x86_64-alpine-linux-musl)

**Comment by derekbekoe** [comment]
Try running `docker run` with `-v /var/run/docker.sock:/var/run/docker.sock` to give access to Docker from the host.

Does that work?

**Comment by derekbekoe** [comment]
See https://github.com/Azure/azure-cli/pull/3747#discussion_r122508167

**Comment by djyou** [comment]
This is the expected behavior. Can you please follow the steps [here](https://github.com/Azure/acr/blob/master/docs/FAQ.md#how-to-log-into-my-registry-when-running-the-cli-in-a-container) and see if it works?

**Comment by derekbekoe** [comment]
Thanks for the comment @djyou.
Closing issue as that should resolve it.

**Comment by tripdubroot** [comment]
@djyou @derekbekoe thank you both. This does solve the issue.
