### ISSUE TITLE
Create documentation on the configuration options available

### ISSUE THREAD

**Issue by bjf** [Azure/azure-cli#4409]
Is there a way to show the default region and then set it to what I want. I am trying to create a vm with --size ExtraSmall. The error I get back says that that size is not available in the region. However, I specified a location of "West US" which I know has ExtraSmall instance types available.

**Comment by tjprescott** [comment]
You can show and set your default region with `az configure`.  In your case it would be `az configure -d location=westus`

However, `ExtraSmall` is *not* a valid VM size, so it will never succeed. You must specify a valid VM size string, such as `Standard_DS1_v2`.

**Comment by bjf** [comment]
On Mon, Sep 11, 2017 at 08:55:44AM -0700, Travis Prescott wrote:
> You can show and set your default region with `az configure`.  In your case it would be `az configure -d location=westus`

Thanks. Is there documentation on other configuration options
that can be set?

> 
> However, `ExtraSmall` is *not* a valid VM size, so it will never succeed. You must specify a valid VM size string, such as `Standard_DS1_v2`.

Yes, I'm aware of that now. I am moving from the previos CLI mode asm which "ExtraSmall" was
a valid size.

> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Azure/azure-cli/issues/4409#issuecomment-328574158

-- 
Brad Figg brad.figg@canonical.com http://www.canonical.com

**Comment by derekbekoe** [comment]
This now exists at https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest
