### ISSUE TITLE
turn off output in color

### ISSUE THREAD

**Issue by bjf** [Azure/azure-cli#4410]
How can I turn off the colored output of the commands. The colors are unreadable in my terminal window (using gnome-terminal on Ubuntu).

**Comment by tjprescott** [comment]
Use JSON format instead of JSONC format, but warnings, errors and debug will still be shown in color. Can you post a screenshot so we can see what you mean by the colors being unreadable?

**Comment by troydai** [comment]
I'm going to close this issue as @tjprescott gave a known solution. If it is still a problem please feel free to open this issue with a screenshot of what the terminal looks like for you.

**Comment by StingyJack** [comment]
This is still not readable in a powershell console either. #8483 logged.
