### ISSUE TITLE
get errors in non-json format

### ISSUE THREAD

**Issue by bjf** [Azure/azure-cli#4411]
I've just run a "az vm create" command which failed. The error message came back in json and in color. I can't read it because of the color and the formatting is not good because it is json. 
 
eg:

Deployment failed. {                                                                                                          │~                                                                                                                            
  "error": {                                                                                                                  │~                                                                                                                            
    "code": "InvalidParameter",                                                                                               │~                                                                                                                            
    "target": "vmSize",                                                                                                       │~                                                                                                                            
    "message": "The requested VM size ExtraSmall is not available in the current region. The sizes available in the current re│~                                                                                                                            
gion are: Standard_DS1_v2,Standard_DS2_v2,Standard_DS3_v2,Standard_DS4_v2,Standard_DS5_v2,Standard_DS11_v2,Standard_DS12_v2,St│~                                                                                                                            
andard_DS13-2_v2,Standard_DS13-4_v2,Standard_DS13_v2,Standard_DS14-4_v2,Standard_DS14-8_v2,Standard_DS14_v2,Standard_DS15_v2,S│~                                                                                                                            
tandard_DS2_v2_Promo,Standard_DS3_v2_Promo,Standard_DS4_v2_Promo,Standard_DS5_v2_Promo,Standard_DS11_v2_Promo,Standard_DS12_v2│~                                                                                                                            
_Promo,Standard_DS13_v2_Promo,Standard_DS14_v2_Promo,Standard_F1s,Standard_F2s,Standard_F4s,Standard_F8s,Standard_F16s,Standar│~                                                                                                                            
d_A0,Standard_A1,Standard_A2,Standard_A3,Standard_A5,Standard_A4,Standard_A6,Standard_A7,Basic_A0,Basic_A1,Basic_A2,Basic_A3,B│~                                                                                                                            
asic_A4,Standard_D1_v2,Standard_D2_v2,Standard_D3_v2,Standard_D4_v2,Standard_D5_v2,Standard_D11_v2,Standard_D12_v2,Standard_D1│~                                                                                                                            
3_v2,Standard_D14_v2,Standard_D15_v2,Standard_D2_v2_Promo,Standard_D3_v2_Promo,Standard_D4_v2_Promo,Standard_D5_v2_Promo,Stand│~                                                                                                                            
ard_D11_v2_Promo,Standard_D12_v2_Promo,Standard_D13_v2_Promo,Standard_D14_v2_Promo,Standard_F1,Standard_F2,Standard_F4,Standar│~                                                                                                                            
d_F8,Standard_F16,Standard_A1_v2,Standard_A2m_v2,Standard_A2_v2,Standard_A4m_v2,Standard_A4_v2,Standard_A8m_v2,Standard_A8_v2,│~                                                                                                                            
Standard_D1,Standard_D2,Standard_D3,Standard_D4,Standard_D11,Standard_D12,Standard_D13,Standard_D14,Standard_DS1,Standard_DS2,│~                                                                                                                            
Standard_DS3,Standard_DS4,Standard_DS11,Standard_DS12,Standard_DS13,Standard_DS14,Standard_G1,Standard_G2,Standard_G3,Standard│~                                                                                                                            
_G4,Standard_G5,Standard_GS1,Standard_GS2,Standard_GS3,Standard_GS4,Standard_GS4-4,Standard_GS4-8,Standard_GS5,Standard_GS5-8,│~                                                                                                                            
Standard_GS5-16,Standard_L4s,Standard_L8s,Standard_L16s,Standard_L32s,Standard_A8,Standard_A9,Standard_A10,Standard_A11,Standa│~                                                                                                                            
rd_H8,Standard_H16,Standard_H8m,Standard_H16m,Standard_H16r,Standard_H16mr. Find out more on the available VM sizes in each re│~                                                                                                                            
gion at https://aka.ms/azure-regions."                                                                                        │~                                                                                                                            
  }                                                                                                                           │~                                                                                                                            
}

**Comment by tjprescott** [comment]
It looks like you entered `--vm-size ExtraSmall` which isn't a valid size. The help shows a link to information on valid VM sizes, and the bulk of the error message is simply the list of size values permitted for your subscription and region.

All errors are displayed in red. You can opt for JSON output (which is black and white) or JSONC output (which is colorized) but errors are always displayed in color.

**Comment by bjf** [comment]
On Mon, Sep 11, 2017 at 03:51:03PM +0000, Travis Prescott wrote:
> It looks like you entered `--vm-size ExtraSmall` which isn't a valid size. The help shows a link to information on valid VM sizes, and the bulk of the error message is simply the list of size values permitted for your subscription and region.
> 
> All errors are displayed in red. You can opt for JSON output (which is black and white) or JSONC output (which is colorized) but errors are always displayed in color. 
> 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Azure/azure-cli/issues/4411#issuecomment-328572745

Yes, I could tell what the error was. As the subject states, for a cli
that humans type into a terminal, humans shouldn't be decoding json
output. There should be a way to get it as a well formatted text string.

Brad
-- 
Brad Figg brad.figg@canonical.com http://www.canonical.com

**Comment by tjprescott** [comment]
To get the valid values for size, use: `az vm list-sizes -l westus -otable`

**Comment by bjf** [comment]
On Mon, Sep 11, 2017 at 03:58:54PM +0000, Travis Prescott wrote:
> To get the valid values for size, use: `az vm list-sizes -l westus -otable`
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Azure/azure-cli/issues/4411#issuecomment-328575133

Thanks. I figured that out. That has nothing to do with this issue.

Brad
-- 
Brad Figg brad.figg@canonical.com http://www.canonical.com

**Comment by troydai** [comment]
@bjf thank you for reporting this. In this case, we're returning the error message that service serves us. Though the output does contain sufficient information for the users to correct the input, the form of the output is not ideal. However, as @tjprescott pointed out you can change the output format to make the error message more readable by setting the output format. I hope it works for you.

Moving forward, it worth to revisit how we output the returned value when the service indicates the operation is failed. However, this will be larger task impacts the entire output and formatting model. And we do need to consider this topic from many different perspectives besides error messages.

Thank you for the reporting. I will close this issue for now.
