### ISSUE TITLE
Bug: az cosmosdb list-connection-strings returns empty result

### ISSUE THREAD

**Issue by chrisdostert** [Azure/azure-cli#4419]
### Description
`az cosmosdb list-connection-strings` returns empty result: 
```
{
  "connectionStrings": null
}
```

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
docker

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.17

**OS Version:** What OS and version are you using?  
Answer here: linux

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: sh

**Comment by moderakh** [comment]
This is account management API not data plane api. Should be assigned to digvijay @dmakwana who owns account mgt API.

**Comment by syedhassaanahmed** [comment]
Still happening in Azure CLI 2.0.44

**Comment by pritam97** [comment]
still issue persists in Azure cli 2.0.45

**Comment by holzapfelnet** [comment]
I have the same issue using azure-cli 2.0.46 on mac os 10.14

**Comment by luisgmsft** [comment]
2.0.47 has this issue as well (running from cloud shell).

**Comment by Dave76** [comment]
This seems to still be an issue. Is there a work around other than retrieving the keys and then building the connection string?

```
# Cosmos connection string
cosmosKey=$(az cosmosdb list-keys --name $cosmos --resource-group $resourceGroup --query primaryMasterKey --output tsv)
connectionString="AccountEndpoint=https://$cosmos.documents.azure.com:443/;AccountKey=$cosmosKey;Database=$cosmosDatabase;DefaultCollection=$cosmosCollection"
echo "ConnectionString:DefaultConnection=$connectionString"
az webapp config connection-string set --resource-group $resourceGroup --name $appService --connection-string-type Custom --settings DefaultConnection="$connectionString"
```

**Comment by mindlessroman** [comment]
To add context from what I've seen - if you run `az cosmosdb list-connection-strings` for a MongoDB set-up, the connection string shows up no problem.   When the connection string is for a Document SQL set-up, the value is null.

**Comment by Dave76** [comment]
Why was this bug closed? Was it fixed?

**Comment by shurd** [comment]
The `az cosmosdb list-connection-strings` command now returns connection strings for all API types. It returns primary, primary read-only, secondary and secondary read-only

**Comment by tjprescott** [comment]
@shurd can this issue be closed then?

**Comment by shurd** [comment]
@tjprescott yes, this issue can be closed

**Comment by tjprescott** [comment]
Thanks @shurd!
