### ISSUE TITLE
[VMSS] Supplying existing AppGateway ID doesn't work

### ISSUE THREAD

**Issue by matiasma** [Azure/azure-cli#4422]
### Description

I cannot create a VM scale set with an existing Application Gateway using Azure CLI

I’m trying some commands, with no success… 

$ az vmss create --resource-group vvvms --name vmss01 --instance-count 1 --image Win2016Datacenter --vm-sku standard_f2s --upgrade-policy-mode manual --storage-sku premium_lrs --subnet /subscriptions/8e627baf-eb09-4677-ad46-c04e89ac9223/resourceGroups/vmss/providers/Microsoft.Network/virtualNetworks/vnet01/subnet/vmss --admin-username mamatias --app-gateway /subscriptions/8e627baf-eb09-4677-ad46-c04e89ac9223/resourceGroups/vmss/providers/Microsoft.Network/applicationGateways/appgw04 --backend-pool-name vmss01a
invalid usage for network balancer: application gateway
        missing: --app-gateway-subnet-address-prefix

I understand the AppGW Address Prefix is only needed to provision a new one. Even with the AppGW Addres Prefix:

$ az vmss create --resource-group vvvms --name vmss01 --instance-count 1 --image Win2016Datacenter --vm-sku standard_f2s --upgrade-policy-mode manual --storage-sku premium_lrs --subnet /subscriptions/8e627baf-eb09-4677-ad46-c04e89ac9223/resourceGroups/vmss/providers/Microsoft.Network/virtualNetworks/vnet01/subnet/vmss --admin-username mamatias --app-gateway /subscriptions/8e627baf-eb09-4677-ad46-c04e89ac9223/resourceGroups/vmss/providers/Microsoft.Network/applicationGateways/appgw04 --backend-pool-name vmss01a --app-gateway-subnet-address-prefix 10.0.1.0/26

Admin Password:
Confirm Admin Password:
Deployment failed. Tracking ID: 8e627baf-eb09-4677-ad46-c04e89ac9223. Deployment template validation failed: 'The template variable 'appGwID' is not valid: Unable to evaluate template language function 'resourceId': function requires exactly one multi-segmented argument which must be resource type including resource provider namespace. Current function arguments 'Microsoft.Network/applicationGateways,/subscriptions/8e627baf-eb09-4677-ad46-c04e89ac9223/resourceGroups/vmss/providers/Microsoft.Network/applicationGateways/appgw04'. Please see https://aka.ms/arm-template-expressions/#resourceid for usage details.. Please see https://aka.ms/arm-template-expressions for usage details.'.

Trying the Backend Pool ID instead AppGW ID:

$ az vmss create --resource-group vvvms --name vmss01 --instance-count 1 --image Win2016Datacenter --vm-sku standard_f2s --upgrade-policy-mode manual --storage-sku premium_lrs --subnet /subscriptions/8e627baf-eb09-4677-ad46-c04e89ac9223/resourceGroups/vmss/providers/Microsoft.Network/virtualNetworks/vnet01/subnet/vmss --admin-username mamatias --app-gateway /subscriptions/8e627baf-eb09-4677-ad46-c04e89ac9223/resourceGroups/vmss/providers/Microsoft.Network/applicationGateways/appgw04/backendAddressPools/appGatewayBackendPool1
invalid usage for network balancer: application gateway
        missing: --app-gateway-subnet-address-prefix

$ az vmss create --resource-group vvvms --name vmss01 --instance-count 1 --image Win2016Datacenter --vm-sku standard_f2s --upgrade-policy-mode manual --storage-sku premium_lrs --subnet /subscriptions/8e627baf-eb09-4677-ad46-c04e89ac9223/resourceGroups/vmss/providers/Microsoft.Network/virtualNetworks/vnet01/subnet/vmss --admin-username mamatias --app-gateway /subscriptions/8e627baf-eb09-4677-ad46-c04e89ac9223/resourceGroups/vmss/providers/Microsoft.Network/applicationGateways/appgw04/backendAddressPools/appGatewayBackendPool1 --app-gateway-subnet-address-prefix 10.0.1.0/26
Admin Password:
Confirm Admin Password:
Deployment failed. Tracking ID: 8e627baf-eb09-4677-ad46-c04e89ac9223. Deployment template validation failed: 'The template variable 'appGwID' is not valid: Unable to evaluate template language function 'resourceId': function requires exactly one multi-segmented argument which must be resource type including resource provider namespace. Current function arguments 'Microsoft.Network/applicationGateways,/subscriptions/8e627baf-eb09-4677-ad46-c04e89ac9223/resourceGroups/vmss/providers/Microsoft.Network/applicationGateways/appgw04/backendAddressPools/appGatewayBackendPool1'. Please see https://aka.ms/arm-template-expressions/#resourceid for usage details.. Please see https://aka.ms/arm-template-expressions for usage details.'.

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
apt-get

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
2.0.17

**OS Version:** What OS and version are you using?  
Ubuntu (Windows 10)

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Ubuntu (Windows 10)

**Comment by tjprescott** [comment]
There is a bug in how the command handles the AG ID.  If you use AG name (it works for existing AGs) then you won't get the error about the address prefix. This may unblock you,

**Comment by matiasma** [comment]
Hi Travis, but in my case the AppGW exists in another resource group. I believe I would have a new one (in the same resource group of the VMSS) if I specify only the name.

**Comment by matiasma** [comment]
Now I understand the error message... There are some function like [resourceId('Microsoft.Network/virtualNetworks',parameters('app-gateway'))] only supporting AppGW Name, even with the documentation describing the AppGW ID support:

"Name to use when creating a new application gateway (default) or referencing an existing one. Can also reference an existing application gateway by ID or specify "" for none."

**Comment by tjprescott** [comment]
Hi @matiasma:

> Hi Travis, but in my case the AppGW exists in another resource group. I believe I would have a new one (in the same resource group of the VMSS) if I specify only the name.

You are right that if your AG is in a different resource group, you need to specify ID. Unfortunately due to the bug it won't work today but I'll release a fix for the upcoming release. If you specify name, then the assumption is that the gateway exists in the same resource group as your VMSS (but it will still use existing if it does in fact exist there).

Some other tricky bits about creating a VMSS with an existing app gateway (so you can try with an AG in the same RG or after this bug is fixed):

Your app gateway has a subnet that its frontend IP config is associated with. You will need to create a second subnet in that same VNet.  This will be the VNet and subnet that you supply when you run your `vmss create` command. So your flow would look something like:

```
az network application-gateway create ...
az network vnet subnet create --vnet-name {ag vnet name} -n VMSSsubnet --address-prefix {subnet within ag vnet}
az vmss create --app-gateway {ag} --vnet-name {ag vnet name} --subnet VMSSsubnet

```

**Comment by matiasma** [comment]
I'm ok to work with either ARM Template or resources.azure.com until the AZ CLI fix. Thanks for help!
