### ISSUE TITLE
Error when trying to select Azure Subscription from Azure CloudShell

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/azure-cli#4426]
### Description
**Outline the issue here:**
Error when trying to select Azure Subscription from Azure CloudShell, as shown in the image:
![image](https://user-images.githubusercontent.com/1712635/30349094-82b0ded8-97c6-11e7-8361-b88ecb7c1b36.png)

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: Just running it from the browser once authenticated in Azure portal.

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Bash from Azure CloudShell

**Comment by derekbekoe** [comment]
It seems to work.
@CESARDELATORRE was this copy/pasted from somewhere?
I suspect if you type the characters out, it'll work.

**Comment by CESARDELATORRE** [comment]
I was pasting the guid from a notepad file (Windows client)...
If I type the whole command, it works. You are right on that.
I guess that there should be some kind of "character filter" so no matter if you are copying the characters from a Windows app, it will work.
This can be a ver common issue, I guess.. :)

**Comment by derekbekoe** [comment]
This is really outside the scope of the CLI.
You'd see something similar with other tools.
