### ISSUE TITLE
[ACS] enable service principal secret in Keyvault

### ISSUE THREAD

**Issue by weinong** [Azure/azure-cli#4429]
### Description
**Outline the issue here:**
---
The ACS RPv2 has new feature to support using service principal secret in the keyvault. Please add it to cli
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

**OS Version:** What OS and version are you using?  
Answer here:

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

**Comment by weinong** [comment]
@rjtsdl FYI

**Comment by yugangw-msft** [comment]
closing as `az acs` is deprecating
