### ISSUE TITLE
Can we send iot data for a device in iothub through azure-cli or terminal?

### ISSUE THREAD

**Issue by AzureUser123** [Azure/azure-cli#4430]
### Description
**Outline the issue here:**

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

**OS Version:** What OS and version are you using?  
Answer here:

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

**Comment by derekbekoe** [comment]
I believe you can now with the IoT extension https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/iot/device?view=azure-cli-latest

https://github.com/Azure/azure-iot-cli-extension
