### ISSUE TITLE
`az group deployment create` Table output is not helpful

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#4432]
In response to customer feedback, our current deploy output is too anemic and does not include important information

CLI 2.0 Output
```
Name ResourceGroup
------------ ---------------
mainTemplate ben2
```

Our output should be updated to support the follow requirements:

- P1: Show important fields, such as name, result, template link
- P1: Show deployment output values
- P3: Show input template params

For example, should we include the Output values:

But we may also want to look at outputting some primary fields as well (Template link, deployment name) if we have a method to support multiple output tables.

**Comment by yugangw-msft** [comment]
Agreed what we have now (2 fields) are too little. I will fix this by adding a few which CLI 1.0 outputs as well. I would not include template information which has lots of varieties, perfect for users to pick up --json
