### ISSUE TITLE
"vpn-connection create" failure error is non informative

### ISSUE THREAD

**Issue by brusMX** [Azure/azure-cli#4436]
### Description
**Outline the issue here:**

Deploying a connection between two gateways in two different RG in different regions fails when `--vnet-gateway2` is not provided as full resource ID and the message error is non informative

Command:
```bash
az network vpn-connection create -g PREMISE-RG -n PremiseToCloudConnection --vnet-gateway1 PREMISE-GATEWAY  --vnet-gateway2 CLOUD-GATEWAY --shared-key superk3y
```

Error:
```json
Deployment failed. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "InternalServerError",
        "message": "An error occurred.",
        "details": []
      }
    ]
  }
}
```

But if I provide full Resource ID to `vnet-gateway2`, it actually works:
```bash
 az network vpn-connection create -g PREMISE-RG -n PremiseToCloudConnection --vnet-gateway1 PREMISE-GATEWAY  --vnet-gateway2 /subscriptions/xxxxx-xxx-xxx/resourceGroups/CLOUD-RG/providers/Microsoft.Network/virtualNetworkGateways/CLOUD-GATEWAY --shared-key superk3y
```

Success:
```json
{
  "connectionStatus": "Unknown",
  "connectionType": "Vnet2Vnet",
  "egressBytesTransferred": 0,
  "enableBgp": false,
  "ingressBytesTransferred": 0,
  "provisioningState": "Succeeded",
  "resourceGuid": "xxx-xxx-xxx",
  "routingWeight": 10,
  "sharedKey": "superk3y",
  "virtualNetworkGateway1": {
    "id": "/subscriptions/xxx-xxx-xx/resourceGroups/PREMISE-RG/providers/Microsoft.Network/virtualNetworkGateways/PREMISE-GATEWAY",
    "resourceGroup": "PREMISE-RG"
  },
  "virtualNetworkGateway2": {
    "id": "/subscriptions/xxxx-xxx-xxx/resourceGroups/CLOUDRG-RG/providers/Microsoft.Network/virtualNetworkGateways/CLOUD-GATEWAY",
    "resourceGroup": "CLOUDRG-RG"
  }
}
```

We could return in the error that the the vnet-gateway2 needs a full resource ID, and we could also put in the documentation that if the RG is in a different region (or whatever the reason is), then you should provide a full id.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 
azure-cli (2.0.16)

acr (2.0.11)
acs (2.0.14)
appservice (0.1.15)
batch (3.1.2)
billing (0.1.4)
cdn (0.0.7)
cloud (2.0.7)
cognitiveservices (0.1.7)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.10)
consumption (0.1.4)
container (0.1.9)
core (2.0.15)
cosmosdb (0.1.12)
dla (0.0.11)
dls (0.0.13)
eventgrid (0.1.3)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.9)
iot (0.1.11)
keyvault (2.0.9)
lab (0.0.10)
monitor (0.0.9)
network (2.0.13)
nspkg (3.0.1)
profile (2.0.11)
rdbms (0.0.6)
redis (0.2.8)
resource (2.0.13)
role (2.0.11)
servicefabric (0.0.3)
sf (1.0.8)
sql (2.0.10)
storage (2.0.14)
vm (2.0.13)

Python (Darwin) 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]

Python location '/Users/brus/lib/azure-cli/bin/python'

**OS Version:** What OS and version are you using?  
Answer here:
Mac OS X Sierra 10.12.6

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
zsh

**Comment by tjprescott** [comment]
cc/ @aanandr

**Comment by MyronFanQiu** [comment]
@Nilambari Any Update about this issue?
