### ISSUE TITLE
Azure CLI 2 Sync Command Does Not Wait for Syncing to Finish. 

### ISSUE THREAD

**Issue by Catpants** [Azure/azure-cli#4439]
### Description
**Outline the issue here:**
The azure cli 2.0 command 'az webapp deployment source sync' does not wait for the syncing to finish. Is there a way to make it wait as I am wanting to use it in and automated fashion. I want to execute a command directly after the syncing is finished. If I execute the command while it is syncing the sync fails.
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: Docker

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.17

**OS Version:** What OS and version are you using?  
Answer here: 

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

**Comment by williexu** [comment]
@Catpants there is currently no support from the service to wait for the sync operation to complete. Your best bet is to poll the deployment using `curl` and check to see if it has been updated.

**Comment by ahmedelnably** [comment]
closing this as there is no support from the backend to wait for the sync operation to complete
