### ISSUE TITLE
traffic-manager with TCP endpoint monitoring doesn't show up in az

### ISSUE THREAD

**Issue by ecgg** [Azure/azure-cli#4440]
### Description
When switching a traffic manager profile over to TCP endpoint monitoring, it does not show up any more under az network traffic-manager profile list

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 

```
azure-cli (2.0.16)

acr (2.0.11)
acs (2.0.14)
appservice (0.1.15)
batch (3.1.2)
billing (0.1.4)
cdn (0.0.7)
cloud (2.0.7)
cognitiveservices (0.1.7)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.10)
consumption (0.1.4)
container (0.1.9)
core (2.0.15)
cosmosdb (0.1.12)
dla (0.0.11)
dls (0.0.13)
eventgrid (0.1.3)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.9)
iot (0.1.11)
keyvault (2.0.9)
lab (0.0.10)
monitor (0.0.9)
network (2.0.13)
nspkg (3.0.1)
profile (2.0.11)
rdbms (0.0.6)
redis (0.2.8)
resource (2.0.13)
role (2.0.11)
servicefabric (0.0.3)
sf (1.0.8)
sql (2.0.10)
storage (2.0.14)
vm (2.0.13)

Python (Linux) 3.6.2 (default, Aug 11 2017, 11:59:59) 
[GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
```

**OS Version:** What OS and version are you using?  
Answer here:

Fedora release 26 (Twenty Six)

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

bash

**Comment by tjprescott** [comment]
Hi @ecgg would you share the sequence of commands you are using to reproduce this issue?

**Comment by ecgg** [comment]
- Create a traffic-manager profile via Portal
- Change the Endpoint monitor settings from HTTP to TCP
- Check if it shows up in az network traffic-manager profile list 

Attached a screenshot:
    upper left terminal shows just after creation
    portal shows the change made from HTTP to TCP endpoint monitoring
    bottom left terminal shows no more traffic-manager profile after change
![screenshot_2017-09-15_09-50-31](https://user-images.githubusercontent.com/27764963/30472201-cd469a5a-99fb-11e7-9098-926941e8c110.png)

**Comment by tjprescott** [comment]
I have reproduced this and it seems to be an issue with the service itself.

**Comment by tjprescott** [comment]
Actually, the reason this doesn't show is because this feature is in a newer API version of traffic manager and the CLI only supports 2017-03-01.
