### ISSUE TITLE
`--ids` parameter only supports 3 levels

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#4443]
Azure Backup has IDs that look like this:

`/Subscriptions/00000/resourceGroups/RG/providers/Microsoft.RecoveryServices/vaults/{vault_name}/backupFabrics/{fabric_name}/protectionContainers/{container_name}/protectedItems/{item_name}/recoveryPoint/{recovery_point_guid}`

Thus they have a 5 level child resource hierarchy.  Our current `--ids` infrastructure only supports "resource", "child" and "grandchild" levels.

We should revise this feature to support an arbitrary number of things. For example, instead of:

```
        - child_namespace       Namespace for the child resoure (optional)
        - child_type            Type of the child resource
        - child_name            Name of the child resource
        - grandchild_namespace  Namespace for the grandchild resource (optional)
        - grandchild_type       Type of the grandchild resource
        - grandchild_name       Name of the grandchild resource
```

We should allow:
```
        - child1_namespace
        - child1_type            
        - child1_name          
        - child2_namespace 
        - child2_type       
        - child2_name       
```
And so forth.  This would impact the way you would need to annotate "id_part" as well as changing the structure of the dictionary "parse_resource_id" returns. 

cc/ @dragonfly91

**Comment by tjprescott** [comment]
@mayurid I placed this in Sprint 24 so that we can get it implemented and allow Azure Backup to finish ID support for the subgroups that currently can't use it (due to the limitation described). This might be a good one for @williexu.

**Comment by williexu** [comment]
I can do this for the next sprint :)

**Comment by williexu** [comment]
Will be released with https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure. I'll continue work then.
