### ISSUE TITLE
Checksum Does not match

### ISSUE THREAD

**Issue by one000mph** [Azure/azure-cli#4445]
### Description
**Outline the issue here:**

I am trying to install the CLI based on provided documentation. The download seems to complete properly, but the checksum fails each time. Output below

```bash
curl -L https://aka.ms/InstallAzureCli | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   167  100   167    0     0    576      0 --:--:-- --:--:-- --:--:--   577
100  1367  100  1367    0     0   2383      0 --:--:-- --:--:-- --:--:--  2383
Downloading Azure CLI install script from https://azurecliprod.blob.core.windows.net/install.py to /var/folders/h4/9lbb3tv951n01trft3dkw12r0000gn/T/azure_cli_install_tmp_XXXX.xCdr4I7c.
######################################################################## 100.0%
/var/folders/h4/9lbb3tv951n01trft3dkw12r0000gn/T/azure_cli_install_tmp_XXXX.xCdr4I7c: FAILED
shasum: WARNING: 1 computed checksum did NOT match

```
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

`curl -L https://aka.ms/InstallAzureCli | bash`

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

N/A

**OS Version:** What OS and version are you using?  
Answer here:
Mac OS 10.12.6 (Sierra)

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

`bash`

**Comment by derekbekoe** [comment]
The checksum of https://azurecliprod.blob.core.windows.net/install.py should be `7419f49b066015d863f398198c4ac5ad026f5aa3705e898b552e4e03fc352552`.
I've verified this is still correct.

Potentially a network issue?
What does the temp file `/var/folders/h4/9lbb3tv951n01trft3dkw12r0000gn/T/azure_cli_install_tmp_XXXX.xCdr4I7c` look like?

**Comment by one000mph** [comment]
The SHA256 checksum for the path `/install` is different from the `/install.py` path.

```bash
11 [11:42:58][T]$curl https://azurecliprod.blob.core.windows.net/install -o ~/Desktop/azurecli-install.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1367  100  1367    0     0   5368      0 --:--:-- --:--:-- --:--:--  5381

12 [11:43:40][T]$openssl dgst -sha256 ~/Desktop/azurecli-install.sh
SHA256(/Users/heather/Desktop/azurecli-windows.sh)= 1d1f7ed01c15e69521663c23e2f3ec370c65dbbf7fd80538bd6855878f5ee838
13 [11:43:46][T]$curl https://azurecliprod.blob.core.windows.net/install.py -o ~/Desktop/azurecli-py.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16656  100 16656    0     0  51826      0 --:--:-- --:--:-- --:--:-- 51726

14 [11:44:12][T]$openssl dgst -sha256 ~/Desktop/azurecli-py.sh
SHA256(/Users/heather/Desktop/azurecli-py.sh)= 7419f49b066015d863f398198c4ac5ad026f5aa3705e898b552e4e03fc352552
```

The `.py` path is correct and I was able to install the CLI via that link. I believe the documentation is misleading as the recommended command `curl -L https://aka.ms/InstallAzureCli | bash` results in an incorrect checksum. The alternative recommended [here in troubleshooting documentation](https://github.com/Azure/azure-cli/blob/master/doc/install_troubleshooting.md#errors-with-curl-redirection) `curl https://azurecliprod.blob.core.windows.net/install | bash` hits the same source. 

My first attempt downloaded the temp file which seems to be the correct file contents (same as the python script except for a trailing newline), however it yields an incorrect checksum.

```bash
$openssl dgst -sha256 /var/folders/h4/9lbb3tv951n01trft3dkw12r0000gn/T/azure_cli_install_tmp_XXXX.xCdr4I7c
SHA256(/var/folders/h4/9lbb3tv951n01trft3dkw12r0000gn/T/azure_cli_install_tmp_XXXX.xCdr4I7c)= db216100724bc8e635b5c3c803bb29f7519a247a6d2f9465a9dbcecae3af623a
```

Anyways, I seem to be good now and have the cli installed, however the documentation would benefit from some updates and clarification. Thank you.

**Comment by derekbekoe** [comment]
The two files `/install` and `/install.py` are indeed different - https://github.com/Azure/azure-cli/tree/master/scripts/curl_install_pypi.
Good to hear it's working.
