### ISSUE TITLE
CI Logs filled overly verbose

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#4452]
@troydai 

With recent changes to the CI build, the log is filling up with useless entries.  About 6000 lines of things like:
`copying azure/cli/core/parser.py -> build/lib/azure/cli/core`

This actively prevents finding out what failed the build because TravisCI truncates the log at 10,000 lines and gives the following:

`This log is too long to be displayed. Please reduce the verbosity of your build or download the raw log. `

So... as the CI requests... please reduce the verbosity of the log 😆

**Comment by troydai** [comment]
Fixed in https://github.com/Azure/azure-cli/issues/4452.
