### ISSUE TITLE
az webapp config should support arraffinity property

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-cli#4470]
### Description
Currently the web app config only shows/ updates the siteconfig properties but not the site properties 
i.e /subscriptions/<sub>/resourceGroups/<RG>/providers/Microsoft.Web/sites/<site>/config?api-version=2016-08-01

& not /subscriptions/3<sub>/resourceGroups/<RG>/providers/Microsoft.Web/sites?api-version=2016-08-01
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Cloud shell

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
N/A

**OS Version:** What OS and version are you using?  
CloudShell

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Cloud SHell

**Comment by yugangw-msft** [comment]
we have exposed it through `az webapp update`
