### ISSUE TITLE
Web docs don't display placeholders in angle brackets

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#4473]
In examples, we sometimes have placeholders like \<this\>.  However, web markup swallows this entire thing, and the resulting web documentation appears like a blank.  Instead, we should use {this}, which appears just fine.

**Comment by derekbekoe** [comment]
This looks addressed.
e.g. https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-install-connector
