### ISSUE TITLE
Incorrect API version mapping for MGMT_STORAGE for the 2017-03-09-profile

### ISSUE THREAD

**Issue by shriramnat** [Azure/azure-cli#4487]
### Description
API version mapping for MGMT_STORAGE for the 2017-03-09-profile  is incorrect.
it needs to be changed to 2016-01-01
page https://github.com/Azure/azure-cli/blob/master/src/azure-cli-core/azure/cli/core/profiles/_shared.py#L77

**Comment by bganapa** [comment]
CC: @viananth
