### ISSUE TITLE
Generic update: repeated --add calls result in duplicate values

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#4492]
If you run:

`az network route-filter rule update -g {rg} --filter-name {name} -n {ruleName} --add communities 12076:50101`

multiple times, the rule's communities list will actually have duplicate entries, which doesn't make sense form the service standpoint.

This issue is to investigate:

1. How other RPs handle repeated additions (do they scrub duplicates, issue an error, or add the dupe?)
2. Can we change the --add behavior from list behavior to set behavior?  (if any RP needs list behavior, the answer would be **no**)

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: dev_setup.py

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.17+dev)

acr (2.0.11+dev)
acs (2.0.15+dev)
appservice (0.1.16+dev)
backup (1.0.0+dev)
batch (3.1.3+dev)
billing (0.1.4+dev)
cdn (0.0.8+dev)
cloud (2.0.7+dev)
cognitiveservices (0.1.7+dev)
component (2.0.7+dev)
configure (2.0.10+dev)
consumption (0.1.4+dev)
container (0.1.10+dev)
core (2.0.16+dev)
cosmosdb (0.1.12+dev)
dev-tools (0.1.1)
dla (0.0.11+dev)
dls (0.0.13+dev)
eventgrid (0.1.3+dev)
extension (0.0.2+dev)
feedback (2.0.6+dev)
find (0.2.6+dev)
interactive (0.3.9+dev)
iot (0.1.11+dev)
keyvault (2.0.10+dev)
lab (0.0.10+dev)
monitor (0.0.9+dev)
network (2.0.14+dev)
nspkg (3.0.1+dev)
profile (2.0.12+dev)
rdbms (0.0.6+dev)
redis (0.2.8+dev)
resource (2.0.14+dev)
role (2.0.11+dev)
servicefabric (0.0.3+dev)
sql (2.0.11+dev)
storage (2.0.15+dev)
taskhelp (0.1.6+dev)
testsdk (0.1.0+dev)
vm (2.0.14+dev)

**OS Version:** What OS and version are you using?  
Answer here: Win10 CU

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: CMD

**Comment by yonzhan** [comment]
@jiasli  add to S162.

**Comment by jiasli** [comment]
Generic update is not the recommended way to operate on resources, and we didn't receive any customer complaints. Closing.
