### ISSUE TITLE
Improve utility of Help parsing errors

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#4495]
I spent over an hour trying to diagnose failing tests due to a help file entry labeled "group" instead of "command". Trying to add a simple example via the help file also caused hours of debugging and delay for what ended up being indentation issues. 

Given that we expect non-programmers to contribute to the _help.py file via the doc edit link, we really need to improve the parsing process to give clear, actionable errors.

**Comment by JasonRShaver** [comment]
@tjprescott  and @williexu  should be addressing this in their help changes
