### ISSUE TITLE
Can not use "space" or "=" in the "environment-variables" when creating container

### ISSUE THREAD

**Issue by ruzickap** [Azure/azure-cli#4496]
### Description
I'm trying to deploy container in ACI, where I would like to use " " or "=" in environment variable.

When I'm using Docker locally this works fine:
```
docker run -it --rm -p 2222:22 -e SSH_PUBLIC_KEYS="ssh-rsa AAA...iM=" peru/ubuntu_sshd

$ docker inspect 2b3528737878
...
            "Env": [
                "SSH_PUBLIC_KEYS=ssh-rsa AAA...iM=",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
....
```

The command above is working fine. When I use the same using the "az container create" it can not handle the "space" nad "=" in the variable properly:

```
az container create --name mycontainer --image peru/ubuntu_sshd --environment-variables SSH_PUBLIC_KEYS="ssh-rsa AAA...iM=" --resource-group H...S --port 2222

or 

az container create --name mycontainer --image peru/ubuntu_sshd --environment-variables "SSH_PUBLIC_KEYS=ssh-rsa AAA...iM=" --resource-group H...S --port 2222
```
As you can see here the environment variable ```SSH_PUBLIC_KEYS``` is not properly parsed/handled, because it takes " " or "=" as separator:

```
az container show -n mycontainer
{
  "containers": [
    {
      "command": null,
      "environmentVariables": [
        {
          "name": "SSH_PUBLIC_KEYS",
          "value": "ssh-rsa"
        },
        {
          "name": "AAA...iM",
          "value": ""
        }
      ],
...
```

---

### Environment summary

I installed ```aws-cli``` using ```pip``` into virtual env.

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
```
$ az --version
azure-cli (2.0.17)
```

**OS Version:** What OS and version are you using?  
Fedora 25

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Bash

**Comment by derekbekoe** [comment]
Should have been addressed in https://github.com/Azure/azure-cli/issues/4084.
cc: @yolo3301
