### ISSUE TITLE
az group deployment create "deployment failed"

### ISSUE THREAD

**Issue by jldeen** [Azure/azure-cli#4499]
### Description
When running:

```
az group deployment create --name name-here --resource-group group-here --template_file file-here --parameters file-here
```
as written above or with the --debug or --verbose switch, I receive a "deployment failed" error. However, the failure was related to the incorrect path - file for both the template file and parameters file was not found but the error was simply, "deployment failed"

The error should say something more descriptive like, "_Deployment failed. File not found. Please check your path and try again._"

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: script

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.17

**OS Version:** What OS and version are you using?  
Answer here: MacOS 10.12.6

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: zsh / bash

**Comment by yonzhan** [comment]
@Juliehzl  add to S162.

**Comment by Juliehzl** [comment]
Hi @jldeen, what about your problem with latest azure cli version? If you don't have problems now, could you please close the issue? If you still have problems, feel free to let me know.
