### ISSUE TITLE
login: support service principal with certificate

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#450]
Was involved with a week long discussion with azure stack team on this. It is an important scenario, confirmed by ARM team as well due to easier revocation. 
I have exposed this support from adal-python before release, but azure-cli needs some plumbing work.

**Comment by twitchax** [comment]
We should schedule this for March.

**Comment by yugangw-msft** [comment]
//cc: @devigned @mayurid
I will use the same cert persistence mechanism of xplat, and that will enable creds sharing as well. Creds sharing for regular secret based service principal is already supported. 
So we should be good across.

**Comment by mayurid** [comment]
@yugangw-msft : This is upcoming sprint. Let me know if u disagree,

**Comment by yugangw-msft** [comment]
login code is complete and functions if user provides a pem encoded key file. For better e2e, I am extending the feature a bit to update `create-for-rbac` to generate a service principal with cert for users.

**Comment by devigned** [comment]
@yugangw-msft since cert auth service principals are the only way to securely provision and use the CLI, it would be a real shame to not provide that in create-for-rbac. This will be the main path for customers to authenticate on box with RBAC to ARM via an Azure provisioned VM.

I think we need to have the PEM option in create-for-rbac. I literally got a bug yesterday about creating a service principal lacking RBAC.

**Comment by yugangw-msft** [comment]
@devigned , I would love to do it. Like i said, my main concern (not technical related) is whether it is safe/compliant to assume a few fields' default values when create a self-signed certs :). When you run 'openssl', you will be asked to provide country, state, etc. I don't like to expose them through the `create-for-rbac` which has the main goal of being simple. So if it is fine to default to 'us', 'wa' states, yeah I can go ahead to wrap all those in.
But at the same time, check out my PR, you can use the openssl + CLI to provision a SP yourself.

**Comment by devigned** [comment]
How about create-for-rbac takes a PEM? Don't gen the PEM for them, but simply allow it to be specified on create-for-rbac.

**Comment by yugangw-msft** [comment]
> How about create-for-rbac takes a PEM? Don't gen the PEM for them, but allow it to be specified on create-for-rbac.

If a user has a cooked `PEM file` already, then he should just use `az ad app create` like I mentioned in the PR. For arguments to get into `create-for-rbac`, it must have a default value, because the goal of having the command is to get things easy, with zero mandatory fields.
On a second thought, since we are creating self signed certificate just for managing a few resources, I think it is fine to skip formal cert configurations like leave them blank, as long as users get a good pem file to login.  With that, yep, `create-for-rbac` can have the extra logics to get the e2e really easy. 

 > Perhaps, if you can load --password as a PEM, then use it.

If i get this right, my PR is already doing this, though it takes a pem file path but that is we discussed before, right?

**Comment by yugangw-msft** [comment]
@devigned, Per our discussions, I will expose one extra field "--cert" to accept existing `pem` so `create-for-rbac` could offer 3 extra pieces of help like `create app`, `create sp`, and `create role assignment`
