### ISSUE TITLE
az cosmosdb create errors with DB names greater than 36 characters

### ISSUE THREAD

**Issue by seanknox** [Azure/azure-cli#4505]
### Description
**Outline the issue here:**

STR:
- create a cosmosdb instance with a DB name greater than 36 characters

EXPECTED:
- The CLI says CosmosDB names can be between 3 and 50 characters, so I'd expect this to work

ACTUAL:
- Errors with "DatabaseAccount name must be at least 3 characters and at most 50characters"

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: pip

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
```
azure-cli (2.0.14)

acr (2.0.10)
acs (2.0.13)
appservice (0.1.13)
batch (3.1.1)
billing (0.1.3)
cdn (0.0.6)
cloud (2.0.7)
cognitiveservices (0.1.6)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.10)
consumption (0.1.3)
container (0.1.8)
core (2.0.13)
cosmosdb (0.1.11)
dla (0.0.10)
dls (0.0.12)
eventgrid (0.1.2)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.7)
iot (0.1.10)
keyvault (2.0.8)
lab (0.0.9)
monitor (0.0.8)
network (2.0.12)
nspkg (3.0.1)
profile (2.0.10)
rdbms (0.0.5)
redis (0.2.7)
resource (2.0.12)
role (2.0.10)
sf (1.0.6)
sql (2.0.9)
storage (2.0.12)
vm (2.0.12)

Python (Darwin) 2.7.13 (default, Aug 18 2017, 10:14:30) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]

Python location '/Users/seknox/lib/azure-cli/bin/python'


```
**OS Version:** What OS and version are you using?  
Answer here: MacOS Sierra

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: `zsh`

**Comment by moderakh** [comment]
@seanknox are you trying to create an account or a database within an existing account?

Could u plz let me know which?

**Comment by seanknox** [comment]
Here's the full command I ran: 

`az cosmosdb create -g sk5-hcp-underlay-southcentralus-cosmosdb -n sk5-hcp-underlay-southcentralus-cosmosdb --kind MongoDB --default-consistency-level Strong -o json`

**Comment by moderakh** [comment]
This is account management API which Digvijay owns it. 
@tjprescott please assign this to Digvijay.

**Comment by greg-pendlebury** [comment]
Spent a while bashing my head against this as well. You also need to consider multiple regions for geo-redundant deployments. Can get quite annoying when the initial deployment works and then Terraform gets a build error because the failover location does not work. Then Terraform falls out of sync with Azure.

In our case the region is '-australiaeast' and failover is '-australiasoutheast', so account names between 36 and 31 characters only partially succeed. Account names longer than 36 characters fail entirely.

**Comment by shurd** [comment]
Thank you all for the feedback. Account creation in the portal validates that the account name is less than 32 characters. We are now tracking a fix (Bug 445256) that will do this validation as well through our API, which the CLI uses. Our ETA for adding this validation is August.

**Comment by shurd** [comment]
Hi all, thank you for your patience. This change is something that we are making in our resource provider, so it does not follow the CLI release schedule. The change should be deployed in the next 2-3 weeks. I will update this issue when it is in production.

After the change, you will be able to create database accounts with names up to 44 characters long. The error message will better reflect the hard limits.

**Comment by shurd** [comment]
Hi everyone. The change has been deployed and you can now create accounts with global database account name length of 44 and region ids of up to 63 characters.
