### ISSUE TITLE
Cannot create empty Availability Set on ASDK (GA) with CLI 2.0.17

### ISSUE THREAD

**Issue by mattmcspirit** [Azure/azure-cli#4508]
### Description
Azure CLI successfully registered and connected to Azure Stack, however, we're unable to create an empty Availability Set with the following command:

az vm availability-set create --verbose --platform-fault-domain-count 1 --platform-update-domain-count 1 --location local --unmanaged --name TEST1AS --resource-group TEST1RG

Error = 

Deployment failed. {
  "error": {
    "code": "BadRequest",
    "target": "availabilitySet.sku",
    "message": "Could not find member 'sku' on object of type 'AvailabilitySet'. Path 'sku', line 1, position 7."
  }
}

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: MSI on Windows

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

azure-cli (2.0.17)

acr (2.0.11)
acs (2.0.15)
appservice (0.1.16)
batch (3.1.3)
billing (0.1.4)
cdn (0.0.8)
cloud (2.0.7)
cognitiveservices (0.1.7)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.10)
consumption (0.1.4)
container (0.1.10)
core (2.0.16)
cosmosdb (0.1.12)
dla (0.0.11)
dls (0.0.13)
eventgrid (0.1.3)
extension (0.0.2)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.9)
iot (0.1.11)
keyvault (2.0.10)
lab (0.0.10)
monitor (0.0.9)
network (2.0.14)
nspkg (3.0.1)
profile (2.0.12)
rdbms (0.0.6)
redis (0.2.8)
resource (2.0.14)
role (2.0.11)
servicefabric (0.0.3)
sf (1.0.8)
sql (2.0.11)
storage (2.0.15)
vm (2.0.14)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\mmcspirt\.azure\cliextensions'

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

**OS Version:** What OS and version are you using?  
Answer here: Tested on Windows 10 (1703), Mac OS X

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe, bash

**Comment by bganapa** [comment]
cc: @viananth

**Comment by mattmcspirit** [comment]
Thanks all!
