### ISSUE TITLE
command layout: 'group' should be at top

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#451]
4 reasons:
a. Portal does so
b. Node xplat does so
c. 'group' is not a child or sub of resource on the conceptual level
d. I feel tired of typing "az resource group deployment ...."

/CC: @jasonrshaver, @johanste, @derekbekoe, @burtbiel, @tjprescott

**Comment by johanste** [comment]
What is the status of this? I didn't see this mentioned in #1033, but I assume that we do want to do this, correct?

And my vote is to name the category resourcegroup, not just plain group.

**Comment by tjprescott** [comment]
:+1: for `resource-group`

**Comment by yugangw-msft** [comment]
@johanste , #1033 is for things we agree we will change. This one falls into a TBD which involves to moving more categories to top such as `provider`,  `feature`, and `policy`
And, i also like `resource-group`  you proposed

**Comment by derekbekoe** [comment]
@yugangw-msft this can be closed now?
