### ISSUE TITLE
how to assign several private IP-addresses to a nic?

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#4520]
### Description
**Outline the issue here:**
how to assign several private IP-addresses to a nic?
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
MSI
**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
root@Alexey-HP:~# az --version | head -1
azure-cli (2.0.17)

**OS Version:** What OS and version are you using?  
Answer here:
Microsoft Windows [Version 10.0.16294.1]

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
Bash on Windows

**Comment by troydai** [comment]
@tjprescott

**Comment by tjprescott** [comment]
When you create the NIC, the initial IP configuration is created. If you want additional private IP addresses, you can create addition IP configurations using `az network nic ip-config create`.
