### ISSUE TITLE
DLS and DLA should not be marked as PREVIEW in the output of "az -h"

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#4531]
Marked as "PREVIEW" implies other modules are GA which might not be true, e.g. webapp for linux
Let us quickly discuss the right term we should use
```bash
    dla              : (PREVIEW) Manage Data Lake Analytics accounts, jobs, and catalogs.
    dls              : (PREVIEW) Manage Data Lake Store accounts and filesystems.
```

//cc:@mayurid; @JasonRShaver

**Comment by JasonRShaver** [comment]
Moving this out of milestone as it has passed

**Comment by tjprescott** [comment]
We could make this an automated thing for modules based on the heuristic that anything with version < 2.0 is preview.  However, there are "branches" with a command module's subtree that could still be PREVIEW (network watcher for example) but it would be a workable solution for modules at least.

**Comment by yugangw-msft** [comment]
let us live with with.
