### ISSUE TITLE
Remove the "required" flag of the "--servers" parameter when creating a new AppGW address-pool

### ISSUE THREAD

**Issue by matiasma** [Azure/azure-cli#4533]
### Description
**Outline the issue here:**

Could you please remove the "required" flag of the "--servers" parameter when creating a new AppGW address-pool (az network application-gateway address-pool create)?

When I try to create a new AppGW backend address pool to associate to a VMSS I need to create a new one with some value in the --servers parameter, then I need to clean the backendAddresses property (AppGW) to allow the VMSS association.

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: apt-get

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 
azure-cli (2.0.18)

acr (2.0.12)
acs (2.0.16)
appservice (0.1.17)
backup (1.0.1)
batch (3.1.4)
billing (0.1.5)
cdn (0.0.9)
cloud (2.0.8)
cognitiveservices (0.1.8)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.11)
consumption (0.1.5)
container (0.1.11)
core (2.0.17)
cosmosdb (0.1.13)
dla (0.0.12)
dls (0.0.14)
eventgrid (0.1.4)
extension (0.0.3)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.10)
iot (0.1.12)
keyvault (2.0.11)
lab (0.0.11)
monitor (0.0.10)
network (2.0.15)
nspkg (3.0.1)
profile (2.0.13)
rdbms (0.0.7)
redis (0.2.9)
resource (2.0.15)
role (2.0.12)
servicefabric (0.0.4)
sql (2.0.12)
storage (2.0.16)
vm (2.0.15)

**OS Version:** What OS and version are you using?  
Answer here: Windows 10

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Bash on Windows

**Comment by tjprescott** [comment]
Hi @matiasma could you email me at alias trpresco. I would like to better understand your scenario as part of a larger look into how we can improve manipulating app gateways with VMSS.
