### ISSUE TITLE
'az interactive' throws unknown locale: UTF-8 on MacOS

### ISSUE THREAD

**Issue by felipebueno** [Azure/azure-cli#4536]
### Description

```az interactive``` command throws error ```unknown locale: UTF-8``` on MacOS command line.

---

It works after I set the ```LC_CTYPE``` environment variable to ```en```.

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
```brew update && brew install azure-cli```

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

**OS Version:** What OS and version are you using?  
Answer here:
```
➜  ~ az --version
azure-cli (2.0.18)

acr (2.0.12)
acs (2.0.16)
appservice (0.1.17)
backup (1.0.1)
batch (3.1.4)
billing (0.1.5)
cdn (0.0.9)
cloud (2.0.8)
cognitiveservices (0.1.8)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.11)
consumption (0.1.5)
container (0.1.11)
core (2.0.17)
cosmosdb (0.1.13)
dla (0.0.12)
dls (0.0.14)
eventgrid (0.1.4)
extension (0.0.3)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.10)
iot (0.1.12)
keyvault (2.0.11)
lab (0.0.11)
monitor (0.0.10)
network (2.0.15)
nspkg (3.0.1)
profile (2.0.13)
rdbms (0.0.7)
redis (0.2.9)
resource (2.0.15)
role (2.0.12)
servicefabric (0.0.4)
sql (2.0.12)
storage (2.0.16)
vm (2.0.15)

Python location '/usr/local/opt/python3/bin/python3.6'
Extensions directory '/Users/felipebueno/.azure/cliextensions'

Python (Darwin) 3.6.2 (default, Aug 27 2017, 16:33:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```
**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
```zsh``` on macOS Sierra 10.12.6

---

Screenshots
<img width="1280" alt="screen shot 2017-09-24 at 13 33 12" src="https://user-images.githubusercontent.com/241271/30784575-2fe26278-a12e-11e7-959a-9e2b15520c75.png">

<img width="1280" alt="screen shot 2017-09-24 at 13 34 37" src="https://user-images.githubusercontent.com/241271/30784582-3d3a72d0-a12e-11e7-92f8-7c5347fcea71.png">

**Comment by troydai** [comment]
@williexu, can you take a quick look?

**Comment by williexu** [comment]
This seems to be a bug in the way Python makes assumptions about the format of locale names and only appears to happen on the OSX terminal. The fix is to set `LANG`/`LC_` environmental variables to the correct string for your locale. Got this from [here,](https://conda.io/docs/user-guide/troubleshooting.html#macos-error-valueerror-unknown-locale-utf-8) [here](https://coderwall.com/p/-k_93g/mac-os-x-valueerror-unknown-locale-utf-8-in-python) [and here.](https://stackoverflow.com/questions/33716748/python-valueerror-unknown-locale-utf-8)

**Comment by troydai** [comment]
@felipebueno could you please try out this solution? I'll close this for now since it doesn't require a product fix. Please feel free to reopen if you have any further concerns.
