### ISSUE TITLE
WSL: _openssl.abi3.so: cannot enable executable stack as shared object requires: Invalid argument

### ISSUE THREAD

**Issue by nphmuller** [Azure/azure-cli#4538]
Issue https://github.com/Azure/azure-cli/issues/4154 has been fixed in `2.0.14`, but I'm running `2.0.18-1` in WSL and I still get the same error.

I've updated all packages (`sudo apt-get update && sudo apt-get upgrade`)
Win 10 build: 15063.608

I followed the installation instructions as described in the [docs](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest#install-on-windows) (under `Install with apt-get for Bash on Ubuntu on Windows`).
One thing I noticed is that adding the key file doesn't work.
```
sudo apt-key adv --keyserver packages.microsoft.com --recv-keys 417A0893
Executing: /tmp/tmp.oTqzpL3vmw/gpg.1.sh --keyserver
packages.microsoft.com
--recv-keys
417A0893
gpg: requesting key 417A0893 from hkp server packages.microsoft.com
?: packages.microsoft.com: Resource temporarily unavailable
gpgkeys: HTTP fetch error 7: couldn't connect: Resource temporarily unavailable
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver unreachable
gpg: keyserver communications error: public key not found
gpg: keyserver receive failed: public key not found
```

**Comment by derekbekoe** [comment]
Looks like it just failed to upgrade.
Does `az --version` show the latest version (2.0.18)?

I just trying installing using the normal apt-get instructions and ran some of the commands that failed in the other issue and they still work, `az appservice plan list`, `az webapp list`

**Comment by derekbekoe** [comment]
Try upgrading again. Maybe there was a transient issue with the keyserver.

**Comment by nphmuller** [comment]
I just figured the keyserver problem out. HKP port was blocked by our firewall. (Sorry!)

Could it be that the missing key was causing the exception? Because I can't reproduce it anymore, and I only remember changing the key.

I had the latest version though. The output of `az --version`:
```
azure-cli (2.0.18)

acr (2.0.12)
acs (2.0.16)
appservice (0.1.17)
backup (1.0.1)
batch (3.1.4)
billing (0.1.5)
cdn (0.0.9)
cloud (2.0.8)
cognitiveservices (0.1.8)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.11)
consumption (0.1.5)
container (0.1.11)
core (2.0.17)
cosmosdb (0.1.13)
dla (0.0.12)
dls (0.0.14)
eventgrid (0.1.4)
extension (0.0.3)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.10)
iot (0.1.12)
keyvault (2.0.11)
lab (0.0.11)
monitor (0.0.10)
network (2.0.15)
nspkg (3.0.1)
profile (2.0.13)
rdbms (0.0.7)
redis (0.2.9)
resource (2.0.15)
role (2.0.12)
servicefabric (0.0.4)
sql (2.0.12)
storage (2.0.16)
vm (2.0.15)

Python location '/opt/az/bin/python3'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Sep 23 2017, 00:13:17) 
[GCC 4.8.4]

Legal docs and information: aka.ms/AzureCliLegal
```
