### ISSUE TITLE
Progress report for the Storage commands (upload and download)

### ISSUE THREAD

**Issue by seguler** [Azure/azure-cli#4543]
### Description
Could we implement progress report for the Storage commands for uploading/downloading single file?

https://github.com/Azure/azure-storage-python/blob/717f616809c82b6cbf3e258f3d94303e6fabe411/azure/storage/file/_upload_chunking.py

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

**OS Version:** What OS and version are you using?  
Answer here:

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

**Comment by troydai** [comment]
https://github.com/Azure/azure-cli/issues/4744
