### ISSUE TITLE
Archived (.tgz) files aren't downloading properly from blob

### ISSUE THREAD

**Issue by TwinkleChawla** [Azure/azure-cli#4558]
### Description
I archived my data (.tgz) on server-1, and uploaded to the container as blob. 

```
$ az storage blob upload -f file_name.tgz -c container_name -n file_name.tgz --account-name account_name --account-key account_key
```
Zipping and Unzipping working fine with server-1,
```
$ file -s file_name.tgz 
file_name.tgz: gzip compressed data, from Unix, last modified: Mon Sep 18 13:44:22 2017
```

On server1:
Original file size is 31M
Archived file size is 7.79M
I check the blob size from UI it was 7.79M
Tried to download archive file on local machine from UI, the downloaded archive's size was 32.4M. 

Then, I downloaded the file to server-2 as,
```
$ az storage blob download -c container_name -f /home/username/file_name.tgz -n file_name.tgz --account-name account_name --account-key account_key
```
** .tgz file gets downloaded [Bigger files showing me "Received response with content" as output]
I tried doing unzipping the file as

```
$ tar xzvf file_name.tgz
 
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
Bigger files when downloaded, giving me output as 
```
Received response with content
```

Also, tried 'dtrx' utility to unzip the file. This gets recover but very less data is there in the folder.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: apt-get

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.16 (Tried 2.0.17 also)

**OS Version:** What OS and version are you using?  
Answer here: Ubuntu 16.04

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by troydai** [comment]
It is fixed in 2.0.18: https://github.com/Azure/azure-cli/issues/4490

**Comment by troydai** [comment]
Please try this scenario with latest CLI. Thanks.

**Comment by TwinkleChawla** [comment]
Thanks! it is working with 2.0.18 version.

**Comment by tmoretti** [comment]
Just for reference for others with same issue, I still got this download problem with 2.0.18 cli version with a file uploaded with previous versions.
I reuploaded the file using the 2.0.18 and download problem has gone away.

**Comment by troydai** [comment]
@tmoretti thank you for the information. You're right. the problem was the upload command in previous two releases. The newly added content type guess logic put `gzip` as content encoding for `tar` files and the SDK failed to download blobs with that content encoding.

**Comment by DheerajJoshi** [comment]
Faced the same issue, but works properly in 2.0.18

**Comment by DheerajJoshi** [comment]
Faced the same issue, but works properly in 2.0.18
