### ISSUE TITLE
The error message print when .azure folder is corrupt is not helpful.

### ISSUE THREAD

**Issue by hajbal** [Azure/azure-cli#4567]
### Description
Loading all installed modules as module with name 'login' not found.
Installed command modules ['acr', 'acs', 'appservice', 'backup', 'batch', 'billing', 'cdn', 'cloud', 'cognitiveservices', 'component', 'configure', 'consumption', 'container', 'cosmosdb', 'dla', 'dls', 'eventgrid', 'extension', 'feedback', 'find', 'interactive', 'iot', 'keyvault', 'lab', 'monitor', 'network', 'profile', 'rdbms', 'redis', 'resource', 'role', 'servicefabric', 'sql', 'storage', 'vm']

When i type az login --help i get response with the help. But I cannot login to azure. It was working before for quite a long time. Any ideas ? What can i do ?  Thanks. 

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
apt-get
**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
azure-cli (2.0.18)

acr (2.0.12)
acs (2.0.16)
appservice (0.1.17)
backup (1.0.1)
batch (3.1.4)
billing (0.1.5)
cdn (0.0.9)
cloud (2.0.8)
cognitiveservices (0.1.8)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.11)
consumption (0.1.5)
container (0.1.11)
core (2.0.17)
cosmosdb (0.1.13)
dla (0.0.12)
dls (0.0.14)
eventgrid (0.1.4)
extension (0.0.3)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.10)
iot (0.1.12)
keyvault (2.0.11)
lab (0.0.11)
monitor (0.0.10)
network (2.0.15)
nspkg (3.0.1)
profile (2.0.13)
rdbms (0.0.7)
redis (0.2.9)
resource (2.0.15)
role (2.0.12)
servicefabric (0.0.4)
sql (2.0.12)
storage (2.0.16)
vm (2.0.15)

**OS Version:** What OS and version are you using?  
Answer here:
Ubuntu 16.04 LTS
**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
bash

**Comment by yugangw-msft** [comment]
//cc: @derekbekoe

**Comment by troydai** [comment]
Could you try remove the CLI and install again?

**Comment by hajbal** [comment]
It happened, and still not working. We got the same error : Unterminated string starting at: line 1 column 2905 (char 2904).

**Comment by hajbal** [comment]
We used this step by step on both server : https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest .

**Comment by tjprescott** [comment]
`login` is part of the `profile` module, which it shows you have loaded.  If you can run `az login -h` then it seems the command is there. What happens when you try and run the command?

**Comment by derekbekoe** [comment]
`Loading all installed modules as module with name 'login' not found.` is a debug message and not an error message.
It happens all the time so that's a red-herring.

**Comment by yugangw-msft** [comment]
Based on Derek's command, @hajbal, you can still execute `az login`, please let us know otherwise

**Comment by hajbal** [comment]
@derekbekoe You're right. Sorry. So guys, the command there is. but we still can't login to azure. Should we check some config file or something ?

**Comment by hajbal** [comment]
@tjprescott Yes, i can run the `az login -h` .

**Comment by tjprescott** [comment]
What happens when you run `az login`?

**Comment by hajbal** [comment]
`az login -u "username" -p "password" `  
I get the following error: 
Unterminated string starting at: line 1 column 2905 (char 2904)

**Comment by yugangw-msft** [comment]
Please use `az login -u "username" -p "password" --debug` and share with us the output

**Comment by hajbal** [comment]
Here is the debug log : 

Loading all installed modules as module with name 'login' not found.
Installed command modules ['acr', 'acs', 'appservice', 'backup', 'batch', 'billing', 'cdn', 'cloud', 'cognitiveservices', 'component', 'configure', 'consumption', 'container', 'cosmosdb', 'dla', 'dls', 'eventgrid', 'extension', 'feedback', 'find', 'interactive', 'iot', 'keyvault', 'lab', 'monitor', 'network', 'profile', 'rdbms', 'redis', 'resource', 'role', 'servicefabric', 'sql', 'storage', 'vm']
Current cloud config:
{'endpoints': {'active_directory': 'https://login.microsoftonline.com',
               'active_directory_data_lake_resource_id': 'https://datalake.azure.net/',
               'active_directory_graph_resource_id': 'https://graph.windows.net/',
               'active_directory_resource_id': 'https://management.core.windows.net/',
               'batch_resource_id': 'https://batch.core.windows.net/',
               'gallery': 'https://gallery.azure.com/',
               'management': 'https://management.core.windows.net/',
               'resource_manager': 'https://management.azure.com/',
               'sql_management': 'https://management.core.windows.net:8443/',
               'vm_image_alias_doc': 'https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json'},
 'is_active': True,
 'name': 'AzureCloud',
 'profile': 'latest',
 'suffixes': {'azure_datalake_analytics_catalog_and_job_endpoint': 'azuredatalakeanalytics.net',
              'azure_datalake_store_file_system_endpoint': 'azuredatalakestore.net',
              'keyvault_dns': '.vault.azure.net',
              'sql_server_hostname': '.database.windows.net',
              'storage_endpoint': 'core.windows.net'}}
Registered application event handler 'CommandTableParams.Loaded' at <function add_id_parameters at 0x7f3bf6687d08>
Registered application event handler 'CommandTable.Loaded' at <function add_id_parameters at 0x7f3bf6687d08>
Loaded module 'acr' in 0.009 seconds.
Loaded module 'acs' in 0.001 seconds.
Registered application event handler 'CommandParser.Parsing' at <function deprecate at 0x7f3bf6620400>
Loaded module 'appservice' in 0.002 seconds.
Loaded module 'backup' in 0.001 seconds.
Did not load Batch Extensions module
No module named 'azure.cli.command_modules.batch_extensions'
Loaded module 'batch' in 0.010 seconds.
Loaded module 'billing' in 0.001 seconds.
Loaded module 'cdn' in 0.002 seconds.
Loaded module 'cloud' in 0.001 seconds.
Loaded module 'cognitiveservices' in 0.001 seconds.
Loaded module 'component' in 0.001 seconds.
Loaded module 'configure' in 0.001 seconds.
Loaded module 'consumption' in 0.001 seconds.
Loaded module 'container' in 0.001 seconds.
Registered application event handler 'CommandParser.Parsing' at <function deprecate at 0x7f3bf653fa60>
Loaded module 'cosmosdb' in 0.002 seconds.
Loaded module 'dla' in 0.001 seconds.
Loaded module 'dls' in 0.001 seconds.
Loaded module 'eventgrid' in 0.001 seconds.
Loaded module 'extension' in 0.001 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.000 seconds.
Loaded module 'interactive' in 0.001 seconds.
Loaded module 'iot' in 0.001 seconds.
Loaded module 'keyvault' in 0.002 seconds.
Loaded module 'lab' in 0.001 seconds.
Loaded module 'monitor' in 0.001 seconds.
Loaded module 'network' in 0.009 seconds.
Loaded module 'profile' in 0.001 seconds.
Loaded module 'rdbms' in 0.002 seconds.
Loaded module 'redis' in 0.001 seconds.
Loaded module 'resource' in 0.002 seconds.
Loaded module 'role' in 0.001 seconds.
Loaded module 'servicefabric' in 0.001 seconds.
Loaded module 'sql' in 0.002 seconds.
Loaded module 'storage' in 0.011 seconds.
Loaded module 'vm' in 0.003 seconds.
Loaded all modules in 0.075 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: '/root/.azure/cliextensions'
Application event 'CommandTable.Loaded' with event data {'command_table': {'login': <azure.cli.core.commands.CliCommand object at 0x7f3bf6487cf8>}}
Application event 'CommandParser.Loaded' with event data {'parser': AzCliCommandParser(prog='az', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)}
Application event 'CommandTableParams.Loaded' with event data {'command_table': {'login': <azure.cli.core.commands.CliCommand object at 0x7f3bf6487cf8>}}
Application event 'CommandParser.Parsing' with event data {'argv': ['login', '-u', 'drvmoperator@vidanetazurecoresystems.onmicrosoft.com', '-p', '****']}
Application event 'CommandParser.Parsed' with event data {'command': 'login', 'args': Namespace(_command_package='login', _jmespath_query=None, _log_verbosity_debug=False, _log_verbosity_verbose=False, _output_format='json', _parser=AzCliCommandParser(prog='az login', usage=None, description='Log in to access Azure subscriptions', formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True), _validators=[], allow_no_subscriptions=False, command='login', func=<azure.cli.core.commands.CliCommand object at 0x7f3bf6487c [...]
attempting to read file /root/.azure/accessTokens.json as utf-8-sig

**Comment by yugangw-msft** [comment]
Please send me the `/root/.azure/accessTokens.json` and `/root/.azure/azureProfile.json` at yugangw at microsoft dot com
At the same time, run `az account clear` first should unblock you

**Comment by hajbal** [comment]
We solved the problem: We renamed the .azure directory to .old_azure and tried again the login and it is working now. So i think its the same as `az account clear` .  Thanks for your time guys and the help.

**Comment by troydai** [comment]
We probably should fix the unhelpful error message.

**Comment by yugangw-msft** [comment]
Agreed, I will take this issue.
