### ISSUE TITLE
Using JMESPath queries with Azure CLI 2.0

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#4575]
### Description
**Outline the issue here:**
Is it possible to rewrite the article https://docs.microsoft.com/en-us/cli/azure/query-azure-cli?view=azure-cli-latest with clear explanation of query syntax (the difference between [] and {} for example), provide more complex examples?
My particular question would be to get name for ip config in 'az network nic list --resource-group myresourcegroup' which is not described in https://docs.microsoft.com/pdfstore/en-us/Azure.azure-documents/live/virtual-machines/linux.pdf

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
MSI
**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
2.0.18
**OS Version:** What OS and version are you using?  
Answer here:
Microsoft Windows [Version 10.0.16299.0]
**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
Bash on Windows

**Comment by tjprescott** [comment]
The primary reference for JMESPath query syntax is www.jmespath.org. One great way to play around with the syntax would be to pipe the output of your command to JQ. There you can write queries and interactively see the result.
