### ISSUE TITLE
[Network] AppGateway - unable to disable TLS version

### ISSUE THREAD

**Issue by djpicard** [Azure/azure-cli#4589]
### Description
**Outline the issue here:**
Attempted to disable TLS 1.0 and TLS 1.1 through the CLI. 

az network application-gateway ssl-policy set --resource-group ${res_group} --gateway-name ${entity_prefix}-cust-gw --disabled-ssl-protocols TLSv1_0 TLSv1_1 --no-wait 
az network application-gateway ssl-policy set --resource-group ${res_group} --gateway-name ${entity_prefix}-agent-gw --disabled-ssl-protocols TLSv1_0 TLSv1_1 --no-wait 

However, this doesn't actually disable the TLS Protocols. I had to use powershell in order to actually disable the protocols. Commands for that are as follows:

Add-AzureRmAccount

Select-AzureRmSubscription -SubscriptionID 97823fae-28fd-46e3-aef3-b81a06cd04e7

Get-AzureRMApplicationGatewayAvailableSslOptions

$gw = Get-AzureRmApplicationGateway -Name AdatumAppGateway -ResourceGroup AdatumAppGatewayRG

Set-AzureRmApplicationGatewaySslPolicy -ApplicationGateway $gw -PolicyType Custom -MinProtocolVersion TLSv1_2 -CipherSuite "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384", "TLS_RSA_WITH_AES_128_GCM_SHA256"

Get-AzureRmApplicationGatewaySslPolicy -ApplicationGateway $gw

Set-AzureRmApplicationGateway -ApplicationGateway $gw
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: brew

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: azure-cli (2.0.14)

**OS Version:** What OS and version are you using?  
Answer here: Mac OS

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by tjprescott** [comment]
In your PS command, you supplied many more parameters.  Try the CLI equivalent:

```
az network application-gateway ssl-policy set --cipher-suites TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 TLS_RSA_WITH_AES_128_GCM_SHA256 --min-protocol-version TLSv1_2
```

Note that when using `set` you must supply all parameters each time (it is not an upsert method). Also, you shouldn't need to explicitly supply `--policy-type` as it will automatically be set based on other supplied parameters.

**Comment by tjprescott** [comment]
If you still have an issue, feel free to reopen.
