### ISSUE TITLE
webapp: msi support in creates

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#4592]
Similar like `az vm/vmss`:
1. expose `--assign-identity`, `--scope`,  and `role` from `az webapp/function create`
2. ~expose `az webapp/functionapp assign-identity` commands~ (Done)

We should try to reuse the existing logic in the vm command module, ideally get the routines to the common module

**Comment by ahmedelnably** [comment]
@panchagnula please track the MSI work using this

**Comment by yugangw-msft** [comment]
Done

**Comment by yugangw-msft** [comment]
Actually, exposing from `create` command was agreed that we should do it at some point, hence let us keep this active till we get it done with explicit identity together

**Comment by yugangw-msft** [comment]
Chatted with @panchagnula, we can live w/o this, but we can reactivate if we have user votes
