### ISSUE TITLE
no attribute 'getargspec'

### ISSUE THREAD

**Issue by gatneil** [Azure/azure-cli#4598]
I just updated my CLI install on Ubuntu 16.04-LTS using the command `curl -L https://aka.ms/InstallAzureCli | bash` (then did the `exec -l $SHELL` command). Now, whenever I try to run an az command I get the error below. 

$ az --version
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/negat/lib/azure-cli/lib/python2.7/site-packages/azure/cli/__main__.py", line 9, in <module>
    import azure.cli.main
  File "/home/negat/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/main.py", line 10, in <module>
    from azure.cli.core.application import APPLICATION, Configuration
  File "/home/negat/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 11, in <module>
    from azure.cli.core.parser import AzCliCommandParser, enable_autocomplete
  File "/home/negat/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/parser.py", line 12, in <module>
    import azure.cli.core._help as _help
  File "/home/negat/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/_help.py", line 12, in <module>
    from azure.cli.core.commands import ExtensionCommandSource
  File "/home/negat/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 33, in <module>
    from ._introspection import (extract_args_from_signature,
  File "/home/negat/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/_introspection.py", line 6, in <module>
    import inspect
  File "/usr/lib/python2.7/inspect.py", line 39, in <module>
    import tokenize
  File "/usr/lib/python2.7/tokenize.py", line 31, in <module>
    from token import *
  File "token.py", line 6, in <module>
    from azure.common.credentials import ServicePrincipalCredentials
  File "/home/negat/lib/azure-cli/local/lib/python2.7/site-packages/azure/common/credentials.py", line 51, in <module>
    from msrest.authentication import (
  File "/home/negat/lib/azure-cli/local/lib/python2.7/site-packages/msrest/__init__.py", line 27, in <module>
    from .configuration import Configuration
  File "/home/negat/lib/azure-cli/local/lib/python2.7/site-packages/msrest/configuration.py", line 36, in <module>
    import requests
  File "/home/negat/lib/azure-cli/local/lib/python2.7/site-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/home/negat/lib/azure-cli/local/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/home/negat/lib/azure-cli/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/home/negat/lib/azure-cli/local/lib/python2.7/site-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/home/negat/lib/azure-cli/local/lib/python2.7/site-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography import utils
  File "/home/negat/lib/azure-cli/local/lib/python2.7/site-packages/cryptography/utils.py", line 80, in <module>
    signature = inspect.getargspec
AttributeError: 'module' object has no attribute 'getargspec'

**Comment by derekbekoe** [comment]
Do you have the required native dependencies installed?
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest#a-namelinuxinstall-on-linux-without-apt-get

**Comment by gatneil** [comment]
Yup:

0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by derekbekoe** [comment]
Can you provide the output of `~/lib/azure-cli/bin/python --version` and the output of `~/lib/azure-cli/bin/pip freeze`?

**Comment by gatneil** [comment]
$ ~/lib/azure-cli/bin/python --version
Python 2.7.12

$ ~/lib/azure-cli/bin/pip freeze
adal==0.4.7
applicationinsights==0.11.1
argcomplete==1.9.2
asn1crypto==0.23.0
azure-batch==3.1.0
azure-cli==2.0.18
azure-cli-acr==2.0.12
azure-cli-acs==2.0.16
azure-cli-appservice==0.1.17
azure-cli-backup==1.0.1
azure-cli-batch==3.1.4
azure-cli-billing==0.1.5
azure-cli-cdn==0.0.9
azure-cli-cloud==2.0.8
azure-cli-cognitiveservices==0.1.8
azure-cli-command-modules-nspkg==2.0.1
azure-cli-component==2.0.7
azure-cli-configure==2.0.11
azure-cli-consumption==0.1.5
azure-cli-container==0.1.11
azure-cli-core==2.0.17
azure-cli-cosmosdb==0.1.13
azure-cli-dla==0.0.12
azure-cli-dls==0.0.14
azure-cli-eventgrid==0.1.4
azure-cli-extension==0.0.3
azure-cli-feedback==2.0.6
azure-cli-find==0.2.7
azure-cli-interactive==0.3.10
azure-cli-iot==0.1.12
azure-cli-keyvault==2.0.11
azure-cli-lab==0.0.11
azure-cli-monitor==0.0.10
azure-cli-network==2.0.15
azure-cli-nspkg==3.0.1
azure-cli-profile==2.0.13
azure-cli-rdbms==0.0.7
azure-cli-redis==0.2.9
azure-cli-resource==2.0.15
azure-cli-role==2.0.12
azure-cli-servicefabric==0.0.4
azure-cli-sql==2.0.12
azure-cli-storage==2.0.16
azure-cli-vm==2.0.15
azure-common==1.1.8
azure-datalake-store==0.0.16
azure-graphrbac==0.31.0
azure-keyvault==0.3.6
azure-mgmt-authorization==0.30.0
azure-mgmt-batch==4.1.0
azure-mgmt-billing==0.1.0
azure-mgmt-cdn==0.30.2
azure-mgmt-cognitiveservices==1.0.0
azure-mgmt-compute==3.0.0rc1
azure-mgmt-consumption==0.1.0
azure-mgmt-containerinstance==0.1.0
azure-mgmt-containerregistry==0.3.1
azure-mgmt-containerservice==1.0.0
azure-mgmt-datalake-analytics==0.1.6
azure-mgmt-datalake-nspkg==2.0.0
azure-mgmt-datalake-store==0.1.6
azure-mgmt-devtestlabs==2.0.0
azure-mgmt-dns==1.0.1
azure-mgmt-documentdb==0.1.3
azure-mgmt-eventgrid==0.2.0
azure-mgmt-iothub==0.2.2
azure-mgmt-keyvault==0.40.0
azure-mgmt-monitor==0.2.1
azure-mgmt-network==1.5.0rc3
azure-mgmt-nspkg==2.0.0
azure-mgmt-rdbms==0.1.0
azure-mgmt-recoveryservices==0.1.0
azure-mgmt-recoveryservicesbackup==0.1.1
azure-mgmt-redis==4.1.0
azure-mgmt-resource==1.2.0rc2
azure-mgmt-servicefabric==0.1.0
azure-mgmt-sql==0.8.0
azure-mgmt-storage==1.2.0
azure-mgmt-trafficmanager==0.30.0
azure-mgmt-web==0.32.0
azure-monitor==0.3.0
azure-multiapi-storage==0.1.4
azure-nspkg==2.0.0
bcrypt==3.1.3
certifi==2017.7.27.1
cffi==1.11.0
chardet==3.0.4
colorama==0.3.9
cryptography==2.0.3
enum34==1.1.6
funcsigs==1.0.2
futures==3.1.1
humanfriendly==4.4.1
idna==2.6
ipaddress==1.0.18
isodate==0.5.4
jmespath==0.9.3
keyring==10.4.0
mock==2.0.0
monotonic==1.3
msrest==0.4.15
msrestazure==0.4.14
oauthlib==2.0.4
paramiko==2.3.1
pathlib2==2.3.0
pbr==3.1.1
prompt-toolkit==1.0.15
pyasn1==0.3.6
pycparser==2.18
pydocumentdb==2.2.1
Pygments==2.2.0
PyJWT==1.5.3
PyNaCl==1.1.2
pyOpenSSL==17.3.0
python-dateutil==2.6.1
pytz==2017.2
PyYAML==3.12
requests==2.18.4
requests-oauthlib==0.8.0
scandir==1.6
scp==0.10.2
SecretStorage==2.3.1
six==1.11.0
sshtunnel==0.1.2
tabulate==0.7.7
urllib3==1.22
vsts-cd-manager==0.118.0
wcwidth==0.1.7
Whoosh==2.7.4
xmltodict==0.11.0

**Comment by derekbekoe** [comment]
Okay I have done some investigations.
In short, I cannot repro this on my VMs.

Does the command below work for you?
```
$ python -c 'import inspect; print(inspect.getargspec)'
<function getargspec at 0x7feedb82bb90>
```

If it doesn't work, do you have a file named `inspect.py` in your current directory or maybe on your path? It's a built-in Python module so no reason why that would fail.
https://docs.python.org/2/library/inspect.html#inspect.getargspec

---

My full investigation:

I created an Ubuntu 16.04 VM on Azure, installed `pip`, `virtualenv`, then installed the CLI.
I then create my freeze file and compare it with yours and there's no difference.

```
$ az vm create -g myresourcegroup --image UbuntuLTS -n myvmclitest1
$ ssh myvmclitest1
$ sudo apt-get update && sudo apt-get install -y python libssl-dev libffi-dev python-dev build-essential
$ wget https://bootstrap.pypa.io/get-pip.py
$ sudo python get-pip.py
$ sudo pip install virtualenv
$ virtualenv test1
$ source test1/bin/activate
$ pip install azure-cli
$ pip freeze > myfreeze.txt
$ diff myfreeze.txt yourfreeze.txt 
```

```
$ python --version
Python 2.7.12
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

**Comment by gatneil** [comment]
Yeah, that command works for me:

```
$ python -c 'import inspect; print(inspect.getargspec)'
<function getargspec at 0x7ff4ac3d00c8>
```

This VM has definitely been through a lot, so it's possible that there is some configuration issue with it. I'll just nuke the machine and make a new one :).

Thanks for the investigation!
