### ISSUE TITLE
Fails to install on windows

### ISSUE THREAD

**Issue by justinmchase** [Azure/azure-cli#4601]
### Description
I am just running the install script in the readme and it fails:
```
$ curl -L https://aka.ms/InstallAzureCli | bash
```

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:

I am running the latest version of Git Bash and I just ran the curl script from the README.

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:

I don't know because I can't install it.

**OS Version:** What OS and version are you using?  
Answer here:

Windows 10.

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:

Git Bash (aka bash)

**Extra Info:**
I have python27 already installed on my machine because nodejs requires it. I see in the output its trying to install python and pip:
```
Already using interpreter C:\Python27\python.exe
New python executable in E:\azure\Scripts\python.exe
Installing setuptools, pip, wheel...done.
```
When I look in my bin folder it is empty:
![2017-10-03](https://user-images.githubusercontent.com/10974/31135884-0f219c52-a82c-11e7-8834-121af880db15.png)

But python is in the azure scripts folder:
![2017-10-03 1](https://user-images.githubusercontent.com/10974/31136067-abe9456c-a82c-11e7-810c-dcd1832d7ad7.png)

But the error states the path its trying to exectute pip at is in the `bin` folder:
```
-- Executing: ['E:\\azure\\bin\\pip', 'install', '--cache-dir', 'c:\\users\\justin\\appdata\\local\\temp\\tmp3v1zxj', 'azure-cli', '--upgrade']
```

I believe the path should be `E:\\azure\\Scripts\\pip`. Interestingly `E:\\azure\\bin\\` does not exist at all.

**Full Error:**
```
$ curl -L https://aka.ms/InstallAzureCli | bash
100   167  100   167    0     0    167      0  0:00:01 --:--:--  0:00:01   594
100  1367  100  1367    0     0   1367      0  0:00:01 --:--:--  0:00:01  6733
Downloading Azure CLI install script from https://azurecliprod.blob.core.windows.net/install.py to /tmp/azure_cli_install_tmp_1Nrb.
######################################################################## 100.0%
/tmp/azure_cli_install_tmp_1Nrb: OK
Running install script.
-- Verifying Python version.
-- Python version 2.7.6 okay.

===> In what directory would you like to place the install? (leave blank to use 'C:\Users\justin\lib\azure-cli'): E:\azure
-- Creating directory 'E:\azure'.
-- We will install at 'E:\azure'.

===> In what directory would you like to place the 'az' executable? (leave blank to use 'C:\Users\justin\bin'): E:\bin
-- Creating directory 'E:\bin'.
-- The executable will be in 'E:\bin'.
-- Downloading virtualenv package from https://pypi.python.org/packages/source/v/virtualenv/virtualenv-15.0.0.tar.gz.
-- Downloaded virtualenv package to c:\users\justin\appdata\local\temp\tmp3v1zxj\virtualenv-15.0.0.tar.gz.
-- Checksum of c:\users\justin\appdata\local\temp\tmp3v1zxj\virtualenv-15.0.0.tar.gz OK.
-- Extracting 'c:\users\justin\appdata\local\temp\tmp3v1zxj\virtualenv-15.0.0.tar.gz' to 'c:\users\justin\appdata\local\temp\tmp3v1zxj'.
-- Executing: ['C:\\Python27\\python.exe', 'virtualenv.py', '--python', 'C:\\Python27\\python.exe', 'E:\\azure']
Already using interpreter C:\Python27\python.exe
New python executable in E:\azure\Scripts\python.exe
Installing setuptools, pip, wheel...done.
-- Executing: ['E:\\azure\\bin\\pip', 'install', '--cache-dir', 'c:\\users\\justin\\appdata\\local\\temp\\tmp3v1zxj', 'azure-cli', '--upgrade']
Traceback (most recent call last):
  File "C:/Users/justin/AppData/Local/Temp/azure_cli_install_tmp_1Nrb", line 370, in <module>
    main()
  File "C:/Users/justin/AppData/Local/Temp/azure_cli_install_tmp_1Nrb", line 356, in main
    install_cli(install_dir, tmp_dir)
  File "C:/Users/justin/AppData/Local/Temp/azure_cli_install_tmp_1Nrb", line 140, in install_cli
    exec_command(cmd)
  File "C:/Users/justin/AppData/Local/Temp/azure_cli_install_tmp_1Nrb", line 100, in exec_command
    subprocess.check_call(command_list, cwd=cwd, env=env)
  File "C:\Python27\lib\subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 709, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

**Comment by tjprescott** [comment]
If you are installing on bash, you should install on WSL (Windows Subsystem Linux).  `git bash` is not the same and not supported. It will generally work, but you will very likely run into problems using it.

For Windows you can install using an MSI.  https://aka.ms/InstallAzureCliWindows

@derekbekoe we should probably update the install instructions on the landing page to reference the different ways on installing. I had to search for Azure CLI MSI to find this link.

**Comment by derekbekoe** [comment]
The `curl` script does not support Windows.
These are the instructions for installing on Windows - https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest#install-on-windows.

I will create a PR to remove `curl -L https://aka.ms/InstallAzureCli | bash` from the README

**Comment by sptramer** [comment]
@derekbekoe Should the README just link to the install page on docs rather than containing its own install instructions? There are so many different recommended installation methods depending on the user system that I would be worried about drift.

**Comment by justinmchase** [comment]
I'm trying to use this from within a gulp script, so its doing some shell exec, as far as I know calling into the windows subsystem isn't possible in this way, so I really need this to work from git bash.

I can't use powershell for this because not all developers are on windows.

I tried installing `azure-cli` from npm, which works but they're now saying that its deprecated in favor of this tool, which you're now telling me that isn't supported on windows. So this leaves a pretty big gap for windows developers who are interested in cross plat, unless I'm missing something?

How hard is it to just fix the bash script to just point to the right directory when run in bash on windows?

**Comment by justinmchase** [comment]
On second thought I guess I can just run everything through the subsystem... I have been using VS Code to do this but it looks like there may be a solution:
https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/Debugger/gdb/Windows%20Subsystem%20for%20Linux.md

And if not I guess I can live with just doing it all through the subsystem. I'll play around with it thanks.
