### ISSUE TITLE
[AAD] az ad app create can not include --identifier-uris

### ISSUE THREAD

**Issue by gregdegruy** [Azure/azure-cli#4615]
### Description
Now clear example of what value for `--identifier-uris` is expected. After peeking at other AAD apps I've registered, seems to be a mix of the domain of my tenant directory and a GUID. 

Where does this GUID come from, it's not my tenant ID or my Azure subscription ID? Am I supoosed to use the `az` tool to generate a GUID and include it in my `--identifier-uris`?

[az_ad_app_create](https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest#az_ad_app_create) < click here to go to docs on how I was able to construct the below command.

```shell
az ad app create --display-name "AwsomeName" --homepage "https://login.windows.net" --identifier-uris "<WHAT_GOES_HERE?>" --reply-urls "https://myawsomesite.azurewebsites.net/.auth/login/aad/callback"
```

JSON snippet from the manifest of my AAD apps I've deployed from the portal.
```c#
{
  // metadata json . . .
  // v ISSUE HERE v
  "identifierUris": [
    "https://microsoft.onmicrosoft.com/0eea48bc-8b2f-464e-b814-d870f4f132bf"
  // more metadata json . . .
}
```
---

### Environment summary

**Install Method:** 
 apt-get 

**CLI Version:** 
```shell
azure-cli (2.0.17)

Python location '/opt/az/bin/python3'
Extensions directory '/home/mr-u/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Sep 11 2017, 20:11:41)
[GCC 4.8.4]
```

**OS Version:** 
Windows  10

**Shell Type:**
Bash on Windows

**Comment by yugangw-msft** [comment]
@gregdegruy, any uri will work, as long as it is unique, and it doesn't need to exist, so `https://mygreatapp` will go.

**Comment by gregdegruy** [comment]
ah cool. so the GUID is optional sounds like? going to test this out and add to thread if I'm blocked again.

**Comment by yugangw-msft** [comment]
GUID is optional

**Comment by yugangw-msft** [comment]
Closing, figuring you have got things work :)
