### ISSUE TITLE
az policy assignment create: definition <id> could not be found

### ISSUE THREAD

**Issue by brharr** [Azure/azure-cli#4617]
### Description

I am trying to create an Azure Policy Assignment using the CLI. I copy and past the name of the policy using the az policy definition list command, but when I run the command, I get the following error:

The policy definition '2a0e14a6-b0a6-4fab-991a-187a4f81c498' could not be found.

This is an out of the box policy, but I still get the same error and I am just doing a copy and paste, so I have verified that all of the values are correct.

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: MSI Installer on Laptop and via Cloud Shell

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: Latest and Cloud Shell version

**OS Version:** What OS and version are you using?  
Answer here: Windows 10 & Cloud Shell

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash shell and cmd.exe

**Comment by yugangw-msft** [comment]
@vivsriaus, assigning this to you since you are already working on this per our mail conversation

**Comment by vivsriaus** [comment]
PR [here](https://github.com/Azure/azure-cli/pull/4625)

**Comment by tjprescott** [comment]
PR #4625 merged. This should be fixed.
