### ISSUE TITLE
IOT Hub Device commands fail in Azure Government

### ISSUE THREAD

**Issue by milope** [Azure/azure-cli#4635]
### Description
Commands such as az iot device create --hub-name milopeiot -d testDevice fail when using the AzureUSGovernment environment. It appears to find the hub fine, but when creating the device, it fails as it is trying to connect to milopeiot.azure-devices.net instead of milopeiot.azure-devices.us. I'm not sure if I'm right on the next part, but this appears to be traced to a function named _get_device_client as it appears to use azure-devices.net directly in line 330 (link below):

https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/custom.py#L330

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: Used the latest MSI.

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 

azure-cli (2.0.18)

acr (2.0.12)
acs (2.0.16)
appservice (0.1.17)
backup (1.0.1)
batch (3.1.4)
billing (0.1.5)
cdn (0.0.9)
cloud (2.0.8)
cognitiveservices (0.1.8)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.11)
consumption (0.1.5)
container (0.1.11)
core (2.0.17)
cosmosdb (0.1.13)
dla (0.0.12)
dls (0.0.14)
eventgrid (0.1.4)
extension (0.0.3)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.10)
iot (0.1.12)
keyvault (2.0.11)
lab (0.0.11)
monitor (0.0.10)
network (2.0.15)
nspkg (3.0.1)
profile (2.0.13)
rdbms (0.0.7)
redis (0.2.9)
resource (2.0.15)
role (2.0.12)
servicefabric (0.0.4)
sql (2.0.12)
storage (2.0.16)
vm (2.0.15)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\[username]\.azure\cliextensions'

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

**OS Version:** What OS and version are you using?  
Answer here: Windows 10 Creators Update.

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: cmd.exe

**Comment by jlian** [comment]
Bug.

**Comment by jlian** [comment]
Created item to fix for Oct this year https://msazure.visualstudio.com/One/_workitems/edit/4979240
