### ISSUE TITLE
Setting a bad cloud breaks your ability to set a new cloud

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#4637]
Setting clouds should not be broken when the cloud is set to an invalid version (no endpoints set)
```
 $ az cloud set -n AzureCloud
The endpoint 'management' for this cloud is not set but is used.
$ az cloud list --out json
The endpoint 'management' for this cloud is not set but is used.
```

**Comment by tjprescott** [comment]
This is no longer an issue. The set and list commands will not fail even if the cloud is invalid. Running a command with an invalid cloud results in this:

```
The endpoint 'active_directory_resource_id' for this cloud is not set but is used.
C:\Users\travi\.azure\clouds.config may be corrupt or invalid.
Resolve the error or delete this file and try again.
```

I think this is adequately resolved so I am closing this issue.
