### ISSUE TITLE
Error getting Storage Account from ID value stored in a Variable

### ISSUE THREAD

**Issue by 5nowx** [Azure/azure-cli#4643]
### Description
**Outline the issue here:**
When i try to pass the id variable of the value: "premiumDataDiskStorageAccount" from a devtest Lab, to my storage account show --id it returns: 
`az storage account show: error: argument --ids: invalid ResourceId value: '"/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/iXXXXXXXXXXXXXX/providers/Microsoft.Storage/storageAccounts/XXXXXXXXXXX"'`

this is the script part:

```
declare labstorage=$(az lab get --resource-group XXXXXXXX --name XXXXXXXXXXX --query "premiumDataDiskStorageAccount")

az storage account show --id $labstorage
```
when i enter the same storage ID directly into the line, it returns the expected values:

`az storage account show --id "/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/iXXXXXXXXXXXXXX/providers/Microsoft.Storage/storageAccounts/XXXXXXXXXXX"`

Am I doing something wrong with the value declaration part?
Or when i try to re use it? 
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: Interactive Script

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
azure-cli (2.0.17)

acr (2.0.11)
acs (2.0.15)
appservice (0.1.16)
batch (3.1.3)
billing (0.1.4)
cdn (0.0.8)
cloud (2.0.7)
cognitiveservices (0.1.7)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.10)
consumption (0.1.4)
container (0.1.10)
core (2.0.16)
cosmosdb (0.1.12)
dla (0.0.11)
dls (0.0.13)
eventgrid (0.1.3)
extension (0.0.2)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.9)
iot (0.1.11)
keyvault (2.0.10)
lab (0.0.10)
monitor (0.0.9)
network (2.0.14)
nspkg (3.0.1)
profile (2.0.12)
rdbms (0.0.6)
redis (0.2.8)
resource (2.0.14)
role (2.0.11)
servicefabric (0.0.3)
sf (1.0.8)
sql (2.0.11)
storage (2.0.15)
vm (2.0.14)

**OS Version:** What OS and version are you using?  
Answer here: MacOS Sierra 10.12.6

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Bash

**Comment by derekbekoe** [comment]
When running `az lab get` include `--output tsv`.
Then you should be able to pass that id value to the next command.

json output wraps the id in quotations.

**Comment by 5nowx** [comment]
Thanks @derekbekoe  , i used sed to take the quotations out and it worked, i'll try it with the output as tsv! thanks!
