### ISSUE TITLE
KeyError exception when deleting resource

### ISSUE THREAD

**Issue by k-popov** [Azure/azure-cli#4653]
### Description

When deleting resource via CLI like:
`az resource delete --debug --resource-group <some-group> --name <some-vm-name> --resource-type Microsoft.Compute/virtualMachines`
the following output is seen (stripped):
```
. . .
msrest.http_logger : Request method: 'DELETE'
. . .
msrest.http_logger : Response status: 202
. . .
msrest.http_logger : Response content:
msrest.http_logger : b''
'subscription'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/application.py", line 212, in execute
    result = expanded_arg.func(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 377, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 620, in _execute_command
    reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 602, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 567, in delete_resource
    logger.debug("deleting", resource_dict_to_id(**id_dict))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 126, in resource_id
    rid = '/subscriptions/{subscription}'.format(**kwargs)
KeyError: 'subscription'
```
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)
apt-get

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
$ az --version
azure-cli (2.0.19)

acr (2.0.13)
acs (2.0.17)
appservice (0.1.18)
backup (1.0.1)
batch (3.1.5)
batchai (0.1.1)
billing (0.1.5)
cdn (0.0.9)
cloud (2.0.8)
cognitiveservices (0.1.8)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.11)
consumption (0.1.5)
container (0.1.11)
core (2.0.18)
cosmosdb (0.1.13)
dla (0.0.12)
dls (0.0.15)
eventgrid (0.1.4)
extension (0.0.4)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.10)
iot (0.1.12)
keyvault (2.0.12)
lab (0.0.11)
monitor (0.0.10)
network (2.0.16)
nspkg (3.0.1)
profile (2.0.14)
rdbms (0.0.7)
redis (0.2.9)
resource (2.0.16)
role (2.0.13)
servicefabric (0.0.4)
sql (2.0.13)
storage (2.0.17)
vm (2.0.16)

Python location '/opt/az/bin/python3'
Extensions directory '/home/hub/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Oct  9 2017, 22:55:40) 
[GCC 4.8.4]

Legal docs and information: aka.ms/AzureCliLegal

**OS Version:** What OS and version are you using?  
Debian unstable

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
bash

**Comment by k-popov** [comment]
Version 2.0.18 installed from the same repository does not have this issue. Looks like regression.

**Comment by yugangw-msft** [comment]
@williexu , could you please take a look and prioritize the fix?

**Comment by williexu** [comment]
Sorry about that, should be fixed with https://github.com/Azure/azure-cli/pull/4661

**Comment by swestner** [comment]
I am still experiencing this issue on version 2.0.59
