### ISSUE TITLE
The 'component' commands will be deprecated in the future.

### ISSUE THREAD

**Issue by VeitSanner** [Azure/azure-cli#4655]
Currently, azure-cli displays a warning when `az component` is used. But there is no hint with what it is going to be replaced.
 
https://github.com/Azure/azure-cli/blob/d3737bbdf9a2bbf54a0a32cf04bd677c944cca0d/src/command_modules/azure-cli-component/azure/cli/command_modules/component/custom.py#L19-L20

If there are more details available it would be very helpful to provide the details here as well.

**Comment by troydai** [comment]
It is replaced by extensions system: https://github.com/Azure/azure-cli/tree/master/doc/extensions.

**Comment by derekbekoe** [comment]
@VeitSanner Was there a particular component you were looking to install?

**Comment by VeitSanner** [comment]
@derekbekoe I use `az component update` to update my azure-cli. And I find it a little bit strange to get the deprecation warning without any hint how to do this in future.

**Comment by derekbekoe** [comment]
To update the CLI, use the same mechanism you used to install the CLI.

A appreciate a clearer message on how to move forward would have been useful.
