### ISSUE TITLE
required options should be arguments

### ISSUE THREAD

**Issue by smoser** [Azure/azure-cli#4656]
### Description
The syntax on many commands require a group but make it an option rather than an argument.

    $ az group delete -h | tail -n 5
    Examples
        Delete a resource group.
            az group delete -n MyResourceGroup

Why isn't that?

    $ az group delete MyResourceGroup

---

### Environment summary

**Install Method:** How did you install the CLI? snap

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here: 2.0.7

**OS Version:** What OS and version are you using?  
Answer here: Ubuntu

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: bash

**Comment by troydai** [comment]
As of now, we do not support the positional argument. The positional argument can cause confusion with multiple levels of subcommand.

Thank you for the feedback.
