### ISSUE TITLE
Delete record set by name without ip address

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#4677]
### Description
` az network dns record-set a remove-record -h`

Looks like IP address should be marked as optional to delete the whole record set?

In particular, since there is not `az network dns record-set delete` command.

With the SDK, I can delete with only a record set name.

```
def remove_dns_a_record(record_set_name):
    from azure.mgmt.dns.models import (ARecord, RecordSet)
    from azure.mgmt.dns import DnsManagementClient
    credentials = ServicePrincipalCredentials(
        client_id = AUTH_CLIENTID,
        secret = AUTH_CLIENTSECRET,
        tenant = AUTH_TENANT
    )
    ncf DnsManagementClient(credentials, SUBSCRIPTION_ID).record_sets
    record_type = 'a'
    return ncf.delete(DNS_RESOURCE_GROUP, INSTANCE_DNS_ZONE, record_set_name, record_type)
```

---

### Environment summary
brew / 2.0.19 / macOS / bash

**Comment by tjprescott** [comment]
There is a `az network dns record-set {type} delete` command for each record type just to keep the commands in a logical grouping. 

Remove record is intended just as removing records from the set, but DNS team wanted it to auto-remove the record-set if the last record was removed (with an opt-out flag).  If you wanted to delete an entire record-set, you'd use the delete command.

**Comment by derekbekoe** [comment]
Hmm I missed that command.
Thanks.
