### ISSUE TITLE
az acr login crashes: "cannot import name SubprocessError"

### ISSUE THREAD

**Issue by xanthalas** [Azure/azure-cli#4678]
### Description
Successfully created a resource group using az group create ...
Successfully create a container registry in the new group using az acr create ...

When I try to login to the new registry using     az acr login --name myRegistryName 

I get the following crash:

cannot import name SubprocessError
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/application.py", line 212, in execute
    result = expanded_arg.func(params)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 377, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 620, in _execute_command
    reraise(*sys.exc_info())
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 602, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/command_modules/acr/custom.py", line 232, in acr_login
    from subprocess import PIPE, Popen, SubprocessError
ImportError: cannot import name SubprocessError

---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here: Installed using sudo yum install azure-cli

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
azure-cli (2.0.19)

acr (2.0.13)
acs (2.0.17)
appservice (0.1.18)
backup (1.0.1)
batch (3.1.5)
batchai (0.1.1)
billing (0.1.5)
cdn (0.0.9)
cloud (2.0.8)
cognitiveservices (0.1.8)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.11)
consumption (0.1.5)
container (0.1.11)
core (2.0.18)
cosmosdb (0.1.13)
dla (0.0.12)
dls (0.0.15)
eventgrid (0.1.4)
extension (0.0.4)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.10)
iot (0.1.12)
keyvault (2.0.12)
lab (0.0.11)
monitor (0.0.10)
network (2.0.16)
nspkg (3.0.1)
profile (2.0.14)
rdbms (0.0.7)
redis (0.2.9)
resource (2.0.16)
role (2.0.13)
servicefabric (0.0.4)
sql (2.0.13)
storage (2.0.17)
vm (2.0.16)

Python location '/usr/lib64/az/bin/python'
Extensions directory '/home/mike/.azure/cliextensions'

Python (Linux) 2.7.13 (default, Sep  5 2017, 08:53:59) 
[GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]

**OS Version:** What OS and version are you using?  
Answer here: Fedora 26
Kernel: x86_64 Linux 4.13.5-200.fc26.x86_64

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here: Bash

**Comment by murphye** [comment]
I have the same problem with azure-cli (2.0.19+dev.8715) on Mac. This is a dev build of Azure CLI from 10/14. Unable to use the ACR service... is there any workaround available?

cannot import name SubprocessError
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/Library/Python/2.7/site-packages/azure/cli/core/application.py", line 212, in execute
    result = expanded_arg.func(params)
  File "/Library/Python/2.7/site-packages/azure/cli/core/commands/__init__.py", line 377, in __call__
    return self.handler(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/azure/cli/core/commands/__init__.py", line 620, in _execute_command
    reraise(*sys.exc_info())
  File "/Library/Python/2.7/site-packages/azure/cli/core/commands/__init__.py", line 602, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/Library/Python/2.7/site-packages/azure/cli/command_modules/acr/custom.py", line 218, in acr_login
    from subprocess import PIPE, Popen, SubprocessError
ImportError: cannot import name SubprocessError

**Comment by murphye** [comment]
Debug output if helpful:

az acr login --name chirperRegistry --debug
Command arguments ['acr', 'login', '--name', 'chirperRegistry']
Current cloud config:
{'endpoints': {'active_directory': 'https://login.microsoftonline.com',
               'active_directory_data_lake_resource_id': 'https://datalake.azure.net/',
               'active_directory_graph_resource_id': 'https://graph.windows.net/',
               'active_directory_resource_id': 'https://management.core.windows.net/',
               'batch_resource_id': 'https://batch.core.windows.net/',
               'gallery': 'https://gallery.azure.com/',
               'management': 'https://management.core.windows.net/',
               'resource_manager': 'https://management.azure.com/',
               'sql_management': 'https://management.core.windows.net:8443/',
               'vm_image_alias_doc': 'https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json'},
 'is_active': True,
 'name': 'AzureCloud',
 'profile': 'latest',
 'suffixes': {'azure_datalake_analytics_catalog_and_job_endpoint': 'azuredatalakeanalytics.net',
              'azure_datalake_store_file_system_endpoint': 'azuredatalakestore.net',
              'keyvault_dns': '.vault.azure.net',
              'sql_server_hostname': '.database.windows.net',
              'storage_endpoint': 'core.windows.net'}}
Registered application event handler 'CommandTableParams.Loaded' at <function add_id_parameters at 0x10a7b9aa0>
Registered application event handler 'CommandTable.Loaded' at <function add_id_parameters at 0x10a7b9aa0>
Successfully loaded command table from module 'acr'.
Extensions directory: '/Users/eric/.azure/cliextensions'
Application event 'CommandTable.Loaded' with event data {'command_table': {'acr login': <azure.cli.core.commands.CliCommand object at 0x10a7ad590>}}
Application event 'CommandParser.Loaded' with event data {'parser': AzCliCommandParser(prog='az', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)}
Application event 'CommandTableParams.Loaded' with event data {'command_table': {'acr login': <azure.cli.core.commands.CliCommand object at 0x10a7ad590>}}
Application event 'CommandParser.Parsing' with event data {'argv': ['acr', 'login', '--name', 'chirperRegistry']}
Application event 'CommandParser.Parsed' with event data {'args': Namespace(_command_package='acr', _jmespath_query=None, _log_verbosity_debug=False, _log_verbosity_verbose=False, _output_format='json', _parser=AzCliCommandParser(prog='az acr login', usage=None, description='Login to a container registry through Docker.', version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True), _validators=[], command='acr login', func=<azure.cli.core.commands.CliCommand object at 0x10a7ad590>, password=None, regi [...]
cannot import name SubprocessError
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/Library/Python/2.7/site-packages/azure/cli/core/application.py", line 212, in execute
    result = expanded_arg.func(params)
  File "/Library/Python/2.7/site-packages/azure/cli/core/commands/__init__.py", line 377, in __call__
    return self.handler(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/azure/cli/core/commands/__init__.py", line 620, in _execute_command
    reraise(*sys.exc_info())
  File "/Library/Python/2.7/site-packages/azure/cli/core/commands/__init__.py", line 602, in _execute_command
    result = op(client, **kwargs) if client else op(**kwargs)
  File "/Library/Python/2.7/site-packages/azure/cli/command_modules/acr/custom.py", line 218, in acr_login
    from subprocess import PIPE, Popen, SubprocessError
ImportError: cannot import name SubprocessError

**Comment by lmazuel** [comment]
`SubprocessError` is new in Python 3.3, then not available in 2.7.. :/ 
Best workaround would be to install the CLI in Python 3 while this code is fixed to be compatible with 2.7

**Comment by murphye** [comment]
Do you have any tips for using Python 3 with azure-cli on Mac? I tried to use pyvenv and that didn't work. There is also virtualenv but that looks more invasive. I am blocked on this, unfortunately. Thanks.
