### ISSUE TITLE
commands: provide general support for tagging a resource or a group

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#468]
We can expose a global parameter for users to tag any kind of resources, or a group; or let each resource command to manually expose the support, say `vm create --tags`. Either way, we need to get this piece work.
@johanste, I think you are working on it, so i am giving this to you
/CC:@jasonrshaver

**Comment by tjprescott** [comment]
@yugangw-msft, @johanste does generic --set suffice for this?

**Comment by tjprescott** [comment]
Generic --set accomplishes this. Additionally most create and update commands have --tags parameter.
