### ISSUE TITLE
az disk create with Chinese Resource Group name get error: the Entity was not found.

### ISSUE THREAD

**Issue by vivianxing** [Azure/azure-cli#4698]
---

### Environment summary

Azure CLI latest version installed on Ubuntu 1404 or 17.04. when running a scrip:
az disk create -g 互道资源组 -n testzabbix01 --source Zabbix_OsDisk_1_f32166d63d2148c1b6b06b6c9c77603a --debug" error: the Entity was not found. 

I created a resource group with exact same name, but cannot repro this issue in my subscription. If I login with the problematic subscription, the issue happened. 

working and not working debug files are attached.
[notworkingdebug.txt](https://github.com/Azure/azure-cli/files/1394052/notworkingdebug.txt)
[workingdebug.txt](https://github.com/Azure/azure-cli/files/1394054/workingdebug.txt)

Would you help check?

**Comment by troydai** [comment]
Thanks for reporting. We will look into this. By the way, @vivianxing are you able to create a resource group and reference it through the port?

**Comment by vivianxing** [comment]
Hi Troy,

Thank you for helping.

I am not sure what you mean by “are you able to create a resource group and reference it through the port”? what are the steps to do it?

I already created a Resource Group with the same name as customer’s in my subscription, but the issue does not happen. It only happens in customer’s subscription.

Thank you.

Regards,
Vivian

**Comment by troydai** [comment]
Sorry for my typo, I meant could you create a resource group with a name in Chinese from the *portal*. What I'm trying to determine if that if Azure service support resource group or the other resources with names containing characters other than ASCII.

**Comment by troydai** [comment]
In short, can you accomplish the same operations through portal?

**Comment by vivianxing** [comment]
hi Troy, 

First, I would like to explain that this CLI command will create a managed disk name "testzabbix01" in Resource Group "互道资源组“ from a source disk. that means this resource group already exists. yes, I can create a resource group with exact same Chinese name from portal without any problem. 

However, for the operations this CLI command will do, it cannot accomplish from Portal. However, PowerShell command works. Only CLI has problem. 

Hope it helps. 

Thank you.

**Comment by vivianxing** [comment]
hi 
issue resolved by add a --location Chinanorth
so, may I know if cli will choose chinaeast as default location if we did not indicate it?

Thank you.

**Comment by troydai** [comment]
You can configure the default resource group through `az configure` command, otherwise, most CLI commands won't decide what resource group to be used.

**Comment by yonzhan** [comment]
issue triaged

**Comment by qwordy** [comment]
I test the following commands. There is no error. Could you share the complete sequence of commands you run?
```
az group create -g 呵呵 -l westus
az disk create -g 呵呵 -n disk1 --size-gb 10
az disk create -g 呵呵 -n disk2 --source disk1
```

**Comment by yungezz** [comment]
hi @vivianxing could you pls more detail of repo steps? thanks.

**Comment by qwordy** [comment]
Close the issue due to no response. You can open a new one if you still have problems.
