### ISSUE TITLE
AZ ACR list failed

### ISSUE THREAD

**Issue by shizn** [Azure/azure-cli#4699]
in cmd
![image](https://user-images.githubusercontent.com/3619378/31710917-059b1466-b429-11e7-94fb-70d11fe28408.png)

in cloud shell (you can see I've provisioned a acr already)
![image](https://user-images.githubusercontent.com/3619378/31710941-1b5156f8-b429-11e7-94c0-61242fd090bc.png)

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

MSI intall

azure-cli (2.0.17)

acr (2.0.11)
acs (2.0.15)
appservice (0.1.16)
batch (3.1.3)
billing (0.1.4)
cdn (0.0.8)
cloud (2.0.7)
cognitiveservices (0.1.7)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.10)
consumption (0.1.4)
container (0.1.10)
core (2.0.16)
cosmosdb (0.1.12)
dla (0.0.11)
dls (0.0.13)
eventgrid (0.1.3)
extension (0.0.2)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.9)
iot (0.1.11)
keyvault (2.0.10)
lab (0.0.10)
monitor (0.0.9)
network (2.0.14)
nspkg (3.0.1)
profile (2.0.12)
rdbms (0.0.6)
redis (0.2.8)
resource (2.0.14)
role (2.0.11)
servicefabric (0.0.3)
sf (1.0.8)
sql (2.0.11)
storage (2.0.15)
vm (2.0.14)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\xshi\.azure\cliextensions'

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

```
```

**Comment by shizn** [comment]
@shiweiz

**Comment by shiweiz** [comment]
For me,
```
> az acr login -n shizhacr
Incorrect function.
```

**Comment by djyou** [comment]
@shizn Can you please check if you are in the right subscription that has your registry?

**Comment by djyou** [comment]
@shiweiz Your issue is unrelated. Do you mind opening a new issue if you want to track it here? And please put an environment summary to help root cause it. Thanks.

**Comment by shiweiz** [comment]
@djyou New issue #4715 is opened for my case.

**Comment by shizn** [comment]
Solved. Thanks.
