### ISSUE TITLE
VM encryption across resource groups does not work

### ISSUE THREAD

**Issue by abramz** [Azure/azure-cli#4707]
### Environment summary

Install Method homebrew / 2.0.19 / macOS 10.12.6 / zsh

I am attempting to add encryption to existing VMs. I have had no troubles when the VM & the key vault are in the same resource group. However, when I try to use the key vault to encrypt VMs outside of its resource group, the request fails. 

Call:
```
az vm encryption enable \
  --resource-group my-rg \
  --name my-vm \
  --aad-client-id my-sp-id \
  --aad-client-secret my-sp-secret \
  --disk-encryption-keyvault /subscriptions/my-sub/resourceGroups/my-other-rg/providers/Microsoft.KeyVault/vaults/my-vault \
  --key-encryption-key my-key \
  --volume-type all
```

Result:
```
Key Vault https://my-vault.vault.azure.net/keys/my-key either has not been enabled for Volume Encryption or the vault id provided does not match /subscriptions/my-sub/resourceGroups/my-rg/providers/Microsoft.KeyVault/vaults/my-other-rgs-vault-name's true resource id.
```

This does not make sense to me. I put the full resource ID to the key vault in my request but the error is talking about the URL to my key vault not matching a non-existant key vault in the VM's resource group.

**Comment by abramz** [comment]
nevermind

**Comment by psinger** [comment]
Having the same issue, did you figure it out?

**Comment by abramz** [comment]
@psinger sorry, I tried running it a day later on a different VM (still different rg than key vault) and it worked so I assume  I had a typo. I made a whole new service principal and key vault so it might have been a typo there too.

If you are using Linux vms, check to make sure they fit the prerequisites, VMs you have installed stuff on are not supported.
