### ISSUE TITLE
Eliminate azure stack specific tests.

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#4711]

**Comment by yonzhan** [comment]
@Juliehzl  add to S162.

**Comment by Juliehzl** [comment]
Hi @troydai, can you provide infomation for your issue?

**Comment by troydai** [comment]
I fired this bug more than two years ago when I was on the CLI team. I have since then left the team and Microsoft. I don’t have much context now. If it is not a problem for the project now, I suggest you close this issue.

**Comment by Juliehzl** [comment]
Thanks for your information. We already have tests targeting to different profiles and I will close this issue now. If you have any other problems, feel free to create a new issue. 😊
