### ISSUE TITLE
CLI Error - The access token expiry UTC time

### ISSUE THREAD

**Issue by neilpeterson** [Azure/azure-cli#4722]
I am receiving this error when running most CLI commands.

```
The access token expiry UTC time '10/19/2017 7:45:39 PM' is earlier than current UTC time '10/19/2017 11:04:07 PM'.
```
---

### Environment summary

Environment - Mac
Installation Method - Brew
Version - `azure-cli (2.0.19)`

### Attempted Fix 

Brew upgrade and Brew force uninstall and re-install

**Comment by neilpeterson** [comment]
Additional note - this appears to only occur on subscriptions associated with my MSFT account. My external subscription works fine.

**Comment by troydai** [comment]
@yugangw-msft

**Comment by neilpeterson** [comment]
@yugangw-msft any thoughts or updates on this?

**Comment by yugangw-msft** [comment]
@neilpeterson, currently there is really no way for me to confirm the root cause be that Cloud Shell didn't update CLI's credential cache with valid access tokens.
Can you try out tomorrow when cloud shell will integrate a new version of CLI with the change I made to dump out host information for me to cross check the service traces?
What you need to do is 
1. Close and reopen the shell
2. Retry 
3. Paste the new error message here, which should look like  `A Cloud Shell credential problem occurred. When you report the issue with the error below, please mention the hostname...`

**Comment by yugangw-msft** [comment]
Hmm, sorry @neilpeterson, I guess I might get confused with another issue which was only repro'd inside Cloud Shell and the same error was quoted
If it is not your case, can you run `az account clear` and then `az login` to see whether you get the same problem?

**Comment by neilpeterson** [comment]
@yugangw-msft - that seems to have cleared it up. The issue has been intermittent, but definitely chronic. I had completely removed the CLI and reinstalled. Perhaps, the uninstallation does not remove cached creds / account.

I will close, if it creeps back up I will re-open.

Thanks

**Comment by LaurentLesle** [comment]
@neilpeterson I would like to re-open that ticket. I am experimenting the same issue when I am running the azure cli from a docker container and mapping my local ~/.azure folder to access the cache from the container.

My local azure-cli and in the container are running the same version of azure cli 2.0.74. I even tried older versions but same issue from the container. Looks like the access token is not refreshed.

To reproduce the problem (mac os or W10 wsl2):

- Make sure you have an active azure login session on your local machine and set a default subscription
```bash
docker run -it --rm -v ${HOME}/.azure:/root/.azure mcr.microsoft.com/azure-cli
```
- from the docker container confirm you can see your azure session with "az account show"
- execute the command "az resource list". If it works, then wait for 1 hour and retry.
- you get the error message: 
![image](https://user-images.githubusercontent.com/4702224/66714194-57095080-ede6-11e9-9a04-e4b659816680.png)

The immediate workaround is to perform an az logout and az login then I can use the cli from docker until the access token expires.

**Comment by rahulroshan96** [comment]
> Hmm, sorry @neilpeterson, I guess I might get confused with another on-going issue which was only repro'd inside Cloud Shell and the same error was quoted to me.
> If it is not your case, can you run `az account clear` and then `az login` to see whether you get the same problem?

Worked for me.

**Comment by lostmygithubaccount** [comment]
I just ran into this issue, running a similar Docker container setup. this worked for me:

```
az logout
az login
```

**Comment by jiasli** [comment]
@lostmygithubaccount, are you mapping `~/.azure` to the container? 

ADAL can refresh the access token when is expires. (+@rayluo) Could you check if the time of your container is correctly set up?

**Comment by lostmygithubaccount** [comment]
I am, I have:

`-v /Users/cody/.azure:/users/cody/.azure`

in my `docker run` command

**Comment by jiasli** [comment]
Could you check if the time of your container is correctly set up? The timezone must also be correct.
