### ISSUE TITLE
Individual PyPi packages are missing LICENSE.txt file

### ISSUE THREAD

**Issue by glaubitz** [Azure/azure-cli#4724]
While packaging the Azure CLI utilities for openSUSE, we noticed that the individual packages on PyPi.org (e.g. ```azure-cli-acr```) are missing their LICENSE.txt files. Only the ```azure-cli``` package itself includes this file.

Since each PyPi package is packaged as an individual RPM distribution package in openSUSE and every RPM package needs to include a license or a copyright file, this would be considered a packaging bug.

To mitigate the issue in openSUSE, I have just copied the LICENSE.txt from the ```azure-cli``` package into the packaging sources of every individual component package. However, it would be great if this issue could be fixed upstream so that other distributions like Debian don't run into this particular issue either.

Since both ```azure-cli``` and the individual component packages on PyPi are generated from the same, single source tree, I would advise to just copy the LICENSE.txt into the source directory of each PyPi package before generating the tarball. This avoids redundant copies of the LICENSE.txt file in the original source tree for Azure CLI.

**Comment by derekbekoe** [comment]
Hi
We no longer produce that tarball that was mentioned and now also provide a `.rpm` package officially.

**Comment by glaubitz** [comment]
I'm not sure whether this addresses the original issue which is that the individual component packages available on PyPy are missing their LICENSE files.

See, for example, azure-cli-find. If you download the tarball from [1], it does not contain a license file.

> [1] https://pypi.org/project/azure-cli-find/#files

**Comment by yonzhan** [comment]
issue triaged.

**Comment by fengzhou-msft** [comment]
Individual component packages are deprecated from azure-cli 2.0.68 (July 2, 2019) when they are all consolidated into one single `azure-cli` package. They will no longer be updated. Please use the `azure-cli` RPM package on openSUSE. Thanks.
