### ISSUE TITLE
Existing SSH key is overwritten

### ISSUE THREAD

**Issue by ghost** [Azure/azure-cli#4725]
When running `az vm create --generate-ssh-keys`: When this option is called, and a private key exists in `~/.ssh/id_rsa`, but there is not a public key in `~/.ssh/id_rsa.pub`, the existing private key is overwritten by generation of a new key pair. Correct behavior is to derive a public key from the private key using `ssh-keygen -y`.

**Comment by troydai** [comment]
@yugangw-msft

**Comment by troydai** [comment]
I think the overwritten is particularly bad.

**Comment by yugangw-msft** [comment]
Let me see how much we can do here.
