### ISSUE TITLE
Add ETA data for upload/downloads

### ISSUE THREAD

**Issue by tylerauerbeck** [Azure/azure-cli#4744]
We've recently been working with uploading a number of images to azure. Depending on the size of these, some of them can take a considerable amount of time to push. It would be nice to have some sort of ETA running alongside the upload that tells you the percentage it's at as well as an estimated time to completion. I know this functionality is there when we take the same type of actions through the storage explorer, so I believe it would be useful to replicate that behavior from the CLI.

Is this already functionality that is available in the CLI? If so, I may just be missing something.

**Comment by tjprescott** [comment]
Are you referring to the storage commands or something else?

**Comment by tylerauerbeck** [comment]
@tjprescott Sorry I should have been more specific. Yes I'm thinking specifically about the storage commands (i.e. az storage blob upload ... etc)

**Comment by tjprescott** [comment]
There used to be a % indicator for upload/download (which granted is not an ETA).  Do you still see that?  It may be you need to supply --verbose to see that, as, by default (and design) the CLI is quiet.

**Comment by pjmeyer** [comment]
@tjprescott I tried this today on az cli installed via docker: azure-cli (2.0.20), storage (2.0.18).

No % indicator was displayed when running `az storage blob upload-batch`, even when `--verbose` or `--debug` switches were added.

**Comment by tjprescott** [comment]
Ah, upload-batch does not have this I believe. @troydai can confirm.  Only the regular upload/download commands have this.

**Comment by troydai** [comment]
Yes. `az storage blob upload-batch` doesn't have a percentage indicator. It does print what file is being uploaded to the stderr.

**Comment by williexu** [comment]
https://github.com/Azure/azure-cli/pull/4820 will add progress-reporting to the `blob upload-batch` command.
