### ISSUE TITLE
`az storage blob copy start-batch` with `--source-uri` gives error

### ISSUE THREAD

**Issue by williexu** [Azure/azure-cli#4749]
---
I am using the following command:
`az storage blob copy start-batch --destination-container wilxcontainer --pattern * --source-uri "https://wilxstorage.blob.core.windows.net/wilxcontainer2"`

Throws the following:
`az storage blob copy start-batch: error: invalid usage: supply only one of the following argument sets:`
        `   --source-uri`
        `OR --source-container`
        `OR --source-container --source-account-name --source-account-key`
        `OR --source-container --source-account-name --source-sas`
        `OR --source-share --source-account-name --source-account-key`
        `OR --source-share --source-account-name --source-account-sas`

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

dev_setup()
```
```

**Comment by Calvin-Yuhui-Liu** [comment]
FYI. I'm working with azure-cli (2.0.45) and it works for me. In my case, I tried to copy bunch of zip files from file share in on storage account to a blob container in another storage account. the trick is that you just need to pass the --source-share parameter with the share name -- not the full uri, and pass --pattern parameter with <path/*.zip>. Everything will be fine.
