### ISSUE TITLE
`az storage blob upload-batch`: cannot upload directories to $root container

### ISSUE THREAD

**Issue by sethdeckard** [Azure/azure-cli#4752]
---

### Environment summary

OS: macOS 10.13
CLI version: 2.0.20 via Homebrew
Shell: zsh 

```
```

I'm attempting to upload a directory with sub directories to the [root container](https://docs.microsoft.com/en-us/rest/api/storageservices/working-with-the-root-container) using this syntax:

`az storage blob upload-batch -d 'https://MY_STORAGE_ACCOUNT.blob.core.windows.net/$root' -s build`

I get the following error when it attempts to upload the first sub directory and the command fails:

`The requested URI does not represent any resource on the server.`

I have tried using other syntax variants such as the one below and I get the same error:

`az storage blob upload-batch -d '$root' -s build --account-name MY_STORAGE_ACCOUNT`

**Comment by williexu** [comment]
Did you create the root container first?
Try:
`az storage container create -n $root`
Before uploading your blobs.

**Comment by sethdeckard** [comment]
Yes, I had already created it through the web console before attempting to upload. I also tried deleting it and recreating it through the CLI but the result is the same.

You also have to quote $root in the shell so it doesn't try to use it as a variable: `az storage container create -n '$root'`

**Comment by williexu** [comment]
Hi Seth, according to the [docs](https://docs.microsoft.com/en-us/rest/api/storageservices/working-with-the-root-container), "A blob in the root container cannot include a forward slash (/) in its name." Thus, `upload-batch` will only upload the files on the first level as blobs in subdirectories have names that include their path from the container.

If you want to batch upload files recursively, a non-root container must be used. Sorry for the trouble and let me know if you have any questions/concerns.

**Comment by troydai** [comment]
@sethdeckard we will close this PR since the reason is given in the MSDN docs. Thank you. If you have any further concern please feel free to reopen this issue.

**Comment by troydai** [comment]
@sethdeckard we will close this PR since the reason is given in the MSDN docs. Thank you. If you have any further concern please feel free to reopen this issue.

**Comment by sethdeckard** [comment]
Thanks, that explains it. Not sure why I didn't see that, I must be blind. :-) With that limitation the root container doesn't seem very useful for hosting a static website, but that's not relevant to this issue so I'll close it, thanks again.

**Comment by derekbekoe** [comment]
@sethdeckard you can achieve this by combining the root container with non-root containers.
e.g.
```
$root/index.html
assets/style.css
assets/main.js
assets/sub_dir/example.ts
```
For example, use $root for your index file and have an 'assets' container then you can batch upload to that assets container. If you need more subdirectories under assets, the files in that container *can* use slashes ('sub_dir/example.ts' would be the file name for example).

**Comment by sagarchavan6210** [comment]
I am not able to upload directory content using `az storage file upload-batch` 
Below command is failing with mentiond issue.  What is the share_name and what value need to provide for it?
`az storage file upload-batch --destination <Container-URL> --source <directory-name> --account-name <storage-account-name> --account-key <storage-account-key>`
uploading <directory-path>\<file-name>
**share_name should not be None.**

**Comment by williexu** [comment]
https://docs.microsoft.com/en-us/azure/storage/common/storage-azure-cli#create-and-manage-file-shares
Containers are used for blob storage.
To use `storage file` commands create a fileshare first.
