### ISSUE TITLE
cannot ping Virtual IP from another node

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#4754]
hello, all!
I've deployed Corosync/Pacemaker cluster in Azure VMs.
I use Pacemaker agent for Virtual IP address (IPaddr2).
I can switchover/failover it from one node to another, but cannot ping it from the other node, while I can ping primary IP of other node.
Any ideas how to fix it?
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```
MSI, 2.0.20, Windows 10.0.17017.1000, Bash on Windows

**Comment by tjprescott** [comment]
What commands are you using?

**Comment by alexeyshishkin01** [comment]
node 'pcs-vm-01' has primary IP 10.0.0.101 and VIP 10.0.0.100:

[azureuser@pcs-vm-01 ~]$ ip address show eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:0d:3a:b7:96:36 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.101/24 brd 10.0.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.0.0.100/24 brd 10.0.0.255 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::20d:3aff:feb7:9636/64 scope link
       valid_lft forever preferred_lft forever

node pcs-vm-02 has primary IP 10.0.0.102:

[azureuser@pcs-vm-02 ~]$ ip address show eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:0d:3a:b0:5d:7e brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.102/24 brd 10.0.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::20d:3aff:feb0:5d7e/64 scope link
       valid_lft forever preferred_lft forever



node pcs-vm-01 can ping its own IPs and IP of pcs-vm-02:

[azureuser@pcs-vm-01 ~]$ ping -c 3 10.0.0.101
PING 10.0.0.101 (10.0.0.101) 56(84) bytes of data.
64 bytes from 10.0.0.101: icmp_seq=1 ttl=64 time=0.038 ms
64 bytes from 10.0.0.101: icmp_seq=2 ttl=64 time=0.052 ms
64 bytes from 10.0.0.101: icmp_seq=3 ttl=64 time=0.028 ms
--- 10.0.0.101 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1999ms
rtt min/avg/max/mdev = 0.028/0.039/0.052/0.011 ms

[azureuser@pcs-vm-01 ~]$ ping -c 3 10.0.0.100
PING 10.0.0.100 (10.0.0.100) 56(84) bytes of data.
64 bytes from 10.0.0.100: icmp_seq=1 ttl=64 time=0.030 ms
64 bytes from 10.0.0.100: icmp_seq=2 ttl=64 time=0.040 ms
64 bytes from 10.0.0.100: icmp_seq=3 ttl=64 time=0.034 ms
--- 10.0.0.100 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1999ms
rtt min/avg/max/mdev = 0.030/0.034/0.040/0.007 ms

[azureuser@pcs-vm-01 ~]$ ping -c 3 10.0.0.102
PING 10.0.0.102 (10.0.0.102) 56(84) bytes of data.
64 bytes from 10.0.0.102: icmp_seq=1 ttl=64 time=0.821 ms
64 bytes from 10.0.0.102: icmp_seq=2 ttl=64 time=0.424 ms
64 bytes from 10.0.0.102: icmp_seq=3 ttl=64 time=0.571 ms
--- 10.0.0.102 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2001ms
rtt min/avg/max/mdev = 0.424/0.605/0.821/0.165 ms



node pcs-vm-02 cannot ping VIP address which is currently attached to pcs-vm-01, but can ping primary IPs of both nodes:

[azureuser@pcs-vm-02 ~]$ ping -c 3 10.0.0.100
PING 10.0.0.100 (10.0.0.100) 56(84) bytes of data.
From 10.0.0.102 icmp_seq=1 Destination Host Unreachable
From 10.0.0.102 icmp_seq=2 Destination Host Unreachable
From 10.0.0.102 icmp_seq=3 Destination Host Unreachable
--- 10.0.0.100 ping statistics ---
3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 1999ms
pipe 3

[azureuser@pcs-vm-02 ~]$ ping -c 3 10.0.0.101
PING 10.0.0.101 (10.0.0.101) 56(84) bytes of data.
64 bytes from 10.0.0.101: icmp_seq=1 ttl=64 time=0.441 ms
64 bytes from 10.0.0.101: icmp_seq=2 ttl=64 time=0.515 ms
64 bytes from 10.0.0.101: icmp_seq=3 ttl=64 time=0.457 ms
--- 10.0.0.101 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1999ms
rtt min/avg/max/mdev = 0.441/0.471/0.515/0.031 ms

[azureuser@pcs-vm-02 ~]$ ping -c 3 10.0.0.102
PING 10.0.0.102 (10.0.0.102) 56(84) bytes of data.
64 bytes from 10.0.0.102: icmp_seq=1 ttl=64 time=0.035 ms
64 bytes from 10.0.0.102: icmp_seq=2 ttl=64 time=0.043 ms
64 bytes from 10.0.0.102: icmp_seq=3 ttl=64 time=0.028 ms
--- 10.0.0.102 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2000ms
rtt min/avg/max/mdev = 0.028/0.035/0.043/0.007 ms

once VIP is switched-over from pcs-vm-01 to pcs-vm-02, the picture is vice versa: pcs-vm-02 can ping VIP, while pcs-vm-01 cannot

**Comment by tjprescott** [comment]
This doesn't appear to be a CLI issue. I'd recommend you try posting your question on StackOverflow with the "azure" tag. You'll have a lot more eyes on it that way.

Closing for now. If you have issues with any of the CLI commands, feel free to reopen.

**Comment by alexeyshishkin01** [comment]
ok, I'll try to contact them or http://clusterlabs.org/ guys then.
but you see the issue doesn't seem to depend on Corosync/Pacemaker - when I configure additional arbitrary IP-addresses on 'eth' interface on two hosts in the same network, they cannot ping each other
so my question has to be amended:
- if I have two VMs with IP addresses (external and internal) which can communicate to each other via internal 'eth0' interface, what is the way to configure additional IP-addresses for these two VMs?

**Comment by gaogaolulu** [comment]
I believe that it needs to create one load balancer and point it to two db nodes and your load balancer ip is the virtual ip . 
https://learn.microsoft.com/en-us/azure/load-balancer/load-balancer-floating-ip
