### ISSUE TITLE
[DNS] Support Interational Domain Names

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#4771]
Customers should be able to supply IDNs and have them converted into ASCII to be stored by AzureDNS.

**Comment by muwaqar** [comment]
This is an Azure DNS issue. Please assign to @karravi-msft.

**Comment by rohinkoul** [comment]
@tjprescott customers can use puny codes to enter IDN. Unless I am missing any context on this, please close this.

**Comment by yonzhan** [comment]
add to S165.
