### ISSUE TITLE
Can't mention vnet resource group while creating a VM in a different resource group

### ISSUE THREAD

**Issue by rathinikunj** [Azure/azure-cli#4789]
---
### Issue

1. vnet1 is present in resource-group A.
2. I create a VM in resource group B, and specified the vnet as vnet1.
3. Since vnet1 is not present in resource-group B, the CLI ends up creating vnet1 in resource-group B.
4. Both the resource-groups are in same subscription.
5. There is no way i can specify the resource-group for vnet in Azure CLI, while Azure portal populates the vnets across resource-groups and allows us to use them.

**CLI Used:**
```
az vm create --name oshiftMaster1 --resource-group nikunj2-resource-group --image RedHat:RHEL:7.3:latest -l westus --size Standard_DS4_v2 --nsg "" --public-ip-address "" --subnet hybrid-subnet-194 --vnet-name  avi-vnet-jenkins --admin-username admin1 --admin-password password1 --availability-set master-availability-set
``` 
### Environment summary

**Install Method** : `apt-get`

**CLI version** : 
```azure-cli (2.0.20)

acr (2.0.14)
acs (2.0.18)
appservice (0.1.19)
backup (1.0.2)
batch (3.1.6)
batchai (0.1.2)
billing (0.1.6)
cdn (0.0.10)
cloud (2.0.9)
cognitiveservices (0.1.9)
command-modules-nspkg (2.0.1)
component (2.0.8)
configure (2.0.12)
consumption (0.1.6)
container (0.1.12)
core (2.0.20)
cosmosdb (0.1.14)
dla (0.0.13)
dls (0.0.16)
eventgrid (0.1.5)
extension (0.0.5)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.11)
iot (0.1.13)
keyvault (2.0.13)
lab (0.0.12)
monitor (0.0.11)
network (2.0.17)
nspkg (3.0.1)
profile (2.0.15)
rdbms (0.0.8)
redis (0.2.10)
resource (2.0.17)
role (2.0.14)
servicefabric (0.0.5)
sql (2.0.14)
storage (2.0.18)
vm (2.0.17)

Python location '/opt/az/bin/python3'
Extensions directory '/home/aviuser/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Oct 18 2017, 20:41:18)
[GCC 4.8.4]

Legal docs and information: aka.ms/AzureCliLegal
```

**OS version** : `Ubuntu 14.04`
**Shell Type** : `bash`

**Comment by tjprescott** [comment]
To use a VNET in another resource group, you must specify the VNET using its fully qualified ARM ID.

**Comment by rathinikunj** [comment]
@tjprescott 

There is actually no CLI parameter to mention the resource-group for a vnet. The '--resource-group' parameter is used for creating VM, NICs etc in that resource-group. But if i want to use an existing vnet in a different resource-group for assigning IP, i cannot do that from CLI.
