### ISSUE TITLE
[Service Fabric]: az sf cluster create - template validation does not show inner error

### ISSUE THREAD

**Issue by aelij** [Azure/azure-cli#4790]
When using `az sf cluster create`, if there's an error in template validation, the error message does not contain the inner error and so isn't helpful at all (even when using `--verbose`). Examples of failure reasons (which we discovered by using the SF blade): incorrect case in cluster name; exceeded cores quota.

### Environment summary

Cloud Shell

**Comment by lawrencegripper** [comment]
Seeing this issue too, just looking  at putting together a pull request to provide the full error information. 

As a temporary workaround for other stuck you can use `--debug` and see the full json returned by the all, this includes the detailed error message.

**Comment by lawrencegripper** [comment]
Here is the result, I recurse through all the detailed errors and display each - submitting the PR now

<img width="1915" alt="newerrorazurecli" src="https://user-images.githubusercontent.com/1939288/32562399-77232f3c-c4a6-11e7-902d-67a144e2e924.png">

**Comment by peterpogorski** [comment]
This issue has been resolved. Please reopen if you experience this issue again.
