### ISSUE TITLE
RBAC: emit an actionable error when creating failed due to permission error

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#4795]
The error should contains the link to the document: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal

(The long term solution should ensure the permission gets configured when the role assignment gets created, or at least we should detect and tell users so)

**Comment by yugangw-msft** [comment]
Involved commands are `az ad sp create-for-rbac` and `az acs create`

**Comment by tjprescott** [comment]
Wasn't this fixed?

**Comment by yugangw-msft** [comment]
yes
