### ISSUE TITLE
VM: captured managed images don't contain the plan information

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#4796]
Market-place images exposed through image APIs contain the plan information like publisher, product, etc. CLI commands are able to retrieve and plumb them to the VM/VMSS creating; however, if they further capture a custom image from the vm, the plan information is not propagated to the image. 
Missing it makes it hard for CLI users to create new VMs from the custom image. 
For now, CLI works around it by exposing new arguments for users to supply the value. #4783

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
