### ISSUE TITLE
azure acs kubernetes get-credentials Permission denied

### ISSUE THREAD

**Issue by IbraheemAlSaady** [Azure/azure-cli#4799]
I'm trying to get the credentials like this
`az acs kubernetes get-credentials -g=<my_resource_group> -n=<my_cluster_name>` and it's throwing this

![image](https://user-images.githubusercontent.com/14288490/32268045-0b743ffc-bef6-11e7-9890-a281945d7cda.png)

I'm using this version 
```
azure-cli (2.0.20)

acr (2.0.14)
acs (2.0.18)
appservice (0.1.19)
backup (1.0.2)
batch (3.1.6)
batchai (0.1.2)
billing (0.1.6)
cdn (0.0.10)
cloud (2.0.9)
cognitiveservices (0.1.9)
command-modules-nspkg (2.0.1)
component (2.0.8)
configure (2.0.12)
consumption (0.1.6)
container (0.1.12)
core (2.0.20)
cosmosdb (0.1.14)
dla (0.0.13)
dls (0.0.16)
eventgrid (0.1.5)
extension (0.0.5)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.11)
iot (0.1.13)
keyvault (2.0.13)
lab (0.0.12)
monitor (0.0.11)
network (2.0.17)
nspkg (3.0.1)
profile (2.0.15)
rdbms (0.0.8)
redis (0.2.10)
resource (2.0.17)
role (2.0.14)
servicefabric (0.0.5)
sql (2.0.14)
storage (2.0.18)
vm (2.0.17)

Python location '/usr/local/opt/python3/bin/python3.6'
Extensions directory '/Users/ibraheemal-saady/.azure/cliextensions'

Python (Darwin) 3.6.3 (default, Oct 29 2017, 09:59:18)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]

Legal docs and information: aka.ms/AzureCliLegal
```

any idea what's going on?

**Comment by vshantharaj** [comment]
similar issue

**Comment by derekbekoe** [comment]
This looks similar to https://github.com/Azure/azure-cli/issues/4746 but this is not on Windows.
cc: @mboersma @yugangw-msft

**Comment by derekbekoe** [comment]
@IbraheemAlSaady We've had a few related issues so any other details would be useful.
https://github.com/Azure/azure-cli/issues?q=is%3Aissue+paramiko+is%3Aclosed

Is the key encrypted?

**Comment by vshantharaj** [comment]
ah.. figured out my issue..  i had to pass my ssh key file path... --ssh-key-file

**Comment by IbraheemAlSaady** [comment]
@derekbekoe I generated the cluster with the '--generate-ssh-key' flag, it was working when it was generated, but later when I'm trying to get credentials, I'm having the error above. The thing I did is that I reduced the VM count to 2 instead of 3 from the portal. Also my credit was due but I renewed. I assume that's not related but that's all what I did during the time I had the cluster. Hope it helps

**Comment by IbraheemAlSaady** [comment]
@vshantharaj I tried that but didn't work too, I still get the same error

**Comment by vshantharaj** [comment]
Did u try running as root...?

And ensure you use the same key which u used for creating the cluster...

**Comment by IbraheemAlSaady** [comment]
@vshantharaj yeah, didn't work.
It's frustrating, luckily it's a staging cluster, so I guess I'll just remove it and create another one , but if I moved to prudctuon and this happened, then it's a problem.
I hope it gets fixed

**Comment by vshantharaj** [comment]
Cool... Some stuff I tried around this...( In case you want to give it a
shot)

- update azure-cli
- reinstalled azure-cli

**Comment by IbraheemAlSaady** [comment]
Oh I did reinstall it twice haha, thanks for the help though, much appreciated.

**Comment by viinhpham** [comment]
The same issue here. And still don't know how to resolve

**Comment by yugangw-msft** [comment]
closing as `az acs` is deprecating
