### ISSUE TITLE
mock as runtime dependency

### ISSUE THREAD

**Issue by rjschwei** [Azure/azure-cli#4800]
Hi,

When using 

az network public-ip create --resource-group xxx --name yyy

the code attempts to load the Python mock module, this appears to be counter intuitive. At runtime, i.e. when using the tools one would expect that things actually happen rather than actions/responses being mocked. Having a dependency on mock outside of testing appears strange.

File "/usr/lib/python3.4/site-packages/azure/cli/command_modules/network/custom.py", line 8, in <module>
    import mock

and in that code:

@mock.patch('msrestazure.azure_operation.AzureOperationPoller._poll', _poll)
def _generate_vpn_profile(....

@mock.patch('msrestazure.azure_operation.AzureOperationPoller._poll', _poll)
def _generatevpnclientpackage(....

@glaubitz please follow this as well
---

### Environment summary

openSUSE Leap 42.3 azure-cli packages

```
```

**Comment by glaubitz** [comment]
I'm already subscribed.

**Comment by tjprescott** [comment]
Yes, it is strange. Everything from lines 2096-2221 (as of the moment I'm looking at it) is a workaround for a service level issue. Once the issue is fixed, the workaround will be removed (as well as the mock dependency)

**Comment by tjprescott** [comment]
https://github.com/Azure/azure-cli/issues/4392

**Comment by glaubitz** [comment]
I'm currently packaging 2.2.4 and ```mock``` is now part of the dependency list. So it seems this issue was silently fixed:

```python
DEPENDENCIES = [
    'azure-mgmt-network==2.0.0rc3',
    'azure-mgmt-trafficmanager==0.50.0',
    'azure-mgmt-dns==2.0.0rc2',
    'azure-cli-core',
    'mock'
]
```
