### ISSUE TITLE
When using az vmss create fails when adding --vm-sku

### ISSUE THREAD

**Issue by sethtregenna** [Azure/azure-cli#4801]
When using az vmss create the command fails with --vm-sku

// Working command
`az vmss create -n myapp -g rg-myapp --backend-pool-name myapp-ilbbepool --instance-count 2 --image myapp-customimage --subnet backend --vnet-name vnet-myapp --load-balancer myapp-ilb`

// Non-working command
`az vmss create -n myapp -g rg-myapp --backend-pool-name myapp-ilbbepool --instance-count 2 --image myapp-customimage --vm-sku Basic_A1 --subnet backend --vnet-name vnet-myapp --load-balancer myapp-ilb`

This returns:

```
Deployment failed. {
  "error": {
    "code": "InvalidParameter",
    "target": "sku.tier",
    "message": "The value of parameter sku.tier is invalid."
  }
}
```

Checking the available SKUs gives (trimmed output marked)

`az vmss list-skus --resource-group rg-myapp --name myapp`
//snip
```
  {
    "capacity": {
      "defaultCapacity": 1,
      "maximum": 100,
      "minimum": 0,
      "scaleType": "Automatic"
    },
    "resourceType": "Microsoft.Compute/virtualMachineScaleSets",
    "sku": {
      "capacity": null,
      "name": "Basic_A1",
      "tier": "Basic"
    }
  },
```
//snip
---

### Environment summary

az --version
azure-cli (2.0.20)

acr (2.0.14)
acs (2.0.18)
appservice (0.1.19)
backup (1.0.2)
batch (3.1.6)
batchai (0.1.2)
billing (0.1.6)
cdn (0.0.10)
cloud (2.0.9)
cognitiveservices (0.1.9)
command-modules-nspkg (2.0.1)
component (2.0.8)
configure (2.0.12)
consumption (0.1.6)
container (0.1.12)
core (2.0.20)
cosmosdb (0.1.14)
dla (0.0.13)
dls (0.0.16)
eventgrid (0.1.5)
extension (0.0.5)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.11)
iot (0.1.13)
keyvault (2.0.13)
lab (0.0.12)
monitor (0.0.11)
network (2.0.17)
nspkg (3.0.1)
profile (2.0.15)
rdbms (0.0.8)
redis (0.2.10)
resource (2.0.17)
role (2.0.14)
servicefabric (0.0.5)
sql (2.0.14)
storage (2.0.18)
vm (2.0.17)

Python location '/opt/az/bin/python3'
Extensions directory '/home/seth/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Oct 18 2017, 20:41:18) 
[GCC 4.8.4]

# nb
I also get the same result in Cloud Shell.

**Comment by yugangw-msft** [comment]
@sethtregenna, there is a CLI bug I can fix to allow basic tiers, but based on the command you mentioned, you might likely hit a subsequent issue that azure load balancer won't support basic tier of VMs. Maybe you can share a bit more details of your work flow, say are you willing to switch to application-gateway, or can live without balancer at all.
Anyway, CLI has a bug I will fix, but at the same time I hope I can understand your context to fully unblock you.

**Comment by yugangw-msft** [comment]
//CC @tjprescott.
We should update 2 places in CLI: 
1. Do not [hard coded](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_template_builder.py#L851) `Standard` tier
2. On `Basic` tier of vm, defaults to no balancer

**Comment by sethtregenna** [comment]
@yugangw-msft Thanks for looking into it - I did subsequently find out that the basic tier isn't supported. The ILB was more important to us than reducing the VM size due to our workload so have used a Standard D1.
