### ISSUE TITLE
Bug: developer docs are broken again, scripts missing

### ISSUE THREAD

**Issue by mboersma** [Azure/azure-cli#4806]
As a developer, I would like to run linters and tests on my code before submitting a PR. That's been difficult in the azure-cli project because:
- the location of the tests script keeps changing, and now `/tools/scripts` is just gone
- the [developer doc](https://github.com/Azure/azure-cli/blob/dev/doc/configuring_your_machine.md) is continually neglected and out-of-date

I've submitted PRs #4293 and #4534 to update the docs previously, but now I'm not sure what scripts take the place of the missing ones.

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by yugangw-msft** [comment]
//cc: @troydai

**Comment by mboersma** [comment]
It looks like the underlying commands are still valid:
```
$ python -m automation.style.run --module acs  # check_style
$ python -m automation.tests.run --module acs  # run_tests
```
Are there new wrapper scripts for this, or should the dev doc be updated to use the python entrypoints directly?

**Comment by squillace** [comment]
We gotta have the dev contrib docs accurate. :-|

**Comment by troydai** [comment]
One you have dev environment setup, the `check_style` command is always available. It is not advised to run script directly.
