### ISSUE TITLE
[Extensions] `run_tests` and `check_style` scripts needs to be enhanced for extensions

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#4809]
This should be high priority given that partner teams are starting to write extensions. The lack of this makes it harder to write an extension than a module, which is not what we want to convey.

These scripts have a `--module` parameter, but that doesn't work with the extensions model.  We need to either allow module to search in the normal spot AND the extensions directory, or simply add a `--extension` argument to target the extensions directory. 

cc/ @derekbekoe, @troydai, @mayurid

**Comment by derekbekoe** [comment]
What if we just document it on the extension authoring doc page.
Something like:
```
pylint ./src/*/azext_*/ --rcfile=./pylintrc
flake8 --statistics --append-config=./.flake8 ./src/*/azext_*/
```
from https://github.com/Azure/azure-cli-extensions/blob/master/scripts/ci/test_static.sh#L5

Or, if they use `Azure/azure-cli-extensions`, there's already pylint/flake8 there.

**Comment by tjprescott** [comment]
It's more so they can run it locally on their machine.  They could run those commands, but they are easy to forget. If they already have the CLI dev_setup on their machine, it'd be nice to be able to use the scripts (especially for the tests, which the invocation can differ based on nose vs. unittest and Python 2 and 3).

Otherwise it's a barrier for extensions vs. module, which we don't want.

**Comment by yonzhan** [comment]
add to S165.

**Comment by haroldrandom** [comment]
Closed as context lost, those scripts are removed. Besides, integration test and code static check are almost the between Azure/azure-cli and Azure/azure-cli-extensions. Besides azdev now has the ability to test and check style on extensions.
