### ISSUE TITLE
az acs get-credentials results in error: Name or service not known

### ISSUE THREAD

**Issue by Teodelas** [Azure/azure-cli#4811]
Occurs in Cloud Shell, CentOS, and Bash on Windows
azure-cli (2.0.20)

**Comment by Teodelas** [comment]
Figured this out.  The certificate on the ACS cluster was incorrect.  Could there be a better error than this?  Below was the error I found on the server:
Unable to connect to the server: x509: certificate is valid for teoacs-ACS-fed7f4mgmt.eastus.cloudapp.azure.com, kuberne
tes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, kubernetes.kube-system, kubernete
s.kube-system.svc, kubernetes.kube-system.svc.cluster.local, not teoacs-acs-fed7f4mgmt.westcentralus.cloudapp.azure.com

**Comment by yugangw-msft** [comment]
closing as `az acs` is deprecating
