### ISSUE TITLE
Is there a metadata generation tool like `azure --gen` in this version?

### ISSUE THREAD

**Issue by tomasaschan** [Azure/azure-cli#4813]
In old versions of the Azure CLI, there was a flag `azure --gen` which generated JSON metadata with info about all the commands. This was really helpful for creating tab completion extensions (see e.g. https://github.com/stuartleeks/posh-azurecli).

I want to make an attempt at porting Posh-AzureCli to the the 2.x version of the CLI, but it relies on the metadata generated with `azure --gen` and I can't figure out how to extract the corresponding metadata from `az`.

Is metadata export available at all today? If not, would you consider adding it?

**Comment by yugangw-msft** [comment]
You can start with: https://github.com/Azure/azure-cli/blob/dev/scripts/dump_command_table.py

**Comment by yonzhan** [comment]
add to S165.

**Comment by jiasli** [comment]
Azure CLI 2.0 already supports auto-completion. 

As https://github.com/stuartleeks/posh-azurecli is archived, closing this issue.
