### ISSUE TITLE
Failed to create image if the disk has the same name with a vm

### ISSUE THREAD

**Issue by yuwzho** [Azure/azure-cli#4814]
---

### Environment summary
Ubuntu 16.04LTS

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
pip install azure-cli
```

I want to create an image use Azure-CLI from a given disk, but a vm in the same group has the same name with disk. Then Azure-CLI will failed to create image from disk but from vm.

## details:

My resource group `myrg` has the following resources:
* /disks/testvm001
* /virtualmachine/testvm001
* /disks/disk001

I now want to create an image with osDisk is `/disks/testvm001`, and dataDisks contains `/disks/disk001`.
So I use the following command:

```bash
az image create --source /subscriptions/XXXX/resourceGroups/myrg/providers/Microsoft.Compute/disks/testvm001 --data-disk-sources disk001--os-type Linux -g myrg -n testimage001
```

However, when it executes these lines: [vm/_validators.py#992](https://github.com/Azure/azure-cli/blob/03636bdbc4fb0e134610a4ea84f32c22766a3f73/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py#L992)

It only checks whether there is a vm with such name, then creates image from this vm, but not from disk as I want.
BTW, it finally failed since this code thinks I define a vm as source and also define the data-disk.

**Comment by yugangw-msft** [comment]
Thanks for reporting this.
