### ISSUE TITLE
[ML] Setup giving `BadRequest` error when trying to provision machine learning resource group

### ISSUE THREAD

**Issue by jwood803** [Azure/azure-cli#4822]
### Environment summary
Installed from Azure ML Workbench and run from `cmd.exe` also from Azure ML Workbench.

Versions:
- azure-cli (2.0.17)
- ml (0.1.0a25.post3)

Windows 10 Pro

### Issue
Following [this tutorial](https://blogs.technet.microsoft.com/machinelearning/2017/09/25/deploying-machine-learning-models-using-azure-machine-learning/) on deploying an Azure ML model from Workbench as a web service. As soon as I get to the `az ml setup` command, I started to get errors. At first, I needed to add more providers via the `az provider` command, but now I get the following `BadRequest` error:
```
{
            "code": "BadRequest",
            "message": "SubDeployment: OperationId=3C6888DDBAD8C49A, ProvisioningState=Failed, StatusCode=BadRequest, StatusMessage={\n  \"code\": \"BadRequest\",\n  \"message\": \"Bad Request\",\n  \"innererror\": {\n    \"diagnosticcontext\": \"8bffadf5-495a-4a2a-a7cb-caa53388de15\",\n    \"time\": \"2017-11-02T18:13:20.8332731Z\"\n  }\n}\n"
},
```
Even on the Portal it gives the same error:
![image](https://user-images.githubusercontent.com/1578160/32353477-ff68b5ce-bffb-11e7-8ad0-bc3be0259047.png)

**Comment by derekbekoe** [comment]
cc: @trangevi

**Comment by trangevi** [comment]
@jwood803 can you please share your subscription ID as well as the name of the cluster you are trying to create and the location? Additionally, was there more to the cli output? I noticed the comma at the end, so if there is more output and you could provide that, it could be helpful as well.

Thanks

**Comment by jwood803** [comment]
Sure, @trangevi!

I used this command - `az ml env setup -n slrdemo -l eastus2 -c` and under the "Visual Studio Enterprise" subscription. Is the actual subscription ID safe to post?

Here's the whole result of the `az ml show` command after the `setup` command:
```
{
  "Cluster Name": "slrdemo",
  "Cluster Size": 2,
  "Created On": "2017-11-03T15:30:59.132Z",
  "Location": "eastus2",
  "Provisioning Errors": [
    {
      "error": {
        "code": "BadRequest",
        "details": [
          {
            "code": "OK",
            "message": "SubDeployment: OperationId=5A5CE70CB8B103AF, ProvisioningState=Succeeded, StatusCode=OK, StatusMessage=\n"
          },
          {
            "code": "OK",
            "message": "SubDeployment: OperationId=A55E8E1E5A88973D, ProvisioningState=Succeeded, StatusCode=OK, StatusMessage=\n"
          },
          {
            "code": "OK",
            "message": "SubDeployment: OperationId=EDE16C6EE01B606B, ProvisioningState=Succeeded, StatusCode=OK, StatusMessage=\n"
          },
          {
            "code": "BadRequest",
            "message": "SubDeployment: OperationId=E55D92543882D708, ProvisioningState=Failed, StatusCode=BadRequest, StatusMessage={\n  \"code\": \"BadRequest\",\n  \"message\": \"Bad Request\",\n  \"innererror\": {\n    \"diagnosticcontext\": \"06d37652-c7b9-4e9c-9a24-4f354ed1aded\",\n    \"time\": \"2017-11-03T15:32:20.3683735Z\"\n  }\n}\n"
          },
          {
            "code": "OK",
            "message": "SubDeployment: OperationId=B4534DFE8E9AA2CF, ProvisioningState=Succeeded, StatusCode=OK, StatusMessage=\n"
          },
          {
            "code": "OK",
            "message": "SubDeployment: OperationId=1FAEC1E84016597C, ProvisioningState=Succeeded, StatusCode=OK, StatusMessage=\n"
          },
          {
            "code": "OK",
            "message": "SubDeployment: OperationId=00FAAE2AC3324687, ProvisioningState=Succeeded, StatusCode=OK, StatusMessage=\n"
          },
          {
            "code": "OK",
            "message": "SubDeployment: OperationId=803B8ADD8E534A60, ProvisioningState=Succeeded, StatusCode=OK, StatusMessage=\n"
          },
          {
            "code": "Conflict",
            "message": "SubDeployment: OperationId=08586918837549864004, ProvisioningState=Failed, StatusCode=Conflict, StatusMessage=Template output evaluation skipped: at least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\n"
          }
        ],
        "message": "Deployment failed with one or more errors. Please look at the inner error details"
      }
    }
  ],
  "Provisioning State": "Failed",
  "Resource Group": "slrdemorg"
}
```

**Comment by trangevi** [comment]
@jwood803 Are you using an MSDN subscription? If you are, that is the issue, as they have a spending cap which causes the app insights deployment to fail.

If you are not I'll have to investigate further.

**Comment by trangevi** [comment]
@jwood803 So the issue is that you are using the Visual Studio Enterprise subscription. Those subscriptions have a spending limit that causes our App Insights deployment to fail. The solution is to either use a subscription that doesn't have that spending limit, or to get the spending limit removed on that subscription.

**Comment by Khirkhoff** [comment]
in azure under subscriptions -> subscription -> resource providers. Do you have Microsoft.ContainerRegistry registered?

**Comment by jwood803** [comment]
@Khirkhoff Yep, it's there. :)

I think what @trangevi mentioned is probably the issue, but I'm hesitant to test since I'm not sure what charges may incur testing it out.

**Comment by mrali92** [comment]
@jwood803. I get the same issue like you. but I didn't solve it. how it's working for you. Did you use another Subscription? Can you please help me? I am stuck in this Problem for a week.

**Comment by trangevi** [comment]
@mrali92 if you are indeed having the same issue then yes, switching to a non Visual Studio Enterprise subscription would likely solve the issue, as long as the subscription that you switch to doesn't have a spending limit.

If you are not using a Visual Studio Enterprise subscription and are having environment setup issues, please provide your subscription id, environment name, and region you are attempting to setup in and I can help to figure out the issue.

**Comment by DaveVoyles** [comment]
I had the same issue, and like @trangevi  said, switching accounts and registering for Azure Container Service worked for me.

**Comment by satsch** [comment]
Hi @trangevi ,can you please tell me how to remove the spending limit, i'm using a free subscription?
Thanks in advance!

**Comment by satsch** [comment]
I needed this, thanks so much for your help @jwood803 .
