### ISSUE TITLE
az storage account update --default-action does not actually set

### ISSUE THREAD

**Issue by nneul** [Azure/azure-cli#4825]
---

### Environment summary

```
2.0.20 nightly pip on ubuntu 16.04 x64
```

Doc here: https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security?toc=%2fazure%2fstorage%2fblobs%2ftoc.json

It appears that the --default-action setting is not up networkRuleSet.defaultAction which gets changed by the portal. The other cli commands appear to work fine.

The documentation appears to be incorrect where it references 'networkAcls.defaultAction' and bypass. 

If I look at a --debug run - I don't ever actually see it issue any update either, though I may be misreading the output.

I was able to set it with an explicit --set though.

**Comment by nneul** [comment]
Looks like bypass setting is also affected.

**Comment by nneul** [comment]
Related to this - how do I use the generic update --set to set a field without it throwing away all the other elements? Or is this something broken server side?

i.e. if do `--set networkRuleSet.defaultAction=Deny` -- it takes effect, but it discards the bypass and actual rules in that same object.

**Comment by troydai** [comment]
@tjprescott can you help with the `--default-action` option? @williexu please take a look the generic set.

**Comment by tjprescott** [comment]
The issue with generic update is a bug in the CLI related to trying to leverage a crummy PATCH implementation in storage.  My PR #4853 addresses the issue, but in the future we may opt to stick with just using the PUT.
