### ISSUE TITLE
--ids should support JSON as well as space separated values

### ISSUE THREAD

**Issue by dend** [Azure/azure-cli#4829]
Using the CLI on a mac, installed through `brew`

When I run:

```
az resource delete --ids $(az resource list -g aci-builders --query "[].id" --resource-type "Microsoft.ContainerInstance/containerGroups")
```

I get:

```
az resource: error: argument --ids: invalid ResourceId value: '['
```

Which makes sense, given the output of `az resource list -g aci-builders --query "[].id" --resource-type "Microsoft.ContainerInstance/containerGroups"`, however as a user, this doesn't make sense at all - why can't the `--ids` parameter also accept a JSON array of IDs instead of a space-separated string?

**Comment by derekbekoe** [comment]
Try `-o tsv` at the end of your resource list command?

**Comment by dend** [comment]
@derekbekoe that would work, but still - seems like a much more intuitive approach would be to not have an extra parameter and instead rely directly on the set of IDs.

**Comment by derekbekoe** [comment]
@dend Okay fair point.
I have modified the issue accordingly.

**Comment by johanste** [comment]
Just to add something to the conversation, there are two things that one would have to keep in mind when implementing this:

- You have to decide how to deal with non-json output types (i.e. table)
- There are commands that return multiple ids - see `az vnet subnet list` for one example. It is probably acceptable to use the top level id - but we should think through the scenario before implementing the solution.
