### ISSUE TITLE
"az stop" doesn't actually stop VM

### ISSUE THREAD

**Issue by seanknox** [Azure/azure-cli#4833]
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
pip / OS X Sierra / zsh
```

STR:
- Stop a VM with `az vm stop`
- Try to resize a managed disk on the vm

EXPECTED:
- managed disk is resized

ACTUAL:
```
az disk update -g aks-underlay-svc --name k8s-master-18898983-1-etcddisk -z 4000

Cannot resize disk k8s-master-18898983-1-etcddisk while it is attached to running VM /subscriptions/.../resourceGroups/aks-underlay-svc /providers/Microsoft.Compute/virtualMachines/k8s-master-18898983-1.
```

This is different behavior than stopping a VM in the Portal, which appears to actually stop the machine.

**Comment by yugangw-msft** [comment]
The portal actually de-allocates the VM, rather just powers off. There is inconsistency here which I will clarify with the portal folks. At the same time, you can use`az vm deallocate`.

**Comment by derekbekoe** [comment]
Is this the same as https://github.com/Azure/azure-cli/issues/3026?

**Comment by yugangw-msft** [comment]
Let us keep on using #3026 for tracking. Closing this one...
