### ISSUE TITLE
Provider Microsoft.DBforMySQL Broken

### ISSUE THREAD

**Issue by dazdaz** [Azure/azure-cli#4842]
Azure CLI 2.0.20 executed on Ubuntu 17.04 is not reporting monitoring stats on the Azure Managed MySQL Service.

I've created a database and content, and yet it reports [] and not the result.  By using the portal, I can see that storage is consumed.

Is the REST API broken, or is my command wrong ?

$ az monitor metrics list-definitions --resource "/subscriptions/\<Subscription ID>/resourceGroups/\<Resource Group Name>/providers/Microsoft.DBforMySQL/servers/\<Name of MySQL Database>" --metric-names "cpu_percent"
[]

$ az monitor metrics list-definitions --resource "/subscriptions/\<Subscription ID>/resourceGroups/\<Resource Group Name>/providers/Microsoft.DBforMySQL/servers/\<Name of MySQL Database>" --metric-names "storage_percent"
[]

**Comment by tjprescott** [comment]
Hi @dazdaz, a few things:
- the `metrics list-definitions` command won't show you the values for metrics. That is the `metrics list` command.
- run the `metric list-definitions` command without `--metric-names` to see what metrics your resource supports. You'd need to use that name in the `list metrics` command. 
- running `metrics list-definitions` with `--metric-names` seems to have a bug. We'll take a closer look.

**Comment by tjprescott** [comment]
`--metric-names` has been removed from `metrics list-definitions` since it didn't make sense. The correct sequence is:

`az monitor metrics list-definitions --resource <resource ID>`
This gets you the correct name to use in the subsequent call:
`az monitor metrics list --resource <resource ID> --metrics <metric names>`
