### ISSUE TITLE
The test of find module should exposed the reindex error

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#4848]
```
 'unicodeescape' codec can't decode bytes in position 148-149: malformed \N character escape
```

Above is an error happens during the reindex of the find command. The error is swallowed during the test and leave the developer confused with `test_search_index` test failure. It is particularly confusing when the root of the failure is in a different command module's help documentation.

**Comment by yonzhan** [comment]
@jiasli  add to S162.

**Comment by jiasli** [comment]
`test_search_index` doesn't exist in Azure CLI anymore. Closing.
