### ISSUE TITLE
InstallAzureCli installer doesn't work in non-interactive mode

### ISSUE THREAD

**Issue by rdonkin** [Azure/azure-cli#4866]
The `InstallAzureCli` installer doesn't work except when the user can provide terminal input via a Mac/Linux tty device.    Even if you type `yes '' | bash InstallAzureCli` after downloading the script, it doesn't work because it insists on the tty device.

The use of a tty is quite unnecessary given there are no passwords or input line editing features involved here.

This is important for use with Ansible, Chef, Puppet, Docker (building your own image), etc. My application is to ensure that a server used to run Azure CLI commands can be re-provisioned entirely by Ansible.

I'm aware of the bundled installer (#3376), but that is now quite out of date (2.0.10 vs current 2.0.20) and I need a recent version of azure-cli to fix a concurrency bug with `clouds.config`.  Same applies to APT packages.

Please can you provide a command line option such as `bash InstallAzureCli --non-interactive` so that this works?  Or just enable `yes '' | bash InstallAzureCli` by reading from standard input instead of a tty?

Or alternatively, build the bundled installer for every Azure CLI release.

Many other tools such as `dpkg` provide such options.   I'm not aware of a workaround, except perhaps for running the installer under `expect` which is quite a hassle for a CLI tool.

---

### Environment summary

Install Method / OS version / Shell Type

```
InstallAzureCli installer, under Ansible, on macOS 10.11 and Ubuntu 16.04.

Azure CLI version: azure-cli (2.0.20) - and earlier versions

Using bash (or any shell)

```

**Comment by derekbekoe** [comment]
@rdonkin The script installer is designed to be interactive.

Can you use the .deb and .rpm packages we provide?
Also, you can install with pip directly with `pip install azure-cli`.

**Comment by rdonkin** [comment]
@derekbekoe That makes sense.

I hadn't realised the .deb and .rpm packages are from your own repository, so they are the latest versions - tried the .deb and that works fine, thanks!
