### ISSUE TITLE
Batch: unexpected behaviour of --select option

### ISSUE THREAD

**Issue by itowlson** [Azure/azure-cli#4870]
I ran the following command:

`az batch pool list --select id`

and it returned JSON with all the top level properties still listed but all except `id` set to null:

```
[
  {
    "allocationState": null,
    "allocationStateTransitionTime": null,
    "applicationLicenses": null,
    "applicationPackageReferences": null,
    "autoScaleEvaluationInterval": null,
    "autoScaleFormula": null,
    "autoScaleRun": null,
    "certificateReferences": null,
    "cloudServiceConfiguration": null,
    "creationTime": null,
    "currentDedicatedNodes": null,
    "currentLowPriorityNodes": null,
    "displayName": null,
    "eTag": null,
    "enableAutoScale": null,
    "enableInterNodeCommunication": null,
    "id": "pool-cpu",
    "lastModified": null,
    // more like this
```

Expected behaviour: return only the `select`-ed properties

Actual behaviour: returned all properties but un-`selected`-ones have null value

---

### Environment summary

Install method: MSI
CLI version: 

```
azure-cli (2.0.20)

...
batch (3.1.6)
...

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\itowlson\.azure\cliextensions'

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
```

Shell type: cmd.exe

**Comment by itowlson** [comment]
cc @darylmsft @matthchr

**Comment by matthchr** [comment]
@xingwu1

**Comment by xingwu1** [comment]
I don't think it is possible for JSON format since this is exactly json.dump result. Unless we convert the result to a new json object by stripping other fields of standard response.

**Comment by itowlson** [comment]
I believe the Batch API would return JSON containing only the `select`-ed fields, so it seems weird that the CLI would add the unselected fields back in with null values.  Or is it the Python SDK that adds back all the fields?  If so, it should be possible for the CLI to transform the object by selecting only the fields listed in the `--select` option (aren't Python objects treatable as maps, similar to JS objects?), or are there nasty edge cases?

I'm no longer consuming Batch CLI output, so this isn't an issue for me any longer, but I still think the behaviour is surprising - but if other people aren't having problems with it, then I'm okay if you want to close this off.

**Comment by xingwu1** [comment]
The server did only response the single field, however, Batch SDK convert the json response back to pool object, and now dump the pool object back to json with so many null fields. 

I need to ask SDK team about the behavior of other commands (if they supports select).

**Comment by bgklein** [comment]
The table format behaves as expected. The problem with JSON responses is we output the response from the Python SDK without doing any parsing.

**Comment by bgklein** [comment]
@tjprescott @bsiegel After discussing this with the team, we won't fix this functionality.  If the user wants client side filtering they can use the functionality TJ mentioned. 

The --select functionality maps to ODATA functionality which references service side attribute names rather than the Python client side attribute names.  Parsing the attribute maps for some complex objects, while maintaining/enforcing all ODATA formatting will likely not be maintainable on our end.
