### ISSUE TITLE
Better error handling when creating fileshare on account that does not support it.

### ISSUE THREAD

**Issue by williexu** [Azure/azure-cli#4872]
---
Running `az storage share create` on a ZRS storage account gives back the error: HTTPSConnectionPool.
This is not helpful at all to the user.

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by limingu** [comment]
#8161

**Comment by limingu** [comment]
The Storage api should give out more meaningful error message for such cases.
