### ISSUE TITLE
"az storage acount update" --bypass option will not accept new values

### ISSUE THREAD

**Issue by AlanSt** [Azure/azure-cli#4873]
Tried to assign the values 'Logging', 'Metrics', or 'None' and it stayed on the default of 'AzureServices'.
---

### Environment summary

Install Method 
CloudShell

OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
CloudShell

**Comment by tjprescott** [comment]
This fix will be in the upcoming release.

**Comment by derekbekoe** [comment]
This will be version 2.0.21.
