### ISSUE TITLE
"az network vnet" incomplete documentation

### ISSUE THREAD

**Issue by AlanSt** [Azure/azure-cli#4874]
The required fields (--resource-group, --vnet-name) are not listed.

This is true on a number of the sub-pages, where additional things like --name aren't listed either.
---

### Environment summary

Install Method 
CloudShell

OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
CloudShell

**Comment by tjprescott** [comment]
This is because these parameters are not required since you could optionally supply `--ids` instead.
