### ISSUE TITLE
"az network nsg rule update" does not accept asterisk as a value for source or destination prefix

### ISSUE THREAD

**Issue by OguzPastirmaci** [Azure/azure-cli#4876]
---

### Environment summary

azure-cli (2.0.20) in MacOS installed with pip.

Docs [here](https://docs.microsoft.com/en-us/cli/azure/network/nsg/rule?view=azure-cli-latest#az_network_nsg_rule_update) use asterisk in the example but I get the following error message when I try to use asterisk for `--source-address-prefixes` or `--destination-address-prefixes`.

```
az network nsg rule update --nsg-name k8s-master-79A38D6D-nsg -g oguzp-acs --name allow_kube_tls --source-address-prefixes *  --destination-address-prefixes *
```

```
Security rule /subscriptions/*******/resourceGroups/oguzp-acs/providers/Microsoft.Network/networkSecurityGroups/k8s-master-79A38D6D-nsg/securityRules/allow_kube_tls has invalid Address prefix. Value provided: $(curl
```

**Comment by derekbekoe** [comment]
Try wrapping the * in single quotes?

**Comment by OguzPastirmaci** [comment]
Both single and double quotes work. Why wouldn't it parse correctly without quotes?

**Comment by derekbekoe** [comment]
Without quotes, bash (the shell I assume you used) expands the `*`.
https://stackoverflow.com/questions/11456403/stop-shell-wildcard-character-expansion

**Comment by derekbekoe** [comment]
@tjprescott Thoughts on modifying the documentation to include the quotes?
FYI: @sptramer

**Comment by sptramer** [comment]
@derekbekoe This should definitely be fixed in documentation. Single quotes are necessary since ZSH expands splats inside double-quotes.
