### ISSUE TITLE
azure network nsg show query shows "null" when there are multiple CIDR blocks in SrcAddrPrefix

### ISSUE THREAD

**Issue by kriszentner** [Azure/azure-cli#4878]
---

### Environment summary

Install Method: Interactive Script
CLI version: 2.0.20
OS version: 14.04.5
Shell Type: Bash on Windows

Running a query such as:
```
 az network nsg show -g myresourcegroup -n mynsg -nsg --query '[defaultSecurityRules[],securityRules[]][].{Name:name,Desc:description,Access:access,Direction:direction,DestPortRange:destinationPortRange,DestAddrPrefix:destinationAddressPrefix,SrcPortRange:sourcePortRange,SrcAddrPrefix:sourceAddressPrefix}'
```
Will display "null" as the below when you put multiple CIDR blocks into the "source" in the Azure portal. This is supported and works, but doesn't seem to fare so well in displaying with the 2.0 cli. When displaying this in table format, the output is simply blank.
```
  {
    "Access": "Allow",
    "Desc": null,
    "DestAddrPrefix": "*",
    "DestPortRange": "*",
    "Direction": "Inbound",
    "Name": "myrule",
    "SrcAddrPrefix": null,
    "SrcPortRange": "*"
  },
```

**Comment by tjprescott** [comment]
If you show the NSG without the query do the address prefixes show?  If so, there is an issue with your query syntax.

If I understanding your scenario correctly, you are using the query in order to generate a table format. Is that right?

**Comment by kriszentner** [comment]
You're right, it looks to be an issue with the query. The docs on this page should probably be updated, which prompted this ticket: 
https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-manage-nsg-arm-cli

Feel free and close this issue, though I'd as to open an issue with whomever is responsible for the docs on that page.
