### ISSUE TITLE
cannot rename a group

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#4879]
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
MSI/azure-cli (2.0.20)/Microsoft Windows [Version 10.0.17035.1000]/Bash on Windows
```
```
I cannot rename a group - is there a way to dot it?

**Comment by tjprescott** [comment]
There is not.  You would have to delete that resource group and recreate it.  This is true of most (all?) Azure resources. If you deployed via an ARM template, this would be pretty easy. If not, you could try exporting your resource group, changing the name in the generated template, and redeploying it.
