### ISSUE TITLE
[Create Commands] Sub-deployment names may collide

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#488]
Deploy a LB named foo to resource group rg1 and another LB named foo to resource group rg2.  In some instances across the create commands, we make the sub-resource deployment names in the form "name-Subnet", in which case one of the deployments would fail.  We need to find the instances of this and add resource group into the deployment name

**Comment by tjprescott** [comment]
We use a random string for deployment name so these collisions don't occur.
