### ISSUE TITLE
Deploy a zip file to Azure Webapp

### ISSUE THREAD

**Issue by aminebizid** [Azure/azure-cli#4880]
Hello,
I tried these samples https://docs.microsoft.com/en-us/azure/app-service/app-service-cli-samples but i could not find how to deploy a webapp from a zip file using the cli.
I'm trying to run my VSTS builds on a UBUNTU agent and don't have MSDeploy running on it.
---

**Comment by yugangw-msft** [comment]
Addressed through #4700, to be released today.
The command signature will be `az webapp deployment source config-zip  -g <myRG> -n <myAppName>                  --src <zip file path location>`
