### ISSUE TITLE
No registered resource provider found for location 'XYZ' and API version '2015-06-01' for type 'storageAccounts/vmImages'. The supported api-versions are '2016-11-01'. The supported locations are ''. "

### ISSUE THREAD

**Issue by axelgMS** [Azure/azure-cli#4914]
Hey there,
Looks like Azure CLI doesn't provide the right API version with Classic VMImages -  'storageAccounts/vmImages'.

When deleting one through CLI, we're getting
**_No registered resource provider found for location 'eastus' and API version '2015-06-01' for type 'storageAccounts/vmImages'. The supported api-versions are '2016-11-01'. The supported locations are ''. "_**

Looking at the Manifest for "Microsoft.ClassicStorage" Resource Provider, it only accepts API version 
                    "apiVersions": [
                        "2016-11-01"

--> Can you please update your code accordingly ?

thanks

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by tjprescott** [comment]
@yugangw-msft for comment.

**Comment by axelgMS** [comment]
sorry - might be an issue from ARM side. They updated the Manifest for Microsoft.ClassicStorage and didn't include all API versions. It's being looked at from their side

**Comment by yugangw-msft** [comment]
@axelgMS, CLI is ARM only, and I don't think there is a command you can use to delete classic VM images

**Comment by axelgMS** [comment]
right - sorry for that
