### ISSUE TITLE
Dns zone creation should support private dns zones

### ISSUE THREAD

**Issue by alonisser** [Azure/azure-cli#4916]
including ZoneType, ResolutionVirtualNetworkId, RegistrationVirtualNetworkId

see [powrshell options](https://docs.microsoft.com/en-us/azure/dns/private-dns-getstarted-powershell)
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by tjprescott** [comment]
This has been implemented.

**Comment by alonisser** [comment]
In what version?

**Comment by tjprescott** [comment]
`azure-cli-network 2.0.26`
