### ISSUE TITLE
KNACK AppService Module Conversion

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#4922]
**Blocked**
- [x] test_acr_integration will be unblocked after the acr command module gets converted.
- [ ] test_webapp_backup_config and test_webapp_backup_restore are converted, but the recording will not be done till webapp team shares out the storage account which persists the webapp backup. I am working with them to migrate to our team's test storage account

**Comment by yugangw-msft** [comment]
All are done except 3 not yet converted scenario tests:

test_acr_integration will be unblocked after the acr command module gets converted.
test_webapp_backup_config and test_webapp_backup_restore are converted, but the recording will not be done till webapp team shares out the storage account which persists the webapp backup. I am working with them to migrate to our team's test storage account

**Comment by yugangw-msft** [comment]
This is no longer a knack conversion related item, so close it. 
I have opened a tracking issue #5369 for the test issues which is blocked by service side fix
