### ISSUE TITLE
KNACK Container module conversion

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#4929]
**Blocking Issues**
- Test re-recording not possible.
Looks like some storage resources are required first. It would be good to add those commands in so the re-recording can be automated.
Also, for the acr test, can that be automated as well?

**Comment by tjprescott** [comment]
See #5056

**Comment by tjprescott** [comment]
@derekbekoe please update this issue with whatever issues remain once your PR is merged.

**Comment by derekbekoe** [comment]
There weren't any blocking issues so should be good to close once the PR is merged.

**Comment by tjprescott** [comment]
So your testing issues have been resolved?

**Comment by derekbekoe** [comment]
Ah yes. Modified the issue above...
