### ISSUE TITLE
Multithreaded cloud config tests is flaky on knack branch

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#4944]

**Comment by derekbekoe** [comment]
Looks like changes from this commit were missed
https://github.com/Azure/azure-cli/commit/29983162f211ae9fd353268b6ff70161673d8fc3#diff-69bacf5348b997023cd1e8e6f475a0da

**Comment by derekbekoe** [comment]
I'll take a look at addressing them.
