### ISSUE TITLE
The command "az cloud update --profile 2017-03-09-profile" now requires all endpoints to be specified

### ISSUE THREAD

**Issue by walterov** [Azure/azure-cli#4948]
---

### Environment summary

Using Bash on WIndows and CLI on OSx used to manage tenant resources in Azure Stack

Version: azure-cli (2.0.21)

Repro steps:
1. Register an Azure Stack cloud:

az cloud register -n AzureStackUser --endpoint-resource-manager "https://managementxsomedomain.com" --suffix-storage-endpoint "storagexsomedomain.com" --suffix-keyvault-dns ".vault.somedomain.com" --endpoint-active-directory-graph-resource-id "https://graph.windows.net/"

2. Set the cloud to use

az cloud set -n AzureStackUser

3. Set the profile to use:

az cloud update --profile 2017-03-09-profile

Result after the last command:

"The following endpoints are required for the CLI to function and were not specified on the command line, in the cloud config or could not be autodetected.
Specify them on the command line or through the cloud config file:
--endpoint-resource-manager, --endpoint-active-directory, --endpoint-active-directory-resource-id, --endpoint-active-directory-graph-resource-id"

Expected:

It should work, no error given, the only way to workaround this is specifying ALL the endpoints again as it was in the 'az register' command.

```
```

**Comment by derekbekoe** [comment]
As a workaround, you should be able to do `az cloud set -n AzureStackUser --profile 2017-03-09-profile`

**Comment by derekbekoe** [comment]
The fix will be in the Jan release.
