### ISSUE TITLE
[Network] EnableHttp2 flag in Application Gateway

### ISSUE THREAD

**Issue by akshaysngupta** [Azure/azure-cli#4968]
EnableHttp2 needs to be added as a property in Application Gateway.
[Rest Api Spec](https://github.com/Azure/azure-rest-api-specs/blob/2e385816fdc99fbff09eb809e159eca464d8ec80/specification/network/resource-manager/Microsoft.Network/2017-10-01/applicationGateway.json#L1553)

**Comment by akshaysngupta** [comment]
@tjprescott This issue was opened in November, any update ?

**Comment by tjprescott** [comment]
This should be in the next release.
