### ISSUE TITLE
Show Wrong IOT Hub  Connection String for Azure China 

### ISSUE THREAD

**Issue by chenrui1988** [Azure/azure-cli#4969]
Show Wrong IOT Hub Connection String for Azure China 

I use azure cli with azure china, and find the function of showing iot hub connection string is not work right for azure china. It show the global endpoint, 

Command:
az cloud set -n AzureChinaCloud
az login
az iot hub show-connection-string --name testtot
{
  "connectionString": "HostName=testtot.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=xxxx"
}
The host name should be **testtot.azure-devices.cn**, not azure-devices.net.

---

### Environment summary
PS C:\Users\kevin> az -v
azure-cli (2.0.21)

acr (2.0.15)
acs (2.0.19)
appservice (0.1.20)
backup (1.0.3)
batch (3.1.7)
batchai (0.1.3)
billing (0.1.6)
cdn (0.0.10)
cloud (2.0.10)
cognitiveservices (0.1.9)
command-modules-nspkg (2.0.1)
component (2.0.8)
configure (2.0.12)
consumption (0.1.6)
container (0.1.13)
core (2.0.21)
cosmosdb (0.1.15)
dla (0.0.15)
dls (0.0.18)
eventgrid (0.1.5)
extension (0.0.6)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.11)
iot (0.1.14)
keyvault (2.0.14)
lab (0.0.13)
monitor (0.0.12)
network (2.0.18)
nspkg (3.0.1)
profile (2.0.15)
rdbms (0.0.9)
redis (0.2.10)
reservations (0.1.0)
resource (2.0.18)
role (2.0.14)
servicefabric (0.0.6)
sql (2.0.15)
storage (2.0.19)
vm (2.0.18)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
```

**Comment by jlian** [comment]
Similar to Azure Government. A bug.

**Comment by jlian** [comment]
Created item to fix for Oct this year https://msazure.visualstudio.com/One/_workitems/edit/4979240
