### ISSUE TITLE
az storage file copy start-batch fails with HTTPSConnectionPool

### ISSUE THREAD

**Issue by dtissen** [Azure/azure-cli#4971]
Failing to set up following az command:
```
az storage file copy start-batch --destination-share "..." --connection-string "DefaultEndpointsProtocol=https;EndpointSuffix=core.cloudapi.de;AccountName=[REPLACED];AccountKey=[REPLACED]" --source-share "int02-content" --source-account-name "int02content"
```
fails allways with "HTTPSConnectionPool" nothing elese....
---

### Environment summary

azure-cli (2.0.20)

acr (2.0.14)
acs (2.0.18)
appservice (0.1.19)
backup (1.0.2)
batch (3.1.6)
batchai (0.1.2)
billing (0.1.6)
cdn (0.0.10)
cloud (2.0.9)
cognitiveservices (0.1.9)
command-modules-nspkg (2.0.1)
component (2.0.8)
configure (2.0.12)
consumption (0.1.6)
container (0.1.12)
core (2.0.20)
cosmosdb (0.1.14)
dla (0.0.13)
dls (0.0.16)
eventgrid (0.1.5)
extension (0.0.5)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.11)
iot (0.1.13)
keyvault (2.0.13)
lab (0.0.12)
monitor (0.0.11)
network (2.0.17)
nspkg (3.0.1)
profile (2.0.15)
rdbms (0.0.8)
redis (0.2.10)
resource (2.0.17)
role (2.0.14)
servicefabric (0.0.5)
sql (2.0.14)
storage (2.0.18)
vm (2.0.17)

Python location '/opt/az/bin/python3'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Oct 18 2017, 20:41:18)
[GCC 4.8.4]

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

**Comment by troydai** [comment]
Could you append `--debug` to generate debug log and paste it here?

**Comment by dtissen** [comment]
Just pasting the last lines (with the error):

x-ms-client-request-id:3e068f96-d34c-11e7-aa02-a434d9460bfd
x-ms-date:Mon, 27 Nov 2017 08:24:24 GMT
x-ms-version:2017-04-17
/int02content/int02-content
comp:list
restype:directory
azure.multiapi.storage.v2017_04_17.common.storageclient : Client-Request-ID=3e068f96-d34c-11e7-aa02-a434d9460bfd Outgoing request: Method=GET, Path=/int02-content, Query={'restype': 'directory', 'comp': 'list', 'prefix': None, 'marker': None, 'maxresults': None, 'timeout': None, 'sharesnapshot': None}, Headers={'x-ms-version': '2017-04-17', 'User-Agent': 'Azure-Storage/0.37.0-0.36.0 (Python CPython 3.6.1; Linux 4.4.0-43-Microsoft)', 'x-ms-client-request-id': '3e068f96-d34c-11e7-aa02-a434d9460bfd', 'x-ms-date': 'Mon, 27 Nov 2017 08:24:24 GMT', 'Authorization': 'SharedKey [REPLACED]'}.
urllib3.connectionpool : Starting new HTTPS connection (4): int02content.file.core.windows.net
azure.multiapi.storage.v2017_04_17.common.storageclient : Client-Request-ID=3e068f96-d34c-11e7-aa02-a434d9460bfd Operation failed: checking if the operation should be retried. Current retry count=3, , HTTP status code=Unknown, Exception=HTTPSConnectionPool(host='int02content.file.core.windows.net', port=443): Max retries exceeded with url: /int02-content?restype=directory&comp=list (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ffed8d08320>: Failed to establish a new connection: [Errno -2] Name or service not known',)).
azure.multiapi.storage.v2017_04_17.common.storageclient : Client-Request-ID=3e068f96-d34c-11e7-aa02-a434d9460bfd Retry policy did not allow for a retry: , HTTP status code=Unknown, Exception=HTTPSConnectionPool(host='int02content.file.core.windows.net', port=443): Max retries exceeded with url: /int02-content?restype=directory&comp=list (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ffed8d08320>: Failed to establish a new connection: [Errno -2] Name or service not known',)).

HTTPSConnectionPool

**Comment by dtissen** [comment]
Looked for the connection url using the azure portal. the uri should be https://int02content.file.core.cloudapi.de/

I'm using the GermanCloud

Current cloud config:
{'endpoints': {'active_directory': 'https://login.microsoftonline.de',
               'active_directory_data_lake_resource_id': None,
               'active_directory_graph_resource_id': 'https://graph.cloudapi.de/',
               'active_directory_resource_id': 'https://management.core.cloudapi.de/',
               'batch_resource_id': 'https://batch.cloudapi.de/',
               'gallery': 'https://gallery.cloudapi.de/',
               'management': 'https://management.core.cloudapi.de/',
               'resource_manager': 'https://management.microsoftazure.de',
               'sql_management': 'https://management.core.cloudapi.de:8443/',
               'vm_image_alias_doc': 'https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json'},
 'is_active': True,
 'name': 'AzureGermanCloud',
 'profile': 'latest',
 'suffixes': {'azure_datalake_analytics_catalog_and_job_endpoint': None,
              'azure_datalake_store_file_system_endpoint': None,
              'keyvault_dns': '.vault.microsoftazure.de',
              'sql_server_hostname': '.database.cloudapi.de',
              'storage_endpoint': 'core.cloudapi.de'}}

**Comment by troydai** [comment]
@chewong

**Comment by dtissen** [comment]
Is this Issue fixed. If not, when?

**Comment by dtissen** [comment]
Still not fixed in new Version 2-0-27

**Comment by troydai** [comment]
@dtissen we're not able to repos this issue. Is it limited to the file batch copy or all storage commands?

**Comment by troydai** [comment]
Is it a cross-accounts copy operation? Are both accounts in the same cloud?

**Comment by troydai** [comment]
@dtissen we're looking into this issue now. Sorry for the delay. We're looking at fixing this in the next sprint which will release in mid-March.

**Comment by troydai** [comment]
The PR is out: https://github.com/Azure/azure-cli/pull/5669

**Comment by troydai** [comment]
Fixed in `dev` branch. Will be released in mid-March.
