### ISSUE TITLE
`az ad app` add support to append password credential 

### ISSUE THREAD

**Issue by weinong** [Azure/azure-cli#4978]
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

Please add support to add `passwordCredential` like [powershell ](https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadapplicationkeycredential?view=azureadps-2.0)has.

**Comment by yugangw-msft** [comment]
@weinong, it is already exposed at: `az ad sp reset-credentials --apend` with much better credential support including key-vault integration. Of course, we can do the same on `az ad app`, but let us know whether that unblocks you

**Comment by PacoGuy** [comment]
@yugangw-msft, I'm running into issues attempting to use the --append method that you suggest.
```
$ az ad sp reset-credentials -n <NAME> -p <mypassword> --append
az: error: unrecognized arguments: --append
```
This command is run on an Ubuntu 16.04 system with the latest azure-cli version available to apt-get (2.0.21-1).
When append is removed from the command I get the following response:
`can't find a service principal matching '<NAME>'`
This app registration I'm attempting to update was created via the `az ad app create ...` command.

**Comment by yugangw-msft** [comment]
The change will be released sometime next week. Apologize that I didn't call it out early on. 
For the value to supply to the `<NAME>` argument, use either the `appId` or one of `replyUrls` from the `app` entity. I am pasting one sample app for your quick reference
```json
{
  "appId": "3fa83063-1a36-49a7-8609-ad3ca46ed263",
  "appPermissions": null,
  "availableToOtherTenants": false,
  "displayName": "sp4615742649c902e8eb",
  "homepage": "http://sp4615742649c902e8eb",
  "identifierUris": [
    "http://sp4615742649c902e8eb"
  ],
  "objectId": "00297e72-fb1a-46ac-b41b-625599609d37",
  "objectType": "Application",
  "replyUrls": [
    "http://sp4615742649c902e8eb"
  ]
}
```

**Comment by PacoGuy** [comment]
Thanks for the update @yugangw-msft, will keep an eye out for that release

**Comment by yugangw-msft** [comment]
Released
