### ISSUE TITLE
`az aks create` and `az acs create` please remove creating subscription scoped role assignment on automatically created service principal

### ISSUE THREAD

**Issue by weinong** [Azure/azure-cli#4979]
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```
For AKS, it is not required to create any role assignment on the SPN.
For ACS, it's recommended to use resource group scope instead of subscription scope as only resource group scope is needed in ACS v1 RP and not needed in ACS v2 RP.

**Comment by yugangw-msft** [comment]
@rjtsdl, could you please handle this?

**Comment by rjtsdl** [comment]
@yugangw-msft Ack

**Comment by rjtsdl** [comment]
@weinong , For aks, we can just remove role assignment.

For acs, do you think we need to implement a different scope for role assignment. Or we can just remove it?
