### ISSUE TITLE
What's the difference between azure.cli.core.sdk.util.command() and custom_command()?

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#4989]
They look v. similar. Why not just have one?

**Comment by tjprescott** [comment]
They are very similar and I originally did conversions without it before eventually putting it back in. A few reasons:

1) the old style CommandGroup had this, so it makes it easier to convert modules that were already using this.
2) I tried this without at first and it was very annoying. You either had to have two command groups (one for SDK and one for custom) when logically they were just one, or you had to specify `command_type=foo_custom` for every custom command.

**Comment by derekbekoe** [comment]
Okay makes sense.
