### ISSUE TITLE
CloudErrors not handled as before

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#4993]

**Comment by derekbekoe** [comment]
The current released product:

![screen shot 2017-11-28 at 5 02 35 pm](https://user-images.githubusercontent.com/16448634/33352486-008514d6-d45e-11e7-823d-8ff48304f660.png)

The KnackConversion branch.

![screen shot 2017-11-28 at 5 02 41 pm](https://user-images.githubusercontent.com/16448634/33352493-06572ae8-d45e-11e7-8982-d069d8212866.png)

This *may* be specific to the `storage account create` command or it could be more general.

**Comment by tjprescott** [comment]
My guess is it is more general.

**Comment by derekbekoe** [comment]
Another slightly different example:
```
$ az eventgrid topic create -g debekoe-test1 -l westus2 -n myfirsttopic
Operation failed with status: 'Conflict'. Details: 409 Client Error: Conflict for url: https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/debekoe-test1/providers/Microsoft.EventGrid/topics/myfirsttopic?api-version=2017-09-15-preview
```

Not it shows a big stack trace.
