### ISSUE TITLE
acs get-credentials stopped working since a few days

### ISSUE THREAD

**Issue by Elexy** [Azure/azure-cli#4995]
I'm running `acs` for a few months now and since Friday my CI started complaining that it wasn't able to connect to the cluster anymore. The sequence that has worked well in the past few months is:
```
az login --service-principal -u $AZURE_USER --password $AZURE_PWD --tenant $AZURE_TENANT
az account set -s $AZURE_ACCOUNT
PROVIDER_RSG=$(getProviderResourceGroup $CIRCLE_BRANCH)
PROVIDER_CN=$(getProviderClusterName $CIRCLE_BRANCH)
az acs kubernetes get-credentials --resource-group=$PROVIDER_RSG --name=$PROVIDER_CN
```
Versions
```
azure-cli (2.0.18)

acr (2.0.12)
acs (2.0.16)
appservice (0.1.17)
backup (1.0.1)
batch (3.1.4)
billing (0.1.5)
cdn (0.0.9)
cloud (2.0.8)
cognitiveservices (0.1.8)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.11)
consumption (0.1.5)
container (0.1.11)
core (2.0.17)
cosmosdb (0.1.13)
dla (0.0.12)
dls (0.0.14)
eventgrid (0.1.4)
extension (0.0.3)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.10)
iot (0.1.12)
keyvault (2.0.11)
lab (0.0.11)
monitor (0.0.10)
network (2.0.15)
nspkg (3.0.1)
profile (2.0.13)
rdbms (0.0.7)
redis (0.2.9)
resource (2.0.15)
role (2.0.12)
servicefabric (0.0.4)
sql (2.0.12)
storage (2.0.16)
vm (2.0.15)

Python location '/opt/az/bin/python3'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Sep 23 2017, 00:13:17)
[GCC 4.8.4]
```
In my local I get this error: `/Users/elexy/.kube/config does not exist`  when it does, in fact, exist. Last friday the command: `az acs kubernetes get-credentials --resource-group=xxx --name=containerservice-xxxx` just worked. Updated my context and kubectl was ready to go.
Investigating a bit more, it seems .kube/config is not getting updated anymore.

**Comment by yugangw-msft** [comment]
@Elexy, could you please update CLI to a newer version? Once the command fails again, please share the stack trace, so that I can forward to the ACS team to take a look,

**Comment by mboersma** [comment]
@Elexy is this still happening for you with the latest 2.0.25 `az` CLI? There were some fixes that may have dealt with this.

**Comment by tjprescott** [comment]
This should be fixed in the latest release. If not, please re-open and provide the stack trace.
