### ISSUE TITLE
Event grid subscription to blob storage account fails

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#4997]
The steps outlined in [this blog post](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-event-quickstart) do not work.

```
az group create --name <resource_group_name> --location westcentralus

az storage account create \
 --name <storage_account_name> \
 --location westcentralus \
 --resource-group <resource_group_name> \
 --sku Standard_LRS \
 --kind BlobStorage \
 --access-tier Hot

az eventgrid resource event-subscription create \
--endpoint <URL_from_RequestBin> \
--name <event_subscription_name> \
--provider-namespace Microsoft.Storage \
--resource-type storageAccounts \
--resource-group <resource_group_name> \
--resource-name <storage_account_name>
```

You get the following error:
```
The attempt to configure storage notifications for the provided storage account <storage_account_name> failed. Please ensure that your storage account meets the requirements described at https://aka.ms/storageevents.
```

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
azure-cli (2.0.21)
Brew install
OS X
bash
```

**Comment by kalyanaj** [comment]
This has been resolved now.

**Comment by kalyanaj** [comment]
Can you share what region your storage account is in, and what kind of replication option you are using for your storage account?  Also, to double-check, the storage account is either a general-purpose v2 storage account or a blob storage account, right?

**Comment by eragonriddle** [comment]
@kalyanaj Thank you for pointing out to use storage account v2. `az cli storage account create` command will create a v1 general purpose account by default unless specified. Changing to general-purpose v2 storage account fixed the issue.

**Comment by kalyanaj** [comment]
Good to know that, thanks for sharing the update!

**Comment by jfggdl** [comment]
@derekbekoe, we are closing this issue for now. Feel free to reopen it if you feel that we still have not addressed your concerns.
