### ISSUE TITLE
Resource group & location completers don't work

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#4999]
Pre knack conversion they work.
Afterwards, I don't believe so.

https://github.com/Azure/azure-cli/blob/KnackConversion/src/azure-cli-core/azure/cli/core/commands/parameters.py#L61

Looks like the completer was modified to add `cli_ctx` but I think it's argparse that calls this method so cli_ctx isn't a thing.

https://github.com/Azure/azure-cli/blob/KnackConversion/src/azure-cli-core/azure/cli/core/commands/parameters.py#L172

**Comment by tjprescott** [comment]
Yes, it needs to be modified to use the @Completer decorator. In this way, you could then make the call with `cmd.cli_ctx`. I tried to do a sweep of these to update them, but since I run on CMD (and my MacBook is off in the void somewhere)....
