### ISSUE TITLE
Support VM scale set attach/detach disk to individual VMs

### ISSUE THREAD

**Issue by gbowerman** [Azure/azure-cli#5002]
CLI support needed for the new VM scale set feature: Attach/detach disks to and from individual VMs, see: [https://github.com/Azure/vm-scale-sets/tree/master/preview/disk](https://github.com/Azure/vm-scale-sets/tree/master/preview/disk).

For example, add a --vm-id parameter to the 'az vmss disk attach' (and detach) commands.

**Comment by yugangw-msft** [comment]
Suggest expose `--instance-ids` from `az vmss disk attach/detach` commands.
This depends on newer api of `2017-12-01`. Let us do it after the support of VMSS/Explicit-MSI gets in first which will brings in the same dependency.

**Comment by yugangw-msft** [comment]
Blocked by missing the PUT on the compute spec. Logged https://github.com/Azure/azure-rest-api-specs/issues/2179

**Comment by yugangw-msft** [comment]
This is done and will be released at the end of Feburary
@gatneil, the command will be `az vmss disk attach  --instance-id 1 ...`
