### ISSUE TITLE
webapp:Support deploying a certificate in Azure Key Vault to a Web App

### ISSUE THREAD

**Issue by jeremymeng** [Azure/azure-cli#5004]
Found examples on the internet that deploy a key vault certificate into a web app. But they are done either directly via the REST endpoint, or using ARM template deployment.

https://blogs.msdn.microsoft.com/appserviceteam/2016/05/24/deploying-azure-web-app-certificate-through-key-vault/

https://winterdom.com/2017/08/29/webapp-with-keyvault-cert-and-sql-token-auth

Can we do that using Azure CLI?

**Comment by gavinbarron** [comment]
Is there any action on this request? Uploading a cert for an app service from a keyvault entity is a trivial action when using the portal.

**Comment by panchagnula** [comment]
NO ETA on this for now. We will  update when we have an ETA - for now please use portal.

**Comment by gavinbarron** [comment]
I've written a script to pull the cert from keyvault to the machine executing the script and then using the existing CLI commands to upload and bind. Using the portal is not a feasible workaround for the volume of times that we're doing this.

**Comment by panchagnula** [comment]
@yutanglin16 we need come up with plan/ design for supporting this.

**Comment by slideep** [comment]
> I've written a script to pull the cert from keyvault to the machine executing the script and then using the existing CLI commands to upload and bind. Using the portal is not a feasible workaround for the volume of times that we're doing this.

@gavinbarron care to share with rest of the classroom your solution, got this far when realized this _minor_ detail...

**Comment by panchagnula** [comment]
this should be fixed by the change https://github.com/Azure/azure-cli/pull/11429

**Comment by panchagnula** [comment]
Closing since this change is now merged
