### ISSUE TITLE
delete files with 'az webapp deployment source config-zip '

### ISSUE THREAD

**Issue by aminebizid** [Azure/azure-cli#5007]
Is it possible to delete existing files in deploy folder

**Comment by ahmedelnably** [comment]
@aminebizid One way to do it is to upload an empty zip file, this will remove everything that was deployed previously

**Comment by panchagnula** [comment]
@aminebizid  also note one of the reasons for not supporting DELETE as a cli command is because 'Delete' will not remove any files that have been added during runtime i.e only the file that have been added by zip deployment will be deleted. You should see this behavior when run the zip deploy command with empty zip as Ahmed suggested above.

**Comment by panchagnula** [comment]
Closing this since this is not going to be supported, the work around to use an empty zip file is what we recommend at this time

**Comment by adamwdennis** [comment]
Why would you **not** want a deployment to remove old files that are no longer part of the deployment??  Refactoring, renaming, etc. causes big problems for subsequent deployments.  @panchagnula - why will this not be supported?

**Comment by tomlagier** [comment]
Seconding this - this seems like a massive oversight to us and has caused several production issues when a file has been moved or renamed.

Our deployment command:
```
az webapp deployment source config-zip --name ${APP_NAME} --resource-group ${RESOURCE_GROUP} --slot ${slot} --src ${LOCAL_BUILD_ARTIFACT_PATH}
```

If another deployment method is more reliable for syncing the directory then we'll use that - it seems frankly insane to me that the behavior of "deploy a directory" is not "remove existing deployed files then copy new files" a la `rsync`.
