### ISSUE TITLE
Create new security rule in range of priorities

### ISSUE THREAD

**Issue by madkroll** [Azure/azure-cli#5009]
Hi,
I see it useful to have such api call in az cli:
```
az network nsg rule create \
    --priority-lowest 1000 \
    --priority-highest 2000 \
    --name <rule-name> \
    --nsg-name <network-security-group> \
    --resource-group <resource-group>
```

As result I expect adding new security rule with priority in range of 1000 and 2000.

At the moment creating new security rule requires specifying priority level. In some situations such accuracy makes sense, but most of the time we just want to add new security rule without putting so much sense into it's priority. I believe it's a common practice that developers come up with custom scripting logic to select any available priority level - which is source of errors and is repeated in every client scripts.

Proposed approach shifts from specifying exact value of priority to providing a possibility to design different priority layers/levels and place new rules in these layers, meaning that all rules in one layer have "same" priority from business perspective.

For example:
- 100..1000 important rules
- 1000..2000 regular rules
- 2000..4096 temporary added rules

**Comment by tjprescott** [comment]
Hi @madkroll thank you for the feedback. This sounds like a reasonable suggestion and we will look at incorporating it in a future release as a CLI convenience.

**Comment by tjprescott** [comment]
We are closing this issue since it is not blocking any scenario and we've received no additional requests for this. That being said, we would be open to a PR that satisfies this ask.

**Comment by tjprescott** [comment]
Reopening this with the `help wanted` tag to make it easier for external contributors to find. If not taken up by the community within a reasonable time, we will close.

**Comment by tjprescott** [comment]
No one has shown interest in taking up this task in the past 6 months. Closing.
