### ISSUE TITLE
az vm create --admin-password question

### ISSUE THREAD

**Issue by kevi5702** [Azure/azure-cli#5013]
Is there anyway to make this variable set to type securestring for deployments?

Currently we can deploy vms from templates with the ability to set the admin password securely but using az vm create results in the password saved in plain text on deployment history.

I suppose the other option is just to use sshkeys?

**Comment by tjprescott** [comment]
VM create is based on templates, so it should just be a matter of updating the generated template to use secure string. Thanks for pointing this out!

**Comment by kevi5702** [comment]
Thanks for the quick reply @tjprescott!

Appreciate the confirmation on this one. I was racking my brain trying to think if there was a valid use case for wanting to save it plain text on templates. Every one I came up with left my spidey sense nervous. I'm a fan of defaulting to secure string and if you want plain text writing out your own template.

Random thought if you know but would this have been something we could perform with --secrets?

**Comment by tjprescott** [comment]
Mmmm...not really. Secrets go onto the VM itself, I believe. The admin password is needed to even create the VM.

**Comment by tjprescott** [comment]
We should ensure that all template-based deployments utilize securestring when appropriate.
