### ISSUE TITLE
Get cloud info from AzureStack should pass verify=False

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-cli#5018]
See https://github.com/Azure/azure-sdk-for-python/issues/1384#issuecomment-348492911

Created an issue as well in msrestazure:
https://github.com/Azure/msrestazure-for-python/issues/61

@derekbekoe maybe you should remove the CLI code and use the one from msrestazure? It's technically your code I backported. At worst, verify=False should be accessible.

**Comment by yugangw-msft** [comment]
@lmazuel, CLI is a bit different that we have more places to cover for Azure Stack and unsigned certificates in general, which I list here:

1. For ADFS, we turn off the authority validation like [here](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/_profile.py#L97) 
2. For general unsigned cert handling on the wire, we deal with ADAL's as well see [here](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/_debug.py)
3. For general certificate configuration guidelines, we have doc [here](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy)
4. For Stack specific, we also have a [doc](https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-version-profiles-azurecli2) for the users

I think, overall the support across doc and code is good to handle unsigned certs come from different contexts. 
For reading metadata endpoint, I would like use a separated work item to tracking as the information from this endpoint is still being discussed actively right now. And CLI is not using that till it is stable
