### ISSUE TITLE
az webapp list returns incorrect results

### ISSUE THREAD

**Issue by adamcrossland** [Azure/azure-cli#5020]
I have two App Service webapps under my subscription, but when I use `az webapp list` only one of them is returned. Not sure if it makes any difference, but the one that does not appear was initially created during publishing from inside Visual Studio 2015. The one that does show up was created directly in the Azure portal.

---

### Environment summary

Installed on my local machine via MSI, but I get the same results running in the Cloud Shell.

```
```

**Comment by guidozanon** [comment]
Did you make sure that both of your webapps are in the same subscription? az commands like **webapp list** will list the webapps from the current active subscription.

To list available subscriptions see
https://docs.microsoft.com/en-us/cli/azure/account?view=azure-cli-latest#az_account_list
To check current active subscription see
https://docs.microsoft.com/en-us/cli/azure/account?view=azure-cli-latest#az_account_show
To change active subscription see
https://docs.microsoft.com/en-us/cli/azure/account?view=azure-cli-latest#az_account_set

**Comment by panchagnula** [comment]
@adamcrossland please check if this still occurs for you. We recently fixed the following issue https://github.com/Azure/azure-cli/issues/4890 , that was causing the linux & function apps to not be listed.

**Comment by panchagnula** [comment]
@adamcrossland please re-activate if this is not yet fixed.
