### ISSUE TITLE
vmss create fails: issue with null name

### ISSUE THREAD

**Issue by gatneil** [Azure/azure-cli#5033]
When I run:
`az vmss create --resource-group vmsssuccess --name vmsssuccess --image UbuntuLTS --disable-overprovision --instance-count 101 --single-placement-group false --debug`,

I get the error `The request content was invalid and could not be deserialized: 'Required property 'name' expects a value but got null. Path 'properties.template.resources[2]', line 1, position 2986.'.` The same happens if I use `-g` and `-n` instead of `--resource-group` and `--name`. Here is the debug output:

Command arguments ['vmss', 'create', '--resource-group', 'vmsssuccess', '--name', 'vmsssuccess', '--image', 'UbuntuLTS', '--disable-overprovision', '--instance-count', '
101', '--single-placement-group', 'false']
Loading all installed modules as module with name 'vmss' not found.
Installed command modules ['acr', 'acs', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'cdn', 'cloud', 'cognitiveservices', 'component', 'configure', 'consumpti
on', 'container', 'cosmosdb', 'dla', 'dls', 'eventgrid', 'extension', 'feedback', 'find', 'interactive', 'iot', 'keyvault', 'lab', 'monitor', 'network', 'profile', 'rdbm
s', 'redis', 'reservations', 'resource', 'role', 'servicefabric', 'sql', 'storage', 'vm']
Current cloud config:
{'endpoints': {'active_directory': 'https://login.microsoftonline.com',
               'active_directory_data_lake_resource_id': 'https://datalake.azure.net/',
               'active_directory_graph_resource_id': 'https://graph.windows.net/',
               'active_directory_resource_id': 'https://management.core.windows.net/',
               'batch_resource_id': 'https://batch.core.windows.net/',
               'gallery': 'https://gallery.azure.com/',
               'management': 'https://management.core.windows.net/',
               'resource_manager': 'https://management.azure.com/',
               'sql_management': 'https://management.core.windows.net:8443/',
               'vm_image_alias_doc': 'https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json'},
 'is_active': True,
 'name': 'AzureCloud',
 'profile': 'latest',
 'suffixes': {'azure_datalake_analytics_catalog_and_job_endpoint': 'azuredatalakeanalytics.net',
              'azure_datalake_store_file_system_endpoint': 'azuredatalakestore.net',
              'keyvault_dns': '.vault.azure.net',
              'sql_server_hostname': '.database.windows.net',
              'storage_endpoint': 'core.windows.net'}}
Registered application event handler 'CommandTableParams.Loaded' at <function add_id_parameters at 0x7f5cfc3dc5f0>
Registered application event handler 'CommandTable.Loaded' at <function add_id_parameters at 0x7f5cfc3dc5f0>
Loaded module 'acr' in 0.006 seconds.
Loaded module 'acs' in 0.001 seconds.
Registered application event handler 'CommandParser.Parsing' at <function deprecate at 0x7f5cfc383758>
Loaded module 'appservice' in 0.002 seconds.
Loaded module 'backup' in 0.001 seconds.
Loaded module 'batch' in 0.011 seconds.
Loaded module 'batchai' in 0.001 seconds.
Loaded module 'billing' in 0.000 seconds.
Loaded module 'cdn' in 0.002 seconds.
Loaded module 'cloud' in 0.000 seconds.
Loaded module 'cognitiveservices' in 0.000 seconds.
Loaded module 'component' in 0.000 seconds.
Loaded module 'configure' in 0.000 seconds.
Loaded module 'consumption' in 0.000 seconds.
Loaded module 'container' in 0.001 seconds.
Registered application event handler 'CommandParser.Parsing' at <function deprecate at 0x7f5cfc1f6320>
Loaded module 'cosmosdb' in 0.002 seconds.
Loaded module 'dla' in 0.001 seconds.
Loaded module 'dls' in 0.001 seconds.
Loaded module 'eventgrid' in 0.001 seconds.
Loaded module 'extension' in 0.000 seconds.
Loaded module 'feedback' in 0.000 seconds.
Loaded module 'find' in 0.000 seconds.
Loaded module 'interactive' in 0.000 seconds.
Loaded module 'iot' in 0.001 seconds.
Loaded module 'keyvault' in 0.001 seconds.
Loaded module 'lab' in 0.001 seconds.
Loaded module 'monitor' in 0.002 seconds.
Loaded module 'network' in 0.009 seconds.
Loaded module 'profile' in 0.000 seconds.
Loaded module 'rdbms' in 0.001 seconds.
Loaded module 'redis' in 0.001 seconds.
Loaded module 'reservations' in 0.000 seconds.
Loaded module 'resource' in 0.002 seconds.
Loaded module 'role' in 0.001 seconds.
Loaded module 'servicefabric' in 0.000 seconds.
Loaded module 'sql' in 0.002 seconds.
Loaded module 'storage' in 0.010 seconds.
Loaded module 'vm' in 0.003 seconds.
Loaded all modules in 0.062 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: '/home/negat/.azure/cliextensions'
Application event 'CommandTable.Loaded' with event data {'command_table': {'vmss create': <azure.cli.core.commands.CliCommand object at 0x7f5cfc0cd4d0>}}
Application event 'CommandParser.Loaded' with event data {'parser': AzCliCommandParser(prog='az', usage=None, description=None, version=None, formatter_class=<class 'arg
parse.HelpFormatter'>, conflict_handler='error', add_help=True)}
Application event 'CommandTableParams.Loaded' with event data {'command_table': {'vmss create': <azure.cli.core.commands.CliCommand object at 0x7f5cfc0cd4d0>}}
Application event 'CommandParser.Parsing' with event data {'argv': ['vmss', 'create', '--resource-group', 'vmsssuccess', '--name', 'vmsssuccess', '--image', 'UbuntuLTS',
 '--disable-overprovision', '--instance-count', '101', '--single-placement-group', 'false']}
Application event 'CommandParser.Parsed' with event data {'args': Namespace(_command_package='vmss', _jmespath_query=None, _log_verbosity_debug=False, _log_verbosity_ver
bose=False, _output_format='json', _parser=AzCliCommandParser(prog='az vmss create', usage=None, description='', version=None, formatter_class=<class 'argparse.HelpForma
tter'>, conflict_handler='error', add_help=True), _validators=[<function validate_tags at 0x7f5cfc233ed8>, <function process_vmss_create_namespace at 0x7f5cfa99f938>], a
ccelerated_networking=False, admin_password= [...]
Getting management service client client_type=ResourceManagementClient
attempting to read file /home/negat/.azure/accessTokens.json as utf-8-sig
adal-python : 3eef9c41-1083-4673-8a10-f00f33fb94df - Authority:Performing instance discovery: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47
adal-python : 3eef9c41-1083-4673-8a10-f00f33fb94df - Authority:Performing static instance discovery
adal-python : 3eef9c41-1083-4673-8a10-f00f33fb94df - Authority:Authority validated via static instance discovery
adal-python : 3eef9c41-1083-4673-8a10-f00f33fb94df - TokenRequest:Getting token with client credentials.
adal-python : 3eef9c41-1083-4673-8a10-f00f33fb94df - TokenRequest:No user_id passed for cache query
adal-python : 3eef9c41-1083-4673-8a10-f00f33fb94df - OAuth2Client:finding with query: {"_clientId": "0dbd7d20-c6d9-4694-850d-36e68b797903"}
adal-python : 3eef9c41-1083-4673-8a10-f00f33fb94df - OAuth2Client:Looking for potential cache entries:
adal-python : 3eef9c41-1083-4673-8a10-f00f33fb94df - OAuth2Client:{"_clientId": "0dbd7d20-c6d9-4694-850d-36e68b797903"}
adal-python : 3eef9c41-1083-4673-8a10-f00f33fb94df - OAuth2Client:Found 0 potential entries.
urllib3.connectionpool : Starting new HTTPS connection (1): login.microsoftonline.com
urllib3.connectionpool : https://login.microsoftonline.com:443 "POST /72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token HTTP/1.1" 200 1376
adal-python : 3eef9c41-1083-4673-8a10-f00f33fb94df - OAuth2Client:Get Token Server returned this correlation_id: 3eef9c41-1083-4673-8a10-f00f33fb94df
adal-python : 3eef9c41-1083-4673-8a10-f00f33fb94df - OAuth2Client:Adding entry AccessTokenId: NSJv8kWFTdD84Ho6y1G0/MUcX7W3ZwG2P3d/77DaA0E=
adal-python : 3eef9c41-1083-4673-8a10-f00f33fb94df - OAuth2Client:Added entry is MRRT
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring proxies: ''
msrest.pipeline : Evaluate proxies against ENV settings: True
msrest.pipeline : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com
urllib3.connectionpool : https://management.azure.com:443 "GET /subscriptions/5a810961-5236-4bbd-b50a-bda258eb00c0/resourcegroups/vmsssuccess?api-version=2017-05-10 HTTP
/1.1" 200 261
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/5a810961-5236-4bbd-b50a-bda258eb00c0/resourcegroups/vmsssuccess?api-version=2017-05-10'
msrest.http_logger : Request method: 'GET'
msrest.http_logger : Request headers:
msrest.http_logger :     'Connection': 'keep-alive'
msrest.http_logger :     'Accept-Encoding': 'gzip, deflate'
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'User-Agent': 'python/2.7.12 (Linux-4.11.0-1011-azure-x86_64-with-Ubuntu-16.04-xenial) requests/2.18.4 msrest/0.4.19 msrest_azure/0.4.18 resourc
emanagementclient/1.2.1 Azure-SDK-For-Python AZURECLI/2.0.21'
msrest.http_logger :     'Authorization': '*****'
msrest.http_logger :     'x-ms-client-request-id': '3fbb7694-d92d-11e7-9f3a-000d3a30e032'
msrest.http_logger :     'CommandName': 'vmss create'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger : Request body:
msrest.http_logger : None
msrest.http_logger : Response status: 200
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Content-Encoding': 'gzip'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'Vary': 'Accept-Encoding'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-reads': '14999'
msrest.http_logger :     'x-ms-request-id': 'f8138ba0-74c3-4f08-9ac4-30a15075cbb1'
msrest.http_logger :     'x-ms-correlation-request-id': 'f8138ba0-74c3-4f08-9ac4-30a15075cbb1'
msrest.http_logger :     'x-ms-routing-request-id': 'WESTUS:20171204T195642Z:f8138ba0-74c3-4f08-9ac4-30a15075cbb1'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'Date': 'Mon, 04 Dec 2017 19:56:42 GMT'
msrest.http_logger :     'Content-Length': '261'
msrest.http_logger : Response content:
msrest.http_logger : {"id":"/subscriptions/5a810961-5236-4bbd-b50a-bda258eb00c0/resourceGroups/vmsssuccess","name":"vmsssuccess","location":"southeastasia","properties":
{"provisioningState":"Succeeded"}}
using location 'southeastasia' from resource group 'vmsssuccess'
storage profile 'StorageProfile.ManagedPirImage'
no subnet specified. Attempting to find an existing Vnet and subnet...
Getting management service client client_type=NetworkManagementClient
adal-python : 1600d093-cd1f-4a88-a93e-f47c57b33da3 - Authority:Performing instance discovery: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47
adal-python : 1600d093-cd1f-4a88-a93e-f47c57b33da3 - Authority:Performing static instance discovery
adal-python : 1600d093-cd1f-4a88-a93e-f47c57b33da3 - Authority:Authority validated via static instance discovery
adal-python : 1600d093-cd1f-4a88-a93e-f47c57b33da3 - TokenRequest:Getting token with client credentials.
adal-python : 1600d093-cd1f-4a88-a93e-f47c57b33da3 - TokenRequest:No user_id passed for cache query
adal-python : 1600d093-cd1f-4a88-a93e-f47c57b33da3 - OAuth2Client:finding with query: {"_clientId": "0dbd7d20-c6d9-4694-850d-36e68b797903"}
adal-python : 1600d093-cd1f-4a88-a93e-f47c57b33da3 - OAuth2Client:Looking for potential cache entries:
adal-python : 1600d093-cd1f-4a88-a93e-f47c57b33da3 - OAuth2Client:{"_clientId": "0dbd7d20-c6d9-4694-850d-36e68b797903"}
adal-python : 1600d093-cd1f-4a88-a93e-f47c57b33da3 - OAuth2Client:Found 0 potential entries.
urllib3.connectionpool : Starting new HTTPS connection (1): login.microsoftonline.com
urllib3.connectionpool : https://login.microsoftonline.com:443 "POST /72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token HTTP/1.1" 200 1376
adal-python : 1600d093-cd1f-4a88-a93e-f47c57b33da3 - OAuth2Client:Get Token Server returned this correlation_id: 1600d093-cd1f-4a88-a93e-f47c57b33da3
adal-python : 1600d093-cd1f-4a88-a93e-f47c57b33da3 - OAuth2Client:Adding entry AccessTokenId: uVQK0J4qsA8oIovdVsqZ28GyGTr8uIH++wWNMnWp6GE=
adal-python : 1600d093-cd1f-4a88-a93e-f47c57b33da3 - OAuth2Client:Added entry is MRRT
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring proxies: ''
msrest.pipeline : Evaluate proxies against ENV settings: True
msrest.pipeline : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com
urllib3.connectionpool : https://management.azure.com:443 "GET /subscriptions/5a810961-5236-4bbd-b50a-bda258eb00c0/resourceGroups/vmsssuccess/providers/Microsoft.Network
/virtualNetworks?api-version=2017-09-01 HTTP/1.1" 200 133
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/5a810961-5236-4bbd-b50a-bda258eb00c0/resourceGroups/vmsssuccess/providers/Microsoft.Network
/virtualNetworks?api-version=2017-09-01'
msrest.http_logger : Request method: 'GET'
msrest.http_logger : Request headers:
msrest.http_logger :     'Connection': 'keep-alive'
msrest.http_logger :     'Accept-Encoding': 'gzip, deflate'
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'User-Agent': 'python/2.7.12 (Linux-4.11.0-1011-azure-x86_64-with-Ubuntu-16.04-xenial) requests/2.18.4 msrest/0.4.19 msrest_azure/0.4.18 network
managementclient/1.5.0rc3 Azure-SDK-For-Python AZURECLI/2.0.21'
msrest.http_logger :     'Authorization': '*****'
msrest.http_logger :     'x-ms-client-request-id': '3fbb7694-d92d-11e7-9f3a-000d3a30e032'
msrest.http_logger :     'CommandName': 'vmss create'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger : Request body:
msrest.http_logger : None
msrest.http_logger : Response status: 200
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Content-Encoding': 'gzip'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'Vary': 'Accept-Encoding'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-reads': '14999'
msrest.http_logger :     'x-ms-request-id': '6ed20b14-2a27-4296-9f21-ed49b080a23d'
msrest.http_logger :     'x-ms-correlation-request-id': '6ed20b14-2a27-4296-9f21-ed49b080a23d'
msrest.http_logger :     'x-ms-routing-request-id': 'WESTUS:20171204T195643Z:6ed20b14-2a27-4296-9f21-ed49b080a23d'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'Date': 'Mon, 04 Dec 2017 19:56:43 GMT'
msrest.http_logger :     'Content-Length': '133'
msrest.http_logger : Response content:
msrest.http_logger : {"value":[]}
no suitable subnet found. One will be created.
defaulting to 'applicationGateway' because instance count <= 100
new application gateway will be created
new public IP address will be created
Use existing SSH public key file: /home/negat/.ssh/id_rsa.pub
Getting management service client client_type=ResourceManagementClient
adal-python : 030148d8-de65-44c0-bc52-d1c7d3230051 - Authority:Performing instance discovery: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47
adal-python : 030148d8-de65-44c0-bc52-d1c7d3230051 - Authority:Performing static instance discovery
adal-python : 030148d8-de65-44c0-bc52-d1c7d3230051 - Authority:Authority validated via static instance discovery
adal-python : 030148d8-de65-44c0-bc52-d1c7d3230051 - TokenRequest:Getting token with client credentials.
adal-python : 030148d8-de65-44c0-bc52-d1c7d3230051 - TokenRequest:No user_id passed for cache query
adal-python : 030148d8-de65-44c0-bc52-d1c7d3230051 - OAuth2Client:finding with query: {"_clientId": "0dbd7d20-c6d9-4694-850d-36e68b797903"}
adal-python : 030148d8-de65-44c0-bc52-d1c7d3230051 - OAuth2Client:Looking for potential cache entries:
adal-python : 030148d8-de65-44c0-bc52-d1c7d3230051 - OAuth2Client:{"_clientId": "0dbd7d20-c6d9-4694-850d-36e68b797903"}
adal-python : 030148d8-de65-44c0-bc52-d1c7d3230051 - OAuth2Client:Found 0 potential entries.
urllib3.connectionpool : Starting new HTTPS connection (1): login.microsoftonline.com
urllib3.connectionpool : https://login.microsoftonline.com:443 "POST /72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token HTTP/1.1" 200 1376
adal-python : 030148d8-de65-44c0-bc52-d1c7d3230051 - OAuth2Client:Get Token Server returned this correlation_id: 030148d8-de65-44c0-bc52-d1c7d3230051
adal-python : 030148d8-de65-44c0-bc52-d1c7d3230051 - OAuth2Client:Adding entry AccessTokenId: bMtgO7lbg6GSI4ySpBaS33vWMA+358cTpAZoHfxzGgo=
adal-python : 030148d8-de65-44c0-bc52-d1c7d3230051 - OAuth2Client:Added entry is MRRT
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring proxies: ''
msrest.pipeline : Evaluate proxies against ENV settings: True
msrest.pipeline : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com
urllib3.connectionpool : https://management.azure.com:443 "PUT /subscriptions/5a810961-5236-4bbd-b50a-bda258eb00c0/resourcegroups/vmsssuccess/providers/Microsoft.Resourc
es/deployments/vmss_deploy_FFImCgbahpGG6GyDBL1XNBSP2b298yyc?api-version=2017-05-10 HTTP/1.1" 400 239
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/5a810961-5236-4bbd-b50a-bda258eb00c0/resourcegroups/vmsssuccess/providers/Microsoft.Resourc
es/deployments/vmss_deploy_FFImCgbahpGG6GyDBL1XNBSP2b298yyc?api-version=2017-05-10'
msrest.http_logger : Request method: 'PUT'
msrest.http_logger : Request headers:
msrest.http_logger :     'Connection': 'keep-alive'
msrest.http_logger :     'Accept-Encoding': 'gzip, deflate'
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'User-Agent': 'python/2.7.12 (Linux-4.11.0-1011-azure-x86_64-with-Ubuntu-16.04-xenial) requests/2.18.4 msrest/0.4.19 msrest_azure/0.4.18 resourc
emanagementclient/1.2.1 Azure-SDK-For-Python AZURECLI/2.0.21'
msrest.http_logger :     'Authorization': '*****'
msrest.http_logger :     'x-ms-client-request-id': '3fbb7694-d92d-11e7-9f3a-000d3a30e032'
msrest.http_logger :     'CommandName': 'vmss create'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Content-Length': '4898'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger : Request body:
msrest.http_logger : {"properties": {"mode": "Incremental", "parameters": {}, "template": {"parameters": {}, "outputs": {"VMSS": {"type": "object", "value": "[reference(
resourceId('Microsoft.Compute/virtualMachineScaleSets', 'vmsssuccess'),providers('Microsoft.Compute', 'virtualMachineScaleSets').apiVersions[0])]"}}, "variables": {"appG
wID": "[resourceId('Microsoft.Network/applicationGateways', 'None')]"}, "contentVersion": "1.0.0.0", "$schema": "https://schema.management.azure.com/schemas/2015-01-01/d
eploymentTemplate.json#", "resources": [{"name": "vmsssuccessVNET", "tags": {}, "apiVersion": "2015-06-15", "location": "southeastasia", "dependsOn": [], "type": "Micros
oft.Network/virtualNetworks", "properties": {"subnets": [{"name": "vmsssuccessSubnet", "properties": {"addressPrefix": "10.0.0.0/24"}}, {"name": "appGwSubnet", "properti
es": {"addressPrefix": "10.0.1.0/24"}}], "addressSpace": {"addressPrefixes": ["10.0.0.0/16"]}}}, {"name": "NonePublicIP", "tags": {}, "apiVersion": "2017-09-01", "locati
on": "southeastasia", "dependsOn": [], "type": "Microsoft.Network/publicIPAddresses", "properties": {"publicIPAllocationMethod": "Dynamic"}}, {"name": null, "tags": {},
"apiVersion": "2015-06-15", "location": "southeastasia", "dependsOn": ["Microsoft.Network/virtualNetworks/vmsssuccessVNET", "Microsoft.Network/publicIpAddresses/NonePubl
icIP"], "type": "Microsoft.Network/applicationGateways", "properties": {"sku": {"tier": "Standard", "capacity": 10, "name": "Standard_Large"}, "frontendPorts": [{"name":
 "appGwFrontendPort", "properties": {"Port": 80}}], "requestRoutingRules": [{"Name": "rule1", "properties": {"backendAddressPool": {"id": "[concat(variables('appGwID'),
'/backendAddressPools/vmsssuccessLBBEPool')]"}, "backendHttpSettings": {"id": "[concat(variables('appGwID'), '/backendHttpSettingsCollection/appGwBackendHttpSettings')]"
}, "RuleType": "Basic", "httpListener": {"id": "[concat(variables('appGwID'), '/httpListeners/appGwHttpListener')]"}}}], "backendHttpSettingsCollection": [{"name": "appG
wBackendHttpSettings", "properties": {"CookieBasedAffinity": "Disabled", "Protocol": "Http", "Port": 80}}], "backendAddressPools": [{"name": "vmsssuccessLBBEPool"}], "ga
tewayIPConfigurations": [{"name": "appGwIpConfig", "properties": {"subnet": {"id": "/subscriptions/5a810961-5236-4bbd-b50a-bda258eb00c0/resourceGroups/vmsssuccess/provid
ers/Microsoft.Network/virtualNetworks/vmsssuccessVNET/subnets/appGwSubnet"}}}], "frontendIPConfigurations": [{"name": "appGwFrontendIP", "properties": {"publicIPAddress"
: {"id": "/subscriptions/5a810961-5236-4bbd-b50a-bda258eb00c0/resourceGroups/vmsssuccess/providers/Microsoft.Network/publicIPAddresses/NonePublicIP"}}}], "httpListeners"
: [{"name": "appGwHttpListener", "properties": {"FrontendPort": {"Id": "[concat(variables('appGwID'), '/frontendPorts/appGwFrontendPort')]"}, "Protocol": "Http", "SslCer
tificate": null, "FrontendIPConfiguration": {"Id": "[concat(variables('appGwID'), '/frontendIPConfigurations/appGwFrontendIP')]"}}}]}}, {"sku": {"capacity": 101, "name":
 "Standard_D1_v2"}, "name": "vmsssuccess", "tags": {}, "apiVersion": "2017-03-30", "location": "southeastasia", "dependsOn": ["Microsoft.Network/virtualNetworks/vmsssucc
essVNET", "Microsoft.Network/applicationGateways/None"], "type": "Microsoft.Compute/virtualMachineScaleSets", "properties": {"overprovision": false, "virtualMachineProfi
le": {"storageProfile": {"imageReference": {"sku": "16.04-LTS", "publisher": "Canonical", "version": "latest", "offer": "UbuntuServer"}, "osDisk": {"caching": "ReadWrite
", "managedDisk": {"storageAccountType": null}, "createOption": "FromImage"}}, "osProfile": {"computerNamePrefix": "vmsssae8c", "adminUsername": "negat", "linuxConfigura
tion": {"ssh": {"publicKeys": [{"path": "/home/negat/.ssh/authorized_keys", "keyData": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCnUNgGM13Iezz3kkHFk10ft6aeTaf7TbVCt0SWKVCo+
ttTWD/1TtBiFY8H+z/G3debaxehZ1Ul4UD4OtoRjWubys2aWAXj1GN8CGP82+lbyjkwojjO9CM1kOaLt5ubFCVmI2ATexV5FMVnelShGnl97fFSdWG+slich2oxya0mlczGTPOtvJwI/JjhcfG7FHYdI3rDZtWJGV4oeKi7oA
+SNGf/lS/ojtEipfDs6OPMt7wbWS/AvteavHB1fcvCZA9bUilp4IeIXRQeKgQ/rIwBQgiT1oRRApu1KqKa7xgSOZkph3EyLlcpm3AiEmIuzuw2EI/yIBPN2B6dEr/+RImB negat@bieber\n"}]}, "disablePasswordAu
thentication": true}}, "networkProfile": {"networkInterfaceConfigurations": [{"name": "vmsssae8cNic", "properties": {"primary": "true", "ipConfigurations": [{"name": "vm
sssae8cIPConfig", "properties": {"ApplicationGatewayBackendAddressPools": [{"id": "/subscriptions/5a810961-5236-4bbd-b50a-bda258eb00c0/resourceGroups/vmsssuccess/provid$
rs/Microsoft.Network/applicationGateways/None/backendAddressPools/vmsssuccessLBBEPool"}], "subnet": {"id": "/subscriptions/5a810961-5236-4bbd-b50a-bda258eb00c0/resource$
roups/vmsssuccess/providers/Microsoft.Network/virtualNetworks/vmsssuccessVNET/subnets/vmsssuccessSubnet"}}}]}}]}}, "singlePlacementGroup": false, "upgradePolicy": {"mod$
": "Manual"}}}]}}}
msrest.http_logger : Response status: 400
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'x-ms-failure-cause': 'gateway'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-writes': '1199'
msrest.http_logger :     'x-ms-request-id': '5ddd5a5c-83c9-42c1-89bc-5b4b2367f7d7'
msrest.http_logger :     'x-ms-correlation-request-id': '5ddd5a5c-83c9-42c1-89bc-5b4b2367f7d7'
msrest.http_logger :     'x-ms-routing-request-id': 'WESTUS:20171204T195643Z:5ddd5a5c-83c9-42c1-89bc-5b4b2367f7d7'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'Date': 'Mon, 04 Dec 2017 19:56:43 GMT'
msrest.http_logger :     'Content-Length': '239'
msrest.http_logger : Response content:
msrest.http_logger : {"error":{"code":"InvalidRequestContent","message":"The request content was invalid and could not be deserialized: 'Required property 'name' expect$
 a value but got null. Path 'properties.template.resources[2]', line 1, position 2986.'."}}
msrest.exceptions : The request content was invalid and could not be deserialized: 'Required property 'name' expects a value but got null. Path 'properties.template.res$
urces[2]', line 1, position 2986.'.
The request content was invalid and could not be deserialized: 'Required property 'name' expects a value but got null. Path 'properties.template.resources[2]', line 1, $
osition 2986.'.

### Environment summary

Install Method: interactive script.
OS: Ubuntu 16.04-LTS
CLI version:

azure-cli (2.0.21)

acr (2.0.15)
acs (2.0.19)
appservice (0.1.20)
backup (1.0.3)
batch (3.1.7)
batchai (0.1.3)
billing (0.1.6)
cdn (0.0.10)
cloud (2.0.10)
cognitiveservices (0.1.9)
command-modules-nspkg (2.0.1)
component (2.0.8)
configure (2.0.12)
consumption (0.1.6)
container (0.1.13)
core (2.0.21)
cosmosdb (0.1.15)
dla (0.0.15)
dls (0.0.18)
eventgrid (0.1.5)
extension (0.0.6)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.11)
iot (0.1.14)
keyvault (2.0.14)
lab (0.0.13)
monitor (0.0.12)
network (2.0.18)
nspkg (3.0.1)
profile (2.0.15)
rdbms (0.0.9)
redis (0.2.10)
reservations (0.1.0)
resource (2.0.18)
role (2.0.14)
servicefabric (0.0.6)
sql (2.0.15)
storage (2.0.19)
vm (2.0.18)

Python (Linux) 2.7.12 (default, Nov 20 2017, 18:23:56)
[GCC 5.4.0 20160609]

**Comment by yugangw-msft** [comment]
The defaulting logic is broken

**Comment by yugangw-msft** [comment]
Fixed though #5138

**Comment by gatneil** [comment]
Awesome. Thanks! :)
