### ISSUE TITLE
'expand' method doesn't retrieve help text correctly on knack branch.

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#5037]
Instances in SQL and RBDMS where `ArgumentContext.expand` are used no longer extract the correct help text aliases from the SDK. 

cc/ @yugangw-msft

**Comment by yugangw-msft** [comment]
Per our conversation in the scrum, this should have been fixed?

**Comment by tjprescott** [comment]
Yes, this has been fixed.
