### ISSUE TITLE
Commands return empty array instead of nothing

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#5044]
Some commands return an empty array instead of nothing.

Pre-knack
![screen shot 2017-12-05 at 10 03 00 am](https://user-images.githubusercontent.com/16448634/33622759-8fc574a2-d9a3-11e7-9156-93d18d14b0b4.png)

Post-knack
![screen shot 2017-12-05 at 10 02 48 am](https://user-images.githubusercontent.com/16448634/33622729-84b61a8a-d9a3-11e7-850d-adcdb64fa02a.png)

**Comment by derekbekoe** [comment]
@tamirkamara thanks for highlighting that.

It may be a separate fix but it's fine to keep that as part of this issue also.

**Comment by tjprescott** [comment]
I've checked and it was the same underlying issue. Has been fixed.
