### ISSUE TITLE
azure-cli client issues a duplicate command after 2 minutes

### ISSUE THREAD

**Issue by dmitsh** [Azure/azure-cli#5047]
I'm seeing in some cases that azure-cli client duplicates already issued command after 2 minutes.

I'm attaching deployment-related HTTP requests (5 fields per request) for the resource group.
The first and the last requests are identical:

PreciseTimeStamp
operationName
httpStatusCode
targetUri
userAgent

## 1 ##
2017-12-05 06:48:42.7163123
PUT/SUBSCRIPTIONS/RESOURCEGROUPS/PROVIDERS/MICROSOFT.RESOURCES/DEPLOYMENTS/
201
https://management.azure.com/subscriptions/<sub>/resourcegroups/<rg>/providers/Microsoft.Resources/deployments/azurecli1512456518.6712350?api-version=2017-05-10
python/2.7.12 (Linux-4.11.0-1015-azure-x86_64-with-Ubuntu-16.04-xenial) requests/2.18.4 msrest/0.4.19 msrest_azure/0.4.17 resourcemanagementclient/1.2.1 Azure-SDK-For-Python AZURECLI/2.0.21

## 2 ##
2017-12-05 06:48:52.8234114
POST/SUBSCRIPTIONS/RESOURCEGROUPS/PROVIDERS/MICROSOFT.RESOURCES/DEPLOYMENTS/VALIDATE
200
https://management.azure.com/subscriptions/<sub>/resourcegroups/<rg>/providers/Microsoft.Resources/deployments/195d0e90-fed2-4d83-8684-f309bec5e0b0/validate?api-version=2016-09-01
Microsoft.Azure.Management.ResourceManager.ResourceManagementClient/1.0.0.0

## 3 ##
2017-12-05 06:48:56.1942056
POST/SUBSCRIPTIONS/RESOURCEGROUPS/PROVIDERS/MICROSOFT.RESOURCES/DEPLOYMENTS/VALIDATE
200
https://management.azure.com/subscriptions/<sub>/resourcegroups/<rg>/providers/Microsoft.Resources/deployments/b87da223-eeca-488b-9267-b6cbc5cb42b9/validate?api-version=2016-09-01
Microsoft.Azure.Management.ResourceManager.ResourceManagementClient/1.0.0.0

## 4 ##
2017-12-05 06:48:59.4633091
PUT/SUBSCRIPTIONS/RESOURCEGROUPS/DEPLOYMENTS/
201
https://management.azure.com/subscriptions/<sub>/resourcegroups/<rg>/deployments/b87da223-eeca-488b-9267-b6cbc5cb42b9?api-version=2014-04-01-preview
Microsoft.Azure.Management.Resources.ResourceManagementClient/2.0.0.0

## 5 ##
2017-12-05 06:50:21.5758500
PUT/SUBSCRIPTIONS/RESOURCEGROUPS/PROVIDERS/MICROSOFT.RESOURCES/DEPLOYMENTS/
409
https://management.azure.com/subscriptions/<sub>/resourcegroups/<rg>/providers/Microsoft.Resources/deployments/azurecli1512456518.6712350?api-version=2017-05-10
python/2.7.12 (Linux-4.11.0-1015-azure-x86_64-with-Ubuntu-16.04-xenial) requests/2.18.4 msrest/0.4.19 msrest_azure/0.4.17 resourcemanagementclient/1.2.1 Azure-SDK-For-Python AZURECLI/2.0.21

**Comment by derekbekoe** [comment]
For some commands, multiple API calls are required so I suspect this is what this is and it's to be expected.
