### ISSUE TITLE
On-board Data Factory service

### ISSUE THREAD

**Issue by eltermann** [Azure/azure-cli#5051]
Hi,

PowerShell seems to have seamless integration to Data Factory (e.g: command Set-AzureRmDataFactoryV2).

It would be great if azure-cli also had support to it.

**Comment by eltermann** [comment]
Hello @tjprescott,

Is there any estimate for this feature to be implemented?

**Comment by tjprescott** [comment]
Hi @eltermann, I'm not aware of any active CLI work on this feature.

cc/ @mayurid @twitchax

**Comment by syedhassaanahmed** [comment]
+1 on Azure CLI support for ADF v2

**Comment by AodbeKulick** [comment]
+1 as well for both ADF and ADFv2.  Powershell support is OS specific.

**Comment by yonzhan** [comment]
issue triaged.

**Comment by yungezz** [comment]
Thanks for reporting the issue, we noticed the coverage gap with Powershell, and working on support Data Factory in CLI. The work is tracked in https://github.com/Azure/azure-cli/issues/11527. close this one for now. pls get latest status from issue https://github.com/Azure/azure-cli/issues/11527.
