### ISSUE TITLE
Configuration object creation (similar to powershell)

### ISSUE THREAD

**Issue by iyerusad** [Azure/azure-cli#5059]
There is small but growing divide the between capability of AZ CLI and Azure Powershell.

Of particular note is object creation in Powershell. In Powershell, a complete configuration object can be created using multiple commands. [Example ($gw)](https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-configure-redirect-powershell):
```
# Get the application gateway
$gw = Get-AzureRmApplicationGateway -Name AdatumAppGateway -ResourceGroupName AdatumAppGatewayRG

# Get the existing HTTPS listener
$httpslistener = Get-AzureRmApplicationGatewayHttpListener -Name appgatewayhttplistener -ApplicationGateway $gw

# Get the existing front end IP configuration
$fipconfig = Get-AzureRmApplicationGatewayFrontendIPConfig -Name appgatewayfrontendip -ApplicationGateway $gw

# Add a new front end port to support HTTP traffic
Add-AzureRmApplicationGatewayFrontendPort -Name appGatewayFrontendPort2  -Port 80 -ApplicationGateway $gw

# Get the recently created port
$fp = Get-AzureRmApplicationGatewayFrontendPort -Name appGatewayFrontendPort2 -ApplicationGateway $gw

# Create a new HTTP listener using the port created earlier
Add-AzureRmApplicationGatewayHttpListener -Name appgatewayhttplistener2  -Protocol Http -FrontendPort $fp -FrontendIPConfiguration $fipconfig -ApplicationGateway $gw 

# Get the new listener
$listener = Get-AzureRmApplicationGatewayHttpListener -Name appgatewayhttplistener2 -ApplicationGateway $gw

# Add a redirection configuration using a permanent redirect and targeting the existing listener
Add-AzureRmApplicationGatewayRedirectConfiguration -Name redirectHttptoHttps -RedirectType Permanent -TargetListener $httpslistener -IncludePath $true -IncludeQueryString $true -ApplicationGateway $gw

# Get the redirect configuration
$redirectconfig = Get-AzureRmApplicationGatewayRedirectConfiguration -Name redirectHttptoHttps -ApplicationGateway $gw


# Add a new rule to handle the redirect and use the new listener
Add-AzureRmApplicationGatewayRequestRoutingRule -Name rule02 -RuleType Basic -HttpListener $listener -RedirectConfiguration $redirectconfig -ApplicationGateway $gw

# Update the application gateway
Set-AzureRmApplicationGateway -ApplicationGateway $gw 
```

**Why does this matter/needed?**

Application Gateway can take a whole day(!) to deploy due to each individual change taking anywhere from [5-45 minutes to apply](https://feedback.azure.com/forums/281804-azure-resource-manager/suggestions/19119910-application-gateway-management-operations-are-agon).

Powershell avoids this by generating the configuration object and then applying it in bulk to the Application Gateway, resulting in only 1 operation.

Presumably this will continue to be the case with more and more PaaS offerings in Azure. Is the right answer here to build this capability in AZ CLI or perhaps the right answer is to improve mgmt PaaS offerings that are so cludgy? This would be a suggestion for the former, as to some extent understand why Application Gateway takes some time to apply changes (multiple nodes, etc).

**Comment by tjprescott** [comment]
HI @iyerusad, please try issuing your application gateway commands with `--no-wait`.  In this way, you don't have to wait for the entire update cycle to finish and can chain multiple commands together to configure your gateway.  In fact, application gateways were the primary reason that `--no-wait` was added in the first place.

To answer you original question, no, for technical reasons, the Powershell approach is not feasible in the CLI.  However, `--no-wait` can alleviate much of the frustration or you can deploy your gateway using an ARM template (through `az group deployment create`.

**Comment by iyerusad** [comment]
Thanks @tjprescott - I had previously attempted the `--no-wait` in the past and for some reason led to believe that it didn't function in this way. I just took some time today to validate and it appears to function as outlined.

The original question appears to be not possible/feasible at this time so will close this issue out.

Code example to validate the `--no-wait` is working:
```
az group create --name "testing-ag-1" --location "westus"

az network application-gateway create \
--name "testAppGateway" \
--location "westus" \
--resource-group "testing-ag-1" \
--vnet-name "testAppGatewayVNET" \
--vnet-address-prefix "10.0.0.0/16" \
--subnet "Appgatewaysubnet" \
--subnet-address-prefix "10.0.0.0/28" \
--servers "10.0.0.5"  \
--public-ip-address test-ip

az network application-gateway probe create \
--gateway-name "testAppGateway" \
--resource-group "testing-ag-1" \
--name "Probe1" \
--path "/probe1" \
--host "127.0.0.1" \
--protocol "Http" \
--no-wait

az network application-gateway probe create \
--gateway-name "testAppGateway" \
--resource-group "testing-ag-1" \
--name "Probe2" \
--path "/probe2" \
--host "127.0.0.1" \
--protocol "Http" \
--no-wait

az network application-gateway probe create \
--gateway-name "testAppGateway" \
--resource-group "testing-ag-1" \
--name "Probe3" \
--path "/probe3" \
--host "127.0.0.1" \
--protocol "Http" \
--no-wait

az group delete --name "testing-ag-1"
```
