### ISSUE TITLE
there should be a way to view a resource from an ID

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#506]
today az resource show requires users to split up IDs into their parts in order to see details of the object.  Since IDs are copy-pasteable, users should be able to paste in the ID to resource show so they can easily expand a related resource.

Scenario:

az vm show -> networkInterfaces: ID
user wants to expand what is in the nic

expected: user copy-pastes ID into az resource show

actual: user has to parse ID and break it into parts or find the command for that specific resource type

**Comment by tjprescott** [comment]
Issue #806 is a duplicate, but is more specific on implementation details.
