### ISSUE TITLE
Enable REST API access for API Management

### ISSUE THREAD

**Issue by nagpal** [Azure/azure-cli#5067]
---

### Environment summary

brew / 2.0.20 / macOS 10.13.1 / bash 

```
```

Using Azure CLI, I am looking for a way to 
1. Enable REST API access for API management
2. Get the API Identifier and Primary/Secondary keys generated from Step1 and push them to keyvault for later use 

Is there any support for enabling REST API access through the CLI?

Btw, this is the PowerShell method of enabling the REST API:
Set-AzureRmApiManagementTenantAccess -Context $apimContext -Enabled $true

-Vijay

**Comment by dmitrytokarev** [comment]
This looks like a duplicate to https://github.com/Azure/azure-cli/issues/3614

**Comment by tjprescott** [comment]
@dmitrytokarev agreed. Closing.
