### ISSUE TITLE
`client_factory` kwarg bug in KnackConversion branch

### ISSUE THREAD

**Issue by williexu** [Azure/azure-cli#5072]
When using the `custom_command()` method to register a command, the client_factory being used is taken from the `command_type` kwarg. 
The client_factory should instead be taken from the `custom_command_type`
https://github.com/Azure/azure-cli/blob/KnackConversion/src/azure-cli-core/azure/cli/core/__init__.py#L319-L321

**Comment by derekbekoe** [comment]
Looks like this was fixed in https://github.com/Azure/azure-cli/pull/5074
