### ISSUE TITLE
webapp-config:space in connection string causes "connection-string set" to create too many entries

### ISSUE THREAD

**Issue by Ian1971** [Azure/azure-cli#5077]
It seems that the spaces in database connection strings cause connection-string set to create additional entries in connection strings. Note also that appsettings set seems to have a similar problem
Even though I have put my connection string in quotes it doesn't help.

`
az webapp config connection-string set --name mywebapp --resource-group mywebapp --connection-string-type SQLAzure --settings ConnectionName="Server=tcp:mydbserver.database.windows.net,1433;Database=mydb;User ID=myuser@mydb;Password=mypassword;Trusted_Connection=False;Encrypt=True;Connection Timeout=30;MultipleActiveResultSets=True;"
`
This gives output e.g.

{
  "ID": {
    "type": "SQLAzure",
    "value": "myuser@mydb;Password=mypassword;Trusted_Connection=False;Encrypt=True;Connection"
  },
  "ConnectionName": {
    "type": "SQLAzure",
    "value": "Server=tcp:mydbserver.database.windows.net,1433;Database=mydb;User ID=myuser@mydb;Password=mypassword;Trusted_Connection=False;Encrypt=True;Connection Timeout=30;MultipleActiveResultSets=True;"
  },
  "Timeout": {
    "type": "SQLAzure",
    "value": "30;MultipleActiveResultSets=True;"
  }
}

---

### Environment summary

Install Method MSI / CLI version 2.0.22 / OS version Windows 10 / Server 2012 r2 / Shell Type powershell and cmd)  

```
```

**Comment by yugangw-msft** [comment]
Make sure to wrap the whole `<name>=<connection-str>` with quotes, instead of only around the `<connection-str>`. We wrote a [doc](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#quoting-issues) recently just for this, particularly on the point 6
