### ISSUE TITLE
Possible issue with Azure Stack

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-cli#5097]
https://github.com/Azure/azure-cli/blob/8fcb30cba06b035bee374c4949dcbfc21ad034b0/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/custom.py#L187

Got confirmation after a discussion with @bganapa that AzureStack metadata endpoint does not fill storage_endpoint, and that this is not gonna happen for any dataplane. We should get the value from
```python
client.storage_accounts.get_properties(rg,name).primary_endpoints.blob
client.storage_accounts.get_properties(rg,name).primary_endpoints.queue
client.storage_accounts.get_properties(rg,name).primary_endpoints.table
client.storage_accounts.get_properties(rg,name).primary_endpoints.file
```

https://docs.microsoft.com/en-us/python/api/azure.mgmt.storage.v2017_06_01.models.endpoints?view=azure-python

Maybe you have a workaround to fill the `storage_endpoint` even if it's not in the metadata endpoint, in that case I'm curious to understand what it is (didn't find it in the CLI code).

Creating this issue just in case, feel free to close it if CLI has a hack I don't know.

**Comment by yonzhan** [comment]
@Juliehzl  add to S162.

**Comment by Juliehzl** [comment]
Hi @bganapa Can you help check that if AzureStack metadata endpoint fill storage_endpoint now?

**Comment by bganapa** [comment]
This is the metadata endpoint, This does not include the dataplane related endpoints
https://management.azure.com/metadata/endpoints?api-version=2018-05-01

**Comment by bganapa** [comment]
in Azure stack, we explicitly ask user to provide the storage endpoint and keyvault data plane while registering the code. 
az cloud register  -n <environmentname>   --endpoint-resource-manager "https://management.local.azurestack.external"  --suffix-storage-endpoint "local.azurestack.external" --suffix-keyvault-dns ".vault.local.azurestack.external" --endpoint-vm-image-alias-doc <URI of the document which contains VM image aliases>   --profile "2019-03-01-hybrid"

As laurent mentioned, if CLI can read the storage data plane endpoint from the storage RP somehow(Im not sure what call would get the dataplane endpoint from storage RP), we can avoid the extra parameter

**Comment by Juliehzl** [comment]
After discussion with @bganapa , it is hard to fiund a way  to get the storage data plane endpoint information automatically from storage RP or ARM. @lmazuel method assumes that  there is a storage account exists, which is not expected.
In this way, we decide to keep current behavior to ask user  to provide the storage endpoint and keyvault data plane while registering the code.
