### ISSUE TITLE
VM/VMSS: removing last user assigned identity doesn't work

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#5103]
2 service end issues, to be fixed by the beginning of January
1. Setting `identity.type` to `None` is not working
2. Setting `identity.type` to `SystemAssigned` after remove the last user assigned identity goes through, compute RP still leave behind a non empty identity_ids

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
