### ISSUE TITLE
Misleading error message when creating new storage account

### ISSUE THREAD

**Issue by polarapfel** [Azure/azure-cli#5115]
Hi there,

the error message given when creating a generic storage account while also providing the --access-tier parameter is misleading.

---

### Environment summary

Cloud Shell in Azure Portal.

```
~$ az storage account create --name eventlogsamplegeneric --location westcentralus --resource-group storageeventlogsample --sku Standard_LRS --kind Storage --access-tier Hot

Account property accessTier is required for the request.
```

The error message is wrong. To create a generic storage account, the --access-tier parameter has to be dropped.

**Comment by cinek810** [comment]
It should be changed also for "update" operation on general purpose storage account

**Comment by williexu** [comment]
The response message is coming from the service. I will raise this to their attention and update this issue accordingly.
Thanks for catching this :)

**Comment by arichiardi** [comment]
I have run into this as well, I agree it should be fixed

**Comment by priyalaggarwal** [comment]
Ran into this issue today via .NET SDK.

`Unhandled Exception: Microsoft.Rest.Azure.CloudException: Account property accessTier is required for the request.`

**Comment by JJ** [comment]
I am getting this error too, with the last version...

**Comment by tjprescott** [comment]
@williexu can we get an update on this? If storage isn't willing to fix it, we could consider a short-term fix for CLI users.

**Comment by williexu** [comment]
@seguler can this be raised to the service team in question? The service is returning an improper error.

**Comment by sanvic76** [comment]
Tested today and issue still persists

**Comment by williexu** [comment]
@seguler I know there was a fix made recently, when will that be available to users?

**Comment by yonzhan** [comment]
add to S165.

**Comment by yonzhan** [comment]
@seguler  any update about this issue?

**Comment by yonzhan** [comment]
@seguler any update about this issue?

**Comment by Juliehzl** [comment]
I have checked with the latest azure cli. It should already be fixed. If there is still any other problem, please create a new issue ticket to us.
