### ISSUE TITLE
[Knack] Fix performance regressions for affected modules

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#5128]
The following modules show significant loading time regressions on the Knack branch relative to the original core.

- [x] batch (PR #5150) [12 ms]
- [ ] cloud [298 ms]
- [ ] dla [88 ms]
- [x] keyvault (PR #5154) [8 ms]
- [ ] lab [121 ms]
- [ ] storage [58 ms]

**Comment by troydai** [comment]
@tjprescott what's the scenario in play here?

**Comment by tjprescott** [comment]
Comparison of `az --debug` on the Knack  branch vs the dev branch.  The modules on the list are slower (sometimes much slower) than those on dev.

**Comment by troydai** [comment]
ok

**Comment by tjprescott** [comment]
After @troydai's PRs fixing the worst offenders (KeyVault and Batch) the load time for all modules is back to 0.5 second, which is comparable to the dev branch.  We can still improve upon that.
