### ISSUE TITLE
cli_ctx should be available for functions in parallel

### ISSUE THREAD

**Issue by tamirkamara** [Azure/azure-cli#5134]
With the move to the Knack framework it's not possible to access cmd / cli_ctx from within functions called in parallel (like with python multiprocess method). The reason is most likely that these objects cannot be pickled and hence can't be transferred to the target functions.
This causes issues when wanting to report progress (for example).

We might need to think of a way for the cli_ctx to be available in these situations.

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by tjprescott** [comment]
The simplest way I would suggest is:

**Old**
```
def my_method(a, b):
  return a + b

pass_this_method(my_method)
```

**New**
```
def get_my_method(cli_ctx):
   def my_method(a, b):
      cli_ctx.foo # do whatever you need cli_ctx for
      return a + b
   return my_method

pass_this_method(get_my_method(cli_ctx))
```

Does this work?

**Comment by yonzhan** [comment]
add to S165.

**Comment by jiasli** [comment]
@tamirkamara, please let us know whether the above answer solves your question. If not, please provide more details about the usage. Thanks.
