### ISSUE TITLE
[ACS/AKS] Tests failing when run live

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#5141]
The following tests fail when run live on the dev branch. They are being converted to LiveScenarioTests to facilitate the Knack conversion since they cannot be re-recorded.

- [x] test_aks_create_with_upgrade: `msrestazure.azure_exceptions.CloudError: 400 Client Error: Bad Request for url: ... ` (PR #5254)
- [ ] test_acs_create_kubernetes: `The credentials in ServicePrincipalProfile were invalid.`
- [x] test_aks_create_default_service: `msrestazure.azure_exceptions.CloudError: 400 Client Error: Bad Request for url: ...` (PR #5254)

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```

install via dev_setup.py 

azure-cli (2.0.24)

acr (2.0.17)
acs (2.0.22)
advisor (0.1.0)
appservice (0.1.22)
backup (1.0.3)
batch (3.1.7)
batchai (0.1.3)
billing (0.1.6)
cdn (0.0.10)
cloud (2.0.10)
cognitiveservices (0.1.9)
configure (2.0.12)
consumption (0.2.0)
container (0.1.15)
core (2.0.24)
cosmosdb (0.1.15)
dev-tools (0.1.1)
dla (0.0.15)
dls (0.0.18)
eventgrid (0.1.5)
extension (0.0.6)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.11)
iot (0.1.15)
keyvault (2.0.15)
lab (0.0.13)
monitor (0.0.13)
network (2.0.19)
nspkg (3.0.1)
profile (2.0.16)
rdbms (0.0.9)
redis (0.2.10)
reservations (0.1.0)
resource (2.0.19)
role (2.0.15)
servicefabric (0.0.7)
sql (2.0.17)
storage (2.0.21)
testsdk (0.1.0)
vm (2.0.20)

Python location 'E:\github\azure-cli\env\Scripts\python.exe'
Extensions directory 'C:\Users\travi\.azure\cliextensions'

Python (Windows) 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
```

**Comment by mboersma** [comment]
@tjprescott I didn't realize we ran tests with `--live` in CI, or that this failed. My hunch is it has something to do with the `RoleBasedServicePrincipalPreparer` decorator... Should I try to fix in the dev or KnackConversion branch?

> They are being converted to LiveScenarioTests to facilitate the Knack conversion since they cannot be re-recorded.

I did re-record all ACS ScenarioTests for Knack conversion in #5036, so I'm confused by this.
