### ISSUE TITLE
[Batch] Batch test failing when run live

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#5142]
The following test `test_batch_account_cmd` fails when run live on the dev branch. Because it cannot be re-recorded, it is being converted to LiveScenarioTest for purposes of merging the Knack branch.

When the test is run, the following error occurs:
```
msrestazure.azure_exceptions.CloudError: Azure Error: InsufficientPermissions
Message: The Batch service does not have the required permissions to access the specified Subscription.
RequestId:f8a48aac-803a-48cd-8cea-726712176d7a
Time:2017-12-20T06:27:41.2567300Z
Target: BatchAccount
```

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
install via dev_setup.py

azure-cli (2.0.24)

acr (2.0.17)
acs (2.0.22)
advisor (0.1.0)
appservice (0.1.22)
backup (1.0.3)
batch (3.1.8)
batchai (0.1.3)
billing (0.1.6)
cdn (0.0.10)
cloud (2.0.11)
cognitiveservices (0.1.9)
configure (2.0.12)
consumption (0.2.0)
container (0.1.15)
core (2.0.24)
cosmosdb (0.1.15)
dev-tools (0.1.1)
dla (0.0.15)
dls (0.0.18)
eventgrid (0.1.6)
extension (0.0.6)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.11)
iot (0.1.15)
keyvault (2.0.15)
lab (0.0.13)
monitor (0.0.13)
network (2.0.19)
nspkg (3.0.1)
profile (2.0.16)
rdbms (0.0.9)
redis (0.2.10)
reservations (0.1.0)
resource (2.0.19)
role (2.0.15)
servicefabric (0.0.7)
sql (2.0.17)
storage (2.0.21)
testsdk (0.1.0)
vm (2.0.23)

Python location 'E:\github\azure-cli\env\Scripts\python.exe'
Extensions directory 'C:\Users\travi\.azure\cliextensions'

Python (Windows) 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
```

**Comment by tjprescott** [comment]
Presumably--it's still listed as a LiveScenarioTest in code.

**Comment by tjprescott** [comment]
It used to be recorded and that is preferable because it lets us test breaking changes to the CLI interface on each PR.  Live tests won't catch a problem until after it has already been merged. It is most likely just that the subscription we use to record the tests needs some permission or whitelist. cc/ @troydai

**Comment by bgklein** [comment]
Yea looks to be the line failing requires 'Microsoft Azure Batch' to be a contributor on the subscription.   if this cannot be granted, I can move the test cmd which is causing the failure to a separate test so the other cmds will still be tested
