### ISSUE TITLE
[KeyVault] KeyVault tests fail when run live

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#5146]
The following tests fail when run live and cannot be re-recorded. They are being temporarily converted to LiveScenarioTests to facilitate work on the Knack branch.

- [ ] test_keyvault_softdelete
- [ ] test_keyvault_certificate_import
- [ ] test_keyvault_certificate_download

**Comment by bim-msft** [comment]
I've checked the latest status of these 3 tests:
`test_keyvault_certificate_import` and `test_keyvault_certificate_download` works fine for me, now they can be re-recorded as well.
For `test_keyvault_softdelete`, there is still some chance of failure as we have to wait for service side's status. So we added a `time.sleep` for this, which can improve the possibility of recording success. When it is successfully recorded, it will works fine on playback process.
