### ISSUE TITLE
Regular expression support for JMESPath queries in Azure CLI

### ISSUE THREAD

**Issue by shriganeshs** [Azure/azure-cli#5148]
I am building images using Packer periodically. Each image will be stored with same image name with a  timestamp as a postfix. I want get the name of the latest image using Azure CLI.

For example I have following image names in the same Resource Group.

1) custom-image-centos73-git-python36_1513795384
2) custom-image-centos73-git-python36_1513796300

The second image is the latest image. I want to use Azure CLI to get the latest image.
`> az image list --query "[?contains(name, 'custom-image-centos73-git-python36_*')]"`

Note that above command needs some sorting to get the latest image, which I have not added here.

```
Environment summary
Install Method: brew install / OS X El Capitan 10.11.6 (15G18013) / Terminal.  

azure-cli (2.0.21)

acr (2.0.15)
acs (2.0.19)
appservice (0.1.20)
backup (1.0.3)
batch (3.1.7)
batchai (0.1.3)
billing (0.1.6)
cdn (0.0.10)
cloud (2.0.10)
cognitiveservices (0.1.9)
command-modules-nspkg (2.0.1)
component (2.0.8)
configure (2.0.12)
consumption (0.1.6)
container (0.1.13)
core (2.0.21)
cosmosdb (0.1.15)
dla (0.0.15)
dls (0.0.18)
eventgrid (0.1.5)
extension (0.0.6)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.11)
iot (0.1.14)
keyvault (2.0.14)
lab (0.0.13)
monitor (0.0.12)
network (2.0.18)
nspkg (3.0.1)
profile (2.0.15)
rdbms (0.0.9)
redis (0.2.10)
reservations (0.1.0)
resource (2.0.18)
role (2.0.14)
servicefabric (0.0.6)
sql (2.0.15)
storage (2.0.19)
vm (2.0.18)

Python location '/Users/sshintre/venv/bin/python'
Extensions directory '/Users/sshintre/.azure/cliextensions'

Python (Darwin) 3.4.4 (v3.4.4:737efcadf5a6, Dec 19 2015, 20:38:52)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

Legal docs and information: aka.ms/AzureCliLegal
```

**Comment by derekbekoe** [comment]
Can you replace `contains` with `starts_with` then use the sort_by function?
http://jmespath.org/specification.html#sort-by

**Comment by yugangw-msft** [comment]
Assuming @derekbekoe's suggestion works, I am closing it, but please reactivate otherwise
