### ISSUE TITLE
Test Feedback

### ISSUE THREAD

**Issue by neilpeterson** [Azure/azure-cli#5156]
I just want to see how this works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58c81c4d-10d2-fc04-e707-fcf914f4d540
* Version Independent ID: 8598f788-bd33-a4c8-ed66-593e0fde75d5
* [Content](https://docs.microsoft.com/en-us/cli/azure/group?view=azure-cli-latest#az_group_create)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py)

**Comment by jdanyow** [comment]
@neilpeterson if you :lock: lock this issue it will stop showing up on the docs site. 

https://github.com/blog/1847-locking-conversations

**Comment by neilpeterson** [comment]
Thanks @jdanyow, this is good to know. Unfortunately I do not see the option to lock the conversation on this issue. Is there configuration that needs to be completed to give me this access?

To troubleshoot, I've checked some of my personal repos and do have this capability.

**Comment by jdanyow** [comment]
I guess you need to be a repo owner to see the lock option

**Comment by babuw** [comment]
test_benjamin (closed issue but still able to add comments)
