### ISSUE TITLE
[VM] test_custom_image_with_plan test is flaky when run live

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#5161]
This tests has oscillated between failing because the '99percentoff' code is sometimes valid and sometimes not (service dependent) but then it tends to run constantly. Since this is unlikely due to the Knack conversion, I'm converting it to LiveScenarioTest so it can be examined later and converted back.

**Comment by yugangw-msft** [comment]
I have got rid of the invalid code usage of `99percentoff` in the test. Since it is an invalid code, so I can't blame service
