### ISSUE TITLE
Bug or "feature" ? az storage blob copy converts BlockBlobs to AppendBlobs

### ISSUE THREAD

**Issue by udf2457** [Azure/azure-cli#5166]
Digging around whilst trying to troubleshoot #5165, I noticed that `az storage blob copy` seems to have converted my Block BLOBs to Append BLOBs during the process of copying them ?

Is this a bug or a "feature" ? I feel its something that might have the potential to cause problems ?

**Comment by troydai** [comment]
Seems to be a bug.

**Comment by williexu** [comment]
@udf2457 can you give me more information as to youre scenario? (i.e. os, shell, cli version, full command, etc)
I just tried both a regular `az storage blob copy start` and `az storage blob copy start-batch` and I do not notice any append blobs being created.

**Comment by udf2457** [comment]
@williexu Thanks for your message. I'm busy with other work projects at the moment but will try to get back to you later this week.

**Comment by williexu** [comment]
@udf2457 let me know if you have further details, closing this for now.
