### ISSUE TITLE
some VM sizes got by `az vm list-sizes --location southeastasia` are not available on the Azure portal

### ISSUE THREAD

**Issue by gossion** [Azure/azure-cli#5170]
For example, Standard_ND6S
```
$ az vm list-sizes --location southeastasia
[
  ...
  {
    "maxDataDiskCount": 12,
    "memoryInMb": 114688,
    "name": "Standard_ND6s",
    "numberOfCores": 6,
    "osDiskSizeInMb": 1047552,
    "resourceDiskSizeInMb": 344064
  },
  ...
]
```
but in Azure portal, that VM size is grey with `Not Available` when creating new VM.

**Comment by derekbekoe** [comment]
Possibly related to https://github.com/Azure/azure-cli/issues/1800?

**Comment by yugangw-msft** [comment]
It is a known service bug that `vm list-sizes` could expose a few sizes which are actually unavailable. To mitigate that the compute service expose a `ListSkus` API to provide accurate information. So please use `az vm list-skus` to cross check.
I am closing this issue as it is the same with #1800 that @derekbekoe  has mentioned
