### ISSUE TITLE
az sql server vnet-rule create dies with 'too many 500 errors'

### ISSUE THREAD

**Issue by vpopescu** [Azure/azure-cli#5171]
I have an AKS cluster, which creates a vnet aks-vnet-123456 as part of the bring-up:

 `az aks create -n k8cluster  -g myrg ...`

also created a managed sql server:

  `az sql server create --name mysqlserver  -g myrg  ...`

I would like to add a rule to the sql server, for the aks-vnet-* subnet. _I can do this fine in the portal_. Select the SQL server, select Firewall rules, Add existing virtual network...

However, when I try to script it:

  `az sql server vnet-rule create -g myrg -s mysqlserver -n myRule --subnet=/subscriptions/...omitted../Microsoft.Network/virtualNetworks/aks-vnet-123456`

it dies with:
```
Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/...omitted../myRule?api-version=2015-05-01-preview (Caused by ResponseError('too many 500 error responses',))
Traceback (most recent call last):
  File "/home/test/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/home/test/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 216, in execute
    result = expanded_arg.func(params)
  File "/home/test/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 381, in __call__
    return self.handler(*args, **kwargs)
  File "/home/test/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 640, in _execute_command
    raise client_exception
ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/...omitted../Microsoft.Sql/servers/mysqlserver/virtualNetwork

```
 I am unclear if this should work? is it a feature that has not yet been implemented on the server side, or is it a disconnect between the CLI and server side? Or maybe even better, am I doing something wrong?

---

### Environment summary

Bash / Ubuntu 17.10
Azure subscription type: MSDN
Installation method: apt

azure-cli (2.0.22)

acr (2.0.16)
acs (2.0.21)
advisor (0.1.0)
appservice (0.1.21)
backup (1.0.3)
batch (3.1.7)
batchai (0.1.3)
billing (0.1.6)
cdn (0.0.10)
cloud (2.0.10)
cognitiveservices (0.1.9)
command-modules-nspkg (2.0.1)
configure (2.0.12)
consumption (0.2.0)
container (0.1.14)
core (2.0.22)
cosmosdb (0.1.15)
dla (0.0.15)
dls (0.0.18)
eventgrid (0.1.5)
extension (0.0.6)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.11)
iot (0.1.14)
keyvault (2.0.14)
lab (0.0.13)
monitor (0.0.13)
network (2.0.18)
nspkg (3.0.1)
profile (2.0.15)
rdbms (0.0.9)
redis (0.2.10)
reservations (0.1.0)
resource (2.0.19)
role (2.0.15)
servicefabric (0.0.6)
sql (2.0.16)
storage (2.0.20)
vm (2.0.19)

**Comment by kisantia** [comment]
Does it work if you replace the `=` with a space for the subnet info like this: 
`--subnet /subscriptions/...omitted../Microsoft.Network/virtualNetworks/aks-vnet-123456`

**Comment by vpopescu** [comment]
No, Sorry. Actually, I don't know where the equal sign came in, maybe while experimenting to get this thing to work. The syntax I'm using is without the equal sign, which is what you suggested.

The exact syntax I use is:

az sql server vnet-rule create -g RGNAME -s SQLNAME -n RULENAME --subnet /subscriptions/...omitted.../resourceGroups/MC_RGNAME_CLUSTERNAME_centralus/providers/Microsoft.Network/virtualNetworks/SUBNET-123456


Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/...omitted.../resourceGroups/RGNAME/providers/Microsoft.Sql/servers/SQLNAME/virtualNetworkRules/RULENAME?api-version=2015-05-01-preview (Caused by ResponseError('too many 500 error responses',))

where RGNAME is my RG, SQLNAME is the name of the SQL server, RULENAME is the name I want for my rule, MC_RGNAME_CLUSTERNAME_centralus is the companion RG created for the RG RGNAME and AKS cluster CLUSTERNAME, and SUBNET is the subnet created automatically as part of the AKS cluster (named SUBNET-somenumber).

**Comment by kisantia** [comment]
Can you email me the details of the resources and the timestamp of when you last tried this so I can take a look at the logs? My email is kisantia@microsoft.com. Thanks!

**Comment by vpopescu** [comment]
Mail sent.

**Comment by vpopescu** [comment]
Close with the help of kisantia.

Problem was:

1. The syntax required the full path to the subnet, not to the vnet
2. Before the command could complete, MIcrosoft.Sql had to be added to service endpoints:

az network vnet subnet update -n <subnet> -g <group> --vnet-name <vnet> --service-endpoints "Microsoft.Sql"

Apparently the console must do this automatically?
anyway, closing.
