### ISSUE TITLE
az cli login ???

### ISSUE THREAD

**Issue by bharathmakawana** [Azure/azure-cli#5173]
Hello Experts!

I have the below info, can you help me to login using CLI, please

subscription_id 
client_id 
secret 
tenant 
cloud_environment 

I tried the below:
az login -u {above client id} -p {secret id} -t {tenant id}

Please assist

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by yugangw-msft** [comment]
you did the right, except for none public cloud, you need to run `az cloud set -n <AzureChinaCloud/AzureUSGovernment/AzureGermanCloud>`
