### ISSUE TITLE
az storage blob copy start-batch adding invalid characters

### ISSUE THREAD

**Issue by jitskv** [Azure/azure-cli#5174]
az storage blob copy start-batch is prefixing a "b'" to the beginning of each folder and suffixing each filename within with an apostrophe.
Example "folder/file.ext" becomes "b'folder/file.ext'"
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
```
apt-get 
Ubuntu 16.04
Bash on Windows (WSL)
> az --version
azure-cli (2.0.23)

acr (2.0.17)
acs (2.0.22)
advisor (0.1.0)
appservice (0.1.22)
backup (1.0.3)
batch (3.1.7)
batchai (0.1.3)
billing (0.1.6)
cdn (0.0.10)
cloud (2.0.10)
cognitiveservices (0.1.9)
command-modules-nspkg (2.0.1)
configure (2.0.12)
consumption (0.2.0)
container (0.1.15)
core (2.0.23)
cosmosdb (0.1.15)
dla (0.0.15)
dls (0.0.18)
eventgrid (0.1.5)
extension (0.0.6)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.11)
iot (0.1.15)
keyvault (2.0.15)
lab (0.0.13)
monitor (0.0.13)
network (2.0.19)
nspkg (3.0.1)
profile (2.0.16)
rdbms (0.0.9)
redis (0.2.10)
reservations (0.1.0)
resource (2.0.19)
role (2.0.15)
servicefabric (0.0.7)
sql (2.0.17)
storage (2.0.21)
vm (2.0.20)
```

**Comment by scottsen** [comment]
Ya, this just made me very sad too.  I'm using docker on windows against azuresdk/azure-cli-python.

**Comment by tjprescott** [comment]
@williexu is this still an issue or has this been fixed?

**Comment by williexu** [comment]
@jitskv @scottsen is this still a problem for you guys?
If so, let me know more about your environment details (version of python, os mainly).

Just tried the command on windows (py3) and ubuntu 16.04 (py3 and py2) with no problems.

**Comment by jitskv** [comment]
Its working for me. Started working even without having to update cli. The problem may have been with some backend resource.
