### ISSUE TITLE
How to associate a certificate with an existing service principal

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-cli#5176]
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
pip/2.0.21/ubuntu/bash
```

I have a service principal with password, say the appId is A. After running [`az ad sp create-for-rbac --name A --create-cert`](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest), what I expect is to add a cert to the existing SP whose appId is A.
But the command creates a new SP for me.
It seems that Azure CLI 1.0's behavior is what I expected. But now I can't find the docs any longer.

**Comment by yugangw-msft** [comment]
For Cli 2.0. please use `az ad sp reset-credentials --apend`

**Comment by bingosummer** [comment]
Thanks. After upgrading to `2.0.23`, I can use the option `--append` to append a new credential.

**Comment by pallavichede** [comment]
I have similar requirement but I want to achieve this using logic app but I am not able to upload certificate to existing service principle .
