### ISSUE TITLE
az configure common arguments

### ISSUE THREAD

**Issue by olandese** [Azure/azure-cli#5177]
it would be nice to have more detailed documentation about which are the common arguments (a list?) to be used with az configure --defaults

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47dd5c85-9d6d-f55e-4632-0e5bfc179657
* Version Independent ID: 84e585d1-2480-b14f-5b8d-c143e3fbd532
* [Content](https://docs.microsoft.com/en-us/cli/azure/?view=azure-cli-latest#feedback)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_help.py)

**Comment by yugangw-msft** [comment]
//cc: @sptramer

**Comment by yugangw-msft** [comment]
AFAIK, there are at least 6 can be configured with defaults, including `group`, `location`, `web`, `vm`, `vmss` and `acs`. Those configurable information will also show up in the help, say when you type `az acs show -h`, the output will mention them:
```
(env) d:\sdk\azure-cli>az acs show -h

Command
    az acs show: Get the details for a container service.

Arguments
    --name -n           [Required]: Name of the container service. You can configure the default
                                    using `az configure --defaults acs=<name>`.
    --resource-group -g [Required]: Name of resource group. You can configure the default group
                                    using `az configure --defaults group=<name>`.
```

**Comment by sptramer** [comment]
This documentation is available online:

https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest

The engineering team is responsible for maintaining a correct and accurate list of settings in the reference documentation. I had to data-mine the CLI to find these settings on my own.

**Comment by yugangw-msft** [comment]
@sptramer, okay, we will try to keep it up to date and thanks for the documenting
