### ISSUE TITLE
az vm create fails with http 404

### ISSUE THREAD

**Issue by gatneil** [Azure/azure-cli#5179]
---

When I try to do an `az vm create --resource-group env23908 --name env23908 --image Canonical:UbuntuServer:16.04-LTS:latest`, I get an HTTP 404 Not Found error. The resource group exists, and the debug output shows that the CLI found the resource group, so I'm not sure what resource the 404 is referring to...

### Environment summary

Install Method: interactive script
OS version: Ubuntu 16.04-LTS
CLI version(s):

$ az --version
azure-cli (2.0.23)

acr (2.0.17)
acs (2.0.22)
advisor (0.1.0)
appservice (0.1.22)
backup (1.0.3)
batch (3.1.7)
batchai (0.1.3)
billing (0.1.6)
cdn (0.0.10)
cloud (2.0.10)
cognitiveservices (0.1.9)
command-modules-nspkg (2.0.1)
configure (2.0.12)
consumption (0.2.0)
container (0.1.15)
core (2.0.23)
cosmosdb (0.1.15)
dla (0.0.15)
dls (0.0.18)
eventgrid (0.1.5)
extension (0.0.6)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.11)
iot (0.1.15)
keyvault (2.0.15)
lab (0.0.13)
monitor (0.0.13)
network (2.0.19)
nspkg (3.0.1)
profile (2.0.16)
rdbms (0.0.9)
redis (0.2.10)
reservations (0.1.0)
resource (2.0.19)
role (2.0.15)
servicefabric (0.0.7)
sql (2.0.17)
storage (2.0.21)
vm (2.0.20)

Python location '/home/negat/lib/azure-cli/bin/python'
Extensions directory '/home/negat/.azure/cliextensions'

Python (Linux) 2.7.12 (default, Nov 20 2017, 18:23:56)
[GCC 5.4.0 20160609]

### COMMANDS RUN

$ az group create -l westus -n env23908
{
  "id": "/subscriptions/<sub-id>/resourceGroups/env23908",
  "location": "westus",
  "managedBy": null,
  "name": "env23908",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null
}

$ az vm create --resource-group env23908 --name env23908 --image Canonical:UbuntuServer:16.04-LTS:latest --debug
Command arguments ['vm', 'create', '--resource-group', 'env23908', '--name', 'env23908', '--image', 'Canonical:UbuntuServer:16.04-LTS:latest']
Current cloud config:
{'endpoints': {'active_directory': 'https://login.microsoftonline.com',
               'active_directory_data_lake_resource_id': 'https://datalake.azure.net/',
               'active_directory_graph_resource_id': 'https://graph.windows.net/',
               'active_directory_resource_id': 'https://management.core.windows.net/',
               'batch_resource_id': 'https://batch.core.windows.net/',
               'gallery': 'https://gallery.azure.com/',
               'management': 'https://management.core.windows.net/',
               'resource_manager': 'https://management.azure.com/',
               'sql_management': 'https://management.core.windows.net:8443/',
               'vm_image_alias_doc': 'https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json'},
 'is_active': True,
 'name': 'AzureCloud',
 'profile': 'latest',
 'suffixes': {'azure_datalake_analytics_catalog_and_job_endpoint': 'azuredatalakeanalytics.net',
              'azure_datalake_store_file_system_endpoint': 'azuredatalakestore.net',
              'keyvault_dns': '.vault.azure.net',
              'sql_server_hostname': '.database.windows.net',
              'storage_endpoint': 'core.windows.net'}}
Registered application event handler 'CommandTableParams.Loaded' at <function add_id_parameters at 0x7f10a613e410>
Registered application event handler 'CommandTable.Loaded' at <function add_id_parameters at 0x7f10a613e410>
Successfully loaded command table from module 'vm'.
Extensions directory: '/home/negat/.azure/cliextensions'
Application event 'CommandTable.Loaded' with event data {'command_table': {'vm create': <azure.cli.core.commands.CliCommand object at 0x7f10a6189e90>}}
Application event 'CommandParser.Loaded' with event data {'parser': AzCliCommandParser(prog='az', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)}
Application event 'CommandTableParams.Loaded' with event data {'command_table': {'vm create': <azure.cli.core.commands.CliCommand object at 0x7f10a6189e90>}}
Application event 'CommandParser.Parsing' with event data {'argv': ['vm', 'create', '--resource-group', 'env23908', '--name', 'env23908', '--image', 'Canonical:UbuntuServer:16.04-LTS:latest']}
Application event 'CommandParser.Parsed' with event data {'args': Namespace(_command_package='vm', _jmespath_query=None, _log_verbosity_debug=False, _log_verbosity_verbose=False, _output_format='json', _parser=AzCliCommandParser(prog='az vm create', usage=None, description='', version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True), _validators=[<function process_vm_create_namespace at 0x7f10a4f45668>, <function validate_tags at 0x7f10a4f2ce60>, <function validate_asg_names_or_ids at 0x7f10a4f4b75 [...]
Getting management service client client_type=ResourceManagementClient
attempting to read file /home/negat/.azure/accessTokens.json as utf-8-sig
adal-python : a99d767c-9200-4158-ac49-26d4dd693969 - Authority:Performing instance discovery: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47
adal-python : a99d767c-9200-4158-ac49-26d4dd693969 - Authority:Performing static instance discovery
adal-python : a99d767c-9200-4158-ac49-26d4dd693969 - Authority:Authority validated via static instance discovery
adal-python : a99d767c-9200-4158-ac49-26d4dd693969 - TokenRequest:Getting token with client credentials.
adal-python : a99d767c-9200-4158-ac49-26d4dd693969 - TokenRequest:No user_id passed for cache query
adal-python : a99d767c-9200-4158-ac49-26d4dd693969 - OAuth2Client:finding with query: {"_clientId": "0dbd7d20-c6d9-4694-850d-36e68b797903"}
adal-python : a99d767c-9200-4158-ac49-26d4dd693969 - OAuth2Client:Looking for potential cache entries:
adal-python : a99d767c-9200-4158-ac49-26d4dd693969 - OAuth2Client:{"_clientId": "0dbd7d20-c6d9-4694-850d-36e68b797903"}
adal-python : a99d767c-9200-4158-ac49-26d4dd693969 - OAuth2Client:Found 0 potential entries.
urllib3.connectionpool : Starting new HTTPS connection (1): login.microsoftonline.com
urllib3.connectionpool : https://login.microsoftonline.com:443 "POST /72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token HTTP/1.1" 200 1376
adal-python : a99d767c-9200-4158-ac49-26d4dd693969 - OAuth2Client:Get Token Server returned this correlation_id: a99d767c-9200-4158-ac49-26d4dd693969
adal-python : a99d767c-9200-4158-ac49-26d4dd693969 - OAuth2Client:Adding entry AccessTokenId: upGs8xckEhKCDyLZZ6pdL4XAEBwlOhjImI94ZFz3fy4=
adal-python : a99d767c-9200-4158-ac49-26d4dd693969 - OAuth2Client:Added entry is MRRT
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring proxies: ''
msrest.pipeline : Evaluate proxies against ENV settings: True
msrest.pipeline : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com
urllib3.connectionpool : https://management.azure.com:443 "GET /subscriptions/5a810961-5236-4bbd-b50a-bda258eb00c0/resourcegroups/env23908?api-version=2017-05-10 HTTP/1.1" 200 257
msrest.http_logger : Request URL: 'https://management.azure.com/subscriptions/5a810961-5236-4bbd-b50a-bda258eb00c0/resourcegroups/env23908?api-version=2017-05-10'
msrest.http_logger : Request method: 'GET'
msrest.http_logger : Request headers:
msrest.http_logger :     'Connection': 'keep-alive'
msrest.http_logger :     'Accept-Encoding': 'gzip, deflate'
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'User-Agent': 'python/2.7.12 (Linux-4.11.0-1011-azure-x86_64-with-Ubuntu-16.04-xenial) requests/2.18.4 msrest/0.4.23 msrest_azure/0.4.19 resourcemanagementclient/1.2.1 Azure-SDK-For-Python AZURECLI/2.0.23'
msrest.http_logger :     'Authorization': '*****'
msrest.http_logger :     'x-ms-client-request-id': '51804942-ec22-11e7-9f3a-000d3a30e032'
msrest.http_logger :     'CommandName': 'vm create'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger : Request body:
msrest.http_logger : None
msrest.http_logger : Response status: 200
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Content-Encoding': 'gzip'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'Vary': 'Accept-Encoding'
msrest.http_logger :     'x-ms-ratelimit-remaining-subscription-reads': '14999'
msrest.http_logger :     'x-ms-request-id': '3f206f8f-5a3e-4f18-857a-e0802b0d48e2'
msrest.http_logger :     'x-ms-correlation-request-id': '3f206f8f-5a3e-4f18-857a-e0802b0d48e2'
msrest.http_logger :     'x-ms-routing-request-id': 'WESTUS:20171228T225620Z:3f206f8f-5a3e-4f18-857a-e0802b0d48e2'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'Date': 'Thu, 28 Dec 2017 22:56:19 GMT'
msrest.http_logger :     'Content-Length': '257'
msrest.http_logger : Response content:
msrest.http_logger : {"id":"/subscriptions/5a810961-5236-4bbd-b50a-bda258eb00c0/resourceGroups/env23908","name":"env23908","location":"westus","properties":{"provisioningState":"Succeeded"}}
using location 'westus' from resource group 'env23908'
usage: az vm create [-h] [--output {json,tsv,table,jsonc}] [--verbose]
                    [--debug] [--query JMESPATH]
                    [--data-disk-caching {None,ReadOnly,ReadWrite}]
                    [--assign-identity [ASSIGN_IDENTITY [ASSIGN_IDENTITY ...]]]
                    [--public-ip-address-dns-name PUBLIC_IP_ADDRESS_DNS_NAME]
                    [--scope IDENTITY_SCOPE] [--image IMAGE] [--no-wait]
                    [--storage-sku {Premium_LRS,Standard_GRS,Standard_LRS,Standard_RAGRS,Standard_ZRS}]
                    [--nsg NSG] [--os-disk-name OS_DISK_NAME]
                    [--storage-container-name STORAGE_CONTAINER_NAME]
                    [--validate] [--size SIZE] [--subnet SUBNET]
                    [--availability-set AVAILABILITY_SET]
                    [--nsg-rule {RDP,SSH}] [--zone {1,2,3}]
                    [--attach-data-disks ATTACH_DATA_DISKS [ATTACH_DATA_DISKS ...]]
                    [--nics NICS [NICS ...]]
                    [--authentication-type {ssh,password}]
                    [--admin-password ADMIN_PASSWORD] [--plan-name PLAN_NAME]
                    [--attach-os-disk ATTACH_OS_DISK] [--location LOCATION]
                    --name NAME [--public-ip-address PUBLIC_IP_ADDRESS]
                    [--vnet-name VNET_NAME] [--tags [TAGS [TAGS ...]]]
                    [--ssh-key-value SSH_KEY_VALUE]
                    [--data-disk-sizes-gb DATA_DISK_SIZES_GB [DATA_DISK_SIZES_GB ...]]
                    [--license-type {Windows_Server,Windows_Client}]
                    [--storage-caching {ReadOnly,ReadWrite}]
                    [--storage-account STORAGE_ACCOUNT]
                    [--asgs APPLICATION_SECURITY_GROUPS [APPLICATION_SECURITY_GROUPS ...]]
                    [--use-unmanaged-disk] [--generate-ssh-keys]
                    [--os-disk-size-gb OS_DISK_SIZE_GB]
                    [--plan-product PLAN_PRODUCT]
                    [--subnet-address-prefix SUBNET_ADDRESS_PREFIX]
                    --resource-group RESOURCE_GROUP_NAME
                    [--public-ip-address-allocation {dynamic,static}]
                    [--secrets SECRETS [SECRETS ...]]
                    [--plan-publisher PLAN_PUBLISHER] [--role IDENTITY_ROLE]
                    [--admin-username ADMIN_USERNAME]
                    [--ssh-dest-key-path SSH_DEST_KEY_PATH]
                    [--plan-promotion-code PLAN_PROMOTION_CODE]
                    [--vnet-address-prefix VNET_ADDRESS_PREFIX]
                    [--custom-data CUSTOM_DATA]
                    [--private-ip-address PRIVATE_IP_ADDRESS]
                    [--os-type {windows,linux}]
az vm create: error: HTTP Error 404: Not Found

**Comment by johanste** [comment]
The issue should have been resolved. We intend to make sure that we are more resilient to this problem.

**Comment by gatneil** [comment]
Groovy :)

**Comment by gatneil** [comment]
@johanste what was the underlying issue? @yugangw-msft as FYI :)

**Comment by johanste** [comment]
A reorganization of the rest api specs repository moved the default image alias file to a new location.


Sent from Outlook<http://aka.ms/weboutlook>


________________________________
