### ISSUE TITLE
a typing error "--custom_data". it must be "--custom-data"

### ISSUE THREAD

**Issue by skatpgusskat** [Azure/azure-cli#5194]
here, "az vm create -g MyResourceGroup -n MyVm --image debian --custom_data MyCloudInitScript.yml". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 152b549b-d4b3-13e5-081c-c604b6e4d89e
* Version Independent ID: 3f79be78-ce75-ad31-304b-bad7d475ec9e
* [Content](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az_vm_create)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)

**Comment by yugangw-msft** [comment]
I think the current error is reasonable `az: error: unrecognized arguments: --custom_data MyCloudInitScript.yml`. If you prefer `--custom_data` be accepted as well, then this would be pretty subjective. Consider it is the basic python argparse behavior, I suggest we live with it.

**Comment by skatpgusskat** [comment]
@yugangw-msft what? I’m sorry but i never said i prefer `—custom_data`.

 I mean, in document, It is written as `custom-data` for right argument but they wrote `custom_data` in example.

**Comment by tjprescott** [comment]
@skatpgusskat thanks for pointing this out!  We'll get the example fixed up.
