### ISSUE TITLE
[Design] The return type of get_api_version and supported_api_version is not homogeneous

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#5195]
The return type used to be `str` for `get_api_version` and `bool` for `supported_api_version`. However it gets complicated after #4983 introduces operation group api version. Both functions will return a `namedtuple` (later changed to `_ApiVersion` by me for performance reason) when the specific command module supported `SDKProfile`.

It makes the API misleading and confusing. For example,
```
if self.supported_api_version(...):
    pass
```
Above condition will always render `True` for compute SDK because it returns an instance now. The consumer of the APIs need to take care of the type before the test the condition.

It is a bad design.

Following is a PR intends to address the issue:
https://github.com/Azure/azure-cli/pull/5167

**Comment by yugangw-msft** [comment]
No a critical item and we have no resources on this
