### ISSUE TITLE
Table Transformer Formatting Issue With Long Strings

### ISSUE THREAD

**Issue by dragonfly91** [Azure/azure-cli#5221]
Table transformer spills long strings instead of doing a "word wrap".

In this case, the Recommendations column contains long text and the width of this column is as long as the text itself. The width of the columns should have an upper limit and the text inside the column should be wrapped.

![image](https://user-images.githubusercontent.com/1173819/34665753-6f7cd7d6-f487-11e7-8d5c-393765326c65.png)

---

### Environment summary

```
Install Method: dev setup
CLI Version: 2.0.24
OS Version: Windows 10 Enterprise 1709
Shell Type: cmd.exe
```

**Comment by JasonRShaver** [comment]
We're aware of cases where this presents some hard to use UX, but after talking with customers about specific fixes and their side-effects, this has not hit our bar.  If you have more user data or comments, please let us know.
