### ISSUE TITLE
pip install of previous version is now broken

### ISSUE THREAD

**Issue by mboersma** [Azure/azure-cli#5223]
Somehow older version(s) of `az` are now broken for `pip install`:
```
$ python3 -m venv venv
$ . ./venv/bin/activate
$ pip install azure-cli 2.0.23
...
$ az --version
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/private/tmp/venv/lib/python3.6/site-packages/azure/cli/__main__.py", line 9, in <module>
    import azure.cli.main
  File "/private/tmp/venv/lib/python3.6/site-packages/azure/cli/main.py", line 9, in <module>
    from azure.cli.core import configure_logging, get_az_logger
ImportError: cannot import name 'configure_logging'
```

Perhaps something in az core wasn't pinned to an explicit version, so we're pulling in a new, incompatible one accidentally?

This makes coming up with a workaround for #5218 difficult.

**Comment by derekbekoe** [comment]
`pip install azure-cli==2.0.23` would still pull down the latest of everything else as all the command modules are separate packages.

You should be able to install like this:
`pip install -r https://gist.githubusercontent.com/derekbekoe/4e60d38f6243ab60cff41ad269cbf0ba/raw/aa7caf587892cc08d6ca3cb7cb85f7dc4b798cfa/azure-cli-2.0.23.txt`
That seemed to work for me.

This is how I created the requirements file.
```
docker run -it azuresdk/azure-cli-python:2.0.23
pip freeze > requirements.txt
```

**Comment by derekbekoe** [comment]
Closing as the above should address your issue and it never worked that way to begin with.

**Comment by mboersma** [comment]
@derekbekoe understood, I just hadn't realized `pip install azure-cli` wasn't officially supported, but now that I re-read [our install docs](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest) I see we don't mention `pip install`. We must have gotten lucky up until now. :-)

**Comment by derekbekoe** [comment]
Yeah `pip install azure-cli` works best for the 'latest' CLI version.
The requirements.txt may be a solution for you if you still want to install with pip.

**Comment by IainColledge** [comment]
It would be good if pip worked that way as for example there seems to be no other way to install 2.0.23 into Stretch using a Dockerfile, the apt-get method has a clash with .Net Core CLI with openssl versions.

**Comment by raykao** [comment]
I've just created a repo with the past versions: https://github.com/OSSCanada/azure-cli-requirements

We've run workshops where the latest version has broken some commands...

**Comment by lostinthecloud** [comment]
@raykao By chance do you have more recent requirements for newer versions, such as 2.0.27, 2.0.28, and 2.0.29, and do you intend to keep publishing version requirements to the above repo? Or is there another source to get the correct requirements to install versions with pip?

**Comment by derekbekoe** [comment]
We now publish versioned Docker images to `microsoft/azure-cli`.

https://hub.docker.com/r/microsoft/azure-cli/tags/

**Comment by lostinthecloud** [comment]
@derekbekoe thanks for the clarification. Doing `pip freeze` works for getting the requirements with `microsoft/azure-cli` in case others may be wondering about requirements for specific versions.

**Comment by justinmchase** [comment]
`pip freeze` does not emit extensions. Any advice on how to get the complete list of all pip modules?
