### ISSUE TITLE
Example for az webapp deployment source config-local-git

### ISSUE THREAD

**Issue by krishnaji** [Azure/azure-cli#5224]
The example with correct command options  
az webapp  deployment source config-local-git  -g MyResourceGroup -n MyUniqueApp                        
git remote add azure     https://<deploy_user_name>@MyUniqueApp.scm.azurewebsites.net/MyUniqueApp.git

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b238907f-0676-8e20-66ac-89a542aa8c20
* Version Independent ID: 60659c33-bfea-eecb-6681-9240191820be
* [Content](https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/source?view=azure-cli-latest#az_webapp_deployment_source_config_local_git)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/webapp/deployment/source.yml)

**Comment by ncacace** [comment]
az webapp deployment source config-local-git -g myResourceName -n myAppName
ERROR!!!!  AttributeError: 'NoneType' object has no attribute 'location'
FFS!!!

**Comment by williexu** [comment]
Example was fixed with https://github.com/Azure/azure-cli/commit/c9fe2efc878a45fdefaec59d42ab7e47912fba24
