### ISSUE TITLE
az monitor diagnostic-setting - cannot list diagnostic settings for a resource

### ISSUE THREAD

**Issue by iamrobdavies** [Azure/azure-cli#5240]
### Issue Summary
Az CLI cannot list diagnostic settings for a resource

I want to list all of the diagnostic settings for a given resource.  For example, valid PowerShell shows all diagnostic settings for a given resource:
``` Get-AzureRmDiagnosticSetting -ResourceId "{resourceId}" ```

With az CLI, both **az monitor diagnostic-settings show** and **az monitor diagnostic-settings update** require the **--name** argument. Without the ability to list all of the configured diagnostic settings for a resource, I am unable to populate the --name argument.  

``` az monitor diagnostic-settings update --resource-id {resourceId}  --name service ```

### Request
Please add an ``` az monitor diagnostic-settings list ``` 

### Environment summary
Bash on Windows: azure-cli (2.0.24) 
and cloud shell: azure-cli (2.0.23)

**Comment by troydai** [comment]
/home/troy/code/azure-cli/src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/tests/test_monitor_diagnostic_settings.py

**Comment by troydai** [comment]
#5242

**Comment by troydai** [comment]
Fixed in https://github.com/Azure/azure-cli/pull/5242
