### ISSUE TITLE
az monitor diagnostic-settings create - failing

### ISSUE THREAD

**Issue by iamrobdavies** [Azure/azure-cli#5241]
### Issue Summary
Unable to use ```az monitor diagnostic-settings create``` as always fails with the error:
 ```--resource-group is required when name is provided for storage account or workspace or service bus namespace and rule.```

This is failing even when the **`--resource-group** argument is supplied correctly.

**Example 1:** 
```az monitor diagnostic-settings create --resource-id {resourceId} --name diag --storage-account {storageAccountResourceId} --resource-group lb-tests```

```--resource-group is required when name is provided for storage account or workspace or service bus namespace and rule.```

**Example 2:**
```az monitor diagnostic-settings create --resource-id {resourceId} --name diag --storage-account {storageAccountResourceId} --resource-group lb-tests --metrics @metrics.json --logs @logs.json --verbose```

```--resource-group is required when name is provided for storage account or workspace or service bus namespace and rule.```
 

### Environment summary
Bash on Windows: azure-cli (2.0.24)
and cloud shell: azure-cli (2.0.23)

**Comment by troydai** [comment]
Thanks for reporting. Just open this PR #5242  to fix this issue.

**Comment by troydai** [comment]
Fixed in https://github.com/Azure/azure-cli/pull/5242
