### ISSUE TITLE
az vm list-sizes shows incorrect vcpu counts for constrained machines

### ISSUE THREAD

**Issue by ranieuwe** [Azure/azure-cli#5243]
In the case of the new SKUs with lower vCPU counts than the original SKU (e.g. m128-32) the number of cores listed is wrong: in my example it [should be 32, instead of 128](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/constrained-vcpu).

Output as follows:

```
                64       1792000  Standard_M64-16ms                    64           1047552                 2048000
                64       1792000  Standard_M64-32ms                    64           1047552                 2048000
                64       1792000  Standard_M64ms                       64           1047552                 2048000
                64       1024000  Standard_M64s                        64           1047552                 2048000
                64       3891200  Standard_M128-32ms                  128           1047552                 4096000
                64       3891200  Standard_M128-64ms                  128           1047552                 4096000
                64       3891200  Standard_M128ms                     128           1047552                 4096000
                64       2048000  Standard_M128s                      128           1047552                 4096000
```

This is also the case for the Ev3 series. This may be a REST API bug in that the wrong JSON is returned instead of a CLI bug.

---

C:\Users\ronieuwe>az --version
azure-cli (2.0.20)

acr (2.0.14)
acs (2.0.18)
appservice (0.1.19)
backup (1.0.2)
batch (3.1.6)
batchai (0.1.2)
billing (0.1.6)
cdn (0.0.10)
cloud (2.0.9)
cognitiveservices (0.1.9)
command-modules-nspkg (2.0.1)
component (2.0.8)
configure (2.0.12)
consumption (0.1.6)
container (0.1.12)
core (2.0.20)
cosmosdb (0.1.14)
dla (0.0.13)
dls (0.0.16)
eventgrid (0.1.5)
extension (0.0.5)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.11)
iot (0.1.13)
keyvault (2.0.13)
lab (0.0.12)
monitor (0.0.11)
network (2.0.17)
nspkg (3.0.1)
profile (2.0.15)
rdbms (0.0.8)
redis (0.2.10)
resource (2.0.17)
role (2.0.14)
servicefabric (0.0.5)
sql (2.0.14)
storage (2.0.18)
vm (2.0.17)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\ronieuwe\.azure\cliextensions'

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

**Comment by yugangw-msft** [comment]
@ranieuwe, let me clarify with the compute service team and get back to you

**Comment by shivankar-madaan** [comment]
Hi Team,
I am facing a similar kind of issue
`az vm list` shows a wrong output with respect to `virtualMachineExtensionType`(getting is as,set to "null") in json body
But if I hit
` az vm show -g <resource-group>-n <VM-name> --query resources[*]`
I get the right resutls

Please let me know,if I am supposed to create a new issue for this

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
