### ISSUE TITLE
webapp: use right 'kind' to filter away non webapp ones

### ISSUE THREAD

**Issue by FinVamp1** [Azure/azure-cli#5244]
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

currently using version 2.0.23 via Azure Cloud Console.

```
For Azure App Service customers can set the kind attribute via ARM Templates and there are some issues where it may be missing although the resource itself is not affected by this.

 @panchagnula can help with how the Portal for Azure App Service handles this situation.

This issue was raised by a customer where az webapp list | grep webAppName did not list their applications because the kind property was missing. 
```

**Comment by ahmedelnably** [comment]
We did a backend change in App Service to normalize the kind property, @panchagnula & @yugangw-msft we need to make sure that CLI handles that change.

**Comment by yugangw-msft** [comment]
@ahmedelnably, please elaborate. You mean we should check more app kind after the backend normalization work? Or maybe we should not filter based on the `kind` in `az webapp list/show` at all? Till `az functionapp` came up, CLI never filters on `kind`; but the filtering logics has been broken a few times per back end change.
And there is a StackOverflow thread for this `https://stackoverflow.com/questions/47563717/azure-cli-returns-an-incomplete-list-of-webapps/47587429`

**Comment by panchagnula** [comment]
@ahmedelnably  please create a new issue with more details on what exactly is needed here, if this is something we still need to work on. thanks!
