### ISSUE TITLE
list available service kinds

### ISSUE THREAD

**Issue by guybartal** [Azure/azure-cli#5246]
Hi, there's a missing functionality for listing available cognitive kinds... how do we know which kind is available and on which region it's available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60024e5-9f73-a991-c699-b334287845d2
* Version Independent ID: 452c87e7-a404-0f3c-8520-c13ef8c789c4
* [Content](https://docs.microsoft.com/en-us/cli/azure/cognitiveservices?view=azure-cli-latest)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-cognitiveservices/azure/cli/command_modules/cognitiveservices/_help.py)

**Comment by tjprescott** [comment]
Which command are you referring to?

**Comment by jfellien** [comment]
For example `az cognitiveservices list --kind` or something like that. We as your customer want's to know how to use the CLI API ;-)

**Comment by MaximRouiller** [comment]
Any updates on this?

**Comment by tjprescott** [comment]
@yangyuan

**Comment by yangyuan** [comment]
I am working on it, targeting Sprint 45.
Will have a command like `az cognitiveservices account list-kinds` which returns a list of valid `kinds`

**Comment by MaximRouiller** [comment]
Thank you so much for the update @yangyuan! 

I appreciate it!
