### ISSUE TITLE
Run Azure CLI with self-signed cert

### ISSUE THREAD

**Issue by Anshapar** [Azure/azure-cli#5258]
Environment summary

CLI version azure-cli (2.0.22)
OS Type: Windows 10
Installation via: apt-get for Bash on Ubuntu on Windows

I am trying to create VM using the following command:
az vm create --resource-group anshitagroup --name myVM --location westeurope --nics myNic --image win2016datacenter --adm
in-username ramarao@revskope.onmicrosoft.com --admin-password password

And I am getting the following error:
usage: az vm create [-h] [--output {json,tsv,table,jsonc}] [--verbose]
                    [--debug] [--query JMESPATH]
                    [--data-disk-caching {None,ReadOnly,ReadWrite}]
                    [--assign-identity [ASSIGN_IDENTITY [ASSIGN_IDENTITY ...]]]
                    [--public-ip-address-dns-name PUBLIC_IP_ADDRESS_DNS_NAME]
                    [--scope IDENTITY_SCOPE] [--image IMAGE] [--no-wait]
                    [--storage-sku {Premium_LRS,Standard_GRS,Standard_LRS,Standard_RAGRS,Standard_ZRS}]
                    [--nsg NSG] [--os-disk-name OS_DISK_NAME]
                    [--storage-container-name STORAGE_CONTAINER_NAME]
                    [--validate] [--size SIZE] [--subnet SUBNET]
                    [--availability-set AVAILABILITY_SET]
                    [--nsg-rule {RDP,SSH}] [--zone {1,2,3}]
                    [--attach-data-disks ATTACH_DATA_DISKS [ATTACH_DATA_DISKS ...]]
                    [--nics NICS [NICS ...]]
                    [--authentication-type {ssh,password}]
                    [--admin-password ADMIN_PASSWORD] [--plan-name PLAN_NAME]
                    [--attach-os-disk ATTACH_OS_DISK] [--location LOCATION]
                    --name NAME [--public-ip-address PUBLIC_IP_ADDRESS]
                    [--vnet-name VNET_NAME] [--tags [TAGS [TAGS ...]]]
                    [--ssh-key-value SSH_KEY_VALUE]
                    [--data-disk-sizes-gb DATA_DISK_SIZES_GB [DATA_DISK_SIZES_GB ...]]
                    [--license-type {Windows_Server,Windows_Client}]
                    [--storage-caching {ReadOnly,ReadWrite}]
                    [--storage-account STORAGE_ACCOUNT]
                    [--asgs APPLICATION_SECURITY_GROUPS [APPLICATION_SECURITY_GROUPS ...]]
                    [--use-unmanaged-disk] [--generate-ssh-keys]
                    [--os-disk-size-gb OS_DISK_SIZE_GB]
                    [--plan-product PLAN_PRODUCT]
                    [--subnet-address-prefix SUBNET_ADDRESS_PREFIX]
                    --resource-group RESOURCE_GROUP_NAME
                    [--public-ip-address-allocation {dynamic,static}]
                    [--secrets SECRETS [SECRETS ...]]
                    [--plan-publisher PLAN_PUBLISHER] [--role IDENTITY_ROLE]
                    [--admin-username ADMIN_USERNAME]
                    [--ssh-dest-key-path SSH_DEST_KEY_PATH]
                    [--plan-promotion-code PLAN_PROMOTION_CODE]
                    [--vnet-address-prefix VNET_ADDRESS_PREFIX]
                    [--custom-data CUSTOM_DATA]
                    [--private-ip-address PRIVATE_IP_ADDRESS]
                    [--os-type {windows,linux}]
az vm create: error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

Azure Version details:
azure-cli (2.0.23)

acr (2.0.17)
acs (2.0.22)
advisor (0.1.0)
appservice (0.1.22)
backup (1.0.3)
batch (3.1.7)
batchai (0.1.3)
billing (0.1.6)
cdn (0.0.10)
cloud (2.0.10)
cognitiveservices (0.1.9)
command-modules-nspkg (2.0.1)
configure (2.0.12)
consumption (0.2.0)
container (0.1.15)
core (2.0.23)
cosmosdb (0.1.15)
dla (0.0.15)
dls (0.0.18)
eventgrid (0.1.5)
extension (0.0.6)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.11)
iot (0.1.15)
keyvault (2.0.15)
lab (0.0.13)
monitor (0.0.13)
network (2.0.19)
nspkg (3.0.1)
profile (2.0.16)
rdbms (0.0.9)
redis (0.2.10)
reservations (0.1.0)
resource (2.0.19)
role (2.0.15)
servicefabric (0.0.7)
sql (2.0.17)
storage (2.0.21)
vm (2.0.20)

Python location '/usr/bin/python'
Extensions directory '/home/anshita/.azure/cliextensions'

Python (Linux) 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609]

**Comment by Anshapar** [comment]
I am using Azure CLI with self-signed certificate.

**Comment by yugangw-msft** [comment]
//CC:@derekbekoe 
I believe, you can use the environment variable `REQUESTS_CA_BUNDLE` to point to your own cert

**Comment by derekbekoe** [comment]
Seems the same as this?
https://github.com/Azure/azure-cli/issues/5099

**Comment by derekbekoe** [comment]
The code to handle this is here (https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/_debug.py#L18).
Is the cert correct? Could there be something else in your environment affecting this?

**Comment by Anshapar** [comment]
I tried with pointing REQUESTS_CA_BUNDLE to my cert but the error still persists. If I set ADAL_PYTHON_SSL_NO_VERIFY=1 and AZURE_CLI_DISABLE_CONNECTION_VERIFICATION=1 then other commands are working fine but I am not able to create VM.

**Comment by yugangw-msft** [comment]
@Anshapar, I will try out myself and get back to you the end to end instructions
