### ISSUE TITLE
DNS exports are relative, but include full domain name (missing a dot or omit full domain)

### ISSUE THREAD

**Issue by sigiklu** [Azure/azure-cli#5259]
It looks like that **az network dns zone export** is exporting a zone with each record appended by the zone name, however not ending with a . (signalling it's an absolute/fully qualified entry). 

Using the example from pull request #2040, if i exported the DNS record for mycname in zone1.com, this is the exported result ($ORIGIN zone1.com.): 
`mycname.zone1.com 3600 IN CNAME contoso.com.`

However, missing the dot this could mean that it is treated as a relative record, and will then - fully qualified - be interpreted as mycname.zone1.com.zone1.com. This is also true when I import that same zone file/record with **az network dns zone import** (it will create a new record instead of updating an existing one): 
`mycname.zone1.com.zone1.com 3600 IN CNAME contoso.com.`

In that sense, there might be two exports that should/might work (not sure about the exact interpretation rules within the az command): 
fully qualified: `mycname.zone1.com. 3600 IN CNAME contoso.com.`
relative to $ORIGIN: `mycname 3600 IN CNAME contoso.com.`

---

### Environment summary

Azure CLI 2.0 on Windows 10.

**Comment by tjprescott** [comment]
Thanks for the report @sigiklu. I'll take a look.

**Comment by tjprescott** [comment]
What do you get when you run `az --version`?

**Comment by tjprescott** [comment]
I just tested this on a DNS zone and it appears to work fine:

```
; Exported zone file from Azure DNS
;      Zone name: tjpzone1.com
;      Resource Group Name: tjp-dns
;      Date and time (UTC): Fri, 12 Jan 2018 16:41:02 -0800

$TTL 300
$ORIGIN tjpzone1.com.

@ 3600 IN SOA ns1-07.azure-dns.com. azuredns-hostmaster.microsoft.com. (
              1 ; serial
              3600 ; refresh
              300 ; retry
              2419200 ; expire
              300 ; minimum
              )

  172800 IN NS ns1-07.azure-dns.com.
  172800 IN NS ns2-07.azure-dns.net.
  172800 IN NS ns3-07.azure-dns.org.
  172800 IN NS ns4-07.azure-dns.info.

mycname 3600 IN CNAME blahblah

txtrecords 3600 IN TXT "My lalala"
```

**Comment by tjprescott** [comment]
If I do a round-trip export > import > export I get the same results each time. You may be using an outdated version of the CLI.  If you can replicate on version 2.0.24 or higher, please reopen.

**Comment by sigiklu** [comment]
Hey, 

sorry for the delay - I have been away from my computer the past few days. 

**az --version is azure-cli (2.0.24).** 

This is what my process looks/looked like with your test data (except the resource group, that I changed) - maybe I am doing something wrong? 

I started off with a zone file, containing your zone (plus an additional outside CNAME, just to have that included): 

**test.zone:** 
``` 
; Exported zone file from Azure DNS
;      Zone name: tjpzone1.com
;      Resource Group Name: my-domains
;      Date and time (UTC): Fri, 12 Jan 2018 16:41:02 -0800

$TTL 300
$ORIGIN tjpzone1.com.

@ 3600 IN SOA ns1-07.azure-dns.com. azuredns-hostmaster.microsoft.com. (
              1 ; serial
              3600 ; refresh
              300 ; retry
              2419200 ; expire
              300 ; minimum
              )

  172800 IN NS ns1-07.azure-dns.com.
  172800 IN NS ns2-07.azure-dns.net.
  172800 IN NS ns3-07.azure-dns.org.
  172800 IN NS ns4-07.azure-dns.info.

myAname 3600 IN A 127.0.0.1

mycname 3600 IN CNAME blahblah

outsidecname 3600 IN CNAME www.example.com.

txtrecords 3600 IN TXT "My lalala"
```

I imported this file using using ` az network dns zone import -f test.zone -g my-domains -n tjpzone1.com`, which worked fine: a new zone was created, all entries are there (below azure panel screenshot) ![zone import after first round](https://user-images.githubusercontent.com/35297614/35104257-94adcb8a-fc68-11e7-869f-9eb7f1f8e501.png)

Then I exported this zone with `az network dns zone export -n tjpzone1.com -g my-domains > test-export.zone`, with the following output: 

**test-export.zone:**
``` 
; Exported zone file from Azure DNS
;      Zone name: tjpzone1.com
;      Resource Group Name: my-domains
;      Date and time (UTC): Thu, 18 Jan 2018 16:16:17 +0100

$TTL 300
$ORIGIN tjpzone1.com.
    
@ 3600 IN SOA ns1-02.azure-dns.com. azuredns-hostmaster.microsoft.com. (
              1 ; serial
              3600 ; refresh
              300 ; retry
              2419200 ; expire
              300 ; minimum
              )

  172800 IN NS ns1-02.azure-dns.com.
  172800 IN NS ns2-02.azure-dns.net.
  172800 IN NS ns3-02.azure-dns.org.
  172800 IN NS ns4-02.azure-dns.info.

myaname.tjpzone1.com 3600 IN A 127.0.0.1

mycname.tjpzone1.com 3600 IN CNAME blahblah.tjpzone1.com.

outsidecname.tjpzone1.com 3600 IN CNAME www.example.com.

txtrecords.tjpzone1.com 3600 IN TXT "My lalala"
```

Now importing this creates additional entries in the zone (see screenshot from Azure admin panel): 
![zone import after second round](https://user-images.githubusercontent.com/35297614/35104256-948d4cfc-fc68-11e7-949d-03621a34318b.png)

Also, exporting these entries into a new zone file: 
**test-export-secondround.zone**
```

; Exported zone file from Azure DNS
;      Zone name: tjpzone1.com
;      Resource Group Name: my-domains
;      Date and time (UTC): Thu, 18 Jan 2018 16:22:56 +0100

$TTL 300
$ORIGIN tjpzone1.com.
    
@ 3600 IN SOA ns1-02.azure-dns.com. azuredns-hostmaster.microsoft.com. (
              1 ; serial
              3600 ; refresh
              300 ; retry
              2419200 ; expire
              300 ; minimum
              )

  172800 IN NS ns1-02.azure-dns.com.
  172800 IN NS ns2-02.azure-dns.net.
  172800 IN NS ns3-02.azure-dns.org.
  172800 IN NS ns4-02.azure-dns.info.

myaname.tjpzone1.com.tjpzone1.com 3600 IN A 127.0.0.1

mycname.tjpzone1.com.tjpzone1.com 3600 IN CNAME blahblah.tjpzone1.com.

outsidecname.tjpzone1.com.tjpzone1.com 3600 IN CNAME www.example.com.

txtrecords.tjpzone1.com.tjpzone1.com 3600 IN TXT "My lalala"

myaname.tjpzone1.com 3600 IN A 127.0.0.1

mycname.tjpzone1.com 3600 IN CNAME blahblah.tjpzone1.com.

outsidecname.tjpzone1.com 3600 IN CNAME www.example.com.

txtrecords.tjpzone1.com 3600 IN TXT "My lalala" ```

**Comment by tjprescott** [comment]
Thanks @sigiklu I can replicate the issue and will get it fixed for an upcoming release.
