### ISSUE TITLE
Allow case-insensitive parameter types

### ISSUE THREAD

**Issue by eltermann** [Azure/azure-cli#5260]
ARM documentation [1] presents the possibility to use the parameter type "secureString".

However, doing so and trying to deploy via this CLI leads to the message:

> Unrecognized type 'secureString' for parameter 'my-parameter'. Interpretting as string.

Using "securestring" works, but the CLI should be case-insensitive for parameter types.

[1] https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-templates-parameters

**Comment by tjprescott** [comment]
Hi @eltermann can you share the command syntax you are using?  In general, parameter options and so forth are case insensitive in the CLI.

**Comment by eltermann** [comment]
Trying to deploy the following template (let's say azuredeploy.json)

```
{
  "contentVersion": "0.0.0.1",
  "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "parameters": {
    "myParameter": {
      "type": "secureString",
    }
  }
  "resources": [
     ...
  ]
}
```


Command for deploy:

```
$ az group deployment validate --verbose -g myGroup --template-file azuredeploy.json --parameters doesntMatter
```


The issue is here:

```
$ grep -rn 'Unrecognized type' .
./src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py:298:            logger.warning("Unrecognized type '%s' for parameter '%s'. Interpretting as string.", param_type, key)
```


Variable **param_type** should be lowered before being checked.

**Comment by tjprescott** [comment]
So the issue then is the display of the warning?  Does your template actually deploy/validate in spite of the warning?
