### ISSUE TITLE
Revisit az monitor diagnostic-settings create command's parameters

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#5274]
Allow users to specify shorter `--event-hub-rule` with a name instead of resource id.

**Comment by tjprescott** [comment]
This will require some discussion with monitor team.  So right now there are two parameters: `--event-hub` and `--event-hub-rule`. Is it the case that the event hub rule always has to come from the specified event hub, or can you have an event hub rule ID that points to a different event hub?  Depending on that, the way forward would be:

**Current**
```
--event-hub - accepts name only
--event-hub-rule - accepts ID only
```

**Option 1 - Event Hub and Rule Must Agree**
```
--event-hub-name - accepts a name only. Cannot be specified if event-hub-rule is an ID.
--event-hub-rule - name or ID of an event hub rule. If a name, then --event-hub-name must be specified
```

**Option 2 - Event Hub and Rule Can Differ**
```
--event-hub - name or ID of an event hub
--event-hub-rule - name or ID of an event hub rule. If a name is supplied, it is assumed to be associated with the event hub given by --event-hub
```
