### ISSUE TITLE
IoT module prints message during 'az interactive' first use.

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#5288]
![screen shot 2018-01-12 at 9 57 03 am](https://user-images.githubusercontent.com/16448634/34888405-0abf7fce-f77f-11e7-9ee0-022e24285b7e.png)

It should only print that message when the specific IoT commands are run.

cc: @digimaun 

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
all installs / 2.0.25
```

**Comment by derekbekoe** [comment]
Maybe it should only show up if `--help` is done.

**Comment by williexu** [comment]
Fixed with https://github.com/Azure/azure-cli/pull/5758
