### ISSUE TITLE
vm command modules: revisit all artifacts marked as preview

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#5292]
Log this as the check-point so we can revisit routinely to remove those flags once GA, and apply necessary adjustment if the GA version has breaking change:
1. ~VMSS Rolling upgrade~
2. ~Availability Zone~
3. ~Run-Commands~
4. ~Disk Encryption~ 
5. ~OS-disk swap~

**Comment by yugangw-msft** [comment]
@ejarvi, is single pass disk encryption still under feature flag for VM and VMSS?

**Comment by ejarvi** [comment]
- Single VM - No
- VMSS - Yes

**Comment by adewaleo** [comment]
@ejarvi just to confirm vmss disk encryption is no longer in preview right?

**Comment by ejarvi** [comment]
That's right... 

- Announcement:  https://azure.microsoft.com/en-us/blog/extending-azure-security-center-capabilities/
- Windows: https://docs.microsoft.com/en-us/azure/security/azure-security-disk-encryption-windows#encrypt-virtual-machine-scale-sets 
- Linux: https://docs.microsoft.com/en-us/azure/security/azure-security-disk-encryption-linux#encrypt-virtual-machine-scale-sets

**Comment by adewaleo** [comment]
Thanks a lot @ejarvi

**Comment by adewaleo** [comment]
Will close this as this is more of a reminder and not an issue. We will always have features in preview. I have removed. Moreover the features mentioned in the issue have had "(PREVIEW)" removed from their help text.

**Comment by adewaleo** [comment]
Some "preview" text in compute help text has been removed in #9306
