### ISSUE TITLE
Documentation on how to install latest github release locally

### ISSUE THREAD

**Issue by nagpal** [Azure/azure-cli#5307]
Environment summary: HomeBrew install / CLI version 2.0.24 / MacOS  / bash  

Hi

The [current latest release in docker](https://hub.docker.com/r/microsoft/azure-cli/tags/) is 2.0.24 (at the time of creating this issue).  Same for other channels like HomeBrew. The [latest release in this github repo](https://github.com/Azure/azure-cli/releases) is 2.0.25 (again, at the time of creating this issue). 

For the brief period (maybe a couple of days, maybe more) until the latest github release makes its way to HomeBrew, docker and other channels, is there a way to install it (2.0.25) locally on my machine? There seems to be lack of documentation around this. 

I could install the edge version (which is 2.0.26-buildnumber) (as documented in the repo README) but it is arguably buggier than an approved release (2.0.25).

-Vijay

**Comment by tjprescott** [comment]
The simplest way to have that level of specificity would be to do a developer setup:
https://github.com/Azure/azure-cli/blob/master/doc/configuring_your_machine.md

Then you can just switch to whatever commit you want (in this case the tag for the 2.0.25 release) and run the `dev_setup.py` script.
