### ISSUE TITLE
Confusing Info/warning about configured defaults

### ISSUE THREAD

**Issue by nagpal** [Azure/azure-cli#5309]
Environment summary: Install Method HomeBrew / CLI version 2.0.24 / MacOS High Sierra / Shell Type: bash

```
$ az --version

azure-cli (2.0.24)

acr (2.0.18)
acs (2.0.23)
advisor (0.1.1)
appservice (0.1.23)
backup (1.0.4)
batch (3.1.8)
batchai (0.1.4)
billing (0.1.7)
cdn (0.0.11)
cloud (2.0.11)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.24)
cosmosdb (0.1.16)
dla (0.0.16)
dls (0.0.19)
eventgrid (0.1.7)
extension (0.0.7)
feedback (2.0.7)
find (0.2.8)
interactive (0.3.12)
iot (0.1.16)
keyvault (2.0.16)
lab (0.0.14)
monitor (0.0.14)
network (2.0.20)
nspkg (3.0.1)
profile (2.0.17)
rdbms (0.0.10)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.20)
role (2.0.16)
servicefabric (0.0.8)
sql (2.0.18)
storage (2.0.22)
vm (2.0.23)

Python location '/usr/local/opt/python3/bin/python3.6'
Extensions directory '/Users/vijay/.azure/cliextensions'

Python (Darwin) 3.6.4 (default, Jan  6 2018, 11:51:59)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

Legal docs and information: aka.ms/AzureCliLegal

```

Hi 

After installing azure cli v2.0.24, I am getting this info/warning that was not being shown in v2.0.23.

```
$ az group exists --resource-group foo
Using default 'bar' for arg resource_group_name
false
```

The info/warning seems to suggest that it is using the resource group that is configured as default. This is confusing since a resource group is being explicitly passed in.

-Vijay

**Comment by tjprescott** [comment]
Hi @nagpal I've looked into this and verified two things:
1. if you have a default configured it will display the message, even if you supply an explicit value.
2. if you supply an explicit value, the command will use the explicit value

So it all still works, but I agree it is confusing and we'll create a fix to address the 1.  Thanks for the report!

**Comment by tjprescott** [comment]
After further investigation, I realized this isn't really a bug. However, I've updated the message and changed the logging level to INFO so it will only appear with --verbose.  The new message will read:

"Configured default 'bar' for arg 'resource-group'".
