### ISSUE TITLE
[ACS] only Linux containers can be created with vm container create

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#531]
windows is also supported, so we should allow it through the CLI

**Comment by yugangw-msft** [comment]
Container is more complex than individual VM, or even scaleset. It is not about individual node, rather multiple nodes in different roles working together to get things done, like master, worker, scheduler, coordinator. Each solution chooses the best OS for them, though the reality is they don't use windows.
So this is sort of the implementation details that users needn't care. Portal doesn't let user choose OS as well.
