### ISSUE TITLE
Cannot enable HTTPS on custom domain for a CDN endpoint

### ISSUE THREAD

**Issue by cdelmas** [Azure/azure-cli#5322]
It looks like there is no way to enable HTTPS for a custom domain on a CDN endpoint using the CLI. Currently, it requires a manual step through the portal.

There is an HTTP REST endpoint for that: `https://docs.microsoft.com/en-us/rest/api/cdn/customdomains/enablecustomhttps`

---

### Environment summary
Install Method: Docker / 2.0.24

**Comment by tjprescott** [comment]
Hi @cdelmas thanks for the report. I've confirmed that this feature is not exposed in verison 2.0.25. We'll get it scheduled for a future release.

**Comment by tjprescott** [comment]
@cdelmas look for this in the upcoming CLI release. (2.0.27)
