### ISSUE TITLE
Add support for az webapp new

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-cli#5342]
Add support for az webapp new

**Comment by tjprescott** [comment]
How would this be different from `az webapp create`?

**Comment by panchagnula** [comment]
the new command will allow for create & deployment together & has fewer required input arguments

**Comment by derekbekoe** [comment]
Would this be a CLI extension?

**Comment by panchagnula** [comment]
this will be the 'quick start' command for websites extension

**Comment by tjprescott** [comment]
The extension has been released.

**Comment by dbradish-microsoft** [comment]
In response to customer feedback [270756](https://dev.azure.com/msft-skilling/Content/_workitems/edit/270756), here is the link to [az webapp create](https://learn.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-create) and for a multi-step reference command, see [az webapp up](https://learn.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-up).  To understand what Azure CLI commands are being run in the `up` command, execute the command with the `--debug` parameter.
