### ISSUE TITLE
How to search Windows client

### ISSUE THREAD

**Issue by cegohub** [Azure/azure-cli#5349]
I´m looking for an example to list and create Windows 10 virtual machines. 

Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90dfc804-87d6-913a-27fe-a9446a04eb13
* Version Independent ID: bfcb97df-2055-9eca-7a93-60811136d8cd
* [Content](https://docs.microsoft.com/en-us/cli/azure/vm/image?view=azure-cli-latest#az_vm_image_list_skus)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)

**Comment by yugangw-msft** [comment]
Use `az vm image list --all`. The `--all` will have CLI to search live service. It will take a while, say 30 seconds, but will return back the list to you. Eg.
```
az vm image list --all --offer windows-10 -otable
Offer       Publisher                Sku       Urn                                                      Version
----------  -----------------------  --------  -------------------------------------------------------  -----------
Windows-10  MicrosoftWindowsDesktop  RS3-ProN  MicrosoftWindowsDesktop:Windows-10:RS3-ProN:16299.125.0  16299.125.0
Windows-10  MicrosoftWindowsDesktop  RS3-ProN  MicrosoftWindowsDesktop:Windows-10:RS3-ProN:16299.192.0  16299.192.0
Windows-10  MicrosoftWindowsDesktop  RS3-ProN  MicrosoftWindowsDesktop:Windows-10:RS3-ProN:16299.64.0   16299.64.0

Then you use the urn to create a vm:

az vm create -g yg -n yg-win10-2 --image MicrosoftWindowsDesktop:Windows-10:RS3-ProN:16299.192.0 --admin-password VerySecret!!!!
```

**Comment by cegohub** [comment]
Hi, @yugangw-msft, thank you!
