### ISSUE TITLE
Improve the error message and error handling in storage command.

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#5352]
A quick search with the term `HTTPSConnectionPool` among storage issues will come up with a dozen of issues caused by various problems. The term becomes ambiguous to the customer and hides the actual error message.

We should look into the overall error handling in the storage data plane commands to see if we can generate a more user-friendly and accurate error message. If it turns out that the service doesn't provide enough clue, we should work with the service team to improve their API.

**Comment by adewaleo** [comment]
@williexu moving this to backlog.

**Comment by williexu** [comment]
Closing this in favor of more scoped issues
