### ISSUE TITLE
AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_KEY handling is inconsistent

### ISSUE THREAD

**Issue by noelbundick** [Azure/azure-cli#5358]
The help for the `az storage` commands tells users that they can set `AZURE_STORAGE_ACCOUNT` and `AZURE_STORAGE_KEY`, so that they don't have to enter them repeatedly. These are handled differently, leading to a confusing user experience.

`AZURE_STORAGE_ACCOUNT` **must** be set using 'export'
```shell
# does not work
AZURE_STORAGE_ACCOUNT=foo

# works
export AZURE_STORAGE_ACCOUNT=foo
```

`AZURE_STORAGE_KEY` can be specified as either an environment var or a bash var
```shell
# works
AZURE_STORAGE_KEY=bar

# also works
export AZURE_STORAGE_KEY=bar
```

I've hit this repeatedly, thinking `AZURE_STORAGE_ACCOUNT` handling was just broken, until I tried adding 'export' and it worked.  This issue is to request that they be handled the same - and that users be able to specify them via environment vars or bash variables, because it's easy to forget 'export' while writing a script.

---

### Environment summary

Install Method:
* apt-get on WSL

```
azure-cli (2.0.25)

acr (2.0.19)
acs (2.0.24)
advisor (0.1.1)
appservice (0.1.24)
backup (1.0.6)
batch (3.1.8)
batchai (0.1.4)
billing (0.1.7)
cdn (0.0.11)
cloud (2.0.11)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.25)
cosmosdb (0.1.16)
dla (0.0.17)
dls (0.0.19)
eventgrid (0.1.8)
extension (0.0.7)
feedback (2.0.8)
find (0.2.8)
interactive (0.3.13)
iot (0.1.16)
keyvault (2.0.16)
lab (0.0.15)
monitor (0.1.0)
network (2.0.21)
nspkg (3.0.1)
profile (2.0.17)
rdbms (0.0.11)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.21)
role (2.0.17)
servicefabric (0.0.9)
sql (2.0.19)
storage (2.0.23)
vm (2.0.24)

Python location '/opt/az/bin/python3'
Extensions directory '/home/noel/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Jan 12 2018, 17:31:35)
[GCC 4.8.4]

Legal docs and information: aka.ms/AzureCliLegal
```

**Comment by tjprescott** [comment]
The intended behaviors are that you can specify the --account-name/--account-key options, or set the environment variables. AFAIK there's no intentional support for trying to find bash variables that matches the environment variable names. cc/ @troydai

**Comment by troydai** [comment]
This is not an issue.

`export` is a `bash` command to expose a variable to other programs run in the same environment. False sense of `AZURE_STORAGE_KEY=xxx` works without `expose` is because the `az storage` command will query the storage key when this environment is missing but `AZURE_STORAGE_ACCOUNT` is set. 

The effect is documented within the help:
```
    --account-key              : Storage account key. Must be used in conjunction with storage
                                 account name. Environment variable: AZURE_STORAGE_KEY.
    --account-name             : Storage account name. Related environment variable:
                                 AZURE_STORAGE_ACCOUNT. Must be used in conjunction with either
                                 storage account key or a SAS token. If neither are present, the
                                 command will try to query the storage account key using the
                                 authenticated Azure account. If a large number of storage commands
                                 are executed the API quota may be hit.
```
