### ISSUE TITLE
azure cli 2.0.24 regression - create asg fails

### ISSUE THREAD

**Issue by briancornally** [Azure/azure-cli#5359]
# environment
broken behaviour on all plaforms tested 2.0.25, 2.0.24
Ubuntu (tested & fails 2.0.25,2.0.24), MacOS (2.0.25), Windows (2.0.25), CloudShell (2.0.25)
installation method (not relevant)
MacOS - curl -L https://aka.ms/InstallAzureCli | bash
Windows - msi https://aka.ms/InstallAzureCliWindows 
Ubuntu - sudo apt-key adv --keyserver packages.microsoft.com --recv-keys 52E16F86FEE04B979B07E28DB02C46DF417A0893; sudo apt-get install apt-transport-https; sudo apt-get update && sudo apt-get install azure-cli

# to reproduce
- install azure cli - currently 2.0.25 
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest

- run any create Application Security Groups command
az network asg create --resource-group myrg --name test --location canadacentral

# workaround
downgrade to 2.0.23
e.g. on Ubuntu
sudo apt-get remove azure-cli -y
sudo apt-get install azure-cli=2.0.23-1 -y

# expected to see
$ az network asg create --resource-group myrg --name test --location canadacentral
{
  "etag": "W/\"xxxxx\"",
  "id": "/subscriptions/xxxxxxxx/resourceGroups/myrg/providers/Microsoft.Network/applicationSecurityGroups/test",
  "location": "canadacentral",
  "name": "test",
  "provisioningState": "Succeeded",
  "resourceGroup": "myrg",
  "resourceGuid": null,
  "tags": null,
  "type": "Microsoft.Network/applicationSecurityGroups"
}
note: xxx = obfuscation for privacy

# saw instead
- Mac error "create_asg() takes at least 4 arguments (5 given)"
macb:Scripts brian$ az network asg create --resource-group myrg --name test --location canadacentral
create_asg() takes at least 4 arguments (5 given)
Traceback (most recent call last):
  File "/Users/brian/lib/azure-cli/lib/python2.7/site-packages/knack/cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/brian/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    six.reraise(*sys.exc_info())
  File "/Users/brian/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 292, in execute
    result = cmd(params)
  File "/Users/brian/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/Users/brian/lib/azure-cli/lib/python2.7/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/brian/lib/azure-cli/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 337, in default_command_handler
    result = op(**command_args)
TypeError: create_asg() takes at least 4 arguments (5 given)

- Ubuntu different error "create_asg() missing 1 required positional argument: 'client'"
brian@ubuntu:~$ az network asg create --resource-group myrg --name test --location canadacentral
create_asg() missing 1 required positional argument: 'client'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 292, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 169, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 337, in default_command_handler
    result = op(**command_args)
TypeError: create_asg() missing 1 required positional argument: 'client'

# versions mac
macb:~ brian$ az -v
azure-cli (2.0.25)

acr (2.0.19)
acs (2.0.24)
advisor (0.1.1)
appservice (0.1.24)
backup (1.0.6)
batch (3.1.8)
batchai (0.1.4)
billing (0.1.7)
cdn (0.0.11)
cloud (2.0.11)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.25)
cosmosdb (0.1.16)
dla (0.0.17)
dls (0.0.19)
eventgrid (0.1.8)
extension (0.0.7)
feedback (2.0.8)
find (0.2.8)
interactive (0.3.13)
iot (0.1.16)
keyvault (2.0.16)
lab (0.0.15)
monitor (0.1.0)
network (2.0.21)
nspkg (3.0.1)
profile (2.0.17)
rdbms (0.0.11)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.21)
role (2.0.17)
servicefabric (0.0.9)
sql (2.0.19)
storage (2.0.23)
vm (2.0.24)
Python location '/Users/brian/lib/azure-cli/bin/python'
Extensions directory '/Users/brian/.azure/cliextensions'
Python (Darwin) 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]

# versions ubuntu
brian@ubuntu:~$ cat /etc/lsb-release; uname -a; az -v
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
Linux ubuntu 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
azure-cli (2.0.25)
 
acr (2.0.19)
acs (2.0.24)
advisor (0.1.1)
appservice (0.1.24)
backup (1.0.6)
batch (3.1.8)
batchai (0.1.4)
billing (0.1.7)
cdn (0.0.11)
cloud (2.0.11)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.25)
cosmosdb (0.1.16)
dla (0.0.17)
dls (0.0.19)
eventgrid (0.1.8)
extension (0.0.7)
feedback (2.0.8)
find (0.2.8)
interactive (0.3.13)
iot (0.1.16)
keyvault (2.0.16)
lab (0.0.15)
monitor (0.1.0)
network (2.0.21)
nspkg (3.0.1)
profile (2.0.17)
rdbms (0.0.11)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.21)
role (2.0.17)
servicefabric (0.0.9)
sql (2.0.19)
storage (2.0.23)
vm (2.0.24)
 
Python location '/opt/az/bin/python3'
Extensions directory '/home/brian/.azure/cliextensions'
 
Python (Linux) 3.6.1 (default, Jan 12 2018, 17:31:35) 
[GCC 4.8.4]
 
Legal docs and information: aka.ms/AzureCliLegal

**Comment by tjprescott** [comment]
Thanks for the report @briancornally. This fix will be included in the upcoming release.
