### ISSUE TITLE
az identity create failing

### ISSUE THREAD

**Issue by smereczynski** [Azure/azure-cli#5360]
Hi,
`az identity create -n name -g group -l westeurope` is failing with error as follows:

> The resource type could not be found in the namespace 'Microsoft.ManagedIdentity' for api version '2015-08-31-preview'.

---

### Environment summary

Install Method: apt-get for Ubuntu, curl for Mac
CLI version: 2.0.25
OS version: Ubuntu 16.04.3 LTS, Mac OSX 10.13.2
Shell Type: bash

**Comment by smereczynski** [comment]
In debug mode I see that request is going to the api-version mentioned in error:

`urllib3.connectionpool : https://management.azure.com:443 "GET /subscriptions/d8207ac4-c426-49b0-8395-3f197ed7a82e/providers/Microsoft.ManagedIdentity/userAssignedIdentities?api-ver
sion=2015-08-31-preview HTTP/1.1" 404 172`

And the response is:

`msrest.http_logger : b'{"error":{"code":"InvalidResourceType","message":"The resource type could not be found in the namespace \'Microsoft.ManagedIdentity\' for api version \'2015-08-31-preview\'."}}'`

**Comment by yugangw-msft** [comment]
@smereczynski, MSI is still in private preview and requires manual sign up: `aka.ms/azuremsiprivatepreview`
Once you are approved, you should be able to create the identity at least in the region of `westus2`
