### ISSUE TITLE
az vm create with --assign-identity option probably should return identity

### ISSUE THREAD

**Issue by smereczynski** [Azure/azure-cli#5361]
Hi,
It's a feature request or probably more discussion on it. When we are creating vm with `az vm create` using --assign-identity, we are getting output like this:

![2018-01-21_14-00-30](https://user-images.githubusercontent.com/705653/35195481-640e17d8-fec4-11e7-96d0-d3ce1c780b6a.png)

In my opinion, an AppId of the newly created SP should be returned in identity block of the output. Having that, it will be possible to use it in a pipeline without need to use `az vm show`.

**Comment by smereczynski** [comment]
I think it is not edge scenario. I'm facing production scenarios where we need to know this SP for scripted assignments. It is a typical usage. The script is creating new VM, then assigning this VM's identity to (let say) KeyVault policy. Without knowing this SP it will be impossible in actual state. I know what are the plans for MSI (I'm Azure MVP). And also after those changes we should be able to read this SP or operate on resources's identities without Azure Portal.
So... I don't agree that it is not needed. At this point if we are creating VM with MSI enabled, we need to read VM's properties to get SP info. It is unnecessary in my opinion.

**Comment by yugangw-msft** [comment]
I see, the KV integration flow requires the principalId(comes from the SP's object id at the implementation layer). If yes, then I agree this is a good ask for us to show the principalId
For you original ask of `an AppId of the newly created SP`, that is not principal ID, rather is graph `clientID`. For that part I am not convinced we need to do that per reasons I mentioned

**Comment by smereczynski** [comment]
True. I'm using a lot of AAD SPs and messed here those two topics :)

**Comment by eliassal** [comment]
Hi I am following MS learn at  https://learn.microsoft.com/en-us/training/modules/implement-managed-identities/4-configure-managed-identities
when I issue

az vm create --resource-group impl-managed-identities-rg --name managidentityVM --image UbuntuLTS --generate-ssh-keys --assign-identity --role contributor --scope $subscription --admin-username sieracuser --admin-password myPassword12 --output json

I get the following error (but the VM is created)

> {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"PrincipalNotFound\",\r\n    \"message\": \"Principal 51a85caafdf2450091c8b8e497161bcc does not exist in the directory 6799c70e-3ceb-4e88-af13-8f6c565fd4a5. Check that you have the correct principal ID. If you are creating this principal and then immediately assigning a role, this error might be related to a replication delay. In this case, set the role assignment principalType property to a value, such as ServicePrincipal, User, or Group.  See https://aka.ms/docs-principaltype\"\r\n  }\r\n}"}]}}

Should I creatre a system principal? I understand not.
Thanks for your help

**Comment by eliassal** [comment]
I just issued
`az vm list --resource-group imy-rg`
in the output, I see

> "identity": {
>       "principalId": "51a85caa-0000000-91c8-0000061bcc",
>       "tenantId": "6799c70e-..........65fd4a5",
>       "type": "SystemAssigned",
>       "userAssignedIdentities": null

Is this the system-assigned service Principal?
