### ISSUE TITLE
webapp: webapp backup/restore not working with SAS tokens created from CLI or portal

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#5369]
This also blocks `Test_webapp_backup_config` and `test_webapp_backup_restore` from running live or re-recorded through creating storage accounts on the fly.
The service appears using older storage libraries which can't work with newer versions of sas tokens

**Comment by yugangw-msft** [comment]
//CC @troydai

**Comment by panchagnula** [comment]
@Nking92  can you take a look at this please?

**Comment by Nking92** [comment]
@panchagnula This requires us to do update the Azure Storage SDK used in the backend. It's certainly doable but it was originally put on hold because there are major API changes in the new version. We should probably do this soon though, before problems from using an old version escalate.

**Comment by panchagnula** [comment]
@Nking92 once we have the backend fix can you update this bug & the milestone. thank you.

**Comment by panchagnula** [comment]
Closing this until we have the feature support for this - we will automatically fix this once we have the backend support enabled.
