### ISSUE TITLE
Feature Request: 'list-usage' for dns zone record-sets

### ISSUE THREAD

**Issue by vdice** [Azure/azure-cli#5370]
Although `az network list-usages -l <region>` prints out a nice overview of usages under the network resource domain, it appears to be lacking dns record-set usage.

This feature request is therefore around seeing dns record-set usage, perhaps looking like `az network dns record-set list-usage -g <resource group> -z <dns zone>`.  

Minimally, I would expect to see the current max quota for dns record-sets in a given resource group/dns zone pair as well as current usage of said quota.

**Comment by tjprescott** [comment]
This is a service limitation and this is not the right forum for service requests. Please direct your request here:
https://feedback.azure.com/forums/217313-networking
