### ISSUE TITLE
No tab completion on macOS when installed from brew

### ISSUE THREAD

**Issue by tleonhardt** [Azure/azure-cli#5400]
I am under the assumption that the ``az`` CLI should have tab-completion, at least for the top-level commands such **az group** and such.  For me, there is no tab completion.

When I searched online some people mentioned having to source a certain tab completion in their .bash_profile, but nothing in the installation instructions mentions this.

So I'm not sure if there is something broken or if there is a step I am missing.  Any help would be appreciated.

Thanks.
---
### Environment summary

macOS 10.13.3

Installed from brew using instructions here:
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest

Shell Type:  iTerm2 3.1.5 with bash
```
```

**Comment by derekbekoe** [comment]
At the end of the brew install, it should say this:
```
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/azure-cli/2.0.25: 8,504 files, 47.0MB
```

Then, to enable completion, you can source that file with:
```
source /usr/local/etc/bash_completion.d/az
```

To make your terminal always load that file, you can add it to your `~/.bash_profile`

**Comment by derekbekoe** [comment]
That should resolve your issue.

**Comment by tleonhardt** [comment]
That did resolve my issue.  Thank you.

**Comment by kfmaurice** [comment]
This helped me too, thanks.

**Comment by OlivierDupre** [comment]
> At the end of the brew install, it should say this:
> 
> ```
> ==> Caveats
> Bash completion has been installed to:
>   /usr/local/etc/bash_completion.d
> ==> Summary
> 🍺  /usr/local/Cellar/azure-cli/2.0.25: 8,504 files, 47.0MB
> ```
> 
> Then, to enable completion, you can source that file with:
> 
> ```
> source /usr/local/etc/bash_completion.d/az
> ```
> 
> To make your terminal always load that file, you can add it to your `~/.bash_profile`

Maybe it should... but it does not. Any way we could force it?

**Comment by richbecks** [comment]
Same here, just installed azure-cli and no completions are installed, have they been removed?
