### ISSUE TITLE
aks create SP has no rights

### ISSUE THREAD

**Issue by hardcorehead87** [Azure/azure-cli#5401]
There were issues (#5219) with the Service Principal creation that happens before the `aks create` command that prevented a cluster to be created in some cases. This has been fixed in the latest build but an other minor issue has come up now. The created Service Principal has no rights.

Before, the SP received contributer rights on the subscription where it was created. This made it possible for the cluster using the SP to access an ACR in the same subscription. 
Now however the SP doesn't get these rights anymore out-of-the-box and these need to be applied manually. 

My user account from which I'm doing this has owner rights on the subscription and I've made sure to remove the `~/.azure/aksServicePrincipals.json` file.

There is something to say for manually applying rights. This makes it clear what is allowed and what not. But had it not been for my earlier issues with the SP I would not have found this and my cluster would not be able to get images from the ACR.

---

### Environment summary

MSI / azure-cli (2.0.26) / Windows 10 build 1709 (16299.192) / Powershell 

```
azure-cli (2.0.26)

acr (2.0.20)
acs (2.0.25)
advisor (0.1.1)
appservice (0.1.25)
backup (1.0.6)
batch (3.1.9)
batchai (0.1.5)
billing (0.1.7)
cdn (0.0.12)
cloud (2.0.11)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.26)
cosmosdb (0.1.16)
dla (0.0.17)
dls (0.0.19)
eventgrid (0.1.8)
extension (0.0.8)
feedback (2.0.8)
find (0.2.8)
interactive (0.3.14)
iot (0.1.16)
keyvault (2.0.16)
lab (0.0.15)
monitor (0.1.0)
network (2.0.22)
nspkg (3.0.1)
profile (2.0.18)
rdbms (0.0.11)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.21)
role (2.0.17)
servicefabric (0.0.9)
sql (2.0.20)
storage (2.0.24)
vm (2.0.25)

Python location '/usr/local/bin/python'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.3 (default, Dec 20 2017, 01:32:21)
[GCC 5.3.0]
```

**Comment by jnoller** [comment]
Closing issue as stale/resolved - AKS has not seen additional reports of SP rights issues such as this. Additionally, the docs here: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-aks should be up to date with AKS/ACR information.
