### ISSUE TITLE
Multiple subscriptions and MSI login, setting default

### ISSUE THREAD

**Issue by ich-sammckenzie** [Azure/azure-cli#5402]
When MSI for a VM is enabled, and allocated to more than one subscription. Only one subscription is used

az login --msi works and lists all the allocated subscriptions, but it appears to be setting the "name" to "MSI@50342" for all subscriptions. Instead of the actual subscription name.
![image](https://user-images.githubusercontent.com/24918082/35386674-d0ccc5c4-01c4-11e8-93a7-0cbbeb925414.png)

Meaning "az account list --output table" only outputs one result. 
![image](https://user-images.githubusercontent.com/24918082/35386721-f7c41d44-01c4-11e8-951e-4a12046d0576.png)

And "az account set -s [id/name]" don't work unless you use "MSI@50342" or the last subscription ID in the list.
![image](https://user-images.githubusercontent.com/24918082/35386761-1d63a060-01c5-11e8-9595-ab4731b8f7ae.png)

### Environment summary
azure-cli (2.0.23)
Azure Server 2016/ Shell Type (cmd.exe)

**Comment by yugangw-msft** [comment]
@ich-sammckenzie, CLI definitely should maintain 2 accounts. `az login --msi` does the right thing. Let me take a look at persistence code to see why one of them was dropped

**Comment by yugangw-msft** [comment]
@ich-sammckenzie, I might have some misunderstanding, so like to confirm here
   1.  The subscription name will be the same, which is by-design for now
   2. `az account list -otable` will show 2 entries, and you can use `id` to switch
   3. I can't reproduce the issue that `az account list` only shows one entry 

The following is what I got for your reference 
```
(env) yugangw@yugangw-msi:~/azure-cli$ az login --msi
[
  {
    "environmentName": "AzureCloud",
    "id": "2c224e7e-...",
    "isDefault": true,
    "name": "MSI@50342",
    "state": "Enabled",
    "tenantId": "72f988bf-...",
    "user": {
      "name": "VM",
      "type": "servicePrincipal"
    }
  },
  {
    "environmentName": "AzureCloud",
    "id": "00977cdb-...",
    "isDefault": false,
    "name": "MSI@50342",
    "state": "Enabled",
    "tenantId": "72f988bf-...",
    "user": {
      "name": "VM",
      "type": "servicePrincipal"
    }
  }
]
(env) yugangw@yugangw-msi:~/azure-cli$ az account set -s "00977cdb-163f-435f-9c32-39ec8ae61f4d"
(env) yugangw@yugangw-msi:~/azure-cli$ az account list -otable
Name       CloudName    SubscriptionId                        State    IsDefault
---------  -----------  ------------------------------------  -------  -----------
MSI@50342  AzureCloud   2c224e7e-...                         Enabled
MSI@50342  AzureCloud   00977cdb-...                         Enabled  True

```

**Comment by ich-sammckenzie** [comment]
@yugangw-msft Thanks for taking a look. You're point about the subscription name being the same. Thank you for clarifying that (though that means you would be unable to run "az account set -s [SubscriptionName]" I'm amusing this will be fixed at some point?).

I've just run the steps again just to confirm I am still seeing the issue
![image](https://user-images.githubusercontent.com/24918082/35432848-4ca5b23c-0279-11e8-9e3f-3c6e37b55983.png)
despite the VM being assigned to two subscriptions, seeing them when logging in, I'm only able to list one. 
As stated this is using CMD.exe on Windows. I noticed you are using bash in your example. If i get chance I will see if I can test this against another VM.

**Comment by yugangw-msft** [comment]
If you run `az account list -o json`, how many you get? Also what is the version of the cli you are using?

**Comment by BeeFrog** [comment]
We still get the one subscription. 
We're using 2.0.23 only the one account.  Just upgrading to 2.0.25 and will try again.

**Comment by ich-sammckenzie** [comment]
@yugangw-msft 
We are using
**Environment summary**
azure-cli (2.0.23)
Azure Server 2016/ Shell Type (cmd.exe)

We have updated to 2.0.25 and it remains the same.

C:\Users\ich_admin>az login --msi
[
  {
    "environmentName": "AzureCloud",
    "id": "2410759f-**",
    "isDefault": true,
    "name": "MSI@50342",
    "state": "Enabled",
    "tenantId": "**",
    "user": {
      "name": "systemAssignedIdentity",
      "type": "servicePrincipal"
    }
  },
  {
    "environmentName": "AzureCloud",
    "id": "da287f7e-**",
    "isDefault": false,
    "name": "MSI@50342",
    "state": "Enabled",
    "tenantId": "**",
    "user": {
      "name": "systemAssignedIdentity",
      "type": "servicePrincipal"
    }
  }
]

C:\Users\ich_admin>az account list -o json
[
  {
    "cloudName": "AzureCloud",
    "id": "da287f7e-**",
    "isDefault": false,
    "name": "MSI@50342",
    "state": "Enabled",
    "tenantId": "**",
    "user": {
      "name": "systemAssignedIdentity",
      "type": "servicePrincipal"
    }
  }
]

C:\Users\ich_admin>

**Comment by yugangw-msft** [comment]
@ich-sammckenzie @BeeFrog, thanks for the information. I am fixing it.
