### ISSUE TITLE
[VM] Ability to query/manipulate `Update Management`?

### ISSUE THREAD

**Issue by iyerusad** [Azure/azure-cli#5403]
Azure VMs have a preview feature called ["Update Management"](https://azure.microsoft.com/en-us/blog/managing-updates-for-your-azure-vm/). This feature offers built-in update management (i.e. Windows Update, apt, etc).

Enabling the feature prompts for a `log analytics workspace` and an `Automation account`. Presumably, the automation account is where update management scheduling actually happens.

Is `Update Management` component query-able via az cli? (I wasn't able to find it if so, under `az vm`)
Are Azure Automation accounts manageable via az cli? 

**My goal:**
- **Identify** `Update Management` status for a VM. <br />(i.e. `az vm updatemgmt show -n "MyVM"`)
- Secondary Goal: **Enable** `Update Management` for a VM <br />(i.e. `az vm updatemgmt status -n "MyVM" -value enable`)
- Stretch goal: Have a policy that audits VMs and shoots off an email indicating which machines don't have update management enabled. (side note: Surprised this isn't a default available policy definition that ships in Azure - is there a board where can post secondary inquiry on this?)

**Comment by iyerusad** [comment]
Ability to toggle `Update Management` on a VM via Azure CLI would likely resolve a bug related to a VM thinking `Update Management` is enabled, but other parts of Azure Portal not recognizing it being enabled (i.e. the automation account). If there is an issue board where can file more detailed bug around `Update Management` or `Azure Portal` in general, please holler.

**Comment by adewaleo** [comment]
Labeling this as a service issue as there isn't a current python SDK for this feature (see [Azure Automation](https://docs.microsoft.com/en-us/azure/automation/)).

**Comment by sbonds** [comment]
For those interested in a programmatic alternative while the CLI is improved, there is an ARM template based method that can work: https://stackoverflow.com/questions/52635285/how-to-deploy-update-management-to-azure-resources-the-programmatic-way

**Comment by adewaleo** [comment]
I will close this as it is not a CLI issue, there isn't python sdk support for it (as far as I'm aware off) and there is a work around with arm templates.

**Comment by sbonds** [comment]
Perhaps rather than closing this we could make it pending the SDK improvement necessary to support this capability?

**Comment by sbonds** [comment]
Is this the SDK support that is supposedly missing?

https://docs.microsoft.com/en-us/python/api/azure-mgmt-edgegateway/azure.mgmt.edgegateway.models.updatesummary?view=azure-python

```python
UpdateSummary(*, device_version_number: str = None, friendly_device_version_name: str = None, device_last_scanned_date_time=None, last_completed_scan_job_date_time=None, **kwargs) -> None
```

**Comment by adewaleo** [comment]
Thanks for sending this our way @sbonds . I can't find any [update management operations](https://docs.microsoft.com/en-us/python/api/azure-mgmt-edgegateway/azure.mgmt.edgegateway.operations?view=azure-python), but yes I can reopen this issue.  

However, I will be moving on to a different team soon, so I won't be able to implement this feature. But hopefully someone else on the CLI team can look into this.

cc: @yugangw-msft  @zikalino @achandmsft

**Comment by sbonds** [comment]
Thanks so much! It may seem like a minor thing, but automating these sorts of reports will be quite useful.

**Comment by Sandido** [comment]
This functionality is present in CLI and PS via Patches: https://learn.microsoft.com/en-us/azure/update-manager/manage-vms-programmatically?tabs=cli%2Crest
