### ISSUE TITLE
Problems creating azure function with source control deployment

### ISSUE THREAD

**Issue by rcastill** [Azure/azure-cli#5409]
I first tried the following tutorial: [https://docs.microsoft.com/en-us/azure/azure-functions/scripts/functions-cli-create-function-app-github](https://docs.microsoft.com/en-us/azure/azure-functions/scripts/functions-cli-create-function-app-github), with a `bitbucket` based repo:

Everything worked except the source control deployment configuration. I thought it may have something to do with using a Bitbucket account instead of a GitHub account.

So, I tried to follow the simplest example: [https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-cli](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-cli):

It also failed. One thing to note is this output when creating the functionapp:

```
Linking to git repository 'master'
Link to git repository failed due to error ''Site' object has no attribute 'cli_ctx''
```

Notes:
- It is weird that it says repository 'master' instead of branch, maybe misleading? (I'm setting the repo url with the option `--deployment-source-url`)
- In between many tests I tried to set the repo url with the option `--deployment-source-branch`. This resulted in the following output:
```
Linking to git repository 'https://github.com/Azure-Samples/functions-quickstart'
Link to git repository failed due to error ''Site' object has no attribute 'cli_ctx''
```
It didn't solve the main problem, so it doesn't seem to be a "config swap" problem.
- Over the comments in [https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-cli](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-cli) there is someone reporting this exact same error recently

---

### Environment summary

**Install Method:** `brew install azure-cli`

`az --version`
```
azure-cli (2.0.25)

acr (2.0.19)
acs (2.0.24)
advisor (0.1.1)
appservice (0.1.24)
backup (1.0.6)
batch (3.1.8)
batchai (0.1.4)
billing (0.1.7)
cdn (0.0.11)
cloud (2.0.11)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.25)
cosmosdb (0.1.16)
dla (0.0.17)
dls (0.0.19)
eventgrid (0.1.8)
extension (0.0.7)
feedback (2.0.8)
find (0.2.8)
interactive (0.3.13)
iot (0.1.16)
keyvault (2.0.16)
lab (0.0.15)
monitor (0.1.0)
network (2.0.21)
nspkg (3.0.1)
profile (2.0.17)
rdbms (0.0.11)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.21)
role (2.0.17)
servicefabric (0.0.9)
sql (2.0.19)
storage (2.0.23)
vm (2.0.24)

Python location '/usr/local/opt/python3/bin/python3.6'
Extensions directory '/Users/Rodolfo/.azure/cliextensions'

Python (Darwin) 3.6.4 (default, Jan  6 2018, 11:51:59)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

Legal docs and information: aka.ms/AzureCliLegal
```

**OS Version:** macOS High Sierra 10.13.2

**Shell:** bash

**Comment by yugangw-msft** [comment]
this has been fixed through #5335, please use  the upcoming release
