### ISSUE TITLE
Thank s

### ISSUE THREAD

**Issue by Digitalmatrix2** [Azure/azure-cli#5410]
Helped

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bea54d36-cb69-577c-e114-2c4bd0e33728
* Version Independent ID: 812e7aa5-2e8a-f9ef-d922-df188bd6275a
* [Content](https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/user?view=azure-cli-latest#az_webapp_deployment_user_set)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/webapp/deployment/user.yml)
* Service: app-service-web

**Comment by tjprescott** [comment]
@JasonRShaver
