### ISSUE TITLE
--container-name parameter for "az backup item list"

### ISSUE THREAD

**Issue by javgarces** [Azure/azure-cli#5411]
The --container-name parameter for "az backup item list" is listed as Optional, but using the CLI it's a required parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60a9656d-adaf-b33e-a5a9-985e6245c970
* Version Independent ID: 98f0d6b5-5005-38a3-0f0d-a10d138062a7
* [Content](https://docs.microsoft.com/en-us/cli/azure/backup/item?view=azure-cli-latest#az_backup_item_list)
* [Content Source](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/_help.py)
* Service: unspecified

**Comment by tjprescott** [comment]
The CLI is correct here. Apparently there is a bug in the doc gen because resource group is optional in the CLI and required in the docs.
