### ISSUE TITLE
Feature Request:  Az Login should open the web browser automatically on WSL

### ISSUE THREAD

**Issue by taylorb-microsoft** [Azure/azure-cli#5413]
In the fall creators update of Windows 10 WSL can natively invoke Windows applications.  Thus az login can automatically open the authentication web page (including passing the auth code like PowerShell does).

Example:  `taylorb@taylorb-sl:/mnt/c/Users/taylorb$ cmd.exe /c start "http:\\\\www.microsoft.com"` results in opening www.microsoft.com in the users default browser (chrome, edge, firefox etc...)

**Comment by yugangw-msft** [comment]
> including passing the auth code like PowerShell does

@taylorb-microsoft, could you please elaborate what particular PowerShell module/command you are talking about. [Azure-PowerShell](https://github.com/Azure/azure-powershell)?

And this is the area I am looking to simplify when there is window manager around.

**Comment by yugangw-msft** [comment]
I will fix this no later than the end of july
