### ISSUE TITLE
Feature Request: Add Non-Recursive Flag for az storage blob upload-batch 

### ISSUE THREAD

**Issue by danielhelfand** [Azure/azure-cli#5420]
### Environment summary

Install Method:
Homebrew `brew install azure-cli`

Version: 
```
az --version
azure-cli (2.0.25)
```

OS:
OS X El Capitan Version 10.11.6 

As referenced in #4752, `az storage blob upload-batch` cannot upload folders to the `$root` container in an Azure Storage account. 

I would like the option when using `az storage blob upload-batch` to upload only files located within a certain directory (e.g., the files located at the root of a directory) but not sub directories. Currently, there is `az storage blob upload` for uploading individual files, but it is not the most elegant solution for my particular use case.

My use case is that I am trying to host an Angular app as a static UI in an Azure blob container. I would like to use the `az storage blob upload-batch` to upload the root files of my dist folder to the `$root` container and then use a subsequent run to upload any subdirectories to a new container (e.g., an assets container with the subdirectories). 

My initial thought is to have a flag like `--root=True` to specify that you want to upload only files in a directory, not subdirectories, to the `$root` container so as to avoid the `The requested URI does not represent any resource on the server.` error referenced in #4752.

A better thought may even be to have a recursive flag that when set will upload subdirectories. Including the  `--recursive` flag with `az storage blob upload-batch` would upload subdirectories. An example could be `az storage blob upload-batch -d <container name> -s <path/to/directory> --recursive`. Not including the recursive flag would then only upload files of a particular directory.

**Comment by williexu** [comment]
@lostinthecloud  Thanks for pointing this out. We are looking into how we can include this behavior into the cli. 
One possibility we are considering is changing the behavior of the `--pattern` globbing parameter to incorporate further scenarios like this one.

**Comment by lostinthecloud** [comment]
@williexu I do like the `--pattern` idea. Would obviously be a lot simpler than adding a new parameter for one particular case.

**Comment by anthonychu** [comment]
@williexu Is it possible to exclude folders right now with `--pattern`?

**Comment by williexu** [comment]
@anthonychu not at the moment. We are looking into various options for opening up our matching to fit more scenarios.

**Comment by bacongobbler** [comment]
For the time being, this has been my workaround to upload static assets to root and non-root containers: https://gist.github.com/bacongobbler/b1a99656d78d5330cb7ff123971700a6

It's a little janky, but it works. You can remove `hugo` from the script and just upload a directory to a blob store. Hope this helps!

**Comment by danielhelfand** [comment]
@bacongobbler Thanks for this. My trouble with this error was not really that the error was happening, as using `az storage blob upload-batch -d '$root'` still works as intended. It more had to do with the fact I was using this on a CI/CD pipeline and the error caused the pipeline to fail each time. My workaround for it was to use a try-catch block to catch the error.

Not much of a better solution than what you have, but there's definitely ways to get around this. I really dislike having to use containers all together with storage accounts and hopefully the service eventually just lets you upload your static content to the storage account directly and is able to replicate the file structure in the storage account similar to how AWS does it with S3 Buckets.

**Comment by limingu** [comment]
The new blob upload command is in our storage-preview extension now. That should solve your issues. We will bring these features into cli core later.

az storage azcopy blob upload \
    -c containerName \
    --account-name accountName \
    -s directory/path \
    -d upload/path

If the sub folder is need to be uploaded, the flag --recursive can be added.
