### ISSUE TITLE
password for cloud-init VM example

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#5422]
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
2.0.25, Bash on Windows, Microsoft Windows [Version 10.0.17074.1000]
```
I'm referring to the example in https://docs.microsoft.com/en-us/azure/opbuildpdf/virtual-machines/linux/toc.pdf which is in the article 'How to customize a Linux virtual machine on first
boot'
It first asks to create clout-init file, then suggests to create VM using the following command:
az vm create \
--resource-group myResourceGroupAutomate \
--name myVM \
--image UbuntuLTS \
--admin-username azureuser \
--generate-ssh-keys \
--custom-data cloud-init.txt
My question is what's gonna be a password to reach VM in this case?
It's not provided either in cloud-init file or in command text.
```

**Comment by adewaleo** [comment]
To connect to the Linux VM you don't use a password, rather you need to use ssh into it using your private key. Page 363 of the doc you shared has some very helpful info on this. You can also see [here](https://unix.stackexchange.com/questions/23291/how-to-ssh-to-remote-server-using-a-private-key) for more info. 

To ssh into the VM, do the following:
- get the VM's IP address `IP="$(az vm show --name TestVM -d --query "publicIps" -o tsv)"`
- use the ssh command:  `ssh $IP`

According to the [CLI reference](https://docs.microsoft.com/en-us/cli/azure/lab/vm?view=azure-cli-latest#az-lab-vm-create) `--generate-ssh-keys` "Generate SSH public and private key files if missing. The keys will be stored in the `~/.ssh` directory."  If you already have an id_rsa.pub public key within `~/.ssh`, then it will be added to the VM's `.ssh/authorized_keys` file which enables you to ssh into the VM using your private key file (`id_rsa`). 

you can use `--ssh-key-value` to use a specific public key when creating a new VM.
