### ISSUE TITLE
az hdinsight support

### ISSUE THREAD

**Issue by JaminShanti** [Azure/azure-cli#5426]
When is hdinsight support planed for azure cli 2.0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47dd5c85-9d6d-f55e-4632-0e5bfc179657
* Version Independent ID: 84e585d1-2480-b14f-5b8d-c143e3fbd532
* [Content](https://docs.microsoft.com/en-us/cli/azure/?view=azure-cli-latest#feedback)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_help.py)
* Service: azure

**Comment by tjprescott** [comment]
Hi @JaminShanti we are tracking this with issue #3571. It is currently on the backlog, but please +1 that issue so we can prioritize it down the road.
