### ISSUE TITLE
Issues while "az ml computetarget attach remotedocker" - Azure CLI and PowerShell

### ISSUE THREAD

**Issue by yenayai** [Azure/azure-cli#5430]
Hi, 

O.S Details : Windows 10
azure-cli (2.0.17)
cloud (2.0.10)
extension (0.0.6)
ml (0.1.0a27.post3)

I am facing an issue when I try to connect to the remote docker container (DSVM) created from Azure Portal.
Below is the logged error :
```
Could not retrieve user token. Please run 'az login'
'utf-8' codec can't decode byte 0x88 in position 428: invalid start byte
```
Following is what I did :
Created a "Predictive Maintenance" sample project  in Azure Machine Learning Workbench.
Login to Azure account with the command: 'az login'
Connect to the remote docker container (DSVM) created from Azure Portal.
" az ml computetarget attach --debug remotedocker --name ubuntu --address "52.230.82.195" --username xxx --password "xxxxxxxxxxxx" "

Result: The above mentioned error when I run via CLI.
![image](https://user-images.githubusercontent.com/35953388/35558647-95c93124-05e3-11e8-939e-92a46e04bcb9.png)

![img_18012018_173355_0-2](https://user-images.githubusercontent.com/35953388/35558684-abe3a4da-05e3-11e8-8139-72de6d24bf6d.png)

**Comment by missionfailed** [comment]
Hello, this seems like a malformed token cache. Please run ‘az account clear’ to clean up. And retry.

**Comment by tjprescott** [comment]
Azure ML is not hosted in this repo.
The best place for questions is the Azure ML forum: https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=MachineLearning
