### ISSUE TITLE
docs about removing cloud-init in Ubuntu 16 image

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#5431]
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  2.0.25, Bash on Windows, Microsoft Windows [Version 10.0.17074.1000]

```
```
I could not find in docs how to get rid of cloud-init in Ubuntu 16 image in favor of waagent:
- how to de-install cloud-init packages, which packages
- how to make change waagent configuration

**Comment by tjprescott** [comment]
This would be a conceptual doc, not in-CLI help. Closing this issue.
