### ISSUE TITLE
Table output cannot handle non-toplevel arrays

### ISSUE THREAD

**Issue by sptramer** [Azure/azure-cli#5434]
There appears to be an issue where the `-o table` type cannot handle non-toplevel arrays. This is visible by running through some steps from an upcoming conceptual tutorial document:

```bash
az group create --name TutorialResources --location eastus

az vm create --resource-group TutorialResources \
          --name TutorialVM1 \
          --image UbuntuLTS \
          --generate-ssh-keys \
          --verbose

NIC_ID=$(az vm show -n TutorialVM1 -g TutorialResources \
          --query 'networkProfile.networkInterfaces[].id' \
          -o tsv)

        az network nic show --ids $NIC_ID \
          -g TutorialResources \
          --query '{IP:ipConfigurations[].publicIpAddress.id, Subnet:ipConfigurations[].subnet.id}' \
          -o json
```

```json
{
  "IP": [
    "/subscriptions/.../resourceGroups/TutorialResources/providers/Microsoft.Network/publicIPAddresses/TutorialVM1PublicIP"
  ],
  "Subnet": [
    "/subscriptions/.../resourceGroups/TutorialResources/providers/Microsoft.Network/virtualNetworks/TutorialVM1VNET/subnets/TutorialVM1Subnet"
  ]
}
```

However, if we change the last command to use `-o table` instead, no output is printed.
```bash
        az network nic show --ids $NIC_ID \
          -g TutorialResources \
          --query '{IP:ipConfigurations[].publicIpAddress.id, Subnet:ipConfigurations[].subnet.id}' \
          -o table
```

```output
```
---
### Environment summary

Ubuntu 16 LTS (on WSL)
zsh
Installed via package
az --version: 2.0.25

**Comment by derekbekoe** [comment]
This is more a feature request rather than bug. The current table format doesn't support this.
You can do this though to get the first index of each item (and seems there is only one) - `{IP:ipConfigurations[].publicIpAddress.id, Subnet:ipConfigurations[].subnet.id}'`.

**Comment by gsacavdm** [comment]
@sptramer , I'm not sure #638 is related to this as. In that case, the field is in the top-level array and even that is not making it through...

@derekbekoe , can you confirm if this is related or a separate issue:

```bash
az vm list --query "[].{id:id}" -o table
```
Returns no results, id is a top-level array field.

**Comment by sptramer** [comment]
@gsacavdm I took a quick look into this and thought about it: That is __definitely__ a separate issue. It seems like there are limitations on the number of characters or types (or even names of fields?) in table output.

**Comment by derekbekoe** [comment]
@gsacavdm That's a separate issue.
There are a few keys we skip currently automatically and `id` is one of them. This is due to `id` appearing in almost every command result and them being very long so it's atypical that you'd want to see it in the default table output of commands.

Change the key name and it will appear.
https://github.com/Microsoft/knack/blob/master/knack/output.py#L152

If this is a real issue to you, please open a separate issue. :)

**Comment by JasonRShaver** [comment]
While we understand the scenario here, currently table requires some specific format to operate and moving it to be more free-form has unintended side-effects and additionally does not promote consistency.
