### ISSUE TITLE
CLI2 CNAME zone import issue.

### ISSUE THREAD

**Issue by cforbesywam** [Azure/azure-cli#5435]
When importing zone files with CNAME via CLI2 the importer is incorrectly adding the full domain name.

Zone file for somedomain.org:
test		3600 	IN	CNAME	someotherdomain.org

Imports as
test.somedomain.org 3600 IN CNAME someotherdomain.org.

When the viewed in azure DNS it is displayed as:
test.somedomain.org,somedomain.org .... indicating that it was incorrectly imported.

The CNAME records need to be imported as:
test   3600    IN    CNAME    someotherdomain.org.
---

### Environment summary

Install Method: MSI / CLI version: 2.0.25 / MS Win 7 / Shell Type: cmd.exe  
azure-cli (2.0.25)

acr (2.0.19)
acs (2.0.24)
advisor (0.1.1)
appservice (0.1.24)
backup (1.0.6)
batch (3.1.8)
batchai (0.1.4)
billing (0.1.7)
cdn (0.0.11)
cloud (2.0.11)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.25)
cosmosdb (0.1.16)
dla (0.0.17)
dls (0.0.19)
eventgrid (0.1.8)
extension (0.0.7)
feedback (2.0.8)
find (0.2.8)
interactive (0.3.13)
iot (0.1.16)
keyvault (2.0.16)
lab (0.0.15)
monitor (0.1.0)
network (2.0.21)
nspkg (3.0.1)
profile (2.0.17)
rdbms (0.0.11)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.21)
role (2.0.17)
servicefabric (0.0.9)
sql (2.0.19)
storage (2.0.23)
vm (2.0.24)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\Colin Forbes\.azure\cliextensions'

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

**Comment by tjprescott** [comment]
If you change:
`test 3600 IN CNAME someotherdomain.org`

to 
`test 3600 IN CNAME someotherdomain.org.`
you will get the expected behavior (at least on the latest version of the CLI). Without the trailing dot, the command assumes the address is relative and appends the zone name.

**Comment by cforbesywam** [comment]
Understood - Thank you!
