### ISSUE TITLE
az ad sp fails without a subscription

### ISSUE THREAD

**Issue by stewartadam** [Azure/azure-cli#5444]
`az ad sp delete --id foo` fails if the user does not have a subscription:
```
The subscription '76fb2689-694a-4a30-8565-e8cec35cdba2' could not be found.
```

This is frustrating as not all SPs for applications appear in Enterprise Applications -- those created manually via Graph API do not appear in the portal but do block tenant deletion.

This is a test tenant spun up off my corp account, so there's not going to be a sub tied to it. `--debug` indicates this occurs after a call to `https://management.azure.com/subscriptions/76fb2689-694a-4a30-8565-e8cec35cdba2/providers/Microsoft.Authorization/roleAssignments?$filter=principalId%20eq%20%270bc76d87-e5e3-4263-ac23-a76689004a68%27&api-version=2015-07-01`.

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
macOS 10.13.3, brew installation

azure-cli (2.0.25)

acr (2.0.19)
acs (2.0.24)
advisor (0.1.1)
appservice (0.1.24)
backup (1.0.6)
batch (3.1.8)
batchai (0.1.4)
billing (0.1.7)
cdn (0.0.11)
cloud (2.0.11)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.25)
cosmosdb (0.1.16)
dla (0.0.17)
dls (0.0.19)
documentdb (0.1.5)
eventgrid (0.1.8)
extension (0.0.7)
feedback (2.0.8)
find (0.2.8)
interactive (0.3.13)
iot (0.1.16)
keyvault (2.0.16)
lab (0.0.15)
monitor (0.1.0)
network (2.0.21)
nspkg (3.0.1)
profile (2.0.17)
rdbms (0.0.11)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.21)
role (2.0.17)
servicefabric (0.0.9)
sf (1.0.8)
sql (2.0.19)
storage (2.0.23)
vm (2.0.24)

Python location '/usr/local/opt/python3/bin/python3.6'
Extensions directory '/Users/stewartadam/.azure/cliextensions'

Python (Darwin) 3.6.4 (default, Jan  8 2018, 09:51:47) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

Legal docs and information: aka.ms/AzureCliLegal
```

**Comment by yugangw-msft** [comment]
Sorry for the delay, but I have submitted a PR to fix this.
