### ISSUE TITLE
Getting a list of all users in a subscription

### ISSUE THREAD

**Issue by marjorienorm** [Azure/azure-cli#5449]
How can I get all users with access to a subscription along with there role (i.e., contributor, reader, etc.)?  I thought using --all would do the trick, but it provides info only for my identity.  Given I am the administrator and owner of the subscription I could get the info.  Similar to what I see in the portal when I view the IAM for the subscriotion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dacfad8-cb2f-2534-3b29-89b0930a2252
* Version Independent ID: 17325cd4-44c5-4069-d9f6-940a55f0f7c9
* [Content](https://docs.microsoft.com/en-us/cli/azure/role/assignment?view=azure-cli-latest#az_role_assignment_list)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: azure-resource-manager

**Comment by marjorienorm** [comment]
Okay "az role assignment list" does work.  I was viewing a subscription with only I as the user.

**Comment by tjprescott** [comment]
@marjorienorm glad that worked for you!
