### ISSUE TITLE
Error loading command module 'sf'

### ISSUE THREAD

**Issue by rcarmo** [Azure/azure-cli#5450]
This error message appears upon nearly _every_ command execution:

```
$ az account list
Error loading command module 'sf'
```

I assume this is due to the Service Fabric module being broken (or unsupported on the Mac) in the current release, but it is extremely annoying.

---

### Environment summary

Installed in macOS 10.13.3 (17D47) via `pyenv`. Multiple Python versions (3.5.1, 2.7.12, anaconda, etc.) give this error 
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
$ az --version
azure-cli (2.0.26)

acr (2.0.20)
acs (2.0.25)
advisor (0.1.1)
appservice (0.1.25)
backup (1.0.6)
batch (3.1.9)
batchai (0.1.5)
billing (0.1.7)
cdn (0.0.12)
cloud (2.0.12)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
component (2.0.6)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.26)
cosmosdb (0.1.17)
dla (0.0.18)
dls (0.0.19)
eventgrid (0.1.9)
extension (0.0.8)
feedback (2.0.8)
find (0.2.8)
interactive (0.3.15)
iot (0.1.16)
keyvault (2.0.17)
lab (0.0.16)
monitor (0.1.1)
network (2.0.22)
nspkg (3.0.1)
profile (2.0.18)
rdbms (0.0.11)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.22)
role (2.0.17)
servicefabric (0.0.9)
sf (1.0.5)
sql (2.0.20)
storage (2.0.24)
vm (2.0.25)

Python location '/Users/rcarmo/.pyenv/versions/3.5.1/bin/python'
Extensions directory '/Users/rcarmo/.azure/cliextensions'

Python (Darwin) 3.5.1 (default, Aug 17 2016, 18:15:46) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]

Legal docs and information: aka.ms/AzureCliLegal
```

**Comment by tjprescott** [comment]
`pip uninstall azure-cli-sf`

The sf module is deprecated in favor of "servicefabric"

**Comment by rcarmo** [comment]
Well, it was just installed on a new pyenv... which is strange.

**Comment by tjprescott** [comment]
Through what mechanism did you install it?

**Comment by rcarmo** [comment]
Pip, inside a 3.6.0 pyenv.

**Comment by derekbekoe** [comment]
Possible `azure-cli-sf` was installed on the machine globally (not in a venv) so it was still picked up.
I fresh install of azure-cli with pip would no longer pull down azure-cli-sf though.

**Comment by derekbekoe** [comment]
I would suggest running `pip freeze` from outside your environment to verify but if you've already uninstalled it, you won't see it.

**Comment by sai-li** [comment]
macos I have got the same error
$ az
Error loading command module 'sf'

Do not have this error when sudo az XXX

**Comment by derekbekoe** [comment]
@sai-li Please provide the output of `az --version` and `sudo az --version `

**Comment by sai-li** [comment]
```
$ az --version
azure-cli (2.0.26)

acr (2.0.20)
acs (2.0.25)
advisor (0.1.1)
appservice (0.1.25)
backup (1.0.6)
batch (3.1.9)
batchai (0.1.5)
billing (0.1.7)
cdn (0.0.12)
cloud (2.0.12)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
component (2.0.8)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.26)
cosmosdb (0.1.17)
dla (0.0.18)
dls (0.0.19)
eventgrid (0.1.9)
extension (0.0.8)
feedback (2.0.8)
find (0.2.8)
interactive (0.3.15)
iot (0.1.16)
keyvault (2.0.17)
lab (0.0.16)
monitor (0.1.1)
network (2.0.22)
nspkg (3.0.1)
profile (2.0.18)
rdbms (0.0.11)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.22)
role (2.0.17)
servicefabric (0.0.9)
sf (1.0.8)
sql (2.0.20)
storage (2.0.24)
vm (2.0.25)

Python location '/Users/lis1/lib/azure-cli/bin/python'
Extensions directory '/Users/lis1/.azure/cliextensions'

Python (Darwin) 2.7.13 (default, Apr  4 2017, 08:46:44)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]

Legal docs and information: aka.ms/AzureCliLegal```

```
$ sudo az --version
acr (2.0.20)
acs (2.0.25)
advisor (0.1.1)
appservice (0.1.25)
backup (1.0.6)
batch (3.1.9)
batchai (0.1.5)
billing (0.1.7)
cdn (0.0.12)
cloud (2.0.12)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.26)
cosmosdb (0.1.17)
dla (0.0.18)
dls (0.0.19)
eventgrid (0.1.9)
extension (0.0.8)
feedback (2.0.8)
find (0.2.8)
interactive (0.3.15)
iot (0.1.16)
keyvault (2.0.17)
lab (0.0.16)
monitor (0.1.1)
network (2.0.22)
nspkg (3.0.1)
profile (2.0.18)
rdbms (0.0.11)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.22)
role (2.0.17)
servicefabric (0.0.9)
sql (2.0.20)
storage (2.0.24)
vm (2.0.25)

Python location '/usr/local/opt/python3/bin/python3.6'
Extensions directory '/Users/lis1/.azure/cliextensions'

Python (Darwin) 3.6.4 (default, Jan  6 2018, 11:49:38)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]

Legal docs and information: aka.ms/AzureCliLegal
```

**Comment by sai-li** [comment]
Python version problem?

**Comment by derekbekoe** [comment]
This is due to having the old `sf` module somewhere in your environment so removing that will resolve the issue.
