### ISSUE TITLE
Moving to different container withing different Resource Group

### ISSUE THREAD

**Issue by mohammednaseem** [Azure/azure-cli#5454]
There seem to be only 2 destination options
--destination-blob 
--destination-container
for specifying the destination path.
I need to move the blob to a container within different Resource group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b4e73a9-187f-ad77-3f22-52e7c3edd149
* Version Independent ID: e58b4f05-7bbc-fcb0-ee55-571ee68bd3e7
* [Content](https://docs.microsoft.com/en-us/cli/azure/storage/blob/copy?view=azure-cli-latest)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py)
* Service: storage

**Comment by tjprescott** [comment]
For reference, this is referring to the `storage blob copy` command.

**Comment by williexu** [comment]
This should work, simply specify the right storage account with it's credentials(key, sas, connection string). The differing resource group is not relevant as the credentials will be enough to authorize the copy.
