### ISSUE TITLE
"az aks browse" dont work

### ISSUE THREAD

**Issue by eskornev** [Azure/azure-cli#5455]
getting error while trying to get the access to k8s dashboard:
user@comp:~$ az aks browse --resource-group staging --name staging
Error from server (NotFound): pods "ubernetes-dashboard-2898242510-pcr6z" not found

pod list:
user@comp:~$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE
kube-system   heapster-2574232661-pgbt0               2/2       Running   0          1h
kube-system   kube-dns-v20-2253765213-64kcn           3/3       Running   0          1h
kube-system   kube-dns-v20-2253765213-jjjmc           3/3       Running   0          1h
kube-system   kube-proxy-834v0                        1/1       Running   0          1h
kube-system   kube-proxy-z6tjp                        1/1       Running   0          1h
kube-system   kube-svc-redirect-xnzk2                 1/1       Running   0          1h
kube-system   kube-svc-redirect-zw552                 1/1       Running   0          1h
kube-system   kubernetes-dashboard-2898242510-pcr6z   1/1       Running   0          1h
kube-system   tunnelfront-2635781678-klwmk            1/1       Running   0          1h

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
azure-cli (2.0.26) 

acr (2.0.20)
acs (2.0.25)
advisor (0.1.1)
appservice (0.1.25)
backup (1.0.6)
batch (3.1.9)
batchai (0.1.5)
billing (0.1.7)
cdn (0.0.12)
cloud (2.0.12)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.26)
cosmosdb (0.1.17)
dla (0.0.18)
dls (0.0.19)
eventgrid (0.1.9)
extension (0.0.8)
feedback (2.0.8)
find (0.2.8)
interactive (0.3.15)
iot (0.1.16)
keyvault (2.0.17)
lab (0.0.16)
monitor (0.1.1)
network (2.0.22)
nspkg (3.0.1)
profile (2.0.18)
rdbms (0.0.11)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.22)
role (2.0.17)
servicefabric (0.0.9)
sql (2.0.20)
storage (2.0.24)
vm (2.0.25)

Python location '/opt/az/bin/python3'
Extensions directory '/home/ekornev/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Jan 26 2018, 16:16:50) 
[GCC 4.8.4]

Legal docs and information: aka.ms/AzureCliLegal
__

installed via "apt install"
Ubuntu 16.04 LTS
SHELL=/bin/bash

```

**Comment by mboersma** [comment]
@eskornev this looks like the same issue as Azure/AKS#159. For now, you may be able to work around it by updating your `kubectl` client to a more recent one as described there. We merged a fix in #5462 that will be in the next `az` release.
