### ISSUE TITLE
"az billing invoice list" requires optin

### ISSUE THREAD

**Issue by sethusrinivasan** [Azure/azure-cli#5471]
<del>Can you please add link to documentation on how to opt-in to download invoices via azure CLI?</del>

Can there be an command in Azure CLI to opt-in?. It looks like going through UI pages again to opt-in seems like extra work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8866b243-5c18-7e9a-f233-0033d0eb64f9
* Version Independent ID: c98a81e3-ec68-5819-4a8f-897043f97371
* [Content](https://docs.microsoft.com/en-us/cli/azure/billing/invoice?view=azure-cli-latest)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-billing/azure/cli/command_modules/billing/_help.py)
* Service: unspecified

**Comment by rukiaEnix** [comment]
running az billing invoice list gives following error:
`ERROR: DisallowedProvider - The operation is not permitted for namespace 'Microsoft.Billing'. List of permitted provider namespaces is '84codes.CloudAMQP,AppDynamics.APM,Aspera.Transfers,Auth0.Cloud,Citrix.Cloud,Citrix.Services,Conexlink.MyCloudIT,Crypteron.DataSecurity,Dynatrace.DynatraceSaaS,Dynatrace.Ruxit,Hive.Streaming,Incapsula.Waf,LiveArena.Broadcast,Lombiq.DotNest,Mailjet.Email,Microsoft.AAD,Microsoft.ADHybridHealthService,Microsoft.Advisor,Microsoft.AlertsManagement,Microsoft.AnalysisServices,Microsoft.ApiManagement,Microsoft.Authorization,Microsoft.Automation,Microsoft.AzureActiveDirectory,Microsoft.AzureStack,Microsoft.BareMetal,Microsoft.Batch,Microsoft.BatchAI,Microsoft.BingMaps,Microsoft.Blockchain,Microsoft.Blueprint,Microsoft.BotService,Microsoft.Cache,Microsoft.Capacity,Microsoft.Cdn,Microsoft.CertificateRegistration,Microsoft.ClassicStorage,Microsoft.CognitiveServices,Microsoft.Compute,Microsoft.Consumption,Microsoft.ContainerInstance,Microsoft.ContainerRegistry,Microsoft.ContainerService,Microsoft.ContentModerator,Microsoft.CostManagement,Microsoft.CustomerLockbox,Microsoft.DataBox,Microsoft.DataBoxEdge,Microsoft.Databricks,Microsoft.DataCatalog,Microsoft.DataFactory,Microsoft.DataLakeAnalytics,Microsoft.DataLakeStore,Microsoft.DataMigration,Microsoft.DataShare,Microsoft.DBforMariaDB,Microsoft.DBforMySQL,Microsoft.DBforPostgreSQL,Microsoft.Devices,Microsoft.DevSpaces,Microsoft.DevTestLab,Microsoft.DocumentDB,Microsoft.DomainRegistration,Microsoft.EventGrid,Microsoft.EventHub,Microsoft.Features,Microsoft.Functions,Microsoft.Genomics,Microsoft.HDInsight,Microsoft.ImportExport,microsoft.insights,Microsoft.IoTCentral,Microsoft.IoTSpaces,Microsoft.KeyVault,Microsoft.Kusto,Microsoft.LabServices,Microsoft.LocationBasedServices,Microsoft.LogAnalytics,Microsoft.Logic,Microsoft.MachineLearning,Microsoft.MachineLearningExperimentation,Microsoft.MachineLearningCompute,Microsoft.MachineLearningServices,Microsoft.MachineLearningModelManagement,Microsoft.ManagedIdentity,Microsoft.ManagedLab,Microsoft.Management,Microsoft.ManagementPartner,Microsoft.Maps,Microsoft.Marketplace,Microsoft.MarketplaceApps,Microsoft.MarketplaceOrdering,Microsoft.Media,Microsoft.Migrate,Microsoft.MixedReality,Microsoft.Network,Microsoft.NotificationHubs,Microsoft.OffAzure,Microsoft.OperationalInsights,Microsoft.OperationsManagement,Microsoft.PolicyInsights,Microsoft.Portal,Microsoft.PowerBI,Microsoft.PowerBIDedicated,Microsoft.RecoveryServices,Microsoft.Relay,Microsoft.ResourceGraph,Microsoft.ResourceGraph.PPE,Microsoft.ResourceHealth,Microsoft.Resources,Microsoft.ResourcesTopology,Microsoft.ResourcesTopology.PPE,Microsoft.SaaS,Microsoft.Scheduler,Microsoft.Search,Microsoft.Security,Microsoft.SecurityGraph,Microsoft.SerialConsole,Microsoft.ServiceBus,Microsoft.ServiceFabric,Microsoft.ServiceFabricMesh,Microsoft.SignalRService,Microsoft.SiteRecovery,Microsoft.Solutions,Microsoft.Sql,Microsoft.SqlVirtualMachine,Microsoft.Storage,Microsoft.StorageSync,Microsoft.StorSimple,Microsoft.StreamAnalytics,Microsoft.Subscription,microsoft.support,Microsoft.TimeSeriesInsights,microsoft.visualstudio,Microsoft.Web,Microsoft.WindowsIoT,Microsoft.WorkloadMonitor,Myget.PackageManagement,nuubit.nextgencdn,Paraleap.CloudMonix,Pokitdok.Platform,RavenHq.Db,Raygun.CrashReporting,RevAPM.MobileCDN,Sendgrid.Email,Sparkpost.Basic,stackify.retrace,SuccessBricks.ClearDB,TrendMicro.DeepSecurity,U2uconsult.TheIdentityHub'.", "stderr_lines": ["ERROR: DisallowedProvider - The operation is not permitted for namespace 'Microsoft.Billing'. List of permitted provider namespaces is '84codes.CloudAMQP,AppDynamics.APM,Aspera.Transfers,Auth0.Cloud,Citrix.Cloud,Citrix.Services,Conexlink.MyCloudIT,Crypteron.DataSecurity,Dynatrace.DynatraceSaaS,Dynatrace.Ruxit,Hive.Streaming,Incapsula.Waf,LiveArena.Broadcast,Lombiq.DotNest,Mailjet.Email,Microsoft.AAD,Microsoft.ADHybridHealthService,Microsoft.Advisor,Microsoft.AlertsManagement,Microsoft.AnalysisServices,Microsoft.ApiManagement,Microsoft.Authorization,Microsoft.Automation,Microsoft.AzureActiveDirectory,Microsoft.AzureStack,Microsoft.BareMetal,Microsoft.Batch,Microsoft.BatchAI,Microsoft.BingMaps,Microsoft.Blockchain,Microsoft.Blueprint,Microsoft.BotService,Microsoft.Cache,Microsoft.Capacity,Microsoft.Cdn,Microsoft.CertificateRegistration,Microsoft.ClassicStorage,Microsoft.CognitiveServices,Microsoft.Compute,Microsoft.Consumption,Microsoft.ContainerInstance,Microsoft.ContainerRegistry,Microsoft.ContainerService,Microsoft.ContentModerator,Microsoft.CostManagement,Microsoft.CustomerLockbox,Microsoft.DataBox,Microsoft.DataBoxEdge,Microsoft.Databricks,Microsoft.DataCatalog,Microsoft.DataFactory,Microsoft.DataLakeAnalytics,Microsoft.DataLakeStore,Microsoft.DataMigration,Microsoft.DataShare,Microsoft.DBforMariaDB,Microsoft.DBforMySQL,Microsoft.DBforPostgreSQL,Microsoft.Devices,Microsoft.DevSpaces,Microsoft.DevTestLab,Microsoft.DocumentDB,Microsoft.DomainRegistration,Microsoft.EventGrid,Microsoft.EventHub,Microsoft.Features,Microsoft.Functions,Microsoft.Genomics,Microsoft.HDInsight,Microsoft.ImportExport,microsoft.insights,Microsoft.IoTCentral,Microsoft.IoTSpaces,Microsoft.KeyVault,Microsoft.Kusto,Microsoft.LabServices,Microsoft.LocationBasedServices,Microsoft.LogAnalytics,Microsoft.Logic,Microsoft.MachineLearning,Microsoft.MachineLearningExperimentation,Microsoft.MachineLearningCompute,Microsoft.MachineLearningServices,Microsoft.MachineLearningModelManagement,Microsoft.ManagedIdentity,Microsoft.ManagedLab,Microsoft.Management,Microsoft.ManagementPartner,Microsoft.Maps,Microsoft.Marketplace,Microsoft.MarketplaceApps,Microsoft.MarketplaceOrdering,Microsoft.Media,Microsoft.Migrate,Microsoft.MixedReality,Microsoft.Network,Microsoft.NotificationHubs,Microsoft.OffAzure,Microsoft.OperationalInsights,Microsoft.OperationsManagement,Microsoft.PolicyInsights,Microsoft.Portal,Microsoft.PowerBI,Microsoft.PowerBIDedicated,Microsoft.RecoveryServices,Microsoft.Relay,Microsoft.ResourceGraph,Microsoft.ResourceGraph.PPE,Microsoft.ResourceHealth,Microsoft.Resources,Microsoft.ResourcesTopology,Microsoft.ResourcesTopology.PPE,Microsoft.SaaS,Microsoft.Scheduler,Microsoft.Search,Microsoft.Security,Microsoft.SecurityGraph,Microsoft.SerialConsole,Microsoft.ServiceBus,Microsoft.ServiceFabric,Microsoft.ServiceFabricMesh,Microsoft.SignalRService,Microsoft.SiteRecovery,Microsoft.Solutions,Microsoft.Sql,Microsoft.SqlVirtualMachine,Microsoft.Storage,Microsoft.StorageSync,Microsoft.StorSimple,Microsoft.StreamAnalytics,Microsoft.Subscription,microsoft.support,Microsoft.TimeSeriesInsights,microsoft.visualstudio,Microsoft.Web,Microsoft.WindowsIoT,Microsoft.WorkloadMonitor,Myget.PackageManagement,nuubit.nextgencdn,Paraleap.CloudMonix,Pokitdok.Platform,RavenHq.Db,Raygun.CrashReporting,RevAPM.MobileCDN,Sendgrid.Email,Sparkpost.Basic,stackify.retrace,SuccessBricks.ClearDB,TrendMicro.DeepSecurity,U2uconsult.TheIdentityHub'`

**Comment by RakeshMohanMSFT** [comment]
Please upgrade latest version of azure cli.
