### ISSUE TITLE
Recursivley List Files

### ISSUE THREAD

**Issue by chanaka-jostle** [Azure/azure-cli#5474]
Hello,

Can you please tell me how to recursively list all files in file container using the cli? az storage file list will not list files in directories without me having to explicitly indicate which directory but sub folders that have files won't be listed. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c633bcb6-d7c0-8bfe-76b6-c69fed9eaf90
* Version Independent ID: 6b2e9a7e-c75f-0b48-0794-acd0ba474eba
* [Content](https://docs.microsoft.com/en-us/cli/azure/storage/file?view=azure-cli-latest#az_storage_file_list)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py)
* Service: storage

**Comment by chanaka-jostle** [comment]
Hello TJPREScott,

Can I please get an answer to my question soon?

Thanks

**Comment by tjprescott** [comment]
@troydai @williexu

**Comment by troydai** [comment]
There isn't a command recursively list all the content in a file share. You need to script `az storage file list` multiple times to list all files in a share. The other option is to mount the file share in your OS and list files. https://docs.microsoft.com/en-us/azure/storage/files/storage-how-to-use-files-windows

**Comment by chanaka-jostle** [comment]
Hello Troy,

Thanks, can you guys add that feature request to your backlog? It would be
really handy. AWS cli has that feature and it saves a lot of time.

**Comment by chanaka-jostle** [comment]
@troydai @williexu If I called az storage blob list without --num-results  on a blob container would it list all the files if I had over 100000 + blob files?

Thanks

**Comment by williexu** [comment]
@chanaka-jostle yes, it would.

**Comment by chanaka-jostle** [comment]
Thanks for the reply!

**Comment by haitsongmsft** [comment]
Where were we on this feature? This is too wierd in first place that the fileshare has to behave differently on listing, finding.
