### ISSUE TITLE
the command 'az vm list-skus' is invalid in Azure Stack env

### ISSUE THREAD

**Issue by leifei87** [Azure/azure-cli#5477]
Azure-cli version:  2.0.26
Env: Azure Stack
Hit the following issue when executing the command 'az vm list-skus -l shanghai'

az vm: error: argument _subcommand: invalid choice: list-skus

**Comment by tjprescott** [comment]
Hi @leifei87 the reason you get this message is because the Compute API version currently supported by stack does not have the endpoint for listing SKUs.  Look for it to be supported in a future version of Stack.
