### ISSUE TITLE
Add warning to DNS zone file import when right hand side is composed fully of relative names

### ISSUE THREAD

**Issue by karravi-msft** [Azure/azure-cli#5479]
Ref - https://docs.microsoft.com/en-us/azure/dns/dns-import-export

The above link mentions a frequent error with godaddy zone files since the values are all relative names without the terminating '.' and hence get appended to the zone name when the record is constructed.

It would be good to add  a warning for customers so that they can correct the zone file if needed. 
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by yonzhan** [comment]
@MyronFanQiu  add to S162.

**Comment by jsntcy** [comment]
![image](https://user-images.githubusercontent.com/16348853/77607843-8526bb00-6f56-11ea-8db7-bcd6eb4cb428.png)
It seems GoDaddy has fixed their zone file format, so close this issue.
If there are similar requests in the future, we can reopen this as an improvement request.
