### ISSUE TITLE
Storage account update with --use-domain incorrect?

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#5500]
https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/operations/account.py#L101

This should be `domain.use_sub_domain` according to this https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-storage/azure/mgmt/storage/v2017_10_01/models/custom_domain.py#L39.

I haven't tried it out but the code looks suspect.

**Comment by williexu** [comment]
Fixed with: https://github.com/Azure/azure-cli/commit/438ed0c66ff96677830f1433004614baad1ad5cf
