### ISSUE TITLE
Authentification Roadmap

### ISSUE THREAD

**Issue by fabienvauchelles** [Azure/azure-cli#5505]
Hello,

I don't know if it is the right place to ask this question :)

Do you know if there is a roadmap around Microsoft SSO authentication (https://login.microsoftonline.com)?

We need to know if the page is modified because many of our developments are based on this authentication (a robot fills in the login and the password).

Thanks,
Fabien.

**Comment by tjprescott** [comment]
@yugangw-msft

**Comment by fabienvauchelles** [comment]
Hello, 
I found the answer: https://github.com/OfficeDev/office-js/issues/58#issuecomment-363863803
Thanks,
Fabien
