### ISSUE TITLE
Should validate the name when using --dryrun argument in az webapp new

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-cli#5527]
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by tjprescott** [comment]
This should go in the https://github.com/Azure/azure-cli-extensions repo where the extension lives.
