### ISSUE TITLE
rerunning the az webapp new without the -l argument should update the app regardless of the resource group

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-cli#5528]
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by tjprescott** [comment]
This should go in the https://github.com/Azure/azure-cli-extensions repo where the extension lives.
