### ISSUE TITLE
Create az functionapp new

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-cli#5529]
Have the same experience like `az webapp new` for function apps
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by tjprescott** [comment]
This should go in the https://github.com/Azure/azure-cli-extensions repo where the extension lives.
