### ISSUE TITLE
Add coloring to the json output of az webapp new

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-cli#5531]
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by tjprescott** [comment]
This should go in the https://github.com/Azure/azure-cli-extensions repo where the extension lives.

**Comment by tjprescott** [comment]
For clarification, the `Extensions` label is intended for issues related to the extension framework.  Issues/requests to existing extensions should be made in the repo where the extension lives.

**Comment by panchagnula** [comment]
@tjprescott thanks for the info. However I see that https://github.com/Azure/azure-cli-extensions/issues currently has extension framework issues tracked here. That was the reason we went ahead with adding the issues here.
