### ISSUE TITLE
Need az functionapp config ssl import command

### ISSUE THREAD

**Issue by AnikShen** [Azure/azure-cli#5533]
---

### Need new command to import Azure Service Certificate for Azure App Service 

Now we can only import App Service Certificate from Azure App Service portal

Azure CLI command for it is missing. we only have upload command 
https://docs.microsoft.com/en-us/azure/azure-functions/scripts/functions-cli-configure-ssl-certificate
az functionapp config ssl upload
az webapp  config ssl upload

How about 
az functionapp config ssl import
az webapp  config ssl import

```
```

**Comment by stagrlee** [comment]
Surprised the BIND won't work since the certificate thumbprint already exists....  Agree "import" will fix the issue.

`az webapp config ssl bind --name myappname --resource-group mygrpname --certificate-thumbprint BE0A2Cxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --ssl-type SNI
ERROR: Certificate for thumbprint 'BE0A2Cxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' not found.`

**Comment by stagrlee** [comment]
@panchagnula - any updates on this issue?

**Comment by panchagnula** [comment]
@stagrlee  don't have an ETA for this as yet.

**Comment by bennovakovic** [comment]
I would also REALLY like this.

At this stage the only solution is to boot up a windows VM, use PowerShell to export it; and then reimport it as a PFX file; which breaks the automation rule.

Other solutions include scripting a clickthrough via phantomJS, which is flakey at the best of times.

How does this not exist yet? Is there really so few people who use wildcard domains?

**Comment by DarinMacRae** [comment]
I just ran into this issue because we have a cert expiring soon and without it will have to manually update >30 sites (plus slots). Any good news for me?

**Comment by Djiit** [comment]
Upvoting this, as this is the last part we can't automate here.

**Comment by janustoth** [comment]
I would also like to upvote this.

**Comment by panchagnula** [comment]
//CC: @ahmedelnably

**Comment by kamperiadis** [comment]
Closing this as it is already supported.
