### ISSUE TITLE
FREE tier reported as invalid sku

### ISSUE THREAD

**Issue by camerican** [Azure/azure-cli#5538]
Azure CLI v2.0.26 is reporting that "FREE" is an invalid sku.  The following command:

az appservice list-locations --skuFREE

results in the following error:

az appservice list-locations: error: the following arguments are required: --sku

This is not a big deal since we can use F1 for the sku to get the same data, but it would be great if the behavior aligned with this document since FREE is listed as being a valid option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9dc8c24-cda6-8672-8017-b66435eadbb7
* Version Independent ID: a0be523a-ff1f-18ed-0fc4-ba0e0befe4d1
* [Content](https://docs.microsoft.com/en-us/cli/azure/appservice?view=azure-cli-latest#az_appservice_list_locations)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py)
* Service: app-service

**Comment by camerican** [comment]
Edit: The relevant command/error is:

az appservice list-locations --sku FREE

with the error:

Invalid sku(pricing tier), please refer to command help for valid values

**Comment by ahmedelnably** [comment]
@camerican this is indeed an issue, we will fix it soon, in the meanwhile please use
F1 as the SKU to target Free
