### ISSUE TITLE
Application Insights resources

### ISSUE THREAD

**Issue by rcarmo** [Azure/azure-cli#5543]
Is there a roadmap for creating App Insights resources via the CLI without resorting to `resource create`?

**Comment by rcarmo** [comment]
For the record, this is how I'm doing it now. But being able to do this in a cleaner way and also having a command to create and retrieve application instrumentation keys would be nice:

```bash
	az resource create \
		--resource-group $RESOURCE_GROUP \
		--resource-type "Microsoft.Insights/components" \
		--name $NAMESPACE_PREFIX-appinsights \
		--location $PRIMARY_LOCATION \
		--properties '{"ApplicationId":"facerecognition","Application_Type":"other", "Flow_Type":"Redfield", "Request_Source":"IbizaAIExtension"}'
```

**Comment by tjprescott** [comment]
Thanks for your interest @rcarmo.

cc/ @mayurid @twitchax

**Comment by kizotheitguy** [comment]
Thanks for the command..
The below should help retrieve application instrumentation keys 
```
az resource show -g $RESOURCEGROUPNAME -n $APPLICATION_NAME --resource-type "Microsoft.Insights/components" --query properties.InstrumentationKey
```

**Comment by Dave76** [comment]
Thanks for the tips, but any ETA on when there will be an az insights cli command?

**Comment by Jarlotee** [comment]
Does anyone know how to create an API key through the CLI?

**Comment by arjenbloemsma** [comment]
This does work. However, when I "connect" the resulting Application Insights to an app service (function app) by using the instrumentation key the Application Map seems not to work. Any ideas on that?

**Comment by nikmd23** [comment]
I've looped in the right people at MS to see this thread!

**Comment by markheath** [comment]
@kuvinodms  It can be really hard to escape the properties JSON correctly. So I tend to save it to a JSON file and then pass it to the Azure CLI with the  `--properties @props.json` syntax

Here's an example using PowerShell and the Azure CLI:
```
'{"Application_Type":"web"}' | Out-File props.json
az resource create `
    -g $resourceGroup -n $appInsightsName `
    --resource-type "Microsoft.Insights/components" `
    --properties "@props.json"
```

see my article [here](https://markheath.net/post/deploying-azure-functions-with-azure-cli)

**Comment by zakimaksyutov** [comment]
Thank you @markheath, file approach did work for me.

**Comment by NicoSorrenti** [comment]
The file approach works just as expected, but if you anybody wants to use the command in PowerShell without writing to a file, the JSON can be escaped adding a \ in the double quotes works, like this:

`az resource create --resource-group myresourcegroup --name myappinsights --resource-type Microsoft.Insights/components --location southcentralus --properties '{\"Application_Type\":\"web\"}'`
(taking the @kuvinodms code as an example)

**Comment by markheath** [comment]
@NicoSorrenti thanks - I thought I'd tried that, but I'll give it another go. Would be nice to simplify that.

**Comment by yugangw-msft** [comment]
Closing. PR made from @alexeldeib has taken care of this.
To use it, please run "az extension add -n application-insights", and you will see related commands under `monitor app-insights`. Once commands are stabilized, we will move them to CLI's core monitor command module
