### ISSUE TITLE
No equivalent to -WhatIf flag in Azure CLI for Azure deployments

### ISSUE THREAD

**Issue by stewartadam** [Azure/azure-cli#5549]
Azure CLI has no equivalent to the `-WhatIf` flag in the Azure PowerShell cmdlets to print what would happen if a template were to be deployed.

This is a feature often requested from users of Terraform, where they want to see what some local changes to the template would do if deployed.

We should add a `--dry-run` flag to `az group deployment create`.

---

### Environment summary
```
azure-cli (2.0.26) via MSI installer
```

**Comment by tjprescott** [comment]
Have you tried `az group deployment validate`? Does that differ from what you are expecting?

**Comment by stewartadam** [comment]
`az group deployment validate` tells you if the deployment is syntactically correct, but not what the execution of the deployment it would do. This is the often asked for feature that terraform has (terraform plan).

**Comment by yugangw-msft** [comment]
This will come from ARM service end

**Comment by rickardp** [comment]
Is this functionality implemented on the server side already, or how does Powershell do it?

**Comment by alex-frankel** [comment]
The -WhatIf powershell cmdlet is not actually doing what was described in the issue. It doesn't preview what the deployment is going to do. -WhatIf is a standard flag for many powershell cmdlets.

Having said that, the feature you are describing is being worked on as we speak :) We are hoping to have a public preview available of ARM template what-if for both powershell and CLI by Ignite of this year. Will update this issue when that is done.

**Comment by jochenvw** [comment]
> The -WhatIf powershell cmdlet is not actually doing what was described in the issue. It doesn't preview what the deployment is going to do. -WhatIf is a standard flag for many powershell cmdlets.
> 
> Having said that, the feature you are describing is being worked on as we speak :) We are hoping to have a public preview available of ARM template what-if for both powershell and CLI by Ignite of this year. Will update this issue when that is done.

Ignite was this week - any news @alex-frankel ?

**Comment by alex-frankel** [comment]
We announced a private preview that will be starting this week. PowerShell will be first, closely followed by Az CLI.

More info here: https://aka.ms/MicrosoftIgnite2019/BRK3233

Sign ups for private preview are here: https://aka.ms/ARMTemplatePreviews

**Comment by jochenvanwylick** [comment]
@alex-frankel - great ! I'll get my customer to sign up. Thanks.

**Comment by svdHero** [comment]
Any update on this? I've seen the `-WhatIf` being used with Powershell in this [Azure Master Class video](https://youtu.be/wR92fLyrW6I?t=2600).
Is this already available with the Azure CLI and if yes, how would I use it? I am using Bash and do not want to learn Powershell, but use the Azure CLI instead.

**Comment by asdkant-bf** [comment]
I just tried to use it and I get:
> `unrecognized arguments: --what-if`

**Comment by Raymondo73** [comment]
I get exactly the same error as @asdkant-bf using the following `az policy exemption create` and the error:
`unrecognized arguments: --what-if`

I've also tried `--confirm-with-what-if` and that yields the same error

**Comment by jj-halfspace** [comment]
I was able to get the --what-if parameter working in the following command:
az deployment group create --what-if --resource-group <resource group name> --template-file main.bicep 

and it shows the changes without deploying them
