### ISSUE TITLE
BLOCKED VM scaleset : support generic extension and enable auto-scale

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#555]
3 things:
1. Generic extension is asked by VS diagnostic team, so users at least have a way (might not convenient) to install extensions on VM instances, including the diagnostics 
2. Enable AutoScale. Recommended by VMSS team
3. Investigate to have VMSS custom commands to share same implementation with VM's. This is mainly for code maintenance -- the interfaces are too different unfortunately, so the code will simply mirror each other

- [x] enable diagnostics on vm profile
- [x] install extension on vm profile
- [ ] enable autoscale in separate command (not in create)
- [ ] show available autoscale metrics

**Comment by BurtBiel** [comment]
Blocked because there is no SDK support for autoscale.  Confirming with the SDK team.

**Comment by BurtBiel** [comment]
Confirmed there is no SDK support for autoscale, so that has been split out into issue #815 and this work is complete
