### ISSUE TITLE
Remove all rules

### ISSUE THREAD

**Issue by yzhang-myob** [Azure/azure-cli#5561]
Can we have an options to clear all network rules?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac52f120-deaa-0a12-3663-8bf51cbbd234
* Version Independent ID: b7e2694c-c7be-8d1f-da00-fdd8b60f327e
* [Content](https://docs.microsoft.com/en-us/cli/azure/storage/account/network-rule?view=azure-cli-latest#az_storage_account_network_rule_remove)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py)
* Service: storage

**Comment by williexu** [comment]
Users can use the following to clear their ip network rules: `az storage account update -n wilxstorage --set networkRuleSet.ipRules=[]`. The same is true for virtual network rules. 

Closing this as there are easy alternatives.
