### ISSUE TITLE
users in some organization cannot get subscription info after login

### ISSUE THREAD

**Issue by Eskibear** [Azure/azure-cli#5566]
For some organizations, the environment consists more than one AAD tenants.

 E.g. for KPMG, it seems they have 2 tenants, one tenant holds AAD objects, and another holds Azure resources. MFA is enabled in both tenants. AzureCLI cannot successfully get azure resources. 

Refer to:
https://github.com/Microsoft/azure-tools-for-java/issues/1332#issuecomment-360107109

FYI,
The users can log into Azure portal, but are asked to provide MFA code **twice**. 

Any clue?

**Comment by Eskibear** [comment]
> Failed to authenticate '{'id': '/tenants/xxx', 'tenant_id': 'xxx'}' due to error 'Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'xxx'.\r\nTrace ID: xxx\r\nCorrelation ID: xxx\r\nTimestamp: 2018-01-24 11:43:21Z","error_codes":[50076],"timestamp":"2018-01-24 11:43:21Z","trace_id":"xxx","correlation_id":"xxx"}'
No subscriptions were found for 'None'. If this is expected, use '--allow-no-subscriptions' to have tenant level accesses

Above is the error message they got.

**Comment by tjprescott** [comment]
@yugangw-msft

**Comment by yonzhan** [comment]
add to S165.

**Comment by jiasli** [comment]
@Eskibear, could you try clearing the browser cache and run `az login` again? It also may be possible the `common` tenant for your account doesn't require MFA. In that case, you may try `az login --tenant` to directly login to the tenant that requires MFA.

**Comment by Eskibear** [comment]
>  could you try clearing the browser cache and run az login again?

No need. We tried before. I'm sure that it was not the cache issue. 

Azure Tools for Java was using exactly the same way with Azure CLI (if you didn't change it) to login for users. For KPMG customers were experiencing the issue as both two of their tenants requires MFA. There must be case uncovered, and that was the reason I open this issue.

**Comment by jiasli** [comment]
That is indeed very strangle. Microsoft tenant also requires MFA and we didn't see any issue. Does logging in with `--tenant` work? Also could you capture `--debug` log during `az login` and send the result to my email? Thanks.
