### ISSUE TITLE
az storage blob url returns urls for blobs that don't exist.

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#5567]
Shouldn't it fail if the blob doesn't actually exist?

**Comment by tjprescott** [comment]
I believe this is an SDK utility function that just concatenates strings. GIGO.  We could wrap the SDK and do an exists check though.

**Comment by williexu** [comment]
Since the current behavior has not been met with much customer opposition and changing the behavior may potentially break users, I will close this issue for now.
