### ISSUE TITLE
What are the allowed values for --included-event-types?

### ISSUE THREAD

**Issue by polarapfel** [Azure/azure-cli#5572]
Other than "All", what other values are allowed and is there a way to query for that enumeration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63e73e1b-aad9-0ce8-be1f-a9b9d02ca6d4
* Version Independent ID: 73525c5f-94f3-1c07-e3b6-3a022aab2a10
* [Content](https://docs.microsoft.com/en-us/cli/azure/eventgrid/event-subscription?view=azure-cli-latest#az_eventgrid_event_subscription_create)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-eventgrid/azure/cli/command_modules/eventgrid/_help.py)
* Service: unspecified

**Comment by ahamad-MS** [comment]
@polarapfel  

Thanks for reporting this issue/question.

The list that can be used with --included-event-types depends on the topic type. For custom topic, you will need to contact the topic owner to know this list as this is controlled by the user himself. For specific Azure Resource Publisher (e.g., StorageAccounts, IoT Hub, Azure Maps, etc), these are documented here: https://docs.microsoft.com/bs-latn-ba/azure/event-grid/event-schema

Also, you can query these specific information using the following CLI command (using StorageAccount as an example):

>az eventgrid topic-type list-event-types -n microsoft.storage.storageaccounts
The behavior of this command has been altered by the following extension: eventgrid
[
  {
    "description": "Raised when a blob is created.",
    "displayName": "Blob Created",
    "id": "providers/Microsoft.EventGrid/topicTypes/Microsoft.Storage.StorageAccounts/eventTypes/Microsoft.Storage.BlobCreated",
    "isInDefaultSet": true,
    "name": "Microsoft.Storage.BlobCreated",
    "schemaUrl": "https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/eventgrid/data-plane/Microsoft.Storage/stable/2018-01-01/Storage.json",
    "type": "Microsoft.EventGrid/topicTypes/eventTypes"
  },
  {
    "description": "Raised when a blob is deleted.",
    "displayName": "Blob Deleted",
    "id": "providers/Microsoft.EventGrid/topicTypes/Microsoft.Storage.StorageAccounts/eventTypes/Microsoft.Storage.BlobDeleted",
    "isInDefaultSet": true,
    "name": "Microsoft.Storage.BlobDeleted",
    "schemaUrl": "https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/eventgrid/data-plane/Microsoft.Storage/stable/2018-01-01/Storage.json",
    "type": "Microsoft.EventGrid/topicTypes/eventTypes"
  }
]

Thanks
