### ISSUE TITLE
az container create environment variables does not parse values with ampersand correctly

### ISSUE THREAD

**Issue by moenkhaus** [Azure/azure-cli#5573]
I am attempting to pass in environment variables to az container create command. When a value has an ampersand contained within it, the environment variables cut out the remainder of the value and subsequent key/values that follow.

**Environment**

Powershell 5.1.16299.98
Azure Client 2.0 (https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest)

**Powershell script**

az container create `
    --resource-group <resourceGroup> `
    --name <name> `
    --image <image> `
    --cpu 1 `
    --memory 1 `
    --registry-password <registryPassword> `
    --ip-address public `
    --ports <port> `
    --environment-variables Key1="value1&value2" Key2=value3

**Current output**

"containers": [
{
    "command": null,
    "environmentVariables": [
        {
            "name": "Key1",
            "value": "value1"
        }
    ]
    ..

**Expected output**

"containers": [
{
    "command": null,
    "environmentVariables": [
        {
            "name": "Key1",
            "value": "value1&value2"
        },
        {
            "name": "Key2",
            "value": "value3"
        },
    ]
    ..

Update #1

Also in the current output is the following error message, I presume due to again how it's parsing.

'Value2' is not recognized as an internal or external command,
operable program or batch file.

Do I need to escape the string somehow?

# update 2

When running in interactive mode (without the "`" line breaks") the environment variables run as expected. I tried removing the line breaks in powershell just the same but am presented with the same error.

# update 3

works in normal command prompt, issue appears restricted to powershell

**Comment by moenkhaus** [comment]
Also in the current output is the following error message, I presume due to again how it's parsing.

'Value2' is not recognized as an internal or external command,
operable program or batch file.

Do I need to escape the string somehow?

**Comment by moenkhaus** [comment]
When running in interactive mode (without the  "`" line breaks") the environment variables run as expected. I tried removing the line breaks in powershell just the same but am presented with the same error.

**Comment by EstebanSmits** [comment]
Had issues with ampersand's myself today.
Try using the format : 
az container create   -e 'key:"value"' 
A small write up is available here with my own personal error and results:  [http://daxmax.com/azure-cli-format-for-environment-variables-with-problematic-characters/]

**Comment by tjprescott** [comment]
Ampersand is used as the call operator in Powershell. https://ss64.com/ps/call.html  You need to escape the ampersand characters.

**Comment by stmax82** [comment]
@EstebanSmits are you sure it's -e 'key:"value"'?

I had to replace the colon with an equals sign to make it work:

Trying to set:

`GF_DATABASE_URL=sqlite3://data/mygrafana.db?cache=private&mode=rwc&_journal_mode=WAL`

requires:

`-e 'GF_DATABASE_URL="sqlite3://data/mygrafana.db?cache=private&mode=rwc&_journal_mode=WAL"'`
