### ISSUE TITLE
Unable to set data disk caching when deploying VM via CLI commands

### ISSUE THREAD

**Issue by MukeshNandaMS** [Azure/azure-cli#5579]
One of the user is trying to attach an existing Data disk while creating the VM. It fails if disk caching parameter is provided, but completes fine without this parameter.

CLI (2.0.26)
az vm create `
  --validate `
  --resource-group $rg
  --name $pa
  --size $size 
  --location $loc
  --image $img
  --os-disk-name $osdk
  --use-unmanaged-disk
  --attach-data-disks $dtdk`
  --data-disk-caching 'ReadOnly'
  --storage-account $stract
  --storage-container-name $strcont
  --storage-sku $strsku
  --admin-username $usr
  --admin-password $pwd

Error:

az : ERROR: invalid usage for storage profile: create unmanaged OS disk from Azure Marketplace image:
At \\deploy_vm.ps1:45 char:1
+ az vm create `
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: invalid ...ketplace image::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

If --data-disk-caching 'ReadOnly'  is removed, it completes the deployment setting the data cache to NONE.

Ask: Is this a known issue where the deployment script fails if DataDisk caching is specified as one of the parameters? Seems applicable if we try to attach an existing DataDisk.

thanks!

**Comment by MukeshNandaMS** [comment]
Would appreciate any help/inputs on this.

**Comment by tjprescott** [comment]
@sauryadas @yugangw-msft

**Comment by sauryadas** [comment]
+ @jluk

**Comment by yugangw-msft** [comment]
Suggest to schedule for Sprint 34
