### ISSUE TITLE
Antimalware Service Executable CPU Spikes

### ISSUE THREAD

**Issue by bhummerstone** [Azure/azure-cli#5586]
Whenever I run an az command in Bash on Windows, the Antimalware Service Executable process spikes for a few seconds, which delays execution of the command significantly. I've tested the same version on a separate laptop running Debian and it is much faster.
---

### Environment summary
apt-get/2.0.26/Windows 10/Bash on Windows 

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by yugangw-msft** [comment]
This is really not actionable from CLI. Closing.
