### ISSUE TITLE
num-results option for az storage blob list

### ISSUE THREAD

**Issue by chanaka-jostle** [Azure/azure-cli#5589]
Hello,

My blob container is expected to have more than 100,000+ blob files. I would like to use az storage blob list to recursively get a list of all blobs in the container. If I do not specify --num-results would I receive the entire list of blobs with my request?

Thanks very much for your help
Chanaka

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by tjprescott** [comment]
Related to #3481.

**Comment by chanaka-jostle** [comment]
Hello TJPREScott,

**Comment by tjprescott** [comment]
Is this different from #5474?

**Comment by chanaka-jostle** [comment]
Hello TJPREScott,

Yes, az storage blob list does seem to work recursively by listing filenames but the documentation is confusing on --num-results option. I would like to get all the results without paging. My container is expected to have over 100,000 + blob files. Will this work if I don't include --num-results option?

Thanks for your help

**Comment by tjprescott** [comment]
@troydai

**Comment by williexu** [comment]
@chanaka-jostle yes, `az storage blob list` will by default list all the blobs in a container (note this might take some time depending on how many blobs you have), we page for all the blobs for you before returning everything. 
Including the `--num-results` parameter will limit the result to whatever you set, with a maximum of 5000 items.

**Comment by chanaka-jostle** [comment]
Thanks for the reply!
