### ISSUE TITLE
deployment with error returns an error code of 0

### ISSUE THREAD

**Issue by assafmendelson** [Azure/azure-cli#5590]
I ran an az group deployment create from a template. Unfortunately the name of one of the resources was already taken and I got a text with an exception.

This is fine by itself as this was indeed an error, however az returned an error code of 0.

This means that I have no way of knowing if the deployment succeeded or not. 

---

### Environment summary

This occurred on ubuntu 16.04 where I installed azure cli directly. I am using bash shell.
I reproduced the same issue in windows 10 with azure cli running from powershell

```
```

**Comment by tjprescott** [comment]
Please provide the output of `az --version`

**Comment by assafmendelson** [comment]
On ubuntu:
azure-cli (2.0.26)

acr (2.0.20)
acs (2.0.25)
advisor (0.1.1)
appservice (0.1.25)
backup (1.0.6)
batch (3.1.9)
batchai (0.1.5)
billing (0.1.7)
cdn (0.0.12)
cloud (2.0.12)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.26)
cosmosdb (0.1.17)
dla (0.0.18)
dls (0.0.19)
eventgrid (0.1.9)
extension (0.0.8)
feedback (2.0.8)
find (0.2.8)
interactive (0.3.15)
iot (0.1.16)
keyvault (2.0.17)
lab (0.0.16)
monitor (0.1.1)
network (2.0.22)
nspkg (3.0.1)
profile (2.0.18)
rdbms (0.0.11)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.22)
role (2.0.17)
servicefabric (0.0.9)
sql (2.0.20)
storage (2.0.24)
vm (2.0.25)

Python location '/opt/az/bin/python3'
Extensions directory '/home/assaf/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Feb  5 2018, 21:31:01) 
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal


On windows:
azure-cli (2.0.26)

acr (2.0.20)
acs (2.0.25)
advisor (0.1.1)
appservice (0.1.25)
backup (1.0.6)
batch (3.1.9)
batchai (0.1.5)
billing (0.1.7)
cdn (0.0.12)
cloud (2.0.12)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.26)
cosmosdb (0.1.17)
dla (0.0.18)
dls (0.0.19)
eventgrid (0.1.9)
extension (0.0.8)
feedback (2.0.8)
find (0.2.8)
interactive (0.3.15)
iot (0.1.16)
keyvault (2.0.17)
lab (0.0.16)
monitor (0.1.1)
network (2.0.22)
nspkg (3.0.1)
profile (2.0.18)
rdbms (0.0.11)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.22)
role (2.0.17)
servicefabric (0.0.9)
sql (2.0.20)
storage (2.0.24)
vm (2.0.25)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\mendea3\.azure\cliextensions'

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by assafmendelson** [comment]
Also the exception I got:

Exception in thread AzureOperationPoller(dc664661-3381-4dd8-9f99-891dfc2ebac0):
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_operation.py", line 377, in _start
    self._poll(update_cmd)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_operation.py", line 464, in _poll
    raise OperationFailed("Operation failed or cancelled")
msrestazure.azure_operation.OperationFailed: Operation failed or cancelled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/az/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_operation.py", line 388, in _start
    self._exception = CloudError(self._response)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 157, in __init__
    self._build_error_data(response)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 173, in _build_error_data
    self.error = self.deserializer('CloudErrorRoot', response).error
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1023, in __call__
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1187, in deserialize_data
    return self(obj_type, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1023, in __call__
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1176, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1203, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1203, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1187, in deserialize_data
    return self(obj_type, data)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1030, in __call__
    return self._instantiate_model(response, d_attrs, additional_properties)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 1132, in _instantiate_model
    response_obj = response(**kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 62, in __init__
    self.message = kwargs.get('message')
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_exceptions.py", line 114, in message
    value = eval(value)
  File "<string>", line 4, in <module>
NameError: name 'null' is not defined

{
  "additionalProperties": {
    "error": {
      "code": "DeploymentFailed",
      "details": [
        {
          "code": "Conflict",
          "message": "{\r\n  \"Code\": \"Conflict\",\r\n  \"Message\": \"Website with given name minerva2 already exists.\",\r\n  \"Target\": null,\r\n  \"Details\": [\r\n    {\r\n      \"Message\": \"Website with given name minerva2 already exists.\"\r\n    },\r\n    {\r\n      \"Code\": \"Conflict\"\r\n    },\r\n    {\r\n      \"ErrorEntity\": {\r\n        \"ExtendedCode\": \"54001\",\r\n        \"MessageTemplate\": \"Website with given name {0} already exists.\",\r\n        \"Parameters\": [\r\n          \"minerva2\"\r\n        ],\r\n        \"Code\": \"Conflict\",\r\n        \"Message\": \"Website with given name minerva2 already exists.\"\r\n      }\r\n    }\r\n  ],\r\n  \"Innererror\": null\r\n}"
        }
      ],
      "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."
    },
    "status": "Failed"
  },
  "id": null,
  "name": null,
  "properties": null
}

**Comment by tjprescott** [comment]
So it looks like there are two issues:
1) The exit code is wrong
2) The error appears as a stack trace.

**Comment by assafmendelson** [comment]
Do note that the exception information goes to stderr while the json response goes to stdout.

**Comment by tjprescott** [comment]
After reproducing this, I have posted an issue in the msrestazure repo https://github.com/Azure/msrestazure-for-python/issues/78.  However, I believe the real culprit might be the service itself as this seems to be a uniquely appservice problem.  Deployment errors for network errors print the error as intended and return exit code 1.

**Comment by alonisser** [comment]
I reproduced this with azure-cli (2.0.54) - trying to incorporate validate in a sane CI pipeline
But hit the problem with the return error code
For example I created a wrong type on parameters file and run:
```bash
az group deployment validate --resource-group redacted --template-file redacted.json --verbose  --parameters parameters.json

> {
>   "error": {
>     "code": "InvalidRequestContent",
>     "details": null,
>     "message": "The request content was invalid and could not be deserialized: 'Could not find member 'defaultValue' on object of type 'DeploymentParameterDefinition'. Path 'properties.parameters.keyData.defaultValue', line 1, position 39098.'.",
>     "target": null
>   },
>   "properties": null
> }
> 

# Then:
echo $?  
0
```

**Comment by panchagnula** [comment]
@tjprescott can you give me more details here on why this is a Appservice issue? can you share the Webapp api that is being used here causing the issue? Thank you.

**Comment by tjprescott** [comment]
@panchagnula it isn't. This is for the deployment create command. I think it was tagged webapps because the user was trying to create one via template. I updated the tags.

**Comment by Juliehzl** [comment]
Hi @alonisser  do you still have wrong exit code problem? If yes, can you share me your tenmplate.json and parameters.json file for reproduce your issue to "zuh at microsoft dot com"?
