### ISSUE TITLE
.Net Core with SqlDb Error

### ISSUE THREAD

**Issue by rberger247** [Azure/azure-cli#5598]
When I navigate to my website I get the following displayed:

An error occurred while starting the application.
.NET Core X86 v4.1.1.0    |   Microsoft.AspNetCore.Hosting version 1.1.2    |    Microsoft Windows 10.0.14393    |   Need help?

The app works on my local host.

I followed the documentation ( https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-dotnet) by step with no changes.

**Comment by tjprescott** [comment]
I get a 404 error when I try to access that link. Were there any CLI commands you were having issues with?

**Comment by yonzhan** [comment]
add to S165.

**Comment by yonzhan** [comment]
move to S166.

**Comment by yonzhan** [comment]
move to S167.

**Comment by yonzhan** [comment]
move to S168

**Comment by yonzhan** [comment]
move to S169

**Comment by yonzhan** [comment]
move to S170

**Comment by panchagnula** [comment]
Not CLI specific closing.
