### ISSUE TITLE
Invalid ARM template gets dropped from create request leading to poor error message

### ISSUE THREAD

**Issue by seanmck** [Azure/azure-cli#560]
I was missing a comma in my ARM template and as a result, it seems that the CLI decided to send my create request onward to the REST API without it, passing only the parameters. This resulted in an error like the following:

*The deployment 'sfsamplesdeploy' must have either the TemplateLink or Template property set. Please see https://aka.ms/arm-deploy for usage details.*

When I tried the same operation in the old CLI, it told me exactly where the syntax error was in the template.

**Comment by johanste** [comment]
Thanks for reporting this. It does look like the failure to parse the json document is incorrectly swallowed by the command execution. I'll get a fix in ASAP.
