### ISSUE TITLE
Move Azure CLI to generic AI event names (such as azure-cli/command-invoke)

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#5600]
In support of our GDPR efforts and requirements, we need to move to generic AI event names.

**Comment by troydai** [comment]
This is done as of today. However, the interactive shell is being refitted to send telemetry to the main source. It will likely introduce a new event name `azurecli/interactive`. If you have any other idea, please suggest. @williexu

**Comment by troydai** [comment]
Done
