### ISSUE TITLE
acs kubernetes get-credentials - [Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by tonybyorick** [Azure/azure-cli#5609]
### Environment summary
CLI Version: azure-cli (2.0.27)
OS Version: Ubuntu 16.04
Shell Type: bash

### CLI COMMAND THAT CREATED ERROR
az acs kubernetes get-credentials --name=$NODE --resource-group=$GROUPNAME

### PROBLEM DESCRIPTION
I've created a kubernetes cluster using azure-cli.  Running **az acs list**  produces JSON output  that includes the line **"provisioningState": "Succeeded",** which indicates the cluster was successfully created. I am now trying to deploy a docker application into the cluster but cannot seem to get kubectl configured locally on my Ubuntu machine.

To install kubectl, I ran **sudo az acs kubernetes install-cli** which produced the message: _Downloading client to /usr/local/bin/kubectl from https://storage.googleapis.com/kubernetes-release/release/v1.9.3/bin/linux/amd64/kubectl_  which looked good and I have verified the kubectl executable is present in /usr/local/bin.

The problem occurs when I run the command to download credentials and configure Kubernetes CLI to use them.  Here is the command:

**az acs kubernetes get-credentials --name=$NODE --resource-group=$GROUPNAME** 

Here is part of the error message:

_[Errno 101] Network is unreachable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 194, in invoke
.
.
.
  File "/opt/az/lib/python3.6/site-packages/paramiko/client.py", line 338, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
OSError: [Errno 101] Network is unreachable_

Any thoughts on this are greatly appreciated

**Comment by mboersma** [comment]
@tonybyorick the `az acs get-credentials` command expects to be able to ssh to the master node. This looks like for some reason the `masterProfile -> fqdn` address isn't reachable from where you are running the CLI. Can you ping or SSH to that address outside of the `az` CLI?

```
az acs list -o jsonc | grep fqdn # find the fully-qualified domain name of the master node
ping maboersmac-maboersm-e220e2mgmt.eastus.cloudapp.azure.com
ssh azureuser@maboersmac-maboersm-e220e2mgmt.eastus.cloudapp.azure.com
```

**Comment by tonybyorick** [comment]
@mboersma , Thanks for your reply..... get nodes is now working, but not sure why....    

```
~$ kubectl get nodes
NAME                    STATUS    ROLES     AGE       VERSION
k8s-agent-596de907-0    Ready     agent     1d        v1.7.7
k8s-master-596de907-0   Ready     master    1d        v1.7.7
```
get nodes began working after I copied the file used as the argument for --file ( `--file=$XDGDIRECTORY/kubeconfig.yaml` ) to `~/kube/config`.

So, seems like kubectl expects output from get-credentials to reside in `~/kube/config` regardless of the --file parameter to get-credentials.  Or maybe there is a command that sets kubectl to look in a specific folder for `kubeconfig.yaml`?
