### ISSUE TITLE
[Generic Update] we should show fields for objects that aren't set

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#561]
Today, we only show available fields on the object being mutated as options for the parameter path.  However, in the case of a VM without data disks, we give no hints as to which properties can be set--the user has to find a VM with a data disk and learn from that pattern.  We should find the SDK object that corresponds to the object (data disk in this case) and show available properties from that object.  This allows users to fill out empty fields without having to find a filled out example first.

**Comment by tjprescott** [comment]
This isn't a bug, as currently we don't have any tab completion on the generic update params.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
