### ISSUE TITLE
Role-assignment: classic administrators

### ISSUE THREAD

**Issue by pjbgf** [Azure/azure-cli#5610]
The documentation shows how to list classic administrators (--include-classic-administrators), however does not provide a way to create nor delete them. Given that the Azure CLI 1 also did not support such functionality, is there any way that this can be automated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dacfad8-cb2f-2534-3b29-89b0930a2252
* Version Independent ID: 17325cd4-44c5-4069-d9f6-940a55f0f7c9
* [Content](https://docs.microsoft.com/en-us/cli/azure/role/assignment?view=azure-cli-latest#feedback)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: azure-resource-manager

**Comment by yugangw-msft** [comment]
@pjbgf, could you please share the 1.0 command which does that?

**Comment by pjbgf** [comment]
@yugangw-msft The command I am talking about is based on Azure CLI 2.0: ```az role assignment list --include-classic-administrators```. However, what I am trying to do is to assign the role of "Classic Administrators" to users. Is that possible by either CLI 1.0 or CLI 2.0?

**Comment by yugangw-msft** [comment]
Sorry for the delay, but it is not possible. There are no such roles. The flag `--include-classic-administrators` is merely a flag to trigger CLI to get the list of old co-admins which should have accesses to everything under the subscription. Within regular roles, the closest is probably the `Owner` role at the scope of subscription.
