### ISSUE TITLE
Issue pushing to azure git with cli created user

### ISSUE THREAD

**Issue by kristaps5** [Azure/azure-cli#5613]
Hi,
I create a deployment user using:
az webapp deployment user set --user-name <username> --password <password>

Then I try to push to the deployment git using: git push azure master
and receive the 403 error that I am forbidden from pushing to that. If I use an incorrect password I receive a 401 error.

When I check the front end, I see that deployment credentials are empty. When I try to add the same username as I created using the above user set command, the platform tells me its a taken user name. 
Running: az webapp deployment user show 

returns

{ "id": null, "kind": null, "name": "web", "publishingPassword": null, "publishingPasswordHash": null, "publishingPasswordHashSalt": null, "publishingUserName": "testUser1234441212", "type": "Microsoft.Web/publishingUsers/web", "userName": null }

When I change the settings manually in the front end "Deployment credentials" under "App Services" and try pushing to git, it all works. 

To conclude, the credentials I create using az webapp deployment user set --user-name <username> --password <password> do not work when pushing to deployment-local-git. Creating a user manually on the front end under "App Services" > "Deployment credentials" and trying that user and password works fine.

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by kristaps5** [comment]
?

**Comment by roosi** [comment]
I have the same issue. 
azure-cli (2.0.26)

**Comment by tjprescott** [comment]
@panchagnula for comment

**Comment by panchagnula** [comment]
@kristaps5 I am looking into it - I was unable to repro this on our end but I will investigate further & update the issue

**Comment by panchagnula** [comment]
@kristaps5 & @roosi  the API never returns the password or password hash that will always be null, that's the reason the az webapp deployment user - only shows the username value only & null for the password.

One way to confirm that setting the username for CLI worked correctly is to navigate to https://<sitename>.scm.azurewebsites.net/basicauth & use the username & password you provided to make sure you can login successfully.  Can you please try this & confirm? Thank you.

**Comment by kristaps5** [comment]
the issue isnt around it returning nulls for the credentials but the problem is it simply doesnt work when trying to push using those just created credentials. Is there perhaps a caching issue?

**Comment by kristaps5** [comment]
just confirmed its some cache issue on your end. I ran my script and created a web server, mysql server and a deployment user. Then I delete the resources and try to create again with a new deployment user. The interface still remembers the old deployment user created before deleting the first time.

**Comment by kristaps5** [comment]
Running az webapp deployment user show
results in a different value for publishingUserName then what I see on the dashboard under "Git/Deployment username" which shows an old previously created username that had its whole resource group deleted

**Comment by kristaps5** [comment]
?

**Comment by panchagnula** [comment]
@kristaps5 when you say dashboard are you referring to the azure portal? If so seems like you are saying that the caching issue you are referring to is on the Portal - if so try to force refresh your browser or login using an inPrivate /incognito browser session & try. i can report the bug to the portal folks.

**Comment by kristaps5** [comment]
no, the issue is the newly created user isn't allowed to push to git while the deleted profile and previously created user is allowed to push. Yes I am referring to the azure portal

**Comment by panchagnula** [comment]
got it so if you override the user (to the new username) from portal you see that it works however, running from CLI doesn't have the same effect? is that what you are seeing?

**Comment by ahmelsayed** [comment]
I'm a bit confused by the description of the issue. 
You're saying when you do `az webapp deployment user show` you get back 

```json
{
    "id": null,
    "kind": null,
    "name": "web",
    "publishingPassword": null,
    "publishingPasswordHash": null,
    "publishingPasswordHashSalt": null,
    "publishingUserName": "testUser1234441212",
    "type": "Microsoft.Web/publishingUsers/web",
    "userName": null 
}
```

is that user `testUser1234441212` not the one you set when doing `az webapp deployment user set --user-name`?

Are you saying that user then gets 403 trying to push to git? I'll need timestamp and username used when you got the 403 to look into logs why that happened. 

Also when you say the front end doesn't show the user after you set it with `az webapp deloyment user set --user-name` are you talking about this view?

![image](https://user-images.githubusercontent.com/645740/37855367-32e521f2-2eac-11e8-99db-0a7913457eac.png)

Are you seeing it completely empty as in the image above?  if you are, are you sure you're logged in with the same AAD user in both the cli and the portal?

> 
> Then I delete the resources and try to create again with a new deployment user. The interface still remembers the old deployment user created before deleting the first time.

> Running az webapp deployment user show
> results in a different value for publishingUserName then what I see on the dashboard under "Git/Deployment username" which shows an old previously created username that had its whole resource group deleted

These statements are a bit confusing to me also. 

The deployment username is a concept that's tied to your AAD user that you use to login the portal or the az cli. The relationship is 1:1 between deployment users and AAD users. The only reason deployment users exist is because some popular publishing tools don't support fancy AAD login requirements things like FTP and older versions of git. Therefore, we give you the option of specifying a deployment userName and password that you can use with these tools. These creds are not per resource group, nor are they per subscription, nor are they per app. They are global to any your AAD user has access to. And they are unique per AAD user.

**Comment by panchagnula** [comment]
this would be the command that lists the available publishing-profiles az webapp deployment list-publishing-profiles --name
                                              --resource-group
                                              [--slot]
https://docs.microsoft.com/en-us/cli/azure/webapp/deployment?view=azure-cli-latest#az-webapp-deployment-list-publishing-profiles

**Comment by kristaps5** [comment]
Hi guys, I run this to create a web deployment user: az webapp deployment user set
is there a user set for setting an app specific deployment user?

**Comment by kristaps5** [comment]
@ahmelsayed To answer your question above - yes, I set the user with az webapp deployment user set and when i try to use those credentials right away within the same script - it gives me a 403. I then delete the app and thus what I assume deletes all users and try again and I get the same issue. But changing manually to push to the previously created users works. This is why I assumed it is some caching issue.

**Comment by kristaps5** [comment]
Just did another test:
created a new deployment, created a new user: testU123
this user fails to push to git.  

I go into the azure dashboard and see this user in the : testUser12344412121

![image](https://user-images.githubusercontent.com/36653415/38508608-a437e954-3bed-11e8-80f8-9a33fd29e35d.png)

**Comment by kristaps5** [comment]
please fix the issue or let me know which specific call to make to create a user for a specific app. There is no call that I could find and your list calls above dont help

**Comment by kristaps5** [comment]
?

**Comment by kristaps5** [comment]
I see you removed the question label - is it a bug? Anyone here to reply to the above?

**Comment by tjprescott** [comment]
We usually start issues with the Question label until we have a better handle on it.  In this case, I'd just consider it an open issue.  Not sure if it's a bug or not.  @panchagnula for further comment.

**Comment by kristaps5** [comment]
anyone?

**Comment by kristaps5** [comment]
?

**Comment by ahmedelnably** [comment]
Adding @suwatch can you please help with this please?

**Comment by suwatch** [comment]
@kristaps5 when you did `az webapp deployment user set` , what account you were login with (az login)?   Is this the same as one you log on to portal?   If the same and it still is not working, provide us the time in UTC and we can take a look.    BTW, I tried the same command and it worked fine - in fact, pretty much right away.

**Comment by kristaps5** [comment]
The account I login with is the same as on the portal. Is there a messenger we can quickly go back and forth on this on and get it resolved?

Thanks,
Kristaps

**Comment by kristaps5** [comment]
When i run the commands one after another in one script the newly created user does not work when pushing to git. When I go to the dashboard I see a previously created user there that it lists as a publishing user

**Comment by suwatch** [comment]
Sorry it has been a long thread.  The hard part is I wasn't able to repro.   

We really need a time of operation in UTC to investigate.  Please run the set user deployment again (apology as you have done this million times) and do provide us the time in UTC.

**Comment by kristaps5** [comment]
The script is running started at 2:15EST (6:15pm UTC)

**Comment by suwatch** [comment]
We looked at 2018-04-18 18:15 UTC (give or take 5 mins).   All update user publishing calls we saw were from Portal (none from azure cli).    Mind running just `az webapp deployment user set ..` alone (not in script) and give us the timeframe again?

**Comment by kristaps5** [comment]
ran it just now
Array
(
    [0] => {
    [1] =>   "id": null,
    [2] =>   "kind": null,
    [3] =>   "name": "web",
    [4] =>   "publishingPassword": null,
    [5] =>   "publishingPasswordHash": null,
    [6] =>   "publishingPasswordHashSalt": null,
    [7] =>   "publishingUserName": "testU1234",
    [8] =>   "type": "Microsoft.Web/publishingUsers/web",
    [9] =>   "userName": null
    [10] => }
)

**Comment by suwatch** [comment]
you are using python/2.7.13 CLI correct?

**Comment by suwatch** [comment]
You account that you are using for CLI is not the same as one you logon to portal.   The CLI is using service principal while Portal is interactive user.    Hence, you see the different user names.   We don't support publishing user for service principal to access SCM site.

You can, instead, get the bearer token for the service principal and access SCM site using that bearer token instead (Header, Authorization: Bearer <jwt>).

**Comment by tjprescott** [comment]
Thank you for your assistance @suwatch. I'm going to close this issue now that the underlying cause has been identified.
