### ISSUE TITLE
Unable to run multiple commands on Azure Stack

### ISSUE THREAD

**Issue by gsee2000** [Azure/azure-cli#5614]
Hi

Not sure if this is for here, but wondered if someone in the community knows. Currently trying to run a few commands against Azure Stack with no joy. We are running the following command set:

az cloud register -n AzureStack (stating relevant values)
az cloud set -n AzureStack
az login -u username -p password

az vm list
The resource type 'virtualMachines' could not be found in the namespace 'Microsoft.Compute' for api version '2017-12-01'. The supported api-versions are '2015-06-15,2016-03-30'.

Checking the resource 'virtualMachines' we see:

{
            "resourceType": "virtualMachines",
            "locations": [
                "azurestacklocatoin"
            ],
            "apiVersions": [
                "2016-03-30",
                "2015-06-15"
            ],
            "apiProfiles": [
                {
                    "profileVersion": "2017-03-09-profile",
                    "apiVersion": "2016-03-30"
                }
            ]
        },

Is there a way to run an earlier profile against this? Or an earlier version of Azure Cli in order to interact with Azure Stack successfully?

Currently using azure-cli (2.0.26), against Azure Stack running latest 1712 update.

Cheers

**Comment by tjprescott** [comment]
Does this help:
`az cloud update -p 2017-03-09-profile` 

Otherwise you are running against profile 'latest' which Stack does not support.

**Comment by derekbekoe** [comment]
Also, see https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-connect-cli#connect-to-azure-stack where it says exactly what @tjprescott said.

**Comment by gsee2000** [comment]
Hi Guys, thanks for coming back on this. I thought I had tried this previously without much luck. I can confirm this method is working.

Many thanks
