### ISSUE TITLE
No option to restore encrypted disks in azure using azure-cli

### ISSUE THREAD

**Issue by areyesjr** [Azure/azure-cli#5615]
No option to restore encrypted disks in azure using azure-cli

I can encrypt the disks but there is no option to restore disks using azure-cli. I created a ticket with Microsoft and they confirmed its not possible. I wanted to know if it was in a sprint or when would it be. 

This is the document for powershell. no document exists for azure-cli. 
https://docs.microsoft.com/en-us/azure/backup/backup-azure-vms-automation#restore-an-azure-vm

**Comment by dragonfly91** [comment]
@pvrk Kartik, can you please respond to this?

**Comment by areyesjr** [comment]
Thanks for looking into this. I know there will be more people asking for this.

**Comment by psinger** [comment]
I am currently wondering the same thing. I have in general quite some problems restoring encrypted vms.

**Comment by areyesjr** [comment]
Hello are there any updates?

**Comment by pvrk** [comment]
@areyesjr : We are working on this. Please give us time until July mid to give you a proper response

**Comment by andrzejjedrzejejwski** [comment]
@pvrk where we are with this? Do you have some updates?

**Comment by pvrk** [comment]
We have now moved to a way of providing deployment templates for each possible configuration. Use [CLI to restore disks](https://docs.microsoft.com/azure/backup/tutorial-restore-disk#restore-a-vm-disk) and then extract the deployment template name from storage account blob. The exact variable name is "Template Blob Uri". Then [deploy the template using CLI](https://docs.microsoft.com/azure/azure-resource-manager/resource-group-template-deploy-cli#deploy-external-template) with this template URI.

**Comment by psinger** [comment]
@pvrk Would be nice to provide a more detailed tutorial for this.

**Comment by tjprescott** [comment]
Thank you @pvrk

**Comment by pvrk** [comment]
@psinger : Yes, I will write a tutorial for this like powershell. This was to unblock any immediate requirements.
