### ISSUE TITLE
`storage cors add`: '--methods' unclear

### ISSUE THREAD

**Issue by ccanizares** [Azure/azure-cli#5621]
Trying to add cors via api, documentation here is not clear... which format should I use for methods param on add? invested some time and not able to add cors via az client... methods param only accept one verb

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2e3dfa7-e7ba-d8b9-9c8b-7a716016b7c0
* Version Independent ID: 249776f7-0d81-361b-822e-b87c2ca7fb23
* [Content](https://docs.microsoft.com/en-us/cli/azure/storage/cors?view=azure-cli-latest#az_storage_cors_list)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py)
* Service: storage

**Comment by tjprescott** [comment]
The `--methods` parameter accepts a space-separate list of verbs, not a single verb. So, for example:
`az storage cors add --methods GET PUT ...`

@troydai we should update the help text to clearly state "Space-separated" instead of just "List" which is ambiguous.

**Comment by troydai** [comment]
Yeah.

**Comment by gvilarino** [comment]
Precisely. Especially since until some versions ago, it would accept this notation: `{GET,OPTIONS,PUT}` and all of a sudden it doesn't (at least since 2.0.28, maybe earlier)
