### ISSUE TITLE
push/pop for az configure defaults

### ISSUE THREAD

**Issue by AlexanderYukhanov** [Azure/azure-cli#5623]
It would be nice to have 'az configure defaults push' and 'az configure pop' commands working similar to pushd/popd. This will allow scripts to setup defaults for during their execution and restore users settings on completion.

**Comment by yonzhan** [comment]
@jiasli  add to S162.

**Comment by jiasli** [comment]
Thank you for the suggestion. You may use `--scope` instead so that the configurations are saved for a specific folder under `.azure/config`, thus preserving the global configurations. For more info, please run `az configure -h`.
