### ISSUE TITLE
Browsing the Dashboard and Credentials

### ISSUE THREAD

**Issue by anschoewe** [Azure/azure-cli#5628]
Since Kubernetes 1.7, the Kubernetes Dashboard now requires some for of authentication (username/password or token).  When running 'az aks browse', how is the Dashboard auth appears in my browser being secured?  In general, how do you/I ensure that the Dashboard is not accessible to outside users.  Is it somehow protected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* [Content](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az_aks_browse)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/aks.yml)
* Service: unspecified

**Comment by suonto** [comment]
I believe this is not a client issue. AKS dashboard is connected via tunneled http. That makes dashboard a security vulnerability if given any privileges. The proper solution would be to make dashboard acessible via https and enable [login-view](https://github.com/kubernetes/dashboard/wiki/Access-control#login-view). I have opened an issue for this in AKS issues: https://github.com/Azure/AKS/issues/630

**Comment by jnoller** [comment]
This is not an Azure CLI issue. Users can enable/disable the kubernetes dashboard, but given well known security and RBAC limitations, we do not recommend customers make the dashboard publicly accessible or otherwise. The dashboard should only be used via the AKS browse command and for internal customer users.
