### ISSUE TITLE
`azdev test --test` cannot take path to test

### ISSUE THREAD

**Issue by williexu** [Azure/azure-cli#5629]
---
This is needed in case there are conflicts and specifying just the test name does not suffice.
It used to be the case that one would be able to do `--test <file>.<test class>.<test name>`

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by tjprescott** [comment]
Upon investigation, this seems to be a problem with nosetests.
