### ISSUE TITLE
[Tagging] az vm nic update doesn't support tagging

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#563]

**Comment by tjprescott** [comment]
This command only associates existing nic IDs with a VM, and thus should probably be called `set` rather than `update`. Tagging would need to (and can) occur using a call to `az network nic update`.

**Comment by tjprescott** [comment]
This is not an issue. PR #1421 renames `vm nic update` to `vm nic set` to reflect that it is not a traditional update mechanism and thus one would not expect to be able to tag NICs in this way.
