### ISSUE TITLE
What should I do with the file which exceeds 256000 characters?

### ISSUE THREAD

**Issue by kamoljan** [Azure/azure-cli#5639]
I am uploading my secret file which is exceeding 25600 characters:

```az keyvault secret set --vault-name mykeyvault --name mycreds --file mycreds.yml```

And getting the following error:

```Secret is beyond the maximum permitted length of 25600 characters.```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39cfb8ed-c246-2ffb-9dff-070b90c18b21
* Version Independent ID: c09c1597-1b6c-b0a2-b3fc-bdc16764d096
* [Content](https://docs.microsoft.com/en-us/cli/azure/keyvault/secret?view=azure-cli-latest#az_keyvault_secret_list_deleted)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py)
* Service: key-vault

**Comment by schaabs** [comment]
The simplest work around would be to split the file and store as multiple secrets.  If this isn't possible or undesirable, then I would suggest encrypting the file with a symmetric key, store the encrypted file outside of the vault, and store the symmetric key as a secret in the vault.

**Comment by slacknet** [comment]
if you split it you might get back a corrupted file

**Comment by comanl** [comment]
see https://www.synopsys.com/apps/support/est/How_to_split_files_over_2GB.html

**Comment by comanl** [comment]
usage of `split` and `cat` and `sha256` will prevent having a corrupted file
