### ISSUE TITLE
Impossible to delete defunctional VM

### ISSUE THREAD

**Issue by chubin** [Azure/azure-cli#5640]
I'm trying to remove my defunct Linux VM using az,
but it does not work, and the command just hangs or better to say it continues forever:
```
$ az vm delete -n NAME -g RESOURCE_GROUP --yes
```
Is there any method to forcedly remove a VM?

**Comment by tjprescott** [comment]
`vm delete` is a long running operation that can take some time. You can run the delete with `--debug` to see the networking traces for the polling events. If these are happening, then the delete is still ongoing.

If that does not help, please provide the information requested when a new issue is created for us to be able to assist you further.

**Comment by chubin** [comment]
Should I reopen the Issue or create a new one?

I've started the command more than 50 hours ago and it is still running;
I suppose something is going wrong. Other VMs are being deleted without any problems.
It is the only strange one

**Comment by tjprescott** [comment]
You can provide the following and reopen the issue:

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
<your data here>
```

**Comment by chubin** [comment]
Installation method:
```
curl -L https://aka.ms/InstallAzureCli | bash
```

az --version:
```
az --version
azure-cli (2.0.13)

acr (2.0.10)
acs (2.0.12)
appservice (0.1.12)
batch (3.1.1)
billing (0.1.3)
cdn (0.0.6)
cloud (2.0.7)
cognitiveservices (0.1.6)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.10)
consumption (0.1.3)
container (0.1.8)
core (2.0.13)
cosmosdb (0.1.11)
dla (0.0.10)
dls (0.0.12)
eventgrid (0.1.1)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.7)
iot (0.1.10)
keyvault (2.0.8)
lab (0.0.9)
monitor (0.0.8)
network (2.0.12)
nspkg (3.0.1)
profile (2.0.10)
rdbms (0.0.5)
redis (0.2.7)
resource (2.0.12)
role (2.0.10)
sf (1.0.6)
sql (2.0.9)
storage (2.0.12)
vm (2.0.12)

Python (Linux) 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4]

Python location '/home/ic/azure-cli/bin/python'
```

OS version:
```
$ cat /etc/issue.net 
Ubuntu 14.04.5 LTS
```

Shell Type:
```
bash
```

How does it look like:
```
$ az vm delete -n XXX -g YYY --yes 
(50 hours later pressed ^C)
Long running operation wait cancelled.  
```

Please reopen the issue.

**Comment by tjprescott** [comment]
Your CLI is over a dozen versions out of date.  The latest release is 2.0.27 (with 2.0.28 releasing this week).  Please update your CLI.  If the problem persists we'll gladly reopen the issue.
