### ISSUE TITLE
support changing TLS version in Web Apps

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-cli#5646]
Proposed command:

az webapp update -n <app name> -g <rg name> --tls <1.0 or 1.1 or 1.2>

**Comment by tjprescott** [comment]
There is already a `webapp update` command.  Simply add `--tls` to that command.

**Comment by panchagnula** [comment]
@tjprescott  yes, that is the idea to add --tls <string> to the existing update command

**Comment by panchagnula** [comment]
This needs to release end of  March to early April so setting for milestone 35 that will release April 10th

**Comment by panchagnula** [comment]
This is a config setting so will be az webapp config set --min-tls-version <vaue>
