### ISSUE TITLE
How to create a Subscription

### ISSUE THREAD

**Issue by rodneyjoyce** [Azure/azure-cli#5647]
Hi,

Is it possible to create a subscription? My end goal is to create and Active Directory and a new subscription but everything seems to work in the context of a subscription.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9abfaa54-0895-29f7-f3bb-ff604912b2ac
* Version Independent ID: d1ff3478-8a86-59e4-62ef-449900132a67
* [Content](https://docs.microsoft.com/en-us/cli/azure/account?view=azure-cli-latest)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_help.py)
* Service: azure

**Comment by tjprescott** [comment]
You cannot create a subscription using the CLI.

https://azure.microsoft.com/en-us/free/

**Comment by rodneyjoyce** [comment]
Is there any other way to create a subscription programmatically? 

We are using Terraform which is using the Azure RM under the hood and the requirements is for a CSP customer to be able to create a subscription for a customer - the Azure RM itself also cannot seem to create a subscription - any opinions appreciated...

**Comment by richeney** [comment]
I know that this is closed, but thought that anyone who stumbled across it should know that you can create subscriptions programmatically now: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/programmatically-create-subscription?tabs=azure-cli
