### ISSUE TITLE
Support aarch64 Linux packages

### ISSUE THREAD

**Issue by PatrickLang** [Azure/azure-cli#5657]
I'm trying to find deb packages to run under aarch64. I only see amd64 packages published

---

### Environment summary

Install Method : attempting with apt using WSL on an ARM64 machine

```
$ uname -rvi
4.4.0-17107-Microsoft #1000-Microsoft Tue Feb 20 13:50:00 PST 2018 aarch64
```

**Comment by derekbekoe** [comment]
@PatrickLang We don't have packages for ARM64.
The best way to go would be install Python on the machine and run `pip install azure-cli`.

**Comment by yonzhan** [comment]
issue triaged.

**Comment by fengzhou-msft** [comment]
We have no plans to add package support for ARM64. Please use `pip install azure-cli`.

**Comment by jamesthurley** [comment]
For future people trying this, for `pip install azure-cli` to succeed you'll also need to have done `sudo apt-get install` for `gcc`, `python3-dev` and `libffi-dev`.

**Comment by jiasli** [comment]
Tracked by https://github.com/Azure/azure-cli/issues/7368
