### ISSUE TITLE
Homogenize file (batch) Operation using Snapshots

### ISSUE THREAD

**Issue by dtissen** [Azure/azure-cli#5662]
It is more than confusing how to manage file / file shares. Especially when using snapshots!

Creating snapshots for shares and files: az storage share .... --> Available
Restore share snapshots: not available.
Delete share snapshot: not available.
Restore File from snapshot in the same share and storage: az storage file copy ... --> Available
Restore Files from snapshot in the same share and storage:  not available
Download file from Snapshot: Available
Download files from Snapshot: Not available.
Restore Files from Snapshot to another storage / share: Not available

I know that Share and files in a share are two topics. But the current functional overview for share and files is confusing:
1. The both have some common functions (Snapshots are done by the share functionalities)
2. There is a lack of Snapshot Management regarding Files and Shares as described above.
3. Snapshot Management of a share should also include delete and restore of the complete snapshot.
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by yugangw-msft** [comment]
@williexu, can you please comment?

**Comment by williexu** [comment]
@dtissen I apologize for your troubles. Please look at https://docs.microsoft.com/en-us/azure/storage/files/storage-how-to-use-files-cli#create-and-manage-share-snapshots for in depth information on using share snapshots.

For the scenarios you mentioned:
Creating snapshots for shares and files: `az storage share snapshot`
Restore share snapshots: not available (this is not supported by the service)
Delete share snapshot: `az storage share delete --snapshot`

Downloading multiple files from a share snapshot: I've opened a PR to add this: https://github.com/Azure/azure-cli/pull/8718

The copy file from one snapshot to another is more complicated as the service supports this through a source-file url. I've opened another issue to address that: https://github.com/Azure/azure-cli/issues/8719
