### ISSUE TITLE
Error Message: Waiting for DNS record for ingress to propagate for node [Kubernetes]

### ISSUE THREAD

**Issue by tonybyorick** [Azure/azure-cli#5664]
---
### Environment Summary

CLI Version: azure-cli (2.0.27)
OS Version: Ubuntu 16.04
Shell Type: bash
Container Service: ACS

### Bottom Line Questions

1. Is an NginX Ingress controller automatically created when a Kubernetes cluster is created in ACS  using the azure-CLI?
1. What is the correct method to determine the IP address of an Ingress controller?

### Background for the Question 
I ran the following command within Azure CLI to create a Kubernetes service:

```
az acs create --orchestrator-type=Kubernetes --resource-group=$GROUPNAME 
--name=$NODE --location=$LOCATION --dns-prefix=$NODE 
--agent-count=1 --agent-vm-size=Standard_DS4 --master-count=1 
--service-principal=$SERVICEPRINCIPAL --client-secret=$CLIENTSECRET 
--ssh-key-value=$SSHPUBLICKEYPATH
```
```Get Nodes``` shows the following message which indicates the cluster was successfully created:

```
~$ kubectl get nodes
NAME                    STATUS    ROLES     AGE       VERSION
k8s-agent-596de907-0    Ready     agent     1d        v1.7.7
k8s-master-596de907-0   Ready     master    1d        v1.7.7
```
So, now I'm attempting to launch an application within a pod in the cluster but am receiving the following standard output exception message from the application being launched which indicates a problem connecting to the Ingress service:

```
[coretestclust.coredltpoc.com]: waiting for non-init-container Symbiont services to come up:
........................................
[coretestclust.coredltpoc.com]: ingress service is running

[coretestclust.coredltpoc.com]: ledger service is running

[coretestclust.coredltpoc.com]: waiting for DNS records to propagate for node ...

[coretestclust.coredltpoc.com]: resolving ingress by IP
................................................................................................................
................................................................................................................
....symbiont: FatalError {msg = "failed while waiting for DNS record for ingress to propagate for node: coretestclust.coredltpoc.com with value: False after 240 retries"}
```

Also, the last few lines of the application log contain the following message also related to Ingress:
```
[2018-02-25 20:59:40][node-coretestclust][Info][PCNAME][17196][ThreadId 1] waiting for DNS record 
for ingress to propagate for node: coretestclust.coredltpoc.com...
[2018-02-25 20:59:40][node-coretestclust][Debug][PCNAME][17196][ThreadId 1] while: waiting for DNS record for ingress to 
propagate for node: coretestclust.coredltpoc.com, got value: False, which did not satisfy the required condition 
because 'Could not resolve expected IP 13.89.187.135 at hostname admin-coretestclust.coredltpoc.com', retrying in 1 sec...
```

It appears that the application being launched is unable to connect with the Ingress controller.  Not sure why.... Any thoughts appreciated.

**Comment by mboersma** [comment]
@tonybyorick I'm sorry no one followed up on your questions sooner. This isn't specific to the CLI. If this is still an issue, could you open an Azure support request?

**Comment by yugangw-msft** [comment]
closing as `az acs` is deprecating
