### ISSUE TITLE
Provide a way to call a method and not output anything, maybe something like: "-o none"

### ISSUE THREAD

**Issue by jongio** [Azure/azure-cli#5667]
It would be great to have -o "none" option, that doesn't print anything from the command.

I'm scripting az login and don't want it to print the subs after login.

**Comment by jonbgallant** [comment]
Here's a hack I came up with:

`az login --query "[?n]|[0]"`

**Comment by tjprescott** [comment]
You could also pipe your output to null.

**Comment by jonbgallant** [comment]
@tjprescott - do you know of a good safe cross-plat way to do that?

**Comment by andreacassioli** [comment]
I have just got in this issue creating storage accounts. There is a lot of output that pollute my scripts. Of source I can pipe the output or use the query, but it is so common to have a flag to silence a cli, and it is more readable and portable.
This should be a common option to all `az cli` commands. I think either

* there is a `--quite` flag
* or the `--verbose` flag accept a verbosity level.

**Comment by jiasli** [comment]
We have added option `--only-show-errors` in #12604 to disable warnings that are written to `stderr`. It will be included in [S167](https://github.com/Azure/azure-cli/milestone/84) release.
