### ISSUE TITLE
DevTestLab VM artifact status broken post Azure CLI 2.0.25

### ISSUE THREAD

**Issue by kcsomisetty** [Azure/azure-cli#5677]
This used to work with api in azure cli 2.0.21
az lab vm show --lab-name <lab name> --name <vmname> -g <LabRG> --expand "properties($expand=artifacts)"

But stopped working post 2.0.25

What is the new way of knowing what artifacts is installed on a DTL vm. 

---

### Environment summary
```
Azure CLI 2.0.21 
```

**Comment by tjprescott** [comment]
What error do you receive?

**Comment by kcsomisetty** [comment]
i dont see the 'artifact details' in the output of this command.
