### ISSUE TITLE
Add Upsert option on Most Resources

### ISSUE THREAD

**Issue by nirmalparekh1984** [Azure/azure-cli#5678]
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

Install Method: brew install azure-cli
CLI version: azure-cli (2.0.27)
OS Version: mac-os
Shell Type: bash

```
```
**New Feature Request**
Currently, most resources only have create, update, delete, show, list...
Adding an upsert (Update Or Insert) option will be beneficial from DevOps Automation using cli, it would reduce coding where in developer first has to check if resource exists then then implement either insert or update operation

**Comment by tjprescott** [comment]
We have discussed this within the team and decided not to implement this. Our create commands and idempotent and we have done dedicated work to standardize the "exists" check with our show commands. To implement this in a consistent way, we would have to expose and test this upsert command across dozens of services, including modules the CLI team does not own. We have another work item to opt into "create if not exists" behavior that we would favor.
