### ISSUE TITLE
Document for update if some fields are not provided then it overwrite with default

### ISSUE THREAD

**Issue by nirmalparekh1984** [Azure/azure-cli#5681]
the update operation overwrites existing values that are not passed with default.
for example if command executed is 
Say current rule has protocol tcp, the below update command only updates source-asgs, however, all other parameters are replace with default value. So the protocol now becomes any.

az network nsg rule update --name $name --nsg-name $nsg_name --resource-group $resource_group --source-asgs $source_asg --source-address-prefixes= 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afe4941c-7b46-b9fb-1c52-98e68f6354cc
* Version Independent ID: d1bc72fb-ccf9-9645-7b1d-98c91bc75a55
* [Content](https://docs.microsoft.com/en-us/cli/azure/network/nsg/rule?view=azure-cli-latest)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py)
* Service: virtual-network

**Comment by tjprescott** [comment]
Thanks for the report @nirmalparekh1984. This is definitely a bug.

**Comment by nirmalparekh1984** [comment]
It also changes the direction of the Rule, by default it makes the direction as inbound

**Comment by tjprescott** [comment]
No update command in the CLI should have any default value.

**Comment by IvanKirianov** [comment]
az network nsg rule create -g $resource_group --nsg-name $nsg_name -n $rule_name --priority $priority --access $policy --source-address-prefixes "192.168.1.1,192.168.1.2" --destination-address-prefixes $destination --protocol $protocol --destination-port-ranges $destination_port --description $downloadUri

Is it possible to add in --source-address-prefixes 2 or more IP's as I describe in my command above? 

For now, error occurred: "has invalid Address prefix. Value provided:192.168.1.1,192.168.1.2"
