### ISSUE TITLE
Storage blob download `--if-match` issues

### ISSUE THREAD

**Issue by tiahgo123** [Azure/azure-cli#5682]
i can not make "if match" in az storage blob download work.
pls give me one example?
I have this error:
The condition specified using HTTP conditional header(s) is not met.ErrorCode: ConditionNotMet

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 472d5f5f-3ce0-1220-3058-4b27068f512b
* Version Independent ID: 76e1699e-e6ba-c0dd-aad4-c5a7ab58260d
* [Content](https://docs.microsoft.com/pt-br/cli/azure/storage/blob?view=azure-cli-latest#az_storage_blob_url)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py)
* Service: storage

**Comment by williexu** [comment]
`az storage blob download -c wilxcontainer -n newblob --if-match "\"0x8D57E1432D49281\"" -f C:\Users\wilx\temp\newdir\dir2\newblob2`
You can get the ETag by doing a `az storage blob show`
