### ISSUE TITLE
Concern: The create-rbac command creates a service principal has contributor permission to entire subscription by default.

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#5683]
The permission is too broad. It raises a security concern. I understand this change originates from https://github.com/Azure/azure-cli/issues/1190, however, I don't think the default setting is reasonable. By default, a good security practice is to grant accounts smallest set of permissions to enable it to function. If the role assignment is not intuitive and convenient, we should instead fix role assignment commands rather than write blank checks to newly created service principal.

**Comment by troydai** [comment]
@yugangw-msft @johanste 
I think we should seek advice from AAD and other security crews.

**Comment by yugangw-msft** [comment]
We have talked to RABC team last year. We will live with it for 2 reasons
1. `create-for-rbac` is a convenient command for `rbac` where role assignment is a must have, hence a default is needed. We don't see there are any other defaults which always work. The help calls out the default value very clearly. `--skip-assignment` was provided for people to skip it
2. At the same time for people with security concerns, use `az ad sp create` which we have agreed that we will never create any default assignments
