### ISSUE TITLE
A bit long: az account set --subscription-name-or-id <value>

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-cli#569]
Can't you infer this is the only required argument and just drop `--subscription-name-or-id`?

It's like saying `rm --file-name file.txt`, it is very unintuitive CLI design which is supposed to be oriented on main nouns/resources and verbs on them. Plus it's breaking the experience we're used to for years where it could've avoided.

**Comment by yugangw-msft** [comment]
/CC: @johanste, this is about positional argument support. I share the same feeling here when used this command.

**Comment by ahmetalpbalkan** [comment]
I realized this is dupe of #333, feel free to close.

**Comment by yugangw-msft** [comment]
it is different, the #333 is just for naming. This one is to get rid of the argument name, as it is the only one. Let me know if you do mean the same thing

**Comment by jluk** [comment]
+1 on removing the required arg

**Comment by BurtBiel** [comment]
--subscription-name-or-id should also be shortened to --subscription and the help text can mention that name and ID are valid.

**Comment by tjprescott** [comment]
Fixed in #1197.
