### ISSUE TITLE
az aks browse not working  : version 2.0.25

### ISSUE THREAD

**Issue by KarthickSelvam** [Azure/azure-cli#5692]
AZ AKS browse not working.. 

Also kubectl functions are not working, like getting logs, exec etc.

---

### Environment summary

Install Method (brew) / CLI version (`2.0.25`) / Mac High Sierra / Shell Type (terminal/bash)  

```
```

**Comment by tjprescott** [comment]
Please update to the latest version of CLI. I believe these issues have already been fixed.

**Comment by mboersma** [comment]
We did fix an `az aks browse` issue in version 2.0.26, but it only showed up when accessing a 1.7.x or 1.8.x Kubernetes cluster with `kubectl` 1.5.x or earlier.

@KarthickSelvam it sounds like you may have a more general issue with your cluster. I would suggest creating a help ticket with Azure support, or posting more specific logs and details to [Azure/AKS](https://github.com/Azure/AKS).
