### ISSUE TITLE
Revoked signing certificate on MSI download 

### ISSUE THREAD

**Issue by jkewley** [Azure/azure-cli#5696]
I just downloaded the CLI from the [download link here](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest) and I'm seeing a message that the signing cert has been revoked.

![image](https://user-images.githubusercontent.com/1148930/36808864-5b1f450a-1c94-11e8-9ad0-d27a0c29c44f.png)

**Comment by derekbekoe** [comment]
What's the date on your machine/

**Comment by jkewley** [comment]
2/28/2018

**Comment by derekbekoe** [comment]
Okay thanks. I have no immediate resolution here.
What area the valid from and valid to dates on the cert.?

**Comment by jkewley** [comment]
All dates are valid. I have a coworker who was able to download and install. I've tried several times and get the same error message. This issue can be closed with the assumption that it's a problem with my machine.
