### ISSUE TITLE
[Resource] Link create: --link-id format wrong

### ISSUE THREAD

**Issue by ericc1103** [Azure/azure-cli#5699]
'providers' needs to be inserted in front of a provider:
/subscriptions/{SubID}/resourceGroups/{ResourceGroup}/providers/{ProviderNamespace}/{ResourceType}/{ResourceName}/providers/Microsoft.Resources/links/{LinkName}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0a44789-a74b-537e-929e-62ff5efcaaef
* Version Independent ID: 10f4128a-7e4a-e982-4888-617b4e720855
* [Content](https://docs.microsoft.com/en-us/cli/azure/resource/link?view=azure-cli-latest#az_resource_link_create)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py)
* Service: azure-resource-manager

**Comment by tjprescott** [comment]
Thanks for the report @ericc1103.

**Comment by tfitzmac** [comment]
@ericc1103 - sorry that this issue was overlooked, and thank you for providing the correct format. I am trying to get it fixed.

**Comment by tjprescott** [comment]
This has been fixed.
