### ISSUE TITLE
Docker image publishing

### ISSUE THREAD

**Issue by ahmetb** [Azure/azure-cli#570]
We can onboard you to `microsoft/azure-cli` image with a tag like `:python-preview`.  (it's a better name).

Also please install stuff like `jq` to the docker image, you're nearly always returning json responses, it's impossible to read. All these was solved in the `microsoft/azure-cli` docker image, feel free to refer to its Dockerfile.

**Comment by JasonRShaver** [comment]
In addition to JQ, we should ensure the following are available in our docker image:

- xplat CLI
- JP (jmespath)
- JPTerm (jmespath terminal)

**Comment by ahmetalpbalkan** [comment]
there are other things like `vim`, `emacs` and `git` I believe we installed on the other image.

**Comment by colemickens** [comment]
Is this going to start being published as `microsoft/azure-cli` instead of  `azuresdk/azure-cli-python` ? It's much more easily remembered.

**Comment by JasonRShaver** [comment]
I think @colemickens mentioned Microsoft/az in #629, which is pretty compelling.  Here are some names I like in order of preference:

1. Microsoft/Az-cli
2. Microsoft/Az
3. Microsoft/Azure-cli-2

**Comment by ahmetalpbalkan** [comment]
First of all, lowercase-all would be preferred. `az-cli` is good and our customers will probably understand it. However if this is branded as "Azure CLI" everywhere else and not "Az CLI"; then I would strongly recommend going with `microsoft/azure-cli` as well. You'll be breaking existing users, but it's good in the long term.

**Comment by colemickens** [comment]
I agree with @ahmetalpbalkan, though I realize that breaking change might be untenable.

You could do it in a step-wise fashion: add the new `azure-cli` to the existing `Microsoft/azure-cli` container... wrap the legacy `azure` command with a big flashy warning that it is going to be deprecated and removed in a future release and that people should transition to `az`.

(Though, if the new `azure-cli` is not at feature parity with the legacy `azure-xplat-cli`, then this action might be a bit too aggressive.)
