### ISSUE TITLE
Unable to run CLI in Docker with mounted volume

### ISSUE THREAD

**Issue by posix4e** [Azure/azure-cli#5701]
posix4e@posix4e-HP-Spectre-x360-Convertible-15-bl1XX:~$ docker run -v ${HOME}:/root -it azuresdk/azure-cli-python:dev
Unable to find image 'azuresdk/azure-cli-python:dev' locally
dev: Pulling from azuresdk/azure-cli-python
ab7e51e37a18: Pull complete 
4a57a4e05b89: Pull complete 
b591eaeaef04: Pull complete 
ddc7f276242f: Pull complete 
2551bd8e779e: Pull complete 
ac1e385fe6d4: Pull complete 
9f927801addf: Pull complete 
f1fc01bb8ca8: Pull complete 
c764985d2cfe: Pull complete 
5c9bbf924618: Pull complete 
69421b335f98: Pull complete 
df2bb00e4feb: Pull complete 
Digest: sha256:2eba8834d110f61f6cb2ee4463ed86038da95628cc5361e7682069bba2f19876
Status: Downloaded newer image for azuresdk/azure-cli-python:dev
bash: gpg-agent: command not found
2048 SHA256:g3pw/IH+teNBbcV2XMeXLPKsuxZpyRJMjXrOCYIjs7A cardno:000606522572 (RSA)
2048 SHA256:g3pw/IH+teNBbcV2XMeXLPKsuxZpyRJMjXrOCYIjs7A (none) (RSA)
2048 SHA256:xOaJLcu6X5OnOQG7wP0LIZQtUp5kPg8ErC3n+BJJ5vE (none) (RSA)
root@e5bd9a1cf02e:/# az
/usr/local/bin/python: No module named azure.cli
root@e5bd9a1cf02e:/# ps ax
PID   USER     TIME   COMMAND
    1 root       0:00 /bin/sh -c bash
    7 root       0:00 bash
   18 root       0:00 ps ax
root@e5bd9a1cf02e:/# az
az                az.bat            az.completion.sh  
root@e5bd9a1cf02e:/# az
/usr/local/bin/python: No module named azure.cli
root@e5bd9a1cf02e:/# exit

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
Docker

```
```

**Comment by derekbekoe** [comment]
What's in the volume you're mounting? Try without mounting the volume.

It works otherwise.
```
$ docker pull azuresdk/azure-cli-python:dev
dev: Pulling from azuresdk/azure-cli-python
ab7e51e37a18: Already exists 
4a57a4e05b89: Already exists 
b591eaeaef04: Already exists 
ddc7f276242f: Already exists 
2551bd8e779e: Already exists 
ac1e385fe6d4: Pull complete 
9f927801addf: Pull complete 
f1fc01bb8ca8: Pull complete 
c764985d2cfe: Pull complete 
5c9bbf924618: Pull complete 
69421b335f98: Pull complete 
df2bb00e4feb: Pull complete 
Digest: sha256:2eba8834d110f61f6cb2ee4463ed86038da95628cc5361e7682069bba2f19876
Status: Downloaded newer image for azuresdk/azure-cli-python:dev
dereks-mbp-2:~ debekoe$ docker run -it azuresdk/azure-cli-python:dev
bash-4.3# az

Welcome to Azure CLI!
...
```
