### ISSUE TITLE
[SQL] Error: Operation failed with status: 'Bad Request'

### ISSUE THREAD

**Issue by prashanthavutalakp** [Azure/azure-cli#5705]
Hello there!

I tried using the above commands form Azure CLI and got the below error when executing pause/resume. Below is the command and error respectively:
command: az sql dw pause --resource-group xxxxxxx --server yyyyyyy  --name zzzzzz
Response: Operation failed with status: 'Bad Request'. Details: This feature is not available for the selected database's edition (sqldbrcqadb01).

I tried changing the database edition to Premium P2, but get the same error. Can you please advise on what edition the pause/resume features are enabled?

-Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6c6ca27-08d8-9c51-d68e-dad749bf8402
* Version Independent ID: a4e3d208-2717-9761-3968-59bd94308576
* [Content](https://docs.microsoft.com/en-us/cli/azure/sql/dw?view=azure-cli-latest)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py)
* Service: sql-database

**Comment by jaredmoo** [comment]
Only data warehouses can be paused, not regular databases. A data warehouse is a database whose edition is "DataWarehouse". This is by design. Thanks!
