### ISSUE TITLE
Docs feature request: show output schema

### ISSUE THREAD

**Issue by tlycken** [Azure/azure-cli#5711]
It would be awesome if these docs also showed the schema of the output I can expect from the various commands, so I don't have to run then and analyze the output in order to e.g. formulate queries against the data they expose.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeedb9a7-2aed-6727-4cfb-1515809d676e
* Version Independent ID: 2c83180d-22ad-db42-e2eb-f27f11977963
* [Content](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_help.py)
* Service: unspecified

**Comment by tjprescott** [comment]
Closing in favor of #5761.  Please follow that issue.
