### ISSUE TITLE
Upload messages are written into stderr 'az storage blob upload-batch'

### ISSUE THREAD

**Issue by Meastro** [Azure/azure-cli#5714]
### Environment summary

**Install Method**: MSI

**CLI version**
azure-cli (2.0.27)

acr (2.0.21)
acs (2.0.26)
advisor (0.1.2)
appservice (0.1.26)
backup (1.0.6)
batch (3.1.10)
batchai (0.1.5)
billing (0.1.7)
cdn (0.0.13)
cloud (2.0.12)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.14)
consumption (0.2.1)
container (0.1.18)
core (2.0.27)
cosmosdb (0.1.19)
dla (0.0.18)
dls (0.0.19)
eventgrid (0.1.10)
extension (0.0.9)
feedback (2.1.0)
find (0.2.8)
interactive (0.3.16)
iot (0.1.17)
keyvault (2.0.18)
lab (0.0.17)
monitor (0.1.2)
network (2.0.23)
nspkg (3.0.1)
profile (2.0.19)
rdbms (0.0.12)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.23)
role (2.0.19)
servicefabric (0.0.10)
sql (2.0.21)
storage (2.0.25)
vm (2.0.26)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\E0460598\.azure\cliextensions'

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

**OS version** : Windows 10 Enterprise
**Shell Type** : cmd.exe
**Description**:
Our VSTS build definition contains an Azure CLI task (to upload templates to Azure). The whole task is marked as failed because **az storage blob upload-batch** command writes info messages into **stderr** stream. 
For example: "WARNING: uploading C:\xxxxxxx\AzureDeployment\Templates\demo.parameters.json"

The flag `--no-progress` disables the progress bar, but still info messages are written into stderr stream.
Could you write into stdout stream instead ? Or if `--no-progress` flag is used don't report at all.

The behavior can be simulated locally as well. Let's create a simple console app which starts a process and redirects the standard error stream of application.

**Comment by williexu** [comment]
We generally only write to stdout the output of the command being run (ussually some json payload).
To check the success/failure of a command, you should check the exit code, not the presence of information in stderr.

**Comment by dineshsharmads** [comment]
I see this behavior when running az storage blob upload from PowerShell ISE. For some reason it writes progress messages to stderr. However, it works fine from PowerShell console.
