### ISSUE TITLE
Advisory Azure CLI encryptionSettings

### ISSUE THREAD

**Issue by sundaxi** [Azure/azure-cli#5717]
---

### Environment summary

Install Method: apt 

```
```
In powershell we have command below to copy the encryptionSettings from one VM to another. 

$SourceVMName = "redhatmanaged" 
$SourceVMRG = "encryption"
 
$DestVMName = "rhelteste"
$DestVMRG = "encryption"
Stop-AzureRmVM -ResourceGroupName $SourceVMRG -Name $SourceVMName –Force
$SourceVM = Get-AzureRmVM -ResourceGroupName $SourceVMRG -VMName $SourceVMName
$DestVM = Get-AzureRmVM -ResourceGroupName $DestVMRG -VMName $DestVMName
$DestVM.StorageProfile.OsDisk.EncryptionSettings = $SourceVM.StorageProfile.OsDisk.EncryptionSettings
	 
Update-AzureRmVM -ResourceGroupName $DestVMRG -VM $DestVM

Do we have relevant command in Azure CLI? 

I tried command below, but it doesn't work 

az vm update -n updateencryption -g encryption --add \
storageProfile.osDisk.encryptionSettings.keyEncryptionKey.keyUrl="https://keyvault20180227.vault.azure.net/keys/Key20180227/xxxxxxxxxxxxxxxxxxxxxx" \
storageProfile.osDisk.encryptionSettings.keyEncryptionKey.sourceVault.id="/subscriptions/xxxxxxxxxxx/resourceGroups/encryption/providers/Microsoft.KeyVault/vaults/keyvault20180227" \
storageProfile.osDisk.encryptionSettings.diskEncryptionKey.secretUrl="https://keyvault20180227.vault.azure.net/secrets/cxxxxxxx/4xxxxxxxxxxxxxxxxxx" \
storageProfile.osDisk.encryptionSettings.diskEncryptionKey.sourceVault.id="/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/encryption/providers/Microsoft.KeyVault/vaults/keyvault20180227" \
storageProfile.osDisk.encryptionSettings.enabled=true \

**Comment by sundaxi** [comment]
I found below command could work to update the encryption settings. But any better way to do the change?

az vm update -n testencryption -g encryption --set storageProfile.osDisk.encryptionSettings.keyEncryptionKey="{'keyUrl': 'https://keyvault20180227.vault.azure.net/keys/Key20180227/xxxxxxxxxxxxxxxx','sourceVault': {'id': '/subscriptions/xxxxxxxxxxxxxxx7/resourceGroups/encryption/providers/Microsoft.KeyVault/vaults/keyvault20180227'}}"

az vm update -n testencryption -g encryption --set storageProfile.osDisk.encryptionSettings.diskEncryptionKey='{"secretUrl":"https://keyvault20180227.vault.azure.net/secrets/cxxxxxx7-xxxb","sourceVault":{"id": "/subscriptions/0fxxxxxxx-f96xxxxxx7/resourceGroups/encryption/providers/Microsoft.KeyVault/vaults/keyvault20180227"}}'

az vm update -n testencryption -g encryption --set storageProfile.osDisk.encryptionSettings.Enabled=true

**Comment by tjprescott** [comment]
@sundaxi, you could chain those three `--set` into one command. 
`az vm update -n test -g blah --set a.b.c='1' --set a.b.d='2' --set a.b.e=true`

However, @yugangw-msft it seems like we could expose convenience args on vm update to make this less painful, or, possibly event better, expose something like `vm encryption update`. Thoughts?

**Comment by yugangw-msft** [comment]
Please check out things under `az vm secret`. If not enough, we start from there.

**Comment by sundaxi** [comment]
Thank you guys. 
I figure it out . The format looks like below

az vm update -n testencryption -g encryption --set storageProfile.osDisk.encryptionSettings.diskEncryptionKey="{'secretUrl': 'https://keyvault20180227.vault.azure.net/secrets/aa97b9f2-0f07-4c5d-8e49-e1995d33b2a9/8d454ccaf67843888e69ef4b61eae26f', 'sourceVault': {'id': '/subscriptions/xxxx-37cf-4c89-xxxx-xxxxx/resourceGroups/encryption/providers/Microsoft.KeyVault/vaults/keyvault20180227'}}" storageProfile.osDisk.encryptionSettings.keyEncryptionKey="{'keyUrl': 'https://keyvault20180227.vault.azure.net/keys/Key20180227/ca695b53ab964684b94648948f4ebc12', 'sourceVault': {'id': '/subscriptions/0xxxxxxxxxxx/resourceGroups/encryption/providers/Microsoft.KeyVault/vaults/keyvault20180227'}}" storageProfile.osDisk.encryptionSettings.Enabled=true
