### ISSUE TITLE
Vertical bar "|" in string litteral causes split in 2 commands

### ISSUE THREAD

**Issue by dimati93** [Azure/azure-cli#5719]
Execute query:
```
az webapp create --resource-group myResourceGroup --plan myAppServicePlan --name myAppName --runtime "NODE|6.9"
```

Error: 
```
'6.9' is not recognized as an internal or external command,
operable program or batch file.
```

Attempt with the same outcome:
```
$1 = "NODE|6.9"
az webapp create --resource-group myResourceGroup --plan myAppServicePlan --name myAppName --runtime $1
```

Caused during try to create WebApp with Node.JS runtime https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-nodejs

---

### Environment summary

Integrated Azure CLI (online at portal.azure.com) / CLI Version : 2.0.28 / Power Shell

**Comment by yugangw-msft** [comment]
This is a known issue, that unfortunately that appservice team has chosen to use the `|` as part of the container image name, which is a reserved cmd/shell character for piping.
Please wrap it with `"` or `'` if on bash

**Comment by ahmedelnably** [comment]
@dimati93 use the following format

az --% webapp create ....

adding the --% will instruct PowerShell to stop interpreting the | as a split operator
