### ISSUE TITLE
[storage] redundant line in stderr

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-cli#572]
```
$ az storage account create -g docker-machine -t Standard_LRS -n foo23489072389 -l westus 2>stderr 1>stdout
```

```
$ cat stderr
WARNING: Starting storage account create
WARNING:
``

1) why is it warning
2) there is an extra empty line at the end.

**Comment by yugangw-msft** [comment]
/CC: @derekbekoe
We should log at the level of regular info.  
The empty line might belong to the old ending message we later removed

**Comment by derekbekoe** [comment]
As @yugangw-msft mentioned, the empty line is an artifact from when we showed a message at the end of a Long Running Operation.

See https://github.com/Azure/azure-cli/pull/591. This PR removes the warning messages.

**Comment by derekbekoe** [comment]
PR merged. Closing issue.
