### ISSUE TITLE
what does 'az storage blob delete-batch' do?

### ISSUE THREAD

**Issue by ormico** [Azure/azure-cli#5722]
I'm trying to delete a large number of blobs from a storage container. I'm currently using delete but I saw delete-batch and was interested if it would help. However, I found the documentation to be a little sparse as to what it actually does.

The doc page
https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az_storage_blob_delete_batch
says 
> Delete blobs from a blob container recursively.

as its only description of it's functionality.

Can someone explain what this is supposed to do or how it works? The above description wasn't clear to me.

Thanks.

**Comment by williexu** [comment]
`storage blob delete-batch` was made for situations like yours, where a large number of blobs need to be deleted.
Essentially, bare-bones, you can specify a container using the `--source`/`-s` and all blobs will be deleted from said container. 
You can narrow down the scope by using the `--pattern`  parameter; e.g. using `--pattern directory*` will delete all blobs who's name starts with "directory"

**Comment by ormico** [comment]
Thanks. I ended up doing it through powershell but it took a long time to run.

What kind of patterns does --pattern support. The doc says 

> --pattern
> The pattern used for globbing files or blobs in the source. The supported patterns are '*', '?', '[seq]', and '[!seq]'.
> 

Would "myapp_log_*.trn" work?

I don't recognize [seq]. What type of pattern is that?

**Comment by williexu** [comment]
`myapp_log_*.trn` would match `myapp_log_<any character(s)>.trn`.
If that your goal, then yes.
[seq] allows you to specify a number of characters to match for.
We are using [fnmatch](`myapp_log_*.trn`) under the hood.

**Comment by arbaiti** [comment]
Hello,
I need to do cleanup of dump files on a blob container, and i don't know how to use this command.
I should delete dump older than 14 days.
Regards,

**Comment by williexu** [comment]
@arbaiti use the `--if-unmodified-since` parameter.
https://github.com/Azure/azure-cli/issues/5286 should be fixed with our next release.

In the meantime, you can query for the `properties.lastModified` datetime value and compare it with the datetime you want.

This should also answer your question: https://github.com/Azure/azure-cli/issues/5575#issuecomment-371762644
Next time, please limit your comments to one issue (or file a new issue) if they are all related.

**Comment by arbaiti** [comment]
Do you have any example with --if-unmodified-since parameter ?

**Comment by williexu** [comment]
Bash:
```
az storage blob delete-batch --source backups --if-unmodified-since `date -ud "14 day ago" '+%Y-%m-%dT%H:%MZ'`
```

**Comment by arbaiti** [comment]
Thanks for your reply i'll test it
