### ISSUE TITLE
Explain output data

### ISSUE THREAD

**Issue by chris-song** [Azure/azure-cli#5725]
Would be nice to have an example output and have the definition for each of the output fields. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bea54d36-cb69-577c-e114-2c4bd0e33728
* Version Independent ID: 812e7aa5-2e8a-f9ef-d922-df188bd6275a
* [Content](https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/user?view=azure-cli-latest#az_webapp_deployment_user_show)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/webapp/deployment/user.yml)
* Service: app-service-web

**Comment by tjprescott** [comment]
Duplication of #5711.
