### ISSUE TITLE
az vm extension image show name/version mismatch

### ISSUE THREAD

**Issue by johanburati** [Azure/azure-cli#5727]
The `az vm extension image show` command returns the version in place of the name (` "name": "1.5.2.2"`), tried this with `azure-cli (2.0.28)`:

```
$  az vm extension image show --location westcentralus --publisher Microsoft.OSTCExtensions --name CustomScriptForLinux --version 1.5.2.2 --output json
{
  "additionalProperties": {},
  "computeRole": "IaaS",
  "handlerSchema": null,
  "id": "/Subscriptions/03dd9652-d9f8-4816-ab45-2dbe05bd3479/Providers/Microsoft.Compute/Locations/westcentralus/Publishers/Microsoft.OSTCExtensions/ArtifactTypes/VMExtension/Types/CustomScriptForLinux/Versions/1.5.2.2",
  "location": "westcentralus",
  "name": "1.5.2.2",
  "operatingSystem": "Linux",
  "supportsMultipleExtensions": false,
  "tags": null,
  "type": null,
  "vmScaleSetEnabled": false
}
```

**Comment by yugangw-msft** [comment]
This comes from service side. Let me contact with CRP folks

**Comment by yugangw-msft** [comment]
The underneath REST call is `GET /subscriptions/.../Providers/Microsoft.Compute/Locations/westcentralus/Publishers/Microsoft.OSTCExtensions/ArtifactTypes/VMExtension/Types/CustomScriptForLinux/Versions/1.5.2.2?api-version=2017-12-01`, so it is the version entity gets retrieved. Still the `name` fields looks odd
//cc: @danielsollondon

**Comment by yugangw-msft** [comment]
> Is the ask to improve the API behavior in that it shouldn't return a field name that confuses users?

That is right, but we can live with this

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
