### ISSUE TITLE
"az interactive" displays IoT package warning on first launch

### ISSUE THREAD

**Issue by sptramer** [Azure/azure-cli#5730]
The first time the `az interactive` command is run, the IoT warning directing users to the extension is displayed, after the user prompt:

```bash
root@edcb32c4dee2:/# az interactive

Do you agree to sending telemetry (yes/no)? Default answer is yes: yes
az>>
                         Comprehensive IoT data-plane functionality is available
                         in the Azure IoT CLI Extension. For more info and install guide
                         go to https://github.com/Azure/azure-iot-cli-extension
```

If the IoT module has been loaded previously, this warning does not seem to be displayed.

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
azure-cli (2.0.28)
iot (0.1.17)

Ubuntu xenial, installed via apt
```

**Comment by troydai** [comment]
@williexu

**Comment by derekbekoe** [comment]
I did a 'quick fix' for this at some point but didn't complete it and create a PR.
https://github.com/derekbekoe/azure-cli/commit/313ea22b7164e8277723c3d051b7587cb7076da5
cc: @digimaun who owns the IoT module.

**Comment by digimaun** [comment]
@derekbekoe Did you want to complete what you had going or should I take over from where you left off?

**Comment by derekbekoe** [comment]
@digimaun Please take over where I left off.
I think that approach should work if I understand what you were trying to do correctly.

**Comment by derekbekoe** [comment]
PR merged. Change will be in the next release.
