### ISSUE TITLE
Add Ubuntu 18LTS bionic to the repo

### ISSUE THREAD

**Issue by mitcht** [Azure/azure-cli#5731]
There isn't much I can say about this issue. Ubuntu 18 LTS "bionic" is not currently located on https://packages.microsoft.com/repos/azure-cli/dists/

FWIW, the instructions to install the package located at https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest use instructions to grab the repo as so:

AZ_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | \
     sudo tee /etc/apt/sources.list.d/azure-cli.list

This results in a broken link in the package manager.

Artful will install if you do it manually.

**Comment by derekbekoe** [comment]
Since Bionic hasn't been finalized yet, we do not publish for bionic.
The install page does call it out "Ubuntu trusty, xenial, and artful".

Since Bionic will be released at the end of April, in the month of May, we can look at adding this.
https://wiki.ubuntu.com/BionicBeaver/ReleaseSchedule

**Comment by mitcht** [comment]
Your repo is not going to be included in the bionic release as part of Canon, and I doubt part of universe. There release schedule, albeit important, Should not weigh on the release timing for this repo. Are you hinting that the Microsoft azure CLI is going to be part of Canon or universe?

**Comment by derekbekoe** [comment]
We provide packages for the Current/Stable releases so once Bionic reaches that status, we'll look into publishing for Bionic also.

> Are you hinting that the Microsoft azure CLI is going to be part of Canon or universe?
We'll publish to https://packages.microsoft.com.

**Comment by maxburke** [comment]
Hello!

With Bionic's official release coming up shortly, I am beginning to evaluate the transition to Ubuntu 18.04 for our infrastructure. Would it be possible to have azure-cli packages posted for Bionic, even if just a pre-release?

Thanks!

**Comment by derekbekoe** [comment]
We are looking into publishing a bionic package to https://packages.microsoft.com/repos/azure-cli/dists/

Meanwhile, the package is available with:
```
wget https://azurecliprod.blob.core.windows.net/release-2-0-31/azure-cli_2.0.31-1~bionic_all.deb
dpkg -i azure-cli_2.0.31-1~bionic_all.deb
```

**Comment by maxburke** [comment]
Fantastic! Thank you so much, Derek!

**Comment by derekbekoe** [comment]
We've published to packages.microsoft.com so follow the standard official install instructions.
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest

https://packages.microsoft.com/repos/azure-cli/dists/bionic/

**Comment by derekbekoe** [comment]
Future releases from 2.0.31 onwards will have bionic packages published.
