### ISSUE TITLE
output: too many empty additionalProperties

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#5733]
Not a huge deal. Guess a side product by integrating the latest autorest runtime
Suggest not emit out empty ones. A single `vm show` gives me 8 of them, that is too many :)

//CC: @lmazuel @derekbekoe

**Comment by yugangw-msft** [comment]
This one is becoming a non-trivial distraction when checkout the response from complex objects like VMSS, VM, LB, etc. It is everywhere.
Unless there is an objection, I will go ahead to make the change to no longer emit out empty `additionalProperties`. Though I don't think would ever be a scenario, but for generic update, users can always assume there is an `additionalProperties` they can update.  But I don't think we should let edge scenarios get into the way of mainline usages.

//CC: @derekbekoe @lmazuel @tjprescott @troydai

**Comment by tjprescott** [comment]
For generic_update, currently it warns if you try and set something that doesn't exist. Perhaps those things should be automatically put in "additionalProperties"?

**Comment by lmazuel** [comment]
That's what additionalProperties is meant for. On read, everything not declared in the Swagger is put inside. On write (PUT, POST), either the Swagger enables it, or you can set an option to do it per Model:
```python
VirtualMachine.enable_additional_properties_sending = True
```

**Comment by yugangw-msft** [comment]
finally done #6277
