### ISSUE TITLE
[Webapp] Webapp config set: Provide a way to pass JSON

### ISSUE THREAD

**Issue by gstrantor** [Azure/azure-cli#5734]
The List option can easily provide the existing settings, please provide a way to pass that JSON output to the set method to easily configure the site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30f2ae52-2c7f-7e7e-8a62-f1b614f281d3
* Version Independent ID: 9f23ff17-14e0-7800-0094-fb50a5fa91d6
* [Content](https://docs.microsoft.com/en-us/cli/azure/webapp/config/appsettings?view=azure-cli-latest#az_webapp_config_appsettings_set)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/webapp/config/appsettings.yml)
* Service: app-service-web

**Comment by slootzky** [comment]
what's the point if list and set don't work in the same format? 
it used to be like that but you broke the behaviour.

**Comment by tobiasbunyan** [comment]
Agree.  Not very joined up thinking.

**Comment by davidlbyrne** [comment]
This is a serious problem because many urls have "=" and many base64 strings are padded with == and if you try to set either from the cli you will have problems. I tries to escape the extra = and its still not working correctly. Please help.

**Comment by davidlbyrne** [comment]
I was able to resolve this after reading some of the previous comments. In python : 
 if str(setting['value']).count('=') > 1:  setting['value'] = "'"+setting['value']+"'"

**Comment by VictorioBerra** [comment]
I had to finally wrap my whole call in a Powershell Invoke-Command as a string for it to stop chopping up my app settings or gluing them together as one big single setting. The amount of time I spent trying every single combination of escaped quotes, single quotes, `{({})}`, kind of stuff was unfortunate.
