### ISSUE TITLE
[webapp] Webjobs management

### ISSUE THREAD

**Issue by lonesomegeek** [Azure/azure-cli#5735]
I would like to know if there is a way to start/stop webjobs associated to a specific webapp/webapp-slot

Thanks,
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by panchagnula** [comment]
@lonesomegeek  currently no, not in CLI, we have support using Powershell - we do have intentions of looking into this soon though
