### ISSUE TITLE
Tests which relied on persistent resources can no longer be recorded

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#5740]
These tests relied on persistent resources and cannot be re-recorded now. They have been converted to LiveScenarioTest to permit updating the Network API version.

- [ ] test_group_deployment_thru_uri 
- [x] test_custom_image 
- [x] test_custom_image_with_plan

**Comment by troydai** [comment]
Why are they not re-recordable?

**Comment by tjprescott** [comment]
Because they relied on resources that were locked in the test subscription but have been deleted.

**Comment by troydai** [comment]
@yugangw-msft let's deal with this offline.

**Comment by yugangw-msft** [comment]
@tjprescott, I have fixed the 2 compute tests. For `test_group_deployment_thru_uri`, I think it should be fine, as the uri points back to the [public git source](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/tests/latest/test_resource.py#L451), which can be accessed anywhere.
If I didn't miss anything, I will flip the test back to regular scenario tests
