### ISSUE TITLE
[Resource, VM] Test live failures cannot be re-recorded

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#5741]
The following tests fail when run live and cannot be re-recorded. They are being temporarily converted to LiveScenarioTest to permit updating the Network API version.
- [x] test_resource_policy (PR #5944)
- [x] test_vm_create_custom_ip
- [x] test_vmss_msi (PR #5805)

**Comment by yugangw-msft** [comment]
test_vmss_msi will be fixed #5805 where I updated azure-cli-testsdk to support playback with guid

**Comment by yugangw-msft** [comment]
`test_vm_create_custom_ip` has worked for 2+ months. We can close it now.
