### ISSUE TITLE
Unmanaged Disk: Storage Account?

### ISSUE THREAD

**Issue by javgarces** [Azure/azure-cli#5743]
There's no clarity about which Storage Account will be chosen to store a new Unmanaged disk (or if a new Storage Account will be created).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2081b80b-2200-ea1a-2131-65602af2ae55
* Version Independent ID: 90a394bc-0235-b9af-fa5d-4d7e235f50df
* [Content](https://docs.microsoft.com/en-us/cli/azure/vm/unmanaged-disk?view=azure-cli-latest)
* [Content Source](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: virtual-machines

**Comment by yugangw-msft** [comment]
the storage account hosting the od disk will be chosen by default
