### ISSUE TITLE
VM CentOS OpenLogic:CentOS:7.4:7.4.20180118 proposed fixes

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#5748]
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
MSI
azure-cli (2.0.28)
Microsoft Windows [Version 10.0.17110.1000]
Bash on Windows

```
```
Pls. consider the following fixes for VM CentOS OpenLogic:CentOS:7.4:7.4.20180118 I do to publish my customized VM:

sudo sed -i 's|rngd -f|rngd -f -r /dev/urandom|' /usr/lib/systemd/system/rngd.service
sudo systemctl daemon-reload
sudo systemctl restart rngd.service
sudo systemctl -l status rngd.service

sudo chmod -x /usr/lib/systemd/system/azure-repo-svc.service
sudo chmod -x /usr/lib/systemd/system/azure-repo-svc.path

sudo mv /usr/lib/firewalld/icmptypes/beyond-scope.xml /usr/lib/firewalld/icmptypes/beyond-scope.xml.ORIG
sudo mv /usr/lib/firewalld/icmptypes/failed-policy.xml /usr/lib/firewalld/icmptypes/failed-policy.xml.ORIG
sudo mv /usr/lib/firewalld/icmptypes/reject-route.xml /usr/lib/firewalld/icmptypes/reject-route.xml.ORIG

These fixes remove error messages in OS log files

**Comment by derekbekoe** [comment]
Hi @alexeyshishkin01,
What was the issue this workaround was for?
What are you thinking the CLI should be doing to resolve this?
Thanks.
