### ISSUE TITLE
--query option gives null output

### ISSUE THREAD

**Issue by jimyjohny** [Azure/azure-cli#5749]
OS - Centos 6.9
az version - 2.0.9

 az vm list --query "[?networkProfile.networkInterfaces[?id=='/subscriptions/7XXXXXXXXXXXXX0/resourceGroups/XXX3/providers/Microsoft.Network/networkInterfaces/XXXX-1883']]|[0]"

None of the commands with --query option is working in one of the azure account.  Same command works in all other accounts. What could be blocking this command from this user account ?

**Comment by tjprescott** [comment]
What you supply to query depends on the structure of the VM show output, so you would want to compare the output between the two accounts.

Also, you might try updating your CLI.  The latest version is 2.0.28.

**Comment by derekbekoe** [comment]
As @tjprescott mentioned, the query is likely incorrect.

**Comment by jimyjohny** [comment]
Somehow the resource groups were created in uppercase and lowercase. So the resource id which got from the vm show output wasn't working when it was passed to the query.
