### ISSUE TITLE
vm image list: space in json keys?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-cli#575]
I'm surprised that command ran so fast (does it make an API request at all?) but the space in `urn alias` json key looks quite a bit unconventional:

```json
[
  {
    "offer": "Debian",
    "publisher": "credativ",
    "sku": "8",
    "urn": "credativ:Debian:8:latest",
    "urn alias": "Debian",
    "version": "latest"
  },
  {
    "offer": "RHEL",
    "publisher": "RedHat",
    "sku": "7.2",
    "urn": "RedHat:RHEL:7.2:latest",
    "urn alias": "RHEL",
    "version": "latest"
  },
 ...
]
```

**Comment by yugangw-msft** [comment]
by default, it hits the static json file somewhere in the git repo, which has limited image information, but good for 80% scenarios. To query all images (3000+),  use the flag of `--all`. I suggest you specify at least a filter say "--publisher" (partial name also work), to get back the result within reasonable time, say less than 15 seconds

**Comment by yugangw-msft** [comment]
I will fix the spec issue.

**Comment by ahmetalpbalkan** [comment]
@yugangw-msft don't you think the following is going to cause some confusion? 

```
# az vm image list --offer ubuntuserver
[
  {
    "offer": "UbuntuServer",
    "publisher": "Canonical",
    "sku": "14.04.4-LTS",
    "urn": "Canonical:UbuntuServer:14.04.4-LTS:latest",
    "urn alias": "UbuntuLTS",
    "version": "latest"
  }
]
```

I think if the VM list has arguments like `--offer`, it should hit the network the network.

**Comment by yugangw-msft** [comment]
The concern is if change it, it might cause other confusions that why `image list --filter` outputs things unavailable from the `image list` (w/o the filter).
I don't have strong opinion on it, but we can keep this open and see whether other people develop the same confusions.

**Comment by ahmetalpbalkan** [comment]
hmm okay. I'll let you figure out. Perhaps when this cmd used, print to stderr saying `You are viewing an offline list of images, use --all to retrieve an up-to-date list`?

**Comment by yugangw-msft** [comment]
@ahmetalpbalkan , i was thinking about  the same statement when i typed the previous comment. :-)

**Comment by ahmetalpbalkan** [comment]
@yugangw-msft want me to open a separate issue for this offline image list issue. It hurt me again and I lost like 5 minutes because of not recalling this fact...

**Comment by yugangw-msft** [comment]
It is there. Could you double check? Or you like it display at the end?
```
You are viewing an offline list of images, use --all to retrieve an up-to-date list
[
  {
    "offer": "CentOS",
    "publisher": "OpenLogic",
    "sku": "7.2",
    "urn": "OpenLogic:CentOS:7.2:latest",
    "urnAlias": "CentOS",
    "version": "latest"
  },
```

**Comment by ahmetalpbalkan** [comment]
hmm let me pull the latest docker image!

**Comment by ahmetalpbalkan** [comment]
hmm am I running an old version?

```
➜  ~ azure -v
0.10.2

➜  ~ az vm image list -l westus --publisher docker --output json
```

**Comment by yugangw-msft** [comment]
`azure -v` is the node version. Did you pull the python version?

**Comment by ahmetalpbalkan** [comment]
@yugangw-msft argh, my mistake. I'm on `azure-cli (0.0.1.dev0)`. The image seems to have built an hour ago. But it isn't printing that warning message for

    az vm image list -l westus --publisher openlogic

anyways feel free to ignore. I also noticed even though I say `--output json` we return empty output for an array response. Is this by design?

**Comment by yugangw-msft** [comment]
The source change was definitely committed. I didn't try the docker image, but I can check that out. 
for `--output json`, we will return empty output for if the response contains an empty array.

/CC: @derekbekoe

**Comment by johanste** [comment]
I would argue that returning nothing for list commands when the user asked for json probably isn’t the best idea. I’d prefer to return an empty array for commands since that allows me to compose the CLI output with other commands (jsawk, jp etc.) without having to worry about the “return no items” case being different from return n>0 items.

Just my SEK0.02

**Comment by ahmetalpbalkan** [comment]
the CLI must be getting an empty array from the server, not an empty string :) I'd also suggest returning empty array instead of empty string. This would be also consistent with the old CLI behavior:

```
~ azure vm image list -l westus --publisher mesosphere --json
[]
```

**Comment by yugangw-msft** [comment]
Returning empty array is the right behavior, we didn't do it before was mainly for the cost reason as we might have lots of tests to update. But regardless we can log an issue and prioritize it.

**Comment by yugangw-msft** [comment]
Tracking bug was created. 
Closing this one as the original issue was fixed
