### ISSUE TITLE
Add the ability to remove credentials from AD Service Principal

### ISSUE THREAD

**Issue by rohrerb** [Azure/azure-cli#5750]
#5642 Hello,

Could you please add the ability to remove credentials or expire credentials from AD Service principal.  It seems there is only support to add new credentials but not remove/expire old ones.

This logic does exist in powershell and not yet in Azure CLI.

-Thank you

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by yugangw-msft** [comment]
4 commands:
1.  `az ad app credentials show/delete`
2.  `az ad sp credentials show/delete`

//CC: @mayurid

**Comment by rohrerb** [comment]
Do these commands exist today or that is what is coming?

**Comment by yugangw-msft** [comment]
To come in the very near future

**Comment by mattpetrick** [comment]
this does not currently work when there is more then 1 password credential for the app. for example:

`  "passwordCredentials": [
    {
      "customKeyIdentifier": "bXAtdGVzdC1yYmFjLTEy",
      "endDate": "2028-07-30T23:59:59Z",
      "keyId": "00d2a9e8-5d50-4354-9118-5cc0e1713a2a",
      "startDate": "2018-07-31T03:11:50.2745325Z",
      "value": null
    },
    {
      "customKeyIdentifier": "bXAtdGVzdC1ha3NyYmFjLTEx",
      "endDate": "2028-07-30T23:59:59Z",
      "keyId": "5d860a64-e09a-474c-b5f9-1b455aee63d0",
      "startDate": "2018-07-30T23:08:07.6434504Z",
      "value": null
    }
  ]`

and then you attempt to delete one of the keys:
`az ad sp credential delete --id XXXXX --key-id 00d2a9e8-5d50-4354-9118-5cc0e1713a2a`

you receive this error saying it has having trouble updating the key you are not trying to delete:
`Update to existing credential with KeyId '5d860a64-e09a-474c-b5f9-1b455aee63d0' is not allowed.`

**Comment by rouke-broersma** [comment]
@yugangw-msft @haroldrandom this bug has existed since 2018... It is impossible to delete a credential with `az ad app credential delete` if there is more than 1 existing credential...

**Comment by jiasli** [comment]
The error `Update to existing credential with KeyId '5d860a64-e09a-474c-b5f9-1b455aee63d0' is not allowed.` is different from the original feature request. Let's focus on #19136.
