### ISSUE TITLE
Add API to return amount of blobs

### ISSUE THREAD

**Issue by madkroll** [Azure/azure-cli#5759]
Please consider to add such useful API call:
az storage blob count

Such commands are very useful for operating and administrating when you need to verify number of uploaded/downloaded blobs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 472d5f5f-3ce0-1220-3058-4b27068f512b
* Version Independent ID: 76e1699e-e6ba-c0dd-aad4-c5a7ab58260d
* Content: [az storage blob | Microsoft Docs](https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by williexu** [comment]
We have a [Jmespath](http://jmespath.org/) querying feature in our CLI. Simply add `--query <your query>` to any cli command.

To get a count of the blobs in a container, you can do `az storage blob list -c <container name> --query length(@)`
There is no need for a new api call.

**Comment by venkateshjayanaik** [comment]
> We have a [Jmespath](http://jmespath.org/) querying feature in our CLI. Simply add `--query <your query>` to any cli command.
> 
> To get a count of the blobs in a container, you can do `az storage blob list -c <container name> --query length(@)`
> There is no need for a new api call.

It's not working for me, it returns 1 for me. Currently I got 200 blob files in the container. I want to get the count as 200. How can I get

**Comment by venkateshjayanaik** [comment]
It worked with this 
--query "[]|length(@)" -o tsv
