### ISSUE TITLE
webapp:Support App Service Environment Isolated Plan SKUs for scaling-up/down an App Service Plan

### ISSUE THREAD

**Issue by cplemm** [Azure/azure-cli#5760]
Support App Service Isolated Plan SKU, i.e. instance types (I1, I2, I3) for App Service Plan scaling, e.g. az appservice plan update --sku I2  ...

Today, it is not possible to use the Azure CLI to scale-up/down instances in App Service Environment.

**Comment by panchagnula** [comment]
Tracking this for next sprint.

**Comment by panchagnula** [comment]
Will do this with the ASE creation support work we have planned

**Comment by panchagnula** [comment]
still waiting for PR to be completed on this - updating milestone.
