### ISSUE TITLE
How to use extensions?

### ISSUE THREAD

**Issue by yooakim** [Azure/azure-cli#5766]
It would be nice of some documentation explained how to use an extension once it has been installed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ea1a0d9-c0d5-657d-f73b-0e9220bec600
* Version Independent ID: 7138b13a-3381-1aee-346b-5e7f6905c5b3
* Content: [az extension | Microsoft Docs](https://docs.microsoft.com/en-us/cli/azure/extension?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-extension/azure/cli/command_modules/extension/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-extension/azure/cli/command_modules/extension/_help.py)
* Service: **unspecified**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by derekbekoe** [comment]
@yooakim Which extension are you looking for more information on?

**Comment by derekbekoe** [comment]
We now have extension documentation.
e.g. https://docs.microsoft.com/en-us/cli/azure/ext/aem/?view=azure-cli-latest
