### ISSUE TITLE
Tag releases in docker

### ISSUE THREAD

**Issue by estei** [Azure/azure-cli#5778]
Currently azure-cli is at version 2.0.28 according to the [releases page](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest) 

The latest version tagged in the [azure-cli-python repository](https://hub.docker.com/r/azuresdk/azure-cli-python/tags/) is version `:2.0.25` whereas the `:latest` has version 2.0.28 (`az --version`)

In our use case we have an image that extends the `azure-cli-python` image with a few scripts used in our CI.
We do not want to depend on a moving target like `:latest`, which can lead to inconsistencies between builds of the image. 
Currently there is a bug with the `az webapp deployment source config-zip` function in version 2.0.25 that makes it not work at all (#5440). This was fixed in a later version between `2.0.26` and `2.0.28`, but there is no version number tagged version that we can depend on after `2.0.25`.

It would be really excellent if new version releases were also tagged in docker again :-)

**Comment by derekbekoe** [comment]
We now publish official, versioned Docker images to hub.docker.com/r/microsoft/azure-cli/ as in [Run Azure CLI 2.0 in a Docker container](https://docs.microsoft.com/en-us/cli/azure/run-azure-cli-docker).

We will continue to use https://hub.docker.com/r/azuresdk/azure-cli-python/tags/ for the automated developer builds.

I've updated the description on [azure-cli-python](https://hub.docker.com/r/azuresdk/azure-cli-python/tags/) to indicate this.

**Comment by estei** [comment]
Great :+1: 

I will move our image over to using that repo then :-)
