### ISSUE TITLE
Listing resource types in a provider does not work

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#5781]
The page https://docs.microsoft.com/en-us/cli/azure/provider?view=azure-cli-latest#az_provider_list gives the following sample to list the resources in a resource provider:

az provider list --query [?namespace=='Microsoft.Network'].resourceTypes[].resourceType

However, it doesn't work. I used it exactly as written, and it just returns '[]'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f6d8c67-e3c2-13b5-29e7-f4c3276c4718
* Version Independent ID: e018eae4-178c-8636-3151-5080370563ce
* Content: [az provider | Microsoft Docs](https://docs.microsoft.com/en-us/cli/azure/provider?view=azure-cli-latest#az_provider_list)
* Content Source: [src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
On bash you need to surround the query string in double quotes.
