### ISSUE TITLE
Support for multi-zone AKS cluster?

### ISSUE THREAD

**Issue by gmflau** [Azure/azure-cli#5782]
Wonder when AKS will support multi-zone AKS cluster.  Meaning the support for distributing K8 worker nodes evenly on specified zones within a single Azure region.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks | Microsoft Docs](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az_aks_create)
* Content Source: [latest/docs-ref-autogen/aks.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/aks.yml)
* Service: **unspecified**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by RTodorov** [comment]
Also interested, any news?

**Comment by tjprescott** [comment]
We cannot comment on upcoming products or features in this forum. The best place to signal your interest in new features is here:
https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks

**Comment by dtsato** [comment]
If you're interested in this, please upvote this feature request: https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/36071860-support-multiple-availability-zones-for-ha-high-a
