### ISSUE TITLE
az login throws storage error 

### ISSUE THREAD

**Issue by melzoghbi** [Azure/azure-cli#5787]
I am trying to run az login command on RPI3 that runs Raspbian Stretch OS. When i try to login using Azure CLI i get the following error:

Error loading command module 'storage'

A screen shot when i am using it to login to ACR in Azure:

![image](https://user-images.githubusercontent.com/11993393/37303545-2618bd80-2605-11e8-827f-914c69f767fc.png)

This is what i have so far when i execute pip freeze:

pi@raspberrypi:~ $ pip freeze
adal==0.5.1
asn1crypto==0.24.0
automationhat==0.0.4
azure==3.0.0
azure-batch==4.0.0
azure-common==1.1.8
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.2
azure-datalake-store==0.0.18
azure-eventgrid==0.1.0
azure-graphrbac==0.40.0
azure-iot-edge-runtime-ctl==1.0.0rc21
azure-keyvault==0.3.7
azure-mgmt==2.0.0
azure-mgmt-advisor==1.0.1
azure-mgmt-applicationinsights==0.1.1
azure-mgmt-authorization==0.30.0
azure-mgmt-batch==5.0.0
azure-mgmt-batchai==0.2.0
azure-mgmt-billing==0.1.0
azure-mgmt-cdn==2.0.0
azure-mgmt-cognitiveservices==2.0.0
azure-mgmt-commerce==1.0.1
azure-mgmt-compute==3.0.1
azure-mgmt-consumption==2.0.0
azure-mgmt-containerinstance==0.3.1
azure-mgmt-containerregistry==1.0.1
azure-mgmt-containerservice==3.0.1
azure-mgmt-cosmosdb==0.3.1
azure-mgmt-datafactory==0.4.0
azure-mgmt-datalake-analytics==0.3.0
azure-mgmt-datalake-nspkg==2.0.0
azure-mgmt-datalake-store==0.3.0
azure-mgmt-devtestlabs==2.2.0
azure-mgmt-dns==1.2.0
azure-mgmt-eventgrid==0.4.0
azure-mgmt-eventhub==1.2.0
azure-mgmt-hanaonazure==0.1.0
azure-mgmt-iothub==0.4.0
azure-mgmt-iothubprovisioningservices==0.1.0
azure-mgmt-keyvault==0.40.0
azure-mgmt-loganalytics==0.1.0
azure-mgmt-logic==2.1.0
azure-mgmt-machinelearningcompute==0.4.0
azure-mgmt-managementpartner==0.1.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-media==0.2.0
azure-mgmt-monitor==0.4.0
azure-mgmt-msi==0.1.0
azure-mgmt-network==1.7.1
azure-mgmt-notificationhubs==1.0.0
azure-mgmt-nspkg==2.0.0
azure-mgmt-powerbiembedded==1.0.0
azure-mgmt-rdbms==0.1.0
azure-mgmt-recoveryservices==0.2.0
azure-mgmt-recoveryservicesbackup==0.1.1
azure-mgmt-redis==5.0.0
azure-mgmt-relay==0.1.0
azure-mgmt-reservations==0.1.0
azure-mgmt-resource==1.2.2
azure-mgmt-scheduler==1.1.3
azure-mgmt-search==1.0.0
azure-mgmt-servermanager==1.2.0
azure-mgmt-servicebus==0.4.0
azure-mgmt-servicefabric==0.1.0
azure-mgmt-sql==0.8.5
azure-mgmt-storage==1.5.0
azure-mgmt-subscription==0.1.0
azure-mgmt-trafficmanager==0.40.0
azure-mgmt-web==0.34.1
azure-nspkg==2.0.0
azure-servicebus==0.21.1
azure-servicefabric==6.1.2.9
azure-servicemanagement-legacy==0.20.6
azure-storage==0.36.0
azure-storage-blob==1.1.0
azure-storage-common==1.1.0
azure-storage-file==1.1.0
azure-storage-nspkg==3.0.0
azure-storage-queue==1.1.0
backports.ssl-match-hostname==3.5.0.1
blinker==1.3
blinkt==0.1.1
Cap1xxx==0.1.3
certifi==2018.1.18
cffi==1.11.5
chardet==3.0.4
click==6.6
colorama==0.3.7
cryptography==2.1.4
docker==3.0.0
docker-pycreds==0.2.2
drumhat==0.1.0
enum34==1.1.6
envirophat==0.0.6
ExplorerHAT==0.4.2
Flask==0.12.1
fourletterphat==0.1.0
futures==3.2.0
gpiozero==1.4.1
idna==2.6
ipaddress==1.0.19
isodate==0.6.0
itsdangerous==0.24
Jinja2==2.8
keyring==11.0.0
keyrings.alt==1.3
lxkeymap==0.1
MarkupSafe==0.23
mcpi==0.1.1
microdotphat==0.1.3
mote==0.0.3
motephat==0.0.2
msrest==0.4.27
msrestazure==0.4.22
numpy==1.12.1
oauthlib==2.0.6
pathlib2==2.3.0
phatbeat==0.1.0
pianohat==0.0.5
picamera==1.13
picraft==1.0
piglow==1.2.4
pigpio==1.38
Pillow==4.0.0
ply==3.9
pyasn1==0.1.9
pycparser==2.18
pycrypto==2.6.1
pygame==1.9.3
pygobject==3.22.0
pyinotify==0.9.6
PyJWT==1.6.0
pyOpenSSL==17.5.0
pyserial==3.2.1
python-dateutil==2.7.0
pyxdg==0.25
rainbowhat==0.0.2
requests==2.18.4
requests-oauthlib==0.8.0
RPi.GPIO==0.6.3
RTIMULib==7.2.1
scandir==1.7
scrollphat==0.0.7
scrollphathd==1.2.0
SecretStorage==2.3.1
sense-emu==1.0
sense-hat==2.2.0
simplejson==3.10.0
six==1.11.0
skywriter==0.0.7
sn3218==1.2.7
spidev==3.3
touchphat==0.0.1
twython==3.4.0
urllib3==1.22
websocket-client==0.47.0
Werkzeug==0.11.15

Any idea how to fix this?

**Comment by derekbekoe** [comment]
@melzoghbi Which version of the CLI do you have? How did you install?
The `pip freeze` output provided doesn't include `azure-cli` after a quick search.

**Comment by melzoghbi** [comment]
I resolved this issue by executing set of commands to get up to date packages in step 6:

https://medium.com/@melzoghbi/troubleshooting-pending-deployment-status-in-iot-edge-cad7232b385a

Thanks.
