### ISSUE TITLE
Error with declaring runtime

### ISSUE THREAD

**Issue by architechcro** [Azure/azure-cli#5790]
Referencing --runtime "node|8.1" returns error'8.1' is not recognized as an internal or external command,operable program or batch file. 
ofcourse error is returned using any runtime|version combination.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2983e943-cce1-effd-57d0-cce4b0c0a7e1
* Version Independent ID: 4262c40a-7140-b420-58b5-5cf40ab2316e
* Content: [az webapp | Microsoft Docs](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az_webapp_list_runtimes)
* Content Source: [latest/docs-ref-autogen/webapp.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/webapp.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ahmedelnably** [comment]
This usually happens when you use a PowerShell window to execute our CLI command
Cause: | is a split operator in PS.
Solution: use the following
az --% webapp create ....

adding the --% will instruct PowerShell to stop interpreting the | as a split operator

**Comment by chadcarlton** [comment]
I've only been using powershell for a little while now.. How do you use parameters after using the stop parsing command?
as soon as you use a --%, any of your parameters (like $ResourceGroupName) stop working for the arguments

**Comment by panchagnula** [comment]
Thats's correct once you add --% any other $arguments cannot be used & instead should be the explicit value. One question is is there a reason you are running the CLI commands (az webapp create) in PowerShell can you run them in a normal bash window, then you don't need to worry about this. Alternately you could use the Az.PowerShell commands directly as well https://docs.microsoft.com/en-us/powershell/module/Az.Websites/?view=azps-2.8.0&viewFallbackFrom=azps-1.3.0
