### ISSUE TITLE
functionapp: need support for az functionapp update

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-cli#5793]
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by yugangw-msft** [comment]
Since i will handle a similar one of #5547

**Comment by panchagnula** [comment]
@yugangw-msft, currently az webapp update can be used for function app as well. Should we create an equivalent for functionapp & add a kind check on the webapp update , that will point them to use az functionapp update?

**Comment by ahmedelnably** [comment]
When we created az functionapp we opted to only have the function specific settings and create commands, with the intention that the users will use az webapp commands for everything else. I think we should do the same here
