### ISSUE TITLE
NSG rule create: improve priority collision handling

### ISSUE THREAD

**Issue by luvvishu23** [Azure/azure-cli#5797]
az nsg create command expects an priority to be defined which I believe has some benefits. But in case we require to create nsg rule large number of senders then priority needs to be unique and is an blocker. For example when  VMs in Virtual machine scale set need an exclusion to a NSG we may have to check priority first before updating or creating  a rule. 

In place of this why not create a flag to be used for --nextavailablepriority , which when used will automatically pick  next available slot.

**Comment by tjprescott** [comment]
Thanks for the suggestion @luvvishu23.

**Comment by tjprescott** [comment]
The CLI team does not have the bandwidth to implement this due to other priorities, but I will mark this help wanted to invite an external contribution.

**Comment by tjprescott** [comment]
No one has expressed interested in taking up this task in the past 6 months. Closing.
