### ISSUE TITLE
Creating AKS cluster via CLI hangs

### ISSUE THREAD

**Issue by lobsteropteryx** [Azure/azure-cli#5799]
Hello all!  

I'm following the tutorial [here](https://docs.microsoft.com/en-us/azure/aks/tutorial-kubernetes-deploy-cluster), and attempting to create an AKS cluster using the following command:

```
az aks create --resource-group foo --name bar --node-count 1 --generate-ssh-keys
```

The command still shows "Running" after ~16 hours, and the cluster state is still "Creating", both in the portal and via `az aks list`.

The resource group is in the Eastern US location.  I've replicated this more than once, using different resource groups.  Is there something obvious I'm doing wrong here?  

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

Bash shell on MacOS Sierra.

```
azure-cli (2.0.28)

acr (2.0.21)
acs (2.0.27)
advisor (0.1.2)
appservice (0.1.28)
backup (1.0.6)
batch (3.1.10)
batchai (0.1.5)
billing (0.1.7)
cdn (0.0.13)
cloud (2.0.12)
cognitiveservices (0.1.11)
command-modules-nspkg (2.0.1)
configure (2.0.14)
consumption (0.2.2)
container (0.1.19)
core (2.0.28)
cosmosdb (0.1.19)
dla (0.0.18)
dls (0.0.19)
eventgrid (0.1.10)
extension (0.0.9)
feedback (2.1.0)
find (0.2.8)
interactive (0.3.16)
iot (0.1.17)
keyvault (2.0.19)
lab (0.0.17)
monitor (0.1.2)
network (2.0.24)
nspkg (3.0.1)
profile (2.0.19)
rdbms (0.0.12)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.24)
role (2.0.20)
servicefabric (0.0.10)
sql (2.0.22)
storage (2.0.26)
vm (2.0.27)

Python location '/usr/local/opt/python/bin/python3.6'
Extensions directory '/Users/ifirkin/.azure/cliextensions'

Python (Darwin) 3.6.4 (default, Mar  1 2018, 18:36:42)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

**Comment by lobsteropteryx** [comment]
It looks like this was due to a capacity issue in the data center: https://github.com/Azure/AKS/issues/240

Moving to `centralus` worked properly.

**Comment by qiangli** [comment]
eastus worked for me - just that it takes quite a while to complete - felt like more than 10 mins.

**Comment by hananiel** [comment]
First time it failed with "The subscription is not registered to use namespace 'Microsoft.ContainerService'. " Then it succeeded by itself, but the CLI was left hanging - So i didnt realize it created it. 
Running the command again, shows error log on "create role assigment" already exists, but this time it returned a bunch of Json.

**Comment by Vshalson** [comment]
Yo.
If it run for more than 14 min kill the progress. CTRL + C
And re-run the command. 💯 
`/ Running...
`
