### ISSUE TITLE
Question: Using pip to install CLI to Specific Directory

### ISSUE THREAD

**Issue by lostinthecloud** [Azure/azure-cli#5803]
---

### Environment summary

Version:
Multiple versions but specifically 2.0.25, 2.0.26, 2.0.27, and 2.0.28.

Install Method :
To be determined

OS:
CentOS 7

I am trying to install multiple versions of the Azure CLI in a CentOS 7 Docker container and be able to use all of these versions. 

Is there any way to install the CLI in specific directories and not globally? I have been trying to use the [rpm build script](https://github.com/Azure/azure-cli/tree/dev/build_scripts/rpm) to do this but haven't had luck with it. I have also tried using the [bundled installer](https://github.com/Azure/azure-cli/issues/3800) approach. My current strategy is using pip.

**Comment by lostinthecloud** [comment]
#3989 seems relevant to this as well. I am currently trying to use pip.

**Comment by lostinthecloud** [comment]
Using `pip install --prefix=<dir name> azure-cli==<version>` appears to accomplish what I am looking for. The last remaining issue is how to set the `PYTHONPATH=/path/to/python/modules` in [az](https://github.com/Azure/azure-cli/blob/master/src/azure-cli/az) to the local path to the pip modules. Changing `export PYTHONPATH="${DIR}/src:${PYTHONPATH}"` to `export PYTHONPATH="/path/to/python/modules"` resolves the `/usr/bin/python: No module named azure` encountered I initially encountered. Is there a way to change `PYTHONPATH` that will be recognized by `az` without changing `az` as is?

**Comment by lostinthecloud** [comment]
So, I was able to accomplish this with `pip`, `virtualenv`, and changing [az](https://github.com/Azure/azure-cli/blob/master/src/azure-cli/az) as referenced in #3989. 

Basically, you create a `virtualenv` in the directory where you would like the cli to be installed, install the cli via `pip` and specify the version you would like, and change the `PYTHONPATH` in `az`. 

I will close this issue, however, I will probably open an issue to update documentation to show people how to do this. It seems that most documentation focuses on globally installing the CLI. However, addressing #3989 does still need to be addressed so perhaps something can be done after addressing #3989. In general, it would be nice to promote more installation options.

**Comment by danielhelfand** [comment]
I know I closed this, but I just wanted to say that my previous comments regarding #3989 were not correct. Please see #5223 for how to install using `pip install -r` for installing multiple versions in one environment. A `virtualenv` is still needed for each version. Using `pip install -r` does not require changing `az` as stated in my previous comment.
