### ISSUE TITLE
Azure functions ignores entries for CORS allowed origins

### ISSUE THREAD

**Issue by yakeem** [Azure/azure-cli#5814]
I'm trying to deploy Azure with resource templates.
In my template.json I want to set up allowed origins to all:

`"siteConfig": {
                    "cors": {
                        "allowedOrigins": [
                            "*"
                        ]
                    },`

The problem is that Azure anyway creates by default additional entries:

![image](https://user-images.githubusercontent.com/2962716/37394524-4104a1de-2774-11e8-9fd3-5163e618afb2.png)

And after that I have problem with CORS, "*" rule seems to be ignored if there are any specific cors entries. 
So I need to manually delete these three added by Azure. Do you have any idea how I can automatically get rid of them or somehow else setup allowed origins to all?

**Comment by tjprescott** [comment]
Which CLI command are you using and which service are you creating CORS rules for?

**Comment by yakeem** [comment]
I'm creating a resource group with command:
`az group deployment create  --resource-group testrg --template-file template.json --parameters parameters.json --mode Complete`

and within this group, i'm creating an Azure Function, triggered by HTTP binding.
I want to create CORS rules for this function. 

In template.json i'm describing this Azure Function, and as I have shown before, I'm adding one entry for cors allowed origin "*".

Azure however adds three additional allowed origins:
https://functions.azure.com
https://functions-staging.azure.com
https://functions-next.azure.com

And in the end, only these three origins are allowed for CORS, the general rule for all origins is then ignored.

**Comment by tjprescott** [comment]
This sounds like a service limitation. @panchagnula can you confirm?

**Comment by jrgithub** [comment]
Is there an ETA for an enhancement where the option to disable the default CORS rules will be supplied via ARM template (i.e. non-manual methods) for customers who do not require them?

**Comment by panchagnula** [comment]
@jrgithub  have you tried this command? https://docs.microsoft.com/en-us/cli/azure/webapp/cors?view=azure-cli-latest , this available for functonapps as well https://docs.microsoft.com/en-us/cli/azure/functionapp/cors?view=azure-cli-latest -

**Comment by lswright** [comment]
> @jrgithub have you tried this command? https://docs.microsoft.com/en-us/cli/azure/webapp/cors?view=azure-cli-latest , this available for functonapps as well https://docs.microsoft.com/en-us/cli/azure/functionapp/cors?view=azure-cli-latest -

Unfortunately this command does not work for me with web apps.  The azure terminal outputs an updated allowedOrigins key:value but the host continues to generate a cors error.

**Comment by panchagnula** [comment]
@ahmelsayed - can you please take a look & help out here please. Are there any special CORS setting that are missing here?

**Comment by navinmistry** [comment]
Hi,
I'm getting same issue where these three default entries remains and CORS headers don't get reflect in response.
I'm using node-js based function and I could temporarily achieved the desired result by removing all CORS rules which were default added ( and did not add a new entry with *)
additionally I added CORS headers manually in response in nodeJS function and after that only they are coming in response.

so the only question remains is " Can these rules be removed programatically or using ARM template" so no manual intervention required. 

R's
navin

**Comment by panchagnula** [comment]
* will not remove all the entries, in Arm Template you should use an [] to remove all the rules, you can try by using resources.azure.com, & edit the Site Config CorRules property.

**Comment by navinmistry** [comment]
Tried with below setting in template after having a word with azure guys on a service ticket call.

"resources": [{
      "apiVersion": "2016-08-01",
      "name": "[parameters('appName')]",
      "type": "Microsoft.Web/sites",
      "properties": {
        "name": "[parameters('appName')]",
        "siteConfig": {
          "cors": {
            "allowedOrigins": ["*"]
          },
       . . .
       . . .

This seems to be working, I didn't try it earlier as the very first comment convinced me it wouldn't work.
( Just to mention, I have CORS headers set in my function explicitly  and they've started getting honoured after this template change )

looks like a solution to me!!

**Comment by panchagnula** [comment]
i am closing this since this - we have a CLI command for this that has been released.
