### ISSUE TITLE
Unable to log into Azure CLI

### ISSUE THREAD

**Issue by sai306** [Azure/azure-cli#5819]
Hi. I am working under corporate environment. I use Windows 10 enterprise 64bit. I am getting error while logging to my Azure portal from CMD.
Version of Azure I am using: Azure CLI =0.10.17
Steps: Open CMD, type Azure
Step2. Type Azure login
I got the below error. Previous story was: I downloaded the latest version of Azure CLI 2 last week, but I have different set of issues with that. So, I tried the old Azure CLI atleast. 

****Error I got with Azure CLI 0.10.17.**

C:\Users\vsai>azure login
info:    Executing command login
+ Authenticating...
error:   unable to get local issuer certificate
ApplicationInsights:Sender [ { Error: unable to get local issuer certificate
      at Error (native)
      at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
      at emitNone (events.js:86:13)
      at TLSSocket.emit (events.js:185:7)
      at TLSSocket._finishInit (_tls_wrap.js:610:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' } ]
error:   Error information has been recorded to C:\Users\v70062\.azure\azure.err
error:   login command failed.

**Comment by derekbekoe** [comment]
Related to https://github.com/Azure/azure-docs-cli-python/issues/681

**Comment by yugangw-msft** [comment]
There is known issue being fixed that AAD gateway machines have a few missing intermediate cert in the chain. I will close this issue when the fix gets rolled out

**Comment by yugangw-msft** [comment]
this should have been fixed. Please reactivate if you still see it
