### ISSUE TITLE
[Storage] The encryption key parameters are missing from storage account update command.

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#5820]
Three parameters are missing from `az storage account update` command, which impacts the storage customer managed key scenario.
```
    --encryption-key-name   : The name of the KeyVault key.
    --encryption-key-vault  : The Uri of the KeyVault.
    --encryption-key-version: The version of the KeyVault key.
```
This is a regression introduced during knack conversion.

**Comment by AngshumanNayakMSFT** [comment]
Thanks for helping fix this Troy.
