### ISSUE TITLE
Azure cloud shell login disabled error

### ISSUE THREAD

**Issue by rfum** [Azure/azure-cli#5822]
I'm trying to login a different tenant from portal cloud shell bash with "az login --tenant mytenant.onmicrosoft.com" it gives error : azure cloud shell automatically authenticates the user it was initially launched under. As a result az login is disabled. How can I solve this problem any idea?

**Comment by tjprescott** [comment]
Correct me if I'm wrong @yugangw-msft but this has been fixed with the most recent release

**Comment by yugangw-msft** [comment]
Actually, I rolled back on last Friday, as a 3rd party's CLI is not ready to migrate to the new model which CLI needs to enable the login command back

**Comment by rfum** [comment]
Solved the issue problem was not relevant with az-cli.
