### ISSUE TITLE
webapp deployment source config-zip use async api

### ISSUE THREAD

**Issue by estei** [Azure/azure-cli#5823]
Currently the `az webapp deployments source config-zip` command uses the sync version of the api endpoint `api/zipdeploy` on the webapp

This results in a small issue when deploying this way, because apparently the load balancer in front of the `.scm.azurewebsites.net` has a request timeout of 230 seconds, as mentioned by David Ebbo [in this issue on kudu](https://github.com/projectkudu/kudu/issues/2474).

We have quite a few times run into an issue where this leads to us getting a status code 500 back from a deploy, while the deploy was still finishing in the web app.

We have in our projects changed away from using the azure cli, to using a hand crafted bash script that uses the async version of the api as referenced in the documentation [here](https://github.com/projectkudu/kudu/wiki/REST-API#zip-deployment).

I think the `az webapp deployments source config-zip` command could benefit from using the `?isAsync=true` query parameter, to stop getting unnecessary and untrue errors.

**Comment by troydai** [comment]
Moving to the backlog. @panchagnula please let me know what's the intended release day for this feature.

**Comment by panchagnula** [comment]
@troydai  this already released. https://pypi.org/project/azure-cli-appservice/

![image](https://user-images.githubusercontent.com/13839372/40806475-70550b1e-64d6-11e8-8d6d-1f7f13ba63ce.png)
