### ISSUE TITLE
It should be possible to create Manage policies for Service Bus entities

### ISSUE THREAD

**Issue by javiermolinar** [Azure/azure-cli#5824]
The command:

az servicebus namespace authorization-rule create --resource-group --namespace-name --name --rights Manage

Returns a Bad request.

This is due that Manage policies comes with Send and Listen as well. This should be handle by cli by a) add them implicitly or throwing an informative message, not a bad request.

This happens for namespace level and for queues and topics.

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

Install Method: MSI
CLI Version: azure-cli (2.0.29)
OS Version: Windows 10 Enterprise
Shell Type: powershell

**Comment by jfggdl** [comment]
@v-ajnava. This is an issue close to #3149 (https://github.com/Azure/azure-sdk-for-python/issues/3149). Would you please validate the kind of message that we are showing the users and provide/release a better message. Please consult within the team, but we have two options: 1) Show an error indicating that Manage includes both Send and Listen rights and need to be specified with the request or 2) Accept Manage, but warn the user that it also includes Send and Listen right. I would prefer 1).

**Comment by jfggdl** [comment]
@axisc - We have decided for 1).  We need to provide better messaging. Would you please work with @v-ajnava on this?
