### ISSUE TITLE
az vm create: what is the picked default location?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-cli#583]
`az vm create` does not enforce `--location` as a default argument and it proceeds with the API call. I'm guessing there is a default location although not documented?:

```
    --location -l                 : Location.
```

**Comment by yugangw-msft** [comment]
it is retrieved from your resource group, which needs to be re-created

**Comment by ahmetalpbalkan** [comment]
Hmm yeah I realized. I will leave it up to you whether this should be documented further or not.
