### ISSUE TITLE
az vm run-command invoke produces cached output

### ISSUE THREAD

**Issue by thisSIDEofRANDOM** [Azure/azure-cli#5833]
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
Docker version of azure-cli: 
azuresdk/azure-cli-python   latest              0bd2597e121d        6 days ago          388MB

bash-4.3# az --version
azure-cli (2.0.29)

acr (2.0.22)
acs (2.0.28)
advisor (0.5.0)
appservice (0.1.29)
backup (1.0.7)
batch (3.1.11)
batchai (0.1.6)
billing (0.1.7)
cdn (0.0.13)
cloud (2.0.12)
cognitiveservices (0.1.11)
command-modules-nspkg (2.0.1)
configure (2.0.14)
consumption (0.2.2)
container (0.1.19)
core (2.0.29)
cosmosdb (0.1.19)
dla (0.0.18)
dls (0.0.19)
eventgrid (0.1.11)
eventhubs (0.1.0)
extension (0.0.10)
feedback (2.1.0)
find (0.2.8)
interactive (0.3.17)
iot (0.1.18)
keyvault (2.0.20)
lab (0.0.17)
monitor (0.1.3)
network (2.0.25)
nspkg (3.0.2)
profile (2.0.20)
rdbms (0.1.0)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.25)
role (2.0.20)
servicebus (0.1.0)
servicefabric (0.0.11)
sql (2.0.23)
storage (2.0.27)
vm (2.0.28)

Python location '/usr/local/bin/python'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.3 (default, Dec 20 2017, 01:32:21) 
[GCC 5.3.0]

Legal docs and information: aka.ms/AzureCliLegal

```

When using azure cli to run a command on machine, the output for running the command twice in a row is cached and not updated to the most recent run.

Easy to reproduce with any linux machine:

```
bash-4.3# az vm run-command invoke --command-id runshellscript --name testweb --resource-group testgroup --scripts "date"
```
Run this twice in a row and you'll see the time doesn't change even though its run at different times.

Example output for both executions:
```
  "output": [
    {
      "code": "ProvisioningState/succeeded",
      "displayStatus": "Provisioning succeeded",
      "level": "Info",
      "message": "Enable succeeded: \n[stdout]\nFri Mar 16 05:11:22 UTC 2018\n\n[stderr]\n"
    }
  ]
```

I found this script gets uploaded on a clean vm to /var/lib/waagent/run-command/download/0

The script doesn't change so it doesn't seem to create a new file on output but the stdout file doesn't update either.

Related Issue happening for powershell version as well: https://github.com/Azure/azure-powershell/issues/5757

**Comment by tjprescott** [comment]
@sauryadas can you comment?  This sounds like service behavior.

**Comment by yugangw-msft** [comment]
@koralski, please clarify?

**Comment by thisSIDEofRANDOM** [comment]
Hi all!

Anyone have an update on this or is there another place I should report this?

Currently this is breaking all azure automation we were using run commands with since we can't be sure the output is recent.

**Comment by yugangw-msft** [comment]
@thisSIDEofRANDOM, I shall post some updates tomorrow as i need to get an internal icm ticket filed and acknowledged by the compute service team

**Comment by yugangw-msft** [comment]
And the workaround for now is to directly use the `az vm extension set` and then use the `get-instance-view` t retrieve the output:
```bash
az vm extension set -g tg --vm-name vm1 -n customScript --publisher Microsoft.Azure.Extensions --settings "{\"commandToExecute\": \"date\"}" --version 2.0
az vm get-instance-view -g rg -n vm1 --query "instanceView.extensions|[?type=='Microsoft.Azure.Extensions.customScript']|[0].statuses[0].message"
```

**Comment by kevi5702** [comment]
Hey @yugangw-msft interesting! So with the above if we had long scripts that were deploying before would we need to manually convert them to the above json format?

For the time being we have been carefully tweaking the script each run to have the date/time echoed to make sure it has a unique md5sum each run. This causes some extra uploads to the server but has at least made sure we aren't hitting the cache issue.

**Comment by yugangw-msft** [comment]
@kevi5702 , for complex script file, you can use `fileUris` from the custom extension, check out details from [doc site](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/virtual-machines/linux/extensions-customscript.md)

We are actively investigating this regression and I will post more updates in time

**Comment by koralski** [comment]
@thisSIDEofRANDOM You can still specify a file in your command. See the help: 
az vm run-command invoke -h
--scripts              : Script lines separated by whites spaces. Use @{file} to load from a file.

As a workaround you should always change the script (maybe add an empty line at the end) to force re-execution. Currently we detect no changes in the script and we don't execute it again. This was a bug on our side that we are fixing now. Thank you for reporting this issue.

**Comment by thisSIDEofRANDOM** [comment]
Thanks @koralski sorry for slow reply had some time off! 

That makes explains it :D Appreciate you all keeping the quick fixes up!

**Comment by yugangw-msft** [comment]
Verified it is fixed now
