### ISSUE TITLE
Output for sub-commands should be formatted nicely

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-cli#584]
Right now, the built-in help looks very confusing, compared to the output from the Node.js-based Azure xPlat CLI

![image](https://cloud.githubusercontent.com/assets/466713/17306932/c3acde40-57ef-11e6-82be-795352d0359a.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by yugangw-msft** [comment]
This is known issue. @johanste. i agree this is confusing by comparing with the node version, which outputs sub-commands. The error here is not suggestive for the next steps people should take.

**Comment by yugangw-msft** [comment]
same issue with #574, i am closing this one
