### ISSUE TITLE
Add example for adding IoTHub Route

### ISSUE THREAD

**Issue by sandervandevelde** [Azure/azure-cli#5844]
The "az iot hub update" has an example showing how to add an firewall filter rule. This works for adding an endpoint. But adding a route is more complicated:

      "routes": [
        {
          "condition": "$body.byPortal=\"true\"",
          "endpointNames": [
            "portalendpoint"
          ],
          "isEnabled": true,
          "name": "portalroute",
          "source": "DeviceMessages"
        }
      ]

The "endpointNames" is an array. How can I manipulate this?

Please provide an extra, more elaborate, example for adding Routes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9afeaa5c-1af2-8fcc-69b4-15ae81a0d342
* Version Independent ID: dea97474-170e-f678-f812-a1e4cdf56c76
* Content: [az iot hub](https://docs.microsoft.com/en-us/cli/azure/iot/hub?view=azure-cli-latest#az_iot_hub_update)
* Content Source: [src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/_help.py)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jlian** [comment]
This will need a new release from us. Feature request

**Comment by jlian** [comment]
Targeting fix by Nov https://msazure.visualstudio.com/One/_workitems/edit/4979257
