### ISSUE TITLE
Docs for az aks create - needs to mention service principal creation

### ISSUE THREAD

**Issue by benc-uk** [Azure/azure-cli#5845]
The `az aks create` docs should mention the creation of a default service principal, and how that is held in `~/.azure/aksServicePrincipal.json` (as per this issue https://github.com/Azure/AKS/issues/117) 

Currently there is no mention of this anywhere and it makes the whole process very mysterious

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az_aks_create)
* Content Source: [latest/docs-ref-autogen/aks.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/aks.yml)
* Service: **unspecified**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by gaziqbal** [comment]
Apart from docs, the AZ CLI should also refer to the existence of this file when it fails. The current message is outdated.

`Operation failed with status: 'Bad Request'. Details: Service principal XYZ not found in Active Directory tenant XYZ, Please see https://aka.ms/acs-sp-help for more details.`

**Comment by palma21** [comment]
Latest CLI aks create by passing an existing SP should work fine
We added the requested clarifications into:
https://docs.microsoft.com/en-us/azure/aks/kubernetes-service-principal#additional-considerations

**Comment by jluk** [comment]
Closing per Jorge's comment. We are also doing a second pass on the document to include that subsequent cmds will depend on that sp stored.
