### ISSUE TITLE
CommandGroup `expand` method not compatible with Autorest 3 generated SDKs

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#5850]
The `expand` method attempts to flatten a complex object by examining its properties and creating arguments for the individual properties. Autorest 3 changes model types to no longer have strongly-typed constructors, but rather to accept keyword arguments. This is not compatible with the technique currently used, which involved reflecting on the constructor signature.

Until this is fixed, expand is only compatible with Autorest 2-based SDKs.

cc/ @rohit-joy @lmazuel @troydai

**Comment by yonzhan** [comment]
@jiasli  add to S162.

**Comment by jiasli** [comment]
This should be addressed in the next generation of Autorest.
