### ISSUE TITLE
Owner

### ISSUE THREAD

**Issue by BitstreamCowboy** [Azure/azure-cli#5855]
URL: https://bcsnetwork.visualstudio.com//BitstreaCowboyNetwork/_home
I'm having a blast!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bea54d36-cb69-577c-e114-2c4bd0e33728
* Version Independent ID: 812e7aa5-2e8a-f9ef-d922-df188bd6275a
* Content: [az webapp deployment user](https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/user?view=azure-cli-latest#az_webapp_deployment_user_set)
* Content Source: [latest/docs-ref-autogen/webapp/deployment/user.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/webapp/deployment/user.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Glad to hear it.
