### ISSUE TITLE
ml (0.1.0a27.post3) returns python error. 

### ISSUE THREAD

**Issue by jmagosta** [Azure/azure-cli#5859]
Possibly an interaction with 'az ml' install:

Shell clipping:  

> $ az functionapp -h
> cannot import name 'ManagedServiceIdentity'
> Traceback (most recent call last):
>   File "/anaconda/envs/py35/lib/python3.5/site-packages/azure/cli/main.py", line 36, in main
>     cmd_result = APPLICATION.execute(args)
>   File "/anaconda/envs/py35/lib/python3.5/site-packages/azure/cli/core/application.py", line 185, in execute
>     args = self.parser.parse_args(argv)
>   File "/anaconda/envs/py35/lib/python3.5/argparse.py", line 1726, in parse_args
>     args, argv = self.parse_known_args(args, namespace)
>   File "/anaconda/envs/py35/lib/python3.5/argparse.py", line 1758, in parse_known_args
>     namespace, args = self._parse_known_args(args, namespace)
>   File "/anaconda/envs/py35/lib/python3.5/argparse.py", line 1946, in _parse_known_args
>     positionals_end_index = consume_positionals(start_index)
>   File "/anaconda/envs/py35/lib/python3.5/argparse.py", line 1923, in consume_positionals
>     take_action(action, args)
>   File "/anaconda/envs/py35/lib/python3.5/argparse.py", line 1832, in take_action
>     action(self, namespace, argument_values, option_string)
>   File "/anaconda/envs/py35/lib/python3.5/argparse.py", line 1129, in __call__
>     subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
>   File "/anaconda/envs/py35/lib/python3.5/argparse.py", line 1758, in parse_known_args
>     namespace, args = self._parse_known_args(args, namespace)
>   File "/anaconda/envs/py35/lib/python3.5/argparse.py", line 1964, in _parse_known_args
>     start_index = consume_optional(start_index)
>   File "/anaconda/envs/py35/lib/python3.5/argparse.py", line 1904, in consume_optional
>     take_action(action, args, option_string)
>   File "/anaconda/envs/py35/lib/python3.5/argparse.py", line 1832, in take_action
>     action(self, namespace, argument_values, option_string)
>   File "/anaconda/envs/py35/lib/python3.5/argparse.py", line 1016, in __call__
>     parser.print_help()
>   File "/anaconda/envs/py35/lib/python3.5/argparse.py", line 2358, in print_help
>     self._print_message(self.format_help(), file)
>   File "/anaconda/envs/py35/lib/python3.5/site-packages/azure/cli/core/parser.py", line 168, in format_help
>     is_group)
>   File "/anaconda/envs/py35/lib/python3.5/site-packages/azure/cli/core/_help.py", line 48, in show_help
>     else GroupHelpFile(delimiters, parser)
>   File "/anaconda/envs/py35/lib/python3.5/site-packages/azure/cli/core/_help.py", line 367, in __init__
>     child.load(options)
>   File "/anaconda/envs/py35/lib/python3.5/site-packages/azure/cli/core/_help.py", line 296, in load
>     description = getattr(options, 'description', None)
>   File "/anaconda/envs/py35/lib/python3.5/site-packages/azure/cli/core/parser.py", line 193, in __getattribute__
>     if callable(self._description) else self._description
>   File "/anaconda/envs/py35/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 660, in description_loader
>     return extract_full_summary_from_signature(get_op_handler(operation))
>   File "/anaconda/envs/py35/lib/python3.5/site-packages/azure/cli/core/commands/__init__.py", line 547, in get_op_handler
>     op = import_module(mod_to_import)
>   File "/anaconda/envs/py35/lib/python3.5/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
>   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
>   File "/anaconda/envs/py35/lib/python3.5/site-packages/azure/cli/command_modules/appservice/custom.py", line 19, in <module>
>     from azure.mgmt.web.models import (Site, SiteConfig, User, AppServicePlan, SiteConfigResource,
> ImportError: cannot import name 'ManagedServiceIdentity'

### Environment summary

Install Method (DSVM preinstalled version  /
 CLI version (`az --version`) azure-cli (2.0.22) with ml (0.1.0a27.post3) install / 
OS version / Shell Type (e.g. bash on Ubuntu  16.04 DSVM)  

```
```

**Comment by derekbekoe** [comment]
To get the CLI working again, you can recreate the virtual environment.
I suspect the 'az ml' module changed some dependencies.

**Comment by derekbekoe** [comment]
Closing as no response for a while.
Also, for `az ml` issues, post an issue at https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=MachineLearning
