### ISSUE TITLE
azure vm create: required arguments

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-cli#586]
Follow up to #585, #582, it appears like required arguments like 
- `--image`,
- `--admin-username`

are not correctly being enforced or documented in --help.

**Comment by JasonRShaver** [comment]
These two parameters are not required as defaults are provided.  

--image defaults to Win2012R2Datacenter as shown in --help
--admin-username is only required for Windows-based images.  For VMs with Linux-based images it defaults to the current user, which is displayed in --help

**Comment by ahmetalpbalkan** [comment]
> --image defaults to Win2012R2Datacenter

Why? What was the thinking behind this decision?

> For VMs with Linux-based images it defaults to the current user

Why? What was the thinking behind this decision?

**Comment by BurtBiel** [comment]
The default image is the most recent Windows Server image found in 'az vm image list'.

We default the admin username for both windows and linux to the current user.  This means 1) admin username is optional, and 2) the default ssh works without specifying the username (i.e. plain "ssh <ip address>" works on the machine the vm was created from )

**Comment by ahmetalpbalkan** [comment]
> The default image is the most recent Windows Server image found in 'az vm image list'.

why is this not ubuntu and windows server?

> This means 1) admin username is optional, and 2) the default ssh works without specifying the username

I guess that's fine. It might provide certain ease of use at the cost of users implicitly signing up for a username that they did not intend to use. Though I don't have data to back this up.

**Comment by ahmetalpbalkan** [comment]
@BurtBiel Pinging this thread as it is important. We are going to have a problem if the default image becomes a Windows image. Linux is a first class citizen on Azure and I don't see the point of favoring one over another. If you want to discuss offline, I believe my team AzLinux@ would be open to discussion.

**Comment by BurtBiel** [comment]
We're discussing possibilities here with respect to the image selection process.  Do you expect the image field would have no default (user must select it) or some other behavior?

**Comment by ahmetalpbalkan** [comment]
User must select it IMHO

**Comment by tjprescott** [comment]
PR #789 merged. Closing issue.
