### ISSUE TITLE
Azure CLI deb installation fails

### ISSUE THREAD

**Issue by godotgildor** [Azure/azure-cli#5861]
I am trying to install the Azure CLI using a deb package following the instructions [here](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest).

On my fresh Ubuntu 14.04 it fails with an error message of:
`Failed to fetch https://packages.microsoft.com/repos/azure-cli/dists/trusty/main/binary-amd64/Packages  Received HTTP code 403 from proxy after CONNECT`

I can install it using the manual method, but this method requires user interaction and I'd like to be able to install unattended.

**Comment by derekbekoe** [comment]
Seems like you're behind a proxy. I would check that you have access to that endpoint.
Alternatively the direct download is https://packages.microsoft.com/repos/azure-cli/pool/main/a/azure-cli/azure-cli_2.0.29-1~trusty_all.deb

**Comment by godotgildor** [comment]
Thanks!
