### ISSUE TITLE
Error When Create VM using CLI

### ISSUE THREAD

**Issue by J1nFr34ks** [Azure/azure-cli#5870]
I'm having problem when creating vm using CLI.
When I type "az vm create --resource-group myresourcegroup --name myvm --image UbuntuLTS --generate-ssh-keys", It shows error message "Could not find member 'managedDisk' on object of type 'OSDisk'. Path 'properties.storageProfile.osDisk.managedDisk', line 1, position 372."

How can I rid this error?

---

Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build)
apt-get

CLI version (`az --version`)
azure-cli (2.0.29)

acr (2.0.22)
acs (2.0.28)
advisor (0.5.0)
appservice (0.1.29)
backup (1.0.7)
batch (3.1.11)
batchai (0.1.6)
billing (0.1.7)
cdn (0.0.13)
cloud (2.0.12)
cognitiveservices (0.1.11)
command-modules-nspkg (2.0.1)
configure (2.0.14)
consumption (0.2.2)
container (0.1.19)
core (2.0.29)
cosmosdb (0.1.19)
dla (0.0.18)
dls (0.0.19)
eventgrid (0.1.11)
eventhubs (0.1.0)
extension (0.0.10)
feedback (2.1.0)
find (0.2.8)
interactive (0.3.17)
iot (0.1.18)
keyvault (2.0.20)
lab (0.0.17)
monitor (0.1.3)
network (2.0.25)
nspkg (3.0.2)
profile (2.0.20)
rdbms (0.1.0)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.25)
role (2.0.20)
servicebus (0.1.0)
servicefabric (0.0.11)
sql (2.0.23)
storage (2.0.27)
vm (2.0.28)

Python location '/opt/az/bin/python3'
Extensions directory '/home/ubuntu/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Mar 10 2018, 01:18:09)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal

OS version
Ubuntu 16.04.1 LTS

Shell Type (e.g. bash, cmd.exe, Bash on Windows) 
bash

**Comment by tjprescott** [comment]
Please provide the required information when submitting a new issue.

**Comment by J1nFr34ks** [comment]
Sorry, I have provide the required informartion.

**Comment by yugangw-msft** [comment]
I can't repro. This same command is being tested every day in our daily run

**Comment by yugangw-msft** [comment]
@J1nFr34ks, please reactivate if you can still repro, and please share the trace using `--debug`
