### ISSUE TITLE
does az storage blob download take advantage of sparse files? It should..

### ISSUE THREAD

**Issue by marvinthepa** [Azure/azure-cli#5872]
Either I cannot find out how to do it, or `az storage blob download` does not seem to take advantage of sparse files.
Downloading a vm os disk snapshot of 30GB, containing only about 1.7GB of data takes more than 60 minutes while [azcopy](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-linux) downloads the same file in 7 minutes.

The only reference to something like this in the documentation is `--max-connections`:

```
    --max-connections             :  ...
                                    ... 
                                    This may also be useful if many blobs are expected to be empty
                                    as an extra request is required for empty blobs if
                                    max_connections is greater than 1.  Default: 2.
```

However, setting max-connections to 1 does not seem to make a difference to using the default of 2.

Am I doing something wrong?
---

### Environment summary

Tried in two different environments, mac os:
```
$ echo $SHELL
zsh
$ brew install azure-cli
...
$ az --version
azure-cli (2.0.28)

...

Python location '/usr/local/opt/python/bin/python3.6'
Extensions directory '/Users/d064064/.azure/cliextensions'

Python (Darwin) 3.6.4 (default, Mar  1 2018, 18:36:50)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

Also using docker image (on linux)
```
docker run --rm -it microsoft/azure-cli:2.0.28 bash
```

**Comment by williexu** [comment]
@marvinthepa thanks for pointing this out, we are aware of the current limitation.

The cli leverages the storage sdk: https://github.com/Azure/azure-storage-python
This feature should be implemented on the sdk level so python devs, as well as the CLI, can make use of it.
@seguler

**Comment by seguler** [comment]
I believe it does. @zezha-msft to confirm

**Comment by zezha-msft** [comment]
@seguler We have the sparse file optimization for upload but not for download. For download, we are currently treating all blob types as equal and simply downloading everything. Perhaps we can add this item to our backlog.

**Comment by zezha-msft** [comment]
@williexu I have added this item in our backlog.

**Comment by iyerusad** [comment]
+1 on sparse enabled downloads using az cli - the only packaged alternative appears to be to use AzCopy, which is not portable to Linux/Mac agents. Want to use this in VSTS.

**Comment by zezha-msft** [comment]
This issue will be solved in the new AzCopy V10. The related issue is [here](https://github.com/Azure/azure-storage-azcopy/issues/391).

**Comment by iyerusad** [comment]
@zezha-msft - Please note AzCopy is NOT available under Azure Automation: Even if I manually downloaded AzCopy within the Azure Automation, Azure Automation didn't/doesn't allow running of arbitrary binaries. 

It would be preferable that `az storage blob download ` handles sparse file downloading efficiently (similarly to AZcopy).

**Comment by zezha-msft** [comment]
Hi @iyerusad, thanks for the clarification! I see that it's still necessary to provide this functionality in the Python SDK.

**Comment by zezha-msft** [comment]
I've logged this item to be included in the next generation of the Storage SDK: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-blob. 

It will be part of the GA criteria.

**Comment by jeremybusk** [comment]
I'm having a hard time following this solution. So does/will az storage blob copy or zacopt ever support conversion to local sparse file on download? I can gzip/compress after the fact but it should be in app, IMHO.
