### ISSUE TITLE
az ad app should be able to set oauth2AllowImplicitFlow=true

### ISSUE THREAD

**Issue by gavinbarron** [Azure/azure-cli#5887]
To provision or update an AD App Registration which allows the OAuth2 Implicit flow you must either use the PowerShell tools or open the portal to complete this configuration step. 

It would be good to have a true cross platform means of doing this with the [az ad app](https://docs.microsoft.com/en-gb/cli/azure/ad/app?view=azure-cli-latest) commands

**Comment by yugangw-msft** [comment]
I added yesterday through #5852
