### ISSUE TITLE
az vm image list --publisher github: no images show up

### ISSUE THREAD

**Issue by jluk** [Azure/azure-cli#589]
It seems the command `az vm image list --publisher github` does not return the github enterprise images that are listed under the github publisher name. Same happens with Bitnami.

**Comment by derekbekoe** [comment]
Running `az vm image list --publisher github --all` will show the images.
@yugangw-msft Should this be made clearer in the help text for the command?

**Comment by jluk** [comment]
Interesting - what is being shown without the --all argument?

**Comment by derekbekoe** [comment]
Referencing a related issue https://github.com/Azure/azure-cli/issues/575#issuecomment-236693176.
Thanks for the feedback!

**Comment by yugangw-msft** [comment]
we load from a [json file] (https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json)
In a separate issue, we are considering to output a statement to stderr to tell you so

**Comment by yugangw-msft** [comment]
I will close this issue as dupe. Thanks for the data that help us do the right thing

**Comment by jluk** [comment]
Yep - looking forward to seeing the progress thanks Yugang 👍
