### ISSUE TITLE
Issue with short name for parameter elastic-pool

### ISSUE THREAD

**Issue by payiAzure** [Azure/azure-cli#5890]
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
For new added az elastic pool command "az sql elastic-pool op list --elastic-pool", this command is to list the operations on an elastic pool. 
    We are thinking of short name for parameter --elastic-pool.
     --elastic-pool  --ep
```

**Comment by derekbekoe** [comment]
`--el` would work with no code changes if nothing else matches with `el`.
This is a Python argparse feature that comes by default.

**Comment by jaredmoo** [comment]
This is not a required parameter so I think it's ok to keep this with long name.
