### ISSUE TITLE
`az storage account create` gives ambiguous message when account already exists

### ISSUE THREAD

**Issue by sptramer** [Azure/azure-cli#5897]
If a storage account already exists, when attempting to create an identically named storage account with a different type, there's an ambiguous message which makes it look like the CLI does not support an argument that it lists as valid:

```
$> az storage account create -n aliascommandtest -g TestGroup1 -l eastus --verbose --kind BlobStorage --access-tier Hot
Values for request parameters are invalid: kind.

$> az storage account list --query '[].name'
[
  "aliascommandtest"
]
```

This error message should be improved.

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
az --version:
azure-cli (2.0.29)
storage (2.0.27)
```

**Comment by williexu** [comment]
The storage service(and services in general) support idempotent creates, so the creation of an existing storage account is treated similarly to an update. 
The error message is because the kind of a storage account is immutable.
Closing this as there is not much we can do.
