### ISSUE TITLE
Some error messages use REST API arguments names for missing parameters

### ISSUE THREAD

**Issue by sptramer** [Azure/azure-cli#5898]
The storage commands use the REST API argument names to denote missing parameters, instead of the CLI's parameter options.

```
$> az storage account create -n aliascommandtest -g TestGroup1 -l eastus --verbose --kind BlobStorage

Account property accessTier is required for the request.
```

The correct parameter to display would be `--access-tier`. This may affect other arguments.

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
cli-core 2.0.29
storage 2.0.27
```

**Comment by tjprescott** [comment]
This is a general documentation issue that applies throughout the CLI and happens because that message is returned by the service.

**Comment by tjprescott** [comment]
We could improve our general error handler, using a mapping of rest API names to CLI names to do a scrub of error messages from the server. However, as a team we've already decided not to do this, recently closing a near-identical issue. For now, I will mark this help wanted in case a third-party would care to make this contribution. It would be welcomed.

**Comment by yonzhan** [comment]
add to S165.
