### ISSUE TITLE
az login command allow access using only user parameter

### ISSUE THREAD

**Issue by jcrphx03** [Azure/azure-cli#5911]
To reproduce the issue 
scenario  #1
_az login -u <your user password> 
password:  < just enter>
output:
It will display the list of subscriptions in your account.  

_scenario #2
If you enter a wrong user and "enter" in the password it will displayed  
_az login -uavocado@gmail.com
password:  < just enter>
Output:
...TypeError: 'NoneType' object is not subscriptable....

_Scenario #3
If you enter a wrong user and wrong  password it will displayed 
Output:
...."Logging in through command line is not supported. For cross-check, try 'az login' to authenticate through browser..."  

Note: Before to reproduce the issue I assured I signed out from my account in the portal. 

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by tjprescott** [comment]
Please fill out the information in Evnironment Summary when posting a new issue.

**Comment by yugangw-msft** [comment]
Scenario 1 and 3 are by design
I will fix the scenario 2 by throwing out a better error

**Comment by jcrphx03** [comment]
AZ CLI 2.0:

$ az --version
azure-cli (2.0.28)

acr (2.0.21)
acs (2.0.27)
advisor (0.1.2)
appservice (0.1.28)
backup (1.0.6)
batch (3.1.10)
batchai (0.1.5)
billing (0.1.7)
cdn (0.0.13)
cloud (2.0.12)
cognitiveservices (0.1.11)
command-modules-nspkg (2.0.1)
configure (2.0.14)
consumption (0.2.2)
container (0.1.19)
core (2.0.28)
cosmosdb (0.1.19)
dla (0.0.18)
dls (0.0.19)
eventgrid (0.1.10)
extension (0.0.9)
feedback (2.1.0)
find (0.2.8)
interactive (0.3.16)
iot (0.1.17)
keyvault (2.0.19)
lab (0.0.17)
monitor (0.1.2)
network (2.0.24)
nspkg (3.0.1)
profile (2.0.19)
rdbms (0.0.12)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.24)
role (2.0.20)
servicefabric (0.0.10)
sql (2.0.22)
storage (2.0.26)
vm (2.0.27)

Python location '/anaconda3/bin/python3.6'
Extensions directory '/Users/jrodriguez/.azure/cliextensions'

Python (Darwin) 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

Legal docs and information: aka.ms/AzureCliLegal

_ Install Method (Brew) 
_Running in Mac book pro laptop. OS version Sierra
