### ISSUE TITLE
unable to add access permission for AD web app registration

### ISSUE THREAD

**Issue by abhijith-pk** [Azure/azure-cli#5913]
I am trying to create a web app with az ad create command (https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest#az-ad-app-create).

 when I am adding --requiredResourceAccess parameter to the command as specified in the documentation ,I am getting "unrecognized arguments: --requiredResourceAccess" error.

full command :

> az ad app create --display-name HatakeApp --homepage http://www.testapp2.com --identifier-uris http://testapp2 --password testpassword --requiredResourceAccess @manifest.json

                    ```
 content of manifest.json :
                        [{
                            "resourceAppId": "00000002-0000-0000-c000-000000000000",
                            "resourceAccess": [
                                {
                                    "id": "a42657d6-7f20-40e3-b6f0-cee03008a62a",
                                    "type": "Scope"
                                }
                           ]
                        }]
```
I have tried with the --required-resource-accesses parameter as well 
(In the documentation --required-resource-accesses is used in syntax and 
--required-resource-access is used in sample command , I couldn't find the parameter
 in the command help)
Am I missing something basic here ? 
---

### Environment summary

ubuntu 16.04.3
install method apt-get

az --version output: 

azure-cli (2.0.29)

acr (2.0.22)
acs (2.0.28)
advisor (0.5.0)
appservice (0.1.29)
backup (1.0.7)
batch (3.1.11)
batchai (0.1.6)
billing (0.1.7)
cdn (0.0.13)
cloud (2.0.12)
cognitiveservices (0.1.11)
command-modules-nspkg (2.0.1)
configure (2.0.14)
consumption (0.2.2)
container (0.1.19)
core (2.0.29)
cosmosdb (0.1.19)
dla (0.0.18)
dls (0.0.19)
eventgrid (0.1.11)
eventhubs (0.1.0)
extension (0.0.10)
feedback (2.1.0)
find (0.2.8)
interactive (0.3.17)
iot (0.1.18)
keyvault (2.0.20)
lab (0.0.17)
monitor (0.1.3)
network (2.0.25)
nspkg (3.0.2)
profile (2.0.20)
rdbms (0.1.0)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.25)
role (2.0.20)
servicebus (0.1.0)
servicefabric (0.0.11)
sql (2.0.23)
storage (2.0.27)
vm (2.0.28)

Python location '/opt/az/bin/python3'
Extensions directory '/home/abhi/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Mar 10 2018, 01:18:09)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal

```
```

**Comment by yugangw-msft** [comment]
The document is a bit ahead of the public release which should get out tomorrow
