### ISSUE TITLE
az login token expiring in 45 minutes to a hour when use with terraform

### ISSUE THREAD

**Issue by rohrerb** [Azure/azure-cli#5922]
Running Azure Cli on a MAC and --version is (2.0.29)

Using Azure Cli for authentication with Terraform.  Once we login we are automatically logged out of cli between 45 minutes to a hour.  Documentation shows that the token should last for up to 14 days - https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest

Is there anyway to see what the token expiration is set to after executing az login?  I tried to use --debug but it didn't show anything useful.  What is the best way to debug this issue?

Thank you

**Comment by yugangw-msft** [comment]
Did you ever invoke "az login"? Please share details steps of how you configured terraform to work with CLI.

**Comment by yugangw-msft** [comment]
@rohrerb, to make it clear, if you have never ran "az login" or the `~/.azure/accessTokens.json` gets updated by terraform,  the likely consequence is the refresh token is not available or persisted. W/o that CLI will not be able to acquire a new token for you, hence it is by design that the original access token gets expired in 45 minute to a hour and CLI stops working.

**Comment by rohrerb** [comment]
az login is simple to use with terraform.  You run az login and start terraforming. ; )

https://www.terraform.io/docs/providers/azurerm/authenticating_via_azure_cli.html

**Comment by rohrerb** [comment]
I can confirm that terraform doesn't modify the jwt token.  

It does seem to be a error with terraform. 

Terraform throws the following error: 

Error: Error refreshing state: 1 error(s) occurred:

* provider.azurerm: No valid (unexpired) Azure CLI Auth Tokens found. Please run `az login`.

However, in the same bash window i can execute az account list or other cli commands with no error.  After executing the cli command I can then rerun the same terraform command and it works.
