### ISSUE TITLE
az vm create [...] --custom-data <filename> does not validate existence of filename

### ISSUE THREAD

**Issue by larryms** [Azure/azure-cli#5929]
When creating a vm and passing a cloud-init file via the --custom-data parameter, the cli does not validate if the file exists.  Instead, it just silently continues and does not print any error message.

e.g, running
`az vm create -g myrg --name myvm --image UbuntuLTS --custom-data thisfiledoesnotexist.txt`
creates the vm, no error message is presented, and obviously the cloud-init file is not run on the vm as it does not exist.

---
### Environment summary
cloud shell.   az --version : 
azure-cli (2.0.29)

**Comment by tjprescott** [comment]
Thanks for the report @larryms

**Comment by larryms** [comment]
looks like this may be cause by custom.py 
custom.py has the following snippet:
`if custom_data:
custom_data = read_content_if_is_file(custom_data)`

read_content_if_is_file() does not do any error checking as to if the file passed exists.

**Comment by yugangw-msft** [comment]
for this flag we support both a file name or plain file content, and we really have no reasonable way to tell you mean a file path or just file content since the configuration could be anything.
If you do want file path check, please just use "@<filepath>" and then CLI will try to open up the file and emit errors in invalid path, e.g.  `az vm create -g myrg --name myvm --image UbuntuLTS --custom-data @thisfiledoesnotexist.txt`
I am closing this issue, please re-activate it if you have different opinions

**Comment by larryms** [comment]
I think this issue should be re-opened because, as far as I can tell, no where is it documented that the --custom-data parameter supports both a file name or plain file content, nor is the "@" strong gesture documented (again, as far as I can tell.)

I looked both here https://docs.microsoft.com/en-us/azure/virtual-machines/linux/using-cloud-init and here https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create .  Both pages imply that only a file name is valid; neither mentions plain file content nor the "@" parameter.

So at a bare minimum, this behavior should be clearly documented.  But ideally, the cli should be more intelligent.  I still think it's bad behavior to have a parameter which can fail silently.

One suggestion might be to have the cli assume that the parameter passed to --custom-data is a filename, unless it begins with a hash (#), which would be an indicator that you were passing file content.  (Yes, I know it's the case that cloud init doesn't *require* a comment at the beginning, but you could make that a requirement of the cli and it wouldn't really hurt anything.)  This would also make it easy to additionally support urls in addition to file paths as well as file content.

**Comment by yugangw-msft** [comment]
@sptramer, can you please make sure we document the usages for `@` somewhere? This is a general thing across all CLI commands.
I also tag this with `feature` for content check on VM custom data. Honestly i don't know whether we have the bandwidth for this or not, but users can feel free vote up.

**Comment by sptramer** [comment]
@yugangw-msft This is a reference documentation issue except where CLI conceptual explicitly calls out to reading files. There's no natural or logical single location in conceptual to document command syntax of this style, especially since it seems some file-read operations do not take `@file`.

**Comment by adewaleo** [comment]
I have a few comments with respect to this issue:

- @larryms  The help text for ['vm create'](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create) does say:  
```
--custom-data
   Custom init script file or text (cloud-init, cloud-config, etc..).
 ```
So the help text does document that the argument for `--custom-data` is meant to be a file or the contents for the file. 

- @sptramer, @yugangw-msft, the CLI logs debug output if it fails to read a filename prefixed with `@`. Should this be updated to a more explicit and visible warning?

- @sptramer, the  use of `@` applies to every argument passed to every command. The CLI will always attempt to expand the file name into its file contents. If this fails, the CLI continues. I think we should document `@`'s syntax somewhere

- @all, I can look into making `read_content_if_is_file` or the validation for `--custom-data` more intelligent. For example, if an argument ends with a common file extension ('.json', '.txt', '.yaml'), contains slashes and does not contain a new line character, it is fair to assume it is a file name. What are your thoughts on this @yugangw-msft?

**Comment by yugangw-msft** [comment]
We don't have other customer voices for this. We will have a blog post talking about the usages of `@`. Considering we have help text calling out the correct usages.  I think what we have is good enough.

**Comment by DarkShadow1060** [comment]
I am not sure if it is the right thing or not but, could you let me know if we can provide a storage account url to --custom-data?

`az vmss create --resource-group rg-vmss-dev --name vmss-dev --image ubuntu2204 --custom-data https://XXXXXXXXXX.blob.core.windows.net/cloudinitfile/cloud-init.yaml --generate-ssh-keys    `
