### ISSUE TITLE
[BatchAI] Issues to resolve prior to GA

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#5933]
Applicable to PR #5923.

**cluster**

- [ ] needs `--ids` support for `delete`, `show`, `list-files`, `list-nodes`
- [ ] `create`: issues with non-standard behavior list extra resource group arguments, arguments that only support name or only support ID.
- [ ] <del>`resize` and `auto-scale` should be folded into a single `update` command which supports the generic update parameter.</del>

**usage**
- [x] Only has a single command. This should be hyphenated and upleveled to `az batchai show-usage` unless there will be other usage commands.

**job**
- [x] `wait` is not using the infrastructure's generic wait pattern. 
- [ ] `--ids` should be supported for a number of commands.
- [x] `list-files`: `output-directory-id` isn't clear and has a random short option (no short option is likely appropriate here).
- [ ] `terminate`: the verb `stop` has precedent in the CLI and should probably be used here
- [x] `stream-file`: has different naming/aliasing from `list-files`.  These two commands could go into a subcommand as `list` and `stream` respectively.

**file-servers**
- [ ] `--ids` should be supported

**Comment by AlexanderYukhanov** [comment]
- I think --ids is confusing and has no value for our customers.
- would suggest to remove --subnet from cluster and file-server creation to not have inconsistent behavior (names vs ids)
- cluster doesn't support generic patching - the only supported path is resizing and having auto-scale and resize is more natural for customers
- will change usage show to show-usage
- are there any appropriate generic pattern for job wait? customers want to be able to wait for the job to switch either into succeeded or failed state, I do not see other way to archive it but checking the execution state
- create requires json and there is no good way to avoid it - too many too complex parameters. Our customers seems to be ok with creating a json config file. The only request was is to provide json validation schema and we have it.
-  extra resource group is the resource group of file server, it's much simpler to provide nfs name and resource group than provide a resource id for our customers
- --output-directory-id has -d short option standing for "directory". "-d" is already used by customers and we don't want to break them
- 'list-files' and 'stream-file'. is it important enough to brake existing customers?
- file server doesn't support update.

**Comment by AlexanderYukhanov** [comment]
After discussion, we decided to break existing customers and merge list-files and stream-file

**Comment by tjprescott** [comment]
Since BatchAI is deprecated, I will close this issue.
