### ISSUE TITLE
az vmss update-instances * doesnt work

### ISSUE THREAD

**Issue by goodwill** [Azure/azure-cli#5941]
As title, you get error to tell you state instance-ids or * but indeed I put * in already

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0408c294-207a-2b72-7b93-e09121602b75
* Version Independent ID: 852cb67b-70c6-b811-3b0a-5d5b84b8a911
* Content: [az vmss](https://docs.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#az-vmss-update-instances)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machine-scale-sets**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
You may be running an outdated version of the CLI. Also, certain shells interpret a raw * (such as bash) so you may need to use `"*"`.
