### ISSUE TITLE
az ad sp create-for-rbac: value for --cert is "unrecognized arguments"

### ISSUE THREAD

**Issue by amandadebler** [Azure/azure-cli#5942]
In both --create-cert and use from keyvault mode, whatever value I put for --cert is an unrecognized argument:

az ad sp create-for-rbac --keyvault someVaultName --name "thisServicePrincipal" --cert someCertThatExists

az ad sp create-for-rbac --create-cert --keyvault someVaultName --name "thatServicePrincipal" --cert someCertToMake

If I leave off --cert, it throws a Python stack trace ending with "ValidationError: Parameter 'certificate_name' can not be None."
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build): yum

CLI version (`az --version`)
acr (2.0.22)
acs (2.0.30)
advisor (0.5.0)
appservice (0.1.30)
backup (1.1.0)
batch (3.1.11)
batchai (0.1.6)
billing (0.1.7)
cdn (0.0.13)
cloud (2.0.12)
cognitiveservices (0.1.11)
command-modules-nspkg (2.0.1)
configure (2.0.14)
consumption (0.2.2)
container (0.1.20)
core (2.0.30)
cosmosdb (0.1.19)
dla (0.0.18)
dls (0.0.20)
eventgrid (0.1.11)
eventhubs (0.1.1)
extension (0.0.11)
feedback (2.1.0)
find (0.2.8)
interactive (0.3.18)
iot (0.1.18)
keyvault (2.0.20)
lab (0.0.20)
monitor (0.1.4)
network (2.0.26)
nspkg (3.0.2)
profile (2.0.21)
rdbms (0.2.0)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.26)
role (2.0.21)
servicebus (0.1.1)
servicefabric (0.0.11)
sql (2.0.24)
storage (2.0.30)
vm (2.0.29)

OS version: Red Hat Enterprise Linux 7.4
Shell Type: bash-4.2

```
```

**Comment by yugangw-msft** [comment]
It was fixed yesterday through #5903, it was a fall out from knack conversion.
Suggest use [dev builds](https://github.com/Azure/azure-cli#docker) till it gets released on Apr 10
