### ISSUE TITLE
Missing 'user assignment' value from az ad sp create

### ISSUE THREAD

**Issue by pasup1rk** [Azure/azure-cli#5948]
Hi.

I am creating Service Principal using the `az ad sp create` command, and have run into an issue where I'm unable to change `user assignment required` value to `true` . It would be useful to have a one similar to powershell `-AppRoleAssignmentRequired` parameter to specify this. 

Thanks

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
$ az --version

azure-cli (2.0.22)

acr (2.0.16)
acs (2.0.21)
advisor (0.1.0)
appservice (0.1.21)
backup (1.0.3)
batch (3.1.7)
batchai (0.1.3)
billing (0.1.6)
cdn (0.0.10)
cloud (2.0.10)
cognitiveservices (0.1.9)
command-modules-nspkg (2.0.1)
configure (2.0.12)
consumption (0.2.0)
container (0.1.14)
core (2.0.22)
cosmosdb (0.1.15)
dla (0.0.15)
dls (0.0.18)
eventgrid (0.1.5)
extension (0.0.6)
feedback (2.0.6)
find (0.2.7)
interactive (0.3.11)
iot (0.1.14)
keyvault (2.0.14)
lab (0.0.13)
monitor (0.0.13)
network (2.0.18)
nspkg (3.0.1)
profile (2.0.15)
rdbms (0.0.9)
redis (0.2.10)
reservations (0.1.0)
resource (2.0.19)
role (2.0.15)
servicefabric (0.0.6)
sql (2.0.16)
storage (2.0.20)
vm (2.0.19)

Python location '/usr/local/bin/python3.6'
Extensions directory '/Users/rpasupuleti/.azure/cliextensions'

Python (Darwin) 3.6.3 (default, Oct  4 2017, 06:09:38) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]

Legal docs and information: aka.ms/AzureCliLegal
```

**Comment by yugangw-msft** [comment]
I will wire up a generic updater for this

**Comment by yugangw-msft** [comment]
This will have to wait, as it requires [api spec change](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/graphrbac/data-plane/stable/1.6/graphrbac.json)

**Comment by yugangw-msft** [comment]
Be more specific, that the spec must be updated to support "service principal patch/update" which is missing right now.

**Comment by yugangw-msft** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/5181 would  fix this, but we will see.
