### ISSUE TITLE
Error when creating VM with Plan Information

### ISSUE THREAD

**Issue by johanburati** [Azure/azure-cli#5949]
We are trying to recreate a Cloudera Linux VM from the Cloud Shell cli.
There was a plan associated with the original VM, but whatever we supply the plan or not we are getting contradictory error messages;
- "Creating a virtual machine from Marketplace image requires Plan information in the request"
- "This resource was created without a plan. A new plan cannot be associated with an update."

Could you advice on the proper command to recreate the VM from a managed disk copy ?
<hr>

- **"Creating a virtual machine from Marketplace image requires Plan information in the request"**

```
az vm create -g rg01 -n vm01 --attach-os-disk vm01_OsDisk_1_d65db0c7a026490199cf55cc0abf7c8c_copy --nics vm015 --os-type Linux
```

```
   Deployment failed. Correlation ID: 5cd2bd25-201e-4a73-9647-546372673970. {

  "status": "Failed",

  "error": {

    "code": "ResourceDeploymentFailure",

    "message": "The resource operation completed with terminal provisioning state 'Failed'.",

    "details": [

      {

        "code": "VMMarketplaceInvalidInput",

        "message": "Creating a virtual machine from Marketplace image requires Plan information in the request. OS disk name is 'vm01_OsDisk_1_d65db0c7a026490199cf55cc0abf7c8c_copy'."

      }

    ]

  }
```
<hr>

- **"This resource was created without a plan. A new plan cannot be associated with an update."**
```

az vm create -g rg01 -n vm01 --attach-os-disk vm01_OsDisk_1_d65db0c7a026490199cf55cc0abf7c8c_copy --nics vm015 --os-type Linux --plan-name 7_2 --plan-product cloudera-centos-os --plan-publisher cloudera
```

```
This resource was created without a plan. A new plan cannot be associated with an update.


```

**Comment by yugangw-msft** [comment]
@johanburati, to confirm, you did create the original vm using exactly the same vm name, same image and same plan info, right?:
           `-n vm01 -plan-name 7_2 --plan-product cloudera-centos-os --plan-publisher cloudera`

**Comment by johanburati** [comment]
hi @yugangw-msft, today I tried the same commands in my own subscrition and it worked and later on I tried again with the customer and this time we were able to recreate the VM, not sure why we go the errors the first time.
