### ISSUE TITLE
"Rebase" button/bot/something...

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#5955]
With increasing frequency, the issue crops up where PRs tend to fail on the CI's version check. Usually this manifests as nearly all modules complaining about their versions. People "merge" the latest changes from dev (because that's generally what the Git community recommends) and then the CI still fails for the same reason. At that point, the author says "I've done all I can," and reaches out to us to make things right.

The solution for this seems to always be for them to rebase their branch against the latest in dev, *not* to merge dev into their branch. If we could have a git bot that would do this, or a button that appears that would automatically do this, it would help, especially for help-only PRs where the author is likely not familiar with Git and may only be submitting changes through GitHub.

**Comment by tjprescott** [comment]
This is why we need this
https://github.com/Azure/azure-cli/pull/5877

**Comment by markjbrown** [comment]
If there was an upvote button on here I would click it.

This would be GREAT to have. This happens to me nearly every single time I submit a PR.

thanks.

**Comment by tjprescott** [comment]
This is why we need this...
https://github.com/Azure/azure-cli/pull/5992

**Comment by derekbekoe** [comment]
Rebasing essentially re-writes a part of the Git history for a particular branch.
Therefore, rebasing someone elses branch 'on behalf' of them could have unintended consequences if their not aware as it's essentially a force-push into their fork.

We *could* merge for them which GitHub already supports but that's different from rebasing - https://blog.github.com/2015-09-03-protected-branches-and-required-status-checks/.

Super long discussion here https://github.com/isaacs/github/issues/88

**Comment by tjprescott** [comment]
Good point.  But if it was a button, we could ask them to click it 😅
