### ISSUE TITLE
Can't use container exec on container groups with multiple containers

### ISSUE THREAD

**Issue by markheath** [Azure/azure-cli#5962]
If you attempt to use `az container exec` in 2.0.30 on a container group with multiple containers, you get an error saying `--container-name` is required even if you supply it:

```
az container exec -g $resourceGroup -n $containerGroupName --container-name "front-end" `
    --exec-command "/bin/bash"
--container-name required when container group has more than one container.
```

Looks like the logic in this `if` statement doesn't account for the situation when there are multiple containers and the container name has been supplied:
https://github.com/Azure/azure-cli/blob/5f1a9c621bfc8b15b17f53399e37e43a8c55aa4c/src/command_modules/azure-cli-container/azure/cli/command_modules/container/custom.py#L261

**Comment by tjprescott** [comment]
This was fixed in PR #5927 and will be in the next release.
