### ISSUE TITLE
Could we get 2.x releases older than 2.0.24 on Docker Hub

### ISSUE THREAD

**Issue by seanknox** [Azure/azure-cli#5964]
Due to https://github.com/Azure/azure-cli/issues/5959 I was trying older versions of azure-cli, however 2.0.24 is the oldest 2.x release that available on Docker Hub. It would be great if the other 2.x. releases could be published as well.

**Comment by derekbekoe** [comment]
@seanknox See https://hub.docker.com/r/azuresdk/azure-cli-python/tags/
It was around 2.0.24 that we moved from `azuresdk/azure-cli-python` to `microsoft/azure-cli` for the versioned released.

**Comment by seanknox** [comment]
Thanks @derekbekoe!
