### ISSUE TITLE
add back "az aks get-versions -n -g" functionality

### ISSUE THREAD

**Issue by knee-berts** [Azure/azure-cli#5967]
### Environment summary
`CLI Version 2.0.30`
`Installed with brew`
`macOS`
`Shell: bash`

---

`az aks get-versions` provides a much needed way to list all the kubernetes versions available to AKS in a region but no longer provides a way to see upgrades available to a specific instance of AKS. In addition to getting versions by region, bring back checking what versions are available to an already existing instance of AKS.

```Command
    az aks get-versions: Get the versions available for creating a managed Kubernetes cluster.

Arguments
    --location -l [Required]: Location. You can configure the default location using `az configure
                              --defaults location=<location>`.

Global Arguments
    --debug                 : Increase logging verbosity to show all debug logs.
    --help -h               : Show this help message and exit.
    --output -o             : Output format.  Allowed values: json, jsonc, table, tsv.  Default:
                              table.
    --query                 : JMESPath query string. See http://jmespath.org/ for more information
                              and examples.
    --verbose               : Increase logging verbosity. Use --debug for full debug logs.```

**Comment by mboersma** [comment]
@knee-berts the old behavior lives on as `az aks get-upgrades -n -g`, and `az aks get-versions` now returns only those versions available for provisioning in a region.

Sorry for the confusion--we knew this was a breaking change and we added some deprecation info for a couple of `az` versions there to hopefully make this clearer. The old command was essentially misnamed, since it only returned upgrade versions.

**Comment by knee-berts** [comment]
Closing as the requested functionality exists using:
```az aks get-upgrades -h

Command
    az aks get-upgrades: Get the upgrade versions available for a managed Kubernetes cluster.

Arguments
    --name -n           [Required]: Name of the managed cluster.
    --resource-group -g [Required]: Name of resource group. You can configure the default group
                                    using `az configure --defaults group=<name>`.
