### ISSUE TITLE
Implement Preview strategies for commands/command groups/parameters

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#5969]
We currently have a mechanism to show that extensions are in preview, but we have no such thing for specific CLI commands, command groups, or parameters.  Even within a GA module, certain parameters may be added in preview, for example `--ddos-protection` for `vnet create`. It would be good to standardize the experience for these: perhaps issue a warning if a preview command or parameter is used so that users are warned that these things may break and thus to avoid using them in scripts. Displaying this warning or not could be a configurable setting.

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
azure-cli (2.0.30)
```

**Comment by dorfire** [comment]
Looks like the warning appears twice:
`
$ az acr pack build https://github.com/johnpapa/node-hello.git -t node-hello:{{.Run.ID}}
This command group is in preview. It may be changed/removed in a future release.
Command group 'acr pack' is in preview. It may be changed/removed in a future release.
[...]
`

**Comment by tjprescott** [comment]
Reopening to investigate the double warning.

**Comment by tjprescott** [comment]
This has been implemented for CLI 2.0.67.
