### ISSUE TITLE
VMSS create: switch default vm size from standard_d1_v2 to standard_ds1_v2

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#5970]
//CC: @gatneil  @mayurid @twitchax 
Related with https://github.com/Azure/azure-cli/issues/2030

**Comment by yugangw-msft** [comment]
I will find a time to switch this default

**Comment by gatneil** [comment]
I agree. We have DSv3 as well in a lot of regions, but it looks like it still needs to end up in a few more regions, so DSv2 is probably still the best default

https://azure.microsoft.com/en-us/global-infrastructure/services/

**Comment by twitchax** [comment]
@yugangw-msft, have we gotten any update from Portal on this?

**Comment by twitchax** [comment]
@gatneil, any update on when this Portal fix is happening?
