### ISSUE TITLE
Service Principal: ensure generated password contain both lower and upper case characters

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#5973]
The short lived security enforcement from AAD graph service got rolled back this morning, but to avoid errors like #5959  from happening again, we can improve "uuid.uuid4" a bit to have stronger password
2 command modules to update
    1. azure-cli-cole
    2. azure-cli-acs

@mboersma, I will take care of both.

**Comment by mboersma** [comment]
Thanks @yugangw-msft, please let me know if I can help.

**Comment by tjprescott** [comment]
Closing per @yugangw-msft

**Comment by yugangw-msft** [comment]
For context, the auto-gen'd guids by CLI commands are accepted as a strong password per confirmations from AAD graph team, and also CLI is retiring the `--password` from the command of `az ad sp create-for-rbac`, so we are good.
