### ISSUE TITLE
az vm update --set/--remove does not work?

### ISSUE THREAD

**Issue by kjhosein** [Azure/azure-cli#5976]
### Environment summary

Install Method: Homebrew (MacOS) 
CLI version: azure-cli (2.0.30), Python (Darwin) 3.6.5
OS version: MacOS Sierra 10.12.6
Shell: Bash 

### Description
I am attempting to remove and set tags on a VM, but am getting the error unrecognized arguments.
For example, removing a tag:

`az vm update –-resource-group MyResourceGroup –-name MyTestVM --remove tags.myNewTagName1`

and setting a tag:

`az vm update --resource-group MyResourceGroup --name MyTestVM –-set tags.myNewTagName1=myNewTagValue1`

Both examples are from [the documentation](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/tag). 

Note that this also fails in the portal's Cloud Shell.

Can anyone else confirm this and/or have it work for them? I haven't found any bugs listed in [this issues db](https://github.com/Azure/azure-cli/issues). Thanks!

**Comment by johanburati** [comment]
I confirm it is working. 

When I copied/pasted your command line, I noticed the first dash of the `–-set` option was a different character that's why you are getting an error.

```
$ az vm update -g rg -n vm --set tags.myNewTagName1=myNewTagValue1
$ az vm show -g rg -n vm --query tags
{
  "myNewTagName1": "myNewTagValue1"
}
$ az vm update -g rg -n vm --remove tags.myNewTagName1
$ az vm show -g rg -n vm --query tags
{}
```

**Comment by kjhosein** [comment]
Good catch, thanks! 

And I know exactly how that happened and why I didn't think to inspect it closer - I copied it out of the documentation.
