### ISSUE TITLE
Azure 2.0 CLI Output is inferior to 1.0 Output

### ISSUE THREAD

**Issue by benofben** [Azure/azure-cli#5978]
Hi, A number of times I've tried to move the Couchbase stuff to the 2.0 CLI.  I just tried again.  It still doesn't print the outputs like the 1.0 CLI did.  Is there any way you guys could add that?

![image](https://user-images.githubusercontent.com/8282917/38177069-416fceb6-35af-11e8-86d2-14ff5942c4ff.png)

The lack of this seriously compromises ease of use.  Here's the output in our template that's apparently not accessible.

https://github.com/couchbase-partners/azure-resource-manager-couchbase/blob/master/simple/mainTemplate.json#L401-L410

**Comment by benofben** [comment]
Here's what the output looks like in the 1.0

Note that it's possible to tell what is the output from the resource group command and what is the output from the deployment create.  Also note that the deployment outputs are printed.  All this seems to have been lost in the 2.0.

https://youtu.be/c7G-o36q8tA?t=4m47s

**Comment by benofben** [comment]
Here's the script.  Look in the history for the old 1.0 command that had better output.  https://github.com/couchbase-partners/azure-resource-manager-couchbase/blob/master/simple/deploy.sh

**Comment by tjprescott** [comment]
In general, the output is CLI 2.0 is deliberate, seeking to avoid the excessively verbose output from CLI 1.0.

Here is example output for `vm create ... --verbose`:
```
(env) C:\Users\trpresco\Documents\github\azure-cli>az vm create -g tjp-rg -n vm1 --verbose --image UbuntuLTS
Use existing SSH public key file: C:\Users\trpresco\.ssh\id_rsa.pub
Accepted: vm1VNET (Microsoft.Network/virtualNetworks)
Accepted: vm1PublicIP (Microsoft.Network/publicIPAddresses)
Accepted: vm1NSG (Microsoft.Network/networkSecurityGroups)
Accepted: vm_deploy_tQ7gdjvCKdxf1ZhdwCsDvnspbeUxzD2w (Microsoft.Resources/deployments)
Succeeded: vm1NSG (Microsoft.Network/networkSecurityGroups)
Succeeded: vm1PublicIP (Microsoft.Network/publicIPAddresses)
Accepted: vm1VNET (Microsoft.Network/virtualNetworks)
Succeeded: vm1VMNic (Microsoft.Network/networkInterfaces)
Succeeded: vm1VNET (Microsoft.Network/virtualNetworks)
Accepted: vm1 (Microsoft.Compute/virtualMachines)
Accepted: vm1 (Microsoft.Compute/virtualMachines)
{
  "fqdns": "",
  "id": "/subscriptions/{sub}/resourceGroups/tjp-rg/providers/Microsoft.Compute/virtualMachines/vm1",
  "location": "westus",
  "macAddress": "00-0D-3A-36-A9-49",
  "powerState": "VM running",
  "privateIpAddress": "10.0.0.4",
  "publicIpAddress": "13.91.89.57",
  "resourceGroup": "tjp-rg",
  "zones": ""
}
```

Is this the kind of info you are looking for, but for the `group deployment create` command?

**Comment by benofben** [comment]
Sort of.  The main thing missing is that in the CLI 1.0 it prints the outputs of an ARM deployment.  In the case of the Couchbase templates we put the database endpoint in that output to make it easy for a user to connect to the database.  In the 2.0 that's gone missing.  The result is a user has to go hunting around either a JSON blob or the portal to find the output rather than it just being presented to them.  This is a step backward.

**Comment by yugangw-msft** [comment]
It is case by case for table output, that individual command should author table transformation to output better information instead of relying on the default CLI transformer which ignores all nested complex property objects. 
For this issue, I suggest we convert it to an issue specifically for  `group deployment create` and address it.

**Comment by tjprescott** [comment]
Intermediate stages of ARM deployment should be displayed if you use `--verbose` output. If this is not the case, please reopen.
