### ISSUE TITLE
 some VM sizes got by `az vm list-skus --location <locationname>` are not available on the Azure portal 

### ISSUE THREAD

**Issue by leifei87** [Azure/azure-cli#5979]
For example:  Standard_H16r in West Europe, from the command output, it's Available:
 {
    "additionalProperties": {},
    "apiVersions": null,
    "capabilities": [
      {
        "additionalProperties": {},
        "name": "LowPriorityCapable",
        "value": "True"
      }
    ],
    "capacity": null,
    "costs": null,
    "family": null,
    "kind": null,
    "locationInfo": [
      { 
        "additionalProperties": {},
        "location": "westeurope",
        "zones": [
          "2",
          "1"
        ]
      }
    ],
    "locations": [
      "westeurope"
    ],
    "name": "Standard_H16r",
    "resourceType": "virtualMachines",
    "restrictions": [],
    "size": "H16r",
    "tier": "Standard"
  }
But in Azure portal , the size is in 'Not Available' list.

**Comment by yugangw-msft** [comment]
The output `vm list-sizes` is not accurate, as it does not take into account any restrictions placed on your subscription by CAS layer due to capacity or offer type. Hence please use `az vm list-skus` which is also what Portal does.
I am closing this issue, as there is nothing much client tools can do

**Comment by leifei87** [comment]
Hi yugangw-msft,  the output is from az vm list-skus,  not az vm list-sizes，please check!

**Comment by yugangw-msft** [comment]
@leifei87 , are you able to create the vm with this size through cli?

**Comment by leifei87** [comment]
No, please see the following errors, actually the core in the location is very enough, I think the mean of the error is the core is exceeding for Standard H Family vCPUs:
x-ms-routing-request-id: WESTEUROPE:20180403T045948Z:fc6a4cbd-2cb8-4184-a9c5-c430885384ba
Error message: {
  "error": {
    "code": "OperationNotAllowed",
    "message": "Operation results in exceeding quota limits of Core. Maximum allowed: 8, Current in use: 0, Additional requested: 16. Please read more about quota increase at http://aka.ms/corequotaincrease."
  }
}

**Comment by yugangw-msft** [comment]
This error is expected. I believe there is a separated quota for `H family`.  I guess portal might cross check the quota and hide images which could be over the limit?  
So far, I don't think CLI has any bugs here.  If you do need to create such VMs, you will have to contact customer service to upper the quota.

**Comment by leifei87** [comment]
I see ,thanks

**Comment by yugangw-msft** [comment]
Closing again
