### ISSUE TITLE
Data from such a repository can't be authenticated and is therefore potentially dangerous to use.

### ISSUE THREAD

**Issue by saanpritom** [Azure/azure-cli#5980]
Linux Mint Sylvia shows these problems.

W: The repository 'https://packages.microsoft.com/repos/azure-cli sylvia Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://packages.microsoft.com/repos/azure-cli/dists/sylvia/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by derekbekoe** [comment]
You must choose from this list: Ubuntu trusty, xenial, and artful
Debian wheezy, jessie, and stretch.
There is no specific package for Sylvia.
See https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest

**Comment by mandarsudame** [comment]
I get the same error for artful:
W: https://packages.microsoft.com/repos/azure-cli/dists/artful/InRelease: No system certificates available. Try installing ca-certificates.
W: https://packages.microsoft.com/repos/azure-cli/dists/artful/Release: No system certificates available. Try installing ca-certificates.
E: The repository 'https://packages.microsoft.com/repos/azure-cli artful Release' does not have a Release file.

Running this inside docker container. Any idea?
