### ISSUE TITLE
Certification test tool for Azure certified

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#5981]
Hello, all!

Are there any plans to have the subject (https://docs.microsoft.com/en-us/azure/marketplace-publishing/marketplace-publishing-vm-image-creation-prerequisites) available in CLI interface?

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```
azure-cli (2.0.30), Microsoft Windows [Version 10.0.17110.1000], Bash on Windows

**Comment by tjprescott** [comment]
There are no current plans to implement this.

**Comment by yonzhan** [comment]
issue triaged.
