### ISSUE TITLE
az dls fs list should print like ls

### ISSUE THREAD

**Issue by rsmith54** [Azure/azure-cli#5986]
It should print like ls from bash.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e0e56a4-5c1a-01c8-6ed5-2eea86010282
* Version Independent ID: 4e4db177-1a4e-b2a9-0858-4c13cd0140fe
* Content: [az dls](https://docs.microsoft.com/en-us/cli/azure/dls?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-dls/azure/cli/command_modules/dls/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-dls/azure/cli/command_modules/dls/_help.py)
* Service: **datalake-store**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by rsmith54** [comment]
I realized that I can use the ```-o table``` flag to get a more bash-like output.  This should likely be the default.

**Comment by tjprescott** [comment]
@rsmith54 currently there aren't per-command output formats. You can only configure your default output format using the `az configure` command. 

If you are interested in per-command default formats, please comment here:
https://github.com/Azure/azure-cli/issues/2471

**Comment by rsmith54** [comment]
I get a different output using the following two commands:

Returns as JSON
``` az dls fs list --account account_name --path /path/to/file```

Returns as table
``` az dls fs list --account account_name --path /path/to/file -o table```

so I'm a bit confused.  The ```az configure``` command to default to table/tsv is very useful though, so thanks for your comment!

**Comment by tjprescott** [comment]
The default output format for the CLI is JSON, unless you change it.

**Comment by akharit** [comment]
@tjprescott I am not sure what change is required here. Can you elaborate? 

The conversation in the thread seems to suggest that everything is working as expected.

**Comment by tjprescott** [comment]
Yes, I think this can be closed.
