### ISSUE TITLE
az vm create fails with cert error 

### ISSUE THREAD

**Issue by JoelHazelton** [Azure/azure-cli#5990]
Command: 
az vm create --resource-group "MyTestRG" --name "MyTestVM" --image "Win2016Datacenter" --admin-username "MyTestAdmin" --size "Basic_A0"

Error message: 
az vm create: error: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json (Caused by SSLError(SSLError("bad handshake: 
Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

This command works fine with CLI in cloudshell. 

---

### Environment summary

Shell Type: PowerShell 
OS: Windows 10
Install Method: MSI
CLI version:
azure-cli (2.0.30)

acr (2.0.22)
acs (2.0.30)
advisor (0.5.0)
appservice (0.1.30)
backup (1.1.0)
batch (3.1.11)
batchai (0.1.6)
billing (0.1.7)
cdn (0.0.13)
cloud (2.0.12)
cognitiveservices (0.1.11)
command-modules-nspkg (2.0.1)
configure (2.0.14)
consumption (0.2.2)
container (0.1.20)
core (2.0.30)
cosmosdb (0.1.19)
dla (0.0.18)
dls (0.0.20)
eventgrid (0.1.11)
eventhubs (0.1.1)
extension (0.0.11)
feedback (2.1.0)
find (0.2.8)
interactive (0.3.18)
iot (0.1.18)
keyvault (2.0.20)
lab (0.0.20)
monitor (0.1.4)
network (2.0.26)
nspkg (3.0.2)
profile (2.0.21)
rdbms (0.2.0)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.26)
role (2.0.21)
servicebus (0.1.1)
servicefabric (0.0.11)
sql (2.0.24)
storage (2.0.30)
vm (2.0.29)

```
```

**Comment by derekbekoe** [comment]
@JoelHazelton Is your Windows machine behind a proxy?

**Comment by JoelHazelton** [comment]
@derekbekoe  Yes, it is. And checking the same command on my home network (off the corporate network), I'm not getting that particular error anymore. 

However, it still is not working on my home network. Now, it hangs indefinitely after "new nic will be created". It's been sitting at that step for about 2 hours now. I attached the debug from PowerShell. 
[NewNICHangup.txt](https://github.com/Azure/azure-cli/files/1872145/NewNICHangup.txt)

**Comment by yugangw-msft** [comment]
So your PowerShell window just goes silent with nothing new coming up? Did you select anything using the cursor? if yes, could you dismiss that? It is possible the text selection could block the command window's output

**Comment by JoelHazelton** [comment]
@yugangw-msft Yes, PowerShell went silent with nothing new coming up. No, I had nothing selected with the cursor.

**Comment by yugangw-msft** [comment]
> PowerShell went silent with nothing new coming up. No, I had nothing selected with the cursor.

I have run out of ideas of how it would happen  under `--debug` mode, the CLI command goes completely silently(no output) and at the same time the portal shows no activities   

Can you try again with `--debug`? and maybe in a regular command window?

**Comment by JoelHazelton** [comment]
@yugangw-msft: I tried this with --debug in a regular CMD window, and it worked fine. I also noticed that as soon as it passed the  "new NIC will be created" line where it was hanging up in PowerShell, CMD prompted me to input a value for an admin password. So, I returned to PowerShell and ran the same command, except I used the --admin-password parameter this time, rather than waiting for PS to prompt me for a password. When I re-ran the command with the --admin-password parameter, everything went through successfully.

**Comment by yugangw-msft** [comment]
So looks like prompting for a password might not work well in PowerShell, let me try to reproduce and get back to you

**Comment by yugangw-msft** [comment]
@JoelHazelton, there is nothing wrong here with the password prompt, rather the vm size of `Basic_A0` chosen here is a bit low end for windows 2016. I tried it and after more than half a hour the command went through.
Please reactivate the issue you see new problems.

![image](https://user-images.githubusercontent.com/6014209/38441188-ba8b24d4-3998-11e8-893a-1159268c8b5e.png)
