### ISSUE TITLE
regression on az sp create-for-rbac w/keyvault and selfsigned cert

### ISSUE THREAD

**Issue by awysza** [Azure/azure-cli#5995]
@derekbekoe 

According to documentation
https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest
and based on past commands that executed correctly, this command should work and result in creating service principal with a name spt222 and a self signed certificate with a name sptest111cert in a keyvault a2-kv.

Cli version 2.0.30, used in Portal’ CloudShell this command results in an error:
**az ad sp create-for-rbac -n spt222 --keyvault a2-kv --cert sptest111cert --create-cert**

 error: unrecognized arguments: sptest111cert

However, when executing on a local cmd window (Windows Laptop), it works ok and results in intended results.
Our documentation hasn’t changed, as well as examples delivered in az ad sp create-for-rbac –help.
Hence looks like a regress

The main difference between the two environments is that 
•	**CloudShell uses az –version: 2.0.30 – the command doesn’t work**
o	Keyvault: 2.0.20
•	On local laptop,  **cli version: 2.0.26 – the command works**
o	KeyVault: 2.0.17

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by yugangw-msft** [comment]
This has been fixed through #5903. You will need to wait for the upcoming release or try out docker image
