### ISSUE TITLE
The output of az --version is too long

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#5999]
```
az -v | wc -l
     57
```

In most situation, you have to scroll back the terminal to see the actual version of the CLI. And the output size will keep expanding as more modules are added. Should we consider a shorter version of this command?

**Comment by tjprescott** [comment]
Alternatively we could just put the overall CLI version at the end.

**Comment by troydai** [comment]
We can do that. We can also print modules' versions in 2 or 3 columns.

**Comment by derekbekoe** [comment]
FYI changing the format of `az --version` would directly affect this
https://github.com/Microsoft/vscode-azurecli/blob/7ceef34c03dd998ea3bab838eeb36e68a6fe7794/src/azService.ts#L123-L130

**Comment by yugangw-msft** [comment]
With the latest status text which has the up to date information at the end, I suggest we keep what we have
