### ISSUE TITLE
az network vnet-gateway create/update fails with 404

### ISSUE THREAD

**Issue by ossark** [Azure/azure-cli#6001]
---

### Environment summary

**Install Method**
pip
 
**CLI version** 
$ az --version
azure-cli (2.0.28)

acr (2.0.21)
acs (2.0.27)
advisor (0.1.2)
appservice (0.1.28)
backup (1.0.6)
batch (3.1.10)
batchai (0.1.5)
billing (0.1.7)
cdn (0.0.13)
cloud (2.0.12)
cognitiveservices (0.1.11)
command-modules-nspkg (2.0.1)
configure (2.0.14)
consumption (0.2.2)
container (0.1.19)
core (2.0.28)
cosmosdb (0.1.19)
dla (0.0.18)
dls (0.0.19)
eventgrid (0.1.10)
extension (0.0.9)
feedback (2.1.0)
find (0.2.8)
interactive (0.3.16)
iot (0.1.17)
keyvault (2.0.19)
lab (0.0.17)
monitor (0.1.2)
network (2.0.24)
nspkg (3.0.1)
profile (2.0.19)
rdbms (0.0.12)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.24)
role (2.0.20)
servicefabric (0.0.10)
sql (2.0.22)
storage (2.0.26)
vm (2.0.27)

Python location '/usr/bin/python'
Extensions directory '/Users/johndoe/.azure/cliextensions'

Python (Darwin) 2.7.10 (default, Jul 15 2017, 17:16:57) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]

Legal docs and information: aka.ms/AzureCliLegal

**OS version** 
$ uname -a
Darwin hostname.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

**Shell Type**
bash

**Description**
An update  (or create after it already exists) yields a 404. Possibly due to the operation being an LRO (See #3330), please confirm or deny this, it is only speculation. Needless to say, update and create does not behave as expected and throws wrongful errors.
```
$ az network vnet-gateway update -g PROD -n PROD-vpngateway --sku VpnGw1
Deployment failed. Correlation ID: 0118d7a2-04b8-436e-88a4-27c9ec058f4f. Operation failed with status: 'Not Found'. Details: 404 Client Error: Not Found for url: https://management.azure.com/subscriptions/<redacted>/providers/Microsoft.Network/locations/westeurope/operations/75fb64d6-f901-4ec3-b02a-70c6f9078aa5?api-version=2017-11-01
```

**Comment by tjprescott** [comment]
Confirmed this. As far as I can tell, this only occurs when you do a create/update where nothing has changed. If you change something, the operation does not throw an error.

**Comment by tjprescott** [comment]
@lmazuel it seems that when you send the PUT, the service either returns the information to create a poller or, if nothing changed, the unchanged object. These operations are identified as failures in the CLI but not on the portal.  Is this an msrest issue?

**Comment by lmazuel** [comment]
@tjprescott Would you be able to send me (or post here) a --debug view of the error?

**Comment by tjprescott** [comment]
I'll send you one.  It's pretty reproducible that it fails if the object is unchanged and doesn't fail if the object was changed.

**Comment by tjprescott** [comment]
Can no longer reproduce. Believe the underlying service has been fixed. Closing.
