### ISSUE TITLE
Telemetry no longer includes exception stacktraces

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#6003]
It seems telemetry no longer includes the exception stacktraces and messages (for all commands, not just extensions)

**Comment by yonzhan** [comment]
@fengzhou-msft  add to S162.

**Comment by fengzhou-msft** [comment]
@derekbekoe I did a [query](https://dataexplorer.azure.com/clusters/ddazureclients/databases/AzureCli?query=H4sIAAAAAAAAA6XSsU7DMBAG4L1PcXQJLFbFngEhkLqhkg0xHPZRrDpxOF+apurD49iVaEBCivBi2br/u5PlDfYPe2ok3B3vnV2cgA5CjQHt6xrjXoL4IGyb7fUT+5ZYLIWXQvtGYqUy9I6dE4XHjkk7qxj7c7R4vbngnI1NNvTZUZD1fDbnOeft1E6l1dDSbDUdJSYnXmxkZfgLZArEezLKoGDtDTmVQ7+s8eI5ATOsPOUYzfVRBPg2awoBt3OGyyAdNLVifaPOwg83COpdxaj/QydERiTpecUe/QcxTZ62hOJxDBeAF//tqoTlMtYHzwJvA6TPWdk4cezYgqGgFyfBHcHtavUFIi3EKL0CAAA=) in kusto and looks like the message and stacktrace for exception is back. Can you confirm from the result of the [link](https://dataexplorer.azure.com/clusters/ddazureclients/databases/AzureCli?query=H4sIAAAAAAAAA6XSsU7DMBAG4L1PcXQJLFbFngEhkLqhkg0xHPZRrDpxOF+apurD49iVaEBCivBi2br/u5PlDfYPe2ok3B3vnV2cgA5CjQHt6xrjXoL4IGyb7fUT+5ZYLIWXQvtGYqUy9I6dE4XHjkk7qxj7c7R4vbngnI1NNvTZUZD1fDbnOeft1E6l1dDSbDUdJSYnXmxkZfgLZArEezLKoGDtDTmVQ7+s8eI5ATOsPOUYzfVRBPg2awoBt3OGyyAdNLVifaPOwg83COpdxaj/QydERiTpecUe/QcxTZ62hOJxDBeAF//tqoTlMtYHzwJvA6TPWdk4cezYgqGgFyfBHcHtavUFIi3EKL0CAAA=) that this issue has been fixed?

**Comment by derekbekoe** [comment]
@fengzhou-msft The issue was initially created a couple years ago so if things look good in telemetry, I'm happy to have the issue closed.
