### ISSUE TITLE
Extensions should be able to extend telemetry to send to their own AI accounts

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#6004]

**Comment by yonzhan** [comment]
@fengzhou-msft add to S162.

**Comment by yungezz** [comment]
hi @derekbekoe could you pls share the context of the requirement? sending telemetry to user's own AI accounts will have security/GDPR concern.

**Comment by derekbekoe** [comment]
We had asks from owners of Azure CLI extensions that they wanted to be able to configure their extensions to send their own telemetry to their own App Insights accounts.

This would be similar to support that's available to VS Code extension authors - https://github.com/microsoft/vscode-extension-telemetry.

Since this issue was created a long time ago, if no further requests have been received, seems the issue can be closed.

**Comment by fengzhou-msft** [comment]
Close as we didn't receive further requests. If anyone has such request, feel free to reopen this issue.
