### ISSUE TITLE
AAD AdministratorTest won't re-record

### ISSUE THREAD

**Issue by payiAzure** [Azure/azure-cli#6011]
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
CLI version 2.0.24
OS: Windows
Install Method: pip install
```
The AAD administrator Test won't record. Have contacted SQL AAD team to take a look.
     azure-cli-sql/test_sql_commands.py
        Test Class: AzureActiveDirectoryAdministratorScenarioTest
        Test Method: test_aad_admin

     Issue: The ServerAzureADAdministratorOperations does not support deserializing response from xml now.
        Error Log.
         File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/azure/mgmt/sql/operations/server_azure_ad_administrators_operations.py", line 247, in delete
    **operation_config
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/azure/mgmt/sql/operations/server_azure_ad_administrators_operations.py", line 212, in _delete_initial
    deserialized = self._deserialize('ServerAzureADAdministrator', response)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/msrest/serialization.py", line 998, in __call__
    data = self._unpack_content(response_data, content_type)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/msrest/serialization.py", line 1114, in _unpack_content
    raise DeserializationError("Do not support XML right now")
msrest.exceptions.DeserializationError: Do not support XML right now

-------------------- >> begin captured logging << --------------------
azure.cli.testsdk: INFO: Command "az group create --location westus --name clitest.rg000001 --tag product=azurecli cause=automation date=2018-04-04T19:20:41Z" => 0. 
azure.cli.testsdk: INFO: Command "az sql server create -l westus -g clitest.rg000001 -n clitestserver000002 -u admin123 -p SecretPassword123" => 0. 
azure.cli.testsdk: INFO: Command "sql server ad-admin create -s clitestserver000002 -g clitest.rg000001 -i 5e90ef3b-9b42-4777-819b-25c36961ea4d -u DSEngAll" => 0. 
azure.cli.testsdk: INFO: Command "sql server ad-admin list -s clitestserver000002 -g clitest.rg000001" => 0. 
azure.cli.testsdk: INFO: Command "sql server ad-admin update -s clitestserver000002 -g clitest.rg000001 -u TestUser -i e4d43337-d52c-4a0c-b581-09055e0359a0" => 0. 

azure.cli.testsdk: INFO: Command "az group delete --name clitest.rg000001 --yes --no-wait" => 0. 
--------------------- >> end captured logging << ---------------------

**Comment by amolagar5** [comment]
I think this is not going to work right now as we are not using Web API infrastructure. try new 2018-06-01-preview version..

**Comment by jeroenterheerdt** [comment]
@payiAzure - please respond by end of this week or we will proceed to close this issue.

**Comment by payiAzure** [comment]
> @payiAzure - please respond by end of this week or we will proceed to close this issue.

please go ahead to close it.

**Comment by jeroenterheerdt** [comment]
thanks!

**Comment by amolagar5** [comment]
I have fixed the test in latest code , its working now.
