### ISSUE TITLE
az login timeout?

### ISSUE THREAD

**Issue by jonbgallant** [Azure/azure-cli#6017]
I'm writing a script that needs to handle az login expiration.  To test it, I have to be able to tell az login to expire after a certain amount of time.  I don't want to az logout. I want the az to be cached, just expired.

Is there a way to do that or hack something to mimic that behavior?

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by yugangw-msft** [comment]
For both user accounts or service principals, the expiration should be rare. It is 3+months for user accounts. For service principals, you can configure the cred validation period as long as you prefer. 

I wonder what scenario would make you to handle that, maybe you can share a bit details, like what account type and problems you are dealing with?

**Comment by jonbgallant** [comment]
Thanks for the response. My script will need to handle that expired state  For example, user logs in 'az login' and then 3 months later tries to run the script.  I want to detect that expiration and handle it in my script, I also want to handle password change.

Right now I get something like this:
```
Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADTS50173: The provided grant has expired due to it being revoked. The user might have changed or reset their password. The grant was issued on '2018-01-27T14:24:55.8600000Z' and the TokensValidFrom date for this user is '2018-04-03T23:19:32.0000000Z'\r\nTrace ID: 5f0c1370-56ff-43fb-9488-8eadaf80c00\r\nCorrelation ID: e696ce28-8d7a-460f-98db-3cc15adfe6e\r\nTimestamp: 2018-04-05 23:51:51Z","error_codes":[50173],"timestamp":"2018-04-05 23:51:51Z","trace_id":"5f0c1370-56ff-43fb-9488-8eaddaf80c00","correlation_id":"e696ce28-8d7a-460f-8db-3cc151adfe6e"}
```

In this case it is because the pwd changed - but I get a similar error when the login has timed out.

In order to test this, I would like to do something like 'az login --timeout 2`, to expire the token, but not logout after 2 mins.

Jon

**Comment by yugangw-msft** [comment]
For this, maybe you can get delete the ~/.azure/accessTokens.json? (for windows it is under C:\Users\<user>\.azure)

**Comment by yugangw-msft** [comment]
Please reopen it if my suggestion does work
