### ISSUE TITLE
az storage blob copy start issue when I use "sas token"

### ISSUE THREAD

**Issue by the1bit** [Azure/azure-cli#6018]
Hi,

I am writing to ask your support regarding an issue I am facing when I would like to copy files with " az storage blob copy start" command with "--sas-token" parameter.

My command:
`az storage blob copy start --account-name mystorageacc --sas-token "?sv=2017-07-29&ss=bfqt&srt=sco&sp=rwdlacup&se=2019-04-04T15:43:14Z&st=2018-04-03T23:43:14Z&spr=https&sig=***************" --destination-container "files" --source-container "files" --source-blob "new/arm-template.json" --destination-blob "archive/arm-template.json"`

Command Result:
```
The specified resource does not exist.ErrorCode: CannotVerifyCopySource
<?xml version="1.0" encoding="utf-8"?><Error><Code>CannotVerifyCopySource</Code><Message>The specified resource does not exist.
RequestId:fe725383-701e-0002-5aae-ccdd02000000
Time:2018-04-05T07:20:26.8836489Z</Message></Error>
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 347, in execute
    six.reraise(*sys.exc_info())
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    result = cmd(params)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 180, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 420, in default_command_handler
    result = op(**command_args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/multiapi/storage/v2017_07_29/blob/baseblobservice.py", line 3032, in copy_blob
    False)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/multiapi/storage/v2017_07_29/blob/baseblobservice.py", line 3102, in _copy_blob
    return self._perform_request(request, _parse_properties, [BlobProperties]).copy
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/multiapi/storage/v2017_07_29/common/storageclient.py", line 354, in _perform_request
    raise ex
AzureMissingResourceHttpError: The specified resource does not exist.ErrorCode: CannotVerifyCopySource
<?xml version="1.0" encoding="utf-8"?><Error><Code>CannotVerifyCopySource</Code><Message>The specified resource does not exist.
RequestId:fe725383-701e-0002-5aae-ccdd02000000
Time:2018-04-05T07:20:26.8836489Z</Message></Error>
```

The file is there because when I use "--account-key" parameter it works fine as you can see:
```
{
  "completionTime": null,
  "id": "c4d61a22-8a56-42ff-9b7e-ea9cb81abb83",
  "progress": null,
  "source": null,
  "status": "success",
  "statusDescription": null
}
```

The SAS-TOKEN is correctly configured because any other operations work fine such as delete, show metadata, list files, etc with SAS-TOKEN.

Please help me to solve this issue.
### Environment summary

- Cloud: MCD
- Azure-Cli version: azure-cli (2.0.30), storage (2.0.30)
- Shell type: bash, python
- OS: RHEL 7.4 (Red Hat Enterprise Linux Server release 7.4 (Maipo))

Feel free to get in touch with any further questions.

I look forward to hearing from you.

Best Regards,
Tibor

**Comment by williexu** [comment]
@the1bit Thanks for bringing this to our attention. 
https://github.com/Azure/azure-cli/pull/6041 will apply the sas token specified by `--sas-token`  for the source as well as the destination and will be available in our next release.

For now, please use `--source-sas` to apply the same sas towards your source, as `--sas-token` currently only applies towards the destination.

**Comment by the1bit** [comment]
Hi,

I have tested again and I am sure there is a bug in the code.


I used this command according to your instructions:
`az storage blob copy start --account-name mystorageacc --sas-token "?sv=2017-07-29&ss=bfqt&srt=sco&sp=rwdlacup&se=2019-04-04T15:43:14Z&st=2018-04-03T23:43:14Z&spr=https&sig=***************" --destination-container "files" --source-container "files" --source-blob "new/arm-template.json" --destination-blob "archive/arm-template.json" --source-account-name mystorageacc --source-sas "?sv=2017-07-29&ss=bfqt&srt=sco&sp=rwdlacup&se=2019-04-04T15:43:14Z&st=2018-04-03T23:43:14Z&spr=https&sig=***************" --debug`


And the error is a new one:
```
AzureHttpError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.ErrorCode: CannotVerifyCopySource
<?xml version="1.0" encoding="utf-8"?><Error><Code>CannotVerifyCopySource</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
```

Then I have found a stange thing in the debug output:
 `'x-ms-copy-source': 'https://mystorageacc.blob.core.cloudapi.de/files/new/arm-template.json??sv=2017-07-29&ss=bfqt&srt=sco&sp=rwdlacup&se=2118-04-10T16:23:59Z&st=2018-04-10T08:23:59Z&spr=https&sig=4dCQpoGDZnHZY%2FCk0TXKXtH6I%2BzZP%2BTW2ZkErE1LgjQ%3D', `

As you can see there is a double '?' around SAS token: 
**.json??sv=**

**This is a bug in the code.**

Then I tested the --source-sas without '?':
`--source-sas "sv=2017-07-29&ss=bfqt&srt=sco&sp=rwdlacup&se=2019-04-04T15:43:14Z&st=2018-04-03T23:43:14Z&spr=https&sig=***************"`

and the copy works:
```
{
  "completionTime": null,
  "id": "077b06d7-d843-4fc3-ba8b-e48091753869",
  "progress": null,
  "source": null,
  "status": "success",
  "statusDescription": null
}
```

Please fix this bug.

Thank you for your help in this matter.

Best regards,
Tibor

**Comment by williexu** [comment]
@the1bit I've raised a new issue for the bug you found.
Thanks for finding this!

**Comment by Brondahl** [comment]
The same bug (i.e. same error message and solved with the same hack-fix) occurs in the `start-batch` command for me.

Running `az --version` returns:
```
azure-cli                          2.5.1 *

command-modules-nspkg              2.0.3
core                               2.5.1 *
nspkg                              3.0.4
telemetry                          1.0.4
```

Which is from late April 2020. So I assume already has the fix from #6073?
I assume there's some duplicated code that got missed in the #6073 patch.

**Comment by KJaunay** [comment]
> 
> 
> The same bug (i.e. same error message and solved with the same hack-fix) occurs in the `start-batch` command for me.
> 
> Running `az --version` returns:
> 
> ```
> azure-cli                          2.5.1 *
> 
> command-modules-nspkg              2.0.3
> core                               2.5.1 *
> nspkg                              3.0.4
> telemetry                          1.0.4
> ```
> 
> Which is from late April 2020. So I assume already has the fix from #6073?
> I assume there's some duplicated code that got missed in the #6073 patch.

This occurs for me as well running the below command when copying files between two directories in the same storage account and fileshare.

- `az storage file copy start-batch --source-account-name {} --source-share {} --pattern {} --account-name {} --destination-share {} --destination-path {} --sas-token {} --dryrun`

If I don't include --source-sas if says "z storage file copy start-batch: error: Storage account '<storage_account_name>' not found." whereas if I _do_ include --source-sas it works as expected. Both --source-sas and --sas-token are given the same values. 

## Environment Summary
```
Linux-4.18.0-147.8.1.el8_1.x86_64-x86_64-with-centos-8.1.1911-Core
Python 3.6.8
Installer: RPM

azure-cli 2.9.1 *

```

**Comment by Juliehzl** [comment]
we will investigate for these senarios.

**Comment by Juliehzl** [comment]
Hi @KJaunay, I think it is because you haven't provided credential for copy source.  `--source-account-key` or `--source-sas` should be specified for copy source authentication.

`--account-key`, `--connection-string` and `--sas-token` are used for copy destionation.

**Comment by Juliehzl** [comment]
Hi @Brondahl, I will look into `az storage blob copy start-batch` for sas token with `?`.

**Comment by KJaunay** [comment]
Yeah it works if you specify the --source-sas token but the wording when
you don't include it doesn't indicate that you need it.
