### ISSUE TITLE
cannot install extension 'dbms'

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#6019]
I'm trying to install Azure Database for PostgreSQL
As part of installation there's a step to complete:
az extension add --name rdbms
It fails with an error:

root@Alexey-HP:~# az extension add --name rdbms --debug
Command arguments: ['extension', 'add', '--name', 'rdbms', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f2ecebeeb70>, <function OutputProducer.on_global_arguments at 0x7f2ece705840>, <function CLIQuery.on_global_arguments at 0x7f2ece28e378>]
Event: CommandInvoker.OnPreCommandTableCreate [<function CLILogging.remove_logger_flags at 0x7f2ecebeebf8>]
Installed command modules ['acr', 'acs', 'advisor', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'dla', 'dls', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'interactive', 'iot', 'keyvault', 'lab', 'monitor', 'network', 'profile', 'rdbms', 'redis', 'reservations', 'resource', 'role', 'servicebus', 'servicefabric', 'sql', 'storage', 'vm']
Loaded module 'acr' in 0.005 seconds.
Loaded module 'acs' in 0.005 seconds.
Loaded module 'advisor' in 0.003 seconds.
Loaded module 'appservice' in 0.008 seconds.
Loaded module 'backup' in 0.005 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.013 seconds.
Loaded module 'batchai' in 0.005 seconds.
Loaded module 'billing' in 0.004 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.004 seconds.
Loaded module 'cloud' in 0.003 seconds.
Loaded module 'cognitiveservices' in 0.003 seconds.
Loaded module 'configure' in 0.002 seconds.
Loaded module 'consumption' in 0.004 seconds.
Loaded module 'container' in 0.003 seconds.
Loaded module 'cosmosdb' in 0.007 seconds.
Loaded module 'dla' in 0.006 seconds.
Loaded module 'dls' in 0.005 seconds.
Loaded module 'eventgrid' in 0.004 seconds.
Loaded module 'eventhubs' in 0.005 seconds.
Loaded module 'extension' in 0.002 seconds.
Loaded module 'feedback' in 0.002 seconds.
Loaded module 'find' in 0.002 seconds.
Loaded module 'interactive' in 0.001 seconds.
Loaded module 'iot' in 0.010 seconds.
Loaded module 'keyvault' in 0.007 seconds.
Loaded module 'lab' in 0.011 seconds.
Loaded module 'monitor' in 0.008 seconds.
Loaded module 'network' in 0.028 seconds.
Loaded module 'profile' in 0.007 seconds.
Loaded module 'rdbms' in 0.008 seconds.
Loaded module 'redis' in 0.009 seconds.
Loaded module 'reservations' in 0.004 seconds.
Loaded module 'resource' in 0.008 seconds.
Loaded module 'role' in 0.007 seconds.
Loaded module 'servicebus' in 0.009 seconds.
Loaded module 'servicefabric' in 0.004 seconds.
Loaded module 'sql' in 0.008 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.045 seconds.
Loaded module 'vm' in 0.019 seconds.
Loaded all modules in 0.290 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: '/root/.azure/cliextensions'
Event: CommandInvoker.OnPreCommandTableTruncate []
Event: CommandInvoker.OnPostCommandTableCreate [<function add_id_parameters at 0x7f2ecc02f158>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7f2ecbe697b8>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f2ece7058c8>, <function CLIQuery.handle_query_parameter at 0x7f2ece28e400>, <function handler at 0x7f2ecbd99d08>]
Extensions directory: '/root/.azure/cliextensions'
urllib3.connectionpool : Starting new HTTPS connection (1): aka.ms
urllib3.connectionpool : https://aka.ms:443 "GET /azure-cli-extension-index-v1 HTTP/1.1" 301 186
urllib3.connectionpool : Starting new HTTPS connection (1): azurecliextensionsync.blob.core.windows.net
urllib3.connectionpool : https://azurecliextensionsync.blob.core.windows.net:443 "GET /index1/index.json HTTP/1.1" 200 29786
Candidates ['rdbms-0.0.5-py2.py3-none-any.whl']
Candidates ['rdbms-0.0.5-py2.py3-none-any.whl']
Candidates ['rdbms-0.0.5-py2.py3-none-any.whl']
Candidates ['rdbms-0.0.5-py2.py3-none-any.whl']
Choosing the latest of the remaining candidates.
Chosen {'filename': 'rdbms-0.0.5-py2.py3-none-any.whl', 'sha256Digest': '2b587493a8e10738bb6f3f82cf9e26ebf32a509c162f7093b4cb8e99aff5072f', 'downloadUrl': 'https://prodrdbmsclipackages.blob.core.windows.net/cliextensions/rdbms-0.0.5-py2.py3-none-any.whl', 'metadata': {'classifiers': ['Development Status :: 4 - Beta', 'Intended Audience :: Developers', 'Intended Audience :: System Administrators', 'Programming Language :: Python', 'Programming Language :: Python :: 2', 'Programming Language :: Python :: 2.7', 'Programming Language :: Python :: 3', 'Programming Language :: Python :: 3.4', 'Programming Language :: Python :: 3.5', 'Programming Language :: Python :: 3.6', 'License :: OSI Approved :: MIT License'], 'extensions': {'python.details': {'contacts': [{'email': 'rohitjoy@microsoft.com', 'name': 'Rohit Joy', 'role': 'author'}], 'document_names': {'description': 'DESCRIPTION.rst'}, 'project_urls': {'Home': 'https://github.com/Azure/azure-cli-extensions'}}}, 'generator': 'bdist_wheel (0.29.0)', 'license': 'MIT', 'metadata_version': '2.0', 'name': 'rdbms', 'summary': 'An Azure CLI Extension providing support for Azure MySQL and Azure PostgreSQL.', 'version': '0.0.5'}}
Extension source is url? True
Extensions directory: '/root/.azure/cliextensions'
Downloading https://prodrdbmsclipackages.blob.core.windows.net/cliextensions/rdbms-0.0.5-py2.py3-none-any.whl to /tmp/tmphzwofsn9/rdbms-0.0.5-py2.py3-none-any.whl
urllib3.connectionpool : Starting new HTTPS connection (1): prodrdbmsclipackages.blob.core.windows.net
urllib3.connectionpool : https://prodrdbmsclipackages.blob.core.windows.net:443 "GET /cliextensions/rdbms-0.0.5-py2.py3-none-any.whl HTTP/1.1" 200 150104
Downloaded to /tmp/tmphzwofsn9/rdbms-0.0.5-py2.py3-none-any.whl
Validating the extension /tmp/tmphzwofsn9/rdbms-0.0.5-py2.py3-none-any.whl
Checksum of /tmp/tmphzwofsn9/rdbms-0.0.5-py2.py3-none-any.whl is OK
Extension compatibility result: is_compatible=True cli_core_version=2.0.30 min_required=None max_required=None
Validation successful on /tmp/tmphzwofsn9/rdbms-0.0.5-py2.py3-none-any.whl
Linux distro check: Reading from: /etc/apt/sources.list.d/azure-cli.list
Linux distro check: Found in list file: trusty
Linux distro check: Reported by API: trusty
Executing pip with args: ['install', '--target', '/root/.azure/cliextensions/rdbms', '/tmp/tmphzwofsn9/rdbms-0.0.5-py2.py3-none-any.whl']
Running: ['/opt/az/bin/python3', '-m', 'pip', 'install', '--target', '/root/.azure/cliextensions/rdbms', '/tmp/tmphzwofsn9/rdbms-0.0.5-py2.py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/az/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/az/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/opt/az/lib/python3.6/site-packages/pip/__init__.py", line 28, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/opt/az/lib/python3.6/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/opt/az/lib/python3.6/site-packages/pip/download.py", line 36, in <module>
    from pip.utils.glibc import libc_ver
  File "/opt/az/lib/python3.6/site-packages/pip/utils/glibc.py", line 4, in <module>
    import ctypes
  File "/opt/az/lib/python3.6/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.5: cannot open shared object file: No such file or directory

Command '['/opt/az/bin/python3', '-m', 'pip', 'install', '--target', '/root/.azure/cliextensions/rdbms', '/tmp/tmphzwofsn9/rdbms-0.0.5-py2.py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']' returned non-zero exit status 1.
Pip failed so deleting anything we might have installed at /root/.azure/cliextensions/rdbms
An error occurred. Pip failed with status code 1. Use --debug for more information.
root@Alexey-HP:~#

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```
azure-cli (2.0.30)
Microsoft Windows [Version 10.0.17110.1000]
Bash on Windows

**Comment by tjprescott** [comment]
@derekbekoe packaging issue, extensions?

**Comment by derekbekoe** [comment]
Please take a look at https://github.com/Azure/azure-cli-extensions/issues/65#issuecomment-366270381
Does the package of azure-cli you have match your distro? You can run `dpkg -s azure-cli` to check.

**Comment by alexeyshishkin01** [comment]
root@Alexey-HP:~# dpkg -s azure-cli
Package: azure-cli
Status: install ok installed
Priority: extra
Section: python
Installed-Size: 279569
Maintainer: Azure Python CLI Team <azpycli@microsoft.com>
Architecture: all
Version: 2.0.30-1~wheezy
Depends: libc6 (>= 2.9), libssl1.0.0 (>= 1.0.1)
Conffiles:
 /etc/bash_completion.d/azure-cli c84398bd5fcef515a11afad8f1a7827e
Description: Azure CLI 2.0
 A great cloud needs great tools; we're excited to introduce Azure CLI 2.0,
 our next generation multi-platform command line experience for Azure.
Homepage: https://github.com/azure/azure-cli
root@Alexey-HP:~# cat /etc/issue
Ubuntu 14.04.5 LTS \n \l

root@Alexey-HP:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

**Comment by derekbekoe** [comment]
Okay so you have `wheezy` but your distro is `trusty`.
Verify that the distro in `/etc/apt/sources.list.d/azure-cli.list` is correct the you can run `apt-get update`.

**Comment by alexeyshishkin01** [comment]
root@Alexey-HP:~# cat /etc/apt/sources.list.d/azure-cli.list
deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ trusty main
root@Alexey-HP:~#
I had to change it from 'wheezy' tp 'trusty' after first run of 'az extension add ...' due to the error message of wrong 'wheezy' in /etc/apt/sources.list.d/azure-cli.list
But after that I got the subject issue

**Comment by derekbekoe** [comment]
@alexeyshishkin01 After making the change to `azure-cli.list`, you should run `apt-get update`.
According to the last comment, it seems you had `wheezy` defined before but in the logs of your first comment, it says:
```
Linux distro check: Reading from: /etc/apt/sources.list.d/azure-cli.list
Linux distro check: Found in list file: trusty
Linux distro check: Reported by API: trusty
```

If it works now, great. However, I cannot reproduce it with `ubuntu:trusty` here.

**Comment by ferantivero** [comment]
hope I'm not adding noise @derekbekoe, but same here with another extensions (azure-devops). In my case was wheezy but xenial.

After running https://github.com/Azure/azure-cli/issues/6019#issuecomment-379987830 I got it working.

IIRC, originally I followed the instructions via apt https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest

$lsb_release -a
```
Distributor ID: Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename: xenial
```

$uname -a
```
Linux ubuntu 4.4.0-143-generic #169-Ubuntu
```

$dpkg -s azure-cli
```
Package: azure-cli
Status: install ok installed
Priority: extra
Section: python
Installed-Size: 377285
Maintainer: Azure Python CLI Team <azpycli@microsoft.com>
Architecture: all
Version: 2.0.60-1~wheezy
Depends: libc6 (>= 2.9), libssl1.0.0 (>= 1.0.1)
Conffiles:
 /etc/bash_completion.d/azure-cli c84398bd5fcef515a11afad8f1a7827e
Description: Azure CLI
 A great cloud needs great tools; we're excited to introduce Azure CLI,
 our next generation multi-platform command line experience for Azure.
Homepage: https://github.com/azure/azure-cli
```
