### ISSUE TITLE
az ad app update 

### ISSUE THREAD

**Issue by lestaat** [Azure/azure-cli#6023]
--required-resource-accesses is not well documented, how does it work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 921aa920-c25f-5227-aabb-49116da38fa7
* Version Independent ID: 9b5a53ad-edf8-4d89-f8e6-cde01b7866f6
* Content: [az ad app](https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest#az-ad-app-update)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
I will add help. For now you can check out sample usages in `az ad app create -h` and the `update` command has the same syntax 
```bash
Examples
    Create a native application with delegated permission of "access the AAD directory as the
    signed-in user
        az ad app create --display-name my-native --native-app --requiredResourceAccess
        @manifest.json
        ("manifest.json" contains the following content)
        [{
            "resourceAppId": "00000002-0000-0000-c000-000000000000",
            "resourceAccess": [
                {
                    "id": "a42657d6-7f20-40e3-b6f0-cee03008a62a",
                    "type": "Scope"
                }
           ]
        }]
```

**Comment by krishnand** [comment]
Have a follow-up question on this since the documentation is still not quite clear. Could you clarify if a json file needs to be created/saved in the local file system and then referenced here or can the manifest.json string be inlined?

**Comment by tjprescott** [comment]
You can inline the string, but it will generally be a painful process because you'll need to escape all of the internal quotes. Using the @syntax is definitely the best way to go.

**Comment by Zazcallabah** [comment]
Is the @ syntax a cmd thing? Or is it specific to az? How can I do something similar in powershell?

**Comment by Zazcallabah** [comment]
When I try quoting the @manifest.json i get the following

    $ad_app = az ad app create --display-name $name --homepage $home --identifier-uris $id --required-resource-accesses "@manifest.json" --oauth2-allow-implicit-flow true
    string indices must be integers
    Traceback (most recent call last):
      File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
      File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-core\azure\cli\core\commands\__init__.py", line 366, in execute
      File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-role\azure\cli\command_modules\role\commands.py", line 31, in graph_err_handler
      File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-core\azure\cli\core\commands\__init__.py", line 343, in execute
      File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-core\azure\cli\core\commands\__init__.py", line 182, in __call__
      File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-core\azure\cli\core\__init__.py", line 436, in default_command_handler
      File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-role\azure\cli\command_modules\role\custom.py", line 637, in create_application
      File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-role\azure\cli\command_modules\role\custom.py", line 715, in _build_application_accesses
    TypeError: string indices must be integers

Removing `--required-resource-accesses "@manifest.json"` makes the command go through without error.

Fun fact: no user named troyd exists on my computer, and the folder c:\users\troyd doesn't exist?

**Comment by cwoolum** [comment]
I was unable to get the file reference to work in OSX. I ended up using the permission add command in the CLI like 

`az ad app permission add --id $serverApplicationId --api 00000003-0000-0000-c000-000000000000 --api-permissions e1fe6dd8-ba31-4d61-89e7-88639da4683d=Scope`

where `api-permissions` is a space separated list of key value pairs.

**Comment by santhoshbomma9** [comment]
> You can inline the string, but it will generally be a painful process because you'll need to escape all of the internal quotes. Using the @syntax is definitely the best way to go.

Hi @tjprescott , how do we inline? which flag helps pass the manifest json as inline?

**Comment by jiasli** [comment]
@santhoshbomma9, you may check the sample with

```
> az ad app update --help


Examples
    update a native application with delegated permission of "access the AAD directory as the
    signed-in user"
        az ad app update --id e042ec79-34cd-498f-9d9f-123456781234 --required-resource-accesses
        @manifest.json
        ("manifest.json" contains the following content)
        [{
            "resourceAppId": "00000002-0000-0000-c000-000000000000",
            "resourceAccess": [
                {
                    "id": "a42657d6-7f20-40e3-b6f0-cee03008a62a",
                    "type": "Scope"
                }
           ]
        }]
```

If you want to make it inline, you may use

```
az ad app update --id e042ec79-34cd-498f-9d9f-123456781234 --required-resource-accesses '[{"resourceAppId": "00000002-0000-0000-c000-000000000000",...'
```

But notice that [quoting rules](https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#using-quotation-marks-in-values) apply.

You may also directly call Microsoft Graph API with `az rest`. See https://github.com/Azure/azure-cli/issues/12946.

**Comment by santhoshbomma9** [comment]
@jiasli  Doesn't seem to work tho, am I missing anything?
![image](https://user-images.githubusercontent.com/40445595/118518936-7fa5aa80-b6ed-11eb-838d-9fd7a7963a08.png)

**Comment by santhoshbomma9** [comment]
landingPageApp=$(az rest --method POST --headers "Content-Type=application/json" --uri https://graph.microsoft.com/v1.0/applications --body '{"displayName": "LandingpageApp", "api":{"requestedAccessTokenVersion": 2}, "signInAudience" : "AzureADandPersonalMicrosoftAccount", "web": {"implicitGrantSettings": { "enableIdTokenIssuance": true }}, "requiredResourceAccess": [{"resourceAppId": "00000003-0000-0000-c000-000000000000", "resourceAccess": [{ "id": "e1fe6dd8-ba31-4d61-89e7-88639da4683d", "type": "Scope" }]}] }' | jq '{ "appId": .appId, "publisherDomain": .publisherDomain }')

this works! thank you

**Comment by jiasli** [comment]
@santhoshbomma9, `--required-resource-accesses` should be followed by `'[{"resourceAppId": ...` instead of `{"signInAudience"...`. Glad to know `az rest` works for you.

**Comment by santhoshbomma9** [comment]
@jiasli looks like az rest doesnt work with deploymentscripts. any insight into that? 
`bash-5.0# az rest --method GET --uri 'https://graph.microsoft.com/v1.0/applications'
Forbidden({"error":{"code":"Authorization_RequestDenied","message":"Insufficient privileges to complete the operation."`

**Comment by jiasli** [comment]
The error indicates you don't have corresponding permission to call [List applications](https://docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&tabs=http) API. Please check the permission of the identity you used to `az login`. 

For questions regarding Microsoft Graph API itself, please feel free to [create a support ticket](https://azure.microsoft.com/en-us/support/create-ticket/).

**Comment by santhoshbomma9** [comment]
All good, it was permissions on my service principle, thank you the heads up!
