### ISSUE TITLE
Is there a way to create a service principal without azure cli?

### ISSUE THREAD

**Issue by NightFantomJ2** [Azure/azure-cli#6030]
Is there a way to create a service principal without azure cli? E.g. in azure portal, or anything that doesn't cost extra specifically.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99d25ff-03e2-e015-37f4-a29b59ec50d4
* Version Independent ID: 1a8e88ed-72c7-fbe7-b0ad-68f23b3946cd
* Content: [az ad sp](https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal

**Comment by tjprescott** [comment]
Looking at the referenced doc though, you would likely find it faster to accomplish this with CLI vs. portal.

**Comment by zariye** [comment]
Is there also a possibility to do it with terraform instead?
