### ISSUE TITLE
--verbose does nothing for most commands

### ISSUE THREAD

**Issue by djberg96** [Azure/azure-cli#6032]
az 2.0.29
Darwin 17.5

When running a command like `az cloud list --verbose` the `--verbose` option doesn't appear to actually do anything. This is true of most commands. In the 1.x CLI it would show you the underlying http requests that it was making.

The `--debug` option only appears to show various bits of python modules loading and so on. It doesn't show the http request info.

Can you add this back in?

**Comment by tjprescott** [comment]
`--debug` does show the HTTP requests. It just so happens that `az cloud list` does not make any HTTP requests.

You are correct that `--verbose` doesn't do much for most commands.

**Comment by tjprescott** [comment]
Some are hard-coded in the CLI. If you had custom cloud registered, it will read those off your machine.

**Comment by djberg96** [comment]
@tjprescott ok, thanks.
