### ISSUE TITLE
"az container delete" does not seem to accept the '--yes' or '-y' options.

### ISSUE THREAD

**Issue by JeffByers-SF** [Azure/azure-cli#6033]
Azure CLI version azure-cli (2.0.30) command "az container delete" does not seem to accept the '--yes' or '-y' options:
ERROR: az: error: unrecognized arguments: --yes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e5d1da7-7c4f-c9e6-e4b9-a30407675acf
* Version Independent ID: ba32e12d-8283-f980-e1d0-1ca2a75a5152
* Content: [az container](https://docs.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest#az-container-delete)
* Content Source: [src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
What shell were you using?  This seems to be working as expected for me.

**Comment by tjprescott** [comment]
Unable to repro. Closing.
