### ISSUE TITLE
'az policy definition list' doesn't show custom policies

### ISSUE THREAD

**Issue by russjury** [Azure/azure-cli#6037]
Running 'az policy definition list' doesn't appear to show a policy that has the policyType of "Custom".

To reproduce, create a policy definition via web console/gui (or via Terraform/azurerm provider with policy_type="Custom").  Then run 'az policy definition list' - and the policy you just created won't show up in the output.

azure-cli 2.0.30

**Comment by byron70** [comment]
@russjury I had this occur to me, but I was in the wrong subscription `az account set -s {sub_id}` to the subscription the definition was scoped to during creation.  Seems the policy definitions are scoped to a subscription.  

I'm actually wishing right now that `az account create` allowed for specifying a scope during creation or an even more sane option to have global definitions, as the assignments have to fall within the definition scope.

**Comment by russjury** [comment]
Thanks @byron70 - that was my issue.  Was working with Terraform using creds from env variables, so I didn't realize that the Azure CLI was still pointed to my old free account - seems it never expires the session (or if it does, it's a LONG timeout).
