### ISSUE TITLE
az vm create and HUB entitlement not clear

### ISSUE THREAD

**Issue by andrew-best-diaxion** [Azure/azure-cli#6051]
The documentation above for the `--license-type` switch says:

```
--license-type
License type if the Windows image or disk used was licensed on-premises.
accepted values: Windows_Client, Windows_Server
```

It doesn't not specifically state which value should be used to have a VM created with the HUB entitlement active.
Some googling around tells me its probably `Windows_Server` however finding an authoritative source from MS for this has got me nothing.
The document here should be made clearer so the reader knows which value to use for which use case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 152b549b-d4b3-13e5-081c-c604b6e4d89e
* Version Independent ID: 3f79be78-ce75-ad31-304b-bad7d475ec9e
* Content: [az vm](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by adewaleo** [comment]
Hello @andrew-best-diaxion, the following [link](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/hybrid-use-benefit-licensing?toc=%2Fazure%2Fvirtual-machines%2Fwindows%2Ftoc.json) has information about using the Hybrid Benefit through the CLI. It also gives an example. This video also explains [AHB](https://www.youtube.com/watch?v=xaHz5QOCWi4). It appears that the correct option for windows server is indeed "windows_server". I will reach out to the service team to see why they also expose "windows_client" in their API, which is reflected in the CLI. It is possible that this is to support another feature or an upcoming feature.
