### ISSUE TITLE
Missing rest calls

### ISSUE THREAD

**Issue by adamlavie** [Azure/azure-cli#6053]
This is probably a general comment about the docs. CLI is nice but I would really like to integrate with ACR using the rest API calls.
These calls should be compatible with DockerHub V1 API but still, some things don't work as expected so these docs could be nice to have

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94aa298e-2dd2-7140-c71a-4214be845051
* Version Independent ID: 0e8da3c9-380f-2864-4ba6-1a8e113448d6
* Content: [az acr repository](https://docs.microsoft.com/en-us/cli/azure/acr/repository?view=azure-cli-latest#az-acr-repository-show-manifests)
* Content Source: [src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
https://docs.microsoft.com/en-us/rest/api/containerregistry/

Closing as this isn't an issue with the CLI.
