### ISSUE TITLE
Creating Azure AD Group with Service Principal Authentication Encounters Insufficient Privilege Response

### ISSUE THREAD

**Issue by danielhelfand** [Azure/azure-cli#6058]
---

### Environment summary

Install Method 
`brew install azure-cli`

CLI Version 
2.0.29 

OS Version
macOS High Sierra 10.13.3  

I am trying to use an Azure Service Principal to create an Azure Active Directory group. My process is shown below:

```
az login --service-principal -u <app id>  -p <client secret> --tenant <tenant id>

az ad group create --display-name example --mail-nickname example
```

After running these commands, I get the following error:
```
Insufficient privileges to complete the operation.
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.29/libexec/lib/python3.6/site-packages/knack/cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.29/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 347, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.29/libexec/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.29/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 319, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.29/libexec/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 180, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.29/libexec/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.29/libexec/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 418, in default_command_handler
    result = op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.29/libexec/lib/python3.6/site-packages/azure/graphrbac/operations/groups_operations.py", line 333, in create
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error.GraphErrorException: Insufficient privileges to complete the operation.
```

I am assuming this is related to the service principal's permissions, but I can't find any clear documentation on what permissions are needed by a service principal to create an Azure AD Group. Any thoughts on what permissions are needed or if this is a more complex issue would be greatly appreciated.

**Comment by yugangw-msft** [comment]
You can check out https://github.com/Azure/azure-sdk-for-node/issues/2363#issuecomment-354897064 which has the most relevant discussions. Feel free to post any follow-up questions here.
In short, you need to configure the service principal to have the write permission first, before you can let it do anything.

**Comment by danielhelfand** [comment]
@yugangw-msft Thanks for this.

So, would the permissions most likely be under Windows Azure Active Directory then give Read and write all groups permission to the service principal?

**Comment by yugangw-msft** [comment]
The most relevant one is the `Read and write directory data` under `APPLICATION PERMISSIONS`.  
Please keep in mind 2 things"
1. Again, the permission is under `APPLICATION PERMISSIONS`, not under `DELEGATED PERMISSIONS` which is a different permission set.
2. Always click the `Grant Permissions` button after you save the change.

**Comment by danielhelfand** [comment]
@yugangw-msft Thanks for the clarification. I'll try this out and close this if everything works.

**Comment by danielhelfand** [comment]
@yugangw-msft So adding `Read and write directory data` didn't appear to resolve the issue. Are there additional permissions needed?

**Comment by danielhelfand** [comment]
This [post](https://serverfault.com/questions/889976/how-to-give-azure-service-principal-the-same-rights-as-my-own-user?rq=1) might be relevant for anyone experiencing this issue. Haven't tried it myself but might look into it.

**Comment by dkmbw** [comment]
i have a similar problem and i do not want to click on any button but to automate it with the az tool. i have SET the Read and write directory data via az app permission add, but az app permission grant does not work on command line, only via website ui.

**Comment by yugangw-msft** [comment]
@dkmbw, once CLI gets refreshed following the [SDK update](https://github.com/Azure/azure-rest-api-specs/pull/5181), i will let you know to try out, hope that work will close out the whole e2e

**Comment by dszryan** [comment]
this issue is resolved when using legacy view for app registration.

the issue still persists when using the new general availability release on azure.

**Comment by yonzhan** [comment]
add to S165.

**Comment by yonzhan** [comment]
add to S165.

**Comment by jiasli** [comment]
Closing the issue, since it hasn't been updated for a long time. If the issue persists, please create a new one. Thanks.
