### ISSUE TITLE
Tab completion not working on Mac 10.13.3

### ISSUE THREAD

**Issue by jamesbannan** [Azure/azure-cli#6067]
---

### Environment summary

Install Method: homebrew (as per [https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest)) 
CLI version: 2.0.30 
OS version: 10.13.3
Shell Type: bash (iTerm/Terminal)

Tab completion doesn't appear to be working at all. Azure CLI has been installed using homebrew as per the official Microsoft documentation. When pressing TAB there is an error sound and the terminal output shows the contents of the local folder, as if you're trying to run a command against a local file and haven't specified the file.

I checked this against Azure CLI on Cloud Shell, and the tab completion behaviour in Cloud Shell is working exactly as expected.

**Comment by jamesbannan** [comment]
Thanks @derekbekoe - I have done that and the issue is fixed. However, it's worth mentioning that the issue is only fixed for bash. If I run PowerShell from the same bash shell, tab completion stops working.

**Comment by tjprescott** [comment]
Tab completion is not supported for PowerShell or CMD.exe.
