### ISSUE TITLE
vm/vmss update: support --ip-forwarding

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#6071]
~e.g. `az vm/vmss update --ip-forwarding (true|false)`~
EDIT: should be made on `az vm/vmss nic set`

**Comment by yugangw-msft** [comment]
//cc: @christiankuhtz

**Comment by yugangw-msft** [comment]
Closing and will reactivate on more incoming user votes

**Comment by kjdeepthi** [comment]
Is there a way to enable ip forwarding on vmss network interface ?Currently i see it is set to false with azure cni

**Comment by kjdeepthi** [comment]
Figured out a way with az vmss update --resource-group <resource group name> --name <vmss-scale-set> --set virtualMachineProfile.networkProfile.networkInterfaceConfigurations[0].enableIPForwarding=false
