### ISSUE TITLE
dir_creator.sh has hard dependency on x86 architecture

### ISSUE THREAD

**Issue by gtrifonov** [Azure/azure-cli#6092]
### Details: 
master/build_scripts/debian/dir_creator.sh has hard dependency on x86 architecture. 
Rebuilding azure-cli failing for arm processors.
See line 113.

### Environment summary

Install Method build
OS: Raspberry PI Jessy
Processor: ArmV7

**Comment by derekbekoe** [comment]
@gtrifonov If you remove that line, does it build successfully?
The script does not support ARM specifically but I'd be interested either way.

**Comment by Arbuzinside** [comment]
any progress on this?

**Comment by tjprescott** [comment]
These scripts are intended for use only by the CLI team to build our releases, not to support external user builds. Closing this issue.
