### ISSUE TITLE
list keys are inconsistent ("keys list" vs. "list-keys") across Cosmos DB and Event Hub

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-cli#6094]
```
az eventhubs eventhub authorization-rule keys list -n myrule -g inventory-hub --namespace-name inventory-test --eventhub-name inventoryeh
 
az cosmosdb list-keys -g inventory-hub -n mycosmosdb0330201
```

Suggest consistency across these commands.

**Comment by tjprescott** [comment]
Agreed. In this case it would be CosmosDB that needs to change.

**Comment by shurd** [comment]
We are tracking this change internally as work item number 449214. The target date for this change is the middle of July. I will post updates as they are available.
