### ISSUE TITLE
Feature request: Allow edit of AD application manifest

### ISSUE THREAD

**Issue by croeck** [Azure/azure-cli#6097]
Currently there is no way to update the manifest of an Azure AD application programatically without using the Windows PowerShell.

Even though I am only interested in updating the `groupMembershipClaims` to `All`, a more generic update would benefit other users as well.

## Environment

My CLI version: azure-cli (2.0.30)

## References

This functionality is given there as described in the two linked websites:
- https://docs.microsoft.com/en-us/powershell/azure/active-directory/install-adv2?view=azureadps-2.0
- https://stackoverflow.com/questions/47581186/how-to-edit-azure-service-principal-manifest-from-command-line

## Why

This feature is required to fully automate the deployment of Kubernetes clusters via the [acs-engine](https://github.com/Azure/acs-engine) to Azure.

**Comment by yugangw-msft** [comment]
This will be covered through #5948 which i will expose a generic update to even taking a manifest json file

**Comment by yugangw-msft** [comment]
reactivate this as I am able to fix this w/o the need to refresh the [GraphRbac' swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/graphrbac/data-plane/stable/1.6/graphrbac.json) which is a long shot due to ownership issues
