### ISSUE TITLE
VMSS extensions documentation

### ISSUE THREAD

**Issue by akramwaseem** [Azure/azure-cli#6102]
Don't you think adding the names of the extensions or link in this page, would make the command usable and easy for everybody.
And less time to figure out what would be the exact extension name and where to find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29233b11-4e55-8560-9dad-43ac44b818c2
* Version Independent ID: b60ca5ef-f607-80b6-c641-0278cd8bdc61
* Content: [az vmss extension](https://docs.microsoft.com/en-us/cli/azure/vmss/extension?view=azure-cli-latest#az-vmss-extension-list)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machine-scale-sets**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Hi @akramwaseem. The command you want to use is:
`az vm extension image list`.

We can update the command to point this out better. Thank you for bringing this to our attention.

**Comment by akramwaseem** [comment]
@tjprescott thanks for the command. That list is very very very big.
Might be easier just to have it on the document which people are reading at that time.

**Comment by gatneil** [comment]
Hey @akramwaseem! I find myself running this command (and other similar ones) frequently, so I wrote a script to run these commands periodically and upload them here: https://negatblog.blob.core.windows.net/lists/meta_list

It's not an official doc, but hopefully it helps :)

Cheers,
Neil

**Comment by akramwaseem** [comment]
@gatneil --thanks for the links.

**Comment by adewaleo** [comment]
A populator command ("values from") for `az vm/ss extension set --name` will be added through this [PR](https://github.com/Azure/azure-cli/pull/8051)
