### ISSUE TITLE
`lab vm create` fails with error that gives no information.

### ISSUE THREAD

**Issue by williexu** [Azure/azure-cli#6107]
---
I've run the following command and it gives me no information:
```
> az lab vm create --lab-name wilxlab --name wilxlabvm0 -g wilxgroup --image "Ubuntu Server 16.04 LTS" --image-type gallery
Admin Password:
Confirm Admin Password:
Deployment failed. Correlation ID: 67e36dbf-5dbc-4819-bd9f-2624b2b23bbc. An error has occurred.
```
This reflects the response from the service, which is:
`{"status":"Failed","error":{"code":"GeneralError","message":"An error has occurred."}}`

Specifying the `--size` and `--ip-configuration` args lets me create this vm, but it is not at all obvious for the customer that these are necessary.

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by RakeshMohanMSFT** [comment]
Reopen this if this is still happening
