### ISSUE TITLE
Improvement to collect_blobs in command_modules/storage/util.py

### ISSUE THREAD

**Issue by ajith-k** [Azure/azure-cli#6116]
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

>az --version
azure-cli (2.0.31)

storage (2.0.31)

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

```
```
Primary Issue : Very slow batch download of blobs from Azure Storage using CLI when we attempt an **az storage blob download-batch** on a container with a very large number of blobs. The enumeration of matching blobs is very slow

Reviewing the collect_blobs function it appears that we perform the pattern matching locally since the service cannot handle wildcards. So we land up listing the entire container contents to match with the pattern. 
We can improve the situation quite a bit by leveraging the blob prefix search in BaseBlobService.list_blobs. However, for this we need to extract the blob prefix from the pattern.

**Comment by troydai** [comment]
Alternative solution: asynchronous list and downloading.

**Comment by limingu** [comment]
The [azcopy download command](https://github.com/Azure/azure-cli-extensions/tree/master/src/storage-preview#azcopy-integration) is in our storage-preview extension now. Let us know if you are satisfied with the performance.

Try that like:
az storage azcopy blob download \
    -c containerName \
    --account-name accountName \
    -s virtual_directory/path \
    -d download/path \
    --recursive
