### ISSUE TITLE
`az monitor autoscale create` gives a cryptic error if the resource type is not supported.

### ISSUE THREAD

**Issue by twitchax** [Azure/azure-cli#6120]
---

### Environment summary

* Installed via brew.
* Version: 2.0.31.
* OS: Mac OS X High Sierra.
* Shell: bash.

```
$ az monitor autoscale create --resource $webappid --count 1
Exception of type 'Microsoft.WindowsAzure.Management.Monitoring.MonitoringServiceException' was thrown.
```

**Comment by tjprescott** [comment]
Due to case-sensitivity issue, the code was not displayed.  After fixing that, the error that would display is:
```
Exception of type 'Microsoft.WindowsAzure.Management.Monitoring.MonitoringServiceException' was thrown.. [Code: "ResourceNotSupported"]
```

So by the code you can see that the resource is not supported.

Beyond that, the message of the error payload should be useful and it isn't. That lies with the Monitor service team itself.

**Comment by asheniam** [comment]
Thanks for reporting this.  We will fix the error message.

**Comment by PatrickTseng** [comment]
Just fixed this issue and the exception now has the following message: 

The target resource id '{0}' is not supported.

Where {0} is the ARM resource id. 

Thanks
Patrick Tseng
Developer, Microsoft Azure Monitoring team.

**Comment by MyronFanQiu** [comment]
@PatrickTseng @twitchax Looks like this issue has been fixed. Could we close this issue?

**Comment by PatrickTseng** [comment]
Yes, I think we can close it.

Regards,
Patrick
________________________________

**Comment by MyronFanQiu** [comment]
@twitchax @PatrickTseng Thanks all.

**Comment by PatrickTseng** [comment]
Thanks for closing it
Appreciated it

Patrick

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
