### ISSUE TITLE
"No module named azure" after installation

### ISSUE THREAD

**Issue by yzhong94** [Azure/azure-cli#6123]
### Environment summary

System: OSX 10.11.6 (15G19009)
Shell: bash

Yis-MacBook-Pro:Documents yizhong$ brew uninstall azure-cli

Uninstalling /usr/local/Cellar/azure-cli/2.0.31... (11,873 files, 59.4MB)
Yis-MacBook-Pro:Documents yizhong$ 
Yis-MacBook-Pro:Documents yizhong$ brew update && brew install azure-cli
Already up-to-date.
==> Downloading https://homebrew.bintray.com/bottles/azure-cli-2.0.31.el_capitan.bottle.tar.gz
Already downloaded: /Users/yizhong/Library/Caches/Homebrew/azure-cli-2.0.31.el_capitan.bottle.tar.gz
==> Pouring azure-cli-2.0.31.el_capitan.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/azure-cli/2.0.31: 11,873 files, 59.4MB

Yis-MacBook-Pro:Documents yizhong$ az
/usr/bin/python: No module named azure

```
```

**Comment by derekbekoe** [comment]
@yzhong94 Can you provide the output of the following commands?
```
$which az
$ cat $(which az)
```

It should look something like this:
```
$ which az
/usr/local/bin/az
$ cat $(which az)
#!/usr/bin/env bash
export PYTHONPATH="/usr/local/Cellar/azure-cli/2.0.30/libexec/lib/python3.6/site-packages"
if command -v python3.6 >/dev/null 2>&1; then
  python3.6 -m azure.cli "$@"
else
  python3 -m azure.cli "$@"
fi
```
