### ISSUE TITLE
Client does not allow multiple destination-port-ranges

### ISSUE THREAD

**Issue by marty2bell** [Azure/azure-cli#6130]
Azure cli 2.0.31 on macOS

issuing
````
az network nsg rule create --destination-port-ranges 80 443
````

fails with Security rule has invalid Port range.  Value should be an integer OR integer range with '-' delimiter. Valid range 0-65535.

Marty

**Comment by tjprescott** [comment]
I am unable to repro on Windows or Mac.

```
az network nsg rule create -g tjp-rg --nsg-name nsg1 -n rule1 --priority 2000 --destination-port-ranges 80 443
{
  "access": "Allow",
  "additionalProperties": {},
  "description": null,
  "destinationAddressPrefix": "*",
  "destinationAddressPrefixes": [],
  "destinationApplicationSecurityGroups": null,
  "destinationPortRange": null,
  "destinationPortRanges": [
    "80",
    "443"
  ],
  "direction": "Inbound",
  "id": "/subscriptions/{sub}/resourceGroups/tjp-rg/providers/Microsoft.Network/networkSecurityGroups/nsg1/securityRules/rule1",
  "name": "rule1",
  "priority": 2000,
  "protocol": "*",
  "provisioningState": "Succeeded",
  "resourceGroup": "tjp-rg",
  "sourceAddressPrefix": "*",
  "sourceAddressPrefixes": [],
  "sourceApplicationSecurityGroups": null,
  "sourcePortRange": "*",
  "sourcePortRanges": []
}
```

Please share the exact command you used to trigger this (the above is missing required parameters) and the error message you got.

**Comment by marty2bell** [comment]
Hi

Here's the slightly massaged version of the call to azure-cli....

````
az network nsg rule create \
--resource-group myresourcegroup \ 
--nsg-name k8s-master-XXXXXX-nsg \
--name ssl_rule \
--priority 200 \
--access 'Allow' \
--destination-address-prefix VirtualNetwork \
--destination-port-ranges 443 30444 \
--protocol Tcp \
--direction 'Inbound' \
--source-address-prefix 99.99.99.99 \
--source-port-range '*'
````

**Comment by tjprescott** [comment]
Please run the command with `--debug` and send the stack trace to me (trpresco) at my Microsoft email so I can take a deeper look. The above command worked fine for me.

**Comment by marty2bell** [comment]
Hey @tjprescott 

I'll close this issue........in getting the command to run with debug, it succeeded so now I'm thinking there's something wrong with the script that calls the az command rather than az itself.

Apologies for the waste of time 

Marty

**Comment by tjprescott** [comment]
No problem @marty2bell. Glad you got it working!

**Comment by marty2bell** [comment]
@tjprescott Sorry Travis, I got an undeliverable response to your ms account.....assume I got it wrong.....can you give me any pointers?

**Comment by tjprescott** [comment]
I got your email and this issue was that you were quoting your list of ports, which is not what CLI considers a space-separated list:

OK: 80 443
OK (but unnecessary): "80" "443"
NOT OK: "80 443"
