### ISSUE TITLE
backup protection enable-for-vm - Resource Group argument shared between VM and Vault

### ISSUE THREAD

**Issue by nofunatall** [Azure/azure-cli#6140]
From azure-cli v2.0.31

For the azure command 'az backup protection enable-for-vm' the --resource-group argument forces you to have your backup vault within the same resource group as the VM.

Simple solution would be to add a second option to define the Vault or VM resource group separately.

Does anyone know a work around for the time being?

**Comment by tjprescott** [comment]
There is no workaround.  
```
 --vm             [Required]: Name or ID of the Virtual Machine to be protected.
```

To specify a VM in a different resource group, use the ARM ID.
