### ISSUE TITLE
AKS Getting Started

### ISSUE THREAD

**Issue by DiginessForever** [Azure/azure-cli#6141]
This set of instructions is a non-starter.  I got here from a Google search "install aks".  There are no instructions on how to get started.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/aks.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/aks.yml)
* Service: **unspecified**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by derekbekoe** [comment]
@DiginessForever Does this not help?
https://docs.microsoft.com/en-us/azure/aks/tutorial-kubernetes-deploy-cluster
