### ISSUE TITLE
Error loading command module 'storage'

### ISSUE THREAD

**Issue by dazdaz** [Azure/azure-cli#6148]
$ az
Error loading command module 'storage'
__init__() got multiple values for keyword argument 'default_completer'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/azure/cli/main.py", line 35, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/lib/python3/dist-packages/azure/cli/core/application.py", line 84, in execute
    self.parser.load_command_table(command_table)
  File "/usr/lib/python3/dist-packages/azure/cli/core/parser.py", line 91, in load_command_table
    enable_autocomplete(self)
  File "/usr/lib/python3/dist-packages/azure/cli/core/parser.py", line 34, in enable_autocomplete
    argcomplete.autocomplete(parser, validator=lambda c, p: c.lower().startswith(p.lower()))
  File "/usr/lib/python3/dist-packages/argcomplete/__init__.py", line 166, in __call__
    default_completer=default_completer)
  File "/usr/lib/python3/dist-packages/azure/cli/core/parser.py", line 30, in __init__
    **kwargs)
TypeError: __init__() got multiple values for keyword argument 'default_completer'

$ az --version
Python (Linux) 3.6.3 (default, Oct  3 2017, 21:45:48)
[GCC 7.2.0]

$ cat /etc/os-release
NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.10"
VERSION_ID="17.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by dazdaz** [comment]
$ dpkg -l python-azure-storage
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                              Version               Architecture          Description
+++-=================================-=====================-=====================-=======================================================================
ii  python-azure-storage              0.33.0-1              all                   Microsoft Azure Storage Library for Python 2.x

$ az --debug
Installed command modules ['component', 'configure', 'feedback', 'iot', 'keyvault', 'network', 'profile', 'redis', 'resource', 'role', 'storage', 'taskhelp', 'vm', 'webapp']
Loading command tables from all installed modules.
Registered application event handler 'CommandTable.Loaded' at <function add_id_parameters at 0x7fbefbc8ed90>
Error loading command module 'storage'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/azure/cli/core/commands/__init__.py", line 196, in get_command_table
    import_module('azure.cli.command_modules.' + mod)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/storage/__init__.py", line 8, in <module>
    import azure.cli.command_modules.storage._params
  File "/usr/lib/python3/dist-packages/azure/cli/command_modules/storage/_params.py", line 18, in <module>
    from azure.storage.models import AccountPermissions
ModuleNotFoundError: No module named 'azure.storage'

**Comment by dazdaz** [comment]
$ sudo apt install python-pip
$ pip install storage
Collecting storage
Collecting paramiko>=1.8.0 (from storage)
  Using cached https://files.pythonhosted.org/packages/3e/db/cb7b6656e0e7387637ce850689084dc0b94b44df31cc52e5fc5c2c4fd2c1/paramiko-2.4.1-py2.py3-none-any.whl
Collecting cryptography>=1.5 (from paramiko>=1.8.0->storage)
  Using cached https://files.pythonhosted.org/packages/dd/c2/3a5bfefb25690725824ade71e6b65449f0a9f4b29702cce10560f786ebf6/cryptography-2.2.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pynacl>=1.0.1 (from paramiko>=1.8.0->storage)
  Using cached https://files.pythonhosted.org/packages/80/3d/d709b9fbd69e21dd3a4d34eb690c5484094699e03b7447bc7eb173cfd7b6/PyNaCl-1.2.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pyasn1>=0.1.7 (from paramiko>=1.8.0->storage)
  Using cached https://files.pythonhosted.org/packages/ba/fe/02e3e2ee243966b143657fb8bd6bc97595841163b6d8c26820944acaec4d/pyasn1-0.4.2-py2.py3-none-any.whl
Collecting bcrypt>=3.1.3 (from paramiko>=1.8.0->storage)
  Using cached https://files.pythonhosted.org/packages/2e/5a/2abeae20ce294fe6bf63da0e0b5a885c788e1360bbd124edcc0429678a59/bcrypt-3.1.4-cp27-cp27mu-manylinux1_x86_64.whl
Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography>=1.5->paramiko>=1.8.0->storage)
  Using cached https://files.pythonhosted.org/packages/14/dd/3e7a1e1280e7d767bd3fa15791759c91ec19058ebe31217fe66f3e9a8c49/cffi-1.11.5-cp27-cp27mu-manylinux1_x86_64.whl
Collecting enum34; python_version < "3" (from cryptography>=1.5->paramiko>=1.8.0->storage)
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting idna>=2.1 (from cryptography>=1.5->paramiko>=1.8.0->storage)
  Using cached https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=1.5->paramiko>=1.8.0->storage)
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting six>=1.4.1 (from cryptography>=1.5->paramiko>=1.8.0->storage)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting ipaddress; python_version < "3" (from cryptography>=1.5->paramiko>=1.8.0->storage)
  Using cached https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.5->paramiko>=1.8.0->storage)
Installing collected packages: pycparser, cffi, enum34, idna, asn1crypto, six, ipaddress, cryptography, pynacl, pyasn1, bcrypt, paramiko, storage
Successfully installed asn1crypto-0.24.0 bcrypt-3.1.4 cffi-1.11.5 cryptography-2.2.2 enum34-1.1.6 idna-2.6 ipaddress-1.0.22 paramiko-2.4.1 pyasn1-0.4.2 pycparser-2.18 pynacl-1.2.1 six-1.11.0 storage-0.0.4.3
Segmentation fault (core dumped)

**Comment by derekbekoe** [comment]
@dazdaz Please provide the following information.

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)

**Comment by derekbekoe** [comment]
That version of the CLI is *very* old.
Install the latest at https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest

That should resolve this.

**Comment by dazdaz** [comment]
I believe that it's the default Azure CLI which came with Ubuntu 17.10, I had assumed that the latest would be deployed.  Thanks.

**Comment by derekbekoe** [comment]
Yes we are tracking this at https://github.com/Azure/azure-cli/issues/5480
