### ISSUE TITLE
az login is spammy and doesn't tell me what I need to know

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#615]
`az login` appears to dump the internal json state stored after retrieving all of my subscriptions.

I don't need to see this raw JSON output. Rather, I do need to see the current active subscription and the subscription ids of all the subscriptions it imported so that I can immediately see if I'm targetting the wrong one and switch quickly.

**Comment by JasonRShaver** [comment]
This has been addressed, output (by default) looks like this now:

```
$ az login 
To sign in, use a web browser to open the page https://aka.ms/devicelogin. Enter the code xxxxxxxxx to authenticate.
Name                             IsDefault  TenantId                              State    EnvironmentName
-----------------------------  -----------  ------------------------------------  -------  -----------------
AzureCLI-Demo                            1  xxx  Enabled  AzureCloud
Java-TEST                                   xxx  Enabled  AzureCloud
My Internal Subscription                    xxx  Enabled  AzureCloud

```

**Comment by mayurid** [comment]
@JasonRShaver : I believe that's when the default output is set as table. //cc @yugangw-msft
