### ISSUE TITLE
cli-lint: "webapp deployment slot list" should deprecate the usages of '--ids'

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#6155]
Can't just strip it out as we have 196 usages in the last 6 months, so I am adding it into the linter_exclusions.yml
This issue tracks:
1. Use right deprecation logic 
2. Pull it out in future and also remove the associated exclusion.

//CC: @williexu  @tjprescott

**Comment by panchagnula** [comment]
@yugangw-msft do we need this to be active? Do we plan on removing this soon? Thank you.

**Comment by tjprescott** [comment]
Should remain active until `--ids` is removed or deprecated on that command.

**Comment by panchagnula** [comment]
thanks @tjprescott is this something we are planning for to be removed in the upcoming release?

**Comment by panchagnula** [comment]
@tjprescott i am mainly asking is because this is oldish issue & its currently tagged as 'Service Attention'  but still assigned to Yugang. If this is something our team should work would be happy to take care of it. Thank you.

**Comment by tjprescott** [comment]
@yugangw-msft are usages low enough to remove this?  If not, we (or they) should move forward with deprecating `--ids` on this command. That would be the best step to drive down usage.

**Comment by tjprescott** [comment]
@panchagnula if you guys wanted to take this up I don't think it would be a problem. 
https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#deprecating-commands-and-arguments

**Comment by panchagnula** [comment]
Assigning this to myself to track

**Comment by panchagnula** [comment]
Seems like a low hanging fruit we can take care of soon.
