### ISSUE TITLE
Unsupported orchestrator type Kubernetes for browse

### ISSUE THREAD

**Issue by Strandedpirate** [Azure/azure-cli#6158]
Cannot figure out why I'm getting this error. Just installed az cli and kubectl on a new Windows 10 machine. This works fine from other machines.

- az cli - v2.0.26
- kubectl - v1.8.1

```
> kubectl config current-context
qa-etchdesignermgmt

> az acs browse --name qa-kubecluster --resource-group qa-containerservice
Unsupported orchestrator type Kubernetes for browse

> kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:16:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by levidehaan** [comment]
I recently created a new acs instance running Kubernetes 1.10 and i get this error as well.

**Comment by Strandedpirate** [comment]
They broken something last year. I have found a workaround though. Just put the work kubernetes, all lower case, before the browse and it works.

az acs **kubernetes** browse --name qa-kubecluster --resource-group qa-containerservice
