### ISSUE TITLE
CosmosDB commands need  examples

### ISSUE THREAD

**Issue by samboustani** [Azure/azure-cli#6168]
Please add examples. I'm getting errors when running these commands.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da15197a-eca2-19d6-72e3-be853337a759
* Version Independent ID: eb84d467-86df-121e-3b04-66b499342f7f
* Content: [az cosmosdb database](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/database?view=azure-cli-latest#az-cosmosdb-database-show)
* Content Source: [src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_help.py)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by shurd** [comment]
Hi @samboustani thank you for bringing up this lack of examples for data plane operations. We are working on making the `database` command API-specific, so we are not planning on adding examples right now. If you have specific errors you need help resolving, provide the specific command and error message so I can look into it.

**Comment by shurd** [comment]
We are going to add some basic examples for `database` and `collection` to the documentation. We plan on having these examples available by mid-July. This documentation addition is being tracked by work item 450614. We do have some CLI examples in other places that show how to use specific arguments. For example, our [page on managing index policies](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-manage-indexing-policy#use-the-azure-cli) gives an example on using the CLI to achieve this.
