### ISSUE TITLE
Docs for the CLI don't show `--ids` or `--subscription`

### ISSUE THREAD

**Issue by williexu** [Azure/azure-cli#6170]
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by tjprescott** [comment]
Updated the issue to reflect that the global `--subscription` argument is also not shown for anything. @adewaleo work with @dend to determine whether this is a problem on our side or theirs.

**Comment by adewaleo** [comment]
It seems this issue has been resolved?
The docs show both --ids and --subscription for applicable commands.
See:
- [`az vm show`](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-show)
- [`az servicebus topic create`](https://docs.microsoft.com/en-us/cli/azure/servicebus/topic?view=azure-cli-latest#az-servicebus-topic-create)

Both of these commands have `--ids` and `--subscription` documented.

**Comment by williexu** [comment]
@adewaleo I believe its been fixed
