### ISSUE TITLE
Any plans to support querying cosmosdb collection using az cli ?

### ISSUE THREAD

**Issue by prashanthmadi** [Azure/azure-cli#6171]
Hi All,

Is there any plan to support querying cosmos db collection via this awesome tool in future ?

I have been through code and i don't see anything here
https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/commands.py

and also documentation at below link.
https://docs.microsoft.com/en-us/cli/azure/cosmosdb?view=azure-cli-latest

**Comment by shurd** [comment]
Hi @prashanthmadi, we are not planning on adding the ability to access data via the CLI at this time. We have other SDKs that deal specifically with data stored in accounts. You can see the options for each API type here: https://docs.microsoft.com/en-us/azure/cosmos-db/
