### ISSUE TITLE
there is no --no-cache parameter

### ISSUE THREAD

**Issue by gabbyGuo** [Azure/azure-cli#6182]
recently meeting an issue when run "az storage container create"
when run with proxy , then there is an issue with proxy layer cache.The MAC signature not the same as any computed signature.
if there is no no-cache parameter, how to work with this one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adcba5ed-e693-6345-2c1b-c17422d7b8f9
* Version Independent ID: 58297400-b777-6868-1687-0af3a512a16f
* Content: [az storage container](https://docs.microsoft.com/en-us/cli/azure/storage/container?view=azure-cli-latest#az-storage-container-create)
* Content Source: [src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by williexu** [comment]
Closing this, will reopen if more info comes up.
