### ISSUE TITLE
`az webapp deployment user set` does not check deployment user name

### ISSUE THREAD

**Issue by JohnReeson** [Azure/azure-cli#6185]
In portal, the limitation on deployment user name is shown clearly in Deployment Credential.
> The user name can contain only letters, numbers, hyphens and underscores. The user name must start with a letter.

While command `az webapp deployment user set` does not check whether deployment user name accord with these rules. This may cause deployment url can't be resolved correctly and lead to deployment failure.

---

### Environment summary

Install Method (installed in azure portal) / CLI version (`2.0.31`) / Shell Type (bash)

**Comment by tjprescott** [comment]
What error message do you get when you try to do this?

**Comment by JohnReeson** [comment]
@tjprescott I deploy a web app using local git according to this [tutorial](https://docs.microsoft.com/en-us/azure/app-service/app-service-deploy-local-git#create-a-deployment-user).

When using `az webapp deployment user set ` to create a deployment user, I used `john@reeson.com` as user name. Then Cli showed me the git url without any error. 

The url is like this `https://john@reeson.com@johntest.scm.azurewebsites.net/johntest.git`. I used this url to deploy the app by git but it said: 

> unable to access {my git url}: Couldn't resolve host 'reeson.com@johntest.scm.azurewebsites.net'

Then I find that in portal there's explicit requirement for user name--`can only contain letters, numbers, hyphens and underscores`. After renaming the user, it worked.

So if I understand correctly, it's not expected that Cli doesn't check user name for invalid sign like '@'.

**Comment by tjprescott** [comment]
Generally no. In this case, the service should return an actionable error. @panchagnula might consider validating this on the client side if a service fix is not expected quickly.

**Comment by panchagnula** [comment]
we might need to emulate portal validation on the cli client side for this - i am going to test this with the latest CLI version to verify if the API return a useful error message or not.

**Comment by panchagnula** [comment]
@JohnReeson looking at the validation from the API for username it throws an exception only if the value is empty or >60 characters - there are other validations the API does, that we don't plan on moving to the CLI client. if you are still seeing failures with this command please run with --debug flag, that should give you details on what is causing the error. Closing this as won't fix.
