### ISSUE TITLE
--expand parameter causes the CLI to timeout, send invalid requests, and generally does not work.

### ISSUE THREAD

**Issue by binderjoe** [Azure/azure-cli#62]
The --expand parameter seems to generally not work.  For example, 
`az vm get --resourcegroup foo --vm_name bar --expand`
will hang for a long time and then timeout:
`Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/172d64a6-0b5e-48e5-a735-fc2df7016da9/resourceGroups/test/providers/Microsoft.Compute/virtualMachines/test?api-version=2015-06-15&$expand= (Caused by ResponseError('too many 503 error responses',))`

.  If you pass a value for expand:
`az vm get --resourcegroup foo --vm_name bar --expand statuses`

An invalid request is sent:
The request URL is not valid.

**Comment by JasonRShaver** [comment]
Example from recent build:
```
jasonsha@JasonShaMBP: ~ $ az vm show -g foo -n bar --expand asdf
expand must be type InstanceViewTypes.
Traceback (most recent call last):
  File "/usr/local/az/envs/default/lib/python2.7/site-packages/azure/cli/main.py", line 50, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/az/envs/default/lib/python2.7/site-packages/azure/cli/application.py", line 103, in execute
    result = args.func(params)
  File "/usr/local/az/envs/default/lib/python2.7/site-packages/azure/cli/commands/__init__.py", line 204, in _execute_command
    result = operation(client, **kwargs) if client else operation(**kwargs)
  File "/usr/local/az/envs/default/lib/python2.7/site-packages/azure/mgmt/compute/operations/virtual_machines_operations.py", line 356, in get
    query_parameters['$expand'] = self._serialize.query("expand", expand, 'InstanceViewTypes')
  File "/usr/local/az/envs/default/lib/python2.7/site-packages/msrest/serialization.py", line 352, in query
    raise TypeError("{} must be type {}.".format(name, data_type))
TypeError: expand must be type InstanceViewTypes.
```

**Comment by BurtBiel** [comment]
It only works with instanceView, perhaps we could make expand a flag and auto-expand instanceView

**Comment by johanste** [comment]
The SDK has been updated to (at least for `vm show`) only support the string instanceView. The type attribute of the parameter should be updated.

**Comment by JasonRShaver** [comment]
Cleaning up old and likely to be abandoned issues, please re-open if this issue still exists
Cleaning up old and likely to be abandoned issues, please re-open if this issue still exists

**Comment by JasonRShaver** [comment]
Cleanse re-open if this issue still exists

**Comment by JasonRShaver** [comment]
Cleaning up old issues, reopen if this is still active.
