### ISSUE TITLE
How to set unique keys using the CLI when creating a collection ?

### ISSUE THREAD

**Issue by rfigueroa** [Azure/azure-cli#6206]
When using the Azure portal to create a DocumentDB Collections you can add a unique key, how can yo do that using the Azure cli ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d791e10-4181-cf15-1398-499eb0918c9c
* Version Independent ID: 2e5f864d-29bd-da4f-b964-a87a39f988c0
* Content: [az cosmosdb collection](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/collection?view=azure-cli-latest#az-cosmosdb-collection-create)
* Content Source: [src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_help.py)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by sugarjig** [comment]
I'm also interested in the answer to this question. It doesn't appear that there is a way to automate the process of creating unique keys.

**Comment by Izharsa** [comment]
+1 unique keys

**Comment by rventuri76** [comment]
So it seems that this is still not possible. Any plan to add this?

**Comment by MarkDordoy** [comment]
Any update on this? 

The only way i can find outside of the portal is making a call direct to the api. 

Ideally i'd like a way to do this via powershell or az cli.

**Comment by moderakh** [comment]
@tjprescott please assign the data plane issues (including this one) to @christopheranderson

**Comment by shurd** [comment]
Hi all, right now it is not possible to add unique keys when creating a collection via the CLI. We do not plan on adding this functionality to the CLI at this time. You can use one of our [other SDKs](https://docs.microsoft.com/en-us/azure/cosmos-db/) to create the unique keys right now. 

We recently added support to perform this operation through our resource provider. You can make direct request with the [uniqueKeyPolicy in the body](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2015-04-08/examples/CosmosDBSqlContainerCreateUpdate.json). You can also use the [azure-mgmt-cosmosdb python package](https://pypi.org/project/azure-mgmt-cosmosdb/), which allows you to [specify this policy](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/sql_container_resource.py) when creating a collection.
