### ISSUE TITLE
Azure Application Gateway : SOAP API  issue

### ISSUE THREAD

**Issue by luvvishu23** [Azure/azure-cli#6214]
I have deployed a Virtual Machine scaleset with an application gateway. VMs in VMSS has a soap api configured. Now when I download WSDL for my soap api by going through application gateway's DNS name, for soap:addresslocation tag in WSDL it gives privateip of VM as url for example https:\\10.1.0.9:443\servicetag while if I access same API WSDL directly by using DNS name of VM it gives same URL in this for :  https\\<VM DNS name>\servicetag.

Please tell me what is causing this behaviour.

Also while googling I found out that this could be due X-forward setting. Is there is any way to modify these settings . Also How to see what settings are been sent 

MY VMs are centos with Tomcat server

**Comment by tjprescott** [comment]
What CLI command are you trying to use?

**Comment by luvvishu23** [comment]
Got it resolved this was happening as I had -pickhostnamefrombackend flag true due to which it is taking private ip of the backend VM . For this issue I set the hostname of application gateway to its fqdn
