### ISSUE TITLE
Unable to login to AzureCloud using latest version of azure-cli 2.0.31

### ISSUE THREAD

**Issue by radhikagupta5** [Azure/azure-cli#6221]
Installed CLI with these instructions:
# Instructions from https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest

AZ_REPO=$(lsb_release -cs)
echo "Installing Azure CLI from $AZ_REPO"
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
sudo apt-key adv --keyserver packages.microsoft.com --recv-keys 52E16F86FEE04B979B07E28DB02C46DF417A0893
sudo apt-get install apt-transport-https -y
sudo apt-get update -y 
sudo apt-get install azure-cli -y

Register to AzureCloud works
Login to AzureCloud using following fails:
az login \
  --service-principal \
  --username $SPN_CLIENT_ID \
  --password $SPN_CLIENT_SECRET \
  --tenant $TENANT_ID

Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

If I bypass SSL auth by doing following this works:
export ADAL_PYTHON_SSL_NO_VERIFY=1 
export AZURE_CLI_DISABLE_CONNECTION_VERIFICATION=1

**Comment by bganapa** [comment]
@radhikagupta5 Can you please add az --version output and the OS details

**Comment by radhikagupta5** [comment]
az --version output:

azure-cli (2.0.31)

acr (2.0.23)
acs (2.0.31)
advisor (0.5.1)
appservice (0.1.31)
backup (1.1.1)
batch (3.2.0)
batchai (0.2.0)
billing (0.1.8)
cdn (0.0.14)
cloud (2.0.13)
cognitiveservices (0.1.12)
command-modules-nspkg (2.0.1)
configure (2.0.15)
consumption (0.3.0)
container (0.1.22)
core (2.0.31)
cosmosdb (0.1.20)
dla (0.0.19)
dls (0.0.21)
eventgrid (0.1.12)
eventhubs (0.1.2)
extension (0.0.12)
feedback (2.1.1)
find (0.2.9)
interactive (0.3.19)
iot (0.1.19)
keyvault (2.0.21)
lab (0.0.21)
monitor (0.1.5)
network (2.0.28)
nspkg (3.0.2)
profile (2.0.22)
rdbms (0.2.1)
redis (0.2.12)
reservations (0.1.2)
resource (2.0.27)
role (2.0.22)
servicebus (0.1.2)
servicefabric (0.0.12)
sql (2.0.25)
storage (2.0.31)
vm (2.0.30)

Python location '/opt/az/bin/python3'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Apr  6 2018, 15:16:25)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by radhikagupta5** [comment]
uname -a (This is on following Ubuntu 16.04.201802220)
Linux vmd-k8s-13586 4.13.0-1011-azure #14-Ubuntu SMP Thu Feb 15 16:15:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by knithinc** [comment]
@tjprescott may I know if someone is looking into this issue?

**Comment by tjprescott** [comment]
@yugangw-msft can you take a look?

**Comment by yugangw-msft** [comment]
@radhikagupta5 , likely you are running behind a proxy with unsigned certificate. Please cross check #5099.
To avoid allowing any unsigned certificate, you can add your proxy's certificate to the CA root through the env var of `REQUESTS_CA_BUNDLE`

**Comment by viananth** [comment]
This was an issue with placing the cert in correct Python store. 
"apt-get" install way of AzureCLI places python in a different location than "curl" way of installation. We were able to resolve this by placing the cert in correct store. Thanks folks!

**Comment by bganapa** [comment]
@radhikagupta5 please close this issue
