### ISSUE TITLE
Cannot set reverse fqdn for public ip without dnsSettings

### ISSUE THREAD

**Issue by Trepliev** [Azure/azure-cli#6232]
If I create public ip (az network public-ip create ...) without RR dns like abcdef I am not able to set PTR record because the whole dnsSettings section is missing. I need to create/update (az network public-ip update --dns-name abcdef -n NAMEOFIP -g RGROUP) the IP name first and after this step I am able to set PTR.

Err:
The domain name label in the dnsSettings section of the public IP address NAMEOFIP is null or empty. If a dnsSettings section exists, its domain name label must not be null or empty.

Env:
mc os x high sierra with the latest updates
azure-cli (2.0.31)

The solution could be
a) always create RR in the creating phase (do not allow to create IP without it)
b) add random name to the creation phase in case the user used none
c) allow to have empty RR/missing dnsSettings section and create it in the PTR process creation

**Comment by adewaleo** [comment]
So according to this azure reverse DNS [doc](https://docs.microsoft.com/en-us/azure/dns/dns-reverse-dns-for-azure-services#azure-cli-20), one is able to add reverse DNS to an existing PublicIPAddress that does not already have a DNS name. 

You have to specify both the reverse-fqdn and the DNS name.

So if you previously ran:

`az network public-ip create --name testIp -g $RG`

You can add a reverse fqdn in one command by running the following:

```
az network public-ip update -g $RG --name testIp --reverse-fqdn yourdnsname.westus.cloudapp.azure.com --dns-name yourdnsname
```
Closing this. Let us know if you have any more questions.
