### ISSUE TITLE
ubuntu image + waagent = bash issue

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#6233]
I'm trying to deploy ubuntu image via waagent, since cloud-init doesn't work with VHD file (permissions denied).
I was able to overcome cloud-init issue in waagent settings and now I can deploy ubuntu VM both from imaged and VHD files.
There's still one issue however: waagent creates new user 'azureuser' with empty shell field in /etc/passwd, which defaults to /bin/sh instead of /bin/bash

Could you pls. help me with that?
There's no such 'bash' issue with CentOS/RHEL/OEL/Debian.

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```
MSI
azure-cli (2.0.31)
Microsoft Windows [Version 10.0.17110.1000]
Bash on Windows

**Comment by tjprescott** [comment]
This sounds like an issue with WAAgent, not the CLI.  Please post your issue here:
https://github.com/Azure/WALinuxAgent
