### ISSUE TITLE
Add login refresh command

### ISSUE THREAD

**Issue by perbergland** [Azure/azure-cli#6234]
The ~/.azure/accessTokens.json file that is generated as a result of az login (and read by e.g. the azurerm terraform module) contains refresh_token sections. To my understanding this means that when the access_tokens have expired, it should be possible to use the refresh_tokens to get new access tokens and avoid the need to actually log in again (which is a bit cumbersome for the manual login step that requires a browser visit).

My suggestion therefore is to add a flag "-refresh" to login and implement this.

CLI Version
2.0.31

OS Version
Windows 10 Pro, Version 1709

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

**Comment by perbergland** [comment]
OK now I understand more - I was after the same thing as here:
https://github.com/terraform-providers/terraform-provider-azurerm/issues/502

Turns out there already is an `az account list --refresh` that probably does what I want.

**Comment by tjprescott** [comment]
Thanks for the suggestion @perbergland. @yugangw-msft has the most knowledge on this to make this decision.

**Comment by yugangw-msft** [comment]
Please use `az account get-access-token`. CLI users would never need this function as CLI takes care of the token refreshing automatically. Due to security concerns, enabling external tools to share the creds is not a goal for CLI even though I made some limited changes to make it feasible, but that is pretty much the most i can do.

**Comment by andre-qumulo** [comment]
@yugangw-msft `az account get-access-token` doesn't seem to refresh the user's group membership, any ideas why not?
