### ISSUE TITLE
az container create: spec for --ports unclear

### ISSUE THREAD

**Issue by revodavid** [Azure/azure-cli#6235]
The reference for the --ports argument does not specify how to open more than one port. (Multiple port numbers can be separated by spaces.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e5d1da7-7c4f-c9e6-e4b9-a30407675acf
* Version Independent ID: ba32e12d-8283-f980-e1d0-1ca2a75a5152
* Content: [az container](https://docs.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest#az-container-create)
* Content Source: [src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jijiechen** [comment]
Um, the `--ports` accepts a maximum of 5 ports, and it seems does not support mapping --just opening a same port that exposed from the container.

**Comment by gigadie** [comment]
that is something they should add asap to make this really powerfull..
something like `--ports 80:8080 443:8443`

**Comment by samkreter** [comment]
Port mapping is a commonly asked for feature. If you are interested up vote it here to make sure its higher priority: https://feedback.azure.com/forums/602224-azure-container-instances

**Comment by tjprescott** [comment]
The text should read "Space-separated list of ..."

**Comment by valdisiljuconoks** [comment]
why description change for the `ports` argument is not yet changed?

**Comment by jayeshsk** [comment]
> The text should read "Space-separated list of ..."

@tjprescott could you please mention the documentation where the change is to be made?

**Comment by rayoef** [comment]
Thank you for your feedback on the documentation. The description for --ports includes that it should be a space-separated list. 
#please-close
