### ISSUE TITLE
how to prepare VHD for publishing in Azure Marketplace

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#6236]
the topic is not documented as a solid example, looking at different source is time-consuming and error-prone
I have such experience - together we can do it - pls. let me know if you find it useful
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by tjprescott** [comment]
https://docs.microsoft.com/en-us/azure/marketplace-publishing/marketplace-publishing-vm-image-creation

This repo is intended only for CLI-related issues, not general help/questions. Please refrain from posting general questions here.

**Comment by tjprescott** [comment]
@alexeyshishkin01 that is great feedback, but this repo is not the place to post it because there is no action we can take on the CLI side to address it.  You should leave your feedback directly on the linked blog post so it can be improved.
