### ISSUE TITLE
Tip: Use your Azure CLI login session to connect to Active Directory and use the AzureAD cmdletes

### ISSUE THREAD

**Issue by perbergland** [Azure/azure-cli#6242]
I got tired of having to log in to Azure in so many different ways since all tooling have some unique functionality (Azure CLI, AzureAD for PS, AzureRM for PS) and when I found the get-access-token command here I got intrigued and actually managed to log in to the AD Graph.

Here's some PS code:

$subscriptions = (az account list -o json 2> $null | ConvertFrom-Json)
# Get a token for AD (Graph)
$adtoken_container = (az account get-access-token --resource "https://graph.windows.net/ " | ConvertFrom-Json)
$adtoken = $adtoken_container.accessToken

$first_sub = $subscriptions[0]
$user_name = $first_sub.user.name
$tenant = $first_sub.tenantId

Connect-AzureAD -aadaccesstoken "$adtoken" -accountid "$user_name" -tenantid "$tenant" 

Get-AzureADUser -top 1 # proves that it worked

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9abfaa54-0895-29f7-f3bb-ff604912b2ac
* Version Independent ID: d1ff3478-8a86-59e4-62ef-449900132a67
* Content: [az account](https://docs.microsoft.com/en-us/cli/azure/account?view=azure-cli-latest#az-account-get-access-token)
* Content Source: [src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_help.py)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Hi @perbergland thanks for sharing!  Our system creates a GitHub issue for comments since most tend to be "xyz doesn't work" so I will close this issue (but your comment will still remain to benefit other users).

**Comment by rtbins** [comment]
Complete login workflow (using device code)

$login_creds = (az login --use-device-code |  ConvertFrom-Json)
$adtoken_container = (az account get-access-token --resource "https://graph.windows.net/ " | ConvertFrom-Json)

$adtoken = $adtoken_container.accessToken
Connect-AzureAD -aadaccesstoken "$adtoken" -accountid  $login_creds.user.name  -tenantid $login_creds.tenantId
Get-AzureADUser -top 1
