### ISSUE TITLE
az network nic update doesnot have the option to update internaldomainsuffix 

### ISSUE THREAD

**Issue by cognsom** [Azure/azure-cli#6243]
az network nic update doesnot have the option to update internaldomainsuffix 
---

 

```
```

**Comment by tjprescott** [comment]
Hi @cognsom thanks for pointing this out. We'll schedule it for a future release. In the meantime, you should be able to set the property using the following:

`--set dnsSettings.internalDomainNameSuffix='whatever'`

**Comment by cognsom** [comment]
Thanks for the reply . Unfortunately the command which you have given is not reflecting any changes after the execution. 
i am not able to change the internaldomainsuffix . It is still showing me the default domainsuffix

**Comment by tjprescott** [comment]
If that is the case, it is entirely possible that the internal domain name suffix cannot be changed.

**Comment by tjprescott** [comment]
@cognsom I believe this is a simply a service-limitation that these values can be set or changed. I've opened issue https://github.com/Azure/azure-rest-api-specs/issues/3033 to have this reflected in the API specs.

As there is nothing we can do from the CLI side to address this, I'm closing this issue.
