### ISSUE TITLE
Application Gateway missing connection draining

### ISSUE THREAD

**Issue by amitsriva** [Azure/azure-cli#6247]
Drain enabled parameter - present in swagger - is missing in CLI.
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by tjprescott** [comment]
This is deliberate. To disable connection draining, you choose a timeout of 0. 

```
--connection-draining-timeout        : The time in seconds after a backend server is removed
                                           during which on open connection remains active. Range: 0
                                           (disabled) to 3600.
```
