### ISSUE TITLE
telemetry hangs during az-cli invocations

### ISSUE THREAD

**Issue by ambakshi** [Azure/azure-cli#6248]
---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
install from https://packages.microsoft.com/yumrepos/azure-cli , via yum
azure-cli-2.0.31-1.el7.x86_64
Centos 7.4 latest
bash
AZURE_STORAGE_KEY and AZURE_STORAGE_ACCOUNT env vars are set
```
I'm seeing random hangs in telemetry.py while executing az commands running in a CustomScript Extension durinng initialization. I don't see an easy way to disable telemetry via env var or cli, except to create the ~/.azure/config file. Any chance we can add an environment variable or be able to configure this programatically? `az configure` is interactive. I could clobber the existing config file, or do something more complex and fix an existing one.

**Comment by derekbekoe** [comment]
See https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest#cli-configuration-values-and-environment-variables

**Comment by aog2000a** [comment]
Same problem here. I now see that this extra connection latency is part of the reason why downloading many tiny blobs takes ages.

Copying from #6265 : I wonder why should the default be to upload telemetry data (what the hell is that for???) when i am just trying to download a blob. This doesn't feel good in "open source" software... guys, why are you uploading OS version, Python version and machine id strings to Azure?? Bad MS habits? I'm pretty upset as you notice...
