### ISSUE TITLE
Add command support for LogAnalytics in OMS

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#6249]
Rest API:
     https://docs.microsoft.com/en-us/rest/api/loganalytics/

Swagger;
    https://github.com/Azure/azure-rest-api-specs/tree/master/specification/operationalinsights

Posh:
   https://github.com/Azure/azure-powershell/tree/preview/src/ResourceManager/OperationalInsights

**Comment by michaelnemtsev** [comment]
This would be very useful support for automation scenarios, as it is blocking many CI use cases now

**Comment by yonzhan** [comment]
@MyronFanQiu  we are working on this.

**Comment by yonzhan** [comment]
Done
