### ISSUE TITLE
Support more vmss creation scenarios

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#625]
Default VMSS Create:
if the user doesn't specify anything, I think that there should be an LB with public IP and inbound NAT rules for ssh/rdp; there should only be 1 pool (size 120); no round-robin rules, ensure subnet supports 120 vms.

Additional VMSS Create options
* do not create public ip
* reference existing Public IP, LB (don't think we need NAT rules or pools as that is part of the existing LB)

**Comment by BurtBiel** [comment]
Closing, this is all implemented @JasonRShaver @mayurid
