### ISSUE TITLE
[service] Non-provisioned VM blocks Image deletion; Image doesn't take a lease on the backing blob

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#6254]
I found what look like at least two different service issues today.

Basically, I've got an Image that I can't delete, and whose backing blob no longer exists. Neither of these seem like situations I should be able to get into.

Note: I think some of this is specifically because the VM I booted didn't report successful provisioning to the platform, so Azure thinks the VM is still booting. It's unclear though, why this would block the Image deletion. Presumably at this time, the Image was copied to a new blob for the OS Disk... but maybe there are backend COW optimizations...?

## Repro

1. Create an RG "aznixos"
2. Create a Storage account and container in that RG
3. Upload a VHD to the storage container
4. Make an "Image" from the VHD Blob.
5. Create a new RG "colemick-nixos-20180423"
6. Create a VM using the Image from the other resource group
7. Later, decide you don't want that image anymore.
8. Delete the `aznixos` resource group
---

**Expected**: The resource group is deleted.

**Alternative Expectation**: The resource group is NOT deleted, because the Image took a lease on the backing blob, which would then prevent the 

**Actual**: The RG fails to delete after sometime (an hour?). Manually attempting to delete the Image results in this error: (which is amusing, at this point in time, the backing blob for the Image doesn't exist, so the Image is probably useless anyway)

```
Operation Not Allowed
Operation 'Image Delete' is not allowed since the Virtual Machines 'colemick-nixosdev' are being provisioned using the Image 'nixos-image-16.09.1694.019dcc3-x86_64-linux-vhd'.
```

### Issues

From my deduction, it seems like there might be three issues:

1. Why didn't the Image take a lease out on the blob?
2. Why does the VM block image deletion? It appears that a user can block Image deletion by booting a VM that doesn't complete provisionig.
3. Why does ARM just keep retrying this delete?

While looking into this, I've noticed other oddities:

1. I'd noticed this literally all the time when using Azure, but hte Activity Log is completely unreliable. There was no evidence of my attempt to delete the `aznixos` group in the Activity Log, despite having done in multiple times. I would've assumed the Activity Log accuracy would be important, but it just doesn't seem that way.

2. The resource group just reverted back to "Success!" after the deletion failed. That just doesn't seem quite right.

cc: @yugangw-msft

**Comment by yugangw-msft** [comment]
I will try to repro at my end. 2 things maybe you can clarify here(hope you can still remember the thing happened at 9 days ago)
1. Regarding `Make an "Image" from the VHD Blob.`, I assume you use `az image create` to create it, right?
2. Regarding `Create a VM using the Image`, did the VM successfully get created? I mean if you use `az vm show`, did the provision state showed as "Success"? 

My guess is the `vm` was still holding to the image for reasons to be figure out here. If you delete the vm first, then  deleting `aznixos` might go through.

**Comment by colemickens** [comment]
1. Yes, that is correct. And the only way I know to do that for now, is to create a storage account/container first, then put the VHD there. (I had for a while, but have since removed the "create an MD" step in between the upload and th `az image create`. It doesn't seem necessary and I need a storage account anyway since I'm uploading the actual raw VHD file myself.)

2. Yes, the VM was created and I was happily using it for a few days. However, the images I'm creating have a ~buggy agent. They don't always report provisioning. When I was in the Portal, I noticed that the VM was marked specially to indicate this. Further, the error message hints at the image being locked due to a VM still being in provisionig.

(I'm wondering outloud, maybe the underlying blob is locked due to COW optimizations for VMs booted from the images...)

**Comment by yugangw-msft** [comment]
please reactivate once you get more information

**Comment by colemickens** [comment]
It was a custom built image that didn't need provisioning and didn't
include the agent. I think that was the cause, since the platform thought
it never finished provisioning. Anyway, I'm no longer using Azure so we can
leave this closed.
