### ISSUE TITLE
upload-batch interpets json files as content-type application/octet-stream

### ISSUE THREAD

**Issue by markuspelnens** [Azure/azure-cli#6257]
when uploading files (such as a react app) to an azure blob container, all json files (such as manifest.json) get interpreted as having content type application/octet-stream. The expected content-type would be application/json

because of this, all json files are not correctly loaded by the browser

**Comment by williexu** [comment]
Thanks for catching this. We are looking into why this happens.
For now, please use the `--pattern` argument to select for `*.json` files and specify the content type using the `--content-type`.

**Comment by troydai** [comment]
We do have a mechanism to "guess" the content type in batch-upload. The implementation relies on [mimetypes](https://docs.python.org/3.6/library/mimetypes.html) to interpret the content type base on the file name. It doesn't returns `application/json` type of the `*.json` file. We will look into how to improve this aspect of the feature.

**Comment by markuspelnens** [comment]
Thanks. Would appreciate feedback as soon as it's fixed

**Comment by markuspelnens** [comment]
By the way, using --pattern, would mean I have to write a batch-upload for every file type (js, json, css, ico etc). This makes it impossible to use batch-upload for website assets. I hope you get around to fixing this soon

**Comment by troydai** [comment]
Thanks for the advice for a valid scenario. We're looking into changes which can improve the experience.

**Comment by troydai** [comment]
@markuspelnens , we will make sure the upload command correctly interrupt `*.json` and `*.js` files' content type correctly in this sprint. Please let us know if there are other files cause trouble in your scenario.

Additionally, we will work out a solution allows users to customize the content type match in batch. The feature will come in later next sprint. Thanks.
