### ISSUE TITLE
Add owners to app registration (AzureAD App)

### ISSUE THREAD

**Issue by idgazit** [Azure/azure-cli#6258]
I would like to be able to add/update/remove owners of an app registration.
similarly to the method in Powershell.
https://docs.microsoft.com/en-us/powershell/module/azuread/add-azureadapplicationowner?view=azureadps-2.0

**Comment by yugangw-msft** [comment]
//CC: @mayurid 
This is related with the on-going Graph Spec improvement so to support getting `owner`'s service principals
