### ISSUE TITLE
Credential sharing between Node and Python CLI

### ISSUE THREAD

**Issue by mayurid** [Azure/azure-cli#627]

**Comment by mayurid** [comment]
1) Complete SDL (Jason)
2) Once SDL is completed, we will need to make a quick change in the Node CLI to use File by default.

**Comment by mayurid** [comment]
@JasonRShaver : Can we prioritize this to get it in for Sprint 1 (no later than Sprint 2) as I would like to have the work for Node CLI done for the upcoming release (which is early September)

**Comment by mayurid** [comment]
@yugangw-msft : We are unblocked here now

**Comment by yugangw-msft** [comment]
all settled
