### ISSUE TITLE
Cosmos DB database and collection create commands are not idempotent

### ISSUE THREAD

**Issue by johndowns** [Azure/azure-cli#6272]
The Cosmos DB integration in the Azure CLI has some inconsistent behaviour when compared to the Storage provider, around how creating databases and collections work.

In Storage, commands like `az storage collection create` are idempotent - if the collection already exists then the command doesn't fail, but instead returns a JSON object indicating that nothing was created.

In Cosmos DB though, executing `az cosmosdb database create` or `az cosmosdb collection create` will fail with a process exit code if the database/collection already exists.

In Storage, there is a `--fail-on-error` flag that we can set if we want an error to be thrown. I would much prefer that Cosmos DB have the same behaviour - no error by default, but an error if explicitly requested. This makes it much easier to integrate the Azure CLI steps into build and release pipelines. Having error exit codes for expected states like this can be very difficult to manage with many build and release tools.

**Comment by jzworkman** [comment]
Any updates on this issue?  I am currently trying to get a build step in our CI pipeline to make sure that a cosmos db collection is created if it doesn't exist(as it is required for a step further down the release pipeline).  Currently this is not possibly via azure cli and requires maintaining multiple build steps/captured output to first check if the collection exists and then conditionally call the next build step based on that output.

**Comment by dpbevin** [comment]
I've just noticed this too.

**Comment by shurd** [comment]
Hi @johndowns thank you for raising this issue. We are currently working on changing the way databases and collections are accessed by the CLI. Currently, the CLI uses "azure-cosmos", which is a data-plane python package. Soon, the CLI will instead access collections and databases through our resource provider. 

When this change is made, the collection create command will be idempotent. The implementation will be very similar to the current implementation of creating a database account, which does not throw an error when the account already exists. The target date for completion of this work item (416566) is September. We will keep you updated as work progresses.

**Comment by shurd** [comment]
Hi, in CLI version 2.0.71, we released a preview version of the new database and collection management commands. These commands are idempotent and do not throw an error if the resource already exists. Each API has their own command group.

For example, ```az cosmosdb mongodb database create``` returns the state of the database resource when run multiple times.
