### ISSUE TITLE
Add `Scheduler` service to azure-cli

### ISSUE THREAD

**Issue by iyerusad** [Azure/azure-cli#6278]
azure-cli doesn't appear to currently support `Scheduler` service related commands. Looks like service has been around for ~2 years now.

`Scheduler` Service: https://docs.microsoft.com/en-us/azure/scheduler/scheduler-intro
REST API: https://msdn.microsoft.com/library/mt629143.aspx
Azure Powershell: https://docs.microsoft.com/en-us/azure/scheduler/scheduler-powershell-reference

**Comment by tjprescott** [comment]
@achandmsft can you reach out to the service team regarding any plans for this?

**Comment by achandmsft** [comment]
Hi @iyerusad, 
Thanks for your feedback. Azure Logic Apps fully replaces Scheduler capabilities, and Scheduler will be retired as a standalone service on September 30, 2019. For more details, please refer to - [Azure Scheduler will retire on September 30 2019](https://azure.microsoft.com/en-us/updates/azure-scheduler-will-retire-on-september-30-2019/) 

If you are interested in Logic Apps support in CLI, please create a new issue for the same. I am closing this one based on the above. 

Thanks,
Arun Chandrasekhar
Principal Program Manager (Azure CLI)
