### ISSUE TITLE
Multiple 'az vm' examples use invalid syntax `--ids {vms_ids}`

### ISSUE THREAD

**Issue by stewartadam** [Azure/azure-cli#6281]
Likely `--ids "$vms_ids"` or `--ids "${vm_ids}"` was intended. Variables with spaces in them should be quoted an a `$` is required for variable subsitution in Bash.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 152b549b-d4b3-13e5-081c-c604b6e4d89e
* Version Independent ID: 3f79be78-ce75-ad31-304b-bad7d475ec9e
* Content: [az vm](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-stop)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
`--ids {vms_ids}` is simply intended to be a placeholder for whatever value(s) you supply. It isn't intended to be a valid value by itself nor a shell-specific syntax. 
The pattern is used commonly throughout the CLI examples, not just for VM. If we decide to remove it (which we are strongly considering), we will do them all en-masse.

**Comment by stewartadam** [comment]
Why not just add the `$` then to make it a fully functional example, like several of the other help strings? It's counter intuitive to have functional examples all over except for `az vm`. For example here, bash substitution is used instead of a placeholder:
https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py#L41
