### ISSUE TITLE
Azure StreamAnalytics

### ISSUE THREAD

**Issue by boredom2** [Azure/azure-cli#6296]
Hi there,

is it possible to support Azure StreamAnalytics in Azure CLI?
There is currently no Way (for our Setup) to monitor the Jobs there without the Portal, we would be happy to automate this with Azure CLI.
Thanks!

**Comment by tjprescott** [comment]
https://azure.microsoft.com/en-us/services/stream-analytics/

@achandmsft can we reach out to the IoT folks and see if they own this service? If they don't, they may know who does.

**Comment by chriswue** [comment]
Yes, it seems like an oversight to not have it included. It's also been raised here more than 18 months ago https://feedback.azure.com/forums/270577-stream-analytics/suggestions/33680929-allow-creating-and-configuring-stream-analytics-fr 

The tooling has become unfortunately somewhat inconsistent (streamanalytics only supported on powershell while functionapps are only supported via az cli) which makes life a bit of a PITA. Would be nice to have one tool that has complete support

**Comment by MyronFanQiu** [comment]
@boredom2 Hi. We already supported this service. https://github.com/Azure/azure-cli-extensions/blob/master/src/stream-analytics/README.md
