### ISSUE TITLE
webapp:Add support to disable FTP & force FTPS for webapp & functionapp

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-cli#6297]
Navigate to the site -> config -> web node.    Toward the bottom of the json pane, they should see ftpsState property.   The default is AllAllowed.  They can try to change  to FtpsOnly or Disabled.   Hopefully, these should be self-explanatory.
 
![image](https://user-images.githubusercontent.com/13839372/39674937-8ac59694-5108-11e8-9cb1-a1b786ff2691.png)

**Comment by jiimaho** [comment]
Any plans on when this feature will be released?

**Comment by panchagnula** [comment]
we are planning to have this available with our upcoming release
