### ISSUE TITLE
Documented, Tested Examples of Idempotent Resource Creation

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#6298]
In light of #5006, I think the community would benefit greatly from having canonical examples of how to write scripts to do things like "ensure resources exist".

These types of scripts are used all over the place, and having a documented method for idempotent resource creation is table stakes, in my opinion.

Further, I've been personally broken by changes in the CLI, due to the fact that there was either no guidance around this, no testing around it, or both.

Additionally, someone on Twitter indicated that I might be better off using `az resource show` (rather than `az [resource] show` as it would then be more likely to be consistent about how it handles 404s. Which is a great point, and would be a great thing to see written down in some guidance and example bash scripts.

(Apologies if these such examples exist, I've not been able to find them yet!)

**Comment by tjprescott** [comment]
Most create commands are idempotent so that you can just always run the create command to ensure it exists. There are exceptions to this (unfortunately) due to services who raise an error if a you attempt to PUT on something that already exists (even if the payload is the same).

Otherwise, I'd defer to @johanste on this topic.

**Comment by johanste** [comment]
What @tjprescott said. For ARM control plane operations, the platform is generally using PUT as the only means for resource creates. Which is inherently idempotent. Which means that our create commands are expected to be idempotent. Which also has the benefit of ensuring that the resource not only exists, but that it is also in the state you expect (e.g. having a network resource in the wrong location probably won't help - you probably want your script to fail or correct the existing resource at that point). The main drawback is performance for some resources (in theory, it should be a no-op if the resource already exists in the state indicated by the request - in practice, less so). 

The pattern we originally wanted to follow was to have a 'create if not exists' flag on the create command. However, unfortunately, it has never been a requirement for an Azure resource provider to provide support for etags/if-match/if-none-match headers, which means that this support is somewhat spotty (we are pushing to get it included in the next rev of the Azure Resource Provider contract - not sure if it will make it or not). We could (and still can) implement this with a GET to determine if the resource exists beforehand modulo the race condition introduced if the resource provider doesn't support etags/if-non-match. 

Thoughts?

**Comment by colemickens** [comment]
Closing for now due to #6740. Thanks.
