### ISSUE TITLE
make completion as easy as azure-xplat-cli

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#630]
It would be nice to use the same technique with `az` as is suggested on the `azure-xplat-cli` readme.

``` shell
echo '. <(az --completion)' >> .zshrc
```

**Comment by derekbekoe** [comment]
This could also be `az completion bash/zsh` then it can be used like `source <(az completion bash/zsh)`

**Comment by colemickens** [comment]
@derekbekoe that's the exact pattern `kubectl` follows and I like it (I think the explicitness is a positive even)

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
