### ISSUE TITLE
[Storage] Upload-batch needs examples

### ISSUE THREAD

**Issue by gwlperl** [Azure/azure-cli#6310]
az storage file upload-batch requires source and destination but gives nothing on how to specify it.  Most things I've tried don't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c633bcb6-d7c0-8bfe-76b6-c69fed9eaf90
* Version Independent ID: 6b2e9a7e-c75f-0b48-0794-acd0ba474eba
* Content: [az storage file](https://docs.microsoft.com/en-us/cli/azure/storage/file?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by williexu** [comment]
@gwlperl what have you tried?
I've copied the help below:
```
--destination -d [Required]: The blob container where the files will be uploaded.
        The destination can be the container URL or the container name. When the destination is the
        container URL, the storage account name will be parsed from the URL.
--source -s      [Required]: The directory where the files to be uploaded are located.
```

**Comment by kostrse** [comment]
Please also mention in the documentation that when uploading into the "$web" container, the $ should be escaped in bash:

```
az storage blob upload-batch -s ~/MyWebsite1 -d "https://mywebsite.blob.core.windows.net/\$web"
```

**Comment by williexu** [comment]
I've added an example for upload-batch with https://github.com/Azure/azure-cli/pull/7153.
@kostrse I am hesitant to add that documentation as it is bash-specific and applies to a variety of other possible web container names.

**Comment by divgo** [comment]
the following worked for me locally. 

`az storage file upload-batch --account-name [StorageAccountName] --destination [ShareName] --source . --pattern *`

When I tried to run it from Azure DevOps though it broke. It was running on a Linux Build Agent. I changed the script to the following command, and this also worked. 

`az storage file upload-batch --account-name [StorageAccountName] --destination [ShareName] --source .`

**Comment by kepikoi** [comment]
> Please also mention in the documentation that when uploading into the "$web" container, the $ should be escaped in bash:
> 
> ```
> az storage blob upload-batch -s ~/MyWebsite1 -d "https://mywebsite.blob.core.windows.net/\$web"
> ```

Escape $web with single quotes in PowerShell `az storage blob upload-batch --account-name myaacountname --source .  -d '$web'`

**Comment by mona24** [comment]
> > Please also mention in the documentation that when uploading into the "$web" container, the $ should be escaped in bash:
> > ```
> > az storage blob upload-batch -s ~/MyWebsite1 -d "https://mywebsite.blob.core.windows.net/\$web"
> > ```
> 
> Escape $web with single quotes in PowerShell `az storage blob upload-batch --account-name myaacountname --source . -d '$web'`

Escaping $web with single quotes worked for me too

**Comment by balbany** [comment]
Thanks @divgo - I was tearing my hair out with the undocumented bug with the linux build agent (can't do --pattern *).

**Comment by praveenmak** [comment]
What if the folder already exists in the destination? 
I have spent couple of hours to figure out on how to overwrite or avoid overwriting.  
This is pretty unproductive. @microsoft help us to be productive.

**Comment by evelyn-ys** [comment]
As far as I know, only uploading a file to a file path in ADLS Gen2 file system with `az storage fs file upload` has `--overwrite` parameter for overwriting existing resource or not.
While uploading a file to a share with `az storage file upload` doesn't support `--overwrite` from service side.
