### ISSUE TITLE
Are there plans to be able to scale all the nodes on a cluster?

### ISSUE THREAD

**Issue by akakira** [Azure/azure-cli#6314]
When scaling the individual nodes the scale options don't update the size of the vms from the initial creation. I am hesitant to scale up nodes not knowing if the newly created nodes will use the original node size and not the new one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-scale)
* Content Source: [latest/docs-ref-autogen/aks.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/aks.yml)
* Service: **unspecified**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by mboersma** [comment]
@akakira changing the parameters of individual nodes / VMs isn't supported by AKS yet. At the very least, the next time you do `az aks scale` to add new nodes, they will be created with the VM size that was specified when the cluster was first created.

**Comment by mboersma** [comment]
@tjprescott this issue can be closed.

**Comment by mboersma** [comment]
See also #7927.
