### ISSUE TITLE
update a few show commands to swallow 404

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#6324]
The goal is to be consistent with the rest commands, that all show commands will output blank with zero exit code instead of error'ing out. (#5006 has the full context)
3 steps:
   1. Find impacted command list, including `az storage account show`
   2. For 2 releases, warn users that breaking change is coming
   3. Update dev documents to call out that `show` should never throw on 404

//CC: @tjprescott @troydai @williexu

**Comment by williexu** [comment]
More information about the breakdown of the show commands at the moment:
-Show commands that catch CloudErrors with a 404 status code: `102`
-Show commands that have no exception handling: `119`
-Show commands that have an exception handler but may/may not catch 404: `83`

**Comment by williexu** [comment]
Closing this due to: https://github.com/Azure/azure-cli/issues/6612
