### ISSUE TITLE
Issue with passing password

### ISSUE THREAD

**Issue by gstrantor** [Azure/azure-cli#6331]
We tried to script the export process for a DB and had issues with authentication as the password contained an exclamation mark. Trying to use the PowerShell methods of escaping the character failed. Any idea how to do it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1bdd674-b454-e863-c943-9c979b466a92
* Version Independent ID: b15341f9-3f1b-00e0-a1c2-970f25a6ab03
* Content: [az sql db](https://docs.microsoft.com/en-us/cli/azure/sql/db?view=azure-cli-latest#az-sql-db-export)
* Content Source: [src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by mleneveut** [comment]
Do you have a solution for this ?

My password starts with a single quote (') and contains exclamation mark.

I tried to surround with double quotes ("), to escape with \ but no success.

E.g. : az login -u myuser@microsoft.com -p 'sd(!MH;du4

**Comment by tjprescott** [comment]
https://www.gnu.org/software/bash/manual/html_node/Double-Quotes.html
So, for you password: "'sd(\!MH;du4"
