### ISSUE TITLE
Monitor / diagnostic settings - Create does not show 

### ISSUE THREAD

**Issue by anoff** [Azure/azure-cli#6332]
**Describe the bug**

When creating a new diagnostic rule via `az monitor diagnostic-settings create` with eventhub target it shows `"eventHubName": null` in the responsive.

An additional `az monitor diagnostic-settings list` shows the rule content including correct eventhub name.

The `timeGrain` also shows inconsistent behavior - only shows up in the initial response and appears as `null` in the list response.

At first I thought the CLI had a bug in parsing the eventhubname and didn't create the rule correctly, but seems it is only an issue in the response at the create command.

**To Reproduce**

```text
▶ az monitor diagnostic-settings create -n eh-blup --resource $REDIS_ID --event-hub redis-metrics --event-hub-rule $EH_RULE_ID --metrics '[{"category": "AllMetrics", "enabled": true}]'
{
  "additionalProperties": {
    "identity": null,
    "kind": null,
    "location": null,
    "tags": null
  },
  "eventHubAuthorizationRuleId": "xxxx/authorizationrules/RootManageSharedAccessKey",
  "eventHubName": null,
  "id": "xxxx/providers/microsoft.insights/diagnosticSettings/eh-blup",
  "logs": [],
  "metrics": [
    {
      "additionalProperties": {},
      "category": "AllMetrics",
      "enabled": true,
      "retentionPolicy": {
        "additionalProperties": {},
        "days": 0,
        "enabled": false
      },
      "timeGrain": "0:01:00"
    }
  ],
  "name": "eh-blup",
  "resourceGroup": "xxxx",
  "storageAccountId": null,
  "type": null,
  "workspaceId": null
}
09:49:28 in andreas/rcs/infra on  19-prod-subscription [$] took 4s
▶ az monitor diagnostic-settings list --resource $REDIS_ID
{
  "additionalProperties": {},
  "value": [
    {
      "additionalProperties": {
        "identity": null,
        "kind": null,
        "location": null,
        "tags": null
      },
      "eventHubAuthorizationRuleId": "xxxx/authorizationrules/RootManageSharedAccessKey",
      "eventHubName": "redis-metrics",
      "id": "xxxx/providers/microsoft.insights/diagnosticSettings/eh-blup",
      "logs": [],
      "metrics": [
        {
          "additionalProperties": {},
          "category": "AllMetrics",
          "enabled": true,
          "retentionPolicy": null,
          "timeGrain": null
        }
      ],
      "name": "eh-blup",
      "resourceGroup": "xxxx",
      "storageAccountId": null,
      "type": null,
      "workspaceId": null
    }
  ]
}
```

**Expected behavior**

Output of `az monitor diagnostic-settings create` shows the created diagnostic settings (incl correct eventhub name). `create` and `list` response are expected to be identical.

**Environment summary**

MacOS 10.13.4 (17E202)

az cli via brew

azure-cli (2.0.32)
monitor (0.1.6)

**Additional context**

Maybe related to #6162

**Comment by tjprescott** [comment]
Hi @anoff the most likely reason you would be seeing "null" in the command response is because that data is simply not returned by the service.  If you run the command with `--debug` you can see the raw response.  Does it include values for these properties?

**Comment by asheniam** [comment]
Thanks for reporting this.  We are taking a look at a fix.

**Comment by tjprescott** [comment]
@asheniam please do not create additional labels in this repo

**Comment by MyronFanQiu** [comment]
@asheniam Any update?
