### ISSUE TITLE
[Storage] Set BLOB storage tier

### ISSUE THREAD

**Issue by udf2457** [Azure/azure-cli#6334]
As per the title.  Please implement functionality to enable setting BLOB tier (hot, cool, archive).

Thank you !

**Comment by williexu** [comment]
I believe:
`az storage blob set-tier -c <container-name> --account-name <account> -n <blob> --tier Cool`
Is what you're looking for.

**Comment by udf2457** [comment]
@williexu Will try that out, but I was more thinking about during upload rather than having to make two calls ?

Under `az storage blob upload --help`,  the `--tier` flag says it is restricted to the following values:

> A page blob tier value to set the blob to. The tier correlates
> to the size of the blob and number of allowed IOPS. This is only
> applicable to page blobs on premium storage accounts.  Allowed
> values: P10, P20, P30, P4, P40, P50, P6, P60

**Comment by zezha-msft** [comment]
Hi @williexu, thanks for tagging me. We are following the [behavior](https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob#request-headers-page-blobs-only) of the service: when creating a blob, tier can only be specified for page blobs; tier cannot be changed at creation time for block blobs.

**Comment by zhusijia26** [comment]
Close the issue based on last comment and the idle time.
