### ISSUE TITLE
az acr build-task delete won't prompt for confirmation nor provide feedback on delete result

### ISSUE THREAD

**Issue by julioct** [Azure/azure-cli#6335]
**Describe the bug**
az acr build-task delete won't ask me for confirmation on the delete operation. It will also provide no feedback to know if the deletion succeeded or failed.

**To Reproduce**
```az acr build-task delete --name <task name> --registry <registry name>```

**Expected behavior**
Ideally the same behavior as any other delete command on Azure CLI. But at least a confirmation prompt and some feedback saying "delete succeded" or "delete failed".

**Environment summary**
Install Method: MSI
CLI version: 2.0.32
OS version: Windows 10 (1709)
Shell Type: cmd.exe

**Comment by djyou** [comment]
@tjprescott @derekbekoe This will be a breaking change from my understanding if we add a confirmation now for delete. Also we didn't have confirmation for other resource delete scenarios (e.g., registry/webhook/replication).

What's your suggestion?

**Comment by troydai** [comment]
Does the exit code indicate if the operation succeed?
