### ISSUE TITLE
`az aks upgrade` doesn't work with azure network plugin

### ISSUE THREAD

**Issue by noelbundick** [Azure/azure-cli#6336]
**Describe the bug**

`az aks upgrade` fails with the following error when used on a cluster that uses the `azure` network plugin (custom vnet)

```
Operation failed with status: 'Bad Request'. Details: Changing property 'networkProfile.networkPlugin' is not allowed.
```

**To Reproduce**

* create an AKS cluster in a custom vnet
* run `az aks upgrade -k 1.9.6 -n aks -g vnet-aks` to upgrade the cluster

**Expected behavior**

The cluster to be upgraded, or possibly a no-op if it's the same version

**Environment summary**

apt-get / 2.0.32 / Ubuntu 16.04 via WSL / zsh

**Comment by mariojacobo** [comment]
+1 seeing the same issue when using custom vNETs

**Comment by neutrongenious** [comment]
+1 same issue when trying to scale, also with custom vNets

**Comment by siliconcat** [comment]
+1 yeah, same using using vnets

**Comment by ronnytag233** [comment]
+1 same issue when trying to scale.

**Comment by mboersma** [comment]
There were a couple service-side issues relating to VNET upgrade that were fixed long ago--this is no longer an issue. @tjprescott this issue can be closed.
