### ISSUE TITLE
Enable access to x-ms-client-request-id 

### ISSUE THREAD

**Issue by udf2457** [Azure/azure-cli#6340]
As per the docs:

> Provides a client-generated, opaque value with a 1 KB character limit that is recorded in the analytics logs when storage analytics logging is enabled. Using this header is highly recommended for correlating client-side activities with requests received by the server.

**Comment by tjprescott** [comment]
Client request IDs are already generated by the CLI. What is the scenario in which you want to manually control them?

**Comment by udf2457** [comment]
Pretty much for the reason the docs state:

> correlating client-side activities

Let's say I've got a backup script.  In that scenario I would like to be able to correlate messages generated by the CLI with a given execution of the backup script.

Also, for example, looking at `ps` output on a Linux box, it might be a nice thing to be able to see the process correlation.

**Comment by tjprescott** [comment]
cc/ @johanste

**Comment by troydai** [comment]
The title reads like you want to "read" the generated client request ID rather than injecting your own ID. Am I right?

**Comment by udf2457** [comment]
Apologies for the badly worded title.

I was thinking more the opposite, i.e.`az foobar --request-id ij2mv03vm2` or whatever.

**Comment by troydai** [comment]
The telemetry logic is tightly correlated to the ID and we need to guarantee this ID to be generated randomly between calls.  Should we open up the generating logic and a flaw is introduced in the customization of the generator the CLI behaviour will be disrupted.

Please also be noted:

> If two subsequent write requests (two PUTs, POSTs, or DELETEs) have the same id, the Network Controller assumes that last request is a retry and returns the same result it returned for the previous request.
[Source](https://msdn.microsoft.com/en-us/library/mt766820.aspx)

As in CLI, we're the client to consume this ID. The consumer of the CLI should in term adopt their own logic to coorelate their command execution and loging.

May I understand your broader scenario? There is probably a different solution to it.

**Comment by yugangw-msft** [comment]
lack of response , closing
