### ISSUE TITLE
Enable syslog acccess

### ISSUE THREAD

**Issue by udf2457** [Azure/azure-cli#6342]
It would be nice if `az` could be told to log using syslog facilities available on linux boxes.

**Comment by tjprescott** [comment]
Thank you for the suggestion @udf2457. We will consider this.

**Comment by yugangw-msft** [comment]
Syslog is mainly for device related events, instead of for applications like CLI. 
We will re-consider if we have more user voices on this, but for now you can use "az  configure" to enable file logging and then write the content to the syslog on script existing

**Comment by udf2457** [comment]
@yugangw-msft that is simply not true.

Might I suggest `man logger` and `man syslogd`

The whole point that you are completely missing is that people shouldn't be forced to have file logging to some random file when they could get things logged to `/var/log/messages` or other centralised locations instead.

**Comment by yugangw-msft** [comment]
@udf2457, the main point I should have communicated is CLI should not have the opinion regarding the physical destination the logging should get to. As command line interface, it just emits out to the stdout/stderr, in the same way like `ls`, `cat`, etc. If we special case to Linux/syslog; what about counterparts on Windows and OSX?
