### ISSUE TITLE
Only works with classic alerts?

### ISSUE THREAD

**Issue by rbigeard** [Azure/azure-cli#6348]
It looks like the current CLI or API only applies to Classic alerts, is there a newer version of the CLI (and the documentation) in the works?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f601495-154d-5e5c-3692-02f8f41516f7
* Version Independent ID: 2968e230-b7a0-b433-333a-af3bba69fd0e
* Content: [az monitor alert](https://docs.microsoft.com/en-us/cli/azure/monitor/alert?view=azure-cli-latest#az-monitor-alert-list)
* Content Source: [src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Yes, the CLI currently only supports classic Monitor alerts. Commands for the newer Metrics Alerts are in development.
