### ISSUE TITLE
Handle VCR test playback when commands being tested generate guids and use them in the request url

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#635]
This blocks role assignments tests. 
The role assignment id is guid gen'd. The test recorder need to remember them and use when playback

**Comment by tjprescott** [comment]
@yugangw-msft I think once PR #1421 is merged, you should be able to fix this. Part of the PR lets you scrub things inside the response body, which previously wasn't possible.

**Comment by yugangw-msft** [comment]
@tjprescott , thank you!

**Comment by yugangw-msft** [comment]
@troydai, do you plan to do this work?

**Comment by troydai** [comment]
I don't think this belong to the test framework. The random value generating mechanism should be mocked.

**Comment by yugangw-msft** [comment]
@troydai  Per our discussion, this should be handled by test fx so that the recordings can be played back.

**Comment by troydai** [comment]
Yes. @yugangw-msft, can you provide me an example of this scenario? For the purpose of testing.

**Comment by yugangw-msft** [comment]
checkout: https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-role/tests/test_role.py#L179

**Comment by troydai** [comment]
cool

**Comment by troydai** [comment]
Per discussion with @yugangw-msft, he already has a solution. Close for now.
