### ISSUE TITLE
Interactive enum completions display error message when typing enum value

### ISSUE THREAD

**Issue by williexu** [Azure/azure-cli#6350]
**To Reproduce**
Steps to reproduce the behavior.
-start interactive
-type `az storage account create --kind s`
-should see error message:
![image](https://user-images.githubusercontent.com/8580552/40030562-204e4664-57a0-11e8-8d78-b39ec1a52ba7.png)

**Expected behavior**
No error message

This is coming from:
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/parser.py#L146

**Comment by tjprescott** [comment]
Possible side effect of #6126
