### ISSUE TITLE
Ability to Configure Azure CLI Trusted Root CAs

### ISSUE THREAD

**Issue by apeschel** [Azure/azure-cli#6352]
**Is your feature request related to a problem? Please describe.**

For an Azure Stack install, there is a requirement to add a Root CA for access via the Azure CLI. However, it is not currently possible to configure a custom CA for the Azure CLI toolset, and the Azure Stack documentation requires you to manually update the CA list in the library used by the Azure CLI toolset. Replacing the CA list in the library is problematic, as upgrading Azure CLI toolset will wipe out the trusted CA list. 

https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-version-profiles-azurecli2

**Describe the solution you'd like**

It would be ideal to have a version-neutral configuration for adding trusted root CAs. Having a trusted CA directory under `$AZURE_CONFIG_DIR/` would be best.

**Comment by troydai** [comment]
Adding @yugangw-msft

**Comment by yugangw-msft** [comment]
Can you configure it through the env variable of `REQUESTS_CA_BUNDLE`?
2 related links, hope it helps:
https://blog.jhnr.ch/2018/05/16/working-with-azure-cli-behind-ssl-intercepting-proxy-server/
https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-cli-admin

**Comment by yugangw-msft** [comment]
please reactivate if you are still blocked
