### ISSUE TITLE
az storage entity query: error: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by nwohlgemuth** [Azure/azure-cli#6353]
**Describe the bug**
With azure-cli 2.0.32, az storage entity query no longer works correctly.

**To Reproduce**
From bash run (where capitalized strings are the appropriate values):
docker run -it microsoft/azure-cli
az storage entity query --account-name ACCOUNT_NAME --account-key ACCOUNT_KEY --table-name TABLE_NAME

The azure cli will error saying "az storage entity query: error: 'NoneType' object is not iterable" (regardless of whether the specified table exists)

**Expected behavior**
If the table exists, this should result in a description of the contents of the table being returned. If not, it should result in an error saying that the table does not exist.

**Environment summary**
Repros on Ubuntu/Debian with version 2.0.32 of azure-cli.

**Additional context**
This command works as expected with azure-cli 2.0.31. Version 2.0.32 appears to have introduced a regression.

**Comment by williexu** [comment]
@nwohlgemuth sorry about the regression, fix will be in next release
