### ISSUE TITLE
Installation instructions are problematic

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#636]
I really don't like the style of "just link to some storage bucket that includes scripts that will download more scripts from another storage container and then all of this gets piped into a `sudo bash` session". It sets off all sorts of alarm bells.

Why can't there just be a page with all of the CI builds so I can choose what I want to install? I'd much rather just have a tarball that I can extract and run. And maybe a convenience link for those that really want to blindly throw binaries all over their system with no regard for their package manager.

I don't even get why there's any `sudo` involved at all. It's completely unneeded on OS X and shouldn't be necessary on Linux either, where `az` could easily be installed in a local user directory.

**Comment by colemickens** [comment]
To be rather blunt, it feels like a very Windows way to go about things. "Just elevate to admin and copy binaries around". No thank you.

**Comment by colemickens** [comment]
Actually, is `azure-cli` being published to PyPI? (If not, why not?) That would make all of this a lot easier and would make it easier for individuals to package this for their distribution.

**Comment by JasonRShaver** [comment]
I agree!  

Regarding PyPI, we are planning this I believe, @derekbekoe.

The script-based install is a point-in-time solution (see #394) until we build our GA install experience (#643, #644, #645).

**Comment by derekbekoe** [comment]
> I don't even get why there's any sudo involved at all. It's completely unneeded on OS X and shouldn't be necessary on Linux either, where az could easily be installed in a local user directory.

`sudo` is not **required** for install. It is only required if you want to install the CLI globally (which is the default). When installing with the curl method (e.g. `curl -L https://aka.ms/projectazinstall | bash`), you can choose to specify the install location.

For example:
```
In[0]: In what directory would you like to place the install? (leave blank to use /usr/local/az): ~/myaz
Out[0]: We will install at '/home/ubuntu/myaz'.
In[1]: In what directory would you like to place the executable? (leave blank to use /usr/local/bin): ~
Out[1]: The executable will be in '/home/ubuntu'.
Out[2]: ...(install continues)
(After install finishes, run az)
In[3]: ~/az
Out[3]: 
     /\
    /  \    _____   _ _ __ ___
   / /\ \  |_  / | | | \'__/ _ \
  / ____ \  / /| |_| | | |  __/
 /_/    \_\/___|\__,_|_|  \___|


Welcome to the cool new Azure CLI!
```

Using `/usr/local` __may__ require elevated permissions as it's a system-wide install.
For example of Ubuntu 14:04, I'm `ubuntu` and `/usr/local` is owned by `root` so `sudo` is needed.
```
ubuntu@azure-cli-dev3:~$ id -a
uid=1000(ubuntu) gid=1000(ubuntu) groups=1000(ubuntu)
ubuntu@azure-cli-dev3:~$ ls -ld /usr/local
drwxr-xr-x 10 root root 4096 Jul 14 20:41 /usr/local
```

As another example, on this particular OS X machine I am `derek` and `/usr/local` is owned by `derek` so `sudo` is not needed for global installation.
```
dereks-mbp:~ derek$ id
uid=501(derek)
dereks-mbp:~ derek$ ls -ld /usr/local
drwxrwxr-x  20 derek  admin  680 Aug  3 12:04 /usr/local
```
---
As @JasonRShaver mentioned, we are planning on publishing to PyPI in the future.

Thanks!

**Comment by colemickens** [comment]
Okay. I see the issues for apt/homebrew/yum... is there an issue I can
track for the PyPI publish?

**Comment by derekbekoe** [comment]
I have created https://github.com/Azure/azure-cli/issues/648.

Close issue?

**Comment by colemickens** [comment]
Excellent. Thanks all.

**Comment by itaysk** [comment]
Why is Windows not even mentioned as an option?
If it's because python is not bundled with Windows, that's not an excuse because neither is node.js but the old cli had Windows instructions and even a nice installer.
