### ISSUE TITLE
az aks commands use a different location for .kube directory than kubectl (Windows)

### ISSUE THREAD

**Issue by NicholasMarty** [Azure/azure-cli#6361]
**Describe the bug**
`az aks` commands are using a different path to the configuration for `kubectl` than `kubectl` itself does. 
* `az aks get-credentials` and `az aks browse` are using the `%USERPROFILE%` path
* `kubectl` uses `%HOMEDRIVE%%HOMEPATH%`
If these paths are different `kubectl` does not find the configuration from `az aks get-credentials` and the configuration has to be manually synced between the two paths.
And as `az aks browse` uses `kubectl` to open the connection `az aks browse` fails to run if the file `%HOMEDRIVE%%HOMEPATH%/.kube/config` does not exist (although a configuration file is passed as parameter to `kubectl`, it still tries to access this file )

**To Reproduce**
1. Delete the .kube directories in `%USERPROFILE%` (and in `%HOMEDRIVE%%HOMEPATH%` if different from `%USERPROFILE%`)
2. Change the HOMEDRIVE and HOMEPATH user variables to be different from the USERPROFILE
3. run `az aks get-credentials`
4. run `kubectl get pods`
kubectl errors out as it is unable to find the config file

**Expected behavior**
The path to the `.kube` directory should be identical for `az aks` commands and `kubectl`

**Environment summary**
Install Method: MSI
CLI version: 2.0.32
OS Version: Microsoft Windows 10 Enterprise (10.0.10586)
Shell Type: cmd.exe

**Additional context**
None

**Comment by jnoller** [comment]
Closing issue as stale/resolved - with the AKS windows support shifting into public preview, we have not received additional updates or issues related to this.

**Comment by nezoic** [comment]
Can this be reopened? this is still an issue. I'm running windows 10, and cannot run kubectl commands along side az aks commands without copying this config file over manually. It doesn't make much sense to have them in different locations.

**Comment by Kladfizk** [comment]
Please reopen this is an feature currently i have to copy the files in between the folder or set the path to the same which is not always possible in an enterprise environment
