### ISSUE TITLE
az vm extension  --name command cannot give any other name other than CustomScriptForLinux

### ISSUE THREAD

**Issue by cognsom** [Azure/azure-cli#6363]
hi 

i want to add an extension to my vm and identify that extension by a particular name .
command : -

 az vm extension set \
   --publisher  Microsoft.OSTCExtensions  \
   --name $Extension_name \
   --vm-name $vmname \
   --resource-group $ResourceGroupName \

But while running this command i am always forced to give the extension name as CustomScriptForLinux 
if iam giving custom name other than this it is throwing up an error saying extension cannot be found . 

But the same i am able to do it with an arm template 

so i would an solution for this issue 

Thanks

**Comment by yugangw-msft** [comment]
@adewaleo, can you take this one? I suggest we expose an `--extension-instance-name` to avoid the ambiguity with "extension type name" which is used more frequently.

**Comment by adewaleo** [comment]
Will do @yugangw-msft

**Comment by yugangw-msft** [comment]
@adewaleo  fixed it
