### ISSUE TITLE
Improve az storage blob upload-batch/download-batch progress output

### ISSUE THREAD

**Issue by marcelvb** [Azure/azure-cli#6364]
Problem:
When up or downloading a large amount of blobs using az storage blob upload-batch/download-batch the progress output is like this:

```
Finished[#############################################################]  100.0000%
Finished[#############################################################]  100.0000%
Finished[#############################################################]  100.0000%
Finished[#############################################################]  100.0000%
Finished[#############################################################]  100.0000%
Finished[#############################################################]  100.0000%
```

This does not tell me anything about the progress such as how many blobs/bytes are copied and which blobs are copied.

Solution:
I'd like the output the show the blob and/or file name and to see the overall progress, e.g. "6352 of 10000 blobs copied" or "1.8 GB of 20 GB copied". Having the speed (MB/s) or ETA (2 hours remaining) would be a nice bonus. Also it would be nice if the progress bar per blob would also show the blob name.

Using azure-cli version 2.0.27.

**Comment by williexu** [comment]
Will be fixed with: https://github.com/Azure/azure-cli/pull/8730
Example Output during progress:
```
1/42: "readme"[#########                                              ]  18.0626%
```

Example Output when done:
```
Finished[#############################################################]  100.0000%
[
  {
    "Blob": "https://wilxstorage.blob.core.windows.net/wilxcontainer/readme",
    "Last Modified": "2019-03-07T22:16:52+00:00",
    "Type": null,
    "eTag": "\"0x8D6A34A99E19009\""
  },
...
```
