### ISSUE TITLE
[Create Commands] Flags will be confusing in SDK

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#637]
Example:
Create a vm from SDK (not CLI) using the Smart Create command for vm.
There is a availability_set parameter and a availability_set_type parameter.  
Set the availability_set parameter to an availability set ID.
Run the command.

Expected: vm is added to the availability set
Actual: the vm is not added to the availability set because the availability_set_type parameter was set to null (which defaults to 'none').

Possible solution: we make the flags (which are a limitation of ARM templates) required so users must fill them out and then look for the related field to set a value to.  We would need to hide that required-ness on the CLI side.

**Comment by JasonRShaver** [comment]
that feels like a input check in the SDK command to me.  The default should undefined instead of null and setting an availability_set param with an undefined type param should raise an exception (invalidargumentexception if we're in .net land).

**Comment by tjprescott** [comment]
Closing this as the plan is to move away from FC deployments.
