### ISSUE TITLE
NoneType error: `az storage entity query --table-name mytable`

### ISSUE THREAD

**Issue by iyerusad** [Azure/azure-cli#6376]
# Describe the bug
Command `az storage entity query --table-name "mytable"` returns:
```
az storage entity query: error: 'NoneType' object is not iterable
```

This appears to be affecting versions:
- `azure-cli=2.0.32-1~wheezy`
- `azure-cli=2.0.31-1~wheezy`

32-1 appears to have been removed, but 31-1 is still serving from repo. I was not able to successfully get the command run until downgraded to 30-1.

## Workaround
We install Azure CLI to VSTS Hosted Linux Agent(s) - so "clean" environments. We have to regress two versions:

```
apt-get update -y
apt-get install -y python libssl-dev libffi-dev python-dev build-essential jq tree
curl -L https://azurecliprod.blob.core.windows.net/install.py -o install.py
printf "/usr/azure-cli\n/usr/bin" | python install.py

apt-get update -y
apt-get install -y azure-cli=2.0.30-1~wheezy --allow-downgrades
```

# To Reproduce
1. Install latest azure-cli:
```
apt-get update -y
apt-get install -y python libssl-dev libffi-dev python-dev build-essential jq tree
curl -L https://azurecliprod.blob.core.windows.net/install.py -o install.py
printf "/usr/azure-cli\n/usr/bin" | python install.py
```
2. Export AZURE_STORAGE_CONNECTION_STRING for valid table storage account/table.
2. Run command: `az storage entity query --table-name "mytable"`
2. Observe error.

## Expected behavior
Return the contents of the table

# Environment summary
Env: Ubuntu 16.04.4 LTS
Env2: VSTS hosted Linux Agent

Install Method:
```
apt-get update -y
apt-get install -y python libssl-dev libffi-dev python-dev build-essential jq tree
curl -L https://azurecliprod.blob.core.windows.net/install.py -o install.py
printf "/usr/azure-cli\n/usr/bin" | python install.py
```

**Comment by williexu** [comment]
Same as https://github.com/Azure/azure-cli/issues/6353
This was a recent regression and fixed with https://github.com/Azure/azure-cli/pull/6355
Fix will be out in next release.
