### ISSUE TITLE
Can't log in into azure 

### ISSUE THREAD

**Issue by Sokolnikoff** [Azure/azure-cli#6380]
**Description**
I installed the standalone version of Machine Learning Server of Microsoft in a server with Windows server 2012 DataCenter. I used `az ml admin bootstrap` added the password to the admin account and for some reason neither node was able to start, even though there were no problems in the installation process. I tried to login to azure with `az login` and this error appears:

`login() missing 1 required positional argument: 'cmd' Traceback (most recent call last): File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack \cli.py", line 193, in invoke cmd_result = self.invocation.execute(args) File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure \cli\core\commands\__init__.py", line 319, in execute six.reraise(*sys.exc_info()) File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\six.p y", line 693, in reraise raise value File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure \cli\core\commands\__init__.py", line 292, in execute result = cmd(params) File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure \cli\core\commands\__init__.py", line 169, in __call__ return super(AzCliCommand, self).__call__(*args, **kwargs) File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack \commands.py", line 109, in __call__ return self.handler(*args, **kwargs) File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure \cli\core\__init__.py", line 328, in default_command_handler result = op(**command_args) File "C:\Users\Administrador\.azure\cliextensions\azure-ml-admin-cli\azext_adm in\custom.py", line 88, in mls_login msi_port=msi_port) TypeError: login() missing 1 required positional argument: 'cmd'`

I am unable to login, there's no way to start the nodes or reset them, as I get this other error with the firewall deactivated:

`2018-05-17 19:39:58,402 WARNING Retrying (Retry(total=2, connect=None, read=None
, redirect=None, status=None)) after connection broken by 'NewConnectionError('<
urllib3.connection.HTTPConnection object at 0x045614F0>: Failed to establish a n
ew connection: [WinError 10061] No connection could be made because the target m
achine actively refused it',)': /login`

Here is the `--debug` spew as requested by another user:
[Debug.txt](https://github.com/Azure/azure-cli/files/2014507/Debug.txt)

I also did the installation from within the SQL Server 2017 bootstrap under the option **New Machine Learning Server (Standalone) installation**, changed the paths in the registries and obtained same results.

**To Reproduce**
I only followed the steps in this page to install and operationalize:
[Machine Learning Server Windows Install](https://docs.microsoft.com/en-us/machine-learning-server/install/machine-learning-server-windows-install)

And also obtained the requirements mentioned here:
[Configure Machine Learning Server One-Box](https://docs.microsoft.com/en-us/machine-learning-server/operationalize/configure-machine-learning-server-one-box)

After this and restarting, I tried to use the commands described above with the error messages already mentioned.
**Expected behavior**
I expected the nodes to be running once configured; or at least be able to login in order to run diagnostics.

**Environment summary**
I installed this in two OS, Windows Server 2012 Standard and, as mentioned above, the other one was DataCenter. Both with same results. I used the installer inside en_machine_learning_server_9.3.0_for_windows_x64_11739592.zip obtained from [Visual Studio Dev Essentials](https://my.visualstudio.com/).

**Comment by yugangw-msft** [comment]
I will let ML team take a look at this. Based on the stack, CLI's login was not invoked under a right context.

**Comment by zwyszomi** [comment]
Hi
I have received the same errors with the same scenarios mentioned by Sokolnikoff. Is there any way to solve it?
Ziggy

**Comment by zwyszomi** [comment]
It seems I have solved that issue ;) 
In many Windows environments Execuction Policy for PowerShell scripts is not configured correctly. When You change it, it works (or at least Web & Computation Nodes start)

**Comment by yugangw-msft** [comment]
Thanks. I am closing this since this issue should go to ML's repository anyway.
