### ISSUE TITLE
Need better documentation on the upgrade works

### ISSUE THREAD

**Issue by akramwaseem** [Azure/azure-cli#6387]
Hi,
Need a better documentation on the rolling upgrade works.
In a VMss lets say I have 10 VMs and I want to do rolling upgrade. How does it work. does it do onre by one with zero downtime or does it do all at once?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 511e79b4-b7c8-3379-50d7-12aface869e5
* Version Independent ID: ce67a39a-6aa8-853d-de41-5c884114f5dd
* Content: [az vmss rolling-upgrade](https://docs.microsoft.com/en-us/cli/azure/vmss/rolling-upgrade?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machine-scale-sets**
* Product: **unspecified**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
//cc: @gatneil

**Comment by gatneil** [comment]
Hello! It works the same as the upgrade described here: https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-automatic-upgrade. Thanks :)

**Comment by yugangw-msft** [comment]
closing, we already have doc 
Thanks @gatneil !
