### ISSUE TITLE
command linter: check show command capture 404

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#6391]
For #6324. 
Emitting out either a warning or an error are both fine. Personally I prefer error and let user suppress, as I don't think we have lots of `show` commands in each command module except network.
The goal is to prevent such inconsistency from spreading to be unsolvable.
@williexu, I am assigning this to you, but we can load balance if needed

//CC: @tjprescott, @troydai

**Comment by williexu** [comment]
Closing this as we have decided to not suppress 404 errors and to instead exit with a code of 3.
https://github.com/Azure/azure-cli/pull/6489
