### ISSUE TITLE
[SQL] SQL firewall-rule needs examples

### ISSUE THREAD

**Issue by basharSS** [Azure/azure-cli#6396]
Please, always add sample

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0ed8c3b-f42d-2421-a563-d09ec7b67ac0
* Version Independent ID: bcdaeb1b-e343-2336-d394-e32f8d867ab2
* Content: [az sql server firewall-rule](https://docs.microsoft.com/en-us/cli/azure/sql/server/firewall-rule?view=azure-cli-latest#az_sql_server_firewall_rule_create)
* Content Source: [src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py)
* Service: **sql-database**
* Product: **unspecified**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by troydai** [comment]
@jaredmoo
