### ISSUE TITLE
MacOS: Can't connect to HTTPS URL because the SSL module is not available

### ISSUE THREAD

**Issue by derekperkins** [Azure/azure-cli#6409]
**Describe the bug**
The cli fails any networks calls, apparently related to 
Related issues for Debian/Ubuntu: https://github.com/Azure/azure-cli/issues/4360 / https://github.com/Azure/azure-cli/issues/3720

**To Reproduce**
1. `brew install azure-cli`
1. `az login` _(any command with a network call)_

**Expected behavior**
That the command succeed

**Environment summary**
Install Method: brew 
CLI version: azure-cli (2.0.32)
OS: MacOS 10.13.4
Shell Type: zsh
`openssl version -v`: LibreSSL 2.2.7

**Comment by derekperkins** [comment]
This was super frustrating, so I figured I'd add a Q&A here to try and help anyone dealing with this in the future. I solved this by uninstalling and reinstalling: 
1. `brew uninstall --force openssl`
1. `brew install openssl`

When I ran `brew install openssl` without uninstalling first, this is what happened:

```
$ brew install openssl
Warning: openssl 1.0.2o_1 is already installed, it's just not linked
You can use `brew link openssl` to link this version.

$ brew link openssl
Warning: Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib
```

**Comment by joshuaheslin** [comment]
Thanks @derekperkins ,

I ran into the same issue you were having. I think the version of openssl azure was wanting was not the correct on install and the symlink was somewhere dropped. I fix this issue by doing the following. 

1. `brew resinstall openssl@1.1` 
2. `brew link --force openssl`
3. `brew reinstall azure-cli`
4. `az login`

Hope that helps anyone.

**Comment by intolerance** [comment]
Thanks @derekperkins and @joshuaheslin ,

I was able to simply run `brew reinstall azure-cli` and I was able to login using `az login` again with no issues.

**Comment by j3pic** [comment]
For me, removing the Pyenv install of Python was necessary after reinstalling OpenSSL:

    rm -rf ~/.pyenv
    pyenv install `cat .python-version`

**Comment by lifenautjoe** [comment]
> For me, removing the Pyenv install of Python was necessary after reinstalling OpenSSL:
> 
> ```
> rm -rf ~/.pyenv
> pyenv install `cat .python-version`
> ```

This helped. Thanks!

**Comment by nomula** [comment]
I tried all the above commands and still have issues:

az login
Note, we have launched a browser for you to login. For old experience with device code, use "az login --use-device-code"
Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/token (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

**Comment by jiasli** [comment]
@fengzhou-msft , could you help take a look at why Azure CLI installed by `brew` can't access the SSL module?

**Comment by fengzhou-msft** [comment]
Close due to inactivity. Please try the latest `azure-cli` and feel free to open a new issue if any problem.

**Comment by nomula** [comment]
for some reason all these emails went to my junk folder and so i missed to reply .....
I will try installing latest cli and please don't close the case until i response in next couple days ....
________________________________
