### ISSUE TITLE
Extension "webapp" commmand "remote-connection" not working on Win8.1 powershell 4

### ISSUE THREAD

**Issue by jboren** [Azure/azure-cli#6411]
When trying to use the Azure CLI to create an tcp tunnel for a remote SSH connection to a Web app on linux, using the command "az webapp remote-connection create -n <webapp name> -g <resource group name>", The command throws a 503 error and hangs.  

**To Reproduce**

1. On Win8.1 install Azure CLI via the MSI at: https://aka.ms/installazurecliwindows
2. Open Powershell
3. Install the webapp extension with "az extension add --name webapp"
4. Login with "az login" go to URL in powershell message (https://microsoft.com/devicelogin) and enter the provided code, and follow the prompts, successfully log in.
5. List accounts with "az account list"
6. Choose correct account with "az account set --subscription <account id>"
7. List webapps in account with "az webapp list"
8. Attempt to create remote connection to app with "az webapp remote-connection create --name <webapp name> --resource-group <resource group name>
9. It picks a random port, then throws a 503 and hangs.

Auto-selecting port: 29547
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "C:\Users\<my user>\.azure\cliextensions\webapp\azext_webapp\custom.py",
line 270, in _start_tunnel
    if not _check_for_ready_tunnel(remote_debugging_enabled, tunnel_server):
  File "C:\Users\<my user>\.azure\cliextensions\webapp\azext_webapp\custom.py",
line 240, in _check_for_ready_tunnel
    default_port = tunnel_server.is_port_set_to_default()
  File "C:\Users\<my user>\.azure\cliextensions\webapp\azext_webapp\tunnel.py",
line 95, in is_port_set_to_default
    raise CLIError("Failed to connect to '{}' with status code '{}' and reason '
{}'".format(url, r.status, r.reason))
knack.util.CLIError: Failed to connect to 'https://<webapp name>.scm.azurew
ebsites.net/AppServiceTunnel/Tunnel.ashx?GetStatus' with status code '503' and r
eason 'Service Unavailable'

No tunnel is created.  Have to CTRL+C to terminate command and return to prompt.

**Expected behavior**
Command should create a tunnel to the webapp allowing SSH access, according to documentation.

**Environment summary**
Install Method: 
1. install Azure CLI via the MSI at: https://aka.ms/installazurecliwindows
2. Open Powershell
3. Install the webapp extension with "az extension add --name webapp" 
      
CLI version: 2.0.33
webapp extension version: 0.2.6
OS version: Windows 8.1 Pro
Shell Type: Powershell 4.0 
same result in cmd.exe

**Additional context**
Doesn't matter whether you set a default resource group or declare the resource group name as part of the command.
Doesn't matter whether you declare the port number or let it select it automatically.
Doesn't matter which slot you choose, although on the default "production" slot it throws a different error:  "The Resource 'Microsoft.Web/sites/<webapp name>/slots/production' under resource group '<resource-group name>' was not found.  If you create another slot copied from production and try to connect to that, it throws the 503 error.   Doesn't matter which slot is active.

**Comment by yugangw-msft** [comment]
please open issue at https://github.com/azure/azure-cli-extensions/issues
