### ISSUE TITLE
Changed shell to zsh and autocomplete doesn't trigger

### ISSUE THREAD

**Issue by benc-uk** [Azure/azure-cli#6414]
**Describe the bug**
Switched default shell to zsh and tab autocomplete doesn't work

**To Reproduce**
- Install Azure CLI under Bash via apt. 
- Install zsh `sudo apt install zsh`
- Launch zsh shell `zsh`
- Type command `az group show -n Foo` where Foo is the start of a resource group name, and hit tab

**Expected behavior**
After a pause the resource group name should autocomplete, but with zsh nothing happens

**Environment summary**
WSL with apt on Windows 10 1803

**Additional context**
None

**Comment by benc-uk** [comment]
Note. When I launch a bash shell the auto-complete still works.

Is there something I need to copy from my .bashrc into my .zshrc for this to work?

**Comment by niwsa** [comment]
I am facing the exact issue, works on bash but not on zsh.It would we really cool to fix this for zsh.

**Comment by benc-uk** [comment]
I've reinstalled the CLI under zsh and it still doesn't work. It's really annoying that bash is the only shell where autocomplete works

**Comment by benc-uk** [comment]
Any update?

zsh is hardly obscure, it's used by everyone

**Comment by niwsa** [comment]
Its working for me with  azure-cli version 2.0.70
