### ISSUE TITLE
Poor performance for azure storage blob delete-batch with pattern option

### ISSUE THREAD

**Issue by popcornylu** [Azure/azure-cli#6415]
**Describe the bug**
I have large volume of blobs in my container (more than 1m blobs). Delete with option `--pattern` seems to traverse all the blobs and match against this pattern. It is much slower than `list --prefix`.

**To Reproduce**
1. Delete batch for pattern in dry run mode. This will take long time
```
az storage blob delete-batch -s <container> --pattern '<dir>/*' --dryrun
```
2. list the blobs with prefix. It will return right away
```
az storage blob list -c <container> --prefix '<dir>'
```

**Expected behavior**
Add the `--prefix` option, in which it behaves like `list --prefix`. Only delete the blobs within the given prefix.

**Environment summary**
Install Method (yum) / azure-cli (2.0.33) / CentOS 7.2  / bash

**Additional context**
N/A

**Comment by tycho01** [comment]
We were experiencing performance issues with this as well.
For reference, deleting e.g. a folder using [azure storage explorer](https://github.com/Microsoft/AzureStorageExplorer) seemed quite performant.

**Comment by ronaldvanrij** [comment]
Same performance issues here. It seems the `delete-batch` is simply iterating over each blob in the container followed by client-side filtering. So this'll be very slow if your contains contains many files (100000+). Source:
https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/util.py#L24

Interestingly this `list_blobs` method seems to take in a prefex parameter as can be seen here:
https://github.com/Azure/azure-cli/blob/master/scripts/ci/publish.py#L77

Can this be implemented?

**Comment by yugangw-msft** [comment]
@williexu, it is worthwhile to cross check whether or not azcopy does better on this?

**Comment by williexu** [comment]
@yugangw-msft for sure :)

For those on this thread, we will be adding [azcopy](https://github.com/Azure/azure-storage-azcopy) functionality through the `storage-preview` extension within the next sprint or so, which should hopefully address this and many other storage issues in the CLI through increased performance.

**Comment by limingu** [comment]
The [azcopy ](https://github.com/Azure/azure-storage-azcopy) delete command is in our storage-preview extension now. Let us know if you are satisfied with the performance.

Try that like:
az storage azcopy blob delete \
    -c containerName \
    --account-name accountName \
    -t targetBlob

**Comment by yonzhan** [comment]
Was this issue resolved?

**Comment by Juliehzl** [comment]
Update: please try `az storage remove` command with latest azure cli version.
Close the issue now and if you still have problem, feel free to create a new one.
