### ISSUE TITLE
[Storage] Onboard Storage Queue Commands

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#642]
If it follows blob and file, 70% or more can be reflected from the SDK.

**Comment by tjprescott** [comment]
PR #702 merged.

**Comment by mqzl1** [comment]
Based on your comments, we understand that when integrating storage queue commands and following the operation patterns for blobs and files, the SDK's reflection rate can reach 70% or higher. maybe PR https://github.com/Azure/azure-cli/pull/702 Closed

**Comment by qweqweqwewrfg** [comment]
I think so

**Comment by qweqweqwewrfg** [comment]
@mqzl1 you are right
