### ISSUE TITLE
`delete-batch` generates too much output

### ISSUE THREAD

**Issue by hdost** [Azure/azure-cli#6420]
**Describe the bug**
When deleting with `delete-batch` it generates a result with a ton of output, which is completely useless

**To Reproduce**
Create a bunch of files with a key leading name FOLDER
az storage blob delete-batch --account-name <ACCOUNT> -s <CONTAINER> --pattern "FOLDER/*"

**Expected behavior**
Either shows nothing, or it says how many blobs were deleted.

**Environment summary**
Doesn't matter

**Additional context**

**Comment by williexu** [comment]
This has been fixed, a warning with the number of failures will occur if some blobs fail to be deleted.
