### ISSUE TITLE
Support storage containers named `$web`

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/azure-cli#6424]
Blob storage is getting a feature to serve up static websites. The destination container must be `$web`, so the CLI must be updated to support this.

**Repro**
> D:\Repos\XXXX> az storage blob upload -f .\index.html -c "$web" -n index.html
> az storage blob upload: error: argument --container-name/-c: expected one argument

**Expected behavior**

> D:\Repos\XXXX> az storage blob upload -f .\index.html -c web -n index.html
> 
> No credentials specified to access storage service. Please provide any of the following:
>     (1) account name and key (--account-name and --account-key options or
>         set AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_KEY environment variables)
>     (2) connection string (--connection-string option or
>         set AZURE_STORAGE_CONNECTION_STRING environment variable)
>     (3) account name and SAS token (--sas-token option used with either the --account-name
>         option or AZURE_STORAGE_ACCOUNT environment variable)

**Additional context**
This feature is in preview. You must go to http://aka.ms/staticwebsites and load a Storage account in the West Central US region to see the option of enabling Static Websites.. Public preview starts in June.

For more info on the feature: https://www.youtube.com/watch?v=LFFCokEONvo

**Comment by williexu** [comment]
@MisinformedDNA works for me on windows terminal:
```
(env36) C:\Users\wilx\azure-cli>az storage blob upload  --account-name wilxstorage1 -c "$web" -n index.html -f C:\Users\wilx\temp\index.html
Finished[#############################################################]  100.0000%
{
  "etag": "\"0x8D5CA6866A846C0\"",
  "lastModified": "2018-06-04T22:13:29+00:00"
}

(env36) C:\Users\wilx\azure-cli>az storage blob upload   -c "$web" -n index.html -f C:\Users\wilx\temp\index.html

No credentials specified to access storage service. Please provide any of the following:
    (1) account name and key (--account-name and --account-key options or
        set AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_KEY environment variables)
    (2) connection string (--connection-string option or
        set AZURE_STORAGE_CONNECTION_STRING environment variable)
    (3) account name and SAS token (--sas-token option used with either the --account-name
        option or AZURE_STORAGE_ACCOUNT environment variable)
```

**Comment by MisinformedDNA** [comment]
Just figured it out. It's a PowerShell "issue". In PS, the `$` needs to be escaped! So it should be 

```
-c "`$web"
```
