### ISSUE TITLE
Support installation on OSX with Homebrew

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#643]

**Comment by mayurid** [comment]
@haocs and @derekbekoe : For one of us to pick for November

**Comment by derekbekoe** [comment]
PR https://github.com/Azure/azure-cli/pull/1573 includes the Homebrew formula.

After the holiday season, we can create a PR to https://github.com/Homebrew/homebrew-core to include the CLI in Hombrew.

Since the name 'azure-cli' is taken by xplat-cli, the formula currently uses the name 'azure-cli-2'.

**Comment by derekbekoe** [comment]
After discussions, changing milestone to Sprint 12.

**Comment by alexkli** [comment]
I see there is a formula that seems ready to go at https://github.com/derekbekoe/homebrew-core/commit/c37b47ef58d886d3d69b253f23256186a6ab2d84

Would be really great to get this done soon. The current standard shell script installation (`curl -L https://aka.ms/InstallAzureCli | bash`) is not great, defaulting to `~/lib/azure-cli` and `~/bin`, as well as possibly reinstalling python & python libraries separate from the ones managed by homebrew (for an osx homebrew user).

**Comment by derekbekoe** [comment]
Possibly blocked to due package dep. conflicts - https://github.com/Homebrew/homebrew-core/pull/13198#issuecomment-306312722

**Comment by balupton** [comment]
What's the latest on this? Seems no new progress was made:

```
> brew install azure-cli-2
Updating Homebrew...
Error: No available formula with the name "azure-cli-2" 
==> Searching for a previously deleted formula...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```

**Comment by balupton** [comment]
Okay. Latest is https://github.com/antoineco/homebrew-azure-cli

```
> brew tap antoineco/azure-cli
==> Tapping antoineco/azure-cli
Cloning into '/usr/local/Homebrew/Library/Taps/antoineco/homebrew-azure-cli'...
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 8 (delta 0), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (8/8), done.
Tapped 1 formula (34 files, 39.2KB)
20:21:50:/Users/balupton:master
> brew install azure-cli@2.0
Updating Homebrew...
==> Installing azure-cli@2.0 from antoineco/azure-cli
==> Downloading https://azurecliprod.blob.core.windows.
```

**Comment by haakoo** [comment]
Is this the current recommended way to install azure-cli v2 for macOS?

**Comment by tamird** [comment]
@derekbekoe is anyone working on this? should be possible to figure out these dependency issues, but doesn't seem like anyone has tried. Perhaps I'm misunderstanding.

**Comment by JasonRShaver** [comment]
I believe we are planning this work in the next sprint; we have some changes to packaging and extension support we need to land first.  If anyone is capable of helping us with the Brew package, we would be thrilled to accept the help =)

**Comment by tjprescott** [comment]
It looks like @antoineco has code to accomplish this. It *could* be as simple as submitting a PR against our repo, pending review of course.

**Comment by tamird** [comment]
@tjprescott what do you mean? you guys probably want your formula to live in https://github.com/Homebrew/homebrew-core, not here in this repo.

**Comment by antoineco** [comment]
Indeed, I keep the aforementioned Tap up-to-date, but I'd also prefer to see this merged in Homebrew core.

**Comment by derekbekoe** [comment]
I have created https://github.com/Azure/azure-cli/pull/4313 to address https://github.com/Homebrew/homebrew-core/pull/13198#issuecomment-306312722.

Once merged and a new version of the CLI is released, there should be no more version conflicts and the commands below should return no errors:
```
pip install azure-cli homebrew-pypi-poet
poet -f azure-cli
```

After this, a PR to homebrew core will be created.

**Comment by derekbekoe** [comment]
The homebrew PR has been created - https://github.com/Homebrew/homebrew-core/pull/17344.

**Comment by derekbekoe** [comment]
Homebrew released.
`brew update; brew install azure-cli`
