### ISSUE TITLE
VM: need a API to get the vm-sizes capable of accelerated networking

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#6440]
This will get rid of the gigantic hard coded [size array](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py#L569-L595) in CLI.

//CC @troydai

**Comment by huangpf** [comment]
This API already exists:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2018-06-01/compute.json#L1031

**Comment by huangpf** [comment]
Please close this issue?

**Comment by yugangw-msft** [comment]
@huangpf, the link you provided is no longer accurate, but if you are talking about listSize/listSku, then that doesn't help as not all sizes with same vCPU number can work with ACC-net.

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
