### ISSUE TITLE
Add az sql server exists command

### ISSUE THREAD

**Issue by nporaMep** [Azure/azure-cli#6442]
I want command similar to az group exists, but for SQL server.

Currently use **az sql server show**, but it prints red exception into log which I don't want
Maybe **az sql server list** with JMES should do the trick, but I can't get it working.
E.g. **az sql server list --query [?.name==`mytestsqlsrv1234`]** gives
az sql server list: error: argument --query: invalid jmespath_type value: '[?.name==mytestsqlsrv1234]'

**Comment by tjprescott** [comment]
Related to #5006. cc/ @yugangw-msft @williexu 

Sounds like in this case, the desired scenario is to swallow the 404.

**Comment by nporaMep** [comment]
Similar problem with **az ad app**
**create** prints an error on update
**update** prints an error on create
**show** prints an error on non existent
**list --query** doesn't work

found this working, but can't say I'm happy with it
(az ad app list --filter "displayName eq 'testadappregistration'" | ConvertFrom-Json).Length

**Comment by nporaMep** [comment]
Similar problem with **az keyvault secret**

Have to do this:
**$secretExists = (az keyvault secret list --vault-name $keyVaultName | ConvertFrom-Json | where { $_.id.Contains('$secretName') }).Length = 1**

**Comment by williexu** [comment]
@nporaMep will https://github.com/Azure/azure-cli/pull/6467 address your needs?
Note that https://github.com/Azure/azure-cli/pull/6467 will not address your concerns for `keyvault secret`

**Comment by nporaMep** [comment]
#6467 will address some of my needs.
I don't know if there is a command to retrieve possible values for --resource-type. Will be nice to have if there is not.

So far I have to check things below for existence. I do all of it via list command and technique that I described above. #6467 probably won't work for things selected in bold:
az sql server
**az sql server firewall-rule**
az sql db
az storage account
az keyvault
**az keyvault secret**
az appservice plan
az webapp
**az webapp deployment slot**

**Comment by williexu** [comment]
The current `show` commands act similarly to `exists` in that they will throw an error upon a 404 (this is the 99.9% case). They will also fail upon other server errors like a 500.

Can you tell us a little bit more about your scenario and why you cannot have logging to stderr when running your existence checks?

**Comment by nporaMep** [comment]
Important addition:
I don't want to use 2>$null to swallow error log, because if it's 5xx then it means that customer must rerun deployment script. While if it's 404 then this should be ignored.

**Comment by aamalvea** [comment]
This isn't SQL specific, but a core CLI functionality. Reassigning to Core team

**Comment by tjprescott** [comment]
This is supported in the CLI core and the SQL commands have already been converted to use this paradigm. If the resource does not exist, the command will return exit code 3, which can be used for an `exists` check. I am closing this issue.

**Comment by rokeno** [comment]
@tjprescott - Can you post an example?
