### ISSUE TITLE
How to Obtain Master VM Public IP (Used for ssh into ACS-Cluster) with azure-cli

### ISSUE THREAD

**Issue by SeanTurner026** [Azure/azure-cli#6445]
---

### Environment summary

**Install Method**: homebrew
**CLI Version**: azure-cli (2.0.23) 
**OS Version**: macOS High Sierra 10.13.4
**Shell Type**: bash

This is a request for help. I am creating a kubernetes cluster on acs using terraform, and I have up to this point been unable to get the cluster's master VM's public IP using the azure command line. This IP is used to ssh into the master VM (`ssh user@public-ip`), and the only way for me to get it currently is to log into the portal, and navigate through the resource group to the master VM.

I want this IP so that I can download the .kube/config file onto my computer via `scp`, and use bash scripting to build the cluster out and output load balancer IP addresses.

Any help would be greatly greatly appreciated! Thank you!

**Comment by SeanTurner026** [comment]
Some additional information, I am unsure how to get the cluster name. Running `az acs list` returns `[]`. I was going to try and input the cluster name from this output into `az acs kubernetes get-credentials -g <resource-group> -n <cluster-name>`, as I am pretty sure that this command would give me the master VM's IP address.

Any help would be absolutely incredible. Thanks again!

**Comment by mboersma** [comment]
@SeanTurner026 if `az acs list` doesn't show the cluster, the CLI commands won't help you unfortunately. In that case, navigating to the VM through the portal (or an equivalent `az vm` command) is the only way to discover the IP address.

I'm not sure how the terraform code works, but I'm guessing it doesn't call the expected APIs to create a proper ACS cluster.

**Comment by yugangw-msft** [comment]
closing as `az acs` is deprecating. If repro's with `az aks` please reactivate
