### ISSUE TITLE
"az role definition create" throws trace, unhashable type: 'slice'

### ISSUE THREAD

**Issue by praveendhac** [Azure/azure-cli#6447]
**Describe the bug**
Executing `az role definition create` is throwing error `TypeError: unhashable type: 'slice'`, the command is broken.

`praveen@Azure:~$ az role definition create --role-definition prav_devops_provisioning.json
unhashable type: 'slice'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 336, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 310, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 171, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/knack/commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 420, in default_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 50, in create_role_definition
    return _create_update_role_definition(cmd.cli_ctx, role_definition, for_update=False)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 65, in _create_update_role_definition
    names = [p for p in role_definition if p[:1].isupper()]
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/role/custom.py", line 65, in <listcomp>
    names = [p for p in role_definition if p[:1].isupper()]
TypeError: unhashable type: 'slice'
`
**To Reproduce**
Execute `az role definition create --role-definition prav_devops_provisioning.json`

**Expected behavior**
Should create a role or throw proper error message indicating the issue in config.

**Environment summary**
Azure CLI on azure portal

**Additional context**
$ cat prav_devops_provisioning.json
`
[
  {
    "assignableScopes": [
      "/subscriptions/111-222-333-444/resourceGroups/prav-*/providers/Microsoft.ContainerRegistry/registries/prav-*/providers/Microsoft.Authorization/roleAssignments/*"
    ],
    "description": "DevOps",
    "name": "prav-DevOps",
    "id": null,
    "iscustom": true,
    "permissions": [
      {
        "actions": [
          "Microsoft.Authorization/roleAssignments/write",
          "Microsoft.Authorization/roleAssignments/delete"
        ],
        "dataActions": [],
        "notActions": [
          "Microsoft.Authorization/*/Delete",
          "Microsoft.Authorization/*/Write",
          "Microsoft.Authorization/elevateAccess/Action"
        ],
        "notDataActions": []
      }
    ],
    "roleName": "prav-DevOps"
  }
]
`

**Comment by anhoward** [comment]
This is also an issue for `az role definition update`, not just `create`.

**Comment by yugangw-msft** [comment]
@praveendhac, please remove the outside `[]`  so to input an object instead of an array of such objects.
If you get such samples json from azure documents, please let me know.

**Comment by yugangw-msft** [comment]
At the same time, I will update CLI to avoid this bad error.

**Comment by praveendhac** [comment]
Seeing below error after removing []
```$ az role definition create --role-definition k8s_cust_role_12062018.json
No registered resource provider found for location 'eastus' and API version '2018-01-01-preview' for type 'registries'. The supported api-versions are '2016-06-27-preview, 2017-03-01, 2017-10-01, 2017-06-01-preview'. The supported locations are 'westus, eastus, southcentralus, westeurope, northeurope, uksouth, ukwest, australiaeast, australiasoutheast, centralindia, eastasia, japaneast, japanwest, southeastasia, southindia, brazilsouth, canadaeast, canadacentral, centralus, eastus2, northcentralus, westcentralus, westus2'.```

**Comment by yugangw-msft** [comment]
@praveendhac, could you please paste here the definition artifacts particularly the `registries` mentioned in the error? I don't believe the original definition you provided would cause this error.

**Comment by yugangw-msft** [comment]
Please reactivate with more information
