### ISSUE TITLE
New-AzureRmRoleDefinition throws error, "Cannot deserialize the current JSON array"

### ISSUE THREAD

**Issue by praveendhac** [Azure/azure-cli#6452]
**Describe the bug**
Executing custom role creation command throws trace/exception.
PS Azure:\> New-AzureRmRoleDefinition -InputFile "C:\Users\prav_devops_provisioning.json"
`New-AzureRmRoleDefinition : Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Microsoft.Azure.Commands.Resources.Models.Authorization.PSRoleDefinition' because the type requires a JSON object (e.g.
{"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be
deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
At line:1 char:1
+ New-AzureRmRoleDefinition -InputFile "C:\Users\prav_devops_provisioning.json"`
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmRoleDefinition], JsonSerializationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleDefinitionCommand

Azure:\
PS Azure:\>`

**To Reproduce**
Execute `New-AzureRmRoleDefinition -InputFile "C:\Users\prav_devops_provisioning.json"`

**Expected behavior**
Should create a role or throw proper error message indicating the issue in config.

**Environment summary**
Azure Cloud Powershell

**Additional context**
JSON file content
`
Azure:\
PS Azure:\> cat C:\Users\prav_devops_provisioning.json

[
        {
                "assignableScopes": [
                        ""/subscriptions/111-222-333-444/resourceGroups/prav-*/providers/Microsoft.ContainerRegistry/registries/prav-*/providers/Microsoft.Authorization/roleAssignments/*""
                ],
                "description": "DevOps",
                "name": "prav-DevOps",
                "id": null,
                "iscustom": true,
                "permissions": [
                        {
                                "actions": [
                                        "Microsoft.Authorization/roleAssignments/write",
                                        "Microsoft.Authorization/roleAssignments/delete"
                                ],
                                "dataActions": [],
                                "notActions": [
                                        "Microsoft.Authorization/*/Delete",
                                        "Microsoft.Authorization/*/Write",
                                        "Microsoft.Authorization/elevateAccess/Action"
                                ],
                                "notDataActions": []
                        }
                ],
                "roleName": "prav-DevOps"
        }
]
Azure:\
PS Azure:\>
`

**Comment by tjprescott** [comment]
This is not the repo for Azure Powershell.  Please post your issue here:
https://github.com/Azure/azure-powershell
