### ISSUE TITLE
Shouldn't the CLI extensions have an Install section?

### ISSUE THREAD

**Issue by cmendible** [Azure/azure-cli#6454]
Hi guys!

reading the documentation it's not clear that a "manual " installation is needed before using the commands. Therefore I miss a section where the install command is shown, something like: 

**To enable the extension run:**
`az extension add --name subscription`

What are your thoughts on this? 

Also If we come up with a standard way I can submit a pull request.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea3833d-6724-93a3-120a-6c855357acad
* Version Independent ID: 9c423dee-a9aa-b32b-2260-db47d9f639cf
* Content: [az](https://docs.microsoft.com/en-us/cli/azure/ext/subscription/?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/subscription/index.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/ext/subscription/index.yml)
* Service: **unspecified**
* Product: **unspecified**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
@dend can we get this on your backlog? It's not really actionable from the CLI side.

**Comment by gauravsaralMs** [comment]
similar issue: https://github.com/Azure/azure-cli-extensions/issues/976

**Comment by yonzhan** [comment]
add to S165.

**Comment by haroldrandom** [comment]
Is this section what you want https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/azure-cli-extensions-overview.md#install-extensions?
