### ISSUE TITLE
Setting VS account name, strips some characters from the account name : impacts az webapp deployment source config

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-cli#6459]
**Describe the bug**
az webapp deployment source config uses the library helper continuous_delivery_manger '_get_vsts_account_name ' to set the vsts account name, when using parameter --cd-project-url.
The method to parse the account name from the url uses python strip, that strips the characters (https) out of the account name i.e sisirap -> returns isirap

**To Reproduce**
Run the command:
az webapp deployment source config -n <> -g <> --repo-url <> --cd-account-create --cd-project-url <>

![cli](https://user-images.githubusercontent.com/13839372/40744108-72ed09c2-6408-11e8-9c46-eb9636b01fb4.jpg)

**Expected behavior**
The command doesn't fail due to incorrect account name
![repro](https://user-images.githubusercontent.com/13839372/40744154-9767c698-6408-11e8-9581-05627f3206f5.png)

**Additional context**
CC: @scottaddie

**Comment by panchagnula** [comment]
@yugangw-msft  can you help us find the right owner to fix this issue.

**Comment by yugangw-msft** [comment]
//cc: @jpricket, the fix should be made at pypi package [vsts-cd-manager](https://pypi.org/project/vsts-cd-manager/), a safer option would be `[len('https://'):]`

**Comment by jpricketMSFT** [comment]
+Vinod who owns the vsts-cd-manager now

**Comment by yugangw-msft** [comment]
Opened https://github.com/Microsoft/vsts-cd-manager/issues/21

**Comment by scottaddie** [comment]
@kuvinodms I tested the same command depicted in the screenshot above. I still have the problem. Does it take a while for the change to propagate?

**Comment by yugangw-msft** [comment]
@scottaddie,  how do you install CLI, through installers/apt-get? If yes, you need to wait till next week when we will release new installers including @kuvinodms's new version; if you use pip to acquire CLI, then you just ensure to get newer `vsts-cd-manager`

**Comment by scottaddie** [comment]
@yugangw-msft I'm doing everything from Azure Cloud Shell in the portal.

**Comment by scottaddie** [comment]
@yugangw-msft No problem. Do you know when next week, so I can check back then?

**Comment by yugangw-msft** [comment]
Based on the milestone info https://github.com/Azure/azure-cli/milestone/41, we will release on June 19
