### ISSUE TITLE
webapps: az webapp config set is missing support for 'virtual applications' & 'handler mapping' properties

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-cli#6463]
**Is your feature request related to a problem? Please describe.**
This is in reference to the issue here https://github.com/Azure/azure-cli/issues/3512

**Describe the solution you'd like**
Current work around has been to use az resource set, the settings is currently supported on the portal, but not Via CLI or powershell

**Describe alternatives you've considered**
rrent work around has been to use az resource set as seen here https://github.com/Azure/azure-cli/issues/3512

**Additional context**

**Comment by levilugato** [comment]
any news?

**Comment by panchagnula** [comment]
Don't have an ETA for this release yet, we however plan to support this on future releases.

**Comment by StingyJack** [comment]
much want. kind of annoying I cant compare and manage app service configs in one place.

**Comment by sdementen** [comment]
any workaround to set the virtualApplications property via the az cli ?
or is the only solution to use the portal ?

**Comment by StingyJack** [comment]
@sdementen - there are REST Apis available if you are feeling adventurous. https://docs.microsoft.com/en-us/rest/api/appservice/webapps/createorupdateconfiguration

**Comment by sdementen** [comment]
Yes, but it breaks a bit my az cli scripts...
If I were to monkey patch the current implementation to support this, where would be a good starting point (to copy/paste/adapt some code)?

**Comment by ahmedchater** [comment]
For others looking to set virtual applications for webapps in Azure using the Azure CLI task in an Azure DevOps pipeline, I described the approach I took here:

https://github.com/Microsoft/azure-pipelines-tasks/issues/5125#issuecomment-498685695

Basically I use az webapp config show, grab and convert the json, create n copies of the virtualapplications object, update them, then reapply using az webapp config set and the generic-configurations property. I would much prefer a more direct method for creating virtual apps using CLI commands, but this is my workaround.

**Comment by panchagnula** [comment]
Setting this for the next milestone.

**Comment by panchagnula** [comment]
changing the ETA

**Comment by yungezz** [comment]
hi @panchagnula what's the new ETA on this now?

**Comment by panchagnula** [comment]
No ETA for this since there is an existing workaround. Thanks!

**Comment by panchagnula** [comment]
We should get this post //BUILD milestones

**Comment by awentzel** [comment]
What's the ETA on this?

**Comment by seligj95** [comment]
Thank you for the feedback but we will not be doing this at this time. Please continue to use the az resource commands as the workaround.
