### ISSUE TITLE
Question: policy on backward compatibiltiy of Azure CLI 2

### ISSUE THREAD

**Issue by nporaMep** [Azure/azure-cli#6464]
I can't find anywhere your policy on backward compatibility and I see quite a lot breaking changes here https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?view=azure-cli-latest

Is Azure CLI a released product or in some alpha/beta/preview state now?
Do you reckon you will have similar rate of breaking changes in future?

I need to ship deployment script to deploy environment in Azure and need to be sure that it works for a few years. Should I not use Azure CLI 2 for such scenario? Right now it seems the only option is to ship concrete version of desktop Azure CLI installer together with script and shell.azure.com is not reliable.

**Comment by tjprescott** [comment]
@twitchax @johanste @mayurid for comment.

**Comment by dsparkplug** [comment]
I have also noticed that there are many breaking changes in every point release. It is generally considered good practice that changes which break backwards compatibility are only introduced in a major versions (see [https://semver.org/](https://semver.org/) or at least in minor versions.

We are planning to call the Azure CLI from actions in our CI server. This can soon become unworkable if we have to ship a new release for every point release of the `az` command line.

**Comment by tjprescott** [comment]
@achandmsft @yugangw-msft for comment.

**Comment by fengzhou-msft** [comment]
Previously we only update patch version for any changes in a regular release. We're about to change that. More context [here](https://github.com/Azure/azure-cli/blob/8e076bb75603115fa59cb2753e49f5a182613baf/doc/version_management.md).
