### ISSUE TITLE
Allow users to define content-type in batch upload

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#6466]
Reference:
https://github.com/Azure/azure-cli/issues/6402
https://github.com/Azure/azure-cli/issues/6257

Ideas:
1. Allow `--content-type` accept multiple file extension to content type pairs.
2. Allow `--content-type-map` accept a configure file.
3. Allow a configuration file under `.azure` folder.
4. Allow a configuration file under the source folder.

**Comment by limingu** [comment]
Azcopy is supporting --content-type. The CLI is planning to migrate Azcopy for the storage upload.
--content-type string                  specifies content type of the file. Implies no-guess-mime-type.

**Comment by tjprescott** [comment]
@limingu since this issue was created internally by the time, you can close this if we don't plan to implmement.

**Comment by Juliehzl** [comment]
@zezha-msft Can you take a look at azcopy? It looks it doesn't work with content-type and it still use file extension.

**Comment by yonzhan** [comment]
@zezha-msft any update?

**Comment by zezha-msft** [comment]
Hi @Juliehzl @yonzhan sorry for the delay (I've been on leave), could you please show the command that you used?

**Comment by Juliehzl** [comment]
> Hi @Juliehzl @yonzhan sorry for the delay (I've been on leave), could you please show the command that you used?

Hi @zezha-msft, it is resolved in new azcopy! thanks for your reply!
