### ISSUE TITLE
Question: az login with blank password

### ISSUE THREAD

**Issue by nporaMep** [Azure/azure-cli#6468]
I can do
**az login -u "user" -p "password"**

And I found that it works with any password as long as user is currently logged in user into Windows (which is also Microsoft and/or Azure account".

but it doesn't work with just **-p** or **-p ""** or **no -p**.
In case of **-p** or **-p ""** it gives usage error.
In case of **no -p** it goes into interactive mode and asks for password.

In general fact that any password works in that scenario is a feature by design or a bug?

**Comment by tjprescott** [comment]
I was able to repro using my @microsoft.com login and can confirm that after using `az account clear` I couldn't log in with an incorrect password (although the error suggested my username was wrong when it was my password).

**Comment by nporaMep** [comment]
Ok, all good then, this can be closed.
