### ISSUE TITLE
Missing port mapping such as Docker's -p 8080:80

### ISSUE THREAD

**Issue by RolfEleveld** [Azure/azure-cli#6476]
I am missing a port-mapping capacity or perhaps the documentation to achieve the same as Docker's port mapper.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e5d1da7-7c4f-c9e6-e4b9-a30407675acf
* Version Independent ID: ba32e12d-8283-f980-e1d0-1ca2a75a5152
* Content: [az container](https://docs.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest#az-container-create)
* Content Source: [src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py)
* Service: **container-service**
* Product: **unspecified**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by samkreter** [comment]
@RolfEleveld we currently do not support port mappings. The exposed ports on the container group must match the exposed ports of the container. 

This is a commonly asked feature. You can upvote it here: https://feedback.azure.com/forums/602224-azure-container-instances
