### ISSUE TITLE
Possible mismatch between the example and the syntax in documentation

### ISSUE THREAD

**Issue by lrodriguez2002cu** [Azure/azure-cli#6477]
While the syntax is:
 az sf application certificate add --cluster-name
                                  --resource-group

the example included uses the command:
az sf cluster application certificate add -g group-name -n cluster1  --secret-identifier 'https://{KeyVault}.vault.azure.net/secrets/{Secret}'

Including the "modifier" [cluster] in the command. Is it an error? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc8df7f4-d9e3-87cc-0283-e8d073459785
* Version Independent ID: 94ea6ce4-5f08-8941-8ffd-5699a5b5e180
* Content: [az sf application certificate](https://docs.microsoft.com/en-us/cli/azure/sf/application/certificate?view=azure-cli-latest#az-sf-application-certificate-add)
* Content Source: [latest/docs-ref-autogen/sf/application/certificate.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/sf/application/certificate.yml)
* Service: **service-fabric**
* Product: **unspecified**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
```
Arguments
    --cluster-name --name -n [Required] : Specify the name of the cluster, if not given it will be
                                          same as resource group name.
    --resource-group -g      [Required] : The resource group name.
```

You can use `-n`, `--name` or `--cluster-name` to identify the cluster in this case, so this would not be an issue.
