### ISSUE TITLE
How to add additional Owner to newly registered app through CLI

### ISSUE THREAD

**Issue by vir2albulb** [Azure/azure-cli#6481]
Hi,

I'm trying to create AD APP through CLI and modify list of Owner for newly created object however I was unable to find answer. Basically PS module provides a way to do it (https://docs.microsoft.com/en-us/powershell/module/azuread/add-azureadapplicationowner?view=azureadps-2.0) however I need to apply same action with CLI. Can someone help me figure out?

Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 921aa920-c25f-5227-aabb-49116da38fa7
* Version Independent ID: 9b5a53ad-edf8-4d89-f8e6-cde01b7866f6
* Content: [az ad app](https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
This is in the area of graph ownership support we plan to work on in the near furture.
//cc @mayurid

**Comment by yugangw-msft** [comment]
Same thing with #6258
