### ISSUE TITLE
how to save VM configuration before deleting, in order to recreate it with the same configuration later

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#6482]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tjprescott** [comment]
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/tutorial-custom-images

**Comment by alexeyshishkin01** [comment]
oh, no - my question is about https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/virtual-machines/linux/troubleshoot-recovery-disks-portal.md#create-vm-from-original-hard-disk
I have to recreate VM by attaching the disk, but I need this VM to be exactly of the same configuration as before deleting.
