### ISSUE TITLE
The specified resource does not exist.ErrorCode: ResourceNotFound

### ISSUE THREAD

**Issue by Epoxboy** [Azure/azure-cli#6483]
**Describe the bug**
Well this might not be a bug, but I have the problem when I try to generate a container SAS and use it to do some blob operations, such as upload, delete...

**To Reproduce**
1, create container access policy
az storage container policy create --container-name $STORAGE_CONTAINER_NAME --name id5 --account-key $STORAGE_ACCOUNT_KEY --account-name $STORAGE_ACCOUNT_NAME --expiry 2023-6-2 --permissions rwd

2, generate container SAS
az storage container generate-sas --name $STORAGE_CONTAINER_NAME --account-key $STORAGE_ACCOUNT_KEY --account-name $STORAGE_ACCOUNT_NAME --expiry 2023-6-2 --policy-name id5

then i can get my SAS.

But when try to use this SAS to upload, delete blobs in the container, it always returns 
"The specified resource does not exist.ErrorCode: ResourceNotFound"

**Expected behavior**
blob operations success as expectation

**Environment summary**
Docker microsoft/azure-cli image, latest

**Additional context**
run the command line inside the docker container.

**Comment by ZachTB123** [comment]
I am experiencing a similar issue when trying to create a storage container. Creating the storage account succeeds but creating the storage container (az storage container create ...) returns ResourceNotFound.

**Comment by troydai** [comment]
@williexu

**Comment by williexu** [comment]
@Epoxboy can you try generating your sas without specifying the expiration date? That should be picked up from the access policy?

@ZachTB123 I don't know why you can't create a storage container... Please check your account name spelling.

**Comment by Epoxboy** [comment]
@williexu  thank you for the reply! I tried, but still same error.

**Comment by williexu** [comment]
@Epoxboy resource not found is usually due to reference a resource that doesn't exist. Before you do your blob operation, can you first do a `az storage account/container/blob show` on resources to verify they are present?

**Comment by limingu** [comment]
@Epoxboy please reopen the issue when you have more details of the repro.

I repro as your step 1 and 2. I can use the SAS to upload the file successfully.
