### ISSUE TITLE
Allow selecting the protocol when creating an ACI container (az container create)

### ISSUE THREAD

**Issue by p-** [Azure/azure-cli#6487]
**Is your feature request related to a problem? Please describe.**
At the moment [it seems](https://docs.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest) not to be possible to specify the protocol of a port when creating a container with `az container create`. It is possible to specify the ports with `--ports`, but the protocol is always TCP.

**Describe the solution you'd like**
Maybe support it in the same way Docker let's you specify the protocol. E.g. `--ports 3000/udp` or another way that suits the az cli tools better.

**Describe alternatives you've considered**
Working alternatives are:
* start container via"Container instances" UI of the Azure Portal
* start container with template JSON file

**Comment by samkreter** [comment]
--protocol has been added to the latest release of the CLI which is availble in [Cloud Shell](https://shell.azure.com). @tjprescott Please close this issue.
