### ISSUE TITLE
What does upgrade option mean on the azure portal?

### ISSUE THREAD

**Issue by akramwaseem** [Azure/azure-cli#6488]
Hi, Lets say I have a VMSS which is running 4 VMs and I deployed them using ARM template.
now I made some changes to cloud init files or some other files which are used by the VMSS. Here there are two things which I can do
1) I can delete the whole resource group and redeploy the updated ARM Templates which is like fresh installs the VMSS from scratch.which is good.
2) I can use two options which I can see the portal. first upgrade the VMs to latest model and after that I can do reimage which upgrades the VMS to the latest image.

This works only after pushing the latest changes and upgrading the VMs to latest model and then reimage.
Might be tricky but there is no proper documentation I can find.
I don't see any az commands which can be used to do both upgrade and reimage using the command line. I can see the upgrade but it is kind of tricky and not sure what does the rolling upgrade do which is mentioned in the commands in the above document.
Also I see there is no reimage az command available ?
Can someone look at these and update the documentation please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0408c294-207a-2b72-7b93-e09121602b75
* Version Independent ID: 852cb67b-70c6-b811-3b0a-5d5b84b8a911
* Content: [az vmss](https://docs.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machine-scale-sets**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
The comments from https://github.com/Azure/azure-cli/issues/6388#issuecomment-394583422 should have the majority clarified. 
For `I don't see any az commands which can be used to do both upgrade and reimage using the command line. `, this is by-design as upgrade and reimage are different actions which we don't expect lots of users would do them together
Please let me know if there are anything else not covered

**Comment by akramwaseem** [comment]
seems good.
