### ISSUE TITLE
az acr build --no-logs returns before the build is pushed to ACR

### ISSUE THREAD

**Issue by sabbour** [Azure/azure-cli#6491]
**Describe the bug**
Doing `BUILD_ID=$(az acr build -r <registry> -g <resource group> -t <registry>.azurecr.io/foo/bar:{{.Build.ID}} ./foobar --no-logs --query buildId)` returns the buildId before it actually makes into the registry.

This causes issues in automation, for example if you follow that command with `helm install foobar/charts/foobar --set image.repository=<registry>.azurecr.io/foo/bar --set image.tag=$BUILD_ID` because that image didn't make it to the registry yet and it might be still building/pushing.

**Expected behavior**
The cli command not returning before it actually completes, unless we pass an argument like `--no-wait`.

**Environment summary**
Homebrew on MacOS
azure-cli (2.0.32)
acr (2.0.24)

**Comment by ehotinger** [comment]
By default it blocks and streams logs until the build is complete. Using `--no-logs` immediately returns, it's like `--no-blocking`, so it's expected right now. If you don't care about the logs you could just redirect it to `/dev/null` for now and use the current behavior to block without "seeing" the logs.

What do you think would make it better; better docs on what the parameter does; change the default; a different parameter name?
