### ISSUE TITLE
az acr build --no-logs still returns a line of log, distrupting --query

### ISSUE THREAD

**Issue by sabbour** [Azure/azure-cli#6492]
**Describe the bug**
`az acr build --no-logs` should not return any logs to the console. This currently returns the following:

```
BUILD_ID=$(az acr build -r sabbour -g acr-rg -t sabbour.azurecr.io/phippy/lighthouse:{{.Build.ID}} ./lighthouse -o tsv  --query buildId --no-logs)

echo $BUILD_ID

Sending build context (2.675 KiB) to ACR.
aa9
```

**Expected behavior**
Only the queried buildID (or other field) is returned.

**Environment summary**
Homebrew on MacOS
azure-cli (2.0.32)
acr (2.0.24)

**Comment by ehotinger** [comment]
What's the use case here? Right now it will skip logs from the build itself but some pieces that you need to view logs, etc. are returned.
