### ISSUE TITLE
incorrect parameters processing at az vm run-command invoke 

### ISSUE THREAD

**Issue by AlexL-CC** [Azure/azure-cli#6493]
**Describe the bug**
[Here](en-us/cli/azure/vm/run-command?view=azure-cli-latest)  I see: 

--parameters
Space-separated parameters in the format of '[name=]value'.

When I try to follow this, it does not work:

```
.... --parameters wsci=$WorkSpace.CustomerId.ToString() psk=$Keys.PrimarySharedKey.ToString()
At line:1 char:191
+ ... > /tmp/qqq" --parameters wsci=$WorkSpace.CustomerId.ToString() psk=$K ...
+                                                                  ~
An expression was expected after '('.
At line:1 char:229
+ ... WorkSpace.CustomerId.ToString() psk=$Keys.PrimarySharedKey.ToString()
+                                                                         ~
An expression was expected after '('.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExpectedExpression
```

**To Reproduce**
```
$WorkSpace = New-AzureRmOperationalInsightsWorkspace -ResourceGroupName $ResourceGroupName -Name MyOIWorkspace -Location "$Location" -Sku "Standard"

$Keys = Get-AzureRmOperationalInsightsWorkspaceSharedKeys -ResourceGroupName  $ResourceGroupName -Name MyOIWorkspace

az vm run-command invoke -g $ResourceGroupName -n $VmName --command-id RunShellScript --scripts "echo wsci $wsci psk $psk>> /tmp/qqq" --parameters wsci=$WorkSpace.CustomerId.ToString() psk=$Keys.PrimarySharedKey.ToString()
```

**Expected behavior**
file /var/lib/waagent/run-command/download/XX/script.sh should contain something like

export wsci=055...-the-id-here-...6939 
export psk=saXaZ...the-key-here...Svw==
echo wsci $wsci psk $psk >> /tmp/qqq

**Environment summary**
on my desktop:
az --version
azure-cli (2.0.30)

acr (2.0.22)
acs (2.0.30)
advisor (0.5.0)
appservice (0.1.30)
backup (1.1.0)
batch (3.1.11)
batchai (0.1.6)
billing (0.1.7)
cdn (0.0.13)
cloud (2.0.12)
cognitiveservices (0.1.11)
command-modules-nspkg (2.0.1)
configure (2.0.14)
consumption (0.2.2)
container (0.1.20)
core (2.0.30)
cosmosdb (0.1.19)
dla (0.0.18)
dls (0.0.20)
eventgrid (0.1.11)
eventhubs (0.1.1)
extension (0.0.11)
feedback (2.1.0)
find (0.2.8)
interactive (0.3.18)
iot (0.1.18)
keyvault (2.0.20)
lab (0.0.20)
monitor (0.1.4)
network (2.0.26)
nspkg (3.0.2)
profile (2.0.21)
rdbms (0.2.0)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.26)
role (2.0.21)
servicebus (0.1.1)
servicefabric (0.0.11)
sql (2.0.24)
storage (2.0.30)
vm (2.0.29)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\allut1\.azure\cliextensions'

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

Ubuntu 16.04.4 LTS on the target VM

**Comment by yugangw-msft** [comment]
You probably should get POSH script out of the way first, and use fixed argument values on the CLI run command. If it doesn't work in the plain command window, let me know.
Error like `An expression was expected after '('` has nothing to do CLI.

**Comment by AlexL-CC** [comment]
@yugangw-msft  Do you mean that?
PS O:\_my\azure\oms> echo $WorkSpace.CustomerId.ToString()
5fe1d........d87f7ee

PS O:\_my\azure\oms> echo $Keys.PrimarySharedKey.ToString()
tW2c.......ZHw==

**Comment by ConnorDickson** [comment]
I had the same issue and it was resolved [here](https://stackoverflow.com/questions/56578122/azure-cli-run-command-invoke-runpowershellscript-with-parameters?noredirect=1#comment99734192_56578122) on stackoverflow. Is it possible to get the documentation updated to clarify?

**Comment by adewaleo** [comment]
> @yugangw-msft Do you mean that?
> PS O:_my\azure\oms> echo $WorkSpace.CustomerId.ToString()
> 5fe1d........d87f7ee
> 
> PS O:_my\azure\oms> echo $Keys.PrimarySharedKey.ToString()
> tW2c.......ZHw==

@AlexL-CC this looks like a powershell issue and not a cli issue (The error is being raised by pwsh).

Have you tried passing in the raw value to the cli command instead of mixing powershell syntax with the CLI. 

fyi: the CLI is cross platform and expects string arguments (just like in bash). You can likely pass variables that contain / expand to strings.

**Comment by adewaleo** [comment]
Closing this given the previous comment and lack of response from the original poster.
