### ISSUE TITLE
Support 2018-05-01 version of Microsoft.Resources API

### ISSUE THREAD

**Issue by Tiano2017** [Azure/azure-cli#6498]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Need to subscription level deployment APIs introduced in Microsoft.Resources/2018-05-01. 

**Describe alternatives you've considered**
No

**Additional context**
swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/2976
Python SDK PR: https://github.com/Azure/azure-sdk-for-python/pull/2500

**Comment by tjprescott** [comment]
@kristapratico this would be one of the high priority items when you return.

**Comment by zhoxing-ms** [comment]
The version we used is ‘2019-07-01’, so we don't need to update it anymore.
