### ISSUE TITLE
Adding a tag to a resource is unacceptably slow

### ISSUE THREAD

**Issue by nwohlgemuth** [Azure/azure-cli#6499]
**Describe the bug**
Running 'az resource tag --id ID --tags KEY=VALUE' or running the equivalent update operation (e.g. 'az network public-ip update --tags') consistently takes just over 30 seconds

**To Reproduce**
Run 'az resource tag --id ID --tags KEY=VALUE' and time the command. It will take just over 30 seconds.

**Expected behavior**
Adding a tag to a resource through the Azure portal takes a few seconds. The Azure CLI shouldn't be significantly (10x) slower.

**Environment summary**
Azure CLI 2.0.33 on both Windows and Linux 

**Additional context**
Running with the '--debug' operation suggests the following. First, the CLI issues several GET and POSTS requests to Azure to tell Azure to update the resource's tags. Then the CLI waits for 30 seconds (I assume waiting for Azure to complete the operation). Then the CLI issues several GET requests to Azure (I assume to see if the tag operation was performed successfully). Is there a way to configure the 30 second wait because it seems like it could be shortened significantly?

**Comment by hichemaichour** [comment]
Is there any work-around?

**Comment by aaronjpitty** [comment]
Yeah this is appalling, I can add a single tag in seconds on the portal but via the CLI running with --debug I see about; `command ran in 94.441 seconds.`

Also looking for a workaround if possible.

**Comment by francovanzyl** [comment]
Has there been any updates or workarounds to this?

**Comment by magnus-longva-bouvet** [comment]
Still a problem in 2023. The tag is applied within seconds after running the command, but it can take several minutes before the CLI finishes the operation.

**Comment by mcdonamw** [comment]
Just ran into this problem myself.  Is this github issue tracker even being monitored?

**Comment by magnus-longva-bouvet** [comment]
When I did have this issue, it was behind a HTTP proxy. That might or might not have been relevant.
