### ISSUE TITLE
Tab completion for VM extension names is incorrect

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#650]
Actual output:

```
$ az vm extension show -g derek1 --vm-name dvmencrypt -n <TAB>
dvmencrypt/AzureDiskEncryptionForLinux               dvmencrypt/VMBackupForLinuxExtension                 swarm-master-80E5A796-0/linuxdiagnostic
dvmencrypt/Microsoft.Insights.VMDiagnosticsSettings  swarm-master-80E5A796-0/configuremaster    
```

Expected output:

```
$ az vm extension show -g derek1 --vm-name dvmencrypt -n <TAB>
AzureDiskEncryptionForLinux               VMBackupForLinuxExtension                 linuxdiagnostic
Microsoft.Insights.VMDiagnosticsSettings  configuremaster    
```

The completer for the `vm_extension_name` parameter of `vm extension` command is defined as `completer=get_resource_name_completion_list('Microsoft.Compute/virtualMachines/extensions')` which looks correct.

However, ARM returns vm extension names prefixed by the vm name (see below) which causes tab completion to show results in the format <vm_name>/<extension_name>.

```
$ az resource list -g derek1 --query "[?type=='Microsoft.Compute/virtualMachines/extensions'].{name:name, type:type}"
[
  {
    "name": "dvmencrypt/AzureDiskEncryptionForLinux",
    "type": "Microsoft.Compute/virtualMachines/extensions"
  },
  {
    "name": "dvmencrypt/Microsoft.Insights.VMDiagnosticsSettings",
    "type": "Microsoft.Compute/virtualMachines/extensions"
  },
  ...
]
```

---

Possible solution, don't use the generic `get_resource_name_completion_list` method for this completer and instead create a method that removes the vm name prefix.

**Comment by johanste** [comment]
I believe that the root cause cause is that the instance of the extension associated with the VM does in fact have a name. Consider the ability to apply the script extension multiple times.
