### ISSUE TITLE
I'm getting an error when trying to run this example

### ISSUE THREAD

**Issue by davidlbyrne** [Azure/azure-cli#6505]
$ az webapp deployment source config-zip -g devops -n my-node --src my-node3.zip 
Zip deployment https://my-node.scm.azurewebsites.net/api/zipdeploy failed with status code '500' and reason '&lt;html&gt;&lt;head&gt;&lt;title&gt;500 - The request timed out.&lt;/title&gt;&lt;/head&gt;&lt;body&gt;  &lt;font color ="#aa0000"&gt;         &lt;h2&gt;500 - The request timed out.&lt;/h2&gt;&lt;/font&gt;  The web server failed to respond within the specified time.&lt;/body&gt;&lt;/html&gt;'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b238907f-0676-8e20-66ac-89a542aa8c20
* Version Independent ID: 60659c33-bfea-eecb-6681-9240191820be
* Content: [az webapp deployment source](https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/source?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/deployment/source.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/webapp/deployment/source.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
//CC: @panchagnula

**Comment by davidlbyrne** [comment]
Removing the BOM fixed the encoding issue. Maybe this should be added to the documentation or a fix to handle the BOM should be applied.

**Comment by panchagnula** [comment]
Thanks for the update @davidlbyrne. I am guessing .BOM is the file format you were trying to use? we  currently we only support .war & .zip formats. Will update help & our commandline to throw a better message for non- supported formats.
