### ISSUE TITLE
az lock list and az lock show do not seem to reveal the resource which is locked.

### ISSUE THREAD

**Issue by kbroughton** [Azure/azure-cli#6508]
bash-4.4# az lock show -n "MY-DEV-LOCK"
{
  "id": "/subscriptions/&lt;mysubscription&gt;/providers/Microsoft.Authorization/locks/MY-DEV-LOCK",
  "level": "CanNotDelete",
  "name": "MY-DEV-LOCK",
  "notes": "Locks the resource to protect from accidental deletion.",
  "owners": null,
  "type": "Microsoft.Authorization/locks"
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62eb3c9f-6934-17b1-5639-c738c1e5cdf3
* Version Independent ID: 1762377d-18df-77c4-bf83-398eec407af9
* Content: [az lock](https://docs.microsoft.com/en-us/cli/azure/lock?view=azure-cli-latest#az-lock-show)
* Content Source: [latest/docs-ref-autogen/lock.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/lock.yml)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
You can tell the resource that was locked by looking at the ID of the lock. In your case, you have locked your entire subscription. If you have a resource locked, you'd see the resource ID, followed by the `Microsoft.Authorization/locks/{lock-name}` piece.

**Comment by javgarces** [comment]
By the "/providers/Microsoft.Authorization/locks/{lock-name}" piece, to be exact.
