### ISSUE TITLE
I don't see offers with Azure CLI

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#6515]
**Describe the bug**

root@Alexey-HP:~# az vm image list --location northeurope --publisher OpenLogic --offer CentOS$ --all

<EMPTY OUTPUT>

root@Alexey-HP:~# az vm image list --location northeurope --publisher OpenLogic
You are viewing an offline list of images, use --all to retrieve an up-to-date list
Offer    Publisher      Sku  Urn                          UrnAlias    Version
-------  -----------  -----  ---------------------------  ----------  ---------
CentOS   OpenLogic      7.3  OpenLogic:CentOS:7.3:latest  CentOS      latest

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

root@Alexey-HP:~# az --version | head -1
azure-cli (2.0.34)

**Additional context**

**Comment by yugangw-msft** [comment]
works for me
```bash
(env) D:\temp\azure-cli>az vm image list --location northeurope --publisher OpenLogic
You are viewing an offline list of images, use --all to retrieve an up-to-date list
[
  {
    "offer": "CentOS",
    "publisher": "OpenLogic",
    "sku": "7.3",
    "urn": "OpenLogic:CentOS:7.3:latest",
    "urnAlias": "CentOS",
    "version": "latest"
  }
]
```

**Comment by alexeyshishkin01** [comment]
so only one offer?
of older version of 7.3?
it used to be at least 20 options to choose from

**Comment by yugangw-msft** [comment]
Ah, i see, you 2nd command doesn't include `--all` which is needed for CLI to query from live service

**Comment by alexeyshishkin01** [comment]
but what about my first command empty output (it used to work for me before yesterday)
az vm image list --location northeurope --publisher OpenLogic --offer CentOS$ --all

**Comment by alexeyshishkin01** [comment]
or this one

az vm image list \
--location northeurope \
--publisher OpenLogic \
--offer CentOS$ \
--sku ^7.* \
--all

**Comment by yugangw-msft** [comment]
you can remove the `$` from the offer. CLI doesn't do regular expression matching rather plain case insensitive partial string match.

**Comment by alexeyshishkin01** [comment]
yes, I can but in this case I'll have other offers which I don't need
and besides it works well in 2.32
