### ISSUE TITLE
EntryPointNotFoundException with Autofac

### ISSUE THREAD

**Issue by Inspyro** [Azure/azure-cli#6522]
**Describe the bug**
When referencing Autofac in an old version in a referenced project of the function app, and referecing a newer version of Autofac in the function app via nuget we get an EntryPointNotFoundException that is rather strange.

**To Reproduce**
Use the attached repro sample, Press F5 to debug the function app -> see the EntryPointNotFoundException
[FunctionApp1_Repro.zip](https://github.com/Azure/azure-cli/files/2080796/FunctionApp1_Repro.zip)

**Expected behavior**
No Exception is thrown and the function succeeds

**Environment summary**
Visual Studio 2017 (15.7.3), Windows 10 1703, .NET 47, Azure CLI Tools 1.0.12.1

**Additional context**
The error seems to be related to using multiple versions of a nuget package in different projects.

**Comment by tjprescott** [comment]
This is not the correct repo for this issue. @panchagnula for redirection.

**Comment by panchagnula** [comment]
@ahmelsayed or @davidebbo this seems to be a functionapp using Autofac which I am not familiar with can one of you please help navigate this to the right GitHub and/or resolution. Thank you.
