### ISSUE TITLE
`az container export` specifies old apiVersion in resultant YAML file

### ISSUE THREAD

**Issue by mmacy** [Azure/azure-cli#6525]
**Describe the bug**
Although current (at time of this bug report) `apiVersion` for Azure Container Instances is **2018-06-01**, the `az container export` command yields an `apiVersion` value of **2018-02-01-preview**.

**To Reproduce**
1. Deploy a [container group via YAML](https://docs.microsoft.com/azure/container-instances/container-instances-log-analytics#create-container-group) that specifies `apiVersion: 2018-06-01`
1. Export the container group configuration to YAML using the `az container export` command
1. Open the resultant YAML file and note that the first line in the exported file is `apiVersion: 2018-02-01-preview`, instead of the deployed version of 2018-06-01.

**Expected behavior**
The export operation should result in a file that specifies the same `apiVersion` as that which was used when the container group was initially deployed.

**Environment summary**
* install via apt-get
* `az --version`: 2.0.34
* OS: Ubuntu 18.04; WSL Ubuntu 16.04
* Shell: bash (18.04), Bash on Windows (WSL)

**Additional context**
Console output from WSL session:

```console
mmacy@MININT-QVP3FHV:~$ head -n 3 api-test-002.yaml
apiVersion: 2018-06-01
location: eastus
name: api-test-002
mmacy@MININT-QVP3FHV:~$ az container create -g rg604 -n api-test-002 -f api-test-002.yaml | head
{
  "id": "/subscriptions/FEEDBEEF-4223-4aa0-bf30-2cd5de52e554/resourceGroups/rg604/providers/Microsoft.ContainerInstance/containerGroups/api-test-002",
  "identity": null,
  "kind": null,
  "location": "eastus",
  "managedBy": null,
  "name": "api-test-002",
  "plan": null,
  "properties": {
    "containers": [
mmacy@MININT-QVP3FHV:~$ az container export -g rg604 -n api-test-002 -f api-test-002-EXPORT.yaml
mmacy@MININT-QVP3FHV:~$ head -n 3 api-test-002-EXPORT.yaml
apiVersion: 2018-02-01-preview
location: eastus
name: api-test-002
mmacy@MININT-QVP3FHV:~$
```

**Comment by samkreter** [comment]
Currently the API version is based on the SDK version for exporting. This will be updated in an upcoming release.

**Comment by samkreter** [comment]
#6650 Fixes this API version

**Comment by samkreter** [comment]
@tjprescott This issue was fixed with the latest. Please close.
