### ISSUE TITLE
WebApp deployment crashing after WebApp stop

### ISSUE THREAD

**Issue by williamthiago** [Azure/azure-cli#6527]
**Describe the bug**
Sometimes during a zip deployment, az crashes with the following exception:

```
ERROR: Object of type 'frozenset' is not JSON serializable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 201, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 134, in out
    output = formatter(obj)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 40, in format_json
    separators=(',', ': ')) + '\n'
  File "/opt/az/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/opt/az/lib/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/opt/az/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/opt/az/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/opt/az/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/opt/az/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/opt/az/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/opt/az/lib/python3.6/site-packages/knack/output.py", line 32, in default
    return json.JSONEncoder.default(self, o)
  File "/opt/az/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'frozenset' is not JSON serializable

```

My guess's because the application isn't fully stopped by `az webapp stop` command, so there's a DLL blocked by WebApp IIS.

> Edit:
> I switched `sleep` command for: `while [[ "$(az webapp show --name ${AZURE_APP_WEB} --resource-group ${AZURE_RG} --query 'state' --output tsv)" != "Stopped" ]]; do sleep 2; done` and the problem still happens. Probably it's not related to `webapp stop`.

**To Reproduce**
This behavior is inconstant, but it occurs in 1 out 10 tries in my environment.

1 - Stop webapp
`az webapp stop --name ${AZURE_APP_WEB} --resource-group ${AZURE_RG}`

2 - Try to upload a new version zip 
`az webapp deployment source config-zip --name ${AZURE_APP_WEB} --resource-group ${AZURE_RG} --src api.zip`

**Expected behavior**
I expected the webapp fully stop after `az webapp stop` command and deployment succeed.

**Environment summary**
Bitbucket pipelines using official microsoft/dotnet:2.1-sdk image as base. Az Cli is installed with:
```
RUN apt update && \
    apt install lsb-release apt-transport-https -y && \
	AZ_REPO=$(lsb_release -cs) && \
    echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | \
    tee /etc/apt/sources.list.d/azure-cli.list && \
	apt-key adv --keyserver packages.microsoft.com --recv-keys 52E16F86FEE04B979B07E28DB02C46DF417A0893 && \
	curl -L https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
	apt update && \
	apt install azure-cli
```

**Additional context**
I tried to add a `sleep 5` command after the stop, the number of errors considerably decreased.

**Comment by yugangw-msft** [comment]
@panchagnula, we might have a bug [here](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py#L186-L189) that the initial response might not be json data and that will break CLI. I suggest you ensure it is a json object say `response = response.json()`
```python
    response = response.json()  
    if response['status'] != 4:
        logger.warning(response['progress'])
        response = _check_zip_deployment_status(deployment_status_url, authorization)
    return response
```

**Comment by yugangw-msft** [comment]
@panchagnula , i will take this one unless you are interested

**Comment by panchagnula** [comment]
Sure thank you.
