### ISSUE TITLE
az function create with --plan parameter does not support resource id as documentation describes

### ISSUE THREAD

**Issue by evandropaula** [Azure/azure-cli#6532]
**Describe the bug**
It is not possible to create an Azure Function App in a resource group different than the on that holds the Application Service Plan by using az function create with --plan parameter using the Azure Function Plan resource id (e.g. /subscriptions/{Subscription Id}/resourceGroups/{Resource Group Name}/providers/Microsoft.Web/serverFarms/{App Service Plan Name})

Command:
az functionapp create --resource-group "abc" --plan "/subscriptions/{Subscription Id}/resourceGroups/azfuncrg/providers/azfunc" --name "functioappname" --storage-account "/subscriptions/{Subscription Id}/resourceGroups/azfuncrg/providers/Microsoft.Storage/storageAccounts/azfuncstorage"

Last part of output with response and error message, where it looks like the resource id is not being parsed properly:
...
msrest.http_logger : Response status: 404
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'x-ms-failure-cause': 'gateway'
msrest.http_logger :     'x-ms-request-id': 'd4ebc73a-a7ca-45b2-bd59-710aeea1faf2'
msrest.http_logger :     'x-ms-correlation-request-id': 'd4ebc73a-a7ca-45b2-bd59-710aeea1faf2'
msrest.http_logger :     'x-ms-routing-request-id': 'WESTUS2:20180608T002628Z:d4ebc73a-a7ca-45b2-bd59-710aeea1faf2'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger :     'Date': 'Fri, 08 Jun 2018 00:26:28 GMT'
msrest.http_logger :     'Content-Length': '139'
msrest.http_logger : Response content:
msrest.http_logger : b'{"error":{"code":"ResourceNotFound","message":"The Resource \'Microsoft.Web/serverFarms/azfunc\' under resource group \'abc\' was not found."}}'
The plan 'azfunc' doesn't exist

This scenario is supported according to documentation https://docs.microsoft.com/en-us/cli/azure/functionapp?view=azure-cli-latest#az-functionapp-create.

**To Reproduce**
1. Create resource group A and adding a service plan to it;
2. Create resource group B where the Azure Function App will be placed/created;
3. Create am Azure Storage Account in resource group B;
4. Run the following command on the Azure Cloud Shell or in your local machine to create a new Azure Function App in resource group B:
az functionapp create --resource-group "**B**" --plan "/subscriptions/{Subscription Id}/resourceGroups/**A**/providers/Microsoft.Web/serverFarms/{App Service Plan}" --name "{Azure Function App Name}" --storage-account "{Storage Account Name}"

**Expected behavior**
Azure Function App is created successfully.

**Environment summary**
Azure CLI Version 2.0
Cloud Shell or Windows 10 Command Prompt

**Additional context**

**Comment by yugangw-msft** [comment]
remove `webapps` tag. webapp handles correctly the cross resource group scenario, this bug is functionapp only

**Comment by yugangw-msft** [comment]
Fixed, thanks @theMichaelB

**Comment by sausagedogcoffee** [comment]
![Image](https://github.com/user-attachments/assets/a3cfb983-abf7-4d7e-b701-c6095a831997)


![Image](https://github.com/user-attachments/assets/7a252eb2-066c-4170-b1c5-f8e768dee369)

Deployment via the portal works without issue
