### ISSUE TITLE
Subscription nicknames

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#654]
I've got maybe between four and six subscriptions on my account. It's a hassle to `az account list` and `az account set "Some Really Long Name I Never Remember"` or to look up the GUID and use it.

Not a super important feature, but it would be nice if I could give my subscriptions nicknames so I could just do `az account set dev` and `az account set prod` or what not.

I know that technically I can do this myself by changing the subscription's name in the json on disk... but then I lose the real subscription name which is convenient to keep as well.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
