### ISSUE TITLE
Unexpected polling state code_expired

### ISSUE THREAD

**Issue by badarosama** [Azure/azure-cli#6547]
I installed azure-cli 2.0.34 because I can't find 2.04 on the install website (https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest#install-or-update). I am using windows 10 machine and chrome and edge browsers to test. I tried az login and it throws the above mentioned error.

It shows me the site and code and then when i enter the code on the link posted, it throws the error above. i have tried chrome. IE and edge browsers multiple times and im logging in with my@microsoft account that i use for my kubernetes account.

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by tjprescott** [comment]
I don't know where you saw a reference to "2.04" but there is no such version. @yugangw-msft

**Comment by yugangw-msft** [comment]
Please opt-out the insider ring using the instructions below. (In near future,  I will rework `az login`'s authentication flow to no longer use device flow if you are on a desktop with window manager, this way you don't need to opt-out of the insider ring.)

```bash
1.	Navigate to https://login.microsoftonline.com/common/insider/optout?upn=YOURALIAS@microsoft.com (replacing YOURALIAS with your alias).
2.	Clear your browser cookies in any browser you will use to sign in to AAD that you don’t want to redirect to the insider ring. 

Once you complete step 2, you should no longer be redirected to the insider ring. If you want to return to the insider ring, you can navigate to https://login.microsoftonline.com/common/insider/clear, which will remove your optout.
```

**Comment by yugangw-msft** [comment]
please reactivate if the workaround does not work or contact me at yugangw at microsoft dot com
