### ISSUE TITLE
Update table output for `nsg show`

### ISSUE THREAD

**Issue by dougthomas71** [Azure/azure-cli#6551]
To provide a middle ground of information between the json and table outputs.
Often times the json output is too much detail and the table output is not enough.
### Example
`az network nsg show -n {NSG_NAME} -g {RESOURCE_GROUP} -o table`
Gives an output with 5 pieces of information of which you supplied 2 pieces of the information and you probably already saw the rest of the info from a `az network nsg list` command.
In the above example selecting either the json or jsonc arguments provides a very detailed list of the rules thats hard to use in a summary of the information.

**Comment by tjprescott** [comment]
You can filter the data shown using `--query`.  This can be used to limit the returned info using JSON format or to specify which info you want to display using table format.

Since you cite `nsg show` in your example, what would you consider the ideal amount of information to display?  The default table formats (using `-o table` without `--query`) for each command can be updated in code.

**Comment by dougthomas71** [comment]
Thanks for responding @tjprescott 
For the task specific task I was working on was on some nsg 😁 
For that specific command I'd say the same fields that are in the portal would be enough.
i.e.
Priority, Name, Port(s), Protocol, Source, Destination and Action

**Comment by tjprescott** [comment]
I believe the command you are looking for then is `az nsg rule list … -o table` which already has a custom table format. We wouldn't show the rules in the `nsg show` table because we don't have the capability to display tables within tables, which this would require.

**Comment by dougthomas71** [comment]
@tjprescott Uhhhh no.
`az nsg rule list … -o table` is not what I'm looking for at all.
I don't need to see a list of nsg's I need to see a summary of the rules of a specific nsg. There's no nested tables. Just a single simple table with a summary of the rules that are in a nsg.

**Comment by tjprescott** [comment]
That's what `az nsg rule list` does...

**Comment by dougthomas71** [comment]
Sorry - I just re-read your message (need more coffee I guess)
Yes `az network nsg rule list -g {ResourceGroup} --nsg-name {NsgName} -o table` works! Thanks for pointing me in that direction.
However ^^^^ this is rather convoluted and not obvious esp when `az network nsg show -g {ResourceGroup} -n {NsgName} -o json` provides you with the list of rules in json format. It would be more obvious that switching the output to a table would provide the list of rules instead of having to use a different command path && (slightly) different arguments (--nsg-name instead of -n).
