### ISSUE TITLE
Help: describe the [id, name, rg] clearly

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#656]
It is a known issue general to all commands.  The help text shows no fields are mandatory, but in fact, people should supply either "resource group"+"name", or "resource id"
Though a little odd, but `(--resource-group --name | --ids)` communicate better.
```
Command
    az vm show

Arguments
    --api-version      : Client Api Version.  Default: 2016-03-30.
    --expand           : The expand expression to apply on the operation.
    --ids              : ID of resource.
    --name -n          : The name of the virtual machine.
    --resource-group -g: Name of resource group.

(env) D:\sdk\azure-cli>az vm show
usage: az vm show [-h] [--output {json,tsv,list,table}] [--verbose] [--debug]
                  [--query JMESPATH] [--expand EXPAND]
                  [--api-version API_VERSION]
                  [--ids RESOURCE_ID [RESOURCE_ID ...]]
                  [--resource-group RESOURCE_GROUP_NAME] [--name NAME]
az vm show: error: (--resource-group --name | --ids) are required
```

**Comment by BurtBiel** [comment]
We have issue https://github.com/Azure/azure-cli/issues/677 to track this

**Comment by tjprescott** [comment]
@yugangw-msft what's the current delta on this? We do output the usage string. Is there anything more you suggest we do?

**Comment by BurtBiel** [comment]
I think the middle ground we reached is to have the ID arguments in their own argument group.  It should be clear which ones are required after the first error message and the group will signify this consistently across commands.
