### ISSUE TITLE
az acr create: Specifying the wrong case for --sku gives a confusing error message

### ISSUE THREAD

**Issue by johanste** [Azure/azure-cli#6562]
**Describe the bug**
$> az acr create -g connectorregistry -n xxsamplejohanstexx --sku basic
az acr create: 'basic' is not an az acr create command. See 'az acr create --help'.

The most similar command to 'basic' is:
        Basic

**To Reproduce**
See description

**Expected behavior**
An error message telling me the set of valid values for the --sku parameter. Additionally, the --sku parameter should be case insensitive, and thus the command should actually have succeeded

**Environment summary**
2.0.32, ran in cmd.exe

**Additional context**

**Comment by djyou** [comment]
This appears to be a general issue in the CLI that enum params are not showing the proper error message.
