### ISSUE TITLE
[Interactive] Parameter descriptions don't appear

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#6570]
**Describe the bug**
When I type a command, the command description appears but the parameter descriptions do not appear in the adjacent panel, even when turned on.

**To Reproduce**
type `group create` and witness how nothing shows up in the parameter pane.

**Expected behavior**
Parameter descriptions appear.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

install via dev_setup.py

```
azure-cli (2.0.38)
interactive (0.3.23)
```

**Comment by williexu** [comment]
I see the following:
![image](https://user-images.githubusercontent.com/8580552/41322945-878fac60-6e60-11e8-8efd-a9747f075f54.png)
![image](https://user-images.githubusercontent.com/8580552/41322969-9b114bcc-6e60-11e8-9437-5bbeaffdb0e4.png)

Do you see/expect something different?

**Comment by tjprescott** [comment]
Yeah, I expected something different. I didn't realize you had to actually specify a parameter to see something. Makes sense though.
