### ISSUE TITLE
az keyvault download returns incorrect exit code if not logged in

### ISSUE THREAD

**Issue by jakepearson** [Azure/azure-cli#6580]
**Describe the bug**
If I try to download a secret from the azure keyvault, but I am not logged in. The process returns with no error message and a exit code of `0`.

**To Reproduce**
1. Delete (or move) your `.azure` credentials folder
2. Run `az keyvault secret download --vault-name <your-vault-name> -n <secret-name> -e base64 -f <filename>

**Expected behavior**
After running the above command without any azure credentials, the command should return with a non-zero exit code. Ideally, it would also print to `stdout` suggesting I should execute `az login`.

**Environment summary**
Running on `OSX 10.13.5` with `az 2.0.35`

**Comment by freeone3000** [comment]
I'm also getting a 0 exit code for a similar issue, running on Alpine Linux with az 2.0.49.
