### ISSUE TITLE
Add slot support for all az functionapp commands

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-cli#6581]
Add slot support for all az functionapp commands

**Comment by ph0rman** [comment]
I hit the same problem.  We zip deploy all our webapps using using the slot flag, but when I went to deploy our functionapps, that flag wasn't available (az functionapp deployment source config-zip -s SLOTNAME ...)
This is preventing us from using function app slots until support is added!

**Comment by ph0rman** [comment]
I've had confirmation from Microsoft that slot support is GA for function apps.  
If the CLI won't add support, what is the alternative? ditch az functionapp and just use az webapp?

**Comment by ahmedelnably** [comment]
@ph0rman unfortunately until we get the support for slots, az webapp is the only way.
We will be working on increasing the support in az functionapp in CY19, stay posted

**Comment by ahmedelnably** [comment]
cc: @dariagrigoriu 

This should involve adding --slot flag to all commands, in addition we should allow the creation of a slot
New commands: az functionapp deployment slot (create/delete/list/swap)

**Comment by ankitkumarr** [comment]
@ahmedelnably, please add Sprint 63 milestone to this, I do not have the right permissions.
