### ISSUE TITLE
"ipConfigurations" return null

### ISSUE THREAD

**Issue by rallyspeed** [Azure/azure-cli#6587]
**Describe the bug**
ipConfiguration is returning null even if interface exist and public and private IP are set

**To Reproduce**
az network nsg list --query [*].[networkInterfaces]

**Expected behavior**
Would except to return the name, type ,private and public ip for each interfaces

**Environment summary**
azure-cli version (2.0.32)

**Additional context**

**Comment by tjprescott** [comment]
Does this information show if you run the command without `--query`? If so then it means your query string is incorrect.

**Comment by rallyspeed** [comment]
No, it always return null.

 "networkInterfaces": [
      {
        "additionalProperties": {},
        "dnsSettings": null,
        "enableAcceleratedNetworking": null,
        "enableIpForwarding": null,
        "etag": null,
        "id": "xxx",
        "ipConfigurations": null,

**Comment by tjprescott** [comment]
What happens when you run `az network nic ip-config list` for the NIC in question?

**Comment by rallyspeed** [comment]
Got the info i was looking for with this command. Thanks.

**Comment by tjprescott** [comment]
Glad to hear it worked for you.
