### ISSUE TITLE
"Please re-register for this provider...", show me the command

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#6595]
When receiving a message like this:

```
The subscription is not registered for the resource type 'managedClusters' in the location 'westus'. Please re-register for this provider in order to have access to this location.
```

Rather than telling me I need to re-register, suggest the command to run to resolve the situation. In my case, this was: `az provider register --namespace Microsoft.ContainerService`

**Comment by tjprescott** [comment]
What command did you run that gave you this error?  msrest or msrestazure should handle the automatic registration of such providers for you. This has been the case for a while now. cc/ @lmazuel

**Comment by colemickens** [comment]
I actually got that with AKS when doing a simple `az aks create`.

I had definitely registered previously though. Not sure if it was something to do with leaving preview? Either way, it didn't happen automatically.

I don't recall, but I don't think I retried the command, I think I immediately just re-registered.

**Comment by lmazuel** [comment]
@mboersma I never seen this message, is this something specific to AKS that will not be detected by my auto-registration code?
To trigger the auto-registration, answer must be 409 with a code "MissingSubscriptionRegistration". Is this answer different?

**Comment by colemickens** [comment]
@mboersma That sounds possible, but I had thought AKS was in `westus` since the initial preview days. If not, and registrations are region-specific, this would likely be the cause.

(Note, the error message above was taken verbatim from my terminal on the date that I filed the issue.)

**Comment by mboersma** [comment]
AKS was initially in `westus2` but was decommissioned after public preview began last year. `westus` is a new region for AKS only recently. I don't know for sure if the registrations are region-specific actually (although that might explain this behavior). Let me get some more info and see if I can reproduce this as well.

**Comment by mboersma** [comment]
I am able to reproduce this, and it is returning a 409, so it seems that the CLI should have auto-registered, but the code is `MIssingRegistrationForLocation`, not `MissingSubscriptionRegistration`. Should the CLI be catching that as well, or should the RP change its error code?

```json
{
   "error": {
      "code": "MissingRegistrationForLocation",
      "message": "The subscription is not registered for the resource type 'managedClusters' in the location 'westus'. Please re-register for this provider in order to have access to this location."
   }
}
```

**Comment by lmazuel** [comment]
@mboersma I'm only looking for MissingSubscriptionRegistration right now, so I don't know if I'm missing a valid return code from ARM, or if the code is incorrect.
@ravbhatnagar thoughts?

**Comment by mboersma** [comment]
This is a routine problem for RPs--when a new region is brought online, a provider needs to be re-registered to be able to access that region. We started running a batch script yesterday to update all existing AKS customer registrations, and we should finish updating them all today, which will fix this problem for now.

If the CLI did handle this error code by re-registering, it appears that would also work around this for the customer.

**Comment by yugangw-msft** [comment]
> The subscription is not registered for the resource type 'managedClusters' in the location 'westus'. Please re-register for this provider in order to have access to this location.

The code of doing auto-registering has  been moved to  msrestazure. Even we can update the run time, the error is  still not enough for the auto-reg to work for 2 reasons:
 1. The provider name  of "managedClusters"  is not complete, rather it should be `Microsoft.managedClusters`
 2. The provider name should be in a specific detail error field like ARM did, and this would avoid client end regex matching, which has always been hacky.

So mark it as service attention, as this is not actionable from CLI

**Comment by yugangw-msft** [comment]
to cross check the `az aks`

**Comment by jluk** [comment]
i believe this should no longer be an issue for az aks creates, so closing as we did some work to improve RP registrations. if this is still occurring though please do re-open or comment for me to revisit.
