### ISSUE TITLE
Az monitor diagnostic setting EventHub - Cannot deserialize as [LogSettings]

### ISSUE THREAD

**Issue by Ycallaer** [Azure/azure-cli#6599]
**Describe the bug**
I am trying to enable diagnostic settings for eventhub through the azure CLI.
I have seen that the JSON format was recently changed, but even after changing the JSON format I am unable to deploy successfully. I am currently running into the following issue:

```
msrest.exceptions.SerializationError: Unable to build a model: Cannot deserialize as [LogSettings] an object of type <class 'dict'>, DeserializationError: Cannot deserialize as [LogSettings] an object of type <class 'dict'>
```

**To Reproduce**
After spinning up an eventhub instance I use the following command to try to enable the diagnostic mode:
`
az monitor diagnostic-settings create --name EventHubDiagnostics --workspace EventHubTest --resource /subscriptions/<subscription>/resourceGroups/<rg>/providers/Microsoft.EventHub/namespaces/<eh> --resource-group <rg> --logs @/Users/x/Downloads/json_cli.json
`

The content of the json looks as follows:
```
 {
 	"category": "ArchiveLogs",
 	"enabled": true,
 	"retentionPolicy": {
"days": 0,
"enabled": false
}
 }
```

**Expected behavior**
I would have expected to be able to create a valid diagnostic setting using the above stmt

**Environment summary**
Az running on mac install through homebrew.
Version:
 az --version ->
```

azure-cli (2.0.37)

acr (2.0.26)
acs (2.1.0)
advisor (0.5.1)
ams (0.1.1)
appservice (0.1.34)
backup (1.1.1)
batch (3.2.3)
batchai (0.2.3)
billing (0.1.8)
cdn (0.0.14)
cloud (2.0.13)
cognitiveservices (0.1.13)
command-modules-nspkg (2.0.1)
configure (2.0.15)
consumption (0.3.1)
container (0.1.24)
core (2.0.37)
cosmosdb (0.1.21)
dla (0.1.0)
dls (0.0.21)
dms (0.0.1)
eventgrid (0.1.12)
eventhubs (0.1.3)
extension (0.0.14)
feedback (2.1.1)
find (0.2.9)
interactive (0.3.22)
iot (0.1.21)
keyvault (2.0.22)
lab (0.0.22)
maps (0.1.0)
monitor (0.1.7)
network (2.1.3)
nspkg (3.0.2)
policyinsights (0.1.0)
profile (2.0.25)
rdbms (0.2.3)
redis (0.2.13)
reservations (0.1.2)
resource (2.0.30)
role (2.0.24)
servicebus (0.1.2)
servicefabric (0.0.12)
sql (2.0.27)
storage (2.0.34)
vm (2.0.33)

Python location '/xx/python3.6'
```

**Comment by tjprescott** [comment]
Your JSON format is wrong.  It should be a list not a dictionary.  I've verified that this works:
```
[
  {
     "category": "ArchiveLogs",
     "enabled": true,
     "retentionPolicy": {
      "days": 0,
      "enabled": false
    }
  }
]
```
