### ISSUE TITLE
az storage blob generate-sas bug 403 error

### ISSUE THREAD

**Issue by nicolaibaralmueller** [Azure/azure-cli#6601]
Azure cli command generates bad sas taken:

`az storage blob generate-sas --account-name $name--account-key $key --container-name $container --name $filename --permissions r --start $($today)T$($now)Z --expiry $($today)T$($later)Z --https-only`

This code has worked for months. I have only updated azure cli, not my azure content or code.

When trying to download with url the following error shows:

`Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.`

`Signature did not match.`

Script runs on Ubuntu 16.04 latest. SAS token url has been testet on linux and windows. Same error.

Manually creating a sas token url in the azure portal works fine.

**Comment by williexu** [comment]
@nicolaibaralmueller this scenario seems to work for me. I used my sas token to do a download after.

Can you make sure that the account key you use to generate your sas is still valid? If it isn't a token will still be generated, but will not be valid. Also make sure you have the proper start and expiration constraints.

**Comment by nicolaibaralmueller** [comment]
Thanks for the answer @williexu 
This has been resolved however.
