### ISSUE TITLE
How to properly escape a : (colon) when setting a tag?

### ISSUE THREAD

**Issue by olivelawn** [Azure/azure-cli#6605]
**Describe the bug**
I cannot wrap my head around how to tag resource groups when there are special characters involved. I'm not sure this is a bug, but this does seem very odd. I am trying to put some name/value pairs, separated by a colon inside a tag.

**To Reproduce**
This almost does what I want:

<pre>
$ az group update -n testing --set tags.sampletag={\"Name\"=\"Value\"}
(output omitted)
    "sampletag": "{\"Name\"=\"Value\"}"
</pre>

Now instead of an equals (=) sign, I want a colon: (:).  This is where things get weird:

<pre>
$ az group update -n testing --set tags.sampletag={\"Name\":\"Value1\"}
(output omitted)
    "sampletag": "{'Name': 'Value1'}".  <-- notice my double-quotes are gone
</pre>

What I want is:
   <pre> "sampletag": "{\"Name\":\"Value\"}"</pre>

I have tried escaping the : with backslashes, tried putting literals all over the place.  I'm stumped.  Anyone understand this one?

**Environment summary**
brew install on macOS.

**Comment by tjprescott** [comment]
The generic set operation has to work with JSON objects, strings, etc. It recognizes `{\"Name\":\"Value1\"}` as valid JSON and thus converts it to a JSON object rather than treating it as a string. Is the behavior just odd or is it blocking your scenario?

**Comment by olivelawn** [comment]
@tjprescott The behavior is blocking a scenario. Is there a way to force it to be interpreted as a string and not JSON?

**Comment by tjprescott** [comment]
There isn't. What is the scenario that is blocked?

**Comment by olivelawn** [comment]
@tjprescott I've been in the thick of a retagging effort (we use tags to determine how to charge $ back individual projects). The syntax of our existing tags looks like this.  The existing values (somehow) get into the tags using a runbook/powershell, but I'm a doofus when it comes to powershell.

We so happen to have 3 name/value pairs, but the same issue would exist even if we just had 1.

<pre>
$ az group show -g sample-rg
{
(output omitted)
  {
 "tags": {
    "sampletag": "{\"Name1\":\"Value1\",\"Name2\":\"Value2\",\"Name3\":\"Value3\"}"
  }
}
</pre>

So our finance department is expecting the above to a "T" and have rules to parse the string exactly as is. If I could change the delimiters I would.

I'm trying to change a few of the values programmatically across hundreds of RG's.

Any other ideas minus going the powershell route?

**Comment by tjprescott** [comment]
We can expose the `--tags` convenience argument, which would not have this issue. But it would have the issue that it would replace the entire tags collection, so you wouldn't just be able to set one tag.  Have you tried the using the `az tag` command?

**Comment by olivelawn** [comment]
@tjprescott the fix you're describing would mean we would need to know every tag at at the same right?  Anotherwords, if we had the situation below, we would need to know the name/value pairs for sampletag1, sampletag2, sampletag3, right?

<pre>
$ az group show -g sample-rg
{
(output omitted)
  {
 "tags": {
    "sampletag1": "{\"Name1\":\"Value1\",\"Name2\":\"Value2\",\"Name3\":\"Value3\"}"
    "sampletag2": "{\"Name1\":\"Value1\",\"Name2\":\"Value2\",\"Name3\":\"Value3\"}"
    "sampletag"3: "{\"Name1\":\"Value1\",\"Name2\":\"Value2\",\"Name3\":\"Value3\"}"
  }
}
</pre>

**Comment by tjprescott** [comment]
@olivelawn yes, that is correct. When you use `--tags` in other update commands it does a replacement. Only the generic update lets you mutate things with finer granularity. I will investigate some options in our next sprint.

**Comment by olivelawn** [comment]
@tjprescott Thanks for making this happen. I'll be on the lookout for the --force-string flag. Much appreciated.

**Comment by tjprescott** [comment]
No problem @olivelawn it should be released July 17th.
