### ISSUE TITLE
Unable to send filers larger than 195G and/or change MAX_BLOCK_SIZE to 100M...

### ISSUE THREAD

**Issue by josrom** [Azure/azure-cli#6606]
Hej same issue here uploading:
2018-06-18T08:50:20.189470061Z azure.common.AzureHttpError: The block list may not contain more than 50,000 blocks.ErrorCode: BlockListTooLong
2018-06-18T08:50:20.189475561Z BlockListTooLongThe block list may not contain more than 50,000 blocks.
2018-06-18T08:50:20.189481861Z RequestId:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2018-06-18T08:50:20.189486961Z Time:2018-06-18T08:50:20.1754772Z

I tried we a new file with the old file... I cannot upload and seems to be size related since the file uploading is a backup tar.gz that has been growin until reach 200GB.... so the breaking point seems to be there.... im using the newest CLI container so all comes preinstalled and nice...

bash-4.3# az --version
azure-cli (2.0.29)

acr (2.0.22)
acs (2.0.28)
advisor (0.5.0)
appservice (0.1.29)
backup (1.0.7)
batch (3.1.11)
batchai (0.1.6)
billing (0.1.7)
cdn (0.0.13)
cloud (2.0.12)
cognitiveservices (0.1.11)
command-modules-nspkg (2.0.1)
configure (2.0.14)
consumption (0.2.2)
container (0.1.19)
core (2.0.29)
cosmosdb (0.1.19)
dla (0.0.18)
dls (0.0.19)
eventgrid (0.1.11)
eventhubs (0.1.0)
extension (0.0.10)
feedback (2.1.0)
find (0.2.8)
interactive (0.3.17)
iot (0.1.18)
keyvault (2.0.20)
lab (0.0.17)
monitor (0.1.3)
network (2.0.25)
nspkg (3.0.2)
profile (2.0.20)
rdbms (0.1.0)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.25)
role (2.0.20)
servicebus (0.1.0)
servicefabric (0.0.11)
sql (2.0.23)
storage (2.0.27)
vm (2.0.28)

Tried to setup MAX_BLOCK_SIZE=100M as variable but not working....
env MAX_BLOCK_SIZE=100M az storage blob upload.....

**Comment by williexu** [comment]
@josrom can you update to a newer container?
I believe you are hitting this issue: https://github.com/Azure/azure-cli/pull/5881
The fix should be in versions v2.0.30 and later

**Comment by williexu** [comment]
Closing this, please comment if you still see problems with the latest version.
