### ISSUE TITLE
vm list-skus: improve it with more filter support for common user scenarios

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#6609]
This command is getting more important because `az vm list-sizes` doesn't return accurate information, as some sizes are not actually available because of subscription level of restrictions.
For context, this API returns ~3MB payload with everything, and becomes an increasing challenge for users to extract out relevant data. Propose here to expose a few filters for common scenarios so to give users more relevant data, e.g.
    `--vm-sizes`:  this should return available sizes after consider restriction from CAS
    `--zonal-vm-sizes`: this should list available sizes you can use to create either `zonal vm` or `x-zone vmss`
   `--fault-domain-count`: this should return fault-domain count for managed AV-set

(Ideally, the service API should return better structured data instead of a huge json blob, but if that can't be done, then CLI needs to follow up)

**Comment by kskvarci** [comment]
To put it very simply, this command needs to be capable of returning a human readable list of VM sizes that are available in a given subscription and region. It should be able to effectively mirror what is returned in the size picker in the portal.

output from az vm list-sizes is easy to parse, it doesn't however pay any attention to the restrictions that are in play w/ in the selected subscription and region. E.G. you'll get a list back that contains a number of sizes that cannot be deployed.

I like Yugangs idea of --vm-sizes and --zonal-vm-sizes parameters. The output should contain all values contained w/ in the capabilities array but unavailable VMs should be filtered out of the output.

**Comment by yugangw-msft** [comment]
In my PR, I made a bit tweak.
```bash
1. `--resource-type`: filter by resource type say: disks, availabilitySets, etc  
2. `--size`:  filter by vm size
3. `--zone`: filter by vm size with zone support
4. `--all`: show disabled/prohibited skus. Should be rarely used.
```
For you case, the command would looks like `az vm list-skus --zone -l eastus2`
