### ISSUE TITLE
Give Examples delete-batch

### ISSUE THREAD

**Issue by rogerywoo** [Azure/azure-cli#6615]
It would help if actual examples were provided.  For source should you include https.  Should it be:
az storage file &lt;command&gt; -- source https://&lt;your_account_name1&gt;.blob.core.windows.net/&lt;your_container_name1&gt;/&lt;your_sub_directory_at_blob1&gt; or something else?

I have tried various commands to delete a number of files without success.  Here are some examples I tried:

az storage file delete-batch --source https://<storage account>.blob.core.windows.net/<storage container> --account-key <my account key>  --pattern xxx_2015 --dryrun

az storage file delete-batch --source <storage account>.blob.core.windows.net/<storage container> --account-key <my account key>  --pattern xxx_2015 --dryrun

az storage file delete-batch --source <storage account>blob.core.windows.net/<storage container> --account-name <storage account>--account-key <my account key>  --pattern xxx_2015 --dryrun

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c633bcb6-d7c0-8bfe-76b6-c69fed9eaf90
* Version Independent ID: 6b2e9a7e-c75f-0b48-0794-acd0ba474eba
* Content: [az storage file](https://docs.microsoft.com/en-us/cli/azure/storage/file?view=azure-cli-latest#az-storage-file-delete-batch)
* Content Source: [src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by rogerywoo** [comment]
Never mind.  I figured it out.  I should have used az storage **blog** delete-batch.   Also, for the pattern it should have been xxx*_2015.  You need an asterisk.

**Comment by divgo** [comment]
This command worked for me,

```az storage file delete-batch --account-name [StorageAccountName] --source [ShareName] --pattern [FilePattern]```

In my case, the pattern I passed was "app-2019*". I had a huge collection of log file output from Spark that I wanted to purge from Azure Files. 

what was weird was that this command deleted all the FILES in the folders, but did not delete the folders themselves. Still trying to figure out how to delete the actual folders.
