### ISSUE TITLE
Does SAS connection to a Azure emulator work?

### ISSUE THREAD

**Issue by yxiang92128** [Azure/azure-cli#6621]
**Describe the bug**
I am trying to use "az" to connect to an Azure emulator instance but it failed to parse and reported a malformed connection string.

**To Reproduce**
Steps to reproduce the behavior.
root@sdl23981:~# az storage blob list --container-name lotsofobjects --connection-string "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;SharedAccessSignature=?sv=2017-07-29&sr=c&sig=4whSHUPmTjVH6EVgqm2laN5vNDJ%2BHi6J9CNHejuGhWo%3D&se=2018-06-30T22%3A17%3A19Z&sp=rwdl;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;"
Connection-string: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;SharedAccessSignature=?sv=2017-07-29&sr=c&sig=4whSHUPmTjVH6EVgqm2laN5vNDJ%2BHi6J9CNHejuGhWo%3D&se=2018-06-30T22%3A17%3A19Z&sp=rwdl;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;, is malformed. Some shell environments require the connection string to be surrounded by quotes.

**Expected behavior**
How do I work around it so it will connect.
**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by williexu** [comment]
@yxiang92128  Your connection string does not look like a connection string. Where did you get yours?

**Comment by williexu** [comment]
@yxiang92128 please use `az storage account show-connection-string` to create a connection string and try that.
I will close this, but feel free to comment if you still have problems.
