### ISSUE TITLE
Publisher: KasperskyLab.SecurityAgent was not found, when list images by offer

### ISSUE THREAD

**Issue by suntong** [Azure/azure-cli#6622]
**Describe the bug**
when listing images by `--offer`, az now returns `Publisher: KasperskyLab.SecurityAgent was not found` error. It was OK just about a week ago.

**To Reproduce**

```
$ az vm image list --all --offer Debian
Publisher: KasperskyLab.SecurityAgent was not found.
```

**Expected behavior**
a list of images returned. 

**Environment summary**
CLI version (`az --version`) / OS version / Shell Type: bash

running in https://shell.azure.com/ using bash:

```
$ az --version
azure-cli (2.0.38)

acr (2.0.27)
acs (2.1.1)
advisor (0.5.1)
ams (0.1.1)
appservice (0.1.35)
...
```

**Additional context**

listing images by publisher still ok. E.g., 

`az vm image list --all --publisher=credativ`

**Comment by yugangw-msft** [comment]
@suntong, sorry for the delay. If you can still repro, can you share the trace using `--debug`? I want to see which region you are in. CLI can be modified to capture those exceptions and continue, but i like to see a repro first.

**Comment by suntong** [comment]
OK. I'll find sometime this weekend to try again...

**Comment by yugangw-msft** [comment]
Please reactivate when you have a repro
