### ISSUE TITLE
--encrypt-format-all UUID issue when run for DATA disks only

### ISSUE THREAD

**Issue by marinnedea** [Azure/azure-cli#6626]
The --encrypt-format-all parameter will also cause the UUIDs to be changed post encryption, therefore adding the disks into the /etc/fstab with UUIDs before encryption will most likely result in a "no boot" situation for that VM due to wrong UUID. Removing that parameter allows the system keeping the same UUIDs. Please have this tested on your own end. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4762f857-8a1e-f1bb-7843-3d8fefe28f8e
* Version Independent ID: 91ce956c-c915-5053-56b0-a489fb2f7b00
* Content: [az vm encryption](https://docs.microsoft.com/en-us/cli/azure/vm/encryption?view=azure-cli-latest#az-vm-encryption-enable)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by marinnedea** [comment]
Before partitioning:

/dev/sda2: UUID="3c11fba3-32c7-4d0c-b614-aad5630504eb" TYPE="xfs"
/dev/sda1: UUID="ca02dd2d-a91b-4fb1-b24b-0fb19c18b89d" TYPE="xfs"
/dev/sdb1: UUID="d4de616e-7a99-4904-9a4d-9cae793e2f9f" TYPE="ext4"
/dev/sdc1: UUID="62afbe50-54dc-4d73-a46b-36ab52c5017d" TYPE="ext4"
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
fd0      2:0    1    4K  0 disk
sda      8:0    0   32G  0 disk
├─sda1   8:1    0  500M  0 part /boot
└─sda2   8:2    0 31.5G  0 part /
sdb      8:16   0    7G  0 disk
└─sdb1   8:17   0    7G  0 part /mnt/resource
sdc      8:32   0   10G  0 disk
└─sdc1   8:33   0   10G  0 part
sr0     11:0    1  628K  0 rom

**Comment by yugangw-msft** [comment]
//cc: @vermashi 
@marinnedea, if I get it right, the flag of `--encrypt-format-all` is pretty much useless for linux due to the severe consequence of no-boot?

**Comment by vermashi** [comment]
The flag '--encrypt-format-all' only changes the UUIDs of data partitions, not the OS or Boot partitions.
Additionally, encrypted data partitions are mounted by the extension, not the fstab.
We have tested this option a lot and it does not cause a no-boot scenario.

**Comment by marinnedea** [comment]
I can confirm the problem is currently no longer manifesting and the extensions, with the --EncryptFormatAll option works as intended. No idea if you guys fixed it or something..but looks good :) .Thank you!
