### ISSUE TITLE
az aks use-dev-spaces

### ISSUE THREAD

**Issue by Treemendus** [Azure/azure-cli#6627]
I am trying to setup an environment to debug a remote kubernetes pod.

![image](https://user-images.githubusercontent.com/16299007/41726385-034e20d0-7540-11e8-90d3-aceb4452b37b.png)

I have followed the example in this article https://docs.microsoft.com/en-gb/azure/dev-spaces/quickstart-netcore I am getting the above error message and not sure how to proceed. 

When the Cluster was originally created there was not an option to Enable HTTP Application Routing.

**Comment by saurabsa** [comment]
We are about to release our latest Azure Dev Spaces cli today. That should fix the issue. Meanwhile, please try to run these commands to use a dev space controller:
`azds controller create`
`azds space select`

**Comment by Treemendus** [comment]
Thank you for the quick update
