### ISSUE TITLE
az vmss rolling-upgrade

### ISSUE THREAD

**Issue by nicolaibaralmueller** [Azure/azure-cli#6640]
Hi,

_az vmss rolling-upgrade -start --name $vmssName --resource-group $resourceGroup_ always fails with the following error:

`The OS Rolling Upgrade API cannot be used on a VM Scale Set unless the VM Scale Set is using a Platform Image select the OS by setting imageReference.`

This does not make sense to me as the image reference is set in azure:

![image](https://user-images.githubusercontent.com/33453919/41776799-65245024-7629-11e8-9b1c-671e083d0765.png)

**Comment by yugangw-msft** [comment]
you can check out [the document](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-automatic-upgrade#supported-os-images). I don't think you can use your own customer images.
