### ISSUE TITLE
filter-sql-expression quotes

### ISSUE THREAD

**Issue by BrandynThornton** [Azure/azure-cli#6641]
Create/Update a rule using Powershell and the Azure CLI you may need to wrap the rule in double quotes as an example:
az servicebus topic subscription rule create --resource-group myresourcegroup --namespace-name mynamespace --topic-name mytopic --subscription-name mysubscription --name myrule --filter-sql-expression "myproperty='myvalue'"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fd5960a-ea47-7542-6837-3e4e49e95d0a
* Version Independent ID: c8a9f5b6-2a2f-4820-3be4-c87e3896a6b7
* Content: [az servicebus topic subscription rule](https://docs.microsoft.com/en-us/cli/azure/servicebus/topic/subscription/rule?view=azure-cli-latest#az-servicebus-topic-subscription-rule-update)
* Content Source: [src/command_modules/azure-cli-servicebus/azure/cli/command_modules/servicebus/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-servicebus/azure/cli/command_modules/servicebus/_help.py)
* Service: **service-bus**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Quoting behavior is shell-dependent and we do not generally attempt to alter it in the CLI. I read this as a general comment or observation vice a specific ask, so I will close this GitHub issue. If there is an ask, we can reopen it.
