### ISSUE TITLE
Add default values

### ISSUE THREAD

**Issue by ccanuel** [Azure/azure-cli#6645]
would be great to know the default values to all the parameters
eg:
[--default-action {Allow, Deny}]
[--https-only {false, true}]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92115d19-d7a0-93a8-bf2b-5126d1cddcd0
* Version Independent ID: a657f09b-e1ac-12a2-4b9c-7aaa1f0e3f5c
* Content: [az storage account](https://docs.microsoft.com/en-us/cli/azure/storage/account?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
For flags (--https-only), the default is always false (flag not specified). For some parameters, like `--default-action` the default from the CLI to specify nothing and allow the server to enforce the default.  However, that default should be expressed via the rest API specs, in which it would bubble up to the CLI. cc/ @johanste

**Comment by yonzhan** [comment]
add to S165.

**Comment by jiasli** [comment]
The help message for `--https-only` has been refined in https://github.com/Azure/azure-cli/pull/10824. cc @Juliehzl 

As for `--default-action`, it is an `Enum`, so there is no default value for it and a specific value is mandatory: 

https://github.com/Azure/azure-cli/blob/5edbd822ee860d7ba5d5182811b68233e0846ba8/src/azure-cli/azure/cli/command_modules/storage/_params.py#L230-L231

As @tjprescott suggested, if the value is not specified, Azure CLI will omit that field in the REST request. Then that depends on the Resource Provider's behavior to decide the default value as defined in the REST spec:

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/storage/resource-manager/Microsoft.Storage/stable/2019-06-01/storage.json#L1851-L1855

```jsonc
        "supportsHttpsTrafficOnly": {
          "type": "boolean",
          "x-ms-client-name": "EnableHttpsTrafficOnly",
          "description": "Allows https traffic only to storage service if sets to true. The default value is true since API version 2019-04-01."
        },
```
