### ISSUE TITLE
az monitor diagnostic-settings create cmdlet help 

### ISSUE THREAD

**Issue by MGoedtel** [Azure/azure-cli#6647]
**Describe the bug**
When using the 1.	–workspace  to create a new Log Analytics workspace, it is not clear that the -workspace parameter requires the full resource object ID "path" and not just the name of the workspace.  The reference documentation and any other related documentation for performing this in CLI does not clearly specify the value required.  

**To Reproduce**
If following the documentation, I would enter the following:  

az monitor diagnostic-settings create --name NSGDiagnostics \
    --resource /subscriptions/<subscriptionID>/resourceGroups/Space1999/providers/Microsoft.Network/networkSecurityGroups/ADDS-NSG \
    --workspace DefaultWorkspaceSpace1999 \
    --resource-group Space1999 \

It returns the following error:  Operation failed [Code: “resourcenotfound”].  It isn't clear what the exact issue is when the error is returned, which is another frustrating by-byproduct of the issue.  

**Expected behavior**
A clear and concise description of the value required/expected and it would be beneficial to include a working example that can be followed by the reader for -workspace and -resource arguments.   

**Environment summary**
Install Method CLI version 2.0

**Additional context**

**Comment by tjprescott** [comment]
The help documentation states:
```
--workspace          : Name or ID of the Log Analytics workspace to send diagnostic logs to.
--resource-group -g  : Name of the resource group for the Log Analytics and Storage Account when
                           the name of the service instead of a full resource ID is given.
```

If you supply the name, you must also supply resource group. If you don't you get the following error message:
```
--resource-group is required when name is provided for storage account or workspace or service bus namespace and rule.
```

For the error you are seeing, it looks like you are supplying something that just doesn't exist.

**Comment by MGoedtel** [comment]
@tjprescott - I understand and my point was that the reference documentation isn't clear on how you should pass the value for --workspace, which my example above is showing the incorrect way I originally followed based on interpretation of the documentation.  However, I learned that it should be including the fully qualified "path" (i.e. resource object id) of the workspace: --workspace /subscriptions/<subscriptionId>/resourceGroups/<resourcegroupName>/providers/Microsoft.OperationalInsights/workspaces/<workspaceName> \ in order for it to work correctly.  If you use the example I originally shared, it doesn't return the error you indicated it should return.

**Comment by tjprescott** [comment]
When I paste the example you gave, I get the following:
```
The subscription 'resourceGroups' could not be found.. [Code: "SubscriptionNotFound"]
```

The value you provided for `--resource` was missing the subscription. The documentation is correct--you do not have to specify the workspace by fully-qualified ID.  You can provide the name, which will use the values of `--resource-group/-g` and/or `--subscription` to assemble the ID.
