### ISSUE TITLE
[Create Commands] Create commands should all fail if the resource already exists

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#665]
VM and VMSS do this today, the rest should also.

**Comment by tjprescott** [comment]
There are commands within storage where you have to specify `--fail-if-exist` to get this behavior (and `--fail-not-exist` to trigger opposite behavior for deletes). In storage, the standard seems to be to overwrite things which already exist. Although I suppose those are data and not technically resources.

**Comment by BurtBiel** [comment]
Perhaps we should use fail-if-exists, although users could check for existence first using the show commands if we left the create commands as they are today.  We have to fail on exists for VM Create because of the randomly generated OS Disk name, but the others don't strictly require it.  We should discuss if we should stick with the original decision to fail on exists by default.

**Comment by tjprescott** [comment]
Since create commands should be idempotent, which should definitely not fail when a resource already exists.  Arguably, we could issue a warning as described in #3593.  Closing this issue.
