### ISSUE TITLE
az network vnet check-ip-address - error in doc

### ISSUE THREAD

**Issue by Makovec** [Azure/azure-cli#6654]
Hi,
--ip-address is also mandatory. If not specified, returned error is: Private IP address is null or empty in the CheckIpAddressAvailability call. Specify IpAddress=$(ipaddress) as a query parameter in the request URI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc99d572-abdb-ab6b-7a9a-c6951a1c1466
* Version Independent ID: 0a50e966-cbc8-8960-c01f-e117cac842d4
* Content: [az network vnet](https://docs.microsoft.com/en-us/cli/azure/network/vnet?view=azure-cli-latest#az-network-vnet-check-ip-address)
* Content Source: [src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Thanks for the report @Makovec!
