### ISSUE TITLE
az vm list-sizes should allow filtering by HDD / SDD

### ISSUE THREAD

**Issue by alexvicegrab** [Azure/azure-cli#6655]
**Describe the bug**

I can filter on the Azure Portal based on SSD, but this is impossible to natively do on the command line.

**To Reproduce**

```
az vm list-sizes
```

See that there is no property relating to SSD/HDD status, so can't filter with JMESPath

**Expected behavior**

I'd expect to be able to filter the machines based on SSD/HDD status.

**Environment summary**

Installed with Homebrew:

Az version:
```
vm (2.0.20)
```

**Additional context**

N/A

**Comment by yugangw-msft** [comment]
Please always use `az vm list-skus` for the most accurate output, which takes into the consideration of  subscription level of restrictions. The command has a capacity filed called `PremiumIO` which would let you know HDD or SSD status.
```bash
(env) D:\sdk\azure-cli>az vm list-skus -l westus --size Standard_DS1_v2 -otable
ResourceType     Locations    Name             Zones    Capabilities                                                                                                                                       Restrictions
---------------  -----------  ---------------  -------  -------------------------------------------------------------------------------------------------------------------------------------------------  --------------
virtualMachines  westus       Standard_DS1_v2           ['MaxResourceVolumeMB=7168', 'OSVhdSizeMB=1047552', 'vCPUs=1', 'MemoryGB=3.5', 'MaxDataDiskCount=4', 'LowPriorityCapable=True', 'PremiumIO=True']  None
```
