### ISSUE TITLE
Missing default values

### ISSUE THREAD

**Issue by yevster** [Azure/azure-cli#6667]
There are no default values provided for the optional parameters for `az postgres server create`. For instance, is ssl enforcement enabled by default if it is omitted? What is the storage size if none is provided? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d11bd3f4-efbf-691d-76a4-293ab97ad845
* Version Independent ID: a553d088-d838-f90f-d601-12fa312fe0cf
* Content: [az postgres server](https://docs.microsoft.com/en-us/cli/azure/postgres/server?view=azure-cli-latest#az-postgres-server-create)
* Content Source: [latest/docs-ref-autogen/postgres/server.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/postgres/server.yml)
* Service: **postgres**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by rachel-msft** [comment]
Thank you for reporting this issue. The defaults were updated: https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/postgres/server.yml 

#please-close
