### ISSUE TITLE
network-rule command not working

### ISSUE THREAD

**Issue by rameshjanjyam** [Azure/azure-cli#6668]
here is the error I am seeing - az keyvault: 'network-rule' is not an az keyvault command. See 'az keyvault --help'

az --version is "azure-cli (2.0.38)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caa4484b-7b01-45d5-4d5c-61f274395eac
* Version Independent ID: de5c4486-080b-6406-5dcb-febd66a5a626
* Content: [az keyvault network-rule](https://docs.microsoft.com/en-us/cli/azure/ext/keyvault-preview/keyvault/network-rule?view=azure-cli-latest#ext-keyvault-preview-az-keyvault-network-rule-add)
* Content Source: [latest/docs-ref-autogen/ext/keyvault-preview/keyvault/network-rule.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/ext/keyvault-preview/keyvault/network-rule.yml)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
This might be a feature in the KeyVault extension. @schaabs can you verify?

**Comment by schaabs** [comment]
@rameshjanjyam This feature is currently only supported in the keyvault-preview extension. To install the extension run the command

    az extension add -n keyvault-preview

You can get more info on the extension, as well as file any issues [here](https://github.com/azure/azure-keyvault-cli-extension/).  We are currently in the process of releasing the features in the preview extension, so they should be available in a standard install of the CLI in July.

**Comment by rameshjanjyam** [comment]
awesome. it worked. Thank you very much @schaabs and @tjprescott
