### ISSUE TITLE
az group deployment create failes because of Circular dependency detected

### ISSUE THREAD

**Issue by dtissen** [Azure/azure-cli#6677]
**Describe the bug**
Deployment template validation failed: 'Circular dependency detected on resource: '/subscriptions/96df8737-1173-496d-abee-c828eee4d264/resourceGroups/demo/providers/Microsoft.Compute/virtualMachines/demo-apl01'. Please see https://aka.ms/arm-template/#resources for usage details.'.

The issue is, that the az group export function exports a json configuration of the ressourcegroup. The Circular Dependency is the VirtualMachine / NetworkInterface Resources which refer to each other.

Since i had an old export (which was ok!) i checked the difference:
In the new export the NetworkInterface refer to the virtualMachine. This is new and causes this issue. Deleting this line solved my problem.

I know this is a server Bug, but i cannot find the corresponding Project to report the bug there.

**To Reproduce**
1. Export an resource group configuration
2. try to deploy the configuration.

**Expected behavior**
1. Export should be validated for circular dependencies
2. Exception should be more detailed. Investigating the configuration took me a while!

**Environment summary**

Ubuntu
azure-cli (2.0.38)

acr (2.0.27)
acs (2.1.1)
advisor (0.5.1)
ams (0.1.1)
appservice (0.1.35)
backup (1.1.1)
batch (3.2.4)
batchai (0.3.0)
billing (0.1.8)
cdn (0.0.14)
cloud (2.0.14)
cognitiveservices (0.1.13)
command-modules-nspkg (2.0.1)
configure (2.0.16)
consumption (0.3.1)
container (0.1.24)
core (2.0.38)
cosmosdb (0.1.21)
dla (0.1.0)
dls (0.0.22)
dms (0.0.1)
eventgrid (0.1.12)
eventhubs (0.1.3)
extension (0.0.15)
feedback (2.1.2)
find (0.2.10)
interactive (0.3.23)
iot (0.1.21)
keyvault (2.0.22)
lab (0.0.22)
maps (0.2.0)
monitor (0.1.7)
network (2.1.4)
nspkg (3.0.2)
policyinsights (0.1.0)
profile (2.0.26)
rdbms (0.2.4)
redis (0.2.13)
reservations (0.2.0)
resource (2.0.31)
role (2.0.26)
servicebus (0.1.2)
servicefabric (0.0.12)
sql (2.0.27)
storage (2.0.35)
vm (2.0.34)

Python location '/opt/az/bin/python3'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Jun 14 2018, 21:24:04)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal

**Additional context**

**Comment by glaisne** [comment]
Additional information, For me, the issue was in an availability set. I removed the availability set's dependency on the VM and I passed the test-azurermresourcegroupdeployment

**Comment by brendandburns** [comment]
There was an error in the network schema fixed here:

https://github.com/Azure/azure-resource-manager-schemas/pull/534

Once that merges, this can be closed.
