### ISSUE TITLE
Table Storage Policy List Doesn't return an array

### ISSUE THREAD

**Issue by ninijay** [Azure/azure-cli#6687]
**Describe the bug**
When listing all the policies for a given table storage, the az tool returns an object with sub- objects rather than an array of objects

**To Reproduce**
1. Create Table Storage
2. Add 2 or more Access Policies
![image](https://user-images.githubusercontent.com/6756364/42080272-63a38dce-7b82-11e8-9c7d-d64cd56e7f23.png)
3. Query for a list of policies for that table:
```bash
az storage table policy list --table-name <tablename> --account-name <storagename>
```
4. Get the "malformed" result:
```
{
  "policy1": {
    "expiry": null,
    "permission": "rau",
    "start": null
  },
  "policy2": {
    "expiry": null,
    "permission": "d",
    "start": null
  }
}
```

**Expected behavior**
Since it is a list, the result should be returned as an array/list and should look like this:
```
[
  "policy1": {
    "expiry": null,
    "permission": "rau",
    "start": null
  },
  "policy2": {
    "expiry": null,
    "permission": "d",
    "start": null
  }
]
```

**Environment summary**
I'm working in the cloud bash shell

**Additional context**
none

**Comment by ninijay** [comment]
Same in other storage types like queues and shares

**Comment by tjprescott** [comment]
@williexu, since we are using the list verb, we should consider using a transform to force the returned object to be a list. We would also need to move the policy name into the dictionary or wrap each policy in a dictionary.

**Comment by limingu** [comment]
@ninijay, we can change the the result as a list. It will be like this:
[
  {
    "policy1": {
      "expiry": null,
      "permission": "rau",
      "start": null
    },
  },
  {
    "policy2": {
      "expiry": null,
      "permission": "d",
      "start": null
    }
  }
]

That actually makes it hard to find a policy name. As a list, you may have to go through the whole list to find the policy. The result as a dictionary seems make more sense here.

**Comment by tjprescott** [comment]
@limingu the issue is that the command is called a list command does not return a list. We can force it to a more normal format like:

```
[
  {
      "name": "policy1",
      "expiry": null,
      "permission": "rau",
      "start": null
  }
]
```

This would be consistent with the rest of Azure and thus the user could employ the same patterns for searching for the desired object.

**Comment by zhoxing-ms** [comment]
@ninijay Hi, after discussions with our PM, we think this will trigger a breaking change, and we are cautious about it. 
This issue is temporarily holding on now. If the impact of this issue becomes larger or more people feedback in the future, we will reopen it, thank you.
