### ISSUE TITLE
Can't enable accelerated networking for a VM

### ISSUE THREAD

**Issue by chubin** [Azure/azure-cli#6688]
When I am trying to enable accelerated networking for a VM, nothing happens:
```
$ az network nic update --name MyLinuxVM-3 -n MyLinuxVM-3VMNic --resource-group ic-exasol-001 --accelerated-networking true                                                                                                                                                                   
{
  "dnsSettings": {
    "appliedDnsServers": [],
    "dnsServers": [],
    "internalDnsNameLabel": null,
    "internalDomainNameSuffix": "a1gteu2qlm3uvda5qury3tvdxc.ax.internal.cloudapp.net",
    "internalFqdn": null
  },
  "enableAcceleratedNetworking": true,
  "enableIpForwarding": false,
  "etag": "W/\"ada75778-f4a2-49f4-b853-c2d0cd29a812\"",
  "id": "/subscriptions/fd6696e3-8f52-4410-a769-230c3727693e/resourceGroups/ic-exasol-001/providers/Microsoft.Network/networkInterfaces/MyLinuxVM-3VMNic",
  "ipConfigurations": [
```

Inside the VM after that I see the same devices as before, no Mellanox:

```
# lspci
00:00.0 Host bridge: Intel Corporation 440BX/ZX/DX - 82443BX/ZX/DX Host bridge (AGP disabled) (rev 03)
00:07.0 ISA bridge: Intel Corporation 82371AB/EB/MB PIIX4 ISA (rev 01)
00:07.1 IDE interface: Intel Corporation 82371AB/EB/MB PIIX4 IDE (rev 01)
00:07.3 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 02)
00:08.0 VGA compatible controller: Microsoft Corporation Hyper-V virtual VGA
```

**Comment by yugangw-msft** [comment]
It would be worthwhile to cross check whether the size of the VM is qualified for this. Not a great source, but there is a [raw list here](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py#L569-L595). Hope this helps.

**Comment by yugangw-msft** [comment]
Can you do a "az vm show" and cross check the os image you are using? Not all OS images support accel-net.
Here is the [raw list](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py#L620-L623)

**Comment by chubin** [comment]
@yugangw-msft That is my *own image*, but it has all needed drivers inside

**Comment by yugangw-msft** [comment]
@gsilva5, is there a way to diagnose why the accelnet is not picked up? like boot diagnostics?
@chubin, I can only suggest you create a new vm  with "--accelerated-networking ", and to cross check whether you can get it with the same size and same image.

**Comment by MyronFanQiu** [comment]
@avijitgupta Hello. Any update about this issue?

**Comment by KarenHammons** [comment]
@gsilva5 can you please review this?
