### ISSUE TITLE
container create --secrets to set environment variables does not work

### ISSUE THREAD

**Issue by t-muko** [Azure/azure-cli#6696]
**Describe the bug**
When trying to set a secret environment variable for a container instance by using az cli switch "--secret mysecret=verysecret", an error message appears:
"Please specify --secrets --secrets-mount-path to enable secrets volume mount."

Secret environment variable does not have anything to do with a secret mount. 
If a mount name is specified the command runs, but no environment variable is set

**To Reproduce**
Try to set a secret environment variable:
`az container create --secret mysecret=verysecret ...`  (plus other required parameters...)

**Expected behavior**
A container being create with a secret variable. 

Environment showing the variable when checked:

> az container show --resource-group myRG --name securetest --query 'containers[].environmentVariables`

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

Python 3.6.1
pip install

az --version
azure-cli (2.0.38)

acr (2.0.27)
acs (2.1.1)
advisor (0.5.1)
ams (0.1.1)
appservice (0.1.35)
backup (1.1.1)
batch (3.2.4)
batchai (0.3.0)
billing (0.1.8)
cdn (0.0.14)
cloud (2.0.14)
cognitiveservices (0.1.13)
command-modules-nspkg (2.0.1)
configure (2.0.16)
consumption (0.3.1)
container (0.1.24)
core (2.0.38)
cosmosdb (0.1.21)
dla (0.1.0)
dls (0.0.22)
dms (0.0.1)
eventgrid (0.1.12)
eventhubs (0.1.3)
extension (0.0.15)
feedback (2.1.2)
find (0.2.10)
interactive (0.3.23)
iot (0.1.21)
keyvault (2.0.22)
lab (0.0.22)
maps (0.2.0)
monitor (0.1.7)
network (2.1.4)
nspkg (3.0.2)
policyinsights (0.1.0)
profile (2.0.26)
rdbms (0.2.4)
redis (0.2.13)
reservations (0.2.0)
resource (2.0.31)
role (2.0.26)
servicebus (0.1.2)
servicefabric (0.0.12)
sql (2.0.27)
storage (2.0.35)
vm (2.0.34)

**Additional context**

**Comment by CurtisLusmore** [comment]
@samkreter Which release will this be part of? Could you please link to the Issue that implements this feature so that I can follow it?
