### ISSUE TITLE
Azure Functions CLI Tools 2.2.2 - Unable to Debug Azure Functions from VS2017

### ISSUE THREAD

**Issue by prawin2k** [Azure/azure-cli#6697]
**Describe the bug**
We are unable to debug the Azure Functions (we tried Timer, HTTP & Cosmos DB) locally in VS 2017 after the 2.2.2 CLI Tools got downloaded . Everything was working perfect before that.

![2 2 2-downloading](https://user-images.githubusercontent.com/10738750/42175712-edc2cd7c-7e15-11e8-8d41-cebc1706a2e4.png)

Below is the screen capture of the releases.
![versionfolder](https://user-images.githubusercontent.com/10738750/42175924-b27b30be-7e16-11e8-98ed-d90b7d6b4b36.png)

**Environment summary**
VS 2017
CLI Tools 2.2.2
Azure Functions Runtime 2.0
Target Framework: .NET Standard 2.0

**Comment by tjprescott** [comment]
This is not the correct repo for this issue.  It belongs here:
https://github.com/Azure/azure-functions-core-tools
