### ISSUE TITLE
Unable to login with the new experience

### ISSUE THREAD

**Issue by maximbaz** [Azure/azure-cli#6698]
**Describe the bug**

I updated from `2.0.35` to `2.0.40` and now the `az login` behaves differently and is unable to sign me in.

I run `az login`, the browser is being opened, I select my account and see the success message:

```
You have logged into Microsoft Azure!
You can close this window, or we will redirect you to the Azure CLI documents in 10 seconds.
```

However in the terminal I see an error:

```
❯ az login                  
Note, we have launched a browser for you to login. For old experience with device code, use "az login --use-device-code"
[3186:3186:0702/202752.046404:ERROR:sandbox_linux.cc(378)] InitializeSandbox() called with multiple threads in process gpu-process.
Created new window in existing browser session.
Get Token request returned http error: 401 and server response: {"error":"invalid_client","error_description":"AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided.\r\nTrace ID: c0834499-922a-445c-87f8-f88d70282700\r\nCorrelation ID: b3e6c2b1-c381-4f1f-aa84-f794c2894056\r\nTimestamp: 2018-07-02 18:27:56Z","error_codes":[70002,50012],"timestamp":"2018-07-02 18:27:56Z","trace_id":"c0834499-922a-445c-87f8-f88d70282700","correlation_id":"b3e6c2b1-c381-4f1f-aa84-f794c2894056"}
```

What kind of client secret is it talking about?

Luckily the old experience is still present, and when I use `az login --use-device-code`, I am able to successfully log in.

**Environment summary**

OS: Latest Arch Linux
Shell: zsh
Install method: [AUR/python-azure-cli](https://aur.archlinux.org/packages/python-azure-cli/) with [AUR/python-azure-git](https://aur.archlinux.org/packages/python-azure-git)

<details>
<summary>The output of <code>az --version</code></summary>

```
❯ az --version
azure-cli (2.0.40)

acr (2.0.28)
acs (2.1.2)
advisor (0.5.1)
ams (0.1.1)
appservice (0.1.36)
backup (1.1.2)
batch (3.2.4)
batchai (0.3.1)
billing (0.1.8)
cdn (0.0.14)
cloud (2.0.15)
cognitiveservices (0.1.13)
command-modules-nspkg (2.0.1)
configure (2.0.17)
consumption (0.3.1)
container (0.2.0)
core (2.0.40)
cosmosdb (0.1.21)
dla (0.1.0)
dls (0.0.22)
dms (0.0.1)
eventgrid (0.1.12)
eventhubs (0.1.3)
extension (0.1.0)
feedback (2.1.3)
find (0.2.11)
interactive (0.3.24)
iot (0.1.21)
keyvault (2.0.23)
lab (0.0.22)
maps (0.2.0)
monitor (0.1.8)
network (2.1.5)
nspkg (3.0.2)
policyinsights (0.1.0)
profile (2.0.27)
rdbms (0.2.5)
redis (0.2.14)
reservations (0.2.1)
resource (2.0.32)
role (2.0.26)
servicebus (0.1.2)
servicefabric (0.0.12)
sql (2.0.27)
storage (2.0.35)
vm (2.0.35)

Python location '/usr/bin/python'
Extensions directory '/home/maximbaz/.azure/cliextensions'

Python (Linux) 3.6.5 (default, May 11 2018, 04:00:52) 
[GCC 8.1.0]

Legal docs and information: aka.ms/AzureCliLegal
```
</details>

**Comment by yugangw-msft** [comment]
CLI doesn't really support `Arch Linux`(at least we never maintained and tested it).
This error means the `adal` is too old that it still puts `none` secret in the token request payload instead of omitting it for public clients. Please let the `Arch Linux` maintainer update the "python-azure-cli" to use newer [version](https://github.com/AzureAD/azure-activedirectory-library-for-python/releases/tag/1.0.2).
At the same time, there are nothing we can do, so I am closing this.
//CC: @troydai

**Comment by maximbaz** [comment]
Thank you! 

The biggest challenge with maintaining Arch Linux package for `azure-cli` is the amount of dependencies to keep track of (they all should be published as separate packages, e.g. now I marked [python-adal](https://aur.archlinux.org/packages/python-adal/) as outdated), and at the same time there are no packages yet for modules within [azure-sdk](https://github.com/Azure/azure-sdk-for-python) (currently only [python-azure-git](https://aur.archlinux.org/packages/python-azure-git) exists, which is a hack, it clones the entire repo and installs everything from master branch.

Currently the Arch Linux packages are all being maintained by @optlink ([their account](https://aur.archlinux.org/account/optlink) contains email address for communication). If you are considering to provide official support, I've seen other companies just adopting the existing AUR packages for their products (basically getting write permissions), and I recommend doing the same — I'm sure @optlink will be happy to assist. That way, you are only left with just bumping the versions in time (package + dependencies), which would be a great help to the community (and for bonus points, if you split `python-azure-git` into multiple packages that also follow official releases instead of `master` branch, that would be even more awesome).

I can also help if you need anything.
