### ISSUE TITLE
Option to disable automatic saving of authentication token

### ISSUE THREAD

**Issue by theheatDK** [Azure/azure-cli#6700]
**Is your feature request related to a problem? Please describe.**
When you use az login an authentication token is saved that is available for 14 days. So you only need to log in every 14 days. So if your laptop is compromised they will have access to your Azure account. If the last log in you did was with a user that for example has owner rights, things could get nasty.

**Describe the solution you'd like**
As far as I can tell there is not way to disable this. For Azure Powershell there is Disable-AzureRmContextAutosave. I would be very nice to have such an option for the Azure CLI.

**Describe alternatives you've considered**
The best solution would be that you always had to use az login, and there was an option to enable the token to live for 14 days.

**Comment by tjprescott** [comment]
cc/ @yugangw-msft @johanste

**Comment by yugangw-msft** [comment]
Each CLI's command execution involves a new process, so disabling the token persistence means each command will require the user to punch in passwords to get the token which itself is more like a security concern on top of the usability problem.
Azure PowerShell's process is per window, so as long as you keep the shell window open, it is able to persist tokens in the memory and get other cmdlets running. But once you laptop is compromised, if the window is still open, then same damages can occur.
The best option is you let your tenant admin shorten the refresh token's live span from 14 days to maybe 1 day.
I am closing this as I don't think there are much CLI can do on this.
