### ISSUE TITLE
KeyVault and MSI is broken in recent CLI releases

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-cli#6706]
More precisely, since IMDS was introduced in msrestazure (March 28, 0.4.25)

This is because `resource` was moved to `_ImdsTokenProvider` internally, and then the `resource` at the credentials level was not used anymore. But KeyVault is using it to change the resource on the fly. This makes all KV call from MSI `Unauthorized` from a VM using IMDS.

Fixed in msrestazure 0.4.35 (unreleased yet).
https://github.com/Azure/msrestazure-for-python/issues/109

Created for tracking, in case someone has the issue and google it here.

This does not require any CLI changes.

FYI @yugangw-msft @williexu @troydai

**Comment by lmazuel** [comment]
Being that KV is doing a lot of black magic in Authentication, that's complicated to test as mock. Best would be to record some tests in MSI env, which I'm not sure we are doing right now.

**Comment by tjprescott** [comment]
Is the issue the KeyVault SDK or CLI?

**Comment by lmazuel** [comment]
msrestazure, but since it impacts CLI, I thought it deserves an issue for tracking.

**Comment by yugangw-msft** [comment]
msrestazure has been released for a while
