### ISSUE TITLE
Is it possible to attach "az aks browse" to a specific interface?

### ISSUE THREAD

**Issue by Gusymochis** [Azure/azure-cli#6718]
Running this command in a container always attaches to the "127.0.0.1" interface but to be able to expose this port it has to be attached to the "0.0.0.0" interface. Are there any plans to support this? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-browse)
* Content Source: [latest/docs-ref-autogen/aks.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/aks.yml)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by troydai** [comment]
@mboersma

**Comment by jnoller** [comment]
az aks browse --name
              --resource-group
              [--disable-browser]
              [--listen-address]
              [--listen-port]
              [--subscription]

Listen address and Port are supported, we do not have additional plans for customization for the browse command at this time.
