### ISSUE TITLE
az deployment --help fail for 2017-03-09-profile

### ISSUE THREAD

**Issue by daxianji007** [Azure/azure-cli#6720]
**Describe the bug**
Run `az deployment --help` fail with message:
```
The operation 'azure.mgmt.resource.resources.v2016_02_01.operations.deployments_operations#DeploymentsOperations.get_at_subscription_scope' is invalid.
Traceback (most recent call last):
  File "E:\CurrentWorks\AzureCLI\TestCmd\venv\lib\site-packages\azure\cli\core\__init__.py", line 471, in get_op_handler
    op = getattr(op, part)
AttributeError: type object 'DeploymentsOperations' has no attribute 'get_at_subscription_scope'
```

**To Reproduce**
```
pip install azure-cli
az cloud update --profile 2017-03-09-profile
az deployment --help
```

**Expected behavior**
show the help message for `az deployment`

**Environment summary**
Python (3.6.5)  
pip (10.0.1)  
azure-cli (2.0.41)  

**Additional context**
Could be related to this [commit](https://github.com/Azure/azure-cli/commit/6a923cbc417209481c08aebfc3ff17f6acdf664f#diff-9ea07fda6d56572359db4aa2be53a348)  
This issue is blocking the [reference document](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest) generation CI. New changes in azure-cli would not be updated to the page before this issue is fixed.  
Please take this as high priority.

**Comment by tjprescott** [comment]
Thank you for the report. The `az deployment` commands should not appear on that profile as they are new.  You might be looking for the `az group deployment` commands. We'll issue a fix in an upcoming release.
