### ISSUE TITLE
the doc is outdated, script is wrong

### ISSUE THREAD

**Issue by eosfor** [Azure/azure-cli#6729]
```bash
storage_sastoken=$(az storage account generate-sas \
                            --account-name $my_diagnostic_storage_account --expiry 9999-12-31T23:59Z \
                            --permissions wlacu --resource-types co --services bt -o tsv)
```

this piece is wrong. it is not aligned with https://github.com/MicrosoftDocs/azure-docs/issues/8212

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a9ab822-6524-9dd7-3bf4-1889e10d1266
* Version Independent ID: ec780873-d291-dda8-6b1d-c410e2d87b98
* Content: [az vm diagnostics](https://docs.microsoft.com/en-us/cli/azure/vm/diagnostics?view=azure-cli-latest#az-vm-diagnostics-get-default-config)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by troydai** [comment]
@yugangw-msft @williexu
