### ISSUE TITLE
"az vm diagnostics set" does not seem to be working

### ISSUE THREAD

**Issue by eosfor** [Azure/azure-cli#6730]
i'm running az vm diagnostics set. it runs well with no issues or failures. however, 

- no new tables under Storage Account given are created
- "Basic" checkbox under diagnostics on the portal is not set.

this is the piece of code

```bash
for (( i=0; i<${masterNodeCount}; ++i )) ; do
#some stuff skipped
vm_resource_id=$(az vm show -g ${resourceGroupName} -n "${projectName}-master-${i}" --query "id" -o tsv)

default_config=$(az vm diagnostics get-default-config \
| sed "s#__DIAGNOSTIC_STORAGE_ACCOUNT__#${diagnosticsStorageAcctName}#g" \
| sed "s#__VM_OR_VMSS_RESOURCE_ID__#${vm_resource_id}#g") > /dev/null

echo $default_config > monitoring-config.json

storage_sastoken=$(az storage account generate-sas \
--account-name ${diagnosticsStorageAcctName} --expiry 2037-12-31T23:59Z \
--permissions wlacu --resource-types co --services bt -o tsv) > /dev/null

set -x
protected_settings="{\"storageAccountName\": \"${diagnosticsStorageAcctName}\", \"storageAccountSasToken\": \"${storage_sastoken}\"}"

az vm diagnostics set --settings "${default_config}" \
 --protected-settings "${protected_settings}" \
 --resource-group $resourceGroupName --vm-name "${projectName}-master-${i}" > /dev/null
done
```

**Version**
azure-cli (2.0.38)

acr (2.0.27)
acs (2.1.1)
advisor (0.5.1)
ams (0.1.1)
appservice (0.1.35)
backup (1.1.1)
batch (3.2.4)
batchai (0.3.0)
billing (0.1.8)
cdn (0.0.14)
cloud (2.0.14)
cognitiveservices (0.1.13)
command-modules-nspkg (2.0.1)
configure (2.0.16)
consumption (0.3.1)
container (0.1.24)
core (2.0.38)
cosmosdb (0.1.21)
dla (0.1.0)
dls (0.0.22)
dms (0.0.1)
eventgrid (0.1.12)
eventhubs (0.1.3)
extension (0.0.15)
feedback (2.1.2)
find (0.2.10)
interactive (0.3.23)
iot (0.1.21)
keyvault (2.0.22)
lab (0.0.22)
maps (0.2.0)
monitor (0.1.7)
network (2.1.4)
nspkg (3.0.2)
policyinsights (0.1.0)
profile (2.0.26)
rdbms (0.2.4)
redis (0.2.13)
reservations (0.2.0)
resource (2.0.31)
role (2.0.26)
servicebus (0.1.2)
servicefabric (0.0.12)
sql (2.0.27)
storage (2.0.35)
vm (2.0.34)

Python location '/opt/az/bin/python3'
Extensions directory '/home/andrei/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Jun 14 2018, 21:24:04)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal

**Some additional context**
~$ uname -a
Linux <some name> 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

Basically it runs in WSL

**Comment by eosfor** [comment]
Seems like an issue with the ```--expiry 2037-12-31T23:59Z``` of a SAS token. What is the maximum possible value for it?

**Comment by yugangw-msft** [comment]
Please use a right format e.g. `2037-12-31T23:59:00Z.` like commented in a [related issue](https://github.com/MicrosoftDocs/azure-docs/issues/8212#issue-321030028)
I will fix the example at the same time

**Comment by yugangw-msft** [comment]
fixed
