### ISSUE TITLE
Invalid orchestrator type for `az acs create` with DockerCE

### ISSUE THREAD

**Issue by iainfoulds** [Azure/azure-cli#6733]
**Describe the bug**
The `az acs create` command indicates `--orchestrator-type dockerce` as a valid value, but the following error is encountered:

```
Deployment failed. Correlation ID: d56164e3-30dd-40ef-9022-4991c37d74b1. {
"error": {
"code": "BadRequest",
"target": "containerService.properties.orchestratorProfile.orchestratorType",
"message": "Error converting value "DockerCE" to type 'System.Nullable1[Microsoft.WindowsAzure.ContainerService.API.OrchestratorType]'. Path 'properties.orchestratorProfile.orchestratorType', line 1, position 87."
```

If you use `--orchestrator type swarm`, the cluster is correctly created.

**To Reproduce**
Try to create a cluster as follows:

```
az acs create --name mySwarmCluster --orchestrator-type dockerce --resource-group myResourceGroup --generate-ssh-keys
```

**Expected behavior**
A cluster is created that uses Docker CE. I suspect it's just a mismatch in the help text. Will also update doc at https://docs.microsoft.com/en-gb/azure/container-service/dcos-swarm/container-service-swarm-mode-walkthrough

**Environment summary**
Azure CLI 2.0.41 (Cloud Shell and Docker image experience same behavior)

**Additional context**
FYI @dazinator and @MicahMcKittrick-MSFT

**Comment by yugangw-msft** [comment]
closing as `az acs` is deprecating
