### ISSUE TITLE
Python 3.7 compatibility assurance

### ISSUE THREAD

**Issue by smereczynski** [Azure/azure-cli#6745]
On Mac (using homebrew) azure-cli is installed with Python 3.7 (as for 08.07.2018). It worls but there is no clear information in repo and documentation about compatibility with 3.7.

**Comment by smereczynski** [comment]
I don't think it's packaging issue in fact. In homebrew "python" dependency is pointing to latest stable, so 3.7. And I don't think there is an option to get 3.6. So there should be a compatibility check with 3.7.

**Comment by marstr** [comment]
Seems like this is a documentation issue, more than a product issue. I'll transfer the issue for you now.

**Comment by marstr** [comment]
Following up here, it took a while but we did finally add explicit declaration of support here in #9685
