### ISSUE TITLE
Blob awareness of VM

### ISSUE THREAD

**Issue by dtissen** [Azure/azure-cli#6746]
**Is your feature request related to a problem? Please describe.**
My initial Problem is to restore a blob snapshot for a blob hosted on premium storage. In that case a break lease is not allowed from serverside - remember blob on standard storage --> you are allowed to break lease.

In my case i have a vm with blobs on standard and premium. In case of standard Storage i just break lease. in case of premium storage i want to detach the blob from the VM, restore the snapshot and attach it again. My script iterate throug all blobs on a storage, select some code specified blobs and restores them. 

That does not work easily for blobs on premium storage. I cannot get the VMName of the blob. In other words: i need to switch the process to get the VM Settings with its blobs and iterate on that list of blobs. That would be a workaround for my problem.

Despite this, i think a blob allready knows if it has a lease and therefor should also know the "lease owner" which is the VM.

**Describe the solution you'd like**
blob metadata also provide the VM Name for a blob.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by williexu** [comment]
Currently the lease owner is not included in the lease information. Including this information would require a service change and is not something that can be done from the CLI side. 
@seguler to comment on this issue.

**Comment by amishra-dev** [comment]
Our current service design does not support identifying which VM has the lease. we expect the client getting the lease to track it. However we have put this in our service feature backlog and will prioritize it accordingly.
