### ISSUE TITLE
Stuck deployment validation: urllib3.connectionpool : Starting new HTTPS connection (1): management.microsoftazure.de

### ISSUE THREAD

**Issue by the1bit** [Azure/azure-cli#6748]
**Describe the bug**
I use my deployment validation command with my ARM template for 1.5 years without any issue in **MCD**. 
About 2 weeks ago this command does not work due to a strange issue. 

``` bash
urllib3.connectionpool : Starting new HTTPS connection (1): management.microsoftazure.de
urllib3.connectionpool : https://management.microsoftazure.de:443 "POST /subscriptions/*********/resourcegroups/rg-custom/providers/Microsoft.Resources/deployments/deployment_dry_run/validate?api-version=2017-05-10 HTTP/1.1" 503 294
```

**To Reproduce**
I am logged in to my Azure subscription in Azure MCD then I execute the following validation:
``` bash
az group deployment validate --resource-group 'rg-custom' --template-file deployment/batch.json --parameters @./temp/params.json --debug
```

**Expected behavior**
Azure validates the template with the parameters and gives back "Succeeded"/"Valid template" result

**Environment summary**

- azure-cli (2.0.37) - I have tested multiple version of Azure-Cli. None of them work.
- Python (Linux) 2.7.5
- [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
- RHEL redhat-release-server-7.4-18.el7.x86_64

**Additional context**

- I have tested multiple version of Azure-Cli. None of them work.
- I have tested many API-Version as well. None of them work.

**Comment by the1bit** [comment]
Please ignore it.

**Comment by sveilleux1** [comment]
May you tell me what was the problem please? I'm experiencing something similar but trying to create an hdinsight cluster. Thanks.

**Comment by the1bit** [comment]
> May you tell me what was the problem please? I'm experiencing something similar but trying to create an hdinsight cluster. Thanks.

Hi,

The issue was here a simple user fault. ;-) I mean the template file was not there the path I provided in command.
Wrong git pull caused the issue. 

Nevertheless if the request limit is reached on subscription you are facing total same error message. 

Sorry, I can't provide you good news and/or exact solution for that.

Have a nice day.

Best Regards,
Tibor
