### ISSUE TITLE
Document --json-file format

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-cli#6751]
There are no details on the format of the JSON file supported via the `--json-file` parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 065a1d73-5ead-81c2-8b7b-5405c2a112b1
* Version Independent ID: fbae9a55-b731-ed86-ff6a-22c1a97d4e53
* Content: [az batch pool](https://docs.microsoft.com/en-us/cli/azure/batch/pool?view=azure-cli-latest#az-batch-pool-create)
* Content Source: [src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_help.py)
* Service: **batch**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by letmaik** [comment]
https://docs.microsoft.com/en-us/azure/batch/batch-cli-get-started#json-files-for-resource-creation

**Comment by bgklein** [comment]
JSON File Syntax can be found in the REST API documentation for the associated call. We can look into adjusting the help text of the CLI to better reflect this.

**Comment by letmaik** [comment]
Yes please :)

**Comment by bgklein** [comment]
Sorry for the delay but I'll add this to the action items for Monday. Don't know what release it will be included in but seems like a nice quick documentation fix.
