### ISSUE TITLE
Why is --account-name required if --account-endpoint is given?

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-cli#6752]
`az batch pool create --account-endpoint https://myaccount.northeurope.batch.azure.com ...`
Here `myaccount` is the account name, so why do I have to provide this as a separate argument in `--account-name`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 065a1d73-5ead-81c2-8b7b-5405c2a112b1
* Version Independent ID: fbae9a55-b731-ed86-ff6a-22c1a97d4e53
* Content: [az batch pool](https://docs.microsoft.com/en-us/cli/azure/batch/pool?view=azure-cli-latest#az-batch-pool-create)
* Content Source: [src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-batch/azure/cli/command_modules/batch/_help.py)
* Service: **batch**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by xingwu1** [comment]
@letmaik the endpoint is very useful. The account name may duplicated in the multiple region. So endpoint not only have account name, but also region name, and cloud type (national cloud vs public cloud). So we can't use account name to replace endpoint.

**Comment by tjprescott** [comment]
If the endpoint contains the name, he's asking why you have to specify name again through `--account-name`.  You could simply extract it from the endpoint.

**Comment by xingwu1** [comment]
Yes. We may not need it in most case. 

However, we don't want to parse an arbitrary URL is main reason, other reasons:
1. We possible change endpoint format (we did once before, we are not grantee in future)
2. Be consistent with other SDKs, etc.
3. User normally uses 'az batch account login' to cache the account information, and they don't provide it at every batch commands.

**Comment by tjprescott** [comment]
Thanks for the response @xingwu1. I'll close this since the question is answered.
