### ISSUE TITLE
webapp:Misspelling

### ISSUE THREAD

**Issue by grayjeremy** [Azure/azure-cli#6760]
Under the --name parameter, I think this should read "Name of the webpp" as opposed to "Name of the web"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2bf26b4-3d91-ec60-c64d-8f910a4f0f00
* Version Independent ID: 33547311-9105-6e41-e477-3681d2a87087
* Content: [az webapp identity](https://docs.microsoft.com/en-us/cli/azure/webapp/identity?view=azure-cli-latest#az-webapp-identity-show)
* Content Source: [latest/docs-ref-autogen/webapp/identity.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/webapp/identity.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
@panchagnula , i will take this one unless you are interested
