### ISSUE TITLE
sample for more than one key/value in --secrets needed

### ISSUE THREAD

**Issue by fabsenet** [Azure/azure-cli#6761]
I tried several types of providing more than one secret at a time but it always either fails to create the container at all or the first key has the everything else as the value.
I tried

```powershell
az container create ... --secrets '"sshuser=xyz" "sshpass=abcdefg"' --secrets -mount-path "/secrets"
az container create ... --secrets "'sshuser=xyz' 'sshpass=abcdefg'" --secrets -mount-path "/secrets"
az container create ... --secrets "sshuser=xyz sshpass=abcdefg" --secrets -mount-path "/secrets"
az container create ... --secrets "sshuser=xyz;sshpass=abcdefg" --secrets -mount-path "/secrets"
```

please provide a sample!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e5d1da7-7c4f-c9e6-e4b9-a30407675acf
* Version Independent ID: ba32e12d-8283-f980-e1d0-1ca2a75a5152
* Content: [az container](https://docs.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest#az-container-create)
* Content Source: [src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by samkreter** [comment]
Hey @fabsenet 
You can create multiple secrets by having a space separating each secret. Below is an example. 
az container create -g myResourceGroup -n myContainerGroup --image nginx --secrets test=hey wow=hey2 --secrets-mount-path /secrets

Let me know if this works for you and i'll close this ticket.

**Comment by tjprescott** [comment]
The help text should call out that it is a space-separated list of key=value pairs

**Comment by fabsenet** [comment]
so basically leaving out all quotes is the solution here:

```powershell
az container create ... --secrets sshuser=xyz sshpass=abcdefg --secrets -mount-path "/secrets"
```

I tested it and it works! 🎺 🎆 

thanks
