### ISSUE TITLE
Cannot update redis cache with vnet integration

### ISSUE THREAD

**Issue by kalavan** [Azure/azure-cli#6769]
**Describe the bug**
When I try to scale redis cache that has vnet integration with command `az redis  update --name <<REDIS_NAME> --resource-group <RG_NAME> --set shardCount=1` command fails with:
`The requested update to the resource is not permitted. The following properties(s) cannot be modified: 'properties.subnet,properties.staticIP'.`

**To Reproduce**
1) Create clustered redis cache with vnet integration.
2) Try to scale it with cli with command like: `az redis  update --name <<REDIS_NAME> --resource-group <RG_NAME> --set shardCount=2`

**Expected behavior**
I expect the service to be scaled.

**Environment summary**
CLI is installed on linux machine with installation script `curl -L https://aka.ms/InstallAzureCli | bash`
`az --version                                                                                                                 
azure-cli (2.0.41)`

`uname -a
Linux 4.16.4-1-ARCH #1 SMP PREEMPT Tue Apr 24 13:21:29 UTC 2018 x86_64 GNU/Linux`

**Comment by ph0rman** [comment]
I'm seeing the same issue while trying to enable redis persistence (RDB).  In the portal it just silently fails, but via CLI it errors out saying prperties.subnet and properties.staticIP cannot be modified (even though those aren't technically the correct property values).
