### ISSUE TITLE
--version is unrecognized in az 2.0.41

### ISSUE THREAD

**Issue by TrevinAvery** [Azure/azure-cli#6772]
Running this command:
az vm image list -l eastus --publisher "RedHat" --offer "RHEL" --sku "7.3" --version "7.3.2017090105" --all
I get this response:
az: error: unrecognized arguments: --version 7.3.2017090105

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90dfc804-87d6-913a-27fe-a9446a04eb13
* Version Independent ID: bfcb97df-2055-9eca-7a93-60811136d8cd
* Content: [az vm image](https://docs.microsoft.com/en-us/cli/azure/vm/image?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
`--version` is not an argument for that command. I don't see anything in the docs referenced that suggest that it is. Were you following a blog or other document?

**Comment by TrevinAvery** [comment]
I just figured out that it was supposed to be "show" not "list":
az vm image show -l eastus --publisher "RedHat" --offer "RHEL" --sku "7.3" --version "7.3.2017090105"

Sorry about that. Thanks for the quick response.
