### ISSUE TITLE
Undocumented but required parameter (az network route-table update)

### ISSUE THREAD

**Issue by sptramer** [Azure/azure-cli#6775]
Some commands' documentation are simply wrong. E.g. az network route-table route update expects a parameter --route-parameters that is not even documented on this page.

__NOTE__: No further information is available. This is a duplicate of a VSTS ticket filed from verbatim text.

**Comment by tjprescott** [comment]
There is no `--route-parameters` argument for `route-table update` and the command runs fine. There's nothing actionable here so I'm closing this and you can cite this to close the VSTS ticket.
