### ISSUE TITLE
az vmss get-instance-view returns nothing if instance-id "*" and query specified.

### ISSUE THREAD

**Issue by RandalliLama** [Azure/azure-cli#6778]
**Describe the bug**
When running

az vmss get-instance-view --resource-group test-sc --name kvvmtest4 --instance-id '*' --query "extensions"

The command completes with no output, which is not expected.

If I remove the --query parameter I get the full view of all instances as expected.  If I leave the --query parameter in the command but specify a specific instance instead of "*" then I get the extensions information as expected.

**To Reproduce**
See above.

**Expected behavior**
I would prefer I get information from all instances with the query applied to the results.  The next best thing would to have an error message that explains that this is not supported.

**Environment summary**
I am running these commands on a High Sierra Mac.  

MININT-3BS5S37:test_config randallilama$ az --version
azure-cli (2.0.17)

acr (2.0.11)
acs (2.0.15)
appservice (0.1.16)
batch (3.1.3)
billing (0.1.4)
cdn (0.0.8)
cloud (2.0.7)
cognitiveservices (0.1.7)
command-modules-nspkg (2.0.1)
component (2.0.7)
configure (2.0.10)
consumption (0.1.4)
container (0.1.10)
core (2.0.16)
cosmosdb (0.1.12)
dla (0.0.11)
dls (0.0.13)
eventgrid (0.1.3)
extension (0.0.2)
feedback (2.0.6)
find (0.2.6)
interactive (0.3.9)
iot (0.1.11)
keyvault (2.0.10)
lab (0.0.10)
monitor (0.0.9)
network (2.0.14)
nspkg (3.0.1)
profile (2.0.12)
rdbms (0.0.6)
redis (0.2.8)
resource (2.0.14)
role (2.0.11)
servicefabric (0.0.3)
sf (1.0.8)
sql (2.0.11)
storage (2.0.15)
vm (2.0.14)

Python location '/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python'
Extensions directory '/Users/randallilama/.azure/cliextensions'

Python (Darwin) 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 12:01:12)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

Legal docs and information: aka.ms/AzureCliLegal
  

**Additional context**

**Comment by tjprescott** [comment]
If you are using "*" you probably get a list output, in which case your query needs to be `[].extensions`.

**Comment by RandalliLama** [comment]
Awesome.  That did it.  Thank you!
