### ISSUE TITLE
Azure Container Registry

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-cli#6785]
_From @Deepfat on July 9, 2018 6:23_

When I tried this everything was fine but I had to use Docker.com to store the container and NOT ACR as your cli command doesnt' have a way of authenticating against ACR.  For AKS we can create permissions as we know the SPN of that service.  #OneMicrosofDo

_Copied from original issue: Azure/azure-functions-core-tools#572_

**Comment by ahmedelnably** [comment]
To configure ACR, you will need to use [“az webapp config container set”](https://docs.microsoft.com/en-us/cli/azure/webapp/config/container?view=azure-cli-latest#az-webapp-config-container-set) command and specify the url, username, password of your container. Here is a tutorial to know the exact syntax of these parameters [https://docs.microsoft.com/en-us/azure/app-service/containers/tutorial-custom-docker-image#use-a-docker-image-from-any-private-registry-optional](https://docs.microsoft.com/en-us/azure/app-service/containers/tutorial-custom-docker-image#use-a-docker-image-from-any-private-registry-optional )

**Comment by ahmedelnably** [comment]
Closing this issue, if there is any update, please reopen the issue
