### ISSUE TITLE
az group deployment fails on empty parameters object

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/azure-cli#6787]
**Describe the bug**
az group deployment create -g "$resourceGroupName" -n AzureRMSamples --template-uri $templateUri --parameters "$parameterJson" --verbose

throws an error when $parametersJson = {}

**Expected behavior**
If the parameters object is empty, and empty object should be passed to the deployment (or not) - command should not fail.

**Additional context**
Without this, it means the caller has to detect issue different commands for each scenario - making scripting or CI/CD scenarios slightly more complex due to the unnecessary code.

**Comment by tjprescott** [comment]
Thanks for the report.
