### ISSUE TITLE
aks browse very buggy

### ISSUE THREAD

**Issue by marekr** [Azure/azure-cli#6794]
**Describe the bug**
I use aks browse on a RBAC cluster often. It seems the proxying gets messed up often where requests just stop working and it gets stuck reloading the same content in the dashboard no matter what is navigated to. i.e. navigating to controllers just reloads the pods page i may have been on when it broke.

Killing the running az aks browse command and restarting is the only way it works again.

Sometimes it happens immediately on the first thing I click on in the dashboard, other times the dashboard works great for quite awhile until it fails.

During this time, the console does not report connection loss or anything, it still prints Handling connection.

**To Reproduce**
browse to a RBAC cluster, use token login?

**Expected behavior**
dashboard not to bug up

**Environment summary**

```
az --version
azure-cli (2.0.41)

acr (2.0.28)
acs (2.1.3)
advisor (0.5.1)
ams (0.1.1)
appservice (0.1.36)
backup (1.1.2)
batch (3.2.4)
batchai (0.3.1)
billing (0.1.8)
cdn (0.0.14)
cloud (2.0.15)
cognitiveservices (0.1.13)
command-modules-nspkg (2.0.1)
configure (2.0.17)
consumption (0.3.1)
container (0.2.1)
core (2.0.41)
cosmosdb (0.1.21)
dla (0.1.0)
dls (0.0.22)
dms (0.0.1)
eventgrid (0.1.12)
eventhubs (0.1.3)
extension (0.1.0)
feedback (2.1.3)
find (0.2.11)
interactive (0.3.25)
iot (0.1.21)
keyvault (2.0.23)
lab (0.0.22)
maps (0.2.0)
monitor (0.1.8)
network (2.1.5)
nspkg (3.0.2)
policyinsights (0.1.0)
profile (2.0.27)
rdbms (0.2.5)
redis (0.2.14)
reservations (0.2.1)
resource (2.0.32)
role (2.0.26)
servicebus (0.1.2)
servicefabric (0.0.12)
sql (2.0.27)
storage (2.0.35)
vm (2.0.35)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\mroszko\.azure\cliextensions'

Python (Windows) 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal
```

**Additional context**
I've tried two different PCs running Windows 10 Pro and the same az client.

**Comment by jnoller** [comment]
Please see https://github.com/Azure/AKS/issues/68 - this is a known issue with the AKS usage of the Azure basic load balancer including short (5 minute) timeouts. We are in the process of shipping Standard Load Balancer support https://github.com/Azure/AKS/releases/tag/2019-06-24 and phasing out basic load balancers in 2019.
