### ISSUE TITLE
View Logs for Azure App Service and Functions

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-cli#6796]
**Is your feature request related to a problem? Please describe.**
When developers are developing Web apps and functions, they often need to view server side logs. They are forced to jump out of their dev environments and view logs by navigating through multiple blades in Azure Portal. This must be easier than that.

**Describe the solution you'd like**
```
$ az webapp viewlogs -g MyResourceGroup -n MyUniqueAppName --last 500
$ az functionapp viewlogs -g MyResourceGroup -n MyUniqueAppName --last 500
```
Developers can view logs without navigating through Azure Portal

**Describe alternatives you've considered**
8 Azure Portal clicks to view logs

**Comment by ahmedelnably** [comment]
We already have 
az webapp log download
az webapp log tail
https://docs.microsoft.com/en-us/cli/azure/webapp/log?view=azure-cli-latest

Both should work for webapp and functions app
