### ISSUE TITLE
ACR does regular expression matching in .dockerignore

### ISSUE THREAD

**Issue by shkit** [Azure/azure-cli#6798]
**Describe the bug**
When I try "az acr build" to build PyTorch, some files are not copied.
With --debug option for az command, I got these logs.
~~~
.dockerignore: rule '*/**/*.so*' matches 'aten/src/THC/THCTensorMathCompareT.cuh'.
.dockerignore: rule '*/**/*.so*' matches 'aten/src/THC/THCTensor.h'.
.dockerignore: rule '*/**/*.so*' matches 'aten/src/THC/THCTensorMathMagma.cu'.
.dockerignore: rule '*/**/*.so*' matches 'aten/src/THC/THCTensorRandom.h'.
~~~
In "az acr" command .dockerignore seems to be treated as regular expression at _upload_source_code()@azure/cli/command_modules/acr/build.py, but it should be matched as glob expression, I think.

**Expected behavior**
Above files are copied to ACR build service.

**Comment by ehotinger** [comment]
@northtyphoon
