### ISSUE TITLE
Manage Owner of groups through Az CLI

### ISSUE THREAD

**Issue by JamesDLD** [Azure/azure-cli#6799]
Would be really convenient for Az CLI or Linux users to implement this feature request.

Same feature that could be done through the PowerShell module « azuread version 2.0.0.115», associated « how to » is available here : https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/groups-settings-v2-cmdlets#manage-owners-of-groups

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c659a298-8897-6d50-c1d9-c14a3b0e6364
* Version Independent ID: 2d2bec5b-ef92-f65f-bfd0-ccdabda52a41
* Content: [az ad group member](https://docs.microsoft.com/en-us/cli/azure/ad/group/member?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by JamesDLD** [comment]
Not sure that it’s the good place, I have also added a feature request on the Azure Voice here : https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/34835497-manage-owner-of-groups-through-az-cli

**Comment by JamesDLD** [comment]
Just adding 2 cent context. This would be very useful for one of my client where we build apps environment As Code where AD group access are created and assigned to AzureRm roles on our resources.

When this is done we set manually an owner of the group (this is the painfull action part) and this person just have to add it’s team members to groups to inherit to the assigned privileges of this group.

**Comment by tjprescott** [comment]
@yugangw-msft are you familiar with these PS commands?

**Comment by yugangw-msft** [comment]
Yes, I know the PS cmdlet. Ownership management is the area with good amount of user voices, and we have discussed with AAD graph team for a while to have this gap filled. This work would have to start from [swagger spec](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/graphrbac/data-plane/stable/1.6/graphrbac.json)

Closing this, as #5651 was opened for the same ask.
