### ISSUE TITLE
[Register command] Parameter comments with ":" are not parsed

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#680]
Instead the comment is blank.  This frequently happens with text like "Example: ..."

**Comment by tjprescott** [comment]
@BurtBiel does this when the text comes from a docstring, alias, help file, or all of the above?

**Comment by BurtBiel** [comment]
@tjprescott  I saw this behavior with the register argument syntax.  We had this issue in the past, but I thought it got fixed.

**Comment by tjprescott** [comment]
I've identified a case where this occurs: `az storage table query -h`.
