### ISSUE TITLE
Take Developers to App Service Linux SSH Quickly - az webapp ssh

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-cli#6801]
**Is your feature request related to a problem? Please describe.**
From dev box command lines, connect developers to App Service Linux instances quickly without requiring them to download and configure SSH clients or navigate through 9-10 blades in Azure Portal to reach SSH client windows that very often disconnect or reset connections.

The same solution can be extended to Azure Functions on Linux

**Describe the solution you'd like**
```
az webapp ssh -n mywebapp -g myresourcegroup
// functions on Linux 
az functionapp ssh -n myfunctionapp -g myresourcegroup
```
**Describe alternatives you've considered**
Install an SSH client and configure it. Or, navigate through 9-10 blades in Azure Portal to reach SSH client windows that very often disconnect or reset connections.

**Comment by tjprescott** [comment]
We have considered this before, not necessarily for webapps but for VMs. Based on the amount of time and future maintenance it would require to make a command that would work on all required platforms, we have typically evaluated this as a high cost, low return item. cc/ @johanste

**Comment by johanste** [comment]
Is the high order bit getting the information needed to connect to the app service, or is it installing and maintaining an SSH client? 

If the former, having specific commands that makes it easier to translate the information we have (i.e. the resource group/name of the app service to the DNS name/IP Address) would be feasible.

**Comment by ahmedelnably** [comment]
What we decided when we launched the ssh capability is to call the command
`az webapp remote-connection create`, it is currently available in the webapp cli extension.
As we are opening a "remote connection" that can be used for multiple reasons (other than SSH), we opted only to provide the user a create connection option, and not specifically just an SSH connection.

That's said, the original design was to have an option to launch an ssh client on the client side (if ssh is present, so we wouldn't have it working for all platforms)
cc/ @rramachand21 we will need to plan to move this command to the main CLI branch.

**Comment by selvasingh** [comment]
@ahmedelnably and @rramachand21 - agree that this should be in the main CLI branch.

The remote-connection does not appear to work.

```
bash-3.2$ az extension add --name webapp
The installed extension 'webapp' is in preview.
bash-3.2$ az webapp remote-connection create -g myjavase -n myjavase-07262018aa
Auto-selecting port: 50175
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/selvasingh/.azure/cliextensions/webapp/azext_webapp/custom.py", line 270, in _start_tunnel
    if not _check_for_ready_tunnel(remote_debugging_enabled, tunnel_server):
  File "/Users/selvasingh/.azure/cliextensions/webapp/azext_webapp/custom.py", line 240, in _check_for_ready_tunnel
    default_port = tunnel_server.is_port_set_to_default()
  File "/Users/selvasingh/.azure/cliextensions/webapp/azext_webapp/tunnel.py", line 95, in is_port_set_to_default
    raise CLIError("Failed to connect to '{}' with status code '{}' and reason '{}'".format(url, r.status, r.reason))
knack.util.CLIError: Failed to connect to 'https://myjavase-07262018aa.scm.azurewebsites.net/AppServiceTunnel/Tunnel.ashx?GetStatus' with status code '503' and reason 'Service Unavailable'
```

**Comment by selvasingh** [comment]
@ahmedelnably and @rramachand21 - imagine there are multiple instances of a Web app, when developers log in, which instance are they logging in?

**Comment by panchagnula** [comment]
this command has been released see https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-ssh
