### ISSUE TITLE
Implicit circular dependency between core and profile module

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#6812]
In `azure.cli.core.commands.arm` there is a reference to the command module profile's module: 

https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/commands/arm.py#L301

1. Implictly make every command modules depend on the `profile` module, since it referenced in core.
2. Unable the break down the boundary between modules to run tests individually in each module.

**Comment by troydai** [comment]
@yugangw-msft let's chat about it tomorrow.

**Comment by tjprescott** [comment]
@yugangw-msft is this fixed now?

**Comment by yugangw-msft** [comment]
yes
