### ISSUE TITLE
Invalid code in azure.cli.command.modules.profile.custom._load_subscriptions

### ISSUE THREAD

**Issue by troydai** [Azure/azure-cli#6813]
https://github.com/Azure/azure-cli/blob/0bbbae84283fde744f79497b43ce0bef00051e1c/src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/custom.py#L27

``` Python
def _load_subscriptions(cli_ctx, all_clouds=False, refresh=False):
    profile = Profile(cli_ctx=cli_ctx)
    if refresh:
        subscriptions = profile.refresh_accounts()
    subscriptions = profile.load_cached_subscriptions(all_clouds)
    return subscriptions
```
The `subscriptions` will be always overridden no matter `refres` is true or false. Unless the `refress_accounts()` changes the state, these two lines are useless. Otherwise, there is not reason to have the `subscriptions` on line 4.

**Comment by troydai** [comment]
@yugangw-msft

**Comment by yugangw-msft** [comment]
`refresh_account` shall make live requests to update cached accounts at local. The code logic is right here.
`refresh` is a pretty heavy operation which could fail, say, you have an account which have not used for a while and the refresh token associated with its tenant has expired.
