### ISSUE TITLE
Azure CLI for Microsoft.Network/virtualNetworkTap

### ISSUE THREAD

**Issue by karthikananth** [Azure/azure-cli#6815]
This is an Ignite preview feature. Please help complete the Azure CLI development.
Azure/azure-rest-api-specs-pr#521

**Comment by karthikananth** [comment]
This is an Ignite preview feature. Please help complete the Azure CLI development.

https://github.com/Azure/azure-rest-api-specs-pr/pull/521

**Comment by tjprescott** [comment]
Private extension has been delivered. Extension will be made public at Ignite.
