### ISSUE TITLE
"az container delete" using half name

### ISSUE THREAD

**Issue by weiserdl** [Azure/azure-cli#6817]
Is there a way to use this command to delete containers with partial name? for i.e.
az container delete Container1*  (to remove every container starting like that, but not the ones starting with Container2#)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e5d1da7-7c4f-c9e6-e4b9-a30407675acf
* Version Independent ID: ba32e12d-8283-f980-e1d0-1ca2a75a5152
* Content: [az container](https://docs.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest#az-container-delete)
* Content Source: [src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by samkreter** [comment]
@weiserdl We currently do not plan on supporting a wildcard feature. The best way would be writing a quick bash script to use 'az container list' to get all the container names in the group then 'az container delete' for each result.

**Comment by tjprescott** [comment]
You could also use a script to get a list of container IDs, filter the list of IDs and then supply that list to the `delete` command with `--ids …`.  Effectively this does what @samkreter is suggesting, calling the delete command for each item in the list.

**Comment by marekpiotrowski** [comment]
If someone still needs it (not too proficient at bash so here's a python script instead) - just replace the `resource_group` and `prefix`:
```
from subprocess import Popen, PIPE
import json

if __name__ == "__main__":
    proc = Popen("az container list", shell=True, stdout=PIPE)
    text = proc.communicate()[0]
    containers = json.loads(text)
    resource_group = "msim_docker"
    prefix = "rgd-instance-"
    for c in containers:
        if c['name'].startswith(prefix):
            rm_proc = Popen(f"az container delete --name {c['name']} --resource-group={resource_group} --yes", shell=True)
            rm_proc.communicate()
            print(f"Removed container: {c['name']}")

```
