### ISSUE TITLE
az webapp up -n <webapp name> produces an error in bash due to malformed path

### ISSUE THREAD

**Issue by morgangrobin** [Azure/azure-cli#6819]
**Describe the bug**
It appears the 'az webapp up' command is mixing Linux style paths with windows style paths.

It appears the 'az webapp up' command is mixing Linux style paths with windows style paths.
Here is what happens when I run the command on the bash cloud shell:
`morgan@Azure:~/clouddrive/quickstart/nodejs-docs-hello-world$ az webapp up -n mg18sampleapp2`
[omitted for brevity]
`[Errno 22] Invalid argument: '/usr/morgan/clouddrive/quickstart\nodejs-docs-hello-world.zip'`

Note the backslash instead of a forward slash in the path. 

**To Reproduce**
Follow this tutorial: https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-nodejs

**Other information**

I opened up a doc bug here: https://github.com/MicrosoftDocs/azure-docs/issues/11798#issuecomment-405423106 but I was redirected to the azure-cli repo. My primary goal is to actually get a node.js webapp up and running, so I would appreciate any workarounds/suggestions. 

<img width="345" alt="1" src="https://user-images.githubusercontent.com/2502505/42833170-4488f86e-89a8-11e8-897b-cb7a17951ea6.PNG">
<img width="367" alt="2" src="https://user-images.githubusercontent.com/2502505/42833171-44b7e980-89a8-11e8-8b7d-881441c53aa3.PNG">
<img width="384" alt="3" src="https://user-images.githubusercontent.com/2502505/42833172-44dbfbea-89a8-11e8-9167-f729ef84662a.PNG">
<img width="400" alt="4" src="https://user-images.githubusercontent.com/2502505/42833169-445abd78-89a8-11e8-8e0e-d7e111aa74aa.PNG">

**Comment by tjprescott** [comment]
Hi @morgangrobin, `az webapp up` is part of a CLI extension, so I posted your issue there and cc'ed you on it. I will close this issue, but you can follow the status here:

https://github.com/Azure/azure-cli-extensions/issues/236
