### ISSUE TITLE
Chain commands on one line similar to other CLIs

### ISSUE THREAD

**Issue by isaacrlevin** [Azure/azure-cli#6821]
**Please describe.**
Being able to chain commands together would be valuable

**Describe the solution you'd like**
Similar to other CLIs, something like `&` allowing the ability to have multiple commands in one statement

**Describe alternatives you've considered**
Currently, I have the commands in PowerShell and than run my ps file to get batch experience

**Comment by yonzhan** [comment]
@jiasli  add to S162.

**Comment by jiasli** [comment]
We have provided some easy ways to chain commands, please check https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#passing-values-from-one-command-to-the-other

We recommend using Bash or PowerShell as scripting tools. For specific usage, please let us know.
