### ISSUE TITLE
Enable diagnostics

### ISSUE THREAD

**Issue by MichaelSmyth184** [Azure/azure-cli#6823]
az vm boot-diagnostics get-boot-log --ids $(az vm list -g MyResourceGroup --query "[].id" -o tsv)
Returns null.
az vm list -g MyResourceGroup --query "[].id" -o tsv returns vms ok, but the command as a whole returns null and doesnt apply diagnostics.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d2d4fa0-d32e-5628-8785-75c0da9d06fb
* Version Independent ID: 4b38be37-9b9f-94d7-bc26-3f279521c3a9
* Content: [az vm boot-diagnostics](https://docs.microsoft.com/en-us/cli/azure/vm/boot-diagnostics?view=azure-cli-latest#az-vm-boot-diagnostics-enable)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
please reactivate with details
