### ISSUE TITLE
[RBAC] `az app update` generic arguments do not work

### ISSUE THREAD

**Issue by unacceptable** [Azure/azure-cli#6826]
What if I want to set a value such as a key name (that's in a json list.)? Like so:

```
  "passwordCredentials": [
    {
      "customKeyIdentifier": null,
      "endDate": "2299-12-31T00:00:00Z",
      "keyId": "d7bd63f7-f6e6-4e13-a86d-2b65922a0864",
      "startDate": "2018-07-18T00:25:14.658779Z",
      "value": null
    }
  ],
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 921aa920-c25f-5227-aabb-49116da38fa7
* Version Independent ID: 9b5a53ad-edf8-4d89-f8e6-cde01b7866f6
* Content: [az ad app](https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest#az-ad-app-update)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ScriptMyJob** [comment]
Sorry I didn't realize that this would open a GitHub bug.  However, it would appear that this is not well documented if the capability does exist.  I am rather surprised that `az ad app create` does not appear to have a way to set this but it does have a way to set the password.

¯\_(ツ)_/¯

**Comment by tjprescott** [comment]
`--set passwordCredentials[0].customKeyIdentifer='blah'`

**Comment by tjprescott** [comment]
You should also be able to use syntax like:
`--set passwordCredentials[keyId='blah'].customKeyIdentifier='foo'` so that you can search for a key value in the list.

**Comment by ScriptMyJob** [comment]
@tjprescott I have already tried the first syntax that you have suggested.  I will have to try the second recommendation after I get back from lunch.

**Comment by tjprescott** [comment]
If you run the first syntax with `--debug` you can see if your value was correctly set.  If nothing happened it doesn't mean the syntax didn't work--it could very well mean that you can't change that property.

**Comment by tjprescott** [comment]
Actually, this is a bug in the RBAC update command.

**Comment by tjprescott** [comment]
cc/ @yugangw-msft

**Comment by tjprescott** [comment]
The generic arguments now work, but I will keep this issue open to remove the workaround once the REST API specs issue is fixed.

**Comment by ScriptMyJob** [comment]
@tjprescott when is the documentation going to be updated to reflect this change?

**Comment by tjprescott** [comment]
My PR was a bugfix, so the documentation won't change. It ensures that the syntax `--set passwordCredentials[0].customKeyIdentifer='blah'` will work as it should.

**Comment by yonzhan** [comment]
Was this issue resolved?

**Comment by jiasli** [comment]
I think there is still a bug in the code: In `update_application`, if no `password` is provided,  `password_credentials` will be set to `None`, causing the generic update `--set` to fail.

https://github.com/Azure/azure-cli/blob/1c0e9c3e18c34116d5a2e25cb7460d1af8a85969/src/azure-cli/azure/cli/command_modules/role/custom.py#L963

At the same time, updating an existing password credential is not a supported operation by AAD. 

When I directly invoke the API with 

```http
PATCH https://graph.windows.net/{}/applications/{}

{
  "passwordCredentials": [
    {
      "customKeyIdentifier": "//5yAGIACQBjAA==",
      "endDate": "2021-02-18T05:47:34.393950+00:00",
      "keyId": "1d0823d4-ce00-48e4-ace4-4172c0ffa909",
      "startDate": "2020-02-18T05:47:34.393950+00:00",
      "value": null
    }
  ]
}
```

I got 400 Bad Request:
```jsonc
{
    "odata.error": {
        "code": "Request_BadRequest",
        "message": {
            "lang": "en",
            "value": "Update to existing credential with KeyId '1d0823d4-ce00-48e4-ace4-4172c0ffa909' is not allowed."
        },
        "requestId": "e4750dca-6e44-4c45-b14b-7dfaf719b018",
        "date": "2020-02-18T07:13:14",
        "values": [
            {
                "item": "PropertyName",
                "value": "passwordCredentials"
            },
            {
                "item": "PropertyErrorCode",
                "value": "KeyNotUpdatable"
            }
        ]
    }
}
```
So fixing this bug in CLI code is meaningless.
