### ISSUE TITLE
How do you resize the VMSS using azure cli ?

### ISSUE THREAD

**Issue by arunjohn** [Azure/azure-cli#6829]
I was not able to find a proper command that would help upgrading the VMSS size( eg: Standard_D2 to Standard_D3 ). Please advise how this can be done in command-line as I looking more into automating this task. rather than performing this on the Portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0408c294-207a-2b72-7b93-e09121602b75
* Version Independent ID: 852cb67b-70c6-b811-3b0a-5d5b84b8a911
* Content: [az vmss](https://docs.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machine-scale-sets**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
`az vmss update -g {rg} n {name} --set sku.name="YOUR_VALUE"` If you are changing from Standard to Premium you must also include `--set sku.tier="Premium"`

**Comment by yugangw-msft** [comment]
Please reactivate if @tjprescott's suggestion is not enough
