### ISSUE TITLE
Public IP SKU for VM not yet supported in profile 2017-03-09-profile

### ISSUE THREAD

**Issue by viananth** [Azure/azure-cli#6833]
**Describe the bug**
When trying to create a Vm with public ip in Azure using 2017-03-09-profile, it fails with the following error:

> 
> usage: az vm create [-h] [--verbose] [--debug]
>                     [--output {tsv,json,table,jsonc}] [--query JMESPATH]
>                     [--private-ip-address PRIVATE_IP_ADDRESS]
>                     [--location LOCATION] [--generate-ssh-keys]
>                     [--admin-username ADMIN_USERNAME]
>                     [--data-disk-caching DATA_CACHING [DATA_CACHING ...]]
>                     [--storage-sku {Standard_LRS,Standard_GRS,Standard_RAGRS,Standard_ZRS,Premium_LRS}]
>                     [--image IMAGE]
>                     [--public-ip-address-dns-name PUBLIC_IP_ADDRESS_DNS_NAME]
>                     [--os-disk-name OS_DISK_NAME] --name NAME
>                     [--boot-diagnostics-storage BOOT_DIAGNOSTICS_STORAGE]
>                     [--plan-name PLAN_NAME] [--public-ip-sku PUBLIC_IP_SKU]
>                     [--storage-container-name STORAGE_CONTAINER_NAME]
>                     [--public-ip-address-allocation {dynamic,static}]
>                     [--attach-os-disk ATTACH_OS_DISK] [--nics NICS [NICS ...]]
>                     [--attach-data-disks ATTACH_DATA_DISKS [ATTACH_DATA_DISKS ...]]
>                     [--size SIZE] [--os-disk-size-gb OS_DISK_SIZE_GB]
>                     [--subnet-address-prefix SUBNET_ADDRESS_PREFIX]
>                     [--role IDENTITY_ROLE] [--ssh-key-value SSH_KEY_VALUE]
>                     [--license-type {Windows_Server,Windows_Client,None}]
>                     [--use-unmanaged-disk]
>                     [--authentication-type {ssh,password}]
>                     [--admin-password ADMIN_PASSWORD] [--nsg NSG]
>                     --resource-group RESOURCE_GROUP_NAME
>                     [--nsg-rule {RDP,SSH}] [--plan-product PLAN_PRODUCT]
>                     [--data-disk-sizes-gb DATA_DISK_SIZES_GB [DATA_DISK_SIZES_GB ...]]
>                     [--secrets SECRETS [SECRETS ...]]
>                     [--assign-identity [ASSIGN_IDENTITY [ASSIGN_IDENTITY ...]]]
>                     [--vnet-address-prefix VNET_ADDRESS_PREFIX]
>                     [--vnet-name VNET_NAME]
>                     [--public-ip-address PUBLIC_IP_ADDRESS]
>                     [--custom-data CUSTOM_DATA]
>                     [--storage-caching {None,ReadOnly,ReadWrite}]
>                     [--ssh-dest-key-path SSH_DEST_KEY_PATH] [--validate]
>                     [--scope IDENTITY_SCOPE] [--os-type {windows,linux}]
>                     [--no-wait] [--plan-promotion-code PLAN_PROMOTION_CODE]
>                     [--tags [TAGS [TAGS ...]]]
>                     [--availability-set AVAILABILITY_SET]
>                     [--subscription _SUBSCRIPTION]
>                     [--plan-publisher PLAN_PUBLISHER] [--subnet SUBNET]
>                     [--storage-account STORAGE_ACCOUNT]
> az vm create: error: 'NoneType' object has no attribute 'standard'
> Traceback (most recent call last):
>   File "d:\Github2\azure-cli\env\lib\site-packages\knack\invocation.py", line 100, in _validation
>     self._validate_cmd_level(parsed_ns, cmd_validator)
>   File "d:\github2\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 423, in _validate_cmd_level
>     cmd_validator(**self._build_kwargs(cmd_validator, ns))
>   File "d:\github2\azure-cli\src\command_modules\azure-cli-vm\azure\cli\command_modules\vm\_validators.py", line 958, in process_vm_create_namespace
>     _validate_vm_vmss_create_public_ip(cmd, namespace)
>   File "d:\github2\azure-cli\src\command_modules\azure-cli-vm\azure\cli\command_modules\vm\_validators.py", line 724, in _validate_vm_vmss_create_public_ip
>     if namespace.public_ip_sku == PublicIPAddressSkuName.standard.value:
> AttributeError: 'NoneType' object has no attribute 'standard'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "c:\program files (x86)\python35\Lib\unittest\case.py", line 58, in testPartExecutor
>     yield
>   File "c:\program files (x86)\python35\Lib\unittest\case.py", line 600, in run
>     testMethod()
>   File "d:\Github2\azure-cli\env\lib\site-packages\azure_devtools\scenario_tests\preparers.py", line 50, in _preparer_wrapper
>     fn(test_class_instance, **kwargs)
>   File "d:\github2\azure-cli\src\command_modules\azure-cli-vm\azure\cli\command_modules\vm\tests\profile_2017_03_09\test_vm_commands.py", line 884, in test_vm_create_custom_ip
>     self.cmd('vm create -n {vm} -g {rg} --image openSUSE-Leap --admin-username user11 --private-ip-address 10.0.0.5 --public-ip-sku {public_ip_sku} --public-ip-address-dns-name {dns} --generate-ssh-keys --use-unmanaged-disk')
>   File "d:\github2\azure-cli\src\azure-cli-testsdk\azure\cli\testsdk\base.py", line 155, in cmd
>     return execute(self.cli_ctx, command, expect_failure=expect_failure).assert_with_checks(checks)
>   File "d:\github2\azure-cli\src\azure-cli-testsdk\azure\cli\testsdk\base.py", line 194, in __init__
>     self._in_process_execute(cli_ctx, command, expect_failure=expect_failure)
>   File "d:\github2\azure-cli\src\azure-cli-testsdk\azure\cli\testsdk\base.py", line 245, in _in_process_execute
>     self.exit_code = cli_ctx.invoke(shlex.split(command), out_file=stdout_buf) or 0
>   File "d:\Github2\azure-cli\env\lib\site-packages\knack\cli.py", line 197, in invoke
>     cmd_result = self.invocation.execute(args)
>   File "d:\github2\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 299, in execute
>     self._validation(expanded_arg)
>   File "d:\Github2\azure-cli\env\lib\site-packages\knack\invocation.py", line 107, in _validation
>     getattr(parsed_ns, '_parser', self.parser).validation_error(str(err))
>   File "d:\github2\azure-cli\src\azure-cli-core\azure\cli\core\parser.py", line 131, in validation_error
>     return super(AzCliCommandParser, self).error(message)
>   File "c:\program files (x86)\python35\Lib\argparse.py", line 2385, in error
>     self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
>   File "c:\program files (x86)\python35\Lib\argparse.py", line 2372, in exit
>     _sys.exit(status)
> SystemExit: 2
> 

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
dev setup

**Comment by yugangw-msft** [comment]
@viananth, this is a test issue that this scenario is not meant for stack profile

**Comment by viananth** [comment]
Thank you Yugang! But I don't suppose checking for not null isn't a bad idea. Thoughts? #6834

**Comment by viananth** [comment]
@yugangw-msft Can we still keep this check for null?
