### ISSUE TITLE
[RBAC] Add commands to manage key/password credentials on an AD app

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#6837]
**Is your feature request related to a problem? Please describe.**
The portal supports adding one or more password or key credential objects. The current `ad app create` command only supports adding one, and doesn't permit all of the customizations. Furthermore, these objects can't be updated after the fact.

**Describe the solution you'd like**
Add sub-commands to `az ad app` for managing these credential objects. 

**Describe alternatives you've considered**
Using generic update after the fact, but the service does not allow you to update these objects once created, so this doesn't work.

**Comment by tjprescott** [comment]
@ScriptMyJob this is your underlying issue. The problem with the generic update will be fixed via a workaround, but even once it is, you would not be able to change the customKeyIdentifier. It has to be set on creation. Please follow this issue.

**Comment by yugangw-msft** [comment]
All are done, the only exception is you can't append to the one added in the portal, see #7957 for context and workaround
