### ISSUE TITLE
Remove Features Resource types in the 2017-03-09-profile map 

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-cli#6838]
**Describe the bug**
Features api is not supported in azurestack. The profile map should not have the entry

**Comment by yonzhan** [comment]
@Juliehzl  add to S162.

**Comment by Juliehzl** [comment]
Hi @bganapa, do you mean `ResourceType.MGMT_RESOURCE_FEATURES`. If yes, I think it already removed according to  https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/profiles/_shared.py#L221.

**Comment by Juliehzl** [comment]
Given no response, I will close this issue.  @bganapa If you still have any problem, feel free to reopen it or create a new one.

**Comment by bganapa** [comment]
@Juliehzl Sorry about that. We can close this.
