### ISSUE TITLE
Consume multi api KV control/data plane in CLI 

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-cli#6839]
**Describe the bug**
Azure KV is moving on to support the api version '2018-02-14' and azure stack only supports 2016-10-01.
WE need to consume multi api KV Control/Data plane packages in CLI and make respective changes for azurestack

**Comment by tjprescott** [comment]
@schaabs isn't this done?

**Comment by schaabs** [comment]
yes fixed with PR https://github.com/Azure/azure-cli/pull/6991. Closing the issue.
