### ISSUE TITLE
[Storage] Service Stats Methods Return Poor Error if SKU is not RAGRS

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#684]
Calls to the `get_{service}_service_stats` methods in the Python SDK work only with RAGRS enabled storage accounts. If you use these commands with other storage account types, you simply get a series of HTTPS connection failure messages.

The service should query the storage account specified in the connection string and respond with an appropriate error message if the storage account type is incorrect.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
