### ISSUE TITLE
wring documentation of --expiration-date

### ISSUE THREAD

**Issue by claasd** [Azure/azure-cli#6840]
lab vm create: The expiration date must be given in the format yyyy-MM-ddTHH:mm:ss (e.g. 2018-07-26T10:24:35) and not in the format YYYY-mm-dd.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef5457fd-c38a-6fb8-1df4-24a15e6ba787
* Version Independent ID: ef65acdc-464a-08c7-b013-d9e3f1560977
* Content: [az lab vm](https://docs.microsoft.com/en-us/cli/azure/lab/vm?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/_help.py)
* Service: **devtest-lab**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
fixed
