### ISSUE TITLE
Unable to specify ports without dns-name-label

### ISSUE THREAD

**Issue by dancowen** [Azure/azure-cli#6841]
It doesn't seem possible to spin up a container with specific ports open without specifying a DNS name.

az group create --name someResourceGroup --location eastus
az container create --resource-group someResourceGroup --name seleniumhub --image selenium/hub:3.13.0-argon --dns-name-label my-selenium-hub --ports 4444

Returns:

"ports": [
        {
          "port": 4444,
          "protocol": "TCP"
        }
      ],

az container create --resource-group someResourceGroup --name chromenode --image selenium/node-chrome:3.13.0-argon --ports 5555 -e HUB_HOST=my-selenium-hub.eastus.azurecontainer.io

Returns: "ports": [],

Is this intended?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e5d1da7-7c4f-c9e6-e4b9-a30407675acf
* Version Independent ID: ba32e12d-8283-f980-e1d0-1ca2a75a5152
* Content: [az container](https://docs.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest#az-container-create)
* Content Source: [src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by samkreter** [comment]
@dancowen This is intended behavior. In order to expose the ports you will either need a dns-name-label or use the "--ip-address public" to expose via a public IP address.
