### ISSUE TITLE
Error when upgrading from command line

### ISSUE THREAD

**Issue by justinhauer** [Azure/azure-cli#6842]
I am able to upgrade my kubernetes version from the Azure console but when I try to upgrade from the command line with the mandatory parameters listed above I get the following error: "ValidationError: Parameter 'ManagedClusterAADProfile.server_app_secret' can not be None" What else needs to be set besides the three mandatory parameters for an upgrade listed above?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-upgrade)
* Content Source: [latest/docs-ref-autogen/aks.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/aks.yml)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jdogg89** [comment]
specifically I am using the CLI, not PowerShell

**Comment by doug-fish** [comment]
FWIW I had the same error using the azure cli to scale the cluster. I was able to recover by upgrading my azure cli from 2.0.37 -> 2.0.42

**Comment by jluk** [comment]
This should be resolved by using the latest CLI modules, closing as a result.
