### ISSUE TITLE
Identity assign does not seem to work

### ISSUE THREAD

**Issue by mariojacobo** [Azure/azure-cli#6851]
$ az vm identity assign -g MyResourceGroup -n MyVm --role Reader 
usage error: '--role Reader' is not applicable as the '--scope' is not provided

This works: 
$ az vm identity assign -g MyResourceGroup -n MyVm 
{
  "systemAssignedIdentity": "80594eff-4edb-4599-8973-b29afcef251b",
  "userAssignedIdentities": []
}

Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de241c0d-7295-bf01-a431-3c94a02c099b
* Version Independent ID: 780195c5-fc93-ee0d-e5e5-8f62f4dee6ee
* Content: [az vm identity](https://docs.microsoft.com/en-us/cli/azure/vm/identity?view=azure-cli-latest#az-vm-identity-assign)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
Please do like the error says `usage error: '--role Reader' is not applicable as the '--scope' is not provided` by providing the `--scope`, since explicitly setting the `--role`  voids the defaults

**Comment by mariojacobo** [comment]
Your tutorial literally says  to run that specific command: az vm identity assign -g MyResourceGroup -n MyVm --role Reader

I offered the workaround, shouldn't you fix the tutorial since the actual command does not work ????

**Comment by yugangw-msft** [comment]
I see, doc issue, Thanks.
