### ISSUE TITLE
az eventhubs eventhub create with data lake capture destination

### ISSUE THREAD

**Issue by frli** [Azure/azure-cli#6852]
**Is your feature request related to a problem? Please describe.**
There currently is no way to enable event capture to `Data Lake` when creating an `Event Hub` via the `az eventhubs eventhub create` command. Currently only capture to `Blob Storage` appears to be supported although the current documentation is a bit cryptic. 

**Describe the solution you'd like**
Since the `destination-name` (possible values: EventHubArchive.AzureBlockBlob, EventHubArchive.AzureDataLake) parameter already exists it would be great if generic capture parameters were added for easier use from the CLI:

- capture-account-name (replaces storage-account)
- capture-folder (or capture-container. Replaces blob-container)
- capture-name-format (replaces archive-name-format  for consistency)
- capture-destination-name (replaces destination-name for consistency)

Alternatively `Data Lake`-specific parameters could be added to solve the same problem.

**Describe alternatives you've considered**
Using an ARM template for deploying in this scenario, example [here](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-resource-manager-namespace-event-hub-enable-capture#resources-to-deploy-for-azure-data-lake-store-as-destination).

**Additional context**
`az cli` rocks.

**Comment by jfggdl** [comment]
@aj-nava, would you please check on this. I heard that there is already a PR to fix this issue.

**Comment by yonzhan** [comment]
What is the status of this issue ?

**Comment by yonzhan** [comment]
How is the status of this issue?

**Comment by MarkLeon** [comment]
Any update on this? Thanks.

**Comment by oliverholliday** [comment]
I don't understand why this was closed, it doesn't seem to have been implemented yet
