### ISSUE TITLE
Missing help for upload option

### ISSUE THREAD

**Issue by kwanlowe** [Azure/azure-cli#6854]
There is no help text for "--progress-callback".  How do the chunk-size and buffer-size affect the upload? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b124629b-d0c8-f761-ac49-4242475d4d2a
* Version Independent ID: 9e85d033-b96d-2b1d-3989-b2d339bffc3f
* Content: [az dls fs](https://docs.microsoft.com/en-us/cli/azure/dls/fs?view=azure-cli-latest#az-dls-fs-upload)
* Content Source: [src/command_modules/azure-cli-dls/azure/cli/command_modules/dls/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-dls/azure/cli/command_modules/dls/_help.py)
* Service: **datalake-store**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
@kwanlowe this looks like implementation fields from the SDK. This parameter would essentially do nothing and should be suppressed.

**Comment by akharit** [comment]
progress_callback is used in python programs and it doesn't make sense to expose it for a clli application. 

Is the help for chunk-size or buffer_size unclear?

**Comment by kwanlowe** [comment]
Apologies for delayed reply.  I believe this was opened because the 'az dls fs --help' listed a --progress-callback option without any other information. At the time I was trying to improve upload performance so was iterating through sizes of buffer and chunk. The progress-callback seemed it could have been useful in this exercise but was not documented.  Looking at a recent version of the CLI, it appears that the usage text has been removed so this is no longer relevant.  Thanks,
Kwan
