### ISSUE TITLE
Streamline and simplify profile structure

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#6855]
Many of these concepts are implemented, but in an inconsistent and potentially confusing way. With the requirements that have evolved, we should consider whether our implementation can be improved.

- [ ] Allow date-based comparison of dates and semver
- [ ] Make command appearance declarative (i.e. a module doesn't appear in the CLI unless it explicitly registered in a profile)
- [ ] Make API versioning calls work with non-multi-API versioned SDKs to minimize the amount of work that needs to be done when switching
- [ ] Allow individual resource types to version independently within an RP.

**Comment by yugangw-msft** [comment]
@limingu, please cross check.
