### ISSUE TITLE
[Keyvault] az keyvault secret show --query value does not return anything on Mac

### ISSUE THREAD

**Issue by vin-yu** [Azure/azure-cli#6858]
**Describe the bug**
Running  `az keyvault secret show -n <name> --vault-name <valuename> --query value` returns nothing on mac. 
_This works on windows._

**To Reproduce**
Run `az keyvault secret show -n <name> --vault-name <valuename> --query value` 

**Expected behavior**

**Environment summary**
Installed via Homebrew

Package Version:
azure-cli (2.0.42)
keyvault (2.2.0)

OS:
OSX 10.13.4

Terminal:
iTerm and default terminal

**Additional context**
![image](https://user-images.githubusercontent.com/7897410/43025011-00ba6ee0-8c25-11e8-9cb2-71cc94bfe107.png)

**Comment by tjprescott** [comment]
If you omit `--query` does it work?

**Comment by vin-yu** [comment]
tried omitting  --query. no results. 

thanks for responding

**Comment by jungopro** [comment]
Hello
It does work for me on mac
Running mojave and zsh shell (not bash)
az cli version 2.0.38

![screen shot 2018-10-08 at 14 49 03](https://user-images.githubusercontent.com/22839439/46607404-903f1e80-cb09-11e8-868f-115bb7395ea6.png)

I do have a different question though... how can I get just the value **data**, without the "Result" prefix?

Thank you
Omer

**Comment by jungopro** [comment]
Turns out I needed to add -o tsv and it got me what I needed 👍
