### ISSUE TITLE
[Generic Update] Accidentally setting a property on a list should have a better error message

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#686]
given object structure: 
A(obj)
-B(list)
--C(list[0])
---D(property)

use generic --set A.B.C.D=5

Expected: "Cannot set on list 'B', use --add instead or B[\<index\>]"
Actual: "available options: [\<C-obj-type\>]

**Comment by tjprescott** [comment]
So C is an entry in list B? You would need to use something like `--set A.B='[C=5]'`? Or `--add A.B C=5`?

**Comment by BurtBiel** [comment]
The correct usage is A.B[0].C=5.  I updated the original description to be a little clearer.  This is about the quality of the error message the user sees in this case, the scenario itself is supported.
