### ISSUE TITLE
az dls download doesn't work for multiple files in directory

### ISSUE THREAD

**Issue by egallo90** [Azure/azure-cli#6863]
Using the az dls download command to download all the content of a directory into Data Lake Store, all the hierarchy of the folder into the Data Lake has been downloaded, instead of only the files contained into the source folder, into the local folder where the command is executed, so ignoring the --destination-path option.

Machine OS: RHEL 7.5

Data Lake:
-test
  -folder1
      file1.txt
      file2.txt
  -folder2

Local path:
-localFolder1
-localFolder2

Command:
cd /localFolder1
 az dls fs download --source-path /test/folder1/* --destination-path "/localFolder2"

Result:
-localFolder1
  -test
      -folder1
          file1.txt
          file2.txt

**Comment by akharit** [comment]
@egallo90 Can you mention the datalake-store version you were using? The following command should work.
$ pip show azure-datalake-store

**Comment by akharit** [comment]
Please close this. I can't proceed without version information.
