### ISSUE TITLE
az ad sp create-for-rbac reports failure if ran from script

### ISSUE THREAD

**Issue by rkujawa** [Azure/azure-cli#6865]
**Describe the bug**
Trying to run:
```
az ad sp create-for-rbac --name myspname --role Contributor --password 'fsdfasda2314^' --scopes "/subscriptions/0f373767-f1db-40ea-9f7a-0394de33218b/resourceGroups/openshiftrg"
```

Works correctly if ran in an interactive terminal session, but results in the following failure if ran from inside of bash script:

Role assignment creation failed.

role assignment response headers: {'Content-Length': '156', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'x-ms-failure-cause': 'gateway', 'X-Content-Type-Options': 'nosniff', 'x-ms-request-id': 'b3eee8a1-f9db-4ed6-a0eb-5e3a02907951', 'Expires': '-1', 'x-ms-correlation-request-id': 'b3eee8a1-f9db-4ed6-a0eb-5e3a02907951', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Date': 'Mon, 23 Jul 2018 11:52:08 GMT', 'x-ms-routing-request-id': 'FRANCESOUTH:20180723T115209Z:b3eee8a1-f9db-4ed6-a0eb-5e3a02907951', 'Content-Type': 'application/json; charset=utf-8'}

The request did not have a provided subscription. All requests must have an associated subscription Id.

However, this error is misleading as checking out with `az ad sp list` shows a newly created service principal:
```
$ az ad sp list | jq -r '.[] | select(.displayName=="myspname")'
{
  "accountEnabled": true,
  "addIns": [],
  "alternativeNames": [],
  "appDisplayName": "myspname",
  "appId": "03aa9237-3244-4b5c-b350-54dee17dacc4",
  "appOwnerTenantId": "7f91886c-0b35-4aa8-bc51-35cf64a645f6",
  "appRoleAssignmentRequired": false,
  "appRoles": [],
  "deletionTimestamp": null,
  "displayName": "myspname",
  "errorUrl": null,
  "homepage": "http://myspname",
  "keyCredentials": [],
  "logoutUrl": null,
  "oauth2Permissions": [
    {
      "adminConsentDescription": "Allow the application to access myspname on behalf of the signed-in user.",
      "adminConsentDisplayName": "Access myspname",
      "id": "fd31f5f0-94e7-4819-97b2-86707a7fa2f3",
      "isEnabled": true,
      "type": "User",
      "userConsentDescription": "Allow the application to access myspname on your behalf.",
      "userConsentDisplayName": "Access myspname",
      "value": "user_impersonation"
    }
  ],
  "objectId": "bd6bbe92-ed04-4ecf-80ee-d66297b47cad",
  "objectType": "ServicePrincipal",
  "odata.type": "Microsoft.DirectoryServices.ServicePrincipal",
  "passwordCredentials": [],
  "preferredTokenSigningKeyThumbprint": null,
  "publisherName": "Default Directory",
  "replyUrls": [],
  "samlMetadataUrl": null,
  "servicePrincipalNames": [
    "http://myspname",
    "03aa9237-3244-4b5c-b350-54dee17dacc4"
  ],
  "servicePrincipalType": "Application",
  "signInAudience": "AzureADMyOrg",
  "tags": [],
  "tokenEncryptionKeyId": null
}
```

**To Reproduce**
Use this script:
```
#!/bin/bash

AZ_SP=myspname
AZ_RG=openshiftrg
AZ_SP_PASS=$1

if [ -z "$AZ_SP_PASS" ] ; then
	echo usage: $0 password
fi

cmd="az ad sp create-for-rbac --name ${AZ_SP} \
	--role Contributor --password ${AZ_SP_PASS} \
	--scopes $(az group show --name ${AZ_RG} --query id)"

echo attempting to run: $cmd
$cmd

```

**Expected behavior**

The `az ad sp create-for-rbac` behaves consistently if ran from command line and from bash scripts.

**Environment summary**

CentOS 7.5 fully updated as of today

az installed from official RPM repository:

azure-cli-2.0.42-1.el7.x86_64

**Additional context**

When trying to run from an interactive terminal session, it looks like the command is tried out a few times before succeeding, though it happens automatically:
```
$ az ad sp create-for-rbac --name myspname --role Contributor --password 'fsdfasda2314^' --scopes "/subscriptions/0f373767-f1db-40ea-9f7a-0394de33218b/resourceGroups/openshiftrg"
Retrying role assignment creation: 1/36
Retrying role assignment creation: 2/36
Retrying role assignment creation: 3/36
{
  "appId": "8eefe7a8-975a-4589-a8b4-aaa85d08d7a8",
  "displayName": "myspname",
  "name": "http://myspname",
  "password": "fsdfasda2314^",
  "tenant": "7f91886c-0b35-4aa8-bc51-35cf64a645f6"
}

```

**Comment by yugangw-msft** [comment]
@rkujawa, i apologize for being late, but please add `-o tsv` to the `$(az group show --name ${AZ_RG} --query id)"` which gets rid of the wrapping double quotes. During interactive environment, shell will unwrap them, but not in the shell script
I have verified the change works, hence I am closing this issue.
Again, sorry for letting this fall through the crack.
