### ISSUE TITLE
Can't use az login with password containing single quote and exclamation mark

### ISSUE THREAD

**Issue by mleneveut** [Azure/azure-cli#6867]
**Describe the bug**
When trying to login to Azure, I can't do 

> az login

 with my password.

**To Reproduce**
az login -u myuser@microsoft.com -p 'sd(!MH;du4

**Expected behavior**
Login success

**Actual behavior**
bash: syntax error near unexpected token `)'

**Environment summary**
Docker image microsoft/azure-cli

**Additional context**
I tried to escape the single quote (with double quotes -p "'sd(!MH;du4", with triple single quote -p '''sd(!MH;du4, with backslash -p \'sd(!MH;du4, etc...)

For the exclamation mark, I tried the backslash : -p "'sd(\!MH;du4"

but I got this error : Error validating credentials. Invalid username or password

Not sure if the issue is with the quotes or the exclamation mark.

**Comment by tjprescott** [comment]
https://www.gnu.org/software/bash/manual/html_node/Double-Quotes.html
So, for you password: `"'sd(\!MH;du4"`

**Comment by mleneveut** [comment]
@tjprescott Hi, thanks for your answer. But I actually already tried this, as stated in my initial report.

> az login -u myuser@microsoft.com -p "'sd(\\!MH;du4"

gives me this error : 

> Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS70002: Error validating credentials. AADSTS50126: Invalid username or password\r\nTrace ID: 60e93dd7-6d31-40d0-8e2a-9b9fbe203d00\r\nCorrelation ID: 7c0998d5-758c-4e45-9fa6-c234acf59e35\r\nTimestamp: 2018-07-24 08:02:00Z","error_codes":[70002,50126],"timestamp":"2018-07-24 08:02:00Z","trace_id":"60e93dd7-6d31-40d0-8e2a-9b9fbe203d00","correlation_id":"7c0998d5-758c-4e45-9fa6-c234acf59e35"}

If I try this password without the double quotes and backslash when prompted it works : 

> az login -u myuser@microsoft.com
Password : 'sd(!MH;du4

But I want to put the whole login with password argument in a script.

Thanks for your help.

**Comment by mleneveut** [comment]
ok I read in your link that when the bash history expansion is enabled (default), the backslash to escape the exclamation mark is not removed (strange...)

So I had to disable history expansion : 

> set +H

and the double quote string works : 

> az login -u myuser@microsoft.com -p "'sd(!MH;du4"

Thanks for your time :)
