### ISSUE TITLE
Acr build task missing --os parameter

### ISSUE THREAD

**Issue by artisticcheese** [Azure/azure-cli#6870]
Looks documentation out of date. 

```
usage: az acr build [-h] [--verbose] [--debug]
                    [--output {json,jsonc,table,tsv}] [--query JMESPATH]
                    --registry REGISTRY_NAME [--image IMAGE_NAMES]
                    [--resource-group RESOURCE_GROUP_NAME] [--timeout TIMEOUT]
                    [--build-arg BUILD_ARG]
                    [--secret-build-arg SECRET_BUILD_ARG]
                    [--file DOCKER_FILE_PATH] [--no-push] [--no-logs]
                    [--os {Windows,Linux}] [--subscription _SUBSCRIPTION]
                    &lt;SOURCE_LOCATION&gt;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c608162e-cf40-9d53-da4a-51f51a0311ea
* Version Independent ID: eccbb543-be68-7de2-d41d-abee55c81452
* Content: [az acr](https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest#az-acr-build)
* Content Source: [src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ehotinger** [comment]
@djyou / @ankurkhemani
