### ISSUE TITLE
webapp:az unable to update CORS setting

### ISSUE THREAD

**Issue by dtzar** [Azure/azure-cli#6884]
**Describe the bug**
The command listed in [the docs site to update CORS ](https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-rest-api#enable-cors) "succeeds" with no errors, but does not actually update the CORS setting.  You can see this reflected in the JSON output after the command completes it states the `properties.cors.allowedOrigins` value is `null`.

**To Reproduce**
Run this command where we replaced <app_name> with the base name listed for the azure website.

`az resource update --name web --resource-group myResourceGroup --namespace Microsoft.Web --resource-type config --parent sites/<app_name> --set properties.cors.allowedOrigins="['http://localhost:5000']" --api-version 2015-06-01`

I also tried this command using `*` instead of `http://localhost:5000` as well as removing the `--api-version 2015-06-01` from the end.

**Expected behavior**
The CORS setting for the domain takes effect on the App Service.

**Environment summary**
Azure App Service Standard Large plan.

**Comment by yugangw-msft** [comment]
This is fixed through #7038. Once released, you will be able to do it through commands like `az webapp cors add -g mygroup -n web --allowed-origins http://foobar.com`
