### ISSUE TITLE
PYTHON/GROOVY: Executing azure CLI Command with JSON - Parsing Issue?

### ISSUE THREAD

**Issue by dtissen** [Azure/azure-cli#6886]
**Describe the bug**
Currently I fail to run an azure CLI command from Groovy because of the JSON Part in the Command.

VM has reported a failure when processing extension 'CustomScript'. Error message: "Enable failed: failed to get configuration: error reading extension configuration: error parsing settings file: error parsing json: json: cannot unmarshal string into Go value of type map[string]interface {}

Please see: https://stackoverflow.com/questions/51424270/groovy-executing-azure-cli-command-with-json-parsing-issue

As from Groovy side: The command looks "fine"

It seems that (maybe) from azure cli side the parsing of the parameter is going wrong and should be changed to be useable from unix/linux

**To Reproduce**
GROOVY Script:

```
def process
            def cargs = [az, vm, extension, set, -g, demo, --vm-name, demo-cfg01, --name, CustomScript, --publisher, Microsoft.Azure.Extensions, --settings, '{"commandToExecute":"ls"}']
            process = (cargs).execute(null,null);

        }
```

The same call started from shell works.

**Expected behavior**
Same as from shell.

**Environment summary**
azure-cli (2.0.38)

acr (2.0.27)
acs (2.1.1)
advisor (0.5.1)
ams (0.1.1)
appservice (0.1.35)
backup (1.1.1)
batch (3.2.4)
batchai (0.3.0)
billing (0.1.8)
cdn (0.0.14)
cloud (2.0.14)
cognitiveservices (0.1.13)
command-modules-nspkg (2.0.1)
configure (2.0.16)
consumption (0.3.1)
container (0.1.24)
core (2.0.38)
cosmosdb (0.1.21)
dla (0.1.0)
dls (0.0.22)
dms (0.0.1)
eventgrid (0.1.12)
eventhubs (0.1.3)
extension (0.0.15)
feedback (2.1.2)
find (0.2.10)
interactive (0.3.23)
iot (0.1.21)
keyvault (2.0.22)
lab (0.0.22)
maps (0.2.0)
monitor (0.1.7)
network (2.1.4)
nspkg (3.0.2)
policyinsights (0.1.0)
profile (2.0.26)
rdbms (0.2.4)
redis (0.2.13)
reservations (0.2.0)
resource (2.0.31)
role (2.0.26)
servicebus (0.1.2)
servicefabric (0.0.12)
sql (2.0.27)
storage (2.0.35)
vm (2.0.34)

Python location '/opt/az/bin/python3'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.6.1 (default, Jun 14 2018, 21:24:04)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal

**Additional context**

**Comment by tjprescott** [comment]
What happens if you escape the internal double quotes?

**Comment by dtissen** [comment]
The Answer is:

DEBUG: msrest.http_logger : b'{\r\n  "startTime": "2018-08-07T08:13:02.3341422+00:00",\r\n  "endTime": "2018-08-07T08:13:43.0520614+00:00",\r\n  "status": "Failed",\r\n  "error": {\r\n    "code": "VMExtensionProvisioningError",\r\n    "message": "VM has reported a failure when processing extension \'CustomScript\'. Error message: \\"Enable failed: failed to get configuration: error reading extension configuration: error parsing settings file: error parsing json: json: cannot unmarshal string into Go value of type map[string]interface {}\\"."\r\n  },\r\n  "name": "e449a166-9548-46c2-aa28-a5358ac65b47"\r\n}'
DEBUG: msrest.exceptions : VM has reported a failure when processing extension 'CustomScript'. Error message: "Enable failed: failed to get configuration: error reading extension configuration: error parsing settings file: error parsing json: json: cannot unmarshal string into Go value of type map[string]interface {}".
ERROR: Deployment failed. Correlation ID: 9fc5bbe7-1cc0-4d95-9f48-980b64f9a47b. VM has reported a failure when processing extension 'CustomScript'. Error message: "Enable failed: failed to get configuration: error reading extension configuration: error parsing settings file: error parsing json: json: cannot unmarshal string into Go value of type map[string]interface {}".

**Comment by dtissen** [comment]
My current workaround is to write the json into a setting file and set the json file as parametervalue...

**Comment by yonzhan** [comment]
add to S165.

**Comment by jiasli** [comment]
I am not a Groovy expert. I followed [this answer](https://stackoverflow.com/a/25292664/2199657) and tried these 2 scripts with `az --debug` which tells you the actual arguments Azure CLI received. On Linux both work for me:

t1.groovy
```groovy
def proc = """az {"name":"value"} --debug""".execute();
proc.waitForProcessOutput(System.out, System.err);
```

```
$ groovy t1.groovy
DEBUG: Command arguments: ['{"name":"value"}', '--debug']
```

t2.groovy
```groovy
def cmd_args = ['az', '{"name":"value"}', '--debug']
proc = (cmd_args).execute(null,null);
proc.waitForProcessOutput(System.out, System.err);
```

```
$ groovy t2.groovy
DEBUG: Command arguments: ['{"name":"value"}', '--debug']
```

On Windows, since az is a bat file, `"` needs to be escaped as `\"` for cmd.exe and `\` needs to escaped again for Groovy itself as `\\`. 

t1.groovy
```groovy
def proc = """az.bat {\\"name\\":\\"value\\"} --debug""".execute();
proc.waitForProcessOutput(System.out, System.err);
```

```
>groovy t1.groovy
DEBUG: Command arguments: ['{"name":"value"}', '--debug']
```

t2.groovy
```groovy
def cmd_args = ['az.bat', '{\\"name\\":\\"value\\"}', '--debug']
proc = (cmd_args).execute(null,null);
proc.waitForProcessOutput(System.out, System.err);
```

```
>groovy t2.groovy
DEBUG: Command arguments: ['{"name":"value"}', '--debug']
```


Please let me know if these solutions work for you.
