### ISSUE TITLE
CosmosDB: Missing option for storage capacity or incomplete documentation

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-cli#6887]
With [az cosmosdb collection create](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/collection?view=azure-cli-latest#az-cosmosdb-collection-create) there is no way to set the storage capacity (in the Azure Portal either "fixed (10GB)" or "unlimited"). Since the command supports `--partition-key-path` which is only useable for unlimited (=partitioned) collections, I assume that the CLI always creates "unlimited" collections. If that's the case, then it should be documented. Currently it is quite confusing.

**Comment by shurd** [comment]
Hi @letmaik thank you for identifying this lack in documentation. At this point, we have deprecated the fixed storage option, so only "unlimited" collections can be created.
