### ISSUE TITLE
Cannot Set New Subscription from CLI 

### ISSUE THREAD

**Issue by dhselman** [Azure/azure-cli#6895]
**Describe the bug**
After a role on a new subscription has been added, the subscription does not appear in the list of accounts (az account list) and you can not set the subscription as well. Instead, you have to re-authenticate the tool through microsoft.com/devicelogin before the new subscription will appear. 

**To Reproduce**
Authenticate the command line for your account, create a new subscription through the portal and add yourself to the subscription, then run az account list and the new subscription will not show. Alternatively you can run az account set [subscription]. 

**Expected behavior**
Once a new subscription is added, users ought to be able to view or set the subscription without having to authenticate the azure cli. 

**Environment summary**
azure-cli (2.0.23) on Windows 10

**Additional context**
Re-authenticating the tool allows the user to set their subscription, but it would be more ideal if the CLI could pull the list directly from Azure rather than populating from a known list at the time of last authentication.

**Comment by yugangw-msft** [comment]
Can you try out  `az account list --refresh`?

**Comment by marstr** [comment]
Closing as stale. This behavior feels fairly expected to me too. If someone wildly disagrees or has a use-case that requires that `--refresh` is implicit, please speak-up here and we'll take another look.
