### ISSUE TITLE
ACR Build doesn't properly parse .dockerignore

### ISSUE THREAD

**Issue by hassanselim0** [Azure/azure-cli#6896]
**Describe the bug**
I had a problem where `az acr build` would always send an empty context (75 bytes, and the `.tar.gz` file in `%TEMP%` was empty).
Turns out my `.dockerignore` was the problem, I've attached it to this issue so you can take a look at it, but it basically ignores everything `**` then un-ignores a few things.
[dockerignore.zip](https://github.com/Azure/azure-cli/files/2233024/dockerignore.zip)

**To Reproduce**
- Create a `.dockerignore` file that starts with `**` then add a few `!` lines to un-ignore the folders you want to add to the context.
- Run `az acr build`
- Notice that it sends a 75 byte context and it will fail to find your `Dockerfile`

**Expected behavior**
I expect it to parse the `.dockerignore` just like regular docker, and thus only send the folders I need while ignoring everything else.

**Environment summary**
azure-cli (2.0.42)
acr (2.1.0)
Docker Version: 18.06.0-ce
OS: Windows 10 Version 1803
Shell Type: Powershell and CMD

**Comment by ehotinger** [comment]
@northtyphoon

**Comment by yugangw-msft** [comment]
closing
