### ISSUE TITLE
Command for firewall rules

### ISSUE THREAD

**Issue by mariojacobo** [Azure/azure-cli#6905]
Hi there, 

Is there any command to add firewall rules ? 

Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecb66426-9b0f-be54-5530-0673e6821f39
* Version Independent ID: 3d89a838-9a95-3cfe-ea58-7d7484e94956
* Content: [az redis](https://docs.microsoft.com/en-us/cli/azure/redis?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/_help.py)
* Service: **redis-cache**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by mariojacobo** [comment]
@GuyPaddock - reopened the issue. I closed it because we don't use Azure Redis anymore.

**Comment by tjprescott** [comment]
Closing this in favor of #8334.
