### ISSUE TITLE
Typo in examples

### ISSUE THREAD

**Issue by jlian** [Azure/azure-cli#6907]
In the example it says to use `az iot hub device-identity create -n [IoTHub Name] -d [Device ID] -am x509_thumbprint –valid-days 10` but really it should be `az iot hub device-identity create -n [IoTHub Name] -d [Device ID] -am x509_thumbprint –-valid-days 10` with two `-` before `valid-days`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62c92565-2490-7306-fa08-b16aa2a402a6
* Version Independent ID: 73f40753-0f05-7e45-ca7d-f0a9d2a276ce
* Content: [az iot hub device-identity](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/iot/hub/device-identity?view=azure-cli-latest#ext-azure-cli-iot-ext-az-iot-hub-device-identity-create)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/hub/device-identity.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/hub/device-identity.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by williexu** [comment]
This should be part of https://github.com/Azure/azure-cli-extensions
Also, this was recently fixed.
@jlian please check again.
