### ISSUE TITLE
This is not clear

### ISSUE THREAD

**Issue by ncacace** [Azure/azure-cli#6915]
"az webapp source-control config-local-git \
                            -g MyResourceGroup -n MyUniqueApp
                        
                        git remote add azure \
                            https://&lt;deploy_user_name&gt;@MyUniqueApp.scm.azurewebsites.net/MyUniqueApp.git"

Is that backslash supposed to mean that it should be one line?
Like this...
"az webapp source-control config-local-git -g MyResourceGroup -n MyUniqueApp"
and then on the next line in the console this....
"git remote add azure https://&lt;deploy_user_name&gt;@MyUniqueApp.scm.azurewebsites.net/MyUniqueApp.git"
????

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b238907f-0676-8e20-66ac-89a542aa8c20
* Version Independent ID: 60659c33-bfea-eecb-6681-9240191820be
* Content: [az webapp deployment source](https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/source?view=azure-cli-latest#az-webapp-deployment-source-config-local-git)
* Content Source: [latest/docs-ref-autogen/webapp/deployment/source.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/webapp/deployment/source.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ncacace** [comment]
"az webapp source-control config-local-git -g MyResourceGroup -n MyUniqueApp"
I tried this and I get an error
"az webapp: 'source-control' is not in the 'az webapp' command group. See 'az webapp --help'."

You know what I think? - I think You have the engineers who produce your software write your documentation...and then they test their own documentation - And I can't even begin to explain how flawed that system would be.

**Comment by williexu** [comment]
@ncacace it seems like our documentation examples are outdated. We will do our best to keep them up-to-date and relevent.

To answer your question, yes, the `\` indicates a continuation of the same command.
