### ISSUE TITLE
az batch task create --json-file should support task collections

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-cli#6916]
Version: 2.0.41

The docs of [`az batch task create`](https://docs.microsoft.com/en-us/cli/azure/batch/task?view=azure-cli-latest#az-batch-task-create) say for `--json-file`:

> The file containing the task(s) to create in JSON format, if this parameter is specified, all other parameters are ignored.

Since this is written such that it can be plural, meaning multiple tasks, I assumed it would support the ["Task - Add Collection"](https://docs.microsoft.com/en-us/rest/api/batchservice/task/addcollection) schema as well, however this seems not to be the case as it errors out with:
```
Parameter 'TaskAddParameter.id' can not be None.
```

It would be great if this could be supported as it can be very convenient.

**Comment by bgklein** [comment]
Could you post an example body of what you are submitting? The Batch CLI should handle collections formatted as https://raw.githubusercontent.com/Azure/azure-docs-cli-python-samples/master/batch/render-scene/json/myrendertask_multi.json . We can look into accepting TaskAddCollection json as well.

**Comment by letmaik** [comment]
I see, that would be fine. Can you document that somewhere?

**Comment by bgklein** [comment]
Yes, I will add it this to my TODO's for the coming week, and contact our doc's liaison for a possible update for our documents to add some version of this explanation in addition to example links.
