### ISSUE TITLE
Why is --account-endpoint required in az batch if --account-name is given?

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-cli#6917]
The command lines with `az batch` often get quite cumbersome because `--account-endpoint` has to be specified. Why is this necessary if `--acount-name` is given together with a selected subscription? Then  it should be unambiguous and it would be possible to infer it, right?

**Comment by tjprescott** [comment]
@annatisch can you comment?

**Comment by annatisch** [comment]
If I recall correctly this is to do with the specific shared access key auth used by Batch - The client requires the account endpoint to instantiate, whereas the shared key credentials requires only the Batch account name.
Though it's probable that in many cases one of these two values could probably be constructed internally - at least as the default behavior - then make adding the account name/endpoint optional if needed.....

Adding @xingwu1 to see if he has a better recollection about why both are needed.

**Comment by xingwu1** [comment]
@tjprescott  this is by azure batch design, the account-endpoint include the region information which is must for azure batch. Azure batch doesn't have global master server, so we have to use full url container region information to direct the user request to regional server.

**Comment by letmaik** [comment]
Does that mean I can create multiple batch accounts named "foo" in different regions?

**Comment by xingwu1** [comment]
@letmaik It was designed to do this way. However, right now, we only implemented the same account can only used for single region. :)
