### ISSUE TITLE
[functionapp create] storage account shouldn't have to be in same resource group

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-cli#6918]
The root cause is that the same `resource_group_name` parameter is reused for the storage account *and* the functionapp within the command definition, but they should be independent:

* https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py#L1677

* https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py#L1691

**Describe the bug**
`az functionapp create` requires the storage account and the functionapp to be in the same resource group, but it should be possible to assign an existing storage account from a different resource group.

It's possible to assign an existing storage account by setting the `AzureWebJobsStorage` env var directly within App Service, so this should also be possible via CLI.

Could the storage account parameter take a full ID with group name and use that?

**To Reproduce**
Create a storage account in one resource group then try to create an App Service plan and functionapp in another resource group, a la the following:

```bash
stor=$(az storage account create -g storage-group -n accountname ...)
plan=$(az appservice plan create --is-linux -g functions-group ...)
az functionapp create -g functions-group --plan $plan --storage-account $stor ...

# expected: success
# get: The Resource 'Microsoft.Storage/storageAccounts/accountname' under resource group 'functions-group' was not found.
```

**Expected behavior**
Successfully create functionapp in its resource group using storage account in other resource group.

**Environment summary**
Up to date via apt on Ubuntu 18.04.

**Comment by yugangw-msft** [comment]
Cross resource group storage account id is supported, but there is a code bug that prevents it from working right.

**Comment by yugangw-msft** [comment]
@panchagnula , i will take this one unless you are interested

**Comment by tonyschollum** [comment]
This issue still seems to exist for RM Storage Accounts.

E.g. the below command is trying to use a RM Storage Account in the staging resource group, however the error suggests it is trying to find the storage account in the function app group regardless of the resourceId:

az functionapp create --name functionapptest --storage-account "/subscriptions/xxxx/resourceGroups/staging/providers/Microsoft.Storage/storageAccounts/stagingtestaccount" --consumption-plan-location australiaeast --resource-group functions-uat1
The Resource 'Microsoft.Storage/storageAccounts/stagingtestaccount' under resource group 'functions-uat1' was not found.

The same command trying to use a classic storage account in the staging resource group does show it is looking in the staging group:
az functionapp create --name functionapptest --storage-account "/subscriptions/xxxx/resourceGroups/staging/providers/Microsoft.ClassicStorage/storageAccounts/stagingstorerlfiles" --consumption-plan-location australiaeast --resource-group functions-uat1
The Resource 'Microsoft.Storage/storageAccounts/stagingstorerlfiles' under resource group 'staging' was not found.
