### ISSUE TITLE
[ACR / Build] Refactor context upload size.

### ISSUE THREAD

**Issue by ehotinger** [Azure/azure-cli#6925]
**Describe the bug**

- The current logic in `_upload_source_code` won't handle sizes of 1 TB+. 

**Expected behavior**

- [ ] The method for calculating size is extracted into its own helper method.
- [ ] Aforementioned method supports 1 TB+, even though we won't accept contexts of this size.
- [ ] Unit tests are added for this method.

**Comment by sajayantony** [comment]
@northtyphoon  - who do you want to reassign this to?
