### ISSUE TITLE
`az group delete` stalls on active `az disk grant-access` token

### ISSUE THREAD

**Issue by iyerusad** [Azure/azure-cli#6927]
**Describe the bug**
If an Azure resource group has a VM that has an active disk access SAS token (generated by using `az disk grant-access`), `az group delete` won't be able to delete the resource group. It will spin/attempt indefinitely (or seemingly indefinitely).

Contrast this with a resource group that has active SAS tokens out for things like blobs/files - those don't appear to block a resource group from being deleted

**To Reproduce**

1. Create resource group
1. Create VM, one that has managed disks
1. Grant access to VM disk using `az disk grant-access`, with at least couple hours of time.
1. Attempt to delete the resource group. Observe how this operation will not complete, spinning endlessly.
1. Remove the disk access token (either in Portal or using `az disk revoke-access`). Observe how the resource group deletes itself shortly after.

**Expected behavior**

`az group delete` either deletes the resource group or errors out with approriate message (e.g. `ERROR: Existing disk access found, remove before attempting to delete this resource group`). 

This behavior would be consistent with how Locks work in Azure - If a lock exists the command errors out due to the existing lock.

**Environment summary**
Install Method: shell.azure.com

**Comment by yugangw-msft** [comment]
Reported to Compute RP.
//CC @singhkays

**Comment by yugangw-msft** [comment]
CRP does return a valid error but it was ignored by ARM. It is an ARM service error.
`There is an active shared access signature outstanding for disk <name>. Call EndGetAccess before attaching or deleting the disk.`

**Comment by chidmdxx** [comment]
Made a change ARM side to acknowledge the error code returned by CRP, and fail the delete operation early

**Comment by achandmsft** [comment]
Closing per @chidmdxx comment as this is now fixed in the ARM service.
