### ISSUE TITLE
az cli 2.0.42 dumps kubectl.exe x64 binary to x86 Program Files (x86) folder

### ISSUE THREAD

**Issue by pradm** [Azure/azure-cli#6928]
**Describe the bug**
https://docs.microsoft.com/en-us/cli/azure/acs/kubernetes?view=azure-cli-latest#az-acs-kubernetes-install-cli States --install-location default value: C:\Program Files\kubectl.exe , but here its dumping it to a x86 folder location. The version of AZ CLI is azure-cli-2.0.42

PS E:\Projects> az acs kubernetes install-cli
Downloading client to C:\Program Files (x86)\kubectl.exe from https://storage.googleapis.com/kubernetes-release/release/v1.11.1/bin/windows/amd64/kubectl.exe
Please ensure that C:\Program Files (x86) is in your search PATH, so the `kubectl.exe` command can be found.
PS E:\Projects > set path=%path%;"C:\Program Files (x86)\"

C:\windows\system32>dumpbin /HEADERS "C:\Program Files (x86)\kubectl.exe"
Microsoft (R) COFF/PE Dumper Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.

Dump of file C:\Program Files (x86)\kubectl.exe

PE signature found

File Type: EXECUTABLE IMAGE

FILE HEADER VALUES
            8664 machine (x64)
               C number of sections
               0 time date stamp
         305F600 file pointer to symbol table
            DD2F number of symbols
              F0 size of optional header
             223 characteristics
                   Relocations stripped
                   Executable
                   Application can handle large (>2GB) addresses
                  Debug information stripped

**To Reproduce**
az acs kubernetes install-cli

**Expected behavior**
it should dump the x64 directory of program files as documented in BOL and as specified in issue https://github.com/Azure/azure-cli/issues/1871

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by yugangw-msft** [comment]
Cc @mboersma 
I can't reproduce this. Based on reading the code, the command is supposed to copy `https://storage.googleapis.com/kubernetes-release/release/v1.11.1/bin/windows/amd64/kubectl.exe` to  `C:\Program Files\kubectl.exe`
@pradm, what you get if you run the command of `echo %ProgramFiles%` in the same console when you ran the CLI, do you get `C:\Program Files (x86)`?

**Comment by pradm** [comment]
The command was executed in powershell window, if i execute the requested command in that window it does not echo out the actual path, following are the details

PS E:\Projects> echo %ProgramFiles%
%ProgramFiles%

**Comment by yugangw-msft** [comment]
Ah, I think I understand the issue now. You probably run the CLI inside a x86 powershell window where both the `ProgramFiles` and `ProgramFiles(x86)` get mapped to `C:\Program Files (x86)`
You can cross check with the cmdlet of `Get-ChildItem Env:`
Maybe use non x86 powershell as a workaround for now?

**Comment by pradm** [comment]
Nope i see that ProgramFiles & ProgramFiles(X86) are mapped separately, Following are the output of the command requested.

PS E:\Projects> Get-ChildItem Env:

Name                           Value
----                           -----
ALLUSERSPROFILE                C:\ProgramData
APPDATA                        C:\Users\pradm\AppData\Roaming
CommonProgramFiles             C:\Program Files\Common Files
CommonProgramFiles(x86)        C:\Program Files (x86)\Common Files
CommonProgramW6432             C:\Program Files\Common Files
COMPUTERNAME                   PRADMLINWIN
ComSpec                        C:\windows\system32\cmd.exe
HOMEDRIVE                      C:
HOMEPATH                       \Users\pradm
LOCALAPPDATA                   C:\Users\pradm\AppData\Local
LOGONSERVER                    \\BLR-FE-DC-04
NUMBER_OF_PROCESSORS           12
OneDrive                       C:\Users\pradm\OneDrive - Microsoft
OS                             Windows_NT
Path                           C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\Sy...
PATHEXT                        .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
PROCESSOR_ARCHITECTURE         AMD64
PROCESSOR_IDENTIFIER           Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
PROCESSOR_LEVEL                6
PROCESSOR_REVISION             3f02
ProgramData                    C:\ProgramData
ProgramFiles                   C:\Program Files
ProgramFiles(x86)              C:\Program Files (x86)
ProgramW6432                   C:\Program Files
PSModulePath                   C:\Users\pradm\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\PowerShell\Modules\
PUBLIC                         C:\Users\Public
SystemDrive                    C:
SystemRoot                     C:\windows
SYSTEMTYPE                     other
TEMP                           C:\Users\pradm\AppData\Local\Temp
TMP                            C:\Users\pradm\AppData\Local\Temp
UATDATA                        C:\Windows\CCM\UATData\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77
USERDNSDOMAIN                  FAREAST.CORP.MICROSOFT.COM
USERDOMAIN                     FAREAST
USERDOMAIN_ROAMINGPROFILE      FAREAST
USERNAME                       pradm
USERPROFILE                    C:\Users\pradm
VS140COMNTOOLS                 C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
VSSDK140Install                C:\Program Files (x86)\Microsoft Visual Studio 14.0\VSSDK\
windir                         C:\windows

**Comment by yugangw-msft** [comment]
And in right this posh window, running "az acs kubernetes install-cli" will download to `C:\Program Files (x86)`?

**Comment by yugangw-msft** [comment]
I understand now, it is CLI's problem because we are embedding a x86 version of python in the windows installer and that guy will see `ProgramFiles` as the x86 one. 
I didn't reproduce this in my machine because my dev environment was built by 64 bits of python.

**Comment by pradm** [comment]
Thank you for the update and the details. Appreciate you looking into this issue.
