### ISSUE TITLE
Add Interface Endpoints support

### ISSUE THREAD

**Issue by rupalivohra** [Azure/azure-cli#6940]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
We would like CLI support for Creating, Updating, Getting, and Deleting Interface Endpoints.

**Describe alternatives you've considered**
N/A

**Additional context**
I will provide the Swagger for this resource next week.

**Comment by tjprescott** [comment]
Moving to Sprint 45 due to no swagger.

**Comment by tjprescott** [comment]
Merged.
