### ISSUE TITLE
Add Subnet Purpose and Subnet Delegation support in CLI

### ISSUE THREAD

**Issue by rupalivohra** [Azure/azure-cli#6941]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like CLI support for two new properties that are being added to the Subnet resource.

**Describe alternatives you've considered**
N/A

**Additional context**
I will share the Swagger for the new properties next week.

**Comment by tjprescott** [comment]
Moving to sprint 45 due to no swagger.
