### ISSUE TITLE
Powershell "az sql db export" doesn't tolerate passwords with special characters

### ISSUE THREAD

**Issue by dkempner** [Azure/azure-cli#6943]
**Describe the bug**
Attempting to use a password with a special character throws an unexpected error.

**To Reproduce**

1. Open Powershell
2. Run the below command noting the special characters in the password parameter:

`az sql db export -u "MyUsername" -p 'aaa-a,aaa^>?a}a' -n "MyDb" -g "MyResourceGroup" -s "MyServer" --storage-key "MyStorageKey" --storage-key-type "StorageAccessKey" --storage-uri "uri"`

3. Note that you get the error message 

`The filename, directory name, or volume label syntax is incorrect.`

**Expected behavior**
Run the db export 

**Environment summary**
PowerShell on Windows 10
az --version: 2.0.42

**Additional context**

- Doesn't work if you convert -p to a SecureString
- The script works in the Azure Portal Shell, but doesn't work in my local PowerShell env.

**Comment by troydai** [comment]
could you try replace single quote with double quote?

**Comment by troydai** [comment]
@dkempner this is about the PowerShell terminal instead of the CLI. We can't process the data unless the shell sends us the correct value.

**Comment by troydai** [comment]
Please note, The Azure Portal Shell is bash based.

**Comment by dkempner** [comment]
@troydai oh I didn't realize it was bash. I'll rewrite my script, thanks!

**Comment by woowil** [comment]
I am receiving `az sql db export` and `az sql db import` error only on Windows. The commandworks from Linux (WSL) using PowerShell or from Azure Shell

I can't figure this out. 
Help, please

**Versions**
azure-cli:  2.30.0
Powershell 7.2.0, Core, Microsoft Windows 10.0.19043, Win32NT
azcopy: 10.13.0

```powershell
az sql db export `
    --server $SQLServerName `
    --name "$DatabaseName" `
    --admin-user "$SQLAdminUser" `
    --admin-password "$SQLAdminPass" `
    --storage-key "$StorageAccessKey" `
    --storage-key-type "StorageAccessKey" `
    --storage-uri "$StorageTypeUrl" `
    --auth-type SQL `
    --resource-group "$ResourceGroupSQL" `
    --subscription $SubscriptionSQL `
    --verbose
```
Errors: _The filename, directory name, or volume label syntax is incorrect._

**Comment by sirsnork** [comment]
If anyone runs into this in future here's the solution

escape the characters in the password that are reserved in PS. Easiest way to do this is with a .replace and also put escaped double quotes around the variable. My working solution looks like this
`
`"$Password.Replace("$","`$")`"

`
