### ISSUE TITLE
"az role assignment list" Name field is either blank or repeat of appID

### ISSUE THREAD

**Issue by flac013** [Azure/azure-cli#6945]
after running the above command I get no names from the query. If the name is filled out, then it is just a repeat of the appID. Example results:

Principal ID repeated
```
{
    "additionalProperties": {},
    "canDelegate": null,
    "id": "sensitive info",
    "name": "aa70e1e3-4000-42f7-ab5a-ebdbe493e45b",
    "principalId": "a363b2ec-05ae-4d1b-aed6-c591075842e6",
    "principalName": "a363b2ec-05ae-4d1b-aed6-c591075842e6",
    "roleDefinitionId": "sensitive info",
    "roleDefinitionName": "Contributor",
    "scope": "censored for privacy",
    "type": "Microsoft.Authorization/roleAssignments"
  }
```

Empty field
```
{
    "additionalProperties": {},
    "canDelegate": null,
    "id": "sensitive info",
    "name": "aa70e1e3-4000-42f7-ab5a-ebdbe493e45b",
    "principalId": "a363b2ec-05ae-4d1b-aed6-c591075842e6",
    "principalName": "",
    "roleDefinitionId": "sensitive info",
    "roleDefinitionName": "Contributor",
    "scope": "censored for privacy",
    "type": "Microsoft.Authorization/roleAssignments"
  }
```

I am looking for something along these lines:
```
{
    "additionalProperties": {},
    "canDelegate": null,
    "id": "sensitive info",
    "name": "aa70e1e3-4000-42f7-ab5a-ebdbe493e45b",
    "principalId": "a363b2ec-05ae-4d1b-aed6-c591075842e6",
    "principalName": "thisismyAppRegName",
    "roleDefinitionId": "sensitive info",
    "roleDefinitionName": "Contributor",
    "scope": "censored for privacy",
    "type": "Microsoft.Authorization/roleAssignments"
  }
```

---

### Environment summary

Azure cloud shell

azure-cli (2.0.43)

acr (2.1.2)
acs (2.2.2)
advisor (0.6.0)
ams (0.2.1)
appservice (0.2.1)
backup (1.2.0)
batch (3.3.1)
batchai (0.4.0)
billing (0.2.0)
cdn (0.1.0)
cloud (2.1.0)
cognitiveservices (0.2.0)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.2)
core (2.0.43)
cosmosdb (0.2.0)
dla (0.2.0)
dls (0.1.0)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.1)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.27)
iot (0.2.0)
keyvault (2.2.1)
lab (0.1.0)
maps (0.3.1)
monitor (0.2.1)
network (2.2.2)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.0)
redis (0.3.0)
reservations (0.3.1)
resource (2.1.1)
role (2.1.2)
search (0.1.0)
servicebus (0.2.1)
servicefabric (0.1.0)
sql (2.1.1)
storage (2.1.1)
vm (2.2.0)

Python location '/opt/az/bin/python3'
Extensions directory '/home/andres/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Jul 26 2018, 17:46:59)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal

```
```

**Comment by yugangw-msft** [comment]
@flac013, can you cross check whether the service principal still exists in the tenant by running  `az ad sp show --id a363b2ec-05ae-4d1b-aed6-c591075842e6`?

**Comment by flac013** [comment]
Hey @yugangw-msft,

Thanks for getting back to me. I ran that command and I got the following:

`{
  "accountEnabled": true,
  "addIns": [],
  "alternativeNames": [],
  "appDisplayName": "testappreg",
  "appId": "26324734-cbb1-44c8-9b8b-c882be13859b",
  "appOwnerTenantId": "b39138ca-3cee-4b4a-a4d6-cd83d9dd62f0",
  "appRoleAssignmentRequired": false,
  "appRoles": [],
  "deletionTimestamp": null,
  "displayName": "testappreg",
  "errorUrl": null,
  "homepage": "http://testappreg",
  "keyCredentials": [],
  "logoutUrl": null,
  "oauth2Permissions": [
    {
      "adminConsentDescription": "Allow the application to access testappreg on behalf of the signed-in user.",
      "adminConsentDisplayName": "Access testappreg",
      "id": "e7209e38-ac0a-497e-8d18-1775a0d19053",
      "isEnabled": true,
      "type": "User",
      "userConsentDescription": "Allow the application to access testappreg on your behalf.",
      "userConsentDisplayName": "Access testappreg",
      "value": "user_impersonation"
    }
  ],
  "objectId": "a363b2ec-05ae-4d1b-aed6-c591075842e6",
  "objectType": "ServicePrincipal",
  "odata.metadata": "https://graph.windows.net/b39138ca-3cee-4b4a-a4d6-cd83d9dd62f0/$metadata#directoryObjects/Microsoft.DirectoryServices.ServicePrincipal/@Element",
  "odata.type": "Microsoft.DirectoryServices.ServicePrincipal",
  "passwordCredentials": [],
  "preferredTokenSigningKeyThumbprint": null,
  "publisherName": "VMware, Inc.",
  "replyUrls": [],
  "samlMetadataUrl": null,
  "servicePrincipalNames": [
    "http://testappreg",
    "26324734-cbb1-44c8-9b8b-c882be13859b"
  ],
  "servicePrincipalType": "Application",
  "signInAudience": null,
  "tags": [],
  "tokenEncryptionKeyId": null
}`

This is what I have on azure portal itself. None of the names are populating for any of these accounts:
![image](https://user-images.githubusercontent.com/11082883/43600560-e8710ce8-9658-11e8-949f-1cc093b4eed2.png)

**Comment by yugangw-msft** [comment]
This is serious. @bganapa, this is broken by your Stack profile change  #6781. 
Since this impacts majority users, I will handle the fix today. I hope this won't incur asks for hot fix release.
//CC @johanste

**Comment by bganapa** [comment]
I am looking at the changes, apologies. I must have overlooked.. cc: @knithinc

**Comment by bganapa** [comment]
just went through my PR again looking for any other issues, I don't find any. I think this slipped through as the tests were not looking for the property

**Comment by flac013** [comment]
any ETA on the fix? I would like to be able to use this feature within the coming week. I understand if it's busy 'round your parts, I just want to ensure that it's being worked on as this issue is marked as closed. Just attempted the command again and I got exact same results.

**Comment by yugangw-msft** [comment]
A few ways here for you to try the dev drops:
   https://github.com/Azure/azure-cli#docker

We will have a release on Aug 14

**Comment by flac013** [comment]
Same problem persists on the cloud shell. Role names do not populate. I essentially just want to be able to view the information listed in the web GUI's Azure>Subscriptions>IAM page and only the names assigned to them. I need this functionality fixed if possible.

azure-cli (2.0.45)

acr (2.1.4)
acs (2.3.2)
advisor (0.6.0)
ams (0.2.3)
appservice (0.2.3)
backup (1.2.1)
batch (3.3.3)
batchai (0.4.2)
billing (0.2.0)
botservice (0.1.0)
cdn (0.1.1)
cloud (2.1.0)
cognitiveservices (0.2.1)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.3)
core (2.0.45)
cosmosdb (0.2.1)
dla (0.2.2)
dls (0.1.1)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.3)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.28)
iot (0.3.1)
iotcentral (0.1.1)
keyvault (2.2.2)
lab (0.1.1)
maps (0.3.2)
monitor (0.2.3)
network (2.2.4)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.1)
redis (0.3.2)
relay (0.1.1)
reservations (0.3.2)
resource (2.1.3)
role (2.1.4)
search (0.1.1)
servicebus (0.2.2)
servicefabric (0.1.2)
sql (2.1.3)
storage (2.2.1)
telemetry (1.0.0)
vm (2.2.2)

**Comment by abhijeetdtu** [comment]
Has this been resolved ? I am still facing the same issue with  azure-cli (2.0.58)

**Comment by yugangw-msft** [comment]
Please move to newer version like 2.0.61

**Comment by abhijeetdtu** [comment]
Still the same issue- switched to 2.0.61

![image](https://user-images.githubusercontent.com/6872080/55428463-c5737900-554e-11e9-9459-c4d4c1986de4.png)

az role assignment list `
    --include-groups `
    --include-inherited `
    --scope "removed ----"
    --query "[].{prName:principalName , name:roleDefinitionName}" 
`
With newer version unable to see the principalName property in the response objects
![image](https://user-images.githubusercontent.com/6872080/55428372-8f35f980-554e-11e9-93d4-6f1a083d8525.png)

**Comment by Slowdive-Aideron** [comment]
Problem still persists in v.2.1.0

azure-cli                                           2.1.0
command-modules-nspkg              2.0.3
core                                                  2.1.0
nspkg                                               3.0.4
telemetry                                         1.0.4

  {
    "name": "Reader",
    "prName": null
  },
with --query "[].{prName:principalName , name:roleDefinitionName}"
