### ISSUE TITLE
List-* naming inconsistencies

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-cli#695]
`az account list-location` ,- singular
`az vm list-ip-addresses` <- plural

**Comment by tjprescott** [comment]
Closing duplicate issue.

**Comment by derekbekoe** [comment]
@tjprescott Can you link to the duplicated issue?

**Comment by tjprescott** [comment]
#694

**Comment by ahmetalpbalkan** [comment]
hah I wonder how this happened.
