### ISSUE TITLE
[ACR / Build] Expose --no-cache for quick build

### ISSUE THREAD

**Issue by ehotinger** [Azure/azure-cli#6952]
Feature request:

Create a new CLI parameter, `--no-cache` and add this when creating a new `QuickBuildRequest` so that we can ignore all layer caching when running a quick build.

**Comment by sajayantony** [comment]
Please assign this to @northtyphoon

**Comment by yugangw-msft** [comment]
Looks like https://github.com/Azure/azure-cli/pull/7255 has handled this
@northtyphoon, please reactivate otherwise.
