### ISSUE TITLE
 Recover a managed disk data encrypted

### ISSUE THREAD

**Issue by lpxavi** [Azure/azure-cli#6954]
Hi,

I have encrypted a managed disk with 'az vm encryption' and I have lost the vm.

I need a way to recover a managed disk data encrypted by lost VM.

Is it possible ?

Tks 

Xavier

**Comment by yugangw-msft** [comment]
@vermashi, any chance? Please help!

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
