### ISSUE TITLE
az webapp deployment:Typical documentation

### ISSUE THREAD

**Issue by spcmastertim01** [Azure/azure-cli#6956]
Short doc with little useful information.  Go look at ANY other service and compare documents.  This is useless

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26f21f9c-7323-9caa-deeb-00e714a8d0ca
* Version Independent ID: c6d509be-937f-e228-17a7-570d275b6fa4
* Content: [az webapp deployment](https://docs.microsoft.com/en-us/cli/azure/webapp/deployment?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/deployment.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/webapp/deployment.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by panchagnula** [comment]
@spcmastertim01 thanks for the issue, we are striving to improve our documentation - in this case is there is any specific examples you can share on the parts that need improvements? either a specific deployment command or any thing else? thank you.

**Comment by panchagnula** [comment]
Closing this  due to lack of response on this issue.
