### ISSUE TITLE
"Provisioning State:  Failed"  after creating deployment environment in Azure ML 

### ISSUE THREAD

**Issue by charlesfarrington** [Azure/azure-cli#6964]
The deployment environment 'Provisioning State' keeps appearing as 'Failed' after attempting to create a deployment environment from the CLI (accessed through Azure ML Workbench).

This happens in the 3rd part of [this](https://docs.microsoft.com/en-us/azure/machine-learning/desktop-workbench/tutorial-classifying-iris-part-3#prepare-to-operationalize-locally-for-development-and-testing-your-service) tutorial.

The command line code used to create the new environment is:
`az ml env setup -n <new deployment environment name> --location <e.g. eastus2>`

The code used to check the environment is:
`az ml env show -n <deployment environment name> -g <existing resource group name>`

The error message in the Azure Portal Activity Logs reads: 

> Error code
> InvalidTemplate
> Message
> Deployment template validation failed: 'The template parameters 'apiVersion' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time. The only supported parameters for this template are 'location, acrStorageName, acrName, storageAccountName, appInsightsAppId, appInsightsLocation, applicationType'. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'.

**Comment by kthejoker** [comment]
Received the same error, here's the debug output specifically related to the creation of the environment:

```
Getting management service client client_type=MachineLearningComputeManagementClient
adal-python : a03c6119-70d3-4137-9e2b-c4f3784c2a8f - Authority:Performing instance discovery: ...
adal-python : a03c6119-70d3-4137-9e2b-c4f3784c2a8f - Authority:Performing static instance discovery
adal-python : a03c6119-70d3-4137-9e2b-c4f3784c2a8f - Authority:Authority validated via static instance discovery
adal-python : a03c6119-70d3-4137-9e2b-c4f3784c2a8f - TokenRequest:Getting token from cache with refresh if necessary.
adal-python : a03c6119-70d3-4137-9e2b-c4f3784c2a8f - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python : a03c6119-70d3-4137-9e2b-c4f3784c2a8f - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python : a03c6119-70d3-4137-9e2b-c4f3784c2a8f - CacheDriver:Found 5 potential entries.
adal-python : a03c6119-70d3-4137-9e2b-c4f3784c2a8f - CacheDriver:Resource specific token found.
adal-python : a03c6119-70d3-4137-9e2b-c4f3784c2a8f - CacheDriver:Returning token from cache lookup, (TOKENS REMOVED)
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring proxies: ''
msrest.pipeline : Evaluate proxies against ENV settings: True
msrest.pipeline : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
requests.packages.urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com
requests.packages.urllib3.connectionpool : "PUT /subscriptions/d87d4530-ce4e-4d84-b997-7a78d01e2906/resourceGroups/testenv12rg/providers/Microsoft.MachineLearningCompute/operationalizationClusters/testenv12?api-version=2017-08-01-preview HTTP/1.1" 201 1217
Resource creation submitted successfully.
To see more information for your environment, run:
  az ml env show -g testenv12rg -n testenv12
You can set the new environment as your target context using:
  az ml env set -g testenv12rg -n testenv12
Application event 'Application.TransformResults' with event data {'event_data': {'result': None}}
Application event 'Application.FilterResults' with event data {'event_data': {'result': None}}
```

And then the same error in my portal. Is there a way to debug/step through the Python when running Azure CLI commands? Sorry, not that well versed in CLI dev.

**Comment by v-strudm-msft** [comment]
We see this was posted over two years ago, but is was never addressed so are closing it. Our apologies. Should this still be an issue, please open a new issue and we will respond on a timely basis. Thank you.
