### ISSUE TITLE
Publish or expose port

### ISSUE THREAD

**Issue by makoit** [Azure/azure-cli#6968]
I am using azure container instances.
Is there a opportunity to bind ports of the container to other ports? 

Something like:

`$ docker run -p 80:8080 ubuntu`

Thanks for help.

**Comment by samkreter** [comment]
@makoit  we currently do not support port mapping in ACI. The ports that are exposed need to be direct mappings to the container's ports.

**Comment by samkreter** [comment]
@makoit  One other note, this is a commonly asked feature. You can upvote it here: https://feedback.azure.com/forums/602224-azure-container-instances
