### ISSUE TITLE
compute: "Microsoft.Compute/skus" should accept server filter

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#6970]
This api returns boat load of information including configurations across all compute resources with 3MB+ payload returned. Because of the volume, the information is hard to digest by CLI users. 
Considering the importance of the api (the only place people can query zone list and vm size availability)  I suggest, service end should expose server side filter including "resource type" and "vm size" so to retrieve  better data with shorter latency.

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
