### ISSUE TITLE
Listing existing Azure Images

### ISSUE THREAD

**Issue by henriquebrisola** [Azure/azure-cli#6972]
How can I list all Images that already exist in Azure, e.g. Win2012R2Datacenter, UbuntuLTS...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42c81f4c-ac29-2f6e-96f2-b6fba3ef3098
* Version Independent ID: 2a24cd5b-8798-a175-5bde-7d2850bf9015
* Content: [az image](https://docs.microsoft.com/en-us/cli/azure/image?view=azure-cli-latest#az-image-show)
* Content Source: [latest/docs-ref-autogen/image.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/image.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
`az vm image -h`

**Comment by henriquebrisola** [comment]
Thanks but this isn't correct, the correct answer would be `az vm image list` and the result is below.
But I think the list should be much greater.

Offer | Publisher | Sku | Urn | UrnAlias | Version
-- | -- | -- | -- | -- | --
------------- | ---------------------- | ------------------ | -------------------------------------------------------------- | ------------------- | ---------
CentOS | OpenLogic | 7.3 | OpenLogic:CentOS:7.3:latest | CentOS | latest
CoreOS | CoreOS | Stable | CoreOS:CoreOS:Stable:latest | CoreOS | latest
Debian | credativ | 8 | credativ:Debian:8:latest | Debian | latest
openSUSE-Leap | SUSE | 42.3 | SUSE:openSUSE-Leap:42.3:latest | openSUSE-Leap | latest
RHEL | RedHat | 7.3 | RedHat:RHEL:7.3:latest | RHEL | latest
SLES | SUSE | 12-SP2 | SUSE:SLES:12-SP2:latest | SLES | latest
UbuntuServer | Canonical | 16.04-LTS | Canonical:UbuntuServer:16.04-LTS:latest | UbuntuLTS | latest
WindowsServer | MicrosoftWindowsServer | 2016-Datacenter | MicrosoftWindowsServer:WindowsServer:2016-Datacenter:latest | Win2016Datacenter | latest
WindowsServer | MicrosoftWindowsServer | 2012-R2-Datacenter | MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest | Win2012R2Datacenter | latest
WindowsServer | MicrosoftWindowsServer | 2012-Datacenter | MicrosoftWindowsServer:WindowsServer:2012-Datacenter:latest | Win2012Datacenter | latest
WindowsServer | MicrosoftWindowsServer | 2008-R2-SP1 | MicrosoftWindowsServer:WindowsServer:2008-R2-SP1:latest | Win2008R2SP1 | latest

**Comment by tjprescott** [comment]
Hi @henriquebrisola when you use `az vm image list` you are seeing a cached list of the most common images. If you want to see all available images, add the `--all` flag. This is a slow operation.

**Comment by yugangw-msft** [comment]
On top of @tjprescott's suggestion, you can still use `--publisher`, `--offer` filters to narrow down the query result which should get things faster. CLI uses case insensitive partial string match, so you don't worry about typing into the exact names.

**Comment by tjprescott** [comment]
It is all documented here:
https://docs.microsoft.com/en-us/cli/azure/vm/image?view=azure-cli-latest#az-vm-image-list
