### ISSUE TITLE
Az Vm Image command missing

### ISSUE THREAD

**Issue by henriquebrisola** [Azure/azure-cli#6976]
The command `az vm image` shows &gt;Information on available virtual machine images.
ps. do not mistake with `az image` which shows only info about custom images.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 152b549b-d4b3-13e5-081c-c604b6e4d89e
* Version Independent ID: 3f79be78-ce75-ad31-304b-bad7d475ec9e
* Content: [az vm](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Closing as this is a comment rather than an issue.

**Comment by henriquebrisola** [comment]
@tjprescott  This is not just comment, the `az vm image` command is missing from the documentation.

**Comment by tjprescott** [comment]
`az vm image` is a command group, not a command. It is documented here:
https://docs.microsoft.com/en-us/cli/azure/vm/image?view=azure-cli-latest
