### ISSUE TITLE
"az aks install-connector" needs tab-completion helpers

### ISSUE THREAD

**Issue by mboersma** [Azure/azure-cli#6978]
From Azure/AKS#513.

**Describe the bug**

`az install-connector --resource-group $AZ_RG --name` doesn't give you a prompt for the list of AKS clusters in that resource group (or the list of all clusters)
`az install-connector --l` doesn't give --location as a prompt.

**Comment by seanmck** [comment]
Closing since `install-connector` was a temporary solution that will disappear once virtual nodes are ubiquitous.
