### ISSUE TITLE
Log Analytics Alert via CLI

### ISSUE THREAD

**Issue by abhiCR7** [Azure/azure-cli#6987]
**Is your feature request related to a problem? Please describe.**
We have App.Insights alert management from az-cli currently.
**Describe the solution you'd like**
It would be great to have the same functionality here so people can have better control over all the monitoring aspects from one space.

**Describe alternatives you've considered**
I tried to explore node.js sdk, but couldn't find anything relative to log analytics alerts management.

**Additional context**

**Comment by tjprescott** [comment]
Hi @abhiCR7  there is a new CLI extension that may be what you're looking for:
`az extension add -n log-analytics`

**Comment by tjprescott** [comment]
https://github.com/Azure/azure-cli-extensions/tree/master/src/log-analytics

**Comment by tjprescott** [comment]
If this does not have the capabilities you are looking for, please open a feature request issue in the CLI extensions repo.
