### ISSUE TITLE
acs: --ssh-key-file

### ISSUE THREAD

**Issue by pradm** [Azure/azure-cli#6994]
Is this input parameter for --ssh-key-file be the public key or private key. It looks like it needs the private key always, if we provide the public key as input it reports "raise SSHException('not a valid ' + tag + ' private key file')"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d382080c-52ae-ea51-9ace-8c86289c6a60
* Version Independent ID: 0f810340-879d-6f24-03d0-c89e93e30348
* Content: [az acs kubernetes](https://docs.microsoft.com/en-us/cli/azure/acs/kubernetes?view=azure-cli-latest#get-credentials)
* Content Source: [src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
closing as `az acs` is deprecating
