### ISSUE TITLE
`az role definition create --role-definition` should accept an array of objects

### ISSUE THREAD

**Issue by brianbaso** [Azure/azure-cli#6995]
I have a json file with over 20 role definition templates. When I run

`az role definition create --role-definition <file-path>`

I get an error

`Invalid role defintion. A valid dictionary JSON representation is expected.`

I think it would be a nice feature if this cli command could accept an array of role definitions. What do you guys think?

**Comment by yugangw-msft** [comment]
Let us live with this still we have enough user voices. On top of Travis's comment, consistency is also a factor that we don't have other commands which would create multiple entities at one shot.
