### ISSUE TITLE
VM create: enable accelerated networking by default on all VM sizes 

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#6999]
NRP service is ready and with the confidence this will work.

**Comment by yugangw-msft** [comment]
Close and rather wait for API support #6440

**Comment by tjprescott** [comment]
@yugangw-msft you mean close this issue?

**Comment by yugangw-msft** [comment]
@tjprescott, yes, the decision is to wait for API instead of tweaking CLI further. For switching to API, we already have #6440 tracking that

**Comment by yugangw-msft** [comment]
closing, thanks.
