### ISSUE TITLE
Supported Versions for --orchestrator-version

### ISSUE THREAD

**Issue by pradm** [Azure/azure-cli#7006]
How do we find what is the supported versions that can be passed as input parameter to --orchestrator-version parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09c0cfaa-d590-f927-15a1-37f9f4e293bb
* Version Independent ID: 32b3d811-99dc-6f4c-d15b-ccf6e9f51142
* Content: [az acs](https://docs.microsoft.com/en-us/cli/azure/acs?view=azure-cli-latest#az-acs-create)
* Content Source: [src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
closing as `az acs` is deprecating
