### ISSUE TITLE
Az webapp create usage error

### ISSUE THREAD

**Issue by elsesiy** [Azure/azure-cli#7013]
Hi there, following the provided documentation on `az webapp create` I'm not able to create a webapp without specifying any of:
--runtime
--deployment-container-image-name
--multicontainer-config-type TYPE
--multicontainer-config-file FILE

Running `az webapp create -g anygrouppreviouslycreated -n test -p anyplanpreviouscreated` leads to the following output:

`usage error: --runtime | --deployment-container-image-name | --multicontainer-config-type TYPE --multicontainer-config-file FILE`

I suspect it has to do with the `--is-linux` flag while creating the service plan.

It's also very disappointing that using `--docker-custom-image-name` is not available which would allow me to do the webapp creation and image instantiation via ACR in one command. With the current issue, I have to basically deploy any available image from docker hub and replace it right after with `az webapp container set` to reference the actual container to be used from ACR.

Version info:
azure-cli (2.0.43)

Related: 
https://github.com/MicrosoftDocs/azure-docs/issues/6286
https://github.com/MicrosoftDocs/azure-docs/issues/11145

Thanks!

**Comment by elsesiy** [comment]
@rijdz No, unfortunately not as this is clearly an issue with the CLI. I worked around it for now by running the commonly used [hello-world](https://hub.docker.com/_/hello-world/) image which immediately exits. I then use `az webapp config container set` to replace it with my custom docker image from ACR.

**Comment by jeromechrist** [comment]
same issue here with the latest az cli 2.0.4.9, workaround by @elsesiy is working thanksfully for a demo app

**Comment by jemag** [comment]
same issue here, while exactly following this tutorial : https://azure.microsoft.com/en-ca/resources/videos/deploy-a-spring-boot-app-to-azure/

**Comment by panchagnula** [comment]
Unfortunately for Linux apps these are required for the Docker container apps we have plans to support an extra parameter - being tracked by this https://github.com/Azure/azure-cli/issues/7261

**Comment by elsesiy** [comment]
@panchagnula The issue you're referencing describe the exact same issue but was filed a month later. Not sure what's the point in closing this one?

**Comment by ewekansige** [comment]
Last time I had this issue, it was because I was specifying the wrong resource group.
az webapp create --resource-group $resourceGroup --plan $hostingPlan --name $applicationName --deployment-container-image-name $dockerCustomImageName

Make sure the the resource group is the one in which your service plan is created.

**Comment by bellwether-thomas** [comment]
This is still not fixed years later? Wow.

**Comment by ilayn** [comment]
I received the same error and no details even with `--verbose` switch.

**Comment by bravegeek** [comment]
I created an appservice plan with the `--is-linux` flag and experienced the above error.
My fix was to specify the `--runtime`.

Example: 
`az webapp create --name yourwebapp --plan yourappserviceplan --resource-group yourresourcegroup --runtime "DOTNETCORE|3.1"`

To get the available runtimes: `az webapp list-runtimes --linux`

**Comment by hctru68** [comment]
Thanks, brave geek. It's working fine as your guide.

**Comment by ca0v** [comment]
Does this mean "--html" is not possible when deploying to Linux?  When I switched to a node runtime (which I do not need) I get this new error, 

_Deployment Failed. deployer = Push-Deployer deploymentPath = ZipDeploy. Extract zip. Remote build._

I have not had any success resolving this new error.

**Comment by JianerCong** [comment]
> Does this mean "--html" is not possible when deploying to Linux? When I switched to a node runtime (which I do not need) I get this new error,
> 
> _Deployment Failed. deployer = Push-Deployer deploymentPath = ZipDeploy. Extract zip. Remote build._
> 
> I have not had any success resolving this new error.

Hi..... my `az webapp up --help` said:
```
 Current support includes Node, Python, .NET Core and ASP.NET. Node, Python apps are created as Linux apps. .Net Core, ASP.NET, and static HTML apps are created as Windows apps.
```
