### ISSUE TITLE
Issue in adding tags to azure SQL database

### ISSUE THREAD

**Issue by MarshallKiruba** [Azure/azure-cli#7017]
While trying to add tags to the database using both portal and azure cli. For some databases tags are getting momentarily added. But after a short while the newly added tags got vanished. Please help us in this issue.

**Comment by aamalvea** [comment]
We're sorry that we weren't able to get back to you in a timely manner. If you are still experiencing this issue, please file a new issue and we will get back to you in 48 hours. For these types of issues, please provide the full trace.
