### ISSUE TITLE
ad sp create: print client_id instead of SP URI/name?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-cli#703]
cc @colemickens can weigh in.

I feel like most apps that run with Service Principal Accounts require inputs

- `client_id`
- `client_secret`

See the following output:

- it lists SP name, which is a URI (not clear if this can be used as `client_id` to the user)
    - there is an `--assignee` argument but not sure if that's objectID or SP ID.
- it lists the password (calls it “secret”), so I guess that one is fine

```
az ad sp create-for-rbac
WARNING: Service principal has been configured with name: 'http://azure-cli-2016-08-15-18-34-00', secret: '7dd33413-ade4-xxxx-xxxx-xxxxxxxxxxxx'
WARNING: Useful commands to manage azure:
WARNING: Assign a role:
WARNING:     az role assignment create --assignee b3c7a3d1-841c-4c80-b042-0c37a95c3423 --role Contributor
WARNING: Log in:
WARNING:     az login --service-principal -u http://azure-cli-2016-08-15-18-34-00 -p 7dd33413-ade4-xxxx-xxxx-xxxxxxxxxxxx --tenant xxxxxxx-xxxxx-xxxxx-xxxx-xxxxxx
WARNING: Reset credentials:
WARNING:     az ad sp reset-sp-credentials --name http://azure-cli-2016-08-15-18-34-00
WARNING: Revoke:
WARNING:     az ad sp delete --id http://azure-cli-2016-08-15-18-34-00
WARNING:     az ad app delete --id http://azure-cli-2016-08-15-18-34-00
```

**Comment by colemickens** [comment]
I'm indifferent about the human readable text output

I think the text output should include mention that the appUrl is usable as client_secret.

I also think it also might be worth discussing what the `--json` output format for this command will look like.

**Comment by ahmetalpbalkan** [comment]
> I also think it also might be worth discussing what the --json output format for this command will look like.

@colemickens probably the standard format for sp accounts file that AAD was supposed to come up with for quite a while? –so that people can just redirect the output to a file and pass it to applications.

**Comment by colemickens** [comment]
Something like that yes. The file we were asking AAD for was the "cache" representation for more-or-less, the `access_token`. For this case, we need different fields to represent the credentials for the service principal. I suppose a single format could sort of encompass both, but I'm not sure it should or needs to.

**Comment by ahmetalpbalkan** [comment]
I think at least we could add some lines to the beginning:

```
az ad sp create-for-rbac
WARNING: Service principal has been configured.
WARNING: Name:                         http://azure-cli-2016-08-15-18-34-00
WARNING: ID (client_id):               xxxxxxx-xxxxx-xxxxx-xxxx-xxxxxx
WARNING: Password (client_secret):     xxxxxxx-xxxxx-xxxxx-xxxx-xxxxxx
WARNING: 
WARNING: Useful commands to manage azure:
WARNING: Assign a role:
WARNING:     az role assignment create --assignee b3c7a3d1-841c-4c80-b042-0c37a95c3423 --role Contributor
[...]
```

**Comment by yugangw-msft** [comment]
I am fine with the suggestion towards the text change. One comment is we probably don't need to display the guid based id.  Some contexts:
  1. The client identifier of a service principal really comes from the `servicePrincipalNames` collection of the service principal graph object. This collection contains at least the associated application's identifier uri(that `http://azure-cli-2016-08-15-18-34-00`), and the guid based id.  Both can represent the service principal. 
  2. The uri style is much easier to remember than the guid. Also the `create-for-rbac` let you pick one you like. 
  3. The `role assignment create` has been simplified. Its `assignee` can take both object id or the uri. 

Based on that, to get things simpler, I can update the command output to use the uri in the assignment creating command, and get the app guid out of the way completely.
