### ISSUE TITLE
typos in az batchai cluster autoscale example

### ISSUE THREAD

**Issue by YoshiakiOi** [Azure/azure-cli#7031]
az batchai auto-scale -g MyResourceGroup -w MyWorkspace -n MyCluster --min 0 --max 10 
--&gt; az batchai cluster auto-scale -g MyResourceGroup -w MyWorkspace -n MyCluster --min 0 --max 10
* cluster is missed in the example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5ad5bd9-6bc2-6489-0f95-226c8d017e3b
* Version Independent ID: 7772f177-332f-db67-3dc6-72795aaf5583
* Content: [az batchai cluster](https://docs.microsoft.com/en-us/cli/azure/batchai/cluster?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/_help.py)
* Service: **batch-ai**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by YoshiakiOi** [comment]
Not fixed yet. Could you please re-open and fix the command?

**Comment by williexu** [comment]
@YoshiakiOi it has been fixed: https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-batchai/azure/cli/command_modules/batchai/_help.py#L107-L113

Our documentation will be updated with our next release, v2.0.45
