### ISSUE TITLE
Incorrect config value set

### ISSUE THREAD

**Issue by jobanputra** [Azure/azure-cli#7032]
I'm running az cli commands to add config values in a windows batch file. In general the config values set are correct, except the one listed below:
**Input**
```
az functionapp config appsettings set --subscription %subscriptionId% ^
--resource-group %resourceGroupName% ^
--name %applicationName% ^
--settings CslJobsEndpoint=https://doesnotmatter/Default.GetDisabledJobs()
```

**Output**
Notice the missing `)` and the python related message. 
```
....other values omitted
  {
    "name": "FUNCTIONS_EXTENSION_VERSION",
    "slotSetting": false,
    "value": "~1"
  },
  {
    "name": "CslJobsEndpoint",
    "slotSetting": false,
    "value": "https://doesnotmatter/Default.GetDisabledJobs("
  }
]
Failed to load python executable.
```

I am targetting V2 (snippet from .csproj listed below)
```xml
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AzureFunctionsVersion>V2</AzureFunctionsVersion>
  </PropertyGroup>
```
 az cli version: azure-cli (2.0.43)

**Comment by jobanputra** [comment]
Checking in to see if you were able to repro this issue?

**Comment by tjprescott** [comment]
@panchagnula for comment

**Comment by panchagnula** [comment]
@ahmelsayed did the default runtime version for Function app change or need to be updated?

**Comment by ahmelsayed** [comment]
I think the bug report is about 

```
--settings CslJobsEndpoint=https://doesnotmatter/Default.GetDisabledJobs()
```

resulting in an app setting 

```
CslJobsEndpoint = https://doesnotmatter/Default.GetDisabledJobs(
```

`GetDisabledJobs(` vs `GetDisabledJobs()`

looks to me like an issue with the `az.cmd` command

```batch
@IF EXIST "%~dp0\..\python.exe" (
  "%~dp0\..\python.exe" -IBm azure.cli %*
) ELSE (
  echo Failed to load python executable.
  exit /b 1
)
```

Where `%*` is getting expanded and causing the `)` at the end of the command to be interrupted as a closing for the IF statement?


**Workaround:**

```
--settings CslJobsEndpoint="https://doesnotmatter/Default.GetDisabledJobs()"
```

**Comment by ahmelsayed** [comment]
btw, from a `cmd.exe` window try 

```
C:\Users\ahmels>az test()
az: 'test(' is not in the 'az' command group. See 'az --help'.

C:\Users\ahmels>echo Failed to load python executable.
Failed to load python executable.

C:\Users\ahmels>exit /b 1
```

**Comment by tjprescott** [comment]
Yes, you should quote the setting. Since this is a quoting/escaping issue, I'm going to close this.

**Comment by jobanputra** [comment]
Thank you for the work around.

**Comment by tjprescott** [comment]
@jobanputra note that this isn't really a workaround. It's how you have to quote/escape your input to be processed correctly by your shell.

**Comment by bigdatamoore** [comment]
Just spent about 2 hours trying to get this to work and finally found this github issue.  I think this might be worth putting something in the docs mentioning that you need to quote your setting values.  The case I had was related to using keyvault backed app settings for function apps as outlined here: https://azure.microsoft.com/en-us/blog/simplifying-security-for-serverless-and-web-apps-with-azure-functions-and-app-service/

**Comment by mreyeros** [comment]
I am in the same scenario as @bigdatamoore, trying to save a keyvault backed setting for a functionapp and no matter what I try I cannot seem to get the quoting correct and continue to receive the above mentioned error. @bigdatamoore can you share your final script solution as an example for correctly quoting these types of settings.

**Comment by jpovey** [comment]
> I am in the same scenario as @bigdatamoore, trying to save a keyvault backed setting for a functionapp and no matter what I try I cannot seem to get the quoting correct and continue to receive the above mentioned error. @bigdatamoore can you share your final script solution as an example for correctly quoting these types of settings.
> 
> UPDATE:
> I was able to finally figure out the correct quoting syntax. I will post my example below for those that may run into a similar issue:
> 
> `$blobStorageSASConfig = '"@Microsoft.KeyVault(SecretUri={0}secrets/{1}/)"' -f $keyvaultUri, $global:blobStorageAccountSASSecretName
> 
> az functionapp config appsettings set --name $functionAppName `--resource-group $resourceGroup`
> --settings UIBlobStorageHost=$blobStorageEndpoint UIBlobStorageSAS=$blobStorageSASConfig`

Thanks @mreyeros, this is the correct solution to escape the secret. It is unusual to require single and double quotes and is not clear in the docs https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references

As above this works
`az functionapp config appsettings set --name func-name --resource-group func-rg --settings SettingName='"@Microsoft.KeyVault(SecretUri=https://keyvaultname.vault.azure.net/secrets/SecretName/SecretVersion)"'`
