### ISSUE TITLE
`az mysql server create` does not infer --location, prints stack trace

### ISSUE THREAD

**Issue by sptramer** [Azure/azure-cli#7035]
**Describe the bug**

`az mysql server create` produces a stack trace when `--location` is missing, and additionally, does not use the resource group's location by default.

**To Reproduce**

Run any valid `az mysql server create` command without the `--location` argument, such as:

```
az mysql server create -g test --name bugtest --admin-user admin--admin-password admin --sku-name GP_Gen4_2 --version 5.7
```

**Expected behavior**

1. No stack trace is produced, even if `--location` is required
2. `--location` should be inferred from the resource group location, as it is for other Azure resources.

**Environment summary**

WSL (Ubuntu 16.04 LTS/Windows 10 Build 17134)
Installed via `apt-get`
`azure-cli 2.0.43`
`sql (2.1.1)`

**Comment by ajlam** [comment]
Updated in PR #8607. 

@bsiegel, please help close this issue.

**Comment by bsiegel** [comment]
Closing this issue as completed. @ajlam can you please comment to inform the customer what version of the CLI will contain this fix? Thanks!
