### ISSUE TITLE
[Output] Support default table format & a custom query that applies

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#704]
@johanste pointed out the following issue: `az vm list -o table --query "[?location=='westus']"` gives the standard error:
`Table output unavailable. Change output type with --output or use the --query option to specify an appropriate query. Use --debug for more info.`

Currently the default table format is only used if --query is not specified. However, if --query is used to specify a filter, but not a projection (as in this case) it would be reasonable for the user to expect that the default projection would be used.

We should look at whether it would be technically feasible/reasonable to apply the result of --query first and then apply the table format query. In this case, you would get the default table output, but filtered on location. Ideally, we would still like the ability to specify the desired projection (like you currently have to).

**Comment by mayurid** [comment]
moving to sprint 2.

**Comment by derekbekoe** [comment]
Table format will be revisited as if command packages have to work across multiple API versions, we can use the current strategy for table format of specifying a static JMESPath query for each command.

A possible approach would be to make table format support complex objects. Alternatively, table format can dynamically try and pull out simple fields.
