### ISSUE TITLE
az storage endpoint not available in AzureGovernment 

### ISSUE THREAD

**Issue by rohrerb** [Azure/azure-cli#7047]
**Describe the bug**
Error that endpoint is not valid when listing storage accounts. 

> The resource type 'storageAccounts' could not be found in the namespace 'Microsoft.Storage' for api version '2018-03-01-preview'. The supported api-versions are '2017-10-01,2017-06-01,2016-12-01,2016-07-01,2016-05-01,2016-01-01,2015-06-15,2015-05-01-preview'.

**To Reproduce**
1. switch to azure government
`az cloud set --name AzureUSGovernment`

2. Run az storage list
`az storage account list --query "[?contains(name,'xwz')].name" --output tsv`

**Expected behavior**
No Error and result be returned.

**Environment summary**
azure-cli (2.0.44)

**Additional context**

1. Debug Info

> msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
> msrest.pipeline : Configuring proxies: ''
> msrest.pipeline : Evaluate proxies against ENV settings: True
> msrest.pipeline : Configuring redirects: allow=True, max=30
> msrest.pipeline : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
> urllib3.connectionpool : Starting new HTTPS connection (1): management.usgovcloudapi.net
> urllib3.connectionpool : https://management.usgovcloudapi.net:443 "GET /subscriptions/xxxx-xxxx-xxxx-xxxx-xxxx/providers/Microsoft.Storage/storageAccounts?api-version=2018-03-01-preview HTTP/1.1" 404 312
> msrest.http_logger : Request URL: 'https://management.usgovcloudapi.net/subscriptions/xxxx-xxxx-xxxx-xxxx-xxxx/providers/Microsoft.Storage/storageAccounts?api-version=2018-03-01-preview'
> msrest.http_logger : Request method: 'GET'
> msrest.http_logger : Request headers:
> msrest.http_logger :     'User-Agent': 'python/3.7.0 (Darwin-17.7.0-x86_64-i386-64bit) requests/2.18.4 msrest/0.5.4 msrest_azure/0.4.34 azure-mgmt-storage/2.0.0rc4 Azure-SDK-For-Python AZURECLI/2.0.44'
> msrest.http_logger :     'Accept-Encoding': 'gzip, deflate'
> msrest.http_logger :     'Accept': 'application/json'
> msrest.http_logger :     'Connection': 'keep-alive'
> msrest.http_logger :     'Authorization': '*****'
> msrest.http_logger :     'x-ms-client-request-id': '2868b160-xxxx-xxxx-b42f-8c8590503e61'
> msrest.http_logger :     'CommandName': 'storage account list'
> msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
> msrest.http_logger :     'accept-language': 'en-US'
> msrest.http_logger : Request body:
> msrest.http_logger : None
> msrest.http_logger : Response status: 404
> msrest.http_logger : Response headers:
> msrest.http_logger :     'Cache-Control': 'no-cache'
> msrest.http_logger :     'Pragma': 'no-cache'
> msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
> msrest.http_logger :     'Expires': '-1'
> msrest.http_logger :     'x-ms-failure-cause': 'gateway'
> msrest.http_logger :     'x-ms-request-id': 'be47b2f4-b92a-xxxx-xxxx-74f0a13a7e8d'
> msrest.http_logger :     'x-ms-correlation-request-id': 'be47b2f4-xxxx-xxxx-9d13-74f0a13a7e8d'
> msrest.http_logger :     'x-ms-routing-request-id': 'USGOVVIRGINIA:20180814T232415Z:be47b2f4-b92a-496f-9d13-74f0a13a7e8d'
> msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
> msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
> msrest.http_logger :     'Date': 'Tue, 14 Aug 2018 23:24:15 GMT'
> msrest.http_logger :     'Content-Length': '312'
> msrest.http_logger : Response content:
> msrest.http_logger : b'{"error":{"code":"InvalidResourceType","message":"The resource type \'storageAccounts\' could not be found in the namespace \'Microsoft.Storage\' for api version \'2018-03-01-preview\'. The supported api-versions are \'2017-10-01,2017-06-01,2016-12-01,2016-07-01,2016-05-01,2016-01-01,2015-06-15,2015-05-01-preview\'."}}'
> msrest.exceptions : The resource type 'storageAccounts' could not be found in the namespace 'Microsoft.Storage' for api version '2018-03-01-preview'. The supported api-versions are '2017-10-01,2017-06-01,2016-12-01,2016-07-01,2016-05-01,2016-01-01,2015-06-15,2015-05-01-preview'.
> The resource type 'storageAccounts' could not be found in the namespace 'Microsoft.Storage' for api version '2018-03-01-preview'. The supported api-versions are '2017-10-01,2017-06-01,2016-12-01,2016-07-01,2016-05-01,2016-01-01,2015-06-15,2015-05-01-preview'.
> telemetry.save : Save telemetry record of length 2548 in cache
> telemetry.check : Negative: The /Users/x/.azure/telemetry.txt was modified at 2018-08-14 19:21:28.091964, which in less than 600.000000 s

**Comment by ernstae** [comment]
Version 2.0.43 were making the requests with API version 2017-1001 via `?api-version=2017-10-01` whereas the latest update 2.0.44 switches that to ```/providers/Microsoft.Storage/storageAccounts?api-version=2018-03-01-preview```

**Comment by ernstae** [comment]
This seems to be the breaking commit:  e55b849c3342fdf8fe4a3958ea86aea315a25bbd

**Comment by tjprescott** [comment]
@williexu please take a look

**Comment by ernstae** [comment]
@williexu - I've already downgraded (`brew switch azure-cli 2.0.43` for those landing on this issue and using homebrew on mac)

**Comment by rohrerb** [comment]
@tjprescott - FYI

This has been fixed.  Everyone should be able to update CLI version and target USGov.
