### ISSUE TITLE
[Output] Table format does not work consistently with show commands

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#705]
The following:
`az vm show --ids {id} -o table` works but `az vm show --ids [multiple ids] -o table` produces a table with one row full of None values. The reason is because the `simple_output_query` is expecting a single object, not an array of objects. Simply appending '[]' to the query will cause the multi-id form to succeed but the single object form to fail.

One solution would be to check the results format and wrap it in a list if it is an object. In this way the simple output query would always be written as for a list. @derekbekoe, @johanste

**Comment by mayurid** [comment]
Moving to Sprint 2.
