### ISSUE TITLE
Camel case error makes starting endpoints impossible

### ISSUE THREAD

**Issue by maltefiala** [Azure/azure-cli#7052]
```bash 
az ams streaming endpoint list [...]
>   "id": "[...]/Microsoft.Media/mediaservices/mediaaccount/streamingendpoints/default"

az ams streaming endpoint start [...]
>   (ResourceNotFound) The Resource 'Microsoft.Media/mediaservices/mediaaccount/streamingEndpoints/default' under resource group '...' was not found.
```

Camel casing of "streaming[Ee]ndpoints" seems to render starting the same impossible using az cli.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e88a2a0-c64c-6df9-cf19-a63981c73f4b
* Version Independent ID: 5cf0b5e5-2b36-d757-f1b0-8ca62427c9bb
* Content: [az ams streaming endpoint](https://docs.microsoft.com/en-us/cli/azure/ams/streaming/endpoint?view=azure-cli-latest#az-ams-streaming-endpoint-start)
* Content Source: [src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/_help.py)
* Service: **media-services**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by akucer** [comment]
Not able to repro so closing out.
