### ISSUE TITLE
Azure Disk Encryption managed data disks display null for encryptionSettings property

### ISSUE THREAD

**Issue by billpratt** [Azure/azure-cli#7059]
**Describe the bug**
**encryptionSettings** value null for managed disks attached to a VM as data disks and that have Azure Disk Encryption enabled

Example of ```az disk list``` with some irrelevant fields removed
```
[
  {
    "creationData": {
      "createOption": "FromImage",
      "imageReference": {
        "id": "/Subscriptions/.../Providers/Microsoft.Compute/Locations/eastus/Publishers/Canonical/ArtifactTypes/VMImage/Offers/UbuntuServer/Skus/16.04-LTS/Versions/16.04.201808060",
        "lun": null
      }
    },
    "diskSizeGb": 30,
    "encryptionSettings": {
      "diskEncryptionKey": {
        "secretUrl": "...",
        "sourceVault": {
          "id": ",..."
        }
      },
      "enabled": true,
      "keyEncryptionKey": {
        "keyUrl": "...",
        "sourceVault": {
          "id": "..."
        }
      }
    },
    "id": "...",
    "location": "eastus",
    "managedBy": "...",
    "name": "test-vm_OsDisk_1_d25779080fe5417398b280161aafcab7",
    "osType": "Linux",
    "provisioningState": "Succeeded",
    "sku": {
      "name": "Premium_LRS",
      "tier": "Premium"
    }
  },
  {
    "creationData": {
      "createOption": "Empty",
      "imageReference": null,
      "sourceResourceId": null,
      "sourceUri": null,
      "storageAccountId": null
    },
    "diskSizeGb": 5,
    "encryptionSettings": null,
    "id": "...",
    "location": "eastus",
    "managedBy": "...",
    "name": "test-encryption-enabled",
    "osType": null,
    "provisioningState": "Succeeded",
    "sku": {
      "name": "Premium_LRS",
      "tier": "Premium"
    }
  }
]
```

**To Reproduce**
* Run ```az vm encryption enable``` on a VM that has data disks attached. After encryption is enabled for all disks, run ```az disk list```. **encryptionSettings** is filled in for the OS disk, but null for the data disks. Similar behavior when running ```az vm show```.

**Expected behavior**
If managed disks are attached to a VM that have ADE enabled,  **encryptionSettings** should be populated when running ```az disk list```, ```az disk show``` or ```az vm show```

**Environment summary**
brew / azure-cli (2.0.38) / bash

**Additional context**

**Comment by yugangw-msft** [comment]
what you get if you run `az vm encryption show`?

**Comment by billpratt** [comment]
@yugangw-msft 
```
{
  "dataDisk": "Encrypted",
  "osDisk": "Encrypted",
  "osDiskEncryptionSettings": {
    "diskEncryptionKey": {
      "secretUrl": "REDACTED",
      "sourceVault": {
        "id": "REDACTED"
      }
    },
    "enabled": true,
    "keyEncryptionKey": {
      "keyUrl": "REDACTED",
      "sourceVault": {
        "id": "REDACTED"
      }
    }
  },
  "osType": "Linux",
  "progressMessage": "Encryption succeeded for all volumes"
}
```

**Comment by yugangw-msft** [comment]
@ejarvi, can you please take a look at this?

**Comment by ejarvi** [comment]
For starters, here are prerequisite steps required to prepare data disks before they can be encrypted: 

https://blogs.msdn.microsoft.com/ejarvi/2018/03/30/encrypting-data-disks-on-linux-with-azure-disk-encryption/

**Comment by adewaleo** [comment]
I will be closing this issue then, thanks @ejarvi. Please let us know if you have any more questions @billpratt 

cc @yugangw-msft
