### ISSUE TITLE
OpenVPN protocol support for VPN Gateways

### ISSUE THREAD

**Issue by anzaman** [Azure/azure-cli#7060]
Need to add OpenVPN as an option for -VpnClientProtocol  parameter.  Swagger is at https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2018-04-01/virtualNetworkGateway.json

**Comment by tjprescott** [comment]
No specific CLI-work needed other than updating the SDK. This will be in the Ignite release.
