### ISSUE TITLE
support classic nsg for az network watcher flow-log configure & show 

### ISSUE THREAD

**Issue by zwswim** [Azure/azure-cli#7066]
**Is your feature request related to a problem? Please describe.**
Currently, classic resources are not supported in Azure CLI 2.0.  Currently, Azure Network Watcher is trying to launch the feature to "enable flowlog for classic nsg " in Ignite and having CLI support would be desirable.

**Describe the solution you'd like**
1. if the NSG name is passed in, a new parameter to indicate which the NSG is a Classic Nsg will be desired. The default value could be false. 
2.  if the NSG Resource ID is passed in, CLI should be able to understand whether the NSG is a Classic or Nrp NSG since they have different provider:  Microsoft.ClassicNetwork vs Microsoft.Network

**Describe alternatives you've considered**

**Additional context**

**Comment by tjprescott** [comment]
If we are able to support this, we would only allow Classic NSG to be supported via ID. The main technical question is whether we can retrieve the classic NSG to retrieve its location given there is 0 Python SDK support for Classic Azure resources.

**Comment by tjprescott** [comment]
PR merged. Will be in Ignite release.
