### ISSUE TITLE
az network watcher connection-monitor query (need to add option to query list of connection monitors)

### ISSUE THREAD

**Issue by irrogozh** [Azure/azure-cli#7067]
**Is your feature request related to a problem? Please describe.**
Before now we had cmdlet which allow to query snapshot of specified connection monitor:
az network watcher connection-monitor query --location --name

We added another API which allow to query list or all connection monitors in the region.
Here is rest API spec: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2018-06-01/networkWatcher.json (line 1848).

Example of usage is here: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2018-06-01/examples/NetworkWatcherQueryConnectionMonitors.json

**Describe the solution you'd like**
we would like to have an option for customer to specify 1 connection monitor, list connection monitors or nothing. In last 2 cases, new API will be used.

**Describe alternatives you've considered**
We could create a new cmdlet, but I doubt it's an optimal solution...

**Additional context**

**Comment by tjprescott** [comment]
Closed at @irrogozh request
