### ISSUE TITLE
Need new cmdlet for NetworkWatcherNetworkConfigurationDiagnostic API

### ISSUE THREAD

**Issue by irrogozh** [Azure/azure-cli#7068]
**Is your feature request related to a problem? Please describe.**
We need a cmdlet for the new API. NetworkConfigurationDiagnostic API allows customer to get an information on if traffic is allowed or denied for configured filters. Each filter consists of direction, protocol, source, destination and sourcePort and destinationPort.

Here is rest API spec: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2018-06-01/networkWatcher.json (line 1781)
Example of usage: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2018-06-01/examples/NetworkWatcherNetworkConfigurationDiagnostic.json

**Describe the solution you'd like**
Our suggestion is to create 2 cmdlet. One is for creating traffic query. Another is for getting network configuration diagnostic.

az network watcher traffic query create --direction --protocol --source --destination --destinationPort
az network watcher network configuration diagnostic --location --targetResourceId --traficeQueries<List<trafficQuery>>

**Describe alternatives you've considered**

**Additional context**

**Comment by yugangw-msft** [comment]
//cc @tjprescott

**Comment by tjprescott** [comment]
PR merged. Will be in Ignite release.
