### ISSUE TITLE
az vm start command with --ids parameter executes serially

### ISSUE THREAD

**Issue by hejix** [Azure/azure-cli#7069]
**Describe the bug**
When using the az vm start and stop command with --ids parameter, machines are started or stopped serially.

For instance a cluster of 12 vms, the example from docs
     https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-start
`az vm start --ids $(az vm list -g MyResourceGroup --query "[].id" -o tsv)
`
takes 17+ minutes to execute.  Activity log indicates they were started in sequence 30 sec to a minute a part.

I opened an Azure support ticket and I was told to a create a batch script which makes this --ids parameter useless.  As a AWS/GCP user, their CLI commands when passing in multiple VMs execute in parallel as one would naturally expect.  (Actually tag filters should be built in to the az stop and start command itself, not tacked on by --ids.)

**To Reproduce**
Run `az vm start --ids $(az vm list -g MyResourceGroup --query "[].id" -o tsv)
` on a RG with more than 10 servers and wait for 10+ minutes

**Expected behavior**
Parallel execution! This is the cloud and that is the obvious expectation. If it does not, the documentation should be very clear that the --ids does not scale. 

**Environment summary**
Ubuntu 16.04 LTS on azure, cli

**Additional context**
We are migrating some of our data pipeline clusters to azure from gcp. Each of our test data pipe line cluster sets have 20+ machines and in gcp- vm startup is less than a minute.

**Comment by yugangw-msft** [comment]
It is by design right now as the core layer just loops around the id array and invoke the same command one after one.
Agreed we should improve it by going parallel.

**Comment by hejix** [comment]
Thanks for the clarification. It would be helpful if the documentation outlined ways to make this scalable.   Since we are using ansible, we will probably launch ansible async tasks for now as a workaround.
