### ISSUE TITLE
Attempt error reporting for zip file uploads

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-cli#7072]
_From @cfjedimaster on August 3, 2018 18:19_

While using zip uploads 

    az functionapp deployment source config-zip -g myResourceGroup -n <app_name> --src <zip_file_path>

I noticed an odd issue. The first time I tried it, I zipped it from a parent directory. So if foo was the folder with my function app, I zipped from the parent foo. This created a zip file where the *root* was a foo folder and not the contents of foo. (Obviously those contents were in there, just not at root.)

When I deployed, the CLI reported no issue with the zip. It took me a while to realize that I was zipped incorrectly. But the CLI never reported anything weird or wrong with the zip. If it had done so, it would have saved me quite a bit of time.

_Copied from original issue: Azure/azure-functions-core-tools#611_

**Comment by panchagnula** [comment]
this specific command takes the zip file provided as input & passes it to the scm zip deployment API, i am not sure what sort of validation is being expected here for the CL command. @ahmelsayed , are there any suggestions here on some pre-validation that can be done - especially if the zip deployment API isn't returning an error.

**Comment by panchagnula** [comment]
@cfjedimaster, the CLI command does not validate the contents of a zip file provided - atleast there is not such support from zip deployment at the time being. Closing this.

**Comment by cfjedimaster** [comment]
You realize that I was *asking* for it to validate? At least the minimum of "is the only entry at top a folder". I realize it doesn't do this now and I was asking it to be considered. Couldn't this be considered?

**Comment by panchagnula** [comment]
I realize & understand your ask - if we see more asks/feedback on this we will consider this on the CLI end, however for the API level to get a more robust validation, the functions-runtime should consider this.
