### ISSUE TITLE
'expiresOn' in accessTokens.json should be UTC time

### ISSUE THREAD

**Issue by karataliu** [Azure/azure-cli#7078]
**Describe the bug**
expiresOn in accessTokens.json should be UTC

**To Reproduce**
1. az login
2. switch timezone
3. az login

The expiresOn property is based on current timezone.

Found related issue:
https://github.com/Azure/azure-cli/issues/5922

**Expected behavior**
The expiresOn should be UTC timezone to keep consistency

**Environment summary**
$ az --version
azure-cli (2.0.42)

**Additional context**

**Comment by troydai** [comment]
@yugangw-msft

**Comment by yugangw-msft** [comment]
This piece of information comes from ADAL which has been like this for a while. Because you have the refresh token, even the token gets expired prematurely per timezone change, but CLI can still acquire a new token for you.
What end user scenarios are impacted by this?

**Comment by karataliu** [comment]
I found this in testing scenario, the same token acquired would not be used in another machine in different timezone.

 `the token gets expired prematurely per timezone change, but CLI can still acquire a new token`
Yes, I'm suggesting it is something we might improve to save one call for refresh token.

Another point is, if you keep timestamp string somewhere without zone information, people may assume it to be UTC, see discussion:
https://github.com/Azure/azure-cli/issues/5922#issuecomment-376355845

**Comment by karataliu** [comment]
Would you please fix this?

**Comment by yugangw-msft** [comment]
Are there any scenarios at your end blocked by this, or just a perf concern? With more context, I might be able to find a solution for you.
Like I said, token entries are not supposed to be tweaked by client end; ADAL.net even serializes to a binary blob to prevent that.

**Comment by karataliu** [comment]
If the raw value comes from server side, I agree we should not fix it.

Could you please point out the code piece for retrieve such binary blob?

**Comment by karataliu** [comment]
This is misleading if other libraries take a look at the value.

Could you please point out the code for retrieving? Thanks

**Comment by yugangw-msft** [comment]
@karataliu, sorry for the delay, here is the [code](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/dev/adal/oauth2_client.py#L187) . 
You can open an issue over there.  Meanwhile I am closing this issue
