### ISSUE TITLE
az cosmosdb create fails with 'too many 502 error responses'

### ISSUE THREAD

**Issue by PeterRockstars** [Azure/azure-cli#7079]
**Describe the bug**
When running az cosmosdb create, the command fails with 'too many 502 error responses' message.

**To Reproduce**
Run 
```
az cosmosdb create --name cosmosdbtest2`
                   --resource-group cosmosdbtest1 `
                   --default-consistency-level Session `
                   --max-interval 5 `
                   --max-staleness-prefix 100 
```

**Expected behavior**
The Cosmos DB instance is created without errors.

**Environment summary**
azure cli run Powershell window on Windows 10 Pro

az --version:

> acr (2.1.3)
> acs (2.3.0)
> advisor (0.6.0)
> ams (0.2.2)
> appservice (0.2.2)
> backup (1.2.0)
> batch (3.3.2)
> batchai (0.4.1)
> billing (0.2.0)
> cdn (0.1.0)
> cloud (2.1.0)
> cognitiveservices (0.2.0)
> command-modules-nspkg (2.0.2)
> configure (2.0.18)
> consumption (0.4.0)
> container (0.3.3)
> core (2.0.44)
> cosmosdb (0.2.0)
> dla (0.2.1)
> dls (0.1.0)
> dms (0.1.0)
> eventgrid (0.2.0)
> eventhubs (0.2.2)
> extension (0.2.1)
> feedback (2.1.4)
> find (0.2.12)
> interactive (0.3.28)
> iot (0.3.0)
> iotcentral (0.1.0)
> keyvault (2.2.2)
> lab (0.1.0)
> maps (0.3.1)
> monitor (0.2.2)
> network (2.2.3)
> nspkg (3.0.3)
> policyinsights (0.1.0)
> profile (2.1.1)
> rdbms (0.3.0)
> redis (0.3.0)
> relay (0.1.0)
> reservations (0.3.1)
> resource (2.1.2)
> role (2.1.3)
> search (0.1.1)
> servicebus (0.2.1)
> servicefabric (0.1.1)
> sql (2.1.2)
> storage (2.2.0)
> telemetry (1.0.0)
> vm (2.2.1)

**Additional context**
Full error message:

Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/d090826d-21e1-44d7-9696-04e33887d08e/resourceGroups/cosmosdbtest1/providers/Microsoft.DocumentDB/databaseAccounts/cosmosdbtest2?api-version=2015-04-08 (Caused by ResponseError('too many 502 error responses',))
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\urllib3\connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\urllib3\connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\urllib3\connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\urllib3\connectionpool.py", line 711, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/d090826d-21e1-44d7-9696-04e33887d08e/resourceGroups/cosmosdbtest1/providers/Microsoft.DocumentDB/databaseAccounts/cosmosdbtest2?api-version=2015-04-08 (Caused by ResponseError('too many 502 error responses',))

During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\msrest\service_client.py", line 342, in send
>     response = http_driver.send(request, **kwargs)
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\msrest\service_client.py", line 187, in send
>     **kwargs)
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\requests\sessions.py", line 512, in request
>     resp = self.send(prep, **send_kwargs)
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\requests\sessions.py", line 622, in send
>     r = adapter.send(request, **kwargs)
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\requests\adapters.py", line 504, in send
>     raise RetryError(e, request=request)
> requests.exceptions.RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/d090826d-21e1-44d7-9696-04e33887d08e/resourceGroups/cosmosdbtest1/providers/Microsoft.DocumentDB/databaseAccounts/cosmosdbtest2?api-version=2015-04-08 (Caused by ResponseError('too many 502 error responses',))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\knack\cli.py", line 197, in invoke
>     cmd_result = self.invocation.execute(args)
>   File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-cli-core\azure\cli\core\commands\__init__.py", line 369, in execute
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\six.py", line 693, in reraise
>     raise value
>   File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-cli-core\azure\cli\core\commands\__init__.py", line 343, in execute
>   File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-cli-core\azure\cli\core\commands\__init__.py", line 182, in __call__
>   File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-cli-core\azure\cli\core\__init__.py", line 436, in default_command_handler
>   File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-cli-cosmosdb\azure\cli\command_modules\cosmosdb\custom.py", line 85, in cli_cosmosdb_create
>   File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-mgmt-cosmosdb\azure\mgmt\cosmosdb\operations\database_accounts_operations.py", line 291, in create_or_update
>   File "C:\Users\troyd\AppData\Local\Temp\pip-install-_jje8pgf\azure-mgmt-cosmosdb\azure\mgmt\cosmosdb\operations\database_accounts_operations.py", line 242, in _create_or_update_initial
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\msrest\service_client.py", line 369, in send
>     raise_with_traceback(ClientRequestError, msg, err)
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\msrest\exceptions.py", line 54, in raise_with_traceback
>     raise error.with_traceback(exc_traceback)
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\msrest\service_client.py", line 342, in send
>     response = http_driver.send(request, **kwargs)
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\msrest\service_client.py", line 187, in send
>     **kwargs)
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\requests\sessions.py", line 512, in request
>     resp = self.send(prep, **send_kwargs)
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\requests\sessions.py", line 622, in send
>     r = adapter.send(request, **kwargs)
>   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\requests\adapters.py", line 504, in send
>     raise RetryError(e, request=request)
> msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/d090826d-21e1-44d7-9696-04e33887d08e/resourceGroups/cosmosdbtest1/providers/Microsoft.DocumentDB/databaseAccounts/cosmosdbtest2?api-version=2015-04-08 (Caused by ResponseError('too many 502 error responses',))

**Comment by edykim** [comment]
It is still returning same problem.

**Comment by shurd** [comment]
@edykim @PeterRockstars If you are still experiencing this response, could you provide a subscriptionId, account name and date/time you saw the error so we can investigate?

**Comment by PeterRockstars** [comment]
@shurd It's been a while since I attempted this, if it happens again (which probably won't be anytime soon), I'll post the details here.

**Comment by tjprescott** [comment]
Since 500 errors tend to be transient server issues, I will close this. @PeterRockstars if you do encounter this again, please reopen this issue or post a new one.
