### ISSUE TITLE
az acr build should exclude .git folder

### ISSUE THREAD

**Issue by northtyphoon** [Azure/azure-cli#7084]
**Describe the bug**
If the source code folder has the vcs folders eg `.git` or `.bzr` , az acr build should exclude the files from the folders in the uploaded tar file.

**To Reproduce**
Source code folder structure:
.git 
 | -- file1
Dockerfile

az acr build -t <registry> <source_code_folder>

**Expected behavior**
The uploaded tar file should exlude `.git` folder. The tar file should only have `Dockerfile`.

**Additional context**
It's a regression from #6950 

Related issue: https://github.com/Azure/acr/issues/122

If users manually add .git in .dockerignore file. The .git folder will be excluded.

**Comment by sajayantony** [comment]
How does this impact users. The default might be good. But if they have a task that does a git checkout then does this fail?

**Comment by ehotinger** [comment]
@sajayantony they can use git context directly for that case instead of using `az acr build .` - valid concern though.

**Comment by alexsandro-xpt** [comment]
Should ignore node_modules please!!!!
![alt text](https://preview.redd.it/tfugj4n3l6ez.png?width=960&crop=smart&auto=webp&s=b477bf6ac3c7bddfef1c2d483d73029437a42e30 "Node Module")

**Comment by ehotinger** [comment]
@alexsandro-xpt you can ignore `node_modules` in a `.dockerignore` file. We honor this in the CLI when packaging the context.

**Comment by alexsandro-xpt** [comment]
Are you sure @ehotinger ? The `.dockerignore` should be just in `<source_code_folder>` the context?

I will test better, at my tests because I saw all `node_modules` files list when `--verbose` was specified with az acr build -t.

**Comment by ehotinger** [comment]
@alexsandro-xpt it should. If you type `--debug` you should see output from the `dockerignore`, i.e.

```
.dockerignore: rule 'node_modules' matches 'node_modules'.
.dockerignore: no rule for 'node_modules/10Gigfile'. parent ignore 'True'
```

for a `.dockerignore` containing the entry `node_modules`.

As a simple test you can run `fallocate -l 10G 10Gigfile` to make a 10GB file in `node_modules` and run `az acr build .` The CLI prints out the uploaded context size:

`Sending context (49.698 KiB)` - if that's changing after your 10 GB file it's a problem. Make a bug report with repro steps on this repo if that's the case.

If your upload itself is slow you could try to use a remote context i.e., a GitHub URL or VSTS URL if possible. Uploads will naturally be slower if you're in a different region than your ACR instance.

**Comment by alexsandro-xpt** [comment]
@ehotinger with `.dockerignore` works, but the problem when `node_modules` is too large and all deep entire subdir path was scanning by az acr build, ie:

```
.
.
.
.
.dockerignore: no rule for 'node_modules/@babel/types/lib/validators/generated'. parent ignore 'False'
.dockerignore: no rule for 'node_modules/@babel/types/lib/validators/generated/index.js'. parent ignore 'False'
.dockerignore: no rule for 'node_modules/@babel/types/lib/validators/is.js'. parent ignore 'False'
.dockerignore: no rule for 'node_modules/@babel/types/lib/validators/isBinding.js'. parent ignore 'False'
.dockerignore: no rule for 'node_modules/@babel/types/lib/validators/isBlockScoped.js'. parent ignore 'False'
.dockerignore: no rule for 'node_modules/@babel/types/lib/validators/isImmutable.js'. parent ignore 'False'
.dockerignore: no rule for 'node_modules/@babel/types/lib/validators/isLet.js'. parent ignore 'False'
.dockerignore: no rule for 'node_modules/@babel/types/lib/validators/isNode.js'. parent ignore 'False'
.dockerignore: no rule for 'node_modules/@babel/types/lib/validators/isNodesEquivalent.js'. parent ignore 'False'
.dockerignore: no rule for 'node_modules/@babel/types/lib/validators/isReferenced.js'. parent ignore 'False'
.dockerignore: no rule for 'node_modules/@babel/types/lib/validators/isScope.js'. parent ignore 'False'
.dockerignore: no rule for 'node_modules/@babel/types/lib/validators/isSpecifierDefault.js'. parent ignore 'False'
.dockerignore: no rule for 'node_modules/@babel/types/lib/validators/isType.js'. parent ignore 'False'
.
.
.
.
```

This scan is too slow..

**Comment by alexsandro-xpt** [comment]
@ehotinger as was tould you:

```
.dockerignore: no rule for 'src/AuthenticationServices.WebApp/VueSpaApp/node_modules/.cache/uglifyjs-webpack-plugin'. parent ignore 'False'
.dockerignore: no rule for 'src/AuthenticationServices.WebApp/VueSpaApp/node_modules/.cache/uglifyjs-webpack-plugin/content-v2'. parent ignore 'False'
.dockerignore: no rule for 'src/AuthenticationServices.WebApp/VueSpaApp/node_modules/.cache/uglifyjs-webpack-plugin/content-v2/sha512'. parent ignore 'False'
.dockerignore: no rule for 'src/AuthenticationServices.WebApp/VueSpaApp/node_modules/.cache/uglifyjs-webpack-plugin/content-v2/sha512/00'. parent ignore 'False'
.dockerignore: no rule for 'src/AuthenticationServices.WebApp/VueSpaApp/node_modules/.cache/uglifyjs-webpack-plugin/content-v2/sha512/00/e5'. parent ignore 'False'
Deleting the archived source code from 'C:\Users\alexs\AppData\Local\Temp\build_archive_5df50b9f3d7d496a84a6e916d2440ec1.tar.gz'...
[WinError 3] O sistema não pode encontrar o caminho especificado: '.\\src\\AuthenticationServices.WebApp\\VueSpaApp\\node_modules\\.cache\\uglifyjs-webpack-plugin\\content-v2\\sha512\\00\\e5\\b3458cdc96c22f252f1972ac9b527a476b3db8aeae653c72e6dc8ace0b9d338517b3fdd53bac87e4a215f650e728a3c03d448ed7c9d2ed9e625828fdcf2b'
telemetry.save : Save telemetry record of length 2442 in cache
telemetry.check : Negative: The C:\Users\alexs\.azure\telemetry.txt was modified at 2019-01-11 23:57:12.193997, which in less than 600.000000 s
```

As you can see, this scan is bad, today a got a `[WinError 3]`: Too deep npm directory at Windows. I know it is some kind of Windows limitation but.... It's bad.

**Comment by dersia** [comment]
> @sajayantony they can use git context directly for that case instead of using az acr build . - valid concern though.

We are using GitVersion when building in a multi-stage-build in ACR. Since ACR is excluding .git and there is no way to include .git, we got stuck here. Is there any work-around?

**Comment by ehotinger** [comment]
@dersia can you use a git context (`az acr build foo.git` instead of `az acr build .`)?

**Comment by northtyphoon** [comment]
@dersia You can create a .dockerignore file with the following setting. It will tell acr command to include back all files under .git which is effectively include .git folder. Let me know if it works.

```
!.git/**
```
