### ISSUE TITLE
Message retention is not available with Basic tier but

### ISSUE THREAD

**Issue by jleach** [Azure/azure-cli#7085]
It would be handy to point out in the documentation that `--message-retention` is not available with a Basic tier namespace. The CLI does let you set the value to 1 which must be the default and a bit confusing; The error message thrown by the the CLI is not really helpful when this scenario is encountered.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fa949ea-86b1-125e-e7d3-f0f88a2661ab
* Version Independent ID: c8351dbc-7358-ba5b-6757-3929a4a2b42b
* Content: [az eventhubs eventhub](https://docs.microsoft.com/en-us/cli/azure/eventhubs/eventhub?view=azure-cli-latest#az-eventhubs-eventhub-create)
* Content Source: [src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/_help.py)
* Service: **event-hubs**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jfggdl** [comment]
Acknowledged.

**Comment by jfggdl** [comment]
@dsouzaarun  and @v-ajnava, would you please check the behavior of the CLI and the documentation. We may need to change the message that we are presenting to the user to make clear that the maximum value for retention is 1 for Basic tier, for example. We also need to double-check that our public documentation provides that information.
