### ISSUE TITLE
Message Retention with Basic Tier

### ISSUE THREAD

**Issue by jleach** [Azure/azure-cli#7086]
Hey,

The problem noted in issue https://github.com/Azure/azure-cli/issues/6676 is that with a Basic Tier you *must* include the option `--message-retention 1` in order for the create command to work. I think this makes it a *required* parameter under some circumstances.

I think the best thing to do is for the CLI or Azure to set a default for the parameter if the tier is `Basic` but a note in the docs would do for now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fa949ea-86b1-125e-e7d3-f0f88a2661ab
* Version Independent ID: c8351dbc-7358-ba5b-6757-3929a4a2b42b
* Content: [az eventhubs eventhub](https://docs.microsoft.com/en-us/cli/azure/eventhubs/eventhub?view=azure-cli-latest#az-eventhubs-eventhub-create)
* Content Source: [src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/_help.py)
* Service: **event-hubs**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jfggdl** [comment]
Duplicate. Same as #7085
