### ISSUE TITLE
Generic mechanism to designate that parameters can be backed by an environment variable or settings file

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#709]
Related to issue #657. Currently, only the storage account connection parameters are backed by environment variables (essentially persistent defaults). As we move forward, looking to expose additional parameters to defaults through `azure configure`, we should unify the way this is handled.

One proposal would be to extend the `register_cli_argument` method so that it can accept a persistent key. This would be the environment variable name and the key in the settings file, as appropriate. The actual value on command execution would be based on the following precedence:
1. The specified option/flag (--account-name)
2. The set environment variable (AZURE_STORAGE_ACCOUNT)
3. The value saved in the settings file, set via `azure configure`.

**Comment by derekbekoe** [comment]
PR #739 supports the precedence method of setting the value.
Only feature left is to extend `register_cli_argument` to support this.

**Comment by derekbekoe** [comment]
There are several places where we use environment variables where instead, they should be backed by configurations that can be set with env variables but also config files.

For example in https://github.com/Azure/azure-cli/blob/master/src/azure/cli/_logging.py#L16, we have:
```
ENABLE_LOG_FILE = os.environ.get('AZURE_CLI_ENABLE_LOG_FILE')
LOG_DIR = os.environ.get('AZURE_CLI_LOG_DIR')
```

Instead, this should be taken from the configuration and the environment variables would be something like 'AZURE_LOG_ENABLE_LOG_FILE' and 'AZURE_LOG_DIR'.

**Comment by tjprescott** [comment]
Hasn't been movement on this in 2 years.  Closing.
