### ISSUE TITLE
Failed to login US Gov with a service principal in a VM in global Azure

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-cli#7094]
**Describe the bug**

When I login US Gov with a service principal in a VM in global Azure, I got the error:
```
Get Token request returned http error: 400 and server response: {"error":"invalid_request","error_description":"AADSTS90038: Confidential Client is not supported in Cross Cloud request"}
```
When I login US Gov with a service principal in a VM in Azure US Gov. It works.
I think, it's an expected behavior. Can you please confirm it?
However, I didn't find an official document to describe this error in Azure doc.

**Environment summary**
Install Method (apt-get) / CLI version (2.0.44) / OS version / Shell Type (bash)

**Comment by tjprescott** [comment]
@sauryadas can you respond? @yugangw-msft is OOF for a couple weeks.

**Comment by yugangw-msft** [comment]
It is about the `Cross-cloud federation`. `WW -> Sovereign` is supported, but not vice versa. So yes, this is expected.
This is not a CLI question, rather on AAD.  So closing ...
