### ISSUE TITLE
unable to choose the -https' --protocol option for the az network lb probe create 

### ISSUE THREAD

**Issue by hectoralicea** [Azure/azure-cli#7095]
**Describe the bug**
unable to use the https protocol for the az network lb probe create 

**To Reproduce**
invoke az network lb probe create on an LB that's already been created using the --sku Standard  option.

**Expected behavior**
I should be able to create probe that probes on an https URL rather than an http.

**Environment summary**
On Mac or Linux, same result.

**Additional context**
CLI version is:
az --version
azure-cli (2.0.35
    on my MAC and
az --version
azure-cli (2.0.37)
    on my Linux server VM

I'm unable to use the https protocol for the az network lb probe create even though on these two web pages it clearly shows that I can use an https probe for a standard lb.

https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-custom-probe-overview#types

https://docs.microsoft.com/en-us/cli/azure/network/lb/probe?view=azure-cli-latest#az-network-lb-probe-create

az network lb probe create --resource-group IAM_FQT_RG --lb-name IAM-APP-LB-FQT --name https_probe --port 443 --protocol Https --path /probe.html
az network lb probe create: 'Https' is not an az network lb probe create command. See 'az network lb probe create --help'.

**Comment by tjprescott** [comment]
I am not able to reproduce this. When I run your command on a standard LB it works without issue.

**Comment by tjprescott** [comment]
Glad it's working for you!
