### ISSUE TITLE
az vm create fails when user account name is too short

### ISSUE THREAD

**Issue by omichels** [Azure/azure-cli#7097]
When running az vm create without specifying an admin-username and having a login name that is 'root' (I'm guessing anything 5 letters or less), your vm deployment fails.

how to reproduce:

az vm create --resource-group myResourceGroup --name myVM --image UbuntuLTS --generate-ssh-keys
This user name 'root' meets the general requirements, but is specifically disallowed for this image. Please try a different value.

bash-4.4# adduser user
bash-4.4# su - user
$ az vm create --resource-group myResourceGroup --name myVM --image UbuntuLTS --generate-ssh-keys
This user name 'user' meets the general requirements, but is specifically disallowed for this image. Please try a different value.

Now i'm using a longer name and now the deployment works:

bash-4.4# adduser oliver_michels
bash-4.4# su - oliver_michels
$ az vm create --resource-group myResourceGroup --name myVM --image UbuntuLTS --generate-ssh-keys
SSH key files '/home/oliver_michels/.ssh/id_rsa' and '/home/oliver_michels/.ssh/id_rsa.pub' have been generated under ~/.ssh to allow SSH access to the VM. If using machines without permanent storage, back up your keys to a safe location.

**Comment by tjprescott** [comment]
As the error messages state, `root` and `user` are specifically blacklisted for admin-username. It isn't because they are too short. This is a service-imposed restriction and there is nothing the CLI can do to make these blacklisted names usable.
