### ISSUE TITLE
Private repos

### ISSUE THREAD

**Issue by keithdoyle9** [Azure/azure-cli#7102]
Just had a conversation with a Support Engineer only to find out that this doesn't support private repos. Can you add that to the documentation for future folks who might run into the same issue? We're running Github Enterprise right now and spent a few days trying to get this to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa503a99-f138-afe4-1185-ff62ce770d0f
* Version Independent ID: 67810fcb-3d9b-a60a-21ec-8d8f40c83328
* Content: [az acr build-task](https://docs.microsoft.com/en-us/cli/azure/acr/build-task?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ehotinger** [comment]
This should support private repositories. If it doesn't then it's a bug. Can you try passing in the build context as `https://PAT@github.com/abc/f.git` where PAT is your personal access token?

/cc @mnltejaswini @ankurkhemani @northtyphoon

**Comment by sajayantony** [comment]
@keithdoyle9 - Eric's solution is one way but if you just want to automate this - 
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-build-task#create-a-github-personal-access-token

**Comment by keithdoyle9** [comment]
We're actually using GitHub Enterprise that's hosted in our own data
center, not at GitHub.com.

**Comment by ehotinger** [comment]
@keithdoyle9  I see, it's possible this isn't supported from the front-end right now in that case. Can you give us an example of the URL you're trying to use - i.e. if you were to use `docker build` with that remote git url, what would it look like?

**Comment by keithdoyle9** [comment]
https://github.example.com/Marketing/docker

Marketing would be the organization in our GitHub.

**Comment by SteveLasker** [comment]
Thanks Keith,
We haven’t yet tested on-prem GitHub enterprise
In the on-prem scenarios, does adding .git work to the conte t?

**Comment by keithdoyle9** [comment]
Nah, that didn't work. I'd be more than happy to help with testing if you
need a guinea pig.

**Comment by sajayantony** [comment]
Could you please email sajaya@microsoft.com and stevelas@microsoft.com so that we can get some more information and work with you on this?

**Comment by keithdoyle9** [comment]
No longer using azure repos.
