### ISSUE TITLE
Issue with first Example

### ISSUE THREAD

**Issue by john-louden** [Azure/azure-cli#7104]
The first example uses the wrong switch for the vnet

az network vnet subnet list -g MyResourceGroup --vnet-name MyVNet

this should be 

az network vnet subnet list -g MyResourceGroup -n MyVNet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 385e420c-4bd0-3ddd-d9cd-a9a411ec1f7b
* Version Independent ID: 65172372-f485-3d2b-64aa-57c38ac11538
* Content: [az network vnet subnet](https://docs.microsoft.com/en-us/cli/azure/network/vnet/subnet?view=azure-cli-latest#az-network-vnet-subnet-list)
* Content Source: [src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
No, the example is correct.  It should be `--vnet-name` not `-n`

**Comment by tjprescott** [comment]
Actually, it's the other way around. The example uses `-n` but should use `--vnet-name`

**Comment by tjprescott** [comment]
This change will be reflect in next month's release.
