### ISSUE TITLE
Support for Gateway Subnet

### ISSUE THREAD

**Issue by john-louden** [Azure/azure-cli#7106]
**Is your feature request related to a problem? Please describe.**
The VNET Subnet module does not have a switch to designate the role of a subnet, eg gateway

**Describe the solution you'd like**
to have a switch similar to --role gateway to denote the subnet to be created is a gateway subnet

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by tjprescott** [comment]
@rupalivohra does issue #6941, Subnet purpose, address this ask?

**Comment by rupalivohra** [comment]
I don't think this is related.

**Comment by tjprescott** [comment]
@john-louden your ask is not currently supported by the service, so I've redirected it to the service team for their attention. In the case of gateways, certain commands (like `vnet-gateway create`) require your subnet to be named "GatewaySubnet".

**Comment by john-louden** [comment]
@tjprescott seeing the name is "hardcoded" is it better to have something like 

network vnet gateway-subnet

with the allowed inputs 

- ResourceGroup,
- VNET, 
- CIDR range 

The out should be similar to the subnet create just with the name hardcoded. Just my random thoughts

**Comment by MyronFanQiu** [comment]
@Am018 Hello. Any update about this issue?
