### ISSUE TITLE
--tags needs a better example

### ISSUE THREAD

**Issue by markgar** [Azure/azure-cli#7112]
I think it would be helpful to show exactly how to format --tags using 2 examples so that it is clear how to put them together.

Space-separated tags in 'key1[=value1],key2[=value2]' format. Use "" to clear existing tags.

When do i use " and when do i use '?  This isn't clear.  I'm assuming this is on every page in the CLI docs...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58c81c4d-10d2-fc04-e707-fcf914f4d540
* Version Independent ID: 8598f788-bd33-a4c8-ed66-593e0fde75d5
* Content: [az group](https://docs.microsoft.com/en-us/cli/azure/group?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by markgar** [comment]
I found the answer to this, but I think it would be helpful to have an example that says it is just a space separate list with no quotes.

**Comment by tjprescott** [comment]
Would this help:
```
--tags  Space-separated list of tags. Use "" to clear tags.
      Usage:  --tags key[=value] [key[=value] ...]
```

**Comment by markgar** [comment]
I think so.  I've seen this same doc sample elsewhere.

**Comment by badalk** [comment]
but if either your tags or values has space then this does not work. Especially when you are adding to the existing tags as then you have to manipulate the strings

**Comment by haokanga** [comment]
+1 to the issue, please provide concrete worked examples that can be understood by _beginners_. 
`key[=value] [key[=value] ...]` may make perfect sense for developers with the knowledge the syntax, but a beginner of Azure CLI can translate "key[=value]" literally into "myKey=[myValue]" instead of "myKey=myValue", which results the key as `myKey[` and the value as `TPZ]`. This misunderstanding is observed (not crafted).

**Comment by yonzhan** [comment]
add to S165.

**Comment by haroldrandom** [comment]
I will choose this style: `Space-separated list of tags. Use "" to clear existing tags. Usage: --tags key[=value] [key[=value] ...]`
