### ISSUE TITLE
Typo "Resorce" in sidebar

### ISSUE THREAD

**Issue by shubhranshu** [Azure/azure-cli#7116]
There is a typo in sidebar. Correct word is "Resource"

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2e3dfa7-e7ba-d8b9-9c8b-7a716016b7c0
* Version Independent ID: 249776f7-0d81-361b-822e-b87c2ca7fb23
* Content: [az storage cors](https://docs.microsoft.com/en-gb/cli/azure/storage/cors?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by williexu** [comment]
@daxianji007 where are the sidebar names defined? It does not seem to come from our CLI.
Can you take a look?

**Comment by tjprescott** [comment]
@dend

**Comment by williexu** [comment]
Fixed with https://github.com/Azure/azure-docs-cli-python/pull/1071
