### ISSUE TITLE
Listing App Service Runtimes should show Linux and Windows Runtimes

### ISSUE THREAD

**Issue by berndverst** [Azure/azure-cli#7131]
`az webapp list-runtimes` currently only lists App Service Windows runtimes. To see the Linux runtimes one must use the less obvious `--linux` flag.

This request is to combine the Linux runtimes into the `az webapp list-runtimes` command.

Desired behavior and output:
`az webapp list-runtimes -ojson`

Produces:
```
[
  {
    "type": "windows",
    "runtimes": [
      "aspnet|v4.7",
      "aspnet|v3.5",
      "node|0.6",
      "node|0.8",
      "node|0.10",
      "node|0.12",
      "node|4.0",
      "node|4.1",
      "node|4.2",
      "node|4.2",
      "node|4.3",
      "node|4.4",
      "node|4.5",
      "node|4.6",
      "node|5.0",
      "node|5.1",
      "node|5.3",
      "node|5.4",
      "node|5.5",
      "node|5.6",
      "node|5.7",
      "node|5.8",
      "node|5.9",
      "node|6.0",
      "node|6.1",
      "node|6.10",
      "node|6.2",
      "node|6.3",
      "node|6.5",
      "node|6.6",
      "node|6.7",
      "node|6.9",
      "node|7.0",
      "node|7.1",
      "node|7.2",
      "node|7.3",
      "node|7.4",
      "node|7.5",
      "node|7.6",
      "node|7.7",
      "node|7.10",
      "node|8.0",
      "node|8.1",
      "php|5.6",
      "php|7.0",
      "php|7.1",
      "php|7.2",
      "python|2.7",
      "python|3.4",
      "java|1.7|Tomcat|7.0",
      "java|1.7|Tomcat|8.0",
      "java|1.7|Tomcat|8.5",
      "java|1.7|Tomcat|9.0",
      "java|1.7|Jetty|9.1",
      "java|1.7|Jetty|9.3",
      "java|1.8|Tomcat|7.0",
      "java|1.8|Tomcat|8.0",
      "java|1.8|Tomcat|8.5",
      "java|1.8|Tomcat|9.0",
      "java|1.8|Jetty|9.1",
      "java|1.8|Jetty|9.3"
    ]
  },
  {
    "type": "linux",
    "runtimes": [
      "RUBY|2.3",
      "NODE|4.4",
      "NODE|4.5",
      "NODE|4.8",
      "NODE|6.2",
      "NODE|6.6",
      "NODE|6.9",
      "NODE|6.10",
      "NODE|6.11",
      "NODE|8.0",
      "NODE|8.1",
      "NODE|8.2",
      "NODE|8.8",
      "NODE|8.9",
      "NODE|8.11",
      "NODE|9.4",
      "NODE|10.1",
      "PHP|5.6",
      "PHP|7.0",
      "PHP|7.2",
      "DOTNETCORE|1.0",
      "DOTNETCORE|1.1",
      "DOTNETCORE|2.0",
      "DOTNETCORE|2.1",
      "TOMCAT|8.5-jre8",
      "TOMCAT|9.0-jre8",
      "JAVA|8-jre8",
      "PYTHON|3.7"
    ]
  }
]
```

**Comment by tjprescott** [comment]
cc/ @Panchagnula, @yugangw-msft

**Comment by panchagnula** [comment]
This is an API level change that needs to happen & our API team is aware of it - this will automatically work when the API is updated.We don't have intentions of making these changes in CLI directly. Thanks!

**Comment by jdubois** [comment]
Thank you so much @berndverst  - I didn't know about this flag, I've been stuck for hours because of this!!!
2 other important things on those runtimes:

- Some of them should be the same on Windows and Linux. "Java 11" should have the same runtime name under both, for instance.
- For Java users, the Maven plugin uses also a "runtime" flag, but it is yet another one. So this is all very misleading.

**Comment by robconery** [comment]
It's 2.5 years later and this is still a problem I'd like to politely suggest that our runtime story RE Linux/Windows could be improved. Please reopen. I just ran into this today and it was discouraging to see a thread from 2018.
