### ISSUE TITLE
Support for Alias Records in Azure DNS

### ISSUE THREAD

**Issue by karravi-msft** [Azure/azure-cli#7136]
**Is your feature request related to a problem? Please describe.**
Need support for alias records in Azure CLI

**Describe the solution you'd like**
Alias records is a new feature in Azure DNS launching in Ignite. It is primarily related to adding an azure resource as a target for a record set. Also, TTL is optional for alias records. Please contact vladrai,karravi for any additional details

**Describe alternatives you've considered**

**Additional context**

Fraft swagger can be seen in https://github.com/karravi-msft/azure-rest-api-specs/tree/master/specification/dns/resource-manager/Microsoft.Network/stable/2018-05-01 . This will be pushed to main line azure fork in the week of 8/28

**Comment by tjprescott** [comment]
Merged.
