### ISSUE TITLE
Why simple CentOS-HPC VM is failing?

### ISSUE THREAD

**Issue by lmiroslaw** [Azure/azure-cli#7137]
az vm create --resource-group hpc-my --name ansysVM --image OpenLogic:CentOS-HPC:7.4:latest --admin-username username123 --admin-password pswd --size Standard_H8

This image requires --osDisk parameter. I don't understand why…
What is the correct set of parameters to deploy CentOS-HPC image?

>Deployment failed. Correlation ID: 33ac9c21-9a80-4b5e-81f9-a0f7a4699528. {
  "error": {
    "code": "InvalidParameter",
    "target": "osDisk.managedDisk",
    "message": "The value of parameter osDisk.managedDisk is invalid."
  }
}
---

### Environment summary
az-cli version 2.0.43

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by lmiroslaw** [comment]
Should not the CentOS image be automatically attached to the osDisk? Should not this be an automated procedure run in the background?

**Comment by johanste** [comment]
For whatever it is worth, I just ran the same command on az @ 2.0.44 on a windows box, and the command succeeded. I created the VM in the westus location.

**Comment by yugangw-msft** [comment]
@lmiroslaw please make sure you are not updating an existing VM with conflicting configurations; then run the vm command with `--debug` and send me the trace with the error at yugangw at microsoft dot com
I am closing this as it is unlikely a CLI issue, but I will reactivate once get a repro
