### ISSUE TITLE
"/managedClusters/listClusterAdminCredential/action" is not working as expected

### ISSUE THREAD

**Issue by praveendhac** [Azure/azure-cli#7138]
**Issue**
listClusterAdminCredential is not working as expected.

Following below documentation to write custom role to block users getting clusterAdmin credentials but allow clusterUser credential 
https://docs.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations

Created below custom role
```
$ az role definition update --role-definition custRoleBlockCAdmin.json
{
  "assignableScopes": [
    "/subscriptions/xx-yy-11-22/"
  ],
  "description": "Restrict users from getting ClusterAdmin credentials",
  "id": "/subscriptions/xx-yy-11-22/providers/Microsoft.Authorization/roleDefinitions/aa-bb-88-99",
  "name": "xxyyzz-6635-4390-9e84-112233",
  "permissions": [
    {
      "actions": [
        "*"
      ],
      "dataActions": [],
      "notActions": [
        "Microsoft.ContainerService/managedClusters/listClusterAdminCredential/action"
      ],
      "notDataActions": []
    }
  ],
  "roleName": "Restrict getting ClusterAdmin kubeconfig",
  "roleType": "CustomRole",
  "type": "Microsoft.Authorization/roleDefinitions"
}
```
Applied the role to user from Portal, Cloud CLI. Logged in as the user from terminal on my laptop using _az login_ and executed below commands.
```
$ az aks get-credentials -n dex-aks -g dex-aks -f rmv_dex-aks_clusteradmin.config
Merged "dex-aks" as current context in rmv_dex-aks_clusteradmin.config

$ az aks get-credentials -n dex-aks -g dex-aks --admin -f rmv_dex-aks_clusteradmin.config
Merged "dex-aks-admin" as current context in rmv_dex-aks_clusteradmin.config
```

**Expectation**:
Execution of _az aks get-credentials_ command should be blocked when"--admin" parameter is used and execution should succeed when the parameter is **not** passed.

**Comment by praveendhac** [comment]
Any updates on this please?
Is there a work around to block "az aks get-credentials --admin" and allow "az aks get-credentials"

**Comment by tjprescott** [comment]
Not sure if this is an issue with AKS or the role definition commands. @mboersma can you take a look?

**Comment by yugangw-msft** [comment]
This is should be investigated by AKS since it is the RP itself be responsible for interpreting the role action
//CC: @weinong

**Comment by praveendhac** [comment]
Can I expect fix anytime sooner? Any other way to block clusterAdmin credentials, "_--admin_".

**Comment by weinong** [comment]
You need to update your Azure CLI.
https://medium.com/@weinong/azure-kubernetes-service-built-in-roles-8083b90e7ba
