### ISSUE TITLE
[Help] Appearance of argument groups in help should be different.

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#714]
Currently, argument groups appear in alphabetical order when specifying -h/--help (except that generic Arguments always appears first). A more logical ordering would be:

Resource Id (always required, so being at the top makes it more prominent)
Arguments
Storage Account
Generic Update
Globals

**Comment by BurtBiel** [comment]
We should implement a generic group-index system to customize group ordering.

**Comment by BurtBiel** [comment]
This is fixed
