### ISSUE TITLE
Command az webapp doesn't work (and never did in my mac)

### ISSUE THREAD

**Issue by ClimberBear** [Azure/azure-cli#7144]
I have a Mac with both clients installed
CLI 1.0
azure --version
0.10.10 (node: 4.3.1)

and CLI 2.0
az --version
azure-cli (2.0.4)

But when I try to execute an "az webapp" command, I get the following error
az webapp
az: error: argument _command_package: invalid choice: 'webapp' (choose from 'appservice', 'monitor', 'feedback', 'account', 'batch', 'snapshot', 'acr', 'acs', 'find', 'resource', 'ad', 'lock', 'image', 'container', 'vm', 'tag', 'disk', 'cloud', 'documentdb', 'feature', 'storage', 'configure', 'group', 'network', 'vmss', 'redis', 'logout', 'role', 'provider', 'policy', 'lab', 'keyvault', 'iot', 'component', 'sql', 'login')

(The azure webapp works fine)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2983e943-cce1-effd-57d0-cce4b0c0a7e1
* Version Independent ID: 4262c40a-7140-b420-58b5-5cf40ab2316e
* Content: [az webapp](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/webapp.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/webapp.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
You have an incredibly old version of CLI 2.0.  You are running 2.0.4 and the latest release is 2.0.45.  Try updating your CLI and please reopen if you still cannot access these commands.

**Comment by ClimberBear** [comment]
Thanks!

I don't know why, but my homebrew was not updating correctly the CLI version. After 2 uninistall and reinstall, start working.

Thanks for the anwser!

**Comment by tjprescott** [comment]
No problem.  Glad it is working for you now!
