### ISSUE TITLE
secret-identifier does not support mixed case key vault name

### ISSUE THREAD

**Issue by gertzen** [Azure/azure-cli#7145]
**Describe the bug**
Using the secret-identifier switch with a mixed-case key vault fails to work:
az sf cluster create --secret-identifier https://MyPrivateKeyVault.vault.azure.net/secrets/mycertname/mycertid

However, if you create your key vault with a lowercase name, the following does work:
az sf cluster create --secret-identifier https://myprivatekeyvault.vault.azure.net/secrets/mycertname/mycertid

The problem occurs

**To Reproduce**
Try to create a cluster using an existing mixed-case key vault.

**Expected behavior**
Mixed-case key vault names should be supported since you can easily create mixed case key vaults within the Azure web interface. Additionally, the error shown the user is currently cryptic and unclear unless pull up the python code and review it.

**Additional context**
This problem can be corrected by adding `.lower()` to the vault name comparison in custom.py:1333 so that the new code reads:
`vault = [v for v in vaults if v.name.lower() == vault_name]`

instead of:
`vault = [v for v in vaults if v.name == vault_name]`

**Comment by schaabs** [comment]
@tjprescott This issue appears to be an issue in the sf command module not keyvault should this be reassigned?

**Comment by tjprescott** [comment]
@schaabs yes, good catch!
