### ISSUE TITLE
The error message of "az network traffic-manager profile create" is not friendly

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-cli#7146]
**Describe the bug**

```
$ az network traffic-manager profile create --name TrafficManagerProfile --resource-group ${RESOURCE_GROUP_NAME} --routing-method Performance --unique-dns-name <unique-dns-name>--monitor-protocol TCP --monitor-port 443 --monitor-path null
Operation failed with status: 'Bad Request'. Details: The Monitor Path must be null when using TCP as a monitoring protocol.
```

`The Monitor Path must be null` is not friendly to users.

**Expected behavior**

The error message should be more clear. For example:
```
Operation failed with status: 'Bad Request'. Details: The Monitor Path must be empty string when using TCP as a monitoring protocol.
```

**Comment by tjprescott** [comment]
What you are seeing is the service error, which does expect a null value. However, for the CLI, that simply means don't send that.

We can look at the internal command validation to see if it can be improved.

**Comment by bingosummer** [comment]
If I don't send `--monitor-path`, the default value of `--monitor-path` is `/`.  CLI gives me exactly same error message `Operation failed with status: 'Bad Request'. Details: The Monitor Path must be null when using TCP as a monitoring protocol.`.

My point is that CLI should ask for an empty string instead of `null` for the monitor path.

**Comment by tjprescott** [comment]
Based on this, I would argue that `--monitor-path` should not have any default. This may have been a service-change. Thanks for brining it up.

**Comment by tjprescott** [comment]
This will be fixed in the next release.
