### ISSUE TITLE
creating MySQL linked service throws an error "'Server' cannot be null"

### ISSUE THREAD

**Issue by boseca** [Azure/azure-cli#7152]
**Describe the bug**
Using the PowerShell to create MySQL linked service fails with error "'Server' cannot be null" when linked service is using the Key Vault (KV) for storing the the credentials. Looks like the new JSON payload version for MySQL linked service is not supported yet.  Using the old payload version and storing each property into KV seems to be working. 

**To Reproduce**
1) create Azure Data Factory V2 `my_test_df`
2) create a JSON file `c:\Test_MySQL.json`
`
{
	"name": "Test_MySQL",
	"properties": {
		"type": "MySql",
		"typeProperties": {
			"connectionString": {
				"type": "AzureKeyVaultSecret",
				"store": {
					"referenceName": "AzureKeyVault",
					"type": "LinkedServiceReference"
				},
				"secretName": "MySql-connection-string",
				"secretVersion": ""
			}
		}
	}
}
`
3) run PowerShell to create the MySQL linked service
>Set-AzureRmDataFactoryV2LinkedService -ResourceGroupName "<YOUR RESOURCE GROUP>" -DataFactoryName "my_test_df" -Name "Test_MySQL" -File "c:\Test_MySQL.json" -Force 

4) the result is "Set-AzureRmDataFactoryV2LinkedService : 'Server' cannot be null."

**Expected behavior**
Not having error

**Environment summary**
Used PowerShell
az --version
azure-cli (2.0.44)

acr (2.1.3)
acs (2.3.0)
advisor (0.6.0)
ams (0.2.2)
appservice (0.2.2)
backup (1.2.0)
batch (3.3.2)
batchai (0.4.1)
billing (0.2.0)
cdn (0.1.0)
cloud (2.1.0)
cognitiveservices (0.2.0)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.3)
core (2.0.44)
cosmosdb (0.2.0)
dla (0.2.1)
dls (0.1.0)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.2)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.28)
iot (0.3.0)
iotcentral (0.1.0)
keyvault (2.2.2)
lab (0.1.0)
maps (0.3.1)
monitor (0.2.2)
network (2.2.3)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.0)
redis (0.3.0)
relay (0.1.0)
reservations (0.3.1)
resource (2.1.2)
role (2.1.3)
search (0.1.1)
servicebus (0.2.1)
servicefabric (0.1.1)
sql (2.1.2)
storage (2.2.0)
telemetry (1.0.0)
vm (2.2.1)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\bose.jankulovsk\.azure\cliextensions'

Python (Windows) 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

**Additional context**

**Comment by tjprescott** [comment]
Issues with Powershell commandlets should be filed here:
https://github.com/Azure/azure-powershell
