### ISSUE TITLE
webapp:Single quotes instead of back ticks

### ISSUE THREAD

**Issue by joewilson** [Azure/azure-cli#7154]
Looks like you're using single quotes instead of back ticks for "Name of the webapp. You can configure the default using 'az configure --defaults web='."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e50d77a-f2fa-6d6e-0c57-2f434c12766f
* Version Independent ID: f9a98805-6e16-487a-03ce-237cb964f83c
* Content: [az webapp config](https://docs.microsoft.com/en-us/cli/azure/webapp/config?view=azure-cli-latest#az-webapp-config-show)
* Content Source: [latest/docs-ref-autogen/webapp/config.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/webapp/config.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by kishdubey** [comment]
Shouldn't this be an issue on MicrosoftDocs, as the content source is there?

**Comment by panchagnula** [comment]
I believe the change should go here https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/_params.py#L258

**Comment by panchagnula** [comment]
@kishdubey are you still planning on creating a PR for this issue here?

**Comment by panchagnula** [comment]
@ammanifold can you take care of this along with your existing changes?

**Comment by ammanifold** [comment]
@panchagnula can you please close this issue? I don't have permissions. PR is merged in, but it didn't auto-resolve this.
