### ISSUE TITLE
az vm extension set: autoUpgradeMinorVersion by default

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-cli#716]
I haven't even checked if the CLI has "az vm extension set" command (I'm mobile right now). 

But if there is any, we should make sure when we set extensions we should set autoUpgradeMinorVersion:true by default (and give users a knob to disable it). 

(This is basically the version:1.* feature in ASM)

This is good and PowerShell cmdlets do this too. 

1. It helps our users get highest minor version. 
2. It helps us reduce fragmentation on by offering users to install highest minor version available as they might be reading some old doc.

**Comment by ahmetalpbalkan** [comment]
@yugangw-msft can you please prioritize this one. It would be very preferable to have `--auto-upgrade-minor-version` set to true by default just like powershell does.

This will help my team (who owns almost all 1st party extensions for both Windows and Linux) reduce fragmentation on extension versions and move forward faster. LMK if you want to sync offline.

**Comment by yugangw-msft** [comment]
@ahmetalpbalkan , you know we already exposed it. The change will be to flip the default value. This should be done next week, once I am back to office.

**Comment by ahmetalpbalkan** [comment]
@yugangw-msft thanks a lot! I was just seeking some confirmation that you folks are fine with the change.

**Comment by mayurid** [comment]
To be picked by @yugangw-msft in this sprint

**Comment by yugangw-msft** [comment]
@ahmetalpbalkan, so i will hide the flag and expose the opposite one of `--no-auto-upgrade`, with description: `by doing this, extension system will not pick the highest minor version for the specified version number, and will not auto update to the latest build/revision number on any VM updates in future`
Let me know any comments/suggestions.

**Comment by ahmetalpbalkan** [comment]
sounds good.
