### ISSUE TITLE
Further information on --command-id

### ISSUE THREAD

**Issue by dneelyep** [Azure/azure-cli#7162]
It would be great if this documentation explained in more detail what "The run command ID" means. I was just guessing, and assumed it was an ID that I give to the command, that would later be surfaced in the Azure portal via logging, etc. I spent 3-4 hours playing with the command until I discovered that I literally have to set --comand-id equal to the value "RunShellScript". It would be great if this was clarified to save other people time in the future.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f04b196d-7d11-7213-f037-f12b85b19c52
* Version Independent ID: adc05d8e-b13b-134b-5f61-42aaf23666df
* Content: [az vm run-command](https://docs.microsoft.com/en-us/cli/azure/vm/run-command?view=azure-cli-latest#az-vm-run-command-invoke)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
The new description will be `The command id. Use 'az vm run-command list' to get the list`
