### ISSUE TITLE
How to upload to subfolder of container?

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-cli#7166]
No guidance is shown as to how to create a folder within the container and upload blobs there. Using `az storage blob upload` with a `--name` parameter containing a folder (eg: `--name foo/myfile.txt` doesn't work and errors out on the CLI with `unrecognized arguments`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 472d5f5f-3ce0-1220-3058-4b27068f512b
* Version Independent ID: 76e1699e-e6ba-c0dd-aad4-c5a7ab58260d
* Content: [az storage blob](https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az-storage-blob-upload)
* Content Source: [src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by brandonh-msft** [comment]
Turns out this syntax (`foo/myfile.txt`) works if you use `-n` but **not** if you use `--name`

🤷🏻‍♂️

**Comment by troydai** [comment]
@williexu

**Comment by brandonh-msft** [comment]
another PG was unable to repro (see https://github.com/MicrosoftDocs/azure-docs/issues/14153) but agreed docs should call out how to do this. Hopefully you do as well. thanks!

**Comment by williexu** [comment]
Blob storage is flat storage, unlike file storage which is hierarchical.
Any provided name for a blob with path seperators will simply mimic a folder structure.
If I see frequent questions regarding this, I can clarify in our docs. Closing for now.
