### ISSUE TITLE
az postgres allow access to azure services

### ISSUE THREAD

**Issue by pascalnaber** [Azure/azure-cli#7168]
I want "Allow Access To Azure Services"  to be turned on for a postgres database.
There is no direct option for this in the CLI, but I found out that this can be done by adding a firewall rule with a specific name and ip-address:

az postgres server firewall-rule create -g $(RESOURCEGROUP_DATA_NAME) -s $(DATABASESERVER_NAME) -n "AllowAllWindowsAzureIps" --start-ip-address "0.0.0.0" --end-ip-address "0.0.0.0"

The button in the portal is turned on now. This looks great, but onfortunately it is not working.
After disabling it in the portal and enable it again to make it really working for other services to have access to the database.

**Comment by pascalnaber** [comment]
@tjprescott if you ask me. It is really a bug. But I can't determine if the Azure CLI contains the bug. All I know is when I use the Azure CLI to turn on Allow Access To Azure Serices, it is not working. 
The UI of the portal shows it is turned on. But it isn't.

**Comment by tjprescott** [comment]
Hi @pascalnaber the "Question" label is often used by us to flag a new issue. The service team will need to investigate this and determine how they want to classify it as they maintain these commands.

**Comment by pascalnaber** [comment]
I can confirm that the functionality works when executing an ARM template. So the CLI is not working correct. ARM is doing it correct.

```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "databaseServerName": {
            "type": "string",
            "metadata": {
                "description": "Name of database server"
            }
        }       
    },
    "variables": {
        "databaseServerName": "[parameters('databaseServerName')]"
    },
    "resources": [       
        {
            "type": "Microsoft.DBforPostgreSQL/servers/firewallrules",
            "name": "[concat(variables('databaseServerName'), '/AllowAllWindowsAzureIps')]",
            "apiVersion": "2017-12-01",
            "properties": {
                "startIpAddress": "0.0.0.0",
                "endIpAddress": "0.0.0.0"
            }
        }
    ]
}
```

**Comment by anilpras** [comment]
@tjprescott, @pascalnaber 
For us we have seen the issue with ARM template deployment triggered via CLI as well.
here is the used template: https://commontemplates.blob.core.windows.net/postgres/2.2/azuredeploy.json

**Comment by rachel-msft** [comment]
This has been resolved in the latest release.

@tjprescott please close.

**Comment by paulmwatson** [comment]
Can confirm this worked for me with az cli 2.18.0 e.g. 
```
az postgres server firewall-rule create --resource-group RG --server-name SN --name "AllowAllLinuxAzureIps" --start-ip-address "0.0.0.0" --end-ip-address "0.0.0.0"
```
