### ISSUE TITLE
`Az network vnet peering create` fails with error: "KeyError: 'subscription'"

### ISSUE THREAD

**Issue by QuinnDamerell-MS** [Azure/azure-cli#7169]
**Describe the bug**
When I try to run `az network vnet peering create` I get an error, see below.

**To Reproduce**
> ~/» az network vnet peering create -g resource -n test --vnet-name vnet1 --remote-vnet-id vnet2 --verbose --debug
> Event: Cli.PreExecute []
> Event: CommandParser.OnGlobalArgumentsCreate [<function on_global_arguments at 0x7f78969f9758>, <function on_global_arguments at 0x7f78960d09b0>, <function on_global_arguments at 0x7f78960e60c8>]
> Event: CommandInvoker.OnPreCommandTableCreate [<function remove_logger_flags at 0x7f78969f97d0>]
> Installed command modules ['acr', 'acs', 'advisor', 'ams', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'interactive', 'iot', 'iotcentral', 'keyvault', 'lab', 'maps', 'monitor', 'network', 'policyinsights', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'servicebus', 'servicefabric', 'sql', 'storage', 'vm']
> Loaded module 'acr' in 0.003 seconds.
> Loaded module 'acs' in 0.002 seconds.
> Loaded module 'advisor' in 0.001 seconds.
> Event: CommandLoader.OnLoadCommandTable []
> Loaded module 'ams' in 0.005 seconds.
> Loaded module 'appservice' in 0.006 seconds.
> Loaded module 'backup' in 0.002 seconds.
> Event: CommandLoader.OnLoadCommandTable []
> Loaded module 'batch' in 0.015 seconds.
> Loaded module 'batchai' in 0.003 seconds.
> Loaded module 'billing' in 0.001 seconds.
> Loaded module 'botservice' in 0.004 seconds.
> Event: CommandLoader.OnLoadCommandTable []
> Loaded module 'cdn' in 0.003 seconds.
> Loaded module 'cloud' in 0.001 seconds.
> Loaded module 'cognitiveservices' in 0.001 seconds.
> Loaded module 'configure' in 0.000 seconds.
> Loaded module 'consumption' in 0.007 seconds.
> Loaded module 'container' in 0.001 seconds.
> Loaded module 'cosmosdb' in 0.003 seconds.
> Loaded module 'dla' in 0.004 seconds.
> Loaded module 'dls' in 0.002 seconds.
> Loaded module 'dms' in 0.002 seconds.
> 
> ...
> 
> Loaded module 'servicebus' in 0.005 seconds.
> Loaded module 'servicefabric' in 0.001 seconds.
> Loaded module 'sql' in 0.006 seconds.
> Event: CommandLoader.OnLoadCommandTable []
> Loaded module 'storage' in 0.028 seconds.
> Loaded module 'vm' in 0.013 seconds.
> Loaded all modules in 0.196 seconds. (note: there's always an overhead with the first module loaded)
> Extensions directory: '/home/user/.azure/cliextensions'
> Event: CommandInvoker.OnPreCommandTableTruncate []
> Event: CommandInvoker.OnPostCommandTableCreate [<function add_id_parameters at 0x7f7895e1ab18>, <function add_subscription_parameter at 0x7f7895e30848>]
> Event: CommandInvoker.OnCommandTableLoaded []
> Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7f7895b11320>]
> Event: CommandInvoker.OnPostParseArgs [<function handle_output_argument at 0x7f78960d0a28>, <function handle_query_parameter at 0x7f78960e6140>, <function parse_subscription_parameter at 0x7f7895e308c0>, <function handler at 0x7f7895a630
> 50>]
> 'subscription'
> Traceback (most recent call last):
>   File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 197, in invoke
>     cmd_result = self.invocation.execute(args)
>   File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
>     six.reraise(*sys.exc_info())
>   File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
>     result = cmd(params)
>   File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
>     return self.handler(*args, **kwargs)
>   File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
>     result = op(**command_args)
>   File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/command_modules/network/custom.py", line 2937, in create_vnet_peering
>     aux_subscription = parse_resource_id(remote_virtual_network)['subscription']
> KeyError: 'subscription'
> Suppress exception Return value is not string
> telemetry.save : Save telemetry record of length 2454 in cache

**Expected behavior**
It should work. :)

**Environment summary**
Yum installed latest CLI version on Centos.

> ~/» az --version                                                                                                                                                                                            azure-cli (2.0.45)
> 
> acr (2.1.4)
> acs (2.3.2)
> advisor (0.6.0)
> ams (0.2.3)
> appservice (0.2.3)
> backup (1.2.1)
> batch (3.3.3)
> batchai (0.4.2)
> billing (0.2.0)
> botservice (0.1.0)
> cdn (0.1.1)
> cloud (2.1.0)
> cognitiveservices (0.2.1)
> command-modules-nspkg (2.0.2)
> configure (2.0.18)
> consumption (0.4.0)
> container (0.3.3)
> core (2.0.45)
> cosmosdb (0.2.1)
> dla (0.2.2)
> dls (0.1.1)
> dms (0.1.0)
> eventgrid (0.2.0)
> eventhubs (0.2.3)
> extension (0.2.1)
> feedback (2.1.4)
> find (0.2.12)
> interactive (0.3.28)
> iot (0.3.1)
> iotcentral (0.1.1)
> keyvault (2.2.2)
> lab (0.1.1)
> maps (0.3.2)
> monitor (0.2.3)
> network (2.2.4)
> nspkg (3.0.3)
> policyinsights (0.1.0)
> profile (2.1.1)
> rdbms (0.3.1)
> redis (0.3.2)
> relay (0.1.1)
> reservations (0.3.2)
> resource (2.1.3)
> role (2.1.4)
> search (0.1.1)
> servicebus (0.2.2)
> servicefabric (0.1.2)
> sql (2.1.3)
> storage (2.2.1)
> telemetry (1.0.0)
> vm (2.2.2)
> 
> Python location '/usr/lib64/az/bin/python'
> Extensions directory '/home/user/.azure/cliextensions'
> 
> Python (Linux) 2.7.5 (default, Jul 13 2018, 13:06:57)
> [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
> 
> Legal docs and information: aka.ms/AzureCliLegal

**Comment by QuinnDamerell-MS** [comment]
I tried clearing out my ~./azure folder and also reinstalling the CLI tools.

**Comment by QuinnDamerell-MS** [comment]
Oh, actually I figured out half of it. `--remote-vnet-id` is expecting a full id path like `/subscriptions/xxxx-xxx-xxxx-xxxx-xxxxxxx/resourceGroups/thing/providers/Microsoft.Network/virtualNetworks/name` but it seems to crash the script if it doesn't get that.

**Comment by emirhosseini** [comment]
@QuinnDamerell-MS Where can I find that full path? I don't see it anywhere

**Comment by emirhosseini** [comment]
Found it, it's under "Properties" inside the vnet settings page. Here's a sample command that worked for me. Note that only the remote-vnet has to have the long path (not both vnets)

`az network vnet peering create -g groupname -n newvnetname --vnet-name firstvnet --remote-vnet /subscriptions/223423-2342234-34-234-24/resourceGroups/YourResourceGroup/providers/Microsoft.Network/virtualNetworks/secondvnetname --allow-vnet-access --allow-forwarded-traffic --subscription subscriptionnameorid`

**Comment by tjprescott** [comment]
@emirhosseini without going to the portal you can just run:
`az network vnet show -g {rg} -n {name} --query "id"`

Also, now the remote Vnet should not require an ID provided both vnets are in the same resource group and subscription.
