### ISSUE TITLE
How to grant extra permissions with az ad app update

### ISSUE THREAD

**Issue by tumluliu** [Azure/azure-cli#7177]
First of all, is it possible to do this with this command? If yes, how to do that, e.g. if I want to grant Windows Active Directory -&gt; Read Directory Data permission to a specific App? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 921aa920-c25f-5227-aabb-49116da38fa7
* Version Independent ID: 9b5a53ad-edf8-4d89-f8e6-cde01b7866f6
* Content: [az ad app](https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest#az-ad-app-update)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
Not a very smooth experience, but you can do it though `az ad app update` by providing the manifest artifacts

**Comment by yugangw-msft** [comment]
okay, i will expose `az ad app permission add` to get it simpler. 
Please note, in the latest release, you will see "az ad app permission grant" which does the same thing of the `grant permissions` button in the portal. The new add command will default to grant unless you opt out with the flag of `--no-grant`

**Comment by tumluliu** [comment]
that would be much better! Many thanks @yugangw-msft !

**Comment by tumluliu** [comment]
@yugangw-msft could you disclose which version of az cli will contain this feature? For now, it's not available yet in `2.0.49`

**Comment by paolosalvatori** [comment]
Hi, I have a couple of related questions: it looks like when running:

az ad app permission grant --id 9f4f64e0-4fd4-4a22-bbd2-b0ccd814f569 --api 00000003-0000-0000-c000-000000000000

none of the permissions at scope and role level that I added to my app registration / service principal using the az ad app permission add  command get granted :( Only if I specify the --scope flag (e.g. --scope User.Read) they get granted. But here is the deal: the documentation at https://docs.microsoft.com/en-us/cli/azure/ad/app/permission?view=azure-cli-latest#az-ad-app-permission-grant does not explain how to use the scope parameter to specify a list of delegated and application permissions. in addition, you said above: The new add command will default to grant unless you opt out with the flag of --no-grant. Is this feature already available? If yes, starting from which version? Thanks!

**Comment by yugangw-msft** [comment]
@paolosalvatori, PR was merged, please use `az ap app permission admin-consent`
