### ISSUE TITLE
"azdev test" no longer works with older profiles.

### ISSUE THREAD

**Issue by williexu** [Azure/azure-cli#7179]
**Describe the bug**
"azdev test" no longer works with older profiles; no tests are detected.

**To Reproduce**
run `azdev test` in a different profile than latest

**Comment by tjprescott** [comment]
Yugang just used it a week or so ago and it worked fine.  Was there a recent commit that broke things?

**Comment by williexu** [comment]
Yeah, was probably https://github.com/Azure/azure-cli/commit/ba221523b20f6f71efb5f3a88a38bb0aab03d6f1#diff-4429e8851f9476cda0d91743e74ef970
