### ISSUE TITLE
ExpressRoute Global Reach

### ISSUE THREAD

**Issue by charwen** [Azure/azure-cli#7181]
**Is your feature request related to a problem? Please describe.**
We added a new capability to ExpressRoute, which is an Azure networking service for a few years. We added a few APIs to configure the new capability. 

**Describe the solution you'd like**
We need the CLI support. 

**Describe alternatives you've considered**
We already added the feature support in PowerShell.

**Additional context**
The new capability is not supported in Azure Portal yet.

**Comment by tjprescott** [comment]
Questions:
1. What is the link to the relevant Swagger?
2. Is this a feature specifically for Ignite?

**Comment by charwen** [comment]
@tjprescott  the swagger is here: https://github.com/Azure/azure-rest-api-specs/blob/7b95fd70c37943bd88eac39b3e7f1e4d4ab295ed/specification/network/resource-manager/Microsoft.Network/stable/2018-07-01/expressRouteCircuit.json#L453

we plan to announce public preview for this feature.
