### ISSUE TITLE
Update & enable bot service app test with the new azure-mgmt-web module

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-cli#7184]
The following change has disabled  test https://github.com/Azure/azure-cli/pull/7135 for bot app, please re-record & publish with the test enabled. See the PR for more details

**Comment by troydai** [comment]
@swagatmishra2007 please get on this issue at your convenience.

**Comment by troydai** [comment]
@panchagnula what's the status of this issue?

**Comment by troydai** [comment]
It is done.
