### ISSUE TITLE
Inconistent behaviour

### ISSUE THREAD

**Issue by john-louden** [Azure/azure-cli#7185]
**Describe the bug**
 When adding a NSG rule  that has a source of AzureLoadbalancer in a inbound direct it adds successfully. When you when add an rule that has a destination of Azureloadbalancer and the direction is outbound, BUT THE SAME RULE NAME the previous rule is silently deleted.

If you attempt to do the same in the portal an error is returned and the command can not proceed.

**To Reproduce**
Steps to reproduce the behaviour.

az network nsg rule create -g <ResourceGroup> --nsg-name <NSGName> -n Allow_AzureLoadbalancer --access Allow --source-address-prefixes AzureLoadBalancer --destination-port-ranges * --direction Inbound  --destination-address-prefixes <SubnetRange> --priority 900

 then run

az network nsg rule create -g <ResourceGroup> --nsg-name nsg-apppublic -n Allow_AzureLoadbalancer --access Allow --source-address-prefixes <subnet ip>  --destination-port-ranges * --direction Outbound  --destination-address-prefixes AzureLoadBalancer --priority 900

The output of the secondary command reports a success, while the first rule is removed

**Expected behavior**
I would expect the second command to fail with an error "Name in use" similar to the portal

**Environment summary**
AZ clie
Powershell
Win10 insider Ringer (Fast)

**Additional context**

**Comment by tjprescott** [comment]
Consistency with another tool such as Powershell commandlets or the portal is not a significant factor in the CLI design. CLI create commands are intended to be idempotent. Were this command to fail because the name is reused, the `nsg rule create` command would no longer be idempotent.
