### ISSUE TITLE
webapp config container set with slot returns main config not slot config

### ISSUE THREAD

**Issue by john681611** [Azure/azure-cli#7186]
**Describe the bug**
When updating a container configuration slot it returns the main config instead of the slot config. (known when changing image)

**To Reproduce**
1. Setup webapp container with a deployment slot
2. Run `az webapp config container set -n <app> -g <group> -s <slot> -i <newImage>

**Expected behavior**
config should be of the slot not of its parent prod 

**Environment summary**
Docker, linux, concourse

**Comment by john681611** [comment]
> Looks like it also doesn't actually update the slot as well.

It was working ok for me.

I'm happy to help out I just need some direction to find the command to fix.

**Comment by BenWalters** [comment]
@john681611 I had the same issue I believe - [Issue 8808](https://github.com/Azure/azure-cli/issues/8808)
Solution for me was to upgrade from 2.0.52 to 2.0.60.

**Comment by panchagnula** [comment]
Unable to repro this one - please upgrade to the latest CLI version & re-try. Thank you.
