### ISSUE TITLE
Subcommand managementgroups does not exist.

### ISSUE THREAD

**Issue by Always-Wright** [Azure/azure-cli#7187]
The examples use the following:
az managementgroups group update --group-name GroupName --display
This does not exist in the Azure CLI, it should be "az management-group"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01f8fe72-48f6-2e30-0741-d83bafc5d438
* Version Independent ID: 32ed6908-2c71-3c17-683b-d07eb08d4590
* Content: [az account management-group](https://docs.microsoft.com/en-us/cli/azure/ext/managementgroups/account/management-group?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/managementgroups/account/management-group.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/ext/managementgroups/account/management-group.yml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
This should be in the https://github.com/Azure/azure-cli-extensions repo since managment groups is an extension. I've created an issue there.
