### ISSUE TITLE
az lab formula create?

### ISSUE THREAD

**Issue by drwhite729** [Azure/azure-cli#7189]
Is there no way to create a formula from the CLI?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 008e6968-b442-d726-71e5-831fbf0b35ca
* Version Independent ID: 6c2b5e54-0259-fa74-b5cc-a0549526932d
* Content: [az lab formula](https://docs.microsoft.com/en-us/cli/azure/lab/formula?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-lab/azure/cli/command_modules/lab/_help.py)
* Service: **devtest-lab**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Currently you can only create formulas using an ARM template.
