### ISSUE TITLE
Wrong documnetation for "--source-asgs" parameter of “az network nsg rule” command

### ISSUE THREAD

**Issue by stprokho** [Azure/azure-cli#7197]
**Describe the bug**
https://docs.microsoft.com/en-us/cli/azure/network/nsg/rule?view=azure-cli-latest article says:
"--source-asgs 
Space-separated list of application security group names or IDs." 
Which in fact is not supported by CLI and following error being returned: 
"A security rule may have up to 1 Application Security Group in the source or destination fields. The requested configuration has 2 in the SourceApplicationSecurityGroups field."

**To Reproduce**
Issue can be reproduced if you run "az network nsg rule create" and assign two or more space separated ASGs via "--source-asgs" parameter

**Expected behavior**
There are two options:
- Both ASGs should be assigned as per documentation.
- documentation should be updated saying that only single ASG can be assigned

**Environment summary**
Any

**Additional context**
N/A

**Comment by tjprescott** [comment]
This feature is not supported by the service but is how their object is modeled.

**Comment by chandrasekarsrinivasan** [comment]
I'll have a look and get back.

**Comment by chandrasekarsrinivasan** [comment]
@tjprescott  can you please update the documentation in CLI?

**Comment by MyronFanQiu** [comment]
@malopMSFT @chandrasekarsrinivasan Does it still support only one source or destination?

**Comment by MyronFanQiu** [comment]
@malopMSFT Thanks. I will update the documentation soon.
