### ISSUE TITLE
az login --service-principal --terraform

### ISSUE THREAD

**Issue by richeney** [Azure/azure-cli#7198]
# Description

It would be nice to have an additional --terraform switch for  **az login** to pull in Terraform AzureRM provider service principal credentials, as per https://www.terraform.io/docs/providers/azurerm/authenticating_via_service_principal.html. 

These would either be exported environment variables, or a provider stanza from a *.tf file in the current directory.  

## Environment variables

Empty provider stanza in *.tf file:
```ruby
provider "azurerm" {}
```

Example environment variables:
```bash
export ARM_SUBSCRIPTION_ID="2d31be49-d959-4415-bb65-8aec2c90ba62"
export ARM_CLIENT_ID="c8adcaf8-9277-4307-965b-5904ba4afa8d"
export ARM_CLIENT_SECRET="0aad251a-f964-4628-a549-e1800d848146"
export ARM_TENANT_ID="72f988bf-86f1-41af-91ab-2d7cd011db47"
```

## Populated provider stanza

Example populated provider stanza in one of the *.tf file:
```ruby
provider "azurerm" {
  subscription_id = "2d31be49-d959-4415-bb65-8aec2c90ba62"
  client_id       = "c8adcaf8-9277-4307-965b-5904ba4afa8d"
  client_secret   = "4b372434-29eb-428d-8c90-fd67991dd086"
  tenant_id       = "72f988bf-86f1-41af-91ab-2d7cd011db47"
}
```

**Comment by marstr** [comment]
Howdy @richeney,

I'm surprised about the directionality you're looking for here. In the past when I've used terraform, I've tried to isolate these credentials so that they're actively not in my `*.tf` files. To those ends, I was way more likely to want terraform to be able to read from my `az` token cache than the other way around. (Which, I believe is supported today.)

Could you tell me more about your scenario, and why you prefer to have `az` read from terraform?

**Comment by richeney** [comment]
Hi @marstr,

A nice and simple scenario.  If I have a service principal set up for Terraform with a custom role then it is useful to be able to log on with those credentials to prove what it can and cannot do.  

If there is an easy way to pull that from existing az tokens then that is great and excuse my ignorance for not knowing how you achieve that!

**Comment by yonzhan** [comment]
add to S165.

**Comment by jiasli** [comment]
Hi @richeney, I agree with @marstr that Terraform should read from CLI's token cache, instead of the other way around. 

Could you check if this doc from Terraform suits your needs? https://www.terraform.io/docs/providers/azurerm/guides/azure_cli.html

**Comment by mpagot** [comment]
Last comment link seems no more valid. Maybe now it is https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/azure_cli.html. Could you confirm?

**Comment by richeney** [comment]
Yep it redirects.

Looking back, this was not one of my better ideas!
