### ISSUE TITLE
az .... --help crashes if there is a choice list containing integers

### ISSUE THREAD

**Issue by johanste** [Azure/azure-cli#720]
From _help.py, line 162-167, issue in **bold**:

def _get_choices_defaults_str(p):
    choice_str = '  Allowed values: {0}.'.format(**', '.join(p.choices)**) \
        if p.choices else ''
    default_str = '  Default: {0}.'.format(p.default) \
        if p.default and p.default != argparse.SUPPRESS else ''
    return '{0}{1}'.format(choice_str, default_str)

**Comment by BurtBiel** [comment]
it sounds like we should have the help object convert choices to string when they are first set

**Comment by tjprescott** [comment]
Merged PR #724
