### ISSUE TITLE
az login: error: cannot import name 'TYPE_CHECKING'

### ISSUE THREAD

**Issue by michael0806** [Azure/azure-cli#7208]
I already installed Homebrew and Azure CLI. However, I cannot log in by using mt terminal.
Shows like below:
sunsunmingweideMacBook-Pro:~ sunmingwei$ az login
usage: az login [-h] [--verbose] [--debug]
                [--output {json,jsonc,table,tsv,yaml}] [--query JMESPATH]
                [--tenant TENANT] [--subscription _SUBSCRIPTION]
                [--username USERNAME] [-i] [--use-device-code]
                [--password PASSWORD] [--allow-no-subscriptions]
                [--service-principal]
az login: error: cannot import name 'TYPE_CHECKING'

**Comment by tjprescott** [comment]
Please open a new issue and provide the required information.
