### ISSUE TITLE
Can't create cognitiveservice for QnaMaker via CLI because missing qnaRuntimeEndpoint.

### ISSUE THREAD

**Issue by tomlm** [Azure/azure-cli#7209]
**Describe the bug**
When you try to use az cli to create a QnAMaker cognitive service it fails because of missing qnaRuntimeEndpoint

**To Reproduce**
```
az cognitiveservices account create -g Group1 --kind QnAMaker -n testQnaxxx --sku F0 --location westus --yes.
```
outputs error
```
(ApiPropertiesInvalid) The given 'apiProperties' '{}' is invalid. Validation errors: Required properties are missing from object: qnaRuntimeEndpoint. Path ''.
```

**Expected behavior**
It should provision the cognitive service

**Environment summary**
windows 10
azure-cli (2.0.45)
cognitiveservices (0.2.1)

**Comment by cloudguy-pro** [comment]
Did you try the commands documented here: https://github.com/Azure/azure-cli/issues/6888#issuecomment-417817480

**Comment by ChrisHMSFT** [comment]
Hi @tomlm ,

Closing the issue. The commands documented above are correct

Thanks,
Chris
