### ISSUE TITLE
route-table behaviour different

### ISSUE THREAD

**Issue by john-louden** [Azure/azure-cli#7210]
**Describe the bug**
Inconsistency  between cli and portal with the command az vnet subnet update --route-table. In the portal if you attempt to associate a subnet that already has a route table associated with it it is greyed out. Using the CLI no error is returned, the existing associational is silently deleted and a new association is created.

**To Reproduce**
Via the portal 
1./ Open the route-table
2./ Select subnet section from the middle plane
3./ Click the associate button.
4./ Select the right vnet 
5./  Click on subnet
6./ All subnets that have  route table are dimmed out. Not possible to select

via Cli  run the following

az network vnet subnet update -n <Subnet Name> --vnet-name <vnet-name> -g <Resourcegroup> --route-table <routetable>

Not error is returned, provisioning state = succeeded.

**Expected behavior**
I would expect an error returned saying the subnet already has an associated route table.

**Environment summary**
AZ CLI 2.x plus powershell win10

**Additional context**

**Comment by tjprescott** [comment]
This is the service behavior--it would be the portal that is inconsistent. I'll refer this to the service team in case they would like to make this an error case in the service.

**Comment by MyronFanQiu** [comment]
@Chandrasekar Srinivasan Any update for this issue?

**Comment by MyronFanQiu** [comment]
@chandrasekarsrinivasan Any update for this issue?
