### ISSUE TITLE
AKS cluster creation fails with 'too many 504 error responses'

### ISSUE THREAD

**Issue by sameersbn** [Azure/azure-cli#7211]
**Describe the bug**

Creating AKS cluster using the `az` client errors out with the following message

```
ERROR: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/****/resourceGroups/my-resource-gp/providers/Microsoft.ContainerService/managedClusters/my-aks-cluster?api-version=2018-03-31 (Caused by ResponseError('too many 504 error responses',))
```

**To Reproduce**

I have been seeing this issue while creating aks clusters with k8s version `1.9.10` as well as `1.8.14`. 

```bash
az aks create --verbose --resource-group my-resource-gp --name my-aks-cluster --node-count 3 --node-vm-size Standard_DS2_v2 --location eastus --kubernetes-version 1.9.10 --generate-ssh-keys --service-principal **** --client-secret ****
```

**Expected behavior**

The cluster should get created

**Environment summary**

apt-get / 2.0.45 / Ubuntu 18.04 / bash

**Additional context**

In some instances the cluster gets created, but the same errors are observed with other commands such as

```
az aks get-credentials --name my-aks-cluster --resource-group my-resource-gp
```

https://pastebin.com/6LMVWzYq contains the command log with `--debug` flag specified while creating the cluster.

**Comment by sameersbn** [comment]
another instance of the error https://pastebin.com/9CqXE2az

**Comment by jluk** [comment]
This has greatly improved since issue opened so closing as a result. If continues please open a support ticket with AKS as it's unlikely the CLI is the culprit of a 504 create error.
