### ISSUE TITLE
[Network] Traffic Manager commands are missing parameters

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#7213]
**Describe the bug**
'az network traffic-manager profile' commands are missing support for various parameters introduced in https://azure.microsoft.com/en-us/roadmap/fast-failover-and-tcp-probing-in-azure-traffic-manager/

Specifically, MonitorIntervalInSeconds, MonitorTimeoutInSeconds, MonitorToleratedNumberOfFailures are not supported

**To Reproduce**
az network traffic-manager profile create -h
Compare supported parameters to the REST spec for Traffic Manager or the equivalent PS command New-AzureRmTrafficManagerProfile

**Expected behavior**
Add support for missing parameters and update help

**Environment summary**
Cloud Shell

**Additional context**
none

**Comment by tjprescott** [comment]
This fix will be features in the next release.

**Comment by jtuliani** [comment]
Thank you!
