### ISSUE TITLE
azure cli create failover groups :Grace period value should not be provided when failover policy Manual is selected for the read-write endpoint.

### ISSUE THREAD

**Issue by Joyw1** [Azure/azure-cli#7215]
**Describe the bug**
Use Azure CLI to create failover group, `az sql failover-group create` , I have not passed the `--grace-period`, but it gives the error. Also I use the `az sql failover-group update` to set it to `Manual`, it gives the same error.

[![enter image description here][1]][1]

[![enter image description here][2]][2]

  [2]: https://i.stack.imgur.com/jgEsl.png

  [1]: https://i.stack.imgur.com/UOghe.png
**To Reproduce**
You could refer to the above screenshots.

**Expected behavior**
I want to create the  failover group with `--failover-policy Manual `.

**Environment summary**
OS type: windows 10
CLI version: 
[![enter image description here][3]][3]

  [3]: https://i.stack.imgur.com/IuA88.png

**Comment by archmangler** [comment]
What was the solution to this issue?
