### ISSUE TITLE
az acs kubernetes get-credentials fails error Incompatible ssh peer (no acceptable kex algorithm)

### ISSUE THREAD

**Issue by bhushangholave** [Azure/azure-cli#7216]
Describe the bug
successfully login using 
```
az login --service-principal -u ${CLIENT_ID} -p ${SECRET_KEY} --tenant ${TENENT_ID}
but next command to get credentials
```
`az acs kubernetes get-credentials --resource-group=${RESOURCE_GROUP_NAME} --name=${CLUSTER_NAME} -f ${LOCAL_CONFIG_DIR}/kube_config --ssh-key-file ${SSH_FILE_PATH}`

This fails with error
Incompatible ssh peer (no acceptable kex algorithm)
Traceback (most recent call last):
 File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
   cmd_result = self.invocation.execute(args)
 File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
   six.reraise(*sys.exc_info())
 File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
   raise value
 File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
   result = cmd(params)
 File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
   return self.handler(*args, **kwargs)
 File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
   result = op(**command_args)
 File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 955, in k8s_get_credentials
   _k8s_get_credentials_internal(name, acs_info, path, ssh_key_file)
 File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/custom.py", line 976, in _k8s_get_credentials_internal
   '.kube/config', path_candidate, key_filename=ssh_key_file)
 File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acs/acs_client.py", line 72, in secure_copy
   ssh.connect(host, username=user, pkey=pkey, sock=proxy)
 File "/opt/az/lib/python3.6/site-packages/paramiko/client.py", line 392, in connect
   t.start_client(timeout=timeout)
 File "/opt/az/lib/python3.6/site-packages/paramiko/transport.py", line 545, in start_client
   raise e
 File "/opt/az/lib/python3.6/site-packages/paramiko/transport.py", line 1933, in run
   self._handler_table[ptype](self, m)
 File "/opt/az/lib/python3.6/site-packages/paramiko/transport.py", line 2031, in _negotiate_keys
   self._parse_kex_init(m)
 File "/opt/az/lib/python3.6/site-packages/paramiko/transport.py", line 2175, in _parse_kex_init
   raise SSHException('Incompatible ssh peer (no acceptable kex algorithm)') # noqa
paramiko.ssh_exception.SSHException: Incompatible ssh peer (no acceptable kex algorithm)'.

To Reproduce
create acs cluster
az login
az acs kubernetes get-credentials

Expected behavior
I was getting kubeconfig file and suddenly it stops working with this error

Environment summary
Installed azure-cli from
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest

CLI version and info

azure-cli (2.0.45)

acr (2.1.4)
acs (2.3.2)
advisor (0.6.0)
ams (0.2.3)
appservice (0.2.3)
backup (1.2.1)
batch (3.3.3)
batchai (0.4.2)
billing (0.2.0)
botservice (0.1.0)
cdn (0.1.1)
cloud (2.1.0)
cognitiveservices (0.2.1)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.3)
core (2.0.45)
cosmosdb (0.2.1)
dla (0.2.2)
dls (0.1.1)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.3)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.28)
iot (0.3.1)
iotcentral (0.1.1)
keyvault (2.2.2)
lab (0.1.1)
maps (0.3.2)
monitor (0.2.3)
network (2.2.4)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.1)
redis (0.3.2)
relay (0.1.1)
reservations (0.3.2)
resource (2.1.3)
role (2.1.4)
search (0.1.1)
servicebus (0.2.2)
servicefabric (0.1.2)
sql (2.1.3)
storage (2.2.1)
telemetry (1.0.0)
vm (2.2.2)

Python location '/opt/az/bin/python3'
Extensions directory '/home/bhushan/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Aug 22 2018, 23:14:28)
[GCC 7.2.0]

Legal docs and information: aka.ms/AzureCliLegal
Additional context
I tried updating az-cli-acs version 
Also tried updating paramiko with version 2.0.2 
Followed instruction given in 
[https://stackoverflow.com/questions/7286929/paramiko-incompatible-ssh-peer-no-acceptable-kex-algorithm](https://stackoverflow.com/questions/7286929/paramiko-incompatible-ssh-peer-no-acceptable-kex-algorithm)
but still I am getting same error

**Comment by bhushangholave** [comment]
Hi @brendandburns ,

Thank you for your response.
Solution you suggested need ssh to master, but as i understand this is Paas service offering for Kubernetes from Azure and It should give us config from service itself.
If we require to ssh or scp to master VM we are going inside infra and doing changes.
Anyways but we integrated this Paas service in product.. now for this change we cannot do it manually.

**Comment by harshaperera532** [comment]
The release notes for 2.0.47 include  - Fixed to fall back to 'scp' when Parimiko fails'. Is this meant to fix this issue? I am running the CLI on Win 2016 and scp is available as a command (open ssh is on the path). I am still seeing this issue.

**Comment by smironov** [comment]
I am using 2.0.51.
Still have the same problem, following official Microsoft tutorial and all commands from there.

Does anyone in the world even use Kubernetes on Azure? The bug was reported on Sep 4th and now is what, end of November?

So Microsoft way...

**Comment by bat9r** [comment]
The same command and error :(
I using azure-cli (2.0.52)

**Comment by bhushangholave** [comment]
HI @bat9r,

Your solution supposed to do a manual steps for ACS paas service.
When we are provisioning multiple clusters using automation we cannot use this solution to login master every time.
Thanks,
Bhushan

**Comment by yugangw-msft** [comment]
closing as `az acs` is deprecating
