### ISSUE TITLE
Provide better way for developer tooling to obtain authorization 

### ISSUE THREAD

**Issue by nphmuller** [Azure/azure-cli#7217]
**Is your feature request related to a problem? Please describe.**
A pretty complicated part of using developer tooling which uses Azure is authentication. 
I currently see 3 patterns how tooling obtains credentials:

- Call `az ad sp create-for-rbac -n "<app_name>"` and set the credentials in 3 env vars (`AZURE_TENANT_ID`, `AZURE_CLIENT_ID` and `AZURE_CLIENT_SECRET`).
I consider this unsafe (for developer tooling), because a lot of programs on my system seem to send the environment variables through telemetry, which would send my Azure credentials to them.

- Call `az ad sp create-for-rbac --sdk-auth > client_credentials.json` and create the env var `AZURE_AUTH_LOCATION` pointing to the location of the file.
This is at least safer, but still a bit cumbersome. I simply want to use the identity that I logged into Azure CLI with already. Why do I need to create a new SP? And why doesn't Azure CLI create the file in a default location automatically? Or at least set the env var automatically?

- Make sure you're logged in with `az login` and the tooling automatically re-uses the credentials.
This is by far the easiest option but current implementations are hacky and unconcise.
Examples:
   - The Azure SDK for .NET simply calls the Azure CLI executable and parses the result. Sounds brittle but I found it working fine in practice. You can't really expect every tool to implement this though, because it's not that easy.
   - The Azure SDK for Python simply calls the Azure CLI Python code. This works great, but only for Python projects, since the languages have to match.

**Describe the solution you'd like**
I would like a way for tooling to use the account I used to log in with `az login`. Preferably through a file (in for example `~/.azure/credentials`) and not through env vars.

**Additional context**
If we compare the Azure experience with the AWS experience, the latter one is much easier and developer friendly. All developer tooling that needs to call the AWS API simply reads the file `~/.aws/credentials` and uses the credentials in it. The AWS CLI creates this file with the command `aws configure` which is the AWS equivalent of `az login`.

Take for example a look at this project: https://github.com/mozilla/sops
It's way more complicated for a developer to configure [Azure KeyVault](https://github.com/mozilla/sops#encrypting-using-azure-key-vault) than it is to configure [AWS KMS](https://github.com/mozilla/sops#2usage).

**Comment by yugangw-msft** [comment]
This should be handled by the on-going creds sharing effort. //CC: @marstr  @devigned

**Comment by yugangw-msft** [comment]
The latest azure-core from Azure SDK team should contain the efforts heading to the direction you called out. I am closing this as this is no longer a Azure CLI specific work.

**Comment by nphmuller** [comment]
@yugangw-msft Do you perhaps have a link to the place or the docs I can check to find out more about this?
