### ISSUE TITLE
az command schema

### ISSUE THREAD

**Issue by KirkMunro** [Azure/azure-cli#7218]
**Is your feature request related to a problem? Please describe.**
I'd like to build a converter to generate the PowerShell equivalent of az commands, but I don't have a schema document to work from.

**Describe the solution you'd like**
I would like one or more schema documents that describes all of the az command line options available.

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by tjprescott** [comment]
There is no 1-to-1 mapping between CLI and Powershell. Closing this issue.

**Comment by KirkMunro** [comment]
@tjprescott I know there is no 1-to-1 mapping, but why does that matter? This request is for schema documents describing the az command line options. I can figure out the mapping to the PowerShell equivalent (which may be a one-liner, or multiple lines, but that doesn't matter) from there. Without said schema, all I have is the [az docs](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest), but a schema would be much more useful.

**Comment by KirkMunro** [comment]
That's helpful, thanks @tjprescott!
