### ISSUE TITLE
CLI v2 for recently merged Swagger (Cortex ExR gateways)

### ISSUE THREAD

**Issue by jjaviercv-msft** [Azure/azure-cli#7219]
Have a Swagger [PR](https://github.com/Azure/azure-rest-api-specs/pull/3776) merged. Please add this feature to CLIv2 as soon as possible. This should be released as part of the September release, so we need to make changes to Swagger - if any - by 9/6/2018.

Thank you!

**Comment by troydai** [comment]
Will be implemented as extension.

**Comment by tjprescott** [comment]
Extension has been released.
