### ISSUE TITLE
az ad sp create fails with "Max retries exceeded"

### ISSUE THREAD

**Issue by schoren** [Azure/azure-cli#7220]
**Describe the bug**
When trying to create a new SP for rbac, it takes a few minutes and finally fails with this message:

```
Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/xxxxxxxxxxxx/providers/Microsoft.Authorization/roleAssignments/xxxxxxxxx?api-version=2018-01-01-preview (Caused by ResponseError('too many 504 error responses',))
```

In the portal I can actually see the SP created, but cannot use it. I guess it's related to the role assigment missing.

**To Reproduce**
Just run:
`az ad sp create-for-rbac` or `az ad sp create-for-rbac --name test`

**Expected behavior**
Have a new usable SP created and have the info output in console

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Install method**:  apt-get
**CLI version**
azure-cli (2.0.45)

acr (2.1.4)
acs (2.3.2)
advisor (0.6.0)
ams (0.2.3)
appservice (0.2.3)
backup (1.2.1)
batch (3.3.3)
batchai (0.4.2)
billing (0.2.0)
botservice (0.1.0)
cdn (0.1.1)
cloud (2.1.0)
cognitiveservices (0.2.1)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.3)
core (2.0.45)
cosmosdb (0.2.1)
dla (0.2.2)
dls (0.1.1)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.3)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.28)
iot (0.3.1)
iotcentral (0.1.1)
keyvault (2.2.2)
lab (0.1.1)
maps (0.3.2)
monitor (0.2.3)
network (2.2.4)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.1)
redis (0.3.2)
relay (0.1.1)
reservations (0.3.2)
resource (2.1.3)
role (2.1.4)
search (0.1.1)
servicebus (0.2.2)
servicefabric (0.1.2)
sql (2.1.3)
storage (2.2.1)
telemetry (1.0.0)
vm (2.2.2)

**OS Version**: Ubuntu 18.04.1 LTS (Linux 4.15.0-33-generic)
**Shell Type**: zsh

**Comment by JasonvanBrackel** [comment]
Seeing very similar behavior with ```az ad sp delete``` as well.

**Comment by gldraphael** [comment]
Same with `az ams account sp` & `az ams account reset-credentials` too.

**Comment by chhajwani** [comment]
same here...

**Comment by tjprescott** [comment]
This isn't related to CLI.
https://azure.microsoft.com/en-us/status/

There's a service outage currently that's affecting a specific region, but also the ARM resource provider, which unfortunately touches pretty much all resources.

**Comment by yugangw-msft** [comment]
transient error from service end, closing
