### ISSUE TITLE
login: support "--allow-no-subscriptions" when login with MSI identity

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#7225]
For now, this flag is not respected when use with "--identity"; but scenarios are coming up now that users might only give the identity some accesses to a keyvault and keyvault data plane is not subscription bound.

**Comment by djyou** [comment]
+1 for this feature. ACR has a use scenario where the identity doesn't have permission to manage Azure resources but has the permission to perform a few runtime operations. /cc @sajayantony

**Comment by sajayantony** [comment]
@yugangw-msft As @djyou pointed out, ACR also has a requirement to make MSI support non-subscription bound operations so once this makes it in, we would like queue up a work item to update the docs to use this 
/cc @dlepow
