### ISSUE TITLE
az iot hub monitor-events/invoke-device-method fails with error message short option not allowed

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-cli#7228]
**Describe the bug**

> $ az iot hub monitor-events 
> command authoring error: multi-character short option '-cg' is not allowed. Use a single character or convert to a long-option.

**To Reproduce**
Issue command on terminal: _az iot hub monitor-events_ 

**Expected behavior**
A help messsage listing various option available with monitor-events

**Environment summary**
Install Method: 

> brew install azure-cli
> az extension add --name azure-cli-iot-ext

**OS**: macOS 10.13.4
**CLI version** 
$ az --version
azure-cli (2.0.35)

> acr (2.0.26)
> acs (2.0.34)
> advisor (0.5.1)
> ams (0.1.1)
> appservice (0.1.33)
> backup (1.1.1)
> batch (3.2.3)
> batchai (0.2.3)
> billing (0.1.8)
> cdn (0.0.14)
> cloud (2.0.13)
> cognitiveservices (0.1.13)
> command-modules-nspkg (2.0.1)
> configure (2.0.15)
> consumption (0.3.1)
> container (0.1.24)
> core (2.0.35)
> cosmosdb (0.1.21)
> dla (0.1.0)
> dls (0.0.21)
> dms (0.0.1)
> eventgrid (0.1.12)
> eventhubs (0.1.3)
> extension (0.0.14)
> feedback (2.1.1)
> find (0.2.9)
> interactive (0.3.22)
> iot (0.1.21)
> keyvault (2.0.22)
> lab (0.0.22)
> maps (0.1.0)
> monitor (0.1.7)
> network (2.1.3)
> nspkg (3.0.2)
> policyinsights (0.1.0)
> profile (2.0.25)
> rdbms (0.2.3)
> redis (0.2.13)
> reservations (0.1.2)
> resource (2.0.30)
> role (2.0.24)
> servicebus (0.1.2)
> servicefabric (0.0.12)
> sql (2.0.27)
> storage (2.0.34)
> vm (2.0.33)
> 
> Extensions:
> azure-cli-iot-ext (0.5.2)
> 
> Python location '/usr/local/opt/python/bin/python3.6'
> Extensions directory '/Users/779591/.azure/cliextensions'
> 
> Python (Darwin) 3.6.5 (default, Apr 25 2018, 14:23:58) 
> [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]

**Additional context**

> $ az iot hub monitor-feedback
> Please provide an IoT Hub entity name or IoT Hub connection string via --login...
> $ az iot hub invoke-device-method
> command authoring error: multi-character short option '-mn' is not allowed. Use a single character or convert to a long-option.
> $ az iot hub monitor-events 
> command authoring error: multi-character short option '-cg' is not allowed. Use a single character or convert to a long-option.
> $ az iot hub show
> usage: az iot hub show [-h] [--verbose] [--debug]
>                        [--output {json,jsonc,table,tsv}] [--query JMESPATH]
>                        [--name HUB_NAME]
>                        [--resource-group RESOURCE_GROUP_NAME]
>                        [--ids RESOURCE_ID [RESOURCE_ID ...]]
> az iot hub show: error: (--name | --ids) are required

**Comment by tjprescott** [comment]
Please try updating your CLI installation. It is several months old and this issue should be fixed. Please reopen if that doesn't solve your issue.
