### ISSUE TITLE
`--set` does not seem to be able to handle JSON input

### ISSUE THREAD

**Issue by ScriptMyJob** [Azure/azure-cli#7230]
A use case for this would be if I wanted to set a key that is a JSON list:

```
function Update-AppSubscriptionKeyDescription {
    param(
        [Parameter(Mandatory=$true)][string]$appId,
        [Parameter(Mandatory=$true)][string]$KeyName
    )

    $GeneratedKey = (
        az ad app list `
            --display-name "$Name" |
                ConvertFrom-Json
    ).passwordCredentials

    $GeneratedKey.customKeyIdentifier = "$KeyName"

    $ReplacementJSON = ConvertTo-Json @($GeneratedKey)

    az ad app update `
        --id $appId `
        --set passwordCredentials=$ReplacementJSON `
        --force-string |
            ConvertFrom-Json
}

Update-AppSubscriptionKeyDescription `
    -AppID "$AzureWebAppID" `
    -KeyName "GraphKey"
```

Her is the error in it's entirety:

```
az : ERROR: Unable to build a model: Cannot deserialize as [PasswordCredential] an object of type <class 'str'>, DeserializationError: Cannot deserialize as [PasswordCredential] an object of type <class 'str'>
At line:19 char:5
+     az ad app update `
+     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: Unable t...e <class 'str'>:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 921aa920-c25f-5227-aabb-49116da38fa7
* Version Independent ID: 9b5a53ad-edf8-4d89-f8e6-cde01b7866f6
* Content: [az ad app](https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ScriptMyJob** [comment]
For clarification, the reason that I was taking this route was because of the following issue:

```
PS Azure:\> az ad app update `
>>         --id '12345678-1234-1234-1234-123456789012' `
>>         --set passwordCredentials[0].customKeyIdentifier='GraphKey'
Update to existing credential with KeyId '87654321-4321-4321-4321-123456789012' is not allowed.
Azure:/
PS Azure:\>
```

**Comment by tjprescott** [comment]
What do the contents of `$ReplacementJSON` actually look like?  The set command is designed to accept JSON strings.

However, your original error message: 
`Update to existing credential with KeyId '87654321-4321-4321-4321-123456789012' is not allowed.`

means that even if you get the JSON to be accepted, the service will still reject your call because you can't update the credential.

**Comment by ScriptMyJob** [comment]
Here is the requested information:

```
PS C:\Temp> function Update-AppSubscriptionKeyDescription {
    param(
        [Parameter(Mandatory=$true)][string]$appId,
        [Parameter(Mandatory=$true)][string]$KeyName
    )

    $GeneratedKey = (
        az ad app list `
            --app-id "$appId" |
                ConvertFrom-Json
    ).passwordCredentials

    $GeneratedKey

    $GeneratedKey.customKeyIdentifier = "$KeyName"

    $ReplacementJSON = ConvertTo-Json @($GeneratedKey)

    $ReplacementJSON

# Commented out replace
}

Update-AppSubscriptionKeyDescription `
    -AppID "1c457fda-21ac-4689-8841-3902c2dfa547" `
    -KeyName "GraphKey"


customKeyIdentifier : 
endDate             : 2299-12-31T00:00:00Z
keyId               : a5048026-80a8-45c2-a22c-140738c2d0a9
startDate           : 2018-11-09T18:45:20.334688Z
value               : 

[
    {
        "customKeyIdentifier":  "GraphKey",
        "endDate":  "2299-12-31T00:00:00Z",
        "keyId":  "a5048026-80a8-45c2-a22c-140738c2d0a9",
        "startDate":  "2018-11-09T18:45:20.334688Z",
        "value":  null
    }
]



PS C:\Temp> 
```

**Comment by tjprescott** [comment]
From the looks of it, I would recommend two things:
1) strip out the newlines so the JSON is a single string
2) remove `"value": null`.

**Comment by yugangw-msft** [comment]
On top of @tjprescott's  idea, please use the new command of `az ad app credential reset`, which should just work for your case. The glitch of  `Update to existing credential with KeyId '87654321-4321-4321-4321-123456789012' is not allowed.` was tracked by #7957. Please check that issue out for workaround
Hence I am closing this bug
