### ISSUE TITLE
az aks browse not working, pod "ubernetes..." not found

### ISSUE THREAD

**Issue by yantang-msft** [Azure/azure-cli#7239]
Running the az aks browse command gives me this error:
```Error from server (NotFound): pods "ubernetes-dashboard-7979b9b5f4-9nqxq" not found```

I have this pod `kubernetes-dashboard-7979b9b5f4-9nqxq`. But how does 'kubernetes' become 'ubernetes'...

**Comment by NilsBreitmann** [comment]
I have the same problem. Is there a fix or workaround?

**Comment by DamonStamper** [comment]
I'm also experiencing this. What's odd is this was working a few days ago.

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Cluster location is East US.

**Comment by DamonStamper** [comment]
Updating from azure-cli v2.0.25 to 2.0.46 resolved my issue.
