### ISSUE TITLE
CLI for Virtual WAN

### ISSUE THREAD

**Issue by reyandap** [Azure/azure-cli#7251]
**Is your feature request related to a problem? Please describe.**
Virtual WAN is to GA 9/24 and hence the CLI need.
Swagger (Developer to contact is Ritwik Basu)
https://github.com/ritwikbasu/azure-rest-api-specs/blob/Network-September-Release/specification/network/resource-manager/Microsoft.Network/stable/2018-08-01/virtualWan.json 
https://github.com/Azure/azure-rest-api-specs/pull/3715 

**Describe the solution you'd like**
Brief about Virtual WAN : Azure Virtual WAN is a networking service providing optimized and automated branch to branch connectivity through Azure. Virtual WAN allows customers to connect branches to each other and Azure, centralizing their network and security needs with virtual appliances such as firewalls and Azure network and security services.

**Describe alternatives you've considered**
CLI is needed to GA

**Additional context**
The swagger was approved for PR link above and will be in the September network release. Please contact ritwikb@microsoft.com and me reyandap@microsoft.com if any questions on Virtual WAN

**Comment by tjprescott** [comment]
Added via extension.
