### ISSUE TITLE
Automating stop/start of VMs

### ISSUE THREAD

**Issue by Fumes007** [Azure/azure-cli#7252]
**Describe the bug**
I am trying to stop multiple VMs (over 700+) using a bash script and Jenkins to orchestrate the schedule. I am using `az vm start/deallocate -n vm -g rg --no-wait`. When it gets to about VM # 200. Azure informs me my environment is being throttled and this causes a lot of VMs to not stop. A lot of the VMs also start in failed state. Cli should be able to handle api calls using the `--no-wait` option. 

Code snippet

```
echo -n "VM count: " $(cat vm.txt | wc -l)
echo

if [[ -s vm.txt ]]; then
    echo "Using resources from vm.txt..."
    echo
else
    echo "Didn't generate any VMs in the file."
    echo "Sorry, no resources to work with..."
    echo
    exit 1
fi

echo "VM_Name		RG"
echo "----------------------------------"
cat vm.txt
echo
echo

while read VM RG; do
    if [[ "${OPTIONS}" == "stop" ]]; then
        echo "Stopping VM: $VM..."
        az vm deallocate -g $RG -n $VM --no-wait
        #PS=$(az vm show -g $RG -n $VM --show-details --query powerState -o tsv | tr -d '"')
        STATUS="deallocated"
    elif [[ "${OPTIONS}" == "start" ]]; then
      	echo "Starting VM: $VM..."
        az vm start -g $RG -n $VM --no-wait
        #PS=$(az vm show -g $RG -n $VM --show-details --query powerState -o tsv | tr -d '"')
        STATUS="running"
    else
        echo "Try again..."
        exit 1
    fi
  
done <vm.txt
```

**To Reproduce**
Try deallocating the same amount of VMs as I am in parallel.

**Expected behavior**
Api calls should be handled by the `--no-wait` option. It should sleep for some time before moving to the next VM in the loop.

**Environment summary**
Install Method (yum) / CLI version (azure-cli (2.0.44)) / OS version (RHEL 7.5) / Shell Type (bash)  

**Additional context**

**Comment by tjprescott** [comment]
The only solution that comes to mind would be to have the CLI wait and retry on a throttling error, which would be bizarre since you explicitly called `--no-wait`. 

My advice would be for your script to track the failures, requeue them and retry until they all succeed, or introduce some delay between calls to avoid the throttling.

**Comment by Fumes007** [comment]
@tjprescott I ended up introducing a 5 seconds delay for the while loop. I've been running this for about 2 days now without any issues. Only thing is my 30 mins Jenkins job now takes 1hr 30.

**Comment by tjprescott** [comment]
@Fumes007 you can try opening a support ticket on the portal to try and increase your API bandwitdth--this is a service issue. I think the retry/requeue strategy would probably work best for you, though I'd do that in a Python script instead of bash.

**Comment by Fumes007** [comment]
@tjprescott not too familiar with using python with Azure. I have some snippet here:

`try:
    vmlist = open("vmlist.txt","r")
 
    for vm in vmlist.readlines():
        values = vm.split()
        if OPTION in ['stop', 'deallocate']:   
            # Stop the VM
            print('\nDeallocating the VM')
            async_vm_deallocate = compute_client.virtual_machines.deallocate(GROUP_NAME, VM_NAME)
            async_vm_deallocate.wait()
  
        elif OPTION in ['start']:
            # Start the VM
            print('\nStart VM')
            async_vm_start = compute_client.virtual_machines.start(GROUP_NAME, VM_NAME)
            async_vm_start.wait()
 
        else:
            print('\nDoing nothing. Select either start or stop")
            exit()
            
finally:
    vmlist.close()`


Issues: I want to be able to read the VM names/rgs from a file and use that info to start/stop. I would also consider using vm id if thats easier or querying by tags

**Comment by tjprescott** [comment]
You'd be better served asking here: https://github.com/Azure/azure-sdk-for-python
