### ISSUE TITLE
Confounding error message when providing blank resource group

### ISSUE THREAD

**Issue by yevster** [Azure/azure-cli#7256]
**Describe the bug**
When the resource group name provided to `az acr create` is an empty string, a confusing and most unhelpful message appears:

```
The api-version '2017-10-01' is invalid. The supported versions are '2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
```

**To Reproduce**
Invoke as follows:
```
 az acr create --location eastus --sku Basic --resource-group "" --name spin0kub
```

The empty value in quotes could be in a variable that a hapless scripter forgot to assign.

**Expected Behavior**
An error message along the lines of "--resource-group parameter may not be empty".

**Environment summary**
Installed via `apt` / `azure-cli (2.0.45)`/ Ubuntu 18.04LTS (x64) / bash

**Comment by djyou** [comment]
@tjprescott Do you think a global validator [here](https://github.com/Azure/azure-cli/blob/1fae61f241a067a583e93ec1f2cce5ece3b24c83/src/azure-cli-core/azure/cli/core/commands/parameters.py#L237) would be helpful?

**Comment by tjprescott** [comment]
This strikes me as a Swagger bug.  In other cases I've tried, the SDK will raise an error like "resource_group_name must have a length greater than 1."

**Comment by djyou** [comment]
Thank you @tjprescott We will fix from the swagger/SDK side.

@yevster While this error message is misleading, it shouldn't block you since empty resource group name is invalid anyway.
