### ISSUE TITLE
Different commands return the virtualMachine id differently

### ISSUE THREAD

**Issue by JonShelley** [Azure/azure-cli#7262]
**Describe the bug**
I am using the following commands to determine the private ip address of my vmss nodes. 

az vmss nic list --vmss-name vmss-name --resource-group myresourcegroup --query [].[virtualMachine.id,ipConfigurations[0].privateIpAddress] --output json

az vmss list-instances --name vmss-name --resource-group myresourcegroup --query "[].[id,osProfile.computerName]" --output json

The return value for the two commands give me

'/subscriptions/xxxxxxx/resourceGroups/myresourcegroup/providers/Microsoft.Compute/virtualMachineScaleSets/vmss-name/virtualMachines/0': {   'private_ip': '10.0.0.6'},

'/subscriptions/xxxxxxx/resourceGroups/MYRESOURCEGROUP/providers/Microsoft.Compute/virtualMachineScaleSets/vmss-name/virtualMachines/0': {   'hostname': 'hostname07f000000'},

I would like to match based on the VM id but one command returns the resource group in UPPERCASE and the other returns the resource group in lowercase. Can it just return it however the resource group is specified?

**To Reproduce**
Run the two command and compare the id for the VMs

az vmss list-instances --name vmss-name --resource-group myresourcegroup --query "[].[id,osProfile.computerName]" --output json

az vmss nic list --vmss-name vmss-name --resource-group myresourcegroup --query [].[virtualMachine.id,ipConfigurations[0].privateIpAddress] --output json

**Expected behavior**
I expect that the VM ids would be the same for both commands so that I don't have to do anything special in my script to match them.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by tjprescott** [comment]
This is the format returned by the service.

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
