### ISSUE TITLE
missing --subscription option

### ISSUE THREAD

**Issue by TiloGit** [Azure/azure-cli#7269]
How to use a different subscription for the cmd only? https://docs.microsoft.com/en-us/cli/azure/manage-azure-subscriptions-azure-cli?view=azure-cli-latest

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c608162e-cf40-9d53-da4a-51f51a0311ea
* Version Independent ID: eccbb543-be68-7de2-d41d-abee55c81452
* Content: [az acr](https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest#az-acr-list)
* Content Source: [src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
@TiloGit , please provide the detail command you are talking about. Some acr commands do have --subscription exposed

**Comment by williexu** [comment]
@TiloGit `acr list` has the `--subscription` parameter exposed. If you do not see it, please update to a newer version of the CLI.
