### ISSUE TITLE
Way to exclude commands/params if a resourcetype is not supported by the current profile.

### ISSUE THREAD

**Issue by williexu** [Azure/azure-cli#7279]
**Is your feature request related to a problem? Please describe.**
Errors occur when the CLI references a ResourceType that is not supported in the current profile but is present in another.
ex: https://github.com/Azure/azure-cli/issues/7259

**Describe the solution you'd like**
The current solution would be to either write a conditional checking for the presence of the ResourceType, or to specify a min/max profile version. The first could be simplified, and the second assumes a linear order to profile (i.e. every profile after a certain date will have the resourceType).

As part of our infrastructure, if a ResourceType is specified, we should exclude the command/loader/param from being loaded.

**Comment by tjprescott** [comment]
One of the problems you will run into here is that profiles don't reach the granularity of specific resource types as they are defined right now.
