### ISSUE TITLE
az login: error: cannot import name 'TYPE_CHECKING' on MacOS

### ISSUE THREAD

**Issue by fdoxyz** [Azure/azure-cli#7286]
**Describe the bug**
After installing the Azure CLI using homebrew I'm unable to authenticate by doing `az login`. The CLI prints out the following message:

```
usage: az login [-h] [--verbose] [--debug]
                [--output {yaml,jsonc,tsv,table,json}] [--query JMESPATH] [-i]
                [--subscription _SUBSCRIPTION] [--username USERNAME]
                [--allow-no-subscriptions] [--password PASSWORD]
                [--use-device-code] [--tenant TENANT] [--service-principal]
az login: error: cannot import name 'TYPE_CHECKING'
```

**To Reproduce**

1) On a MacOS High Sierra 10.13.6 install Azure CLI following the [steps in the docs](https://docs.microsoft.com/es-es/cli/azure/install-azure-cli-macos?view=azure-cli-latest)
2) Run `az login` in a terminal window

**Expected behavior**
The CLI should interactively prompt for credentials to authenticate the CLI

**Environment summary**
Install Method: Homebrew
OS version: MacOS High Sierra 10.13.6 (17G65)
Shell Type: iTerm2 build 3.2.0
CLI version:
```
azure-cli (2.0.45)

acr (2.1.4)
acs (2.3.2)
advisor (0.6.0)
ams (0.2.3)
appservice (0.2.3)
backup (1.2.1)
batch (3.3.3)
batchai (0.4.2)
billing (0.2.0)
botservice (0.1.0)
cdn (0.1.1)
cloud (2.1.0)
cognitiveservices (0.2.1)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.3)
core (2.0.45)
cosmosdb (0.2.1)
dla (0.2.2)
dls (0.1.1)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.3)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.28)
iot (0.3.1)
iotcentral (0.1.1)
keyvault (2.2.2)
lab (0.1.1)
maps (0.3.2)
monitor (0.2.3)
network (2.2.4)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.1)
redis (0.3.2)
relay (0.1.1)
reservations (0.3.2)
resource (2.1.3)
role (2.1.4)
search (0.1.1)
servicebus (0.2.2)
servicefabric (0.1.2)
sql (2.1.3)
storage (2.2.1)
telemetry (1.0.0)
vm (2.2.2)

Python location '/Library/Frameworks/Python.framework/Versions/3.5/bin/python3'
Extensions directory '/Users/fernando/.azure/cliextensions'

Python (Darwin) 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

**Comment by yugangw-msft** [comment]
@williexu, I remember we had a similar report before. Any information to share? I don't think this error is specific to the "login" command

**Comment by williexu** [comment]
Yep, the standard library typing is missing `TYPE_CHECKING` was introduced in python 3.5.2.
@fdoxyz you are using 3.5.1, can you update your version of python to something later?

**Comment by fdoxyz** [comment]
The standard Python install on MacOS was linked by default instead of using the recently installed 3.7.0

@williexu Yes, updating Python fixes the problem. Thanks for the help.
