### ISSUE TITLE
"-o tsv" on Mac outputs with Windows line terminators

### ISSUE THREAD

**Issue by seanknox** [Azure/azure-cli#7290]
**Describe the bug**
Outputting with `-o tsv` on Mac generates output with CRLF line terminators (Windows)

**To Reproduce**
``` 
$ az account list --query "[?contains(name, 'My Account')]".id -o tsv > accounts.txt
$ file accounts.txt
accounts.txt: ASCII text, with CRLF line terminators
```

**Expected behavior**
I'd expect output to use linefeeds on Mac and Linux, and CRLF on Windows only.

**Environment summary**
Install Method: `pip`

**Comment by squillace** [comment]
+1

**Comment by tjprescott** [comment]
I am not able to repro that on my Mac.

```
(env) Traviss-MBP-2:github travisprescott$ az account list --query "[?contains(name, 'Powershell')]".id -o tsv > accounts.txt
(env) Traviss-MBP-2:github travisprescott$ file accounts.txt
accounts.txt: ASCII text
```

Can either of your try again with the latest CLI to see if it is still reproducible? If so, please post the output of `az --version` and `pip list`.

**Comment by seanknox** [comment]
I can't repro now either. Closing. Thanks!
