### ISSUE TITLE
File-based caching in _session very likely broken

### ISSUE THREAD

**Issue by zarenner** [Azure/azure-cli#7294]
**Describe the bug**
From looking at the code at https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/_session.py#L46, I think the following is incorrect and won't expire as expected:
```python  
if st.st_mtime + max_age < time.clock():
    self.save()
```

time.clock() is "wall-clock seconds elapsed since the first call to this function" which is definitely not what was intended. time.time() is likely what you want.

This was first discovered in a port of this code into the vsts-python-api project (see https://github.com/Microsoft/vsts-python-api/issues/111)

**Comment by yugangw-msft** [comment]
//cc @troydai

**Comment by troydai** [comment]
Interesting. This particular line of code hasn't been changed since it was added 3 years ago. And this is the first time it is mentioned. And you're probably right.

**Comment by troydai** [comment]
Is it not an issue probably because we rarely set the `max_age`

**Comment by williamjacksn** [comment]
Also, the call to `time.clock()` makes this incompatible with Python 3.8.

https://docs.python.org/3.7/library/time.html#time.clock

> Deprecated since version 3.3, will be removed in version 3.8

**Comment by williamjacksn** [comment]
This appears to be fixed in #10777

**Comment by yonzhan** [comment]
Can we close it?

**Comment by jiasli** [comment]
I have fixed this issue in PR https://github.com/Azure/azure-cli/pull/10777
