### ISSUE TITLE
subscription name with space is not working in command az account set

### ISSUE THREAD

**Issue by abhiramani-iptiq** [Azure/azure-cli#7304]
subscription="IPTIQADATA DEV"
az account set --subscription $subscription

the above command does not work in azure cloud shell bash.i tried single quotes,i even tried single quotes inside double quotes

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9abfaa54-0895-29f7-f3bb-ff604912b2ac
* Version Independent ID: d1ff3478-8a86-59e4-62ef-449900132a67
* Content: [az account](https://docs.microsoft.com/en-us/cli/azure/account?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_help.py)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
What version of the CLI are you using?  I have no issue using this command when the subscription name has a space.

**Comment by abhiramani-iptiq** [comment]
I am sign azure cloudshell bash so whatever come with azure cloudshell


Abhijit Ramani | Cloud Infrastructure DevOps Engineer | ASSISTANT VICE PRESIDENT | iptiQ Americas L&H
iptiQ Americas Inc. | 175 King Street, 10504 ARMONK, UNITED STATES (USA)
Direct: +1 914 828 8397 Fax: +1 914 828 7397 Email: Abhijit_Ramani@iptiq.com<mailto:Abhijit_Ramani@iptiq.com>

**Comment by tjprescott** [comment]
```
subscription="IPTIQADATA DEV"
az account set --subscription "$subscription"
```

**Comment by abhiramani-iptiq** [comment]
yes pls close

**Comment by esnellmidmark** [comment]
@abhiramani-iptiq -sorry, it is closed, I should have been more clear: if you resolved it, what was the fix?

**Comment by pushkalb123** [comment]
@esnell-midmark , the solution is to use double quotes in the command `az account set --subscription "$subscription"`
`subscription="IPTIQADATA DEV"
az account set --subscription "$subscription"`
