### ISSUE TITLE
`az webapp config ssl unbind` has no effect on slot

### ISSUE THREAD

**Issue by Costo** [Azure/azure-cli#7310]
**Describe the bug**
I have a Web App with a `staging` slot and I want to unbind the SSL certificate.
I use the `ssl unbind` command. The command runs successfully, but the SSL bindings are still there. I have the same issue when I do it through the Azure Portal.

**To Reproduce**
A Web App with a slot. The slot has a custom domain and SSL bindings. 
Run the `ssl unbind` command on the slot:
`az webapp config ssl unbind --ids "/subscriptions/<subscription>/resourceGroups/<resource-group>/providers/Microsoft.Web/sites/<webapp>/slots/staging" --certificate-thumbprint <thumbprint> --subscription "<subscription>"`

The command runs sucessfully, but the SSL bindings are still there.

If  I use the `--name` parameter instead of the `--ids` parameter, the command fails (this might be another bug entirely):
`az webapp config ssl unbind --name "<webapp>" --certificate-thumbprint <thumbprint> --subscription "subscription" --resource-group <resource-group> --slot staging`

Error: **Can not perform requested operation on nested resource. Parent resource '`<webapp>(staging)`' not found.**

**Expected behavior**
The SSL bindings are gone after running the `ssl unbind` command.

**Environment summary**
Azure Cloud Shell

azure-cli (2.0.45)

acr (2.1.4)
acs (2.3.2)
advisor (0.6.0)
ams (0.2.3)
appservice (0.2.3)
backup (1.2.1)
batch (3.3.3)
batchai (0.4.2)
billing (0.2.0)
botservice (0.1.0)
cdn (0.1.1)
cloud (2.1.0)
cognitiveservices (0.2.1)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.3)
core (2.0.45)
cosmosdb (0.2.1)
dla (0.2.2)
dls (0.1.1)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.3)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.28)
iot (0.3.1)
iotcentral (0.1.1)
keyvault (2.2.2)
lab (0.1.1)
maps (0.3.2)
monitor (0.2.3)
network (2.2.4)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.1)
redis (0.3.2)
relay (0.1.1)
reservations (0.3.2)
resource (2.1.3)
role (2.1.4)
search (0.1.1)
servicebus (0.2.2)
servicefabric (0.1.2)
sql (2.1.3)
storage (2.2.1)
telemetry (1.0.0)
vm (2.2.2)

Python location '/opt/az/bin/python3'
Extensions directory '/home/vincent/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Aug 22 2018, 23:15:02)
[GCC 5.4.0 20160609]

**Comment by tjprescott** [comment]
@panchagnula

**Comment by Costo** [comment]
I tried again today and it worked this time. I'm closing this issue.
