### ISSUE TITLE
"Parameter 'maxresults' failed to meet validation requirement" in az keyvault key list-versions

### ISSUE THREAD

**Issue by Soul-D** [Azure/azure-cli#7311]
**Describe the bug**
According to [az keyvault key list-versions
](https://docs.microsoft.com/en-us/cli/azure/keyvault/key?view=azure-cli-latest#az-keyvault-key-list-versions) we can get specified numbers of key versions. But when I tried to run this command both from Azure Cloud Shell and from Cloud Shell in Azure web portal, I've got error: 
c

**To Reproduce**
1. Open Cloud shell in Azuree web portal.
2. Enter command
`az keyvault key list-versions --name "yourKeyName" --vault-name "yourKeyVaultName" --maxresults 1`
3. Error is occurred
`Parameter 'maxresults' failed to meet validation requirement`

**Expected behavior**
Version of key should be returned.

**Comment by yonzhan** [comment]
@jiasli  add to S162.

**Comment by bim-msft** [comment]
Fixed in #11531
