### ISSUE TITLE
az monitor diagnostic-settings list  --resource "/subscriptions/xxxxxxxx

### ISSUE THREAD

**Issue by just-olaakinyemi** [Azure/azure-cli#7312]
**Error from command az monitor diagnostic-settings list **
The command ```az monitor diagnostic-settings list --resource "/subscriptions/xxxxxxxx ``` gave an error
`Operation returned an invalid status code 'Bad Request'`
I have the az --version `azure-cli (2.0.44)`

Upgraded the cli to `azure-cli (2.0.45)`

After upgrade the command ```az monitor diagnostic-settings list --resource "/subscriptions/xxxxxxxx ``` gave a new error

```No registered resource provider found for location 'westeurope' and API version '2017-05-01-preview' for type 'networkSecurityGroups'. The supported api-versions are '2014-12-01-preview, 2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-06-01, 2016-07-01, 2016-08-01, 2016-09-01, 2016-10-01, 2016-11-01, 2016-12-01, 2017-03-01, 2017-04-01, 2017-06-01, 2017-08-01, 2017-09-01, 2017-10-01, 2017-11-01, 2018-01-01, 2018-02-01, 2018-03-01, 2018-04-01, 2018-05-01, 2018-06-01, 2018-07-01, 2018-08-01'. The supported locations are 'westus, eastus, northeurope, westeurope, eastasia, southeastasia, northcentralus, southcentralus, centralus, eastus2, japaneast, japanwest, brazilsouth, australiaeast, australiasoutheast, centralindia, southindia, westindia, canadacentral, canadaeast, westcentralus, westus2, ukwest, uksouth, koreacentral, koreasouth, francecentral'.. [Code: "NoRegisteredProviderFound"]```

Checked the provider list

```
az provider show -n Microsoft.Web --query "resourceTypes[?resourceType=='sites'].locations"
[
  [
    "Central US",
    "North Europe",
    "West Europe",
    "Southeast Asia",
    "Korea Central",
    "Korea South",
    "West US",
    "East US",
    "Japan West",
    "Japan East",
    "East Asia",
    "East US 2",
    "North Central US",
    "South Central US",
    "Brazil South",
    "Australia East",
    "Australia Southeast",
    "West India",
    "Central India",
    "South India",
    "Canada Central",
    "Canada East",
    "West Central US",
    "UK West",
    "UK South",
    "West US 2",
    "France Central"
  ]
]
```

Please review.

**Comment by tjprescott** [comment]
This is an error returned by the service. I'd recommend opening a support ticket in the portal since the error message clearly implies what you are trying to do is legitimate.
