### ISSUE TITLE
Does image-copy-extension copy to other subscriptions?

### ISSUE THREAD

**Issue by anniehedgpeth** [Azure/azure-cli#7316]
Does image-copy-extension copy to other subscriptions or only within the same subscription to other regions?

The documentation is misleading as it says, "Copy a managed image (or vm) to other regions," but it will also receive a `[--target-subscription]` parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1806a2fb-e007-03d5-ac2d-277da130d29b
* Version Independent ID: f8583594-0ed8-ff4d-33a8-2f7c9f41c288
* Content: [az image](https://docs.microsoft.com/en-us/cli/azure/ext/image-copy-extension/image?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/image-copy-extension/image.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/ext/image-copy-extension/image.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
@williexu comments on extensions should not create issues here but in the extensions repo.
