### ISSUE TITLE
Command syntax

### ISSUE THREAD

**Issue by amandadebler** [Azure/azure-cli#7328]
"az ad sp credential append" would be easier to discover and use than "az ad sp credential reset --append"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bef1f12-de16-93ed-1cb7-3f3d5d99d786
* Version Independent ID: 4e9329a6-50f8-ee2a-af63-f750d66ed574
* Content: [az ad sp credential](https://docs.microsoft.com/en-us/cli/azure/ad/sp/credential?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by amandadebler** [comment]
It would also be good if we could add a description to the key (password) generated.

**Comment by annebelleo** [comment]
Correct me if I'm wrong, but it looks like this issue has been fixed? Does this issue need to stay open?

**Comment by yugangw-msft** [comment]
If we could have started from scratch, I would agree `append` is better, but now going through a breaking change is a bit costly.  For context, AAD Graph doesn't support the append API, rather CLI has to construct the whole list with existing and new ones to overwrite, hence `set/reset` is not very bad.  
I have already added the description towards the password and certificate.
