### ISSUE TITLE
[Command Consistency] There are several aspects to command consistency we should track/enforce

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#733]
Add more here as they come up and split out into other issues if necessary.
- [ ] Naming
  - [ ] subresources should be peers, not children (e.g. network vnet, network subnet)

**Comment by yugangw-msft** [comment]
Regarding `vnet` and `subnet`, making it a children is consistent with both portal and xplat. In portal, you will see "subnet" is showing up in the `setting` section of a vnet. Also you can't create a subnet w/o a vnet.
Of course, if this is cause confusion under other scenarios, we can evaluate case by case

**Comment by tjprescott** [comment]
@yugangw-msft there are other places where this is not applied: blob/container and share/file in storage for example, or traffic-manager profile/endpoint in network. I agree that we shouldn't deviate from Xplat unnecessarily, but there are two standards in both our CLI and Xplat. :) So if consistency is of primary importance, we'll need to break one convention or the other.

**Comment by yugangw-msft** [comment]
I think be consistent with portal (and api service ) is more important. `vnet subnet` is consistent with portal.
Just be consistent with xplat is not critical. But before we take action, i suggest we call it out when review with network folks

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
