### ISSUE TITLE
az iot: 'device' is not in the 'az iot' command group. See 'az iot --help'.

### ISSUE THREAD

**Issue by damadei** [Azure/azure-cli#7338]
**Describe the bug**
az iot device stopped working after updating to CLI v2.0.45 on windows. It works on cloud shell.

**To Reproduce**
Upgrade to 2.0.45 on windows

**Expected behavior**
az iot device should work

**Environment summary**
Windows 10 OS

azure-cli (2.0.45)

acr (2.1.4)
acs (2.3.2)
advisor (0.6.0)
ams (0.2.3)
appservice (0.2.3)
backup (1.2.1)
batch (3.3.3)
batchai (0.4.2)
billing (0.2.0)
botservice (0.1.0)
cdn (0.1.1)
cloud (2.1.0)
cognitiveservices (0.2.1)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.3)
core (2.0.45)
cosmosdb (0.2.1)
dla (0.2.2)
dls (0.1.1)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.3)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.28)
iot (0.3.1)
iotcentral (0.1.1)
keyvault (2.2.2)
lab (0.1.1)
maps (0.3.2)
monitor (0.2.3)
network (2.2.4)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.1)
redis (0.3.2)
relay (0.1.1)
reservations (0.3.2)
resource (2.1.3)
role (2.1.4)
search (0.1.1)
servicebus (0.2.2)
servicefabric (0.1.2)
sql (2.1.3)
storage (2.2.1)
telemetry (1.0.0)
vm (2.2.2)

**Additional context**

**Comment by tjprescott** [comment]
Please see the release notes for the azure-cli-iot module 0.3.0:

```
BREAKING CHANGE: Removed deprecated commands which have moved to the iot extension 
```


This command has been deprecated for a long time and was finally removed by the IOT team. However, you can acquire the IOT extension which should have the functionality you are looking for. 

https://github.com/azure/azure-iot-cli-extension
