### ISSUE TITLE
Unable to update custom headers and Expected Status code range

### ISSUE THREAD

**Issue by gursin87** [Azure/azure-cli#7339]
**Describe the bug**
I am trying to change the custom headers and expected status code range for the monitoring setting for my ATM through azure cloud shell and i get the following error:

Set-AzureRmTrafficManagerProfile : Endpoint name '' is invalid. Endpoint names cannot be empty or all whitespace, and must be up to 260 alphanumeric characters long. The type '<null>' specified for endpoint '<null>' is invalid. Valid endpoint types are: 'Microsoft.Network/trafficManagerProfiles/azureEndpoints', 'Microsoft.Network/trafficManagerProfiles/externalEndpoints', 'Microsoft.Network/trafficManagerProfiles/nestedEndpoints'.

I am following the samples mentioned in the following articles:
https://docs.microsoft.com/en-us/powershell/module/azurerm.trafficmanager/add-azurermtrafficmanagerexpectedstatuscoderange?view=azurermps-6.8.1

**To Reproduce**
Try the first example mentioned in the following article.
https://docs.microsoft.com/en-us/powershell/module/azurerm.trafficmanager/add-azurermtrafficmanagerexpectedstatuscoderange?view=azurermps-6.8.1

Note : Update an existing traffic manager which already has an endpoint. 

**Expected behavior**
I should be able to update the custom headers and expected status codes

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
using Azure Cloud shell(powershell)
PS Azure:\> az --version
azure-cli (2.0.45)

acr (2.1.4)
acs (2.3.2)
advisor (0.6.0)
ams (0.2.3)
appservice (0.2.3)
backup (1.2.1)
batch (3.3.3)
batchai (0.4.2)
billing (0.2.0)
botservice (0.1.0)
cdn (0.1.1)
cloud (2.1.0)
cognitiveservices (0.2.1)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.3)
core (2.0.45)
cosmosdb (0.2.1)
dla (0.2.2)
dls (0.1.1)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.3)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.28)
iot (0.3.1)
iotcentral (0.1.1)
keyvault (2.2.2)
lab (0.1.1)
maps (0.3.2)
monitor (0.2.3)
network (2.2.4)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.1)
redis (0.3.2)
relay (0.1.1)
reservations (0.3.2)
resource (2.1.3)
role (2.1.4)
search (0.1.1)
servicebus (0.2.2)
servicefabric (0.1.2)
sql (2.1.3)
storage (2.2.1)
telemetry (1.0.0)
vm (2.2.2

**Additional context**
Idea is to be able to update custom headers and expected status codes of an existing endpoint

**Comment by tjprescott** [comment]
`Set-AzureRmTrafficManagerProfile : Endpoint name...`

Is this what the error says or are you using Powershell cmdlets?

**Comment by tjprescott** [comment]
Your issue should be filed here:
https://github.com/Azure/azure-powershell

This repo is for Azure CLI commands only.
