### ISSUE TITLE
Command Table linter

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#734]
Related to item #733. We already have a command table dump. It would be very useful if we analyzed the command table against certain rules that we want to enforce, or at least be alerted if there is an inconsistency. Possible rules:

- [ ] name type arguments without completers
- [ ] arguments in creates that have id_part=name and also have a completer
- [x] arguments missing help
- [ ] arguments that use hard coded choice lists instead of reflecting on enums
- [x] arguments or commands missing help text
- [ ] update commands that have arguments with default values
- [x] list commands that expose --ids
- [ ] non-standard command names (get, new, etc)
- [ ] update commands that don't have generic update arguments

This would help greatly as we get into the polish stage, relying on the rules to identify inconsistencies instead of the manual and error prone process of reviewing packages.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
