### ISSUE TITLE
Export an Azure SQL

### ISSUE THREAD

**Issue by mendiney** [Azure/azure-cli#7340]
hello!
I am trying to Export an Azure SQL database to a BACPAC file with the python-cli(I already do it in the portal), but I can't find any way to do it with a python script.

I find this class in the doc
https://docs.microsoft.com/en-us/python/api/azure-mgmt-sql/azure.mgmt.sql.models.export_request_py3.exportrequest?view=azure-python
but I can't understand how to send the request.

please help me!

**Comment by aamalvea** [comment]
Here is the documentation for the REST API that contains samples: https://docs.microsoft.com/en-us/rest/api/sql/databases%20-%20import%20export/export#examples.
