### ISSUE TITLE
[ACR] Module builtins is not supported in Python2 while is used in ACR.

### ISSUE THREAD

**Issue by christianbader** [Azure/azure-cli#7343]
**Describe the bug**
The `az acr build` command is failing with `ImportError: No module named builtins`

**To Reproduce**
Install/update azure-cli: `sudo yum install azure-cli-2.0.45`
Run : `az acr build`

**Expected behavior**
Should return `az acr build: error: too few arguments` or (if appropriate arguments provided) build the image.

**Environment summary**
```
NAME="CentOS Linux"
VERSION="7 (Core)"
```
Kernel:
```
4.18.8-1.el7.elrepo.x86_64
```
Installed via:
```
sudo yum install azure-cli-2.0.45
```

**Additional context**
Version `azure-cli-2.0.33` works just fine. Stopped working after updating to `azure-cli-2.0.45`.
It works after installing the `future` package manually via:
```
/usr/lib64/az/bin/pip install future
```

**Comment by glebsam** [comment]
Got the same issue using command `az interactive`. The exceptions appeared after a second after command launched. Be aware, w/a cannot be applied using system-wide `pip` (I mean `pip install future`), need to use **exactly** pip from `/usr/lib64/az/bin/` as described in the issue description.

Problem also can be solved by downgrade with command `yum -y downgrade azure-cli-2.0.43-1.el7`.
So, currently affected versions of yum package for CentOS 7:
* 2.0.46-1
* 2.0.45-1
* 2.0.44-1

**Comment by troydai** [comment]
Thank you. I'm taking a look at it.

**Comment by troydai** [comment]
Acknowledge. Working on it.

**Comment by troydai** [comment]
Just as @glebsam pointed out: `builtins`[1] is not supported in python2, which is the default installation in centos.

I will ask ACR team to work out a back-compatible solution for Python2. However, it worth pointed out that Python2 is reaching the end of its lifecycle, we should really get prepared for the day when it is not supported.

[1] https://github.com/Azure/azure-cli/blob/d5467e4fdd4916f8c1249ca1ee030d3ff509d999/src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_archive_utils.py#L10

**Comment by troydai** [comment]
@djyou there is import in the `ACR` module not compatible with Python2 (see my comments above).

**Comment by troydai** [comment]
Fixed in https://github.com/Azure/azure-cli/pull/7454#pullrequestreview-160471883
