### ISSUE TITLE
az iot dps create    Location is required

### ISSUE THREAD

**Issue by djaus2** [Azure/azure-cli#7344]
I found that without this the creation failed, but worked with it specified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb078bf-8f6c-a3f6-d157-3ecf9d94f7e2
* Version Independent ID: a5e7ccb7-7593-4c0c-bc95-66c8216ed35f
* Content: [az iot dps](https://docs.microsoft.com/en-us/cli/azure/iot/dps?view=azure-cli-latest#az-iot-dps-create)
* Content Source: [src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/_help.py)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jlian** [comment]
`--location` shouldn't be an optional parameter. This is a bug

**Comment by jlian** [comment]
Target Oct for fix https://msazure.visualstudio.com/One/_workitems/edit/4979281
