### ISSUE TITLE
generate-sas-token cannot be used with az iot hub command

### ISSUE THREAD

**Issue by designncode7** [Azure/azure-cli#7345]
This error is generated: 
az iot hub: 'generate-sas-token' is not in the 'az iot hub' command group. See 'az iot hub --help'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9e0abf1-d0b9-d886-c106-ae056daa47ec
* Version Independent ID: 7534d5aa-8270-49e5-21d6-e9456969a60e
* Content: [az iot hub](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/iot/hub?view=azure-cli-latest#ext-azure-cli-iot-ext-az-iot-hub-generate-sas-token)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/hub.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/hub.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by axellejamous** [comment]
I have the same issue. All other commands listed in doc generate the same error.
