### ISSUE TITLE
az storage blob upload :  'Connection aborted.', timeout()) with large(ish) files

### ISSUE THREAD

**Issue by udf2457** [Azure/azure-cli#7346]
I had a shell script (simplified version attached) that was uploading files to azure without problem using `az storage blob upload`.

However now it has stopped working.

Uploading small files (e.g. a KBs to small-MBs) works fine.
However large files (e.g. hundreds of MB or more) now gives an error "'Connection aborted.', timeout()"

I am using the following syntax:
`az storage blob upload --validate-content --no-progress --content-md5 "${md5Val}" -c "${AZ_STORAGE_CONTAINER}" -f "${filePath}" -n "${blobPath}" `

azure-cli (2.0.45)
Python (Linux) 3.6.5 (default, Aug 22 2018, 23:15:02) 
[GCC 5.4.0 20160609]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
Linux ukc-bk04 4.4.0-135-generic #161-Ubuntu SMP Mon Aug 27 10:45:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

> ('Connection aborted.', timeout())
> Traceback (most recent call last):
>   File "/opt/az/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 308, in _send_until_done
>     return self.connection.send(data)
>   File "/opt/az/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1729, in send
>     self._raise_ssl_error(self._ssl, result)
>   File "/opt/az/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1616, in _raise_ssl_error
>     raise WantWriteError()
> OpenSSL.SSL.WantWriteError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
>     chunked=chunked)
>   File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
>     conn.request(method, url, **httplib_request_kw)
>   File "/opt/az/lib/python3.6/http/client.py", line 1239, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/opt/az/lib/python3.6/http/client.py", line 1285, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/opt/az/lib/python3.6/http/client.py", line 1234, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/opt/az/lib/python3.6/http/client.py", line 1065, in _send_output
>     self.send(chunk)
>   File "/opt/az/lib/python3.6/http/client.py", line 986, in send
>     self.sock.sendall(data)
>   File "/opt/az/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 319, in sendall
>     sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
>   File "/opt/az/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 311, in _send_until_done
>     raise timeout()
> socket.timeout
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
>     timeout=timeout
>   File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "/opt/az/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "/opt/az/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
>     raise value.with_traceback(tb)
>   File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
>     chunked=chunked)
>   File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
>     conn.request(method, url, **httplib_request_kw)
>   File "/opt/az/lib/python3.6/http/client.py", line 1239, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/opt/az/lib/python3.6/http/client.py", line 1285, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/opt/az/lib/python3.6/http/client.py", line 1234, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/opt/az/lib/python3.6/http/client.py", line 1065, in _send_output
>     self.send(chunk)
>   File "/opt/az/lib/python3.6/http/client.py", line 986, in send
>     self.sock.sendall(data)
>   File "/opt/az/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 319, in sendall
>     sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
>   File "/opt/az/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 311, in _send_until_done
>     raise timeout()
> urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout())
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/storageclient.py", line 269, in _perform_request
>     response = self._httpclient.perform_request(request)
>   File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/_http/httpclient.py", line 92, in perform_request
>     proxies=self.proxies)
>   File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/opt/az/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
>     r = adapter.send(request, **kwargs)
>   File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 495, in send
>     raise ConnectionError(err, request=request)
> requests.exceptions.ConnectionError: ('Connection aborted.', timeout())
> 
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
>     cmd_result = self.invocation.execute(args)
>   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
>     six.reraise(*sys.exc_info())
>   File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
>     raise value
>   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
>     result = cmd(params)
>   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
>     return self.handler(*args, **kwargs)
>   File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
>     result = op(**command_args)
>   File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 286, in upload_blob
>     return type_func[blob_type]()
>   File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 279, in upload_block_blob
>     return client.create_blob_from_path(**create_blob_args)
>   File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/blob/blockblobservice.py", line 463, in create_blob_from_path
>     timeout=timeout)
>   File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/blob/blockblobservice.py", line 614, in create_blob_from_stream
>     initialization_vector=iv
>   File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/blob/_upload_chunking.py", line 86, in _upload_blob_chunks
>     raise f.exception()
>   File "/opt/az/lib/python3.6/concurrent/futures/thread.py", line 56, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/blob/_upload_chunking.py", line 211, in process_chunk
>     return self._upload_chunk_with_progress(chunk_offset, chunk_bytes)
>   File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/blob/_upload_chunking.py", line 225, in _upload_chunk_with_progress
>     range_id = self._upload_chunk(chunk_offset, chunk_data)
>   File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/blob/_upload_chunking.py", line 270, in _upload_chunk
>     timeout=self.timeout,
>   File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/blob/blockblobservice.py", line 1013, in _put_block
>     self._perform_request(request)
>   File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/storageclient.py", line 381, in _perform_request
>     raise ex
>   File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/common/storageclient.py", line 311, in _perform_request
>     raise AzureException(ex.args[0])
> azure.common.AzureException: ('Connection aborted.', timeout())

[azureSimplified.sh.txt](https://github.com/Azure/azure-cli/files/2389342/azureSimplified.sh.txt)

**Comment by luqian1** [comment]
have the similar error when upload large file

**Comment by williexu** [comment]
@zezha-msft Can you comment on this?
The CLI simply passes along arguments to the sdk.

**Comment by williexu** [comment]
Use the command with the `--socket-timeout` parameter.
ex. `az storage blob upload --socket-timeout <number of secs> ....`
@zezha-msft  how would a customer know what would be a good socket timeout to specify?

**Comment by zezha-msft** [comment]
@williexu please refer to the comments [here](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-common/azure/storage/common/_constants.py#L39).

**Comment by williexu** [comment]
@zezha-msft it's interesting how the default socket timeout is set to a tuple if in python 3.
If the user specifies an int, does that apply to the combined timeout to connect and read?

**Comment by zezha-msft** [comment]
Hi @williexu, the value would be used for both connect and read. Here is the doc:
```
:param timeout: (optional) How long to wait for the server to send
            data before giving up, as a float, or a :ref:`(connect timeout,
            read timeout) <timeouts>` tuple.
```

**Comment by williexu** [comment]
@udf2457 can you specify a socket timeout larger than 2000? Say, 3000, per Ze's suggestion?

**Comment by marcelvb** [comment]
I have a similar error, where some kind of network timeout causes `az storage blob download-batch` throws an exception:

```
Finished[#############################################################]  100.0000%
Finished[#############################################################]  100.0000%
Finished[#############################################################]  100.0000%
Finished[#############################################################]  100.0000%
[Errno 5] Input/output error
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 366, in execute
    cmd.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 234, in new_handler
    handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/__init__.py", line 177, in handler
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 151, in storage_blob_download_batch
    for blob_normed in blobs_to_download)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 151, in <genexpr>
    for blob_normed in blobs_to_download)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/storage/operations/blob.py", line 124, in _download_blob
    progress_callback=progress_callback)
  File "/opt/az/lib/python3.6/site-packages/azure/multiapi/storage/v2018_03_28/blob/baseblobservice.py", line 1872, in get_blob_to_path
    timeout)
OSError: [Errno 5] Input/output error
```

Looks like the error comes from the underlying Python SDK. It would be nice if either the SDK or the Azure CLI would handle this a bit nicer. Now it crashes halfway during a 1 TB download. The only thing you can do is to start from scratch.

**Comment by williexu** [comment]
@marcelvb can you please raise an issue in https://github.com/Azure/azure-storage-python? There is nothing the CLI can do around the limitations in the python sdk.
@zezha-msft for awareness.

**Comment by zezha-msft** [comment]
Hi @williexu, is it possible for the CLI to skip the failed transfer instead or crashing? It would be a much nicer user experience.

**Comment by zhusijia26** [comment]
Close this issue since solution provided and long idle time.
