### ISSUE TITLE
Error message for `container create` incorrectly describes `--memory` units

### ISSUE THREAD

**Issue by mlda065** [Azure/azure-cli#7355]
**Describe the bug**
The `--memory` flag of `az container create` is described by the client as being multiples of 0.1GB. But that is incorrect.

**To Reproduce**

```
azureuser@Azure:~$ az container create --resource-group openface --name matt-of-big --image bamos/openface --dns-name-label matt-of-big --ports 8000 9000 --cpu 4 --memory 4000000000
The memory requirement is '4000000000' in container 'matt-of-big' of container group 'matt-of-big'. The memory requirement should be times of 0.1 GB.
azureuser@Azure:~$ az container create --resource-group openface --name matt-of-big --image bamos/openface --dns-name-label matt-of-big --ports 8000 9000 --cpu 4 --memory 40
The requested resource with '4' CPU and '40' GB memory is not available in the location 'australiaeast' at this moment. Pleaseretry with a different resource request or in another location.
```

Note the crucial parts:

> The memory requirement should be times of 0.1 GB

But when I set `--memory 40` it interprets that as 40 * 1GB, not 40 * 0.1GB.

**Expected behaviour**

* If I try `--memory 4GB` or `--memory 4000000000` or something else invalid, the error message should tell me what units and format it's expecting
* The [documentation](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-tutorial-deploy-app) should specify what units the argument expects

**Environment summary**
Cloud shell

**Comment by samkreter** [comment]
@mlda065 This message is misleading but it is referring that it should be in increments of .1 GB. So --memory 7.3 is equivalent to 7.3 GB. 

I'm changing the error message to "The memory requirement should be in increments of 0.1 GB."

Let me know if we can make this message even more clear.

**Comment by mlda065** [comment]
Yes that's still unclear.

E.g. My first attempt was `--memory 0.2GB`, but that doesn't work because it expects a float not a string. My second attempt was `--memory 200000000` (because 0.2GB = 200000000B, roughly) but that doesn't work either.

So maybe say something like

> The memory requirement is measured in GB, in increments of 0.1 GB

Also

> The requested resource with '4' CPU and '40' GB memory is not available in the location 'australiaeast' at this moment

should be

> The requested resource with '4' CPU and '40' GB memory is not available in the location 'australiaeast' at this moment. The current limits for 'australiaeast' are 1 CPU and 1.5 GB.

Also, can you let the GUI team know that when you exceed those limits in the Portal, the error message doesn't tell you what went wrong. It just says "deployment failed".

**Comment by tjprescott** [comment]
@samkreter another option would be to allow the user to specify the units and do internal conversion to the units expected by the service.

**Comment by tjprescott** [comment]
You could also use for the text "The memory in GB, accurate to one decimal place."
