### ISSUE TITLE
VM size should contain pricing information.

### ISSUE THREAD

**Issue by AttilaVM** [Azure/azure-cli#7356]
**Is your feature request related to a problem? Please describe.**

It would be nice to determine optimal VM prices with azure-cli, which already has the feature to list all the possible VM sizes for a region with important and JMESPath quariable properties, but the price is missing.

**Describe the solution you'd like**

The returned virtual machine size dictionaries of the `az vm list-sizes` command should expose the hourly costs. So the following example command would return the price-sorted-list containing all of the size options which have more than 8000MB memory and more than 4 cores in the specified location.

```
az vm list-sizes \
	 --location northeurope \
	 --query "[?memoryInMb>\`8000\` && numberOfCores>\`4\`] | sort_by(@,&pricePerHour)" 
```

**Describe alternatives you've considered**

One can use the [Azure price calculator](https://azure.microsoft.com/en-us/pricing/calculator/), but it is not so convinient.

**Comment by tjprescott** [comment]
AFAIK the service does not support returning that information.

**Comment by AttilaVM** [comment]
Thank you. This is not a critical problem for me. I wrote the issue because it seems like a nice possible enhancement.

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.

**Comment by aytekinar** [comment]
@Drewm3, @AttilaVM Could we reopen this issue?

Having pricing information available via CLI (or, perhaps, Azure SDK for Python) is indeed a nice addition.

**Comment by Drewm3** [comment]
@aytekinar, could you please open this feature request through https://feedback.azure.com/forums/216843-virtual-machines. With the large number of requests and feature suggestions it is much easier for us to manage and gather feedback through the User Voice platform as compared to trying to use issues in multiple GitHub repros to track feature ideas.

Thanks
