### ISSUE TITLE
product name incorrect

### ISSUE THREAD

**Issue by christiankuhtz** [Azure/azure-cli#7359]
Product name is "Load Balancer".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c3075af-3efc-1e5a-610e-6b22b3022cf5
* Version Independent ID: a50ce9cf-b80d-98d6-4dfe-1dae7f79ed39
* Content: [az network lb](https://docs.microsoft.com/en-us/cli/azure/network/lb?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
As opposed to what?

**Comment by tjprescott** [comment]
Closing as I'm not sure what the ask is here.
