### ISSUE TITLE
load balancing rules instead of "rules"

### ISSUE THREAD

**Issue by christiankuhtz** [Azure/azure-cli#7360]
please change the heading to "Load balancing rules" rather than "Rules".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 833c520c-fcbe-64f0-39c9-fdc6553940b0
* Version Independent ID: e9f6fdaf-fd76-0b90-2571-2c80677c5460
* Content: [az network lb rule](https://docs.microsoft.com/en-us/cli/azure/network/lb/rule?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
This is not controlled in the CLI source code. @dend
