### ISSUE TITLE
Add Macports install for macOS

### ISSUE THREAD

**Issue by conradwt** [Azure/azure-cli#7361]
**Is your feature request related to a problem? Please describe.**

At this time, the only way to install the Azure CLI is Homebrew if one is reading the documentation.  However, I really don't want to install yet another package manager but rather use an existing package manager that I'm using at this time.  Thus, I would like to see support for MacPorts.

**Describe the solution you'd like**

I would like to be able to install Azure CLI using MacPorts.

**Describe alternatives you've considered**

I have tried using pip during a Cloud Native workshop which failed.  Also, I have used Docker with success but it would be nice not to force this dependency on users of the Azure CLI.

**Additional context**

I would be interested in creating the Portfile to work with MacPorts and updating the necessary dependencies like documentation.

**Comment by yugangw-msft** [comment]
If there is a solution for the #7362 you opened, do you still want this?

**Comment by troydai** [comment]
At this point, we don't have a plan to ship the package in MacPorts.

**Comment by conradwt** [comment]
I would like to submit a PR which provides support for MacPorts.

**Comment by tjprescott** [comment]
@conradwt we would welcome your PR.

**Comment by conradwt** [comment]
@tjprescott Good to hear because I have learned from a previous PR that I should get some confirmation prior to starting any PR.

**Comment by tjprescott** [comment]
Since we do not plan to add MacPorts support, I will close this issue. You are welcome to submit a PR supporting this platform.

**Comment by ain** [comment]
When discussing HomeBrew vs MacPorts, it's of course two very different package managers. 

I'd have expected Azure to do better for the MacPorts and the developers who prefer a more conservative and stable platform. 

Google Cloud SDK is there:

```
$ port search google-cloud-sdk
google-cloud-sdk @418.0.0 (devel, python)
    Command-line interface for Google Cloud Platform products and services
```

**Comment by breiter** [comment]
```
$ port search py-awscli
py-awscli @1.29.24 (python, devel)
    Universal Command Line Environment for Amazon Web Services.

py-awscli-plugin-endpoint @0.4 (python)
    An awscli plugin to configure service endpoint from aws configure file

py-awscli2 @2.13.3 (python, devel)
    Universal Command Line Environment for Amazon Web Services.

Found 3 ports.
```

**Comment by tthoma24** [comment]
Wow, can't believe we're in the year of our lord 2026 with this

<img width="1440" height="775" alt="Image" src="https://github.com/user-attachments/assets/0a1e7654-f445-4592-a3fa-123fd0c5a976" />
<img width="1121" height="83" alt="Image" src="https://github.com/user-attachments/assets/ef2bc683-7c61-473e-b557-3487b5187159" />
