### ISSUE TITLE
error message when trying to update reply-url with az ad app update

### ISSUE THREAD

**Issue by Zazcallabah** [Azure/azure-cli#7364]
When I try to use az cli to update a reply url i get the following:

    az ad app update --id f1aec2f5-090e-4994-be10-a9ab7e23c705 --reply-urls "http://localhost:8233"
    Update to existing credential with KeyId 'd0e6649d-d546-4b64-86b2-ec64b46adf66' is not allowed.

The KeyId mentioned matches the id on the passwordCredentials property on the ad app.

This seems like a bug, because if I manually do a http PATCH to `"https://graph.windows.net/$($tenant)/applications/$($objectId)?api-version=1.6"` with the same credentials and just `{"replyUrls":["https://localhost:4503"]}` as payload the update works fine.

**Comment by yugangw-msft** [comment]
I apologize for being late in response, but we have fixed a few bugs in app update command recently.
Please migrate to a newer version and run the command again. 
I tried already and it worked; hence I am closing this issue.
