### ISSUE TITLE
incorrect json in --required-resource-accesses property in az add app create example command

### ISSUE THREAD

**Issue by MrDoNotBreak** [Azure/azure-cli#7365]
az add app create example with --required-resource-accesses is invalid. Can you provide a working example here? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 921aa920-c25f-5227-aabb-49116da38fa7
* Version Independent ID: 9b5a53ad-edf8-4d89-f8e6-cde01b7866f6
* Content: [az ad app](https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
yes, we should accept the full manifest file to make lives easier

**Comment by yugangw-msft** [comment]
I will get this in as part of the overhaul effort for AAD graph commands improvement.

**Comment by yugangw-msft** [comment]
I believe the `az ad app permission add` we introduced in the latest release should get the experience really simple now.
