### ISSUE TITLE
ip-config create should support public IP's from other resource groups

### ISSUE THREAD

**Issue by rhnewtron** [Azure/azure-cli#7366]
In azure, our NOC manages the public IP's for us and keeps them in a centrally managed resource group.  We can select IP's from this Resource Group for Public Purposes.

Currently it is not possible for the CLI to assign those public IP's in resource group B to Network interfaces hosted in resource group A, 

There should be an optional parameter to specify the "public-ip-address-resource-group" 

```
λ az network nic ip-config create --resource-group ProjectGroup --nic-name nic1 --name egressip --private-ip-address 10.10.3.110 --public-ip-address public-ip-1  --public-ip-ressource-group NocGroup
```
This is possible in the Portal.

**Comment by yugangw-msft** [comment]
@rhnewtron, I thought `--public-ip-address` takes an resource id for crossing resource groups support. Not the case here?

**Comment by rhnewtron** [comment]
@yugangw-msft Thanks for this Tip. I tested with resourceID and it Works, Thanks. Maybe it's worth adding to the documentation.

```
λ az network nic ip-config create --resource-group ProjectGroup  --nic-name nic1 --name egressip --private-ip-address 10.10.3.112 --public-ip-address /subscriptions/xxx-xxx-xxx-xxx-xxx/resourceGroups/NocGroup/providers/Microsoft.Network/publicIPAddresses/public-ip-3
```
