### ISSUE TITLE
Support arm64 Linux builds

### ISSUE THREAD

**Issue by sirredbeard** [Azure/azure-cli#7368]
**Is your feature request related to a problem? Please describe.**

azure-cli is available for amd64 through Microsoft's official repos for Debian, Ubuntu, and OpenSUSE.

See Debian and Ubuntu repo at https://packages.microsoft.com/repos/azure-cli/dists/.

However, azure-cli is not available for arm64 on any of those systems.

**Describe the solution you'd like**

Add arm64 builds to Microsoft's official repos for Linux and WSL.

**Describe alternatives you've considered**

I have considered re-building each release for arm64 anew each time.

**Comment by yugangw-msft** [comment]
@troydai could you clarify?

**Comment by sirredbeard** [comment]
Thank you Troy.

**Comment by CmdLnJedi** [comment]
Hi Random User here, any update on this request?

**Comment by jwg4** [comment]
It threw me that the instructions at https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt install a version which includes an AMD64 python binary - if there isn't an ARM version then it just should refuse to install rather than install a broken version?

**Comment by admin-olivetech** [comment]
Hello Team, 

Is this near a resolution by any chance?? I've recently bought Pi400 in bulk(10 units) and looking to install az cli, but failed. I understand it is to do the with arm architecture. sharing the response from my unit when I investigate the architecture. 

 ~  dpkg --print-architecture
armhf

**Comment by anphel31** [comment]
Installing with the script instead of apt appears to work on ARM64. ("curl -L https://aka.ms/InstallAzureCli | bash
" - https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=script)

**Comment by mdfranz** [comment]
Not really (Lenovo Mediatek Chromebook) 

```
mfranz@crosdeb-s330:~$ az --version
/usr/bin/az: line 2: /opt/az/bin/python3: cannot execute binary file: Exec format error
```

and

```
Linux crosdeb-s330 5.4.88-12224-gf05236dbdecf #1 SMP PREEMPT Fri Feb 19 05:43:30 PST 2021 aarch64 GNU/Linux
```

**Comment by GoetzGoerisch** [comment]
Looking forward to native Arm64 versions.

`Linux penguin 5.4.88-12224-gf05236dbdecf #1 SMP PREEMPT Fri Feb 19 05:43:30 PST 2021 aarch64 GNU/Linux`

**Comment by cha000** [comment]
Why is it always such a fight to get Microsoft to support their own products? I just tried installing the cli yesterday and had the same result as OP 2 1/2 years later. I was trying to use the Az cli version of Bicep (which also isn't supported) and it **STILL** installs an incompatible version.

**Comment by clarkezone** [comment]
+1 this is super annoying, why is it taking so long?

**Comment by jchomarat** [comment]
it appears that now the [arm64 build is ready](https://packages.microsoft.com/repos/azure-cli/dists/groovy/):

![image](https://user-images.githubusercontent.com/6317287/122721812-60141b80-d271-11eb-97ff-00fb486452cd.png)

I've installed the "groovy / arm64" version on my container and I receive an "architecture" error:

```sh
alex@c55c367518dc:/workspace/.devcontainer$ uname -a
Linux c55c367518dc 5.10.25-linuxkit #1 SMP PREEMPT Tue Mar 23 09:24:45 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

alex@c55c367518dc:/workspace/.devcontainer$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.10
Release:        20.10
Codename:       groovy

../..
Get:1 https://packages.microsoft.com/repos/azure-cli groovy/main arm64 azure-cli all 2.25.0-1~groovy [63.5 MB]
../..

alex@c55c367518dc:/workspace/.devcontainer$ az --version
/lib64/ld-linux-x86-64.so.2: No such file or directory
```

**Comment by jiasli** [comment]
As stated in https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt

> The `azure-cli` deb package does not support ARM64 architecture.

Currently the only way to use Azure CLI on ARM64 is to install from PyPI (https://pypi.org/project/azure-cli/):

```
pip install azure-cli
```

If you encounter any issue during installation, please let us know.

**Comment by clarkezone** [comment]
@jiasli the python install listed above did indeed work.  I suggest you update the docs to reference this rather than merely stating that the deb package doesn’t support it.

**Comment by clarkezone** [comment]
Spoke to soon.. although the pip based install above worked, the az command is DOA.

**Comment by jiasli** [comment]
@clarkezone, we don't recommend installing via `pip` as it tends to cause all kinds of problems (https://github.com/Azure/azure-cli/issues/16526#issuecomment-893947765).

> although the pip based install above worked, the az command is DOA.

Do you mean DOA as "Dead On Arrival"? Are you seeing any failure? Please make sure the one installed by `apt` is uninstalled first.

```
sudo apt-get remove -y azure-cli
```

**Comment by Chuxel** [comment]
Re: DoA - I think this is https://github.com/Azure/azure-cli/issues/19567

**Comment by jiasli** [comment]
I have tested installing Azure CLI on `debian:bullseye` on `arm64` on an `amd64` machine, and it is working as expected.

Directly installing `PyNaCl` can take very long, because [`PyNaCl` 1.4.0 on PyPI](https://pypi.org/project/PyNaCl/) has no wheel for `arm64/aarch64` (https://github.com/pyca/pynacl/issues/306), so it has to build `libsodium` from source code. I used `SODIUM_INSTALL=system` provided by https://github.com/pyca/pynacl/issues/553#issuecomment-582506232 to make the installation faster.

```
docker run -it --rm --platform linux/arm64 debian:bullseye
```

```sh
apt-get update
apt-get install --yes python3 python3-pip

# Optional steps
apt-get install --yes libsodium-dev
SODIUM_INSTALL=system pip install pynacl

pip install azure-cli
```

**Comment by jiasli** [comment]
Tested installing Azure CLI on `alpine` Linux (https://github.com/Azure/azure-cli/issues/19591) in `arm64` container running on `amd64` machine, and it is also working as expected.

**Comment by jjgriff93** [comment]
Are there any plans for an ARM version of the cli now? We are unable to use pip due to dependency conflicts

**Comment by jiasli** [comment]
> Are there any plans for an ARM version of the cli now? We are unable to use pip due to dependency conflicts

We recommend installing in a virtual environment. See https://github.com/Azure/azure-cli/issues/20476.

**Comment by badsyntax** [comment]
@jiasli confirming 

> I have tested installing Azure CLI on `debian:bullseye` on `arm64` on an `amd64` machine, and it is working as expected.
> 
> Directly installing `PyNaCl` can take very long, because [`PyNaCl` 1.4.0 on PyPI](https://pypi.org/project/PyNaCl/) has no wheel for `arm64/aarch64` ([pyca/pynacl#306](https://github.com/pyca/pynacl/issues/306)), so it has to build `libsodium` from source code. I used `SODIUM_INSTALL=system` provided by [pyca/pynacl#553 (comment)](https://github.com/pyca/pynacl/issues/553#issuecomment-582506232) to make the installation faster.
> 
> ```
> docker run -it --rm --platform linux/arm64 debian:bullseye
> ```
> 
> ```shell
> apt-get update
> apt-get install --yes python3 python3-pip
> 
> # Optional steps
> apt-get install --yes libsodium-dev
> SODIUM_INSTALL=system pip install pynacl
> 
> pip install azure-cli
> ```

I've confirmed these instructions work on Ubuntu arm64 in a [qemu virtual machine](https://mac.getutm.app/) on a Mac Mini M1

**Comment by andrewegel** [comment]
Hi there-

Also a random user stumbling on this issue- I have some feedback for the package maintainers who build the azure-cli debian packages, which is that its not genuine to mark a debian package as "all" or "any" if said package ships a binary that is architecture dependent [1].

Interestingly enough the team is correctly marking the RPMs as being x86_64 architecture [2] but is not noted in your docs that [3] only EL7 and x86_64 are supported.

[1] https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-architecture
[2] https://packages.microsoft.com/yumrepos/azure-cli/
[3] https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=dnf

**Comment by tbugfinder** [comment]
Update of PyNaCl to 1.5.0 would be beneficial as it provides wheels, now.

**Comment by rdtechie** [comment]
Any update on this? I'd like to see a arm64 package also for Linux as this comes in handy to use in ubuntu based docker images running on top of macos m1/m2 systems.

**Comment by github527561222** [comment]
> 
Azure should GA ARM64 VM in preview.
https://azure.microsoft.com/en-us/updates/public-preview-arm64based-azure-vms-can-deliver-up-to-50-better-priceperformance

Amazon already online arm64 awscliv2.
https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html

It is confused that Microsoft Azure should abandon azure-cli arm64 with pip replacement or arm64 version development already on roadmap? 

Expect azure-cli arm64 should publish as soon as possible.

**Comment by bebound** [comment]
This issue is closed as completed. You’ll see ARM64 version in 2.46.

**Comment by kurt-mueller-osumc** [comment]
@bebound How would I install the latest version in an `aarch64`container? The current instructions for installizre Azure cli from Microsoft says that `deb` packages are `x86_64` architecture only.

**Comment by github527561222** [comment]
> 
You could refer bellow python venv installation for your arm64 azure-cli.

# pip with venv to install azure-cli (https://dev.to/paul8989/install-azure-cli-on-arm64-raspberry-pi-39mb)👍
$ docker run --name ubt_kinetic -itd ubuntu:kinetic bash # create a new container
$ docker exec -it ubt_kinetic bash # exec in docker
$ sudo apt update # update docker apt source
$ sudo apt install python3 python3-venv -y # install python3 and python3-venv in docker
$ python3 -m venv azure-cli-env # Create a virtual environment
$ azure-cli-env/bin/python -m pip install pip --upgrade # Update pip
$ azure-cli-env/bin/python -m pip install azure-cli # Install azure-cli
$ azure-cli-env/bin/az --version # Run any Azure CLI commands
$ rm -rf azure-cli-env # Delete the virtual environment
$ sudo ln -s azure-cli-env/bin/az /usr/local/bin/az # symbolic link az

**Comment by bebound** [comment]
> @bebound How would I install the latest version in an `aarch64`container? The current Microsoft instructions for installing the Azure CLI states that `deb` packages are `x86_64` architecture only.

The doc is not updated yet. You can follow the same installation guide to install arm64 version for Ubuntu >=20.04 and Debian.
