### ISSUE TITLE
Installing azure-cli tools from official Microsoft repos stalls on Debian/Ubuntu on WSL

### ISSUE THREAD

**Issue by sirredbeard** [Azure/azure-cli#7374]
**Describe the bug**

Installing azure-cli tools from the official Microsoft repos stalls for a very long time when installed using apt on Debian/Ubuntu-based distros on Windows Subsystem for Linux.

It can often stall for 10-25 minutes for an unclear purpose on WSL, see these reports [here](https://github.com/Microsoft/WSL/issues/2775). 

**To Reproduce**

[Follow steps](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest) to add azure-cli repo to /etc/apt/sources.list via apt on Debian or Ubuntu.
```
sudo apt-get update
sudo apt install azure-cli -y
```

**Expected behavior**

azure-cli is installed without long delays.

**Environment summary**

Debian stretch on Windows Subsystem for Linux

**Additional context**

**Comment by sirredbeard** [comment]
The delay is the extensive install script in the background.

**Comment by jlorich** [comment]
I don't think this should be closed.  The install time on Linux compared to other platforms is insane and makes for a terrible and confusing experience.

**Comment by pasisavolainen** [comment]
Time spent in installation seems to be dpkg:

```shell
$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
...
root     23697 47.5  0.1  49808 38040 pts/5    Ss   13:58   7:38 /usr/bin/dpkg --status-fd 30 --no-triggers --unpack --auto-deconfigure --recursive /tmp/apt-dpkg-install-rS1iJh`
```


This triggers every single update for me, 30-40 minutes easily.

**Comment by sirredbeard** [comment]
The time spent is because Azure-CLI is unpacking it's own Python 2 distribution. It is slow because WSL1 file I/O is slow. Some status updates during the install could be implemented.

**Comment by pasisavolainen** [comment]
@sirredbeard I'm guessing the python2 dependency isn't going anywhere soon, but how about taking it out into separate package and "just" sym/hardlinking into it from the proper azure-cli package? Again guessing that rate of change in python2 stuff is much lower than az itself

**Comment by sirredbeard** [comment]
@pasisavolainen Well Python 2 reaches EOL in 7 months. I imagine they will move to Python 3 and will still bundle it.

**Comment by embix** [comment]
>  It is slow because WSL1 file I/O is slow.

Installing azure-cli on WSL2 is not fast either - If it were, I wouldn't be here checking for issues.

**Comment by vzabawski** [comment]
I have same problem:
```
$ sudo apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  azure-cli
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 65.1 MB of archives.
After this operation, 57.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://packages.microsoft.com/repos/azure-cli bionic/main amd64 azure-cli all 2.31.0-1~bionic [65.1 MB]
Fetched 65.1 MB in 3s (18.7 MB/s)
(Reading database ... 164163 files and directories currently installed.)
Preparing to unpack .../azure-cli_2.31.0-1~bionic_all.deb ...
Unpacking azure-cli (2.31.0-1~bionic) over (2.28.0-1~bionic) ...

Progress: [ 17%] [################..................................................................................]
```
And no progress for 10-20 minutes.

**Comment by jiasli** [comment]
@vzabawski, installing on WSL 2 is pretty fast for me. 

```
$ sudo time apt-get install azure-cli
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  azure-cli
0 upgraded, 1 newly installed, 0 to remove and 19 not upgraded.
Need to get 0 B/67.0 MB of archives.
After this operation, 1035 MB of additional disk space will be used.
Selecting previously unselected package azure-cli.
(Reading database ... 38428 files and directories currently installed.)
Preparing to unpack .../azure-cli_2.31.0-1~focal_all.deb ...
Unpacking azure-cli (2.31.0-1~focal) ...
Setting up azure-cli (2.31.0-1~focal) ...
11.81user 10.41system 0:22.45elapsed 98%CPU (0avgtext+0avgdata 127884maxresident)k
200inputs+2293896outputs (2major+93352minor)pagefaults 0swaps
```

Are you using WSL 2?

**Comment by vzabawski** [comment]
Unfortunately, no. It's my corporate virtual desktop which doesn't support any nested virtualization, so I'm using WSL 1, which is sometimes very slow.
Installation took ~40 minutes, so it wasn't stuck in fact, just very slow.

**Comment by jiasli** [comment]
The latest Azure CLI consists of 49864 files:

```
$ find /opt/az -type f | wc -l
49864
```

See https://stackoverflow.com/questions/9157138/recursively-counting-files-in-a-linux-directory

WSL 1's file IO is known to be very slow, and that's why WSL 2 was born: https://docs.microsoft.com/en-us/windows/wsl/compare-versions#increased-file-io-performance

If you have further questions regarding WSL 1, you may create an issue at https://github.com/microsoft/WSL.

**Comment by farhank3389** [comment]
> The time spent is because Azure-CLI is unpacking it's own Python 2 distribution. It is slow because WSL1 file I/O is slow. Some status updates during the install could be implemented.

I don't know why you keep mentioning this everywhere this issue is reported. I'm having the same issue on a Ubuntu 20 server. It's not caused by WSL being slow, the install itself is slow.

**Comment by charmoniumQ** [comment]
The current Azure CLI package includes a tonnn of unused files, which is a known bug. See #7387
