### ISSUE TITLE
azure-cli-acs module requires some strict type checking for all the input parameters

### ISSUE THREAD

**Issue by awesomenix** [Azure/azure-cli#7388]
**Describe the bug**
azure-cli\src\command_modules\azure-cli-acs\azure\cli\command_modules\acs\custom.py
has functions which type cast to int, this needs to have a stricter type checking during input parameter itself.

example: count=int(node_count),

**To Reproduce**
Code improvement to have strict type checking.

**Expected behavior**
Not lead to run time errors due to casting

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by jluk** [comment]
Closing due to ACS deprecation in Jan 2020.
