### ISSUE TITLE
creating aks cluster with a long resource group name errors out with bad request

### ISSUE THREAD

**Issue by awesomenix** [Azure/azure-cli#7389]
**Describe the bug**
Creating a aks cluster with long resource group name errors out with a bad request

**To Reproduce**
az aks create -g clitest.rgjug4amagf7n42kaltr3tbreekmwv2gfd76u6w3swsqsiphvtfhc23le2kq7iihc36 -n cliakstestjwiv6f

**Expected behavior**
Restrict client to provide a valid resource group name acceptable by AKS

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by jluk** [comment]
This has been fixed, you can only pass in an RG name that exists which means only valid names can be handled. @yugangw-msft could you #please-close?

**Comment by jluk** [comment]
#close
