### ISSUE TITLE
How do I restore a snapshot?

### ISSUE THREAD

**Issue by spacecat** [Azure/azure-cli#7399]
Is there a CLI command for this as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fca6f8c5-a518-04ee-08e3-4ad8d4c9516e
* Version Independent ID: 17710c8c-9cd9-57ea-b6b0-1411648ea03f
* Content: [az snapshot](https://docs.microsoft.com/en-us/cli/azure/snapshot?view=azure-cli-latest#az-snapshot-create)
* Content Source: [latest/docs-ref-autogen/snapshot.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/snapshot.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
You can restore the snapshot to a managed disk, image, or even another snapshot. Check out "az disk/snapshot/image create"
