### ISSUE TITLE
az vm encryption issues with new method

### ISSUE THREAD

**Issue by johanburati** [Azure/azure-cli#7410]
I am using az cli directly from the Cloud Shell so it should be the latest version.

The first issue is when enabling encryption on the VM using the old method with the _--aad_ options I can see the **- Running ..** prompt indicating that the command is executing.
When using the new method without the _--aad_ options I do not see that  **- Running ..** prompt.

The second issue is when checking the disk status, the CLI returns the disks status when using the old method but just a blank line when using the new method.

Please have a look the code block below, *test1* has been encrypted using the old method, *test2* with the new method the data disks are encrypted on both but the CLI does not report the status for *test2*.

Screenshot: https://i.imgur.com/USMGYNb.png
```
johan@Azure:~$ az vm encryption enable --resource-group test1 --name test1 --aad-client-id $sp_id  --aad-client-secret $sp_password --disk-encryption-keyvault vaultest1 --volume-type data --encrypt-format-all --output table
johan@Azure:~$ az vm encryption show --resource-group test1 --name test1 --output table
DataDisk              OsDisk        OsType    ProgressMessage
--------------------  ------------  --------  ---------------------------------------------------------------------------------------------------------------
EncryptionInProgress  NotEncrypted  Linux     https://vaultest1.vault.azure.net/secrets/3bf925b7-e8f7-4223-8236-8f452be2eb02/475e1a060320431a8ecdbb3e55018f80
johan@Azure:~$
johan@Azure:~$
johan@Azure:~$ az vm encryption enable --resource-group test2 --name test2 --disk-encryption-keyvault vaultest2 --volume-type data --encrypt-format-all --output table
johan@Azure:~$ az vm encryption show --resource-group test2 --name test2 --output table

johan@Azure:~$
johan@Azure:~$
johan@Azure:~$
johan@Azure:~$
johan@Azure:~$
johan@Azure:~$ az vm encryption show --resource-group test1 --name test1 --output table
DataDisk    OsDisk        OsType    ProgressMessage
----------  ------------  --------  -------------------------------------
Encrypted   NotEncrypted  Linux     Encryption succeeded for data volumes
johan@Azure:~$ az vm encryption show --resource-group test2 --name test2 --output table

johan@Azure:~$
johan@Azure:~$ az vm encryption show --resource-group test2 --name test2 --output table

johan@Azure:~$
```

**Comment by yugangw-msft** [comment]
For new method, did you register the feature of `UnifiedDiskEncryptionForVMs`?
/cc @vermashi @ejarvi

**Comment by yugangw-msft** [comment]
@johanburati , could you please use `-o json` to get the json output? Table output might skip complex payloads.

**Comment by johanburati** [comment]
The issue with ```az vm encryption enable```  is that it does not show the ```- Running ..```  progress prompt when executing the command as it does when you use the ```--aad-client-id```/```--aad-client-secret``` to encrypt the VM ,  as the command takes some time to return the prompt the progress prompt is a must have, I tried using the  ```--output json``` option but that did not change that behavior.

For the ```az vm encryption show``` it does output the values in json when you use the ```--output json``` option, however I think it should also output the status of the disks when using the ```--output table``` option as it does when the VM has been encrypted using the ``--aad-client-id```/```--aad-client-secret``` options.

 ```az vm encryption show``` should output the status of the disks when using the ```--output table```  options whatever method you used to encrypt the VM.

VM has been encrypted using the ``--aad-client-id```/```--aad-client-secret``` options.
```
johan@Azure:~$ az vm encryption show --resource-group test1 --name test1 --output table
DataDisk              OsDisk        OsType    ProgressMessage
--------------------  ------------  --------  ---------------------------------------------------------------------------------------------------------------
EncryptionInProgress  NotEncrypted  Linux     https://vaultest1.vault.azure.net/secrets/3bf925b7-e8f7-4223-8236-8f452be2eb02/475e1a060320431a8ecdbb3e55018f80
```

VM has been encrypted **without** using the ``--aad-client-id```/```--aad-client-secret``` options:
```
johan@Azure:~$ az vm encryption show --resource-group test2 --name test2 --output table

johan@Azure:~$
```
