### ISSUE TITLE
Please consider configuration overrides when a directory contains a .azurerc file

### ISSUE THREAD

**Issue by robconery** [Azure/azure-cli#7411]
## The Problem:
When working with the CLI I find myself having to enter the same settings repeatedly. Subscription, Resource Group, App Name and so on. Currently it's possible to set global defaults for this, but that can lead to further problems by creating resources in groups and subscriptions in error.

## Proposed Solution
In Unix land, a common configuration override is done with a dot file, typically using the naming `.xxxrc`, where `xxx` is the binary and `rc` means "runtime configuration". A `.azurerc` file could be a simple text file that overrides the configuration environment variables - but for that local directory only. In other words, when a command is run, check to see if the file exists and if it does, load the values.

## Current Workarounds
Right now I use `dotenv`, a plugin for Oh-My-Zsh! from Robby Russel. It loads a `.env` file automatically for you, but it's relegated to people who use z-shell. It's also possible to do this manually with `source .azurerc`, but that would override the environment variables and could cause problems in other applications with different settings.

## Flexibility is Key
A tool that the Ruby community uses (rbenv) will set the local config for you with a simple command. I can see a command such as `az local AZURE_RESOURCE_GROUP=thing` dropping a `.azurerc` file for the user, with simple instructions in it. I think this would go a long way to making Unix people happy.

**Comment by yonzhan** [comment]
@jiasli  add to S162.

**Comment by smalgin** [comment]
Our deployment scripts cannot run in parallel because az CLI configuration are machine-wide. Having this will simplify our set up. Right now we have to run every deployment job in a separate container.

**Comment by jiasli** [comment]
Currently the only ways to set default values are using `az configure` and corresponding env vars, such as `AZURE_DEFAULTS_GROUP`, `AZURE_DEFAULTS_LOCATION`. Please see https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest

We will consider implementing `.azurerc` as a feature request.

**Comment by jiasli** [comment]
Reply to https://github.com/Azure/azure-cli/issues/7411#issuecomment-564265580

Hi @smalgin, the configuration of Azure CLI is user-wide stored under `$HOME/.azure` on Linux and macOS, and `%USERPROFILE%\.azure` on Windows.

**Comment by lucharo** [comment]
> Similar to [#5623](https://github.com/Azure/azure-cli/issues/5623)
> 
> Currently the only ways to set default values are using `az configure` and corresponding environment variables, such as `AZURE_DEFAULTS_GROUP`, `AZURE_DEFAULTS_LOCATION`. Please see https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest
> 
> As an equivalent to `.azurerc`, you may use `--scope local` instead so that the configurations are saved for a specific folder under `.azure/config`, thus preserving the global configurations at `$HOME/.azure/config`. For more info, please run `az configure -h`.

If I have some config in my local project folder, will that override `~/.azure/config`?
