### ISSUE TITLE
cannot grant access to disk (SAS)

### ISSUE THREAD

**Issue by alexeyshishkin01** [Azure/azure-cli#7413]
**Describe the bug**
'az disk grant-access' output is 'None'

**To Reproduce**
Steps to reproduce the behavior.

root@ubuntu:~# az group create \
> --name ubunturesourcegroup \
> --location northeurope
Location     Name
-----------  -------------------
northeurope  ubunturesourcegroup

root@ubuntu:~# az vm create \
> --name ubuntu-ent10-prepare \
> --resource-group ubunturesourcegroup \
> --image Canonical:UbuntuServer:16.04-LTS:16.04.201809120 \
> --location northeurope \
> --size Standard_DS1_v2 \
> --ssh-key-value ~/.ssh/id_rsa.pub \
> --admin-username azureuser \
> --authentication-type ssh \
> --public-ip-address-dns-name ubuntu-ent10-prepare-dnsname \
> --os-disk-name ubuntu-ent10-prepare-osdisk \
> --storage-sku Standard_LRS
ResourceGroup        PowerState    PublicIpAddress    Fqdns                                                        PrivateIpAddress    MacAddress         Location     Zones
-------------------  ------------  -----------------  -----------------------------------------------------------  ------------------  -----------------  -----------  -------
ubunturesourcegroup  VM running    13.69.138.253      ubuntu-ent10-prepare-dnsname.northeurope.cloudapp.azure.com  10.0.0.4            00-0D-3A-B6-2E-84  northeurope

root@ubuntu:~# osdisk_id=$(az vm show --name ubuntu-ent10-prepare --resource-group ubunturesourcegroup --query "storageProfile.osDisk.managedDisk.id" -o tsv)
root@ubuntu:~# echo $osdisk_id
/subscriptions/3486ae61-b408-4a54-b277-ffab699ef713/resourceGroups/ubunturesourcegroup/providers/Microsoft.Compute/disks/ubuntu-ent10-prepare-osdisk

root@ubuntu:~# az snapshot create \
> --name ubuntu-20180925-ent10-prepare-snapshot \
> --resource-group ubunturesourcegroup \
> --location northeurope \
> --source "$osdisk_id"
DiskSizeGb    Location     Name                                    OsType    ProvisioningState    ResourceGroup        TimeCreated
------------  -----------  --------------------------------------  --------  -------------------  -------------------  --------------------------------
30            northeurope  ubuntu-20180925-ent10-prepare-snapshot  Linux     Succeeded            ubunturesourcegroup  2018-09-25T11:32:12.149469+00:00

root@ubuntu:~# az disk create \
> --name ubuntu-20180925-ent10-preimage-osdisk \
> --resource-group ubunturesourcegroup \
> --size-gb 50 \
> --sku Standard_LRS \
> --source ubuntu-20180925-ent10-prepare-snapshot
Name                                   ResourceGroup        Location     Zones    Sku           OsType    SizeGb    ProvisioningState
-------------------------------------  -------------------  -----------  -------  ------------  --------  --------  -------------------
ubuntu-20180925-ent10-preimage-osdisk  ubunturesourcegroup  northeurope           Standard_LRS  Linux     50        Succeeded

root@ubuntu:~# sas_id=$(az disk grant-access --name ubuntu-20180925-ent10-preimage-osdisk --resource-group ubunturesourcegroup --duration-in-seconds 3600 --query [accessSas] -o tsv)
root@ubuntu:~# echo $sas_id
None
root@ubuntu:~#

**Expected behavior**
'az disk grant-access' output should not be 'None'

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
az --version 2.0.46
Ubuntu 16.04.5 LTS

**Additional context**
I tried CentOS, Ubuntu, Debian - the issue is the same.
It worked well in CLI 2.0.45, now I use 2.0.46, but I'm not 100% sure this is due to version upgrade.

**Comment by yugangw-msft** [comment]
@lmazuel, I made a CLI PR which adds the test coverage and a workaround. If we can make the SDK fix ready by next Wednesday, I will pull out the workaround, which is my preference.

**Comment by yugangw-msft** [comment]
@alexeyshishkin01, the SAS was returned, but was at a wrong place. You can use json output to get it. We are sorting out a fix to restore to the old behavior.

**Comment by alexeyshishkin01** [comment]
ok, thanks, waiting for the fix
