### ISSUE TITLE
deleting resource group fails to perform expected behavior

### ISSUE THREAD

**Issue by prashanthmadi** [Azure/azure-cli#7415]
**Describe the bug**
we've faced a strange problem with Resource Group removal.  In case we cancel HDInsight deployment and immediately remove resource group which contains HDInsight, the resource group is not removed.

**To Reproduce**
1. Create resource group
2. Submit deployment of the HDInsight
3. Cancel the deployment
4. Remove resource group 'az group delete --name <rg-name> --no-wait --yes'
5. After approximately 1hour there is still an empty resource group

Looks like there is a kind of timeout which exceeds due to a long HDInsight cluster removal (40~60 minutes).

**Expected behavior**
- HDInsight cluster getting deleted along with cluster

**Comment by yugangw-msft** [comment]
This is a service end problem, not CLI. A better way to seek the fix is to run with "--debug", get the correlation id, and open a support ticket.

**Comment by puravsaraiya** [comment]
Would be great if we can get SubscriptionId/CorrelationId to debug the issue on the service side. If providing SubscriptionId please provide a rough timeline of when the issue happened so we can locate the logs. Thanks!

**Comment by tjprescott** [comment]
@prasanthmadi has this been fixed in the service?

**Comment by tjprescott** [comment]
Ah, nevermind, I see you posted this issue. Must be resolved.
