### ISSUE TITLE
Cannot create network-rule for storage account

### ISSUE THREAD

**Issue by OwenGr** [Azure/azure-cli#7417]
**Describe the bug**
On a newly-created storage account, I can no longer create a network-rule. This was working previous to 2.0.46 but I can't rule out that something else changed in my script.

**To Reproduce**
1. Create a fresh resource group using `az group create --name my-test-resource-group --location eastus2`
1. Create a fresh storage account using `az storage account create --name my2345teststorageaccount --resource-group my-test-resource-group --location eastus2 --sku Standard_LRS --kind StorageV2`
1. Add network rule `az storage account network-rule add --account-name my2345teststorageaccount --resource-group my-test-resource-group --ip-address 10.0.0.0/8`

Received the following:
`Values for request parameters are invalid: networkAcls.ipRule[*].value.`

**Expected behavior**
Network rule successfully created.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows) 

Homebrew / 2.0.46 / MacOS Sierra / ITerm2.

```
$ az --version
azure-cli (2.0.46)

acr (2.1.5)
acs (2.3.4)
advisor (0.6.0)
ams (0.2.3)
appservice (0.2.4)
backup (1.2.1)
batch (3.4.0)
batchai (0.4.3)
billing (0.2.0)
botservice (0.1.1)
cdn (0.1.1)
cloud (2.1.0)
cognitiveservices (0.2.3)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.4)
core (2.0.46)
cosmosdb (0.2.1)
dla (0.2.3)
dls (0.1.3)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.2.4)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.30)
iot (0.3.2)
iotcentral (0.1.2)
keyvault (2.2.3)
lab (0.1.1)
maps (0.3.2)
monitor (0.2.3)
network (2.2.5)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.2)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.0)
resource (2.1.4)
role (2.1.5)
search (0.1.1)
servicebus (0.2.3)
servicefabric (0.1.3)
signalr (1.0.0)
sql (2.1.4)
storage (2.2.2)
telemetry (1.0.0)
vm (2.2.3)

Python location '/usr/local/opt/python/bin/python3.7'
Extensions directory '/Users/owen/.azure/cliextensions'

Python (Darwin) 3.7.0 (default, Jun 29 2018, 20:14:27)
[Clang 9.0.0 (clang-900.0.39.2)]

Legal docs and information: aka.ms/AzureCliLegal
```

**Additional context**
I've tried other IP addresses, both single IPs and in CIDR format.

**Comment by OwenGr** [comment]
Thanks. I realized my mistake a few minutes ago with the reserved IP. This works fine when you don't try variations of 10.*.

**Comment by r0bnet** [comment]
Had the same issue with /31 and /32 addresses. In the portal it said that prefix must be <= 30. Strange thing is that this works for keyvault.

**Comment by stefangordon** [comment]
/32 makes some sense at least, but I'm baffled as to the /31 - why isn't that allowed?

**Comment by creadle** [comment]
I don't understand why this doesn't work...if I were trying to grant access to an on premises resource, it will likely have an IP one of the private IP spaces.

I'm asking, because I'm running into the same issue with Key Vault right now.

**Comment by Juliehzl** [comment]
> I were trying to grant access to an on premises re

Hi @creadle, could you please create a new issue with debug information in your description to help us figure out what happened? 
And I am thinking if your premises resource has private connection enabled.

**Comment by UmairSyed** [comment]
I am trying to add 10.141.130.0/24 to keyvault firewall but i am also getting an error
Invalid value found at properties.networkAcls.ipRules[3].value: 10.141.131.0/24 belongs to forbidden range 10.0.0.0–10.255.255.255 (private IP addresses).
Please note that I was using this cidr for an NIC/VM and I have just deleted it so it must be free to use now.

**Comment by anstein-msft** [comment]
I got the same error from the portal using a 47.x.x.x IP address.
However, the setting actually saved despite the Portal error. I've never seen that in Azure before :)
