### ISSUE TITLE
sample script

### ISSUE THREAD

**Issue by qqnarwhal** [Azure/azure-cli#7418]
--description is a required parameter. Some of the same script on the page don't include--description and will fail while running. Can this be corrected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d97968df-72c9-e50c-d5b1-54562c1bdef7
* Version Independent ID: 0cde4f15-6464-3106-b787-3ee37c7de0ee
* Content: [az monitor metrics alert](https://docs.microsoft.com/en-us/cli/azure/monitor/metrics/alert?view=azure-cli-latest#az-monitor-metrics-alert-create)
* Content Source: [src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by danishprakash** [comment]
@tjprescott since this has been filed by a bot(maybe), pinging you. Could you add some more context to this issue, I would like to work on it.

**Comment by tjprescott** [comment]
@danishprakash the issue is that the examples for `az monitor metrics create` don't all include the `--description` parameter, but this is required.

**Comment by qqnarwhal** [comment]
@danishprakash @tjprescott Thanks for responding! @tjprescott is correct. Example 1 and 2 doesn't have --description parameter included in the script, therefore when users try copy/paste the commend, it will fail.
