### ISSUE TITLE
"az login --identity" doesn't show subscription name

### ISSUE THREAD

**Issue by jackchenquest** [Azure/azure-cli#7420]
**Describe the bug**
When I use MSI to login az cli, it hide all the subscription name:

az login --identity
EnvironmentName    IsDefault    Name    State    TenantId
-----------------  -----------  ------  -------  ------------------------------------
AzureCloud         True         MSI     Enabled  xxx
AzureCloud         False        MSI     Enabled  xxx

All subscription names are shown as "MSI", not sure if this is by design.

**To Reproduce**
run "az login --identity"
or "az account list"
Name    CloudName    SubscriptionId                        State    IsDefault
------  -----------  ------------------------------------  -------  -----------
MSI     AzureCloud   xxx  Enabled  True
MSI     AzureCloud   yyy  Enabled  False

**Expected behavior**
It should show subscription name same as regular login user.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

Installed from ubuntu apt-get,
Ubuntu 17, bash, 
az --version
azure-cli (2.0.46)

**Comment by yugangw-msft** [comment]
this is by design for the reason that is no longer very legit (creds-sharing with CLI 1.0). I will fix it.

**Comment by yugangw-msft** [comment]
This has been fixed since December 2018
