### ISSUE TITLE
az policy definition create --management-group-name

### ISSUE THREAD

**Issue by kiazhi** [Azure/azure-cli#7421]
**Is your feature request related to a problem? Please describe.**
Yes, my Azure environment is structured by Management Groups with multiple Subscriptions. I'm struggling to use AzureCLI to create policy definition to the Management Group as the definition location.

*Organization Management Groups - Example*
```md
|- Tenant Root
|   |- Organization MG
|   |   |- IT Dept MG
|   |   |   |- Prd Azure Subscription A
|   |   |   |- Dev Azure Subscription A
|   |   |- Services Dept MG
|   |   |   |- Product A
|   |   |   |   |- Product A1 Service
|   |   |   |   |   |- Product Azure Subscription A1
|   |   |   |   |- Product A2 Service
|   |   |   |   |   |- Product Azure Subscription A2
|   |   |   |- Product B
|   |   |   |   |- Product B1 Service
|   |   |   |   |   |- Product Azure Subscription B1
|   |   |   |   |- Product B2 Service
|   |   |   |   |   |- Product Azure Subscription B2
|   |- Subsidiary Organization MG
|   |   |- IT Dept MG
|   |   |   |- Prd Azure Subscription A
|   |   |   |- Prd Azure Subscription B
|   |   |   |- Dev Azure Subscription A
.   .   .   .   .   .
```
**Describe the solution you'd like**
Include the `--management-group-name` parameter to allow policy definition to be created at the management group scope instead of subscription scope.

This is because subscription scope under 6 level of management group cannot be assigned to parent level of management groups which means that i will have to duplicate the same policy with different names to each subscription before assigning it to the resource.

*Proposed Solution - Example*
```sh
az policy definition create \
    --management-group-name "${ManagementGroupName}" \
    --name "${AzurePolicyName}" \
    --display-name "${AzurePolicyDisplayName}" \
    --description "${AzurePolicyDescription}" \
    --mode All \
    --rules "${AzurePolicyRulesFilePath}" \
    --params "${AzurePolicyParametersFilePath}"
```

**Describe alternatives you've considered**
Well. AzureRm module has the `New-AzureRmPolicyDefinition` cmdlet with the `-ManagementGroupName` parameter that currently solved my issue but would like to have the same experience with AzureCLI,

```powershell
New-AzureRmPolicyDefinition `
    -ManagementGroupName $ManagementGroupName `
    -Name $AzurePolicyName `
    -DisplayName $AzurePolicyDisplayName `
    -Description $AzurePolicyDescription `
    -Mode "all" `
    -Policy $AzurePolicyRulesFilePath `
    -Parameter $AzurePolicyParametersFilePath
```

**Comment by yugangw-msft** [comment]
//CC: @williexu
We need to port a few [Azure POSH](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Policy/PolicyCmdletBase.cs#L179-L208) logic over.

**Comment by yugangw-msft** [comment]
#7716 should get this done. Please verify
