### ISSUE TITLE
az functionapp create with with --deployment-container-image-name results in a Function App without the container kind.

### ISSUE THREAD

**Issue by FinVamp1** [Azure/azure-cli#7426]
**Describe the bug**
Create Function App with Azure CLI command: "az functionapp create --name <func name> --resource-group <resource grp> --plan <plan> -s <storage acc> --deployment-container-image-name <image>", the function app is created succssfully but of kind "functionapp,linux" intead of expected "functionapp,linux,container", and there are no "Container settings" blade from "All settings" on Portal.

**To Reproduce**
Steps to reproduce the behavior.

az login
az account set --subscription "CloverSub"
az group create -l southeastasia -n clicontainerfunc2
az storage account create --name clicontainerfunc2storage --location southeastasia --resource-group clicontainerfunc2 --sku Standard_LRS
az appservice plan create --name clicontainerfunc2Plan --resource-group clicontainerfunc2 --sku B1 --is-linux
az functionapp create -g clicontainerfunc2 -p clicontainerfunc2Plan -n clicontainerfunc2 -s clicontainerfunc2storage -i appsvcsample/static-site

**Expected behavior**
It is expected that the resulting Function App should have the container kind applied so that the container can be updated via the portal.

**Environment summary**
CLI Version 2.0.45

**Comment by yugangw-msft** [comment]
@panchagnula, can you take a look?

**Comment by panchagnula** [comment]
@patricklee2 , let me know if this is something you will be able to update. Thank you.

**Comment by patricklee2** [comment]
ill take a look

**Comment by abhilashmk** [comment]
I have observed the below behavior when using Azure CLI for creation of Function Apps on Linux:

When we create a function app on Linux using the command:

**az functionapp create -n yourfunctioname -g yourresourcegroup-p yourAppServicePlan -s storage_account_name -i yourdockerimage**

In the back-end a resource is created which is of “kind” - “**functionapp, linux**”, you can check this is resources.azure.com. Probably the above commands checks for specified image in Public docker hub.

 
After this if we specify App Settings to pull image from Private registry. Basically the Registry URL, username , password using the following command the type changes to “**functionapp,linux,container**”.

**az webapp config container set -n yourfunctioname -g yourresourcegroup -c yourACR_CONTAINER_PATH -r ACR_URL -u ACR_Username -p ACR_Password**
