### ISSUE TITLE
Creating Service Principals with certs and deploying to Windows VM via keyvault fails deployment

### ISSUE THREAD

**Issue by jsturtevant** [Azure/azure-cli#7430]
**Describe the bug**
When using the cert that is generated and stored in the KeyVault with a windows vm we are getting the error `CertificateImproperlyFormatted`.  It seems that the auto generated cert from the CLI is in pem format and so hence the error when it is downloaded during arm deployment.
 
For this to work properly with windows, It looks like we have to download the cert, convert it to PFX, then store it back into keyvault as a Secret and use that url. This "just works on" linux because it is a pem format and no conversion necessary.

**To Reproduce**
Create using a self-signed certificate, and store it within KeyVault.
 
`az ad sp create-for-rbac --keyvault MyVault --cert CertName --create-cert`
 
Then we get the cert url and pass it to an arm template:

``` 
certificateUrl=$(az keyvault secret list-versions --vault-name $VAULT_NAME \
-n $SERVICE_PRINCIPAL_CERT_NAME --query "[?attributes.enabled].id" -o tsv)
```
 
arm template section:
 
```
"secrets": [
{
     "sourceVault": {
       "id": "[concat(resourceGroup().id, '/providers/Microsoft.KeyVault/vaults/', parameters('vaultName'))]"
    },
     "vaultCertificates": [
     {
          "certificateUrl": "[parameters('certificateUrl')]",
        "certificateStore": "My"
   }
  ]
  }
]
```

It fails with:
 
```
code: CertificateImproperlyFormatted
message: The secret retrieved from  ... is not a properly encoded Base64 string
```

**Expected behavior**
The auto generated certificate type can be specified in cli so that it will work for Windows and Linux VM deployments.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**
Work around is to create the cert then convert to pfx:

```
kv=$(az keyvault create -g $RESOURCE_GROUP -n $VAULT_NAME --enabled-for-deployment)
kvID=kv | jq -r .id
service_principal=$(az ad sp create-for-rbac --create-cert --scope $kvID)

cert_file=$(echo $service_principal | jq .fileWithCertAndPrivateKey -r)
openssl pkcs12 -export -in $cert_file -out $cert_file.pfx -passout pass:

az keyvault certificate import --vault-name $VAULT_NAME --file $cert_file.pfx --name $SERVICE_PRINCIPAL_CERT_NAME
```

**Comment by yugangw-msft** [comment]
@jsturtevant, I apologize that we are getting to this so late, but the reason that the cert&key files stay in pem is they are used for AAD service principal's key credential which only takes PEM format. Are you using the cert for `az login` which is what the command was designed for or other purpose?

**Comment by yonzhan** [comment]
add to S165.

**Comment by jiasli** [comment]
The certificate created by `az ad sp create-for-rbac --create-cert` is only designed for RBAC related usage. It is not designed for VM deployment. It is recommended to use `openssl` to create a new certificate instead. Thanks for understanding.

**Comment by scgbear** [comment]
<details>
<summary>Internal Tracking</summary>
CSEF151343
</details>
