### ISSUE TITLE
az storage cors add should accept JSON input

### ISSUE THREAD

**Issue by kamranayub** [Azure/azure-cli#7431]
**Is your feature request related to a problem? Please describe.**

I spent about 2 hours attempting to write a sample where I ingested a JSON file in a bash script and pass the parameters to `az storage cors add` but to no avail (I fully admit bash/Linux is not my forte). I just could not get the multi-value, space separated arguments to work due to quoting/escaping issues. Usually I can stumble my way through something like this but I gave up in frustration.

**Describe the solution you'd like**

I'd ❤️ it if I could just do:

    az storage cors add -i ./rules.json
    az storage cors add --input-file ./rules.json

The output is already JSON for `az storage cors list`, why not allow it to be the input, too?

The PowerShell SDK allows me to easily write:

```
$Rules = @(
  @{ 
        AllowedOrigins = "*";
        AllowedMethods = "GET";
        AllowedHeaders = @("x-ms-request-id", "x-api-key");
        ExposedHeaders = "*";        
        MaxAgeInSeconds = 30
    },
   # etc
)
$Rules | Set-AzureStorageCORSRule
```

**Describe alternatives you've considered**

I tried it in bash then tried in PowerShell Core and got close but still not able to overcome the bash escaping I needed to do (or felt hacky to do).

In the end, I just called `az storage cors add` individually for every rule and manually passed in the values. 😢 

**Additional context**

**Comment by williexu** [comment]
@kamranayub the output for any CLI command defaults to JSON.
Some commands in the CLI do take JSON input(which can refer to a file), however those are usually only for APIs that require JSON object types in the request. 
For `storage cors add`, adding the functionality would be solely for convenience.

I will leave this open for now; if a number of asks for the scenario occur, I can consider adding it.

**Comment by kamranayub** [comment]
@williexu Thanks, if you want to see why it would be nice, check out this demo I tried to do. Since I couldn't put together anything for the learner, I just decided to do the individual commands but the PS version has a nice array input I used.

https://app.pluralsight.com/player?course=microsoft-azure-storage-cors-access-configuring&author=kamran-ayub&name=da4e8a34-7a7d-42cf-adf0-6a1a1e797db0&clip=7&mode=live

Timestamp 3:23

**Comment by zhoxing-ms** [comment]
@kamranayub  Sorry, this command is not recommended to use JSON files because the parameter structure passed in is not complex. The problem you want to solve is that you don't want to expose parameters during execution?

**Comment by kamranayub** [comment]
To me it seems more of an automation and PowerShell parity issue. It's hard to write automation that sets a list of CORS rules using az CLI, as you can see by the Pluralsight clip I mentioned before. With PowerShell it's quite easy to do but if writing automation using az CLI it's a huge pain.

The feature doesn't necessarily need to be implemented if the documentation could provide an example of using JSON to read and set CORS rules. I just couldn't figure it out after some hours of tinkering with a script.

I will be updating the course soon and it would be awesome to be able to have an example taking a JSON structure and using az CLI to set CORS rules in one command.

**Comment by zhoxing-ms** [comment]
Sorry, Pluralsight is a paid website that requires payment channels outside of China, which I haven't handled these payment channels before. So I can't see it.
The JSON data is currently not recommended on this command, and I'll see if there are other solutions.

**Comment by zhoxing-ms** [comment]
@kamranayub I want to make sure that your problem is that it's difficult to parse the data in JSON in an automated script and then split it up into the parameters of azure-cli command, right? 
If so, Could you please give me a specific JSON example that is difficult to parse?

**Comment by zhoxing-ms** [comment]
Because there is no reply to this question for a long time, I will close it temporarily. If you have any questions, please feel free to let us know.

**Comment by kamranayub** [comment]
Sorry, here's a clear example. You can do this in PowerShell, you can't do this easily in `az cli`

https://github.com/kamranayub/pluralsight-azure-cors-storage/blob/master/Module%203/demo-azure-powershell/03-Set-Cors-Rules.ps1

This is what I had to present in my course:

https://github.com/kamranayub/pluralsight-azure-cors-storage/blob/master/Module%203/demo-azure-cli/03-add-cors-rules.sh

If you can come up with a script or Bash syntax to translate that JSON into `az cli` calls, that's acceptable but I'd argue it's not very easy to use.
