### ISSUE TITLE
Rate-limiting function

### ISSUE THREAD

**Issue by udf2457** [Azure/azure-cli#7432]
As far as I can tell, there is no option to rate-limit throughput in `az`.

For example, when doing a large BLOB upload, it would be nice to be able to limit to _x_ Mbps.

**Comment by yugangw-msft** [comment]
> As far as I can tell, there is no option to rate-limit throughput in az.

Correct.

For `az storage blob upload` @williexu, do you know?

**Comment by williexu** [comment]
@udf2457 there is currently no option to limit throughput for `az storage blob upload`.
@zezha-msft is this possible through the storage sdk?

**Comment by zezha-msft** [comment]
Hi @williexu and @udf2457, you are right that the SDK does not support rate limiting at the moment. It is on our radar but hasn't become a priority. 

@udf2457, what's the reason that you need the rate-limit? Is it because of Storage account throttling(service returns 503s if ingestion is too high)?

**Comment by udf2457** [comment]
@zezha-msft 

The primary reason is simply efficient use of client-side banwidth.  Sometimes, for whatever reason, it is not appropriate to allow Azure ingestion to take 100% of available bandwidth.  As outlined above, achieving rate limiting using built-in OS tools such as `tc` is difficult and error prone due to complex and poorly documented syntax as well as limited support options because of the lack of community usage of `tc`.

So I was thinking more in terms of throughput rate-limiting when ingesting large BLOBs, rather than pure rate-limiting, such as you outline, in relation to ingestion-rate.

**Comment by zezha-msft** [comment]
@udf2457  thanks for the explanation!

I've added this item to our backlog and will discuss it with my team.

**Comment by tjprescott** [comment]
Since this is on Storage team's backlog and is a service/SDK issue instead of a CLI issue, I'm closing this thread.

**Comment by udf2457** [comment]
@tjprescott Just to check we're singing from the same hymn sheet here.... the Storage team are planning to implement throughput rate-limiting server-side ?!?

I'm not fussed how you do it, whether server-side or client-side CLI, as long as someone implements it !  Doing it server-side would certainly be innovative.  :smiley:

**Comment by tjprescott** [comment]
It could be done server-side or client-side via the SDK.
