### ISSUE TITLE
webapp:Key=Value formats unclear

### ISSUE THREAD

**Issue by rambotech** [Azure/azure-cli#7433]
Can you please add some clarification on the format of key=value on the command line.  How would I add the following:

message=Hello World

or

items=one;two;three

connection-string allows use of apostrophes on the value portion, but this does not work in appsettings.  I have tried the following and all fail with 400 Client error.

az webapp config appsettings set -g MyGroup -n servername --settings ...

message=Hello World
message='Hello World'
"message=Hello World"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30f2ae52-2c7f-7e7e-8a62-f1b614f281d3
* Version Independent ID: 9f23ff17-14e0-7800-0094-fb50a5fa91d6
* Content: [az webapp config appsettings](https://docs.microsoft.com/en-us/cli/azure/webapp/config/appsettings?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config/appsettings.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/webapp/config/appsettings.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
On windows use `"name=value"`.
On nix, use `'name=value'`

**Comment by danishprakash** [comment]
@yugangw-msft should this be added to the docs? I'm taking this up if nobody else is.

**Comment by nmeuret** [comment]
Can you also clarify the escape characters to use ? For example this doesn't work :

--settings "server-password=abcdexyz"   -> Operation returned an invalid status code 'Bad Request'

Any idea ??

**Comment by yugangw-msft** [comment]
We have documented this, please see [this](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#quoting-issues), particularly the point 6

**Comment by nmeuret** [comment]
> We have documented this, please see [this](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#quoting-issues), particularly the point 6, also the same command support to take json file through syntax of `@<file>`

Unfortunatly, it's not answering my question. I do use quotes for the settings argument, but what doesn't work is the '-' character. Maybe there is more characters making trouble, and using quotes doesn't help at all.

**Comment by yugangw-msft** [comment]
can you please run with `--debug` and tell me about the payload on the wire?
