### ISSUE TITLE
Multiply values on "--source-address-prefixes" field

### ISSUE THREAD

**Issue by IvanKirianov** [Azure/azure-cli#7439]
az network nsg rule create -g $resource_group --nsg-name $nsg_name -n $rule_name --priority $priority --access $policy --source-address-prefixes "192.168.1.1,192.168.1.2" --destination-address-prefixes $destination --protocol $protocol --destination-port-ranges $destination_port --description $downloadUri

Is it possible to add in --source-address-prefixes 2 or more IP's as I describe in my command above?

For now, error occurred: "has invalid Address prefix. Value provided:192.168.1.1,192.168.1.2"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afe4941c-7b46-b9fb-1c52-98e68f6354cc
* Version Independent ID: d1bc72fb-ccf9-9645-7b1d-98c91bc75a55
* Content: [az network nsg rule](https://docs.microsoft.com/en-us/cli/azure/network/nsg/rule?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
The help is fine at `Space-separated list of CIDR prefixes or IP ranges`, which means `--source-address-prefixes 192.168.1.1 192.168.1.2`. Wrapping all within a pair of double quotes would make command parser treat as a single value instead of an array.
@sptramer would it make sense we have a general doc to clarify the area when an argument value is defined as an array, and how to use double and single quote correctly? I ran into a similar case yesterday.

**Comment by sptramer** [comment]
I don't think the problem here is conceptual documentation, because it's a one-sentence description, which isn't even always true right now ("multiple values to a CLI argument are separated by spaces."). The problem is more likely a lack of consistency and people not reading the inline help where usage isn't clear.

**Comment by yugangw-msft** [comment]
The majority are indeed `multiple values to a CLI argument are separated by spaces` because that is what generic `argparse` enforces, not CLI.
If you run into other cases, please let me know that I can migrate to the correct case

**Comment by tjprescott** [comment]
The help text is correct here and consistent with the overwhelming majority of the rest of the CLI. If there are exceptions to the space-separated rule, I'm not aware of them.

**Comment by stoune** [comment]
This just don't work. 
If I supply 
`--source-address-prefix "195.xxx.xxx.0/22 xx.xxx.201.0/24"` 
I get an error 
`Security rule /subscriptions/<subscr guid>/resourceGroups/resgroup/providers/Microsoft.Network/networkSecurityGroups/AnsibleVMNSG/securityRules/default-allow-ssh has invalid Address prefix. Value provided: 1195.xxx.xxx.0/22 xx.xxx.201.0/24`
Parser is broken. 
I can't supply multiple values neither for tags, or source-address-prefix.

**Comment by Yiyito11** [comment]
Same Here I would like to add 2 single IPs and a private IP range. Is this possible?
Im using: `--source-address-prefixes `--source-address-prefixes "10.240.0.0/21 10.224.2.44" `
(also tried with single quote)
And I´m getting:
**_invalid Address prefix. Value provided: 10.240.0.0/21 10.224.2.44_**

**Comment by Yiyito11** [comment]
just put values without double quotes.

> --source-address-prefix 195.xxx.xxx.0/22 xx.xxx.201.0/24

**Comment by ersameed** [comment]
Hi,
I am facing a similar problem, unable to pass the variable. I need to create rules frequently. 
This is what i am doing 

group=PDC
nsg=mynsg
rule=allowweb
sourceip='10.10.01.5/32 192.168.1.10/32'
destinationport="*"

az network nsg rule create -g $group --nsg-name $nsg -n $rule --priority 500 \
    --source-address-prefixes $sourceip --source-port-ranges '*' \
    --destination-address-prefixes '*' --destination-port-ranges $destinationport --access Allow \
    --protocol Tcp --description $rule

It is not allowing me to pass the value as a variable.

**Comment by mloskot** [comment]
Since it seems examples above are based on the PowerShell and the issue is the arguments parsing, here is the correct command 

```powershell
$AzAddresses="192.168.1.1,192.168.1.2"

az network nsg rule create `
  --resource-group $AzResourceGroup `
  --nsg-name $AzNsg `
  --name Allow-HTTP `
  --access Allow `
  --protocol Tcp `
  --direction Inbound `
  --priority 101 `
  --source-address-prefixes ($AzAddresses.split(',')) `
  --source-port-range "*" `
  --destination-address-prefix "*" `
  --destination-port-range 80
```

**Comment by ianroberts** [comment]
> The help is fine at `Space-separated list of CIDR prefixes or IP ranges`, which means `--source-address-prefixes 192.168.1.1 192.168.1.2`. Wrapping all within a pair of double quotes would make command parser treat as a single value instead of an array.

I would say that the description is wrong - saying it expects a "space-separated list" suggests that the tool wants _one_ argument whose value is a space-separated list of multiple CIDRs, whereas what it actually requires is one _or more_ separate arguments containing _exactly one_ CIDR each.

"Space-separated" is an artefact of how command shells do word splitting rather than a specific required format (if I were to call this tool from C code with an `execvp` call then each CIDR would have to be a separate entry in the args array, and none of the args would contain any space characters).

**Comment by asos-tommycouzens** [comment]
In powershell this does not behave expectedly.

The following do not work:
```pwsh
az network nsg rule create --source-address-prefixes "104.119.188.0/24 104.71.131.0/24"
```

or without quotes
```pwsh
az network nsg rule create --source-address-prefixes 104.119.188.0/24 104.71.131.0/24
```

The follow, somehow, does work though:
```pwsh
prefixes = @("104.119.188.0/24, 104.71.131.0/24")
az network nsg rule create --source-address-prefixes $prefixes
```

but ONLY if `$prefixes` does not have quotes around it.

This caused me quite a lot of headache until I figured it out. Any way to reopen this issue?

**Comment by JawnnyB** [comment]
Agreed that this is a huge headache and not entirely clear based on the "Space-separated list of CIDR prefixes or IP ranges"

IP1=192.168.1.1
IP2=192.168.1.2
IP3=192.168.1.3

**Comment by rafatorgar** [comment]
> Agreed that this is a headache and not entirely clear based on the "Space-separated list of CIDR prefixes or IP ranges"
> 
> The following works - would be nice to add as an additional example possibly.
> 
> AZ1=192.168.1.0/24 AZ2=192.168.2.0/24 AZ3=192.168.3.0/24
> 
> az network nsg rule create --source-address-prefixes $AZ1 $AZ2 $AZ3

Using this reference, for me also worked defining an array of prefixes and then using it into the param: `--source-address-prefixes ${PREFIXES[@]}`
