### ISSUE TITLE
Cloud Shell: 'kubectl get <object>' returns "Error from server (NotAcceptable): unknown"

### ISSUE THREAD

**Issue by yamlCase** [Azure/azure-cli#7440]
**Describe the bug**
When using the azure portal's embedded Cloud Shell with BASH (appears to be Ubuntu 16.04.05 LTS), running any `kubectl get <object>` commands results in the following error:

```
$ kubectl get nodes
No resources found.
Error from server (NotAcceptable): unknown (get nodes)
```

This appears to be a bug with Kubernetes 1.11.x's new "Server-side columns" feature where custom columns can be provided by the Master server ([Link to reference](https://kubernetes.io/docs/reference/kubectl/overview/#server-side-columns)).  

**Workaround**
For those wishing to workaround the issue, pass a ` --server-print=false` parameter:

```
$ kubectl --server-print=false get nodes
NAME                    STATUS    ROLES     AGE       VERSION
k8s-agent-e0424423-0    Ready     agent     1h        v1.7.7
k8s-agent-e0424423-1    Ready     agent     1h        v1.7.7
k8s-agent-e0424423-2    Ready     agent     1h        v1.7.7
k8s-master-e0424423-0   Ready     master    1h        v1.7.7
```

**To Reproduce**

- in the Azure web portal, in the top right , click the Cloud Shell icon.  Looks like this:  `>_`
- Choose the "BASH" environment
- If you don't already have a group created, create one:
```
az group create --name=<group-name> --location=<location>
```
- Create a kubernetes cluster if you don't already have one: 
```
az acs create --orchestrator-type=kubernetes \
--resource-group=<group-name> --name=<cluster-name> \
--ssh-key-value="<paste your PUBLIC SSH key>"
```
- once the kluster create is finished, run some 'kubectl get' commands:

```
kubectl get componentstatuses
kubectl get nodes
kubectl get pods
```

**Expected behavior**
The Failure will be an error that reads:
```
No resources found.
Error from server (NotAcceptable): unknown (get <object>)
```

**Environment summary**
Detailed in bug description

**Additional context**
Reference for Kubernetes bug: https://github.com/kubernetes/kubernetes/issues/65575

**Comment by yugangw-msft** [comment]
Closing as `az acs` is deprecating
