### ISSUE TITLE
az disk revoke-access fails with "The response from long running operation does not contain a body"

### ISSUE THREAD

**Issue by jswoodward** [Azure/azure-cli#7450]
After updating the python libraries via azure and the azure-cli metapackages, running az disk revoke-access now fails with:
Deployment failed. Correlation ID: 48df2ae3-53e3-4e9e-ad79-7c9f8bff457f. The response from long running operation does not contain a body.

Python versions installed:
azure==4.0.0                                                        
azure-applicationinsights==0.1.0                                    
azure-batch==4.1.3                                                  
azure-cli==2.0.46                                                   
azure-cli-acr==2.1.5                                                
azure-cli-acs==2.3.4                                                
azure-cli-advisor==0.6.0                                            
azure-cli-ams==0.2.3                                                
azure-cli-appservice==0.2.4                                         
azure-cli-backup==1.2.1                                             
azure-cli-batch==3.4.0                                              
azure-cli-batchai==0.4.3                                            
azure-cli-billing==0.2.0                                            
azure-cli-cdn==0.1.1                                                
azure-cli-cloud==2.1.0                                              
azure-cli-cognitiveservices==0.2.3                                  
azure-cli-command-modules-nspkg==2.0.2                              
azure-cli-configure==2.0.18                                         
azure-cli-consumption==0.4.0                                        
azure-cli-container==0.3.4                                          
azure-cli-core==2.0.46                                              
azure-cli-cosmosdb==0.2.1                                           
azure-cli-dla==0.2.3                                                
azure-cli-dls==0.1.3                                                
azure-cli-dms==0.1.1                                                
azure-cli-eventgrid==0.2.0
azure-cli-eventhubs==0.2.4
azure-cli-extension==0.2.1
azure-cli-feedback==2.1.4
azure-cli-find==0.2.12
azure-cli-interactive==0.3.30
azure-cli-iot==0.3.2
azure-cli-keyvault==2.2.3
azure-cli-lab==0.1.1
azure-cli-monitor==0.2.3
azure-cli-network==2.2.5
azure-cli-nspkg==3.0.3
azure-cli-profile==2.1.1
azure-cli-rdbms==0.3.2
azure-cli-redis==0.3.2
azure-cli-reservations==0.4.0
azure-cli-resource==2.1.4
azure-cli-role==2.1.5
azure-cli-search==0.1.1
azure-cli-servicebus==0.2.3
azure-cli-servicefabric==0.1.3
azure-cli-sql==2.1.4
azure-cli-storage==2.2.2
azure-cli-telemetry==1.0.0
azure-cli-vm==2.2.3
azure-common==1.1.16
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.5
azure-datalake-store==0.0.31
azure-eventgrid==1.2.0
azure-graphrbac==0.40.0
azure-keyvault==1.1.0
azure-loganalytics==0.1.0
azure-mgmt==4.0.0
azure-mgmt-advisor==1.0.1
azure-mgmt-applicationinsights==0.1.1
azure-mgmt-authorization==0.50.0
azure-mgmt-batch==5.0.1
azure-mgmt-batchai==2.0.0
azure-mgmt-billing==0.2.0
azure-mgmt-cdn==3.0.0
azure-mgmt-cognitiveservices==3.0.0
azure-mgmt-commerce==1.0.1
azure-mgmt-compute==4.1.0
azure-mgmt-consumption==2.0.0
azure-mgmt-containerinstance==1.1.0
azure-mgmt-containerregistry==2.2.0
azure-mgmt-containerservice==4.2.2
azure-mgmt-cosmosdb==0.4.0
azure-mgmt-datafactory==0.6.0
azure-mgmt-datalake-analytics==0.2.0
azure-mgmt-datalake-nspkg==3.0.0
azure-mgmt-datalake-store==0.5.0
azure-mgmt-datamigration==0.1.0
azure-mgmt-devspaces==0.1.0
azure-mgmt-devtestlabs==2.2.0
azure-mgmt-dns==2.1.0
azure-mgmt-eventgrid==0.4.0
azure-mgmt-eventhub==2.1.0
azure-mgmt-hanaonazure==0.1.1
azure-mgmt-iotcentral==0.1.0
azure-mgmt-iothub==0.5.0
azure-mgmt-iothubprovisioningservices==0.2.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-loganalytics==0.2.0
azure-mgmt-logic==3.0.0
azure-mgmt-machinelearningcompute==0.4.1
azure-mgmt-managementgroups==0.1.0
azure-mgmt-managementpartner==0.1.0
azure-mgmt-maps==0.1.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-media==1.0.0rc1
azure-mgmt-monitor==0.5.2
azure-mgmt-msi==0.2.0
azure-mgmt-network==2.2.1
azure-mgmt-notificationhubs==2.0.0
azure-mgmt-nspkg==3.0.0
azure-mgmt-policyinsights==0.1.0
azure-mgmt-powerbiembedded==2.0.0
azure-mgmt-rdbms==1.3.0
azure-mgmt-recoveryservices==0.1.0
azure-mgmt-recoveryservicesbackup==0.1.1
azure-mgmt-redis==5.0.0
azure-mgmt-relay==0.1.0
azure-mgmt-reservations==0.2.1
azure-mgmt-resource==2.0.0
azure-mgmt-scheduler==2.0.0
azure-mgmt-search==2.0.0
azure-mgmt-servicebus==0.5.2
azure-mgmt-servicefabric==0.2.0
azure-mgmt-signalr==0.1.1
azure-mgmt-sql==0.9.1
azure-mgmt-storage==2.0.0rc4
azure-mgmt-subscription==0.2.0
azure-mgmt-trafficmanager==0.50.0
azure-mgmt-web==0.35.0
azure-multiapi-storage==0.2.2
azure-nspkg==3.0.0
azure-servicebus==0.21.1
azure-servicefabric==6.3.0.0
azure-servicemanagement-legacy==0.20.6
azure-storage-blob==1.1.0
azure-storage-common==1.1.0
azure-storage-file==1.3.1
azure-storage-nspkg==3.0.0
azure-storage-queue==1.3.0
msrestazure==0.5.0

**Comment by yugangw-msft** [comment]
Likely the same thing like #7413 where disk access commands were broken by bad SDKs. Please reactivate if you still see it in the upcoming release on next Tuesday.
