### ISSUE TITLE
Better support for Fiddler

### ISSUE THREAD

**Issue by collinsauve** [Azure/azure-cli#7455]
**Describe the bug**
When Fiddler (or any other mitm debugging proxy) is running, `az` does not work.  This happens even if the Fiddler cert is trusted by the OS (Windows). 

**To Reproduce**
1. Install Fiddler
2. Configure Fiddler to decrypt HTTPS requests
3. Install Fiddler cert to Windows cert store
4. Begin capturing requests in Fiddler
5. Run `az login --use-device-code` (chosen as a demonstration only, other commands also fail)

You will see this:

```
Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/devicecode?api-version=1.0 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
```

**Expected behavior**
`az` begins old login flow. 

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

Windows, installed via the [msi](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest) a couple of weeks ago

**Additional context**
There are two semi-workarounds that are **insufficient**:

1. [AZURE_CLI_DISABLE_CONNECTION_VERIFICATION](https://github.com/Azure/azure-cli/issues/1572).  This is **UNSAFE** and should not be used.
2. `REQUESTS_CA_BUNDLE`.  This allows me to specify a path to the Fiddler cert and az will now work when Fiddler is running, however it will no longer work while Fiddler is not running.  Given that a typical developer will turn Fiddler on and off multiple times throughout the day it is not feasible to expect to constantly flip environment variables.

Please either use the OS cert store or allow a way to support this scenario.

**Comment by collinsauve** [comment]
Alternatively is there a way to tell `az` not to use the system proxy? ie Never use Fiddler?

**Comment by collinsauve** [comment]
We've found a solution that solves this for our team:  set `NO_PROXY=1`.

**Comment by yugangw-msft** [comment]
@lmazuel, does requests package support to read OS's certificate store?
Based on this [Python issue](https://bugs.python.org/issue28547) it doesn't; however this [SO thread](https://stackoverflow.com/questions/42981429/ssl-failure-on-windows-using-python-requests) mentioned it is possible, but is it reliable?

**Comment by lmazuel** [comment]
@yugangw-msft no, requests does not support it. If I understood correctly, @zooba is working on this.

**Comment by yugangw-msft** [comment]
I am closing this issue as it is clearly not an issue CLI can address and we have a [document](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy) which calls out all required steps to get this working.

**Comment by mikeblakeuk** [comment]
"clearly". Can you include the actual steps required for developers who are not used to hacking certs
e.g.

https://techcommunity.microsoft.com/blog/azurepaasblog/capturing-powershell-and-az-cli-rest-api-calls/3960926
