### ISSUE TITLE
AZ cli is fialed to install on ubuntu for xenail 

### ISSUE THREAD

**Issue by vamsi248** [Azure/azure-cli#7458]
gnutls_handshake() failed: Error in the pull function.

W: The repository 'https://packages.microsoft.com/repos/azure-cli xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://packages.microsoft.com/repos/azure-cli/dists/xenial/main/binary-amd64/Packages  gnutls_handshake() failed: Error in the pull function.
E: Some index files failed to download. They have been ignored, or old ones used instead.---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

**Comment by tjprescott** [comment]
Please try installing again. The Xenial package of CLI is available.
