### ISSUE TITLE
VNET support for Azure Container Instances didn't make it into 2.0.64

### ISSUE THREAD

**Issue by hairmare** [Azure/azure-cli#7464]
**Describe the bug**
When I try using `az container create` with the new `--vnet-name` and `--subnet` args that should be available as preview I get the following error:
```
az: error: unrecognized arguments: --vnet-name vnet-portal --subnet aci-subnet
```
**To Reproduce**
Use the latest `2.0.46` version of the azure-cli to try creating a container in a private VNET.

**Expected behavior**
I would expect what is documented [here](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-vnet) and in the [CLI docs](https://docs.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest#optional-parameters) to work out of the box. I'm aware that the docs link points to "latest" but it's what ~~Google~~ Bing shows as first result.

**Environment summary**
* nothing special

**Additional context**
It works when I use the `azuresdk/azure-cli-python:dev` container image. I guess this will be resolved in the next release of the CLI and this issue simply serves the purpose of trying to surface that a new release of azure-cli would be nice now that docs describe how I can use the mentioned arguments.

**Comment by tjprescott** [comment]
I have verified these arguments appear and are accepted in CloudShell, CLI version 2.0.46.  How did you install the CLI?

**Comment by hairmare** [comment]
Thanks for the reply. My installation of the azure cli was done locally using `pip install azure-cli` a while ago. I have been keeping it up to date using `az install --upgrade azure-cli`. It look like my local installation didn't upgrade all the parts of the CLI, I still had `container (0.3.3)`. I was able to fix this by running `pip install --upgrade azure-cli-container`. It looks like I'm going to deprecate my local installation and switch to using the docker version to take care of this in future.

**Comment by tjprescott** [comment]
Pip install is not a recommend install method. The reason is because, just as you found, when you run `pip install --upgrade azure-cli` it only updates that one package, not all of the individual modules. This will likely result in many issues. For recommended installation methods, see:
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest
