### ISSUE TITLE
Resource could not be found when exporting ARM template, but it's there when listing resources in resource group

### ISSUE THREAD

**Issue by tappoz** [Azure/azure-cli#7466]
**Describe the bug**

When trying to export a Stream Analytics Job the `az` fails stating: `Deployment '<MY_SAJ_NAME>' could not be found.`, however that resource is there in that resource group.

**To Reproduce**

```bash
$ # 
$ # Check the Resource Group exists
$ # 
$ az group exists --name <MY_RESOURCE_GROUP_NAME>
true
$ # 
$ # Check the Resource exists
$ # 
$ az resource list --resource-group <MY_RESOURCE_GROUP_NAME> | grep -B 6 -A 7 '"name": "<MY_SAJ_NAME>"'
  {
    "id": "/subscriptions/<SOME_GUID>/resourceGroups/<MY_RESOURCE_GROUP_NAME>/providers/Microsoft.StreamAnalytics/streamingjobs/<MY_SAJ_NAME>",
    "identity": null,
    "kind": null,
    "location": "<AZURE_LOCATION>",
    "managedBy": null,
    "name": "<MY_SAJ_NAME>",
    "plan": null,
    "properties": null,
    "resourceGroup": "<MY_RESOURCE_GROUP_NAME>",
    "sku": null,
    "tags": null,
    "type": "Microsoft.StreamAnalytics/streamingjobs"
  },
$ # 
$ # Attempt at exporting the existing Resource
$ # 
$ az group deployment export --name <MY_SAJ_NAME> --resource-group <MY_RESOURCE_GROUP_NAME> > foo.json
Deployment '<MY_SAJ_NAME>' could not be found.
```

**Expected behavior**

I am expecting to export the ARM template for that resource, but it's not possible even if the resource is there on Azure.

**Environment summary**

- The `az` command is a Debian package (`apt-get` from this repository: `deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main`)
- The `az` CLI version is: `azure-cli (2.0.43)`
- The Operating System is: `Debian GNU/Linux 9.5 (stretch)` (found out with `lsb_release -a | grep Description`)
- Shell Type: `bash` (found out comparing outputs from `ps -p $$` and `echo $SHELL`)

**Comment by tjprescott** [comment]
```
Command
    az group export : Captures a resource group as a template.

Arguments
    --name --resource-group -g -n [Required] : Name of resource group. You can configure the default
                                               group using `az configure --defaults group=<name>`.
    --include-comments                       : Export template with comments.
    --include-parameter-default-value        : Export template parameter with default value.
```

You are giving conflicting information to the CLI. Group export is used to export a resource group only, not a specific resource. The correct syntax should be `az group deployment export -g <MY_RESOURCE_GROUP_NAME>`
