### ISSUE TITLE
log streaming should reconnect when app restarts

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-cli#7468]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
log streaming should reconnect when app restarts

If a user is streaming logs from a web app, and the app recycles/restarts, the command should reconnect once the scm site is back up

**Comment by panchagnula** [comment]
Not sure what is the ask for CLI here - we just call the SCM API to get logs.
