### ISSUE TITLE
Application Gateway creation fails for SKUs WAF_v2 & Standard_v2

### ISSUE THREAD

**Issue by MichaelMcCoyDNVGL** [Azure/azure-cli#7472]
Unable to create an Application Gateway of SKU's WAF_v2 & Standard_v2 using CLI.

**To Reproduce**
```
az network application-gateway create --name scriptedv2gateway --sku WAF_v2

or 

az network application-gateway create --name scriptedv2gateway --sku Standard_v2
```

**Expected behavior**
I would expect it to create the application gateway but instead it gives error
```
Azure Error: InvalidTemplateDeployment
Message: The template deployment 'ag_deploy_YNI0HkJEk5l40QPeGofIauqm28Gqiw7G' is not valid according to the validation procedure. The tracking id is '5dde08b6-fd7f-41d4-bdfa-4add678c3748'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.
Exception Details:


        Error Code: ApplicationGatewaySkuNameInvalidForSkuTier
        Message: Application Gateway SKU name WAF_v2 is not valid for the SKU tier WAF

OR

Azure Error: InvalidTemplateDeployment
Message: The template deployment 'ag_deploy_8EJ0WfA2mFGULffCLbeF3Qdirw9Pqz5q' is not valid according to the validation procedure. The tracking id is 'a42bfa7e-d72b-442c-abc0-d2d74522e1f5'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.
Exception Details:


        Error Code: ApplicationGatewaySkuNameInvalidForSkuTier
        Message: Application Gateway SKU name Standard_v2 is not valid for the SKU tier Standard

```

**Environment summary**
Windows 10
azure-cli (2.0.46)

acr (2.1.5)
acs (2.3.4)
advisor (0.6.0)
ams (0.2.3)
appservice (0.2.4)
backup (1.2.1)
batch (3.4.0)
batchai (0.4.3)
billing (0.2.0)
botservice (0.1.1)
cdn (0.1.1)
cloud (2.1.0)
cognitiveservices (0.2.3)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.4)
core (2.0.46)
cosmosdb (0.2.1)
dla (0.2.3)
dls (0.1.3)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.2.4)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.30)
iot (0.3.2)
iotcentral (0.1.2)
keyvault (2.2.3)
lab (0.1.1)
maps (0.3.2)
monitor (0.2.3)
network (2.2.5)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.2)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.0)
resource (2.1.4)
role (2.1.5)
search (0.1.1)
servicebus (0.2.3)
servicefabric (0.1.3)
signalr (1.0.0)
sql (2.1.4)
storage (2.2.2)
telemetry (1.0.0)
vm (2.2.3)

**Comment by tjprescott** [comment]
Thank you for the report @MichaelMcCoyDNVGL. This will be fixed in an upcoming release. In the meantime, you can run the command with `--validate --verbose` to extract the ARM template that underlies this create. Then, in the "sku" properties for the gateway, change "tier" to match "name".  You should then be able to deploy this template with `az group deployment create …` to create your gateway.
