### ISSUE TITLE
Calculate the size of a Blob storage container

### ISSUE THREAD

**Issue by imeya** [Azure/azure-cli#7485]
In this tutorial: [Calculate the size of a Blob storage container](https://docs.microsoft.com/en-us/azure/storage/scripts/storage-blobs-container-calculate-size-cli), it throws an error: "bash bc: command not found", so I wonder is there something missing which caused the "bc" cannot find?

I used  the could shell button in azure portal.

**Comment by tjprescott** [comment]
The `bc` utility it not present on the Cloud Shell image.

**Comment by imeya** [comment]
@tjprescott, so I can only run it from an Linux client? and in cloud shell, is there anyway I can do the same thing instead of `bc`?

**Comment by tjprescott** [comment]
@imeya you would need to reach out to the authors of the blog. They are listed near the top of the article as contributors.
