### ISSUE TITLE
list-sku is not updated

### ISSUE THREAD

**Issue by ralucasg** [Azure/azure-cli#7486]
" az vm list-skus --help

Command
    az vm list-skus: Get details for compute-related resource SKUs.
        This command incorporates subscription level restriction, offering the most accurate
        information.

Arguments
    --location -l: Location. You can configure the default location using `az configure --defaults
                   location=&lt;location&gt;`.

Global Arguments
    --debug      : Increase logging verbosity to show all debug logs.
    --help -h    : Show this help message and exit.
    --output -o  : Output format.  Allowed values: json, jsonc, table, tsv.  Default: json.
    --query      : JMESPath query string. See http://jmespath.org/ for more information and
                   examples.
    --verbose    : Increase logging verbosity. Use --debug for full debug logs.

Examples
    List all SKUs in the West US region.
        az vm list-skus -l westus "
As a result --zone and --size do not work as stated and there's no example for --query

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 152b549b-d4b3-13e5-081c-c604b6e4d89e
* Version Independent ID: 3f79be78-ce75-ad31-304b-bad7d475ec9e
* Content: [az vm](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-list-sizes)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
The `--zone` flag and `--size` argument do work as intended. If you don't see them, you likely need to update your CLI installation.
