### ISSUE TITLE
Required Arguments

### ISSUE THREAD

**Issue by Bnjmn83** [Azure/azure-cli#7487]
&gt; az ad app create --display-name my-nativ
leaves me with _'--identifier-uris' is required for creating an application_ although the documentation states that only _--display_name_ is required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 921aa920-c25f-5227-aabb-49116da38fa7
* Version Independent ID: 9b5a53ad-edf8-4d89-f8e6-cde01b7866f6
* Content: [az ad app](https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest#az-ad-app-show)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
`--display-name` is required in all cases.  Depending on the option you provide, `--identifier-uris` may or may not be required.
