### ISSUE TITLE
azure cli - download certificate as pfx format 

### ISSUE THREAD

**Issue by wlodekb** [Azure/azure-cli#7489]
az keyvault certificate download --file
                                 [--encoding {DER, PEM}]
On azure web-portal (also in PS) there is an option to download as pfx. Why it is missing in az cli then?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9c661d7-bf43-5354-015e-3859f30a42a2
* Version Independent ID: fa69e552-5904-ce97-d02c-915c819bdde1
* Content: [az keyvault certificate](https://docs.microsoft.com/en-us/cli/azure/keyvault/certificate?view=azure-cli-latest#az-keyvault-certificate-download)
* Content Source: [src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by bradwilson** [comment]
You can do that today in two steps.

First, download the certificate with `az keyvault secret download`, which will download the raw PFX as Base64-encoded text. Then undo the Base64 encoding, and you have the binary PFX file.

I don't know why, but the certificate APIs only want to return the public part of the certificate, which is why `az keyvault certificate download` doesn't offer PFX as an option. If you download the certificate as a secret (even though it's not a secret), it downloads the raw PFX (with no password).

Go figure. 🤷‍♂️

**Comment by wlodekb** [comment]
@bradwilson :+1: thx, but still there in inconsistent API between CLI and Powershell (with Azure Portal).
IMHO at least it should be mentioned in the docs how to download pfx through CLI with your workaround.

**Comment by apurvc** [comment]
My use case was getting the pfx from keyvault and upload that in Azure Apim instance, we tried what @bradwilson has suggested and then uploaded the pfx via Rest API. 

Not sure if that is the best option but that has worked.

**Comment by cristhianbicca** [comment]
My use case is:
Generate pem with cert and key, after this imported in azure:
az keyvault certificate import --file certandkey.pem --name test --vault-name kevaulttest

When download in Azure:
az keyvault certificate download --vault-name kevaulttest -n test -f certificate.pem

Only certificate with:

 -----BEGIN CERTIFICATE----- -----END CERTIFICATE-----

Private key not show in certificate.pem

But when I download the secret, comes the private key + certificate

**Comment by bradwilson** [comment]
This is just how these APIs work in Azure Key Vault. The "get certificate" API is only intended to permit access to the public part of the certificate; if you need access to the private key, then you request the certificate through the "get secret" API.

**Comment by akshita31** [comment]
I had to use the cert in a tomcat server. The problem was that the downloaded cert didnt contain the password, hence I had to import and then export the cert again with the password.

Here is the code : 
az keyvault secret download \
    --file inputCert.pfx \
    --vault-name MyKeyvault \
    --encoding base64 \
    --name inputCert \
    2>&1 \
    | tee -a $SETUP_LOG

echo "Converting downloaded cert to pem format"
openssl pkcs12 -in inputCert.pfx -out temp.pem -nodes -password pass:""

echo "Converting the cert with the password"
openssl pkcs12 -export -out outputCert.pfx -in temp.pem -password pass:"yourpassword"

**Comment by andrewboxer** [comment]
I import a pkcs12 certificate via the cli but cannot get it back? 
why use key vault for this at all?
I'm going to store my certs as blobs. 
This is not a vault, if I put something into a vault I expect to get it back exactly as it was when I put it in.

**Comment by mbactol3** [comment]
> You can do that today in two steps.
> 
> First, download the certificate with `az keyvault secret download`, which will download the raw PFX as Base64-encoded text. Then undo the Base64 encoding, and you have the binary PFX file.
> 
> I don't know why, but the certificate APIs only want to return the public part of the certificate, which is why `az keyvault certificate download` doesn't offer PFX as an option. If you download the certificate as a secret (even though it's not a secret), it downloads the raw PFX (with no password).
> 
> Go figure. 🤷‍♂️
> 
> **Edit:** You can specify `--encoding base64` and it will un-encode it for you automatically.

its almost 3 years later and this saved me.  Powershell az.keyvault does not grab the chain when you get the secret and turn it into a pfx.  `az keyvault secret download` does.  Its a work around and not ideal, but it unblocks me.  Thanks.

**Comment by jimbo8098** [comment]
Thank you @bradwilson, saved me too!

While the documentation at https://docs.microsoft.com/en-us/azure/key-vault/certificates/how-to-export-certificate?tabs=azure-cli goes over this, what it doesn't mention is that you need to use the same ID for the certificate but amend it such that it is in the format http://${VAULTNAME}.vault.azure.net/**secrets**/${CERTNAME}. If you use the ID provided by Azure directly, i.e. replacing secrets with certificates, you receive an error:
```
ValidationError: invalid id: The collection "certificates" does not match the expected "secrets"
```
It seems to me that Azure should either allow those to redirect in some way if they are certificates or add something into the az cli to allow the PFX to be downloaded. I suspect adding a cli command for it might also open up opportunities to create a password on the PFX too.

**Comment by jayaneti1** [comment]
I created new version of the certificate through az keyvault certificate create 
Then I downloaded the cert using az keyvault secret download  with --encoding base64
Thentried to apply openssl pkcs12 -in to get .pem file but I got the following error
140633834518336:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto/asn1/tasn_dec.c:1149:
140633834518336:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:309:Type=PKCS12

What am I doing wrong?

**Comment by LaurentLesle** [comment]
The problem seams to be related to the command "az keyvault secret download with --encoding base64" which get the private key unprotected with no password >"-----BEGIN PRIVATE KEY-----". 

Azure cli library expects the PEM file to have an encrypted key > "-----BEGIN ENCRYPTED PRIVATE KEY-----"

As mentioned by @akshita31 you need to download and export the PEM with a password

```bash
# Login with credentials having access to the Key Vault certificate. Role > "Key Vault Certificate User"
# az login -t $tenantId

# Private key pfk is exported from KeyVault with an empty password.
passphrase=""

# Store the certificate into variable
certificate_pfx_private=$(az keyvault secret show --name ${certificate_name} --vault-name ${KeyVaultName} --query value --output tsv)

# Close the current Azure session to clean the local cli cache
az account clear

# Create temp file
temp_file="$(mktemp)"

# Set the output PEM to empty password is working but not recommended
openssl pkcs12 -in <(echo -n "$certificate_pfx_private" | base64 --decode) -passin "pass:$passphrase"  -out $temp_file -passout pass:$passphrase

# check the PEM file is in the correct format
check_private_key=$(cat $temp_file | grep -e "-----BEGIN ENCRYPTED PRIVATE KEY-----")
if [ $? -ne 0 ]; then
  echo "Error: Private key not in the correct format."
  #exit 1
fi

az login --service-principal -u "${clientId}" -p $temp_file --tenant "${tenantId}"

# Do you work on Azure. Note the file is required to allow the az cli to request new access token as needed.
# delete file to logout
# rm $temp_file
```

**Comment by tanvp112** [comment]
> You can do that today in two steps.
> 
> First, download the certificate with `az keyvault secret download`, which will download the raw PFX as Base64-encoded text. Then undo the Base64 encoding, and you have the binary PFX file.
> 
> I don't know why, but the certificate APIs only want to return the public part of the certificate, which is why `az keyvault certificate download` doesn't offer PFX as an option. If you download the certificate as a secret (even though it's not a secret), it downloads the raw PFX (with no password).
> 
> Go figure. 🤷‍♂️
> 
> **Edit:** You can specify `--encoding base64` and it will un-encode it for you automatically.

`az keyvault secret download --encoding base42 ...` doesn't work, the downloaded PFX seems corrupted. It has 1 extra byte.

> You can do that today in two steps.
> 
> First, download the certificate with `az keyvault secret download`, which will download the raw PFX as Base64-encoded text. Then undo the Base64 encoding, and you have the binary PFX file.
> 
> I don't know why, but the certificate APIs only want to return the public part of the certificate, which is why `az keyvault certificate download` doesn't offer PFX as an option. If you download the certificate as a secret (even though it's not a secret), it downloads the raw PFX (with no password).
> 
> Go figure. 🤷‍♂️
> 
> **Edit:** You can specify `--encoding base64` and it will un-encode it for you automatically.

There's no need to decode the downloaded file. But the downloaded PFX is not valid.

> openssl pkcs12 -info -noout -in downloaded.pfx
> F8420000:error:068000A8:asn1 encoding routines:asn1_check_tlen:wrong tag:../openssl-3.2.1/crypto/asn1/tasn_dec.c:1186:
> F8420000:error:0688010A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:../openssl-3.2.1/crypto/asn1/tasn_dec.c:349:Type=PKCS12
