### ISSUE TITLE
Recovery Vault: az backup protection does not provide idempotent disable/enable of protection

### ISSUE THREAD

**Issue by archmangler** [Azure/azure-cli#7493]
**Describe the bug**
- The "az backup protection" command does not provide a way to disable backup protection and then re-enable it, without first needing to delete the backups in a recovery services vault:
- When RSV protection is disabled with "az backup protection disable" one must specify delete-backups "yes" or the enable command will fail if we want to re-enable backups again. 
- This means that we cannot automate via a script and expect idempotent behaviour  , without deleting backups in the rsv first. Ideally we want to disable protection, keep backups in rsv, and re-enable at any time with azure cli understanding that there are previous backups in the Recovery Services Vault, but protection is disabled.
- Without this behaviour RSV management cannot be smoothly automated via script or infrastructure as code (e.g terraform).

**To Reproduce**

- Disable backup protection (retaining backups)

```
(.env) [moi@host terraform]$ az backup protection disable --subscription yyyyyyy --resource-group myrsg --vau
lt-name myrsv --container-name xxxxxxxxx --item-name xxxxxxxxx --delete-backup-data false --yes
{
  "eTag": null,
  "id": "/Subscriptions/yyyyyyy/resourceGroups/myrsg/providers/Microsoft.RecoveryServices/vaults/myrsv/backupJobs/zzzzzzzzzzz",
  "location": null,
  "name": "zzzzzzzzzzz",
  "properties": {
    "actionsInfo": null,
    "activityId": "317f3fb2-c855-11e8-b063-000d3aa1fbfb",
    "backupManagementType": "AzureIaasVM",
    "duration": "0:00:11.918393",
    "endTime": "2018-10-05T04:15:02.618552+00:00",
    "entityFriendlyName": "xxxxxxxxx",
    "errorDetails": null,
    "extendedInfo": {
      "dynamicErrorMessage": null,
      "progressPercentage": null,
      "propertyBag": {
        "Policy Name": "",
        "VM Name": "xxxxxxxxx"
      },
      "tasksList": []
    },
    "jobType": "AzureIaaSVMJob",
    "operation": "DisableBackup",
    "startTime": "2018-10-05T04:14:50.700159+00:00",
    "status": "Completed",
    "virtualMachineVersion": "Compute"
  },
  "resourceGroup": "myrsg",
  "tags": null,
  "type": "Microsoft.RecoveryServices/vaults/backupJobs"
}


```

- Try to Re-enable backup protection following that:

```
(.env) [moi@host terraform]$ az backup protection enable-for-vm  --subscription yyyyyyy  --resource-group myrsg  --vault-name myrsv  --vm /subscriptions/yyyyyyy/resourceGroups/vmRSG/providers/Microsoft.Compute/virtualMachines/xxxxxxxxx  --policy-name DefaultPolicy

            The specified Azure Virtual Machine Not Found. Possible causes are
               1. VM does not exist
               2. The VM name or the Service name needs to be case sensitive
               3. VM is already Protected with same or other Vault.
                  Please Unprotect VM first and then try to protect it again.

            Please contact Microsoft for further assistance.

(.env) [moi@host terraform]$

```

- This is because the item still shows up using vm check:

```
(.env) [moi@host terraform]$ az backup protection check-vm --subscription yyyyyyy --vm /subscriptions/yyyyyyy/resourceGroups/vmRSG/providers/Microsoft.Compute/virtualMachines/xxxxxxxxx                                                                   "/subscriptions/yyyyyyy/resourceGroups/myrsg/providers/Microsoft.RecoveryServices/vaults/myrsv"
```

- There is no other way to enable protection again once disabled via the CLI (unless the backups had been deleted along with protection disablement!):

```
(.env) [moi@host terraform]$ az backup protection disable \
 --subscription yyyyyyy \
 --resource-group myrsg \
 --vault-name myrsv \
 --container-name xxxxxxxxx \
  --item-name xxxxxxxxx \
  --delete-backup-data true --yes
```

Only if protection is disabled with the "--delete-backups yes" option is the configuration removed "cleanly", and a re-apply of enable-for-vm works.

```
 {
   "eTag": null,
   "id": "/Subscriptions/yyyyyyy/resourceGroups/rsg-sgprho-ns1-a
ackupJobs/4556634675564",
   "location": null,
   "name": "4556634675564",
   "properties": {
     "actionsInfo": null,
     "activityId": "535256575tg345rfcf45d2tr5",
     "backupManagementType": "AzureIaasVM",
     "duration": "0:00:32.369000",
     "endTime": "2018-10-05T04:24:24.469550+00:00",
     "entityFriendlyName": "xxxxxxxxx",
     "errorDetails": null,
     "extendedInfo": {
       "dynamicErrorMessage": null,
       "progressPercentage": null,
       "propertyBag": {
         "Policy Name": "DefaultPolicy",
         "VM Name": "xxxxxxxxx"
       },
       "tasksList": []
     },
     "jobType": "AzureIaaSVMJob",
     "operation": "ConfigureBackup",
     "startTime": "2018-10-05T04:23:52.100550+00:00",
     "status": "Completed",
     "virtualMachineVersion": "Compute"
   },
   "resourceGroup": "myrsg",
   "tags": null,
   "type": "Microsoft.RecoveryServices/vaults/backupJobs"
 }
plete after 49s (ID: 6898262476066139042)
```

**Expected behavior**

- Disable of protection using the "az backup protection enable-for-vm" command keeps backups in vault if they're there already from a previous run, but the protection status is correctly identified as "unprotected" and it enables the protection again.

**Environment summary**

azure-cli (2.0.44)
Python (Linux) 2.7.5 (default, May 31 2018, 09:41:32)
GCC 4.8.5 20150623 (Red Hat 4.8.5-28)

**Additional context**

- the az cli is to be used in a shell script wrapper embedded in terraform in order to provision rsv backups to azure virtual machines.
- this mechanism was chosen because terraform does not yet support provisioning rsv to vms natively, nor is ARM templating a feasible option.

**Comment by archmangler** [comment]
Hi, any update on this? Let me know if I can pass through any further debugging information.

**Comment by pvrk** [comment]
@archmangler: Thanks for the feedback. We can change this behavior by having a "item-name" parameter when you want to resume backup. The VM name only refers to "unprotected VMs". Once a VM is backed up, it is referred to as backup-item. So, you would enable-protection-for VM with <VM name> for the first time, then delete protection for a backup item with "disable-protection" with <item-name> and then enable-protection with <item-name>to resume backup.

We will plan and implement this behavior. Will update this thread after planning timelines are fixed.

**Comment by ranokarno** [comment]
hi @siddharth7 ,
any update on idempotent script for enable/disable backup ? the az cli code return error

>[ranokarno@svr001 ~]$ az backup protection enable-for-vm \\
>     --resource-group recovery_resourcegroup \\
>     --vault-name recovery_vaultname \\
>     --vm vm_resource_id  \\
>     --policy-name policy_name
Command group 'backup' is in preview. It may be changed/removed in a future release.

            The specified Azure Virtual Machine Not Found. Possible causes are
               1. VM does not exist
               2. The VM name or the Service name needs to be case sensitive
               3. VM is already Protected with same or other Vault.
                  Please Unprotect VM first and then try to protect it again.

            Please contact Microsoft for further assistance.
`

**Comment by ggg333** [comment]
> hi @siddharth7 ,
> any update on idempotent script for enable/disable backup ? the az cli code return error
> 
> > [ranokarno@svr001 ~]$ az backup protection enable-for-vm \
> > --resource-group recovery_resourcegroup \
> > --vault-name recovery_vaultname \
> > --vm vm_resource_id  \
> > --policy-name policy_name
> > Command group 'backup' is in preview. It may be changed/removed in a future release.
> 
> ```
>         The specified Azure Virtual Machine Not Found. Possible causes are
>            1. VM does not exist
>            2. The VM name or the Service name needs to be case sensitive
>            3. VM is already Protected with same or other Vault.
>               Please Unprotect VM first and then try to protect it again.
> 
>         Please contact Microsoft for further assistance.
> ```
> 
> `

any fix for this? have the same exact problem even today

**Comment by siddharth7** [comment]
@sambitratha  can you look at this?

**Comment by pvrk** [comment]
@ggg333 : Can you please elaborate on idempotency? The "enable-protection" command is for enabling backup for "yet-unprotected-items" and there is a "resume" command for "protection-stopped-items". Can you help me understand what is the expectation here?

**Comment by zubairabid** [comment]
@yonzhan as the Cx hasn't responded in a while can we close this issue.
