### ISSUE TITLE
Documentation typo "Resorce" [website]

### ISSUE THREAD

**Issue by earthquakesan** [Azure/azure-cli#7494]
**Describe the bug**
Typo in the docs: https://docs.microsoft.com/en-us/cli/azure/storage/cors?view=azure-cli-latest

**To Reproduce**
Go to the URI and check the left sidebar menu

**Expected behavior**
"Cross-Origin Resorce Sharing" should be changed to "Cross-Origin Resource Sharing"

**Environment summary**
N/A

**Comment by williexu** [comment]
Fixed with https://github.com/Azure/azure-docs-cli-python/pull/1071
