### ISSUE TITLE
How to enable access from Azure Portal with firewall settings

### ISSUE THREAD

**Issue by chetanmeh** [Azure/azure-cli#7495]
Is there any option to configure the "Allow access from Azure Portal" while using the `--ip-range-filter` options. Currently when we use this option it resets the portal access settings and that needs to be enabled again.

This cause issue for us where we configure the firewall as part of scripts for every deployment

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc8d652-2eda-296f-28ea-8d5f1ea855b3
* Version Independent ID: 80b87995-d339-61e9-1cac-b5c9ad6efe5e
* Content: [az cosmosdb](https://docs.microsoft.com/en-gb/cli/azure/cosmosdb?view=azure-cli-latest#az-cosmosdb-update)
* Content Source: [src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_help.py)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by chetanmeh** [comment]
From terraform-providers/terraform-provider-azurerm#1192 and discussion thread [here][1] it appears that one needs to add following ip

```
0.0.0.0,104.42.195.92,40.76.54.131,52.176.6.30,52.169.50.45,52.187.184.26
```

To enable portal access

[1]: https://social.msdn.microsoft.com/Forums/ie/en-US/b2554b0b-1097-48f7-9b56-cdd6d43734e2/get-ip-address-for-portal-access?forum=azurecosmosdb

**Comment by chetanmeh** [comment]
Seems like just adding `0.0.0.0` should enable portal access

**Comment by shurd** [comment]
Hi @chetanmeh it looks like you found the right IP addresses. For future reference, the IP addresses to allow requests from the Azure portal are documented here: https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-configure-firewall#allow-requests-from-the-azure-portal

**Comment by chetanmeh** [comment]
Thanks @shurd for the details We can close this issue then

**Comment by mikemowgli** [comment]
C'mon guys, Of course adding '0.0.0.0' works! since it allows connectivity from _any_ IP. But then there's no reason to enable the firewall anymore. Just remove '0.0.0.0' and define the proper IPs (https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-configure-firewall#allow-requests-from-the-azure-portal)

**Comment by mcalnd70** [comment]
@mikemowgli I think that 0.0.0.0 reference in this situation doesn't actually allow ALL. It merely "ticks" the box that states "Accept connections from within public Azure datacenters". Certainly that is what I found in my testing. Added 0.0.0.0 on the end of my long firewall string just ticked that box

https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-configure-firewall#allow-requests-from-global-azure-datacenters-or-other-sources-within-azure

**Comment by mikemowgli** [comment]
@mcalnd70, I only whitelisted the IPs mentioned [here](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-configure-firewall#allow-requests-from-the-azure-portal) and it also ticket that box for me. So my understanding is that the portal performs a check whether the necessary Azure IPs are whitelisted in the firewall definition, and ticks the box if true. But it does not mean it'll tick the box if the Azure public IPs are the only ones whitelisted...
