### ISSUE TITLE
Major Regression: Many Commands Now Missing

### ISSUE THREAD

**Issue by apeschel** [Azure/azure-cli#7499]
**Describe the bug**
At least 2.0.46 and 2.0.45 are missing many sub-commands that existed in 2.0.42. It's not clear which version this regression occured in. This was noticed with the `az aks` commands specifically.

**To Reproduce**
Run `az aks` on either v2.0.45 or 2.0.46, an error will return.

Run `az help` on v2.0.45 or 2.0.46 vs v2.0.42 to see a much shorter list of available sub-commands.

v2.0.46

```
az help | wc -l
      31
```

v2.0.42

```
az help | wc -l
      69
```

**Expected behavior**
`az aks` sub-system responds.

Full list of sub-commands remains available.

**Environment summary**
Install Method: Homebrew

**Additional context**
I'm assuming this change was not intentional, since it is a major breaking change with only a bug-fix version bump, and no documentation to support it.

**Comment by tjprescott** [comment]
Please try running:
`brew uninstall azure-cli && brew install azure-cli`

If it still fails, please provide the output of `az --version`

**Comment by apeschel** [comment]
```
ERROR: az: 'aks' is not in the 'az' command group. See 'az --help'.
```

**Comment by apeschel** [comment]
@tjprescott I am on MacOS X High Sierra 10.13.6. I was able to confirm a coworker on High Sierra also has the same problem. However, a coworker on Mojave does not have this problem, so this may be specific to the High Sierra release.

**Comment by tjprescott** [comment]
My dev machine is also High Sierra 10.13.6 and I don't experience this, so there must be something else going on. While I can't repro your specific issue yet, I'm actively investigating #7559 so that might address some of the problem.

**Comment by apeschel** [comment]
Upgraded to Mojave and upgrades to the latest homebrew release and this continues to be a problem.

**Comment by tjprescott** [comment]
Please contact me at trpresco at microsoft.com and include the results of running `az -h --debug`

**Comment by apeschel** [comment]
@tjprescott email sent

**Comment by apeschel** [comment]
@tjprescott Hello, still haven't heard back on the email. This still continues to be a problem for the CLI toolset, unfortunately.

**Comment by tjprescott** [comment]
After more investigation, the issue was that, in version 2.0.43, many command modules that aren't supported on older profiles were updated so that they would not appear unless on profile 'latest'. After switching back to 'latest' the commands were present.
