### ISSUE TITLE
Bad error message when SB namespace over qouta. 

### ISSUE THREAD

**Issue by paulgmiller** [Azure/azure-cli#7502]
**Describe the bug**
Creating a service bus namespace when you are over the quota give bad error message. Just bad request with no other details. 

**To Reproduce**
Create 10 premium namespaces in  a sub then do 
az servicebus namespace create --name fsdfgddssdfds  --resource-group gdffgdfgdf --location westus2 --sku Premium

**Expected behavior**
Error message should mention quota. 

**Environment summary**
Windows 
 azure-cli (2.0.45)
servicebus (0.2.2)

**Additional context**

**Comment by tjprescott** [comment]
If you run with `--debug` you should see additional information. If running on the latest version of the CLI, the "BadRequest" should now display with more info without needed to use `--debug`

**Comment by jfggdl** [comment]
@paulgmiller, would you please confirm if you try what @tjprescott suggested?

**Comment by paulgmiller** [comment]
We haven't hit this in some time so I assume this is fixed
