### ISSUE TITLE
How to reference key=value parameters in az vm  run-command invoke ?

### ISSUE THREAD

**Issue by lukasmrtvy** [Azure/azure-cli#7505]
I am running this command: 
```
az vm  run-command invoke -g my-group --name my-vm  --command-id RunShellScript  --scripts 'echo "$@"' --parameters 'foo=bar' 'color=red' 'thing=car'
```

Seems that parameters are parsed as keys and values.

Output:
```
{
  "value": [
    {
      "code": "ProvisioningState/succeeded",
      "displayStatus": "Provisioning succeeded",
      "level": "Info",
      "message": "Enable succeeded: \n[stdout]\nbar red car\n\n[stderr]\n",
      "time": null
    }
  ]
}
```

Of course that I can do: 
```
az vm  run-command invoke -g my-group --name my-vm  --command-id RunShellScript  --scripts 'env | grep -E "foo|color|thing"' --parameters 'foo=bar' 'color=red' 'thing=car'
```
, but if You want to dynamically reference these parameters like this: (vars are set in execution time)

`for i in "$@"; do echo $i >> variables.file; done ` it will not work for sourcing purposes, because it will put only keys to variables.file.

Format should be key=value

Thanks

---

### Environment summary

apt-get az-cli version, Ubuntu 18.04 LTS

**Comment by andrejzelnik** [comment]
We have come across the same issue... any resolution?

**Comment by adewaleo** [comment]
@lukasmrtvy @andrejzelnik, unless I am mistaken, you want to pass parameters that contain the '=' sign to the executed shell script? If this is the case, you can pass the parameters like so:

```
az vm run-command invoke -g $RG --name $TEST_VM  --command-id RunShellScript  --scripts 'for i in "$@"; do echo $i >> variables.file; done; cat variables.file;'  \
--parameters "arg=foo=bar" "arg=color=red" "arg=thing=car"
```
The reason for this syntax is that the run-command api requires parameters to be named, even though a shell script ultimately receives positional args. If you pass un-named parameters, the CLI auto-generates parameter names for your arguments i.e. arg1, arg2, arg3 etc. 

After some experimentation, it appears that the RunshellScript run command:
- exports the parameters as environment variables
- runs the shell script with the value of the parameters as positional arguments. 

Hence, running the following:
 ```
az vm run-command invoke -g $RG --name $TEST_VM  --command-id RunShellScript \
--scripts 'printenv; echo "---"; for i in "$@"; do echo $i >> variables.file; done; cat variables.file'  \
--parameters "arg=foo=bar" "arg=color=red" "arg=thing=car"
```
Yields:

{
  "value": [
    {
      "code": "ProvisioningState/succeeded",
      "displayStatus": "Provisioning succeeded",
      "level": "Info",
      "message": "Enable succeeded: \n[stdout]\n**SHLVL=1**\n_=/usr/bin/nohup\nPATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\nLANG=en_US.UTF-8\nPWD=/var/lib/waagent/run-command/download/20\n**arg=thing=ca**r\n---\n**foo=bar**\n**color=red**\n**thing=car**\n\n[stderr]\n",
      "time": null
    }
  ]
}

Even though the same name is used for all the parameters (which means each parameter's export overrides the previous value), the different parameter values are passed to the executed shell script.

I believe this should answer your question. Please let me know if this does.

I will be closing this issue.

**Comment by adewaleo** [comment]
I hope the explanation helps.
