### ISSUE TITLE
Add throughput by database support

### ISSUE THREAD

**Issue by diirib** [Azure/azure-cli#7506]
**Is your feature request related to a problem? Please describe.**
Cosmos Databases can now have their Throughput (RUs) set at database level instead of collection, and this should be supported in az cosmosdb as well.

**Describe the solution you'd like**
Add a parameter in az cosmosdb database create to set it.

**Describe alternatives you've considered**
It can be done through the Azure portal, but it cannot be automated and scaled that way.

**Additional context**
I checked the latest version of azure-cli-cosmosdb (0.2.1) and it is not included.

**Comment by JohnGalt1717** [comment]
It should also allow update of existing values.

And it should allow setting it on an existing database that doesn't have database throughput configured yet.

**Comment by shurd** [comment]
Hi @diirib thank you for this feature request. We are in the process of changing how the CLI creates/updates databases and collections. As a part of this change, we will be allowing users to set database level throughput. We are tracking this internally as work item 416566. The ETA for the change is September 2019.

**Comment by shurd** [comment]
Hi, in version 2.0.71 of the CLI, we released a preview version of the new database and collection management. As a part of this change, you can management database level throughput.

For example, you can create a MongoDB database with:
```
az cosmosdb mongodb database create --account-name {account_name} -n {database_name} --throughput 500 -g {resource_group}
``
And then update the throughput with:
```
az cosmosdb mongodb database throughput update -a {account_name} -n {database_name} -g {resource_group} --throughput 600
```

You must determine at create time if throughput will be configured at the database level.
