### ISSUE TITLE
CosmosDB Collection TTL parameter options changed and now can't be set to 'Off' through powershell.

### ISSUE THREAD

**Issue by diirib** [Azure/azure-cli#7508]
**Describe the bug**
There's a new option for TTL in a CosmosDB Collection but there's no way to set it to 'off' now. The documentation says it has to be set to "null", and that way it will be 'off', but I get an error when doing it that way. 0 doesn't work either, since it says it should be a non-zero positive number, or -1 to set it to Off (which is no longer valid).

**To Reproduce**
az cosmosdb collection create -c mycollection -d mydatabase -n myaccount -g myresourcegroup --default-ttl 'null'  --partition-key-path "/key"
Returns:
az cosmosdb collection create: error: argument --default-ttl: invalid int value: 'null'

az cosmosdb collection create -c mycollection -d mydatabase -n myaccount -g myresourcegroup --default-ttl 0  --partition-key-path "/key"
Returns:
Operation Failed: Invalid Arg {"Errors":["The input defaultTtl '0' is invalid. Ensure to provide a nonzero positive integer less than or equal to '2147483647', or '-1' which means never expire."]}

az cosmosdb collection create -c mycollection -d mydatabase -n myaccount -g myresourcegroup --default-ttl 0  --partition-key-path "/key"
Returns:
Creates a collection with TTL: On (No default)

**Expected behavior**
According to the documentation, TTL of the collection should be set to 'Off'.

**Environment summary**
az cli 2.0.46
az cosmosdb 0.2.1  

**Additional context**

**Comment by diirib** [comment]
Any updates on this @tjprescott ?

**Comment by tjprescott** [comment]
@moderakh @dmakwana

**Comment by deepikaak** [comment]
Hi,
Even I am facing this issue. We have multiple collections and one command to create them. so for some it is set to some value and for some it is On(default) but for the collections which needs to be set to off what value we need to pass? Do we have any update on this or is there any other way we can set it to off?

**Comment by shurd** [comment]
Hi @diirib thank you for raising this issue. Based on [documentation](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-time-to-live#disable-time-to-live), to disable TTL you need to get the collection resource, remove the TTL field and then replace the collection resource. Right now, this is not possible with the CLI. I am tracking a change that will allow you to pass 0 to turn off TTL (work item 457760). The ETA for this update is July 2019. I will post any updates here.

**Comment by shurd** [comment]
The fix has been merged and will appear in the next CLI released on 7/2.
