### ISSUE TITLE
Add parameter Protocol to CLI operation network watcher test-connectivity

### ISSUE THREAD

**Issue by junyezhu** [Azure/azure-cli#7512]
**Is your feature request related to a problem? Please describe.**
Network Watcher operation connectivity troubleshoot added a new input parameter Protocol, which can value Tcp and Icmp. Also if Protocol value is Icmp, user doesn't need to input both source and destination port.

**Describe the solution you'd like**
Add parameter Protocol into operation network watcher test-connectivity

Currently:
az network watcher test-connectivity --resource-group juz-er-networkwatcher-team-rg --source-resource juzVm0 --dest-address 13.107.21.200 --dest-port 80 

Expected something like 
az network watcher test-connectivity --resource-group juz-er-networkwatcher-team-rg --source-resource juzVm0 --dest-address 13.107.21.200 --dest-port 80 
az network watcher test-connectivity --resource-group juz-er-networkwatcher-team-rg --source-resource juzVm0 --dest-address 13.107.21.200 --dest-port 80 -–protocol Tcp
az network watcher test-connectivity --resource-group juz-er-networkwatcher-team-rg --source-resource juzVm0 --dest-address 13.107.21.200 -–protocol Icmp

**Describe alternatives you've considered**
None

**Additional context**
Portal change shall be released soon, which can be a reference.

**Comment by tjprescott** [comment]
The `test-connectivity` command already has a protocol parameter. Are you talking about `network watcher troubleshooting start`?

**Comment by junyezhu** [comment]
@tjprescott My fault, I failed on finding the correct website. Closed now. Sorry for the trouble, Travis.
