### ISSUE TITLE
azure-cli package for openSUSE should depend on python2 and python-xml

### ISSUE THREAD

**Issue by Arnavion** [Azure/azure-cli#7523]
**Describe the bug**

1. The RPM package requires `python`, which on a minimal empty openSUSE install (like a Docker container image) will install the `python3` package since it provides `python = 3.6`. Instead the package should require `python = 2` specifically, or `python2`, both of which are provided by the `python` package.

1. The RPM package does *not* depend on `python-xml`, which means many commands fail because they can't import `xml.etree`

**To Reproduce**
Steps to reproduce the behavior.

(Run inside `docker run -it --rm -v ~/.azure:/root/.azure opensuse:leap bash` for easy reproducability.)

1. Problem 1: Depends on `python` which causes zypper to install `python3-base` instead of `python-base`

    ```sh
    $ zypper in -y curl
    $ rpm --import https://packages.microsoft.com/keys/microsoft.asc
    $ zypper addrepo --name 'Azure CLI' --check https://packages.microsoft.com/yumrepos/azure-cli azure-cli
    $ zypper install --from azure-cli -y azure-cli

    ...

    The following 6 NEW packages are going to be installed:
      azure-cli libpython2_7-1_0 libpython3_4m1_0 libsqlite3-0 python3 python3-base

    ...

    $ az account list

    Could not find platform dependent libraries <exec_prefix>
    Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
    Could not import runpy module
    ```

    Workaround is to install `python-base` manually.

    ```sh
    $ zypper in python-base
    ```

1. Problem 2: Does not depend on `python-xml`

    ```sh
    $ az account list

    usage: az account list [-h] [--verbose] [--debug]
                           [--output {tsv,table,json,jsonc,yaml}]
                           [--query JMESPATH] [--subscription _SUBSCRIPTION]
                           [--all] [--refresh]
    az account list: error: No module named xml.etree.ElementTree
    ```

    Workaround is to install `python-xml` manually.

    ```sh
    $ zypper in python-xml
    $ az account list 

    {
        ...
    }
    ```

**Expected behavior**

**Environment summary**

**Additional context**

**Comment by marstr** [comment]
Thank you for the tremendous write-up on this @Arnavion. Right now, there seems to be a discrepancy between the RPM platforms that we say we support on our [install instructions page](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest) and the RPMs that are actually available in [our repository](https://packages.microsoft.com/yumrepos/azure-cli/). To spare people the click, the only packages in our repo right now are all "el7" packages (e.g Centos7, Red Hat 7, and CloudLinux 7.) Not too surprisingly, I can empirically also tell you these packages just work for Fedora 29.

I'll have to poke around internally to see what levers we have to pull around distributing packages for different distros.

**Comment by Arnavion** [comment]
Yeah, I know :) Making openSUSE users use the RHEL packages has had problems with .Net Core and PowerShell Core as well.

**Comment by marstr** [comment]
I'm rolling up this and a few other issues into the broader #8780.

**Comment by marstr** [comment]
Now that the RPM spec has been updated to be more accommodating of different distros, this issue should be reassessed.

**Comment by yugangw-msft** [comment]
Per discussion, we will live with this limitation, as there is workaround available

**Comment by Arnavion** [comment]
Then please document it on https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-zypper?view=azure-cli-latest Something like

>4. Update the zypper package index and install:
>
>    ```bash
>    sudo zypper install python-base python-xml
>    sudo zypper install --from azure-cli -y azure-cli
>    ```

Incidentally, the "Important" note at the top of the page also implies that `azure-cli` works with `python3` if that is available:

>Be aware that Python 2 is being end-of-lifed on January 1, 2020, and will no longer receive updates. For this reason, upgrade to Python 3 when possible. The Azure CLI is compatible with Python 3.6 and higher.

But this is clearly not the case, as not supporting Python 3 is why this issue exists in the first place. So it would be good to fix that note too.

**Comment by Arnavion** [comment]
Actually, with `azure-cli-2.0.66-3.el7.x86_64` that is the latest as of just now:

```sh
$ zypper install --from azure-cli -y azure-cli

...

The following 13 NEW packages are going to be installed:
  azure-cli libdb-4_8 libpython2_7-1_0 python python-base python-rpm-macros python-xml python2-appdirs python2-packaging python2-pyparsing python2-setuptools python2-six python2-virtualenv
```

The `python2-virtualenv` dep added in https://github.com/Azure/azure-cli/commit/45579caa99b7f1d81bfc1f05adacab8f5ae59f69#diff-28fbe56abba57837471970f7a05e3edf is pulling `python-base` and `python-xml` in transitively. So this works but it is brittle. It would still be good to add the `python-base` and `python-xml` deps explicitly.

And fix that "compatible with Python 3.6" note in the docs, of course.

**Comment by yonzhan** [comment]
add to S164.

**Comment by fengzhou-msft** [comment]
The RPM package uses python3 starting from 2.0.77. Can we close this issue now?

**Comment by Arnavion** [comment]
Yes, confirmed the OP repro with `2.0.78-1.el7`:

```sh
$ zypper install --from azure-cli -y azure-cli

...

The following 5 NEW packages are going to be installed:
  azure-cli libpython3_6m1_0 python-rpm-macros python3 python3-base
```

... and `az account list` also works.
