### ISSUE TITLE
Contract change:  new property "Format" in contract FlowLogProperties 

### ISSUE THREAD

**Issue by zwswim** [Azure/azure-cli#7524]
**Is your feature request related to a problem? Please describe.**
A new property “Format” has been added to NRP contract FlowLogProperties
public class FlowLogProperties {
    ………
        
        /// <summary>
        /// Gets or sets the flow log format
        /// </summary>
        public FlowLogFormat Format { get; set; }
       }

public class FlowLogFormat
    {
        public FlowLogFormat()
        {
            // Defaults
            this.Type = FlowLogFormatType.JSON;
            this.Version = 0;
        }

        /// <summary>
        /// Gets or sets the type of flow log format
        /// </summary>
        public FlowLogFormatType Type { get; set; }

        /// <summary>
        /// Gets or sets the version (revision) of the flow log format
        /// </summary>
        public int Version { get; set; }
}

**Describe the solution you'd like**
Please update flow-log configure/show to handle the new property “Format”.

For “az network watcher flow-log configure”, user could set the optional property "Format". If "Format" is not set, NRP will use the default FlowLog format.

For “az network watcher flow-log show”, NRP/ARM will return the Format if flowlog is enabled.

**Describe alternatives you've considered**

**Additional context**

**Comment by tjprescott** [comment]
There is no reference to this property in the current rest API specs:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2018-08-01/networkWatcher.json

Thus there is no SDK and can be no CLI work.
