### ISSUE TITLE
[docs] az vm extension set --auto-upgrade-minor-version: Misdocumented

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-cli#753]
If somebody ever asks how you spent your career at Microsoft, I will reply:

> I kept explaining people what the `--auto-upgrade-minor-version` flag means.

Here we go again:

```
~ az vm extension set -h
^C
Command
    az vm extension set

Arguments
    --name -n         [Required]: The name of the extension.
    --publisher       [Required]: The name of extension publisher.
    --auto-upgrade-minor-version: Auto upgrade to the newer version if available.
```

This is not true. Period.

It just means 

> Pick the highest minor version for the specified version number at the provisioning time.

Once extensions are added to the VM, they are NEVER upgraded to a new minor version unless user explicitly removes and re-adds the extension.

The extension hotfixes (`C` and `D in `A.B.C.D`) are fetched for a minor version of an extension and users can't control this. It is forced upon users.

AutoUpgradeMinorVersion just means that pick the `max(B)` for specified `A.*` while adding it to this VM right now.

cc: @huangpf @yugangw-msft

**Comment by yugangw-msft** [comment]
@ahmetalpbalkan, i will loop you in a mail thread where I inquired about the appropriate descriptions and  the answer i got was a little different. With this issue opened, it is now a good time to finalize it.

**Comment by yugangw-msft** [comment]
Fixed, though in my next PR, i will rename it to "--no-auto-upgrade"
