### ISSUE TITLE
After upgrade problem getting az vm list to work

### ISSUE THREAD

**Issue by Josuruma** [Azure/azure-cli#7533]
**Describe the bug**
az vm list produces the following error in version 2.0.47
The resource type 'virtualMachines' could not be found in the namespace 'Microsoft.Compute' for api version '2018-10-01'. The supported api-versions are '2015-05-01-preview,2015-06-15,2016-03-30,2016-04-30-preview,2016-08-30,2017-03-30,2017-12-01,2018-04-01,2018-06-01'.

**To Reproduce**
Upgrade to version 2.0.47 on Debian 9.5 and using the command az vm list

**Expected behavior**
Normally it shows a list of virtual machines and it did before with version 2.0.46

**Environment summary**
Installed on Debian 9.5

**Additional context**
Installed version 2.0.46 again and the command is working...

**Comment by kb321** [comment]
+1 Josuruma

**Comment by yugangw-msft** [comment]
can you please share me the trace using "--debug". This is a compute service issue.

**Comment by Josuruma** [comment]
Sure following the output.
> Command arguments: ['vm', 'list', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fe613dc1d08>, <function OutputProducer.on_global_arguments at 0x7fe613b5e378>, <function CLIQuery.on_global_arguments at 0x7fe613906e18>]
Event: CommandInvoker.OnPreCommandTableCreate [<function CLILogging.remove_logger_flags at 0x7fe613dc1d90>]
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'lab', 'maps', 'monitor', 'network', 'policyinsights', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'servicebus', 'servicefabric', 'signalr', 'sql', 'storage', 'vm']
Loaded module 'acr' in 0.010 seconds.
Loaded module 'acs' in 0.006 seconds.
Loaded module 'advisor' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.009 seconds.
Loaded module 'appservice' in 0.014 seconds.
Loaded module 'backup' in 0.005 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.016 seconds.
Loaded module 'batchai' in 0.005 seconds.
Loaded module 'billing' in 0.002 seconds.
Loaded module 'botservice' in 0.006 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.004 seconds.
Loaded module 'cloud' in 0.002 seconds.
Loaded module 'cognitiveservices' in 0.002 seconds.
Loaded module 'configure' in 0.001 seconds.
Loaded module 'consumption' in 0.007 seconds.
Loaded module 'container' in 0.003 seconds.
Loaded module 'cosmosdb' in 0.005 seconds.
Loaded module 'dla' in 0.007 seconds.
Loaded module 'dls' in 0.005 seconds.
Loaded module 'dms' in 0.003 seconds.
Loaded module 'eventgrid' in 0.003 seconds.
Loaded module 'eventhubs' in 0.004 seconds.
Loaded module 'extension' in 0.002 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.001 seconds.
Loaded module 'hdinsight' in 0.002 seconds.
Loaded module 'interactive' in 0.000 seconds.
Loaded module 'iot' in 0.006 seconds.
Loaded module 'iotcentral' in 0.003 seconds.
Loaded module 'keyvault' in 0.017 seconds.
Loaded module 'lab' in 0.008 seconds.
Loaded module 'maps' in 0.003 seconds.
Loaded module 'monitor' in 0.012 seconds.
Loaded module 'network' in 0.054 seconds.
Loaded module 'policyinsights' in 0.002 seconds.
Loaded module 'profile' in 0.002 seconds.
Loaded module 'rdbms' in 0.009 seconds.
Loaded module 'redis' in 0.003 seconds.
Loaded module 'relay' in 0.005 seconds.
Loaded module 'reservations' in 0.003 seconds.
Loaded module 'resource' in 0.011 seconds.
Loaded module 'role' in 0.005 seconds.
Loaded module 'search' in 0.002 seconds.
Loaded module 'servicebus' in 0.006 seconds.
Loaded module 'servicefabric' in 0.003 seconds.
Loaded module 'signalr' in 0.002 seconds.
Loaded module 'sql' in 0.021 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.043 seconds.
Loaded module 'vm' in 0.016 seconds.
Loaded all modules in 0.362 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: '/root/.azure/cliextensions'
Event: CommandInvoker.OnPreCommandTableTruncate []
Event: CommandInvoker.OnPostCommandTableCreate [<function add_id_parameters at 0x7fe61382e8c8>, <function register_global_subscription_parameter.<locals>.add_subscription_parameter at 0x7fe61388f730>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7fe61335fb70>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fe613b5e400>, <function CLIQuery.handle_query_parameter at 0x7fe613906ea0>, <function register_global_subscription_parameter.<locals>.parse_subscription_parameter at 0x7fe61384f1e0>, <function handler at 0x7fe6132ba378>]
Getting management service client client_type=ComputeManagementClient
attempting to read file /root/.azure/accessTokens.json as utf-8-sig
adal-python : c8cb8765-6131-4d73-96a0-060b3b43febb - Authority:Performing instance discovery: ...
adal-python : c8cb8765-6131-4d73-96a0-060b3b43febb - Authority:Performing static instance discovery
adal-python : c8cb8765-6131-4d73-96a0-060b3b43febb - Authority:Authority validated via static instance discovery
adal-python : c8cb8765-6131-4d73-96a0-060b3b43febb - TokenRequest:Getting token from cache with refresh if necessary.
adal-python : c8cb8765-6131-4d73-96a0-060b3b43febb - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python : c8cb8765-6131-4d73-96a0-060b3b43febb - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python : c8cb8765-6131-4d73-96a0-060b3b43febb - CacheDriver:Found 2 potential entries.
adal-python : c8cb8765-6131-4d73-96a0-060b3b43febb - CacheDriver:Resource specific token found.
adal-python : c8cb8765-6131-4d73-96a0-060b3b43febb - CacheDriver:Returning token from cache lookup, AccessTokenId: b'REMOVED', RefreshTokenId: b'REMOVED'
adal-python : c8cb8765-6131-4d73-96a0-060b3b43febb - CacheDriver:Cached token is expired at 2018-10-10 21:45:01.743689.  Refreshing
adal-python : c8cb8765-6131-4d73-96a0-060b3b43febb - TokenRequest:called to refresh a token from the cache
adal-python : c8cb8765-6131-4d73-96a0-060b3b43febb - TokenRequest:Getting a new token from a refresh token
urllib3.connectionpool : Starting new HTTPS connection (1): login.microsoftonline.de:443
urllib3.connectionpool : https://login.microsoftonline.de:443 "POST /efb79223-92a2-4bd1-bdb7-324dd0b6dffc/oauth2/token HTTP/1.1" 200 2748
adal-python : c8cb8765-6131-4d73-96a0-060b3b43febb - OAuth2Client:Get Token Server returned this correlation_id: c8cb8765-6131-4d73-96a0-060b3b43febb
adal-python : c8cb8765-6131-4d73-96a0-060b3b43febb - CacheDriver:Created new cache entry from refresh response.
adal-python : c8cb8765-6131-4d73-96a0-060b3b43febb - CacheDriver:Removing entry.
adal-python : c8cb8765-6131-4d73-96a0-060b3b43febb - CacheDriver:Adding entry AccessTokenId: b'REMOVED', RefreshTokenId: b'REMOVED'
adal-python : c8cb8765-6131-4d73-96a0-060b3b43febb - CacheDriver:Updating 1 cached refresh tokens
adal-python : c8cb8765-6131-4d73-96a0-060b3b43febb - CacheDriver:Remove many: 1
adal-python : c8cb8765-6131-4d73-96a0-060b3b43febb - CacheDriver:Add many: 1
adal-python : c8cb8765-6131-4d73-96a0-060b3b43febb - CacheDriver:Returning token refreshed after expiry.
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
msrest.pipeline : Configuring proxies: ''
msrest.pipeline : Evaluate proxies against ENV settings: True
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
urllib3.connectionpool : Starting new HTTPS connection (1): management.microsoftazure.de:443
urllib3.connectionpool : https://management.microsoftazure.de:443 "GET /subscriptions/c62f6c6c-7028-4f57-bbf9-231b6e3cb660/providers/Microsoft.Compute/virtualMachines?api-version=2018-10-01 HTTP/1.1" 404 323
msrest.http_logger : Request URL: 'https://management.microsoftazure.de/subscriptions/c62f6c6c-7028-4f57-bbf9-231b6e3cb660/providers/Microsoft.Compute/virtualMachines?api-version=2018-10-01'
msrest.http_logger : Request method: 'GET'
msrest.http_logger : Request headers:
msrest.http_logger :     'User-Agent': 'python/3.6.5 (Linux-4.9.0-x86_64-with-debian-9.5) requests/2.19.1 msrest/0.5.5 msrest_azure/0.5.0 computemanagementclient/4.3.0 Azure-SDK-For-Python AZURECLI/2.0.47'
msrest.http_logger :     'Accept-Encoding': 'gzip, deflate'
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'Connection': 'keep-alive'
msrest.http_logger :     'Authorization': '*****'
msrest.http_logger :     'x-ms-client-request-id': '47e2e3b0-cce4-11e8-ab05-b1a899669a94'
msrest.http_logger :     'CommandName': 'vm list'
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger : Request body:
msrest.http_logger : None
msrest.http_logger : Response status: 404
msrest.http_logger : Response headers:
msrest.http_logger :     'Cache-Control': 'no-cache'
msrest.http_logger :     'Pragma': 'no-cache'
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger :     'Expires': '-1'
msrest.http_logger :     'x-ms-failure-cause': 'gateway'
msrest.http_logger :     'x-ms-request-id': 'cd666804-e009-4d95-a872-819b695c9ea7'
msrest.http_logger :     'x-ms-correlation-request-id': 'cd666804-e009-4d95-a872-819b695c9ea7'
msrest.http_logger :     'x-ms-routing-request-id': 'GERMANYCENTRAL:20181010T232908Z:cd666804-e009-4d95-a872-819b695c9ea7'
msrest.http_logger :     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'
msrest.http_logger :     'Date': 'Wed, 10 Oct 2018 23:29:07 GMT'
msrest.http_logger :     'Content-Length': '323'
msrest.http_logger : Response content:
msrest.http_logger : b'{"error":{"code":"InvalidResourceType","message":"The resource type \'virtualMachines\' could not be found in the namespace \'Microsoft.Compute\' for api version \'2018-10-01\'. The supported api-versions are \'2015-05-01-preview,2015-06-15,2016-03-30,2016-04-30-preview,2016-08-30,2017-03-30,2017-12-01,2018-04-01,2018-06-01\'."}}'
msrest.exceptions : The resource type 'virtualMachines' could not be found in the namespace 'Microsoft.Compute' for api version '2018-10-01'. The supported api-versions are '2015-05-01-preview,2015-06-15,2016-03-30,2016-04-30-preview,2016-08-30,2017-03-30,2017-12-01,2018-04-01,2018-06-01'.
The resource type 'virtualMachines' could not be found in the namespace 'Microsoft.Compute' for api version '2018-10-01'. The supported api-versions are '2015-05-01-preview,2015-06-15,2016-03-30,2016-04-30-preview,2016-08-30,2017-03-30,2017-12-01,2018-04-01,2018-06-01'.
telemetry.save : Save telemetry record of length 2444 in cache
telemetry.check : Returns Positive.
telemetry.main : Begin creating telemetry upload process.
telemetry.process : Creating upload process: "/opt/az/bin/python3 /opt/az/lib/python3.6/site-packages/azure/cli/telemetry/__init__.py /root/.azure"
telemetry.process : Return from creating porcess
telemetry.main : Finish creating telemetry upload process.

**Comment by yugangw-msft** [comment]
This issue should be fixed now. We made sure the new api-version got fully deployed yesterday night.
We do apologize for that.
I am closing this as fixed.
