### ISSUE TITLE
functionapp create runtime parameter is ignored

### ISSUE THREAD

**Issue by benc-uk** [Azure/azure-cli#7534]
**Describe the bug**
The runtime parameter of `functionapp create` is ignored

**To Reproduce**
run 
```
az functionapp create -g myResGroup -s mystorage37462 -n newFunctionApp --os-type Windows --runtime node -c northeurope
```
When the function app is deployed the application setting **FUNCTIONS_WORKER_RUNTIME** is missing and the portal prompts you to set the runtime.
I don't understand why the `--runtime` parameter exists if it doesn't do anything

**Expected behavior**
The function is created with runtime and **FUNCTIONS_WORKER_RUNTIME** set to `node`

**Environment summary**
Cloud Shell and WSL (installed via apt)
azure-cli (2.0.47)

**Additional context**
Nothing

**Comment by panchagnula** [comment]
@ankitkumarr can you take a look please.

**Comment by ankitkumarr** [comment]
Looks like right now, the `--runtime` flag works only for `--os-type linux`.

I will make an update to fix it for Windows.
