### ISSUE TITLE
front-door aci command are not available

### ISSUE THREAD

**Issue by malachma** [Azure/azure-cli#7535]
When will the ACI commands for front-door be available?
Even the CLI Edge build is missing support for them 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e1b5ddd-0054-0175-b689-d20a1349bedb
* Version Independent ID: 72ccc1b6-814f-b780-99cd-ab48dfdecb66
* Content: [az network front-door](https://docs.microsoft.com/en-us/cli/azure/ext/front-door/network/front-door?view=azure-cli-latest#ext-front-door-az-network-front-door-check-custom-domain)
* Content Source: [latest/docs-ref-autogen/ext/front-door/network/front-door.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/ext/front-door/network/front-door.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
@jmelvinwork

**Comment by malachma** [comment]
Thanks, that was the missing piece. Our existing docu should be Extended with this Detail as well
--> https://docs.microsoft.com/de-de/azure/frontdoor/
This issue can be closed

**Comment by rajarshi-singh** [comment]
> Need to install the extension by running `az extension add --name front-door` first
> 
> https://github.com/Azure/azure-cli-extensions/tree/master/src/front-door

Thanks, this helps. Also note that you need Azure CLI version 2.0.68 or beyond for this extension to be available for installation.
