### ISSUE TITLE
az vm extension set: error message hides the service error

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-cli#754]
```
$ az vm extension set -n CustomScript --publisher Microsoft.Azure.Extensions --auto-upgrade-minor-version -g ahmet-test --vm-name ub16
Starting vm extension set
ERROR: Long running operation failed with status 'Failed'
```

obviously this extension setting is missing something like `--settings '{"commandToExecute":"date"}'` therefore extension returns a failure for humans:

![image](https://cloud.githubusercontent.com/assets/159209/17982157/873723e2-6abb-11e6-855a-b95205b439c3.png)

However that error message is hidden from the users in the CLI, confusing them, and then forcing them to go to Portal if they "know the system"

cc: @singhkays @yugangw-msft

**Comment by singhkays** [comment]
Adding folks who are working on this project @JasonRShaver @sauryadas

**Comment by ahmetalpbalkan** [comment]
Oops then I was ccing the wrong people for the past few issues. Apologies. Who's the point of contact for the new compute parts in CLI?

**Comment by singhkays** [comment]
@saurydas is leading this from compute

**Comment by ahmetalpbalkan** [comment]
and who would be the dev counterpart?

**Comment by sauryadas** [comment]
@huangpf FYI

**Comment by yugangw-msft** [comment]
This bug is coming timely.  I have seen AD graph errors are buried as well and was about to open one. 
Python CLI's individual commands by default don't polish errors coming from Azure SDK.  Looks like we need to do something here to get error specific

**Comment by mayurid** [comment]
This is indeed confusing. @yugangw-msft: can we take a look at it all up?

**Comment by yugangw-msft** [comment]
With the fix,  the error from the response will be surfaced:
```
Long running operation failed with status 'Failed' {"message": "Handler 'Microsoft.Azure.Extensions.CustomScript' has reported failure for VM Extension 'CustomScript' with terminal error code '1007' and error message: 'Install failed for plugin (name: Microsoft.Azure.Extensions.CustomScript, version 2.0.0) with exception The specified executable is not a valid application for this OS platform.'", "code": "VMExtensionHandlerNonTransientError"}
```

**Comment by ahmetalpbalkan** [comment]
@yugangw-msft if the response is JSON, then can we print indented JSON output instead of single-line? I think that would help customers better.

**Comment by yugangw-msft** [comment]
`what's the error when you add it to a Linux VM `
The exact error will be consistent with the error reported by portal: `VM has reported a failure when processing extension 'CustomScript'. Error message: \"Enable failed: failed to get configuration: invalid configuration: 'commandToExecute' is not specified\"`. My previous comment was meant to just communicate errors will get surfaced

    `if the response is JSON, then can we print indented JSON output instead of single-line?`
On a second thought, i will pursue the fix at sdk side. After cross check, it appears the SDK base library is already doing error sniffing, but doesn't do it right on the extension errors. I will hold on the change at azure-cli for now. The ideal behavior is you should see one liner error of 'Enable failed: failed to get configuration: invalid configuration: 'commandToExecute' is not specified'

**Comment by yugangw-msft** [comment]
Please reinstall the azure-cli and you should get the fix
