### ISSUE TITLE
incorrect flag name in example

### ISSUE THREAD

**Issue by switj** [Azure/azure-cli#7541]
az iot hub device-identity export --bcu

should be

az iot hub device-identity export -bcu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62c92565-2490-7306-fa08-b16aa2a402a6
* Version Independent ID: 73f40753-0f05-7e45-ca7d-f0a9d2a276ce
* Content: [az iot hub device-identity](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/iot/hub/device-identity?view=azure-cli-latest#ext-azure-cli-iot-ext-az-iot-hub-device-identity-export)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/hub/device-identity.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/hub/device-identity.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
This help text is correct. `--bcu` is a single argument, not three flags, which is how `-bcu` would be interpretted.
