### ISSUE TITLE
--metric Examples?

### ISSUE THREAD

**Issue by AlverezYari** [Azure/azure-cli#7545]
I'm trying to get some simple streaming metrics from one of our Windows VMs into eventhub. I've got the cli command working 95% of the way but I have no clue how to find out the JSON format that the '--metrics' argument needs to work. I suggest linking in some examples of the most common uses (CPU,Memory, Network IN/OUT) in these documents because its mostly a guessing game at this point.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9ae3afa-74ff-12e8-a32c-c01240bd37da
* Version Independent ID: 522b7e55-2510-8e51-021a-2fc134fabfbe
* Content: [az monitor diagnostic-settings](https://docs.microsoft.com/en-us/cli/azure/monitor/diagnostic-settings?view=azure-cli-latest#az-monitor-diagnostic-settings-create)
* Content Source: [src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by gravityuser** [comment]
+1
