### ISSUE TITLE
Incorrect parameter name in `az network vnet subnet create

### ISSUE THREAD

**Issue by omerlh** [Azure/azure-cli#7566]
This is the documentation:
`az network vnet subnet create --address-prefixes` 
When trying it with the CLI, it failed and request missing parameter `--address-prefix`. 

CLI version: `2.0.42`
OS: Mac

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 385e420c-4bd0-3ddd-d9cd-a9a411ec1f7b
* Version Independent ID: 65172372-f485-3d2b-64aa-57c38ac11538
* Content: [az network vnet subnet](https://docs.microsoft.com/en-us/cli/azure/network/vnet/subnet?view=azure-cli-latest#az-network-vnet-subnet-create)
* Content Source: [src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
You need to update your CLI.
