### ISSUE TITLE
Creating AKS when Resource Group policy is enabled

### ISSUE THREAD

**Issue by omerlh** [Azure/azure-cli#7573]
**Describe the bug**
In our subscription, there is a policy that enforces all resource groups to have specific tags. Due to this policy, creating resource groups without these tags is forbidden.
When using `aks create`, a new resource group is created for the nodes, but I couldn't find how I can control this resource group. I need either to be able to supply an existing resource group which I'll create with the required tags or a way to pass tags to this resource group.
I tried to use the `--tags` flags, but it did not help. If I understood correctly this will only control which tags will be on the cluster object.

**To Reproduce**
* Enable a policy that enforces specific tags on resource groups
* Run `aks create`

**Expected behavior**
A cluster is created.

**Environment summary**
Install Method: brew / CLI version `azure-cli (2.0.47)` - brew latest / OS MacOX 10.13.6 / Shell Type bash

**Additional context**
This is the error returned by the CLI:
```
Deployment failed. Correlation ID: e74a6225-d7fb-44cb-a854-ea17d69758f6. unable to create resource group. error: resources.GroupsClient#CreateOrUpdate: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="RequestDisallowedByPolicy" Message="Resource 'MC_<redacted>_<redacted>-cluster_westus' was disallowed by policy. Policy identifiers: '[{\"policyAssignment\":{\"name\":\"Enforce <> tag on resource group\",\"id\":\"/subscriptions/<redacted>/providers/Microsoft.Authorization/policyAssignments/ceddc4997c96421a9a0e9082\"},\"policyDefinition\":{\"name\":\"Enforce tag on resource group\",\"id\":\"/subscriptions/<redacted>/providers/Microsoft.Authorization/policyDefinitions/f574c9e6-af80-452e-b85c-63a6f4f4d052\"}},{\"policyAssignment\":{\"name\":\"Enforce <> tag on resource group\",\"id\":\"/subscriptions/<redacted>/providers/Microsoft.Authorization/policyAssignments/ea8782ce687e4e30a567a72e\"},\"policyDefinition\":{\"name\":\"Enforce tag on resource group\",\"id\":\"/subscriptions/<redacted>/providers/Microsoft.Authorization/policyDefinitions/f574c9e6-af80-452e-b85c-63a6f4f4d052\"}}]'." Target="MC_<redacted>_<redacted>-cluster_westus" AdditionalInfo=[{"info":{"policyAssignmentDisplayName":"Enforce <> tag on resource group","policyAssignmentId":"/subscriptions/<redacted>/providers/Microsoft.Authorization/policyAssignments/ceddc4997c96421a9a0e9082","policyAssignmentName":"ceddc4997c96421a9a0e9082","policyAssignmentParameters":{"tagName":{"value":"creator"}},"policyAssignmentScope":"/subscriptions/<redacted>","policyDefinitionDisplayName":"Enforce tag on resource group","policyDefinitionEffect":"deny","policyDefinitionId":"/subscriptions/<redacted>/providers/Microsoft.Authorization/policyDefinitions/f574c9e6-af80-452e-b85c-63a6f4f4d052","policyDefinitionName":"f574c9e6-af80-452e-b85c-63a6f4f4d052"},"type":"PolicyViolation"},{"info":{"policyAssignmentDisplayName":"Enforce <> tag on resource group","policyAssignmentId":"/subscriptions/<redacted>/providers/Microsoft.Authorization/policyAssignments/ea8782ce687e4e30a567a72e","policyAssignmentName":"ea8782ce687e4e30a567a72e","policyAssignmentParameters":{"tagName":{"value":"team"}},"policyAssignmentScope":"/subscriptions/<redacted>","policyDefinitionDisplayName":"Enforce tag on resource group","policyDefinitionEffect":"deny","policyDefinitionId":"/subscriptions/<redacted>/providers/Microsoft.Authorization/policyDefinitions/f574c9e6-af80-452e-b85c-63a6f4f4d052","policyDefinitionName":"f574c9e6-af80-452e-b85c-63a6f4f4d052"},"type":"PolicyViolation"}]
```

**Comment by tehleet** [comment]
Can we prioritize this issue? It's f** hilarious, that I need to disable more than half my Subscription policies in order to create Azure AKS cluster.

**Comment by sugun999** [comment]
Please treat this as high priority issue

**Comment by tjprescott** [comment]
@mboersma can you triage this?

**Comment by mboersma** [comment]
It's true that there is no way to add tags to the resource group created by `az aks create` currently. Maybe @jnoller can tell us if that's on the roadmap for AKS.

(This isn't a CLI issue, so it might be better to open an issue at https://github.com/Azure/AKS. [This issue](https://github.com/Azure/AKS/issues/207) looks similar.)

**Comment by jnoller** [comment]
Revamping how and what RGs are used is on the AKS roadmap; I do not have any dates to communicate but I have made sure that tagging the RGs and passing in custom ones so customer can meet internal compliance needs.

**Comment by theheatDK** [comment]
It is possible to do now. You of cause has to be a little careful. Do not use too many tags so there is room for the "built-in" ones and make sure that you tag keys are unique.
```
$AksCluster     = Get-AzureRmResource -Name "MyAksCluster" `
                                      -ResourceGroupName "MyAksClusterResourceGroup" `
                                      -ResourceType "Microsoft.ContainerService/managedClusters" `
                                      -ExpandProperties

$ResourceGroupMc = Get-AzureRmResourceGroup -Name $AksCluster.Properties.nodeResourceGroup

$ResourceGroupMc.Tags.Add("myAksTagKey","myAksTagValue")

Set-AzureRmResource -ResourceId $ResourceGroupMc.ResourceId -Force -UsePatchSemantics -Tags $ResourceGroupMc.Tags

```

**Comment by jluk** [comment]
Closing this CLI issue in favor of the existing one on the AKS project. This is on the roadmap and we are likely 3-4 weeks away from supporting cascading tags onto the managed RG.

Please ref this for status:
https://github.com/Azure/AKS/issues/970
