### ISSUE TITLE
Resource not found when MI is in different resource group than the vnet

### ISSUE THREAD

**Issue by f3rdy** [Azure/azure-cli#7575]
I get an error "Resource not found: 'The Resource 'Microsoft.Network/virtualNetworks/MYVNET' under resource group MYRG' was not found.'."

Isn't it possible to create the MI in a different resource group than the vnet is located in?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06c9a36f-c18a-748b-559a-927c7f4988fb
* Version Independent ID: 7af90d97-d085-b8fa-4e02-d3e601a1846d
* Content: [az sql mi](https://docs.microsoft.com/en-us/cli/azure/sql/mi?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by A144546** [comment]
I had the same issue, but you can specify the full path to the vnet or subnet. For example of the subnet:
`--subnet /subscriptions/{SubID}/resourceGroups/{ResourceGroup}/providers/Microsoft.Network/virtualNetworks/{VNETName}/subnets/{SubnetName}`

**Comment by tjprescott** [comment]
@A144546 is correct. If the resource in question is in a different resource group, you *must* specify the fully-qualified resource ID. That pattern is applied throughout the CLI. If you are using names, the resource groups must be the same.
