### ISSUE TITLE
List VMs under availabilitySets table format

### ISSUE THREAD

**Issue by areyesjr** [Azure/azure-cli#7595]
**Is your feature request related to a problem? Please describe.**
It would be nice to list vms under an availability list natively in table format.
az vm availability-set show -n  -g  ->  does not show vms

**Describe the solution you'd like**
az vm availability-set show -n  -g -> should show virtuals under the scaleset

**Describe alternatives you've considered**
if a query can be identified that would show this information it would be great as well.

**Additional context**
I was able to show the vms in Azure-cli under json format but it shows the full path in ID. 
az vm availability-set show -n  -g  -o json

**Comment by adewaleo** [comment]
Hello @areyesjr,

So if you would like to get the VMs under an availability set in table output , you can run the following commands. These commands leverage JMESPATH queries supplied through the `--query` option:

First store the ids in a variable
```
AV_SET_IDS=$(az vm availability-set show -n my-av-set --query "virtualMachines[].id"  -o tsv)
```
then  run:
```
az vm show --ids $AV_SET_IDS --query "[].{VMS:name}" -o table
```
if you want to add additional details, you can run something like this:
```
az vm show -d --ids $AV_SET_IDS --query "[].{VMS:name, PublicIps:publicIps}" -o table
```

For more information about the --query option or JMESPATH see:

- [Query Azure CLI command output](https://docs.microsoft.com/en-us/cli/azure/query-azure-cli?view=azure-cli-latest)
- [JMESPath Examples](http://jmespath.org/examples.html#filters-and-multiselect-hashes)

This should solve your issue.

cc: @yugangw-msft
