### ISSUE TITLE
Azure CLI Show Resource Group Locations

### ISSUE THREAD

**Issue by imeya** [Azure/azure-cli#7602]
when use `az account list-locations`, this location "Australiacentral2 " is listed. 

But when I create a resource group via UI in azure portal, in the Resource Group Location drop-down list, there is no this location "Australiacentral2 ". 

So what's the location "Australiacentral2 " used for?
Can I have another cli command to list all the available locations for resource group?

**Comment by tjprescott** [comment]
There is no specific API for that, but if you try and create the resource group in australiacentral2 you get the following error that does tell you the supported regions:

**The provided location 'australiacentral2' is not available for resource group. List of available regions is 'centralus,eastasia,southeastasia,eastus,eastus2,westus,westus2,northcentralus,southcentralus,westcentralus,northeurope,westeurope,japaneast,japanwest,brazilsouth,australiasoutheast,australiaeast,westindia,southindia,centralindia,canadacentral,canadaeast,uksouth,ukwest,koreacentral,koreasouth,francecentral'.**
