### ISSUE TITLE
[dev_setup.py] In Windows, `check_call(command, shell=True)` breaks when users has AutoRun command in registry

### ISSUE THREAD

**Issue by xscript** [Azure/azure-cli#761]
As stated in title, [the dev_setup.py script](https://github.com/Azure/azure-cli/blob/master/scripts/dev_setup.py) will break in Windows.
When user has AutoRun command in Registry, below error message is thrown.
`Couldn't open requirements file: [Errno 2] No such file or directory: 'requirements.txt'`
Root cause is [here](https://blogs.msdn.microsoft.com/oldnewthing/20071121-00/?p=24433).

A simple fix is to remove the "shell=true" parameter. But I am not sure whether this flag is required in Linux. Haven't tested it yet.
So maybe we can just fix this for Windows.

**Comment by mayurid** [comment]
@xscript : Do you want to do a PR for this?

**Comment by xscript** [comment]
@mayurid 
Sure. Will send out a PR later. 
Just want to know whether there is any other context and confirm the solution with you guys. :smiley:

**Comment by derekbekoe** [comment]
Removing `shell=true` breaks the script on Linux in the same way.
I have created the referenced PR to fix this issue.

You can verify this fix with your particular configuration with:
```
$ git fetch origin pull/798/head:dev_setup_fix
$ git checkout dev_setup_fix
$ python scripts/dev_setup.py
```
If all looks good, we can get the PR merged.

**Comment by derekbekoe** [comment]
Merging #798 and closing issue.
Issue can be reopened if issue persists with AutoRun in registry.
