### ISSUE TITLE
azure storage blob upload-batch needs a --parallelism flag

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli#7616]
**Describe the bug**
`azure storage blob upload-batch` is a bit slow when uploading a lot of smaller files. I feel like it wouldn't be stressing the storage rate limits to do uploads in parallel (even when most blobs are smaller than 64MB which appears to be the only time that multiple connections will currently be used).

**Comment by yugangw-msft** [comment]
The approach of invoking azcopy through CLI, which is on-going in cli extension, should improve it.
We will work out the plan to bring this option to the main repo when it is ready

**Comment by limingu** [comment]
The [azcopy upload command](https://github.com/Azure/azure-cli-extensions/tree/master/src/storage-preview#azcopy-integration) is in our storage-preview extension now. Let us know if you are satisfied with the performance.

Try that like:
az storage azcopy blob upload \
    -c containerName \
    --account-name accountName \
    -s directory/path \
    -d upload/path
    --recursive

**Comment by yonzhan** [comment]
add to S164.

**Comment by Juliehzl** [comment]
please try to use ` az storage copy` in azure cli 2.0.71 or newer version, which already integrate azcopy and can work in parallel.

**Comment by sidroopdaska** [comment]
Why do you folks make it so difficult to upload a directory to Azure Blob Service. The experience with AWS S3 is seamless and here I have wasted an hour to get this to work without any success. There are a dozen APIs some of which are deprecated, some don't work or report progress. UGh!
