### ISSUE TITLE
webapp: Support Azure Site Extensions (Azure App Service)

### ISSUE THREAD

**Issue by tjrobinson** [Azure/azure-cli#7617]
# Background

It's not currently possible to use either the Azure CLI, or Azure PowerShell, to add/remove Azure Site Extensions. It can only be done using ARM templates, the REST API (steep learning curves for beginners, see below) or manually through the Azure Portal. I would like it to be easily scriptable alongside existing CLI or PowerShell scripts I use, including in Azure Cloud Shell.

# Proposed Solution

Add the following commands:

```
az webapp extensions list --name --resource-group
az webapp extensions add --name --resource-group --extension-name [--version]
az webapp extensions remove --name --resource-group --extension-name
```

Where `extension-name` would be the name of the nuget package, e.g. `RemoveCustomHeaders` (https://www.nuget.org/packages/RemoveCustomHeaders).

The `add` command could also update to either the latest version, or the specified version if already installed.

# Alternatives

It's possible to configure Site Extensions using ARM templates but unless you are already using ARM templates, it's potentially a lot of work to get set up, especially for beginners: https://developer.rackspace.com/blog/Azure-WebApp-Extensions-with-ARM/

It's possible to call the Kudu REST API directly, though as you can see from this blog post, it's not straightforward: http://poshdb.com/home/install-azure-app-extension-powershell/

# Additional context

Documentation on what Azure Site Extensions are: https://github.com/projectkudu/kudu/wiki/Azure-Site-Extensions

Blog post describing how to install and manage extensions via the Azure Portal: https://www.michaelcrump.net/azure-tips-and-tricks21/

This existing issue was closed as part of a clean-up: https://github.com/Azure/azure-cli/issues/2590

Note that all Site Extensions are hosted on NuGet, with a tag of `AzureSiteExtension`: https://www.nuget.org/packages?q=Tags%3A%22AzureSiteExtension%22

Copying in @davidebbo (Dev manager on Azure Functions and Azure App Service).

I have raised a similar feature request for Azure PowerShell here: https://github.com/Azure/azure-powershell/issues/7627

Thanks.

**Comment by panchagnula** [comment]
Have no ETA on this.

**Comment by panchagnula** [comment]
We need to design these commands - adding a milestone to track the design phase/plans.

**Comment by rogerprz** [comment]
Any ETA on this?

**Comment by seligj95** [comment]
Thank you for the feedback but we will not be creating dedicated CLI commands at this time.

**Comment by Chervique** [comment]
> It's not currently possible to use either the Azure CLI, or Azure PowerShell, to add/remove Azure Site Extensions.
It IS possible via az resource

**Comment by caleb-terry** [comment]
I can't tell you all how much I love the inconsistency across Azure CLI commands and resources where an action works for one resource type and doesn't for another. For example, being able to add extensions to VMs but not to web apps. Very insightful reasoning into why this won't be implemented. Thanks!
