### ISSUE TITLE
`az curl` or `az rest` for custom REST support (coverage)

### ISSUE THREAD

**Issue by mxplusb** [Azure/azure-cli#7618]
**Is your feature request related to a problem? Please describe.**

The Azure docs have a REST API explorer, and that is helpful for one-off testing, but isn't very helpful for scripting or for REST APIs that haven't made their way into the Azure CLI.

**Describe the solution you'd like**

I'd like to propose adding a new subcommand, such as `az curl` or `az rest`, that allows a user to call a resource provider with a custom payload. I could see the feature looking something like this:

```bash
az {curl,rest} /subscriptions/{subscriptionId}/providers/{Resource.Provider}/{endpoint} \
  --api-version {version} \
  --payload '{"json": "payload"}'
```

or 

```bash
az {curl,rest} /{Resource.Provider}/{endpoint} \
  --subscription {sub-id} \
  --api-version {version} \
  --payload '{"json": "payload"}'
```
or

```bash
az {curl,rest} {endpoint} \
  --subscription {sub-id} \
  --resource-provider {Resource.Provder} \
  --api-version {version} \
  --payload '{"json": "payload"}'
```

This would allow users to pass JSON payloads for scripting or for testing and validating of the REST API for custom clients.

**Describe alternatives you've considered**

Currently you can `curl` the Azure REST API, but you have to pass a lot of authentication context that will persist in your shell history, which can be a security concern. This would alleviate that and allow a user to interact with the raw REST API while letting the Azure CLI handle authentication contexts on behalf of the user.

**Additional context**

You can see a good example of this with the Cloud Foundry CLI, `cf`. You can `cf curl` to interact with raw API resources the CLI doesn't support out of the box.

**Comment by tjprescott** [comment]
@mxplusb have you tried that `az resource create/update` commands?  That is essentially what those do. 

@ppanyukov if there isn't already, please open a feature request for webapps to support these properties. The article is likely referring to use of `--set` on generic update. Opening a specific issue will put it on their radar to add this, and may get you a workaround using `--set` in the meantime.

**Comment by nickwalkmsft** [comment]
I'm struggling to achieve some of the REST calls made in https://docs.microsoft.com/en-gb/azure/storage/common/storage-metrics-in-azure-monitor using an `az resource` command; as far as I can tell they can't be achieved. This feature would be great in the CLI, as `armclient` isn't available in the Cloud Shell.

**Comment by yugangw-msft** [comment]
I recommend we prioritize this work as it becomes helpful not just on ARM but also any rest calls on data plane APIs like AAD Graph. Having such support will not only handle the thorny part like propagating access tokens, but also getting other CLI command built-in supports for free such as output, jmespath, etc.

Regarding the design, I suggest add an argument of HTTP Method like `get/put/post/delete` 

With that, CLI can be used for more scripting scenarios even with temporary service coverage gaps.

**Comment by yugangw-msft** [comment]
i will take this

**Comment by yugangw-msft** [comment]
folks, check out my #9490 and let me know if you have any comments. The command signature looks like:
```
(env) C:\sdk\azure-cli>az rest -h

Command
    az rest : Invoke custom request.

Arguments
    --method         [Required] : HTTP request method.  Allowed values: delete, get, head, options,
                                  patch, post, put.  Default: get.
    --url            [Required] : Request url.
    --body                      : Request body.
    --headers                   : Space-separated appsettings in KEY=VALUE format or JSON string.
                                  Use @{file} to load from a file.
    --output-file               : Save response payload to a file.
    --resource                  : Resource which CLI would acquire token so to put on the
                                  "Authorization" header. By default, CLI can figure this out based
                                  on --url, unless you use ones not in the list of "az cloud show".
    --skip-authorization-header : Do not auto append "Authorization" header.
    --uri-parameters            : Space-separated appsettings in KEY=VALUE format or JSON string.
                                  Use @{file} to load from a file.
Examples
    Get Audit log through Microsoft Graph
        az rest --method get --url https://graph.microsoft.com/beta/auditLogs/directoryAudits


    Update a Azure Active Directory Graph User's display name
        az rest --method patch --headers "{"Content-Type": "application/json"}" --url
        "https://graph.microsoft.com/v1.0/users/johndoe@azuresdkteam.onmicrosoft.com" --body
        "{"displayName":"jondoe2"}"

```

**Comment by mxplusb** [comment]
@yugangw-msft that looks fantastic, it definitely solves my original ask, thanks for following through!

**Comment by yugangw-msft** [comment]
I have merged it to release on June 18. //CC @achandmsft
@nickwalkmsft,  the command for your scenario would be:
```
az rest --method get --url https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/yugangw/providers/Microsoft.Storage/storageAccounts/yugangwstor22/providers/microsoft.insights/metricdefinitions?api-version=2018-01-01
```

**Comment by bigdatamoore** [comment]
Hi @yugangw-msft  can you provide an example of how to use the resource argument?  I am not clear on what I am supposed to pass to that.

**Comment by yugangw-msft** [comment]
Sure, most of times, you don't need to supply values to `--resource` as Azure CLI is able to figure out from `--uri`. e.g.
```
az rest --method get --uri https://graph.microsoft.com/beta/auditLogs/directoryAudits
```   
CLI will default the resource to `https://graph.microsoft.com/`, which is the right one, hence you have nothing to worry about.

`--resource` by itself is a bit confusing, but you can understand it as a service endpoint, and to send a request to it, CLI works underneath to get the appropriate token issued for accessing the service endpoint. When CLI tries to acquire the token, Azure AD requires the `resource` argument, you can always supply it for CLI to pass over to it, or leave to CLI to figure out.
JFYI, `--resource` is also called `relying party`, `web api`, `audience uri`, etc based on the context. 

Hope this helps.

**Comment by Slowdive-Aideron** [comment]
How do i specify the Authorization : bearer $token in the --headers ? i haven't found anything useful . Also is it possible to user az rest -m get on a private keyvault for example ?

**Comment by brandonh-msft** [comment]
@yugangw-msft how do I use this? `az rest` throws an error

**Comment by minascasiou** [comment]
Nice! Thank you.
Does az rest support --query?

I can't seem to get any results when I try it

**Comment by minascasiou** [comment]
> Nice! Thank you.
> Does az rest support --query?
> 
> I can't seem to get any results when I try it




This is what I'm trying...

az rest -m get -u "https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/HaNeCan/providers/Microsoft.Web/sites/HaNeCan/functions?api-version=2019-08-01" --query "[].{id: [].invoke_url_template}"

**Comment by bbkane** [comment]
@Slowdive-Aideron , I was able to run the following successfully:

```bash
readonly vaultBaseUrl="https://concert-kv-dev-bbk-01.vault.azure.net/"
readonly issuerName="digicert-bbkane-com-03"
readonly resource="https://vault.azure.net"

az rest \
    --body "@body.json" \
    --method put \
    --resource "$resource" \
    --uri "${vaultBaseUrl}/certificates/issuers/${issuerName}" \
    --uri-parameters 'api-version=7.2'
```

**Comment by BhargaviAnnadevara-MSFT** [comment]
@yugangw-msft @bbkane Can `az rest` be used to invoke Azure DevOps REST APIs? I haven't been successful in doing so since ADO REST APIs require one to pass a PAT as part of  `--headers` and I couldn't.

Just see a 403 when I run this:
```
az rest --method get --url https://dev.azure.com/xxx/xxx/_apis/wit/workitems/456?api-version=5.0 --headers Authorization="Basic <PAT>"
```

**Comment by jiasli** [comment]
@BhargaviAnnadevara-MSFT, `az rest` definitely works with Azure DevOps REST APIs:

You can see the `'Authorization': 'Basic...'` header is set correctly:

```
> az rest --method get --url https://dev.azure.com/xxx/xxx/_apis/wit/workitems/456?api-version=5.0 --headers Authorization="Basic <PAT>" --verbose
Request URL: 'https://dev.azure.com/xxx/xxx/_apis/wit/workitems/456?api-version=5.0'
Request method: 'GET'
Request headers:
    ...
    'Authorization': 'Basic...'
    ...
Request body:
None
Response status: 401
...
```

Please verify if the PAT is valid. You may use other REST API client, like [postman](https://www.postman.com/), to cross check.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@bbkane Agree. :) However, this effort is for a customer who has their setup scripted all in `az` and doesn't want to switch for the one API call. Hence the need.

**Comment by jiasli** [comment]
@bbkane, nice explanation! You just said everything I want to say. 😄

@BhargaviAnnadevara-MSFT, glad to know `az rest` is working for you.

Indeed, `az rest` is designed to automatically authenticate the request using an AAD `Bearer` access token, furtherly optimized for ARM resource ID as the URL. If you use `Basic` authentication, using `curl` or `Invoke-WebRequest` would be a better choice in environments without `az`. That being said, `az` is still a fully functional REST client that you may use anywhere.

**Comment by jamesrapadmi** [comment]
@yugangw-msft I have the same issue as @BhargaviAnnadevara-MSFT. Is there a `--resource` value that will allow access to the `https://dev.azure.com/_apis`? Or can you only use the PAT method for this? The `az` command clearly can access other devops apis.

**Comment by jiasli** [comment]
@jamesrapadmi,

> Is there a `--resource` value that will allow access to the `https://dev.azure.com/_apis`?

This is out of the scope of Azure CLI, but I will try my best to answer.

---

Using AAD Bearer token to call Azure DevOps API seems to be undocumented. I am not able to find the **resource ID** of Azure DevOps API `https://dev.azure.com/` from the doc https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/authentication-guidance

Then I followed the [sample](https://github.com/microsoft/azure-devops-auth-samples/tree/master/ManagedClientConsoleAppSample) for Interactive client-side (REST):

![image](https://user-images.githubusercontent.com/4003950/131601219-29fe6581-250c-4684-95df-9ca60e5b6693.png)

The `scopes` (for MSAL) is exactly the `resource` (for ADAL, which Azure CLI still uses) we want:

https://github.com/microsoft/azure-devops-auth-samples/blob/30ad4e1ed9cf343c3b001bb07a9a967370661b6b/ManagedClientConsoleAppSample/Program.cs#L28

```cs
        internal static string[] scopes = new string[] { "499b84ac-1321-427f-aa17-267ca6975798/user_impersonation" }; //Constant value to target Azure DevOps. Do not change  
```

So we can use `499b84ac-1321-427f-aa17-267ca6975798` as the value of `--resource` to call `az rest`:

```
> az rest --url 'https://dev.azure.com/azure-sdk/_apis/projects?stateFilter=All&api-version=2.2' --resource 499b84ac-1321-427f-aa17-267ca6975798
{
  "count": 4,
  "value": [
    {
      ...
      "name": "Release",
      ...
    },
    {
      ...
      "name": "public",
      ...
    },
    ...
  ]
}
```

ℹ If you use PowerShell, pay attention to quoting rules: https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md

## Too long; don't read

Actually I did search for `499b84ac-1321-427f-aa17-267ca6975798` in the doc:

![image](https://user-images.githubusercontent.com/4003950/131602076-f230a85c-41ab-468a-ba7c-50052a936148.png)

The only place it appears is https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/manage-personal-access-tokens-via-api. The doc only mentions `499b84ac-1321-427f-aa17-267ca6975798` is for `https://vssps.dev.azure.com/`, but it doesn't mention `499b84ac-1321-427f-aa17-267ca6975798` can also be used for `https://dev.azure.com/`.

Also I found an error in the sample: https://github.com/microsoft/azure-devops-auth-samples/pull/79

**Comment by jamesrapadmi** [comment]
@jiasli that works! Thank you so much! I thought there would be a magic value to make this all work and you've found it for me . Much appreciated.

**Comment by BhargaviAnnadevara-MSFT** [comment]
Awesomesauce! :D Thank you very much @jiasli!
