### ISSUE TITLE
CosmosDB (SQL API) database operations

### ISSUE THREAD

**Issue by alant94** [Azure/azure-cli#7630]
**Describe the bug**
After creating CosmosDB database (SQL API) with name that follows pattern `abc_defg` (three alphanumeric literals + underscore + four alphanumeric literals), methods `az cosmosdb database delete/show` and `az cosmosdb collection create/list` (maybe some others too) don't work, failing with error `binascii.Error: Incorrect padding`

**To Reproduce**
1. Create cosmosDB account with SQL API
2. Create cosmosDB database with name `abc_defg`, for example
3. Try to delete/show this `abc_defg` database from cli, or to create/list collections in it.

**Expected behavior**
Delete/show database, create/list collections in this database

**Environment summary**
Install Method: apt-get
CLI version: 2.0.47-1~xenial
OS version: Ubuntu 16.04.5 LTS
Shell Type: bash, Bash on Windows  

**Additional context**
Output with errors is attached in corresponding files

[list_collections.log](https://github.com/Azure/azure-cli/files/2499095/list_collections.log)
[show_db.log](https://github.com/Azure/azure-cli/files/2499096/show_db.log)
[create_collection.log](https://github.com/Azure/azure-cli/files/2499097/create_collection.log)
[delete_db.log](https://github.com/Azure/azure-cli/files/2499098/delete_db.log)

**Comment by shurd** [comment]
@alant94 thank you for reporting this issue. The CLI was using pydocumentdb for data plane operations (database, collection). There was a bug in this package that caused problems when decoding some base 64 strings. This has been fixed as of [version 3.0.2 of the package](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sdk-python#302). The package was renamed, and I will update our dependencies to capture the fix.
