### ISSUE TITLE
Cannot create profile with Standard Microsoft SKU

### ISSUE THREAD

**Issue by alexpilon666** [Azure/azure-cli#7635]
Azure CLI hasn't been updated to support the Standard_Microsoft SKU, even though it's been GA since September 24th, and in preview for more than 6 months now.
Same goes for the equivalent Powershell module/command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d57c3a30-b150-2982-a70e-72ae5b2b95cf
* Version Independent ID: 5075b7f3-d8ca-c051-d9a1-0b1e6921300a
* Content: [az cdn profile](https://docs.microsoft.com/en-us/cli/azure/cdn/profile?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-cdn/azure/cli/command_modules/cdn/_help.py)
* Service: **cdn**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by alexpilon666** [comment]
Haven't heard anything back in over two weeks.
Any idea when this will be implemented ?
Thanks.

**Comment by AlexandreGarino** [comment]
As of today the CLI does not support the Standard_Microsoft SKU yet.

A workaround is to create the CDN profile through the resource base command:

```
# Create a new CDN profile
az resource create \
    --name myname \
    --resource-group myresourcegroup \
    --resource-type Microsoft.Cdn/profiles \
    --is-full-object \
    --properties \
        '{ 
            "location": "WestEurope",
            "sku": {
                "name": "Standard_Microsoft"
            },
            "tags": { 
                "projectName": "MyProject",
                "environment": "Staging",
                "tier": "FrontEnd"
            }
        }'
```
