### ISSUE TITLE
can't add 'botservice'

### ISSUE THREAD

**Issue by amthomas46** [Azure/azure-cli#7637]
**Describe the bug**
Unable to add botservice extension

**To Reproduce**
Steps to reproduce the behavior.

![image](https://user-images.githubusercontent.com/28786161/47320175-84715300-d605-11e8-9a9e-f6600c972c23.png)

**Environment summary**
Latest DSVM 
Azure CLI 2.0.45

**Additional context**

**Comment by amthomas46** [comment]
upgrading from 2.0.45 CLI to 2.0.47 seems to have addressed the issue. The documentation says 2.0.45 is OK, may want to update

**Comment by tjprescott** [comment]
In the upcoming release, the BotService extension is suppressed as the command module has been greatly enhanced. Please check it out.
