### ISSUE TITLE
CLI Extension not working on MacOs

### ISSUE THREAD

**Issue by carlosscastro** [Azure/azure-cli#7640]
The extension runes perfectly on Windows, but on MacOs will fail with the error below. How do we get the extensions to be compatible with MacOs?

![image](https://user-images.githubusercontent.com/21318528/47325359-3d408d80-d618-11e8-9cd2-f5b10c771540.png)

Thanks!

**Comment by tjprescott** [comment]
Did you install on OSX using Homebrew?

**Comment by tjprescott** [comment]
I did not have any problems running this extension (botservice 0.4.1) on OSX Mojave with CLI version 2.0.48. I recommend updating your CLI.

**Comment by carlosscastro** [comment]
@vishwacsena could you comment on @tjprescott question? Did you install on OSX using Homebrew? That would help bottom this out.

Thanks!

**Comment by vishwacsena** [comment]
I did a clean install yesterday and everything worked. I believe we can close this issue. Thanks!
