### ISSUE TITLE
`az role assignment list` does not work with `--subscription` argument

### ISSUE THREAD

**Issue by ppanyukov** [Azure/azure-cli#7650]
**Describe the bug**

When we run `az role assignment list --subscription="${required_sub_name}"`, it fails when  `"${required_sub_name}"` does not match the active subscription as shown by `az account show`.

The failure is with the message:

> `No matches in graph database for '${assignee}'`

When we set active sub to match `--subscription` argument, everything works just fine.

**To Reproduce**

Using `bash`:

Set ${OTHER_SUB} to be active

```
+ az account set --subscription=${OTHER_SUB}
```

Try getting role assignment from ${REQUIRED_SUB_NAME}
This is expected to fail
Expected error message: No matches in graph database for '${ASSIGNEE_ID}'

```
+ az role assignment list \
  --subscription=${REQUIRED_SUB_NAME} \
  --include-inherited \
  --assignee=${ASSIGNEE_ID} \
  --scope /subscriptions/${REQUIRED_SUB_ID}/resourceGroups/${ACR_RG}/providers/Microsoft.ContainerRegistry/registries/${ACR_NAME}
No matches in graph database for '${ASSIGNEE_ID}'
```

Set ${REQUIRED_SUB_NAME} to be active

```
+ az account set --subscription=${REQUIRED_SUB_NAME}
```

Try getting role assignment from ${REQUIRED_SUB_NAME}
This should succeed now

```
+ az role assignment list \
  --subscription=${REQUIRED_SUB_NAME} \
  --include-inherited \
  --assignee=${ASSIGNEE_ID} \
  --scope /subscriptions/${REQUIRED_SUB_ID}/resourceGroups/${ACR_RG}/providers/Microsoft.ContainerRegistry/registries/${ACR_NAME}

[
  {
    "canDelegate": null,
    "id": "/subscriptions/${REQUIRED_SUB_ID}/resourceGroups/${ACR_RG}/providers/Microsoft.ContainerRegistry/registries/${ACR_NAME}/providers/Microsoft.Authorization/roleAssignments/cb52e595-90ab-4bbb-b3a1-581835e38295",
    "name": "redacted",
    "principalId": "${ASSIGNEE_ID}",
    "principalName": "redacted",
    "resourceGroup": "${ACR_RG}",
    "roleDefinitionId": "/subscriptions/${REQUIRED_SUB_ID}/providers/Microsoft.Authorization/roleDefinitions/redacted",
    "roleDefinitionName": "Reader",
    "scope": "/subscriptions/${REQUIRED_SUB_ID}/resourceGroups/${ACR_RG}/providers/Microsoft.ContainerRegistry/registries/${ACR_NAME}",
    "type": "Microsoft.Authorization/roleAssignments"
  }
]
```

**Expected behavior**

The `az role assignment list` should succeed when used with `--subscription` argument regardless of the active subscription.

**Environment summary**

```
az --version
azure-cli (2.0.48)
```

**Comment by marstr** [comment]
Howdy @ppanyukov does this still repro for you? The scenario you lay out seems to work for me using 2.0.58.

**Comment by marstr** [comment]
Ah, I actually haven't tried reproing this with subscriptions across two separate tenants. I'm about to go AFK, but I'll try to repro this again in the morning.

**Comment by marstr** [comment]
Still looks successful for me when I pick subscriptions across tenant.

**Comment by tjprescott** [comment]
This will likely be fixed in the 2.0.59 release. There was a bug using `--subscription NAME` that was fixed in PR #8484.

**Comment by marstr** [comment]
That would explain why I can't repro it, thought I was going crazy.

**Comment by marstr** [comment]
I'm going to close this out, assuming it was fixed because I can't repro it.
