### ISSUE TITLE
blob copy start-batch and auth-mode=login doesn't work

### ISSUE THREAD

**Issue by cpuguy83** [Azure/azure-cli#7652]
**Describe the bug**
When using `az storage blob copy start-batch` with `--auth-mode=login`, I wind up with an error that the storage account be found, presumably because it's not using the defined auth... not sure if it's not authoring with the source or the destination.

**To Reproduce**

1. `az login` to account with access to a storage account
2. `az storage blob copy-start --auth-mode=login ...`

**Expected behavior**
Since I'm logged in with all necessary credentials (and really in my case the source and target accounts are the same) this should just work.

Currently my work-around is to download and then upload to the new location.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

Version 2.0.47
Using docker image (microsoft/azure-cli:2.0.47)

**Additional context**

**Comment by williexu** [comment]
@cpuguy83 the copy service does NOT support oauth for both the source and destination (only the destination). As such, the CLI generates a sas-token under the hood and uses that to authenticate.

I can improve the experience to query for the source account-key even if using auth-mode login; for now, however please use the source arguments to specify a key or sas_token
