### ISSUE TITLE
[az image create] Provide a way to set default disk caching

### ISSUE THREAD

**Issue by gpenin** [Azure/azure-cli#7655]
Using azure cli to deploy custom images (from a vhd file), leads to images with a default host caching to "None", at least for the os disk.

We should be able, by using arguments like '--storage-caching' and '--data-disk-caching' (like with 'az vm create'), to set the default host caching for the os and data disks.

**Comment by adewaleo** [comment]
One should be able to specify these fields when creating a vm. Is there a reason you would need this feature?

**Comment by gpenin** [comment]
Hi @adewaleo 
We found that using read/write host caching with the os disk gave us a performance benefit in our workloads. We would like this host caching parameter to be the default with our custom images, especially when our customers do not set this parameter with 'az vm create'. The only way to do this now is by creating the images with the Azure Portal, but that's really time consuming (4 images in 27 subscriptions). The hability to set this parameter with 'azure cli' would be a real benefit for us as it would be possible to directly create the image in our build workflow.

**Comment by adewaleo** [comment]
Thanks for the clarification. I will add a parameter to set the default caching for the image. The change should be out this upcoming release.

**Comment by adewaleo** [comment]
closed in #7919
