### ISSUE TITLE
Is it possible to let the created SP reset its password by itself?

### ISSUE THREAD

**Issue by tumluliu** [Azure/azure-cli#7656]
The scenario is that we (admin) have created an SP for an external user, shared the SP name and initial password with that user. Then we would like to put a security policy that enforce the user to change the password after the first time login by him/herself. Note that the role for the SP is very restricted (can only get secrets from a specific KeyVault, nothing else). I tried with the `az ad sp credential reset` after `az login` with the created SP. Azure cli complained with `Insufficient privileges to complete the operation.` which made sense. So what should be the correct way to achieve the goal in such case? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bef1f12-de16-93ed-1cb7-3f3d5d99d786
* Version Independent ID: 4e9329a6-50f8-ee2a-af63-f750d66ed574
* Content: [az ad sp credential](https://docs.microsoft.com/en-us/cli/azure/ad/sp/credential?view=azure-cli-latest#az-ad-sp-credential-reset)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tumluliu** [comment]
Hello Microsoft, could you provide some hints about this? I think the scenario should be typical: we created an SP with very restricted permissions defined by a custom role for our customer, shared the initial credential with them. The custom role's definition looks like this:
```json
{ 
  "Name": "ext-keyvault-xxxxx Reader", 
  "IsCustom": true, 
  "Description": "Can read secrets from KeyVault keyvault-xxxxx", 
  "Actions": [ "Microsoft.KeyVault/vaults/secrets/read" ], 
  "NotActions": [ ], 
  "AssignableScopes": [ 
    "/subscriptions/1111111-1111-1111-1111-1111111111/resourceGroups/rg-xxxxxx/providers/Microsoft.KeyVault/vaults/ext-keyvault-xxxxx" 
  ] 
}
```

Then, the next step will be to let our customer change the credential to sth. we don't want to know. My gut feeling is that there should be some extra permissions/actions need to be added in the custom role. I tried putting `microsoft.aad.directory/applications/credentials/update` in the role definition, but it complained that `microsoft.aad.directory/applications/credentials/update` was not an action. Now I could not figure out what are the proper actions (maybe also the NotActions) should be given. I must also prevent this SP from modifying other SPs' credentials in the same AAD. Any suggestions? Thank you!

**Comment by yugangw-msft** [comment]
The SP's information is saved in AAD graph DB which is sort of orthogonal to RABC roles. For SP to update its own credential, you will need to give the SP some read and write access to your directory which has its own set of concerning

**Comment by yonzhan** [comment]
add to S164.

**Comment by jiasli** [comment]
Permissions are granted on app level. In order for an app to reset its own credential, it needs to have Application Permission **Azure Active Directory Graph > Application.ReadWrite.All permission**, then it can run `az ad app credential reset --id {}`. The side effect is it has permission to reset credentials of other apps as well. 

You may also grant **Azure Active Directory Graph > Application.ReadWrite.OwnedBy** permission and use this app to create child app and login with the child app. The parent app is capable of resetting the credential of the child app.

**Comment by yonzhan** [comment]
@tumluliu any update for this issue? Can we close it?

**Comment by tumluliu** [comment]
@yonzhan Sorry for the delayed reply. We finally decided doing this in some other way to bypass the blocker. I could not verify that from my side as of now unfortunately. You can close this issue ofc if necessary. Thanks!

**Comment by jiasli** [comment]
@tumluliu, thanks for confirming. Don't hesitate to reply here if there is any question regarding this issue.

**Comment by hoadinhmai** [comment]
> Permissions are granted on app level. In order for an app to reset its own credential, it needs to have Application Permission **Azure Active Directory Graph > Application.ReadWrite.All permission**, then it can run `az ad app credential reset --id {}`. The side effect is it has permission to reset credentials of other apps as well.
> 
> You may also grant **Azure Active Directory Graph > Application.ReadWrite.OwnedBy** permission and use this app to create child app and login with the child app. The parent app is capable of resetting the credential of the child app.

Hi @jiasli , we just came across this issue also. Based on the parent and child app setup described above, is it correct that the **parent** app not only can reset credential of the child app but all other apps as well?
