### ISSUE TITLE
Examples please!

### ISSUE THREAD

**Issue by kristianjaeger** [Azure/azure-cli#7661]
Could you please provide examples?  Also it would be great to just do this at the time of resource creation instead of a follow up Azure CLI call.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9984dc8-c276-354c-6c40-db77fad8e7cc
* Version Independent ID: f785cf84-06f2-946e-c8c6-c2a227394335
* Content: [az tag](https://docs.microsoft.com/en-us/cli/azure/tag?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Nearly all create commands support the `--tags` argument to do this at creation time.

**Comment by kristianjaeger** [comment]
Awesome!  I will check that out.  Thanks.

**Comment by adewaleo** [comment]
@kristianjaeger, what command(s) exactly would you like to see examples for or what type of examples would you like?

**Comment by kristianjaeger** [comment]
@adewaleo This was a long time ago.  I believe I was looking for ways to tags resources as I was creating them via the Azure CLI on OS X.

One thing I've noticed, in the past at least, is that the PowerShell Azure CLI seems to be better documented than the OS X / *nix CLI.  Thanks.

**Comment by adewaleo** [comment]
@kristianjaeger.  How do you find Powershell's documentation to be better, so we can improve the CLI's docs?

[az resource tag](https://docs.microsoft.com/en-us/cli/azure/resource?view=azure-cli-latest#az-resource-tag) has an example on how to tag resources. Also most create commands include `--tags` for tagging resources on resource creation. e.g. [az vm create](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create), [az storage account create](https://docs.microsoft.com/en-us/cli/azure/storage/account?view=azure-cli-latest#az-storage-account-create) and [az network vnet create](https://docs.microsoft.com/en-us/cli/azure/network/vnet?view=azure-cli-latest#az-network-vnet-create).

**Comment by kristianjaeger** [comment]
@adewaleo Thanks. As I mentioned as of 10/24/18 when I filed this issue.  There were more examples for using Azure CLI with Powershell rather than Bash on OS X.  If that's not the case now then your teams should know. If the *nix CLI docs / examples are better now that's great. Cheers.

**Comment by adewaleo** [comment]
It's interesting you say that, because we've gotten some feedback that some of our commands tend to be more bash-oriented rather that powershell/cmd-oriented. 

Seeing there aren't any directly actionable items concerning this issue. I will go ahead and close it. Thanks @kristianjaeger
