### ISSUE TITLE
[VM] secret format should print warning message when used with -o table / -o tsv

### ISSUE THREAD

**Issue by adewaleo** [Azure/azure-cli#7665]
**Is your feature request related to a problem? Please describe.**
`vm secret format`'s primary purpose is to generate json output for `vm create --secret`

**Describe the solution you'd like**
It would be good to inform the user that the command is intended to be used with json output.

See #7260

**Comment by tjprescott** [comment]
It seems you could also try erroring out if the user supplied an unsupported format or forcing output to JSON and issuing a warning that the output field is being overriden. You should not just have a chatty message that the command expects `--o json`.
