### ISSUE TITLE
az servicebus queue show -> InvalidApiVersionParameter exception

### ISSUE THREAD

**Issue by Andrey-Anatolyevich** [Azure/azure-cli#7667]
On Ubuntu with Azure CLI installed from here:
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest
I'm unable to use the tool for ServiceBus It crashes with the following:
`InvalidApiVersionParameter - The api-version '2017-04-01' is invalid. The supported versions are '2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.`

**To Reproduce**
0) With valid user account in Azure create some ServiceBus and a queue in it.
1) Install Azure CLI using actual manual:
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest
2) Login under valid account `az login -u [USERNAME] -p [PASSWORD]`
3) Execute the following with valid names:
`az servicebus queue show --resource-group "[resource group name]" --namespace-name "[namespace name]" --name "[queue name]"`

**Expected behavior**
Command is executed without errors. The queue's details are displayed.

**Actual behavior**
The following error message is displayed:
`InvalidApiVersionParameter - The api-version '2017-04-01' is invalid. The supported versions are '2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.`

**Environment summary**
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
**az --version** dump:
` az --version
azure-cli (2.0.49)`

`acr (2.1.7)
acs (2.3.9)
advisor (0.6.0)
ams (0.2.4)
appservice (0.2.5)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.4)
billing (0.2.0)
botservice (0.1.1)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.3)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.7)
core (2.0.49)
cosmosdb (0.2.2)
dla (0.2.3)
dls (0.1.4)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.0)
extension (0.2.2)
feedback (2.1.4)
find (0.2.12)
hdinsight (0.1.0)
interactive (0.3.31)
iot (0.3.3)
iotcentral (0.1.3)
keyvault (2.2.5)
lab (0.1.2)
maps (0.3.2)
monitor (0.2.5)
network (2.2.7)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.2)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.0)
resource (2.1.5)
role (2.1.8)
search (0.1.1)
servicebus (0.3.1)
servicefabric (0.1.6)
signalr (1.0.0)
sql (2.1.5)
storage (2.2.3)
telemetry (1.0.0)
vm (2.2.6)`

`Python location '/opt/az/bin/python3'
Extensions directory '/root/.azure/cliextensions'`

`Python (Linux) 3.6.5 (default, Oct 18 2018, 19:51:37)
[GCC 7.3.0]`

`Legal docs and information: aka.ms/AzureCliLegal`

**Additional context**
The only things are installed on top of clean ubuntu are:
MySql
Zabbix

I believe, none of them should cause any issues.

Please, fix the bug.

**Comment by apraovjr** [comment]
@jfggdl  @mozehgir  

To reproduce, i followed the steps as mentioned in the issue. The command 

az servicebus queue show --resource-group "[resource group name]" --namespace-name "[namespace name]" --name "[queue name]"  executes and successfully returns the response.

When i ran the `az --version` the dump is as follows

azure-cli                         2.0.67

acr                                2.2.9
acs                                2.4.4
advisor                            2.0.1
ams                                0.4.7
appservice                        0.2.21
backup                             1.2.5
batch                              4.0.3
batchai                           0.4.10
billing                            0.2.2
botservice                         0.2.2
cdn                                0.2.4
cloud                              2.1.1
cognitiveservices                  0.2.6
command-modules-nspkg               2.0.2
configure                         2.0.24
consumption                        0.4.4
container                         0.3.18
core                              2.0.67
cosmosdb                          0.2.11
deploymentmanager                  0.1.1
dla                                0.2.6
dls                               0.1.10
dms                                0.1.4
eventgrid                          0.2.4
eventhubs                          0.3.7
extension                          0.2.5
feedback                           2.2.1
find                               0.3.4
hdinsight                          0.3.5
interactive                        0.4.5
iot                               0.3.11
iotcentral                         0.1.7
keyvault                          2.2.16
kusto                              0.2.3
lab                                0.1.8
maps                               0.3.5
monitor                           0.2.15
natgateway                         0.1.1
network                            2.5.2
nspkg                              3.0.3
policyinsights                     0.1.4
privatedns                         1.0.2
profile                            2.1.5
rdbms                             0.3.12
redis                              0.4.4
relay                              0.1.5
reservations                       0.4.3
resource                          2.1.16
role                               2.6.4
search                             0.1.2
security                           0.1.2
servicebus                         0.3.6
servicefabric                     0.1.20
signalr                            1.0.1
sql                                2.2.5
sqlvm                              0.2.0
storage                            2.4.3
telemetry                          1.0.2
vm                                2.2.23

Python location '/opt/az/bin/python3'
Extensions directory '/home/aprao/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Jun 13 2019, 21:23:14)
[GCC 7.4.0]

Legal docs and information: aka.ms/AzureCliLegal

I would suggest to try it out with latest CLI as i am not able to repo it.

**Comment by jfggdl** [comment]
@Andrey-Anatolyevich, I am going to close this issue, but feel free to reopen it if you are able to reproduce your original problem. Thanks.
