### ISSUE TITLE
When tagging the Azure HDInsight Cluster using az resource tag --tags environment=development --ids $rid, it is failing

### ISSUE THREAD

**Issue by AzureCloudArchitect** [Azure/azure-cli#7676]
When tag the Azure HDInsight Cluster using 

az resource tag --tags environment=development --ids $rid

it fails with the following error message

“Operation failed with status: 'Bad Request'. Details: 'BlueprintUri' cannot be used together with 'Kind'. Please specify only one of the properties during create.,Both 'password' and 'sshProfile' cannot be null,Both 'password' and 'sshProfile' cannot be null,Both 'password' and 'sshProfile' cannot be null”

To reproduce this issue, ensure that you have a hdinsight cluster

try to tag it from az cli / Cloudshell using the command 

az resource tag --tags environment=development --ids $rid

I am using the same command to tag all the resources in my subscription and it works well. But when trying to tag the HDInsight Cluster the issue happens..

**Environment summary**
Azure Subscription and a HD Insight Cluster.

Please help me fix this issue. (Created a ticket with Microsoft Azure Support and they confirmed that it is a bug.)

**Comment by AzureCloudArchitect** [comment]
Please note: I am able to tag the same HD Insight Cluster using Azure PowerShell command and the Azure Portal (Portal.azure.com).

**Comment by AzureCloudArchitect** [comment]
any updates?

**Comment by wawon-msft** [comment]
This is a server-side bug where our RP has issues updating via PUT from the contents of a GET on the cluster resource. We're tracking this item internally.

Note that this isn't an issue with the HDInsight command module itself, as az resource uses the resource command module and the actual bug is RP-side. This could be avoided if PATCH was used instead, though the right approach is to fix the RP bug.

**Comment by AzureCloudArchitect** [comment]
any updates after 5 months

**Comment by AzureCloudArchitect** [comment]
any updates?

**Comment by tjprescott** [comment]
@wawon-msft

**Comment by aravish** [comment]
Are there any updates on this? Also can you please patch if there is one?

**Comment by pacuna** [comment]
getting same `Both 'password' and 'sshProfile' cannot be null,Both 'password' and 'sshProfile' cannot be null` when trying to create a cluster.

**Comment by idear1203** [comment]
> getting same Both 'password' and 'sshProfile' cannot be null,Both 'password' and 'sshProfile' cannot be null when trying to create a cluster.

Hi @pacuna , would you mind sharing the command that ran into the issue?  Looks like this is a different issue.

**Comment by tylerfox** [comment]
To tag an HDInsight cluster, please use `az hdinsight update --tags`
