### ISSUE TITLE
az vm nic remove not working

### ISSUE THREAD

**Issue by jamvar** [Azure/azure-cli#7683]
I'm trying the command, "az vm nic remove -g omsagenttesting --vm-name vmname --nics nic" just returns the message, "Virtual machine suse12-clitest must have at least one network interface"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44492c80-0c67-be85-468f-61408358305d
* Version Independent ID: 1e9b4811-c10d-e29f-7d48-ba07e17bc322
* Content: [az vm nic](https://docs.microsoft.com/en-us/cli/azure/vm/nic?view=azure-cli-latest#az-vm-nic-remove)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Please reopen if you in fact have multiple NICs on your VM and are still receiving this message
