### ISSUE TITLE
Slot swap reset action deleted all application and connection strings

### ISSUE THREAD

**Issue by mehmetcakmaz** [Azure/azure-cli#7689]
I use "az webapp deployment slot swap" command with -action reset option. This remove all application and connection strings settings including slot settings. 

To Reproduce same situation

1. I create new web apps 
2. Add new slot (name is = test)
3. Add sample application settings both slot (test and production)
4. Final status in test slot application settings
![picture-1](https://user-images.githubusercontent.com/10825597/47594545-7e240380-d984-11e8-8934-7a5ee3ee0523.PNG)
5. Run `az webapp deployment slot swap --name xxx --resource-group yyy --slot test --action preview` command
6. Run `az webapp deployment slot swap --name xxx --resource-group yyy --slot test --action reset`
7. Test slot application settings are deleted
![picture-4](https://user-images.githubusercontent.com/10825597/47594685-2a65ea00-d985-11e8-9331-8a7f9cfb8050.PNG)

Normally all settings should not be deleted. I tried the same issue Azure portal and "Switch-AzureRmWebAppSlot" everything worked as it should

**Environment summary**
Install Method is MSI / CLI version (2.0.43) / OS version Windows / Shell Type Windows

**Comment by yugangw-msft** [comment]
@panchagnula, any comments?

**Comment by panchagnula** [comment]
Yes, anything set as SlotSetting should not be deleted, this does seem like a bug on CLI end.

**Comment by panchagnula** [comment]
@mehmetcakmaz  one clarification i need here before i start debugging this on the CLI end is that was the app settings, set as Slot Settings using CLI or portal?

**Comment by mehmetcakmaz** [comment]
> @mehmetcakmaz one clarification i need here before i start debugging this on the CLI end is that was the app settings, set as Slot Settings using CLI or portal?

I used the portal

**Comment by panchagnula** [comment]
@mehmetcakmaz, turns out the  bug is in the CLI command where the default value for target-slot is not being set, run the --action preview command as follows

az webapp deployment slot swap --name xxx --resource-group yyy --slot test --action preview **--target-slot production** , followed by the reset command, We will have a fix deployed for this with our next release

**Comment by yugangw-msft** [comment]
Fixed
