### ISSUE TITLE
Add related tools to docker image

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#769]
It would be helpful to add the following tools to our docker image:
- jq
- jpterm
- jp
- azure (xplat cli)

**Comment by mayurid** [comment]
@JasonRShaver : curious why do you think xplat cli is important?

**Comment by BurtBiel** [comment]
@JasonRShaver @mayurid I think the motivation for including xplat was so users could use both ARM and ASM with a single image.

**Comment by derekbekoe** [comment]
Related to https://github.com/Azure/azure-cli/issues/947

**Comment by derekbekoe** [comment]
The linked PR adds jp, jq and jpterm.
xplat cli has not been added. As mentioned in https://github.com/Azure/azure-cli/issues/947#issuecomment-260799310, we can discuss if we still wish to do this later.
