### ISSUE TITLE
Download all secrets in a key vault in on go

### ISSUE THREAD

**Issue by andreacassioli** [Azure/azure-cli#7692]
**Is your feature request related to a problem? Please describe.**
I would like to download all the secrets contained in a key vault in one go. Instead it seems the only way is to get them one at the time and only dumped in a file.

**Describe the solution you'd like**
a command to get all secrets in one go

**Comment by andreacassioli** [comment]
Any thoughts about this?

**Comment by tjprescott** [comment]
@schaabs for comment

**Comment by andreacassioli** [comment]
Bump...

**Comment by yonzhan** [comment]
add to S164.

**Comment by yungezz** [comment]
need a design discussion.

**Comment by yungezz** [comment]
PR ready, need confirm with PM. @bim-msft could you pls follow up on this? thanks

**Comment by bim-msft** [comment]
> PR ready, need confirm with PM. @bim-msft could you pls follow up on this? thanks

Sure, will send mail to PM to further discuss this.

**Comment by nihar** [comment]
Is there any update to this? Would love to have [12243](https://github.com/Azure/azure-cli/pull/12243) merged

**Comment by evelyn-ys** [comment]
Sorry we had a discussion with keyvault service PM and they don't think it's safe and necessary. Please consider `az keyvault secret list` and then download one by one with simple script
