### ISSUE TITLE
AKS supported Regions

### ISSUE THREAD

**Issue by pradm** [Azure/azure-cli#7693]
can we have a separate command to list AKS Supported regions using az aks, Today i am able to gather this information via portal or from command like using the following.

C:\Python34\Scripts&gt;az aks get-versions --location SouthAsia
No registered resource provider found for location 'SouthAsia' and API version '2017-09-30' for type 'locations/orchestrators'. The supported api-versions are '2017-09-30'. The supported locations are 'eastus, westeurope, centralus, canadaeast, canadacentral, uksouth, ukwest, westus, westus2, australiaeast, northeurope, japaneast, eastus2, southeastasia'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-versions)
* Content Source: [latest/docs-ref-autogen/aks.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/aks.yml)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
Will `az provider show -n Microsoft.ContainerService` be enough?

**Comment by yugangw-msft** [comment]
closing

**Comment by pradm** [comment]
Sure thank you so much.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
