### ISSUE TITLE
VM create should show usage error when `--vnet-name` and `--subnet` are used incorrectly

### ISSUE THREAD

**Issue by areyesjr** [Azure/azure-cli#7700]
I need to create a VM in resource group B.
I need that VM to be connected to vnet on resource group A.
I am pointing directly to the vnet id but its failing. 
I do not have any problems when using the portal to duplicate this. 

vnet=$(az network vnet show -g test -n test -o tsv --query id)

az vm create \
--resource-group $rg \
--name $vm \
--image Win2016Datacenter \
--size Standard_A2 \
--admin-username $user \
--admin-password $pass \
--public-ip-address $vm"-ip" \
--vnet-name $vnet \
--nsg $nsg \
--subnet $subnet

# This is the error that I get
Azure Error: InvalidTemplate
Message: Deployment template validation failed: 'The template resource 'resourceGroups/$RG/providers/Microsoft.Network/virtualNetworks/$VNET' for type 'Microsoft.Network/virtualNetworks' at line '1' and column '398' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-template/#resources for usage details.'.

**Comment by tjprescott** [comment]
'resourceGroups/$RG/providers/Microsoft.Network/virtualNetworks/$VNET'

This is not a valid ID.  IDs start with subscription. Furthermore, the parameter is `--vnet-name`.  It does not accept an ID.

`--subnet ID | --vnet-name NAME --subnet NAME`

I will leave this issue open since you should have gotten a usage error.

**Comment by areyesjr** [comment]
Sorry I omitted the full path to not show information. Here is the full error. It did show the correct ID and I do have the correct --vnet-name parameter. I set the variable "vnet" with output the azure-cli command to show vnet id. Thanks in advance.

# Error

Azure Error: InvalidTemplate
Message: Deployment template validation failed: 'The template resource '/subscriptions/$subid/resourceGroups/$rg/providers/Microsoft.Network/virtualNetworks/test-vnet' for type 'Microsoft.Network/virtualNetworks' at line '1' and column '398' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-template/#resources for usage details.'.

**Comment by tjprescott** [comment]
You don't have `--vnet-name` set correctly because `--vnet-name` only accepts a vnet *name*, not an ID. Only `--subnet` accepts a name or ID.

**Comment by areyesjr** [comment]
ah thanks missed that. 
So basically I need to reference the ID of the subnet and remove the reference of vnet. 
Since referencing the subnet automatically adds the correct vnet. 

This works thanks!!

**Comment by tjprescott** [comment]
Exactly :smile:

**Comment by tjprescott** [comment]
@adewaleo please schedule for the appropriate upcoming sprint to add this validation.

**Comment by tjprescott** [comment]
PR #7824 merged.

**Comment by flavionakao** [comment]
https://stackoverflow.com/questions/65689873/cant-create-azure-virtual-machine-using-the-cli
