### ISSUE TITLE
Some azure-cli documents have no 'edit' button to link to the source file.

### ISSUE THREAD

**Issue by daxianji007** [Azure/azure-cli#7706]
**Describe the bug**
Some azure-cli documents have no 'edit' button to link to the source file.

**To Reproduce**
Sample page https://docs.microsoft.com/en-us/cli/azure/managedapp?view=azure-cli-latest.

**Expected behavior**
Every command group should have an 'edit' button, such as https://docs.microsoft.com/en-us/cli/azure/ams/account?view=azure-cli-latest 

**Environment summary**
None

**Additional context**
The root cause should be that the mapping file did not update with the new command group. See the mapping here: https://github.com/Azure/azure-cli/blob/dev/doc/sphinx/azhelpgen/doc_source_map.json. When managedapp is added into the mapping, the Docs CI will update the page to show the 'edit' button.

**Comment by layog** [comment]
I have fixed the `mangedapp` 'edit' mapping, but how do I view the Docs CI?

I am searching for any more such discrepancies and will add those to this PR, if I find any.

**Comment by layog** [comment]
I have added some other missing mappings such as `aks`, `functionapp` etc.

The mapping for `identity` is also missing, but I was not able to find the respective `_help.py`

**Comment by yonzhan** [comment]
add to S164.

**Comment by haroldrandom** [comment]
@daxianji007  I guess currently you can click the `edit` link. Which will redirect you to the Github repo source file.
![image](https://user-images.githubusercontent.com/14357159/72048598-1e4f1980-32f8-11ea-8090-e0ae79cc88dc.png)

@layog If you want to submit your sugguestion to help content please click the pencil icon button to fire a PR. 
![image](https://user-images.githubusercontent.com/14357159/72048735-6cfcb380-32f8-11ea-8a41-3f3f5c029d45.png)

Close as solved. Feel free to reopen if I missed something.
