### ISSUE TITLE
'az ad group delete' Insufficient privileges to complete the operation.

### ISSUE THREAD

**Issue by KenticoMartinS** [Azure/azure-cli#7708]
**Environment summary**
```
az --version
azure-cli (2.0.49)

acr (2.1.7)
acs (2.3.9)
advisor (0.6.0)
ams (0.2.4)
appservice (0.2.5)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.4)
billing (0.2.0)
botservice (0.1.1)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.3)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.7)
core (2.0.49)
cosmosdb (0.2.2)
dla (0.2.3)
dls (0.1.4)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.0)
extension (0.2.2)
feedback (2.1.4)
find (0.2.12)
hdinsight (0.1.0)
interactive (0.3.31)
iot (0.3.3)
iotcentral (0.1.3)
keyvault (2.2.5)
lab (0.1.2)
maps (0.3.2)
monitor (0.2.5)
network (2.2.7)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.2)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.0)
resource (2.1.5)
role (2.1.8)
search (0.1.1)
servicebus (0.3.1)
servicefabric (0.1.6)
signalr (1.0.0)
sql (2.1.5)
storage (2.2.3)
telemetry (1.0.0)
vm (2.2.6)
```

**Describe the bug**
We are maintaining some of our Azure AD Groups from script using service principal login for AZ CLI. Service principal is part of **Directory Writer** role with following granted permissions (**Azure Active Directory** -> **App registrations (Preview)** -> **Service Principal** -> **API permissions**):
![image](https://user-images.githubusercontent.com/17612117/47732994-9e471180-dc67-11e8-81d8-f4379d0c3f23.png)

We are able to create Azure AD Group and add members without any problem. However, when we try to delete the group we get an error 'Insufficient privileges to complete the operation.'

```
az ad group delete --group add1e175-d0cd-49b6-b778-b06b898ea645
Insufficient privileges to complete the operation.
```

Are there any other permissions that we must assign to service principal to fix the error?

**Comment by yugangw-msft** [comment]
CLI, and Azure Resource Manager, works with AAD Graph, not MS Graph. Different things. You should configure the API of "windows azure active directory"
