### ISSUE TITLE
Information update

### ISSUE THREAD

**Issue by hahazeMSFT** [Azure/azure-cli#7711]
**Describe the bug**

Discrepancy with the username used for CLI quick create command. [Documentation](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create) says default value: <b>VssAdministrator</b>,  but notice CLI is using the current user as the default username which changes depending on who is logged in.
![CLI information](https://i.imgur.com/5pcX1Js.png)

**To Reproduce**

`az vm create -n MyLinuxVM -g MyResourceGroup --image UbuntuLTS`

**Environment summary**

azure-cli (2.0.49)

Seeing same behavior on CloudShell and CLI on Ubuntu or Bash on Windows

**Comment by tjprescott** [comment]
The online docs are incorrect. The default value is, intentionally, the current user.

**Comment by hahazeMSFT** [comment]
Thought is was a misroute when I got routed here but document team just referred me to Azure-CLI for to get this information updated.

[https://github.com/MicrosoftDocs/azure-docs/issues/17933](https://github.com/MicrosoftDocs/azure-docs/issues/17933)

**Comment by adewaleo** [comment]
Hello @hahazeMSFT, if you run the cli locally (`az vm create -h`), the default user will be the current user's name. However, I will add this issue to a project I am currently working on so that the displayed default user is something clearer like "user".

**Comment by hahazeMSFT** [comment]
The concern is just for a document to reflect the correct information. Currently it says username default value: VssAdministrator

https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create

[https://i.imgur.com/imbzhPz.png](https://i.imgur.com/imbzhPz.png)

Thanks.

**Comment by adewaleo** [comment]
> The concern is just for a document to reflect the correct information. Currently it says username default value: VssAdministrator
> 
> https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create
> 
> https://i.imgur.com/imbzhPz.png
> 
> Thanks.

You are right. I understand this is the issue. I should have been clearer in my previous comment. 
What i meant to say is:
"... so that the displayed default user **on the online docs** is something clearer like 'user'." Do you have a preference for what the online docs should say?

**Comment by tjprescott** [comment]
@adewaleo as discussed, the sphinx generation script should mock the result of the method called to return a logical placeholder.
