### ISSUE TITLE
Key Vault Create Fails

### ISSUE THREAD

**Issue by samkreter** [Azure/azure-cli#7715]
**Describe the bug**
On the current dev branch, when executing the command 'az keyvault create -g myResourceGroup -n mykeyvault' it fails with error "AttributeError: 'GraphRbacManagementClient' object has no attribute 'signed_in_user'' (See picture below)

![image](https://user-images.githubusercontent.com/5633835/47748313-ba3abb00-dc47-11e8-8615-8a417ea8d877.png)

It seems to be working on the currently released version.

**To Reproduce**
On the latest dev branch, run az keyvault create -g myResourceGroup -n mykeyvault

**Expected behavior**
Create a new keyvault

**Environment summary**
Using PowerShell on Windows. KeyVault version (2.2.4) and CLI version (2.0.48)

**Comment by tjprescott** [comment]
You need to re-run the dev setup script to pull in the updated dependencies.
