### ISSUE TITLE
[AMS] Issues to resolve prior to GA

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#7718]
**az ams account-filter**
 - [ ]	Add the time scale format in the help text
 - [ ]  Consider using `get_datetime_type` in `azure.cli.core.commands.parameters` for better UX with ISO8601 formats
 - [ ] Bitrate: add units in the help text
**az ams asset filter**
 - [ ] Same issues as account-filter
**Get Streaming Locators**
 - [ ] Should be list-streaming-locators, not get
 - [ ] Return the contents (which is an actual list)
**az ams content-key-policy**
 - [ ] Policy Option name - why is this required?
 - [ ] OpenID connect discovery document  - what is it?  A URL?
 - [ ] Rental Duration - should point out the units and/or format
 - [ ] Commands which say “get value by running this command…” should use the `populator-commands` kwarg in help.py  (https://github.com/Azure/azure-cli/blob/dev/doc/authoring_help.md#example-yaml-help-file-_helppy)

**az ams live-event create**
 - [ ] Stream options - should say it is a "Space separated list of …"
 - [ ] Since `--no-wait` is used, should expose the `wait` command (https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#register-commands) (scroll down to “wait_command”)
 - [ ]	Vanity URL: Show what the URL would look like so that the customer understands that it comes from the name. 
 - [ ]	Silverlight Client Access Policy: Add a URL to this doc.
 - [ ] Cross domain URL also - link to the doc.
 - [ ] Preset names: Call out the predefined ones. (720PDefault, etc..)
 - [ ] Key frame interval: ISO 8601 (use `get_datetime_type` for improved UX)

**az ams live-event**
 - [ ] support `wait` command 

**az ams live-event reset**
 - [ ] Link to the documentation on this or provide some longer explanation on this. 

**az ams live-output create**
 - [ ] ISO 8601 helper on archive window length
 - [ ] Output Snapshot time - put the time format. 

**az ams streaming-endpoint create**
 - [ ] Remove ‘Use "" to clear existing list.’ sentence as it has no sense for a create operation
 - [ ]	Point out max-cache-age format/units

**az ams streaming-endpoint akamai add**
 - [ ]	expiration-time argument: ISO 8601 (get_datetime_type)

**az ams streaming-locator get-content-keys**
 - [ ] Change to list-content-keys

**az ams streaming-locator start/stop**
 - [ ] Support `wait` command

**Comment by akucer** [comment]
Closing as won't fix as Azure Media Services was retired on 6/30/2024 (https://aka-ms/ams-retirement)
