### ISSUE TITLE
Unix

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-cli#772]
https://github.com/Azure/azure-cli/blob/master/doc/preview_instructions.md

It'll work on "Unix" is a bit of a bold claim. :)

![image](https://cloud.githubusercontent.com/assets/159209/18023474/57b97d7e-6bae-11e6-9b72-8d7e84da8e88.png)

**Comment by mayurid** [comment]
@derekbekoe: Should we be more specific to the Unix version we have tried it on

**Comment by ahmetalpbalkan** [comment]
Change looks good
