### ISSUE TITLE
Installing Windows MSI on VM requires VM to be restarted

### ISSUE THREAD

**Issue by ryancrawcour** [Azure/azure-cli#7720]
Downloaded the MSI from the official docs. 
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest

Run installer. 
Installer completes.
No errors, no warnings, no info. 

Try run _az login_ in a PowerShell window, errs with "az not recognized".

This is a Windows Server 2016
No python installed.

I understand the MSI is meant to wrap _pip install azure-cli_ but that would imply that Python is required

I saw a post on the docs that said the MSI contains Python
But, it never installed Python on my machine

I had to manually install Python, set the PATH, and then run _pip install azure-cli_

**Comment by yugangw-msft** [comment]
@tjprescott, it is a different thing
@ryancrawcour, please verify 2 things for me
1. If you invoke `az` in a command window, does it work?
2. Can you open windows explorer and let me know whether or not there is a az.cmd under `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\web`?  MSI installer is supposed to add its path to the system PATH env variable. Please cross check that as well.

**Comment by ryancrawcour** [comment]
1. No. I tried that. 'az' is not recognized as an internal or external command. 
2. Hard for me to verify now, b/c I manually did pip install and now the files are all there. Pretty sure I checked my entire system for az.cmd and found nothing.

**Comment by yugangw-msft** [comment]
The chance is you might have installed the CLI under admin, and then run it under a normal user, 2 different user accounts involved.

**Comment by ryancrawcour** [comment]
No. Only one user on this machine. An admin. 

This was on a Windows Server 2016 machine. 
Just tried it on a clean Windows 10 machine, and it worked. 
So not sure if it's an OS thing.

**Comment by yugangw-msft** [comment]
I think i found a repro using windows VM. That the MSI's custom action of propagating the env variable change on PATH didn't go through like Win10. I will take a look. This is not a new thing.
Right now, might not be a perfect workaround, but you need to sign out and sign in

**Comment by ryancrawcour** [comment]
ah, yeah, I forgot to mention that this was on a VM.

**Comment by ryancrawcour** [comment]
sign out & sign in is an ok workaround. thanks.

**Comment by yugangw-msft** [comment]
I know what is going on now. The custom action which broadcasts the env PATH change(appended with the CLI's) fails to run on win2016 vm for missing the "MSVCR120.dll". The custom action problem doesn't fail the installation hence the confusion.
I will sort out the right dependency and rebuild out a new executable. 
This problem has been there for a while, so is not a show stopper.

**Comment by ryancrawcour** [comment]
Nice! Thanks for hunting it down. Like you say, not a show stopper. Just thought I was going mad :)

**Comment by yonzhan** [comment]
Close it since we do not have bandwith to do it and this issue is not common because it is only repro when you invoke install under admin mode.
