### ISSUE TITLE
what privileges do I need to execute this method?

### ISSUE THREAD

**Issue by simonschwingel** [Azure/azure-cli#7727]
When trying to add a service principal to a group I receive the error message "Authorization request denied. Insufficient privileges to complete the operation.". What permissions is required to do this? I have tried with role "user admin". This works fine when adding a user to the group - for service principals I get an error.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c659a298-8897-6d50-c1d9-c14a3b0e6364
* Version Independent ID: 2d2bec5b-ef92-f65f-bfd0-ccdabda52a41
* Content: [az ad group member](https://docs.microsoft.com/en-us/cli/azure/ad/group/member?view=azure-cli-latest#az-ad-group-member-add)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
You will need to at least give the SP "read and write application permission" from the API of "Windows Azure Active Directory". If that is not enough, consider "Read and write directory data". When you toggle the checkbox in the portal, don't forget to click the button of "Grant Permission"
In the upcoming CLI release, new commands under of `az ad app permission` should do the same thing for you.

**Comment by yugangw-msft** [comment]
Reactivating as the context is different from I have assumed.

**Comment by yugangw-msft** [comment]
Like I communicated in the email , this is a graph service question that you can get answers from AAD group
