### ISSUE TITLE
"az ad app update" failing with "Update to existing credential with KeyId 'keyId' is not allowed."

### ISSUE THREAD

**Issue by alexpilon666** [Azure/azure-cli#7728]
**Describe the bug**
When trying to update the list of reply URLs associated with a registered app (App Registration), I get thrown the error `Update to existing credential with KeyId 'keyid' is not allowed.`, where `keyId` is the ID of the password credential associated with the app.

This error message has been flagged multiple times, while doing different tasks (mostly Powershell tasks) like [here](https://github.com/Azure/azure-powershell/issues/6784) and [here](https://github.com/Azure/azure-powershell/issues/6855) 

**To Reproduce**
`az ad app update --id %AppId_of_the_app% --reply-urls %some_URL%`

**Expected behavior**
Was expecting the command to update the Reply URLs field in the app with the new value.

**Environment summary**
Install Method: MSI
CLI version: v2.0.49
OS version: Windows 10 Pro v1803
Shell Type: Powershell v5.1.17134.228

**Comment by yugangw-msft** [comment]
It is a bug. The generic update command should not send back the existing credential properties, though it is debatable that graph service should not throw when related credential properties are not changed

**Comment by yugangw-msft** [comment]
@alexpilon666, can you please give me a end to end repro?  I tried out and it appears the service end is able to verify nothing changed on credentials and processes the rest update.
Updating existing credential is not allowed as credential is immutable 
Please reactivate with a repro

**Comment by alexpilon666** [comment]
@yugangw-msft, I don't know exactly what kind of information you're expecting, but here's a full rundown of what I do, with a real app ID, name of my subscription, a valid and existing URL, etc.
Let me know if you need more information and if so, which kind of info you need.

```
PS C:\Users\apilon> az login -u apilon@sidlee.com | Out-Null
Password:
PS C:\Users\apilon> az account set --subscription "Sidlee Dev/QA/UAT Environments"
PS C:\Users\apilon> az ad app update --id "be5bd562-6200-4d2f-877c-f763d1f42faf" --reply-urls "https://mailhog.sidlee.cloud"
Update to existing credential with KeyId '6a0b0ff3-de5f-46e7-927d-94bd0fe92a56' is not allowed.
```

**Comment by yugangw-msft** [comment]
Do you mind

**Comment by alexpilon666** [comment]
There you go: 
```
{
  "acceptMappedClaims": null,
  "addIns": [],
  "appId": "be5bd562-6200-4d2f-877c-f763d1f42faf",
  "appPermissions": null,
  "appRoles": [],
  "availableToOtherTenants": false,
  "deletionTimestamp": null,
  "displayName": "default-webapp-authentication",
  "errorUrl": null,
  "groupMembershipClaims": null,
  "homepage": "https://sidlee.cloud",
  "identifierUris": [
    "https://sidlee.onmicrosoft.com/3af02728-1c16-46c8-92d1-6e01325b4140"
  ],
  "informationalUrls": {
    "marketing": null,
    "privacy": null,
    "support": null,
    "termsOfService": null
  },
  "isDeviceOnlyAuthSupported": null,
  "keyCredentials": [],
  "knownClientApplications": [],
  "logo@odata.mediaEditLink": "directoryObjects/dffa88bb-aed0-45c3-a0d1-d13c3b1561de/Microsoft.DirectoryServices.Application/logo",
  "logoUrl": null,
  "logoutUrl": null,
  "mainLogo@odata.mediaEditLink": "directoryObjects/dffa88bb-aed0-45c3-a0d1-d13c3b1561de/Microsoft.DirectoryServices.Application/mainLogo",
  "oauth2AllowIdTokenImplicitFlow": true,
  "oauth2AllowImplicitFlow": false,
  "oauth2AllowUrlPathMatching": false,
  "oauth2Permissions": [
    {
      "adminConsentDescription": "Allow the application to access default-webapp-authentication on behalf of the signed-in user.",
      "adminConsentDisplayName": "Access default-webapp-authentication",
      "id": "a6481835-9864-4f37-8585-aab1f7c98619",
      "isEnabled": true,
      "type": "User",
      "userConsentDescription": "Allow the application to access default-webapp-authentication on your behalf.",
      "userConsentDisplayName": "Access default-webapp-authentication",
      "value": "user_impersonation"
    }
  ],
  "oauth2RequirePostResponse": false,
  "objectId": "dffa88bb-aed0-45c3-a0d1-d13c3b1561de",
  "objectType": "Application",
  "odata.metadata": "https://graph.windows.net/e7a05cb0-71dc-4803-bf7e-d0e1c5a625d9/$metadata#directoryObjects/@Element",
  "odata.type": "Microsoft.DirectoryServices.Application",
  "optionalClaims": null,
  "orgRestrictions": [],
  "parentalControlSettings": {
    "countriesBlockedForMinors": [],
    "legalAgeGroupRule": "Allow"
  },
  "passwordCredentials": [
    {
      "customKeyIdentifier": "YQB6AHUAcgBlAF8AdwBlAGIAYQBwAHAAXwBwAHcAZAA=",
      "endDate": "2299-12-31T05:00:00Z",
      "keyId": "6a0b0ff3-de5f-46e7-927d-94bd0fe92a56",
      "startDate": "2018-10-31T12:05:09.3838253Z",
      "value": null
    }
  ],
  "publicClient": false,
  "publisherDomain": null,
  "recordConsentConditions": null,
  "replyUrls": [
    "https://sidlee.cloud"
  ],
  "requiredResourceAccess": [
    {
      "resourceAccess": [
        {
          "id": "311a71cc-e848-46a1-bdf8-97ff7156d8e6",
          "type": "Scope"
        }
      ],
      "resourceAppId": "00000002-0000-0000-c000-000000000000"
    }
  ],
  "samlMetadataUrl": null,
  "signInAudience": "AzureADMyOrg",
  "tokenEncryptionKeyId": null
}

```

**Comment by sajithvasu** [comment]
az ad app update worked fine in az cli version 2.0.42
Any idea when this will be resolved ?

**Comment by alexpilon666** [comment]
@yugangw-msft , any follow-up please ? I haven't heard back since my last reply, 8 days ago.
Thanks!

**Comment by yugangw-msft** [comment]
Would be great if you can provide an end to end repro for this say start from `az ad app create`. I have tried at least 5 times, but just can't make it happen.
I can be reached at yugangw at microsoft dot com

**Comment by sajithvasu** [comment]
@yugangw-msft 
This scenario can be reproduced. It does not work on any az cli version after 2.0.42. 
To reproduce this scenario, create keys manually under Azure App Registration --> <appName> --> settings --> API --> Create keys with any name/expiry --> save and then run the app update command. This use to work fine in older version of az cli -2.0.42

$ az ad app update --id $appId --reply-urls https://$hostname/.auth/login/aad/callback

az ad app update --id $appId --set groupMembershipClaims=All

az ad app update --id $appId --required-resource-accesses @manifest.json

You will get this error --> Update to existing credential with KeyId '$keyid' is not allowed.

**Comment by yugangw-msft** [comment]
Repro'd and I have submitted a PR
