### ISSUE TITLE
az role → az ad role

### ISSUE THREAD

**Issue by ahmetb** [Azure/azure-cli#773]
I looked for the role assignment subcommand in `az ad [...]`  commands like 2 minutes then had to create a new Service Principal account (because I recalled it tells the user how to do role assignments) and realized it's under `az role`. 

How was the decision made to put `az role` at the root level?

**Comment by mayurid** [comment]
@ahmetalpbalkan : This is the same Xplat is today so i would think it would be intuitive to the customers. @yugangw-msft : Can you add your thoughts?

**Comment by ahmetalpbalkan** [comment]
@mayurid  Oh I did not know that. I guess users has built up a muscle memory already with `azure role`, no need to break that.
