### ISSUE TITLE
`az account list` unexpected behavior

### ISSUE THREAD

**Issue by lietu** [Azure/azure-cli#7731]
**Describe the bug**
`az account list` output's "name" field always shows `Pay-As-You-Go` even if the Subscription is renamed in Azure Portal.

**To Reproduce**
1. Login
2. `az account list`
3. Rename Subscription from `Pay-As-You-Go` to `My project Pay-As-You-Go` in Azure Portal (and wait for it to go in effect)
4. `az account list`

Doesn't seem to matter if you use `--output table`.

**Expected behavior**
`az account list` should show `My project Pay-As-You-Go` as the name, instead still shows `Pay-As-You-Go`

**Environment summary**
Installed via MSI installer.

```
C:\Users\lietu>az --version
azure-cli (2.0.44)

acr (2.1.3)
acs (2.3.0)
advisor (0.6.0)
ams (0.2.2)
appservice (0.2.2)
backup (1.2.0)
batch (3.3.2)
batchai (0.4.1)
billing (0.2.0)
cdn (0.1.0)
cloud (2.1.0)
cognitiveservices (0.2.0)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.3)
core (2.0.44)
cosmosdb (0.2.0)
dla (0.2.1)
dls (0.1.0)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.2)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.28)
iot (0.3.0)
iotcentral (0.1.0)
keyvault (2.2.2)
lab (0.1.0)
maps (0.3.1)
monitor (0.2.2)
network (2.2.3)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.0)
redis (0.3.0)
relay (0.1.0)
reservations (0.3.1)
resource (2.1.2)
role (2.1.3)
search (0.1.1)
servicebus (0.2.1)
servicefabric (0.1.1)
sql (2.1.2)
storage (2.2.0)
telemetry (1.0.0)
vm (2.2.1)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\lietu\.azure\cliextensions'

Python (Windows) 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal



C:\Users\lietu>ver

Microsoft Windows [Version 10.0.17134.345]
```

Using `cmd.exe` on Windows.

**Additional context**
I've got access to 3 accounts and 3 subscriptions. I renamed the subscriptions specifically to make identifying them on the CLI tools easier. Subscription names have updated everywhere on portal, and I've waited weeks since updating, and `az` still shows the names wrong on the CLI tool.

**Comment by lietu** [comment]
I expected caching might have been the case, however as I mentioned, I've waited weeks.

**Comment by tjprescott** [comment]
This is not something the CLI team can fix. I would recommend you open a support ticket on the Portal to get a more rapid response.

**Comment by lietu** [comment]
And what should I tell them? The portal has updated the name just fine, it's visible everywhere there. I don't see any problem with the portal.

**Comment by tjprescott** [comment]
Actually, run `az account clear` first and then `az account list`.  The CLI maintains a cache of your subscriptions.

**Comment by tjprescott** [comment]
Or `az account list --refresh`

**Comment by tjprescott** [comment]
@yugangw-msft shouldn't `--refresh` work the same as clear + list?  If it isn't working this would be a bug.

**Comment by yugangw-msft** [comment]
@tjprescott, `--refresh` might have a bug. @lietu, can you run "az login" again? That should get things in sync.

**Comment by lietu** [comment]
@yugangw-msft I had to run `login` after `clear`, and it did indeed update the list.

**Comment by yonzhan** [comment]
add to S165.

**Comment by jiasli** [comment]
Checked again the code of `refresh_accounts`:

https://github.com/Azure/azure-cli/blob/5edbd822ee860d7ba5d5182811b68233e0846ba8/src/azure-cli-core/azure/cli/core/_profile.py#L640 

but couldn't locate where the issue may happen. Also can't repro with `az account list --refresh` after changing the subscription name. If it happens again, please capture the network trace with `--debug` and reply to this issue. Thanks.
