### ISSUE TITLE
[Storage] Issues with listing BlockBlobStorage and FileStorage storage accounts.

### ISSUE THREAD

**Issue by williexu** [Azure/azure-cli#7734]
**Describe the bug**
If those storage accounts are present in your subscription or resource group, doing a list or show using a older api-version than `2018-07-01` will result in an exception. This behavior in the service affects all CLI users (as well as all language sdks, and other client tools, as well as users making rest calls directly using older api-versions).

**Additional context**
`storage-preview` extension will be updated to use the `2018-07-01` version of the storage sdk to make all mgmt-plane calls so that users can bypass this restriction for now. Users can install the extension by running `az extension add -n storage-preview`.

**Comment by zhusijia26** [comment]
Close this issue due to idle time. Please reopen if there is still question.
