### ISSUE TITLE
az vm identity remove provides inconsistent/confusing experience

### ISSUE THREAD

**Issue by keyoke** [Azure/azure-cli#7738]
Hi,
My feeling is we can improve the experience when when removing User assigned Identites from a VM

If I run the following command

> $ az vm identity remove -g gelabs -n EX2013-DEV
> {
>   "principalId": null,
>   "tenantId": null,
>   "type": "UserAssigned",
>   "userAssignedIdentities": {
>     "/subscriptions/[SUB ID]/resourceGroups/gelabs/providers/Microsoft.ManagedIdentity/userAssignedIdentities/getestlab": {
>       "clientId": null,
>       "principalId": null
>     }
>   }
> }

its not clear from the output that by default it will only clear the system assigned identity and even if a user assigned identity exists will ignore it, of course there is some mention of this in the --help output. I could be wrong but my feeling is that if there was no System identity defined and only one user assigned identity it should remove it completely, in the case that there are multiple user assigned identities I would show an error message indicating that --identities switch should be used.

Many Thanks

**Comment by adewaleo** [comment]
Hello @keyoke, so the examples for `az vm identity remove` (see [docs](https://docs.microsoft.com/en-us/cli/azure/vm/identity?view=azure-cli-latest#az-vm-identity-remove) or `az vm identity remove -h`) illustrates how the command should be used. 

However, I will update the help text to clarify the command's usage. I think it would be good to leave the command's behavior as is, as that would be consistent with [`az vm identity assign`](https://docs.microsoft.com/en-us/cli/azure/vm/identity?view=azure-cli-latest#az-vm-identity-assign) which also defaults to the system assigned identity if identities is not supplied.

cc @yugangw-msft
