### ISSUE TITLE
az keyvault network-rule add with VNet from a different resource group

### ISSUE THREAD

**Issue by omerlh** [Azure/azure-cli#7739]
**Describe the bug**
I'm trying to create a new KeyVault network rule to allow traffic only from a VNet that exist in a different resource group (not the one containing the KeyVault). This request failed with the following error:
```
Virtual Network could not be validated. code: ResourceNotFound. message: "The Resource 'microsoft.network/virtualNetworks/<>' under resource group '<>' was not found.".
```
**To Reproduce**
* Create 2 resource group, a and b
* Create keyvault in a 
* Create vnet in b
*  Try to create a new rule by using:
```
z keyvault network-rule add --resource-group a --vnet-name <vnet name> --subnet <subnet name> -n <keyvault name>
```
**Expected behavior**
Rule created succesfully 
**Environment summary**
* MacOS, az installed view brew
* `azure-cli (2.0.49)`

**Comment by tjprescott** [comment]
This is not a bug. If you want to reference a subnet in a different resource group, you must supply subnet by ID.

**Comment by omerlh** [comment]
In the name of the vnet? The documentation is a bit unclear

**Comment by tjprescott** [comment]
You can't provide just a VNet. You must supply a subnet. You can do either of the following:
`--vnet-name NAME --subnet NAME | --subnet ID`
For the cross-subscription or cross-RG scenario, you must supply the ID, not names.

**Comment by omerlh** [comment]
Ohh I see. I should have read carefully the docs. Thank you!
