### ISSUE TITLE
Create/Validate deployment template commands should handle improper syntax more gracefully

### ISSUE THREAD

**Issue by tappoz** [Azure/azure-cli#7740]
**Describe the bug**

Not able to deploy an Azure App as a docker container pulled from a private Azure Container Registry.
Seeing an error message referring to some `malformed node or string` (see below).

**To Reproduce**

Run this command:

```sh
az group deployment create \
  --name "deployAzureApp" \
  --resource-group MyRG \
  --template-file ./ci/arm/function-app.json  --verbose --debug
```

Then see this at the bottom of the stdout/stderr:

```
malformed node or string: <_ast.Name object at 0x7f3cecc8add8>
```

The content of the template is this:

```
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "appName": {
      "type": "String",
      "value": "<PUT_APP_NAME_HERE>"
    },
    "dockerImageName": {
      "type": "String",
      "value": "<NAMESPACE>/<IMAGE_NAME>:latest"
    },
    "dockerRegistryUrl": {
      "type": "String",
      "value": "https://<PUT_REGISTRY_HERE>.azurecr.io"
    },
    "dockerRegistryUsername": {
      "type": "String",
      "value": "<PUT_REGISTRY_USERNAME_HERE>"
    },
    "dockerRegistryPassword": {
      "type": "String",
      "value": "<PUT_REGISTRY_PSW_HERE>"
    },
    "servicePlanName": {
      "type": "String",
      "value": "<PUT_EXISTING_SERVICE_PLAN_HERE>"
    },
    "appLocation": {
      "type": "String",
      "value": "<PUT_AZURE_REGION_HERE>"
    }
  },
  "resources": [
    {
      "type": "Microsoft.Web/sites",
      "name": "[parameters('appName')]",
      "location": "[parameters('appLocation')]",
      "properties": {
        "name": "[parameters('appName')]",
        "siteConfig": {
          "linuxFxVersion": "[concat('DOCKER|', parameters('dockerImageName'))]",
          "alwaysOn": true,
          "appSettings": [
            {
              "name": "WEBSITES_ENABLE_APP_SERVICE_STORAGE",
              "value": "false"
            },
            {
              "name": "DOCKER_REGISTRY_SERVER_URL",
              "value": "[parameters('dockerRegistryUrl')]"
            },
            {
              "name": "DOCKER_REGISTRY_SERVER_USERNAME",
              "value": "[parameters('dockerRegistryUsername')]"
            },
            {
              "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
              "value": "[parameters('dockerRegistryPassword')]"
            }
          ],
        },
        "serverFarmId": "[resourceId('Microsoft.Web/serverfarms', parameters('servicePlanName'))]"
      }
    }
  ]
}
```

The template details come from:

- https://docs.microsoft.com/en-us/azure/templates/microsoft.web/sites
- https://stackoverflow.com/a/52177725/1264920
- https://social.msdn.microsoft.com/Forums/aspnet/en-US/966b5126-f361-497f-97cb-e94832a74303/web-app-container-registry-arm-template

**Expected behavior**

Being able to deploy an Azure App.

**Environment summary**

- Install Method: `sudo apt-get install --only-upgrade azure-cli`
- Azure CLI version: `2.0.49`
- OS: Debian stretch 9.5
- Shell Type: Bash

**Comment by tjprescott** [comment]
The error suggests your JSON is malformed. When I open it, I see there is a trailing comma on line 61. Remove that and see if that resolves your issue.

**Comment by tappoz** [comment]
Yep, removing that comma made it work. 

Those error messages are a bit obscure though, is there any other way to get back more information about what's wrong in the validation of the JSON template? I run the command with `--verbose --debug`, but I don't see more details when the error message is printed in red.

**Comment by tjprescott** [comment]
If you run `az group deployment validate` does that give you better results?
