### ISSUE TITLE
docker run command fails for using cli inside docker

### ISSUE THREAD

**Issue by initmahesh** [Azure/azure-cli#7752]
**Describe the bug**
trying to run docker container fails on our device which is Yocto based arm32v7 based 

    # docker run -it microsoft/azure-cli
Unable to find image 'microsoft/azure-cli:latest' locally
latest: Pulling from microsoft/azure-cli
ff3a5c916c92: Pull complete
471170bb1257: Pull complete
d487cc70216e: Pull complete
9358b3ca3321: Pull complete
d4d73eb5841d: Pull complete
d12f14110b3e: Pull complete
b5e14417f811: Pull complete
dce4931f07b0: Pull complete
Digest: sha256:1677d2c3b6692c5665a2b24bf586349367c8a784f8043a7832ae3d7c7cd6ef17
Status: Downloaded newer image for microsoft/azure-cli:latest
standard_init_linux.go:190: exec user process caused "exec format error"
/ # docker run -it microsoft/azure-cli bash
standard_init_linux.go:190: exec user process caused "exec format error"
/ # docker images
REPOSITORY                               TAG                 IMAGE ID            CREATED             SIZE
mycapreg.azurecr.io/visionsamplemodule   1.0.2-arm32v7       ce7304420f58        45 hours ago        941MB
mcr.microsoft.com/azureiotedge-hub       1.0                 7f34a278dbc4        3 days ago          247MB
mcr.microsoft.com/azureiotedge-agent     1.0                 3bff1e93a9c2        3 days ago          231MB
microsoft/azure-cli                      latest              fc79f636e273        2 weeks ago         490MB
/ # docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
/ # docker run -it microsoft/azure-cli
standard_init_linux.go:190: exec user process caused "exec format error"
/ # docker run -it --entrypoint=bash microsoft/azure-cli
standard_init_linux.go:190: exec user process caused "exec format error"
/ # docker run microsoft/azure-cli
standard_init_linux.go:190: exec user process caused "exec format error"
**To Reproduce**
Try running docker based cli experience on https://visionaidevkit.com/

**Expected behavior**
docker should just run …

**Environment summary**
docker run 

**Additional context**

**Comment by tjprescott** [comment]
I have no issues pulling the latest CLI release (2.0.49) via docker and running it with your command. If you are running from a 3rd party dev environment you would need to troubleshoot a potential issue with that platform.
