### ISSUE TITLE
unable to install using Linux steps on Yocto arm32v& dist.

### ISSUE THREAD

**Issue by initmahesh** [Azure/azure-cli#7753]
**Describe the bug**
Installation fails on yocto arm32v7

**To Reproduce**
try below step on rasp Pi …or aicamera by microsoft

/data/misc/camera # curl -L https://aka.ms/InstallAzureCli | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1367  100  1367    0     0   1174      0  0:00:01  0:00:01 --:--:--  1174
Downloading Azure CLI install script from https://azurecliprod.blob.core.windows.net/install.py to /tmp/azure_cli_install_tmp_tOKE.
######################################################################## 100.0%
/tmp/azure_cli_install_tmp_tOKE: OK
Running install script.
-- Verifying Python version.
-- Python version 2.7.13 okay.

'/home/root/lib/azure-cli'): you like to place the install? (leave blank to use '
-- We will install at '/home/root/lib/azure-cli'.

 to use '/home/root/bin'): d you like to place the 'az' executable? (leave blank
-- The executable will be in '/home/root/bin'.
-- Downloading virtualenv package from https://pypi.python.org/packages/source/v/virtualenv/virtualenv-15.0.0.tar.gz.
-- Downloaded virtualenv package to /tmp/tmpUbtdgK/virtualenv-15.0.0.tar.gz.
-- Checksum of /tmp/tmpUbtdgK/virtualenv-15.0.0.tar.gz OK.
-- Extracting '/tmp/tmpUbtdgK/virtualenv-15.0.0.tar.gz' to '/tmp/tmpUbtdgK'.
-- Executing: ['/usr/bin/python', 'virtualenv.py', '--python', '/usr/bin/python', '/home/root/lib/azure-cli']
Traceback (most recent call last):
  File "virtualenv.py", line 25, in <module>
    import distutils.sysconfig
ImportError: No module named distutils.sysconfig
Traceback (most recent call last):
  File "/tmp/azure_cli_install_tmp_tOKE", line 370, in <module>
    main()
  File "/tmp/azure_cli_install_tmp_tOKE", line 355, in main
    create_virtualenv(tmp_dir, install_dir)
  File "/tmp/azure_cli_install_tmp_tOKE", line 135, in create_virtualenv
    exec_command(cmd, cwd=working_dir)
  File "/tmp/azure_cli_install_tmp_tOKE", line 100, in exec_command
    subprocess.check_call(command_list, cwd=cwd, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', 'virtualenv.py', '--python', '/usr/bin/python', '/home/root/lib/azure-cli']' returned non-zero exit status 1

**Expected behavior**
install should work ..
**Environment summary**
curl 

**Additional context**

**Comment by yugangw-msft** [comment]
Can you do `pip install azure-cli` or `dev_setup`? You can also get virtualenv package and create one yourself.  I don't think we support the curl script any more.

**Comment by yonzhan** [comment]
add to S164.

**Comment by fengzhou-msft** [comment]
The script is not tested on Yocto as we don't have support plans for Yocto.
The error comes from python 2 lacking a module on Yocto. You may try the install script again. It uses Python 3 by default now.
