### ISSUE TITLE
add commands for sending/receiving messages to Service Bus and Event Hubs

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-cli#7756]
## Is your feature request related to a problem? Please describe.

I need to carry out tests and one-off operations sending and receiving messages and events to Service Bus and Event Hubs. Today this requires custom code built with those services' packages, such as [azure-event-hubs-python](https://github.com/Azure/azure-event-hubs-python) and [azure-service-bus-python](https://github.com/Azure/azure-service-bus-python).

## Describe the solution you'd like

The CLI already provides dataplane helpers for Storage entities, such as `az storage blob upload ...` and `az storage message put ...`. These are particularly useful for tests and one-off operations.

I'd like similar operations for Service Bus entities, such as `az servicebus message [put | get]` and `az eventhubs event [send | receive]`.

## Describe alternatives you've considered

I've written my own helpers using [azure-service-bus-go](https://github.com/Azure/azure-service-bus-go).

## Additional context

This could be built with [azure-event-hubs-python](https://github.com/Azure/azure-event-hubs-python) and [azure-service-bus-python](https://github.com/Azure/azure-service-bus-python).

**Comment by axisc** [comment]
@joshgav

Thanks for raising the feature request.

Send and Receive operations for Service Bus and Event Hubs must rely on a stateful protocol like AMQP and SBMP since HTTP is too chatty. 

We understand the value in debugging scenarios but we don't have plans to support this for now, but can revisit if there is more customer interest for the same.

**Comment by VinayakRaoB** [comment]
Are there any az cli commands yet to send or receive message from eventhub
