### ISSUE TITLE
az bot create -- add command to specify service plan rather than creating a new one

### ISSUE THREAD

**Issue by himexia** [Azure/azure-cli#7761]
**Is your feature request related to a problem? Please describe.**
I've been using Azure Cli to automate the bot creating process. The thing that bothers me most is that each time I run az bot create command, a service plan is created along with the bot, and a user can end up keeping a bunch of service plans and got a large unexpected bill like myself.

**Describe the solution you'd like**
I think there should be a --plan option for users to specify what service plan the bot app is going to be hosted in.

**Describe alternatives you've considered**
Meanwhile, I'd like to know if there's any workaround.

**Comment by carlosscastro** [comment]
Thank you @himexia, I think this is a great idea. We'll consider it for our next update! @stevengum as FYI.

**Comment by sgellock** [comment]
we've made a design change in that users need to provide AppId and AppPassword to az bot create.  this assumes an az ad call that that would have been mapped to a plan.  said another way, because we've changed how this command works, we no longer need the ability to specify a plan as this occurs with commands run prior

**Comment by himexia** [comment]
> we've made a design change in that users need to provide AppId and AppPassword to az bot create. this assumes an az ad call that that would have been mapped to a plan. said another way, because we've changed how this command works, we no longer need the ability to specify a plan as this occurs with commands run prior

Would you mind elaborate on how to assign a mapped webapp to the bot via az bot create command?

The AppId and AppPassword the command accepts are the credentials of the app created on https://apps.dev.microsoft.com (now is App Registrations from Azure Portal). So far i could not find a way to link these Apps to a webapp.
