### ISSUE TITLE
Possible bug - set private ip

### ISSUE THREAD

**Issue by ymkaos** [Azure/azure-cli#7767]
I was trying to setup a private ip in an internal lb with this command
az network lb frontend-ip update -g $groupNet --lb-name $lb -n $feName --subscription $subs --private-ip-address 10.20.254.5

I wasn't work, no error though. so I tried this one:
az network lb frontend-ip update -g $groupNet --lb-name $lb -n $feName --subscription $subs --set privateIpAddress=10.20.254.5

Same thing, the command ran nomarlly but didn't change the ip at all. 
But I realised that the field privateIpAllocationMethod had changed to Dynamic.
So I set it to static
az network lb frontend-ip update -g $groupNet --lb-name $lb -n $feName --subscription $subs --set privateIpAllocationMethod=Static

Then ran the first command again. no luck. and the allocation method had changed to dynamic again. 
Finally I ran:
az network lb frontend-ip update -g $groupNet --lb-name $lb -n $feName --subscription $subs --set privateIpAllocationMethod=Static
az network lb frontend-ip update -g $groupNet --lb-name $lb -n $feName --subscription $subs --set privateIpAddress=10.20.254.5

And worked. so definelly something is not clear or not working as expected. It's a standard Internal load balancer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f347e399-f8d3-2e98-93f7-e7857a3d32ce
* Version Independent ID: 2cabde06-20be-752a-e75f-240731b6318f
* Content: [az network lb frontend-ip](https://docs.microsoft.com/en-us/cli/azure/network/lb/frontend-ip?view=azure-cli-latest#az-network-lb-frontend-ip-update)
* Content Source: [src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
`az --version`?

**Comment by ymkaos** [comment]
az --version
azure-cli (2.0.43)

acr (2.1.2)
acs (2.2.2)
advisor (0.6.0)
ams (0.2.1)
appservice (0.2.1)
backup (1.2.0)
batch (3.3.1)
batchai (0.4.0)
billing (0.2.0)
cdn (0.1.0)
cloud (2.1.0)
cognitiveservices (0.2.0)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.2)
core (2.0.43)
cosmosdb (0.2.0)
dla (0.2.0)
dls (0.1.0)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.1)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.27)
iot (0.2.0)
keyvault (2.2.1)
lab (0.1.0)
maps (0.3.1)
monitor (0.2.1)
network (2.2.2)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.0)
redis (0.3.0)
reservations (0.3.1)
resource (2.1.1)
role (2.1.2)
search (0.1.0)
servicebus (0.2.1)
servicefabric (0.1.0)
sql (2.1.1)
storage (2.1.1)
vm (2.2.0)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\...\.azure\cliextensions'

Python (Windows) 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)]

**Comment by tjprescott** [comment]
Please update your CLI instance. We are on version 2.0.50 and work has recently been done that should address your concerns. If it does not, please reopen.

**Comment by ymkaos** [comment]
Yep , worked.
my mistake, thanks
