### ISSUE TITLE
az ad app update command does not work for az cli version 2.0.49/2.0.50

### ISSUE THREAD

**Issue by sajithvasu** [Azure/azure-cli#7772]
az cli version 2.0.42 supports az ad app update command.. Post upgrade to any version of az cli does not support az ad app update. 

$ az ad app update --id $appId--reply-urls https://$hostname/.auth/login/aad/callback
Update to existing credential with KeyId '$keyid' is not allowed.

az ad app update --id $appId --set groupMembershipClaims=All
Property 'groupMembershipClaims' not found on root. Send it as an additional property .
Update to existing credential with KeyId '$keyid' is not allowed.

 az ad app update --id $appId --required-resource-accesses @manifest.json
Update to existing credential with KeyId '$keyid' is not allowed.

This scenario can be reproduced. It does not work on any az cli version after 2.0.42
To reproduce this scenario, create keys manually under Azure App Registration &gt; settings &gt; API &gt; keys and then run the app update command as shown above.

This is a major bug to use az cli for any update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 921aa920-c25f-5227-aabb-49116da38fa7
* Version Independent ID: 9b5a53ad-edf8-4d89-f8e6-cde01b7866f6
* Content: [az ad app](https://docs.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest#az-ad-app-update)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
dupe #7728
