### ISSUE TITLE
Support for Ubuntu Cosmic (18.10)

### ISSUE THREAD

**Issue by slim1688** [Azure/azure-cli#7776]
---

### Environment summary

I have tried to install azure-cli using apt by following the instruction from this webpage https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest and it failed. The error says azure-cli package not found.

**Comment by tjprescott** [comment]
Did you run `apt-get update` before? I did and then it had no problem finding the azure-cli package.

**Comment by slim1688** [comment]
I did run apt-get update and still did not work. I think the problem is in this address https://packages.microsoft.com/repos/azure-cli/dists/ it does not have cosmic. As you can see in below screenshot. Cosmic is codename for Ubuntu 18.10. It does have Bionic which is for Ubuntu 18.04 LTS version. Any idea when this Cosmic package will be available?

![image](https://user-images.githubusercontent.com/38484163/48239460-14473780-e423-11e8-858a-f4006e96689c.png)

**Comment by slim1688** [comment]
> Did you run `apt-get update` before? I did and then it had no problem finding the azure-cli package.

I did that few times and still did not work. See what I have found my comment and I guess that is the problem. The problem is there is no package created yet for cosmic (Ubuntu 18.10).

**Comment by tjprescott** [comment]
Hi @slim1688 we are hoping it will available with next week's release (azure-cli 2.0.51) otherwise it will be the release after that.

**Comment by tjprescott** [comment]
Azure CLI 2.0.51 has been released and should have Ubuntu Cosmic support. Please reopen if this is not the case.

**Comment by slim1688** [comment]
> 
> 
> Azure CLI 2.0.51 has been released and should have Ubuntu Cosmic support. Please reopen if this is not the case.

Thank you for this but I still did not see the cosmic folder/link on this url https://packages.microsoft.com/repos/azure-cli/dists/. I believe it won't work because the apt install is still referring cosmic to that url link.

**Comment by tjprescott** [comment]
Thanks @slim1688. The Cosmic build was created... we'll investigate why it didn't make it to the repo.

**Comment by tjprescott** [comment]
Hi @slim1688, please update your repo and try again. The cosmic folder is appearing in:
https://packages.microsoft.com/repos/azure-cli/dists/

**Comment by tjprescott** [comment]
I just verified that version 2.0.51 can be installed on Ubuntu Cosmic. Please note you may need to run `apt-get update` before installing.

**Comment by nicolaibaralmueller** [comment]
I can confirm that update is working again.
