### ISSUE TITLE
az acr helm push takes up to 5 mins to become visible

### ISSUE THREAD

**Issue by Xorima** [Azure/azure-cli#7777]
Hi,
When I upload a new package it can take 5 minutes for it to appear

## Process
Create and upload a package with `az acr helm push` 
run: `helm repo update`

## Expected Result
helm will list the new package

## Actual Result
helm does not list the new package

If I wait for a period of time and rerun `helm repo update` the package will show

Would it be possible for `az acr helm push` to only return after the chart has been fully uploaded and is available for use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bed94c3-b7a7-40d4-0102-8c9b1f1145ca
* Version Independent ID: 2d4ac8bd-dc7a-236c-56db-7f0e1ce0fd05
* Content: [az acr helm](https://docs.microsoft.com/en-us/cli/azure/acr/helm?view=azure-cli-latest#az-acr-helm-push)
* Content Source: [src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ehotinger** [comment]
@shizhMSFT @djyou @yuwaMSFT2

**Comment by scottzilla** [comment]
I don't see 5 minute delays, but it is not uncommon to see a delay of 1-2 minutes.

**Comment by yuwaMSFT2** [comment]
@scottzilla @Xorima are you registries geo-replicated?

**Comment by Xorima** [comment]
No they are not geo replicated

Even if it is common to see a delay of 1-2 mins my point still stands that it breaks scripts to do an upload, return success even though the chart is not actually available for my next step

**Comment by Xorima** [comment]
Will do when I'm back in work next week

**Comment by Xorima** [comment]
E-mail sent.

**Comment by Xorima** [comment]
KraterDev@microsoft.com
Remote Server returned '< #5.7.133 smtp;550 5.7.133 RESOLVER.RST.SenderNotAuthenticatedForGroup; authentication required; Delivery restriction check failed because the sender was not authenticated when sending to this group>'

**Comment by yuwaMSFT2** [comment]
@Xorima We got the information. Will investigate. Thanks!

**Comment by yuwaMSFT2** [comment]
This was mostly due to some cache effect. We are optimizing it and will deploy a fix soon.

**Comment by Xorima** [comment]
Can you let me know when this has been pushed out please and thank you @yuwaMSFT2

**Comment by yuwaMSFT2** [comment]
@Xorima Sure. Will have you updated once the fix is deployed.

**Comment by yugangw-msft** [comment]
Closing as the fix was deployed
