### ISSUE TITLE
Monitor autoscale examples

### ISSUE THREAD

**Issue by visokoo** [Azure/azure-cli#7779]
I hope this helps someone else since it can't be found on their official docs at all.

If you want to create a rule to autoscale via a guest vm metric enabled from diagnostic extensions, you have to use the `counterSpecifier` field from `az vmss diagnostics get-default-config`

Eg: az monitor autoscale rule create -g {rg} --autoscale-name test --condition "/builtin/memory/percentavailablememory &gt; 80 total 5m" --scale out 1

@MSFT, it would be really helpful to update this doc to reflect an example of that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25999d81-221d-052e-03b8-601585f71e3a
* Version Independent ID: ee988a97-bcf4-0ea2-9ab7-cd6af5e98237
* Content: [az monitor autoscale rule](https://docs.microsoft.com/en-us/cli/azure/monitor/autoscale/rule?view=azure-cli-latest#az-monitor-autoscale-rule-create)
* Content Source: [src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Where are you supplying the counter specifier in your command?

**Comment by visokoo** [comment]
Right after `--condition` in my example.

**Comment by tjprescott** [comment]
`/builtin/memory/percentavailablememory`?

**Comment by asheniam** [comment]
This is now possible with configuring guest metrics via Windows Azure Diagnostic (WAD) to custom metrics in Azure Monitor and setting up autoscale over these custom metrics.
https://azure.microsoft.com/en-us/blog/a-new-way-to-send-custom-metrics-to-azure-monitor/

We are looking at producing a doc for this scenario.

**Comment by davidbIQ** [comment]
The problem with the +/- percentage is it varies alot if it's scaled at 2 units or 10 units, it would be nice to allow for a mechanism to reflect this.  i.e. if my thing is at 13 machines I want it to downscale if both memory & cpu fall below 80%, but I don't want that to happen if it's at 2 machines, I would want that number to be closer to 40%.  similarly the converse is true for the scale up.  I guess it may be possible with a rule for each machine count if that's avail, I'll need to look...
