### ISSUE TITLE
Multiple credential caches

### ISSUE THREAD

**Issue by wsmckenz** [Azure/azure-cli#7781]
Is it possible to have multiple credential caches on a single machine for the same user. Our use case is to use azure cli on Azure DevOps build agents. We have 5 concurrent 'agent' processes run on each machine. The service principal used for each job is supplied by the job itself. Therefore, if we 'az login' for each job, they could tromp on each others credentials, default subscription, etc. 

Is this as simple as setting AZURE_CONFIG_DIR to point to the local directory of the build job, instead of ~/.azure?

**Comment by yugangw-msft** [comment]
Correct, you can just use `AZURE_CONFIG_DIR`.

**Comment by wsmckenz** [comment]
Thanks!
