### ISSUE TITLE
KeyVault swallows error when not logged in

### ISSUE THREAD

**Issue by julioct** [Azure/azure-cli#7783]
**Describe the bug**
Running az keyvault secret show --name <name> --vault-name <valuename> returns nothing on Windows.

**To Reproduce**
Run az keyvault secret show --name <name> --vault-name <valuename>

**Expected behavior**
Should show the secret

**Environment summary**
Install Method: MSI / CLI version 2.0.50 / Windows 10 1809 / Shell Type: cmd.exe  

**Additional context**
![annotation 2018-11-07 160019](https://user-images.githubusercontent.com/2374270/48168958-3f584c80-e2a6-11e8-8c71-c8f8f49ff85d.jpg)

**Comment by yugangw-msft** [comment]
It would be good to run with --debug and check out the response on payload

**Comment by julioct** [comment]
Interesting, using --debug revealed this (among other things):

``az keyvault secret show --vault-name mcr-test-global-kv --name McrflowApp-Password --debug``

**Suppress exception There are no active accounts.
Suppress exception Please run 'az login' to setup account.**  

And so, indeed, I had not done az login in this box yet. After login the command worked just fine.

Wish I got that additional bit when running without --debug.

**Comment by tjprescott** [comment]
Thanks @julioct you are right--the command should not swallow this error. I've updated the issue to reflect this bug.

**Comment by yugangw-msft** [comment]
I will take a look since it is also related with auth. This has been a common user confusion since 2017

**Comment by julioct** [comment]
Thanks for looking into this!
