### ISSUE TITLE
IoTCentral create command is not idempotent.

### ISSUE THREAD

**Issue by r-delgadillo** [Azure/azure-cli#7791]
**Describe the bug**
IotCentral create command is not idempotent. 

**To Reproduce**
Run same create command twice: 
`command`: az iotcentral app create --name myapp000 --subdomain myapp000 -g iOTC

`Response1`:
{
       "applicationId": "4cb23807-65c6-4bbd-a5a2-1636bb3b3bd3",
       "displayName": "myapp000",
       "etag": "\"02000b6a-0000-0000-0000-5be48bcb0000\"",
        "id": "/subscriptions/c75f6a44-0c50-4e42-b7ec- 
       9ff5590b0944/resourceGroups/iOTC/providers/Microsoft.IoTCentral/IoTApps/myapp000",
       "location": "westus",
       "name": "myapp000",
       "resourceGroup": "iOTC",
       "sku": {
         "name": "F1"
       },
       "subdomain": "myapp000",
       "tags": null,
       "template": "iotc-default@1.0.0",
       "type": "Microsoft.IoTCentral/IoTApps"
}

`Response2`:
Try other variations of the name

**Expected behavior**
Should update/replace existing application and return application properties on every response.

**Environment summary**
Any

**Comment by jlian** [comment]
IoT Central has a separate CLI than IoT Hub

**Comment by vilit1** [comment]
Closing the issue due to no response. If you still need help with this issue, please re-open.
