### ISSUE TITLE
IoT Hub Create is not idempotent

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#7792]
**Describe the bug**
CLI command guidelines require CREATE commands to be idempotent:
https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md

`iot hub create` has a client-side check for name availability that will cause the command to fail if run twice. This client-side check should be removed.

**To Reproduce**
Run `az iot hub create ...` twice with the same parameters. An error will be thrown.

**Expected behavior**
The second call should succeed.

**Comment by jlian** [comment]
@iluican is this a bug we can fix?

**Comment by iluican** [comment]
Not really.

**Comment by iluican** [comment]
We've had an extensive conversation about this in our team, and we don't feel like the existing behavior can be changed. Let's follow up offline, there is too much to discuss over a github issue.

**Comment by cocowalla** [comment]
Another vote for fixing this. Azure CLI tries to ensure all commands are idempotent, so why not this one?

**Comment by iluican** [comment]
@cocowalla Thank you for your comment. We will take another look and get back to you with our assessment.

**Comment by montgomp** [comment]
PR https://github.com/Azure/azure-cli/pull/13941
