### ISSUE TITLE
az login directed to localhost:8400

### ISSUE THREAD

**Issue by 08Alan** [Azure/azure-cli#7796]
I am using Az cli on my Mac
When using the az login command
MS login page will appear
The page will then be directed to `http://localhost:8400/?code=XXX&state=code&session_state=2c3aXXX`
Then there is no response.

my solution ： Use Device Code
`az login --use-device-code`

Environment：
macOS 10.14
Python 2.7.10
pip 10.0.1

**Comment by 08Alan** [comment]
Yes ! I used VPN when I login

**Comment by yugangw-msft** [comment]
It is dupe of #7227
