### ISSUE TITLE
test: bring back those disabled live storage blob tests

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#7798]
See #7797

**Comment by marstr** [comment]
Skimming over #7797, it seems like reducing the amount of space required by the tests would really amount to reducing how heavily parallelized they can be. 30GB is also not a huge memory footprint, so it seems forgivable to me that tests may assume they're executing in an environment with more storage available.

The next course of action will be to expand the storage available by adding a [Persistent Volume Claim](https://kubernetes.io/docs/concepts/storage/volumes/) to the pod definition of the test runner, and to update the location of the cached files to be in the mounted volume location.

**Comment by marstr** [comment]
To complete this, I had to also inject the TMPDIR environment variables to point to the mounted storage for test process.
