### ISSUE TITLE
Required Permissions

### ISSUE THREAD

**Issue by badalk** [Azure/azure-cli#7805]
What is the permission we need to have to push Helm charts into the repository. I am using a service principal? I have given ACRImagePusher but it doesnt work and gives a message saying authentication required

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bed94c3-b7a7-40d4-0102-8c9b1f1145ca
* Version Independent ID: 2d4ac8bd-dc7a-236c-56db-7f0e1ce0fd05
* Content: [az acr helm](https://docs.microsoft.com/en-us/cli/azure/acr/helm?view=azure-cli-latest#az-acr-helm-push)
* Content Source: [src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ehotinger** [comment]
@djyou @shizhMSFT @yuwaMSFT2 for Helm + auth.

**Comment by yugangw-msft** [comment]
Sorry the delay.
Based on the [doc](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-roles), ` AcrPush` should be sufficient. The key is whether you ran `az acr helm repo add -n <ACR-Name>` to initialize helm with required credentials so push would work through `az acr helm push`. Do check out the [e2e](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-helm-repos), which should help you.

**Comment by yugangw-msft** [comment]
Please reactivate if my comments have not addressed the question here
