### ISSUE TITLE
Deploy zip doesn't work

### ISSUE THREAD

**Issue by vgaltes** [Azure/azure-cli#7813]
**Describe the bug**
I'm trying to deploy a Function App using a zip file using the steps described below. When doing it, I'm getting the following error and the Function App is not being deployed:
```
'status'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 373, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 347, in execute
    result = cmd(params)
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 440, in default_command_handler
    result = op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 265, in enable_zip_deploy
    response = _check_zip_deployment_status(deployment_status_url, authorization)
  File "/usr/local/Cellar/azure-cli/2.0.50/libexec/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 1986, in _check_zip_deployment_status
    if res_dict['status'] == 5:
KeyError: 'status'
```
**To Reproduce**
Create a simple environment and function:
 - `func init (select dotnet)`
 - `func function new --languate C# --template "HTTP trigger" --name HelloWorld`
 - `az group create --name TestManualZipDeploy --location westeurope`
 - `az storage account create --name testmanualzipdeploysa --location westeurope --resource-group TestManualZipDeploy --sku Standard_LRS`
 - `az functionapp create --name TestManualZipDeploy --storage-account testmanualzipdeploysa --consumption-plan-location westeurope --resource-group TestManualZipDeploy`

If in this moment I use the command `func azure functionapp publish TestManualZipDeploy` the Function App gets deployed correctly, but want I want to do here is to deploy using a zip file. So, let's create the zip file and try to deploy:
 - `dotnet publish`
 - `pushd bin/Debug/netcoreapp2.1/publish`
 - `zip -r -X ../../../../functionapp.zip *`
 - `popd`
 - `az functionapp deployment source config-zip --resource-group TestManualZipDeploy --name TestManualZipDeploy --src functionapp.zip`

At this moment is when I get the error.

**Expected behavior**
I expect the Function App to be deployed correctly.

**Environment summary**
`az --version`: 
```
azure-cli (2.0.50)

acr (2.1.8)
acs (2.3.11)
advisor (2.0.0)
ams (0.3.0)
appservice (0.2.6)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.4)
billing (0.2.0)
botservice (0.1.1)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.3)
command-modules-nspkg (2.0.2)
configure (2.0.19)
consumption (0.4.0)
container (0.3.8)
core (2.0.50)
cosmosdb (0.2.3)
dla (0.2.3)
dls (0.1.4)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.1)
extension (0.2.3)
feedback (2.1.4)
find (0.2.12)
hdinsight (0.1.0)
interactive (0.4.0)
iot (0.3.4)
iotcentral (0.1.3)
keyvault (2.2.6)
lab (0.1.3)
maps (0.3.2)
monitor (0.2.6)
network (2.2.8)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.2)
rdbms (0.3.4)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.0)
resource (2.1.6)
role (2.1.9)
search (0.1.1)
servicebus (0.3.2)
servicefabric (0.1.7)
signalr (1.0.0)
sql (2.1.5)
storage (2.2.4)
telemetry (1.0.0)
vm (2.2.7)

Python location '/usr/local/opt/python/bin/python3.7'
Extensions directory '/Users/xxxx/.azure/cliextensions'

Python (Darwin) 3.7.1 (default, Nov  6 2018, 18:45:35)
[Clang 10.0.0 (clang-1000.11.45.5)]
```
OS Version: macOS High Sierra 10.13.3

**Additional context**
I've tried to stop the Funcion App, but I got the same error.

**Comment by ankitkumarr** [comment]
I wasn't able to reproduce the error in my Windows machine. But, I think the problem might be that for some reason the deployment hasn't started by the time we try to retrieve the status. So, the json received does not have a status key.

I will add a PR for what I think might be causing the error in your case.
