### ISSUE TITLE
Support for SemVer2 build metadata

### ISSUE THREAD

**Issue by sand32** [Azure/azure-cli#7814]
**Describe the bug**
Unable to push helm packages with build metadata (e.g. mypack-1.0.0+1.tgz).

`az acr helm push mypack-1.0.0+1.tgz` results in:
`ERROR: Invalid helm package name 'mypack-1.0.0+1.tgz'. Is it a '*.tgz' or '*.tgz.prov' file?`

**To Reproduce**
1. `helm package --version 1.0.0+1 charts/mypack`
1. `az acr helm push mypack-1.0.0+1.tgz`
1. Behold

**Expected behavior**
Should push successfully.

**Environment summary**
Helm v2.11.0
Azure CLI v2.0.49

**Additional context**
I'm able to push helm packages with either pre-release version data or with just the base MAJOR.MINOR.PATCH format, but not with build metadata.

Build metadata is valid SemVer2 as described here: [https://semver.org/#spec-item-10](https://semver.org/#spec-item-10)

**Comment by sand32** [comment]
Decided to do something about it: #7820

**Comment by lindhe** [comment]
I take this as ACR not supporting semantic versioning schemes. A bit strange to have Helm repo compatability without supporting the naming scheme that Helm uses... Or are there plans to fix this?

**Comment by avtakkar** [comment]
@djyou

**Comment by yugangw-msft** [comment]
@sand32 and @lindhe , with helm 3 around the corner, we don't plan for feature work for helm 2; rather we will consider this when we add support for helm 3.
Meanwhile, please keep on upvote this which would be a good data point for us to plan for helm3.
