### ISSUE TITLE
Add configurable timeout to az webapp deploy

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-cli#7823]
**Is your feature request related to a problem? Please describe.**
A long-running deployment may cause the command to exit too early. The deployment will continue in the background, but this does not work for automations where the deployment needs to have completed. The issue seems to be with https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py#L1974

**Describe the solution you'd like**
Add flags such as `--num_status_checks` and `--num_seconds_between_checks` to allow users to configure this window, keeping the default behavior as-is. Even better to just let someone specify the aggregate timeout window and dynamically calculate the number of checks required (keeping the 15s delay between). So then I could just say `--timeout 3600` or similar.

**Describe alternatives you've considered**
Scripting a loop on one's own, basically re-coding the `az webapp deploy` command. isAsync would be required due to an additional server-side timeout that is in place.

**Additional context**
N/A

**Comment by mattchenderson** [comment]
CC @panchagnula

**Comment by panchagnula** [comment]
@yugangw-msft , FYI - this is becoming a high pri issue on our end. planning to add --timeout as an optional parameter so that we can allow a customer to keep polling for longer.

**Comment by yugangw-msft** [comment]
Done through #7828
