### ISSUE TITLE
License files are in conflict

### ISSUE THREAD

**Issue by matt-richardson** [Azure/azure-cli#7825]
**Describe the bug**
There are 2 license files in this repo, [LICENSE.txt](https://github.com/Azure/azure-cli/blob/dev/LICENSE.txt) and [cli_license_terms.md](https://github.com/Azure/azure-cli/blob/dev/cli_license_terms.md), which appear to be in conflict.

**To Reproduce**
n/a

**Expected behaviour**
I'd expect one license, not 2.

**Environment summary**
n/a

**Additional context**
The readme says this is licensed under MIT, but the package includes `cli_license_terms.md`.

The included `cli_license_terms.md` file says this cannot be redistributed, but the MIT license says that it can.

Can you please clarify?

**Comment by yonzhan** [comment]
@jiasli add to S162.

**Comment by jiasli** [comment]
Hi @matt-richardson, The license for the Azure CLI project is MIT as set out at https://github.com/Azure/azure-cli/blob/dev/LICENSE. 

I have created a PR to remove the conflicting `cli_license_terms.md` license.

**Comment by matt-richardson** [comment]
Many thanks, @jiasli.

**Comment by jiasli** [comment]
You are mostly welcome. And thank you too for bring out this issue. 😄
