### ISSUE TITLE
keyvault secret download drops Exceptions ( e.g. open in non-existent directory )

### ISSUE THREAD

**Issue by donaldguy** [Azure/azure-cli#7844]
Attn: @yugangw-msft 

When performing an `az keyvault secret download` the exception chain is being terminated early without producing sufficient output for the user

**To Reproduce**
A reliable reproduction case is attempting a download with `-f` set to a path in a non-existent folder

In this case, https://github.com/Azure/azure-cli/blob/1fae61f241a067a583e93ec1f2cce5ece3b24c83/src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/custom.py#L709

(and presumably https://github.com/Azure/azure-cli/blob/1fae61f241a067a583e93ec1f2cce5ece3b24c83/src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/custom.py#L699 )

generates a `FileNotFoundError(2, 'No such file or directory')`

This is raised and caught again at https://github.com/Azure/azure-cli/blob/1fae61f241a067a583e93ec1f2cce5ece3b24c83/src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_command_type.py#L117-L125

This hits neither branch of https://github.com/Azure/azure-cli/blob/1fae61f241a067a583e93ec1f2cce5ece3b24c83/src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_command_type.py#L32-L46

And is summarily ignored 

**Expected behavior**
Some error message is printed, or a python stack trace for unhandled exception

**Experienced behavior**
silent failure

**Environment summary**
homebrew / azure-cli (2.0.43), Python (Darwin) 3.7.0 / macOS 10.14.1 (18B75) / zsh (but its not relevant)

**Additional context**

I would guess #7333 may be related. #7783 appears to be a similar instance, but the fix there is scoped too narrow for me

**Comment by yugangw-msft** [comment]
@donaldguy, thanks!
