### ISSUE TITLE
az dls fs list should support wildcard

### ISSUE THREAD

**Issue by oldmonk101** [Azure/azure-cli#7847]
We should be able to run commands with wildcards to recurse into subfolder level like -

```
az dls fs ls --path /path-to-dir/*/*.csv
```

**Comment by akharit** [comment]
There aren't any plans to support wildcards in subfolders as requested. That said it will be kept in the backlog and wait for more customer justification.

**Comment by tjprescott** [comment]
@akharit if your team has a user voice or something similar where you track customer feature requests (as opposed to bugs) we could transfer this to there.

**Comment by akharit** [comment]
Please close this issue. There aren't any plans to do this.

**Comment by sumantmehtams** [comment]
Closing after discussion with Akshat.

**Comment by Ture2019** [comment]
Yeah, prevent any usage value for the users. They suck!
