### ISSUE TITLE
az network vnet subnet update silently fails

### ISSUE THREAD

**Issue by N3rd007** [Azure/azure-cli#7848]
**Describe the bug**
When using the Azure CLI if a subnet does not exist, when using the command in the context below, and the subnet doesn't exist it fails silently.  

**To Reproduce**
Utilize the command as illustrated below, and you should see it proceed even if the subnet doesn't exist.  

**Expected behavior**
If a resource doesn't exist, it is expected that an error would be returned indicating that the subnet in question is null, or does not exist.  

**Environment summary**
This was produced using Susse Linux, in an architecture that leverages: 
AKS, Azure DNS, App Gateway, NGINX (for ingress controllers), and BASH.  

**Additional context**
When using Azure's CLI in the following manner:

["/bin/sh" "-c" "az network vnet subnet update -n cs-k8s-subnet-rd-multi-test-3eastus-mirror-mirror -g rd-multi-test-3eastus-mirror --vnet-name cs-k8s-vnet-rd-multi-test-3eastus-mirror-mirror --route-table $(az resource list --resource-group MC_rd-multi-test-3eastus-mirror_aks_cluster_backend-mirror_eastus --resource-type Microsoft.Network/routeTables --query '[].{ID:id}' -o tsv)"] 

If the subnet does not exist azure the Azure-CLI silently fails and presents a false positive: Executing: ["/bin/sh" "-c" "az network vnet subnet update -n cs-k8s-subnet-rd-multi-test-3eastus-mirror-mirror -g rd-multi-test-3eastus-mirror --vnet-name cs-k8s-vnet-rd-multi-test-3eastus-mirror-mirror --route-table $(az resource list --resource-group MC_rd-multi-test-3eastus-mirror_aks_cluster_backend-mirror_eastus --resource-type Microsoft.Network/routeTables --query '[].{ID:id}' -o tsv)"] --  when the subnet is not created the command seems to pass without a failure.

**Comment by tjprescott** [comment]
What version of the CLI are you using?  I just tried this on a non-existent subnet and got the expected error message.
```
Resource /subscriptions/xxxx/resourceGroups/tjp-rg/providers/Microsoft.Network/virtualNetworks/vnet1/subnets/subnet1 not found.
```

**Comment by tjprescott** [comment]
Closing as the commands performs as expected for a non-existent subnet.
