### ISSUE TITLE
[Network] `az vm nic` commands should combine '--nic-names' and '--nic-ids' into '--nics'

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#785]
There are many many places in the CLI that accept a name or ID as a parameter. We don't use the Xplat convention of exposing `foo-name` and `foo-id`. Instead we expose `foo: Name or ID of the foo.` Similarly, we should simply expose `--nics` and have the validation convert any names into valid IDs.

**Comment by johanste** [comment]
Reasonable suggestion. The one thing I’d like to point out is that it can make statement/tab completion more cumbersome to implement correctly/make useful.

**Comment by tjprescott** [comment]
@johanste I believe that currently we do tab-completion on the name only. I don't know of anywhere we currently have tab completion on whole IDs.
