### ISSUE TITLE
Incorrect example for "update" command

### ISSUE THREAD

**Issue by StanProkhorov-MSFT** [Azure/azure-cli#7852]
https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/url-path-map?view=azure-cli-latest#examples

Incorrect example, "--http-settings" is not a valid argument for "az network application-gateway url-path-map update". Following error is being received: 
az: error: unrecognized arguments: --http-settings 

Correct syntax should be:

az network application-gateway url-path-map update \
    --resource-group MyResourceGroup \
    --gateway-name MyAppGateway \
    --name MyUrlPathMap \
    --default-http-settings MyNewHttpSettings \
    --set pathRules[0].backendHttpSettings.id="/subscriptions/MySubscriptionId/resourceGroups/MyResourceGroup/providers/Microsoft.Network/applicationGateways/MyAppGateway/backendHttpSettingsCollection/MyNewHttpSettings"
    
Where index "0" in "pathRules[0]" can be different depending on the rule number to be updated. 

Also, it would be good to have a better example for use of "--set" argument.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a78e7c17-0704-a61d-5c46-b776afb980c0
* Version Independent ID: 95009d9f-e65d-7659-b02c-1993a47048ef
* Content: [az network application-gateway url-path-map](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/url-path-map?view=azure-cli-latest#az-network-application-gateway-url-path-map-update)
* Content Source: [src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Thank you for the report @StanProkhorov-MSFT. The incorrect example was fixed by @adewaleo's recent PR.
