### ISSUE TITLE
Azure cli 2.0 Blob upload slower than old azure cli

### ISSUE THREAD

**Issue by arowleslawson** [Azure/azure-cli#7857]
When uploading a file to a blob (from an Azure Ubuntu 18.04 box) using Azure cli. It is significantly slower with the new Azure-cli 2.0 than with the old version of Azure cli. To upload a 250GB image using the old Azure it takes 30-40mins but with the new Azure cli it takes 2.5-3 hours. It seems like this should be the other way around.

**Old Azure version 0.10.20**
Command: `azure storage blob upload  --file {file} --account-name {storage}  --account-key {key} --container {container} --blob {blob}  --blobtype page`

Time to complete: 30-40 mins 

**New Azure version 2.0.50**
Command: `az storage blob upload --account-key {key} --account-name {storage} -c {container} -f {file_path} -n {image} -t page`

Time to complete: 2.5-3 hours 

I would expect that the newer version of Azure-cli would be at least as fast if not faster, not _so_ much slower

**Old Azure version 0.10.20**
Installed using NPM 
    sudo apt-get update
    sudo apt-get install -y npm
    sudo npm install azure-cli -g
    sudo reboot

**New Azure version 2.0.50**
Installed using apt-get
AZ_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | \
    sudo tee /etc/apt/sources.list.d/azure-cli.list
curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
sudo apt-get update
sudo apt-get install libssl-dev libffi-dev python-dev apt-transport-https azure-cli

Ubuntu box used for testing (Standard F4 (4 vcpus, 8 GB memory)) version 18.04.1

**Comment by chubin** [comment]
Yes, it is extremely slow. In my case it is even slower than the old `azure` client,
because I've optimized it and it was possible to upload files with 50% speed boost.
That means almost 10 times faster than with the new client (`at storage blob`).

The new tools are *extremely* slow.

**Comment by chubin** [comment]
I've tried to use `azopy` as the guys recommended me here:

https://www.reddit.com/r/AZURE/comments/ajeppa/extremely_slow_azure_blob_upload/

and it is much better indeed. It took 6 minutes to upload a 120GB file,
comparing to circa 420 minutes by the azure tools (`az`).
So use `azcopy`, it is 70 times faster for big files.

I also noticed that `az` permorms extremely slowly when uploading the end of the file.
Probably it is because of some bug in `seek` implementation there (or something of the sort).

**Comment by arowleslawson** [comment]
@chubin Ill have to try azcopy! Thanks for the advice

**Comment by tjprescott** [comment]
@williexu does the storage-preview extension help address any of this?

**Comment by williexu** [comment]
The `storage-preview` extension will be integrating with azcopy soon :), it is currently under development.

**Comment by limingu** [comment]
The work item is created: https://github.com/Azure/azure-cli/issues/9794

az storage CLI will use Azcopy to copy/upload/download the blobs. The performance will be much better.

**Comment by Juliehzl** [comment]
@arowleslawson you can upload using `az storage copy` in azure cli 2.0.71 and wait for your feedback.

**Comment by yonzhan** [comment]
add to S164.

**Comment by Juliehzl** [comment]
Given no response, I will close this issue now. please try `az storage copy` command with latest azure cli and if you still have problem, feel free to create a new issue.
