### ISSUE TITLE
Reevaluate storage types supported for Function App creation

### ISSUE THREAD

**Issue by dariagrigoriu** [Azure/azure-cli#7861]
Reevaluate the storage account types supported for Function App creation. The storage types must support features like queues and blob $logs in order to interface properly with the Functions runtime.

CLI command: az functionapp create

Storage types requested: including but not limited to RAGRS

Code: https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py#L1920

**Comment by ahmedelnably** [comment]
Dupe of https://github.com/Azure/azure-cli/issues/9840
PR is already out. Closing this
