### ISSUE TITLE
az storage container generate-sas support for --FullUri option

### ISSUE THREAD

**Issue by jochenvanwylick** [Azure/azure-cli#7865]
I'm porting a PowerShell script to Azure CLI and I've noticed that PowerShell supports a '-FullUri' option that returns the full URI of the SAS token: [https://docs.microsoft.com/en-us/powershell/module/azure.storage/new-azurestorageblobsastoken?view=azurermps-6.12.0](https://docs.microsoft.com/en-us/powershell/module/azure.storage/new-azurestorageblobsastoken?view=azurermps-6.12.0)

Here's the syntax:

```PowerShell
New-AzureStorageBlobSASToken
   [-Container] <String>
   [-Blob] <String>
   [-Permission <String>]
   [-Protocol <SharedAccessProtocol>]
   [-IPAddressOrRange <String>]
   [-StartTime <DateTime>]
   [-ExpiryTime <DateTime>]
   [-FullUri] <<-- Here's the option
   [-Context <IStorageContext>]
   [-DefaultProfile <IAzureContextContainer>]
   [<CommonParameters>]
```

However - the CLI does not support this option:

```bash
az storage container generate-sas --name
                                  [--account-key]
                                  [--account-name]
                                  [--auth-mode {key, login}]
                                  [--cache-control]
                                  [--connection-string]
                                  [--content-disposition]
                                  [--content-encoding]
                                  [--content-language]
                                  [--content-type]
                                  [--expiry]
                                  [--https-only]
                                  [--ip]
                                  [--permissions]
                                  [--policy-name]
                                  [--sas-token]
                                  [--start]
```
Source: [https://docs.microsoft.com/en-us/cli/azure/storage/container?view=azure-cli-latest#az-storage-container-generate-sas](https://docs.microsoft.com/en-us/cli/azure/storage/container?view=azure-cli-latest#az-storage-container-generate-sas)

I would love support for this flag - it saves me combining the container URI with the SAS token myself.

**Comment by tjprescott** [comment]
@williexu, do you have any suggestions for this?

**Comment by williexu** [comment]
We can implement this, though this is low-pri. Right now as a workaround, of course, one can simply append the sas token to the uri.
