### ISSUE TITLE
 Application Gateway support for new feature - Header CRUD

### ISSUE THREAD

**Issue by sai-manoj-kumar** [Azure/azure-cli#7867]
**Is your feature request related to a problem? Please describe.**
CLI needs to be updated according to the NRP and swagger changes.
A new property RewriteRuleSets is added in the applicationGateway resource.
It is referenced in the RequestRoutingRule and UrlPathMap.

**Describe the solution you'd like**
Need CLI to be written as per the [swagger changes here](https://github.com/Azure/azure-rest-api-specs/pull/4331).

**Comment by tjprescott** [comment]
Moving to the backlog due to service limitations.

**Comment by sai-manoj-kumar** [comment]
@tjprescott Can you elaborate on what is the limitation?

**Comment by tjprescott** [comment]
Closing in favor or newer issue: #8428.
