### ISSUE TITLE
az vm identity remove

### ISSUE THREAD

**Issue by littleddpig** [Azure/azure-cli#7872]
it seems like to use the command for the parameter --identities need to be full path, not just the MSI name
try to delete MSI ID1:
az vm identity remove -g VM -n MSIVM --identities readerId ID1
'/subscriptions/.../resourcegroups/vm/providers/microsoft.managedidentity/userassignedidentities/id2' are not associated with 'MSIVM'

az vm identity remove -g VM -n MSIVM --identities /subscriptions/.../resourcegroups/myResourceGroupVM/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ID1
 - Running ..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de241c0d-7295-bf01-a431-3c94a02c099b
* Version Independent ID: 780195c5-fc93-ee0d-e5e5-8f62f4dee6ee
* Content: [az vm identity](https://docs.microsoft.com/en-us/cli/azure/vm/identity?view=azure-cli-latest#az-vm-identity-remove)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
@adewaleo, let us fix this

**Comment by adewaleo** [comment]
@littleddpig. The CLI uses a `name or ID` pattern for certain parameter values. However, if the parameter is the name of a resource, it must be a resource in the resource group (specified by --resource-group / -g) of the executed command.  So to refer to a managed identity that belongs in a different resource group that the specified resource group, you would need to specify the full resource ID of the managed identity. 

To solve your issue without explicitly copying and pasting the MSI, you can do the following:

```
READER_ID=$(az identity show -n readerid -g my-id-group --query "id" -o tsv )
az vm identity remove  -n MSIVM -g my-vm-group --identities $READER_ID
```

I hope this helps. Let us know if you have any more questions.
