### ISSUE TITLE
Get Dynamic VM states

### ISSUE THREAD

**Issue by nicolaibaralmueller** [Azure/azure-cli#7875]
I need to get all VM states, regardless of state dynamically (without knowing VM name and resource group). How can the below working Powershell script be achieved with azure cli? Thanks

$FindVMs = Get-AzureRmResource | where {$_.ResourceType -like "Microsoft.Compute/virtualMachines"}
  
$out = @()
  
Foreach ($vm in $Findvms)
{
    $Name = $VM.Name
    $ResourceId = $VM.ResourceId
    $ResourceGroupName = $VM.ResourceGroupName
    $Location = $VM.Location
  
    $VMDetail = Get-AzureRmVM -ResourceGroupName $VM.ResourceGroupName -Name $VM.Name -Status

    $props = @{
        VMName = $VM.Name
        ResourceGroup = $VM.ResourceGroupName
        Location = $VM.Location
        PowerState = $VMDetail.Statuses[1].DisplayStatus
    }
    
    $out += New-Object PsObject -Property $props
}

$out | Format-Table -AutoSize -Wrap  ResourceGroup, Location, VMName,Powerstate

$out | ConvertTo-Json

**Comment by yugangw-msft** [comment]
`az vm list -g MCCANCEL01 -d --query "[].{resourceGroup:resourceGroup, location:location, name:name, PowerState:powerState}"` should do it for you

**Comment by nicolaibaralmueller** [comment]
> `az vm list -g myRG -d --query "[].{resourceGroup:resourceGroup, location:location, name:name, PowerState:powerState}"` should do it for you

@yugangw-msft Above command expects resource group. What if I just need all VM states from all resource groups within a subscription.
