### ISSUE TITLE
How to create new azure Oauth connection using REST API? 

### ISSUE THREAD

**Issue by utkarsh24** [Azure/azure-cli#7876]
I want to create dynamically new Oauth connection using Rest API.
currently i am using
https://management.azure.com/subscriptions/subscriptionId/resourceGroups/resourceGroupName/providers/Microsoft.BotService/botservices/botName/Connections?api-version=2017-12-01

I get following error

{
"error": {
"code": "InvalidRequestMethodForResourceCollectionRequest",
"message": "The request method 'POST' is invalid for the resource collection request https://management.azure.com/subscriptions/subscriptionId/resourceGroups/resourceGroupName/providers/Microsoft.BotService/botservices/botName/Connections?api-version=2017-12-01'. Only GET requests are supported for resource collection requests."
}
}

What is the api-version to create Oauth connection using REST?
Could you please provide sample code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c910113e-ccf1-6c81-400c-40d2e00c09d7
* Version Independent ID: e9baac80-b846-074c-dc34-c68f5313e19b
* Content: [az bot authsetting](https://docs.microsoft.com/en-us/cli/azure/bot/authsetting?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/_help.py)
* Service: **bot-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by utkarsh24** [comment]
@yugangw-msft Any updates..

**Comment by tjprescott** [comment]
@swagatmishra2007 for comment.

**Comment by carlosscastro** [comment]
Hello! Seems like you are not using the AZ-cLI but the ARM api directly. Refer to the API spec, here I send a link specifically to the API verb to create a new OAuth connection.

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/botservice/resource-manager/Microsoft.BotService/preview/2018-07-12/botservice.json#L767

As shown in the link I sent, to create an OAuth connection you need to use the HTTP verb PUT. See the parameters in the swagger.

**Comment by tjprescott** [comment]
Since this is not related to the CLI commands for botservice, I am closing this issue.

**Comment by utkarsh24** [comment]
Thanks @tjprescott for your help, yes I am using ARM api directly.
