### ISSUE TITLE
Introduce yamlc output format

### ISSUE THREAD

**Issue by richeney** [Azure/azure-cli#7878]
Adding yaml as an output option is great - thank you.  (My default has been jsonc for a long time.)

Is there a possibility to have a yamlc option with the same colorizing as jsonc?

**Comment by yonzhan** [comment]
@jiasli add to S162.

**Comment by jiasli** [comment]
`YamlLexer` is already supported: https://pygments.org/docs/lexers/#pygments.lexers.data.YamlLexer. 

Moving to Knack

**Comment by jiasli** [comment]
`YamlLexer` is already supported: https://pygments.org/docs/lexers/#pygments.lexers.data.YamlLexer

I will create PR to support `yamlc`.
