### ISSUE TITLE
[webapp] - App Service support high density per-app scaling

### ISSUE THREAD

**Issue by markheath** [Azure/azure-cli#7888]
It doesn't seem that the `az appservice plan create` command offers support to enable the "high density" "PerSiteScaling" feature described [here](https://docs.microsoft.com/en-us/azure/app-service/app-service-high-density-hosting)

It would be great if this support could be added. It would also necessary to support setting the number of workers on a web app basis (perhaps with `az webapp config set`)

**Comment by panchagnula** [comment]
Work around for now would be to use PowerShell command for this https://docs.microsoft.com/en-us/azure/app-service/manage-scale-per-app

**Comment by panchagnula** [comment]
For CLI we support --set on the Appservice plan update which takes the propertyname=Value, you can also pass it a path to a json object file as @myJson.json & we will update the ASP settings. We will work on exposing this parameter on ASP create

On the webapp config set you can follow the same pattern & use the  --generic-configurations CLI property to set the numbers of workers

**Comment by panchagnula** [comment]
Moving this out to the next sprint
