### ISSUE TITLE
[Create] VM and VMSS create should have image as a required param

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#789]
Feedback from the AzLinux teams pointed out that having a default for this field biases Az against Linux VMs.  We should simply require the image to be selected (which is commonly overridden anyway) so all images have an equal opportunity to be selected.

**Comment by BurtBiel** [comment]
@ahmetalpbalkan

**Comment by BurtBiel** [comment]
Related to #586

**Comment by yugangw-msft** [comment]
Agreed. 
The Image is the most important aspect for a VM, hence I never mind providing it explicitly.
