### ISSUE TITLE
What are the options to vm create --size?

### ISSUE THREAD

**Issue by Luo-Liang** [Azure/azure-cli#7893]
What are the string options? The link just shows the name, not what I need to pass to the CLI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 152b549b-d4b3-13e5-081c-c604b6e4d89e
* Version Independent ID: 3f79be78-ce75-ad31-304b-bad7d475ec9e
* Content: [az vm](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by adewaleo** [comment]
@Luo-Liang 

The help text for `az vm create --size` on the online docs says:

"The VM size to be created. See [https://azure.microsoft.com/en-us/pricing/details/virtual-machines/](https://azure.microsoft.com/en-us/pricing/details/virtual-machines/) for size info. default value: Standard_DS1_v2"

To get a list of vm sizes, run:
```
az vm list-sizes -l "westus" 
```

You might find using the `--output table` option helpful.
