### ISSUE TITLE
Very slow import at startup

### ISSUE THREAD

**Issue by zooba** [Azure/azure-cli#7897]
The line at https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/_profile.py#L16 makes startup time considerably slower on Windows as it triggers a full enumeration of `HKEY_CLASSES_ROOT`.

```python
from six.moves import BaseHTTPServer
```

It appears that the import is only required for the authorization flow, which means it can probably move to a module that is only imported when needed. This should improve startup time noticeably.

(I've also filed https://bugs.python.org/issue35292 to fix the underlying cause in CPython, but I doubt that will show up before 3.8.)

**Comment by tjprescott** [comment]
Thanks for pointing this out. We'll relocate it and see if it improves load times.

**Comment by tjprescott** [comment]
Average module load times (20 runs)
before relocation: 588
after relocation: 582

Relocating the import doesn't produce a noticeable change in Windows load times. It may be that many other modules are already importing from `six.moves`. Closing this issue.
