### ISSUE TITLE
[VM/VMSS] Create Appears to Hang After "Admin Password" Prompt

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#790]
I tried creating a VM scale set with minimal parameters using:

`az vmss create -g myrg -n vmss1`

It prompted me for an admin password. Once I entered it, I was expecting it to confirm my password (because basically every password prompt in existence does so) and instead it just hung. I eventually used Ctrl+C to break out of the process.

I tried it again and got a "change property 'adminPassword' is not allowed" which suggested that it in fact succeeded. Looking in the portal this was indeed that case.

Apparently, after I entered my password, while I was expecting to have to re-enter the password it started the long running operation and I assumed it had hung.

I would recommend adding the password confirmation logic and adding the "Starting vmss create..." blurb to avoid confusion.

**Comment by derekbekoe** [comment]
In PR #767, we removed the long running operation start messages.

For this particular case, if the user entered the password interactively, we could print a message to logger.warning() stating that the vm is being created.

**Comment by tjprescott** [comment]
Related to issue #987

**Comment by yugangw-msft** [comment]
We will add a warning for this particular scenario

**Comment by tjprescott** [comment]
I would actually expect it to reconfirm the password input, especially since you can't see it. That would also clue me in that it hadn't just frozen.

**Comment by tjprescott** [comment]
This has been fixed in #1849
