### ISSUE TITLE
Azure CLI, DNS: An Upper.Case zone name is concatenated to the record name, causing duplication

### ISSUE THREAD

**Issue by zvargams** [Azure/azure-cli#7907]
**Describe the bug**
When the Azure CLI DNS import command is called with a zone name containing Upper.Case.Letters, then the zone name is concatenated to the record name, causing duplication.

**To Reproduce**
Import a zone with:

`az network dns zone import --resource-group xxx --name Test.Zone `

will import / create the following records:

```
(1/27) Imported 1 records of type 'soa' and name 'test.zone'
(2/27) Imported 1 records of type 'a' and name 'test.zone'
(3/27) Imported 1 records of type 'mx' and name 'test.zone'
(8/27) Imported 5 records of type 'txt' and name 'test.zone'
(9/27) Imported 1 records of type 'cname' and name '*.test.zone' 

```
while with all lower case:

`az network dns zone import --resource-group xxx --name test.one `

does import it properly:

```
(1/27) Imported 1 records of type 'soa' and name '@'
(2/27) Imported 1 records of type 'a' and name '@'
(3/27) Imported 1 records of type 'mx' and name '@'
(8/27) Imported 5 records of type 'txt' and name '@'
(9/27) Imported 1 records of type 'cname' and name '*'

```

**Expected behavior**
DNS is case insensitive, therefore having upper or lower case letters in the zone name should not lead to different behaviors / results.

**Environment summary**
Windows 10

az --version
azure-cli (2.0.28)

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

**Comment by muwaqar** [comment]
Please assign to @karravi-msft.

**Comment by MyronFanQiu** [comment]
@karravi-msft Hello. Any update?

**Comment by yonzhan** [comment]
add to S164.

**Comment by MyronFanQiu** [comment]
@zvargams Thanks for this issue. I think your suggestion should be right. However, there are existing users using this command. This would be a breaking change for them. So I added warning information first and open another issue to track it. This would be fixed months later. Thanks.
