### ISSUE TITLE
.net core 2.1(Web API) and angular 6 project on azure server giving error : 500 - The request timed out.The web server failed to respond within the specified time.

### ISSUE THREAD

**Issue by gauravthakur321** [Azure/azure-cli#7908]
I uploaded .net core 2.1(Web API) and angular 6 project on azure but when I am uploading a CSV file data then It is showing to me an error in response that is Error: **The specified CGI application encountered an error and the server terminated the process.**  

I checked it on internet and applied some change for this error according to this post.
**https://www.michaelcrump.net/azure-tips-and-tricks132/**

But now again it is showing to me error which is 

![image](https://user-images.githubusercontent.com/41986628/48929341-ef1bf400-ef0d-11e8-9eda-6de6680538ba.png)
![image](https://user-images.githubusercontent.com/41986628/48929355-01962d80-ef0e-11e8-854f-b12366a4a549.png)

The same projects are running on other server(window server 2008 R2 standard  64 BIt) and it is  uploading data  and showing 200 in response .

Please help me that how I can solve this issue.

**Comment by tjprescott** [comment]
What specific CLI command are you trying to use that isn't working?

**Comment by gauravthakur321** [comment]
Thanks for reply but Now it is resolved.
