### ISSUE TITLE
--location name formatting

### ISSUE THREAD

**Issue by pjdv2** [Azure/azure-cli#7911]
It may seem straightforward, "westus" and "West US", but initially I actually wasn't sure what to use, being from a different location; it may be helpful to put a note on the location-name-formatting. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58c81c4d-10d2-fc04-e707-fcf914f4d540
* Version Independent ID: 8598f788-bd33-a4c8-ed66-593e0fde75d5
* Content: [az group](https://docs.microsoft.com/en-us/cli/azure/group?view=azure-cli-latest#az-group-create)
* Content Source: [src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Either one should be accepted. You will just need to quote the long form with the space. Tab completion defaults to the short-form.

**Comment by tjprescott** [comment]
Tab completion works out of the box on Azure Cloud Shell and other variants of the bash shell (not CMD.exe or Powershell). 

<img width="1125" alt="screen shot 2018-11-26 at 8 37 37 am" src="https://user-images.githubusercontent.com/5723682/49028165-9723fe00-f156-11e8-94ad-015dbed3909d.png">

**Comment by tjprescott** [comment]
You get this by typing `-l [Tab][Tab]`

**Comment by pjdv2** [comment]
> You get this by typing `-l [Tab][Tab]`

Nice. The space can be a bit tricky though, right after the parameter ;).

**Comment by tjprescott** [comment]
We'll consider adding clarifying language to the `--location` parameter, since it is used almost universally throughout the CLI.

**Comment by pjdv2** [comment]
Thanks.

**Comment by tjprescott** [comment]
We'll add the reference to the `az account list-locations` command to the global help for this parameter.

**Comment by adewaleo** [comment]
see #7951
