### ISSUE TITLE
az network vnet create is not idempotent

### ISSUE THREAD

**Issue by pascalnaber** [Azure/azure-cli#7912]
**Describe the bug**
running the second time results in an output status of 1, first time it's 0.
so second time it fails.

**To Reproduce**
Execute the following twice:
az network vnet create -g $RESOURCEGROUP_VNET_NAME -n $VNET_NAME --address-prefix 10.0.0.0/8 -l $LOCATION

echo status: $?

az network vnet subnet create -g $RESOURCEGROUP_VNET_NAME --vnet-name $VNET_NAME -n aks-subnet --address-prefix 10.240.0.0/16

executing the first command results the second time in:
Subnet aks-subnet is in use by /subscriptions/xxxxxx/resourceGroups/playground-rg/providers/Microsoft.Network/networkInterfaces/xxxxx/ipConfigurations/ipconfig1 and cannot be deleted.

**Expected behavior**
Twice exactly the same behavior and result status of 0. Second time it just already exists.

**Comment by tjprescott** [comment]
I just tried your repo steps and it worked without issue. The second call to `vnet create` wipes away the subnet, but that is the expected behavior.

From the error message it seems like after creating the subnet but before you tried to run `vnet create` again, you associated that subnet with a network interface. This might be due to a call to `vm create` which, if a vnet is not specified, looks for a vnet in the resource group and uses that.

**Comment by pascalnaber** [comment]
Hmm. You are correct about my repo steps. I will have a second look what is happening exactly in my situation.

Are you serious about the wiping of the subnet? My opinion would be that it is not allowed to delete  subnets. The commands asks to create the vnet. If the vnet exists already, it should leave it as is. Why is it expected that the command deletes subnets?

**Comment by tjprescott** [comment]
Nearly all `create` commands in the CLI are PUT requests. If you make a PUT request for a resource that already exists, you overwrite it. `vnet create` certainly follows this pattern. Doing an existence check would result in the command not being idempotent because the second call would fail.

**Comment by corveen** [comment]
This is confusing. "az webapp create" is not a PUT command becuase it gives this error:

az : ERROR: The site with name testsite already exists in resource group testrg.

So I have to do existence check myself.
Can someone explain why some commands work different than others?

**Comment by tjprescott** [comment]
@corveen the issue with `webapp create` was someone inserted validation logic that broke the idempotency of the command. That has been fixed and will be in the next release.
