### ISSUE TITLE
invalid choice: action-group

### ISSUE THREAD

**Issue by hoangpx** [Azure/azure-cli#7915]
Azure CLI on Macos Mojave. 

brew update && brew upgrade azure-cli
Already up-to-date.
Error: azure-cli 2.0.51 already installed

az monitor action-group
az monitor: error: argument subcommand: invalid choice: action-group
usage: az monitor [-h]
                  {autoscale-settings,activity-log,log-profiles,alert,diagnostic-settings,metrics}

**Comment by tjprescott** [comment]
My suggestion is to first run `brew uninstall azure-cli`. Then run `az --version` and verify it _doesn't work_. Then run `brew install azure-cli` and see if it works. From the looks of things, you may have an old version of the CLI installed through some other installation mechanism.

**Comment by hoangpx** [comment]
I believed I installed az using pip. `az --version` did the trick. I reinstalled then everything worked. Thanks.
