### ISSUE TITLE
What do we should use "az ad app permission grant"?

### ISSUE THREAD

**Issue by WayneYangsa** [Azure/azure-cli#7925]
In this doc, it shows that "--api" and "--id" are required. However, in the example, it use this "az ad app permission grant --id e042ec79-34cd-498f-9d9f-1234234 --app-id a0322f79-57df-498f-9d9f-12678 --expires 2". May I know what's this? It really sucks!

Even I change the the way to use it, it still not works!! How can I grant permission with this command?????????

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a5b5348-f67e-ef14-0529-4c80fddd4bc6
* Version Independent ID: bfd7e6b1-1fba-3d25-8ee3-5105bcf4157d
* Content: [az ad app permission](https://docs.microsoft.com/en-us/cli/azure/ad/app/permission?view=azure-cli-latest#az-ad-app-permission-grant)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
sample uses the wrong flag, and i will change `--app-id` to `--api`. At the same time, you do realize the sample uses faked app id, and you need to replace with the real work api id

**Comment by WayneYangsa** [comment]
> sample uses the wrong flag, and i will change `--app-id` to `--api`. At the same time, you do realize the sample uses faked app id, and you need to replace with the real work api id

Um.. So, may i know if there is any update? It has taken 19 days you replied.

**Comment by yugangw-msft** [comment]
@WayneYangsa, thanks for the reminder. PR was submitted. FYI, we have an engineering work item on board which will automatically flag out those wrong examples moving forward.

**Comment by nikoudel** [comment]
Hello!

The example tells to use guid `311a71cc-e848-46a1-bdf8-97ff7156d8e6` to add the "Sign in and read user profile" permission:

`az ad app permission add --id eeba0b46-78e5-4a1a-a1aa-cafe6c123456 --api 00000002-0000-0000-c000-000000000000 --api-permissions 311a71cc-e848-46a1-bdf8-97ff7156d8e6=Scope`

But what if I need to add the "Read all groups" permission for example... how and where to find the guid?

**Comment by jwoehrle** [comment]
I would actually like to grant the `Policy.ReadWrite.TrustFramework` ... how do I find the ID of this permission?

**Comment by yugangw-msft** [comment]
The best way is to configure it through portal, and then there is a button called "Manifest" that you can use to see the id:
![image](https://user-images.githubusercontent.com/6014209/58107587-04ad6600-7b9f-11e9-881e-9b8620f15d76.png)

**Comment by davidtom** [comment]
I'm still a bit confused here. From what I can tell, in order to grant a new permission to an app I need the following details:
- app id (--id)
- api id (--api)
- api permission id (--api-permissions)

Getting the app id seems straightforward, but not the other two. When I open my manifest (after adding a permission), it looks like the api id (from `requiredResourcesAccess[0].resourceAppId`) is `00000003-0000-0000-c000-000000000000`? Is this something that changes based on the app/subscription/tenant or is it a constant?

This same question applies for the api permission id. I have given my app `Application.ReadWrite.All` permission, which appears to map to id `1bfefb4e-e0b5-418b-a88f-73c46d2cc8e9` in the manifest (located at `requiredResourcesAccess[0].resourceAccess[0].id`). If this is true, does that id always map to that permission across all of Azure?

Finally, based on all of this it would seem that the only way to programmatically do any of this, which is ultimately my goal, first requires one to set things up in the portal, pull the data from the manifest, then use that data to do any additional work programmatically. And all of this is only true if the ids above are constant across all of Azure. Is this the case? Is there someplace where a list of permission ids can be found? Surely there is a better way to do all of this??

**Comment by yugangw-msft** [comment]
> And all of this is only true if the ids above are constant across all of Azure. Is this the case? 

Yes

  > Is there someplace where a list of permission ids can be found

I don't think so. Still the the same approach that you configure a sample one through portal and check out the manifests.

**Comment by ericchansen** [comment]
If possible, I think this issue was never addressed. There should be a programmatic way to do this that doesn't require the portal. In my client's use case, it isn't possible to use the portal to access the manifest. These permissions must be given entirely from the command line. We can't do an example of adding it to the portal, checking the manifest and then using the values in the manifest to write the code.

**Comment by jannikbuschke** [comment]
**Im currently also facing issues with adding permissions via azure cli.
A solution that requires clicking in a portal is not at all how software releases should be done today.**

In my specific case I execute 
`az ad app permission add --id <app-id> --api 00000002-0000-0000-c000-000000000000 --api-permissions 311a71cc-e848-46a1-bdf8-97ff7156d8e6=Scope`
 
CLI responds:
`Invoking "az ad app permission grant --id <app-id> --api 00000002-0000-0000-c000-000000000000" is needed to make the change effective`

Executing `az ad app permission grant --id <app-id> --api 00000002-0000-0000-c000-000000000000` then results in
`Operation failed with status: 'Not Found'. Details: 404 Client Error: Not Found for url: https://graph.windows.net/<app-id>/oauth2PermissionGrants?$filter=clientId%20eq%20%<some-id>&api-version=1.6`

**Comment by jwoehrle** [comment]
> **Im currently also facing issues with adding permissions via azure cli. A solution that requires clicking in a portal is not at all how software releases should be done today.**

I couldn't agree more... Hope this gets added soon... how are you supposed to script anything with this approach and do any infrastructure as code?

**Comment by jannikbuschke** [comment]
@davidtom **the ids for permissions as well as apis are the same in each tenant** (as of today, this might change in the future). However so far I have not found any official document about this. So you should be careful.

There are some blogposts about these values, but nothing really that suites the importance of this topic.

As of today I would also recommend to check the guids in the manifest file after adding the permissions in the UI.

Sidenote as you mentioned this specific api id:
00000003-0000-0000-c000-000000000000 is the api/resource https://graph.microsoft.com

some more refs
https://github.com/microsoftgraph/microsoft-graph-docs/issues/3646 (docs issue about missing guids, pls comment or upvote the topic, this should really get more visibility)
AAD permissions: https://blogs.msdn.microsoft.com/aaddevsup/2018/06/06/guid-table-for-windows-azure-active-directory-permissions/
https://www.shawntabrizi.com/aad/common-microsoft-resources-azure-active-directory/

**Comment by davidtom** [comment]
Thanks so much for the documentation and links @jannikbuschke! I've upvoted the docs issue you linked - definitely agree it needs more visibility.

For the time being it seems that getting the guids from the manifest after creating the permissions in the UI is the best way to go about this, but I couldn't agree more that this is not at all how things should be done. Especially from the 2nd largest cloud provider, much less Microsoft.

**Comment by holylander** [comment]
Just fyi, this command may only be needed in certain scenarios.. For instance, if you are adding API permissions related to the `Sharepoint API`, you dont need to run this.

On the other hand, right after running `az ad app permission add ...` you will get a hint of which other command you may need to run

**Comment by mchudinov** [comment]
I need to add  permission to perform action 'Microsoft.Network/publicIPAddresses/join/action' 
on scope '/subscriptions/.../resourceGroups/rg-healthcheck-node-1/providers/Microsoft.Network/loadBalancers/kubernetes'

How to do it using command line?
Where to find those GUIDs **from cli** ?
I need it to be automated in a script.

**Comment by jiasli** [comment]
@mchudinov, `az ad app permission grant` is for [Active Directory Graph delegated permissions](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#permission-types).

What you are referring to are ARM permissions, which should be configured using [Azure role-based access control (Azure RBAC)](https://docs.microsoft.com/en-us/azure/role-based-access-control/overview). You may refer to RBAC document and do corresponding settings with [`az role`](https://docs.microsoft.com/en-us/cli/azure/role) commands. 

If you are still not sure about how to do that, you may [create a support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) for corresponding service.
