### ISSUE TITLE
Capability to change the vm size of the nodes

### ISSUE THREAD

**Issue by strimpak** [Azure/azure-cli#7927]
One should be capable to change the vm sizes of the nodes (re-define the vm size of all nodes). Currently we can define the vm size on cluster creation and we must leave with this size. In case we need to change the vm size we have to create another cluster and then phase out the old one. This is not a good practice in modern devops. 

I thinks spawning vm by vm of the new size definition and shutting old nodes down could be an approach. I think something similar is done when upgrading kubernetes version. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-create)
* Content Source: [src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by GabrielSchlatter** [comment]
This is important to me as well.

In my case i initially chose a VM size that has not enough memory for production use.
Now i will have to spawn an entirely new cluster instead of just upgrading to a larger node size (which i wpould have expected)

**Comment by jluk** [comment]
This is now supported with multiple agent pools feature in preview. You can create and delete new pools which enable a different VM SKU to be defined for a given cluster.

Docs are here: https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools

Closing.
