### ISSUE TITLE
Description for --reliability-level is incorrect

### ISSUE THREAD

**Issue by danvanderboom** [Azure/azure-cli#7931]
Under "Required Parameters", the description for --reliability-level says "Durability level." It should say "Reliability level." Or even better, a real description of what these terms mean, or at least a link to that documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be85eda5-6445-bd94-c6fc-424f218c92f9
* Version Independent ID: 6713012a-a8cb-33a3-888b-4f89d62ccd53
* Content: [az sf cluster reliability](https://docs.microsoft.com/en-us/cli/azure/sf/cluster/reliability?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/sf/cluster/reliability.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/sf/cluster/reliability.yml)
* Service: **service-fabric**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by nixphix** [comment]
Let me send a patch

**Comment by tjprescott** [comment]
The PR would be made to the file `_help.py` in this repo for azure-cli-servicefabric.

**Comment by peterpogorski** [comment]
@tjprescott This looks to be resolved. Can you please close this issue?
