### ISSUE TITLE
az role assignment list --assignee useremail@mydonain.com not working

### ISSUE THREAD

**Issue by abhiramani-iptiq** [Azure/azure-cli#7935]
**Describe the bug**
command:az role assignment list --assignee useremail@mydonain.com 
is not showing any results but corresponding powershell command works fine
Get-AzureRmRoleAssignment -SignInName useremail@mydonain.com

**To Reproduce**
run this command in Azure cloudshell bash.replace with correct email
az role assignment list --assignee useremail@mydonain.com 

**Expected behavior**
it should list all roles assigned to user

**Environment summary**
using azure cloud shell

**Additional context**

**Comment by yugangw-msft** [comment]
if you use `--all`, do you see anything coming out?

**Comment by abhiramani-iptiq** [comment]
yes i get results

**Comment by yugangw-msft** [comment]
By default, you only see assignments at the subscription level unless you call out the `--scope` or use `--all`

**Comment by abhiramani-iptiq** [comment]
not sure some temporary issue with azure cloudshell.now same command 
az role assignment list --assignee useremail@mydonain.com

is working fine
