### ISSUE TITLE
example eventhub create eventhub error

### ISSUE THREAD

**Issue by nzregs** [Azure/azure-cli#7938]
sample command above, az eventhubs eventhub create --resource-group myresourcegroup --namespace-name mynamespace --name myeventhub --message-retention 4 ---partition-count 15

"---partition-count 15" has an extra "-".  should be "--partition-count 15"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fa949ea-86b1-125e-e7d3-f0f88a2661ab
* Version Independent ID: c8351dbc-7358-ba5b-6757-3929a4a2b42b
* Content: [az eventhubs eventhub](https://docs.microsoft.com/en-us/cli/azure/eventhubs/eventhub?view=azure-cli-latest#az-eventhubs-eventhub-create)
* Content Source: [src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/_help.py)
* Service: **event-hubs**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Fixed in #7883.
