### ISSUE TITLE
Return empty array '[]' instead of nothing for json output

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#794]
If you have no VMs and you run vm list, you get nothing when you should get an empty array.

Actual:

```
$ az vm list -ojson
$
```

Expected:

```
$ az vm list -ojson
[]
$
```

See https://github.com/Azure/azure-cli/issues/575#issuecomment-243504152

**Comment by ahmetalpbalkan** [comment]
It looks like `jq` works just fine with this.

```
➜  ~ echo '' | jq '.[].name'
➜  ~ echo '[{"name":"x"}]' | jq '.[].name'
"x"
```

however this is still concerning as empty string is NOT valid json contents. So outputting `[]` from empty results would still be preferable.

**Comment by derekbekoe** [comment]
Here's how jpterm handles empty string.
```
$ echo '' | jpterm
Unable to load the input JSON: No JSON object could be decoded

$ echo $?
0
```

Whilst jpterm does not open, jpterm returns exit code 0.

```
$ echo 'null' | jpterm
```

With this, jpterm opens as expected.
