### ISSUE TITLE
webapp: Zipdeployment status polling : Increase default time out (currently 5mins) & decrease the polling interval (currently 30s)

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-cli#7942]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by yugangw-msft** [comment]
Fixed by #7930
