### ISSUE TITLE
webapp: zip deployment should return a failure if deployment does not complete during the timeout provided

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-cli#7943]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by panchagnula** [comment]
@yugangw-msft , i updated the command to return raise ValueError, instead of logger.warning. However, i don't understand the difference b/w using logger.error vs raising an exception & what is recommendation on using one over the other. Thanks!

**Comment by yugangw-msft** [comment]
Logger.error only makes sure the information gets to `stderr`. The exit code will still be 0. 
Suggest raise CLIError

**Comment by yugangw-msft** [comment]
#7930 fixed it
