### ISSUE TITLE
Can't update app property "allowPublicClient"

### ISSUE THREAD

**Issue by haodeon** [Azure/azure-cli#7955]
**Describe the bug**

Run command

az ad app update --id "guid of application" --set allowPublicClient=false

command returns an error saying input is invalid

**To Reproduce**

az ad app update --id "guid of application" --set allowPublicClient=false

**Expected behavior**

command to return successfully and for property "allowPublicClient" to be set to false

**Environment summary**

ubuntu 18.04 on WSL, azure cli installed via official repo - version 2.0.51

**Additional context**

I have tried setting it true, null, 0. All values I have tried are invalid and error. Currently the only way I know of to set the value is to edit the manifest in the Azure Portal.

**Comment by yugangw-msft** [comment]
`allowPublicClient` is not a valid app property to tweak. If you are asking about converting from a confidential client to a public client, the only way is to go through `az ad app create`. I can elaborate the context if needed, let me know.

**Comment by haodeon** [comment]
@yugangw-msft Could you please explain your answer with the below documentation as context?

https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest

In the docs for Azure Active Directory app manifest, allowPublicClient is a key that can take on a boolean value. In the Azure AD portal, I can open this manifest and change the bool to true or false and save the change.

What I was raising in this bug report is the fact the Azure CLI is unable to set this key.

This issue is not solved as far as I am aware and should not be closed.

**Comment by yugangw-msft** [comment]
@haodeon, the link you pointed out is on V2. Azure CLI works with V1 like the most of other Azure resources. To cross check, I opened a V1 application in portal, and I could not find the "allowPublicClient" property in the manifest.

**Comment by haodeon** [comment]
@yugangw-msft, thanks for your response. I did not know in Azure AD an application could be V1 or V2.

However, I opened the portal and checked the application manifest in both "App Registrations" and "App Registrations (Preview)"

The property "allowPublicClient" is in the "App Registrations (Preview)" manifest blade.

In the older blade the manifest does have a "publicClient" property.

As a test I edited the "allowPublicClient" property to be **true** and when I refreshed the other manifest "publicClient" was changed to **true**.

So these two properties appear to be one and the same

My last test was to try

az ad app update --id "guid of application" --set publicClient=false

This did set the property in both manifests to false.

So this confirms the properties are one and the same.

**Comment by yugangw-msft** [comment]
@haodeon, let me cross check with AAD group and get clear on this. If `publicClient` == `allowPublicClient`, I will sure update the command to support this. Thanks for the information.

**Comment by paolosalvatori** [comment]
Any update? I need to set the following properties in the manifest of a registered app:

"allowPublicClient": true,
"oauth2AllowIdTokenImplicitFlow": true,
"signInAudience": "AzureADMultipleOrgs",

**Comment by yugangw-msft** [comment]
Can you try `az ad app update --id $aksClientApplicationAppId --set publicClient=true --remove identifierUris`? Public client is not supposed to have `identifierUris` which is what this error tries to communicate.

**Comment by paolosalvatori** [comment]
Hi @yugangw-msft 

I tried your suggestion, but it didn’t work for me. I still get a Property identifierUris is invalid error when the script executes the command below. The script below is taken from the first part of my script to generate an AKS cluster integrated with Azure AD. Note: I’m a global administrator of the Azure AD tenant in question.


#!/bin/bash

# variables

# service principal, server application and client application used by the AKS cluster
aksServicePrincipal="LeonardAksServicePrincipal"
aksServerApplication="LeonardAksServerApplication"
aksClientApplication="LeonardAksClientApplication"

# subscriptionId and tenantId of the current subscription
subscriptionId=$(az account show --query id --output tsv)
tenantId=$(az account show --query tenantId --output tsv)
tenantName="babo"


# check if the client application already exists
echo "Checking if ["$aksClientApplication"] client application actually exists in ["$tenantId"] tenant..."

aksClientApplicationId="https://"$aksClientApplication"."$tenantName".onmicrosoft.com"
aksClientApplicationAppId=$(az ad app list --display-name $aksClientApplication --query [].appId --output tsv)

if [[ -z $aksClientApplicationAppId ]]; then
    echo "No ["$aksClientApplication"] client application actually exists in ["$tenantId"] tenant"
    echo "Creating ["$aksClientApplication"] client application in ["$tenantId"] tenant..."

    # create the client application
    aksClientApplicationAppId=$(az ad app create \
    --identifier-uris $aksClientApplicationId \
    --reply-urls $aksClientApplicationId \
    --display-name $aksClientApplication \
    --end-date $endDate \
    --credential-description "AKSPassword" \
    --available-to-other-tenants true \
    --oauth2-allow-implicit-flow true \
    --query appId \
    --output tsv)

    if [[ -n $aksClientApplicationAppId  ]]; then
        echo "["$aksClientApplication"] client application successfully created in ["$tenantId"] tenant with [$aksClientApplicationAppId] appId"
    else
        echo "Failed to create ["$aksClientApplication"] client application in ["$tenantId"] tenant"
        exit
    fi

    # Create a service principal for the Azure AD application
    echo "Assigning service principal to ["$aksClientApplication"] client application..."
    az ad sp create --id $aksClientApplicationAppId 1> /dev/null

    if [[ $? == 0 ]]; then
        echo "Service principal successfully assigned to [$aksClientApplication] client application"
    else
        echo "Failed to assign service principal to ["$aksClientApplication"] client application"
        exit
    fi

    # setting public client to true
    az ad app update \
    --id $aksClientApplicationAppId \
    --set publicClient=true \
    --remove identifierUris

    if [[ $? == 0 ]]; then
        echo "Successfully set allowPublicClient value to [true] for the ["$aksServerApplication"] server application"
    else
        echo "Failed to set allowPublicClient value to [true] for the ["$aksServerApplication"] server application"
        exit
    fi

    # get the id of the access delegated permission to the server application
    oAuthPermissionId=$(az ad app show --id $aksServerApplicationAppId --query "oauth2Permissions[0].id" --output tsv)

    if [[ -n $oAuthPermissionId ]]; then
        echo "["$oAuthPermissionId"] id of the [Access "$aksServerApplication"] delegated permission successfully retrieved"
    else
        echo "Failed to retrieve the id of the [Access "$aksServerApplication"] delegated permission" 
        exit
    fi

    # add to the client application the delegated permission to access the server application
    az ad app permission add \
    --id $aksClientApplicationAppId \
    --api $aksServerApplicationAppId \
    --api-permissions $oAuthPermissionId=Scope

    #az ad app permission add \
    #--id $aksClientApplicationAppId \
    #--api 00000002-0000-0000-c000-000000000000 \
    #--api-permissions 311a71cc-e848-46a1-bdf8-97ff7156d8e6=Scope 

    az ad app permission grant --id $aksClientApplicationAppId --api $aksServerApplicationAppId

    if [[ $? == 0 ]]; then
        echo "[Access "$aksServerApplication"] delegated permission successfully added to the ["$aksClientApplication"] client application"
    else
        echo "Failed to add the [Access "$aksServerApplication"] delegated permission to the ["$aksClientApplication"] client application"
        exit
    fi
else
    echo "["$aksClientApplication"] client application already exists in ["$tenantId"] tenant with [$aksClientApplicationAppId] appId"
fi

**Comment by yugangw-msft** [comment]
@paolosalvatori, did you try the CLI from the latest dev ?

**Comment by MichaelBakker** [comment]
I believe you shouldn't remove the "identifierUris", but leave it empty.
This worked for me: 
...
"identifierUris": [],
...

**Comment by roederja2** [comment]
Well, it "works" as it it lets you edit the manifest, but it seems to break the Device Code flow if identifierUris is empty:

`AADSTS500011: The resource principal named api://<...> was not found in the tenant named <...>. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.`

I have an old application which was set up when simultaneously setting identifierUris and allowPublicClient was still allowed and everything works fine.

**Comment by jiasli** [comment]
### AD Graph API 1.6 - `publicClient` (Deprecated)
Per the doc for [Application](https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/api/entity-and-complex-type-reference#application-entity), `publicClient` is a `bool`.

Name | Type | Supports | Description
-- | -- | -- | --
publicClient | Edm.Boolean | POST, GET | Specifies whether this application is a public client (such as an installed application running on a mobile device). Default is false.

### AD Graph API 2.0 - `allowPublicClient` (Deprecated)
AD Graph 2.0 is an internal API used by Azure Portal, but is not exposed to public client tools like Azure CLI. Per the doc for [app manifest](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest#allowpublicclient-attribute), the corresponding name is `allowPublicClient`.

| Key | Value type |
| :--- | :--- |
| allowPublicClient | Boolean |

### MS Graph API 1.0 - `isFallbackPublicClient`
Per the doc for [Application](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0), the name is now `isFallbackPublicClient`. In MS Graph, the name `publicClient` now stands for a `publicClientApplication` object.

| Property | Type | Description |
|:---------------|:--------|:----------|
| isFallbackPublicClient | Boolean | Specifies the fallback application type as public client, such as an installed application running on a mobile device. The default value is `false` which means the fallback application type is confidential client such as web app. There are certain scenarios where Azure AD cannot determine the client application type (e.g. [ROPC](https://tools.ietf.org/html/rfc6749#section-4.3) flow where it is configured without specifying a redirect URI). In those cases Azure AD will interpret the application type based on the value of this property.|
| publicClient | [publicClientApplication](https://docs.microsoft.com/en-us/graph/api/resources/publicclientapplication?view=graph-rest-1.0) | Specifies settings for installed clients such as desktop or mobile devices. |

To turn on `isFallbackPublicClient`, you may use `az rest` with MS Graph API [Update application](https://docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&tabs=http):

```
az rest --method PATCH --uri https://graph.microsoft.com/v1.0/applications/b4e4d2ab-e2cb-45d5-a31a-98eb3f364001 --headers 'Content-Type=application/json' --body '{"isFallbackPublicClient": true}'
```

(We will track MS Graph issue at https://github.com/Azure/azure-cli/issues/12946)

**Comment by Farzad-Jalali** [comment]
> `allowPublicClient` is not a valid app property to tweak. If you are asking about converting from a confidential client to a public client, the only way is to go through `az ad app create`. I can elaborate the context if needed, let me know.

yes, please elaborate more, I need to create a SPA App and set it's AllowPublicclient to be true, because it'sfalse .
here is my code:

```

 az ad app create --display-name $config.PkceApp.displayName  `
    --native-app $false `
    --oauth2-allow-implicit-flow $false `
    --required-resource-accesses @Azure/manifest-pkce-required-resource-accesses.json `
    --reply-urls $config.PkceApp.redirectUris
```

**Comment by jiasli** [comment]
@Farzad-Jalali, please kindly follow the above answer (https://github.com/Azure/azure-cli/issues/7955#issuecomment-611976458) and use `az rest` to make the change.
