### ISSUE TITLE
getting error while creating the acs cluster

### ISSUE THREAD

**Issue by palashg7563** [Azure/azure-cli#7966]
**Describe the bug**
error: unknown option `--orchestrator-type
**To Reproduce**
azure acs create --name Clustername --orchestrator-type=DockerCE --resource-group resourcename --generate-ssh-keys
**Expected behavior**
will create a cluster

Do correct me if i am wrong

**Comment by tjprescott** [comment]
If this is a bug, please reopen, providing all of the information requested in the issue template.
