### ISSUE TITLE
error on update firewall using cli

### ISSUE THREAD

**Issue by prashanthmadi** [Azure/azure-cli#7969]
```
az cosmosdb update --name \\'xxx\\' --resource-group \\'xxxxx\\' --ip-range-filter 
```
gives below error

'stderr': 'ERROR: Operation failed with status: 'BadRequest'. Details: Cannot disable 'enableMultipleWriteLocations' flag once it has been enabled.\\r

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc8d652-2eda-296f-28ea-8d5f1ea855b3
* Version Independent ID: 80b87995-d339-61e9-1cac-b5c9ad6efe5e
* Content: [az cosmosdb](https://docs.microsoft.com/en-us/cli/azure/cosmosdb?view=azure-cli-latest#az-cosmosdb-update)
* Content Source: [src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_help.py)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by shichawl** [comment]
Is there any update on this issue?

**Comment by tjprescott** [comment]
Thank you @shurd!
