### ISSUE TITLE
Add the ability to configure a new Linux functionapp with ACR/Private registry

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-cli#7970]
**Describe the solution you'd like**
an `az functionapp xyz` command that would configure the app at creation time and afterwards to work with ACR and Private registries

**Describe alternatives you've considered**
this currently can be done after creating a Linux function using `az functionapp config container set` commands

**Additional context**

**Comment by panchagnula** [comment]
@ahmedelnably / @ankitkumarr can you take a look at this since this looks function app related. Thank you.

**Comment by ahmedelnably** [comment]
This is related to https://github.com/Azure/azure-cli/issues/7261, reassigning 7970 to @Nking92

**Comment by panchagnula** [comment]
@ahmedelnably we are still trying to figure out the work for #7261& is still assigned to Yi. Also Note that webapp create & function app create don't share the same code anymore so even with basic work done for az webapp create some one from function will need to make the changes for functionapp https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/commands.py#L215 . Please don't assign issue to Nick directly, in the future please assign it to Yi or me & we will triage it. Thank you.
