### ISSUE TITLE
Add testing to RPM step of the release process to ensure the RPM build is signed prior to publishing.

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#7986]
We have had at least two instances where the "signed" RPM package wasn't actually signed but was published, blocking customers. Similar to what we do for Homebrew, we can test the RPM build prior to publishing it to ensure the package that will be published is in fact signed.

**Comment by marstr** [comment]
Related PR: https://github.com/Azure/azure-cli/pull/8089

**Comment by tjprescott** [comment]
@marstr I believe this is done. Can we close this?
