### ISSUE TITLE
az container create - support decimal values for CPU

### ISSUE THREAD

**Issue by benc-uk** [Azure/azure-cli#7988]
**Describe the bug**
Azure Container Instances supports decimal values for the CPU resource allocation and also allows a value less than 1. This works when deploying via ARM template or YAML file. When using the CLI and supplying the --cpu switch it incorrectly expects the value to be an integer. e.g.
```
az container create: error: argument --cpu: invalid int value: '1.5'
```

**To Reproduce**
Run `az container create -g myGroup -n demofoo --image microsoft/aci-helloworld --cpu 0.5`

**Expected behavior**
Container group is deployed with fractional CPU allocation

**Environment summary**
Installed CLI via MSI and also apt-get
Problem occurs on both PowerShell and WSL bash
CLI version azure-cli (2.0.51)

**Additional context**
This is the offending line of code, changing it to type=float would solve this
https://github.com/Azure/azure-cli/blob/810bebab6a886d17a2cf4d59db048eb62b389ffb/src/command_modules/azure-cli-container/azure/cli/command_modules/container/_params.py#L67

**Comment by benc-uk** [comment]
Nearly two months an not even a comment?

**Comment by tjprescott** [comment]
@samkreter for comment.

**Comment by samkreter** [comment]
Just made the fix. Should be merged soon.
