### ISSUE TITLE
Cannot create resource groups with parenthesis

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#799]
```
$ az resource group create -l westus -n "derek(1"
Parameter 'resource_group_name' must conform to the following pattern: '^[-\\w\\._]+$'.
```

From the documentation at https://msdn.microsoft.com/en-us/library/azure/dn790546.aspx:
{resource-group-name} must uniquely identify the resource group within the subscription. It must be no longer than 80 characters long. It can only contain alphanumeric characters, dash, underscore, **opening parenthesis, closing parenthesis** or period. The name cannot end with a period. Currently, using a parenthesis in the name causes problems when using Azure PowerShell or Azure CLI. Therefore, we recommend you avoid using an opening or closing parenthesis in the name.

Creating this issue to track this along with xplat CLI and PowerShell.
https://github.com/Azure/azure-xplat-cli/issues/3109
https://github.com/Azure/azure-powershell/issues/2768

**Comment by derekbekoe** [comment]
The Swagger file was updated with this fix (https://github.com/Azure/azure-rest-api-specs/pull/490).
When the new azure-mgmt-resources SDK package is released (0.30.0rc6?), this will be fixed and the issue can be closed.

**Comment by mayurid** [comment]
@derekbekoe and @yugangw-msft : Is this change in with the RC6 update we just did.

**Comment by derekbekoe** [comment]
Verified that this is working now. Closing issue.
