### ISSUE TITLE
--share-name parameter does not exist.

### ISSUE THREAD

**Issue by moebius87** [Azure/azure-cli#7990]
the "--share-name / -s" parameter does not exist. The correct one should be "--name / -n"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae881ef-ad75-32e6-6e64-6b526a2d9a5d
* Version Independent ID: 99971e2e-9ff6-f865-07f7-61efbcb16021
* Content: [az storage share](https://docs.microsoft.com/en-us/cli/azure/storage/share?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
See #8023.

**Comment by tjprescott** [comment]
This has been fixed.
