### ISSUE TITLE
core: local context support

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#7992]
The idea is to find a way to persist current resource group, current webapp, etc, and be able to switch among different contexts.  From UX's aspect, this saves you from typing the resource group name again and again.
`az configure` has the support, but the usage is limited per the nature of the global singleton. 

//CC: @panchagnula @tjprescott @yiliaomsft @achandmsft

**Comment by yugangw-msft** [comment]
Code is complete at https://github.com/yugangw-msft/azure-cli/tree/localctx and we just wait for appservice  team's confirmation

**Comment by panchagnula** [comment]
@yugangw-msft  thanks I will give you an update on our usage of this, later this week.

**Comment by yugangw-msft** [comment]
done
