### ISSUE TITLE
--server

### ISSUE THREAD

**Issue by dcbrown16** [Azure/azure-cli#7995]
This appears to take --server, not --server-name now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d84bcc6-6274-7c1b-3394-c8be820ec786
* Version Independent ID: 67fc9ae8-4e2b-f58b-fde9-0c3f5ab8a24d
* Content: [az sql server conn-policy](https://docs.microsoft.com/en-us/cli/azure/sql/server/conn-policy?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
This has been fixed.
