### ISSUE TITLE
Install particular version of an extension

### ISSUE THREAD

**Issue by gauravsaralMs** [Azure/azure-cli#7997]
If I have written scripts on a particular version of an azure cli extension then is it possible for me to install the same version on a fresh machine (using az extension add)?

This will be useful in automation if or when some CLI extension breaks back compatibility.. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ea1a0d9-c0d5-657d-f73b-0e9220bec600
* Version Independent ID: 7138b13a-3381-1aee-346b-5e7f6905c5b3
* Content: [az extension](https://docs.microsoft.com/en-us/cli/azure/extension?view=azure-cli-latest#az-extension-add)
* Content Source: [src/command_modules/azure-cli-extension/azure/cli/command_modules/extension/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-extension/azure/cli/command_modules/extension/_help.py)
* Service: **azure-cli**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
I believe that is more controlled by the extension author than the user. For example, if your CLI version is < X it would install version Y of the extension, but if your CLI version is > X it would install version Z.  @williexu for confirmation.

**Comment by gauravsaralMs** [comment]
Thanks @tjprescott @williexu .
Closing this now

**Comment by gauravsaralMs** [comment]
Reopening this because we have a scenario around this.
Azure DevOps ship online as well as it ships on-prem.
For on-prem customers (who are on old version) we would like to support the functionality of installing old versions.

@tjprescott  @williexu : Do you think this as a functionality which we can add to CLI. I know we can provide wheels for installation but having an option to install from CLI by giving version will be a much better experience for our customers.

**Comment by williexu** [comment]
@gauravsaralMs I'm a little confused by what you mean. How does being able to install two different versions of an extension for a single version of the CLI support your scenario?

You mentioned wanting to provide different functionality for some users in an older extension version. What happens if changes need to be made for that set of users?

**Comment by gauravsaralMs** [comment]
We ship azure DevOps server as well and would like to support that as well
Now scenario is something like this
in DevOps Server 2018 there is option to create PR so we have a command `az repos pr create source_branch target_branch`
in DevOps Server 2019 there is option to create **with draft mode** so the command needs to be `az repos pr create source_branch target_branch`

so we want to provide different version of CLI to user of Server 2018 and different version of CLI to user of Server 2019

we plan to recommend something like this
If you are using CLI against server 2018 then install version X, if you are using CLI against server 2019 then use version Y
and for server (Azure DevOps online) we will always recommend using latest version of extension.

About the changes, once a server is shipped on-prem there are very small changes (security/ critical patches) which go in, so we really don't anticipate much changes but yes this is a valid case (although a corner case)

cc: @williexu

**Comment by williexu** [comment]
@gauravsaralMs I know what you mean, but shipping different logic based on the version of the extension still does not sound ideal to me. Some aspects of semantic versioning will be thrown off.

Have you considered allowing the user to set some context stating the DevOps Server he/she wants to use and then simply running the right logic based on that context? This could be scoped to the one command through an option, or the full set of devops commands through a configuration saved to file. Another possibility could also be to maintain a separate extension if the changes between the  two versions are large enough.

**Comment by gauravsaralMs** [comment]
@williexu : We did considered that approach as well but that has a few downsides like
1. Every extension which wants to provide this kind of support will have to write logic to handle different versions and will have to handle the same in code
2. Because we will have to pack clients across multiple versions it will make the extension heavy (install time) and of the multiple client versions packed only one be used at max by the user.

Does shipping entirely different extensions sounds fine? because that will solve this problem as well..

**Comment by williexu** [comment]
@gauravsaralMs Shipping different extensions is fine. :)

To relay your concerns about the other method-
For 1., this is not unprecedented; we already do so in even the CLI itself, to account for different profiles (stack, hyprid) and the api-versions they support. 
For 2., this may be a concern, though for most client libraries, we have not seen this as a problem.
On the plus side, assuming the two versions are similar enough, having both in one extension will prevent much code duplication and will give users the benefit of simply installing the one extension.
