### ISSUE TITLE
vcores is not a valid parameter

### ISSUE THREAD

**Issue by pbritnell** [Azure/azure-cli#7998]
vcores is not a valid parameter, I had to use --capacity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06c9a36f-c18a-748b-559a-927c7f4988fb
* Version Independent ID: 7af90d97-d085-b8fa-4e02-d3e601a1846d
* Content: [az sql mi](https://docs.microsoft.com/en-us/cli/azure/sql/mi?view=azure-cli-latest#az-sql-mi-update)
* Content Source: [src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
See #8023.

**Comment by tjprescott** [comment]
This has been fixed.
