### ISSUE TITLE
az disk list 

### ISSUE THREAD

**Issue by sam90909** [Azure/azure-cli#7999]
What is the purpose of this command?

Is this not used to list the disk information?

Why does the  --disk-name mentioned in the doc talk about the disk being created? Am I missing something or the doc needs to be corrected?

**The name of the managed disk that is being created. The name can't be changed after the disk is created. Supported characters for the name are a-z, A-Z, 0-9 and _. The maximum name length is 80 characters.**

I am using this command to view disk information. Is this not how this is supposed to be used? Also, I keep getting an error for the following command 

**PS Azure:\&gt; az disk show --keerthidisk --v-kegan
az: error: unrecognized arguments: --keerthidisk --v-kegan
usage: az [-h] [--verbose] [--debug] [--output {json,jsonc,table,tsv,yaml}]
          [--query JMESPATH]
          {disk} ...**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74997eeb-6fa3-4318-79da-8cf4dce59cfe
* Version Independent ID: c8cea09f-196e-7269-dc42-b6b8933dbaf1
* Content: [az disk](https://docs.microsoft.com/en-us/cli/azure/disk?view=azure-cli-latest#az-disk-list)
* Content Source: [latest/docs-ref-autogen/disk.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/disk.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by adewaleo** [comment]
@sam90909. This is not how the command is to be used. 

The help for this command ([online](https://docs.microsoft.com/en-us/cli/azure/disk?view=azure-cli-latest#az-disk-show) or by running `az disk show -h`) show you what parameters you need to execute this command.

So if you have a disk named  `my_disk` in a group called `my_group`, you would execute the following command to get the information for the disk:

```
az disk show --name my_disk --resource-group my_group
```
