### ISSUE TITLE
`az cosmosdb list-connection-strings` documentation difference

### ISSUE THREAD

**Issue by mindlessroman** [Azure/azure-cli#8006]
When you run `az cosmosdb list-connection-strings --account-name blahblahblah` as suggested by the documentation, the following error will result:
```
$ az cosmosdb list-connection-strings -g blahblahblah --account-name testing
az: error: unrecognized arguments: --account-name testing
usage: az [-h] [--verbose] [--debug] [--output {json,jsonc,table,tsv,yaml}]
          [--query JMESPATH]
          {cosmosdb} ...
```
Additionally, if you try to run `az cosmosdb list-connection-strings -g blahblahblah` without the account name (to see what complains), it returns an error:
```
$ az cosmosdb list-connection-strings -g blahblahblah
(--name | --ids) are required
```
Two problem here: 
1. This error would sort of suggest that these two things are interchangeable and they are not
```
$ az cosmosdb list-connection-strings -g blahblahblah --ids testing
option '--resource-group' will be ignored due to use of '--ids'.
```
2. The `--name` argument is not in the documentation, which will lead to confusion. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc8d652-2eda-296f-28ea-8d5f1ea855b3
* Version Independent ID: 80b87995-d339-61e9-1cac-b5c9ad6efe5e
* Content: [az cosmosdb](https://docs.microsoft.com/en-us/cli/azure/cosmosdb?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_help.py)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
See #8023.

**Comment by tjprescott** [comment]
This has been fixed.
