### ISSUE TITLE
Documentation fix?

### ISSUE THREAD

**Issue by mindlessroman** [Azure/azure-cli#8007]
```
usage: az cosmosdb collection create [-h] [--verbose] [--debug]
                                     [--output {json,jsonc,table,tsv,yaml}]
                                     [--query JMESPATH]
                                     [--resource-group-name DB_RESOURCE_GROUP_NAME]
                                     [--name DB_ACCOUNT_NAME]
                                     [--key DB_ACCOUNT_KEY]
                                     [--url-connection DB_URL_CONNECTION]
                                     --db-name DATABASE_ID --collection-name
                                     COLLECTION_ID [--throughput THROUGHPUT]
                                     [--partition-key-path PARTITION_KEY_PATH]
                                     [--default-ttl DEFAULT_TTL]
                                     [--indexing-policy INDEXING_POLICY]
                                     [--subscription _SUBSCRIPTION]
```
It would seem that in most of these instances `--database-id` needs to become `--db-name` for this page's documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d791e10-4181-cf15-1398-499eb0918c9c
* Version Independent ID: 2e5f864d-29bd-da4f-b964-a87a39f988c0
* Content: [az cosmosdb collection](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/collection?view=azure-cli-latest#az-cosmosdb-collection-create)
* Content Source: [src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_help.py)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by shurd** [comment]
@mindlessroman thank you for submitting an issue. I am not sure if that page has changed since you submitted the suggestion, but I do not see `--database-id` referenced on the page. Are you referring to "DATABASE_ID" following the `--db-name` parameter?

**Comment by shurd** [comment]
I am going to close this issue for now. I do not see where `--database-id` is referenced on that page. If you have a specific example of where it is used, you can re-open the issue, and we can work on correcting it if needed. Database Id is another term for the database name, so these can be interchangeable in documentation.
