### ISSUE TITLE
cannot set space-separated --service-endpoints on subnets

### ISSUE THREAD

**Issue by rnowagk** [Azure/azure-cli#8009]
**Describe the bug**

Documentation of 'network vnet subnet create/update' says

> --service-endpoints            : Space-separated list of services allowed private access to this                                                                              subnet.  

This leads to errors like:
    .../subnets/test has an item in ServiceEndpoints array with invalid service name 'Microsoft.Storage Microsoft.Sql'

**To Reproduce**

    az network vnet subnet update -g ... --vnet-name ... -n ... --service-endpoints "Microsoft.Sql Microsoft.Storage"

**Expected behavior**
subnet configured with both endpoints;
ideally in the 'update' case: a flag to allow adding endpoints instead of always overwriting the existing list

**Environment summary**
CentOS 7.5;  azure-cli-2.0.52-1.el7.x86_64.rpm  through yum repository:

**Comment by tjprescott** [comment]
That is because you are not supplying a space-separated list. You are supplying a string with a space in it. Remove the double quotes and it should work just fine.
