### ISSUE TITLE
Enable activity log output to Log Analytics workspace

### ISSUE THREAD

**Issue by SenthuranSivananthan** [Azure/azure-cli#8010]
**Is your feature request related to a problem? Please describe.**
I would like the ability to enable activity log output to Log Analytics workspace through CLI.  The goal is to automate subscription creation and scaffolding before handing out subscriptions to LOBs.

**Describe the solution you'd like**
Add extra parameter for workspaceid.  For example:

az monitor log-profiles create --workspace-id `resourceId`

**Describe alternatives you've considered**
This is possible Azure Portal.

**Comment by asheniam** [comment]
Logprofiles does not support Log Analytics as a destination sink.  We are working on new version of diagnostic settings API to support routing Activity Logs to Log Analytics

**Comment by diegoitaliait** [comment]
Hi,

Is there an approximate date for the new API?

**Comment by MyronFanQiu** [comment]
@asheniam Hello. Any update?

**Comment by nkiest** [comment]
We are shipping the new API method "Subscription Diagnostic Settings" this month. The CLI should be available shortly thereafter.

**Comment by yonzhan** [comment]
@nkiest any update for this issue?

**Comment by nkiest** [comment]
We have REST API support, but are still working to enable powershell and CLI.

**Comment by nkiest** [comment]
https://docs.microsoft.com/en-us/rest/api/monitor/subscriptiondiagnosticsettings/createorupdate

**Comment by infa-dgowran** [comment]
Any updates on cli support ? trying to automate the Azure Activity Log connection to subscription with Log Analytics Connection. this does not appear to have a cli option.

![image](https://user-images.githubusercontent.com/55835575/80825145-b8a0d900-8bd7-11ea-9a41-d38d61589d89.png)

**Comment by yonzhan** [comment]
@nkiest any update for this?

**Comment by infa-dgowran** [comment]
Is this something in the roadmap ?

**Comment by yonzhan** [comment]
@nkiest any update for this?

**Comment by nkiest** [comment]
We already have a request on the CLI team, awaiting that. https://github.com/Azure/azure-cli/issues/13692
