### ISSUE TITLE
azure-cli-core breaking change detection

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#8014]
We have had instances where a change in `azure-cli-core` was not identified as a breaking change during development or code review, resulting in inadvertently breaking extensions or other interfacing tools. We should follow the example of the Python SDK to detect breaking changes to specific interfaces we want to ensure continue to work.  Example files:

https://github.com/Azure/azure-sdk-for-python/blob/master/azure-sdk-tools/packaging_tools/code_report.py

https://github.com/Azure/azure-sdk-for-python/blob/master/azure-sdk-tools/packaging_tools/change_log.py

**Comment by tjprescott** [comment]
Also, our static analyzers (PEP8, pylint) will encourage us to make breaking changes without realizing it.  See #8012.

**Comment by adewaleo** [comment]
Also see: https://github.com/Azure/azure-sdk-for-python/wiki/Automatic-ChangeLog

**Comment by adewaleo** [comment]
Will continue work on this in sprint 56 based on feedback from brain storm meeting.

**Comment by adewaleo** [comment]
closed this as we don't have bandwidth to open this in the near future
