### ISSUE TITLE
az webapp deployment slot swap: wrong documented params

### ISSUE THREAD

**Issue by tiny-dancer** [Azure/azure-cli#8015]
```bash
az webapp deployment slot list --resource-group stuff --webapp application

az: error: unrecognized arguments: --webapp application
usage: az [-h] [--verbose] [--debug] [--output {json,jsonc,table,tsv,yaml}]
          [--query JMESPATH]
          {webapp} ...
```

```bash
$ az webapp deployment slot list --resource-group stuff
(--name | --ids) are required
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce9f5bf9-d178-de1a-645b-be6947a7c049
* Version Independent ID: cb7fb876-160c-e6d9-d473-7ac39b930b48
* Content: [az webapp deployment slot](https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/slot?view=azure-cli-latest#az-webapp-deployment-slot-list)
* Content Source: [latest/docs-ref-autogen/webapp/deployment/slot.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/webapp/deployment/slot.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
See #8023.

**Comment by tjprescott** [comment]
This has been fixed.
