### ISSUE TITLE
az policy state - Trigger policy evaluation through CLI

### ISSUE THREAD

**Issue by SenthuranSivananthan** [Azure/azure-cli#8016]
**Is your feature request related to a problem? Please describe.**
As a policy admin, I'd like to trigger policy evaluation through CLI.  This helps in troubleshooting and validating policy definitions faster.

**Describe the solution you'd like**
I would like another verb added to `az policy state` such as `az policy state evaluate --scope ...`

The scope will define where the policies should be validated and would allow for management group, subscription and resource groups. 

Given that evaluation is an async process, we'll then need a way to monitor status.  Example: `az policy state status --scope ...`

**Describe alternatives you've considered**
The only alternative for this is through a REST client and following instructions from https://docs.microsoft.com/en-us/azure/governance/policy/how-to/getting-compliance-data

**Subscription**
```bash
POST https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.PolicyInsights/policyStates/latest/triggerEvaluation?api-version=2018-07-01-preview`
```

**Resource Group**
```bash
POST https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{YourRG}/providers/Microsoft.PolicyInsights/policyStates/latest/triggerEvaluation?api-version=2018-07-01-preview
```

**Comment by tjprescott** [comment]
How would this differ from `az policy state summarize`?

**Comment by SenthuranSivananthan** [comment]
> How would this differ from `az policy state summarize`?

You are right.  The status can be checked through the summarize command.  So I think the feature that's missing is to trigger the evaluation.

**Comment by yonzhan** [comment]
add to S164.

**Comment by zhoxing-ms** [comment]
I have seen that the Python SDK lacks the following method which supports evaluation of resources.

**Evaluation scan for resources:**
https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.PolicyInsights/policyStates/latest/triggerEvaluation?api-version=2018-07-01-preview
https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{YourRG}/providers/Microsoft.PolicyInsights/policyStates/latest/triggerEvaluation?api-version=2018-07-01-preview

**Get resource evaluation results asynchronously:**
https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.PolicyInsights/asyncOperationResults/{ResourceContainerGUID}?api-version=2018-07-01-preview

Could the Python SDK support the above services? @sandipsh

**Comment by yonzhan** [comment]
@sandipsh any update for this issue?

**Comment by sandipsh** [comment]
Yes, we have plan to add this operation to the swagger/SDK soon. I will keep you posted. Thanks!

**Comment by yonzhan** [comment]
@sandipsh any update for this issue?

**Comment by sandipsh** [comment]
> @sandipsh any update for this issue?

@yonzhan, swagger update is completed now - https://github.com/Azure/azure-rest-api-specs/pull/8312

**Comment by zhoxing-ms** [comment]
@sandipsh We also need the method of obtaining resource evaluation results asynchronously, please add it.

Service API: https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.PolicyInsights/asyncOperationResults/{ResourceContainerGUID}?api-version=2018-07-01-preview

**Comment by yonzhan** [comment]
@sandipsh any further update?

**Comment by sandipsh** [comment]
Sorry for delayed response - I have notified [Cale](https://github.com/calecarter) who made original change to respond.

**Comment by kenieva** [comment]
Hi yonzhan, we don't have this in the upcoming plans due to other features in the pipeline. One of those is an improvement in the time for compliance evaluation to surface. With this exciting change, there will be little need to trigger an evaluation. However, I would recommend adding a feature request to our UserVoice on this request: https://feedback.azure.com/forums/915958-azure-governance. You can add this and any other feature request in that channel so it can be properly backlog. Thanks!

**Comment by zhoxing-ms** [comment]
@calecarter Hi, Here is another customer who also has similar requirements. #12718
May I ask how is your progress?

**Comment by kenieva** [comment]
@zhoxing-ms  changes will come in throughout the year.

**Comment by slapointe** [comment]
It's been more than a year.

any update?

> @zhoxing-ms changes will come in throughout the year.

**Comment by kenieva** [comment]
Documentation on this can be found here: https://docs.microsoft.com/en-us/cli/azure/policy/state?view=azure-cli-latest#az_policy_state_trigger_scan

**Comment by slapointe** [comment]
> Documentation on this can be found here: https://docs.microsoft.com/en-us/cli/azure/policy/state?view=azure-cli-latest#az_policy_state_trigger_scan

Thank you. I totally missed this.
