### ISSUE TITLE
Installation on Ubuntu Mate 18.04 LTS w apt fails in regard of using sudo or logged in as root

### ISSUE THREAD

**Issue by nocheinlarry** [Azure/azure-cli#8019]
**Describe the bug**
Following the install instructions https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest failed to install a usable Az Cli.

Install // 1. The copy button in this document does not work in a Linux Terminal. Only the first line worked. 

From here I got follow-up error (please refer to repo-section)
**To Reproduce**
Follow-up failure in install:

To get the repository added to apt, I switched to root (sudo -s) and created the file etc/apt/sources.list.d/azure-cli.list manual: 

AZ_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" >
etc/apt/sources.list.d/azure-cli.list

as root is ran apt-get update; apt-get install azure-cli in the home-directory of my normal priveleged user.

Then I tried to run az login, which caused probaly to create the .azure directory with root file access rights. I got error with unsupported operation in root environment.

**Expected behavior**
Please make sure, Linux .azure directory/files are always created in the right /home/xyz directory and get the right file access permissions.  

**Environment summary**
Install Method: apt-get
Az --version: 2.0.52
uname -a: 
Linux (myHostName) 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

**Comment by yugangw-msft** [comment]
@nocheinlarry, sorry for the late response, please provide output with error details. Are you on bash or other shell? Also, copying & pasting instructions from the help document works for me. JFYI I am under the similar system:
```
Linux yg-1 4.15.0-1036-azure #38~16.04.1-Ubuntu SMP Fri Dec 7 03:21:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by yugangw-msft** [comment]
Please re-activate with more information. Thanks for reporting this issue!
