### ISSUE TITLE
az appservice plan list always lists numberOfSites as 0

### ISSUE THREAD

**Issue by mgfink** [Azure/azure-cli#8022]
**Describe the bug**
The az appservice plan list does not properly identify the "numberOfSites" attribute as compared with az appservice plan show.  For example:

az appservice plan **list** output
  {
    "name": "clnc-aspint",
    "numberOfSites": 0,
    "resourceGroup": "clnc-app-rg"
  },

az appservice plan **show** output
{
  "name": "clnc-aspint",
  "numberOfSites": 6,
  "resourceGroup": "clnc-app-rg"
}

**To Reproduce**
az appservice plan list --output json --query '[].{name:name, resourceGroup:resourceGroup, numberOfSites:numberOfSites}'

**Expected behavior**
numberofSites should be properly represented in the appservice plan list output.

**Comment by panchagnula** [comment]
@mgfink filed an internal issue on the API folks about this - if this turns out to be byDesign we will remove the numberOfSites property from the appservice plan list output.

**Comment by panchagnula** [comment]
@mgfink  looking a further into this - if you run the command with -g parameter appservice plan list -g <RG NAME> you will get the right values, i am waiting to hear back from the API team, but i am guessing that in the earlier case due to perf reasons when querying across the full subscription - we don't return all the values. Closing this for now.

**Comment by mgfink** [comment]
@panchagnula I'm concerned by the implication of the previous comment.  Are we unable to trust the output from AZCLI if someone arbitrarily decides it's taking too long to return results?  Or in general are there recommendations we should always scope commands to a RG and never run them unbounded on the subscription level?

If that's really the case I'd expect some kind of flag in the output indicating the data is not to be trusted as complete.

**Comment by panchagnula** [comment]
@mgfink got an update from the backend team & there is a way to make CLI get the details even when trying to run this command on Subscription level. We will make the change on our end.

**Comment by mgfink** [comment]
@panchagnula thanks for the good news!  Once the update is available I'll test it out in our subscription.

Thanks again!
