### ISSUE TITLE
`webapp deployment source config-local-git` result misleading/wrong if publishing user not set

### ISSUE THREAD

**Issue by nickwalkmsft** [Azure/azure-cli#8028]
**Describe the bug**
If you run `az webapp deployment source config-local-git` on a webapp as a user that does not have a webapps publishing user credential configured, the username component of the resulting git URL is "None". Example result:

```
{
  "url": "https://None@myapp.scm.azurewebsites.net/myapp.git"
}
```

See [`_get_local_git_url`](https://github.com/Azure/azure-cli/blob/60c84492381dab454695b374c377dda8084502f5/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py#L1273-L1278), which does not have any handling for the case where there is no publishing user set.

**To Reproduce**
Run `az webapp deployment source config-local-git` on a webapp as a user that does not have a publishing user credential configured.

**Expected behavior**
Not sure. Suggestions:

- Fall back to the username of the app credentials (`$sitename`) and document appropriately (it's a common misconception that you must set publishing user to do git push; this is not correct, the app credentials work just as well).
- Leave out the username component of the URL entirely and document appropriately
- Throw with clear error message

**Environment summary**
Cloud shell (currently with azure-cli 2.0.52, webapp 0.2.7)

**Additional context**
The portal has essentially the same issue, but it doesn't stem from a common implementation. Reporting separately.

**Comment by panchagnula** [comment]
Closing this since this will be something that will be supported once we get API to throw the right error message in this case.
