### ISSUE TITLE
az redis import needs better docs/examples

### ISSUE THREAD

**Issue by noelbundick** [Azure/azure-cli#8030]
**Describe the bug**
`az redis import` does not have enough information available to use the command

**To Reproduce**
Execute `az redis import --help` and read the help info. I 'm not sure what file formats are supported, if the file paths are local files, public URLs, etc. 

The [REST API docs](https://docs.microsoft.com/en-us/rest/api/redis/redis/importdata) are similarly sparse - looks like RDB + a public URL, but that's not entirely clear

**Expected behavior**
`az redis import --help` should list the supported file formats, and information about the import file paths, and/or have a short aka.ms link to where to find this info.

The command should have examples on how to import one or more file types

**Environment summary**

Azure Cloud Shell / 2.0.52

**Additional context**
To confuse matters further - the docs pages have an entry for [`az redis import-method`](https://docs.microsoft.com/en-us/cli/azure/redis?view=azure-cli-latest#az-redis-import-method) which seems to have been deprecated in 2.0.34 - I'm guessing the help isn't version-aware?

**Comment by tjprescott** [comment]
The docs do not do anything with the deprecation metadata contained in the CLI.
