### ISSUE TITLE
Inserting Entity Sets Unexpected OData Type for Numeric Values

### ISSUE THREAD

**Issue by Andrei15193** [Azure/azure-cli#8032]
**Describe the bug**
When adding numeric values the specified OData type is being ignored and instead is inferred.

**To Reproduce**
1. Create test table
2. Insert entity having properties containing numeric values and also specify OData type for them
3. Query the test table (using the REST API, the command line tooling ignores some OData types)

**Expected behavior**
The specified OData type is taken into consideration and there is no inferrence (breaks string properties)

**Environment summary**
Install method: MSI (for Windows)
CLI version: azure-cli (2.0.52)
OS: Windows 10
Shell Type: PowerShell

**Additional context**
Below is the script I used to insert data, follow the REST API documentation for querying an entity: [Table Service REST API / Query Entities](https://docs.microsoft.com/en-us/rest/api/storageservices/query-entities).

```powershell
$connectionString = "storage emulator or actual storage account connection string"
$tableName = "UnexpectedODataTypeTestTable"

# Ensure test table exists
az storage table create,
    --name $tableName,
    --connection-string $connectionString

# Ensure the test entity exists
az storage entity insert,
    --table-name $tableName,
    --entity,
        "PartitionKey=partitionKey",
        "RowKey=rowKey",
        "BinaryProperty=$([Convert]::ToBase64String(@(1, 2, 3)))",
        "BinaryProperty@odata.type=Edm.Binary",
        "Boolean=true",
        "Boolean@odata.type=Edm.Boolean",
        "DateTime@odata.type=Edm.DateTime",
        "DateTime=2018-12-10T20:33:53.4475462Z",
        "Double@odata.type=Edm.Double",
        "Double=1.2",
        "Guid@odata.type=Edm.Guid",
        "Guid=41ddfac7-8f88-4c6c-bc91-a0aa2f036b05",
        "Int32@odata.type=Edm.Int32",
        "Int32=3",
        "Int64@odata.type=Edm.Int64",
        "Int64=4",
        "String=string",
        "String1=5",
        "String2=6.7",
    --if-exists replace,
    --connection-string $connectionString
```

When querying the table (with REST API) I get the following entity (minimal metadata):
```js
{
    "odata.etag": "W/\"datetime'2018-12-10T22%3A26%3A38.3942305Z'\"",
    "PartitionKey": "partitionKey",
    "RowKey": "rowKey",
    "Timestamp": "2018-12-10T22:26:38.3942305Z",
    "BinaryProperty@odata.type": "Edm.Binary", // good
    "BinaryProperty": "AQID",
    "Boolean": true, // good, there's no OData type for boolean, double, int32 and strings
    "DateTime@odata.type": "Edm.DateTime", // good
    "DateTime": "2018-12-10T20:33:53.4475462Z",
    "Double": 1.2, // good, there's no OData type for boolean, double, int32 and strings
    "Guid@odata.type": "Edm.Guid", // good
    "Guid": "41ddfac7-8f88-4c6c-bc91-a0aa2f036b05",
    "Int32@odata.type": "Edm.Int64", // wrong
    "Int32": "3",
    "Int64@odata.type": "Edm.Int64", // good
    "Int64": "4",
    "String": "string", // good, there's no OData type for boolean, double, int32 and strings
    "String1@odata.type": "Edm.Int64", // wrong
    "String1": "5",
    "String2": 6.7 // wrong, this is not a string, expected "String2": "6.7"
}
```

**Comment by williexu** [comment]
@seguler @zezha-msft it looks like the service is not interpreting some of these `odata.type` annotations properly. 
Ex. for `"Int32@odata.type=Edm.Int32", "Int32=3"`, I would assume the odatatype returned to be int32 as it was explicitly provided.

**Comment by zezha-msft** [comment]
@williexu I do not maintain the table SDK. 

Adding @srinathnarayanan to help you with this issue.

**Comment by Andrei15193** [comment]
@williexu I did some digging and I think I have found the source of the bug. It's at [_serialization.py:157](https://github.com/Azure/azure-multiapi-storage-python/blob/master/azure/multiapi/cosmosdb/v2017_04_17/table/_serialization.py#L157) in the multiapi project for CosmosDB.

It looks like there is some kind of `@odata.type` handling but not fully (there's no check if the `@odata.type` was already set), it depends on the order in which properties are handled. Moving the `@odata.type` after the related property should work as a workaround.

**Comment by zhusijia26** [comment]
Work around provided. Close this issue. Please reopen if there is more issue.
