### ISSUE TITLE
2.0.33 is latest version using apt repository

### ISSUE THREAD

**Issue by novaterata** [Azure/azure-cli#8039]
Following the directions for Ubuntu here: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest

And I cannot update azure-cli beyond 2.0.33 (2.0.33-1-xenial specifically)

Why is it stuck at this version?

**Comment by tjprescott** [comment]
Did you run `apt-get update`? We have Xenial packages available for all CLI versions.

**Comment by novaterata** [comment]
Yes

**Comment by novaterata** [comment]
So, for some reason the repository was removed even though I ran the command to add the repository multiple times and that was how it was installed in the first place. I think it might be an issue with "apt" vs "apt-get" in any case it works now.
