### ISSUE TITLE
Alpine Docker Image cannot run CLI if built using Docker for Windows

### ISSUE THREAD

**Issue by marstr** [Azure/azure-cli#8050]
**Describe the bug**

While the default Dockerfile builds and executes successfully when using MacOS, if one uses Docker for Windows, the image that is created has an unusable installation of the Azure CLI.

**To Reproduce**
1. Clone the Azure CLI repository.
1. Navigate to the repository root in a CLI environment.
1. Execute the commands:
  ``` bash
  docker build -t microsoft/azure-cli:alpine .
  docker run microsoft/azure-cli:alpine az --version
  ````

**Expected behavior**
Version information about the CLI and all command modules is reported.

**Environment summary**
OS: Windows
Required Application: [Docker for Windows](https://docs.docker.com/docker-for-windows/install/)

**Comment by marstr** [comment]
This bug discovered by @williexu.

**Comment by tjprescott** [comment]
What is unusable about the image?

**Comment by williexu** [comment]
@tjprescott 
```
bash: /root/.bashrc: line 1: syntax error near unexpected token `$'{\r''
'ash: /root/.bashrc: line 1: `_python_argcomplete() {
bash-4.4# az
': No such file or directory
bash-4.4#
```
