### ISSUE TITLE
Set expiry is not working while creating secret in akv

### ISSUE THREAD

**Issue by lambodar** [Azure/azure-cli#8052]
Hi Team,
As per the document, I tried to set expires while creating the secret but it didn't work. However set-attributes is working fine while updating. Can you please take look.

az keyvault secret set --name &lt;my-key&gt; --value &lt;my-value&gt; --vault-name &lt;my-kv&gt; --expires "2018-12-30T07:28:38Z"

{
  "attributes": {
    "created": "2018-12-13T07:45:37+00:00",
    "enabled": true,
    "expires": null,
    "notBefore": null,
    "recoveryLevel": "Purgeable",
    "updated": "2018-12-13T07:45:37+00:00"
  },
  "contentType": null,
  "id": "https://my-kv.vault.azure.net/secrets/&lt;mykey&gt;/&lt;version&gt;",
  "kid": null,
  "managed": null,
  "tags": {
    "file-encoding": "utf-8"
  },
  "value": "&lt;myvalue&gt;"
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39cfb8ed-c246-2ffb-9dff-070b90c18b21
* Version Independent ID: c09c1597-1b6c-b0a2-b3fc-bdc16764d096
* Content: [az keyvault secret](https://docs.microsoft.com/en-us/cli/azure/keyvault/secret?view=azure-cli-latest#az-keyvault-secret-set)
* Content Source: [src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by lambodar** [comment]
Here is the stackoverflow link for your reference which I asked before raising the request. https://stackoverflow.com/q/53757424/1753177

**Comment by DdenBraver** [comment]
@tjprescott @schaabs Is there any update on this issue yet?
We are running into the exact same issue with azcli version 2.0.70
We require to set an expiration date on creation from our organisation.

**Comment by yugangw-msft** [comment]
I will fix this

**Comment by lambodar** [comment]
I didn't see it working after 1yr. common @msft

**Comment by SharmaRakeshPFE** [comment]
> I will fix this

Is this issue fixed, because I can see still the expired secrets are working.

**Comment by sudhirpandey** [comment]
still is not fixed it seems
az keyvault secret set --vault-name pM-test-nore-xxjn-kv --name "ExamplePassword" --value "hVFkk965BuUv" --expires "2025-12-29T12:00.00Z"
argument --expires: invalid datetime_type value: '2025-12-29T12:00.00Z'

how can you pass datetime_type via cli ?
