### ISSUE TITLE
Azure Function app stops automatically with Orange exclamatory mark

### ISSUE THREAD

**Issue by ThangaPradeep** [Azure/azure-cli#8053]
I have created a Azure function app with two queue triggers. The app runs fine for first 1 hour or so and it stops. Am logging the application error in Azure table. There is no error logged even after it stopped!. 

So I checked the monitor option in queue trigger in portal, whenever it stops there will be orange exclamatory mark present instead of tick. Today along with exclamatory mark I saw another error message in portal. Check the below screenshot 

> The access token expiry UTC time "yyyymmdd" is earlier than current
> UTC time "yyyymmdd"

[![enter image description here][1]][1]

I checked metrics of app service plan(S1) during the same time period of error to check for any resource issues. Looks like on average memory and cpu was utilized around 70% and 90% respectively. 

Note the app service plan is utilized only by this function app.

[![enter image description here][2]][2]

Any ideas why function app is stopping by itself 

After checking in Application Insights --> Application Crashes, I can see there is crash.

![image](https://user-images.githubusercontent.com/16377346/49931513-020e5c80-feed-11e8-9465-b8bb9d6b37ff.png)

In event log I can see this 

>"Worker Process requested recycle due to 'Percent Memory' limit. Memory Used: 2007666688 out of 2147012608 available. Exceeded 90 Percent of Memory" 

[![enter image description here][3]][3]

Should I have to upgrade app service plan ? Code is fairly simple and well optimized! 

  [1]: https://i.stack.imgur.com/DCmwt.png
  [2]: https://i.stack.imgur.com/Dut8I.jpg
  [3]: https://i.stack.imgur.com/ZqCB5.png

**Comment by ahmedelnably** [comment]
Closing this issue, if this is still happening please open a support ticket for investigation
