### ISSUE TITLE
Azure Policy - Improved error message with policy failures during deployments in CLI

### ISSUE THREAD

**Issue by SenthuranSivananthan** [Azure/azure-cli#8058]
**Is your feature request related to a problem? Please describe.**
I would like to see a more descriptive error message when there are errors caused by Azure Policy.

Today, the error message is:

`
Operation failed with status: 'Forbidden'. Details: 403 Client Error: Forbidden for url: https://management.azure.com/subscriptions/xxxxxx-xxxxxxxxx/resourceGroups/test/providers/Microsoft.Storage/storageAccounts/senthuranstg?api-version=2018-03-01-preview
`

However, when running the CLI command in --debug mode, I'm able to see which policy that failed but it's buried.  The information that's useful for troubleshooting is this `/subscriptions/xxxxxx-xxxxxxxxx/providers/Microsoft.Authorization/policyDefinitions/regions`

Full error:

`
{"error":{"code":"RequestDisallowedByPolicy","target":"senthuranstg","message":"Resource 'senthuranstg' was disallowed by policy. Policy identifiers: '[{\"policyAssignment\":{\"name\":\"regions\",\"id\":\"/subscriptions/xxxxxx-xxxxxxxxx/providers/Microsoft.Authorization/policyAssignments/regions\"},\"policyDefinition\":{\"name\":\"regions\",\"id\":\"/subscriptions/xxxxxx-xxxxxxxxx/providers/Microsoft.Authorization/policyDefinitions/regions\"}}]'.","additionalInfo":[{"type":"PolicyViolation","info":{"evaluationDetails":{"evaluatedExpressions":[{"result":"True","expression":"location","path":"location","expressionValue":"eastus","targetValue":["canadaeast","canadacentral"],"operator":"NotIn"}]},"policyDefinitionId":"/subscriptions/xxxxxx-xxxxxxxxx/providers/Microsoft.Authorization/policyDefinitions/regions","policyDefinitionName":"regions","policyDefinitionEffect":"deny","policyAssignmentId":"/subscriptions/xxxxxx-xxxxxxxxx/providers/Microsoft.Authorization/policyAssignments/regions","policyAssignmentName":"regions","policyAssignmentScope":"/subscriptions/xxxxxx-xxxxxxxxx","policyAssignmentSku":{"name":"A0","tier":"Free"}}}]}}
msrest.exceptions : Unable to deserialize to object: type, KeyError: 'TypedErrorInfo'
msrest.exceptions : Operation failed with status: 'Forbidden'. Details: 403 Client Error: Forbidden for url: https://management.azure.com/subscriptions/xxxxxx-xxxxxxxxx/resourceGroups/test/providers/Microsoft.Storage/storageAccounts/senthuranstg?api-version=2018-03-01-preview
`

**Describe the solution you'd like**
I would like the policy name & description to be extracted out and displayed on stdout/stderr.

The message can be

`
Resource 'senthuranstg' was disallowed by policy.
Policy: /subscriptions/xxxxxx-xxxxxxxxx/providers/Microsoft.Authorization/policyDefinitions/regions
`

**Describe alternatives you've considered**
Azure Portal provides this context.

**Additional context**
Steps to reproduce are below.

Create Policy

```json
{
    "if": {
        "field": "location",
        "notIn": [
            "canadaeast",
            "canadacentral"
        ]
    },
    "then": {
        "effect": "deny"
    }
}
```

Deploy Policy

```bash
az policy definition create --name 'regions' --rules limit-regions-to-canada.json --subscription Lab
```

Assign Policy to Subscription

```bash
az policy assignment create --name 'regions' --policy regions --subscription Lab
```

Attempt to create a storage account in US
```bash
az storage account create -g test -n senthuranstg -l eastus --access-tier Hot
```

Run CLI in debug mode to see the full details

```bash
az storage account create -g test -n senthuranstg -l eastus --access-tier Hot --debug
```

**Comment by tjprescott** [comment]
What version of the CLI are you using?

**Comment by SenthuranSivananthan** [comment]
I'm using 2.0.52.

```bash
azure-cli (2.0.52)

acr (2.1.10)
acs (2.3.12)
advisor (2.0.0)
ams (0.3.1)
appservice (0.2.8)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.5)
billing (0.2.0)
botservice (0.1.2)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.4)
command-modules-nspkg (2.0.2)
configure (2.0.19)
consumption (0.4.0)
container (0.3.9)
core (2.0.52)
cosmosdb (0.2.5)
dla (0.2.3)
dls (0.1.6)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.1)
extension (0.2.3)
feedback (2.1.4)
find (0.2.12)
hdinsight (0.1.0)
interactive (0.4.0)
iot (0.3.4)
iotcentral (0.1.4)
keyvault (2.2.8)
lab (0.1.4)
maps (0.3.2)
monitor (0.2.7)
network (2.2.10)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.2)
rdbms (0.3.5)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.1)
resource (2.1.6)
role (2.1.11)
search (0.1.1)
servicebus (0.3.2)
servicefabric (0.1.9)
signalr (1.0.0)
sql (2.1.6)
storage (2.2.6)
telemetry (1.0.0)
vm (2.2.9)

Extensions:
interactive (0.4.1)

Python location '/opt/az/bin/python3'
Extensions directory '/home/senthuran/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Nov 29 2018, 21:51:02)
[GCC 4.8.4]
```

**Comment by tjprescott** [comment]
It should be possible for us to unwrap this error as part of our generic exception handler. @kristapratico please take a look.

**Comment by zhoxing-ms** [comment]
In the latest version of azure-cli, the error messages are already as expected. 
The error message is as follows:
> Resource 'senthuranstg' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"regions","id":"/subscriptions/xxxxxx-xxxxxxxxx/providers/Microsoft.Authorization/policyAssignments/regions"},"policyDefinition":{"name":"regions","id":"/subscriptions/xxxxxx-xxxxxxxxx/providers/Microsoft.Authorization/policyDefinitions/regions"}}]'
 
@SenthuranSivananthan So I close it first, if you still have any other new reuqests, please feel free to feedback.
