### ISSUE TITLE
arm: 'resource show' should work with resource id

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#806]
Per discussion with @tjprescott, we will not continue the xplat's convention, as it has been really hard to use. The improvement will be:
1. `az resource show --id <id>`  should just work w/o any other parameters. This is the most important scenario.
2.  'az resource show --provider-name --parent <parent path> --resource-type <type> --name <name>' should also work. The help for `parent` should call out the format of `parent-resource-type/parent-resource-name`, or `grandparent-resource-type/grandparent-resource-name/parent-resource-type/parent-resource-name`, so on and so on.

**Comment by mayurid** [comment]
@vivsriaus : any updates on this?

**Comment by vivsriaus** [comment]
@mayurid to do this the right way, we need an updated SDK. I just sent a PR for specs [here](https://github.com/Azure/azure-rest-api-specs/pull/548). Once this is merged, I can work on updating the python SDK, and then continue with my updates on the CLI side. I'm hoping to get all these done by EOD tomorrow (9/16)

**Comment by mayurid** [comment]
@vivsriaus and @yugangw-msft : Moving this to Sprin4 as the SDK change is needed.

**Comment by yugangw-msft** [comment]
@vivsriaus, per command review, you will also handle it in `resource delete`

**Comment by yugangw-msft** [comment]
@vivsriaus, also please update `resource show` sample section when you submit PR

**Comment by tjprescott** [comment]
This isn't fixed. Is it part of issue #1033?

**Comment by yugangw-msft** [comment]
Not fixed. i have seen a PR from @vivsriaus. I am fine to fold it into the #!033

**Comment by mayurid** [comment]
I thought the PR was already folded in. Please do so.
