### ISSUE TITLE
`az export container` throws error

### ISSUE THREAD

**Issue by ctstone** [Azure/azure-cli#8068]
**Describe the bug**
Python error is thrown when attempting to export yaml for a container instance

**To Reproduce**
`az export -g {rg} -n {name} -f mycontainer.yaml`

**Expected behavior**
`mycontainer.yaml` is written to local disk

**Environment summary**
- Install Method: brew
- CLI version: azure-cli (2.0.52)
- OS version: macOS 10.14.1
- Shell Type: bash

**Additional context**
Container was created with this:
```bash
az container create \
	--resource-group xxx-yyy \
	--name aa-bb-cc \
	--image mcr.microsoft.com/azure-cognitive-services/luis:latest \
	--cpu 1 \
	--location westus \
	--memory 2 \
	--azure-file-volume-account-name xxx \
	--azure-file-volume-account-key $KEY \
	--azure-file-volume-share-name xx-yy-zz \
	--azure-file-volume-mount-path /input \
	--environment-variables Eula=accept Billing=https://westus.api.cognitive.microsoft.com/luis/v2.0 ApiKey=xxxxx
```

**Comment by ifeoluwaokunoren** [comment]
Hello,

The command should be az container export not az export.
For example: az container export -g MyResourceGroup --name mynginx -f output.yaml

You can find more details here:  https://docs.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest#az-container-export

**Comment by ctstone** [comment]
I suspect I accidentally dropped the `container` command when I typed the issue here. I think running `az export ...` would show an unsupported command message, not a Python exception stack.

Anyway `az container export` is working today for me on CLI 2.0.63, so I am OK if you want to close this issue

**Comment by ifeoluwaokunoren** [comment]
Hi @ctstone,
Thank you for confirming this issue is now resolved.
