### ISSUE TITLE
Can i use blob address?

### ISSUE THREAD

**Issue by raymondhahs** [Azure/azure-cli#8069]
Hi, i just wonder is this  "--cert-file \path\to\new\cert\file"  support azure blob url?  i believe technically yes, but what is the correct syntax?    --cert-file "https:/xxxx " ?  TQ

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67b074ef-2732-8002-ba0e-47534e238c0c
* Version Independent ID: 3b48511d-b007-f938-985f-cc6765d37d45
* Content: [az network application-gateway ssl-cert](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/ssl-cert?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by williexu** [comment]
@tjprescott this is about the `az network application-gateway ssl-cert create` command. From the example, it looks like it simply accepts a local filepath. Does the api accept a blob url?
