### ISSUE TITLE
command: expose global parameter of --subscription-id

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#807]
xplat supports it. 
Not critical, but it is convenient for people to work on other subscriptions for a short while w/o switching the account.
Mentioned at #667.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.

**Comment by JasonRShaver** [comment]
Cleaning up old issues, reopen if this is still active.

**Comment by ppanyukov** [comment]
(copypasta from #5618)

This is pretty important in my book!

-----

The current CLI currently requires this workflow:

```
# set subscription
az account set --subscription <sub_name>

# do az stuff in that sub
az acs login --name ...
```

This makes it very unfriendly and dangerous for scripts and interactive use.

Consider:

1. Long running script sets curernt sub to SubProduction, then does some azure commands.
2. In the meantime user from the terminal, is thinking the commands execute against SubDev issues "delete resource group MyApp". **OOPS**.

If we had `--subscription` as a globa flag, we could have all scripts use that and not interfere with each other.

**Comment by ppanyukov** [comment]
This issue is pretty much 1.5 years old now. Just sayin! Would be great to have this. Please? :)

**Comment by tjprescott** [comment]
To do list:
- [ ] Allow overriding the global parameter
- [ ] Allow suppressing the global parameter
- [ ] Add configurable default
- [ ] Ensure tab completion

**Comment by tjprescott** [comment]
Due to this affecting the entire CLI, I will continue this issue post-Build.
