### ISSUE TITLE
How to create a resource delete lock for a resource group?

### ISSUE THREAD

**Issue by theheatDK** [Azure/azure-cli#8071]
Hi,
I cannot figure out how to create a delete lock for a resource group. In AzureRm it is simple:
`New-AzureRmResourceLock -ResourceGroupName $MyRg -LockName $MyLockName -LockLevel CanNotDelete
`

When I try to do the same in Az Cli (2.0.52) it fails.
```
az resource lock create --lock-type CanNotDelete \
                         --name 'delete lock' \
                         --resource-group "$RESOURCEGROUP_NAME"
Missing required resource_name parameter.

az resource lock create --lock-type CanNotDelete \
                        --name 'delete lock' \
                        --resource-group "$RESOURCEGROUP_NAME" \
                        --resource "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCEGROUP_NAME"
--resource-type is required if the name, --resource, is present

az resource lock create --lock-type CanNotDelete \
                         --name 'delete lock' \
                         --resource-group "$RESOURCEGROUP_NAME" \
                        --resource "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCEGROUP_NAME"
                         --resource-type resourceGroup
A resource namespace is required if the name, --resource, is present.Expected <namespace>/<type> or --namespace=<namespace>

```
What am I missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58e53ca7-36a6-8200-ea38-411cbb05f570
* Version Independent ID: 4932042b-6e49-5773-8e05-802ca9da1c29
* Content: [az resource lock](https://docs.microsoft.com/en-us/cli/azure/resource/lock?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
The simplest way is to use `az group lock create`.  You could also use the generic `az lock create` but `az resource lock create` is *only* for locking resources, not subscriptions or resource groups.

**Comment by ausfestivus** [comment]
I just wasted an hour trying to understand why this didn't work:

```bash
😱 abest@BARMIX2:~ $ az resource lock create --lock-type CanNotDelete --name prevent-delete --resource-group bes067sdp-rg
Missing required resource_name parameter.
```

This documentation needs updating. Considering the age of this issue as well thats a poor user experience.

**Comment by zhoxing-ms** [comment]
@ausfestivus In fact, the lock related commands describe the scope which they support in help, please add parameter `-h` to the commands to see these instructions:

```pwsh
(env) PS D:\project> az resource lock create -h

Command
    az resource lock create : Create a resource-level lock.

Arguments
    --lock-type -t  [Required] : The type of lock restriction.  Allowed values: CanNotDelete,
                                 ReadOnly.
    --name -n       [Required] : Name of the lock.
    --notes                    : Notes about this lock.
    --resource-group -g        : Name of resource group. You can configure the default group using
                                 `az configure --defaults group=<name>`.
...
```
```
(env) PS D:\project> az group lock create -h

Command
    az group lock create : Create a resource group lock.
...
```
```
(env) PS D:\project> az lock create -h

Command
    az lock create : Create a lock.
        Locks can exist at three different scopes: subscription, resource group and resource.
...
```
