### ISSUE TITLE
az cli not able to change licensetype to None in windows

### ISSUE THREAD

**Issue by StellaZhou64** [Azure/azure-cli#8072]
**Describe the bug**
az cli not able to change licensetype to None in windows. I tried below two command in windows powershell, but neither worked.
az vm update --resource-group testclassicVM --name testLicense --remove licenseType
az vm update --resource-group testclassicVM --name testLicense --set licenseType="None"

However, below command worked find in Linux.
az vm update --resource-group testclassicVM --name testLicense --set licenseType=\"None\"

**To Reproduce**
Steps to reproduce the behavior.
1. Create a VM using Azure hybrid benefit.
2. Use below two commands to convert the licensetype to null. But it won't change anything.
az vm update --resource-group testclassicVM --name testLicense --remove licenseType
az vm update --resource-group testclassicVM --name testLicense --set licenseType="None"

**Expected behavior**
az cli command should work to set licensetype to null in windows environment.

**Environment summary**
PS C:\Users\jieyzhou\Desktop> az --version
azure-cli (2.0.34)

acr (2.0.26)
acs (2.0.34)
advisor (0.5.1)
ams (0.1.1)
appservice (0.1.33)
backup (1.1.1)
batch (3.2.3)
batchai (0.2.3)
billing (0.1.8)
cdn (0.0.14)
cloud (2.0.13)
cognitiveservices (0.1.13)
command-modules-nspkg (2.0.1)
configure (2.0.15)
consumption (0.3.1)
container (0.1.24)
core (2.0.34)
cosmosdb (0.1.21)
dla (0.1.0)
dls (0.0.21)
dms (0.0.1)
eventgrid (0.1.12)
eventhubs (0.1.3)
extension (0.0.14)
feedback (2.1.1)
find (0.2.9)
interactive (0.3.21)
iot (0.1.21)
keyvault (2.0.22)
lab (0.0.22)
maps (0.1.0)
monitor (0.1.7)
network (2.1.3)
nspkg (3.0.2)
policyinsights (0.1.0)
profile (2.0.25)
rdbms (0.2.3)
redis (0.2.13)
reservations (0.1.2)
resource (2.0.30)
role (2.0.24)
servicebus (0.1.2)
servicefabric (0.0.12)
sql (2.0.27)
storage (2.0.34)
vm (2.0.33)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\jieyzhou\.azure\cliextensions'

Python (Windows) 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Would you please help? Thanks a lot.

**Comment by StellaZhou64** [comment]
Correction:

command below works for Linux
az vm update --resource-group testclassicVM --name testLicense --set licenseType=\\"None\\"

**Comment by StellaZhou64** [comment]
Using latest az cli, still didnot work.

**Comment by adewaleo** [comment]
Try either of the following:
```
az vm update --resource-group testclassicVM --name testLicense --license-type None 
az vm update --resource-group testclassicVM --name testLicense \
      --set licenseType="None" --force-string
```
The CLI parses "None" or "null" as a null type and not as a string. --force-string remedies this.
