### ISSUE TITLE
How can I check the images size in the acr repository ? 

### ISSUE THREAD

**Issue by akramwaseem** [Azure/azure-cli#8077]
Hi, Is there a command to check the size of all the images or repositories in ACR ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94aa298e-2dd2-7140-c71a-4214be845051
* Version Independent ID: 0e8da3c9-380f-2864-4ba6-1a8e113448d6
* Content: [az acr repository](https://docs.microsoft.com/en-us/cli/azure/acr/repository?view=azure-cli-latest#az-acr-repository-list)
* Content Source: [src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by djyou** [comment]
You may use the following command for usage/quota information related to your registry
```
>az acr show-usage -n MyRegistry
{
  "value": [
    {
      "currentValue": 3011,
      "limit": 536870912000,
      "name": "Size",
      "unit": "Bytes"
    },
    {
      "currentValue": 0,
      "limit": 100,
      "name": "Webhooks",
      "unit": "Count"
    }
  ]
}
```

**Comment by akramwaseem** [comment]
@djyou --Thanks for the info.
How about the size of a image stored in the registry or Size of all the images in a registry ?
I think you misunderstood the question, if I need the size of the registry I can access it from the azure portal, but I dont see the option to see the size of a docker image apart from pulling it and checking the size.

**Comment by djyou** [comment]
The size you see in Azure Portal or with `az acr show-usage` is the size of all the images in a registry. We don't have support for each image size at this point, which can be obtained from pulling the image as you suggested. /cc @sajayantony

**Comment by akramwaseem** [comment]
@djyou  -- can you try and add this to the feature list.
That would be great.

**Comment by sajayantony** [comment]
@akramwaseem do you think, could you please open an issue under https://github.com/Azure/acr
We track items on that.

**Comment by Leonardo-Ferreira** [comment]
can I get a breakdown of the total usage by repository?

**Comment by Nastaliss** [comment]
@Leonardo-Ferreira in case you still need it, I needed the same thing. You'll need to have `jq` installed
I wrote a small bash script that does the job : 
```bash
repositories=$(az acr repository list)
while read -r repository; do
	repository_size=$(az acr manifest list-metadata --only-show-errors -r "$ACR_NAME" --name "$repository" | jq 'reduce .[].imageSize as $size (0; .+$size)')
	echo "$repository: $(numfmt --to iec --format "%8.4f" "$repository_size")"
done < <(echo "$repositories" | jq -rcM ".[]")
```

**Comment by TiloGit** [comment]
see https://github.com/Azure/acr/issues/169
