### ISSUE TITLE
Misleading command descriptions

### ISSUE THREAD

**Issue by rohancragg** [Azure/azure-cli#8095]
The descriptions of what these command do is very misleading. The Powershell equivalent docs are much more helpful - please align them to be more consistent.

For example:

Powershell cmdlet `Remove-AzKeyVaultManagedStorageAccount`:
https://docs.microsoft.com/en-gb/powershell/module/az.keyvault/remove-azkeyvaultmanagedstorageaccount?view=azps-1.0.0

says:

> Removes a Key Vault managed Azure Storage Account and all associated SAS definitions.

CLI equivalent:
https://docs.microsoft.com/en-us/cli/azure/keyvault/storage?view=azure-cli-latest#az-keyvault-storage-remove

says:

> Deletes a storage account.

To my mind, this implies that the Storage Account resource will be deleted which is definitely not what happens!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2d724c9-6606-2a86-b8e8-43c01b1a42e1
* Version Independent ID: 22c38bcb-78d6-9347-00e7-86f56b2674df
* Content: [az keyvault storage](https://docs.microsoft.com/en-us/cli/azure/keyvault/storage?view=azure-cli-latest#az-keyvault-storage-remove)
* Content Source: [src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@jiasli  add to S162.

**Comment by VamsiSangam** [comment]
Since this has been fixed in code, shouldn't the `good first issue` tag be removed?... Or better yet, shouldn't the issue be closed?
