### ISSUE TITLE
cert_file=$(echo $service_principal | jq .fileWithCertAndPrivateKey -r)

### ISSUE THREAD

**Issue by SyntaxGeek** [Azure/azure-cli#8096]
This assumes you have jq installed in the environment, which azure cli tools doesn't depend on natively.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9c661d7-bf43-5354-015e-3859f30a42a2
* Version Independent ID: fa69e552-5904-ce97-d02c-915c819bdde1
* Content: [az keyvault certificate](https://docs.microsoft.com/en-us/cli/azure/keyvault/certificate?view=azure-cli-latest#az-keyvault-certificate-create)
* Content Source: [src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
This is true, but the CLI is designed to work with other tools. I wouldn't say it is inappropriate to illustrate via examples how that can be accomplished. 

Do you have a recommendation for what you think should be changed here?

**Comment by SyntaxGeek** [comment]
> This is true, but the CLI is designed to work with other tools. I wouldn't say it is inappropriate to illustrate via examples how that can be accomplished.
> 
> Do you have a recommendation for what you think should be changed here?

I think that's a fair point - I just felt like it deserved a callout prior to the example code given to understand what "jq" is and that it isn't a Microsoft tool.  I expect most veterans will have familiarity with jq, but not all.

All in all not really an "issue" 👍

**Comment by yonzhan** [comment]
add to S164.

**Comment by bim-msft** [comment]
@SyntaxGeek Yea, you are right, `jq` is not a Azure-CLI dependency so it's not installed automatically. But the scope of documents is much larger, using some independent uninstalled packages/tools is not harmful to tutorial.
Anyway, thanks for the information!

**Comment by bim-msft** [comment]
Issue closed, if you have anything unresolved, feel free to reopen and ask me again, thanks!
