### ISSUE TITLE
Add provisionAfterExtensions support in CLI

### ISSUE THREAD

**Issue by sirajudeens** [Azure/azure-cli#8101]
**Describe the bug**
CLI needs to updated to include the new property "provisionAfterExtensions" introduced in VMSS Extension.

The corresponding github url: https://github.com/Azure/azure-rest-api-specs/pull/4306

**To Reproduce**
Try adding extension sequencing for VMSS extensions in CLI

**Expected behavior**
CLI should expose the new property "provisionAfterExtensions" to enable customer to define extension sequencing in VMSS.

**Environment summary**
Nil

**Additional context**
Nil

**Comment by yugangw-msft** [comment]
@adewaleo, let us start the work in Jan. We will need a new Compute SDK for this from @lmazuel

**Comment by lmazuel** [comment]
See https://github.com/Azure/azure-sdk-for-python/pull/3668 for the candidate SDK
