### ISSUE TITLE
Azure Disk Encryption not allowing KV and VM in different RG with just KV name

### ISSUE THREAD

**Issue by AdamSharif-MSFT** [Azure/azure-cli#8110]
I've been testing Azure Disk Encryption following an issue raised - it appears that when a Key Vault and VM are in a different Resource Group (confirmed same subscription, same region, access for ADE enabled at KV), when the encryption commands are executed via Azure CLI with just the key vault name, encryption proceeds but the secrets are not written to the Key Vault.
No error is displayed in the command line, but secrets are missing and so when VM is stopped/deallocated, and started back up, access to encrypted volume is enabled.

Example:

az vm encryption enable --resource-group <rgname> --name testvm-diffrg --disk-encryption-keyvault <kvname> --key-encryption-key <keyname> --volume-type data

If, however, resource groups are different and the full path to the Key Vault is used, encryption again succeeds, but this time the secret is created and the access to the encrypted volume persists across stop/deallcoate and starts.

Example:

az vm encryption enable --resource-group newrg --name <rgname>--disk-encryption-keyvault /subscriptions/<subid>/resourceGroups/<rgname>/providers/Microsoft.KeyVault/vaults/<kvname>--key-encryption-key <keyname> --volume-type data

There are two issues here:

1. Az CLI should report back if it can't write the key, and encryption should not proceed
2. Documentation does not make it clear that the full path needs to be used if the RG differs (if the RG is the same for VM and KV, just the short KV name can be used for the --disk-encryption-keyvault parameter, and the secrets are successfully written to the KV).

**Comment by AdamSharif-MSFT** [comment]
Looks like #4318 mentioned a similar issue but it still seems to be present

**Comment by tjprescott** [comment]
That you cannot simply provide the name when the resources are in different resource groups is by design and is a pattern used throughout the CLI.

**Comment by johanburati** [comment]
@tjrescott It really does not make sense to go through the encryption if the short KV name is provided since that will result in a VM that does not boot after redeployment.

The CLI should catch this and throw an error, it should not go through with the encryption.
