### ISSUE TITLE
azure Key Vault:how do delete latest version of secret using Azure CLI

### ISSUE THREAD

**Issue by abhiramani-iptiq** [Azure/azure-cli#8114]
Azure Key Vault:how do delete latest version of secret using Azure CLI

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by tjprescott** [comment]
`az keyvault secret delete -h`

```
    az keyvault secret delete : Deletes a secret from a specified key vault.
        The DELETE operation applies to any secret stored in Azure Key Vault. DELETE cannot be
        applied to an individual version of a secret. This operation requires the secrets/delete
        permission.
```

**Comment by abhiramani-iptiq** [comment]
any plans to give this functionality using Azure CLi.because we can delete specific versions using web interface?

**Comment by tjprescott** [comment]
@schaabs

**Comment by schaabs** [comment]
@abhiramani-iptiq Key Vault does not support deleting specific versions of secrets by any means.  Even in the portal if you select a specific version and click delete, it will still prompt that it will delete all versions.

![image](https://user-images.githubusercontent.com/11322348/50607877-a4cc5200-0e7f-11e9-8d9d-bbdaeed3e6d5.png)

**Comment by schaabs** [comment]
There are no plans to support deletion of individual versions of a secret at this time.

**Comment by jjxtra** [comment]
Can you explain why there are no plans to allow cleaning out old and no longer used secrets?

**Comment by PauloPaixao** [comment]
Keeping old versions of secrets stored can even be a security issue.

**Comment by jcwchen** [comment]
Looking forward to a concrete explanation and solution for it from 2021... It makes no sense why we cannot remove those deprecated secrets.

**Comment by tomwarner13** [comment]
This seems like an obvious feature which has several useful applications -- for example, if credentials accidentally got entered into the wrong field where they are available to users who should not have access to them. Right now, the only workaround is to delete the entire secret (all versions) and then recreate it. I agree that the Azure team should provide a specific explanation for why they refuse to implement this request.

**Comment by ma185360** [comment]
@schaabs Any update on this one. Are you guys re-considering this request?

**Comment by JoeBigToe** [comment]
Upvote. This feature seems obvious given that you can access different versions of a secret.
I planned a solution to sync KV secret rotation and deleting the last version would be very handy as a rollback operation in case the synchronization failed.

**Comment by petemantai** [comment]
Almost 4 years later and this is still an issue.  WHY hasn't this been addressed yet?

**Comment by luigibrancati** [comment]
Still an issue

**Comment by InterpolationStation** [comment]
Use import as a workaround. Download the previous version you wish to make "current", then import it.

**Comment by petemantai** [comment]
> Use import as a workaround. Download the previous version you wish to make "current", then import it.

That is not a work around.  You can't remove the old secrets unless you completely delete the cert entry and enter it again.

**Comment by sajalgolas-path** [comment]
We need this feature to permanently delete the old version of the secret. Not sure, its been so long why it is not addressed yet ?

**Comment by Swaps76** [comment]
in my case, I accidentally created a new version using the wrong value and my only option now is to disable the wrong version or create a new version with the correct value.  Ideally I just want to delete the wrong version only.. but as I can see this is not possible.  Upvote to have this functionality.

**Comment by matolink** [comment]
mid 2023 and still not addressed

**Comment by keunsoopark** [comment]
end 2023. we are still waiting

**Comment by GaelanMines** [comment]
Honestly, Microsoft should be embarrassed at this point. Why even have versioning if it's just a means for cruft to collect? Honestly, who is making these decisions? Can we send them back to whatever non-technical role they came from?

**Comment by calzakk** [comment]
nearly mid 2024 and still not addressed, this issue was raised 5½ years ago!

**Comment by petemantai** [comment]
> Based on my experience, setting a key to being disabled, removes the possibility of "Get"ting it nor recovering it, effectively purging the secret version. But, do correct me if I'm wrong.

Here is another major issue without the ability to delete certificates from the keyvault entry - There are times when a junior admin uploads a new certificate into the incorrect certificate listing in the keyvault, for example, they upload the certificate for example.com into the test.com keyvault entry.  Now when using things like Azure Front Door, AFD will automatically try to use the latest certificate and if that certificate that was incorrectly uploaded is the newest certificate, AFD will continue to try to use that cert if possible.  If you disable that cert, AFD will show that the keyvault is inaccessible.  Microsoft NEEDS to make a way to be able to delete these certificates besides having to delete the entire entry and recreate it.

**Comment by joluizquierdo** [comment]
Early 2025, still waiting for this feature...

**Comment by LGNorris** [comment]
Mid 2025, still waiting for this feature...

**Comment by Liyongchao321** [comment]
Almost end of 2025, still waiting for this feature...

**Comment by rxaveri** [comment]
2026 - it would be nice to have this feature.

**Comment by salimdhahri** [comment]
2026 - still waiting.

**Comment by DL444** [comment]
One of the implications of the lack of history delete feature is that once a secret accumulates more than 500 past versions, it can no longer be backed up. [Doc](https://learn.microsoft.com/en-us/azure/key-vault/general/backup):
> Key Vault does not support the ability to backup more than 500 past versions of a key, secret, or certificate object, and attempting to do so may result in an error. It is not possible to delete previous versions of a key, secret, or certificate.
