### ISSUE TITLE
Azure CLI | Unable to Log-in to Azure Command Line Interface (CLI)

### ISSUE THREAD

**Issue by mscss** [Azure/azure-cli#8124]
root@xxxxxxx:~# sudo apt-key --keyring /etc/apt/trusted.gpg.d/Microsoft.gpg adv --keyserver packages.microsoft.com --recv-keys BC528xxxxxx9D3721CEB3E94ADBE1229CF

Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.ERck6qSOVm --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg.d/Microsoft.gpg --primary-keyring /etc/apt/trusted.gpg.d/Microsoft.gpg --keyserver packages.microsoft.com --recv-keys BC528686xxxxxx1CEB3E94ADBE1229CF

gpg: requesting key BE1229CF from hkp server packages.microsoft.com

gpg: key BExxx29CF: public key "Microsoft (Release signing) <xxxxxx@microsoft.com>" imported

gpg: Total number processed: 1

gpg:               imported: 1  (RSA: 1)

root@xxxxxxx:~# sudo -u makecert -H az login

To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code Axxxx2SQ to authenticate.

Unexpected polling state invalid_grant

Customer Time zone is UTC+2 and within Microsoft. I have already let him to log in as debug mode and get the trace on chrome. Please let me know if we need any information.

**Comment by adewaleo** [comment]
@mscss, you should scrub any sensitive information in your issue comment.

**Comment by yugangw-msft** [comment]
@mscss, are you working with an internal or external customer? `invalid_grant` usually happens on internal MS users who are in the AAD insider ring.

**Comment by marstr** [comment]
I'm going to close this issue as stale. If @yugangw-msft's guess is wrong, and this isn't an AAD insider from Microsoft tenant, I'll open it back up.

**Comment by DavidBurela** [comment]
I'm a MSFT employee, when I use `az login` I am getting `Unexpected polling state invalid_grant`.
As far as I know, I never opted into AAD insider ring.

Any way to debug this?

**Comment by jiasli** [comment]
@DavidBurela, are you logging in with device code? Please run with `--debug` and share the output. Let's discuss via Outlook or Teams.

**Comment by jiasli** [comment]
As discussed offline, you are using device code login with **Windows Hello** which may not be well supported by AAD or Microsoft IT configuration. In the browser, please use normal **username + password + PIN / phone auth / smart card** to login.
