### ISSUE TITLE
Deploying a data factory ARM template from command line failed

### ISSUE THREAD

**Issue by brentd-smith** [Azure/azure-cli#8129]
**Describe the bug**
Deploying a ARM data factory template fails when using the azure-cli but succeeds when switching back to powershell. 

**To Reproduce**
Tried to deploy a simple data factory via the command line after a portal deployment using "edit your own template" feature worked.

CLI command:
```
cd templates
az deployment create -l EastUS --template-file my-template.json --parameters @parameters.json
	
```	

Powershell command worked: 
```
New-AzureRmResourceGroupDeployment -Name MyARMDeployment -ResourceGroupName my-resource-group -TemplateFile templates/my-template.json -TemplateParameterFile templates/parameters.json		
```

**Expected behavior**
I expected the data factory to be deployed into the default resource group, but instead received the error below:
```
Deployment failed. Correlation ID: aaaaa-bbbb-ccc-ddddd. {
	  "error": {
			"code": "ResourceNotFound",
			"message": "The Resource 'Microsoft.DataFactory/factories/myDataFactoryDeployedFromQS01' under resource group '<null>' was not found."
	  }
}
```

**Environment summary**
azure-cli (2.0.53)
Cloud Shell

**Additional context**
Seems that the data factory template has no place to include the resource group, but the deployment process requires the resource group for a successful deployment.

Thanks.

**Comment by tjprescott** [comment]
`az deployment create` is for creating subscription-level deployments. The command that corresponds to the Powershell command you gave is `az group deployment create`.
