### ISSUE TITLE
Network Watcher flow-log -- add support for traffic analytics

### ISSUE THREAD

**Issue by zwswim** [Azure/azure-cli#8132]
**Is your feature request related to a problem? Please describe.**
Add code to support the new property “TrafficAnalyticsInterval”  in network contract TrafficAnalyticsConfigurationProperties

here is the PR for swagger: https://github.com/Azure/azure-rest-api-specs/pull/4420/files

**Describe the solution you'd like**
Please update flow-log configure/show to handle the new property “TrafficAnalyticsInterval”.

For “az network watcher flow-log configure”, user could set the optional property "TrafficAnalyticsInterval" when the TrafficAnalytics is enabled.

For “az network watcher flow-log show”, NRP/ARM will return the TrafficAnalyticsInterval if TrafficAnalytics is enabled.

**Describe alternatives you've considered**
I did not find the document how the CLI support "TrafficAnalytics".  Let me know if you need more information

Here is how Powershell support the flowAnalyticsConfiguration: https://docs.microsoft.com/en-us/powershell/module/az.network/set-aznetworkwatcherconfigflowlog?view=azps-1.0.0
You can search following keywords:
-  EnableTrafficAnalytics 
- Workspace 
- TrafficAnalyticsInterval 

**Additional context**
my Microsoft email:  wezheng@microsoft.com

**Comment by tjprescott** [comment]
Will open a PR to enable Traffic Analytics. For this specific features, minimum API version is 2018-12-01, for which no SDK is available. Moving to the backlog.
