### ISSUE TITLE
unable to pass service principal password stored in vault for az aks create --client-secret parameter

### ISSUE THREAD

**Issue by hectoralicea** [Azure/azure-cli#8133]
**Describe the bug**
Unable to pass service principal password stored in the vault for az aks create --client-secret parameter

**To Reproduce**
1.) create a vault
```
az keyvault create \
	--name ${AZURE_VAULT_NAME} \
	--resource-group ${AZURE_RESOURCE_GROUP} \
	--location ${AZURE_LOCATION} \
	--enabled-for-deployment 'true'

```
2.) create service principal account using vault
```
az ad sp create-for-rbac \
	--skip-assignment \
	--name ${AZURE_SERVICE_PRINCIPAL_NAME} \
	--create-cert \
	--cert ${AZURE_VAULT_SERVICE_PRINCIPAL_KEY_NAME} \
	--keyvault ${AZURE_VAULT_NAME}
```

3.) output to az ad sp create shows as 
```
{
  "appId": "xxxxxxx",
  "displayName": "aksServicePrincipalPOC",
  "name": "http://aksServicePrincipalPOC",
  "password": null,
  "tenant": "xxxxxxx"
}
```
Note password is null.

4.) create aks cluster using service principal.  There does not appear to be a way to pass the secret or vault name for the az aks create command.  I have no value to set --client-secret since it was not returned when creating a service principal account.

```
az aks create \
	--resource-group ${AZURE_RESOURCE_GROUP} \
	--name ${AKS_CLUSTER_NAME} \
	--admin-username ${AKS_NODE_ADMIN_USERNAME} \
	--node-count ${AKS_MIN_NUMBER_OF_NODES} \
	--service-principal ${AZURE_SERVICE_PRINCIPAL} \
	--client-secret ??????????? \
	--ssh-key-value ${AKS_VM_SSH_KEY_FILE_DIR}/${AKS_VM_SSH_KEY_FILE_NAME}.pub \
	--network-plugin azure \
	--vnet-subnet-id ${AZURE_PRIVATE_SUBNET_ID} \
	--docker-bridge-address ${AZURE_AKS_DOCKER_BRIDGE_ADDRESS} \
	--dns-service-ip ${AZURE_AKS_DNS_SERVICE_IP} \
	--service-cidr ${AZURE_AKS_SERVICE_CIDR}
```

**Expected behavior**
There should be an option with az aks create to have it pull the service principal password from the vault maintaining that secret.

**Environment summary**
Install Method (using Mac.  Forgot maybe brew?)
CLI version (`az --version`) azure-cli (2.0.44) /
OS version MacOS Mojave 10.14.2 
Shell Type (bash 4.x)  

Any workarounds?  Such as creating SP without vault then add the secret password to the vault?

**Comment by mohoff** [comment]
I'm having the same issue/question.

@hectoralicea Were you able to solve this? If so, how?

**Comment by hectoralicea** [comment]
I was not able to solve this.  I think I just worked around it by keeping a copy of the SP account password and then passing into the AKS create.  Which defeats the purpose of using a vault for services to pull SP account password from vault rather than having to pass it around.

**Comment by RakeshMohanMSFT** [comment]
Please go through this. https://github.com/Azure/azure-cli/issues/13026
