### ISSUE TITLE
Cleanup for extensions which are removed/uninstalled

### ISSUE THREAD

**Issue by ishitam8** [Azure/azure-cli#8134]
**Is your feature request related to a problem? Please describe.**
Our extension creates and stores some configurations by creating a folder in config directory of azure CLI. So, a folder called <extension_name> is created in $HOME/.azure  directory.
When user triggers the command 'az extension remove -n  <extension_name>' , we would like to delete the folder created in config directory as well.

Currently, remove extension command doesn't seem to do this. I can see that it removes the extension_name folder from 'cliextensions' directory.

Is there a way to clear extension specific configs before removing the extension?

**Comment by yonzhan** [comment]
@zikalino  add to S162.

**Comment by haroldrandom** [comment]
Can't reproduce, since https://github.com/Azure/azure-cli/pull/7653 has made the change to remove extension.

I can remove the extension dir, maybe you are runing on a older version azure-cli before this PR release?

Feel free tor reop if I was wrong.
