### ISSUE TITLE
Unable to update WebTest content in Availability test using Azure CLI

### ISSUE THREAD

**Issue by Relgon** [Azure/azure-cli#8135]
---
I have Availability test resource named "sla-live-myproject" which contains multistep web test. I want to configure CD using Azure DevOps to update this test on each change in code. I try to use Azure CLI task in release pipeline to do it. 

Using `az resource show` I get details of this resource:
`az resource show -g $ResoruceGroupName -n $ResourceName --resource-type Microsoft.Insights/webtests`
I have received the next response
```json{
  "etag": "\"51016086-0000-0000-0000-5c29c1fd0000\"",
  "id": "/subscriptions/{guid}/resourceGroups/myproject-log/providers/microsoft.insights/webtests/sla-webapi-live-myproject",
  "identity": null,
  "kind": null,
  "location": "westeurope",
  "managedBy": null,
  "name": "sla-webapi-live-myproject",
  "plan": null,
  "properties": {
    "Configuration": {
      "WebTest": "**Xml with my test, uploaded manualy using portal**"
    },
    "Description": "Availability-api.webtest",
    "Enabled": true,
    "Frequency": 300,
    "Kind": "multistep",
    "Locations": [
      {
        "Id": "emea-nl-ams-azr"
      },
      {
        "Id": "emea-ru-msa-edge"
      },
      {
        "Id": "emea-se-sto-edge"
      },
      {
        "Id": "emea-gb-db3-azr"
      },
      {
        "Id": "emea-ch-zrh-edge"
      },
      {
        "Id": "emea-fr-pra-edge"
      }
    ],
    "Name": "sla-webapi",
    "RetryEnabled": true,
    "SyntheticMonitorId": "sla-webapi-live-myproject",
    "Timeout": 120,
    "provisioningState": "Succeeded"
  },
  "resourceGroup": "myproject-log",
  "sku": null,
  "tags": {
    "hidden-link:/subscriptions/guid/resourceGroups/myproject-log/providers/microsoft.insights/components/live-myproject": "Resource"
  },
  "type": "microsoft.insights/webtests"
}
```
Next I want to update property `properties.Configuration.WebTest` and set the updated XML test
`az resource update -g $ResoruceGroupName -n $ResourceName --resource-type "microsoft.insights/webtests"  --set properties.Configuration.WebTest="<WebTest>{Content of web test}</WebTest>"`, but I got the next error
`Operation failed with status: 'Bad Request'. Details: Bad Request`.
What I do wrong? Is it my mistake or a possible bug in cli?
If it is my mistake, I think it can be good to make more informative response than simple "Bad Request" message.

**Comment by tjprescott** [comment]
You can run the command with `--debug` to see what is actually sent on the wire. It is possible that a special character is being interpreted by the shell and resulting in a broken input.

**Comment by Relgon** [comment]
When I used this command with `--debug` parameter I also received the same response content with minimum information in it...
`msrest.http_logger : {"code":"BadRequest","message":"Bad Request","innererror":{"diagnosticcontext":"bc8b32b6-0e7b-11e9-9d81-3497f63385af","time":"2019-01-02T10:47:06.5458729Z"}}`
What about special characters escaping, I've tried to use the xml string returned by `az resource show` without any changes or with minimal changes ( changed url, etc) as well. `az resource show`  returns the xml with escaped special characters.

**Comment by tjprescott** [comment]
Bad Request is returned from the service, and using the generic `resource update` method, there is no way for the CLI to know what you are trying to do. It is almost certainly some kind of quoting or escaping issue with your input. If you are still having issues, please reopen.
