### ISSUE TITLE
no az container start and restart doesn't work on stopped container

### ISSUE THREAD

**Issue by myusrn** [Azure/azure-cli#8136]
**Describe the bug**
There is currently no `az container start -g <resource group name> -n <container groups/instances name>` action support and executing `az container start -g <resource group name> -n <container groups/instances name>` generates error `Container Group '<container groups/instances name>' in resource group '<resource group name>' is stopped` if used against container that is not already running.

**To Reproduce**
1.  create azure container group/instances resource
2.  stop resource using either portal UI or `az container stop -g <resource group name> -n <container groups/instances name>` command
3.  attempt to restart instance using `az container restart -g <resource group name> -n <container groups/instances name>` at which point it unexpectedly says generates error `Container Group '<container groups/instances name>' in resource group '<resource group name>' is stopped` if used against container that is not already running.

**Expected behavior**
I expect restart command to start container even if it is currently stopped OR better still provide semantically more relevant `az container start . . . ` action support.

**Environment summary**
Install Method = msi from https://aka.ms/installazurecliwindows / CLI version = azure-cli (2.0.54) / OS version = windows 10.0.17763.195 [ 1809 ] / Shell Type = cmd.exe

**Additional context**
n/a

**Comment by SDubrulle** [comment]
I'm experiencing the same issue, not able to restart a stopped container from the CLI. Any suggestions on how to solve this?

**Comment by DibranMulder** [comment]
I'm also experiencing this. Its causing me unnecessary costs.
