### ISSUE TITLE
az vm stop - info about stopping without deallocating

### ISSUE THREAD

**Issue by darthkurak** [Azure/azure-cli#8137]
Issue described here:
https://github.com/Azure/azure-cli/issues/3026
Would be great to have this documentation to be line with above fix.
Warning about missed deallocation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 152b549b-d4b3-13e5-081c-c604b6e4d89e
* Version Independent ID: 3f79be78-ce75-ad31-304b-bad7d475ec9e
* Content: [az vm](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by adewaleo** [comment]
The changes you are requesting have already been made. See [here](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py#L1226), for example. The help for the CLI was updated as part of the merged PR above. The changes in that PR will be reflected in the next release of the CLI (January 15). The online documentation will be updated around the release as well.
