### ISSUE TITLE
Installing azure-cli leads to installing built-in packages into a wrong directory

### ISSUE THREAD

**Issue by wvxvw** [Azure/azure-cli#8138]
Before installing `azure-cli`:

```
python3 -c 'import concurrent;print(concurrent.__path__)'
```

Will give you `/usr/local/lib/python3.7/concurrent/__init__.py`

After, installing `azure-cli` it will give you: `/usr/local/lib/python3.7/site-packages/concurrent/__init__.py`.

I have no idea how did you manage to screw this up so badly, and, in part this must be the `setuptools` fault that it was coerced into doing this.  The heinous thing about it is that it installs the Python v2 version of `concurrent` library, and no code that uses Azure CLI no longer works because of syntax errors.

PS. It also installs a v2 version of `ipaddress.py` built-in module...

**Comment by tjprescott** [comment]
How did you install the CLI?

**Comment by wvxvw** [comment]
pip install azure-cli

**Comment by tjprescott** [comment]
I am not able to repro this issue. On both OSX and Windows, running `python3 -c 'import concurrent;print(concurrent.__path__)'` yielded the same path before and after installing the CLI.

There is a reason we don't list `pip install` as a recommend method on our installation page:
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest

We recommend using the packaged installers appropriate for your system. The ways in which pip can fail spectacularly are independent of the CLI and if you do wish to pip install the CLI directly, we strongly advise that you do so within a virtual environment.

As I cannot repro the issue, I will close this.

**Comment by wvxvw** [comment]
Then why do you keep uploading your stuff to pypi?

Just remove it from there: and I can in good consciousness tell my
employer that your garbage doesn't work and move on.

Besides, who needs your single experiment on systems nobody cares
about? Why don't you test it on AIX for greater effect?

What you have to do, is test on a system, which is most likely to be
used for automation, and on about two dozens of versions of pip and
setuptools. Run it multiple times, because both tools are flaky, and
only THEN you may have enough confidence to tell me that the problem
doesn't exist.
