### ISSUE TITLE
 Error in example for "az webapp config storage-account add"

### ISSUE THREAD

**Issue by spitzfaust** [Azure/azure-cli#8150]
The `--type` parameter that is used in the example should probably be `--storage-type` or `-t` :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4892bb1c-5cb4-91fa-325b-f5180cd05c3a
* Version Independent ID: 8c9a9a0e-5b36-4039-72c5-b28fd0bb9fd4
* Content: [az webapp config storage-account](https://docs.microsoft.com/en-us/cli/azure/webapp/config/storage-account?view=azure-cli-latest#az-webapp-config-storage-account-add)
* Content Source: [latest/docs-ref-autogen/webapp/config/storage-account.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/webapp/config/storage-account.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by adewaleo** [comment]
this should be fixed when #8083 is merged.

**Comment by adewaleo** [comment]
Should be fixed after our release...

**Comment by tjprescott** [comment]
For this, it's okay to close immediately. I realize I'm being somewhat inconsistent here, but this is a specific example, whereas the extensions thing was all extension docs. So... it's a little different. Normal process is to close when fixed. :)
