### ISSUE TITLE
No matches in graph database when creating role assignment

### ISSUE THREAD

**Issue by sajithvasu** [Azure/azure-cli#8153]
**Describe the bug**
Adding SPN id to subscription scope as any role fails using az cli with below error -
No matches in graph database for 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

Tested on az cli version 2.0.54 or 2.0.52

**To Reproduce**
Step to reproduce:

Add SPN Id as any role on subscription from portal
Delete the assigned spn id role from subscription
try to add it back using az cli command -
az role assignment create --role "Reader" --assignee 'xxxxxxxxxxxxxxxxxxxxxxx' --scope "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/"

**Comment by yugangw-msft** [comment]
@sajithvasu, can you please run `az ad sp show --id xxxxxxxxxxxxxxxxxxxxxxx` to confirm this SP does exist in the current tenant? Also if you are on Windows command prompt, please do not use single quote around the `--assignee` argument values as command prompt won't unwrap them.

**Comment by sajithvasu** [comment]
@yugangw-msft - we were able to identify this problem. Our automation was deleting spn instead of the role assignment due to which we were seeing the error. You can close this bug.
