### ISSUE TITLE
[Network] Public IP Create Issues

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#816]
Issues with `az network public-ip create`

- [x] exposes `dns-name-type`, which seems like it should be set automatically based on whether `dns-name` is set.
- [x] does not expose `idle-timeout` like Xplat
- [x] does not expose `ip-version` like Xplat
- [x] does not expose `reverse-fqdn` like Xplat

**Comment by BurtBiel** [comment]
Corresponding with network team.  It appears IPv6 addresses cannot be created through ARM templates.
