### ISSUE TITLE
`az storage share list` for storage account without shares generating a stack trace

### ISSUE THREAD

**Issue by Koura** [Azure/azure-cli#8161]
**Describe the bug**
Issuing command `az storage share list --account-name myaccountname` for a storage account without shares fails with `HTTPSConnectionPool max retries exceeded...` producing a lengthy python track trace. 

**To Reproduce**
Create a new Resource Group:
`az group create --name mytestresourcegroup --location westeurope`

Create a new Storage Account:
`az storage account create -n mytestsa -g mytestresourcegroup -l $AKS_PERS_LOCATION --sku Standard_ZRS`

BUG is reproduced now by calling:
 `az storage share list --account-name mytestsa`

However, the same command will work as expected if a file share is created:
```
export AZURE_STORAGE_CONNECTION_STRING=`az storage account show-connection-string -n mytestsa -g mytestresourcegroup -o tsv`
az storage share create -n mytestshare
az storage share list --account-name mytestsa
```

**Expected behavior**
The command should return an empty result.

**Environment summary**
I'm running on Ubuntu 18.04.1 LTS and azure-cli was installed by following the instruction found in https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest.

Version information:
Python 3.6.5
azure-cli 2.0.54

**Comment by williexu** [comment]
Actually, after some testing, I was able to see this problem when the sku `Standard_ZRS` was used with kind `Storage` (not v1). @Koura specifying `--kind StorageV2` should solve this problem.

@seguler [this](https://docs.microsoft.com/en-us/azure/storage/common/storage-redundancy-zrs#support-coverage-and-regional-availability) indicates that ZRS skus are only available for general purpose v2 accounts, but why does the service allow the creation of v1 accounts with ZRS sku? Clearer error messages from the service would make things more apparent.

**Comment by williexu** [comment]
@Koura should be okay, thanks

**Comment by amishra-dev** [comment]
Looks like the filer was able to resolve this issue. hope that no one minds if I close it here.
