### ISSUE TITLE
Recursive Permissions allocation parameter

### ISSUE THREAD

**Issue by rtcn2** [Azure/azure-cli#8163]
The powershell cmdlet for Set-AzDataLakeStoremItemAclEntry have an option to Recurse to child subdirectories and files, this option seems to be missing from the az cli commands, or is this documented somewhere else?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54936045-8eba-e6a2-530b-7ad9f19cbca5
* Version Independent ID: a3201b6f-e420-7596-3e42-3c58655688a0
* Content: [az dls fs access](https://docs.microsoft.com/en-gb/cli/azure/dls/fs/access?view=azure-cli-latest#az-dls-fs-access-set)
* Content Source: [src/command_modules/azure-cli-dls/azure/cli/command_modules/dls/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-dls/azure/cli/command_modules/dls/_help.py)
* Service: **datalake-store**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by abhiramani-iptiq** [comment]
any update?

**Comment by tjprescott** [comment]
The option isn't currently supported. It would be up to the data lake service team if they plan to implement this feature.

**Comment by sachinsbigdata** [comment]
Hi,
There are no current plans to add this support to CLI. You could use adlstool in the meanwhile - 
https://github.com/Azure/data-lake-adlstool . Hoping that meets your requirements.

Thanks.

**Comment by tjprescott** [comment]
Closing based on @sachinsbigdata's response.

**Comment by dgcaron** [comment]
i guess the same holds for the az cli?

**Comment by Riddle4045** [comment]
@tjprescott  any chance we can bump this up, this seems to be a critical feature gap.
