### ISSUE TITLE
Migrate the CLI packaging system to the latest recommendation

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-cli#8164]
I was randomly discussing packaging and CLI impact with @marstr, and I promised I will create an issue about the packaging update to do for CLI. So here it is :)

This means getting rid of azure_bdist_wheel file, using PEP420 for Python 3, etc. A more complete rational can be found here:
https://github.com/Azure/azure-sdk-for-python/wiki/Azure-packaging

I wouldn't say it's urgent, being that it doesn't impact at all the installers (Windows MSI, homebrew, etc.). Main benefits are : 
- For service team development, since it will simplify the dev_setup.py (remove this [kind of black magic](https://github.com/Azure/azure-cli/blob/8ab6e63cbb56c6443c52d8a3105ddc602b90666c/scripts/dev_setup.py#L54-L57)). `pip install --force-reinstall azure-nspkg==1.0.0` should never be needed anymore.
- Could simplify the "pip install" scenario in some corner case (shouldn't be considered a big concern)

Note that azure_bdist_wheel file logic is broken since an update of setuptools in November 2017, so we could consider as a benefit too removing a file that adds no value and just noise.

**Comment by yonzhan** [comment]
@fengzhou-msft  add to S162.

**Comment by fengzhou-msft** [comment]
will work on this when support for Python 2 is removed.

**Comment by jeffb4** [comment]
Just to note, this does impact an internal Python project we wrote because we call out to the azure-cli and thus have this project as a listed dependency (which forces back our setuptools).

So while it surely isn't critical, I'd love to see it.

**Comment by fengzhou-msft** [comment]
resolved in version 2.11.0.
