### ISSUE TITLE
functionapp CLI Error Messages are Inaccurate with regards to flags usage

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-cli#8169]
**Describe the bug**
CLI Error Messages are Inaccurate with regards to flags usage

**To Reproduce**
From @raahmed on January 3, 2019 21:29

Context: Running Python on Functions in Linux (Preview) on VS Code.

Severity: Potentially Serious (Potentially Blocking)

Reproduction Steps:

CLI error messages are inaccurate and confusing - notice how the --name flag is present in the command.
image
![image](https://user-images.githubusercontent.com/7810433/50717333-77c49e80-103b-11e9-8141-9de5bb15482d.png)

**Expected behavior**
Have accurate error messages that point, specifically, to the actual problem.
Note: In this case, the actual error was never found. While debugging this issue, I encountered other issues that, once fixed, eventually led to this error never being seen again.

Originally submitted https://github.com/Azure/Azure-Functions/issues/1089

**Comment by ankitkumarr** [comment]
I think the core CLI logic detects if all the required args are present, and spits that error. I haven't been able to reproduce it, even with a similar set of arguments. I can tell in the image, the error is the `uswest2`, but I see the appropriate message when I try it.

**Comment by ahmedelnably** [comment]
Closing this, please reopen if the issue is still happening
