### ISSUE TITLE
[Network] NIC list does not expose optional VMSS/index options like XPlat

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#817]
`az network nic list` shows all NICs in a resource group... EXCEPT for any which happen to be associated with any VMSS instances in the group. This is because there is a completely separate client for getting scale set NIC information. However, Xplat exposes what we would label `vmss-name` and `instance-id` on this command, effectively acting as an alias for `az vmss nic list(-vm-nics)`. 

The discussion is how we should handle this:
1. expose these parameters just like Xplat does
2. do not expose these parameters since `az vmss nic list(-vm-nics)` does the same thing
3. since the purpose of `az network nic list` is to show ALL nics in a resource group, you could also argue that we should take the union of `az network nic list` and `az vmss nic list` for each VMSS in the resource group... that already sounds costly so I doubt we'd go for it, but I at least wanted to point out the option. :)

**Comment by mayurid** [comment]
@jasonrshaver: Something to discuss with Network team
//cc @burtbiel:

**Comment by tjprescott** [comment]
I believe based on email discussion with @MikhailTryakhov, the implementation we have (which differs from Xplat) is fine. @JasonRShaver if you agree we can close this one.
