### ISSUE TITLE
webapp: zip deployment returns zip deployment taking too long exception even when the deployment actually failed

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-cli#8174]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by tjprescott** [comment]
#8173 merged. Closing
