### ISSUE TITLE
Argument completions incorrect in VSS and `az interactive`

### ISSUE THREAD

**Issue by chrmarti** [Azure/azure-cli#8179]
_From @sameershaikgithub on January 6, 2019 0:1_

in VSS:
az sql db create  (auto complete shows --database-name & --server-name, instead of  --name & --server)

correct syntax:
az sql db create --name shaiksdb --resource-group cligroup --server shaikssqlserver

az: error: unrecognized arguments: --database-name shaiksdb --server-name shaikssqlserver

screenshot attached
<img width="558" alt="screen shot 2019-01-05 at 6 51 05 pm" src="https://user-images.githubusercontent.com/20804460/50730460-3e179480-111c-11e9-9237-cc2bfb11e8ca.png">

_Copied from original issue: Microsoft/vscode-azurecli#42_

**Comment by chrmarti** [comment]
We are reading these from the CLI itself. `az interactive` shows the same (wrong) argument names for `sql db create --help`.

**Comment by tjprescott** [comment]
What version of the CLI are you using?  When I try using version 2.0.54 of the CLI and 0.4.1 of the interactive extension (i.e. latest of each) I see the correct completions (at least in `az interactive`).

**Comment by chrmarti** [comment]
![image](https://user-images.githubusercontent.com/9205389/50819487-71c80980-132a-11e9-8e8c-d84c151ca6ea.png)

![image](https://user-images.githubusercontent.com/9205389/50819530-92905f00-132a-11e9-94d9-45b235839491.png)

This is with Azure CLI 2.0.52 and the interactive extension 0.4.1.

Updating to 2.0.54 fixed it. (That did come through Homebrew yesterday.) 👍 

Closing, thanks.

**Comment by tjprescott** [comment]
Glad it's working for you @chrmarti. After that regression we added some more test coverage to hopefully prevent similar issues in the future.
