### ISSUE TITLE
Possible az container exist command

### ISSUE THREAD

**Issue by RicardoLans** [Azure/azure-cli#8181]
At my company we would love to see something like `az container exists --name ...` to get a true/false if a container instance already exists or not, just like the `az group exists` command.
Now we use the following:
`az container list --query "length([?name == '$ContainerGroupName'].{Name: name})"` and we check if this count == 0 so we know the chosen $ContainerGroupName is available to use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e5d1da7-7c4f-c9e6-e4b9-a30407675acf
* Version Independent ID: ba32e12d-8283-f980-e1d0-1ca2a75a5152
* Content: [az container](https://docs.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest#az-container-list)
* Content Source: [src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
`az container show` should return error code 3 if the container does not exist. That is the preferred way of exists checking in the CLI. @williexu please correct if I misspoke.

**Comment by RicardoLans** [comment]
@tjprescott it is true that I get the following error message with `az container show -n yyy -g xxx`: 
`The Resource 'Microsoft.ContainerInstance/containerGroups/yyy' under resource group 'xxx' was not found.`

But to me it looks like there is some inconsistency:
For checking if a 'ResourceGroup' exists there is a command `az group exists` which returns true/false.
For checking if a 'ContainerInstance' exists I must rely on an error message/error code. 

You see this made me a bit confused, hence this question :-)

But if that is how it is designed and must be used then my question is answered and you can close this 👍

**Comment by tjprescott** [comment]
`group exists` is really the anomaly here and only because there happens to be an API endpoint for it. Most resources have no such thing and that's why we added the more standard behavior to have the GET (`show` command) return a unique error code when something doesn't exist.

If `container show` isn't following that, that would be a bug.
