### ISSUE TITLE
Add pip packaging checks to release pipeline

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#8182]
There are two scripts that should be added to the PIP release pipeline and should gate *all* release mechanisms.

`azdev verify version` - script to ensure that the version has been bumped if the build artifact differs from the latest version on PyPI.
`azdev verify history` - checks random little things like the length of the underline, etc.

Verify history is done as part of each PR on the dev branch, but `verify version` and `verify history` must be run on the release branch since that is where the versioning is ultimately resolved before release. If these steps are missed for any reason (since this is a manual step), there is a risk of modules which *should* be published NOT being published because of the version number.

So, as a failsafe, the first step of the release pipeline should be to ensure these checks pass.

cc/ @yugangw-msft @marstr

**Comment by tjprescott** [comment]
Note: this issue can't be resolved until azdev is published since that is where the script lives. So it is blocked for now but will be important once azdev is published.

**Comment by tjprescott** [comment]
@yugangw-msft I would recommend that be a CI script that runs on each check-in, the same way that the documentation map script is. Alternatiely, if we use a script to pin the versions for each module in `azure-cli`'s `setup.py` file as part of #8165, these would all be collected (though it wouldn't hurt to verify).

**Comment by marstr** [comment]
I'm taking aim at this with #8646.

**Comment by marstr** [comment]
Given that #8592 is delayed until after //build, I'm adding this check in to keep us safe in the meantime.
