### ISSUE TITLE
functionApp zip deployment missing parameters

### ISSUE THREAD

**Issue by jaycle** [Azure/azure-cli#8191]
**Describe the bug**
The command `az functionApp deployment source config-zip --src <file.zip>` fails with the error:

```
az: error: unrecognized arguments: --src .<file.zip>
```
Same will be seen for any combination of flags `-g` or `-n`. The docs at https://docs.microsoft.com/en-us/azure/azure-functions/deployment-zip-push suggest this is the syntax yet when running `az functionApp deployment source config-zip -h` there are no arguments listed.

**To Reproduce**
1. Install latest az cli (2.0.54)
2. Run command

**Expected behavior**
Command succeeds and function app is deployed.

**Environment summary**
Running from powershell, windows 10, installed CLI from https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest and selecting "Install on windows"
```
> az --version
azure-cli (2.0.54)

acr (2.1.11)
acs (2.3.13)
advisor (2.0.0)
ams (0.3.1)
appservice (0.2.10)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.5)
billing (0.2.0)
botservice (0.1.3)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.4)
command-modules-nspkg (2.0.2)
configure (2.0.19)
consumption (0.4.1)
container (0.3.10)
core (2.0.54)
cosmosdb (0.2.6)
dla (0.2.3)
dls (0.1.7)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.2)
extension (0.2.3)
feedback (2.1.4)
find (0.2.13)
hdinsight (0.1.0)
interactive (0.4.1)
iot (0.3.4)
iotcentral (0.1.5)
keyvault (2.2.9)
lab (0.1.4)
maps (0.3.3)
monitor (0.2.7)
network (2.2.11)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.2)
rdbms (0.3.5)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.1)
resource (2.1.7)
role (2.2.0)
search (0.1.1)
servicebus (0.3.2)
servicefabric (0.1.10)
signalr (1.0.0)
sql (2.1.6)
storage (2.2.7)
telemetry (1.0.0)
vm (2.2.11)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\jayson\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
```

**Additional context**

**Comment by ahmedelnably** [comment]
@jaycle do you still have the same issue with the latest version of the CLI?

**Comment by jaycle** [comment]
I hadn't checked but I just updated to latest (`2.0.69`) and it seems to understand the arguments.

**Comment by ahmedelnably** [comment]
Thanks @jaycle, will close the issue for now, if you have any other issues please open a new one and we will take a look
