### ISSUE TITLE
AZ AKS command to get available nodes in running AKS cluster ??

### ISSUE THREAD

**Issue by akramwaseem** [Azure/azure-cli#8193]
Is there a command like az aks show --node-count --name &lt;&gt; --resourcegroup &lt;&gt;.
That would be a good idea, so that we can automate it to scale a node and get info of a node.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-list)
* Content Source: [src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by mboersma** [comment]
@akramwaseem the most detail you can get about your Kubernetes cluster with the CLI is `az aks show -n <> -g <> -o jsonc`, which only shows the node count:

**Comment by akramwaseem** [comment]
@mboersma -- Thanks for the info,
I know we can do this with kubectl but was wondering if we can do this using az command.
thanks for the help either way.

**Comment by mboersma** [comment]
Detail of the nodes isn't part of the AKS API schema, so it would take some significant changes there before this could be added to a new `az aks` command. Not impossible, but unlikely given than `kubectl` is a workaround.

**Comment by sahitkumarreddy** [comment]
@akramwaseem 
 az aks show --name yourClusterName --resource-group yourResourceGroup --query agentPoolProfiles[0].count

This command will print the nodes

**Comment by archmangler** [comment]
One could use (with BASH):

```
CLUSTER_RESOURCE_GROUP=$(az aks show --resource-group $resource_group --name $cluster_name --query nodeResourceGroup -o tsv)
az vm list --resource-group $CLUSTER_RESOURCE_GROUP| jq -r ".[] .name" 
```

**Comment by ringerc** [comment]
Actually you can get more info via a Resource Graph query.

See https://melcher.dev/2020/08/azure-resource-graph-getting-node-sizes-and-node-count-of-all-kubernetes-clusters/ (not my blog)

and their query

```
Resources
 | where type == "microsoft.containerservice/managedclusters"
 | extend properties.agentPoolProfiles
 | project subscriptionId, name, pool = (properties.agentPoolProfiles)
 | mv-expand pool
 | project subscription = subscriptionId, cluster = name, size = pool.vmSize, count = pool.['count']
```
