### ISSUE TITLE
az network vnet subnet update command is deleting existing subnet service endpoints

### ISSUE THREAD

**Issue by pritam97** [Azure/azure-cli#8204]
**Describe the bug**
"az network vnet subnet update" is deleting the existing subnet and recreating it. this is not expected.  

**To Reproduce**
1. create a subnet with 1 service endpoint enabled. 
2. use az network vnet subnet update to add one more service endpoint enable 

first service endpoint get deleted. and adding new one. 

Steps to reproduce the behavior.

**Expected behavior**
subnet should have 2 endpoints enabled. 

**Environment summary**

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
Install method: apt-get 
cli verison: azure-cli (2.0.52)

**Additional context**

**Comment by tjprescott** [comment]
If you are using the `--service-endpoints` argument, this is the expected behavior. It is not deleting and recreating the subnet, but it is overwriting what you put for service endpoints. If you want to add a service endpoint, you can either specify both service endpoints in the command or use the generic `--add` argument to add it to the list.

**Comment by tjprescott** [comment]
Here's the example syntax for that:
`az network vnet subnet update -g {rg} --vnet-name vnet1 -n subnet1 --add serviceEndpoints {} --set serviceEndpoints[1].service="Microsoft.Sql"`

Much simpler to simply specify both enpoints with `--service-endpoints Microsoft.Storage Microsoft.Sql`

**Comment by keriksson-rosenqvist** [comment]
Is there a more general way of doing this, if you don't know the number of current serviceEndpoints?
> az network vnet subnet update -g {rg} --vnet-name vnet1 -n subnet1 --add serviceEndpoints {} --set serviceEndpoints[1].service="Microsoft.Sql"
