### ISSUE TITLE
Document that --public-access in create is configurable post-creation using set-permission

### ISSUE THREAD

**Issue by TomasHubelbauer** [Azure/azure-cli#8205]
I was trying to find how to set `--public-access` on an already existing container, the Azure Portal UI doesn't really guide one in the right direction with showing this under "Access Policy", so I was very surprised to find that creating two accounts, one with default and one with `blob` and querying their policies using `az storage container policy list`resulted in `{}` in both cases.

I figured out I have to use `az storage container set-permission`, but it would be nice to say that in the description of the `--public-access` argument in the `az storage container create` section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adcba5ed-e693-6345-2c1b-c17422d7b8f9
* Version Independent ID: 58297400-b777-6868-1687-0af3a512a16f
* Content: [az storage container](https://docs.microsoft.com/en-us/cli/azure/storage/container?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
@williexu would an example help with this?

**Comment by williexu** [comment]
Yep, an example or added param help would both suffice to help with discovery.
