### ISSUE TITLE
--auth-mode argument for blob commands no longer exists

### ISSUE THREAD

**Issue by orn688** [Azure/azure-cli#8206]
**Describe the bug**

The `--auth-mode` argument for `az storage blob` commands seems to have disappeared since version 2.0.51, despite still being mentioned in the [docs](https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az-storage-blob-delete). I also can't find any mention of it being removed in the [release notes](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/release-notes-azure-cli.md). Was this an intentional change?

**To Reproduce**

`az storage blob list --help` doesn't display `--auth-mode` when using azure-cli version 2.0.54. However, when I switch back to 2.0.51 (using `brew switch azure-cli 2.0.51` on MacOS), it shows up.

**Expected behavior**

`az storage blob list --auth-mode=login ....` should accept the `--auth-mode` argument.

**Environment summary**

Install Method: Homebrew
CLI version: 2.0.54
OS version: MacOS 10.14.2
Shell Type: fish, bash

**Comment by williexu** [comment]
I just looked at the command and the parameter is there. Also used v2.0.54 on homebrew. 
Just a random idea, but do you have a very old version of the storage-preview extension installed?

**Comment by orn688** [comment]
@williexu Aha, that was it! Thanks for the help.
