### ISSUE TITLE
'az aks browse' does not work - "port already in use"

### ISSUE THREAD

**Issue by sshorkey** [Azure/azure-cli#8220]
I'm trying to connect to K8 dashboard but the steps aren't working.. when I try to connect I end up with this error:

```
scott@Azure:~$ az aks get-credentials --resource-group <redacted> --name <redacted>
Merged "<redacted>" as current context in /home/scott/.kube/config
scott@Azure:~$ az aks browse --resource-group <redacted> --name <redacted>
Merged "<redacted>" as current context in /tmp/tmpkpgjab6n
To view the console, please open https://gateway03.eastus.console.azure.com/n/cc-f587ecc9/cc-f587ecc9/proxy/8001/ in a new tab
Press CTRL+C to close the tunnel...
Unable to listen on port 8001: All listeners failed to create with the following errors: Unable to create listener: Error listen tcp4 127.0.0.1:8001: bind: address already in use, Unable to create listener: Error listen tcp6 [::1]:8001: bind: address already in use
error: Unable to listen on any of the requested ports: [{8001 9090}]
```

But then when the browser tab opens it says:
`{"error":{"message":"Port 8001 is not open"}}`

**Comment by sshorkey** [comment]
Any updates? This issue keeps recurring and it makes AKS unusable

**Comment by tjprescott** [comment]
@mboersma for comment.

**Comment by mboersma** [comment]
@sshorkey most likely there is a process listening already at TCP port 8001, which prevents the underlying `kubectl proxy` command from starting since it wants to listen on the same port.

Does a command like `netstat -lnt | grep .8001` show any process already listening there?

Have you tried `az aks browse --listen-port=8002` to listen on a different port?

**Comment by sshorkey** [comment]
> Have you tried `az aks browse --listen-port=8002` to listen on a different port?

Yes, and it worked. However, I constantly have to use a new port number every time. Pretty inconvenient...

**Comment by jluk** [comment]
The browse behavior is behaving correctly, it has to have an open port to listen on. It looks like you are using cloud shell as well, so double check you don't have other processes using port 8001 - when the port is free as expected it should function appropriately.

@yugangw-msft can you help close this?
