### ISSUE TITLE
typo in debug output

### ISSUE THREAD

**Issue by christiankuhtz** [Azure/azure-cli#8229]
**Describe the bug**
when running az group deployment validate with --debug, the penultimate line misspells process.

telemetry.process : Return from creating _**porcess**_

**To Reproduce**
az group deployment validate --debug with whatever other args.

**Expected behavior**
spell process process and not porcess.

**Environment summary**
azure-cli (2.0.54)

acr (2.1.11)
acs (2.3.13)
advisor (2.0.0)
ams (0.3.1)
appservice (0.2.10)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.5)
billing (0.2.0)
botservice (0.1.3)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.4)
command-modules-nspkg (2.0.2)
configure (2.0.19)
consumption (0.4.1)
container (0.3.10)
core (2.0.54)
cosmosdb (0.2.6)
dla (0.2.3)
dls (0.1.7)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.2)
extension (0.2.3)
feedback (2.1.4)
find (0.2.13)
hdinsight (0.1.0)
interactive (0.4.1)
iot (0.3.4)
iotcentral (0.1.5)
keyvault (2.2.9)
lab (0.1.4)
maps (0.3.3)
monitor (0.2.7)
network (2.2.11)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.2)
rdbms (0.3.5)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.1)
resource (2.1.7)
role (2.2.0)
search (0.1.1)
servicebus (0.3.2)
servicefabric (0.1.10)
signalr (1.0.0)
sql (2.1.6)
storage (2.2.7)
telemetry (1.0.0)
vm (2.2.11)

Python location '/opt/az/bin/python3'
Extensions directory '/home/christian/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Dec 20 2018, 01:00:18)
[GCC 7.3.0]

**Additional context**
Event: Cli.PostExecute []
telemetry.save : Save telemetry record of length 2530 in cache
telemetry.check : Returns Positive.
telemetry.main : Begin creating telemetry upload process.
telemetry.process : Creating upload process: "/opt/az/bin/python3 /opt/az/lib/python3.6/site-packages/azure/cli/telemetry/__init__.py /home/christian/.azure"
telemetry.process : Return from creating **_porcess_**
telemetry.main : Finish creating telemetry upload process.

**Comment by tjprescott** [comment]
Fixed in PR #8238.
