### ISSUE TITLE
az cognitiveservices account list-usage broken

### ISSUE THREAD

**Issue by diberry** [Azure/azure-cli#8233]
The ref page says the command to list usage is 
 
az cognitiveservices account list-usage --name
                                        --resource-group
                                        [--subscription]
 
When I try the command, I get an error.
 
C:\Users\diberry>az cognitiveservices account list-usage --name diberry-cogserv-all-key --resource-group docs-diberry
az cognitiveservices account: 'list-usage' is not in the 'az cognitiveservices account' command group. See 'az cognitiveservices account --help'.
 
The most similar choice to 'list-usage' is:
        list-skus
 

It looks like the AZ command isn’t working.

**Comment by tjprescott** [comment]
I just tested this command and it worked fine. There is a good likelihood that your CLI is out of date. What do you have when you run `az --version`

**Comment by diberry** [comment]
azure-cli (2.0.43)

acr (2.1.2)
acs (2.2.2)
advisor (0.6.0)
ams (0.2.1)
appservice (0.2.1)
backup (1.2.0)
batch (3.3.1)
batchai (0.4.0)
billing (0.2.0)
cdn (0.1.0)
cloud (2.1.0)
cognitiveservices (0.2.0)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.2)
core (2.0.43)
cosmosdb (0.2.0)
dla (0.2.0)
dls (0.1.0)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.1)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.27)
iot (0.2.0)
keyvault (2.2.1)
lab (0.1.0)
maps (0.3.1)
monitor (0.2.1)
network (2.2.2)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.0)
redis (0.3.0)
reservations (0.3.1)
resource (2.1.1)
role (2.1.2)
search (0.1.0)
servicebus (0.2.1)
servicefabric (0.1.0)
sql (2.1.1)
storage (2.1.1)
vm (2.2.0)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\diberry\.azure\cliextensions'

Python (Windows) 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by diberry** [comment]
@tjprescott As a general guideline, how often should I update the Azure CLI?

**Comment by diberry** [comment]
@tjprescott Is there an automatable way to upgrade - the docs just link to a downloadable installer?

**Comment by diberry** [comment]
I just found it on [chocolatey.org](https://chocolatey.org/packages/azure-cli). I'll use that moving forward. Thanks.

**Comment by tjprescott** [comment]
@diberry sound good. Just be aware that the chocolatey release is **not** provided or maintained by Microsoft, so the release cadence will likely lag the official release channels described here:
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest
