### ISSUE TITLE
Update docs/help for az bot prepare-publish's --proj-name and --sln-name for Node bots

### ISSUE THREAD

**Issue by mdrichardson** [Azure/azure-cli#8234]
**Is your feature request related to a problem? Please describe.**
when using `az bot prepare-publish`, it states that `--proj-name` and `--sln-name` are required, even with Node/JS/TS bots

**Describe the solution you'd like**
It would be easiest to update the docs from:

> --proj-name
> Name of the start up project file name. Required only for C#.
> 
> --sln-name
> Name of the start up solution file name. Required only for C#.

to:

> --proj-name
> Name of the start up project file name. Required for C#. For Node, use `--proj-file ""`.
> 
> --sln-name
> Name of the start up solution file name. Required for C#. For Node, use `--sln-file ""`.

But if the prepare-publish already does some kind of language detection at this point, it could make the `--proj-file` and `--sln-file` params optional.

**Describe alternatives you've considered**
I can get around it by calling them with blank parameters, i.e. `--proj-file ""`

**Comment by tjprescott** [comment]
There is no `az prepare-publish` command in the CLI. Are you using an extension?

**Comment by mdrichardson** [comment]
Whoops. I mean `az bot prepare-publish`. Edited.

**Comment by yochay** [comment]
@Kaiqb - FYI
@stevengum add this to 4.3?

**Comment by mdrichardson** [comment]
This has been fixed for awhile. Closing
