### ISSUE TITLE
Require "--location" in create command

### ISSUE THREAD

**Issue by terrymandin** [Azure/azure-cli#8235]
I needed to include "--location" when I ran the az create command or I got the following error:

"Source Virtual Machine 'TMIoTEdgeVM' specified in the request does not exist in this Azure location."

eg:
az image create -g MyResourceGroup -n image1 --source MyVm1 --location location

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42c81f4c-ac29-2f6e-96f2-b6fba3ef3098
* Version Independent ID: 2a24cd5b-8798-a175-5bde-7d2850bf9015
* Content: [az image](https://docs.microsoft.com/en-us/cli/azure/image?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/image.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/image.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by adewaleo** [comment]
Hello @terrymandin,

The documentation for the --source parameter says:
OS disk source from the same region, including a **virtual machine ID or name**, OS disk blob URI, managed OS disk ID or name, or OS snapshot ID or name.

If you specify a VM name, then the command searches for the VM within the specified resource group.  Have you tried specifying the ID of the VM as the source, when creating the image? 

P.S.
I don't think requiring location would solve this issue, unless I am misunderstanding what you mean. Location does not have to be required, because if --location is not specified and a command requires it, the command can default to the resource group's location.

**Comment by adewaleo** [comment]
@terrymandin, I hear you. But location isn't required, as it defaults to the resource group if specified. I imagine your issue is that you are trying to create the image in a different location (resource group's) from the VM's location. 

If the source vm is in the same location as the resource group, one doesn't need to specify the location and everything works fine:

```
(ext-venv) [01:45 PM] azure-cli-wktree tosin$ az group create -n ova-test -l westus
{
  "id": "/subscriptions/00000/resourceGroups/ova-test",
  "location": "westus",
  "managedBy": null,
  "name": "ova-test",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null
}
(ext-venv) [01:45 PM] azure-cli-wktree tosin$ az vm create -n test-vm -g ova-test --image debian
{
  "fqdns": "",
  "id": "/subscriptions/00000/resourceGroups/ova-test/providers/Microsoft.Compute/virtualMachines/test-vm",
  "location": "westus",
  "macAddress": "00-00-00-00-00-00",
  "powerState": "VM running",
  "privateIpAddress": "10.0.0.4",
  "publicIpAddress": "100.00.00.00",
  "resourceGroup": "ova-test",
  "zones": ""
}
(ext-venv) [01:48 PM] azure-cli-wktree tosin$ az image create -g ova-test -n test-image --source test-vm
The operation 'Create Image' requires the Virtual Machine 'test-vm' to be Generalized.
(ext-venv) [01:51 PM] azure-cli-wktree tosin$ az vm deallocate -n test-vm -g ova-test
(ext-venv) [01:53 PM] azure-cli-wktree tosin$ az vm generalize -n test-vm -g ova-test
(ext-venv) [01:56 PM] azure-cli-wktree tosin$ az image create -g ova-test -n test-image --source test-vm
{
  "id": "/subscriptions/00000/resourceGroups/ova-test/providers/Microsoft.Compute/images/test-image",
  "location": "westus",
  "name": "test-image",
  "provisioningState": "Succeeded",
  "resourceGroup": "ova-test",
  "sourceVirtualMachine": {
    "id": "/subscriptions/00000/resourceGroups/ova-test/providers/Microsoft.Compute/virtualMachines/test-vm",
    "resourceGroup": "ova-test"
  },
  "storageProfile": {
    "dataDisks": [],
    "osDisk": {
      "blobUri": null,
      "caching": "ReadWrite",
      "diskSizeGb": 30,
      "managedDisk": {
        "id": "/subscriptions/00000/resourceGroups/ova-test/providers/Microsoft.Compute/disks/test-vm_OsDisk_1_cf02f879e08546c89246f13069ca787a",
        "resourceGroup": "ova-test"
      },
      "osState": "Generalized",
      "osType": "Linux",
      "snapshot": null,
      "storageAccountType": "Standard_LRS"
    },
    "zoneResilient": null
  },
  "tags": {},
  "type": "Microsoft.Compute/images"
}
(ext-venv) [02:19 PM] azure-cli-wktree tosin$  
```

**Comment by adewaleo** [comment]
However if the VM is created in a diff location, say eastus...:
```
(ext-venv) [02:25 PM] azure-cli-wktree tosin$ az vm create -n test-vm-2 -g ova-test --image debian -l eastus -otable
ResourceGroup    PowerState    PublicIpAddress    Fqdns    PrivateIpAddress    MacAddress         Location    Zones
---------------  ------------  -----------------  -------  ------------------  -----------------  ----------  -------
ova-test         VM running    00.00.00.00                10.0.0.4            00-00-00-00-00-00  eastus
(ext-venv) [02:28 PM] Work-Mac:azure-cli-wktree tosin$ az vm deallocate -n test-vm-2 -g ova-test
(ext-venv) [02:30 PM] Work-Mac:azure-cli-wktree tosin$ az vm generalize -n test-vm-2 -g ova-test

Here the VM is created in east us, let us attempt to create an image in the resource group (located in westus). The image's location will default to the RG's location

```
(ext-venv) [02:32 PM] Work-Mac:azure-cli-wktree tosin$ az image create -g ova-test -n test-image-2 --source test-vm-2
Source Virtual Machine 'test-vm-2' specified in the request does not exist in this Azure location.
(ext-venv) [02:32 PM] Work-Mac:azure-cli-wktree tosin$ 
```
It fails.

**Comment by adewaleo** [comment]
However if the VM is created in a diff location, say eastus...:
```
(ext-venv) [02:25 PM] azure-cli-wktree tosin$ az vm create -n test-vm-2 -g ova-test --image debian -l eastus -otable
ResourceGroup    PowerState    PublicIpAddress    Fqdns    PrivateIpAddress    MacAddress         Location    Zones
---------------  ------------  -----------------  -------  ------------------  -----------------  ----------  -------
ova-test         VM running    00.00.00.00                10.0.0.4            00-00-00-00-00-00  eastus
(ext-venv) [02:28 PM] azure-cli-wktree tosin$ az vm deallocate -n test-vm-2 -g ova-test
(ext-venv) [02:30 PM] azure-cli-wktree tosin$ az vm generalize -n test-vm-2 -g ova-test
```
Here the VM is created in east us, let us attempt to create an image in the resource group (located in westus). The image's location will default to the RG's location

```
(ext-venv) [02:32 PM] azure-cli-wktree tosin$ az image create -g ova-test -n test-image-2 --source test-vm-2
Source Virtual Machine 'test-vm-2' specified in the request does not exist in this Azure location.
```

It fails.

Closing this issue. Please let me know if anything else comes up @terrymandin
