### ISSUE TITLE
Support external parameter files in az group deployment create

### ISSUE THREAD

**Issue by yaegashi** [Azure/azure-cli#8236]
**Is your feature request related to a problem? Please describe.**

Please support external parameter files in `az group deployment create`, namely `parametersLink` property in [DeploymentProperties](https://docs.microsoft.com/en-us/rest/api/resources/deployments/createorupdate#deploymentproperties) in the REST API.

PowerShell already has this feature (`-TemplateParameterUri` in [New-AzureRmResourceGroupDeployment](https://docs.microsoft.com/en-us/powershell/module/azurerm.resources/new-azurermresourcegroupdeployment)).  It's explicitly documented as unsupported (https://github.com/MicrosoftDocs/azure-docs/issues/20698), but I don't think there's clear reason Azure CLI cannot support it.

**Describe the solution you'd like**

Add argument `--parameters-uri` in command `az group deployment create`.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by tjprescott** [comment]
We would not add `--parameters-uri` but we could likely make `--parameters` accept a local path or URI.

**Comment by yaegashi** [comment]
@tjprescott Hi, thanks for seeing this.

Adding URI support in `--parameters` is great. I'm looking forward to seeing it.

Aside from that,  do you think there's nothing beneficial in having `--parameters-uri` for the completeness?  Actually I'm not sure about it.

Any difference which possibly occurs in deployment consequences between `parameters` and `parametersLink` used in [DeploymentProperties](https://docs.microsoft.com/en-us/rest/api/resources/deployments/createorupdate#deploymentproperties)?  For example, size limitation of inlined parameters in REST API input, ongoing deployment view in Azure Protal, or something like that.

Both of them are supported in other common tooling options, including [New-AzureRmResourceGroupDeployment cmdlet](https://docs.microsoft.com/en-us/powershell/module/azurerm.resources/new-azurermresourcegroupdeployment) in PowerShell and [azure_rm_deployment module](https://docs.ansible.com/ansible/latest/modules/azure_rm_deployment_module.html) in Ansible.

**Comment by tjprescott** [comment]
`--parameters` is already overloaded in the CLI to accept key-value pairs or a file, so a URI is just an extension of the file concept.  @yugangw-msft has made PR #8306 which will add this functionality, so it should make it in the next release :)

**Comment by yaegashi** [comment]
What I mean is whether or not there's any case you must use `parametersLink` which is not supported by Azure CLI because `parameters` is not functional for some reason.  If you could assure there's no such concern in underlying Azure REST API, that would be fine.

**Comment by yugangw-msft** [comment]
I talked to people working on azure resource manager, and confirmed there are no situations that you have to use the link option, which is mainly for convenience. With that, I will continue with the `--parameters` option, which also brings in the benefit of keeping the command simple

**Comment by yaegashi** [comment]
@yugangw-msft I appreciate the confirmation given.  And thanks for the great work on this issue!
