### ISSUE TITLE
[AKS]Validate network plugin when using customVnet

### ISSUE THREAD

**Issue by zqingqing1** [Azure/azure-cli#8243]
**Describe the bug**
az aks create --resource-group delete-aks-subdns --name aksclustername -l westus2 --node-count 1 --vnet-subnet-id /subscriptions/fa6d648f-a63d-4dc5-a9cf-56eeb1fd9141/resourceGroups/delete-vnet-dns-cli/providers/Microsoft.Network/virtualNetworks/bruhnet/subnets/subdub --docker-bridge-address 172.17.0.0/16 **--dns-service-ip 192.168.0.10 --service-cidr 192.168.0.0/24** --kubernetes-version 1.11.5

Without --network-plug azure, the network profile will use default plugin and values

 "networkProfile": {

    **"networkPlugin": "kubenet"**,

    "podCidr": "10.244.0.0/16",

    **"serviceCidr": "10.0.0.0/16",**

    **"dnsServiceIP": "10.0.0.10",**

    "dockerBridgeCidr": "172.17.0.1/16"

   }

**To Reproduce**
Creating AKS with customVnet and without azure plugin provided.

**Expected behavior**
Validate if azure plugin provided when creating AKS with customVnet, if not, raise error and let customer to add the plugin.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by jluk** [comment]
This should be resolved with @GaneshaThirumurthi changes a few weeks back. Closing unless I am mistaken, if so please re-open.
