### ISSUE TITLE
azure-cli (python3.6) pulls futures lib that is not fully python3 compatible

### ISSUE THREAD

**Issue by thiagoss** [Azure/azure-cli#8253]
**Describe the bug**
Azure-cli pulls as a dependency futures==3.1.1 that has python3.6 incompatible code

**To Reproduce**
Create a virtualenv with python3.6
`pip3 install azure-cli==2.0.55`

Run `pip freeze` and check that futures was installed. Eventually the line
```
  File "/usr/local/lib/python3.6/site-packages/concurrent/futures/_base.py", line 381
    raise exception_type, self._exception, self._traceback
```
is executed and it fails. It will shadow the real python3 native futures library and cause problem in other packages that use it.

**Expected behavior**
futures library should not be installed for python3 environments.

**Environment summary**
As described: virtualenv with python3.6 and pip3

**Additional context**
When I get the failure due to some other lib, if I just remove the concurrent/futures directory in the virtualenv libraries it starts working as the native python3 futures lib is picked up and works just fine.

This is similar to https://github.com/Azure/azure-cli/issues/3988 but the library is still being installed regardless of this fix.

**Comment by tjprescott** [comment]
@marstr for triage.
