### ISSUE TITLE
group delete works differently between interactive and normal

### ISSUE THREAD

**Issue by mlda065** [Azure/azure-cli#8254]
# Describe the bug

    az group delete --name mygroup

works as a command, but not inside `az interactive`.

    az group delete --help

returns

    Arguments
        --name --resource-group -g -n [Required] : Name of resource group. You can configure the default

This clearly means that *either* `--name` or `--resource-group` is an acceptable flag for the name of the resource group you want to delete.

And `az group delete --name mygroup` does work.

If you run `az interactive` and type `group delete --` the suggestions are

```
az>> group delete --name draw-demo
 --name            [Required] Name of resource group. You can configure the default group using `az configure --defaults group=<na...
 --resource-group  [Required] Name of resource group. You can configure the default group using `az configure --defaults group=<na...
```

This also makes it clear that *either* `--name` or `--resource-group` can be used. 

However if you try to run the same command as before, but now in interactive mode, it fails.

```
$ az interactive
az>> group delete --name mygroup
az group delete: error: the following arguments are required: --resource-group/-g
usage: az group delete [-h] [--verbose] [--debug]
                       [--output {json,jsonc,table,tsv,yaml}]
                       [--query JMESPATH] --resource-group RESOURCE_GROUP_NAME
                       [--yes] [--no-wait] [--subscription _SUBSCRIPTION]

```

# To Reproduce

```
$ az interactive
az>> group delete --name mygroup
```

# Expected behavior

Group is successfully deleted

# Actual Behavior

```
az group delete: error: the following arguments are required: --resource-group/-g
usage: az group delete [-h] [--verbose] [--debug]
                       [--output {json,jsonc,table,tsv,yaml}]
                       [--query JMESPATH] --resource-group RESOURCE_GROUP_NAME
                       [--yes] [--no-wait] [--subscription _SUBSCRIPTION]

```

# Environment summary

* Ubuntu 18
* installed based on the official instructions
* `az --version`:

```
azure-cli (2.0.54)
...

Extensions:
interactive (0.4.1)
...
Python (Linux) 3.6.5
```

**Comment by tjprescott** [comment]
I am not able to repro this issue. If you run `az group delete -h`  outside of interactive, does it not show:

```
Command
    az group delete : Delete a resource group.

Arguments
    --name --resource-group -g -n [Required] : Name of resource group. You can configure the default
                                               group using `az configure --defaults group=<name>`.
```

**Comment by mlda065** [comment]
I just ran `apt-get update && apt-get -y upgrade`. Now my client has upgraded from 2.0.54 to 2.0.55. The problem still exists.

In fact, when trying to reproduce this problem with the newer version, I noticed that the problem extends to `group create` too.

![groupcreate screenshot](https://user-images.githubusercontent.com/7035647/51219339-95233200-1984-11e9-9127-d682e5e9f755.png)

**Comment by tjprescott** [comment]
Hi @mlda065 thanks for updating. Please try a few things:
1. Run `az --version` from both the raw command line and from within `az interactive`. Confirm that they are the same.
2. On your command line run `which az` and then in az interactive run `#which az`. Confirm that they are the same. 
3. Exit `az interactive` and delete your `.azure-shell` folder (shuld be in your home directory). Then re-launch interactive. You may have an outdated cache.

**Comment by mlda065** [comment]
1. Same for both
2. same for both
3. Yes that fixed it

**Comment by tjprescott** [comment]
Thanks @mlda065. I'm going to transfer this issue to extensions repo and suggest that we add a flag to clear the cache.
