### ISSUE TITLE
 az aks disable-addons failure

### ISSUE THREAD

**Issue by rprinsen** [Azure/azure-cli#8258]
###  Describe the bug

I'm trying to disable the monitoring addon in aks, because my kubernetes cluster is marked as 'misconfigured' in containerInsights.

As suggested [here](https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-optout), i can opt out and re-onboard by running the following command:

> az aks disable-addons -a monitoring -n {cluster-name} -g {resource-group}

However, this results in a stacktrace being thrown by azure-cli:

> Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/{removed}/resourceGroups/{removed}/providers/Microsoft.ContainerService/managedClusters/{removed}?api-version=2018-03-31 (Caused by ResponseError('too many 500 error responses',))
> Traceback (most recent call last):
>   File "/opt/az/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
>     timeout=timeout
>   File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
>     body_pos=body_pos, **response_kw)
>   File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
>     body_pos=body_pos, **response_kw)
>   File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 731, in urlopen
>     body_pos=body_pos, **response_kw)
>   File "/opt/az/lib/python3.6/site-packages/urllib3/connectionpool.py", line 711, in urlopen
>     retries = retries.increment(method, url, response=response, _pool=self)
>   File "/opt/az/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/{removed}/resourceGroups/{removed}/providers/Microsoft.ContainerService/managedClusters/{removed}?api-version=2018-03-31 (Caused by ResponseError('too many 500 error responses',))

Meanwhile, all oms pods seem to be running fine, but containerInsights shows 'Error retrieving data'.

### Expected behavior
Monitoring to be disabled for my kubernetes cluster, and being able to onboard again

### Environment summary

Kubernetes version: 1.10.9

az --version output:

> azure-cli (2.0.54)
> 
> acr (2.1.11)
> acs (2.3.13)
> advisor (2.0.0)
> ams (0.3.1)
> appservice (0.2.10)
> backup (1.2.1)
> batch (3.4.1)
> batchai (0.4.5)
> billing (0.2.0)
> botservice (0.1.3)
> cdn (0.2.0)
> cloud (2.1.0)
> cognitiveservices (0.2.4)
> command-modules-nspkg (2.0.2)
> configure (2.0.19)
> consumption (0.4.1)
> container (0.3.10)
> core (2.0.54)
> cosmosdb (0.2.6)
> dla (0.2.3)
> dls (0.1.7)
> dms (0.1.1)
> eventgrid (0.2.0)
> eventhubs (0.3.2)
> extension (0.2.3)
> feedback (2.1.4)
> find (0.2.13)
> hdinsight (0.1.0)
> interactive (0.4.1)
> iot (0.3.4)
> iotcentral (0.1.5)
> keyvault (2.2.9)
> lab (0.1.4)
> maps (0.3.3)
> monitor (0.2.7)
> network (2.2.11)
> nspkg (3.0.3)
> policyinsights (0.1.0)
> profile (2.1.2)
> rdbms (0.3.5)
> redis (0.3.2)
> relay (0.1.2)
> reservations (0.4.1)
> resource (2.1.7)
> role (2.2.0)
> search (0.1.1)
> servicebus (0.3.2)
> servicefabric (0.1.10)
> signalr (1.0.0)
> sql (2.1.6)
> storage (2.2.7)
> telemetry (1.0.0)
> vm (2.2.11)
> 
> Python location '/opt/az/bin/python3'
> Extensions directory '/home/rienk/.azure/cliextensions'
> 
> Python (Linux) 3.6.5 (default, Dec 20 2018, 01:00:26) 
> [GCC 8.2.0]

```
```

**Comment by zqingqing1** [comment]
I don't think it is CLI issue, the 500 error means `internal server error`, so I suggest you to create Icm, and on-call will follow up there.

**Comment by tjprescott** [comment]
Assuming this is a transient server issue, I'll close this. @rprinsen if you continue to experience this, please reopen.
