### ISSUE TITLE
--resource-type (Ex: 'Microsoft.Compute/virtualMachines)')

### ISSUE THREAD

**Issue by michaelspinks** [Azure/azure-cli#8259]
Change (Ex: 'Microsoft.Compute/virtualMachines)'). to (Ex: 'Microsoft.Compute/virtualMachines').

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f601495-154d-5e5c-3692-02f8f41516f7
* Version Independent ID: 2968e230-b7a0-b433-333a-af3bba69fd0e
* Content: [az monitor alert](https://docs.microsoft.com/en-us/cli/azure/monitor/alert?view=azure-cli-latest#az-monitor-alert-update)
* Content Source: [src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
This is an issue with the `--target-type` argument.  Thanks for the report @michaelspinks

**Comment by daxter44** [comment]
I reserve this task for 24 h :) 
Beginner here
