### ISSUE TITLE
`az vm delete` does not delete the VM listing under its resource group in the portal

### ISSUE THREAD

**Issue by anlatsko** [Azure/azure-cli#8260]
When I run `az vm delete --resource-group resourceGroup --name vmName`, I can see that the VM is removed from when I run `az vm lis` (it returns an empty list) but the VM resources are not removed from the portal. I saw another issue (#4897) that the disk is not deleted, but I expect everything else to be fully removed from the portal.

**To Reproduce**
Run `az vm create ...` and create a VM. Run `az vm list` to assure yourself that it's there. Then, run `az vm delete ...` and rerun `az vm list` again to assure yourself that it's gone. Finally, visit the portal and look at the resource group under which you created the VM. The VM, disk, NSG, PublicIP, VMNic, and VNET are all still listed. You should be able to create a VM with the exact same name (whereas if the VM had not been deleted, you would not be able to do so).

**Expected behavior**
I expect the VMs to be removed from the portal so it does not, misleadingly, look like there is a VM available. They are considered to be "marked for deletion," but do not get deleted from the portal even if you wait 12 hours.

**Comment by anlatsko** [comment]
hi, @adewaleo Thanks for getting back to me.

I was running 
`az vm list --resource-group anlatsko-rg --subscription 646cce9f-0a1c-4acb-be06-401056b03659`. The result is in the last screenshot (`[]`).

![freebsd_in_portal](https://user-images.githubusercontent.com/46537390/51345124-359e5280-1a68-11e9-9322-9decd668ed67.png)

![subscription_confirmed](https://user-images.githubusercontent.com/46537390/51345123-359e5280-1a68-11e9-99e6-8d3e5532960f.png)

**Comment by adewaleo** [comment]
@anlatsko there are no VMs in the screenshot, just resources previously associated with the VM. There is a virtualnetwork though. But the VM resource itself has been deleted.

If you run:

`az resource list --resource-group anlatsko -otable`

You should see the same resources listed in the CLI.

P.S.
You don't need to specify the subscription if it is the default subscription shown after running: 

`az account show`

**Comment by anlatsko** [comment]
Hi @adewaleo 

AH i'm so sorry to have wasted your time. I see that you are correct. I assumed that everything would have been deleted.

Thanks for your help.

**Comment by tjprescott** [comment]
@anlatsko if you create the VM in it's own resource group, you can delete the entire resource group when you are done with it, which *will* delete all the related resources.

**Comment by adewaleo** [comment]
> Hi @adewaleo Tosin Adewale FTE
> 
> AH i'm so sorry to have wasted your time. I see that you are correct. I assumed that everything would have been deleted.
> 
> Thanks for your help.

no worries @anlatsko, It's my pleasure to clear up any confusion.
