### ISSUE TITLE
More details on --skip-assignment

### ISSUE THREAD

**Issue by gaziqbal** [Azure/azure-cli#8264]
More details on what --skip-assignment means would be helpful. What is a "default assignment" and why would one want to skip it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99d25ff-03e2-e015-37f4-a29b59ec50d4
* Version Independent ID: 1a8e88ed-72c7-fbe7-b0ad-68f23b3946cd
* Content: [az ad sp](https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#az-ad-sp-create-for-rbac)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by stewartadam** [comment]
Note that this clarified `—skip-assignment`, but not what a ‘default assignment’ is earlier in the docs per OP’s recommendation.

I just ran into this as well and its extremely unclear that `create-for-rbac` grants permissions to the subscription by default. That’s a broad permission and deserves an explicit callout whenever ‘default assignment’ is mentioned.

**Comment by yugangw-msft** [comment]
@stewartadam, I am updating the command to output a message of creating such a role assignment.
Also the help of `--skip-assignment` has already mentioned the default assignment.
