### ISSUE TITLE
[ACR] Remove hard coded api-version when importing SDK

### ISSUE THREAD

**Issue by djyou** [Azure/azure-cli#8265]
**Is your feature request related to a problem? Please describe.**

Remove hard coded api-version when importing SDK such as https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/run.py#L12

This also includes cleaning up deprecated legacy commands using old api-versions such as https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/build_task.py#L11

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tjprescott** [comment]
Should involve:
1. Add a resource type to `_shared.py` for 'latest' profile.
2. Specify that resource type in your module `__init__.py`
3. Update your model import to use `self.get_models('ModelA', 'ModelB')` etc.

Ping me with questions.

**Comment by tjprescott** [comment]
https://github.com/Azure/azure-cli/issues/8267 has a bit more explicit guidance if that's helpful.
