### ISSUE TITLE
How to get list of all Metrics?

### ISSUE THREAD

**Issue by asubmani** [Azure/azure-cli#8271]
`az monitor metrics list --resource {resourceID}` lists only the first metric in the list. It should output all metrics.  Often we do not know what namespace a metric is available; or what the namespace value should be in this command. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c722777b-9914-5c57-b869-a92bb16e159e
* Version Independent ID: 19b7e250-35b0-6e41-6662-b86791cf4c78
* Content: [az monitor metrics](https://docs.microsoft.com/en-us/cli/azure/monitor/metrics?view=azure-cli-latest#az-monitor-metrics-list)
* Content Source: [src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
I believe the command you are looking for is `az monitor metrics list-definitions`. That command shows you what metrics are available. You get the metric names and namespace names from there and use them here, which will then retrieve the actual metric data.

The help text should call this out.
