### ISSUE TITLE
Command "az vm image list -f "Windows-10" --all" returns empty list

### ISSUE THREAD

**Issue by skybear2014** [Azure/azure-cli#8272]
Command "az vm image list -f "Windows-10" --all" used to give us list of windows 10 images. It started return empty list recently. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90dfc804-87d6-913a-27fe-a9446a04eb13
* Version Independent ID: bfcb97df-2055-9eca-7a93-60811136d8cd
* Content: [az vm image](https://docs.microsoft.com/en-us/cli/azure/vm/image?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by adewaleo** [comment]
This is very strange. The command works for me.

```
$ az vm image list -f "Windows-10" --all -otable
Offer       Publisher                Sku       Urn                                                       Version
----------  -----------------------  --------  --------------------------------------------------------  ------------
Windows-10  MicrosoftWindowsDesktop  RS3-Pro   MicrosoftWindowsDesktop:Windows-10:RS3-Pro:16299.904.65   16299.904.65
Windows-10  MicrosoftWindowsDesktop  RS3-ProN  MicrosoftWindowsDesktop:Windows-10:RS3-ProN:16299.904.65  16299.904.65
Windows-10  MicrosoftWindowsDesktop  rs4-pro   MicrosoftWindowsDesktop:Windows-10:rs4-pro:17134.523.65   17134.523.65
Windows-10  MicrosoftWindowsDesktop  rs4-pron  MicrosoftWindowsDesktop:Windows-10:rs4-pron:17134.523.65  17134.523.65
Windows-10  MicrosoftWindowsDesktop  rs5-pro   MicrosoftWindowsDesktop:Windows-10:rs5-pro:17763.253.65   17763.253.65
```

I have a few questions:
1. What version of the CLI are you using? What is the output of `az --version`
2. Have you configured any defaults that could be affecting the behavior of the command. Run `az configure`

**Comment by skybear2014** [comment]
Thank you for the reply. 
I tried again today. And It is good now. Please close this thread. Thank you.
