### ISSUE TITLE
Any plan to support creating stored procedures, triggers, and user-defined functions for azure cosmos db

### ISSUE THREAD

**Issue by Enoch-Ye** [Azure/azure-cli#8273]
Hi,

Is there any plan to support creating stored procedures, triggers and user-defined functions for azure cosmos db?

Can't find any related commands from here
https://docs.microsoft.com/es-es/cli/azure/cosmosdb?view=azure-cli-latest

https://github.com/Azure/azure-cli/blob/c2a242e9215ebafbbbd78994773cac80c1a0868a/src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/custom.py

**Comment by shurd** [comment]
This is a data plane question @moderakh @christopheranderson
