### ISSUE TITLE
Suppress SQL VM extension

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#8278]
The recently merged sqlvm module should add the correct metadata to suppress the existing extension. Otherwise the extension (which is older) will continue to override the newer module.

https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#extension-suppression

**Comment by yareyes** [comment]
Pull request https://github.com/Azure/azure-cli/pull/8318

**Comment by tjprescott** [comment]
Fixed in #8318.
