### ISSUE TITLE
[webapp ssh] sometimes the connection refused

### ISSUE THREAD

**Issue by patricklee2** [Azure/azure-cli#8281]
I ran into connection refused issue several time when tried to connect but was able to connect after couple of tries. We should look into the issue, you may be able to get repro logs from https://petclinic.azurewebsites.net/ 
```
yiliao@yili-ubuntu-03:~$ az webapp ssh -g appsvc_rg_Linux_centralus -n yili-python-up-08
Auto-selecting port: 34229
SSH is available ( username: root, password: Docker! )
_ssh: connect to host localhost port 34229: Connection refused_
```

**Comment by patricklee2** [comment]
assign to @patricklee2

**Comment by yugangw-msft** [comment]
https://github.com/Azure/azure-cli/pull/8324 fixes it
