### ISSUE TITLE
Docker CLI Needs Update

### ISSUE THREAD

**Issue by bgklein** [Azure/azure-cli#8284]
**Describe the bug**
https://github.com/Azure/azure-batch-cli-extensions/issues/94
After discussions with @lmazuel and @williexu it seems like this is an issue with the Docker container.

**To Reproduce**
docker run -it Microsoft/azure-cli
az extension add -n azure-batch-cli-extensions

**Expected behavior**
Install extension

**Environment summary**
Docker container

**Additional context**

[log.txt](https://github.com/Azure/azure-cli/files/2770566/log.txt)

**Comment by tjprescott** [comment]
@marstr for triage.

**Comment by bgklein** [comment]
https://github.com/Azure/azure-cli/pull/8291
