### ISSUE TITLE
Application Gateway support for Get Server Variables APIs

### ISSUE THREAD

**Issue by nirkum18** [Azure/azure-cli#8290]
**Is your feature request related to a problem? Please describe.**
CLI needs to be updated according to the NRP and swagger changes. We have added 3 new APIs to fetch the supported server variables, request and response headers, for Header CRUD feature in Application Gateway. CLI needs to be updated to support these APIs.

**Describe the solution you'd like**
Need CLI to be written as per the [Swagger Changes here](https://github.com/Azure/azure-rest-api-specs/pull/4916).

**Comment by tjprescott** [comment]
API version 2018-11-01.

**Comment by tjprescott** [comment]
@nirkum18 I believe there is something wrong with the Swagger specs for these three endpoints. Whenever I try to call them using the Autorest generated SDK, I get the following error:

```
  File "d:\gitrepos\github\env\lib\site-packages\azure\mgmt\network\v2018_12_01\operations\application_gateways_operations.py", line 955, in list_available_response_headers
    deserialized = models.list(internal_paging, self._deserialize.dependencies)
AttributeError: module 'azure.mgmt.network.v2018_12_01.models' has no attribute 'list'
```

cc/ @lmazuel

**Comment by tjprescott** [comment]
I will proceed with my PR to bump the Network API version, but I will not add these commands until the specs are fixed.

**Comment by nirkum18** [comment]
> @nirkum18 I believe there is something wrong with the Swagger specs for these three endpoints. Whenever I try to call them using the Autorest generated SDK, I get the following error:
> 
> ```
>   File "d:\gitrepos\github\env\lib\site-packages\azure\mgmt\network\v2018_12_01\operations\application_gateways_operations.py", line 955, in list_available_response_headers
>     deserialized = models.list(internal_paging, self._deserialize.dependencies)
> AttributeError: module 'azure.mgmt.network.v2018_12_01.models' has no attribute 'list'
> ```
> cc/ @lmazuel

@tjprescott  Some recent swagger changes related to these changes were pushed to the network-january-release branch. If you the SDK, that you are using, is getting generated from network-december-release branch, it may not contain the recently checkedin changes.

I have generated the SDK with those changes and powershell cmdlets are working fine for me.
Here is the swagger PR link: https://github.com/Azure/azure-rest-api-specs/pull/5113

In this PR we changed the return type of commandlets from a dictionary to a list of strings.

**Comment by tjprescott** [comment]
Thanks for the update @nirkum18. When those changes are merged to master, we will be able to proceed.

**Comment by tjprescott** [comment]
@nirkum18 it seems the `network-january-release` branch has still not been merged to master? Do you know when this will happen?

**Comment by tjprescott** [comment]
Due to the necessity for Swagger changes, there is no way this will be released this sprint. @nirkum18 please advise when the Swagger fix has been merged and we will reschedule this work accordingly.

**Comment by tjprescott** [comment]
Swagger issues have been resolved, so this change will go into Sprint 58.
