### ISSUE TITLE
az lab vm create incorrectly parses inline artifacts

### ISSUE THREAD

**Issue by nyaapa** [Azure/azure-cli#8292]
**Describe the bug**
az lab vm create doesn't support inline artifacts

**To Reproduce**
    az lab vm create --artifacts '[{"a":"/artifactsources/publi"}]'
    Expecting property name enclosed in double quotes: line 1 column 3 (char 2)

**Expected behavior**
Artifacts parsing succeeded.

**Environment summary**
Win10, powershell

**Additional context**
Can't save to a file

**Comment by nyaapa** [comment]
maybe it's a powershell specific: can put it into a variable and pass it;
but hitting types issues

`> $arg = '[{"a":"/artifactsources/publi"}]'`
`> az lab vm create --name qqq --formula qqq--admin-username qqq --artifacts "'$arg'" --lab-name qqq --resource-group qqq --admin-password qqq`

`Artifacts must be of type list. Given artifacts: '[{a:/artifactsources/publi}]'`

**Comment by tjprescott** [comment]
From the looks of it, Powershell is stripping out the double quotes.

**Comment by nyaapa** [comment]
Thanks!

`> $darg = $arg -replace '"', '""""'`
`> $darg`
`[{""""a"""":""""/artifactsources/publi""""}]`

`> az lab vm create ... --artifacts $darg`
`Missing 'artifactId' for artifact: '{'a': '/artifactsources/publi'}'`
