### ISSUE TITLE
Azure stack AZ problem 

### ISSUE THREAD

**Issue by JohanLander** [Azure/azure-cli#8307]
**Describe the bug**
When i have configured AZ to go to Azure stack it will not work to change Subscription to public azure cloud 

**To Reproduce**
1. configure your Az to go to a Azure stack with one account user@onmicrosoft.com
2. Try to start a new AZ session and try to go to your Azure cloud subscription then you get this error message:

Authentication Error: "['access_denied']". Description: "["AADSTS650057: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. Client app ID: 04b07795-8ddb-461a-bbee-02f9e1bf7b46. Resource value from request: https://management.XXXXXXXXAZURESTACK.onmicrosoft.com/147ebf36-1ddd-463b-939b-42b9605fb272. Resource app ID: dd6bdbbc-e1cd-47b2-83d0-5878d4547699. List of valid resources from app registration: .\r\nTrace ID: b758e748-7e31-436e-b826-7cb2e49a5400\r\nCorrelation ID: 1a983d73-7b97-45a2-a414-0d5f79c2a761\r\nTimestamp: 2019-01-21 13:24:16Z"]"

**Environment summary**
 azure-cli (2.0.55)
**Additional context**

**Comment by JohanLander** [comment]
i have used this guide 
https://docs.microsoft.com/sv-se/azure/azure-stack/user/azure-stack-version-profiles-azurecli2
and i got this message in then end of this guide

**Comment by yugangw-msft** [comment]
@JohanLander, could you run `az cloud set -n AzureCloud` and then `az account set ...` to get to your azure subscription?

**Comment by bbcnt** [comment]
Just thought I would leave a comment here, @yugangw-msft command fixed it for me. I ran `az cloud list` and found out I was using AzureStackUser, which was obviously wrong when trying to access azure on cloud.

**Comment by yugangw-msft** [comment]
@bbcnt, thanks for the response.
@JohanLander, please reactivate with more information
