### ISSUE TITLE
Wondering about webapp vs web app

### ISSUE THREAD

**Issue by craigpla** [Azure/azure-cli#8309]
I see it both ways in this list -- I realize the command will have webapp with no space, but when talking about a web app, does it get a space or no? The first few command explanations have it without a space. Looks like the rest have it with one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2983e943-cce1-effd-57d0-cce4b0c0a7e1
* Version Independent ID: 4262c40a-7140-b420-58b5-5cf40ab2316e
* Content: [az webapp](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/webapp.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
@panchagnula for the call here. Whichever way it goes, the documentation should be consistent.

**Comment by panchagnula** [comment]
Documentation should use web app , will update on our end. Thanks for reporting this.

**Comment by craigpla** [comment]
Not a problem. You're quite welcome.
