### ISSUE TITLE
az extension add failing if latest (19.0) pip is present in the machine

### ISSUE THREAD

**Issue by gauravsaralMs** [Azure/azure-cli#8319]
**Describe the bug**
`az extension add ` fails when latest pip is present in the machine
i.e. it fails after `python -m pip install --upgrade pip` is ran on any machine

**To Reproduce**
assuming azure-cli is present on the machine
run 
1. python -m pip install --upgrade pip
2. az extension add --name azure-cli-iot-ext --debug

**Expected behavior**
Extension should be installed

**Environment summary**
Machine ubuntu
sharing whole script to reproduce issue
`python -m pip install --upgrade pip `
`pip install --pre azure-cli==2.0.55 --extra-index-url https://azurecliprod.blob.core.windows.net/edge`
`az --h`
`az --version`
`az extension add --name azure-devops --debug`
`az extension add --name azure-cli-iot-ext --debug`
`az devops -h`

**Comment by gauravsaralMs** [comment]
Script output when running without pip upgrade
https://gsaralranchi.visualstudio.com/AzureCLIBug8319/_build/results?buildId=214
Script failure when running with pip upgrade
https://gsaralranchi.visualstudio.com/AzureCLIBug8319/_build/results?buildId=213

**Comment by tjprescott** [comment]
@marstr @williexu. I see pip already released 19.0.1. Does that fix the problem?

**Comment by gauravsaralMs** [comment]
> @marstr @williexu. I see pip already released 19.0.1. Does that fix the problem?

Looks like fixed with pip 19.0.1
https://gsaralranchi.visualstudio.com/AzureCLIBug8319/_build/results?buildId=222
