### ISSUE TITLE
az iot hub routing-endpoint create for storage account missing configuration parameters 

### ISSUE THREAD

**Issue by rcoccia** [Azure/azure-cli#8323]
At this moment in the creation of a storage account endpoint it is impossible to set parameter like 
batchfrequency
chunksizewindow
fileformat

the workaround is create the endpoint with defaul and after leverage the portal for specific configuration

this parameters should be added as optional

**Comment by jlian** [comment]
Thanks, we will look into this.

**Comment by jlian** [comment]
Target Nov https://msazure.visualstudio.com/One/_workitems/edit/4979320
