### ISSUE TITLE
Storage: Rsync helper for blob storage 

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#833]
Port from azure/azure-xplat-cli#1685

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.

**Comment by seguler** [comment]
We will have this functionality in AzCopy in the next few months. Could you please share the most used rsync commands here for us to take a look, and implement ? For instance, is the desire for rsync mainly for the checksum comparison capability, or is file timestamp enough ? What about partial file uploads ? 

Please share your favorite rysnc command line with options here :)

**Comment by danpritts** [comment]
My most typical rsync command line is
`rsync -av [--delete] /original /destination`

The idea is to make the destination directory tree a mirror copy of the origin.   Support that and you've probably met the 80/20 requirement.  

Mostly i don't checksum files - the default checks size+mtime+name and that is typically good enough.  However, it would be a nice feature to support in a second round.  Example usage:  A fixity check of an online backup.  Not sure how you'd pull that off without retrieving the object from storage.  If you could modify the storage backend to actually compute a checksum real-time and return it, that'd be interesting - but that's a much bigger ask.  Simply comparing the local file's checksum to the checksum you stored when you stored the object is interesting - much more so if the platform already does that fixity check on each object as part of a regular "scrub" cycle.  

I don't care much about the rsync algorithm for sending diffs of large files, although I can imagine it could be very useful in some cases - e.g., incrementally updating a vm disk image backup or a large database dump file.  

Bonus features that plain rsync doesn't support would be local encryption and compression before you upload the object.

I just came across https://rclone.org/ ; probably worth reviewing.

**Comment by yugangw-msft** [comment]
Hi folks, we have released a CLI extension with the initial support and we are looking for users to try out and give us the feedback 
```
az extension add -n storage-preview
az storage azcopy blob sync -h
```

**Comment by yugangw-msft** [comment]
With today's release, the command should be `az storage blob sync` and you don't need to install the extension any more
