### ISSUE TITLE
After SSL binding by CLI all TAGs of WebApp are erased

### ISSUE THREAD

**Issue by MacJot** [Azure/azure-cli#8333]
Hi,
I use `az webapp config ssl bind` in my automated Power Shell script.
So, I faced that after adding a banding to the WeebApp all TAGs from this WebApp were erased. I had to set the TAGs again.
When binding is set from the Azure portal, everything is OK.
Can anyone could reproduce this issue?
MacJot

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3f984d-0d48-e075-7e2f-2da5667b15cf
* Version Independent ID: 98e06d47-0ed4-4d8e-ccf5-d3a78e510539
* Content: [az webapp config ssl](https://docs.microsoft.com/en-us/cli/azure/webapp/config/ssl?view=azure-cli-latest#az-webapp-config-ssl-bind)
* Content Source: [latest/docs-ref-autogen/webapp/config/ssl.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config/ssl.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by panchagnula** [comment]
This a known issue tracked by ##6929
`az webapp config ssl bind` clears Web App tags
