### ISSUE TITLE
API Profiles should declare resources they support

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#8355]
Currently, modules that should not appear in the stack profile use a syntax like this:

```Python
class MapsCommandsLoader(AzCommandsLoader):

    def __init__(self, cli_ctx=None):
        from azure.cli.core.commands import CliCommandType
        custom_type = CliCommandType(
            operations_tmpl='azure.cli.command_modules.maps.custom#{}',
            client_factory=cf_accounts)
        super(MapsCommandsLoader, self).__init__(cli_ctx=cli_ctx,
                                                 custom_command_type=custom_type,
                                                 min_profile='2017-03-10-profile')
```

The issue is that profiles are inherently unordered, so specifying `min_profile` here is a logic bug. We need to replace this mechanism.

One option is to ensure that all services supported by a profile are registered in the `ResourceType` enum and declared in the profile definition.

Another option would be to replace `min/max_profile` with `min/max_api`.

**Comment by adewaleo** [comment]
We would need to update code that relies on the min/max API paradigm such as:
-  The [api_version_constraint decorator](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-testsdk/azure/cli/testsdk/decorators.py#L9) used in our test sdk for skipping inapplicable tests.
-  The supported_api_version [function](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/profiles/__init__.py#L24) and any methods that leverage it like this [one](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/__init__.py#L369).

There are definitely be other portions of code we would also need to update.
