### ISSUE TITLE
[Network] Add support for `enableFIPS` to app gateway create/update

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#8361]
Add support. API version 2018-04-01.

/cc @MikhailTryakhov

**Comment by tjprescott** [comment]
The value of "enableFips" is not returned by the GET call for the application gateway. Thus, I cannot know if the value I am sending works or not. I can't find the value in the portal either. Please advise.

**Comment by MyronFanQiu** [comment]
No response from the service team. I cannot test the code. Move it to the next sprint.

**Comment by MyronFanQiu** [comment]
No response from the service team. I cannot test the code. Move it to the backlog.

**Comment by yonzhan** [comment]
@MikhailTryakhov  any update about this issue ?

**Comment by MikhailTryakhov** [comment]
api version was added

**Comment by MyronFanQiu** [comment]
@MikhailTryakhov Hello. I had a discussion with @akshaysngupta offline. The current status is that the value of "enableFips" is not returned by the GET call for the application gateway. The server will return `enableFIPS: true`. However, the swagger define this field as `enableFips`. I think that's the reason.

**Comment by yonzhan** [comment]
@akshaysngupta have you looked into the enableFips inconsistency issue @MyronFanQiu mentioned ?

**Comment by yonzhan** [comment]
@surajmb @sfiguemsft @akshaysngupta  any update for this issue ?

**Comment by surajmb** [comment]
We have a backlog item to fix this. We'll update here once it's been fixed and we don't have a firm ETA now. Should we close this for now?
