### ISSUE TITLE
How do I add "key-vault-contributor" role to a resource group using azure Cli, I don't see it documented

### ISSUE THREAD

**Issue by akramwaseem** [Azure/azure-cli#8365]
Hi,
How can I add IAM based roles to a resource group using azure key-vault, I don't see a documentation on this.
please suggest or point to the right document if possible ?

Below link shows only the roles.
https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#key-vault-contributor

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfe29c90-ab37-174c-3365-d33044447272
* Version Independent ID: 3118d6a2-bb53-a881-0017-0313a15c9ef1
* Content: [az policy set-definition](https://docs.microsoft.com/en-us/cli/azure/policy/set-definition?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by akramwaseem** [comment]
@Penberthy - I need to add someone as "key-vault-contributor" to a resource group.
Can I do that using az assign roles to a resource group.which has keyvault in it and I am hoping key-vault is going to inherit the permission.

**Comment by Penberthy** [comment]
This might help, if you get a "forbidden" error then you need to be owner or have the "role assign" privildge. Example is for Reader Role but you get the idea.

## Assign Reader Role to new Identity for your keyvault
`
az role assignment create --role Reader --assignee <principalid> --scope /subscriptions/<subscriptionid>/resourcegroups/<resourcegroup>/providers/Microsoft.KeyVault/vaults/<keyvaultname>
`
 ## set policy to access keys in your keyvault
`az keyvault set-policy -n $KV_NAME --key-permissions get --object-id <object-ref-of-your-guy>`
## set policy to access secrets in your keyvault
`az keyvault set-policy -n $KV_NAME --secret-permissions get --object-id <object-ref-of-your-guy>`
## set policy to access certs in your keyvault
`az keyvault set-policy -n $KV_NAME --certificate-permissions get --object-id <object-ref-of-your-guy>`

you will also need to add the resource group argument  if the your guy isn't a resource in the same resource group as the key vault.

cribbed from https://github.com/Azure/kubernetes-keyvault-flexvol

**Comment by akramwaseem** [comment]
@Penberthy -- thanks for the info. az keyvault worked out but problem is, some of the teams cannot access the resource group at all because they are not contributors. but manually adding the azure ad group to the resource group with key-vault-contributor is working.teams can access the keyvault from the portal and through az cli.

Let me do some research and see if there is any documentation to assign roles to a resource group.
tried az --help but no luck so far.

**Comment by Penberthy** [comment]
Don't think you will be able to assign role to a resource group only to the Service principles or managed identities running the resources in that resource group.

It just a coincidence that if you create a resource group and all the resources in it then you will have the same role for all the resources in that group and the group its self, but they are not defined by your permission on the group but policy that decide what privileges you have on resources and groups you create.

This is my understanding anyway, it may be wrong, let me know how you get on.

**Comment by yugangw-msft** [comment]
On top of @Penberthy's suggestion, the help for `az role assignment create` has called out the possible values for `--assignee` which is what @akramwaseem has done, particularly the aad group.
With that, I am closing this issue, as the help is sufficient.
```
(env) D:\sdk\azure-cli>az role assignment create -h

Command
    az role assignment create : Create a new role assignment for a user, group, or service
    principal.

Arguments
    --role    [Required] : Role name or id.
    --assignee           : Represent a user, group, or service principal. supported format: object
                           id, user sign-in name, or service principal name.
```
