### ISSUE TITLE
Keyvault secret backup fails unexpected keyword argument

### ISSUE THREAD

**Issue by gavinhow** [Azure/azure-cli#8371]
**Describe the bug**
Keyvault secret backup command fails with error unexpected keyword argument
`backup_secret() got an unexpected keyword argument 'secret_version'`

**To Reproduce**
az keyvault secret backup --id {SecretId} --subscription {Subscription} --file-path test

**Expected behavior**
I assume it would download a backup of the secret to the file path I have specified.

**Environment summary**
Mac OS 10.14 with azure cli installed via Homebrew

Let me know if more information is needed

**Comment by tjprescott** [comment]
Please supply the output of `az --version`.

**Comment by gavinhow** [comment]
azure-cli (2.0.55)

acr (2.1.12)
acs (2.3.14)
advisor (2.0.0)
ams (0.3.2)
appservice (0.2.11)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.6)
billing (0.2.0)
botservice (0.1.4)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.4)
command-modules-nspkg (2.0.2)
configure (2.0.20)
consumption (0.4.2)
container (0.3.11)
core (2.0.55)
cosmosdb (0.2.7)
dla (0.2.3)
dls (0.1.7)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.2)
extension (0.2.3)
feedback (2.1.4)
find (0.2.13)
hdinsight (0.2.0)
interactive (0.4.1)
iot (0.3.4)
iotcentral (0.1.5)
keyvault (2.2.9)
lab (0.1.5)
maps (0.3.3)
monitor (0.2.8)
network (2.3.0)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.2)
rdbms (0.3.5)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.1)
resource (2.1.8)
role (2.3.0)
search (0.1.1)
security (0.1.0)
servicebus (0.3.2)
servicefabric (0.1.11)
signalr (1.0.0)
sql (2.1.7)
storage (2.3.0)
telemetry (1.0.0)
vm (2.2.12)

Extensions:
webapp (0.2.11)

Python location '/usr/local/bin/python3'
Extensions directory '/Users/gavinhow/.azure/cliextensions'

Python (Darwin) 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 03:02:14)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by schaabs** [comment]
@gavinhow I have a fix for this issue in the PR https://github.com/Azure/azure-cli/pull/8375.  As a temporary work around until the fix is published you should be able to backup a secret using the parameters --vault-name and --name rather than the --id parameter.
