### ISSUE TITLE
Live Test system should help reduce "noise" and improve triage

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#8372]
We store all of our live test results in a database. We should analyze that database to help identify certain patterns of test failures.

Recommend adding two columns to test results, "Category" and "Likely Cause":

**Category**

- Tests that sometimes fail and sometimes don't over a period of time should be labeled as "flaky". These would be the lowest priority fixes involving adding some kind of retry logic or otherwise tweaking test infrastructure to be more stable.
- Tests that have been consistently passing and suddenly fail (i.e. NEW failure) should be flagged for quick investigation. These could represent a service outage, failure of the live test systems itself, or, most critically **a CLI regression that was masked by the presence of a recording**.
- Any test failure marked "Live Only" should be a red flag, as described in a separate issue.
- Tests that have been consistently failing should be marked as such. These are often the ones where the test requires specific features to be enabled on the test subscription.

**Likely Cause**
Rather than require the user to click the link to open the logs or recording, it would be helpful if the system (A01 or an external one) would offer a best guess diagnosis. For example, cases where the subscription lacks a feature will often say "Subscription X is not registered for feature...". Even if all it did is find the root error message in the stack trace and display it, it would save us time. Any kind of non-CLI error (ValueError, TypeError, etc) should be a red flag that there's a likely CLI regression, and so on.

**Comment by yonzhan** [comment]
@bim-msft  add to S162.

**Comment by yungezz** [comment]
Seems the database isn't transitioned. @qwordy  is setting up a new live test pipeline in ADO. Current the goal is to enable efficient/accurate live test run/result. Next step is save test result for analyzing purpose. Close the issue for now.
