### ISSUE TITLE
Not possible to create alert for Select *

### ISSUE THREAD

**Issue by pascalnaber** [Azure/azure-cli#8377]
**Describe the bug**
Using the az cli it's not possible to create an alert that has configured Select *. 

Select *: Checking “Select *” will dynamically select all current and future dimension values for the dimension. 

**To Reproduce**
To select a couple of instances, this works: (note the condition)
az monitor metrics alert create -n test1234 -g myrg--scopes $WEBAPP_RESOURCEID --condition "total Http4xx > 10 where Instance includes instanceA instanceB" --window-size 5m --evaluation-frequency 1m --description "High CPU" --action HorizonsAlertActions --severity 2

which results in: 
```
"dimensions": [
          {
            "name": "Instance",
            "operator": "Include",
            "values": [
              "InstanceName",
              "InstanceName2"
            ]
          }
        ],
```

I need to check Select * and this doesn't work: (note the condition)
az monitor metrics alert create -n test1234 -g myrg --scopes $WEBAPP_RESOURCEID --condition "total Http4xx > 10 where Instance includes *" --window-size 5m --evaluation-frequency 1m --description "High CPU" --action HorizonsAlertActions --severity 2

It doesn't work using either * {*} [*] '*' in the condition.

Result:
line 1:43 token recognition error at: '*'
line 1:44 mismatched input '<EOF>' expecting {NUMBER, WHITESPACE, WORD}
Monitors: Dimension values cannot be empty. [Code: "BadRequest"]

**Expected behavior**

The result should be:
```
"dimensions": [
          {
            "name": "Instance",
            "operator": "Include",
            "values": [
              "*"
            ]
          }
        ],
```

**Comment by tjprescott** [comment]
What is the output of `az --version`?

**Comment by tjprescott** [comment]
Thanks @pascalnaber. Can you share with me the exact `--condition` syntax that doesn't work for you. Also, which shell are you using?

**Comment by pascalnaber** [comment]
--condition "total Http4xx > 10 where Instance includes *"

I'm running this in WSL ubuntu. Does this give you enough information?
