### ISSUE TITLE
az billing invoice list doesn't work

### ISSUE THREAD

**Issue by rukiaEnix** [Azure/azure-cli#8378]
running az billing invoice list gives following error:
`ERROR: DisallowedProvider - The operation is not permitted for namespace 'Microsoft.Billing'. List of permitted provider namespaces is '84codes.CloudAMQP,AppDynamics.APM,Aspera.Transfers,Auth0.Cloud,Citrix.Cloud,Citrix.Services,Conexlink.MyCloudIT,Crypteron.DataSecurity,Dynatrace.DynatraceSaaS,Dynatrace.Ruxit,Hive.Streaming,Incapsula.Waf,LiveArena.Broadcast,Lombiq.DotNest,Mailjet.Email,Microsoft.AAD,Microsoft.ADHybridHealthService,Microsoft.Advisor,Microsoft.AlertsManagement,Microsoft.AnalysisServices,Microsoft.ApiManagement,Microsoft.Authorization,Microsoft.Automation,Microsoft.AzureActiveDirectory,Microsoft.AzureStack,Microsoft.BareMetal,Microsoft.Batch,Microsoft.BatchAI,Microsoft.BingMaps,Microsoft.Blockchain,Microsoft.Blueprint,Microsoft.BotService,Microsoft.Cache,Microsoft.Capacity,Microsoft.Cdn,Microsoft.CertificateRegistration,Microsoft.ClassicStorage,Microsoft.CognitiveServices,Microsoft.Compute,Microsoft.Consumption,Microsoft.ContainerInstance,Microsoft.ContainerRegistry,Microsoft.ContainerService,Microsoft.ContentModerator,Microsoft.CostManagement,Microsoft.CustomerLockbox,Microsoft.DataBox,Microsoft.DataBoxEdge,Microsoft.Databricks,Microsoft.DataCatalog,Microsoft.DataFactory,Microsoft.DataLakeAnalytics,Microsoft.DataLakeStore,Microsoft.DataMigration,Microsoft.DataShare,Microsoft.DBforMariaDB,Microsoft.DBforMySQL,Microsoft.DBforPostgreSQL,Microsoft.Devices,Microsoft.DevSpaces,Microsoft.DevTestLab,Microsoft.DocumentDB,Microsoft.DomainRegistration,Microsoft.EventGrid,Microsoft.EventHub,Microsoft.Features,Microsoft.Functions,Microsoft.Genomics,Microsoft.HDInsight,Microsoft.ImportExport,microsoft.insights,Microsoft.IoTCentral,Microsoft.IoTSpaces,Microsoft.KeyVault,Microsoft.Kusto,Microsoft.LabServices,Microsoft.LocationBasedServices,Microsoft.LogAnalytics,Microsoft.Logic,Microsoft.MachineLearning,Microsoft.MachineLearningExperimentation,Microsoft.MachineLearningCompute,Microsoft.MachineLearningServices,Microsoft.MachineLearningModelManagement,Microsoft.ManagedIdentity,Microsoft.ManagedLab,Microsoft.Management,Microsoft.ManagementPartner,Microsoft.Maps,Microsoft.Marketplace,Microsoft.MarketplaceApps,Microsoft.MarketplaceOrdering,Microsoft.Media,Microsoft.Migrate,Microsoft.MixedReality,Microsoft.Network,Microsoft.NotificationHubs,Microsoft.OffAzure,Microsoft.OperationalInsights,Microsoft.OperationsManagement,Microsoft.PolicyInsights,Microsoft.Portal,Microsoft.PowerBI,Microsoft.PowerBIDedicated,Microsoft.RecoveryServices,Microsoft.Relay,Microsoft.ResourceGraph,Microsoft.ResourceGraph.PPE,Microsoft.ResourceHealth,Microsoft.Resources,Microsoft.ResourcesTopology,Microsoft.ResourcesTopology.PPE,Microsoft.SaaS,Microsoft.Scheduler,Microsoft.Search,Microsoft.Security,Microsoft.SecurityGraph,Microsoft.SerialConsole,Microsoft.ServiceBus,Microsoft.ServiceFabric,Microsoft.ServiceFabricMesh,Microsoft.SignalRService,Microsoft.SiteRecovery,Microsoft.Solutions,Microsoft.Sql,Microsoft.SqlVirtualMachine,Microsoft.Storage,Microsoft.StorageSync,Microsoft.StorSimple,Microsoft.StreamAnalytics,Microsoft.Subscription,microsoft.support,Microsoft.TimeSeriesInsights,microsoft.visualstudio,Microsoft.Web,Microsoft.WindowsIoT,Microsoft.WorkloadMonitor,Myget.PackageManagement,nuubit.nextgencdn,Paraleap.CloudMonix,Pokitdok.Platform,RavenHq.Db,Raygun.CrashReporting,RevAPM.MobileCDN,Sendgrid.Email,Sparkpost.Basic,stackify.retrace,SuccessBricks.ClearDB,TrendMicro.DeepSecurity,U2uconsult.TheIdentityHub'.", "stderr_lines": ["ERROR: DisallowedProvider - The operation is not permitted for namespace 'Microsoft.Billing'. List of permitted provider namespaces is '84codes.CloudAMQP,AppDynamics.APM,Aspera.Transfers,Auth0.Cloud,Citrix.Cloud,Citrix.Services,Conexlink.MyCloudIT,Crypteron.DataSecurity,Dynatrace.DynatraceSaaS,Dynatrace.Ruxit,Hive.Streaming,Incapsula.Waf,LiveArena.Broadcast,Lombiq.DotNest,Mailjet.Email,Microsoft.AAD,Microsoft.ADHybridHealthService,Microsoft.Advisor,Microsoft.AlertsManagement,Microsoft.AnalysisServices,Microsoft.ApiManagement,Microsoft.Authorization,Microsoft.Automation,Microsoft.AzureActiveDirectory,Microsoft.AzureStack,Microsoft.BareMetal,Microsoft.Batch,Microsoft.BatchAI,Microsoft.BingMaps,Microsoft.Blockchain,Microsoft.Blueprint,Microsoft.BotService,Microsoft.Cache,Microsoft.Capacity,Microsoft.Cdn,Microsoft.CertificateRegistration,Microsoft.ClassicStorage,Microsoft.CognitiveServices,Microsoft.Compute,Microsoft.Consumption,Microsoft.ContainerInstance,Microsoft.ContainerRegistry,Microsoft.ContainerService,Microsoft.ContentModerator,Microsoft.CostManagement,Microsoft.CustomerLockbox,Microsoft.DataBox,Microsoft.DataBoxEdge,Microsoft.Databricks,Microsoft.DataCatalog,Microsoft.DataFactory,Microsoft.DataLakeAnalytics,Microsoft.DataLakeStore,Microsoft.DataMigration,Microsoft.DataShare,Microsoft.DBforMariaDB,Microsoft.DBforMySQL,Microsoft.DBforPostgreSQL,Microsoft.Devices,Microsoft.DevSpaces,Microsoft.DevTestLab,Microsoft.DocumentDB,Microsoft.DomainRegistration,Microsoft.EventGrid,Microsoft.EventHub,Microsoft.Features,Microsoft.Functions,Microsoft.Genomics,Microsoft.HDInsight,Microsoft.ImportExport,microsoft.insights,Microsoft.IoTCentral,Microsoft.IoTSpaces,Microsoft.KeyVault,Microsoft.Kusto,Microsoft.LabServices,Microsoft.LocationBasedServices,Microsoft.LogAnalytics,Microsoft.Logic,Microsoft.MachineLearning,Microsoft.MachineLearningExperimentation,Microsoft.MachineLearningCompute,Microsoft.MachineLearningServices,Microsoft.MachineLearningModelManagement,Microsoft.ManagedIdentity,Microsoft.ManagedLab,Microsoft.Management,Microsoft.ManagementPartner,Microsoft.Maps,Microsoft.Marketplace,Microsoft.MarketplaceApps,Microsoft.MarketplaceOrdering,Microsoft.Media,Microsoft.Migrate,Microsoft.MixedReality,Microsoft.Network,Microsoft.NotificationHubs,Microsoft.OffAzure,Microsoft.OperationalInsights,Microsoft.OperationsManagement,Microsoft.PolicyInsights,Microsoft.Portal,Microsoft.PowerBI,Microsoft.PowerBIDedicated,Microsoft.RecoveryServices,Microsoft.Relay,Microsoft.ResourceGraph,Microsoft.ResourceGraph.PPE,Microsoft.ResourceHealth,Microsoft.Resources,Microsoft.ResourcesTopology,Microsoft.ResourcesTopology.PPE,Microsoft.SaaS,Microsoft.Scheduler,Microsoft.Search,Microsoft.Security,Microsoft.SecurityGraph,Microsoft.SerialConsole,Microsoft.ServiceBus,Microsoft.ServiceFabric,Microsoft.ServiceFabricMesh,Microsoft.SignalRService,Microsoft.SiteRecovery,Microsoft.Solutions,Microsoft.Sql,Microsoft.SqlVirtualMachine,Microsoft.Storage,Microsoft.StorageSync,Microsoft.StorSimple,Microsoft.StreamAnalytics,Microsoft.Subscription,microsoft.support,Microsoft.TimeSeriesInsights,microsoft.visualstudio,Microsoft.Web,Microsoft.WindowsIoT,Microsoft.WorkloadMonitor,Myget.PackageManagement,nuubit.nextgencdn,Paraleap.CloudMonix,Pokitdok.Platform,RavenHq.Db,Raygun.CrashReporting,RevAPM.MobileCDN,Sendgrid.Email,Sparkpost.Basic,stackify.retrace,SuccessBricks.ClearDB,TrendMicro.DeepSecurity,U2uconsult.TheIdentityHub'`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8866b243-5c18-7e9a-f233-0033d0eb64f9
* Version Independent ID: c98a81e3-ec68-5819-4a8f-897043f97371
* Content: [az billing invoice](https://docs.microsoft.com/en-us/cli/azure/billing/invoice?view=azure-cli-latest#az-billing-invoice-list)
* Content Source: [src/command_modules/azure-cli-billing/azure/cli/command_modules/billing/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-billing/azure/cli/command_modules/billing/_help.py)
* Service: **billing**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ramaganesan-rg** [comment]
thank you for the details. can you please let us know for which offer this error occurs. Need this info for troubleshooting

**Comment by msft-adrianma** [comment]
Is this issue still happening? I dont see the disallowed error happening anymore.
C:\WINDOWS\system32> az billing invoice list
UnsupportedSubscriptionType - Offer id MS-AZR-0017G is not supported.

That being said, this sdk is using 2018-11-01-preview apis which are old. There is a newer version of apis 2019-10-01-preview that you can use using REST apis.

**Comment by ramaganesan-rg** [comment]
Offer id MS-AZR-0017G is not supported. hence closing this issue.
