### ISSUE TITLE
az aks create + virtual-node doesn't work

### ISSUE THREAD

**Issue by grampelberg** [Azure/azure-cli#8383]
**Describe the bug**
When using `virtual-node` as part of `az aks create --enable-addons` , the following failure message occurs:

```
"virtual-node" is not recognized by the --enable-addons argument.
```

When using `az aks enable-addons`, it works as expected.

**To Reproduce**

Run `az aks create --enable-addons virtual-node`.

**Comment by jluk** [comment]
The syntax must follow the below. Closing but please open again if the cmd does not work for you.

```
Examples
    Enable Kubernetes addons. (autogenerated)
        az aks enable-addons --addons virtual-node --name MyManagedCluster --resource-group
        MyResourceGroup --subnet-name VirtualNodeSubnet
```
