### ISSUE TITLE
Would be nice if the documents listed sample Json responses.

### ISSUE THREAD

**Issue by willemodendaal** [Azure/azure-cli#8385]
It would be nice if the documents listed sample Json responses, so that devs can write scripts without having to create new dbs just to see what the outputs are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc8d652-2eda-296f-28ea-8d5f1ea855b3
* Version Independent ID: 80b87995-d339-61e9-1cac-b5c9ad6efe5e
* Content: [az cosmosdb](https://docs.microsoft.com/en-us/cli/azure/cosmosdb?view=azure-cli-latest#az-cosmosdb-create)
* Content Source: [src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_help.py)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
I'd recommend you take a look at the REST API reference. It contains sample requests and responses:
https://docs.microsoft.com/en-us/rest/api/azure/

The main difference in the CLI is that we flatten out "properties" so `foo.properties.bar` would simply be `foo.bar`.
