### ISSUE TITLE
Missing ErrorAction option, cannot try-catch errors

### ISSUE THREAD

**Issue by electrosonics** [Azure/azure-cli#8389]
I am building a PowerShell script and would like to trap errors like invalid login. It appears that the AZ CLI is lacking support for -ErrorAction Stop

So if there is a problem logging, I get a messy message and no way to try-catch the error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeedb9a7-2aed-6727-4cfb-1515809d676e
* Version Independent ID: 2c83180d-22ad-db42-e2eb-f27f11977963
* Content: [az](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-login)
* Content Source: [src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
CLI commands are not designed for Powershell and thus will not support Powershell-specific features. For that kind of functionality, consider using the Azure Powershell cmdlets. https://github.com/Azure/azure-powershell

**Comment by electrosonics** [comment]
I am using Azure PowerShell AZ v1.2.0 and the AZ does not accept the --ErrorAction Stop option.

I was able to get the try-catch to work by setting the global variable $ErrorActionPreference = "Stop"

David

**Comment by tjprescott** [comment]
Ah, sorry @electrosonics I misunderstood. GitHub opened your issue here because you made your comment from the Azure CLI's reference docs (as opposed to Azure Powershell). I'd recommend you copy your issue to their repo so they can address it: https://github.com/Azure/azure-powershell
