### ISSUE TITLE
Unable to run the CLI encryption command to update encryption settings for Virtual Machine Scale Sets. 

### ISSUE THREAD

**Issue by Jyotsna-Anand** [Azure/azure-cli#8392]
**Describe the bug**
Unable to run the az-cli command to encrypt Virtual Machine Scale Sets after the first time. The command errors out making it impossible to update encryption settings or disable encryption on a VMSS using az-cli. 

**To Reproduce**
1. Encrypt a VMSS using the command:  az vmss encryption enable --resource-group "MySecureRG" --name "MySecureVmss" --disk-encryption-keyvault "MySecureVault" 
2. Run the above command again on the same VM. The below error is hit:
_"On resource"MySecureVmss", extension name 'AzureDiskEncryption' cannot be used for more than one extension."_

**Expected behavior**
The command should succeed and initiate encryption on the VM again. 

**Additional context**
This issue can occur when a user tries to update encryption settings on a VM [e.g: using a different keyvault or opting to use a Key Encryption Key] or when a user tries to Disable encryption settings.

**Comment by yugangw-msft** [comment]
@adewaleo, this should be a simple fix to ensure we don't blindly add a new extension
