### ISSUE TITLE
Intellisense showing invalid argument for az group name: --rg-name

### ISSUE THREAD

**Issue by chrmarti** [Azure/azure-cli#8395]
_From @aws-scripting-guy on January 30, 2019 23:19_

Using latest Azure CLI tools for VS Code 0.4.2

Steps to reproduce the issue:

1. Typing in .azcli file
az group create 
 Intellisense suggesting --rg-name as required argument for group name.  There is also missing help (stuck in Loading)

2. Right-click and Run line in the terminal
az group create --rg-name myGroup2 \\
 --location westeurope --tags 'Environment=Test'

3. Output
az group show: error: argument --name/-n/--resource-group/-g is required

![azure_cli_rg_name](https://user-images.githubusercontent.com/16693850/52021126-200f3b00-24f4-11e9-9657-abf9b68e2975.PNG)
![azure_cli_rg_name_missing_help](https://user-images.githubusercontent.com/16693850/52020229-d2dd9a00-24f0-11e9-8405-4606bda55ae3.PNG)

Solution:
pass argument -n or --name for resource group name

_Copied from original issue: Microsoft/vscode-azurecli#44_

**Comment by chrmarti** [comment]
Can reproduce with Azure CLI 2.0.56. Related: https://github.com/Azure/azure-cli/issues/8179

**Comment by tjprescott** [comment]
We do not maintain the VSCode extension. I would recommend reopening the issue you originally posted in the vscode-azurecli repo.

**Comment by chrmarti** [comment]
@tjprescott I've moved this issue from the VS Code extension's repository because it seems to be caused by a similar discrepancy as #8179.

**Comment by tjprescott** [comment]
@chrmarti our online docs and `az interactive` are all displaying correctly in 2.0.56.

**Comment by chrmarti** [comment]
@tjprescott I'm using `cli_ctx.invocation.commands_loader.load_arguments(command.name)` to get at the arguments. Is there a new way for doing this?

**Comment by tjprescott** [comment]
@chrmarti recommend you get in touch with @adewaleo. He's familiar with what changes were made to fix docs and that would likely be what you need. Additionally, he's spearheading efforts to clarify our public signature and the functionality you guys need should be  key part of that discussion. I'd recommend reaching out to him via email.
