### ISSUE TITLE
"Expected at least one argument" error when value begins with "-"

### ISSUE THREAD

**Issue by jgallucci32** [Azure/azure-cli#8396]
**Describe the bug**
When creating a TXT record using `az network dns` the command fails if the value of the TXT record begins with a "-"

The following error is shown
> az network dns record-set txt add-record: error: argument --value/-v: expected at least one argument

**To Reproduce**
Create a TXT record with a value which starts with a "-"
```
az network dns record-set txt add-record --resource-group myresourcegroup --zone-name mydomain.com --record-set-name _mynewrecord --value "-TEST"
```

**Expected behavior**
A TXT record set is created with a value which starts with a "-"

**Environment summary**
azure-cli (2.0.56)

acr (2.1.13)
acs (2.3.15)
advisor (2.0.0)
ams (0.4.0)
appservice (0.2.12)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.7)
billing (0.2.0)
botservice (0.1.5)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.4)
command-modules-nspkg (2.0.2)
configure (2.0.20)
consumption (0.4.2)
container (0.3.13)
core (2.0.56)
cosmosdb (0.2.7)
dla (0.2.3)
dls (0.1.7)
dms (0.1.2)
eventgrid (0.2.1)
eventhubs (0.3.3)
extension (0.2.3)
feedback (2.1.4)
find (0.2.13)
hdinsight (0.3.0)
interactive (0.4.1)
iot (0.3.5)
iotcentral (0.1.5)
keyvault (2.2.10)
kusto (0.1.0)
lab (0.1.5)
maps (0.3.3)
monitor (0.2.9)
network (2.3.1)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.3)
rdbms (0.3.6)
redis (0.3.2)
relay (0.1.3)
reservations (0.4.1)
resource (2.1.9)
role (2.3.1)
search (0.1.1)
security (0.1.0)
servicebus (0.3.3)
servicefabric (0.1.12)
signalr (1.0.0)
sql (2.1.8)
sqlvirtualmachine (0.1.0)
storage (2.3.1)
telemetry (1.0.1)
vm (2.2.13)

Python location '/usr/lib64/az/bin/python'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 2.7.5 (default, Sep 12 2018, 05:31:16)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

**Additional context**
This was discovered when attempting to create pre and post validation hooks for Certbot to automatically validate DNS entries when creating/renewing a Let's Encrypt certificate. The TXT values are auto-generated by Certbot and it doesn't fail every time, only when a TXT value has a "-" at the beginning.

**Comment by tjprescott** [comment]
This is a bug in the argparse library (https://bugs.python.org/issue9334) and affects *any* value in the CLI, not just this command or argument.  The workaround is to use the alternative syntax:
`--value="-TEST"`

I've updated the title to reflect the generic nature of this issue.
