### ISSUE TITLE
az image: allow to add tags to existing image

### ISSUE THREAD

**Issue by jstodola** [Azure/azure-cli#8398]
**Is your feature request related to a problem? Please describe.**
It's not possible to add a tag to an existing image using azure-cli. The "image update" command doesn't exist in azure-cli-2.0.56-1.el7

**Describe the solution you'd like**
az image update --name $IMAGE_NAME --resource-group $RESOURCE_GROUP --set "tags.$MY_TAG=$VALUE"

**Additional context**
"az image create" allows to add tags when creating a new image, however this solution doesn't work for me, since I need to be able to tag both new and existing images.

**Comment by tjprescott** [comment]
Great point, @jstodola! 

In the meantime, you could try the following commands:
`az resource tag` This seems more relevant to your current needs
`az resource update` If you need more powerful updating capability

**Comment by jstodola** [comment]
Thanks for the hint, @tjprescott , it works for my needs.
