### ISSUE TITLE
az network nic show --query 'id' shouldn't return a line encased in double-quotes

### ISSUE THREAD

**Issue by carlosvsilva** [Azure/azure-cli#8401]
Hi.

When I run the command:
az network nic show --resource-group "$resourceGroup" -n "$nicName" --query 'id' to find out the ID of an existing NIC I get a resulting line encapsulated in double quotes, thus breaking Shell scripts like so:

$ az network nic show --resource-group "$resourceGroup" -n "$nicName" --query 'id'
"/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourceGroups/yyyyyyyyy/providers/Microsoft.Network/networkInterfaces/zzzzzzzzNic"

Can you please fix this Shell script unfriendly behavior and remove the double quotes around the lines outputed from this command? Thanks
---

### Environment summary

Install Method apt-get / azure-cli (2.0.55) / Windows 10 1809 / Shell Type (Bash on Windows)  

```
```

**Comment by tjprescott** [comment]
For scripting purposes you should be using `-o tsv`, which will remove the quotes.

**Comment by the-vampiire** [comment]
@tjprescott this is a useful fact to add to the documentation at least man. 

what about just switching to tsv automatically for single string outputs if executed in a bash shell? is there a use case im overlooking for outputting with literal quote characters?
