### ISSUE TITLE
webapp & functionapp: Add support for adding IP Restrictions to webapp or functionapp

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-cli#8407]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Chedberg84** [comment]
Hi, 
I'm wondering if this is something that is going to happen. I'd like to be able to add ip restrictions to an Azure Function App programmatically. It that possible? This is currently the closest solution I've seen: 
https://docs.microsoft.com/en-us/azure/app-service/app-service-ip-restrictions

**Comment by panchagnula** [comment]
You can achieve this as follows, we will still look into making this a first class command if still needed. 

az webapp config set --generic-configurations @"ipsec.json" -g <RG> -n <AppName> 
and the IPSec.json can have the IpRestrictions object you want to set. See the example JSON

{
  "ipSecurityRestrictions": [
    {
      "action": "Allow",
      "ipAddress": "208.13.0.0/16",
      "name": "test",
      "priority": 300,
      "tag": "Default"
    }
  ]
}

**Comment by panchagnula** [comment]
@ccompy can you share your commandlet design for doing this? with the current SDK we have we can start working on this work item. Thank you.

**Comment by mdddev** [comment]
@panchagnula your workaroudn works fine, thank you! However, I think there is a slight syntax error. It only works for me if I reference the json file (as value to the --generic-configurations) like this:

az webapp config set --generic-configurations "@ipsec.json" -g group -n name ("at" within the quotes)
