### ISSUE TITLE
Incorrect instructions in error message

### ISSUE THREAD

**Issue by AgSync-Aaron** [Azure/azure-cli#8411]
**Describe the bug**
The command line parameters [here](https://github.com/Azure/azure-cli/blob/cfb9d22243897aa4b0bccf664a2828b9cda18870/src/command_modules/azure-cli-network/azure/cli/command_modules/network/_validators.py#L639) are incorrect. I receive the error message 
```
az network lb create: error: incorrect usage: --subnet NAME --vnet-name NAME | --subnet ID | --public-ip NAME_OR_ID
```
When it should be `--public-ip-address` based on `az network lb create --help`
```
az network lb create: error: incorrect usage: --subnet NAME --vnet-name NAME | --subnet ID | --public-ip-address NAME_OR_ID
```

**To Reproduce**
Run `az network lb create ...`

**Expected behavior**
Get correct instructions for the command line parameters.

**Environment summary**
Windows subsystem for linux (Debian)
Install Method: apt-get
CLI version: azure-cli (2.0.56)
OS version: Windows 10
Shell Type: Bash on Windows

**Additional context**
None.

**Comment by tjprescott** [comment]
Hi @AgSync-Aaron thanks for the report! We will get this fixed for our upcoming release.

**Comment by tjprescott** [comment]
Thanks for the PR @AgSync-Aaron. Your fix will be visible after the next release.
