### ISSUE TITLE
Where is the YAML definition?

### ISSUE THREAD

**Issue by katlimruiz** [Azure/azure-cli#8415]
There is no where to find the YAML definition so we know which are all the fields available

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e5d1da7-7c4f-c9e6-e4b9-a30407675acf
* Version Independent ID: ba32e12d-8283-f980-e1d0-1ca2a75a5152
* Content: [az container](https://docs.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-container/azure/cli/command_modules/container/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by i3anaan** [comment]
I agree with you, I ran into the same problem.
Best I can give you is a little trick/workaround:

use container show to get a response json object that contains most of the fields, you can then mirror this structure in your yaml file.

Not a full solution, but did help me a bit, hope it does for you too!

**Comment by lilyjma** [comment]
@dkkapur please take a look
