### ISSUE TITLE
Add more info about creating receivers

### ISSUE THREAD

**Issue by macux** [Azure/azure-cli#8419]
Would be helpful to have more info on creating action group receivers under the action-group create command in this doc. This github issue has more info but took me a little while to find it (yes I should have just tried --help but wouldn't hurt to add more info to this doc as well):

https://github.com/Azure/azure-cli/issues/7370

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c03d4ff4-4752-4ed4-2f6c-312ff3fd9fd8
* Version Independent ID: 822e4b3b-4079-9a88-2525-715c8d4ea90a
* Content: [az monitor action-group](https://docs.microsoft.com/en-us/cli/azure/monitor/action-group?view=azure-cli-latest#az-monitor-action-group-enable-receiver)
* Content Source: [src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
This info is contained in the CLI if you run the command with `-h`. Unfortunately, the online docs currently do not display the additional info. 

https://github.com/MicrosoftDocs/azure-docs-cli/issues/1264

Please reference the above issue and add your comment.
