### ISSUE TITLE
Servicebus subscription Message TTL changes to weird number when updating forwardTo

### ISSUE THREAD

**Issue by johnknoop** [Azure/azure-cli#8424]
When updating a topic subscription to forward it´s messages to another topic:

```bash
az servicebus topic subscription update --forward-to XXXX --namespace-name X -g "Default-ServiceBus-NorthEurope" --topic-name XX -n XXX
```

It changes the "Message time to live" to a weird number:

![image](https://user-images.githubusercontent.com/3394270/52232834-d50f7200-28bd-11e9-9724-1de7c27f3a28.png)

I've tried to change that number to 1 in the portal, but that overwrites the "forwardTo", which means I have to run the cli command again, which brings back that weird number.

**Comment by jfggdl** [comment]
@johnknoop, this is actually by design. while forwardto is set, the system will update the ttl to timespan.max and this is the value to represent it. because while forwardto is set, the message expiration will no longer be applied.

Please let us know if you have any more questions.

**Comment by johnknoop** [comment]
Ok, thanks!
