### ISSUE TITLE
Application Gateway Support for conditions and ruleSequence in Header CRUD

### ISSUE THREAD

**Issue by sobaner** [Azure/azure-cli#8428]
**Is your feature request related to a problem? Please describe.**

CLI needs to be updated according to the NRP and swagger changes.
Two new properties - conditions and ruleSequence is added in RewriteRuleSet in the applicationGateway resource.

**Describe the solution you'd like**
Need CLI to be written as per the [Swagger Changes](https://github.com/Azure/azure-rest-api-specs/pull/5009)

**Comment by tjprescott** [comment]
@sobaner please provide the following information for us to begin work on this feature:

**Comment by sobaner** [comment]
Hi @tjprescott here are the answers for the queries raised by you:

1. Description of the feature can be found in the following Swagger PR descriptions - 
     - https://github.com/Azure/azure-rest-api-specs/pull/4331
     - https://github.com/Azure/azure-rest-api-specs/pull/5009
     Apart from that, I will email you the API design document for further reference.

2. Minimum API version Required:
     - 2018-12-01

3. Swagger Link:
     The swagger link is given in the above points - but here let me share you with the path of the file in master branch.
      - File Path: [Azure/azure-rest-api-specs/commits/master/specification/network/resource-manager/Microsoft.Network/stable/2018-12-01/applicationGateway.json](url)

4. Target Date:
     The plan is to get things ready for customer by middle of March, 2019

**Comment by tjprescott** [comment]
This will be the experimental scenario for #8055.

```
az network application-gateway rewrite-rule set create -g tjp-rg --gateway-name gw1 -n rewrite1 --cache
az network application-gateway rewrite-rule create -g tjp-rg --gateway-name gw1 --ruleset-name rewrite1 -n rule1 --sequence 1 --request-headers FOO=BAR --response-headers FOO=BAR --cache
az network application-gateway rewrite-rule condition add -g tjp-rg --gateway-name gw1 --ruleset-name rewrite1 -n rule1 --variable http_req_Authorization --pattern "^Bearer" --ignore-case --negate false
```
