### ISSUE TITLE
Profile system requires an entry even if not supported.

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#8434]
**Describe the bug**
ACR has converting their module to multi-API format. They are only supported on profile `latest` and are not part of either profile listed in the REST API specs repo:
https://github.com/Azure/azure-rest-api-specs/tree/master/profile

However, they had to add their key to each of those unsupported profiles or the CI failed:
https://github.com/Azure/azure-cli/pull/8417#discussion_r253982550

**Expected behavior**
If a profile doesn't support a service, the fact that it isn't in that profile should illustrate that. It shouldn't crash.

**Environment summary**
azure-cli (2.0.58)

**Comment by tjprescott** [comment]
Relates closely to #8355

**Comment by adewaleo** [comment]
Has this been closed / handled by @limingu already, @tjprescott?

**Comment by limingu** [comment]
Yes, It has been handled.

**Comment by adewaleo** [comment]
nice! Closing this then
