### ISSUE TITLE
Azure CLI support to read and write messages to ServiceBus queue?

### ISSUE THREAD

**Issue by foobar008** [Azure/azure-cli#8435]
Azure CLI has support to manage Servicebus queues, but don't support for reading/writing from/to queues. Is this option supported? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 124549e3-8a58-b07e-7e8d-e4655ef561bb
* Version Independent ID: ea61fbb9-1283-40a7-afaa-26349931ac7e
* Content: [az servicebus](https://docs.microsoft.com/en-us/cli/azure/servicebus?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-servicebus/azure/cli/command_modules/servicebus/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-servicebus/azure/cli/command_modules/servicebus/_help.py)
* Service: **service-bus**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by marstr** [comment]
Howdy @foobar008, you are correct. Data-plane Service Bus interaction isn't supported today. Mind describing the scenario you had in mind for using the CLI to publish Service Bus messages or subscribe to queues/subscriptions?

More and more of our SDKs are providing support for data-plane Service Bus interactions. Until it's supported here, I would checkout out:
- https://github.com/Azure/azure-service-bus-dotnet
- https://github.com/Azure/azure-service-bus-java
- https://github.com/Azure/azure-service-bus-go
- https://github.com/Azure/azure-service-bus-python
- https://github.com/Azure/azure-service-bus-node

**Comment by marstr** [comment]
Because we're not planning on adding this for the moment, and because the question is answered I'm going to close this issue. However, I'd love to continue to use this thread to discuss your scenario.

**Comment by evancarey** [comment]
I made it here because I'm migrating from az storage queue to service bus. I assumed there'd be a similar set of methods as described [here](https://docs.microsoft.com/en-us/cli/azure/storage/message?view=azure-cli-latest) for service bus queues/messages. I use the cli for testing/development of queue clients. Was hoping to have the same capability for dev of service bus clients.

**Comment by AlexanderAnishchik** [comment]
@marstr Howdy. I'm wondar what is the best way to send a message to Service Bus from my Azure Devops CI/CD Release pipeline? If I cant run c# code here and Azure CLI does not support it what should I do?

**Comment by santoshsinha100** [comment]
Can you please provide us the AZURE CLI command to create a service bus premium pricing tier?. I heard at present this is not supported. Can you please provide an ETA on that ?

**Comment by marstr** [comment]
Howdy, I'm no longer on the Azure CLI team and have no operational knowledge of when Service Bus data-plane operations will be supported.
