### ISSUE TITLE
Azure CLI cannot update BGP settings on VPN connections across subscriptions

### ISSUE THREAD

**Issue by captainbrown** [Azure/azure-cli#8439]
**Describe the bug**
Let's say we have 2 subscriptions: Sub1 and Sub 5
We then have a VNET in a respective resource group on each subscription.  It appears the module fails to run an update since the vpn-connection has a connection in each subscription.

$az network vpn-connection update -n VNet1toVNet5 -g TestRG1 --enable-bgp true
Resource group 'TestRG5' could not be found.
$

**To Reproduce**
Steps to reproduce the behavior.
$az network vpn-connection update -n VNet1toVNet5 -g TestRG1 --enable-bgp true
Resource group 'TestRG5' could not be found.
$

**Expected behavior**
$az network vpn-connection update -n VNet1toVNet5 -g TestRG1 --enable-bgp true
VPN-connection now has BGP enabled.   Hurray.
$
**Environment summary**
$ az --version
azure-cli (2.0.51)

acr (2.1.9)
acs (2.3.11)
advisor (2.0.0)
ams (0.3.0)
appservice (0.2.7)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.4)
billing (0.2.0)
botservice (0.1.1)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.4)
command-modules-nspkg (2.0.2)
configure (2.0.19)
consumption (0.4.0)
container (0.3.9)
core (2.0.51)
cosmosdb (0.2.5)
dla (0.2.3)
dls (0.1.5)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.1)
extension (0.2.3)
feedback (2.1.4)
find (0.2.12)
hdinsight (0.1.0)
interactive (0.4.0)
iot (0.3.4)
iotcentral (0.1.4)
keyvault (2.2.7)
lab (0.1.3)
maps (0.3.2)
monitor (0.2.7)
network (2.2.9)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.2)
rdbms (0.3.5)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.1)
resource (2.1.6)
role (2.1.10)
search (0.1.1)
servicebus (0.3.2)
servicefabric (0.1.8)
signalr (1.0.0)
sql (2.1.5)
storage (2.2.5)
telemetry (1.0.0)
vm (2.2.8)

Python location '/usr/lib64/az/bin/python'
Extensions directory '/home/bisaacs/.azure/cliextensions'

Python (Linux) 2.7.5 (default, Sep 12 2018, 05:31:16)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

Legal docs and information: aka.ms/AzureCliLegal

**Additional context**

**Comment by tjprescott** [comment]
Hi @captainbrown I will take a look at this in the upcoming sprint. Thanks for the report.
