### ISSUE TITLE
Azure CLI install on tinycore question.

### ISSUE THREAD

**Issue by RavSalgado** [Azure/azure-cli#8440]
---

### Environment summary

The machine is running Mac OSx, with Docker toolbox that starts up a VM in virtual box.
VM is a tinycore default VM.

How can I install Azure CLI on the VM?
Tried https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest. But I must be doing some pre req step wrong since I cannot get it to work.

Any help would be greatly appreciated.

```
```

**Comment by marstr** [comment]
@RavSalgado, mind providing more information about the problem you're seeing? What error pops up when you try to install? Also, what OS is the VM running?

**Comment by RavSalgado** [comment]
Sure, The VM runs a custom Linux build, tinycore. I run through the python, libffi and OpenSSL install, then the script "curl -L https://aka.ms/InstallAzureCli | bash" cmd.

Am I missing something here? 

I'v atached a screen shott. 
![screen shot 2019-02-06 at 12 09 17 pm](https://user-images.githubusercontent.com/40475586/52363355-24fa5000-2a08-11e9-9b36-d4dc50d71412.png)

Thanks.

**Comment by marstr** [comment]
Ah, got it. This is actually a dup of https://github.com/Azure/azure-cli/issues/8353 and will get fixed when the next version drops. In the mean-time you should be able to work around it by download the install script from https://aka.ms/InstallAzureCli and modifying the line that uses `mktemp` to:

``` bash
install_script=$(mktemp -t azure_cli_install_tmp_XXXXXX) || exit
```
> Note: the differences is two extra `X` characters in the directory name template.

Once that is done, you should be able to install the CLI by running the following from the directory where you downloaded the script:

``` bash
. install
```

**Comment by RavSalgado** [comment]
Thanks, @marstr I had to do a few extra steps and set the $PATH, but now AZ is running without issue. Thank you for your help. closing issue.
