### ISSUE TITLE
incorrect example for az network dns zone export

### ISSUE THREAD

**Issue by jaypharis** [Azure/azure-cli#8446]
In the arguments, `-o mysite_com_zone.tsv` is listed, it should read `-f mysite_com_zone.tsv`. `-o` is used for output format.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ccaec50-407e-bf8a-6004-a824c2094c5b
* Version Independent ID: 8d2f2443-7636-2462-7806-0916a8603a0d
* Content: [az network dns zone](https://docs.microsoft.com/en-us/cli/azure/network/dns/zone?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Thanks for the report @jaypharis

**Comment by tjprescott** [comment]
@adewaleo any ideas why the example linter didn't catch this problem?  Does it not evaluate enums?

**Comment by adewaleo** [comment]
@tjprescott, the linter only evaluates that correct parameters are used. It does not do any parameter value validation. However, I can definitely add a parameter value linter rule or update the current rule.
