### ISSUE TITLE
Trouble with az vm create

### ISSUE THREAD

**Issue by WiseMack** [Azure/azure-cli#8450]
**Describe the bug**
Attempt to create a vm, using a bunch of arguments in addition to the ones showed in the examples
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/tutorial-secure-web-server
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/tutorial-secure-web-server

**To Reproduce**
Type code
```
keyvaultName="airheadsbcKeys"
az keyvault update --name $keyvaultName --enabled-for-deployment true
admin="j007am"
keyFile=$(cat ~/.ssh/id_rsa.pub)
resourceGroup="airheadsbc"
VMName="VMInstance"
location="Canada Central"
bootDiagStorage="airheadsbcdiag"
customData="cloud-init-web-server.txt"
subs="Pay-As-You-Go"
nics="instancevm231"
image="Bitnami:simplemachinesforum:2-0:2.0.1811302007"
cert="airheadsbcCert"
secret=$(az keyvault secret list-versions --vault-name $keyvaultName --name $cert --query "[?attributes.enabled].id" --output tsv)
vm_secret=$(az vm secret format --secret "$secret" --keyvault $keyvaultName --resource-group $resourceGroup --subscription $subs)

az vm create --name $VMName --resource-group $resourceGroup --admin-username $admin --authentication-type ssh --boot-diagnostics-storage $bootDiagStorage --custom-data $customData --image $image --location $location --nics $nics --ssh-key-value $keyFile --subscription $subs --secrets $vm_secret
```
**Expected behavior**
Created VM with the given parameters

**Result**
```
az vm create --name $VMName --resource-group $resourceGroup --admin-username $admin --authentication-type ssh --boot-diagnostics-storage $bootDiagStorage --custom-data $customData --image $image --location $location --nics $nics --ssh-key-value $keyFile --subscription $subs --secrets $vm_secret
az: error: unrecognized arguments: Central AAAAetc(It prints my ssh id_rsa.pub file right here)
```
The Central part should be a reference to the location... but the nic is between the location and ssh parameters, so I'm not sure what is going on

Note
I ran
`echo $keyFile`
to confirm that the ssh file was stored correctly, and this IS the case, there is NO "Central" at the beginning of the ssh file.

**Environment summary**
CLI 2.0, bash (the one from the azure website)

**Additional context**
This is a project I've been working for for quite some time, I will add some references to other issues I made to point out that while the topic is the same the problem isn't.

#8172 This one was my mistake
#8162 This one was a result of attempting to use a bash script in PowerShell (Despite the fact that nowhere in the tutorial does it indicate whether I should be using bash and PowerShell)
And as @tjprescott said 
"Fundamentally, the problem here is that you are trying to use a script that is written for Linux bash in Powershell. That will not work. I have opened an issue in the docs repo for that tutorial to request that they clarify that it only works in Bash."
A note that I feel should be here, based on the fact that I am following the tutorial should make it clear that I am not an expert in Azure CLI, bash, Cloud Shell. However you want to call it, if the tutorial does not point something out like this code should work in Bash/Power Shell, I will assume that it should work in either.
https://github.com/MicrosoftDocs/azure-docs/issues/21618 
Is me pointing out that there was something wrong the tutorials
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/tutorial-secure-web-server
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/tutorial-secure-web-server
But unfortunately, I didn't understand what the problem was...

Note:
Please add a tutorial (https://docs.microsoft.com/en-us/azure/virtual-machines/)  where it explains what bash is, what powershell is and what are some of the common differences in syntax (which would allow the user to figure out whether a given example is either based on the syntax
For example
in  Power Shell
$var = "var123"
which if I tried to use in bash would throw an error.
In bash
var=var123
var="var123"
You have to remove the $ and spaces before and after the =

**Comment by tjprescott** [comment]
Hi @WiseMack I agree the tutorial should point out that it uses bash specific syntax or direct you to choose a bash shell in Cloud Shell rather than Powershell. I opened an issue with just that feedback and they have taken it under advisement.
https://github.com/MicrosoftDocs/azure-docs/issues/24311

However, this team does not write tutorials, including the ones you reference. If there are problems with those tutorials, you need to open the issue from that page. I see you *have* done that, and that is the correct course of action.

To request new tutorials, please make your request here:
https://github.com/MicrosoftDocs/azure-docs/issues

If you encounter problems with the in-product examples (displayed when you run a command with -h) or otherwise encounter a CLI bug, this would be the appropriate repo to open an issue.

Keep in mind that if examples use any shell-specific syntax, it is bash-specific syntax.

**Comment by WiseMack** [comment]
@tjprescott 
Is there any chance you could answer my question before closing the issue? It is
```
az vm create --name $VMName --resource-group $resourceGroup --admin-username $admin --authentication-type ssh --boot-diagnostics-storage $bootDiagStorage --custom-data $customData --image $image --location $location --nics $nics --ssh-key-value $keyFile --subscription $subs --secrets $vm_secret
```
THIS ERROR produced when executing the previous command
```
az: error: unrecognized arguments: Central AAAAetc(It prints my ssh id_rsa.pub file right here)
```
I will certainly open a new issue over in https://github.com/MicrosoftDocs/azure-docs/issues, but I still would like an answer to my problem.

**Comment by tjprescott** [comment]
I would recommend trying this:
`--ssh-key-value @"~/.ssh/id_rsa.pub"`

**Comment by WiseMack** [comment]
@tjprescott 
So I ask, WHY is the recommended action NOT using a variable?

What is the reason?
This works
```--location "Canada Central"
--ssh-key-value @"~/.ssh/id_rsa.pub"
```
And this doesn't work?
```
location="Canada Central"
keyFile=$(cat ~/.ssh/id_rsa.pub)
--location= $location
--ssh-key-value $keyFile
```

There is no reason for a parameter to accept variables If it is only going to take half of it..
When the parameter --location recognizes "Canada Central" but doesn't recognize the variable  $location, there is a problem.

**Comment by tjprescott** [comment]
The recommendation for `--ssh-key-value` comes directly from the examples for VM create, which you see when running `az vm create -h`. Whatever syntax the tutorial is suggesting clearly isn't working for you, which would be an issue with that tutorial. 

`--location= $location` doesn't work because it would be the same as `--location= "Canada Central"` which also doesn't work. If you used `--location $location` it would work fine.
