### ISSUE TITLE
webapp:Adding tests for hybrid connection and vnet integration methods. 

### ISSUE THREAD

**Issue by singlessis** [Azure/azure-cli#8453]
**Is your feature request related to a problem? Please describe.**
In the future, I want to add more tests for the hybrid connection and vnet-integration commands, as I have had a lot issues with how difficult the required relay libraries can be to work with. This will require a lot more research, and potentially reaching out to the relay team

**Comment by panchagnula** [comment]
closing this since we already finished this.
