### ISSUE TITLE
[Network] Support new 2016-06-01 operations

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#846]
With API version 2016-06-01, there are new operations that didn't exist before.
Add these operations to the CLI.

From a diff between the following files, I found the new operations listed below:
https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-network/2016-03-30/swagger/network.json
https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-network/2016-06-01/swagger/network.json

- [x] `nic get-effective-route-table`
- [x] `nic list-effective-nsg`
- [x] `vnet peering delete`
- [x] `vnet peering show`
- [x] `vnet peering create`
- [x] `vnet peering update` (generic update)
- [x] `vnet peering list`
- [x] `vnet check-ip-address`

**Comment by mayurid** [comment]
@tjprescott : Could you take a look? @burtbeil as fyi
