### ISSUE TITLE
az acr helm push .. command fails with error 'Please run az login'

### ISSUE THREAD

**Issue by dikhakha** [Azure/azure-cli#8460]
az acr helm push command is failing with error

**ERROR: Please run 'az login' to setup account.**
Full command: az acr helm push -n <> sampleapp-v0.2.0.tgz -u <> -p <>

This command is executed  as bash script in Azure DevOps pipelines running on Hosted Ubuntu agent. I could repro this issue locally on Windows machine using az-cli version 2.0.57. On debugging, I found that this command works on az-cli version 2.0.52 and started failing there after for version 2.0.55. 

There are several stack Stackoverflow threads opened:
https://stackoverflow.com/questions/54513537/az-login-fails-wih-azure-devops-pipelines/54546350#54546350
https://stackoverflow.com/questions/54497214/azure-devops-pipeline-asks-to-run-az-login-to-setup-account/54546463#54546463

Question on Microsoft developer community - https://developercommunity.visualstudio.com/content/problem/446195/az-acr-helm-push-failes-in-pipeline-second-try.html

Can someone please take a look at this? Appreciate the help!

**Comment by djyou** [comment]
See reference to this issue https://github.com/AzureCR/azure-cli/issues/302

We had blockers that prevented us from allowing runtime commands without `az login`. After offline discussions with the team and given that ACR is in the process of deprecating Classic registries, we provided a workaround in https://github.com/Azure/azure-cli/pull/8455 that will be available in the next release.

**Comment by tjprescott** [comment]
Thanks @djyou. Closing this issue.
