### ISSUE TITLE
az eventgrid event-subscription create not working in Powershell 

### ISSUE THREAD

**Issue by andrefsoliveira** [Azure/azure-cli#8465]
Hi all,

i'm trying to create a new eventgrid topic webhook subscription to trigger a logicapp endpoint using Azure CLI (v2.0.57) via Windows Powershell, but it's not working as expected.

I'm do the same thing on the azure portal and also on CloudShell web interface and it's works perfectly. 

The command is the follow:

`az eventgrid event-subscription create --name "sopas" --source-resource-id "/subscriptions/id/resourceGroups/name/providers/Microsoft.EventGrid/topics/name" --endpoint-type "webhook" --endpoint "https://prod-16.westeurope.logic.azure.com:443/workflows/xxx/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=xxx" --debug --verbose`

The error on windows powershell is the follow:

```
az : ERROR: The attempt to validate the provided endpoint https://prod-16.westeurope.logic.azure.com/workflows/371848cd5a2242cda3f88bfcce80962a/triggers/manual/paths/invoke failed. For more details, visit 
https://aka.ms/esvalidation.
At line:3 char:1
+ az eventgrid event-subscription create --name "sopas" --source-resour ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: The atte...s/esvalidation.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
'sp' is not recognized as an internal or external command,
operable program or batch file.
'sv' is not recognized as an internal or external command,
operable program or batch file.
'sig' is not recognized as an internal or external command,
operable program or batch file.
```
Am I doing something wrong ?

Can someone help ?

Thanks!

**Comment by tjprescott** [comment]
You need to properly escape the `&` character in your string for Powershell, which is typically the backtick ( ` )

**Comment by tjprescott** [comment]
From the error, it is clear that Powershell is splitting your line by the `&` character before it reaches the CLI. Unfortunately, we are unable to provide support for shell-specific issues like this. You will need to figure out how to disable this Powershell feature or escape your strings to avoid such behavior.

Alternatively, consider running your scripts in Linux bash or Windows CMD.exe, which have far fewer issues like this and are easier to overcome when they do occur.
