### ISSUE TITLE
Support end-date on az ad app credential reset

### ISSUE THREAD

**Issue by davidmatson** [Azure/azure-cli#8468]
**Is your feature request related to a problem? Please describe.**
I can't create a credential that matches the portal "Never" expires usage.

**Describe the solution you'd like**
Allow specifying a specific end-date when doing "az ad app credential reset" rather than just a relative number of years.

**Describe alternatives you've considered**
Specify a large relative number of years, but the expiration date won't match what the portal has for "Never" (always 2299-12-31).

**Additional context**
A fixed end-date would also be consistent with how az ad app create and update work.

**Comment by omerlh** [comment]
I need this feature for another reason - currently, you cannot create credentials for less than a year. I want to create credentials that are valid only for 6 months - but you can pass 0.6 as value to `--years` parameter.
