### ISSUE TITLE
Support credential-description on az ad app app create and update

### ISSUE THREAD

**Issue by davidmatson** [Azure/azure-cli#8469]
**Is your feature request related to a problem? Please describe.**
Creating a credential via az ad app create/update have the same feature set as az ad app credential reset. One allows fixed end dates, the other relative. One does not supports credential descriptions (except via --set), the other does.

**Describe the solution you'd like**
Add a credential-description parameter to az ad app create and update.

**Describe alternatives you've considered**
Use az ad app credential reset, but that doesn't support fixed end dates currently. Use az ad app update with --set, but that gives a warning, requires encoding logic, and is tricky syntax.

**Comment by yugangw-msft** [comment]
Both `az ad app create` and `az ad app credential reset` have got the support now. Please use the latest installer
