### ISSUE TITLE
'visibility' missing in results

### ISSUE THREAD

**Issue by rgerbranda** [Azure/azure-cli#8473]
I would like to know/show if a group is 'Private' or 'Public'.

CLI doesn't give this information
 (while the Graph API does: https://graph.microsoft.com/v1.0/groups?$select=displayName,visibility&$orderby=displayName)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34960494-f5eb-4144-b508-0573f7382e40
* Version Independent ID: 0c7138d1-9849-0b71-8e76-22d0116ff663
* Content: [az ad group](https://docs.microsoft.com/en-us/cli/azure/ad/group?view=azure-cli-latest#az-ad-group-list)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
CLI supports AAD graph, which is different from MS Graph like your link points out.
I cross checked the response payload and confirmed this field is MS graph specific.
