### ISSUE TITLE
az webapp deployment source config command fails when trying to add an external repository using a url that isn't one of certain hostnames

### ISSUE THREAD

**Issue by gabesmsft** [Azure/azure-cli#8476]
_From @gabesmsft on February 8, 2019 18:26_

_From @gabesmsft on February 8, 2019 4:22_

If I try to use the Azure CLI command az webapp deployment source config to add an external repository using a url that doesn't use a hostname such as GitHub.com, Bitbucket.org, dev.azure.com (or technically onedrive.com or dropbox.com), it fails with error indicating that the repo-url has an invalid value.

For example, I am trying to add a GitLab external repository via the following command:
az webapp deployment source config --repo-url https://gitlab.com/myfakeaccount/myfakeproj.git --branch master --repository-type externalgit --name myfakeappservice --resource-group myresourcegroup --subscription myfakesubid

This fails with the following error:
The parameter https://gitlab.com/myfakeaccount/myfakeproj.git has an invalid value.

If I add the external repository using the same url via the portal, it succeeds. So it would seem that adding the url via CLI should be allowed, but is presumably failing because CLI validates against a list of specific repo hostnames.

If I then use the cli to get the repository info, it returns the repoUrl as expected. Eg:
az webapp deployment source show --name myfakeappservice --resource-group myresourcegroup --subscription myfakesubid

So the issue appears to be specific just to adding the repoUrl.

_Copied from original issue: Azure/azure-functions-core-tools#1028_

_Copied from original issue: gabesmsft/fakeplaceholder#1_

**Comment by gabesmsft** [comment]
_From @ankitkumarr on February 8, 2019 17:59_

Hi @gabesmsft, this is the repository for Azure Functions CLI for local development (`func`). For Azure CLI (`az`) (Azure management operations), please move the issue to the [Azure CLI repository](https://github.com/Azure/azure-cli).

Thanks!

**Comment by suwatch** [comment]
For external repo, Kudu will need to be able to do git fetch from that.   There are 2 scenarios we support.

- External repo is https to any publicly-accessible git repo.   If it is not, Kudu will not be able to fetch it – it will fail nonetheless.
- External repo is ssh which user has set up private SSH key with Kudu (see https://github.com/projectkudu/kudu/wiki/Continuous-deployment#for-private-repos-set-up-a-deploy-key). 

In this case, you are using https - so make sure your repo is valid and publicly accessible.

**Comment by gabesmsft** [comment]
The invalid value error reproduces when using a public repository via https. Eg: https://gitlab.com/gabes_msft/fakepublicrepo.git

Note: It also reproduces when using a private repository via the SSH URI. Eg:
git@gitlab.com:gabes_msft/fakeproj.git

I am able to add either external repository if I use az resource update as a workaround. Eg:
az resource update --resource-group MyRG --namespace Microsoft.Web --parent sites/MyAppServiceName--resource-type sourcecontrols --name web --set properties.repoUrl=git@gitlab.com:MyGitLabAccount/MyProject.git properties.branch=master properties.IsManualIntegration=true properties.deploymentRollbackEnabled=false properties.isMercurial=false

**Comment by panchagnula** [comment]
Closing this since this an old issue looks like there is an existing workaround. Please file a new issue if this is still a concern.

**Comment by markor002002** [comment]
The issues is still present after 4 years. 
No matter what I set for --repository-type externalgit is always isMercurial=true
