### ISSUE TITLE
Parameter missing, Parameter not working

### ISSUE THREAD

**Issue by mhofmann-hb** [Azure/azure-cli#8486]
There is no --disk Parameter documented for existing Disks. 
The --subscription Parameter is not working, neither with a Variable nor with a Subscription ID: "Subscription 'SUBSCRIPTION' not found. Check the spelling and casing and try again."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbc06453-93e1-e616-9649-c1487c605a65
* Version Independent ID: 76d52328-613f-bd5f-7daf-f62841300e2b
* Content: [az vm disk](https://docs.microsoft.com/en-us/cli/azure/vm/disk?view=azure-cli-latest#az-vm-disk-attach)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by mhofmann-hb** [comment]
I will close the Ticket, with Azure CLI 2.0.57 there is no --disk parameter anymore. The --subscription Error was my fault.

**Comment by mhofmann-hb** [comment]
see above

**Comment by SteveBurkettNZ** [comment]
Still mention of the --disk parameter in the 'Attach a managed persistent disk to a VM. (autogenerated)' example.
