### ISSUE TITLE
Create budget notification missing

### ISSUE THREAD

**Issue by davidobrien1985** [Azure/azure-cli#8488]
**Is your feature request related to a problem? Please describe.**
When creating a budget on a subscription or resource group we also need to configure notifications when reaching certain % of those budgets. This currently doesn't seem to be possible via https://docs.microsoft.com/en-us/cli/azure/consumption?view=azure-cli-latest

**Describe the solution you'd like**
I'd like the CLI to support the same functionality the PowerShell module already supports:
https://docs.microsoft.com/en-us/powershell/module/azurerm.consumption/set-azurermconsumptionbudget?view=azurermps-6.13.0#examples (Example 2)

**Describe alternatives you've considered**
Use PowerShell, but for my current customer that is not an option.

**Comment by achandmsft** [comment]
@ms-premp Can someone from your team look into this? 

- ContactEmails are supported in the REST API [here](https://github.com/Azure/azure-rest-api-specs/blob/380e8e584ff924d9c175db7e0eabfba25447bf7d/specification/consumption/resource-manager/Microsoft.Consumption/stable/2018-10-01/consumption.json#L3900) 
- Corresponding Python SDK is [here](https://github.com/Azure/azure-sdk-for-python/blob/d59956a893037d98a46ba299885c18ac66edb149/azure-mgmt-consumption/azure/mgmt/consumption/models/notification.py#L27) 

Any help is much appreciated.

**Comment by ms-premp** [comment]
acknowledged

**Comment by davidobrien1985** [comment]
@ms-premp any updates on this when this might get released?

**Comment by nabsthevagabond** [comment]
Any updates on this?

**Comment by ramaganesan-rg** [comment]
Update on Powershell scripts is in work in progress. In the interim, you can use this link as the reference to REST APIs. 
    
https://docs.microsoft.com/en-us/rest/api/consumption/budgets/createorupdate  
Here is the tutorial to create Budget using ARM template deployment - https://docs.microsoft.com/en-us/azure/cost-management-billing/costs/quick-create-budget-template?tabs=CLI- https://docs.microsoft.com/en-us/azure/cost-management-billing/costs/quick-create-budget-template?tabs=CLI

**Comment by frackham** [comment]
I don't understand why this is closed? Original issue is that Az CLI doesn't allow creating of budgets with notifications (fairly standard use case) when using the consumption api, and that's still the case. Don't see this on the feature backlog either.

Not sure directing towards ARM or az resource create is optimal here.

Apologies if I'm missing something - perhaps docs at https://docs.microsoft.com/en-us/cli/azure/consumption/budget?view=azure-cli-latest#az_consumption_budget_create haven't been updated with new parameters?

**Comment by dan-dimitrov** [comment]
Bump - a workaround has been provided but the solution is not resolved.
Rest API allows for this and so does Az PowerShell module.
