### ISSUE TITLE
az keyvault secret list:output is wrong

### ISSUE THREAD

**Issue by abhiramani-iptiq** [Azure/azure-cli#8489]
this command is returning all certificates too stored in keyvault instead of just returning secrets
az keyvault secret list --vault-name &lt;key vault-name&gt; --query [].id --output tsv

this command working fine and only returns certificates
az keyvault certificate list --vault-name &lt;key vault-name&gt; --query [].id --output tsv

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39cfb8ed-c246-2ffb-9dff-070b90c18b21
* Version Independent ID: c09c1597-1b6c-b0a2-b3fc-bdc16764d096
* Content: [az keyvault secret](https://docs.microsoft.com/en-us/cli/azure/keyvault/secret?view=azure-cli-latest#az-keyvault-secret-list)
* Content Source: [src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@jiasli add to S162.

**Comment by bim-msft** [comment]
Hi @abhiramani-iptiq , thanks for the feedback, really nice catch! Actually we create a secret and a key for each certificate to store its public key by design. Anyway, in order to make it consistent with Azure Portal (which doesn't display those auto-generated keys/secrets), I will filter them out.
