### ISSUE TITLE
[Test] Errors appearing in successful test output

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#849]
After recent merges, red error message text has started re-appearing in test outputs. The general policy is that any red text that appears during a test run should be considered a test failure, so I will need to look at why this is happening. (The tests are successful but the red text makes it confusing as to whether a test should pass/fail for someone not familiar with them).

**Comment by tjprescott** [comment]
@derekbekoe it looks like this is related to PR #828.

**Comment by derekbekoe** [comment]
I'll take a look.
