### ISSUE TITLE
[Scale set] There should be an easy way to get the public IP address for a scale set

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#850]
The Public IP address for a scale set lives on its load balancer.  However, there doesn't appear to be a way to get the load balancer using only the scale set data.  Investigate if it can be done, probably by contacting the service teams.

**Comment by mayurid** [comment]
@jasonrshaver: could you follow up as well.

**Comment by yugangw-msft** [comment]
Not command issue

**Comment by yugangw-msft** [comment]
It has been a long enough time w/o any actions taken.
I have chatted with CRP team, and exposed the command `list_instance_connection_info` to get users' lives easier.
