### ISSUE TITLE
Azure App Service - Get Publishing credentials

### ISSUE THREAD

**Issue by vincentdass** [Azure/azure-cli#8505]
**Describe the bug**
Azure CLI doesnt have equivalent command for fetching publishing credentials of Azure App Service.
https://docs.microsoft.com/en-us/rest/api/appservice/webapps/listpublishingcredentials

We couldnt rely on [List Publishing profile](https://docs.microsoft.com/en-us/cli/azure/webapp/deployment?view=azure-cli-latest#az-webapp-deployment-list-publishing-profiles) as it may contain URL other than Kudu.

I am happy to contribute if equivalent command doesnt exist. :)

**Comment by yugangw-msft** [comment]
//CC: @panchagnula 
@vincentdass, contribution is very welcome!

**Comment by vincentdass** [comment]
@yugangw-msft , @panchagnula , planned to add command like this:
`az webapp deployment list-publishing-credentials`
is this fine?

**Comment by panchagnula** [comment]
Closing since this is merged
