### ISSUE TITLE
cannot set key's value ending by ')'

### ISSUE THREAD

**Issue by Sang-ShinLEE** [Azure/azure-cli#8506]
When setting appsetting ith keyvault's secret, through identity manager, the closing bracket is not registered
i.e.
az webapp config appsettings set  --slot &lt;slot's name&gt; -n &lt;webapp's name&gt; -o tsv --settings Blabla="@Microsoft.KeyVault(SecretUri=&lt;keyvault url&gt;/secrets/&lt;secret's name&gt;/&lt;secret's version&gt;)"
=&gt; appsetting Blabla has value "@Microsoft.KeyVault(SecretUri=&lt;keyvault url&gt;/secrets/&lt;secret's name&gt;/&lt;secret's version&gt;"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30f2ae52-2c7f-7e7e-8a62-f1b614f281d3
* Version Independent ID: 9f23ff17-14e0-7800-0094-fb50a5fa91d6
* Content: [az webapp config appsettings](https://docs.microsoft.com/en-us/cli/azure/webapp/config/appsettings?view=azure-cli-latest#az-webapp-config-appsettings-set)
* Content Source: [latest/docs-ref-autogen/webapp/config/appsettings.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config/appsettings.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
Suggest use the latest CLI, put in a json file with content
```json
{"Blabla": "@Microsoft.KeyVault(SecretUri=<keyvault url>/secrets/<secret's name>/<secret's version>)"}
```
 and let the setting command load from the file using `@mysetting.json`

We made this change to help prevent the shell from interpreting the special characters in the setting value

If you don't like the json file, make sure you wrap the quote around <name>=<value> not just around <value>, and use `--debug` to inspect the payload to make sure you get the value right

**Comment by Sang-ShinLEE** [comment]
I've installed the lastest version (2.0.58)
This is not working:
 - neither by using --settings "mysettings=myvalue"
 - neither when using 'az webapp config appsettings set -g MyResourceGroup -n MyUniqueApp --settings mySetting=value @moreSettings.json'
I have an error:
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-2txkquks\azure-cli-core\azure\cli\core\util.py", line
218, in shell_safe_json_parse
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by danielbecroft** [comment]
@yugangw-msft Apologies for commenting on a closed issue, but I can't get any combination of quotes to work around the value. Both of the following strip the trailing ')' character:

```
--setttings "Database=@Microsoft.KeyVault(SecretUri=FOO)"
--settings Database="@Microsoft.KeyVault(SecretUri=FOO)"
```

Is that correct for the quote marks, or was there a different method you were referring to?

I've tried using the external JSON file, but the use of the '@' character to identify the file doesn't seem to play nicely with running the commands through a powershell script (the "@" character isn't fed through to the az command).

Weirdly, if I put a space after the value, the closing parenthesis is retained, but I don't know if that causes other issues.

Using az-cli v2.0.63.

**Comment by Sang-ShinLEE** [comment]
I’ve solved this issue with the only workaround that as worked for me: using json file with powershell.
Other ways are not working:

  *   CMD + json file
  *   POWERSHELL + --settings
  *   CMD + --settings

Not tried yet space after valule.

**Comment by danielbecroft** [comment]
@Sang-ShinLEE  I managed to get it working - I had to double-quote the value:

`--settings "Database=""@Microsoft.KeyVault(SecretUri=FOO)"""`

That fixed the problem.

**Comment by Sang-ShinLEE** [comment]
Thanks to letting me know that workaround… which is quite non-intuitive

**Comment by guilhermesurek** [comment]
It's possible to use sigle-quote with double-quote, like this: 'sidFKedhs")"ahwey'
It worked for me.

**Comment by trailmax** [comment]
April 2021, still hit the same issue. I wish this was better documented.

**Comment by Edgaras91** [comment]
Mid-2023, still hit by the issue 🥳

**Comment by joetossell** [comment]
In case anyone else has a similar issue, running in powershell

This fails:

```
az rest --debug --method get --url "https://graph.microsoft.com/v1.0/tenantRelationships/findTenantInformationByTenantId(tenantId='00000000-0000-0000-0000-000000000000')"
```

Looking at the debug output it's stripping the closing parenthesis )

This works:

```
az rest --debug --method get --url """https://graph.microsoft.com/v1.0/tenantRelationships/findTenantInformationByTenantId(tenantId='00000000-0000-0000-0000-000000000000')"""
```

**Comment by jiasli** [comment]
See https://github.com/Azure/azure-cli/issues/15529
