### ISSUE TITLE
Release pipeline PyPI phase is not having secrets correctly injected

### ISSUE THREAD

**Issue by marstr** [Azure/azure-cli#8507]
The release pipeline:
https://dev.azure.com/azure-public/azcli/_release?definitionId=2

When referencing secrets, we are getting empty values. There are two ways that we can fix it:
1. Continue digging to see why Key Vault values aren't getting injected into our script.
1. Mimic what was done with the Debian release phase, and use the "Azure CLI" task. This will allow us to use our own product to fetch the secrets.

**Comment by tjprescott** [comment]
I would vote for #2.  Seems like the simplest approach.

**Comment by marstr** [comment]
Agreed, that was my plan. Other one is too hard to estimate.

**Comment by marstr** [comment]
This is now complete. After authenticating, you can see the "Azure CLI" task here:
https://dev.azure.com/azure-public/azcli/_releaseDefinition?definitionId=2&_a=definition-tasks&environmentId=5
