### ISSUE TITLE
[Generic Update] Filter doesn't work in some cases

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#851]
az vmss update -n myvmss9 -g myvmsss --set virtualMachineProfile.extensionProfile.extensions[name=VMAccessForLinux].protectedSettings={}

Expected: commands succeeds

Actual: Error: item with value 'VMAccessForLinux' doesn't exist for key 'name' on extensions

**Update**: Additionally, when using generic update to create a tag, the tag key gets converted from camelCase to snake_case. This is not intended.

**Comment by tjprescott** [comment]
Essentially a dupe of #824 but more examples are helpful.
