### ISSUE TITLE
Additional clarification for "--disk-encryption-keyvault"

### ISSUE THREAD

**Issue by cocallaw** [Azure/azure-cli#8518]
Description for "--disk-encryption-keyvault" should be updated to include the following clarification 
"If the key vault is not located in the same resource group as the Virtual Machine, specify the full key vault resource ID"
If the user does not specify the resource ID for the key vault located outside of the resource group of the virtual machine, the CLI will build the resource ID based on the value of --resource-group -g. This will cause the enabling of ADE to fail as the extension will not be able to resolve to the key vault. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4762f857-8a1e-f1bb-7843-3d8fefe28f8e
* Version Independent ID: 91ce956c-c915-5053-56b0-a489fb2f7b00
* Content: [az vm encryption](https://docs.microsoft.com/en-us/cli/azure/vm/encryption?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Technically, the keyvault must be in the same resource group and subscription as the VM or the ID must be specified.

This is a standard pattern in Azure CLI, so it should not be specifically called out. However, the wording does need to be updated to say that it is the "Name or ID of the keyvault…"
