### ISSUE TITLE
"az network nic create" ignores --subscription and always uses default subscription

### ISSUE THREAD

**Issue by jerickmsft** [Azure/azure-cli#8525]
**Describe the bug**
"az network nic create" ignores --subscription and always uses default subscription

**To Reproduce**
Try to create a NIC in a subscription that is not the default.

**Expected behavior**
A NIC can be created

**Environment summary**
azure-cli (2.0.57) on Windows

**Additional context**

![image](https://user-images.githubusercontent.com/13840214/52801552-f9dcb580-3032-11e9-8cfd-3836156d03e9.png)

**Comment by tjprescott** [comment]
@jerickmsft thanks for the report. This issue has already been fixed this sprint and will be in the next release.
