### ISSUE TITLE
Improve Homebrew Release Pipeline Job

### ISSUE THREAD

**Issue by marstr** [Azure/azure-cli#8526]
There are a couple of problems with the [Homebrew Release Pipeline job](https://dev.azure.com/azure-public/azcli/_releaseDefinition?definitionId=2&_a=definition-tasks&environmentId=6):

- [x]  Like with #8507, it needs to be an "Azure CLI" job instead of a "bash" job so that we don't have to tinker with getting DevOps to inject secrets.
- [x] Today, it uses my account with a PAT instead of a GitHub enabled service account. I think it @AutorestCI or @azuresdkciprbot would probably do the trick.

**Comment by marstr** [comment]
@lmazuel, do you approve of using @AutorestCI for this?

**Comment by lmazuel** [comment]
@marstr , I would suggest you create a new service account and new Github account for that specifically. I'm afraid of Github ratio limit

**Comment by marstr** [comment]
Finished this a few weeks ago, never cleaned up here. The @azclibot account was created, and is currently being used to submit Homebrew/homebrew-core PRs.
