### ISSUE TITLE
Understand popularity of various release channels of Azure CLI

### ISSUE THREAD

**Issue by achandmsft** [Azure/azure-cli#8528]
**Is your feature request related to a problem? Please describe.**
We need to understand popularity of various release channels of Azure CLI to understand what to support/invest in. 

**Describe the solution you'd like**
A simple way to measure popularity of various Azure CLI release channels by platform 

([Related docs page](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest))

**Comment by achandmsft** [comment]
@marstr

**Comment by marstr** [comment]
Adding context here:

Known set of release channels that we'd like to track (with some open questions that would be helpful to get answered):

- Windows MSI
- MacOSX from [Homebrew](https://github.com/Homebrew/homebrew-core/tree/master/Formula/azure-cli.rb)
- Linux [packages](https://packages.microsoft.com/)
  - Debian based distributions (install from `.deb` files)
    - Today we publish packages for some Debian releases that are no longer supported, like [`wheezy`](https://www.debian.org/News/2018/20180601). Are there many people using these older releases, do they ever feel the need to upgrade their CLI?
  - Red Hat based distributions (install from `.rpm` files)
    - Issues like #7523 point out a real focus on only Enterprise Linux in this band of distributions. Is there a business incentive to support SUSE based distributions, or should we be leaving it to community members, the way we endorse but do not participate in releasing to [Chocolatey](https://chocolatey.org/packages/azure-cli).
- `pip` direct installs
  - Installing directly from pip doesn't have as strong of a dependency management story as our other install mechanisms, and we've spent a lot of time dealing with the fallout from this. Are people taking advantage of it? Should we stop providing the roll-up package all together, or should we double down and create install instructions for Pip [here](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest)?
- Install from catch-all [install script](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest)

**Comment by marstr** [comment]
There are a couple of questions above about how much support different Linux distributions should get. I think getting these questions sorted out and answered before January 2020 is crucial, as there will likely be a lot of maintenance work associated with repackaging to accommodate the deprecation of Python2.

**Comment by yonzhan** [comment]
add to S164.

**Comment by fengzhou-msft** [comment]
Added installer information in telemetry and set up a [BI report](https://msit.powerbi.com/groups/8de24d49-e97c-4672-9bfc-45fee0ec58f7/reports/8303e614-be5c-4845-b26e-0b7449a44e55/ReportSectionac0d9a85162513c98d50) based on it.
