### ISSUE TITLE
az identity create returns for created in AD

### ISSUE THREAD

**Issue by timja** [Azure/azure-cli#8530]
**Describe the bug**
`az identity create` returns before the identity has been fully created, if you try do a role assignment straight after it will fail with:
```
No matches in graph database for '138d8747-9262-4a78-8842-4ae3e1682bbc'
```

I'm currently working around it with a `sleep 10`, tried 3 and 5 before but not long enough

**To Reproduce**
az group create  -n rg -l uksouth

export IDENTITY_CLIENT_ID=$(az identity create -g ${NODE_RESOURCE_GROUP} -n ${BASE_NAME} --query clientId -o tsv)

export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
az role assignment create --role Reader --assignee ${IDENTITY_CLIENT_ID} --scope /subscriptions/${SUBSCRIPTION_ID}/resourcegroups/rg

**Expected behavior**
Some sort of check should be done to make sure it is fully created before exiting the command

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

brew
mac
```
$ az --version
azure-cli (2.0.54)
```

**Additional context**

**Comment by yugangw-msft** [comment]
Let me reach to the service team to clarify

**Comment by kevinwedwards** [comment]
I'm seeing this issue as well

**Comment by Owemeone** [comment]
Just to add my +1. Seeing the same issue in my deployment script. Creating an identity and adding a role to it. For the time being added a sleep 30, just to be sure, but would be nice if we could:
1) have the command only return when actually done propagating to AAD
or 2) have a way to actively poll or check on the propagation

**Comment by frosenberg** [comment]
I am seeing the same issue on our end - version 2.14.0

**Comment by navba-MSFT** [comment]
@timja Apologies for the late reply. I did some research on this and I am sharing my findings here.

>If you create a new service principal and immediately try to assign a role to that service principal, that role assignment can fail in some cases. For example, if you create a new managed identity and then try to assign a role to that service principal, the role assignment might fail. The reason for this failure is likely a replication delay. The service principal is created in one region; however, the role assignment might occur in a different region that hasn't replicated the service principal yet.

>To address this scenario, use the [Role Assignments - Create](https://docs.microsoft.com/en-us/rest/api/authorization/roleassignments/create) REST API and set the principalType property to ServicePrincipal. You must also set the apiVersion to 2018-09-01-preview or later.

More Information on this is [here](https://docs.microsoft.com/en-us/azure/role-based-access-control/role-assignments-rest#new-service-principal). This issue has been open for quite sometime. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by timja** [comment]
The feature request is for the CLI to handle this transparently to the user like terraform does if I remember correctly.

**Comment by navba-MSFT** [comment]
@timja Thanks for getting back. We are looking into this issue and we will update this thread once we have more details.

@adamedx Could you please let us know if you have any update on this ?

**Comment by adamedx** [comment]
I'm not the right contact for anything related to azure-cli -- @dcaro , can you re-route?

**Comment by zhoxing-ms** [comment]
@timja I can't reproduce this issue at present. Could you please update the latest version of CLI to have a try?

**Comment by timja** [comment]
Is anyone else still seeing this?

(I raised it 3 years ago and have since switched to terraform...)

**Comment by navba-MSFT** [comment]
@timja Thanks for getting back. We shall keep this thread open for sometime if any of the users are facing the same issue. They can also reopen this thread too, just in case it gets archived.

**Comment by Jtango18** [comment]
I can confirm that I am still seeing this issue in az version 2.34.1

`az identity create` returns success immediately which breaks role assignment further down the script because the identity/SP has not been populated yet. 

Exactly as originally posted by @timja

**Comment by zhoxing-ms** [comment]
@Jtango18 At present, we have determined that this problem is caused by propagation delay of managed identity on the server side, and we are discussing the solution with the service team through email

**Comment by enrique-palazuelos** [comment]
Same behaviour observed. Could be possible to add the "wait" command to az identity?

Thanks!

**Comment by timja** [comment]
@navba-MSFT could you please re-open

**Comment by mgd722** [comment]
This definitely still exists in CLI 2.65.0, but the message I get is: `ERROR: Cannot find user or service principal in graph database for '<UUID>'.`
