### ISSUE TITLE
Automate Install Script Upload

### ISSUE THREAD

**Issue by marstr** [Azure/azure-cli#8531]
The catch-all install script ([documented here](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest)) is not part our release process. Uploading the most recent copy to azurecliprod should be added to the release pipeline.

**Comment by tjprescott** [comment]
The curl script?

**Comment by marstr** [comment]
Correct :) I don't think updating it was documented in the old instructions either. Fortunately, it just don't change all that much either.

**Comment by yonzhan** [comment]
add to S164.

**Comment by fengzhou-msft** [comment]
Added task in ADO.
