### ISSUE TITLE
Wrong example command in document

### ISSUE THREAD

**Issue by mrnonz** [Azure/azure-cli#8541]
Hi, I read example command here https://docs.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest#examples

and I found wrong command on "Create a container in a container group that runs Windows, with 2 cores and 3.5Gb of memory." Section.

Here your command
`az container create -g MyResourceGroup --name myapp --image myimage:latest --ip-address public --ports 8081 --protocol UDP`

I think it's should have `--os-type` option in command like this

`az container create -g MyResourceGroup --name myapp --image myimage:latest --os-type Windows --ip-address public --ports 8081 --protocol UDP`

thank you

**Comment by mrnonz** [comment]
I open issue wrong repo.

sorry

**Comment by VamsiSangam** [comment]
This has been fixed.

**Comment by shubham1172** [comment]
@tjprescott should we close this?

**Comment by SaurabhSharma-MSFT** [comment]
@tjprescott I believe this issue has been fixed and can be closed. Please let us know.

**Comment by mrnonz** [comment]
@SaurabhSharma-MSFT I think so, Thank you
