### ISSUE TITLE
Input Parameter secureString

### ISSUE THREAD

**Issue by Klaas-** [Azure/azure-cli#8542]
**Describe the bug**
An input parameter using type "secureString" is accepted but input is shown on console.

**To Reproduce**
```
cat test.json
{
    "$schema":  "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion":  "1.0.0.0",
    "parameters":  {
                       "domainJoinPassword":  {
                                                  "type":  "secureString"
                                              }
                },
    "resources":  [
                  ],
    "outputs":  {
                }
}
```

```
az group deployment create --subscription 'subs' --resource-group 'ReG' --template-file test.json
Please provide secureString value for 'domainJoinPassword' (? for help): asdsecret
```

**Expected behavior**
```
az group deployment create --subscription 'subs' --resource-group 'ReG' --template-file test.json
Please provide secureString value for 'domainJoinPassword' (? for help): [no input visible]
```

**Environment summary**
RHEL7 current Azure Image with azure-cli via yum
azure-cli-2.0.58-1.el7.x86_64

**Additional context**
I think it should either not accept secureString because it is not valid as per docs or make the check in https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/custom.py#L159 case insensitive

**Comment by Klaas-** [comment]
this is not really a question @tjprescott  :) its either don't accept the type or make the check case insensitive. If the latter is decided I'd be willing to create a PR for that.

**Comment by tjprescott** [comment]
We label every initial issue Question, @Klaas-. :) It's a question for us because we need to look into it further.

**Comment by tjprescott** [comment]
Thanks @Klaas- I've identified the problem. The fix will be in the next release.
