### ISSUE TITLE
az network vnet-gateway list-* missing table output

### ISSUE THREAD

**Issue by alexjmoore** [Azure/azure-cli#8543]
**Describe the bug**
When using the 'table' output type the following commands show no output:

az network vnet-gateway list-learned-routes
az network vnet-gateway list-advertised-routes
az network vnet-gateway list-bgp-peer-status 

**To Reproduce**
Execute the above commands with '--output table' or 'table' as the default output type.  The command will complete successfully, but no output is shown.

**Expected behavior**
I would would expect a sensible default tabular view of the returned data.

**Environment summary**
Installed via apt-get on Ubuntu on WSL on Windows 10 Pro 1809 17763.316
azure-cli 2.0.58
network 2.3.2

**Additional context**
N/A

**Comment by tjprescott** [comment]
Hi @alexjmoore should be able to address this in this sprint. Do you have any recommendation as to what columns you would like to see here?

**Comment by alexjmoore** [comment]
For az network vnet-gateway list-learned-routes I suggest:

network | nextHop | origin | sourcePeer | asPath | weight

For az network vnet-gateway list-advertised-routes I suggest:

network | nextHop | origin | sourcePeer | asPath | weight

For az network vnet-gateway list-bgp-peer-status I suggest:

neighbor | asn | state | connectedDuration | routesReceived | messagesSent | messagesReceived

**Comment by tjprescott** [comment]
Thanks @alexjmoore!

**Comment by alexjmoore** [comment]
Hi @tjprescott ,

The others are all good, but just noticed on 2.0.60 that `az network vnet-gateway list-advertised-routes` actually still doesn't provide output, although it has moved from no output, to providing an error message:

`Table output unavailable. Use the --query option to specify an appropriate query. Use --debug for more info.`

**Comment by tjprescott** [comment]
Thanks @alexjmoore  I'll take a look.

**Comment by tjprescott** [comment]
@alexjmoore can you show the output of the command with `-o json`?

**Comment by alexjmoore** [comment]
Example:

`{
  "value": [
    {
      "asn": 65010, 
      "connectedDuration": "7.15:21:30.6779198",
      "localAddress": "10.2.0.30",
      "messagesReceived": 10278,
      "messagesSent": 12583,
      "neighbor": "10.4.0.1",
      "routesReceived": 25,
      "state": "Connected"
    },
    {
      "asn": 65020,
      "connectedDuration": "7.15:21:30.6466710",
      "localAddress": "10.2.0.30",
      "messagesReceived": 9909,
      "messagesSent": 12787,
      "neighbor": "10.0.0.1",
      "routesReceived": 7,
      "state": "Connected"
    } 
  ]
}`
