### ISSUE TITLE
Give example of .json file format

### ISSUE THREAD

**Issue by Sang-ShinLEE** [Azure/azure-cli#8547]
Can you give some details on format of .json file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30f2ae52-2c7f-7e7e-8a62-f1b614f281d3
* Version Independent ID: 9f23ff17-14e0-7800-0094-fb50a5fa91d6
* Content: [az webapp config appsettings](https://docs.microsoft.com/en-us/cli/azure/webapp/config/appsettings?view=azure-cli-latest#az-webapp-config-appsettings-set)
* Content Source: [latest/docs-ref-autogen/webapp/config/appsettings.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config/appsettings.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
I think the existing examples are enough to demonstrate that the json content should be
```json
   {
      "settingName": "settingValue",
      "settingName2": "settingValue2"
   }
```

**Comment by petrformanek** [comment]
Hello @yugangw-msft,
which examples demonstrate it? I cannot see any at this page.
It is somehow possible to get the result of the **list** command in this format?
To be able easily import and export settings among apps.
