### ISSUE TITLE
az create functionapp uses the wrong image for Linux app service function app

### ISSUE THREAD

**Issue by balag0** [Azure/azure-cli#8553]
**Describe the bug**
"az functionapp create" uses the wrong image for Linux App Service Function apps.
https://github.com/Azure/azure-cli/blob/f1c301b07dc349bbbda30ae83df0809345a88f9e/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py#L1985

It should instead use one of the following images (based on the runtime)
microsoft/azure-functions-dotnet-core2.0:2.0
microsoft/azure-functions-node8:2.0
microsoft/azure-functions-python3.6:2.0

**To Reproduce**
az functionapp create --resource-group <RG> --os-type Linux --plan <PLAN> --runtime python --name <APPNAME> --storage-account <SA>

**Expected behavior**
This creates a linux appservice python function app, but the image used is not microsoft/azure-functions-python3.6:2.0.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by ahmedelnably** [comment]
@tjprescott Feel free to assign all Functions issues to me, and with functions-cli/functions tag(s) so it can be properly tagged and resolved

**Comment by ankitkumarr** [comment]
@balag0 or @ahmelsayed do you know if the linuxFxVersion needs to have the version tag as well? `DOCKER|microsoft/azure-functions-node8:2.0` or `DOCKER|microsoft/azure-functions-node8`?

**Comment by ahmelsayed** [comment]
yes, it should have the tag of `2.0`. Also please use the `mcr.microsoft.com/azure-functions/...` version instead of the dockerhub version.
