### ISSUE TITLE
[Functions] More intelligence around default node versions

### ISSUE THREAD

**Issue by ColbyTresness** [Azure/azure-cli#8555]
We should detect which version of node a user is running locally, check that it's supported by Functions, and then set to whichever version makes the most sense. This is an improvement over what we currently do, which is default the user into a hard coded value, 8.11.x.

**Comment by ahmedelnably** [comment]
This will be tracked within the larger effort to configure the language/version of a function app
Replaced by: https://github.com/Azure/azure-cli/issues/8797
