### ISSUE TITLE
Microsoft CLI 2.0 for Azure? 

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-cli#8559]
When we install the Azure CLI via MSI, the product is called "Microsoft CLI 2.0 for Azure". The product name should be updated.
![cli](https://user-images.githubusercontent.com/3135708/52911615-70351e00-32a6-11e9-8282-770a7fae3bec.jpg)

**Comment by tjprescott** [comment]
I tend to agree. @yugangw-msft do you?

**Comment by tjprescott** [comment]
I would advocate "Microsoft Azure CLI 2.0"

**Comment by alexandair** [comment]
@tjprescott As of the end of June 2018, explicit version numbers have been removed from Azure CLI product names. More details at https://docs.microsoft.com/en-us/cli/azure/cli-versioning-identifiers?view=azure-cli-latest

Name can be "Microsoft Azure CLI".
