### ISSUE TITLE
MSI installer on windows does not create executable for Git bash

### ISSUE THREAD

**Issue by marcofranssen** [Azure/azure-cli#8560]
The following path only contains az.cmd

`C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin`

It would make sense to also install a file called `az` in there which will work with Git bash.

```
#!/usr/bin/env bash
../python -IBm azure.cli $*
```

**Comment by tjprescott** [comment]
We will examine the feasibility. As a general aside, people have reported issues using the CLI with Git bash so we do not recommend it, but if it is working for you, then 👍

**Comment by marstr** [comment]
This would be a pretty easy thing to knock out, and I know there is a pretty real set of people who use Git Bash as their primary CLI environment in Windows. I'm pretty swamped before //build, but it would be awesome if we could get it in.

**Comment by marstr** [comment]
For any future person working on this, you'd be adding a new bash script named `az` here:
[${REPO_ROOT}/build_scripts/windows/scripts](https://github.com/Azure/azure-cli/tree/237f3a8878156212b4e1f0675c0c0319c8bb78cf/build_scripts/windows/scripts)

**Comment by atbagga** [comment]
Isn't it the same script - https://github.com/Azure/azure-cli/pull/5776/files which needs to be added?

**Comment by yonzhan** [comment]
add to S164.
