### ISSUE TITLE
How long [az vm deallocate] will wait for the VM operation?

### ISSUE THREAD

**Issue by KeiroKamioka0000** [Azure/azure-cli#8563]
Is there are maximum wait duration for [az vm deallocate] commands to be get run?

Does it will wait for over 30 minuets before commands run?
Without [--no-wait] option, does it will wait until the long-running operation finish?

https://docs.microsoft.com/ja-jp/cli/azure/vm?view=azure-cli-latest#az-vm-deallocate
--no-wait
Do not wait for the long-running operation to finish.

**Comment by tjprescott** [comment]
There is not a maximum time limit imposed by the CLI on polling. The service may support timing out. If you do not supply `--no-wait` then the CLI will continue to poll until the long running operation completes. You can often break out of the polling with Ctrl+C.

**Comment by KeiroKamioka0000** [comment]
@tjprescott 
Thanks for the response.
Just double checking.... 
If [--no-wait] was supplied, deallocating will start without waiting for VM's OS-side shutdown procedure.
Is my understanding is correct?

If so, please close it please.
Thanks for the answer.

**Comment by tjprescott** [comment]
That should be the case, yes.
