### ISSUE TITLE
How to use Azure cli to create autoscale for an app service plan?

### ISSUE THREAD

**Issue by David-Stark** [Azure/azure-cli#8564]
Hi!

This is my first issue i create on Github, hope i don´t missed anything or this issue is in the wrong place. 

I’m trying to create a rule for auto-scaling for an app service plan with Azure CLI. But i can´t find any documentation how to do this? Or is it even supporten? 

For example what i want is a rule that scales out my app service plan with 2 instances when we have more than 200 requests. 

This is the commands i have created:
```
az monitor autoscale create --resource-group MyResourceGroup \ 
--resource MyResource \
--resource-type Microsoft.Web/serverFarms \
--name MyAutoScale \
--min-count 2 \
--max-count 10 \
--count 2
```

```
az monitor autoscale rule create  --resource-group MyResourceGroup  \
--autoscale-name MyAutoScale \
--condition "Requests > 200 avg 5m" \
--scale out 2
```
When i run this i get following message:
```
Exception of type 'Microsoft.WindowsAzure.Management.Monitoring.MonitoringServiceException' was thrown.. [Code: "UnsupportedMetric"]
```

**Comment by David-Stark** [comment]
I found the answer after some digging. I did not truly understand how to create rules. If someone else in the future have the same question i leave an example how to solve this. For this example, basically you create a rule based on how many request the web app gets and scales out its related service plan.

```
az monitor autoscale rule create  --resource-group MyResourceGroup   `
--resource MyWebSite  `
--resource-type 'Microsoft.Web/sites' `
--autoscale-name MyAutoScale    `
--condition "Requests >= 200 avg 5m"   `
--scale out 2
```

**Comment by kramfs** [comment]
I was having the same issue, I documented the steps I did to overcome this. Hopefully, somebody will find it useful  -https://stackoverflow.com/a/66326925/1400202
