### ISSUE TITLE
"az webapp" is not working

### ISSUE THREAD

**Issue by marcofranssen** [Azure/azure-cli#8565]
the command `az webapp` seems to be broken. I'm unable to list any of my web apps for my account.

`az account list` works fine
`az resource list` works fine
`az webapp list` returns nothing

```
az webapp config ssl upload \
  --name "$AZ_APP_NAME" \
  --resource-group "$AZ_RS_GROUP" \
  --certificate-file "$CERT" \
  --certificate-password "$PFX_PASS" \
  --query thumbprint \
  --output tsv
```

gives error on resource group not found, which I copy pasted from the portal.

That makes me conclude there could be something wrong with the `az webapp` commands or something on the API side.

**Comment by yugangw-msft** [comment]
@marcofranssen, are you in the same subscription like portal? Also using `--debug` always helps disclose the url involved to retrieve the webapps, please use that and cross check

**Comment by marcofranssen** [comment]
Yeah finally I figured out I have to manually switch subscriptions. 🤦‍♂️

**Comment by waigitdas** [comment]
I had the same problem with Putty. But when I used Anaconda, I could them list the webapp. Anaconda is a free download.
