### ISSUE TITLE
az login authentication failed

### ISSUE THREAD

**Issue by yueguoguo** [Azure/azure-cli#8566]
**Describe the bug**
I tried `az login` but received the following message 
```
Failed to authenticate '{'additional_properties': {}, 'id': '/tenants/xxxxxxxxxxxxxxxx', 'tenant_id': 'xxxxxxxxxxxxxxxxxxx'}' due to error 'Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS50057: User account is disabled.\r\nTrace ID: xxxxxxxxxxxxxxxxx\r\nCorrelation ID: xxxxxxxxxxxxxxxxxxxx\r\nTimestamp: 2019-02-19 07:58:56Z","error_codes":[50057],"timestamp":"2019-02-19 07:58:56Z","trace_id":"xxxxxxxxxxxxxxxxxxxxx","correlation_id":"xxxxxxxxxxxxxxxxxxxx"}'
```
but when I do `az account list -o table` I see my account is listed there with `Enabled` in the column of `State`. 

**To Reproduce**
N/A

**Expected behavior**
A successful authentication in `az login`.

**Environment summary**
Azure Data Science Virtual Machine (Linux) command line console.

**Additional context**
The subscription is from my customer, and I have been added with **Reader** role to a resource group under that subscription.

**Comment by yueguoguo** [comment]
It works if I specify the tenant id, i.e., `az login --tenant <tenant_id>`. Is it a mandate to do so?

**Comment by marstr** [comment]
Howdy @yueguoguo, it is not supposed to be mandatory that you provide a tenant ID to login. When you don't provide a Tenant, we authenticate against the "common" tenant, and using the Azure CLI's application ID, I don't believe you should be getting back a "User account is disabled" error.

Have thoughts on this, @yugangw-msft?

**Comment by yugangw-msft** [comment]
@yueguoguo, did your log in command succeed overall? I suspect this is just a warning that your account is disabled in a particular tenant, while fine in others.

**Comment by yugangw-msft** [comment]
I am pretty sure this is a warning, so i am closing this. Feel free to reactivate if you see this is failure, and please provide a trace using "--debug" flag
