### ISSUE TITLE
Subnet resource is not found

### ISSUE THREAD

**Issue by ahmetwaly** [Azure/azure-cli#8569]
**Describe the bug**
After creating Vnet with subnet and it was provisioned successfully .Tried to provision NIC using same subnet and vnet resource gives the below error: 

Resource /subscriptions/5f852b13-2cb1-4335-a646-2d4a5b95db30/resourceGroups/psdemo-rg/providers/Microsoft.Network/virtualNetworks/psdemo-vent-1/subnets/psdemo-subnet-1 referenced by resource /subscriptions/5f852b13-2cb1-4335-a646-2d4a5b95db30/resourceGroups/psdemo-rg/providers/Microsoft.Network/networkInterfaces/psdemo-linux-1-nic-1 was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.

**To Reproduce**
1- create resource group 
az network vnet create --name=psdemo-vnet-1 --resource-group psdemo-rg --address-prefix 10.1.0.0/16 --subnet-name psdemo-subnet-1 --subnet-prefix 10.1.1.0/24

2- create a vnet and subnet 
**az network vnet create --name=psdemo-vnet-1 --resource-group psdemo-rg --address-prefix 10.1.0.0/16 --subnet-name psdemo-subnet-1 --subnet-prefix 10.1.1.0/24**

3- create a public ip resource
az network public-ip create --resource-group psdemo-rg --name psdemo-linux-1-pip-1

4-create a nsg 
az network nsg create --resource-group psdemo-rg --name psdemorg-linux-nsg-1
5- create NIC resource 
az network nic create --resource-group=psdemo-rg --name=psdemo-linux-1-nic-1 --vnet-name psdemo-vent-1 --subnet psdemo-subnet-1 --network-security-group psdemo-linux-nsg-1 --public-ip-address=psdemo-linux-1-pip-1

**Expected behavior**
NIC resource would be created properly .

**Environment summary**
Mac Os Sierra 
azure-cli                         2.0.58

acr                                2.2.0
acs                               2.3.17
advisor                            2.0.0
ams                                0.4.1
appservice                        0.2.13
backup                             1.2.1
batch                              3.4.1
batchai                            0.4.7
billing                            0.2.0
botservice                         0.1.6
cdn                                0.2.0
cloud                              2.1.0
cognitiveservices                  0.2.4
command-modules-nspkg               2.0.2
configure                         2.0.20
consumption                        0.4.2
container                         0.3.13
core                              2.0.58
cosmosdb                           0.2.7
dla                                0.2.4
dls                                0.1.8
dms                                0.1.2
eventgrid                          0.2.1
eventhubs                          0.3.3
extension                          0.2.3
feedback                           2.1.4
find                              0.2.13
hdinsight                          0.3.0
interactive                        0.4.1
iot                                0.3.6
iotcentral                         0.1.6
keyvault                          2.2.11
kusto                              0.1.0
lab                                0.1.5
maps                               0.3.3
monitor                           0.2.10
network                            2.3.2
nspkg                              3.0.3
policyinsights                     0.1.1
profile                            2.1.3
rdbms                              0.3.7
redis                              0.4.0
relay                              0.1.3
reservations                       0.4.1
resource                          2.1.10
role                               2.4.0
search                             0.1.1
security                           0.1.0
servicebus                         0.3.3
servicefabric                     0.1.12
signalr                            1.0.0
sql                                2.1.9
sqlvm                              0.1.0
storage                            2.3.1
telemetry                          1.0.1
vm                                2.2.15

Python location '/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7'
Extensions directory '/Users/ahmetwaly/.azure/cliextensions'

Python (Darwin) 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) 
[Clang 6.0 (clang-600.0.57)]

**Comment by tjprescott** [comment]
This scenario is tested daily and working. From your repro, it looks like you have a typo in your NIC create:

--vnet-name psdemo-**vent**-1
