### ISSUE TITLE
az bot Project file not found

### ISSUE THREAD

**Issue by MattRuwe** [Azure/azure-cli#8577]
**Describe the bug**
I'm getting the following error:

`project file not found. Please pass a valid --proj-file-path.`

when trying to run this command:

`az bot publish --resource-group MyBot -n MyBot --subscription xxxxx -v v4 --proj-file-path ".\MyBot.csproj" --verbose --code-dir "C:\dev\MyCodeDirectory"`

The project file exists at the specified location.

I'm following the instructions in the readme.md that gets created when working with a new CoreBot AzureBotService template in Visual Studio.  These instructions discuss how to use msbot and I'm using the command in there that ultimately calls az bot and gives the above error.

I'm running in PowerShell on Windows 10 using the latest version of Azure CLI and msbot.

**Comment by tjprescott** [comment]
@stevengum

**Comment by stevengum** [comment]
Hmmm this might be due to some naming changes a little while ago that perhaps fully picked up in the underlying code, instead of the path relative to the code directory for the --proj-file-path, can you try using just `MyBot.csproj`?

**Comment by MattRuwe** [comment]
That did the trick!  Looks like the documentation needs to be updated within the Visual Studio template readme.md.

**Comment by sgellock** [comment]
customer issue has been resolved
