### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by mcurko** [Azure/azure-cli#8581]
az iot hub show-connection-string --hub-name
(not --name)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9afeaa5c-1af2-8fcc-69b4-15ae81a0d342
* Version Independent ID: dea97474-170e-f678-f812-a1e4cdf56c76
* Content: [az iot hub](https://docs.microsoft.com/en-us/cli/azure/iot/hub?view=azure-cli-latest#az-iot-hub-show-connection-string)
* Content Source: [src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/_help.py)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
I don't see anything on this page that references --hub-name.

**Comment by mcurko** [comment]
That's the point, you have an error in the command syntax.

**Comment by tjprescott** [comment]
--name is correct. You likely have an outdated version of the CLI or may be using the IoT extension, which could be different.

**Comment by mcurko** [comment]
I indeed do have the extension, as required by various MS tutorials on IoT, and only now realize what a colision there is between command syntaxes. Very confusing!

**Comment by tjprescott** [comment]
Totally understandable @mcurko.  For you reference, here's the link to the extension documentation:
https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/?view=azure-cli-latest

You might consider opening an issue in the extensions repo so they can address the inconsistency:
https://github.com/Azure/azure-cli-extensions
