### ISSUE TITLE
Az role definition python libary error

### ISSUE THREAD

**Issue by tpetkovic** [Azure/azure-cli#8582]
When creating an custom role on the azure-cli on the portal I receive python libary errors, this has been replicated on other colleagues devices within the team and they receive the exact same issue. I can also send the contents of the JSON file when engaged with a microsoft support engineer. It contains the same layout as the vmoperator.json on your how-to page. https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles-cli

xxxxx@Azure:~$ az role definition create --role-definition /home/xxxx/xxxxxxxxxxx.json
malformed node or string: <_ast.Name object at 0x7fc72cb13588>
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 218, in shell_safe_json_parse
    return json.loads(json_or_dict_string)
  File "/opt/az/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/opt/az/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/az/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 3 (char 193)

**Comment by marstr** [comment]
Howdy @tpetkovic, given that this issue is regarding a JSON parsing problem, we'll definitely need a way of understanding the contents of your role definition. If you're comfortable sharing via email, you can send it to me at marstr@micrsoft.com.

**Comment by tjprescott** [comment]
Sounds like it might be similar to #8456.

**Comment by yonzhan** [comment]
add to S164.

**Comment by arrownj** [comment]
Hi @tpetkovic , is this issue still valid ? It seems that your json file wasn't parsing well , could you please also paste your json content here ? Thanks

**Comment by yungezz** [comment]
hi @tpetkovic is there any update on json file validation? Would like to close the issue for now since no response for a while. Feel free to create a new issue if met any other error. thanks.
