### ISSUE TITLE
acr logout

### ISSUE THREAD

**Issue by strimpak** [Azure/azure-cli#8583]
It would be useful to have an `az acr logout` command available. 

Could you please define what steps should be done in order to terminate session created after az acr login succeeds?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c608162e-cf40-9d53-da4a-51f51a0311ea
* Version Independent ID: eccbb543-be68-7de2-d41d-abee55c81452
* Content: [az acr](https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest#az-acr-login)
* Content Source: [src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by sgarshol** [comment]
It still seems like a weird thing not to include. To be fair, `az acr logout` as envisioned would be a wrapper too.
