### ISSUE TITLE
az acr repository list does not work same with -u -p parameters

### ISSUE THREAD

**Issue by dalehhirt** [Azure/azure-cli#8584]
**Describe the bug**
When I use the -u and -p parameters, it cannot find the repository I need it to list.

**To Reproduce**
For a given repository that I am using a service principal to log into, if I do the following:

az acr repository list -n <name>

it will come back eventually with "Unable to get AAD authorization tokens with message: Registry '<name>.azurecr.io' does not support AAD login.".  It will then prompt for username and password, and then a list will be returned.

If I pass in:

az acr repository list -n <name> -u <username> -p <password>

It will eventually time out because it is actually querying the wrong URL.

HTTPSConnectionPool(host='<name>.azurecr.io', port=443): Max retries exceeded with url: /acr/v1/_catalog?n=100 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x058557D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

**Expected behavior**
It should be querying and getting the correct URL for the repository regardless of what method is used.

**Environment summary**
interactive and script

azure-cli (2.0.52)

acr (2.1.10)
acs (2.3.12)
advisor (2.0.0)
ams (0.3.1)
appservice (0.2.8)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.5)
billing (0.2.0)
botservice (0.1.2)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.4)
command-modules-nspkg (2.0.2)
configure (2.0.19)
consumption (0.4.0)
container (0.3.9)
core (2.0.52)
cosmosdb (0.2.5)
dla (0.2.3)
dls (0.1.6)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.1)
extension (0.2.3)
feedback (2.1.4)
find (0.2.12)
hdinsight (0.1.0)
interactive (0.4.0)
iot (0.3.4)
iotcentral (0.1.4)
keyvault (2.2.8)
lab (0.1.4)
maps (0.3.2)
monitor (0.2.7)
network (2.2.10)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.2)
rdbms (0.3.5)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.1)
resource (2.1.6)
role (2.1.11)
search (0.1.1)
servicebus (0.3.2)
servicefabric (0.1.9)
signalr (1.0.0)
sql (2.1.6)
storage (2.2.6)
telemetry (1.0.0)
vm (2.2.9)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\dalehirt\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

**Additional context**
I am not sure if this is a permissions issue or not.

**Comment by tjprescott** [comment]
@djyou for triage

**Comment by dalehhirt** [comment]
This also happens for az acr repository show-tags.  I think the problem is in the azure-cli/src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_docker_utils.py module.  But that's as far as I have gone without running the debugger directly.

**Comment by djyou** [comment]
@dalehhirt Could you upgrade your CLI version to mitigate this issue?

This is a backward compatibility issue with Classic registry with a special tenant suffix in the login server such as `registry-tenant.azurecr.io`. The following should all work:

If your registry is in the current subscription (e.g., your can switch subscription by `az account set -s <Your Sub>` and you can get the registry using `az acr show -n MyRegistry`), the following should just work:
```
az acr repository list -n MyRegistry -u <username> -p <password>
```

If your registry is not in the current subscription, you can either specify the subscription that has the registry using `--subscription`:
```
az acr repository list -n MyRegistry -u <username> -p <password> --subscription <Your Sub>
```
or specify `--suffix` so the CLI can resolve the correct login server:
```
az acr repository list -n MyRegistry -u <username> -p <password> --suffix tenant
```
where `tenant` is the `tenant` in `registry-tenant.azurecr.io`.

**Comment by dalehhirt** [comment]
Upgrading helped.  It resolved the issue without any further code changes.

**Comment by tjprescott** [comment]
Thanks @djyou! Closing.
