### ISSUE TITLE
Updating via MSI sometimes leaves the old installation which causes problems.

### ISSUE THREAD

**Issue by dumbnose** [Azure/azure-cli#8585]
**Describe the bug**
After upgrading to az cli 2.0.58, attempting to run any functionapp command (e.g. create), I receive an error stating: "cannot import name 'validate_timeout_value'"

**To Reproduce**
Upgrade to 2.0.58 and then run "az functionapp create"

**Expected behavior**
I expect the command to report usage info

**Environment summary**
Install Method MSI, az version 2.0.58, Windows 10, cmd.exe shell

**Additional context**
The version I upgraded from was likely several months old

**Comment by dumbnose** [comment]
I had tried uninstalling / reinstalling a couple of times and that did not help.  So, I did an uninstall and then looked under "C:\Program File (x86)\Microsoft SDKs\Azure" and noticed there was still a CLI2 directory under there with a bunch of content.  I manually deleted that directory and did another install and it is now fixed.  So, this looks like a bug in the installer.

**Comment by tjprescott** [comment]
Thank you for the update @dumbnose.

**Comment by marstr** [comment]
Thanks for the report, @dumbnose. I need some more helping getting to the bottom of this. I checked to make sure that we're marking the old installation for deletion, and found that here: https://github.com/Azure/azure-cli/blob/fe0f256ee877c6f88ff432213115e9a0bf82e97b/build_scripts/windows/Product.wxs#L87-L91

A few lines above though, I did see that we define `AZURECLIFOLDER` relative to the new install location: https://github.com/Azure/azure-cli/blob/fe0f256ee877c6f88ff432213115e9a0bf82e97b/build_scripts/windows/Product.wxs#L66-L77

Could it be that `TARGETDIR` changed between your two installs?

**Comment by marstr** [comment]
I'm going to close this as a fluke. Since we're note hearing wide-spread reports of this problem, and I've ensured that we are marking the folder for deletion, I think we can hold off.

If you continue to experience this problem, or if others report also feeling these effects, I'm happy to open it back up.
