### ISSUE TITLE
advisor: "az advisor recommendation list" command hangs 

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#8597]
Python SDK's paging gets into a dead loop as the nextLink is `""`, while AutoRest runtime only stops at `None`. 
This should be a service end bug, as clearly there are other information in the upcoming pages.

**Comment by mojayara** [comment]
Hi, if that is the case. Can you explain how it was working in the first place.

**Comment by yugangw-msft** [comment]
The real fix would come from https://github.com/Azure/msrest-for-python/issues/147

**Comment by tjprescott** [comment]
@Prasanna-Padmanabhan for comment.

**Comment by Prasanna-Padmanabhan** [comment]
This issue was resolved more than a month ago, please let us know if this is still an issue.
