### ISSUE TITLE
Getting information about vm size in resource group

### ISSUE THREAD

**Issue by ZEROF** [Azure/azure-cli#8598]
Hi,

I try to get information about vm size. For one VM in resource group or all VM's in one resource group. Something like this:

    "hardwareProfile": {
      "vmSize": "Standard_D2s_v3"

Is there command for getting this type of information using Azure AZ.

Thanks

**Comment by yugangw-msft** [comment]
`az vm list --query "[].hardwareProfile.vmSize" -otsv -g myRG`
Let me know if I misunderstood your questions

**Comment by ZEROF** [comment]
Hi,

Thanks a lot. That did the trick.
