### ISSUE TITLE
Provide Edge Build of MSI

### ISSUE THREAD

**Issue by marstr** [Azure/azure-cli#8602]
Related to #8139

To support users looking to test our latest functionality on Windows, we can make our existing CI builds available through a separate install link, like `https://aka.ms/InstallAzureCliWindowsEdge` to go along with our existing `https://aks.ms/InstallAzureCliWindows`.

**Comment by yugangw-msft** [comment]
@marstr, per our conversation yesterday, please fix this in the upcoming sprint.

**Comment by yugangw-msft** [comment]
Also for edge builds, with the bar of good enough, I don't think we need to code sign it.
