### ISSUE TITLE
Provide Edge Build of `.deb` package

### ISSUE THREAD

**Issue by marstr** [Azure/azure-cli#8603]
Related to #8139

To support users looking to test our latest functionality on a Debian based Linux machine, we can make our existing CI builds available through either:
- A separate package repository that is updated at nightly cadence.
- Host the `.deb` packages in a storage account and create a link for how to download the latest one, similar to how we would with the MSI.

**Comment by yugangw-msft** [comment]
@marstr, per our conversation yesterday, can you please fix this in the upcoming sprint?

**Comment by marstr** [comment]
These are being built as part of our ADO setup, we just need to decide which of these deb packages we would like to publish. It seems a bit extraneous to publish all of the .debs that we currently produce :)

**Comment by marstr** [comment]
This never got to the top of my priority list! With the shuffle of our team, I'm not going to get to it before I move on. I'm going to unassign myself, but one last thought on this thread: I think that publishing the latest `.deb` for either xenial or the latest version Ubuntu we support makes some sense. However, we also haven't heard many people asking for this, so it's remained low priority.
