### ISSUE TITLE
Provide Edge Build of `.rpm` package

### ISSUE THREAD

**Issue by marstr** [Azure/azure-cli#8604]
Related to #8139

To support users looking to test our latest functionality on a Red Hat based Linux machine, we can make our existing CI builds available through either:
- A separate package repository that is updated at a nightly cadence.
- Host the `.rpm` packages in a storage account and create a link for how to download the latest one, similar to how we would with the MSI.

**Comment by yugangw-msft** [comment]
@marstr,  per our conversation yesterday, can we fix this in the upcoming sprint?

**Comment by marstr** [comment]
We're now uploading the MSI to a storage account on each build of the dev branch from ADO. Further more you can access it by navigating to https://aka.ms/InstallAzureCliWindowsEdge

I'm going to submit a PR to update the instructions on our README to mention the new mechanism.

**Comment by fengzhou-msft** [comment]
Edge build rpm package is already uploaded in the storage account in the pipeline, but the package name contains azure cli version, so the url is different for each version. We need to rename the package to have a similar short link like MSI.
