### ISSUE TITLE
Provide Edge Build of Homebrew Package

### ISSUE THREAD

**Issue by marstr** [Azure/azure-cli#8605]
Related to #8139 

To support users looking to test our latest functionality on a machine running macOSX, we can make our existing CI builds available as a formula in a separate [Homebrew tap](https://docs.brew.sh/Taps).

**Comment by marstr** [comment]
Chatting with @devigned this morning, it sounds like having a separate tap to track releases at a different cadence isn't idiomatic for Homebrew. Rather, using [Unstable version](https://github.com/Homebrew/brew/blob/ba2885323776275ddb5456dcd1925605d739acc5/docs/Formula-Cookbook.md#unstable-versions-devel-head) mechanisms in the main formula is more appropriate. What's more, looks [like CLI V1 used this mechanism](https://github.com/Homebrew/homebrew-core/blob/4cffeb3812e7965f3cd49f34b7c1d64ec4f0009f/Formula/azure-cli.rb#L8).

**Comment by marstr** [comment]
I've confirmed here that at time of writing, [our Formula does not use this trick](https://github.com/Homebrew/homebrew-core/blob/d85a6e77835a964adba81b90fc508f0f672bb974/Formula/azure-cli.rb#L7).

**Comment by yugangw-msft** [comment]
I suggest we approach this from the aspect of being cost effective. If it is easy, we do it; otherwise edge builds can live w/o homebrew. Personally I have never received ask on it.

**Comment by marstr** [comment]
Absolutely. I filed these issues separately so that we could prioritize them independently at our next sprint planning meeting.

**Comment by marstr** [comment]
It also gives the community a way to react to different options independently if they would find them useful. :)

**Comment by marstr** [comment]
You can now install the edge version of the CLI via Homebrew by downloading the most recently published formula from https://aka.ms/InstallAzureCliHomebrewEdge and installing with with `brew install -s azure-cli.rb`.

As a single-line shortcut, you can just run:
``` bash
brew install $(curl -Ls -o /dev/null -w %{url_effective} https://aka.ms/InstallAzureCliHomebrewEdge)
```
