### ISSUE TITLE
--destination-asgs not a valid command

### ISSUE THREAD

**Issue by EmilMunk** [Azure/azure-cli#8615]
When creating a rule under a precreated network securit group; 
az network nsg rule create -g &lt;resource&gt; --nsg-name &lt;nameOfNsg&gt; -n test --priority 100 --destination-address-prefix '*' --access Allow

And afterwards try to update this rule to now have an ASG as destination instead of wildcard address-prefix;
az network nsg rule update -g &lt;resource&gt; --nsg-name &lt;nameOfNsg&gt; -n test --destination-asgs &lt;asgName&gt; --access Allow

Then the update command fail with:
Security rule with Id ... must specify a non empty value for exactly one of: DestinationAddressPrefixes, DestinationAddressPrefix, DestinationApplicationSecurityGroups. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afe4941c-7b46-b9fb-1c52-98e68f6354cc
* Version Independent ID: d1bc72fb-ccf9-9645-7b1d-98c91bc75a55
* Content: [az network nsg rule](https://docs.microsoft.com/en-us/cli/azure/network/nsg/rule?view=azure-cli-latest#az-network-nsg-rule-update)
* Content Source: [src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Please provide the output of `az --version`

**Comment by tjprescott** [comment]
The service error message describes why your operation isn't working, albeit not elegantly. You had previously set the address prefix and are now setting the ASG without unsetting the address prefix.

Adding either of these to your command will succeed:
`--destination-address-prefixes ""`
OR
`--remove destinationAddressPrefix`
