### ISSUE TITLE
Long operations timeout the logs

### ISSUE THREAD

**Issue by EriksonBahr** [Azure/azure-cli#8616]
Long operations to build the container timeout the logs:

Step 7/28 : RUN msiexec /i $env:tempFolder\\$env:sqlNCliName /qn IACCEPTSQLNCLILICENSETERMS=YES
 ---&gt; Running in 5f32922dd2f9
CreateComputeSystem 5f32922dd2f9b50fc85497ca8484755e31bf80ddfd89b912ba6760340375fd75: hcsshim: timeout waiting for notification

The only way I manage to make this work is through the --no-logs options. Please document that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c608162e-cf40-9d53-da4a-51f51a0311ea
* Version Independent ID: eccbb543-be68-7de2-d41d-abee55c81452
* Content: [az acr](https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ehotinger** [comment]
@EriksonBahr yeah so this is expected behavior right now. We could consider increasing the timeout or adding an additional CLI flag that allows you to control the client-side timeout maybe, what do you think? How long do your builds go without writing anything?

**Comment by msyihchen** [comment]
@EriksonBahr Let us know if you need anything from this thread.

**Comment by yugangw-msft** [comment]
@EriksonBahr, we are closing this, but please feel free to reactivate it with more information so that we can provide more effective assistence
