### ISSUE TITLE
az context influences --subscription parameter when trying to activate insight monitoring

### ISSUE THREAD

**Issue by tmontalbano** [Azure/azure-cli#8618]
**Describe the bug**

When doing the following command:

az aks enable-addons -a monitoring -n demo-cluster -g demo-group --subscription subName1 -o table

We get the following error:

Operation failed with status: 'Bad Request'. Details: Subscription subId2 is not registered with Microsoft.ContainerService resource provider. This is required to enable Container Insights with /subscriptions/subId2/resourcegroups/defaultresourcegroup-cca/providers/microsoft.operationalinsights/workspaces/defaultworkspace-subId2. Please register and retry.

The problem is because the current context is set to another subscription.

**To Reproduce**

az account show -o table
EnvironmentName    IsDefault    Name                  State    TenantId
-----------------  -----------  --------------------  -------  ------------------------------------
AzureCloud         True         subName2  Enabled  subId2
az aks enable-addons -a monitoring -n demo-cluster -g demo-group --subscription subId1 -o table
Operation failed with status: 'Bad Request'. Details: Subscription subId2 is not registered with Microsoft.ContainerService resource provider. This is required to enable Container Insights with /subscriptions/subId2/resourcegroups/defaultresourcegroup-cca/providers/microsoft.operationalinsights/workspaces/defaultworkspace-subId2. Please register and retry.
az account set -s "subId1"
az account show -o table
EnvironmentName    IsDefault    Name              State    TenantId
-----------------  -----------  ----------------  -------  ------------------------------------
AzureCloud         True         subName1  Enabled  subId1
jenkins@pfu-jenkins:~$ az aks enable-addons -a monitoring -n demo-cluster -g demo-group --subscription subId1 -o table
DnsPrefix                         EnableRbac    Fqdn                                                                KubernetesVersion    Location    Name              NodeResourceGroup                              ProvisioningState    ResourceGroup
--------------------------------  ------------  ------------------------------------------------------------------  -------------------  ----------  ----------------  ---------------------------------------------  -------------------  ---------------
demo-c-demo-group-17d054  True          demo-c-demo-group-17d054-a61b17dc.hcp.canadaeast.azmk8s.io  1.12.4               canadaeast  demo-cluster  MC-demo-group_demo-cluster_canadaeast  Succeeded            demo-group

**Expected behavior**

The current context should not have any influence in the command as long as we put the --subscription parameter in it.

**Environment summary**

Azure-cli 2.0.58
Ubuntu 16.04.5 LTS

We had another similar issue before with another command:
az monitor metrics alert create (see: https://github.com/Azure/azure-cli/issues/8437).

Issue 8437 git fixed in the latest release 2.0.58, but it does not seem to address all azure-cli commands.

Thank you.
Thierry.

**Comment by tjprescott** [comment]
PR #8484 has already implemented the fix. Please try the new version (2.0.59) when it is released next week and re-open if your issue persists.
