### ISSUE TITLE
[ACS] ACS create should take multiple agent pools

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#862]
today we only take one agent pool.  There needs to be a command to add more pools if they can be added after the fact.  Otherwise we need to support them in the create command itself, which required taking arrays of objects

**Comment by BurtBiel** [comment]
for ignite

**Comment by BurtBiel** [comment]
this is not currently supported, so it is moving to the backlog

**Comment by rjtsdl** [comment]
ACS support multiple agent pools since api version 2017-07-01. @BurtBiel  Please help close this. 
Btw 2017-07-01 is only available in acs preview regions. We expect to be everywhere in one or two months.
