### ISSUE TITLE
`az storage blob list --num-results "*"` raises error

### ISSUE THREAD

**Issue by benjspriggs** [Azure/azure-cli#8627]
## problem

I'd like to fetch all blobs in a container. Per the docs:

> --num-results
> Specifies the maximum number of results to return. Provide "*" to return all.
default value: 5000

However, `az storage blob list --num-results "*" --account-name account --container-name container` raises an error:

```
az storage blob list: error: argument --num-results: invalid int value: '*'
usage: az storage blob list [-h] [--verbose] [--debug]
                            [--output {json,jsonc,table,tsv,yaml}]
                            [--query JMESPATH] [--account-name ACCOUNT_NAME]
                            [--account-key ACCOUNT_KEY]
                            [--connection-string CONNECTION_STRING]
                            [--sas-token SAS_TOKEN] --container-name
                            CONTAINER_NAME [--prefix PREFIX]
                            [--num-results NUM_RESULTS] [--include INCLUDE]
                            [--delimiter DELIMITER] [--timeout TIMEOUT]
                            [--auth-mode {login,key}]
                            [--subscription _SUBSCRIPTION]
```

## details

```
$> az --version
azure-cli (2.0.54)

acr (2.1.11)
acs (2.3.13)
advisor (2.0.0)
ams (0.3.1)
appservice (0.2.10)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.5)
billing (0.2.0)
botservice (0.1.3)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.4)
command-modules-nspkg (2.0.2)
configure (2.0.19)
consumption (0.4.1)
container (0.3.10)
core (2.0.54)
cosmosdb (0.2.6)
dla (0.2.3)
dls (0.1.7)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.2)
extension (0.2.3)
feedback (2.1.4)
find (0.2.13)
hdinsight (0.1.0)
interactive (0.4.1)
iot (0.3.4)
iotcentral (0.1.5)
keyvault (2.2.9)
lab (0.1.4)
maps (0.3.3)
monitor (0.2.7)
network (2.2.11)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.2)
rdbms (0.3.5)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.1)
resource (2.1.7)
role (2.2.0)
search (0.1.1)
servicebus (0.3.2)
servicefabric (0.1.10)
signalr (1.0.0)
sql (2.1.6)
storage (2.2.7)
telemetry (1.0.0)
vm (2.2.11)

Extensions:
storage-preview (0.2.0)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\v-bespri\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 472d5f5f-3ce0-1220-3058-4b27068f512b
* Version Independent ID: 76e1699e-e6ba-c0dd-aad4-c5a7ab58260d
* Content: [az storage blob](https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az-storage-blob-list)
* Content Source: [src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Thanks for the report @benjspriggs. Looks like a problem with the parameter metadata.

**Comment by williexu** [comment]
@benjspriggs this issue was addressed in later versions. Can you upgrade your version of the CLI?

**Comment by benjspriggs** [comment]
I upgraded it, and it seems to have fixed the issue. Thanks @williexu!

**Comment by DonFrazier** [comment]
az --version
azure-cli                         2.0.76

az storage blob list -c myContainer --account-name myblobname --subscription 'my subscription name' --num-results 10 

The marker should be part of the payload otherwise there's no way to script enumeration of the entire blob unless you use --num-results * or similar.

from powershell 

$json = (az storage blob list -c myContainer --account-name myblobname --subscription 'my subscription name' --num-results 10 ) | ConvertFrom-Json

The $json variable should include the marker value.
