### ISSUE TITLE
missing character in list example

### ISSUE THREAD

**Issue by CloudCrusader** [Azure/azure-cli#8629]
Hi, the example to list VM extensions has a missing character for the resource group.
it shows -r but should be --r

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ebbeb5f-6ab6-3fb3-c969-5d935e60f251
* Version Independent ID: 9d4169c9-f5b5-512a-8061-2234d6dec1eb
* Content: [az vm extension](https://docs.microsoft.com/en-us/cli/azure/vm/extension?view=azure-cli-latest#az-vm-extension-list)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
The example to list VM extensions is:
`az vm extension list -g MyResourceGroup --vm-name MyVm`

This is correct. Can you copy the exact problematic example?

**Comment by CloudCrusader** [comment]
hi, my bad. seems indeed correct.
topic can be closed
