### ISSUE TITLE
There should be a way to discover components that can be installed

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#863]

**Comment by mayurid** [comment]
is az --version a possible way?

**Comment by derekbekoe** [comment]
A command like `az component search` was suggested also.

**Comment by mayurid** [comment]
@derekbekoe : Perhaps something like az component list-available or a parameter to az component list
@jasonrshaver to comment as well

**Comment by derekbekoe** [comment]
Provisionally marked this for Sprint 7 but it's a short sprint so may fall into the next sprint.
