### ISSUE TITLE
az network public-ip list command intermittently returns incomplete results

### ISSUE THREAD

**Issue by theDogOfPavlov** [Azure/azure-cli#8634]
**Describe the bug**
The _az network public-ip list_ command intermittently returns incomplete results. 

I have a script that calls the interface every 10min then processes the results. Every few days there will be a successful response that includes results that will simply be incomplete and missing a lot of the expected entries. After the spurious response the API returns to operating as expected for another few days. No errors are returned.

**To Reproduce**
Create a loop to repeatedly call the command and then delta the results, then wait for it to vary wildly.

**Expected behavior**
The command should return a consistent set of results.

**Environment summary**
Ubuntu package.

**Additional context**
N/A

**Comment by tjprescott** [comment]
Hi @theDogOfPavlov the command merely returns what the service does, so the aberrant behavior you experienced occurs on the service side.

**Comment by theDogOfPavlov** [comment]
Ah, fair enough. I shall poke the Azure chaps. ;)

**Comment by MyronFanQiu** [comment]
@theDogOfPavlov Hello. How about this issue?

**Comment by theDogOfPavlov** [comment]
As above: the script just wraps the service.

I raised it with the Azure support team directly, and it looks like at some point during the discussion the underlying issue was resolved.

I've not seen a recurrence in a few months.
