### ISSUE TITLE
Cannot create a docker user wit a service principal

### ISSUE THREAD

**Issue by dkmbw** [Azure/azure-cli#8637]
**Describe the bug**
I create a service principal X which is the owner of the subscription. I give the service principal Active Directory Privileges to manage its own apps and read/write directory  with azure cli
i login and create a acr and try to create a service principal which can push and one who can pull from the ACR. 

There is an error management that i have NOT sufficient privileges. 
BUT: when i click in the UI the GRANT for the permissions and it works. but azu app permission grant DOES NOT work as DESCRIBED by the Documentation.

**To Reproduce**
1. az ad sp create-for-rbac --name "myadmin" --role="Owner" --scopes="/subscriptions/${SUBSCRIPTION_ID}"
2. 	az ad app permission add --id "${MYADMIN_ID}" --subscription "${SUBSCRIPTION_ID}"  --api 00000002-0000-0000-c000-000000000000 --api-permissions 5778995a-e1bf-45b8-affa-663a9f3f4d04=Role  824c81eb-e3f8-4ee6-8f6d-de7f50d565b7=Role  78c8a3c8-a07e-4b9e-af1b-b5ccab50a175=Role 78c8a3c8-a07e-4b9e-af1b-b5ccab50a175=Scope

(potential az app permission grant --id ... -- subscription --api ..)

3. login with myadmin (az login --service-principal ...)
4. create acr 
5. az ad sp create-for-rbac --name http://the-user --scopes /subscriptions/1cb7df76-fc9f-4676-97ee-XXXXXXX/resourceGroups/YY-XX-registry/providers/Microsoft.ContainerRegistry/registries/xXYY --role acrpull --query password --output tsv

**Expected behavior**
Either that the service principal can create docker service principal after az app permission add OR after az app permission grant with the AZURE CLI, WITHOUT THE AZURE Wizard/WebsiteUI

**Environment summary**
bash > 4, latest azure:
After apt update && apt upgrade -y 
azure-cli                         2.0.58

acr                                2.2.0
acs                               2.3.17
advisor                            2.0.0
ams                                0.4.1
appservice                        0.2.13
backup                             1.2.1
batch                              3.4.1
batchai                            0.4.7
billing                            0.2.0
botservice                         0.1.6
cdn                                0.2.0
cloud                              2.1.0
cognitiveservices                  0.2.4
command-modules-nspkg               2.0.2
configure                         2.0.20
consumption                        0.4.2
container                         0.3.13
core                              2.0.58
cosmosdb                           0.2.7
dla                                0.2.4
dls                                0.1.8
dms                                0.1.2
eventgrid                          0.2.1
eventhubs                          0.3.3
extension                          0.2.3
feedback                           2.1.4
find                              0.2.13
hdinsight                          0.3.0
interactive                        0.4.1
iot                                0.3.6
iotcentral                         0.1.6
keyvault                          2.2.11
kusto                              0.1.0
lab                                0.1.5
maps                               0.3.3
monitor                           0.2.10
network                            2.3.2
nspkg                              3.0.3
policyinsights                     0.1.1
profile                            2.1.3
rdbms                              0.3.7
redis                              0.4.0
relay                              0.1.3
reservations                       0.4.1
resource                          2.1.10
role                               2.4.0
search                             0.1.1
security                           0.1.0
servicebus                         0.3.3
servicefabric                     0.1.12
signalr                            1.0.0
sql                                2.1.9
sqlvm                              0.1.0
storage                            2.3.1
telemetry                          1.0.1
vm                                2.2.15

Python location '/opt/az/bin/python3'
Extensions directory '/home/benutzer01/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Feb 12 2019, 02:10:26) 
[GCC 7.3.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by yugangw-msft** [comment]
@dkmbw for the step 2 of `az ad app permission` if you click the "grant permission" button in the portal instead, does it work? If yes, then `az ad app permission` has a bug

**Comment by dkmbw** [comment]
Yes, when i do az ad app permission via script and do the "grant permission" via Portal, then it works! Interesting i found a bug! :)

**Comment by dkmbw** [comment]
This is certainly annoying and happens with App Permissions as well, here's an example:

`az ad app create --display-name testname --homepage https://url --reply-urls https://url/oauth2/callback --identifier-uris https://url/ --password password
{
  ....
}
Works, Check.

export OAUTHUSER_ID=$(az ad app list --query '[].{tname:displayName, theid:appId}' -o table | grep testname | awk '{ print $2 }')

Works, Check.



az ad app permission add --id "${OAUTHUSER_ID}" --subscription fcc317e5-a877-4222-0034-d12999989c1e --api 00000002-0000-0000-c000-000000000000 --api-permissions 311a71cc-e848-46a1-bdf8-97ff7156d8e6=Scope
Invoking "az ad app permission grant --id 8a22abfc-61c7-4b08-84c0-062fba4508a3 --api 00000002-0000-0000-c000-000000000000" is needed to make the change effective


Ah, the program says we have to grant something?

az ad app permission grant --id "${OAUTHUSER_ID}" --api 00000002-0000-0000-c000-000000000000


Operation failed with status: 'Bad Request'. Details: 400 Client Error: Bad Request for url: https://graph.windows.net/547a6153-3590-49ee-93b5-c57fe6bea227/oauth2PermissionGrants?api-version=1.6

.... What?`

:)

**Comment by yugangw-msft** [comment]
@dkmbw, #8787 has the change to deal with this error, but to cross check, can you run the `grant` with `--debug` and let me know the trace on the wire? I can be reached at yugangw at microsoft dot com

**Comment by MakerSquid** [comment]
I feel like I have the same issue.  Is there any new information?

When I add permissions to an application, I get the message showing how to invoke the permission grant.  When I execute that permission grant I get the same error as above.

Example:
Invoking "az ad app permission grant --id c23346c7-8cac-4c0a-9e18-c7f2721143a9 --api 00000002-0000-0000-c000-000000000000" is needed to make the change effective
az ad app permission grant --id c23346c7-8cac-4c0a-9e18-c7f2721143a9 --api 00000002-0000-0000-c000-000000000000
Operation failed with status: 'Bad Request'. Details: 400 Client Error: Bad Request for url: https://graph.windows.net/{SubscriptionIDHidden}/oauth2PermissionGrants?api-version=1.6

**Comment by MakerSquid** [comment]
My CLI was slightly outdated.  Using 2.0.62 produces the same 404 as the cloud shell.

**Comment by MakerSquid** [comment]
Finally, I see that there is an issue where 404 means there are no permissions found.  Seemingly, the adding of permissions via CLI isn't working unless the portal is used to give admin consent.  Possibly fixed by changes discussed here: https://github.com/Azure/azure-cli/issues/8310

**Comment by MakerSquid** [comment]
The problems I was having seem to all be related to the fact that a couple of my guids identifying permissions were wrong.  An error to that effect would be nice, but things seem to work fine with the latest version and valid guids.

**Comment by yugangw-msft** [comment]
Closing per comment that things seem to work fine in the latest version. Also admin-grant has been implemented in the latest, which should get all scenario working
