### ISSUE TITLE
Formatting goes off screen

### ISSUE THREAD

**Issue by adost10A** [Azure/azure-cli#8638]
https://imgur.com/a/NbegfNm

This is what the site renders on Firefox (Latest) and Chrome (Latest). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74997eeb-6fa3-4318-79da-8cf4dce59cfe
* Version Independent ID: c8cea09f-196e-7269-dc42-b6b8933dbaf1
* Content: [az disk](https://docs.microsoft.com/en-us/cli/azure/disk?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/disk.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/disk.yml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
@dendeli-msft please add this to your backlog. It relates to the display of text in the online reference docs.

**Comment by tjprescott** [comment]
Closing as this is not actionable by the CLI team.

**Comment by gldraphael** [comment]
Please reopen this. The first section is illegible. The only way to read it right now is to copy it into another application.

**Comment by rloutlaw** [comment]
@tjprescott This is an issue with the storage help.py source. The long-summary field is essentially declaring a blockquote with the '>4' before the text which we will intentionally interpret as a code block and not wrap text in. Either have the storage team remove the >4 or format the text in their blockquote so it doesn't wrap the page.
