### ISSUE TITLE
Lacking info in documentation for az aks upgrade

### ISSUE THREAD

**Issue by theadzik** [Azure/azure-cli#8640]
Hi

I'm wondering if someone could add the format in which data is returned by az aks upgrade command when the upgrade was successful and when it was not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by palma21** [comment]
If it's successful it will display the new cluster config. If it isn't it will display an error message (which can vary depending on the error)
