### ISSUE TITLE
Make CI fail for PRs to azure-cli/master

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#8643]
Add pre-check to CI to immediately reject PRs made to the master branch, as this complicates the release process if something sneaks through (spoiler alert: something did!)

**Comment by marstr** [comment]
To add a little context for outside folks, our release docs are currently regenerated whenever the `master` branch is updated. For that reason, contributions come to us via the `dev` branch. When something accidentally sneaks into `master` unintentionally it breaks some of our partners and clutters our Git history when we go to fix things.
