### ISSUE TITLE
sql automatic tuning

### ISSUE THREAD

**Issue by ranokarno** [Azure/azure-cli#8649]
Hi, 
can anyone advise what is azure cli syntax equivalent for `sqlserver automatic tuning` as mentioned in documentation below.

[sqlserver RestAPI](https://docs.microsoft.com/en-us/rest/api/sql/serverautomatictuning/update#updates_server_automatic_tuning_settings_with_all_properties)

**Comment by danimir** [comment]
@ranokarno CLI command for automatic tuning is not available, and not planned for development at this time. Thank you.

**Comment by yugangw-msft** [comment]
@ranokarno, you can consider `az rest` meanwhile

**Comment by ranokarno** [comment]
thanks @yugangw-msft ,
I am using rest-api for automatic tuning requirement.
