### ISSUE TITLE
'az consumption usage list' does not return 'tags' anymore

### ISSUE THREAD

**Issue by fogelk** [Azure/azure-cli#8651]
**Describe the bug**
While using CLI to obtain consumption usage list, all resources do not contain its tags. For all of them is a null value.
It worked Monday last week.

**Environment summary**
azure-cli (2.0.55) & azure-cli (2.0.59) as well / Windows 10

**Comment by iqbal-nazir** [comment]
We are having the same issue. We know it was listing all the tags and also deployed a script in our test environment with this command. Now, we wanted to deploy that in our production environment and noticed it's not working anymore. We find only the `tags` key, but not the values.

Environment: azure-cli (2.0.52) / Windows 10

**Comment by yonzhan** [comment]
consumption

**Comment by ms-premp** [comment]
This should be working already. Please close this out.
