### ISSUE TITLE
Linter Exclusions Broken by move into azure-cli package

### ISSUE THREAD

**Issue by marstr** [Azure/azure-cli#8656]
During the PR #8646, we discovered that our mechanism for excluding CI violations is broken when command_modules are moved in the azure-cli package. However, in that PR it was easier to just fix the issues that the linter was catching than to fix our exclusion logic. This issue captures the follow-up work that must be finished before we transition the individual service command_modules into the main package.

**Comment by yonzhan** [comment]
@haroldrandom  add to S162.

**Comment by haroldrandom** [comment]
@MyronFanQiu can you take a look?

**Comment by MyronFanQiu** [comment]
I didn't find this issue during my debug process. Has it been fixed?

**Comment by haroldrandom** [comment]
Can not reproduce. Seems it's been fixed.
