### ISSUE TITLE
[VM]  Azure Image Builder Commands

### ISSUE THREAD

**Issue by adewaleo** [Azure/azure-cli#8657]
Issue to track azure image builder commands progress.

Let us discuss bugs, features and improvements here.

PR: https://github.com/Azure/azure-cli/pull/8647

**Comment by feiyushi** [comment]
Just start trying it out, still getting familiar with commands. Something minor to start with:
- for command `az image-builder output add`, the argument `--output-name` and `--name` is a bit confusing. Usually `--name` indicates the name of the output in this command subgroup. I'd suggest something like `--name` for the output name and `--template-name` for its template name.

**Comment by danielsollondon** [comment]
I was just running this, and hit: 
bash-4.4# az image-builder template list -g ibdemo
InvalidResourceNamespace - The resource namespace 'Microsoft.VirtualMachineImages' is invalid.
bash-4.4#

**Comment by adewaleo** [comment]
@danielsollondon. Are you logged into the correct subscription. Try `az account show` to see your current subscription. And use `az account set -s subscription_name_or_id` to set to the whitelisted subscription.

**Comment by adewaleo** [comment]
Work to do by April 2nd:
- Move commands to az image
- Support customizing windows server image and new customizers
- update to new API version.
- add tags support for images and possibly templates
- support exporting image to VHD
- custom managed image as source base image.

See [here](https://github.com/danielsollondon/azvmimagebuilder/blob/master/aibMarch2019Update.md) for more info. [Quickstarts](https://github.com/danielsollondon/azvmimagebuilder/tree/master/quickquickstarts).

**Comment by adewaleo** [comment]
> Just start trying it out, still getting familiar with commands. Something minor to start with:
> 
> * for command `az image-builder output add`, the argument `--output-name` and `--name` is a bit confusing. Usually `--name` indicates the name of the output in this command subgroup. I'd suggest something like `--name` for the output name and `--template-name` for its template name.

It would be good to get feedback from users on this. I opted for `--output-name` because the command is adding an output to a template. I would be more inclined towards `--template-name` if outputs were bonafide resources and the command was associating a template with an image template. Moreover, the command support the use of `--ids` to add an output to multiple templates given their resource ids.

@yugangw-msft  @danielsollondon what do yo think?

**Comment by adewaleo** [comment]
fixed in #9641
