### ISSUE TITLE
AKS Admin Credentials Persist 

### ISSUE THREAD

**Issue by Xorima** [Azure/azure-cli#8660]
Hi,

Admin credentials appear to still be usable even after a user has access revoked to admin credentials:

Steps to reproduce:
User A is granted roles of: 
* Contributor
* Reader
User A gets `--admin` credentials
User A then has the following permissions set:
* Azure Kubernetes Service Cluster User Role
* Reader
Note: They should no longer have admin credentials, however the admin context will still work. 

Expected outcome: Admin Credentials stop working. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by Xorima** [comment]
@tjprescott  any chance of getting this triaged and looked at?

**Comment by tjprescott** [comment]
@mboersma can you take a look?

**Comment by mboersma** [comment]
Unfortunately this is a known issue that is not yet fixed, although I think the work is on our roadmap for the future. cc: @jnoller.

(This isn't an AKS CLI issue, so it might be more useful to track it at our AKS repo. See https://github.com/Azure/AKS/issues/756 for example.)

**Comment by jnoller** [comment]
Known issue, tracked on the AKS issue. Can not provide dates at this time

**Comment by Xorima** [comment]
Hi @jnoller / @mboersma 

Could I get an update on this as our security team are nervous of this going into production as is

**Comment by jnoller** [comment]
@Xorima This is not an issue on the Azure CLI, this is a known limitation of AKS currently with support for kubernetes certificate rotation on track for 2019 delivery, please see: https://github.com/Azure/AKS/issues/756
