### ISSUE TITLE
az webapp up defaults to Node 8.11

### ISSUE THREAD

**Issue by yiliaomsft** [Azure/azure-cli#8664]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by panchagnula** [comment]
Need to check more into this, we should be defaulting to 8.11 for up.

**Comment by panchagnula** [comment]
This was because an older version of webapp extension version was being used that had an older node version as default
