### ISSUE TITLE
Az webapp up should enable logging by default

### ISSUE THREAD

**Issue by yiliaomsft** [Azure/azure-cli#8666]
Please refer to https://docs.microsoft.com/en-us/cli/azure/webapp/log?view=azure-cli-latest#az-webapp-log-config

**Comment by tjprescott** [comment]
@panchagnula for consideration.

**Comment by adewaleo** [comment]
@panchagnula moving this to sprint 57

**Comment by panchagnula** [comment]
@yiliaomsft , looking more into this, turning on this will cause an app recycle & so we don't turn this on by default on Portal either. Please comment if you still think this is required.

**Comment by panchagnula** [comment]
Added a --logs parameter for now as an optional parameter
