### ISSUE TITLE
The subscription of 'xxx' doesn't exist in cloud 'AzureCloud'

### ISSUE THREAD

**Issue by kawayiboy** [Azure/azure-cli#8667]
**Describe the bug**
When I installed azurecli and run it on VSTS, https://msazure.visualstudio.com/One/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=62027
When I try to set it to another available subscription, this error appear:
ERROR: The subscription of 'iotc_client_whitelist_ppe' doesn't exist in cloud 'AzureCloud'.
https://msazure.visualstudio.com/One/_build/results?buildId=20484963

**To Reproduce**
In VSTS, after installation, I just execute 3 lines bash
az cloud set --name AzureCloud
az login --service-principal --username xxx --password xxx --tenant 72f988bf-86f1-41af-91ab-2d7cd011db47
az account set -s IOTC_CLIENT_WHITELIST_PPE
This error would appear,
ERROR: The subscription of 'iotc_client_whitelist_ppe' doesn't exist in cloud 'AzureCloud'.
but weird thing is I can do it in shell.azure.com, or do it through the local powershell, but not the bash in VSTS, could you go here to see what I did wrong?
https://msazure.visualstudio.com/One/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=62027

**Expected behavior**
the command should execute successfully

**Environment summary**
Install through VSTS

**Additional context**
my email is telu@microsoft.com, thanks

**Comment by kawayiboy** [comment]
ping...

**Comment by tjprescott** [comment]
@marstr you have the most context on Azure DevOps--can you take a look? @kawayiboy if you are able to accomplish your scenario on Cloud Shell and locally, then you would likely need to engage with the Azure DevOps team on this.

**Comment by yugangw-msft** [comment]
@kawayiboy if you are switching clouds, I suggest try the same scenario in the upcoming release which contains a fix towards a similar issue #8641

**Comment by kawayiboy** [comment]
> ou have the most context on Azure DevOps--can you take a look? @kawayiboy if you are able to accomplish your scenario on Cloud Shell and locally, then you would likely need to engage with the Azure DevOps team on this.
