### ISSUE TITLE
[VM Create]How to add multiple ssh keys while creating VM?

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/azure-cli#8669]
Hi,

We wish to add multiple ssh keys while creating VM. For example, I wish to create a VM with user "azureuser" and add 2 public keys to it. The RestAPI(https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/createorupdate#create_a_vm_with_ssh_authentication.) can support this feature. Is this feature supported in Azure CLI? Thanks!

**Comment by yugangw-msft** [comment]
Not supported through `vm create`, and also after a vm gets create, the `linuxConfiguration.ssh.publicKeys` becomes read-only. Based on that, before we get more votes for the support, right now, your workaround is:
1. az vm create --debug --validate" and get the template
2. Add a new ssh entry into the template file
3. Run `az group deployment create <template-file>`

**Comment by yugangw-msft** [comment]
@adewaleo, let us wait on this before we get more votes. If we need to expand the `--ssh-key-value` to be a list

**Comment by adewaleo** [comment]
@yugangw-msft, this might also be a good candidate for generic `--set` for create commands.

**Comment by yuxisun1217** [comment]
@yugangw-msft Thanks for the workaround and looking forward to the new feature support :)

**Comment by adewaleo** [comment]
@yuxisun1217, this feature has been added via #9306 with `--ssh-key-values`. `--ssh-key-value` would also work. They are now aliases for one another. 

These change should be in our upcoming release.

**Comment by yuxisun1217** [comment]
Got it. Thank you so much!
