### ISSUE TITLE
Examples for 'az vmss extension image list' don't work

### ISSUE THREAD

**Issue by stijnherreman** [Azure/azure-cli#8670]
The first example gives an error:

```
C:\Users\herremanst>az vmss extension image list --query "[].publisher" -o tsv | sort -u
-uThe system cannot find the file specified.
[Errno 22] Invalid argument
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-bb1gu7gd\knack\knack\cli.py", line 212, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-bb1gu7gd\knack\knack\output.py", line 134, in out
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-bb1gu7gd\colorama\colorama\ansitowin32.py", line 41, in write
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-bb1gu7gd\colorama\colorama\ansitowin32.py", line 162, in write
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-bb1gu7gd\colorama\colorama\ansitowin32.py", line 190, in write_and_convert
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-bb1gu7gd\colorama\colorama\ansitowin32.py", line 195, in write_plain_text
OSError: [Errno 22] Invalid argument
```

The other two examples don't work on a Windows system:

```
C:\Users\herremanst>az vmss extension image list --query "[].name" -o tsv | sort -u | grep Docker
-uThe system cannot find the file speci'grep' is not recognized as an internal or external command,
operable program or batch file.
f
```

```
C:\Users\herremanst>az vmss extension image list --query "[?starts_with(publisher, 'Microsoft.Azure.App')].publisher" -o tsv | sort -u | xargs -I{} az vmss extension image list-names --publisher {} -l westus
-uThe system cannot find the file specified.
'xargs' is not recognized as an internal or external command,
operable program or batch file.
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fef366c0-2cea-5bbf-9a1d-e8c826a08edf
* Version Independent ID: dad95e53-7162-07d8-d687-4d6b3db96e2a
* Content: [az vmss extension image](https://docs.microsoft.com/en-us/cli/azure/vmss/extension/image?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machine-scale-sets**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
@stijnherreman, you are running the sample command, which are meant for Bash, in a windows prompt.  
I will keep this issue open as we need to figure out whether we should tag the sample with Shell type

**Comment by adewaleo** [comment]
https://github.com/Azure/azure-cli/issues/8755 seems relevant to this issue.

**Comment by tjprescott** [comment]
@adewaleo yes, it is. I think the simplest fix would simply be to tag it with bash so that it doesn't even appear for Powershell or CMD users. This won't help though when people find the example via docs.

**Comment by adewaleo** [comment]
@tjprescott I agree with this solution, but couldn't this cut out a lot of relevant examples for our windows users?

For example, the example in the first comment is relevant to both Windows and Linux users but would be cut simply because it sorts the output of the CLI command with a bash command. We will need to develop a strategy with how we want to deal with this.

**Comment by adewaleo** [comment]
closing for #8755 as this should solve the general problem of shell-sensitive examples.

In the meanwhile, on powershell you can run:
`az vmss extension image list --query "[].publisher" -o tsv | sort -Unique`
