### ISSUE TITLE
Is az vm encryption disable supported for Linux

### ISSUE THREAD

**Issue by StefanSchoof** [Azure/azure-cli#8671]
On https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/disable-azurermvmdiskencryption?view=azurermps-6.13.0 is stated that the powershell command `Disable-AzureRmVMDiskEncryption` does not support linux vms. Does the `az vm encryption disable` command support linux vms?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4762f857-8a1e-f1bb-7843-3d8fefe28f8e
* Version Independent ID: 91ce956c-c915-5053-56b0-a489fb2f7b00
* Content: [az vm encryption](https://docs.microsoft.com/en-us/cli/azure/vm/encryption?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ejarvi** [comment]
The Azure Disk Encryption for Linux extension does not yet support decryption of Linux VM's that have or have had an encrypted OS disk.  Since the Powershell and CLI commands both call into the same downstream extension to perform that action, they both have that limitation.

**Comment by StefanSchoof** [comment]
This is a information I would expect on the documentation page for the command.

What happens if someone runs this command against a Linux VM? Does it break or should it simple not run?

**Comment by yugangw-msft** [comment]
CLI will error out unless you use `--force` to continue

**Comment by adewaleo** [comment]
@ejarvi @yugangw-msft I will update `vm encryption disable/enable` to make it clear that disable isn't supported for linux vm's.

**Comment by adewaleo** [comment]
I have updated VM encryption's documentation (see pr #8691). Closing this.
