### ISSUE TITLE
examples please

### ISSUE THREAD

**Issue by christiankuhtz** [Azure/azure-cli#8676]
there are no examples here.  it's not clear how to actually correctly specify arguments for commands like az backup protection disable

How do I obtain the correct value for --container-name? it apparently isn't just the vm name

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48754d22-3349-4e45-a315-126569fe9047
* Version Independent ID: 72e517fa-8000-0ec4-1b33-853901d75cb2
* Content: [az backup protection](https://docs.microsoft.com/en-us/cli/azure/backup/protection?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/_help.py)
* Service: **backup**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by christiankuhtz** [comment]
ignore the comment about --container-name.  but this thing needs examples all over in az backup. in the cli commands themselves, examples are largely missing. incredibly confusing command set.

**Comment by pvrk** [comment]
@christiankuhtz : Apologies for the inconvenience. Since Azure Backup CLI currently supports only Azure VM backups, the documentation is about Azure VM backups only. Will have a relook at the documentation.

**Comment by pvrk** [comment]
Added examples for all az backup related commands which should also be appearing in the command help text. Working on adding documentation in Azure Backup section using CLI.

Closing this bug. Please feel free to re-open if the command help-text or documentation is in-sufficient.
