### ISSUE TITLE
unregister?

### ISSUE THREAD

**Issue by christiankuhtz** [Azure/azure-cli#8677]
Where is the command to unregister items from a container?  The equivalent of     Unregister-AzureRmRecoveryServicesBackupContainer -Container $container

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09210de3-5f1e-a72e-286b-998275969c13
* Version Independent ID: c5f2c022-f67d-b53f-9e63-ebb9acbb22de
* Content: [az backup container](https://docs.microsoft.com/en-us/cli/azure/backup/container?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/_help.py)
* Service: **backup**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by christiankuhtz** [comment]
or rather unregister the container. is this whole feature set incomplete in az backup? what am i missing?

**Comment by pvrk** [comment]
@christiankuhtz : Currently Azure CLI for backup is only supported for Azure VM backups. Unregister is not used for Azure VM backups. It will be added with future releases. May I know what is the scenario for unregister which you are testing with Azure backup CLI?

**Comment by pvrk** [comment]
@christiankuhtz: any update on this please?

**Comment by pvrk** [comment]
@christiankuhtz : Any update on this please?

**Comment by pvrk** [comment]
Closing this issue since un-register is not required for VM backups. It has been added for AFS backups and HANA backups.
