### ISSUE TITLE
Storage errors need better text

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#868]
When my env var for my storage account was invalid, I got this error with no details or next steps.  

```
$ az storage share list

ConnectionError
```

**Comment by mayurid** [comment]
@tjprescott : I assume this is the error that the SDK call returns?

**Comment by binderjoe** [comment]
+1.  This is pretty bad:  
`az storage share create -n foo`
`Unable to obtain data client. Check your connection parameters.`

I don't think P3 is appropriate given the emphasis we put on the need for great, actionable error messages.

**Comment by tjprescott** [comment]
I'll take a look at these.

**Comment by tjprescott** [comment]
cc @devigned
