### ISSUE TITLE
Examples in `az policy definition -h` do not work

### ISSUE THREAD

**Issue by SteveParson** [Azure/azure-cli#8680]
**Describe the bug**
Executing the command  `az policy definition -h` provides documentation about this command. The provided examples do not work. Also, a similar example is present at https://docs.microsoft.com/en-us/cli/azure/policy/definition?view=azure-cli-latest# . These need to be fixed as well.

**To Reproduce**
Try this example that is present in the CLI docs.
```    Create a read-only policy.
        az policy definition create --name readOnlyStorage --rules '{
            "if":
            {
                "field": "type",
                "equals": "Microsoft.Storage/storageAccounts/write"
            },
            "then":
            {
                "effect": "deny"
            }
        }'
```

Also, try the one present on the web.
```
az policy definition create --name readOnlyStorage --rules '{ \
                            "if": \
                            { \
                                "field": "type", \
                                "equals": "Microsoft.Storage/storageAccounts/write" \
                            }, \
                            "then": \
                            { \
                                "effect": "deny" \
                            } \
                        }'
```

**Expected behavior**
I would expect the policy to be created.

**Environment summary**
azure-cli (2.0.55)
Powershell 
``` $psversiontable.psversion
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17134  590
```
**Additional context**
Actual behavior: 
```
> az policy definition create --name readOnlyStorage --rules '{ \
>>                             "if": \
>>                             { \
>>                                 "field": "type", \
>>                                 "equals": "Microsoft.Storage/storageAccounts/write" \
>>                             }, \
>>                             "then": \
>>                             { \
>>                                 "effect": "deny" \
>>                             } \
>>                         }'
Expecting property name enclosed in double quotes: line 1 column 3 (char 2)
```

**Comment by tjprescott** [comment]
This syntax is specific for bash, and any shell-specific syntax in the CLI is specific to bash, never Powershell or CMD.exe.

For Powershell, you can put the JSON content of rules into a file and load that file using `--rules @filename.json`

**Comment by SteveParson** [comment]
Thanks for noticing that. I should have noticed based on the line-split character, but I am new to Powershell.

Since this example is the one presented when you call `az policy definition create -h` (even from powershell), would it make sense to make the output dependent on the shell context?

**Comment by tjprescott** [comment]
Hi @SteveParson it would make sense, and we've talked about it in the past. I created an issue to track this, though I can't say when it might appear on the horizon.

https://github.com/Azure/azure-cli/issues/8755
