### ISSUE TITLE
Can a metric alert be created with a filter?

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-cli#8683]
It is possible to filter in the metrics graph. Is it possible to filter for the alert?

For example, I able able to filter the graph with `where Host='cameron.coolpc.test`:
![image](https://user-images.githubusercontent.com/80104/53769490-c915d080-3eba-11e9-8c86-0f4716cc7d40.png)

When I click `New alert rule`, the filter is not transferred. In this example, I'd like to send an alert only for the specific host.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d97968df-72c9-e50c-d5b1-54562c1bdef7
* Version Independent ID: 0cde4f15-6464-3106-b787-3ee37c7de0ee
* Content: [az monitor metrics alert](https://docs.microsoft.com/en-us/cli/azure/monitor/metrics/alert?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
There is an example in the command of how to create an alert using dimensional filters:
```
       az monitor metrics alert create -g {ResourceGroup} -n alert1 --scopes {StorageAccountId} \
            --description "Storage Slow Transactions" \
            --condition "total transactions > 5 where ResponseType includes Success" \
            --condition "avg SuccessE2ELatency > 250 where ApiName includes GetBlob or PutBlob"
```

In your case you would use "where Host includes cameron.coolpc.test"
