### ISSUE TITLE
az postgres db <option to create user>

### ISSUE THREAD

**Issue by bartb01** [Azure/azure-cli#8685]
**Is your feature request related to a problem? Please describe.**
I am stuck. I cannot create an automation (bash) script for a pipeline where I create a user with a password for a database in my azure postgres server.
(the exact commands I would like to use are written in **Additional context**)

**Describe the solution you'd like**
the database can be created with "az postgres db create", it would be nice if there was an option like
"az postgres db user add --username < user > --password < password > --database < db > --all-priveledges "

**Describe alternatives you've considered**
tried connecting to the postgres server with 
    psql postgresql://<_user>:<_password>@<_host>:<_port>/postgres
but this does not work, since azure created a suffix to my admin user login: user@server
so the '@' in the username causes the command to fail.

**Additional context**
The commands I want to use in postgres:
o	CREATE DATABASE <DB_NAME>;
o	CREATE USER <KEYCL_USER> WITH PASSWORD '<KEYCL_PASS>';
o	GRANT ALL PRIVILEGES ON DATABASE <DB_NAME> TO <KEYCL_USER>;

**Additionally**
Small issue I would like to add here:
 the command "az postgres db create --help" does not list all arguments, because in the given examples different arguments are used.

**Comment by bartb01** [comment]
If anyone is interested, 
not the most beautiful way, but there is a way to connect to the db in an automation script without exposing password from keyvault, using 'expect':

```
#!/bin/bash
echo "connecting to db ..."
/usr/bin/expect <<EOD
spawn psql -h $SERVER_HOST -U $SERVER_USER -d postgres -c "CREATE DATABASE $DB_NAME;" -c "CREATE USER $KEYCL_USER WITH PASSWORD '$KEYCL_PASS';" -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $KEYCL_USER;"
expect "Password for user $SERVER_USER: "
send "$SERVER_PASS\r"
expect eof
EOD
echo "finished."
```
Note that each psql command needs to be written separately,  and do not forget the carriage return after server password variable.

**Comment by rachel-msft** [comment]
Thank you for submitting feedback @bartb01.

It's preferred that the majority of native database operations (creating/deleting/updating users, tables, functions etc) are done through standard Postgres ways, for example psql. If you need this support through the Azure CLI we encourage you to make a feature request on our [requests page](https://feedback.azure.com/forums/597976-azure-database-for-postgresql) so that other customers who need that feature can add their support.

You mentioned that az postgres db create -h does not list all arguments. Could you please specify which arguments?

**Comment by bartb01** [comment]
Hi @rachel-msf, I understand that these operations are normally done through standard postgres ways. However, this was not possible in a pipeline script for me (except for the work around i mentioned) because i could not escape the '@' in the username.. Because of this, psql considers the '@' in the username as the '@' that separates the password from the host (referring to the command i described in 'describe alternatives you've considered'), therefore the arguments become invalid.

I cannot create a username without the '@' because its a suffix created by azure.
Hence I suggested the azure-cli command. The workaround does not seem like the best solution for obvious reasons, but it has been doing the job for me. Also the additional issue from the 'az postgres db create -h'  command seems to be resolved!

**Comment by rachel-msft** [comment]
@bartb01 Can you try url encoding the @ sign in the user name with %40 

For example, if username = theuser@theserver, it would become theuser%40theserver

and the psql url would be `psql postgresql://theuser%40theserver:Password473635@theserver.postgres.database.azure.com:5432/postgres`

**Comment by bartb01** [comment]
@rachel-msft Yes, that actually seems like an easier solution! thanks

**Comment by rachel-msft** [comment]
Glad that worked out.

@tjprescott #please-close

**Comment by msbhanuprakash** [comment]
do we have az postgres add_schema  with options

**Comment by rachel-msft** [comment]
To create a schema, you would sign in to the server and issue a Postgres CREATE SCHEMA command
