### ISSUE TITLE
"Resource group 'copiedFromPortal' could not be found"

### ISSUE THREAD

**Issue by StingyJack** [Azure/azure-cli#8686]
This command doesnt work. 

Even when I give it the resource group name, the app service name, and subscription, it cant find anything.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9169e28-f731-4772-6aa5-865c7f480a35
* Version Independent ID: 0decf749-52ca-1cc5-b20d-b5eed621281d
* Content: [az webapp webjob continuous](https://docs.microsoft.com/en-us/cli/azure/webapp/webjob/continuous?view=azure-cli-latest#az-webapp-webjob-continuous-list)
* Content Source: [latest/docs-ref-autogen/webapp/webjob/continuous.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/webjob/continuous.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by panchagnula** [comment]
@StingyJack can you give me more details here what is the name of the app & resourcegroup you are were using? Also can you run the command with --debug & copy the details here? Thank you.

**Comment by StingyJack** [comment]
> the name of the app & resourcegroup

um... no. What purpose does it serve that I give you values that you cannot use without permission, or that you (or anyone reading this) may try to use to create an attack later?

The problem here is/was multi part and starts with the ambiguous `--name` parameter. Does it want App Service name? Web App name? Web Job name?  

If you arent sure of more than one value for a set of required arguments, it becomes easy to fall into a successive set of attempts that fail. 

If you think you are sure but get an error indicating otherwise, this is compounded. Consider the case where the wrong subscription is currently set. That error (see issue title) suggests you are entering data incorrectly for the current command when that is not the problem at all. The data entry is 100% correct for the command.

This command (and I suspect many of them) do not list resources in any kind of aggregate manner. If I type `az webapp webjob continuous list` I expect to see all of them - which would actually be useful to determine quickly if any are stopped that should be running - and not the few webjobs that may be on a specific appservice (not "webapp"), in a specific subscription tied to my account.  

Its not terribly useful or efficient to iterate through every subscription to get the app services, and then ask each app service for its continuous webjobs, then ask it again for its triggered webjobs.

**Comment by tjprescott** [comment]
> The problem here is/was multi part and starts with the ambiguous --name parameter. Does it want App Service name? Web App name? Web Job name?

```
Command
    az webapp webjob continuous list : List all continuous webjobs on a selected web app.

Arguments
    --name -n           [Required] : Name of the web app. You can configure the default using 'az
                                     configure --defaults web=<name>'.
```

**Comment by panchagnula** [comment]
Also you can get to the help documentation above  by running  az webapp webjob continuous list -n 
or see this https://docs.microsoft.com/en-us/cli/azure/webapp/webjob/continuous?view=azure-cli-latest#az-webapp-webjob-continuous-list

**Comment by StingyJack** [comment]
So what is the "webapp" name? I'm looking everywhere in the az portal on my app services and resource groups and do not see a web app name displayed. The closest thing I can reckon is the App Service name.

**Comment by panchagnula** [comment]
webapp name is name of the app or appservice name.

**Comment by StingyJack** [comment]
Ok, small but confusing terminology bug in `--help`. I'll submit a PR for that repo when I'm back in front of a PC.
