### ISSUE TITLE
`az container exec` fails using PATH of non-root

### ISSUE THREAD

**Issue by martinvelos** [Azure/azure-cli#8687]
**Describe the bug**
To a Jenkins container
`az container exec --exec-command 'bash -c java -h' --resource-group mygroupp --name jenkifriend` returns 
`rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"bash -c java -h\": executable file not found in $PATH"`.

**To Reproduce**
`az container create  --resource-group mygroupp   --name jenkifriend --image jenkins/jenkins --ports 8080 5000  --dns-name-label $DNS_NAME_LABEL   --location eastus`
When ready, try the command above an see.

**Expected behavior**
print whatever `java -h` does, when in shell that `container exec  --exec-command 'bash'` does.( This two-step way does what expected.)

**Environment summary**
This one obtained by `pipsi`, but I have the same issue with basic `pip` or `dnf`.
azure-cli (2.0.57)
Fedora 29, `bash`  

**Additional context**
Does with any more complex command, even `az container exec --exec-command 'bash -c whoami'`..

**Comment by texnokot** [comment]
Hey,

having same issues with "az container exec"
Tried to run python command with parameters:

`user1@Azure:~$ az container exec -g RG --name images1 --container-name images1 --exec-command "command.py -t some_parameter"
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"command.py -t some_parameter\": executable file not found in $PATH"`

If I try to add $(pwd) in the path for command it takes my machines local directory not the container's one:

`user1@Azure:~$ az container exec -g RG --name images1 --container-name images1 --exec-command "$(pwd)/command.py -t some_parameter"
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"/home/user1/command.py -t some_parameterl\": stat /home/user1/command.py -t some_parameter: no such file or directory"`

**Comment by yonzhan** [comment]
container

**Comment by SaurabhSharma-MSFT** [comment]
@martinvelos Apologies for the delayed response. This GitHub issue has been open for quite some time. Could you please let us know if you still facing this issue and need assistance? Awaiting your reply.

**Comment by romulo-dbts** [comment]
Hi,

Romulo is no longer working with us. But possibly @Ugur Bayazit can follow up.
Have you reached out to Ugur already??

Kind Regards,
Frederik

________________________________
