### ISSUE TITLE
az aks use-dev-spaces fails to install because missing setup blob

### ISSUE THREAD

**Issue by stefaanvermassen** [Azure/azure-cli#8688]
**Describe the bug**
Setup blob on https://azuredevspacestools.blob.core.windows.net/azdssetup doesn't exist anymore

**To Reproduce**
az aks use-dev-spaces

**Expected behavior**
Download setup package from blob storage, unzip and install

**Environment summary**
Bash

**Comment by mboersma** [comment]
@saurabsa do you know what might have happened here?

**Comment by saurabsa** [comment]
Thank you for pointing it out. Looking into it.

**Comment by saurabsa** [comment]
@stefaanvermassen _https://azuredevspacestools.blob.core.windows.net/azdssetup_ is not accessible directly. You need to specify the intended file name. You can use the alias, which az cli uses: **https://aka.ms/get-azds-windows-az** which seems to be working fine
or use command:
_az aks use-dev-spaces -n <resourceName> -g <resourceGroup> --update_

**Comment by stefaanvermassen** [comment]
The file name is indeed specific to the OS version. For Linux, https://azuredevspacestools.blob.core.windows.net/azdssetup/AzdsCliLinux.zip doesn’t seem to work for me.

**Comment by saurabsa** [comment]
@stefaanvermassen  where did you get the above link from and why do you need to access it?
For Linux you can directly use:
**curl https://aka.ms/azds-linux-az | bash** and the script will install AZDS Cli on your machine.

**Comment by stefaanvermassen** [comment]
@saurabsa This is the blob that the install script tries to download, causing the installation to fail.

**Comment by stefaanvermassen** [comment]
**curl https://aka.ms/get-azds-linux-az | bash** seems to work fine, thanks!
