### ISSUE TITLE
brew install into a virtualenv

### ISSUE THREAD

**Issue by marstr** [Azure/azure-cli#8689]
Our homebrew formula installs `az` using system python without a virtual environment. This is causing issues for folks who have existing non-hombrew python installs, or use system Python for their projects.

We should isolate the CLI into its own virtual environment, [the way the bash install script does](https://github.com/Azure/azure-cli/blob/971ce078888f428bfd3799475dbdb1bf41a3e7cf/scripts/curl_install_pypi/install.py#L355). It'll also allow us to fix this logic: https://github.com/Azure/azure-cli/blob/971ce078888f428bfd3799475dbdb1bf41a3e7cf/scripts/release/homebrew/docker/formula_template.txt#L58-L66

Which is getting confused on systems where python3.x is available, but not where the azure-cli was installed. (Folks setting it up in a virtualenv by themselves.)

**Comment by marstr** [comment]
I started chasing this down, and made some good progress after following guidance [here](https://github.com/Homebrew/brew/blob/5eaf4e5c28e7605cd9d8e1631d376b0e46c98624/docs/Python-for-Formula-Authors.md#installing). However, for reasons I do not yet understand, when [pip is invoked](https://github.com/Homebrew/brew/blob/a208ce49e82fd28c3288019d217cc8fab2e64b5d/Library/Homebrew/language/python.rb#L254-L259) by homebrew's virtualenv code, installing resources [`entrypoints`](https://pypi.org/project/entrypoints) and [`jeepney`](https://pypi.org/project/jeepney/) both fail with a very generic error message:

```
pip._internal.exceptions.InstallationError: Command "/usr/local/Cellar/azure-cli/2.0.60/libexec/bin/python3.7 /usr/local/Cellar/azure-cli/2.0.60/libexec/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-2szx5z77/overlay --no-warn-script-location -v --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- flit" failed with error code 1 in None
```

I'm still investigating several ways forward. The happiest case would getting to the bottom of why exactly these dependencies are different than all the rest, and installing them appropriately before invoking Homebrew's code. Alternatively, I could try to cut these dependencies out of our product. Obviously, that could prove to be challenging in its own right.

I partnered with @devigned earlier today to dig, and we didn't make a lot of headway. I'm going to give it another look, and may recruit more help from @lmazuel.

**Comment by marstr** [comment]
Further investigation makes it look like our problems are related to: https://github.com/takluyver/flit/issues/245 and https://github.com/pypa/pip/issues/6222

**Comment by marstr** [comment]
**/CC** @tjprescott @yugangw-msft 
 
Alright, I've spent the better part of the day investigating our options here.

I've confirmed with @lmazuel that at the end of the day, we are not able to install all of our declared resources because of pypa/pip#6222. However, the good news is that the two packages involved (`entrypoints` and `jeepney`) only seem to be included because of [`keyring`](https://pypi.org/project/keyring), which is no longer a requirement of [Azure/msrestazure-for-python](https://github.com/Azure/msrestazure-for-python). Bad news, we can't adopt new versions of msrestazure-for-python because of a couple of delinquent command_modules that are still relying on relatively old versions of management libraries. Assuming that pypa/pip#6222 will not be fixed soon enough for us to just kick the can down the road, the right fix is to rewrite those command modules to use newer management library packages. However, it sounds like as a team we had previously decided it was too expensive to do this. 

What that leaves us with, is the ability to add a hack where we simply just don't declare the two packages involved as dependencies anymore, on @lmazuel word that we don't need them.

**Comment by lmazuel** [comment]
To emphasize, `keyring` was only used in `msrestazure` authentication, which is not even use by the CLI (use it's own ADAL wrapper). And because `keyring` was a problem, I catch any failure and just disable the feature (that again the CLI doesn't use):
https://github.com/Azure/msrestazure-for-python/blob/e347fc59d323edccf04ce9a043768ce4d36b6271/msrestazure/azure_active_directory.py#L49-L53

So in an ideal world, updating these command modules + pip has not bug and the world is all rainbow :). In practical terms, removing `keyring` bypass the issue before it even happens, with no known drawbacks.
My two cents

**Comment by yugangw-msft** [comment]
I support the idea of removing `keyring` to bypass the issue.
In future on potential secure token persistence implementation, we just remember this when consider to using keyring, but that is still too far away to worthwhile think that much
