### ISSUE TITLE
Create Service Principal with multi-tenant property

### ISSUE THREAD

**Issue by michaelmdeng** [Azure/azure-cli#8707]
When I am creating a Service Principal with the command 

```
az ad sp create ...
```

I would also like to be able to specify that I want to create a multi-tenanted principal. Currently, I have to create the principal in the CLI, then navigate to the UI in the Azure portal to toggle the multi-tenanted property.

This will allow us to fully script creation of multi-tenanted principals without user intervention.

**Comment by yugangw-msft** [comment]
Multi-tenant is a configuration at the application level which the Service Principal is associated, so try `-az ad app update --available-to-other-tenants`.
Please reactivate if you still have questions
