### ISSUE TITLE
When uploading blob .wasm files content type set to application/wasm rather then application/octet-stream

### ISSUE THREAD

**Issue by Lupusa87** [Azure/azure-cli#8708]
I do publish blazor apps on azure storage accounts from visual studio code.

Uploaded .wasm file's content type is set to application/octet-stream.

Browser expects for .wasm files content type application/wasm, so we are forced to correct later content types using different ways, which is not convenient and requires extra time.

If it is possible please address this issue.

**Comment by adewaleo** [comment]
@Lupusa87 
Sorry what azure cli command are you having issues with? Or is this a visual studio code / azure portal issue?

**Comment by Lupusa87** [comment]
I guess this is similar as #6257 where it happens with js files.

I don't know, maybe it is Visual studio code issue but I think it is more azure-cli related because what I read in #6257.

I don't know good how this works but reading #6257 I assume that your code can guess mimetype for given extension, if it's true we need to add .wasm - apllication/wasm to you list.

**Comment by tjprescott** [comment]
@Lupusa87 what specific command are you trying to use?

**Comment by Lupusa87** [comment]
I use VS Code, have installed azure storage extension, it adds option - deploy to static website.
Using this command uploads entire folder to selected azure storage account.

![untitled3](https://user-images.githubusercontent.com/40779557/54046811-6dda2b80-41a3-11e9-9245-55169334d4a3.png)

![untitled](https://user-images.githubusercontent.com/40779557/54046812-6f0b5880-41a3-11e9-8bca-f43a65e63cf4.png)

**Comment by tjprescott** [comment]
Since your problem is with the VSCode extension, you would need to open an issue here:
https://github.com/Microsoft/vscode-azurestorage

**Comment by Lupusa87** [comment]
@tjprescott Ok, Thank you.

It will be great if you check on your side how your code handles .wasm files.
