### ISSUE TITLE
Deploy Azure Function to Slot

### ISSUE THREAD

**Issue by mswilson4040** [Azure/azure-cli#8713]
**Resource Provider**
What is the Azure resource provider your feature is part of?

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.

I am on a mac running Visual Studio code. I am trying to deploy my azure function to a slot. I don't see anywhere in the documentation where it states how to do this. I've tried a couple different variations but no luck. Is this supported yet? It appears to be supported within Visual Studio UI but I am looking for the command line or the visual studio code ui equivalent.

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
Latest

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. This should be on the master branch
of the REST API specs repo.

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.

**Comment by panchagnula** [comment]
@ahmedelnably & @ankitkumarr FYI.

**Comment by ahmedelnably** [comment]
this is out in 2.0.68
