### ISSUE TITLE
az eventgrid event-subscription list required parameter

### ISSUE THREAD

**Issue by dcbrown16** [Azure/azure-cli#8717]
**Describe the bug**
Not sure if this is related to this change, but I'm finding that `az eventgrid event-subscription list` at least is requiring the --location parameter, which is contrary to the documentation and examples.
![image](https://user-images.githubusercontent.com/34466884/53932052-a0bddb80-404c-11e9-8ef9-b8ffa8348c78.png)

**To Reproduce**
Run `az eventgrid event-subscription list` with other parameters.

**Expected behavior**
You should be able to run without the location.

**Environment summary**
Portal Bash Shell

**Additional context**
Very strangely, the only subscription I can actually find when using the --location parameter is one that was supposed to have failed.

**Comment by adewaleo** [comment]
@kalyanaj can you look into this. Also can you remove the examples that are in the `--topic-type-name` help for `az eventgrid event-subscription list -h`

https://github.com/Azure/azure-cli/blob/cbcf889258d16d58b4eb9acedc911865d9ace912/src/command_modules/azure-cli-eventgrid/azure/cli/command_modules/eventgrid/_help.py#L229-L235

**Comment by ahamad-MS** [comment]
@dcbrown16 Thanks for reporting this issue. The usage of location parameter is required in some cases for "az eventgrid event-subscription list" command. Event Subscriptions are not Azure Resource Manager (ARM) tracked resource and hence we need to specify the location to determine if this is for "global" event subscription or for specific region (say westus).

For example, "Microsoft.Storage.StorageAccounts" is an event grid topic type is that regional only. Hence, it does not exit in the global context. Hence, the first command fails while the other succeeds.

--> With global location 

az eventgrid event-subscription list --topic-type-name "Microsoft.Storage.StorageAccounts" --location global
Invalid usage: Global cannot be specified for the location as the specified topic type is a regional topic type with regional event subscriptions. Specify a location value such as westus. Global can be used only for global topic types: Microsoft.Resources.Subscriptions and Microsoft.Resources.ResourceGroups.


az eventgrid event-subscription list --topic-type-name "Microsoft.Storage.StorageAccounts" --location westus2

Hope this helps clarifies the difference and the need for location.

**Comment by dcbrown16** [comment]
@ahamad-MS I see, thanks.
