### ISSUE TITLE
[Storage] Add better support for file copies from a share snapshot

### ISSUE THREAD

**Issue by williexu** [Azure/azure-cli#8719]
**Is your feature request related to a problem? Please describe.**

Right now this is supported for a single file copy through specifying a `--source-uri` for a file that indicates a snapshot. This requires a developer to get the file url and append the snapshot name as a query parameter. The CLI can do better to make this scenario smoother.

**Describe the solution you'd like**

A clear and concise description of what you want to happen, a `--snapshot` parameter for both `az storage file copy start/start-batch`

**Describe alternatives you've considered**

**Additional context**

**Comment by binnie268** [comment]
**Describe the solution you'd like**
Wanted to reopen this to see if we could add snapshot support for az storage file copy start-batch?

Thanks!
