### ISSUE TITLE
`az storage blob upload` fails within DevOps

### ISSUE THREAD

**Issue by uniquelau** [Azure/azure-cli#8722]
**Describe the bug**
We have a script that is used across multiple projects to update files into storage.
The script has stopped working for one project, but no changes have been made.
Error thrown saying `account-key` not set, but `account-key` is set via variables.

**To Reproduce**
Hard to reproduce, as identical script and variable setup is working for other projects.

**Environment summary**
Azure DevOps
Azure CLI 1.147.0

The script is "inline"

```az storage blob upload-batch --account-name $(StorageAccountName) --account-key $(StorageAccountKey) --destination $(StorageAccountDestination) --source $(ArtifactWww)```

I have checked that the variable exists, it does, and it has worked for deployments earlier today.

**Additional context**

```
2019-03-07T16:35:36.8892121Z D:\a\r1\a>az storage blob upload-batch --account-name _customer_wwwdev --account-key  --destination $web --source D:\a\r1\a\_Customer_\Www\dist 
2019-03-07T16:35:40.4856930Z ERROR: az storage blob upload-batch: error: argument --account-key: expected one argument
```

**Comment by uniquelau** [comment]
Tried re-deploying, same error persists.
Updated key in variable, issue now resolved.
Very odd.

**Comment by uniquelau** [comment]
Re-opening issue.
A build about an hour later failed.

**Comment by williexu** [comment]
> ```
> 2019-03-07T16:35:36.8892121Z D:\a\r1\a>az storage blob upload-batch --account-name _customer_wwwdev --account-key  --destination $web --source D:\a\r1\a\_Customer_\Www\dist 
> 2019-03-07T16:35:40.4856930Z ERROR: az storage blob upload-batch: error: argument --account-key: expected one argument
> ```

From what you posted above, I see `az storage blob upload-batch --account-name _customer_wwwdev --account-key  --destination  ...`

You did not specify a account key for the `--account-key <key should be here>` parameter. It looks like something is wrong with how your script is supplying that parameter. Since the CLI was not called properly, this is not a CLI issue.

**Comment by uniquelau** [comment]
Linked issue to Azure Pipelines Task issue.
I have made some further investigations.

When the variable `padlock == false` it works on every deployment.
When the variable `padlock == true` it works for the first deployment and then fails.

However, this behaviour is not mirrored in other Azure DevOps projects.

**Comment by mgeorgebrown89** [comment]
I'm experiencing a similar issue. I have a .ps1 script called from an Azure Pipelines yml pipeline. I use it to upload two files and there's no problem. I use it to upload 4 files, only the first 2 are uploaded, and then I get a powershell error exit code 1 with no further details. Running this script locally works just fine.

   [CmdletBinding()]
    param(
        [string]
        $sourcesDirectory,
    
        [string]
        $serviceName,
    
        [string]
        $env = "dev",
    
        [string]
        $storageAccountKey
    )
    
    $storageAccountName = "teamutilities$($env)" 
    
    az storage blob upload --file         "$sourcesDirectory/Infrastructure/BlueGreenDeployment/$serviceName/Secrets.template.json" `
        --container-name "armtemplates" `
        --name "$($serviceName)_Secrets_Template" `
        --account-name $storageAccountName  `
        --account-key $storageAccountKey --debug
    
    az storage blob upload --file     "$sourcesDirectory/Infrastructure/BlueGreenDeployment/$serviceName/Secrets.parameters.json" `
        --container-name "armtemplates" `
        --name "$($serviceName)_Secrets_Parameters" `
        --account-name $storageAccountName  `
        --account-key $storageAccountKey --debug
    
    az storage blob upload --file     "$sourcesDirectory/Infrastructure/BlueGreenDeployment/$serviceName/$serviceName.template.json" `
        --container-name "armtemplates" `
        --name "$($serviceName)_Template" `
        --account-name $storageAccountName  `
        --account-key $storageAccountKey --debug
    
    az storage blob upload --file     "$sourcesDirectory/Infrastructure/BlueGreenDeployment/$serviceName/$serviceName.parameters.json" `
        --container-name "armtemplates" `
        --name "$($serviceName)_Parameters" `
        --account-name $storageAccountName  `
        --account-key $storageAccountKey --debug
