### ISSUE TITLE
`az webapp config appsettings set` examples show using @moreSettings.json but thats not documented for `--settings`

### ISSUE THREAD

**Issue by VictorioBerra** [Azure/azure-cli#8723]
`--settings` shows "Space-separated appsettings in a format of =." but the example snippet above clearly shows `... --settings mySetting=value @moreSettings.json`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30f2ae52-2c7f-7e7e-8a62-f1b614f281d3
* Version Independent ID: 9f23ff17-14e0-7800-0094-fb50a5fa91d6
* Content: [az webapp config appsettings](https://docs.microsoft.com/en-us/cli/azure/webapp/config/appsettings?view=azure-cli-latest#az-webapp-config-appsettings-set)
* Content Source: [latest/docs-ref-autogen/webapp/config/appsettings.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config/appsettings.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by panchagnula** [comment]
@yugangw-msft is this just a case of updating our help for this command?

**Comment by tjprescott** [comment]
@panchagnula yes.

**Comment by VictorioBerra** [comment]
https://github.com/MicrosoftDocs/azure-docs-cli/pull/1337

**Comment by tjprescott** [comment]
@VictorioBerra the change needs to be made in this repo's `_help.py` file.

**Comment by tjprescott** [comment]
https://github.com/Azure/azure-cli/blob/8f30c358850959700bf2711ed90e17ef214dcbb4/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py#L536

**Comment by VictorioBerra** [comment]
@tjprescott I do not see anywhere the --settings is mentioned in that file. The change is only needed in the flags description not the example usage.

![image](https://user-images.githubusercontent.com/2934507/53989936-b551b080-40ec-11e9-9a03-88e0cdf4f31c.png)

**Comment by tjprescott** [comment]
@VictorioBerra the repo you made your PR to is autogenerated. Any change you suggest there will likely not be merged, because if it were, it would be trampled the next time the content is regenerated. It is generated from the CLI source, so you need to make the change to the CLI source. 

In this case, you can add the entry for this to the help.py file, like this:
```
    parameters:
        - name: --settings
          short-summary: <your text here>
```

**Comment by VictorioBerra** [comment]
https://github.com/Azure/azure-cli/pull/8738
