### ISSUE TITLE
--max-events does not match documentation

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-cli#8726]
I thought `--max-events` was going to be the `Maximum number of records to return.`, but the maximum number of records to query.

I get back 7 records with this query:
```
az monitor activity-log list --query "[?level=='Error']" --offset 30d --max-events 500000
```

I get back 0 records with this query:
```
az monitor activity-log list --query "[?level=='Error']" --offset 30d --max-events 50
```

Shouldn't I be getting back 7 records?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6c5dc4-a466-9a0d-6276-98853b6fb4f6
* Version Independent ID: 03fc41a4-f06c-a6fb-fcd6-cd72e0a15add
* Content: [az monitor activity-log](https://docs.microsoft.com/en-us/cli/azure/monitor/activity-log?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
This is a known issue. Please see:
https://github.com/Azure/azure-cli/issues/7816#issuecomment-437981923
