### ISSUE TITLE
activity-log alert create for Administrative category requires additional conditions

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-cli#8732]
When I try to create an activity-log alert for the Administrative category, I get UnsupportedCondition error. Please document what additional conditions for this category are needed.
``` ps1
$category = "Administrative"
az monitor activity-log alert create -n "$category activity $rg" -g $rg --condition category=$category
Specify additional conditions for this category: Administrative. [Code: "UnsupportedCondition"]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d2421be-dcd7-4418-9518-e884b7190a96
* Version Independent ID: eb40fdf2-0776-bee3-3f8d-5e5f042f2504
* Content: [az monitor activity-log alert action-group](https://docs.microsoft.com/en-us/cli/azure/monitor/activity-log/alert/action-group?view=azure-cli-latest#az-monitor-activity-log-alert-action-group-add)
* Content Source: [src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Since this is the error that comes back from the service, they would need to take a look at improving it.

The documentation for activity log alerts is here and may provide some assistance:
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-activity-log

However, you may find it easiest to create your activity log alert in the portal and then create the CLI equivalent.

**Comment by msvijayn** [comment]
Confirming, the error occurs as the rule condition is too broad. As stated in our [Activity Log alert document](https://docs.microsoft.com/azure/azure-monitor/platform/alerts-activity-log) :
![image](https://user-images.githubusercontent.com/33087919/60345097-d872d980-99d5-11e9-9f14-ebcce4b6c1e3.png)

**Comment by msvijayn** [comment]
#please-close

**Comment by JohnDelisle** [comment]
Apologies for replying to such an old thread.  The warning you've highlighted is no longer present on that page.  Is it still relevant?  

I'm troubleshooting this error:
`Alert Rule with category 'Administrative' and subscription scope must have at least one additional filtering condition. `

Google brought me here, and if I understand correctly it seems we cannot have a rule that matches category = administrative, and any-of operationName = abc, operationName = xyz.   We must create an alert rule for each operation name. 

Is that correct?  Should the docs be updated to reflect this limitation?
