### ISSUE TITLE
webapp webjob: examples needed

### ISSUE THREAD

**Issue by Leon99** [Azure/azure-cli#8733]
It would be great to have some examples of performing an operation on multiple webjobs.
One particular problem I faced is I needed to stop multiple webjobs, however, `stop` command seems to require just the webjob name, while `list` command returns name as `webAppName/webjobName`, so it's not straightforward.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9169e28-f731-4772-6aa5-865c7f480a35
* Version Independent ID: 0decf749-52ca-1cc5-b20d-b5eed621281d
* Content: [az webapp webjob continuous](https://docs.microsoft.com/en-us/cli/azure/webapp/webjob/continuous?view=azure-cli-latest#az-webapp-webjob-continuous-list)
* Content Source: [latest/docs-ref-autogen/webapp/webjob/continuous.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/webjob/continuous.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by panchagnula** [comment]
Please refer to the examples here https://docs.microsoft.com/en-us/cli/azure/webapp/webjob/continuous?view=azure-cli-latest#az-webapp-webjob-continuous-stop

stop does take the webapp name as optional parameter, if this is not provided, then the command tries to use the name set in the global/local config  see this for more info https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-configure

**Comment by Leon99** [comment]
Thanks @panchagnula, but I don't see an example that covers what I asked for (performing an operation on multiple webjobs) in the links you provided. Does closing this issue mean that you won't add it?

**Comment by panchagnula** [comment]
Managing Multiple webjobs in the same command no - not going to be supported at this time, the solution is to call the command for each of the webjob. Thank you.

**Comment by Leon99** [comment]
> Managing Multiple webjobs in the same command

It's OK but it's not what I asked for. I asked for an example of doing it, not necessarily by using one command. I also stated why it's not straightforward, please re-read my issue.

**Comment by panchagnula** [comment]
@Leon99 clearly i did not understand your question - let me take another shot & see if i got it this time.

az webapp webjob continuous list -> does return the full list of continuous webjobs related to the webapp [--name parameter]
the list command returns the name as this webAppName/webjobName
 the stop command takes webappname, webjob name as parameters
Ex. would be to run this way 
`az webapp webjob continuous stop --name webAppName --resource-group MyResourceGroup --webjob-name webjobName`

let me know if this helps.
