### ISSUE TITLE
--address-prefix shouldn't be used in the example

### ISSUE THREAD

**Issue by ryancfields** [Azure/azure-cli#8737]
https://docs.microsoft.com/en-us/cli/azure/network/vnet/subnet?view=azure-cli-latest#feedback

The first example shows "--address-prefix" it should be "--address-prefixes".  

az network vnet subnet create -g MyResourceGroup --vnet-name MyVnet -n MySubnet \
                            **--address-prefix** 10.0.0.0/24 --network-security-group MyNsg --route-table MyRouteTable

**Comment by tjprescott** [comment]
The way argparse matches arguments, it will correctly match `--address-prefix` to `--address-prefixes`. If you run the example, you will find that it works.

**Comment by ryancfields** [comment]
If it is expected that we can use --address-prefix, can it be included in the optional parameters?

**Comment by ryancfields** [comment]
It is not clear how both work since --address-prefix is not documented but is used in the example.

Optional Parameters:
--address-prefix (accepts a single CIDR Range)

Required Parameters:
--address-prefixes - Space-separated list of address prefixes in CIDR format.

**Comment by ryancfields** [comment]
Or if they both do the same thing, why not just change the example.

**Comment by ryancfields** [comment]
After this experience, I am hesitant to continue to provide my feedback for Azure services.  The response that the command still works is not what I was asking.  I raised an issue regarding the example in the documentation not using the required parameters.

**Comment by tjprescott** [comment]
@ryancfields we welcome your feedback. The example using `--address-prefix` instead of `--address-prefix` is simply demonstrating a feature of argparse and since there is no reason for the customer not to leverage such a feature, we see no reason that examples should not also leverage this feature as long as the example works.

That being said, we would not reject a PR that made such a change.

**Comment by ryancfields** [comment]
That sounds good to me, I will open a PR now.
