### ISSUE TITLE
az webapp create java 

### ISSUE THREAD

**Issue by jvano** [Azure/azure-cli#8742]
Long story short, we need “az webapp create” or “az webapp up” for java apps. It should be interactive and prompt for stack to use and default to app service as we will for the new UX create experience.

Something like:
az webapp create java -n myjavapp

This should create the rd, asp on linux and use "Java SE" blessed image. We should have also
az webapp create tomcat -n myTomcatApp
az webapp create springboot -n mySpringbootApp
az webapp create wildfly -n myWildFlyApp

Ideally we need an interactive experience in which I simple type:
az webapp create

it should start asking me interactively for sitename, stack and derive the rest from that.

**Comment by panchagnula** [comment]
The interactive approach will be provided by the az interactive module across all of CLI no special interactive support will be added to appservice specifically https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-interactive

**Comment by panchagnula** [comment]
@btardif can we should discuss supporting this with az web app up

**Comment by panchagnula** [comment]
the current plan is to support this with az webapp up

**Comment by seligj95** [comment]
Thank you for the feedback. We will not be creating a dedicated command for this at this time.
