### ISSUE TITLE
az webapp deploy

### ISSUE THREAD

**Issue by jvano** [Azure/azure-cli#8743]
We need a command to deploy:
az webapp deploy --src {FilePathLocation}

The FilePathLocation, should be a local or remote file (http://) 
If extension is .zip -> use /zipdeploy as today
If extension is .war -> use /wardeploy
Else case -> add the file to a zip and use /zipdeploy (this is useful to transfer .jar files or any other file).

Ideally the context should be passed from previous create, so we should not need to type other parameter to explain where are we deploying to

**Comment by panchagnula** [comment]
There is an existing deployment command https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/source?view=azure-cli-latest#az-webapp-deployment-source-config-zip that already does zip deploy the wardeployment support will be added to this. 

the remote file support is tracked here https://github.com/Azure/azure-cli/issues/9291

**Comment by panchagnula** [comment]
@btardif this is request for a command for war deploy

**Comment by panchagnula** [comment]
we will add support for this to the existing deployment command

**Comment by panchagnula** [comment]
@btardif can you let me know when this ready with the new deployment command? so that we add support for JAVA with zip deploy?

**Comment by panchagnula** [comment]
Closing this since the changes are merged.
