### ISSUE TITLE
az ad app create is not idempotent

### ISSUE THREAD

**Issue by anschoewe** [Azure/azure-cli#8750]
There are two scenarios to consider...

- Re-running 'az ad app create' with the '--native-app true' results in multiple applications being created with unique appIds.
- Re-running 'az ad app create' with the '--native-app false', results in this message being returned instead of the expected existing object. Message: Another object with the same value for property identifierUris already exists.

This seems to conflict with the CLI 'create' [guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md#standard-command-types) of being idempotent.

**Comment by anschoewe** [comment]
I also noticed that 'az ad sp create-for-rbac' is not idempotent.  Re-running the command does not return the existing service account but instead just returns: <name> already exists.  I would have expected it to return the existing/matching service principal object.

**Comment by tjprescott** [comment]
@marstr I believe you recently closed a similar issue?

**Comment by yugangw-msft** [comment]
The graph command are probably the only exception.  The backend service doesn't support `PUT` like most other azure services; rather it has "POST" and `PATCH`. This makes idempotent a bit hard
