### ISSUE TITLE
v2.0.59 and v2.0.60 az --version hangs

### ISSUE THREAD

**Issue by agray** [Azure/azure-cli#8762]
**Describe the bug**
With version 2.0.59 or 2.0.60 installed executing az --version from an admin command prompt just hangs.

**To Reproduce**
Install Azure CLI
Open cmd admin prompt
Execute az --version
Hangs!

**Expected behavior**
It shouldn't hang.

**Environment summary**
Windows MSI installer v 2.0.59 or 2.0.60 downloaded from https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest

**Additional context**

**Comment by williexu** [comment]
I was not able to reproduce this on my windows machine- installed using the msi for 2.0.60.

@agray could you try again/give your system info?

**Comment by tjprescott** [comment]
Are you running behind a network proxy?  If you disable your network and try running it again, does it still hang?

**Comment by agray** [comment]
We had to set the HTTP_PROXY and HTTPS_PROXY environment variables.

Then it worked.

**Comment by tjprescott** [comment]
Thanks @agray. If you temporarily turn off your network connection and run `az --version` does it hang or does it say "Unable to determine if your CLI is up-to-date"?

**Comment by agray** [comment]
It takes a VERY long time to eventually say that it can't check CLI update
as you said.

**Comment by tjprescott** [comment]
Thanks @agray this was a concern I had when putting this check in. I'll see what we can do.
