### ISSUE TITLE
Concurrent Azure CLI Usage

### ISSUE THREAD

**Issue by tdillon** [Azure/azure-cli#8766]
**Is your feature request related to a problem? Please describe.**
I'm running Azure CLI to perform deployments on my CI server (Bamboo).  My current steps for a deployment are:

1) `az login ...`
1) `az webapp deployment ...`
1) `az logout`

The Azure CLI commands are not isolated, they are run by the same service account in separate threads.  Therefore, if 2 deployment jobs are running concurrently, they can impact each other.  For example, 1 deployment could finish and logout shortly after another deployment logs in (causing the 2nd deployment to fail when it attempts to deploy).  Another example is if I have 2 deployments that login as 2 different service principles then the last login essentially determines which account is being used.

**Describe the solution you'd like**
I would like to be able to run multiple deployments concurrently without causing side effects between the deployments.  One way for this to be implemented would be to allow login information to be passed to individual CLI commands.  For example:

```shell
az webapp deployment source config-zip
    # Login Credentials
    --service-principal
    --username <...>
    --password <...>
    --tenant <...>
    # Normal deployment parameters
    --src <...>
    --name <...>
    --resource-group <...>
    --subscription <...>
```

**Describe alternatives you've considered**
One alternative I thought was to just not logout.  But this only solves 1 of the potential issues I've mentioned above.

**Additional context**
I believe the current behavior is due to the following 2 files being updated and used by each process that is executing Azure CLI commands for the given user.
- `%USERPROFILE%\.azure\accessTokens.json`
- `%USERPROFILE%\.azure\azureProfile.json`

**Comment by yugangw-msft** [comment]
You can use `AZURE_CONFIG_DIR` env var to have each CLI get its own folder for profile and tokens.
We can update the [CLI doc](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md) to call out this

**Comment by tdillon** [comment]
Thanks @yugangw-msft, that sounds like it should solve my issue.  Let me verify (may take a day or two).

**Comment by tdillon** [comment]
Setting the `AZURE_CONFIG_DIR` env var has solved my issue.  Below are the steps I perform for each deployment.  I now have to execute `az cloud set ...` for each deployment since I cannot use the CLI's global configuration.  For each task I set `AZURE_CONFIG_DIR=.` so the current working directory is used for the CLI's profile and tokens.

1) `az cloud set ...`
1) `az login ...`
1) `az webapp deployment ...`
1) `az logout`
