### ISSUE TITLE
'Cannot decrypt backup blob' on az keyvault secret restore

### ISSUE THREAD

**Issue by blacelle** [Azure/azure-cli#8767]
**Describe the bug**
After a backup with CLI, the CLI failed restoring the entry

**To Reproduce**

    az keyvault secret backup \
   		--vault-name someVaultName \
   		--id $fullKeyVaultEntryId \
   		--file-path "$outputFolder/$keyVaultEntryId.json"

   	az keyvault secret restore \
   		--file-path "$filename" \
   		--vault-name otherVaultName

**Expected behavior**
I would expect the key to be restored. I receive the error: 'Cannot decrypt backup blob'

**Environment summary**
MacOS

**Comment by blacelle** [comment]
It appear it is not possible to use backup/restore to transfer keys to a different KeyVault

**Comment by juescuder** [comment]
Hi there. There is actually a way to do it using Powershell. The only constraint is that you have to backup/restore in the same subscription and region.

```
Function BKPKeyVault ($param_PrimaryKeyVault)
{
If ((Get-AzureRmKeyVault -VaultName $param_PrimaryKeyVault) -ne $null) {
If (test-path C:\AzureKeyVaultSwap\$param_PrimaryKeyVault) {Write-Output "Folder already exists"} Else { New-Item ("C:\AzureKeyVaultSwap\" + $param_PrimaryKeyVault) -ItemType Directory}
cd C:\AzureKeyVaultSwap\$param_PrimaryKeyVault
Get-AzureKeyVaultSecret -VaultName $param_PrimaryKeyVault | % { Backup-AzureKeyVaultSecret -VaultName $_.VaultName -Name $_.Name -OutputFile ($_.Name + ".secret.bkp") -Confirm:$False -Force}
Get-AzureKeyVaultKey -VaultName $param_PrimaryKeyVault | % { Backup-AzureKeyVaultKey -VaultName $_.VaultName -Name $_.Name -OutputFile ($_.Name + ".key.bkp") -Confirm:$False -Force}
}
}

Function DRKeyVault($param_PrimaryKV,$param_SecondaryKV){

Get-AzureKeyVaultSecret -VaultName $param_SecondaryKV | Remove-AzureKeyVaultSecret -confirm:$false -Force
Get-AzureKeyVaultKey -VaultName $param_SecondaryKV | Remove-AzureKeyVaultKey -Confirm:$False -Force
cd C:\AzureKeyVaultSwap\$param_PrimaryKV
$vSecretBKP = Get-Item *.secret.bkp
$vKeyBKP = Get-Item *.key.bkp
If ($vSecretBKP -ne $null) { $vSecretBKP | % { Restore-AzureKeyVaultSecret -VaultName $param_SecondaryKV -InputFile $_.Name } } Else { Write-Output "There are not Secrets to be transferred." }
If ($vKeyBKP -ne $null) { $vKeyBKP | % { Restore-AzureKeyVaultKey -VaultName $param_SecondaryKV -InputFile $_.Name } } Else { Write-Output "There are not Keys to be transferred." }

}

BKPKeyVault "from"
DRKeyVault "from" "to"
```

**Comment by johnsk3131** [comment]
{
  "error": {
    "code": "Malformed backup blob",
    "message": "Cannot decrypt backup blob."
  }
}

**Comment by johnsk3131** [comment]
Backup & Restore Key Vault Secrets via Logic Apps I'm geeting error while restoring from azure storage blob
Error message :
{
"error": {
"code": "Malformed backup blob",
"message": "Cannot decrypt backup blob."
}
}
