### ISSUE TITLE
Compute: Large disk support

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#8774]
**Resource Provider**
What is the Azure resource provider your feature is part of?
  `Compute and Disk resource provider`

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
```
1.	Disks/Snapshots have a new optional property HyperVGeneration which may be set to V1 or V1.
2.	There is a new CreateOption (Upload) for disks. To upload disks customers
        a.	PUT a disk with CreateOption.Upload.
        b.	Use  GrantAccess API with AccessLevel.Write to a get a write SAS to the disk. This is a new access level and it can only be used when uploading to a new disk. Customers can then use storage API to upload the bits for the disk
        c.	There are new DiskStates (DiskState.ReadyToUpload and DiskState.ActiveUpload) that are associated with the upload process.
3.	EncryptionSettings on a disk are now a collection instead of a single value. This allows multiple volumes on an encrypted disk.
```

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
2018-09-30

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. This should be on the master branch of the REST API specs repo.

https://github.com/Azure/azure-rest-api-specs/pull/5232

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.

**Comment by adewaleo** [comment]
Closed through #8876
