### ISSUE TITLE
ARM template parameters of type SecureObject are not recognized

### ISSUE THREAD

**Issue by Choc13** [Azure/azure-cli#8776]
**Describe the bug**
The Az CLI does not appear to support ARM template parameters of type `secureObject`.

**To Reproduce**
Deploying the below template highlights the problem:

```json
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "certificate": {
            "defaultValue": {},
            "type": "secureObject"
        }
    },
    "outputs": {
        "certificate": {
            "type": "object",
            "value": "[parameters('certificate')]"
        }
    }
}
```

Running the following command:
 ```sh
az group deployment validate -g dev-eu-rp --template-file .\template.json --parameters certificate='{}'
``` 

produces the following warning and error:

```
Unrecognized type 'secureobject' for parameter 'certificate'. Interpretting as string.
{
  "error": {
    "code": "InvalidTemplate",
    "details": null,
    "message": "Deployment template validation failed: 'The provided value for the template parameter 'certificate' at line '1' and column '183' is not valid.'.",
    "target": null
  },
  "properties": null
}
```

Obviously interpreting it as a string leads to the error that the provided value is not valid.

However if we change the `certificate` parameter to be of type `object` then the deployment validation is fine.

**Expected behavior**
Parameters of type `secureObject` should be supported and not interpreted as a string. Please could you advise on whether `secureObject` type parameters are supported in the Az CLI when invoked from PowerShell.

**Environment summary**
CLI version: 2.0.60
OS: Windows
Shell Type: PowerShell

**Comment by tjprescott** [comment]
The CLI command recognizes `secureString` but not `secureObject`.

**Comment by Choc13** [comment]
Thanks for clearing that up. I take it from the fact that you’ve opened a PR that you’re going to add support for this? Do you have a rough idea when this will be shipped?

**Comment by tjprescott** [comment]
End of March.
