### ISSUE TITLE
RPM Spec Should be updated to accomodate different distros (incl. RHEL8).

### ISSUE THREAD

**Issue by marstr** [Azure/azure-cli#8780]
[Our RPM Spec is only setup to build using Enterprise Linux 7 repositories](https://github.com/Azure/azure-cli/blob/e5fd28ca284aa2d2b96409555b86bf68ba643258/scripts/release/rpm/azure-cli.spec), and indeed we only publish an `*.el7.x86_64.rpm`.

However, [in our installation instructions](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-yum?view=azure-cli-latest), we callout several RPM based Linux distros that we support. The list that we say we support is:
- RHEL 7
- Fedora 19+
- CentOS 7
- openSUSE 42.2
- SLES 12 SP2

We should decide which of these distros we want to continue supporting, and make sure that our RPM specifies the particular packages that are available in each of those ecosystems. There are some choices that should be easier than others. For instance, only Fedora Core 28 and 29 are supported now, so I believe those are the only Fedora releases we need to bother attempting to support. https://github.com/Azure/azure-cli/issues/7523 is a great example of what happens when we don't cater to each ecosystem.

Another perk of doing this, is that we may be able to continue ratcheting down the number of people installing the CLI who use Python2.

**Comment by marstr** [comment]
In addition, this will help us manage Enterprise Linux 8, and it's new handling of Python.

**Comment by Arnavion** [comment]
@achandmsft @marstr The issue https://github.com/Azure/azure-cli/issues/7523 that was duped against this one still repros with the latest package `azure-cli-2.0.65-1.el7.x86_64.rpm`. Should one of these be reopened?

**Comment by marstr** [comment]
Good call, yes. I'll reopen #7253 for this.
