### ISSUE TITLE
Get recovery vault for VM

### ISSUE THREAD

**Issue by Klaas-** [Azure/azure-cli#8789]
**Resource Provider**
vm

**Description of Feature or Work Requested**
I would like to know if/how it is possible to find out which recovery vault is associated to a VM. I could only figure out the other way around - which VM is associated to a vault. But that means I'd have to cycle through all vaults to find the right one.

External (unanswered) Link https://stackoverflow.com/questions/43105398/using-azure-rm-powershell-how-do-i-find-out-which-recovery-services-vault-vm-is

**Comment by yugangw-msft** [comment]
I don't think it is supprted, but @dragonfly91 can confirm.

**Comment by Klaas-** [comment]
Is it just not in az-cli or is it not possible even through api/whatever?

**Comment by tjprescott** [comment]
If you run `vm show` and it makes no mention of the vault, then it is not supported by the API.

**Comment by Klaas-** [comment]
@tjprescott no mention of it :) Where would I make a feature request against API?

**Comment by tjprescott** [comment]
Hi @Klaas- my suggestion would be to the feedback forums. That is what most of the service teams prefer:
https://feedback.azure.com/forums/216843-virtual-machines

There is a link for Azure Backup as well:
https://feedback.azure.com/forums/258995-azure-backup

I think that to get the relevant vault to appear on VM show, that request would need to go to the VM team.

**Comment by Klaas-** [comment]
Okay, I'll do that; thank you

**Comment by Klaas-** [comment]
https://feedback.azure.com/forums/216843-virtual-machines/suggestions/37151851-api-connection-to-backup
