### ISSUE TITLE
az-cli install on windows 7

### ISSUE THREAD

**Issue by razmohan** [Azure/azure-cli#8790]
i have installed azure-cli 2.0.60 in my Windows 7 machine, but when tried to check the version "az --version" commands returns the message "Access is denied". I am not sure where the problem is. Even pyhton latest version is installed in my machine and also the PATH variables are set properly.

**Comment by williexu** [comment]
@razmohan can you show me the output that you are seeing?

**Comment by tjprescott** [comment]
My guess @williexu is that this isn't an installation problem but is related to the PyPI calls made in `az --version`.  @razmohan can you run other az commands without issue? Can you login and run `az group list` for instance?

**Comment by razmohan** [comment]
@williexu @tjprescott 
/can you show me the output that you are seeing?/
C:\users\razmohan> az --version
Access is denied

/In addition, how are you installing the CLI?/
downloaded the msi and installed, even i tried the pip install through command prompt.

/can you run other az commands without issue?/
its giving the same error message "Access is denied" for all az commands

**Comment by tjprescott** [comment]
Thanks @razmohan. In that case, this doesn't seem related to the network calls in az --version. Instead, it seems like a permissions issue specific to Windows 7.

If you run a command prompt as administrator, do you still get this error?

**Comment by razmohan** [comment]
Hi @tjprescott i have tried running command prompt as administrator but still its giving me the same error message.
![image](https://user-images.githubusercontent.com/48553741/54584826-684fd180-4a3e-11e9-9e0b-717cac8d63ba.png)

**Comment by kristapratico** [comment]
@razmohan could you tell us more about the environment you're running? 
I spun up a Windows 7 VM and downloaded azure-cli 2.0.60, but was unable to reproduce the error.

**Comment by yugangw-msft** [comment]
@razmohan, maybe you can run with "az --version --debug". Likely accessing to the folder of `%USERPROFILE%` is blocked

**Comment by razmohan** [comment]
@kristapratico  @yugangw-msft the issue was with installing the older version of the cli version, when tried with new version 2.0.60 it worked fine for me as well. Thanks for your suggestions.

**Comment by marstr** [comment]
Looks like this is resolved, thanks @razmohan.
