### ISSUE TITLE
az aks create not honoring 'azure' networkPlugin

### ISSUE THREAD

**Issue by MarcosMMartinez** [Azure/azure-cli#8794]
**Describe the bug**
Running az aks create while requesting _azure_ networkPlugin defaults to _kubenet_ plugin when _--docker-bridge-address_, _--dns-service-ip_, and _--service-cidr_ are not specified - the end user is not informed of this default and the custom subnet hosting the agent nodes do not have the route table necessary to allow a kubenet k8s cluster to function properly. The end user is left with networking issues due to this missing route-table. 

**To Reproduce**
**You can run the command below**

marcos@Azure:~$ az aks create -g aks -n aks-cli-missing-fields --admin-user sign --generate-ssh-keys --kubernetes-version 1.11.7 -l eastus --vnet-subnet-id /subscriptions/2727775c7ed3f7f/resourceGroups/aks/providers/Microsoft.Network/virtualNetworks/cli-aks-bugtest/subnets/default --node-vm-size Standard_DS2_v2 --service-principal **<app-id-here>** --client-secret **<secret-here>** --node-count 1 --nodepool-name azclibug1 --network-plugin azure

This will yield a cluster with _kubenet_ plugin instead of _azure cni_ with an un-assigned route-table on the subnet hosting the k8s agents. 

**Running the command below will yield the cluster we expect:**

marcos@Azure:~$ az aks create -g aks -n aks-cli-with-fields --admin-user sign --generate-ssh-keys --kubernetes-version 1.11.7 -l eastus --vnet-subnet-id /subscriptions/27277ed3f7f/resourceGroups/aks/providers/Microsoft.Network/virtualNetworks/cli-aks-bugtest2/subnets/default --node-vm-size Standard_DS2_v2 --service-principal **<app-id-here>** --client-secret **<secret-here>** --node-count 1 --nodepool-name azclibug1 --network-plugin azure **--docker-bridge-address 172.17.0.1/16 --dns-service-ip 10.0.0.10 --service-cidr 10.0.0.0/16** 

**Expected behavior**

If the _docker bridge address_, _dns-service-ip_, and _service-cidr_ are required, then the az cli client should fail at the client with appropriate error message rather than deploying a cluster with the unexpected network plugin. 

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**On CloudShell**
marcos@Azure:~$ az --version
azure-cli                         2.0.60

acr                                2.2.2
acs                               2.3.19
advisor                            2.0.0
ams                                0.4.2
appservice                        0.2.15
backup                             1.2.1
batch                              4.0.0
batchai                            0.4.7
billing                            0.2.0
botservice                         0.1.8
cdn                                0.2.0
cloud                              2.1.0
cognitiveservices                  0.2.4
command-modules-nspkg               2.0.2
configure                         2.0.20
consumption                        0.4.2
container                         0.3.15
core                              2.0.60
cosmosdb                           0.2.8
dla                                0.2.4
dls                                0.1.8
dms                                0.1.2
eventgrid                          0.2.1
eventhubs                          0.3.4
extension                          0.2.3
feedback                           2.1.4
find                               0.3.0
hdinsight                          0.3.2
interactive                        0.4.1
iot                                0.3.6
iotcentral                         0.1.6
keyvault                          2.2.12
kusto                              0.2.0
lab                                0.1.5
maps                               0.3.3
monitor                           0.2.10
network                            2.3.4
nspkg                              3.0.3
policyinsights                     0.1.1
profile                            2.1.3
rdbms                              0.3.8
redis                              0.4.1
relay                              0.1.3
reservations                       0.4.1
resource                          2.1.11
role                               2.4.2
search                             0.1.1
security                           0.1.0
servicebus                         0.3.3
servicefabric                     0.1.14
signalr                            1.0.0
sql                                2.1.9
sqlvm                              0.1.0
storage                            2.3.1
telemetry                          1.0.1
vm                                2.2.16

Python location '/opt/az/bin/python3'
Extensions directory '/home/marcos/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Mar  7 2019, 19:49:28)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Additional context**

**_Here you can confirm the two object models yielded by the two commands:_**

**This demonstrates the bug**
marcos@Azure:~$ az aks create -g aks -n aks-cli-missing-fields --admin-user sign --generate-ssh-keys --kubernetes-version 1.11.7 -l eastus --vnet-subnet-id /subscriptions/2727775c7ed3f7f/resourceGroups/aks/providers/Microsoft.Network/virtualNetworks/cli-aks-bugtest/subnets/default --node-vm-size Standard_DS2_v2 --service-principal **app-id-here** --client-secret **secret-here** --node-count 1 --nodepool-name azclibug1 **--network-plugin azure**
{
  "aadProfile": null,
  "addonProfiles": null,
  "agentPoolProfiles": [
    {
      "count": 1,
      "maxPods": 110,
      "name": "azclibug1",
      "osDiskSizeGb": 30,
      "osType": "Linux",
      "storageProfile": "ManagedDisks",
      "vmSize": "Standard_DS2_v2",
      "vnetSubnetId": "/subscriptions/27277d3f7f/resourceGroups/aks/providers/Microsoft.Network/virtualNetworks/cli-aks-bugtest/subnets/default"
    }
  ],
  "dnsPrefix": "aks-cli-mi-aks-272779",
  "enableRbac": true,
  "fqdn": "aks-cli-mi-aks-272779-b4965529.hcp.eastus.azmk8s.io",
  "id": "/subscriptions/27277913-5d8a-4de5-b626-1975c7ed3f7f/resourcegroups/aks/providers/Microsoft.ContainerService/managedClusters/aks-cli-missing-fields",
  "kubernetesVersion": "1.11.7",
  "linuxProfile": {
    "adminUsername": "sign",
    "ssh": {
      "publicKeys": [
        {
          "keyData": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1O+PjVgL+0w86fQbtkIcEbORR+HMas2weFinrh8AeDz4pT2mZ3KQfP1M83VMkAR6HawFcD0XDjnDxIhZajj8ePL marcos@cc-54406bf2-588f6c49f5-dt5l4\n"
        }
      ]
    }
  },
  "location": "eastus",
  "name": "aks-cli-missing-fields",
  "networkProfile": {
    "dnsServiceIp": "10.0.0.10",
    "dockerBridgeCidr": "172.17.0.1/16",
    **"networkPlugin": "kubenet",**
    "networkPolicy": null,
    "podCidr": "10.244.0.0/16",
    "serviceCidr": "10.0.0.0/16"
  },
  "nodeResourceGroup": "MC_aks_aks-cli-missing-fields_eastus",
  "provisioningState": "Succeeded",
  "resourceGroup": "aks",
  "servicePrincipalProfile": {
    "clientId": "89b578f4053be73",
    "secret": null
  },
  "tags": null,
  "type": "Microsoft.ContainerService/ManagedClusters"
}

**This demonstrates expected behavior**
marcos@Azure:~$ az aks create -g aks -n aks-cli-with-fields --admin-user sign --generate-ssh-keys --kubernetes-version 1.11.7 -l eastus --vnet-subnet-id /subscriptions/27277913-5d8a-4de5-b626-1975c7ed3f7f/resourceGroups/aks/providers/Microsoft.Network/virtualNetworks/cli-aks-bugtest2/subnets/default --node-vm-size Standard_DS2_v2 --service-principal **app-id-here** --client-secret **secret-here** --node-count 1 --nodepool-name azclibug1 --network-plugin azure **--docker-bridge-address 172.17.0.1/16 --dns-service-ip 10.0.0.10 --service-cidr 10.0.0.0/16** 

{
  "aadProfile": null,
  "addonProfiles": null,
  "agentPoolProfiles": [
    {
      "count": 1,
      "maxPods": 30,
      "name": "azclibug1",
      "osDiskSizeGb": 30,
      "osType": "Linux",
      "storageProfile": "ManagedDisks",
      "vmSize": "Standard_DS2_v2",
      "vnetSubnetId": "/subscriptions/27277913-ed3f7f/resourceGroups/aks/providers/Microsoft.Network/virtualNetworks/cli-aks-bugtest2/subnets/default"
    }
  ],
  "dnsPrefix": "aks-cli-wi-aks-272779",
  "enableRbac": true,
  "fqdn": "aks-cli-wi-aks-272779-617caa72.hcp.eastus.azmk8s.io",
  "id": "/subscriptions/27277913-5d8a-4de5-b626-1975c7ed3f7f/resourcegroups/aks/providers/Microsoft.ContainerService/managedClusters/aks-cli-with-fields",
  "kubernetesVersion": "1.11.7",
  "linuxProfile": {
    "adminUsername": "sign",
    "ssh": {
      "publicKeys": [
        {
          "keyData": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1O+PjVgL+0w86fQbtkIcEbORR+HMas2weFinrh8AeDz4pT2mZ3KQfP1MAR6HawFcD0XDjnDxIhZajj8ePL marcos@cc-54406bf2-588f6c49f5-dt5l4\n"
        }
      ]
    }
  },
  **"location": "eastus",
  "name": "aks-cli-with-fields",
  "networkProfile": {
    "dnsServiceIp": "10.0.0.10",
    "dockerBridgeCidr": "172.17.0.1/16",
    "networkPlugin": "azure",
    "networkPolicy": null,
    "podCidr": null,
    "serviceCidr": "10.0.0.0/16"
  },**
  "nodeResourceGroup": "MC_aks_aks-cli-with-fields_eastus",
  "provisioningState": "Succeeded",
  "resourceGroup": "aks",
  "servicePrincipalProfile": {
    "clientId": "89b574053be73",
    "secret": null
  },
  "tags": null,
  "type": "Microsoft.ContainerService/ManagedClusters"
}

**Comment by MarcosMMartinez** [comment]
I forgot to mention - below is the object model being passed to the AKS Resource Provider, so the RP is behaving as expected, by Az Cli is not passing appropriate values.

Note how the network profile is not included and therefore defaults to **kubenet**. 

sanitized request body: {
    "location": "eastus2",
    "properties": {
        "kubernetesVersion": "1.11.7",
        "dnsPrefix": "micro63b",
        "agentPoolProfiles": [{
            "name": "micprova7b",
            "count": 5,
            "vmSize": "Standard_F16s_v2",
            "storageProfile": "",
            "vnetSubnetID": "/subscriptions/21963bbe0be547c4/resourceGroups/microservicesprod-va7-base-rg/providers/Microsoft.Network/virtualNetworks/microservices-prod-va7/subnets/microservices-prod-va7-MasterB-subnet",
            "osType": "Linux"
        }],
        "linuxProfile": {
            "adminUsername": "sign",
            "ssh": {
                "publicKeys": [{
                    "keyData": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9ICQdUNw+2Aroz9WemlrUc+qCRRCfR2JncqeubPY6TkhUsPv4BLBi1rTeMpEcZysEMiozGcae8C2WOmKbtZn5n"
                }]
            }
        },
        "servicePrincipalProfile": {
            "clientId": "62927cd71df",
            "secret": "REDACTED"
        },
        "enableRBAC": true
    }
}

**Comment by snobu** [comment]
I've hit this one too. Glad the root cause is already known. Temporary workaround - pass an ARM template to `az` instead. Not ideal but should get you through these tough times :)

**Comment by MarcosMMartinez** [comment]
This has been resolved now.
