### ISSUE TITLE
az vm create should allow images to exist in other resource groups

### ISSUE THREAD

**Issue by emcconne** [Azure/azure-cli#8803]
I am frustrated because the cli doesn't allow me to create a vm from an image in another resource group.  I am able to create an image in a resource group that is different from the source VM but when I try to use the image I have to either use ARM templates or the UI.  Neither powershell or the Azure CLI supports an option to use an image in another resource group.

**Comment by tjprescott** [comment]
Did you try using `--image ID` where ID is the ARM ID to the image in a different resource group?

**Comment by tjprescott** [comment]
```
   --image                        : The name of the operating system image as a URN alias, URN,
                                     custom image name or ID, or VHD blob URI. This parameter is
                                     required unless using `--attach-os-disk.` Valid URN format:
                                     "Publisher:Offer:Sku:Version".  Values from: az vm image list,
                                     az vm image show.
```

If the above doesn't work, that would be a bug.

**Comment by yugangw-msft** [comment]
This definitely works and I have verified, please use command with such arguments, e.g.
```
az vm create -g mygroup1 -n vm1 --image /subscriptions/0b1f6471-1bf0-4dda-aec3-cb92712345678/resourceGroups/group2/providers/Microsoft.Compute/images/my-image
```

**Comment by robert-baboi-playtech** [comment]
Hello

This does not work for me.
I have tried 
```
az vm create -n vm-test -g rg-test --image /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/vm-templates/providers/Microsoft.Compute/images/yy-zz-mysql5.7-image
```

And I get back
```
ERROR: ValidationError: (ResourceNotFound) The Resource 'Microsoft.Compute/images/C:' under resource group 'rg-bbprod08' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
```

Are there some restrictions on the name of the image?

It works if I do it from the UI, but the cli fails

Any tips?

**Comment by yonzhan** [comment]
@qwordy for awareness

**Comment by qwordy** [comment]
I don't believe. It is a basic usage.
@robert-baboi-playtech I suspect you don't have access to the image or the image is deleted. Can you try `az image show`?

**Comment by robert-baboi-playtech** [comment]
hey, so I tried that command (with the name of the image and rg) and it works

I'm using
```
azure-cli                         2.18.0

core                              2.18.0
telemetry                          1.0.6

Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]
```

**Comment by robert-baboi-playtech** [comment]
I found the problem, I was running that command from git bash under Windows, so I tried it from under Ubuntu, and that worked.

So it's either gitbash or Windows that has a issue.

**Comment by qwordy** [comment]
@robert-baboi-playtech Don't use Azure CLI in git bash. Git bash replaces `/` to `C:/`.

**Comment by emp00001** [comment]
hello,

I am getting the same problem, but I am running it from devops, does anybody know the work around ?

**Comment by cameron-doherty** [comment]
I was brought here as I had the same problem when attempting to create a VMSS but what ended up working for me is removing the versions portion of the ID (I just cut/pasted from the gallery properties for the image def).

Not working...

`az vmss create -n myVmss -g rg-vmss --image /subscriptions/[...]/resourceGroups/rg-custom-image/providers/Microsoft.Compute/galleries/gallery.myGallery/images/Ubuntu_20.04_LTS/versions/1.1.0`

Working...

`az vmss create -n myVmss -g rg-vmss --image /subscriptions/[...]/resourceGroups/rg-custom-image/providers/Microsoft.Compute/galleries/gallery.myGallery/images/Ubuntu_20.04_LTS`
