### ISSUE TITLE
Am subscription owner but getting Insufficient privileges to complete the operation.

### ISSUE THREAD

**Issue by justSteve** [Azure/azure-cli#8805]
I created a keyvault with: az keyvault create   --name "foo"   --resource-group fooresgroup   --location "North Central US"   --enabled-for-template-deployment true

That worked and I eyes on the KV in the portal. Next I issued: az keyvault set-policy --upn email@subOwner.com --name foo --secret-permissions set delete get list

and got Insufficient privileges to complete the operation.

What next? thx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 226e5769-f6c8-a480-db78-727fb96348ec
* Version Independent ID: 8ee06a2a-6eda-11be-3c8e-6ad948be207e
* Content: [az keyvault](https://docs.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
@justSteve, what kind of accounts you authenticated through CLI? A user account or a service principal account?

**Comment by yonzhan** [comment]
add to S164.

**Comment by bim-msft** [comment]
@justSteve Hi, I have reproduced your scenario. If you are a guest of this group, your upn looks like `aaa_bbb.com#EXT#@ccc.ddd.com` .
To find out your upn, please use the command `az ad user list --display-name "Your Name"`.
Any questions, please feel free to leave a comment here.

**Comment by bim-msft** [comment]
@justSteve Hi, has your problem been resolved?

**Comment by bim-msft** [comment]
Closing this due to long time no response, you can kindly reopen the issue if there are any updates.
