### ISSUE TITLE
Typo in json returned by `az security task list` 

### ISSUE THREAD

**Issue by docunid** [Azure/azure-cli#8807]
"securityTaskParameters": {
   "name": "GenericSecuirtyTask",

Security?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b05427b-880b-682d-86aa-b76e563962b5
* Version Independent ID: 15136c2b-d558-2d62-f077-a3d388341b34
* Content: [az security task](https://docs.microsoft.com/en-us/cli/azure/security/task?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-security/azure/cli/command_modules/security/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-security/azure/cli/command_modules/security/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by omerchechik** [comment]
Thank you for pointing this typo out. The API for tasks is pending deprecation.
Please use assessment api instread (https://docs.microsoft.com/en-us/rest/api/securitycenter/assessments/get)
