### ISSUE TITLE
--slot not acknowledged on 'az webapp config container set' command

### ISSUE THREAD

**Issue by BenWalters** [Azure/azure-cli#8808]
When using 'az webapp config container set' the --slot parameter is ignored and changes are submitted directly to the production slot!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acac0890-ff1e-ef72-7715-94988b818426
* Version Independent ID: 7db8a57d-4b68-aa5c-8d7f-52251403f797
* Content: [az webapp config container](https://docs.microsoft.com/en-us/cli/azure/webapp/config/container?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/webapp/config/container.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config/container.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by panchagnula** [comment]
@Nking92 can you take a look at this.

**Comment by Nking92** [comment]
@BenWalters I wasn't able to repro, can you give a specific example?

I tried this, which worked as intended:
az webapp config container set -g web -n nkcontainer -s staging -c couchbase

**Comment by BenWalters** [comment]
@Nking92 See below the command I ran when I incurred the problem (info sanitised):

az webapp config container set --resource-group test-rg --name appname --slot qa -o json --multicontainer-config-type COMPOSE --multicontainer-config-file "C:\Users\ben\ssh.yml"

Let me know if you are able to reproduce it with this.

**Comment by BenWalters** [comment]
@Nking92 I've emailed you directly the CLI commands showing that the set command changes Prod and not the slot. I set up a test WebApp so not to cause problems to our Prod environment.

**Comment by BenWalters** [comment]
@Nking92 I just realised that I might have been running an old version of the CLI, I was running 2.0.52, I upgraded to 2.0.60 and it seems work okay now!
