### ISSUE TITLE
Cosmos DB - Cannot set an offer throughput on an existing container that uses the database shared throughput

### ISSUE THREAD

**Issue by ajk2018** [Azure/azure-cli#8811]
If a container has not had it's throughput set before (i.e. we are using the DB shared throughput), and you try to call `az cosmosdb collection update`  to set a throughput on that container. The method will fail with the following error:

`Cannot find offer for collection X`

This looks like it was possible using the older .NET SDK per this example: https://github.com/markjbrown/cosmosdb-offers/blob/master/ChangeOfferNetCore/Program.cs

If we should be using a different method to set a throughput on an existing container for this case, please let me know.

Thanks

**Comment by ajk2018** [comment]
I just verified that the example provided does not work.  There is an error since the query for an offer returns null.  The question is, can we only set throughput on a container at creation?  There seems to be some confusion on this.

**Comment by ajk2018** [comment]
We also have this ticket open with the SDK team.  https://github.com/Azure/azure-cosmos-dotnet-v3/issues/82

**Comment by shurd** [comment]
Hi @ajk2018, I am looking into your question. I will post an update when I find out more.

**Comment by shurd** [comment]
Currently, with the database shared throughput model, you cannot switch between throughput provisioned at a database level or at a collection level. You can only select shared throughput or collection level the first time you provision either.

If you want to be able to update throughput at a collection level, you will need to specify dedicated throughput for that collection when it is provisioned under the database with shared throughput enabled.
