### ISSUE TITLE
Improve Error message for Incorrect folder paths for ACR build

### ISSUE THREAD

**Issue by sajayantony** [Azure/azure-cli#8815]
**Describe the bug**
Run acr build with an incorrect relative folder path as shown below. 

`az acr build -t app:latest ./non-existant-path`

**Expectation** 
Output a message describing that the folder/path is not valid or folder not found etc. 

**Actual Output** 
The command exits with a failure. 
`'./../aap' is not a valid remote URL for git or tarball.`

```
azure-cli (2.0.55)

acr (2.1.12)
acs (2.3.14)
advisor (2.0.0)
ams (0.3.2)
appservice (0.2.11)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.6)
billing (0.2.0)
botservice (0.1.4)
cdn (0.2.0)
cloud (2.1.0)
cognitiveservices (0.2.4)
command-modules-nspkg (2.0.2)
configure (2.0.20)
consumption (0.4.2)
container (0.3.11)
core (2.0.55)
cosmosdb (0.2.7)
dla (0.2.3)
dls (0.1.7)
dms (0.1.1)
eventgrid (0.2.0)
eventhubs (0.3.2)
extension (0.2.3)
feedback (2.1.4)
find (0.2.13)
hdinsight (0.2.0)
interactive (0.4.1)
iot (0.3.4)
iotcentral (0.1.5)
keyvault (2.2.9)
lab (0.1.5)
maps (0.3.3)
monitor (0.2.8)
network (2.3.0)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.2)
rdbms (0.3.5)
redis (0.3.2)
relay (0.1.2)
reservations (0.4.1)
resource (2.1.8)
role (2.3.0)
search (0.1.1)
security (0.1.0)
servicebus (0.3.2)
servicefabric (0.1.11)
signalr (1.0.0)
sql (2.1.7)
storage (2.3.0)
telemetry (1.0.0)
vm (2.2.12)

Python location '/usr/local/opt/python/bin/python3.7'
Extensions directory '/Users/sajay/.azure/cliextensions'

Python (Darwin) 3.7.2 (default, Mar  6 2019, 00:02:28) 
[Clang 10.0.0 (clang-1000.11.45.5)]
```

/cc @northtyphoon

**Comment by NatalieYuGong** [comment]
For now, `acr build` assumes all inexistent local source code directories are potential remote URLs. The issue wants to report a clear message for invalid local directory, nonexistent local directory, invalid remote URL and nonexistent remote URL. 

@SteveLasker What are the customer-friendly message to display?

1. There is a problem with source location. Please check and retry later.

2. Sick source location. Please check and retry.

3. ?

**Comment by sajayantony** [comment]
Are there other messages in the CLI aligning with path not found?
