### ISSUE TITLE
Unable to update Kafka on existing Namespace

### ISSUE THREAD

**Issue by dipesharora** [Azure/azure-cli#8818]
I followed the instructions on az eventhubs namespace update section and set --enable-kafka true for an existing namespace and it failes with error "BadRequest - Updating the KafkaEnabled property on a namespace is not supported. CorrelationId: ccd5aff6-4ce8-49d3-b590-75fa194542c1"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2a1ce05-6574-eaa1-cde9-640de52af451
* Version Independent ID: 4dc152fd-ca4f-6dca-9f63-b1ca2f90e2e9
* Content: [az eventhubs namespace](https://docs.microsoft.com/en-us/cli/azure/eventhubs/namespace?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/_help.py)
* Service: **event-hubs**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jfggdl** [comment]
Currently enabling Kafka support after the namespace has been created is not supported. We will take this a new feature request and will communicate when will be released.

**Comment by jfggdl** [comment]
@dipesharora, Thanks for suggesting this new feature. Again, we acknowledge this feature and will consider adding that capability in a future release. 
I am closing this issue as we have a record of your request. That said, please free to reopen it if you have additional questions.

Thanks.

**Comment by mapdegree** [comment]
Please reopen as this is still not working and functionality not introduced.

We need to add firewall rules via a JSON template and it failed with the exact same error:

"Updating the KafkaEnabled property on a namespace is not supported"

We are deploying this through Terraform and Azure provider.

Regards,
D


`* azurerm_template_deployment.event_hub_kafka_enabled_firewallrule: Error waiting for deployment: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details." Details=[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"message\": \"Updating the KafkaEnabled property on a namespace is not supported. CorrelationId: ****\",\r\n    \"code\": \"BadRequest\"\r\n  }\r\n}"}]`
