### ISSUE TITLE
az webapp create fails when the app plan is not in same resource group

### ISSUE THREAD

**Issue by exuviae** [Azure/azure-cli#8822]
when you attempt to create a web app using:

az webapp create -n $AppName --resource-group $ResourceGroupName --plan $AppPlanName

fails to find the app plan if the app is being created in a different resource group then the one the plan exist in.  

The portal allows you do to this.  You can get around it with a resource move, but the move call takes much longer then the app creation.

**Comment by tjprescott** [comment]
```
Command
    az webapp create : Create a web app.
        The web app's name must be able to produce a unique FQDN as AppName.azurewebsites.net.

Arguments
    --name -n                 [Required] : Name of the new web app.
    --plan -p                 [Required] : Name or resource id of the app service plan. Use
                                           'appservice plan create' to get one.
```

To use a plan in a different resource group, you must supply the ARM ID.
