### ISSUE TITLE
Need clarity on `--docker-bridge-address` option of `aks create` command

### ISSUE THREAD

**Issue by lefrog** [Azure/azure-cli#8830]
I'm really not clear on what this flag does. I guess what I'm trying to understand is;
1. how will this impact the network layout/configuration?
2. what part of the system will care about that value (Kubernetes, AKS, thing outside of the cluster)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-wait)
* Content Source: [src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by rigerosa** [comment]
It's not even clear if it has to be a /16 range, and if you can reuse the same range for two AKS clusters in two Vnet that are peered

**Comment by palma21** [comment]
https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni#deployment-parameters has the docker bridge explanation.
