### ISSUE TITLE
Documentation on az webapp deployment command

### ISSUE THREAD

**Issue by lakshmanav** [Azure/azure-cli#8837]
We receive a response from az webapp deployment command. Do we have a documentation on what the "status", "active" mean ? Would be great to have a documentation on the response from the command

{
"active": true,
"author": "N/A",
"author_email": "N/A",
"complete": true,
"deployer": "Push-Deployer",
"end_time": "time",
"id": "id",
"is_readonly": true,
"is_temp": false,
"last_success_end_time": "time",
"log_url": "https://site/log",
"message": "Created via a push deployment",
"progress": "",
"provisioningState": null,
"received_time": "time",
"site_name": "site",
"start_time": "time",
"status": 4,
"status_text": "",
"url": "https://url"
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b238907f-0676-8e20-66ac-89a542aa8c20
* Version Independent ID: 60659c33-bfea-eecb-6681-9240191820be
* Content: [az webapp deployment source](https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/source?view=azure-cli-latest#az-webapp-deployment-source-config-zip)
* Content Source: [latest/docs-ref-autogen/webapp/deployment/source.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/deployment/source.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
You would need to consult the service API documentation. 
https://docs.microsoft.com/en-us/rest/api/appservice/webapps/createinstancemsdeployoperation
