### ISSUE TITLE
is there a way to enable waf rules with the az command?

### ISSUE THREAD

**Issue by bvx5009** [Azure/azure-cli#8841]
i see that there is a parameter to disable specific rules, is there anyway to enable them through an az command? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68725488-1e3a-ac2d-c454-bcedd26e4b70
* Version Independent ID: 706d7f46-f132-10ab-423c-4a640d65d2dc
* Content: [az network application-gateway waf-config](https://docs.microsoft.com/en-us/cli/azure/network/application-gateway/waf-config?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Anything not disabled is enabled, so you would basically re-run the command without those disabled rules.
