### ISSUE TITLE
Need clarity on --workspace-resource-id option

### ISSUE THREAD

**Issue by squasta** [Azure/azure-cli#8849]
I spend a lot of time and try many thing to activate monitoring on a log analytics workspace with the option --workspace-resource-id and i still don't know what the value should be like. I found here (https://docs.microsoft.com/en-us/azure/azure-monitor/insights/media/container-insights-optout/container-properties-page.png) an example of log analytic workspace id but this format doesn't fit with what the az command option --workspace-resource-id wants. Could your provide an example is the documentation ? thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-create)
* Content Source: [src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by Gordonby** [comment]
The value should be;
"/subscriptions/<subscription-id>/resourcegroups/<resource-group>/providers/microsoft.operationalinsights/workspaces/<workspace-name>"

**Comment by jluk** [comment]
This discussion is being discussed on #6949 I am going to close this in favor of that since we have a proposal to clarify what ID should be passed in. There are more examples on that issue as well about the proper formatting. Thanks for the report!
