### ISSUE TITLE
az vm: 'list-ip-addresses' is not in the 'az vm'

### ISSUE THREAD

**Issue by szaher** [Azure/azure-cli#8850]
**Describe the bug**
While executing az vm list-ip-addresses from a bash script I got the following error
az vm: 'list-ip-addresses' is not in the 'az vm' command group. See 'az vm --help'.

**To Reproduce**
my bash script
`#!/bin/bash

RG=$1
SUBSCRIPTION=$2
DEPLOYMENT_NAME="TESTVM"
OUTPUT="$(az group deployment  show  --name $DEPLOYMENT_NAME -g $RG --subscription $SUBSCRIPTION --query 'properties.outputs.vm.value')"
echo "Instance Name: $OUTPUT"
VMIP="$(az --debug vm list-ip-addresses --name $OUTPUT --subscription $SUBSCRIPTION --query '[].virtualMachine[].network.publicIpAddresses[].ipAddress' -o tsv)"
echo "VMIP IS $VMIP"
`

**Expected behavior**
Return the VM IP

**Environment summary**
sudo apt-get install azure-cli
Ubuntu 18.04 LTS

**Additional context**
Debug Output
./saad.sh TEST-RG2 152138b6-b232-68fb-b3df40-dfsde8w

Instance Name: "TEST-VM-42cyjrsdiu3nc"
Command arguments: ['--debug', 'vm', 'list-ip-addresses', '--name', '"TEST-VM-42cyjrsdiu3nc"', '--subscription', '152138b6-b232-68fb-b3df40-dfsde8w', '--query', '[].virtualMachine[].network.publicIpAddresses[].ipAddress', '-o', 'tsv']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f796b72fd90>, <function OutputProducer.on_global_arguments at 0x7f796b6f9488>, <function CLIQuery.on_global_arguments at 0x7f796b71bea0>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'maps', 'monitor', 'network', 'policyinsights', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
Loaded module 'acr' in 0.005 seconds.
Loaded module 'acs' in 0.003 seconds.
Loaded module 'advisor' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.014 seconds.
Loaded module 'appservice' in 0.008 seconds.
Loaded module 'backup' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.009 seconds.
Loaded module 'batchai' in 0.003 seconds.
Loaded module 'billing' in 0.001 seconds.
Loaded module 'botservice' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.002 seconds.
Loaded module 'cloud' in 0.001 seconds.
Loaded module 'cognitiveservices' in 0.001 seconds.
Loaded module 'configure' in 0.001 seconds.
Loaded module 'consumption' in 0.002 seconds.
Loaded module 'container' in 0.002 seconds.
Loaded module 'cosmosdb' in 0.005 seconds.
Loaded module 'dla' in 0.005 seconds.
Loaded module 'dls' in 0.003 seconds.
Loaded module 'dms' in 0.002 seconds.
Loaded module 'eventgrid' in 0.002 seconds.
Loaded module 'eventhubs' in 0.003 seconds.
Loaded module 'extension' in 0.002 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.001 seconds.
Loaded module 'hdinsight' in 0.002 seconds.
Loaded module 'interactive' in 0.000 seconds.
Loaded module 'iot' in 0.004 seconds.
Loaded module 'iotcentral' in 0.001 seconds.
Loaded module 'keyvault' in 0.006 seconds.
Loaded module 'kusto' in 0.002 seconds.
Loaded module 'lab' in 0.003 seconds.
Loaded module 'maps' in 0.001 seconds.
Loaded module 'monitor' in 0.005 seconds.
Loaded module 'network' in 0.030 seconds.
Loaded module 'policyinsights' in 0.002 seconds.
Loaded module 'profile' in 0.001 seconds.
Loaded module 'rdbms' in 0.006 seconds.
Loaded module 'redis' in 0.002 seconds.
Loaded module 'relay' in 0.003 seconds.
Loaded module 'reservations' in 0.002 seconds.
Loaded module 'resource' in 0.008 seconds.
Loaded module 'role' in 0.005 seconds.
Loaded module 'search' in 0.002 seconds.
Loaded module 'security' in 0.002 seconds.
Loaded module 'servicebus' in 0.004 seconds.
Loaded module 'servicefabric' in 0.002 seconds.
Loaded module 'signalr' in 0.001 seconds.
Loaded module 'sql' in 0.007 seconds.
Loaded module 'sqlvm' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.033 seconds.
Loaded module 'vm' in 0.014 seconds.
Loaded all modules in 0.235 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: '/home/saad/.azure/cliextensions'
Event: CommandInvoker.OnPreCommandTableTruncate []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f796b42f048>, <function register_ids_argument.<locals>.add_ids_arguments at 0x7f796b45b9d8>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7f79690caea0>]
az vm: 'list-ip-addresses' is not in the 'az vm' command group. See 'az vm --help'.
telemetry.save : Save telemetry record of length 2593 in cache
telemetry.check : Negative: The /home/saad/.azure/telemetry.txt was modified at 2019-03-22 16:24:27.548810, which in less than 600.000000 s
VMIP IS

Client Version
az --version
azure-cli                         2.0.60

acr                                2.2.2
acs                               2.3.19
advisor                            2.0.0
ams                                0.4.2
appservice                        0.2.15
backup                             1.2.1
batch                              4.0.0
batchai                            0.4.7
billing                            0.2.0
botservice                         0.1.8
cdn                                0.2.0
cloud                              2.1.0
cognitiveservices                  0.2.4
command-modules-nspkg               2.0.2
configure                         2.0.20
consumption                        0.4.2
container                         0.3.15
core                              2.0.60
cosmosdb                           0.2.8
dla                                0.2.4
dls                                0.1.8
dms                                0.1.2
eventgrid                          0.2.1
eventhubs                          0.3.4
extension                          0.2.3
feedback                           2.1.4
find                               0.3.0
hdinsight                          0.3.2
interactive                        0.4.1
iot                                0.3.6
iotcentral                         0.1.6
keyvault                          2.2.12
kusto                              0.2.0
lab                                0.1.5
maps                               0.3.3
monitor                           0.2.10
network                            2.3.4
nspkg                              3.0.3
policyinsights                     0.1.1
profile                            2.1.3
rdbms                              0.3.8
redis                              0.4.1
relay                              0.1.3
reservations                       0.4.1
resource                          2.1.11
role                               2.4.2
search                             0.1.1
security                           0.1.0
servicebus                         0.3.3
servicefabric                     0.1.14
signalr                            1.0.0
sql                                2.1.9
sqlvm                              0.1.0
storage                            2.3.1
telemetry                          1.0.1
vm                                2.2.16

Python location '/opt/az/bin/python3'
Extensions directory '/home/saad/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Mar  7 2019, 19:46:51) 
[GCC 7.3.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by szaher** [comment]
Also from CLI 
**az vm list-ip-addresses --name $NAME --subscription $SUBSCRIPTION** Working fine!!
az --debug vm list-ip-addresses --name $NAME --subscription $SUBSCRIPTION  gives error !!

**Comment by tjprescott** [comment]
The command name is: `az vm list-ip-addresses`.  Everything to the right of that are options or positional arguments. You cannot splice an option into the middle of a command name. If you simply move --debug to anywhere after `list-ip-addresses` your command will work fine.
