### ISSUE TITLE
cannot create QnA using powershell

### ISSUE THREAD

**Issue by PrajithB** [Azure/azure-cli#8854]
I'm trying to create QnA using powershell command - New-AzCognitiveServicesAccount, but I get the error shown below. I'm not sure to which parameter the runtimeendpoint needs to passed. Guess it also needs search instance, appservice, appserviceplan and web app bot to be created. Not really sure how these parameters can be passed to PS command. Using JSON it works fine. I do have same issue in creating web app bot using New-AzResource command, wherein cannot figure out how to pass the appID of the web app bot. Not sure, if these can be done using powershell. Please help if there's a way.

command --- New-AzCognitiveServicesAccount -ResourceGroupName XXXXXXX -Name XXXXXQNA001 -Type qNaMaker -Location 'West US' -SkuName S0 -Force
Error ---- New-AzCognitiveServicesAccount : The given 'apiProperties' '{}' is invalid. Validation errors: Required properties are missing from object:  qnaRuntimeEndpoint. Path

**Comment by tjprescott** [comment]
You would need to file your issue here: https://github.com/Azure/azure-powershell

This repo is for Azure CLI.
