### ISSUE TITLE
 WARNING: Role "id" is missing. Look for the role in the current subscription...

### ISSUE THREAD

**Issue by way2arun** [Azure/azure-cli#8856]
az cli version - 2.0.60, getting the error while trying to update 
 WARNING: Role "id" is missing. Look for the role in the current subscription..., updated the feedback in 
https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40e649cf-40e3-1b9e-141a-c62d244eda61
* Version Independent ID: 78ea89c1-7c56-e33b-d10a-dae05642aa34
* Content: [az role definition](https://docs.microsoft.com/en-us/cli/azure/role/definition?view=azure-cli-latest#az-role-definition-update)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
@way2arun, when you invoke `az role definition update`, `id` is expected. You can use the output of the `create` or `show` commands
