### ISSUE TITLE
Public IP create no longer returns the domain name

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#886]
Previously, the following command `az network public-ip create -g myrg -n myname --dns-name mydnsname --allocation-method static` would return the doman name label in publicIp.dnsSettings.domainNameLabel.

After the update of API version for network to 2016-06-01 (SDK rc6), this is no longer the case.

**Comment by mayurid** [comment]
Assigning to Sprint 3 for @BurtBiel to take a look.
