### ISSUE TITLE
Need clarity on --generate-ssh-keys

### ISSUE THREAD

**Issue by gaziqbal** [Azure/azure-cli#8861]
Why would one choose to specify or not specify this option? Which ssh keys are these and why would they be missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?toc=%2Fen-us%2Fazure%2Faks%2FTOC.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json&view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
this [doc](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/ssh-from-windows) has the description for ssh.
CLI by defaults looks for  key files under `~/.ssh`. If the key is unavailable, creating linux VM will fail, then you can use `--generate-ssh-keys` to have CLI generate one for you. This flag will do nothing if the key file exists, so using it all the time is safe

**Comment by gaziqbal** [comment]
Can we add this link to the "--generate-ssh-keys" section on this page to help in discoverability?

**Comment by adewaleo** [comment]
@yugangw-msft I think they are referring to aks' --generate--ssh-keys parameter / help. I mis-labeled this issue. 

@gaziqbal,  Still I tested this and the behavior is the same, the command checks your .ssh folder for an ssh key-pair, if it is not found, you need to supply `--generate-ssh-keys` for an ssh key-pair to be generated.

@gaziqbal, the link is about general ssh key concepts and not relevant to the command or parameter itself.  Moreover, there are about 2 or 3 other commands that use ssh key pairs. There is an expectation that users of these commands are familiar with ssh keys. I can however update the --generate-ssh-keys text to add some more clarification about its behavior
