### ISSUE TITLE
List the current OS users of Linux VM

### ISSUE THREAD

**Issue by shehzadshaikh** [Azure/azure-cli#8868]
Hi,

I want to add the multiple users on my Linux VM on Azure cloud, i could find the instruction on https://docs.microsoft.com/en-us/cli/azure/vm/user?view=azure-cli-latest, however strangely enough there's no such command to list the current OS users.

My requirement is to create and delete users, hence, i would like to pull the list of existing OS users and then perform some comparison before deleting or updating them.

Any help in this regard would be highly appreciated.

Thanks,

**Comment by tjprescott** [comment]
I don't believe this information is returned by the service, but I'll defer to @adewaleo for further clarification.

**Comment by yugangw-msft** [comment]
There is no Azure API to give you the list, rather you have to do it through linux commands executed in the VM. For scripting, you can consider ` ssh yugangw2@13.91.133.10 'cat /etc/passwd'`

**Comment by yugangw-msft** [comment]
Closing as this is a by-design

**Comment by adewaleo** [comment]
Thanks @yugangw-msft @tjprescott . I was going to look into this, which was why I hadn't responded
