### ISSUE TITLE
[Output] YAML output format

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli#887]
Consider having a YAML output format.

**Comment by BurtBiel** [comment]
JSON is YAML, what additional YAML features could we use?

**Comment by derekbekoe** [comment]
YAML may be cleaner to read as it doesn't contain all the curly braces.

It came up during a review but I added the Discussion label so we can discuss.

**Comment by BurtBiel** [comment]
Sounds good.  Are there tools such as jq and jpterm that users can use with yaml output?

**Comment by derekbekoe** [comment]
There is https://pypi.python.org/pypi/yq/0.0.2

**Comment by johanste** [comment]
…but since I’d assume that we are not intending to remove json output support, I would hypothesize that most users would be better off using jq directly… and if you want to convert the json to yaml, you can use something like json2yaml [https://www.npmjs.com/package/json2yaml]

**Comment by mayurid** [comment]
No the intention is not to replace the json or jsonc format with yaml. It was brought up that yaml will be another interesting format for us to support. This is a item i would defer to see some if we have some customer feedback around it (hence the backlog) @jasonrshaver to look for customer input here.

**Comment by mayurid** [comment]
closing for now due to lack of customer asks.
