### ISSUE TITLE
Provide sample to show how to use --cluster-configurations

### ISSUE THREAD

**Issue by emirhosseini** [Azure/azure-cli#8873]
There's no documentation here or anywhere else that I can find to show how to use --cluster-configurations to provide additional information such as the hardware profile of the various components for a Kafka cluster. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b788579d-d73c-df07-abfe-1ab149da330a
* Version Independent ID: 057f1657-8841-39ce-38d0-29f154c0163e
* Content: [az hdinsight](https://docs.microsoft.com/en-us/cli/azure/hdinsight?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-hdinsight/azure/cli/command_modules/hdinsight/_help.py)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tylerfox** [comment]
The --cluster-configurations parameter should be the contents of the 'configurations' object in JSON. For example:
`--cluster-configurations '{ "hive-site": { "hive.metastore.client.connect.retry.delay": "5", "hive.execution.engine": "mr", "hive.security.authorization.manager": "org.apache.hadoop.hive.ql.security.authorization.DefaultHiveAuthorizationProvider" }}'`

[Learn more about configurations here.](https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-hadoop-customize-cluster-bootstrap#use-resource-manager-template)
