### ISSUE TITLE
HP labtop

### ISSUE THREAD

**Issue by fran38** [Azure/azure-cli#8877]
Labtop stopped working again.
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f747ed8-c379-a8c4-731f-a77ee3e47c89
* Version Independent ID: 2e29e92b-89d5-aeae-c447-9cfd79d69fc7
* Content: [az backup recoverypoint](https://docs.microsoft.com/en-ca/cli/azure/backup/recoverypoint?view=azure-cli-latest#az-backup-recoverypoint-list)
* Content Source: [src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-backup/azure/cli/command_modules/backup/_help.py)
* Service: **backup**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
There is insufficient information for us to do anything with this.
