### ISSUE TITLE
how do you set connection strings? There is no az functionapp config connection-string.

### ISSUE THREAD

**Issue by VictorioBerra** [Azure/azure-cli#8882]
**Is your feature request related to a problem? Please describe.**
Just like https://docs.microsoft.com/en-us/cli/azure/webapp/config/connection-string?view=azure-cli-latest#az-webapp-config-connection-string-set

**Describe the solution you'd like**
Exactly like `az webapp config connection-string *`

![image](https://user-images.githubusercontent.com/2934507/55031763-4e356680-4fdd-11e9-857e-3f9265739e35.png)

**Comment by TomChantler** [comment]
Have you tried running the webapp config command against your functionapp?

I just created a new Azure Function App (consumption model) and ran this:
```
az webapp config connection-string set -g resource-group-name -n functionapp-name -t SQLServer -s slot-name --settings SqlConnectionString='Data Source=...'
```

And got this output:
```
{
  "SqlConnectionString": {
    "type": "SQLServer",
    "value": "Data Source=..."
  }
}
```

And when I checked through the Azure Portal, it had configured my Connection Strings section correctly.

**Comment by VictorioBerra** [comment]
@TomChantler Thats a great idea, I am hosting in an App Service Plan as well which im not sure if that makes a difference or not. For now, I will probably keep my conn str in app settings but ill bookmark this for next time.
