### ISSUE TITLE
az webapp webjob continuous start/stop not working

### ISSUE THREAD

**Issue by johnpaultthomas** [Azure/azure-cli#8884]
**Describe the bug**
Azure cli webjob start and stop simply not working.While running with --debug option we noticed that there is ''' No route registered for '/api/continuouswebjobs/<webappname>/<webjobname>?api-version=2018-02-01'''

**To Reproduce**
Login to azure cloud shell 
run the command 
'''az webapp webjob continuous stop --webjob-name <webappname/webjobname> --name "<webappname>" --resource-group <resourcegroupname> --debug'''

'''az webapp webjob continuous start --webjob-name <webappname/webjobname> --name "<webappname>" --resource-group <resourcegroupname> --debug'''

**Expected behavior**
Supposed to stop and start a web job

**Environment summary**
Azure cloud shell(powershell) 

**Additional context**

**Comment by panchagnula** [comment]
@johnpaultthomas  when running this command the -w parameter should just be the name of the webjob instead of <webappname/webjobname>

so try this 
az webapp webjob continuous stop -n <webappname> -g <resourceGroupName> -w <webjobname>

Please let me know if this fixes the issue. thank you.

**Comment by panchagnula** [comment]
Please re-activate if this is still an issue after trying the above suggestion. Thanks!
