### ISSUE TITLE
Unable to access public github release for extension

### ISSUE THREAD

**Issue by dwj300** [Azure/azure-cli#8885]
**Describe the bug**
When trying to add the sap-hana extension using a release newer than 2.0.52, we get a 403 when trying to get a publically accessible URL on github.

**To Reproduce**
`$ docker run -it microsoft/azure-cli:2.0.53 python -c "import requests; print(requests.get('https://github.com/Azure/azure-hanaonazure-cli-extension/releases/download/0.3.4/sap_hana-0.3.4-py2.py3-none-any.whl').status_code)" `
This will return a 403 from github on anything newer than 2.0.52.

**Expected behavior**
`$ docker run -it microsoft/azure-cli:latest python -c "import requests; print(requests.get('https://github.com/Azure/azure-hanaonazure-cli-extension/releases/download/0.3.4/sap_hana-0.3.4-py2.py3-none-any.whl').status_code)"`
This should return a 200 and download our extension.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
docker

**Additional context**

**Comment by yonzhan** [comment]
@fengzhou-msft  add to S162.

**Comment by fengzhou-msft** [comment]
I cannot reproduce the issue with `microsoft/azure-cli:2.0.53` or `microsoft/azure-cli:latest`. They both return 200 for me.
Please also note that we migrated the docker image to mcr, you can pull from `mcr.microsoft.com/azure-cli` for newer images.
