### ISSUE TITLE
Misleading message when creating functionapp

### ISSUE THREAD

**Issue by zikalino** [Azure/azure-cli#8889]
**Describe the bug**
When creating functionapp you try to specify **--deployment-container-image-name httpd** without passing **--plan** that is **is_linux**, Azure CLI resoponds with following message, which is quite misleading:

**usage error: --runtime RUNTIME required for linux functions apps without custom image.**

**To Reproduce**

az group create --name zimsfromclixx --location westeurope

az storage account create --name zimsstoragefromclixx --location westeurope --resource-group zimsfromclixx --sku Standard_LRS

az functionapp create --resource-group zimsfromclixx --os-type Linux --name zimsfromclixx --deployment-container-image-name httpd --storage-account zimsstoragefromclixx

**Expected behavior**
Argument **--deployment-container-image-name** should not be just ignored.
The message should be perhaps "Argument --deployment-container-image-name  can be only specified with plan that is_linux" or something like this.

**Environment summary**
CloudShell

**Additional context**

**Comment by ankitkumarr** [comment]
Hi @zikalino, I am unable to reproduce this bug in cloudshell. On running something like- `az functionapp create --resource-group zimsfromclixx --os-type Linux --name zimsfromclixx --deployment-container-image-name httpd --storage-account zimsstoragefromclixx`,
I get this error-
`usage error: --plan NAME_OR_ID | --consumption-plan-location LOCATION`

which is expected. Did you have any additional param?

On providing a `--plan`, it works fine for me.

**Comment by zikalino** [comment]
@ankitkumarr I can recheck that. perhaps something got updated in a meanwhile. or something is different in my subscription. I think if I haven't specified --plan it was either creating a default one or finding one in the subscription. I am not sure now.

**Comment by ankitkumarr** [comment]
@zikalino, I think you might have specified `--consumption-plan-location`. If you specify that, you cannot have custom image. So, that's why `--consumption-plan-location` was ignored and you got that error message.
I agree that the error message should be clear and let people know that you shouldn't use `--consumption-plan-location` and `--deployment-container-image-name` at the same time. We should fix that. Thanks for the report!

\cc @ahmedelnably

**Comment by panchagnula** [comment]
CC: @ankitkumarr
