### ISSUE TITLE
Doc: in 'README.rst' put a link to configuring_your_machine.md

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#889]
(open this issue after chatted with a folk who struggled to get his dev box setup)
For people going to git repo page, more or less are developers who want to contribute, so we should mention dev scenarios in the repo's main page, particularly on how to set up the machine . So suggest mention a link to
    https://github.com/Azure/azure-cli/blob/master/doc/configuring_your_machine.md

**Comment by brettcannon** [comment]
Another possible place is CONTRIBUTING.md.
