### ISSUE TITLE
Information needed for how name servers assigned

### ISSUE THREAD

**Issue by jshomphe** [Azure/azure-cli#8891]
When doing an import from a BIND .zone file, it appears that name servers are automatically assigned.  Is there a way to predict what name servers get assigned?  I am concerned if we have to do a delete and bulk import again we could have new name servers assigned to each zone and break dns.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ccaec50-407e-bf8a-6004-a824c2094c5b
* Version Independent ID: 8d2f2443-7636-2462-7806-0916a8603a0d
* Content: [az network dns zone](https://docs.microsoft.com/en-us/cli/azure/network/dns/zone?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
My understanding is you cannot control the name servers. @muwaqar for additional clarification.

**Comment by muwaqar** [comment]
That is correct (AFAIK). Please confirm with karravi@microsoft.com.

**Comment by jshomphe** [comment]
If it cannot be controlled, is it deterministic?  Meaning if I deleted and re-imported at a later date, would it get the same name servers?  It seems to work that way within a subscription, but not across subscriptions

**Comment by muwaqar** [comment]
My understanding is that it is non-deterministic as well, but again karravi
will be able to confirm.

**Comment by tjprescott** [comment]
@karravi-msft for clarification

**Comment by jshomphe** [comment]
Thanks everyone! Your team moves very quickly.

Either way, it would be helpful to know in the documentation how it works.

**Comment by MyronFanQiu** [comment]
@karravi-msft Hello. Any update?

**Comment by yonzhan** [comment]
add to S164.

**Comment by MyronFanQiu** [comment]
@karravi-msft Hi. Could you give a doc link or confirm the service's behavior? We don't know too much details about this question.

**Comment by yonzhan** [comment]
@karravi-msft any feedback or update?

**Comment by rohinkoul** [comment]
@yonzhan Nameserver assignment is based on a hashing mechanism. However this can change in future and customers must not rely on this. Please close this issue.
