### ISSUE TITLE
It is not clear how to find api and permissions numbers

### ISSUE THREAD

**Issue by spacekitty76** [Azure/azure-cli#8894]
**Describe the bug**
This is more of a question or feature request to update the documentation.

The examples use alphanumerical strings for the api and permissions values rather than the human friendly names like "Graph API" and permissions of "Sign in and read user profile".  It is unclear how to convert these name to the values az cli is looking for.

**To Reproduce**
I want to grant an app API access to Microsoft Graph with the permissions of Sign in and read user profile and Read directory data.  I can find no information on the cli values for these things.

For example I want to use this command:
az ad app permission add --id (my app id here) --api (desired api) --api-permissions (desired permission)=Scope

How to I find the desired api and desired permissions that I need to enter into the command above?  I.e. in the example, how do you convert "Sign in and read user profile" to this "311a71cc-e848-46a1-bdf8-97ff7156d8e6".  It would be helpful to have this in the documentation.

**Comment by spacekitty76** [comment]
For clarity here's the example I'm trying to use:
https://docs.microsoft.com/en-us/cli/azure/ad/app/permission?view=azure-cli-latest#examples

**Comment by yugangw-msft** [comment]
@spacekitty76, each permission is a uuid, and there is no reference doc you can get for all the values.
The recommended flow is you manually configure one in the Azure portal and click the manifest button in the application's tab which will show you the permission uuid that you can use it to do the same thing through CLI.

![image](https://user-images.githubusercontent.com/6014209/55124692-56b49c80-50c4-11e9-923e-3188e0f294de.png)

**Comment by yugangw-msft** [comment]
Closing, since I have answered the question
