### ISSUE TITLE
Feature: `az cdn endpoint list-cached` or `az cdn endpoint purge-all`

### ISSUE THREAD

**Issue by iyerusad** [Azure/azure-cli#8895]
**Is your feature request related to a problem? Please describe.**
Purging CDNs doesn't appear to be possible without `az cdn endpoint list-cached` (output of what paths are currently cached in a CDN endpoint). Standard Akamai CDN [does not appear to support wildcards in CDN purge](https://docs.microsoft.com/en-us/azure/cdn/cdn-purge-endpoint) - Premium Verizon CDN does. This does not appear to be a market segmentation distinction, but a tooling issue.

**Describe the solution you'd like**
A) `az cdn endpoint list-cached`: Outputs list of cached files
B) More ideally, `az cdn endpoint purge-all`: Iterate through cached files list and purge them. This is similar to `az storage blob delete-batch` command.

**Describe alternatives you've considered**
- Premium Verizon CDN
- 3rd Party CDN providers
- Using SPA that links off everything in index.html, and then purging path `/index.html` (this is edge case grace due to SPA and not without its flaws)

Would like to stay within ecosystem, seems like tooling update here can make an "unsupported" feature, supported across the board.

**Additional context**
CDN is fronting a static website hosted on Azure Storage. Purging CDN is neccesary during deployment as content is changed.

**Comment by tjprescott** [comment]
@iyerusad the tooling is owned by the service team, so it would be up to them whether they would support it purely at the tools level or at the service level.

**Comment by hytao** [comment]
These features are currently not supported by the service provider Akamai. Please reach out to CDN PM(azcdnpm@microsoft.com) team to discuss about this feature request.

**Comment by MohamedOthman** [comment]
is this supported in verizon premium ?

**Comment by hytao** [comment]
No, non of the providers support this feature at the moment. Please reach out to CDN PM(azcdnpm@microsoft.com) team to discuss about this feature request.
