### ISSUE TITLE
Add deprecation banner to Azure Batch AI page

### ISSUE THREAD

**Issue by garyericson** [Azure/azure-cli#8897]
Azure Batch AI has been deprecated and the Azure CLI reference content for Batch AI will be removed in the next few months. Until then, we would like to add a banner to the [Batch AI ref content](https://docs.microsoft.com/en-us/cli/azure/batchai?view=azure-cli-latest) similar to what we've done for other Batch AI reference (e.g., [REST API](https://docs.microsoft.com/en-us/rest/api/batchai/), [.NET](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/batchai?view=azure-dotnet)). Other CLI content appear to have custom text, such as [Cognitive Services](https://docs.microsoft.com/en-us/cli/azure/cognitiveservices?view=azure-cli-latest), but I can't figure out how that was done. I can find nothing in the Contributor Guide that addresses this for CLI.

The banner we would like to add is the following:

HTML:
```
<strong>Note</strong><br><strong>Azure Batch AI service has been retired.</strong> The capabilities of Azure Batch AI are now available as a managed compute target in Azure Machine Learning service. For more information, see <a href="https://aka.ms/batchai-retirement">What happened to Batch AI?</a>
```

Markdown:
```
>[!Note]
>**Azure Batch AI service has been retired.** The capabilities of Azure Batch AI are now available as a managed compute target in Azure Machine Learning service. For more information, see [What happened to Batch AI?](https://aka.ms/batchai-retirement)
```

**Comment by tjprescott** [comment]
Use can use deprecation mechanisms in the CLI to advertise that the batchai command tree is deprecated. 
https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#deprecating-commands-and-arguments

For doc specific issues, I'd refer you to @dendeli-msft.

**Comment by garyericson** [comment]
@tjprescott @dendeli-msft - Thanks. I looked at the information you linked to, but best I can tell this is something that a developer needs to do in the code. There is no more development on this, so I'm looking for a way to just put a banner on the doc temporarily until the CLI is removed altogether in a few months. It's similar to what we've done for other Batch AI APIs.

**Comment by garyericson** [comment]
We've decided that we're okay with leaving this as-is. #please-close
