### ISSUE TITLE
Setting truthy tags "false" get case converted

### ISSUE THREAD

**Issue by dbilleci-lightstream** [Azure/azure-cli#8911]
Easiest bug report ever:

````
$ az vm update --name my-vm --resource-group my-rg --set tags.test=false | jq .tags.test
"False"

$ az vm update --name my-vm --resource-group my-rg --set tags.test=test | jq .tags.test
"test"

$ az vm update --name my-vm --resource-group my-rg --set tags.test=true | jq .tags.test
"True"

$ az vm update --name my-vm --resource-group my-rg --set tags.test=banana | jq .tags.test
"banana"

$ az --version
azure-cli                         2.0.61
````

Assume somewhere in the python depths of the cli they are cast as a boolean and that causes this.. it caused an issue on our app (we'll work around the case) but figured it's worth a report.

Thanks!

**Comment by tjprescott** [comment]
Thanks for the report @dbilleci-lightstream. We'll take a look.

**Comment by tjprescott** [comment]
Hi @dbilleci-lightstream. Please run your command with `--force-string`.  This will force it to preserve the value as a string and not try to evaluate it (in this case to boolean).

**Comment by dbilleci-lightstream** [comment]
this makes no sense..

booleans in JSON/javascript are written in lowercase..

https://imgur.com/a/S3Id35t

only Python as far as I know uses capital True and False like that
