### ISSUE TITLE
--years

### ISSUE THREAD

**Issue by Als30** [Azure/azure-cli#8918]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by tjprescott** [comment]
There is no information in this issue.
