### ISSUE TITLE
webapp: add generic update on web app

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#892]
There is ongoing API improvements made by the service team, particularly on annotating clearly which fields are mutable vs read-only . I suggest we do it after that work is done, which mean post-ignite.
At the same time, we have strong typed `update` which is easier to use but expose less fields, and it is in parity with posh. xplat has not had the support yet.

**Comment by tjprescott** [comment]
PR #999 added generic update to service plan. Only web app remains.

**Comment by yugangw-msft** [comment]
@williexu, please expose a `--client-affinity-enabled` from the update command to cover #4471 tries to accomplish
