### ISSUE TITLE
Command `az keyvault key/secret/certificate list/list-deleted/list-versions` with parameter `--maxresults` do not work as intended

### ISSUE THREAD

**Issue by SteveParson** [Azure/azure-cli#8921]
**Describe the bug**
`az keyvault secret list` has an optional argument that specifies the maximum number of results to return. When a user specifies this argument, they receive an error `Parameter 'maxresults' failed to meet validation requirement.`

**To Reproduce**
$ `az keyvault secret list --vault-name my-keyvault --maxresults 1000`
Parameter 'maxresults' failed to meet validation requirement.

**Expected behavior**
I would expect the secrets to be listed.

**Environment summary**
$ `cat os-release | grep VERSION=`
VERSION="18.04.2 LTS (Bionic Beaver)"
$ `az --version | grep azure-cli`
azure-cli                         2.0.61
$ `bash --version | grep 'GNU bash'`
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
$ `python3 --version`
Python 3.6.7

**Additional context**
Related to https://github.com/Azure/azure-cli/issues/7311

**Comment by yonzhan** [comment]
@jiasli add to S162.

**Comment by frackham** [comment]
This is also the case for az keyvault secret list-versions.

**Comment by bim-msft** [comment]
Same issue for all commands like `az keyvault key/secret/certificate list/list-deleted/list-versions`

**Comment by yungezz** [comment]
Fixing of the issue will be released in next release 2.0.29, which will be released around mid of Jan.
