### ISSUE TITLE
Make extensions compatible with latest versions of wheel

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#8923]
Currently, extensions are required to be built with wheel 0.29.0 or 0.30.0, which are not the latest versions. We should investigate updating the extension infrastructure (and supporting scripts, like the doc gen script that is very brittle) to be compatible with the latest wheel package. This will also involve changes to azdev. 

cc/ @marstr yugangw-msft

**Comment by tjprescott** [comment]
I will take a look after Build.

**Comment by yonzhan** [comment]
add to S164.

**Comment by haroldrandom** [comment]
Dup https://github.com/Azure/azure-cli/pull/12583.
There are some context, It needs a bit effort to make change.
