### ISSUE TITLE
optional vs non optional parameters are missing for many commands

### ISSUE THREAD

**Issue by shaochen** [Azure/azure-cli#8924]
optional vs non optional parameters are missing for many commands

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e50d77a-f2fa-6d6e-0c57-2f434c12766f
* Version Independent ID: f9a98805-6e16-487a-03ce-237cb964f83c
* Content: [az webapp config](https://docs.microsoft.com/en-us/cli/azure/webapp/config?view=azure-cli-latest#az-webapp-config-show)
* Content Source: [latest/docs-ref-autogen/webapp/config.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Can you give a specific example?

**Comment by shaochen** [comment]
e.g. for webapps it seems to be only specified for "create"

**Comment by tjprescott** [comment]
There are many cases where arguments are conditionally required. In these cases, they will appear as optional unless you try to use them incorrectly, at which time you will receive an error giving the proper use. The most common example, using `webapp show` to illustrate, is with the "Resource Id Arguments":

```
Resource Id Arguments
    --ids               : One or more resource IDs (space-delimited). If provided, no other
                          'Resource Id' arguments should be specified.
    --name -n           : Name of the web app. You can configure the default using 'az configure
                          --defaults web=<name>'.
    --resource-group -g : Name of resource group. You can configure the default group using `az
                          configure --defaults group=<name>`.
    --subscription      : Name or ID of subscription. You can configure the default subscription
                          using `az account set -s NAME_OR_ID`.
```
You must either supply `--name` and `--resource-group` OR `--ids`. Unfortunately, there is not a way to convey this with argparse so they all simply appear optional. If an argument is listed as [Required] then is is required in all uses of the command.

If there is a specific issue where an argument is always required but not labeled as so, feel free to open a new issue (or if an arg is listed as required and shouldn't necessarily be).
