### ISSUE TITLE
Add Support for Environment Variables Detection

### ISSUE THREAD

**Issue by robconery** [Azure/azure-cli#8930]
One of the things I like to do is to orchestrate resource creation with a script, set of scripts, or a Makefile. The first step is, typically, to create a `.env` file with my Azure settings, typically something like:

```
APPNAME=MyApp
RG=MyResourceGroup
PLAN=$APPNAME-Plan
```

What would be SUPER helpful is if the CLI could standardize application-wide settings like this. For instance, if I could specify, in my `.env` file:

```
AZ_NAME=MyApp
AZ_RG=MyResourceGroup
AZ_PLAN=$APPNAME-Plan
```

... and have the CLI pick those up automatically (if set), it would make a lot of redundancy go away. For instance, creating app settings and so one, I wouldn't need to pass in `-n` and `-g` every single time. 

This is mostly a convenience, but it would be super helpful!

**Comment by tjprescott** [comment]
Hi @robconery, this is already supported. The format for the environment variables are:

AZURE_DEFAULTS_<NAME>

You will know properties that can be set in this way when the help says "You can configure the default BLAH using `az configure --defaults NAME=<name>`"

**Comment by robconery** [comment]
Thanks @tjprescott - I gave it a whirl and something seems to be amiss... either that or I wasn't clear enough with the issue. 

I created a `.env` file and added these:

```
AZURE_DEFAULTS_WEB=velzyappX
AZURE_DEFAULTS_GROUP=velzyX
AZURE_DEFAULTS_APPSERVICEPLAN=velzyplanX
``

I then ran `printenv` to be sure they're present, and they are. Next, I executed:

```
az group create
``

Unfortunately this throws `az group create: error: the following arguments are required: --name/--resource-group/-n/-g` which would suggest the variable is not being picked up.

If I understand you correctly, the resource group default should work here - is this correct? If not, _that_ was my request :) that we could set these in a common area and have them picked up.

**Comment by tjprescott** [comment]
It you simply `export AZURE_DEFAULTS_GROUP=velzyX` then running `az group show -h` should show your default value. Alternatively, you can simply use `az configure -d group=velzyX` to configure the defaults in your config file.

**Comment by robconery** [comment]
Ah - I see what you mean. Yes, I see the default there, but that's not necessarily what I want. I want a localized "rc file" kind of experience, if you will, that identifies the common resource group/name/plan/location values that I'll be using for my application _in this specific location_. Not system-wide defaults, just local defaults.

I can't run `az group create` using the method you suggest here - even if it is a default - because I need to specify the name and location. I'd rather specify those things _once_ in a .env file or .azrc file (which would be killer).

Does this make sense?

**Comment by tjprescott** [comment]
Hi @robconery yes, that does make sense. @yugangw-msft isn't this what your local context implementation does?

**Comment by tjprescott** [comment]
Possible related to #7992.

**Comment by robconery** [comment]
Yeah - that looks like a related suggestion. Can't quite tell how the implementation is done but ideall it's some kind of text file :) or environment variable.

**Comment by yonzhan** [comment]
add to S164.

**Comment by jiasli** [comment]
`az configure` now supports `--scope` which make the config specific to a directory. 

```
>az configure -h

    --scope            : Scope of defaults. Using "local" for settings only effective under current
                         folder.  Allowed values: global, local.  Default: global.
```

We are going to extent to automatic argument populating in Local Context implementation: https://github.com/Azure/azure-cli/issues?q=+label%3A%22Local+Context%22. +@arrownj
