### ISSUE TITLE
getting error while doing "az acr create"

### ISSUE THREAD

**Issue by abhishekkarigar** [Azure/azure-cli#8932]
**Describe the bug**
while doing az acr create , i get pip install erorrs, 

**To Reproduce**
az acr create --resource-group myResourceGroup --name mycontainerregistry082 --sku Basic --admin-enabled true

**Expected behavior**
{
  "adminUserEnabled": true,
  "creationDate": "2018-03-16T21:54:47.297875+00:00",
  "id": "/subscriptions/<Subscription ID>/resourceGroups/myResourceGroup/providers/Microsoft.ContainerRegistry/registries/mycontainerregistry082",
  "location": "eastus",
  "loginServer": "mycontainerregistry082.azurecr.io",
  "name": "mycontainerregistry082",
  "provisioningState": "Succeeded",
  "resourceGroup": "myResourceGroup",
  "sku": {
    "name": "Basic",
    "tier": "Basic"
  },
  "status": null,
  "storageAccount": null,
  "tags": {},
  "type": "Microsoft.ContainerRegistry/registries"
}

**Environment summary**
  CLI version (`az --version`) = 2.6.x
  OS version = windows 10 64 bit
 Shell Type = cmd.exe

**Comment by yugangw-msft** [comment]
@abhishekkarigar, we are closing this issue, but feel free to reactivate if you can provide the error text of pip install
