### ISSUE TITLE
--zone not creating standard pulic IP in eastus

### ISSUE THREAD

**Issue by brianbar-MSFT** [Azure/azure-cli#8933]
**Describe the bug**
Using --zone when the resource group is located in eastus fails with an error that basic SKU public IP is not supported. The same command run in westus2 doesn't fail and the public IP is created as standard SKU.

**To Reproduce**
az group create --name testRG --location eastus
az vm create --resource-group testRG --name testVM --image ubuntults --size Standard_B1ms --admin-username testuser --generate-ssh-keys --zone 3

The error:

Deployment failed. Correlation ID: b28b7921-4d51-4885-a398-2b2044a69903. {
  "error": {
    "code": "ZonesNotAllowedInBasicSkuResource",
    "message": "Zones not allowed in basic SKU resource /subscriptions/<mySubID>/resourceGroups/testRG/providers/Microsoft.Network/publicIPAddresses/testVMPublicIP in this region. Please use standard SKU.",
    "details": []
  }
}

**Expected behavior**
If you run this same command but the RG is located in westus2 it successfully creates the VM.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)
Cloud Shell - Bash - Azure CLI 2.0.61
Ubuntu 18.01 Windows Subsystem for Linux - Azure CLI 2.0.61

**Comment by yugangw-msft** [comment]
@singhkays 
Can you have CRP folks take a look? East US does have zonal VM support for this size
```bash
(env) D:\sdk\azure-cli-extensions>az vm list-skus -l eastus --size Standard_B1ms --query "[].locationInfo"
[
  [
    {
      "location": "eastus",
      "zones": [
        "2",
        "1",
        "3"
      ]
    }
  ]
]
```

**Comment by singhkays** [comment]
Adding @shandilvarun VM PM for taking a look

**Comment by adewaleo** [comment]
@singhkays @shandilvarun, any progress on this issue?

**Comment by shandilvarun** [comment]
I'm investigating. will respond to this thread.

**Comment by shandilvarun** [comment]
some resources are not availble in all zones, Adding @anavinahar since this error was returned by netwokring RP. 
For Compute, you should look at zones which are returned with the SKU to see if a zone is supported on a SKU or not, if zones are absent on the SKU then that zone is not supported. Thanks!

**Comment by adewaleo** [comment]
Thanks for the update @shandilvarun. What do you mean by "returned"? Do you mean returned by a compute RP error or by the endpoint for viewing vm sku information?  

` Request URL: 'https://management.azure.com/subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/providers/Microsoft.Compute/skus?api-version=2017-09-01'`

@anavinahar what do you think, could it be that publicIPAddresses can be zonal in "westus2" but not in "eastus"?

**Comment by Drewm3** [comment]
This looks like an issue with the CLI code. IP addresses for zonal VMs are supposed to be Standard IP addresses, but it seems that some regions such as East US 2 are allowing Basic IP addresses to be used for Zonal VMs. 

East US, which is used in the above example, seems to be returning an expected error. 

I am in the process of identifying the right owners for this issue, and I will update the issue once the correct owners have been identified.

**Comment by anavinahar** [comment]
Basic zonal is not supported. We are working to block this in the few regions that remain.

**Comment by Drewm3** [comment]
Thanks @anavinahar. Let me find the current owner of the Azure CLI VM quick-create functionality, and then assign this issue to them.

**Comment by qwordy** [comment]
```
<class 'dict'>: {'apiVersion': '2018-01-01', 'type': 'Microsoft.Network/publicIPAddresses', 'name': 'testVMPublicIP', 'location': 'eastus', 'tags': {}, 'dependsOn': [], 'properties': {'publicIPAllocationMethod': None}, 'zones': ['3']}
```
In order to create VM, we need to create publicIPAddresses. The default sku for publicIPAddresses is basic. But in some region, zone are not allowed in basic sku.
@MyronFanQiu Do you know which regions allows zones in basic sku?

**Comment by MyronFanQiu** [comment]
@qwordy Well. I don't know the answer either. It's a quite detail question. But for this issue, my opinion is to expose an argument for user to choose the sku for public ip or you can automatically set the sku of the public ip to Standard if they want to use `--zones`. @anilingle-ms may know which regions allows zones in basic sku.

**Comment by qwordy** [comment]
You can use `--public-ip-sku Standard` to specify a standard public ip sku.
Complete command:
```
az vm create --resource-group testRG --name testVM --image ubuntults --size Standard_B1ms --admin-username testuser --generate-ssh-keys --zone 3 --public-ip-sku Standard
```

**Comment by Drewm3** [comment]
Moving this over to @yonzhan who is the owner of the CLI, and removing Service Attention. This needs to be fixed in the CLI when it automatically creates IP addresses it must create a standard IP address instead of a basic IP address when the IP address is being created to be used with a zonal VM.

**Comment by yonzhan** [comment]
@Drewm3 we will triage and plan it after National holiday.

**Comment by qwordy** [comment]
> 
> 
> Moving this over to @yonzhan who is the owner of the CLI, and removing Service Attention. This needs to be fixed in the CLI when it automatically creates IP addresses it must create a standard IP address instead of a basic IP address when the IP address is being created to be used with a zonal VM.

It's a feasible method.  It seems some regions such as East US 2 are allowing Basic IP addresses to be used for Zonal VMs. Will users complain that an expensive standard IP address are automatically created?

**Comment by Drewm3** [comment]
I am not sure why basic is allowed in some of these regions. My understanding was that only standard IP addresses were going to be supported for zonal VMs. Please work with the Azure Networking folks to understand why there is differing support in different regions. I believe that the regions that support basic for zonal VMs may have been a mistake which will eventually be removed by Azure Networking.

**Comment by qwordy** [comment]
OK. Thanks for explanation. Let's use standard IP address automatically when using zones. I suggest put it into Sprint 76 since only 2 days left before release. If coding and testing go very smoothly, maybe we can catch up with Spring 75.

**Comment by qwordy** [comment]
I've added this feature. https://github.com/Azure/azure-cli/pull/10691

**Comment by Drewm3** [comment]
Thanks for adding the feature. I am going to close out this issue now.

**Comment by brianbar-MSFT** [comment]
Thanks for the hard work on resolving this everyone. :)

**Comment by qwordy** [comment]
https://github.com/Azure/azure-cli/pull/10691 has been merged.
