### ISSUE TITLE
az group deployment fails on empty parameters file

### ISSUE THREAD

**Issue by bobvandevijver** [Azure/azure-cli#8935]
**Describe the bug**
When you have an empty parameters file (such as below), the CLI will not be able to parse it for the group deployment.

```json
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {}
}
``` 

**To Reproduce**
```
az group deployment validate --resource-group rg-common-eu-dev --template-file common/template.json --parameters @common/parameters.dev.json
Unable to parse parameter: {
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {}
}
```

**Expected behavior**
An empty parameters file should work like there are no parameters are supplied

**Environment summary**
azure-cli 2.0.61 on macOS Mojave

**Additional context**
Similar to #6787, but this ticket concerns the parameter file.

**Comment by tjprescott** [comment]
Thanks for the report @bobvandevijver. This should be fixed in the next release.
