### ISSUE TITLE
`az configure` should help you pick the right subscription

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#894]
Today, `az configure` helps you get logged in, but for users with multiple subscriptions, you are required to manually set the right 'default' subscription.  We should add this to the `configure` command after your login completes.

```
We've found multiple subscriptions on your account, which would you like to make your default?
   [0] AzureCloud - AzureCLI-Demo
   [1] AzureCloud - JavaTest
   [2] ChinaCloud - Test subscription
Please enter a choice [0]: 
```

**Comment by mayurid** [comment]
@JasonRShaver :To get the associated Subscriptions with an account to be able to prompt we need to sign in first which is counter intuitive at the configure phase. 
@yugangw-msft  please feel free to comment

**Comment by mayurid** [comment]
I am closing this @JasonRShaver Please reactivate if u disagree.
