### ISSUE TITLE
Support az feature unregister

### ISSUE THREAD

**Issue by jluk** [Azure/azure-cli#8941]
**Is your feature request related to a problem? Please describe.**
There are feature previews that impact the ongoing behavior of CLI due to using new versions of APIs.

**Describe the solution you'd like**
I want one command to revert my API version to one that is supported and not on preview terms.

**Describe alternatives you've considered**
API calls can be made but that is not a good experience after enabling something.

**Comment by tjprescott** [comment]
It seems like there's a PS cmdlet for this, but there doesn't seem to be an ARM endpoint for this functionality. @yugangw-msft do you know a good contact on the ARM team to confirm?

**Comment by yugangw-msft** [comment]
I have not found the PS cmdlet doing that. Under the source [folder](https://github.com/Azure/azure-powershell/tree/master/src/Resources/ResourceManager/Implementation/Features) only has the `register` cmdlet.
@vladimirjoanovic, can you please chip in the api details?

**Comment by jluk** [comment]
Talking to @yangl900 looks like a post can be made similar to: `armclient post /subscriptions/<somesubscription>/providers/Microsoft.Features/providers/Microsoft.Xrm/features/uxdevelopment/unregister?api-version=2015-12-01`

**Comment by yugangw-msft** [comment]
Maybe improve the swagger api [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Features/stable/2015-12-01/features.json) to unblock SDK/POSH/CLI?

**Comment by jluk** [comment]
@vladimirjoanovic can you add the proper owner to this discussion?

**Comment by jluk** [comment]
Opened an issue on swagger as well https://github.com/Azure/azure-rest-api-specs/issues/5607

**Comment by zparnold** [comment]
Has this gotten any love?

**Comment by yonzhan** [comment]
ARM service attention

**Comment by ifeoluwaokunoren** [comment]
We're actively working on providing this command - 
PR link: https://github.com/Azure/azure-cli/pull/13487
I'd add update this thread once the PR is merged.
In the meanwhile if you're blocked, you can directly unregister a subscription from a feature using the REST API: https://github.com/Azure/azure-rest-api-specs/blob/38388fadb2a31238262c96520a96f413ff7c7311/specification/resources/resource-manager/Microsoft.Features/stable/2015-12-01/features.json#L230

**Comment by ifeoluwaokunoren** [comment]
az feature unregister is now supported - [PR merged](https://github.com/Azure/azure-cli/pull/13487) 
Documentation Here: https://docs.microsoft.com/en-us/cli/azure/feature?view=azure-cli-latest
