### ISSUE TITLE
Enable WinRM access

### ISSUE THREAD

**Issue by mvsouza** [Azure/azure-cli#8956]
I'm looking for a command that enable WinRM service for a VM.

It would enable the admin to automate a VM configuration via powershell scripts.

This feature can be found on the Azure Cloud Shell(Enable-AzVMPSRemoting).

**Comment by yugangw-msft** [comment]
@adewaleo, I suggest talk to the author of the PoSH cmdlet and understand the detail and offer workarounds at least.
I guess this pretty much winds down 
    1. Configure the NSG
    2. Open a port
    3. Maybe a custom script extension to install PowerShell

**Comment by adewaleo** [comment]
> @adewaleo, I suggest talk to the author of the PoSH cmdlet and understand the detail and offer workarounds at least.
> I guess this pretty much winds down
> 1. Configure the NSG
> 2. Open a port
> 3. Maybe a custom script extension to install PowerShell

Sounds good @yugangw-msft. This makes sense!

**Comment by adewaleo** [comment]
I will be closing this for now as CLI team does not have the bandwidth to implement this in the near feature and there isn't a high demand for this feature.

cc: @yugangw-msft
