### ISSUE TITLE
`test_vmss_run_command_e2e` test is flaky and spuriously fails CI

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#8958]
This test spuriously fails the CI, necessitating a wasteful 40 minute retry.

![Picture1](https://user-images.githubusercontent.com/5723682/55424262-b4b60980-5534-11e9-9247-7b567d66dd4b.png)

![Picture2](https://user-images.githubusercontent.com/5723682/55424265-b67fcd00-5534-11e9-984f-deabbc09d3bd.png)

**Comment by adewaleo** [comment]
@tjprescott I can't see the pictures clearly. Not sure if this was intentional. Do you have any other info on the failures? For example, what the error was?

**Comment by tjprescott** [comment]
All that really mattered was it was Python 2.7 and took 40 minutes

**Comment by tjprescott** [comment]
All that really mattered was it was Python 2.7 and took 40 minutes to fail, which is very frustrating to have to refresh for a spurious fault.

**Comment by adewaleo** [comment]
This is helpful :) thanks for the info!
