### ISSUE TITLE
az vm run-command invoke command timed out for long running command or script

### ISSUE THREAD

**Issue by Sas002** [Azure/azure-cli#8967]
I am using "/bin/sh" "-c" "az vm run-command invoke command from Linux VM to trigger command which has to run for more than 2 hours for SAP data Hub installation script. In backend it just calls ansible-playbook. I am getting timed out issue for long running process and it terminates in middle. Which is not the way it should work.  Is there a quick fix or configuration to keep the process running for long time .

Error **Provisioning of VM extension 'RunCommandLinux' has timed out. Extension installation may be taking too long, or extension status could not be obtained.** 

Here is my az  cli version which is latest for RHEL7 VM . 

**azure-cli                         2.0.61**

acr                                2.2.3
acs                               2.3.20
advisor                            2.0.0
ams                                0.4.3
appservice                        0.2.16
backup                             1.2.2
batch                              4.0.0
batchai                            0.4.8
billing                            0.2.1
botservice                         0.1.9
cdn                                0.2.1
cloud                              2.1.1
cognitiveservices                  0.2.5
command-modules-nspkg               2.0.2
configure                         2.0.20
consumption                        0.4.2
container                         0.3.15
core                              2.0.61
cosmosdb                           0.2.9
dla                                0.2.5
dls                                0.1.8
dms                                0.1.3
eventgrid                          0.2.2
eventhubs                          0.3.4
extension                          0.2.4
feedback                           2.1.4
find                               0.3.1
hdinsight                          0.3.2
interactive                        0.4.2
iot                                0.3.7
iotcentral                         0.1.6
keyvault                          2.2.13
kusto                              0.2.1
lab                                0.1.6
maps                               0.3.4
monitor                           0.2.11
network                            2.3.5
nspkg                              3.0.3
policyinsights                     0.1.2
profile                            2.1.4
rdbms                              0.3.9
redis                              0.4.2
relay                              0.1.4
reservations                       0.4.2
resource                          2.1.12
role                               2.4.3
search                             0.1.1
security                           0.1.1
servicebus                         0.3.4
servicefabric                     0.1.15
signalr                            1.0.0
sql                                2.2.0
sqlvm                              0.1.1
storage                            2.3.2
telemetry                          1.0.2
vm                                2.2.17

Python location '/usr/lib64/az/bin/python'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 2.7.5 (default, Sep 12 2018, 05:31:16)

**Comment by Sas002** [comment]
I found about the restriction which timed out for operation runs more than 90 minutes. Is there any work around for bypass 90 minutes ?  SAP and other enterprise softwares require more than 90 minutes and sometimes triggered with one script and can't modular to run in phases. So higher timed out value will be really help here . 

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/run-command#restrictions

**Comment by adewaleo** [comment]
@Sas002 this timeout restriction is a service side restriction. It doesn't appear from the docs your recommended that the timeout can be modified.  You are welcome to leave feedback on the run-commands docs page that run-commands should have configurable timeouts.

I can think of two solutions:
- If your script is custom written and can be broken down into more manageable portions, you can run them in sequence by using the [CustomScript](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-linux) vm extension via `az vm extension set`. You can run the custom scripts in the order desired.
- You can upload the desired script / command to your vm and have your Run-command script run the desired script in the background. I imagine scripts running in the background aren't subject to this timeout. The only issue is that you would need to verify if the launched script successfully ran and installed SAP data Hub.

Do you think this could help? What is your scenario?

**Comment by Sas002** [comment]
Thanks for your reply but this install script is provided by SAP and I do not think I can modify it. I am triggering install script using Ansible-playbook which is running fine inside VM for 3 hours or more only az vm is terminating with error after 90 minutes , which cause error and exit 1 code . As part of work around , I trigger one more check using az vm command which check Ansible process in VM and sleep for 1 second using do while loop but again I get error after next 90 minutes timed out if installation runs more than 3 hours which is the case always.

**Comment by adewaleo** [comment]
@Sas002. Thanks for the clarification.

The timeout of the run-command operation is not determined or modifiable by the CLI, it is determined by the compute service that manages VMs. The CLI simply interacts with the service via REST calls.

Given what you have described. I will go with the second recommendation I made. Let the run command run the install script as a background process (this means the command will return almost immediately but the install script won't be limited by the timeout).

 I am not familiar with Ansible-playbook, but what does the script you are executing / running through `az vm run-command` look like?

**Comment by Sas002** [comment]
I am calling Ansible-playbook 
az vm run-command invoke -g 
'${azurerm_virtual_machine.myserver.resource_group_name}' -n 
'${azurerm_virtual_machine.myserver.resource_group_name}' -- 
command-id RunShellScript —scripts 'Ansible-playbook myplaybook.yaml’

**Comment by Sas002** [comment]
Which run Ansible playbook inside vm nite than 3 hours but the az vm timed out with error after 90 minutes

**Comment by adewaleo** [comment]
@Sas002 this issue is not a CLI-side issue as the CLI simply sends the request to the VM for the run-command to be executed. The CLI does not determine the run-command timeout, this is a limit set on the service side.

As I have suggested above, your best bet would be to run Ansible playbook as a background process, so it is not constrained by the timeout. You can then run another script to validate that the Ansible install script ran properly. See below for examples of how to do this.


Run sleep 60:
```
$ time az vm run-command invoke -g ova-test -n tosin-debian --command-id runshellscript --scripts 'sleep 60'
{
  "value": [
    {
      "code": "ProvisioningState/succeeded",
      "displayStatus": "Provisioning succeeded",
      "level": "Info",
      "message": "Enable succeeded: \n[stdout]\n\n[stderr]\n",
      "time": null
    }
  ]
}

real	1m34.234s
user	0m1.146s
sys	0m0.249s

```

Run sleep 60 in the background using `&`:

```
$ time az vm run-command invoke -g ova-test -n tosin-debian --command-id runshellscript --scripts 'sleep 60 &'
{
  "value": [
    {
      "code": "ProvisioningState/succeeded",
      "displayStatus": "Provisioning succeeded",
      "level": "Info",
      "message": "Enable succeeded: \n[stdout]\n\n[stderr]\n",
      "time": null
    }
  ]
}

real	0m34.036s
user	0m1.083s
sys	0m0.239s
```

The run command returns in 30 seconds (overhead to get script running) instead of 1m 34 s, because the sleep command is being run in the background.

For your situation you would need to run:

```
az vm run-command invoke -g
'${azurerm_virtual_machine.myserver.resource_group_name}' -n
'${azurerm_virtual_machine.myserver.resource_group_name}' --
command-id RunShellScript —scripts 'Ansible-playbook myplaybook.yaml &’
```

**NOTE:**
You would need some mechanism to verify that the ansible.playbook installation script ran successfully.

**Comment by adewaleo** [comment]
As this is not a CLI issue and a workaround as been provided, I will be closing this issue. You can definitely follow up on the run-command docs page and request the ability to modify the command's timeout. This is something we cannot control on the CLI side.
