### ISSUE TITLE
az acr helm install-cli

### ISSUE THREAD

**Issue by Xaseron** [Azure/azure-cli#8974]
**Is your feature request related to a problem? Please describe.**
It bad to relay on external installations of helm. There is no official docker image with helm pre installed

**Describe the solution you'd like**
An easy way to install helm cli e.g. `az acr helm install-cli` which is similar to `az aks install-cli`

**Comment by schdief** [comment]
would be helpful for me as well, great idea!

**Comment by yugangw-msft** [comment]
This is a valid ask, which we should do

**Comment by karok2m** [comment]
Similar functionality would be useful for `az aks` command as well.

**Comment by yugangw-msft** [comment]
@Wwwsylvia, please fix this

**Comment by anweiss** [comment]
This would also address the use of the `az acr helm ... ` commands using the official Docker images. At the moment, you can't run `az acr helm ...` commands using the `mcr.microsoft.com/azure-cli` images, which subsequently prevents one from using these commands with the official GitHub Action for the Azure CLI (https://github.com/Azure/cli).

**Comment by Xaseron** [comment]
❤️
