### ISSUE TITLE
Cortana

### ISSUE THREAD

**Issue by bw-kforce-ms** [Azure/azure-cli#8976]
Has anyone thought of adding a cortana channel creation cli?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55111b1f-ca0d-0eb9-7457-3cdee47a6804
* Version Independent ID: 9442f477-20be-a67b-a38a-1846dc3cfbc4
* Content: [az bot](https://docs.microsoft.com/en-us/cli/azure/bot?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-botservice/azure/cli/command_modules/botservice/_help.py)
* Service: **bot-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Hi @bw-kforce-ms, this thread might be the best place to voice your support for this:
https://feedback.azure.com/forums/562027-azure-bot-service/suggestions/32039644-allow-cortana-channel-for-o365-aad-accounts

If that idea doesn't quite reflect your ask, it might make sense to post a new idea there. It seems that ideas get more traction with the service teams when they are posted to those forums.
