### ISSUE TITLE
Fabric MSI Azure CLI authentication stopped working after upgrading to VS 2019 

### ISSUE THREAD

**Issue by VaclavK** [Azure/azure-cli#8977]
**Describe the bug**
I have an SF app - reliable service -accessing KeyVault  - locally I have been using az cli connection string AzureServicesAuthConnectionString- RunAs=Developer; DeveloperTool=AzureCli

this has stopped working SLN running under freshly installed VS 2019 (2017 uninstalled) with az CLI failing to create a directory (SF running as local system - default)

There seems to be conflicting information about whether the scenario of local debug using az cli works under fabric or not - I am under impression that I have been using it but I am seeing statements that it is not supported and cannot work and cannot confirm anymore (with my local environment no longer working)

Is this "now" supported scenario?

seeing the stacktrace, it may be more appropriate to raise this with az-cli team?

***Exception or Stack Trace***
Parameters: Connection String: RunAs=Developer; DeveloperTool=AzureCli, Resource: https://vault.azure.net, Authority: https://login.windows.net/............ Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. Traceback (most recent call last):
 File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 193, in _run_module_as_main
   "__main__", mod_spec)
 File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 85, in _run_code
   exec(code, run_globals)
 File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\__main__.py", line 32, in <module>
   az_cli = get_default_cli()
 File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\__init__.py", line 492, in get_default_cli
   help_cls=AzCliHelp)
 File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\__init__.py", line 50, in __init__
   ensure_dir(azure_folder)
 File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\util.py", line 38, in ensure_dir
   os.makedirs(d)
 File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\os.py", line 220, in makedirs
   mkdir(name, mode)
PermissionError: [WinError 5] Access is denied: 'C:\\WINDOWS\\system32\\config\\systemprofile\\.azure'

**To Reproduce**
configure az cli azure connection string and run app running app authenticator

**Expected behavior**
This used to work so I am trying to understand the underlying cause why this stopped working after (coincidentally) VS 2019 installation

**Setup (please complete the following information):**
 - OS: Win 10
 - IDE : VS 2019 
 - Version of the Library used - SDK 3.3.644

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

This appears to be a CLI issue, not an issue with the .Net Azure SDKs, so I'm transferring the issue there.

CC: @yugangw-msft

**Comment by VaclavK** [comment]
also to note - az cli updated to latest 2.0.61

**Comment by yugangw-msft** [comment]
PermissionError: [WinError 5] Access is denied: C:\WINDOWS\system32\config\systemprofile\.azure'

This error shows the launcher (Fabric MSI?) sets CLI's configuration folder under system32 instead of the user profile folder like `c:\users\johndoe\.azure`?  Very wrong. Unless you run as admin, CLI will not be able to initialize its profile data under system32.

Pretty sure, not a CLI issue, please connect to SF team. 

Closing.
