### ISSUE TITLE
Can I retrieve Potential Annual Cost Savings and Recommendation Detail/Rule using this CLI ?

### ISSUE THREAD

**Issue by reddy-sucharit** [Azure/azure-cli#8988]
Hello Team, My customer is trying to consolidate an Exec report over 1400 + Subscriptions and they have to programaticaly retrieve all of the following Fields that they see when they download a report from Advisor. Is this possible ? , If so would you be kind enough to post an example on how to retrieve ? (Recommendation & Potential Annual Cost Savings ?)

Recommendation	Subscription ID	Subscription Name	Resource Group	Resource Name	Resource Type	Updated Date	Recommendation rule	Potential Annual Cost Savings	Potential Cost Savings Currency	Potential Cost Savings Percentage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06faf684-60e4-b8dc-f974-ca6d6018e843
* Version Independent ID: 809dab74-84dc-f7e5-895b-9203f302ff9d
* Content: [az advisor recommendation](https://docs.microsoft.com/en-us/cli/azure/advisor/recommendation?view=azure-cli-latest#az-advisor-recommendation-list)
* Content Source: [src/command_modules/azure-cli-advisor/azure/cli/command_modules/advisor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-advisor/azure/cli/command_modules/advisor/_help.py)
* Service: **advisor**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by treymorgan** [comment]
I'm interested in seeing this example.

**Comment by tjprescott** [comment]
@Prasanna-Padmanabhan for comment.

**Comment by Prasanna-Padmanabhan** [comment]
This is not yet possible but something we are planning for. I would encourage you to submit this request at https://feedback.azure.com/forums/919474-azure-advisor so others can see and upvote it which will help us prioritize this.

**Comment by reddy-sucharit** [comment]
Posted this question in Azure Feedback: https://feedback.azure.com/forums/919474-azure-advisor/suggestions/37323007-can-i-retrieve-potential-annual-cost-savings-and-r

Request followers on here to kindly vote against this feedback to help prioritize this request/recommendation.

**Comment by BathiniRavi** [comment]
Do we have any update here ?
Is there a way to pull the potential savings info via azure cli
