### ISSUE TITLE
SQL DB UPDATE command does not accept short name for elastic-pool argument

### ISSUE THREAD

**Issue by johnymachine** [Azure/azure-cli#8989]
**Describe the bug**
SQL DB UPDATE command does not accept short name for elastic-pool argument

[Documentation](https://docs.microsoft.com/en-us/cli/azure/sql/db?view=azure-cli-latest#az-sql-db-update) for **az-sql-db-update** on elastic-pool argument states: The name or resource id of the elastic pool to create the database in.

**This does not work:**
`user@machine:~$ az sql db update -g resgrp-s resgrp-sqlsrv -n madb_Copy --elastic-pool mypool`
Invalid resource identifier 'mypool'.

**This works:**
`user@machine:~$ az sql db update -g resgrp-s resgrp-sqlsrv -n madb_Copy --elastic-pool /subscriptions/xxxx-xxxx-xxxx/resourceGroups/rgjg/providers/Microsoft.Sql/servers/rgjg/elasticPools/mypool`

**To Reproduce**
Perform commands above.

**Expected behavior**
As defined by documentation.

**Environment summary**
Bash on Windows
azure-cli v2.0.61
python 3.6.5
_same in powershell on Windows 10_

**Comment by tjprescott** [comment]
Thank you for the report @johnymachine. This should follow the guidance here:
https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#supporting-name-or-id-parameters

**Comment by johnymachine** [comment]
Thanks for a tip, looks like some unfinished business here: https://github.com/Azure/azure-cli/blob/e843e2291a9b0dff264e11858c007fadf5a9a816/src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_validators.py

No trace of elastic pool validator.
