### ISSUE TITLE
[Diagnostics VMSS] Add support for private config. and update parameters

### ISSUE THREAD

**Issue by Skantha** [Azure/azure-cli#899]
For the "az vmss diagnostics set" command need to add additional parameters:
1. Private config (similar to extension command)
2. Other parameters similar to PowerShell

Sample PowerShell cmdlets for VMSS diagnostics
Add-AzureRmVmssDiagnosticsExtension -VirtualMachineScaleSet <VMSS> -SettingFilePath <String> [-ProtectedSettingFilePath <String>] [-Name <String>] [-TypeHandlerVersion <String>] [-AutoUpgradeMinorVersion <String>]
Remove-AzureRmVmssDiagnosticsExtension -VirtualMachineScaleSet <VMSS> [-Name <String>]

The default public config that should be used for Windows and Linux are attached.

[default_config.zip](https://github.com/Azure/azure-cli/files/475295/default_config.zip)

**Comment by mayurid** [comment]
@burtbiel as FYI
