### ISSUE TITLE
az account: 'create' is not in the 'az account' command group

### ISSUE THREAD

**Issue by fergara** [Azure/azure-cli#8991]
**Create Azure Enterprise subscriptions Programmatically**
I'm trying to use the "az account create" to create a new subscription via the azure cli. The az cli gives me a warning stating that the azure client account command does not have the "create" instruction.

**Description of Issue**
Using the following URL.
https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/azure-resource-manager/programmatically-create-subscription.md

azure-cl --> 2.0.61

Is it still in preview? What other options do I have?

Thanks,
Fernando

**Comment by tjprescott** [comment]
> To use this preview extension, install it by running az extension add --name subscription first.

You need to install the extension first.
