### ISSUE TITLE
Tab completion should not show 'empty' options

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#900]
if I do `az vm list -g [tab][tab]` it should only show resource groups that contain VMs

**Comment by johanste** [comment]
I would respectfully disagree. The same reasons apply to this as to the fact that standard shell tab completion includes directories with no files, or files that are empty. 

It may very well be that I'm running the command to ensure that there weren't any VMs in the resource group before I deploy a new template to said resource group (or create a new VM in the resource group using az vm create).

**Comment by JasonRShaver** [comment]
agree
