### ISSUE TITLE
Are QnaMaker cognitiveservices compatible with a linux service plan ?

### ISSUE THREAD

**Issue by MrLuje** [Azure/azure-cli#9004]
**Describe the bug**
A QnaMaker cognitiveservice created on a linux serviceplan cannot be linked to https://qnamaker.ai

![image](https://user-images.githubusercontent.com/632075/55613896-0d331400-578c-11e9-83c7-fc8aeda89cbb.png)

I used the commands from [this post (windows serviceplan version)](https://github.com/Azure/azure-cli/issues/6888#issuecomment-417817480) to create the cognitiveservices/webapp

**To Reproduce**
The differences with the working example are :
- is-linux flag on serviceplan
- "DOTNETCORE|2.1" on webapp
```
// Create resource group.
az group create --name devexp-qnamaker --location westus

// Create Search instance and get admin key.
// in this example, the key is "B044183F2450193E26751DC20423DFE4"
az search service create -g devexp-qnamaker -n devexp-qnamaker-search --sku standard
az search admin-key show -g devexp-qnamaker --service-name devexp-qnamaker-search

// Create App Service plan and Web App
// in this example, Web App endpoint will be https://devexp-qnamaker-webapp.azurewebsites.net
az appservice plan create -g devexp-qnamaker -n devexp-qnamaker-webapp-plan --is-linux --sku S1
az webapp create -g devexp-qnamaker -n devexp-qnamaker-webapp --plan devexp-qnamaker-webapp-plan --runtime "DOTNETCORE|2.1"

// Configure Web App
az webapp config appsettings set -g devexp-qnamaker -n devexp-qnamaker-webapp --settings 
    AzureSearchName=devexp-qnamaker-search 
    AzureSearchAdminKey=C6109F408309D28DCE72483FE50CAE86 
    PrimaryEndpointKey=devexp-qnamaker-webapp-PrimaryEndpointKey 
    SecondaryEndpointKey=devexp-qnamaker-webapp-SecondaryEndpointKey 
    DefaultAnswer="No good match found in KB." 
    QNAMAKER_EXTENSION_VERSION="latest"
    
az webapp cors add -g devexp-qnamaker -n devexp-qnamaker-webapp -a "*"

// Create QnAMaker account
az cognitiveservices account create -g devexp-qnamaker -n devexp-qnamaker-account --kind QnAMaker --sku S0 --location westus --api-properties qnaRuntimeEndpoint=https://devexp-qnamaker-webapp.azurewebsites.net
```
All resources are properly created at this point.

**Expected behavior**
The QnaService should be usable for a KB.
At this point, I'm not really sure if this is a known limitation of the current version of QnaMaker or bug

**Environment summary**
cf previous steps, commands done from cmd.exe on windows 10

**Comment by esoler-sage** [comment]
I'm interested in this scenario as well. Do you have any information about this?

**Comment by peterbozso** [comment]
Are there any updates on this? This scenario would be interesting for my customer.

**Comment by pravinambekar** [comment]
Are there any updates on configuring Linux based Cognitive Service for QnAMaker ? In my case LinuxFxVersion and Stack is correctly getting configured during deployment but, unable to create knowledgebase through script and throwing error about EndpointKeysError
