### ISSUE TITLE
Are there SKUs with no versions? What do they mean?

### ISSUE THREAD

**Issue by danielestevez** [Azure/azure-cli#9011]
Hi!
I was able to get some SKUs with apparently no version
```
$ az vm image list-skus --location canadaeast --publisher MicrosoftWindowsServer --offer servertesting
[
  {
    "id": "/Subscriptions/[SUBSCRIPTION_ID]/Providers/Microsoft.Compute/Locations/CanadaEast/Publishers/MicrosoftWindowsServer/ArtifactTypes/VMImage/Offers/servertesting/Skus/2016-datacenter",
    "location": "CanadaEast",
    "name": "2016-datacenter",
    "properties": {
      "automaticOSUpgradeProperties": {
        "automaticOSUpgradeSupported": false
      }
    },
    "tags": null
  }
]
```

```
$ az vm image show  --urn MicrosoftWindowsServer:servertesting:2016-datacenter:latest
Can't resolve the vesion of 'MicrosoftWindowsServer:servertesting:2016-datacenter'
```

What are those SKUs? Are they usable?

(Also there's a typo at can't resolve version/vesion error message :))

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90dfc804-87d6-913a-27fe-a9446a04eb13
* Version Independent ID: bfcb97df-2055-9eca-7a93-60811136d8cd
* Content: [az vm image](https://docs.microsoft.com/en-us/cli/azure/vm/image?view=azure-cli-latest#az-vm-image-show)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by adewaleo** [comment]
@danielestevez.

This is very strange. I investigated and it appears there are no images for that offer:

```
azure-cli tosin$ az vm image list-skus --location canadaeast --publisher MicrosoftWindowsServer --offer servertesting
[
  {
    "id": "/Subscriptions/00977cdb-163f-435f-9c32-39ec8ae61f4d/Providers/Microsoft.Compute/Locations/CanadaEast/Publishers/MicrosoftWindowsServer/ArtifactTypes/VMImage/Offers/servertesting/Skus/2016-datacenter",
    "location": "CanadaEast",
    "name": "2016-datacenter",
    "properties": {
      "automaticOSUpgradeProperties": {
        "automaticOSUpgradeSupported": false
      }
    },
    "tags": null
  }
]
azure-cli tosin$ az vm image list  --location canadaeast --publisher MicrosoftWindowsServer --all | grep "testing"
azure-cli tosin$ 

```

My guess is its some sort of internal testing sku. I will reach out to the Compute service team for clarification.

P.S. Thanks for catching and reporting the typo. I have created a [PR](#9025) to fix it.

cc: @yugangw-msft @kmoussa

**Comment by danielestevez** [comment]
It looks like some kind of internal testing so i think they shouldn't be exposed by the API?

**Comment by adewaleo** [comment]
> It looks like some kind of internal testing so i think they shouldn't be exposed by the API?

I agree @danielestevez, it seems like this might be a sku used for internal testing that is being leaked out.

**Comment by danielestevez** [comment]
Thanks @adewaleo !

**Comment by adewaleo** [comment]
I will be closing this not a CLI issue and it doesn't prevent users from working with regular vm images and skus.
Thanks for opening this @danielestevez. Please let me know if you have any questions. I have followed up / am currently following up with people on the service team on this.
