### ISSUE TITLE
Link to Docs for 'az appservice plan update' not showing correctly

### ISSUE THREAD

**Issue by gbellmann** [Azure/azure-cli#9012]
The link to Docs for 'az appservice plan update' not showing correctly, it's being shown as the HTML source text instead of the actual anchor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9dc8c24-cda6-8672-8017-b66435eadbb7
* Version Independent ID: a0be523a-ff1f-18ed-0fc4-ba0e0befe4d1
* Content: [az appservice](https://docs.microsoft.com/en-us/cli/azure/appservice?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py)
* Service: **app-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
@sptramer @dendeli-msft which repo should this go to? It seems like a general docs display issue.

**Comment by rloutlaw** [comment]
@tjprescott can you move this to https://github.com/MicrosoftDocs/feedback ?

**Comment by tjprescott** [comment]
Couldn't transfer it directly, but I created a new issue there. https://github.com/MicrosoftDocs/feedback/issues/1362

Closing this one. Thank @rloutlaw!
