### ISSUE TITLE
telemetry: include Azure CLI acquisition information in the user-agent

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#9013]
For us to know how people acquired CLI, like pip, bundle, curl? We need this information to help out with the decision that whether and when CLI can be Python3 only

//CC: @marstr

**Comment by tjprescott** [comment]
Additionally, it will allow our update message to be more useful when users run `az --version`.

**Comment by marstr** [comment]
Adding a little more context on how we've talked about doing this:
Many of our release channels create their own launcher script. We do this to accommodate different manners of acquiring Python. However, we can take advantage of this by setting an environment variable as we invoke the CLI.

Take our RPM spec for example:
https://github.com/Azure/azure-cli/blob/e241fd56c07a03445ea5d7db99a776696acfa3b3/scripts/release/rpm/azure-cli.spec#L69

would be come:
``` bash
printf '#!/usr/bin/env bash\nAZ_INSTALLER=RPM %{cli_lib_dir}/bin/python -Esm azure.cli "$@"' > %{buildroot}%{_bindir}/az
```

In Homebrew, our launcher would go from:
https://github.com/Azure/azure-cli/blob/a3cad860fe0e61f003ff4f3efdf0c4d3b955ebc1/scripts/release/homebrew/docker/formula_template.txt#L39-L42

to:

``` ruby
    (bin/"az").write <<~EOS
      #!/usr/bin/env bash
      AZ_INSTALLER=brew #{libexec}/bin/python -m azure.cli \"$@\"
    EOS
```

We could then take the value of `AZ_INSTALLER` and append it to our user agent.

**Comment by adewaleo** [comment]
this information would be helpful for az feedback as well!

**Comment by yonzhan** [comment]
add to S164.
