### ISSUE TITLE
az functioapp cors remove

### ISSUE THREAD

**Issue by shaochen** [Azure/azure-cli#9018]
with reference to https://github.com/Azure/azure-cli/issues/8514

`az functionapp cors remove -g {myRG} -n {myAppName} --allowed-origins *` doesn't remove all the allowed origins as suggested in the examples

`az functionapp cors remove -g {myRG} -n {myAppName} --allowed-origins` will clear all the allowed origins

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a3961a2-da0c-5697-b52d-35c8e676537d
* Version Independent ID: 3111fdd6-55ed-c1c8-7ac6-c4806a16945c
* Content: [az functionapp cors](https://docs.microsoft.com/en-us/cli/azure/functionapp/cors?view=azure-cli-latest#az-functionapp-cors-remove)
* Content Source: [src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py)
* Service: **functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ahmedelnably** [comment]
@panchagnula what is the intended behavior here?

**Comment by panchagnula** [comment]
@shaochen see this known issues on the documentation https://github.com/Azure/azure-cli/issues/8514  if the cors values is not set to * (i.e to allow all then it won't remove this) if you want remove all the values  run the command as az functionapp cors -g {} -n {} --allowed-origins

**Comment by shaochen** [comment]
I found it indeed, as referenced in a github issue. 
Thank you for pointing out that the behaviour I've reported is the behaviour you're suggesting.
Hover this is nowhere to be found in the documentation, for which the issue has been raised.

The suggestion is to properly document this "intended behaviour" so people don't need to sherlock holmes it from a github issue through google.

The existing documented example is at the very least ambiguous.
![image](https://user-images.githubusercontent.com/1136906/56528519-9f3e6900-654f-11e9-8d29-8496f14135b8.png)

**Comment by ahmedelnably** [comment]
@ankitkumarr

**Comment by ahmedelnably** [comment]
The example need to be updated, so the correct behavior is documented

**Comment by ahmedelnably** [comment]
tracked in https://github.com/Azure/azure-cli/pull/9700

**Comment by ahmedelnably** [comment]
This should be out in Sprint 64, will close when 2.0.68 is released
