### ISSUE TITLE
az aks get-credentials failure

### ISSUE THREAD

**Issue by MikeLangley68** [Azure/azure-cli#9019]
**Describe the bug**
While trying to pull the credentials for another azure environment I got an error messages as follows:
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 868, in emit
    msg = self.format(record)
  File "/home/mike/lib/azure-cli/local/lib/python2.7/site-packages/knack/log.py", line 78, in format
    msg = logging.StreamHandler.format(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 741, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 469, in format
    s = self._fmt % record.__dict__
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 172: ordinal not in range(128)

Upon further investigation I find that apt THINKS azure-cli 2.0.61 is installed, however, when I run az --version it reports that azure-cli (2.0.44) is installed. Furthermore, at the bottom of the version output I find that Python (Linux) is running a RC1 version 2.7.15.rc1 

Python (Linux) 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 

**To Reproduce**
az aks get-credentials -n integration-aks -g integration-aks

**Expected behavior**
I expected that the credentials for that environment would be copied to my local machine.

**Environment summary**
Azure-Cli tools where installed using apt onto Ubuntu 18.04. I expected that the current version would be 
2.0.61. When I run az --version I find the following:
azure-cli (2.0.44)

acr (2.1.3)
acs (2.3.0)
advisor (0.6.0)
ams (0.2.2)
appservice (0.2.2)
backup (1.2.0)
batch (3.3.2)
batchai (0.4.1)
billing (0.2.0)
cdn (0.1.0)
cloud (2.1.0)
cognitiveservices (0.2.0)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.3)
core (2.0.44)
cosmosdb (0.2.0)
dla (0.2.1)
dls (0.1.0)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.2)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.28)
iot (0.3.0)
keyvault (2.2.2)
lab (0.1.0)
monitor (0.2.2)
network (2.2.3)
nspkg (3.0.3)
profile (2.1.1)
rdbms (0.3.0)
redis (0.3.0)
reservations (0.3.1)
resource (2.1.2)
role (2.1.3)
search (0.1.1)
servicebus (0.2.1)
servicefabric (0.1.1)
sql (2.1.2)
storage (2.2.0)
telemetry (1.0.0)
vm (2.2.1)

Python location '/home/mike/lib/azure-cli/bin/python'
Extensions directory '/home/mike/.azure/cliextensions'

Python (Linux) 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0]

**Additional context**

**Comment by tjprescott** [comment]
You will need to update to the latest CLI. It sounds like you may need to uninstall an old version, potentially that was installed a different way. Try running `which az`. That should help identify where your executable is coming from.

**Comment by tjprescott** [comment]
I believe this particular bug is fixed, so I will close this. If it persists after you update, please reopen.

**Comment by MikeLangley68** [comment]
Travis,
It can't be fixed if I've uninstalled and reinstalled 3 times with the same exact results each time. What verion is the latest azure-cli version? 2.0.61? If so then your issue isn't fixed. It tells me to update to Python 3.6 or 3.7. I've done that but it doesn't help when you install a version of python 2.7.x and force the cli to use that version.

Thanks,
Mike Langley
________________________________

**Comment by tjprescott** [comment]
Yes, the latest version is 2.0.61. Is that the version you have installed?

**Comment by MikeLangley68** [comment]
Yes, I state that very clearly in my initial notes.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tjprescott** [comment]
Your initial report states that running `az --version` shows you are running 2.0.44, which means that even if you have 2.0.61 installed, it is clearly not being run.

You need to find the 2.0.44 installation and remove it. Please provide the output of `which az` and `pip list`. If the error persists when you are running version 2.0.61 then I will gladly reopen the issue and direct it to the AKS team.

**Comment by MikeLangley68** [comment]
Yes, but if you read the whole thing APT things it has 2.0.61 installed. As mitigation I removed the "y" folder and the az bash script in my bin folder. I've also cleaned up my .bashrc file. I've now reinstalled the azure-cli 2.0.61 but it doesn't know anything about the az command.
________________________________

**Comment by tjprescott** [comment]
I did read the whole thing and the bottom line is that it isn't running 2.0.61 whether it is installed or not, which is not an AKS issue and they won't be able to help you.

Again, please provide the output of `which az` and `pip list`. If you don't provide the requested information, there is nothing I can do to help you.

**Comment by MikeLangley68** [comment]
I removed everything for the cli and reinstalled and recreated the az bash file in my bin folder and pointed that at the /usr/bin/az. It seems that the install was trying to create the azure-cli under the lib folder again which was the bad version.

Look at this page: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest

**Comment by tjprescott** [comment]
So it sounds like you were able to get the latest version to run?  Does your issue persist?

**Comment by MikeLangley68** [comment]
yes, I had to recreate the plumbing but it seems to be working now. It didn't create an az bash file when I installed the 2.0.61 version. Should it have?

**Comment by tjprescott** [comment]
@MikeLangley68 I don't believe so, no. My best guess is that you installed the CLI some time ago potentially using a different mechanism (maybe the curl script) and that was the source of the trouble. We have an open issue to be able to identify how people installed the CLI so that we can avoid these kinds of headaches. https://github.com/Azure/azure-cli/issues/9013

**Comment by MikeLangley68** [comment]
At the time I don't believe that the azure-cli was being pushed any other way. In any case, I have now cleaned up all the nastiness that I believe the previous install created. Is there any documentation that exists that says what should have been installed where on Ubuntu 18.04 Bionic?

**Comment by tjprescott** [comment]
Generally speaking there is only the installation doc https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest
