### ISSUE TITLE
--os is no longer supported

### ISSUE THREAD

**Issue by TravisEz13** [Azure/azure-cli#9024]
I get this error when I use it `Docker build failed with: az.cmd : WARNING: Argument 'os_type' has been deprecated and will be removed in a future release. Use 'platform' instead.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c608162e-cf40-9d53-da4a-51f51a0311ea
* Version Independent ID: eccbb543-be68-7de2-d41d-abee55c81452
* Content: [az acr](https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest#az-acr-build)
* Content Source: [src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ehotinger** [comment]
@TravisEz13 How are you determining failure, anything on stderr instead of exit code? Otherwise what's the issue with the long-term deprecation?

**Comment by TravisEz13** [comment]
This is a doc bug.  The docs should say that you shouldn't use the switch.  Also, the error is not clear, as it says `os_type` when it is referring to `--os`

**Comment by ehotinger** [comment]
Can you point out what docs you're referring to? All the ones I checked out refer to platform, so I don't understand. The error can be improved for sure.

**Comment by TravisEz13** [comment]
It would be nice if when you filed a bug on the doc, it linked to the doc.  I'll try to find the doc.  I assume the docs are generated based on this python.

**Comment by ehotinger** [comment]
Hmm, yeah I'm not sure. I checked https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py and there's no mention of os, there's only platform.

**Comment by tjprescott** [comment]
@TravisEz13 if you make a comment from the docs page, it will be linked. However, in this case, we have already communicated to the docs team that they need to display the deprecation info that is in CLI and it is on their backlog. There is nothing in the CLI repo we can do about this as we are sending them the correct data.

@ehotinger to fix the message displayed in the CLI this is what needs to be changed:
current `deprecate_info=c.deprecate(redirect='platform', hide=True)`
change `deprecate_info=c.deprecate(target='--os', redirect='--platform', hide=True)`

**Comment by TravisEz13** [comment]
@ehotinger  do you mean why?  Because:
https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest#az-acr-build
![image](https://user-images.githubusercontent.com/10873629/56320025-102ced80-6118-11e9-8bbc-bf67782f6892.png)

**Comment by ehotinger** [comment]
@TravisEz13 ah okay, so just that it's showing up as an available option at all. I thought you meant it was in the samples. I think Travis answered your question for now then. @tjprescott thanks, will PR it in a bit.

**Comment by tjprescott** [comment]
With #9136 merged to fix the warning message, I will close this issue. Docs already has the item on their backlog to use the CLI's metadata. There is no action we can take form the CLI in this regard.
