### ISSUE TITLE
Please update to clarify CREATE options.

### ISSUE THREAD

**Issue by ThePhunny** [Azure/azure-cli#9026]
It might be useful to clarify that in az snapshot create --resource-group -g that it is the TARGET RG the snapshot will be created in not the location of the source.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fca6f8c5-a518-04ee-08e3-4ad8d4c9516e
* Version Independent ID: 17710c8c-9cd9-57ea-b6b0-1411648ea03f
* Content: [az snapshot](https://docs.microsoft.com/en-us/cli/azure/snapshot?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/snapshot.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/snapshot.yml)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by adewaleo** [comment]
@ThePhunny. Thanks for reaching out about this. This is the existing general pattern of the CLI
`--resource-group` is the destination of the resource to be created.
see the following commands and their examples:
- az vm create --help
- az storage account create --help
- az image create --help

This is why --source accepts **a name or ID** for source managed disks and snapshots. I

**Comment by adewaleo** [comment]
@ThePhunny 

Is there any way you think we could make this command clearer? Could an example showing snapshot creation from a source in a different resource group help?

**Comment by adewaleo** [comment]
Closing this as #9306 adds an example to `az snapshot create` that illustrates how to create a snapshot from a disk in a different resource group (via its resource ID).
