### ISSUE TITLE
Remove WEBSITE_CONTENTAZUREFILECONNECTIONSTRING and WEBSITE_CONTENTSHARE appsettings when creating linux consumption function apps

### ISSUE THREAD

**Issue by balag0** [Azure/azure-cli#9027]
https://github.com/Azure/azure-cli/blob/9ad476d1911b2c46351f142c6112516d66e2af85/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py#L2087

We no longer need this to be set.

**Comment by ankitkumarr** [comment]
@jeffhollan, we are removing `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` and `WEBSITE_CONTENTSHARE` for consumption. I remember we had added this for Premium as well. Do you know if we still need them for premium?

**Comment by jeffhollan** [comment]
Yes we need them for premium

**Comment by jeffhollan** [comment]
Premium linux and premium windows as well I believe

**Comment by ankitkumarr** [comment]
Ok, thanks Jeff!

**Comment by ankitkumarr** [comment]
Fixed by https://github.com/Azure/azure-cli/pull/9111. Can be closed
