### ISSUE TITLE
SSL Error when brew install azure-cli

### ISSUE THREAD

**Issue by curiousminion** [Azure/azure-cli#9030]
**Describe the bug**
az login throws error: Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/token (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')])")))

**To Reproduce**
run brew install azure-cli
as of this time of submitting bug: 
mycomputer:~ myuser$ az --version
azure-cli                         2.0.61

**Expected behavior**
az login should login successfully after authentication passed. 

**Environment summary**
using new setup Mac OS Mojave.  Has python 3.6.5, was also tried with python 3.7.3

**Additional context**
Here is the full dump from my terminal attached:
[SSLError_BREW-install_azure-cli.txt](https://github.com/Azure/azure-cli/files/3056866/SSLError_BREW-install_azure-cli.txt)

Eventually I choose to use the manual installation using command:  
$ curl -L https://aka.ms/InstallAzureCli | bash
which was working right away. 

Someone should take a look on the brew install for azure-cli, so other users will not wasting trying to troubleshoot whether it is the python3, certifi, openssl, pyopenssl, etc.

**Comment by achandmsft** [comment]
Thanks for your feedback @smurf2smurf! 

@marstr, FYI. I wonder if this is the same issue mentioned in #9054?

**Comment by marstr** [comment]
Howdy @smurf2smurf,

IS this still reproing for you? I believe there were some known SSL problems with the federated AAD servers right around when you posted this. Could be unrelated though, I'm curious to hear back.

**Comment by marstr** [comment]
Another thing to take a look is our troubleshooting guide when working through proxy issues: https://github.com/Azure/azure-cli/blob/43daaefc5da67ab7a39e0d78ca475a11fb45edb3/doc/use_cli_effectively.md#working-behind-a-proxy

**Comment by smurf2smurf** [comment]
Ah... I did this over span of multiple days of switching to new machine.  I gave up using brew and eventually just use the curl install for azure cli.It should easy to reproduce if you can get access to new machine.  

    On Friday, April 19, 2019, 10:11:15 AM PDT, Martin Strobel <notifications@github.com> wrote:  
 
 
Another thing to take a look is our troubleshooting guide when working through proxy issues: https://github.com/Azure/azure-cli/blob/43daaefc5da67ab7a39e0d78ca475a11fb45edb3/doc/use_cli_effectively.md#working-behind-a-proxy

**Comment by curiousminion** [comment]
Hi - is there any update on this?  there have been many users in our company that use Mac and a lot of people reporting same issue.   For now, we are following the step to install manually on linux with the curl (https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos?view=azure-cli-latest#other-installation-methods) - which also have a NOTE: **... Note that this process is not officially maintained to be compatible with macOS...**

**Comment by yonzhan** [comment]
@fengzhou-msft please take a look and comment.

**Comment by fengzhou-msft** [comment]
@curiousminion starting from 2.0.72, azure-cli upgraded to openssl 1.1. please run `brew update` and `brew upgrade azure-cli` to install the lastest version to retry. let me know if you still have the SSL error after upgrade.

**Comment by fengzhou-msft** [comment]
@curiousminion Please also check for network settings, such as using a corporate proxy. Here's some tips for working behind a proxy: https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy

**Comment by yonzhan** [comment]
@curiousminion  We did not receive your response for a while. We will close this issue right now. If any further question, please open a new issue.
