### ISSUE TITLE
az aks scale fails when using CustomVnet + kubenet

### ISSUE THREAD

**Issue by brusMX** [Azure/azure-cli#9038]
**Describe the bug**

When deploying a cluster with Custom VNET + kubenet, we are unable to run the scale command on it if we provided custom values for the serviceCIDR and/or the DNS service IP.​

```bash
az aks scale -g aks-20180614f --name aks-20180614f --node-count 5 

> Operation failed with status: 'Bad Request'. Details: Changing property 'networkProfile.dnsServiceIP' is not allowed.​
```

**To Reproduce**

Deploy the cluster with custom `serviceCIDR` and custom DNS Service IP and Kubenet plugin.
​Try to scale the cluster using `az aks scale`

**Expected behavior**

The cluster should create new vms in the specified CIDRs

**Environment summary**

Azure CLI > 2.0.61 but any should be

**Additional context**

This problem is probably underlying somewhere deeper than in the Azure CLI

**Comment by palma21** [comment]
I tested this and could not repro on latest. Could you confirm if you still experience on latest?

**Comment by yonzhan** [comment]
aks
