### ISSUE TITLE
Az account set switches the user logged on 

### ISSUE THREAD

**Issue by mariojacobo** [Azure/azure-cli#9045]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior. 

Create a service principal and use that to login 
$ az login --service-principal -u "app-url" --password "password" --tenant "tenant" --allow-no-subscriptions

{
    "cloudName": "AzureCloud",
    "id": "REDACTED",
    "isDefault": true,
    "name": "N/A(tenant level account)",
    "state": "Enabled",
    "tenantId": "REDACTED",
    "user": {
      "name": "https://xxx.onmicrosoft.com/REDACTED",
      "type": "servicePrincipal"
    }
  }
]

Set a default subscription: 
$ az account set -s "subscriptionID" 

User has switched: 
$ az account show 
{
  "environmentName": "AzureCloud",
  "id": "REDACTED",
  "isDefault": true,
  "name": "REDACTED",
  "state": "Enabled",
  "tenantId": "REDACTED",
  "user": {
    "name": "REDACTED",
    "type": "user"
  }
}
**Expected behavior**
The user principal credentials should persist when setting the subscription 

**Environment summary**
CentOS 7.5
azure-cli  2.0.62

**Additional context**

**Comment by mariojacobo** [comment]
after more testing, it looks like this is due to missing permissions on the subscription in question. So, I need to add the service principal to that subscription first, then login (remove --allow-no-subscriptions) and then set the subscription. Kind of backwards if you ask me, defeats the whole purpose of automation with AZ cli.

**Comment by achandmsft** [comment]
Hi @mariojacobo, 
Thanks a lot for your feedback! We are looking into this issue. In the meantime, could you please let us know what is your specific automation scenario? For several automation scenarios, we recommend using [Managed Identity](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview) if it is supported by the related Azure resources. 

We provide a --identity parameter in [az login](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-login) specifically for such scenarios. 

Please let me know if that helps solve your issue? 

Thanks,
Arun Chandrasekhar
Principal Program Manager 
Azure Management Experience

**Comment by mariojacobo** [comment]
That's not going to work for us. "--identity" is for VMs, but we don't have any , so not sure how that applies to the issue.
