### ISSUE TITLE
webapp: try not to use pycurl for live trace streaming

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#905]
@haoc, for you get ramp up :-)
It would be great to use built-in http modules or the requests to accomplish it, so that we don't need to pull in the pycurl  
The code is [here](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-webapp/azure/cli/command_modules/webapp/custom.py#L306)

/CC:@derekbekoe

**Comment by derekbekoe** [comment]
If we are going to use pycurl before our next release, we should add the dependency to our documentation (for the distributions that need it).

**Comment by yugangw-msft** [comment]
For background, the reason to use pycurl is per kudu's [document](https://github.com/projectkudu/kudu/wiki/Diagnostic-Log-Stream) , which calls out using `curl`

**Comment by haocs** [comment]
https://github.com/kennethreitz/requests/issues/3577 Some discussions of the issue that blocks replacing pycurl. Still trying to figure out how to let requests print data chunk by chunk as curl does.

**Comment by yugangw-msft** [comment]
Appears fixed. Thanks @haocs !
