### ISSUE TITLE
Ability to list resources by multiple tags

### ISSUE THREAD

**Issue by itelligence** [Azure/azure-cli#9060]
At the moment when you request resource list you are only allowed to request list based only on single tag. 

`az resource list --tag foo=bar`

Ideally it would be nice to request that list by specifying multiple tags to narrow down the results you wish to retrieve.

`az resource list --tag foo=bar --tag foo2=bar2`

**Comment by achandmsft** [comment]
Hi Jacek (@itelligence),
Thanks a lot for your feature request! To better prioritize this request, can you give me some specific real world cases where you think this will be valuable? 

Thanks,
Arun Chandrasekhar
Principal Program Manager
Azure Management Experience

**Comment by itelligence** [comment]
Hi Arun,

For example, in my case where we primarily use Azure Cognitive Search subscriptions, we provide various search feeds to our clients based on type of search they perform and at the same time to optimise subscription costs.

So we have few subscriptions of S2, S3, S4 and S5. These could related to web, images, video and news. We then assign tags such as feed_id and category.
By adding tags feed_id and category this will allow us to get subscriptions based on these tags and then perform reports based on just these subscriptions. Each feed_id is related to a client.
So I could request feed_id=1222 and category=web. This will provide me all the subscriptions just for these tags.
Currently you can only request a single tag and then you need to filter through each subscription and determine which is which.

Hope this makes sense.

Regards, 
Jacek

**Comment by tjprescott** [comment]
Assigning to @kristapratico. This filter is done server-side with OData. The first important question is whether the service will support filtering by multiple tags. If so, it would be feasible for us to unblock this scenario.

**Comment by yonzhan** [comment]
@kristapratico  any update for this issue?

**Comment by kristapratico** [comment]
@yonzhan I'm no longer on the CLI team, this should be reassigned.

**Comment by yonzhan** [comment]
@kristapratico  thanks. Do you know who from ARM team can look into this issue?

**Comment by rthorn17** [comment]
@leylakazemi  - Can you and the team take a look at this please.  Thanks

**Comment by yonzhan** [comment]
@leylakazemi  any update for this?

**Comment by leylakazemi** [comment]
This work has not been planned, I just created a uservoice item for this, and will add it to our backlog.
https://feedback.azure.com/forums/281804-azure-resource-manager/suggestions/39741979-ability-to-list-resources-by-multiple-tags

**Comment by cnaslainpro** [comment]
@leylakazemi the above URL no longer exists. Can you tell me if this was taken into account? Was it added to a specific version?
