### ISSUE TITLE
vnet create should allow creation of multiple subnets

### ISSUE THREAD

**Issue by DenisBiondic** [Azure/azure-cli#9065]
**Describe the bug**
az network vnet create is idempotent, and this is ok. If you run vnet create on a vnet with multiple existing subnets however, the subnets will be deleted; and altough this is also expected behaviour, there should be a way to create a vnet with mutliple subnets at the same time. Similar approach exists in Azure Python SDK create_or_update method, so why not expose it in CLI as well?

**To Reproduce**
az network vnet create --name myvnet ... 
az network vnet subnet create --name subnetA ...
az network vnet subnet create --name subnetB ...
az network vnet subnet create --name subnetC ...
az network vnet create --name myvnet ...  # the subnets a, b & c are gone, there is not way to implement idempotentcy correctly with azure CLI and vnets with multiple subnets (without relying on if statements etc.)

**Expected behavior**
az network vnet create should allow creating multiple subnets at the same time

**Environment summary**
CLI Version: 2.0.62

**Comment by tjprescott** [comment]
The ability to create any subnets at the time of Vnet creation was always intended purely as a convenience for those who only cared about getting a vnet with some subnet. For multiple subnets, the intention has always been to require multiple commands, because the subnet create command itself has many parameters. 

We are working on an infrastructure level feature that would support your scenario though. Please keep an eye on https://github.com/Azure/azure-cli/issues/8055.

**Comment by jboeshart** [comment]
Upvote for this. We could benefit from this feature on Microsoft Learn to simplify the steps required to create resources. Came here to see if this exact feature had been requested, would be great to have.

**Comment by voltaire-ilustrisimo-webjet** [comment]
+1 This feature makes building up my vnet much easier.

**Comment by tjprescott** [comment]
We do not plan to implement this request. The subnet create command contains many parameters. Trying to support all of those features on vnet create is impractical, and not supporting those features means the user would need to follow up with just as many update commands to configure them.

In regards to idempotency, simply running:
```
az network vnet create --name myvnet ...
az network vnet subnet create --name subnetA ...
az network vnet subnet create --name subnetB ...
az network vnet subnet create --name subnetC …
```

Will ensure that the vnet is set up correctly each time without relying on if statements. Recent changes will allow you to do the following to minimize the network calls you make to Azure:

```
az network vnet create --name myvnet ... --defer
az network vnet subnet create --name subnetA ... --defer
az network vnet subnet create --name subnetB ... --defer
az network vnet subnet create --name subnetC …
```
