### ISSUE TITLE
az storage blob generate-sas returns double url-encoded sas token

### ISSUE THREAD

**Issue by dlott** [Azure/azure-cli#9072]
**Describe the bug**
sas token returned is incorrectly double url-encoded in azure-cli 2.0.62

**To Reproduce**
`az storage blob generate-sas --container-name foo --name bar --account-name baz --expiry 2020-04-10T10:44:56Z --permissions r`

returns

`"se=2020-04-10T10%253A44%253A56Z%26sp=r%26sv=2018-03-28%26sr=b%26sig=[omitted]"`

**Expected behavior**
Previously in azure-cli                         2.0.61 it returned
`"se=2020-04-10T10%3A44%3A56Z&sp=r&sv=2018-03-28&sr=b&sig=[omitted]"`

**Environment summary**
Confirmed broken installing 2.0.62 via `curl -L https://aka.ms/InstallAzureCli | bash` and apt-get install azure-cli on Ubuntu 16.04

**Comment by dlott** [comment]
Thanks for the quick fix.  In the interim, as a workaround, I've been manually url decoding the current token and it usually works.  Sometimes however, I've noticed if the token contains a `/` (forward slash) it is doubled as `//`.  Is that also fixed with this commit?  Or is that a separate issue?

**Comment by mkowalskigps** [comment]
Another potential workaround is to use the new `--full-uri` flag (if you need to full URI) as that does not double escape the token.
