### ISSUE TITLE
403 Error when creating AKS cluster.

### ISSUE THREAD

**Issue by mgrabarz** [Azure/azure-cli#9080]
CLI version 2.0.62 with AKS-Preview extension (0.3.0)

**Describe the bug**
I am **able to create AKS** cluster **from portal**, but **cannot create it with CLI** due to 403 error. Error states that I'm lacking 'resourceGroups/write' permission on linked scope 'providers/Microsoft.ContainerService/managedClusters/azureuser' in the same resource group.

The "azureuser" is unexpected and this is linux node ssh user, not a cluster name. 

**To Reproduce**
1. See additional context to setup user permissions
2. Deploy cluster with CLI
`az aks create 
    --resource-group rgname 
    --name clustername
    --node-count 3 
    --kubernetes-version 1.12.7 
   --node-vm-size Standard_DS2_v2 
    --generate-ssh-keys`
3. I receive following error:
`The client '...' with object id '…’ has permission to perform action 'Microsoft.ContainerService/managedClusters/write' on scope '/subscriptions/…/resourceGroups/.../providers/Microsoft.ContainerService/managedClusters/clustername'; however, it does not have permission to perform action 'Microsoft.Resources/subscriptions/resourceGroups/write' on the linked scope(s) '/subscriptions/…/resourceGroups/.../providers/Microsoft.ContainerService/managedClusters/azureuser'.`
4. When I add extra parameter --admin-username azureuser2 error is following:
`The client '...' with object id '…’ has permission to perform action 'Microsoft.ContainerService/managedClusters/write' on scope '/subscriptions/…/resourceGroups/.../providers/Microsoft.ContainerService/managedClusters/clustername'; however, it does not have permission to perform action 'Microsoft.Resources/subscriptions/resourceGroups/write' on the linked scope(s) '/subscriptions/…/resourceGroups/.../providers/Microsoft.ContainerService/managedClusters/azureuser2'.`

**Expected behavior**
I believe CLI checks extra permissions that are not needed for deployment (portal deployment works). Probably there is formatting bug that substitutes --admin-username instead of --name somwhere in the code.

**Environment summary**
Windows 10, 1803

**Additional context**
My AAD user has custom role on RG where AKS is deployed.
- Contributor permission to all resources in RG
- No resourceGroup/write permission – to avoid changing RG properties, e.g. tags.

**Comment by moulla** [comment]
Similar on linux azure-cli.x86_64 0:2.0.68-1.el7

**Comment by lilyjma** [comment]
@Azure/aks-pm please take a look!

**Comment by navba-MSFT** [comment]
@mgrabarz Apologies for the late reply. While creating the AKS cluster, ensure that the identity you are using to create your cluster has the appropriate minimum permissions. For more details on access and identity for AKS, see [Access and identity options for Azure Kubernetes Service (AKS)](https://docs.microsoft.com/en-us/azure/aks/concepts-identity). This issue thread is open for quite sometime. Please let me know if you need any further assistance on this. Awaiting your reply.

**Comment by mgrabarz** [comment]
After 3 years, number of cli releases and aks part being ga'ed I don't think this issue is still there.

If you believe it requires investigation, please do it - you have repro steps. If you read it carefully you would notice that issue isn't about my user permissions.

**Comment by mgrabarz** [comment]
Please close this issue, i don't think it is still there.

**Comment by mgrabarz** [comment]
Please note, that issue was about incorrect cli parameter handling (--azure-user) not permissions :)

**Comment by navba-MSFT** [comment]
@mgrabarz Thanks for your reply. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
