### ISSUE TITLE
Create CLI Support For Shared Image Gallery GA

### ISSUE THREAD

**Issue by vanbasten2323** [Azure/azure-cli#9081]
**Resource Provider**
What is the Azure resource provider your feature is part of?
Azure.Compute

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
We need help from CLI team to generate CLI tooling for Shared Image Gallery service from our new swagger file. The new swagger file contains a new api-version and a few new API fields: https://github.com/Azure/azure-rest-api-specs/pull/5528

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
2018-06-01

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. This should be on the master branch
of the REST API specs repo.
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-03-01/gallery.json

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.
We'll be GA at April 22, 2019. It would be great if we can have a CLI tooling before that date.

**Comment by adewaleo** [comment]
addressed in #9105
