### ISSUE TITLE
New "az webapp up" change which launches default browser cannot be turned off

### ISSUE THREAD

**Issue by dsparkplug** [Azure/azure-cli#9086]
**Describe the bug**

As of commit 02afe0a9cd1cfcae7fcad9e9924757fcf40e946a the command `az webapp up` automatically launches the URL of the new web app in the default browser (line 2420 in [/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py](https://github.com/Azure/azure-cli/blob/02afe0a9cd1cfcae7fcad9e9924757fcf40e946a/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py)).

While this can be useful in general use, it is a significant issue when running from an automated tool such as a CI server. There does not appear to be any option to turn this off.

**To Reproduce**

run `az webapp up --name MyFancyWebApp` 

**Expected behavior**

There needs to be an option to turn off this new feature. This should also be listed as a breaking change in the release notes.

**Comment by panchagnula** [comment]
@limingu we made this change since this was one of the top requests for az webapp up -> Noted about the breaking change update on the documentation. Let me run this with our team & update the thread

**Comment by limingu** [comment]
@dsparkplug , the previous message is for you.

**Comment by panchagnula** [comment]
we will add a parameter to make launching in browser an optional parameter.
