### ISSUE TITLE
az group deployment template parse error unhelpful

### ISSUE THREAD

**Issue by tbertenshaw** [Azure/azure-cli#9087]
`azure-cli version 2.0.62`

when running `az group deployment create` with a scaleset template file it appears to parse the template file ok. Running it with debug i can see it creates a json file with the template section and parameters section which watches what i expect from my inputs. It even validates in the Azure Portal Templates if i create a new template and paste the json in. However it errors with an error which makes it very difficult to establish where the fault lies `"Deployment template parse failed: 'Error reading string. Unexpected token: StartObject. Path 'name'.'.",`

Is there a way of getting a better location for the error?

Below is the end of the output from `az group deployment validate` (i dont appear to get any better output when i run `create` or `validate` with `--debug`

```
msrest.http_logger : Response content:
msrest.http_logger : {"error":{"code":"InvalidTemplate","message":"Deployment template parse failed: 'Error reading string. Unexpected token: StartObject. Path 'name'.'."}}
Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x03B60C00>, <function _x509_from_base64_to_hex_transform at 0x03B60C48>]
Event: CommandInvoker.OnFilterResult []
{
  "error": {
    "code": "InvalidTemplate",
    "details": null,
    "message": "Deployment template parse failed: 'Error reading string. Unexpected token: StartObject. Path 'name'.'.",
    "target": null
  },
  "properties": null
}
```

**Comment by tjprescott** [comment]
Thank you for your report @tbertenshaw. We will notify the service team of your feedback, as they control the error message emitted in this scenario.

**Comment by tbertenshaw** [comment]
I've found my error but as above the error message made it quite difficult to diagnose

This was in my template
```
 "sku": {
        "name": "parameters('vmSku')"
        "tier": "Standard",
        "capacity": 1
      },
```
but after my variable contained an object of the sku rather than `Standard_DS1_v2` for example so the resulting transformed template was

```
 "sku": {
        "name": {
                "name": "Standard_DS1_v2",
                "tier": "Standard",
                "capacity": 1
            },
        "tier": "Standard",
        "capacity": 1
      },
```
rather than
```
 "sku": {
        "name": "Standard_DS1_v2"
        "tier": "Standard",
        "capacity": 1
      },
```
If it could have told me what line or column or surrounding object or something i could have worked it out much sooner.

**Comment by alex-frankel** [comment]
Hi,

We are working on a fix now that will return line number and position number when there is an error in deployment. Will update this once the feature is released.

Thanks,
Alex

**Comment by alex-frankel** [comment]
You should now be getting line and position numbers when this template is validated. @tbertenshaw If possible, can you try reproducing the issue? I will plan to close this if I don't hear back.
