### ISSUE TITLE
NSG support for additional protocols

### ISSUE THREAD

**Issue by malopMSFT** [Azure/azure-cli#9090]
**Resource Provider**
Microsoft.Network

**Description of Feature or Work Requested**
Accepting new protocol on NSG security rules: 'Icmp'

**Minimum API Version Required**
2019-02-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/5582/files
Note: 'Esp', 'Ah' are not ready yet, only ICMP for now

**Target Date**
May release

**Comment by tjprescott** [comment]
Hi @malopMSFT to clarify, do you need this request in for Build?

**Comment by malopMSFT** [comment]
Not required for //Build

Updated the list, it's only 1 protocol for now ICMP
