### ISSUE TITLE
Weird characters when using Azure VM (Linux-Ubuntu)

### ISSUE THREAD

**Issue by Kunalkatdare** [Azure/azure-cli#9091]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Bug Description**
I am seeing weird characters in my azure VM CLI when I type 'ls'.
Also, when hitting backspace, I see weird characters popping up

**To Reproduce**
After using ssh to login to the VM, I usually like to see a list of my directories.
When I type **ls** I see weird characters along with the expected output.
Please see the screenshot for reference.
![azure](https://user-images.githubusercontent.com/15366226/56050894-07ed4080-5d1b-11e9-80df-fef9ec59caa5.PNG)

**Environment summary**

     
/0                   bus        Motherboard
/0/0                 memory     7977MiB System memory
/0/1                 processor  Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
/0/100               bridge     440BX/ZX/DX - 82443BX/ZX/DX Host bridge (AGP dis
/0/100/7             bridge     82371AB/EB/MB PIIX4 ISA
/0/100/7.1           storage    82371AB/EB/MB PIIX4 IDE
/0/100/7.3           bridge     82371AB/EB/MB PIIX4 ACPI
/0/100/8             display    Hyper-V virtual VGA
/1          docker0  network    Ethernet interface
/2          eth0     network    Ethernet interface

**Comment by tjprescott** [comment]
@Kunalkatdare you will need to open a support ticket to engage with the service team. This repository is only for issues related to the Azure CLI and its commands.
