### ISSUE TITLE
az webapp config storage-account add with slot settings return 'Not Found'

### ISSUE THREAD

**Issue by kimsk** [Azure/azure-cli#9092]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
The command returns `Operation returned an invalid status code 'Not Found'` and the configurations was not updated.

**To Reproduce**
``` PowerShell
az webapp config storage-account add `
-g $resourceGroup `
-n $appServiceName `
-s staging `
--slot-setting
--account-name $storageAccountName `
--access-key $accessKey `
--storage-type AzureFiles `
--share-name $shareName `
--mount-path $mountPath `
--custom-id $customId `
```

**Expected behavior**
The storage account configurations for a specific AppService/Slot is updated successfully.

**Environment summary**
Install Method **chocolatey**
CLI version **2.0.62**
OS version **Windows 10**
Shell Type **PowerShell**

**Additional context**
1. `az webapp config storage-account list -g $resourceGroup -n $appServiceName -s staging` returns `[]`
2. I also try setting this via portal (which doesn't have slot setting checkbox) and settings were not saved (although the portal said that the settings was updated)

**Comment by panchagnula** [comment]
@kimsk i am unable to repro this on CLI - can you re-try and let me know if you are still seeing this.
If so will you be willing to share the name of the app so that we can check the logs on our end? 

Alternately you can run the command with --debug flag at the end & see if you see any specific error returned on your end & just share this info as well. Thanks again.

**Comment by kimsk** [comment]
@panchagnula thanks for the information. I tried creating new linux container appservice, and I can mount the storage to slot deployments without any issue. So I think it could be our specific settings and not the `azure-cli` issue. If we continue experiencing the issue, we will submit a ticket to our Azure support directly.

**Comment by panchagnula** [comment]
@Kimsk thanks for the update on this.
