### ISSUE TITLE
az resource delete doesn't delete a vnet

### ISSUE THREAD

**Issue by DevSE99** [Azure/azure-cli#9104]
## Describe the bug

**Command Name**
`az resource delete`

**Errors:**

:open_mouth:

```The command failed with an unexpected error. Here is the traceback:

'subscription'Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 326, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 384, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 377, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 354, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 145, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 451, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/resource/custom.py", line 875, in delete_resource
    error_msg_builder.append(resource_dict_to_id(**id_dict))
  File "/opt/az/lib/python3.6/site-packages/msrestazure/tools.py", line 206, in resource_id
    rid_builder = ['/subscriptions/{subscription}'.format(**kwargs)]
KeyError: 'subscription'
```

## To Reproduce:
Steps to reproduce the behavior. Note: Command arguments have been redacted.

- `Fill in additional info here`
- `Run: az resource delete -g {} --ids {}`

## Environment Summary
```
Linux-4.15.0-1041-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli                         2.0.62

Extensions:
dev-spaces-preview                 0.1.6

Python location '/opt/az/bin/python3'
Extensions directory '/home/roland/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Apr  4 2019, 22:51:52)
[GCC 5.4.0 20160609]

```

**Comment by DevSE99** [comment]
--ids /subscriptions/24a10425-c230-4b86-8ddd-0f3d3b9c64e7/resourceGroups/weareone/providers/Microsoft.Network/virtualNetworks/miitya-vnet

**Comment by tjprescott** [comment]
If you provide `--ids` you should not provide `-g`

**Comment by tjprescott** [comment]
I will update the CSV to issue a proper error rather than a stack trace.

**Comment by DevSE99** [comment]
Now it's shown a proper message "Azure Error: InUseSubetCannotBeDeleted". But this doesn't solve the problem that I still can't delete the vnet. The subnet is not connected to any running service, but was connected to a ACI. Other networks can be deleted without problems.

**Comment by tjprescott** [comment]
You would need to the delete the ACI and try again. There is nothing the CLI can do if the service fails to delete the resource. You could try opening a support ticket in the portal.

**Comment by DevSE99** [comment]
Ok, thanks. The ACI is not there anymore, was deleted by me long time ago.

**Comment by tjprescott** [comment]
@DevSE99 that can be super frustrating I know. In that case, your case sounds to me like something the service team needs to investigate. I think a support ticket from portal is your best bet. I'd like to leave this issue as is so that way we can ensure an actionable error is thrown when using `--ids` in conjunction with `-g`. Otherwise I'd repurpose this ticket as a ServiceAttention item. But honestly, for your situation, the support ticket is the best option.

**Comment by tjprescott** [comment]
Reassigning to @kristapratico. For this issue, it will just be adjusting the error handling so something actionable is emitted and not a stack trace.

**Comment by DevSE99** [comment]
@tjprescott Thank you for your support. I will open a support ticket from the portal.

**Comment by navba-MSFT** [comment]
@DevSE99 Apologies for the late reply. This github issue has been open for quite sometime. Could you please let us know if you need any further assistance on this ?

**Comment by navba-MSFT** [comment]
@tjprescott @kristapratico Please update this thread if you had a chance to look into the this.

**Comment by tjprescott** [comment]
@navba-MSFT neither @kristapratico nor myself are on the CLI team anymore. If necessary, it should be reassigned.
