### ISSUE TITLE
ACR Health Diagnose

### ISSUE THREAD

**Issue by ni-reis** [Azure/azure-cli#9112]
## Problem

It is a common situation for customers to face an issue when dealing with containers that can be solved by themselves (like docker daemon failures or authorization  issues), but as there's a lack of guidance, they end up contacting the Azure Container Registry team. Although issues end up being fixed, they can take, for example, one day when they could be solved in one hour.

## Solution

It would be good if `az acr` command line had a command (such as `az acr health check`), that can check, among other things, if:
1) registry is online and discoverable
2) docker daemon is running as expected
3) try to download a sample image to check that `docker pull` is running as expected
4) authenticate credentials

## Additional Context

```
$ az acr health check -n myregistry
DNS lookup to myregistry.azurecr.io 123.123.23.23. : OK
AAD Token acquisition : OK
Upload test : OK
Correlation Id : 1234123012341231234
```

More information can be found [here](https://gist.github.com/sajayantony/699ecfc299293220bb533f036e9b845f).

**Comment by yugangw-msft** [comment]
Your contribution of https://github.com/Azure/azure-cli/pull/9459 handled it
