### ISSUE TITLE
--expiry default value is the current datetime

### ISSUE THREAD

**Issue by daxianji007** [Azure/azure-cli#9114]
**Describe the bug**
I run `az ams asset get-sas-urls -h`. The default value of `--expiry` changes every time and seems it is equal to the current datetime. Is that something by-designed?

**To Reproduce**
Install azure-cli
run `az ams asset get-sas-urls -h`
The default value of `--expiry` changes every time

**Expected behavior**
Maybe it should be an constant value or more clear description?

**Environment summary**
Azure CLI 2.0.62

**Comment by hivyas** [comment]
Hi there, the default value for the `--expiry` parameter is a little less than 24 hours from the current datetime. The SAS url is where users can upload a video and for security purposes it shouldn't be available for more than 24 hours later. I submitted a PR to update the help text for the variable to make it more understandable. Thanks
