### ISSUE TITLE
[Profile] If profile is saved in UTF-8, it won't load

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#912]
Somehow I got into a state where my azureprofile.json file was saved in UTF-8, which failed to load on one of my environments.  We should use the json loader code to load json from multiple encodings similar to how we do for template deployment command

**Comment by yugangw-msft** [comment]
@BurtBiel , can you provide the broken profile file? The azureProfile's load is handled through python Session object. Also how recent is your local clone, particularly whether you have the change from #897

**Comment by BurtBiel** [comment]
@yugangw-msft Ah, I think the branch I'm testing hasn't been rebased to include that change yet.  I'll reopen if I run into it again

**Comment by yugangw-msft** [comment]
@BurtBiel , sounds good

**Comment by yugangw-msft** [comment]
repro'd in @BurtBiel machine. We need to investigate

**Comment by yugangw-msft** [comment]
The error is from `adal-python` on formatting error strings. I will fix that.

**Comment by yugangw-msft** [comment]
will close once new adal-python gets published

**Comment by yugangw-msft** [comment]
adal 0.4.1 was published and integrated in azure-cli. Running dev_setup should get it.
