### ISSUE TITLE
Missing comma in the role definition example

### ISSUE THREAD

**Issue by Charmendar** [Azure/azure-cli#9121]
Should be a comma after "Description": "Perform VM actions and read storage and network information."  and before "Actions" in the example code. Otherwise JSON is not loaded properly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40e649cf-40e3-1b9e-141a-c62d244eda61
* Version Independent ID: 78ea89c1-7c56-e33b-d10a-dae05642aa34
* Content: [az role definition](https://docs.microsoft.com/en-us/cli/azure/role/definition?view=azure-cli-latest#az-role-definition-create)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
@Charmendar thank you for the report!
