### ISSUE TITLE
az extension add has an Unicode display issue

### ISSUE THREAD

**Issue by limingu** [Azure/azure-cli#9122]
**Describe the bug**
az extension add has an Unicode display issue

**To Reproduce**
Steps to reproduce the behavior.
az extension add --name azure-devops

**Expected behavior**

**Additional context**
has an Unicode display issue

**Comment by limingu** [comment]
![unicode](https://user-images.githubusercontent.com/48228819/56243910-87974a00-6050-11e9-9047-dce1835a3e35.png)

**Comment by adewaleo** [comment]
I will add this command was an issue on the command prompt

**Comment by tjprescott** [comment]
What is the python version?

**Comment by atbagga** [comment]
This is duplicate of #9140 

I haven't been able to get to it. I will try to debug and raise a fix soon. 
FYI.. The issue is on Windows only.

**Comment by yonzhan** [comment]
add to S164.

**Comment by jiasli** [comment]
Fixed by #9660
