### ISSUE TITLE
Inbound NAT pools are Poorly documented.

### ISSUE THREAD

**Issue by Know1** [Azure/azure-cli#9123]
After much head-scratching I finally figured out these do not work as I thought they would.
I thought they were a quick way to map multiple inbound ports to multiple backend ports on the same VM or VMs. This is not the intent and function of Inbound NAT pools.

Documentation requires clarification of the actual function of Inbound NAT pools.
Something like the following.

Inbound NAT pools are for use in VM Scale Sets. They create a pool of inbound ports for use by the dynamic number of VMs to use Theymap all the inbound ports to the same backend port on each VM in the scale set.
e.g. az network lb inbound-nat-pool create --resource-group "MyGroups" --lb-name "MyLB" --name "NAT_to_LB" --protocol Tcp --frontend-port-range-start 100001 --frontend-port-range-end 10010 --backend-port 3389
This would create the following:
  FE tcp/10001 -&gt; VM01 tcp/3389
  FE tcp/10002 -&gt; VM02 tcp/3389
  FE tcp/10003 -&gt; VM03 tcp/3389
   .....
  FE tcp/10010 -&gt; VM10 tcp/3389

Also as you don't have to specify the backend server I presume it maps the FE Nat rules to whatever VMs are configured in the first Backend Pool for that LB?, but is not documented clearly. I have no idea how it determines the order of mapping if you have multiple pools.

---
EDIT: for Clarity

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c4182ba-31dd-e65f-5fe4-949c9e414d3f
* Version Independent ID: 2cc91f75-932b-d630-0ba7-9162b9c1972e
* Content: [az network lb inbound-nat-pool](https://docs.microsoft.com/en-us/cli/azure/network/lb/inbound-nat-pool?view=azure-cli-latest#az-network-lb-inbound-nat-pool-create)
* Content Source: [src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by MyronFanQiu** [comment]
@Know1 Hello. I don't fully understand your request. Do you just mean that we should correct our documentation or we need some feature to correctly map multiple inbound ports to multiple backend ports.

**Comment by Know1** [comment]
This specific request was to update the documentation to clarify as per pointed out above.
It should also clarify the last point as that is ambiguous and an unknown outcome.

**Comment by MyronFanQiu** [comment]
@anavinahar Could you share your knowledge about this issue with us so that we can make a better fix for it.

**Comment by yonzhan** [comment]
@anavinahar any update?
