### ISSUE TITLE
function app: az functionapp create should support slots creation

### ISSUE THREAD

**Issue by exc3eed** [Azure/azure-cli#9126]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Cannot create slot for Function app. Following error is returned.
"Function App app settings are not expected to be empty. Please try again with WEBSITE_CONTENTAZUREFILECONNECTIONSTRING as a storage account connection string"
**To Reproduce**
Just execute this command
az webapp deployment slot create --name <function_app_name>--resource-group deletete --slot <slot_name>
**Expected behavior**
Slot should be created successfully for function app.

**Environment summary**
**Additional context**

**Comment by panchagnula** [comment]
@ankitkumarr this is the bug from the CRI - if you have an existing bug please link the bugs.

**Comment by Chedberg84** [comment]
👍 
I am also experiencing this issue.

I am using an Azure Function runtime version ~2. Following the Terraform example here: https://vgaltes.com/post/deploying-azure-functions-using-slots/

I was able to confirm I see the same issue as stated by @exc3eed above when running the az webapp deployment slot create command. Adding the storage account connection string doesn't seem to change the exception thrown:

Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Function App app settings are not expected to be empty. Please try again with WEBSITE_CONTENTAZUREFILECONNECTIONSTRING as a storage account connection string.

**Comment by panchagnula** [comment]
@Chedberg84 az webapp should not be used for functionapp - the az functionapp * commands should be used for functionapp & slots creation for functionapp is not currently supported.

**Comment by afuggetta** [comment]
Hello,

Is this on track to be deployed on May 15th?

Thanks

**Comment by ahmedelnably** [comment]
We are still working on this, unfortunately the support for slots in the create command will not be out by May 15th

**Comment by bigdatamoore** [comment]
any idea when this will be available?

**Comment by ahmedelnably** [comment]
We will start working in the near future, we still do not have a concrete ETA yet

**Comment by ankitkumarr** [comment]
We have started the work https://github.com/Azure/azure-cli/pull/9550. It should be completed in [Sprint 63](https://github.com/Azure/azure-cli/milestone/66) (Official Release: 6/18/2019).

**Comment by ankitkumarr** [comment]
This can be closed @ahmedelnably. Work was completed and released.

**Comment by rerime** [comment]
BUG!
az functionapp deployment slot create
It is clone all settings from main function. Including variable WEBSITE_CONTENTSHARE
So it leads to deploy to same function.
In Azure Portal it generate random WEBSITE_CONTENTSHARE variable based on function name.

**Comment by ahmedelnably** [comment]
@rerime thanks for reporting the issue, we will be fixing that in the next release

**Comment by ahmedelnably** [comment]
Thanks to @ankitkumarr the fix is addressed in https://github.com/Azure/azure-cli/pull/9731
