### ISSUE TITLE
"Try it" experience doesn't work even though same command works from Azure CLI locally

### ISSUE THREAD

**Issue by rohitsaigal** [Azure/azure-cli#9139]
Specific command that I was using is given below. Just try to grant permissions for one of my app signed in as global administrator for the Azure AD Tenant.

Even though command parameters are correct and signed in user has required permissions, the `Try it` experience kept returning 403 Forbidden error. When using the same command locally instead it works just fine. My guess is that incorrect clientId was being passed, but you can debug further to see what's the issue.

`az ad app permission grant --id 1e948769-5844-447f-97b3-e831ffd3159b --api 00000003-0000-0000-c000-000000000000 --scope 405a51b5-8d8d-430b-9842-8be4b0e9f324 --consent-type AllPrincipals`

![Error screenshot](https://user-images.githubusercontent.com/48256335/56329981-1e98fa80-6154-11e9-8ffd-959a5dae50c0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a5b5348-f67e-ef14-0529-4c80fddd4bc6
* Version Independent ID: bfd7e6b1-1fba-3d25-8ee3-5105bcf4157d
* Content: [az ad app permission](https://docs.microsoft.com/en-us/cli/azure/ad/app/permission?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
@sptramer @dendeli-msft the "Try It" feature is not under the ownership of the CLI team. Please help us route this to the appropriate backlog/issue tracker.
