### ISSUE TITLE
 Support for new parameters for VMSS instances - protectFromScaleIn and protectFromScaleSetActions

### ISSUE THREAD

**Issue by mayanknayar** [Azure/azure-cli#9164]
**Resource Provider**
CRP

**Description of Feature or Work Requested**
Support for new parameters for VMSS instances - protectFromScaleIn and protectFromScaleSetActions

Under instance properties, the protection parameters are configured as follows:
"protectionPolicy": {
      "protectFromScaleIn": boolean,
      "protectFromScaleSetActions": boolean
    }

This is updateable after create. Not applied at create.

**Minimum API Version Required**
2019-03-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-03-01/compute.json

**Target Date**
05/01/2019
Feature is high-pri ask by external and internal customers

**Comment by adewaleo** [comment]
@mayanknayar, thanks for the information.
