### ISSUE TITLE
az login authentication fails

### ISSUE THREAD

**Issue by ebertrams** [Azure/azure-cli#9169]
On corpnet wifi
Re-installed latest az with windows MSI installer 2.0.62
az login
choose my MS corpnet account in browser (which is already signed in)
Authentication in browser seems successful
Then getting authentication failed. see verbose logs below:
![image](https://user-images.githubusercontent.com/33331084/56540466-ab113780-651d-11e9-98fe-7b2cc8c7f9cf.png)
Verified that commands do not work:
![image](https://user-images.githubusercontent.com/33331084/56540503-c2e8bb80-651d-11e9-95b2-73ed6906b587.png)

**Comment by yugangw-msft** [comment]
@ebertrams, it appears you are using your MS account in Azure dogfood environment? I am seeing the ARM endpoint of `https://api-dogfood.resources.windows.net:443` from the trace. Please use a correct test account.

**Comment by marstr** [comment]
Ah, I hadn't noticed this. Good catch, @yugangw-msft. I'm going to close this out, but the issue is that your standard Microsoft account won't have access to a dogfood environment like this.
