### ISSUE TITLE
ATG7373

### ISSUE THREAD

**Issue by atongkuze** [Azure/azure-cli#9175]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by marstr** [comment]
Seems like an empty bug. Closing this out.
