### ISSUE TITLE
az ad app permission add ERROR : Property requiredResourceAccess.resourceAccess is invalid.

### ISSUE THREAD

**Issue by zipper97412** [Azure/azure-cli#9176]
I have some trouble adding roles via the permission subcommand: 
```
az ad app permission add --id $MyAppId --api $MyApplicationIWantToAccessId --api-permissions "<RoleId>=Role"
```

if I add my role manually via the manifest on azure, it works, 
if I do the same thing with this command, I get the following error:
```
az : ERROR: Property requiredResourceAccess.resourceAccess is invalid.
Au caractère Ligne:1 : 1
+ az ad app permission add --id xxxx --api xxxx --api-permissions "xxxx ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: Property...ess is invalid.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```
I only found examples using "Scope" instead of "Role" as permission type

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a5b5348-f67e-ef14-0529-4c80fddd4bc6
* Version Independent ID: bfd7e6b1-1fba-3d25-8ee3-5105bcf4157d
* Content: [az ad app permission](https://docs.microsoft.com/en-us/cli/azure/ad/app/permission?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
@zipper97412 Can you please use `--debug` share with me the trace?

**Comment by yugangw-msft** [comment]
please reactivate with more traces

**Comment by smartpcr** [comment]
i had the same problem, got it to work using `<RoleId>=Scope` instead of `<RoleId>=Role`, then when I call permission list, it says type is "Role"

**Comment by Kitwradr** [comment]
Having the same problem with `New-Object -TypeName "Microsoft.Open.AzureAD.Model.ResourceAccess" -ArgumentList "---------------id------------","Role"`

**Comment by fabienso** [comment]
i have the same issue with
`az ad app create --display-name GraphAPI_SP33 --native-app true --required-resource-accesses "[{'resourceAppId': '00000003-0000-0000-c000-0000000xxxxx', 'resourceAccess': [{'id': '65319a09-a2be-469d-8782-xxxx,'type': 'Role'}]}]" --available-to-other-tenants false`

**Comment by jiasli** [comment]
We currently don't have enough bandwidth maintaining `az ad` module which still uses AD Graph, please see https://github.com/Azure/azure-cli/issues/12946 for calling MS Graph with `az rest`.

**Comment by fabienso** [comment]
Thanks @jiasli  - it works with the following command line:


` az rest --method POST --uri "https://graph.microsoft.com/beta/applications" --body "{'displayName': 'testApp1234', 'requiredResourceAccess':[{'resourceAppId': '00000003-0000-0000-c000-000000000000', 'resourceAccess': [{'id': '65319a09-a2be-469d-8782-f6b07debf789','type': 'Role'}]}]}"`

**Comment by jiasli** [comment]
I am glad it works for you. 

Though I didn't quite understand the problem yet, here are some information that may be helpful.

From the result of `az ad sp show --id 00000003-0000-0000-c000-000000000000`, we can see 

```
    {
      "allowedMemberTypes": [
        "Application"
      ],
      "description": "Allows the app to read or write your organization's user flows, without a signed-in user.",
      "displayName": "Read and write all identity user flows",
      "id": "65319a09-a2be-469d-8782-f6b07debf789",
      "isEnabled": true,
      "value": "IdentityUserFlow.ReadWrite.All"
    },
```

is under `appRoles` which should be **application permission**, so `type` should be `Role`, instead of `Scope`.

`az ad app permission add` shows some help about their relationship:

```
> az ad app permission add --help

Command
    az ad app permission add : Add an API permission.
        Invoking "az ad app permission grant" is needed to activate it.

        To get available permissions of the resource app, run `az ad sp show --id <resource-appId>`.
        For example, to get available permissions for Graph API:
          - Azure Active Directory Graph: `az ad sp show --id 00000002-0000-0000-c000-000000000000`
          - Microsoft Graph: `az ad sp show --id 00000003-0000-0000-c000-000000000000`
        Application permissions under the `appRoles` property correspond to `Role` in --api-
        permissions. Delegated permissions under the `oauth2Permissions` property correspond to
        `Scope` in --api-permissions.
```

**Comment by fabienso** [comment]
The problem is simply that it does not recognize the "Type" -> "Role" under the permissions when the resource requirements are passed and throws the error (which is in the debug log). "Role" is not recognized or accepted when adding permissions to the Active Directory applications.

**Comment by jiasli** [comment]
@fabienso anyway, let's stick to `az rest` for now. We will revisit this when we migrate to MS Graph in the future.
