### ISSUE TITLE
Default name for policy assignment exceeds '24' characters.

### ISSUE THREAD

**Issue by murarisumit** [Azure/azure-cli#9177]
**Describe the bug**
Default name for policy assignment  exceed '24' characters, which results in error.

**To Reproduce**
* Try creating any policy.
* Creating policy assignment without `name` flag 
  ```
  az policy assignment create \
                --scope "/providers/Microsoft.Management/managementGroups/test-group" \
                --policy "/providers/Microsoft.Management/managementgroups/test-group/providers/Microsoft.Authorization/policyDefinitions/<policy-name>"

  ```

Steps to reproduce the behavior.

**Expected behavior**
I should be able to create assignment of policy at given management group with some system generated name.

**Environment summary**
Running it in bash with az cli <2.0.60> in mac mojave.

**Comment by yonzhan** [comment]
@Juliehzl, add to S162
