### ISSUE TITLE
[component] Error thrown when installing additional command module

### ISSUE THREAD

**Issue by xscript** [Azure/azure-cli#918]
In OS X, when I try to install IoT command module with `sudo az component install -n iot -p`, the following error message is thrown.
`AZURE_CLI_PRIVATE_PYPI_URL environment variable not set.`
Then I tried `sudo /usr/local/az/envs/default/bin/pip install azure-cli-iot==2016.09.05.nightly --extra-index-url http://40.112.211.51:8080 --trusted-host 40.112.211.51`, which successfully installed the IoT command module.
I don't think this is good experience for additional command module.

And the same thing happened in Ubuntu 16.04 LTS.

I know there are some changes on package management recently. Please update the installation script accordingly, so that people can easily install additional command module as they want.
Thanks!

**Comment by derekbekoe** [comment]
Did you export the two following environment variables?
```
export AZURE_CLI_PRIVATE_PYPI_URL=http://40.112.211.51:8080/
export AZURE_CLI_PRIVATE_PYPI_HOST=40.112.211.51
```

Also, it looks like you ran `az component install` with `sudo` so maybe the environment variables weren't set for that specific user?

Also, you're correct in that PR #914 changes how additional components are installed. Once that gets in, it should make it a little easier to install components.

**Comment by xscript** [comment]
Without `sudo`, permission error will be thrown.
I aslo have tried exporting above environment variables with the following command `sudo -E bash -c 'az component install -n iot -p'`, still getting error. Will paste the error here later.

**Comment by derekbekoe** [comment]
@xscript I'm closing the issue as we have discussed over email.

**Comment by xscript** [comment]
Thanks @derekbekoe !
