### ISSUE TITLE
Recent "az webapp up" change removes json from output

### ISSUE THREAD

**Issue by dsparkplug** [Azure/azure-cli#9181]
**Describe the bug**

As of commit 02afe0a the command `az webapp up` no longer outputs json containing properties of the deployed web app 

**To Reproduce**

run `az webapp up --output json --name MyFancyWebApp`

Output using version 2.0.63 is: 

```
Creating Resource group 'dave.sparks_rg_Windows_centralus' ...
Resource group creation complete
Creating App service plan 'dave.sparks_asp_Windows_centralus_0' ...
App service plan creation complete
Creating app 'MyFancyWebApp' ...
Webapp creation complete
Configuring default logging for the app, if not already enabled
Updating app settings to enable build after deployment
All done.
You can launch the app at 'http://myfancywebapp.azurewebsites.net'. To redeploy the app run the command az webapp up -n MyFancyWebApp -l Central US
```

**Expected behavior**

Output from the same command using version 2.0.61 was:

```
Creating Resource group 'dave.sparks_rg_Windows_centralus' ...
Resource group creation complete
Creating App service plan 'dave.sparks_asp_Windows_centralus_0' ...
App service plan creation complete
Creating app 'MyFancyWebApp' ....
Webapp creation complete
Updating app settings to enable build after deployment
All done.
{
  "app_url": "http://myfancywebapp.azurewebsites.net",
  "location": "Central US",
  "name": "MyFancyWebApp",
  "os": "Windows",
  "resourcegroup": "appsvc_rg_Windows_centralus",
  "serverfarm": "appsvc_asp_Windows_centralus",
  "sku": "FREE",
  "src_path": "D:\\temp\\test\\publish",
  "version_detected": "-",
  "version_to_create": "-"
}
```
I would expect the json at the end of this output to be included in the output of version 2.0.63.

**Environment summary**
```
>az --version
azure-cli                         2.0.63

acr                                2.2.5
acs                               2.3.22
advisor                            2.0.0
ams                                0.4.5
appservice                        0.2.18
backup                             1.2.4
batch                              4.0.0
batchai                            0.4.8
billing                            0.2.1
botservice                        0.1.10
cdn                                0.2.3
cloud                              2.1.1
cognitiveservices                  0.2.5
command-modules-nspkg               2.0.2
configure                         2.0.22
consumption                        0.4.2
container                         0.3.16
core                              2.0.63
cosmosdb                          0.2.10
deploymentmanager                  0.1.0
dla                                0.2.5
dls                                0.1.9
dms                                0.1.3
eventgrid                          0.2.3
eventhubs                          0.3.4
extension                          0.2.5
feedback                           2.2.1
find                               0.3.2
hdinsight                          0.3.3
interactive                        0.4.3
iot                                0.3.8
iotcentral                         0.1.6
keyvault                          2.2.14
kusto                              0.2.2
lab                                0.1.7
maps                               0.3.4
monitor                           0.2.13
network                            2.3.7
nspkg                              3.0.3
policyinsights                     0.1.2
privatedns                         1.0.0
profile                            2.1.5
rdbms                             0.3.10
redis                              0.4.2
relay                              0.1.4
reservations                       0.4.2
resource                          2.1.14
role                               2.6.0
search                             0.1.1
security                           0.1.1
servicebus                         0.3.4
servicefabric                     0.1.17
signalr                            1.0.0
sql                                2.2.2
sqlvm                              0.1.1
storage                            2.4.1
telemetry                          1.0.2
vm                                2.2.19

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\daves\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.
```

**Additional context**

We were previously parsing the json output from the `az` cli in our build script to get the app_url, location and resourcegroup of the new web app. So removing the json from the output is a breaking change for us.

**Comment by yugangw-msft** [comment]
@panchagnula, expected?

**Comment by panchagnula** [comment]
Yes expected —dryrun still shows this but on running the operation. We show the url & how to redeploy. Since we got feedback that the output JSON is not very useful.

**Comment by dsparkplug** [comment]
Surely, if we explicitly state that the output format is json using `--output json`, then we should get json. People who don't want json, can use a different output format.

A bigger issue here is that this functionality has been released and people are already  using it. Fair enough, if you remove this as a part of a major, or event minor release, but  as part of a point change from 2.0.61 to 2.0.62? We have created actions for our CI server which call the Azure CLI. It is very difficult to keep this up to date when the goal posts change every couple of weeks.

**Comment by panchagnula** [comment]
@dsparkplug unfortunately this is a breaking change that we are not willing add back at this time. I apologize for the inconvenience here, but the reason we are making some changes on a regular basis is because we are seeing an increase in the usage of this command & receiving a lot of feedback. We heard that url is the only useful part of the JSON that is useful post operation is completed so we are just    responding to this feedback. In the future from the upcoming release we will follow the pattern to add a deprecation message one release before actual breaking changes are introduced for this command - just  like the rest of the CLI commands.

**Comment by dsparkplug** [comment]
The main problem here is the resource group. There does not appear to be a way to get any details about the deployed web app, using `az webapp show` for example, without knowing the resource group.

I know that the resource group, app service plan, web app name and app url are included in the text, but this is not really a machine readable format. 

People who are giving feedback that they don't like the json are probably using the cli manually, and not as part of an automated process. Most of the az cli commands output json by default. Those people probably don't like that either. However, there are some of us who are calling the cli from another process want more json. Or maybe its just me? Anyway, surely there's a way make this optional so all parties are happy.

**Comment by panchagnula** [comment]
we are going to be adding RG & ASP as parameters to the command itself soon & hoping that will solve the problem you are seeing since the command parameters then match the rest of the CLI commands. Currently we are trying to stop add too many parameters to this command we will add RG & Plan, but no intentions of supporting JSON at this time.  Actually your comment gives an idea here is to do a GET call site created a return the full site object instead of a special JSON. Let me ponder a bit more on this.

**Comment by dsparkplug** [comment]
> Actually your comment gives an idea here is to do a GET call site created a return the full site object instead of a special JSON

👍 to this. I guess that would make the output similar to that of the `az webapp create` command.
