### ISSUE TITLE
Role definition update throws error "KeyError: 'roleName'"

### ISSUE THREAD

**Issue by subesokun** [Azure/azure-cli#9183]
## Describe the bug

**Command Name**
`az role definition update`

**Errors:**
```
'roleName'
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 523, in execute
    raise ex
cli/core/commands/__init__.py, ln 581, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 574, in _run_job
    six.reraise(*sys.exc_info())
lib/python3.7/site-packages/six.py, ln 693, in reraise
    raise value
...
azure/cli/core/__init__.py, ln 453, in default_command_handler
    return op(**command_args)
cli/command_modules/role/custom.py, ln 55, in update_role_definition
    return _create_update_role_definition(cmd, role_definition, for_update=True)
cli/command_modules/role/custom.py, ln 84, in _create_update_role_definition
    role_name = role_definition['roleName']
KeyError: 'roleName'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az role definition update --role-definition {}`

## Environment Summary
```
Darwin-18.5.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.63

Extensions:
dev-spaces-preview 0.1.6

```

**Comment by yugangw-msft** [comment]
@subesokun, can you double check whether or not the input contains `roleName`?

**Comment by subesokun** [comment]
@yugangw-msft It seems like my role definition was no longer valid as there has been some breaking changes. I've managed now to fix it and the command works again. Nevertheless, a helpful error message (e.g. role definition is invalid) would have been nice instead of some error stack trace.

**Comment by jiasli** [comment]
Duplicate of https://github.com/Azure/azure-cli/issues/12027
