### ISSUE TITLE
Issue in installing Azure CLI with apt (ubuntu 16.04)

### ISSUE THREAD

**Issue by razmohan** [Azure/azure-cli#9185]
i am following the same steps mentioned in the below path
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest

1) sudo apt-get install curl apt-transport-https lsb-release gpg
error message : 
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package gpg is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'gpg' has no installation candidate

2) sudo apt-get install azure-cli
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package azure-cli

Please let me know if any one installed successfully ?

**Comment by marstr** [comment]
Howdy, is this a new enough environment that you may not have run `sudo apt-get update`?

**Comment by razmohan** [comment]
@marstr i am using this commands in dockerfile to build an image with ubuntu + azure cli.
I have solved the second part of my question, but still the "Package 'gpg' has no installation candidate" issue hangs. Pls check out this command "sudo apt-get install curl apt-transport-https lsb-release gpg" in ubuntu.

**Comment by marstr** [comment]
Hey thanks, I'm able to repro this. You can work around it by using the package name `gnupg` instead of `gpg`. I've just checked and `gnupg` works in both ubuntu:xenial and ubuntu:disco. I'll see that these instructions get updated.

**Comment by marstr** [comment]
Looks like the [instructions mention gnupg](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#manual-install-instructions) as well. I'm going to close this issue out.
