### ISSUE TITLE
Proposal: az account refresh

### ISSUE THREAD

**Issue by ahmetb** [Azure/azure-cli#919]
Sometimes I have new subscriptions associated to my account that did not exist when I did `azure login` so I have to do `azure login` again and go through the interactive login flow to get the new subscriptions I have show up on my local CLI.

Since CLI already has my working credentials, perhaps a new `az account refresh` can re-download my subscriptions list?

**Comment by mayurid** [comment]
@Yugang-msft: Thoughts?
I am curious how common is this scenario?

**Comment by listonb** [comment]
Instead of az account refresh i'd like az account list to just pull a live list of the active subscriptions. I'd like to see real time data.

**Comment by yugangw-msft** [comment]
I will expose that in “az account list”. About opt-in vs opt-out, we can leave it as an open question and decide it later on. Either way, we need new logics to get the live list, and flipping the default is easy.
JFYI, caching the subscriptions and access tokens, so to avoid asking for user credentials and active subscription on running every command, is the design coming from CLI 1.0. For creds sharing, CLI 2.0 inherited it.

**Comment by yugangw-msft** [comment]
This issue has a PR there
