### ISSUE TITLE
Need an azure cli command to add a document into CosmosDB (SQL API, MongoDB)

### ISSUE THREAD

**Issue by kjcho-msft** [Azure/azure-cli#9190]
**Is your feature request related to a problem? Please describe.**
Using az cli command, I could create a database and collecton in CosmosDB. But there is no command to create a document. This is a blocking issue for me to move to azure cli. 

**Describe the solution you'd like**
Need an azure cli command to add a document into CosmosDB (SQL API, MongoDB)

**Describe alternatives you've considered**
Couldn't find any alternative solutions on Linux. On Windows, there are a couple Powershell cmdlets but they don't work on Linux.

**Comment by limingu** [comment]
This is related to the CosmosDB instead of storage.

**Comment by shurd** [comment]
Hi @kjcho-msft, thank you for raising this issue. At this time, we do not plan on adding the ability to access data (such as documents) to the CLI. For these operations, we provide other SDKs, which can be found at https://docs.microsoft.com/en-us/azure/cosmos-db/. You can also try out our data plane python package, [azure-cosmos](https://github.com/Azure/azure-cosmos-python).

**Comment by veerun14** [comment]
Make HTTP requests using SDK with CURL or WGET tools if command line is your only option.
