### ISSUE TITLE
az container - Specify private IP to use.

### ISSUE THREAD

**Issue by fauxcoding** [Azure/azure-cli#9197]
**Is your feature request related to a problem? Please describe.**
I'm currently using Azure Container Instances with the bring your vNet functionality. Whilst we can specify the subnet, there doesn't seem to be a way to specify the private IP we would like to use.

To get the IP we must run the following command after the container is created

```
$ az container show --resource-group myResourceGroup --name appcontainer --query ipAddress.ip --output tsv
10.0.0.4
``` 

**Describe the solution you'd like**
I'd like to be able to specify the IP at the time of creating the container by passing in an additional command line argument for the `az container create` command.

**Describe alternatives you've considered**
N/A

**Additional context**
This is the guide I've been following to create container instances with a custom vNet.
https://docs.microsoft.com/en-us/azure/container-instances/container-instances-vnet

**Comment by yonzhan** [comment]
container

**Comment by navba-MSFT** [comment]
@heymega Apologies for the late reply. Thanks for reaching out to us. We will update this thread once we have more details about this. As a workaround to this you can refer [this](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-egress-ip-address) article if you want to configure a single public IP address for outbound and inbound traffic to a container group. Please let us know if you still have a requirement of specifying a private IP address manually ? 

@macolso Could you please look into this and let us know if this ask is achievable ?
