### ISSUE TITLE
The AKS default VM size should be larger

### ISSUE THREAD

**Issue by lawrencegripper** [Azure/azure-cli#9198]
**Describe the bug**
Currently the VM Size used by default is a `Standard_DS2_v2` I'd like to submit a PR to update this to `Standard_D4s_v3` or `Standard_DS3_v2`

**To Reproduce**
`az aks create -n aks1 -g aks-test`

**Expected behavior**
For the vast majority of workloads this is too small a VM size.

The effect, in my opinion, is that users start a cluster and notice very quickly that it doesn't perform or deployment fail after install helm charts like Jaeger or Istio

**Environment summary**
NA

**Additional context**
Was previously raised from https://github.com/Azure/azure-cli/pull/7025

**Comment by marstr** [comment]
@mboersma, is this something you have an opinion on?

**Comment by mboersma** [comment]
We shouldn't change the default VM size except by agreement with the project management team, IMHO.

**Comment by lawrencegripper** [comment]
Agreed. To play devils advocate to my own proposal moving to a larger size by default might annoy people as it would increase the cost of a cluster by default.
