### ISSUE TITLE
Invalid example in az functionapp config appsettings set

### ISSUE THREAD

**Issue by bigdatamoore** [Azure/azure-cli#9201]
The example included here is not valid. There should not be spaces between the setting name and the value of the setting.   Here's a corrected example:
```
az functionapp config appsettings set --name MyFunctionApp --resource-group MyResourceGroup --settings "APPINSIGHTS_INSTRUMENTATIONKEY=$key"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06e69fb3-f10c-98ac-0506-35d02f2a7481
* Version Independent ID: ad86610e-e20d-2c96-80fd-61c3d6e7f9ff
* Content: [az functionapp config appsettings](https://docs.microsoft.com/en-us/cli/azure/functionapp/config/appsettings?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py)
* Service: **functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
@JasonRShaver @albaloo please fix this in the Aladdin code gen and update this example asap.

```
  - name: Update a function app's settings. (autogenerated)
    text: |
        az functionapp config appsettings set --name MyFunctionApp --resource-group MyResourceGroup --settings "APPINSIGHTS_INSTRUMENTATIONKEY = $key"
    crafted: true
```

**Comment by JasonRShaver** [comment]
Thanks for reporting; We're fixing the issue and should have a fix out soon.
