### ISSUE TITLE
P1 no longer available

### ISSUE THREAD

**Issue by daherna** [Azure/azure-cli#9205]
support notified a customer that P1 is no longer supported as a sku and to use p1v2. P1 is still listed in the documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f99cdf3a-4fd3-e949-aabe-1b26fe828444
* Version Independent ID: 1c2e7517-1275-9e30-db67-393c0451055f
* Content: [az appservice plan](https://docs.microsoft.com/en-us/cli/azure/appservice/plan?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py)
* Service: **app-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by panchagnula** [comment]
This is a bug on the CLI documentation that we will fix - as per out official documentation these are the supported SKU's https://azure.microsoft.com/en-us/pricing/details/app-service/windows/
