### ISSUE TITLE
Change az functionapp devops-build to devops-pipeline

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-cli#9208]
the current command `az functionapp devops-build` need to get into deprecation mode, and we should replace it with `az functionapp devops-pipeline` as the command creates an azure pipeline to build and release.

**Comment by marstr** [comment]
Howdy @ahmedelnably, what's the timeline you're targeting for this?

**Comment by ahmedelnably** [comment]
@marstr  We are targeting the next release, we will keep the old command for at least 2 releases, and we will also mark it as deprecated

**Comment by Hazhzeng** [comment]
This issue will be addressed in https://github.com/Azure/azure-cli/pull/9220

**Comment by Hazhzeng** [comment]
The change has been merged. Please close this thread.
