### ISSUE TITLE
Monitor: metric alerts cmd should accept count as an aggregation type

### ISSUE THREAD

**Issue by snehithm** [Azure/azure-cli#9211]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
CLI commands for metric alerts dont support Count as an aggregation type. 

**To Reproduce**
Steps to reproduce the behavior.
![image](https://user-images.githubusercontent.com/20316932/56784321-7cd97380-680d-11e9-8240-082ce8079bef.png)

**Expected behavior**
Count should be an allowed aggregation type. This was added to metric alerts a few months ago.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
Installed using MSI. azure-cli 2.0.60 monitor 0.2.10, cmd.exe

**Additional context**
This is probably by design. When cli commands for metric alerts were created, count was not a supported aggregation type. However metric alerts have added support for count in January.

**Comment by tjprescott** [comment]
Please update your CLI. This was already added in azure-cli-monitor 2.0.12.
