### ISSUE TITLE
AMS - MRU commands fail with 'The access token is invalid' for Service Principal

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-cli#9212]
## Describe the bug
Attempted to programatically set the MRU as described in documentation. After successfully creating the media service account and running the below command, the following error was returned.

`The access token is invalid.`

**Command Name**
`az ams account mru set`

**Errors:**
```
The access token is invalid.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Created the ams account with the same login details and session
- `az ams account mru set -n {} -g {} --count {} --type {}`

## Expected Behavior
Command to run successfully

## Environment Summary
```
Linux-4.4.0-17134-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.63

```
## Additional Context
I'm currently performing this action under a service principal. This same service principal created the resource and has contributor rights to both the media service itself and to the whole subscription.

**Comment by yugangw-msft** [comment]
Likely, this is an error on AMS command. @BrianBlum, does AMS cli acquire the right token? This error usually means the token is for the a different audience(aka resource)

**Comment by BrianBlum** [comment]
There's a work item to acquire the AMS RESTv2 token with the audience "https://rest.media.azure.net".
You should be able to work around the problem by logging in with az login.

**Comment by wahyuen** [comment]
@BrianBlum was there any particular arguments for the workaround?

Our release pipeline scripts have already logged the service principal in via the following statement

`[command]/usr/bin/az login --service-principal -u *** -p *** --tenant ***`

**Comment by BrianBlum** [comment]
Is the service principal you're using registered to use the AMS REST v2 API. See https://docs.microsoft.com/en-us/azure/media-services/previous/media-services-use-aad-auth-to-access-ams-api.

**Comment by wahyuen** [comment]
@BrianBlum I believe so. I have attempted this when the service principal was a `Contributor` at the subscription level, then ran another test when the service principal was a `Contributor` on the Media Services resource itself and both came back with the same error.

**Comment by BrianBlum** [comment]
After az login, if you run az account get-access-token, is the subscription that is returned the same subscription that your Media Services account is in? If not, you can reset it with 
az account set --subscription "<name>".

**Comment by BrianBlum** [comment]
az account set --subscription "name from subscription details". I used less than and greater than chars and everything disappeared.

**Comment by wahyuen** [comment]
@BrianBlum yes, the subscription matches up with the one where media services has been deployed.

I ran the following commands explicitly to test and still have the same result :(

 - `az account set -s {}`
- `az account get-access-token --resource https://rest.media.azure.net`
- `az ams account mru set -n {} -g {} --count 1 --type S3`

Result:
`The access token is invalid.`

**Comment by BrianBlum** [comment]
I'd like to look at our REST v2 logs to see if there's more information about the access token. 
Which DC is your account in and about what time did you run these commands?

**Comment by wahyuen** [comment]
@BrianBlum Service is located in `australiaeast`. I've run a fresh batch this morning as well, please see below for timestamps.

```
>>$ az login --service-principal -u *** -p *** -t ***
[
  {
    "cloudName": "AzureCloud",
    "id": "***",
    "isDefault": true,
    "name": "***",
    "state": "Enabled",
    "tenantId": "***",
    "user": {
      "name": "***",
      "type": "servicePrincipal"
    }
  }
]
>>$ date -u
Fri May  3 01:37:18 UTC 2019
>>$ az account get-access-token --resource https://rest.media.azure.net
{
  "accessToken": "***",
  "expiresOn": "2019-05-03 10:37:27.366291",
  "subscription": "***",
  "tenant": "***",
  "tokenType": "Bearer"
}
>>$ date -u
Fri May  3 01:37:29 UTC 2019
>>$ az ams account mru set -n *** -g *** --count 1 --type s3
The access token is invalid.
>>$ date -u
Fri May  3 01:37:53 UTC 2019
>>$
```

Happy to share specific subscription/account ids privately if this will aid you in finding out the logs :)

**Comment by BrianBlum** [comment]
There were no token authorization failures in the australiaeast logs. I assume that when you run
$ az ams account show -n ** -g **
you see the account you want.

At this point, I suggest that you go to the Azure portal and open a new support request. You can supply the subscriptionId and the Media Services account name and ID there.
