### ISSUE TITLE
az postgres server vnet-rule create does not have option to specify rg of the vnet

### ISSUE THREAD

**Issue by alexjmoore** [Azure/azure-cli#9214]
## Describe the bug
The option to specify subnet names and vnet names assumes that the vnet is within the same resource group as the postgresql instance, which is likely rarely the case.  It therefore errors as it cannot find the vnet in the resource group.  There should be an option to specify the resource group name.

**Command Name**
`az postgres server vnet-rule create`

**Errors:**
```
Resource not found: 'The Resource 'Microsoft.Network/virtualNetworks/<VNET>' under resource group '<POSTGRESQL RG>' was not found.'.
```

## To Reproduce:
`az postgres server vnet-rule create -g <postgresql rg> --server-name <server name> --name <rule name> --subnet <subnet name> --vnet <vnet name where vnet is in a different RG to PostgreSQL instance>`

## Expected Behavior
There should be an option similar to `--vnet-resource-group` to specify the resource group of the VNet itself for cases where the VNet is not within the same RG as the server instance.

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.63

Extensions:
azure-firewall 0.1.0
front-door 0.1.1

```

**Comment by tjprescott** [comment]
If the vnet is not in the same resource group, then you must submit the subnet by ID. This is the standard pattern in the CLI.
