### ISSUE TITLE
az ad user list --upn should support starts_with functionality like --display-name does

### ISSUE THREAD

**Issue by lukasmrtvy** [Azure/azure-cli#9216]
I am not quite sure if its feature request or bug...

```
az ad user list --display-name "John Doe (Exter"
```
Will quckly find all users starting with `"displayName"` :`"John Doe (Exter"` 

-> It will find `John Doe (External)` in this case, which is OK.

I suppose that:
```
az ad user list --upn "John.Doe@exa"
```
should do the same with `"userPrincipalName"`  attribute

-> It will not find anyting, unless You supply full `--upn` name.

I understand that this is neccessary for `az ad user show --upn-or-object-id` to output only single result.

Is possible to use something like this:
```
az ad user list --query "[?starts_with(userPrincipalName,'John.Do')]"
```
but it takes almost 1,5 min in our environment, instead of almost instant output with `az ad user list --upn "John.Doe@exa"`

Thanks

**Comment by yugangw-msft** [comment]
You can use the `--filter` argument, e.g.

     az ad user list --filter "startswith(userPrincipalName, 'yugangw@azure')"

For full reference of the filter synatx, check out https://docs.microsoft.com/en-us/graph/query-parameters#filter-parameter

**Comment by yugangw-msft** [comment]
I am pretty sure I have addressed this question, so I am closing it. Feel free to reactivate if you are still blocked

**Comment by dshamanthreddy** [comment]
Hello @yugangw-msft need help I need to list all user in AAD with displayname and email,

I m trying this way 
az ad user list –query “[].{ name:displayName,mail:mail}” -o tsv

it is not display anything

can you help

**Comment by yonzhan** [comment]
@jiasli could you help with above?

**Comment by jiasli** [comment]
@dshamanthreddy, your command looks good to me. Projecting `displayName` and `mail` requires [MultiSelect Hash](https://jmespath.org/specification.html#multiselect-hash) expression. 

The command is working fine in my test:

```
> az ad user list --query "[].{name:displayName,mail:mail}" --output tsv
Admin06 admin06@xxx.onmicroosft.com
Admin07 admin07@xxx.onmicroosft.com
```

Things you may check:

- Does the command return anything without `--query` and `--output`?
  ```
  az ad user list
  ```
- Does CLI receive the correct argument? Make sure arguments are not parsed by the shell.
  ```
  > az ad user list --query "[].{name:displayName,mail:mail}" --output tsv --debug
  cli.knack.cli: Command arguments: ['ad', 'user', 'list', '--query', '[].{name:displayName,mail:mail}', '--output', 'tsv', '--debug']
  ```
