### ISSUE TITLE
Hi There I am unable to create resource group from pycharm terminal

### ISSUE THREAD

**Issue by samanshariq** [Azure/azure-cli#9217]
## Describe the bug

**Command Name**
`az group create`

**Errors:**
```
az group create: error: the following arguments are required: --name/--resource-group/-n/-g, --location/-l
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az group create {}`

## Environment Summary
```
Darwin-18.2.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.63

```

**Comment by samanshariq** [comment]
I am using below script:
az group create \
   --name “samandemo-rg” \
   --location “centralus”

**Comment by tjprescott** [comment]
It looks like you need to correctly annotate the line breaks in your script or put everything on the same line.

**Comment by samanshariq** [comment]
I tried putting everything on the same line then it says resource group doesn't conform to the correct format.

**Comment by samanshariq** [comment]
parameter resource group name must conform to the following pattern '^[-\\w\\._\\(\\)]+$ when creating nsg

**Comment by tjprescott** [comment]
I would try removing the double quotes, since your names otherwise look like they conform to Azure expectations.
