### ISSUE TITLE
az ad sp show does not work with name

### ISSUE THREAD

**Issue by shirleyla10** [Azure/azure-cli#9221]
Per the doc, you should be able to show the service principal by entering az ad sp show --id &lt;name_of_sp&gt;, but when I try to do that, I get that the SP cannot be found.  However, if I do az ad sp show --id &lt;id_of_sp&gt;, the SP info is displayed correctly.  I am trying to use the command to pull up the id of the SP when given the name.  Please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99d25ff-03e2-e015-37f4-a29b59ec50d4
* Version Independent ID: 1a8e88ed-72c7-fbe7-b0ad-68f23b3946cd
* Content: [az ad sp](https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
@shirleyla10, you need to use values coming from the `servicePrincipalNames` array inside a service principle, not the `display name`

**Comment by yugangw-msft** [comment]
please activate if you are still blocked
