### ISSUE TITLE
az keyvault secret set

### ISSUE THREAD

**Issue by johnwildes** [Azure/azure-cli#9223]
Clicking the EDIT button on this page doesn't show all the content that the page has, it shows some root az keyvault help autogenerator.  I would have changed this instead of opening a feedback issue.

Can someone please update az keyvault secret set short description from: 

Sets a secret in a specified key vault.

to

Sets a secret in a specified key vault or creates a new secret if it doesn't exist.

Every other command for az keyvault has a CREATE option except SECRETS.  Here the SET purpose has two meanings, one to SET something that currently exists, and CREATE something that doesn't exist.  Searching for a CREATE option, which seems more logical, produces nothing.  Nothing in this document states that SET creates a new secret.  The cli --help does, but that isn't where I first looked. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39cfb8ed-c246-2ffb-9dff-070b90c18b21
* Version Independent ID: c09c1597-1b6c-b0a2-b3fc-bdc16764d096
* Content: [az keyvault secret](https://docs.microsoft.com/en-us/cli/azure/keyvault/secret?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by johnwildes** [comment]
How does one edit this Document? When I click on edit, it would only show the root keyvault auto generated help?  Is there something else I needed to do?

**Comment by tjprescott** [comment]
It should open the `_help.py` file.  You can add an entry like this:

```Python
helps['keyvault secret set'] = """
type: command
short-summary: Create a secret or update a secret in a KeyVault.
"""
```

**Comment by johnwildes** [comment]
Thanks for the help! I made the change, and submitted a PR, essentially using what you entered. https://github.com/Azure/azure-cli/pull/9253
