### ISSUE TITLE
az vm create does not support load balancer backend pool, inbound nat rules

### ISSUE THREAD

**Issue by christiankuhtz** [Azure/azure-cli#9225]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
ARM allows a VM to join the backend pool of a Load Balancer resource at the time that it is created.  There's no option in 

**To Reproduce**
doesn't exist. no option under az vm create 

**Expected behavior**
--lb-name and --lb-address-pool --lb-inbound-nat-rules should be valid arguments.  If --lb-address-pool is specified and/or --lb-inbound-nat-rules, --lb-name is mandatory as well.

**Environment summary**
azure-cli 2.0.63 on linux, but not really environment dependent. 

**Additional context**
The only way to accomplish this operation in cli is to then dig up the name of the NICs and modify them.  this can all be done in one operation at vm create. Or to create the NICs ahead of time.

**Comment by adewaleo** [comment]
@yugangw-msft what are your thoughts on this, should we expose arguments that make it easier to add a VM to a load balancer?

**Comment by adewaleo** [comment]
I will be closing this for now as CLI team does not have the bandwidth to implement this in the near feature and there isn't a high demand for this feature.

cc: @yugangw-msft @achandmsft
