### ISSUE TITLE
az aks enable-addons does not accept single quote in windows cmd

### ISSUE THREAD

**Issue by sscchh2001** [Azure/azure-cli#9228]
## Describe the bug
**Command Name**
`az aks enable-addons`

**Errors:**
```
Subscription 'subscriptions' not found. Check the spelling and casing and try again.
```

## To Reproduce:
az aks enable-addons -g {} -n {} -a monitoring --workspace-resource-id **'**wksp resource id**'**
Subscription 'subscriptions' not found. Check the spelling and casing and try again.

If you use double quote for workspace resource ID, then cmd won't throw exception.
az aks enable-addons -g {} -n {} -a monitoring --workspace-resource-id **"**wksp resource id**"**
-Running

## Expected Behavior
The cmd should work for both single quote and double quote.

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.63

```

**Comment by marstr** [comment]
Howdy please see our documentation regarding quoting issues here: https://github.com/Azure/azure-cli/blob/master/doc/use_cli_effectively.md#quoting-issues.

Command Prompt has somewhat unexpected single-quote behavior.
