### ISSUE TITLE
az ad user list hangs

### ISSUE THREAD

**Issue by amms-mnl** [Azure/azure-cli#9232]
Hello,

I am trying to command "az ad user list" but it seems like it is hanging tried to use --debug and saw that it is retrying always on the this part:
msrest.http_logger : Request method: 'GET'
msrest.http_logger : Request headers:
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'User-Agent': 'python/2.7.5 (Linux-3.10.0-957.10.1.el7.x86_64-x86_64-with-redhat-7.6-Maipo) msrest/0.6.6 msrest_azure/0.6.0 azure-graphrbac/0.60.0 Azure-SDK-For-Python AZURECLI/2.0.61'
msrest.http_logger : Request body:
msrest.http_logger : None
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): graph.windows.net:443
urllib3.util.retry : Incremented Retry for (url='/********/users?api-version=1.6&$filter='): Retry(total=3, connect=3, read=4, redirect=None, status=None)

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57b0bbf2-3dca-90b2-1734-a38e78104b41
* Version Independent ID: 39842113-e499-d863-0f61-795089d844d9
* Content: [az ad user](https://docs.microsoft.com/en-us/cli/azure/ad/user?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by marstr** [comment]
Are you behind a corporate proxy, or some other mechanism that is preventing the appropriate TLS handshake?

**Comment by marstr** [comment]
If you are, checkout our advice on configuring your environment here: https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy

**Comment by amms-mnl** [comment]
Hi Marstr, 
Yes, we are behind a corporate proxy. I tried doing your advice from that link but it still fails. As a workaround we just tried adding the proxy to the /etc/hosts and then adding the env. variable http_proxy. now it is working as it should.

Thanks!
