### ISSUE TITLE
2.0.63

### ISSUE THREAD

**Issue by mattfarina** [Azure/azure-cli#9235]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.63

**Describe the bug**
Version 2.0.63 does not appear on Docker Hub where the install instructions tell one to install if from when using Docker. See https://hub.docker.com/r/microsoft/azure-cli

**To Reproduce**
Run:

```
docker pull microsoft/azure-cli:2.0.63
```

**Expected behavior**
Should have pulled a valid image because 2.0.63 has been released.

**Comment by marstr** [comment]
Howdy @mattfarina, we have migrated our Docker repository to MCR to comply with relatively new policy.

You can get an image containing version 2.0.63 by running:

``` bash
docker pull mcr.microsoft.com/azure-cli:2.0.63
```

It may be worth noting that we're continuing to publish to `microsoft/azure-cli:latest` in Docker Hub as a legacy-support mechanism.
