### ISSUE TITLE
Azure cli query returning inconsistent data of vm size for Standard_DS2_v2

### ISSUE THREAD

**Issue by sunnyjit** [Azure/azure-cli#9238]
az cli version 2.0.57

**Describe the bug**
Azure cli returns the size of VM but it returns "Standard_DS2_V2" sometimes or "Standard_DS2_v2 " . There is change in small v and capital V . 

**To Reproduce**

`az vm list --subscription <subscription> -g <resource_group> -d --query '[].[hardwareProfile.vmSize]'`

**Expected behavior**
Ideally it should return "Standard_DS2_v2" as GUI also displays the vm size with small v .

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

Mac OSX (mojave), azure-cli (2.0.57) 

**Additional context**
Please let me know if you need further details.

**Comment by adewaleo** [comment]
Hello @sunnyjit, inconsistent casing is typically a service side issue. This isn't a cli issue.

The workaround I can give is to use -i with grep or to use case-insensitive logic in any script that works off of the output of your call of `az vm list`.

Concrete examples of when you notice the casing to be different might be helpful

**Comment by Drewm3** [comment]
The VM size casing is generally case preserving based on what the customer had entered. As such we do not consider this a bug on the backend APIs.
