### ISSUE TITLE
az webapp config backup create --backup-name parameter does nothing

### ISSUE THREAD

**Issue by Nking92** [Azure/azure-cli#9244]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
The --backup-name parameter for az webapp config backup create is not behaving properly. It does not set the name for the backups as expected.

**To Reproduce**
Run the following command with placeholders filled in:
`az webapp config backup create --resource-group $groupname --webapp-name $webappname --backup-name this-value-not-used --container-url $sasurl`

**Expected behavior**
Backups created with the schedule should have the name provided in the parameter

**Environment summary**

**Additional context**
The problem is that the underlying API request body has a missing value where BackupName should be. Updating the SDK might fix the issue.

**Comment by panchagnula** [comment]
This PR has the new SDK https://github.com/Azure/azure-cli/pull/9492 @Nking92 can you verify this once this change is merged?

**Comment by panchagnula** [comment]
@Nking92 just checking to see if this still reproes? Also is it possible to add a test for this?

**Comment by panchagnula** [comment]
Adding this to track for the upcoming milestone

**Comment by panchagnula** [comment]
@Nking92 we got an internal email referring this issue as well - can you check if this is something that is not fixed with the SDK

**Comment by panchagnula** [comment]
we are unable to repro this one. closing this
