### ISSUE TITLE
az webapp misleading error message '{nameofapp}' app doesn't exist if slot name is bad

### ISSUE THREAD

**Issue by Ashtonian** [Azure/azure-cli#9254]
```
version 2.0.62
```
**Describe the bug**
When trying to access a slot via the cli, if the slot name is wrong, cli reports that the app is missing, instead of specifying its an issue with the slot. Especially confusing because the UI shows the full {appname}-{slotname} when listing slots while the cli is expecting just the {slotname}. 

**To Reproduce**
```shell
# verify webapp works without slot
az webapp log download --resource-group "{resourcegroup}" --name "{webappname}"
# attempt to access slot with wrong name 
az webapp log download --resource-group "{resourcegroup}" --name "{webappname}"
--slot "{badslotname}"
# '{webappname}' app doesn't exist
```
**Expected behavior**
I expect the errors to be accurate, direct, and not misleading. When a slot is named wrong in the cli it should say: 
```
 '{badslotname}' slot doesn't exist
```

**Environment summary**
OS X 
installed via homebrew

**Comment by adewaleo** [comment]
@panchagnula

**Comment by panchagnula** [comment]
@Ashtonian Portal does some pre-validation which CLI doesn't since we expect API to show a useful error message. In general we are updating the commands to do some pre-validations, but a general suggestion for CLI commands incase of any errors run command with --debug & you should see the detailed error message from API. Please try that out & let me know if it helps. For now i am closing this.

**Comment by Ashtonian** [comment]
@panchagnula - I don't think that's a very desirable developer experience. To provide a bit of feedback:
- what is the point of having an error message if it's not useful?  
- if there is additional context or information from the API it would be useful to provide that automatically not through an additional flag.
- it's frustrating when your trying to debug azure resources directly and this type of misdirection can lead to somebody to spend substantial time chasing digital ghosts.
- aws and Google cloud are able to achieve this. These kind of things make the platform feel fairly immature.

**Comment by panchagnula** [comment]
@Ashtonian all great feedback we are working on making our APIs return a useful error message in general so that will be fixed once we have that. In the meantime we are trying to make as many changes as possible to improve our experience.
