### ISSUE TITLE
az interactive won't launch

### ISSUE THREAD

**Issue by ctktfg** [Azure/azure-cli#9260]
## Describe the bug
az interactive throws error upon launching and then fails to launch

**Command Name**
`az interactive`

**Errors:**
```
cannot import name 'DEFAULTS_SECTION'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 523, in execute
    raise ex
cli/core/commands/__init__.py, ln 581, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 574, in _run_job
    six.reraise(*sys.exc_info())
...
cli/command_modules/interactive/custom.py, ln 31, in start_shell
    azext_interactive.start_shell(cmd, style=style)
cliextensions/interactive/azext_interactive/__init__.py, ln 10, in start_shell
    from .azclishell.app import AzInteractiveShell
interactive/azext_interactive/azclishell/app.py, ln 35, in <module>
    from azure.cli.core._config import DEFAULTS_SECTION
ImportError: cannot import name 'DEFAULTS_SECTION'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az interactive`

## Expected Behavior
az interactive should launch

## Environment Summary
```
Linux-5.0.0-13-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.63

Extensions:
interactive 0.4.1

```

**Comment by tjprescott** [comment]
You need to update your extension with `az extension update -n interactive`.

**Comment by tjprescott** [comment]
Pinning this issue to hopefully avoid additional duplicates.

**Comment by ctktfg** [comment]
This worked - thanks.

Sorry for the dupe - is this documented somewhere?  I saw previous issues but there was no specifics on how to update extensions?  Is there a way to update all extensions?  I was also having a hard time figuring out what the current available version of any given extension is.  How would I know if a given extension is out of date?

**Comment by tjprescott** [comment]
Hi @ctktfg no worries about the dupe--it's not your fault. I just decided to pin this version of the issue because it was the newest one. The real problem is being tracked with #9241 because the CLI should recognize your extension is incompatible and raise a warning or prompt you to upgrade. `az extension list-available` will show the latest version for each extension in the index.

**Comment by tjprescott** [comment]
Additionally, you can run `az interactive --update` to update the extension before launching it.

**Comment by bonillajose** [comment]
I am running into and issue with this interactive shell. I successfully updated it before running it and installed the most recent azure-cli version 2.0.64. 

azure-cli                         2.0.64
Extensions:
interactive                        0.4.2

When I ran the az interactive command, the interactive shell shows briefly then it closes.

az>>
Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x041AF738>, <function _x509_from_base64_to_hex_transform at 0x041AF780>]
Event: CommandInvoker.OnFilterResult []
Event: Cli.PostExecute []
az_command_data_logger : exit code: 0

**Comment by ilaplace** [comment]
I'm using the latest version of the CLI but when I run `az interactive`  it automatically shuts down without saying anything. I'm on ubuntu 18.04. I do see for a split second that it's open.

**Environment**
`azure-cli         2.0.64`                 
`interactive                        0.4.3`

**Comment by bonillajose** [comment]
> I'm using the latest version of the CLI but when I run `az interactive` it automatically shuts down without saying anything. I'm on ubuntu 18.04. I do see for a split second that it's open.
> 
> **Environment**
> `azure-cli 2.0.64`
> `interactive 0.4.3`

I have the same issue as you are having but in Windows 10. Please follow my thread at #677

**Comment by tjprescott** [comment]
@ilaplace that is a different issue.
