### ISSUE TITLE
[azure-cli 2.0.63]- AttributeError: 'CLIConfig' object has no attribute 'config_parser' in cli_ctx.config.config_parser.get('cloud', 'name')

### ISSUE THREAD

**Issue by pradm** [Azure/azure-cli#9262]
## Describe the bug
executing az comands fails with the following error post upgrading to 2.0.63
line 241, in get_active_cloud_name
    return cli_ctx.config.config_parser.get('cloud', 'name')
AttributeError: 'CLIConfig' object has no attribute 'config_parser'

**Command Name**
`az login`

**Errors:**
AZ Login Code in Notebook

    print(f'START:     !az login\n')

    !az login
    if _exit_code != 0:
       raise SystemExit('Shell command:\n\n\t    !az login\n\nreturned non-zero exit code: ' + str(_exit_code) + '.\n')

    print(f'\nSUCCESS:     !az login')

Output
START:     !az login

Traceback (most recent call last):
  File "C:\Users\pradm\azuredatastudio-python\0.0.1\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\pradm\azuredatastudio-python\0.0.1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\azure\cli\__main__.py", line 33, in <module>
    az_cli = get_default_cli()
  File "C:\Users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\azure\cli\core\__init__.py", line 522, in get_default_cli
    help_cls=AzCliHelp)
  File "C:\Users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\azure\cli\core\__init__.py", line 55, in __init__
    self.cloud = get_active_cloud(self)
  File "C:\Users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\azure\cli\core\cloud.py", line 310, in get_active_cloud
    return get_cloud(cli_ctx, get_active_cloud_name(cli_ctx))
  File "C:\Users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\azure\cli\core\cloud.py", line 241, in get_active_cloud_name
    return cli_ctx.config.config_parser.get('cloud', 'name')
AttributeError: 'CLIConfig' object has no attribute 'config_parser'
An exception has occurred, use %tb to see the full traceback.

SystemExit: Shell command:

              !az login

returned non-zero exit code: 1.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Windows-10-10.0.14393-SP0
Python 3.7.1
Shell: cmd.exe

azure-cli 2.0.63

```

**Comment by pradm** [comment]
Steps to Reproduce the issue are follows these were utilized in a Jupyter Notebook and we noticed intermittently one of the steps break. Post that we have to re-install and then with in a short interval of time some az command will break. Once it breaks none of the az command would work even az login will also start to showcase the same errors and issues.

!{sys.executable} -m pip install azure-cli -qq
!{sys.executable} -m pip install requests -qq
!az --version
!az login
!az account set --subscription {azure_subscription_id}
!az aks get-versions --location {azure_region} --output table | findstr {aks_kubernetes_version}
!az group create --name {aks_rg_name} --location {azure_region}

**Comment by pradm** [comment]
i uninstalled and re-installed azure-cli using the following commands today and it has been couple of hours  and the issue has not re-occurred yet. So i am not sure what went wrong and where the problem was because post re-installation the version of azure-cli is still 2.0.63 which was earlier.

!{sys.executable} -m pip uninstall azure-cli
!{sys.executable} -m pip install azure-cli

**Comment by adewaleo** [comment]
@pradm how did you initially upgrade to the latest version of the CLI? Also are you installing these python packages system-wide or in packaging?

We do not expect / support users installing the cli via pip (please correct me if I'm wrong @marstr @tjprescott ).
If you really which to install / upgrade the cli via pip, however, then I would suggest **you always recreate a virtualenv and install the CLI using its latest version and dependencies**. 

Although we release our modules separately on pip we bundle them together and release the cli via different [installation methods](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest). We do not expect people to install different parts of the cli separately. This may have been the cause of your original issue. Upgrading one part of the cli without properly upgrading its dependencies and / or command modules.

@marstr @tjprescott you probably have a better sense of the CLI's policy regarding installation via pip. Please feel free to follow up on my statements if I misspoke.

Also @pradm, @marstr plans to consolidating all our command modules into one package. This might simplify installation via pip, sans maintaining other dependencies.

**Comment by pradm** [comment]
@pradm how did you initially upgrade to the latest version of the CLI? Also are you installing these python packages system-wide or in packaging?
**[Pradeep]**- We are using Azure Data Studio in which we have a notebook feature that enables us with Python Kernel so that we can execute any python commands from that interface. The install are local to the tool as it has it own python folder. Initial install was made with !{sys.executable} -m pip install azure-cli which got it to 2.0.52 sometime back and yesterday i did !{sys.executable} -m pip install azure-cli --upgrade and it moved it to 2.0.63.

We do not expect / support users installing the cli via pip (please correct me if I'm wrong @marstr
**[Pradeep]** Could you please confirm this as an official statement so that i can communicate the same at my side.

If you really which to install / upgrade the cli via pip, however, then I would suggest you always recreate a virtualenv and install the CLI using its latest version and dependencies.
**[pradeep]** we dont need an python virtual environments as the tools creates its own python installation folder and azure cli gets install under tools context. If someone has to explictly use Azure CLI commands outside Azure Data Studio they have to find the path and directly call the command as we dont add it to the path. Can you please help us with the correct command if we are using it in a wrong way in the python.exe -m pip install format.

Although we release our modules separately on pip we bundle them together and release the cli via different installation methods. We do not expect people to install different parts of the cli separately. This may have been the cause of your original issue. Upgrading one part of the cli without properly upgrading its dependencies and / or command modules.
**[pradeep]** could you please explain in more detail what do you mean by install different parts of the cli separately, if you can share a command which will install complete cli package via python.exe -m pip install format that would be very helpful for us.

Also @pradm, @marstr plans to consolidating all our command modules into one package. This might simplify installation via pip, sans maintaining other dependencies.
**[Pradeep]** If you share an example on the consolidation part that would be helpful.

**Comment by marstr** [comment]
Looking at this briefly, I'm fairly confident that the this is coming down to an incomplete install when upgrading via pip. Now that it's worked successfully after a reinstall, I would imagine that it will continue to work.

@adewaleo is correct that we discourage people from installing directly from pip as we have less control over the dependencies that will be used.

**Comment by pradm** [comment]
Thank you so much for the update appreciate it a lot; One last question "Azure Data Studio" is installed on a Windows machine. Similar to the Linux manual installation steps shared in https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest which uses CURL command is there something similar to this that we can achieve from windows.

**Comment by adewaleo** [comment]
> Thank you so much for the update appreciate it a lot; One last question "Azure Data Studio" is installed on a Windows machine. Similar to the Linux manual installation steps shared in https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest which uses CURL command is there something similar to this that we can achieve from windows.

You can [install the CLI on windows machines ](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest)using our MSI installer or by running a docker image.

**Comment by marstr** [comment]
The team is going through a bit of a shuffle, and I'm moving on to a new team starting next week. I'm going to unassign myself. :)

**Comment by tjprescott** [comment]
I believe this has also been fixed. It was an issue requiring an update. Please reopen if this recurs.
