### ISSUE TITLE
yaml output for az ad sp list is broken

### ISSUE THREAD

**Issue by ryan-emtelligent** [Azure/azure-cli#9263]
## Describe the bug

**Command Name**
`az ad sp list`

**Errors:**
```
('cannot represent an object', OrderedDict([('id', ''), ('tenant', '')]))
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 212, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
python3.7/site-packages/knack/output.py, ln 132, in out
    output = formatter(obj)
...
python3.7/site-packages/yaml/representer.py, ln 231, in represent_undefined
    raise RepresenterError("cannot represent an object", data)
yaml.representer.RepresenterError: ('cannot represent an object', OrderedDict([('id', ''), ('tenant', '')]))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad sp list --query '[].{"id":"appId", "tenant":"appOwnerTenantId"}' --output yaml`

## Environment Summary
```
Darwin-18.5.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.63

Extensions:
interactive 0.4.2

```

**Comment by adewaleo** [comment]
cc: @yugangw-msft @tjprescott 

This seems like an output issue so I will add it to the scripting and interactive experience projects.

**Comment by tjprescott** [comment]
@adewaleo bugs don't go into projects for triage. They get scheduled to be fixed.

**Comment by adewaleo** [comment]
> @adewaleo bugs don't go into projects for triage. They get scheduled to be fixed.

This makes perfect sense @tjprescott , I assumed that issues not related to a specific command module / group  (e.g. vm, network, storage, etc...) were added to the project.

**Comment by adewaleo** [comment]
It turns out that this is bug is not specific to `az ad sp list`.

`az vm list -g ova-test -oyaml --query "[].{name:name, group:resourceGroup}"` also fails but
`az vm list -g ova-test -otable --query "[].{name:name, group:resourceGroup}"` succeeds

Seems like --query and -o yaml don't work together. 

I am working on a fix.
