### ISSUE TITLE
Would like 'az servicebus queue exists' method

### ISSUE THREAD

**Issue by matt-lethargic** [Azure/azure-cli#9266]
There is a `namespace exists` method, but no `queue exists` method. My deployment scripts check for a queue using `az servicebus queue show` but this outputs an error to STDERR when it cannot find it and then will fail my release if I set "Fail on standard error" even though it completes.

**Describe the solution you'd like**
I would like the method  `az servicebus queue exists` the same as `namespace exists`

**Describe alternatives you've considered**
I would use `list` but my bash skills are good enough to then search the results! ;-)

**Comment by yonzhan** [comment]
What is the status of this issue ?

**Comment by yonzhan** [comment]
Is this issue resolved?

**Comment by yonzhan** [comment]
How is the status of this issue ?
