### ISSUE TITLE
MSI Install Phase of Build Pipeline Targets Incorrect Binary

### ISSUE THREAD

**Issue by marstr** [Azure/azure-cli#9270]
The dev branch is currently failing in CI. This is because the ADO agent already has the CLI available, and the updated bits aren't being picked up after the `msiexec` is called in the pipeline. I'm temporarily disabling this phase in #9269 to unblock our release and edge builds. However, this will mean we must manually test the MSI before each release until this issue is closed.

Related to #9133

**Comment by marstr** [comment]
This never made it to the top of the priority list for me, and I'm now moving on to a different team as part of a re-org happening here. However, the issue of making sure we test the Windows installer is definitely important enough to leave this issue open.

**Comment by yonzhan** [comment]
add to S164.

**Comment by fengzhou-msft** [comment]
The installation of MSI needs elevated priviledge. Without the priviledge the installation step of the CI script would fail silently.
