### ISSUE TITLE
test: do not record any http traffics coming from test preparer 

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli#9272]
1. This blows up almost all test recordings since `ResourceGroupPreparer` is always used 
2. This will cause a nightmare when we need to use azure-mgmt-resource with new api-version, which will come up in the near future with features which CLI need to incorporate like the real `dry-run` support

**Comment by yugangw-msft** [comment]
// CC @adewaleo @tjprescott  @kristapratico

**Comment by adewaleo** [comment]
I will look into:
1. simply ignoring this preparer traffic during playback.
2. not recording this traffic in resource group preparers.

**Comment by adewaleo** [comment]
@yugangw-msft when would you like this done by, at the latest?
