### ISSUE TITLE
CLI restore of Azure SQL Database

### ISSUE THREAD

**Issue by vannovv** [Azure/azure-cli#9273]
## Describe the bug

**Command Name**
`az sql db restore`

**Errors:**
```
Unable to build a model: Cannot deserialize datetime object., ValueError: Invalid datetime string: 2019-05-01T17-00Z, DeserializationError: Cannot deserialize datetime object., ValueError: Invalid datetime string: 2019-05-01T17-00Z
Traceback (most recent call last):
python3.7/site-packages/msrest/serialization.py, ln 1755, in deserialize_iso
    raise ValueError("Invalid datetime string: " + attr)
ValueError: Invalid datetime string: 2019-05-01T17-00Z

...

python3.7/site-packages/msrest/serialization.py, ln 1755, in deserialize_iso
    raise ValueError("Invalid datetime string: " + attr)
msrest.exceptions.SerializationError: Unable to build a model: Cannot deserialize datetime object., ValueError: Invalid datetime string: 2019-05-01T17-00Z, DeserializationError: Cannot deserialize datetime object., ValueError: Invalid datetime string: 2019-05-01T17-00Z
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az sql db restore --dest-name {} --resource-group {} --server {} --name {} --time {}`

## Expected Behavior
For the database to be restored on a specified SQL Server.  
## Environment Summary
```
Darwin-18.5.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.63

Extensions:
application-insights 0.1.1

```
## Additional Context
Have been able to manually walk through the restore using the portal.  Want to figure out a way to automate the recovery of my databases in another region.  For this test I grabbed the date/time from the available backup that showed up in the portal.  I would also like to know if there is a way to determine from the CLI what the most recent backup time is so that I can use that in for my restore.

**Comment by jaredmoo** [comment]
This error is happening because python can't parse your datetime string. I will update documentation to show the expected datetime format.

> I would also like to know if there is a way to determine from the CLI what the most recent backup time is so that I can use that in for my restore.

Yes, you can `az sql db show` and then refer to the `earliestRestoreDate` property.
