### ISSUE TITLE
az login with SP 

### ISSUE THREAD

**Issue by Sas002** [Azure/azure-cli#9282]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Sas002** [comment]
I am trying use az login with SP .  I a using on Linux , so export as variable . Problem is az vm list or any az command is not working unless, I authenticate with az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID 

Which is fine but after az login , it is generating .azure/accessTokens.json  on home directory and SP credential information are on clear text , which is a big risk for security. 

**How it should work** : After export , az login should work but without generating any .azure/**accessTokens.json** in clear text. Same login concept is working for AWS . When aws credentials are export then just aws  s3 ls  or similar command work without generating Key and secret is clear text. 
Example:

export AZURE_CLIENT_ID=xxxxxxx
export AZURE_CLIENT_SECRET=xxxxxxx
export AZURE_TENANT_ID=xxxxxxx
export AZURE_SUBSCRIPTION_ID=xxxxxx
az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
az vm list

**Comment by yugangw-msft** [comment]
Thanks  @Sas002, right now this is by-design. Also ~/.azure is being ACL'd correctly for protection. For record, AWS also saves secret in [plain text](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html), or if that been changed, please let me know.
For secret free solution, I very much suggest you go with the [managed service identity](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-sign-in)
Any questions/suggestion, let us know

**Comment by yugangw-msft** [comment]
Closing as we don't have outstanding bugs

**Comment by jiasli** [comment]
Let's discuss this further in https://github.com/Azure/azure-cli/issues/9282.
