### ISSUE TITLE
InstanceView displays 'null' instead of instanceView details for osName or osVersion

### ISSUE THREAD

**Issue by paulf-personal** [Azure/azure-cli#9284]
## Describe the bug
When you want to query specific OS information about a VM via CLI, the instanceView information is returned as null. 

The Azure Portal shows this information for a VM (e.g. Linux (ubuntu) for the Operating System on the VM properties)

Using the API (https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/instanceview) the instanceView is populated with details for osName and osVersion (e.g.  "osName": "ubuntu",     "osVersion": "18.10")

**Command Name**
`az vm get-instance-view`

**Errors:**
The command returns information about the VM, but the instanceView information is 
"instanceView": null,

## To Reproduce:
Create a VM

- _Put any pre-requisite steps here..._
- `az vm get-instance-view -g {} -n {}`

## Expected Behavior
The instanceView should be populated with the osName and osVersion data, as with an API query. 

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.63

```

**Comment by yugangw-msft** [comment]
Can you please run with `--debug` and share with me the trace? This is a service end issue, not on CLI

**Comment by paulf-personal** [comment]
Details sent privately (due to Subscription information, etc. in the Debug output).

**Comment by yugangw-msft** [comment]
Resolved per offline conversation. The instance view does contain the OS fields
