### ISSUE TITLE
redis export failed

### ISSUE THREAD

**Issue by christophemorio** [Azure/azure-cli#9287]
This issue happens when running `az redis export ...`

The call from the **cli** module :
https://github.com/Azure/azure-cli/blob/ea1bcfec7a4cf29c030602392efeebc71294505b/src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/custom.py#L24

Does not matches the **mgmt** constructor module :

https://github.com/Azure/azure-sdk-for-python/blob/400f9b9bc9dd316222e75f636fd7dd6717d46293/azure-mgmt-redis/azure/mgmt/redis/models/export_rdb_parameters_py3.py#L39
```
    def __init__(self, *, prefix: str, container: str, format: str=None, **kwargs) -> None:
```

Workaround :
```diff
# file: ~/.virtualenvs/azure/lib/python3.7/site-packages/azure/cli/command_modules/redis/custom.py
-   parameters = ExportRDBParameters(prefix, container, file_format) 
+   parameters = ExportRDBParameters(prefix=prefix, container=container, format=file_format)

```

## Describe the bug

**Command Name**
`az redis export`

**Errors:**
```
__init__() takes 1 positional argument but 4 were given
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 523, in execute
    raise ex
cli/core/commands/__init__.py, ln 581, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 574, in _run_job
    six.reraise(*sys.exc_info())
...
cli/core/commands/__init__.py, ln 289, in __call__
    return self.handler(*args, **kwargs)
azure/cli/core/__init__.py, ln 453, in default_command_handler
    return op(**command_args)
cli/command_modules/redis/custom.py, ln 24, in cli_redis_export
    parameters = ExportRDBParameters(prefix, container, file_format)
TypeError: __init__() takes 1 positional argument but 4 were given
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az redis export --container {} --file-format {} --prefix {} -g {} -n {}`

## Environment Summary
```
Darwin-18.2.0-x86_64-i386-64bit
Python 3.7.1
Shell: bash

azure-cli 2.0.63

```

**Comment by tjprescott** [comment]
Thanks for the report @christophemorio. Since you've identified the solution, would you be open to creating a PR?

**Comment by christophemorio** [comment]
Alright, it's done on #9302

**Comment by tjprescott** [comment]
Thank you @christophemorio!
