### ISSUE TITLE
webapp: az webapp deployment source config-zip should support the packageUri scm API

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-cli#9291]
**Is your feature request related to a problem? Please describe.**
Kudu supports packageUri - Zipdeployment command should support this as well https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file-or-url

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nickwalkmsft** [comment]
This would be great for all kinds of scenarios. I'd also love to see support for this from `az webapp create`, similar to the way `--deployment-source-url` works.

**Comment by panchagnula** [comment]
waiting for this support to be extended to Linux as well - & then add support for this feature.

**Comment by panchagnula** [comment]
Still waiting for the api changes to be available for Linux. @btardif assigning this to you so that you can push for the Linux backend changes here. Thanks!

**Comment by panchagnula** [comment]
Moving this out to the next sprint

**Comment by yonzhan** [comment]
@panchagnula what is the status of this issue ?

**Comment by yonzhan** [comment]
How is the status of this issue ?

**Comment by yonzhan** [comment]
Can we close this issue?

**Comment by yonzhan** [comment]
How about this issue?

**Comment by yonzhan** [comment]
move to S165.

**Comment by yonzhan** [comment]
move to S166.

**Comment by yonzhan** [comment]
move to S167.
