### ISSUE TITLE
Add support to cancel in-flight arm deployments via CLI

### ISSUE THREAD

**Issue by Monte-Hazboun** [Azure/azure-cli#9294]
**Is your feature request related to a problem? Please describe.**
Currently, the only way to cancel in-flight arm deployments programmatically is via the REST api.  Adding support to cancel in-flight deployments would alleviate complexity required when scripting deployments. 

**Describe the solution you'd like**
Add an option to cancel in-flight arm deployments via the az cli. 

**Describe alternatives you've considered**
The only alternative is the REST api, which requires a service principal.  Logging into the portal to cancel requires manual intervention. 

**Additional context**
None

**Comment by yugangw-msft** [comment]
Command coverage gap we need to fill.

**Comment by zhoxing-ms** [comment]
This feature request has been completed by PR #12915
