### ISSUE TITLE
Error on AKS Browser

### ISSUE THREAD

**Issue by imartinez2** [Azure/azure-cli#9301]
## Describe the bug

**Command Name**
`az aks browse`

**Errors:**
```
The Resource 'Microsoft.ContainerService/managedClusters/mmymicroservice' under resource group 'myMicroserviceResources' was not found.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks browse --resource-group {} --name {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.63

```

**Comment by adewaleo** [comment]
Hello @imartinez2, what is the question or issue you are facing.

This error seems clear to me. the resource you were looking for was not found in the resource group you specified. Please make sure you have the correct name and resource group and that you are logged into the correct subscription.
