### ISSUE TITLE
az role assignment list returns empty JSON when it should not

### ISSUE THREAD

**Issue by LRomandine** [Azure/azure-cli#9304]
## Describe the bug

**Command Name**
`az role assignment list`

**Errors:**
No errors but output is incorrect.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Have a storage account with a blob container
- Blob container has a user assigned managed identity role assigned to it
- `az role assignment list --scope "/subscriptions/<<SUBSCRIPTION_ID>>/resourceGroups/<<RESOURCE_GROUP>>/providers/Microsoft.Storage/storageAccounts/<<STORAGE_ACCOUNT>>" --include-inherited --include-groups`
- The output is blank

## Expected Behavior
The behavior should match that of the following PowerShell command which correctly lists the user assigned managed identity role assigned to the container
- `Get-AzRoleAssignment -Scope "/subscriptions/<<SUBSCRIPTION_ID>>/resourceGroups/<<RESOURCE_GROUP>>/providers/Microsoft.Storage/storageAccounts/<<STORAGE_ACCOUNT>>"`

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.63

```

**Comment by yugangw-msft** [comment]
Please use `--all` (Show all assignments under the current subscription.) Or, use `--scope`(/subscriptions/<<SUBSCRIPTION_ID>>/resourceGroups/<<RESOURCE_GROUP>>/providers/Microsoft.Storage/storageAccounts/<<STORAGE_ACCOUNT>>)

CLI does this for consistency that `list` without any arguments should only give you the assignments at the subscription level.

I am closing this but feel free to re-activate if my suggestion doesn't address the issue.

**Comment by ElvenSpellmaker** [comment]
@yugangw-msft This is still an issue and when you use your suggested `--all` it comes back with `ValidationError: Parameter 'scope' can not be None.`...

**Comment by ElvenSpellmaker** [comment]
Also using `--scope /subscriptions/<sub id>` it comes back with an empty array still.

**Comment by yonzhan** [comment]
@jiasli to help with.

**Comment by JasonRodman** [comment]
I am running into the same problem. This only works with the --all option. No other option does anything, always returning an empty array. This is the second cli command today I ran into that simply doesn't work. Frustrating to say the least.

**Comment by jiasli** [comment]
@JasonRodman, it seems your issue is the same as https://github.com/Azure/azure-cli/issues/14302.
