### ISSUE TITLE
enable PodSecurityPolicy for existing Cluster

### ISSUE THREAD

**Issue by kasunsjc** [Azure/azure-cli#9313]
When I follow[ this](https://docs.microsoft.com/en-us/azure/aks/use-pod-security-policies#enable-pod-security-policy-on-an-aks-cluster ) aks documentation to enable  existing PodSecurityPolicy, it mentioned command similar to following 

`az aks update --resource-group aks-cluster-rg --name aks-network-policy --enable-pod-security-policy `

I tried the same command in cloud shell and gives following error

`az aks update --resource-group aks-cluster-rg --name aks-network-policy --enable-pod-security-policy
az aks: 'update' is not in the 'az aks' command group. See 'az aks --help'.`

Cloud shell az version - 2.0.63

When I try it gives following error

## Describe the bug

**Command Name**
`az aks update`

**Errors:**
```
az: error: unrecognized arguments: --enable-pod-security-policy
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks update --resource-group {} --name {} --enable-pod-security-policy`

## Environment Summary
```
Darwin-18.5.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.63

Extensions:
aks-preview 0.2.3
resource-graph 0.1.8
interactive 0.4.1

```

**Comment by kasunsjc** [comment]
Fixed it !!

**Comment by SivaPeddineni2921** [comment]
we are getting error while disabling PSP
unrecognized arguments: --disable-pod-security-policy

I am using latest version
{
  "azure-cli": "2.44.1",
  "azure-cli-core": "2.44.1",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}
