### ISSUE TITLE
webapp: list-publishing-profiles valid query returns empty array 

### ISSUE THREAD

**Issue by JKamsker** [Azure/azure-cli#9324]
## Describe the bug
The command works fine when not using any query.
When using the command with `--query [?publishMethod=='FTP']`, the tool returns an empty set.
Succsessfully tested query on http://jmespath.org

**Command Name**
`az webapp deployment list-publishing-profiles`

**Errors:**
It returns []. 

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az webapp deployment list-publishing-profiles --id {YOUR-ID-HERE} --query [?publishMethod=='FTP']`

## Expected Behavior
Returning just the profile for publishing with ftp.

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.64

```

**Comment by Juliehzl** [comment]
cc @AzureAppServiceCLI @antcp

**Comment by Kotasudhakarreddy** [comment]
@JKamsker we are unable to repro the issue in latest CLI version (2.11.1) . could you please try with the latest CLI version and let us know if you still face the issue.

**Comment by panchagnula** [comment]
Please reopen if this still repros with latest - closing due to lack of response.
