### ISSUE TITLE
Support for updating the min TLS version on deployed Redis in Clustered mode

### ISSUE THREAD

**Issue by archmangler** [Azure/azure-cli#9325]
Is it supported to update the min-tls-version of a Premium, clustered Rediscache instance via the cli ?

Az cli support for this parameter would allow better automation of this configuration feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecb66426-9b0f-be54-5530-0673e6821f39
* Version Independent ID: 3d89a838-9a95-3cfe-ea58-7d7484e94956
* Content: [az redis](https://docs.microsoft.com/en-us/cli/azure/redis?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-redis/azure/cli/command_modules/redis/_help.py)
* Service: **redis-cache**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by archmangler** [comment]
Any update?

**Comment by MECHANDR** [comment]
@archmangler MinimumTlsVersion can be changed through CLI. Sample command: `az redis update --resource-group <resource group name> --name <redis cache name> --set minimumTlsVersion=<tls version>`
