### ISSUE TITLE
az login NoneType

### ISSUE THREAD

**Issue by ThomasHantke** [Azure/azure-cli#9326]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
'NoneType' object is not callable
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 560, in execute
    raise ex
cli/core/commands/__init__.py, ln 618, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 611, in _run_job
    six.reraise(*sys.exc_info())
...
azure/cli/core/_profile.py, ln 787, in find_through_authorization_code_flow
    result = self._find_using_common_tenant(token_entry[_ACCESS_TOKEN], resource)
azure/cli/core/_profile.py, ln 829, in _find_using_common_tenant
    client = self._arm_client_factory(token_credential)
azure/cli/core/_profile.py, ln 751, in create_arm_client_factory
    base_url=self.cli_ctx.cloud.endpoints.resource_manager))
TypeError: 'NoneType' object is not callable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Darwin-17.7.0-x86_64-i386-64bit
Python 3.6.8
Shell: bash

azure-cli 2.0.64

```

**Comment by invidian** [comment]
I'm hitting the same issue on Arch Linux.

## Environment Summary
```
Linux-5.0.12-arch2-1-ARCH-x86_64-with-arch
Python 3.7.3
Shell: bash

azure-cli 2.0.64

```

**Comment by dashesy** [comment]
Same issue on Windows and Python3 in Anaconda (pip install azure-cli). `azure-cli` seems completely broken now!

**Comment by jiasli** [comment]
Hi @dashesy, I tested in Anaconda but can't repro this issue. May I know which version of CLI you are using? Could you try updating to the latest version? Thanks.

**Comment by dashesy** [comment]
Responded [here](https://github.com/Azure/azure-cli/issues/11236#issuecomment-564212694)

**Comment by jiasli** [comment]
> I'm hitting the same issue on Arch Linux.
> 
> ## Environment Summary
> ```
> Linux-5.0.12-arch2-1-ARCH-x86_64-with-arch
> Python 3.7.3
> Shell: bash
> 
> azure-cli 2.0.64
> ```
> 
> BTW duplicate of #9143?

**Comment by jiasli** [comment]
@ThomasHantke, it seems `azure-mgmt-resource` is missing. Could you check https://github.com/Azure/azure-cli/issues/11236#issuecomment-561543508 and share the output? Thanks.

**Comment by jiasli** [comment]
@invidian, we have known issue with Arch Linux that it doesn't honor CLI's [`DEPENDENCIES`](https://github.com/Azure/azure-cli/blob/4f89b707cc28658d41b38a1e03bb240894975f15/src/azure-cli/setup.py#L55-L154). Please install with [official install methods](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest) or pip.

**Comment by jiasli** [comment]
@invidian, we have known issue with Arch Linux that it doesn't honor CLI's [`DEPENDENCIES`](https://github.com/Azure/azure-cli/blob/4f89b707cc28658d41b38a1e03bb240894975f15/src/azure-cli/setup.py#L55-L154). Please install with [official install methods](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest) or pip.

You may contact the package maintainer at https://aur.archlinux.org/packages/python-azure-cli/ or https://aur.archlinux.org/packages/python-azure-git/. These packages use the latest source code from GitHub which may not be compatible with Azure CLI.

**Comment by yonzhan** [comment]
Can we close this issue?
