### ISSUE TITLE
Virtual network gateway custom routes feature

### ISSUE THREAD

**Issue by Nilambari** [Azure/azure-cli#9327]
**Resource Provider**
What is the Azure resource provider your feature is part of?
Network

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
This feature is added for customers to specify Custom routes (list of Ip addresses) on Virtual network gateway to have access to.

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
2019-02-01 

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. This should be on the master branch
of the REST API specs repo.
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-02-01/virtualNetworkGateway.json

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.
This feature is already released.

**Comment by tjprescott** [comment]
Bumping to Sprint 67 due to higher priority direction from NRP.

**Comment by MyronFanQiu** [comment]
@Nilambari Hello. Could you please provide me with the corresponding PR? I cannot figure out which part is related with custom routes feature.

**Comment by MyronFanQiu** [comment]
@Nilambari ping

**Comment by MyronFanQiu** [comment]
@Nilambari Thanks. I will begin the implementation soon.
