### ISSUE TITLE
Application Gateway Custom Error Support

### ISSUE THREAD

**Issue by KaiChiLin** [Azure/azure-cli#9331]
**Description of Feature**
Provide a brief description of the feature. A link to conceptual documentation may be helpful too.
Customers can specify the error page Application Gateway returns for specific http status code. The custom error config is consist of a list of custom errors, which constains status code and error page url and is unique based on the status code. The custom error config can be set on the Application Gateway level (which apply to all the requests) or the listener level (which apply to the requests for this listener)

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
2018-08-01

**Swagger Link**
Provide a link to the resource in the rest API specs repo. Note that this PR should be to the
master branch of the rest API specs repo.
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2018-08-01/applicationGateway.json

**Comment by tjprescott** [comment]
@KaiChiLin this has already been implemented in `az network application-gateway create/update`. Is the API version the same for listeners?

**Comment by KaiChiLin** [comment]
Yes the custom error config in both appgw level and listener level are in the same API version. I receive an email saying "We ran another iteration of gaps searcher basing on the current versions of API specs and Azure CLIv2. Table there contains resources and properties that are currently not implemented in CLIv2." So I thought it's not in CLI yet, but maybe I was wrong.
Do you know if custom error change is implemented for now?

**Comment by tjprescott** [comment]
Custom error pages were added in azure-cli-network 2.2.9. If you believe that it was incomplete, please reopen this issue with what specific items are missing.

**Comment by EvgenyAgafonchikov** [comment]
Thanks for noting this, I missed this property due to different naming between specs and parameters. Added related mapping to our tools config.
