### ISSUE TITLE
Az WebApp Up sees LSW as Windows

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#9334]
In v64, when using Bash on Windows (Linux SubSystem for Windows), `az webapp up` identifies the platform as Windows, which results in Oryx build and deployment issues.  

I expect the `az webapp up` command to identify LSW as Linux
  
    jasonsha@Jason6700:~/temp/jrsdjango$ uname -a
    Linux Jason6700 4.4.0-17763-Microsoft #379-Microsoft Wed Mar 06 19:16:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
    jasonsha@Jason6700:~/temp/jrsdjango$ az webapp up -n jrsDjango
    Creating Resource group 'jasonsha_rg_Windows_centralus' ...
    Resource group creation complete
    Creating App service plan 'jasonsha_asp_Windows_centralus_0' ...
    App service plan creation complete
    Creating app 'jrsDjango' ...
    Webapp creation complete
    Configuring default logging for the app, if not already enabled
    Updating app settings to enable build after deployment
    All done.
    You can launch the app at 'http://jrsdjango.azurewebsites.net'
    To redeploy the app run the command az webapp up -n jrsDjango -l "Central US"

**Comment by panchagnula** [comment]
@JasonRShaver az webapp up doesn't default the OS based the OS its run on. Its based on the code the command detects. You need to run the up command from the directory where the code you want to deploy to app is located. Run the az webapp up command with --dryrun you will see the Src folder, the commands trys  to parse the files Ex. if it detects Node.js files or python files we use Linux, anythign else is windows. Please check the folder you are running the code from & re-run. Let me know if this helps. Thank you.

**Comment by JasonRShaver** [comment]
Ah, the Python logic failed because I didn't have a requirements.txt file.  Is it possible to get a parameter to set the OS or runtime for cases where detection logic doesn't have us covered?

**Comment by panchagnula** [comment]
good to know. We did think about adding a --os-type parameter but was not a high priority.

**Comment by panchagnula** [comment]
@JasonRShaver i am closing this issue please file a new issue to support the OS type if you still want this as a feature request. Thank you.
