### ISSUE TITLE
Creating AMS v3 Asset at CLI using same info as an old/deleted AMS account/live event/asset fails

### ISSUE THREAD

**Issue by plzm** [Azure/azure-cli#9339]
## Describe the bug

**Command Name**
`az ams asset create`

**Errors:**
```
(BadRequest) Cannot insert duplicate key row in object 'dbo.media' with unique index 'Index_BlobStorageUri'. The duplicate key value is (https://pzamssa.blob.core.windows.net/media).

The statement has been terminated.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ams asset create -a {} -g {} -n {} --container {} --storage-account {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.64

Extensions:
interactive 0.4.2

```

**Comment by yonzhan** [comment]
ams

**Comment by hivyas** [comment]
Hi there, this appears to be an old bug that is now fixed. I repro and creating a new asset using information from a deleted asset and it works as expected. Thanks!
