### ISSUE TITLE
az network lb create : Creating a load balancer without a public ip address fails

### ISSUE THREAD

**Issue by johanste** [Azure/azure-cli#934]
az network lb create -n internal -g threetier2 --public-ip-address ''
Long running operation failed with status 'Failed' {
  "error": {
    "code": "InvalidRequestFormat",
    "message": "Cannot parse the request.",
    "details": [
      {
        "code": "MissingJsonReferenceId",
        "message": "Value for reference id is missing. Path properties.frontendIPConfigurations[0].properties.subnet."
      }
    ]
  }
}

**Comment by mayurid** [comment]
@BurtBiel : Can you take a look?

**Comment by BurtBiel** [comment]
This fails by design because a subnet is required if no IP is specified.  I am adding a better error message for this case.
