### ISSUE TITLE
What about managedBy param ?

### ISSUE THREAD

**Issue by alexbenedek** [Azure/azure-cli#9342]
How can i define the managedBy param when i create the Resource Group in the cli?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58c81c4d-10d2-fc04-e707-fcf914f4d540
* Version Independent ID: 8598f788-bd33-a4c8-ed66-593e0fde75d5
* Content: [az group](https://docs.microsoft.com/en-us/cli/azure/group?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-resource/azure/cli/command_modules/resource/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
@kristapratico, this is a simple fix towards `az group create` by exposing a new argument.

**Comment by tjprescott** [comment]
This parameter may be read-only. It would be worth contacting ARM to be sure (i.e. I would *not* look to Swagger for truth unless it says it is)

**Comment by yonzhan** [comment]
add to S164.

**Comment by zhoxing-ms** [comment]
@alexbenedek Why would you want to add the managedBy param when creating a Resource Group?

**Comment by zhoxing-ms** [comment]
Could you tell me the specific meaning of the `managedBy` parameter in the `Resource Groups - Create Or Update` service? @Tiano2017 
doc link: [https://docs.microsoft.com/zh-cn/rest/api/resources/resourcegroups/createorupdate](url)

**Comment by Tiano2017** [comment]
@dandanwang0320 to help.

**Comment by zhoxing-ms** [comment]
@dandanwang0320 Please take a look. I don't think the description of the `--managedBy` parameter in the document is clear what type the ID it is. Could you give a specific example for it?

**Comment by haymansfield** [comment]
I'm not sure why this is closed.

Managed by doesn't appear to be an available parameter on the cli yet is still in the documentation.

**Comment by zhoxing-ms** [comment]
@haymansfield Please use `pip install` to download the latest version of azure cli (2.0.81) and have a try.

**Comment by dcbrown16** [comment]
In case anyone else comes looking, managed-by parameter would be used to specify the tenant that manages a resource group when deploying an Azure Managed Application. There is no reason to use this parameter in deploying standard resource groups, and actually the sample CLI for managed apps doesn't even use this parameter.
https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-applications/scripts/managed-application-cli-sample-create-application
