### ISSUE TITLE
Documentation not generated for az functionapp devops-pipeline

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-cli#9343]
**Describe the bug**
Documentation not generated for az functionapp devops-pipeline

**To Reproduce**
check docs page

**Comment by tjprescott** [comment]
@yugangw-msft @dendeli-msft

**Comment by ahmedelnably** [comment]
This is causing
https://github.com/MicrosoftDocs/azure-docs/issues/30865

**Comment by yugangw-msft** [comment]
dupe of #9336
