### ISSUE TITLE
az storage blob generate-sas fails with self.account_key should not be None

### ISSUE THREAD

**Issue by panesofglass** [Azure/azure-cli#9346]
## Describe the bug

**Command Name**
`az storage blob generate-sas`

**Errors:**
```
self.account_key should not be None.
Traceback (most recent call last):
Temp\pip-install-v1m4qsu_\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 560, in execute
azure\cli\core\commands\__init__.py, ln 618, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 609, in _run_job
azure\cli\command_modules\storage\__init__.py, ln 240, in new_handler
azure\cli\command_modules\storage\__init__.py, ln 183, in handler
azure\cli\core\commands\__init__.py, ln 588, in _run_job
azure\cli\core\commands\__init__.py, ln 297, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 453, in default_command_handler
cli\command_modules\storage\operations\blob.py, ln 423, in generate_sas_blob_uri
multiapi\storage\v2018_03_28\blob\baseblobservice.py, ln 494, in generate_blob_shared_access_signature
multiapi\storage\v2018_03_28\common\_error.py, ln 130, in _validate_not_none
ValueError: self.account_key should not be None.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob generate-sas -c {} -n {} --permissions {} --expiry {}`

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.64

```

**Comment by yugangw-msft** [comment]
We need to validate and error out when no account related credential arguments are provided

**Comment by limingu** [comment]
@panesofglass, I can't repro this bug. Can you rerun the failed command with --debug parameter and email me(limgu@microsoft.com) the logs? So I can look into why the command failed. Thanks.

**Comment by panesofglass** [comment]
Odd; I can no longer reproduce it, either. I don't know what changed. I'll close and re-open if I experience it again. I'll remember the `--debug` flag for future reports.

**Comment by simonbrady** [comment]
I can consistently reproduce this in 2.0.75 by setting `AZURE_STORAGE_SAS_TOKEN` in the shell environment. My theory is that if the environment variable is set, the `generate-sas` command tries to use the token for authorisation, finds the token doesn't grant it sufficient permissions, then falls back to requiring an account key instead. After unsetting `AZURE_STORAGE_SAS_TOKEN` I can no longer reproduce the error.

Seems to be the same behaviour as #10205.

**Comment by bondib** [comment]
I can verify this issue occurs when you try to run the command and your AZ is logged in to a different subscription than where your storage account is

**Comment by yonzhan** [comment]
@evelyn-ys please take a look

**Comment by Juliehzl** [comment]
seems dupe of #17176. @bondib could you check and comment in #17176?

**Comment by bondib** [comment]
Yes - seems like it. The thing is people do not understand why it occurs and why the command just stops working.
For me as well - it took me time to understand why suddenly it stopped working and the error message is misleading - as you know (as a user) that the same thing worked for you earlier.

I think the error message should be more descriptive (not just a key error failure) and say that "Make sure you are trying to create .

I'll add my comments to #17176 as well
