### ISSUE TITLE
Remove "PREVIEW"

### ISSUE THREAD

**Issue by atgreen** [Azure/azure-cli#9353]
This feature is GA now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d37d0e2b-3f2a-2119-805a-9045631b8ef2
* Version Independent ID: 1301306e-263e-0582-1839-b1ace0157bea
* Content: [az openshift](https://docs.microsoft.com/en-us/cli/azure/openshift?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/openshift.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/openshift.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by rloutlaw** [comment]
Resolved in [1452](https://github.com/MicrosoftDocs/azure-docs-cli/pull/1452) in the CLI Docs repo.
