### ISSUE TITLE
Seem unable to update subnet with nsg from another resourcegroup

### ISSUE THREAD

**Issue by tbertenshaw** [Azure/azure-cli#9354]
`az network vnet subnet update -g MyResourceGroup -n MySubnet --vnet-name MyVNet --network-security-group MyNsg`

when using this command and the nsg is in a different vnet i get an error showing that it is trying to reference the nsg as if it is in the same resourcegroup as specified in the command.  It is possible for the nsg to be in a different resourcegroup as i can achieve this via the portal.

```
Resource /subscriptions/{REDACTED SUBSCRIPTIONID}/resourceGroups/MyResourceGroup/providers/Microsoft.Network/networkSecurityGroups/MyNsg referenced by resource /subscriptions/{REDACTED SUBSCRIPTIONID}/resourceGroups/MyResourceGroup/providers/Microsoft.Network/virtualNetworks/MyVNet/subnets/MySubnet was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 385e420c-4bd0-3ddd-d9cd-a9a411ec1f7b
* Version Independent ID: 65172372-f485-3d2b-64aa-57c38ac11538
* Content: [az network vnet subnet](https://docs.microsoft.com/en-us/cli/azure/network/vnet/subnet?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Yes. Use the resource ID.
