### ISSUE TITLE
Attempt to create Azure file share results into SSLError

### ISSUE THREAD

**Issue by radoonech** [Azure/azure-cli#9355]
## Describe the bug

**Command Name**
`az storage share create`

**Errors:**
```
HTTPSConnectionPool(host='ceresforakssa.file.core.windows.net', port=443): Max retries exceeded with url: /myshare?restype=share (Caused by SSLError(SSLError("bad handshake: SysCallError(54, 'ECONNRESET')")))
Traceback (most recent call last):
site-packages/urllib3/contrib/pyopenssl.py, ln 456, in wrap_socket
    cnx.do_handshake()
python3.7/site-packages/OpenSSL/SSL.py, ln 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
...

storage/v2018_03_28/common/storageclient.py, ln 311, in _perform_request
    raise AzureException(ex.args[0])
azure.common.AzureException: HTTPSConnectionPool(host='ceresforakssa.file.core.windows.net', port=443): Max retries exceeded with url: /myshare?restype=share (Caused by SSLError(SSLError("bad handshake: SysCallError(54, 'ECONNRESET')")))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage share create --account-name {} --account-key {} --name {}`

## Environment Summary
```
Darwin-18.5.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.64

```

**Comment by limingu** [comment]
I can't repro this issue.

Tried:
az storage share create --account-name myaccount --name myshare.

Got:
{
  "created": true
}

@radoonech can you provide more details of the urllib3 and OpenSSL versions?

**Comment by radoonech** [comment]
@limingu With Microsoft support we identified that the issue is caused by the corporate firewall intercepting one REST API call. I am closing this one.
