### ISSUE TITLE
az: error: unrecognized arguments: --subscription

### ISSUE THREAD

**Issue by aguerot** [Azure/azure-cli#9356]
**az webapp log tail** documentation states that there is an optional parameter available named **subscription** as described bellow:

`--subscription
  Name or ID of subscription.`

However, when running the command `az webapp log tail -g <my group> -n <my-resource-name> --subscription "<subId>"`, I get the following error message:
`az: error: unrecognized arguments: --subscription`

Is this parameter still available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bee2e287-5fb7-a849-9d3b-87013b783f16
* Version Independent ID: 97f9e1c4-1573-b776-0fce-53c65839d713
* Content: [az webapp log](https://docs.microsoft.com/en-us/cli/azure/webapp/log?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/webapp/log.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/log.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
`--subscription` works for me. Please run `az --version` to make sure you are using newer enough CLI.
I am closing this since I am pretty sure it works, but feel free reactivate if you are on the latest CLI already, and keep on seeing this error

**Comment by pranavtiwari09** [comment]
Hi,
I have been getting this error since yesterday. I have spent many many hours trying to figure out why it is doing so. Even if I remove --subscription argument, use -s instead or do whatever I do - it just doesn't work. 
I am working on AZ301 practice set: https://github.com/MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign/blob/master/Instructions/AZ-301T04_Lab_Mod03_Deploying%20Network%20Infrastructure%20for%20use%20in%20Azure%20Solutions.md
There is no parameter in hub-vnet.json file. 
I am on the latest Azure CLI.
Tried added subscription extension. Just doesn't work. 
Please help - I am stuck.

**Comment by aguerot** [comment]
Hi, 
double check `az` version, it did the trick for me

**Comment by pranavtiwari09** [comment]
> Hi,
> double check `az` version, it did the trick for me

Nope, it is on the latest: Here is output below.
azure-cli                         2.0.71

command-modules-nspkg               2.0.3
core                              2.0.71
nspkg                              3.0.4
telemetry                          1.0.3

Python location '/opt/az/bin/python3'
Extensions directory '/home/pranav/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Aug  8 2019, 03:50:35)
[GCC 5.4.0 20160609]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

**Comment by yugangw-msft** [comment]
@pranavtiwari09,  `azbb` is not a Azure CLI command. Please open an issue at their repository: https://github.com/mspnp/template-building-blocks

**Comment by pranavtiwari09** [comment]
> @pranavtiwari09, `azbb` is not a Azure CLI command. Please open an issue at their repository: https://github.com/mspnp/template-building-blocks

Thanks Yugangw. I will open an issue with them. Thanks for looking into it. 
I agree azbb is not Azure CLI but you install the package through nmp which I did as instructed. 
Just wonder if there is another way of working with Azure Building Blocks. Any pointers will be helpful. 

Thanks again.

**Comment by Ankit191095** [comment]
Hi

I am getting "unrecognized arguments: -–subscription <subid>" error while executing the command :
az iot edge set-modules --hub-name "RtcvHub" --device-id "RtcvEdgeDevice" --content DeploymentManifest.json -–subscription "<my subscription ID>"
My current Azure CLI version is 2.23.0
