### ISSUE TITLE
Workspace ID not found for OMS resource

### ISSUE THREAD

**Issue by berridgd** [Azure/azure-cli#9357]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
  "error": {
    "code": "Workspace ID not found for OMS resource",
    "message": {
      "lang": "en-US",
      "value": "Workspace ID not found for OMS resource"
    },

**To Reproduce**
Copy template from here [.](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-log#log-alert-with-cross-resource-query-using-azure-resource-template). Update template with your own work space for SourceId and Resource2 attributes. Update Resource1 with your own resource to monitor. Deploy the ARM template.

**Expected behavior**
A Microsoft.Insights/scheduledQueryRules resource should be created without error.

**Environment summary**
Powershell v5.1 using Az module.

**Comment by tjprescott** [comment]
What specific CLI command are you having an issue with?

**Comment by berridgd** [comment]
Sorry, wrong repo, closing now.
