### ISSUE TITLE
az: error: unrecognized arguments: --advanced-filter error. 

### ISSUE THREAD

**Issue by amitamit281** [Azure/azure-cli#9358]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.64

**Describe the bug**
az: error: unrecognized arguments: --advanced-filter data.routeTo StringIn finsei all

i am on MacOS Sierra version 10.12.6 using az cli latest version  2.0.64. trying to create event grid subscription using cli with below command.
az eventgrid event-subscription create --name $subName --endpoint-type eventhub -g $resourceGroupName --endpoint /subscriptions/$subscriptionId/resourceGroups/$subResourceGroupName/providers/Microsoft.EventHub/namespaces/$eventhubNameSpaceName/eventhubs/$eventhubName --topic-name  $eventGridName --advanced-filter data.routeTo StringIn finsei all

it throws az: error: unrecognized arguments: --advanced-filter data.routeTo StringIn finsei all error. 

As per documentation it's valid argument https://docs.microsoft.com/en-us/cli/azure/ext/eventgrid/eventgrid/event-subscription?view=azure-cli-latest#ext-eventgrid-az-eventgrid-event-subscription-create  

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by ahamad-MS** [comment]
@amitamit281 

Thanks for reporting this issue.  It is not clear if you are trying to use the CLI module or the extension and which version you are trying. The Advanced Filter option is currently available in event grid extension (and hence, the reference you mentioned is for the extension itself).

I just attempted the same command in shell.portal.com and it is working just fine for me using eventgrid extension version "0.4.2"

Check the extension version using the following command and try to update the extension to newer one if you are using an older version

:~$ az extension list
[
  {
    "extensionType": "whl",
    "name": "eventgrid",
    "version": "0.4.2"
  }
]

:~$ az eventgrid event-subscription create --name <EventSubName> --source-resource-id "/subscriptions/<ID>/resourceGroups/<RG>/providers/Microsoft.EventGrid/domains/<DomainName>" --advanced-filter data.awe StringIn data.routeTo StringIn finsei all error. --endpoint "<URL>"

**Comment by ahamad-MS** [comment]
Information provided for customer. this is by design. Please feel free to contact us or reopen the issue if needed.
