### ISSUE TITLE
Is it possible to specify the virtualMachineProfile.OsProfile.ComputerNamePrefix?

### ISSUE THREAD

**Issue by tbertenshaw** [Azure/azure-cli#9362]
When creating a scaleset ` az vmss create` Is it possible to specify the virtualMachineProfile.OsProfile.ComputerNamePrefix?Additionally if general when using the `az cli`, if the parameter is missing from the cli command in question is there a way of passing it in as a fully qualified parameter. Something like ` -- parameter properties.virtualMachineProfile.OsProfile.ComputerNamePrefix="$myPrefix"`
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0408c294-207a-2b72-7b93-e09121602b75
* Version Independent ID: 852cb67b-70c6-b811-3b0a-5d5b84b8a911
* Content: [az vmss](https://docs.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#az-vmss-create)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machine-scale-sets**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
// CC: @adewaleo, @tjprescott, this is about the generic setter we have talked about beffore

**Comment by adewaleo** [comment]
@yugangw-msft @tjprescott, yes this is about the generic setter argument. I would be open to discuss this more when I am back. Interestingly enough, this is similar to the now closed #8402

**Comment by qwordy** [comment]
https://docs.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#az-vmss-create
`az vmss update` has `--set` parameter.

I think it's a good idea that we can specify `ComputerNamePrefix` in `az vmss create` command directly.

**Comment by adewaleo** [comment]
> https://docs.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#az-vmss-create
> `az vmss update` has `--set` parameter.
> 
> I think it's a good idea that we can specify `ComputerNamePrefix` in `az vmss create` command directly.

Sounds good. This was done not too long ago with [`az vm create --computer-name`](https://github.com/Azure/azure-cli/pull/9306/files#diff-56c1e6c2a52ce59ca10e73f68ccb7706R8).

**Comment by xpillons** [comment]
Being able to control the computerNamePrefix thru the CLI will unblock some HPC scenarios. Especially there are applications that doesn't support such long names, some are crashing like OpenMPI 4.0.1 or others failed to get licences like Fluent. Because the name is random there is no easy way to work around this

**Comment by microkost** [comment]
Just note: 
azure-cli 2.0.71 *
az vmss create --name XXX... --computer-name-prefix machine...
az : ERROR: az: error: unrecognized arguments: --computer-name-prefix machine

azure-cli 2.0.75
It's OK, just for debug of someone dealing with error.

**Comment by qwordy** [comment]
> 
> 
> Just note:
> azure-cli 2.0.71 *
> az vmss create --name XXX... --computer-name-prefix machine...
> az : ERROR: az: error: unrecognized arguments: --computer-name-prefix machine
> 
> azure-cli 2.0.75
> It's OK, just for debug of someone dealing with error.

Thank you for the tips.
