### ISSUE TITLE
Crash while trying to deploy to Azure Functions

### ISSUE THREAD

**Issue by nebrius** [Azure/azure-cli#9369]
## Describe the bug

**Command Name**
`az functionapp deployment source config-zip`

**Errors:**
```
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 560, in execute
    raise ex
cli/core/commands/__init__.py, ln 618, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 611, in _run_job
    six.reraise(*sys.exc_info())
...
lib/python3.6/json/decoder.py, ln 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
lib/python3.6/json/decoder.py, ln 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp deployment source config-zip --subscription {} --resource-group {} -n {} --src {}`

## Environment Summary
```
Linux-4.4.0-17763-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.64

```

**Comment by ahmedelnably** [comment]
@nebrius can you please share the function app name so we can investigate more

**Comment by nebrius** [comment]
@ahmedelnably unfortunately the function app has since been deleted because we needed to clean up our subscription.

**Comment by ankitkumarr** [comment]
@nebrius, do you remember if you were on a Consumption plan or an App Service plan? Currently this call is not supported for Linux Consumption.

**Comment by asears** [comment]
Another issue which causes this is when  Firewall/Access Restriction rules are enabled for the scm site and the machine deploying does not have ip allowed.

**Comment by nebrius** [comment]
@ankitkumarr IIRC correctly, it was on a consumption plan running on Windows. (I used all the defaults when creating through the portal).

**Comment by ahmedelnably** [comment]
Please reopen if the issue still persists in the latest CLI version

**Comment by cyberpion-yotam** [comment]
For anyone having these same issues, I just spent a few hours finding out that @asears couldn't be more correct.
I've been getting this issue when running with the azure-functions-deploy:1.0.0 (so make sure to check out the Access Restriction rules!)
