### ISSUE TITLE
Ability to create docker registry endpoints for devops extension from the azure cli so that it can be scripted.

### ISSUE THREAD

**Issue by prateeknayak** [Azure/azure-cli#9370]
**Is your feature request related to a problem? Please describe.**
I want to automate setting up azure devops projects where i want to be able to bootstrap things like Github connection, External Docker Registry connections etc. In the UI I can create service-endpoints and use it in the pipeline but the devops extension doesn't allow me to create the same.

**Describe the solution you'd like**
I would like the azure devops extension to support the creation of service endpoints for all the types that are supported in the GUI.

**Describe alternatives you've considered**
Just do it in the GUI.

**Comment by yugangw-msft** [comment]
Please open an issue at https://github.com/Azure/azure-devops-cli-extension
