### ISSUE TITLE
az ad app update --add replyUrls overwrites app registration

### ISSUE THREAD

**Issue by midgleyc** [Azure/azure-cli#9375]
**Describe the bug**
`az ad app update --add replyUrls` overwrites the `replyUrls` field instead of adding to it 

**To Reproduce**
1. Create a new app registration. Record the object ID `OBJ_ID`
2. Add a Reply Url of https://example.com/test
3. Run `az ad app update --id "OBJ_ID" --add replyUrls "https://example.com/test2"`

**Expected behavior**
The reply Urls list should contain both https://example.com/test and https://example.com/test2

**Environment summary**
WSL version 2.0.64

**Additional context**
Based on --debug output, this is correctly sending a PATCH request. Either I've misintepreted the syntax, this is a REST API bug, or the REST API isn't supposed to be able to handle this call. If the second option, can this be forwarded to the correct team?

**Comment by yugangw-msft** [comment]
It is bug that we should fix.

**Comment by abrignola** [comment]
Hi, when will this fix be available? The current version of the cli 2.0.75 is still overwriting the replyurls

**Comment by yonzhan** [comment]
@jiasli please take a look.

**Comment by abrignola** [comment]
any update on this?

**Comment by jiasli** [comment]
Hi @abrignola, this issue is already addressed. 

```
> az ad app show --id 93dde3da-9fca-47dd-aee2-409b402ffed3

  "replyUrls": [
    "https://myapp.com"
  ],

> az ad app update --id 93dde3da-9fca-47dd-aee2-409b402ffed3 --add replyUrls "https://example.com/test"

> az ad app show --id 93dde3da-9fca-47dd-aee2-409b402ffed3

  "replyUrls": [
    "https://myapp.com",
    "https://example.com/test"
  ],
```

For MS Graph approach, you may refer to https://github.com/Azure/azure-cli/issues/9501#issuecomment-610979930. (Also see https://github.com/Azure/azure-cli/issues/12946)
