### ISSUE TITLE
Azure CLI from Azure functions

### ISSUE THREAD

**Issue by dariuszbz** [Azure/azure-cli#9376]
Hi,

I would like to run az cli from azure function powershell.

I will help me to use Azure functions with Azure cli to manage my Azure environment.

So far can't load Az modules,

**Comment by ahmedelnably** [comment]
@dariuszbz This is currently not supported. Is it possible to do it using Azure PowerShell?

**Comment by dariuszbz** [comment]
I can use az cli from powershell and cmd.

I can't use azure rm from azure functions as well.


The only option I see is azure automation and azure rm + run as account.

**Comment by ahmedelnably** [comment]
We announced the public preview of Azure Functions support for PowerShell, if the commands you want to use is also represented in Azure PowerShell, you can write a PowerShell function to run these commands

https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell

**Comment by dariuszbz** [comment]
Nor az cli, azure rm work.

What do you mean azure power shell? Is it azure rm module ? AZ CLI? What
are you referring to, please ?

**Comment by dariuszbz** [comment]
It works from vscode (4ex Get-AzContext), but not from azure functions it
self.

**Comment by dariuszbz** [comment]
Ok I found:
first on your VM/workstation:
Connect-AzAccount
Save-AzContext

copy context json file to your azure function file system.

in your functions:
Import-AzContext -Path "D:\\home\\site\\wwwroot\\<you function
name>\\azctx.json"
$az = Get-AzContext
write-host $az


works.

**Comment by ahmedelnably** [comment]
Closed as resolved
