### ISSUE TITLE
DDoS Policy Customization Feature

### ISSUE THREAD

**Issue by mancgupta** [Azure/azure-cli#9380]
**Resource Provider**
What is the Azure resource provider your feature is part of?

`Azure.Network`

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.

`DDoS Policy Customization is a feature to enrich the Azure DDoS Protection service. Using this feature, customers can choose to manually set DDoS protection parameters overriding what the product would automatically do in its normal course of action.`

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
`Network 2018-12-01`

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. This should be on the master branch
of the REST API specs repo.
`https://github.com/Azure/azure-rest-api-specs/pull/4897`

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.

**Comment by tjprescott** [comment]
Bumping to Sprint 68 due to higher priority direction from NRP.

**Comment by MyronFanQiu** [comment]
@mancgupta Hello. What's the metric of these two fields `trigger_rate_override` and `sourceRateOverride` ? Does the word `rate` represent a number or something else? 
https://github.com/Azure/azure-rest-api-specs/blob/ad759850354ddb7b4ffea0a49b70243fd9ec5a42/specification/network/resource-manager/Microsoft.Network/stable/2019-04-01/ddosCustomPolicy.json#L336-L346

**Comment by mancgupta** [comment]
> @mancgupta Hello. What's the metric of these two fields `trigger_rate_override` and `sourceRateOverride` ? Does the word `rate` represent a number or something else?
> https://github.com/Azure/azure-rest-api-specs/blob/ad759850354ddb7b4ffea0a49b70243fd9ec5a42/specification/network/resource-manager/Microsoft.Network/stable/2019-04-01/ddosCustomPolicy.json#L336-L346

It's an integer value but input is taken as a string.

**Comment by MyronFanQiu** [comment]
> > @mancgupta Hello. What's the metric of these two fields `trigger_rate_override` and `sourceRateOverride` ? Does the word `rate` represent a number or something else?
> > https://github.com/Azure/azure-rest-api-specs/blob/ad759850354ddb7b4ffea0a49b70243fd9ec5a42/specification/network/resource-manager/Microsoft.Network/stable/2019-04-01/ddosCustomPolicy.json#L336-L346
> 
> It's an integer value but input is taken as a string.

so, the range of these two fields is 0-infinity. Am I right?

**Comment by MyronFanQiu** [comment]
> > @mancgupta Hello. What's the metric of these two fields `trigger_rate_override` and `sourceRateOverride` ? Does the word `rate` represent a number or something else?
> > https://github.com/Azure/azure-rest-api-specs/blob/ad759850354ddb7b4ffea0a49b70243fd9ec5a42/specification/network/resource-manager/Microsoft.Network/stable/2019-04-01/ddosCustomPolicy.json#L336-L346
> 
> It's an integer value but input is taken as a string.

Meanwhile, the type of this filed is array. https://github.com/Azure/azure-rest-api-specs/blob/8a1e364ceba55f27ec737eb3bc48a83cdcd0b70d/specification/network/resource-manager/Microsoft.Network/stable/2019-04-01/ddosCustomPolicy.json#L311 Could customers provide more than one `ProtocolCustomSettingsFormat`? Because there is no id/name of `ProtocolCustomSettingsFormat`. A little bit strange for this filed to be an array.

**Comment by MyronFanQiu** [comment]
@mancgupta Is this feature available in the Azure Cloud? I checked several regions like eastus, eastus2, westus, westus2, centralus. However, this feature is not available in the above locations.

**Comment by mancgupta** [comment]
> > > @mancgupta Hello. What's the metric of these two fields `trigger_rate_override` and `sourceRateOverride` ? Does the word `rate` represent a number or something else?
> > > https://github.com/Azure/azure-rest-api-specs/blob/ad759850354ddb7b4ffea0a49b70243fd9ec5a42/specification/network/resource-manager/Microsoft.Network/stable/2019-04-01/ddosCustomPolicy.json#L336-L346
> > 
> > 
> > It's an integer value but input is taken as a string.
> 
> so, the range of these two fields is 0-infinity. Am I right?

We have internal thresholds on the max rate possible depending up network protocol.

**Comment by mancgupta** [comment]
> @mancgupta Is this feature available in the Azure Cloud? I checked several regions like eastus, eastus2, westus, westus2, centralus. However, this feature is not available in the above locations.

Only the APIs are available. It's not available on portal and PS yet.

**Comment by mancgupta** [comment]
> > @mancgupta Is this feature available in the Azure Cloud? I checked several regions like eastus, eastus2, westus, westus2, centralus. However, this feature is not available in the above locations.
> 
> Only the APIs are available. It's not available on portal and PS yet.

Currently we don't have any customer using this feature.

**Comment by MyronFanQiu** [comment]
@mancgupta So it seems that this issue doesn't have high priority. I will move this one to the next sprint.
cc @MikhailTryakhov

**Comment by number213** [comment]
@MyronFanQiu could you please take a look at this issue again? It seems the resource is available in all regions now
```powershell
PS C:\Users\v-anevse> $rp = Get-AzResourceProvider -ProviderNamespace Microsoft.Network | Where-Object { $_.ResourceTypes[0].ResourceTypeName -eq "ddosCustomPolicies" }
PS C:\Users\v-anevse> $rp.Locations
East US
North Europe
West Europe
East Asia
Southeast Asia
North Central US
South Central US
Central US
East US 2
Japan East
Japan West
Brazil South
Australia East
Australia Southeast
Central India
South India
West India
Canada Central
Canada East
West Central US
West US 2
UK West
UK South
Korea Central
Korea South
France Central
Australia Central
South Africa North
UAE North
West US
Central US EUAP
East US 2 EUAP
```

**Comment by MyronFanQiu** [comment]
@number213 No problem. I will take a look soon

**Comment by MyronFanQiu** [comment]
@number213 Hello. I still get errors like "Region centralus is not enabled for DdosCustomPolicy feature." and "Region eastus is not enabled for DdosCustomPolicy feature." Is there a feature flag which should be enabled for my subscription?

**Comment by number213** [comment]
@MyronFanQiu strange, I don't see anything related to ddos in my enabled flags
@mancgupta could you please clarify if you need to get ddos custom policy activated in any way?

**Comment by yonzhan** [comment]
@number213 @mancgupta  CLI is blocked from testing. Any update for this ?

**Comment by mancgupta** [comment]
@yonzhan @number213 This feature is disabled in NRP side on all the prod regions, that's why it's returning region not enabled. Since feature is not active, can we hold off with the testing. I will enable the feature and the thread.

**Comment by yonzhan** [comment]
Close it for now. Please reopen or create another issue when it is enabled.
