### ISSUE TITLE
az ad sp create-for-rbac -n <> : flakiness

### ISSUE THREAD

**Issue by akramwaseem** [Azure/azure-cli#9384]
## Describe the bug
When I run the below command, it should be able to create the service principal account with name my-test-app but for some reason on the portal I see it as Display Name : azure-cli-2019-05-14-04-00-18.
**az ad sp create-for-rbac -n my-test-app  --skip-assignment** 

**Command Name**
`az ad sp create-for-rbac -n my-test-app --skip-assignment`

**Errors:**
Creates the service principal app with name "azure-cli-2019-05-14-04-00-18" rather than given name in the command.
az ad sp create-for-rbac -n my-test-app  --skip-assignment

## To Reproduce:
Run below command 
**az ad sp create-for-rbac -n my-test-app  --skip-assignment**  and try listing the service principal using the command **az ad sp list --show-mine** 
Service Principal account should be created and listed under give name **my-test-app** but it is listed under different name **azure-cli-2019-05-14-04-00-18**. Upon checking in azure portal it is displayed as "azure-cli-2019-05-14-04-00-18".

This is happening through azure-cli only.

## Expected Behavior
Should be able to create the Service principal with the given name, but creates the name with az cli name and time stamp.(azure-cli-2019-05-14-04-00-18)

## Environment Summary
```
Darwin-18.5.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.64

```

**Comment by yugangw-msft** [comment]
Can you please double check that you are using the latest Azure CLI. This has been fixed for a while...
```
(env27) D:\sdk\azure-cli>az ad sp create-for-rbac -n my-test-app --skip-assignment
Changing "my-test-app" to a valid URI of "http://my-test-app", which is the required format used for service principal names
{
  "appId": "eabdc42b-a2ac-4317-aa81-459d3e75c4f0",
  "displayName": "my-test-app",
  "name": "http://my-test-app",
  "password": "....",
  "tenant": "..."
}
```

**Comment by akramwaseem** [comment]
@yugangw-msft -- This is happening to me for the past couple of days when I upgraded to the latest version.
If you look at my issue you can see the az version I am using mentioned under Environment Summary.
I am on the latest version when this happened and I have to move to 2.0.63 because it was blocking us.

**Comment by yugangw-msft** [comment]
Did you see the warning of `Changing "my-test-app" to a valid URI of "http://my-test-app`?

**Comment by akramwaseem** [comment]
> Did you see the warning of `Changing "my-test-app" to a valid URI of "http://my-test-app`?

I am not sure, I can try it quickly and will let you know.
Thanks.

**Comment by yugangw-msft** [comment]
@akramwaseem, I am closing this as I am fairly certain there was an old CLI involved. But that said, anything could happen, do reactivate if you are still blocked

**Comment by akramwaseem** [comment]
@yugangw-msft -- Those env settings are populated by az itself when I did az feedback.

Environment Summary
Darwin-18.5.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.64


I am using the 2.0.63 since the latest one had issues.
Let me try it again by installing the latest version.

**Comment by akramwaseem** [comment]
▶ az --version
azure-cli                         2.0.64


Looks like its working now but below are the some of the names which got created when using the latest version of az

azure-cli-2019-05-14-23-31-30
azure-cli-2019-05-14-23-31-57
azure-cli-2019-05-14-23-32-23
azure-cli-2019-05-15-20-31-54.

Will reopen if I keep seeing this.

Thanks

**Comment by teplyuska** [comment]
Hello

I have this issue using 2.0.64 where displayName and signInUrl is set to "azure-cli-DATE"

It only happens when i use --role and --scopes like this:

az ad sp create-for-rbac --name http://co-dep-env --role co-dep-env-role --scopes /subscriptions/SUBSCRIPTION_ID/resourceGroups/co-dep-env-group

If i only use --name it will correctly set displayName and signInUrl:

az ad sp create-for-rbac --name http://co-dep-env

**Comment by akramwaseem** [comment]
Hi @yugangw-msft ,

Turns out this is happening on 2.0.63 too sometimes.
Can we reopen this ?

**Comment by yugangw-msft** [comment]
Please reach to me at yugangw at microsoft dot com with the trace of using `--debug`

**Comment by yugangw-msft** [comment]
Reopening to track one ask that on `--name http://foo.bar`, that the display name should be `foo.bar`

**Comment by colemickens** [comment]
how many years will this bug persist?

**Comment by akramwaseem** [comment]
@yugangw-msft  — Tried this  az ad sp create-for-rbac -n "http://test-aks-sp" --skip-assignment -o json 2>&1

OUTPUT :


That is what I see in azure portal : azure-cli-2019-07-29-22-33-09

**Comment by hofnarwillie** [comment]
(Using AZ CLI version 2.0.69)

The behaviour can be replicated by adding the `http://` prefix to the service principal name

```
sh-4.2# az ad sp create-for-rbac -n foo
Changing "foo" to a valid URI of "http://foo", which is the required format used for service principal names
```

after the above executes it creates an app with displayName "foo". However, the warning message makes me think I should have added the "http://", so I tried:

```
sh-4.2# az ad sp create-for-rbac -n http://foo
```

this time it doesn't give the warning, but results in the generated app displayName of `azure-cli-<dateTime>`.

**Comment by yugangw-msft** [comment]
@akramwaseem @hofnarwillie, please check out #10196 which I will merge for release on Aug 27.
@jiasli, please review

**Comment by jiasli** [comment]
PR #10196 has been merged.

**Comment by akramwaseem** [comment]
@yugangw-msft -- It's still the same. I don't see anything changed even after upgrading to latest version.
▶ az --version                                                                                                                                                     (K8AKSGreenProsDv2/default)
azure-cli                         2.0.72 *

command-modules-nspkg               2.0.3
core                              2.0.72 *
nspkg                              3.0.4
telemetry                          1.0.3

Python location '/usr/local/Cellar/azure-cli/2.0.72_1/libexec/bin/python'
Extensions directory '/Users/wmohamme/.azure/cliextensions'

Python (Darwin) 3.7.4 (default, Sep  7 2019, 18:27:02)
[Clang 10.0.1 (clang-1001.0.46.4)]

Legal docs and information: aka.ms/AzureCliLegal

This is what I ran : az ad sp create-for-rbac -n http://test-sp-again --skip-assignment -o json
This is what I see in Portal : azure-cli-2019-09-18-17-30-30.

Please reopen the issue.

**Comment by jiasli** [comment]
Please test if 2.0.73 work. Here is my result:

```
az ad sp create-for-rbac -n http://test-sp-again0919 --skip-assignment -o json
{
  "appId": "",
  "displayName": "test-sp-again0919",
  "name": "http://test-sp-again0919",
  "password": "",
  "tenant": ""
}
```

**Comment by jiasli** [comment]
Please test if 2.0.73 works. Here is my result:

```
az ad sp create-for-rbac -n http://test-sp-again0919 --skip-assignment -o json
{
  "appId": "",
  "displayName": "test-sp-again0919",
  "name": "http://test-sp-again0919",
  "password": "",
  "tenant": ""
}
```
