### ISSUE TITLE
[Install] Download tab completion script even when user turns down tab completion

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#939]
Currently, if you run the installer and answer "no" to whether you want to enable tab completion, it skips downloading the script, so that if you later change your mind, you can't simply follow the directions on the repo to enable it. 

I'd recommend downloading the script regardless and then simply don't run it if they answer "no". That way they can more easily opt-in at a later time.

**Comment by derekbekoe** [comment]
Yes currently, if you choose 'no' or tab completion fails (#1009), there is no way to add tab completion later.

When we run into these cases, we can do as suggested and download the tab completion file anyway and print instructions on how the user can source the tab completion file in their own rc file.

Example with choosing "n":
```
Installation successful.
Enable shell/tab completion? [y/N]: n
Add 'source /usr/local/az/az.completion' to your rc file and restart your shell to enable tab completion.
Run the CLI with /usr/local/bin/az --help
```

Example with tab completion error:
```
Installation successful.
Enable shell/tab completion? [y/N]: y
Unable to enable tab completion. No '/var/root/.bashrc' or '/var/root/.bash_profile' file found.
Add 'source /usr/local/az/az.completion' to your rc file and restart your shell to enable tab completion.
Run the CLI with /usr/local/bin/az --help
```

**Comment by colemickens** [comment]
related: https://github.com/Azure/azure-cli/issues/630
