### ISSUE TITLE
[ACR] 'az acr run --cmd' doesn't render the built-in values properly

### ISSUE THREAD

**Issue by northtyphoon** [Azure/azure-cli#9398]
**Describe the bug**
`az acr run -r myregistry --cmd "bash echo {{.Run.Registry}}" /dev/null`

**Expected behavior**
The output shows `myregistry.azurecr.io` 

**Actual behavior**
The output shows `{{.Run.Registry}}`

**Comment by northtyphoon** [comment]
@sajayantony @samarths-msft

**Comment by northtyphoon** [comment]
@ElianaLiberman can you take a look?

**Comment by northtyphoon** [comment]
@ggonzalere

**Comment by sajayantony** [comment]
@northtyphoon @ggonzalere can this be closed?
