### ISSUE TITLE
Failed to create hdinsight application with azure cli

### ISSUE THREAD

**Issue by daqing613** [Azure/azure-cli#9400]
When i executed the below command,
```
az hdinsight application create --application-name 'wptest01' --name wphadoop01 --resource-group wp-rs --script-action-name  empty_scrpit --script-uri myurl --application-type CustomApplication --edgenode-si
ze Standard_D4 --https-endpoint-access-mode webpage --https-endpoint-destination-port 7170 --https-endpoint-location "https://wphadoop01-ran.apps.azurehdinsight.cn:443"  --https-endpoint-public-port 443 --vn
et-name wp-vnet-ce --subnet default
```
I got the error: 
`Https Endpoint 'subDomainSuffix' cannot be null or empty`

Thanks in advance.

**Comment by yugangw-msft** [comment]
//CC @idear1203

**Comment by idear1203** [comment]
Thanks @daqing613 for notification. We are looking. Please create your application through Azure portal.

**Comment by daqing613** [comment]
@idear1203 So sorry for replying late. I need to create the application automatically.  Do you have other workaroud except Azure portal ?   restful api or cli?

**Comment by idear1203** [comment]
Hi @daqing613 we are currently fixing this issue. It takes about 3 or 4 weeks from now. I will let you know the process. You can use RESTful API as a workaround. Add `subDomainSuffix` in the HTTP request payload

**Comment by daqing613** [comment]
@idear1203 Sounds great! Thanks for your updates.

**Comment by idear1203** [comment]
Hi @daqing613 The PR has been merged and it will be available in the next Azure CLI release:)
