### ISSUE TITLE
Get and List commands for PeerExpressRouteCircuitConnection child resource

### ISSUE THREAD

**Issue by syfarogh** [Azure/azure-cli#9404]
**Resource Provider**
What is the Azure resource provider your feature is part of?
Network

**Description of Feature or Work Requested**
Provide a brief description of the feature or work requested. A link to conceptual documentation may be helpful too.
A new resource PeerExpressRouteCircuitConnection has been added. The resource is **read-only**. It is a child resource of ExpressRouteBgpPeering. Request is to add commands in cli for point query and list query. Get a particular PeerExpressRouteCircuitConnection resource and List all PeerExpressRouteCircuitConnection resources in a peering.

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?
2019-02-01

**Swagger Link**
Provide a link to the location of your feature(s) in the REST API specs repo. This should be on the master branch
of the REST API specs repo.
Link from master Repo:

Specification link: (line 711 - see next link for exact changes that were made)
https://github.com/Azure/azure-rest-api-specs/blob/94cbaeeaf29ef55c283f698877d654b5c3f19b2a/specification/network/resource-manager/Microsoft.Network/stable/2019-02-01/expressRouteCircuit.json

Change link from PR: (
https://github.com/Azure/azure-rest-api-specs/pull/5266/files#diff-c571d0be52025b85c9bb8614eb0079af

Example for Get:
https://github.com/Azure/azure-rest-api-specs/blob/94cbaeeaf29ef55c283f698877d654b5c3f19b2a/specification/network/resource-manager/Microsoft.Network/stable/2019-02-01/examples/PeerExpressRouteCircuitConnectionGet.json

Example for List:
https://github.com/Azure/azure-rest-api-specs/blob/94cbaeeaf29ef55c283f698877d654b5c3f19b2a/specification/network/resource-manager/Microsoft.Network/stable/2019-02-01/examples/PeerExpressRouteCircuitConnectionList.json

**Target Date**
If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates,
it will help us prioritize your request against other requests.
July 2018

**Comment by yugangw-msft** [comment]
CC: @tjprescott

**Comment by tjprescott** [comment]
Bumping to Sprint 69 due to higher priority direction from NRP.

**Comment by MyronFanQiu** [comment]
@syfarogh Hello. I checked the existed code. I have a question, is this feature request related with current command `az network express-route peering connection`? you can check that we have `az network express-route peering connection show` command for now.

**Comment by syfarogh** [comment]
they are logically related, but PeerExpressRouteCircuitConnection is a separate resource.
_az network express-route peering connection_ is for ExpressRouteCircuitConnection resource.

**Comment by syfarogh** [comment]
> @syfarogh Hello. I checked the existed code. I have a question, is this feature request related with current command az network express-route peering connection? you can check that we have az network express-route peering connection show command for now.

they are logically related, but PeerExpressRouteCircuitConnection is a separate resource.
az network express-route peering connection is for ExpressRouteCircuitConnection resource.
