### ISSUE TITLE
Azure subscription check error 

### ISSUE THREAD

**Issue by Mrmozz** [Azure/azure-cli#9407]
## Describe the bug

**Command Name**
`az policy assignment list`

**Errors:**
```
'type'
Traceback (most recent call last):
Temp\pip-install-v1m4qsu_\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 560, in execute
azure\cli\core\commands\__init__.py, ln 618, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 611, in _run_job
Local\Temp\pip-install-v1m4qsu_\six\six.py, ln 693, in reraise
azure\cli\core\commands\__init__.py, ln 588, in _run_job
azure\cli\core\commands\__init__.py, ln 297, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 453, in default_command_handler
azure\cli\command_modules\resource\custom.py, ln 1141, in list_policy_assignment
KeyError: 'type'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az policy assignment list --scope {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.64

```

**Comment by yugangw-msft** [comment]
//CC: @zikalino

**Comment by Juliehzl** [comment]
Hi @Mrmozz, can you show me more information with `--debug` appended? I cannot reproduce your issue with azure cli 2.0.73.

**Comment by Juliehzl** [comment]
Given no response for a long time, I will close the issue and if you still have problem, feel free to reopen it  or create a new one.
