### ISSUE TITLE
Private DNS questions

### ISSUE THREAD

**Issue by gucarreira** [Azure/azure-cli#9410]
In documentation said "--registration-vnets
Space-separated names or IDs of virtual networks that register hostnames in this DNS zone."
But when I put only two vnets I received "Operation failed with status: 'Bad Request'. Details: Registration virtual networks per private zone limit exceeded in subscription 99999-999-99-99-99."
In my subscription I can't find my quota private DNS x vNets registration.

And also the "--add" parameter doesn't explain well which properties we could use.

thanks

Gustavo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ccaec50-407e-bf8a-6004-a824c2094c5b
* Version Independent ID: 8d2f2443-7636-2462-7806-0916a8603a0d
* Content: [az network dns zone](https://docs.microsoft.com/en-us/cli/azure/network/dns/zone?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by haroldrandom** [comment]
@gucarreira Sorry for the late reply. We have checked that limitation. According to the limitatin https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits

![image](https://user-images.githubusercontent.com/14357159/69946705-1fd23880-1527-11ea-8802-d47f9b79e16c.png)

Number of private DNS zones a virtual network can get linked to with auto-registration enabled  is 1 by default.

**Also If you need expand the limitation please contact Azure Support.**

So the behavior is as expected. It's for the backward-compatible so marked it as an array ahead. 
I don't know until you reported.

We will modify the doc.

**Comment by haroldrandom** [comment]
for `--add` option is a generic update option, the syntax is subjected to JMESpath, please take a look their site http://jmespath.org/
