### ISSUE TITLE
How to downgrade from 2.0.64 to mitigate its breaking change for msbot?

### ISSUE THREAD

**Issue by dawwa** [Azure/azure-cli#9414]
Wondering where can download the previous versions MSI, we started getting msbot CLI error and figured out it's due to breaking change in Azure CLI, but we could not find the previous versions of MSI, e.g., would you please tell where we can download the 2.0.63 MSI installer?

**Comment by yugangw-msft** [comment]
https://azurecliprod.blob.core.windows.net/msi/azure-cli-2.0.63.msi
