### ISSUE TITLE
KeyVault certificate policy format

### ISSUE THREAD

**Issue by adi658** [Azure/azure-cli#9423]
What does the json look like? How difficult was it to provide a json for policy on this page? I am trying to create a cert in vault. But it only creates SELF SIGNED. I need to create a key and csr for the non-partnered ca which i am just not able to find. Pls help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9c661d7-bf43-5354-015e-3859f30a42a2
* Version Independent ID: fa69e552-5904-ce97-d02c-915c819bdde1
* Content: [az keyvault certificate](https://docs.microsoft.com/en-us/cli/azure/keyvault/certificate?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-keyvault/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by xsreality** [comment]
+1. There is no help regarding JSON policy definition. No links to external page where this is explained. Currently trying to figure out how to create a certificate that is not signed by a known issuer.

**Comment by adi658** [comment]
Yes exactly, facing the same issue. Infact I contacted the Microsoft azure support team and they are yet to get back to me even after 4 days. Also, in powershell we have apis but same apis are not there in azure CLI. For ex : I can login yo portal and download certificate in pfx format but how do I do it using CLI? No clue. No examples given.

**Comment by xsreality** [comment]
@adi658 Please check if this one helps? https://github.com/Azure/azure-cli/issues/7489

**Comment by adi658** [comment]
Awesome... that helped.. So we use download secret instead of download certificate. Wierd :(

**Comment by Antiohne** [comment]
See the blog post of Peter Hobor: https://techblog.hobor.hu/2018/08/26/self-signed-certificate-with-sans-using-azure-cli-keyvault/

**Comment by jiasli** [comment]
You may use `az keyvault certificate get-default-policy --scaffold` to get a template to work with. This is a Python representation of `Create Certificate REST API`'s body: https://docs.microsoft.com/en-us/rest/api/keyvault/createcertificate/createcertificate#certificatepolicy

**Comment by haymansfield** [comment]
> You may use `az keyvault certificate get-default-policy --scaffold` to get a template to work with. This is a Python representation of `Create Certificate REST API`'s body: https://docs.microsoft.com/en-us/rest/api/keyvault/createcertificate/createcertificate#certificatepolicy

While the document referenced is useful, it should be pointed out the formats have a lot of differences.

**Comment by bim-msft** [comment]
As @jiasli said, `az keyvault certificate get-default-policy --scaffold` will give you a rough frame to work with. Closing this issue due to long time inactivity.

**Comment by mikedzikowski** [comment]
Hello, we are facing this issue. 

Trying this from the documentation:
--policy -p
JSON encoded policy definition. Use @{file} to load from a file(e.g. @my_policy.json).

How can we get this syntax to work? 
`az keyvault certificate create --vault-name "kv-LED-devring0-01" -n "aksCert" -p @cert_policy.json

At line:1 char:82
+ ... e --vault-name "kv-LED-devring0-01" -n "aksCert" -p @cert_policy.json
+                                                         ~~~~~~~~~~~~
The splatting operator '@' cannot be used to reference variables in an expression. '@cert_policy' can be used only as an argument to a command. To reference variables in an expression use '$cert_policy'.  
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : SplattingNotPermitted`

Tested created an object containing the json as $var

az keyvault certificate create --vault-name "kv-LED-devring0-01" -n "aksCert" -p $var

Failed to parse JSON: {
Error detail: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
The JSON may have been parsed by the shell. See https://docs.microsoft.com/cli/azure/use-cli-effectively#quoting-issues
PowerShell requires additional quoting rules. See https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md

Using default policy:
az keyvault certificate create --vault-name "kv-LED-devring0-01" -n "aksCert" -p $(az keyvault certificate get-default-policy)  

Failed to parse JSON: {
Error detail: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
The JSON may have been parsed by the shell. See https://docs.microsoft.com/cli/azure/use-cli-effectively#quoting-issues
PowerShell requires additional quoting rules. See https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md

**Comment by bbkane** [comment]
@mikedzikowski what shell are you using?

**Comment by mikedzikowski** [comment]
PS C:\git\led\LeadingEdgeDelivery\test> $PSVersionTable


Name                           Value
----                           -----
PSVersion                      5.1.19041.1237
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1237
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by bbkane** [comment]
Disclaimer: I don't work on the az CLI, I'm simply another participant in this GitHub discussion :)

I don't have PowerShell installed, but from https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md#best-practice-use-file-input-for-json , try enclosing the file name in quotes:

```
az keyvault certificate create --vault-name "kv-LED-devring0-01" -n "aksCert" -p "@cert_policy.json"
```

If you need to create `cert_policy.json`, I *think* you can do it in PowerShell with the following command

```
az az keyvault certificate get-default-policy > cert_policy.json
```

**Comment by bbkane** [comment]
Pretty sure not quoting that `@` in the filename is your issue - from https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#quoting-issues :

<img width="842" alt="image" src="https://user-images.githubusercontent.com/6081085/134711563-f676ccd2-fab1-496c-b2ac-990223140d65.png">

**Comment by mikedzikowski** [comment]
That was the issue. Thank you sir!

**Comment by ohads-MSFT** [comment]
The authoritative schema for KeyVault API operations (including certificate policy) can be found alongside all other Azure REST schemas in the specs repo: https://github.com/Azure/azure-rest-api-specs/tree/main/specification.

For example: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/keyvault/data-plane/Microsoft.KeyVault/preview/2025-06-01-preview/certificates.json.

Note that the schemas are versioned (each version has its own folder).

The schema is also documented in the REST API docs (though for some reason it wouldn't let me choose the version, and I needed a very specific one): https://learn.microsoft.com/en-us/rest/api/keyvault/certificates/create-certificate/create-certificate?view=rest-keyvault-certificates-2025-07-01&viewFallbackFrom=rest-keyvault-certificates-2025-06-01-preview&tabs=HTTP
