### ISSUE TITLE
Azure Stack AppService certificate binding not working using azure cli

### ISSUE THREAD

**Issue by tuthan** [Azure/azure-cli#9424]
I can upload the certificate but when binding to web app, it thrown exception

Environment:

`
azure-cli                         2.0.61 *

acr                                2.2.3 *
acs                               2.3.20 *
advisor                            2.0.0
ams                                0.4.3 *
appservice                        0.2.16 *
backup                             1.2.2 *
batch                              4.0.0 *
batchai                            0.4.8
billing                            0.2.1
botservice                         0.1.9 *
cdn                                0.2.1 *
cloud                              2.1.1
cognitiveservices                  0.2.5
command-modules-nspkg               2.0.2
configure                         2.0.20 *
consumption                        0.4.2
container                         0.3.15 *
core                              2.0.61 *
cosmosdb                           0.2.9 *
dla                                0.2.5
dls                                0.1.8 *
dms                                0.1.3
eventgrid                          0.2.2 *
eventhubs                          0.3.4 *
extension                          0.2.4 *
feedback                           2.1.4 *
find                               0.3.1 *
hdinsight                          0.3.2 *
interactive                        0.4.2 *
iot                                0.3.7 *
iotcentral                         0.1.6
keyvault                          2.2.13 *
kusto                              0.2.1 *
lab                                0.1.6 *
maps                               0.3.4
monitor                           0.2.11 *
network                            2.3.5 *
nspkg                              3.0.3
policyinsights                     0.1.2 *
profile                            2.1.4 *
rdbms                              0.3.9 *
redis                              0.4.2
relay                              0.1.4
reservations                       0.4.2
resource                          2.1.12 *
role                               2.4.3 *
search                             0.1.1
security                           0.1.1
servicebus                         0.3.4 *
servicefabric                     0.1.15 *
signalr                            1.0.0
sql                                2.2.0 *
sqlvm                              0.1.1
storage                            2.3.2 *
telemetry                          1.0.2
vm                                2.2.17 *

Python location '/usr/lib64/az/bin/python'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 2.7.5 (default, Oct 30 2018, 23:45:53) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
`
Exception:
`
The command failed with an unexpected error. Here is the traceback:

Error occurred in request., RetryError: HTTPSConnectionPool(host='management.jakarta.azurestactprovider.com', port=443): Max retries exceeded with url: /subscriptions/7b11f862-717a-4b7a-85fe-4cec1ceb77c8/resourceGroups/zyllem-prod-indo/providers/Microsoft.Web/sites/[SiteName]/hostNameBindings?api-version=2018-02-01 (Caused by ResponseError('too many 500 error responses',))
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 351, in execute
    raise ex
ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.jakarta.azurestactprovider.com', port=443): Max retries exceeded with url: /subscriptions/7b11f862-717a-4b7a-85fe-4cec1ceb77c8/resourceGroups/zyllem-prod-indo/providers/Microsoft.Web/sites/[SiteName]/hostNameBindings?api-version=2018-02-01 (Caused by ResponseError('too many 500 error responses',))
`

**Comment by adewaleo** [comment]
What command did you run? 

Please try to supply as much information as you can. this would help us help you!
 
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62
 
**Describe the bug**
A clear and concise description of what the bug is.
 
**To Reproduce**
Steps to reproduce the behavior.
 
**Expected behavior**
A clear and concise description of what you expected to happen.
 
**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
 
**Additional context**
Add any other context about the problem here.

**Comment by tuthan** [comment]
Sorry for delay. I have chance to run again
This is the command, the upload certificate to Az stack is working. Only the binding didnt work
az webapp config ssl bind \
            --name "${app_name}" \
            --resource-group "${resource_group_name}"\
            --certificate-thumbprint "${thumbprint}" \
            --ssl-type SNI
`

msrest.http_logger : Request URL: 'https://management.jakarta.azurestactprovider/subscriptions/7b11f862-717a-4b7a-85fe-4cec1ceb77c8/resourceGroups/resource-group/providers/Microsoft.Web/sites/SiteName/hostNameBindings?api-version=2018-02-01'
msrest.http_logger : Request method: 'GET'
msrest.http_logger : Request headers:
msrest.http_logger :     'accept-language': 'en-US'
msrest.http_logger :     'Accept': 'application/json'
msrest.http_logger :     'User-Agent': 'python/2.7.5 (Linux-3.10.0-957.1.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core) msrest/0.6.6 msrest_azure/0.6.0 azure-mgmt-web/0.40.0 Azure-SDK-For-Python AZURECLI/2.0.61'
msrest.http_logger : Request body:
msrest.http_logger : None
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): management.jakarta.azurestactprovider:443
urllib3.connectionpool : https://management.jakarta.azurestactprovider:443 "GET /subscriptions/7b11f862-717a-4b7a-85fe-4cec1ceb77c8/resourceGroups/resource-group/providers/Microsoft.Web/sites/SiteName/hostNameBindings?api-version=2018-02-01 HTTP/1.1" 500 36
urllib3.util.retry : Incremented Retry for (url='/subscriptions/7b11f862-717a-4b7a-85fe-4cec1ceb77c8/resourceGroups/resource-group/providers/Microsoft.Web/sites/SiteName/hostNameBindings?api-version=2018-02-01'): Retry(total=3, connect=4, read=4, redirect=None, status=None)
urllib3.connectionpool : Retry: /subscriptions/7b11f862-717a-4b7a-85fe-4cec1ceb77c8/resourceGroups/resource-group/providers/Microsoft.Web/sites/SiteName/hostNameBindings?api-version=2018-02-01
urllib3.connectionpool : Resetting dropped connection: management.jakarta.azurestactprovider
urllib3.connectionpool : https://management.jakarta.azurestactprovider:443 "GET /subscriptions/7b11f862-717a-4b7a-85fe-4cec1ceb77c8/resourceGroups/resource-group/providers/Microsoft.Web/sites/SiteName/hostNameBindings?api-version=2018-02-01 HTTP/1.1" 500 36
urllib3.util.retry : Incremented Retry for (url='/subscriptions/7b11f862-717a-4b7a-85fe-4cec1ceb77c8/resourceGroups/resource-group/providers/Microsoft.Web/sites/SiteName/hostNameBindings?api-version=2018-02-01'): Retry(total=2, connect=4, read=4, redirect=None, status=None)
urllib3.connectionpool : Retry: /subscriptions/7b11f862-717a-4b7a-85fe-4cec1ceb77c8/resourceGroups/resource-group/providers/Microsoft.Web/sites/SiteName/hostNameBindings?api-version=2018-02-01
urllib3.connectionpool : Resetting dropped connection: management.jakarta.azurestactprovider
urllib3.connectionpool : https://management.jakarta.azurestactprovider:443 "GET /subscriptions/7b11f862-717a-4b7a-85fe-4cec1ceb77c8/resourceGroups/resource-group/providers/Microsoft.Web/sites/SiteName/hostNameBindings?api-version=2018-02-01 HTTP/1.1" 500 36
urllib3.util.retry : Incremented Retry for (url='/subscriptions/7b11f862-717a-4b7a-85fe-4cec1ceb77c8/resourceGroups/resource-group/providers/Microsoft.Web/sites/SiteName/hostNameBindings?api-version=2018-02-01'): Retry(total=1, connect=4, read=4, redirect=None, status=None)
urllib3.connectionpool : Retry: /subscriptions/7b11f862-717a-4b7a-85fe-4cec1ceb77c8/resourceGroups/resource-group/providers/Microsoft.Web/sites/SiteName/hostNameBindings?api-version=2018-02-01
urllib3.connectionpool : Resetting dropped connection: management.jakarta.azurestactprovider
urllib3.connectionpool : https://management.jakarta.azurestactprovider:443 "GET /subscriptions/7b11f862-717a-4b7a-85fe-4cec1ceb77c8/resourceGroups/resource-group/providers/Microsoft.Web/sites/SiteName/hostNameBindings?api-version=2018-02-01 HTTP/1.1" 500 36
urllib3.util.retry : Incremented Retry for (url='/subscriptions/7b11f862-717a-4b7a-85fe-4cec1ceb77c8/resourceGroups/resource-group/providers/Microsoft.Web/sites/SiteName/hostNameBindings?api-version=2018-02-01'): Retry(total=0, connect=4, read=4, redirect=None, status=None)
urllib3.connectionpool : Retry: /subscriptions/7b11f862-717a-4b7a-85fe-4cec1ceb77c8/resourceGroups/resource-group/providers/Microsoft.Web/sites/SiteName/hostNameBindings?api-version=2018-02-01
urllib3.connectionpool : Resetting dropped connection: management.jakarta.azurestactprovider
urllib3.connectionpool : https://management.jakarta.azurestactprovider:443 "GET /subscriptions/7b11f862-717a-4b7a-85fe-4cec1ceb77c8/resourceGroups/resource-group/providers/Microsoft.Web/sites/SiteName/hostNameBindings?api-version=2018-02-01 HTTP/1.1" 500 36
msrest.exceptions : Error occurred in request., RetryError: HTTPSConnectionPool(host='management.jakarta.azurestactprovider', port=443): Max retries exceeded with url: /subscriptions/7b11f862-717a-4b7a-85fe-4cec1ceb77c8/resourceGroups/resource-group/providers/Microsoft.Web/sites/SiteName/hostNameBindings?api-version=2018-02-01 (Caused by ResponseError('too many 500 error responses',))
The command failed with an unexpected error. Here is the traceback:

Error occurred in request., RetryError: HTTPSConnectionPool(host='management.jakarta.azurestactprovider', port=443): Max retries exceeded with url: /subscriptions/7b11f862-717a-4b7a-85fe-4cec1ceb77c8/resourceGroups/resource-group/providers/Microsoft.Web/sites/SiteName/hostNameBindings?api-version=2018-02-01 (Caused by ResponseError('too many 500 error responses',))
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 351, in execute
    raise ex
ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.jakarta.azurestactprovider', port=443): Max retries exceeded with url: /subscriptions/7b11f862-717a-4b7a-85fe-4cec1ceb77c8/resourceGroups/resource-group/providers/Microsoft.Web/sites/SiteName/hostNameBindings?api-version=2018-02-01 (Caused by ResponseError('too many 500 error responses',))

`

**Comment by btardif** [comment]
@panchagnula please sync up with Domains/SSL team

**Comment by panchagnula** [comment]
@tuthan is this still happening with the latest cli version?

**Comment by panchagnula** [comment]
@tuthan please let us know if this still repros with the latest CLI version
