### ISSUE TITLE
Unable to manipulate AD Enterprise Application

### ISSUE THREAD

**Issue by clauslund** [Azure/azure-cli#9429]
Deployed "Azure Red Hat Openshift" and we now have an "Enterprise Application" AD object that needs to be manipulated. Specifically need to change Properties->"User assignment required?" to yes.
There appears to be no way to manipulate this outside the web UI.

![Capture-aad-enterprise-apps](https://user-images.githubusercontent.com/42252547/57948240-1f39c380-78af-11e9-8b72-d69d55bab8ba.PNG)

**Comment by adewaleo** [comment]
@clauslund, thanks for reaching out. This repo and its issues are for the Azure CLI (Command Line Interface). Moreover, our team maintains the CLI and isn't familiar with the portal.

Please see here for opening issues against the [Azure Portal](https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request).

**Comment by clauslund** [comment]
But I want to be able to do just that using the az cli!

**Comment by clauslund** [comment]
@adewaleo I understand that ... and I would like to be able to do that using the az cli!
I was questioning the picture as I thought it might confuse things and I guess I shouldn't have included it...

**Comment by adewaleo** [comment]
Oh I see what you mean. I apologize for hastily closing the issue. I will reopen it and label the issue.

**Comment by adewaleo** [comment]
Does it look like the application has an associated resource ID. `az openshift --help` does not have an update command. It would be good to add one. If this commands supports generic update and this application is an ARM resource then it should be possible to update fields on the resource.

However, given this is a Redhat application, it might not be possible to update this directly through ARM. However there might be ways to modify the resource outside the portal.

Please [see here ](https://docs.microsoft.com/en-us/azure/openshift/tutorial-create-cluster)for more information. Apparently [there is a openshift specific CLI
](https://docs.microsoft.com/en-us/azure/openshift/tutorial-create-cluster#step-5-install-the-openshift-cli) for more powerful control of Openshift clusters.
The doc might also be a more relevant place to post this issue, given the authors might have a better sense of how automation should work with this Redhat application.

**Comment by clauslund** [comment]
Openshift is just our current example.
I believe this is the case for any “Enterprise Application”.
I think under the current az cli this ability should probably live somewhere under: az ad sp

-Claus

**Comment by clauslund** [comment]
Never mind. I figured it out.

az ad sp update --id [ID] --set appRoleAssignmentRequired=true

-Claus

From: Lund, Claus
Sent: Friday, May 17, 2019 4:31 PM
To: Azure/azure-cli <reply@reply.github.com>; Azure/azure-cli <azure-cli@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Azure/azure-cli] Unable to manipulate AD Enterprise Application (#9429)

Openshift is just our current example.
I believe this is the case for any “Enterprise Application”.
I think under the current az cli this ability should probably live somewhere under: az ad sp

-Claus

**Comment by yugangw-msft** [comment]
@clauslund, good you figured out the right approach. I am closing this.
