### ISSUE TITLE
Introduce new parameters into az network watcher connection-monitor. Add new commands.

### ISSUE THREAD

**Issue by irrogozh** [Azure/azure-cli#9432]
**Resource Provider**
Az.Network

**Description of Feature or Work Requested**
We are going to create a new version of connection monitor API. instead of single source/destination we are going to enable monitoring for multiple endpoints and configurations. Instead of current parameters, we will need to have a list of endpoints, testConfigurations, testGroups and outputs.

Looks like reasonable approach:
1. create a shallow connection monitor resource:
    az network watcher connection-monitor create --name --notes

2. add endpoint to connection monitor:
    az network watcher connection-monitor endpoint create --name --resourceId --address --filterType --filterAddresses

3. add testConfiguration to connection monitor:
    az network watcher connection-monitor testConfiguration create --name --testFrequencySec -- successThresholdChecksFailedPercent --successThresholdRoundTripTimeMs --preferredIPVersion  --protocolConfiguration

4. add testGroup to connection monitor:
    az network watcher connection-monitor testGroup create --name --testConfigurations(list of test configuration names) --sources(list of source endpoint names) --destinations(list of destination endpoint names)

5. add output to connectionMonitor:
   az network watcher connection-monitor output create --outputType --workspaceResourceId

6. I'm not sure what's the best approach to set protocolConfiguration from item 3. 
For powershell we do it like this:

New-AzNetworkWatcherConnectionMonitorProtocolConfigurationObject -Protocol<String> 

[1st parameter set - if TCP protocol specified: [-Port<Int32>] [-DisableTraceRoute<bool>]]
[2nd parameter set - if HTTP protocol specified: [-Port<Int32>] [-Method<String>] [-Path<string>] [-RequestHeader<IDictionary>] [-ValidStatusCodeRange<List[String]>] [-PreferHTTPS<bool>]]
[3nd parameter set - if ICMP protocol specified: [-DisableTraceRoute<bool>]]

-----------------------------------

7. We also need to have some way to update connection monitor. If there is an option to delete endpoint, testConfiguration, testGroup and output from connectionMonitor, it could work. The challenge is that if customer remove endpoint but forget to remove this endpoint name from a testGroup which was referenced it, customer will have validation exception on server side. Probably, it's fine...

**Minimum API Version Required**
What is the minimum API version of your service required to implement your feature?

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/pull/7821

it's not updated with new parameters yet

**Target Date**
We are going to have private preview at the second half of June.

**Comment by tjprescott** [comment]
@irrogozh what is the min API version for these features and are there PRs that show the actual swagger changes?

**Comment by tjprescott** [comment]
Bumping to sprint 66 due to higher priority direction from NRP.

**Comment by irrogozh** [comment]
Travis, please, don't implement this please. The spec is not approved yet - there is ongoing changes in contract...

**Comment by tjprescott** [comment]
@irrgozh no worries. If the spec isn't approved for work in sprint 66 I'll just shuffle priorities accordingly.

**Comment by MyronFanQiu** [comment]
@irrogozh Hello. Once are the spec PR ready, please modify the title and ping me. Thanks

**Comment by MyronFanQiu** [comment]
@irrogozh Feel free to ping me when the service's ready.

**Comment by irrogozh** [comment]
@MyronFanQiu , can we discuss design? The public preview is going to be in January. So, we will need to have cmdlets by this time.

**Comment by MyronFanQiu** [comment]
@irrogozh sure. Should we schedule a meeting?

**Comment by irrogozh** [comment]
@MyronFanQiu, yep, would be great. Could you send me your Msft alias so I could schedule a meeting? What time would be convenient for you? I'm working on PST time... 
Just in case, my alias - irrogozh@microsoft.com

**Comment by yonzhan** [comment]
add to S164.
