### ISSUE TITLE
[Expanded params] Should be an option to load file contents as a list

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#944]
Today we have @file to load contents from a file (loads it as one chunk, useful for SSH keys, etc.).  We should also have an option to load contents as a list, say with #file.  This would be especially useful in Windows where shell substitution isn't supported.  Windows users could then pipe IDs to a file and execute a command like az vm show --ids #file

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
