### ISSUE TITLE
Unable to create VMSS on Windows

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#9440]
## Describe the bug

**Command Name**
`az vmss create`

**Errors:**
```
Deployment failed. Correlation ID: f6d619b5-2ac6-403d-b8ae-bbd2ae7f87bb. {
  "error": {
    "code": "InvalidParameter",
    "message": "The value of parameter linuxConfiguration.ssh.publicKeys.keyData is invalid.",
    "target": "linuxConfiguration.ssh.publicKeys.keyData"
  }
}
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vmss create -g {} -n {} --image {}`

## Expected Behavior

VMSS is created. If I do this on Cloud Shell it succeeds. If get the same failure if I use `--generate-ssh-keys`. 

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.7.3
Shell: python.exe

azure-cli 2.0.64

Extensions:
alias 0.5.2
front-door 0.1.5
interactive 0.4.2

```

**Comment by tjprescott** [comment]
@adewaleo, not sure why it says the shell is python.exe, but I was running on CMD.

**Comment by adewaleo** [comment]
this is because of the bug i caught and fixed on the release branch last week. It should be solved when the release branch is merged back into dev.

For now the solution is to explicitly reference --ssh-key-value in your command:

```
az vm create -n test-deb-data-disks -g ova-test --data-disk-sizes-gb 10 10 10 --image debian --validate --ssh-key-value ~/.ssh/id_rsa.pub
```

**Comment by adewaleo** [comment]
About the shell being python.exe. I am not sure. Maybe because the command was run in the dev environment in CMD or an IDE?
