### ISSUE TITLE
TrafficAnalyticsProperties.network_watcher_flow_analytics_configuration'

### ISSUE THREAD

**Issue by rfc791** [Azure/azure-cli#9443]
## Describe the bug

Command works in Canada Central but in Canada East it does not and throws the error below.
I have tried adding `--traffic-analytics false` but then it causes `AttributeError: 'NoneType' object has no attribute 'enabled'`

**Command Name**
`az network watcher flow-log configure`

**Errors:**
```
Parameter 'TrafficAnalyticsProperties.network_watcher_flow_analytics_configuration' can not be None.
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 523, in execute
    raise ex
cli/core/commands/__init__.py, ln 581, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.6/site-packages/msrest/serialization.py, ln 662, in validate
    raise ValidationError("required", name, True)
msrest.exceptions.ValidationError: Parameter 'TrafficAnalyticsProperties.network_watcher_flow_analytics_configuration' can not be None.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az network watcher flow-log configure --resource-group {} --nsg {} --storage-account {} --retention {} --format {} --log-version {} --enabled {}`

## Expected Behavior

Enables Flow logs on the NSG.

## Environment Summary
```
Linux-4.15.0-44-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.63 *

```

**Comment by tjprescott** [comment]
I can reproduce this. It looks like different versions of the service are deployed in different regions. I will flag this with service attention, but my recommendation would be to open a support ticket on the portal to more quickly reach the service team.

**Comment by tjprescott** [comment]
Have you tried supplying `--workspace`?

**Comment by tjprescott** [comment]
I have tracked down the issue and will open a PR to fix.
