### ISSUE TITLE
Can not create a connection for ER by Azure CLI if resource group is different between GW and ER circuit.

### ISSUE THREAD

**Issue by hisasima** [Azure/azure-cli#9447]
I tried to create a connection by Azure CLI that subscriptions are same and resource groups are different between GW and ER circuit but I could not create. And I could not find how to use  2 resource group to create a connection for ER.
I hope you write this limitation in this documents or Azure will enhance this feature.

az network vpn-connection create --name connection --resource-group RG1 --vnet-gateway1 /subscriptions/AAAA/resourceGroups/RG1/providers/Microsoft.Network/virtualNetworkGateways/RGateway 
--express-route-circuit2 /subscriptions/AAAA/resourceGroups/RG2/providers/Microsoft.Network/expressRouteCircuits/ER

 

Deployment failed. Correlation ID: b6f9d04e-c165-497a-88ee-fa39fce0313b. {

  "error": {

    "code": "ExpressRouteConnectionPeerCannotBeChanged",

    "message": "Connection's peer cannot be changed. Please use /subscriptions/AAAA/resourceGroups/RG1/providers/Microsoft.Network/virtualNetworkGateways/RG1 and /subscriptions/AAAA/resourceGroups/RG1/providers/Microsoft.Network/expressRouteCircuits/ER as endpoints for connection /subscriptions/AAAA/resourceGroups/RG1/providers/Microsoft.Network/connections/connection.",

    "details": []

  }

}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9cd3cc3-90c6-19d0-1486-b779d65f6b97
* Version Independent ID: f3033d7d-e123-57a2-7eab-0837c3d9c8c0
* Content: [az network vpn-connection](https://docs.microsoft.com/en-us/cli/azure/network/vpn-connection?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
From the error message, it looks like you are trying to create on top of an existing VPN connection. Can you run the command with `--debug`, find the line that starts with "Request body" and copy-paste the next several lines in the debug output?

**Comment by hisasima** [comment]
Thank you for your advice. I'll check.
