### ISSUE TITLE
az aks nodeppol not in the az aks command group

### ISSUE THREAD

**Issue by gmalk** [Azure/azure-cli#9448]
az CLI version 2.0.65

I would like to upgrade a nodepool aks cluster, but by running "az aks nodeppol list -resource-group RGNAME --cluster-name CLUSTERNAME" get nodepool not in the az aks command group.

az aks --help
    browse             : Show the dashboard for a Kubernetes cluster in a web browser.
    create             : Create a new managed Kubernetes cluster.
    delete             : Delete a managed Kubernetes cluster.
    disable-addons     : Disable Kubernetes addons.
    enable-addons      : Enable Kubernetes addons.
    get-credentials    : Get access credentials for a managed Kubernetes cluster.
    get-upgrades       : Get the upgrade versions available for a managed Kubernetes cluster.
    get-versions       : Get the versions available for creating a managed Kubernetes cluster.
    install-cli        : Download and install kubectl, the Kubernetes command-line tool.
    install-connector  : (PREVIEW) Install the ACI Connector on a managed Kubernetes cluster.
    list               : List managed Kubernetes clusters.
    remove-connector   : (PREVIEW) Remove the ACI Connector from a managed Kubernetes cluster.
    remove-dev-spaces  : Remove Azure Dev Spaces from a managed Kubernetes cluster.
    scale              : Scale the node pool in a managed Kubernetes cluster.
    show               : Show the details for a managed Kubernetes cluster.
    update-credentials : Update credentials for a managed Kubernetes cluster, like service
                         principal.
    upgrade            : Upgrade a managed Kubernetes cluster to a newer version.
    upgrade-connector  : (PREVIEW) Upgrade the ACI Connector on a managed Kubernetes cluster.
    use-dev-spaces     : Use Azure Dev Spaces with a managed Kubernetes cluster.
    wait               : Wait for a managed Kubernetes cluster to reach a desired state.

**Comment by adewaleo** [comment]
You need to add the aks-preview extension to use `aks nodepool` command group. 

See [here](https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#install-aks-preview-cli-extension) and [here](https://docs.microsoft.com/en-us/cli/azure/ext/aks-preview/aks/nodepool?view=azure-cli-latest) for more info.
