### ISSUE TITLE
Missing examples and details about option for command on website , customer asking about it.

### ISSUE THREAD

**Issue by porrascarlos802018** [Azure/azure-cli#9449]
[Enter feedback here]
2)The “--base-image-trigger-type” parameter has two values: “All” and “Runtime”. We didn’t find more detailed explanation about what these really mean. Can you please advise?
examples!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d13a1ecb-d45d-84fe-aa0d-d61a4020e5dc
* Version Independent ID: 128e5bc6-e518-bd5a-f511-48e0ed185739
* Content: [az acr task](https://docs.microsoft.com/en-us/cli/azure/acr/task?view=azure-cli-2018-03-01-hybrid#feedback)
* Content Source: [src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ehotinger** [comment]
@northtyphoon  I vaguely recall you answering this somewhere else. Was it fixed / can this be closed now?

**Comment by northtyphoon** [comment]
In a multi-stage Dockerfile, users can build the binaries based on one or more “buildtime” image and then package the binaries to a “runtime” image. The final output image is based on the “runtime” image.

ACR Tasks currently supports tracking runtime base image. We plan to support buildtime in the future. “All” is reserved for this purpose.

**Comment by northtyphoon** [comment]
https://learn.microsoft.com/en-us/azure/container-registry/container-registry-tasks-base-images
