### ISSUE TITLE
run-command example for windows

### ISSUE THREAD

**Issue by cconrado** [Azure/azure-cli#9455]
there should be a run example for windows its only linux and takes awhile to go find the command-id for powershell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f04b196d-7d11-7213-f037-f12b85b19c52
* Version Independent ID: adc05d8e-b13b-134b-5f61-42aaf23666df
* Content: [az vm run-command](https://docs.microsoft.com/en-us/cli/azure/vm/run-command?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
@adewaleo, let us come out with one

**Comment by ConnorDickson** [comment]
You could use a similar example to what I have posted in a stackoverflow question [here](https://stackoverflow.com/questions/56578122/azure-cli-run-command-invoke-runpowershellscript-with-parameters)

**Comment by cconrado** [comment]
@ConnorDickson it helps but having it in the doc helps with searching :)

**Comment by yugangw-msft** [comment]
https://github.com/Azure/azure-cli/pull/9705 fixes it
