### ISSUE TITLE
AZ interactive mode installation failed (Linux)

### ISSUE THREAD

**Issue by ZEROF** [Azure/azure-cli#9461]
Hi,

**Sysinfo:**

az version: 2.0.60
pip version: 19.1.1
OS: BackBox Linux, based on Ubuntu 16.04

**Bug info**

Can't install az interactive shell with:

az interactive
pip install azure-cli-interactive

**Debug mode output:**
https://paste.lugons.org/?fd85dc356b56bf44#wXKlH0a/x2Vegfunt2K3cbeuvuNYcEudaxStfFzwFuE=

Thanks

**Comment by tjprescott** [comment]
Please update your CLI installation. If the problem persists, please reopen.
