### ISSUE TITLE
Cannot Query Private IPs through Loop

### ISSUE THREAD

**Issue by Genysys** [Azure/azure-cli#9464]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Trying to loop through an array. Works well when query one machine, but when i loop through the array, the outputs says it cant be found

**To Reproduce**
Steps to reproduce the behavior.

```
for i in "${VM_NAME[@]}"; do \
   P_IP=$(az vm show -g $rg -n $i -d --query privateIps -otsv)
   echo $i $P_IP;
done 
```

I get the following output:

```
The Resource 'Microsoft.Compute/virtualMachines/"VM-NAME"' under resource group 'Resource-GroupC' was not found.
```
**Expected behavior**

IP1
IP2...
IPN

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
```
azure-cli (2.0.52)
MacOS
```

**Additional context**

**Comment by tjprescott** [comment]
It looks like your VM names are including double quotes. 
'Microsoft.Compute/virtualMachines/"VM-NAME"'
Should be:
'Microsoft.Compute/virtualMachines/VM-NAME'

Your script will need to handle this.

**Comment by Genysys** [comment]
But when i use the double quote in a single command it works?

az vm show -g $rg -n "VM_NAME" -d --query privateIps -otsv

**Comment by tjprescott** [comment]
When you do this:
`az vm show -g $rg -n "VM_NAME" -d --query privateIps -otsv`

Your shell is stripping off the quotes and only sending the string `VM_NAME`. You script is preserving the quotes and thus the CLI is seeing `"VM_NAME"`.
