### ISSUE TITLE
Azure CLI fails to add load balancer backend pool to VMSS

### ISSUE THREAD

**Issue by goatmale** [Azure/azure-cli#9467]
## Azure CLI fails to add load balancer backend pool to VMSS

**Command Name**
`az vmss update`

**Errors:**
```
Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
python3.6/site-packages/msrest/serialization.py, ln 1288, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
python3.6/site-packages/msrest/serialization.py, ln 1078, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
...

python3.6/site-packages/msrest/serialization.py, ln 1101, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
```

## To Reproduce:
The json string is being built in bash - format is as follows.
```bash
JSONVALUE='"''id": "/subscriptions/'$AZSUB_ID'/resourceGroups/'$resource_group_name'/providers/Microsoft.Network/loadBalancers/'$AZLB_NLB_NAME'/backendAddressPools/'$AZLB_BEP_NAME'"'
```
The python string uses these variables:
```python
az vmss update -g {$rg} -n {$vmss} --add virtualMachineProfile.networkProfile.networkInterfaceConfigurations[0].ipConfigurations[0].loadBalancerBackendAddressPools = \'{$JSONVALUE}\'
```
## Expected Behavior
The VMSS should be added to the backend pool.

## Environment Summary
```
Linux-4.15.0-50-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.65

```
## Additional Context
I am happy to use any other workaround, but this seems to be the only way to automate adding a vmss to a load balancer.

We are rebuilding / destorying our AKS cluster on a scheduled basis to save cost and we have to manually add in the scale set to the backend pool to fix this issue.

**Comment by goatmale** [comment]
This seems to be an issue with the Azure CLI and bash - when I echo the variable, copy the output and run I'm not getting an error - however this limits my options on automating this :( so it's still an issue for me.

**Comment by yugangw-msft** [comment]
Would the [hints](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#quoting-issues) works to by-pass the quote issue? Particularly, leverage the `@`?

**Comment by goatmale** [comment]
Using @ did not work unfortunately.

**Comment by adewaleo** [comment]
I tried the following and it worked for me:

```
# Remove the load balancer backend address pool
az vmss update --name tosin-vmss -g ova-test --remove virtualMachineProfile.networkProfile.networkInterfaceConfigurations[0].ipConfigurations[0].loadBalancerBackendAddressPools 0

# add the backend address pool back to the vmss. This works with --instance-id and correct path for individual vmss instances.
az vmss update --name tosin-vmss -g ova-test --add virtualMachineProfile.networkProfile.networkInterfaceConfigurations[0].ipConfigurations[0].loadBalancerBackendAddressPools   "id=/subscriptions/0000-0000-0000000/resourceGroups/ova-test/providers/Microsoft.Network/loadBalancers/tosin-vmssLB/backendAddressPools/tosin-vmssLBBEPool"
```
 
The solution is to use `--add [path] [key-value pair]`

I will be closing the issue, but please let me know if you have any other questions.

cc: @yugangw-msft

**Comment by goatmale** [comment]
We ended up going a different route - **assigning the command to an alias and then calling that alias.**
