### ISSUE TITLE
az network lb create doesn't use existing vnet with --vnet-name parameter pased

### ISSUE THREAD

**Issue by johnwildes** [Azure/azure-cli#9468]
## Describe the bug
I was working in the azure cloud shell to create a loadbalancer, off of an existing vnet.  The vnet exists in the subscription, in a resource group called vnet-rg, in centralus.

I was creating a loadbalancer in it's own resource group called lb-rg, in centralus.  The cli created a new vnet in the resource group, and attached the new loadbalancer to that vnet with the same name as the one that existed in the other resource group.

**Command Name**
`az network lb create`

**Errors:**
No errors.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Create new resource group (vnet-rg was my example)
`az group create -n "vnet-rg" -l centralus`

Create new vnet in resource group vnet-rg (lbvnet was my example) with default subnet.
`az network vnet create -g vnet-rg -n lbvnet --address-prefix 10.10.0.0/16 --subnet-name default --subnet-prefix 10.10.0.0/24`

Create new resource group for load balancer (lb-rg was my example)
`az group create -n lb-rg -l centralus`

Create new loadbalancer using the code below
`az network lb create -g lb-rg -n lbtest --sku Basic --vnet-name lbvnet --subnet default`

## Expected Behavior
I expected the cli to create a new load balancer, but connect it to my already existing vnet.

## Environment Summary
```
Linux-4.15.0-1045-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.65

Extensions:
webapp 0.2.6

```
## Additional Context
I wanted to see what the dependencies are for creating a loadbalancer, and based on this doc it seems you can create a load balancer without the supporting vnet environment first.

https://docs.microsoft.com/en-us/azure/load-balancer/quickstart-create-basic-load-balancer-cli

Which is ok, but there's no mention of a requirement that the VNET should or must exist in the same resource group as the load balancer resource.  Which makes the fact that this is occuring puzzling. 

Hopefully it's not just me.  If it is specified somewhere that this is a requirement, that the lb and vnet exist in the same resource group, please point me in the direction of that documentation.

**Comment by yugangw-msft** [comment]
if you omit the `--vnet-name`, rather provide the full resource id to the `--subnet` from the existing vnet, does that work?
CC: @tjprescott

**Comment by tjprescott** [comment]
Yes, the correct usage is to provide `--subnet` with the ID to the subnet in the other RG.

**Comment by johnwildes** [comment]
That’s not what the cli documentation states nor the example.  

https://docs.microsoft.com/en-us/cli/azure/network/lb?view=azure-cli-latest#az-network-lb-create

**Comment by johnwildes** [comment]
Clarified the language in the documentation.  
https://github.com/Azure/azure-cli/pull/9471

**Comment by tjprescott** [comment]
You can either provide the names or ID. However, if you provide names, they must be in the same subscription and resource group as the load balancer. If that is not the case, you have no other option that to use the ID of the subnet.
