### ISSUE TITLE
az command not working: import issue

### ISSUE THREAD

**Issue by amramtamir** [Azure/azure-cli#9473]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
cannot import name '_thread' from 'six.moves' (unknown location)
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 560, in execute
    raise ex
cli/core/commands/__init__.py, ln 618, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 611, in _run_job
    six.reraise(*sys.exc_info())
Users/tamir.amram/six.py, ln 491, in reraise
    raise value
...
site-packages/dateutil/parser/__init__.py, ln 2, in <module>
    from ._parser import parse, parser, parserinfo
site-packages/dateutil/parser/_parser.py, ln 50, in <module>
    from .. import tz
site-packages/dateutil/tz/__init__.py, ln 2, in <module>
    from .tz import *
site-packages/dateutil/tz/tz.py, ln 21, in <module>
    from six.moves import _thread
ImportError: cannot import name '_thread' from 'six.moves' (unknown location)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az login`

## Environment Summary
```
Darwin-18.5.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.64 *

```

**Comment by adewaleo** [comment]
Hello @amramtamir, what is your CLI installation method?

**Comment by amramtamir** [comment]
Hi,
brew install azure-cli

**Comment by yugangw-msft** [comment]
@marstr, can you please take a look?

**Comment by marstr** [comment]
Investigating now

**Comment by marstr** [comment]
I need more information, @amramtamir! When I run `brew install azure-cli`on my Mac running 10.14.4, all seems well. Is there anything special about your machine? Have you installed Python on your machine outside of using Homebrew?

**Comment by amramtamir** [comment]
Hi @marstr ,
Nothing special on my Mac - I used brew to install python.
I also tried to:
reinstall azure-cli, python, brew, Six package.

**Comment by adewaleo** [comment]
> Hi @marstr ,
> Nothing special on my Mac - I used brew to install python.
> I also tried to:
> reinstall azure-cli, python, brew, Six package.

This might help? https://stackoverflow.com/questions/27630114/matplotlib-issue-on-os-x-importerror-cannot-import-name-thread

**Comment by amramtamir** [comment]
Hi @marstr
It seems to work!
I have done this steps:
opened python from the terminal
import six
print six.__file__

the output showed that the six.pyc and six.py was on my home path
I ran rm -rf six.* 
and the "az" command is now working :)

**Comment by marstr** [comment]
This is troublesome to me, as my hope was that using a Virtualenv in the Homebrew installer would isolate us from these sorts of problems.

@lmazuel, my take away from this is that in addition to invoking the python inside of the virtualenv, I should be invoking it with the `-s` flag. Do you think that's the right conclusion?

**Comment by lmazuel** [comment]
@marstr venv should not load any system or user system directory by default, so that option should be useless. If you're able to show me an example with venv and user directory where "-s" makes a difference I'm curious :)
That being said, it seems the story is more subtle:
https://github.com/pypa/pip/issues/4141
https://github.com/pypa/pip/issues/5702

**Comment by marstr** [comment]
I'm going to close this out as a one-off error for now. However, if other people stumble on this and it needs a fix from us, I'm happy to open it back up.
