### ISSUE TITLE
`variables` parameter for az pipelines create|update

### ISSUE THREAD

**Issue by mathieu-benoit** [Azure/azure-cli#9477]
**Is your feature request related to a problem? Please describe.**
Some variables can't be in the azure-pipelines.yaml file in source control. For that we have the ability to edit via the UI the variables of the pipeline definition. It would be ideal to have the ability to set `variables` while leveraging `az pipelines create` and `az pipelines update`.

**Describe the solution you'd like**
`az pipelines create --variables key1=value1 key2=value2` same for `az pipelines update`

**Describe alternatives you've considered**
The alternative is to do that via the UI by editing the pipelines definition, but not very efficient for automation.

**Comment by atbagga** [comment]
az pipelines is a az devops command. The issues are tracked in the repository - https://github.com/Azure/azure-devops-cli-extension/issues.

**Comment by mathieu-benoit** [comment]
Got it thanks @atbagga, feature request moved there: https://github.com/Azure/azure-devops-cli-extension/issues/639 Thanks!
