### ISSUE TITLE
az group delete --name '-biubiubiu' will fail.

### ISSUE THREAD

**Issue by andyliuliming** [Azure/azure-cli#9479]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
if the resource group name have hyphens prefix, "-biubiubiu", then az group show or az group update or az group delete would fail.
**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by adewaleo** [comment]
I am not sure why one would want to create a resource group with a hyphen as a prefix, but I was able to reproduce this issue. 

At first I thought it was simply a quoting issue:

```
$ az group show -n '-biubiubiu'
az group show: error: argument --name/-n/--resource-group/-g: expected one argument
usage: az group show [-h] [--verbose] [--debug]
                     [--output {json,jsonc,table,tsv,yaml,none}]
                     [--query JMESPATH] --name RESOURCE_GROUP_NAME
                     [--subscription _SUBSCRIPTION]
```

But even with correct quoting, we see that msrest does not approve of this name in its validation.

```
$ az group show -n '"-biubiubiu"'
validation error: Parameter 'resource_group_name' must conform to the following pattern: '^[-\\w\\._\\(\\)]+$'.

```
With --debug:

```
Getting management service client client_type=ResourceManagementClient
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
msrest.exceptions : Parameter 'resource_group_name' must conform to the following pattern: '^[-\\w\\._\\(\\)]+$'.
cli.azure.cli.core.util : validation error: Parameter 'resource_group_name' must conform to the following pattern: '^[-\\w\\._\\(\\)]+$'.
validation error: Parameter 'resource_group_name' must conform to the following pattern: '^[-\\w\\._\\(\\)]+$'.
```
cc: @lmazuel @yugangw-msft

**Comment by adewaleo** [comment]
I will add that I was able to create a rg with this name through the portal. I imagine this should be possible through ARM templates. However, I have not tested this yet.

**Comment by tjprescott** [comment]
This is a known issue with argparse. You can use `az group show -n=-biubiubiu` and it will work.
