### ISSUE TITLE
az account list returns success code even though the user is not logged in

### ISSUE THREAD

**Issue by johanste** [Azure/azure-cli#948]
...it should return a failure (non-zero)

**Comment by yugangw-msft** [comment]
why? 'listing' returns nothing is normal, no?  Like `ls` under dir w/o files still gives a 0

**Comment by JasonRShaver** [comment]
There should be a way to just check if you are logged in or not; but I don't think an empty list is a 'failure', and I can get a non-empty list even when I am logged out.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
