### ISSUE TITLE
Update `az feedback` to open issues in github repo of extension if extension is coming from a different repo

### ISSUE THREAD

**Issue by gauravsaralMs** [Azure/azure-cli#9483]
**Is your feature request related to a problem? Please describe.**
Currently giving feedback on any command coming from extension goes into azure cli extension repo. While a extension can even live outside of the main cli extension repo, like devops cli extension.

**Describe the solution you'd like**
Say some user wants to give feedback for command coming from devops-cli-extension, then also currently issue will be opened in cli extension repo, it will be better if issue can directly be opened in azure devops cli github repository

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by adewaleo** [comment]
This should be possible via the extension's [project_url link in the index.json file](https://github.com/Azure/azure-cli-extensions/blob/master/src/index.json#L673). If this could be surfaced up within the CLI, it should be possible to direct a user to this link instead.

cc: @achandmsft

**Comment by atbagga** [comment]
@adewaleo  This was fixed by above PR and is released already. We can close this issue.

**Comment by adewaleo** [comment]
Thanks a lot @atbagga!
