### ISSUE TITLE
jmeshpath filtering not working as expected

### ISSUE THREAD

**Issue by axthosarouris** [Azure/azure-cli#9484]
## Describe the bug
Given that the command `az account list ` gives the following list
 
```
[
  {
    "cloudName": "AzureCloud",
    "id": "abcdefg",
    "isDefault": false,
    "name": "One Project",
    "state": "Enabled",
    "tenantId": 1234567890",
    "user": {
      "name": "foo@foo.com",
      "type": "user"
      }
    },
 {
    "cloudName": "AzureCloud",
    "id": "abcdefflfjsdf",
    "isDefault": false,
    "name": "Another project",
    "state": "Enabled",
    "tenantId": "123455667",
    "user": {
      "name": foo@foo.com",
      "type": "user"
    }
  }
]

```

**Command Name**
az account list --query [?state=='Enabled']

**Errors:**
Produces empty list when it should produce  a list of with all enabled elements.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

-  `az account list --query [?state=='Enabled']`

One can also run the following command:
- `az account list --query[?cloudName='AzureCloud']`

## Expected Behavior
A list with all entries where state is set to Enabled.
For the alternative command the expected result should be all entries with cloudName AzureCloud.

## Environment Summary

Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.64

```
## Additional Context

<!--Please don't remove this:-->
<!--auto-generated-->

**Comment by adewaleo** [comment]
This worked for me:

`az account list --query "[?state=='Enabled']"
`

The solution is to wrap the query argument in quotes. It also seems like the string value for the key you are matching must be quoted with single quotes.

This did not work:

`az account list --query '[?state==Enabled]'
`
nor this:

`az account list --query '[?state=="Enabled"]'`


This also worked for me:

```
$ az account list --query "[?name== 'node']"
[
  {
    "cloudName": "AzureCloud",
    "id": "0000-0000-00000",
    "isDefault": true,
    "name": "node",
    "state": "Enabled",
    "tenantId": "1111-1111-1111",
    "user": {
      "name": "username@microsoft.com",
      "type": "user"
    }
  }
]
```
