### ISSUE TITLE
Query argument on az servicebus topic subscription list returns nothing

### ISSUE THREAD

**Issue by matt-lethargic** [Azure/azure-cli#9487]
## Describe the bug
`az servicebus topic subscription list --query id` returns nothing

**Command Name**
`az servicebus topic subscription list`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az servicebus topic subscription list --namespace-name {} --resource-group {} --topic-name {} --query id`

## Expected Behavior
Returns ids of subscriptions

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.63 *

```

**Comment by tjprescott** [comment]
This is user error. You need to use `--query "[].id"`

**Comment by matt-lethargic** [comment]
Happy to be corrected 😁
