### ISSUE TITLE
What are the default value for --accelerated-networking?

### ISSUE THREAD

**Issue by KeiroKamioka0000** [Azure/azure-cli#9496]
Please consider to add the default value for this.
I assuming it is false, is am I correct?

--accelerated-networking
Enable accelerated networking.

accepted values: false, true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29b6bb22-cb91-c7f8-995e-134d0fe5627f
* Version Independent ID: a92f24e8-36a0-808b-a9e7-598f85560b0f
* Content: [az network nic](https://docs.microsoft.com/en-us/cli/azure/network/nic?view=azure-cli-latest#az-network-nic-create)
* Content Source: [src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
Yes, if omitted, it would be false. This is the case for any flag.

**Comment by KeiroKamioka0000** [comment]
Thanks!

**Comment by adewaleo** [comment]
closing this then

**Comment by dcbrown16** [comment]
@tjprescott @adewaleo it seems odd that accelerated networking is disabled by default when creating the NIC, but enabled by default (if able) when creating a VM.
from az vm create:
--accelerated-networking 
Enable accelerated networking. Unless specified, CLI will enable it based on machine image and size.
accepted values: false, true
https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create

Should we take the vm creation behavior as an exception to the rule of "unspecified = false"?

**Comment by adewaleo** [comment]
@dcbrown16, yes I suppose it's an "exception to the rule". This is not surprising given the complexity of the command.

Accelerated networking greatly boosts up vm performance essentially for free (as long as its enabled and you have the correct vm image and size). I imagine that the desire is that it be set to true by default. However, given that not all vm sizes support it it can't always be true. Does that mean it should always be false? Probably not, as it makes sense to enable this feature **when** it can be enabled as users who can enable it would likely like to enable it.

This is my theory for why its behavior is like so. @yugangw-msft can speak more definitively about this design decision as he added this feature to the CLI.

cc: @zikalino

**Comment by dcbrown16** [comment]
Thanks, the specification seems fine as long as it is documented correctly.

**Comment by adewaleo** [comment]
This is documented in [az vm create -h](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create):

```
--accelerated-networking
Enable accelerated networking. Unless specified, CLI will enable it based on machine image and size.

accepted values: false, true
```

**Comment by dcbrown16** [comment]
@adewaleo sorry for the lack of clarity.
My understanding is that currently, although the quoted part suggests accelerated networking is always enabled when supported, it is NOT enabled if you are specifically attaching an existing NIC that doesn't have it enabled.
It sounds like you are working to change the behavior so that accelerated networking would be enabled in those cases, which would be great. If not, I'd like the nic parameter to specify that it overrides the default enabling. My understanding is that the existing NIC setting wins against whatever you might try to specify with the accelerated networking parameter.

**Comment by adewaleo** [comment]
> @adewaleo sorry for the lack of clarity.
> My understanding is that currently, although the quoted part suggests accelerated networking is always enabled when supported, it is NOT enabled if you are specifically attaching an existing NIC that doesn't have it enabled.
> It sounds like you are working to change the behavior so that accelerated networking would be enabled in those cases, which would be great. If not, I'd like the nic parameter to specify that it overrides the default enabling. My understanding is that the existing NIC setting wins against whatever you might try to specify with the accelerated networking parameter.

Yes I was responding to [this](https://github.com/Azure/azure-cli/issues/9496#issuecomment-498074851) question here.

Your second question which was about the nics setting being ignored [is addressed ](https://github.com/Azure/azure-cli/issues/9495#issuecomment-500609215) in the original [issue](#9495) you posted. I agree with you that this behavior is not good and the solution will be to either raise an error that the nic does not have a correct setting or to actually update the nics setting.

**Comment by dcbrown16** [comment]
Ok thanks!
