### ISSUE TITLE
az storage container generate-sas fails when using auth-mode login

### ISSUE THREAD

**Issue by rogeraustin** [Azure/azure-cli#9498]
## Describe the bug

**Command Name**
`az storage container generate-sas` fails when using `auth-mode login`

**Errors:**
```
self.account_key should not be None.
Traceback (most recent call last):
Temp\pip-install-dsvrkf2x\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 560, in execute
azure\cli\core\commands\__init__.py, ln 618, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 609, in _run_job
azure\cli\command_modules\storage\__init__.py, ln 240, in new_handler
azure\cli\command_modules\storage\__init__.py, ln 183, in handler
azure\cli\core\commands\__init__.py, ln 588, in _run_job
azure\cli\core\commands\__init__.py, ln 297, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 461, in default_command_handler
multiapi\storage\v2018_03_28\blob\baseblobservice.py, ln 407, in generate_container_shared_access_signature
multiapi\storage\v2018_03_28\common\_error.py, ln 130, in _validate_not_none
ValueError: self.account_key should not be None.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

1. Create a service principal account
2. For an existing storage account, assign role Storage Account Contributor to this service principal
3. 'az login' as service principal
4. `az storage container generate-sas --name {} --auth-mode {} --account-name {} --debug`

## Expected Behavior

SAS generated.

Note that SAS is correctly generated if `auth-mode key` is used instead

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.65

```
## Additional Context

--debug output is available if required

**Comment by achandmsft** [comment]
Thanks for the feedback @rogeraustin. We have identified this as a possible bug and @limingu is investigating.
