### ISSUE TITLE
Updating replyUrlsWithType property of a App Registration does not work

### ISSUE THREAD

**Issue by vinkobedek** [Azure/azure-cli#9501]
**Describe the bug**
`az ad app update --set` does not work as intended for the replyUrlsWithType property.
The error is as following:
```
Property 'replyUrlsWithType' not found on root. Send it as an additional property .
A value without a type name was found and no expected type is available. When the model is specified, each value in the payload must have a type which can be either specified in the payload, explicitly by the caller or implicitly inferred from the parent value.
```

**To Reproduce**
1. Create a new app registration and note the applicationID
2. Open Powershell 
3. `$replyUrls = '[{\"url\":\"http://localhost:8081\",\"type\":\"Web\"},{\"url\":\"http://localhost:8181\",\"type\":\"Web\"},{\"url\":\"urn://test-public-client/\",\"type\":\"InstalledClient\"}]'`
4. `az cli app update --id $applicationID --set replyUrlsWithType="$replyUrls"`
5. `az cli app update --id $applicationID --set replyUrlsWithType="[]"`

Steps 4 and 5 will throw the error mentioned in the description.

**Expected behavior**
I expect to be able to set the replyUrlsWithType property because i need to define a public client redirect reply url.

**Environment summary**
Windows, Powershell, az CLI 2.0.65

**Comment by jiasli** [comment]
It looks like the current public REST API (api-version=1.6) only supports `replyUrls`: https://github.com/Azure/azure-rest-api-specs/blob/e9b03021559994e2988fd977d465685795c2f70d/specification/graphrbac/data-plane/Microsoft.GraphRbac/stable/1.6/graphrbac.json#L2974, while Azure Portal is using api-verison=2.0. We will improve this in CLI soon. Currently please use `--reply-urls` instead:

```
az ad app update --id "xxx" --reply-urls "xxx" "xxx"
```
or
```
az ad app update --id "cb2e95ba-6d22-4913-b428-09e1f93f81f1" --set replyUrls=[]
```

**Comment by yashints** [comment]
This is a very common scenario for any company who has a mobile app and need native reply url to be set per each of their environment via their pipeline. I am surprised it's not part of the REST API already.

**Comment by Falconne** [comment]
Is there no progress on this issue? In our product I have a PowerShell script that uses `az` during the install process to create a suitable app registration, but I can't add a public reply-url because of this issue. We need to include instructions for customers to go to the Portal and manually add that, which is not a good look.

**Comment by fume** [comment]
any update on this?

**Comment by jiasli** [comment]
As MS Graph is now GA, you may use [Update application](https://docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&tabs=http) API directly with `az rest` to achieve the same effect as updating `replyUrlsWithType`.

The GUID part in the URL is the object ID of the application. You can retrieve it with application ID using

```sh
az ad app show --id 93dde3da-9fca-47dd-aee2-409b402ffed3 --query objectId
```


Get the application:

```sh
az rest --method GET --uri 'https://graph.microsoft.com/v1.0/applications/b4e4d2ab-e2cb-45d5-a31a-98eb3f364001'
```

Update `redirectUris` for `publicClient` property:

```sh
# pwsh
az rest --method PATCH --uri 'https://graph.microsoft.com/v1.0/applications/b4e4d2ab-e2cb-45d5-a31a-98eb3f364001' --headers 'Content-Type=application/json' --body '{\"publicClient\":{\"redirectUris\":[\"https://myapp.com\"]}}'

# bash
az rest --method PATCH --uri 'https://graph.microsoft.com/v1.0/applications/b4e4d2ab-e2cb-45d5-a31a-98eb3f364001' --headers 'Content-Type=application/json' --body '{"publicClient":{"redirectUris":["https://myapp.com"]}}'
```

Update `redirectUris` for `web` property:

```sh
# pwsh
az rest --method PATCH --uri 'https://graph.microsoft.com/v1.0/applications/b4e4d2ab-e2cb-45d5-a31a-98eb3f364001' --headers 'Content-Type=application/json' --body '{\"web\":{\"redirectUris\":[\"https://myapp.com\"]}}'

# bash
az rest --method PATCH --uri 'https://graph.microsoft.com/v1.0/applications/b4e4d2ab-e2cb-45d5-a31a-98eb3f364001' --headers 'Content-Type=application/json' --body '{"web":{"redirectUris":["https://myapp.com"]}}'
```

**Comment by fume** [comment]
thanks @jiasli , honestly i didn't notice the publicClient property on the application object, i was pretty sure it was a boolen, so thanks for pointing me out to that. I was doing exactly the same thing for the web.redirectUris array, so shame on me!

Do you know if updating the publicClient.redirectUris array will reflect in the Azure Portal? I mean, will the public clients be divided in categories such as Android, iOS/macOS?

**Comment by jiasli** [comment]
In Cloud Shell, I generated a hash with:

```sh
$ echo "something" | openssl sha1 -binary | openssl base64
UKTpiDgMCdKQrNq0vVPSTue0l98=
```

Then add an Android app to the AAD app in Azure Portal with

> Package name: com.myandroidapp
> Signature hash: UKTpiDgMCdKQrNq0vVPSTue0l98=

Then add an iOS app to the AAD app in Azure Portal with

> Bundle ID: com.myiosapp

Then retrieve the app using 

```pwsh
> az rest --method GET --uri 'https://graph.microsoft.com/v1.0/applications/b4e4d2ab-e2cb-45d5-a31a-98eb3f364001'

  "publicClient": {
    "redirectUris": [
      "msauth://com.myandroidapp/UKTpiDgMCdKQrNq0vVPSTue0l98%3D",
      "msauth://code/msauth.com.myiosapp%3A%2F%2Fauth",
      "msauth.com.myiosapp://auth"
    ]
  },
```

So you may follow this pattern to add Android and iOS apps accordingly.

To add an Android app:

```sh
az rest --method PATCH --uri 'https://graph.microsoft.com/v1.0/applications/b4e4d2ab-e2cb-45d5-a31a-98eb3f364001' --headers 'Content-Type=application/json' --body '{"publicClient":{"redirectUris":["msauth://com.myandroidapp/UKTpiDgMCdKQrNq0vVPSTue0l98%3D"]}}'
```

To add an iOS app:

```sh
az rest --method PATCH --uri 'https://graph.microsoft.com/v1.0/applications/b4e4d2ab-e2cb-45d5-a31a-98eb3f364001' --headers 'Content-Type=application/json' --body '{"publicClient":{"redirectUris":["msauth://code/msauth.com.myiosapp%3A%2F%2Fauth","msauth.com.myiosapp://auth"]}}'
```

**Comment by jiasli** [comment]
FYI, we will track all MS Graph issue in https://github.com/Azure/azure-cli/issues/12946.

**Comment by fume** [comment]
@jiasli , i'm already adding iOS and Android app that way, but i don't understand why when you navigate the app registration in the Azure Portal you don't see the Android platform (like you do when you add an Android app directly from the portal).

Adding the same Android app (using same packagename and same signaturehash) i have two different results in the azure portal.
Using the cli (basically using the MS Graph):
![image](https://user-images.githubusercontent.com/2969850/78973672-a9ff5e80-7b10-11ea-8191-b4ec4d877f23.png)

Using the portal:
![image](https://user-images.githubusercontent.com/2969850/78973445-365d5180-7b10-11ea-8302-f73463dc6fe8.png)

I would like to be sure that this won't alter the functionality of my app registration and that this is just a graphic "glitch". BTW, iOS/macOS redirectUris are recognized successfully. The manifest looks like the same...so i don't really know how the portal is "recognizing" the different platforms.

Thanks a lot.

**Comment by jiasli** [comment]
I added it twice with both Azure Portal and CLI:

```
az rest --method PATCH --uri 'https://graph.microsoft.com/v1.0/applications/b4e4d2ab-e2cb-45d5-a31a-98eb3f364001' --headers 'Content-Type=application/json' --body '{"publicClient":{"redirectUris":["msauth://com.microsoft.fumer.android/2pmj9i4rSx0yEb%2fviWBYkE%2fZQrk%3d"]}}'

$ az rest --method GET --uri 'https://graph.microsoft.com/v1.0/applications/b4e4d2ab-e2cb-45d5-a31a-98eb3f364001'
      "msauth://com.microsoft.fumer.android/2pmj9i4rSx0yEb%2FviWBYkE%2FZQrk%3D",
      "msauth://com.microsoft.fumer.android/2pmj9i4rSx0yEb%2fviWBYkE%2fZQrk%3d"
```

I think the issue is caused by the URL-encoded sequence: `%2F`,`%3D`. They should be capitalized, otherwise it makes Azure Portal confused.

**Comment by fume** [comment]
Uppercase to the rescue :) thanks a lot!

(but that's weird!)

**Comment by jiasli** [comment]
I agree, we will sync with MS Graph team on this.

**Comment by fume** [comment]
For future reference, if anyone will land here searching for a similar thing:

I'm using a powershell script that internally uses the Azure CLI. When preparing the json body for the MS Graph i was using the `[System.Web.Utilty]::UrlEncode()` method on the SignatureHash. For some reason, this encodes using the lowercase letters. You can use the `[Uri]::EscapeDataString()` method to achieve the objective: uppercase encoded chars!
