### ISSUE TITLE
az acr login without az login - should it work?

### ISSUE THREAD

**Issue by tomko80** [Azure/azure-cli#9505]
When I try to login to ACR using the "admin user" credentials I get the error "Get Token request returned http error: 400 and server response ... invalid_grant" indicating the token as expired. 

My assumption is that the _az acr login_ can be used using the admin user account without doing a _az login_ first. Is this assumption wrong? Does this work only with docker login and az login is required by the az cli?

What I like to do is to use ACR build without first signing in to azure.

**Comment by sajayantony** [comment]
@tomko80 Could you describe your scenario a bit more. We would like to understand scenario here.  ACR build is an ARM operation and hence you just need to be logged into the AZ CLI.

**Comment by yugangw-msft** [comment]
@tomko80, we are closing this issue due to inactivities, but we can reactivate it if you can respond to our question.
