### ISSUE TITLE
Have az account list/show contain the object id of the user or principle

### ISSUE THREAD

**Issue by zippy1981** [Azure/azure-cli#9506]
**Is your feature request related to a problem? Please describe.**

My ultimate goal is to use the Azure CLI to get the object id of user that I am logged into the Azure CLI with to set an environment variable which terraform will use to give itself permission to create certificates in the azure key vault it is creating.

**Describe the solution you'd like**
Ideally I'd like `az account show` to have an additional field in the user object e.g:

```json
{
  "environmentName": "AzureCloud",
  "id": "XXXXXXXX",
  "isDefault": true,
  "name": "Pay-As-You-Go",
  "state": "Enabled",
  "tenantId": "XXXXXXX",
  "user": {
    "object_id": "8fdc6358-0cde-45cd-b1b1-3ca7eb733a93",
    "name": "zippy1981@mydomain",
    "type": "user"
  }
}
```

Therefore I could issue the command `$env:TF_VAR_certificate_creator =  $(az account show --query 'user.object_id' -otsv)`

And it would put the right object id in m terraform file like so:

```terraform
resource "azurerm_key_vault" "always_encrypted_sample" {
  # . . . . . . . SNIP . . . . . .
  access_policy {
    tenant_id = "${data.azurerm_client_config.current.tenant_id}"
    object_id = "${var.certificate_creator}"

    certificate_permissions = [
      "create", "get" # Terraform needs get to make the cert, probably to check its existance
    ]
  }
```

**Describe alternatives you've considered**

The following would also work:

* `az ad user show` could default to the currently logged in user if using user auth as opposed to service principle auth.
* If `az account get-access-token` had a parameter to output the decoded JWT token that I could query with --query I could read the `oid` property. 
* If `az account show` listed the upn as opposed to the object id, I could get this info on to command lines

**Additional context**

**Comment by Arnavion** [comment]
Doesn't `az ad signed-in-user show --query objectId --output tsv` do what you want?

**Comment by zippy1981** [comment]
@Arnavion Why yes that will work. I didn't see that.

**Comment by zippy1981** [comment]
Reopening, because, which that does solve my particular issue, the object id or upn of the user seems more important than the display name for in the `account list/show` output.

**Comment by yonzhan** [comment]
add to S164.

**Comment by yonzhan** [comment]
add to S170

**Comment by qianwens** [comment]
@zippy1981 `az ad signed-in-user show --query objectId --output tsv` will output the "oid" of the current signed-in-user which is the same as the one decoded from the access token. To help us understand your requirement, could you please help let us know why does it not resolve your problem?

**Comment by qianwens** [comment]
Close this issue since there is no response for more than 15 days. Please help file a new issue if you still have questions.

**Comment by ElvenSpellmaker** [comment]
This doesn't seem to work for non-user accounts, such as an Azure DevOps Service Connection SPN.

**Comment by ElvenSpellmaker** [comment]
This doesn't seem to work for non-user accounts, such as an Azure DevOps Service Connection SPN.

**Comment by jiasli** [comment]
@ElvenSpellmaker, `az ad signed-in-user show` is for user account. For Service Principal, please use `az ad sp show` whose output contains an `objectId` property.

```
> az ad sp show --id <appId> --query objectId --output tsv
4d1c7269-582f-4698-8369-4334eb33cd0f
```

**Comment by Steiniche** [comment]
At some point objectId seems to have been updated to id in the graph api.
The command is now:

`az ad signed-in-user show --query id --output tsv`
