### ISSUE TITLE
az run-command script sample

### ISSUE THREAD

**Issue by giovannifl** [Azure/azure-cli#9513]
Hi,
Please could you provide a sample about how to execute az run-command using a file with bash or ps1 script ? Powershell version of this command has a "--scriptpath" switch while here it's written " Use @{file} to load from a file"

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f04b196d-7d11-7213-f037-f12b85b19c52
* Version Independent ID: adc05d8e-b13b-134b-5f61-42aaf23666df
* Content: [az vm run-command](https://docs.microsoft.com/en-us/cli/azure/vm/run-command?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by achandmsft** [comment]
Thanks for your feedback @giovannifl Could you let me know if the blog [here] (https://techcommunity.microsoft.com/t5/ITOps-Talk-Blog/How-to-Run-scripts-on-Azure-Virtual-Machines-with-the-Run/ba-p/292446 ) is what you are looking for or do you need something else?

**Comment by giovannifl** [comment]
Hi, 
Not exactly.
This document should also include an example such as:
az vm run command invoke  -g MyResourceGroup -n MyVm --command-id RunPowerShellScript --scripts @test.ps1

**Comment by devbeard** [comment]
+1 to Giovannis suggestion. I am currently struggeling with starting a PowerShell script (.ps1) on a VM including positional parameters. Would be great to see an example in the docs of a PowerShell script with parameters.

**Comment by adewaleo** [comment]
I will work on adding some examples that should hopefully shed light on this

**Comment by ConnorDickson** [comment]
I have a stackoverflow question [here](https://stackoverflow.com/questions/56578122/azure-cli-run-command-invoke-runpowershellscript-with-parameters) that has been answered and should help you out

**Comment by adewaleo** [comment]
I apologize for not addressing the issue yet. I was been working on another feature / issues. @ConnorDickson. Thanks a lot for addressing @devbeard's question.

I will add the examples this sprint. And reference this issue.

For now though, https://github.com/Azure/azure-cli/issues/7505 raises and addresses a general question on run command key value arguments through the CLI. You might find it helpful.

**Comment by yugangw-msft** [comment]
https://github.com/Azure/azure-cli/pull/9705 fixes it
