### ISSUE TITLE
az graph query for tags using table output does not show correct output

### ISSUE THREAD

**Issue by amaturehr** [Azure/azure-cli#9517]
**Description**

Running az graph query with TABLE output shows empty tags despite tag values showing up in JSON output

**To Reproduce**
```
$ az graph query -q 'project name, type, location, tags | limit 2' --output table 

Location    Name               Tags
----------  -----------------  ------
eastus      Doug-RG-vnet
centralus   doug-waf-test
```
```
$ az graph query -q 'project name, type, location, tags | limit 2'

[
  {
    "location": "eastus",
    "name": "Doug-RG-vnet",
    "tags": {
      "vm": "testvm"
    },
    "type": "microsoft.network/virtualnetworks"
  },
  {
    "location": "centralus",
    "name": "doug-waf-test",
    "tags": "",
    "type": "microsoft.operationalinsights/workspaces"
  }
]
```

**Expected behavior**

I would expect the table output to look similar to the following:

```
Location    Name               Tags
----------  -----------------  ------
eastus      Doug-RG-vnet       vm: testvm
centralus   doug-waf-test      ---
```
In the event of a resource having multple tag values I would expect something like:

```
Location    Name               Tags
----------  -----------------  -------------------------------------------------------
eastus      Doug-RG-vnet       tagname: tagvalue, tagname: tagvalue, tagname: tagvalue
centralus   doug-waf-test      ---
```

**Environment summary**

Install Method: pip
CLI Version: 
```
az - 2.0.62
resource-graph - 0.1.8
```
OS version: Linux
Shell Type : Bash

**Comment by achandmsft** [comment]
Hi @amaturehr, Thanks for the feedback. So we can prioritize this better, could you please let us know if you needed this formatting for readability while using this interactively or for any other scenario?

**Comment by amaturehr** [comment]
Hi @achandmsft , I just needed this formatting for readability.  I often provide sample commands for users to verify a specific output, the table output is more friendly for ad-hoc things, rather than the json.  

I also realized in the above example the "type" column is missing too, I was mostly just looking for the tag values, but "type" seems to be missing too...

Thanks for the response.

Doug

**Comment by yonzhan** [comment]
add to S164.

**Comment by yonzhan** [comment]
add to S170

**Comment by yonzhan** [comment]
add to S172

**Comment by doherty100** [comment]
Logged similar issue:

https://github.com/Azure/azure-cli/issues/14197

**Comment by jiasli** [comment]
`tags` is not a simple type like `string` or `int`, but a complex type - `dict`: 

```
"tags": {
      "tag1": "value1",
      "tag2": "value2"
    },
```

There is no default transformer for `dict`. The `resource-graph` extension owner needs to implement a corresponding `transformer`, such as those in [`_transformers.py`](https://github.com/Azure/azure-cli/blob/c3fd340dbd8a734c6246bf0f860539d0fb71bca8/src/azure-cli/azure/cli/command_modules/storage/_transformers.py).

**Comment by snaheth** [comment]
Thanks @jiasli. Our team (Azure Resource Graph) will implement a transformer.py to address this. We'll update this thread on our progress.

**Comment by snaheth** [comment]
Upon trying this out myself within the Azure CLI, I noticed that you can actually use JMESPath within the query parameter to have the tags listed in the table. Example query:

```
az graph query -q "project name, type, location, tags | take 2" --output table --query '[].{Name:name,Location:location,Tags: to_string(tags)}'
```

I understand that this doesn't fully meet the format @amaturehr gave as his ideal output...but given the low demand for this ask and the fix above, we'll close this issue for now.
