### ISSUE TITLE
Add `-v` alias for `--version` flag

### ISSUE THREAD

**Issue by joshgav** [Azure/azure-cli#952]
Running `az -v` is an easy way to check that it's been installed correctly. Would be nice if the `-v` and `--version` options took a short path too, in other words not load much and return as fast as possible.

Related to: https://github.com/Azure/azure-cli/issues/581

Thanks!

**Comment by johanste** [comment]
@joshgav, out of curiosity, what are you using the command for that makes performance/short parameter version desirable? 

To give you some context, the az cli is less monolithic and more component based than the previous xplat cli. Just having the CLI installed does not guarantee that you have the specific commands (or version of the commands) that you are interested in installed. We do intent to have a core set of packages be included in the basic install, but you can add/remove from the set at any point. In other words, knowing that only the base cli is available and can be loaded may not be accomplishing what you want.

Oh, and the reason that we haven't enabled -v (even though it is pretty much a standard flag) is that we are trying to avoid "squatting on" short parameter names from other commands. It is not a hard & fast rule (we did decide to use -h for help), so we are more than open to feedback on this.

**Comment by tjprescott** [comment]
@johanste actually, I use `--version` and `-v` in the key vault commands it doesn't complain. The check for version is very near the beginning and only "claims" --version if it is the second argument (after az). So this could actually work without stealing an option from commands.

**Comment by derekbekoe** [comment]
`az -v` is available is recent CLI versions.
