### ISSUE TITLE
Cant build azure function using zip deployment

### ISSUE THREAD

**Issue by vfragola** [Azure/azure-cli#9530]
## Describe the bug

**Command Name**
`az functionapp deployment source config-zip`

**Errors:**
```
('Connection aborted.', OSError("(10054, 'WSAECONNRESET')",))
Traceback (most recent call last):
urllib3\urllib3\contrib\pyopenssl.py, ln 320, in _send_until_done
pip-install-dsvrkf2x\pyOpenSSL\OpenSSL\SSL.py, ln 1737, in send
pip-install-dsvrkf2x\pyOpenSSL\OpenSSL\SSL.py, ln 1639, in _raise_ssl_error
OpenSSL.SSL.SysCallError: (10054, 'WSAECONNRESET')

...

pip-install-dsvrkf2x\requests\requests\sessions.py, ln 646, in send
pip-install-dsvrkf2x\requests\requests\adapters.py, ln 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(10054, 'WSAECONNRESET')",))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az functionapp deployment source config-zip -g {} -n {} --src {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.65

```

**Comment by ahmedelnably** [comment]
@vfragola can you please provide the function app name so we can investigate more
Also if you can provide the --debug output (note that it may contain sensitive data, please remove these before sharing it with us)

**Comment by vfragola** [comment]
GET https://management.azure.com/resources?api-version=2018-09-01&$filter=(SubscriptionId%20eq%20'cb0f5d39-b859-40c4-a52e-5a22e7189743'%20and%20name%20eq%20'MasterPersistDev'%20and%20resourceType%20eq%20'Microsoft.Web/sites') HTTP/1.1
User-Agent: functions-core-tools/2.7.1158
Accept: application/json
x-ms-request-id: d8066234-32da-44a4-a275-e378a664f154
Host: management.azure.com


HTTP/1.1 504 Fiddler - Receive Failure
Date: Thu, 06 Jun 2019 18:11:05 GMT
Content-Type: text/html; charset=UTF-8
Connection: close
Cache-Control: no-cache, must-revalidate
Timestamp: 14:11:05.209

[Fiddler] ReadResponse() failed: The server did not return a complete response for this request. Server returned 0 bytes.

**Comment by ahmedelnably** [comment]
If the issue still persists in the latest version please reopen

**Comment by GiriNeu** [comment]
what could be the solution for this issue?
