### ISSUE TITLE
Windows SAS token parsed badly

### ISSUE THREAD

**Issue by schade-l** [Azure/azure-cli#9536]
**Describe the bug**
Using a SAS token, provided as a string in powershell, causes it to not be fully parsed, attempting to execute various commands for each of the parameters in the token, and only parsing small portions of it.

Input
```powershell
$sas = "<SAS_TOKEN>"
az storage blob exists --container-name 'contianer' --name 'file.json' --account-name storageaccount --sas $sas
```

Output
```
{
  "exists": false
}
'ss' is not recognized as an internal or external command,
operable program or batch file.
'srt' is not recognized as an internal or external command,
operable program or batch file.
'sp' is not recognized as an internal or external command,
operable program or batch file.
'se' is not recognized as an internal or external command,
operable program or batch file.
'st' is not recognized as an internal or external command,
operable program or batch file.
'spr' is not recognized as an internal or external command,
operable program or batch file.
'sig' is not recognized as an internal or external command,
operable program or batch file.
```

This can be circumvented by wrapping the SAS token with double quotes inside the string literal:

```powershell
$sas = '"<SAS_TOKEN>"'
```

This seems like a hacky workaround, and the cli should be able to just read in the whole string.

**Environment summary**

```
Windows-10-10.0.17134-SP0
Python 3.6.6
Shell: powershell.exe
```

Installed using scoop (`scoop bucket add extras; scoop install azure-cli`)

**Additional context**

**Comment by tjprescott** [comment]
This is due to Powershell interpreting `&` as a new command. There is nothing the CLI can do about this since it occurs before the input reaches the CLI. You will need to escape your string appropriately for your Powershell version.

**Comment by schade-l** [comment]
I'm not sure this is correct, because `&` isn't a command separator in Powershell (it's a separate reserved character with no functionality: 

```$ echo "test" & echo "foo"
At line:1 char:13
+ echo "test" & echo "foo"
+             ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
```
It seems more likely that it's being passed through CMD, where `&` is a command separator. This actually makes some sense, in that it seems that you are passing the value of the string literal to a separate call that executes in CMD.

**Comment by tjprescott** [comment]
Run on CMD with --debug:
```
Command arguments: ['storage', 'container', 'list', '--sas-token', 'se=2020-01-01T00%3A00Z&sp=rwdlacup&sv=2018-03-28&ss=qt&srt=sco&sig=Y%2BnDcVL7b2FOM0wxqpObWZK1D%2B8DYPceoLRnabYc%2BxY%3D', '--debug']
```

Run on Powershell with --debug:
```
Command arguments: ['storage', 'container', 'list', '--debug', '--sas-token', 'se=2020-01-01T00%3A00Z']
```

Powershell is splitting at the & and treating it as a new command.

**Comment by schade-l** [comment]
It still doesn't seem right, because "not operable as an internal or external command" is a CMD output, not a Powershell one and other Powershell commands parse `"<SASToken>"` perfectly.

For example:
In powershell, with the following test.py:

```python
####[test.py]
import sys

if len(sys.argv) == 2:
  print(f"SAS Token: {sys.argv[1]}")
```


Running `python test.py "<SAS Token>"` works as expected

**Comment by xenalite** [comment]
@tjprescott Same issue here. Please re-open this issue as the closing reason is incorrect.
I tried to pass the SAS token using every method of quoting strings, including calling az like so:
`az @('--source-sas', '<sas_token>')`
None of them worked.

**Comment by adstep** [comment]
Taken from [stackoverflow](https://stackoverflow.com/a/47313365).

Try wrapping the SAS token in a 2nd set of quotes:

```
$sasToken = '"st=2017-11-13T10%3A55%3A06Z&se=2017-11-13T11%3A27%3A06Z&sp=w&spr=https&sv=2017-04-17&sr=c&sig=%2BA6LDTwHes6JdxEAHXSvbYc70y30OcznjMVSyFbCXog%3D"'
```

so that the CLI command looks like this:
```
--sas-token "st=2017-11-13T10%3A55%3A06Z&se=2017-11-13T11%3A27%3A06Z&sp=w&spr=https&sv=2017-04-17&sr=c&sig=%2BA6LDTwHes6JdxEAHXSvbYc70y30OcznjMVSyFbCXog%3D"
```

**Comment by MatisseHack** [comment]
The trick @adstep pointed out of wrapping the double quoted string in single quotes does indeed work!

I do think this is a bug in the Azure CLI for Windows though. An ampersand inside of a quoted string should not be an issue. For example `Write-Host "fast&furious"` works just fine and outputs `fast&furious` as you'd expect.

Also the same `az storage blob copy start` command works fine in PowerShell on a Mac.

**Comment by stej** [comment]
This trick with embedded double quotes doesn't work if `PSNativeCommandArgumentPassing` feature is enabled.
```
(Get-ExperimentalFeature -Name PSNativeCommandArgumentPassing).Enabled
```

**Comment by Matthew0x** [comment]
As a person living late 2022 I can confirm that the person from 2019 was right.
I confirm that I just faced the exactly same problem with SAS and connection strings.

The workaround worked.

"Powershell is splitting at the & and treating it as a new command."
This statement seems correct.

However, quoting the PS documentation:
"Single-quoted strings
A string enclosed in single quotation marks is a verbatim string. The string is passed to the command exactly as you type it. No substitution is performed."

?

**Comment by Superzer0** [comment]
Hi, 
For those who stumbled upon the same problem, I was able to fix it with the following line: 
```powershell
$sasTokenEscaped = $IsWindows ? "`"$sasToken`"" : $sasToken
```
