### ISSUE TITLE
all commands should return json

### ISSUE THREAD

**Issue by singingfish** [Azure/azure-cli#9539]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by singingfish** [comment]
I've got a specific situation here where `az vm delete` returns invalid json as it's returning nothing.:

The code I'm running is:

```
sub run {
    my ($cmd) = @_;
    my $j = capture $cmd;
    my $res = eval { $json->decode($j) };
    warn "command: $cmd .... did not return valid JSON ... output was: $j" if $@;
    return ($res, $j);
}
```

and the warning I'm getting is:

```
command: az vm delete -g ny_resource_group -n my_vm -y .... did not return valid JSON ... output was:  at move_availability_set.pl line 84.
```

Which tells me it's returning an empty string.  Really all operations should be returning JSON for consistency.  In this case some informative valid json  should be returned.  For example:

```
{ command: "az vm delete ... etc ...",
  success: true
 }
```
or anything really.  Having it return an empty string makes abstracting the operation unnecessarily tricky, as any decent json parser will fail, yet the command itself still returns a successful exit status.

**Comment by tjprescott** [comment]
It is the standard behavior of deletes in Azure and thus the CLI that they do not return any payload on a successful delete. Thus, you will need to adjust your script so that it is not reliant on the structure of the JSON payload. As you point out, you can examine the exit code to determine that the command was successful.
