### ISSUE TITLE
Error loading command modules: TypeError: Unrecognized kwargs: ['is_preview']

### ISSUE THREAD

**Issue by viananth** [Azure/azure-cli#9545]
**Describe the bug**
Error while loading command modules during VM creation

**To Reproduce**
az cloud update --profile 2018-03-01-hybrid
az vm create -g testrg -n testvm

**Expected behavior**
To create a VM without issues

**Environment summary**
Edge build
C:\Users\AzureStackAdmin>az -v
azure-cli                         2.0.65

acr                       2.2.8.dev19715
acs                       2.4.3.dev19715
advisor                            2.0.0
ams                       0.5.1.dev18717
appservice                        0.2.20
backup                             1.2.4
batch                     4.0.2.dev19715
batchai                            0.4.9
billing                            0.2.1
botservice                         0.2.1
cdn                       0.3.0.dev18717
cloud                              2.1.1
cognitiveservices                  0.2.5
command-modules-nspkg               2.0.2
configure                         2.0.23
consumption                        0.4.3
container                         0.3.17
core                              2.0.65
cosmosdb                          0.2.10
deploymentmanager                  0.1.0
dla                                0.2.5
dls                                0.1.9
dms                                0.1.3
eventgrid                          0.2.3
eventhubs                          0.3.6
extension                          0.2.5
feedback                           2.2.1
find                               0.3.3
hdinsight                          0.3.4
interactive                        0.4.4
iot                      0.3.10.dev19715
iotcentral                         0.1.6
keyvault                          2.2.15
kusto                              0.2.2
lab                                0.1.7
maps                               0.3.4
monitor                           0.2.14
natgateway                         0.1.0
network                            2.5.0
nspkg                              3.0.3
policyinsights                     0.1.3
privatedns                         1.0.1
profile                            2.1.5
rdbms                             0.3.11
redis                              0.4.3
relay                              0.1.4
reservations                       0.4.2
resource                 2.1.15.dev19715
role                               2.6.2
search                             0.1.1
security                           0.1.1
servicebus                         0.3.5
servicefabric                     0.1.19
signalr                            1.0.0
sql                                2.2.4
sqlvm                              0.1.1
storage                            2.4.2
telemetry                          1.0.2
vm                       2.2.22.dev19715

Python location 'C:\Program Files (x86)\Python35\python.exe'
Extensions directory 'C:\Users\AzureStackAdmin\.azure\cliextensions'

Python (Windows) 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

**Additional context**
15692 : 2019-06-02 15:40:44,784 : DEBUG : cli.knack.cli : Command arguments: ['vm', 'create', '--resource-group', 'canvr626', '--name', 'testvm', '--image', 'Win2016Datacenter', '--admin-username', 'xxxxxxxxxxxxxxxx', '--admin-password', 'xxxxxxxxxxxxxxxxxxxxx']
15692 : 2019-06-02 15:40:44,784 : DEBUG : cli.knack.cli : Event: Cli.PreExecute []
15692 : 2019-06-02 15:40:44,784 : DEBUG : cli.knack.cli : Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x02C0D468>, <function OutputProducer.on_global_arguments at 0x02CA7030>, <function CLIQuery.on_global_arguments at 0x02CBD228>]
15692 : 2019-06-02 15:40:44,831 : DEBUG : cli.knack.cli : Event: CommandInvoker.OnPreCommandTableCreate []
15692 : 2019-06-02 15:40:44,863 : DEBUG : cli.azure.cli.core : Installed command modules ['acr', 'acs', 'advisor', 'ams', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'maps', 'monitor', 'natgateway', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
15692 : 2019-06-02 15:40:44,863 : DEBUG : cli.azure.cli.core : Loaded module 'acr' in 0.010 seconds.
15692 : 2019-06-02 15:40:44,878 : ERROR : cli.azure.cli.core : Error loading command module 'acs'
15692 : 2019-06-02 15:40:44,878 : DEBUG : cli.azure.cli.core : Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\__init__.py", line 144, in _update_command_table_from_modules
    module_command_table, module_group_table = _load_module_command_loader(self, args, mod)
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 893, in _load_module_command_loader
    return _load_command_loader(loader, args, mod, 'azure.cli.command_modules.')
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 875, in _load_command_loader
    command_table = command_loader.load_command_table(args)
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\command_modules\acs\__init__.py", line 23, in load_command_table
    load_command_table(self, args)
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\command_modules\acs\commands.py", line 77, in load_command_table
    g.custom_command('install-connector', 'k8s_install_connector', is_preview=True)
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 1073, in custom_command
    return self._command(name, method_name=method_name, custom_command=True, **kwargs)
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 1077, in _command
    merged_kwargs = self._flatten_kwargs(kwargs, get_command_type_kwarg(custom_command))
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 1016, in _flatten_kwargs
    merged_kwargs = self._merge_kwargs(kwargs)
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 1013, in _merge_kwargs
    return _merge_kwargs(kwargs, base, CLI_COMMAND_KWARGS)
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\commands\__init__.py", line 964, in _merge_kwargs
    raise TypeError('unrecognized kwargs: {}'.format(unrecognized_kwargs))
TypeError: unrecognized kwargs: ['is_preview']

15692 : 2019-06-02 15:40:45,441 : ERROR : cli.azure.cli.core.parser : az: 'vm' is not in the 'az' command group. See 'az --help'.
15692 : 2019-06-02 15:40:45,441 : ERROR : cli.azure.cli.core.parser : az: 'vm' is not in the 'az' command group. See 'az --help'.

**Comment by tjprescott** [comment]
This isn't really a Stack-specific issue. @limingu can you take a look

**Comment by tjprescott** [comment]
You need to update your version of knack. `pip install --upgrade knack`

**Comment by viananth** [comment]
@tjprescott Thank you Travis! Seems like its already up-to-date.

> C:\Users\AzureStackAdmin>pip install --upgrade knack
Requirement already up-to-date: knack in c:\program files (x86)\python35\lib\site-packages (0.6.2)
Requirement already satisfied, skipping upgrade: pygments in c:\program files (x86)\python35\lib\site-packages (from knack) (2.4.2)
Requirement already satisfied, skipping upgrade: colorama in c:\program files (x86)\python35\lib\site-packages (from knack) (0.4.1)
Requirement already satisfied, skipping upgrade: six in c:\program files (x86)\python35\lib\site-packages (from knack) (1.12.0)
Requirement already satisfied, skipping upgrade: argcomplete in c:\program files (x86)\python35\lib\site-packages (from knack) (1.10.0)
Requirement already satisfied, skipping upgrade: pyyaml in c:\program files (x86)\python35\lib\site-packages (from knack) (5.1)
Requirement already satisfied, skipping upgrade: jmespath in c:\program files (x86)\python35\lib\site-packages (from knack) (0.9.4)
Requirement already satisfied, skipping upgrade: tabulate in c:\program files (x86)\python35\lib\site-packages (from knack) (0.8.3)

**Comment by tjprescott** [comment]
`pip list`?

**Comment by viananth** [comment]
C:\Users\AzureStackAdmin>pip list
Package                               Version
------------------------------------- ---------------
adal                                  1.2.1
antlr4-python3-runtime                4.7.2
applicationinsights                   0.11.7
argcomplete                           1.10.0
asn1crypto                            0.24.0
azure-batch                           6.0.0
azure-cli                             2.0.65
azure-cli-acr                         2.2.8.dev19715
azure-cli-acs                         2.4.3.dev19715
azure-cli-advisor                     2.0.0
azure-cli-ams                         0.5.1.dev18717
azure-cli-appservice                  0.2.20
azure-cli-backup                      1.2.4
azure-cli-batch                       4.0.2.dev19715
azure-cli-batchai                     0.4.9
azure-cli-billing                     0.2.1
azure-cli-botservice                  0.2.1
azure-cli-cdn                         0.3.0.dev18717
azure-cli-cloud                       2.1.1
azure-cli-cognitiveservices           0.2.5
azure-cli-command-modules-nspkg       2.0.2
azure-cli-configure                   2.0.23
azure-cli-consumption                 0.4.3
azure-cli-container                   0.3.17
azure-cli-core                        2.0.65
azure-cli-cosmosdb                    0.2.10
azure-cli-deploymentmanager           0.1.0
azure-cli-dla                         0.2.5
azure-cli-dls                         0.1.9
azure-cli-dms                         0.1.3
azure-cli-eventgrid                   0.2.3
azure-cli-eventhubs                   0.3.6
azure-cli-extension                   0.2.5
azure-cli-feedback                    2.2.1
azure-cli-find                        0.3.3
azure-cli-hdinsight                   0.3.4
azure-cli-interactive                 0.4.4
azure-cli-iot                         0.3.10.dev19715
azure-cli-iotcentral                  0.1.6
azure-cli-keyvault                    2.2.15
azure-cli-kusto                       0.2.2
azure-cli-lab                         0.1.7
azure-cli-maps                        0.3.4
azure-cli-monitor                     0.2.14
azure-cli-natgateway                  0.1.0
azure-cli-network                     2.5.0
azure-cli-nspkg                       3.0.3
azure-cli-policyinsights              0.1.3
azure-cli-privatedns                  1.0.1
azure-cli-profile                     2.1.5
azure-cli-rdbms                       0.3.11
azure-cli-redis                       0.4.3
azure-cli-relay                       0.1.4
azure-cli-reservations                0.4.2
azure-cli-resource                    2.1.15.dev19715
azure-cli-role                        2.6.2
azure-cli-search                      0.1.1
azure-cli-security                    0.1.1
azure-cli-servicebus                  0.3.5
azure-cli-servicefabric               0.1.19
azure-cli-signalr                     1.0.0
azure-cli-sql                         2.2.4
azure-cli-sqlvm                       0.1.1
azure-cli-storage                     2.4.2
azure-cli-telemetry                   1.0.2
azure-cli-vm                          2.2.22.dev19715
azure-common                          1.1.21
azure-datalake-store                  0.0.39
azure-functions-devops-build          0.0.22
azure-graphrbac                       0.60.0
azure-keyvault                        1.1.0
azure-mgmt-advisor                    2.0.1
azure-mgmt-applicationinsights        0.1.1
azure-mgmt-authorization              0.50.0
azure-mgmt-batch                      6.0.0
azure-mgmt-batchai                    2.0.0
azure-mgmt-billing                    0.2.0
azure-mgmt-botservice                 0.2.0
azure-mgmt-cdn                        3.1.0
azure-mgmt-cognitiveservices          3.0.0
azure-mgmt-compute                    5.0.0
azure-mgmt-consumption                2.0.0
azure-mgmt-containerinstance          1.4.0
azure-mgmt-containerregistry          2.8.0
azure-mgmt-containerservice           5.2.0
azure-mgmt-cosmosdb                   0.5.2
azure-mgmt-datalake-analytics         0.2.1
azure-mgmt-datalake-nspkg             3.0.1
azure-mgmt-datalake-store             0.5.0
azure-mgmt-datamigration              0.1.0
azure-mgmt-deploymentmanager          0.1.0
azure-mgmt-devtestlabs                2.2.0
azure-mgmt-dns                        2.1.0
azure-mgmt-eventgrid                  2.0.0
azure-mgmt-eventhub                   2.6.0
azure-mgmt-hdinsight                  0.2.1
azure-mgmt-iotcentral                 1.0.0
azure-mgmt-iothub                     0.8.2
azure-mgmt-iothubprovisioningservices 0.2.0
azure-mgmt-keyvault                   1.1.0
azure-mgmt-kusto                      0.3.0
azure-mgmt-loganalytics               0.2.0
azure-mgmt-managementgroups           0.1.0
azure-mgmt-maps                       0.1.0
azure-mgmt-marketplaceordering        0.1.0
azure-mgmt-media                      1.1.1
azure-mgmt-monitor                    0.5.2
azure-mgmt-msi                        0.2.0
azure-mgmt-network                    2.7.0
azure-mgmt-nspkg                      3.0.2
azure-mgmt-policyinsights             0.3.1
azure-mgmt-privatedns                 0.1.0
azure-mgmt-rdbms                      1.8.0
azure-mgmt-recoveryservices           0.1.1
azure-mgmt-recoveryservicesbackup     0.1.2
azure-mgmt-redis                      6.0.0
azure-mgmt-relay                      0.1.0
azure-mgmt-reservations               0.3.1
azure-mgmt-resource                   2.1.0
azure-mgmt-search                     2.0.0
azure-mgmt-security                   0.1.0
azure-mgmt-servicebus                 0.6.0
azure-mgmt-servicefabric              0.2.0
azure-mgmt-signalr                    0.1.1
azure-mgmt-sql                        0.12.0
azure-mgmt-sqlvirtualmachine          0.2.0
azure-mgmt-storage                    3.3.0
azure-mgmt-trafficmanager             0.51.0
azure-mgmt-web                        0.41.0
azure-multiapi-storage                0.2.3
azure-nspkg                           3.0.2
azure-storage-blob                    1.3.1
azure-storage-common                  1.4.2
azure-storage-nspkg                   3.1.0
bcrypt                                3.1.6
certifi                               2019.3.9
cffi                                  1.12.3
chardet                               3.0.4
colorama                              0.4.1
cryptography                          2.4.2
fabric                                2.4.0
humanfriendly                         4.18
idna                                  2.8
invoke                                1.2.0
isodate                               0.6.0
Jinja2                                2.10.1
jmespath                              0.9.4
knack                                 0.6.2
MarkupSafe                            1.1.1
mock                                  3.0.5
msrest                                0.6.6
msrestazure                           0.6.0
oauthlib                              3.0.1
paramiko                              2.4.2
pip                                   19.1.1
portalocker                           1.2.1
prompt-toolkit                        1.0.16
psutil                                5.6.2
pyasn1                                0.4.5
pycparser                             2.19
pydocumentdb                          2.3.3
Pygments                              2.4.2
PyJWT                                 1.7.1
PyNaCl                                1.3.0
pyOpenSSL                             19.0.0
pyperclip                             1.7.0
pypiwin32                             223
pyreadline                            2.1
python-dateutil                       2.8.0
pytz                                  2019.1
pywin32                               224
PyYAML                                5.1
requests                              2.22.0
requests-oauthlib                     1.2.0
scp                                   0.13.2
setuptools                            39.0.1
six                                   1.12.0
sshtunnel                             0.1.4
tabulate                              0.8.3
urllib3                               1.25.3
virtualenv                            16.6.0
vsts                                  0.1.25
vsts-cd-manager                       1.0.2
wcwidth                               0.1.7
websocket-client                      0.56.0
wheel                                 0.30.0
xmltodict                             0.12.0

C:\Users\AzureStackAdmin>

**Comment by tjprescott** [comment]
Hmm... thanks. I'll investigate.

**Comment by tjprescott** [comment]
I recreated my virtual environment and this error went away.

**Comment by viananth** [comment]
@tjprescott Travis, this should work out-of-the-box without virtual environments, right? We are hitting this issue in our CI, which assumes no virtual environments.

**Comment by tjprescott** [comment]
@marstr do you think this has to do with the fact that the released CLI is 2.0.66 but the dev branch still says 2.0.65?  We have had these problems before with the edge build.

**Comment by tjprescott** [comment]
@viananth you are right that this shouldn't have anything to do with virtual environments. You are installing via the Edge Build, right? Is this still giving you this error?

**Comment by viananth** [comment]
Thank you Travis! With the latest edge build, the issue is gone. Was it because the az version of previous edge build was 2.0.65? The current version of edge build is 2.0.66.

**Comment by tjprescott** [comment]
Yes. @marstr has more context on the issue.

**Comment by marstr** [comment]
Yep, it seems like a bit of a race condition was exposed. When we release new PyPI packages, pip factors the newer version of the package over local copies. This broke a few bits of our CI/CD infrastructure. This problem should be eased when we merge all of the command modules into azure-cli package (https://github.com/Azure/azure-cli/issues/8592).

**Comment by viananth** [comment]
Thank you @marstr @tjprescott
