### ISSUE TITLE
Kubernetes Dashboard doesn't provide access to any resources

### ISSUE THREAD

**Issue by andrei-dascalu** [Azure/azure-cli#9552]
## Describe the bug

**az aks browse --resource-group <group> --name <cluster name>**

**Errors:**
`nodes is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list resource "nodes" in API group "" at the cluster scope`

## To Reproduce:
1. Create a K8S cluster, either under existing RS or new RS
2. Run `az aks browse` on it

## Expected Behavior

- K8S Dashboard loads providing information and access to objects/nodes

## Environment Summary
```
Darwin-18.6.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.64 *

```

**Comment by x10an14** [comment]
You've met the situation described here; https://blogs.msdn.microsoft.com/kennethteo/2018/07/26/aks-with-aad/

It's not a bug per se, it's rather a (not well documented in AKS imho) missing link that is indeed missing.

**Comment by andrei-dascalu** [comment]
@x10an14  hm, indeed. This should definitely be part of the official documentation, at the very least. Though, at the same time, it stands to reason that if the dashboard is part of the cluster provisioning then appropriate bindings and role bindings should be there.

**Comment by brendandburns** [comment]
This is documented here:

https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard#for-rbac-enabled-clusters

@tjprescott This issure can be closed.
