### ISSUE TITLE
az policy assignment list --scope "/subscriptions/xxxx" Failed

### ISSUE THREAD

**Issue by Ben-65535** [Azure/azure-cli#9555]
I'm just trying to understand why this command failed as it returned an unknown error and there doesn't appear to be an issue with the syntax.

I ran this from the Azure CLI from my local CMD window where xxxx is my subscription ID.
az policy assignment list --scope "/subscriptions/xxxx"

I retrieved my subscription ID using the following command.
az account list --output table

## Describe the bug

**Command Name**
`az policy assignment list`

**Errors:**
```
'type'
Traceback (most recent call last):
Temp\pip-install-dsvrkf2x\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 560, in execute
azure\cli\core\commands\__init__.py, ln 618, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 611, in _run_job
Local\Temp\pip-install-dsvrkf2x\six\six.py, ln 693, in reraise
azure\cli\core\commands\__init__.py, ln 588, in _run_job
azure\cli\core\commands\__init__.py, ln 297, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 461, in default_command_handler
azure\cli\command_modules\resource\custom.py, ln 1141, in list_policy_assignment
KeyError: 'type'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az policy assignment list --scope {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.65

```

**Comment by tjprescott** [comment]
I can confirm this bug. We should have a fix in the next release.

**Comment by Ben-65535** [comment]
Thanks for the quick response Travis. Glad to hear this is being addressed.
Best,
Ben
