### ISSUE TITLE
Unable to import images from gcr.io

### ISSUE THREAD

**Issue by stevehedrick** [Azure/azure-cli#9557]
**Describe the bug**
Images imported from gcr.io with broken manifests.  No error message is generated during import, az acr repository show-manifests shows the image manifest, as does the portal.  But any attempt to pull the image, either via a `docker pull` or an `az acr import` to another repository fail with an error message indicating that the manifest is missing.

**To Reproduce**

```
PS > az acr import --source gcr.io/heptio-images/ark:v0.10.0 --name myacr
PS > az acr login --name myacr
Login Succeeded
PS > docker pull myacr.azurecr.io/heptio-images/ark:v0.10.0
Error response from daemon: manifest for myacr.azurecr.io/heptio-images/ark:v0.10.0 not found
```

**Expected behavior**
It is expected that after an `az acr import` of an image that pulling it would result in the image being pulled, and not an error about a missing manifest.

**Environment summary**
Install Method: MSI
CLI version: 2.0.63
OS version: Win10 1809
Shell Type: Powershell 5.1  

**Additional context**
I pulled 25 images using `az acr import`, from the following repository hosts:
* mcr.microsoft.com
* docker.io
* quay.io
* registry.opensource.zalan.do
* grc.io
* k8s.gcr.io

Only the two gcr.io repositories (3 images in total) had this manifest problem.  But they consistently had it.  I do not know if there are issues with other repositories.

**Workaround**
I've been able to work around this by doing:
1. `docker pull gcr.io/heptio-images/ark:v0.10.0`
2. `docker image tag gcr.io/heptio-images/ark:v0.10.0 myacr.azurecr.io/heptio-images/ark:v0.10.0`
3. `az acr login --name myacr`
4. `docker push myacr.azurecr.io/heptio-images/ark:v0.10.0`

**Comment by sajayantony** [comment]
We are able to repo this and will investigate. 
/cc @nathana1

**Comment by sajayantony** [comment]
This being tracked https://github.com/Azure/acr/issues/254

**Comment by nathana1** [comment]
A fix for this has been deployed to all regions.  Please let us know if you see any issues.
