### ISSUE TITLE
Can't connect to AKS by az aks get-credentials

### ISSUE THREAD

**Issue by michaelbpalmer** [Azure/azure-cli#9559]
## Describe the bug

**Command Name**
`az aks get-credentials`

**Errors:**
```
request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/a8c3fdb1-94c2-4db4-bc18-470696fa4bd4/resourceGroups/cp-annotation-api/providers/Microsoft.ContainerService/managedClusters/cp-annotation-api-cluster/listClusterUserCredential?api-version=2019-02-01 (Caused by ResponseError('too many 500 error responses'))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks get-credentials --resource-group {} --name {}`

## Environment Summary
```
Darwin-18.5.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.64 *

```

**Comment by seanmck** [comment]
Closing stale issues. Please reopen if there is a consistent repro.
