### ISSUE TITLE
[Scale set] az vmss nic list doesn't work

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#956]
Throws error:
No registered resource provider found for location 'westus' and API version '2016-06-01' for type 'virtualMachineScaleSets/networkInterfaces'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview'. The supported locations are 'eastus, eastus2, westus, centralus, northcentralus, southcentralus, northeurope, westeurope, eastasia, southeastasia, japaneast, japanwest, australiaeast, australiasoutheast, brazilsouth, southindia, centralindia, westindia, canadacentral, canadaeast, westus2, westcentralus, uksouth, ukwest'.

Likely a service/SDK error since we simply call into the SDK on this one.

**Comment by BurtBiel** [comment]
Filed https://github.com/Azure/azure-sdk-for-python/issues/798

**Comment by johanste** [comment]
This is https://github.com/Azure/azure-rest-api-specs/issues/570.

**Comment by johanste** [comment]
We should be able to (temporarily) override this behavior by explicitly setting the API version on the compute client for this call...
