### ISSUE TITLE
'management-policy' is not in the 'az storage account' command group

### ISSUE THREAD

**Issue by sawyerh** [Azure/azure-cli#9566]
In the azure-cli (v2.0.64) for Mac, "az storage account management-policy" is not a valid command group and results in the following error:

az storage account: 'management-policy' is not in the 'az storage account' command group. See 'az storage account --help'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f84b325-33af-86ab-749e-faec2e01a1f3
* Version Independent ID: 87036460-df59-9239-680d-29c68a0490bb
* Content: [az storage account management-policy](https://docs.microsoft.com/en-us/cli/azure/storage/account/management-policy?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
@limingu please take a look. This may be an OSX packaging bug, but right now I can't brew install azure-cli at all to be able to repro this. cc/ @marstr

**Comment by limingu** [comment]
azure-cli (v2.0.64)  won't have the 'management-policy' command. Please install the newest azure-cli version v2.0.65/v.2.0.66.

**Comment by tjprescott** [comment]
@limingu I didn't see any release notes in storage for these commands. We should definitely update the history accordingly.

**Comment by sawyerh** [comment]
Thanks. At the time when I created this issue, `v2.0.64` was the latest version available for Mac using `brew`. I've since been able to update and now see the `management-policy` command.
