### ISSUE TITLE
az webapp create returns Error : There was a conflict. AlwaysOn cannot be set for this site as the plan does not allow it.

### ISSUE THREAD

**Issue by ChNorman** [Azure/azure-cli#9567]
**Describe the bug**
when you create an ASP on Shared SKU and then create a web app on that ASP it tries to enable AlwaysOn. Returns Error : There was a conflict. AlwaysOn cannot be set for this site as the plan does not allow it.

**To Reproduce**
1.	install AZ CLI  2.0.66
2.	az group create -l wewstus -n MyTestRG
3.	az appservice plan create --name "MyDemoASP" --resource-group MyTestRG --location westus --sku SHARED
4.	az webapp create -g MyTestRG -p MyDemoASP -n MyDemoApp

**Expected behavior**
create the webapp and not enable AlwaysOn

**Environment summary**
MSI install of latest version 2.0.66
Windows 10 
![image](https://user-images.githubusercontent.com/11824459/58917401-0709d700-86ec-11e9-90b6-b69f599620b0.png)
PowerShell Core 6.0

**Additional context**
This appears to happen with any version greater than 2.0.61

**Comment by panchagnula** [comment]
@chNorman thanks for reporting this. Shared SKU doesn't support Always ON & is a regression on our end. For not you can create an app with a different SKU & Scale Out to Shared. Sorry for the inconvinience.

**Comment by yugangw-msft** [comment]
https://github.com/Azure/azure-cli/pull/9323 fixes this
