### ISSUE TITLE
updating nic ip-config results in error

### ISSUE THREAD

**Issue by vanraz79** [Azure/azure-cli#9569]
## Describe the bug

**Command Name**
`az network nic ip-config update`

**Errors:**
```
pop from empty list
Traceback (most recent call last):
Temp\pip-install-ygnynjtx\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 560, in execute
azure\cli\core\commands\__init__.py, ln 618, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 611, in _run_job
Local\Temp\pip-install-ygnynjtx\six\six.py, ln 693, in reraise
azure\cli\core\commands\__init__.py, ln 588, in _run_job
azure\cli\core\commands\__init__.py, ln 297, in __call__
azure\cli\core\commands\arm.py, ln 523, in handler
azure\cli\core\commands\arm.py, ln 804, in set_properties
azure\cli\core\commands\arm.py, ln 966, in _get_name_path
IndexError: pop from empty list
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network nic ip-config update --nic-name {} --ids {} --set {} {} {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.66

```

**Comment by tjprescott** [comment]
What are the inputs you are actually using (redacted in the initial report)? I see a usage error in that you should not be specifying `--ids` and `--nic-name`. What are you trying to set?
