### ISSUE TITLE
`az webapp up` redeploy fails for S1 tier

### ISSUE THREAD

**Issue by nickwalkmsft** [Azure/azure-cli#9573]
**Describe the bug**
Using `az webapp up` to create a new app with `--sku S1` then subsequently using `az webapp up` with no parameters to redeploy fails to detect the existing App Service plan and fails with `Cannot update the site 'MyUniqueAppName' because it uses AlwaysOn feature which is not allowed in the target compute mode`.

**To Reproduce**
```
az webapp up --name MyUniqueAppName --sku S1
az webapp up
```

**Expected behavior**
Second invocation succeeds and redeploys.

**Environment summary**
Azure Cloud Shell as of 6/5 (azure-cli: 2.0.66; appservice: 0.2.20)

**Additional context**
Does not repro for free tier (no `--sku` supplied on initial invocation). Not sure if it fails for other tiers.

**Comment by yugangw-msft** [comment]
https://github.com/Azure/azure-cli/pull/9323 fixes this
