### ISSUE TITLE
az batch commands fails asking for account credentials even when logged in

### ISSUE THREAD

**Issue by devaradhanm** [Azure/azure-cli#9577]
**Describe the bug**
This seems to be a regression. I suspect this is caused by this commit https://github.com/Azure/azure-cli/commit/c234eace46488506c5db82f58c2af09d6606fe2c

**To Reproduce**
az batch login --name <name> --resource-group <group name>
az batch pool list

**Expected behavior**
Should return pools details for the logged in batch account.

**Actual behavior**
usage: az batch pool list [-h] [--verbose] [--debug]
                          [--output {json,jsonc,table,tsv,yaml,none}]
                          [--query JMESPATH] [--filter FILTER]
                          [--select SELECT] [--expand EXPAND]
                          [--account-name ACCOUNT_NAME]
                          [--account-key ACCOUNT_KEY]
                          [--account-endpoint ACCOUNT_ENDPOINT]
                          [--subscription _SUBSCRIPTION]
az batch pool list: error: usage error: --account-name NAME --account-key KEY --account-endpoint ENDPOINT

**Comment by jotsif** [comment]
Yes, this happens to me as well since 4.0.2

**Comment by devaradhanm** [comment]
Is there any update on this? Azure devps Azure CLI task is using 2.0.66 which has this issue as well. It is blocking our release pipeline.
