### ISSUE TITLE
Bad documentation bug in az acr repository delete

### ISSUE THREAD

**Issue by elibarzilay** [Azure/azure-cli#9579]
When I run `az acr repository delete -h`, the help text has this at the
top:

    az acr repository delete : Delete a repository or image in an Azure
    Container Registry.
        This command deletes all associated layer data that are not
        referenced by any other manifest in the container registry.

This made me think that removing a specific tag with the delete command
will not affect any other tags -- but turns out that this is wrong, and
all tags that refer to the same manifest get nuked as well...  I'm
assuming that this is the intended behavior, since running a plain
delete without `-y` does indeed list all of the tags that will be
removed too -- and therefore I consider this a documentation bug.

There are four parts that should be fixed:

1. That top blurb should *really* be fixed to say that it ***does***
   delete all other tags in the same repository that refer to the same
   manifest.

2. I now see that the last example at the bottom of the help text says
   what the expected behavior is too -- but it's at the bottom, so it
   could use some highlighting, maybe make "and all tags" be in all
   caps.

3. Having `-y` is helpful, but it is often used to dismiss plain
   warnings.  That was my original assumption so I used `-y` and didn't
   see the tag listing that you get without `-y`...  It would be much
   better if that list of deleted tags would be shown even if you used
   -y.

4. Finally, I think that it's kind of strange that there is nothing that
   is similar to `docker rmi`, which deletes a tag and only if there are
   no other references to the image, it will delete it too.  The ACR
   `delete` command is of course much too strong in what it deletes, and
   `unlink` is on the other hand too weak since it doesn't remove the
   manifest when it's left with no references.

   This means that to do the `docker rmi` behavior, I must implement my
   own logic that uses `untag` or `delete` depending on whether there are
   additional references to the same sha256...  It would be REALLY helpful
   if such a CLI command existed (and shouldn't be too hard...).

**Comment by northtyphoon** [comment]
@ElianaLiberman can you take a look?

**Comment by ElianaLiberman** [comment]
@SteveLasker What text would you recommend for me to add in the beginning (in addition to changing to capital letters "AND ALL TAGS"?

If it helps this is the PR: https://github.com/Azure/azure-cli/pull/9654

**Comment by ElianaLiberman** [comment]
Not fixing issue number 4.

**Comment by elibarzilay** [comment]
@ElianaLiberman, FWIW, I implemented that functionality in a simple way: just list all tags with their sha256, and if the tag-to-be-deleted's sha256 is unique, delete it.

Since this is what `docker rmi` does, I suspect that this is a very expected+desired behavior, so I'm surprised at not implementing it...

(Alternatively, just wait some time for people to shoot their feet, either by losing images like I did, or more likely by going over their quota by always untagging and accumulating old images -- and then implement it...?)

**Comment by SteveLasker** [comment]
Hi Eli,
Thanks for the feedback. It's hard to get the right level of detail in CLI docs, particuarly for a complex topic of images, tags, manifest, and shared layers. We are working to provide more detail in the complete docs: https://github.com/MicrosoftDocs/azure-docs-pr/pull/79861

For the CLI docs, lets re-order the examples, with a bit of clarity to help identify the manifest deletion, indexed by tag:

    Delete an image manifest by tag. This deletes the manifest referenced by 'hello-world:latest' and all
    other tags referencing the same manifest.
        az acr repository delete -n MyRegistry --image hello-world:latest

    Delete an image manifest by sha256-based manifest digest. This deletes the manifest identified by 'hello-world@sha256:abc123' and all tags referencing the same manifest.
        az acr repository delete -n MyRegistry --image hello-world@sha256:abc123

    Delete a repository from an Azure Container Registry. This deletes all manifests and tags under
    'hello-world'.
        az acr repository delete -n MyRegistry --repository hello-world

**Comment by elibarzilay** [comment]
Thanks!

**Comment by ElianaLiberman** [comment]
> Hi Eli,
> Thanks for the feedback. It's hard to get the right level of detail in CLI docs, particuarly for a complex topic of images, tags, manifest, and shared layers. We are working to provide more detail in the complete docs: MicrosoftDocs/azure-docs-pr#79861
> For the CLI docs, lets re-order the examples, with a bit of clarity to help identify the manifest deletion, indexed by tag:
> Delete an image manifest by tag. This deletes the manifest referenced by 'hello-world:latest' and all
> other tags referencing the same manifest.
>     az acr repository delete -n MyRegistry --image hello-world:latest
> 
> Delete an image manifest by sha256-based manifest digest. This deletes the manifest identified by 'hello-world@sha256:abc123' and all tags referencing the same manifest.
>     az acr repository delete -n MyRegistry --image hello-world@sha256:abc123
> 
> Delete a repository from an Azure Container Registry. This deletes all manifests and tags under
> 'hello-world'.
>     az acr repository delete -n MyRegistry --repository hello-world

Done here! https://github.com/Azure/azure-cli/pull/9738
