### ISSUE TITLE
No parameters when invoking shell script from file with #! at the beginning

### ISSUE THREAD

**Issue by kkoyot** [Azure/azure-cli#9596]
When launching shell script via
`az vm run-command invoke --command-id RunShellScript --script '@foo.sh' --parameters="Param1"`
I get two different results when I insert #!/bin/bash at the beginning of foo.sh.

foo.sh:
```
#!/bin/bash
printenv
```
Result:
```
[stdout]
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
PWD=/var/lib/waagent/run-command/download/2
LANG=en_US.UTF-8
SHLVL=4
_=/usr/bin/printenv

[stderr]
```
Second version:
foo.sh:
```
printenv
```
Result:
```
Enable succeeded: 
[stdout]
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
PWD=/var/lib/waagent/run-command/download/3
LANG=en_US.UTF-8
arg1=Param1
SHLVL=4
_=/usr/bin/printenv

[stderr]
```
In short: all arguments passed via --parameter option in azure-cli disappear. Please advise

No target date

**Comment by yonzhan** [comment]
@qwordy add to next Sprint.

**Comment by qwordy** [comment]
Thank you for finding this problem. Similar to this issue https://github.com/Azure/azure-cli/issues/10400. We are still investigating it.

**Comment by qwordy** [comment]
Could you check the new line character? Use a Linux style \n.

**Comment by yonzhan** [comment]
@kkoyot  Did you check what @qwordy  suggested?

**Comment by qwordy** [comment]
The request body:
```
{"commandId": "RunShellScript", "script": ["#!/bin/bash\r\nprintenv"], "parameters": [{"name": "arg1", "value": "Param1"}]}
```
No "param1" in ENV.

If I use
```
az vm run-command invoke -g rg -n vm --command-id RunShellScript --scripts '#!/bin/bash' 'printenv' --parameters 'Param1'
```
request body is
```
{"commandId": "RunShellScript", "script": ["#!/bin/bash", "printenv"], "parameters": [{"name": "arg1", "value": "Param1"}]}
```
I can get the correct result.
@koralski Can you help with this issue?

**Comment by qwordy** [comment]
Duplicate issue with #10400, where there are more comments. We will update status of this problem in that issue. Close this issue.
