### ISSUE TITLE
az acre login --name <docker-reg-name> fails

### ISSUE THREAD

**Issue by maguirpd** [Azure/azure-cli#9598]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
when I run the following command via an SSH session:
```
az acr login --name <docker-reg-name>
```
get the following error:
```
Error saving credentials: error storing credentials - err: exit status 1, out: 'user interaction not allowed'
```
However, when I physically log into my Mac-mini to run the command it works! 

**To Reproduce**
1. setup azure-cli and docker on a Mac-mini 
2. try ssh'ing into Mac-mini and run the above command..
 
**Expected Behaviour**
I expect instead of an error message to see a message "Login succeeded"

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  
OS: Mojava 10.14.5
using bash shell

az --version
azure-cli                         2.0.66

acr                                2.2.8
acs                                2.4.3
advisor                            2.0.0
ams                                0.4.6
appservice                        0.2.20
backup                             1.2.4
batch                              4.0.2
batchai                            0.4.9
billing                            0.2.1
botservice                         0.2.1
cdn                                0.2.3
cloud                              2.1.1
cognitiveservices                  0.2.5
command-modules-nspkg               2.0.2
configure                         2.0.23
consumption                        0.4.3
container                         0.3.17
core                              2.0.66
cosmosdb                          0.2.10
deploymentmanager                  0.1.0
dla                                0.2.5
dls                                0.1.9
dms                                0.1.3
eventgrid                          0.2.3
eventhubs                          0.3.6
extension                          0.2.5
feedback                           2.2.1
find                               0.3.3
hdinsight                          0.3.4
interactive                        0.4.4
iot                               0.3.10
iotcentral                         0.1.6
keyvault                          2.2.15
kusto                              0.2.2
lab                                0.1.7
maps                               0.3.4
monitor                           0.2.14
natgateway                         0.1.0
network                            2.5.1
nspkg                              3.0.3
policyinsights                     0.1.3
privatedns                         1.0.1
profile                            2.1.5
rdbms                             0.3.11
redis                              0.4.3
relay                              0.1.4
reservations                       0.4.2
resource                          2.1.15
role                               2.6.3
search                             0.1.1
security                           0.1.1
servicebus                         0.3.5
servicefabric                     0.1.19
signalr                            1.0.0
sql                                2.2.4
sqlvm                              0.1.1
storage                            2.4.2
telemetry                          1.0.2
vm                                2.2.22

Python location '/usr/local/Cellar/azure-cli/2.0.66/libexec/bin/python'
Extensions directory '/Users/jenkins/.azure/cliextensions'

Python (Darwin) 3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Additional context**

**### IN FUTURE - PLEASE ALLOW USERS TO DOWNLOAD PREVIOUS VERSION OF AZURE-CLI INSTEAD OF AN ALL OR NOTHING RELEASE ###**

**Comment by SriniBanala** [comment]
@tjprescott Please assign this to @hkuadithya. Thanks.

**Comment by hkuadithya** [comment]
@maguirpd  Could you please run `az acr check-health` and post the logs here. Thanks.

**Comment by hkuadithya** [comment]
@sajayantony this issue has been open for more than a couple of months now. I suggested @maguirpd to run `check-health` but he hasn't responded so far.

Do you think we should wait for his response or close this issue? 
We could request him to reopen this issue if the problem persists.

**Comment by yonzhan** [comment]
Close this issue since no response for months. Please create a new issue for further question.

**Comment by nomaed** [comment]
I have the same issue when I am calling the command through SSH.

`check-health` yields:

```
> az acr check-health
Docker daemon status: available
Docker version: 'Docker version 20.10.8, build 75249d8, platform linux/amd64'
This will pull the image mcr.microsoft.com/mcr/hello-world:latest. Proceed? (y/n): y
Docker pull of 'mcr.microsoft.com/mcr/hello-world:latest' : OK
Azure CLI version: 2.27.2
Registry name must be provided to check connectivity.
Helm version: 3.5.2
An error occurred: NOTARY_COMMAND_ERROR
Please verify if notary is installed.
```

**Comment by danikgan** [comment]
Any update on this issue? Having exactly the same problem.

**Comment by vgaticah** [comment]
You have to install notary v0.6.0
You can download it from https://github.com/notaryproject/notary/releases/tag/v0.6.0 

> I have the same issue.
> 
> ```
> ❯ az acr check-health --ignore-errors
> Docker daemon status: available
> Docker version: 'Docker version 20.10.11, build 847da184ad5048b27f5bdf9d53d070f731b43180, platform linux/arm64'
> This will pull the image mcr.microsoft.com/mcr/hello-world:latest. Proceed? (y/n): y
> Docker pull of 'mcr.microsoft.com/mcr/hello-world:latest' : OK
> Azure CLI version: 2.32.0
> DNS lookup to ***.azurecr.io at IP 52.168.114.5 : OK
> Challenge endpoint https://***.azurecr.io/v2/ : OK
> Fetch refresh token for registry '***.azurecr.io' : OK
> Fetch access token for registry '***.azurecr.io' : OK
> Helm version: 3.7.2
> An error occurred: NOTARY_COMMAND_ERROR
> Please verify if notary is installed.
> 
> Please refer to https://aka.ms/acr/health-check for more information.
> ```
