### ISSUE TITLE
Misbehaving pattern option in azure storage blob download-batch command when there is a local directory with the same name as that of the blob being used in command

### ISSUE THREAD

**Issue by raviteja22** [Azure/azure-cli#9599]
**Describe the bug**
I have a blob in the container. I have a local directory which has the same name. When I run download-batch command with pattern option as "blob_name/*", it is expanding the command options with the files in the local directory and failing.

**To Reproduce**
Create a directory locally test_pattern with multiple files file1 and file2 in it. 
Upload a blob with the same name test_pattern.
Then try to download using the following command with pattern option from the path where local directory exists. 
`az storage blob download-batch -d . --pattern test_pattern/* -s  <container>`

**Error:**
cli.azure.cli.core.parser : az: error: unrecognized arguments: test_pattern/file2
az: error: unrecognized arguments: test_pattern/file2

**Debug message:**
Command arguments: ['storage', 'blob', 'download-batch', '-d', '.', '--pattern', ' test_pattern/file1', ' test_pattern/file2', '-s', 'mlebarstoragecontainer', '--debug']

**Expected behavior**
It should not care about the local directory, it should just find a blob with the given name in the container and download locally or throw a proper warning/error.

**Environment summary**

Install Method: pip
CLI version:
 azure-cli:      2.0.60 *
 storage:        2.4.2
OS version:    Ubuntu Docker Container 
Shell Type:  bash

**Comment by limingu** [comment]
@raviteja22 , as the debug message: ['storage', 'blob', 'download-batch', '-d', '.', '--pattern', ' test_pattern/file1', ' test_pattern/file2', '-s', 'mlebarstoragecontainer', '--debug']

Your command is not right. You can only set one parameter for --pattern.
For example, these commands will work.
az storage blob download-batch -d . --pattern test_pattern/file1 -s mlebarstoragecontainer
az storage blob download-batch -d . --pattern test_pattern/file2 -s mlebarstoragecontainer
az storage blob download-batch -d . --pattern test_pattern/* -s mlebarstoragecontainer

**Comment by raviteja22** [comment]
As you can see in my "To reproduce" details, I have used the valid command only.
`az storage blob download-batch -d . --pattern test_pattern/* -s mlebarstoragecontainer` 

The third command that you mentioned was the exact command I used.

The following was the debug log which shows that the command is expanding the local directory and adding extra parameters with file1 and file2.

Basically, this issues occurs when the blob name and the local directory name from where you run the az command are same.

**Command used**: 
**`az storage blob download-batch -d . --pattern test_pattern/* -s mlebarstoragecontainer`*

**Bebug Log:**
the debug message: ['storage', 'blob', 'download-batch', '-d', '.', '--pattern', ' test_pattern/file1', ' test_pattern/file2', '-s', 'mlebarstoragecontainer', '--debug']

**Comment by jimmy-dg** [comment]
@limingu I think this is a valid bug, I'm able to reproduce this with v2.0.70, with the exact same behaviour @raviteja22 described in the above comment.

> Basically, this issues occurs when the blob name and the local directory name from where you run the az command are same.

If I move the files to a sub directory and run batch upload, the error goes away and works fine.

**Comment by raviteja22** [comment]
Thanks, @jimmy-dg for verifying the issue.

Can this bug be reopened if not already got fixed?

**Comment by Juliehzl** [comment]
@raviteja22 Feel free to reopen it if not fixed.

**Comment by Juliehzl** [comment]
Reopen it for my triage later

**Comment by mlathara** [comment]
I had the same issue. @raviteja22 was on the right track that the issue is bash expands the glob pattern and passes that on to az cli -- but the issue doesn't have anything to do with blob/directory names. AZ CLI expects to see the glob pattern, but only see the expanded filenames that fit the pattern instead. Adding a backslash before the glob (maybe quotes would work as well?) fixes the problem. Something like:

```
az storage blob download-batch -d . --pattern test_pattern/\* -s mlebarstoragecontainer
```

**Comment by tylerjgarland** [comment]
> I had the same issue. @raviteja22 was on the right track that the issue is bash expands the glob pattern and passes that on to az cli -- but the issue doesn't have anything to do with blob/directory names. AZ CLI expects to see the glob pattern, but only see the expanded filenames that fit the pattern instead. Adding a backslash before the glob (maybe quotes would work as well?) fixes the problem. Something like:
> 
> ```
> az storage blob download-batch -d . --pattern test_pattern/\* -s mlebarstoragecontainer
> ```

Thanks, you helped me solve my issue.
