### ISSUE TITLE
Add ability to supply runbook receiver parameters through az monitor action-group

### ISSUE THREAD

**Issue by aullom1** [Azure/azure-cli#9605]
Currently, we can add an automation runbook receiver to an existing action group with something like this.

```
az monitor action-group update --ids "$ActionGroupId" `
	--add automationRunbookReceivers `
	automationAccountId="/subscriptions/$RunbookSubscriptionId/resourceGroups/$RunbookResourceGroupName/providers/Microsoft.Automation/automationAccounts/$AutomationAccountName" `
	isGlobalRunbook=false `
	name="$ReceiverName" `
	runbookName=CherwellIncident-v1 `
	serviceUri=$ServiceUri `
	useCommonAlertSchema=true `
	webhookResourceId="/subscriptions/$RunbookSubscriptionId/resourceGroups/$RunbookResourceGroupName/providers/Microsoft.Automation/automationAccounts/$AutomationAccountName/webhooks/$WebhookName"
```

However, there is no way to set the parameters to the runbook except through the UI.

I would like to be able to add parameters to the runbook by appending something like this to the above cli call.

```
parameters="{`"title`":`"Llama fact`",`"body`":`"Llamas communicate with their tails, ears and sounds.  Humming is a common sound llamas make.`"}"
```

I have considered creating a webhook that is pre-configured with the desired parameters/values, but this is not ideal for anything more than initial testing.  It would be possible to create the webhooks through automation, but that would require the use of something other than the Azure CLI (not supported at this time).

**Comment by mukeshinit** [comment]
You can create Webhook URI using Rest API and pass the serviceUri to into action group 
**Note**: Each run book needs separate web hook so create new one using rest api call. 

Reference link : https://docs.microsoft.com/en-us/rest/api/automation/webhook/generateuri

**Comment by yonzhan** [comment]
add to S164.

**Comment by yonzhan** [comment]
add to S170

**Comment by ankur198** [comment]
Any updates?

**Comment by kairu-ms** [comment]
Currently the update API not support receiver parameters.

**Comment by G0PINATH-WW** [comment]
I ran into this issue with Terraform and it seems that this needs to be at the webhook and as a property in the action group.
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/automation_webhook
So you create the webhook and bind it to a hybrid worker group, and when creating the action group, use this webhook.

**Comment by navba-MSFT** [comment]
@aullom1 Apologies for the delayed response. We are looking into this issue. We will update this thread once we have more details on this. 

@sameergMS @jsntcy Could you please provide an update on this github request once you get a chance ? Awaiting your reply.

**Comment by G0PINATH-WW** [comment]
Just to clarify, this is available in terraform already. An example that worked for  me.

resource "azurerm_monitor_action_group" "start_domainjoin_automation_workbook" {
  name                = "start-domainjoin-automation-workbook"
  resource_group_name = var.pipeline_shared_storage_rg_name
  short_name          = "start-aa-job"

  webhook_receiver {
    name                    = "start-domainjoin-automation-workbook-corpprod"
    service_uri             = azurerm_automation_webhook.DomainJoinStorageAccountForAzureFiles.uri
    use_common_alert_schema = true
  }

  depends_on = [
    azurerm_automation_webhook.DomainJoinStorageAccountForAzureFiles
  ]
}


resource "azurerm_automation_webhook" "DomainJoinStorageAccountForAzureFiles" {
  name                    = "DomainJoinStorageAccountForAzureFiles_Webhook"
  resource_group_name     = "REPLACERGNAME"
  automation_account_name = "REPLACEAANAME"
  expiry_time             = timeadd(var.webhook_expiry_start, var.webhook_endtime_duration)
  enabled                 = true
  runbook_name            = "DomainJoinStorageAccountForAzureFiles"
  run_on_worker_group     = var.run_on_worker_group
  parameters = {
    operationmode = "AzureMonitorTriggered"
  }

  depends_on = [module.azure_automation]

}

**Comment by navba-MSFT** [comment]
@G0PINATH-WW Thanks for sharing this. 
@aullom1 Could you please test tis and let us know if that serves your requirement ? Awaiting your reply.

**Comment by aullom1** [comment]
Sorry, I'm not even using the runbook any more.  It was so long ago I can't even remember what I was trying to accomlish.
