### ISSUE TITLE
[Discussion] Provide ls/rm command aliases 

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#961]
This is highly subjective, but I feel like it would be a little more "ergonomic", and potentially more idiomatic for some users, to be able to use `ls` and `rm` commands--within the applicable command groups--as opposed to `list` and `delete`. I find myself naturally attempting to type either `ls` or `rm` many times (e.g. `az resource group ls`), due to the muscle memory I've built-up from other CLIs, so I can imagine that providing this kind of "interopable" interface could help some users more easily integrate AZ into their regular workflow. I wouldn't recommend changing what's already there, but I'm curious whether it wouldn't be valuable to provide aliases for some of the core commands, that have pseudo-established naming conventions for some users.

Apologies if this discussion has already been had. I couldn't find an issue when I did a search, so I figured I would just file a quick issue while I was thinking about it.

**Comment by johanste** [comment]
This is very much a relevant discussion to have with our users. 

The team has gone back and forth on this subject. At one point, we had a prototype that used exactly rm and ls as the names for the delete and list commands respectively. We got mixed feedback from internal use. But that was from a very limited set of users. 

One alternative discussed has also been to selectively adopting the rm/ls command names only for the storage command and make them look & feel more like "vanilla" local file operations. 

Any additional feedback/suggestions are more than welcome!

**Comment by lostintangent** [comment]
I can definitely appreciate the mixed feedback. I wonder whether simply aliasing the existing commands wouldn't work well for everyone, and could piggy-back off a fairly established naming convention. For example, both the NPM and Docker CLI provide this functionality for listing commands (e.g. `npm ls` or `npm list`, `docker network ls` or `docker network list`). `rm` is a little different, since I feel like the "long name" that CLIs tend to support is "remove" instead of "delete" (e.g. `docker network rm` or `docker network remove`), but at least there is precedent for supporting shorthand command names, and `ls/list` and `rm` are pretty ubiquitous.

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
