### ISSUE TITLE
Piping blob lists or reading from source file for az storage blob operations

### ISSUE THREAD

**Issue by nofunatall** [Azure/azure-cli#9613]
Is it possible to pipe through a list of blob files or read a list source file for blob operations?

Example:
I have a large amount of blobs to cleanup that are stored using UUID naming - the list of files that needs deleting is generated from our SQL.
I have a script that can delete those files line by line using xargs but it's extremely slow given that the list can be in the 100,000s or even 1,000,000s.

az storage blob delete-batch seems to only be able to do operations based on container names, regex matching, time match etc and I see no way to have it run against a pre-generated list of files.

**Comment by nofunatall** [comment]
Any answers?

**Comment by limingu** [comment]
@nofunatall, you can create a script that goes through the list of the files and call 'az storage blob delete' to delete each file.

**Comment by nofunatall** [comment]
A single operation takes a few seconds.

As mentioned I already have a script using xargs which is essentially the same as a For loop going over a file.

If I have over 1,000,000 files that need deleting it will take days.

Is there no better way to do bulk operations rather then one by one?

**Comment by limingu** [comment]
'--output none' won't skip waiting for the Azure response.

One thing you can try is 'az storage blob sync' command. Another is try to use azcopy. The storage-preview has azcopy to remove blobs.

**Comment by Juliehzl** [comment]
@nofunatall We have released a new command ```az storage remove``` in v2.0.70. You can use this command to delete files more effectively.
