### ISSUE TITLE
[SignalR] SignalR lacks CLI conventions

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#9623]
Tracking issue since SignalR is considered GA.  This module lacks the following CLI conventions/features:

- [ ] missing generic update `az signalr update`
- [ ] `az signalr show/delete`: missing `--ids` convention.
- [ ] `az signalr key` command group should be `az signalr keys` command group for consistency.

**Comment by yonzhan** [comment]
SignalR

**Comment by chenkennt** [comment]
@zackliu please help take a look

**Comment by zackliu** [comment]
I will follow the issue.

**Comment by zackliu** [comment]
For generic update and `ids` for `az signalr show/delete` have been fixed. And `key` is used for years and we don't want to introduce breaking changes
