### ISSUE TITLE
AZ Login seems to stop working on Linux hosts

### ISSUE THREAD

**Issue by element-of-surprise** [Azure/azure-cli#9625]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
Get Device Code request returned http error: 400 and server response: {"error":"invalid_request","error_description":"AADSTS220050: The specified encryption key version override 31 was not found in the list of keys.\r\nTrace ID: 1dc9b7c7-c123-4ad1-9c01-d3a2a0287d01\r\nCorrelation ID: 810b74f5-e81c-4110-80f7-4f34aa92a2f5\r\nTimestamp: 2019-06-10 22:11:16Z","error_codes":[220050],"timestamp":"2019-06-10 22:11:16Z","trace_id":"1dc9b7c7-c123-4ad1-9c01-d3a2a0287d01","correlation_id":"810b74f5-e81c-4110-80f7-4f34aa92a2f5"}
```

## To Reproduce:
- `az login`

## Expected Behavior
Directed to a web url in order to authenticate.

## Environment Summary
```
Linux-4.18.0-1014-azure-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.66
```
## Additional Context
Also is broken on another Linux box running an older version.  I also updated this to a new version today to see if that would fix it.  Works fine under OSX, so it appears to only affect my Linux version and isn't related directly to an account.

**Comment by marstr** [comment]
Howdy @element-of-surprise! Good to see a Gopher over here in the CLI world. :)

Could you tell me more about how you're installing the CLI? In general we don't have a repository for `buster` yet. Though, getting bug reports back from sid is always valuable so that we know if there's something coming around the corner.

![sid](https://media.giphy.com/media/doCsLMiHvGTmg/giphy.gif)

**Comment by marstr** [comment]
I did just test in a debian:stretch container, and there everything seems okay. Also for general Linux testing via my Fedora 29 machine, all seems well.

**Comment by marstr** [comment]
We chatted offline, and it sounds like this is transient. Guessing it's backend related.
