### ISSUE TITLE
About the OpenShift in Azure

### ISSUE THREAD

**Issue by christinewong2019** [Azure/azure-cli#9628]
![image](https://user-images.githubusercontent.com/48715450/59242273-809a4b80-8c3d-11e9-9c7b-69d30349cd0a.png)
I following this document https://docs.microsoft.com/en-us/azure/virtual-machines/linux/openshift-prerequisites, but I try to run this command get the wrong message
the result:

![image](https://user-images.githubusercontent.com/48715450/59242397-f56d8580-8c3d-11e9-80bd-0e1885cfcc8f.png)

I don't know how to fix this problem, please give some help

**Comment by yugangw-msft** [comment]
if you type `echo $scope` which do you get?

**Comment by yugangw-msft** [comment]
We are closing it as we don't have enough information to diagnose the root cause. Please reactivate with more data.
