### ISSUE TITLE
webapp:azure-cli 2.0.66 cryptography <2.5 and >2.5

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-cli#9629]
azure-cli 2.0.66 [from pypi](https://pypi.org/project/azure-cli/) requires cryptography `<2.5` and `>=2.5`. 😢 

azure-cli-core is requiring `>=2.5` becauseof paramiko:
```
    - azure-cli-core [required: Any, installed: 2.0.66]
      - paramiko [required: >=2.0.8, installed: 2.5.0]
        - cryptography [required: >=2.5, installed: 2.4.2]
```

It is azure-cli-appservice that is putting a dependency on `<2.5` [here](https://github.com/Azure/azure-cli/blob/891d259dd9e98698cf3d396261cfad149abcec2b/src/command_modules/azure-cli-appservice/setup.py#L43) and should probably be fixed.
```
  - azure-cli-appservice [required: ==0.2.20, installed: 0.2.20]
    - cryptography [required: <2.5, installed: 2.4.2]
```

I ran into this bug and diagnosed it with [pipenv](https://docs.pipenv.org/en/latest/).

**Comment by tjprescott** [comment]
Hi @ctaggart this has been fixed as part of https://github.com/Azure/azure-cli/pull/9612

**Comment by tjprescott** [comment]
@panchagnula is there a reason that `azure-cli-appservice` required cryptography < 2.5?

**Comment by tjprescott** [comment]
Leaving open for @marstr to weigh in on.

**Comment by ctaggart** [comment]
It looks like [the change](https://github.com/Azure/azure-cli/pull/8324#discussion_r251573381) was done to suppress some warning at the time. With the updated version of paramiko, I doubt this is needed anymore. @patricklee2 @yugangw-msft

**Comment by panchagnula** [comment]
@patricklee2 - assigning this to you to weigh in on this & make the update if needed. //CC: @rramachand21

**Comment by marstr** [comment]
Looks to me like `paramiko` and `cryptography` are playing nice now. I believe the appropriate fix is to remove the ceiling from the appservice package. Whatever changes are made, I'll make sure it gets applied to the [`flatten`](https://github.com/Azure/azure-cli/tree/flatten) branch as well.

**Comment by patricklee2** [comment]
I'll make the fix
