### ISSUE TITLE
Unable to create a VMSS in single-placement-group larger than 100 nodes

### ISSUE THREAD

**Issue by edwardsp** [Azure/azure-cli#9630]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
I am trying to create a VMSS larger than 100 instances with RDMA (all H series node types).  This is possible using the `az vmss scale` but a hard-coded limit stops this with `az vmss create`.

**To Reproduce**
Create a VMSS with `--single-placement-group true` and `--instance-count` greater than 100. 
 The error is:

    ERROR: usage error: '--single-placement-group' should be turned off for zonal scale-sets or with 100+ instances

We require a single placement group for the H series node types to all be on the same IB network.

**Expected behavior**
The VMSS should be created (the limit is now 300 AFAIK).

**Environment summary**
Just az cli.

**Additional context**
Here is the hardcoded limit in the code:
    https://github.com/Azure/azure-cli/blob/3bdff7e063121af9c5528c2689413cbf6d213886/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py#L1096

**Comment by adewaleo** [comment]
I'll do this today
