### ISSUE TITLE
Unable to enter CLI commands after envr. variable update

### ISSUE THREAD

**Issue by kchuying** [Azure/azure-cli#9646]
Hi, 

I am not able to enter any CLI commands to restart my computer node after changing the system variable (path). Any idea what went wrong?

The error is: 'az: error: argument _command_package: invalid choice: ml'

I prefer not to reinstall the entire ML package, so please comment if you have faced the same issue before. Thanks in advance!

**Comment by tjprescott** [comment]
Does it work if you revert the change to your path?

**Comment by kchuying** [comment]
No, the same error persists after rebooting the server.

**Comment by tjprescott** [comment]
You will likely need to search your machine for the az executable or, failing that, reinstall.

**Comment by kchuying** [comment]
Seems like the error was fixed after adding the ML extension back. 

`az extension add -n azure-cli-ml`

Anyway, thanks for your advise.. @tjprescott
