### ISSUE TITLE
storage account network-rule regression

### ISSUE THREAD

**Issue by mooninite** [Azure/azure-cli#9647]
**Describe the bug**
Sometime in the past month the **az storage account network-rule add** functionality has broken. It only returns:
`Values for request parameters are invalid: networkAcls.virtualNetworkRules[].`

**To Reproduce**

    $ az storage account network-rule add --account-name $ACCOUNT --vnet-name $VNET --subnet $SUBNET_NAME --resource-group $RG --subscription '$SUB'
    Values for request parameters are invalid: networkAcls.virtualNetworkRules[].

or

    $ az storage account network-rule add --account-name $ACCOUNT --subnet $SUBNET_ID --resource-group $RG --subscription '$SUB'
    Values for request parameters are invalid: networkAcls.virtualNetworkRules[].

**Expected behavior**
Network rule added.

**Environment summary**
RHEL 7 host installed via yum
Host was originally running 2.0.58, but I upgraded to 2.0.66 and the result is the same.

**Additional context**

**Comment by Juliehzl** [comment]
@mooninite  Can you show me more details using ```az storage account network-rule add --account-name $ACCOUNT --vnet-name $VNET --subnet $SUBNET_NAME --resource-group $RG --subscription '$SUB' --debug``` ?

**Comment by mooninite** [comment]
I no longer have access to the Azure account in question. I forwarded this request to the people who do. Thanks.

**Comment by Juliehzl** [comment]
@mooninite
