### ISSUE TITLE
aks create is invalid

### ISSUE THREAD

**Issue by gustavo-accellog** [Azure/azure-cli#9651]
## Describe the bug

**Command Name**
`az aks create`

**Errors:**
```
The operation 'azure.cli.command_modules.acs.custom#aks_create' is invalid.
Traceback (most recent call last):
python2.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 482, in execute
    self.commands_loader.load_arguments(command)
azure/cli/core/__init__.py, ln 275, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
...
azure/cli/core/__init__.py, ln 464, in default_arguments_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
azure/cli/core/__init__.py, ln 511, in get_op_handler
    raise ValueError("The operation '{}' is invalid.".format(operation))
ValueError: The operation 'azure.cli.command_modules.acs.custom#aks_create' is invalid.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az aks create --resource-group {} --name {} --node-count {} --service-principal {} --client-secret {} --generate-ssh-keys`

## Environment Summary
```
Linux-3.10.0-957.12.2.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Python 2.7.5
Shell: bash

azure-cli 2.0.66

```

**Comment by gustavo-accellog** [comment]
I run in Azure Cloud Shell and It's OK. But It's not working in my client.
I use CentOS 7 and the Azure Cli is up-to-date.

**Comment by rchamberlin-amplero** [comment]
I'm seeing similar having just done a yum update in Centos.  Specifically az aks list was failing with the following:
The command failed with an unexpected error. Here is the traceback:

The operation 'azure.cli.command_modules.acs.custom#aks_list' is invalid.
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 482, in execute
    self.commands_loader.load_arguments(command)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 275, in load_arguments
    self.command_table[command].load_arguments()  # this loads the arguments via reflection
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 282, in load_arguments
    super(AzCliCommand, self).load_arguments()
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/commands.py", line 97, in load_arguments
    cmd_args = self.arguments_loader()
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 464, in default_arguments_loader
    op = handler or self.get_op_handler(operation, operation_group=kwargs.get('operation_group'))
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 511, in get_op_handler
    raise ValueError("The operation '{}' is invalid.".format(operation))
ValueError: The operation 'azure.cli.command_modules.acs.custom#aks_list' is invalid.


I was able to get things working by downgrading azure-cli to 2.0.65 so I think there is a regression in 2.0.66 here.

**Comment by random-dwi** [comment]
same for me on Fedora 30. Downgrading from 2.0.67 to 2.0.65 helped

**Comment by jnoller** [comment]
This is a definite bug.

Looking at the stack trace, its more than likely due to a Python 3 vs Python 2 issue in the command line or the extension. Any Redhat Linux flavor (Centos, Fedora, etc) has Python2 pinned to the default version. The stack trace is occurring when the core CLI is loading the AKS extension to the CLI. I’ve seen reports of issues like this in the past where Python 3 native syntax has been added to the AKS extension.

^^ @jluk

**Comment by jluk** [comment]
@tjprescott or @yugangw-msft any ideas on this? I can't imagine this is an AKS isolated issue.

**Comment by yugangw-msft** [comment]
@marstr, any ideas?

**Comment by marstr** [comment]
RHEL is the last way we distribute that still relies on Python 2. My guess is that there is some Python3 specific syntax that snuck into the AKS module, as @jnoller mentioned.

**Comment by brendandburns** [comment]
Hrm, I can not reproduce this on a fresh Centos 7.5

```
[bburns@bburns-centos ~]$ az --version
azure-cli                         2.0.70

command-modules-nspkg               2.0.3
core                              2.0.70
nspkg                              3.0.4
telemetry                          1.0.3

Python location '/usr/bin/python'
Extensions directory '/home/bburns/.azure/cliextensions'

Python (Linux) 2.7.5 (default, Jun 20 2019, 20:27:34)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

Is it possible something got fixed somewhere else in the CLI? Regardless, I think we have to close this as "can not reproduce"

**Comment by gustavo-accellog** [comment]
I updated to 2.0.70 and it's ok.
Thank you.

**Comment by jluk** [comment]
Thank you for confirm @gustavo-accellog
