### ISSUE TITLE
Unable to assign the identity to webapp

### ISSUE THREAD

**Issue by benjaminbhuang** [Azure/azure-cli#9663]
## Describe the bug

**Command Name**
`az webapp identity assign`

**Errors:**
```
'NoneType' object has no attribute 'identity'
Traceback (most recent call last):
Temp\pip-install-ygnynjtx\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 560, in execute
azure\cli\core\commands\__init__.py, ln 618, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 611, in _run_job
Local\Temp\pip-install-ygnynjtx\six\six.py, ln 693, in reraise
azure\cli\core\commands\__init__.py, ln 588, in _run_job
azure\cli\core\commands\__init__.py, ln 297, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 461, in default_command_handler
azure\cli\command_modules\appservice\custom.py, ln 465, in assign_identity
azure\cli\core\commands\arm.py, ln 1032, in assign_identity
azure\cli\command_modules\appservice\custom.py, ln 460, in setter
AttributeError: 'NoneType' object has no attribute 'identity'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp identity assign --name {} --resource-group {}`

## Environment Summary
```
Windows-10-10.0.16299-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.66

```

**Comment by panchagnula** [comment]
@benjaminbhuang sorry for the dealy on getting back to you on this. The error occurs when the app was not found in the RG. Can you confirm you have the correct values for -n &  -g & the app does exist in the RG specified. One way to debug this further would be to run the command with --debug flag.  Please verify & lets us know if this indeed the case. Thanks!
