### ISSUE TITLE
Output weirdness with `--query` and `--out table`

### ISSUE THREAD

**Issue by JasonRShaver** [Azure/azure-cli#968]
While `--out table` is *way* more effective than before, it shows some output escaping with arbitrary query output that looks like something we can clean up.

```
$ az vm list --query [].[name,resourceGroup]
Result
-------------------------------
[u'VM-Data', u'VMGROUP1']
[u'VM-StagingWeb', u'VMGROUP1']
[u'VM-Web', u'VMGROUP1']
[u'MyNewVM', u'VMGROUP2']
```

**Comment by derekbekoe** [comment]
Previously, it what display an error as the query wasn't supported by table format.
After PR #911, now it doesn't display an error and attempts to show a table.

@tjprescott: thoughts on this?

A query that would work is:
```
$ az vm list --query [].{name: name, resourceGroup: resourceGroup}
```

**Comment by derekbekoe** [comment]
The query `[].[name,resourceGroup]` couldn't be displayed in table format as the table wouldn't have headings.

**Comment by derekbekoe** [comment]
I'd suggest for this, we go back to showing an error.

**Comment by johanste** [comment]
I respectfully disagree. I would expect generated column names (i.e. column1, column2 etc.)

**Comment by tjprescott** [comment]
@derekbekoe I agree with @johanste here. I'll create a PR to (1) add generated headings in the case of a list and (2) remove the fun u'blah' formatting if necessary.

**Comment by mayurid** [comment]
Agree with approach. Sprint 4 unless anyone disagrees
