### ISSUE TITLE
az ad app create --password does not always set the password I designate

### ISSUE THREAD

**Issue by shehreendheda** [Azure/azure-cli#9686]
**Describe the bug**
I have a workflow that runs a script in a VM that creates a new service principal in Azure AD each time a VM image is launched. The script includes the `az ad app create` command with the `--password ${PASSWORD}` argument that I designate. Sometimes the password is set to `${PASSWORD}` and sometimes the the password is set automatically by Azure. I know when the password is not set to `${PASSWORD}` because when I try to log in with the sp credentials, `${PASSWORD}` is not the correct password. Interestingly, when the `az ad app create` command runs and `--password` does not work, there is no error message.

Each time the script runs, I need the password to be set to `${PASSWORD}` because there is no way to capture the password set automatically by Azure and I need to pass the `${PASSWORD}` value into other commands that follow in the script.

Note:
1. The `${PASSWORD}` value is randomly generated each time so does not repeat for any app and ${PASSWORD} meets the criteria for a valid password in 
2. In the script, the new app is made into an sp using the `az ad sp create` and` az ad role assignment` commands.

I have also noticed that whenever the password is not set to the `${PASSWORD}` value, if I then run `az ad sp credential reset` command from the VM, the password that is output by this command also does not match the actual password that Azure has stored. But then, when I run `az ad sp credential reset` from my local machine for the same app, the password set by this command matches the one stored in Azure AD and the service principal is able to log in with this password. 

So what I am experiencing is that (1) sometimes the password can be set manually from the VM and sometimes the password cannot be set manually from the VM and (2) whenever I am unable to set/reset the password for an app from the VM, I am still able to set/reset the password from a local machine. What setting in Azure could cause this behavior? Or what system settings can cause Azure to behave this way?

**To Reproduce**
Launch a new VM multiple times (may take even more than 10 launches) that, each time, runs the `az ad app create` command with the `--password ${PASSWORD}` argument, followed by the `az ad sp create` and `az ad role assignment` commands. Use the `az login --service principal` command to test if the password ${PASSWORD} works.

**Expected behavior**
I expect that each time the password for the app is set to the ${PASSWORD} value that I designate.

**Environment summary**

Hyper-V virtualization platform to launch my VMs

azure-cli                         2.0.60 *
acr                                2.2.2 *
acs                               2.3.19 *
advisor                            2.0.0
ams                                0.4.2 *
appservice                        0.2.15 *
backup                             1.2.1 *
batch                              4.0.0 *
batchai                            0.4.7 *
billing                            0.2.0 *
botservice                         0.1.8 *
cdn                                0.2.0 *
cloud                              2.1.0 *
cognitiveservices                  0.2.4 *
command-modules-nspkg               2.0.2
configure                         2.0.20 *
consumption                        0.4.2 *
container                         0.3.15 *
core                              2.0.60 *
cosmosdb                           0.2.8 *
dla                                0.2.4 *
dls                                0.1.8 *
dms                                0.1.2 *
eventgrid                          0.2.1 *
eventhubs                          0.3.4 *
extension                          0.2.3 *
feedback                           2.1.4 *
find                               0.3.0 *
hdinsight                          0.3.2 *
interactive                        0.4.1 *
iot                                0.3.6 *
iotcentral                         0.1.6
keyvault                          2.2.12 *
kusto                              0.2.0 *
lab                                0.1.5 *
maps                               0.3.3 *
monitor                           0.2.10 *
network                            2.3.4 *
nspkg                              3.0.3
policyinsights                     0.1.1 *
profile                            2.1.3 *
rdbms                              0.3.8 *
redis                              0.4.1 *
relay                              0.1.3 *
reservations                       0.4.1 *
resource                          2.1.11 *
role                               2.4.2 *
search                             0.1.1
security                           0.1.0 *
servicebus                         0.3.3 *
servicefabric                     0.1.14 *
signalr                            1.0.0
sql                                2.1.9 *
sqlvm                              0.1.0 *
storage                            2.3.1 *
telemetry                          1.0.1 *
vm                                2.2.16 *

Python location '/opt/az/bin/python3'
Extensions directory '/home/student/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Mar  7 2019, 19:46:51)
[GCC 7.3.0]

  

**Additional context**

**Comment by shehreendheda** [comment]
@yugangw-msft Hi. Any progress with this issue? Thanks!

**Comment by jiasli** [comment]
Looks like an AAD delay issue. When the issue happens, could you send me the output when you run `az login --service principal --debug` at jiasli@microsoft.com? We can involve AAD team to take a look.

**Comment by yonzhan** [comment]
add to S170

**Comment by yonzhan** [comment]
@shehreendheda any update?

**Comment by jiasli** [comment]
If you are still seeing this issue, please create a Support Request in Azure portal and provide the `--debug` log which contains correlation IDs. AAD team will help investigate from the backend.
