### ISSUE TITLE
Ubuntu Disco ppa.launchpad.net/jonathonf/backports/ubuntu is missing, consequently breaking installation

### ISSUE THREAD

**Issue by PorkyProgs** [Azure/azure-cli#9689]
Whether installing the Automated script or running the process manually as described on https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest for the Ubuntu Disco release fails, with the following error:
Err:11 http://ppa.launchpad.net/jonathonf/backports/ubuntu disco Release
404 Not Found [IP: 91.189.95.83 80]
Any tips how to complete the installation would be greatly appreciated.

**Comment by PorkyProgs** [comment]
Whether installing the Automated script or running the process manually as described on https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest for the Ubuntu Disco release fails, with the following error:
Err:11 http://ppa.launchpad.net/jonathonf/backports/ubuntu disco Release       
  404  Not Found [IP: 91.189.95.83 80]
Any tips how to complete the installation would be greatly appreciated.

**Comment by marstr** [comment]
Howdy @PorkyProgs,

I'm able to install the Azure CLI via apt in a fresh container by running the following:

``` bash
docker run -it --rm ubuntu:disco # I'm actually using podman because I use Fedora, but it works the same as Docker.
apt update
apt install -y curl
curl -sL https://aka.ms/InstallAzureCLIDeb | bash
az --version
```
Obviously, that's not really an alternative for you! But it does tell me that trying to install in a blank-slate works. Looking at the error you encountered, it looks like you have a malformed apt repository. I bet you'll encounter this error for any other apt package you try to install. :) [Here's a post on AskUbuntu](https://askubuntu.com/questions/307/how-can-ppas-be-removed) about how to remove PPAs that should fix you.

**Comment by marstr** [comment]
For some confirmation of this: if you checkout http://ppa.launchpad.net/jonathonf/backports/ubuntu/dists/, you'll see that `disco` hasn't been added there yet.

**Comment by PorkyProgs** [comment]
Thanks Martin for an explanation. You're absolutely correct in taht the PPA for Disco is missing
However perhaps you can explain; if the PPA is unnecessary why is it built into the installation setup script in the first place? Or am I missing something from my installaiton? 
Is that a normal practice in Linux to write a sort of standard setup script for all Ubuntu versions even if the respective PPA is not needed? Hmm interesting.

**Comment by marstr** [comment]
Ah so in general Ubuntu users just use `apt install` to get new applications. The trouble for us is that this only works for programs that are distributed through Ubuntu's repositories. Our package is distributed via Microsoft's repositories here: https://packages.microsoft.com. Our script goes about helping you out by adding our repository as a trusted place to install from. However, as part of that we run `apt update` which synchronizes all of the metadata about available packages. However, if you have a repository (in your case the PPA) that isn't setup correctly, apt isn't able to synchronize that metadata, blocking further progress in our script.
