### ISSUE TITLE
az logout --subscription

### ISSUE THREAD

**Issue by yvesdeceuleners** [Azure/azure-cli#9694]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by yvesdeceuleners** [comment]
Current status: logged in to 2 different subscriptions, using "az login".

$ az account list 
A few accounts are skipped as they don't have 'Enabled' state. Use '--all' to display them.
[
  {
    "cloudName": "AzureCloud",
    "id": "029615ac-www-xxxx-yyyy-zzzzzzzzzzz",
    "isDefault": false,
    "name": "Very Nice Name",
    "state": "Enabled",
    "tenantId": "6cf18ffb-wwww-xxxx-yyyy-zzzzzzzzzzzz",
    "user": {
      "name": "xyz@xyz.com",
      "type": "user"
    }
  },
  {
    "cloudName": "AzureCloud",
    "id": "88c5cd9c-wwww-xxxx-yyyy-zzzzzzzzzzzz",
    "isDefault": true,
    "name": "Also a Very Nice Name",
    "state": "Enabled",
    "tenantId": "08e45a9f-wwww-xxxx-yyyy-zzzzzzzzzzzz",
    "user": {
      "name": "abc@abc.com",
      "type": "user"
    }
  }
]

**Logging out to one subscription, using az logout:** 
`az logout --subscription 029615ac -www-xxxx-yyyy-zzzzzzzzzzz`

_Result_: logged out to the wrong account.
```
$ az account list 
[
  {
    "cloudName": "AzureCloud",
    "id": "029615ac-www-xxxx-yyyy-zzzzzzzzzzz",
    "isDefault": false,
    "name": "Very Nice Name",
    "state": "Enabled",
    "tenantId": "6cf18ffb-wwww-xxxx-yyyy-zzzzzzzzzzzz",
    "user": {
      "name": "xyz@xyz.com",
      "type": "user"
    }
  }
]
```

**Comment by marstr** [comment]
Given the semantics here: https://github.com/Azure/azure-cli/blob/a1f2f2b666a759eb2f593dd7796db6bbd0237614/src/azure-cli-core/azure/cli/core/_profile.py#L452-L459

Plus the context that all of the other account related commands squash the global subscription parameter, and it's my impression that this command should accept the subscription parameter at all. I'll have a PR out momentarily that strips `--subscription` as a valid flag.

**Comment by muyukha** [comment]
use az logout --subscription

**Comment by jiasli** [comment]
@muyukha, `az logout` does not support `--subscription`:

```
> az logout -h

Command
    az logout : Log out to remove access to Azure subscriptions.

Arguments
    --username         : Account user, if missing, logout the current active account.

Global Arguments
    --debug            : Increase logging verbosity to show all debug logs.
    --help -h          : Show this help message and exit.
    --only-show-errors : Only show errors, suppressing warnings.
    --output -o        : Output format.  Allowed values: json, jsonc, none, table, tsv, yaml, yamlc.
                         Default: json.
    --query            : JMESPath query string. See http://jmespath.org/ for more information and
                         examples.
    --verbose          : Increase logging verbosity. Use --debug for full debug logs.
```

`az logout` can only log out a specific user account, not a subscription.
