### ISSUE TITLE
`az lab vm create` does not support shared image galleries

### ISSUE THREAD

**Issue by scarolan** [Azure/azure-cli#9696]
## Describe the bug
`az lab vm create` only appears to support images from the public Gallery, and not private shared gallery.  We want to use our own internal images to spin up labs.  Please add support for this.

https://docs.microsoft.com/en-us/cli/azure/lab/vm?view=azure-cli-latest#az-lab-vm-create

**Command Name**
`az lab vm create`

**Errors:**
```
Unable to find custom image name 'selabworkstation' in the 'se-training-lab' lab.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az lab vm create --lab-name {} -g {} --name {} --image {} --image-type {} --size {} --admin-username {} --admin-password {} --ip-configuration {}`

## Expected Behavior
It should find the image in the shared image gallery and use that to build a VM.

## Environment Summary
```
Linux-4.4.0-17134-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.66

Extensions:
image-copy-extension 0.2.1

```

**Comment by tjprescott** [comment]
Hi @scarolan I don't believe new features are being planned for the DevTest Labs command modules, but I will mark with service team attention so that they can consider it for the future.

**Comment by scarolan** [comment]
That's too bad.  Programmatic access to be able to spin up dev/test VMs would be really useful.  Our use case is spinning up training labs with either the az command or terraform.  Right now we are hamstrung by having to do this through the UI.

**Comment by tanmayeekamath** [comment]
Thanks for your feedback @scarolan and apologies for the delay. 
This has been in our backlog, however we don't have a timeline for it unfortunately. 

Since this was last year, were you able to find a workaround for this? If not happy to jump on a call or start an email thread to help you find alternatives. Please let us know. 

Tanmayee

**Comment by adstep** [comment]
Was looking to spin up a VM from a SIG image using az cli and this seems to be unsupported/undocumented still.

@tanmayeekamath any updates?

**Comment by tanmayeekamath** [comment]
Hello @adstep 
Yes you should be able to use an ARM template or the REST API for this today. 
Here is a doc on the same: https://docs.microsoft.com/en-us/azure/devtest-labs/add-vm-use-shared-image#resource-manager-template

CLI is not yet supported for the SIG related actions in DTL. 

Thanks,
Tanmayee

**Comment by SaurabhSharma-MSFT** [comment]
@tanmayeekamath Do you have any latest updates on this feature request?

**Comment by sagarlankala** [comment]
Hi @SaurabhSharma-MSFT , 

We are currently working on the next version of API's and associated SDK's, CLI's. SIG support in CLI will be available after we publish them. Until then, we recommend using REST API's and ARM templates for automation.

**Comment by SaurabhSharma-MSFT** [comment]
@sagarlankala Thanks for the information.

**Comment by scarolan** [comment]
You can close it out, thanks.
