### ISSUE TITLE
Onboarding Request for PrepareNetworkPolicies feature for Azure CLI

### ISSUE THREAD

**Issue by mvvsubbu** [Azure/azure-cli#9703]
**Resource Provider**
Microsoft.Network

**Description of Feature or Work Requested**
This API gives permissions to a delegated service to apply or modify network intent policies on the given subnet. 

**Minimum API Version Required**

2019-06-01

**Swagger Link**
[virtualNetwork.json](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fblob%2Fnetwork-may-release%2Fspecification%2Fnetwork%2Fresource-manager%2FMicrosoft.Network%2Fstable%2F2019-06-01%2FvirtualNetwork.json&data=02%7C01%7Csubraman%40microsoft.com%7Cb5278e5f15fa4c8e61a808d6f36624b8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636964017355524783&sdata=l%2BzCY2PGQ5gBJOP6rBhTdwrQ2Wi0KGEAoE7%2FysUWFrs%3D&reserved=0)

**Target Date**
2019-07-16

**Comment by yonzhan** [comment]
@MyronFanQiu  put in backlog.

**Comment by yonzhan** [comment]
add to S170

**Comment by haroldrandom** [comment]
@mvvsubbu Could you please provide other information about the service?  Is it available on Portal?

**Comment by haroldrandom** [comment]
Closed as no need as discussed in email thread.
