### ISSUE TITLE
--ssh-key-values

### ISSUE THREAD

**Issue by andreasottosson** [Azure/azure-cli#9706]
Should this be --ssh-key-value ? Without the "s".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 152b549b-d4b3-13e5-081c-c604b6e4d89e
* Version Independent ID: 3f79be78-ce75-ad31-304b-bad7d475ec9e
* Content: [az vm](https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
```
--ssh-key-values               : Space-separated list of SSH public keys or public key file
                                     paths.
```

It accepts multiple values, so this is correct.

**Comment by andreasottosson** [comment]
Sorry! My azure-cli was outdated.. Now it works. Your example still says --ssh-key-value though, in this example `az vm create -n MyVm -g MyResourceGroup --image debian --vnet-name MyVnet --subnet subnet1 \
                            --availability-set MyAvailabilitySet --public-ip-address-dns-name MyUniqueDnsName \
                            --ssh-key-value @key-file`

**Comment by Calvin-Yuhui-Liu** [comment]
Agree with @andreasottosson, better to change the example command to **_--ssh-key-values_**.
