### ISSUE TITLE
Using '--orderby' and '--top' without' '--detail' in 'az acr repository show-tags'

### ISSUE THREAD

**Issue by GHSimeon** [Azure/azure-cli#9708]
Executing 'az acr repository show-tags -n MyRegistry --repository MyRepository --top 10 --orderby time_desc' (without the --detail flag) returns two warnings stating that the ordby and top flags are ignored when using them without the detail flag, yet the command still returns the top 10 tags ordered descending by time (if they're omitted all tags are shown unordered). I personally don't see a reason why the flags should only be used with --detail, therefor I suggest the warnings to be removed.

**Comment by sajayantony** [comment]
The change is breaking to existing users. 
@tjprescott Do you folks have any recommendation, we would potentially remove the --detail options and make that output the default since its definitely the more useful command anyway.

**Comment by tjprescott** [comment]
If I understand correctly, @GHSimeon  is simply suggesting removing the warning in CLI since the things it warns won't work does work. That wouldn't be a breaking change unless I'm missing something.

**Comment by sajayantony** [comment]
Yes. 
/cc @hkuadithya can you pick this up?

**Comment by hkuadithya** [comment]
@sajayantony I'll create a task and start working on it. Thanks.

**Comment by djyou** [comment]
@GHSimeon Could you upgrade your CLI and try again?

**Comment by GHSimeon** [comment]
@djyou Sorry for the late reply. I checked and the warnings aren't displayed anymore.
@hkuadithya I can't remember which version that was, sorry. Probably the latest one though as I was using the CLI from within the Azure CLI task in Azure Pipelines.
Thank you.

**Comment by sajayantony** [comment]
@GHSimeon @tjprescott Could we please this issue in that case.
