### ISSUE TITLE
Requesting metrics list-definition by id fails but name, resource group and type succeeds

### ISSUE THREAD

**Issue by mrwizard82d1** [Azure/azure-cli#9713]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Requesting a metrics list-definition of an existing resource using the resource ID copied from my Azure portal fails, but requesting a metrics list-definition using the resource name, resource group and resource type for the same resource succeeds.

**To Reproduce**
- Given I have created an Azure resource
- When I execute the command `az monitor metrics list-definitions --resource /subscriptions/<subscription-id>/resourceGroups/<resource-group>/providers/Microsoft.Ev entHub/namespaces/<resource-type>`
Then I expect to source a list of metrics definitions
But I see the error message `usage error: --resource ID | --resource NAME --resource-group NAME --resource-type TYPE [--resource-parent PARENT] [--resource-namespace NAMESPACE]`

If I explicitly specify the name, resource group and type, I **do** see the metrics list definitions

**Expected behavior**
I expect the two ways of requesting metrics list-definitions to provide the same information.

**Environment summary**
Install Method (chocolateyinstalled into Python 3) / CLI version (2.0.67) / OS version (Microsoft Windows 10 Pro Version	10.0.17763 Build 17763
) / Shell Type (mingw64 bash - MINGW64_NT-10.0)  

**Additional context**
I am incredibly new. It is most likely user error, but I've not been able to find it. :)

**Comment by tjprescott** [comment]
`/subscriptions/<subscription-id>/resourceGroups/<resource-group>/providers/Microsoft.Ev entHub/namespaces/<resource-type>`

That is not a resource ID.  If you add name, it will work:
`/subscriptions/<subscription-id>/resourceGroups/<resource-group>/providers/Microsoft.Ev entHub/namespaces/<resource-type>/<name>`

**Comment by mrwizard82d1** [comment]
Travis,

Thanks for your note. 

What I'm surprised by is that this is the ID of the resource as reported in the Properties blade of the resource:

![image](https://user-images.githubusercontent.com/595422/59783149-1e68c880-9285-11e9-96d1-5f284d0b1b09.png)

**Comment by mrwizard82d1** [comment]
This is the name that I copied into my script that reported the error.

**Comment by tjprescott** [comment]
Hmm... if you did a copy-paste of the resource ID from the portal it should work. I did a copy-paste from the CLI show command and it worked no problem. If you can post the actual command you issued that failed I might be able to identify what is wrong.

**Comment by mrwizard82d1** [comment]
Can I email it to you directly? I'd prefer not to paste it in a public forum.

**Comment by tjprescott** [comment]
Absolutely, trpresco AT microsoft.com

**Comment by mrwizard82d1** [comment]
Just sent, Travis. Thanks.
