### ISSUE TITLE
az vm user update still use  VMAccessForLinux 1.4 version

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/azure-cli#9726]
**Version**
vm: 2.2.23

**Describe the bug**
The "az vm user" command still uses vmaccess version 1.4 which does not work in RHEL-8.0. (the new version is 1.5.2). Could you please update the version? Or could you please consider to add a parameter that let customer specify the extension version? Thanks!

**To Reproduce**
az vm user update --name "wala8ond" --resource-group walaautoeastus --username xxxxx --password "xxxx"

**Additional context**
azure/cli/command_modules/vm/custom.py
extension_mappings = {
    _LINUX_ACCESS_EXT: {
        'version': '1.4', ->  '1.5',

**Comment by yonzhan** [comment]
@qwordy please take a look.

**Comment by qwordy** [comment]
> 
> 
> @qwordy please take a look.

OK

**Comment by qwordy** [comment]
@yuxisun1217 Is it safe to update version to 1.5? Is it compatible? If so, we can update version without offering multiple choices of version.

**Comment by yuxisun1217** [comment]
Hi @qwordy ,
Sorry I cannot confirm if it is safe in all platforms. I checked with RHEL-7.7 and RHEL-8 with version 1.5.4 and it worked well. Thanks!

**Comment by qwordy** [comment]
> 
> 
> Hi @qwordy ,
> Sorry I cannot confirm if it is safe in all platforms. I checked with RHEL-7.7 and RHEL-8 with version 1.5.4 and it worked well. Thanks!

Thanks for your reply.

**Comment by qwordy** [comment]
The PR is merged. It will be available in Azure 2.0.76. Official Release: 11/04/2019

**Comment by yuxisun1217** [comment]
Got it. Thank you so much!
