### ISSUE TITLE
az ad app create with roles fails

### ISSUE THREAD

**Issue by adibraniste** [Azure/azure-cli#9728]
az ad app create with --app-roles fails with the following error:
az : ERROR: Expecting value: line 1 column 1 (char 0)
At ...\dev-we1\software\api-client.deploy.ps1:14 char:20
+ ... istration = az ad app create --display-name $displayName --app-roles  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: Expectin...lumn 1 (char 0):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

I am running the following command from a ps1 file in a power shell 5 console, where the roles.json is in the same location as the ps file:
az ad app create --display-name "app-test" --app-roles "roles.json"

Removing the --app-roles "roles.json" part creates the app properly. I have tried removing the ", prefixing the filename with @, nothing seems to work.

roles.json content:
[
  {
    "allowedMemberTypes": [
      "Application"
    ],
    "description": "Allow the application to call actions as itself.",
    "displayName": "Call actions",
    "isEnabled": true,
    "lang": null,
    "origin": "Application",
    "value": "Actions.Call"
  }
]

I am running the latest version of Az module installed via MSI:
azure-cli                         2.0.67

acr                                2.2.9
acs                                2.4.4
advisor                            2.0.1
ams                                0.4.7
appservice                        0.2.21
backup                             1.2.5
batch                              4.0.3
batchai                           0.4.10
billing                            0.2.2
botservice                         0.2.2
cdn                                0.2.4
cloud                              2.1.1
cognitiveservices                  0.2.6
command-modules-nspkg               2.0.2
configure                         2.0.24
consumption                        0.4.4
container                         0.3.18
core                              2.0.67
cosmosdb                          0.2.11
deploymentmanager                  0.1.1
dla                                0.2.6
dls                               0.1.10
dms                                0.1.4
eventgrid                          0.2.4
eventhubs                          0.3.7
extension                          0.2.5
feedback                           2.2.1
find                               0.3.4
hdinsight                          0.3.5
interactive                        0.4.5
iot                               0.3.11
iotcentral                         0.1.7
keyvault                          2.2.16
kusto                              0.2.3
lab                                0.1.8
maps                               0.3.5
monitor                           0.2.15
natgateway                         0.1.1
network                            2.5.2
nspkg                              3.0.3
policyinsights                     0.1.4
privatedns                         1.0.2
profile                            2.1.5
rdbms                             0.3.12
redis                              0.4.4
relay                              0.1.5
reservations                       0.4.3
resource                          2.1.16
role                               2.6.4
search                             0.1.2
security                           0.1.2
servicebus                         0.3.6
servicefabric                     0.1.20
signalr                            1.0.1
sql                                2.2.5
sqlvm                              0.2.0
storage                            2.4.3
telemetry                          1.0.2
vm                                2.2.23

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\dev\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

**Comment by adibraniste** [comment]
Same issue also for _az ad app update --id $appRegistration.appId --app-roles "roles.json"_

**Comment by adibraniste** [comment]
It seems that the issue was caused by PowerShell ISE - it was running the script by default under the 'PS C:\WINDOWS\system32>' folder. Because of this, the roles.json file was not found in this folder since obviously it was under another folder.
Maybe it would make sense to have a more specific error message with 'File not found' in this case.

**Comment by yugangw-msft** [comment]
Agreed, ideally we should emit out a warning to tell people that the file can't load or the role content is not json. We will consider once we have more user voices on this. 
For anyone who runs into this, please upvote
