### ISSUE TITLE
Flattening related issues

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#9734]
Tracking issue for items that need to be resolved prior to release that are related to the change in azure-cli packaing:

- [x] Update internal test logic used by CI to detect tests
- [x] Restore the `linter_exclusion.yml` files that were previously in certain modules.
- [x] Fix the internal linter (azdev already patched) to locate the relocated modules.
- [ ] The script to verify the doc source map likely does not work and always passes even though it can't detect the modules.
- [x] Ensure CODEOWNERS file is compatible with the new package structure

**Comment by marstr** [comment]
Removing my assignment as I've moved to the Notification Hubs team.

**Comment by yonzhan** [comment]
add to S164.

**Comment by yonzhan** [comment]
add to S172

**Comment by MyronFanQiu** [comment]
Closed this issue since I think they're already fixed or not met by us.
