### ISSUE TITLE
unable to upload blob

### ISSUE THREAD

**Issue by raytrun** [Azure/azure-cli#9740]
## Describe the bug

**Command Name**
`az storage blob upload`

**Errors:**
```
az storage blob upload: error: the following arguments are required: --file/-f
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob upload --container-name {} --name {} {} {}`

## Environment Summary
```
Darwin-18.6.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.67

```

**Comment by limingu** [comment]
As the error message, the file parameter is need to tell which file to upload.
