### ISSUE TITLE
[AKS] az aks create -h sample command for enabling cluster autoscaler incorrect

### ISSUE THREAD

**Issue by sauryadas** [Azure/azure-cli#9746]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
az aks create -h returns the following as an example for cluster autoscaler which does not work 
Cluster autoscaler requires --enable-vmss flag.. Please not that i have the aks-preview cli extension enabled.

    Create a kubernetes cluster with preview api version and cluster autosclaler enabled.
        az aks create -g MyResourceGroup -n MyManagedCluster --kubernetes-version 1.11.2 --node-
        count 3 --enable-cluster-autoscaler --min-count 1 --max-count 5

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
Should be 

    Create a kubernetes cluster with preview api version and cluster autosclaler enabled.
        az aks create -g MyResourceGroup -n MyManagedCluster --kubernetes-version 1.11.2 --node-
        count 3 --enable-cluster-autoscaler --min-count 1 --max-count 5 --enable-vmss

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by brendandburns** [comment]
Fix is here:
https://github.com/Azure/azure-cli-extensions/pull/878
