### ISSUE TITLE
Please document supported platform flags

### ISSUE THREAD

**Issue by PatrickLang** [Azure/azure-cli#9748]
Also related - I noticed `--platform Windows/x86` called out as an example above, which is wrong. The typical Windows example should be `Windows/amd64`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c608162e-cf40-9d53-da4a-51f51a0311ea
* Version Independent ID: eccbb543-be68-7de2-d41d-abee55c81452
* Content: [az acr](https://docs.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-acr/azure/cli/command_modules/acr/_help.py)
* Service: **container-registry**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by PatrickLang** [comment]
If you are trying to build using the example here with `--platform Windows/x86` and get this error:
`hcsshim::PrepareLayer failed in Win32: The parameter is incorrect. (0x57) path=C:\ProgramData\docker\windowsfilter\..` then you probably need to use `--platform Windows/amd64` instead.

**Comment by yugangw-msft** [comment]
https://github.com/Azure/azure-cli/pull/10406 should have addressed this
CC: @northtyphoon
