### ISSUE TITLE
Error loading command module 'storage'

### ISSUE THREAD

**Issue by irl** [Azure/azure-cli#975]
Using b7, with azure-cli-storage installed, the following error pops up when running `az`:

```
Error loading command module 'storage'
```

Please let me know if there's anything I can do to debug this if this is not reproducible.

**Comment by derekbekoe** [comment]
@irl: Use the `--debug` flag to show debug information.

**Comment by irl** [comment]
Thanks. python-azure-storage was missing from the installation.
