### ISSUE TITLE
[VM] [Feature Request] Add provisionVMAgent configuration

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/azure-cli#9757]
**Is your feature request related to a problem? Please describe.**
I need this feature to test "provision with cloud-init, without wala agent" scenario.

**Describe the solution you'd like**
Add a parameter that can specify --provision-vm-agent as "true" or "false"; "true" as default.

**Describe alternatives you've considered**
No idea. Please help to provide any workaround if have.

**Additional context**
None

Thanks!

**Comment by qwordy** [comment]
We have received your feature request.

**Comment by qwordy** [comment]
PR merged.

**Comment by yuxisun1217** [comment]
Got it. Thank you so much!

**Comment by danielsollondon** [comment]
Has this been released yet? thanks
