### ISSUE TITLE
Can't get the resource details using az consumption

### ISSUE THREAD

**Issue by prabhakarreddy1234** [Azure/azure-cli#9758]
I am using below command to get some properties (e.g meterId) of a newly created resource.

 `az consumption usage list --include-meter-details --query "[?contains(instanceName,'<resource name>')].meterId" --top 10 -o json`

But i am getting empty array as output. I could query for other resources and get their properties. It's happening for newly created resources.

Is there any timeframe i need to wait before i can get them through consumption cli ?

**To Reproduce**
Create a new azure resource group and resources. Run above command.

**Expected behavior**
It should return resource details queried for

**Environment summary**
az consumption - v0.4.2

https://stackoverflow.com/questions/56700324/cant-get-result-from-az-consumption-command

**Comment by ramaganesan-rg** [comment]
This is by design.. newly created resources will take time to emit usage and will show up in our system after 4-8 hours.
