### ISSUE TITLE
[storage] sas token is not in the same argument group as the rest of the storage arguments

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-cli#976]
Storage Account Arguments
    --account-key                 : Storage account key. Must be used in conjunction with storage
                                    account name. Environment variable: AZURE_STORAGE_KEY.
    --account-name                : Storage account name. Must be used in conjunction with either
                                    storage account key or a SAS token. Environment variable:
                                    AZURE_STORAGE_ACCOUNT.
    --connection-string           : Storage account connection string. Environment variable:
                                    AZURE_STORAGE_CONNECTION_STRING.

Pre-condition Arguments
    --if-match                    : An ETag value, or the wildcard character (*). Specify this
                                    header to perform the operation only if the resource's ETag
                                    matches the value specified.
    --if-modified-since           : Alter only if modified since supplied UTC datetime
                                    (Y-m-d'T'H:M'Z').
    --if-none-match               : An ETag value, or the wildcard character (*). Specify this
                                    header to perform the operation only if the resource's ETag does
                                    not match the value specified. Specify the wildcard character
                                    (*) to perform the operation only if the resource does not
                                    exist, and fail the operation if it does exist.
    --if-unmodified-since         : Alter only if unmodified since supplied UTC datetime
                                    (Y-m-d'T'H:M'Z').

Storage Account Arguments
    --sas-token                   : A Shared Access Signature (SAS). Must be used in conjunction
                                    with storage account name. Environment variable:
                                    AZURE_STORAGE_SAS_TOKEN.

**Comment by tjprescott** [comment]
This was supposed to have been fixed in #845. I'll check it out.
