### ISSUE TITLE
Examples have incorrect syntax

### ISSUE THREAD

**Issue by kiwi-dejero** [Azure/azure-cli#9766]
`"$({ ~/.ssh/id_rsa.pub)"`  should have { replaced with &lt; 

`"$(< ~/.ssh/id_rsa.pub)"`

Alternatively use the @ form to source the file.

`@~/.ssh/id_rsa.pu`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0474c5a5-4231-0e39-f63f-f7bc05cb7797
* Version Independent ID: 22ea94c8-cc6f-97aa-77b1-4ffca845807e
* Content: [az vm user](https://docs.microsoft.com/en-us/cli/azure/vm/user?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@haroldrandom  planned after Ignite.
