### ISSUE TITLE
Unable to record FunctionApp test

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#9769]
- [ ] test_functionapp_unavailable_location_app_insights

Test keeps failing to re-record:
```
ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/clitest.rg000001/providers/Microsoft.Web/sites/functionappwithappinsights000003?api-version=2018-11-01 (Caused by ResponseError('too many 502 error responses',))
```

Test has been marked @live_only to permit merging PR #9759.

**Comment by ankitkumarr** [comment]
Sorry about that @tjprescott. The test was assuming that Application Insights was unavailable at a location. But looks like it was made available. The test shouldn't have depended on something like that. I will update / remove the test this Sprint.
