### ISSUE TITLE
Unable to re-record MySQL test

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#9770]
- [ ] test_mysql_replica_mgmt

Test cannot be recorded. Yields error:
```
ValidationError: Parameter 'body' can not be None.
```

Test marked @live_only to permit merging PR #9759.

**Comment by ajlam** [comment]
@tjprescott - do you need someone from our team to look into this?

**Comment by tjprescott** [comment]
@ajlam someone should yes to fix up the test and ensure that some critical functionality isn't broken.

**Comment by ajlam** [comment]
@grigusev @QingqingYuan2  - can you look into this?

**Comment by grigusev** [comment]
I'm working on submitting CLI change with replica create API and will take care about this issue.

**Comment by grigusev** [comment]
the fix is included into PR https://github.com/Azure/azure-cli/pull/9837/

**Comment by ajlam** [comment]
Closing after PR #9837 has been merged.
