### ISSUE TITLE
No way to remove certifiation from service fabric application

### ISSUE THREAD

**Issue by lovelangy** [Azure/azure-cli#9774]
I don't find any command to remove cert  from service fabric applicaiton.
all the document i can found is to add cert by `az sf application certificate add `or [Add-AzServiceFabricApplicationCertificate
](https://docs.microsoft.com/en-us/powershell/module/az.servicefabric/Add-azServiceFabricApplicationCertificate?view=azps-2.3.2)

I tried to RDP to the service fabric node, mannually delete the certificate from cert store(run 'mmc'->add/remove snapin -> certificate),  the certificate will come back after VM restart.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc8df7f4-d9e3-87cc-0283-e8d073459785
* Version Independent ID: 94ea6ce4-5f08-8941-8ffd-5699a5b5e180
* Content: [az sf application certificate](https://docs.microsoft.com/en-us/cli/azure/sf/application/certificate?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/sf/application/certificate.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/sf/application/certificate.yml)
* Service: **service-fabric**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by lovelangy** [comment]
find a way to remove application certificate:
1. go to https://resources.azure.com/, find the vm scaleset,  click edit, remove the  the values from `vaultCertificates` section
2. then RDP to each instances of the VM scaleset,  manually remove the cert.  then it won't come back after restart.

It is still nice to have `az sf application certificate remove `command.

**Comment by peterpogorski** [comment]
@lovelangly Thanks for the feedback! At this time we are not going to be adding this cmdlet as we do not have the required functionality to remove a certificate from an application. 

When completing this action, the cerificate is not actually removed from the current VMs in the VM scale set but will indicate that the certificate will not be added to new VMs added to the scale set. 
_go to https://resources.azure.com/, find the vm scaleset, click edit, remove the the values from vaultCertificates section_
