### ISSUE TITLE
Azure CLI "cors add" creates multiple entries of the same origin.

### ISSUE THREAD

**Issue by liron-navon** [Azure/azure-cli#9778]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Calling "az functionapp cors add" from the CI/CD pipeline creates a new cors entry every time, instead of checking if the entry already exists.
This is important since I use it in the pipelines which are called every time the git repo is updated.

**To Reproduce**
```
az functionapp cors add --resource-group  $(ResourceGroupName) --name $(AppName)  --allowed-origins $(allowedOrigins)
```

**Expected behavior**
If I call `az functionapp cors add` multiple time, it should just create a single entry of the origin and not multiple.

**Environment summary**
Azure pipeline

**Additional context**
Image from the azure dashboard
![Screenshot 2019-06-24 at 14 06 06](https://user-images.githubusercontent.com/18119833/60017544-3ecfc300-9689-11e9-8db1-a1c268080d86.png)

**Comment by ahmedelnably** [comment]
Thanks for reporting that, we will take a look and fix it in a future release

**Comment by jmulcahy-fiscaltec** [comment]
Also had this issue. Only an issue for me when running via our pipeline on a Linux agent. When running locally on Windows, the command does not create duplicate entries.

**Comment by LockTar** [comment]
Uggly workaround to check if origin is already set in PowerShell.
If not set, add it otherwise skip.

```ps1
# Configure CORS for Function App
Write-Host "Set CORS in function app"
$allowedOrigins = "https://dev.azure.com","https://localhost:3000"

foreach ($item in $allowedOrigins) {
    Write-Host "Check if allowedorigin '$item' is already set"
    $missesOrigin = az functionapp cors show --name "$FunctionAppName" --query "contains(to_string(length(allowedOrigins[?contains(@, '$item')])),'0')"
    if ($missesOrigin -eq "true") {
        Write-Host "Add allowedorigin '$item'"
        az functionapp cors add -n "$FunctionAppName" --allowed-origins $item
    }
    else {
        Write-Host "Allowedorigin '$item' already set"
    }
}
```

**Comment by ShawnMcGough** [comment]
Still an issue. I'm using a different workaround where I remove before adding. Seems to work fine since removing non-existing origins does not throw error or warning.
ex:
`az functionapp cors remove --allowed-origins http://www.example.com`
`az functionapp cors add --allowed-origins http://www.example.com`

**Comment by SaurabhSharma-MSFT** [comment]
@liron-navon Apologies for the delayed response. This GitHub issue has been open for quite some time. Could you please let us know if you still facing this issue and need assistance? Awaiting your reply.
