### ISSUE TITLE
ADFS _authority is wrong in stored profile

### ISSUE THREAD

**Issue by jbpaux** [Azure/azure-cli#9779]
## Describe the bug
In an disconnected Azure Stack environment (with ADFS authentication), the authority in the token has the following format:
https://adfs.region.fqdn/adfs/tenantid
However, in the stored token ( in ~/.azure/accessTokens.json), the _authority field only has https://adfs.region.fqdn/adfs/

**Command Name**
`az account get-access-token` to show the access token then decrypt it using jwt.io

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login`
- `az account get-access-token`
- `jq '.[0]._authority' ~/.azure/accessTokens.json`

## Expected Behavior
_authority should be the authority of the token

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.67

```

**Comment by jbpaux** [comment]
Can you tag Azure Stack and Authentication instead ? and maybe @yugangw-msft can have a look ?

**Comment by jbpaux** [comment]
Any advice ?

**Comment by yonzhan** [comment]
We will triage this issue.

**Comment by Matt45D** [comment]
Any update on a temporary workaround for this issue? I am running into exact same issue with my connected ADFS Azure Stack environment.

**Comment by gusmann** [comment]
Same as Matt for us, we're unable to use our Terraform to provision resources in a disconnected (ADFS) Azure Stack. What's the temporary fix here? Is there a way to modify the authorization token manually so that it matches up with how AAD's token is written?

**Comment by gusmann** [comment]
Same as Matt for us, we're unable to use our Terraform to provision resources in a disconnected (ADFS) Azure Stack. What's the temporary fix here? Is there a way to modify the authorization token manually so that it matches up with how AAD's token is written?

**Comment by gusmann** [comment]
Ok, it looks like the temporary fix is to modify `~/.azure/accessTokens.json` so that the value for the `_authorization` key is `https://adfs.region.fqdn/adfs/tenantid` instead of `https://adfs.region.fqdn/adfs` (just like jbpaux explains above)

**Comment by jiasli** [comment]
Here is a sample of the decoded access token using https://jwt.ms/

```json
{
  "typ": "JWT",
  "alg": "RS256",
  "x5t": "1gg_DNjNKSGnZOxnagXxgAYAY88",
  "kid": "1gg_DNjNKSGnZOxnagXxgAYAY88"
}.{
  "aud": "https://management.adfs.redmond.selfhost.local/81cfafcd-8b9a-4419-9c85-823b54076b55",
  "iss": "https://adfs.redmond.azurestack.corp.microsoft.com/adfs/81cfafcd-8b9a-4419-9c85-823b54076b55/",
  "iat": 1592187157,
  "nbf": 1592187157,
  "exp": 1592190757,
  "unique_name": "xxx@microsoft.com",
  "upn": "xxx@microsoft.com",
  "family_name": "xxx",
  "given_name": "xxx",
  "oid": "S-1-5-21-xxx",
  "tid": "81cfafcd-8b9a-4419-9c85-823b54076b55",
  "hasgroups": "true",
  "appidacr": "0",
  "authmethod": "http://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/windows",
  "AppId": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "apptype": "Public",
  "appid": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "auth_time": "2020-06-15T02:12:25.289Z",
  "ver": "1.0"
}.[Signature]
```

Yes, the `iss` field does have `https://adfs.redmond.azurestack.corp.microsoft.com/adfs/81cfafcd-8b9a-4419-9c85-823b54076b55/`. **However, directly accessing `~/.azure/accessTokens.json` is never officially supported.** It is an internal file used by Azure CLI and should never be parsed directly by the user. Moreover, it will be deprecated once we move to MSAL. 

To get the tenant ID (in such case, `81cfafcd-8b9a-4419-9c85-823b54076b55`) of an ADFS environment, please use the porcelain command `az account show`:

```
> az account show
{
  "environmentName": "redmond",
  "id": "c9b8dfff-aff0-49b5-93bd-a1581f1896a0",
  "isDefault": true,
  "name": "azclidevtools",
  "state": "Enabled",
  "tenantId": "81cfafcd-8b9a-4419-9c85-823b54076b55",
  "user": {
    "name": "xxx@microsoft.com",
    "type": "user"
  }
}
```
