### ISSUE TITLE
webapp: Project type ambiguous when *.csproj and package.json both present.

### ISSUE THREAD

**Issue by bryanwood** [Azure/azure-cli#9787]
### Extension name (the extension in question)
webapp

### Description of issue (in as much detail as possible)
I have a .NET Core Razor Pages project that contains a `package.json` that is used for the client JavaScript dependencies and build. The project type is detected as node.js because of the `package.json` file being present.

-----

Perhaps an argument for specifying the project type to resolve the ambiguity?

**Comment by panchagnula** [comment]
Closing this since for up we don't have plans to support overriding this - please use az webapp create command for now. Thank you.
