### ISSUE TITLE
webapp:Unable to create serviceplan using the CLI (System.Collections.Generic.HashSet`1[System.String])

### ISSUE THREAD

**Issue by liron-navon** [Azure/azure-cli#9792]
version 2.0.62

**Describe the bug**
I'm trying to create an appservice plan using azure cli from the pipeline (azure devops => pipelines => releases => Azure CLI block => inline script), but it doesn't work and throws a very cryptic error message (see "additional context").

Also apparently sku is required, even though the documentation says it's optional.

**To Reproduce**
You can replace the sku here with different types like B1 or "S1" - but none work.
I also tried with different configurations, but it doesn't work with any.
```
az appservice plan create -g MyResourceGroup -n MyPlan --number-of-workers 4 --sku S1 --is-linux
```

[As seen in the documentation
](https://docs.microsoft.com/en-us/cli/azure/appservice/plan?view=azure-cli-latest#az-appservice-plan-create)

**Expected behavior**
A service plan should be created

**Environment summary**
Azure pipeline

**Additional context**
```
2019-06-25T11:51:51.4165536Z ERROR: This version of AppServiceEnvironments only supports System.Collections.Generic.HashSet`1[System.String] Sku(s).
```

**Comment by btardif** [comment]
@panchagnula assigned this to you for current sprint, can you take a look?

**Comment by TechnologyAnimal** [comment]
This may not be applicable here, but wanted to share just in case.  I am using terraform to deploy app service plans into app service environments using Terraform and the AzureRM provider.  Just now I was getting almost exactly the same error message (googling brought me to this issue).  It turns out that the app service plan sku that I was attempting to deploy is not supported in the ASEV2 I deployed.  ASEV2 uses isolated tier, ASEV1 uses premium tier.

**Comment by panchagnula** [comment]
@TechnologyAnimal I am glad you figured out what was causing the failure here. Did running the command with --debug show a useful error message?

**Comment by panchagnula** [comment]
@liron-navon looks like you are trying to use this in a ASE , mostly likely ASE V2?
ASEs don't support B1, standard or shared SKU  see documentation here https://docs.microsoft.com/en-us/azure/app-service/environment/app-service-app-service-environment-intro
