### ISSUE TITLE
--partition-key-path is not always optional 

### ISSUE THREAD

**Issue by git-heath** [Azure/azure-cli#9793]
For the command `az cosmosdb collection create`, the parameter  `--partition-key` is not always optional. If you try and create a collection on a database without this parameter where throughput is configured on the database then the following error is returned.

`Operation Failed: Invalid Arg Shared throughput collection should have a partition key`

I think the documentation should be updated to reflect this scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d791e10-4181-cf15-1398-499eb0918c9c
* Version Independent ID: 2e5f864d-29bd-da4f-b964-a87a39f988c0
* Content: [az cosmosdb collection](https://docs.microsoft.com/en-us/cli/azure/cosmosdb/collection?view=azure-cli-latest#az-cosmosdb-collection-create)
* Content Source: [src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-cosmosdb/azure/cli/command_modules/cosmosdb/_help.py)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by shurd** [comment]
Hi @git-heath thank you for raising this issue. We are currently working on changing the way the CLI manages databases and collections. We will update the documentation as a part of this change. ETA for the change is September 2019, and it is being tracked as work item 416566.

**Comment by shurd** [comment]
Hi, in version 2.0.71 of the CLI, we added a preview version of the new way that databases and collections are managed. As a part of this change, we now have API-specific database and collection create/updates. These new commands provide more guidance for required parameters depending on the API.

**Comment by worleywa7** [comment]
Hello,

I'm experiencing this issue with v2.0.75 of the CLI. According to the documentation this is supposed to be an option, not a strict requirement. Are partition keys a requirement for the creation of a collection now?

**Comment by shurd** [comment]
Hi @worleywa7 which commands are you using? The new commands follow the format `az cosmosdb {api}`

**Comment by burkeholland** [comment]
I'm working with version 2.0.78, and `-p` is a required parameter. How do we then create a collection with a fixed size?
