### ISSUE TITLE
Header check didn't call out which file was in violation

### ISSUE THREAD

**Issue by marstr** [Azure/azure-cli#9798]
After a file was changed in a way that broke the regular expression `azdev` is using to look for headers at the top of source files, the right error message was presented, but without the a list of violating files.

See here: https://travis-ci.org/Azure/azure-cli/jobs/550518820#L590

**Comment by tjprescott** [comment]
This will presumably be fixed once the CI is transitioned to use the stand-alone azdev.

**Comment by yonzhan** [comment]
add to S164.

**Comment by haroldrandom** [comment]
closed as done.
