### ISSUE TITLE
Error when generating signed-in user owned objects

### ISSUE THREAD

**Issue by vjsimha1** [Azure/azure-cli#9800]
## Describe the bug

**Command Name**
`az ad signed-in-user list-owned-objects`

**Errors:**
```
cannot import name 'AppRole' from 'azure.graphrbac.models' (C:\Users\C5096778\Documents\Projects & Initiatives\Azure Policies\Scripts\pes-env\lib\site-packages\azure\graphrbac\models\__init__.py)
Traceback (most recent call last):
lib\site-packages\knack\cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli\core\commands\__init__.py, ln 482, in execute
    self.commands_loader.load_arguments(command)
...
ImportError: cannot import name 'AppRole' from 'azure.graphrbac.models' (C:\Users\C5096778\Documents\Projects & Initiatives\Azure Policies\Scripts\pes-env\lib\site-packages\azure\graphrbac\models\__init__.py)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad signed-in-user list-owned-objects`

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.7.2
Shell: powershell.exe

azure-cli 2.0.66 *

```

**Comment by yugangw-msft** [comment]
The `azure-graphrbac` library is too old. You need to rebuild a new virtual-env and run `pip install`. FYI, our upcoming release should greatly improve the scenario on upgrading from an old version
