### ISSUE TITLE
webapp: roles not specified

### ISSUE THREAD

**Issue by docgregt** [Azure/azure-cli#9803]
Please for each command specify what roles are needed to execute the command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e390289-90cc-30e2-de78-33b080f9c27d
* Version Independent ID: df152c25-2434-0831-46b7-e9d0e3015f06
* Content: [az webapp config hostname](https://docs.microsoft.com/en-us/cli/azure/webapp/config/hostname?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/config/hostname.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config/hostname.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by panchagnula** [comment]
@btardif is there some existing documentation we can point to for RBAC support for our APIs?

In general if a given RBAC acces doesn't work the command throws an error indicating the same.

**Comment by panchagnula** [comment]
please refer to the documentation - closing this since there is nothing we would fix here from CLI command perspective.
