### ISSUE TITLE
Support for custom routes

### ISSUE THREAD

**Issue by mtmargala** [Azure/azure-cli#9806]
Hello, 

Does the az CLI support creating custom routes? It is documented in the SDK here https://docs.microsoft.com/en-us/javascript/api/@azure/arm-network/virtualnetworkgateway?view=azure-node-latest#customroutes

The reason I ask is I am attempting to set up a PTS VPN that allows for connecting to Azure Files only while on the VPN.  According to this doc(https://github.com/Azure-Samples/azure-files-samples/tree/master/point-to-site-vpn-azure-files) it should be possible, but it doesn't look like the CLI supports this at the moment.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e274d7-9619-d96b-4389-8de0883b98e6
* Version Independent ID: 0c402156-30a9-6963-c8d1-64455536c541
* Content: [az network vnet-gateway](https://docs.microsoft.com/en-us/cli/azure/network/vnet-gateway?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-network/azure/cli/command_modules/network/_help.py)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
It is not currently supported. You can track issue #9327 for completion of this feature.
