### ISSUE TITLE
Please map your CLI to the equivalent REST API

### ISSUE THREAD

**Issue by sonnycloudtp** [Azure/azure-cli#9807]
It would be useful if you could map your CLI to the REST API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9abfaa54-0895-29f7-f3bb-ff604912b2ac
* Version Independent ID: d1ff3478-8a86-59e4-62ef-449900132a67
* Content: [az account](https://docs.microsoft.com/en-us/cli/azure/account?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-profile/azure/cli/command_modules/profile/_help.py)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by tjprescott** [comment]
That's not possible since commands often make use of several APIs, and there are also commands that don't use any REST calls.

**Comment by adewaleo** [comment]
I will add that we have a new command [az rest](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-rest) that makes it easier to make http requests on different azure endpoints.
