### ISSUE TITLE
az storage blob service-properties update --set is broken

### ISSUE THREAD

**Issue by sjentzsch** [Azure/azure-cli#9808]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.67

**Describe the bug**
I need to programmatically modify the Diagnostic Settings of a storage account across storage account types, to configure Blob audit logging for example. For this, I want to use the Azure CLI (Terraform provider does not support such). However, while the `show` command works, `update` in combination with `--set` does not. Any time I fire a command, I get the same (old) JSON as a response.

I followed the docs: https://docs.microsoft.com/en-us/cli/azure/storage/blob/service-properties?view=azure-cli-latest#az-storage-blob-service-properties-update

Tested on Azure EU storage account types `StorageV2 (general purpose v2)`, `Storage` and `BlobStorage`.

Also, for `Storage` types we could use `az storage logging`, but `BlobStorage` do not support such, right?

**To Reproduce**
1. Fetch the connection string of your storage acc: `az storage account show-connection-string --name NAME --resource-group RG --subscription SUBSCRIPTION -o tsv`

2. Update something in your blob service-properties: `az storage blob service-properties update --set hourMetrics.enabled=false --force-string --connection-string 'DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=azurewtf;AccountKey=v3vE3JyZAeT13e6kB2LmXF009KhwpV6J6lDfRyBRwabFvXvqjQG7xgJWzFJOsS875Rv4Q563FrdmMnMRyq2mkQ==' --subscription svh-neutral-zone`

**Expected behavior**
I expect either a meaningful response (warning, error, what went wrong?!), or (better!) the updated JSON.

**Environment summary**
Linux Ubuntu 18.04 (Linux-4.15.0-52-generic-x86_64-with-debian-buster-sid), bash, azure-cli 2.0.67, azure cli storage plugin/module 2.4.3, Python 3.6.5

**Comment by limingu** [comment]
Working on the fix. PR will be out soon.
