### ISSUE TITLE
[Discussion] Typing a command group should print its help text by default

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#981]
It would be great if typing a command group (e.g. `az component`, `az network`) would print out the same text that you get when appending the `-h` flag. This would make the already well-documented nature of the CLI feel a little easier to navigate. For example, typing `az network` does in fact print out the list of acceptable commands, but it's a pretty long list, with no help descriptions, and so you really have to add `-h` to make that text usable.

I've always felt like help flags were mostly used for commands (to indicate that you don't want to execute it), and not command groups, and many CLIs special-case "executing" a command group by printing out its pretty-printed help text. For example, if you run `docker network` (or any other group/sub group), you get the full help text, that is analogous to what you'd get by running `az network -h`. It's a subtle difference, but saving a few keystrokes can go a long way when using a CLI a lot :)

This behavior would seem conceptually similar to the fact that simply typing `az` (which is the "root" command group) outputs the print-printed help text for the top-level command groups.

**Comment by mayurid** [comment]
@lostintangent : Thanks for your input. This is something that team has gone back and forth on a bit and decided to stick with a minimalistic approach on a missing value case and providing a detailed help when the user asks for it (by doing -h or --help). This is something we have been looking for feedback from our customers as they use it to see if things are intuitive.
I have marked this as discussion and will talk to the team about this.
//cc @johanste

**Comment by JasonRShaver** [comment]
Same as #574

**Comment by johanste** [comment]
I could be convinced to treat "executing" the command group more like commands than failure/missing command. I assume that this would also mean that the return code for the "group command" would indicate success/0 (today, you'll get a failure/2 return code with the assumption that you made a mistake rather than asked for help)

**Comment by lostintangent** [comment]
@johanste That would be awesome :)

**Comment by lostintangent** [comment]
@johanste Any updates on this discussion?

**Comment by JasonRShaver** [comment]
Cleaning u old issues, reopen if this is still active.
