### ISSUE TITLE
az cosmosdb check-name-exists fails with 500s

### ISSUE THREAD

**Issue by gavinbarron** [Azure/azure-cli#9817]
## Describe the bug

**Command Name**
`az cosmosdb check-name-exists`

**Errors:**
```
request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /providers/Microsoft.DocumentDB/databaseAccountNames/myinspire-staging?api-version=2015-04-08 (Caused by ResponseError('too many 500 error responses',))
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az login`
- `az cosmosdb check-name-exists --name {}`

## Expected Behavior
A true or false is returned without error
## Environment Summary
```
Linux-4.9.125-linuxkit-x86_64-with
Python 3.6.4
Shell: bash

azure-cli 2.0.67
docker image: microsoft/azure-cli@latest
```
## Additional Context

This started happening in our Azure DevOps pipelines today and appears to be persistent. As it has been happening for at least 7 hours.

**Comment by cuvillier** [comment]
I have the same issue.

**Comment by shurd** [comment]
Hi @gavinbarron thank you for reporting this issue. We are looking into it.

**Comment by JeffARose** [comment]
Also experiencing the issue with Python 2.7.5 and azure-cli (2.0.28)

**Comment by nate12o6** [comment]
Im having same issue.

**Comment by shurd** [comment]
Hi all, thank you for your patience. We have corrected the issue and check name calls should be working again.

**Comment by findemor** [comment]
This issue is happening in our GitLab-ci DevOps pipelines and in my local setup.

`az cosmosdb check-name-exists --name ACCOUNTNAME`
Response:
`request failed: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /providers/Microsoft.DocumentDB/databaseAccountNames/ACCOUNTNAME?api-version=2019-08-01 (Caused by ResponseError('too many 500 error responses',))`

I tried login with "az login" and service principal.

I noticed it while I was trying to launch my Terraform plan, this error ocurred and then I tried to debug it:

```
2020/06/02 11:37:09 [ERROR] <root>: eval: *terraform.EvalSequence, err: Error checking if CosmosDB Account "ACCOUNTNAME" already exists (Resource Group "RESOURCEGROUPNAME"): documentdb.DatabaseAccountsClient#CheckNameExists: Failure responding to request: StatusCode=500 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF

Error: Error checking if CosmosDB Account "ACCOUNTNAME" already exists (Resource Group "RESOURCEGROUPNAME"): documentdb.DatabaseAccountsClient#CheckNameExists: Failure responding to request: StatusCode=500 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF

  on main.tf line 40, in resource "azurerm_cosmosdb_account" "db":
  40: resource "azurerm_cosmosdb_account" "db" {
```

I am using version 2.12

```
provider "azurerm" {
  subscription_id = var.SUBSCRIPTION_ID
  tenant_id       = var.SERVICEPRINCIPAL_TENANT_ID
  client_id       = var.SERVICEPRINCIPAL_CLIENT_ID
  client_secret   = var.SERVICEPRINCIPAL_CLIENT_SECRET

  version = "= 2.12"
  features {}
}
```
