### ISSUE TITLE
Allow disabling Key Vault purge protection

### ISSUE THREAD

**Issue by KevinBrooke** [Azure/azure-cli#9818]
We created a key vault with soft delete and purge protection enabled in the wrong region. It is impossible to re-use the key vault name for 90 days. 

Soft delete and purge protection are great as they give an extra "are you sure" steps when deleting a key vault, however a resource that is under a customers control should be able to be purged by setting purge protection to disabled.

We stopped using purge protection to get around this at the moment.

**Comment by jiasli** [comment]
Enabling "soft delete" and "purge protection" are irreversible operations, which is by-design behavior of Key Vault service. You may vote or submit a feedback at https://feedback.azure.com/forums/906355-azure-key-vault/suggestions/37900363-allow-keyvault-purge-when-purge-protection-is-en
