### ISSUE TITLE
[VM] Creating a VM failed midway

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-cli#982]
I attempted to create a VM, as part of an existing resource group, by running `az vm create --image UbuntuLTS -g LinuxTest -n vmtest`, and I got the following error after about 30 seconds:

<img width="1088" alt="screen shot 2016-09-26 at 10 08 16 am" src="https://cloud.githubusercontent.com/assets/116461/18844217/44ab24d6-83d1-11e6-9543-8eb3f66574f1.png">

When looking at my account in the portal, the following resources were created:

<img width="548" alt="screen shot 2016-09-26 at 10 09 33 am" src="https://cloud.githubusercontent.com/assets/116461/18844248/670a1c26-83d1-11e6-8eca-1126baeb1cc3.png">

The location of the resource group in question is `South Central US`, so I'm not sure whether the issue is related to the fact that the NSG was created in `West US` or not. Did I do something wrong here? 

Also, does the CLI do any kind of reconciliation for failed transactions? It seems a little odd that I'd have these network resources left behind for a VM that wasn't even successfully created.

**Comment by tjprescott** [comment]
Yes, this is the same as issue #974.

**Comment by lostintangent** [comment]
@tjprescott Ah! Apologies for opening the dupe. I wasn't sure what exactly to search for :) Out of curiosity, what will be the story moving forward to handling these kind of multi-resource transactions? Will the CLI eventually treat them atomically and do a rollback of any kind if something fails?

**Comment by tjprescott** [comment]
Currently, the plan is to do what ARM does. Since ARM is not transactional, the CLI won't be. There is value to keeping those resources around. If your create fails and you retry, it will detect and attempt to reuse those already created resources. If they were created incorrectly (like the NSG in this case) you would want to delete them before retrying.

**Comment by lostintangent** [comment]
It seems potentially error prone for it to be the responsibility of an end-user to have to identify and then delete any resources that were created "incorrectly" (the NSG in my case), but maybe that's just me.

Just so that I understand, are there any other benefits of keeping the created resources around other then the time savings or not needing to re-create them on subsequent attempts to provision the VM? I appreciate the idempotent behavior of ARM deployments, but in my case, I would have preferred (and found it less confusing) for my account to have been left in clean state. 

I'll close this issue since the core problem is already tracked. Thanks!
