### ISSUE TITLE
Storage Account Firewall Prevents User from Listing Containers

### ISSUE THREAD

**Issue by zhusulai** [Azure/azure-cli#9826]
## Describe the bug
When the storage firewall is set, the user is not able to list containers from outside of the specified IP ranges. This is inconsistent with the behaviour in the portal, which does allow the containers to be listed. The ability to list containers is very important from an administrative perspective.

**Command Name**
`az storage container list`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'CommandResultItem' object is not iterable
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/knack/cli.py", line 212, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/knack/output.py", line 132, in out
    output = formatter(obj)
  File "/usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/knack/output.py", line 38, in format_json
    input_dict = dict(result) if hasattr(result, '__dict__') else result
TypeError: 'CommandResultItem' object is not iterable
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage container list --account-key {} --account-name {}`

## Expected Behavior
Should be able to list containers.

## Environment Summary
```
Darwin-18.5.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.67

Extensions:
dev-spaces 1.0.3

```

**Comment by Juliehzl** [comment]
Thanks for your feedback. We will improve it as soon as possible.

**Comment by yonzhan** [comment]
Storage

**Comment by Juliehzl** [comment]
Hi @zhusulai, please update your azure cli with `az upgrade` and try `az storage container-rm list`.
To use `az storage container-rm` commands, you have to make sure you azure cli version >= 2.13.0.
