### ISSUE TITLE
okay

### ISSUE THREAD

**Issue by musicfreak7** [Azure/azure-cli#9830]
## Describe the bug

**Command Name**
`az devops`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az devops -h`

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.67

Extensions:
azure-devops 0.11.0

```

**Comment by tjprescott** [comment]
Closing due to insufficient information.
