### ISSUE TITLE
az vm encryption enable cross subscriptions (VM/KeyVault)

### ISSUE THREAD

**Issue by ithahn** [Azure/azure-cli#9835]
Hi,
as stated in the document we have tried to following Code:
`az vm encryption enable --resource-group "MyVirtualMachineResourceGroup" --name "MySecureVM" --disk-encryption-keyvault "MySecureVault" --key-encryption-key "MyKEK_URI" --key-encryption-keyvault "MySecureVaultContainingTheKEK" --volume-type "All"
`

When we use this in the Cloud Shell we get the following error:
`Resource Group "MySecureVault" Cloud not be found.
`

I Need to say that the VM and the KeyVault are in different subscriptions.
The KeyVault got all needed Access policies enabled. So this can't be the issue.

Can someone please support on this issue?

Thanks,
Klaus

**Comment by tjprescott** [comment]
If the KeyVault is in a different subscription, please try supplying the full ARM ID to that KeyVault. That should work for your scenario.

**Comment by ithahn** [comment]
Thanks,

I think the ARM ID is looking like that right?
`/subscriptions/21c4d411-837a-4992-b97c-bed123456789/resourceGroups/RESOURCEGROUPNAME/providers/Microsoft.KeyVault/vaults/KeyVaultName`

If yes, we have tried that already with the above error message appearing in the Cloud Shell.

Regards,
Klaus

**Comment by RalfWenzel** [comment]
I can confirm the issue. It seems that the resource group of the keyvault is never found if in other subscription. We tried other forms of command also, i.e specifying full id of vm, but always same result.

**Comment by adewaleo** [comment]
Hello everyone I was able to reproduce this issue. From running the encryption command with --debug. It turns out that during validation the CLI does not factor in the keyvault's subscription id when retrieving the kv.

I will look into fixing this

**Comment by ithahn** [comment]
Hi,
any update on this topic please?

Meanwhile I have tested that the same behaviour appears if you just use powershell with the Az Cmdlets.

Thanks,
Klaus

**Comment by adewaleo** [comment]
Hello, unfortunately I am no longer on the CLI team. Now in ACR. I will forward this to the team to see if someone can pick up this issue.

**Comment by qwordy** [comment]
I reproduce your problem. I find the related code. Azure CLI checks whether subscriptions match. If not, it raises an error. It also verifies region match. So, it is by design now.

@yugangw-msft Do you think Azure should support such cross subscription operations?

**Comment by RalfWenzel** [comment]
@qwordy From our experience: The command fails also, if the keyvault is in another resource group but in the same subscription (as the vm to be protected). Can you please review your finding?

**Comment by adewaleo** [comment]
I apologize for not looking into this issue more carefully. However Azure Disk Encryption has the following requirement:

"Azure Disk Encryption requires that your key vault and VMs reside in the same Azure region and subscription. Configuring the resources in separate regions causes a failure in enabling the Azure Disk Encryption feature." - [ADE prerequisites doc](https://docs.microsoft.com/en-us/azure/security/azure-security-disk-encryption-prerequisites#supported-operating-systems).

So this scenario is not supported by the Disk Encryption service.

I will leave it to @qwordy and @yugangw-msft  to follow up. But doesn't look like much might be done from the CLI side except possibly more clarification, documentation or client side validation to make it clear when the user uses a KV in a diff sub or region.
