### ISSUE TITLE
issues using azure cli with blob storage

### ISSUE THREAD

**Issue by samuda2019** [Azure/azure-cli#9836]
## Describe the bug

**Command Name**
`az storage blob download`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob download --container-name {} --output {} --account-name {} --sas-token {} --name {} --file {}`

## Environment Summary
```
Windows-2012ServerR2-6.3.9600-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.67

```

**Comment by samuda2019** [comment]
C:\Users\sxa100601>az storage blob list --container-name dware-tst --output table --account-name driattunityblob --sas-token xxxx 
The command failed with an unexpected error. Here is the traceback:

HTTPSConnectionPool(host='driattunityblob.blob.core.windows.net', port=443): Max
 retries exceeded with url: /dware-tst?sv=2018-03-28&sv=2018-03-28&sv=2018-03-28
&sv=2018-03-28&restype=container&comp=list&maxresults=5000 (Caused by SSLError(S
SLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate'
, 'certificate verify failed')],)",),))
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-v0p8dbpk\urllib3\urllib
3\contrib\pyopenssl.py", line 456, in wrap_socket
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\pyOpenSSL\Open
SSL\SSL.py", line 1915, in do_handshake
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\pyOpenSSL\Open
SSL\SSL.py", line 1647, in _raise_ssl_error
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\pyOpenSSL\Open
SSL\_util.py", line 54, in exception_from_error_queue
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certific
ate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-v0p8dbpk\urllib3\urllib
3\connectionpool.py", line 600, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-v0p8dbpk\urllib3\urllib
3\connectionpool.py", line 343, in _make_request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-v0p8dbpk\urllib3\urllib
3\connectionpool.py", line 839, in _validate_conn
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-v0p8dbpk\urllib3\urllib
3\connection.py", line 344, in connect
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-v0p8dbpk\urllib3\urllib
3\util\ssl_.py", line 347, in ssl_wrap_socket
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-v0p8dbpk\urllib3\urllib
3\contrib\pyopenssl.py", line 462, in wrap_socket
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certi
ficate', 'certificate verify failed')],)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-wl9gly17\requests\reque
sts\adapters.py", line 449, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-v0p8dbpk\urllib3\urllib
3\connectionpool.py", line 638, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-v0p8dbpk\urllib3\urllib
3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='driattunityblob.blob
.core.windows.net', port=443): Max retries exceeded with url: /dware-tst?sv=2018
-03-28&sv=2018-03-28&sv=2018-03-28&sv=2018-03-28&restype=container&comp=list&max
results=5000 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines'
, 'tls_process_server_certificate', 'certificate verify failed')],)",),))

During handling of the above exception, another exception occurred:

**Comment by limingu** [comment]
@samuda2019 , try the command as 'az storage blob download --container-name {} --output {} --account-name {} --name {} --file {}'.

Reomve the sas-token parameter to see if it works. Let me know if that works for you. Thanks.

**Comment by Juliehzl** [comment]
@samuda2019  does it work now?

**Comment by samuda2019** [comment]
@Juliehzl @limigu I removed the sas token and it prompted me to run az login. After I entered the credentials and got authenticated it listed my subscriptions but still gave the same error when I ran the below command

You have logged in. Now let us find all the subscriptions to which you have access...
  {
    "cloudName": "AzureCloud",
..................
az storage blob list --container-name dware-tst --output table --account-name driattunityblob

The command failed with an unexpected error. Here is the traceback:

HTTPSConnectionPool(host='driattunityblob.blob.core.windows.net', port=443): Max retries exceeded with url: /dware-tst?restype=container&comp=list&maxresults=5000 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

**Comment by yonzhan** [comment]
add to S164.

**Comment by Juliehzl** [comment]
@samuda2019, what about your problem now? If no sas token, cli command will try to authenticate the storage client according to your login information. You need to make sure the target storage account in your account default subscription.
But with sas token, you don't need to login. According to the debug information, you sas token may be not valid. How do you get the sas token and can you check if it is valid through browser first?
