### ISSUE TITLE
az network watcher test-ip-flow has unexpected error

### ISSUE THREAD

**Issue by adammodlin** [Azure/azure-cli#9844]
I am trying to use `az network watcher test-ip-flow` to diagnose RDP failures to an Azure VM. When I ran the command, I got an error.

**Command Name**
`az network watcher test-ip-flow`

**Errors:**
```
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
Temp\pip-install-wl9gly17\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 566, in execute
azure\cli\core\commands\__init__.py, ln 624, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 617, in _run_job
Local\Temp\pip-install-wl9gly17\six\six.py, ln 693, in reraise
azure\cli\core\commands\__init__.py, ln 594, in _run_job
azure\cli\core\commands\__init__.py, ln 303, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 470, in default_command_handler
azure\cli\command_modules\network\custom.py, ln 3047, in check_nw_ip_flow
ValueError: not enough values to unpack (expected 2, got 1)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az network watcher test-ip-flow --direction {} --protocol {} --local {} --remote {} --vm {} --resource-group {}`

## Expected Behavior
I expected to get the output of the command.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.67

```
## Additional Context
You can contact me via my Microsoft alias `admodlin` and I'll share the specifics of the command.

**Comment by MyronFanQiu** [comment]
@adammodlin Hello, could you share the content of the `local` field you are setting? It should be something like `x.x.x.x:port`. If you don't have `:` in the `local`, it will fail. If this is the situation you met, I will make the code more robust and throw out useful error message. If not, let us figure out what's the root cause together.

**Comment by MyronFanQiu** [comment]
@adammodlin Hello. Did your solve your issue? I plan to create a PR to make the code more robust. If it's not the root cause, please let me know.

**Comment by adammodlin** [comment]
@MyronFanQiu I believe I had already included the port in that field. I'll make a note to verify it when I get a chance.

**Comment by adammodlin** [comment]
@MyronFanQiu Perhaps I'm misunderstanding what this command can do. I'm trying to verify connectivity from my local machine (laptop) to an Azure VM. Connectivity is not working due to NSG rules and I'm trying to find out which rule. Is this a scenario supported by this tool?

**Comment by MyronFanQiu** [comment]
@adammodlin Sorry for the delay. I think this scenario is supported by this tool. You should provide both local port and remote port.

**Comment by MyronFanQiu** [comment]
or you can provide x.x.x.x:*

**Comment by adammodlin** [comment]
Thanks @MyronFanQiu. I'll give that a shot.
