### ISSUE TITLE
az network watcher test-ip-flow fails without resource group and displays bad error

### ISSUE THREAD

**Issue by adammodlin** [Azure/azure-cli#9845]
When running the below command, it should work according to the docs [here](https://docs.microsoft.com/en-us/cli/azure/network/watcher?view=azure-cli-latest#az-network-watcher-test-ip-flow). The docs state that the `--resource-group` parameter is optional.

The second issue is that when this command fails, the incorrect parameter name is used in the failure message. The output is:

```
usage: az network watcher test-ip-flow [-h] [--verbose] [--debug]
                                       [--output {json,jsonc,table,tsv,yaml,none}]
                                       [--query JMESPATH] --vm VM --direction
                                       {Inbound,Outbound} --protocol
                                       {Tcp,Http,Https,Icmp} --local LOCAL
                                       --remote REMOTE
                                       **[--resource-group RESOURCE_GROUP_NAME]**
                                       [--nic NIC]
                                       [--subscription _SUBSCRIPTION]
az network watcher test-ip-flow: error: Parameter '**resource_group_name**' can not be None.
```

**Command Name**
`az network watcher test-ip-flow`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az network watcher test-ip-flow --direction {} --protocol {} --local {} --remote {} --vm {}`

## Expected Behavior
The command should work according to the documentation. Either the docs need to be updated or the command should not require resource group. Also, when this fails, it should show the correct parameter name.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.67

```
## Additional Context
None

**Comment by MyronFanQiu** [comment]
@adammodlin Hello, I checked the code. Now, If you provide the resource id of the vm, it doesn't need the `resource_group_name`. If you provide the name of the vm, it need the `resource_group_name`. The help information is a little bit unclear for now. Besides, I want to have a discussion about how to deal with such question? @tjprescott Is there any way like `required_if` to solve the dependency between several parameters?

**Comment by tjprescott** [comment]
@MyronFanQiu there is a helper method called `validate_parameter_set` in `azure.cli.core.commands.validators` that can assist here.

**Comment by MyronFanQiu** [comment]
@tjprescott Thanks. I will have a try.

**Comment by MyronFanQiu** [comment]
@adammodlin Hello. I have updated the help information and added check for these two arguments. Could we close this issue?

**Comment by adammodlin** [comment]
Yes, thank you!
