### ISSUE TITLE
Private DNS link vnet from different tenant

### ISSUE THREAD

**Issue by tleepa** [Azure/azure-cli#9851]
## Describe the bug
I have two tenants (_tenant1_, _tenant2_). Each tenant has a subscription (_sub1_, _sub2_), resource group (_rg1_, _rg2_), vnets (_vnet1_, _vnet2_). I am able to create a peering between _vnet1_ and _vnet2_ using the IAM roles configured (added user from _tenant1_ to _rg2_ with Network Contributor role)
I am trying to register _vnet2_ as a resolution network (old nomenclature) to the private zone created in _sub1_. Tried both previous and current preview version of Private DNS zone feature - both failing with similar messages.
Documentation only specifies permissions necessary to create vnet peering between different tenants - Network Contributor. Do I need any other permissions?

Is it possible at all?

`az account list` for _user1_:
``` json
[
  {
    "cloudName": "AzureCloud",
    "id": "_sub1_",
    "isDefault": true,
    "name": "Visual Studio Enterprise",
    "state": "Enabled",
    "tenantId": "_tenant1_",
    "user": {
      "name": "_user1_",
      "type": "user"
    }
  },
  {
    "cloudName": "AzureCloud",
    "id": "_sub2_",
    "isDefault": false,
    "name": "_sub2-name_",
    "state": "Enabled",
    "tenantId": "_tenant2_",
    "user": {
      "name": "_user1_",
      "type": "user"
    }
  }
]
```

**Command Name**
`az network private-dns link vnet create`

**Errors:**
```
The client has permission to perform action 'Microsoft.Network/virtualNetworks/join/action' on scope '/subscriptions/_sub1_/resourceGroups/_rg1_/providers/Microsoft.Network/privateDnsZones/_zonename_/virtualNetworkLinks/_vnet1_', however the current tenant '_tenant1_' is not authorized to access linked subscription '_sub2_'.
```

## To Reproduce:
az network private-dns link vnet create --resource-group _rg1_ --name _linkname_ --zone-name _zonename_ --virtual-network /subscriptions/_sub2_/resourceGroups/_rg2_/providers/Microsoft.Network/virtualNetworks/_vnet2_ --registration-enabled false --subscription _sub1_

**Comment by tjprescott** [comment]
@dijyotir for comment

**Comment by MyronFanQiu** [comment]
@dijyotir Hello. Any update?

**Comment by dijyotir** [comment]
@MyronFanQiu Hi, this functionality is right now only available in Portal. Right now CLI and Powershell does not support this functionality.

**Comment by MyronFanQiu** [comment]
@tleepa Should I change this issue into a feature request?

**Comment by tleepa** [comment]
@MyronFanQiu Yes, please. Thank you.

**Comment by roblohmann** [comment]
@dijyotir i'm not quite sure if this is the correct place to ask this question. But i'm working with the Azure CLI to link a VNET to a private DNS as well. However, my VNET is in a different resource group than the Private DNS is, and I suspect that this is giving me the following error: 

_'Can not perform requested operation on nested resource. Parent resource 'my-zone-name' not found.'_

Could this have to do something with this feature request as well?

**Comment by dijyotir** [comment]
@roblohmann The error seems to suggest that you are trying to create a virtual network link under a private zone but that zone doesn't exist.

**Comment by roblohmann** [comment]
> @roblohmann The error seems to suggest that you are trying to create a virtual network link under a private zone but that zone doesn't exist.

That was also my inital thought, however I'm sure it exists and linking the VNET to the Private DNS Zone through the portal is not an issue. I just see that I got a response on Stackoverflow to my question regarding this issue, so I'll see what that brings. Otherwise I'll open a new tread here I think.

**Comment by roblohmann** [comment]
> > @roblohmann The error seems to suggest that you are trying to create a virtual network link under a private zone but that zone doesn't exist.
> 
> That was also my inital thought, however I'm sure it exists and linking the VNET to the Private DNS Zone through the portal is not an issue. I just see that I got a response on Stackoverflow to my question regarding this issue, so I'll see what that brings. Otherwise I'll open a new tread here I think.

For future references: Got the answer on Stackoverflow, had to get the virtual network id and pass that in. Also see https://stackoverflow.com/a/59384739/291293

**Comment by randy2ner** [comment]
I'm not sure if this solution was available due to the bug filed, but I ran into the same problem.  By doing this through PowerShell using New-AzPrivateDnsVirtualNetworkLink there is a parameter called -RemoteVirtualNetworkId you can use to reference a VNET in a different tenant.
