### ISSUE TITLE
scripts/ci/dependency_check.bat doesn't fail CI, even when it detects errors.

### ISSUE THREAD

**Issue by marstr** [Azure/azure-cli#9853]
If you check #9750, you'll see that CI fails dependency checks for Darwin and Linux, however the Windows check passes. Digging in, it's clear that the Windows script even detects the error here: [Build 60891, Verify src/azure-cli/requirements.*.Windows.txt, Line 342](https://dev.azure.com/azure-sdk/public/_build/results?buildId=60891&view=logs&j=796343fd-f04d-59ce-7e73-c4eab21e4249&t=3e5b4737-4f47-5027-dc25-be482d8c1eaf&l=342). However, the appropriate exit code isn't getting set.

**Comment by yonzhan** [comment]
@haroldrandom add to next Sprint.

**Comment by haroldrandom** [comment]
Fix at #11094. Feel free to reopen if there are futher problems.
