### ISSUE TITLE
Add support for JIT requests from Azure CLI

### ISSUE THREAD

**Issue by stewartadam** [Azure/azure-cli#9855]
**Is your feature request related to a problem? Please describe.**
JIT policy management is supported by Azure CLI (`az security jit-policy`) but JIT requests cannot be created or managed from the Azure CLI without manually constructing the API call for use with `az rest`.

**Describe the solution you'd like**
Something like `az security jit-request` to programmatically create, read, update, delete, and approve JIT requests.

**Describe alternatives you've considered**
Obtaining the VM resource ID, manually constructing the request URI and body per our [API docs](https://docs.microsoft.com/pt-pt/rest/api/securitycenter/jitnetworkaccesspolicies/initiate?view=powerbiaspnetwf-1.1.10#initiate-an-action-on-a-jit-network-access-policy)
```sh
URL="https://management.azure.com/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/microsoft.Security/locations/$RG_LOCATION/jitNetworkAccessPolicies/default/Initiate?api-version=2015-06-01-preview"
BODY=<...> # per https://docs.microsoft.com/pt-pt/rest/api/securitycenter/jitnetworkaccesspolicies/initiate?view=powerbiaspnetwf-1.1.10#initiate-an-action-on-a-jit-network-access-policy
az rest --method post --uri "$URL" --body "$BODY"
```

**Comment by chrisvugrinec** [comment]
any news about this issue?

**Comment by ronari2** [comment]
Hello, We have added it to our backlog. No ETA at this stage. Thanks, Ronen

**Comment by JasonHaley** [comment]
Was this completed? Its not clear why it was closed.

**Comment by joelw** [comment]
Love the idea! I couldn't get the method in the original request to work, but came up with the following method by looking at the requests that Azure Portal makes:

```
jit() {
  IP=$(curl -s https://ifconfig.me/ip)
  VM="your vm name here"
  RG="your vm resource group here"
  IFS=$'\r\n' command eval 'VMDETAILS=($(az vm show -g $RG -n $VM -o tsv --query "[id, location]"))'

  VMID="${VMDETAILS[0]}"
  LOCATION="${VMDETAILS[1]}"
  SUB=$(echo $VMID | cut -d \/ -f 3)
  ENDPOINT="https://management.azure.com/subscriptions/$SUB/resourceGroups/$RG/providers/Microsoft.Security/locations/japaneast/jitNetworkAccessPolicies/default/initiate?api-version=2015-06-01-preview"

  BODY=$(cat <<'END'
{"requests":[{"content":{"virtualMachines":[{"id":"VMID","ports":[{"number":3389,"duration":"PT3H","allowedSourceAddressPrefix":"MYIP"}]}]},"httpMethod":"POST","name":"8f6b5ca7-ff45-4476-b623-53a0a2beeae9","requestHeaderDetails":{"commandName":"Microsoft_Azure_Compute."},"url":"ENDPOINT"}]}
END
)
  BODY=${BODY/MYIP/$IP}
  BODY=${BODY/VMID/$VMID}
  BODY=${BODY/ENDPOINT/$ENDPOINT}
  echo $BODY

  URL="https://management.azure.com/batch?api-version=2015-11-01"
  az rest --verbose --method post --uri "$URL" --body "$BODY"
}
```

**Comment by bordera-randy** [comment]
Any update on this?

**Comment by Iain-S** [comment]
Any update on when this feature will be added?

**Comment by moizahmedtuc** [comment]
As an alternative to Azure CLI, here’s how I successfully implemented JIT access using Azure PowerShell:

Define $resourceGroup, $vmName and $Location in your script.

**Step 1: Authenticate with Azure**

`Connect-AzAccount`

And if you don't want to authenticate via browser always. I think there's a way to do this. But, I know how to do this if you're using service principal.

```
$securePassword = ConvertTo-SecureString -String $Env:ARM_CLIENT_SECRET -AsPlainText -Force
    $credential = New-Object System.Management.Automation.PSCredential ($Env:ARM_CLIENT_ID, $securePassword)
    $connectAZ = Connect-AzAccount -ServicePrincipal -Credential $credential -Tenant $Env:ARM_TENANT_ID
```

**Step 2: Fetch Public IP of the Requesting Machine**

`$myPublicIP = Invoke-RestMethod -Uri "https://ifconfig.me"`

**Step 3: Define VM and JIT Policy Parameters**

Define Resource Group, VM name, and location where JIT access needs to be applied:

`$vmResourceId = "/subscriptions/$Env:ARM_SUBSCRIPTION_ID/resourceGroups/$resourceGroup/providers/Microsoft.Compute/virtualMachines/$vmName"`

**Step 4: Remove Existing JIT Policy (optional)**

```
$existingPolicy = Get-AzJitNetworkAccessPolicy -ResourceGroupName $resourceGroup -Location $Location -Name "default" -ErrorAction Stop
    Remove-AzJitNetworkAccessPolicy -ResourceGroupName $resourceGroup -Name "default" -Location $Location -Confirm:$false
```

**Step 5: Apply New JIT Policy**

Define the JIT policy allowing specific ports for a limited duration.

```
$jitPolicy = @(
    @{
        id = $vmResourceId
        ports = @(
            @{number = 22; protocol = "*"; allowedSourceAddressPrefix = @("*"); maxRequestAccessDuration = "PT2H"},
            @{number = 8080; protocol = "*"; allowedSourceAddressPrefix = @("*"); maxRequestAccessDuration = "PT2H"}
        )
    }
)

$JitPolicyArr = @($jitPolicy)

    Set-AzJitNetworkAccessPolicy -Kind "Basic" -Location $Location -Name "default" -ResourceGroupName $resourceGroup -VirtualMachine $JitPolicyArr
```

**Step 6: Request JIT Access**

Once the policy is set, I request access for my IP for the next 1 hour:

```
$MyResource = Get-AzResource -Id $vmResourceId
$EndTimeUtc = (Get-Date).ToUniversalTime().AddHours(1).ToString("o")

$JitPolicyVm1 = (@{
        id    = $MyResource.ResourceId;
        ports = @(
        @{ number = 22; endTimeUtc = $EndTimeUtc; allowedSourceAddressPrefix = @($myPublicIP) },
        @{ number = 8080; endTimeUtc = $EndTimeUtc; allowedSourceAddressPrefix = @($myPublicIP) }
    ) 
    })
$ActivationVM = @($JitPolicyVm1)

Write-Host "INFO: Requesting Just-in-Time access..."
try {
    Start-AzJitNetworkAccessPolicy -ResourceGroupName $resourceGroup -Location $Location -Name "default" -VirtualMachine $ActivationVM
    Write-Host "INFO: JIT access granted for IP: $myPublicIP"
} catch {
    Write-Host "ERROR: Failed to request JIT access. Exiting script."
    exit 1
}
```

After running this script: Just-in-Time (JIT) access is applied and only my public IP can access the VM on the defined ports and access expires automatically after 1 hour.

I hope this works.
