### ISSUE TITLE
az network nsg cmdlet does not show destinationportrange for port 22

### ISSUE THREAD

**Issue by villanub** [Azure/azure-cli#9858]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
az network nsg cmdlet does not show destinationportrange for port 22, all other ports show correctly. Same issue with Get-AzureRmNetworkSecurityGroup

**To Reproduce**
Create a rule that has the Destination Port Range with 22

![image](https://user-images.githubusercontent.com/11998436/60628974-793c0d00-9db9-11e9-8eed-ce560ce15930.png)

Query the rule using either az network nsg show or Get-AzureRmNetworkSecurityGroup

![image](https://user-images.githubusercontent.com/11998436/60629049-c28c5c80-9db9-11e9-9f1d-ce04ec4e409e.png)

**Expected behavior**
All ports shown in UI should be output in CLI cmdlets, issue only affects port 22 for some reason.

**Environment summary**
Powershell script and bash script.

**Additional context**

**Comment by tjprescott** [comment]
The fact that this affects both CLI and Powershell suggests a service-level problem.

**Comment by allegradomel** [comment]
Hi @villanub, we weren't able to reproduce your issue. Are you using the updated versions of CLI and Powershell? Here are the steps we followed: 

![nsg_rule](https://user-images.githubusercontent.com/17442871/62810986-df046e80-bab4-11e9-8acf-7d45e4e2c79d.PNG)
![az_network_command](https://user-images.githubusercontent.com/17442871/62810999-e75ca980-bab4-11e9-958c-36c1db940e5b.PNG)
And the result:
![cli_screenshot](https://user-images.githubusercontent.com/17442871/62811027-fe9b9700-bab4-11e9-9fcc-dfc739a4183e.PNG)

Are you still experiencing this issue?

**Comment by MyronFanQiu** [comment]
@villanub Ping

**Comment by villanub** [comment]
I tested this morning and do not experience this issue any more. Looks like all is reporting correctly now.
