### ISSUE TITLE
Poor access token management in accessTokens.json

### ISSUE THREAD

**Issue by DrEsteban** [Azure/azure-cli#9859]
## Describe the bug

**Command Name**
`az login`/`az logout`

**Errors:**
No errors per-se, but I've noticed the AzCLI doesn't really manage the tokens obtained in accessTokens.json.  If an access_token/refresh_token expires, it will never be removed.  The list is simply appended to.

Also, when you run `az logout`, nothing is done to invalidate any active sessions or mark the refresh_token as unusable.  The accessTokens.json file is simply cleared of all tokens for the current user***.

***This is another oddity.  `az logout` doesn't clear the whole accessTokens.json file, only the tokens associated with the current login.  Additionally, if you `az login` to a new account, all the access tokens of your previous account remain.  So its very easy to accumulate tokens for multiple accounts in accessTokens.json if you never run `az logout` and only do `az login` over and over to switch accounts.

## To Reproduce:
**Multiple account tokens**
>1. `az login` account X
>1. `az login` account Y

Tokens for both accounts will be present in accessTokens.json.

**Never cleared access_tokens/refresh_tokens**
>1. `az login`
>1. Wait long enough for the access_token/refresh_token to expire
>1. Perform an operation that refreshes the tokens

Expired tokens will remain in accessTokens.json

**`az logout` behavior**
>1. `az login` account X
>1. `az login` account Y
>1. `az logout`

The access tokens for account X will remain in accessTokens.json

**Poor logout security hygiene**
>1. `az login`
>1. Make a copy of accessTokens.json
>1. `az logout`
>1. `az login`
>1. Replace copy of accessTokens.json

access_token and refresh_token from previous "session" continue to work. The AzCLI never calls out to AAD to invalidate the session.

## Expected Behavior
Better token management.

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.64 *

Extensions:
dev-spaces 1.0.1

```

**Comment by marstr** [comment]
Howdy @DrEsteban,

We're actually not happy with the way that this is handled at all right now. For that reason, as well as supporting single-sign-on with Visual Studio and Azure PowerShell, we're in the middle of overhauling the way that we store tokens altogether. You can checkout an older preview version with the overhauled approach in the [`msal` branch](https://github.com/Azure/azure-cli/tree/msal), or checkout the under-pinning over at https://github.com/AzureAD/microsoft-authentication-library-for-python and https://github.com/AzureAD/microsoft-authentication-extensions-for-python
