### ISSUE TITLE
Add a new way to list webapp instances

### ISSUE THREAD

**Issue by Socolin** [Azure/azure-cli#9862]
Hey

I'm looking for a way to get instances information of a webapp with a command like `az webapp instance list`.

On https://resources.azure.com the given url to this is:
```
https://management.azure.com/subscriptions/{SubscriptionId}/resourceGroups/{RessourceGroupName}/providers/Microsoft.Web/sites/{AppName}/instances?api-version=2018-02-01
```

Regards

**Comment by btardif** [comment]
@Socolin we reviewed your question during our triage and would like to get a few more details.

what are you planning on using the instanceID for?

If you can share the scenario you have in mind, this would help prioritize/design a solution or point you in the direction of existing scenarios that can address this ask.

**Comment by Socolin** [comment]
It's to ping each instance of our webapp before swapping between deployments slots.

Since some time we have random errors (like invalid dll or other wtf messages) on one instance that are fixed be rebooting the webapp, we want to ensure that all instance are working before swapping, to do so we want to use the affinity cookie with the instance name. instead of spamming to be sure to hit all the instances.

Also we experienced some problem with warmup lately and we want to be sure that the webapp is fully warmed up on all instance before swapping.

**Comment by btardif** [comment]
@Socolin there might be a better solution for this, I need to dig up some documentation, but I'll add it here.

**Comment by btardif** [comment]
@Socolin  this is the feature that I think will be a better solution for you. We are still in the process of building it, but it will let you set a health ping to a specific route in your app/slot and report health across instances.

https://github.com/projectkudu/kudu/wiki/Health-Check-%28Preview%29
