### ISSUE TITLE
Unable to list containers without access to storage account keys

### ISSUE THREAD

**Issue by zhusulai** [Azure/azure-cli#9863]
## Describe the bug
`az storage container list` fails when the user just has Reader role. This is inconsistent with the behavior in the portal as I was able to list the containers and view their properties such as access level.

**Command Name**
`az storage container list`

**Errors:**
`az storage container list: error: Azure Error: AuthorizationFailed
Message: The client 'email@org.com' with object id '29b05c5c-b498-zzzz-acf8-7046f26eb2ac' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '/subscriptions/efbf00f6-e9c5-zzzz-a9bd-c82895ef93d3/resourceGroups/somerg/providers/Microsoft.Storage/storageAccounts/someaccount'.`

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage container list --account-name {}`

## Expected Behavior
Should be able to list the containers and view their properties.

## Environment Summary
```
Darwin-18.5.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.67 *

Extensions:
dev-spaces 1.0.3

```

**Comment by Juliehzl** [comment]
Please try to use `az storage container list --account-name {} --auth-mode login`.

**Comment by Juliehzl** [comment]
Sorry for late response. CLI team is in transition process in the past few months. I will try to fix it when available as soon as possible.

**Comment by zhusulai** [comment]
@Juliehzl Thank you. FYI, I tried your previous suggestions of setting `--auth-mode login` and it did work.

**Comment by Juliehzl** [comment]
Sounds good! In this way, I will close this issue and if you still have any problem when using azure cli, feel free to open a new one.
