### ISSUE TITLE
az group create: error: the following arguments are required: --location/-l

### ISSUE THREAD

**Issue by geebee3** [Azure/azure-cli#9864]
I am using cli command for azure on my MacOs, everything is up to date, while trying to use the command: `az group create -n PimpUrPoochRG -1 USEast 
` i get an error message that says "az group create: error: the following arguments are required: --location/-l"

please if someone could help me promptly on this, i'm using bash cli on my macbook pro (july 4th, 2019)

**Comment by LarsSkovslund** [comment]
Your `location` is invalid, please run `az account list-locations` to see available locations.

It should be `az group create -n PimpUrPoochRG -l eastus`

**Comment by tjprescott** [comment]
Well, it looks like you are using `-1`(one) instead of `-l`(el)

**Comment by geebee3** [comment]
thank you guys, it works now, was using 1 instead of l.
