### ISSUE TITLE
Not possible to change appservice plan for existing webapp

### ISSUE THREAD

**Issue by LarsSkovslund** [Azure/azure-cli#9865]
## Describe the bug
With version 2.0.67 of Azure CLI a [pre-validation](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?toc=%2Fcli%2Fazure%2Ftoc.json&bc=%2Fcli%2Fazure%2Fbreadcrumb%2Ftoc.json&view=azure-cli-latest#appservice-1) on webapp name was introduced, preventing the command from executing when a webapp with the same name exists. Effectively blocking for scenarios such as changing a webapps appservice plan.

> This is a `[BREAKING CHANGE]` and should be marked as such in the change log.

This also goes against the command [guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md#standard-command-types) that states that all `CREATE` commands should be idempotent. We use `Azure CLI` for CI/CD to provision all resources and is heavily dependent on `create` commands being idempotent. 

**Command Name**
`az webapp create`

**Errors:**
```
The site with name [xxx] already exists in resource group [xxx].
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- For any existing webapp
- `az webapp create --resource-group {} --name {} --plan {}`

## Expected Behavior
As stated in the [guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md#standard-command-types), `CREATE` command should be idempotent, thus expecting it to execute regardless of the existence of a webapp with the same name.
## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.68

Extensions:
azure-devops 0.11.0
mesh 0.10.6

```

**Comment by tjprescott** [comment]
@yugangw-msft I believe you already fixed this, yes?

**Comment by tjprescott** [comment]
@LarsSkovslund I believe this has already been fixed in: https://github.com/Azure/azure-cli/pull/9847.  cc/ @panchagnula

**Comment by yugangw-msft** [comment]
@tjprescott, that is correct. The fix will be released on July 16

**Comment by LarsSkovslund** [comment]
Thanks, really appreciate it

**Comment by benverlinden30** [comment]
Hi all,

Currently all of our releases (hosted agent vs2019) are failing because of this issue in azure cli.
I have set the tasks on app service plan create and app service create on continue on error but
now im facing issues with web app deploy task as well because the app service stays in a running state

So we have to wait for one week until this fix will be pushed to the master?


Grtz,
Ben
