### ISSUE TITLE
Bug during az webapp up -n

### ISSUE THREAD

**Issue by hyochan** [Azure/azure-cli#9870]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 575, in execute
    raise ex
cli/core/commands/__init__.py, ln 633, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 624, in _run_job
    cmd_copy.exception_handler(ex)
...
lib/python3.7/json/__init__.py, ln 348, in loads
    return _default_decoder.decode(s)
lib/python3.7/json/decoder.py, ln 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
lib/python3.7/json/decoder.py, ln 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up -n {}`

## Environment Summary
```
Darwin-18.6.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.68

```

**Comment by panchagnula** [comment]
@hyochan  need some more information here to debug this.
Are you using this command for the first time? Are you running the command from the directory path where your code is hosted.?

You can run the command with --debug flag & check what info it gives? Also, feel free to share that information (--debug info) with me directly at sisirap@microsoft.com.thank you.

**Comment by hyochan** [comment]
@panchagnula Thanks for the feedback. After a few test & trials myself, it magically worked again. I was wondering why it isn't guiding me any `logs` but yes there is a flag `--debug`. Thanks, I will try to re-report issue when I can clarify this.
