### ISSUE TITLE
Issue with "az vm image list --output table" command

### ISSUE THREAD

**Issue by sanju918** [Azure/azure-cli#9879]
## Describe the bug

**Command Name**
`az vm image list`

**Errors:**
```
HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
Traceback (most recent call last):
urllib3\urllib3\contrib\pyopenssl.py, ln 456, in wrap_socket
pip-install-v1m4qsu_\pyOpenSSL\OpenSSL\SSL.py, ln 1915, in do_handshake
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm image list --output {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.64

```

**Comment by yugangw-msft** [comment]
This is not specific to the image list command.
It is more likely you are running behind a proxy. Please refer to the [doc](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy) for help.
Please reactivate if it doesn't resolve the problem.
