### ISSUE TITLE
Repository update to include release for Debian 10 (Buster)

### ISSUE THREAD

**Issue by davivcgarcia** [Azure/azure-cli#9880]
Debian 10 (Buster) was officially released on July 6th (https://www.debian.org/News/2019/20190706), and it is the current stable release for the distribution. There isn't a compatible repository at https://packages.microsoft.com/repos/azure-cli/dists/ yet.

**Comment by marstr** [comment]
I'm moving to a new team after this week, but we should definitely start publishing for buster.

**Comment by sitewards-tkaplonski** [comment]
Any forecast about when support for buster would be introduced?

**Comment by swaechter** [comment]
I switched to a manual installation and use `bionic` - works well (Debian Testing user)

**Comment by aueelis** [comment]
The Microsoft Docs say that Buster is not supported and having to rely on the Troubleshooting section to install Azure CLI on (as far as I understand your post) any upcoming release of Debian and Ubuntu is just bad.

Yes, we need Buster support.


And concerning the Raspberry Pi: It doesn't seem that arm-linux is supported.

> If you are running a distribution that comes with apt, such as Ubuntu or Debian, there's an x86_64 package available for the Azure CLI.

**Comment by achandmsft** [comment]
We are working on Buster support currently. @zikalino will update this issue once it is released.

**Comment by yonzhan** [comment]
@zikalino is working on this issue and will give update by next week.

**Comment by jpreese** [comment]
Just ran into this, so looking forward to the release. Thanks @zikalino !

**Comment by x10an14** [comment]
I'm also eagerly awaiting this! =D

**Comment by frgomes** [comment]
I'm using the binaries for Debian Stretch on Debian Buster and ... "it works".
However, I don't remember if I had troubles when I've first installed it.
