### ISSUE TITLE
Edit button on the storage docs pages are broken

### ISSUE THREAD

**Issue by jlorich** [Azure/azure-cli#9882]
None of the edit buttons work, the all links go to pages like [this](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py/#L0) which are not valid URLs.

Example URL: https://docs.microsoft.com/en-us/cli/azure/storage/container?view=azure-cli-latest#az-storage-container-generate-sas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adcba5ed-e693-6345-2c1b-c17422d7b8f9
* Version Independent ID: 58297400-b777-6868-1687-0af3a512a16f
* Content: [az storage container](https://docs.microsoft.com/en-us/cli/azure/storage/container?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by adewaleo** [comment]
@marstr, @shuangjiang 

looks like this is related to the recent flatten work. 

Looks like this should already be fixed [here](https://github.com/Azure/azure-cli/blob/dev/doc/sphinx/azhelpgen/doc_source_map.json).

**Comment by marstr** [comment]
@sptramer, know anything about how the edit buttons are wired up?

**Comment by adewaleo** [comment]
> @sptramer, know anything about how the edit buttons are wired up?

I believe they get the url to link to from [doc_source_map.json ](https://github.com/Azure/azure-cli/blob/dev/doc/sphinx/azhelpgen/doc_source_map.json). 

Hopefully @sptramer / @daxianji007 (Shuang Jiang) can follow up on this.

**Comment by VamsiSangam** [comment]
This issue seems to be fixed.
