### ISSUE TITLE
az lock delete does not work

### ISSUE THREAD

**Issue by borkod** [Azure/azure-cli#9884]
Azure CLI "az lock delete" command does not seem to work on disks (Microsoft.Compute/disks).

I've tried a number of different variations of the command as suggested [here](https://github.com/Azure/azure-cli/issues/2688), however none of them seem to work.

In my specific scenario, the lock is inherited from parent resource group.  If I try to include the --parent attribute, I also receive the following error:
The resource type could not be found in the namespace 'Microsoft.Compute' for api version '2016-09-01'.

If I remove the --resource-type attribute, then one receives the following error:
--resource-type is required if the name, --resource, is present

Any suggestions on what is the proper way to use az lock delete cli command on disks?

**Comment by tjprescott** [comment]
If I understand you, the lock is not on the disk but the resource group. In that case you should delete the lock on the resource group before deleting the disk. The `az group lock delete` command would be the easiest way to do this.

**Comment by borkod** [comment]
Correct - the lock is on the resource group.  The resource is inheriting the lock from the resource group.  
The approach you suggest should work.  However should we not be able to remove the lock on the individual resource?  For instance, I may have many resources in a resource group and they would all inherit the delete lock.  In this situation I want to be able to delete a single resource.  In order to do that, I need to remove the delete lock on it.  It seems inappropriate to release the lock on the entire resource group (and subsequently all resources inside it) just to be able to delete a single resource?

**Comment by tjprescott** [comment]
There is no inheritance of locks. When you create a delete lock on the resource group, it does NOT create individual resources locks on the resources in the resource group. The delete lock on the resource group simply means you can't delete anything in the resource group (or the group itself) while the lock is in place.

To accomplish your scenario, you must remove the resource group lock, delete your resource, and then reapply the resource group lock. Alternatively, you could create individual locks for each resource you create, at which point the approach you tried of deleting that individual lock would work.

**Comment by borkod** [comment]
I did the workaround you suggested (remove lock on resource group, delete resource, reapply the resource group lock).  I thought it should be also possible to just remove the lock on the individual resource.  Thanks for the clarification that this is the expected behavior.
