### ISSUE TITLE
The command for Azure DevOps does not work

### ISSUE THREAD

**Issue by TechWatching** [Azure/azure-cli#9889]
When I try to use the command to create an Azure Pipeline with specific Azure DevOps organization and project I receive the following message : "Error finding organization. Please check that the organization exists by navigating to the Azure DevOps portal at dev.azure.com."
I am using the correct organization name, I can see it when I navigate to Azure DevOps portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3162209-04eb-aafb-a830-9edd55b584b3
* Version Independent ID: d1aad587-01b8-16c5-49f6-78cc85ab23cc
* Content: [az functionapp devops-pipeline](https://docs.microsoft.com/en-us/cli/azure/functionapp/devops-pipeline?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/_help.py)
* Service: **functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ahmedelnably** [comment]
Do you mind running the command in an interactive way `az functionapp devops-pipeline create`
And check if your organization name shows up in the list provided by the command or not

**Comment by TechWatching** [comment]
Az interactive seems not be up-to-date with the funcion app last changes. Only the devops-build command appears even if this command has been changed to devops-pipeline and no list appears for this command.

**Comment by ahmedelnably** [comment]
Sorry for the confusion, if you just execute `az functionapp devops-pipeline create` without any parameters it should guide you through its own interactive mode (not the az interactive).

**Comment by TechWatching** [comment]
Okay, just did, it seems it does not see the Azure DevIops organizations I am part of.
![image](https://user-images.githubusercontent.com/15186176/60945553-26e47a00-a2ec-11e9-8074-82f4ab01a4e3.png)

**Comment by Hazhzeng** [comment]
@TechWatching Thanks for reporting this issue, I will take a look into it. Seems like the organization created from MSA and AAD account is still tangled together. I will improve the organization detection.

**Comment by Hazhzeng** [comment]
@TechWatching If possible could you let me know what's your account type.
When you login to microsoft, if the icon is a badge, that is AAD. Otherwise, it is MSA.
![Untitled](https://user-images.githubusercontent.com/48038149/60996328-3cb46800-a309-11e9-8b5f-691208c542a2.png)

**Comment by TechWatching** [comment]
Sorry I did not see your message. It's AAD.

**Comment by ahmedelnably** [comment]
@TechWatching, will close this issue. please reopen if you still facing the same issue
