### ISSUE TITLE
No option to specify template when creating a deployment

### ISSUE THREAD

**Issue by iainfoulds** [Azure/azure-cli#989]
When creating a new deployment with `az resource group deployment create`, there is no option to specify a template URI. It appears that only a local json file can be specified. There is also then no interactive prompts when passing in .parameters file (which also must be local). This is probably fine if the user is creating their own templates.

The Azure quickstart templates (https://github.com/Azure/azure-quickstart-templates), however, can't be used unless you curl the json files from Github and then manually edit the .parameters file accordingly. 

Trying to use template in Github repo rather than local file:

```
ifoulds@Ubuntu:~$ az resource group deployment create -n mongodb -g mongodb --template-file-path https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/mongodb-on-ubuntu/azuredeploy.json
File 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/mongodb-on-ubuntu/azuredeploy.json' contains error: [Errno 2] No such file or directory: 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/mongodb-on-ubuntu/azuredeploy.json'
```

Once curl'd the json files and edited accordingly, the following works:

```
ifoulds@Ubuntu:~$ az resource group deployment create -n mongodb -g mongodb --template-file-path azuredeploy.json --parameters-file-path azuredeploy.parameters.json
```

If you don't edit the parameters.json, then the following is an example of lack of prompts, just a failure:

```
At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. {
  "error": {
    "code": "InvalidParameter",
    "target": "adminPassword",
    "message": "Required parameter 'adminPassword' is missing (null)."
  }
}
```

Using

```
ifoulds@Ubuntu:~$ az --version
azure-cli (2016.09.05.nightly)
```

**Comment by tjprescott** [comment]
This has been fixed. `group deployment create` now supports `--template-file` and `--template-uri`
