### ISSUE TITLE
az storage blob download-batch fails with 'Read timed out'

### ISSUE THREAD

**Issue by Makabata** [Azure/azure-cli#9890]
## Describe the bug

**Command Name**
`az storage blob download-batch`

**Errors:**
```
HTTPSConnectionPool(host='connectorssaacc.blob.core.windows.net', port=443): Read timed out.
Traceback (most recent call last):
site-packages/urllib3/contrib/pyopenssl.py, ln 297, in recv_into
    return self.connection.recv_into(*args, **kwargs)
python3.6/site-packages/OpenSSL/SSL.py, ln 1822, in recv_into
    self._raise_ssl_error(self._ssl, result)
python3.6/site-packages/OpenSSL/SSL.py, ln 1622, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError

...

storage/v2018_03_28/common/storageclient.py, ln 311, in _perform_request
    raise AzureException(ex.args[0])
azure.common.AzureException: HTTPSConnectionPool(host='connectorssaacc.blob.core.windows.net', port=443): Read timed out.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az storage blob download-batch -s {} --pattern {} -d {} --account-name {}`

## Environment Summary
```
Linux-4.18.0-25-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.66 *

```

**Comment by limingu** [comment]
This seems be more likely network connection issue. @Makabata, can you reproduce the issue with --debug in the command? Thanks.

**Comment by Juliehzl** [comment]
@Makabata Have your problem solved? If you still have connection error, can you show me your debug message with ```-debug``` appended?

**Comment by Makabata** [comment]
Hey Zunli, indeed it was a network issue. Thanks for the replay.
