### ISSUE TITLE
az dls cmd logs preview warning to stderr since new version which makes devops pipeline fail

### ISSUE THREAD

**Issue by markvanschaik** [Azure/azure-cli#9891]
## Describe the bug

**Command Name**
`az dls account list`

**Errors:**
A dls-preview warning is shown when calling any az dls cmd, which is written to the std err output. The devops pipeline fails, as it is treated as an error. 

`Command group 'dls' is in preview. It may be changed/removed in a future release.`

We came up with a temporary solution to write the error to the null device by adding `2> /dev/null` to each az dls cmd, so that the pipeline will succeed. 

## To Reproduce:
Execute any az dls command. For example:
- `az dls account list --query {}`

## Expected Behavior
The dls commands were not in preview before, so we were suprised to find it in preview mode since the new version came out.

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.68

```

**Comment by tjprescott** [comment]
The DLS commands have always been in preview. It was not called out until the recent change.

**Comment by aweiker** [comment]
The `pipelines` commands had the same thing happen to them. The side effect here is that our Azure DevOps pipelines now fail because warnings are written to STDERR.

How is this new feature disabled so that we can differentiate between an error and an informational notice?

**Comment by yonzhan** [comment]
@jiasli  please take a look and comment.

**Comment by jiasli** [comment]
Writing to std.err is a very common behavior across many CLI tools. 

The CI should not rely on the contents in std.err. The CI should check the exit code instead: https://github.com/Azure/azure-cli#exit-codes

**Comment by igelineau** [comment]
The problem is Powershell is not very friendly with programs writing to STDERR. I've spend half of my day trying to strip out what is written to STDERR and only keep the JSON output from STDOUT, but didn't find a solution yet. Any workaround at this point would be much appreciated.

**Comment by atbagga** [comment]
@igelineau Follow this thread for detailed conversations and some workarounds - https://github.com/microsoft/knack/issues/166

**Comment by jiasli** [comment]
We have added option `--only-show-errors` in #12604 to disable warnings that are written to `stderr`. It will be included in [S167](https://github.com/Azure/azure-cli/milestone/84) release.
