### ISSUE TITLE
Azure CLI login failure

### ISSUE THREAD

**Issue by Pilchie** [Azure/azure-cli#9898]
_From @kylepeters on Tuesday, July 2, 2019 6:42:21 PM_

Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-deploy-microservice-tutorial/azure-resources
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Every time I attempt to use the >az login command, it launches a browser window for me to log in. After successful login via browser window, I get this error...
C:\>az login
Note, we have launched a browser for you to login. For old experience with device code, use "az login --use-device-code"
You have logged in. Now let us find all the subscriptions to which you have access...
request failed: Error occurred in request., SSLError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /tenants?api-version=2016-06-01 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

_Copied from original issue: dotnet/core#2975_

**Comment by Pilchie** [comment]
_From @carlossanlop on Tuesday, July 9, 2019 8:04:02 PM_

@Pilchie I am not sure if this is something for the ASP.NET team specifically, since the question is happening in Azure tools. Is this something your team would be able to address? If not, do you know who would be the best contact for this?

**Comment by Pilchie** [comment]
_From @Pilchie on Tuesday, July 9, 2019 8:05:19 PM_

@Petermarcu any ideas?

**Comment by Pilchie** [comment]
_From @Petermarcu on Tuesday, July 9, 2019 8:53:17 PM_

This is probably best opened here: https://github.com/Azure/azure-cli

**Comment by Petermarcu** [comment]
@yugangw-msft FYI

**Comment by yugangw-msft** [comment]
@kylepeters, can you please try again? This error happened once before that the azure resource manager service hit a deployment error which ended up having an incomplete certificate chain. If this error persists, please run with `--debug` and mail the trace to me at yugangw at microsoft dot com.

**Comment by kylepeters** [comment]
I just tried this again, and received the exact same request failure.

**Comment by yugangw-msft** [comment]
@kylepeters, are you behind a proxy? To get unblocked, please try the [tips](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy) here. If you don't think you are behind a proxy, please run with `--debug` and send the trace to me: yugangw at microsoft dot com

**Comment by kylepeters** [comment]
Unblocking the proxy by [temporarily] setting an AZURE_CLI_DISABLE_CONNECTION_VERIFICATION environment variable worked. I will have to work with our infrastructure guys to set the REQUESTS_CA_BUNDLE to the file path of the proxy server's certificate....if we even have one, and if they know where to find it.  Thank you for the assist - much appreciated.

**Comment by yugangw-msft** [comment]
@kylepeters, good to know you are unblocked. Since this is related with the proxy server in your work space, not a CLI specific issue, I am closing this.

**Comment by kylepeters** [comment]
Understood. But hey thanks for pointing me to the solution!

Sincerely,

Kyle Peters
