### ISSUE TITLE
Monitor metric alert condition with special characters

### ISSUE THREAD

**Issue by pajzo** [Azure/azure-cli#9901]
**Describe the bug**
When creating a metric alert where the condition is filtering on a disk it's excluding the `:` charterer, so the filtering gets wrong.

**To Reproduce**
```
        az monitor metrics alert create `
            --name "Server $serverNameDisplay Disk E" `
            --scopes "/subscriptions/$subscriptionId/resourceGroups/$resourceGroup/providers/Microsoft.OperationalInsights/workspaces/xxxxx" `
            --description "Low disk" `
            --condition "min Average_Free Megabytes < 5000 where InstanceName includes E: and Computer includes $serverName" `
            --severity 0 `
            --evaluation-frequency 1m `
            --window-size 1m `
            --resource-group "$resourceGroup" `
            --subscription "$subscriptionId"
```

**Expected behavior**
The created metric is created with
```json
{
	"name": "InstanceName",
	"operator": "Include",
	"values": [
		"E"
	]
}
```

But it should be like this:
```json
{
	"name": "InstanceName",
	"operator": "Include",
	"values": [
		"E:"
	]
}
```

**Environment summary**
- PowerShell
- Windows
- azure-cli version 2.0.68
- Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

**Comment by tjprescott** [comment]
Thanks for the report @pajzo. We'll get a fix into an upcoming release.

**Comment by MyronFanQiu** [comment]
@pajzo Hello. `$` will not be a special character in the condition. Right?

**Comment by pajzo** [comment]
@MyronFanQiu I'm not sure what your question is - but `$` is a reference to a PowerShell variable.

So yes there will be a `$` in the condition like:

`--condition "min Average_Free Megabytes < 5000 where InstanceName includes $diskName and Computer includes $serverName" `

**Comment by MyronFanQiu** [comment]
I got your point. `$` is reference to a PowerShell variable. So the real condition will be a specific name like "MyServerName". The real REST call will not contain the character "$".

**Comment by pajzo** [comment]
That's correct @MyronFanQiu  :-) 

But the condition may contain a `:` like `E:` or `C:`

**Comment by MyronFanQiu** [comment]
@pajzo of course. I'm working on it. 😄
