### ISSUE TITLE
Need to view Validation error log

### ISSUE THREAD

**Issue by BhuvanaSurannagari** [Azure/azure-cli#9909]
Cx is trying to import DNS zone file to Azure using CLI. They have more than 1300 zone files which need to be imported and some of them are having validation errors due to which the log is not hitting NRP and the errors are not seen in the Activity log. So cx wouldn't know which zone file has failed and what error message has been recorded for that particular zone file.

So cx has below questions

1. Is there any way that we can capture these kind of Validation errors?
I understand this is not possible from activity log on portal. But is there any alternate way (like Az console logs)?

2. Can we know which zone file (the name of zone file) has failed the import?
Because while importing ~1300 zones, cx felt that it would be easier if they can look at the logs and go to that particular zone file and make the required changes.

**Comment by tjprescott** [comment]
1) none that I know of
2) `az network dns zone import` on accepts a single file per invocation. So, they should know exactly which file failed because it would be the one that immediately preceded the failure.

**Comment by tjprescott** [comment]
The question has been answered with no further discussion from the customer, so I will close this issue.
