### ISSUE TITLE
az ad sp create-for-rbac fails when name already taken

### ISSUE THREAD

**Issue by jongio** [Azure/azure-cli#9910]
## Describe the bug

This command:
`az ad sp create-for-rbac -n sample-devops --role Owner --sdk-auth > sp-azdo.json`

Gives the below error.

If I change to 
`az ad sp create-for-rbac -n jong101 --role Owner --sdk-auth > sp-azdo.json`

and it works.

I believe it is because sample-devops is already taken in my tenant.

**Command Name**
`az ad sp create-for-rbac`

**Errors:**
```
AADSTS9002313: Invalid request. Request is malformed or invalid.

Trace ID: 21c3e4db-d2fd-44f7-a3e0-59393b050900

Correlation ID: 9d25c5fd-bcda-413e-b340-750fe20fa5a0

Timestamp: 2019-07-10 21:32:47Z
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az ad sp create-for-rbac -n {} --role {} --sdk-auth`

## Expected Behavior

sp created

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.68
azure-cli-iot-ext 0.7.1

Extensions:
azure-cli-iot-ext 0.7.1

```

**Comment by tjprescott** [comment]
@yugang-msft believe this is essentially a dupe of #8750?

**Comment by jongio** [comment]
Not a dupe.  This one is 'invalid request'...doesn't say it already exists.

**Comment by yugangw-msft** [comment]
`AADSTS9002313` is an authentication error, and more likely happened when CLI used the refresh token to exchange for a new access token. This is likely a transient error. @jongio, can you try again? Like the PR called out by the @tjprescott, `create-for-rbac` is idempotent, and should not report an error for conflicting with an existing app.
If this error persists, please run with `--debug` and send me the trace through offline mails.

**Comment by jongio** [comment]
Now getting this, which is expected behavior. Closing as transient.

```
Changing "sample-devops" to a valid URI of "http://sample-devops", which is the required format used for service principal names
Found an existing application instance of "3d0a9351-6035-4561-886b-". We will patch it
Insufficient privileges to complete the operation.
```
