### ISSUE TITLE
Issue with RPM package on RHEL with EUS repo

### ISSUE THREAD

**Issue by johanburati** [Azure/azure-cli#9912]
On RHEL images using the EUS repo (rhui-microsoft-azure-rhel7-eus), the installation is failing because of a dependency on  **python2-virtualenv**.

On RHEL images using the standard repo, **python2-virtualenv** point to **python-virtualenv** so it is working.

I have already reported the issue to Redhat but they told me Microsoft should change their package.

The dependency on  **python2-virtualenv** was introduce by https://github.com/Azure/azure-cli/commit/45579caa99b7f1d81bfc1f05adacab8f5ae59f69, the previous package **azure-cli-2.0.65-1.el7.x86_64.rpm** only required **python**

###  Error on RHEL 7.4 with EUS repo
```
$ sudo yum install azure-cli
..
--> Processing Dependency: python2-virtualenv for package: azure-cli-2.0.66-3.el7.x86_64
--> Finished Dependency Resolution
Error: Package: azure-cli-2.0.66-3.el7.x86_64 (azure-cli)
           Requires: python2-virtualenv
..
$ sudo repoquery --whatprovides python2-virtualenv
$
```

**Comment by johanburati** [comment]
I have submitted a fix: https://github.com/Azure/azure-cli/pull/9913

**Comment by marstr** [comment]
I've just verified that the formal name of the package is `python-virtualenv`, and that the environments that were tested were automatically correcting `python2-virtualenv`. I've accepted the fix, thank you very much @johanburati.

**Comment by yugangw-msft** [comment]
CC: @zikalino

**Comment by johanburati** [comment]
Thanks @marstr/@yugangw-msft/@zikalino !

Any idea when the fixed package will be published to the repo ?

**Comment by zikalino** [comment]
@johanburati  it will be out next week on tuesday

**Comment by johanburati** [comment]
Ref:
- https://github.com/Azure/azure-cli/issues/9791
