### ISSUE TITLE
`az webapp config appsettings set --settings endpoints:api=https://example.com` returns bad request when containing colon in the name 

### ISSUE THREAD

**Issue by mratrifork** [Azure/azure-cli#9914]
## Describe the bug

I have a .net core web API with some app settings. These app settings are in a json structure, ie. 

```json
{
  "endpoints": {
       "api":"https://example.com"
    }
}
```

When settings this app setting via. the Azure Portal, i would set the name to `endpoints:api` and the value to `https://example.com` and this works fine.

Doing in via the CLI, this is not allowed.

**Command Name**
`az webapp config appsettings set`

**Errors:**
```
Operation returned an invalid status code 'Bad Request'

msrest.http_logger : Response content:
msrest.http_logger : {"Code":"BadRequest","Message":"AppSetting with name 'endpoints:api' is not allowed.","Target":null,"Details":[{"Message":"AppSetting with name 'endpoints:api' is not allowed."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"04072","MessageTemplate":"AppSetting with name '{0}' is not allowed.","Parameters":["endpoints:api"],"Code":"BadRequest","Message":"AppSetting with name 'endpoints:api' is not allowed."}}],"Innererror":null}
msrest.exceptions : Operation returned an invalid status code 'Bad Request'
```

## To Reproduce:

- `az webapp config appsettings set --resource-group {} --name {} --settings endpoints:api=https://example.com --debug`

## Expected Behavior

Should set an app setting

## Environment Summary
```
Darwin-18.6.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.67 *

```

**Comment by btardif** [comment]
@panchagnula can you take a look at this one

**Comment by panchagnula** [comment]
@mratrifork please follow the examples in the documentation on using the --settings, the command excepts a KEY=VALUE format. in your case the key is "endpoints" & value is "{'api': 'https://example.com'}"
So run the command as 
az webapp config appsettings set -n{} -g {}  --settings endpoints="{'api': 'https://example.com'}"

or use a json file with the settings with say name appsettings.json
{
  "endpoints": {
       "api":"https://example.com"
    }
}
& run command as 
az webapp config appsettings set -n {} -g{} --settings @appsettings.json

**Comment by avdv** [comment]
> please follow the examples in the documentation on using the --settings, the command excepts a KEY=VALUE format. in your case the key is "endpoints" & value is "{'api': '[https://example.com'}](https://example.com'%7D)" So run the command as az webapp config appsettings set -n{} -g {} --settings endpoints="{'api': '[https://example.com'}](https://example.com'%7D)"

@panchagnula this does not seem quite right. Why would changing a setting in the Portal be allowed, but not if I change it from the cli?

When configuring the keys in Portal and `az webapp config appsettings list --name {} -g {}` it shows as follows:
```
  {
    "name": "AzureAd:CallbackPath",
    "slotSetting": false,
    "value": "/signin-oidc"
  },
```
But when I try to set this via `az webapp config appsettings set --resource-group {} --name {} --settings 'AzureAd={ "CallbackPath": "/signin-oidc" }'` as you suggested, it turns up as:
```
  {
    "name": "AzureAd",
    "slotSetting": false,
    "value": "{ \"CallbackPath\": \"/signin-oidc\" }"
  },
```
Am I doing something wrong? Are you saying this should be equivalent?
