### ISSUE TITLE
"az resource list --tag" gives strange error

### ISSUE THREAD

**Issue by mick62** [Azure/azure-cli#9916]
## Describe the bug

**Command Name**
`az resource list`

**Errors:**
```
you cannot use the tag filter with other filters
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- I assigned tag (key) 'customer' for 2 of my storage accounts.
- `az resource list --tag 'customer' `

## Expected Behavior
JSON text with description of the 2 resources which have tag 'customer' assigned. 

## Environment Summary
```
Windows-10-10.0.16299-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.65 *

```

**Comment by tjprescott** [comment]
If you run the command with --debug, what is the first line (starts with command_arguments:)?

**Comment by mick62** [comment]
Command entered:
az resource list --tag 'customer' --debug
Result:
Command arguments: ['resource', 'list', '--tag', 'customer', '--debug']...az_command_data_logger : command args: resource list --tag {} --debug
...cli.azure.cli.core.util : you cannot use the tag filter with other filters
you cannot use the tag filter with other filters...


Content of log file in ~\.azure\commands:
CMD-LOG-LINE-BEGIN 21488 | 2019-07-12 18:56:44,648 | INFO | az_command_data_logger | command args: resource list --tag {} --debug
CMD-LOG-LINE-BEGIN 21488 | 2019-07-12 18:56:45,161 | ERROR | cli.azure.cli.core.util | you cannot use the tag filter with other filters
CMD-LOG-LINE-BEGIN 21488 | 2019-07-12 18:56:45,164 | INFO | az_command_data_logger | exit code: 1

Why is it changed to "--tag {}" in the log file?


    Am Donnerstag, 11. Juli 2019, 20:42:23 MESZ hat Travis Prescott <notifications@github.com> Folgendes geschrieben:  
 
 
If you run the command with --debug, what is the first line (starts with command_arguments:)?

**Comment by tjprescott** [comment]
Probably to avoid logging potentially sensitive info. If you run `az configure` do you have any defaults set like resource group?

**Comment by mick62** [comment]
az configure
entered in VS Code terminal displays:
...
Your current configuration is as follows:
[cloud]
name = AzureCloud

[defaults]
output = table
location = eastus
--
entered in Web Shell displays:...
Your current configuration is as follows:

[cloud]
name = AzureCloud

[core]
first_run = yes

[defaults]
location = eastus

Environment variables:
AZURE_ACCESS_TOKEN_FILE = /tmp/accessTokens.json
AZURE_HTTP_USER_AGENT = cloud-shell/1.0
--

    Am Freitag, 12. Juli 2019, 20:34:38 MESZ hat Travis Prescott <notifications@github.com> Folgendes geschrieben:  
 
 
Probably to avoid logging potentially sensitive info. If you run az configure do you have any defaults set like resource group?

**Comment by tjprescott** [comment]
Yes, this is occurring because you have a default location set. It is using the default location and applying it as a filter, which cannot be used in conjunction with `--tag`.

**Comment by tjprescott** [comment]
The workaround would be to unset your default location before running the command. The validation should be updated to ignore location if it is simply set by the default.

**Comment by yonzhan** [comment]
add to S164.
