### ISSUE TITLE
Azure Batch Commandlets should accept both ISO and timedelta __str__ representations

### ISSUE THREAD

**Issue by bgklein** [Azure/azure-cli#9917]
Azure batch commands should accept both ISO8601 and timedelta __str__ formats as input for commands 

See #3633

**Comment by carogonzalezzapata** [comment]
Hello? Can we have an update here, please?

**Comment by bgklein** [comment]
Resolving as now there is a KPI tracking customer issues and this was solely meant as a feature/tracking issue
