### ISSUE TITLE
az vm run-command invoke does not pass parameter correctly

### ISSUE THREAD

**Issue by swbae31** [Azure/azure-cli#9923]
## Describe the bug

**Command Name**
`az vm run-command invoke`

**Errors:**
Running
`az vm run-command invoke -g rg -n linux_vm --command-id RunShellScript --scripts '@./test.sh' --parameters hello`

with test.sh :
`echo $1`

does not pass the parameter 'hello' correctly. The stdout just returns with newlines.

This style of passing works for PowerShell Scripts.
When I run 
`az vm run-command invoke -g rg -n windows_vm --command-id RunPowerShellScript--scripts '@./test.ps1' --parameters param1=hello`

with test.ps1 :
`Param([Parameter(Mandatory=$true)][string]$param1)`
`echo $param1`

and it will return hello.

## To Reproduce:
1) Have the test.sh file in the current directory with content
`echo $1`

2) Run 
`az vm run-command invoke -g rg -n linux_vm --command-id RunShellScript --scripts '@./test.sh' --parameters hello`

3) Will Return

{
  "value": [
    {
      "code": "ProvisioningState/succeeded",
      "displayStatus": "Provisioning succeeded",
      "level": "Info",
      "message": "Enable succeeded: \n[stdout]\n\n\n[stderr]\n",
      "time": null
    }
  ]
}

## Expected Behavior

{
  "value": [
    {
      "code": "ProvisioningState/succeeded",
      "displayStatus": "Provisioning succeeded",
      "level": "Info",
      "message": "Enable succeeded: \n[stdout]\nhello\n\n[stderr]\n",
      "time": null
    }
  ]
}

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.7.2
Shell: python.exe

azure-cli 2.0.68

Extensions:
vm-repair 0.1.2 (dev) C:\Users\subae\Desktop\azure-cli-extensions\src\vm-repair

```

**Comment by swbae31** [comment]
Issue resolved

**Comment by adewaleo** [comment]
For context, I think there might have been a typo in the script.

I was unable to reproduce the behavior with a correct test.sh script on bash or powershell. However, when I tried `echo $!` instead of `echo $1`, the parameter was not written to stdout on the vm.
