### ISSUE TITLE
Unable to pass multiple instance IDs into --instance-ids parameter

### ISSUE THREAD

**Issue by AgSync-Aaron** [Azure/azure-cli#9926]
```bash
$ CURRENT_INSTANCE_IDS="11 14"
$ az vmss delete-instances --name=$VMSS_NAME --resource-group=$VMSS_RG --instance-ids="$CURRENT_INSTANCE_IDS"
The provided instanceId 11 14 is invalid. It must be a non-negative integer or the character "*".
```
Your documentation says 
&gt; Space-separated list of IDs (ex: 1 2 3 ...) or * for all instances.

Can you please provide an example of how to pass multiple instance IDs into the parameter `--instance-ids`?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0408c294-207a-2b72-7b93-e09121602b75
* Version Independent ID: 852cb67b-70c6-b811-3b0a-5d5b84b8a911
* Content: [az vmss](https://docs.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#feedback)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machine-scale-sets**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by AgSync-Aaron** [comment]
🤦🏻‍♂️ it doesn't like the `=` sign 
```bash
$ az vmss delete-instances --name=$VMSS_NAME --resource-group=$VMSS_RG --instance-ids $CURRENT_INSTANCE_IDS
```

**Comment by andresbarcenas** [comment]
I tried creating a vmss on an existing subnet and it keeps creating a new one:

 --subnet XX \
  --vnet-name XX \

I also tried just the Resource ID of the subnet --subnet /resources/*** but it does not work.

Any ideas?

**Comment by sysadmin-exe** [comment]
this is closed but I am having the same issue. The command here is without a = sign

az vmss update-instances  --instance-ids * --name server_scaleset --resource-group web_rg

the error I get is this: The provided instanceId data.tf is invalid. It must be a non-negative integer or the character "*". data.tf is actually the first file in the PWD where the command was run from on the terminal. 

Tried same on Portal CLI and the error was: The provided instanceId clouddrive is invalid. It must be a non-negative integer or the character "*".

**Comment by qwordy** [comment]
I notice you opened a new issue. So we will not update here.
