### ISSUE TITLE
az ad app create --native-app not working in Azure China.

### ISSUE THREAD

**Issue by sscchh2001** [Azure/azure-cli#9931]
>[root@cheshcentce2 aks]# az ad app create 
>     --display-name "${aksname}Client" \
>     --native-app \
>     --reply-urls "https://${aksname}Client" \
>     --query appId -o tsv

Error message: **Property identifierUris value is required but is empty or missing.**

>[root@cheshcentce2 aks]# az ad app create \
>     --display-name "${aksname}Client" \
>     --native-app \
>     --reply-urls "https://${aksname}Client" \
>     --identifier-uris "https://${aksname}Client" \
>     --query appId -o tsv

Error message: **'--identifier-uris' is not required for creating a native application**

If I remove --native-app, the command would work, but I will have to modify the application type to default in AAD portal.

>[root@cheshcentce2 aks]# az --version
>azure-cli                         2.0.68
>
>command-modules-nspkg               2.0.3
>core                              2.0.68
>nspkg                              3.0.4
>telemetry                          1.0.3

Only latest CLI version 2.0.68 has this issue in both Linux and Windows, but I could not reproduce it in global Azure. 
Please investigate.

**Comment by forester123** [comment]
Anyone look at this issue?

**Comment by yugangw-msft** [comment]
`Property identifierUris value is required but is empty or missing.` is an AAD graph server error which only pops up in the China Cloud, let me contact AAD graph team to clarify this

**Comment by jluk** [comment]
@thomas1206 as FYI

**Comment by thomas1206** [comment]
I tried it in my Mooncake sub, it works:

thomas@thomascli:~$ serverApplicationId=$(az ad app create \
    --display-name "aksthomasServer" \
    --identifier-uris "https://aksthomasServer" \
    --query appId -o tsv)
thomas@thomascli:~$ echo $serverApplicationId
12bf9afd-5288-4a9a-a4ca-02ed9f711741

**Comment by yugangw-msft** [comment]
@thomas1206, I have talked to the AAD graph team, they suggest open a ICM ticket against `AADFirstPartyApps/AADApplicationModel`. The key difference in mooncake is the graph would reject any payload w/p `identifierUris`, while public cloud allows it.
I don't have mooncake account to test, but if yo ucan reproduce it, please open the ticket

**Comment by yugangw-msft** [comment]
Not a CLI issue; rather a AAD graph service end issue

**Comment by sscchh2001** [comment]
Thanks for the investigation @yugangw-msft , I will proceed from ICM perspective.
