### ISSUE TITLE
Are parameters supported for script loaded from a file?

### ISSUE THREAD

**Issue by AntoineGagne** [Azure/azure-cli#9937]
I have been trying to pass parameters to a script loaded from a file to no avail. Is this a supported use case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f04b196d-7d11-7213-f037-f12b85b19c52
* Version Independent ID: adc05d8e-b13b-134b-5f61-42aaf23666df
* Content: [az vm run-command](https://docs.microsoft.com/en-us/cli/azure/vm/run-command?view=azure-cli-latest)
* Content Source: [src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_help.py)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by adewaleo** [comment]
Some more context will be very helpful.

We do have examples that supply parameters to scripts.

**Comment by AntoineGagne** [comment]
I would like to use a script with options such as:

```sh
az vm run-command invoke \
    --command-id RunShellScript \
    --name test-vm \
    --subscription 18feceeb-8255-44ff-a576-afa212c1ffe9 \
    --resource-group some-group \
    --scripts @a-script.sh \
    --parameters "--some-option=$(value_that_will_expand_on_the_host)"
```

but it doesn't seem to work so I was wondering whether there is a way to do it.

Thank you for your help!

**Comment by adewaleo** [comment]
So when you say it doesn't seem to work what do you mean? What kind of error do you get? 

run commands (in the CLI) take a space separated list of parameters; see az vm run-command invoke -h.

Also --debug can be helpful to see how the cli is parsing your arguments and what's being sent in the request to Azure Compute / ARM

**Comment by qwordy** [comment]
Could you please provide error message?

**Comment by qwordy** [comment]
Similar to https://github.com/Azure/azure-cli/issues/10400

**Comment by qwordy** [comment]
I tried your command. I am afraid you can't. $VAR will be interpreted in your current shell. You can put $VAR in the script file so that it will be interpreted in host.
