### ISSUE TITLE
Role names in authorization error messages incorrectly refer to '(Preview)' roles

### ISSUE THREAD

**Issue by cbrooksmsft** [Azure/azure-cli#9938]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
error message when accessing azure storage without sufficient permissions guides the user to be assigned to one of the following role names which no longer exist:

**You do not have the required permissions needed to perform this operation.
Depending on your operation, you may need to be assigned one of the following roles:
    "Storage Blob Data Contributor (Preview)"
    "Storage Blob Data Reader (Preview)"
    "Storage Queue Data Contributor (Preview)"
    "Storage Queue Data Reader (Preview)"**

**To Reproduce**
Attempt to access storage using --auth-mode login but with insufficient permissions

**Expected behavior**
correct role names should be listed.  The existing role names listed should be modified to remove the " (Preview)" suffix.

**Environment summary**
Bash on Windows
azure-cli                         2.0.68
core                              2.0.68

**Additional context**
none

**Comment by Juliehzl** [comment]
Can you show your exact command here?  And you can append your command with ```--debug``` to see more information for the command event.

**Comment by yugangw-msft** [comment]
@Juliehzl, the exact command should not matter as you can reproduce with any storage commands using `--auth-mode`. Please work with @limingu to cross check the latest names though "az role definition list" and remove the `(Preview)` suffix.
