### ISSUE TITLE
Azure CLI Example missing content

### ISSUE THREAD

**Issue by TheChadR** [Azure/azure-cli#9944]
Hi
The Azure CLi example is missing some content in the following location:
https://docs.microsoft.com/en-us/cli/azure/role/definition?view=azure-cli-latest#examples

When run through CloudShell, the example fails as it is missing `*` under actions and should look like the below:

```
"Actions": [ \
                                "Microsoft.Compute/*/read", \
                                    "Microsoft.Compute/virtualMachines/start/action", \
                                    "Microsoft.Compute/virtualMachines/restart/action", \
                                    "Microsoft.Network/*/read", \
                                "Microsoft.Storage/*/read", \
                                    "Microsoft.Authorization/*/read", \
                                "Microsoft.Resources/subscriptions/resourceGroups/read", \
                                "Microsoft.Resources/subscriptions/resourceGroups/resources/read", \
                                "Microsoft.Insights/alertRules/*", \
                                    "Microsoft.Support/*" \
```

Thanks
Chad

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40e649cf-40e3-1b9e-141a-c62d244eda61
* Version Independent ID: 78ea89c1-7c56-e33b-d10a-dae05642aa34
* Content: [az role definition](https://docs.microsoft.com/en-us/cli/azure/role/definition?view=azure-cli-latest#examples)
* Content Source: [src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-role/azure/cli/command_modules/role/_help.py)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jiasli** [comment]
The contents are displayed correctly on Chrome and can be executed in Cloud Shell without any error. Could you share a screenshot of what is shown on your browser?

**Comment by yonzhan** [comment]
add to S172
