### ISSUE TITLE
'az storage container create' required '--connection-string'

### ISSUE THREAD

**Issue by elilienstein** [Azure/azure-cli#9948]
## Describe the bug
Couldn't create storage (az storage container create -n MyStorageContainer)
without adding the --connection-string in quotes although I did set  AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_KEY environment variables as indicated in the error message below and  [documentation](https://docs.microsoft.com/en-us/cli/azure/storage/container?view=azure-cli-latest) 
 
 
**Command Name**
`az storage container create`

**Errors:**
```
Missing credentials to access storage service. The following variations are accepted:
    (1) account name and key (--account-name and --account-key options or
        set AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_KEY environment variables)
    (2) account name and SAS token (--sas-token option used with either the --account-name
        option or AZURE_STORAGE_ACCOUNT environment variable)
    (3) account name (--account-name option or AZURE_STORAGE_ACCOUNT environment variable;
        this will make calls to query for a storage account key using login credentials)
    (4) connection string (--connection-string option or
        set AZURE_STORAGE_CONNECTION_STRING environment variable); some shells will require
        quoting to preserve literal character interpretation.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
set AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_KEY environment variables 
- `az storage container create -n {}`

## Environment Summary
```
Linux-4.15.0-54-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.69

```

**Comment by Juliehzl** [comment]
Can you use ```printenv AZURE_STORAGE_ACCOUNT``` and ```printenv AZURE_STORAGE_KEY``` to show the value for AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_KEY?

**Comment by elilienstein** [comment]
Yes,
I should have mentioned this is a free account. 
I repeated as follows:
Create free account
Install Azure CLI
On command line do:
az login

az group create --name my-resource-group --location westus

az storage account create --name ericstestaccount --resource-group my-resource-group --location westus --sku Standard_RAGRS --kind StorageV2

az storage account keys list --account-name ericstestaccount --resource-group my-resource-group --output table

export AZURE_STORAGE_ACCOUNT="ericstestaccount"
export AZURE_STORAGE_KEY="nHs+r3i..."
printenv AZURE_STORAGE_ACCOUNT
OUTPUT: ericstestaccount
printenv AZURE_STORAGE_KEY
OUTPUT: nHs+r3i...
az storage container create --name ericsstoragecontainer
OUTPUT: Error as above in report
az storage account show-connection-string --name ericstestaccount
az storage container create --name ericsstoragecontainer --connection-string "DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=ericstestaccount;AccountKey=nHs+r3..."
OUTPUT:
{
  "created": true
}

**Comment by Juliehzl** [comment]
@elilienstein Sorry for late response. Something else makes the issue dropped... I try to reproduce your error scenario but failed. 
Can you run your command with `--debug` and show me your debug message for more information?
If there are keys message, please delete or reedit keys information, but it shouldn't have keys information.

**Comment by Juliehzl** [comment]
Thanks @elilienstein for your feedback. I add your tips in our document https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/docs/Use%20Storage%20Commands.md#L14-L13
