### ISSUE TITLE
az still available after uninstall

### ISSUE THREAD

**Issue by jongio** [Azure/azure-cli#9958]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

CLI wouldn't update to latest version 2.0.66 on Windows using the installer.

I uninstalled via CLI but it still worked in terminal.

I had to manually remove the following files:

![image](https://user-images.githubusercontent.com/2163001/61350715-5d0a8800-a81d-11e9-82c1-c9ed5f3cc29e.png)

Then it didn't work.

Then I reinstalled via the Windows installer and I got the latest version.

**To Reproduce**
Steps to reproduce the behavior.

Don't know. Got to a weird state that I'm not sure I can repro.

**Expected behavior**

Latest version to be updated or completely uninstalled.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

Windows installer.
Windows Terminal and CMD and PowerShell.

**Additional context**

**Comment by yugangw-msft** [comment]
@jongio, based on the screen snapshot you provided, it appears at some point you installed the CLI using `pip`. CLI windows installer can only upgrade the one acquired through the installer and would not recognize the one through pip.
Specifically to pip, deleting the entry scripts of `az.bar` is not a complete uninstall as the bulk files would still be under `c:\Python36\Lib\site-packages`. And to be honest, Azure CLI hasn't really supported a clean uninstall through `pip uninstall` till the very recent release.

**Comment by jongio** [comment]
Gotcha. Thanks. I must have forgot I did that.  I ran `pip uninstall azure-cli` to clean things up.
