### ISSUE TITLE
'az network dns record-set ns create' - where is the --subscription parameter?

### ISSUE THREAD

**Issue by DenisBiondic** [Azure/azure-cli#9965]
Our automation scripts are failing because the command no longer supports a --subscription parameter. We need this functionality to automate resources in multiple subscriptions at the same time.

**Comment by tjprescott** [comment]
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/_params.py#L481

Looks like this is the source of the problem. Looks like lines 481 and 482 can simply be removed, as the remainder of DNS commands accept subscription.

**Comment by MyronFanQiu** [comment]
@DenisBiondic It seems that in order to support another feature, so the `--subscription` parameter was suppressed. Since the other feature is not related with the `az network dns record-set ns create`, I move this suppression into lower scope to solve your issue.
