### ISSUE TITLE
az policy assignment create having issues assigning initatives

### ISSUE THREAD

**Issue by mistertwoturbo** [Azure/azure-cli#9966]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

I'm trying to assign a pre-built Azure policy, more specifically an initiative to my resource group, however I am unable to do so. 

**To Reproduce**

If I run:

az policy assignment create --name 'Enable Monitor for VMs' --scope 'Pay-As-You-Go/slyResourceGroup' --policy '/providers/Microsoft.Authorization/policySetDefinitions/55f3eceb-5573-4f18-9695-226972c6d74a' 

I get the error: 

The client 'steve@xxx.com' with object id 'xxxxxx' does not have authorization to perform action 'Microsoft.Authorization/policyDefinitions/Microsoft.Authorization/55f3eceb-5573-4f18-9695-226972c6d74a/read' over scope '/providers/Microsoft.Authorization/policyDefinitions/providers/Microsoft.Authorization/policySetDefinitions'.

**Expected behavior**

I'd expect that the command would assign the policy to the resource group of the account for which I'm signed into. 

**Environment summary**

Workstation Stats:
RHEL x86_64 GNU/Linux
Azure CLI version 2.0.68
Python 2.7.5

**Additional context**

Policy Name: [Preview]: Enable Azure Monitor for VMs
Policy ID: 55f3eceb-5573-4f18-9695-226972c6d74a
Description: Azure Initiative consisting of 87 separate policies
Policy Set Definition: /providers/Microsoft.Authorization/policySetDefinitions/55f3eceb-5573-4f18-9695-226972c6d74a
Subscription: xxxxxx
Scope: 'Pay-As-You-Go/slyResourceGroup'
Name: Enable Monitor for VMs

**Comment by AmanGarg-MSFT** [comment]
I have answered this question here:

https://social.msdn.microsoft.com/Forums/en-US/52c54ee7-542d-40c7-9a83-2a0b43200cf8/az-policy-assignment-create-issues?forum=azurescripting

**Comment by yugangw-msft** [comment]
@AmanGarg-MSFT, thank you!

**Comment by sozercan** [comment]
Ran into this issue also, solved it by specifying just the policy ID (not fully qualified resource ID). So it looks something like `az policy assignment create --policy 1a5b4dca-0b6f-4cf5-907c-56316bc1bf3d ...`
