### ISSUE TITLE
Problems authenticating as a service principal (with a key/certificate) using azurecli on macos

### ISSUE THREAD

**Issue by alanold** [Azure/azure-cli#9970]
## Describe the bug

**Command Name**
`az login`

**Errors:**
```
[('PEM routines', 'PEM_read_bio', 'no start line')]
Traceback (most recent call last):
python3.7/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 566, in execute
    raise ex
cli/core/commands/__init__.py, ln 624, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 617, in _run_job
    six.reraise(*sys.exc_info())
...
azure/cli/core/_profile.py, ln 1020, in __init__
    cert = load_certificate(FILETYPE_PEM, self.cert_file_string)
python3.7/site-packages/OpenSSL/crypto.py, ln 1837, in load_certificate
    _raise_current_error()
python3.7/site-packages/OpenSSL/_util.py, ln 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.crypto.Error: [('PEM routines', 'PEM_read_bio', 'no start line')]
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

create self signed cert using these instructions
* openssl genrsa -out cert.pem 2048
* openssl req -new -x509 -key cert.pem -out cert.cer -days 30
* openssl pkcs12 -export -out cert.pfx -inkey cert.pem -in cert.cer

create service principle in Azure AD, assign appropriate role.  upload cert.cer (public key) to the service principle
From directory containing certs on local mac.
- `az login --service-principal --username {} --tenant {} --password ./cert.pem`

## Expected Behavior
should sign in per article
https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest
(section 'Sign in using a service principal')

## Environment Summary
```
Darwin-18.6.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.67 *

Extensions:
resource-graph 0.1.11
subscription 0.1.3

```
## Additional Context

above command creates python errors.  if you @ the path to the pem file it runs but still errors.  This is the debug

$ az login --service-principal --username c53d1bd6-799c-4da2-ad95-6b3170c508c4 --tenant 8e8b2939-7a7b-4edd-8140-2262ffcd2b7c --password @fwsync.pem --debug
Command arguments: ['login', '--service-principal', '--username', 'c53d1bd6-799c-4da2-ad95-6b3170c508c4', '--tenant', '8e8b2939-7a7b-4edd-8140-2262ffcd2b7c', '--password', '@fwsync.pem', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x102d296a8>, <function OutputProducer.on_global_arguments at 0x102daf620>, <function CLIQuery.on_global_arguments at 0x102dc6268>]
attempting to read file fwsync.pem as utf-8-sig
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'maps', 'monitor', 'natgateway', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
Loaded module 'acr' in 0.007 seconds.
Loaded module 'acs' in 0.006 seconds.
Loaded module 'advisor' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.008 seconds.
Loaded module 'appservice' in 0.028 seconds.
Loaded module 'backup' in 0.004 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.012 seconds.
Loaded module 'batchai' in 0.004 seconds.
Loaded module 'billing' in 0.003 seconds.
Loaded module 'botservice' in 0.004 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.004 seconds.
Loaded module 'cloud' in 0.004 seconds.
Loaded module 'cognitiveservices' in 0.003 seconds.
Loaded module 'configure' in 0.003 seconds.
Loaded module 'consumption' in 0.005 seconds.
Loaded module 'container' in 0.003 seconds.
Loaded module 'cosmosdb' in 0.005 seconds.
Loaded module 'deploymentmanager' in 0.003 seconds.
Loaded module 'dla' in 0.006 seconds.
Loaded module 'dls' in 0.004 seconds.
Loaded module 'dms' in 0.003 seconds.
Loaded module 'eventgrid' in 0.004 seconds.
Loaded module 'eventhubs' in 0.006 seconds.
Loaded module 'extension' in 0.002 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.002 seconds.
Loaded module 'hdinsight' in 0.004 seconds.
Loaded module 'interactive' in 0.002 seconds.
Loaded module 'iot' in 0.008 seconds.
Loaded module 'iotcentral' in 0.003 seconds.
Loaded module 'keyvault' in 0.008 seconds.
Loaded module 'kusto' in 0.004 seconds.
Loaded module 'lab' in 0.005 seconds.
Loaded module 'maps' in 0.003 seconds.
Loaded module 'monitor' in 0.007 seconds.
Loaded module 'natgateway' in 0.003 seconds.
Loaded module 'network' in 0.031 seconds.
Loaded module 'policyinsights' in 0.003 seconds.
Loaded module 'privatedns' in 0.006 seconds.
Loaded module 'profile' in 0.002 seconds.
Loaded module 'rdbms' in 0.007 seconds.
Loaded module 'redis' in 0.003 seconds.
Loaded module 'relay' in 0.004 seconds.
Loaded module 'reservations' in 0.003 seconds.
Loaded module 'resource' in 0.008 seconds.
Loaded module 'role' in 0.008 seconds.
Loaded module 'search' in 0.003 seconds.
Loaded module 'security' in 0.004 seconds.
Loaded module 'servicebus' in 0.007 seconds.
Loaded module 'servicefabric' in 0.003 seconds.
Loaded module 'signalr' in 0.003 seconds.
Loaded module 'sql' in 0.008 seconds.
Loaded module 'sqlvm' in 0.004 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.035 seconds.
Loaded module 'vm' in 0.021 seconds.
Loaded all modules in 0.346 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: '/Users/apo20176/.azure/cliextensions'
Found 2 extensions: ['resource-graph', 'subscription']
Extensions directory: '/Users/apo20176/.azure/cliextensions'
Extension compatibility result: is_compatible=True cli_core_version=2.0.67 min_required=2.0.45 max_required=None
Extensions directory: '/Users/apo20176/.azure/cliextensions'
Loaded extension 'resource-graph' in 0.005 seconds.
Extensions directory: '/Users/apo20176/.azure/cliextensions'
Extension compatibility result: is_compatible=True cli_core_version=2.0.67 min_required=None max_required=None
Extensions directory: '/Users/apo20176/.azure/cliextensions'
Loaded extension 'subscription' in 0.007 seconds.
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x102e5a1e0>]
az_command_data_logger : command args: login --service-principal --username {} --tenant {} --password {} --debug
metadata file logging enabled - writing logs to '/Users/apo20176/.azure/commands'.
Event: CommandInvoker.OnPostCommandTableCreate [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x102e81048>, <function register_ids_argument.<locals>.add_ids_arguments at 0x102eae840>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x102eae9d8>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x103de3510>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x102daf6a8>, <function CLIQuery.handle_query_parameter at 0x102dc62f0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x102eae8c8>, <function handler at 0x103f0e9d8>]
attempting to read file /Users/apo20176/.azure/accessTokens.json as utf-8-sig
adal-python : 63a4b95b-a859-4dd2-940e-ebd1485629b6 - Authority:Performing instance discovery: ...
adal-python : 63a4b95b-a859-4dd2-940e-ebd1485629b6 - Authority:Performing static instance discovery
adal-python : 63a4b95b-a859-4dd2-940e-ebd1485629b6 - Authority:Authority validated via static instance discovery
adal-python : 63a4b95b-a859-4dd2-940e-ebd1485629b6 - TokenRequest:Getting token with client credentials.
adal-python : 63a4b95b-a859-4dd2-940e-ebd1485629b6 - TokenRequest:No user_id passed for cache query
adal-python : 63a4b95b-a859-4dd2-940e-ebd1485629b6 - CacheDriver:finding with query keys: {'_clientId': '...'}
adal-python : 63a4b95b-a859-4dd2-940e-ebd1485629b6 - CacheDriver:Looking for potential cache entries: {'_clientId': '...'}
adal-python : 63a4b95b-a859-4dd2-940e-ebd1485629b6 - CacheDriver:Found 0 potential entries.
urllib3.connectionpool : Starting new HTTPS connection (1): login.chinacloudapi.cn:443
urllib3.connectionpool : https://login.chinacloudapi.cn:443 "POST /8e8b2939-7a7b-4edd-8140-2262ffcd2b7c/oauth2/token HTTP/1.1" 401 404
cli.azure.cli.core.util : Get Token request returned http error: 401 and server response: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: de4fdf87-a29e-43c2-846f-4234427f3100\r\nCorrelation ID: 63a4b95b-a859-4dd2-940e-ebd1485629b6\r\nTimestamp: 2019-07-18 08:25:05Z","error_codes":[7000215],"timestamp":"2019-07-18 08:25:05Z","trace_id":"de4fdf87-a29e-43c2-846f-4234427f3100","correlation_id":"63a4b95b-a859-4dd2-940e-ebd1485629b6"}
Get Token request returned http error: 401 and server response: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: de4fdf87-a29e-43c2-846f-4234427f3100\r\nCorrelation ID: 63a4b95b-a859-4dd2-940e-ebd1485629b6\r\nTimestamp: 2019-07-18 08:25:05Z","error_codes":[7000215],"timestamp":"2019-07-18 08:25:05Z","trace_id":"de4fdf87-a29e-43c2-846f-4234427f3100","correlation_id":"63a4b95b-a859-4dd2-940e-ebd1485629b6"}
az_command_data_logger : exit code: 1
telemetry.save : Save telemetry record of length 2562 in cache
telemetry.check : Returns Positive.
telemetry.main : Begin creating telemetry upload process.
telemetry.process : Creating upload process: "/usr/local/Cellar/azure-cli/2.0.67/libexec/bin/python /usr/local/Cellar/azure-cli/2.0.67/libexec/lib/python3.7/site-packages/azure/cli/telemetry/__init__.py /Users/apo20176/.azure"
telemetry.process : Return from creating process
telemetry.main : Finish creating telemetry upload process.
command ran in 3.248 seconds.

**Comment by yugangw-msft** [comment]
@alanold, the pem file has to be in a particular format which is to include both the key and the public cert(for calculating the thumbprint). Please use the command of `az ad sp create-for-rbac  --create-cert` to produce a sample service principle with the certificate and then inspect the file content to understand the format.
Meanwhile, I will keep the issue open for us to fix the uncaught exception.
