### ISSUE TITLE
Missing support for subnet-id when creating a volume with netappfiles

### ISSUE THREAD

**Issue by edwardsp** [Azure/azure-cli#9971]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Previously a subnet id could be used when creating volumes when it was an extension.  Since being moved to the main cli this is not available.  The impact here is that I cannot create a volume in a separate resource group to where the vnet is located.

**To Reproduce**
az netappfiles volume create --resource-group <volume-resource-group> --vnet <vname-name> --subnet <subnet-name> ...

This will fail unless the vnet is in the same resource group as the netappfiles.  

**Expected behavior**
An option for --subnet-id is specified for other commands when the vnet is in a different resource group.

**Environment summary**
Linux latest azure-cli.

**Additional context**
It works in the portal.

**Comment by edwardsp** [comment]
This is where the subnet-id is generated in the azure cli.  Here is it wrong to assume the resource_group also applies to the vnet:

* https://github.com/Azure/azure-cli/blob/20a25fff6775e5dbc8d7ecae1c037426a25a927a/src/azure-cli/azure/cli/command_modules/netappfiles/custom.py#L93

**Comment by tjprescott** [comment]
If you want a VNET or subnet that are in different resource groups, you need to supply the ARM ID. That is the standard convention in the CLI. If that doesn't work, please reopen.

**Comment by edwardsp** [comment]
Reopening as there is no support for the full subnet-id.
