### ISSUE TITLE
Missing support for subnet-id when creating a volume with netappfiles (reopening)

### ISSUE THREAD

**Issue by edwardsp** [Azure/azure-cli#9976]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Previously a subnet id could be used when creating volumes when it was an extension.  Since being moved to the main cli this is not available.  The impact here is that I cannot create a volume in a separate resource group to where the vnet is located.

**To Reproduce**
az netappfiles volume create --resource-group <volume-resource-group> --vnet <vname-name> --subnet <subnet-name> ...

This will fail unless the vnet is in the same resource group as the netappfiles.  

**Expected behavior**
An option for --subnet-id is specified for other commands when the vnet is in a different resource group.

**Environment summary**
Linux latest azure-cli.

**Additional context**
It works in the portal.

This is where the subnet-id is generated in the azure cli.  Here is it wrong to assume the resource_group also applies to the vnet:

https://github.com/Azure/azure-cli/blob/20a25fff6775e5dbc8d7ecae1c037426a25a927a/src/azure-cli/azure/cli/command_modules/netappfiles/custom.py#L93

**Comment by tjprescott** [comment]
@leonardbf `--subnet` should accept a name or ID. Same with `--vnet`. I assumed this was already the case since otherwise the conventional naming of these arguments would be `--subnet` and `--vnet-name`. 
https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#supporting-name-or-id-parameters

**Comment by leonardbf** [comment]
> @leonardbf `--subnet` should accept a name or ID. Same with `--vnet`. I assumed this was already the case since otherwise the conventional naming of these arguments would be `--subnet` and `--vnet-name`.
> https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#supporting-name-or-id-parameters

@tjprescott ok, I will provide an update

**Comment by leonardbf** [comment]
@tjprescott Fixed with https://github.com/Azure/azure-cli/pull/10058

**Comment by edwardsp** [comment]
From looking at the commit I can't see this fixing the issue where a vnet can be in a different resource group to ANF.  All this patch does is extract the subnet from the string and build a new subnet_id with the resource group that is passed to it.

Also, if you specify a subnet id you could also extract the vnet from it - you wouldn't need to also specify it.

**Comment by leonardbf** [comment]
@tjprescott I know this is now a couple of months old but I think it has resurfaced in a new ticket (ANF-464 JIRA). What is your feeling on the comments above? Was the change not sufficient to address the problem or does it just require alternative usage?

**Comment by tjprescott** [comment]
While I'm no longer on the CLI team, I would say that you shouldn't accept an ID just to extract a name and then rebuild an ID, as @edwardsp suggests. If the ID is provided, you should accept it as-is. This would cover the situation where the subnet RG is different from the ANF RG.

cc/ @yonzhan

**Comment by yonzhan** [comment]
netappfiles

**Comment by audunn** [comment]
Stale issue
