### ISSUE TITLE
Certificate create policy parameter

### ISSUE THREAD

**Issue by kamil-mrzyglod** [Azure/azure-cli#9977]
I find the -p/--policy parameter for `az keyvault certificate create` a little bit misleading - it suggests, that if I want to load policy from a file, I should use @{file}. You can clearly miss the concept here as initially, you want to use @{my-policy.json} syntax instead of @my-policy.json. Extending the hint would help in proper usage of the command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9c661d7-bf43-5354-015e-3859f30a42a2
* Version Independent ID: fa69e552-5904-ce97-d02c-915c819bdde1
* Content: [az keyvault certificate](https://docs.microsoft.com/en-us/cli/azure/keyvault/certificate?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/keyvault/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/keyvault/_help.py)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yugangw-msft** [comment]
Fixed by #9999
