### ISSUE TITLE
az webapp up

### ISSUE THREAD

**Issue by zentekpoolsystem** [Azure/azure-cli#9979]
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
list index out of range
Traceback (most recent call last):
Temp\pip-install-qdpilz60\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 578, in execute
azure\cli\core\commands\__init__.py, ln 636, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 627, in _run_job
azure\cli\command_modules\appservice\commands.py, ln 55, in _polish_bad_errors
azure\cli\core\commands\__init__.py, ln 606, in _run_job
azure\cli\core\commands\__init__.py, ln 305, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 485, in default_command_handler
azure\cli\command_modules\appservice\custom.py, ln 2441, in webapp_up
azure\cli\command_modules\appservice\_create_util.py, ln 66, in get_runtime_version_details
azure\cli\command_modules\appservice\_create_util.py, ln 207, in parse_node_version
IndexError: list index out of range
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up --name {}`

## Environment Summary
```
Windows-10-10.0.16299-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.69

```

**Comment by panchagnula** [comment]
@zentekpoolsystem thanks for reporting this. Looking at the details seems like this is a node app with package.json & seems like we have an issue parsing the package.json to get the node version.

Can you share your package.json here? Also, in order to workaround this if your code has index.js or server.js file you can delete the package.json & the command will work to create & deploy a node app.
Hope this helps. 

https://github.com/Azure/azure-cli/blob/01aa37ae89865155bf3745fe28f2388c6c4f290d/src/azure-cli/azure/cli/command_modules/appservice/_create_util.py#L130

**Comment by zentekpoolsystem** [comment]
@panchagnula  Thanks. This is my package.json:
{
  "name": "zepra_diagram",
  "version": "1.0.0",
  "main": "server/server.js",
  "engines": {
    "node": ">=4"
  },
  "scripts": {
    "test": "mocha",
    "lint": "eslint .",
    "start": "node .",
    "scheduler": "node server/cron.js"
  },
  "dependencies": {
    "bcrypt": "^3.0.6",
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "date-fns": "^1.30.1",
    "helmet": "^3.15.0",
    "loopback": "^3.0.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^6.3.1",
    "node-schedule": "^1.3.2",
    "serve-favicon": "^2.0.1",
    "strong-error-handler": "^2.0.0",
    "strong-soap": "^1.18.0"
  },
  "devDependencies": {
    "chai": "^4.2.0",
    "eslint": "^3.17.1",
    "eslint-config-loopback": "^8.0.0",
    "eslint-config-prettier": "^4.1.0",
    "eslint-plugin-prettier": "^3.0.1",
    "mocha": "^6.1.4",
    "node-fetch": "^2.3.0",
    "nsp": "^3.2.1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/zentekpoolsystem/ZepraDiagram.git"
  },
  "eslintConfig": {
    "parserOptions": {
      "ecmaVersion": 2017
    },
    "env": {
      "es6": true
    }
  },
  "prettier": {
    "singleQuote": true,
    "trailingComma": "es5",
    "overrides": [
      {
        "files": "app/**/*.js",
        "options": {
          "singleQuote": false,
          "trailingComma": "none"
        }
      }
    ]
  },
  "license": "MIT",
  "description": "ZepraDiagram"
}

**Comment by panchagnula** [comment]
@zentekpoolsystem  thanks for sharing for now update the node version in your package.json to '4.0' from 4 , so this one

"engines": {
"node": ">=4.0"
} this will fix it, i am adding error-handling for this.
