### ISSUE TITLE
[Storage] Support downloading multiple blobs/files with a single call

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#998]
Since blob names allow slashes to simulate directories for organizational purposes, it would be nice if we could download multiple blobs by specifying a prefix (ex: CreateVM_2016-07-01*). This would require the downloaded file name to default as described in issue #995.

For files, you would download multiple files not by specifying a file prefix (although you could), but by specifying the directory path.

**Comment by tjprescott** [comment]
@troydai also related to what you are currently working on.

**Comment by hcd00045** [comment]
I think I'm very interested in this feature. I have a bash script that downloads about 200 files (400MB) from a blob "folder" via the Azure CLI. Currently I do this by getting a list of the matching blobs and then piping them to "xargs -n1 azure storage blob download...". In all, it takes about 15 minutes, and it seems like a lot of the time is spent in the overhead of making the calls. Would this feature improve that timing?

**Comment by tjprescott** [comment]
It should improve the timing, as well as the simplicity of not having to manually send things through xargs.

**Comment by mayurid** [comment]
@hcd00045 : This is in progress right now and we will have something for you to try in the upcoming sprints and will keep you posted. Hoping you will be willing to give it try and give us feedback.

**Comment by tjprescott** [comment]
PR #1432 is merged, so please give this command a try: `az storage blob download-batch`.

**Comment by tjprescott** [comment]
When #1462 is merged this can be closed.

**Comment by hcd00045** [comment]
Hi guys! I am just seeing this message now. I will gladly give this a try and report back if there are any issues. Thanks!
