### ISSUE TITLE
How to set useCommonAlertSchema to true

### ISSUE THREAD

**Issue by pmaaren** [Azure/azure-cli#9980]
I’m using the Azure cli to create an action group with the email action where the useCommonAlertSchema is set to true. So far, I’m unsuccessful. Can you please add a description how to accomplish this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c03d4ff4-4752-4ed4-2f6c-312ff3fd9fd8
* Version Independent ID: 822e4b3b-4079-9a88-2525-715c8d4ea90a
* Content: [az monitor action-group](https://docs.microsoft.com/en-us/cli/azure/monitor/action-group?view=azure-cli-latest#feedback)
* Content Source: [src/azure-cli/azure/cli/command_modules/monitor/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/monitor/_help.py)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jonathandbyrd** [comment]
it's a bit of a hack but it works...

az monitor action-group update --name <enter-name-of-action-group-to-update> --set emailReceivers[0].useCommonAlertSchema=true --resource-group <enter-your-resource-group>

**Comment by pmaaren** [comment]
Hi jonathandbyrd, I have tried your solution and it works for me despite the warning message.

Thanks for your help.
