### ISSUE TITLE
Update Azure cli library to add support for VMSS Plan name update

### ISSUE THREAD

**Issue by Petermarcu** [Azure/azure-cli#9981]
@SamRakaba commented on [Fri Jul 19 2019](https://github.com/Azure/azure-sdk/issues/519)

When creating an Redhat custom image, the plan information meta data is not carried with the image. if we are creating a scale set and use custom image with one plan and attempt to update to new image, the Plan information can only be done through ARM PATCH verb.
can we add support  for "Az vmss update " command

**Comment by Petermarcu** [comment]
Thanks for reporting this issue. @yugangw-msft, can you take a look?

**Comment by yugangw-msft** [comment]
@SamRakaba, I might need more information from you, but let me try to understand:
1. To confirm, I assume you are not updating the base image; rather just like to update the plan name, correct?
2. Even a custom image doesn't capture the plan information, when you create a VM/VMSS from it, you can always supply the right plan information, which is what I would suggest you do.
3. Once the VM/VMSS was created, you can always use `az vmss update` to tweak lots of things; however, I don't think you can update the plan. I assume you have tried and got a failure? If that is the reason you propose the `ARM PATCH`, then I would suggest the command of `az rest` which you can use to send out any arbitrary request payload

**Comment by yugangw-msft** [comment]
@SamRakaba, please feel free to reactivate with more information.
