### ISSUE TITLE
webapp:Specify default timeout , which is not stated clearly in docs

### ISSUE THREAD

**Issue by jstallm** [Azure/azure-cli#9984]
I can see that timeout is available as a parameter here
https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/source?view=azure-cli-latest#az-webapp-deployment-source-config-zip

But nothing states the default timeout. Can you please update the docs here
https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/source?view=azure-cli-latest#az-webapp-deployment-source-config-zip

to include the timeout default? This would clear up any confusion regarding what timeout we can expect, without passing a custom value as a param.

**Comment by panchagnula** [comment]
Unfortunately there is no default time out we can share here - the timeout is a big  concern if you are doing a BUILD operation along with your deployment.  The deplpyment operation itself is async  (will continue to happen on the background )& CLI command line exists checking the status after 10 attempts & returns an error message.

We have seen that for customers who have either requested BUILD following a deployment with a large # of packages - all the timeout does is that the command keeps checking for the status of the deployment without existing the operation.

**Comment by panchagnula** [comment]
Closing  this question
