### ISSUE TITLE
I want Azure CLI to be able to create Monitor Alert rules for all subscriptions at once.

### ISSUE THREAD

**Issue by naqash11** [Azure/azure-cli#9989]
I am trying to create Azure Monitor log alerts using Azure CLI for all subscriptions. I can create rules for only one subscription but i want to replicate it to other subscriptions too. Specifically, i am creating alerts for Storage, VM and Resource Group.

Please help me achieving this.

**Comment by naqash11** [comment]
I do not think it can be done for all subscriptions at once because we have other parameters to handle as well like Resource Groups and Action Groups. I have created the alerts using CLI by just changing the subid and action groups in the command.

**Comment by tjprescott** [comment]
It cannot be done. The service calls create resources that are subscription-specific. Best case, you can write a script that will loop through all of your subscriptions and create the necessary alerts.
