### ISSUE TITLE
az vm image list -o table

### ISSUE THREAD

**Issue by chetanpisal** [Azure/azure-cli#9990]
## Describe the bug

**Command Name**
`az vm image list`

**Errors:**
```
HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')])")))
Traceback (most recent call last):
site-packages/urllib3/contrib/pyopenssl.py, ln 456, in wrap_socket
    cnx.do_handshake()
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az vm image list -o {}`

## Environment Summary
```
Darwin-18.6.0-x86_64-i386-64bit
Python 3.7.3
Shell: bash

azure-cli 2.0.67
azure-cli-ml 1.0.45.1

Extensions:
azure-cli-ml 1.0.45.1
interactive 0.4.3

```

**Comment by zikalino** [comment]
@chetanpisal is this error occurring consistently for you?

This problem could be similar to described in following article:

https://blog.jhnr.ch/2018/05/16/working-with-azure-cli-behind-ssl-intercepting-proxy-server/

**Comment by yugangw-msft** [comment]
Agreed with @zikalino. On top of his suggestion, CLI also has a [doc](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#working-behind-a-proxy) for this.
