### ISSUE TITLE
Log configuration settings are not respected

### ISSUE THREAD

**Issue by wrosenuance** [Azure/azure-cli#9991]
## Describe the bug

According to [the documentation](https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration), it should be possible to disable all logging in the Azure CLI by editing the `$AZURE_CONFIG_DIR/config` file or running `az configure` and answering no when prompted.

However, the setting in the configuration file is no longer respected, seemingly as of commit [86385e6452f03ad8952ea64cdd63622b6a45c921](https://github.com/Azure/azure-cli/commit/86385e6452f03ad8952ea64cdd63622b6a45c921#diff-5d2413def69bb36d10122cca306870af), which replaced the check. Subsequent refactorings of this module further disabled any possibility for disabling logs, in favor of an unconfigurable log rotation option.

The Azure CLI should respect the `logging.enable_log_file=false` setting and avoid all logging if specified.

## To Reproduce:
- Run `az configure` and select the option to disable file logging.
- Clear `$AZURE_CONFIG_DIR/commands` to clean all existing log files.
- Run `az account show` or any other CLI command
- Observe log files are still created under `$AZURE_CONFIG_DIR/commands`

## Expected Behavior
Log files should not be created if `$AZURE_CONFIG_DIR/config` sets `enable_log_file=false` in the `[logging]` section.

## Environment Summary
```
Linux-3.10.0-693.21.1.el7.x86_64-x86_64-with-centos-7.4.1708-Core
Python 2.7.5
Shell: bash

azure-cli 2.0.69
```

**Comment by yugangw-msft** [comment]
The files under `$AZURE_CONFIG_DIR/commands` contain information for people to report issue/suggestion through `az feedback`, and are not related with logging to file

**Comment by yugangw-msft** [comment]
Closing. Please let us know if you have any further questions.

**Comment by wrosenuance** [comment]
Is there any way to avoid having these files created?

**Comment by SetTrend** [comment]
@yugangw-msft: I have the same question:

Is there a way to have Azure CLI automatically purge all the files in `$AZURE_CONFIG_DIR/commands` older than, say, a week?

**Comment by jiasli** [comment]
Contents in `$AZURE_CONFIG_DIR/commands` are indeed automatically purged. These files are used for `az feedback`.

https://github.com/Azure/azure-cli/blob/bae390c813d7df0eb49f3c1d1128848aca26e81a/src/azure-cli-core/azure/cli/core/azlogging.py#L66-L82
