### ISSUE TITLE
Remove 'sourceAddressPrefix' key and keep 'sourceAddressPrefixes'

### ISSUE THREAD

**Issue by saccy** [Azure/azure-cli#9993]
If there is only one source address present on the NSG rule it will present under the 'sourceAddressPrefix' key, otherwise if there is > 1 source there will be a list under 'sourceAddressPrefixes' key. 

I suggest consolidating to 'sourceAddressPrefixes' and making it possible to have a list of 1 to make it easier when automating.

example data with one source address on an nsg rule:
```
  "sourceAddressPrefix": "10.141.51.38",
  "sourceAddressPrefixes": [],
```

example data with > 1 source addresses on an nsg rule:
```
  "sourceAddressPrefix": "",
  "sourceAddressPrefixes": [
    "10.141.51.38",
    "10.141.51.37"
  ],
```

**Comment by yugangw-msft** [comment]
@tjprescott, any comments?
/CC @MyronFanQiu

**Comment by MyronFanQiu** [comment]
@saccy I think your suggestion is good. I checked the `network nsg rule list` and `network nsg rule show` commands. They just return the service's response. @tjprescott Is it proper for us to adjust the response?

**Comment by tjprescott** [comment]
@saccy is correct, but we are hamstrung by the service design here, because there are instances where you *must* use the singular property.

**Comment by anavinahar** [comment]
Hi folks, this feedback is definitely valid, however, this would be considered a breaking change by few customers. We haven't yet planned for this change.

**Comment by anavinahar** [comment]
#please-close
