### ISSUE TITLE
`az feedback` is confused when no web browser is available

### ISSUE THREAD

**Issue by Huge** [Azure/azure-cli#9998]
**Describe the bug**
`az feedback` doesn't work without a browser and doesn't acknowledge that. 

**To Reproduce**
`docker run -it microsoft/azure-cli`
`...`
`az feedback`
says "**A browser has been opened to aka.ms/azcli/issues to create an issue.**" which is false.

**Expected behavior**
Detect whether a browser is available and inform accordingly. Could do something like the `az login` does there. 

**Environment summary**
Install Method: Docker
CLI version: latest;  2.0.69

**Comment by yugangw-msft** [comment]
Add `feedback` specific label
